### ISSUE TITLE
[extension_google_sign_in_as_googleapis_auth] can't use this library with the new google_sign_in library

### ISSUE THREAD

**Issue by rosenpin** [flutter/flutter#121165]
I've been using both `extension_google_sign_in_as_googleapis_auth` and `google_sign_in` in my app.  
Since the breaking change to both `google_sign_in` and `google_sign_in_web` I need to update the dependencies to 6.0.0 and 0.11.0 respectively.  
Unfortunately it seems like this library depends on older, soon to be deprecated versions of those libraries.  
Is there an update planned soon?   

Here is the build log:
```
Running "flutter pub get" in Goals...                           
Because extension_google_sign_in_as_googleapis_auth 2.0.7 depends on google_sign_in ^5.0.0 and no versions of extension_google_sign_in_as_googleapis_auth match >2.0.7 <3.0.0, extension_google_sign_in_as_googleapis_auth ^2.0.7 requires google_sign_in ^5.0.0.
So, because goals_for_google_calendar depends on both google_sign_in ^6.0.0 and extension_google_sign_in_as_googleapis_auth ^2.0.7, version solving failed.
pub get failed (1; So, because goals_for_google_calendar depends on both google_sign_in ^6.0.0 and extension_google_sign_in_as_googleapis_auth ^2.0.7, version solving failed.)
Process finished with exit code 1
```

**Comment by stuartmorgan** [comment]
@ditman Can we just widen the dependency here to include both major versions?

**Comment by ditman** [comment]
> @ditman Can we just widen the dependency here to include both major versions?

Yes, and I think this would even continue working! Let me prepare a quick PR.

**Comment by ditman** [comment]
Posted PR: https://github.com/flutter/packages/pull/3235
