### ISSUE TITLE
[impeller scene] Expose VertexBuffer[Builder] to Dart.

### ISSUE THREAD

**Issue by xclud** [flutter/flutter#121169]
Exposing VertexBuffer and VertexBufferBuilder as defined in `impeller/renderer/vertex_buffer_builder.h` will enable more 3D uses for Flutter. Developers should not be limited to the "skinned" and "not-skinned" vertex types.

## Use case

To enable developers to create custom meshes. Useful for game development.

## Proposal

I would be happy to submit a PR.

**Comment by chinmaygarde** [comment]
We are working on a more generic way of exposing this functionality to Dart. cc @bdero to xref any issues he knows of. Closing this.
