### ISSUE TITLE
Would you update the version of WebView plugin on version 3.x?

### ISSUE THREAD

**Issue by firstmetcs** [flutter/flutter#121141]
I'm working with flutter 2.5.3 with my app, there are some new feature updated with version 4.x, but the min dart SDK required by  the latest version is 2.17, I'm not planning to upgrade my flutter version recently, so maybe I can get a solution here. Thanks a lot!!!

**Comment by stuartmorgan** [comment]
The Flutter team only maintains the latest version of its packages.
