### ISSUE TITLE
Error running flutter run, doctor or any flutter command "Error: Unable to find git in your PATH."

### ISSUE THREAD

**Issue by Neeraj029** [flutter/flutter#121192]
## Steps to Reproduce

But no doubt I actually do have git in the path, but it still throw the error ` Error: Unable to find git in your PATH. `
Flutter version: 3.7.3
Windows 10 64 bit

Steps to reproduce
1. run any flutter command and it throws that error

## Logs

![image](https://user-images.githubusercontent.com/66945520/220533111-2dc17d00-bd2d-4fe4-9ef0-dd7f0ee58b2c.png)

<details>
<summary>Logs</summary>

```
```
 Error: Unable to find git in your PATH. 

```
```

</details>

**Comment by Neeraj029** [comment]
I have tried adding C:\Windows\System32 to path, reinstalling, adding git to path. I guess this issue is from flutter side?

**Comment by abinvs-2019** [comment]
Can you show your `flutter --doctor -v` here.

**Comment by Neeraj029** [comment]
> flutter --doctor -v

![image](https://user-images.githubusercontent.com/66945520/220544133-b0860f84-b128-4a7c-ab38-8063b02fdae4.png)

**Comment by exaby73** [comment]
Hello @Neeraj029. What's the output of `git --version`? Also, what is the installation location of your Flutter installation and git installation? Are they both in your `C:` drive?

**Comment by Neeraj029** [comment]
> Hello @Neeraj029. What's the output of `git --version`? Also, what is the installation location of your Flutter installation and git installation? Are they both in your `C:` drive?

> git --version
gir version 2.39.2.windows.1

And only flutter is in C: not git

**Comment by liscanso** [comment]
Hi.

I had the same issue.
First, I thought that was because I was playing with channels, so, deleted the flutter folder and clone it again.
All worked correctly after that.
But, if you want to figure out, what's going on, that message is located at (example): C:\flutter\bin\internal\shared.bat
Note the flutter and git path to test the script (powershell).

get-command -name @("flutter", "git")
$env:FLUTTER_ROOT = "C:\flutter or wharever it is"
& "$env:FLUTTER_ROOT\bin\internal\shared.bat"
write-output $?

You should not see any error message.
The last output must be "True".
If something fail, you can debug the script shared.bat to delimit the cause in your installation.

**Comment by exaby73** [comment]
@Neeraj029 Try moving `git` to `C:` as well. This is a know issue with Windows where programs installed on different drives do not have permission to access other drives

**Comment by Neeraj029** [comment]
> @Neeraj029 Try moving `git` to `C:` as well. This is a know issue with Windows where programs installed on different drives do not have permission to access other drives

Sorry for misunderstanding, I meant flutter is in C: root and git is in different directory in C: drive itself. 
Both are in same drive.

**Comment by exaby73** [comment]
Have you tried the steps highlighted in https://github.com/flutter/flutter/issues/15047? and https://github.com/flutter/flutter/issues/12129?

**Comment by Neeraj029** [comment]
> Have you tried the steps highlighted in #15047? and #12129?

Yeah tried that already, didn't work. 
But what I did is, I opened up the shared.bat file in flutter/bin/internal and check where it throws the error `Error: Unable to find git in your PATH.`. and I saw that it runs git rev-parse HEAD command in root of flutter, so I ran the command manually and found that I was getting an error 
```
C:/flutter' is owned by:
        'S-1-5-21-140910783-400654637-2112822741-1001'
but the current user is:
        'S-1-5-21-757521687-79357024-253676287-1001'
To add an exception for this directory, call:
        git config --global --add safe.directory C:/flutter
```

Ran `git config --global --add safe.directory C:/flutter` andddd IT"S finally fixed! 🥳

Thanks @exaby73, @liscanso & @abinvs-2019 for your help!
