### ISSUE TITLE
unbundling dependencies from engine (distro packaging)

### ISSUE THREAD

**Issue by selfisekai** [flutter/flutter#121106]
## Use case

packaging flutter for distributions (I'm a contributor to Alpine Linux, currently working on packaging flutter), following best practices and guidelines.

a bit more explanation from chromium team: https://chromium.googlesource.com/chromium/src/build/+/refs/heads/main/linux/unbundle/README

**this is not related to platform compatibility** as in "it builds and runs successfully" (for musl-related problems see my other issue, #124285). this is related to platform compatibility as in "distribution packaging standards" - for packaging flutter as a tool available within distribution's repositories, for packaging end-user apps written using flutter.

**the proposed workflow is entirely opt-in, and does not interfere with any developer workflows or production environments**. it is to optionally replace gn files in tree on machine.

**this is not an officially supported workflow**. issues coming from this workflow always have a solution of "do not unbundle this library", and otherwise fall under one of these categories:
1. "skill issue",
2. "fix it yourself",
3. "wait for someone else to fix this".

## Proposal

port analogical solutions from chromium:
- tool for replacing normal gn build files with unbundle ones, for use in such environments (engine already had it for gyp, but it doesn't use gyp anymore)
- shim headers

libraries to support in this workflow:
- [ ] freetype2 (https://github.com/flutter/buildroot/pull/687)
- [ ] fontconfig (https://github.com/flutter/buildroot/pull/687)
- [ ] harfbuzz (https://github.com/flutter/buildroot/pull/687)
- [ ] icu (https://github.com/flutter/buildroot/pull/687)
- [ ] libjpeg/libjpeg-turbo
- [ ] libpng (https://github.com/flutter/buildroot/pull/687)
- [ ] libwebp
- [ ] libxml
- [ ] sqlite (https://github.com/flutter/buildroot/pull/687)
- [ ] zlib (https://github.com/flutter/buildroot/pull/687)

some of this is specific to flutter engine, some is shared with dart (namely, zlib) - what to do here? should I backport the shared ones to dart later? should the replacement build files be in a repository shared with dart?

**Comment by stuartmorgan** [comment]
> packaging flutter for distributions (I'm a contributor to Alpine Linux, currently working on packaging flutter)

What's the use case here exactly? Unlike Chromium, the output of an engine build isn't a direct end-user product, and unlike a standard library isn't versioned for general-purpose use; an application built with the Flutter SDK has to be shipped with the exact corresponding version of the engine.

Is the goal here to ship a forked copy of the Flutter SDK itself that produces applications that use non-bundled, forked engine builds?

**Comment by selfisekai** [comment]
the framework and tool are versioned, and have a [corresponding engine revision](https://github.com/flutter/flutter/blob/master/bin/internal/engine.version) that they depend on. the builds of engine are used for building a flutter app, and some parts are copied over to app builds (`libflutter_linux_gtk.so`)

the goal is to package the build tools, to then use them for building (and packaging) flutter desktop apps.

"forked copy of the Flutter SDK" is IMO an overstatement here. all the patches for framework/tool I needed to build a desktop app are a few lines of diff (not counting engine patches), a few more will be needed to fix e.g. "unknown channel" in flutter doctor. you can see my work so far here, if you're interested: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/44347/diffs

**Comment by stuartmorgan** [comment]
> "forked copy of the Flutter SDK" is IMO an overstatement here

All I meant was an altered distribution of the SDK (in particular, the tool), so it sounds like the answer is yes.

**Comment by adenilsoncavalcanti** [comment]
You may want to rethink the idea of dropping Chromium zlib.

It is a highly optimized fork of zlib using SIMD instructions on x86 and Arm.

For further info, check:
https://docs.google.com/presentation/d/1_XWLhF4FcTz_HGc4QqvVapkxMj2-QTOZNdyXvpy2oYU/edit?usp=sharing
https://docs.google.com/presentation/d/1-sNwEtudmblPKuoIR-Skls3j7NMO24G1BG9Si_1JWrI/edit?usp=sharing

If anything, I'm seriously considering removing support for 'use_system_zlib', as there are no good reasons (performance or security) to use something else.

To quote the discussion (https://chromium-review.googlesource.com/c/chromium/src/+/947464): "I wouldn't recommend running Chromium against a zlib that is not third_party/zlib.".

**Comment by adenilsoncavalcanti** [comment]
So basically by using a system zlib, the following would be slowed down in Flutter: PNG decoding, accessing compressed web content (content-encoding: gzip), WebSockets, loading V8 snapshots, hashing (crc32/adler32) and many more.

Chromium zlib is used by V8, Skia, Angle, PDFium, AOSP and probably more.

**Comment by adenilsoncavalcanti** [comment]
Even if you don't care about performance, from a security perspective would be a bad idea:
https://docs.google.com/presentation/d/1GNCnusHEVFY3vuqVMUh1b6fqo212T0HYkYSVe3f3CPw/edit?usp=sharing&resourcekey=0-8_xbWFtMBBLM60NoZwUtnQ

**Comment by selfisekai** [comment]
I don't feel like writing the same so I'll just copy a bit from reply on equivalent issue in dart: https://github.com/dart-lang/sdk/issues/51535#issuecomment-1507523795

>it dynamically links a dependency from the system, which allows upgrades (and potential security fixes, etc) independently without requiring any rebuilds for reverse dependencies. [...]
>
>now you could say something like 'well, zlib updates with chromium, which itself updates fairly often, etc', but that still requires a rebuild of the entirety of chromium (on my machine this is about 4 hours without cache) if potentially someone immediately had to release a security fix for the zlib in question.
>
>that's also assuming that 'system zlib' here is actually 'canonical zlib'. i think in the coming years we will see something like zlib-ng take priority for /usr/lib/libz.so.1 over the canonical. but you can't actually know what is there! it is just a preference for dynamic linking, not necessarily "remove the google code".

**Comment by adenilsoncavalcanti** [comment]
It seems the issue you are trying to solve is related to compilation time, perhaps Goma could help here:
https://chromium.googlesource.com/infra/goma/client/+/HEAD/doc/early-access-guide.md

**Comment by dnfield** [comment]
We can't do this.

Most of these libraries do not provide stable ABI. And Flutter does not guarantee that it plays nicely - sometimes we use private API even though we're not supposed to.

If you arbitrarily change the versions of these dependencies, you could get anything from reduced performance to completely broken/crashing binaries.

**Comment by dnfield** [comment]
(for example, we track Chromium's fork of zlib specifically because it has fixes for crashes we've observed in upstream zlib)

**Comment by chinmaygarde** [comment]
Closing this as wont-fix per @dnfield s [comment](https://github.com/flutter/flutter/issues/121106#issuecomment-1541192332).
