### ISSUE TITLE
Codelab for Animated-Responsive-Layout - Step 4 wget Error

### ISSUE THREAD

**Issue by Avasond** [flutter/flutter#121265]
Pulls page HTML and gives it the .png extension instead of pulling the image. This may be user error but I noticed there was a 301 error and thought it may have affected the function.

Code that fails:

> `for name in avatar_1 avatar_2 avatar_3 avatar_4 \
>               avatar_5 avatar_6 avatar_7 thumbnail_1; \
>   do wget \
>     https://github.com/flutter/codelabs/tree/main/animated-responsive-layout/step_04/assets/$name.png ; \
>   done`

Code that solved the issue for me:

> `for name in avatar_1 avatar_2 avatar_3 avatar_4 \
>               avatar_5 avatar_6 avatar_7 thumbnail_1; \
>   do wget \
>    https://raw.githubusercontent.com/flutter/codelabs/main/animated-responsive-layout/step_04/assets/$name.png ; \
>   done`

Again, this may just be an environment issue on my end but wget was otherwise working.

**Comment by darshankawar** [comment]
codelab link: https://codelabs.developers.google.com/codelabs/flutter-animated-responsive-layout#0

/cc @domesticmouse

**Comment by domesticmouse** [comment]
Update in progress.

Googlers: cl/511925608

**Comment by domesticmouse** [comment]
This should now be fixed.
