### ISSUE TITLE
Unable to find git in your PATH IntelliJ

### ISSUE THREAD

**Issue by KameronBueckendorf** [flutter/flutter#12129]
I started a project in IntelliJ from command line and created it successfully. When I go into IntelliJ file\settings\Languages and select Flutter to set Flutter SDK path it gives me error: Unable to find git in your PATH

c:\>flutter doctor
[√] Flutter (on Microsoft Windows [Version 10.0.15063], locale en-US, channel alpha)
    • Flutter at C:\Flutter
    • Framework revision 701d534ba9 (3 days ago), 2017-09-12 14:01:51 -0700
    • Engine revision 31d03de019
    • Tools Dart version 1.25.0-dev.11.0

[√] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at C:\Users\Kameron\AppData\Local\Android\sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] IntelliJ IDEA Ultimate Edition (version 2017.2)
    • Flutter plugin version 17.0
    • Dart plugin version 172.4155.35

[√] Connected devices
    • None

Flutter doctor output above

**Comment by acaliaro** [comment]
I have the same problem... a solution?

**Comment by tenhobi** [comment]
Same issue.

**Comment by zameerrig** [comment]
Have the same problem. Any update on this?

**Comment by tenhobi** [comment]
@zameerrig I do not know exactly what fixed this, but I did update my Flutter, add all things to PATH etc. and it started to work. Also I reinstalled the git for windows app and updated the PATH variable.

**Comment by zameerrig** [comment]
@tenhobi Thanks for the update. Yes, it is the problem with PATH variable in flutter.bat file. After setting the GIT in PATH system environment variables(Windows machine), I need to restart my system to work it.

**Comment by abhay2smart** [comment]
same issue

**Comment by zoechi** [comment]
Please check also the discussions in #15047 and #16591

**Comment by zoechi** [comment]
Is this still an issue?

**Comment by djwind** [comment]
Before install flutter, I have already  installed git. After install flutter and run "flutter doctor", I got the same issue.Then I noticed that this directory("XXX\flutter\bin\mingit\cmd") contains a "git.exe".
So I tried to comment these two lines of code in the file of "XXX\flutter\bin\flutter.bat", then the command of "flutter doctor" works.
![image](https://user-images.githubusercontent.com/3746553/51224922-30b3a300-1983-11e9-99d9-23d6a90544f1.png)

I don't know if there are other side effects.

**Comment by arias01** [comment]
> Before install flutter, I have already installed git. After install flutter and run "flutter doctor", I got the same issue.Then I noticed that this directory("XXX\flutter\bin\mingit\cmd") contains a "git.exe".
> So I tried to comment these two lines of code in the file of "XXX\flutter\bin\flutter.bat", then the command of "flutter doctor" works.
> ![image](https://user-images.githubusercontent.com/3746553/51224922-30b3a300-1983-11e9-99d9-23d6a90544f1.png)
> 
> I don't know if there are other side effects.

Perfect

**Comment by apabhishek2002** [comment]
> Before install flutter, I have already installed git. After install flutter and run "flutter doctor", I got the same issue.Then I noticed that this directory("XXX\flutter\bin\mingit\cmd") contains a "git.exe".
> So I tried to comment these two lines of code in the file of "XXX\flutter\bin\flutter.bat", then the command of "flutter doctor" works.
> ![image](https://user-images.githubusercontent.com/3746553/51224922-30b3a300-1983-11e9-99d9-23d6a90544f1.png)
> 
> I don't know if there are other side effects.

my problem got solved! thanks!

**Comment by fatibellafkih** [comment]
My problem got solved too thank you
