### ISSUE TITLE
Unexpected view of BottomNavigationBar

### ISSUE THREAD

**Issue by 0xff00ff** [flutter/flutter#121290]
I have unexpected behavior of BottomNavigationBar
Here is an [example](https://dartpad.dev/?id=d5b2f2cb024bf31e0d60ecc1e21ded46)
The colors of BottomNavigationBarItems are white (foreground and background), foreground colors should be black
If you comment the 46 line (or any other BottomNavigationBarItem) view will be changed to expected.

Is that normal behavior? How it should be changed to default without setting the exact color?

**Comment by znromonk** [comment]
@0xff00ff If you have three items in the nav bar, Flutter defaults to a `fixed` nav bar type. That is why you are seeing the icon and label colors. If you have four or more items, the default type is `shifting`. The default colors are white unless specified by user. You can find this in the docs for [`BottomNavigationBar`](https://api.flutter.dev/flutter/material/BottomNavigationBar-class.html).

If you do not want a shifting nav bar, which is used when each item has different colors (although you could still have same color), you can specify `type: BottomNavigationBarType.fixed`.

>[BottomNavigationBarType.shifting](https://api.flutter.dev/flutter/material/BottomNavigationBarType.html), the default when there are four or more [items](https://api.flutter.dev/flutter/material/BottomNavigationBar/items.html). If [selectedItemColor](https://api.flutter.dev/flutter/material/BottomNavigationBar/selectedItemColor.html) is null, all items are rendered in white. The navigation bar's background color is the same as the [BottomNavigationBarItem.backgroundColor](https://api.flutter.dev/flutter/widgets/BottomNavigationBarItem/backgroundColor.html) of the selected item. In this case it's assumed that each item will have a different background color and that background color will contrast well with white.

**Comment by danagbemava-nc** [comment]
Hi @0xff00ff, as noted above, this is the expected behavior

I am closing this as this is the documented behavior. 

Thank you

**Comment by 0xff00ff** [comment]
thank you, i should better read the documentation
