### ISSUE TITLE
[Timeline Dashboard] Correctly blame user widgets for missed frames.

### ISSUE THREAD

**Issue by B3rn475** [flutter/flutter#12124]
The new Timeline Dashboard shows a logical view allowing the developer to identify missed frames.
![pastedimage0](https://user-images.githubusercontent.com/2686902/30506406-833897da-9a30-11e7-9520-581fad672652.png)

At the moment it is possible to blame against Dart code.
Due to the sample based nature of the Dart VM profiling the number of available samples is reduced.
Also the samples tend to hit Framework internals because all the Layout phase manages objects that are not implemented by the final Developer.

It would be interesting to correctly blame both the build and layout time against the widgets that are causing it and not to the layout code itself.

**Comment by Hixie** [comment]
@rmacnak-google What repo is the right repo for this issue?
