### ISSUE TITLE
[pigeon] Pigeon example invocation should mention experimental_kotlin_out flag

### ISSUE THREAD

**Issue by paolorotolo** [flutter/flutter#121238]
The example of running Pigeon available [here](https://github.com/flutter/packages/blob/main/packages/pigeon/example/README.md), mentions that Swift and Kotlin generation are experimental.

A flag for Swift generation is included in the example (`experimental_swift_out`), but Kotlin ones are not. Moreover, I couldn't find the exact name for the experimental Kotlin generation flag without looking at Pigeon's source code. In fact, the section [Swift / Kotlin Plugin Example ](https://github.com/flutter/packages/blob/main/packages/pigeon/example/README.md#swift--kotlin-plugin-example) links an example project that still hasn't the Kotlin flag in its [run_pigeon.sh](https://github.com/gaaclarke/pigeon_plugin_example/blob/master/run_pigeon.sh).

**Comment by danagbemava-nc** [comment]
Closing this since https://github.com/flutter/packages/pull/3260 has been merged
