### ISSUE TITLE
[Memory Dashboard] Add selection for different time windows in graph

### ISSUE THREAD

**Issue by B3rn475** [flutter/flutter#12122]
Currently in the Flutter Observatory Memory Dashboard the graph samples are fixed at a 2 minutes window, everything outside that window is dropped.

It would be interesting to store samples indefinitely and allow the developer to:
- Choose the size of the window (1 minute, 2 minutes, 5 minutes, 10 minutes, 20 minutes, ...).
- See old values by moving the window back in time.

![carlo s jam 1](https://user-images.githubusercontent.com/2686902/30506195-cd61149c-9a2e-11e7-922d-a67aaf6401aa.png)

**Comment by zoechi** [comment]
@Hixie what is the reason you removed the observatory label? (there were a few others where you did this) Looks like it's about Observatory. (don't know how to triage)

**Comment by Hixie** [comment]
@zoechi It was part of an effort to clean up our labels. There were very few things with that label so I removed the label from our list of labels. Really this probably belongs in the IDE issue list? cc @devoncarew

**Comment by devoncarew** [comment]
I think we'll still want something like this, but likely done as an enhancement to the VM's service protocol. Perhaps best to re-purpose, and instead track at the sdk repo.
