### ISSUE TITLE
Truncate large doubles to FLT_MAX instead of infinity (or instead of relying on UB)

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#121299]
__EDIT__:

The real problem here is that when the engine gets a very large positive/negative double, it is implicitly converted to a float (`SkScalar`/`impeller::Scalar`) and more often than not converted to `inf` or `-inf`. This results in transformation matrices or offsets that are unexpectedly infinite. In some parts of the engine, these matrices are discarded and replaced with an identity matrix; in others, it puts the rendering state into sadness.

There are a few ways we could try to fix this:

- Turn off implicit float conversion. I like this idea but it requires updating a large swathe of the codebase.
- Try to update Tonic so that it does this for us. This is probably easier to do, but will be very unfortunate if we ever _actually_ want a double from Dart and get something clamped to float. We also have to make sure if we explicitly get `double.infinity` (or nan/-inf for that matter) from Dart we keep it. We could probably have a special dart converter that you have to opt into when you want a full precision double. I did try something sort of like this by using Chromium's `StrictNumeric`, but that basically affects as much of the codebase as just turning on `-Wno-implicit-float-conversion`.
- Update the Matrix conversion code. This gets some codepaths but not all of them. We also see this for things that aren't matrices, like offsets or scales on the canvas/paths.

__Original issue__:

Today, the engine does a sanity check on transform matrices here: https://github.com/flutter/engine/blob/4c6c259bad0e2939b9a4a63bf957c3e33a0ae4e6/flow/layers/transform_layer.cc#L24 and then just uses identity if it's not.

This can happen if people make mistakes that result in infinity or NaN in their matrices, or it can happen if their 64-bit `Matrix4` in the framework exceeds the max value of the 32-bit floats used in `SkMatrix` or `SkM44` in the Engine.

We should assert higher up in the stack (specifically, in Dart code) that this doesn't happen.

Something like

```dart
    assert(
      _lastEffectiveTransform!.storage.every((double component) => component.isFinite && component.abs() < 3.40282e+38),
      'The matrix\n'
      '$_lastEffectiveTransform\n'
      'contains at least one component which is either not finite or larger '
      'than 3.40282e+38.',
    );
```

Would work. @Hixie was suggesting adding this as a public API to dart:ui that could be called from the framework. Another option is to add it as private API in dart:ui and just call it in places where we're handing a matrix to native.

**Comment by dnfield** [comment]
I encountered this issue looking at an application that has custom code for panning and zooming that is (unintentionally?) allowing for _very_ large zoom values when pinch zooming, which exceed the max 32 bit float value.

**Comment by dnfield** [comment]
I think the real fix here is to avoid truncating to infinity.

**Comment by dnfield** [comment]
After some investigation today, I've learned we have this problem in a lot of places.

Basically we do implicit conversions from double to float all over the place in the native backings of dart:ui. In every place that we do this, we can end up with an overflow to infinity.

Matrix conversion (whether to SkMatrix, SkM44, or impeller::Matrix) happens in numerous places as well, and all of them are using implicit double to float conversion which can result in this kind of overflow.

I think the right solution here is to turn on `-Wno-implicit-float-conversion` and fix up all the call sites, but that's turning into a larger effor tthan I anticipated. Going to sleep on this.

**Comment by dnfield** [comment]
I was hoping we coudl try something like Chromium's `StrictNumeric`, but the typed data wrapper is really just a thin wrapper around access to an array and I'm not sure we want to make that an array of `StrictNumeric`s since I'm pretty sure that'd introduce some runtime overhead in what should really be a compile time check.

**Comment by dnfield** [comment]
Something that feels hacky would be to specialize `Float64List::at` to return a double that always fits into a float. That would probably work for our matrix cases but it wouldn't work for other places where we're directly taking in doubles and implicitly converting them to floats.

**Comment by cmkweber** [comment]
FWIW - I have come across this loss of precision at high zoom levels where the canvas transform is smooth during panning, but a path appears to be jumping, but I haven’t had a chance yet to make a small reproducible.

**Comment by dnfield** [comment]
The specific bug I'm seeing is when you have a value in a transform (or anything expecting a double in dart:ui more or less) that is greater than can fit into a 32 bit float. At that point it gets converted to infinity (or -infinity) and things go bad.
