### ISSUE TITLE
Autosubmit merging more than one PR at a time?

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#121295]
It seems that the `autosubmit` bot is merging more than one PR at a time, for example in `flutter/packages` it has just merged these two PRs with a couple of minutes of difference:

* https://github.com/flutter/packages/pull/3235 (at 4:10 PM PST)
* https://github.com/flutter/packages/pull/2730 (at 4:11 PM PST)

Verification tests for both pushes are now running (in parallel) in the flutter/packages CI:

* https://github.com/flutter/packages/runs/11535474358
* https://github.com/flutter/packages/runs/11535387980

Is this a feature of autosubmit that it detects that the PRs are unrelated? Or should it only merge one PR at a time?

<img width="685" alt="Screenshot 2023-02-22 at 4 23 22 PM" src="https://user-images.githubusercontent.com/1255594/220794556-82666c3c-7dc8-4b19-872e-4cd505015e22.png">

**Comment by godofredoc** [comment]
This is working as intended, the auto-submit app can land multiples PRs at the same time as long as they are approved and tests have completed successfully.

**Comment by ditman** [comment]
@godofredoc ah, this is great news. Thanks for the clarification! I don't know why I thought the autosubmit would land one at a time. Closing!
