### ISSUE TITLE
[Timeline Dashboard]

### ISSUE THREAD

**Issue by B3rn475** [flutter/flutter#12125]
Due to its new Frame based layout the Timeline Dashboard is no more about "time" itself.
Which should be the correct name to refer to this page?

Proposals:
- `Frameline Browser` @lukechurch
-  `Timeline View` @devoncarew
- `Performance` @devoncarew

**Comment by Hixie** [comment]
@B3rn475 This seems like the wrong repo for this bug, but I'm not sure where it should go?

**Comment by devoncarew** [comment]
I'll close this; we're generally tracking this work over at flutter/devtools.
