### ISSUE TITLE
[Web] Scrolling issue with Telegram Web Apps for Bots

### ISSUE THREAD

**Issue by NelepovDmitry** [flutter/flutter#121264]
## Steps to Reproduce

1. Execute `flutter build web` or flutter run` on the code sample 
2. Create Telegram Web App
3. Deploy
4. Try to Scroll

**Expected results:**
Scroll works fine

**Actual results:** 
While finger touches the screen, all fine. But then try scroll down, seems that scroll offset sets to 0, and then scrolling app closing

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const ScrollAppExample());
}

class ScrollAppExample extends StatelessWidget {
  const ScrollAppExample({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Scroll bug App',
      home: Container(
        color: Colors.black,
        child: ListView.separated(
          itemBuilder: (context, index) => Container(
            padding: const EdgeInsets.all(32),
            color: Colors.blue[200 + index % 4 * 100],
            child: Text(
              'Item $index',
              style: const TextStyle(
                color: Colors.white,
                fontSize: 14,
              ),
            ),
          ),
          separatorBuilder: (context, index) => const SizedBox(
            height: 32,
          ),
          itemCount: 100,
        ),
      ),
    );
  }
}

```

</details>

<details>
Here video example
![flutter_scroll_bug](https://user-images.githubusercontent.com/1499945/220738643-2f827455-e38c-49df-b9b1-5b0de1b96e10.gif)

At first I thought that this was a Telegram problem, but I made a simple HTML page with a DIV with scrolling, and everything worked correctly there. 

</details>

**Comment by NelepovDmitry** [comment]
https://user-images.githubusercontent.com/1499945/220739484-2798c1bc-dff5-4617-b7e4-4be523280bd5.MP4

**Comment by NelepovDmitry** [comment]
And also.
Yes, i try build canvaskit, try build html. 
Same results.

**Comment by huycozy** [comment]
Hi @NelepovDmitry 
I'm not quite familiar with Telegram Web Apps. Can you be more specific on `Steps to reproduce`? (adding steps to deploy to Telegram Web Apps would be helpful)

And from your demo video, it seems the Telegram page (which contains the Flutter listview) works as a [DraggableScrollableSheet](https://api.flutter.dev/flutter/widgets/DraggableScrollableSheet-class.html). Is that possible to try reproducing this issue with this widget only?

Also, which Flutter version are you using? Please provide the output of `flutter doctor -v` as well. Thanks!

**Comment by NelepovDmitry** [comment]
### Telegram Flutter scrolling bug
**Platforms - Android & iOS**

**Steps to reproduce**

1. Create Flutter app with a simple ListView (like ListView.builder for example)
2. Deploy it on any host (or for test use https://todo.hubitproject.com/flutter_bug_ck)
3. Create Telegram bot
3.1. Open Telegram bot father @BotFather
3.2. Type /newbot
3.3. Enter a unique name
3.3. Enter a unique bot login
3.4. Type /setmenubutton
3.5. Enter a path to flutter app from step 2 (or for test use https://todo.hubitproject.com/flutter_bug_ck)
3.6. Enter button name, for example "Test Flutter"
4. Open bot from Mobile device
5. Tap button from step 3.6
6. Expand Web App to fullscreen by dragging topbar part of webapp
7. Try scroll up (finger move up) and down (finger move down)

**Expected result**
Scroll works correctly

**Actual result**
Scrolling down is close telegram web app

Complete code of app deployed  at https://todo.hubitproject.com/flutter_bug_ck
```
import 'dart:math';

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const HomeScreen(),
    );
  }
}

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView.separated(
          itemBuilder: (context, index) {
            return Container(
              padding: const EdgeInsets.all(32),
              color: Color.fromARGB(
                255,
                Random().nextInt(255),
                Random().nextInt(255),
                Random().nextInt(255),
              ),
              child: Text('Item $index'),
            );
          },
          separatorBuilder: (context, index) {
            return const SizedBox(
              height: 32,
            );
          },
          itemCount: 100),
    );
  }
}

```

**flutter doctor -v result**
```
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-arm, locale en-RU)
    • Flutter version 3.3.10 on channel stable at /Users/rain/Dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (2 months ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/rain/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 72.0.4
    • Dart plugin version 223.8617.8

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.1 22C65 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by NelepovDmitry** [comment]
> Hi @NelepovDmitry I'm not quite familiar with Telegram Web Apps. Can you be more specific on `Steps to reproduce`? (adding steps to deploy to Telegram Web Apps would be helpful)
> 
> And from your demo video, it seems the Telegram page (which contains the Flutter listview) works as a [DraggableScrollableSheet](https://api.flutter.dev/flutter/widgets/DraggableScrollableSheet-class.html). Is that possible to try reproducing this issue with this widget only?
> 
> Also, which Flutter version are you using? Please provide the output of `flutter doctor -v` as well. Thanks!

Try with [DraggableScrollableSheet](https://api.flutter.dev/flutter/widgets/DraggableScrollableSheet-class.html).

Same thing.

**Comment by huycozy** [comment]
Thanks for the detailed `Steps to reproduce`, I can reproduce the issue now (on the latest Flutter stable and master channels). 

### Issue analysis
- On iOS: The sheet containing the Web is gradually collapsed even though the list has not been scrolled to the top.
- On Android: It seems the issue is also happening on Android as the web is not dismissed when pulling down from the top position (the 1st item). This works normally on the below demo with [github.com](https://github.com/) website.
- When testing this with [github.com](https://github.com/) site, it works as expected on both Android and iOS
- It seems the issue is caused by the conflict between Telegram's sheet gesture and Flutter web's ListView gesture.

    <img width="400" src="https://user-images.githubusercontent.com/104349824/221505476-6b968694-a276-4e56-a77e-bb7ef5542391.png">

### Demo

<details>
<summary>Demo issue (Android + iOS)</summary>

| iOS | Android |
| --------------- | --------------- |
<video src="https://user-images.githubusercontent.com/104349824/221505893-946011b3-0658-45c3-9301-4290e749f569.MP4"/> | <video src="https://user-images.githubusercontent.com/104349824/221505918-46920c40-5ca8-482f-bc1b-aea1d556a7b4.mp4"/>

</details>

<details>
<summary>Demo (Expected result with github.com site)</summary>

| iOS | Android |
| --------------- | --------------- |
<video src="https://user-images.githubusercontent.com/104349824/221506267-9729619c-ff5e-4ed5-b669-63b6ba32c6fe.MP4"/> | <video src="https://user-images.githubusercontent.com/104349824/221506244-1e863d8a-06ec-45ec-a6eb-490d6036aa24.mp4"/>

</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.7.5, on macOS 13.0.1 22A400 darwin-x64, locale en-EE)
    • Flutter version 3.7.5 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c07f788888 (5 hours ago), 2023-02-22 17:52:33 -0600
    • Engine revision 0f359063c4
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Users/huynq/Library/Java/JavaVirtualMachines/corretto-1.8.0_302/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Corretto-8.302.08.1 (build 1.8.0_302-b08)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 110.0.5481.100

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```bash
[!] Flutter (Channel master, 3.8.0-16.0.pre.57, on macOS 13.0.1 22A400 darwin-x64, locale en-EE)
    • Flutter version 3.8.0-16.0.pre.57 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 45723adf4d (2 hours ago), 2023-02-26 23:35:37 -0500
    • Engine revision 88b48c357b
    • Dart version 3.0.0 (build 3.0.0-275.0.dev)
    • DevTools version 2.22.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (4 available)
    • Pixel 3a (mobile) • 964AY0WL20 • android-arm64  • Android 12 (API 32)
    • macOS (desktop)   • macos      • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 110.0.5481.100

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

Labeling the issue for further insights.

@NelepovDmitry I update the title (for Android issue as above analysis). If you disagree, please write in the comments.

**Comment by yjbanov** [comment]
We've heard similar problems with other app-specific webviews (IIRC Instagram's built-in browser does this too). My best guess is those browsers use the swipe gesture to dismiss the browser tab, but they can't tell if the swipe is used by the web app for anything other than native HTML scrolling. So they just check "is it scrolling some HTML content?", and if not initiate the swipe-away gesture. I think it is poor user experience when browsers do that, because they have to ignore the use-cases of some web apps. Not every finger drag means scrolling. What they should provide is a "Close" button to close the view, but they want to look fancy and do it via gestures. But it's not something we can influence. A workaround is to use a scrollable HTML wrapper for scrolling root-level content. See discussions in https://github.com/flutter/flutter/issues/77883, which I'm going to deduplicate this issue into as this would be solved by the other.
