### ISSUE TITLE
[tool_crash] _CastError: (#0      HotRunner._resetDirtyAssets (package:flutter_tools/src/run_hot.dart:497:20))

### ISSUE THREAD

**Issue by atmikbharat** [flutter/flutter#121207]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_CastError: (#0      HotRunner._resetDirtyAssets (package:flutter_tools/src/run_hot.dart:497:20))
```
#0      HotRunner._resetDirtyAssets (package:flutter_tools/src/run_hot.dart:497:20)
#1      HotRunner._restartFromSources (package:flutter_tools/src/run_hot.dart:565:5)
<asynchronous suspension>
#2      HotRunner._fullRestartHelper (package:flutter_tools/src/run_hot.dart:754:16)
<asynchronous suspension>
#3      HotRunner.restart (package:flutter_tools/src/run_hot.dart:694:38)
<asynchronous suspension>
#4      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1699:40)
<asynchronous suspension>
#5      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1739:7)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.3.2, on Microsoft Windows [Version 10.0.21996.1], locale en-IN)
    • Flutter version 3.3.2 on channel stable at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (5 months ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\Atmik Bharat\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = C:\Users\Atmik Bharat\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.74.2)
    • VS Code at C:\Users\Atmik Bharat\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.54.0

[✓] Connected device (4 available)
    • Redmi Note 8 Pro (mobile) • oj6heemrqcw8dykn • android-arm64  • Android 11 (API 30)
    • Windows (desktop)         • windows          • windows-x64    • Microsoft Windows [Version 10.0.21996.1]
    • Chrome (web)              • chrome           • web-javascript • Google Chrome 110.0.5481.104
    • Edge (web)                • edge             • web-javascript • Microsoft Edge 110.0.1587.46
    ! Device oj6heemrqcw8dykn is offline.

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 676cefaaff197f27424942307668886253e1ec35
### Plugins
cloud_firestore-3.5.1
cloud_firestore_web-2.8.10
connectivity_plus-2.3.7
connectivity_plus_linux-1.3.1
connectivity_plus_macos-1.2.4
connectivity_plus_web-1.2.4
connectivity_plus_windows-1.2.2
file_picker-4.6.1
firebase_core-1.24.0
firebase_core_web-1.7.3
firebase_dynamic_links-4.3.11
flutter_plugin_android_lifecycle-2.0.7
flutter_sms_autofill-1.0.4
image_cropper-3.0.0
image_cropper_for_web-1.0.2
image_picker-0.8.6
image_picker_android-0.8.5+3
image_picker_for_web-2.1.8
image_picker_ios-0.8.6+1
onesignal_flutter-3.4.2
open_file-3.2.1
path_provider-2.0.11
path_provider_android-2.0.20
path_provider_ios-2.0.11
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.0.7
permission_handler-9.0.1
sqflite-2.1.0
url_launcher-6.1.6
url_launcher_android-6.0.19
url_launcher_ios-6.0.17
url_launcher_linux-3.0.1
url_launcher_macos-3.0.1
url_launcher_web-2.0.13
url_launcher_windows-3.0.1
video_player-2.4.7
video_player_android-2.3.9
video_player_avfoundation-2.3.7
video_player_web-2.0.12
webview_flutter-4.0.0
webview_flutter_android-3.1.1
webview_flutter_wkwebview-3.0.1

**Comment by christopherfujino** [comment]
I believe I already fixed this in https://github.com/flutter/flutter/pull/108771. That fix is not present in 3.3.2, I would recommend upgrading (we do not hotfix stable releases older than the current stable, which is currently 3.7.5, which has the fix).
