### ISSUE TITLE
[CP] fix crash during "flutter doctor --android-licenses" on macOS

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#121273]
### issue_link

https://github.com/flutter/flutter/issues/114031

### Commit Hash

https://github.com/flutter/flutter/commit/b8f5394a5ca6d2bce062d9d0a20aaffb4289fb4c & https://github.com/flutter/flutter/commit/1546fa08d3243f3d9401dfa0620231e7cb72ff67

### Target

stable

### pr_link

https://github.com/flutter/flutter/pull/120717

### Impacted Users

macOS users who run `yes | flutter doctor --android-licenses`

### Impact Description

once the sdkmanager sub-process finishes, users will get a cryptic `ArgumentError`, even though the accepting licenses may have succeeded.

### Workaround

The user could find the path on their disk to `sdkmanager` within the Android SDK, can invoke `yes | /path/to/sdkmanager --licenses`.

### Risk

low

### Test Coverage

yes

### Validation Steps

Issue `yes | flutter doctor --android-licenses` from a macOS host.

**Comment by christopherfujino** [comment]
requesting approval from @zanderso

**Comment by zanderso** [comment]
CP lgtm
