### ISSUE TITLE
Typo in "guestbook" at https://firebase.google.com/codelabs/firebase-get-to-know-flutter#5

### ISSUE THREAD

**Issue by gustavolramos** [flutter/flutter#121361]
As you can see in the image below the word is written as "gustbook" instead of "guestbook" in the tutorial. 

![image](https://user-images.githubusercontent.com/100650338/221019897-803d6f8d-09c9-4963-a246-fb6440086cc5.png)

**Comment by domesticmouse** [comment]
PTAL @ericwindmill
