### ISSUE TITLE
skp_generator didn't report completion status on presubmit run

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#121362]
In this presubmit check: https://github.com/flutter/flutter/pull/121186/checks?check_run_id=11536432110

The status appears to never have been reported to GitHub, so the check thinks it's still running, even though it [succeeded](https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20skp_generator/32046/overview) 18 hours ago.

Since it's still "running", I can't restart it, and re-running the job on LUCI didn't seem to force it to report, I'm going to push an empty commit to force all the tests to run again (which seems inefficient to do for the sake of a 3 minute test).

(Refer to https://github.com/flutter/flutter/pull/121186)

**Comment by gspencergoog** [comment]
Pushing an empty commit did solve this incident of the issue (at least skp_generator did report), but it would be good to know why it failed, and/or have a way to restart checks in that state.

**Comment by keyonghan** [comment]
Infra has submitted several fixes regarding check run logic. Please reopen if you see this issue again.
