### ISSUE TITLE
[Embedder API] Fix `FlutterEngineNotifyDisplayUpdate`'s ABI stability 

### ISSUE THREAD

**Issue by loic-sharma** [flutter/flutter#121352]
The embedder ABI must support full backward and forward compatibility. The engine receives an array of `FlutterEngineDisplay` from the embedder - the engine must not assume it receives the latest version the `FlutterEngineDisplay` struct here: https://github.com/flutter/engine/blob/4c6c259bad0e2939b9a4a63bf957c3e33a0ae4e6/shell/platform/embedder/embedder.cc#L2871-L2878

Instead, it should inspect the structs it receives and access elements/members safely. For example:  https://github.com/flutter/engine/blob/4c6c259bad0e2939b9a4a63bf957c3e33a0ae4e6/shell/platform/embedder/embedder.cc#L2120-L2121

**Comment by dnfield** [comment]
I have a local patch that fixes this in the process of implementing more display properties for macOS embedder.
