### ISSUE TITLE
Remove // comment from Info.plist in Flutter Firebase codelab.

### ISSUE THREAD

**Issue by truberCompany** [flutter/flutter#12134]
## Steps to Reproduce
I downloaded flutter + firebase demo from https://codelabs.developers.google.com/codelabs/flutter-firebase

I am getting following error while trying to run flutter on iOS simulator of iPhone SE
Launching lib/main.dart on iPhone SE in debug mode...
2017-09-09 08:34:17.555 defaults[30324:975026] 
The domain/default pair of (/Users/mac/IdeaProjects/friendlychat/ios/Runner/Info, CFBundleIdentifier) does not exist
No application found for TargetPlatform.ios.
Is your project missing an ios/Runner/Info.plist?
Consider running "flutter create ." to create one.

Here are screenshot of IntelliJ Idea CE 
![screenshot 2017-09-09 08 46 30](https://user-images.githubusercontent.com/24494124/30513492-d129fc80-9b21-11e7-9d3c-646024648462.png)
and screenshot of Info.plist file 
![screenshot 2017-09-12 08 14 53](https://user-images.githubusercontent.com/24494124/30513498-e82cc098-9b21-11e7-93e1-d43c71465335.png)

## Logs

Run your application with `flutter run` and attach all the log output.
[  +34 ms] [/Users/mac/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +54 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] [/Users/mac/flutter/] git ls-remote --get-url origin
[  +12 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [/Users/mac/flutter/] git log -n 1 --pretty=format:%H
[  +12 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] c46347b6df27abdb91b8b7c63e90255fefc86a6e
[        ] [/Users/mac/flutter/] git log -n 1 --pretty=format:%ar
[  +13 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 8 days ago
[ +957 ms] /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[ +211 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[        ] 2.3
[ +243 ms] Listing devices using /Users/mac/Library/Android/sdk/platform-tools/adb
[        ] /Users/mac/Library/Android/sdk/platform-tools/adb devices -l
[  +20 ms] Exit code 0 from: /Users/mac/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[   +8 ms] idevice_id -h
[ +319 ms] which ideviceinstaller
[   +5 ms] Exit code 0 from: which ideviceinstaller
[        ] /usr/local/bin/ideviceinstaller
[        ] which iproxy
[   +5 ms] Exit code 0 from: which iproxy
[        ] /usr/local/bin/iproxy
[        ] which ios-deploy
[   +5 ms] Exit code 0 from: which ios-deploy
[        ] /usr/local/bin/ios-deploy
[ +149 ms] /usr/bin/xcrun simctl list --json devices
[+1127 ms] Launching lib/main.dart on Aniket’s iPhone in debug mode...
[   +3 ms] /usr/bin/defaults read /Users/mac/IdeaProjects/friendlychat/ios/Runner/Info CFBundleIdentifier
[ +209 ms] Exit code 1 from: /usr/bin/defaults read /Users/mac/IdeaProjects/friendlychat/ios/Runner/Info CFBundleIdentifier
[  +24 ms] "flutter run" took 3,211ms.
[ +264 ms] ensureAnalyticsSent: 257ms
[   +1 ms] exiting with code 1

Run `flutter analyze` and attach any output of that command also.
[  +40 ms] [/Users/mac/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +58 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] [/Users/mac/flutter/] git ls-remote --get-url origin
[  +14 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [/Users/mac/flutter/] git log -n 1 --pretty=format:%H
[  +14 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] c46347b6df27abdb91b8b7c63e90255fefc86a6e
[        ] [/Users/mac/flutter/] git log -n 1 --pretty=format:%ar
[  +16 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 8 days ago
[ +491 ms] /Users/mac/flutter/bin/cache/dart-sdk/bin/dartanalyzer --packages /Users/mac/IdeaProjects/friendlychat/.packages /Users/mac/IdeaProjects/friendlychat
[ +367 ms] Analyzing /Users/mac/IdeaProjects/friendlychat...
[+9754 ms]   error • Target of URI doesn't exist: 'package:flutter_test/flutter_test.dart' at test/widget_test.dart:8:8 • uri_does_not_exist
[        ]   error • The function 'testWidgets' isn't defined at test/widget_test.dart:13:3 • undefined_function
[        ]   error • Undefined class 'WidgetTester' at test/widget_test.dart:13:49 • undefined_class
[        ]   error • Undefined class 'MyApp' at test/widget_test.dart:15:33 • undefined_class
[        ]   error • The function 'expect' isn't defined at test/widget_test.dart:18:5 • undefined_function
[        ]   error • Undefined name 'find' at test/widget_test.dart:18:12 • undefined_identifier
[        ]   error • Undefined name 'findsOneWidget' at test/widget_test.dart:18:28 • undefined_identifier
[        ]   error • The function 'expect' isn't defined at test/widget_test.dart:19:5 • undefined_function
[        ]   error • Undefined name 'find' at test/widget_test.dart:19:12 • undefined_identifier
[        ]   error • Undefined name 'findsNothing' at test/widget_test.dart:19:28 • undefined_identifier
[        ]   error • Undefined name 'find' at test/widget_test.dart:22:22 • undefined_identifier
[        ]   error • The function 'expect' isn't defined at test/widget_test.dart:26:5 • undefined_function
[        ]   error • Undefined name 'find' at test/widget_test.dart:26:12 • undefined_identifier
[        ]   error • Undefined name 'findsNothing' at test/widget_test.dart:26:28 • undefined_identifier
[        ]   error • The function 'expect' isn't defined at test/widget_test.dart:27:5 • undefined_function
[        ]   error • Undefined name 'find' at test/widget_test.dart:27:12 • undefined_identifier
[        ]   error • Undefined name 'findsOneWidget' at test/widget_test.dart:27:28 • undefined_identifier
[        ]   hint • The value of the local variable 'message' isn't used at lib/main.dart:106:17 • unused_local_variable
[        ]   hint • Unused import at test/widget_test.dart:10:8 • unused_import
[  +40 ms] 19 issues found.
[  +29 ms] "flutter analyze" took 10,596ms.
[ +139 ms] ensureAnalyticsSent: 130ms
[   +1 ms] exiting with code 3

## Flutter Doctor

Paste the output of running `flutter doctor` here.
[  +33 ms] [/Users/mac/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +63 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] [/Users/mac/flutter/] git ls-remote --get-url origin
[  +13 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [/Users/mac/flutter/] git log -n 1 --pretty=format:%H
[  +18 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] c46347b6df27abdb91b8b7c63e90255fefc86a6e
[        ] [/Users/mac/flutter/] git log -n 1 --pretty=format:%ar
[  +17 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 8 days ago
[+1068 ms] /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[ +204 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[        ] 2.3
[ +335 ms] [✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-IN, channel master)
[   +1 ms]     • Flutter at /Users/mac/flutter
[        ]     • Framework revision c46347b6df (8 days ago), 2017-09-07 22:52:36 -0700
[        ]     • Engine revision 2d7c30033d
[        ]     • Tools Dart version 1.25.0-dev.11.0
[ +659 ms] /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[ +220 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[        ] 2.3
[ +142 ms] java -version
[ +126 ms] [✓] Android toolchain - develop for Android devices (Android SDK 25.0.0)
[        ]     • Android SDK at /Users/mac/Library/Android/sdk
[        ]     • Platform android-24, build-tools 25.0.0
[        ]     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
[        ]     • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)
[+1252 ms] DevToolsSecurity -status
[  +82 ms] Developer mode is currently enabled.
[        ] python -c import six
[ +766 ms] idevice_id -h
[  +10 ms] idevice_id -l
[  +17 ms] 7b63ef0d6e292495dc89c77cee022e8e6389525a
[   +1 ms] idevicename
[ +185 ms] ideviceinstaller -h
[ +134 ms] ios-deploy --version
[  +55 ms] ios-deploy --version
[  +14 ms] 1.9.2
[   +5 ms] ios-deploy --version
[  +21 ms] ios-deploy --version
[  +39 ms] 1.9.2
[   +6 ms] pod --version
[+2642 ms] pod --version
[ +542 ms] 1.3.1
[   +3 ms] pod --version
[ +755 ms] 1.3.1
[   +1 ms] [✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
[        ]     • Xcode at /Applications/Xcode.app/Contents/Developer
[        ]     • Xcode 8.2.1, Build version 8C1002
[        ]     • ios-deploy 1.9.2
[        ]     • CocoaPods version 1.3.1
[   +2 ms] [✓] Android Studio (version 2.3)
[        ]     • Android Studio at /Applications/Android Studio.app/Contents
[        ]     • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)
[   +2 ms] /usr/bin/defaults read /Applications/IntelliJ IDEA CE.app/Contents/Info CFBundleShortVersionString
[ +238 ms] Exit code 0 from: /usr/bin/defaults read /Applications/IntelliJ IDEA CE.app/Contents/Info CFBundleShortVersionString
[        ] 2017.2.3
[ +205 ms] [✓] IntelliJ IDEA Community Edition (version 2017.2.3)
[        ]     • Flutter plugin version 17.0
[        ]     • Dart plugin version 172.3968.27
[   +7 ms] Listing devices using /Users/mac/Library/Android/sdk/platform-tools/adb
[        ] /Users/mac/Library/Android/sdk/platform-tools/adb devices -l
[  +20 ms] Exit code 0 from: /Users/mac/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[   +7 ms] idevice_id -h
[ +303 ms] which ideviceinstaller
[   +7 ms] Exit code 0 from: which ideviceinstaller
[        ] /usr/local/bin/ideviceinstaller
[        ] which iproxy
[   +5 ms] Exit code 0 from: which iproxy
[        ] /usr/local/bin/iproxy
[        ] which ios-deploy
[   +5 ms] Exit code 0 from: which ios-deploy
[        ] /usr/local/bin/ios-deploy
[   +4 ms] /usr/bin/xcrun simctl list --json devices
[ +159 ms] [✓] Connected devices
[        ]     • Aniket’s iPhone • 7b63ef0d6e292495dc89c77cee022e8e6389525a • ios • iOS 10.3.3
[  +32 ms] "flutter doctor" took 10,211ms.
[ +161 ms] ensureAnalyticsSent: 158ms
[   +1 ms] exiting with code 0

**Comment by collinjackson** [comment]
I think removing the `// Add the following entries to the <dict> tag in Info.plist` comment should fix it.

We should change this to a `<!-- ... -->` comment

**Comment by collinjackson** [comment]
I made this change in the codelab doc, @LarkAscending please review. No change to friendlychat-steps repo is necessary because the comment doesn't appear there.

**Comment by LarkAscending** [comment]
Yes, my bad. Fixed!
https://codelabs.developers.google.com/codelabs/flutter-firebase/index.html#5

**Comment by truberCompany** [comment]
Great, thanks
