### ISSUE TITLE
Update android triage documentation to replace 'plugins' with 'packages'

### ISSUE THREAD

**Issue by gmackall** [flutter/flutter#121357]
https://github.com/flutter/flutter/wiki/Triage#android

Update the above documentation.

Also consider making dependabot its own search criteria/category in triage.

**Comment by gmackall** [comment]
is:open draft:false is:pr label:platform-android sort:updated-asc -author:app/dependabot

**Comment by stuartmorgan** [comment]
FYI I did update the link as part of my docs sweep. I didn't change the link text since in practice it's going to be almost entirely plugins. (Technically package example apps could end up in that query, but that's it.)

**Comment by stuartmorgan** [comment]
>  -author:app/dependabot

Why exclude these? The fact that dependabot PRs get really stale and I have to ping people about them regularly has been an issue.

**Comment by gmackall** [comment]
> > -author:app/dependabot
> 
> Why exclude these? The fact that dependabot PRs get really stale and I have to ping people about them regularly has been an issue.

Sorry, made this in triage meeting and didn't add enough context. We aren't looking to exclude them, but to separate them so there is a section in our triage process for looking at dependabot PRs and a section for looking at non dependabot PRs. 

I just added that to save the filter for creating the non-dependabot section.

**Comment by gmackall** [comment]
I've changed the android triage template to have separate dependabot and non-dependabot pr links, and am leaving the link reading "plugins" on Stuarts suggestion above. 

Closing as there is nothing left to be done!
