### ISSUE TITLE
AR widgets

### ISSUE THREAD

**Issue by MukulKrSingh** [flutter/flutter#121312]
It would be cool to have AR widgets.

**Comment by darshankawar** [comment]
@MukulKrSingh 
Check out [this](https://flutter.dev/docs/resources/faq#can-i-build-3d-opengl-apps-with-flutter) link to know about Flutter's support for 3D models. You may also checkout [this](https://pub.dev/packages/arkit_plugin) plugin and [this](https://medium.com/codechai/flutter-and-ar-a65bb202c5d8) article for reference. Also see this related issue for further reference: https://github.com/flutter/flutter/issues/18509

Closing from here for now.
