### ISSUE TITLE
Is the firebase_analytics plugin used IDFA on iOS

### ISSUE THREAD

**Issue by txthinking** [flutter/flutter#12135]
I use the firebase plugin, and when I submit app to App Store, it ask me about IDFA whether used.
Should i check yes or no?

Thanks to Flutter.

**Comment by Hixie** [comment]
@collinjackson Something for some documentation maybe?

**Comment by collinjackson** [comment]
This is a general to Firebase and not really Flutter-specific, see firebase/quickstart-ios/issues/266

**Comment by kroikie** [comment]
@txthinking

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/967. Any further collaboration will be done there.
