### ISSUE TITLE
We are looking forward to Flutter's support for linux embedded development, which will be the perfect support for the whole platform of Flutter

### ISSUE THREAD

**Issue by qinjinze** [flutter/flutter#121375]
The Internet of Things needs Flutter to support linux embedded development

**Comment by stuartmorgan** [comment]
Closing as this does not describe a specific feature request; "linux embedded" is not a specific platform. And there are a number of third-party embeddings build on the officially supported embedder API that target various embedded use cases.

If you are requesting first-party support for a specific target, please file a new issue with the Feature Request template and provide a detailed description of what exactly you are requesting.
