### ISSUE TITLE
Can't run flutter run

### ISSUE THREAD

**Issue by dimasvm** [flutter/flutter#12133]
## Steps to Reproduce

I've setup my linux for using Flutter, I've finisihed all setup and finishing created project, and when I was running `flutter run` I've got like this...

## Logs 
This is output from `flutter run`
Launching lib/main.dart on Redmi 3X in debug mode...
Initializing gradle...                                1.4s
Resolving dependencies...                             1.2s
Running 'gradlew assembleDebug'...                        

Oops; flutter has exited unexpectedly.
Crash report written to /home/rythm/AndroidStudioProjects/sample_flutter_basic/flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.

FAILURE: Build failed with an exception.

* Where:
Script '/home/rythm/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 329

* What went wrong:
Execution failed for task ':app:flutterDependenciesDebug'.
> Process 'command '/home/rythm/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Gradle build failed: 1

## Flutter Doctor
[-] Flutter (on Linux, locale en_US.UTF-8, channel alpha)
    • Flutter at /home/rythm/flutter
    • Framework revision 701d534ba9 (3 days ago), 2017-09-12 14:01:51 -0700
    • Engine revision 31d03de019
    • Tools Dart version 1.25.0-dev.11.0
    ✗ Downloaded executables cannot execute on host (see https://github.com/flutter/flutter/issues/6207 for more information)

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /home/rythm/Android/Sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /home/rythm/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /home/rythm/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] IntelliJ IDEA Community Edition (version 2017.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected devices
    • Redmi 3X • 293ac1107d23 • android-arm • Android 6.0.1 (API 23)

So, what's wrong with this... ?

**Comment by moiseshiraldo** [comment]
Same error for me I think. I'm using Slackware 64-bit, with multilib enabled and all the 32-bit libraries required by Android Studio installed (including libstdc++6) https://developer.android.com/studio/install.html

I can build an application successfully and run it from Android Studio, but I get that error building or running from flutter:

```
$ flutter run
Launching lib/main.dart on Android SDK built for x86 64 in debug mode...
Initializing gradle...                                1.0s
Resolving dependencies...                             9.0s
Running 'gradlew assembleDebug'...                        
Failed to run the Flutter compiler. Exit code: -11

FAILURE: Build failed with an exception.

* Where:
Script '/home/devis/dev/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 329

* What went wrong:
Execution failed for task ':app:flutterDependenciesDebug'.
> Process 'command '/home/devis/dev/flutter/bin/flutter'' finished with non-zero exit value 245

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Gradle build failed: 1
```

The output of flutter doctor:

```
[-] Flutter (on Linux, locale en_US.UTF-8, channel alpha)
    • Flutter at /home/devis/dev/flutter
    • Framework revision 701d534ba9 (3 weeks ago), 2017-09-12 14:01:51 -0700
    • Engine revision 31d03de019
    • Tools Dart version 1.25.0-dev.11.0
    ✗ Downloaded executables cannot execute on host (see https://github.com/flutter/flutter/issues/6207 for more information)

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /home/devis/Android/Sdk
    • Platform android-26, build-tools 26.0.2
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Connected devices
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 7.1.1 (API 25) (emulator)
```
