### ISSUE TITLE
Failed assertion with Flutter version 3.7.1

### ISSUE THREAD

**Issue by Avijaygovinda** [flutter/flutter#121386]
'package:flutter/src/painting/text_style.dart': Failed assertion: line 1541 pos 14: 'decorationDescription.isNotEmpty': is not true.

whenevere i would debug my code in 1st time, it will showing the above error. After that i can start hot restart then it will be normal

**Comment by huycozy** [comment]
Please provide the complete output of `flutter run -v` which contains the error log. 

Also, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that may be related to this issue along with the output of `flutter doctor -v` as well.

Thank you!

**Comment by Avijaygovinda** [comment]
import 'package:cached_network_image/cached_network_image.dart';
import 'package:carousel_slider/carousel_slider.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:vvoosh_testing/Constants/customImage.dart';
import 'package:vvoosh_testing/Constants/custom_text.dart';
import 'package:vvoosh_testing/Constants/custompadding.dart';
import 'package:vvoosh_testing/Constants/getx_bindings.dart';
import 'package:vvoosh_testing/Constants/mediaquery.dart';
import 'package:vvoosh_testing/Constants/postdata_viewmodel.dart';
import 'package:vvoosh_testing/Constants/repository.dart';

import 'Constants/post_model.dart';

void main() {
  // WidgetsFlutterBinding.ensureInitialized();
  // GestureBinding.instance.resamplingEnabled = true;
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'vVoosh',
      initialBinding: GetxBindings(),
      debugShowCheckedModeBanner: false,
      home: const MainPage(),
    );
  }
}

class MainPage extends StatefulWidget {
  const MainPage({super.key});

  @override
  State<MainPage> createState() => _MainPageState();
}

class _MainPageState extends State<MainPage> {
  final PostsViewModel productModel = Get.find();
  String imageBaseurl = PostsRepository().imageurl;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0XFFf8f8f8),
      appBar: AppBar(
        title: CustomText(text: 'vVoosh'),
        backgroundColor: const Color(0XFFf8f8f8),
        elevation: 0,
        centerTitle: true,
      ),
      body: Obx(
        () => productModel.isLoading.isTrue
            ? const Center(
                child: CircularProgressIndicator.adaptive(),
              )
            : ListView.builder(
                itemCount: productModel.postList.length,
                physics: const BouncingScrollPhysics(),
                itemBuilder: (BuildContext context, int index) {
                  var postDetails = productModel.postList[index];
                  return postWidget(
                      productModel: productModel, postDetails: postDetails);
                },
              ),
      ),
    );
  }
}

Widget postWidget(
    {required PostsViewModel productModel,
    required PostsDataResult postDetails}) {
  // print(postDetails.contentType);
  //  postDetails.post?.contentType
  return CustomPadding(
    horizontal: .035,
    vertical: .02,
    child: Card(
      shape: const RoundedRectangleBorder(
          borderRadius: BorderRadius.all(Radius.circular(7))),
      margin: EdgeInsets.zero,
      elevation: .4,
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          postDetails.contentType == 'EVENT'
              ? Container()
              : headerWidget(
                  productModel: productModel, postDetails: postDetails),
          postDetails.contentType == 'POST'
              ? sharedimagePostWidget(
                  productModel: productModel, postDetails: postDetails)
              : postDetails.contentType == 'TIMELINE_LOVE_INTEREST'
                  ? intrestedFollowingWidget(
                      productModel: productModel, postDetails: postDetails)
                  : postDetails.contentType == 'EVENT'
                      ? privateEventWidget(
                          productModel: productModel, postDetails: postDetails)
                      : textPostWidget(
                          productModel: productModel, postDetails: postDetails),
          // privateEventWidget(),
          // textPostWidget(),
          // intrestedFollowingWidget(),
          footerWidget(productModel: productModel, postDetails: postDetails),
        ],
      ),
    ),
  );
}

Widget privateEventWidget(
    {required PostsViewModel productModel,
    required PostsDataResult postDetails}) {
  return Column(
    crossAxisAlignment: CrossAxisAlignment.start,
    children: [
      CustomPadding(
        horizontal: .025,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Container(
              alignment: Alignment.centerRight,
              height: 20,
              padding: const EdgeInsets.only(right: 10),
              width: ScreenSize.screenWidth,
              decoration: const BoxDecoration(
                gradient: LinearGradient(
                  colors: [
                    Colors.grey,
                    Colors.green,
                  ],
                  begin: FractionalOffset(0.0, 0.0),
                  end: FractionalOffset(1.0, 0.0),
                  stops: [0.0, 1.0],
                  tileMode: TileMode.clamp,
                ),
              ),
              child: CustomText(
                text: 'PRIVATE EVENT',
                color: Colors.white,
              ),
            ),
            CustomPaddingOnly(
              top: .02,
              bottom: .03,
              child: IntrinsicHeight(
                child: Row(
                  children: [
                    CustomText(
                      text: '25',
                      fontSize: .04,
                    ),
                    const VerticalDivider(
                      color: Colors.black,
                      thickness: 1,
                    ),
                    CustomText(
                      text: 'Sat, 23rd Jul 2022\n12:00 - 17:30',
                      fontSize: .02,
                    ),
                  ],
                ),
              ),
            ),
            CustomText(
              text:
                  '${postDetails.event?.name ?? ''} ${postDetails.event?.locationFormatted?.replaceAll(postDetails.event!.locationFormatted.toString(), 'Islington Assembly Hall') ?? ''}',
              fontSize: .025,
            ),
            CustomPaddingOnly(
              top: .07,
              bottom: .03,
              child: Row(
                children: [
                  CircleAvatar(
                    // child: Icon(Icons.person),
                    backgroundImage: CachedNetworkImageProvider(
                        '${PostsRepository().imageurl}${postDetails.profileUser?.avatarImageContentGuid}'),
                  ),
                  CustomPaddingOnly(
                    left: .03,
                    child: Column(
                      children: [
                        CustomText(
                          text: 'Created by',
                          fontSize: .02,
                          fontWeight: FontWeight.w400,
                        ),
                        CustomText(
                          text:
                              '${postDetails.profileUser?.firstName} ${postDetails.profileUser?.lastName}',
                          fontSize: .022,
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
      // const CustomImage(
      //   image: 'Assets/dummy_image.jpg',
      //   height: .25,
      //   width: 1,
      //   fit: BoxFit.cover,
      // ),
      postDetails.event?.coverImageUri?.uri == null
          ? Container()
          : CustomNetworkImage(
              image: postDetails.event?.coverImageUri?.uri ?? '',
              height: .25,
              width: 1,
              fit: BoxFit.cover,
            ),
      CustomPadding(
        vertical: .02,
        horizontal: .025,
        child: Row(
          children: [
            CircleAvatar(
              backgroundImage: CachedNetworkImageProvider(
                  '${PostsRepository().imageurl}${postDetails.profileUser?.avatarImageContentGuid}'),
            ),
            CustomPaddingOnly(
              left: .03,
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  CustomText(
                    text: 'You',
                    fontSize: .022,
                  ),
                  CustomText(
                    text: 'went',
                    fontWeight: FontWeight.w400,
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    ],
  );
}

Widget intrestedFollowingWidget(
    {required PostsViewModel productModel,
    required PostsDataResult postDetails}) {
  var corouselImages;
  int corouselIndex = 0;
  return Column(
    children: [
      CustomPadding(
        vertical: .01,
        child: Stack(
          alignment: Alignment.center,
          children: [
            GetBuilder<PostsViewModel>(
                id: 'update_carousel_index',
                builder: (controller) {
                  return postDetails.subEntries?.length != 0
                      ? CarouselSlider.builder(
                          itemCount: postDetails.subEntries?.length,
                          itemBuilder: (context, index, realIndex) {
                            var images = postDetails.subEntries?[index];
                            // productModel.carouselIndex.value = index;
                            return CustomNetworkImage(
                              image: images?.interest?.summaryImg?.uri ?? '',
                              height: .25,
                              width: 1,
                              fit: BoxFit.cover,
                            );
                          },
                          options: CarouselOptions(
                            height: ScreenSize.screenHeight * .25,
                            autoPlay: true,
                            aspectRatio: 16 / 9,
                            autoPlayCurve: Curves.fastOutSlowIn,
                            enableInfiniteScroll: true,
                            autoPlayAnimationDuration: 800.milliseconds,
                            viewportFraction: 1,
                          ),
                        )
                      : CustomNetworkImage(
                          image: postDetails.interest?.summaryImg?.uri ?? '',
                          height: .25,
                          width: 1,
                          fit: BoxFit.cover,
                        );
                }),
            postDetails.subEntries!.length >= 2
                ? CustomPadding(
                    horizontal: .025,
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        GestureDetector(
                          onTap: () {
                            // productModel.updateCarouselIndex(
                            //   index: productModel.carouselIndex.value,
                            //   totalLength: postDetails.subEntries!.length,
                            //   increment: false,
                            // );
                          },
                          child: const Icon(
                            Icons.arrow_back_ios,
                            color: Colors.white,
                          ),
                        ),
                        GestureDetector(
                          onTap: () {
                            print('object');

                            // productModel.updateCarouselIndex(
                            //   index: productModel.carouselIndex.value,
                            //   totalLength: postDetails.subEntries!.length,
                            //   increment: true,
                            // );
                          },
                          child: const Icon(
                            Icons.arrow_forward_ios,
                            color: Colors.white,
                          ),
                        ),
                      ],
                    ),
                  )
                : Container(),
            Positioned(
                top: 5,
                left: 0,
                child: CustomPadding(
                  horizontal: .025,
                  child: CustomText(
                    text:
                        '${postDetails.interest?.title ?? ''}\n${postDetails.interest?.systemWideLoves ?? ''} Followers',
                    color: Colors.white,
                    fontWeight: FontWeight.w700,
                  ),
                ))
          ],
        ),
      ),
    ],
  );
}

Widget textPostWidget(
    {required PostsViewModel productModel,
    required PostsDataResult postDetails}) {
  // print(postDetails.post?.authorId.toString());
  return CustomPadding(
    horizontal: .025,
    child: Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        CustomPadding(
          vertical: .02,
          child: CustomText(
            text: postDetails.post?.authorId.toString() ?? '',
            fontWeight: FontWeight.w400,
            fontSize: .028,
          ),
        ),
        Row(
          children: [
            Flexible(
              child: CustomText(
                text:
                    'https://restofworld.org/2022/indian-tech-firms-layoffs/?utm_source=pocket-newtab-intl-en',
                fontWeight: FontWeight.w400,
                fontSize: .02,
              ),
            ),
            const Icon(Icons.ios_share)
          ],
        ),
        CustomPaddingOnly(
          top: .01,
          bottom: .01,
          child: CustomText(
            text: 'CONTEXT.NEWS',
            fontSize: .015,
            fontWeight: FontWeight.w400,
          ),
        ),
      ],
    ),
  );
}

Widget footerWidget(
    {required PostsViewModel productModel,
    required PostsDataResult postDetails}) {
  return CustomPadding(
    horizontal: .025,
    child: Column(
      children: [
        CustomPadding(
          vertical: .025,
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Icon(Icons.chat_bubble_outline),
              CustomPadding(
                horizontal: .01,
                child: CustomText(
                  text: '0',
                  fontWeight: FontWeight.w400,
                  fontSize: .018,
                ),
              ),
              const Icon(Icons.favorite_border_outlined),
              CustomPadding(
                horizontal: .01,
                child: CustomText(
                  text: '3 People',
                  fontWeight: FontWeight.w400,
                  fontSize: .018,
                ),
              ),
            ],
          ),
        ),
        CustomPaddingOnly(
          bottom: .025,
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Row(
                children: [
                  // const CustomImage(
                  //   image: 'Assets/dummy_image.jpg',
                  //   height: .045,
                  //   width: .1,
                  //   fit: BoxFit.cover,
                  //   borderRadius: BorderRadius.all(Radius.circular(10)),
                  // ),
                  CustomNetworkImage(
                    image:
                        '${PostsRepository().imageurl}${postDetails.profileUser?.avatarImageContentGuid}',
                    height: .045,
                    width: .1,
                    fit: BoxFit.cover,
                    borderRadius: const BorderRadius.all(Radius.circular(10)),
                  ),
                  CustomPaddingOnly(
                    left: .03,
                    child: CustomText(
                      text: 'Say Something...',
                      fontWeight: FontWeight.w400,
                      fontSize: .02,
                      color: Colors.black54,
                    ),
                  ),
                ],
              ),
              Row(
                children: const [
                  Icon(Icons.emoji_emotions_outlined),
                  CustomPaddingOnly(left: .01, child: Icon(Icons.send)),
                ],
              ),
            ],
          ),
        )
      ],
    ),
  );
}

Widget sharedimagePostWidget(
    {required PostsViewModel productModel,
    required PostsDataResult postDetails}) {
  return Column(
    crossAxisAlignment: CrossAxisAlignment.start,
    children: [
      CustomPadding(
        vertical: .02,
        horizontal: .025,
        child: CustomText(
          text: postDetails.post?.title ?? '',
          fontSize: .022,
          fontWeight: FontWeight.w400,
        ),
      ),
      postDetails.post?.jsonBody?.sections?[0].content?.externalResource?.medias
                  ?.length !=
              0
          ? CustomNetworkImage(
              image: postDetails.post?.jsonBody?.sections?[0].content
                          ?.externalResource?.medias?.length ==
                      null
                  ? '${PostsRepository().imageurlwithmediaKeyword}${postDetails.post?.imageUri}'
                  : postDetails.post?.jsonBody?.sections?[0].content
                          ?.externalResource?.medias?[0].originalUrl ??
                      '',
              height: .35,
              width: 1,
              fit: BoxFit.cover,
            )
          : Container(),
      CustomPadding(
        vertical: .015,
        horizontal: .025,
        child: Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Flexible(
              child: CustomText(
                text: postDetails.post?.jsonBody?.sections?[0].content
                        ?.externalResource?.title ??
                    '',
                fontSize: .02,
                fontWeight: FontWeight.w400,
              ),
            ),
            const Icon(Icons.ios_share)
          ],
        ),
      ),
      CustomPadding(
        horizontal: .025,
        child: CustomText(
          text: 'CONTEXT.NEWS',
          fontSize: .015,
          fontWeight: FontWeight.w400,
        ),
      ),
    ],
  );
}

Widget headerWidget(
    {required PostsViewModel productModel,
    required PostsDataResult postDetails}) {
  return CustomPaddingOnly(
    top: .02,
    child: CustomPadding(
      horizontal: .025,
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Flexible(
            child: CustomNetworkImage(
              image:
                  '${PostsRepository().imageurl}${postDetails.profileUser?.avatarImageContentGuid}',
              height: .065,
              width: .16,
              fit: BoxFit.cover,
              borderRadius: const BorderRadius.all(Radius.circular(10)),
            ),
          ),
          CustomPaddingOnly(
            left: .007,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  children: [
                    CustomText(
                      text: postDetails.contentType == 'TIMELINE_LOVE_INTEREST'
                          ? '${postDetails.profileUser?.firstName} ${postDetails.profileUser?.lastName} '
                          : '${postDetails.post?.author?.firstName} ${postDetails.post?.author?.lastName} ',
                      fontWeight: FontWeight.w600,
                    ),
                    CustomText(
                      text: 'shared a post in ',
                      fontWeight: FontWeight.w400,
                    ),
                    CustomText(
                      text: 'Charity Work',
                      fontWeight: FontWeight.w600,
                      color: Colors.black54,
                    ),
                  ],
                ),
                CustomText(
                  text: '2 months ago',
                  fontWeight: FontWeight.w400,
                ),
              ],
            ),
          ),
        ],
      ),
    ),
  );
}

**Comment by huycozy** [comment]
Hi @Avijaygovinda 
Your sample code above contains 3rd packages (get, carousel_slider, etc) and other undefined widgets as well. For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Please provide such a sample.
