### ISSUE TITLE
promo code

### ISSUE THREAD

**Issue by Lee380822516** [flutter/flutter#121314]
<img width="467" alt="image" src="https://user-images.githubusercontent.com/19160535/220845178-60f020f8-7c40-4705-a2c5-7de0ab9fa3b8.png">
I can't find a place to fill in the promo code,running in release mode also has the problem with the latest in_app_purchase: ^3.1.5 package.
How to fix it

**Comment by huycozy** [comment]
This is a known issue being tracked at #110909. Closing this issue as a duplicate, so please follow up on it for further updates. Thanks!
