### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by yangzai100** [flutter/flutter#121330]
I have a simple issue with  https://github.com/flutter/flutter/issues/36272

#04 pc 001faacd /data/app/~~JNOg1TCITdpkrLnMdb_dQA==/com.qimao.writerassistant-1H7qXkyfRs_xlOQX6vk9gQ==/lib/arm/libflutter.so [armeabi-v7a::687fbcabdb8255a4947afbec0ece075c]

02-23 15:56:32.959 22368 22613 I awcn.StrategyCenter: StrategyCenter initialize started.

--
402-23 15:56:32.959 22368 22613 I awcn.StrategySerializeHelper: StrateyFolder path:/data/user/0/com.qimao.writerassistant/files/awcn_strategy
502-23 15:56:32.961 22368 22613 I awcn.StrategyTable: strategy map size:1
602-23 15:56:32.961 22368 22613 I awcn.StrategyInfoHolder: restore
702-23 15:56:32.962 22368 22613 W awcn.SerializeHelper: file not exist. file:WIFI$d41d8cd98f00b204e9800998ecf8427e

**Comment by kazemini** [comment]
Hi, can you explain more about issue.
( when app crash ), thank u❤️

**Comment by huycozy** [comment]
Hi @yangzai100 
Please provide the information indicated below so that we can verify the issue properly:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- Reproduction steps if any
- The output of `flutter doctor -v`, `flutter run -v` which may contains full of the crash log

Thank you!

**Comment by yangzai100** [comment]
> Hi, can you explain more about issue. ( when app crash ), thank u❤️

this is a bugly crash log。
我也不知道这个bug是怎么出现的,目前只出现了一次

**Comment by yangzai100** [comment]
> Hi @yangzai100 Please provide the information indicated below so that we can verify the issue properly:
> 
> * A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
> * Reproduction steps if any
> * The output of `flutter doctor -v`, `flutter run -v` which may contains full of the crash log
> 
> Thank you!

this is the output of ‘fluter doctor - v’
[✓] Flutter (Channel stable, 3.3.7, on macOS 12.5 21G72 darwin-arm, locale zh-Hans-CN)
    • Flutter version 3.3.7 on channel stable at /Users/yang/fvm/versions/3.3.7
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (4 个月前), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0
    • Pub download mirror http://mirrors.cnnic.cn/dart-pub

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/aozhaoyang/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.73.1)
    • VS Code at /Users/aozhaoyang/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 110.0.5481.100

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by huycozy** [comment]
@yangzai100 Please provide all information indicated on https://github.com/flutter/flutter/issues/121330#issuecomment-1442100469 so that we can verify the issue properly.
