### ISSUE TITLE
Option to disable D/EGL_emulation app_time_stats logs

### ISSUE THREAD

**Issue by bhavinb98** [flutter/flutter#121326]
I use VS Code for development. I am aware I can filter it using '!D/EGL`.

![image](https://user-images.githubusercontent.com/98743183/220890409-15df847e-ba23-4e97-848d-86d296d0dcc1.png)

Now if I want to see other important logs I have to use the same filter box for it which causes the spam to come back again, especially if you are working with videos on the app, hundreds of logs in a matter of seconds. 

Please give an option to disable it.

**Comment by darshankawar** [comment]
@bhavinb98 
I think this issue belongs to https://github.com/Dart-Code/Dart-Code/issues, so please file it there.
Closing from here. If you get directed here, please write in comments and I'll reopen it.
