### ISSUE TITLE
flutter/web.  Accessing remote server.  Cannot read: `set-cookie` header

### ISSUE THREAD

**Issue by WorikQCI** [flutter/flutter#121367]
Making HTTPS requests to remote server - I cannot read the returned `set-cookie` header

I am running Flutter/Web on my local server (`flutter run -d chrome --web-root 65152 `on MacOS and added the flag: `--web-browser-flag "--disable-web-security"`on windows)

I am making API calls via HTTPS to a remote server.

The remote server is responding including headers, which I thought were enough.

```
headers: access-control-allow-credentials: true
access-control-allow-headers:
Accept,Accept-Language,Content-Type,Authorization,X-Requested-With,X-HTTP-Method-Override,Access-Control-Request-Headers,Access-Control-Allow-Origin,Access-Control-Allow-Methods,Access-Control-Allow-Credentials
access-control-allow-origin: http://localhost:65152
access-control-expose-headers: set-cookie
```

Also tried: `access-control-allow-origin: https://<My IP number>:65152`

I cannot read the `set-cookie` header from the headers returned.  I need the cookie to authenticate with the remote server.

In the Network panel of devtools I can see the `set-cookie`header is  is there but: `request.getAllResponseHeaders()` does not list it and `request.responseHeaders['set-cookie']` cannot access it.  `request.responseHeaders` does not exist.

The code I am using on the client:

```dart
    HttpRequest request = await HttpRequest.postFormData(
      url.toString(),
      key,
      withCredentials: true,
      requestHeaders: APIGlobalVariables.headers,
    );
    String headers = request.getAllResponseHeaders();
    print("headers: $headers");

    if (request.status != 200) {
		.....throw an exception
	}
    // This outputs "12".  Cannot read `request.responseHeaders` in the watch pane of chrome/devtools
    print("request.responseHeaders.length: ${request.responseHeaders.length}");
    if (request.responseHeaders['set-cookie'] != null) {
	  // Never get here

      // Get the session cookie.  Forced unwrap OK
      String cookie = request.responseHeaders['set-cookie']!;
    }	
```

In the chrome debugger (DevTools/Sources tab) with a breakpoint on: `if (request.responseHeaders['set-cookie'] != null)` I cannot see the value of `request.responseHeaders` in the watch panel.

**Comment by huycozy** [comment]
Hi @WorikQCI 
This doesn't seem to be related to flutter itself but dart. I would recommend you open a new issue on [dart-lang/sdk](https://github.com/dart-lang/sdk/issues) for better support. 

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it. Thanks!
