### ISSUE TITLE
[local_auth] provide the authentication in the app context not the phone context.

### ISSUE THREAD

**Issue by MohamadTahir** [flutter/flutter#121397]
Hello, I am developing a very sensitive app, there is a behavior that we are trying to achieve 

1. user installs the app for the first time.
2. user logs into their account for the first time using their credentials.
3. app checks if there are any biometric authentications registered that are related to this account.
4. since this is the first time for the user to log in on this device they are asked to register a local authentication mechanism.
5. next time when the user opens the app, they still have an active session so there is no need for them to log in again, they only need to locally authenticate to prove that they are the same person who started this session.

we only want the user who initially logged in to be able to open the app, this is how the package works for most cases except for when you have an active session and the user removes the previously registered biometric authentication mechanism, here is what I mean

1. user already has an active session and has registered a biometric authentication mechanism.
2. the user decides to remove the local authentication mechanisms but forgets to log out of the app (and sells the device or gives it to someone else)
3. The new owner of the device opens the app.
4. The previous owner's account is still logged in since his session has not expired.
5. the local_auth won't find any registered biometric authentication mechanism so it will ask the user to register a new one.
6. the new user registers a new authentication mechanism.
7. the new user now can go inside the application with the previous device user's account.

one way to solve this issue is to relate the biometric authentication data to an account, not a device (local_auth does not keep that data), when a user registers their biometric authentication information we store the information somewhere (be it the cloud or securely on the device) the next time the user tries to authenticate the newly provided data compared to the data they provided at the authentication. this way even if you change the device and forget to log out, the new owners won't be able to use the app with the previous owner's session.

I hope that is clear enough, if not please feel free to ask so I can try to clarify more. 
if there is a better way to achieve this behavior please let me know.
Thank you.

**Comment by stuartmorgan** [comment]
`local_auth` is wrapping OS authentication functionality, which is at the device account level. If you have specialized needs beyond that functionality that involve validating the exact biometric details, you'd need a custom plugin as that's out of scope for `local_auth`.
