### ISSUE TITLE
colors messed up in emulator

### ISSUE THREAD

**Issue by cohortor** [flutter/flutter#12139]
The code below produces a background color of 0xFF676767 in the emulator, 0xFFAAAAAA on the device. Screenshots below taken with the android monitor tool.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Color test',
      home: new Container(
        alignment: FractionalOffset.center,
        color: const Color(0xFFAAAAAA),
        child: new Text('boo!'),
      ),
    );
  }
}
```

![Image on emulator](https://ibin.co/3akOxs9b3R2T.png) ![Image on device](https://ibin.co/3akPatqMppcL.png)

## Flutter Doctor

[✓] Flutter (on Linux, locale en_US.UTF-8, channel alpha)
    • Flutter at /opt/flutter
    • Framework revision 701d534ba9 (5 days ago), 2017-09-12 14:01:51 -0700
    • Engine revision 31d03de019
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /opt/android-sdk-linux
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /opt/jdk1.8.0_101/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_101-b13)

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2)
    • Flutter plugin version 17.0
    • Dart plugin version 172.4155.35

[✓] Connected devices
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 6.0 (API 23) (emulator)
Paste the output of running `flutter doctor` here.

**Comment by Hixie** [comment]
Probably an issue with colour correction in Skia. cc @chinmaygarde @jason-simmons

**Comment by chinmaygarde** [comment]
This was fixed by https://github.com/flutter/engine/pull/4355. Closing this old issue.
