### ISSUE TITLE
ScrollController doesn't broadcast change notification after it updates due to shrinking content

### ISSUE THREAD

**Issue by marcianx** [flutter/flutter#121419]
## Steps to Reproduce

Steps
1. Render a scrollable container with `ListView` and a `ScrollController`.
2. Listen to events on `ScrollController` (e.g. via `addListener`).
3. Scroll the content all the way to the end. Observe that all events are fired.
4. Shrink the content so that the `ScrollController` is updated to the reduced `maxScrollExtent`.

**Expected results:** `ScrollController` should notify that it was changed.

**Actual results:** It doesn't.

<details>
<summary>Here's a unit test that demonstrates it -- the last expectation fails.</summary>

I ran this as a flutter-web integration test.

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

const _viewportWidth = 300.0;

class FooApp extends StatelessWidget {
  final ScrollController scrollController;
  final ValueNotifier<double> contentWidth;

  FooApp(this.scrollController, this.contentWidth);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Material(
        child: Wrap(
          children: [
            Container(
              height: 40,
              width: _viewportWidth,
              child: ListView(
                controller: scrollController,
                scrollDirection: Axis.horizontal,
                shrinkWrap: true,
                children: [
                  ValueListenableBuilder(
                    valueListenable: contentWidth,
                    builder: (context, contentWidth, _) =>
                        SizedBox(height: 40, width: contentWidth),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}

void main() {
  group('Scroll issues', () {
    testWidgets(
        'No scroll notification when scroll offset changes due to content shrinking',
        (tester) async {
      final contentWidth = ValueNotifier(500.0);
      final scrollController = ScrollController();

      // Listen to [scrollController] update notifications.
      var scrollOffset = 0.0;
      scrollController
          .addListener(() => scrollOffset = scrollController.offset);

      await tester.pumpWidget(FooApp(scrollController, contentWidth));

      // When moving the scroll controller all the way to the end.
      scrollController.jumpTo(scrollController.position.maxScrollExtent);
      var expectedScrollPosition = contentWidth.value - _viewportWidth;
      await tester.pumpAndSettle();
      expect(scrollController.offset, expectedScrollPosition,
          reason: 'Expect scrollController to update to scroll to the end.');
      expect(scrollOffset, expectedScrollPosition,
          reason: 'Expect scrollController to have broadcast notifications.');

      // When shrinking the content so that the maxScrollExtent decreases.
      contentWidth.value -= 100;
      expectedScrollPosition = contentWidth.value - _viewportWidth;
      // Wait as long as needed for everything to settle.
      await tester.pumpAndSettle();
      await tester.pumpAndSettle();
      await tester.pumpAndSettle();
      expect(scrollController.offset, expectedScrollPosition,
          reason: 'Expect scrollController to update to the new end.');
      // >>>>>>>>>> FAILS HERE: <<<<<<<<<<
      expect(scrollOffset, expectedScrollPosition,
          reason: 'Expect scrollController to have broadcast a notification.');
    });
  });
}
```
</details>

**Comment by Piinks** [comment]
The ScrollController does not receive notifications for ScrollMetrics changes. Only scrolling activities. Can you ry to using a NotificationListener<ScrollMetricsNotification>?

**Comment by marcianx** [comment]
It still reproduces the issue. I'd be very surprised if it didn't especially since:

1. https://api.flutter.dev/flutter/widgets/ScrollController-class.html 
"A ScrollController is a Listenable. It notifies its listeners whenever any of the attached ScrollPositions notify their listeners (i.e. whenever any of them scroll)."
2. https://api.flutter.dev/flutter/widgets/ScrollPosition-class.html
"This object is a Listenable that notifies its listeners when pixels changes."
3. [ScrollController.offset reflects the ScrollPosition's `pixels`.](https://github.com/flutter/flutter/blob/b1b7284a7238ae114192e77e83449d8201a8aa6b/packages/flutter/lib/src/widgets/scroll_controller.dart#L100-L113)

The first test above demonstrates that `scrollController.offset` (and thus `scrollController.position.pixels`) changes, but the listener is not fired.

<details>
<summary>Here's the updated code using `NotificationListener`:</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

const _viewportWidth = 300.0;

class FooApp extends StatelessWidget {
  final ScrollController scrollController;
  final ValueNotifier<double> contentWidth;
  final void Function(double updatedOffset) onScrollUpdate;

  FooApp(this.scrollController, this.contentWidth,
      {required this.onScrollUpdate});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Material(
        child: Wrap(
          children: [
            NotificationListener<ScrollNotification>(
              onNotification: (notification) {
                onScrollUpdate(notification.metrics.pixels);
                return false;
              },
              child: Container(
                height: 40,
                width: _viewportWidth,
                child: ListView(
                  controller: scrollController,
                  scrollDirection: Axis.horizontal,
                  shrinkWrap: true,
                  children: [
                    ValueListenableBuilder(
                      valueListenable: contentWidth,
                      builder: (context, contentWidth, _) =>
                          SizedBox(height: 40, width: contentWidth),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

void main() {
  group('Scroll issues', () {
    testWidgets(
        'No scroll notification when scroll offset changes due to content shrinking',
        (tester) async {
      final contentWidth = ValueNotifier(500.0);
      final scrollController = ScrollController();

      // Updated with scroll offset change notifications.
      var scrollOffset = 0.0;

      await tester.pumpWidget(FooApp(scrollController, contentWidth,
          onScrollUpdate: (updatedOffset) {
        scrollOffset = updatedOffset;
      }));

      // When moving the scroll controller all the way to the end.
      scrollController.jumpTo(scrollController.position.maxScrollExtent);
      var expectedScrollPosition = contentWidth.value - _viewportWidth;
      await tester.pumpAndSettle();
      expect(scrollController.offset, expectedScrollPosition,
          reason: 'Expect scrollController to update to scroll to the end.');
      expect(scrollOffset, expectedScrollPosition,
          reason: 'Expect scrollController to have broadcast notifications.');

      // When shrinking the content so that the maxScrollExtent decreases.
      contentWidth.value -= 100;
      expectedScrollPosition = contentWidth.value - _viewportWidth;
      // Wait as long as needed for everything to settle.
      await tester.pumpAndSettle();
      await tester.pumpAndSettle();
      await tester.pumpAndSettle();
      expect(scrollController.offset, expectedScrollPosition,
          reason: 'Expect scrollController to update to the new end.');
      // >>>>>>>>>> FAILS HERE: <<<<<<<<<<
      expect(scrollOffset, expectedScrollPosition,
          reason: 'Expect scrollController to have broadcast a notification.');
    });
  });
}
```
</details>

**Comment by marcianx** [comment]
Changing to listening to `ScrollMetricsNotification` instead of `ScrollNotification` made the test pass, however.
Consider changing `ScrollPosition` to be updated on the former then to reflect all changes to `pixels`?

**Comment by Piinks** [comment]
> Consider changing ScrollPosition to be updated on the former then to reflect all changes to pixels?

ScrollPosition is what notifies for both ScrollNotifications and ScollMetricsNotifications, I am not sure what we could change. Can you say more about that?

> This is really easy hazard to run into, especially with `HookWidgets` where one might use
> 
> ```
> scrollController = useScrollController();
> ```
> 
> which is supposed to automatically trigger re-render when the scroll offset changes, but fails to do so in this case.

I am not familiar with `HookWidgets` or `useScrollController` in the context of this issue. How those are implemented could be directly related to whether or not the UI is rebuilt in response to scroll offset changes.

It sounds like there are some opportunities here to improve our documentation regarding the different types of scrolling notifications. ScrollMetricsNotification is intentionally separate from ScrollNotification and its subclasses, but all come from the ScrollPosition.

**Comment by marcianx** [comment]
> ScrollPosition is what notifies for both ScrollNotifications and ScollMetricsNotifications, I am not sure what we could change. Can you say more about that?

Oh sorry, I made a typo here. I meant `ScrollNotification` instead of `ScrollPosition`. But you're right, I can imagine there being a reason for the separation here.

So my original request is the more relevant one -- that whenever `scrollPosition.pixels` changes, then `scrollPosition` should notify as is currently documented. Otherwise, I don't see why one should listen to `scrollPosition` since that it would be a footgun.
