### ISSUE TITLE
fvm reports incorrect error message when there is an issue with git

### ISSUE THREAD

**Issue by wfsaxton** [flutter/flutter#121488]
This can be reproduced with the following:

1. Install git and fvm via choco as administrator.
```
choco install git
choco install fvm
```

2. Setup fvm as administrator
```
fvm install stable
fvm global (select stable)
```

3. Setup fvm as a local user
```
PS C:\Users\saxto> fvm global (select stable)
```

4. Attempt to run a flutter command
```
PS C:\Users\saxto>fvm flutter --version
Error: Unable to find git in your PATH.
```

This is an incorrect error message. The issue is with the git command being run in shared.bat and producing an error.  Here is the git command run manually:

```
PS C:\Users\saxto\fvm\versions\stable> git rev-parse HEAD
fatal: detected dubious ownership in repository at 'C:/Users/saxto/fvm/versions/stable'
'C:/Users/saxto/fvm/versions/stable' is owned by:
        'XXX'
but the current user is:
        'YYY'
To add an exception for this directory, call:

        git config --global --add safe.directory C:/Users/saxto/fvm/versions/stable
```

shared.bat should be modified to report that error.

**Comment by wfsaxton** [comment]
(I would fix this myself if I were more familiar with how to program batch files!)

**Comment by danagbemava-nc** [comment]
Hi @wfsaxton,

Does this bug occur if you use the flutter tool by itself or does it only occur with fvm? If it occurs only when you use fvm then you'll need to report this on their repo as it is a third-party tool

Thank you
