### ISSUE TITLE
[image_picker][documentation] `ImagePicker` does nothing without permission on Android

### ISSUE THREAD

**Issue by lukehutch** [flutter/flutter#121436]
Out of the box, `image_picker` does nothing on the Android emulator (does not open the gallery or camera).

In the console, the following error is reported:

```
Unhandled Exception: MissingPluginException(No implementation found for method pickImage
on channel plugins.flutter.io/image_picker_android)
```

The problem is that the [documentation states](https://pub.dev/packages/image_picker) `Android: No configuration required - the plugin should work out of the box.`

However, in reality Android [needs](https://github.com/flutter/flutter/issues/17545#issuecomment-395763875) the following permission:

```
    <uses-permission android:name="android.permission.CAMERA" />
```

In fact, this permission is needed *even if the app only uses `ImagePicker.gallery`, not `ImagePicker.camera`*. Neither method works without this permission, and there is no visual indication in the app as to why it failed, you have to look at the logs and then google the error message to figure out you're missing a permission.

The `image_picker` docs need to be fixed to state that this permission must be added to `AndroidManifest.xml`.

**Comment by stuartmorgan** [comment]
> you have to look at the logs and then google the error message to figure out you're missing a permission

I'm not sure what you found indicating that error message is related to permissions, but whoever said that was incorrect. That error message means that there's no handler on the native side for the method you called; generally that means the plugin hasn't been registered at all. Even if there were code in `image_picker` that required manifest permissions (which is not the case), the error message is saying that none of that code even had a chance to run.

Adding a permission could not possibly have fixed that error. However, it would have involved quitting the app, rebuilding it, and relaunching, and just that process could have (e.g., if you had tried adding the plugin while the app was already running and just hot reloading, which would cause that error).

Closing as the premise of this report is incorrect. However, if you have a reproducible way of causing the error you listed, please file a new issue with details about that.

**Comment by stuartmorgan** [comment]
I noticed the comment in the other issue that you linked to after posting my comment above; I've hidden it so that it doesn't cause similar confusion for others in the future.
