### ISSUE TITLE
Incorrect dartdoc reference

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#121422]
https://github.com/flutter/engine/blob/11b4380b622f3e3ee71ae2ec99fb6912ca5876cf/lib/ui/text.dart#L2057

The `[Text]` reference in the docs from `dart:ui` linked above is supposed to link to the `Text` widget from `package:flutter/widgets.dart` [1], instead it links to the `Text` class from `dart:html` [2].

[1] https://master-api.flutter.dev/flutter/widgets/Text-class.html
[2] https://master-api.flutter.dev/flutter/dart-html/Text-class.html

**Comment by goderbauer** [comment]
@srawlins @jcollins-g Is there anything we can do to guide dartdoc to link to the right class? Also, is there some kind of a way to specify globally what references take precedence if there are multiple candidates? We probably always want to prefer linking to things in `dart:ui` or `package:flutter` over linking to some obscure thing in another `dart:` library or third-party package.

cc @gspencergoog

**Comment by goderbauer** [comment]
Interestingly, dartdoc also things that this `[Text.rich]` reference is unresolvable:

https://github.com/flutter/engine/blob/11b4380b622f3e3ee71ae2ec99fb6912ca5876cf/lib/ui/text.dart#L179

Probably because `Text` from `dart:html` doesn't have a `rich` constructor, unlike the one from `package:flutter/widgets.dart`, which should have been the link target...

**Comment by srawlins** [comment]
> @srawlins @jcollins-g Is there anything we can do to guide dartdoc to link to the right class? Also, is there some kind of a way to specify globally what references take precedence if there are multiple candidates?

No, that feature is https://github.com/dart-lang/sdk/issues/50702.

**Comment by jcollins-g** [comment]
@goderbauer You can attempt to force the heuristics to obey you by specifying the library name and/or package name in the comment reference.   ```[widgets.Text.rich]``` or ```[widgets.Text]``` is more likely to work, ```[flutter.widgets.Text.rich]``` should also work.   What we really need however is the feature @srawlins mentioned because there is no way to implement this reasonably in the analyzer.   Arguably, it is implemented unreasonably in dartdoc....

**Comment by chinmaygarde** [comment]
Blocked on the the [cross referenced issue](https://github.com/flutter/flutter/issues/121422).

**Comment by goderbauer** [comment]
`[widgets.Text.rich]` did the trick, thanks @jcollins-g!
