### ISSUE TITLE
Help with Devtools g3 automated rolling.

### ISSUE THREAD

**Issue by CoderDake** [flutter/flutter#121424]
I'm hoping to configure Caas for Devtools, but I'm in need of help from an admin who can initiate the process.

The config, and more information can be found here: https://critique.corp.google.com/cl/510501189

Any information or direction on this would be helpful :D

**Comment by CoderDake** [comment]
CC: @Hixie @godofredoc

**Comment by godofredoc** [comment]
@CoderDake the copybara application is installed and setup for all the repositories of the flutter org. Is there anything else required?

**Comment by CoderDake** [comment]
@godofredoc I need someone with admin permissions who would be able to potentially approve the above critique, and be comfortable running the `copybara service insert [...]` command in order to initialize our service.

**Comment by godofredoc** [comment]
Added @yusuf-goog  and @CaseyHillers as reviewers. They are more familiar with copybara, after the CL is landed I can run the commands to enable it.

**Comment by CoderDake** [comment]
@godofredoc the Copybara changes are now submitted.
I think a fresh client should be able to run the the command that was listed in the CL now, and the service should then get set up.

I look forward to seeing if that ends up working for us :D

**Comment by godofredoc** [comment]
The copybara command was run successfully:

`INFO: 'devtools': Migrations 'devtools' was successfully added to copybara service.`

**Comment by godofredoc** [comment]
@CoderDake please let us know if it is running as expected.

**Comment by CoderDake** [comment]
Thank you so much @godofredoc!!!!!!!!!!!!!! I will follow up if we run into any issues with it :D
