### ISSUE TITLE
flutter/engine instructions incomplete for compiling on Mac Arm64

### ISSUE THREAD

**Issue by eseidel** [flutter/flutter#121426]
I believe I've followed all of:
https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment
and
https://github.com/flutter/flutter/wiki/Compiling-the-engine#compiling-for-macos-or-linux

But I can't seem to get the gn invocation correct to generate with the right arm64 buildtools.

e.g. 
```
./flutter/tools/gn --unoptimized --mac-cpu=arm64
ninja -C out/host_debug_unopt_arm64  
```
results in the log below.  That's pretty much a quote from:
https://github.com/flutter/flutter/wiki/Compiling-the-engine#compiling-for-macos-or-linux
so I must be missing something.

```
../../buildtools/mac-x64/clang/bin/clang++ -MD -MF obj/flutter/fml/string_conversion.string_conversion.o.d -D_LIBCPP_DISABLE_DEPRECATION_WARNINGS -DUSE_OPENSSL=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_DISABLE_AVAILABILITY=1 -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -D_DEBUG -DFLUTTER_RUNTIME_MODE_DEBUG=1 -DFLUTTER_RUNTIME_MODE_PROFILE=2 -DFLUTTER_RUNTIME_MODE_RELEASE=3 -DFLUTTER_RUNTIME_MODE_JIT_RELEASE=4 -DDART_LEGACY_API=\[\[deprecated\]\] -DFLUTTER_RUNTIME_MODE=1 -DFLUTTER_JIT_RUNTIME=1 -I../.. -Igen -I../../third_party/libcxx/include -I../../third_party/libcxxabi/include -I../../build/secondary/third_party/libcxx/config -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -mmacosx-version-min=10.14.0 -fno-strict-aliasing -fstack-protector-all -arch arm64 -fcolor-diagnostics -Wall -Wextra -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-implicit-int-float-conversion -Wno-c99-designator -Wno-deprecated-copy -Wno-psabi -Wno-unqualified-std-cast-call -Wno-non-c-typedef-for-linkage -Wno-range-loop-construct -Wunguarded-availability -Wno-deprecated-declarations -fvisibility=hidden -Wstring-conversion -Wnewline-eof -O0 -g2 -fvisibility-inlines-hidden -std=c++17 -fno-rtti -nostdinc++ -nostdinc++ -fvisibility=hidden -fno-exceptions -stdlib=libc++  -c ../../flutter/fml/string_conversion.cc -o obj/flutter/fml/string_conversion.string_conversion.o
/bin/sh: ../../buildtools/mac-x64/clang/bin/clang++: Bad CPU type in executable
[15/6199] ACTION //flutter/build/dart:...sdk(//build/toolchain/mac:clang_arm64)
ninja: build stopped: subcommand failed.
```

**Comment by eseidel** [comment]
Trying just the default "host_unopt", (in hopes using the defaults might let the gn script guess correct) also fails:

```
./flutter/tools/gn --unoptimized
ninja -C out/host_debug_unopt
```

```
FAILED: obj/flutter/fml/command_line.command_line.o 
../../buildtools/mac-x64/clang/bin/clang++ -MD -MF obj/flutter/fml/command_line.command_line.o.d -DUSE_OPENSSL=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_DISABLE_AVAILABILITY=1 -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -D_DEBUG -DFLUTTER_RUNTIME_MODE_DEBUG=1 -DFLUTTER_RUNTIME_MODE_PROFILE=2 -DFLUTTER_RUNTIME_MODE_RELEASE=3 -DFLUTTER_RUNTIME_MODE_JIT_RELEASE=4 -DDART_LEGACY_API=\[\[deprecated\]\] -DFLUTTER_RUNTIME_MODE=1 -DFLUTTER_JIT_RUNTIME=1 -I../.. -Igen -I../../third_party/libcxx/include -I../../third_party/libcxxabi/include -I../../build/secondary/third_party/libcxx/config -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -mmacosx-version-min=10.14.0 -fno-strict-aliasing -fstack-protector-all -arch x86_64 -fcolor-diagnostics -Wall -Wextra -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-implicit-int-float-conversion -Wno-c99-designator -Wno-deprecated-copy -Wno-psabi -Wno-unqualified-std-cast-call -Wno-non-c-typedef-for-linkage -Wno-range-loop-construct -Wunguarded-availability -Wno-deprecated-declarations -fvisibility=hidden -Wstring-conversion -Wnewline-eof -O0 -g2 -fvisibility-inlines-hidden -std=c++17 -fno-rtti -nostdinc++ -nostdinc++ -fvisibility=hidden -fno-exceptions -stdlib=libc++  -c ../../flutter/fml/command_line.cc -o obj/flutter/fml/command_line.command_line.o
/bin/sh: ../../buildtools/mac-x64/clang/bin/clang++: Bad CPU type in executable
[14/6994] ACTION //flutter/build/dart:...t_sdk(//build/toolchain/mac:clang_x64)
ninja: build stopped: subcommand failed.
```

**Comment by eseidel** [comment]
@christopherfujino kindly pointed me to https://github.com/flutter/engine/blob/main/ci/builders/mac_host_engine.json as examples of what the builders do, but assuming I'm reading that file correctly all the builders are (judging by their "drone_dimensions" actually x86 machines cross compiling to arm64, rather than arm64 themselves).

I'm currently assuming that building the engine on arm64 may not yet be supported?  Would love to be wrong. :)

**Comment by eseidel** [comment]
Looks like Rosetta is required: https://github.com/flutter/flutter/issues/103386  So this is just a dupe of that bug.

Here is a full log for posterity: https://gist.github.com/eseidel/112ee5ac416b86f63a310ad8a0ead64c

**Comment by jmagman** [comment]
You need to install Rosetta to build the engine on an arm64 Mac `softwareupdate --install-rosetta` because of https://github.com/flutter/flutter/issues/103386.  

In this case though you need Rosetta because it's building with `buildtools/mac-x64/clang/bin/clang++` instead of `buildtools/mac-arm64/clang/bin/clang++`.  If you add `--no-goma` I think it's _supposed_ to go through this path and use it, but it doesn't on my M1 machine (see also https://github.com/flutter/buildroot/pull/599):
https://github.com/flutter/buildroot/blob/2fd45de1f80de6b535163573463924b4be68def0/build/toolchain/mac/BUILD.gn#L27-L29

I'll file that.  I'll also update the wiki to indicate you need to have Rosetta installed.

**Comment by jmagman** [comment]
> In this case though you need Rosetta because it's building with `buildtools/mac-x64/clang/bin/clang++` instead of `buildtools/mac-arm64/clang/bin/clang++`. If you add `--no-goma` I think it's _supposed_ to go through this path and use it, but it doesn't on my M1 machine (see also [flutter/buildroot#599](https://github.com/flutter/buildroot/pull/599)): https://github.com/flutter/buildroot/blob/2fd45de1f80de6b535163573463924b4be68def0/build/toolchain/mac/BUILD.gn#L27-L29
> 
> I'll file that.

Never mind, this is on purpose, for now:
https://github.com/flutter/engine/blob/b9e1359b5964878b6938511c4fd4e8d0c0e12d74/tools/gn#L342-L348
https://github.com/flutter/engine/pull/39279

**Comment by jmagman** [comment]
Filed https://github.com/flutter/flutter/issues/121431
