### ISSUE TITLE
Implement LayoutTransform

### ISSUE THREAD

**Issue by afandria** [flutter/flutter#1214]
When we use the Transform widget, the current behavior is that the render object remains in place but is visually offset or rotated by the Transform.

This is usually good behavior, but in my case, I want some text/images to be rotated 90 degrees (or upside down) in place. (I use Transform + FractionalOffset to do this.) The current behavior has them take up the same space as they would have right-side-up (this can lead to odd amounts of whitespace being present on-screen, especially if they are put inside Flexible's).

Would it be possible to have a widget that TrueTransform's its children such that the space they take up is also rotated?

**Comment by abarth** [comment]
Do want to rotate the text by multiples of 90 degrees?

**Comment by abarth** [comment]
We can actually support arbitrary rotations.  It'll just be easier/faster if you only need multiples of 90 degrees.

**Comment by afandria** [comment]
Yes, I am good with increments of 90 degrees. The other angles... are out of luck.

**Comment by abarth** [comment]
> We can actually support arbitrary rotations.

Turns out that's much harder than just 90 degrees.
