### ISSUE TITLE
Adaptive Scaffold Navigation destinations 

### ISSUE THREAD

**Issue by rahul-yr** [flutter/flutter#121487]
I want to use Adaptive Scaffold without Navigation Destinations.. But unfortunately the destination field is mandatory. Any work around for this?

**Comment by darshankawar** [comment]
@rahul-yr 
I am not sure if that's possible. The `navigationRail` is used to create material 3 design spec deriving from list of navigation destinations and in turn the navigation destinations represents each destination view as we pass, hence the destination field is mandatory. so I am not sure if the use case you are trying to achieve is feasible or not. 
I suggest you to ask this on support channels like StackOverflow.
Closing from here.
