### ISSUE TITLE
The AssetImage cannot load asset in package when use git in pubspec.yaml 

### ISSUE THREAD

**Issue by dodatw** [flutter/flutter#121466]
I'm implementing a package (package_test) and an application that includes this package.
I have a problem with asset access in a package. Reference: https://docs.flutter.dev/development/ui/assets-and-images#from-packages

I have an Widget display an image (image_test.png) in package_test.
```
AssetImage('packages/package_test/images/image_test.png');
```

Now I want to include this Widget in main application.
I face a different result when I use different setting in pubspec.yaml

case 1: by local path
```
  package_test:
    path: /Users/xxx/package_test
```

case 2: by git path
```
  package_test:
    git:
      url: ssh://git@xxxx/package_test.git
```

The image can show in case 1, but not work at case 2.
here is error message:
```
The following assertion was thrown resolving an image codec:
Unable to load asset: packages/package_test/images/image_test.png.
```

flutter doctor -v
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.1 22C65 darwin-arm, locale zh-Hant-TW)
    • Flutter version 3.3.9 on channel stable at /Users/rdapp/fvm/versions/3.3.9
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (3 個月前), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/rdapp/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Connected device (2 available)
    • Tommy’s iPhone (mobile) • 00008110-00185018347A801E • ios          • iOS 16.2 20C65
    • macOS (desktop)         • macos                     • darwin-arm64 • macOS 13.1 22C65 darwin-arm

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by darshankawar** [comment]
@dodatw 
Can you take a look at https://docs.flutter.dev/development/packages-and-plugins/using-packages#dependencies-on-unpublished-packages and see if it helps in your case ?

**Comment by dodatw** [comment]
The local path can work seem a special case ?

After read document again https://docs.flutter.dev/development/ui/assets-and-images#from-packages
Here is different between `application` and `package` when handle assets. 
1. for `package`, the assets must under `lib/` folder, (it is not work at other path in `package`.)
2. for `package`, although folder is under lib/, but don't add "lib" in path when define and access. ex:
    - in pubspec.yaml: add `- packages/package_name/xxx/xxx.png` in `assets`
    - in using:  `AssetImage('packages/package_name/xxx/xxx.png')`;
3. for `package`, you need to add image one by one in package's `pubspec.yaml`, folders are not supported.

Is this best practice when handle asset in `package` ?
For "item 3", how to support folder mode ? I have a package with hundreds of images and modifies frequently.
Requires folder mode support like `application`.

**Comment by darshankawar** [comment]
See if below links helps to answer your query, or if you can follow-up in them for further resolution / reference:

https://github.com/flutter/flutter/issues/118635
https://github.com/flutter/flutter/issues/65921
https://github.com/flutter/flutter/issues/31756

**Comment by dodatw** [comment]
After checking these posts, there doesn't seem to be a good solution, it seems that I have used the best practice.

The folder issue still there, I still need add file one by one

**Comment by darshankawar** [comment]
Since the linked issues are open and have not yet resolved, I suggest you to follow-up in those issues for further updates. Will close this in favor of them. If you disagree, write in comments and I'll reopen it.
Please do leave a thumbs up on the original author's posts so we can track and prioritize the issue base on severity and demand. Thanks!
