### ISSUE TITLE
Calls to /api/postsubmit-luci-subscription are failing to update build results

### ISSUE THREAD

**Issue by ricardoamador** [flutter/flutter#121413]
Calls to /api/postsubmit-luci-subscription are failing and aborting transactions when updating the datastore with the results of builds from LUCI.

```
The transaction was aborted.
#0      GrpcDatastoreImpl.commit (package:appengine/src/grpc_api_impl/datastore_impl.dart:111:9)
<asynchronous suspension>
#1      DatastoreService.insert.<anonymous closure>.<anonymous closure> (package:cocoon_service/src/service/datastore.dart:251:13)
<asynchronous suspension>
#2      DatastoreService.insert.<anonymous closure> (package:cocoon_service/src/service/datastore.dart:249:11)
<asynchronous suspension>
#3      RetryOptions.retry (package:retry/retry.dart:131:16)
<asynchronous suspension>
#4      DatastoreService.insert (package:cocoon_service/src/service/datastore.dart:247:7)
<asynchronous suspension>
#5      PostsubmitLuciSubscription.post (package:cocoon_service/src/request_handlers/postsubmit_luci_subscription.dart:84:5)
<asynchronous suspension>
#6      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:53:24)
<asynchronous suspension>
#7      SubscriptionHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/subscription_handler.dart:139:19)
<asynchronous suspension>
#8      SubscriptionHandler.service (package:cocoon_service/src/request_handling/subscription_handler.dart:138:5)
<asynchronous suspension>
#9      main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:288:11)
<asynchronous suspension>
```

Here is the query in the cocoon log: https://pantheon.corp.google.com/logs/query;query=resource.type%3D%22gae_app%22%0Aresource.labels.module_id%3D%22default%22%0Aresource.labels.version_id%3D%22version-60a1590%22%0A%22dfe7f841b3cc4137a519e9c2bfce7febaa5979f3%22%0Aseverity%3DERROR;timeRange=P2D;cursorTimestamp=2023-02-24T15:46:19.446Z?serviceId=default&project=flutter-dashboard

I am not sure what is causing this only that it happens when we attempt to commit the transaction in the datastore.dart code. This needs to be investigated.

**Comment by nehalvpatel** [comment]
It looks like this is being mitigated by the PubSub retries as expected, but yea this is pretty common and its contributing to the constant GAE 500 level error incidents.

https://pantheon.corp.google.com/logs/query;query=resource.type%3D%22gae_app%22%0Aresource.labels.module_id%3D%22default%22%0Aresource.labels.version_id%3D%22version-60a1590%22%0A%22dfe7f841b3cc4137a519e9c2bfce7febaa5979f3%22%0A%22publishTime:%202023-02-24T15:46:20.461Z%22%0A%22%5C%22build_id%5C%22:%5C%228788265876307085121%5C%22%22;timeRange=P2D;summaryFields=httpRequest%252Fstatus:false:32:beginning;cursorTimestamp=2023-02-24T15:46:35.500Z?serviceId=default&project=flutter-dashboard

**Comment by ricardoamador** [comment]
Ah okay this is mitigation for this issue: https://github.com/flutter/flutter/issues/54615

**Comment by ricardoamador** [comment]
Closing as these get retried.
