### ISSUE TITLE
[tool_crash] TlsException

### ISSUE THREAD

**Issue by Mic-360** [flutter/flutter#121400]
## Command
```
flutter doctor -v
```

## Steps to Reproduce
1. git clone https://github.com/flutter/flutter.git -b master
2. flutter upgrade
3. flutter doctor -v

## System 
Windows 11 Build 25300-dev
Ram: 32GB
Processor: Ryzen 9 5000HS

## Logs
TlsException
```
#0      new _HttpClientConnection.<anonymous closure> (dart:_http/http_impl.dart:2098:9)
#1      _rootRunBinary (dart:async/zone.dart:1422:47)
#2      _CustomZone.runBinary (dart:async/zone.dart:1314:19)
#3      _CustomZone.runBinaryGuarded (dart:async/zone.dart:1224:7)
#4      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358:15)
#5      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:376:7)
#6      _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)
#7      _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:778:19)
#8      _StreamController._addError (dart:async/stream_controller.dart:656:7)
#9      _StreamController.addError (dart:async/stream_controller.dart:610:5)
#10     _rootRunBinary (dart:async/zone.dart:1422:47)
#11     _CustomZone.runBinary (dart:async/zone.dart

**Comment by huycozy** [comment]
Hi @Mic-360 
(Just to confirm this) Does the issue happen when executing `flutter doctor -v`? Is there any remaining crash log that you can provide?

**Comment by Mic-360** [comment]
Just after pulling from git i ran `flutter doctor -v` and there was no other log. I ran it again the problem got fixed.

**Comment by huycozy** [comment]
@Mic-360 Can you please check whether the issue also happens on the stable channel? Or is it only on the master channel?
Also, as I understand right, the issue is only happening once time and you don't see it currently?

**Comment by Mic-360** [comment]
It is only in beta and master channel.

**Comment by huycozy** [comment]
Labeling the issue for the team's attention.

**Comment by a-siva** [comment]
@Mic-360 do you still see this error on the newer versions of Flutter ? If not can you please close the issue.

**Comment by a-siva** [comment]
Closing issue as we have not heard back from the user, please reopen if you still think there is a problem and reproduction instructions exist.
