### ISSUE TITLE
Insert new line on enter press in a TextField

### ISSUE THREAD

**Issue by Ivaskuu** [flutter/flutter#12143]
Hi.
How do I create a TextArea? That means a TextField where when you press enter on your keyboard it adds a new line, something like notepad, or really any text editor. When I press enter in a TextField it just toggles the keyboard.
How can I achieve this in flutter? Thank you.

**Comment by eseidelGoogle** [comment]
@gspencergoog was looking at this recently, may have fixed?

**Comment by selvan** [comment]
TextField has a contructor param - maxLines, by setting maxLines greater than 1, TextField accepts multi-line text input but currently there are issues with cursor placement (When I tested, after pressing enter, cursor didn't move to the new line, even though a new line was created), see #12120 for more details.

Was looking for similar feature and sharing what I had found.

**Comment by jerrywell** [comment]
@selvan i ran into the same issue -  (When I tested, after pressing enter, cursor didn't move to the new line, even though a new line was created).

but i didn't see any related information for the tracking of this issue, except 

> There are still some issues with cursor placement in multi-line input, but those may go away when we switch to a non-Blink text renderer.

do you mean this one??

excuse me, @gspencergoog. is there any workaround for it??
thanks.

**Comment by zoechi** [comment]
libtxt landed in master as far as I know and this could be fixed

**Comment by gluix20** [comment]
Tested in Flutter v0.4.4 with libtxt landed and still has the described behavior.

**Comment by gluix20** [comment]
Take a look on this workaround #15572 from @oshima819

It worked for me!

**Comment by zoechi** [comment]
I close this as dup of #15572 because it has a bir more information.
