### ISSUE TITLE
flutter_gallery__transition_perf_with_semantics regression

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#12144]
flutter_gallery__transition_perf_with_semantics delta_missed_frame_build_budget_count regressed after https://github.com/flutter/flutter/pull/12039.

cc @goderbauer

**Comment by goderbauer** [comment]
De-duplicating into https://github.com/flutter/flutter/issues/12138.

**Comment by Hixie** [comment]
This is the benchmark in question; this bug is about the right-most regression (the last 100 or so pixels):
![](https://user-images.githubusercontent.com/551196/30563088-93d8a2c8-9c75-11e7-928d-678a59efbaa0.png)

It is almost a 2x regression on the number of missed frames overall in that benchmark (previous worst case to new worst case). It's weird to that it would be so much more expensive. Surely we should only be computing the semantics when something new scrolls on screen, and in this benchmark that's hardly anything at all. There should barely be any additional work here. It's a very simple list, and we're only scrolling one or two new rows onto screen each time.

**Comment by goderbauer** [comment]
> Surely we should only be computing the semantics when something new scrolls on screen

We have to update the `rect` of each SemanticNode visible in the scrolling list even if nothing new scrolls on the screen while scrolling, right? So, I'd expect that even for the tiny-tiniest scroll every node that's moving has to be updated.

**Comment by Hixie** [comment]
Isn't that all done on the Java side though?

**Comment by goderbauer** [comment]
I don't think so. I can see the `rect` numbers changing in the semantics tree output obtained by pressing "S" while `flutter run`. Those are computed on the dart side.
