### ISSUE TITLE
flutter- there is not any way to showing widget on keyboard

### ISSUE THREAD

**Issue by XleiterPG** [flutter/flutter#121452]
like telegram chatting  when we tap on item , telegram will focus on item and showing menu...
this menu will open on keyboard  and as well as this menu will not close the keyboard if keyboard was open .

**problem 1** :  the menu will close the keyboard ( menu -popupMenu- dialog- alertDialog - cupertinoContextMenu - etc  )

so thank you flutter for creating overlay   BUT  it's not really good for passing this issue
OK ! , we can use the overlay  and  give it our menu as custom Widget  👍 
so the keyboard will not going hide and close  ...

**problem 2** : the inserted overlayEntry to Overlay with global context (or any context you pass ) will going behind of keyboard and  we cant show our widget on keyboard

anyway  this issue didn't solved from 2018   and  there is not any solvation for that .

```import 'package:flutter/material.dart';

void main() {
  runApp(const  MaterialApp(

      home: MyApp()));
}


class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {

  OverlayEntry? overlayEntry;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomInset: false,
        body: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const SizedBox(height: 50,),
            const TextField(decoration: InputDecoration(
                hintText: "textField"
            ),),
            const SizedBox(height: 10,),
            InkWell(
              onTap: (){
                createHighlightOverlay();
              },
              child: Container(
                color: Colors.blue,
                width: 70 , height: 70 , child: const Center(child: Text("Tap Me")),
              ),)
          ],
        ),
    );
  }
  // Remove the OverlayEntry.
  void removeHighlightOverlay() {
    if (overlayEntry != null) {
      overlayEntry?.remove();
      overlayEntry = null;
    }
  }

  void createHighlightOverlay() {
    // Remove the existing OverlayEntry.
    removeHighlightOverlay();

    assert(overlayEntry == null);
    overlayEntry = OverlayEntry(
      builder: (BuildContext context) {
        print("AAAA");
        return GestureDetector(
          onTap: () {
            removeHighlightOverlay();
          },
          child: Container(
            color: Colors.black54,
            child: Stack(
              children: [
                Positioned(
                  top: MediaQuery.of(context).size.height / 2,
                  left: 40,
                  child: Container(
                    width: 200 , height: 300,
                    color: Colors.lightGreenAccent,
                  ),
                )
              ],
            ),
          ),
        );
      },
    );
    Overlay.of(context).insert(overlayEntry!);
  }
}
```

**Comment by darshankawar** [comment]
@XleiterPG 
Upon running your code sample using latest master, I see below after tapping on `tap me` button:

<img width="336" alt="Screenshot 2023-02-27 at 1 36 18 PM" src="https://user-images.githubusercontent.com/67046386/221507957-f1f30c9a-57e2-40c4-8306-c2d5eabaf5d8.png">

If I tap in textfield which opens keyboard and then tap on `tap me`, it shows below:

<img width="334" alt="Screenshot 2023-02-27 at 1 36 34 PM" src="https://user-images.githubusercontent.com/67046386/221508053-f3616b5a-2b42-4b26-b285-c02fcbc59575.png">

What's the expected behavior are you looking for ?

**Comment by XleiterPG** [comment]
@darshankawar  
im looking for solvation what i explained on **problem 2**

i try to explain simpler :   how to showing widget on keyboard ( not above keyboard )  which we using  overlay  for solving  keyboard Keeping up problem

the picture that will guild you in right way 
this picture  captured from telegram chat . as we can see  the widget ( its menu or custom widget , anyway not important ) going on keyboard  Not behind of that as my sample code 

![msg318070412-23865](https://user-images.githubusercontent.com/126311707/222884043-9dc5cc1a-5c8a-449c-90f2-e5c9a6b12366.jpg)

**Comment by darshankawar** [comment]
@XleiterPG So if I understand correctly, the custom menu or just the floating widget shown in below screenshot should appear behind the keyboard ? Is this the expected behavior are you looking for ?

<img width="609" alt="Screenshot 2023-03-06 at 11 21 53 AM" src="https://user-images.githubusercontent.com/67046386/223029543-f7ce2145-783f-4418-a964-33bf4f447ea8.png">

**Comment by XleiterPG** [comment]
@darshankawar 
sir
the custom menu or floating widget shown in below screenshot should appear **on** the keyboard.
as i shown you in sample code , we can appear widget behind keyboard with overlay.
im looking for appear custom menu or floating widget  _on keyboard  NOT behind or Above that._
have to there is a property or something like that for developers to  showing widget on keyboard !
------
when developer uses the overlay , that will insert above on all widgets and routes 👍 but the keyboard still is upper
i thing flutter have to workaround overlay to solve this as well

**Comment by darshankawar** [comment]
@XleiterPG 
Have you already checked if there are any community packages that offers the functionality you are reporting ?
Maybe you can take a look at below ones and see if they help in your case:

https://pub.dev/packages/keep_keyboard_popup_menu
https://pub.dev/packages/keyboard_overlay

**Comment by XleiterPG** [comment]
@darshankawar 
nope sir.
i searched alot time  before opening this. and if you Take time to search this specially event , you will see no one had this problem before , or the flutter developers didn't create this event yet to see this problem
also there is not any package to resolve this.

 for example this packages you offered :

https://pub.dev/packages/keep_keyboard_popup_menu
this package focused on keyboard keeping up with menu  as well as  i did in my sample code without this package.
this package just using overlay for showing custom menu or floating widget with keyboard.
there is not any idea for showing widget on keyboard.

https://pub.dev/packages/keep_keyboard_popup_menu
also this package using keyboard configuration 
so this package don't have any idea  for this issue too.

i stopped my programming at this step !
if there is not anyway in flutter and the flutter compony didn't work on this yet ... at result i have to insert some java code in my program😑

please give me some feedback i have to return it to my Scrum Master 🤷‍♂️

**Comment by XleiterPG** [comment]
@darshankawar 

this package also working around  showing widgets above keyboard , this package  based on resizing context when keyboard is coming up  and use the window bottom inserted padding and scrollView for support overFlow  this package not have idea and solution for this issue too.

I created a question for this topic before opening a support ticket
But the flutter developers didn't give me an answer or an idea for a solution
my question it's : https://stackoverflow.com/questions/75528651/flutter-inserted-overlay-going-behind-of-software-keyboard

my idea for this issue it is : 
in when we make a OverlayEntry and insert it on Local OverLay  as this `Overlay.of(context).insert()`
in this method we can yield  to insert our OverlayEntry at Above or Below of another OverlayEntry 
at result we know the overlay is a list of OverlayEntris  ... this ok until here
IF we make our keyboard an OverlayEntry  which that inserted on our Overlay List .
At The End  its Done ! 💯  we can insert our OverlayEntry Above keyboard Overlay 👍 also we can keep Keyboard Up  because we uses the overlay as well !!

ALSO we know there is a method for textInput  that is  `SystemChannels.textInput.invokeMethod("");`
IF the developer used it `SystemChannels.textInput.invokeMethod("textInput.insertOverlay");` , the keyboard will insert on OverLay and also show on Screen as OverlayEntry !
and IF developer use it `SystemChannels.textInput.invokeMethod("textInput.removeOverlay");` , the keyboard going as default style

also the another way it is :  the keyboard have local context , if there is way to giving keyboard  a context  at result we can manage keyboard with overlay as well ( idk  maybe this way have to be fixes )

END !

**Comment by XleiterPG** [comment]
@darshankawar  
amazing !
what i told as a idea , there aren't in flutter !!
and flutter compony have to work to make something like that  
i just offered my way to Compony , for faster solution 🤷‍♂️

anyway this  is a not solved issue And also maybe a bug until Flutter give a solution for that   Thank you...

**Comment by darshankawar** [comment]
> If you think the framework should have this feature out of the box, you may raise a new feature request issue providing all relevant details in it.

@XleiterPG As I mentioned earlier.
