### ISSUE TITLE
[Impeller] CupertinoPicker very lag when scroll 

### ISSUE THREAD

**Issue by litang0908** [flutter/flutter#121476]
## Details

CupertinoDatePicker become very lag when scrolling up or down, so i wrote a similar one with CupertinoPicker, but it's still very lag.
This only happened when  enable Impeller. 
`<key>FLTEnableImpeller</key> <true/> `

Maybe related issues: https://github.com/flutter/flutter/issues/106737

**Target OS version/browser:**  iOS 16.2
**Devices:** iPhone 13 Pro
**Screen video:**

https://user-images.githubusercontent.com/44760239/221401811-de472a98-51ae-4414-957a-9bb9fbea9898.MOV

## Reproduce 
[main.dart](https://gist.github.com/litang0908/dc86f86df60368412273496c0e401ff3)

## Logs

<details>
<summary>flutter doctor -v</summary>

```
Flutter (Channel master, 3.8.0-16.0.pre.48, on macOS 12.0.1 21A559 darwin-arm64, locale
    zh-Hans-CN)
    • Flutter version 3.8.0-16.0.pre.48 on channel master at /Users/tangyc/Documents/softs2/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c4bc9d5f37 (32 hours ago), 2023-02-24 19:30:27 -0500
    • Engine revision 4d8a7cbcb1
    • Dart version 3.0.0 (build 3.0.0-266.0.dev)
    • DevTools version 2.22.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

```

</details>

**Comment by jonahwilliams** [comment]
There are a few things going wrong here.

1. Each item in the cupertino picker is wrapped in an opacity layer. Because the opacity peephole isn't wired up (https://github.com/flutter/flutter/issues/120506) we end up creating a ton more subpasses then we otherwise would.

2. Because we don't have correct hazzard tracking (https://github.com/flutter/flutter/issues/120406)  the multiple subpasses are inefficient (https://github.com/flutter/flutter/issues/120399)

Fixing any of these would likely improve performance dramatically.

**Comment by jonahwilliams** [comment]
here is Xcode frame debugger dependency graph:

![image](https://user-images.githubusercontent.com/8975114/221440853-fe3f8f4e-7e62-4d97-a3cc-ac4c78280ca5.png)


And here is an engine timeline:

![image](https://user-images.githubusercontent.com/8975114/221440951-2ab62754-26bf-4e7d-9857-359433ce0962.png)

**Comment by ManInTheWind** [comment]
any update? I facing this issue too.🤣

**Comment by litang0908** [comment]
> any update? I facing this issue too.🤣

I have try a alternative solutions with [numberpicker](https://pub.dev/packages/numberpicker) , and it's also good.

**Comment by ManInTheWind** [comment]
> 

actually u just need to comment 'overAndUnderCenterOpacity' out and it will act normally😄

![image](https://user-images.githubusercontent.com/32859126/224740852-13bb7d8f-4270-4d89-960d-92744a68aab1.png)

**Comment by jonahwilliams** [comment]
Hi, all of the updates are posted in my previous responses and linked pull requests. Please don't ping for updates on issues, updates will be posted when they are available

**Comment by jonahwilliams** [comment]
I've landed https://github.com/flutter/engine/pull/40101 which should help substantially. While working on this we discovered that the existing Skia backend was actually misbehaving and over-optimizing this case: https://github.com/flutter/flutter/issues/122266

**Comment by jonahwilliams** [comment]
This has relanded
