### ISSUE TITLE
No Android Studio Setup

### ISSUE THREAD

**Issue by AkT-01** [flutter/flutter#121454]
When you install flutter for first time there are many issues we face related to android build tools gradle etc. and in same cases people don't want to use android studio for development so they have to go through manual process of installing stuff like sdk tools platform tools etc, so add a command maybe like 

`flutter setup --no-studio <optional>[path-where-user-wants-to-save-sdk-tools-cmdline-tools-etc-needed-by-flutter]`

which basically installs sdk and platform tools and stuff like that and also set them to the path or displays user some text to copy and paste into path so that developers can use flutter without android studio if they want.

PLEASE!!!!!!!!

**Comment by darshankawar** [comment]
@AkT-01 
There seem to be various ways / already existing solutions that you can take a look and see if they help in your case or not:

https://gist.github.com/syntaxhacker/046b57b556d2ce6bca81ba3ca7fd28cd
https://ksrk.medium.com/install-flutter-without-android-studio-on-window-9d3781172912
https://abrialstha.medium.com/getting-started-with-flutter-without-android-studio-c7e1128330dd
https://stackoverflow.com/questions/57909176/setup-flutter-app-without-android-studio-on-windows
