### ISSUE TITLE
shared preferences data persists even after uninstall

### ISSUE THREAD

**Issue by Kabilan21** [flutter/flutter#121451]
Hi, I have been using **shared_preferences** package to persist data. In a recent update of the app published in the play store, the data provided by shared preference seems wrong. 

- I used a boolean to check if the app is opened for the first time and also a timestamp(**DateTime.now().millisecondsSinceEpoch**). Both of the preferences had values which are persisted previously.
-  isFirstOpen value is false and the timestamp value seems to have a month old date.
- The behavior is only seen when the app is not installed before and installed from the play store.
- when I cleared app data of the same version of the app installed from the play store, no value obtained from shared preference is correct. 
- The behavior and the data provided by preference are consistent even if I uninstalled and installed it again from Play Store.

**Expected results:** shared preference data need to empty when the app is not installed before.

**Actual results:** shared preference data obtained seems old and seems to persist even after the app is uninstalled.

flutter version: 3.7.0
shared_preferences: ^2.0.12

**Comment by stuartmorgan** [comment]
Restoring data when re-installing an application is an Android-level behavior; the `shared_preferences` plugin has no control over it. If you want to control data backup for your application that's something you'd need to do at the application level.

**Comment by Kabilan21** [comment]
The issue here is:

1. Installed app for the first time.
2. get(isFirstOpen) returns true
3. set(isFirstOpen) preference to false
4. uninstalled the flutter app.
5.  get(isFirstOpen) returns false which is wrong. As it returns the value set at **step 3**. I could verify this on my test device (android) and couldn't reproduce on a different device.
6. This fetching of old data occurs repeatedly.

**Comment by stuartmorgan** [comment]
Please re-read my response; this was closed not because I don't understand what you are describing, but because it's a behavior of the OS API that the plugin is providing access to, not the plugin.

> 5\. get(isFirstOpen) returns false which is wrong.

You are welcome to file a bug against Android if you believe that this Android-level behavior is wrong.
