### ISSUE TITLE
google_sign_in with a idToken of null

### ISSUE THREAD

**Issue by wafy125** [flutter/flutter#12140]
I am using the plugins/packages/google_sign_in package for authenticating my app. It seems to authenticate fine and I am able to get a profile in the app. The issue I run into is getting a code that will work with my PHP Backend server. The idToken comes back null and the accessToken gives the errors of "id_token must be passed in or set as part of setAccessToken" if I set the Access Token and verifyIdToken. Or if I use the access tokens in the verifyIdToken I get "Wrong number of segments". 

I am assuming the token I need is the idToken, but that just comes back as null from the GoogleSignInAuthentication object.

#Code
<pre><code>
GoogleSignIn _googleSignIn = new GoogleSignIn(
  scopes: <String>[
    'email',
    'openid',
    'profile',
//    'https://www.googleapis.com/auth/contacts.readonly',
  ],
);
class _MyHomePageState extends State<MyHomePage> {
  AsyncResponse _response = null;
  @override
  void initState() {
    super.initState();
    _googleSignIn.onCurrentUserChanged.listen((GoogleSignInAccount account) {
      setState(() {
        _currentUser = account;
        if (account != null) {
          account.authentication.then((GoogleSignInAuthentication value) {
            setState(() {
              //_token = value.accessToken;
              print(value.toString());
              _token = value.idToken;
              _tokenType = 'Google';
            });
          });
        }
      });
    });
    _googleSignIn.signInSilently();
  }
</code></pre>
## Logs
Performing full restart...
Restarted app in 404ms.
I/flutter ( 4098): GoogleSignInAuthentication:{accessToken: <a long code>, idToken: null}

## Flutter Doctor
/usr/local/flutter/bin/flutter --no-color doctor
[✓] Flutter (on Linux, locale en_US.utf8, channel alpha)
    • Flutter at /usr/local/flutter
    • Framework revision 701d534ba9 (5 days ago), 2017-09-12 14:01:51 -0700
    • Engine revision 31d03de019
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /home/wafy/Android/Sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /usr/local/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 17.0
    • Dart plugin version 172.4155.35

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 5.1.1 (API 22) (emulator)

Process finished with exit code 0

**Comment by wafy125** [comment]
To add to the list of issues. I was able to get an accessToken from the IOS side. However when I try to use it to authenticate it fails on the PHP backend. What am I missing?

**Comment by andrepl** [comment]
@wafy125 not sure if you've figured this out yet, but I had the same issue, and was able to figure it out (for Android at least) after some digging, though it's not particularly well documented.

The plugin will only request `idToken` if it can find a `default_web_client_id` resource identifier.  This is generated by a gradle plugin which you need to set up, and requires the `google-services.json` file you download at the end of [registering your app](https://developers.google.com/mobile/add?platform=android)

First the `google-services.json` file must be placed in `<projectroot>/android/app/`

Next, you need to add:

    apply plugin: 'com.google.gms.google-services'

to your `<projectroot>/app/build.gradle` and:

            classpath 'com.google.gms:google-services:3.1.2'

to the `dependencies` section of your `<projectroot>/app/build.gradle`

and that's it.  GoogleSignIn will return a real idToken instead of null.

**Comment by csbenjamin** [comment]
I also am having trouble in getting idToken. I have tried the suggestion of @andrepl replacing `apply plugin: 'com.google.gms.google-services'` with `implementation com.google.gms:google-services:3.1.2` because I am using gradle 4, but it didn't work either. I still am getting a null idToken.

**Comment by richmidwinter** [comment]
3.2.1 worked for me.

**Comment by zoechi** [comment]
Is this still an issue?

**Comment by wafy125** [comment]
Unknown, moved on.

**Comment by scottdewald** [comment]
@andrepl Thanks a lot! I was missing the 'default_web_client_id' in my strings.xml resource.

**Comment by scottdewald** [comment]
> Is this still an issue?

@zoechi I am now able to get the id_token on Android once I added 'default_web_client_id' to my strings.xml resource based on @andrepl recommendation.

**Comment by akeating** [comment]
Thanks @andrepl. For future visitors, the Google Services Gradle Plugin docs are at https://developers.google.com/android/guides/google-services-plugin. I had success using 
```
classpath 'com.google.gms:google-services:4.1.0'
```

**Comment by enyo** [comment]
Just wanted to add my experience:

1. Simply adding `default_web_client_id` to my `strings.xml` file did **not** work
2. Adding `google-services:3.1.2` as a gradle dependency, the way @andrepl suggested, did not finish compiling for me
3. Using `google-services:4.1.0` however **did** work.

Side note: Adding the `default_web_client_id` manually to the `strings.xml` will result in an **error** because the google services dependency will try to add the same string again, resulting in a duplicate entry.

* * *

So to sumarize:

Do everything @andrepl [has suggested here](
https://github.com/flutter/flutter/issues/12140#issuecomment-348720774) but use `4.1.0` as the `google-services` version.

**Comment by uendar** [comment]
@ashishkumar1550  same with react native. Did you figure out anything?

**Comment by ashishkumar1550** [comment]
@uendar In my case it was some issue with the version of firebase I was using,  I was using old version of firebase_auth and google_sign_in to avoid androidX compatibility issues. After I updated to the new version, the idToken is still null but it is able to authenticate. Hope this helps you.

**Comment by tronglv92** [comment]
My experience:
insert in end of _android/app/build.gradle:_
    **apply plugin: 'com.google.gms.google-services'** in end of build.gradle, if not end of build.gradle 
   it not work
_android/build.gradle:_
    **classpath 'com.google.gms:google-services:4.3.0'**

**Comment by jerrymani33** [comment]
getting idToken null

classpath 'com.google.gms:google-services:4.3.3'
implementation 'com.google.android.gms:play-services-auth:17.0.0'
implementation 'com.google.firebase:firebase-auth:19.1.0'

**Comment by durduliu2009** [comment]
Unfortunately even in 2020 idToken is still null 
```
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.1'
        classpath 'com.google.gms:google-services:4.3.3'
    }
```

**Comment by danimateo** [comment]
Using `classpath 'com.google.gms:google-services:4.3.0` and following the instructions [here](https://codesundar.com/flutter-google-login) made it work for me

**Comment by PandukaNandara** [comment]
As [this](https://github.com/flutter/flutter/issues/16613#issuecomment-490494672)  
 explained 
> I was having the same issue as you, google sign in was not getting any jwt/idToken.
> 
> I was able to solve this by adding a Web Application oauth credential to the developers console. Then, redownloading `google-services.json` from firebase, somethings will be changed:
> 
> * a new record in the `oauth_client` array is added with `client_type: 3`.
> * `services` gets filled with `appinvite_service.other_platform_oauth_client`, that has the same content of the above record.
> 
> After that, the jwt/idToken started getting retrivied.

This worked for me.

**Comment by yethael** [comment]
> 
> 
> @andrepl Thanks a lot! I was missing the 'default_web_client_id' in my strings.xml resource.

This works for me, I'm using google_sign_in v.4.4.4 without firebase, only oauth2 for user authentication.

**Comment by ittechsathish** [comment]
2020 - changes:

 classpath 'com.google.gms:google-services:4.1.0'
apply plugin: 'com.google.gms.google-services'

you have to create a new file - settings.xml
default_web_client_id - it is your client id from Google Console
path: <root>/android/app/src/main/res/values/settings.xml

file content:
<resources>
  <string name="default_web_client_id">number-chunkstring.apps.googleusercontent.com</string>
</resources>

**Comment by lazarvgd** [comment]
My experience is to add google-service.json file to the project with all settings from Firebase console - I mean the third step in setup. Please UPDATE the documentation, because of the sentence:

> You don't need to include the google-services.json file in your app unless you are using Google services that require it.

was mislead me and I spent 2 days trying to solve the problem.

**Comment by ShehabSunny** [comment]
> > Is this still an issue?
> 
> @zoechi I am now able to get the id_token on Android once I added 'default_web_client_id' to my strings.xml resource based on @andrepl recommendation.

This worked for me. Make sure you add a **Web application type client ID** value for 'default_web_client_id' in _strings.xml_.  
PS. I'm using **google_sign_in: 4.5.1** without Firebase, just OAuth2.

**Comment by TranDinhKhang** [comment]
Using [this](https://stackoverflow.com/a/57169691/6182992) solution worked for me

**Comment by gilbertKaradja** [comment]
> > > Is this still an issue?
> > 
> > 
> > @zoechi I am now able to get the id_token on Android once I added 'default_web_client_id' to my strings.xml resource based on @andrepl recommendation.
> 
> This worked for me. Make sure you add a **Web application type client ID** value for 'default_web_client_id' in _strings.xml_.
> PS. I'm using **google_sign_in: 4.5.1** without Firebase, just OAuth2.

Hi, I'm also working without firebase. Can you please outline the steps you took?

**Comment by VarmaMSP** [comment]
@gilbertKaradja As the [docs](https://developers.google.com/identity/sign-in/android/start-integrating#get_your_backend_servers_oauth_20_client_id) point out you need oauth2 client id of your backend to request idToken or serverAuthCode.

Create a new oauth2 web application client from your developer console and add the following to res/values/strings.xml, That should work

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="default_web_client_id">{Web app Client id goes here}</string>
</resources>
```

**Comment by Antoniossss** [comment]
This is really annoying issue. Copying google-services.json around and trying bumping versions of gradle dependencies didnt work for me. What DID work for me, is explicitly setting `clientId` param when creating `GoogleSingIn`. Without that, I only able to get user identity, but withoud `idToken`, After explicitly setting it, `idToken` is retrieved 

I have take my client id from google-services.json /client/0/oauth_client/0/client_id

  GoogleSignIn _googleSignIn = GoogleSignIn(
      scopes: [
        'https://www.googleapis.com/auth/userinfo.email',
        'https://www.googleapis.com/auth/userinfo.profile',
      ],
      clientId:
          "YourClientIdFromGoogleServicesJsonFile-oauth_client.client_id.apps.googleusercontent.com");

**Comment by danielgomezrico** [comment]
In my case the issue was that my `google-services.json` does not contain any `type: 3` oauth clients, that happen because I deleted the oauth client that firebase created just after the project was created on firebase.

To fix it just create one web app in your firebase console, and then it will create that web OAuth client in console.developers.google.com, and redownload your `google-services.json`, now it will contain that web OAuth client id, and the android plugin will be able to find it.

It will not work if you create the oauth web client in console.developers.google.com by yourself, for some reason firebase does not know the existence of those clients, so you make it know by creating a fake web app and then removing it. 

![image](https://user-images.githubusercontent.com/76348/102944074-bc93ab00-4487-11eb-9680-2b84eb3ac700.png)

![image](https://user-images.githubusercontent.com/76348/102944077-bdc4d800-4487-11eb-88a2-ef704d9f4af8.png)
