### ISSUE TITLE
image_picker forces my router to reload

### ISSUE THREAD

**Issue by rlee1990** [flutter/flutter#121465]
When using the image_picker package with Auto Route package after taking a picture the view is auto popped and forces my app back to the root route.

**Comment by stuartmorgan** [comment]
See https://pub.dev/packages/image_picker#handling-mainactivity-destruction-on-android

Closing as a duplicate of https://github.com/flutter/flutter/issues/48016

**Comment by rlee1990** [comment]
@stuartmorgan This has nothing to do with anything you mentioned please reopen. Image picker should provide an option as to if we want to use root navigation or not.

**Comment by stuartmorgan** [comment]
> This has nothing to do with anything you mentioned

Being returned to the main screen of your application is exactly the behavior that results from your activity being terminated if you don't handle restoration, so I'm not sure why you believe it's unrelated.

> please reopen.

If you can reproduce what you are describing without activity destruction, please file a new issue that completely fills in the bug report template. Without all of the information in the template, including a reproducible test case, the issue isn't actionable.

> Image picker should provide an option as to if we want to use root navigation or not.

`image_picker` doesn't do any Flutter-level navigation, so there's nothing to control with an option.

**Comment by rlee1990** [comment]
> > This has nothing to do with anything you mentioned
> 
> 
> 
> Being returned to the main screen of your application is exactly the behavior that results from your activity being terminated if you don't handle restoration, so I'm not sure why you believe it's unrelated.
> 
> 
> 
> > please reopen.
> 
> 
> 
> If you can reproduce what you are describing without activity destruction, please file a new issue that completely fills in the bug report template. Without all of the information in the template, including a reproducible test case, the issue isn't actionable.
> 
> 
> 
> > Image picker should provide an option as to if we want to use root navigation or not.
> 
> 
> 
> `image_picker` doesn't do any Flutter-level navigation, so there's nothing to control with an option.

The reason is that normal app behavior when you take a photo is to return the results. Which works if I use auto router without having a nested navigation for bottom bar tabs. With them it restarts the router only when using a package that does not allow us to manage route navigation. I had the same issue with bottom sheets until I say use root navigation to false. I do not get a crash or an error. It just pops to the root because root navigation is being used
