### ISSUE TITLE
OrientationBuilder calls builder on resize (twice), not only on orientation change

### ISSUE THREAD

**Issue by YouRik** [flutter/flutter#121448]
Hi, I've been using the OrientationBuilder and noticed that it calls its builder whenever the window size changes, i.e., when the parent constraints change, rather than just when the actual orientation changes. This might be intended but is contrary to my expectations since it leads to possibly unnecessary rebuilds as it is called multiple times for a single resize (multiple frames?)

## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. (FLICKER WARNING) Resize the window

**Expected results:** 
Builder is only called when orientation changes, color only changes when orientation changes

**Actual results:** 
Builder is called (color change) on every resize (twice actually, tested by debugging), even if the orientation has not changed

<details>
<summary>Code sample</summary>

```dart
import 'dart:math';

import 'package:flutter/widgets.dart';

void main() {
  runApp(const OrientationApp());
}

class OrientationApp extends StatelessWidget {
  const OrientationApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return OrientationBuilder(
        builder: (BuildContext context, Orientation orientation) {
      final random = Random();
      return Container(
          color: Color.fromARGB(255, random.nextInt(255), random.nextInt(255),
              random.nextInt(255)));
    });
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```

```

```
Analyzing orientation_example.dart...                                   
No issues found! (ran in 0.5s)
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.5, on macOS 13.2 22D49 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[!] Android Studio (version 2022.1)
    ✗ Unable to find bundled Java version.
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.1)
[✓] VS Code (version 1.75.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @YouRik 
According to [this](https://docs.flutter.dev/cookbook/design/orientation#2-use-an-orientationbuilder-to-change-the-number-of-columns) documentation:

`The OrientationBuilder calculates the current Orientation by comparing the width and height available to the parent widget, and rebuilds when the size of the parent changes.`

So in your case, since the window resize is happening, it rebuilds as the size of the parent is changing.

See if it helps to answer your query.

**Comment by darshankawar** [comment]
@YouRik 

> 1. Is there a way to limit rebuilds to just when the orientation actually has changed?

maybe making use of statefulwidget could possibly limit it, but this is my guess.



> 2\. Why is the rebuild happening twice per resize?

This may not be specific to `OrientationBuilder` but with widget being rebuilding twice for which you can read https://api.flutter.dev/flutter/widgets/State-class.html which explains following:

- where to do one-time initialization
- build may be called any number of times.

**Comment by YouRik** [comment]
Thank you for the clarification!
