### ISSUE TITLE
Janky GridView with remote images

### ISSUE THREAD

**Issue by delfme** [flutter/flutter#121547]
Scrolling a gridView is janky

Tested with Impeller on latest stable and master 3.8.0-15.0.pre.25, iphone 13 pro, iose 16.1.

## Steps to Reproduce
Please run this example here:
https://github.com/delfme/janky-gridview-scrolling

**Expected results:**
Smooth scrolling.

**Actual results:**
Scrolling janks are less evident on ios with Impeller but it is still not perfectly smooth and it janks at times.

https://user-images.githubusercontent.com/53510751/221690041-a76036bf-4b28-4fee-b2cd-e4ce1bc84986.mp4

**Profiling vid:**
A few janks here and there, more janks from 0:12 on.

https://user-images.githubusercontent.com/53510751/221689399-88c1aba0-ba2d-4b3c-91a7-42cf0be2ec19.mov

<img width="1261" alt="Screenshot 2023-02-27 at 22 18 43" src="https://user-images.githubusercontent.com/53510751/221689560-2b24be42-f38e-4df1-87c2-137d1fe6e16a.png">

**Flutter doctor:**
 [✓] Flutter (Channel master, 3.8.0-15.0.pre.25, on macOS 12.2 21D49 darwin-arm64, locale en-IT) [!] Android toolchain - develop for Android devices (Android SDK version 31.0.0) ✗ cmdline-tools component is missing Run path/to/sdkmanager --install "cmdline-tools;latest" See https://developer.android.com/studio/command-line for more details. ✗ Android license status unknown. Run flutter doctor --android-licenses to accept the SDK licenses. See https://flutter.dev/docs/get-started/install/macos#android-setup for more details. [✓] Xcode - develop for iOS and macOS (Xcode 13.4.1) [✓] Chrome - develop for the web [✓] Android Studio (version 2021.2) [✓] Connected device (3 available) [✓] HTTP Host Availability

**Comment by delfme** [comment]
Raster thread takes much time but it is just 100x100px pics that weight a few KB each. Fade effects disabled. It looks a simple scenario.

**Comment by jonahwilliams** [comment]
I'm not able to reproduce any issues running with or without impeller on iOS.

1. What device are you using to test?
2. Can you upload the timeline so I can inspect it myself

**Comment by delfme** [comment]
1. iphone 13 pro iose 16.1
2. https://drive.google.com/file/d/16J4K2sp2X971hgvu61HoF0eAlHBYlVt1/view?usp=sharing

**Comment by delfme** [comment]
I see raster mostly and at times a huge paint
<img width="1237" alt="Screenshot 2023-02-28 at 00 11 39" src="https://user-images.githubusercontent.com/53510751/221710610-0055d8c6-39fa-48df-860d-9e7c60c0327d.png">


<img width="1260" alt="Screenshot 2023-02-28 at 00 10 13" src="https://user-images.githubusercontent.com/53510751/221710628-4dd47b8f-461e-4c9d-b2df-160a08baa6ea.png">

**Comment by darshankawar** [comment]
@delfme 
I ran with `--profile` using latest master version on iPhone 6s but didn't see / experience the jank:


https://user-images.githubusercontent.com/67046386/221804962-de6b2363-dba9-47d5-891b-e0d904af4d37.MP4



Although saw couple of performance shader as below while running / scrolling in the app:


https://user-images.githubusercontent.com/67046386/221804681-3fc81052-de47-4322-a109-4f5b73c826e8.mov


Also, since the repo you shared in this issue is same as https://github.com/flutter/flutter/issues/121525 with images loading via network, wondering what exactly is the difference between this issue and the other one.

**Comment by delfme** [comment]
@darshankawar I edited the code to let Jonah see the issue with remote images. Inside the main you can disabled remote images and enable asset images to test things as it is needed.

https://github.com/delfme/janky-gridview-scrolling/blob/0098f033403501ba8aee69121d5002fcf36c1686/lib/main.dart#L52-L64

OR

https://github.com/delfme/janky-gridview-scrolling/blob/0098f033403501ba8aee69121d5002fcf36c1686/lib/main.dart#L40-L49

**Comment by delfme** [comment]
> @delfme I ran with `--profile` using latest master version on iPhone 6s but didn't see / experience the jank:
> 
> 
> Although saw couple of performance shader as below while running / scrolling in the app:
> 
> 
> Also, since the repo you shared in this issue is same as #121525 with images loading via network, wondering what exactly is the difference between this issue and the other one.

This is curious, I can see janks in the scrolling even if you have just a couple of slow frames in your timeline. At least in my case I have several slow frames.

**Comment by delfme** [comment]
Here is another sample from ios Impeller. This is horizontal scrolling, janks make it feel like avatars are bumping. Item is a small size pic with a gradient circle and text. 

https://user-images.githubusercontent.com/53510751/221934686-27c33648-7f5f-411f-8a8f-50587645ed0a.MOV

**Comment by jonahwilliams** [comment]
I've tried a few more phones and I'm not able to reproduce any jank in the timeline. I see some sort of jank in the trace you posted, but when i tried to open the devtools trace from https://github.com/flutter/flutter/issues/121547#issuecomment-1447254885 it fails to load any information correctly. FYI @kenzieschmoll

**Comment by kenzieschmoll** [comment]
@jonahwilliams what do you mean by "it fails to load any information correctly"? I'm able to load the file into DevTools:
![Screenshot 2023-02-28 at 4 34 09 PM](https://user-images.githubusercontent.com/43759233/222014857-792edd3a-d823-4eda-bee5-2eb188359675.png)

**Comment by jonahwilliams** [comment]
as soon as I start scrolling around it starts to break. Also notices issues if I clikced on other frame times in the top, sometimes it would jump around incorrectly.

**Comment by darshankawar** [comment]
Ran again with impeller enabled in profile mode using latest master version on iPhone 6s and saw below:

<img width="1440" alt="Screenshot 2023-03-01 at 11 33 47 AM" src="https://user-images.githubusercontent.com/67046386/222058244-034eade5-c1e8-43d2-83ba-8404e03b5e49.png">

Will keep this issue open for team's tracking and attention.

<details>
<summary> master flutter doctor -v </summary>

```

[!] Flutter (Channel master, 3.8.0-18.0.pre.28, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.8.0-18.0.pre.28 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 25712d95d3 (2 hours ago), 2023-02-28 19:31:23 -0800
    • Engine revision 46ee3209b9
    • Dart version 3.0.0 (build 3.0.0-277.0.dev)
    • DevTools version 2.22.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by delfme** [comment]
@jonahwilliams @kenzieschmoll I can create a new one if needed. That one has 70 jank frames if I recall correctly.

@darshankawar can you please share your timeline as well?

**Comment by delfme** [comment]
Departing for a moment from numbers, and describing it by user experience:
- On ios with Impeller (iphoneX and newer models) it is a mixed bag. When it is smooth, it is very smooth. But on several scenarios (ie. images) it can be janky and bumping. In other cases, it is smooth and at some point, out of blue, you have a jank for 1-2sec till smoothness recovers.
- On android we can never get a smooth scrolling. Even in the best case scenario, there is always some micro-jitters. We also noticed that things get worse when finger touches up the screen (which makes us think there might be also a touch gesture issue).

We filled issues to report things for each platform, but this is the big picture.

**Comment by jonahwilliams** [comment]
Of the single trace file you've uploaded I see only a single missed frame - on the UI thread and due to GC. This doesn't have anything to do with impeller.

**Comment by jonahwilliams** [comment]
@delfme can you upload a trace that shows raster thread taking a long time?

**Comment by delfme** [comment]
@jonahwilliams my bad, I have uploaded a trace that is not the one used to file the issue.

Please check this other one, I'm testing on iphone 13 pro.

https://drive.google.com/file/d/1fdWSSA6x53WaUn9ZxLPKKcbfGk5H_hVr/view?usp=sharing

https://user-images.githubusercontent.com/53510751/222229891-57936d8f-5fa1-47d9-86fd-1fc8278f7d65.mp4

**Comment by jonahwilliams** [comment]
Here is the interesting part of the trace. it looks like texture upload is delaying the raster start time, which is contributing to the long raster thread timing. I wonder if the impeller decoders need to be aware of what the raster thread is doing so they can schedule more efficiently.

@chinmaygarde @bdero for more insight

![image](https://user-images.githubusercontent.com/8975114/222233161-5bdd9e39-e1dc-4195-a7a7-4f1cb0da9722.png)

**Comment by delfme** [comment]
This is the trace of the scrolling from this comment above
https://github.com/flutter/flutter/issues/121547#issuecomment-1448605141

https://drive.google.com/file/d/1Cn-2xwsumRqES97OpJQH-AccgcFYzVmG/view?usp=sharing

https://user-images.githubusercontent.com/53510751/222407212-8dbcc98f-ef06-4303-96cd-df0ea953cebc.mp4

**Comment by delfme** [comment]
Did latest commits after 3.8.0-15.0.pre.25 affect this? Because I just upgraded and now I see more janks, both list/grid scrolling and screens animations (basic left/right animation).

Lmk if other traces might be helpful. I think sharing code should instead not be required.

**Comment by chinmaygarde** [comment]
We should get a multi-frame GPU trace from Instruments. The multiple texture uploads will also cause overhead due to mip-mapping and potential format conversions. But that ought to not be a sweat for the GPU.

Another cause could be that with Metal, we are doing concurrent texture uploads and mip-mapping. Perhaps that is causing the GPU to be bandwidth limited? Don't know but Instruments will tell us this answer fairly quickly. We perhaps don't face this issue as much on OpenGL because we only have one IO context and everything is serialized. So just slower. We could just lower the concurrency on the modern backends.

Either way, Instruments traces.

**Comment by delfme** [comment]
@chinmaygarde this is the trace for android. 

https://drive.google.com/file/d/1EQrBWpIieNmWHZvhBilghB7TAHfvZIVn/view?usp=sharing

https://user-images.githubusercontent.com/53510751/224507587-6c36a1c3-ab98-43c1-93d5-1358463ee2fa.mp4

**Comment by delfme** [comment]
This is trace from sample code:

https://drive.google.com/file/d/1N9vFeoGJopmQyVUMydFpi7MQIKaEWoPo/view?usp=sharing

https://user-images.githubusercontent.com/53510751/224508201-f83b7e63-4250-4298-a413-fb1902c12328.mp4

**Comment by delfme** [comment]
Was wondering if there is something in the engine that is not working as supposed to and could be disabled. 

Just guessing theoretically-wise, coz dart is compiled into native. So, scrolling a grid of images cannot be janky if app is making no background work, pics are lightweight (150x150px) and cached in memory. 

React Native can operate at 60fps consistently in that scenario. Flutter should be smoother than RN. Is it GC that gets in the middle when it shouldn't? Is it an attempt to go at 80 - 120 fps which somehow end up causing janks?

**Comment by Iuri92** [comment]
Ok
