### ISSUE TITLE
[CP] Fix finding JDK in current Android Studio

### ISSUE THREAD

**Issue by gnprice** [flutter/flutter#121505]
### issue_link

https://github.com/flutter/flutter/issues/106674

### Commit Hash

aed9b4adc

### Target

stable

### pr_link

https://github.com/flutter/flutter/pull/121504

### Impacted Users

All Flutter developers using the current version of Android Studio

### Impact Description

Flutter is unable to find the JDK supplied by Android Studio.

As a result, Flutter fails to build for Android, depending on the rest of the system's configuration. (Flutter will leave Gradle on its own to try to find a JDK, which can succeed if `java` is on the developer's `PATH`.)

For a sense of the number of developers affected and the extent to which many are stuck when they hit this issue, see the numerous comments on #106674 and its many duplicates:
* #113775
* #118535
* #118513
* #118790
* and several more.

The first Android Studio version that triggers this issue, 2022.1 "Electric Eel", [became the stable release](https://plugins.jetbrains.com/docs/intellij/android-studio-releases-list.html#2022) on Jan 12. That's why #106674 got a wave of many new reports starting then. It's likely most developers have not yet upgraded Android Studio, so there are many more developers set to hit this issue in the future.

### Workaround

On Linux or macOS, one can work around by creating a symbolic link, like `ln -s jbr /path/to/Android/Studio/jre`.

This workaround has to be repeated after each minor Android Studio upgrade, which sees the `jre` symlink as a stray file and deletes it.

### Risk

low

### Test Coverage

yes

### Validation Steps

1. Install Android Studio "Electric Eel" (the current stable release) or later.
2. Run `flutter doctor -v`.
3. Confirm that it successfully reports a Java version for that Android Studio install, rather than "Unable to find bundled Java version."

(Compare the issue's original repro notes: https://github.com/flutter/flutter/issues/106674#issuecomment-1168580243 )

**Comment by christopherfujino** [comment]
This LGTM

**Comment by JasonChiu-dev** [comment]
Before the fix in next Flutter hotfix stable version, here is the solution for

**MacBook M1:**

Step 1: Change directory to the subdirectory (Contents) of the Android Studio forder:

`cd /Applications/Android\ Studio.app/Contents/`

Step 2: Create a symbolic link named jre and point it to jbr:

`ln -s jbr jre`

**Comment by itsjustkevin** [comment]
This cherry-pick missed the window.  It will be picked up during the next stable hotfix.

**Comment by ti4n1993** [comment]
Why not merged into main branch

**Comment by itsjustkevin** [comment]
@ti4n1993 it is already merged into the master branch since 07 Feb 2023.  See https://github.com/flutter/flutter/commit/aed9b4adce2f8301469b242e74a9e9dea8a9da66

**Comment by ti4n1993** [comment]
@itsjustkevin  but it is still showing Unable to find bundled Java version.I'm using Android Studio Giraffe Canary 7 and the master branch flutter

**Comment by gnprice** [comment]
@ti4n1993 Please file a new issue, and fill out the complete issue template including the output of `flutter doctor -v`. That will make it possible to investigate the issue you're seeing.

**Comment by ti4n1993** [comment]
@gnprice I have opened a new issue #121925
