### ISSUE TITLE
Don't use 'BuildContext's across async gaps.

### ISSUE THREAD

**Issue by m8811163008** [flutter/flutter#121519]
I have got this error when use context mounted

```dart
return TextField(
      controller: textEditingController,
      readOnly: true,
      decoration: InputDecoration(
        labelText: label,
        suffixIcon: IconButton(
          onPressed: () async {
            await Clipboard.setData(ClipboardData(text: initialValue));
            if (!context.mounted) {
              
            }
           
          },
          icon: const Icon(Icons.copy),
        ),
      ),
    )

```

Don't use 'BuildContext's across async gaps.
Try rewriting the code to not reference the 'BuildContext'

but when using this code the error is not shown.
```dart
if (context.mounted) {
    showSnackBar(context, 'Copied!');
 } else {
     showSnackBar(context, 'Try again!');
 }
```

**Comment by danagbemava-nc** [comment]
Hi @m8811163008, this is being tracked in https://github.com/dart-lang/linter/issues/4007, a similar case was previously reported in https://github.com/flutter/flutter/issues/116779. 

Kindly follow up in the dart-linter issue for updates. 

Closing from here. 

Thank you
