### ISSUE TITLE
Error waiting for a debug connection: The log reader stopped unexpectedly Error launching application on I2011.

### ISSUE THREAD

**Issue by kapilsharma-gts** [flutter/flutter#121585]
Launching lib/main.dart on I2011 in debug mode...
lib/main.dart:1
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Error waiting for a debug connection: The log reader stopped unexpectedly
Error launching application on I2011.
Exited

**Comment by danagbemava-nc** [comment]
Closing this as a duplicate of https://github.com/flutter/flutter/issues/106086. 

Kindly follow up in the issue linked above for updates. 

Thank you
