### ISSUE TITLE
[Impeller] Subtle pixel shifts in text during page transitions

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#121531]
Notices on an iPhone 7. Go to the old gallery page and navigate back and forth to a page. notice that as the page transition completes, the text visibly shifts. The effect is subtle, but once you see it.

I tried removing the source position rounding in the fragment shader but I think this actually made things worse.

Running with the Skia backend shows no such shifts.

**Comment by chinmaygarde** [comment]
Can we have a video of this?

**Comment by jonahwilliams** [comment]
Its actually kind of hard to see in the video, but on device - especially the iPhone 7 its more apparentl. Probably due to how we are snapping, but it would be nice if we could make this look better

https://user-images.githubusercontent.com/8975114/222790932-a50dd0fe-bcec-4d34-84ff-fc08bff1424c.MP4

**Comment by jonahwilliams** [comment]
FYI @bdero

**Comment by chinmaygarde** [comment]
Ok, its hard to unsee now.
