### ISSUE TITLE
[flutter_markdown] <sup> tags are not converting

### ISSUE THREAD

**Issue by Faisalkc4u** [flutter/flutter#121595]
`flutter_markdown: ^0.6.14`

![flutter_01](https://user-images.githubusercontent.com/12441355/221797376-b7fe326b-312c-442e-835f-5c7d5301ecef.png)

**Comment by danagbemava-nc** [comment]
Hi @Faisalkc4u, as noted in the README for the package, this is not supported. See https://pub.dev/packages/flutter_markdown#flutter-isnt-a-html-renderer

Closing as this is not supported. 

Thank you
