### ISSUE TITLE
IOS version 3.7.3 shows a bubble magnifying glass permanently during onsubmitted event

### ISSUE THREAD

**Issue by shalinicez** [flutter/flutter#121522]
![Screenshot 2023-02-24 at 4 49 33 PM](https://user-images.githubusercontent.com/97884969/221577137-1bb17a69-0ac6-4442-b674-301e4395d156.png)

**Comment by darshankawar** [comment]
@shalinicez 
The reported behavior is fixed and works on latest master but it is not in stable version yet. So I suggest you to try on latest master to see the feature working properly. The fix would most probably be available in next stable release.

`flutter channel master`
`flutter upgrade`

See a similar issue reported earlier: https://github.com/flutter/flutter/issues/119711
