### ISSUE TITLE
Make it possible to apply Flutter's Gradle plugin using the declarative plugins block

### ISSUE THREAD

**Issue by bartekpacia** [flutter/flutter#121552]
## Use case and proposal

it'd be great if Flutter's Gradle Plugin could be applied using the [declarative plugins block](https://docs.gradle.org/current/userguide/plugins.html#plugins_dsl_limitations). It's the recommended method of applying Gradle plugins.

[From Gradle docs:](https://docs.gradle.org/current/userguide/plugins.html#sec:using_plugins)
> This way of adding plugins to a project is much more than a more convenient syntax. The plugins DSL is processed in a way which allows Gradle to determine the plugins in use very early and very quickly. This allows Gradle to do smart things such as:
>
> - Optimize the loading and reuse of plugin classes.
> 
> - Provide editors detailed information about the potential properties and values in the buildscript for editing assistance.
> 
> This requires that plugins be specified in a way that Gradle can easily and quickly extract, before executing the rest of the build script. It also requires that the definition of plugins to use be somewhat static.

and:

> With the introduction of the [plugins DSL](https://docs.gradle.org/current/userguide/plugins.html#sec:plugins_block), users should have little reason to use the legacy method of applying plugins.

This would let Flutter developers do:

```groovy
plugins {
    id "com.android.application"
    id "kotlin-android"
    id "flutter"
}
```

instead of current:

```groovy
plugins {
    id "com.android.application"
    id "kotlin-android"
}

// ...

apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

// ...
```

## Implementation

The `plugins` block is constrained and doesn't allow for the direct loading of plugins from the filesystem path like it's currently done:

```groovy
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
```

The simplest way to get around this would be to serve Flutter Gradle plugin on [Gradle Plugin Portal](https://plugins.gradle.org). Developers would then use it ("it" being "the Flutter Gradle Plugin") in their `build.gradle`/`build.gradle.kts` files like this:

```groovy
plugins {
    id "com.android.application"
    id "kotlin-android"
    id "io.flutter.gradle.plugin" version 3.7.5 // Flutter version used
}
```

The above is unfortunately quite bad because it forces the developer to manually update the version of their Flutter Gradle Plugin every time they `flutter upgrade`.

It's still possible, though, by using [the `pluginManagement {}` block](https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_management) in the `settings.gradle`/`settings.gradle.kts`.

```kotlin
// settings.gradle.kts

pluginManagement {
    val flutterVersion: String = "..." // Get it somehow. Maybe run `flutter --version` and parse output?

    repositories {
        mavenCentral()
        google()
        gradlePluginPortal() // assume that Flutter Gradle Plugin is hosted here
    }

    resolutionStrategy {
        eachPlugin {
            if (requested.id.name == "flutter") {
                useModule("dev.flutter:flutter-gradle-plugin:$flutterVersion")
            }
        }
    }

    // pluginManagement block
    plugins {
        id("flutter") version flutterVersion apply false
    }
}
```

Then, developers could very easily apply this plugin in `build.gradle`:

```groovy
// app/build.gradle

plugin {
    id "com.android.application"
    id "kotlin-android"
    id "flutter"
}
```

See also:
- #121541
- [this comment in #121541](https://github.com/flutter/flutter/issues/121541#issuecomment-1447072829)

**Comment by gnprice** [comment]
Thanks for writing this up!

> The `plugins` block is constrained and doesn't allow for the direct loading of plugins from the filesystem path like it's currently done:

This is unfortunate. If the plugin gets loaded from a published artifact, that would mean a significant regression in the experience of developing changes to the plugin. It would also mean a significant regression in the experience for any developers using a local fork of Flutter where they've made any changes to the Gradle plugin. And it'd be an additional task the Flutter release team would have to perform on each Flutter release. … In fact, perhaps subsuming all of those: I'm not sure how using the Flutter main/master channel would work at all in that setup.

From the linked documentation, it looks like one potential way to manage this might be to put something in the `buildSrc` directory:
https://docs.gradle.org/current/userguide/plugins.html#sec:buildsrc_plugins_dsl
This would involve adding a file `android/buildSrc/build.gradle` in the Flutter project's tree, with a `gradlePlugin` block that somehow contrives to get Gradle to look in Flutter's own tree for the source of the plugin. I'm not sure just what that would look like, though (and not certain it's possible.)

**Comment by bartekpacia** [comment]
Fair points!

Another alternative might be using a composite build – one build for Flutter app, another build for Flutter Gradle Plugin.
The developer would then include the plugin build by calling:

```
// settings.gradle.kts

pluginManagement {
    includeBuild("path-to-flutter-plugin")
}
```

[Learn more here about including plugin builds](https://docs.gradle.org/current/userguide/composite_builds.html#included_plugin_builds). Also, bear in mind it's an incubating feature.

**Comment by gnprice** [comment]
> Another alternative might be using a composite build – one build for Flutter app, another build for Flutter Gradle Plugin.

Ah neat, that seems like it should work. And it looks cleaner than trying to get `buildSrc` to handle this.

> ```kotlin
> // settings.gradle.kts
> 
> pluginManagement {
>     includeBuild("path-to-flutter-plugin")
> }
> ```

Specifically I think the `includeBuild` line would look something like:
```kt
    includeBuild("$flutterSdkPath/packages/flutter_tools/gradle")
```
using the same `flutterSdkPath` variable the existing `settings.gradle` defines. And then the `packages/flutter_tools/gradle` directory would need a `build.gradle` of its own, describing how to build the plugin.


> The developer would then include the plugin build by calling:

In general it could be the developer, but for the great majority of projects the Gradle scripts are going to largely be left in whatever form the `flutter` tool put them, at least when it comes to this sort of logic. So whenever this gets implemented (either with the `includeBuild` strategy, or `buildSrc`, or something else), it should probably be accompanied in the same release by making the `flutter create` templates use the new way, and by writing a migration so that existing Flutter projects get brought along.

That definitely increases the effort required to ship this, but it's the only way to deliver the benefit of it to most Flutter developers. It's also the only way to avoid having to fully support both ways of doing things indefinitely.
