### ISSUE TITLE
Clang roll blocked due to object_path_lto flag regression

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#121537]
The Clang roll into the Flutter engine is currently failing.

When the linker runs with the `-object_path_lto` flag, it fails with this error:
`ld64.lld: error: No available targets are compatible with triple ""`

(example: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8788310090993751153/+/u/build_host_debug_unopt/stdout)

The Fuchsia toolchain team looked at this, and it appears to be related to https://reviews.llvm.org/D138451

**Comment by chinmaygarde** [comment]
The toolchain team is aware of the issue and the bug has been cross referenced. [Rolls are blocked ATM](https://autoroll.skia.org/r/fuchsia-linux-sdk-flutter-engine).

**Comment by jason-simmons** [comment]
See https://github.com/llvm/llvm-project/issues/61031

**Comment by chinmaygarde** [comment]
The linked patch landed 3 days ago. Waiting for a roll.

**Comment by goderbauer** [comment]
Since all p2 should have an owner I assigned this one to you, @jason-simmons.

**Comment by flar** [comment]
This was supposed to have been fixed a week ago, but the rolls are still failing on the same issue.

**Comment by flar** [comment]
Rolls are now attempting to roll to commit `ee3efcf1bc8b327cc04297895529b1088a2b748d` and are still failing with the same error.

**Comment by gaaclarke** [comment]
update from jason: we're waiting for Fuchsia to publish another Clang release with this issue fixed

**Comment by chinmaygarde** [comment]
Triage: We are still waiting on a release on a roll as of today.

**Comment by chinmaygarde** [comment]
Infra attempted to roll the new clang but that attempt timed out. Presumably because the new release wasn't goma capable. We are going to followup with the Fuchsia toolchain chatroom to figure out why this isn't being populated in the Fuchsia RBE.

**Comment by chinmaygarde** [comment]
There have been no new releases of clang to kick off this process again. This isn't a blocker but we will revisit this in a while.

**Comment by zanderso** [comment]
I think this issue is stale. Closing.
