### ISSUE TITLE
Flutter web app gets blurred on zooming on safari browser

### ISSUE THREAD

**Issue by gauria24** [flutter/flutter#121514]
Flutter web app gets blurred on zooming on safari browser. Attached the video of flutter gallery app.

Steps to reproduce:
1. Launch https://gallery.flutter.dev/#/ in safari browser
2. Zoom the web page using the browser zoom functionality (Cmd + or View, Zoom In) 
3. Observed that all text and images are blurred
4. The text and images blurring can be reproduced on locally hosted flutter web applications as well
5. The zooming does not blur the text and images on other browsers like chrome or Edge

flutter doctor command output is as below.
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.5, on macOS 13.2.1 22D68 darwin-x64,
    locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version
    33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.75.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

https://user-images.githubusercontent.com/97582254/221525465-f0331efe-d48e-4d02-b3a9-bf7be4814fee.mov

**Comment by huycozy** [comment]
Hi @gauria24 
As far as I can see, it seems this is an intentional result on Safari since other websites are also blurred as well (it is not too blurred for me, though).

<details>
<summary>Demo</summary>


https://user-images.githubusercontent.com/104349824/221596221-77223610-2c8a-4df5-8457-fb584789229f.mov


</details>

Please also try on other websites as well. Also, I am not sure if there is any tool to verify this better, if any, please share it.

**Comment by mfdcoder** [comment]
> Hi @gauria24 As far as I can see, it seems this is an intentional result on Safari since other websites are also blurred as well (it is not too blurred for me, though).
> 
> Demo
> Please also try on other websites as well. Also, I am not sure if there is any tool to verify this better, if any, please share it.

The issue is not reproducible on other websites like yahoo.com, linked etc.
@huycozy to see the extent of the blur, please view the video in full screen mode

**Comment by gauria24** [comment]
Hi @huycozy 
I checked with other websites like yahoo, twitter and linkedIn on safari browser and all they look good as intended. There is no blur issue with those websites.

Also please see the attached video on full screen to see blur effect better.


https://user-images.githubusercontent.com/97582254/226542787-2de360f0-4667-46bc-ba5e-d7d813f811cf.mov

**Comment by huycozy** [comment]
To make it more intuitive, I took screenshots with maximum zooming of Flutter Gallery and Yahoo on both Safari and Chrome: 

### Safari:
- Flutter Gallery

<img width="800" src="https://user-images.githubusercontent.com/104349824/226801641-5ec22eb2-b9af-4267-9996-7c6458ed0a18.png">

- Yahoo 

<img width="800" src="https://user-images.githubusercontent.com/104349824/226801615-8bc5430d-ff6d-499a-be6f-86e3a278f595.png"> 

### Chrome:
- Flutter Gallery

<img width="800" src="https://user-images.githubusercontent.com/104349824/226802364-fd6c9825-0d7d-4052-b8af-f31d074c43bd.png"> 

- Yahoo 

<img width="800" src="https://user-images.githubusercontent.com/104349824/226802374-d102f25c-29f7-46be-ad60-7f39f6ad9f29.png">

I can see Flutter Gallery looks better on Chrome, but Yahoo doesn't. 

And taking a look at both websites on Safari, it's hard to see the issue. For a more thorough analysis and to make sure it doesn't depend on a large repository like Flutter Gallery, would you mind you create 2 sample codes (one using Flutter and another is non-Flutter) that represent the same content?
