### ISSUE TITLE
Provide a way to add symbols to CanvasKit stack traces

### ISSUE THREAD

**Issue by jacobsimionato** [flutter/flutter#121579]
Sometimes, CanvasKit crashes in the browser, emitting stack traces with no symbols attached (e.g. https://github.com/flutter/flutter/issues/117946). If we capture the stack trace and upload it to a crash reporting server, we sometimes find high volume crashes, but they're difficult to investigate because I'm not aware of any instructions for adding symbols.

Is there a process for this? Even just a manual process using a script would be a big leap forward. I guess it should be reasonably achievable to symbolicate with the source map for canvaskit.js, but for canvaskit.wasm, is there an equivalent process?

Assigning to Yegor to ask about this!

**Comment by yjbanov** [comment]
Makes sense! I unassigned it temporarily to let the issue go through the triage queue.

**Comment by jacobsimionato** [comment]
Maybe we should close this in favour of https://github.com/flutter/flutter/issues/122834 which has more discussion

**Comment by yjbanov** [comment]
Yeah, let's dedupe and track the other one.
