### ISSUE TITLE
Not able to change system navigationbar color in android

### ISSUE THREAD

**Issue by rohnsht** [flutter/flutter#121503]
After updating to Flutter >3.7.0, changing the system navigationbar color doesn't work on android.  Once you push a new widget using Navigator the navigationbar color resets to default black color.

**Comment by danagbemava-nc** [comment]
Hi @rohnsht,

Please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with steps to reproduce so that we can investigate this issue. 

Thank you

**Comment by rohnsht** [comment]
Hi @danagbemava-nc 
I figured out the issue. It was because I was using `systemOverlayStyle:
            SystemUiOverlayStyle.dark` in Appbar which was working fine before flutter sdk version 3.7.0. Its solved now.
