### ISSUE TITLE
Issue using Admob plugin

### ISSUE THREAD

**Issue by jtrunick** [flutter/flutter#12159]
## Steps to Reproduce

Even though the rest of the flutter plugins (firebase_*) are publised, firebase_admob is not. I've downloaded that repo locally and refer to it thusly:

  firebase_admob:
    path: ~/dev/3rd_party/plugins/packages/firebase_admob

## Logs

FAILURE: Build failed with an exception.

What went wrong:
A problem occurred configuring project ':app'.
Could not resolve all dependencies for configuration ':app:_debugApk'.
A problem occurred configuring project ':firebase_admob'.
> Could not resolve all dependencies for configuration ':firebase_admob:_debugPublishCopy'.
> Could not find any version that matches com.google.firebase:firebase-core:11.0.+.
Versions that do not match:
10.2.6
10.2.4
10.2.1
10.2.0
10.0.1
+ 10 more
Required by:
project :firebase_admob
> Could not find any version that matches com.google.firebase:firebase-ads:11.0.+.
Versions that do not match:
10.2.6
10.2.4
10.2.1
10.2.0
10.0.1
+ 10 more
Required by:
project :firebase_admob

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.11.6 15G1510, locale en, channel alpha)
    • Flutter at /Users/joelt/dev/3rd_party/flutter
    • Framework revision 701d534ba9 (6 days ago), 2017-09-12 14:01:51 -0700
    • Engine revision 31d03de019
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/joelt/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.2
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.3)
    • Flutter plugin version 17.0
    • Dart plugin version 171.4424.63

[✓] Connected devices
    • None

**Comment by Hixie** [comment]
cc @collinjackson

**Comment by collinjackson** [comment]
firebase_admob is here: https://pub.dartlang.org/packages/firebase_admob

**Comment by kroikie** [comment]
@jtrunick

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/966. Any further collaboration will be done there.
