### ISSUE TITLE
Add functionality to copy logs, screenshots, and other artifacts to LUCI recipe location in packages repo

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#121535]
> Recipe will run the test in a deferred context which will create an env variable called FLUTTER_LOGS_DIR, the test runner can place any logs|artifacts to help debugging there and they will be automatically uploaded to GCS.

https://github.com/flutter/flutter/issues/74332#issuecomment-763865412

Implement in the packages repo recipe.

See also https://github.com/flutter/flutter/issues/43124 and https://github.com/flutter/flutter/issues/74344

**Comment by jmagman** [comment]
@stuartmorgan @godofredoc this would really really help out with native iOS and macOS failures so we can see the screenshot of what the app is doing when the test fails.

This looks pretty easy to do?
https://flutter-review.googlesource.com/c/recipes/+/39100

**Comment by godofredoc** [comment]
Closed with https://flutter-review.googlesource.com/c/recipes/+/39703

**Comment by jmagman** [comment]
Thank you!
