### ISSUE TITLE
SystemChrome.setPreferredOrientations only works the first time on iOS

### ISSUE THREAD

**Issue by jsmeke** [flutter/flutter#121625]
In my app I need all screens to be in portrait mode, and just only single screen that can be moved in landscape view however when I execute SystemChrome.setPreferredOrientations it takes effect only the first time I do it and on subsequent times I run it doesn't work anymore.

On Android it works well.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.3, on macOS 13.2.1 22D68 darwin-arm64, locale es-419)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.75.1)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!

**Comment by Jorge-Saieg** [comment]
Same issue...

**Comment by darshankawar** [comment]
@jsmeke 
Can you provide a minimal code sample that shows the reported behavior ?
Also, you may take a look at [this](https://github.com/flutter/flutter/issues/34230) similar / related issue and see if it resembles your use case.

Another related issue for reference: https://github.com/flutter/flutter/issues/57748

**Comment by kunkaamd** [comment]
> @jsmeke Can you provide a minimal code sample that shows the reported behavior ? Also, you may take a look at [this](https://github.com/flutter/flutter/issues/34230) similar / related issue and see if it resembles your use case.
> 
> Another related issue for reference: #57748

same issue for me.
Here is my minimal code:
`import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: const <Widget>[
            Text(
              'Screen 1',
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          Navigator.push(context, MaterialPageRoute(builder: (_) => const Screen2()));
        },
        tooltip: 'Go To Screen2',
        child: const Icon(Icons.navigate_next),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

class Screen2 extends StatefulWidget {
  const Screen2({super.key});

  @override
  State<Screen2> createState() => _Screen2State();
}

class _Screen2State extends State<Screen2> {

  @override
  void initState() {
    SystemChrome.setPreferredOrientations(
        DeviceOrientation.values
    );
    super.initState();
  }

  @override
  void dispose() {
    SystemChrome.setPreferredOrientations(
        [DeviceOrientation.portraitUp]
    );
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Screen 2"),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: const <Widget>[
            Text(
              'Screen 2',
            ),
          ],
        ),
      ),
    );
  }
}
`

https://user-images.githubusercontent.com/22388256/222327579-6e7464b9-cfb8-4b24-8bc0-fc5c4e12b2b2.mov

**Comment by hadukin** [comment]
Same issue...

**Comment by im-x** [comment]
Same issue...

**Comment by darshankawar** [comment]
Everyone facing the reported issue in this thread, please check this similar issue describing a similar case https://github.com/flutter/flutter/issues/57748 and you may also try your use case on latest versions (3.7.7) and latest master to see if it still replicates or not.

Also, please avoid commenting `same issue`. Instead upvote the original post to get more attention from the team.

**Comment by AmarjitM13** [comment]
Instead of using DeviceOrientation.values try specifying the orientation like:

    class _Screen2State extends State<Screen2> {
    
      @override
      void initState() {
        SystemChrome.setPreferredOrientations(
             [DeviceOrientation.landscapeLeft]             //  Try using this
        );
        super.initState();
      }
    
      @override
      void dispose() {
        SystemChrome.setPreferredOrientations(
            [DeviceOrientation.portraitUp]
        );
        super.dispose();
      }

**Comment by moribellamy** [comment]
this ticket is not "waiting for customer response." @kunkaamd posted repro instructions

**Comment by admincode1** [comment]
I'm also having same issue on Flutter (Channel stable, 3.7.10).
Works fine in master channel, but unable to use master due to plugin update..

**Comment by darshankawar** [comment]
Everyone facing this issue, please take a look at this related / similar open issue https://github.com/flutter/flutter/issues/57748 and comment your findings in that issue if you think your use case is similar to the one described in it. Also, leave a thumbs up on original description of that issue so that the team can prioritize it based on number of upvotes.

**Comment by moribellamy** [comment]
this was probably the same issue as https://github.com/flutter/flutter/issues/57748#issuecomment-1507325419
