### ISSUE TITLE
Error: unable to locate asset entry in pubspec.yaml: "assets/CupertinoIcons.ttf". Target debug_android_application failed: Exception: Failed to bundle asset files.

### ISSUE THREAD

**Issue by sudishk** [flutter/flutter#121600]
Hi all I am facing this issue for the last 5 -7 days I have also tried with different flutter SDK and when I  am running flutter doctor it is showing all correct. 

kindly Help me.

Error: unable to locate asset entry in pubspec.yaml: "assets/CupertinoIcons.ttf".
Target debug_android_application failed: Exception: Failed to bundle asset files.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutterSdk\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1151

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutterSdk\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 25s
Running Gradle task 'assembleDebug'...                             26.6s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by huycozy** [comment]
It seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any.
For quick search results, please see these StackOverflow answers: https://stackoverflow.com/questions/59432187/error-unable-to-locate-asset-entry-in-pubspec-yaml-assets-fonts-lato-regular

Closing for now.

**Comment by sudishk** [comment]
Thanks but this not working because after solving that issue the next same issue is appearing.

Error: unable to locate asset entry in pubspec.yaml: "fonts/LineAwesome.ttf".
Target debug_android_application failed: Exception: Failed to bundle asset files.
