### ISSUE TITLE
Edit command to disable/enable analytics in new unified analytics package

### ISSUE THREAD

**Issue by eliasyishak** [flutter/flutter#121617]
## Use case

Once we start using the new unified analytics package for all dart and flutter related tooling, we will need to implement a cli command to disable or enable telemetry collection

**Comment by eliasyishak** [comment]
Currently blocked until analytics package has been added to flutter tools

**Comment by christopherfujino** [comment]
Is there any reason we can't use the existing one? Renaming this would break all scripts that automate opting out: https://github.com/christopherfujino/flutter/blob/flutter_tools_api/packages/flutter_tools/lib/src/commands/config.dart#L16

**Comment by eliasyishak** [comment]
Oh I wasn't aware of this command, this issue will aim at refactoring it with the new package's disable telemetry method as well then

**Comment by eliasyishak** [comment]
For my own reference, the block of code that needs to be edited when the new analytics package gets onboarded to flutter-tools

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/config.dart#L129-L142
