### ISSUE TITLE
Material3 Dropdownmenu widget width problems

### ISSUE THREAD

**Issue by yasinertune** [flutter/flutter#121609]
Hello everyone, I used the Dropdownmenu wideget with the arrival of Material3 components.

Dropdownmenu widget takes width parameter. The size of the dropdownmenu widget remains fixed when I give a dynamic width parameter and change the size of the screen. dynamic width is not working.

I leave the link of the widget. I would be glad if you help.

https://api.flutter.dev/flutter/material/DropdownMenu-class.html

**Comment by darshankawar** [comment]
@yasinertune 
I believe you are hitting https://github.com/flutter/flutter/issues/120567, so please follow-up in it for further updates.

Please do leave a thumbs up on the original author's post so we can track and prioritize the issue base on severity and demand. Thanks!
