### ISSUE TITLE
url_launcher(6.1.9) is blocked in safari

### ISSUE THREAD

**Issue by toknT** [flutter/flutter#121658]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues/55121)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. url_launcher version 6.1.9
2. Call `await launchUrl(openUrl)` or `await launch(url, forceSafariVC: true)`
3. It should open the URL in Safari, instead, it was blocked by Safari. (I know there is setting in safari but I am not allowed to require user change that)

### Actual results

Safari blocked it , when open new tab.

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.3, on Microsoft Windows [Version 10.0.22621.1265], locale ja-JP)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.75.1)
[√] Connected device (3 available)
HTTP Host availability check is taking a long time...[!] HTTP Host Availability
    X HTTP host "https://maven.google.com/" is not reachable. Reason: An error occurred while checking the HTTP host: The semaphore timeout period has
      expired.

    X HTTP host "https://pub.dev/" is not reachable. Reason: An error occurred while checking the HTTP host: Connection terminated during handshake
    X HTTP host "https://cloud.google.com/" is not reachable. Reason: An error occurred while checking the HTTP host: The semaphore timeout period has
      expired.

! Doctor found issues in 2 categories.

**Comment by toknT** [comment]
sorry it's `launch` method not `launchUrl` but still blocked by safari

**Comment by toknT** [comment]
From this [issue](https://github.com/flutter/flutter/issues/75227#issuecomment-771917971) ,I solve it by using [flutter_linkify](https://pub.dev/packages/flutter_linkify)

**Comment by darshankawar** [comment]
@toknT 
I tried the [plugin example](https://pub.dev/packages/url_launcher/example) and ran on iOS simulator which opened the test url in iOS safari browser as expected:

<img width="339" alt="Screenshot 2023-03-01 at 1 53 22 PM" src="https://user-images.githubusercontent.com/67046386/222084068-bf4d80a4-347c-42eb-b700-4fface5c4f15.png">

Also check if this related issue for your further reference: https://github.com/flutter/flutter/issues/78524

**Comment by toknT** [comment]
@darshankawar Thanks. Finally I found out why the jump is blocked by safari. In my case there is a page with downlad button and **before downloading we need report user's action to a api** for soring or others . May safari find it and block the jump.If **remove the `await`** it do as expected.The code like this

```dart
Column(
              children: [
                ElevatedButton(
                  onPressed: () {
                    _reportDownload();
                    _launchInBrowser(Uri.parse(DOWNLOAD_LINK));
                  },
                  child: const Text('download'),
                ),
                ElevatedButton(
                  onPressed: () async {
                    await _reportDownload();
                    await _launchInBrowser(Uri.parse(DOWNLOAD_LINK));
                  },
                  child: const Text('download(can not launch in safari)'),
                ),
              ],
            )
```
