### ISSUE TITLE
flutter-dashboard.appspot.com dashboard is down: Not found: /index.html 404

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#121616]
https://flutter-dashboard.appspot.com 404:

```
Not found: /index.html
```

**Comment by ricardoamador** [comment]
Not an issue.

**Comment by jmagman** [comment]
From Discord:
@drewroengoogle: "It looked like the dashboard traffic was splitting to two versions of dashboard, and one of them was causing a 404, so I switched the traffic to all point to the most recent build"
@ricardoamador: "Yeah that was me. Testing some changes to our transactions to Datastore."
