### ISSUE TITLE
Because <app> depends on google_sign_in >=5.4.4 which requires Flutter SDK version >=3.0.0, version solving failed.

### ISSUE THREAD

**Issue by verscph** [flutter/flutter#121673]
After migrating to google_sign_in 6.0.1, running the web app in debug and release mode (VS Code) is working fine. 

But building or running the release version of the web app from the command line using 
`flutter run -d chrome` 

results in an error:
```
The current Flutter SDK version is 2.10.5.

Because <app> depends on google_sign_in >=5.4.4 which requires Flutter SDK version >=3.0.0, version solving failed.
Running "flutter pub get" in <app>...                                
pub get failed (1; Because <app> depends on google_sign_in >=5.4.4 which requires Flutter SDK version >=3.0.0, version solving failed.)
```

google_sign_in 6.0.1 release documentation on pub.dev shows the minimum Dart SDK version should be 2.14. 

`fluttter --version` on my machine gives:
```
Flutter 2.10.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5464c5bac7 (11 months ago) • 2022-04-18 09:55:37 -0700
Engine • revision 57d3bac3dd
Tools • Dart 2.16.2 • DevTools 2.9.2
```

Is Flutter SDK version >=3.0.0 a requirement for google_sign_in 6.0.1?

**Comment by danagbemava-nc** [comment]
Hi @verscph, `google_sign_in` and the 1st party plugins all have their minimum flutter versions set to 3.0.0 now so you'll need to upgrade to at least flutter 3.0.0 to be able to use them. For `google_sign_in` this was actually changed in v5.5.4. See the changelog https://pub.dev/packages/google_sign_in/changelog#544

**Comment by stuartmorgan** [comment]
> pub.dev shows the minimum Dart SDK version should be 2.14.

Minimum Dart SDK and minimum Flutter SDK are separate things; a package can require recent Flutter APIs but not use new Dart APIs.

Closing as the error message is correct, and reflects the package's pubspec.yaml.
