### ISSUE TITLE
Bug with example code Flutter tutorial

### ISSUE THREAD

**Issue by neilself** [flutter/flutter#12168]
This section appears to have code where the send button doesn't work: https://codelabs.developers.google.com/codelabs/flutter/#7

The issue here is that in the onPressed parameter here:

"onPressed: _isComposing ?            // modified
                                  () =>  _handleSubmitted(_textController.text) :// modified
                                  null,"

If you pass a null in there initially (which you will since initially _isComposing is false), then the send button will become greyed out. Because of this, even though _isComposing will change later after typing, the send button doesn't change. At least, that's what I think is happening.

**Comment by Hixie** [comment]
You add the code that updates _isComposing earlier on; maybe you missed that part?
The build method is rerun each time you call setState.
