### ISSUE TITLE
Setting package name in Image.asset causes image not to load

### ISSUE THREAD

**Issue by moneer-muntazah** [flutter/flutter#121679]
If I'm using a package and that package loads an asset I have to specify the package name. I have built an app to test my application so it uses my app as a dependency therefore I have to pass the package name  like so

```
Scaffold(
      body: Center(
        child: Image.asset('assets/images/flutter_bird.png',
        package: 'asset_loading_issue',),
      ),
    );
```

but this breaks the image loading if I run the app directly  so now it works with the testing package but not if I run it directly.

the directory structure is

assets/images/flutter_bird.png
lib/main.dart
pubspec.yaml

in pubspec.yaml I have
assets:
  - assets/images/

```
[√] Flutter (Channel stable, 3.7.5, on Microsoft Windows [Version 10.0.19045.2604], locale en-US)
    • Flutter version 3.7.5 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c07f788888 (6 days ago), 2023-02-22 17:52:33 -0600
    • Engine revision 0f359063c4
    • Dart version 2.19.2
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Moneer\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Moneer\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32922.545
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
      development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[!] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.74.3)
    • VS Code at C:\Users\Moneer\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (4 available)
    • Nokia 2 3 (mobile) • PT99621AA1A30902750 • android-arm    • Android 11 (API 30)
    • Windows (desktop)  • windows             • windows-x64    • Microsoft Windows [Version 10.0.19045.2604]
    • Chrome (web)       • chrome              • web-javascript • Google Chrome 110.0.5481.178
    • Edge (web)         • edge                • web-javascript • Microsoft Edge 106.0.1370.52

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

**Comment by moneer-muntazah** [comment]
Sure here

[git@github.com:moneer-muntazah/asset_loading_issue.git](https://github.com/moneer-muntazah/asset_loading_issue)

it's very simple just remove package: 'asset_loading_issue' and the image will display if you add it, it wont'. The issue is that if I am to use this as a package I need to have this value set

**Comment by huycozy** [comment]
This is caused by your project is missing the package. You need to create the corresponding package inside the current project and it will work even when you run the project directly.

For eg:

<img width="799" alt="Screenshot 2023-03-01 at 18 59 17" src="https://user-images.githubusercontent.com/104349824/222209472-9863ddb0-6abe-4560-892e-343bc031ba15.png">

Please try and confirm if it works for you. (Please also check the reference documentation: https://docs.flutter.dev/development/packages-and-plugins/developing-packages#dart)

**Comment by moneer-muntazah** [comment]
Hi thank you,

I apologize there seems to be some confusion. I have a use case where my application which uses assets like so 

```
Image.asset('assets/images/flutter_bird.png')
```

needs to be used as a dependency in a testing app. The testing app displays the screens in the app in different ways for development reasons. The issue is assets won't be displayed when I run the testing apps because the package param is not set in the dependency and if I set it, it won't be displayed when I run the application directly- not as a dependency

I hope this is clear now.

**Comment by danagbemava-nc** [comment]
Hi @moneer-muntazah, are you in control of the testing app? If you are, I think it might be best for you to create a widget that can load the images and adds the package name based on whether or not you're running from the testing app. 
The image is not being loaded because if you specify the package within the app, it looks in the packages folder to see if there's a package with that name that contains the assets, but since you can't add your app as a dependency of itself, it can’t find that package and load the image.
