### ISSUE TITLE
Material border regression

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#12165]
## Steps to Reproduce

Reported by Posse, here's a reduced test case.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: new Scaffold(
        body: new Center(
          child: new Material(
            color: Colors.blue,
            child: new Container(
              width: 100.0,
              height: 100.0,
              decoration: new BoxDecoration(
                border: new Border.all(
                  width: 10.0,
                  color: Colors.red,
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

What I see:

<img width="95" alt="screen shot 2017-09-19 at 8 26 27 am" src="https://user-images.githubusercontent.com/394889/30600690-fe8f1274-9d14-11e7-8a96-bdfab7645693.png">

What I expect to see:

<img width="124" alt="screen shot 2017-09-19 at 8 26 18 am" src="https://user-images.githubusercontent.com/394889/30600698-04239764-9d15-11e7-8685-89193a8b5440.png">

If I change `Material` to `Container` it works fine.

`git bisect` tells me this is was introduced in @Hixie's recent border refactoring 9d59fb0c302cad1cd0c77ece70a818115fa1cf5c

**Comment by Hixie** [comment]
Weird.

**Comment by Hixie** [comment]
Oh, I see. The red border is being painted in the wrong place and the Material is clipping it. Fix incoming.
