### ISSUE TITLE
Missing plugin exception after adding flutter plugin to the flutter module

### ISSUE THREAD

**Issue by MaduraDiasTreinetic** [flutter/flutter#121664]
i have add flutter module to the ios application using App to app method. after  add a flutter plugin to the module it got "missing plugin exception" error.

Flutter Doctor result.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.0.1 22A400 darwin-x64, locale
    en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.75.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

**Comment by darshankawar** [comment]
@MaduraDiasTreinetic 
Can you provide complete reproducible code sample or a sample repo that we can clone to verify the reported behavior ?

You can take a look at below add2app github samples and compare with your implementation and see if you are missing any in your code that is causing the error.

https://github.com/flutter/samples/tree/main/add_to_app

**Comment by MaduraDiasTreinetic** [comment]
i have followed your sample code and fixed my code, Thank you for your support
