### ISSUE TITLE
ci.yaml is not getting run on pull request, possible dropped messages from pubsub

### ISSUE THREAD

**Issue by ricardoamador** [flutter/flutter#121647]
ci.yaml is either not getting scheduled or in this case I believe not getting rescheduled. 
https://github.com/flutter/engine/pull/39915

For some reason earlier the check was getting scheduled. Tests were failing and several commits were sent to make fixes for those tests. It appears that the test was never rescheduled as there are logs saying that there are no checkRuns for this pr.

![image](https://user-images.githubusercontent.com/32242716/221999459-97de51f8-6b95-432f-a8e7-ab1897565221.png)

Here is the earlier run which shows that the ci.yaml validation test was in fact scheduled and did run to completion.
![image](https://user-images.githubusercontent.com/32242716/221999681-3ff0b2b6-9175-4e21-a387-1d2ab5481977.png)

From an initial look at the code it appears that the checkRuns did not get scheduled.

**Comment by ricardoamador** [comment]
In each case whether it saw the checkRuns or did not the hash was the same: 465dd99d7c0f9ab49bca6fefc46146f3307e4296

**Comment by ricardoamador** [comment]
This is also not the newest change but the one before it with failed runs. We should be looking to update the hash bff496f. In the picture below that is the newest hash. It looks like we did not pick up change request for this new hash. Looking to see if this was github failing to deliver a payload.

![image](https://user-images.githubusercontent.com/32242716/222003478-63b8158d-0bae-4788-a8c0-91378aeeee94.png)

**Comment by ricardoamador** [comment]
We did get the webhook payload from github with the correct information:
```
{
  "action": "synchronize",
  "number": 39915,
  "pull_request": {
    "url": "https://api.github.com/repos/flutter/engine/pulls/39915",
    "id": 1255960141,
    "node_id": "PR_kwDOAlZRSc5K3G5N",
    "html_url": "https://github.com/flutter/engine/pull/39915",
    "diff_url": "https://github.com/flutter/engine/pull/39915.diff",
    "patch_url": "https://github.com/flutter/engine/pull/39915.patch",
    "issue_url": "https://api.github.com/repos/flutter/engine/issues/39915",
    "number": 39915,
    "state": "open",
    "locked": false,
    "title": "[web] Remove non-ShadowDom mode",
    "user": {
      "login": "mdebbar",
      "id": 1278212,
      "node_id": "MDQ6VXNlcjEyNzgyMTI=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1278212?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mdebbar",
      "html_url": "https://github.com/mdebbar",
      "followers_url": "https://api.github.com/users/mdebbar/followers",
      "following_url": "https://api.github.com/users/mdebbar/following{/other_user}",
      "gists_url": "https://api.github.com/users/mdebbar/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mdebbar/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mdebbar/subscriptions",
      "organizations_url": "https://api.github.com/users/mdebbar/orgs",
      "repos_url": "https://api.github.com/users/mdebbar/repos",
      "events_url": "https://api.github.com/users/mdebbar/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mdebbar/received_events",
      "type": "User",
      "site_admin": false
    },
    "body": "If we still want to do this, here's a quick PR :)\r\n\r\nFixes https://github.com/flutter/flutter/issues/116204",
    "created_at": "2023-02-27T18:30:33Z",
    "updated_at": "2023-02-28T16:11:54Z",
    "closed_at": null,
```

**Comment by ricardoamador** [comment]
It appears we just "lost" this or pub sub did not send it to us. Once I updated the branch the checks were immediately picked up and everything appeared as normal with all the checks getting kicked off. We never received the updated synchronized request for the issue above.

**Comment by keyonghan** [comment]
Obsolete. Will revisit if this happens again.
