### ISSUE TITLE
Builds are not "clean"

### ISSUE THREAD

**Issue by tiwiz** [flutter/flutter#12176]
When rebuilding, changes are not always applied

## Steps to Reproduce
Please check [this video](https://drive.google.com/file/d/0B77uAjKpun_RVjhTc01KS3dqcE0/view?usp=sharing) for steps to reproduce

**Comment by Hixie** [comment]
cc @tvolkert @a-siva

**Comment by Hixie** [comment]
(This might be obsolete.)

**Comment by zoechi** [comment]
dup of #16604 ?

**Comment by zoechi** [comment]
Duplicate of #16604
