### ISSUE TITLE
flutter_plugin_tools format stuck waiting.

### ISSUE THREAD

**Issue by kroikie** [flutter/flutter#12177]
## Steps to Reproduce

run:
flutter packages pub global run flutter_plugin_tools format

## Output

Formatting all .dart files...
Waiting for another flutter command to release the startup lock...

## Flutter Doctor

flutter doctor
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-US, channel master)
    • Flutter at /Users/arthurthompson/opt/flutter
    • Framework revision d29c4a3c97 (68 minutes ago), 2017-09-19 13:07:57 -0700
    • Engine revision dd1e0b59ec
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /Users/arthurthompson/opt/android/sdk
    • Platform android-26, build-tools 26.0.1
    • ANDROID_HOME = /Users/arthurthompson/opt/android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.2
    • CocoaPods version 1.2.1

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.0 Preview.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.4)
    • Flutter plugin version 17.0
    • Dart plugin version 172.4155.35

[✓] Connected devices
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 6.0 (API 23) (emulator)

**Comment by kroikie** [comment]
Nvm this was user error, I did not have all the necessary tools on my path.

**Comment by duzenko** [comment]
Which tool was missing? I got the same issue.
