### ISSUE TITLE
Suggestion: remove filtering and search from the new DropdownMenu widget.

### ISSUE THREAD

**Issue by ljmatan** [flutter/flutter#121726]
[As @danagbemava-nc says](https://github.com/flutter/flutter/issues/121456#issuecomment-1445936523), if we're to use a lot of entries in the DropdownMenu, we're better off not using it. 

If that's the case, I'd suggest for the search and filtering capabilities to be removed, since we wouldn't scroll through too many items at once anyway, and it's therefore redundant.

**Comment by moffatman** [comment]
Even if performance is poor with many items, the filtering is still useful to quickly select an item with the keyboard amongst a few choices.

**Comment by darshankawar** [comment]
@ljmatan 
Agreeing with @moffatman's comment and also the fact that search and filtering is part and parcel of basic functionality of dropdownmenu widget as also mentioned in the [documentation](https://api.flutter.dev/flutter/material/DropdownMenu-class.html).

If you are looking for quick search feature / functionality in the said widget, you can checkout https://pub.dev/packages/dropdown_search community package and see if it helps in your case.

Coming back to your suggestion, it doesn't sound like feasible / valid. With that being said, I'll go ahead and close as not valid. If you disagree, please write in comments and I'll reopen it.
