### ISSUE TITLE
Remove ViewConfiguration and PlatformConfiguration from `dart:ui`

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#121742]
Both the `PlatformDispatcher` [1] and the `FlutterView` [2] are backed by immutable configuration objects: `ViewConfiguration` [3] and `PlatformConfiguration` [4]. They both have a `configuration` getter [5][6] that exposes the configuration object. At the same time, they implement convenience getter to retrieve values from the configuration: e.g. instead of calling `FlutterView.viewConfiguration.devicePixelRatio` one can call `FlutterView.devicePixelRatio` directly. This is true for all other values exposed by the configuration as well.

AFAIK, this setup doesn't provide us with any benefits and just adds more complexity through indirection: There are two ways to do the same things and when it comes to testing and mocking it is more complicated to keep the mock value on the FlutterView in sync with the same value exposed by its configuration.

Proposal: Let's simplify this by removing the `ViewConfiguration` and `PlatformConfiguration` classes as well as the `FlutterView.viewConfiguration` and `PlatformConfiguration.configuration` getters from the public interface of `dart:ui` and instead always use the getters on `FlutterView` or `PlatformDispatcher` directly to obtain these values.

[1] https://master-api.flutter.dev/flutter/dart-ui/FlutterView-class.html
[2] https://master-api.flutter.dev/flutter/dart-ui/PlatformDispatcher-class.html
[3] https://master-api.flutter.dev/flutter/dart-ui/ViewConfiguration-class.html
[4] https://master-api.flutter.dev/flutter/dart-ui/PlatformConfiguration-class.html
[5] https://master-api.flutter.dev/flutter/dart-ui/FlutterView/viewConfiguration.html
[6] https://master-api.flutter.dev/flutter/dart-ui/PlatformDispatcher/configuration.html

**Comment by goderbauer** [comment]
cc @gspencergoog You originally added these in https://github.com/flutter/engine/pull/21932. Is there anything we're missing that is making these configurations useful?
cc @pdblasi-google Your PR https://github.com/flutter/flutter/pull/121549 would probably benefit from this simplification.

**Comment by goderbauer** [comment]
Impact of these change: None of these three entities see any usage in google3 or the framework with one exception that can trivially be migrated to use a getter:

https://github.com/flutter/flutter/blob/888b7b9b19642e18e001e3edfa9438c2624d8773/packages/flutter/lib/src/gestures/gesture_settings.dart#L29

In accordance with our breaking change policy we should be able to just remove these from the public interface without deprecation period.

**Comment by gspencergoog** [comment]
No, they can safely be private or removed.  They were a way to expose the configuration of the view and platform (obviously), with an eye towards exposing things like the screen and view dimensions and location, what display they were on, etc., but those can be done in other ways.
