### ISSUE TITLE
Google Maps InfoWindow customize option in [google_maps_flutter] package

### ISSUE THREAD

**Issue by umerbutt03** [flutter/flutter#121796]
## Use case

I am not able to customize the InfoWindow in Goolge Maps.
## Proposal

Please add this customize option in google_maps_flutter package!

**Comment by stuartmorgan** [comment]
Closing as a duplicate of https://github.com/flutter/flutter/issues/52878

If you were requesting something other than that, please file a new issue and fill out the request in detail, describing exactly what customization you are looking for and how it's distinct from existing requests.
