### ISSUE TITLE
When I want to switch to another page from my google maps open page, the screen opens and quickly closes the previous page.

### ISSUE THREAD

**Issue by DenizUlucan** [flutter/flutter#121790]
I am encountering this problem on the android side in both applications.

<details>
<summary>flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.3, on Microsoft Windows [Version 10.0.22621.1265], locale tr-TR)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.6)
[√] Android Studio (version 2020.3)
[√] IntelliJ IDEA Community Edition (version 2021.2)
[√] VS Code (version 1.76.0)
[√] Connected device (4 available)
[√] HTTP Host Availability
```
</details>

youtube --> https://studio.youtube.com/video/YS5P2aQLBAM/edit

when this error happens it says this --> E/Surface ( 5737): getSlotFromBufferLocked: unknown buffer: 0xec5d4610

<details>
<summary>AndroidManifest.xml</summary>

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="tr.com.naknak.naknak_user">

   <uses-permission android:name="android.permission.INTERNET"/>
   <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
   <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
   <uses-permission android:name="android.permission.CAMERA" />
   <uses-permission android:name="android.permission.FLASHLIGHT" />

   <application
        android:label="NakNak"
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher"
        android:usesCleartextTraffic="true">
        
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
             <meta-data
              android:name="com.google.firebase.messaging.default_notification_channel_id"
              android:value="@string/default_notification_channel_id"/>
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
   
        
        <meta-data
            android:name="com.google.android.geo.API_KEY"
            android:value=""/>
    </application>
</manifest>
```
</details>

**Comment by danagbemava-nc** [comment]
Hi @DenizUlucan, please provide a complete minimal reproducible code sample so that we can investigate this. 

Please also provide the version of `google_maps_flutter` & `google_maps_flutter_android` you're using. 

Please also provide the full output of `flutter run -v` that captures any errors you may be facing. 

The link to the video you shared does not appear to be public so please provide a publicly available link. 

Thank you

**Comment by DenizUlucan** [comment]
--link-->https://www.youtube.com/shorts/YS5P2aQLBAM

It doesn't happen in all my applications, but I get this error when I open a new file as a trial in the application that has an error.
When I run the application, the logs appear like this.

D/MapsInitializer(13298): preferredRenderer: null
D/zzcb    (13298): preferredRenderer: null
I/Google Maps Android API(13298): Google Play services package version: 230617040
I/Google Maps Android API(13298): Google Play services maps renderer version(legacy): 203115000

android/app/build.gradle


def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keyProperties = new Properties()
def keyPropertiesFile = rootProject.file('key.properties')
if(keyPropertiesFile.exists()){
    keyProperties.load(new FileInputStream(keyPropertiesFile))
}

android {
    compileSdkVersion 33

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "tr.com.naknak.naknakuser"
        minSdkVersion 20
        targetSdkVersion 31
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    signingConfigs {
        release{
            keyAlias keyProperties['keyAlias']
            keyPassword keyProperties['keyPassword']
            storeFile file(keyProperties['storeFile'])
            storePassword keyProperties['storePassword']
        }
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
        // Import the BoM for the Firebase platform
    implementation platform('com.google.firebase:firebase-bom:31.0.1')
    implementation "androidx.browser:browser:1.3.0"
    // Declare the dependency for the Firebase Authentication library
    // When using the BoM, you don't specify versions in Firebase library dependencies
}


apply plugin: 'com.google.gms.google-services'



android/build.gradle
buildscript {
    ext.kotlin_version = '1.6.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.google.gms:google-services:4.3.10'
        classpath 'com.android.tools.build:gradle:7.1.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

pubspec.yaml
name: naknak_user
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.5+22

environment:
  sdk: ">=2.16.2 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  
  flutter_lints: ^2.0.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^2.1.1
  #firebase_auth: ^4.1.1
  firebase_database: ^10.0.0
  firebase_storage: ^11.0.4
  fluttertoast: ^8.0.9
  google_maps_flutter: ^2.2.4 
  geolocator: ^8.2.1
  geocoding: ^2.0.1
  http: ^0.13.4
  provider: ^6.0.2
  flutter_polyline_points: ^1.0.0
  flutter_geofire: ^2.0.1
  smooth_star_rating_nsafe: ^1.0.0+1
  animated_text_kit: ^4.2.2
  intl: ^0.17.0
  image_picker: ^0.8.5+3
  get: ^4.6.5
  flutter_datetime_picker: ^1.5.1
  time_picker_sheet: ^0.0.2+1
  firebase_messaging: ^14.0.4
  slide_countdown: ^0.2.8
  overlay_support: ^2.0.1
  package_info_plus: ^1.4.3
  pinput: ^2.2.12
  shared_preferences: ^2.0.10
  uuid: ^3.0.6
  url_launcher: ^6.1.6
  webview_flutter: ^3.0.4
  flutter_credit_card: ^2.0.0
  crypto: ^3.0.2
  enough_convert: ^1.6.0
  app_tracking_transparency: ^2.0.3




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.11.0"

#  flutter pub get
#  flutter pub run flutter_launcher_icons

flutter_icons:
  image_path: "images/naknak-logo.png"
  ios: true
  android: true

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/icons/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

**Comment by danagbemava-nc** [comment]
Hi @DenizUlucan, we'll need a complete minimal reproducible code sample, preferably without any 3rd party packages/plugins so that we can investigate this. 

Thank you

**Comment by DenizUlucan** [comment]
this is my minimally reproducible code sample, after the necessary google maps installations are made, you can see the following texts when you switch between the pages in the drawer (only android)

E/Surface ( 5893): getSlotFromBufferLocked: unknown buffer: 0xf517a110
E/Surface ( 5893): getSlotFromBufferLocked: unknown buffer: 0xf517ea90
E/Surface ( 5893): getSlotFromBufferLocked: unknown buffer: 0xf5176f10

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  runApp(
    MaterialApp(home: Try()),
  );
}

class Page1 extends StatelessWidget {
  const Page1({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: SafeArea(
          child: Column(
        children: [
          Expanded(
            child: GridView.count(
                crossAxisCount: 3,
                crossAxisSpacing: 4.0,
                mainAxisSpacing: 8.0,
                children: List.generate(10, (index) {
                  return FlutterLogo(
                    size: 100,
                  );
                })),
          )
        ],
      )),
    );
  }
}

class Page2 extends StatelessWidget {
  const Page2({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: SafeArea(
          child: Column(
        children: [
          Expanded(
            child: GridView.count(
                crossAxisCount: 3,
                crossAxisSpacing: 4.0,
                mainAxisSpacing: 8.0,
                children: List.generate(10, (index) {
                  return Container(
                    color: Colors.red,
                    child: FlutterLogo(
                      size: 100,
                      style: FlutterLogoStyle.stacked,
                    ),
                  );
                })),
          )
        ],
      )),
    );
  }
}

class Try extends StatelessWidget {
  Try({Key? key}) : super(key: key);
  GlobalKey<ScaffoldState> sKey = GlobalKey<ScaffoldState>();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        key: sKey,
        drawer: Container(
          width: 100,
          color: Colors.white,
          child: Column(
            children: [
              ElevatedButton(
                  onPressed: () {
                    Navigator.push(context,
                        MaterialPageRoute(builder: (context) => Page1()));
                  },
                  child: Text("Page1")),
              ElevatedButton(
                  onPressed: () {
                    Navigator.push(context,
                        MaterialPageRoute(builder: (context) => Page2()));
                  },
                  child: Text("Page2"))
            ],
          ),
        ),
        body: Stack(
          children: [
            GoogleMap(
              padding: const EdgeInsets.only(bottom: 100, top: 50, right: 20),
              mapType: MapType.normal,
              myLocationEnabled: true,
              zoomGesturesEnabled: true,
              zoomControlsEnabled: true,
              initialCameraPosition: const CameraPosition(
                target: LatLng(41.015137, 28.979530),
                zoom: 13,
              ),
              onMapCreated: (GoogleMapController controller) {},
            ),
            Positioned(
              top: 50.0,
              left: 30.0,
              child: GestureDetector(
                onTap: () {
                  sKey.currentState!.openDrawer();
                },
                child: Container(
                  height: 40,
                  width: 40,
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(7),
                    color: Colors.white,
                  ),
                  child: Icon(
                    Icons.open_in_new,
                    color: Colors.black,
                    size: 30,
                  ),
                ),
              ),
            )
          ],
        ));
  }
}

**Comment by DenizUlucan** [comment]
i downgrade my google maps verison 2.2.4 to 2.0.0 and it ran without error

**Comment by danagbemava-nc** [comment]
Hi @DenizUlucan, I just noticed that you're using an older version of flutter stable, can you upgrade to the latest version of flutter stable(3.7.6) to see if you still experience this issue? 

If you do, please provide the updated output of `flutter doctor -v`. 

Thank you
