### ISSUE TITLE
Remove recipes/packaging packages not being used anymore.

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#121735]
https://cs.opensource.google/flutter/recipes/+/main:recipes/packages/ are not used anymore. Once removed we'll need to rename https://cs.opensource.google/flutter/recipes/+/main:recipes/packaging_v2/ as packaging.

**Comment by godofredoc** [comment]
CLs:

* https://flutter-review.googlesource.com/c/recipes/+/39940
* https://flutter-review.googlesource.com/c/recipes/+/39961
* https://flutter-review.googlesource.com/c/recipes/+/39960

**Comment by godofredoc** [comment]
▐

**Comment by keyonghan** [comment]
> https://cs.opensource.google/flutter/recipes/+/main:recipes/packages/ are not used anymore. Once removed we'll need to rename https://cs.opensource.google/flutter/recipes/+/main:recipes/packaging_v2/ as packaging.

Do you mean https://cs.opensource.google/flutter/recipes/+/main:recipes/packaging? @godofredoc 
Is this something you can help with? @sealesj

**Comment by godofredoc** [comment]
That's correct, I meant packaging. The CLs are ready to review:

* https://flutter-review.googlesource.com/c/recipes/+/39960
* https://flutter-review.googlesource.com/c/recipes/+/39961
