### ISSUE TITLE
ChromeProxyService: Failed to evaluate expression 'completer': InternalError: Expression evaluation in async frames is not supported. No frame with index 14..

### ISSUE THREAD

**Issue by zarkaishyar** [flutter/flutter#121798]
ChromeProxyService: Failed to evaluate expression 'completer': InternalError: Expression evaluation in async frames is not supported. No frame with index 14..

**Comment by darshankawar** [comment]
@zarkaishyar 
Can you provide `flutter doctor -v`, a complete code sample along with steps to replicate that shows this error ?
Also, please note to use new issue template and fill out requested details so that we'll have enough info to work with. Just commenting a single line error without other details won't help us much to analyze properly.

**Comment by gopalkumr** [comment]
Same issue is with me.

Launching lib\main.dart on Chrome in debug mode...
This app is linked to the debug service: ws://127.0.0.1:59534/04bcu_l5em4=/ws
Debug service listening on ws://127.0.0.1:59534/04bcu_l5em4=/ws
 Running with sound null safety
Connecting to VM Service at ws://127.0.0.1:59534/04bcu_l5em4=/ws
ChromeProxyService: Failed to evaluate expression 'completer': InternalError: Expression evaluation in async frames is not supported. No frame with index 14..
ChromeProxyService: Failed to evaluate expression 'Firebase': InternalError: Expression evaluation in async frames is not supported. No frame with index 14..

<img width="867" alt="image" src="https://user-images.githubusercontent.com/91552766/223632207-4ea0f0a8-e49a-4a70-85ad-d5d2b89ed089.png">

<img width="571" alt="image" src="https://user-images.githubusercontent.com/91552766/223632346-2aa8dd4c-db41-4ee3-948d-fb5689b9c633.png">

**Comment by yuvansundrani** [comment]
Having the same problem, no clue how to go about it :(

**Comment by gopalkumr** [comment]
![github post](https://user-images.githubusercontent.com/91552766/224875110-038d1025-f128-4f25-9a5d-79aa1a42758f.png)

I removed  name parameter from firebase initializer, and it's working

@yuvansundrani

**Comment by poka-IT** [comment]
Same problem, I fixed it by removing async from main function.

**Comment by darshankawar** [comment]
If anybody can provide exact steps to replicate, it will help to make this issue actionable.

**Comment by Othniel16** [comment]
> If anybody can provide exact steps to replicate, it will help to make this issue actionable.

main.dart

`void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: const FirebaseOptions(
      apiKey: 'api-key',
      appId: 'app-id',
      messagingSenderId: 'sender-id',
      projectId: 'project-id',
    ),
  );
  runApp(const App());
}`

app.dart

`class App extends StatefulWidget {
  const App({super.key});

  @override
  State<App> createState() => _AppState();
}

class _AppState extends State<App> {
  var collection =
      FirebaseFirestore.instance.collection('collection').snapshots();

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<QuerySnapshot>(
        stream: collection,
        builder: (context, snapshot) {
          // issue lies here with showAlert call
          if (snapshot.hasData) showAlert(context);

          return Container();
        });
  }

  Future<void> showAlert(BuildContext context) async {
    return await showDialog(
      context: context,
      builder: (context) => AlertDialog(content: Column()),
    );
  }
}`

**Comment by paneerlovr** [comment]
I'm getting this same issue on VSCode.  All I did was create a new project, it created a boiler plate around "Flutter Demo".  I ran it as a windows app, that worked.  Then I switched to Chrome (web-javascript) for the target.  When I did, now VSCode adds an automatic breakpoint on await ui.webOnlyWarmupEngine, then after that, I get ChromeProxyService errors...

**Comment by gopalkumr** [comment]
consider adding the name in firebase initialiser 

await Firebase.initializeApp(
      name: 'your app id',
      options: const FirebaseOptions(
          apiKey: " ",
          appId: "",
          messagingSenderId: "",
          projectId: ""));
  runApp(const MyApp());
}

Mine was working when i added name.
@paneerlovr

**Comment by paneerlovr** [comment]
@gopalkumr Thanks, but I'm not even using firebase.  For some reason there's a sudden breakpoint added in web_entrypoint.dart on awaiting the ui.webOnlyWarmupEngine.  I think it's part of the flutter SDK.

Future<void> main() async {
  await ui.webOnlyWarmupEngine(
    runApp: () {
      if (entrypoint.main is _UnaryFunction) {
        return (entrypoint.main as _UnaryFunction)(<String>[]);
      }
      return (entrypoint.main as _NullaryFunction)();
    },
    registerPlugins: () {
      pluginRegistrant.registerPlugins();
    },
  );
}

ChromeProxyService: Failed to evaluate expression 'await': InternalError: Expression evaluation in async frames is not supported. No frame with index 58..

I'm new to flutter entirely, trying to figure it out...

**Comment by paneerlovr** [comment]
In case in matters, I'm behind a proxy with environment variables set.  Doctor output:

flutter -v doctor
[√] Flutter (Channel stable, 3.7.8, on Microsoft Windows [Version 10.0.19044.2728], locale en-US)
    • Flutter version 3.7.8 on channel stable at c:\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 90c64ed42b (7 days ago), 2023-03-21 11:27:08 -0500
    • Engine revision 9aa7816315
    • Dart version 2.19.5
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\khuranam\AppData\Local\Android\sdk
    • Platform android-33-ext5, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Professional 2022 17.4.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
    • Visual Studio Professional 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] VS Code (version 1.76.2)
    • VS Code at C:\Users\khuranam\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.60.0

[√] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1,::1
    • NO_PROXY contains localhost
    • NO_PROXY contains ::1
    • NO_PROXY contains 127.0.0.1

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.2728]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 111.0.5563.111
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 111.0.1661.54

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by paneerlovr** [comment]
Sorry to update again...

If I set web renderer to html instead of canvaskit, it works!

I'm trying to figure out now why the canvaskit download might be failing...

**Comment by darshankawar** [comment]
@paneerlovr 
See if [this](https://github.com/flutter/flutter/issues/96463#issuecomment-1053733920) help in your case.

**Comment by darshankawar** [comment]
Everyone else facing this issue using firebase, please report the issue in dedicated repo: https://github.com/firebase/flutterfire/issues

**Comment by darshankawar** [comment]
Everyone else facing this issue using firebase, please report the issue in dedicated repo: https://github.com/firebase/flutterfire/issues

**Comment by paneerlovr** [comment]
@darshankawar Thanks for your help, I actually figured it out by researching how to do offline PWA with flutter, thanks!
