### ISSUE TITLE
[Impeller] `FML_OS_PHYSICAL_IOS` defines in the entity layer prevent Android optimizations.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#121886]
The Android Vulkan backend is now within a stone's throw of the Metal backend on iOS. However, these defines make doing an apples to apples comparison hard. We knew these were short term workarounds to keep the OpenGL prototype going. This issue tracks prioritizing the generalization of the approach to select modern approaches on backends that support them.

**Comment by chinmaygarde** [comment]
cc @bdero @jonahwilliams

**Comment by jonahwilliams** [comment]
My current idea is to pull all/most of the FML_PHYSICAL_IOS defines into a new TU that uses a mix of runtime and platform checks to bundle the correct shaders. The rest of the impeller code base can rely on this + capabilities check to use it appropriately. Would be necessary to handle bundling this for newer versions of macOS too
