### ISSUE TITLE
Metrics upload is failing due to multiple tasks found in the datastore

### ISSUE THREAD

**Issue by ricardoamador** [flutter/flutter#121822]
Used the following hash: 92bb306bcd1b62f56ea39f359bd8b1423bb74beb

An example: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20run_debug_test_linux/125/overview
In this case several tests failed due to this issue. The run cannot complete because there are two entries for the task.

Here is an example for a task on the same run: 
![image](https://user-images.githubusercontent.com/32242716/222539111-e2173a58-f929-4b4f-b939-1c2478f99843.png)

**Comment by ricardoamador** [comment]
Somehow the run for the post submit build shown here was duplicated: 
![image](https://user-images.githubusercontent.com/32242716/222542985-abd6cb75-ebf8-4ea2-a48b-9980e37b56cb.png)

The count is shown as 708 for all of the tasks: 
![image](https://user-images.githubusercontent.com/32242716/222543074-af27d7e2-c388-43b4-8ded-0ff194e0d7c7.png)

**Comment by ricardoamador** [comment]
Okay so we definitely somehow got two pull_request events with the action being "closed". The pubsub message ids were different but for the same type of request. I was able to verify this in the logs. Both went to the same instance. These were 2 to 3 seconds apart. I am not sure what the latency is here if any.

We processed `7056746420972805` at 11:18:35 on 03/02
![image](https://user-images.githubusercontent.com/32242716/222591593-3a0905b2-39ee-4d2f-8dbc-1ee1d2a53ec1.png)

Then we processed `7056756224701923` at 11:18:38 on 03/02
![image](https://user-images.githubusercontent.com/32242716/222591980-f3ad2ea5-970c-42e7-87d1-ba0b66792bf9.png)

This somehow lead to us putting two entries for that pull request in the database. When we look up values we do not create a transaction (Not sure if that matters at this point). I did not see the error message that prints if we do find the commit in the database. 

Then we processed the following check_suite with id `11315316575` request at 11:18:48 on 03/02
![image](https://user-images.githubusercontent.com/32242716/222592504-3353a041-8506-4151-819e-ff7d18eb348c.png)

And the other check_suite with id `11315316770` for the same pr at 11:18:50 on 03/02
![image](https://user-images.githubusercontent.com/32242716/222592696-c03d079a-3f1a-425a-b7f9-423499394007.png)

Then later we received two different check_suites created for that single pull request. Those messages went to two different instances. This resulted in double the checks being generated for the post submit run.

**Comment by ricardoamador** [comment]
Okay looking at the github payload I found that github delivered two of the same message to us!

Request 1:
![image](https://user-images.githubusercontent.com/32242716/222594272-9f330052-bb36-4fb9-aedc-2e5507601e35.png)

Request 2:
![image](https://user-images.githubusercontent.com/32242716/222594572-1e77c5bd-547a-4d16-9474-0d8ec47d138c.png)

**Comment by keyonghan** [comment]
Does it mean it's a github issue and we can close this one?

**Comment by ricardoamador** [comment]
No. We have an issue here since we should have been able to catch this from happening. I had already started to wrap the calls to Datastore in transactions to hopefully prevent this. This in conjunction with a pull subscription will help greatly.

**Comment by keyonghan** [comment]
Please reopen if you see this issue again.
