### ISSUE TITLE
Localize showDatePicker

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#12185]
This issue is split from https://github.com/flutter/flutter/issues/10616 to avoid too much scope for one issue.

## Proposed scope

As part of this issue we will localize Gregorian calendar only. This will include:

 - [x] translations of numerals, week days, month names and buttons
 - [x] first day of week localization
 - [x] RTL
 - [x] move the `package:intl` dependency into `MaterialLocalizations`
 - [ ] tests

**Comment by yjbanov** [comment]
Copy of @Hixie's https://github.com/flutter/flutter/issues/10616#issuecomment-328925098:

> When we localize DatePicker, we should make sure that as a side-effect all the `intl` dependencies end up indirected through MaterialLocalizations, to enable https://github.com/flutter/flutter/issues/12050.

**Comment by PiN73** [comment]
For anyone who wants to actually localize date picker

pubspec.yaml
```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
```

main.dart
```dart
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: const <Locale>[
        // put all locales you want to support here
        const Locale('en', 'US'),
        const Locale('ru', 'RU'),
      ],
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Localizations'),
      ),
      body: Center(
        child: RaisedButton(
          child: Text('PICK DATE'),
          onPressed: () {
            showDatePicker(
              context: context,
              initialDate: DateTime.now(),
              firstDate: DateTime.now(),
              lastDate: DateTime.now().add(Duration(days: 30)),
            );
          },
        ),
      ),
    );
  }
}
```

Now date picker will use system locale if it's present in `supportedLocales` list.

Also you can force a locale for date picker of for whole app by passing `locale` parameter to `showDatePicker` or `MaterialApp`
