### ISSUE TITLE
I got this error when i am trying to run the command "flutter build apk" Exhausted heap space, trying to allocate 240 bytes

### ISSUE THREAD

**Issue by khaledmurtaja** [flutter/flutter#121845]
I have 8GB of Ram
when i am trying to run the command (flutter build apk) i was having like free space of 3GB Ram
I can not figure what is the root cause of this problem .
i can build debug mode(slow so much but it works), but i can not build apk mode
i turned off my machine so i can be sure that i am freeing up space but it did not work too .
i run with stacktrace too

khaled:android khaled$ ./gradlew assembleDebug --stacktrace

Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

WARNING:We recommend using a newer Android Gradle plugin to use compileSdk = 33

​

This Android Gradle plugin (7.2.0) was tested up to compileSdk = 32

​

This warning can be suppressed by adding

android.suppressUnsupportedCompileSdk=33

to this project's gradle.properties

​

The build will continue, but you are strongly encouraged to update your project to

use a newer Android Gradle Plugin that has been tested with compileSdk = 33

​

> Task :app:compressDebugAssets

Execution optimizations have been disabled for task ':app:compressDebugAssets' to ensure correctness due to the following reasons:

- Gradle detected a problem with the following location: '/Users/khaled/StudioProjects/blood4life/build/app/intermediates/assets/debug/mergeDebugAssets'. Reason: Task ':app:compressDebugAssets' uses this output of task ':app:copyFlutterAssetsDebug' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5/userguide/validation_problems.html#implicit_dependency for more details about this problem.

​

> Task :app:stripDebugDebugSymbols

Unable to strip the following libraries, packaging them as they are: libflutter.so.

​

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

​

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

​

See https://docs.gradle.org/7.5/userguide/command_line_interface.html#sec:command_line_warnings

​

Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.

Please consult deprecation warnings for more details.

​

BUILD SUCCESSFUL in 1m 33s

1

**Comment by darshankawar** [comment]
@khaledmurtaja 
I think this is similar to what you already reported: https://github.com/flutter/flutter/issues/121739. So take a look at this recent comment https://github.com/flutter/flutter/issues/121739#issuecomment-1453123890 for your reference.

Also, let's track this in the linked issue instead of filing new issue for same error. I'll close from here. You may comment / reply or add your feedback in that issue for better tracking.
