### ISSUE TITLE
Emoji Keycap Sequence displays incorrectly in TextField on iOS

### ISSUE THREAD

**Issue by wadeowenwatt** [flutter/flutter#121861]
if I put some emoji in front of 1️⃣, it will display. But I only type 1️⃣ in textfield, it will show two box with question mark.
It occurs with Emoji Keycap 1️⃣2️⃣3️⃣...🔟.

flutter doctor -v
```
[✓] Flutter (Channel stable, 3.7.5, on macOS 13.0.1 22A400 darwin-arm64, locale
    en-VN)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.73.1)
[✓] Connected device (4 available)
[✓] HTTP Host Availability
```

https://user-images.githubusercontent.com/73239433/222660472-899d7fec-4033-45af-abcd-bee774dd9063.mp4

**Comment by darshankawar** [comment]
@wadeowenwatt 
There's already an open issue describing your case, https://github.com/flutter/flutter/issues/36062, so follow-up in it for further updates.
Please do leave a thumbs up on the original author's post so we can track and prioritize the issue base on severity and demand. Thanks!
