### ISSUE TITLE
strong mode analysis issues using the dev sdk

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#1218]
- [ ] `[error] Field declaration RenderObject.parentData cannot be overridden in RenderSector. (flutter/flutter/examples/rendering/lib/sector_layout.dart, line 75, col 3)`
- [ ] `[error] Field declaration HitTestEntry.target cannot be overridden in BoxHitTestEntry. (flutter/flutter/packages/flutter/lib/src/rendering/box.dart, line 310, col 3)`
- [ ] `[error] The argument type 'List<T>' cannot be assigned to the parameter type 'List<TextSpan>' (flutter/flutter/packages/flutter/lib/src/widgets/basic.dart, line 1396, col 40)`
- [ ] `[error] The argument type '(dynamic) → TextSpan' cannot be assigned to the parameter type '(dynamic) → T' (flutter/flutter/packages/flutter/lib/src/widgets/basic.dart, line 1396, col 60)`
- [ ] `[error] Field declaration Simulation.tolerance= cannot be overridden in SimulationGroup. (flutter/flutter/packages/newton/lib/src/simulation_group.dart, line 36, col 3)`

When we move to `1.14.0` we'll hit these issues. Looks like the main one is about shadowing fields defined in superclasses (`...cannot be overridden in...`). @Hixie, don't know if you'll want to regex them out or change the call sites.

**Comment by Hixie** [comment]
Is there an easy way to switch SDK briefly to test this?

**Comment by devoncarew** [comment]
This guy should do it: https://github.com/flutter/flutter/pull/1223

**Comment by devoncarew** [comment]
You can also use brew locally, which is what I do (brew upgrade dart --devel).

**Comment by Hixie** [comment]
I meant locally on a Linux install. I don't really want to have to reinstall the SDK... Don't we pull one down with gclient or something? I think my path points to `.../engine/src/third_party/dart-sdk/dart-sdk/bin/`.

**Comment by abarth** [comment]
Yeah, in your engine repo, you can edit tools/dart/update.py and run gclient sync

**Comment by Hixie** [comment]
ah, right. thanks.
