### ISSUE TITLE
Flutter install/doctor still doesn't work with spaces in Windows paths see https://github.com/flutter/flutter/issues/83195

### ISSUE THREAD

**Issue by kragil** [flutter/flutter#121866]
I couldn't reopen the issue, but it is not fixed!

flutter doctor and https://docs.flutter.dev/get-started/install/windows  are giving wrong advice:

you have to do:

flutter config --android-studio-dir="C:\Program Files\Android\Android Studio" without a \ at the end

and not 

flutter config --android-studio-dir <directory>

there has to be a = and no \ at the end.

Is everybody on a Mac and Linux or why are so basic problems still around?

More info on https://github.com/flutter/flutter/issues/83195

**Comment by darshankawar** [comment]
@kragil 
I think you should open this issue in dedicated repo: https://github.com/flutter/website/issues
The documentation has a bug icon as shown below and if you click on it, will take you to the correct repo where this issue need to be reported:

<img width="332" alt="Screenshot 2023-03-03 at 6 22 20 PM" src="https://user-images.githubusercontent.com/67046386/222725081-f568247b-3d52-41f5-b943-22eff727f04f.png">

I already see few similar issues in it. Check them and see if they resemble your case. If not, you can create a new one there:

https://github.com/flutter/website/labels/os%3AWin

Closing from here.
