### ISSUE TITLE
Seeing differences in text, shadows and font when changed the rendering backend to impeller

### ISSUE THREAD

**Issue by faisalansari0367** [flutter/flutter#121863]
![with impeller](https://user-images.githubusercontent.com/61263149/222674502-96cbd90e-85af-4bb7-88bd-eb805b3bb79c.png)
![without impeller](https://user-images.githubusercontent.com/61263149/222674513-72ad4ba0-0220-4e88-812c-18f948
![headline with impeller](https://user-images.githubusercontent.com/61263149/222674808-864f838b-47e2-454e-a164-2ce9293573e0.png)
![headline without impeller](https://user-images.githubusercontent.com/61263149/222674821-b3d14e0e-c5af-41f9-9811-a87a5fbe5ac7.png)
d07cd0.png)

I changed the rendering backend engine to the impeller and I started seeing some shadows, crunched-up text, and different behavior of dialogs which were not there before

**Comment by darshankawar** [comment]
@faisalansari0367 
Can you provide `flutter doctor -v` and minimal complete code sample that shows the reported behavior ?
