### ISSUE TITLE
Enable setting of shader uniforms  on web beta channel.

### ISSUE THREAD

**Issue by j6c-001** [flutter/flutter#121841]
## Use case
Using shaders on web should be more or less the same as desktop etc.
  fooShader.setFloat(0,barValue); // barValue is not passed into the shader, fooShader.

## Proposal
Enable if possible.

**Comment by jonahwilliams** [comment]
Can you elaborate please? What isn't working? What version of flutter are you on?

**Comment by j6c-001** [comment]
I pulled the simple shade sample and confirmed uniforms are working (https://github.com/flutter/samples/tree/main/simple_shader) on web using flutter version -Flutter 3.8.0-10.1.pre • channel beta. So closing.  Taking a closer look and will open a bug if relevant.

**Comment by j6c-001** [comment]
For the sake of completeness: I found that setting the paint shader _before_ setting the uniforms apparently  prevents the values from being passed in the shader (floats are always zero)

So in this slightly modified version of the simple_shader [sample](https://github.com/flutter/samples/blob/3ef54e495cd33e3529265ba80d6ada0ec861d03b/simple_shader/lib/main.dart#L51), the following does not work. (on web using flutter version -Flutter 3.8.0-10.1.pre • channel beta.)

The shader .frag file defines the uniform: [(here)](https://github.com/flutter/samples/blob/main/simple_shader/shaders/simple.frag)
`layout(location = 0) uniform vec2 resolution;`

When  the corresponding values are set  with `setFloat(0, x)` and `setFloat(1, y)` _before_ assigning the `FragmentShader` instance to the `Paint` instance, the `resolution` value in the shader code is always zero regardless of the x & y values passed in. So this code does not work. A black screen is always rendered.
```
class ShaderPainter extends CustomPainter {
  ShaderPainter({required this.shader});
  ui.FragmentShader shader;
  final shaderPaint = Paint();
  @override
  void paint(Canvas canvas, Size size) {

    shader.setFloat(0, size.width);
    shader.setFloat(1, size.height);

    shaderPaint.shader = shader; // <------ assign shader after setting uniform doesn't work

    canvas.drawRect(
      Rect.fromLTWH(0, 0, size.width, size.height),
      shaderPaint,
    );
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) {
    return false;
  }
}
```

However if the assignment of the FragmentShader instance to the Paint instance is moved before the  calls to` setFloat()`. So the following produces the expected result showing the blue gradient:

```
class ShaderPainter extends CustomPainter {
  ShaderPainter({required this.shader});
  ui.FragmentShader shader;
  final shaderPaint = Paint();
  @override
  void paint(Canvas canvas, Size size) {

    shaderPaint.shader = shader; // <------ assign shader before setting uniform works

    shader.setFloat(0, size.width);
    shader.setFloat(1, size.height);
   
    canvas.drawRect(
      Rect.fromLTWH(0, 0, size.width, size.height),
      shaderPaint,
    );
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) {
    return false;
  }
}
```
