### ISSUE TITLE
Getting this error when trying to run "flutter build apk" Exhausted heap space, trying to allocate 240 bytes.

### ISSUE THREAD

**Issue by khaledmurtaja** [flutter/flutter#121812]
## Steps to Reproduce

this is the output after running flutter build apk
Exhausted heap space, trying to allocate 240 bytes.
../../third_party/dart/runtime/vm/object.cc: 2803: error: Out of memory.
version=2.19.3 (stable) (Tue Feb 28 15:52:19 2023 +0000) on "macos_arm"
pid=2828, thread=-1, isolate_group=isolate(0x7fae60001000), isolate=isolate(0x7fae60006600)
os=macos, arch=arm, comp=no, sim=no
isolate_instructions=0, vm_instructions=0
  pc 0x0000000102dd03a5 fp 0x00007ffeecfb8630 dart::Profiler::DumpStackTrace(void*)+0x85
  pc 0x0000000102c50334 fp 0x00007ffeecfb8710 dart::Assert::Fail(char const*, ...) const+0x84
  pc 0x0000000102d5b642 fp 0x00007ffeecfb8760 dart::Object::Allocate(long, long, dart::Heap::Space, bool)+0x122
  pc 0x0000000102d8514f fp 0x00007ffeecfb87a0 dart::Instructions::New(long, bool)+0x4f
  pc 0x0000000102d8b7e2 fp 0x00007ffeecfb8820 dart::Code::FinalizeCode(dart::FlowGraphCompiler*, dart::compiler::Assembler*, dart::Code::PoolAttachment, bool, dart::CodeStatistics*)+0xa2
  pc 0x0000000102d8bb6a fp 0x00007ffeecfb8840 dart::Code::FinalizeCodeAndNotify(char const*, dart::FlowGraphCompiler*, dart::compiler::Assembler*, dart::Code::PoolAttachment, bool, dart::CodeStatistics*)+0x2a
  pc 0x0000000102e2fb4a fp 0x00007ffeecfb89e0 dart::StubCode::GetBuildMethodExtractorStub(dart::compiler::ObjectPoolBuilder*, bool)+0x15a
  pc 0x0000000102ce9abc fp 0x00007ffeecfb8fc0 dart::Dart::InitializeIsolate(unsigned char const*, unsigned char const*, unsigned char const*, long, dart::IsolateGroup*, void*)+0x43c
  pc 0x00000001030e7a62 fp 0x00007ffeecfb94f0 dart::CreateIsolate(dart::IsolateGroup*, bool, char const*, void*, char**)+0xc2
  pc 0x00000001030e7f98 fp 0x00007ffeecfb95c0 Dart_CreateIsolateGroupFromKernel+0x1b8
  pc 0x0000000102c47dc4 fp 0x00007ffeecfb9760 dart::bin::main(int, char**)+0x824
  pc 0x00007fff51cea015 fp 0x00007ffeecfb9770 start+0x1
-- End of DumpStackTrace
Dart snapshot generator failed with exit code -6
Exhausted heap space, trying to allocate 208 bytes.
../../third_party/dart/runtime/vm/object.cc: 2803: error: Out of memory.
version=2.19.3 (stable) (Tue Feb 28 15:52:19 2023 +0000) on "macos_x64"
pid=2830, thread=-1, isolate_group=isolate(0x7feff4800a00), isolate=isolate(0x7feff4806600)
os=macos, arch=x64, comp=yes, sim=no
isolate_instructions=0, vm_instructions=0
  pc 0x000000010ca35895 fp 0x00007ffee3362670 dart::Profiler::DumpStackTrace(void*)+0x85
  pc 0x000000010c8a6334 fp 0x00007ffee3362750 dart::Assert::Fail(char const*, ...) const+0x84
  pc 0x000000010c9b6302 fp 0x00007ffee33627a0 dart::Object::Allocate(long, long, dart::Heap::Space, bool)+0x132
  pc 0x000000010c9e5c2f fp 0x00007ffee33627e0 dart::Instructions::New(long, bool)+0x4f
  pc 0x000000010c9ec582 fp 0x00007ffee3362860 dart::Code::FinalizeCode(dart::FlowGraphCompiler*, dart::compiler::Assembler*, dart::Code::PoolAttachment, bool, dart::CodeStatistics*)+0xa2
  pc 0x000000010c9ec92a fp 0x00007ffee3362880 dart::Code::FinalizeCodeAndNotify(char const*, dart::FlowGraphCompiler*, dart::compiler::Assembler*, dart::Code::PoolAttachment, bool, dart::CodeStatistics*)+0x2a
  pc 0x000000010ca96bea fp 0x00007ffee3362a20 dart::StubCode::GetBuildMethodExtractorStub(dart::compiler::ObjectPoolBuilder*, bool)+0x15a
  pc 0x000000010c94341c fp 0x00007ffee3363000 dart::Dart::InitializeIsolate(unsigned char const*, unsigned char const*, unsigned char const*, long, dart::IsolateGroup*, void*)+0x49c
  pc 0x000000010cd5d2f2 fp 0x00007ffee3363530 dart::CreateIsolate(dart::IsolateGroup*, bool, char const*, void*, char**)+0xc2
  pc 0x000000010cd5d838 fp 0x00007ffee3363600 Dart_CreateIsolateGroupFromKernel+0x1b8
  pc 0x000000010c89ddc4 fp 0x00007ffee33637a0 dart::bin::main(int, char**)+0x824
  pc 0x00007fff51cea015 fp 0x00007ffee33637b0 start+0x1
-- End of DumpStackTrace
Dart snapshot generator failed with exit code -6
Exhausted heap space, trying to allocate 240 bytes.
../../third_party/dart/runtime/vm/object.cc: 2803: error: Out of memory.
version=2.19.3 (stable) (Tue Feb 28 15:52:19 2023 +0000) on "macos_simarm64"
pid=2829, thread=-1, isolate_group=isolate(0x7fe970002e00), isolate=isolate(0x7fe970007400)
os=macos, arch=arm64, comp=yes, sim=yes
isolate_instructions=0, vm_instructions=0
  pc 0x000000010fdc6975 fp 0x00007ffedffd1660 dart::Profiler::DumpStackTrace(void*)+0x85
  pc 0x000000010fc37334 fp 0x00007ffedffd1740 dart::Assert::Fail(char const*, ...) const+0x84
  pc 0x000000010fd47482 fp 0x00007ffedffd1790 dart::Object::Allocate(long, long, dart::Heap::Space, bool)+0x132
  pc 0x000000010fd76daf fp 0x00007ffedffd17d0 dart::Instructions::New(long, bool)+0x4f
  pc 0x000000010fd7d612 fp 0x00007ffedffd1850 dart::Code::FinalizeCode(dart::FlowGraphCompiler*, dart::compiler::Assembler*, dart::Code::PoolAttachment, bool, dart::CodeStatistics*)+0xa2
  pc 0x000000010fd7d9ba fp 0x00007ffedffd1870 dart::Code::FinalizeCodeAndNotify(char const*, dart::FlowGraphCompiler*, dart::compiler::Assembler*, dart::Code::PoolAttachment, bool, dart::CodeStatistics*)+0x2a
  pc 0x000000010fe32cba fp 0x00007ffedffd1a10 dart::StubCode::GetBuildMethodExtractorStub(dart::compiler::ObjectPoolBuilder*, bool)+0x15a
  pc 0x000000010fcd3f1c fp 0x00007ffedffd1ff0 dart::Dart::InitializeIsolate(unsigned char const*, unsigned char const*, unsigned char const*, long, dart::IsolateGroup*, void*)+0x49c
  pc 0x00000001100f1392 fp 0x00007ffedffd2520 dart::CreateIsolate(dart::IsolateGroup*, bool, char const*, void*, char**)+0xc2
  pc 0x00000001100f18d8 fp 0x00007ffedffd25f0 Dart_CreateIsolateGroupFromKernel+0x1b8
  pc 0x000000010fc2edc4 fp 0x00007ffedffd2790 dart::bin::main(int, char**)+0x824
  pc 0x00007fff51cea015 fp 0x00007ffedffd27a8 start+0x1
-- End of DumpStackTrace
Dart snapshot generator failed with exit code -6
Target android_aot_release_android-arm failed: Exception: AOT snapshotter exited with code -6
Target android_aot_release_android-x64 failed: Exception: AOT snapshotter exited with code -6
Target android_aot_release_android-arm64 failed: Exception: AOT snapshotter exited with code -6

FAILURE: Build failed with an exception.

* Where:
Script '/Users/khaled/Developer/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1151

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command '/Users/khaled/Developer/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

**Comment by Doraemonhub** [comment]
请问你是怎么解决了？
