### ISSUE TITLE
After drag and stop, finger lift can still cause a small position shift

### ISSUE THREAD

**Issue by xster** [flutter/flutter#12181]
Seems to happen on Android and iOS.

After a drag and a complete stop, the finger lifting motion can still cause a small movement which happens more or less with the same frequency on native Android but seems mostly suppressed on native iOS. 

Match on iOS with a filter after stopped scrolls.

**Comment by xster** [comment]
cc @sethladd

**Comment by sethladd** [comment]
Sounds like a good characterization of the effect. Thanks for opening this issue!

**Comment by xster** [comment]
I don't know if I'm losing my mind. @sethladd can you try it again? It seems like I'm no longer experiencing this issue.

**Comment by sethladd** [comment]
Happy to try again!

**Comment by sethladd** [comment]
Still happening on Alpha.

**Comment by sethladd** [comment]
And still happening on master (as of today)

**Comment by Hixie** [comment]
@sethladd can you work with @xster to see if you can reproduce the issue on a device while logging all input events? It would be good to get the precise series of touches that trigger this, so that we can then study that precise sequence.

**Comment by sethladd** [comment]
happy to do whatever it takes. I confirmed with @xster while @xster was watching, and I believe he was able to repro, as well.

**Comment by xster** [comment]
Ya, I'm good. Will send a fix.
