### ISSUE TITLE
LogicalKeyboardKey returns wrong label when pressing shift + asterisk

### ISSUE THREAD

**Issue by LucasXu0** [flutter/flutter#121855]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Press Shift and Asterisk.

**Expected results:** 
In flutter 3.0.5, the callback from the `Focus` widget returns LogicalKeyboardKey.Asterisk.

**Actual results:** 
In flutter 3.3.10 or 3.7.5, the callback from the `Focus` widget returns LogicalKeyboardKey.Digit8.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Focus(
          autofocus: true,
          onKey: (node, event) {
            print('event = $event');
            return KeyEventResult.ignored;
          },
          child: Container(),
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Flutter 3.0.5**
<img width="1624" alt="Screenshot 2023-03-03 at 13 28 25" src="https://user-images.githubusercontent.com/11863087/222640406-da2c54e7-a011-4c68-a041-79165f6a39b3.png">

**Flutter 3.3.10 or 3.7.5**
<img width="1580" alt="Screenshot 2023-03-03 at 13 35 36" src="https://user-images.githubusercontent.com/11863087/222640462-27cda345-29f2-4805-a82a-f0155474955a.png">

**Comment by darshankawar** [comment]
@LucasXu0 
Check [this](https://github.com/flutter/flutter/issues/90167) related / similar issue for your reference and [this](https://github.com/flutter/flutter/issues/90167#issuecomment-1184876681) comment and see if it helps in your case to resolve.

**Comment by LucasXu0** [comment]
Thanks, @darshankawar. Let me check the issue.
