### ISSUE TITLE
Can anyone help me? I Couldn't find any solution for this

### ISSUE THREAD

**Issue by GisangLee** [flutter/flutter#121864]
1. I have sub routes
    - /question
    - /question/:qid
2. I made list of questions wrapped by GestureWidget to go to question detail screen when tap each question

Here is my Code

A. question list screen
<img width="537" alt="image" src="https://user-images.githubusercontent.com/48057905/222678392-f69cc01a-a92f-462a-800f-bbddc6178de0.png">

------------------------

B. router
<img width="627" alt="image" src="https://user-images.githubusercontent.com/48057905/222678430-b9833ac8-7f48-42e6-9c62-3a7fa13caa91.png">

--------------------------

C. Question Detail screen
<img width="669" alt="image" src="https://user-images.githubusercontent.com/48057905/222678845-19dd305f-f87a-4bad-a45c-a971c318e26b.png">

----------------------------------

BUT I GOT this ERROR

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/48057905/222678205-4ce2ae7c-04a4-4df4-a86c-0e49702e2815.png">

HOW can I solve this?

**Comment by darshankawar** [comment]
@GisangLee 
Your question is better suited for support channels like StackOverflow, so please ask the same there to get solution.
Closing from here.
