### ISSUE TITLE
[web] On hot restart _canvasKitVariant isn't initialized

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#121905]
Error being thrown:
```
The following LateError was thrown during performLayout():
LateInitializationError: Field '_canvasKitVariant' has not been initialized.
```

This is because we only set that variable when we download CanvasKit. On hot restart, we don't re-download CanvasKit so we never set the variable again, and it remains uninitialized.

**Comment by jpdlr** [comment]
So I haven't changed anything, on my old laptop it works fine I can hot restart.
Got a new laptop and on this one, it gets the same error. For me, it says that 'Icon'  is the problem.

**Comment by jpdlr** [comment]
It is only on the master channel that this error occurs. Switching to 'stable' fixes this issue for anyone that might run into this problem.

**Comment by chasanpro** [comment]
Switch Flutter Channel to stable by running
**Flutter channel stable
Flutter upgrade** 
Fixed the '_canvasKitVariant' has not been initialized. issue

**Comment by volgin** [comment]
I am on beta channel, and I see this issue.
