### ISSUE TITLE
[video_player] VidePlayerController.network() datasource datatype should be to Uri

### ISSUE THREAD

**Issue by cscoderr** [flutter/flutter#121927]
## Use case
Video is not loading if there is space between the URI
if we have something like this `https://flutter.github.io/assets for api docs/assets/videos/bee.mp4` the video won't load unless you parse it with Uri.parse()

## Proposal
Change the VideoController.network() datasource from String to Uri

**Comment by stuartmorgan** [comment]
This isn't something we would do a breaking change for, but we can deprecate the current version and add a `networkUri`, similar to what we did with `url_launcher`.

> Video is not loading if there is space between the URI

The reason it's not loading is that that's not a valid URI; the documentation says that the string must be a URI, and a URI cannot contain unencoded spaces.

We should make the change since violating the API requirements a common mistake with `String` URIs (as was the motivation for `url_launcher`), but it is a bug in the calling code.

**Comment by cscoderr** [comment]
> The reason it's not loading is that that's not a valid URI; the documentation says that the string must be a URI, and a URI cannot contain unencoded spaces.

Yes i understand but i think most people pays attention to the docs example more than reading the docs so introducing new networkUri will be great to avoid something like this in future especially for beginners

**Comment by cscoderr** [comment]
i have worked on the PR but needs to be sure as its a breaking change

**Comment by cscoderr** [comment]
which means introducing networkUri will look something like this right
```dart
VideoPlayerController.networkUri(
    Uri url, {
    this.formatHint,
    Future<ClosedCaptionFile>? closedCaptionFile,
    this.videoPlayerOptions,
    this.httpHeaders = const <String, String>{},
  })  : _closedCaptionFileFuture = closedCaptionFile,
        dataSource = url.toString(),
        dataSourceType = DataSourceType.network,
        package = null,
        super(VideoPlayerValue(duration: Duration.zero));
```

## Usecases
```dart
VideoPlayerController.networkUri(
   Uri.parse('https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4')
)
```

**Comment by stuartmorgan** [comment]
@nikshit-chauhan We don't generally assign issues to people who aren't Flutter team members, as they can't update their assignment if they change their mind. Please feel free to just send a PR.

**Comment by nikshit-chauhan** [comment]
@stuartmorgan can u help me setup this repo I want start contributing

**Comment by stuartmorgan** [comment]
@nikshit-chauhan Please see https://github.com/flutter/packages/blob/main/CONTRIBUTING.md for links and resources.

**Comment by srijanAtGithub** [comment]
I am learning and mastering my work on flutter. Been through some courses already. Would love to work on the issue as one of my first contributions to open source projects. Can someone help me along regarding this?
