### ISSUE TITLE
Waiting for a connection from Flutter on ...

### ISSUE THREAD

**Issue by zzzh** [flutter/flutter#121966]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Sorry I don't know how to reproduce it, it used to work well.

### Actual results

I'm using flutter in vscode, it used to work well, but now something is wrong:

I can't see my phone ( connected to my PC by usb cable ) in status bar now, tried to press F5 to start debugging, nothing happens.

So I run "flutter attach --verbose" in terminal, it can found my phone, but can't build a connection, below is the log.

### Logs

flutter attach -v       
[  +26 ms] executing: [e:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +161 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] 12cb4eb7a009f52b347b62ade7cb4854b926af72
[        ] executing: [e:\flutter/] git tag --points-at 12cb4eb7a009f52b347b62ade7cb4854b926af72
[ +297 ms] Exit code 0 from: git tag --points-at 12cb4eb7a009f52b347b62ade7cb4854b926af72
[   +1 ms] 3.7.6
[  +25 ms] executing: [e:\flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[ +143 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[   +1 ms] origin/stable
[        ] executing: [e:\flutter/] git ls-remote --get-url origin
[ +125 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +174 ms] executing: [e:\flutter/] git rev-parse --abbrev-ref HEAD
[ +240 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +105 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +122 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'PubDependencies' is not required, skipping update.
[ +227 ms] executing: e:\Android\sdk\platform-tools\adb.exe devices -l
[ +139 ms] List of devices attached
                    HT43HSF04122           device product:htccn_chs_ct model:HTC_M8d device:htc_m8wl transport_id:2
[ +113 ms] e:\Android\sdk\platform-tools\adb.exe -s HT43HSF04122 shell getprop
[ +280 ms] Waiting for a connection from Flutter on HTC M8d...

### Flutter Doctor output

flutter doctor -v
[✓] Flutter (Channel stable, 3.7.4, on Microsoft Windows [版本 10.0.19044.2604], locale zh-CN)
    • Flutter version 3.7.4 on channel stable at e:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b4bce91dd0 (12 days ago), 2023-02-21 09:50:50 +0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✗] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at e:\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: E:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Android Studio (version 2021.3)
    • Android Studio at E:\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.76.0)
    • VS Code at C:\Users\wxzzz\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.58.0

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1,::1
    • NO_PROXY contains localhost
    • NO_PROXY contains ::1
    • NO_PROXY contains 127.0.0.1

[✓] Connected device (1 available)
    • HTC M8d (mobile) • HT43HSF04122 • android-arm • Android 6.0 (API 23)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

**Comment by exaby73** [comment]
Could you try with the master channel of Flutter? Also, could you try running `flutter run` in the terminal? This would allow us to determine if it's a an issue with only VSCode or with the Flutter CLI itself

**Comment by zzzh** [comment]
Hi, @exaby73,
Sorry, I can't do this now because I'm running on a back-up image I saved before, though, before that, I saved another image which have this issue.
I'll switch back later, then will do what you need.
Thank you for the reply.

**Comment by zzzh** [comment]
Hi, @exaby73,
I did it yesterday, to my surprise,  it can find device now, but can't connect to wsl...
I believe it's a vscode multi-install issue, instead of a flutter one.
Thanks for the help.
