### ISSUE TITLE
[web] Golden "canvaskit_picture_texture_toimage" isn't uploaded to Gold

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#121906]
For some reason, the following golden isn't uploaded to Gold:
https://github.com/flutter/engine/blob/02a379db1d384cc108d0dad295504456a01eb6bd/lib/web_ui/test/canvaskit/image_golden_test.dart#L781-L784

The test is passing, but the image is no where to be found on Gold.

**Comment by yjbanov** [comment]
Making it a P2 because this may apply to other goldens. We may be missing some important golden tests.

**Comment by eyebrowsoffire** [comment]
I'll be taking a look at this as I get goldens up and running with the Skwasm renderer.
