### ISSUE TITLE
iOS has  about 6MB  memory  leak

### ISSUE THREAD

**Issue by cj3479** [flutter/flutter#121993]
I am Adding a Flutter screen to an existing iOS app，The app entry is native UIViewController. There is a button which can
enter flutter screen on the UIViewController.
When I enter flutter screen and operate it arbitrarily then close the flutter screem
I fount it retain  about 6MB memory not free.
Can you help solve it?

flutter doctor -v
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/9412601/223034696-4edddab4-3c7b-4ffb-bef9-e6dd3e3be752.png">

This is my operation
https://user-images.githubusercontent.com/9412601/223035458-4fcd89ab-7ba0-4a5b-94ce-edc60edbfc41.mp4

This is memory profile 
![704b36fe83672ec0d635583fa8a77446](https://user-images.githubusercontent.com/9412601/223035580-a88c4e48-ec5b-40f6-9a06-eff563cd872c.png)

![7797595674ea1380f9456f04a136edde](https://user-images.githubusercontent.com/9412601/223035597-41d451aa-6193-4745-a2c8-02d6abcd21bb.png)

This is my sample code, the sample is very simple
[TestFlutter_1.zip](https://github.com/flutter/flutter/files/10895020/TestFlutter_1.zip)

**Comment by cj3479** [comment]
By the way .My team application is more complex app, it leak more memory ,about 30MB

**Comment by huycozy** [comment]
Hi @cj3479, thanks for filing the issue. 
I see there are some open issues addressing the case you described #97390, #77621 (also meta-issue: https://github.com/flutter/flutter/issues/72009)

Closing this issue as a duplicate, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
