### ISSUE TITLE
Camera keeps crashing after recording is finished with image_picker

### ISSUE THREAD

**Issue by TheHudek** [flutter/flutter#121951]
As the title says, image_picker crashes after recording a video. The issue is very similar to #84540. The error is reproduced with the example app as well. Picking images work, and picking videos from the gallery works as well. There is no debug output, the camera app just crashes and returns me to the app. After the second try Android will give me an error message saying "Camera keeps stopping."

`flutter doctor -v`
```
[✓] Flutter (Channel stable, 3.7.1, on Microsoft Windows [Version 10.0.22621.1265], locale en-US)
    • Flutter version 3.7.1 on channel stable at <path>\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7048ed95a5 (4 weeks ago), 2023-02-01 09:07:31 -0800
    • Engine revision 800594f1f4
    • Dart version 2.19.1
    • DevTools version 2.20.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at <path>\Local\Android\sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: <path>\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.8)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.32002.261
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2022.1)
    • Android Studio at <path>\andoid-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[✓] VS Code (version 1.76.0)
    • VS Code at <path>\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.60.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.1265]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 110.0.5481.178
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 110.0.1587.63

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by TheHudek** [comment]
Creating a brand new application and running `flutter pub get video_player` and `flutter pub get image_picker` won't help either.

**Comment by stuartmorgan** [comment]
The plugin has no control over the camera, it's just requesting that the system launch it via an intent. A crash in the camera is something you would need to report to the developer of the camera application.

**Comment by TheHudek** [comment]
Camera application works in itself, I can capture videos and save them natively in the android emulator. Third-party packages such as camera awesome also work. The crash happens in a fresh example app and a fresh android emulator as well.

**Comment by TheHudek** [comment]
I've just found #118443, my issue is identical to this.

**Comment by stuartmorgan** [comment]
> Camera application works in itself, I can capture videos and save them natively in the android emulator.

Those aren't the same code paths. The fact that one code path works in an application doesn't mean all of them do.

> Third-party packages such as camera awesome also work.

That is entirely different from an intent to the camera activity.

> The crash happens in a fresh example app and a fresh android emulator as well.

This would be good information to provide in a report to the developer of the crashing code.
