### ISSUE TITLE
Sizing is calculated wrong while using GridView.count in CupertinoPageScaffold

### ISSUE THREAD

**Issue by eifr** [flutter/flutter#121964]
`GridView.count` size and placement is rendered in the wrong place while is a child of `CupertinoPageScaffold` and also padding being set.

## Steps to Reproduce

1. Execute `flutter run` on the code sample 

**Expected results:** 
Grid view list will be in view and worn start behind app bar

**Actual results:** 
![Screenshot_1678010906](https://user-images.githubusercontent.com/5452613/222954285-d68c74a9-031a-4ed3-a90c-f930ab5f64ba.png)

```dart
return CupertinoPageScaffold(
              navigationBar: const CupertinoNavigationBar(
                middle: Text('Go Back'),
              ),
              child: GridView.count(
                primary: false,
                padding: const EdgeInsets.all(8.0),
                crossAxisSpacing: 10.0,
                crossAxisCount: 2,
                children: points
                    .map((p) => PointItem(
                          point: p,
                        ))
                    .toList(),
              ),
            );
          }
```
```dart
class PointItem extends StatelessWidget {
  const PointItem({super.key, required this.point});
  final Point point;

  @override
  Widget build(BuildContext context) {
    return Card(
      elevation: 4,
      shape: const BeveledRectangleBorder(
        borderRadius: BorderRadius.all(
          Radius.circular(15),
        ),
      ),
      child: Column(
        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
        children: [
          Text(point.name),
          Text(point.area),
          Text(point.category),
        ],
      ),
    );
  }
}
```

**Comment by darshankawar** [comment]
@eifr 
Can you provide complete code sample ? Some pieces seems to be missing from the code snippet you provided such as `points` and then `area`, `name` and `category`.

What's the expected behavior are you looking for upon running your code ?

**Comment by eifr** [comment]
@darshankawar 
I don't think this data is relevant as it comes from an api..
```dart
var points = [
    { area: 'area-text', name: 'name-text', category: 'category-text'}
];
```

in this specific case the tree goes 
`CupertinoApp` -> `CupertinoTabScaffold` -> `CupertinoTabView` -> `CupertinoPageScaffold`  -> `Gridview.count`

**Comment by darshankawar** [comment]
@eifr 
I came up with below complete code sample that shows the app per screenshot shared below:

<details>
<summary> runnable code sample </summary>

```

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: Home()));

class Home extends StatefulWidget  {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> with SingleTickerProviderStateMixin {
  final GlobalKey<ScaffoldState> _scaffoldKey = GlobalKey();
  late AnimationController controller;

  @override
  void initState() {
    super.initState();
    controller = AnimationController(vsync: this);
  }

  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: const CupertinoNavigationBar(
        middle: Text('Go Back'),
      ),
      child: GridView.count(
        primary: false,
        padding: const EdgeInsets.all(8.0),
        crossAxisSpacing: 10.0,
        crossAxisCount: 2,
        children: [
          DialKey(
            number: '1',
            letters: '',
          ),
          DialKey(
            number: '2',
            letters: '',
          ),
        ],
      ),
    );
  }
  }

class DialKey extends StatelessWidget {
  final String number;
  final String letters;

  DialKey({required this.number, required this.letters});

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Container(
        width: 80,
        height: 80,
        child: FloatingActionButton(
          onPressed: () {},
          backgroundColor: Colors.grey.withOpacity(0.5),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Text(
                '$number',
                style: TextStyle(
                    color: Colors.white,
                    fontSize: 24,
                    fontWeight: FontWeight.bold),
              ),
              Text(
                '$letters',
                style: TextStyle(
                    color: Colors.white,
                    fontSize: 16,
                    fontWeight: FontWeight.bold),
              )
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>

<img width="342" alt="Screenshot 2023-03-07 at 6 31 36 PM" src="https://user-images.githubusercontent.com/67046386/223430045-fd7953f6-cf0f-4e85-8f68-3e91740a6bf7.png">

Is the issue that the gridview is cut-off at the top ? If so, does the same behavior occur without using `CupertinoPageScaffold` ?

**Comment by eifr** [comment]
@darshankawar 
Yes! the issue is that the page is being cut-off at the top.
I tested while using `Scaffold` instead of `CupertinoPageScaffold` and the gridview placement was correct (no issues)

**Comment by darshankawar** [comment]
@eifr 
In your code sample, `CupertinoPageScaffold` has `navigationBar` implementation which you have placed at the top of the screen which takes part in cutting-off the gridview items.  If you comment out that code, the gridview items are displayed fine. 
Can you provide us the same implementation using `Scaffold` and what exactly is your use case that requires using `CupertinoPageScaffold` + `navigationBar` at the top ?
