### ISSUE TITLE
[Proposal] Add spellCheckConfiguration property to TextFormField

### ISSUE THREAD

**Issue by Dan1ell** [flutter/flutter#121965]
Since Flutter 3.7 we can activate spellchecking in TextFields with:
`TextField: spellCheckConfiguration: kIsWeb ? null : SpellCheckConfiguration()
`

I would like to request similar spellchecking support for TextFormField.

**Comment by goderbauer** [comment]
@camsim99

**Comment by justinmc** [comment]
@Dan1ell Thanks for pointing this out!  I totally forgot about TextFormField.  Fix incoming.
