### ISSUE TITLE
We should remove the #define ENABLE_RASTER_CACHE

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1219]

**Comment by abarth** [comment]
I wonder how much of this machinery we want to expose to Dart.  It's something that we might want to be able to fiddle with easily while we're experimenting.

**Comment by eseidelGoogle** [comment]
Is this still an issue?  I know we have a raster cache.  My impression was Dart was involved in managing it somehow now.  @chinmaygarde

**Comment by abarth** [comment]
Still an issue.

**Comment by chinmaygarde** [comment]
The define was removed a while ago. Dart can control cache behavior by specifying that the picture will change from frame to frame.
