### ISSUE TITLE
Use a full gclient checkout for engine_v2 global test shards

### ISSUE THREAD

**Issue by eyebrowsoffire** [flutter/flutter#121900]
The web tests currently need a full engine checkout with gclient sync run in order for the test harness to run properly. For now, we at least need an option we can specify for the test shards that will allow this.

Note: In the future, we can find a solution that can allow the test harness to run more independently of the source checkout and/or gclient.

**Comment by godofredoc** [comment]
As a first step the global tests need to provide a default recipe and also allow to override it from configs. This logic is implemented in https://flutter-review.googlesource.com/c/recipes/+/40881

**Comment by godofredoc** [comment]
Implementation ready for review: https://flutter-review.googlesource.com/c/recipes/+/41065
