### ISSUE TITLE
XCode 14.2 claims "The file “[YourPluginFileName].swift” couldn’t be opened because you don’t have permission to view it."

### ISSUE THREAD

**Issue by nerdybunz** [flutter/flutter#121953]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a new flutter plugin using flutter (version 3.7.3 to reproduce exactly)  by typing "flutter create -t plugin --platforms ios --platforms android my_plugin" 
2. Open the plugin project in an IDE (VSCode 1.75.1 to reproduce exactly).
3. Right click on the "ios" folder that resides in the "example" folder and select "open project in Xcode"
4. Using the Project Navigator in Xcode (14.2 to reproduce exactly), navigate to the plugin's boiler plate swift file at Pods\Development Pods\[your_plugin_name]\..\..\example\ios\.symlinks\plugins\[your_plugin_name]\ios\Classes\[YourPluginFileName].swift and attempt to open it.

### Actual results

Seemingly "out-of-nowhere" starting today (I have always worked on these same projects regulary on the same system), an XCode pop-up states "The file “[YourPluginFileName].swift” couldn’t be opened because you don’t have permission to view it.  To view or change permissions, select the item in the Finder and choose File > Get Info."

The strange thing is that this swift file has the same permissions set on it that other files have that do open just fine in XCode.

I understand this could technically not be related to Flutter (a macOS or XCode issue), but if it is indeed reproducible with the described steps, then it basically affects everyone trying to work on a plugin at this moment and would be in everyone's interest to know the exact cause (and solution if known).

### Logs

n/a

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.7.3, on macOS 13.1 22C65 darwin-x64, locale en-US)
    • Flutter version 3.7.3 on channel stable at /Users/boober/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (3 weeks ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/boober/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • iPod touch (7th generation) (mobile) • 49668CE6-F66C-43A5-93CC-13A41A6EF430 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)                      • macos                                • darwin-x64
      • macOS 13.1 22C65 darwin-x64
    • Chrome (web)                         • chrome                               • web-javascript
      • Google Chrome 110.0.5481.177

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by nerdybunz** [comment]
UPDATE: After upgrading from Flutter 3.7.3 to to 3.7.6, and creating a new plugin using the described steps, the problem does not occur.  However, the existing projects still remain "borked."

**Comment by exaby73** [comment]
Hello @nerdybunz. If this is working in 3.7.6, this seems like an issue that is already fixed. Due to this, this issue is invalid and therefore I will close it. If you disagree with my decision, please comment with your reasoning and I can reopen the issue. Thank you
