### ISSUE TITLE
package google_sign_in_web needs updated example

### ISSUE THREAD

**Issue by emicklei** [flutter/flutter#121930]
On https://github.com/flutter/packages/tree/main/packages/google_sign_in/google_sign_in_web under the "Usage" section, the example link refers to the **old** google_sign_in package. 

This documentation page starts with "Migrating to v0.11 (Google Identity Services)" and this package (google_sign_in_web) was created (or updated?) to implement sign in using the new GIS service.

At the time of writing this issue, I could not find any example (tests do not show the intended flow)  that demonstrates how to use this package in a simple SignInDemo (similar to the old example).

Maybe it is already work-in-progress looking at this scaffold https://github.com/flutter/packages/blob/main/packages/google_sign_in/google_sign_in_web/example/lib/main.dart

**Comment by huycozy** [comment]
I'm not sure if I can understand this right, but the [example code](https://github.com/flutter/packages/blob/main/packages/google_sign_in/google_sign_in/example/lib/main.dart) is displaying normally from my end:

<img width="400" src="https://user-images.githubusercontent.com/104349824/223054654-a52233c7-d4c1-4d7e-a539-172a4888848c.png">

Please try again. If it's not an issue that you are talking about, please clarify this in detail by providing `Actual result` and `Expected result`.

**Comment by emicklei** [comment]
The way I see it is that google_sign_in_web is a new package that uses the new GIS service.

With that new package the old "GoogleSignIn" type is replaced? by the type "GoogleSignInPlugin".
Initialisation for this plugin is done using "plugin.initWithParams(SignInInitParameters(..."

I have been trying to put together a new demo page and was looking for a complete example before creating this issue.

My effort looks like this:
```
import 'package:flutter/material.dart';
import 'package:google_sign_in_platform_interface/google_sign_in_platform_interface.dart';
import 'package:google_sign_in_web/google_sign_in_web.dart';

GoogleSignInPlugin plugin = GoogleSignInPlugin();

class LoginPage extends StatefulWidget {
  const LoginPage({Key? key}) : super(key: key);

  @override
  State createState() => LoginPageState();
}

class LoginPageState extends State<LoginPage> {
  GoogleSignInUserData? _userData;

  @override
  void initState() {
    super.initState();
    plugin
        .initWithParams(SignInInitParameters(
            clientId:
                "my-client-id.apps.googleusercontent.com",
            scopes: ["email"]))
        .then((v) {
      print('skip login silently for now');
      /**
      plugin.signInSilently().then((value) {
        print('after sigin silently');
        plugin.signIn().then((value){
          print('after sign in after silent');
          _userData = value;
        });
      });
              **/
    });
  }
```

**Comment by emicklei** [comment]
maybe, I misunderstood the architecture and the google_sign_in_web is actually an internal package one should not use directly?

**Comment by huycozy** [comment]
As far as I can see, the example code remains the same and there are differences in the returned results/behaviors when you use the GIS SDK (difference between using `signInSilently` or `signIn` for eg). And you should check your Authentication/Authorization flow after upgrading to GIS SDK. 

>maybe, I misunderstood the architecture and the google_sign_in_web is actually an internal package one should not use directly?

Please see [Import the package](https://github.com/flutter/packages/tree/main/packages/google_sign_in/google_sign_in_web#import-the-package).

You also can see there is an **unmodified** Google Sign-In example app has been deployed here: https://dit-gis-test.web.app/ (source: https://github.com/flutter/plugins/pull/6921)

Kindly cc @ditman for the better explanation if I miss something here.

**Comment by emicklei** [comment]
@huycozy thank you for confirming that the sign in package is there to stay and it should work with the new GIS SDK. 
The existing example code therefore is sufficient.

**Comment by ditman** [comment]
@emicklei this is correct. The `_web` version of the package is just the "web implementation" of the package, that gets selected automatically when you `flutter build` or `flutter run` on a web target.

(The package is a dependency of the core package, see the [pubspec](https://github.com/flutter/packages/blob/843bd8c7786c3127dc43f901d0c0b7420e4efabd/packages/google_sign_in/google_sign_in/pubspec.yaml#L19-L20))

I'm actually adding some extra code to the google_sign_in_web (a new Widget), and then I'll update the current example to use the new architecture I'm proposing. Follow this issue:

* https://github.com/flutter/flutter/issues/121781
