### ISSUE TITLE
Http works in Postman but keep getting 400 bad request error in Flutter

### ISSUE THREAD

**Issue by yanzisu68** [flutter/flutter#121969]
When sending request in Flutter, suddenly today always got 400 err from API. But same cURL copied from dev tools able to work as normal in Postman. 

Can help suggest how could resolve it. Thanks!!

The following is my code:

```
class _MusicService implements MusicService {
  _MusicService(this._dio, {this.baseUrl}) {
    baseUrl ??= 'http://ws.audioscrobbler.com/2.0/';
  }

  final Dio _dio;

  String? baseUrl;

  @override
  Future<HttpResponse<ArtistSearchResponse>> searchForArtist(artist,
      {apiKey = AppConst.kApiKey,
      format = 'json',
      method = 'artist.search'}) async {
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{
      r'artist': artist,
      r'api_key': apiKey,
      r'format': format,
      r'method': method
    };
    final _headers = <String, dynamic>{};
    final _data = <String, dynamic>{};
    final _result = await _dio.fetch<Map<String, dynamic>>(
        _setStreamType<HttpResponse<ArtistSearchResponse>>(
            Options(method: 'GET', headers: _headers, extra: _extra)
                .compose(_dio.options, '',
                    queryParameters: queryParameters, data: _data)
                .copyWith(baseUrl: baseUrl ?? _dio.options.baseUrl)));
    final value = ArtistSearchResponse.fromJson(_result.data!);
    final httpResponse = HttpResponse(value, _result);
    return httpResponse;
  }
```

</details>
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/58883343/222963222-70d90bc5-2ceb-4ce1-88af-eb2de1345108.png">
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/58883343/222963238-a68e741f-c9b5-424c-9d8c-a0cea012ef99.png">

when grab the cURL to run in Postman, actually can work well with 200 status code
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/58883343/222963265-cad8fb30-0d19-4432-af36-c7caeaf5b78e.png">

Can help suggest how could resolve this issue? Basically yesterday still works fine, but today keeps failing >_<

**Comment by darshankawar** [comment]
@yanzisu68 
Your question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here as this is more of a support question instead of a bug report or feature request. If you disagree, or think there's a bug in the sdk, use new issue template, fill out requested details so that we can address it properly.
