### ISSUE TITLE
Allow changing of the keyboard type in DateRangePicker (similar to DatePicker)

### ISSUE THREAD

**Issue by ko16a46** [flutter/flutter#121912]
## Use case

We noticed the same issue as #62401 wherein dates cannot be typed in the input date range picker on some phones, because they don't include a slash ('/') in their date input keyboard.

![67c15004-117f-46b4-921b-f8236aee65be](https://user-images.githubusercontent.com/100613422/222852574-46c2d97f-0f99-484e-8bef-3f2c32f5c4cb.png)

We were hoping to work around it similar to how the Android Material components team worked around it in their codebase. By showing the full keyboard on Samsung (and also LGE) devices as seen in material-components/material-components-android#682

However, the `DateRangePickerDialog` and `showDateRangePicker` don't have any options for keyboard type like the one added to `DatePickerDialog` and `showDatePicker` in #93439

## Proposal

Add `keyboardType` as an optional parameter in `DateRangePickerDialog` and `showDateRangePicker`, so we can change the keyboard type ourselves as necessary.

**Comment by justinmc** [comment]
You're totally right, we should add this parameter.  Thanks for the issue.  I'm working on a PR.
