### ISSUE TITLE
Cann't start debugging 

### ISSUE THREAD

**Issue by M-Yahia2011** [flutter/flutter#121944]
I get this error every time I try to run or debug.

Launching lib\main.dart on SM N920C in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Gradle could not start your build.
> Could not create service of type BuildLifecycleController using ServicesProvider.createBuildLifecycleController().
   > Could not create service of type GradleInternal using ServicesProvider.createGradleModel().
      > Could not create an instance of type org.gradle.invocation.DefaultGradle.
         > Could not configure services using GradleScopeCompileServices.configure().

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by huycozy** [comment]
It seems to be a gradle issue rather than Flutter issue. Please check answers on [this gradle thread](https://github.com/gradle/gradle/issues/8436) if they can help.
