### ISSUE TITLE
Diagnosticable toString interface change broke leafy unexpectedly 

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#12191]
The Diagnosticable class introduced an issue during a g3 roll to customer:leafy.  They had a mixin class that implemented toString, which was getting mixed in with a widget.  When the optional `minLevel` parameter was added to Widget through Diagnosticable, it produced the following diamond inheritance

![image](https://user-images.githubusercontent.com/14947366/30670813-baf49d4a-9e18-11e7-92e5-0c2498f5fe17.png)

The break has been corrected, but similar situations could happen in the future.  This issue is about finding ways to mitigate the impact of such changes.

The confusing part of the breakage was that the interface to toString had changed, and that the code  implementing toString had no way of knowing about the change, because it was a VM class that was being mixed in to a widget.  

Breakages like this will always be possible when interfaces change, both with and without mixins, but we can reduce the confusion that they cause by not changing the interface of Object.

I think as a general rule, we should preserve the interface signature of Object and other dart:core classes when we extend them.  Without that rule, Dart libraries that are written under the assumption that the Object interface will remain constant may become incompatible with Flutter.

CC: @yjbanov (@ыйбанов) and @jacob314

**Comment by Hixie** [comment]
It's not actually a diamond inheritance pattern. Mixins don't inherit from Object, they just implement it. The actual inheritance is just LayoutWidget -> DescMixin -> Diagnosticable -> Object (plus some additional ones in there probably). DescMixin is required to implement Diagnosticable when mixed in in this way.

In general we prevent such breakages by not making breaking changes, and handling breaking changes that we feel are really necessary by following this process: https://flutter.io/design-principles/#handling-breaking-changes

**Comment by Hixie** [comment]
Regarding the specific proposal to not override toString: adding arguments to toString is too useful to never do it. In practice, anything inheriting from Diagnosticable shouldn't implement toString at all. DocsMixin should just use the DIagnosticable API instead (and `implements Diagnosticable` to indicate it needs to be mixed in to things that inherit from that API).

**Comment by Hixie** [comment]
Closing based on arguments above, let me know if you disagree.

**Comment by kriswuollett** [comment]
What about desiring to make a BuiltValue Diagnosticable? See https://github.com/google/built_value.dart/issues/582. The use case is including complex value types in a diagnostics tree.
