### ISSUE TITLE
 android-studio-dir = D:\Program Files\Android\Android Studio

### ISSUE THREAD

**Issue by 404495580** [flutter/flutter#122071]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

flutter version: 1.12.13+hotfix.8
androd studio:2022.1.1 patch2
win11 home 22h2

### Actual results

[!] Android Studio
    • Android Studio at D:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    X android-studio-dir = D:\Program Files\Android\Android Studio
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.
    • Consider removing your android-studio-dir setting by running:
      flutter config --android-studio-dir=

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

 flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.22621.1265], locale zh-CN)
    • Flutter version 1.12.13+hotfix.8 at D:\Flutter\flutter
    • Framework revision 0b8abb4724 (3 years, 1 month ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\40449\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-33-ext4, build-tools 33.0.2
    • ANDROID_HOME = C:\Users\40449\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
    • All Android licenses accepted.

[!] Android Studio
    • Android Studio at D:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    X android-studio-dir = D:\Program Files\Android\Android Studio
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.
    • Consider removing your android-studio-dir setting by running:
      flutter config --android-studio-dir=

[√] Connected device (1 available)
    • MI 8 • ec3b1908 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.

**Comment by darshankawar** [comment]
> Flutter (Channel stable, v1.12.13+hotfix.8,

@404495580 
This is an obsolete version of the framework. You need to upgrade so see the reported issue been fixed already in latest versions.
I'll close this for now. After upgrading to latest version, if you still encounter same issue, write in comments and I'll reopen it.
