### ISSUE TITLE
Flutter Build arm64 at paralles (windows 11)

### ISSUE THREAD

**Issue by longfit** [flutter/flutter#122098]
I have installed windows 11 64 arm  at m1 parallels,

When I build the windows arm64 shown below:

Can I make use apple m1 parallels emulator of windows 11 for building windows apps ??

best Regards

flutter_window.obj : error LNK2019: �b�禡 __imp_FlutterDesktopViewGetHWND"public: struct HWND__ * __cdecl flutter::FlutterView::GetNativeWindow(void)" (?GetNativeWindow@FlutterView@flutter@@QEAAPEAUHWND__@@XZ) ���ѦҤF�L�k�ѪR���~���Ÿ� [C:\Users\ykwings\flutter_try\flutter_application_1\build\windows\runner\flutter_application_1.vcxproj]
utils.obj : error LNK2019: �b�禡 __imp_FlutterDesktopResyncOutputStreams"void __cdecl CreateAndAttachConsole(void)" (?CreateAndAttachConsole@@YAXXZ) ���ѦҤF�L�k�ѪR���~���Ÿ� [C:\Users\ykwings\flutter_try\flutter_application_1\build\windows\runner\flutter_application_1.vcxproj]
win32_window.obj : error LNK2019: �b�禡 __imp_FlutterDesktopGetDpiForMonitor"public: bool __cdecl Win32Window::Create(class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,struct Win32Window::Point const &,struct Win32Window::Size const &)" (?Create@Win32Window@@QEAA_NAEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@AEBUPoint@1@AEBUSize@1@@Z) ���ѦҤF�L�k�ѪR���~���Ÿ� [C:\Users\ykwings\flutter_try\flutter_application_1\build\windows\runner\flutter_application_1.vcxproj]
flutter_wrapper_app.lib(flutter_engine.obj) : error LNK2019: �b�禡 __imp_FlutterDesktopEngineCreate"public: __cdecl flutter::FlutterEngine::FlutterEngine(class flutter::DartProject const &)" (??0FlutterEngine@flutter@@QEAA@AEBVDartProject@1@@Z) ���ѦҤF�L�k�ѪR���~���Ÿ� [C:\Users\ykwings\flutter_try\flutter_application_1\build\windows\runner\flutter_application_1.vcxproj]
flutter_wrapper_app.lib(flutter_engine.obj) : error LNK2019: �b�禡 __imp_FlutterDesktopEngineDestroy"public: void __cdecl flutter::FlutterEngine::ShutDown(void)" (?ShutDown@FlutterEngine@flutter@@QEAAXXZ) ���ѦҤF�L�k�ѪR���~���Ÿ� [C:\Users\ykwings\flutter_try\flutter_application_1\build\windows\runner\flutter_application_1.vcxproj]
flutter_wrapper_app.lib(flutter_engine.obj) : error LNK2019: �b�禡 __imp_FlutterDesktopEngineRun"public: bool __cdecl flutter::FlutterEngine::Run(char const *)" (?Run@FlutterEngine@flutter@@QEAA_NPEBD@Z) ���ѦҤF�L�k�ѪR���~���Ÿ� [C:\Users\ykwings\flutter_try\flutter_application_1\build\windows\runner\flutter_application_1.vcxproj]
flutter_wrapper_app.lib(flutter_engine.obj) : error LNK2019: �b�禡 __imp_FlutterDesktopEngineProcessMessages"public: class std::chrono::duration<__int64,struct std::ratio<1,1000000000> > __cdecl flutter::FlutterEngine::ProcessMessages(void)" (?ProcessMessages@FlutterEngine@flutter@@QEAA?AV?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@chrono@std@@XZ) ���ѦҤF�L�k�ѪR���~���Ÿ� [C:\Users\ykwings\flutter_try\flutter_application_1\build\windows\runner\flutter_application_1.vcxproj]
flutter_wrapper_app.lib(flutter_engine.obj) : error LNK2019: �b�禡 __imp_FlutterDesktopEngineReloadSystemFonts"public: void __cdecl flutter::FlutterEngine::ReloadSystemFonts(void)" (?ReloadSystemFonts@FlutterEngine@flutter@@QEAAXXZ) ���ѦҤF�L�k�ѪR���~���Ÿ� [C:\Users\ykwings\flutter_try\flutter_application_1\build\windows\runner\flutter_application_1.vcxproj]
flutter_wrapper_app.lib(flutter_engine.obj) : error LNK2019: �b�禡 __imp_FlutterDesktopEngineGetPluginRegistrar"public: virtual struct FlutterDesktopPluginRegistrar * __cdecl flutter::FlutterEngine::GetRegistrarForPlugin(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?GetRegistrarForPlugin@FlutterEngine@flutter@@UEAAPEAUFlutterDesktopPluginRegistrar@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) ���ѦҤF�L�k�ѪR���~���Ÿ� [C:\Users\ykwings\flutter_try\flutter_application_1\build\windows\runner\flutter_application_1.vcxproj]
flutter_wrapper_app.lib(flutter_engine.obj) : error LNK2019: �b�禡 __imp_FlutterDesktopEngineGetMessenger"public: __cdecl flutter::FlutterEngine::FlutterEngine(class flutter::DartProject const &)" (??0FlutterEngine@flutter@@QEAA@AEBVDartProject@1@@Z) ���ѦҤF�L�k�ѪR���~���Ÿ� [C:\Users\ykwings\flutter_try\flutter_application_1\build\windows\runner\flutter_application_1.vcxproj]
flutter_wrapper_app.lib(flutter_engine.obj) : error LNK2019: �b�禡 __imp_FlutterDesktopEngineSetNextFrameCallback"public: void __cdecl flutter::FlutterEngine::SetNextFrameCallback(class std::function<void __cdecl(void)>)" (?SetNextFrameCallback@FlutterEngine@flutter@@QEAAXV?$function@$$A6AXXZ@std@@@Z) ���ѦҤF�L�k�ѪR���~���Ÿ� [C:\Users\ykwings\flutter_try\flutter_application_1\build\windows\runner\flutter_application_1.vcxproj]
flutter_wrapper_app.lib(flutter_view_controller.obj) : error LNK2019: �b�禡 __imp_FlutterDesktopViewControllerCreate"public: __cdecl flutter::FlutterViewController::FlutterViewController(int,int,class flutter::DartProject const &)" (??0FlutterViewController@flutter@@QEAA@HHAEBVDartProject@1@@Z) ���ѦҤF�L�k�ѪR���~���Ÿ� [C:\Users\ykwings\flutter_try\flutter_application_1\build\windows\runner\flutter_application_1.vcxproj]

**Comment by ImagineBoom** [comment]
me too!

**Comment by huycozy** [comment]
Hi @longfit, @ImagineBoom 
I see there are open issues:
- https://github.com/flutter/flutter/issues/53120
- https://github.com/flutter/flutter/issues/62597

Closing this issue as a duplicate, so please follow up on these issue for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
