### ISSUE TITLE
AutoScrolling is not smooth on listview builder ?

### ISSUE THREAD

**Issue by harryandroiddev** [flutter/flutter#122093]
use the below code to scroll to the end of list with listview.builder :

`var extent = scrollController.position.maxScrollExtent;
          scrollController.animateTo(
            extent,
            duration:const Duration(minutes: 5),
            curve: Curves.ease
          );`

But the scolling is not even smooth it just stops and scroll that is not appropriate if the user is reading something on the screen .

**Comment by huycozy** [comment]
Hi @harryandroiddev 

Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` along with the affected environment as well.

Thank you!

**Comment by harryandroiddev** [comment]
Now by using Curves.linear  , makes the scrolling smooth .
