### ISSUE TITLE
media_query_test flake

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#122045]
I've seen the following test fail flakily in two separate PRs.  It eventually passed by rerunning one or two times.

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: <null>
  Actual: <33.333333333333336>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///Volumes/Work/s/w/ir/x/w/flutter/packages/flutter/test/widgets/media_query_test.dart:159:5)
#5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:170:29)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///Volumes/Work/s/w/ir/x/w/flutter/packages/flutter/test/widgets/media_query_test.dart line 159
The test description was:
  MediaQueryData.fromView is sane
════════════════════════════════════════════════════════════════════════════════════════════════════
```

[Example run](https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20framework_tests_widgets/35964/overview)

https://github.com/flutter/flutter/blob/57c7aa53c178f722aec19a76a60552e78ad09997/packages/flutter/test/widgets/media_query_test.dart#L159

Affected PR 1: https://github.com/flutter/flutter/pull/121110
Affected PR 2: https://github.com/flutter/flutter/pull/119225

CC @pdblasi-google

**Comment by goderbauer** [comment]
This flake was likely caused by https://github.com/flutter/flutter/pull/121749 and fixed by https://github.com/flutter/flutter/pull/121956.

**Comment by darshankawar** [comment]
@justinmc Hi, is it safe to close the issue based on above comment ?

**Comment by justinmc** [comment]
I haven't seen it again so I'll close it, but let me know if I'm wrong @goderbauer or anyone else.
