### ISSUE TITLE
`Uri` with empty `queryParameter` has an extra `?` at the end

### ISSUE THREAD

**Issue by ValentinVignal** [flutter/flutter#122089]
A `Uri` with empty `queryParameters` (`= {}`) will have a `?` at the end even it doens't have any query parameters

## Steps to Reproduce

1. Execute `flutter run` on the code sample (see "Code sample" section below)
2. Notice that the uri finishes with a `?` but has no query parameters.

**Expected results:** 

I would expect the uri to be `/path`

**Actual results:** 

The uri is `/path?`

<details>
<summary>Code sample</summary>

```dart
void main() {
  final uri = Uri(path: '/path', queryParameters: {});
  print(uri);
}
```

</details>

<details>
  <summary>Logs</summary>

```
/path?
```

</details>

**Comment by huycozy** [comment]
As I can see, this issue should be filed in [dart-lang/sdk](https://github.com/dart-lang/sdk/issues) for better support. However, you may also try the below workaround (just a logic check) as well. 

<details>
<summary>Sample code (workaround)</summary>

```dart
void main() {
  final uri = Uri(path: '/path', queryParameters: {});
  if(uri.query.isEmpty) {
    print(uri.path);
  } else {
    print(uri);
  }
}
```
</details>

Closing, as this isn't an issue with Flutter itself.

**Comment by ValentinVignal** [comment]
Thank you for the workaround, there is also the case where 

```dart
const Map<String, dynamic> queryParameters = {
  'my-parameter': [],
}
```

so it would actually require a bit more complexity than only checking whether or not the map is empty
