### ISSUE TITLE
[go_router] onWillPop is not called when we use context.pop();

### ISSUE THREAD

**Issue by Pr47h4m** [flutter/flutter#122010]
* I am using ShellRoute and building page with common app bar
* so when I click on back button of app bar -> it will be good if onWillPop method of WillPopScope widget is called
* some workaround can be instead of context.pop() we can have context.mayBePop()

go_router version: 6.2.0

flutter version: 3.7.5 (stable)

**Comment by friedScotch** [comment]
WillPop WIdget doen't work with GoRouter and other Router-based APIs. 
For Info do check out this official documentation:
https://pub.dev/documentation/go_router/latest/topics/Navigation-topic.html
Section Prevent Nagitaion.

https://github.com/flutter/flutter/issues/102408 this is how onWillPopScope might look like for go_router

**Comment by huycozy** [comment]
@Pr47h4m Closing the issue per the explanation above. You can follow up on https://github.com/flutter/flutter/issues/102408 for further updates. Thank @friedScotch for the referenced document and issue.
