### ISSUE TITLE
The header of the M3 DatePicker is clipped in landscape mode.

### ISSUE THREAD

**Issue by QuncCccccc** [flutter/flutter#122056]
If the DatePicker is in landscape mode and it uses DatePickerEntryMode.input, the header will be clipped. 

The portrait mode and M2 version work as expected.

<img width="350" alt="Screenshot 2023-03-06 at 2 51 33 PM" src="https://user-images.githubusercontent.com/36861262/223274693-462338a2-67bb-4209-8cab-a2092790fdb7.png">

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const DatePickerApp());

class DatePickerApp extends StatelessWidget {
  const DatePickerApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: true),
      home: const Scaffold(body: Center(child: DatePickers())),
    );
  }
}
class DatePickers extends StatefulWidget {
  const DatePickers({super.key});

  @override
  State<DatePickers> createState() => _DatePickersState();
}

class _DatePickersState extends State<DatePickers> {
  DateTime? selectedDate;
  final DateTime _firstDate = DateTime(DateTime.now().year - 2);
  final DateTime _lastDate = DateTime(DateTime.now().year + 1);

  @override
  Widget build(BuildContext context) {
    return TextButton(
      onPressed: () {
        showDatePicker(
          initialEntryMode: DatePickerEntryMode.input,
          context: context,
          initialDate: selectedDate ?? DateTime.now(),
          firstDate: _firstDate,
          lastDate: _lastDate,
        );
      },
      child: const Text('Show date picker'),
    );
  }
}

```

</details>

**Comment by HansMuller** [comment]
The M3 date picker lays out correctly in portrait mode and the [spec](https://m3.material.io/components/date-pickers/specs) doesn't even cover landscape mode. Currently the date picker chooses landscape orientation using `MediaQuery.orientationOf(context)` however it should probably use portrait orientation unconditionally on non-mobile platforms. 

Here's the current portrait model input date picker dialog:
![Screenshot 2023-03-09 at 4 27 24 PM](https://user-images.githubusercontent.com/1377460/224192858-4c0894b5-1630-4719-a629-6d41812e00de.png)
