### ISSUE TITLE
Textformfield buildcounter proporty nullable problem

### ISSUE THREAD

**Issue by kaanavcix** [flutter/flutter#122063]
I noticed it while developing application with Flutter. buildcounter function is giving nullable mistake at textformfield. I solved that added "?" in current length and isFocus inside source code. 
<img width="930" alt="Ekran görüntüsü 2023-03-07 040332" src="https://user-images.githubusercontent.com/79256195/223293283-022592b6-801c-4b64-98b2-4ca860609711.png">
<img width="538" alt="Ekran görüntüsü 2023-03-07 040919" src="https://user-images.githubusercontent.com/79256195/223293287-7bb06365-f4ae-46eb-ae5d-39192aaf1690.png">
I added can be nullable. then, ı solved

as you can see. I hope new flutter update can be changed

**Comment by chooyan-eng** [comment]
@kaanavcix 
I guess it's not the problem of implementation of `InputCounterWidgetBuilder`, but of the automatically generated code.
You can fix the compile error by adding `required` to the params `currentLength` and `isFocused` of your `buildCounter` like below.

```dart
buildCounter: (context, {required currentLength, required isFocused, maxLength}) {

}
```
