### ISSUE TITLE
Android/Camera: App is crashing(Crashlytics) - Camera.refreshPreviewCaptureSession

### ISSUE THREAD

**Issue by Shriyanshx** [flutter/flutter#122072]
This issue is similar to - https://github.com/flutter/flutter/issues/117945, https://github.com/flutter/flutter/issues/89352

## Steps to Reproduce

I am not able to reproduce the problem, but it is crashing into many devices.

## Error - 

```
Fatal Exception: java.lang.IllegalArgumentException: No handler given, and current thread has no looper!
       at android.hardware.camera2.impl.CameraDeviceImpl.checkHandler(CameraDeviceImpl.java:2500)
       at android.hardware.camera2.impl.CameraDeviceImpl.checkHandler(CameraDeviceImpl.java:2515)
       at android.hardware.camera2.impl.CameraCaptureSessionImpl.setRepeatingRequest(CameraCaptureSessionImpl.java:312)
       at io.flutter.plugins.camera.Camera.refreshPreviewCaptureSession(Camera.java:33)
       at io.flutter.plugins.camera.Camera.access$900(Camera.java)
       at io.flutter.plugins.camera.Camera$2.onConfigured(Camera.java:48)
       at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.lambda$onConfigured$0$android-hardware-camera2-impl-CallbackProxies$SessionStateCallbackProxy(CallbackProxies.java:53)
       at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy$$ExternalSyntheticLambda6.run(CallbackProxies.java:4)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)

```

### Error Log

[com.sunstone.hub_issue_cc074384fedec63d9a1afa61a87d6429_crash_session_63FE31EA00DB000165A8E8F4C6C53ABD_DNE_8_v2_stacktrace.txt](https://github.com/flutter/flutter/files/10905368/com.sunstone.hub_issue_cc074384fedec63d9a1afa61a87d6429_crash_session_63FE31EA00DB000165A8E8F4C6C53ABD_DNE_8_v2_stacktrace.txt)

### Camera plugin version
camera: 0.10.3

### Flutter doctor
`[✓] Flutter (Channel stable, 3.3.8, on macOS 13.2.1 22D68 darwin-arm, locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
[✓] VS Code (version 1.75.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

`

### Crashlytics screenshot

![Screenshot 2023-03-07 at 9 50 30 AM](https://user-images.githubusercontent.com/109217699/223320080-db29c548-39db-4054-8b1d-79ba69614e68.png)

**Comment by darshankawar** [comment]
@Shriyanshx 
Looking at the error log you shared, it looks similar to https://github.com/flutter/flutter/issues/90070. Can you take a look at that issue, use code sample mentioned in it and see if using it, you get the same error log as you reported ?

**Comment by Shriyanshx** [comment]
@darshankawar  Can't do that as the issue is not replicating with my current code.

**Comment by Shriyanshx** [comment]
I am able to replicate the issue- 

**Steps: -**
1. Start camera
2. go to background instantly
3. go foreground
4. app crashes

_note: sometimes it crashes sometimes not._


@darshankawar I think crash is happening  due to firebase_perfromance plugin - https://github.com/firebase/flutterfire/pull/10560 - 

`[firebase_performance/unknown] Attempt to invoke virtual method 'void com.google.firebase.perf.metrics.HttpMetric.setHttpResponseCode(int)' on a null object reference
I/flutter (19183): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
I/flutter (19183): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
I/flutter (19183): <asynchronous suspension>
I/flutter (19183): #2      MethodChannelHttpMetric.stop (package:firebase_performance_platform_interface/src/method_channel/method_channel_http_metric.dart:80:7)
I/flutter (19183): <asynchronous suspension>
I/flutter (19183): #3      SHNetworkListner.networkRequestEnded (package:hub/network/sh_network_listner.dart:22:5)
I/flutter (19183): <asynchronous suspension>`

**Comment by darshankawar** [comment]
Try to use the newest version of the plugin https://pub.dev/packages/firebase_performance/changelog#09015 which has the fix and try again to see if you still get the same error or not.

**Comment by parmeetmaster** [comment]
Hello I found a solution to fix this issue permanently.Just upgrade compiler version 31 to 33.



![image](https://user-images.githubusercontent.com/42370506/223996364-2da62c89-6cae-4cfe-b3bc-f78c9a2966e0.png)

**Comment by parmeetmaster** [comment]
try to clean flutter project open android folder clear project and then try once.

**Comment by Shriyanshx** [comment]
its on production with 33

**Comment by darshankawar** [comment]
@Shriyanshx 
Did you try this already https://github.com/flutter/flutter/issues/122072#issuecomment-1461321386 ?


> I am able to replicate the issue-
> 
> **Steps: -**
> 
> 1. Start camera
> 2. go to background instantly
> 3. go foreground
> 4. app crashes
> 
> _note: sometimes it crashes sometimes not._
> 
> @darshankawar I think crash is happening due to firebase_perfromance plugin - [firebase/flutterfire#10560](https://github.com/firebase/flutterfire/pull/10560) -
> 
> `[firebase_performance/unknown] Attempt to invoke virtual method 'void com.google.firebase.perf.metrics.HttpMetric.setHttpResponseCode(int)' on a null object reference I/flutter (19183): #0 StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7) I/flutter (19183): #1 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18) I/flutter (19183): <asynchronous suspension> I/flutter (19183): #2 MethodChannelHttpMetric.stop (package:firebase_performance_platform_interface/src/method_channel/method_channel_http_metric.dart:80:7) I/flutter (19183): <asynchronous suspension> I/flutter (19183): #3 SHNetworkListner.networkRequestEnded (package:hub/network/sh_network_listner.dart:22:5) I/flutter (19183): <asynchronous suspension>`

Please provide a complete minimal code sample without third party plugin implementation that triggers this crash, so that we can verify it properly.

**Comment by Shriyanshx** [comment]
@darshankawar  yes still not working

**Comment by darshankawar** [comment]
> Please provide a complete minimal code sample without third party plugin implementation that triggers this crash, so that we can verify it properly.
