### ISSUE TITLE
Dismissible widget has a problem.

### ISSUE THREAD

**Issue by freedemocracy** [flutter/flutter#122077]
There is a problem with the Dismissible widget, the confirmDismiss and onDismissed callbacks do not work with each other

1、Without using confirmDismiss, onDismissed can delete the item normally

2、If confirmDismiss is used, onDismissed will not be executed, regardless of whether confirmDismiss returns true or false.

Stable channel (Windows) Flutter version 3.7.6

The code is very simple, hurry up and fix it flutter has too many bugs, so annoying ah

**Comment by exaby73** [comment]
According to [the documentation](https://api.flutter.dev/flutter/widgets/Dismissible/confirmDismiss.html):

> If the returned Future<bool?> completes to false or null the [onResize](https://api.flutter.dev/flutter/widgets/Dismissible/onResize.html) and [onDismissed](https://api.flutter.dev/flutter/widgets/Dismissible/onDismissed.html) callbacks will not run.

This is working as expected. Therefore, I will close this issue. If you disagree, please comment with your reasoning and I can reopen the issue. Thank you

**Comment by freedemocracy** [comment]
Thank you very much for your answer

After I checked it step by step, I found that the problem is in the following code:

FocusScope.of(context).requestFocus(FocusNode());
_showBottomSheet(context);    

_showBottomSheet is called by: showModalBottomSheet

If the above 2 lines of code together, it will cause onDismissed failure, the specific reason is not clear

Recorded here, later someone encountered, you can see this solution.
