### ISSUE TITLE
`Border.symmetric` seems wrong. Horizontal = top/bottom?

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter#122034]
I really don't understand this. Shouldn't vertical = top/bottom and horizontal = left/right? Why is the opposite?

<img width="591" alt="image" src="https://user-images.githubusercontent.com/351125/223204052-f26561b5-cb6a-4af2-a607-f28779d3ee5d.png">

Source:
https://github.com/flutter/flutter/blob/f5ddece56e0e9d21d3b3f2d46d96330cb7bd789b/packages/flutter/lib/src/painting/box_border.dart#LL340C5-L340C5

Could anyone help me understand if this is intended and why?
EdgeInsets work fine, every other symmetrical Flutter usage seems fine, but Border.symmetric doesn't make sense to me.
This was implemented/updated by @tvolkert about 3 years ago.

**Comment by tvolkert** [comment]
Yep, this is intended (and was changed in https://github.com/flutter/flutter/issues/61470)

It's because the _lines_ on the top and bottom are _horizontal lines_ -- and the _lines_ on the left and right are _vertical lines_.

Per https://en.wikipedia.org/wiki/Vertical_and_horizontal:

> a direction or plane passing by a given point is said to be vertical if it contains the local gravity direction at that point. Conversely, a direction or plane is said to be horizontal (or leveled) if it is perpendicular to the vertical direction.

**Comment by bernaferrari** [comment]
wow, it was hard for me to understand. I guess it makes some sense! Thanks, lol

I saw the original issue but never saw the reason, so I couldn't sleep thinking about this. Thanks!
