### ISSUE TITLE
`flutter doctor` should explicitly say when it can't find Android Studio version

### ISSUE THREAD

**Issue by gnprice** [flutter/flutter#122081]
When the tool isn't able to identify what version an Android Studio installation is, that can cause the build to fail because some logic depends on the Android Studio version. For example:
* #121468 
* #121925 

So when someone's running `flutter doctor -v` because things have gone wrong, the fact that the Android Studio version couldn't be identified is potentially a quite important clue for resolving the problem.

Currently, though, the `flutter doctor` output just suppresses mention of the version when it doesn't know the answer:
```dart
    // in [AndroidStudioValidator.validate]
    final String? studioVersionText = _studio.version == Version.unknown
      ? null
      : userMessages.androidStudioVersion(_studio.version.toString());
```

The result is a line like
```
[!] Android Studio
```

instead of like
```
[✓] Android Studio (version 2022.3)
```

This is too subtle; e.g. in #121925 it wasn't noticed in the first few rounds of debugging. It should instead say something like:
```
[!] Android Studio (unknown version)
```
or perhaps somewhat louder than that.

**Comment by surajsahani** [comment]
This is very common, problem in Flutter. 
there's a workaround if you want to interact with Java Bundle. 

Follow the Steps.
1. Open any flutter project.
2. Now Click on File -> Open, Open the same Project, Select android part and Open it in New Window.
   This will open android part in different window. Bundle issues will be resolved.

![Screenshot from 2023-03-07 13-25-38](https://user-images.githubusercontent.com/22853459/223359590-e093a986-4cd4-4e9e-abdb-a5656ffdeec1.png)

**Comment by gnprice** [comment]
@surajsahani Those steps can be useful to work around problems where the Flutter tool doesn't find the right JDK to use to build the app. That can be caused by the tool not finding the Android Studio version, but other problems can cause the same symptom, and the same problem can cause other symptoms too.

This thread is about better diagnostics for the situation where the tool doesn't find the Android Studio version, so discussion about other problems and about workarounds for them should go elsewhere in order to keep the thread focused.

**Comment by christopherfujino** [comment]
cc @andrewkolos

**Comment by andrewkolos** [comment]
This likely applies to the VSCode validator as well: https://github.com/flutter/flutter/blob/0916375f440bb7128835c9923da1f33b09d26510/packages/flutter_tools/lib/src/vscode/vscode_validator.dart#L27-L29
