### ISSUE TITLE
Getting following device doctor healthcheck error on all Linux machines.

### ISSUE THREAD

**Issue by kentnguyen99** [flutter/flutter#122155]
Will someone take a look the following device doctor healthcheck errors, I'm seeing this error on all Linux machines.

Quarantined: device doctor healthcheck error: b"error: protocol fault (couldn't read status): Connection reset by peer\nUnhandled exception:\nExecutable adb failed with exit code 1.\n#0 fail (package:device_doctor/src/utils.dart:33)\n#1 eval (package:device_doctor/src/utils.dart:105)\n<asynchronous suspension>\n#2 Future.timeout.<anonymous closure> (dart:async/future_impl.dart:870)\n<asynchronous suspension>\n#3 AndroidDeviceDiscovery._deviceListOutputWithRetries.<anonymous closure> (package:device_doctor/src/android_device.dart:54)\n<asynchronous suspension>\n#4 RetryOptions.retry (package:retry/retry.dart:131)\n<asynchronous suspension>\n#5 AndroidDeviceDiscovery._deviceListOutputWithRetries (package:device_doctor/src/android_device.dart:52)\n<asynchronous suspension>\n#6 AndroidDeviceDiscovery.discoverDevices (package:device_doctor/src/android_device.dart:74)\n<asynchronous suspension>\n#7 AndroidDeviceDiscovery.checkDevices (package:device_doctor/src/android_device.dart:104)\n<asynchronous suspension>\n#8 main (file:///b/s/w/ir/x/w/cocoon/device_doctor/bin/main.dart:67)\n<asynchronous suspension>\n"

<img width="1646" alt="Screenshot 2023-03-07 at 5 04 41 PM" src="https://user-images.githubusercontent.com/120754754/223593234-879da083-8759-474f-a230-134da049a791.png">

**Comment by keyonghan** [comment]
Devices seem recoverable by themselves for this error? If not, could you try ssh to the machine as the swarming user, and run an `ade` command? That should bring the bot back.

The root cause should be further investigated. Moving to TD.

**Comment by kentnguyen99** [comment]
Execute the ade command but not found.  Is there package needs to install in order to run ade command?
swarming@flutter-devicelab-linux-27:~$ ade

Command 'ade' not found, did you mean:

**Comment by keyonghan** [comment]
Sorry I meant `adb`.

**Comment by kentnguyen99** [comment]
How do you fix for Mini Mac lost connection from external iPhone device?
<img width="1490" alt="Screenshot 2023-03-08 at 3 47 23 PM" src="https://user-images.githubusercontent.com/120754754/223878682-d096e2c1-0d4a-4800-8951-2766b42157c7.png">

**Comment by keyonghan** [comment]
Could you try:
1) reboot the device
2) reboot the mac
3) unplug/replug the device
4) change a different cable

**Comment by kentnguyen99** [comment]
Suggesting to reboot machine will reset and clear the errors failure.
