### ISSUE TITLE
Cli tool shows wrong method when called with build ipa --export-options-plist

### ISSUE THREAD

**Issue by rossixolit** [flutter/flutter#122179]
When running `flutter build ipa --export-options-plist ...` the log output is always "Building *App Store* IPA..." because the message only takes into account the --export-method arg (and falls back to appstore if not set), and ignores what's set as method inside the plist.
Rather cosmetic issue, but it does lead to confusion - at least I checked the code to see if the .ipa is built with the method set in the plist. (It is, it's just the message that is wrong.)

**Comment by danagbemava-nc** [comment]
Hi @rossixolit,

Please provide your `flutter doctor -v` and the full verbose logs of the command that you run, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with steps to reproduce so that we can investigate this issue. 

Thank you

**Comment by rossixolit** [comment]
It's right here: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/build_ios.dart#L458

The logic does not read the method from the plist file, only from the `--export-method` argument, which is mutually exclusive to `--export-options-plist` - so it will always be not set and the message will always fall back to the default ("App Store") even if the ipa is in fact built for ad-hoc or enterprise.

To reproduce you could take any flutter app and build with `flutter build ipa --export-options-plist PLIST` and have something else than app-store as method in the plist and see that the message will say "Building *App Store* IPA...", even though the .ipa is built with the correct method from the plist.

**Comment by rossixolit** [comment]
...and I just noticed it also outputs the appStore info for non-appstore ipa in https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/build_ios.dart#L516 which would also be fixed if there was a check for the method in the plist.

**Comment by danagbemava-nc** [comment]
Thanks for the info.

Labeling for further insight based on the information shared above.

**Comment by mnguyen427** [comment]
Hi @jmagman @danagbemava-nc, I'd like to pick up this issue. Has it been resolved or assigned to anyone? Thanks.

**Comment by danagbemava-nc** [comment]
@mnguyen427 feel free to work on it

**Comment by raphire08** [comment]
Added PR https://github.com/flutter/flutter/pull/138555
