### ISSUE TITLE
Unable to update Dart SDK on Windows with AllSigned ExecutionPolicy

### ISSUE THREAD

**Issue by bwnyasse** [flutter/flutter#12211]
## Steps to Reproduce

In powershell on Windows 10 for example, ensure that the execution policy is set to **AllSigned**

      Set-Executionpolicy -ExecutionPolicy AllSigned

You can verify the actuel execution policy with the following command : 

      Get-ExecutionPolicy

When running `flutter doctor` , the framework is unable to update Dart SDK because the script update_dart_sdk.ps1 is unsigned.

## Flutter Doctor

![executionpolicyerror](https://user-images.githubusercontent.com/5323628/30750253-3c4ac1f0-9fb6-11e7-9eeb-7939644eef90.png)

_In fact Windows provide a way to change the execution policy , but sometimes users don't have right to change it ( according to the company policy ). 
I guess it will be better to deliver a **signed** update_dart_sdk.ps1 file_

**Comment by Hixie** [comment]
cc @goderbauer

**Comment by goderbauer** [comment]
@bwnyasse We recently fixed a problem around the unsigned PowerShell script. Do you still see this problem?

**Comment by roja** [comment]
I am still seeing this same issue. Happy to help disagnose as it currently stops attempts to update flutter.
