### ISSUE TITLE
certain presubmit targets not scheduled

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#122157]
For example on this run, the following did not run (probably more, I did not exhaustively cross-reference with .ci.yaml):

- Linux tool_integration_tests_*_4
- Linux tool_tests_commands
- Linux tool_tests_general

Where the mac and windows versions appear to have run. The `runIf` fields are the same.

For the PR https://github.com/flutter/flutter/pull/121549, this same issue lead to the PR getting reverted in https://github.com/flutter/flutter/pull/122037 because of a test target that failed post-submit but didn't run presubmit.

**Comment by christopherfujino** [comment]
cc @yusuf-goog infra on-call. provisionally prioritizing this p1, as it has already broken the tree once.

**Comment by keyonghan** [comment]
This seems due to https://github.com/flutter/flutter/issues/122116, which has been fixed. Please help report if any new instances.

**Comment by vashworth** [comment]
Not sure if this is related, but my PR has a couple pre-submit tests that have been stuck for over a day https://github.com/flutter/flutter/pull/121903

**Comment by keyonghan** [comment]
> Not sure if this is related, but my PR has a couple pre-submit tests that have been stuck for over a day https://github.com/flutter/flutter/pull/121903

It is. 
![Screenshot 2023-03-08 at 2 17 10 PM](https://user-images.githubusercontent.com/54558023/223864132-c6531b81-e026-4631-8e8d-740e323923a2.png)

To unblock your PR, I reset those two tasks. They should be good now.

**Comment by keyonghan** [comment]
For reference, here is how to reset those tasks: go/flutter-luci-playbook#manually-trigger-try-pre-submit-builds

**Comment by vashworth** [comment]
Okay awesome, thanks @keyonghan!

**Comment by keyonghan** [comment]
Seems no new instances. Presumably this is resolved with https://github.com/flutter/flutter/issues/122116 fixed. 
Please reopen if same issue repros.
