### ISSUE TITLE
`flutter build web --wasm` doesn't update output with code changes

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#122159]
this code: https://github.com/kevmoo/flutter_web_number_fun at https://github.com/kevmoo/flutter_web_number_fun/commit/8109765992a212ee7c8dee974b5bd4b325f84d06

Flutter at https://github.com/flutter/flutter/commit/80be2bfc9f8cc39d197f616b8ce809217908a5f8

Repro:

- edit code in `lib/main.dart` that changes the output
- rebuild

Expected:

- output updates to show change

Actual:

- no-opt

Work-around

- `rm -rf .dart_tool` and rebuild

Note: deleting `build/web_wasm` does NOT fix it. Have to delete `.dart_tool`

**Comment by eyebrowsoffire** [comment]
This is related to https://github.com/dart-lang/sdk/issues/50747. Now that that is implemented in dart2wasm, I think we can do the proper thing in the flutter tool which should fix this problem.
