### ISSUE TITLE
[webview_flutter] Webview works well on Iphone, but I get blank screen on Ipad

### ISSUE THREAD

**Issue by jjacosta37** [flutter/flutter#122164]
Hi -

Im trying to add Webview to my app. I am using   webview_flutter: ^3.0.4.
The same code is working well on Iphones, but is not showing on Ipads. Any clue why this might happen? Up next the code:

```
class ConnectAccountPage extends StatefulWidget {
  static const id = 'ConnectAccountPage';

  @override
  State<ConnectAccountPage> createState() => _ConnectAccountPageState();
}

class _ConnectAccountPageState extends State<ConnectAccountPage> {
  @override
  void initState() {
    super.initState();
    if (Platform.isAndroid) WebView.platform = AndroidWebView();
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
        future: getToken(),
        builder: (context, snapshot) {
          dynamic initialUrl = Uri.encodeFull(
              'https://widget.belvo.io/?access_token=${snapshot.data}');
          if (!snapshot.hasData) {
            // Future hasn't finished yet, return a placeholder
            return Container(
              color: Colors.black,
              child: const Center(
                child: CircularProgressIndicator(),
              ),
            );
          }

          return SafeArea(
            child: WebView(
              javascriptMode: JavascriptMode.unrestricted,
              initialUrl: initialUrl,
              navigationDelegate: (request) {
                if (request.url.contains('success')) {
                  String link = Uri.parse(request.url).queryParameters['link']!;
                  String institution =
                      Uri.parse(request.url).queryParameters['institution']!;
                  Map data = {'link': link, 'institution': institution};
                  addLink(data, context);
                }
                if (request.url.contains('exit')) {
                  Navigator.pushAndRemoveUntil(
                      context,
                      MaterialPageRoute(
                        builder: (context) =>
                            HomePage(comesFromConnectAccount: false),
                      ),
                      (Route<dynamic> route) => false);
                }
                return request.url == initialUrl
                    ? NavigationDecision.navigate
                    : NavigationDecision.prevent;
              },
            ),
          );
        });
  }
}

Future getToken() async {
  Map result = await HttpRequestsBack.getRequest(endpoint: 'generatetoken/');
  return result['body']['access'];
}

void addLink(data, context) async {
  Navigator.pushAndRemoveUntil(
      context,
      MaterialPageRoute(
        builder: (context) =>
            HomePage(comesFromConnectAccount: true, connectAccuntData: data),
      ),
      (Route<dynamic> route) => false);
}

```

**Comment by danagbemava-nc** [comment]
Hi @jjacosta37, kindly upgrade to the latest version of `webview_flutter`(4.0.6) to see if you still experience this issue. 

If you do, please provide the version of `webview_flutter_wkwebview` that is resolved in your `pubspec.lock`. Please also provide the output of `flutter doctor -v` along with the new complete minimal reproducible code sample and the iPad that you're experiencing the issue on. 

Thank you

**Comment by jjacosta37** [comment]
Hi Daniel - Thank you for answering.

I just updated to the last version of webview_flutter (4.0.6), but keep experiencing the issue. Reproducing the code would be hard, as to construct the webview there is a token that needs to be generated from the BE. 

Im not sure if there is any reason (on the webview_flutter end) why it would work for iPhone devices and not iPad. If not, I am guessing that it may have something to do with the host of the website I am trying to call. I'm not sure if there is any way I could debug this  

wkwebview version

```
webview_flutter_wkwebview:
    dependency: transitive
    description:
      name: webview_flutter_wkwebview
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.2.1"
```


Code

```
import 'package:fintly/screens/homepage.dart';
import 'package:flutter/material.dart';
import 'dart:io';
import 'package:webview_flutter/webview_flutter.dart';
import 'package:fintly/httprequests_back.dart';

class ConnectAccountPage extends StatefulWidget {
  static const id = 'ConnectAccountPage';

  @override
  State<ConnectAccountPage> createState() => _ConnectAccountPageState();
}

class _ConnectAccountPageState extends State<ConnectAccountPage> {
  @override
  void initState() {
    super.initState();
  }

  WebViewController createWebviewControler(
      BuildContext context, dynamic initialUrl) {
    return WebViewController()
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setBackgroundColor(const Color(0x00000000))
      ..setNavigationDelegate(
        NavigationDelegate(
          onProgress: (int progress) {
            // Update loading bar.
          },
          onPageStarted: (String url) {},
          onPageFinished: (String url) {},
          onWebResourceError: (WebResourceError error) {},
          onNavigationRequest: (NavigationRequest request) {
            if (request.url.contains('success')) {
              String link = Uri.parse(request.url).queryParameters['link']!;
              String institution =
                  Uri.parse(request.url).queryParameters['institution']!;
              Map data = {'link': link, 'institution': institution};
              addLink(data, context);
            }
            if (request.url.contains('exit')) {
              Navigator.pushAndRemoveUntil(
                  context,
                  MaterialPageRoute(
                    builder: (context) =>
                        HomePage(comesFromConnectAccount: false),
                  ),
                  (Route<dynamic> route) => false);
            }
            return request.url == initialUrl
                ? NavigationDecision.navigate
                : NavigationDecision.prevent;
          },
        ),
      )
      ..loadRequest(Uri.parse(initialUrl));
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
        future: getToken(),
        builder: (context, snapshot) {
          dynamic initialUrl = Uri.encodeFull(
              'https://widget.belvo.io/?access_token=${snapshot.data}');
          if (!snapshot.hasData) {
            // Future hasn't finished yet, return a placeholder
            return Container(
              color: Colors.black,
              child: const Center(
                child: CircularProgressIndicator(),
              ),
            );
          }

          return SafeArea(
            child: WebViewWidget(
              controller: createWebviewControler(context, initialUrl),
            ),
          );
        });
  }
}

Future getToken() async {
  Map result = await HttpRequestsBack.getRequest(endpoint: 'generatetoken/');
  return result['body']['access'];
}

void addLink(data, context) async {
  Navigator.pushAndRemoveUntil(
      context,
      MaterialPageRoute(
        builder: (context) =>
            HomePage(comesFromConnectAccount: true, connectAccuntData: data),
      ),
      (Route<dynamic> route) => false);
}

```



Flutter Doctor results

```
✓] Flutter (Channel stable, 3.3.9, on macOS 12.6.3 21G419 darwin-x64, locale en-US)
    • Flutter version 3.3.9 on channel stable at /Users/j0a0gif/Developer/Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (4 months ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/j0a0gif/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.68.1)
    • VS Code at /Users/j0a0gif/Downloads/Visual Studio Code 2.app/Contents
    • Flutter extension version 3.60.0

[✓] VS Code (version 1.63.2)
    • VS Code at /Users/j0a0gif/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • Ipad Pro iOS 16.1 (mobile) • 29BC932B-247B-4D93-A3BF-09787CF0C843 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 12.6.3 21G419 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 110.0.5481.177

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by danagbemava-nc** [comment]
Hi @jjacosta37, if you open the `flutter.dev` site in the webview on the iPad, do you still experience the bug? Or are you experiencing this bug with a specific URL?

**Comment by jjacosta37** [comment]
Hi Daniel - I only experience the bug with this specific URL. If I open the flutter.dev site on the iPad it works well

**Comment by danagbemava-nc** [comment]
Hi @jjacosta37, can you provide us with a token or a way to get a token so that we can investigate? 

Also what iPads and what version of iPadOS are you experiencing the issue on? 

Can you also check with Safari to see if there's an error thrown when you try to access the page on iPads? I believe you should be able to monitor the webview console from safari when you check the develop menu and select the webview application

**Comment by esam12** [comment]
same issue, only experience the bug with this specific URL. If I open the flutter.dev site on the phone it works well

Myphone : 13 pro max
IOS : 16.1.1

**Comment by jjacosta37** [comment]
Hi - I was able to solve the issue by setting the user agent as if always an iPhone. I did this on the 3.0.4 version. This is what my webview looks like:

I created a function using the device_plus_info package to know whether the user is using an iPad or an iPhone, and then only send the user agent if user is on an iPad (no need to mess with iPhone).

Not the most ideal solution (UI looks weird) but it worked for me.

```
     child: WebView(
              userAgent: isIpad
                  ? 'Mozilla/5.0 (iPhone; CPU iPhone OS 12_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Mobile/15E148 Safari/604.1'
                  : null,
              javascriptMode: JavascriptMode.unrestricted,
              initialUrl: initialUrl,
              navigationDelegate: (request) {
                if (request.url.contains('success')) {
                  String link = Uri.parse(request.url).queryParameters['link']!;
                  String institution =
                      Uri.parse(request.url).queryParameters['institution']!;
                  Map data = {'link': link, 'institution': institution};
                  addLink(data, context);
                }
                if (request.url.contains('exit')) {
                  Navigator.pushAndRemoveUntil(
                      context,
                      MaterialPageRoute(
                        builder: (context) =>
                            HomePage(comesFromConnectAccount: false),
                      ),
                      (Route<dynamic> route) => false);
                }
                return request.url == initialUrl
                    ? NavigationDecision.navigate
                    : NavigationDecision.prevent;
              },
            ),
```

**Comment by esam12** [comment]
Hi - @jjacosta37 , I tried it, but it didn't work for me

**Comment by danagbemava-nc** [comment]
Hi @esam12, can you provide a complete minimal reproducible code sample with the URL you're experiencing this issue with so that we can investigate this issue? 

Thank you

**Comment by esam12** [comment]
Hi @danagbemava-nc Thank you for your interest, of course this is the code : 


import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

class WebViewExample extends StatefulWidget {
  const WebViewExample({super.key});

  @override
  State<WebViewExample> createState() => _WebViewExampleState();
}

class _WebViewExampleState extends State<WebViewExample> {
  late final WebViewController _controller;

  @override
  void dispose() {
    super.dispose();
  }

  getin() {
    final WebViewController controller =
        WebViewController(); // #enddocregion platform_features
    controller.setJavaScriptMode(JavaScriptMode.unrestricted);
    controller.loadRequest(Uri.parse('https://odoo.com'));
    _controller = controller;
  }

  @override
  void initState() {
    super.initState();
    getin();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Flutter WebView example'),
      ),
      body: WebViewWidget(
        controller: _controller,
      ),
      floatingActionButton: favoriteButton(),
    );
  }

  Widget favoriteButton() {
    return FloatingActionButton(
      onPressed: () async {
        final String? url = await _controller.currentUrl();
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Favorited $url')),
        );
      },
      child: const Icon(Icons.favorite),
    );
  }
}

**Comment by danagbemava-nc** [comment]
Hi @esam12, I tested on an iPhone XS running iOS 16.3.1 and the website opened just fine for me.  See the screenshot below

<img src="https://user-images.githubusercontent.com/88313112/225308867-eb7f4915-152e-4c6e-807f-84e484e7bef2.PNG" width="300"/> 

Can you use `Safari` to check if any errors are being thrown when you try to access the website?

You'll need to enable `Web Inspector` in `Safari` settings on your iPhone. Open `Settings > Safari > Advanced` and toggle `Web Inspector`. Then you can use the develop menu in safari (on mac) to access the console. See the screenshot below for how to locate it. 

<img width="751" alt="Screenshot 2023-03-15 at 12 25 19" src="https://user-images.githubusercontent.com/88313112/225308957-3cd82309-8a00-4799-899f-764b6ef0e9da.png">

Can you also upgrade to the latest version of iOS to see if you still face the issue?

**Comment by danagbemava-nc** [comment]
The launch mode you've set for `url_launcher` is `LaunchMode.externalApplication` which is why it's opening an external application. You can try using `LaunchMode.inAppWebview`. 

We've gone a bit off track in what this issue is supposed to track and also it seems like the issues have been resolved without any intervention from our end as such I'm going to have to reluctantly close this issue.

If anyone runs into the original issue, kindly file a new issue and provide detailed steps to reproduce it so that we can investigate this issue. 

Thank you
