### ISSUE TITLE
Flutter Feature Request to Get Real Date Time Without Internet

### ISSUE THREAD

**Issue by abdulrehmananwar** [flutter/flutter#122110]
i am using android phone and in setting there is a option Network Provide Time and if i turned it off then i can change my phone time manully.
i dont have internet to check my time only. i just using sim card which auto correct time in offline mode as well.
i want in flutter app to get real time without internet connection.

**Comment by abdulrehmananwar** [comment]
There also need any option to read phone system settings to check time setting mode is manual or network provided.

**Comment by stuartmorgan** [comment]
Specialized methods for determining the time without trusting the OS APIs is out of scope for Flutter; they would be best implemented as community plugins.
