### ISSUE TITLE
Error when capturing iOS screenshots in Flutter app

### ISSUE THREAD

**Issue by arslanrazacrew** [flutter/flutter#122173]
When attempting to capture screenshots in my Flutter app on an iOS device, I receive the following error message: "[VERBOSE-2:platform_view_layer.cc(19)] Trying to embed a platform view but the PrerollContext does not support embedding". I have tried updating to the latest version of Flutter and plugins, wrapping the code in a WidgetsBinding.instance.addPostFrameCallback method, and using the UiKitView widget for iOS platform views, but the issue persists. Any help in resolving this error would be greatly appreciated.
more I have added 
    <key>io.flutter.embedded_views_preview</key>
	<true/> in my info.plist

**[VERBOSE-2:platform_view_layer.cc(19)] Trying to embed a platform view but the PrerollContext does not support embedding**

**Comment by danagbemava-nc** [comment]
Hi @arslanrazacrew,

Please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with steps to reproduce so that we can investigate this issue. 

Thank you
