### ISSUE TITLE
[google_maps_flutter] Update example app android configuration to fix building

### ISSUE THREAD

**Issue by Rexios80** [flutter/flutter#122137]
Currently I get this error when I open the project:
![](https://user-images.githubusercontent.com/7896519/223564365-490e87d4-2207-4dd5-8e74-3ede361739d4.png)

**Comment by stuartmorgan** [comment]
Why are you trying to build with Java 17?

**Comment by Rexios80** [comment]
It comes bundled with newer versions of Android Studio. Most projects are updated so it doesn't matter, not sure how this one survived this long without someone bumping the versions.

**Comment by stuartmorgan** [comment]
> Most projects are updated so it doesn't matter

I don't follow; a quick scan shows that 2/3 of our packages are a version older than 7.2.

> not sure how this one survived this long without someone bumping the versions.

I've never seen anyone report this issue before, and CI builds fine, so I'm not sure why it would be surprising (and IIRC we've had some issues in the past with incompatibilities with AGP updates).

**Comment by Rexios80** [comment]
Okay so the bundled java version change hasn't hit stable yet, but it is now on beta which means it should hit stable soon and everyone will start seeing the issues as they update. It seems to be version Flamingo that introduced the change. I always run Android Studio Canary, so that's why I've had this issue for a long time.

What I meant by "most projects are updated" is most plugins/packages are updated already. It makes sense that an example project could slip through the cracks because most people don't end up actually running them.

**Comment by stuartmorgan** [comment]
@reidbaker If the next version of Android Studio is going to require AGP 7.2+, should we mass-update flutter/packages so we don't end up with a lot of piecemeal PRs like the one linked above?

**Comment by reidbaker** [comment]
> @reidbaker If the next version of Android Studio is going to require AGP 7.2+, should we mass-update flutter/packages so we don't end up with a lot of piecemeal PRs like the one linked above?

yes it looks like we will need to do that.
