### ISSUE TITLE
[pigeon] Support pass int64 from Swift to Dart

### ISSUE THREAD

**Issue by bc-lee** [flutter/flutter#122160]
According to https://github.com/flutter/packages/blob/4aa259aa4f21e2cf510e5fc7755fbd26175807f2/packages/pigeon/lib/swift_generator.dart#L711, Users don't seem to be able to pass int64 without converting to another type like int32 or double.

Example dart code:
```dart
import 'package:pigeon/pigeon.dart';

@FlutterApi()
abstract class Callback {
  void onEvent(int timestampNs);
}
```

generates following swift code:
```swift
/// Generated class from Pigeon that represents Flutter messages that can be called from Swift.
class Callback {
  private let binaryMessenger: FlutterBinaryMessenger
  init(binaryMessenger: FlutterBinaryMessenger){
    self.binaryMessenger = binaryMessenger
  }
  func onEvent(timestampNs timestampNsArg: Int32, completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.Callback.onEvent", binaryMessenger: binaryMessenger)
    channel.sendMessage([timestampNsArg] as [Any?]) { _ in
      completion()
    }
  }
}
```

It would be nice to be able to pass int64 from Swift to Dart using pigeon.

**Comment by huycozy** [comment]
Thanks for the report! This is a known issue being tracked at https://github.com/flutter/flutter/issues/120861. Closing this issue as a duplicate, so please follow up on it for further updates.

**Comment by stuartmorgan** [comment]
This is unrelated to exceptions

**Comment by stuartmorgan** [comment]
We fixed this for Kotlin, but not Swift.

@tarrinneal per discussion we should also add an e2e test that echos an int outside the 32-bit range.
