### ISSUE TITLE
"Unimplemented handling of missing static target" test failure

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#122163]
Splitting off from https://github.com/flutter/flutter/issues/121703#issuecomment-1450453979:

https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20flutter_gallery__transition_perf_e2e_impeller_ios/2876/overview failed with the compilation error:
```
Unimplemented handling of missing static target
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8788270337242662161/+/u/run_flutter_gallery__transition_perf_e2e_impeller_ios/test_stdout

That message is coming from Dart:
https://github.com/dart-lang/sdk/blob/8627463c237951126db4ca9fd47854cd1879f8d2/runtime/vm/compiler/frontend/kernel_translation_helper.cc#L533

cc @a-siva @rmacnak-google @zanderso

**Comment by a-siva** [comment]
@jmagman  https://dart-review.googlesource.com/c/sdk/+/291055 was submitted to produce more detailed error message about the missing target and some code around this was also changed. Do you still see error messages from the test, if not can we close the issue.

**Comment by jmagman** [comment]
We can close this.  Looks like there's a duplicate I missed when I filed this, which I also closed https://github.com/flutter/flutter/issues/59005.
