### ISSUE TITLE
Machine win-6 marked as dead on monitoring website.

### ISSUE THREAD

**Issue by kentnguyen99** [flutter/flutter#122112]
Machine win-6 marked as dead on monitoring website.
![Screenshot 2023-03-07 9 44 20 AM](https://user-images.githubusercontent.com/120754754/223505522-6db4f387-4c1a-4336-9651-6e5d4312d9ea.png)

**Comment by yusuf-goog** [comment]
this looks like its back up, can we close?

**Comment by kentnguyen99** [comment]
Machine win-6 is back online and running.  Machine win-6 was hung and required power recycle Windows OS.
