### ISSUE TITLE
[CP] Remove obsolete builders

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#122205]
### issue_link

https://github.com/flutter/flutter/issues/122204

### Commit Hash

36446d82542a1ccdf608115dbd50043607826039

### Target

stable

### pr_link

https://github.com/flutter/engine/pull/40143

### Impacted Users

release engineering team

### Impact Description

Builds showing up as pending forever in stable and beta branches.

### Workaround

N/A

### Risk

low

### Test Coverage

yes

### Validation Steps

Validated presubmit tests are passing correctly.

**Comment by itsjustkevin** [comment]
Will this change get picked up for the next beta or will we need to cherry-pick this into the beta branch also?

**Comment by godofredoc** [comment]
It will also need to land in beta.
