### ISSUE TITLE
Error connecting to observatory

### ISSUE THREAD

**Issue by tain335** [flutter/flutter#12222]
## Steps to Reproduce
run command: flutter run

Flutter app can start normally，but it throw a exception.
I try three android devices, but all have the same exception.

## Logs
Unhandled exception:
Exception: Error connecting to observatory: WebSocketChannelException: WebSocketChannelException: WebSocketException: Connection to 'http://127.0.0.1:8104/ws#' was not upgraded to websocket
#0      throwToolExit (package:flutter_tools/src/base/common.dart:29)
#1      VM.invokeRpcRaw (package:flutter_tools/src/vmservice.dart:738)
<asynchronous suspension>
#2      VM._fetchDirect (package:flutter_tools/src/vmservice.dart:566)
<asynchronous suspension>
#3      ServiceObject.reload (package:flutter_tools/src/vmservice.dart:414)
<asynchronous suspension>
#4      VMService.getVM (package:flutter_tools/src/vmservice.dart:243)
#5      FlutterDevice.getVMs (package:flutter_tools/src/resident_runner.dart:88)
<asynchronous suspension>
#6      ResidentRunner.connectToServiceProtocol (package:flutter_tools/src/resident_runner.dart:584)
<asynchronous suspension>
#7      HotRunner.attach (package:flutter_tools/src/run_hot.dart:106)
<asynchronous suspension>
#8      HotRunner.run (package:flutter_tools/src/run_hot.dart:209)
<asynchronous suspension>
#9      AppDomain.startApp.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:418)
<asynchronous suspension>
#10     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#11     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#12     _rootRun (dart:async/zone.dart:1120)
#13     _CustomZone.run (dart:async/zone.dart:1001)
#14     runZoned (dart:async/zone.dart:1467)
#15     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#16     AppInstance._runInZone (package:flutter_tools/src/commands/daemon.dart:774)
#17     AppDomain.startApp (package:flutter_tools/src/commands/daemon.dart:416)
<asynchronous suspension>
#18     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:267)
<asynchronous suspension>
#19     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:239)
<asynchronous suspension>
#20     RunCommand.verifyThenRunCommand (package:flutter_tools/src/commands/run.dart:232)
<asynchronous suspension>
#21     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:181)
<asynchronous suspension>
#22     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#23     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:276)
<asynchronous suspension>
#24     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#25     new Future.sync (dart:async/future.dart:222)
#26     CommandRunner.run (package:args/command_runner.dart:109)
#27     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:161)
#28     run.<anonymous closure> (package:flutter_tools/executable.dart:143)
<asynchronous suspension>
#29     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#30     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#31     _rootRun (dart:async/zone.dart:1120)
#32     _CustomZone.run (dart:async/zone.dart:1001)
#33     runZoned (dart:async/zone.dart:1467)
#34     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#35     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#36     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#37     main (file:///E:/flutter-workspace/libs/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#38     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

## Flutter Doctor
E:\flutter-workspace\secret>flutter doctor
[√] Flutter (on Microsoft Windows [Version 6.1.7601], locale zh-CN, channel master)
    • Flutter at E:\flutter-workspace\libs\flutter
    • Framework revision c44aa2665d (7 hours ago), 2017-09-22 15:33:50 -0700
    • Engine revision 0a6e415b60
    • Tools Dart version 1.25.0-dev.11.0

[√] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at E:\Android\sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: E:\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-736)

[√] Android Studio (version 3.0)
    • Android Studio at E:\android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-736)

[√] IntelliJ IDEA Ultimate Edition (version 2017.2)
    • Flutter plugin version 17.0
    • Dart plugin version 172.4155.35

[√] Connected devices
    • PRO 6 Plus • M960BDPN2223K     • android-arm • Android 6.0.1 (API 23)
    • PRO 6 Plus • 172.18.8.159:5555 • android-arm • Android 6.0.1 (API 23)

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by tain335** [comment]
But  I  can access  the page in chrome: http://127.0.0.1:8104/#/

**Comment by tain335** [comment]
I resolved,because I set the env variable 'http_proxy'.

**Comment by pluveto** [comment]
Set no_proxy = "localhost,0,1,2,3,4,5,6,7,8,9" to solve this.
