### ISSUE TITLE
[packages] Run AGP update on all examples

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#122213]
See discussion in https://github.com/flutter/packages/pull/3408 and https://github.com/flutter/flutter/issues/122137. We should make all of the examples compatible with the upcoming version of Android Studio, and make the examples consistent (especially the linter settings).

**Comment by bartekpacia** [comment]
Should the integration test apps and benchmarks apps under in [dev](https://github.com/flutter/flutter/tree/master/dev) be migrated as well?

**Comment by reidbaker** [comment]
https://developer.android.com/studio/build/agp-upgrade-assistant#run-upgrade-assistant

**Comment by reidbaker** [comment]
> Should the integration test apps and benchmark apps in [dev](https://github.com/flutter/flutter/tree/master/dev) be migrated as well?

Yes but that should be a different issue.

**Comment by reidbaker** [comment]
All packages in flutter/packages are running at least gradle 7.6.1. With @stuartmorgan's change to conditionally support namespace all packages should support AGP 8.0 (unknown behavior with 8.1). Closing.
