### ISSUE TITLE
Transition animation curves used by Cupertino are outdated

### ISSUE THREAD

**Issue by ivirtex** [flutter/flutter#122247]
CupertinoPageRoute animations are now outdated and don't feel native to the user.
Related to the https://github.com/flutter/flutter/issues/22862

**Expected results:**
Transition animation being close to native.

**Actual results:**
1. Transition duration is 100 ms shorter than native iOS.
2. Native transition starts slowly and quickly accelerates, rather than being linear from the beginning.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      title: 'Cupertino App',
      home: CupertinoPageScaffold(
        navigationBar: const CupertinoNavigationBar(
          middle: Text('Cupertino App Bar'),
        ),
        child: Center(
          child: Builder(builder: (context) {
            return CupertinoButton(
              child: const Text('Next Page'),
              onPressed: () {
                Navigator.push(
                  context,
                  CupertinoPageRoute(builder: (context) => const SecondPage()),
                );
              },
            );
          }),
        ),
      ),
    );
  }
}

class SecondPage extends StatelessWidget {
  const SecondPage({super.key});

  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: const CupertinoNavigationBar(
        middle: Text('Second Page'),
      ),
      child: Center(
        child: CupertinoButton(
          child: const Text('Back'),
          onPressed: () {
            Navigator.pop(context);
          },
        ),
      ),
    );
  }
}

```
</details>

https://user-images.githubusercontent.com/57679865/223876857-16f78682-9b24-4d32-9daf-d299efd57c03.mov

**Comment by darshankawar** [comment]
@ivirtex 
Can you provide a minimal code sample that highlights the behavior you are reporting along with expected result that you are looking for ?

**Comment by ivirtex** [comment]
@darshankawar Sure, I updated the description.

**Comment by ivirtex** [comment]
@bernaferrari Thanks! 
This app has overlaid iOS platform view which sends its ViewController's position relative to the screen via a platform channel every frame. Flutter measures relative position of own pages in a similar way. 
Then, data sent by iOS and Flutter is captured and drawn using a `CustomPainter`.

Whole tool has been merged in https://github.com/flutter/platform_tests/pull/18, so you can check details of the implementation or try it yourself :)
