### ISSUE TITLE
[Impeller] Impeller implements ImageQuality differently than Skia.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#122219]
During an overview of the use-cases of "pixel art" in Flutter, it was discovered that Impellers notion of ImageQuality as being tied to texture sampler options is incorrect. Instead, quality is determined using a separate filter. Impeller must match Skia behavior here. The "pixel art" use-case is not related to geometric aliasing (intentional or otherwise).

**Comment by jonahwilliams** [comment]
I don't think this is actually true? If you look at the Flutter API, setting FilterQuality on a transform widget causes us to create a Matrix IMageFilter instead of apply a transform to the children.

But setting the FilterQuality on an image should just be sampling options

**Comment by chinmaygarde** [comment]
I was under the impression that we were not matching Skia behavior. But this was a while ago. Thanks for the clarification.
