### ISSUE TITLE
Color of suffixIcon changes to red when ussing ErrorText  in TextField -Material 3 design

### ISSUE THREAD

**Issue by Saad-202** [flutter/flutter#122293]
I am using Material 3 design in my flutter app, In my textField, Color of SuffixIcon is the default one but when I use errorText the Color of textField changes to red automatically.

### Steps to reproduce:

1- create an application and use material3 design
2- create a textfield  and suffixIcon
3- give a value to errorText

### expected result:
the color of suffixIcon  Icon should not be  red when using errorText

### sample code:
```
void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(),
      home: Scaffold(
        body: Padding(
          padding: const EdgeInsets.all(8.0),
          child: Center(
            child: TextField(
              decoration: InputDecoration(
                errorText: '',
                suffixIcon: Icon(Icons.visibility),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

## result (material3):

![Screenshot (40)](https://user-images.githubusercontent.com/114399861/224043630-6a755425-89e8-497b-a6c5-e2e6de22f759.png)

## without using errorText:

![Screenshot (41)](https://user-images.githubusercontent.com/114399861/224045209-16ba8e96-745f-4c6e-bed0-40d58685d7b4.png)

## Expected Result (material 2 design) :

![Screenshot (39)](https://user-images.githubusercontent.com/114399861/224043706-9e5bba17-3ba5-4f74-99f5-8c8ab4bd58f5.png)

I don't know if they changed it or it is a bug ,but it should not be red when there is an error in textField

**Comment by exaby73** [comment]
Hello @Saad-202. This is inline with the Material Specs. See https://m3.material.io/components/text-fields/specs#a3fc535d-b5c5-405d-9293-4671340d7411. Since this is intended, I am closing this issue. Thank you
