### ISSUE TITLE
Can I help translating the tutorials?

### ISSUE THREAD

**Issue by valtim** [flutter/flutter#122287]
I'm following the step by step tutorials and I think it's really sufficient to learn flutter but the language is a barrier to a lot of developers specially in Brazil. 

Perhaps "ma english to bad(orkut)" but I think it is a wonderful opportunity to train English AND learn flutter.

**Comment by bartekpacia** [comment]
> learn angular

Are you sure you're in the right place?

**Comment by valtim** [comment]
> > learn angular
> 
> Are you sure you're in the right place?
Thank's for the correction...
