### ISSUE TITLE
Unable to fetch offers of a subscription using In_App_Purchase package.

### ISSUE THREAD

**Issue by utgupta27** [flutter/flutter#122286]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Create a Auto-renewable subscription in Google play console
Add a base plan
Create multiple offer inside the base plan
Now using flutter in_app_purchase package, try to fetch the product(subscription) with offers.

### Actual results

Should get the details of the Offer and upon calling purchase method, the Google Play Purchase Popup should show the offer to the user.

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```
flutter doctor --verbose 
[✓] Flutter (Channel stable, 3.7.6, on macOS 13.2.1 22D68 darwin-arm64, locale
    en-IN)
    • Flutter version 3.7.6 on channel stable at
      /Users/utgupta27/Programs/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12cb4eb7a0 (8 days ago), 2023-03-01 10:29:26 -0800
    • Engine revision ada363ee93
    • Dart version 2.19.3
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/<username>/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.76.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • M2873Y36 (mobile) • UCXOMZSCDGVDELN • android-arm    • Android 10 (API
      29)
    • macOS (desktop)    • macos            • darwin-arm64   • macOS 13.2.1
      22D68 darwin-arm64
    • Chrome (web)       • chrome           • web-javascript • Google Chrome
      110.0.5481.177

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
</details>

**Comment by exaby73** [comment]
Hello @utgupta27. Could you provide a [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that I can verify this issue?
