### ISSUE TITLE
iOS - No longer getting helpful commands or reloading / hot reloading options after running flutter-run in a new app.

### ISSUE THREAD

**Issue by dabit3** [flutter/flutter#12224]
## Steps to Reproduce

flutter create myapp

flutter run

![screen shot 2017-09-23 at 12 29 23 pm](https://user-images.githubusercontent.com/1857282/30775519-dd21f4aa-a05a-11e7-9b50-a31cca051d77.png)

<img width="525" alt="screen shot 2017-09-23 at 1 00 02 pm" src="https://user-images.githubusercontent.com/1857282/30775732-3ac62442-a05f-11e7-912e-44a93823571c.png">

![screen shot 2017-09-23 at 12 58 14 pm](https://user-images.githubusercontent.com/1857282/30775733-3ac71eb0-a05f-11e7-8779-369c0ebbc7ca.png)

## Logs

Launching lib/main.dart on iPhone 7 in debug mode...

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-US, channel alpha)
    • Flutter at /Users/naderdabit/bin/flutter
    • Framework revision 701d534ba9 (11 days ago), 2017-09-12 14:01:51 -0700
    • Engine revision 31d03de019
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/naderdabit/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.0, Build version 9A235
    • ios-deploy 1.9.2
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Connected devices
    • iPhone 7 • 0B9AFAA5-1D2B-4AD4-8448-C93DBBB83A8D • ios • iOS 11.0 (simulator)

**Comment by dabit3** [comment]
Update: This is just happening on iOS, Android is still working fine for me.

**Comment by jwmcglynn** [comment]
+1, this started happening after I updated to Xcode 9.  It repros on the latest alpha channel, but *not* on the master channel.

**Comment by themnd** [comment]
+1

**Comment by lwoerdeman** [comment]
+1

**Comment by dabit3** [comment]
Ok, so installing a simulator at version 10.3.1 fixed this for now, just make sure you run on the 10.3.1 simulator. This issue seems to only be happening in the version 11.0.

**Comment by sethladd** [comment]
@cbracken we've updated support for XCode 9, yes? Do we expect this to work now?

**Comment by cbracken** [comment]
Yep - alpha's been rolled and includes all the Xcode 9 support. Please re-open if you're still encountering issues after a `flutter upgrade`.

**Comment by dabit3** [comment]
Awesome, thanks!
