### ISSUE TITLE
Exception caught by widgets library 

### ISSUE THREAD

**Issue by jimbo-jones1313** [flutter/flutter#122299]
======== Exception caught by widgets library =======================================================
The following assertion was thrown building _ZoomEnterTransition(state: _ZoomEnterTransitionState#0a44f):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4692 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub.

The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///C:/.../AndroidStudioProjects/MonreposMuseum/lib/main.dart:23:12
When the exception was thrown, this was the stack: 
#2      Element.rebuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4692:14)
#3      Element.rebuild (package:flutter/src/widgets/framework.dart:4695:6)
#4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
#5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124:11)
#6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
...     Normal element mounting (77 frames)
#83     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#84     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#85     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6524:32)
...     Normal element mounting (680 frames)
#765    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#766    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#767    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6524:32)
...     Normal element mounting (680 frames)
#1447   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#1448   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#1449   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6524:32)
...     Normal element mounting (680 frames)
#2129   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#2130   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#2131   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6524:32)
...     Normal element mounting (680 frames)
#2811   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#2812   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#2813   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6524:32)
...     Normal element mounting (680 frames)
#3493   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#3494   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#3495   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6524:32)
...     Normal element mounting (680 frames)
#4175   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#4176   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#4177   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6524:32)
...     Normal element mounting (680 frames)
#4857   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#4858   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#4859   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6524:32)
...     Normal element mounting (680 frames)
#5539   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#5540   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#5541   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6524:32)
...     Normal element mounting (680 frames)
#6221   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#6222   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#6223   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6524:32)
...     Normal element mounting (680 frames)
#6903   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#6904   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#6905   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6524:32)
...     Normal element mounting (680 frames)
#7585   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#7586   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#7587   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6524:32)
...     Normal element mounting (467 frames)
#8054   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#8055   Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
#8056   RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1176:16)
#8057   RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1145:5)
#8058   RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1092:18)
#8059   BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2682:19)
#8060   RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1091:13)
#8061   WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:926:7)
#8062   WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:906:7)
#8066   _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
(elided 5 frames from class _AssertionError, class _Timer, and dart:async-patch)

**Comment by jimbo-jones1313** [comment]
I just did what Android told me to do.
I never expect anything like help here.

**Comment by bartekpacia** [comment]
Ah, sure :)

> Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub.

I also think this message is "too encouraging", most of the time it's not a bug in Flutter but people making errors and causing assertions in the framework to fire.

**Comment by jimbo-jones1313** [comment]
If I "restart from scratch," etc. (which I will do), I will eventually solve the problem, so even responding to the Android prompt/request is just a waste of time.

**Comment by gnprice** [comment]
> most of the time it's not a bug in Flutter but people making errors and causing assertions in the framework to fire.

I think the idea of that prompt is that if there's a raw assertion like this that developers are hitting when using Flutter, then we would like to upgrade that assertion to a fancier `FlutterError` that provides some more useful information to help the developer figure out what's wrong and what they should be doing differently. That's a useful thing to do.

However, the issue is only helpful if it's filed with the information that makes it possible to diagnose and fix. @jimbo-jones1313 if at some point you would like to file an issue by [using the New issue button](https://github.com/flutter/flutter/issues/new/choose) and filling out the information in the template, including a minimal, reproducible example, that will be appreciated and can help improve Flutter for everyone. You're quite right that if you file an issue without any of the information we ask for, then that is not a good use of time.
