### ISSUE TITLE
FlutterTestRunner Not working on Firebase Test Lab with Flutter version 3.3.4

### ISSUE THREAD

**Issue by akagupta9** [flutter/flutter#122264]
My Flutter Doctor -

`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.2.1 21D62 darwin-arm, locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.76.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.`

I have done the proper setup with AndroidTest using Flutter Integration Test with Firebase Test Lab. 

`ERROR: (gcloud.firebase.test.android.run)
2580
Matrix [matrix-uq8ir6w9l2hha] failed during validation: The test APK does not contain the test runner class specified by the user or the manifest file. The test runner class name may be incorrect, or the class may be mislocated in the app APK..
2581
Error: Process completed with exit code 1.`

**Comment by darshankawar** [comment]
@akagupta9 
Can you provide the command you are using / running that throws this error ? Looking at the error, `the class may be mislocated in the app apk`, indicating it could be that the arguments you are passing in the command maybe incorrect.
