### ISSUE TITLE
Linux Web Framework tests engine shard regressed ~10 minutes

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#122211]
Over the past two weeks, the Linux Web Framework tests engine shard has become about 10 minutes slower, and is now the slowest build on the engine tree by a margin of about 5 minutes. The goal is for engine tree builds to take about 30 minutes. A few builds are a little slower than that, but this shard is now running consistently for about 45 minutes. This needs attention from the web team.

cc @yjbanov

**Comment by zanderso** [comment]
A major component is that the `wasm_release` build step is taking about 15 minutes. It looks like this build is not goma enabled, and so it should be using `autoninja` to build. However it looks like it is using this recipe module here: https://flutter.googlesource.com/recipes/+/refs/heads/main/recipe_modules/build_util/api.py#63, which is doing an entirely serial build.

**Comment by zanderso** [comment]
`wasm_release` is also still building in the Linux Host Engine config here https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/engine/engine.py#742. So https://github.com/flutter/flutter/issues/119250 is also still relevant, and probably has the same solution.

**Comment by zanderso** [comment]
It looks like `autoninja` support has been removed from CI. I'm not sure whether some mitigation was put in place to handle the reduction in build performance, but on further investigation, the `wasm_release` build appears to be taking about 8 minutes on an `e2-standard-32` configuration, and 15-20 minutes on `n1-standard-8` configurations.

I'm routing this issue to infra to make sure that when we are running the `wasm_release` build, it should be pinned to the `e2-standard-32` configuration. So far, those are
- [ ] Linux Web Framework tests 
- [ ] Linux Host Engine
- [ ] Linux Web Engine

@yjbanov @eyebrowsoffire Are there any others?

**Comment by zanderso** [comment]
cc @godofredoc what was the reason that `autoninja` was removed from CI? Does `ninja` itself now detect the right `-j` argument when goma is not being used?

**Comment by godofredoc** [comment]
Chromium deprecated autoninja and removed it from depot_tools recipes.

**Comment by godofredoc** [comment]
According to goma people ninja sets the appropriate values but it can be overwritten if necessary.

**Comment by godofredoc** [comment]
By the way the removal of autoninja happened a couple of quarters ago, if this regression younger than a quarter it could be related to something else.

**Comment by godofredoc** [comment]
Actually thinking a bit more about it, does the regression correlates to the introduction of the wasm builds? @eyebrowsoffire

**Comment by zanderso** [comment]
> Actually thinking a bit more about it, does the regression correlates to the introduction of the wasm builds? @eyebrowsoffire

See my comments above. Non-goma-enabled builds need to run on large Linux instances. The configurations that are running `wasm_release` builds need to be on `e2-standard-32` or larger.

**Comment by eyebrowsoffire** [comment]
We have added a few more wasm targets recently (skwasm and the
chromium-optimized version of canvaskit) so a build time regression is
expected.

**Comment by godofredoc** [comment]
There was a bug in the build_util module that was forcing all builds to go through the goma path and using `-j 200`. I'm fixing that but that probably means that providing bigger `-j` won't have a lot of impact.

**Comment by eyebrowsoffire** [comment]
In general it would be nice if we could figure out a story for using goma
with emscripten. Unfortunately my knowledge of goma is very limited.

- Jackson

**Comment by godofredoc** [comment]
For engine/engine.py the `-j 200` is coming from here https://cs.opensource.google/flutter/recipes/+/master:recipes/engine/engine.py;l=121 and a global default setting goma_jobs to 200.

Not sure if it is worthy investing on fixing those issues in that recipe when we will be ready to deprecate it in < 1 month. @zanderso what do you think?

**Comment by eyebrowsoffire** [comment]
To be honest, we might actually be able to remove the web engine build from
the `engine.py` recipe right now, since the v2 web engine recipe now builds
and uploads the artifacts. The tricky part is the Linux Web Framework tests
specifically, it does an entirely separate build of the web engine so that
it can point the flutter tool at it. I've been working on getting the
engine unit tests working with v2 recipes, but to be honest I haven't even
started thinking about what it's going to take to convert the framework
tests. So I'm not sure how close we are on that end of things.

- Jackson

**Comment by godofredoc** [comment]
Here is a build for wasm going through the no_goma path and setting the correct -j value. https://chromium-swarm.appspot.com/task?id=60e0f473f1c2ab10

**Comment by zanderso** [comment]
I think I don't entirely understand the question for me, but overall, we should fix the current P2 issue of the CI cycle time being pushed up by the slow `wasm_release` build. We should not be leaving them like this for ~1 month.

**Comment by godofredoc** [comment]
The relevant fix for the slow releases is to move those 3 builds to 32 machines the `-j` value is not providing any improvements.

The question was about fixing the inconsistent use of goma in engine/engine.py that requires several hours of investment and will be deprecated in ~1 month.

**Comment by zanderso** [comment]
If the inconsistent use of -j is not currently causing any problems, then I'm fine with leaving it as it is.

**Comment by godofredoc** [comment]
ok, here is part1 out of 3: https://flutter-review.googlesource.com/c/recipes/+/40160

**Comment by eyebrowsoffire** [comment]
My suggestion to just bypass this issue for now is to (1) just remove the
web build from engine.py:
https://flutter-review.googlesource.com/c/recipes/+/40160 and (2) add the
`no_goma` property to the Web Framework builder:
https://github.com/flutter/engine/pull/40197

- Jackson
