### ISSUE TITLE
Sample code is using a non-standard copy content icon.

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#122246]
## expected result
https://fonts.google.com/icons?selected=Material+Symbols+Outlined:content_copy:FILL@0;wght@400;GRAD@0;opsz@48

## observed result
<img width="704" alt="Screenshot 2023-03-08 at 3 30 26 PM" src="https://user-images.githubusercontent.com/30870216/223876418-2470c4c5-abfc-4511-9762-1fd0b6e05903.png">

**Comment by goderbauer** [comment]
@gspencergoog Do we control the icon that shows up there or is that dart doc?
