### ISSUE TITLE
[Impeller] On iOS, make Impeller on by default with an opt-out.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#122223]
Deprecate the [`--enable-impeller` flag and `FLTEnableImpeller` plist key](https://github.com/flutter/engine/blob/431df2e9a8c1a3501044b6c20f455ae3ccd11ef8/impeller/README.md#try-impeller-in-flutter). Replace them with `--disable-impeller` and `FLTDisableImpeller` key.

**Comment by chinmaygarde** [comment]
Tracks capping out the [Impeller on iOS milestone](https://github.com/orgs/flutter/projects/21/views/12).

**Comment by jonahwilliams** [comment]
We also need to update the google3 infra to always specify FLTImpellerEnabled to true or false, so that we can update the default independently there and not deal with it in a roll. FYI @chingjun

**Comment by zanderso** [comment]
A few performance issues were discovered by the temporary devicelab benchmark flag flip:
- [ ] https://github.com/flutter/flutter/issues/122408
- [ ] https://github.com/flutter/flutter/issues/122406
- [ ] https://github.com/flutter/flutter/issues/122405

These aren't necessarily blockers, and given that all tests ran without errors, we should attempt landing the flag-flip in the engine after the g3 infra issue is sorted out.

**Comment by jonahwilliams** [comment]
g3 infra changes have landed as of CL/515454075 (Thanks @chingjun !)

**Comment by chinmaygarde** [comment]
@zanderso May I close this as done?

**Comment by jonahwilliams** [comment]
It is done!

**Comment by zanderso** [comment]
Yes.

**Comment by chinmaygarde** [comment]
Closing the loop here since this issue got attention. IIRC, this was completed after the [provisional flip of the flag in this patch stuck its landing](https://github.com/flutter/engine/pull/40405). Is that right @zanderso @jonahwilliams? Please correct me if I am mistaken 🙏.

**Comment by jonahwilliams** [comment]
Correct
