### ISSUE TITLE
fresh flutter app is 129 mb

### ISSUE THREAD

**Issue by taymiyyah** [flutter/flutter#122221]
creating fresh flutter app on android studio  is 129 MB

**Comment by bernaferrari** [comment]
That's fine. When releasing you are going to use app bundle which reduces the code size.

**Comment by elsamuko** [comment]
Can you post the output of 
```bash
flutter create test
cd test
flutter build appbundle
```

It should say sth like
```bash
✓ Built build/app/outputs/bundle/release/app-release.aab (16.8MB).
```
at the end.

**Comment by darshankawar** [comment]
Closing as this not an issue and WAI. You may read about app size here for further reference: https://docs.flutter.dev/perf/app-size
