### ISSUE TITLE
M3 Button MaterialStateProperty defaults don't resolve MaterialState.pressed

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#122250]
Many of the MaterialStateProperty defaults for the Button classes are defined like the example from ElevatedButton below. The MaterialState.pressed and MaterialState.hovered states are always reported together, so the resolved color is always the hovered one, since that clause is first.  The order should be pressed then hovered, since hovered can occur without pressed.

```dart
  MaterialStateProperty<Color?>? get overlayColor =>
    MaterialStateProperty.resolveWith((Set<MaterialState> states) {
      if (states.contains(MaterialState.hovered)) {
        return _colors.primary.withOpacity(0.08);
      }
      if (states.contains(MaterialState.focused)) {
        return _colors.primary.withOpacity(0.12);
      }
      if (states.contains(MaterialState.pressed)) {
        return _colors.primary.withOpacity(0.12);
      }
      return null;
    });
```

**Comment by HansMuller** [comment]
CC @gspencergoog @QuncCccccc @guidezpl @esouthren

**Comment by gspencergoog** [comment]
I agree with your assessment here: it needs to be ordered differently. I also wonder if we should investigate returning a blended color when there is more than one state enabled. If my hovered color was bluish and my pressed color was reddish, I might expect that the when I was pressing the button, the color would be a magenta-ish blend of the two, since both states are active.

**Comment by guidezpl** [comment]
The order we've been using is disabled, pressed, hovered, focused.

> I also wonder if we should investigate returning a blended color when there is more than one state enabled.
 It's not a bad idea, but since color defaults are fully defined through tokens it wouldn't currently be feasible.

**Comment by HansMuller** [comment]
> The order we've been using is disabled, pressed, hovered, focused.

That sounds like the correct default order to me.

**Comment by gspencergoog** [comment]
> It's not a bad idea, but since color defaults are fully defined through tokens, it wouldn't currently be feasible.

Why not?  At least in Flutter, we can definitely do it:

```dart
  MaterialStateProperty<Color?>? get overlayColor =>
    MaterialStateProperty.resolveWith((Set<MaterialState> states) {
      Color? color;
      if (states.contains(MaterialState.hovered)) {
        color = Colors.alphaBlend(_colors.primary.withOpacity(0.08), color ?? Colors.transparent);
      }
      if (states.contains(MaterialState.focused)) {
        color = Colors.alphaBlend(_colors.primary.withOpacity(0.12), color ?? Colors.transparent);
      }
      if (states.contains(MaterialState.pressed)) {
        color = Colors.alphaBlend(_colors.primary.withOpacity(0.12), color ?? Colors.transparent);
      }
      return color;
    });
```

**Comment by gspencergoog** [comment]
Or do you just meant that the opacities, etc., in the tokens were designed to not be blended?

**Comment by guidezpl** [comment]
As far as I know, the color and opacity tokens aren't meant to be blended together
