### ISSUE TITLE
Update `flutter/test/material` to no longer use `TestWindow`

### ISSUE THREAD

**Issue by pdblasi-google** [flutter/flutter#122240]
There are currently 60 references in `flutter/test/material` that make use of `TestWindow` properties, these should be updated to use `TestFlutterView` and `TestPlatformDispatcher` as appropriate for the use cases.

* `app_test.dart` has 2 references
* `date_picker_test.dart` has 6 references
* `drawer_test.dart` has 6 references
* `dropdown_test.dart` has 4 references
* `navigation_drawer_test.dart` has 3 references
* `page_test.dart` has 7 references
* `scrollbar_test.dart` has 1 reference
* `text_field_test.dart` has 3 references
* `text_selection_test.dart` has 8 references
* `time_picker_test.dart` has 20 references

**Comment by yaakovschectman** [comment]
Reopened by revert https://github.com/flutter/flutter/pull/122636
