### ISSUE TITLE
Release candidate branches showing pending builds forever

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#122235]
This happens when builders are removed from master but they are still present in release candidate branches.

The current scheduler implementation checks only the branch under test to determine what to run. One potential improvement is to make the scheduler read both the main ToT .ci.yaml and the branch under test, remove all the builds in the release candidate branch that do not exist anymore in main.

**Comment by XilaiZhang** [comment]
de-dup against infra ticket queue

**Comment by godofredoc** [comment]
No, this bug is for the long term fix.
