### ISSUE TITLE
google_maps_flutter bug on pop

### ISSUE THREAD

**Issue by NikosTsesmelis** [flutter/flutter#122397]
Google maps leaves a weird afterimage when you pop a screen in Android.

[✓] Flutter (Channel stable, 3.7.7, on macOS 13.1 22C65 darwin-arm64, locale en-GR)
    • Flutter version 3.7.7 on channel stable at /Users/nikostsesmelis/Tools/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (2 days ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

```
class TestScreen extends StatefulWidget {
  const TestScreen({Key? key}) : super(key: key);

  @override
  _TestScreenState createState() => _TestScreenState();
}

class _TestScreenState extends State<TestScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        children: [
          const Padding(
            padding: EdgeInsets.symmetric(horizontal: 32, vertical: 200),
            child: GoogleMap(
              initialCameraPosition: CameraPosition(
                target: LatLng(37.42796133580664, -122.085749655962),
                zoom: 14.4746,
              ),
            ),
          ),
          Align(
            alignment: Alignment.bottomCenter,
            child: Padding(
              padding: const EdgeInsets.only(bottom: 24),
              child: MaterialButton(
                color: Colors.blue,
                onPressed: _nextScreen,
                child: const Text("Open"),
              ),
            ),
          ),
        ],
      ),
    );
  }

  void _nextScreen() {
    Navigator.push(context, MaterialPageRoute(builder: (context) => const TestScreen()));
  }
}
```

**Comment by huycozy** [comment]
Hi @NikosTsesmelis 
Which `google_maps_flutter ` version are you using? Please also provide the `Steps to reproduce` along with `Actual result` so that we may verify the issue properly.

**Comment by NikosTsesmelis** [comment]
google_maps_flutter: 2.2.5

You need to press the button to navigate on a new screen and then hit the android back button.

Tested on pixel 4a(android 13)

https://user-images.githubusercontent.com/100851392/224644631-21a3bb1d-d24c-4bd7-8aa1-05b37da9b49c.mp4

**Comment by NikosTsesmelis** [comment]
New info. I see that appling opacity over the map is not working. So could the rest of the screen fade away but the map stays painted fully for the whole duration?

**Comment by huycozy** [comment]
As I can see in your video, it seems to be working fine. You are popping a screen that is rendered similar to the previous one. Maybe this is just an optical effect?

**Comment by NikosTsesmelis** [comment]
It just makes it harder to see because the screens both have a map. It happens on our app no matter where in the screen the map is. The map persists i believe for the duration of the transition animation. I believe that the opacity is not applied to the map and has that effect.

https://user-images.githubusercontent.com/100851392/224707378-3bb4f34d-fc80-4395-8e17-26235c78da1d.mp4

**Comment by huycozy** [comment]
This sounds like a platform-view issue on navigating. I see there's an open issue addressing the case you described #113167 which has been reported recently.

Closing this issue in favor of #113167, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!

**Comment by NikosTsesmelis** [comment]
I'm sorry but I don't believe this is the same issue. What is described on the other issue is when pushing a screen from the map screen. I am describing the issue of possibly the opacity not applied on the map when the map screen fades out.

**Comment by huycozy** [comment]
Thanks for your response. I re-open the issue for further discussion. 

I remember, there was an open issue similar to what you described https://github.com/flutter/flutter/issues/118498 (I checked it). Please take a look at https://github.com/flutter/flutter/issues/118498#issuecomment-1384797734, it looks better on Flutter 3.3.10. Can you please retry on Flutter 3.3.10 and confirm it works as expected? If so, that's the issue you should follow up, not https://github.com/flutter/flutter/issues/113167 :).

**Comment by NikosTsesmelis** [comment]
thanks that seems to be the same issue. I will follow that one.
