### ISSUE TITLE
There should be a PageTransformer for having various effects when PageView's pages are switched

### ISSUE THREAD

**Issue by roughike** [flutter/flutter#12234]
Could be slightly related to #8103.

Android has a notion of [PageTransformers](https://developer.android.com/training/animation/screen-slide.html#pagetransformer) (see under "Customize the Animation with PageTransformer" section). `PageTransformers` allow the developer to customize animations on Android's equivalent of PageViews, `ViewPagers`.

Here's a sample what kinds of effects developers usually want to do:

![PageTransformer sample.](https://github.com/FlutterRocks/page-transformer/raw/master/page_transform_sample.gif)

**Comment by roughike** [comment]
I needed a way to do this so I implemented a [PageTransformer class in Flutter](https://github.com/FlutterRocks/page-transformer/blob/master/lib/page_transformer.dart) myself. 

The API currently looks like this:

**page_transformer_sample.dart**

```dart
new PageTransformer(
  pageViewBuilder: (context, pageVisibilityResolver) {
    return new PageView.builder(
      itemBuilder: (context, index) {
        final pageVisibility =
            pageVisibilityResolver.resolvePageVisibility(index);

        // position is exactly the same than in PagerTransformer on Android: 
        // if the page is completely hidden on the left, it's -1.0. If the page is
        // completely hidden on the right, it's 1.0. If the page is currently in the
        // view, on a "non-dragging" state, it's 0.0. So it can be anything between -1.0 and 1.0.
        final position = pageVisibility.pagePosition;

        // visibleFraction is how much of the page is currently visible, between 0.0 - 1.0.
        // I found this convenient when I wanted to do simple things like scale or opacity animations
        // so that calculating the visible fraction myself would've been annoying.
        final visibleFraction = pageVisibility.visibleFraction;

        return new Transform(new Card(...));
      },
    );
  },
);
```

If you feel this is a good way of doing it, I'll be happy to document things better and **hit you with a PR**. 

@sethladd proposed that I should make this as a library on Pub, but speaking from experience, I don't want to go that way. It would be nice to have this officially supported instead.

**Comment by Hixie** [comment]
You can do this today. When you create the PageView, make sure you pass it a PageController. Then, inside the PageView, use an AnimatedBuilder, passing it the PageController as the animation, then in the builder, use the PageController's `page` value. You'll have to tweak the value a bit to get it into the range you want, but that should be easy enough.

**Comment by roughike** [comment]
I'll check that out and see if I should update my article and sample app to use that way instead.

Thanks!
