### ISSUE TITLE
shortcuts to support XButton1 and XButton2

### ISSUE THREAD

**Issue by Zereef** [flutter/flutter#122356]
## Use case

```
shortcuts: const <ShortcutActivator, Intent>{
    SingleActivator(LogicalKeyboardKey.XButton1): IncrementIntent(),
},
```

## Proposal

XButton1 (4th mouse button. Typically performs the same function as Browser_Back.)
XButton2 (5th mouse button. Typically performs the same function as Browser_Forward.)

those be added as possible things to click for shortcuts

**Comment by Zereef** [comment]
explaining better i wanna be able to use the side buttons in my mouse as shortcuts

**Comment by darshankawar** [comment]
@Zereef 
Can you check if [this](https://github.com/flutter/flutter/issues/115641) open proposal resembles your case ?

**Comment by darshankawar** [comment]
Please follow-up in the linked issue for further updates. Closing this as a duplicate.
