### ISSUE TITLE
Auto release memory inside isolate while running

### ISSUE THREAD

**Issue by ngminhduong** [flutter/flutter#122377]
## Use case
I want keep instance isolate and use it when the app running instead of continuously spawn and kill because:
1. Reduce the cost to create isolate.
2. In my case I use https://pub.dev/packages/reflectable package and I want run it in a isolate so that I need call initializeReflectable() only one in a isolate and reuse it.
My solution:
I build a class to create isolate, call initializeReflectable() in this isolate  and keep this keep this instance.
``` dart


import 'dart:async';
import 'dart:isolate';
import 'package:flutter/foundation.dart';
import 'package:isolate_leak_2/database_reflect.dart';

class FSTypeMirror {
  Type dynamicReflectedType;
  String simpleName;
  FSTypeMirror(this.dynamicReflectedType, this.simpleName);
}

class GetAllClassCrossIsolatesMessage {
  final SendPort? sender;
  final SendPort? errorPort;
  GetAllClassCrossIsolatesMessage({required SendPort this.errorPort, required SendPort this.sender});
}

class DBIsolate<Q, R> {
  late SendPort _isolateSendPort;
  bool _isInitialized = false;
  VoidCallback initializer;
  ComputeCallback<Q?, R> handler;
  Isolate? _isolate;
  final ReceivePort resultPort = ReceivePort();

  DBIsolate(this.handler, this.initializer);

  void kill() {
    resultPort.close();
    _isolate?.kill();
  }

  Future<void> initialize() async {
    if (this._isInitialized) {
      return Future<void>.value(null);
    } else {
      _isolate = await Isolate.spawn<_IsolateConfiguration<Q?, FutureOr<R>>>(
        _spawn,
        _IsolateConfiguration<Q?, FutureOr<R>>(
            this.handler,
            null,
            this.initializer,
            resultPort.sendPort
        ),
        errorsAreFatal: false,
      );
      this._isolateSendPort = await resultPort.first;
      this._isInitialized = true;
    }
  }

  Future<List<FSTypeMirror>> getAllClasses() {
    var completer = Completer<List<FSTypeMirror>>();
    ReceivePort port = ReceivePort();
    ReceivePort errorPort = ReceivePort();
    this._isolateSendPort.send(GetAllClassCrossIsolatesMessage(
        errorPort: errorPort.sendPort,
        sender: port.sendPort));
    port.listen((message) {
      completer.complete(message);
    });
    errorPort.listen((error) {
      completer.completeError(error);
    });
    return completer.future;
  }
}

Future<void> _spawn<Q, R>(_IsolateConfiguration<Q, FutureOr<R>> configuration) async {
  configuration.initializer();

  var ourReceivePort = ReceivePort();

  configuration.resultPort.send(ourReceivePort.sendPort);
  ourReceivePort.listen((msg) async {
    if (msg is GetAllClassCrossIsolatesMessage) {
      try {
        var clazzes = dbReflectable.annotatedClasses.map((e) => FSTypeMirror(e.dynamicReflectedType, e.simpleName)).toList();
        msg.sender!.send(clazzes);
      } catch (e) {
        msg.errorPort!.send(e);
      }
    }
  });
}

@immutable
class _IsolateConfiguration<Q, R> {
  const _IsolateConfiguration(
      this.callback,
      this.message,
      this.initializer,
      this.resultPort,
      );
  final ComputeCallback<Q, R> callback;
  final Q message;
  final VoidCallback initializer;
  final SendPort resultPort;
}
typedef ComputeCallback<Q, R> = FutureOr<R> Function(Q message);

```
Everything work fine with me but I have an issue. The memory continues to increase while running.
I found the root cause of this issue is because I don't kill the isolate.

Please check memory timeline:
<img width="1023" alt="Screen Shot 2023-03-10 at 3 35 31 PM" src="https://user-images.githubusercontent.com/5801114/224267334-070b56f6-d778-4cdc-ba17-3fb7f67fcd8b.png">

## Proposal

Do you have any solution to release memory without kill the isolate

I also attach example. Please help to check

[isolate.zip](https://github.com/flutter/flutter/files/10940189/isolate.zip)

**Comment by darshankawar** [comment]
@ngminhduong 
This issue looks similar to the one you reported earlier: https://github.com/flutter/flutter/issues/98856 which had comments from Flutter team on what to do. Is this case different from it ?

Also, you raised use case / proposal, but it looks like you are looking for a solution rather than proposing one.
If you are looking for a solution, support channels like StackOverflow is better suited for this issue.

**Comment by bernaferrari** [comment]
This is probably more suitable for Dart sdk than Flutter.

**Comment by ngminhduong** [comment]
Hi @darshankawar 

After diving deep into this issue from ticket https://github.com/flutter/flutter/issues/98856, I found the root cause of the problem. The issue is not related to a memory leak. It is related to how the isolate works. The isolate doesn't release memory until we close all ports and kill the isolate.

Therefore, I created a new thread for further discussion because the old thread was closed.

I think my approach makes sense because it could help to improve the app's performance significantly. Instead of continuing to spawn new isolates, we should have a solution to reuse them.

Please review my request and think about it.

**Comment by darshankawar** [comment]
@ngminhduong 
I think this request is better suited for dart-lang repo, so please open this issue in that repo: https://github.com/dart-lang/sdk/issues
If you get directed here, write in comments and I'll reopen it.
