### ISSUE TITLE
Expand deprecation policy to package:flutter_test

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#122323]
This is the tracking issue for the proposal to expand the deprecation policy to package:flutter_test

When first introduced, we decided to first focus the application of the deprecation policy on just the flutter package. During that time we worked on the process and gathered feedback from users. This process has become pretty stable, and so we are looking to expand it to other packages, with the first being flutter_test.

This will involve:

- [x] adding dart fix support to flutter_test
  - #123154
- [x] advance communication to users and a feedback period
  - https://groups.google.com/g/flutter-announce/c/nwVUWwsX_mM
- [x] deprecation notice formatting enforcement
- [ ] updating the deprecation policy on the wiki and website to list enforced packages 

If we were to do this after the *_next_* release (not the current round that completed with https://github.com/flutter/flutter/issues/119580 but the next round), these would be up for removal:

class / method | property | deprecated in
-- | -- | --
AnimationSheetBuilder | display | 2.3
AnimationSheetBuilder | sheetSize | 2.3
TestWidgetsFlutterBinding | addTime | 2.6
TestWidgetsFlutterBinding | runAsync | 2.6
TestWidgetsFlutterBinding.runTest | timeout | 2.6
AutomatedTestWidgetsFlutterBinding.runTest | timeout | 2.6
LiveTestWidgetsFlutterBinding.runTest | timeout | 2.6
testWidgets | initialTimeout | 2.6

cc @goderbauer @pdblasi-google

**Comment by gslender** [comment]
Is the appropriate place to raise issues with depreciation of methods and classes (in the test package) that are still needed because no equivalent method or class exists?

**Comment by Piinks** [comment]
> Is this appropriate place to raise issues with depreciation of methods and classes that are still needed because no equivalent method or class exists?

Definitely! I think all of the listed APIs have migration paths, but if we are missing one we certainly would love to know!

**Comment by workerbee22** [comment]
If we are extending to `flutter_test` would you consider also `integration_test` (now also part of the framework)? Then all core testing components covered 🤔

**Comment by Piinks** [comment]
> If we are extending to flutter_test would you consider also integration_test (now also part of the framework)?

Great question! The long term goal is to expand the policy to cover all packages in flutter/flutter, and maybe even `dart:ui`. 🙂 

We're just doing this at a considerate pace since it means more potential braking changes for developers.

**Comment by pdblasi-google** [comment]
@Piinks I added a link to a ticket for adding dart fix support to the description. I plan on starting on it in the next couple weeks, hopefully early next week.

**Comment by Piinks** [comment]
Closing this as we are about to proceed with the next batch of deprecations, including flutter_test. Follow along in https://github.com/flutter/flutter/issues/127042
