### ISSUE TITLE
[Impeller] Document the GPU Compute arc of work.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#122310]
This is just a stub issue for documenting the use-cases we are looking to tackle using GPU Compute. So far, due to minimum version restrictions, we haven't really looked into using this as much as we could even though the infrastructure to use GPU Compute has been built out.

**Comment by chinmaygarde** [comment]
cc @dnfield. From the item discussed in the weekly sync.

**Comment by jonahwilliams** [comment]
The end of the arc is that we didn't find a good use for compute
