### ISSUE TITLE
Flutter callery code ?

### ISSUE THREAD

**Issue by mandata5010** [flutter/flutter#122495]
I'm a beginner, I'm trying to copy the Flutter Callery code, but I can't get the copied code to work ? I have acted so that I remove the underlying code and copy the Callery code! Why doesn't the code work, do I need to add some additional information? I would like to study the code and thus learn more?

**Comment by Radiant690** [comment]
@mandata5010 it would be great if you could provide the code sample and logs generated.

Regarding the Flutter Gallery code, it is possible that the code you copied has dependencies that are not included in your project. In this case, you may need to add the necessary dependencies to your project for the code to work as expected.

Another possibility is that the code you copied may require additional configuration settings or environment variables that are not present in your project.

**Comment by mandata5010** [comment]
This is the "new flutter" base code created by Flutter and this seems to work. When I want to try Flutter caller's codes, they don't work? I'll put the flutter gallery's "Material" button code below? It doesn't work, is it missing some basic functions? What log data do you mean, where can I get it?   The most important thing would be for me to understand how those gallery codes can be used as help??? 

**This Flutter new project basic code works!**

import 'package:flutter/material.dart';
void main() {
  runApp(const MyApp());
}
class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}
class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'Sinä olet painanut NAPPIA näin monta kertaa:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

**This is a button code copied from the gallery and it doesn't work???**

// Copyright 2019 The Flutter team. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter/material.dart';
import 'package:flutter_gen/gen_l10n/gallery_localizations.dart';
import 'package:gallery/demos/material/material_demo_types.dart';

class _TextButtonDemo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final localizations = GalleryLocalizations.of(context)!;
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            TextButton(
              onPressed: () {},
              child: Text(localizations.buttonText),
            ),
            const SizedBox(width: 12),
            TextButton.icon(
              icon: const Icon(Icons.add, size: 18),
              label: Text(localizations.buttonText),
              onPressed: () {},
            ),
          ],
        ),
        const SizedBox(height: 12),
        // Disabled buttons
        Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            TextButton(
              onPressed: null,
              child: Text(localizations.buttonText),
            ),
            const SizedBox(width: 12),
            TextButton.icon(
              icon: const Icon(Icons.add, size: 18),
              label: Text(localizations.buttonText),
              onPressed: null,
            ),
          ],
        ),
      ],
    );
  }
}

**Comment by danagbemava-nc** [comment]
Hi @mandata5010, you can't just copy the code from the flutter gallery code sample and expect it to work in the default counter app. The flutter gallery code sample contains dependencies and other code that is necessary for the code to work. 
If you want to understand how the gallery code works, your best bet is to clone the repo and play around with it locally on your system. From there you can see how to apply what you've learnt in your projects. 

Closing as this is not a flutter issue.

Thank you
