### ISSUE TITLE
[ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(97)] Could not make the context current to destroy the GrDirectContext resources.

### ISSUE THREAD

**Issue by siw0oo0** [flutter/flutter#122479]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

...

### Actual results

[ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(97)] Could not make the context current to destroy the GrDirectContext resources.

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by siw0oo0** [comment]
How can I do..?

**Comment by darshankawar** [comment]
@siw0oo0 
In order to properly address this issue, please provide `flutter doctor -v`, a minimal code sample that shows the reported error along with steps to replicate.
