### ISSUE TITLE
Plugins tests are not cleaning up created iOS simulators

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#122416]
On [this plugin test](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8787351356520040209/+/u/Run_package_tests/list_simulators/stdout) I can see there's 110 Flutter-iPhone simulators, some still booted before the tests run https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8787351356520040209/+/u/Run_package_tests/list_simulators/stdout. That could cause issues like running out of disk space.

The plugins tests should try to delete any simulators they have added.

Also a good idea to add `api.os_utils.shutdown_simulators()` to the recipe so at least they aren't booted:
https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/devicelab/devicelab_drone.py#203

**Comment by jmagman** [comment]
cc @stuartmorgan @yusuf-goog

**Comment by stuartmorgan** [comment]
Looks like those are coming from https://github.com/flutter/packages/blob/main/.ci/scripts/create_simulator.sh, which was ported over from the Cirrus script. Probably we were getting a clean VM every time from Cirrus so it wasn't an issue that we didn't clean up.

Can we just delete it by name, or do we need to keep some state across script steps?

**Comment by stuartmorgan** [comment]
I'll see if I can figure out the right commands to shut down and delete the created simulator.
