### ISSUE TITLE
Cannot load dynamic lib first time download from google!

### ISSUE THREAD

**Issue by eav-solution** [flutter/flutter#122465]
Hello all,
I can run normally in debug mode.
But first time I download it from ch play, it's show this error.
After that, I close app and run again, it's work normally.

So I cannot run app normally in first time I download from google play.

![Screenshot 2023-03-11 223958](https://user-images.githubusercontent.com/88574969/224493693-748c1459-8bb7-49ee-9433-1980956d548f.png)

**Comment by iapicca** [comment]
@eav-solution 
could you provide a runnable code sample?
here is a possible solution
- https://github.com/flutter/flutter/issues/73318#issuecomment-754598119
