### ISSUE TITLE
Error: Unable to find git in your PATH.

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#122461]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

flutter upgrade
Error: Unable to find git in your PATH.
(base) PS C:\Users\god> git

### Actual results

I have git

<img width="554" alt="image" src="https://user-images.githubusercontent.com/21303438/224477795-f6dfd421-a5d9-47b7-8b92-b1579cf15933.png">

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

Unable to run any flutte rcomand.

**Comment by flexagoon** [comment]
Please provide the logs and the `flutter doctor` output.

**Comment by flexagoon** [comment]
Please provide the output of a flutter command that fails with the `--verbose` flag

**Comment by darshankawar** [comment]
@jinfagang 
As mentioned above, please provide verbose log. Does this error started occuring after `flutter upgrade` only or before it too ?
Also check if you have properly set the flutter root variable.
