### ISSUE TITLE
Flutter roll broke then framework tree

### ISSUE THREAD

**Issue by flar** [flutter/flutter#122456]
Flutter PR: https://github.com/flutter/flutter/pull/122430

Failures in most of the Linux web tests:

- https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_benchmarks_canvaskit/10748/overview
- https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_long_running_tests_1_5/9340/overview
- https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_long_running_tests_3_5/9304/overview
- https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_long_running_tests_4_5/9306/overview
- https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_long_running_tests_5_5/9349/overview

**Comment by flar** [comment]
Revert PR: https://github.com/flutter/flutter/pull/122455

**Comment by jason-simmons** [comment]
Reproduced the hang in `web_benchmarks_canvaskit` locally and found that it started with https://github.com/flutter/engine/pull/40194

That PR has already been reverted (https://github.com/flutter/engine/pull/40235).  It was also causing errors when running web apps with the `--local-engine` flag.

**Comment by flar** [comment]
The engine roll has rolled the framework tree is green.
