### ISSUE TITLE
[CP] Remove obsolete builders.

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#122413]
### issue_link

https://github.com/flutter/flutter/issues/122204

### Commit Hash

36446d82542a1ccdf608115dbd50043607826039

### Target

beta

### pr_link

https://github.com/flutter/engine/pull/40225

### Impacted Users

release engineering team

### Impact Description

Builds showing up as pending forever in stable and beta branches.

### Workaround

N/A

### Risk

low

### Test Coverage

yes

### Validation Steps

Validated presubmit tests are passing correctly.

**Comment by XilaiZhang** [comment]
Closing after merge.
