### ISSUE TITLE
[Impeller] Implement our own allocators on the Metal backend.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#122464]
* These take real memory, according to xcode memory profiling. We allocate one for each subpass. 
* This partially explains why we spend so much time in texture allocation, since these are created from scratch per frame.
* Experimentally, I can trigger OOM in wonderous on iPhone 7 even after image sizes are fixed. Removing one or two of the subpasses caused by color filters makes it nearly impossible to trigger this OOM.

This is likely a cause for https://github.com/flutter/flutter/issues/122406

**Comment by chinmaygarde** [comment]
IMO, instead of texture recycling, we need our own allocators (similar to Vulkan) backend by `MTLHeap`.

**Comment by chinmaygarde** [comment]
What we have is working well enough for Metal right? Do we still need this? Vulkan is a whole different story admittedly.

**Comment by jonahwilliams** [comment]
I've experimented a bit with building our own VMA like suballocators using MTLHeap. Seems promising but also doens't seem to be a bottleneck in the workloads we are currently measuring. Lets keep this around at a low priority?

**Comment by chinmaygarde** [comment]
Sounds good.

**Comment by chinmaygarde** [comment]
I don't think we are going to attempt doing this anytime soon.
