### ISSUE TITLE
Stuck on I/flutter (20447): The Dart VM service is listening on ***** on IQOO Z5 5G [android 13] as in issue #82520

### ISSUE THREAD

**Issue by Nktech-Official** [flutter/flutter#122487]
output of `flutter doctor -v`
[l.log](https://github.com/flutter/flutter/files/10950129/l.log)

output of  `flutter run -v`
[log.log](https://github.com/flutter/flutter/files/10950133/log.log)

as mentioned in the issue   #82520 some devs have solved this with the android 12 update on fontouch os but this error still happening on android 12 (Fountouch Os 13) please. 
did not used any thrid party module just `flutter create myapp --org com.my_domain`

Operating System
 OS: Ubuntu 22.10 x86_64 
 Kernel: 5.19.0-35-generic 

output of `neofetch`
<details>
 <summary> 
</summary>
 
  ```log


            .-/+oossssoo+/-.               nktech@hackerbook 
        `:+ssssssssssssssssss+:`           ----------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 22.10 x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: VivoBook_ASUSLaptop X412FAC_X412FA 1.0 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.19.0-35-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 3 hours, 59 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 3104 (dpkg), 36 (flatpak), 11 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: zsh 5.9 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1920x1080 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: Unity 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Dracula-shell-v40 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Yaru-blue-dark [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: Yaru-blue-dark [GTK2/3] 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: vscode 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: Intel i3-10110U (4) @ 4.100GHz 
    .ossssssssssssssssssdMMMNysssso.       GPU: Intel CometLake-U GT2 [UHD Graphics] 
      -+sssssssssssssssssyyyssss+-         Memory: 3164MiB / 3775MiB 

```
</details>

**Comment by danagbemava-nc** [comment]
Hi @Nktech-Official, this is an issue with vivo devices and not something the flutter team can fix. See https://github.com/flutter/flutter/issues/117019 for a similar report of this issue.

Closing this based on https://github.com/flutter/flutter/issues/117019#issuecomment-1353683329. 

Thank you
