### ISSUE TITLE
Concurrent build via windows power shell still not working

### ISSUE THREAD

**Issue by alex9153** [flutter/flutter#122491]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Run at the same time
flutter run -d chrom
flutter run -d edge

### Actual results

Failed to clean up asset directory build\flutter_assets: FileSystemException: Deletion failed, path =
'build\flutter_assets' (OS Error: Папка не пуста.
, errno = 145)
To clean build artifacts, use the command "flutter clean".
Flutter failed to open a file at "build\flutter_assets\resources/icons/._play_battle.png". The flutter tool cannot
access the file or directory.
Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current
user.

### Flutter Doctor output

[flutter] flutter doctor -v
[√] Flutter (Channel stable, 3.7.5, on Microsoft Windows [Version 10.0.22621.1344], locale ru-RU)
    • Flutter version 3.7.5 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c07f788888 (2 weeks ago), 2023-02-22 17:52:33 -0600
    • Engine revision 0f359063c4
    • Dart version 2.19.2
    • DevTools version 2.20.1

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\\Android\sdk
    • Platform android-33-ext4, build-tools 33.0.2
    • Java binary at: C:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33403.182
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] VS Code (version 1.75.1)
    • VS Code at C:\Users\Aleks\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.60.0

[√] Connected device (4 available)
    • SM T970 (mobile)  • 192.168.1.34:45689 • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.22621.1344]
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 110.0.5481.180
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 110.0.1587.69

[√] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by huycozy** [comment]
Hi @alex9153 
I see there's an open issue addressing the case you described #70216. There could be some external reasons causing this issue (project located at Google Drive https://github.com/flutter/flutter/issues/70216#issuecomment-921082171 or windows antivirus https://github.com/flutter/flutter/issues/70216#issuecomment-921775624, etc). You can also check other comments and try them as well.

Closing this issue as a duplicate, so please follow up on it for further updates. Thank you!
