### ISSUE TITLE
Wire up malioc to run on .spv shaders

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#122417]
Right now we only run malioc on shaders that compile to GLES. For the SSBO gradients, and potentially future shaders, we can get analysis by running over the generated spv.

**Comment by jonahwilliams** [comment]
We should potentially run malioc over all .spv shaders, since the gles and spv second stage will be different.

**Comment by jonahwilliams** [comment]
@zanderso I believe this is done now?

**Comment by zanderso** [comment]
Yeah, the analysis will happen if the target GPU supports the GLES or Vulkan version that the `impeller_shaders` target declares, like here: https://github.com/flutter/engine/blob/main/impeller/entity/BUILD.gn#L91.
