### ISSUE TITLE
[Material 3] : Proposal to customize Switch's track outline width

### ISSUE THREAD

**Issue by MrHBS** [flutter/flutter#122451]
I can't seem to find a way to change the switch's track outline width.

**Comment by darshankawar** [comment]
@MrHBS 
Are you referring to the outline width which is currently set as 2dp ?

<img width="950" alt="Screenshot 2023-03-13 at 2 02 50 PM" src="https://user-images.githubusercontent.com/67046386/224647982-ef694266-0e0a-48e8-a7c5-649a937b389b.png">

If so, can you provide us your use case using Switch to know what are you trying to achieve ?

**Comment by darshankawar** [comment]
Thanks for the feedback. Treating this as a proposal.
