### ISSUE TITLE
[Android TV] A KeyUpEvent is dispatched, but the state shows that the physical key is pressed on a different logical key

### ISSUE THREAD

**Issue by rounce** [flutter/flutter#122492]
## Steps to Reproduce

1. Execute `flutter run` on any code sample (https://github.com/flutter/samples/tree/main/provider_counter for example)
2. Press middle key (select)
3. 
```
_AssertionError ('package:flutter/src/services/hardware_keyboard.dart': Failed assertion: line 437 pos 16: '_pressedKeys[event.physicalKey] == event.logicalKey': A KeyUpEvent is dispatched, but the state shows that the physical key is pressed on a different logical key. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#88edc(physicalKey: PhysicalKeyboardKey#f5c25(usbHidUsage: "0x000700e4", debugName: "Control Right"), logicalKey: LogicalKeyboardKey#d24f3(keyId: "0x200000101", keyLabel: "Control Right", debugName: "Control Right"), character: null, timeStamp: 0:05:28.012220, synthesized) and the recorded logical key LogicalKeyboardKey#4999d(keyId: "0x10000050c", keyLabel: "Select", debugName: "Select"))
E/flutter (21570): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter (21570): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter (21570): #2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:437:16)
E/flutter (21570): #3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:445:6)
E/flutter (21570): #4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:537:5)
E/flutter (21570): #5      KeyEventManager.handleKeyData (package:flutter/src/services/hardware_keyboard.dart:883:29)
E/flutter (21570): #6      PlatformDispatcher._keyDataListener.<anonymous closure>.<anonymous closure> (dart:ui/platform_dispatcher.dart:430:41)
E/flutter (21570): #7      _invoke1 (dart:ui/hooks.dart:158:13)
E/flutter (21570): #8      PlatformDispatcher._keyDataListener.<anonymous closure> (dart:ui/platform_dispatcher.dart:428:7)
E/flutter (21570): #9      _invoke2 (dart:ui/hooks.dart:174:13)
E/flutter (21570): #10     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40:5)
E/flutter (21570): #11     _Channel.push (dart:ui/channel_buffers.dart:130:31)
E/flutter (21570): #12     ChannelBuffers.push (dart:ui/channel_buffers.dart:326:17)
E/flutter (21570): #13     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:664:22)
E/flutter (21570): #14     _dispatchPlatformMessage (dart:ui/hooks.dart:86:31)
```

Beta channel.
Same error in stable channel (3.7.7) and master (9ba0d08ebc).

<details>

[✓] Flutter (Channel beta, 3.8.0-10.1.pre, on Calculate Linux 23 6.0.9-calculate-x86_64, locale ru_RU.UTF-8)
    • Flutter version 3.8.0-10.1.pre on channel beta at /opt/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision 1a0a03a41d (3 недели назад), 2023-02-16 22:03:58 -0600
    • Engine revision 639e313f99
    • Dart version 3.0.0 (build 3.0.0-218.1.beta)
    • DevTools version 2.21.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /opt/android-sdk-update-manager
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /opt/android-sdk-update-manager
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 15.0.7
    • cmake version 3.25.2
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[✓] Android Studio (version 2021.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 71.2.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (4 available)
    • X96 W (mobile)               • 192.168.0.76:5555 • android-arm   • Android 7.1.2 (API 25)
    • Linux (desktop)              • linux             • linux-x64     • Calculate Linux 23 6.0.9-calculate-x86_64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

</details>

**Comment by danagbemava-nc** [comment]
Hi @rounce
Looking at the error log, it looks similar to https://github.com/flutter/flutter/issues/101275, so follow up in that issue for further updates.

Please do leave a thumbs up on the original author's post so we can track and prioritize the issue base on severity and demand. Thanks!

**Comment by rounce** [comment]
Thanks. 
Workaround https://github.com/flutter/flutter/issues/65233#issuecomment-1364115011 works
