### ISSUE TITLE
Compile time error - 

### ISSUE THREAD

**Issue by bibaswan-bhawal** [flutter/flutter#122407]
## Steps to Reproduce
I just started getting this error when trying to run my app. flutter run was working working fine and then I did some code cleanup and ran again and I am getting this error. The enviroment did not change and the logic of the code did not change just restructuring. Not quite sure where to even begin debuging this because all the files it's reporting are from the dart kernel. 
 

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

flutter compiles and runs app on device

**Actual results:** 

![2023-03-10 08_08_03-](https://user-images.githubusercontent.com/67685395/224366012-8d7824ad-9c90-4d2a-bd12-14ea4bdf7ac9.png)

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by bibaswan-bhawal** [comment]
what's that?

**Comment by johnniwinther** [comment]
@alexmarkov meant that the crash happens in the CFE (common front end) of Dart, which I am in charge of.

What version of Flutter/Dart are you using?

**Comment by bibaswan-bhawal** [comment]
I'm running this on the beta channel with flutter 3.8.0-10.1 and dart 3.0.0

**Comment by johnniwinther** [comment]
The crash happens in code that checks exhaustiveness for switch statements/expressions using the experimental "Patterns" feature. Did you enable the experiment or try to use patterns?

**Comment by bibaswan-bhawal** [comment]
yes I am using records and patterns

**Comment by johnniwinther** [comment]
Ok. Then you are hitting some of the cases we haven't implemented (fully) yet.

**Comment by bibaswan-bhawal** [comment]
Is there a way to figure out which case that is so I can work around it?

**Comment by bibaswan-bhawal** [comment]
Also this seems to be a new problem because I've had records and patterns implements for a couple weeks now and it's been working fine including on this version of dart and flutter

**Comment by johnniwinther** [comment]
The crash in this case is trigger when an enum value used in a switch case hasn't had its value computed when the switch case is being processed. The order in which this occurs in dependent on the order of the code (within the library or the order of the imports). It is hard to avoid.

It might be that you can avoid triggering the exhaustiveness check that crashes by add a default case to the switch statement.

**Comment by bibaswan-bhawal** [comment]
interestingly enough I haven't changed the switch statements or the code that returns the enum the only thing I did do was add explicit return types for my functions and removing them seems to compile the code again

**Comment by darshankawar** [comment]
@bibaswan-bhawal 
Can you provide us a minimal code sample that shows this error log ? Also please provide the error log in formatted text for better viewing.

@johnniwinther Should this be directed to dart-lang repo for better tracking ?

**Comment by bibaswan-bhawal** [comment]
I would if I knew what even caused this compile time error. This just seems like the exhaustive pattern matching algorithm for switch statements is going up against a race condition somewhere else in the code. I really have no clue what it could be racing against and for the time being upgrading to the master build channel has solved this.

**Comment by johnniwinther** [comment]
I think we can close this. We'll track this in the Dart issue tracker: https://github.com/dart-lang/sdk/issues/51716
