### ISSUE TITLE
[iOS] App crashes on after running out of memory.

### ISSUE THREAD

**Issue by inc16sec** [flutter/flutter#122453]
Ever since I upgraded to Flutter 3.7.0 and up from 3.3.10 the app started to run out of memory and would crash.
The app relies on both `CachedNetworkImage` and `VideoPlayer` so I am not sure what exactly causes the app to run out of memory. There are issues out there open about both [video_player](https://github.com/flutter/flutter/issues/96370) causing this and [image](https://github.com/flutter/flutter/issues/62107) widget so not sure exactly which one. 
NOTE. The memory usage keeps increasing even if I'm not using the app.. Example: I run the app, it loads and then the memory usage keeps increasing even if scrolling and stopping or navigating to a different page just once and then doing nothing memory usage keeps increasing. It looks like a memory leak, but I can't seem to know what exactly causes this. And I don't think there's a leak on my part. As I've mentioned before, this only started to happen to me after upgrading to 3.7.0. And even when upgrading to 3.7.3 the issue still persists.

This is what is thrown when the app crashes.

```
[VERBOSE-2:profiler_metrics_ios.mm(203)] Error retrieving thread information: (os/kern) invalid argument
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_RESOURCE RESOURCE_TYPE_MEMORY (limit=2098 MB, unused=0x0)
    frame #0: 0x0000000212414da8 libsystem_kernel.dylib`mach_msg2_trap + 8
libsystem_kernel.dylib`mach_msg2_trap:
->  0x212414da8 <+8>: ret
libsystem_kernel.dylib`macx_swapon:
    0x212414dac <+0>: mov    x16, #-0x30
    0x212414db0 <+4>: svc    #0x80
    0x212414db4 <+8>: ret
Target 0: (Runner) stopped.
Lost connection to device.
Exited
```

I would like to share some reproducible code too, but I don't exactly know what makes the app crash, and I do have quite a big project so I don't know what to share.

**Target OS version/browser:**
16.3
**Devices:**
iPhone 11

## Logs

<details>
<summary>Logs</summary>

```
[!] Flutter (Channel stable, 3.7.3, on macOS 12.6.3 21G419 darwin-x64, locale
    en-ES)
    • Flutter version 3.7.3 on channel stable at
      /Users/ndm/documents/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/ndm/Documents/flutter/bin/flutter, which is not inside your
      current Flutter SDK checkout at /Users/ndm/documents/flutter.
      Consider adding /Users/ndm/documents/flutter/bin to the front of your
      path.
    ! Warning: `dart` on your path resolves to
      /Users/ndm/Documents/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/ndm/documents/flutter.
      Consider adding /Users/ndm/documents/flutter/bin to the front of your
      path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (4 weeks ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/ndm/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.76.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • ndm’s iPhone (mobile) • 00008030-0011188A14A3402E • ios            • iOS
      16.3 20D47
    • macOS (desktop)         • macos                     • darwin-x64     •
      macOS 12.6.3 21G419 darwin-x64
    • Chrome (web)            • chrome                    • web-javascript •
      Google Chrome 111.0.5563.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by kasun-1991** [comment]
[VERBOSE-2:profiler_metrics_ios.mm(203)] Error retrieving thread information: (os/kern) invalid argument
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_RESOURCE RESOURCE_TYPE_MEMORY (limit=2098 MB, unused=0x0)
    frame #0: 0x0000000212414da8 libsystem_kernel.dylib`mach_msg2_trap + 8
libsystem_kernel.dylib`mach_msg2_trap:
->  0x212414da8 <+8>: ret
libsystem_kernel.dylib`macx_swapon:
    0x212414dac <+0>: mov    x16, #-0x30
    0x212414db0 <+4>: svc    #0x80
    0x212414db4 <+8>: ret
Target 0: (Runner) stopped.
Lost connection to device.
Exited

**Comment by darshankawar** [comment]
Thanks for the report @inc16sec 

`stop reason = EXC_RESOURCE RESOURCE_TYPE_MEMORY (limit=2098 MB, unused=0x0)` indicates memory exhaustion and most probably related to images you might be using that are large in size.

We would need reproducible code to properly analyze / verify this crash.

**Comment by inc16sec** [comment]
@darshankawar Most of my images are not large in size. Plus it is a ListView.builder.. Isn't it supposed to dispose of images that are out of view?

**Comment by darshankawar** [comment]
See [this](https://stackoverflow.com/a/66345328) for your reference and check if it helps in your case.

**Comment by inc16sec** [comment]
> See [this](https://stackoverflow.com/a/66345328) for your reference and check if it helps in your case.

Looks very helpful. Thank you @darshankawar for your response.
