### ISSUE TITLE
Error: 'AssetManifest' is imported from both 'package:flutter/src/services/asset_manifest.dart' and 'package:printing/src/fonts/manifest.dart'.

### ISSUE THREAD

**Issue by Bucaneiradill** [flutter/flutter#122544]
Hello There! I have been developing a flutter web app, but recently the I switched  to the flutter branch Master  instead of the stable, 'cause I had an issue on the windows recognize in `flutter doctor`. Now I have the issue mentioned bellow: 

`Error: 'AssetManifest' is imported from both 'package:flutter/src/services/asset_manifest.dart' and 'package:printing/src/fonts/manifest.dart'.`

I already tried `flutter pub get` and `flutter pub cache repair`. 
Looking all over project, I didn't found the packages mentioned in the error.
Can someone help me?

Here is my pubspec.yaml file:

`name: speleo_web
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  flutter_secure_storage: ^8.0.0
  crypt: ^4.2.1
  postgrest: ^0.1.10+1
  multi_select_flutter: ^4.1.2
  table_calendar: ^3.0.6
  intl: ^0.18.0
  mask_text_input_formatter: ^2.3.0
  easy_mask: ^2.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.1
  supabase_flutter: ^0.3.3
  path_provider: ^2.0.11
  pdf: ^3.8.3
  printing: ^5.9.3
  carousel_slider: ^4.1.1
  smooth_page_indicator: ^1.0.0+2
  photo_view: ^0.14.0
  flutter_unity_widget: ^2022.2.0
  pointer_interceptor: ^0.9.3+3
  webview_flutter: ^2.8.0
  flutter_unity_widget_web: ^1.0.1
  flutter_dropzone: ^3.0.5
  universal_io: ^2.0.4
  file_saver: ^0.1.1
  dio: ^4.0.6
  foundation_flutter: ^0.2.0
  open_file_plus: ^3.3.0
  showcaseview: ^2.0.0+1
  page_transition: ^2.0.9
  scrollable_positioned_list: ^0.3.5
  shimmer: ^2.0.0
  csv: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

`

**Comment by darshankawar** [comment]
@Bucaneiradill 
See [this](https://github.com/flutter/flutter/issues/120882) issue and underlying comments in it for solution.
Closing this as a duplicate.

**Comment by Bucaneiradill** [comment]
Thank you! I finally solved this issue, editing the font.dart file with the code founded on the link.
