### ISSUE TITLE
Cannot sign into to https://pub.flutter-io.cn/ on any browser to authenticate

### ISSUE THREAD

**Issue by Kerandon** [flutter/flutter#122506]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run flutter pub publish
2. Asked to authenticate
3. Unable to authenticate with any browser (Mozilla, Chrome, Edge). Add blocker turned off, page refreshed.
4. Note, I can log into pub.dev with VPN, but not https://pub.flutter-io.cn

### Actual results

Unable to login to https://pub.flutter-io.cn to authenticate in order to publish a flutter package

### Logs

```
tps://pub.flutter-io.cn (y/N)? y
Uploading...
https://pub.flutter-io.cn package repository requested authentication!
You can provide credentials using:
    flutter pub token add https://pub.flutter-io.cn

Authentication is required, please add `authorization` header.
Authentication failed!
pub finished with exit code 65
```

Sign in button for https://pub.flutter-io.cn does not respond to taps.

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by exaby73** [comment]
Hello @Kerandon. This issue does not seem to be specific to Flutter itself. It would be best raised in https://github.com/dart-lang/pub. Since this issue is not an issue with Flutter itself as mentioned, I will close this issue. Thank you
