### ISSUE TITLE
autosubmit bot submits without waiting for green Google Testing

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#122543]
Examples:
* https://github.com/flutter/flutter/pull/122233
* https://github.com/flutter/flutter/pull/122327
* https://github.com/flutter/flutter/pull/122325
* https://github.com/flutter/flutter/pull/122060
* https://github.com/flutter/flutter/pull/121549

The first three have a pending Google Testing check, the last two have a failing Google Testing check and all of them were submitted by the auto-submit bot.

The expectation is that the autosubmit bot should wait for a green Google Testing check before it submits a PR.

In at least one instance this bug has caused major issues during a flutter roll into google3: b/272640575

**Comment by ricardoamador** [comment]
Hmm, odd. Okay I will take a look shortly.

**Comment by ricardoamador** [comment]
Taking a look now.

**Comment by ricardoamador** [comment]
Some info from the release team on this: 

```

**Comment by ricardoamador** [comment]
@goderbauer Can you please clarify what you mean by:

> this bug has caused major issues during a flutter roll into google3

https://github.com/flutter/flutter/wiki/Understanding-Google-Testing
It can take 2+ hours total turnaround time for Google Testing. Since Google Testing is not currently a checkRun it is not required to complete.

**Comment by goderbauer** [comment]
The autosubmit bot landed a PR, which turned out to break google3. If the autosubmit bot would have waited for the google testing check, the PR would have never landed because the check would have failed. Because it didn't do that, the failure was only discovered when the rollers tried to roll the change into google3. It then had to be reverted to unblock the roll.

The issue here is all the churn resulting out of not properly waiting for the result of Google Testing before the PR was auto-submitted.

**Comment by ricardoamador** [comment]
@itsjustkevin I believe the release team has tracking issues. Once they are done this should be trivial depending on how the checkrun is created. You can leave it assigned to me.

**Comment by XilaiZhang** [comment]
from triage: this would be fixed once google testing migrate to check run.

**Comment by XilaiZhang** [comment]
From triage: Autosubmit should respect Google Testing status now
