### ISSUE TITLE
flutter tool's help output wraps

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1225]
In 80 char columns, this is what the flutter tool's help output looks like:

![screen shot 2016-01-13 at 8 33 59 am](https://cloud.githubusercontent.com/assets/5479/12300465/6cb6a67e-b9d0-11e5-9a80-71496d26653c.png)

Not sure if we're using the args package, or if the args package makes this easier, but if we can newline and indent the help output, it will make it easier to read and scan.

For example:

```
Local build selection options (not normally required):

    --debug                Set this if you are building Flutter locally and want
                                 to use the debug build products. (Defaults to true
                                 if --engine-src-path is specified and
                                 --release is not, otherwise false.)

    --release              Set this if you are building Flutter locally and want
                                to use the release build products.
```

**Comment by devoncarew** [comment]
We could tighten up the text for `listen` as well.

**Comment by sethladd** [comment]
We are using the args package: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/runner/flutter_command_runner.dart

@munificent are you aware of a way for the args package to print the help text in a way that indents and newlines instead of wraps? Or is that the responsibility of the tool?

I'm also curious if we can put a newline after `Global options:`

**Comment by Hixie** [comment]
I would like the args package to automatically line wrap on spaces at the current screen width. We should just not linewrap at all in the flutter code, IMHO.

**Comment by munificent** [comment]
> @munificent are you aware of a way for the args package to print the help text in a way that indents and newlines instead of wraps? Or is that the responsibility of the tool?

Right now, it's the responsibility of the tool. In my apps, I just hand-wrap the output to fit in 80 columns. Even if the terminal is wider, wider lines aren't necessarily easier to ready anyway.

I wouldn't be opposed to having args support word-wrapping, though. Want to [file an issue](https://github.com/dart-lang/args/issues)?

**Comment by Hixie** [comment]
Filed https://github.com/dart-lang/args/issues/41

**Comment by sethladd** [comment]
Fixed by https://github.com/flutter/flutter/pull/1362

**Comment by sethladd** [comment]
Looks like this regressed.

![screen shot 2016-02-01 at 12 08 25 pm](https://cloud.githubusercontent.com/assets/5479/12729640/a2240eb2-c8dc-11e5-82e0-bff68f5058d9.png)

**Comment by sethladd** [comment]
cc @devoncarew maybe some of the recent tool work?

**Comment by devoncarew** [comment]
Were we using a feature of `args` to wrap?

**Comment by sethladd** [comment]
Nope. See https://github.com/flutter/flutter/pull/1362 ... we have to hand-wrap. (there was a bug fix in args to allow for multi-line descriptions, but wrapping is up to us)

**Comment by devoncarew** [comment]
Not 100% certain that we should hard-code wraps at 80 cols in the tool's output. I can tersify some of the above descriptions however.

**Comment by sethladd** [comment]
The current output doesn't look great with the default width for a console. And the args package isn't going to get auto-wrap anytime soon. The default output is hard to scan, unless you take the time to make your console wider.

**Comment by eseidelGoogle** [comment]
We can get the terminal width via tput:
http://stackoverflow.com/questions/263890/how-do-i-find-the-width-height-of-a-terminal-window

Or looks like dart's stdout exposes this too:
https://api.dartlang.org/1.13.2/dart-io/Stdout/terminalColumns.html

There are some doubts as to its usability expressed in https://github.com/dart-lang/test/issues/288, not sure why.

We can write our own simple wrapping function if necessary.

**Comment by eseidelGoogle** [comment]
the test package even has one we could use:
https://github.com/dart-lang/test/blob/master/lib/src/utils.dart#L121

**Comment by devoncarew** [comment]
The current help output now displayed w/o wrapping at 100 cols (https://github.com/flutter/flutter/pull/1559) - I think this is a reasonable target.
