### ISSUE TITLE
EOF reached without finding string terminator

### ISSUE THREAD

**Issue by yangxiavae** [flutter/flutter#122583]
## There are error info when I upload package with commond  'flutter packages pub publish --server=xxx -v'
FINE: Uploading finished (4.522s).
ERR : EOF reached without finding string terminator
FINE: Exception type: ApplicationException
FINE: package:pub/src/utils.dart 523:5                                 fail
    | package:pub/src/http.dart 323:3                                  handleJsonError
    | package:pub/src/command/lish.dart 147:9                          LishCommand._publishUsingClient
    | ===== asynchronous gap ===========================
    | dart:async                                                       Future.catchError
    | package:pub/src/utils.dart 109:52                                captureErrors.wrappedCallback
    | package:stack_trace                                              Chain.capture
    | package:pub/src/utils.dart 122:11                                captureErrors
    | package:pub/src/command.dart 189:13                              PubCommand.run
    | package:args/command_runner.dart 209:27                          CommandRunner.runCommand
    | package:pub/src/command_runner.dart 176:24                       PubCommandRunner.runCommand
    | package:pub/src/command_runner.dart 161:20                       PubCommandRunner.run
    | package:dartdev/dartdev.dart 45:56                               runDartdev
    | C:\b\s\w\ir\cache\builder\sdk\pkg\dartdev\bin\dartdev.dart 11:9  main
IO  : Writing 2493290 characters to text file D:\software\sdk\flutter\flutter_windows_3.3.0-stable\flutter\.pub-cache\log\pub_log.txt.
MSG : Logs written to D:\software\sdk\flutter\flutter_windows_3.3.0-stable\flutter\.pub-cache\log\pub_log.txt.
[+21408 ms] "flutter pub" took 21,527ms.
[   +3 ms] pub finished with exit code 1
[        ]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:418:7)
           <asynchronous suspension>
           #2      PackagesPassthroughCommand.runCommand (package:flutter_tools/src/commands/packages.dart:274:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>

[ +203 ms] ensureAnalyticsSent: 202ms
[        ] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

## Flutter doctor 
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.0, on Microsoft Windows [版本 10.0.17763.1098])
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.1)
[√] Android Studio (version 4.1)
[√] Connected device (4 available)

How can i fix it?

**Comment by exaby73** [comment]
Hello @yangxiavae. Did you try with the latest stable version 3.7.x? If the issue still persists, I suggest you open an issue on https://github.com/dart-lang/pub as this is related to the pub CLI and not Flutter itself. Due to these reasons, I will close this issue. Thank you
