### ISSUE TITLE
RawKeyboardListener can't get any scan keylabel when the system input type is Chinese pinyin and the barcode is char

### ISSUE THREAD

**Issue by NickYoung-max** [flutter/flutter#122510]
RawKeyboardListener can't get any scan keylabel when the system input type is Chinese pinyin and the barcode info is char,like yyydsds 、dsdljksdkf，and barCode info 123456date lost char : date , just get 123456 .

my flutter version is 3.7.0
code like below and the system input type is Chinese pinyin，scan barCode （info is 123456date）， only print 123456 , no date
RawKeyboardListener(
      focusNode: _focusNode,
      onKey: (event) {
        if(event is RawKeyDownEvent){
          RawKeyEventDataWindows rawKeyEventDataWindows = event.data as RawKeyEventDataWindows;
          keyLabel = rawKeyEventDataWindows.logicalKey.keyLabel;
         print("main--按键-------------------keyLabel=$keyLabel}");
     }
)

**Comment by flexagoon** [comment]
It's not clear what your issue is. Please use the proper template and format your code using code blocks (```).

**Comment by exaby73** [comment]
Hello @NickYoung-max. As @flexagoon mentioned, the issue here is unclear. Could you please describe the issue in more detail? 

Could you please provide the following information as well?

- A [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by NickYoung-max** [comment]
> Hello @NickYoung-max. As @flexagoon mentioned, the issue here is unclear. Could you please describe the issue in more detail?
> 
> Could you please provide the following information as well?
> 
> * A [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
> * The output of `flutter doctor -v`
> 
> Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.0, on Microsoft Windows [Version 10.0.19044.2728], locale zh-CN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
[√] Android Studio (version 2021.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!

part of my code:
    RawKeyboardListener(
        focusNode: _focusNode,
        onKey: (event) {
        if(event is RawKeyDownEvent){
        RawKeyEventDataWindows rawKeyEventDataWindows = event.data as RawKeyEventDataWindows;
        keyLabel = rawKeyEventDataWindows.logicalKey.keyLabel;
        print("main---------------------keyLabel=$keyLabel}");
        }
    )
I use the string "123456data" to make a qrcode,then sacn the qrcode to input .when the windows system keyboard  input type is char/english 
![image](https://user-images.githubusercontent.com/38856823/225495518-efed37b2-b5a8-4e2f-9057-d29235023b35.png)
，I can get the full scan input string “123456data” print ,but when tne system keyboard input type is chinese pinyin (
![image](https://user-images.githubusercontent.com/38856823/225495232-12488b23-20af-454d-82a2-e126b0c79512.png)
)，I only get  "123456" print ，string "data" lost .

**Comment by NickYoung-max** [comment]
> I need a [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that I can run directly to reproduce the issue. Please provide a complete and minimal sample


//the simple code of my main.dart
void main() async {
  runApp(MainApp());
}


class MainApp extends StatelessWidget {
  MainApp({Key key}) : super(key: key);

  final FocusNode _focusNode = FocusNode();
  String keyLabel = '';
  @override
  Widget build(BuildContext context) {
    return RawKeyboardListener(
      focusNode: _focusNode,
      onKey: (event) {
        if(event is RawKeyDownEvent){
          // print('data---------------${jsonEncode(event.data as RawKeyEventDataWindows)}');
          RawKeyEventDataWindows rawKeyEventDataWindows = event.data as RawKeyEventDataWindows;
          keyLabel = rawKeyEventDataWindows.keyLabel;
          print("keyLabel=$keyLabel---------keyCode=${rawKeyEventDataWindows.keyCode}");
        }
      },
      child: const SizedBox()
    );
  }
}

**Comment by flexagoon** [comment]
@NickYoung-max please format your code as a code block using triple backticks (```) to make it easier to read.

It also doesn't seem like your code has anything to do with barcodes or QR codes?

**Comment by exaby73** [comment]
Hello @NickYoung-max. The code sample provided is not complete. Could you provide steps to reproduce the issue?

**Comment by NickYoung-max** [comment]
> 

Just like the code I provided, I use a RawKeyboardListener as the root widget. When I use the scanner to scan the QR code(generate by string "123456data"), the scanner will send the data (1,2,3,4,5,6,d,a,t,a) like keyboard input. At this time, the onKey event will monitor the input. When system input method is char/english 
![image](https://user-images.githubusercontent.com/38856823/225939464-86c6fc30-65ec-4700-9a03-f6b955c63203.png), the onKey event monitors all the input information (1,2,3,4,5,6,d,a,t,a), but when the system input method is Chinese Pinyin, ![image](https://user-images.githubusercontent.com/38856823/225939706-f20c3082-6692-4ea0-8679-c5e2d5239265.png),only " 1,2,3,4,5,6"  is input, "d,a,t,a" is missing. So sometimes I lose data when the qrcode information contains char.

> Hello @NickYoung-max. The code sample provided is not complete. Could you provide steps to reproduce the issue?

**Comment by flexagoon** [comment]
@NickYoung-max please provide a code file.

**Comment by flexagoon** [comment]
It's not clear what QR codes you're talking about

**Comment by flexagoon** [comment]
Alright, I understood your issue now.

Have you tried using `KeyboardListener` instead of `RawKeyboardListener`?

**Comment by NickYoung-max** [comment]
> Alright, I understand your issue now.
> 
> Have you tried using `KeyboardListener` instead of `RawKeyboardListener`?

yeah,I've tried KeyboardListener,it's the same result. There is a new situation,when I use "data123456" to generate a qrcode,scan it ,I only get string "23456" and "data1" lost.

**Comment by exaby73** [comment]
When manually typing `123456data`, does the `RawKeyboardListener` work as expected?
