### ISSUE TITLE
RichText behave differently with the latest flutter version.

### ISSUE THREAD

**Issue by Senthuran-01** [flutter/flutter#122514]
I am using the RichText() Widget to show a icon and text parallelly. I have wrapped the RichText() widget with SizedBox(), So, That if the text get bigger it will be folded to two lines.But the problem is with the latest flutter version 3.7.7 the icon is also getting to the second line.It didn't happened with the flutter version 3.3.10.I am not sure whether it's a bug or they changed the behaviour of the RichText() widget.

```
import 'package:device_info/sending_health_data.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const InitialApp());
}

class InitialApp extends StatelessWidget {
  const InitialApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: "RichText Issue",
      home: RichTextIssue(),
      debugShowCheckedModeBanner: false,
    );
  }
}

```

```
import 'package:flutter/material.dart';

class RichTextIssue extends StatelessWidget {
  const RichTextIssue({super.key});

  @override
  Widget build(BuildContext context) {
    double kWidth = MediaQuery.of(context).size.width;
    double kHeight = MediaQuery.of(context).size.height;
    return Scaffold(
      body: Container(
        height: kHeight,
        padding: const EdgeInsets.all(10),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            SizedBox(
              width: kWidth * 0.45,
              child: RichText(
                text: const TextSpan(
                  style: TextStyle(color: Colors.black, fontSize: 16),
                  children: [
                    WidgetSpan(
                        child: Icon(
                      Icons.language,
                      color: Colors.orange,
                      size: 24,
                    )),
                    TextSpan(text: "Name of the Language"),
                  ],
                ),
              ),
            ),
            SizedBox(
              width: kWidth * 0.45,
              child: RichText(
                textDirection: TextDirection.rtl,
                text: const TextSpan(
                  style: TextStyle(color: Colors.black, fontSize: 16),
                  children: [
                    WidgetSpan(child: Icon(Icons.translate)),
                    TextSpan(text: "Name of the Subcategory"),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```

<details><summary>Output Image</summary>
<p>

**Flutter Version 3.3.10:**

![Correct Image](https://user-images.githubusercontent.com/81215997/224713662-31c2dc19-93f5-4fc0-be50-bbf7eb7606b2.jpg)

**Flutter Version 3.7.7:**

![Issue Image](https://user-images.githubusercontent.com/81215997/224713726-e29b8fc4-0684-4add-8ee2-84a64710ec96.jpg)

</p>
</details>

<details><summary>Flutter Doctor</summary>
<p>

**Flutter Doctor 3.3.10:**

[✓] Flutter (Channel stable, 3.3.10, on macOS 12.6.3 21G419 darwin-x64, locale en-IN)
    • Flutter version 3.3.10 on channel stable at /Volumes/Backup/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (3 months ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/casperonflutter/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.76.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • RMX3612 (mobile) • XGLZJFM7JRMNJFAQ • android-arm64  • Android 13 (API 33)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 12.6.3 21G419 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 111.0.5563.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Flutter Doctor 3.7.7:**

[✓] Flutter (Channel stable, 3.7.7, on macOS 12.6.3 21G419 darwin-x64, locale en-IN)
    • Flutter version 3.7.7 on channel stable at /Volumes/Backup/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (5 days ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/casperonflutter/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.76.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • RMX3612 (mobile) • XGLZJFM7JRMNJFAQ • android-arm64  • Android 13 (API 33)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 12.6.3 21G419 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 111.0.5563.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

</p>
</details>

**To reproduce the issue just switch between flutter version 3.3.10 and 3.7.7**

**Comment by exaby73** [comment]
Hello @Senthuran-01. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by Senthuran-01** [comment]
Hi @exaby73 I have updated the question please check if this one is ok.

**Comment by exaby73** [comment]
@Senthuran-01 Why not try using a `Row` to achieve the same effect?

**Comment by Senthuran-01** [comment]
@exaby73 With `Row()` i won't be able to achieve the design I want. 

- The text on the right side must be right-aligned.
- if the text get's bigger it should be folded into two lines.
- there should not be any extra space between the text and the prefix icon

if I use the `Row()` I need to wrap the text with a `Sizedbox()` with a fixed width. And when the text is folded into two lines there will be a space between the icon and the text. Also using the `Expanded` or `Flexible` leads to the same result.

`RichText()` is the only option I have here.

**Comment by exaby73** [comment]
Is this how you want it to look?

![image](https://user-images.githubusercontent.com/50555895/225244419-ec78892c-a3e2-4189-9abb-46bfd184e59f.png)

**Comment by exaby73** [comment]
I see no difference in 3.3.10 and 3.7.7

![image](https://user-images.githubusercontent.com/50555895/225333313-694d057b-e8eb-40d3-8cb6-7e0211012062.png)

**Comment by Senthuran-01** [comment]
@exaby73 if this is the exact behaviour then how can I achieve the design I mentioned above.

**Comment by exaby73** [comment]
Instead of `textDirection: TextDirection.rlt`, you should use `textAlign: TextAlign.right`. I was able to recreate your design with that :)

**Comment by Senthuran-01** [comment]
@exaby73 Thanks, Replacing the `textDirection` with `textAlign` do the work.
