### ISSUE TITLE
[image_picker] Image file getting renamed.

### ISSUE THREAD

**Issue by SwiftDeveloper859** [flutter/flutter#122523]
Hi All, we are building an application using flutter for both iOS and Android platform.
In This app we are using the flutter  "image_picker" library with version "0.8.4". Everything working fine except the original image name is getting replaced with other name string "image_picker_guidValue".  
Can anybody suggest us, how we can get the original image name?

**Comment by darshankawar** [comment]
@SwiftDeveloper859 
There's a similar open issue describing your case, https://github.com/flutter/flutter/issues/64685. You can follow-up in it for further updates. 

Please do leave a thumbs up on the original author's post so we can track and prioritize the issue base on severity and demand. Thanks!
