### ISSUE TITLE
[web] Modify external resource URL

### ISSUE THREAD

**Issue by fawdlstty** [flutter/flutter#122509]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. using flutter web in internal or limited web

### Actual results

For example <https://github.com/flutter/flutter/issues/98492>, it is expected to replace the google apis path with the font resource path specified by the flutter compilation command (--dart-define), or package the google font resource at the time of compilation, to avoid users from failing because they cannot access google apis. For developers, the ideal way is to specify the dart-define parameter instead of specifying a new font. If many things need to be handled manually to solve a font resource, it will cause a lot of trouble for many developers. Because it can be solved manually by developers, it is not considered as a feature problem.

In addition, the Google Apis font file is large. In the absence of a specific font, I prefer to use the browser default font, otherwise the compiled volume will become large

### Logs

N

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.8, on Ubuntu 20.04.5 LTS 5.15.0-67-generic, locale zh_CN.UTF-8)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] VS Code (version 1.73.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 2 categories.

**Comment by huycozy** [comment]
Hi @fawdlstty 
As far as I can see, this issue looks like a proposal, but can you be more specific on the `Proposal` (what you would like Flutter to be able to do)? (it would be appreciated if you could provide an example)

**Comment by fawdlstty** [comment]
I think flutter should add two features:

1. Package all externally referenced font files
`flutter build web --dart-define=FLUTTER_WEB_FONT=PACK`

2. Modify the external referenced font file URL host
`flutter build web --dart-define=FLUTTER_WEB_FONT=URL:fonts.font.im`

Thank you for your attention @huycozy

**Comment by huycozy** [comment]
Thanks for the response. But as my understanding, even when using `--dart-define` with a font URL, will it solve the problem you raised above (`to avoid users from failing because they cannot access google apis`)? (As it's related to network issue rather than Flutter itself)

**Comment by fawdlstty** [comment]
I think this is related to Flutter, because the web feature of Flutter is very different from that of Flutter native app. If possible, I hope the features are the same as native applications compiled by Flutter. If not, I wish I can modify them through compiler options

**Comment by huycozy** [comment]
Labeling the issue as a proposal for further insights.

**Comment by yjbanov** [comment]
I think the following two issues cover this:

- https://github.com/flutter/flutter/issues/85793
- https://github.com/flutter/flutter/issues/94404

Deduplicating.
