### ISSUE TITLE
Flutter WebView don't work as intended (see video below)

### ISSUE THREAD

**Issue by ysumiit005** [flutter/flutter#122516]
I made webview in flutter. (code below)(video below)
It does show the webpage of https://flutter.dev
but the webpage is losing some of its css properties like
- slider has no CSS.
- button colors are not visible.
- flutter logo gets stuck on screen while scrolling down. 
- etc 

this all donot happen on chrome or other browsers.
also tried webview in RN & it worked correctly there.

below is the code to reproduce 
<details>
<summary>Code sample</summary>
//// main.dart file

import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(
    const MaterialApp(
      home: WebViewApp(),
    ),
  );
}

class WebViewApp extends StatefulWidget {
  const WebViewApp({super.key});

  @override
  State<WebViewApp> createState() => _WebViewAppState();
}

class _WebViewAppState extends State<WebViewApp> {
  late final WebViewController controller;

  @override
  void initState() {
    super.initState();
    controller = WebViewController()
      ..loadRequest(
        Uri.parse('https://flutter.dev'),
      );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Flutter WebView'),
      ),
      body: WebViewWidget(
        controller: controller,
      ),
    );
  }
}

</details>

https://user-images.githubusercontent.com/98808586/224653037-06bb256d-28ab-488c-aa13-22e1f99a76dc.mp4

other things I found 
- slider CSS donot work properly 
- cannot full screen videos on the youtube site
- on clicking on the youtube link it donot open the app on the android device rather does nothing

**Comment by stuartmorgan** [comment]
You haven't enabled JavaScript, and that's how the page displays with JavaScript disabled; you can compare to a trivial non-Flutter Android WebView app.

Closing as this is expected behavior.
