### ISSUE TITLE
How to set initial cookie in webview_flutter 4.0.6？"initialCookies" not found

### ISSUE THREAD

**Issue by luckmlc** [flutter/flutter#122599]
How to set initial cookie in webview_flutter 4.0.6？"initialCookies" not found

**Comment by huycozy** [comment]
Hi @luckmlc 
Where did you see the error message (`initialCookies not found`)?

Also, in order to address the issue properly, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. 

Thank you!

**Comment by luckmlc** [comment]
In webview_flutter 3.0.4, initial cookies can be set using initialCookies，as follows：

```
WebView(
	initialUrl: url,
	initialCookies: initCookies,
	javascriptMode: JavascriptMode.unrestricted,
)
```

Upgrade to version 4.0.6, The initialCookies parameter is removed，How to set initial cookie now？

**Comment by stuartmorgan** [comment]
See [WebViewCookieManager](https://pub.dev/documentation/webview_flutter/latest/webview_flutter/WebViewCookieManager-class.html)

@bparrishMines We should probably add a mention of this to the migration section in the README, and/or add a small section about cookies to the README in general.

**Comment by RishabhSpark** [comment]
Hi! I'd like to work on this. Can someone guide me through this as I'm new to open-source and flutter? :D

**Comment by stuartmorgan** [comment]
@RishabhSpark Please see https://github.com/flutter/packages/blob/main/CONTRIBUTING.md for resources.

**Comment by StephenBanz** [comment]
Hey @stuartmorgan 
Thanks for the reply.
I have tried with [WebViewCookieManager](https://pub.dev/documentation/webview_flutter/latest/webview_flutter/WebViewCookieManager-class.html). It works for android but not for IOS.
IOS works with the header but for only the first load.
I created a StackOverflow question as I was unsure if it was a library problem or a code problem.

**Comment by bparrishMines** [comment]
@StephenBanz Can you create a new issue for this? Your bug is unrelated to this issue.
