### ISSUE TITLE
Get all values from Flutter Form

### ISSUE THREAD

**Issue by HonestElf** [flutter/flutter#122597]
Hi everyone
I cant find the right way to work with forms in Flutter.
Now if I want to send all values from form on submit, I need to create controller for each field and put all these values ​​in the function call. This is normal if the form is small for 2-3 fields. And what if there are 10, 15 fields?
At the same time, I want to use third-party libraries to a minimum. In my opinion it would be very useful to be able to get all values for example by "_loginForm.currentState.values" as Map<_fieldName, fieldValue_>

**Comment by natintosh** [comment]
You can't, just write a business logic that gets the values from `TextEditingController` if not, you can make one yourself

**Comment by huycozy** [comment]
Thanks for the report! This is a known issue being tracked at #107528 and its PR is on the way. 

Closing this issue as a duplicate, so please follow up on it for further updates.
