### ISSUE TITLE
TextField Cursor in persian language

### ISSUE THREAD

**Issue by HosseinAsadi** [flutter/flutter#122545]
Hello
 
TextField widget have a problem in persian(or arabic) language

problem is when we type a persian text in it, after moving the cursor with clicking on part of text then we try to move cursor to end of text but it is impossible!!!

you can see below image, when try move cursor to end of text with clicking

![Screen Shot 2023-03-13 at 10 29 58 PM](https://user-images.githubusercontent.com/41711646/224802955-dcdb995e-0015-476b-b02e-294206db6473.png)

`flutter --version`

Flutter 3.3.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b8f7f1f986 (4 months ago) • 2022-11-23 06:43:51 +0900
Engine • revision 8f2221fbef
Tools • Dart 2.18.5 • DevTools 2.15.0

**Please, if possible, solve this problem by force**

**Comment by parsa10** [comment]
I was able to reproduce this issue 
`flutter --version`

Framework • revision 2ad6cd72c0 (5 days ago) • 2023-03-08 09:41:59 -0800
Engine • revision 1837b5be5f
Tools • Dart 2.19.4 • DevTools 2.20.1

**Comment by NavidHosseini** [comment]
I solve this bug  check my answer in stackoverflow...
please if helps you rate my answer, Thanks.

[[Bug in Flutter, while editing text in RTL languages](https://stackoverflow.com/questions/72726230/bug-in-flutter-while-editing-text-in-rtl-languages)](https://stackoverflow.com/questions/72726230/bug-in-flutter-while-editing-text-in-rtl-languages/72852349#72852349)

**Comment by mahdiramezani-mr** [comment]
Hi
This bug is in stable channel. I fixed that with switch to master.
I hope it's useful for you (:

**Comment by darshankawar** [comment]
@HosseinAsadi 
On which platform are you seeing this behavior ? (web, desktop or mobile) ?

I used below code sample and ran on mobile (ios and android) using latest master and confirmed that the behavior doesn't occur.

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: Scaffold
      (body: Center(child: TextFormField(
      textDirection: TextDirection.rtl,
    ))));
  }
}
```


https://user-images.githubusercontent.com/67046386/224928807-a836ef0b-a8a9-478c-a7bc-04096fbc690c.mov


https://user-images.githubusercontent.com/67046386/224928836-54287491-05eb-4098-9853-3a113a18ff90.mov

If you are seeing this behavior on web, then there's an already similar open issue describing your case, https://github.com/flutter/flutter/issues/120604 in which you can follow-up for further updates.

Also see this similar issue for your reference: https://github.com/flutter/flutter/issues/81013

So follow-up in these issues for further updates. Closing this in favor of the linked issues. If you disagree, write in comments and I'll reopen it.
