### ISSUE TITLE
Engine CI iOS simulator tests fail on arm64 bots

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#122534]
https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Unopt/26491/overview

It looks like `flutter/testing/ios/IosUnitTests` is failing to build due to missing symbols:
```
ld: warning: ignoring file ../../../../out/ios_debug_sim/libocmock_shared.dylib, building for iOS Simulator-arm64 but attempting to link with file built for iOS Simulator-x86_64
ld: warning: ignoring file ../../../../out/ios_debug_sim/libios_test_flutter.dylib, building for iOS Simulator-arm64 but attempting to link with file built for iOS Simulator-x86_64
Undefined symbols for architecture arm64:
  "_FlutterMethodNotImplemented", referenced from:
      ___48-[FlutterChannelsTest testMethodInvokeWithReply]_block_invoke_2 in FlutterChannelsTest.o
  "_OBJC_CLASS_$_FlutterBasicMessageChannel", referenced from:
      objc-class-ref in FlutterChannelsTest.o
  "_OBJC_CLASS_$_FlutterEventChannel", referenced from:
      objc-class-ref in FlutterChannelsTest.o
  "_OBJC_CLASS_$_FlutterMethodCall", referenced from:
      objc-class-ref in FlutterChannelsTest.o
  "_OBJC_CLASS_$_FlutterMethodChannel", referenced from:
      objc-class-ref in FlutterChannelsTest.o
  "_OBJC_CLASS_$_OCMArg", referenced from:
      objc-class-ref in FlutterChannelsTest.o
  "_OBJC_CLASS_$_OCMMacroState", referenced from:
      objc-class-ref in FlutterChannelsTest.o
  "_OBJC_CLASS_$_OCMockObject", referenced from:
      objc-class-ref in FlutterChannelsTest.o
  "_OCMIsObjectType", referenced from:
      -[FlutterChannelsTest testMethodInvoke] in FlutterChannelsTest.o
      -[FlutterChannelsTest testMethodInvokeWithReply] in FlutterChannelsTest.o
      -[FlutterChannelsTest testMethodMessageHandler] in FlutterChannelsTest.o
      -[FlutterChannelsTest testCallMethodHandler] in FlutterChannelsTest.o
      -[FlutterChannelsTest testBasicMessageChannelCleanup] in FlutterChannelsTest.o
      -[FlutterChannelsTest testMethodChannelCleanup] in FlutterChannelsTest.o
      -[FlutterChannelsTest testBasicMessageChannelTaskQueue] in FlutterChannelsTest.o
      ...
  "_OCMMakeLocation", referenced from:
      -[FlutterChannelsTest testMethodInvoke] in FlutterChannelsTest.o
      -[FlutterChannelsTest testMethodInvokeWithReply] in FlutterChannelsTest.o
      -[FlutterChannelsTest testMethodMessageHandler] in FlutterChannelsTest.o
      -[FlutterChannelsTest testResize] in FlutterChannelsTest.o
      -[FlutterChannelsTest testBasicMessageChannelCleanup] in FlutterChannelsTest.o
      -[FlutterChannelsTest testMethodChannelCleanup] in FlutterChannelsTest.o
      -[FlutterChannelsTest testBasicMessageChannelTaskQueue] in FlutterChannelsTest.o
      ...
ld: symbol(s) not found for architecture arm64
```

It looks like @jmagman might be familiar with this area. cc @godofredoc

**Comment by jmagman** [comment]
Mac Unopt would need to be updated to build arm64 host `--mac-cpu=arm64` and simulator `--simulator-cpu=arm64` variants, and the test updated to use them.

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8786989403765787713/+/u/test:_Host_Tests_for_ios_debug_sim/execution_details#L25109_6

```patch
   '--variant',
-  'ios_debug_sim',
+  'ios_debug_sim_arm64',
   '--type',
   'objc',
   '--engine-capture-core-dump',
   '--ios-variant',
-  'ios_debug_sim',
+  'ios_debug_sim_arm64',
```

**Comment by chinmaygarde** [comment]
This a fairly high priority since we are not able to use available CI capacity.

**Comment by dnfield** [comment]
Taking a stab at doing something like this here: https://github.com/flutter/engine/pull/41141/

AFAIU this will schedule both x86 and arm64 builds. I'm not sure if that's the behavior we really want or not. There are some tests though that can fail in one case and not the other, and it'd be sad to miss those. OTOH it requires more capacity.

https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20mac_unopt/105/overview is the build itlaunch, which seems to have launched sensible subbuilds, but will have to see if they complete. We may run into issues because the `host_debug_unopt_arm64` builds don't actually set `enable_unittests` to true right now.

**Comment by dnfield** [comment]
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8783978260989136769/+/u/test:_Tests_for_ios_debug_sim_arm64/stdout successfully ran the ios arm64 tests.

**Comment by dnfield** [comment]
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8783978260989136785/+/u/test:_Host_Tests_for_host_debug_unopt_arm64/stdout failed to run host tests because we're not setting `enable_unittests` to true. I'll look into that later.

**Comment by dnfield** [comment]
Updated https://github.com/flutter/engine/pull/41141 to Not try to run host tests for now, that can be added back in when https://github.com/flutter/flutter/issues/103386 is fixed.

**Comment by jmagman** [comment]
> Updated [flutter/engine#41141](https://github.com/flutter/engine/pull/41141) to Not try to run host tests for now, that can be added back in when #103386 is fixed.

I don't think gen_snapshot is going to be run natively on arm any time soon.  I don't quite understand why the tests wouldn't run on arm Macs though other than the tests not actually being generated.  @dnfield can you file an issue with your findings?

**Comment by dnfield** [comment]
The challenge wasn't so much around gen_snapshot but around building and running the host unittests. I'll file an issue.
