### ISSUE TITLE
request and response section of network tab inside devtools always shows blank

### ISSUE THREAD

**Issue by dipakp2726** [flutter/flutter#122511]
## Steps to Reproduce

#121133 its still happen

**Comment by exaby73** [comment]
Hello @dipakp2726. I am unable to reproduce this issue. Can you reproduce this on the master channel? You can use https://jsonplaceholder.typicode.com/ for your HTTP request

**Comment by dipakp2726** [comment]
not on master channel but its happening on stable and beta channel.

**Comment by exaby73** [comment]
Then this issue is fixed in master. It will be included as a fix to a future stable version. Since it's fixed, there is nothing to do currently than wait for the fix to be released. Therefore, I am closing this issue

**Comment by dipakp2726** [comment]
where can we expect this to be released?

can't we cherry-pick this from master

**Comment by exaby73** [comment]
Please see https://github.com/flutter/flutter/wiki/Flutter-build-release-channels for more information
