### ISSUE TITLE
Migrate CI_YAML.md to GitHub wiki

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#122552]
This file rarely changes, but contains useful information. We should migrate it to the GitHub wiki to make it easier to update, and easier to discover.

Afterwards, we'll need to update all ci.yamls to point to the new wiki link

**Comment by CaseyHillers** [comment]
@keyonghan this was a recommendation from @zanderso. Does this proposal sound good to you?

From experience, I have to link people here quite often to answer questions, and the wiki might be able to help.

**Comment by godofredoc** [comment]
Docs were added to single page index instead https://github.com/flutter/flutter/wiki/Flutter-Self-Service-Index
