### ISSUE TITLE
Flutter Inappwebview browser website block error

### ISSUE THREAD

**Issue by cricmazza** [flutter/flutter#122524]
I create my website web app in flutter. when i open my website Flutter Inappwebview block my website. what I do.

![WhatsApp Image 2023-03-13 at 7 27 05 PM](https://user-images.githubusercontent.com/88313570/224725677-0021311f-99fd-41c3-941c-59833a0f05e1.jpeg)

**Comment by stuartmorgan** [comment]
It looks like your site's host is blocking browsers based on user agents. You'll need to contact them for support; Flutter can't control the behavior of the hosting service.
