### ISSUE TITLE
[google_sign_in] [web] Logout does not work

### ISSUE THREAD

**Issue by radvansky-tomas** [flutter/flutter#122668]
Logout on WEB platform does not actually logout user from google account.

So next login via google results in instant login (without option to select another account).

Guides online suggest to use google sign-in plugin to logout before firebase auth logout function.
However this is not applicable for WEB, as we do not have clientId present!

Based on current  docs to login via google on web platform we use google provider:
```
 final GoogleAuthProvider googleProvider = GoogleAuthProvider();

        googleProvider.addScope('email');

        //  googleProvider.setCustomParameters({'login_hint': 'user@example.com'});

        return await _auth.signInWithPopup(googleProvider);
```

So there is not even use of google sign in plugin, and if we try to use it it fails with clientId is not being set. 
Which obviously can work on native platform with plist/json files present!

**Comment by huycozy** [comment]
I've tried verifying this with [google_sign_in's example](https://github.com/flutter/plugins/tree/main/packages/google_sign_in/google_sign_in/example) but it still works as expected on Chrome.

What is your current plugin version? Please try using google_sign_in's example on the latest plugin version to see if the issue still persists or not. Also, please provide the output of flutter doctor -v as well.

**Comment by radvansky-tomas** [comment]
This is not the same, this is docs and example for flutter/firebase:
https://firebase.google.com/docs/auth/flutter/federated-auth#web

```
Future<UserCredential> signInWithGoogle() async {
  // Create a new provider
  GoogleAuthProvider googleProvider = GoogleAuthProvider();

  googleProvider.addScope('https://www.googleapis.com/auth/contacts.readonly');
  googleProvider.setCustomParameters({
    'login_hint': 'user@example.com'
  });

  // Once signed in, return the UserCredential
  return await FirebaseAuth.instance.signInWithPopup(googleProvider);

  // Or use signInWithRedirect
  // return await FirebaseAuth.instance.signInWithRedirect(googleProvider);
}
```

This does not use google_sign_in plugin or any of its implementation at least i cant tell from this code.

Native part, yes for sure:
```
import 'package:google_sign_in/google_sign_in.dart';

Future<UserCredential> signInWithGoogle() async {
  // Trigger the authentication flow
  final GoogleSignInAccount? googleUser = await GoogleSignIn().signIn();

  // Obtain the auth details from the request
  final GoogleSignInAuthentication? googleAuth = await googleUser?.authentication;

  // Create a new credential
  final credential = GoogleAuthProvider.credential(
    accessToken: googleAuth?.accessToken,
    idToken: googleAuth?.idToken,
  );

  // Once signed in, return the UserCredential
  return await FirebaseAuth.instance.signInWithCredential(credential);
}
```

**Comment by radvansky-tomas** [comment]
All I am saying is that first web example and NOT using google_sign_in instance, expectation is that 
flutter auth instance logout /sign out method -> should logout all providers including google.

But what is happening is that
- user is logged out
- listener is correctly triggered with NULL event

But with subsequent login via google, google account is still connected. And there is auto-login with previous account

**Comment by huycozy** [comment]
>All I am saying is that first web example and NOT using google_sign_in instance, expectation is that
flutter auth instance logout /sign out method -> should logout all providers including google.

Thanks for your response, but since you don't use `google_sign_in` plugin on Web, but `firebase_auth` (from your documentation url above, which is a 3rd party plugin), I would suggest you file a new issue on [flutterfire repository](https://github.com/firebase/flutterfire) for better support there. 

Closing as it's not Flutter or 1st party plugin's issue.
