### ISSUE TITLE
FlutterFragmentActivity Splash Screen onFlutterUiDisplayed alternative?

### ISSUE THREAD

**Issue by abhineetchandan** [flutter/flutter#122688]
## Steps to Reproduce
**Problem**

So, I am trying to change `FlutterActivity` to `FlutterFragmentActivity` because `FlutterFragmentActivity` only supports features like view binding etc. My existing `FlutterActivity` supports overriding `onFlutterUiDisplayed` to handle splash screen changes. But after reading the Java doc of `FlutterFragmentActivity`, there is no porting of those functionalities. So, can anyone please tell me the alternative of onFlutterUiDisplayed in FlutterFragmentActivity?
```dart
class MainActivity : FlutterFragmentActivity(), EventChannel.StreamHandler, MethodCallHandler {
    
   override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
        methodChannel = MethodChannel(flutterEngine.dartExecutor.binaryMessenger, channelTag)
        methodChannel.setMethodCallHandler { call, result -> onMethodCall(call, result) }
        eventChannel = EventChannel(flutterEngine.dartExecutor.binaryMessenger, eventTag)
        eventChannel!!.setStreamHandler(this)
        MainActivity.methodChannel = methodChannel
        MainActivity.flutterEngine = flutterEngine
      }

//This is not available in Flutter Fragment Activity
    override fun onFlutterUiDisplayed() {
        super.onFlutterUiDisplayed()
        flutterUiReady = true;
        Log.d("OnFlutterUiDisplayed", "OnFlutterUiDisplayed");
        if (initialAnimationFinished) {
            Log.d("InitiatingAnimation", "OnFlutterUiDisplayed");
            splashScreenFinish()
        }
    }
}
...Other code
```

**Comment by huycozy** [comment]
Hi @abhineetchandan 
I also see [`FlutterFragmentActivity`](https://github.com/flutter/engine/blob/main/shell/platform/android/io/flutter/embedding/android/FlutterFragmentActivity.java) doesn't have `onFlutterUiDisplayed` but `FlutterFragment` does. 

Can you be more specific about view binding that cannot be achieved on FlutterActivity?

**Comment by abhineetchandan** [comment]
@huycozy  I managed to solve that issue but when using `FlutterFragmentActivity` with the `local-auth` plugin, following its documentation of setup,  I have to replace FlutterActivity with FlutterFragmentActivity and if I did that i can't know when the Flutter UI is ready to render. **So, the actual question is, Is there any specific method which can be used to know if the Flutter UI is ready to display in FlutterFragmentActivity?**

**Comment by huycozy** [comment]
Can you try this way and check if it works for your case?

```kotlin
class MainActivity : FlutterFragmentActivity() {

    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
        flutterEngine.renderer.addIsDisplayingFlutterUiListener(object : FlutterUiDisplayListener {
            override fun onFlutterUiDisplayed() {
                TODO("Not yet implemented")
            }

            override fun onFlutterUiNoLongerDisplayed() {
                TODO("Not yet implemented")
            }
        })
    }
}
```

**Comment by abhineetchandan** [comment]
@huycozy yep. that's what I was looking for. Thanks so much. Will close the issue now.
