### ISSUE TITLE
Add configurable cleanup step to packages recipe

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#122629]
The flutter/packages repo uses a dynamic recipe, which loads and runs steps from a yaml file in the repo. As soon as the first step fails, the rest of the steps aren't run. That's usually what we want, but https://github.com/flutter/packages/pull/3458 is an example of a case where we want to run regardless. When we migrate Linux tasks from Cirrus to LUCI we'll have more (see use of `always:` in the repo's current ci.yml).

We should have some way of doing this that's equally dynamic and in-repo. Maybe via an annotation in the yaml file, or maybe a second .ci.yaml property with a second yaml file of "always"-style tasks.

@keyonghan Is this something you could help set up? I don't know enough about recipes to know how to configure this.

**Comment by keyonghan** [comment]
> That's usually what we want, but https://github.com/flutter/packages/pull/3458 is an example of a case where we want to run regardless.

For this case, do we want to mark the whole task as failure or success? Do we want to have this fail but continue run logic on only specific test step, or for all always?

**Comment by stuartmorgan** [comment]
There are two use cases we have for `always` in Cirrus currently:
- Things that should run at the end even if earlier steps failed (like the PR linked above).
- Tests we just always want to run (e.g., `repo_tests` is a bunch of very fast, unrelated tests, and we want to get all failures from all of them at once rather than always only seeing the first thing, fixing it, getting a new failure, fixing it, etc.)

Currently we do both with `always` since that's the only mechanism we have, but if it's easy for them to be different in LUCI that could be nice.

> do we want to mark the whole task as failure or success

I would want any failure, even if it's just cleanup, to mark the whole task as failing. Otherwise we'll never noticed if important cleanup is broken.

**Comment by keyonghan** [comment]
First case is clear to me.

As for the second, take the `repo_checks` task for example, I see `always` is applied to all scripts. Does that mean any script failure will not block any one else, and the task fails when any one of them fails?

**Comment by stuartmorgan** [comment]
> Does that mean any script failure will not block any one else, and the task fails when any one of them fails?

Yes, exactly.

**Comment by keyonghan** [comment]
I guess this should be doable.
From the `config yaml file` side, we can add one more entry: `always: true/false` for each test step.
From `recipes` side, when iterating each test step

- if we hit an error
  - check remaining steps which have `always: true`, and keep finish running them
  - return failure for the whole task
- if we didn't hit any error, we just treat all test steps the same as regular steps

**Comment by keyonghan** [comment]
This is now complete with https://flutter-review.googlesource.com/c/recipes/+/46041.
