### ISSUE TITLE
image_picker_ios Choose a picture to report an error "invalid_image, Cannot load representation of type public.jpeg, NSItemProviderErrorDomain"

### ISSUE THREAD

**Issue by MeiYuLong** [flutter/flutter#122604]
image_picker_ios 
An error is reported when selecting a picture on the simulator
"invalid_image, Cannot load representation of type public.jpeg, NSItemProviderErrorDomain"

`XFile? image = await _imagePicker.pickImage(source: source, imageQuality: 50).catchError((error) {
      print('pickImage ${error.toString()}');
    });`

![image](https://user-images.githubusercontent.com/20105390/225025146-7a33facd-2435-46ba-a16d-24ec567e4677.png)

Use the same error as the official Demo.
How to deal with it！！！ Thanks！！！

**Comment by MeiYuLong** [comment]
this image is HDR

**Comment by darshankawar** [comment]
@MeiYuLong 
Thanks for the report. I think your issue is similar to https://github.com/flutter/flutter/issues/117240 so please follow-up in it for further updates. I'll close this as a duplicate.

**Comment by vashworth** [comment]
The issue described is a known issue of Apple's simulators (63426347). According to Apple, it's only an issue on the simulator, physical devices should work fine.
https://developer.apple.com/forums/thread/665265
