### ISSUE TITLE
Consider providing an alternative to NetworkImage

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#12266]
NetworkImage is perhaps a poor example of how Flutter code should work, because it schedules work from within the build() function.  A better pattern might be to have a separate explicit loader (which might allow for easy pre-loading of images or waiting on their loads for example) which then called setState on some other Image Widget.  (Maybe this pattern already exists and I'm just not aware of good examples of it?)

NetworkImage also has some non-mobile-typical behaviors of not requiring a size for your "image view" a priori, causing a web-like "pop-in" effect as images load which has confused previous Flutter developers (including Posse).

If we had a separate/improved pattern, we could consider moving NetworkImage out of package:flutter proper and thus (I believe) remove our package:http dependency in package:flutter.

I understand we've declared API stability, and thus we may be stuck with NetworkImage (and thus never get to remove our package:http dependency), but if we believe NetworkImage is a bad pattern or footgun (for the reasons above) we can at least provide a recommended alternative.

Thoughts?  @yjbanov @Hixie

**Comment by sethladd** [comment]
See also https://github.com/flutter/flutter_image

**Comment by yjbanov** [comment]
> because it schedules work from within the build() function

This scheduling is idempotent though. It won't schedule new work if the loading parameters are the same. This makes it compatible with the semantics of the build() function. However, kicking off network requests as a side-effect of a constructor call does indeed smell, and also reduces the amount of control a developer has over the image loading process. So, I'd be in favor of improving the design.

> I understand we've declared API stability, and thus we may be stuck with NetworkImage (and thus never get to remove our package:http dependency)

We can move to `dart:io` and remove the `package:http` dependency. The only breaking change AFAICT would be the removal of `createHttpClient`, which leaks `package:http` to our public API. We'd still need some abstraction for tests to stub out network access.

**Comment by sethladd** [comment]
> We'd still need some abstraction for tests to stub out network access.

@zanderso is working on a proposal, afaik

**Comment by Hixie** [comment]
> NetworkImage is perhaps a poor example of how Flutter code should work, because it schedules work from within the build() function. 

Why is this bad? We do this in various places. So long as it's idempotent, it's fine, no?

**Comment by eseidelGoogle** [comment]
My understanding was that this was one of the "bad patterns" (also common in web apps) which you had identified when troubleshooting Posse's launch/loading screen "jank".  If I recall correctly, it was suggested at that time that in most cases it's better to separate loading from display?

**Comment by Hixie** [comment]
It's fine to schedule work in the build function if it doesn't block additional work. The problem in the app you're referring to was that the build function would schedule work, and then not allow anything else to build in the meantime, so the next chunk of work couldn't start until the first chunk had finished.

**Comment by zanderso** [comment]
I'm working on dart:io mocking support here: https://dart-review.googlesource.com/#/c/sdk/+/3302/. Currently iterating on it with @floitschG.

**Comment by Hixie** [comment]
I'm going to close this PR in favour of more specific requests like https://github.com/flutter/flutter/issues/9676.
