### ISSUE TITLE
please provide something like setRoundingMode in numberformat

### ISSUE THREAD

**Issue by mahdiqdi** [flutter/flutter#122627]
in java we have a method that let us to change rounding mode
i have a numbers with different decimals but rounding the last decimal is really annoying.
please help me with my problem

**Comment by huycozy** [comment]
Hi @mahdiqdi
As I can see, you can use `.ceil()` or `.floor()` directly for your case.

Your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any. 
Instead, if you propose a method exactly the same as `setRoundingMode()` in Java, please file a new issue in [dart-lang/sdk](https://github.com/dart-lang/sdk) for better support. 

Closing, as this isn't an issue with Flutter itself. Thanks!
