### ISSUE TITLE
[Impeller] Matrix filter: Don't render to snapshot

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#122660]
For the matrix filters, there's no longer any need to render to a snapshot. Instead, we should just be able to manipulate the Entity transform, and ask the FilterInput to produce a new entity that can render the result, and return that instead.

**Comment by ColdPaleLight** [comment]
Although the performance will indeed be better if this is done, I am afraid that if this is done, the following issue will occur again https://github.com/flutter/engine/pull/36193#discussion_r975995020 . Let me know if I missed something.

**Comment by bdero** [comment]
Ah right, I forgot about this behavior... I think this situation is probably as efficient as it can be at the moment, given all of the snapshot passthrough optimizations in place at this point. If we were to chain multiple matrix filters together, we should still only get the one additional subpass to render the input.
