### ISSUE TITLE
In a TextFormField, ⬅ moves left but ➡ does nothing

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#12260]
## Steps to Reproduce

In the iOS simulator, I can use the left arrow key to move left in text fields. The right arrow key does nothing. I expected it to move right.

Reduced test case:
```
import 'package:flutter/material.dart';

void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: new MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: new Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          new TextFormField(),
        ],
      ),
    );
  }
}
```

[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-US, channel unknown)
    • Flutter at /Users/jackson/git/flutter
    • Framework revision bb0a724a1d (13 minutes ago), 2017-09-26 09:12:40 -0700
    • Engine revision 005212683c
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /Users/jackson/Library/Android/sdk
    • Platform android-26, build-tools 26.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    ✗ libimobiledevice and ideviceinstaller are not installed or require updating. To update, run:
        brew uninstall --ignore-dependencies libimobiledevice
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2.4)
    • Flutter plugin version 17.0
    • Dart plugin version 172.4155.35

[✓] Connected devices
    • SM G930V      • caef18a6                             • android-arm • Android 7.0 (API 24)
    • iPhone 7 Plus • A712DA0B-FEBD-4746-9BAF-45ECE15EDDBA • ios         • iOS 10.3 (simulator)

**Comment by cbracken** [comment]
Fixed by flutter/engine#4319 rolled to framework by #12853
