### ISSUE TITLE
How to create a List of VideoPlayer widgets in Flutter?

### ISSUE THREAD

**Issue by bestofman** [flutter/flutter#122631]
***I uploaded the complete application code*** [here][1]. The problem with this application is that the `Next` and `Back` buttons don't work as expected! 

I am trying to create a `List<VideoPlayer>` with the help of a multi step Flutter `Form`. In each form user picks a video file using `file_picker()`, then clicks on `Next` and can do the same step as much as he wants. So the application should create a List of videos navigatable by clicking `Next`/`Back` buttons.

  [1]: https://github.com/bestofman/test

    upload_movie.dart:
    
    import 'dart:io';
    import 'dart:typed_data';
    import 'package:file_picker/file_picker.dart';
    import 'package:flutter/material.dart';
    import 'package:provider/provider.dart';
    import 'package:test/movie_create.dart';
    
    import 'video_player_widget.dart';
    
    List<File>? videoFileShow = [];
    List<String>? fileName = [];
    List<String>? fileType = [];
    
    class UploadPage extends StatefulWidget {
      const UploadPage({super.key});
      static const routeName = '/contests-form-video-upload';

    
      @override
      State<UploadPage> createState() => _UploadPageState();
    }
    
    class _UploadPageState extends State<UploadPage> {
      final GlobalKey<FormState> _formKey = GlobalKey<FormState>();
    
      @override
      Widget build(BuildContext context) {
        var movie = Provider.of<MovieCreate>(context, listen: false);

    
        return Column(
          children: [
            Container(
                padding: const EdgeInsets.all(15),
                child: const Text('Please choose the video to upload')),
            Expanded(
              flex: 3,
              child: Form(
                key: _formKey,
                child: Padding(
                  padding: const EdgeInsets.all(10),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Container(
                        child: videoFileShow == null ||
                                videoFileShow!.length <= movie.videoIndex
                            ? Image.asset('assets/images/video-placeholder.jpg')
                            : VideoPlayerWidget(
                                index: movie.videoIndex,
                                path: videoFileShow![movie.videoIndex]),
                      ),
                      Column(
                        crossAxisAlignment: CrossAxisAlignment.stretch,
                        children: [
                          ElevatedButton(
                            style: ElevatedButton.styleFrom(
                              foregroundColor: Colors.white,
                              backgroundColor:
                                  movie.videos![movie.videoIndex].videoUrl !=
                                                  null &&
                                              movie.videos![movie.videoIndex]
                                                  .videoUrl!.isNotEmpty ||
                                          videoFileShow!.length > movie.videoIndex
                                      ? Theme.of(context).highlightColor
                                      : Theme.of(context).primaryColor,
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(5),
                              ),
                            ),
                            onPressed: () async {
                              FilePickerResult? result = await FilePicker.platform
                                  .pickFiles(
                                      allowMultiple: false, type: FileType.video);
    
                              if (result != null) {
                                PlatformFile pFile = result.files.first;
                                File fFile = File(pFile.path.toString());
                                Uint8List newFile = await fFile.readAsBytes();
    
                                setState(() {
                                  videoFileShow!.add(fFile);
                                  fileName!.add(result.files.first.name);
                                  fileType!.add(
                                      fileName![movie.videoIndex].split('.').last);
                                });
                              }
                            },
                            child: Text('Upload video'),
                          ),
                        ],
                      )
                    ],
                  ),
                ),
              ),
            ),
            Padding(
              padding: EdgeInsets.all(10),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Expanded(
                    flex: 1,
                    child: ElevatedButton(
                      style: ElevatedButton.styleFrom(
                        foregroundColor: Colors.white,
                        backgroundColor: Theme.of(context).primaryColor,
                        disabledBackgroundColor: Theme.of(context).disabledColor,
                        disabledForegroundColor: Theme.of(context).primaryColor,
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(10),
                        ),
                      ),
                      onPressed: () {
                        if (movie.videoIndex == 0) {
                          setState(() {
                            movie.changeStep(0);
                          });
                        } else {
                          setState(() {
                            movie.changeVideoIndex(--movie.videoIndex);
                            movie.changeStep(1);
                          });
                        }
                      },
                      child: Text('Back'),
                    ),
                  ),
                  const SizedBox(
                    width: 20,
                  ),
                  Expanded(
                    flex: 1,
                    child: ElevatedButton(
                      style: ElevatedButton.styleFrom(
                        foregroundColor: Colors.white,
                        backgroundColor: Theme.of(context).primaryColor,
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(10),
                        ),
                      ),
                      onPressed: () {
                        if (videoFileShow != null &&
                            videoFileShow![movie.videoIndex].path.isNotEmpty) {
                          setState(() {
                            movie.changeVideoIndex(++movie.videoIndex);
                            if (movie.videoIndex + 1 > movie.videos!.length) {
                              movie.videos!.add(MovieVideo());
                            }
                            movie.changeStep(1);
                          });
                        }
                      },
                      child: Text('Next'),
                    ),
                  ),
                ],
              ),
            ),
          ],
        );
      }
    }

video_player_widget.dart:

    import 'dart:io';
    import 'package:flutter/material.dart';
    import 'package:video_player/video_player.dart';
    
    import 'video_player_base_widget.dart';
    
    int? videoIndex;
    File? videoPath;
    List<VideoPlayerController> controllers = [];
    
    class VideoPlayerWidget extends StatefulWidget with ChangeNotifier {
      File path;
      int index;
      VideoPlayerWidget({Key? key, required this.index, required this.path})
          : super(key: key) {}
    
      @override
      State<VideoPlayerWidget> createState() => _VideoPlayerWidgetState();
    }
    
    class _VideoPlayerWidgetState extends State<VideoPlayerWidget> {
      @override
      void initState() {
        super.initState();
        videoIndex = widget.index;
        videoPath = widget.path;
        if (videoIndex! + 1 > controllers.length) {
          controllers.add(VideoPlayerController.file(videoPath!));
        }
        controllers[videoIndex!] = VideoPlayerController.file(videoPath!)
          ..addListener(() => setState(() {}))
          ..setLooping(false)
          ..initialize().then((_) => controllers[videoIndex!].pause());
      }
    
      @override
      void dispose() {
        super.dispose();
        controllers[videoIndex!].dispose();
      }
    
      @override
      Widget build(BuildContext context) {
        return Container(
          alignment: Alignment.center,
          child: Column(children: [
            VideoPlayerBaseWidget(controller: controllers[videoIndex!]),
          ]),
        );
      }
    }

movie_create.dart:

    import 'package:flutter/foundation.dart';
    
    class MovieCreate with ChangeNotifier {
      List<MovieVideo>? videos = [];
      int activeIndex = 0;
      int videoIndex = 0;
    
      changeVideoIndex(int index) {
        videoIndex = index;
        notifyListeners();
      }
    
      changeStep(int index) {
        activeIndex = index;
        notifyListeners();
      }
    }
    
    class MovieVideo {
      String? videoUrl;
    }

**Comment by darshankawar** [comment]
@bestofman 
Your question is better suited for support channels like StackOverflow, so please ask this question there.
Closing from here, as this repo is not to provide code assistance.

**Comment by bestofman** [comment]
> @bestofman Your question is better suited for support channels like StackOverflow, so please ask this question there. Closing from here, as this repo is not to provide code assistance.

I have asked my question over there but nobody answered it as well!

https://stackoverflow.com/questions/75730093/how-to-create-a-list-of-videoplayer-widgets-in-flutter
