### ISSUE TITLE
MissingPluginException(No implementation found for method share on channel plugins.flutter.io/share)

### ISSUE THREAD

**Issue by arnoldparge** [flutter/flutter#12264]
## Steps to Reproduce

Added share plugin

## Logs

caught exception:

`MissingPluginException(No implementation found for method share on channel plugins.flutter.io/share)`

## Flutter Doctor

[√] Flutter (on Microsoft Windows [Version 10.0.15063], locale en-IN, channel unknown)
    • Flutter at C:\Users\username\flutter\flutter
    • Framework revision 1c372c6803 (4 weeks ago), 2017-08-31 15:54:45 -0700
    • Engine revision f9e00a7c72
    • Tools Dart version 1.25.0-dev.11.0

[√] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at C:\Program Files (x86)\Android\android-sdk
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = C:\Program Files (x86)\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 17.0
    • Dart plugin version 172.3968.27

[√] Connected devices
    • GT I9152 • **** • android-arm • Android 4.2.2 (API 17)

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by Hixie** [comment]
cc @mravn-google

**Comment by mravn-google** [comment]
The `share` plugin works as intended. The error probably appears because the addition of the plugin was followed by hot restart or hot reload rather than full restart. This means the plugin's platform-specific code is not built into the app.

Work around: stop the app and restart it after adding a plugin.

Documentation PR: https://github.com/flutter/website/pull/1038

**Comment by marksheekey** [comment]
I get this error, even after a complete restart.

**Comment by FlutterAddict** [comment]
I get this error after complete restart too.

**Comment by Navil** [comment]
I have the same error. I tried restarting and even reinstalling the application.

**Comment by krish30393** [comment]
I have the same issue .
I tried **remove application completely **   then  **flutter clean**  then **reinstall**   
solved

**Comment by mcmikecreations** [comment]
Still cannot run latest version of the plugin

**Comment by CedYF** [comment]
This also breaks even after restarting and re-installing my app for me.

**Comment by Onus31** [comment]
MissingPluginException(No implementation found for method shareFile on channel plugins.flutter.io/share)

**Comment by ospar0829** [comment]
This also breaks even after flutter clean, restarting and re-installing the app

**Comment by wandriputra** [comment]
flutter clean not work for me

**Comment by Daniel-Sogbey** [comment]
run :

flutter clean

after that run:

flutter pub get

**Comment by Daniel-Sogbey** [comment]
> flutter clean not work for me

run :

flutter clean

after that run:

flutter pub get

**Comment by Daniel-Sogbey** [comment]
> This also breaks even after flutter clean, restarting and re-installing the app

run :

flutter clean

after that run:

flutter pub get

**Comment by Daniel-Sogbey** [comment]
> This also breaks even after restarting and re-installing my app for me.
run :

flutter clean

after that run:

flutter pub get

**Comment by Daniel-Sogbey** [comment]
> I get this error after complete restart too.

run :

flutter clean

after that run:

flutter pub get

**Comment by foxsofter** [comment]
```java
  @Override
  public void onAttachedToActivity(ActivityPluginBinding binding) {
    share.setActivity(binding.getActivity());
  }
```
Change to the following code and it will work

```java
  @Override
  public void onAttachedToActivity(ActivityPluginBinding binding) {
    share.setActivity(binding.getActivity());
    methodChannel.setMethodCallHandler(handler);
  }
```

**Comment by gitcarlosandrade** [comment]
Hello everyone!

I am also struggling with this error.

I have two native projects (Kotlin and Swift) with an add-2-app module.

The lib share (0.6.5) works well after a cold startup of the application, but after I get back from the FlutterActivity intent by the back button (Android), this error occurs until a new cold startup.

This bug is consistent. Every moment that i get back from FlutterActivity.

Someone in the same scenario?

**Comment by Spinthecode** [comment]
> 
> 
> ```java
>   @Override
>   public void onAttachedToActivity(ActivityPluginBinding binding) {
>     share.setActivity(binding.getActivity());
>   }
> ```
> 
> Change to the following code and it will work
> 
> ```java
>   @Override
>   public void onAttachedToActivity(ActivityPluginBinding binding) {
>     share.setActivity(binding.getActivity());
>     methodChannel.setMethodCallHandler(handler);
>   }
> ```

In what file please?

**Comment by foxsofter** [comment]
> > ```java
> >   @Override
> >   public void onAttachedToActivity(ActivityPluginBinding binding) {
> >     share.setActivity(binding.getActivity());
> >   }
> > ```
> > 
> > 
> > Change to the following code and it will work
> > ```java
> >   @Override
> >   public void onAttachedToActivity(ActivityPluginBinding binding) {
> >     share.setActivity(binding.getActivity());
> >     methodChannel.setMethodCallHandler(handler);
> >   }
> > ```
> 
> In what file please?

https://github.com/flutter/plugins/blob/f7096d7d7be9883149a1fb6cebfaa6ff85fb01a5/packages/share/android/src/main/java/io/flutter/plugins/share/SharePlugin.java#L42

**Comment by gagan781992** [comment]
I have no such file in our project I am in the same error. Which is my thinking everything is right. what should I do now

**Comment by lordvidex** [comment]
Do not use any hack or touch the MainActivity.java file. Mostly, I noticed issues only from the Android side.. So,
1. Delete `android/`
2. run `flutter create .`  _<<This will generate normal gradle and kotlin setup that works if you are on the latest stable flutter version>>_
3. run `flutter clean && flutter pub get`
4. run the app
