### ISSUE TITLE
[Impeller] Gaussian Blur: Render the second pass directly to the parent pass.

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#122657]

**Comment by jonahwilliams** [comment]
This ends up being particularly important in the gallery, as almost every page has a shadow that doesn't hit one of the fast paths and ends up with the full gaussian blur.

**Comment by chinmaygarde** [comment]
@jonahwilliams (or was it @bdero): There was a point of discussion in the weekly about using Metal Performance Shaders in some cases. There was nuance that I was unable to capture in the meeting notes. Can we add that in here or in a separate issue so we don't lose track of it please?

**Comment by jonahwilliams** [comment]
IIRC the questions were:

1. Does the MPS cover all of our use cases? i.e. sampling options/radius configuration.
2. Does the MPS treat color spaces similar to existing flutter shaders. Something about gamma correct rendering. 😅

**Comment by chinmaygarde** [comment]
okie dokie. I filed https://github.com/flutter/flutter/issues/123472 just to track the MPS stuff. Having a portable solution seems like the thing to do still. But getting a baseline for performance from MPS might be valuable.

**Comment by jonahwilliams** [comment]
Agreed, ultimately we'll still have to come up with a fast enough solution for other platforms. Still, if its significantly fast it might be worth having at some point

**Comment by bdero** [comment]
Closing this. The solution to reduce passes turned out to be a false start that I should have realized when I suggested it; by doing this, we would lose our downscaling optimization on the second pass, which works out to be a cubic loss for fragment load w.r.t. sigma.
