### ISSUE TITLE
One or more plugins require a higher Android SDK version.

### ISSUE THREAD

**Issue by helloworkcupid** [flutter/flutter#122694]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

flutter run --no-sound-null-safety 

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 3.3.0-0.5.pre, on macOS 13.2 22D49 darwin-arm, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[!] Xcode - develop for iOS and macOS (Xcode 14.2)
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.75.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

### Actual results

Warning: The plugin path_provider_android requires Android SDK version 33.
For more information about build configuration, see https://docs.flutter.dev/deployment/android#reviewing-the-build-configuration.
Warning: The plugin shared_preferences_android requires Android SDK version 33.
For more information about build configuration, see https://docs.flutter.dev/deployment/android#reviewing-the-build-configuration.
One or more plugins require a higher Android SDK version.
Fix this issue by adding the following to /Users/cupid/androidProjects/zhaoShang/invest_moudle-master/sg_module/.android/Flutter/build.gradle:
android {
  compileSdkVersion 33
  ...
}

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by darshankawar** [comment]
@helloworkcupid 
As the message gives you solution on how to fix the log that you are seeing, you need to follow it and fix to see it working.

**Comment by helloworkcupid** [comment]
It was just an error caused by the upgrade of a plug-in. Later, I returned the upgrade, but the error was still there, which I could not understand. So, I don't think it's such a superficial reason.

**Comment by helloworkcupid** [comment]
> @helloworkcupid As the message gives you solution on how to fix the log that you are seeing, you need to follow it and fix to see it working.

It was just an error caused by the upgrade of a plug-in. Later, I returned the upgrade, but the error was still there, which I could not understand. So, I don't think it's such a superficial reason.

**Comment by darshankawar** [comment]
@helloworkcupid 
I see that you are on old version of beta. Maybe try to upgrade to latest master or stable version and make sure all of the plugins you are using are uptodate.
