### ISSUE TITLE
Release xcframework causes "all-product-headers.yaml not found"

### ISSUE THREAD

**Issue by jeremy-carbonne** [flutter/flutter#122605]
I include a flutter project in a native iOS app (from xcframework)

When I use breakpoints with debug xcframeworks everything works fine

But if I use release xcframeworks I get this error

```
error: virtual filesystem overlay file '/Users/{USERNAME}/{MY_PROJECT}/.output/ios-intermediates/Release/iphoneos/Pods.build/Release-iphoneos/camerax.build/all-product-headers.yaml' not found
error: couldn't IRGen expression. Please check the above error messages for possible root causes.
```

It seems that “all-product-headers.yaml” is added in the dsym files (with an absolute local path, which is not possible because I have to share this xcframework to third parties)

After i add
```'SWIFT_SERIALIZE_DEBUGGING_OPTIONS=NO',```
In flutter_tools/lib/src/commands/build_ios_framework.dart [here](https://github.com/flutter/flutter/blob/1306d7f1588c9de4c8534b90308494c3630a8c5a/packages/flutter_tools/lib/src/commands/build_ios_framework.dart#L498) and [here](https://github.com/flutter/flutter/blob/1306d7f1588c9de4c8534b90308494c3630a8c5a/packages/flutter_tools/lib/src/commands/build_ios_framework.dart#L524)

"all-product-headers.yaml' not found"  not appear anymore and everything seems to be working fine

## Steps to Reproduce

1. Generate xcframework, Execute `flutter build ios-framework --output=.output/ios-intermediates`
2. Import release xcframework to your native app
3. Add breakpoint, run app and hit breakpoint
4. In lldb terminal type command `po variable_name`

**Expected results:**
```
po variable_name
"variable_value"
```

**Actual results:** 
```
error: expression failed to parse:
error: virtual filesystem overlay file '/Users/{USERNAME}/{MY_PROJECT}/.output/ios-intermediates/Release/iphoneos/Pods.build/Release-iphoneos/camerax.build/all-product-headers.yaml' not found
error: virtual filesystem overlay file '/Users/{USERNAME}/{MY_PROJECT}/.output/ios-intermediates/Release/iphoneos/Pods.build/Release-iphoneos/camerax.build/all-product-headers.yaml' not found

error: couldn't IRGen expression. Please check the above error messages for possible root causes.
```

I have this error with several third-party libraries, not particularly with camerax
I think this problem only happens with libraries written in swift

Note: When we modify `flutter_tools/lib/src/commands/build_ios_framework.dart`,
this has no effect on the flutter command `flutter build ios-framework` , 
i used this command `dart ~/flutter/packages/flutter_tools/bin/flutter_tools.dart build ios-framework --output= ../.output/ios-intermediates`

**Comment by jeremy-carbonne** [comment]
Other issues that seem similar:

https://github.com/getsentry/sentry-unity/issues/1221
https://github.com/facebook/facebook-ios-sdk/issues/1628

which make me think that you should probably add "SWIFT SERIALIZE DEBUGGING OPTIONS=NO" while building xcframeworks

**Comment by darshankawar** [comment]
Thank for the report @jeremy-carbonne 
Can you provide us a sample repo that we can clone and run locally to verify this scenario ?



> 4\. In lldb terminal type command `po variable_name`

I am not too aware about this terminal and the command `po`, so please elaborate on this as well so that we can properly address the issue.
