### ISSUE TITLE
[Infra] Beta MacOS arm binaries not showing on docs.flutter.dev

### ISSUE THREAD

**Issue by itsjustkevin** [flutter/flutter#122769]
Since the release of the Flutter 3.8 beta, MacOS binaries have not been appearing on the [website](https://docs.flutter.dev/development/tools/sdk/releases?tab=macos) for the beta channel. 

The binaries are available for use however, and the normal flow of upgrading still works. 

To verify:
`flutter channel beta`
`flutter upgrade` 

You should be able to see the new flutter beta.

**Comment by godofredoc** [comment]
Does this work on an arm machine? it seems like the packages were never created for arm64

**Comment by christopherfujino** [comment]
> Does this work on an arm machine? it seems like the packages were never created for arm64

The engine binaries already exist on GCS, which is what the tool will pull from after a `flutter channel beta && flutter upgrade`. We just never generated the compressed archive.

**Comment by godofredoc** [comment]
aaaah now I understand, the release bundle does not exist but the engine artifacts do exist. Thanks for the explanation.

**Comment by itsjustkevin** [comment]
The website is now showing 4 different entries for beta 3.9.0-0.1.pre. 
![image](https://user-images.githubusercontent.com/11145366/225605866-12cfd7b4-9d87-4b1e-ab91-07871b141cba.png)

**Comment by godofredoc** [comment]
That was caused by the direct push to beta. As soon as we get the SLSA workflow ready we'll remove individuals access to prevent this from happening.
