### ISSUE TITLE
[packages] Audit external dependencies

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#122713]
I've written up [a policy for dependencies in flutter/packages](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#dependencies), and am in the process of adding tooling that will enforce it to prevent accidental violations. We didn't always have this policy, and the tooling is new, so we don't have explanations for all of the current dependencies that don't follow the policy. We should audit those dependencies, and for each one either eliminate it, or put a justification for why it's an exception.

**Comment by ditman** [comment]
Removed the `jwt_decoder` dependency here: https://github.com/flutter/packages/pull/3432

**Comment by stuartmorgan** [comment]
Current packages that aren't Dart- or Flutter-team owned:
- [ ] mocktail
  - Used in camera_web tests
- [ ] lcov_parser
  - Used in rfw tests
- [ ] adaptive_dialog
  - Used in go_router example
- [ ] provider
  - Used in go_router and go_router_builder examples
- [ ] equatable
  - No longer used; needs to be removed from the config
- [ ] xml
  - Used in flutter_migrate
- [ ] win32 (previously owned by timsneath personally, now owned by the "dart-windows" org)
  - Used in path_provider_windows
- [ ] build_verify (owned by kevmoo personally)
  - Used in go_router_builder example/tests
- [ ] google_maps (owned by a14n personally, and not using a verified publisher)
  - Used in google_maps_flutter_web
- [ ] path_to_regexp (owned by leonsenft personally
  - Used in go_router_builder

**Comment by ditman** [comment]
I'll take a stab at `mocktail` next time I'm tinkering on `camera_web`.

**Comment by stuartmorgan** [comment]
I'm going to close this as complete. I've filed bugs for most of the cases, and the two that I haven't are very specific test-only dependencies, which gives us minimal exposure to issues; if they were to break, we could in the worst case just immediately drop those specific tests without much short-term cost, and then evaluate how to proceed (and there would be no issues for package clients).
