### ISSUE TITLE
Connection terminated during handshake - flutter packages get

### ISSUE THREAD

**Issue by YASSERRMD** [flutter/flutter#12279]
## Steps to Reproduce

Added new package pubspec.yaml

`image_picker: 0.1.1`

Under 
`dependencies:`

I am getting following error, even i tried with different library, i am getting the same error

```
flutter packages get
Running "flutter packages get" in xxx_xxxx...
Connection terminated during handshake
pub get failed (1)
exit code 1
```

**Comment by YASSERRMD** [comment]
My ISP blocks this site, after contacting them it was solved

**Comment by guyulmaz** [comment]
which urls should be allowed at firewall?

**Comment by YASSERRMD** [comment]
https://pub.dartlang.org

**Comment by razu-shaikh** [comment]
> https://pub.dartlang.org

But I can browse  this link!!and get the same error?
How to solve
