### ISSUE TITLE
Redirecting to telegram bot using url_launcher package in flutter

### ISSUE THREAD

**Issue by AbdullohFlutterDeveloper** [flutter/flutter#122781]
I am using url_launcher to redirecting to telegram bot in my flutter app. 
Here was first verison of code:

 onTap: () async {
            const url = 'https://t.me/hilol_support_bot';
            // ignore: deprecated_member_use
            if (await canLaunch(url)) {
              // ignore: deprecated_member_use
              await launch(url);
            } else {
              throw 'Could not launch $url';
            }
          },

 When I am using with this code it is working not in all android devices as I understand that this code is deprecated.
 
 Then I modified the code into new one like this:

            const url = 'https://t.me/hilol_support_bot';

            if (await canLaunchUrl(Uri.parse(url))) {
              await launchUrl(
                Uri.parse(
                  url,
                ),
              );
            } else {
              throw 'Could not launch $url';
            }
          },

 but it now it is opening and error page in web page:
 Web page not abailable
 The web page at tg:resolve?
 domain=hilol_support_bot&appname=share could not be loaded beacause:
 
 net::ERR_UNKNOWN_URL_SCHEME

my wrote scheme to AndroidManifest.xml   file like this:

<queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="tg" android:host="t.me" android:pathPrefix="/hilol_support_bot" />
        </intent>
    </queries>
    <application
    .
    .
    
    <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
       
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="tg" android:host="t.me" android:pathPrefix="/hilol_support_bot" />
            </intent-filter>
        </activity>
        .
        .
     
     But it is still not redirecting to my telegram support bot

**Comment by darshankawar** [comment]
@AbdullohFlutterDeveloper 
I think your issue is better suited for support channels like StackOverflow, so please ask the same there.
You can also check the plugin example to see if there's any missing implementation.
Closing from here. If you disagree, write in comments and I'll reopen it.

**Comment by AbdullohFlutterDeveloper** [comment]
I am new here to use git hub, and it was my first question, And thanks for your suggestion [darshankawar](https://github.com/darshankawar), but I think this question may help to resolve someone's problem, Here is my solution for my question, I found that in my code only one implemention was lack and here it is:
mode: LaunchMode.externalApplication,

this mode should be written into urlLauncher widget
 if (await canLaunchUrl(Uri.parse(url))) {
              await launchUrl(
                Uri.parse(
                  url,
                ),
                mode: LaunchMode.externalApplication,
              );
            } else {
              throw 'Could not launch $url';
            }
 
 If you have any suggestions you give me, I will be glad to hear them

**Comment by AbdullohFlutterDeveloper** [comment]
I wouldn't mind if you change you label invalid, thanks in advance
