### ISSUE TITLE
web engine breaks with Dart 3.0

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#122724]
Web engine tests start failing when bumping the Dart SDK constraints to `'>=3.0.0-0 <4.0.0'` in these two files:

* https://github.com/flutter/engine/blob/bbde3a77b93528cf3f6b344ec80c3b800a8851d3/web_sdk/pubspec.yaml#L5
* https://github.com/flutter/engine/blob/bbde3a77b93528cf3f6b344ec80c3b800a8851d3/lib/web_ui/pubspec.yaml#L6

To see the failure, bump the Dart SDK to `'>=3.0.0-0 <4.0.0'` and run `dev/felt test test/engine/pointer_binding_test.dart`:

```
00:00 +30 ~1 -1: PointerAdapter does synthesize add or hover or move for scroll [E]                                                                              
  Expected: an object with length of <2>
    Actual: []
     Which: has length of <0>
  
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_helper.dart 1172:37          Object.wrapException
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_helper.dart 1203:25          Object.throwExpression
  /.pub-cache/hosted/pub.dev/test_api-0.4.17/lib/src/expect/expect.dart 134:31     Object.fail
  /.pub-cache/hosted/pub.dev/test_api-0.4.17/lib/src/expect/expect.dart 129:3      Object._expect
  /.pub-cache/hosted/pub.dev/test_api-0.4.17/lib/src/expect/expect.dart 46:3       Object.expect
  ../../../../test/engine/pointer_binding_test.dart 988:7                          testMain.<fn>
  ../../../../test/engine/pointer_binding_test.dart 33:9                           _testEach.<fn>
  /.pub-cache/hosted/pub.dev/test_api-0.4.17/lib/src/backend/declarer.dart 215:15  <fn>
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/async_patch.dart 308:19         _wrapJsFunctionForAsync.closure.$protected
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/async_patch.dart 333:23         _wrapJsFunctionForAsync.<fn>
```

Some initial investigation seems to indicate that synthesizing (or dispatching) scroll wheel events is somehow silently failing. Other mouse events seem to work. It is not clear what feature of dart 3.0 would cause this.

**Comment by goderbauer** [comment]
For now, I am bumping all but the web engine to 3.0 in https://github.com/flutter/engine/pull/40178.

cc @yjbanov Can someone from the web team figure our why the web engine is incompatible with Dart 3.0?

@jakemac53 FYI, not sure who from the Dart side may have an idea what in Dart 3.0 may be causing this.

**Comment by goderbauer** [comment]
@yjbanov and I debugged this a little further and we suspect a compiler bug. The test passes when we insert a random print. The hypothesis is that a switch/case is illegally optimized out when enabling the new pattern matching feature by bumping the constraints to 3.0.0. The following PR illustrates the problem: https://github.com/flutter/engine/pull/40314

@sigmundch Can you take a look at this or route it to the right person?

**Comment by jakemac53** [comment]
cc @munificent

**Comment by itsjustkevin** [comment]
FYI: @zanderso

**Comment by goderbauer** [comment]
> Note that the [invalid_case_patterns](https://dart.dev/tools/linter-rules#invalid_case_patterns) lint should also flag these for you.

The lint is enabled for this repo and did not flag any problems. As far as I can tell, this isn't a problem with how we use switch/cases. I think it is a complier problem since a randomly inserted print "fixes" the problem, as explained and demonstrated here: https://github.com/flutter/flutter/issues/122724#issuecomment-1470486649

**Comment by vsmenon** [comment]
Siggi may be out - perhaps @johnniwinther @rakudrama or could take a look?  See comment above.  An optimization may be going awry?

**Comment by sigmundch** [comment]
Thanks @goderbauer, great debugging!

While we investigate, is it possible to opt-out this one library as a way to unblock? (mark the library as 2.19 for now)

**Comment by goderbauer** [comment]
> While we investigate, is it possible to opt-out this one library as a way to unblock? (mark the library as 2.19 for now)

Yes, a `// @dart = 2.19` placed in this one file works. I'll do that for now. Thanks for investigating!

**Comment by a-siva** [comment]
> > While we investigate, is it possible to opt-out this one library as a way to unblock? (mark the library as 2.19 for now)
> 
> Yes, a `// @dart = 2.19` placed in this one file works. I'll do that for now. Thanks for investigating!

Cool. I guess that accounts for one of the failures, what about the other failure "pub roll failing to roll into the framework" that resulted in a revert of the Dart roll. is anybody looking at that ?

**Comment by goderbauer** [comment]
> This is a huge method. Would it be possible to share the compiled --no-minify JavaScript for the test in three configurations?

Can you tell me what command I need to run to generate these? (or maybe @yjbanov knows) Happy to upload them then.

**Comment by rakudrama** [comment]
We have a repro. Nothing more required from you.

**Comment by rakudrama** [comment]
I just landed a fix to dart2js.
The bug fixed would explain the effect of code in the second half of `convert` appearing to have no effect, and the effect of adding a 'print' causing the code to work.

**Comment by goderbauer** [comment]
Thank you! I'll remove the work around once that change has rolled into the engine.
