### ISSUE TITLE
`--local-web-sdk` flag should also use wasm artifacts (i.e. CanvasKit) from local build

### ISSUE THREAD

**Issue by eyebrowsoffire** [flutter/flutter#122748]
We should make sure that when `--local-web-sdk` is passed to the flutter tool, that the flutter tool overrides the canvaskit base URL to point at the locally built canvaskit artifacts. Right now I think it still fetches from unpkg.

**Comment by mdebbar** [comment]
My 2 cents: when the app uses `canvasKitBaseUrl: "..."` or `FLUTTER_WEB_CANVASKIT_URL` we should always respect that regardless of `--local-web-sdk` or not. (if it's set to `"canvaskit/"` then it'll load the locally built artifacts per https://github.com/flutter/flutter/pull/121902).

But I think what you are saying is we should change the [_default_](https://github.com/flutter/engine/blob/13a7f84ac25ea31857d24c9f185570615ab94d20/lib/web_ui/lib/src/engine/configuration.dart#L183-L186) base url when `--local-web-sdk` is used, right?

**Comment by eyebrowsoffire** [comment]
@mdebbar Yes exactly. I agree with your strategy.

**Comment by mdebbar** [comment]
Now that the default base url is `canvaskit/`, this issue is obsolete, right?

**Comment by eyebrowsoffire** [comment]
Yes, @mdebbar is right, this is no longer relevant.
