### ISSUE TITLE
`flutter run` of layers examples does not work on iOS simulators

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#12270]
```
cd flutter/examples/layers
flutter run raw/text.dart
flutter run raw/canvas.dart
```

The second `flutter run` will fail on iOS (simulators) with:

```
Exit code 3 from: /usr/bin/xcrun simctl launch F896CED0-7CB2-4A10-A8C1-7A0014E24CC5 io.flutter.examples.Layers --enable-dart-profiling --flx=/src/flutter/examples/layers/build/app.flx --dart-main=/src/flutter/examples/layers/raw/canvas.dart --packages=/src/flutter/examples/layers/.packages --enable-checked-mode --observatory-port=8100 --diagnostic-port=8101:
An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=3):
The request to open "io.flutter.examples.Layers" failed.
The process did launch, but has since exited or crashed.
Error launching application on iPhone 6s.
```

Works fine on Android.  @cbracken @chinmaygarde

**Comment by eseidelGoogle** [comment]
My understanding is that it's failing to notice that it should rebuild since the passed in .dart file has changed.

**Comment by cbracken** [comment]
Just to clarify, do you kill the app via `q` in between the two runs as follows:
1. flutter run raw/text.dart
2. `q` to exit hot reload
3. flutter run raw/canvas.dart
or are you doing to second run without terminating the first one?

I just tried both ways (using Xcode 9.1 beta on an iOS 11 simulator) and both worked as expected for me.

**Comment by sdirin** [comment]
I had this problem too. But I did not change the source code. In fact it was an empty default application.
The next run was fine.
I have to mention that I have an old MacBook with 4gb ram.

**Comment by zoechi** [comment]
This looks stale. Can we close?
