### ISSUE TITLE
Support of iOS accessibilityHint and accessibilityValue

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#12271]
* [accessibilityHint](https://developer.apple.com/documentation/objectivec/nsobject/1615093-accessibilityhint) 
* [accessibilityValue](https://developer.apple.com/documentation/objectivec/nsobject/1615117-accessibilityvalue)

There seems to be no equivalent for these on Android.

Right now, we only allow a SemanticsNode to have a `label`, which is reported to iOS as [accessibilityLabel](https://developer.apple.com/documentation/objectivec/nsobject/1615181-accessibilitylabel).

It's unclear how important it is to differentiate...

**Comment by Hixie** [comment]
How are they exposed in the UI?

**Comment by goderbauer** [comment]
The hint is not exposed in the UI at all. By default, a button has the hint "double-tab to activate". In the calendar app I have seen a button that opens an inline date-picker with the hint "double-tab to open date/time picker below".
In general it's meant as an additional hint about what the element will do when activated.

The value is the dynamic part of an accessibility element. How it is exposed in the UI highly depends on the UI element. When you have a text field for entering a city in a form, the `accesibilityLabel` could be "street" (static part) and the `acessibilityValue` would be whatever the current content of the text field is, e.g. "Mountain View" (dynamic part). 

Voiceover will always read out all threeL `accessibilityLabel`, `accessibilityValue`, `accessibilityHint`.

**Comment by Hixie** [comment]
By "the UI" I meant the UI of the AT, i.e., how does Voiceover read them out.

If Voiceover always reads all three out sequentially and never separates them, then I don't see any value in exposing them separately.

**Comment by harveynick** [comment]
I would add accessibility traits to the list, as well. I don't see any way of marking something as a section header in a list, for example, which will break some a11y functionality in iOS.

**Comment by harveynick** [comment]
Bringing over my comments from elsewhere:

Actually, the more I look at this, the more this seems like it should part of Widget, not Semantics. Having to wrap existing widgets in an instance of Semantics seems to break things here and there.

Example: TabBar.
- I can't (correctly) wrap the individual Tabs in an instance of Semantics, because TabBar expects its direct children to be instances of Tab;
- I can't wrap the TabBar itself in an instance of any of the semantics widgets, because its parent is expecting a PreferredSizeWidget.

**Comment by goderbauer** [comment]
> I would add accessibility traits to the list, as well. I don't see any way of marking something as a section header in a list, for example, which will break some a11y functionality in iOS.

We already support some accessibility traits and it is easy to add more. Instead of exposing them as iOS-specific UIAccessibilityTraits we expose them as [SemnticsFlags](https://docs.flutter.io/flutter/dart-ui/SemanticsFlags-class.html) so we can be cross-platform). I filed https://github.com/flutter/flutter/issues/12419 for your specific request to add a Flag for Headers.

**Comment by harveynick** [comment]
You can safely assume the all of the currently supported accessibility traits are needed, I think.

**Comment by harveynick** [comment]
How familiar are you with iOS accessibility?

**Comment by harveynick** [comment]
Also: Is there any documentation on how to actually use semantics flags and actions?

**Comment by harveynick** [comment]
Bringing over comments from a 1:1 chat between @goderbauer and myself:

>> The main thing is that the system reads hint out *after* traits.
>> It goes: label, value, traits, hint
>> In English, at least. It might be different in other languages.
>> Currently, Flutter provides no way to represent this.
>> You *can* bake the value in the label.
>> Mostly. It's just less elegant. Voiceover won't leave the pause the user might be expecting.
>> Also, I think in the cause of adjustable elements, a change means *only* the value is read out. (confirmed by @goderbauer )
>> And like I said, the order might be different in other languages.
>> (I was the CJK guy on Calendar, so I learned to *never* make assumptions about that sort of thing)

**Comment by goderbauer** [comment]
To sum up what I learnt: For excellent a11y support on iOS we will need to separate value, label, and hint because iOS treats them differently (see @harveynick post above). 

At the same time we need to make sure that we also expose those values correctly on Android, so we don't degrade the experience there. How to do this is still TBD.
