### ISSUE TITLE
When drawing in Flutter, Apple pencil cannot be operated even if the finger is operating. If the Apple pencil is working, your finger cannot.

### ISSUE THREAD

**Issue by zhoushuangjian001** [flutter/flutter#122784]
I am using GestureDetector to handle gestures. I found that the Apple Pencil accidentally touched the screen during my finger operation, and the finger event was terminated. I'd like to be able to implement anti-false touch handling. what should i do

**Comment by danagbemava-nc** [comment]
Hi @zhoushuangjian001, what platform are you experiencing this issue on? 

Please provide a complete minimal reproducible code sample so we can investigate this. Please also provide the output of flutter doctor -v. 

Thank you

**Comment by zhoushuangjian001** [comment]
@danagbemava-nc 
What I am working on is a painting software. When using Apple Pencil to create, if the finger accidentally touches the drawing board, the event callback of the Apple Pencil being drawn will be terminated. I want to implement anti-touch handling.

**Comment by zhoushuangjian001** [comment]
flutter --version ：
Flutter 3.7.7 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2ad6cd72c0 (12 days ago) • 2023-03-08 09:41:59 -0800
Engine • revision 1837b5be5f
Tools • Dart 2.19.4 • DevTools 2.20.1

flutter doctor -v
[✓] Flutter (Channel stable, 3.7.7, on macOS 13.2.1 22D68 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 3.7.7 on channel stable at /Users/admin/fvm/versions/3.7.7
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (12 days ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/admin/android
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/admin/android
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.76.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.61.20230301

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.2.1 22D68 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 111.0.5563.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
 admin@MrZhou  ~ 

**Comment by danagbemava-nc** [comment]
Hi @zhoushuangjian001, what platform is this one? Is it on the web or in a native iPad OS app? Can you also take a look at https://github.com/flutter/flutter/issues/120667 to see if it is similar to your case?

**Comment by zhoushuangjian001** [comment]
@danagbemava-nc 
When the supportedDevices property of Flutter's ScaleGestureRecognizer widget is set to PointerDeviceKind.touch and PointerDeviceKind.stylus . ScaleGestureRecognizer's onUpdate is called when we slide our fingers on the screen, but when we slide our fingers, we use Apple Pencile to slide on the screen at the same time, and the event of this finger will be replaced by Apple Pencile. What I want to achieve is that one PointerDeviceKind is operating, and other PointerDeviceKinds cannot be operated.

**Comment by danagbemava-nc** [comment]
Hi @zhoushuangjian001, please provide a complete minimal reproducible code sample that reproduces the issue so that we can investigate this. 

Thank you
