### ISSUE TITLE
[packages] Icon rounded outlined at the same time

### ISSUE THREAD

**Issue by guyluz11** [flutter/flutter#122728]
Flutter is missing the option to make icons both rounded and outlined at the same time.

This option should exist because 

1. In Figma material extension there is an option to make the icon rounded and outlined at the same time  (see fill=off)
<img width="360" alt="Screenshot_2023-03-15_at_19 25 26" src="https://user-images.githubusercontent.com/9304740/225392856-cdf2b60c-707f-4aeb-b6b2-d14999ef7ab7.png">
2. I can do it under Material Symbols

https://fonts.google.com/icons?icon.style=Rounded

I may be missing how to use **material symbols** in Flutter.

I have tried
`Icon(Icons.home_rounded, fill: 0.0)` vs `Icon(Icons.home_rounded, fill: 1.0)`
and
`Icon(Icons.home_outlined, fill: 0.0)` vs `Icon(Icons.home_outlined, fill: 1.0)`
and
`Icon(Icons.home, fill: 0.0)` vs `Icon(Icons.home, fill: 1.0)`

```dart
flutter --version
Flutter 3.9.0-1.0.pre.164 • channel master • https://github.com/flutter/flutter.git
Framework • revision 9ba0d08ebc (4 days ago) • 2023-03-12 00:16:19 -0500
Engine • revision 57f7120ef9
Tools • Dart 3.0.0 (build 3.0.0-322.0.dev) • DevTools 2.22.2
```

**Comment by danagbemava-nc** [comment]
Hi @guyluz11, material symbols are not yet supported in flutter. See  https://github.com/flutter/flutter/issues/102560

Closing from here as duplicate. 

Kindly subscribe to the issue linked above for updates. 

Thank you
