### ISSUE TITLE
M2Crypto not installed on Windows 7 ARM.

### ISSUE THREAD

**Issue by kentnguyen99** [flutter/flutter#122731]
M2Crypto software not installed on Windows 7 ARM.

flutter@FLUTTER-WIN-7 C:\Users\flutter>salt-call --versions
Salt Version:
          Salt: 3003.5
 
Dependency Versions:
          cffi: 1.14.5
      cherrypy: 18.6.0
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.5
     gitpython: Not Installed
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed

**Comment by yusuf-goog** [comment]
This has been resolved. M2Crypto successfully installed.
