### ISSUE TITLE
[go_router] Add a way to set the default transition page

### ISSUE THREAD

**Issue by ValentinVignal** [flutter/flutter#122789]
## Use case

I would like all my pages to use the same transition/animation (ex: fade).
Right now, I have to give a `pageBuilder` to all my `GoRoute` (or override all the `pageBuilder` of my `GoRouteData` with `go_router_builder`) to pass the same `CustomTransitionPage`

example with `go_router_builder` and `GoRouteData`:

```dart

Page<void> _buildPage(BuildContext context, GoRouterState state) {
    return CustomTransitionPage<void>(
      key: state.pageKey,
      transitionsBuilder: (
        context,
        animation,
        secondaryAnimation,
        child,
      ) =>
          FadeTransition(
        opacity: animation,
        child: child,
      ),
      child: build(context, state),
    );
  }
}

class MyRoute extends GoRouteData {
  @override
  Page<void> buildPage(BuildContext context, GoRouterState state) => _buildPage(context, state);
}
```

## Proposal

It would be nice to have a way to set the default page builder of go router so it is apply to each routes

```dart
GoRouter(
  defaultPageBuilder: _pageBuilder,
);
```

Or even better would be having a parameter in `GoRouter` or `RouteShell` to set the default page builder of the sub-routes:

```dart
GoRoute(
  subRoutesDefaultPageBuilder: _pageBuilder,
  routes: [/* ... */],
);
ShellRoute(
  subRoutesDefaultPageBuilder: _pageBuilder,
  routes: [/* ... */],
);
```

**Comment by danagbemava-nc** [comment]
Hi @ValentinVignal, this looks similar to https://github.com/flutter/flutter/issues/113282. 

Can you take a look and confirm if this is the same as the feature being requested in the issue linked above?

**Comment by ValentinVignal** [comment]
@danagbemava-nc Thanks, it looks like a similar feature. However, mine is also mentioning the ability to set it in the `GoRoute`/`ShellRoute` for the subroutes.
Do you want to keep this issue open or do you prefer me to add a comment in https://github.com/flutter/flutter/issues/113282 ?

**Comment by danagbemava-nc** [comment]
Hi @ValentinVignal,  please add a comment in #113282. 

Closing from here as duplicate. 

Thank you
