### ISSUE TITLE
[MacOS]  unsealed contents present in the bundle root Command CodeSign failed with a nonzero exit code

### ISSUE THREAD

**Issue by TheGlorySaint** [flutter/flutter#122898]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I created a new flutter project from the CLI with support for iOS, macOS, Android and web, I also installed flutterfire to configure firebase. I installed these Packages: 
```
firebase_core: ^2.4.1
firebase_crashlytics: ^3.0.11
firebase_dynamic_links: ^5.0.15
cloud_firestore: ^4.4.4
```

I have created a Dev and Prod Flavor. For each flavor, I created an own runner config. Inside the iOS and macOS Folder, I created a config folder with a dev and prod subfolder with the GoogleService-Info.plist and the .JSON file in it. The config Folder gets created in the Finder and then drag'n dropped into Xcode, the same with the .JSON and GoogleService-Info.plist file(s).
iOS runs and build perfectly fine on Simulator as well as the physical Device, with each Flavor also accessing each Firebase Project.

macOS on the other Hand only builds when I change the name of the GoogleService-Info.plist file, but then I can't use Firebase. If I leave the "normal Name" it throws this error: `unsealed contents present in the bundle root Command CodeSign failed with a nonzero exit code`. 

### Actual results

iOS Build fine
macOS only builds when GoogleService-info.plist is changed to a different name, but then FIrebase can't be used.

### Logs

<details>
<summary>Logs</summary>

```console

unsealed contents present in the bundle root Command CodeSign failed with a nonzero exit code

```

</details>

### Flutter Doctor output

Please Ignore the Android Warning. I use Android Studio Preview Giraffe that shows this warning, but when i run `flutter doctor --android-licenses` I get no error.

<details>
<summary>Doctor output</summary>

```console

[✓] Flutter (Channel master, 3.9.0-9.0.pre.8, on macOS 13.2.1 22D68 darwin-arm64, locale de-DE)
    • Flutter version 3.9.0-9.0.pre.8 on channel master at /opt/homebrew/Caskroom/flutter/3.7.0/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 09cc1c4cda (32 hours ago), 2023-03-16 09:18:57 +0100
    • Engine revision 3194afad72
    • Dart version 3.0.0 (build 3.0.0-322.0.dev)
    • DevTools version 2.22.2

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/blackbox/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.76.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • iPhone 14 Pro Max (mobile) • CENSORED• ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 111.0.5563.64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

</details>

**Comment by TheGlorySaint** [comment]
Might my Issue be related to https://github.com/flutter/flutter/issues/64088

**Comment by darshankawar** [comment]
Thanks for the report @TheGlorySaint 
In order to narrow down the issue / behavior to framework itself, can you confirm if the same error occurs without using firebase plugins ?
If so, a github repo of the demo would be helpful to have so that we can clone it and verify at our end.

**Comment by TheGlorySaint** [comment]
@darshankawar The same error occurs when using without firebase plugins. I'd invite you to the demo project due to the fact, that for Firebase the API Key etc. is exposed and i don't want that anybody else does have access to it.

**Comment by darshankawar** [comment]
Thanks for the update @TheGlorySaint 

> macOS on the other Hand only builds when I change the name of the GoogleService-Info.plist file, but then I can't use Firebase. If I leave the "normal Name" it throws this error: `unsealed contents present in the bundle root Command CodeSign failed with a nonzero exit code`.

Coming back to this statement. Are you trying to add or change name of this file through VSCode ? If so, can you try to add this file via XCode itself ?

Also, I cloned the repo you shared with me, but I don't see `mac` folder in it.

**Comment by TheGlorySaint** [comment]
@darshankawar The config Folder gets created in the Finder and then drag'n dropped into Xcode, the same with the .JSON and GoogleService-Info.plist file(s). Please use the macosandweb Branch.

**Comment by darshankawar** [comment]
Thanks for the update. Since I don't use VSCode, I cloned the said branch and tried to run on macOS, but seem to be getting `Exception: No macOS desktop project configured.`

Would be good if you could provide exact steps on how to use the project clone and run on macos desktop so that we can make this issue actionable.

**Comment by TheGlorySaint** [comment]
@darshankawar There is not much to do. Clone the Project, switch to the Branch I mentioned, and run it with these args.
```
"--flavor",
        "dev",
        "--dart-define-from-file",
        "dev-config.json"
```

**Comment by darshankawar** [comment]
Thanks for the update. Upon following above I was able to see the originally reported behavior, but looking at the repo you shared and the code implementation, it has lot of third party package and code, but in order to narrow down to the behavior to the framework itself, would it be possible for you to trim down the repo just to have framework related code and not any third party implementation, that way it'll help to analyze the behavior properly.

**Comment by TheGlorySaint** [comment]
> Thanks for the report @TheGlorySaint In order to narrow down the issue / behavior to framework itself, can you confirm if the same error occurs without using firebase plugins ? If so, a github repo of the demo would be helpful to have so that we can clone it and verify at our end.

@darshankawar as you requested here three days ago, trimmed down to use only the Firebase Plugin, because it is necessary to use the flavor.

**Comment by darshankawar** [comment]
I meant I was referring to: https://github.com/TheGlorySaint/timetrec/blob/macOSandWeb/lib/main.dart wherein it has lots of third party packages and implementation.



> I have created a Dev and Prod Flavor. For each flavor, I created an own runner config. Inside the iOS and macOS Folder, I created a config folder with a dev and prod subfolder with the GoogleService-Info.plist and the .JSON file in it. The config Folder gets created in the Finder and then drag'n dropped into Xcode, the same with the .JSON and GoogleService-Info.plist file(s). iOS runs and build perfectly fine on Simulator as well as the physical Device, with each Flavor also accessing each Firebase Project.
> 
> macOS on the other Hand only builds when I change the name of the GoogleService-Info.plist file, but then I can't use Firebase. If I leave the "normal Name" it throws this error: `unsealed contents present in the bundle root Command CodeSign failed with a nonzero exit code`.

Ideally what we look for is a barebone repo that in your case would only contain what you described here. Because the team member / engineer who would be looking into this issue would be looking for it. Since you gave me the access for your project, it may not be feasible to do the same for other members as you'll need to give access to them as well.
