### ISSUE TITLE
Widget-level a11y tests

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#12286]
Our test framework should support testing the proper generation of the semantics tree for a widget or set of widgets.

Internally, we have `SemanticsTester` for that. We should consider making that part of the API offered by Flutter's testing package to make it accessible for every developer.

For that, we should clean-up and improve its API.

**Comment by yjbanov** [comment]
I would, but i18n work will block my progress on this for some time.

**Comment by Hixie** [comment]
cc @jonahwilliams 

There's some tests that reference this issue (in particular, examples/catalog/test/custom_semantics_test.dart).

**Comment by jonahwilliams** [comment]
I've already sort of started of this issue with getSemanticsData - that also needs some improvements though

**Comment by jonahwilliams** [comment]
Mostly done, https://github.com/flutter/flutter/issues/19691 as a follow up
