### ISSUE TITLE
[Impeller] Enable RuntimeStage tests for the Vulkan backend.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#122823]
The backend been implemented but tests disabled since the test harness only creates *.iplr files for the host backend instead of all enabled backends.

Related to https://github.com/flutter/flutter/issues/105538 for OpenGL ES. Filing a separate issue for more granular tracking.

**Comment by dnfield** [comment]
E.g. https://github.com/flutter/engine/pull/42146 has it failing.

**Comment by dnfield** [comment]
Ok, it was failing there because I actually broke it - however, in a local run it seems to pass, even though it's desginated as being skipped (it's not actually skipping)

**Comment by chinmaygarde** [comment]
Depends on https://github.com/flutter/flutter/issues/129659. Today, the packaged SL is not SPIRV.
