### ISSUE TITLE
macOS crash in debug mode - 0x105dadbf4 dart::Assert::Fail

### ISSUE THREAD

**Issue by filiph** [flutter/flutter#122889]
This is similar to https://github.com/flutter/flutter/issues/119841 but doesn't look like the exact same crash, looking at the stack trace.

When debugging my Flutter app on MacOS and doing a lot of hot reloading, at some point the app just crashes with a "Report Problem" window.

<img width="1202" alt="Screenshot 2023-03-17 at 15 17 15" src="https://user-images.githubusercontent.com/919717/225931299-c163b8de-7c05-4b7d-bde2-f11be862fe60.png">

## Steps to Reproduce

This will be hard to reproduce but I do have the Problem Details and the System Configuration, so I thought I'd report it anyway.

I can also provide access to the current code so people can give the reproduction a try. The trick seems to be to just keep the game running and keep making Hot-Reload changes. I have crashed the game several times now in this way.

Some things that seem salient from the Details that I'm copying here for SEO:

Some things that seem salient from the Details that I'm copying here for SEO:

- Code Type:             ARM-64 (Native)
- Crashed Thread:        1  io.flutter.ui
- OS Version:            macOS 13.2.1 (22D68)
- Application Specific Information: abort() called
- Exception Type:        EXC_CRASH (SIGABRT)
- Thread 1 Crashed:: io.flutter.ui
  - 0   libsystem_kernel.dylib        	       0x190e36868 __pthread_kill + 8
  - 1   libsystem_pthread.dylib       	       0x190e6dcec pthread_kill + 288
  - 2   libsystem_c.dylib             	       0x190da62c8 abort + 180
  - 3   FlutterMacOS                  	       0x105dadbf4 dart::Assert::Fail(char const*, ...) const + 48
  - 4   FlutterMacOS                  	       0x105f99958 dart::ThreadPool::RunImpl(std::_LIBCPP_ABI_NAMESPACE::unique_ptr<dart::ThreadPool::Task, std::_LIBCPP_ABI_NAMESPACE::default_delete<dart::ThreadPool::Task> >) + 300
  - 5   FlutterMacOS                  	       0x105dc051c dart::BootstrapNatives::DN_Isolate_spawnFunction(dart::Thread*, dart::Zone*, dart::NativeArguments*) + 2112
  - 6   FlutterMacOS                  	       0x105e6a5b0 dart::NativeEntry::BootstrapNativeCallWrapper(_Dart_NativeArguments*, void (*)(_Dart_NativeArguments*)) + 216

<details>
  <summary>Logs</summary>

```
Analyzing giant_robot...                                        

   info • The declaration '_logFloat32x4' isn't referenced • lib/experimental/neural/backpropagation_with_advantage.dart:505:11 • unused_element
   info • The parameter name 'learningRate' doesn't match the name 'value' in the overridden method • lib/experimental/neural/parameter_strategy.dart:167:24 • avoid_renaming_method_parameters
   info • The parameter name 'momentum' doesn't match the name 'value' in the overridden method • lib/experimental/neural/parameter_strategy.dart:257:24 • avoid_renaming_method_parameters
   info • The value of the local variable 'result' isn't used • lib/game/combat/impact_particle.dart:71:9 • unused_local_variable
   info • The value of the local variable 'chosen' isn't used • tool/backprop_driver_brain.dart:448:13 • unused_local_variable
```

(These info warnings are unrelated, I'm 99.99% sure. I've been wanting to fix them for a few months now...

```
[!] Flutter (Channel stable, 3.7.7, on macOS 13.2.1 22D68 darwin-arm64, locale en-US)
    • Flutter version 3.7.7 on channel stable at /Users/filiph/fvm/versions/stable
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart-beta/2.19.0-444.4.beta/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/filiph/fvm/versions/stable. Consider adding /Users/filiph/fvm/versions/stable/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (9 days ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /Users/filiph/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.76.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 111.0.5563.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

</details>

Gah! I closed the window before getting the whole crash report. I'll add one the next time this happens.

**Comment by darshankawar** [comment]
> I can also provide access to the current code so people can give the reproduction a try. The trick seems to be to just keep the game running and keep making Hot-Reload changes. I have crashed the game several times now in this way.

@filiph Would be good to get code sample for us to try and verify.

Meantime, /cc @mraleph for thoughts on the crash reported.

**Comment by mraleph** [comment]
I have seen this before - this is some sort of out of memory. The assertion indicates failure to spawn a thread, which I presume is caused by running out of something (e.g. memory or some kernel specific resources). Hard to say anything specific about this crash. 

PS. I have previously went to a rabbit hole of trying to figure out a way to include more information into the crash report, but it turns out that "Application Specific Section" is redacted for privacy reasons these days, so even though there are some APIs which previously could be used to include strings into ASI these strings don't end up in the report.

**Comment by filiph** [comment]
@darshankawar Would it be okay if I just give you or someone else on the team access to a private repo? That's easiest for me. I can give you the exact commit.

Of course, as soon as I decided to reproduce the issue, I can't. I _think_ it was just me doing a _lot_ of hot reloads without ever hot-restarting, switching between my IDE and the app. (I was fine-tuning some particle effects at the time.) We can park this and if I see this again, I know what to do.

**Comment by darshankawar** [comment]
> We can park this and if I see this again, I know what to do.

Sounds good. 

> Would it be okay if I just give you or someone else on the team access to a private repo? That's easiest for me. I can give you the exact commit.

Yes, you may give me the access when you are able to consistently replicate it and we can take this issue forward.
