### ISSUE TITLE
Flutter integration test not working when build for testlab (iOS with schema)

### ISSUE THREAD

**Issue by rbargux** [flutter/flutter#122809]
How are you? I’m trying to configure Testlab for ios, but I’m having problems with the configuration.

https://github.com/flutter/flutter/tree/main/packages/integration_test#ios-device-testing

When following the documentation recommended by Firebase when executing the `xcodebuild build-for-testing` command (Only difference with documentation is schema),  code breaks because it does not find some frameworks.

Script

```
output="../build/ios_integ"
product="build/ios_integ/Build/Products"

Pass --simulator if building for the simulator.
flutter build ios integration_test/authentication/test/sign_in_co_test.dart --flavor qa --dart-define=flavor=qa --release


pushd ios
xcodebuild build-for-testing \
  -workspace Runner.xcworkspace \
  -scheme qa \
  -xcconfig Flutter/Release.xcconfig \
  -configuration Release \
  -derivedDataPath \
  $output -sdk iphoneos


xcodebuild test-without-building \
  -xctestrun "../build/ios_integ/Build/Products/qa_iphoneos16.2-arm64.xctestrun" \
  -destination id=<device-id>
popd
```

![framework error](https://user-images.githubusercontent.com/30943325/225680411-85543f2a-7518-4e03-af44-c35c3383dffd.png)

To give a momentary solution to this, I copy the modules manually and there it allows me to execute the code correctly. However, later I try to run the test build locally and the test fails with the following error.

![dictionary error](https://user-images.githubusercontent.com/30943325/225680571-9948bf75-1e82-4eb1-b0e1-0a6acba0e6b2.png)

Thanks a lot for read and try to help me . :pray:

run flutter test on testlab (ios with schema).

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.7, on macOS 13.1 22C65 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.76.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Comment by huycozy** [comment]
Hi @rbargux 
In order to address the issue properly, please provide `Steps to reproduce` in detail, along with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. 

Also, please provide the information (error log, exception, crash, etc) in text format instead of a screenshot for better readability and investigation. You may want to refer to [writing and formatting syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) for beautifully formatted issue description. Thank you!

**Comment by rbargux** [comment]
Thanks for answer. I attach the step by step.

## 1. Open ios/Runner.xcworkspace in Xcode. Create a test target if you do not already have one via File > New > Target... and select Unit Testing Bundle. Change the Product Name to RunnerTests. Make sure Target to be Tested is set to Runner and language is set to Objective-C. Select Finish. Make sure that the iOS Deployment Target of RunnerTests within the Build Settings section is the same as Runner.

Add the new test target to ios/Podfile by embedding in the existing Runner target.

```
target 'Runner' do
  # Do not change existing lines.
  ...

  target 'RunnerTests' do
    inherit! :search_paths
  end
end
```

## 2. In Xcode, add a test file called RunnerTests.m (or any name of your choice) to the new target and replace the file:

```
@import XCTest;
@import integration_test;

INTEGRATION_TEST_IOS_RUNNER(RunnerTests)
```

## 3. create build 

`flutter build ios integration_test/authentication/test/sign_in_co_test.dart --flavor qa --dart-define=flavor=qa --release`

## 4. build for testing

```
xcodebuild build-for-testing \
  -workspace Runner.xcworkspace \
  -scheme qa \
  -xcconfig Flutter/Release.xcconfig \
  -configuration Release \
  -derivedDataPath \
  $output -sdk iphoneos
```

At this point the execution throws me the following error.

... -F/Users/ricardobejarano/Documents/monorepos/tyba-client/packages/apps/tyba-app/ios/Pods/MLKitXenoCommon/Frameworks -F/Users/ricardobejarano/Documents/monorepos/tyba-client/packages/apps/tyba-app/ios/Pods/UXCam -F/Users/ricardobejarano/Documents/monorepos/tyba-client/packages/apps/tyba-app/build/ios_integ/Build/Products/Release-prd-iphoneos/XCFrameworkIntermediates/AppsFlyerFramework/Main -F/Users/ricardobejarano/Documents/monorepos/tyba-client/packages/apps/tyba-app/build/ios_integ/Build/Products/Release-prd-iphoneos/XCFrameworkIntermediates/FirebaseAnalytics/AdIdSupport -F/Users/ricardobejarano/Documents/monorepos/tyba-client/packages/apps/tyba-app/build/ios_integ/Build/Products/Release-prd-iphoneos/XCFrameworkIntermediates/GoogleAppMeasurement/AdIdSupport -F/Users/ricardobejarano/Documents/monorepos/tyba-client/packages/apps/tyba-app/build/ios_integ/Build/Products/Release-prd-iphoneos/XCFrameworkIntermediates/GoogleAppMeasurement/WithoutAdIdSupport -F/Users/ricardobejarano/Documents/monorepos/tyba-client/packages/apps/tyba-app/build/ios_integ/Build/Products/Release-prd-iphoneos/XCFrameworkIntermediates/UXCam -F/Users/ricardobejarano/Documents/monorepos/tyba-client/packages/apps/tyba-app/ios/Pods/UXCam -MMD -MT dependencies -MF /Users/ricardobejarano/Documents/monorepos/tyba-client/packages/apps/tyba-app/build/ios_integ/Build/Intermediates.noindex/Runner.build/Release-prd-iphoneos/Runner.build/Objects-normal/arm64/GeneratedPluginRegistrant.d --serialize-diagnostics /Users/ricardobejarano/Documents/monorepos/tyba-client/packages/apps/tyba-app/build/ios_integ/Build/Intermediates.noindex/Runner.build/Release-prd-iphoneos/Runner.build/Objects-normal/arm64/GeneratedPluginRegistrant.dia -c /Users/ricardobejarano/Documents/monorepos/tyba-client/packages/apps/tyba-app/ios/Runner/GeneratedPluginRegistrant.m -o /Users/ricardobejarano/Documents/monorepos/tyba-client/packages/apps/tyba-app/build/ios_integ/Build/Intermediates.noindex/Runner.build/Release-prd-iphoneos/Runner.build/Objects-normal/arm64/GeneratedPluginRegistrant.o
/Users/ricardobejarano/Documents/monorepos/tyba-client/packages/apps/tyba-app/ios/Runner/GeneratedPluginRegistrant.m:12:9: fatal error: module 'advance_pdf_viewer' not found
@import advance_pdf_viewer;

1 error generated.

## 5. In order to get around this error what I do is copy the frameworks from the Release-iphoneos folder to Release-prd-iphoneos

![Screenshot 2023-03-17 at 9 14 38 AM](https://user-images.githubusercontent.com/30943325/225930497-53013203-80bb-42db-9d79-16550cbe7a96.png)

## 6. At this point repeat point 4 and it now compiles correctly.

## 7. Run locally to check that everything is ok.

```
xcodebuild test-without-building \
  -xctestrun "../build/ios_integ/Build/Products/qa_iphoneos16.2-arm64.xctestrun" \
  -destination id=<device-id>
```

and finally throw this error 

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

Testing started
2023-03-17 09:31:19.217 xcodebuild[12647:65810] [MT] IDETestOperationsObserverDebug: 61.966 elapsed -- Testing started completed.
2023-03-17 09:31:19.217 xcodebuild[12647:65810] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2023-03-17 09:31:19.217 xcodebuild[12647:65810] [MT] IDETestOperationsObserverDebug: 61.966 sec, +61.966 sec -- end

Test session results, code coverage, and logs:
	/Users/ricardobejarano/Library/Developer/Xcode/DerivedData/Runner-gajhxufifczcccbjttsahdghxweq/Logs/Test/Test-qa-2023.03.17_09-30-16--0500.xcresult

Testing failed:
	Runner (11596) encountered an error (Exception raised during test suite construction: NSInvalidArgumentException: -[__NSDictionaryM isEqualToString:]: unrecognized selector sent to instance 0x280cdf8c0
Exception callstack: (
	0   CoreFoundation                      0x00000001afa68e44 42CCFC7B-FF32-3D25-8F01-CCB2AD843A8B + 40516
	1   libobjc.A.dylib                     0x00000001a8bff8d8 objc_exception_throw + 60
	2   CoreFoundation                      0x00000001afbdd81c 42CCFC7B-FF32-3D25-8F01-CCB2AD843A8B + 1566748
	3   CoreFoundation                      0x00000001afa7ef50 42CCFC7B-FF32-3D25-8F01-CCB2AD843A8B + 130896
	4   CoreFoundation                      0x00000001afae7320 _CF_forwarding_prep_0 + 96
	5   integration_test                    0x00000001143e99a4 __59-[FLTIntegrationTestRunner testIntegrationTestWithResults:]_block_invoke + 240
	6   CoreFoundation                      0x00000001afa72538 42CCFC7B-FF32-3D25-8F01-CCB2AD843A8B + 79160
	7   CoreFoundation                      0x00000001afafcb90 42CCFC7B-FF32-3D25-8F01-CCB2AD843A8B + 646032
	8   integration_test                    0x00000001143e9864 -[FLTIntegrationTestRunner testIntegrationTestWithResults:] + 552
	9   RunnerTests                         0x00000001268b3c04 +[RunnerTests testInvocations] + 132
	10  XCTestCore                          0x0000000114e5d020 +[XCTestCase _testInvocationDescriptors] + 76
	11  XCTestCore                          0x0000000114e4383c +[XCTestSuite testSuiteForTestCaseClass:] + 316
	12  XCTestCore                          0x0000000114e4304c +[XCTestSuite suitesForBundlesIncludingEmptySuites:] + 332
	13  XCTestCore                          0x0000000114e45860 -[XCTestSuite _initWithTestConfiguration:] + 328
	14  XCTestCore                          0x0000000114e45e24 +[XCTestSuite testSuiteForTestConfiguration:] + 52
	15  XCTestCore                          0x0000000114e147d0 __53-[XCTTestRunSession initWithTestConfiguration:error:]_block_invoke_2 + 68
	16  XCTestCore                          0x0000000114e42348 +[XCTContext _runInChildOfContext:forTestCase:markAsReportingBase:block:] + 180
	17  XCTestCore                          0x0000000114e4225c +[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 144
	18  XCTestCore                          0x0000000114e14774 __53-[XCTTestRunSession initWithTestConfiguration:error:]_block_invoke + 124
	19  XCTestCore                          0x0000000114e14474 +[XCTTestRunSession performTestSuiteConstructionInBlock:] + 60
	20  XCTestCore                          0x0000000114e14630 -[XCTTestRunSession initWithTestConfiguration:error:] + 216
	21  XCTestCore                          0x0000000114e15464 -[XCTTestRunSessionProvider executionExtensionWithTestConfiguration:reportingSession:completion:] + 84
	22  XCTestCore                          0x0000000114e19670 __128+[XCTExtensionProvider(XCTExecutionExtension_Internal) allExecutionExtensionsWithTestConfiguration:reportingSession:completion:]_block_invoke + 148
	23  XCTestCore                          0x0000000114e532bc __69-[NSArray(XCTestAdditions) xct_arrayByApplyingAsyncBlock:completion:]_block_invoke + 188
	24  XCTestCore                          0x0000000114e53450 __XCTAsyncEnumerate_block_invoke.27 + 64
	25  XCTestCore                          0x0000000114e530d8 -[NSArray(XCTestAdditions) xct_arrayByApplyingAsyncBlock:completion:] + 756
	26  XCTestCore                          0x0000000114e19544 +[XCTExtensionProvider allExecutionExtensionsWithTestConfiguration:reportingSession:completion:] + 356
	27  XCTestCore                          0x0000000114e3efcc -[XCTestDriver _runTests] + 616
	28  XCTestCore                          0x0000000114e139bc _XCTestMain + 88
	29  libXCTestBundleInject.dylib         0x000000011325f56c __copy_helper_block_e8_32s + 0
	30  CoreFoundation                      0x00000001afaa2514 42CCFC7B-FF32-3D25-8F01-CCB2AD843A8B + 275732
	31  CoreFoundation                      0x00000001afb0ad6c 42CCFC7B-FF32-3D25-8F01-CCB2AD843A8B + 703852
	32  CoreFoundation                      0x00000001afadab90 42CCFC7B-FF32-3D25-8F01-CCB2AD843A8B + 506768
	33  CoreFoundation                      0x00000001afadfeb0 CFRunLoopRunSpecific + 612
	34  GraphicsServices                    0x00000001e9cd5368 GSEventRunModal + 164
	35  UIKitCore                           0x00000001b1fd5668 CF21AD9C-EFBF-3961-A7C0-54BD30CEFEA9 + 3806824
	36  UIKitCore                           0x00000001b1fd52cc UIApplicationMain + 340
	37  Runner                              0x00000001042bc69c main + 64
	38  dyld                                0x00000001ce3d8960 4B042F28-0D14-30EC-A1DE-3DBB10866AD7 + 88416
). If you believe this error represents a bug, please attach the result bundle at /Users/ricardobejarano/Library/Developer/Xcode/DerivedData/Runner-gajhxufifczcccbjttsahdghxweq/Logs/Test/Test-qa-2023.03.17_09-30-16--0500.xcresult)

** TEST EXECUTE FAILED **


Please, if you need any other type of information to help me, let me know and I'll share it with you.

Reference Doc https://github.com/flutter/flutter/tree/main/packages/integration_test#ios-device-testing

**Comment by huycozy** [comment]
Thanks for your response. As far as I can see from your log and the command, the test was failed by `advance_pdf_viewer` plugin. And you also ran the test in QA flavor. Does the issue happen without using `advance_pdf_viewer` or a specific flavor?

Also, it would be appreciated if you could provide a sample code on a GitHub repository so that may verify the issue. Thanks!
