### ISSUE TITLE
Paytabs url is not working in webview_flutter

### ISSUE THREAD

**Issue by micaelsn** [flutter/flutter#122890]
These logs show up when I try access paytabs url in ios app
I already put the ios permissions in info.plist:
<dict>
  <key>NSAllowsArbitraryLoads</key>
  <true/>
  <key>NSAllowsArbitraryLoadsInWebContent</key>
  <true/>
</dict>
but it didn't works. :(
you could try access this url: https://secure.paytabs.com/payment/expired

and it will appears:

Sandbox] Could not enable Mach bootstrap, errno = 1.
[Sandbox] Could not enable Mach bootstrap, errno = 1.
[Process] 0x124064220 - GPUProcessProxy::gpuProcessExited: reason=IdleExit
[Process] 0x1250009d0 - [PID=3761] WebProcessProxy::gpuProcessExited: reason=IdleExit

## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by huycozy** [comment]
Hi @micaelsn 
I checked this on the latest plugin version (`webview_flutter: ^4.0.7`) but it is displayed normally on iOS. 

<details>
<summary>Demo</summary>

![Screenshot 2023-03-20 at 13 18 46](https://user-images.githubusercontent.com/104349824/226262121-73f270b2-8797-41c6-ac3a-2182ec3aad90.png)

</details>

Which is your current plugin version? Please retry on the latest version with [plugin sample code](https://github.com/flutter/packages/tree/main/packages/webview_flutter/webview_flutter/example) and confirm if it works or not. Thanks!

**Comment by micaelsn** [comment]
It's works, thank you
