### ISSUE TITLE
[integration_test] flutter test --tags "someTag" loads all the test files in integration_test path rather than loading and running only those test files that have tag 'someTag'

### ISSUE THREAD

**Issue by RamyaAcharya** [flutter/flutter#122874]
## Steps to Reproduce
1. Create 2 integration_test files in ./integration_test/test/  folder `add_product_test.dart `and `remove_product_test.dart`. Code below
2. Create dart_test.yaml
```
tags:
  add:
  remove:
```
3. Run command: `flutter test ./integration_test/test/ --tags “remove”  -d emulator-5554`

Test code:
`add_product_test.dart`
```
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:sampleProject/main.dart' as app;
import 'package:get_it/get_it.dart';

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();
  WidgetsFlutterBinding.ensureInitialized();
print("═════════════════════════════════════════ Add New Test ═══════════════════════════════════════════════════════════");
  group('Group 1', () {
    testWidgets(
      'Scenario - Add product A',
          (WidgetTester tester) async {
        final FlutterExceptionHandler? originalOnError = FlutterError.onError;
        app.main();
        await tester.pumpAndSettle();
        FlutterError.onError = originalOnError;
        // Test code to add product here

            print(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Add product A Test Completed <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<");
      });

    tearDown(() async {
    });
  });

  group('Group 2', () {
    testWidgets(
        'Scenario: Add product B',
            (WidgetTester tester) async {
          final FlutterExceptionHandler? originalOnError = FlutterError.onError;
          app.main();
          await tester.pumpAndSettle();
          FlutterError.onError = originalOnError;
          // Test code to add product here
          print(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Add product B Test Completed <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<");
        });
    tearDown(() async {
    });
  });
}
```

**remove_product_test.dart**
```

import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:sampleProject/main.dart' as app;
import 'package:get_it/get_it.dart';

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();
  WidgetsFlutterBinding.ensureInitialized();
print("═════════════════════════════════════════ Remove New Test ═══════════════════════════════════════════════════════════");

  group('Group 1', () {
    testWidgets(
      'Scenario - Remove product A',
          (WidgetTester tester) async {
        final FlutterExceptionHandler? originalOnError = FlutterError.onError;
        app.main();
        await tester.pumpAndSettle();
        FlutterError.onError = originalOnError;
        // Test code to Remove product here
            print(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Remove product A Test Completed <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<");
      });

    tearDown(() async {
      //some tearDown logic
    });
  });

  group('Group 2', () {
    testWidgets(
        'Scenario: Remove product B',
            (WidgetTester tester) async {
          final FlutterExceptionHandler? originalOnError = FlutterError.onError;
          app.main();
          await tester.pumpAndSettle();
          FlutterError.onError = originalOnError;
          // Test code to Remove product here

          print(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Remove product B Test Completed <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<");
        }, tags: ['remove']);
    tearDown(() async {
      //some tearDown logic
    });
  });
}
```

**Expected results:** When running command: `flutter test ./integration_test/test/ --tags “remove” -d emulator-5554`. Only **remove_product_test.dart** should load and run Group 2 test alone.

**Actual results:** When running command: `flutter test ./integration_test/test/ --tags “remove”  -d emulator-5554`
Both test scripts in ./integration_test/test/folder **load** and runs only **remove_product_test.dart**. 
**Is loading both files expected behavior?** 

```
03:00 +0 -1: loading /15Mar/sampleProject/integration_test/test/add_product_test.dart                                                                                                   03:44 +0 -1: loading /15Mar/sampleProject/integration_test/test/add_product_test.dart                                                                                        
03:47 +0 -1: loading /15Mar/sampleProject/integration_test/test/add_product_test.dart     Built build/app/outputs/flutter-apk/app-qa-debug.apk                                                                                              03:49 +0 -1: loading /15Mar/sampleProject/integration_test/test/add_product_test.dart                                                                                            
03:54 +0 -1: loading /15Mar/sampleProject/integration_test/test/add_product_test.dart 
═════════════════════════════════════════ Add New Test ═══════════════════════════════════════════════════════════
03:00 +0 -1: loading /15Mar/sampleProject/integration_test/test/remove_product_test.dart                                                                                                   03:44 +0 -1: loading /15Mar/sampleProject/integration_test/test/remove_product_test.dart                                                                                               
03:47 +0 -1: loading /15Mar/sampleProject/integration_test/test/remove_product_test.dart   Built build/app/outputs/flutter-apk/app-qa-debug.apk                                                                                                03:49 +0 -1: loading /15Mar/sampleProject/integration_test/test/remove_product_test.dart                                                                                            
03:54 +0 -1: loading /15Mar/sampleProject/integration_test/test/remove_product_test.dart 
═════════════════════════════════════════ Remove New Test ═══════════════════════════════════════════════════════════
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Remove product B Test Completed <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

```
<details><summary>Flutter doctor -v</summary>
<p>

ramya@Ramyas-MacBook sampleProject % flutter doctor -v
[!] Flutter (Channel unknown, 3.3.9, on macOS 12.6.2 21G320 darwin-x64, locale en-IN)
    ! Flutter version 3.3.9 on channel unknown at /Users/ramya/Desktop/flutter /
    ! Upstream repository unknown
    • Framework revision b8f7f1f986 (4 months ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/ramyaacharya/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/ramya/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Community Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] VS Code (version 1.69.2)
    • VS Code at /Users/ramya/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)         • macos         • darwin-x64     • macOS 12.6.2 21G320 darwin-x64
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 111.0.5563.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

</p>

**Comment by darshankawar** [comment]
@RamyaAcharya 
There's already a similar open issue describing your case https://github.com/flutter/flutter/issues/25141 so follow-up in that issue for further updates.
Closing this as a duplicate.

**Comment by RamyaAcharya** [comment]
@darshankawar I see this issue's [25141](https://github.com/flutter/flutter/issues/25141) subject line matches the issue that I have raised here, the only difference is the issue is raised for `flutter drive` while I am using `flutter test`. 
But the fix given here: [32836](https://github.com/flutter/flutter/issues/32836) is for introducing --tags support. 
--tags support for `flutter test --tags someTag` is working fine now. But, `flutter test -t` does not still focus on running only tag-specific tests.

Could you please help me in confirming if I am missing anything in `dart_test.yaml` file or in specifying something for running only tag-specific tests using the `flutter test`?

**Comment by RamyaAcharya** [comment]
@darshankawar
Yes, I expected the same behavior as you have mentioned too. But, unfortunately, it's **LOADING** all the UI integration test files in the `integration_tests/tests/` folder and then RUNS only the ones that are tagged as 'testme'. 

I tried without `dart_test.yaml` file too. It's the same behavior.

Basically, it's not running only the tag-specific test file, rather loads all the test files in the tests folder and then runs the only ones that are tagged as 'testme'. 

Test files are expected to be filtered based on specified tags in `flutter test --tags 'testme'` before loading. But, currently, I see all test files load > install apk for that file > and then do not run that UI test if the tag specified in `flutter test --tags 'testme'` is not matching in the test file.

BTW, the command I am using is `flutter test ./integration_test/test/ --tags “remove”  -d emulator-5554`. If I use just `flutter test -t 'testme'  as u mentioned. It will load all the unit test files as well to search for this tag.
