### ISSUE TITLE
[Android] Remove accessibility root ID assumptions

### ISSUE THREAD

**Issue by loic-sharma** [flutter/flutter#122847]
Android assumes there is a single accessibility root node with ID `0`. In a multi-window world, there may be multiple root nodes each with their own unique ID. Thus, Android must not rely on the root node having ID `0`.

See: https://github.com/search?q=repo%3Aflutter%2Fengine%20ROOT_NODE_ID&type=code

**Comment by gmackall** [comment]
We think this is probably something the engine team should take. If you disagree please let us know.

**Comment by loic-sharma** [comment]
I'm not familiar with who owns which Android code, but just to be clear this is work in the Android embedding. The platform-agnostic part of the engine has already been updated to remove single accessibility root assumptions.

**Comment by loic-sharma** [comment]
This is no longer necessary as the framework will no longer require that embedders use unique IDs across all accessibility trees. Android can continue assuming ID `0` is the root of its accessibility trees.
