### ISSUE TITLE
[Impeller] Failure in glyph atlas recycling unit test (host_profile, arm64 macOS)

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#122839]
@jonahwilliams 

```
[ RUN      ] Play/TypographerTest.GlyphAtlasTextureIsRecycledIfUnchanged/Metal
../../flutter/impeller/typographer/typographer_unittests.cc:195: Failure
Expected equality of these values:
  atlas
    Which is: (ptr = 0x60000356ee98, value = 64-byte object <01-00 00-00 00-00 00-00 48-97 A7-03 00-60 00-00 30-97 A7-03 00-60 00-00 40-F5 56-03 00-60 00-00 0B-00 00-00 00-00 00-00 40-A1 A7-03 00-60 00-00 07-00 00-00 00-00 00-00 00-00 80-3F 00-00 00-00>)
  next_atlas
    Which is: (ptr = 0x60000356eb98, value = 64-byte object <01-00 00-00 00-00 00-00 B8-B3 A7-03 00-60 00-00 A0-B3 A7-03 00-60 00-00 A0-FE 56-03 00-60 00-00 0B-00 00-00 00-00 00-00 50-AB A7-03 00-60 00-00 07-00 00-00 00-00 00-00 00-00 80-3F 00-00 00-00>)
[  FAILED  ] Play/TypographerTest.GlyphAtlasTextureIsRecycledIfUnchanged/Metal, where GetParam() = 4-byte object <00-00 00-00> (8 ms)
```

**Comment by jonahwilliams** [comment]
I can't reproduce the failure locally, which probably means that it depends on the particular machine. I'll try and adjust this test to be more stable to the font selected

**Comment by zanderso** [comment]
Sorry I should have noted that it's flaky. I've seen it only once out of 8-10 runs. Not sure if there might also be a timing dependence in there.

**Comment by jonahwilliams** [comment]
ahh, hmm. Thats worse actually lol

**Comment by zanderso** [comment]
@jonahwilliams from flake/disabled-test review, would any of our work on text in the meantime have had any effect on this test?

**Comment by jonahwilliams** [comment]
https://github.com/flutter/engine/pull/41374/ should make it significantly better, since it increases the min size of the atlas. I thought I actually marked it enabled but I might have missed one

**Comment by jonahwilliams** [comment]
Yeah I removed the disabled check, lets see if it stays passing on CI

**Comment by jonahwilliams** [comment]
The disabled checks were re-added as that PR were reverted, trying again.
