### ISSUE TITLE
webview_flutter fails to load in android integration tests

### ISSUE THREAD

**Issue by fuzzybinary** [flutter/flutter#122888]
## Steps to Reproduce

1. Create an application that uses the `webview_flutter` package
2.  Write an integration test that navigates to a screen using the WebViewWidget
3. Run the integration test on an Android Emulator

**Expected results:** The WebViewWidget loads, even if integration_test isn't able to interact with it.

**Actual results:** Nothing. The WebViewWidget presents as a blank white widget.

<details>

While not a minimal example, the `datadog_webview_tracking` package integration test is loading a WebView to ensure events get forwarded to the mobile app properly. It doesn't need to interact with the Web view itself.

https://github.com/DataDog/dd-sdk-flutter/tree/develop/packages/datadog_webview_tracking

</details>
<details>
  <summary>Flutter Doctor</summary>

Flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.7.6, on macOS 13.2.1 22D68 darwin-arm64, locale en-US)
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.18.7/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/jeff.ward/Projects/flutter.
      Consider adding /Users/jeff.ward/Projects/flutter/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.76.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @fuzzybinary 

I am trying to run the package integration_test example https://github.com/flutter/packages/blob/main/packages/webview_flutter/webview_flutter/example/integration_test/webview_flutter_test.dart on Android emulator, but for some reason it is taking too much time to come up with results. Meantime, can you verify the same at your end and check if using these examples, you get same behavior as reported ?
