### ISSUE TITLE
Listview widget does not scroll smoothly(scroll with glitch)

### ISSUE THREAD

**Issue by Sasikumar3595** [flutter/flutter#122886]
## Steps to Reproduce

1. Run the attached sample on iPhone 14 simulator 16.2 
2. List view does not scroll smoothly

**Expected results:** ListView widget will scroll smoothly without a glitch

**Actual results:** ListView widget scroll with glitch

<details>
<summary>Code sample</summary>

```dart

  ScrollController scrollController1 = ScrollController();
  ScrollController scrollController2 = ScrollController();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text("Title"),
      ),
      body: Container(
        child: Stack(
          children: [
            Positioned(
                left: 0,
                right: 0,
                bottom: 0,
                top: 0,
                child: Scrollbar(
                  controller: scrollController1,
                  child: ListView(
                    scrollDirection: Axis.horizontal,
                    controller: scrollController1,
                    children: [
                      Container(
                        width: 1500,
                        child: Scrollbar(
                          controller: scrollController2,
                          child: ListView(
                            scrollDirection: Axis.vertical,
                            controller: scrollController2,
                            children: [
                              Container(
                                width: 1500,
                                height: 1500,
                                child: Row(
                                  children: getChildren(),
                                ),
                              )
                            ],
                          ),
                        ),
                      )
                    ],
                  ),
                ))
          ],
        ),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    ));
  }

  List<Widget> getChildren()
  {
    List<Widget> children = <Widget>[];

    for(int i=0; i<10; i++)
    {
      children.add(Container(
        width: 150,height: 1500,
        child: Padding(
          padding: const EdgeInsets.all(5.0),
          child: Container(color: Colors.red.withOpacity(0.1 * i),),
        ),
      ));
    }

    return children;
  }

```

</details>

<details>
<summary>Issue replication video</summary>

https://user-images.githubusercontent.com/44917578/225917437-37b3551f-9e6f-4480-adc8-527f228309c3.mov

</details>

**Comment by sashn-citiqprepaid** [comment]
Running this example on https://dartpad.dev errors in the console:
```bash
Error: Assertion failed: file:///Users/brettmorgan/Documents/GitHub/dart-services/flutter-sdks/stable/packages/flutter/lib/src/widgets/framework.dart:2685:20
_debugCurrentBuildTarget == context
is not trueError: Error: Assertion failed: file:///Users/brettmorgan/Documents/GitHub/dart-services/flutter-sdks/stable/packages/flutter/lib/src/widgets/framework.dart:2685:20
_debugCurrentBuildTarget == context
is not true

```

**Comment by Sasikumar3595** [comment]
@sashn-citiqprepaid 

The above code was working fine as expected, please find the dartpad image as below
![Screen Shot 2023-03-17 at 8 00 23 PM](https://user-images.githubusercontent.com/44917578/225933935-ba22b959-b842-4548-8187-a3f16ebb8bdc.png)

**Comment by iapicca** [comment]
possibly related to
- https://github.com/flutter/flutter/issues/35687

**Comment by Sasikumar3595** [comment]
@iapicca

The specified issue only raised on iPhone devices and simulators. It was not replicated on Android, Web, Windows and Mac OS platforms.

**Comment by darshankawar** [comment]
@Sasikumar3595 
I looked at the code implementation you shared and noted below as the hierarchy of widgets:

`Container -> Stack -> children [Positioned] -> Scrollbar -> ListView -> [children] -> Container -> Scrollbar -> ListView -> [children] -> Container -> Row -> Container.
`
Which shows nested `Scrollbar` and `ListView` respectively. Would like to know the use case you are trying to achieve by having above widgets hierarchy. Are you looking to implement 2D scrolling ?

Can you also try by using `SingleChildScrollView` or something like `ListView.builder` and pass horizontal and vertical scroll directions and see if it helps or not ?

**Comment by iapicca** [comment]
@Sasikumar3595 
I tried your [code sample](https://github.com/flutter/flutter/issues/122886#issue-1629316372) and I have 2 observations and a question


#### observations

- I don't experience any glitch or stutter

<details>
  <summary>screen recording</summary>
  
![alleged_issue](https://user-images.githubusercontent.com/45637986/226914758-2d0c4292-dc55-463e-a04b-6c9872696403.gif)

</details>

- partially related to the alleged issue, your code need optimization
  - [flutter_lints](https://pub.dev/packages/flutter_lints) is yelling about unnecessary containers and such
  - `List<Widget> getChildren() ...` is bad for performances  (see this [issue](https://github.com/flutter/flutter/issues/19269) and this [SO question](https://stackoverflow.com/questions/53234825/what-is-the-difference-between-functions-and-classes-to-create-reusable-widgets/53234826#53234826))
  
#### question

are you experiencing the issue scrolling with a mouse? 
(if so the issue is very much related to [this](https://github.com/flutter/flutter/issues/122886#issuecomment-1474231468))

**Comment by iapicca** [comment]
> We created this sample to replicate the issue and we still facing issues on scrolling for iPhone simulator and iPhone devices. It looks like a glitch(video added on description [#122886 (comment)](https://github.com/flutter/flutter/issues/122886#issue-1629316372))

I'm not sure "'reproduces' on my machine" is a useful input for a bug report,
running your code sample the issue doesn't seem to occur (and I'm running a air m1, nothing fancy)

**Comment by Sasikumar3595** [comment]
@iapicca 

We prepared the above-attached sample for reproducing the issue and we checked with the stateless widget to resolve the issue but still, the glitch showed to us.

We suspect the issue is related to performance.

We have tested the issue on the below devices and the issue was reproduced - iPhone 14 simulator and iPhone SE real device.

We have tested this with the iPad simulator and it is working fine.

**Note**: We have tested the issue on iOS's latest version with flutter's latest version and the issue was only replicated on the iOS platform only, other platforms(Windows, MacOS, Android, Web) are working fine.

**Comment by QuentinSc** [comment]
> Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. If you find this problem please file a new issue with the same description, what happens, logs and the output of 'flutter doctor -v'. All system setups can be slightly different so it's always better to open new issues and reference the related ones. Thanks for your contribution.

Seriously ???

**Comment by iapicca** [comment]
> > Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. If you find this problem please file a new issue with the same description, what happens, logs and the output of 'flutter doctor -v'. All system setups can be slightly different so it's always better to open new issues and reference the related ones. Thanks for your contribution.
>
> Seriously ???

@QuentinSc
when an issue is not reproducible gets closed (seriously).
If you are experiencing this issue I encourage you to **_open a new issue_** 
with a minimal reproducible code sample (w/o 3rd party packages)
