### ISSUE TITLE
How to do MT build on Windows?

### ISSUE THREAD

**Issue by RellyLee** [flutter/flutter#122873]
How to do MT build on Windows?

**Comment by darshankawar** [comment]
@RellyLee 
Your question is better suited for support channels like StackOverflow, so please ask the same there.

I found below way to do MT build, but I am not sure about it's further performance upon building, but sharing it here just for your reference:

- Go to Windows/CMakeLists.txt and add this property to build the app with MT flag

`set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")`

I'll close this issue from here.
