### ISSUE TITLE
Release mode app not launching. Visual Studio version 17.5.1

### ISSUE THREAD

**Issue by Lighting123** [flutter/flutter#122880]
When i build my app in release mode and launch the app from the executable. Sometimes it doesn't show any window and sometimes it does show a window. I don't understand what is going on. On debug mode it's okay.

Flutter SDK version: 3.7.6
Windows Build: 18363.418
Windows SDK version: 18362

**Comment by darshankawar** [comment]
@Lighting123 
Please elaborate by providing details as what does `Sometimes it doesn't show any window and sometimes it does show a window.` mean. Does it render text or not ? Does it show any elements on screen ?
What device does this behavior occur on ? 
Can you provide a minimal code sample that replicates the behavior ?

**Comment by FusoraTech** [comment]
> Sometimes it doesn't show any window and sometimes it does show a window.

Also, did you mean a possible silent crash? Anything logged at the Windows Event Viewer?

**Comment by Lighting123** [comment]
> @Lighting123 Please elaborate by providing details as what does `Sometimes it doesn't show any window and sometimes it does show a window.` mean. Does it render text or not ? Does it show any elements on screen ? What device does this behavior occur on ? Can you provide a minimal code sample that replicates the behavior ? Also, if you build via terminal / command line instead of IDE, do you get same behavior or not ?

Well sometimes it launches as a process in task manager but doesn't display any window while other times it does display a window and building it with command line it also does the same behavior.

Device: HP Probook 650

**Comment by darshankawar** [comment]
Are you trying release mode on windows desktop platform, like `flutter run --release -d windows` or `flutter build windows` ?
The .exe generated you are trying to launch but it is not launching properly ?
Can you provide your `pubspec.yaml` and also check at your end if any of the plugins might be conflicting ?
For ex: https://stackoverflow.com/questions/73760625/flutter-exe-release-not-running-on-windows

**Comment by Lighting123** [comment]
> Are you trying release mode on windows desktop platform, like `flutter run --release -d windows` or `flutter build windows` ? The .exe generated you are trying to launch but it is not launching properly ? Can you provide your `pubspec.yaml` and also check at your end if any of the plugins might be conflicting ? For ex: https://stackoverflow.com/questions/73760625/flutter-exe-release-not-running-on-windows

Yes. I'm using flutter build windows to build the release app and the executable is not launching properly it just shows up as a process in task manager but it doesn't show any window and sometimes it does.

[pubspec.yaml.txt](https://github.com/flutter/flutter/files/11038897/pubspec.yaml.txt)

**Comment by darshankawar** [comment]
@Lighting123 
Does the same behavior occur using flutter counter app ? If not, we will need minimal reproducible code sample that shows the reported behavior.

**Comment by Lighting123** [comment]
> @Lighting123 Does the same behavior occur using flutter counter app ? If not, we will need minimal reproducible code sample that shows the reported behavior.

Yes. It does.

**Comment by darshankawar** [comment]
@Lighting123 
What command are you running to build the app ? Can you add `-v` to it and check if you get any meaningful error in the log that'll be helpful for us to debug further ?
Also, a short video of the behavior would be good.

**Comment by mgenware** [comment]
Possible duplicate of https://github.com/flutter/flutter/issues/119415

**Comment by Shiyam23** [comment]
This worked for me: https://github.com/flutter/flutter/issues/119415#issuecomment-1480492795

**Comment by Lighting123** [comment]
@mgenware 
It might be the problem because it launches as a process but never displays a window. Yeah, maybe you're right.

**Comment by darshankawar** [comment]
@Lighting123 
Please follow-up in the linked issue https://github.com/flutter/flutter/issues/119415 and you may share your findings in it for further updates and better tracking. Closing as duplicate.
