### ISSUE TITLE
Whitescreen due to battery optimization

### ISSUE THREAD

**Issue by komunikelliot** [flutter/flutter#122870]
We meet a similar issue that the one originally posted by bhavesh350.

We run a flutter app with some process that probably run in background, and the app is getting white screen after a few hours of running (generally users reopen app that was not completely killed but just pushed in background after one night).

Testing the solution to deactivate the battery optimization and it seems to work !

What does it mean for our app ? What changes are required to get it work for everybody without requirement to change the device settings ?

Is the background process with background_fetch supposed to trigger a "placebo" function that keeps app alive every 15 minutes ? Or, can we force the battery optimization setting by code ?

______________________
Original message that helped us to understand:
That's true but it doesn't actually reproduce "white screen" or blank screen as in your screenshot.  App launches with no issues, if it was a Flutter issue, app won't be running again. 
Instead of running in optimized battery usage, since no real app is supposed to run like that, It's never guaranteed, the app won't be killed. You can Android documentation for battery optimization for more details. You need to write an app with a background process. if any UI is killed when running for a longer period, you need to restore data from the background process. In this case, counter logic would be in the background process.

See https://flutter.dev/docs/development/packages-and-plugins/background-processes and there are third-party packages such as https://pub.dev/packages/background_fetch

There have many attempts to reproduce white/blank screen issue and given your goal, you need to run actual background process instead.

_Originally posted by @TahaTesser in https://github.com/flutter/flutter/issues/82969#issuecomment-859399455_
            ](https://github.com/flutter/flutter/issues/82969#issuecomment-859399455)

**Comment by darshankawar** [comment]
@komunikelliot 

> What does it mean for our app ? What changes are required to get it work for everybody without requirement to change the device settings ?
> 
> Is the background process with background_fetch supposed to trigger a "placebo" function that keeps app alive every 15 minutes ? Or, can we force the battery optimization setting by code ?

Please check [this](https://docs.flutter.dev/development/packages-and-plugins/background-processes) documentation and see if it helps in your case.

**Comment by komunikelliot** [comment]
Hello,
I have seen this link before in the original answer from @TahaTesser, which is in my post.
My main question is that I don't know what I should check with the background process.

Do I need to check for my code some code that should be wrapped in a background process function, or is it just a function that will do nothing but keep the app alive ?

As the app is running fine without the battery optimization setting, I'm not sure if I need to change some of the code or if I only need to implement a "placebo" background event.

I hope that my confusion is clearly described.

Thank you.

**Comment by darshankawar** [comment]
> Do I need to check for my code some code that should be wrapped in a background process function, or is it just a function that will do nothing but keep the app alive ?

As also suggested in the linked issue, one option for you is to use community package `background_fetch`. Another option is to make use of isolates for which you can read [this](https://blog.codemagic.io/understanding-flutter-isolates/) article and see if it helps.
For further resolution or support on how to wrap your code in background process function or its implementation, you may ask the same on support channels like StackOverflow. I'll close this issue for now based on above comment. If you disagree, write in comments and I'll reopen it.
