### ISSUE TITLE
Error after used pub upgrade and the error show RC2Parameters that never heard.

### ISSUE THREAD

**Issue by SittiphanSittisak** [flutter/flutter#122892]
After I used `pub upgrade` I got this error and I don't know why. Although I comment on the `crypto` package(I see the `crypto` is a path in the error) this error still appears.
```
Launching lib\main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
/C:/Users/user/AppData/Local/Pub/Cache/hosted/pub.dev/basic_utils-5.5.1/lib/src/library/crypto/rc2_engine.dart:4:1: Error: 'RC2Parameters' is imported from both 'package:basic_utils/src/library/crypto/rc2_parameters.dart' and 'package:pointycastle/api.dart'.
import 'package:pointycastle/export.dart';
^^^^^^^^^^^^^
Failed to compile the application.
```

I tried to ctrl+shift+f to find `package:basic_utils/src/library/crypto/rc2_parameters.dart` and `RC2Parameters` but this is not found.

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.5, on Microsoft Windows [Version 10.0.19045.2728], locale th-TH)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.5)
[√] Android Studio (version 2022.1)
[√] IntelliJ IDEA Community Edition (version 2022.2)
[√] VS Code (version 1.76.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!
```

**Comment by IkramBOULAKSAKIS** [comment]
Just got the same issue !!

**Comment by stuartmorgan** [comment]
This error is coming from the `basic_utils` package; you'll need to report it to the developers of that package. It looks like they'll need to update it for a conflict in its dependencies.

**Comment by mc100p** [comment]
What worked for me is is that 

<img width="1136" alt="Screenshot 2023-03-17 at 4 04 05 PM" src="https://user-images.githubusercontent.com/62410547/226047996-91d877f9-4a59-46e2-875e-8281d0fb0e14.png">

for the import - import 'package:basic_utils/src/library/crypto/rc2_parameters.dart'

I added as crypto so It wouldn't be ambiguous.

**Comment by stuartmorgan** [comment]
Editing files in your pub cache is not recommended, as the cache is subject to being cleared or rebuilt.

**Comment by swisscheesy** [comment]
No current workaround besides editing pub cache?

**Comment by SittiphanSittisak** [comment]
I am not using the `basic_utils` package why do I face this error?
Or this package was required in some package that I am using?

**Comment by SittiphanSittisak** [comment]
I tried to find the package that makes this error, and the result is the `mongo_dart` package(didn't find more).

**Comment by chasanpro** [comment]
same happening with me while using the mongo_dart
the package is having the conflict issues it seems

**Comment by chasanpro** [comment]
<img width="1381" alt="image" src="https://user-images.githubusercontent.com/61396515/226093813-90d5c902-9ff9-4f4d-9c7d-b34103d8e74f.png">
I tried this 
and the build was successful

**Comment by simplyKarthic** [comment]
please remove ^ in the basic_utils: ^5.3.0 and do basic_utils: 5.3.0 this is currently working

**Comment by stuartmorgan** [comment]
Please post any further discussion in https://github.com/Ephenodrom/Dart-Basic-Utils/issues/84 rather than in this closed issue.

> I am not using the `basic_utils` package why do I face this error?
> Or this package was required in some package that I am using?

Yes, anyone with this error has a dependency on `basic_utils`, either direct or transitive.

**Comment by marcellocamara** [comment]
I'm with the same problem, can't compile and using only this dependencies:

```
dart_frog: ^0.3.4
mongo_dart: ^0.9.1
```

**Comment by MazenCoder** [comment]
You can override the package
`
dependency_overrides:
  basic_utils: "5.3.0"
`
