### ISSUE TITLE
[Web] Remove accessibility root ID assumptions

### ISSUE THREAD

**Issue by loic-sharma** [flutter/flutter#122850]
Flutter web assumes there is a single accessibility root node with ID `0`. In a multi-window world, there may be multiple root nodes each with their own unique ID. Thus, Flutter web must not rely on the root node having ID `0`.

See:

1. https://github.com/flutter/engine/blob/6a846703002d0b86dc54da56b39ddf7a22b271f5/lib/web_ui/lib/src/engine/semantics/semantics.dart#L422-L423
2. https://github.com/flutter/engine/blob/6a846703002d0b86dc54da56b39ddf7a22b271f5/lib/web_ui/lib/src/engine/semantics/semantics.dart#L1822
3. https://github.com/flutter/engine/blob/6a846703002d0b86dc54da56b39ddf7a22b271f5/lib/web_ui/lib/src/engine/semantics/semantics.dart#L1829

**Comment by yjbanov** [comment]
The best approach would be for each `FlutterView` to have its own `EngineSemanticsOwner`. This way node IDs can continue being unique within each view's semantics tree.

**Comment by loic-sharma** [comment]
This is no longer necessary as the framework will no longer require that embedders use unique IDs across all accessibility trees. Web can continue using ID `0` for the root of its accessibility trees.

**Comment by ditman** [comment]
> Web can continue assuming ID 0 is the root of its accessibility trees.

@loic-sharma web is going multi-view, so we'll have to tweak this. It's good to know that each view will have its own accessibility tree :) (I guess the updates to accessibility trees will come with a view ID as well!)
