### ISSUE TITLE
Proposal to customize date_picker icons

### ISSUE THREAD

**Issue by MichalNemec** [flutter/flutter#122840]
## Use case
I want to have custom icons in date_picker
date_picker.dart itself has this
```dart
entryModeButton = IconButton(
          icon: const Icon(Icons.edit), //hardcoded icon
          color: onPrimarySurface,
          tooltip: localizations.inputDateModeButtonLabel,
          onPressed: _handleEntryModeToggle,
        );
```
calendar_date_picker has 
```dart
RotationTransition(
                          turns: _controller,
                          child: Icon(
                            Icons.arrow_drop_down,
                            color: controlColor,
                          ),
                        ),
```

## Proposal

expose these hardcoded icons, so we can change them to our needs.

**Comment by HansMuller** [comment]
Sounds like a reasonable request. Is it enough to expose the hardwired icons, or is there a use case for changing colors or the animation?

**Comment by MichalNemec** [comment]
@HansMuller for me its enough to have option to replace icons, then other could come in and ask for animations, colors,.. i would try to expose as much as possible.
