### ISSUE TITLE
Lots of jobs have failed on devicelab win hosts

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#122852]
Many builds on win devicelab hosts seem to be failing with jdk version issues. See: https://luci-milo.appspot.com/ui/p/flutter/builders/staging/Windows_staging%20flutter_gallery_win__compile/5452/overview

Because it can't find the necessary cipd package: failed to resolve flutter/java/openjdk/windows-amd64@11 (line 1): no such ref

**Comment by keyonghan** [comment]
This affects also Linux targets: https://luci-milo.appspot.com/p/flutter/builders/staging/Linux_android_staging%20android_obfuscate_test?limit=200

The version of open_jdk has been updated to `version: 11` instead of `11`.

**Comment by keyonghan** [comment]
https://flutter-review.googlesource.com/c/infra/+/40840 to fix.

**Comment by yusuf-goog** [comment]
Putting CL to change to `version:11` to `11`
