### ISSUE TITLE
Downloading Gradle Wrapper... dead

### ISSUE THREAD

**Issue by zhangcf2012** [flutter/flutter#12295]
## Flutter Doctor

Downloading Gradle Wrapper...                             

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Failed to send crash report due to a network error: SocketException: Connection failed (OS Error: No route to host, errno = 65), address = clients2.google.com, port = 443
Crash report written to /var/folders/zk/_vt2mqbd7fvbby8v9_3l2d2h0000gn/T/flutter_04.log;

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by eseidelGoogle** [comment]
This looks like https://github.com/flutter/flutter/issues/11681.
