### ISSUE TITLE
We need a controlled way to show motion on the website

### ISSUE THREAD

**Issue by Sfshaza** [flutter/flutter#12291]
I am documenting animations, so it makes sense to show what the motion looks like in some of the relevant docs.

Animated GIFs have been suggested, but I've played with these enough to know that I hate how they demand your attention. I can't scroll them off the screen fast enough. This is not ideal for technical documentation. (I've asked some engineers around here who feel the same way.)

Tao suggested the approach that Material Design uses, which involves JavaScript, I believe. They have a play/pause button that overlays the area. 

So, what say you? If we want this sort of feature, I'll need someone to implement it. Or should we display two images - before and after?

I'm open to suggestions! In the short term, I'll stick with images.

**Comment by sethladd** [comment]
What are your requirements? Sounds like:

* Ability for the reader to play/pause.
* No auto-play. (See above)

Anything else?

**Comment by InMatrix** [comment]
Features nice to have from an email discussion:
* When the video is paused, show the still image instead of the player control overlay on https://material.io/guidelines/motion/transforming-material.html#transforming-material-radial-transformation
* Allow the user to scrub the video
* Allow the user to play the video at a slower speed

I wonder if the standard HTML5 video tag can satisfy our needs? https://www.html5rocks.com/en/tutorials/video/basics/

**Comment by sethladd** [comment]
Here is how you can move to arbitrary points in the video (presumably how to move one frame at a time): https://stackoverflow.com/questions/20336955/how-to-step-one-frame-forward-and-one-frame-backward-in-video-playback

**Comment by Sfshaza** [comment]
This is the behavior that @Hixie suggested:

<blockquote>
I would prefer if videos played once when they came fully on screen, then paused until clicked again, at which point they'd play. With a play/pause button and scrub control that showed at the bottom while the mouse was over the image but not otherwise.
</blockquote>

**Comment by sethladd** [comment]
@Sfshaza if you can create a single list of requirements that you're looking for, I think we can help you out. :) thanks!

**Comment by Sfshaza** [comment]
I talked to @sethladd in person, but want to close the loop. For now, I'm using a video that I upload to youtube. I don't love the fact that youtube displays the video in landscape mode, but it works for now. This would be nice to have in the long term, though.

**Comment by Sfshaza** [comment]
To follow up. Tao suggested that I append "&rel=0" to the URL to suppress the ads shown at the end of the video. I tried that both with a Flutter doc, and with my personal website. In each case, it broke the video.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1841](https://github.com/flutter/website/issues/1841) via [**ZenHub**](https://www.zenhub.com/)
