### ISSUE TITLE
[Impeller] Investigate if lossy texture compression makes sense for Flutter.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#122918]
Introduced in iOS 15+ on select devices, `MTLTextureCompressionTypeLossy` yields texture memory savings of ~100 MB in the Flutter Gallery.

Investigate if Impeller can opt-into using these textures for some (intermediates) or all textures.

**Comment by chinmaygarde** [comment]
cc @jonahwilliams who found the savings in gallery and @bdero for ideas on the intermediates that we should definitely use this on. We could perhaps add this option to `impeller::TextureDescriptor`.

**Comment by bdero** [comment]
I don't know the characteristics of the lossy compression here, but we can probably get away with aggressive compression on lossy filters and their input snapshots (like the gaussian blur, which is just a pure low pass filter) with results that are indistinguishable from the lossless result.

**Comment by jonahwilliams** [comment]
xref: https://metalbyexample.com/metal-on-a15/

**Comment by jonahwilliams** [comment]
> In terms of operations, lossy textures can be render targets, can be the source or destination of blit operations, and can be sampled and read. However, they cannot be used with shader write operations, which precludes some compute use cases.

> Finally, lossy textures must use the private storage mode; they cannot be in shared or managed storage. This implies that [reading back texture data](https://developer.apple.com/documentation/metal/mtltexture/1516318-getbytes) on the CPU will entail an additional blit operation (along with the usual latency-stall tradeoff).

**Comment by chinmaygarde** [comment]
Enabled by @jonahwilliams in https://github.com/flutter/engine/pull/40520. We'll keep an eye out for regressions in https://github.com/flutter/flutter/issues/123290.
