### ISSUE TITLE
[Impeller] ComputeCommands should generate a validation routine to make sure that all expected buffers are bound.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#122937]
I was debugging a test where I forgot to bind a buffer I added to the shader and felt very confused about the results. When run through Xcode, I got a nice validation message from Metal - it should be trivial to add some debug validation as well to generated ComputeCommand code.

**Comment by jonahwilliams** [comment]
The Vulkan validation layers do this for us, so as long as we have unit tests we are covered. Closing
