### ISSUE TITLE
[Impeller] Get rid of an extra copy during texture upload by decompressing to a device buffer.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#122914]
A [temporary host allocation is created](https://github.com/flutter/engine/blob/991cf41eb850235af9559efc281db79644797902/lib/ui/painting/image_decoder_impeller.cc#L174) when image decompression before that allocation is transferred over to the device. Depending on the need for a staging buffer, yet another copy may be necessary. The image decoders should decompress directly into a device buffer. The buffer could then be used as a staging buffer or transmuted into a texture directly.

**Comment by chinmaygarde** [comment]
There is an `SkBitmap::tryAllocPixels` variant that takes a custom allocator. That allocator can be made to return an `impeller::DeviceBuffer` mapping.

**Comment by jonahwilliams** [comment]
We also do this for multiframe codecs (gifs), but that codec class needs substantially more work to remove this allocation

**Comment by jonahwilliams** [comment]
Need to add support to the blit copy for gles and vulkan support, but done for metal

**Comment by chinmaygarde** [comment]
Fixed https://github.com/flutter/flutter/issues/123468 as a followup for Vulkan and GLES. Closing this as done.
