### ISSUE TITLE
Stocks FAB "+" sometimes teleports to near the top left

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1229]
If you launch stocks, once the stocks data loads, the FAB rebuilds and the + image becomes tiny teeny and teleports to near the top left of the list. It's obvious if you switch to the dark theme.

cc @HansMuller who has played with FABs recently and @abarth who has played with the compositor recently.

**Comment by Hixie** [comment]
@abarth Hans says it works on his device which has his FAB changes but not your compositor changes.

**Comment by abarth** [comment]
I haz fix.

**Comment by abarth** [comment]
Fixed in 17ed6993976aa11a54ac4c1af77fc4020b57eb44
