### ISSUE TITLE
[Desktop] SelectableText scrollbar can't hide.

### ISSUE THREAD

**Issue by chifandeyu** [flutter/flutter#122947]
Test code:

```
ConstrainedBox(
            constraints: const BoxConstraints(maxHeight: 80),
            child: const SelectableText(
              '''ASHDGHOAIHSGOHAASHDGHOAIHSGOHAOISDH
              FGIoAOSDJASHDGHOAIHSGOHAOISDHFGIoAOSD
              JGOASHDGHOAIHSGOHAOISDHFGIoAOSDJGOIJ
              AOSDGIOAJIOSJDIOGOIIJAOSDGIOAJIOSJDI
              OASHDGHOAIHSGOHAOISDHFGIoAOSDJGOIJAO
              SDGIOAJIOSJDIOGOIGOIGOIJAOSDGIOAJIOS
              JDIOGOIOISDHFGIoASHDGHOAIHSGASHDGHOA
              IHSGOHAOISDHFGIoAOSDJGOIJAOSDGIOAJIOS
              JDIOGOIOHAOISDHFGIoAOSDJGOIJAOSDGIOA
              JIOSJDIOGOIAOSDJGOIJAOSDGIOAJIOSJDIOGOI''',
              scrollPhysics: NeverScrollableScrollPhysics(),
              style: TextStyle(overflow: TextOverflow.ellipsis),
            ),
          )
```

You can disable scrolling with the mouse wheel. But moving the mouse over scroll bar will show and drag-and-drop scrolling is possible.

**Comment by exaby73** [comment]
## Triage report

While I cannot scroll the view by dragging the scroll bar, I can still see it even after adding a `ScrollConfiguration` with `MaterialScrollBehavior.scrollbars: false` or adding a `Scrollbar` with `thumbVisibility: false`.

<details>
<summary>Code Sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final controller = ScrollController();

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ConstrainedBox(
          constraints: const BoxConstraints(maxHeight: 80),
          child: ScrollConfiguration(
            behavior:
                const MaterialScrollBehavior().copyWith(scrollbars: false),
            child: const SelectableText(
              '''ASHDGHOAIHSGOHAASHDGHOAIHSGOHAOISDH
                FGIoAOSDJASHDGHOAIHSGOHAOISDHFGIoAOSD
                JGOASHDGHOAIHSGOHAOISDHFGIoAOSDJGOIJ
                AOSDGIOAJIOSJDIOGOIIJAOSDGIOAJIOSJDI
                OASHDGHOAIHSGOHAOISDHFGIoAOSDJGOIJAO
                SDGIOAJIOSJDIOGOIGOIGOIJAOSDGIOAJIOS
                JDIOGOIOISDHFGIoASHDGHOAIHSGASHDGHOA
                IHSGOHAOISDHFGIoAOSDJGOIJAOSDGIOAJIOS
                JDIOGOIOHAOISDHFGIoAOSDJGOIJAOSDGIOA
                JIOSJDIOGOIAOSDJGOIJAOSDGIOAJIOSJDIOGOI''',
              scrollPhysics: NeverScrollableScrollPhysics(),
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

<details>
<summary>Screenshot<summary>

![image](https://user-images.githubusercontent.com/50555895/226274283-f4c1766c-4fe8-4093-a383-31732414a109.png)

</details>

**Comment by chifandeyu** [comment]
> 

Thank you very much. Use your try to avoid scrollbar display.

**Comment by chifandeyu** [comment]
> ## Triage report
> While I cannot scroll the view by dragging the scroll bar, I can still see it even after adding a with or adding a with .`ScrollConfiguration``MaterialScrollBehavior.scrollbars: false``Scrollbar``thumbVisibility: false`
> 
> Code Sample
> ```dart
> import 'package:flutter/material.dart';
> 
> void main() {
>   runApp(const MyApp());
> }
> 
> class MyApp extends StatelessWidget {
>   const MyApp({super.key});
> 
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Flutter Demo',
>       theme: ThemeData(
>         primarySwatch: Colors.blue,
>       ),
>       home: const MyHomePage(),
>     );
>   }
> }
> 
> class MyHomePage extends StatefulWidget {
>   const MyHomePage({super.key});
> 
>   @override
>   State<MyHomePage> createState() => _MyHomePageState();
> }
> 
> class _MyHomePageState extends State<MyHomePage> {
>   final controller = ScrollController();
> 
>   @override
>   void dispose() {
>     controller.dispose();
>     super.dispose();
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       body: Center(
>         child: ConstrainedBox(
>           constraints: const BoxConstraints(maxHeight: 80),
>           child: ScrollConfiguration(
>             behavior:
>                 const MaterialScrollBehavior().copyWith(scrollbars: false),
>             child: const SelectableText(
>               '''ASHDGHOAIHSGOHAASHDGHOAIHSGOHAOISDH
>                 FGIoAOSDJASHDGHOAIHSGOHAOISDHFGIoAOSD
>                 JGOASHDGHOAIHSGOHAOISDHFGIoAOSDJGOIJ
>                 AOSDGIOAJIOSJDIOGOIIJAOSDGIOAJIOSJDI
>                 OASHDGHOAIHSGOHAOISDHFGIoAOSDJGOIJAO
>                 SDGIOAJIOSJDIOGOIGOIGOIJAOSDGIOAJIOS
>                 JDIOGOIOISDHFGIoASHDGHOAIHSGASHDGHOA
>                 IHSGOHAOISDHFGIoAOSDJGOIJAOSDGIOAJIOS
>                 JDIOGOIOHAOISDHFGIoAOSDJGOIJAOSDGIOA
>                 JIOSJDIOGOIAOSDJGOIJAOSDGIOAJIOSJDIOGOI''',
>               scrollPhysics: NeverScrollableScrollPhysics(),
>             ),
>           ),
>         ),
>       ),
>     );
>   }
> }
> ```
> 
> Screenshot

Thank you very much. Use your try to avoid scrollbar display.
