### ISSUE TITLE
Highlighting remains visible after changes to Slider and DropdownButton widgets

### ISSUE THREAD

**Issue by moshestanylov** [flutter/flutter#122901]
The highlighting around the slider tick remains visible after the change to the widget completes, same goes for highlighting on dropdown items. The issue was found on a linux desktop app but can be reproduced in dart pad, see code below.

![Screenshot from 2023-03-17 10-02-03](https://user-images.githubusercontent.com/108144720/225971168-7f6adb46-aaaf-4006-95f4-2f7ce568798d.png)
![Screenshot from 2023-03-17 10-02-07](https://user-images.githubusercontent.com/108144720/225971187-2f71d64e-5827-4f73-98b2-09e07494c24c.png)
![Screenshot from 2023-03-17 10-02-14](https://user-images.githubusercontent.com/108144720/225971196-b31a594a-7af2-4692-b467-a08669d44699.png)
![Screenshot from 2023-03-17 10-02-19](https://user-images.githubusercontent.com/108144720/225971208-14b8f2ec-2242-4996-ae9a-239a53f5bde7.png)
![Screenshot from 2023-03-17 10-02-23](https://user-images.githubusercontent.com/108144720/225971221-65103d51-a7c2-402c-8b54-8e36765555f6.png)
![Screenshot from 2023-03-17 10-02-28](https://user-images.githubusercontent.com/108144720/225971234-f97cb61c-1c7e-43f6-8cdc-ea9ce7a245db.png)
![Screenshot from 2023-03-17 10-02-35](https://user-images.githubusercontent.com/108144720/225971249-643af564-47e2-4ab3-b350-7919f603bed1.png)

```Dart
// Copyright (c) 2019, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;

  const MyHomePage({
    Key? key,
    required this.title,
  }) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  double sliderValue = 0;
  String dropdownValue = 'a';

  List<DropdownMenuItem> getItems() {
    List<DropdownMenuItem> items = [];
    for (String label in ['a', 'b', 'c']) {
      items.add(
        DropdownMenuItem(
          value: label,
          child: Text(label),
        ),
      );
    }
    return items;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            DropdownButton(
                value: dropdownValue,
                items: getItems(),
                onChanged: (value) {
                  setState(() {
                    dropdownValue = value;
                  });
                }),
            Slider(
              value: sliderValue,
              min: 0,
              max: 10,
              onChanged: (value) {
                setState(() {
                  sliderValue = value;
                });
              },
            ),
          ],
        ),
      ),
    );
  }
}
```

**Comment by jason-simmons** [comment]
This behavior was implemented based on the Material 3 specification (see https://github.com/flutter/flutter/pull/113543)

**Comment by himanshu21072002** [comment]
Hi,
My name is Himanshu Gangwar, I have been working with flutter for more than one and a half year.
I want to solve this issue so can you please assign this issue to me.

**Comment by exaby73** [comment]
This seems to be working as expected based on https://github.com/flutter/flutter/pull/113543. Closing for the same reason

**Comment by moshestanylov** [comment]
According to the material component demo https://material-components.github.io/material-web/demos/slider/ clicking or tapping anywhere on the screen should clear the highlighting, this is not the current behavior.

**Comment by exaby73** [comment]
This is because the `Slider` has focus. You can achieve this by wrapping your `Scaffold` in a `GestureDetector` and `onTap` call `FocusScope.of(context).unfocus()` to unfocus any widget on the screen
