### ISSUE TITLE
App crash when using soft keyboard's extra function in some phone.

### ISSUE THREAD

**Issue by godfeather** [flutter/flutter#122997]
Hello every flutter developers, some phone with Android OS has a "text Edit" function, tap the "start Selection" then app is crash.

i tried 3 phone all can reproduce this issue. the following is detail of those phone:
1. Galaxy S22 Ultra
   Model: SM-S9080
   System Version: Android 13
2. Honor 20 Pro
   Model: YAL-AL10
   System Version: Harmony 2.0.0
3. Vivo Y30 standard
   Model: V2036A
   Android: 10

Currently "Sougo input method" has this function may reproduce this issue.

The crash stack trace print is :
<img width="1687" alt="image" src="https://user-images.githubusercontent.com/51359288/226297581-31d67c8a-ed1b-4c27-bdeb-36c9fd52de52.png">

The "flutter doctor" print is:

<img width="678" alt="image" src="https://user-images.githubusercontent.com/51359288/226301326-09b21bb7-b501-4cb4-85c7-533f2229b497.png">

**Comment by exaby73** [comment]
Hello @godfeather. I noticed you running an older version of Flutter. Could you try upgrading to the latest stable (3.7.7) and retry?

**Comment by godfeather** [comment]
> Hello @godfeather. I noticed you running an older version of Flutter. Could you try upgrading to the latest stable (3.7.7) and retry?

**Comment by godfeather** [comment]
@exaby73 Thank you so much, I have upgraded the flutter then this issue gone.
