### ISSUE TITLE
[web, wasm] When wasm fails to load, print chrome details + option to update element

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#122978]
Right now if a demo is loaded in non-chrome and/or without the right flags nothing helpful happens

- [ ] include that things are currently tested in Chrome v111 w/ which flags
- [ ] Have some (pluggable) way so folks can show the error in html. Maybe look for a well defined function or something that could be overridden

CC @eyebrowsoffire @joshualitt

**Comment by eyebrowsoffire** [comment]
I think we should just close this. The bootstrapping code is going to just fall back to JS if needed, so there is no need for an error message.
