### ISSUE TITLE
semantics label disappeared on TextField after upgrading from flutter 3.3.x to 3.7.x

### ISSUE THREAD

**Issue by mato7511** [flutter/flutter#122967]
## Steps to Reproduce

1. run sample app
2. create uiautomator dump

**Expected results:**
<details><summary>result (screenshot) on flutter 3.3.10</summary>
<p>

![expected](https://user-images.githubusercontent.com/32419733/226162325-fd933833-1ba5-464e-af77-220fb2019360.png)

</p>
</details> 
<details><summary>result (xml) on flutter 3.3.10</summary>
<p>

```
<hierarchy rotation="0">
	<node index="0" text="" resource-id="" class="android.widget.FrameLayout" package="com.example.untitled" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,2138]">
		<node index="0" text="" resource-id="" class="android.widget.LinearLayout" package="com.example.untitled" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,2138]">
			<node index="0" text="" resource-id="android:id/content" class="android.widget.FrameLayout" package="com.example.untitled" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,2138]">
				<node index="0" text="" resource-id="" class="android.widget.FrameLayout" package="com.example.untitled" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,2138]">
					<node index="0" text="" resource-id="" class="android.view.View" package="com.example.untitled" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,2138]">
						<node index="0" text="" resource-id="" class="android.view.View" package="com.example.untitled" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,2138]">
							<node index="0" text="" resource-id="" class="android.view.View" package="com.example.untitled" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,2138]">
								<node index="0" text="" resource-id="" class="android.view.View" package="com.example.untitled" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,2138]">
									<node index="0" text="semantics-label text-field" resource-id="" class="android.widget.EditText" package="com.example.untitled" content-desc="" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,1123][1080,1277]"/></node>
							</node>
						</node>
					</node>
				</node>
			</node>
		</node>
	</node>
</hierarchy>
``` 

</p>
</details> 
<details><summary>flutter doctor -v on 3.3.10</summary>
<p>

[✓] Flutter (Channel stable, 3.3.10, on Ubuntu 20.04.6 LTS 5.4.0-144-generic, locale en_US.UTF-8)
    • Flutter version 3.3.10 on channel stable at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (3 months ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /opt/android/sdk/
    • Platform android-33-ext5, build-tools 33.0.2
    • Java binary at: /opt/android/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
    ✗ CMake is required for Linux development.
      It is likely available from your distribution (e.g.: apt install cmake), or can be downloaded from https://cmake.org/download/
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
    • pkg-config version 0.29.1
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)

[✓] Android Studio (version 2022.1)
    • Android Studio at /opt/android/android-studio
    • Flutter plugin version 72.1.2
    • Dart plugin version 221.6103.1
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3)
    • IntelliJ at /opt/idea
    • Flutter plugin version 72.1.4
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64 • Android 12 (API 31) (emulator)
    • Linux (desktop)              • linux         • linux-x64   • Ubuntu 20.04.6 LTS 5.4.0-144-generic

[✓] HTTP Host Availability
    • All required HTTP hosts are available

</p>
</details> 

**Actual results:**
<details><summary>result (screenshot) on flutter 3.7.7</summary>
<p>

![actual](https://user-images.githubusercontent.com/32419733/226163487-c41624ed-f6d2-4f30-9d55-02ae5985fc27.png)

</p>
</details> 
<details><summary>result (xml) on flutter 3.7.7</summary>
<p>

```
<hierarchy rotation="0">
	<node index="0" text="" resource-id="" class="android.widget.FrameLayout" package="com.example.untitled" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,2138]">
		<node index="0" text="" resource-id="" class="android.widget.LinearLayout" package="com.example.untitled" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,2138]">
			<node index="0" text="" resource-id="android:id/content" class="android.widget.FrameLayout" package="com.example.untitled" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,2138]">
				<node index="0" text="" resource-id="" class="android.widget.FrameLayout" package="com.example.untitled" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,2138]">
					<node index="0" text="" resource-id="" class="android.view.View" package="com.example.untitled" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,2138]">
						<node index="0" text="" resource-id="" class="android.view.View" package="com.example.untitled" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,2138]">
							<node index="0" text="" resource-id="" class="android.view.View" package="com.example.untitled" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,2138]">
								<node index="0" text="" resource-id="" class="android.view.View" package="com.example.untitled" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,2138]">
									<node NAF="true" index="0" text="" resource-id="" class="android.widget.EditText" package="com.example.untitled" content-desc="" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,1123][1080,1277]"/></node>
							</node>
						</node>
					</node>
				</node>
			</node>
		</node>
	</node>
</hierarchy>
``` 

</p>
</details> 
<details><summary>flutter doctor -v on 3.7.7</summary>
<p>

[!] Flutter (Channel stable, 3.7.7, on Ubuntu 20.04.6 LTS 5.4.0-144-generic, locale en_US.UTF-8)
    • Flutter version 3.7.7 on channel stable at /opt/flutter
    ! The dart binary is not on your path. Consider adding /opt/flutter/bin to your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (11 days ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /opt/android/sdk/
    • Platform android-33-ext5, build-tools 33.0.2
    • Java binary at: /opt/android/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
    ✗ CMake is required for Linux development.
      It is likely available from your distribution (e.g.: apt install cmake), or can be downloaded from https://cmake.org/download/
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
    • pkg-config version 0.29.1
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)

[✓] Android Studio (version 2022.1)
    • Android Studio at /opt/android/android-studio
    • Flutter plugin version 72.1.2
    • Dart plugin version 221.6103.1
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3)
    • IntelliJ at /opt/idea
    • Flutter plugin version 72.1.4
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64 • Android 12 (API 31) (emulator)
    • Linux (desktop)              • linux         • linux-x64   • Ubuntu 20.04.6 LTS 5.4.0-144-generic

[✓] HTTP Host Availability
    • All required HTTP hosts are available

</p>
</details> 

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: Center(
          child: Semantics(
            label: 'semantics-label',
            child: TextFormField(
              decoration: const InputDecoration(label: Text('text-field')),
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

**Comment by darshankawar** [comment]
@mato7511 
There's a similar open issue describing your case, https://github.com/flutter/flutter/issues/119326, so follow-up in it and underlying comments for further updates.
Closing this as a duplicate.
