### ISSUE TITLE
'package:flutter/src/widgets/overscroll_indicator.dart': Failed assertion: line 243 pos 14: 'notification.metrics.axis == widget.axis': is not true.

### ISSUE THREAD

**Issue by chiragmundhava** [flutter/flutter#123002]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by huycozy** [comment]
Hi @chiragmundhava 
Please don't try to create multiple similar issues without providing information. I will close this issue with the same response at https://github.com/flutter/flutter/issues/123001#issuecomment-1476053504. 

Also, based on your issue title, I see there is an issue that has more full stack trace, you can check an answer at https://github.com/flutter/flutter/issues/107772#issuecomment-1219906155 that may be applicable for your case.
