### ISSUE TITLE
DataTable: customizable mouse cursor

### ISSUE THREAD

**Issue by jpnurmi** [flutter/flutter#123020]
## Use case

It would be nice to be able to set the [basic](https://api.flutter.dev/flutter/services/SystemMouseCursors/basic-constant.html) mouse cursor on desktop platforms to match the look'n'feel of the desktop and other apps around.

![image](https://user-images.githubusercontent.com/140617/226389422-f8174dfc-6187-497d-90fb-bdec7f1289b1.png)

[DataTable](https://api.flutter.dev/flutter/material/DataTable-class.html) does not expose API for setting the mouse cursor. Given that interactive table rows are wrapped with [TableRowInkWell](https://api.flutter.dev/flutter/material/TableRowInkWell-class.html), the mouse cursor ends up being InkWell's default i.e. the [clickable](https://api.flutter.dev/flutter/services/SystemMouseCursors/clickable-constant.html) mouse cursor.

## Proposal

Expose API to be able to set mouse cursor on desktop platforms.

## Related issues

- https://github.com/flutter/flutter/issues/88371
- https://github.com/flutter/flutter/issues/59576
- https://github.com/canonical/ubuntu-desktop-installer/issues/1532

**Comment by TahaTesser** [comment]
Working on this @jpnurmi.
Should be an easy fix.

**Comment by jpnurmi** [comment]
@TahaTesser wow, that was quick! :rocket: looks good! notice that the header may also change the cursor if sortable.

**Comment by TahaTesser** [comment]
@jpnurmi 
Add cursor customizable for header cell as well. Id appreciate it if you can test my code implementation and provide any feedback on the behavior and naming https://github.com/flutter/flutter/pull/123128
