### ISSUE TITLE
[in-app-purchases][Android TV] Error while retrieving information from server [DF-DFERH-01]

### ISSUE THREAD

**Issue by phamdanh** [flutter/flutter#123083]
I have an App using the in_app_purchase package, everything works fine on Android mobile phone, but when I purchase an item on Android TV, it gives an error "Error while retrieving information from server [DF-DFERH-01]"

**Comment by danagbemava-nc** [comment]
Hi @phamdanh, this is not an issue with the plugin. It could rise for any number of reasons. See https://www.androiddata-recovery.com/blog/google-play-store-error-df-dferh-01#:~:text=Quick%20Answer%3A,below%20in%20this%20troubleshooting%20guide.

Closing as this is not an issue with the plugin. 

Thank you
