### ISSUE TITLE
App crashes on /lib/arm64 - couldn't find "libflutter.so"

### ISSUE THREAD

**Issue by Jai05-techie** [flutter/flutter#123091]
Hello, I recently released my application on the Play Store and I've been receiving a large number of crash reports as below.

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mynewsapp/com.mynewsapp.MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.mynewsapp-gPJd8MyNcgdyJYrEzcZOUw==/base.apk"],nativeLibraryDirectories=[/data/app/com.mynewsapp-gPJd8MyNcgdyJYrEzcZOUw==/lib/arm64, /system/lib64, /product/lib64]]] couldn't find "libflutter.so"
```
We know flutter doesn't support x86 on aab but this is happening from lib/arm64 couldn't find "libflutter.so". Hence I extracted the aab file which I released and it has only these folders under lib arm64-v8a, armeabi-v7a, and x86_64.

Can anyone help me to solve this? Why arm64 folder not there? And who are those users?

Below am attaching the screenshots,

**First snap:** abb extracted lib folder
**Second snap:** Crashed devices name

<img width="483" alt="Screenshot 2023-03-21 at 11 06 48 AM" src="https://user-images.githubusercontent.com/62050139/226532799-563389b3-3c0c-48be-ad69-58a14450a034.png">
<img width="400" alt="Screenshot 2023-03-21 at 11 09 12 AM" src="https://user-images.githubusercontent.com/62050139/226532808-7f1cb956-404d-4fbb-a8b7-bfe7c2ecc2ce.png">

**Comment by darshankawar** [comment]
@Jai05-techie 
There's a similar issue open describing your case, https://github.com/flutter/flutter/issues/83596 so follow-up in it for further updates. You may share your findings in that issue for better tracking and can look at underlying comments to see if they help in your case.
Closing this as a duplicate.
