### ISSUE TITLE
[Impeller] Better scheduling of texture upload during image decoding.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#123058]
Currently the frame capture when navigating to a page with a lot of images looks a lot like the following. Because we upload concurrently from N threads, we can end up overloading the GPU and competing with the normal frame workload.

![image (12)](https://user-images.githubusercontent.com/8975114/226461188-874e79ce-5fcf-4285-8986-2c68bf4974d1.png)

To improve this, I'm going to force serialization of upload by posting the upload task to the io runner. This shouldn't be necessary, but we'll need some way to throttle uploads and/or avoid competing with the raster workloads before relanding support for this

**Comment by dnfield** [comment]
Actually I see why not - we moved to the concurrent runner because the IO task runner could get really bogged down if you decoded a lot of images.

**Comment by chinmaygarde** [comment]
What we have now is probably the best we can do on Metal right? Throttling IO workloads seems like the right thing to do since those are frame time senstive. Or, is there some sort of prioritization mechanism with Metal?

**Comment by jonahwilliams** [comment]
This probably needs more investigation.
