### ISSUE TITLE
tests failing on current beta branch (flutter-3.9-candidate.1)

### ISSUE THREAD

**Issue by XilaiZhang** [flutter/flutter#123052]
This is first discovered in https://github.com/flutter/flutter/pull/122645/checks?check_run_id=12008937385 by @godofredoc , that several tests are consistently failing on pull requests opened against the beta branch. 

It was later triaged by @christopherfujino and @pdblasi-google that a cherry pick is needed.
Creating this issue, so I can refer to this issue on the actual issue for the cherry pick request onto the beta branch.

**Comment by keyonghan** [comment]
Closing as obsolete.
