### ISSUE TITLE
Migrate to --suppress-analytics flag

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#123066]
https://github.com/dart-lang/sdk/commit/68353d76a49 deprecated the --no-analytics, which flutter seems to be using. When updating my branch to the latest flutter master and then running the `flutter` tool for the first time it prints:

```
Building flutter tool...
`--[no-]analytics` is deprecated.  Use `--suppress-analytics` to disable analytics for one run instead.
```

**Comment by goderbauer** [comment]
cc @christopherfujino Might be worthwhile to fix this as part of getting ready for dart 3 (https://github.com/flutter/flutter/issues/118837).

**Comment by christopherfujino** [comment]
@goderbauer thanks for the tip
