### ISSUE TITLE
[CP] <add cpu dimension for arm packaging>

### ISSUE THREAD

**Issue by XilaiZhang** [flutter/flutter#123041]
### issue_link

https://github.com/flutter/flutter/issues/122769

### Commit Hash

cf18456

### Target

beta

### pr_link

https://github.com/flutter/flutter/pull/123037

### Impacted Users

users who download flutter beta from https://docs.flutter.dev/development/tools/sdk/releases?tab=macos

### Impact Description

users who download macos beta binary from https://docs.flutter.dev/development/tools/sdk/releases?tab=macos will get confused since they could not find the arm version.

### Workaround

if the user already have flutter installed, they can do 
```
flutter channel beta
flutter upgrade
```

### Risk

low

### Test Coverage

yes

### Validation Steps

mac arm beta binary should show up on https://docs.flutter.dev/development/tools/sdk/releases?tab=macos if this works

**Comment by XilaiZhang** [comment]
@christopherfujino @godofredoc will have the expertise to review

**Comment by christopherfujino** [comment]
LGTM

**Comment by XilaiZhang** [comment]
Closing after merge
