### ISSUE TITLE
[camera] green screen after photo capture on huawei tv

### ISSUE THREAD

**Issue by mat20s23** [flutter/flutter#123003]
i'm running app on a huawei tv with android 9. after capturing the photo, a preview image appears completely green. Does anyone know what can it be?

```
 _controller = CameraController(
      // Get a specific camera from the list of available cameras.
      widget.camera,

      // Define the resolution to use.
      ResolutionPreset.high,
      enableAudio: false
    );

    // Next, initialize the controller. This returns a Future.
    _initializeControllerFuture = _controller.initialize();
```

```
_body() {
    Size size = MediaQuery.of(context).size;
    double width = size.width > size.height ? size.height : size.width;
    bool isTablet = width > 600;
    return SingleChildScrollView(
      child: Center(
        child: Wrap(
          spacing: 8,
          children: [ Center(
              child: Image.file(File(widget.imagePath),
                height: isTablet ? 600: 300,
                fit: BoxFit.cover,
                alignment: Alignment.center,)),
            SizedBox(height: 40,),

        ]),
      ),
    );
  }
```

**Comment by mat20s23** [comment]
camera 0.10.3+2
tv physical device
tv model: Huawei IdeaHub Pro 65


[√] Flutter (Channel stable, 3.7.3, on Microsoft Windows [versÆo 10.0.19045.2604], locale pt-BR)
    • Flutter version 3.7.3 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (6 weeks ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\xxxx\AppData\Local\Android\sdk
    • Platform android-33-ext4, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Professional 2022 17.5.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
    • Visual Studio Professional 2022 version 17.5.33424.131
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
      development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] VS Code, 64-bit edition (version 1.75.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [versÆo 10.0.19045.2604]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 108.0.5359.125
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 111.0.1661.44

[√] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by darshankawar** [comment]
Thanks for the update. Can you try the same using latest master version as well ?
Since I don't have the specific device to verify on, please try to run the [plugin example](https://github.com/flutter/packages/tree/main/packages/camera/camera/example) on your same device and see if using it, you get same behavior or not.
