### ISSUE TITLE
Can't build IPA: Encountered error while archiving for device

### ISSUE THREAD

**Issue by giovanni256** [flutter/flutter#123051]
Hi there,

I'm building my IPA file to upload it on App Store.
Since I have 2 big files (250k rows), I had to split the biggest functions in order to build the APK file (since I was getting the "Out of memory" error).

Now I'm getting about the same error by building the IPA.

Here is the error that I'm getting:
```
Running Xcode build...
Xcode archive done. 1748s
Failed to build iOS app
Error (Xcode): ===== CRASH =====

Encountered error while archiving for device.
```

The APK/AAB file is ok, but I can't build the IPA.
I'm using the latest flutter version.

**Comment by giovanni256** [comment]
> @giovanni256 We would need a minimal reproducible code sample to properly address the issue you are reporting. Also please provide complete error log for further analysis.

Hi there, the error is already complete.
It doesn't give me more details.

The reproducible code is 250k rows, are you sure? 😅

**Comment by darshankawar** [comment]
> The reproducible code is 250k rows, are you sure? 😅

In order to make this issue actionable, we would need some kind of reproducible code sample so that the team can look into the code. I tried with a sample app which ofcourse doesn't have 250k rows, but was able to build ipa properly without any issues.

**Comment by darshankawar** [comment]
I see in the repo you shared a single file, so whenever you have replicable code, just comment here and will check it out.

**Comment by giovanni256** [comment]
> I see in the repo you shared a single file, so whenever you have replicable code, just comment here and will check it out.

Thank you for your help!
Since I'm new in creating repositories, I made a mistake so I had to create a new one where I invited you.

I don't know if the app is running since it doesn't mind, but the error is replicated since I can't build the IPA file.
Let me know if you need more information.

Thanks in advance!

**Comment by darshankawar** [comment]
I cloned the repo and ran `flutter build ipa` using latest stable version but got below while compiling:

```
💪 Building with sound null safety 💪

Expected ios/Runner.xcodeproj/project.pbxproj but this file is missing.
Application not configured for iOS

```

**Comment by giovanni256** [comment]
> I cloned the repo and ran `flutter build ipa` using latest stable version but got below while compiling:
> 
> ```
> 💪 Building with sound null safety 💪
> 
> Expected ios/Runner.xcodeproj/project.pbxproj but this file is missing.
> Application not configured for iOS
> ```

Sorry my friend, I made a mistake by testing the app on another folder.
I just uploaded the new files.

**Comment by darshankawar** [comment]
Sorry, I cloned `ta` repo and don't see `ios` folder in it, so getting `ios` is not configured for the project.

**Comment by giovanni256** [comment]
> Sorry, I cloned `ta` repo and don't see `ios` folder in it, so getting `ios` is not configured for the project.

Hi there, you should use the taN repo.
I just removed you from the other one.

**Comment by darshankawar** [comment]
Tried `flutter build ipa` on `taN` repo but have been getting below:

```
Xcode archive done.                                         10.8s
Failed to build iOS app
Error (Xcode): No profiles for 'it.iovara.trainassistant' were found: Xcode
couldn't find any iOS App Development provisioning profiles matching
'it.iovara.trainassistant'. Automatic signing is disabled and unable to generate
a profile. To enable automatic signing, pass -allowProvisioningUpdates to
xcodebuild.


Error (Xcode): No profiles for
'it.iovara.trainassistant.OneSignalNotificationServiceExtension' were found:
Xcode couldn't find any iOS App Development provisioning profiles matching
'it.iovara.trainassistant.OneSignalNotificationServiceExtension'. Automatic
signing is disabled and unable to generate a profile. To enable automatic
signing, pass -allowProvisioningUpdates to xcodebuild.



It appears that there was a problem signing your application prior to
installation on the device.

Verify that the Bundle Identifier in your project is your signing id in Xcode
  open ios/Runner.xcworkspace

Also try selecting 'Product > Build' to fix the problem.
Encountered error while archiving for device.
dhs@Dhss-MacBook-Pro taN % 

```

I tried to use the correct provisioning profile using my apple dev account:

<img width="519" alt="Screenshot 2023-03-28 at 10 32 41 AM" src="https://user-images.githubusercontent.com/67046386/228133279-8f7f10c8-4107-4839-9ee7-5925543102dd.png">

So, is there a way for you to make the repro simple so that we can make this issue actionable for the team ?

**Comment by giovanni256** [comment]
> Tried `flutter build ipa` on `taN` repo but have been getting below:
> 
> ```
> Xcode archive done.                                         10.8s
> Failed to build iOS app
> Error (Xcode): No profiles for 'it.iovara.trainassistant' were found: Xcode
> couldn't find any iOS App Development provisioning profiles matching
> 'it.iovara.trainassistant'. Automatic signing is disabled and unable to generate
> a profile. To enable automatic signing, pass -allowProvisioningUpdates to
> xcodebuild.
> 
> 
> Error (Xcode): No profiles for
> 'it.iovara.trainassistant.OneSignalNotificationServiceExtension' were found:
> Xcode couldn't find any iOS App Development provisioning profiles matching
> 'it.iovara.trainassistant.OneSignalNotificationServiceExtension'. Automatic
> signing is disabled and unable to generate a profile. To enable automatic
> signing, pass -allowProvisioningUpdates to xcodebuild.
> 
> 
> 
> It appears that there was a problem signing your application prior to
> installation on the device.
> 
> Verify that the Bundle Identifier in your project is your signing id in Xcode
>   open ios/Runner.xcworkspace
> 
> Also try selecting 'Product > Build' to fix the problem.
> Encountered error while archiving for device.
> dhs@Dhss-MacBook-Pro taN % 
> ```
> 
> I tried to use the correct provisioning profile using my apple dev account:
> 
> <img alt="Screenshot 2023-03-28 at 10 32 41 AM" width="519" src="https://user-images.githubusercontent.com/67046386/228133279-8f7f10c8-4107-4839-9ee7-5925543102dd.png">
> 
> So, is there a way for you to make the repro simple so that we can make this issue actionable for the team ?

I don't know how to do that in order to let you build the release version.
I think you should change the package name and create an app ID on Apple Developer?

**Comment by darshankawar** [comment]
In order to make this issue actionable and to avoid keep this in limbo, please share the entire verbose log that you are getting, so that it'll be helpful for concerned team to make further analysis.

**Comment by giovanni256** [comment]
> In order to make this issue actionable and to avoid keep this in limbo, please share the entire verbose log that you are getting, so that it'll be helpful for concerned team to make further analysis.

I really appreciate your help.
The error log is already complete, there aren't missing information and you have the reproducible example to confirm it.

What can I do is add you as a Developer (Team Member) in my Apple account in order to let you build the app with the release profile.
I need your email address

**Comment by huycozy** [comment]
Hi @giovanni256 
The issue should be actionable with clear steps to reproduce it and they should be open for others can see/find the similar issue if any. Adding an individual as a member will not be a suitable approach for others to investigate this issue. 

In order to address the issue properly, please provide the complete output of `flutter build ipa -v`. If the log is too long, please save it into a file and attach it here. 

Also, it may be related to OneSignal plugin (since you have seen its error though XCode build), you can try detaching the module related to it from the current project (make sure you back up the project yourself) and see if it is the cause of this issue.

Meanwhile, you may try running the project in `release` mode to see if it can run normally.

**Comment by giovanni256** [comment]
> Hi @giovanni256 The issue should be actionable with clear steps to reproduce it and they should be open for others can see/find the similar issue if any. Adding an individual as a member will not be a suitable approach for others to investigate this issue.
> 
> In order to address the issue properly, please provide the complete output of `flutter build ipa -v`. If the log is too long, please save it into a file and attach it here.
> 
> Also, it may be related to OneSignal plugin (since you have seen its error though XCode build), you can try detaching the module related to it from the current project (make sure you back up the project yourself) and see if it is the cause of this issue.
> 
> Meanwhile, you may try running the project in `release` mode to see if it can run normally.

Hi there, I know that and I'm trying to do everything you ask.
In the meantime that I produce the -v logs, I want you to know that I already tried to build the IPA file without all plugins.

The app doesn't run in release mode on the simulator.

**Comment by huycozy** [comment]
>The app doesn't run in release mode on the simulator.

release mode is not supported on the simulator/emulator. You should try it on a physical device.

**Comment by giovanni256** [comment]
> > The app doesn't run in release mode on the simulator.
> 
> release mode is not supported on the simulator/emulator. You should try it on a physical device.

I will try it ASAP.
I attach the [**complete log**](https://file.io/p940z9qA4eX4), here you have the error:

`"errorSummaries" : {
                         "_type" : {
                           "_name" : "Array"
                         },
                         "_values" : [
                           {
                             "_type" : {
                               "_name" : "IssueSummary"
                             },
                             "issueType" : {
                               "_type" : {
                                 "_name" : "String"
                               },
                               "_value" : "Error"
                             },
                             "message" : {
                               "_type" : {
                                 "_name" : "String"
                               },
                               "_value" : "[+10520 ms] ===== CRASH ====="
                             }
                           }
                         ]
                       },`

**Comment by huycozy** [comment]
Thanks, you should provide the crash log as below. 

<details>
<summary>Snippet crash log (from huge complete log above)</summary>

```bash
                      /Users/macnew/Documents/GitHub/ta/taN/.dart_tool/flutter_build/b697e45da7458a65f6ee00d73a55014d/app.
                       dill
                       [   +3 ms] Persisting file store
                       [  +20 ms] Done persisting file store
                       [  +20 ms] "flutter assemble" took 14.104ms.
                       [        ] ensureAnalyticsSent: 0ms
                       [        ] Running 0 shutdown hooks
                       [        ] Shutdown hooks complete
                       [   +1 ms] exiting with code 1
                       error: [+10520 ms] ===== CRASH =====
                       [   +2 ms] si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0xffffffffffffffff
                       [        ] version=2.19.4 (stable) (Tue Mar 7 09:58:46 2023 +0000) on "macos_simarm64"
                       [        ] pid=29813, thread=-1, isolate_group=isolate(0x7f8918822a00),
                       isolate=isolate(0x7f891881ea00)
                       [        ] os=macos, arch=arm64, comp=no, sim=yes
                       [        ] isolate_instructions=0, vm_instructions=0
                       [   +1 ms]   pc 0x0000000100ccf13a fp 0x00007ff7bf2543d0 dart::String::Equals(dart::String const&)
                       const+0x5a
                       [        ]   pc 0x0000000100db2303 fp 0x00007ff7bf254470
                       dart::Class::GetInvocationDispatcher(dart::String const&, dart::Array const&,
                       dart::UntaggedFunction::Kind, bool) const+0x223
                       [        ]   pc 0x0000000100db5a92 fp 0x00007ff7bf2544e0
                       dart::Function::GetDynamicInvocationForwarder(dart::String const&, bool) const+0xe2
                       [        ]   pc 0x0000000100f656c8 fp 0x00007ff7bf254530 dart::AddNamesToFunctionsTable(dart::Zone*,
                       dart::UnorderedHashMap<dart::NameFunctionsTraits>*, dart::String const&, dart::Function const&,
                       dart::String*, dart::Function*)+0xf8
                       [        ]   pc 0x0000000100f56bcc fp 0x00007ff7bf254640
                       dart::Precompiler::CollectDynamicFunctionNames()+0x2cc
                       [        ]   pc 0x0000000100f55356 fp 0x00007ff7bf254d90 dart::Precompiler::DoCompileAll()+0x1386
                       [        ]   pc 0x0000000100f53f4b fp 0x00007ff7bf2551f0 dart::Precompiler::CompileAll()+0xbb
                       [        ]   pc 0x000000010113ea9c fp 0x00007ff7bf255310 Dart_Precompile+0x21c
                       [        ]   pc 0x0000000100c9bf4b fp 0x00007ff7bf2554a0 dart::bin::main(int, char**)+0x9ab
                       [        ]   pc 0x000000010bfcb51e fp 0x00007ff7bf2555b0 Unknown symbol
                       [        ] -- End of DumpStackTrace
                       [        ] === Crash occurred when compiling unknown function in AOT mode in unknown pass
                       [        ] === Flow Graph not available
                       [   +9 ms] Dart snapshot generator failed with exit code -6
                       [  +25 ms] Target aot_assembly_release failed: Exception: AOT snapshotter exited with code -6
                                  #0      AotAssemblyBase.build
                                  (package:flutter_tools/src/build_system/targets/ios.dart:111:7)
                                  <asynchronous suspension>
                                  #1      _BuildInstance._invokeInternal
                                  (package:flutter_tools/src/build_system/build_system.dart:847:9)
                                  <asynchronous suspension>
                                  #2      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
                                  <asynchronous suspension>
                                  #3      _BuildInstance.invokeTarget
                                  (package:flutter_tools/src/build_system/build_system.dart:785:32)
                                  <asynchronous suspension>
                                  #4      FlutterBuildSystem.build
                                  (package:flutter_tools/src/build_system/build_system.dart:614:16)
                                  <asynchronous suspension>
                                  #5      AssembleCommand.runCommand
                                  (package:flutter_tools/src/commands/assemble.dart:337:32)
                                  <asynchronous suspension>
                                  #6      FlutterCommand.run.<anonymous closure>
                                  (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
                                  <asynchronous suspension>
                                  #7      AppContext.run.<anonymous closure>
                                  (package:flutter_tools/src/base/context.dart:150:19)
                                  <asynchronous suspension>
                                  #8      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
                                  <asynchronous suspension>
                                  #9      FlutterCommandRunner.runCommand.<anonymous closure>
                                  (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
                                  <asynchronous suspension>
                                  #10     AppContext.run.<anonymous closure>
                                  (package:flutter_tools/src/base/context.dart:150:19)
                                  <asynchronous suspension>
                                  #11     FlutterCommandRunner.runCommand
                                  (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
                                  <asynchronous suspension>
                                  #12     run.<anonymous closure>.<anonymous closure>
                                  (package:flutter_tools/runner.dart:64:9)
                                  <asynchronous suspension>
                                  #13     AppContext.run.<anonymous closure>
                                  (package:flutter_tools/src/base/context.dart:150:19)
                                  <asynchronous suspension>
                                  #14     main (package:flutter_tools/executable.dart:91:3)
                                  <asynchronous suspension>

                       [   +3 ms] 
                                  #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
                                  #1      AssembleCommand.runCommand
                                  (package:flutter_tools/src/commands/assemble.dart:354:7)
                                  <asynchronous suspension>
                                  #2      FlutterCommand.run.<anonymous closure>
                                  (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
                                  <asynchronous suspension>
                                  #3      AppContext.run.<anonymous closure>
                                  (package:flutter_tools/src/base/context.dart:150:19)
                                  <asynchronous suspension>
                                  #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
                                  <asynchronous suspension>
                                  #5      FlutterCommandRunner.runCommand.<anonymous closure>
                                  (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
                                  <asynchronous suspension>
                                  #6      AppContext.run.<anonymous closure>
                                  (package:flutter_tools/src/base/context.dart:150:19)
                                  <asynchronous suspension>
                                  #7      FlutterCommandRunner.runCommand
                                  (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
                                  <asynchronous suspension>
                                  #8      run.<anonymous closure>.<anonymous closure>
                                  (package:flutter_tools/runner.dart:64:9)
                                  <asynchronous suspension>
                                  #9      AppContext.run.<anonymous closure>
                                  (package:flutter_tools/src/base/context.dart:150:19)
                                  <asynchronous suspension>
                                  #10     main (package:flutter_tools/executable.dart:91:3)
                                  <asynchronous suspension>
                       Failed to package /Users/macnew/Documents/GitHub/ta/taN.


                       Result bundle written to path:
                       	/var/folders/vh/7hbc4c1s1bx0xhqgfv3ld4tc0000gn/T/flutter_tools.97vPIH/flutter_ios_build_temp_dirw1R
                       	iMT/temporary_xcresult_bundle


                       2023-03-30 14:51:03.019 xcodebuild[20871:80526] Requested but did not find extension point with
                       identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension
                       Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
                       2023-03-30 14:51:03.020 xcodebuild[20871:80526] Requested but did not find extension point with
                       identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension
                       Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in
                       com.apple.dt.IDEWatchSupportCore
                       ** ARCHIVE FAILED **


                       The following build commands failed:
                       	PhaseScriptExecution Run\ Script
                       	/Users/macnew/Library/Developer/Xcode/DerivedData/Runner-gnxxexowrsnqtidpgqlplzysdxbh/Build/Interme
                       	diates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release-iphoneos
                       	/Runner.build/Script-9740EEB61CF901F6004384FC.sh (in target 'Runner' from project 'Runner')
                       (1 failure)
[+9350 ms] Running Xcode build... (completed in 1441,3s)
[        ] Xcode archive done.                                         1441,3s
```
</details>

It may be similar to https://github.com/flutter/flutter/issues/119220 which has been fixed recently and is available on master channel. 

What is your current Flutter version? And have the build worked before on older versions? 
Can you try switching to master channel and retry?

```
flutter channel master
flutter upgrade
```

**Comment by giovanni256** [comment]
> 

Hi there.
I used Flutter 3.3 and then upgrade to 3.7 recently, so I will try to switch to Master channel and then build the IPA.

I will update the comment.

**Comment by giovanni256** [comment]
> Thanks, you should provide the crash log as below.
> 
> Snippet crash log (from huge complete log above)
> It may be similar to #119220 which has been fixed recently and is available on master channel.
> 
> What is your current Flutter version? And have the build worked before on older versions? Can you try switching to master channel and retry?
> 
> ```
> flutter channel master
> flutter upgrade
> ```

Thank you so much, it works!
Thanks also to @darshankawar for the help and for the patience.
