### ISSUE TITLE
[Question] Why are `ThemeExtension`s part of material?

### ISSUE THREAD

**Issue by jtdLab** [flutter/flutter#123054]
Wouldn't it be better to provide the `ThemeExtension`s mechanism from a more general lib like `widgets` and allow `material`, `cupertino`, `fluent_ui`, `macos_ui` and other ui libs to use it consistently without having to depend on `material`?

Or is there anything i am missing why the concept of `ThemeExtension`s is only added to `material`?

**Comment by huycozy** [comment]
Thanks for filing the issue, @jtdLab 
I see there's an open issue (https://github.com/flutter/flutter/issues/116876) that is proposing `extensions` for `CupertinoThemeData`.  

I will close this issue in favor of #116876, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
