### ISSUE TITLE
unable to login to the build dashboard

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#123026]
## observed
Clicking the "sign in" button in the top right brings up the popup to sign in with google, but after clicking my account the UI doesn't change to reflect that I was logged in and I'm unable to rerun tasks. 

## expected

I expect after having clicked my account that the top right "sign in" button will disappear and show who i'm logged in as and allow me to rerun tasks.

cc @CaseyHillers

**Comment by keyonghan** [comment]
@gaaclarke Are you able to sign in after a hard refreshing the dashboard page? I am able to though.
There is some glitch with the sign in button. Related bug: https://github.com/flutter/flutter/issues/121275

**Comment by gaaclarke** [comment]
@CaseyHillers are you sure this is the same error?  That one makes it sound like there is a workaround.  I was unable to work around the issue and was unable to perform the duties of the engine sheriff.

**Comment by CaseyHillers** [comment]
Ah, that's fair @gaaclarke. Thanks for pointing that out.

**Comment by keyonghan** [comment]
This is not a `hard` blocker, reducing to P3. It doesn't sound unreasonable to combine this issue with https://github.com/flutter/flutter/issues/121275, which solves the silent sign in issue.

The workaround is:
1) refresh the dashboard (though it pops up signing you in, it doesn't)
2) click the sign in button.

**Comment by ricardoamador** [comment]
@gaaclarke is this still an issue? @ditman has implemented login via the google sign in button. I don't think this is an issue any longer. Please confirm and close.

**Comment by ditman** [comment]
> Did something change recently in the login flow that requires the People API?

(Good eye @drewroengoogle! in fact the `signIn` method on the web attempts to do more than what it should and part of it was using the People API. I reimplemented the `signIn` using the standard Google Sign In Button, so that People API is not required. I'll probably deprecate the custom `signIn` method on the web so it start throwing exceptions soon-ish!)

**Comment by ditman** [comment]
As @ricardoamador said above, the sign-in (and out) status of the cocoon app should be more robust now.
