### ISSUE TITLE
canvaskit.js  violates the following Content Security Policy directive. Please explain how to fix this

### ISSUE THREAD

**Issue by coppermight** [flutter/flutter#123030]
Refused to load the script 'https://unpkg.com/canvaskit-wasm@0.37.1/bin/canvaskit.js' because it violates the following Content Security Policy directive: "script-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

Context
index.html
Stack Trace
main.dart.js:181 (bUv)

`return s},
bUv(a){var s,r,q="defineProperty"
if(self.exports==null){s=A.m1(A.c(["get",A.ay(new A.b2v(a)),"set",A.ay(new A.b2w()),"configurable",!0],t.N,t.z))
A.R(self.Object,q,[self.window,"exports",s])}if(self.module==null){r=A.m1(A.c(["get",A.ay(new A.b2x(a)),"set",A.ay(new A.b2y()),"configurable",!0],t.N,t.z))
A.R(self.Object,q,[self.window,"module",r])}self.document.head.appendChild(a)},
b10(){var s=0,r=A.Q(t.e),q,p
var $async$b10=A.M(function(a,b){if(a===1)return A.N(b,r)
while(true)switch(s){case 0:s=3
return A.U(A.btK(),$async$b10)
case 3:p=new A.am($.ap,t.lX)`

**Comment by darshankawar** [comment]
Closing this as a duplicate of https://github.com/flutter/flutter/issues/80221
