### ISSUE TITLE
flutter build web failed

### ISSUE THREAD

**Issue by lycshmee** [flutter/flutter#123106]
**flutter doctor**
[√] Flutter (Channel stable, 3.7.7, on Microsoft Windows [版本 10.0.17763.4131], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.2)
[√] Android Studio (version 2022.1)
[√] Android Studio
[√] Connected device (2 available)

**Dependencies:** 
dependencies:
  flutter: 
  sdk: flutter
  cupertino_icons: ^1.0.2
  adaptive_breakpoints: ^0.1.0
  sizer: ^2.0.13
  google_fonts: ^2.1.0
  flutter_svg: ^0.22.0
  animated_text_kit: ^4.2.1
  http: ^0.13.3
  provider: ^6.0.0
  path_provider: ^2.0.13
  flutter_web_plugins:
    sdk: flutter

  string_validator: ^0.3.0
  getwidget: ^2.0.4
  flutter_staggered_grid_view: ^0.4.0
  device_info_plus: ^2.1.0
  recase: ^4.0.0
  number_paginator: ^0.0.2
  photo_view: ^0.12.0
  file_picker: ^4.1.3
  cached_network_image: ^3.1.0
  intl: ^0.17.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^5.0.0-beta.5
  hive_generator: ^1.1.1
  flutter_slider_drawer_v: ^2.0.2
  flutter_inner_drawer:
    git:
      url: https://github.com/kenjishiromajp/flutter_inner_drawer
      ref: kenjishiromajp-update-for-2.12-null-safety-casting
  table_calendar: ^3.0.5
  syncfusion_flutter_calendar: ^20.1.47

**"isn't a type" issues**
/C:/Users/yc/AppData/Local/Pub/Cache/hosted/pub.dev/win32-2.6.1/lib/src/winrt/icalendar.dart:2642:19: Error: 'NativeFunction' isn't a type.
                  NativeFunction<
                  ^^^^^^^^^^^^^^
/C:/Users/yc/AppData/Local/Pub/Cache/hosted/pub.dev/win32-2.6.1/lib/src/winrt/icalendar.dart:2641:15: Error: 'Pointer' isn't a type.
              Pointer<
              ^^^^^^^
/C:/Users/yc/AppData/Local/Pub/Cache/hosted/pub.dev/win32-2.6.1/lib/src/winrt/icalendar.dart:2650:13: Error: 'Pointer' isn't a type.
            Pointer,
            ^^^^^^^
/C:/Users/yc/AppData/Local/Pub/Cache/hosted/pub.dev/win32-2.6.1/lib/src/winrt/icalendar.dart:2651:21: Error: 'Int32' isn't a type.

**JS issues**
/C:/Users/yc/AppData/Local/Pub/Cache/hosted/pub.dev/win32-2.6.1/lib/src/structs.g.dart:7445:16: Error: Only JS interop members may be 'external'.
Try removing the 'external' keyword or adding a JS interop annotation.
  external int dwNumberOfPeers;
               ^
/C:/Users/yc/AppData/Local/Pub/Cache/hosted/pub.dev/win32-2.6.1/lib/src/structs.g.dart:7448:50: Error: Only JS interop members may be 'external'.
Try removing the 'external' keyword or adding a JS interop annotation.
  external Array<WLAN_HOSTED_NETWORK_PEER_STATE> PeerList;
                                                 ^
/C:/Users/yc/AppData/Local/Pub/Cache/hosted/pub.dev/win32-2.6.1/lib/src/structs.g.dart:7457:16: Error: Only JS interop members may be 'external'.
Try removing the 'external' keyword or adding a JS interop annotation.
  external int interfaceType;

**there are many of these two types of errors.**

**Comment by exaby73** [comment]
Hello @lycshmee. Looks like you're using an old version of win32. Try upgrading that package. But even if your issues are not solved, I suggest raising an issue with the package author (https://github.com/timsneath/win32). Since this is not really an issue with Flutter itself, I am closing this issue. Thank you
