### ISSUE TITLE
[Impeller] Tracking: Partial screen flickering on iOS with Impeller enabled.

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#123121]
Split off from https://github.com/flutter/flutter/issues/100522.

This issue is intended to capture reproduction steps from users for apps that are experiencing *partial* screen flickering on iOS with Impeller enabled in Flutter versions newer than 3.7.

Please only comment here with one of two things:
1. A code sample and detailed reproduction steps that triggers the issue, or
1. Full un-redacted device logs collected starting from just before the flickering starts.

Since #100522 got a little bit out of hand, on this issue comments will be hidden, deleted, or split off into separate issues in line with Flutter's issue hygiene policies.

**Comment by jonahwilliams** [comment]
Since no one has filled any details here I think we should close the issue?

**Comment by zanderso** [comment]
This issue has been open for 5 months with no reports, so sgtm. Closing.
