### ISSUE TITLE
`flutter doctor` should warn if Android licenses are not signed.

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#12315]
Spin-off of https://github.com/flutter/flutter/issues/8438.  Hopefully easy to fix?

**Comment by sethladd** [comment]
Yup, this one also happened a lot at Workshops. Can we fix this before the next one, which is on Oct 31st?

**Comment by sethladd** [comment]
cc @mit-mit

**Comment by mit-mit** [comment]
This is https://github.com/flutter/flutter/issues/8093, see my comments over there.
