### ISSUE TITLE
android flutter run -Unable to locate gradlew script

### ISSUE THREAD

**Issue by zhangcf2012** [flutter/flutter#12316]
## Steps to Reproduce
this is android

flutter create myapp
cd myapp
flutter run

## Logs
flutter run
Launching lib/main.dart on SM G906S in debug mode...
Initializing gradle...                                   -Unable to locate gradlew script

## Flutter Doctor

flutter doctor
[✓] Flutter (on Mac OS X 10.11.4 15E65, locale zh-Hans, channel alpha)
    • Flutter at /Users/zcf2015/flutter
    • Framework revision 701d534ba9 (2 weeks ago), 2017-09-12 14:01:51 -0700
    • Engine revision 31d03de019
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/zcf2015/adt-bundle-mac-x86_64-20140624/sdk
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = /Users/zcf2015/adt-bundle-mac-x86_64-20140624/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] iOS toolchain - develop for iOS devices (Xcode 7.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3, Build version 7D175
    ✗ Flutter requires a minimum Xcode version of 8.0.0.
      Download the latest version or update via the Mac App Store.
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Connected devices
    • SM G906S • 83334ffb • android-arm • Android 5.0.1 (API 21)

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by Hixie** [comment]
Can you still reproduce this?
