### ISSUE TITLE
Divider 

### ISSUE THREAD

**Issue by dreamerlaveena** [flutter/flutter#123102]
hello ,
i just want to ask  about divider in dart programming language in  listtile . but mai divider har jaga nahi dena chhati hu 2 jaga dena chati hu

**Comment by huycozy** [comment]
_"I just want to ask about adding a divider in the Dart programming language for a ListTile. But I don't want to give the divider everywhere, I want to add it in two places."_ (Using translation service)

It seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any. You may also get some help if you post it on https://flutter.dev/community or https://www.reddit.com/r/flutterhelp.

Closing, as this isn't a Flutter framework bug or feature request.

**Comment by dreamerlaveena** [comment]
okay thankyou so much
