### ISSUE TITLE
Dart 3 cleanup: Remove work around for ContinueSwitchStatement crash on web

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#123171]
Once https://github.com/dart-lang/sdk/issues/51802 is resolved, we should remove the work around put in place for it by reverting this commit: https://github.com/flutter/flutter/pull/122546/commits/39d8336fe70c31482f74d1831ce21e95355c5da6

**Comment by rakudrama** [comment]
An alternative to reinstating the ContinueSwitchStatement is to `break` and put the 'glow' code after the outer switch.

There is no equivalent to continue-switch in JavaScript, so dart2js and DDC have to contrive that the switch is wrapped in a loop so it can be re-entered to divert control-flow to the other case. So continue-switch is not exactly the simple 'goto' that it appears to be. The combination of infrequent use and implementation complexity is why we keep finding bugs with the feature (e.g. https://github.com/dart-lang/sdk/issues/51777).
