### ISSUE TITLE
Android app crashes after using SystemNavigator.pop() method，SIGSEGV(SEGV_MAPERR)

### ISSUE THREAD

**Issue by wtwsky** [flutter/flutter#123104]
## Steps to Reproduce

1. Double-click the return key to call SystemNavigator.pop(), which may cause a crash
2. flutter doctor -v no error，Flutter SDk 2.10.5

  <summary>
#12296 1.io

SIGSEGV(SEGV_MAPERR)
#00 pc 0000000000515524 createCompressedTexture2D (../../third_party/skia/src/gpu/gl/GrGLGpu.cpp:1693) [arm64-v8a]
#01 pc 00000000005183ec onDrawIndexedIndirect (../../third_party/skia/src/gpu/gl/GrGLOpsRenderPass.cpp:359 [Inline: multiDrawElementsANGLEOrWebGL]) [arm64-v8a]
#02 pc 00000000004800dc ComputeScratchKey (../../third_party/skia/src/gpu/GrAttachment.cpp:88) [arm64-v8a]
#03 pc 000000000047f988 Cr_z_inflate (../../third_party/zlib/contrib/optimizations/inflate.c:0) [arm64-v8a]
#04 pc 000000000047f9b0 updatewindow (../../third_party/zlib/contrib/optimizations/inflate.c:409) [arm64-v8a]
#05 pc 00000000003fbedc is_plane_config_compatible_with_subsampling (../../third_party/skia/src/core/SkYUVAInfo.cpp:91) [arm64-v8a]
#06 pc 00000000003fbf80 SkYUVAPixmapInfo::DefaultColorTypeForDataType(SkYUVAPixmapInfo::DataType, int) (../../third_party/skia/include/core/SkYUVAPixmaps.h:293-294) [arm64-v8a]
#07 pc 00000000003fbf98 SkYUVAPixmapInfo::SkYUVAPixmapInfo() (../../third_party/skia/include/core/SkYUVAPixmaps.h:90) [arm64-v8a]
#08 pc 0000000000544e8c CanRasterizeRect (../../flutter/flow/raster_cache.cc:56) [arm64-v8a]
#09 pc 00000000002ff7bc __call_once_proxy<std::__1::tuple<(lambda at ../../flutter/fml/icu_util.cc:105:18) &&> > (../../flutter/fml/icu_util.cc:49) [arm64-v8a]
#10 pc 0000000000303088 JavaStringToString (../../third_party/libcxx/include/string:0) [arm64-v8a]
#11 pc 0000000000016bb0 /system/lib64/libutils.so (android::Looper::pollInner(int)+912) [arm64-v8a::72b95803b5fd8108bc84451ecb5146cb]
#12 pc 00000000000167b8 /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+112) [arm64-v8a::72b95803b5fd8108bc84451ecb5146cb]
#13 pc 0000000000017284 /system/lib64/libandroid.so (ALooper_pollOnce+100) [arm64-v8a::8da9da22f08b16eb6a0165c76d1dc067]
#14 pc 0000000000303198 JavaStringToString (../../third_party/libcxx/include/locale:3891) [arm64-v8a]
#15 pc 000000000030148c operator() (../../third_party/libcxx/include/functional:1707) [arm64-v8a]
#16 pc 00000000000dc188 /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+264) [arm64-v8a::f24f65acf653c409ca4332aced817a71]
#17 pc 000000000007a438 /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) [arm64-v8a::f24f65acf653c409ca4332aced817a71]
</summary>

**Comment by wtwsky** [comment]
unresolved stack：

#00 pc 0000000000515524 /data/app/~~1eR1amO7ptiKP_KJQDzvPQ==/com.halamate.app-RZ4r-P6rw2aZIkApIYyvsQ==/lib/arm64/libflutter.so [arm64-v8a::39158a956f52247fdf7a41778fee53a6]
#01 pc 00000000005183ec /data/app/~~1eR1amO7ptiKP_KJQDzvPQ==/com.halamate.app-RZ4r-P6rw2aZIkApIYyvsQ==/lib/arm64/libflutter.so [arm64-v8a::39158a956f52247fdf7a41778fee53a6]
#02 pc 00000000004800dc /data/app/~~1eR1amO7ptiKP_KJQDzvPQ==/com.halamate.app-RZ4r-P6rw2aZIkApIYyvsQ==/lib/arm64/libflutter.so [arm64-v8a::39158a956f52247fdf7a41778fee53a6]
#03 pc 000000000047f988 /data/app/~~1eR1amO7ptiKP_KJQDzvPQ==/com.halamate.app-RZ4r-P6rw2aZIkApIYyvsQ==/lib/arm64/libflutter.so [arm64-v8a::39158a956f52247fdf7a41778fee53a6]
#04 pc 000000000047f9b0 /data/app/~~1eR1amO7ptiKP_KJQDzvPQ==/com.halamate.app-RZ4r-P6rw2aZIkApIYyvsQ==/lib/arm64/libflutter.so [arm64-v8a::39158a956f52247fdf7a41778fee53a6]
#05 pc 00000000003fbedc /data/app/~~1eR1amO7ptiKP_KJQDzvPQ==/com.halamate.app-RZ4r-P6rw2aZIkApIYyvsQ==/lib/arm64/libflutter.so [arm64-v8a::39158a956f52247fdf7a41778fee53a6]
7
#06 pc 00000000003fbf80 /data/app/~~1eR1amO7ptiKP_KJQDzvPQ==/com.halamate.app-RZ4r-P6rw2aZIkApIYyvsQ==/lib/arm64/libflutter.so [arm64-v8a::39158a956f52247fdf7a41778fee53a6]
8
#07 pc 00000000003fbf98 /data/app/~~1eR1amO7ptiKP_KJQDzvPQ==/com.halamate.app-RZ4r-P6rw2aZIkApIYyvsQ==/lib/arm64/libflutter.so [arm64-v8a::39158a956f52247fdf7a41778fee53a6]
9
#08 pc 0000000000544e8c /data/app/~~1eR1amO7ptiKP_KJQDzvPQ==/com.halamate.app-RZ4r-P6rw2aZIkApIYyvsQ==/lib/arm64/libflutter.so [arm64-v8a::39158a956f52247fdf7a41778fee53a6]
#09 pc 00000000002ff7bc /data/app/~~1eR1amO7ptiKP_KJQDzvPQ==/com.halamate.app-RZ4r-P6rw2aZIkApIYyvsQ==/lib/arm64/libflutter.so [arm64-v8a::39158a956f52247fdf7a41778fee53a6]
#10 pc 0000000000303088 /data/app/~~1eR1amO7ptiKP_KJQDzvPQ==/com.halamate.app-RZ4r-P6rw2aZIkApIYyvsQ==/lib/arm64/libflutter.so [arm64-v8a::39158a956f52247fdf7a41778fee53a6]
#11 pc 0000000000016bb0 /system/lib64/libutils.so (_ZN7android6Looper9pollInnerEi+912) [arm64-v8a::72b95803b5fd8108bc84451ecb5146cb]
#12 pc 00000000000167b8 /system/lib64/libutils.so (_ZN7android6Looper8pollOnceEiPiS1_PPv+112) [arm64-v8a::72b95803b5fd8108bc84451ecb5146cb]
#13 pc 0000000000017284 /system/lib64/libandroid.so (ALooper_pollOnce+100) [arm64-v8a::8da9da22f08b16eb6a0165c76d1dc067]
#14 pc 0000000000303198 /data/app/~~1eR1amO7ptiKP_KJQDzvPQ==/com.halamate.app-RZ4r-P6rw2aZIkApIYyvsQ==/lib/arm64/libflutter.so [arm64-v8a::39158a956f52247fdf7a41778fee53a6]
#15 pc 000000000030148c /data/app/~~1eR1amO7ptiKP_KJQDzvPQ==/com.halamate.app-RZ4r-P6rw2aZIkApIYyvsQ==/lib/arm64/libflutter.so [arm64-v8a::39158a956f52247fdf7a41778fee53a6]
#16 pc 00000000000dc188 /apex/com.android.runtime/lib64/bionic/libc.so (_ZL15__pthread_startPv+264) [arm64-v8a::f24f65acf653c409ca4332aced817a71]
#17 pc 000000000007a438 /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) [arm64-v8a::f24f65acf653c409ca4332aced817a71]

**Comment by exaby73** [comment]
Hello @wtwsky. You are using an old version of Flutter. Please upgrade to the latest stable 3.7.7 and confirm if this is still an issue
