### ISSUE TITLE
[Impeller] drawPaint with a runtime effect has different behavior on Skia and Impeller

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#123142]
From https://github.com/flutter/codelabs/pull/1494/files#diff-08321e06007abf96930f31b2a9a5b9f929de54361b73ec85fc7cfdf9a0d8f77dR73

The drawPaint on Skia takes up the whole screen. On impeller it is tiny.

**Comment by jason-simmons** [comment]
Possibly related to https://github.com/flutter/flutter/issues/132802#issuecomment-1684685424
