### ISSUE TITLE
Expanded is throwing an error 

### ISSUE THREAD

**Issue by Ammarmahmoud1995** [flutter/flutter#123116]
Expanded is acting weird throwing Error: Cannot hit test a render box with no size. every single time >>> 
I want to know where I made a mistake or if it s a bug 
Row(children:[ widget 1] , 
Column(children:[Widget 2, 
Expanded(child: Widget 3 ) ,  // Widget 3 is single child scroll view then Column
Widget 4 ) ] ) 
expected result : Widget 4 will always stick to the screen  Because it is out of the scroll 
real result : the error I mentioned before

**Comment by darshankawar** [comment]
@Ammarmahmoud1995 
Can you provide `flutter doctor -v` and a minimal reproducible code sample that shows the error you are reporting ?
