### ISSUE TITLE
Flutter logo is clipped during animation

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#12313]
Long press on the animation to trigger this.
@Hixie 

![simulator screen shot sep 28 2017 6 30 31 pm](https://user-images.githubusercontent.com/11857803/30997227-303a7be8-a47b-11e7-8267-f3801a039cfc.png)

**Comment by Hixie** [comment]
Weird. Can you give more information about platform and so on? This doesn't happen in general last I checked...

**Comment by eseidelGoogle** [comment]
It looks like I'm running inside the iOS Simulator.  I'm happy to repro in person for you if you need.

**Comment by Hixie** [comment]
A dump of the render tree would be useful.

**Comment by goderbauer** [comment]
Closing this since this view doesn't exist in the gallery anymore.
