### ISSUE TITLE
Tablet support

### ISSUE THREAD

**Issue by vanhp** [flutter/flutter#12310]
Please add support for tablet. I'm working on a project that uses a tablet as the main device and I'd like to use flutter for this project.

Vanh

**Comment by Hixie** [comment]
What in particular do you find to be lacking for tablets?

**Comment by vanhp** [comment]
Here is the quote from  flutter document FAQ 

"We do not offer support for tablets or have tablet-aware layouts."

Which prompt me to make the feature request.

**Comment by sethladd** [comment]
Thanks for reaching out!

Flutter should run on tablets. However, we don't test on tablets so there may be some issues with some of our widgets on a tablet.

I've created this PR to clarify this: https://github.com/flutter/website/pull/689

**Comment by vanhp** [comment]
thank for clarify it and thumb up for quick response.

**Comment by yathit** [comment]
We want to show split panel for tablet? How to check it is a tablet?

**Comment by sebaslogen** [comment]
@yathit here is a short tutorial to build tablet aware app: https://flutter.rocks/2018/01/28/implementing-adaptive-master-detail-layouts/

Basically:
```

// Compute the equivalent of the "smallestWidth" qualifier 
// on Android.
final double smallestDimension = min(
  constraints.maxWidth,
  constraints.maxHeight,
);

// Determine if we should use mobile layout or not. The 
// number 600 here is a common breakpoint for a typical 
// 7-inch tablet.
final bool useMobileLayout = smallestDimension < 600;
```

**Comment by srix55** [comment]
I got that flutter isn't being tested on tablets. Like the OP, I too intend to develop for tablets for the most part. My question is, if I find an issue with flutter on tablets, & I log the said issue here, would it still be considered worth fixing? Or would it be dropped saying that flutter is mostly for mobiles?

**Comment by Hixie** [comment]
We definitely want to address tablets, so please do file bugs. We just aren't focusing on them right now (and probably not for the next few months at least). However, we would very much welcome any fixes that you may wish to contribute, and once we _do_ work on this, we will very much care about the bugs.

**Comment by Hixie** [comment]
cc @mit-mit @eseidelGoogle for consideration

**Comment by Hixie** [comment]
To clarify, when Eric says we don't have any customers asking for this, he means customers that our devrel team is working with directly. Obviously we acknowledge everyone here who is asking for this. :-)

**Comment by THEJDEEP1** [comment]
@MichaelSowah  Do we have support for 10 inch tablet ? I am getting this error
Package install error: Failure [INSTALL_FAILED_NO_MATCHING_ABIS]

**Comment by kangwang1988** [comment]
@THEJDEEP1 
I think INSTALL_FAILED_NO_MATCHING_ABIS is because that the ABI for your APK and the ABI for the target device doesn't match. For example, your apk is a armeabi based and the machine is x86 based.
It is not a `tablet support problem`. They may have relations, but not the same problem.

**Comment by THEJDEEP1** [comment]
@kangwang1988   I am using 10 inch amazon fire tablet. I did not ran into any issues when I use 7 inch amazon fire tablet.

**Comment by kangwang1988** [comment]
@THEJDEEP1 
I suggest you to file a new issue so that we can continue discussing on it with more concrete context.

**Comment by zoechi** [comment]
@THEJDEEP1 @kangwang1988 #27026

**Comment by PhilParisot** [comment]
What's the status for tablet support? I'd like to make my app responsive for all screen sizes like lists into grids etc.

**Comment by Hixie** [comment]
We believe Flutter works well on tablets. We do not currently implement all of the tablet-specific adaptations recommended by Material Design, though we are planning further investment in this area.

**Comment by Hixie** [comment]
Since this bug is so vague, it's not really actionable. We are adding tablet and desktop support in general to all widgets, but if there's specific areas where we currently are lacking, don't hesitate to file a bug for that specific feature. Thanks.
