### ISSUE TITLE
in flutter google sign v6.0.0, idToken is null

### ISSUE THREAD

**Issue by meansoup** [flutter/flutter#123168]
hello.
I'm updating `google_sign_in` library from `^5.4.1` to `^6.0.0`

Before update, I can get idToken.
But after update It just gives accessToken and it's idToken is always null.

In this documentation, I found `idToken is null in the GoogleSignInAccount object after signIn`.
So, how can I got idToken?
It's impossible in this library?
- https://pub.dev/documentation/google_sign_in_web/latest/

---

### environment

service: flutter web with google_sign_in ^6.0.0.
browser: chrome

**Comment by danagbemava-nc** [comment]
Hi @meansoup, this is presently not available. There is however a feature tracking a way for you to be able to get the idToken being tracked in https://github.com/flutter/flutter/issues/121781.

Kindly subscribe to that issue for updates. 

Closing from here as duplicate. 

Thank you
