### ISSUE TITLE
Software caused connection abort & Failed host lookup: 'api.xyz.io'

### ISSUE THREAD

**Issue by kamxy** [flutter/flutter#123152]
I'm facing `Failed host lookup: 'api.xyz.io'` and `Software caused connection abort` some users on crashlytics logs. when i send http request on my app opening loading screen.

`Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Software caused connection abort. Error thrown Init User.
       at IOClient.send(io_client.dart:88)
       at BaseClient._sendUnstreamed(base_client.dart:93)
       at get.<fn>(http_custom.dart:47)
       at ._withClient(http_custom.dart:256)
       at UserController.initUser(userController.dart:33)
       at LoadingScreenState.checkRequirements(loading_screen.dart:172)
       at LoadingScreenState.asyncInits(loading_screen.dart:121)`

it is looking like connection problem but i am checking user network status before send request. Other side I'm sending 3 request as a sync 1- check connection 2- initser 3- getsettings ussualy stuck check connection not a problem (maybe connection lost), but wierd side sometimes check connection success, init user thrown `Failed host lookup: 'api.xyz.io'` sometimes all success, getsettings stuck. it's so weird i think

`Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Failed host lookup: 'api.xyz.io'. Error thrown Internet connection failed.
       at IOClient.send(io_client.dart:88)
       at BaseClient._sendUnstreamed(base_client.dart:93)
       at get.<fn>(http_custom.dart:47)
       at ._withClient(http_custom.dart:256)
       at ConnectionUtils.isConnected(connection_utils.dart:11)`

All request similar like that

` try {
      final url = this.routes.userRoutes.getSettings;

      // Send the request
      final response = await httpCustom.get(
        url,
        headers: await HeaderUtils.authorizedGet(),
      );
      var responseJson = jsonDecode(response.body);

      User user = User.fromJson(responseJson['user']);
      Settings settings = Settings.fromJson(responseJson);
      await storage.write(key: StorageKeys().user, value: user.toString());
      await storage.write(
          key: StorageKeys().settings, value: settings.toString());
      sendSuccesLog(funcName: "initUser");
      return user;
    } catch (e, stack) {
      FirebaseCrashlytics.instance.recordError(e, stack, reason: 'Init User');
      checkNetworkConnection(funcName: "initUser");
      return null;
    }`

i tried 

` <uses-permission android:name="android.permission.INTERNET" /> <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />`

and

`android:usesCleartextTraffic="true"`

and im using

https://pub.dev/packages/internet_connection_checker

**Comment by darshankawar** [comment]
@kamxy 

https://pub.dev/packages/internet_connection_checker is a third party package. Does the same behavior occur without using it ?

Also provide complete code sample and also see if this issue is helps in your case or not.https://github.com/flutter/flutter/issues/115921

**Comment by kamxy** [comment]
@darshankawar  
Yes, I see
It's occured before when i don't use this package. I added after for more information like when happening that problem I'm logging user has connection or not. 

and also red it #115921 but not explain my problem different side my app don't 
goes to background I'm checking app lifecycle and logging (foreground,resumed,inactive etc.). This happening app in foreground.

For Example 

<img width="1134" alt="Ekran Resmi 2023-03-22 15 07 00" src="https://user-images.githubusercontent.com/43723696/226900466-6901bcc8-4cb4-4b62-8ebd-813364e24670.png">
<img width="1142" alt="Ekran Resmi 2023-03-22 15 07 11" src="https://user-images.githubusercontent.com/43723696/226900534-64156636-2e38-4ea5-ac66-39fef6a74663.png">

I checked internet connection log: Connection changed as connected 0:00:00.306395 Success
I checked my database with endpoint : Success log: isConnected time:0:00:02.133325 Success
and second request to db scheduleDefaultDigest : Catch network log false on scheduleDefaultDigest time:0:00:02.307260
failed and then check network connection with package connection changed as false 
what happened in this time 0:00:02.133325 - 0:00:02.307260 ? why status changed as disconnected
I dont understund

**Comment by darshankawar** [comment]
Please provide a complete minimal reproducible code sample that we can use along with steps to replicate that shows the reported error.
