### ISSUE TITLE
[Impeller] Tracking: Whole screen flickering on iOS with Impeller enabled

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#123120]
Split off from https://github.com/flutter/flutter/issues/100522.

This issue is intended to capture reproduction steps from users for apps that are experiencing *whole* screen flickering on iOS with Impeller enabled in Flutter versions newer than 3.7.

Please only comment here with one of two things:
1. A code sample and detailed reproduction steps that triggers the issue, or
1. Full un-redacted device logs collected starting from just before the flickering starts.

Since #100522 got a little bit out of hand, on this issue comments will be hidden, deleted, or split off into separate issues in line with Flutter's issue hygiene policies.

**Comment by hongdangodori** [comment]
Is there any update?

**Comment by zanderso** [comment]
Since this has been open for quite awhile with no no information, I'm going to close this as stale.

**Comment by kvenn** [comment]
I've still seen it on iOS with Impeller and it appears there are others who also saw it.
https://github.com/flutter/flutter/issues/100522#issuecomment-1423140073
https://github.com/flutter/flutter/issues/100522#issuecomment-1417010503

Does closing this issue mean there will be no further investigation?

**Comment by zanderso** [comment]
@kvenn Please file a new issue with full details and repro instructions using Flutter version at least as new as the beta channel.

**Comment by kvenn** [comment]
I have been unable (like others in that thread) to reproduce this issue consistently. I'll keep my eye out and create an issue if I have anything of value.
Thanks for the update.
