### ISSUE TITLE
[go_router] Router cannot resolve location when launching app with deep links starting with app://

### ISSUE THREAD

**Issue by astubenbord** [flutter/flutter#123203]
## Description
My app uses deep links to link to navigate to certain routes inside the app. 
I have a home page, from which the user can navigate to a details page which will then display details from the item with the id passed as a url parameter. I'm also bound to the following url format: `app://details/:id`
I have to support this format since legacy versions of this app all operate based on this format and old links shall remain functional. 

Now, when I launch the app with app://details/12345, go router cannot resolve the route and throws the error "No routes for location /12345". 
I'm using a shell route which wraps all routes with a CupertinoTabBar (the code sample below does not use shell route for simplicity, but the result is the same).

I only added a custom scheme (app) in the Info.plist file, I did not add a url name (CFBundleURLName).

How do I have to set up the router to achieve the desired behaviour? I've tried to replace the '//' with '/' in the redirect callback, but unfortunately the route parameters are empty when launching from a deep link. I've also looked at https://github.com/flutter/flutter/issues/115355, could this be related?

## Steps to Reproduce and observations

Launch the app with the following commands and observe the in-app behaviour:
* `xcrun simctl openurl booted app://details/123456` -> Error
* `xcrun simctl openurl booted app://home/details/123456` -> Works as expected
* `xcrun simctl openurl booted app:/details/123456` -> Works and redirects to /home/details/123456
* `xcrun simctl openurl booted app:///details/123456` -> Works and redirects to /home/details/123456

I'm using go_router 6.4.0.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:go_router/go_router.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final _router = GoRouter(
    initialLocation: "/",
    routes: [
      GoRoute(
        path: "/",
        redirect: (context, state) {
          return "/home";
        },
      ),
      GoRoute(
        path: '/home',
        builder: (context, state) => const HomePage(),
        routes: [
          GoRoute(
            path: 'details/:id',
            builder: (context, state) {
              final id = state.params['id'];
              return TestPage(
                extra: id ?? 'No id provided',
              );
            },
          ),
        ],
      ),
      GoRoute(
        path: "/details/:id",
        redirect: (context, state) {
          return "/home${state.location}";
        },
      ),
    ],
  );

  @override
  Widget build(BuildContext context) {
    return CupertinoApp.router(
      routerConfig: _router,
    );
  }
}

class TestPage extends StatelessWidget {
  final String extra;
  const TestPage({
    super.key,
    required this.extra,
  });

  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: const CupertinoNavigationBar(
        middle: Text("Details Page"),
      ),
      child: Center(
        child: Text(extra),
      ),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: const CupertinoNavigationBar(
        middle: Text("Home Page"),
      ),
      child: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            CupertinoButton(
              child: const Text("Go to details page (without redirect)"),
              onPressed: () {
                context.go("/home/details/1234");
              },
            ),
            CupertinoButton(
              child: const Text("Go to test page (with redirect)"),
              onPressed: () {
                context.go("/details/1234");
              },
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 3.7.3, on macOS 13.0 22A380 darwin-arm64, locale
    en-DE)
    • Flutter version 3.7.3 on channel stable at
      /Users/antonstubenbord/Development/src/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (6 weeks ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/antonstubenbord/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.76.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • Anton’s iPhone (mobile)    • 00008101-00093D3E0290001E            • ios
      • iOS 16.2 20C65
    • iPhone 14 Pro Max (mobile) • 2C87B1EB-90C7-4056-B5DC-6C800AE893DC • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-arm64 • macOS 13.0 22A380 darwin-arm64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @astubenbord,

Please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with steps to reproduce so that we can investigate this issue. 

Please also provide the version of `go_router` you're using. 

Thank you

**Comment by astubenbord** [comment]
Hi @danagbemava-nc, 

sorry, I just added the information.

Thanks!

**Comment by danagbemava-nc** [comment]
Hi @astubenbord, I believe what you're running into is the issue described in https://github.com/flutter/flutter/issues/100624. 

Can you take a look and confirm if this is the case?

**Comment by astubenbord** [comment]
Hi @danagbemava-nc,

Yes, thank you, this is exactly the issue. I also tried with a custom url, and with that, it works as expected.

**Comment by danagbemava-nc** [comment]
Hi @astubenbord, thanks for confirming. 

Kindly follow up in the issue linked above for updates. 

Closing from here as duplicate. 

Thank you
