### ISSUE TITLE
Add 1 win arm host into devicelab and run bringup procedured

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#123261]
Add a win arm machine into devicelab. And run bringup procedures to determine we need to change anything to existing procedures for arm based win devices.

**Comment by kentnguyen99** [comment]
The following steps to install M2Crypto software onto new ARM Windows 11.

Install OpenSSL
https://slproweb.com/products/Win32OpenSSL.html
Win64 OpenSSL v1.1.1t

Install Salt-Minion
https://repo.saltproject.io/windows/
[Salt-Minion-3005-1-Py3-AMD64-Setup.exe](https://repo.saltproject.io/windows/Salt-Minion-3005-1-Py3-AMD64-Setup.exe)

https://visualstudio.microsoft.com/downloads/
Install VisualStudioSetup

Install Chocolatey https://chocolatey.org/
Follow instructions on website to run command to install “chocolatey” software.

Open PowerShell then run command below:
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))


Install Swig software by using Chocolatey software “choco” command
choco.exe install swig

Download M2Crypto file
C:\salt\bin\python.exe -m pip download M2Crypto==0.37.1

tar -xzf <M2Crypto-tar-file>

cd M2Crypto folder

C:\salt\bin\python.exe setup.py build —openssl=<Win_OpenSSL Folder>

C:\salt\bin\python.exe setup.py bdist_wheel

C:\salt\bin\python.exe -m pip install <dist/M2Crypto-wheel Folder>

**Comment by kentnguyen99** [comment]
Work has been completed and ticket is closed.
