### ISSUE TITLE
Increase frequency of ios_debug_symbol_doctor on ios hosts in devicelab

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#123257]
From @jmagman: We're seeing high flake counts for iPhones that are getting stuck launching the apps, like https://github.com/flutter/flutter/issues/120808 shows 5-10% flaky. Other issues https://github.com/flutter/flutter/issues/121231, https://github.com/flutter/flutter/issues/122703.  Most of those machines show

```! Error: iPhone 11 is busy: Preparing iPhone 11 for development. Xcode will continue when iPhone 11 is finished. (code -10)```

We seem to hit this every other month or so, it manifests in most iOS builders so the flake bot generates lots an issue per builder, and it takes awhile for me or Zach to track down what's going on.  Any suggestions for getting this unwedged?  Can we run that ios_debug_symbol_doctor recover command more aggressively, like when a Mac_ios build fails or flakes?

**Comment by yusuf-goog** [comment]
@keyonghan do you know if we can add additional triggers for this to run. Or, if its cheap enough, can we run it regularly (at least till we figure out a long term solution).

**Comment by yusuf-goog** [comment]
cc @christopherfujino

**Comment by keyonghan** [comment]
> @keyonghan do you know if we can add additional triggers for this to run. Or, if its cheap enough, can we run it regularly (at least till we figure out a long term solution).

@christopherfujino is working on a potential fix. Let's hold a bit here for frequency bump.

**Comment by jmagman** [comment]
https://github.com/flutter/cocoon/pull/2550 would have helped if the debug_symbol_doctor xcdevice output showed `iPhone 11 is busy: Preparing iPhone 11 for development`, but I only see it in `flutter doctor` (and I can't think why that would be).  Maybe we need to add `flutter devices` output to also be parsed. 

Though that means debug_symbol_doctor can only be run with Flutter installed, which I don't think is the case now.  Though in practice that seems to always be true in the recipes I looked at.

https://github.com/flutter/cocoon/blob/da7d854d852284a0fec6c6b40ae68a6aa0091b72/device_doctor/lib/src/ios_debug_symbol_doctor.dart#L29

**Comment by christopherfujino** [comment]
> [flutter/cocoon#2550](https://github.com/flutter/cocoon/pull/2550) would have helped if the debug_symbol_doctor xcdevice output showed `iPhone 11 is busy: Preparing iPhone 11 for development`, but I only see it in `flutter doctor` (and I can't think why that would be). Maybe we need to add `flutter devices` output to also be parsed.

I like your suggestion of just running the `ios_debug_symbol_doctor.dart recover` sub-command any time an ios devicelab test fails.

**Comment by jmagman** [comment]
I'm pulling the priority over from https://github.com/flutter/flutter/issues/120808 since this is still pretty often flaking and these devices need to be unwedged by opening Xcode.

**Comment by ricardoamador** [comment]
@christopherfujino did you make any kind of PR change for this? Just trying to get an update as the last action in this issue was 3 weeks ago. Thanks!

**Comment by christopherfujino** [comment]
> @christopherfujino did you make any kind of PR change for this? Just trying to get an update as the last action in this issue was 3 weeks ago. Thanks!

Ooh thanks for the ping, didn't know about this bug. Assigning myself, and https://flutter-review.googlesource.com/c/recipes/+/41848 should address this.

**Comment by ricardoamador** [comment]
Thanks @christopherfujino !

**Comment by christopherfujino** [comment]
https://flutter-review.googlesource.com/c/recipes/+/41848 was merged, so calling this done.
