### ISSUE TITLE
Use non-linear viewport metrics interpolation to achieve smoother rotation transition

### ISSUE THREAD

**Issue by hellohuanlin** [flutter/flutter#123248]
## Use case

As discussed in https://github.com/flutter/engine/pull/40412: 

> There are still some minor amount of distortion. There are 2 main reasons:
> 
> 1. Flutter drawing happens on the UI thread, which is not iOS main thread. The delay between issuing engine command till the drawing happens is indeterministic and could vary depending on how busy/idle the app is during the rotation. This amount of distortion is unavoidable, and unlikely solvable.
> 
> 2. We use linear interpolation for simplicity, but iOS window rotation is likely non-linear, with ease-in ease-out effect. Consider using non-linear interpolation if this becomes a problem.

So we may wanna try out non-linear interpolation to further reduce the distortion. 

Also related to: https://github.com/flutter/flutter/issues/16322

The native behavior below can be our benchmark: 

https://user-images.githubusercontent.com/41930132/227052693-420e946a-ad83-4141-a5c6-09c6c2319530.mp4

**Comment by jmagman** [comment]
@hellohuanlin I think you had some screen recordings showing the differences?

**Comment by hellohuanlin** [comment]
i have no tried out non-linear interpolation yet

**Comment by jmagman** [comment]
> @hellohuanlin I think you had some screen recordings showing the differences?

I thought you had some recordings from the demo day showing what it looked like on your PR https://github.com/flutter/engine/pull/40412 vs on native apps but maybe I'm misremembering 🙂

**Comment by hellohuanlin** [comment]
Oh not on the demo day, but I do have native app recording. Let me post it here.

**Comment by hellohuanlin** [comment]
closing as irrelevant anymore
