### ISSUE TITLE
Update contributor wiki to suggest naming upstream git remote "origin" and fork "downstream"

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#123250]
Currently, Flutter's wiki for contributing to the framework suggests a git workflow where the contributors forked repository is named "origin", while the official source of truth is named "upstream": https://github.com/flutter/flutter/wiki/Setting-up-the-Framework-development-environment#set-up-your-environment.

This sometimes leads to surprising behavior from the Flutter CLI tool, however, since certain parts of the tool (and the git CLI tool in general) defaults to the "origin" remote (for example https://github.com/flutter/flutter/issues/121564#issuecomment-1474288126, where `flutter channel main` failed when the dev's fork didn't have a branch named "main").

To bring contributor's experience in line with the rest of Flutter's users, we should update the wiki to recommend naming their fork "downstream" (or "fork") while the source of truth should be "origin":

|URL|Current remote name|Proposed remote name|
|---|---|---|
|https://github.com/flutter/flutter|upstream|origin|
|https://github.com/christopherfujino/flutter|origin|downstream|

**Comment by gnprice** [comment]
> "downstream" (or "fork")

I don't know if there's a widespread convention for what to use here, other than "origin"; but FWIW the remote name I use for my own fork is "me".

One inconvenience of "downstream" is that it's a bit long to type. That comes up particularly when referring to a remote-tracking ref on the Git command line: for example to see the changes made in your own "some-feature" branch, you might type `git diff origin...downstream/some-feature`, or `git diff origin...me/some-feature`.

**Comment by jmagman** [comment]
I prefer the current origin/upstream naming. Since `git` defaults to `origin` I'd rather people be accidentally pushing or doing destructive things to their fork and not the flutter/flutter repo.
