### ISSUE TITLE
Set an alarm clock ?

### ISSUE THREAD

**Issue by Ivaskuu** [flutter/flutter#12322]
Hi, I was wondering if I am able to set an alarm clock with Flutter, and open the app on a specific view (class), to stop the alarm, on Android. Thank you.

**Comment by tomc1998** [comment]
Did you find the answer to this??

**Comment by chenmurong** [comment]
hi, do you haved implement the alarm clock?

**Comment by zoechi** [comment]
Seems related https://stackoverflow.com/questions/44622237/is-there-something-like-alarmmanager-in-flutter
