### ISSUE TITLE
Dart 3: Remove exhaustiveness workaround in focus_traversal.dart

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#123243]
Basically undo the changes in https://github.com/flutter/flutter/pull/123242 once the underlying bug is fixed.

**Comment by goderbauer** [comment]
@jakemac53 Once we have an upstream issue, can you link it here for reference?

**Comment by jakemac53** [comment]
https://github.com/dart-lang/sdk/issues/51823 is the issue on the dart side of things
