### ISSUE TITLE
Default italic font looks bad in ios 16 - flutter 3.7.7

### ISSUE THREAD

**Issue by wfinf** [flutter/flutter#123299]
On ios 16 devices, the angle of the italic font is high, what can be done to make this angle smooth? I created app with flutter 3.7.7 and used default italic font (Roboto)
![ ](https://user-images.githubusercontent.com/24759125/227058904-19e4b99b-91a5-4f0e-b2c9-f663d6d6b33b.png)

**Comment by huycozy** [comment]
I'm checking this on `iPhone 14 Pro, iOS 16.1 (emulator)` but it seems smooth (verified on both the latest Flutter stable and master channels):

<img width="400" src="https://user-images.githubusercontent.com/104349824/227150080-b7dced64-e873-4df3-89dd-d4f46bb894b4.png">

Did you opt-in `Impeller`?

**Comment by wfinf** [comment]
No I did not use impeller.

The devices in the image are device farm devices. But it is the same in simulators. Simulator ios version 16.2. And I tried it with 3.7.7 stable version.
I found a temporary solution. I downloaded the Roboto-italic font and used it directly where I want to italicize. It looks fine this way.

**Comment by huycozy** [comment]
>I found a temporary solution. I downloaded the Roboto-italic font and used it directly where I want to italicize. It looks fine this way.

It seems you solved this, right? If so, feel free to close the issue.

Since you didn't provide the sample code, I don't know your implementation. It looks like the code is missing the font assets, right?
