### ISSUE TITLE
flutter/engine is not tagged for 3.7.8 

### ISSUE THREAD

**Issue by eseidel** [flutter/flutter#123301]
https://github.com/flutter/engine/tree/3.7.8 which is 404 (currently)
vs.
https://github.com/flutter/engine/tree/3.7.7 which resolves as expected
https://github.com/flutter/engine/tree/3.7.6
https://github.com/flutter/engine/tree/3.7.5
etc.

@CaseyHillers says this is due to the new SLSA release workflows. 🤷 

It's not a big deal either way.  Just filing in case it's useful.  I was walking through how to rebase our engine patches with @felangel and found the tag was missing.

**Comment by CaseyHillers** [comment]
Thanks for catching this Eric!

@sealesj can you take a look? It looks like we'll need to update the recipe to also push the engine tag.

**Comment by sealesj** [comment]
Yes, I'll look into this. Thanks for letting me know

**Comment by sealesj** [comment]
Resolved for 3.7.8 and also for the 3.7.9 release which happened yesterday.
https://github.com/flutter/engine/tree/3.7.8
https://github.com/flutter/engine/tree/3.7.9

**Comment by CaseyHillers** [comment]
@sealesj let's keep this open until the automation is fixed.

**Comment by sealesj** [comment]
Fix landed to programmatically determine engine version + tag and push in recipe

**Comment by eseidel** [comment]
Thank you!
