### ISSUE TITLE
Checkered background at the bottom of Screen.

### ISSUE THREAD

**Issue by shalabhapp** [flutter/flutter#12338]
## Steps to Reproduce

1st Case: (in Release mode frequent)
1. Create List View using Cards
2. Scroll down and up
3. Observe the checkered background at the bottom.

2nd: (Sometimes in dev mode, but in release mode it is frequent)
1. Create a Flat button on the cards.
2. Route to a new page. (used Navigator.of(context).push(route))
3. Press back button on AppBar or use android button 
4. Again you will see the same checkered background at the bottom

Mobile Processor: 4x ARM Cortex A7 @ 1.30 Ghz
Mobile GPU - Mali 400 MP

## SCREEN RECORDING MOBILE

![error-checkered](https://user-images.githubusercontent.com/5064613/31115481-2c3bd8b6-a840-11e7-947a-05574018f11a.gif)

## Flutter Doctor

![image](https://user-images.githubusercontent.com/5064613/31048835-a2f32b0c-a643-11e7-887f-acf362efca71.png)

**Comment by shalabhapp** [comment]
Any help on this issue?

**Comment by Hixie** [comment]
cc @chinmaygarde

**Comment by chinmaygarde** [comment]
I haven't been able to reproduce this with any of the devices I have access to. I'll bring this up with the Skia team during our sync.

**Comment by shalabhapp** [comment]
@chinmaygarde 
I again tested on the same device and with the same configuration. Now, instead of black-white checkered background, I am getting white-grey checkered background, when I click on the button of the card. 

Addition: 
1) I am using Tabbed Layout or in Android Terms Tabbed Layout with Fragments type of Views in Flutter.
2) I am also using **ListView.builder** with **container** and **refresh indicator**, currently in Stateless Widget class.

**Comment by zoechi** [comment]
It's a while. Sorry for that. It seems we weren't able to reproduce yet.
A lot has changed since.
Are you still seeing this?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
