### ISSUE TITLE
Support getting the maximum window size (or the size of the display)

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#123307]
Today, on some Android devices (particularly large screen/foldable), restricting your orientation may place you into a letterboxed state. In that state, `View#onSizeChanged` will no longer report the actual size of the whole screen availalbe, but a smaller portion of the screen size.

In a scenario where a Flutter app decides to lock its orientation because of a small screen size (e.g. when the phone is folded up), it may end up locking itself into letter boxing when the phone is opened. It will never get the full avialalbe screen size in the `MediaQuery` because it has locked its orientation.

One work around for this is to unlock orientation during the fold transition, e.g.

```dart
class UnlockingObserver extends WidgetsBindingObserver {
  @override
  void didChangeMetrics() {
    super.didChangeMetrics();
    if (window.displayFeatures.any((DisplayFeature feature) => feature.state == DisplayFeatureState.postureHalfOpened)) {
      SystemChrome.setPreferredOrientations([]);
    }
  }
}
```

However, we should either expose some way to get the maximum display size (which is probably generally useful on other platforms as well, and which isn't necessarily the same as what the MediaQuery/window expose as the `size`).

[Android recommends this formula](https://developer.android.com/guide/topics/large-screens/large-screen-cookbook#java):

```java
/** Determines whether the device has a compact screen. **/
public boolean compactScreen() {
    WindowMetrics screenMetrics = WindowMetricsCalculator
                                  .getOrCreate()
                                  .computeMaximumWindowMetrics(this);
    int shortSide = Math.min(screenMetrics.getBounds().width(),
                             screenMetrics.getBounds().height());
    return shortSide / getResources().getDisplayMetrics().density < 600;
}
```

/cc @reidbaker -we've been talking about an issue related to this recently.
/cc @TytaniumDev for the same reason

**Comment by dnfield** [comment]
The current `MediaQuery` based logic to determine breakpoints is also fragile against multi window on Android, and may end up with the app getting stuck in a letterboxed shape.

**Comment by alexvanyo** [comment]
Just to be precise from the Android side: `WindowMetricsCalculator.computeMaximumWindowMetrics` is part of the recipe if an app feels it must restrict orientation, but in general we'd prefer that apps not restrict orientation and support both landscape and portrait.

Knowing the maximum size that an app could take on in the current system environment if the user adjusts the window seems like a useful thing to be able to calculate in general though.

I do find it interesting that Flutter has (up to now) not provided a built-in way to query for this, which might be evidence that apps shouldn't really need to care about the maximum size they could take most of the time, and just render in the space they are given.

**Comment by dnfield** [comment]
> I do find it interesting that Flutter has (up to now) not provided a built-in way to query for this, which might be evidence that apps shouldn't really need to care about the maximum size they could take most of the time, and just render in the space they are given.

There may be a plugin out there that does this.

It also seems likely to me that the majority of Flutter apps on Android are not tested in an environment where letterbox mode happens, and if they are the developer probably doesn't lock orientation.

**Comment by dnfield** [comment]
Bumping priority on this. Other work arounds for apps on foldable devices are not working very well.

**Comment by dnfield** [comment]
Also, @alexvanyo - the main reason no one has complained too much about this so far is that no one has noticed getting letterboxed (to my knowledge). As apps are getting deployed to foldable devices this is becoming a more serious concern for some of our customers. I'm sure as people start developing more for split screens on larger factor tablets it will be an issue as well.
