### ISSUE TITLE
SelectableRegion Widget crash due to 'Null check operator used on a null value' (Firebase Crashalytics)

### ISSUE THREAD

**Issue by rohanjsh** [flutter/flutter#123378]
**Description:**
I have been using the SelectableRegion Widget in my Flutter application, and I have encountered two issues related to Null check operator used on a null value. These issues have been reported by Firebase Crashlytics, and I have not been able to reproduce them on my local machine. Hence, I would like to report them to the Flutter repository.

**Issue 1:**
In the file 'package:flutter/src/widgets/selectable_region.dart' at line number 609, there is a Null check operator used on a null value error. The error occurs when the '_updateLastEdgeEventsFromGeometries' function is called. It seems that the 'lastParagraph' variable is null, which causes the error.
Stack Trace
```
package:flutter/src/widgets/selectable_region.dart:609
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value. Error thrown Instance of 'ErrorDescription'.
       at _SelectableRegionContainerDelegate._updateLastEdgeEventsFromGeometries(selectable_region.dart:1285)
       at _SelectableRegionContainerDelegate.handleSelectWord(selectable_region.dart:1314)
       at MultiSelectableSelectionContainerDelegate.dispatchSelectionEvent(selectable_region.dart:2014)
       at _SelectionContainerState.dispatchSelectionEvent(selection_container.dart:187)
       at SelectableRegionState._selectWordAt(selectable_region.dart:857)
       at SelectableRegionState._handleTouchLongPressStart(selectable_region.dart:472)
       at LongPressGestureRecognizer._checkLongPressStart.<fn>(long_press.dart:720)
       at GestureRecognizer.invokeCallback(recognizer.dart:253)
       at LongPressGestureRecognizer._checkLongPressStart(long_press.dart:720)
       at LongPressGestureRecognizer.didExceedDeadline(long_press.dart:618)
       at PrimaryPointerGestureRecognizer.didExceedDeadlineWithEvent(recognizer.dart:643)
       at PrimaryPointerGestureRecognizer.addAllowedPointer.<fn>(recognizer.dart:586)
```

**Issue 2:**
In the same file 'package:flutter/src/widgets/selectable_region.dart' at line number 634, there is another Null check operator used on a null value error. The error occurs when the '_handleSelectionStartHandleDragUpdate' function is called. It seems that the 'endHandle' variable is null, which causes the error.
Stack Trace
```
package:flutter/src/widgets/selectable_region.dart:634
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value. Error thrown Instance of 'ErrorDescription'.
       at SelectableRegionState._handleSelectionStartHandleDragUpdate(selectable_region.dart:609)
       at DragGestureRecognizer._checkUpdate.<fn>(monodrag.dart:483)
       at GestureRecognizer.invokeCallback(recognizer.dart:253)
       at DragGestureRecognizer._checkUpdate(monodrag.dart:483)
       at DragGestureRecognizer.handleEvent(monodrag.dart:330)
       at PointerRouter._dispatch(pointer_router.dart:98)
       at PointerRouter._dispatchEventToRoutes.<fn>(pointer_router.dart:143)
       at _LinkedHashMapMixin.forEach(dart:collection)
       at PointerRouter._dispatchEventToRoutes(pointer_router.dart:141)
       at PointerRouter.route(pointer_router.dart:127)
       at GestureBinding.handleEvent(binding.dart:460)
       at GestureBinding.dispatchEvent(binding.dart:440)
       at RendererBinding.dispatchEvent(binding.dart:336)
       at GestureBinding._handlePointerEventImmediately(binding.dart:395)
       at GestureBinding.handlePointerEvent(binding.dart:357)
       at GestureBinding._flushPointerEventQueue(binding.dart:314)
       at GestureBinding._handlePointerDataPacket(binding.dart:295)
```

**Steps to Reproduce:**
As mentioned earlier, I have not been able to reproduce these errors on my local machine. However, the errors are occurring on user devices, which suggests that they are related to some specific conditions or configurations.

**Expected Result:**
The SelectableRegion Widget should work without any Null check operator errors.

**Actual Result:**
The Null check operator used on a null value error occurs in the SelectableRegion Widget.

**Additional Information:**

Widget tree looks something like this
<img width="444" alt="Screenshot 2023-03-24 at 10 51 39" src="https://user-images.githubusercontent.com/35066779/227431500-e7eb37e0-e8e1-4555-83c2-1983820e3147.png">

I have attached the stack traces of the errors in the Firebase Crashlytics console. 
Any help or suggestions regarding these issues would be appreciated. 

Screenshot from crashalytics console

<img width="1027" alt="Screenshot 2023-03-24 at 10 55 08" src="https://user-images.githubusercontent.com/35066779/227432041-56a73928-d00d-4ef7-a6bd-94b11eccb1ef.png">

Thank you.

**Comment by darshankawar** [comment]
@rohanjsh 
Looking at the error log, it seems to be closely related / similar to https://github.com/flutter/flutter/issues/115787, so can you try to replicate using the code sample mentioned in it and see if using it you get same error log as you reported ? Or maybe use that code sample and then come up with the one which replicates exact error log that throws null check ?

**Comment by rohanjsh** [comment]
I'll check this

**Comment by rohanjsh** [comment]
I was able to reproduce the mentioned issue.
Got the following error
```
════════ Exception caught by gesture ═══════════════════════════════════════════
The following _CastError was thrown while handling a gesture:
Null check operator used on a null value

When the exception was thrown, this was the stack
#0      _SelectableRegionContainerDelegate._updateLastEdgeEventsFromGeometries
selectable_region.dart:1285
#1      _SelectableRegionContainerDelegate.handleSelectWord
selectable_region.dart:1314
#2      MultiSelectableSelectionContainerDelegate.dispatchSelectionEvent
selectable_region.dart:2014
#3      _SelectionContainerState.dispatchSelectionEvent
selection_container.dart:187
#4      SelectableRegionState._selectWordAt
selectable_region.dart:857
#5      SelectableRegionState._handleTouchLongPressStart
selectable_region.dart:472
#6      LongPressGestureRecognizer._checkLongPressStart.<anonymous closure>
long_press.dart:720
#7      GestureRecognizer.invokeCallback
recognizer.dart:253
#8      LongPressGestureRecognizer._checkLongPressStart
long_press.dart:720
#9      LongPressGestureRecognizer.didExceedDeadline
long_press.dart:618
#10     PrimaryPointerGestureRecognizer.didExceedDeadlineWithEvent
recognizer.dart:643
#11     PrimaryPointerGestureRecognizer.addAllowedPointer.<anonymous closure>
recognizer.dart:586
#22     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
(elided 10 frames from class _Timer, dart:async, and dart:async-patch)
Handler: "onLongPressStart"
Recognizer: LongPressGestureRecognizer#2cd7c
    debugOwner: SelectableRegionState#9f604
    state: possible
```
Which corresponds to the 'Issue 1', 
I wasn't able to reproduce 'Issue 2' yet.

**Comment by rohanjsh** [comment]
Check this recording, the mid element is HTML, and left and right are padding. Long pressing on padding gives `Null check operator used on a null value` . I am long pressing multiple times, you can see it in the debug console

Uploading Screen Recording 2023-04-02 at 12.05.14.mov…

**Comment by darshankawar** [comment]
Thanks for the update. Can you provide minimal code sample that triggers this error ?

**Comment by rohanjsh** [comment]
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      color: Color(0xFF2196F3),
      title: 'Demo',
      home: SelectionAreaNull(),
      debugShowCheckedModeBanner: false,
    );
  }
}

class SelectionAreaNull extends StatelessWidget {
  const SelectionAreaNull({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('TypeSet example'),
      ),
      body: SelectionArea(
        child: Padding(
          padding: const EdgeInsets.all(80.0),
          child: Text('Hello World' * 200),
        ),
      ),
    );
  }
}
```

Long pressing on padding gives Null check operator used on a null value error.
Also just to mention, I am also able to reproduce this issue #115787. Which has a scrollable widget inside SelectionArea.

Thanks
