### ISSUE TITLE
While running flutter web app I got this issue.

### ISSUE THREAD

**Issue by SaloxiddinTursunaliev** [flutter/flutter#123391]
The source code was working fine. Suddenly I got this issue while re-running. And I got this message "Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!"
## Command
```
flutter run -d chrome --web-port 8080
```

## Steps to Reproduce
1. Run flutter web with "flutter run -d chrome --web-port 8080" command

## Logs
RPCError
```
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1746:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2262:21)
#2      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:2233:14)
#3      FlutterVmService._checkedCallServiceExtension (package:flutter_tools/src/vmservice.dart:807:28)
#4      FlutterVmService.invokeFlutterExtensionRpcRaw (package:flutter_tools/src/vmservice.dart:826:49)
#5      FlutterVmService.flutterDebugDumpApp (package:flutter_tools/src/vmservice.dart:575:50)
#6      ResidentHandlers.debugDumpApp (package:flutter_tools/src/resident_runner.dart:650:53)
<asynchronous suspension>
#7      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1739:7)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.3.9, on Microsoft Windows [Version 10.0.25252.1000], locale en-US)
    • Flutter version 3.3.9 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (4 months ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\Salokhiddin\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = C:\Users\Salokhiddin\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31424.327
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.76.2)
    • VS Code at C:\Users\Salokhiddin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows       • windows-x64    • Microsoft Windows [Version 10.0.25252.1000]
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 111.0.5563.65
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 111.0.1661.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: b8f7f1f9869bb2d116aa6a70dbeac61000b52849
### Plugins
awesome_notifications-0.7.4+1
file_picker-5.2.5
flutter_background-1.2.0
flutter_file_dialog-3.0.0
flutter_plugin_android_lifecycle-2.0.7
geocoding-2.0.5
geolocator-9.0.2
geolocator_android-4.1.7
geolocator_apple-2.2.5
geolocator_web-2.1.6
geolocator_windows-0.1.1
lecle_downloads_path_provider-0.0.2+8
location-4.4.0
location_web-3.1.1
move_to_background-1.0.2
path_provider-2.0.12
path_provider_android-2.0.22
path_provider_foundation-2.1.1
path_provider_linux-2.1.8
path_provider_windows-2.1.3
shared_preferences-2.0.18
shared_preferences_android-2.0.16
shared_preferences_foundation-2.1.4
shared_preferences_linux-2.1.4
shared_preferences_web-2.0.5
shared_preferences_windows-2.1.4
sqflite-2.2.4+1
url_launcher-6.1.9
url_launcher_android-6.0.23
url_launcher_ios-6.1.0
url_launcher_linux-3.0.2
url_launcher_macos-3.0.2
url_launcher_web-2.0.14
url_launcher_windows-3.0.3

**Comment by huycozy** [comment]
Hi. Can you retry on the latest master channel to see if it still occurs?
```
flutter channel master
flutter upgrade
```
If it still persists, can you share the complete output of `flutter run -v`?

Also, did you press `j` button while the app's running? (Maybe duplicated/similar: https://github.com/flutter/flutter/issues/117988)

**Comment by SaloxiddinTursunaliev** [comment]
Hi @huycozy 

I tried to press j button while running on chrome and I got that issue.
It seems that this issue is duplicated.

I am closing this issue, Thanks!
