### ISSUE TITLE
Enable Firestore: wrong directions

### ISSUE THREAD

**Issue by Touciuciu** [flutter/flutter#123332]
it is like this:

Enable Firestore
The web app uses [Firestore](https://firebase.google.com/docs/firestore/) to save chat messages and receive new chat messages.

Enable Firestore:

In the Build menu, click **Cloud Firestore** > Create database.

And it should be like this:

Enable Firestore
The web app uses [Firestore](https://firebase.google.com/docs/firestore/) to save chat messages and receive new chat messages.

Enable Firestore:

In the Build menu, click **Firestore Database** > Create database.

**Comment by Touciuciu** [comment]
The image is old as well, showing the old naming.

**Comment by huycozy** [comment]
This issue doesn't seem to describe a Flutter framework bug or a feature request. 

I'm not sure where you're quoting the documentation from, but it seems appropriate for [flutterfire](https://github.com/firebase/flutterfire/) so please ask the same there for this request. Or maybe you can find appropriate support channels from your documentation source.

Closing, as this isn't an issue with Flutter framework itself.
