### ISSUE TITLE
[CP] Run windows_arm build only on main branch. 

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#123334]
### issue_link

https://github.com/flutter/flutter/issues/123288

### Commit Hash

686552f9444af6b169fbe522fc1987d99be88586

### Target

beta

### pr_link

https://github.com/flutter/engine/pull/40568

### Impacted Users

release engineering team

### Impact Description

Build for windows arm failing in presubmit. This is expected to work only on main branch.

### Workaround

N/A

### Risk

low

### Test Coverage

yes

### Validation Steps

Validate the build is not running on release candidate branches.

**Comment by XilaiZhang** [comment]
closing after merge
