### ISSUE TITLE
Evaluate if partial repaint on Android is too buggy to use reliably.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#123353]
We currently disable it on Android API levels < 29. We have continued to bump up this level and its entirely arbitrary. We are also getting patches to disable it [using properties](https://github.com/flutter/engine/pull/40431/files). If we cannot rely on this being well supported and cannot detect when it isn't, we should consider backing out the feature entirely.

**Comment by chinmaygarde** [comment]
Yet another case.

**Comment by gdzx** [comment]
Here's the check that Firefox does to put my device's GPU on the blocklist for partial redraws. https://hg.mozilla.org/integration/autoland/file/tip/widget/android/GfxInfo.cpp#l648

If I look at affected users' devices in https://github.com/flutter/flutter/issues/105093, most of them seem to have an Adreno 3xx GPU (Samsung Galaxy Note 3, Fairphone 2, Moto G3 / G4, Xiaomi Mi 3 / Mi 4, Wileyfox Swift).

Maybe we could replicate this check first before considering removing this feature entirely?

**Comment by reidbaker** [comment]
Is is possible that https://github.com/flutter/flutter/issues/123545 is another instance of this?

**Comment by chinmaygarde** [comment]
From Triage: We discussed this further and we don't have confidence in the correctness of the implementation of this feature due to lack of testing. We are going to back this out. If re-enabled, this would be behind an allow-list that we know is capable of supporting the feature.

**Comment by chinmaygarde** [comment]
cc @jon

**Comment by jonahwilliams** [comment]
Landing this regressed some benchmarks. several picture/cache memory benchmarks:

https://flutter-flutter-perf.skia.org/e/?begin=1680558012&end=1680624018&keys=X45de8991d6c24dd09df3915cf39d0383&selected=commit%3D34164%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DSM-A025V%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253D90th_percentile_picture_cache_memory%252Ctest%253Dnew_gallery__crane_perf%252C&xbaroffset=34164

And 90% on the backdrop filter blur stress test (the one with dozens of blurs):

https://flutter-flutter-perf.skia.org/e/?begin=1680558012&end=1680624018&keys=X1d9da29da761da88fb3a7b24b2084033&selected=commit%3D34164%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DSM-G973U1%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253D90th_percentile_frame_rasterizer_time_millis%252Ctest%253Dbackdrop_filter_perf__timeline_summary%252C&xbaroffset=34164

Neither is particularly troubling, filling as an FYI

**Comment by jonahwilliams** [comment]
Though it looks like some raster time benchmarks may have improved:

https://flutter-flutter-perf.skia.org/e/?begin=1680553572&end=1680623352&keys=X8baec50836a4a2706a10a0250640b0bd&selected=commit%3D34164%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DSM-G973U1%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253Daverage_frame_rasterizer_time_millis%252Ctest%253Dplatform_views_scroll_perf__timeline_summary%252C&xbaroffset=34163

**Comment by jonahwilliams** [comment]
We have determined that we're not going to attempt to use partial repaint with GLES on Android. Will revist separately with Vulkan Impeller backend
