### ISSUE TITLE
Flutter DatePicker does not scale properly on max zoom on web

### ISSUE THREAD

**Issue by gauria24** [flutter/flutter#123398]
Flutter DatePicker does not scale properly on max zoom on web. Attached the screen shot of flutter gallery app.

Steps to reproduce:

1. Launch https://gallery.flutter.dev/#/ in a browser
2. Go to Categories section. Under Material type choose Pickers.
3. Select DatePicker from options. Click on Show Picker.
4. Zoom screen up to 400% and up to 500%

flutter doctor command output is as below.
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.8, on macOS 13.2.1 22D68 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.76.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
![Screenshot 2023-03-24 at 5 45 11 PM](https://user-images.githubusercontent.com/97582254/227519893-30279fbd-d15f-4351-a8df-5ae62d78609f.png)
![Screenshot 2023-03-24 at 5 45 37 PM](https://user-images.githubusercontent.com/97582254/227519899-fb84f0cc-0db7-4011-be55-ee4205a4e3fc.png)

**Comment by exaby73** [comment]
Hello @gauria24. I think this works as expected. According to the Material Specs on m3.material.io, there is no UI for extremely zoomed in date pickers. I think this is just a product of unnecessary zooming that realistically no user would zoom in that much. Therefore, I am closing this issue. If you disagree with me decision, please comment with your reasoning and I can reopen it. Thank you
