### ISSUE TITLE
How to add a side borders for unseleted tabs in tabBar flutter

### ISSUE THREAD

**Issue by athiraHash** [flutter/flutter#123379]
I want to add a border for unselected tabs in flutter tab bar .

**Comment by huycozy** [comment]
Hi @athiraHash. Your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any.

For quick search results, please see these StackOverflow answers: https://stackoverflow.com/questions/69533643/how-to-add-a-side-borders-of-unseleted-tabs-in-tabbar

Closing for now.
