### ISSUE TITLE
[pigeon] The generated Swift object crashes during parsing.

### ISSUE THREAD

**Issue by jackyshan** [flutter/flutter#123387]
### Use case
My Pigeon template definition is as follows：
```dart
class RequestParam {
  late String key;
  Map<String?, Object?>? data;
}
class ResponseParam {
  late ResponseCode code;
  String? message;
  Map<String?, Object?>? data;
}
```
Here's an example of a generated Swift code block:
```Swift
/// Generated class from Pigeon that represents data sent in messages.
struct RequestParam {
  var key: String
  var data: [String?: Any?]? = nil

  static func fromList(_ list: [Any]) -> RequestParam? {
    let key = list[0] as! String
    let data = list[1] as! [String?: Any?]? 

    return RequestParam(
      key: key,
      data: data
    )
  }
  func toList() -> [Any?] {
    return [
      key,
      data,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ResponseParam {
  var code: ResponseCode
  var message: String? = nil
  var data: [String?: Any?]? = nil

  static func fromList(_ list: [Any]) -> ResponseParam? {
    let code = ResponseCode(rawValue: list[0] as! Int)!
    let message = list[1] as! String? 
    let data = list[2] as! [String?: Any?]? 

    return ResponseParam(
      code: code,
      message: message,
      data: data
    )
  }
  func toList() -> [Any?] {
    return [
      code.rawValue,
      message,
      data,
    ]
  }
}
```
When I use it like this, it crashes
```Swift
func disconnect(param: RequestParam) throws -> ResponseParam {
    pushBridge?.disConnect()
    
    return ResponseParam(code: .success)
}
```
I see. The reason for the crash could be that both data and message have been converted to NSNull
![image](https://user-images.githubusercontent.com/9671825/227456452-338bc2a3-37f3-43b4-ac71-6902322fb184.png)

### Proposal
Changing the code from:
```Swift
    let message = list[1] as! String? 
    let data = list[2] as! [String?: Any?]? 
```
to
```Swift
let message = list[1] as? String
let data = list[2] as? [String?: Any?]
```

**Comment by huycozy** [comment]
Hi @jackyshan 
Which `pigeon` version are you using? Please try the latest version to see if the issue still occurs or not. 

Also, please provide the complete and minimal sample code as well so that we may verify this. Thanks!

**Comment by stuartmorgan** [comment]
@tarrinneal Looks like we have an unintentional regression from the casting change, due to the nil/NSNull conversion in the codec.

I'm confused why this wouldn't be showing up in integration tests though.

**Comment by tarrinneal** [comment]
@jackyshan can you upload your entire generated file for me?

**Comment by jackyshan** [comment]
> @jackyshan Since I haven't been able to replicate this issue, can you try the code in [flutter/packages#3545](https://github.com/flutter/packages/pull/3545) to see if it fixes your problem?

Sure, I can translate the given information into English for you. Here it is:


"No, that didn't solve my problem. Can you run the code on a real device to verify? The device information is iOS 14.4.2 (18D70) Model: iPhone 8 Plus (Model A1864, A1897, A1898, A18999)."

**Comment by tarrinneal** [comment]
Thank you for sharing this, I'll look into it as soon as I can.

**Comment by huycozy** [comment]
@jackyshan Thanks for the sample code, but when I ran `pod install` on the example, I got the error:

```
    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update
    [!] Couldn't determine repo type for URL: `https://gitlab.lizhi.fm/iOSPods/LizhiSpecs.git`: Net::OpenTimeout
```

It seems it's a private source so that it's failed. Could you provide a minimal sample code instead? Thanks!

**Comment by jackyshan** [comment]
> @jackyshan Thanks for the sample code, but when I ran `pod install` on the example, I got the error:
> 
> ```
>     Resolving dependencies of `Podfile`
>       CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update
>     [!] Couldn't determine repo type for URL: `https://gitlab.lizhi.fm/iOSPods/LizhiSpecs.git`: Net::OpenTimeout
> ```
> 
> It seems it's a private source so that it's failed. Could you provide a minimal sample code instead? Thanks!

You can try again, I have deleted those irrelevant configurations.

**Comment by jackyshan** [comment]
> Thanks for updating the sample code. I pull again and run it on my physical device (`iPhone 7, iOS 15.7.2`) but can not reproduce the crash. Based on what I can see, not sure how to `connect` so that can invoke `disconnect` to reproduce this. Can you be more specific on `Steps to reproduce` the issue?
> 
> This is the current result from my end:
> 
> <img alt="" width="400" src="https://user-images.githubusercontent.com/104349824/228193460-48298a5c-5e18-4a04-a4f3-5be2ec6f6b05.png">

Can you try the machine with iOS 14? I can reproduce a crash.

**Comment by stuartmorgan** [comment]
That's odd; I would not expect serialization details to depend on the iOS version.

**Comment by hellohuanlin** [comment]
I think I found the issue - force casting `NSNull` (rather than `nil`) to other types will crash. 

So the "Bool crash" you mentioned before in our chat was not just related to `Bool`, but to other types as well. 

```
let list: [Any?] = [NSNull(), 1, "hi"]
let optionalBool = list[0] as! Bool?

Could not cast value of type 'NSNull' (0x7ff863eec530) to 'NSNumber' (0x7ff863eebc68).

```


We will need to handle special `NSNull` case and see if it fixes this issue. May also also test on your initial Bool crash issue you mentioned in our chat. @tarrinneal

**Comment by stuartmorgan** [comment]
> I think I found the fix - force casting `NSNull` (rather than `nil`) to other types will crash.

Yes, I mentioned that [above](https://github.com/flutter/flutter/issues/123387#issuecomment-1483114660). What doesn't make sense is that a) based on the above it's iOS-version dependent, which shouldn't be the case (the codec should use NSNull consistently) and b) it's not showing up in our Pigeon integration tests.

**Comment by hellohuanlin** [comment]
> I can reproduce the issue now on iPhone 8 Plus (iOS 14.0). Plugin version pigeon: ^9.1.1.
>
> Error message:

> Syncing files to device iPhone 8 Plus...
> Could not cast value of type 'NSNull' (0x7fff86cead08) to 'NSString' (0x7fff86d0fd00).
> Lost connection to device.

@huycozy Can you try again on other iOS version? This error (casting NSNull to NSString) shouldn't be iOS version specific. The latest iOS gives the same error.

**Comment by tarrinneal** [comment]
> 

I tried that here https://github.com/flutter/packages/pull/3545 and @jackyshan says it didn't fix the issue.

**Comment by tarrinneal** [comment]
NSNull can't be cast to any optional type

**Comment by tarrinneal** [comment]
This is essentially the same issue, I think I fixed it from a codec standpoint (aka data from Dart won't be NSNull), but not from a native standpoint (platform can still provide NSNull). 

I'm just guessing here. I haven't had a ton of time to dive into what's actually causing this problem.

**Comment by tarrinneal** [comment]
> I can reproduce the issue now on iPhone 8 Plus (iOS 14.0). Plugin version `pigeon: ^9.1.1`.
> 
> Error message:
> 
> ```
> Syncing files to device iPhone 8 Plus...
> Could not cast value of type 'NSNull' (0x7fff86cead08) to 'NSString' (0x7fff86d0fd00).
> Lost connection to device.
> ```
> 
> Full crash stack trace: [crash_log.txt](https://github.com/flutter/flutter/files/11088139/crashl_log.txt)
> 
> It seems the issue is only reproducible on specific OS:
> 
> * iPhone 7, iOS 15.7.2 (physical device) ✅
> * iPhone 14 Pro, iOS 16.1 (emulator) ✅
> * iPhone 8 Plus, iOS 14.0 (emulator)  ❌
> 
> ✅: No Issue ❌: Issue reproduced
> 
> Updating label for further investigation. Thank you!
> 
> flutter doctor -v (stable and master)

I cannot replicate this issue. Can you give me a guide on how you did it?

**Comment by huycozy** [comment]
>I cannot replicate this issue. Can you give me a guide on how you did it?

@tarrinneal I only clone OP's [repository](https://github.com/jackyshan/swift_null_pigeon) and run it on `iPhone 8 Plus` emulator (I don't have a such physical device) then the crash occurs right after opening it.

>@huycozy Can you try again on other iOS version? This error (casting NSNull to NSString) shouldn't be iOS version specific. The latest iOS gives the same error.

@hellohuanlin I tried testing some other OS/devices but it only happens on iOS 14.

- iPhone 11, iOS 14.0 (emulator): ❌
- iPhone 13, iOS 15.0 (emulator): ✅

✅: No Issue ❌: Issue reproduced

**Comment by tarrinneal** [comment]
That is so strange
