### ISSUE TITLE
Impeller still being used after app restart despite using 'flutter run --no-enable-impeller'

### ISSUE THREAD

**Issue by b3nni97** [flutter/flutter#123374]
## Details
I am encountering an issue where, after restarting the app, the Impeller is still being used despite running the command `flutter run --no-enable-impeller --release`. This causes some bugs to appear in the production app after its second launch, which were previously only observed when using the `--enable-impeller` flag. 

**Target Platform:**iOS
**Target OS version/browser:**16.3.1
**Devices:**iPhone 14 Pro

## Logs

<details>
<summary>Logs</summary>

```
Flutter (Channel master, 3.9.0-16.0.pre.3, on macOS 12.6 21G115 darwin-arm64, locale en-US)
```

</details>

**Comment by jonahwilliams** [comment]
the --enable-impeller/--no-enable-impeller flag is not persistent and is only a debugging choice. If you want to permanently select one of the renderers you need to use the info.plist/manifest options described here:  https://github.com/flutter/flutter/wiki/Impeller#availability
