### ISSUE TITLE
Leak test for the legacy `webview_flutter_android` implementation is failing

### ISSUE THREAD

**Issue by bparrishMines** [flutter/flutter#123327]
Test is failing because it is attempting to override the default `InstanceManager`, but recent changes to the `InstanceManager` prevents duplicate identifiers: https://github.com/flutter/packages/pull/3282

**Comment by stuartmorgan** [comment]
Keeping at P1 since this is important test coverage not to lose.

**Comment by stuartmorgan** [comment]
Since this is legacy-only, closing.
