### ISSUE TITLE
Installation freezes at "Updating flutter tool..."

### ISSUE THREAD

**Issue by AhnanAzhar** [flutter/flutter#12341]
I'm on a Windows 10 laptop, trying to install flutter(and dart) for the first time.
I have managed to clone the flutter git repo into `C:/flutter` and added the environment variable.

When I run `flutter doctor`, when it reaches the step `Updating flutter tool...`, nothing happens. Not even an error message. I checked the Task Manager and it showed me consistent 30% CPU usage and 39MB of RAM usage with no other i/o activities. If I close and re-run, it doesn't even start. I have to clear the `flutter/bin/cache` (210MB) directory to make it run again. Tried running on cmd and PowerShell with and without admin privilege. Same EXACT result. I couldn't finish installing flutter.

**Comment by gitrocyang** [comment]
same question

**Comment by ferpujol** [comment]
Same problem here.

**Comment by mpdevilleres** [comment]
I'm also facing this scenario. I tried both master and alpha branch.

    PS D:\> git clone https://github.com/flutter/flutter.git
    Cloning into 'flutter'...
    remote: Counting objects: 104147, done.
    remote: Compressing objects: 100% (50/50), done.
    rRemote: Total 104147 (delta 9), reused 5 (delta 0), pack-reused 104097eceiving objects: 100%     (104147/104147), 30.21 MiB
    Receiving objects: 100% (104147/104147), 30.77 MiB | 1.14 MiB/s, done.

    Resolving deltas: 100% (77575/77575), done.
    Checking connectivity... done.
    PS D:\> flutter doctor
    Checking Dart SDK version...
    Downloading Dart SDK 1.25.0-dev.11.0...
    Unzipping Dart SDK...
    Updating flutter tool...

I'm using PowerShell 5.0

    PS D:\> $PSVersionTable.PSVersion

    Major  Minor  Build  Revision
    -----  -----  -----  --------
    5      0      10586  117

**Comment by mit-mit** [comment]
Sounds like we are getting stuck here:
https://github.com/flutter/flutter/blob/master/bin/flutter.bat#L93

Some troubleshooting ideas:

1. delete the `cache` directory located inside `<flutter location>\bin\`
1. open `<flutter location>\bin\flutter.bat` and change:
   `CALL "%pub%" upgrade --verbosity=error --no-packages-dir` to:
   `CALL "%pub%" upgrade --verbosity=normal --no-packages-dir`
1. run `flutter doctor` again

This will likely produce a lot of output. Please add that to a gist (https://gist.github.com/).

If it doesn't show enough troubleshooting info, try `--verbosity=all`

**Comment by mpdevilleres** [comment]
@mit-mit 
I tried what you suggest, twice here's the result:

Trial 1: run `flutter doctor` without removing the `cache` folder.

    1930|    ERR : Connection terminated during handshake
    1980|    Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...

Complete Log: https://gist.github.com/mpdevilleres/50f4174f74caf98b8e65f0ef22462996

Trial 2: newly cloned.

    1571|    ERR : Connection closed before full header was received
    1660|    Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...

Complete Log: https://gist.github.com/mpdevilleres/920e7399e2dc3f8460e7a73d4ce9e759

**Comment by mit-mit** [comment]
@nex3 we are seeing a couple of failures here during pub. Any idea what's going on? This is on Windows if that makes a difference.

From https://gist.github.com/mpdevilleres/50f4174f74caf98b8e65f0ef22462996:
```
ERR : Connection terminated during handshake
FINE: Exception type: HandshakeException
FINE: dart:io                                      _HttpClient.openUrl
    | package:http/src/io_client.dart 30           IOClient.send
    | ===== asynchronous gap ===========================
...
```

From: https://gist.github.com/mpdevilleres/920e7399e2dc3f8460e7a73d4ce9e759
```
ERR : Connection closed before full header was received
FINE: Exception type: ClientException
FINE: package:pub/src/source/hosted.dart 338                    BoundHostedSource._throwFriendlyError
    | package:pub/src/source/hosted.dart 140                    BoundHostedSource.doGetVersions
    | package:pub/src/source.dart 165                           BoundSource.getVersions
    | package:pub/src/solver/version_solver.dart 231            SolverCache.getVersions.<fn>
    | dart:async                                                runZoned
    | package:pub/src/http.dart 228                             withDependencyType
    | package:pub/src/solver/version_solver.dart 230            SolverCache.getVersions
    | package:pub/src/solver/unselected_package_queue.dart 121  UnselectedPackageQueue._getNumVersions
    | package:pub/src/solver/unselected_package_queue.dart 50   UnselectedPackageQueue.add
    | package:pub/src/solver/version_selection.dart 68          VersionSelection.select.<fn>
    | dart:async                                                _completeOnAsyncReturn
    | package:pub/src/solver/version_selection.dart 70          VersionSelection.select.<fn>
    | dart:async                                                _completeOnAsyncReturn
    | package:pub/src/solver/unselected_package_queue.dart 54   UnselectedPackageQueue.add
    | dart:async                                                _completeOnAsyncReturn
    | package:pub/src/solver/unselected_package_queue.dart 137  UnselectedPackageQueue._getNumVersions
    | dart:async                                                _completeOnAsyncReturn
    | package:pub/src/solver/version_solver.dart 253            SolverCache.getVersions
    | dart:async                                                _completeOnAsyncReturn
    | package:pub/src/source/hosted.dart 144                    BoundHostedSource.doGetVersions
    | ===== asynchronous gap ===========================
...
```

**Comment by mpdevilleres** [comment]
@mit-mit I rerun `flutter doctor` many times now, and every time it proceeds further, and it finish its job now. took me 4x rerun.

    [√] IntelliJ IDEA Ultimate Edition (version 2017.2)
        • Flutter plugin version 19.1
        • Dart plugin version 172.4343.25

    [√] Connected devices
        • None

**Comment by mit-mit** [comment]
Yes, I suspect these are transient networking issues. We should see if we can make things more reliable at the lower levels, but we should also print more feedback (so that you can see if anything is happening), and have more automated retry logic.

**Comment by Hixie** [comment]
Leaving in current milestone since this will probably affect many new users.

**Comment by jfloresremar** [comment]
I am on Windows and had a smiliar problem when running the last activity (Packages get) from step 5 of Flutter - Firebase tutorial at https://codelabs.developers.google.com/codelabs/flutter-firebase/index.html?index=..%2F..%2Findex#4

`
IO  : HTTP GET https://pub.dartlang.org/packages/stack_trace/versions/1.9.1.tar.gz
    | X-Pub-OS: windows
    | X-Pub-Command: get
    | X-Pub-Session-ID: 8EA3E0BC-14B9-4454-B7BC-81AD521E33D0
    | X-Pub-Environment: flutter_cli:get
    | user-agent: Dart pub 1.25.0-dev.11.0
ERR : Handshake error in client (OS Error: 
    | 	CERTIFICATE_VERIFY_FAILED: self signed certificate in certificate chain(ssl_cert.c:345))
FINE: Exception type: HandshakeException
FINE: dart:io                                      _HttpClient.openUrl
    | package:http/src/io_client.dart 30           IOClient.send
    | ===== asynchronous gap ===========================
    | dart:async                                   new Future.microtask
    | package:http/src/io_client.dart 26           IOClient.send
    | package:pub/src/http.dart 66                 _PubHttpClient.send
    | ===== asynchronous gap ===========================
    | dart:async                                   new Future.microtask
    | package:pub/src/http.dart 45                 _PubHttpClient.send
    | package:http_throttle/http_throttle.dart 33  ThrottleClient.send
    | ===== asynchronous gap ===========================
    | dart:async                                   _asyncThenWrapperHelper
    | package:http_throttle/http_throttle.dart 28  ThrottleClient.send
    | package:pub/src/source/hosted.dart 300       BoundHostedSource._download
    | ===== asynchronous gap ===========================
    | dart:async                                   new Future.microtask
    | package:pub/src/source/hosted.dart 293       BoundHostedSource._download
    | package:pub/src/source/hosted.dart 195       BoundHostedSource.downloadToSystemCache
    | ===== asynchronous gap ===========================
    | dart:async                                   new Future.microtask
    | package:pub/src/source/hosted.dart 190       BoundHostedSource.downloadToSystemCache
    | package:pub/src/entrypoint.dart 504          Entrypoint._get.<fn>
    | ===== asynchronous gap ===========================
    | dart:async                                   new Future.microtask
    | package:pub/src/entrypoint.dart 499          Entrypoint._get.<fn>
    | package:pub/src/http.dart 227                withDependencyType
    | package:pub/src/entrypoint.dart 499          Entrypoint._get
    | package:pub/src/entrypoint.dart 212          Entrypoint.acquireDependencies.<fn>
    | dart:async                                   Future.wait
    | package:pub/src/entrypoint.dart 212          Entrypoint.acquireDependencies
    | ===== asynchronous gap ===========================
    | dart:async                                   _asyncThenWrapperHelper
    | package:pub/src/entrypoint.dart 192          Entrypoint.acquireDependencies
    | package:pub/src/command/get.dart 38          GetCommand.run
    | package:args/command_runner.dart 194         CommandRunner.runCommand
    | ===== asynchronous gap ===========================
    | dart:async                                   new Future.microtask
    | package:args/command_runner.dart 142         CommandRunner.runCommand
    | package:pub/src/command_runner.dart 168      PubCommandRunner.runCommand.<fn>
    | dart:async                                   new Future.sync
    | package:pub/src/utils.dart 102               captureErrors.<fn>
    | package:stack_trace                          Chain.capture
    | package:pub/src/utils.dart 117               captureErrors
    | package:pub/src/command_runner.dart 168      PubCommandRunner.runCommand
---- End log transcript ----
pub get failed (1)
Process finished with exit code 1
`
When i suspend my antivirus protection then "Flutter packages get" executes successfully
`
Running "flutter packages get" in tutorial03...
Process finished with exit code 0
`
Hope it helps

**Comment by Hixie** [comment]
Can the people who are seeing this confirm if the "retrying after 5 seconds" logic actually does retry? I noticed all the logs here end at the first such message. If you do let it wait 5 seconds and it does retry, does it subsequently work? Or does it only work if you break it and manually restart it?

**Comment by Hixie** [comment]
cc @nex3 @kevmoo any ideas?

**Comment by nex3** [comment]
Has https://github.com/dart-lang/pub/commit/932e76efcd813be84045da31d1c4e17b18b227f3 made its way into Flutter yet? It should address these transient networking issues.

**Comment by kevmoo** [comment]
Are they one -dev.15?

On Tue, Feb 6, 2018 at 5:37 PM, Natalie Weizenbaum <notifications@github.com

**Comment by Hixie** [comment]
Flutter's SDK is currently 2.0.0-dev.22.0. The only logs I see in this bug mention SDK 1.25.0-dev.11.0. It is possible this is fixed?

@AhnanAzhar @gitrocyang @ferpujol Can you see if you still run into this?

**Comment by DinoSane** [comment]
Same problem here... Stucked...

**Comment by sywesk** [comment]
I have the same problem. I tried the verbosity flag, and everything goes smoothly, no errors, until it stops displaying stuff, hits cpu max, and starts to eat all the available ram (i let it go above 8gb of ram before killing it). restarting won't help, deleting cache neither. Looks like a crazy while loop with some allocation going on

**Comment by guivho** [comment]
Same problem here, see https://gist.github.com/guivho/a05ac42cdfad45f652c9078ada780ee4

With verbosity=normal it appears to stop after downloading yaml.

So I tried it with verbosity=all and then it gets stuck after:
FINE: Extracting .tar.gz stream to C:\Users\guivh\AppData\Roaming\Pub\Cache\_temp\dir25298446-3435-11e8-92d4-000acd2cc15d.

Then I removed the cache directory and ran the doctor again. It gets stuck at:
FINE: Extracting .tar.gz stream to C:\Users\guivh\AppData\Roaming\Pub\Cache\_temp\dir275bdef4-3436-11e8-92d4-000acd2cc15d.

This is on windows 10, using a fresh git clone

Please advise: I'd really like to start experimenting with flutter

**Comment by aam** [comment]
@guivho do you see files being added/extracted into C:\Users\guivh\AppData\Roaming\Pub\Cache\_temp\dir275bdef4-3436-11e8-92d4-000acd2cc15d ?

@nex3 any more suggestions regarding how to figure out what `pub` is doing at that point? What is it supposed to be doing? Just extracting .tar.gz file?

**Comment by nex3** [comment]
Yeah, it should be piping the data from the HTTP response for the `html` package to `7zip` (on Windows) which will extract it to the directory. If that's stalling out, my best guess is that it's because either the HTTP response never closed or `7zip` encountered a bug of some sort, but I'm not sure why that would be. It's also possible that that extraction succeeds and it's blocked somewhere else, but I'm not sure why that would be. It might be possible to figure out what's going on if you can attach an observatory to the process, but it's notoriously difficult to tell what events are pending.

**Comment by aliriomambo** [comment]
I had a similar issue. What I did is cancel the "updating process" and open the cmd as admin and it worked smoothly.

**Comment by guivho** [comment]
@aam @aliriomambo 
Restarted the doctor in an admin cmd
Process stuck in FINE: Extracting .tar.gz stream to C:\Users\guivh\AppData\Roaming\Pub\Cache\_temp\dirf25fefb7-34e2-11e8-92d5-000acd2cc15d.

And no files appearing in C:\Users\guivh\AppData\Roaming\Pub\Cache\_temp\dirf25fefb7-34e2-11e8-92d5-000acd2cc15d.

**Comment by guivho** [comment]
Tried it again, this time after deleting  /Users/guivh/AppData/Roaming/Pub/Cache and /flutter/bin/cache
Hangs again. always when extracting some .tar.gz stream, this time into  C:\Users\guivh\AppData\Roaming\Pub\Cache\_temp\diraa437a6b-34ec-11e8-92d5-000acd2cc15d

It creates a lot of directories in the  C:\Users\guivh\AppData\Roaming\Pub\Cache\_temp\
All these directories are empty.
I do not understand the process, so this fact may be as expected as strange as it loks

**Comment by guivho** [comment]
Completely removed flutter as well as the roaming pub directory .
Same problem: see gist https://gist.github.com/guivho/5d81b3e738e05d515cf2fd5c76532606

**Comment by Hixie** [comment]
we don't recommend running as admin; if that is required for success we consider that a serious bug.

**Comment by aam** [comment]
@guivho are you able to download https://pub.dartlang.org/packages/charcode/versions/1.1.1.tar.gz file manually?
Can you check contents of C:\Users\guivh\AppData\Roaming\Pub\Cache\_temp\dir3d0a9f35-34f1-11e8-92d5-000acd2cc15d - folder where `pub` extracts downloaded .tar.gz. It should have following:
```
.analysis_options
LICENSE
CHANGELOG.md
AUTHORS
.status
codereview.settings
README.md
pubspec.yaml
.gitignore
CONTRIBUTING.md
lib/ascii.dart
lib/html_entity.dart
lib/charcode.dart
.travis.yml
tool/travis.sh
```

@nex3 wrote 
> Yeah, it should be piping the data from the HTTP response for the html package to 7zip (on Windows) which will extract it to the directory

Do you know if there is a command line one can use to verify that that works?

**Comment by guivho** [comment]
My problem was a Windows File / Folder ownership problem and had nothing to do with flutter, which works fine as I am writing this reply.

(Anyone interested in details, send me a private mail)

Thank you for your efforts and sorry for the noise,

Guido

**Comment by nex3** [comment]
@aam 
> Do you know if there is a command line one can use to verify that that works?

It sounds like this user's issue was already resolved, but in general `pub --verbose` should print the call it makes to `7z`, which the user can try running manually.

**Comment by mit-mit** [comment]
We recently launched new installation bundles (see https://flutter.io/get-started/install/), that are precompiled. Thus closing this issue as fixed!

**Comment by SaabirMohamed** [comment]
I had this same issue ... on windows too. its a rights thing
if you put flutter in the folder usually from the zip file to the program files...as the tut says...then the rights get (as normal) inherited...anyways open cmd as admin or just give your user account the appropriate permission to the program files\flutter folder. (then no need for running shell as admin)

**Comment by zoechi** [comment]
@SaabirMohamed it's probably better to not install in `c:/Program Files` but instead into a users data directory.

**Comment by priteshjain0310** [comment]
Had the same issue. Anti-virus was the culprit. It was blocking pub upgrade.
