### ISSUE TITLE
BUILD FAILED in 27s with Exception: Gradle task assembleDebug failed with exit code 1

### ISSUE THREAD

**Issue by tiger-githubb** [flutter/flutter#123440]
**When i run my project i reeceive this error** 

## Steps to Reproduce

**Expected results:** 
Launching lib\main.dart on moto g 7 in debug mode...
Invalid depfile: C:\Users\HP\Desktop\Git clone\tigernote\.dart_tool\flutter_build\8cf1138cc04f6b9c877f87b2d75e8223\kernel_snapshot.d
Invalid depfile: C:\Users\HP\Desktop\Git clone\tigernote\.dart_tool\flutter_build\8cf1138cc04f6b9c877f87b2d75e8223\kernel_snapshot.d
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:dart%3Ahtml; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:34:7)
#1      asFileUri (package:vm/kernel_front_end.dart:654:37)
#2      writeDepfile (package:vm/kernel_front_end.dart:794:21)
<asynchronous suspension>

#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:629:9)
<asynchronous suspension>
#4      starter (package:frontend_server/starter.dart:99:12)
<asynchronous suspension>
#5      main (file:///C:/b/s/w/ir/x/w/sdk/pkg/frontend_server/bin/frontend_server_starter.dart:13:14)

<asynchronous suspension>
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.
* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1151

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Get more help at https://help.gradle.org

BUILD FAILED in 8s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by mraleph** [comment]
You are trying to launch something that uses `dart:html` on an Android device as a native app. You can't do that - you will need to locate and remove all references to `dart:html` (or wrap them into conditional imports).

The error message is rather bad though /cc @johnniwinther

**Comment by huycozy** [comment]
@tiger-githubb Please try using [conditional imports](https://dart.dev/guides/libraries/create-library-packages#conditionally-importing-and-exporting-library-files) to see if it works for your case.
