### ISSUE TITLE
Flutter should provide pinch-to-zoom behavior matching iOS and Android

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#12340]
I was asked about this at Strange Loop.

**Comment by Hixie** [comment]
Does https://docs.flutter.io/flutter/widgets/GestureDetector/onScaleUpdate.html not do what you want?

**Comment by eseidelGoogle** [comment]
Someone was explaining to me at Strange Loop that standard pinch-gesture behavior differs between iOS and Android.  I don't know more than that.

**Comment by Hixie** [comment]
I think we need more detail before this can be actionable.

**Comment by wmleler** [comment]
I don't know if this is what they were talking about, but I just noticed something strange for onScaleUpdate. onScaleUpdate is being triggered for a GestureDetector even when the user is touching the screen with only a single finger. In this case, details.scale is 1.0. I don't know the behavior of iOS or Android, but it seems like no scale update should be triggered for a single finger.

**Comment by Hixie** [comment]
Closing since the original report isn't actionable.

**Comment by wmleler** [comment]
(LMGTFY) Check out https://www.applevis.com/forum/ios-ios-app-discussion/ios-zoom-vs-android-magnification-gestures

**Comment by eseidelGoogle** [comment]
Eventually we will have to implement a bunch of "platform" gestures like this, but it's OK to close this.  FYI @xster

**Comment by xster** [comment]
Maybe the person was referring to something like this https://github.com/flutter/flutter/issues/13171
