### ISSUE TITLE
WhitelistingTextInputFormatter digitsOnly fail on backspace.

### ISSUE THREAD

**Issue by frederickcook** [flutter/flutter#12347]
## Steps to Reproduce

Run the flutter_gallery example app. Navigate to the Text Form Field Demo. Begin typing a phone number, then press backspace. The phone validators trigger an infinite loop of trying to delete then replacing the last digit.

Removing either the WhitelistingTextInputFormatter.digitsOnly validator or the _phoneNumberFormatter validator causes the issue not to occur. I played around and it seems that even an empty second formatter triggers the issue. I was unable to debug on my own.

## Flutter Doctor

```
% flutter doctor

[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-US, channel master)
    • Flutter at /Users/frederickcook/flutter
    • Framework revision 89566feeed (2 days ago), 2017-09-29 17:56:25 -0700
    • Engine revision bdfedcc26f
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /Users/frederickcook/Library/Android/sdk
    • Platform android-26, build-tools 26.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.0, Build version 9A235
    • ios-deploy 1.9.2
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2.5)
    • Flutter plugin version 17.0
    • Dart plugin version 172.4155.35

[✓] Connected devices
    • iPhone 7 • 2AE532E3-5B4B-4D8D-8CFB-F54C3BF6F8EE • ios • iOS 11.0 (simulator)
```

**Comment by JFixby** [comment]
~ https://github.com/flutter/flutter/issues/10723

**Comment by parkskier426** [comment]
I've found a temporary fix for this. 

- Remove the WhitelistingTextInputFormatter from the phone TextFormField.
- Replace _UsNumberTextInputFormatter with this updated version:
class _UsNumberTextInputFormatter extends TextInputFormatter {

  WhitelistingTextInputFormatter formatter = WhitelistingTextInputFormatter(new RegExp(r'\d+'));

  @override
  TextEditingValue formatEditUpdate(
      TextEditingValue oldValue, TextEditingValue newValue) {

    TextEditingValue formattedValue = formatter.formatEditUpdate(oldValue, newValue);
    if(oldValue.text == newValue.text){
      return newValue;
    }
    final int newTextLength = formattedValue.text.length;

    int selectionIndex = formattedValue.selection.end;
    int usedSubstringIndex = 0;
    final StringBuffer newText = new StringBuffer();
    if (newTextLength >= 1) {
      newText.write('(');
      if (formattedValue.selection.end >= 1) selectionIndex++;
    }
    if (newTextLength >= 4) {
      newText.write(formattedValue.text.substring(0, usedSubstringIndex = 3) + ') ');
      if (formattedValue.selection.end >= 3) selectionIndex += 2;
    }
    if (newTextLength >= 7) {
      newText.write(formattedValue.text.substring(3, usedSubstringIndex = 6) + '-');
      if (formattedValue.selection.end >= 6) selectionIndex++;
    }
    if (newTextLength >= 11) {
      newText.write(formattedValue.text.substring(6, usedSubstringIndex = 10) + '');
      if (formattedValue.selection.end >= 10) selectionIndex++;
    }
    // Dump the rest.
    if (newTextLength >= usedSubstringIndex)
      newText.write(formattedValue.text.substring(usedSubstringIndex));

    if(oldValue != null && oldValue.text != null && oldValue.text.length > newText.toString().length){
      //selectionIndex++;
    }

    if(oldValue.text == newText.toString()){
      return oldValue;
    }
    return new TextEditingValue(
      text: newText.toString(),
      selection: new TextSelection.collapsed(offset: selectionIndex),
    );
  }
}

The root problem as far as I can tell is that iOS seems to call TextInputClient.updateEditingState twice when backspace is pressed. Once with the value before backspace was pressed, once after. This means that the formatter gets called twice as well, and gets caught in a loop updating itself. By moving the WhitelistingTextInputFormatter to the _UsNumberTextInputFormatter, we can check if the old and new values are the same, and throw the errant call out.

**Comment by timtraversy** [comment]
The fix above works for me, and if you want to prevent the number from being longer than 10 digits, add this:
```
final int newTextLength = formattedValue.text.length;

//add this
if (newTextLength > 10) {
    return oldValue;
}

int selectionIndex = formattedValue.selection.end;
```

**Comment by billmoyers** [comment]
I'm also having this problem.  The above workaround from @parkskier426 improved the situation but I still get weird behavior from various validators in iOS.  Anyone know of another workaround?  I've ended up just disabling validators conditionally in iOS.

**Comment by NathanAP** [comment]
We need an update about this. This issue is here for an year and it breaks a lot of situations...

**Comment by xster** [comment]
@jslavitz if you'd like to help pick up the test in @jonahwilliams 's PR

**Comment by jslavitz** [comment]
@xster Looks like he got to it first!

**Comment by larssn** [comment]
I'm still seeing infinite loops on the dev branch. Always backspace related.
