### ISSUE TITLE
Git repo caching failure(?) causing build failure on CI

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#123416]
On Dart rolls, git commands executed during the build and during the initial checkout appear to be failing to hit the git cache on the bots sometimes. Like in https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Engine%20Drone/138201/overview.

```
error: unable to normalize alternate object path: /Volumes/Work/s/w5zm283yk/ir/cache/git/dart.googlesource.com-sdk/objects
```

This is manifesting as a failure when extra output from the error messages is polluting Dart's `version.cc` file, which causes the build to fail, but the error is also printed during the initial checkout:

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8785725138688366817/+/u/Checkout_source_code/bot_update/stdout?format=raw

Filing under infra since it seems like this might be a problem with the git caching setup on the bots.

cc @rmacnak-google to take a look at the git commands in Dart's `make_version.py`.

**Comment by zanderso** [comment]
@rmacnak-google did a local test of the path used as an alternate not existing. It produces the same error message.
```
$ echo "no/such/path" > .git/objects/info/alternates
$ git log -n1
error: unable to normalize alternate object path: /usr/local/google/home/rmacnak/dart1/sdk/.git/objects/no/such/path
commit e8f6276a469ca9ce931ae22dfcd7b474e4ef5831  ...
```

**Comment by zanderso** [comment]
@rmacnak-google has a workaround in https://dart-review.googlesource.com/c/sdk/+/291050, but it is still concerning that something might be going wrong with the caches on CI.

**Comment by keyonghan** [comment]
On those failed builds, the error happened across many repos, not limited to a specific one. We do no see any of such error on a pass build.

Following up with LUCI git cache team.

**Comment by keyonghan** [comment]
Didn't get a quick response from chat. Created https://crbug.com/1428312 to follow.

**Comment by keyonghan** [comment]
Gclient fix to "reset alternates when the git_cache dir is updated" has been merged: https://crrev.com/c/4379380

Monitoring to see if this fixes our problem.

**Comment by keyonghan** [comment]
Checked recent failed builds on https://ci.chromium.org/p/flutter/builders/try/Mac%20mac_host_engine?limit=200, didn't spot an instance of the mentioned error.

@zanderso Please help double check and let me know if the error still happens.

**Comment by zanderso** [comment]
A fix also landed in the Dart SDK to make the failing python scrip resilient to noise printed to stderr, so I wouldn't expect the issue to present as a failed build, rather it would be log noise during the initial `gclient sync`. Either way, I think we can close this as presumed fixed.
