### ISSUE TITLE
ci_yaml roller generate_jspb step does not contain any output

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#123429]
See https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20ci_yaml%20flutter%20roller/8171/overview for an example.

When this builder fails, there's nothing we can do to investigate why the bot fails.

AI is to add the output to the recipe UI

**Comment by keyonghan** [comment]
> Culprit is https://cs.opensource.google/flutter/recipes/+/main:recipes/infra/ci_yaml.py;l=88
> 
> The stdio is being captured, and redirected to the fs. @keyonghan do you know if there's a way to have it both output to MILO and be captured for use in the recipe?

This is doable by catching and populating the error. Moving to the TD to track.

**Comment by ricardoamador** [comment]
https://flutter-review.googlesource.com/c/recipes/+/46540?tab=checks
