### ISSUE TITLE
The project SHOULD include many run-time assertions

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#123449]
The project SHOULD include many run-time assertions in the software it produces and check those assertions during dynamic analysis. 

This criterion does not suggest enabling assertions during production; that is entirely up to the project and its users to decide. This criterion's focus is instead to improve fault detection during dynamic analysis before deployment. Enabling assertions in production use is completely different from enabling assertions during dynamic analysis (such as testing). In some cases enabling assertions in production use is extremely unwise (especially in high-integrity components). There are many arguments against enabling assertions in production, e.g., libraries should not crash callers, their presence may cause rejection by app stores, and/or activating an assertion in production may expose private data such as private keys. Beware that in many Linux distributions NDEBUG is not defined, so C/C++ assert() will by default be enabled for production in those environments. It may be important to use a different assertion mechanism or defining NDEBUG for production in those environments.

**Comment by godofredoc** [comment]
\cc @zanderso

**Comment by zanderso** [comment]
Engine "unopt" builds are built with additional checks (`FML_DCHECK()` in the code).

https://github.com/flutter/flutter/wiki/Compiling-the-engine#general-compilation-tips

We run tests with these builds on CI on the "Unopt" builders.

https://github.com/flutter/engine/blob/main/ci/builders/mac_unopt.json#L24

I think we can close this as done.

**Comment by godofredoc** [comment]
Initial versions of docs: https://github.com/flutter/flutter/wiki/security

**Comment by godofredoc** [comment]
https://github.com/flutter/flutter/wiki/security#Best-practices
