### ISSUE TITLE
There's no way to follow a widget's position

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1234]
Suppose you have a widget that's in a list, inside a layout-based transition, inside an animating transform, etc, and you want to overlay something above it, for example a tooltip. There's no way to do this today. None of the widgets notify anyone when they decide to scroll or reposition children or transform them in paint (or in the compositor!) or whatever.

**Comment by DavidMihola** [comment]
I think this would also be useful to create a parallax effect of items in a ListView, right? (On Android I did this by taking the current position of each child of a `RecyclerView` after each scroll event and re-calculating the offset of, say, the image content withing the `ImageView`).

**Comment by abarth** [comment]
Parallax is likely to have a different solution because it will want to integrate with the sliver protocol.  I don't see an issue on file for parallax scrolling, but that's something we definitely want to support.  Would you be willing to file an issue about support parallax scrolling?

**Comment by DavidMihola** [comment]
Yeah, sure, I'm on it!

**Comment by Hixie** [comment]
I fixed this! CompositedTransformFollower.

**Comment by jifalops** [comment]
@Hixie Can you point to a usage example of the target/follower pattern? I'm wondering if this is what I've been looking for to animate a list item to full screen to show a details view. The initial item position on screen has been difficult for me to find so far.

**Comment by Hixie** [comment]
If you search for CompositedTransformFollower in the framework, you can find a couple of places where we use it.
