### ISSUE TITLE
Problem installing on OSX: Dart_NewStringFromUTF8 expects argument 'str' to be valid UTF-8

### ISSUE THREAD

**Issue by mbinkhorst** [flutter/flutter#12349]
I followed the install instructions to install Flutter on OSX. Running 'flutter doctor' gave me the following error:
 
`Dart_NewStringFromUTF8 expects argument 'str' to be valid UTF-8.`

Then running 'flutter doctor -v' gave me a clue to where the issue could be. At first I thought it could be a weird character in a name somewhere but that was not the case.

I had an alias to the applications folder inside another app's folder (no idea why). 
/Applications/data rescue/Wondershare Data Recovery 3.1.0/**_Applications_**/

This probably led to some recursion and a too long filename/path:

`[        ] Exception while looking for Android Studio: FileSystemException: Directory listing failed, path = '/Applications/data rescue/Wondershare Data Recovery 3.1.0/Applications/data rescue/Wondershare Data Recovery 3.1.0/Applications/data rescue/Wondershare Data Recovery 3.1.0/Applications/data rescue/Wondershare Data Recovery 3.1.0/Applications/data rescue/Wondershare Data Recovery 3.1.0/Applications/data rescue/Wondershare Data Recovery 3.1.0/Applications/data rescue/Wondershare Data Recovery 3.1.0/Applications/data rescue/Wondershare Data Recovery 3.1.0/Applications/data rescue/Wondershare Data Recovery 3.1.0/Applications/data rescue/Wondershare Data Recovery 3.1.0/Applications/data rescue/Wondershare Data Recovery 3.1.0/Applications/Adobe After Effects CC 2017/Plug-ins/MAXON CINEWARE AE/(CINEWARE Support)/lite/resource/modules/python/Python.osx.framework/lib/python2.6/plat-mac/lib-scriptpackages/Explorer/Microsoft_Internet_E' (OS Error: File name too long, errno = 63)`

Full log:
https://pastebin.com/ii9pEyUA

Output after removing the alias:
https://pastebin.com/1DzqdUvM

Removing the alias to the applications folder made it all work just fine.
@cbracken

**Comment by Pacane** [comment]
I had this issue this week, and it was caused by some garbage character in a file in my home directory. 

Probably not the same issue, but it was hard to diagnose as well

**Comment by cbracken** [comment]
The recursion issue @mbinkhorst identified is in a bug in `_checkForStudio` in `lib/src/android/android_studio.dart`. Looks like we fail to canonicalise/prune the search tree.

**Comment by Hixie** [comment]
This is caused by https://github.com/dart-lang/sdk/issues/29451

**Comment by Hixie** [comment]
Or maybe not, upon reading more closely. Sorry.

**Comment by cbracken** [comment]
I suspect @Pacane's issue is dart-lang/sdk#29451, but @mbinkhorst's uncovered a Mac-specific bug in the directory walk we do when searching for Android Studio in `flutter_tool`.

**Comment by zoechi** [comment]
dart-lang/sdk#29451 is fixed
I assume this is fixed then as well.
