### ISSUE TITLE
Opening a drawer stops list scrolling

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#12344]
## Steps to Reproduce

1. In Flutter Gallery, fling the main page demo list.
2. Tap the hamburger icon to open the drawer.

**Expected behaviour:** list continues scrolling and drawer opens.
**Actual behaviour:** list stops scrolling and drawer does not open until second tap.

Only verified on iOS simulator, where it's hard to move my virtual fingers quickly, but it appears as though swiping the drawer open also pauses scrolling.

Kudos goes to /u/omniuni for [reporting](https://www.reddit.com/r/androiddev/comments/73ju8l/flutter_how_were_building_a_ui_framework_for/dnraoo3/) this issue on Reddit. Full comment:

>If you've scrolling, you can't open the drawer, for example. Opening the drawer stops 
> the list from scrolling. The same blocking behavior exists when swiping between tabs.

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.13 17A365, locale en-AU, channel master)
    • Flutter at /Users/cbracken/src/flutter/flutter
    • Framework revision 89566feeed (2 days ago), 2017-09-29 17:56:25 -0700
    • Engine revision bdfedcc26f
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/cbracken/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0)
    • Xcode at /Applications/Xcode9.0.app/Contents/Developer
    • Xcode 9.0, Build version 9A235
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2.5)
    • Flutter plugin version 17.0
    • Dart plugin version 172.4155.35
```

**Comment by cbracken** [comment]
@HansMuller @Hixie @xster (can't remember who's touched scrolling most recently)

**Comment by Hixie** [comment]
This probably has more to do with gesture handling that scrolling.

**Comment by Hixie** [comment]
This is working as intended. The hamburger menu is in the list, so tapping it when the list is scrolling stops the scroll, just like tapping anywhere else on a scrolling list should stop the scroll.
