### ISSUE TITLE
[engine] Host Tests for host_debug_unopt is flaky

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#123483]
`LeakSanitizer` crashes unpredictably on various builds. Sample builds:

* https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Unopt/10825/overview
* https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Unopt/27250/overview

I'm not sure if we run automatic flake detection on the engine repo, so pessimistically filing this as P1.

**Comment by chinmaygarde** [comment]
The ones we looked at seem like singleton registrations in the font factory. I would have expected these to be in the default suppressions list already.

**Comment by zanderso** [comment]
`EmbedderTest.CanReloadSystemFonts` continues to flake. @chunhtai sorry for the archeology, but it looks like you added this test in https://github.com/flutter/engine/commit/aadd5a346bb5fcf970a90e3c98d55818b4734e48. Mind taking a look at this flake?
