### ISSUE TITLE
Google Play Store "library libflutter.so not found" error

### ISSUE THREAD

**Issue by under3415** [flutter/flutter#123458]
Recently started getting this stability issue reported by Google Play store. For some reason they are testing on a Wear OS device which I am not targeting. Play support is saying this is not their issue. Can you please help?

## Steps to Reproduce

1. Submit your app to Google Play store
2. Play Store raises stability issue (details below)
3. This is detected on Wear (Virtual) device, locale es_US, Android 11, x86
```
Exception java.lang.RuntimeException: Unable to start activity ComponentInfo{MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3449)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3601)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:85)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2066)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:223)
  at android.app.ActivityThread.main (ActivityThread.java:7651)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:592)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:947)
Caused by java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
  at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete (FlutterLoader.java)
  at io.flutter.embedding.engine.FlutterEngine.<init> (FlutterEngine.java)
  at io.flutter.embedding.engine.FlutterEngine.<init> (FlutterEngine.java)
  at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine (FlutterActivityAndFragmentDelegate.java)
  at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach (FlutterActivityAndFragmentDelegate.java)
  at io.flutter.embedding.android.FlutterActivity.onCreate (FlutterActivity.java)
  at android.app.Activity.performCreate (Activity.java:7998)
  at android.app.Activity.performCreate (Activity.java:7978)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1309)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3422)
Caused by java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
  at java.util.concurrent.FutureTask.report (FutureTask.java:123)
  at java.util.concurrent.FutureTask.get (FutureTask.java:193)
  at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete (FlutterLoader.java)
Caused by java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
  at java.lang.Runtime.loadLibrary0 (Runtime.java:1087)
  at java.lang.Runtime.loadLibrary0 (Runtime.java:1008)
  at java.lang.System.loadLibrary (System.java:1664)
  at io.flutter.embedding.engine.FlutterJNI.loadLibrary (FlutterJNI.java)
  at io.flutter.embedding.engine.loader.FlutterLoader$1.call (FlutterLoader.java)
  at io.flutter.embedding.engine.loader.FlutterLoader$1.call (FlutterLoader.java)
  at java.util.concurrent.FutureTask.run (FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:923)
```

**Expected results:** 
No problem
**Actual results:** 
Problem detected on a device that my app is not even targeting
I have logged this with play store support, but they are saying "As per investigation, it seems like this is an issue with regards to your app implementation. Unfortunately, our team doesn't support issues related to app implementation."
</details>

<details>

```
[√] Flutter (Channel stable, 3.7.8, on Microsoft Windows [Version 10.0.19045.2728], locale en-US)
    • Flutter version 3.7.8 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 90c64ed42b (4 days ago), 2023-03-21 11:27:08 -0500
    • Engine revision 9aa7816315
    • Dart version 2.19.5
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\dejan\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33502.453
    • Windows 10 SDK version 10.0.22621.0
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] VS Code (version 1.76.2)
    • VS Code at C:\Users\dejan\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.60.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2728]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 111.0.5563.111
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 111.0.1661.51

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by pjq** [comment]
See the same issue, no idea why they are testing on watch.

<img width="1253" alt="image" src="https://user-images.githubusercontent.com/87846/227726874-8b222e47-ec0d-4389-ab41-d3f4518999a8.png">

**Comment by leospotlight** [comment]
Same error here with Google Wear: 
![image](https://user-images.githubusercontent.com/96927523/227729375-ca481d51-596a-418e-a98d-41b1c7dc1bee.png)

**Comment by Slntn** [comment]
the same issue is here. I sent a message to google support... waiting for they response....

My build.gradle:
 
```
   buildTypes {
       release {
           signingConfig signingConfigs.release
           ndk {
            abiFilters 'arm64-v8a', 'armeabi-v7a', 'x86_64', 'x86'
          }
       }
   }
```

`Exception java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example/com.example.MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
`

**Comment by under3415** [comment]
Would a workaround be to remove x86 from `abiFilters`? What else would be affected? Is there a way to explicitly ban Wear OS?

**Comment by Vahitbeh** [comment]
I have too same issue

**Comment by fosella11** [comment]
Same issue, any solution? Has anyone tried to put the app into production?

**Comment by under3415** [comment]
Would be goo for someone from Flutter/Google to advise if this is just a Google Play store testing issue, of if there is something er need to change?

To me it looks like Play Store issue. When I look at "native platforms" in Play Store it has these" `arm64-v8a, armeabi-v7a, x86_64`, so it should not be testing on x86 Wear OS device. 

I am not sure if all wear device are x86? There does not seem to be a way to specify if you are targeting wear. Seems that store only knows about these: Phones, Tablets, Android TV, Chrome OS, there is no option for Wear OS in there!

**Comment by aoizoijoizj** [comment]
I have the same issue.
Why flutter didn't fix this issue yet? It's from 2018!

**Comment by Slntn** [comment]
Got a solution! Try to use the following settings in the app/build.gradle: 

```
   buildTypes {
       release {
           signingConfig signingConfigs.release
            ndk { 
                abiFilters 'arm64-v8a', 'armeabi-v7a'
            }
       }
   }
```

Related ticket: https://github.com/flutter/flutter/issues/85826

**Comment by thuchau** [comment]
I have the same issue too, any solution?

**Comment by darshankawar** [comment]
This most probably looks similar to https://github.com/flutter/flutter/issues/83596, so follow-up in it for further updates. You may share your findings in that issue for better tracking.

Closing this as a duplicate. If anyone disagrees, write in comments and I'll reopen it.

**Comment by under3415** [comment]
Hi,
These two issues don't seem related. The old issue is from 2021. This one just started happening. 
The new issue is with a Play Store
Why do you think the two are related?

**Comment by thuchau** [comment]
Hi,
I think we have new issue because the issue #83596 relate issue about Flutter does not currently support building for x86. This issue about "Recently started getting this stability issue reported by Google Play store. For some reason they are testing _**on a Wear OS device which I am not targeting.**_"

**Comment by darshankawar** [comment]
Please see below from same linked issue:

https://github.com/flutter/flutter/issues/83596#issuecomment-987799827
https://github.com/flutter/flutter/issues/83596#issuecomment-998893166

**Comment by dubydu** [comment]
> thuchau

try this solution:
```
    defaultConfig {
        //...
        ndk {
            abiFilters 'arm64-v8a', 'armeabi-v7a', 'x86', 'x86_64'
        }
    }
```

**Comment by aintend-com** [comment]
> 

This solution worked in my case. I remove `x86_64` from the list

**Comment by under3415** [comment]
> > 
> 
> This solution worked in my case. I remove `x86_64` from the list

that will remove any devices on intel 64 bit CPUs. While x86 32-bit architecture is on its way out removing x64 is going to have more of an impact on device covereage

**Comment by darshankawar** [comment]
Based on the comments, reports, I'll reopen it and label for team's attention.

**Comment by darshankawar** [comment]
Another similar / related issue: https://github.com/flutter/flutter/issues/122095 and most probably https://github.com/flutter/flutter/issues/83596

**Comment by reidbaker** [comment]
Mariam to try to figure out what data from flutter builds Play is using to determine watch support. Then we will figure out where we set that data in flutter projects. 

There should be a way to support x86 android phones and not support watches. Also there is probably an opportunity to update out documentation about watch support.

**Comment by under3415** [comment]
> Mariam to try to figure out what data from flutter builds Play is using to determine watch support. Then we will figure out where we set that data in flutter projects.
> 
> There should be a way to support x86 android phones and not support watches. Also there is probably an opportunity to update out documentation about watch support.

I thought that flutter does not support `x86`?

Regardless of whether I specify this in gradle or not, the Play Store only has 3 platforms under package ABIs, so x86 is NOT included. This makes me think this is a play store issue as `x86` testing devices should not be included, whether Wear OS or otherwise. I am trying to escalate this with Play Store support even though they first said this is my problem. Some help from Flutter gurus would be helpful
![image](https://user-images.githubusercontent.com/3857822/228982147-04d8d734-3158-418b-8f04-19048f2e7c94.png)

**Comment by under3415** [comment]
Hi
I've updated to flutter 3.7.9.
Not sure if that made a difference or if Play Store fixed something but the issue has gone away!

**Comment by aoizoijoizj** [comment]
@under3415 What is your ndk.abiFilters please?

**Comment by aoizoijoizj** [comment]
> Someone says you may have to add the following in AndroidManifest.xml file
> 
> ```
> <application
>     android:extractNativeLibs="true"
>     ...
> 
> </application>
> ```
> 
> I will try that

This doesn't work i tried it.

**Comment by under3415** [comment]
> @under3415 What is your ndk.abiFilters please?

ndk {
            abiFilters 'arm64-v8a', 'armeabi-v7a', 'x86_64'
          }

**Comment by aoizoijoizj** [comment]
Yes the issue gone, either from Flutter's last update or from Google Play Store.

**Comment by reidbaker** [comment]
Closing per the last comment

> Yes the issue gone, either from Flutter's last update or from Google Play Store.

**Comment by abeeriqbal** [comment]
> Yes the issue gone, either from Flutter's last update or from Google Play Store.



> > @under3415 What is your ndk.abiFilters please?
> 
> ndk { abiFilters 'arm64-v8a', 'armeabi-v7a', 'x86_64' }
@aoizoijoizj Do you have this   android:extractNativeLibs="true"?
Also can you please share your gradle and manifest configurations here. So we can verify, also please share Flutter version which you are using. This information would be helpful to fix issues on our end also.

**Comment by abeeriqbal** [comment]
@aoizoijoizj Do you have this android:extractNativeLibs="true"?
Also can you please share your gradle and manifest configurations here. So we can verify, also please share Flutter version which you are using. This information would be helpful to fix issues on our end also.



> Yes the issue gone, either from Flutter's last update or from Google Play Store.

**Comment by aoizoijoizj** [comment]
@abeeriqbal
- i don't use android:extractNativeLibs="true".
- flutter version is the last one, (upgraded using flutter upgrade command). 
- and ndk.abiFilters is 'arm64-v8a', 'armeabi-v7a', 'x86_64' .
when i removed the ndk.abiFilters the problem again appeared in some devices. So don't remove it.
