### ISSUE TITLE
[add2app] how to add multiple app.xcframework to ios native application

### ISSUE THREAD

**Issue by Gaoxichao** [flutter/flutter#123576]
I have two flutter projects, now I need to build them into frameworks（APP.Xcframework and Flutter.Xcframework） and add to  iOS native application.

It is normal when adding only one, But when I add two, it results in duplicate error（by APP.Xcframework）. PS: We cannot add either one flutter project to the other flutter project.

what should I do?

**Comment by Gaoxichao** [comment]
@jmagman @xster

**Comment by huycozy** [comment]
Hi @Gaoxichao. Can you please share the steps you have tried to do along with the error log output? Also, do frameworks have the same name? 
And please provide the output of `flutter doctor -v` as well. Thanks!

**Comment by jmagman** [comment]
See also https://github.com/flutter/flutter/issues/39707 and https://github.com/flutter/flutter/issues/39707

**Comment by Gaoxichao** [comment]
> Hi @Gaoxichao. Can you please share the steps you have tried to do along with the error log output? Also, do frameworks have the same name? And please provide the output of `flutter doctor -v` as well. Thanks!

@huycozy 
The simplest case steps（add2App）：
1. Create a flutter module（Referred to as A Flutter module） and execute command `flutter build ios-framework` then generate `APP.Xcframework` and `Flutter.Xcframework`
2. Create a native ios project and import `APP.Xcframework` and `Flutter.Xcframework`
3. Run the native ios project , it works fine now
4. Create a flutter module（Referred to as B Flutter module）in this step，build frameworks as same as step 1.
5. Import the frameworks to native ios from B Flutter module
6. Run the native ios project ,it error!!  because there have tow same name framework(APP.Xcframework)

how to resolve the same name framwork and run success？how to import two flutter module framework?

by the way, we can not use the plugin ways ,because these two flutter modules are different company projects, It can not provide source code to each other.

and my flutter version is 3.7.1, but I think this question has nothing to do with flutter version.

**Comment by huycozy** [comment]
Thanks for your response @Gaoxichao. As the mentioned issue above, I will close this issue in favor of #39707 which has been discussed before. Please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue.
