### ISSUE TITLE
getting multiple error

### ISSUE THREAD

**Issue by Vishal143-dot** [flutter/flutter#123520]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by Vishal143-dot** [comment]
import 'package:english_words/english_words.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart'; 
error in this part

**Comment by darshankawar** [comment]
@Vishal143-dot 
You are probably referring to https://codelabs.developers.google.com/codelabs/flutter-codelab-first#2 but we are not sure what errors you are getting as you have not mentioned any. Please provide proper details as what error are you getting while following the codelab.
