### ISSUE TITLE
Dart to Engine roller stopped

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#123516]
The engine -> framework roll failed on the changes to the `--serve-observatory` flag in https://dart.googlesource.com/sdk.git/+/fb1516c4ea52111f05a96d9eaedffc1e6feed000:

https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20tool_integration_tests_4_4/20764/overview

cc @bkonyi @aam

**Comment by bdero** [comment]
The affecting change has been reverted
