### ISSUE TITLE
can we use Pigeon in flutter module? 

### ISSUE THREAD

**Issue by ravi451** [flutter/flutter#123530]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by danagbemava-nc** [comment]
Yes, you can use pigeon in flutter modules. See https://github.com/flutter/samples/tree/master/add_to_app/books/flutter_module_books for an example.

Closing as this is neither a bug report nor a feature request.
