### ISSUE TITLE
RichText drawing problem on Android devices

### ISSUE THREAD

**Issue by kutian** [flutter/flutter#123529]
Hello, our users found a RichText drawing problem on Android devices (our test devices are Huawei mate 40 and Redmi 9A) during online project usage. The user searched for text and our app will highlight the hit keywords.
The user has text “flh”, and entered keyword “f”. Ideally, the user can find the text “flh” by entering “f”, and text “flh” should be highlighted.
But the actual result is: the text “flh” is displayed as “flfl” on flutter pages, and the first pair of “fl” was highlighted, letter “h” was not drawn by flutter.
Our sample code is as follows:
```
List<TextSpan> spans = [];
TextSpan keyword = new TextSpan(
    text: "f",
    style: TextStyle(
    color: Colors.red,
    fontSize: 14,
    fontWeight: FontWeight.w400,),
);
TextSpan normal = new TextSpan(
    text: "lh",
    style: TextStyle(
    color: Colors.yellow,
    fontSize: 14,
    fontWeight: FontWeight.w400,),
);
spans.add(keyword);
spans.add(normal);
TextSpan richSpan = new TextSpan(children: spans);
return RichText(
      textScaleFactor: MediaQuery.textScaleFactorOf(context),
      text: richSpan,
    );
```
Operation Environment：
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.0.1 22A400 darwin-arm, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.74.2)
[✓] VS Code (version 1.69.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```
![图片1](https://user-images.githubusercontent.com/9430366/227893049-70bc31a4-0444-4fcf-94f2-e400b6311905.png)

**Comment by huycozy** [comment]
Hi @kutian, this is a known issue being tracked at https://github.com/flutter/flutter/issues/123515. Closing this issue as a duplicate, so please follow up on it for further updates and you also can leave there your comment will help to investigate the issue. Thank you!
