### ISSUE TITLE
local_auth plugin does not work with Xiaomi Android phones

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#12355]
Xiaomi Android phones do not use the standard authentication libraries shipped with Android. However, both Paypal and Bank of America apps work with the fingerprint reader. We need to investigate how to make it work.

**Comment by MichaelPriebe** [comment]
It works for me on Xiaomi Mi Mix 3 but it defaults to the error icon, but using the fingerprint it works.

**Comment by mehmetf** [comment]
I had tested the latest biometric apis and this no longer seems to be an issue.
