### ISSUE TITLE
Flutter is not providing sufficient iOS Debug symbols for Sentry

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#12352]
https://github.com/getsentry/sentry-cocoa/issues/205

**Comment by eseidelGoogle** [comment]
I think https://github.com/getsentry/sentry-cocoa/issues/205#issuecomment-326953227 shows an example of what is desired.  @chinmaygarde or @cbracken likely knows how to fix.

**Comment by Hixie** [comment]
Dupe of https://github.com/flutter/flutter/issues/12012
