### ISSUE TITLE
The webview_flutter plugin renders problems for android devices with api 28

### ISSUE THREAD

**Issue by zhaobin0122** [flutter/flutter#123579]
## Steps to Reproduce

1. Create a sample project with the introduction of the webview_flutter plugin 2.0.0
2. Display a webView widget and place the webView at the bottom
2. Running the app on android devices with api 28, the webView widget is not fully rendered
3. Place the webView widget at the top. The webView renders normally

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  late WebViewController _controller;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Stack(
        children: [
          Positioned(
              bottom: 0,
              child: Container(
                width: 300,
                height: 300,
                child: WebView(
                  initialUrl:
                      "https://www.google.com/",
                  onWebViewCreated: (WebViewController webViewController) {},
                  javascriptMode: JavascriptMode.unrestricted,
                ),
              )),
        ],
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by huycozy** [comment]
Hi @zhaobin0122 
I checked this on emulator API 28 and on the latest Flutter master channel, the web can be loaded fully.
The result is the same on `webview_flutter: 2.0.0` and the latest version `webview_flutter: ^4.0.7`. 

![Screenshot 2023-03-28 at 14 44 24](https://user-images.githubusercontent.com/104349824/228164874-6664790a-eada-451b-adb7-668fbc0cfbaf.png)

<details>
<summary>Sample code (compatible with new plugin version)</summary>

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late WebViewController controller;

  @override
  void initState() {
    super.initState();

    // #docregion webview_controller
    controller = WebViewController()
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setBackgroundColor(const Color(0x00000000))
      ..setNavigationDelegate(
        NavigationDelegate(
          onProgress: (int progress) {
            // Update loading bar.
          },
          onPageStarted: (String url) {},
          onPageFinished: (String url) {},
          onWebResourceError: (WebResourceError error) {},
          onNavigationRequest: (NavigationRequest request) {
            return NavigationDecision.navigate;
          },
        ),
      )
      ..loadRequest(Uri.parse('https://www.google.com/'));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Stack(
        children: [
          Positioned(
              bottom: 0,
              child: Container(
                width: 300,
                height: 300,
                child: WebViewWidget(controller: controller)
              )),
        ],
      ),
    );
  }
}

```
</details>

Please retry on the latest Flutter master channel to see if the issue is fixed or not.

**Comment by zhaobin0122** [comment]
Hi
Thank you very much for your prompt reply. Let me confirm again.




有点小糊涂
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "flutter/flutter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月28日(星期二) 下午3:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [flutter/flutter] The webview_flutter plugin renders problems for android devices with api 28 (Issue #123579)





 
Hi @zhaobin0122
 I checked this on emulator API 28 and on the latest Flutter master channel, the web can be loaded fully.
 The result is the same on webview_flutter: 2.0.0 and the latest version webview_flutter: ^4.0.7.
 

  Sample code (compatible with new plugin version) import 'package:flutter/material.dart'; import 'package:webview_flutter/webview_flutter.dart'; void main() {   runApp(const MyApp()); } class MyApp extends StatelessWidget {   const MyApp({super.key});   @override   Widget build(BuildContext context) {     return MaterialApp(       title: 'Flutter Demo',       theme: ThemeData(         primarySwatch: Colors.blue,       ),       home: const MyHomePage(title: 'Flutter Demo Home Page'),     );   } } class MyHomePage extends StatefulWidget {   const MyHomePage({super.key, required this.title});   final String title;   @override   State<MyHomePage&gt; createState() =&gt; _MyHomePageState(); } class _MyHomePageState extends State<MyHomePage&gt; {   late WebViewController controller;   @override   void initState() {     super.initState();     // #docregion webview_controller     controller = WebViewController()       ..setJavaScriptMode(JavaScriptMode.unrestricted)       ..setBackgroundColor(const Color(0x00000000))       ..setNavigationDelegate(         NavigationDelegate(           onProgress: (int progress) {             // Update loading bar.           },           onPageStarted: (String url) {},           onPageFinished: (String url) {},           onWebResourceError: (WebResourceError error) {},           onNavigationRequest: (NavigationRequest request) {             return NavigationDecision.navigate;           },         ),       )       ..loadRequest(Uri.parse('https://www.google.com/'));   }   @override   Widget build(BuildContext context) {     return Scaffold(       appBar: AppBar(         title: Text(widget.title),       ),       body: Stack(         children: [           Positioned(               bottom: 0,               child: Container(                 width: 300,                 height: 300,                 child: WebViewWidget(controller: controller)               )),         ],       ),     );   } } 
  
Please retry on the latest Flutter master channel to see if the issue is fixed or not.

**Comment by zhaobin0122** [comment]
Hi
I would like to ask you a question. For several devices here, the marked part cannot be rendered (as shown in the figure). What might be the cause.









有点小糊涂
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "flutter/flutter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月28日(星期二) 下午3:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [flutter/flutter] The webview_flutter plugin renders problems for android devices with api 28 (Issue #123579)





 
Hi @zhaobin0122
 I checked this on emulator API 28 and on the latest Flutter master channel, the web can be loaded fully.
 The result is the same on webview_flutter: 2.0.0 and the latest version webview_flutter: ^4.0.7.
 
Sample code (compatible with new plugin version)


  


 import 'package:flutter/material.dart'; import 'package:webview_flutter/webview_flutter.dart'; void main() {   runApp(const MyApp()); } class MyApp extends StatelessWidget {   const MyApp({super.key});   @override   Widget build(BuildContext context) {     return MaterialApp(       title: 'Flutter Demo',       theme: ThemeData(         primarySwatch: Colors.blue,       ),       home: const MyHomePage(title: 'Flutter Demo Home Page'),     );   } } class MyHomePage extends StatefulWidget {   const MyHomePage({super.key, required this.title});   final String title;   @override   State<MyHomePage&gt; createState() =&gt; _MyHomePageState(); } class _MyHomePageState extends State<MyHomePage&gt; {   late WebViewController controller;   @override   void initState() {     super.initState();     // #docregion webview_controller     controller = WebViewController()       ..setJavaScriptMode(JavaScriptMode.unrestricted)       ..setBackgroundColor(const Color(0x00000000))       ..setNavigationDelegate(         NavigationDelegate(           onProgress: (int progress) {             // Update loading bar.           },           onPageStarted: (String url) {},           onPageFinished: (String url) {},           onWebResourceError: (WebResourceError error) {},           onNavigationRequest: (NavigationRequest request) {             return NavigationDecision.navigate;           },         ),       )       ..loadRequest(Uri.parse('https://www.google.com/'));   }   @override   Widget build(BuildContext context) {     return Scaffold(       appBar: AppBar(         title: Text(widget.title),       ),       body: Stack(         children: [           Positioned(               bottom: 0,               child: Container(                 width: 300,                 height: 300,                 child: WebViewWidget(controller: controller)               )),         ],       ),     );   } } 
  
Please retry on the latest Flutter master channel to see if the issue is fixed or not.

**Comment by huycozy** [comment]
It seems you forgot to attach the image so I don't know what the issue is. Please confirm if the original issue still happens or not when you retry on the latest Flutter master channel. If you have another issue, please open a new issue for that for better tracking.
