### ISSUE TITLE
aspectRatio, autoResizeIntervals and autoResize 

### ISSUE THREAD

**Issue by gerardoluisbv** [flutter/flutter#123540]
Is there a way to add the functionality of aspect Ratio, autoResize Intervals and autoResize? In the old version I used a Widget to place Embeds inside my Widget with these parameters and it worked very well but in this new version they don't exist and I have problems with the size of the Embed, I tried a solution taking the size of the document with runJavaScriptReturningResult("" "document.getElementsByClassName("iframe")[0].offsetHeight;""") but it doesn't seem to work, I'll copy my old solution that did work. greetings

```
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

class HtmlEmbed extends StatelessWidget {
	final String html;
	final bool raw;
	const HtmlEmbed({Key? key, required this.html, required this.raw}) : super(key: key);

	@override
	Widget build(BuildContext context) {

		String scripts ="""<script async src=\"https://www.instagram.com/embed.js\"></script>
				<script async src=\"https://platform.twitter.com/widgets.js\"></script>
				<script async defer src=\"https://connect.facebook.net/en_US/sdk.js\"></script>""";
		
		if (raw) {
			scripts = """<link rel=\"stylesheet\" type=\"text/css\" href=\"https://www.domain.com/pf/resources/assets/link.css?d=493\">""";
		}

		return Column(
			children: <Widget>[
				SizedBox(height: 20,),
					WebView(
					Uri.dataFromString(
						"""<!doctype html>
							<html lang="es">
							<head>
								<meta charset="utf-8">
								<meta name="viewport" content="width=device-width">
								$scripts
								<style>
									iframe {
										width: 100% !important;
									}
									.article a {
										color: #0074d9;
									}
								</style>
							</head>
							<body>
							$html
							</body>
							</html>""",
						mimeType: 'text/html',
						encoding: Encoding.getByName('utf-8'),
					).toString(),
					aspectRatio: 16 / 9,
					autoResize: true,
					js: true,
					autoResizeIntervals: [
						Duration(seconds: 3),
						Duration(seconds: 6),
						Duration(seconds: 9),
						Duration(seconds: 12),
						Duration(seconds: 24),
						],
					interceptNavigationRequest: (value) {
						launch(value, forceSafariVC: false);
						return true;
					},
				),

				SizedBox(height: 10,),
			],
		);
	}
}
```

**Comment by darshankawar** [comment]
@gerardoluisbv 
Can you provide `flutter doctor -v` and what exactly are you trying to achieve using the code sample provided above ?
I see that you are using `WebView` widget but don't seem to have `webview_flutter` package imported.



> Is there a way to add the functionality of aspect Ratio, autoResize Intervals and autoResize?

Are you referring these from any package / plugin perspective ?

**Comment by gerardoluisbv** [comment]
Hi @darshankawar 

Thanks for answering, in the code that I have placed above, it is how my previous solution worked fine, and that I would like to use in this new version.

We use the Webview to show Embeds within it (Twitter, Facebook, Instagram), and these parameters fix the size of these Embeds, these are cut off and are not fully visible. This old version of Webview allowed me to send you these parameters that I mentioned in the title. 

I would like to know if they will include this feature in this new version. Greetings

[✓] Flutter (Channel stable, 3.7.7, on Microsoft Windows [Versi¢n 10.0.19043.1706], locale es-PA)
    • Flutter version 3.7.7 on channel stable at C:\Users\gerar\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (4 weeks ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

[✗] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\gerar\AppData\Local\Android\sdk
    • Platform android-33-ext4, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33213.308
    ✗ Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
      development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[✓] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.77.0)
    • VS Code at C:\Users\gerar\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Versi¢n 10.0.19043.1706]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 111.0.5563.147
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 103.0.1264.37

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

**Comment by gerardoluisbv** [comment]
This is my new solution, it seems to work fine but it leaves me spaces in the Widgets and I'm not sure if it works correctly on all devices. Greetings

import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

class HtmlEmbed extends StatefulWidget {
  final String html;
  final bool raw;
  const HtmlEmbed({Key? key, required this.html, required this.raw})
      : super(key: key);

  @override
  State<HtmlEmbed> createState() => _HtmlEmbedState();
}

class _HtmlEmbedState extends State<HtmlEmbed> {
  bool _loading = true;
  late double webViewHeight = 100;
  late double webViewHeightCalc = 100;

  late final WebViewController controller;
  @override
  void initState() {
    super.initState();

    String scripts =
        """<script async src=\"https://www.instagram.com/embed.js\"></script>
				<script async src=\"https://platform.twitter.com/widgets.js\"></script>
				<script async defer src=\"https://connect.facebook.net/en_US/sdk.js\"></script>""";

    if (widget.raw) {
      scripts =
          """<link rel=\"stylesheet\" type=\"text/css\" href=\"https://www.prensa.com/pf/resources/assets/la-prensa.css?d=493\">""";
    }

    controller = WebViewController()

      // ..runJavaScript(scripts)
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setNavigationDelegate(
        NavigationDelegate(
          onPageFinished: (_) async {
            await controller.runJavaScriptReturningResult(
                """document.getElementsByClassName("iframe")[0].offsetHeight;""").then((news) {
              double height = double.parse(news.toString());
              setState(() {
                webViewHeight = height;
                _loading = false;
              });
            });
          },
          onWebResourceError: (WebResourceError error) {},
        ),
      )
      ..loadRequest(Uri.parse(Uri.dataFromString(
        """<!DOCTYPE html>
                <html lang="en" style="border: 1px solid blue;">
                <head>
                <meta charset="UTF-8">
                <meta http-equiv="X-UA-Compatible" content="IE=edge">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
								$scripts
								<style>
									iframe {
										width: 100% !important;
									}
									.article a {
										color: #0074d9;
									}
								</style>
							</head>
							<body style="border: 1px solid blue;">
              <div style="border: 1px solid red;" class="iframe">
							${widget.html}
              </div>
							</body>
							</html>""",
        mimeType: 'text/html',
        encoding: Encoding.getByName('utf-8'),
      ).toString()));
  }

  @override
  Widget build(BuildContext context) {
    return _loading
        ? const Center(child: CircularProgressIndicator())
        : Center(
            child: Container(
                height: webViewHeight,
                child: WebViewWidget(controller: controller)));
  }
}

**Comment by darshankawar** [comment]
Thanks for the update. So if I understand correctly, in your previous solution, the parameters `aspectRatio`, `autoResizeIntervals` and `autoResize` were part of `webview_flutter` package, but not anymore in current version ?

**Comment by gerardoluisbv** [comment]
Will these features be integrated in new versions? What solution is recommended in this case?
