### ISSUE TITLE
firebase storage image not showing on iOS when Apple reviewer review the app

### ISSUE THREAD

**Issue by hussenIbrahim** [flutter/flutter#123554]
all API work without any issue on android and simulator and real iOS devices
TestFlight version also works
only during review  process firebase storage image links throw error 

`SocketException: Connection refused (OS Error: Connection refused, errno= 61), address = firebasestorage.googleapis.com, port = 63689`
iPad  iOS 16.3.1

**Comment by darshankawar** [comment]
@hussenIbrahim 
firebase related issues need to be reported in dedicated repo: https://github.com/firebase/flutterfire/issues
Closing from here.
