### ISSUE TITLE
Autosubmit bot message calculates reviewer number incorrectly

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#123555]
https://github.com/flutter/flutter/pull/122275#issuecomment-1485495304
```
auto label is removed for flutter/flutter, pr: 122275, due to This PR has not met approval requirements for merging. You have project association CONTRIBUTOR and need 0 more review(s) in order to merge this PR.

Merge guidelines: You need at least one approved review if you are already a MEMBER or two member reviews if you are not a MEMBER before re-applying the autosubmit label. Reviewers: If you left a comment approving, please use the "approve" review action instead.
```

Apparently it should `need 1 more review in order to merge this PR`. As of the time this message popped up, the PR had just one approval from a MEMBER, and the owner's association is CONTRIBUTOR.

/cc @ricardoamador

**Comment by gnprice** [comment]
A related issue with that message text:
* #123665

**Comment by ricardoamador** [comment]
Ah okay this is a really odd one. It looks like any time someone reviews a pull request the review is added to the nodes. So a reviewer can actually review a pull request multiple times. Autosubmit was tracking the individual reviewers just not the number of times that person had submitted a review. I will send out a fix shortly.
