### ISSUE TITLE
libtxt: Text metrics are sometimes wrong (in different ways on different platforms at different sizes)

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#12357]
When the textScaleFactor in a RenderParagraph is not 1.0, or the font size is particular sizes (even without scaling) the Linux tests render, or at least measure, widths that are different than the same tests on Mac.  When they are off, they appear to be exactly one pixel off, and only in width.

Mac: fontSize: 10.0, textScaleFactor: 1.3 --> 13.0 wide
Linux: fontSize: 10.0, textScaleFactor: 1.3 --> 14.0 wide

Mac: fontSize: 123.0, textScaleFactor: 1.3 --> 160.0 wide
Linux: fontSize: 123.0, textScaleFactor: 1.3 --> 161.0 wide

Mac: fontSize: 100.0, textScaleFactor: 2.0 --> 200.0 wide
Linux: fontSize: 100.0, textScaleFactor: 2.0 --> 201.0 wide

BUT:
Mac: fontSize: 200.0, textScaleFactor: 2.0 --> 400.0 wide
Linux: fontSize: 200.0, textScaleFactor: 2.0 --> 400.0 wide

So it's not ALL the time, for all scales/font sizes.  This suggests some subtle difference in font rendering on one/both platforms.

Since Blink-based text rendering is being replaced, re-evaluate this bug once that has completed.

Some tests affected by this:
```
test/painting/text_painter_test.dart
test/widgets/text_test.dart
test/rendering/paragraph_test.dart
```
There is a `TODO(#12357)` in `paragraph_test.dart` that marks where the test should have the `anyOf` converted to a single value once this issue is fixed.

**Comment by Hixie** [comment]
Since the scale factor is entirely in the framework, not the engine, if this happens only when you have a scale factor, it suggests the bug is with the scale factor code, not with the font rendering.

**Comment by gspencergoog** [comment]
Actually, at your suggestion, I tried it without the scaling changes, and it also occurs with just fontSize.  It works for some font sizes and not others.

**Comment by gspencergoog** [comment]
As an example of one where it's just the fontSize, if you remove the textScaleFactor from 'nested TextSpans in paragraph handle textScaleFactor correctly.' in [`paragraph_test.dart`](https://github.com/flutter/flutter/blob/master/packages/flutter/test/rendering/paragraph_test.dart), the sizes that should appear in the `expect`s for the text spans should all be either 20.0 or 10.0, depending on the requested font size. The width of the span with 'b' in it is 21.0 instead of 20.0, but only on Linux.

**Comment by Hixie** [comment]
We are planning on not looking at this carefully until after libtxt lands.

**Comment by chinmaygarde** [comment]
Font discovery is not handled by Skia. The engine does this. I am removing the tag.

**Comment by yjbanov** [comment]
Has there been any progress on this? I noticed that `chip_test.dart` contains some unrealistic expectations for text size. For example, the test "Chip in row works ok" expects the string "Test" and "Ahem" font of size 10.0 and 1x scale factor to be `Size(40.0, 10.0)`, which seems very unlikely. It should be closer to `Size(20.0, 10.0)`. So there's a 2x discrepancy in width.

**Comment by Hixie** [comment]
at 10px and 1x scale factor, four characters of Ahem should be exactly 40px wide, 10px high, with the baseline 8px from the top, and intraline spacing of 10px baseline-to-baseline (i.e. zero leading).

See also http://www.hixie.ch/resources/fonts/

**Comment by yjbanov** [comment]
A-ha! I was testing in the browser but failed to load the font :man_facepalming: so nvm

**Comment by zoechi** [comment]
@gspencergoog is this still relevant?

**Comment by Sp4Rx** [comment]
#48069 Same issue for images too.

**Comment by GaryQian** [comment]
The way Coretext interprets fonts produces slightly different results than FreeType. These differences are manifested directly in the metrics provided by skia, which in turn is dependent on either Coretext on mac, and FreeType on other platforms.

cc @Rusino Do you know anything about the exact reason why there is this difference? I imaging it is a combination of subtle rounding/bit-precision/design choices that result in tiny differences.
