### ISSUE TITLE
Firebase Auth implementation for signInWithCustomToken.

### ISSUE THREAD

**Issue by chrislondon** [flutter/flutter#12361]
I currently only see the following implemented sign in functions for Firebase Auth:

- signInAnonymously
- signInFacebook
- signInGoogle
- signInWithEmailAndPassword

Firebase is a retro fit for our legacy app and so we are using the custom token SDK on our Python backend.

How hard would it be to implement `signInWithCustomToken()`?

**Comment by christian-lefty** [comment]
One of our devs submitted a PR for this: https://github.com/flutter/plugins/pull/212

**Comment by romelgomez** [comment]
Hi folks, 

Currently firebase has now support for python with firebase_admin 

https://github.com/firebase/firebase-admin-python

but this method signInWithCustomToken is not available... 

https://firebase.google.com/docs/reference/admin/python/firebase_admin.auth

how this workflow is now implemented with the new API?.

**Comment by kroikie** [comment]
@chrislondon

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/964. Any further collaboration will be done there.
