### ISSUE TITLE
Update pinned test_api dependency to 0.5.0

### ISSUE THREAD

**Issue by jakemac53** [flutter/flutter#123603]
Tracking issue for updating test_api, cc @itsjustkevin. I can't link this directly to the Dart 3 milestone, not sure how you want to do the tracking.

This will allow flutter users to try out the new `checks` package, and will prevent confusion about not being able to get the latest version of `test` when fetching packages.

**Comment by natebosch** [comment]
The package roll in #123350 updates the `test_api` dependency. It is currently blocked by the `packages` repo pinning dependencies that require an older `analyzer` which blocks the latest test packages.

https://github.com/flutter/packages/pull/3544

**Comment by itsjustkevin** [comment]
Thanks @jakemac53 added to the cleanup list here https://github.com/dart-lang/sdk/issues/51813.

**Comment by natebosch** [comment]
This was done in #123350
