### ISSUE TITLE
[shared_preferences] support storing null

### ISSUE THREAD

**Issue by yangzai100** [flutter/flutter#123680]
Currently in shared_preferences, prefs.setBool('my_bool_null', null); is not supported, but bool can be true, false, or null.

**Comment by danagbemava-nc** [comment]
Wouldn't it be better to use the `remove` method in that case? From what I gather, SharedPreferences on android will return a boolean when getBoolean is called (even if the value saved is null) and it seems NSUserDefaults also does the same thing. I'm not sure about the other platforms but supporting null on some when it isn't supported on others might just lead to confusion
