### ISSUE TITLE
/C:/Flutter%20src/flutter/packages/flutter/lib/src/painting/border_radius.dart

### ISSUE THREAD

**Issue by sawchin** [flutter/flutter#123610]
how can we solve this issue?
/C:/Flutter%20src/flutter/packages/flutter/lib/src/painting/border_radius.dart

**Comment by darshankawar** [comment]
There's not enough details provided to analyze it properly. Please use new issue template and fill out requested details so that we can address it properly. Or you can ask the same on support channels like StackOverflow.
Closing due to lack of details.
