### ISSUE TITLE
Autosubmit bot mentions MEMBER vs CONTRIBUTOR association, which isn't the logic it acts on

### ISSUE THREAD

**Issue by gnprice** [flutter/flutter#123665]
I've recently been seeing comments from the auto-submit bot like this one (https://github.com/flutter/flutter/pull/123426#issuecomment-1487774092 ):

> auto label is removed for flutter/flutter, pr: 123426, due to This PR has not met approval requirements for merging. You have project association CONTRIBUTOR and need 1 more review(s) in order to merge this PR.
> 
> * Merge guidelines: You need at least one approved review if you are already a MEMBER or two member reviews if you are not a MEMBER before re-applying the autosubmit label. **Reviewers**: If you left a comment approving, please use the "approve" review action instead.

This text is misleading, because the difference between an association of CONTRIBUTOR and an association of MEMBER does not govern the bot's behavior in that way. It's not supposed to do so, either; the bot's behavior seems to be correct, and it's only the message that is wrong.

The logic the autosubmit bot [is supposed to have](https://github.com/flutter/flutter/wiki/Tree-hygiene#getting-a-code-review), and that it appears to indeed have, is that there need to be either:
* two approvals from people in [the flutter-hackers group](https://github.com/flutter/flutter/wiki/Contributor-access);
* or one such approval, if the author is also in that group.

From what I can see, it looks like many people in flutter-hackers have association CONTRIBUTOR (not MEMBER); and on the other hand some people who are *not* in flutter-hackers also have association CONTRIBUTOR. So the bot's description of its behavior should probably not involve the concept of "association", or the values CONTRIBUTOR and MEMBER, at all.

---

For example, in that PR #123426:
* The author is not a flutter-hackers member.
* The reviewer who first approved the PR is in flutter-hackers, and has association CONTRIBUTOR with the repository. (See https://api.github.com/repos/flutter/flutter/pulls/123426/reviews .)
* So when that was the only approval, the bot correctly rejected the auto-submission, because there was only one flutter-hackers approval.
* I am also in flutter-hackers, and also have association CONTRIBUTOR.
* A few hours after that message from the bot, I added an approval and re-added the "autosubmit" label.
* This time, the bot cheerfully merged the PR.
* This was the correct behavior, because there were now two flutter-hackers approvals.
* But it was in direct contradiction of what the bot's comment had said, because there were still zero MEMBER approvals, not two of them.

**Comment by ricardoamador** [comment]
Hi @gnprice you make good points here. I am working on changes to autosubmit and this will be addressed. This is something that has been happening for a while but will be addressed shortly.

**Comment by ricardoamador** [comment]
This has been addressed in the new configurable iteration of autosubmit. We now perform the check against team membership in flutter-hackers and implement a 1+ review if you are a flutter-hacker member or a 2+ review if you are not a flutter-hacker member. We no longer use CONTRIBUTOR, MEMBER or OWNER authorAssociation.
