### ISSUE TITLE
web compile benchmarks running on host with Moto G4 attached?

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#123690]
As far as I understand, the web compile benchmarks do not need a host with a phone attached.

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20flutter_gallery_v2_web_compile_test/8124/overview

https://github.com/flutter/flutter/blob/master/.ci.yaml#L1903

Unfortunately, moving to a machine without a device attached will break the SkiaPerf series since the dimensions will be different.

https://flutter-flutter-perf.skia.org/e/?begin=1680042218&end=1680068938&keys=X30be105b706881c87490b8befc483ed1&selected=commit%3D34052%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DMoto_G__4_%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253Dnew_gallery_canvaskit_wasm_compressed_bytes%252Ctest%253Dflutter_gallery_v2_web_compile_test%252C&xbaroffset=34050

cc @keyonghan @yjbanov

**Comment by yjbanov** [comment]
I'm ok with rebooting the Skia Perf series. Typically I review benchmarks as one big batch, and it's not that hard to spot series switching configurations. It just looks like a line that changed color at some point.
