### ISSUE TITLE
[engine] When Windows app handles WM_CLOSE, requestAppExit doesn't do the right thing.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#123654]
In an application that wants to handle WM_CLOSE in a special way (like continuing to run in the background), the event handling that the `WindowsLifecycleManager` does isn't optimal: it prevents the custom WM_CLOSE handler from running, since it always handles the event, preventing the event from propagating.

Perhaps the event should never be handled by the `WindowsLifecycleManager`, and if the app allows the exit request, then it will exit, closing the window anyhow, and aborting the window close itself should be handled by the (as yet nonexistent) windowing API.

If that's not the solution, then perhaps this is what we need to do:

1. Windows sends WM_CLOSE message
2. Flutter eats the Windows message and notifies the framework
3. If the framework cancels the exit, Flutter creates a new WM_CLOSE message
4. This new WM_CLOSE message is ignored by Flutter, allowing the app to use custom logic

In any case, we need to evaluate how to enable this scenario.

Related internal issue: b/275565297

**Comment by loic-sharma** [comment]
Tagged as P3 as we should prioritize the revert. We can downgrade issue once revert lands.

**Comment by yaakovschectman** [comment]
It looks like the issue you linked resulted because the message handler we register for `WM_CLOSE` consumes the message and stops the propagation, while the app in question expects to receive it for system tray minimization, so even if we follow those 4 steps you laid out, the app won't receive the message. It might be easier if they migrate to using the proper handler API for their message handling instead of modifying `FlutterWindow` directly.

**Comment by gspencergoog** [comment]
It would receive the second WM_CLOSE that was generated by the engine, since we would ignore the one we generated ourselves.

**Comment by gspencergoog** [comment]
Lowering priority since the original has been reverted.

**Comment by yaakovschectman** [comment]
And for clarity, is that suggestion that the application exit request handle these `WM_CLOSE` messages, or that a future windowing API do?

**Comment by gspencergoog** [comment]
> And for clarity, is that suggestion that the application exit request handle these WM_CLOSE messages, or that a future windowing API do?

Sorry, I'm not sure I understand the question.  The suggestion is that we modify the WM_CLOSE handling to always handle the message when it first is presented, and then to synthesize a new one if the app decides to not cancel the close.
