### ISSUE TITLE
Unable able read the command line argument in flutter integration test code

### ISSUE THREAD

**Issue by jagadeeshpurplle** [flutter/flutter#123605]
I'm running `flutter integration test` on `firebase test lab` (Ref: https://github.com/flutter/flutter/tree/main/packages/integration_test#android-device-testing) by building the app & test APK via shell script like below, where i'm also passing an argument `--dart-define="FIREBASE_ACCESS_TOKEN=$accessToken` to read in my test function.
```
pushd android
flutter build apk --flavor uat --debug --dart-define="FIREBASE_ACCESS_TOKEN=$accessToken"
./gradlew app:assembleUatDebugAndroidTest
./gradlew app:assembleUatDebug -Ptarget=$(pwd)/../integration_test/"$target"
popd
```
, I'm trying to read the value that i passed in `command line argument` in my test function like below,
```
    testWidgets('Verify first user credit health', (tester) async {
      app.main();
      const accessToken = String.fromEnvironment("FIREBASE_ACCESS_TOKEN");
      var accessTokenVar = Platform.environment["FIREBASE_ACCESS_TOKEN"];
      print('accessToken from cmd: $accessToken');
      print('accessTokenVar from cmd: $accessTokenVar');
    });
```
But, those were printing `empty/null` values instead of actual, 
However if i run the tests on local via `flutter test integration_test/regression/regression_test.dart --flavor uat --dart-define="TEST=<someValue>`,  then its working to print the values properly.

Can anyone help me in this regard?
@exaby73

**Comment by exaby73** [comment]
Is your `app:assembleUatDebugAndroidTest` or `app:assembleUatDebug` rebuilding the APK or using the one built with Flutter?

**Comment by jagadeeshpurplle** [comment]
- I'm using `flutter build apk --flavor uat --debug......` command which does generates files in `android/` folder for building the app.
- Then i'm building `app apk` by `app:assembleUatDebug` & `test apk` via `app:assembleUatDebugAndroidTest` which using the files from `android/` folder.!

**Comment by exaby73** [comment]
Any reason why you can't use `flutter test` directly?

**Comment by jagadeeshpurplle** [comment]
- `flutter test...` won't work on firebase test lab, as firebase test lab requires the `App APK ` & `Test APK`.
> Official Documentation is here: https://github.com/flutter/flutter/tree/main/packages/integration_test#android-device-testing 

- So, I need to use `flutter build...` command & then `./gradlew app:assembleUatDebugAndroidTest` to build the `Test APK` and `./gradlew app:assembleUatDebug -Ptarget=$(pwd)/../integration_test/"$target"` to build the `App APK`

**Comment by jagadeeshpurplle** [comment]
This solution worked: https://stackoverflow.com/a/72064105/8140419

we can pass `--dart-define` to gradlew command.!

- Flutter `dart-define` flag is encoded to base64, so we need convert it into base64 encoded string and pass it like below.

For ex: 

- If i want to pass `-Pdart-defines=token=tokenValue`, then i need to convert `token=tokenValue` to base64 which is `dG9rZW49dG9rZW5WYWx1ZQ==`.
- Final command will be: `./gradlew app:assembleUatDebug -Ptarget=$(pwd)/../integration_test/"$target"  -Pdart-defines="dG9rZW49dG9rZW5WYWx1ZQ=="`
