### ISSUE TITLE
Button taps are cancelled when moved inside the container

### ISSUE THREAD

**Issue by frankvollebregt** [flutter/flutter#123675]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Activate the button by tapping it
3. The tap event goes through (as expected)
4. Activate the button, but drag outside the button
5. The tap event is cancelled (as expected)
6. Activate the button, but drag inside the button
7. The tap event is cancelled (but it shouldn't be)

**Expected results:** 
This video from a native Android app shows the expected behavior:

https://user-images.githubusercontent.com/23523399/228458702-438871c6-46d2-47ae-b386-ba1120c8c580.mp4

When ending the gesture inside the button/container, I expect that the tap event comes through. When moving out (as already happens) I expect the event to be cancelled.

This example is the messages app, but almost all apps show this same behavior (Gmail, Phone, Calendar, Whatsapp, Telegram, Signal, ...).

**Actual results:** 
This video from the default demo Flutter app (with the FAB extended for better visiblity) shows the actual behavior in Flutter.

https://user-images.githubusercontent.com/23523399/228461949-a904a992-0124-4ef8-ad21-208880a0e84f.mp4

In Flutter, when the touch moves away too far from the starting position, independent of whether it was moved inside or out of the container, the tap event gets cancelled.

As a result of this, users of my app have reported buttons not working, as they accidentally did a small swiping motion when trying to tap a button.

<details>
<summary>Code sample</summary>

The code sample below is mostly identical to the default Flutter demo app.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: _incrementCounter,
        label: const Text('Increment'),
        icon: const Icon(Icons.add),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
Analyzing test_app...
No issues found! (ran in 1.3s)
```

```
[√] Flutter (Channel stable, 3.7.7, on Microsoft Windows [Version 10.0.22000.1696], locale nl-NL)
    • Flutter version 3.7.7 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (3 weeks ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
    • Android SDK at C:\Users\fvollebregt\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.0.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.76.2)
    • VS Code at C:\Users\fvollebregt\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • Pixel 2 (mobile)  • FA8271A02656 • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows      • windows-x64    • Microsoft Windows [Version 10.0.22000.1696]
    • Chrome (web)      • chrome       • web-javascript • Google Chrome 111.0.5563.146
    • Edge (web)        • edge         • web-javascript • Microsoft Edge 111.0.1661.54

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment]
Thanks for filing a detailed issue, @frankvollebregt 
I also can simulate a simple case with a Container wrapped by InkWell/GestureDetector to detect its `onTap` gestures:

```dart
InkWell(
  onTapDown: (details) {
    print('onTapDown');
  },
  onTapUp: (details) {
    print('onTapUp');
    setState(() {
      _counter++;
    });
  },
  onTapCancel: () {
    print('onTapCancel');
  },
  child: Container(
    width: 200,
    height: 200,
    color: Colors.blue,
  ),
)
```

<details>
<summary>Demo video</summary>

https://user-images.githubusercontent.com/104349824/228504323-e3fde53e-5e2a-4077-b9a4-0f6968a7a865.mp4

</details>

 I notice that `onTapCancel` will be invoked when dragging the tap (inside the Container) away from the initial position (by onTapDown), so it will cause `onTapUp` to be canceled.

This is a known issue being tracked at # #75732. So I will close this issue in favor of that issue. 

Please leave there your comment about your use case and react an upvote to the original comment will help to raise the issue. If you disagree, please write in the comments and I will reopen it. Thank you!

**Comment by frankvollebregt** [comment]
Thank you for the quick response @huycozy! It's a bit concerning that the referenced issue has been open for over two years without any comments 😟 I'll post my comment there.
