### ISSUE TITLE
[Android] TextField not recognizing dead keys with an external keyboard

### ISSUE THREAD

**Issue by aleripe** [flutter/flutter#123689]
Flutter TextField does not recognize dead keys with an external keyboard setup in US_INTERNATIONAL or SPANISH on Android. On the same device (an LG V30 I use for debugging) an keyboard Gmail properly works. I haven't tested it with other platforms.

## Steps to Reproduce

1. Execute `flutter run` on the minimal code sample
2. Attach an external keyboard
3. Configure it to use a profile with dead keys (i.e. US_INTERNATIONAL or SPANISH)
4. Type ^ followed by a

**Expected results:** â

**Actual results:** ^a

<details>
<summary>Code sample</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter TextField issue',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyScreen(title: 'Flutter TextField issue'),
    );
  }
}

class MyScreen extends StatefulWidget {
  const MyScreen({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyScreen> createState() => _MyScreenState();
}

class _MyScreenState extends State<MyScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body:
          Column(mainAxisSize: MainAxisSize.min, children: const [TextField()]),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
I/ViewRootImpl(19182): ViewRoot's KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_SHIFT_LEFT, scanCode=42, metaState=META_SHIFT_ON|META_SHIFT_LEFT_ON, flags=0x8, repeatCount=0, eventTime=724116207, downTime=724116207, deviceId=14, source=0x301 } to DecorView@e561275[MainActivity]
I/ViewRootImpl(19182): ViewRoot's KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_SHIFT_LEFT, scanCode=42, metaState=META_SHIFT_ON|META_SHIFT_LEFT_ON, flags=0x88, repeatCount=1, eventTime=724116708, downTime=724116207, deviceId=14, source=0x301 } to DecorView@e561275[MainActivity]
I/ViewRootImpl(19182): ViewRoot's KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_SHIFT_LEFT, scanCode=42, metaState=META_SHIFT_ON|META_SHIFT_LEFT_ON, flags=0x8, repeatCount=2, eventTime=724116762, downTime=724116207, deviceId=14, source=0x301 } to DecorView@e561275[MainActivity]
I/ViewRootImpl(19182): ViewRoot's KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_SHIFT_LEFT, scanCode=42, metaState=META_SHIFT_ON|META_SHIFT_LEFT_ON, flags=0x8, repeatCount=3, eventTime=724116812, downTime=724116207, deviceId=14, source=0x301 } to DecorView@e561275[MainActivity]
I/ViewRootImpl(19182): ViewRoot's KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_SHIFT_LEFT, scanCode=42, metaState=META_SHIFT_ON|META_SHIFT_LEFT_ON, flags=0x8, repeatCount=4, eventTime=724116863, downTime=724116207, deviceId=14, source=0x301 } to DecorView@e561275[MainActivity]
I/ViewRootImpl(19182): ViewRoot's KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_SHIFT_LEFT, scanCode=42, metaState=META_SHIFT_ON|META_SHIFT_LEFT_ON, flags=0x8, repeatCount=5, eventTime=724116913, downTime=724116207, deviceId=14, source=0x301 } to DecorView@e561275[MainActivity]
I/ViewRootImpl(19182): ViewRoot's KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_SHIFT_LEFT, scanCode=42, metaState=META_SHIFT_ON|META_SHIFT_LEFT_ON, flags=0x8, repeatCount=6, eventTime=724116964, downTime=724116207, deviceId=14, source=0x301 } to DecorView@e561275[MainActivity]
I/ViewRootImpl(19182): ViewRoot's KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_SHIFT_LEFT, scanCode=42, metaState=META_SHIFT_ON|META_SHIFT_LEFT_ON, flags=0x8, repeatCount=7, eventTime=724117016, downTime=724116207, deviceId=14, source=0x301 } to DecorView@e561275[MainActivity]
I/ViewRootImpl(19182): ViewRoot's KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_6, scanCode=7, metaState=META_SHIFT_ON|META_SHIFT_LEFT_ON, flags=0x8, repeatCount=0, eventTime=724117020, downTime=724117020, deviceId=14, source=0x301 } to DecorView@e561275[MainActivity]
I/ViewRootImpl(19182): ViewRoot's KeyEvent { action=ACTION_UP, keyCode=KEYCODE_6, scanCode=7, metaState=META_SHIFT_ON|META_SHIFT_LEFT_ON, flags=0x8, repeatCount=0, eventTime=724117148, downTime=724117020, deviceId=14, source=0x301 } to DecorView@e561275[MainActivity]
I/ViewRootImpl(19182): ViewRoot's KeyEvent { action=ACTION_UP, keyCode=KEYCODE_SHIFT_LEFT, scanCode=42, metaState=0, flags=0x8, repeatCount=0, eventTime=724117607, downTime=724117020, deviceId=14, source=0x301 } to DecorView@e561275[MainActivity]
I/ViewRootImpl(19182): ViewRoot's KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_A, scanCode=30, metaState=0, flags=0x8, repeatCount=0, eventTime=724117990, downTime=724117990, deviceId=14, source=0x301 } to DecorView@e561275[MainActivity]
I/ViewRootImpl(19182): ViewRoot's KeyEvent { action=ACTION_UP, keyCode=KEYCODE_A, scanCode=30, metaState=0, flags=0x8, repeatCount=0, eventTime=724118049, downTime=724117990, deviceId=14, source=0x301 } to DecorView@e561275[MainActivity]
```
</details>

<details>
  <summary>Flutter Doctor</summary>
[√] Flutter (Channel stable, 3.7.8, on Microsoft Windows [Versione 10.0.19044.2728], locale it-IT)
    • Flutter version 3.7.8 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 90c64ed42b (8 days ago), 2023-03-21 11:27:08 -0500
    • Engine revision 9aa7816315
    • Dart version 2.19.5
    • DevTools version 2.20.1

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Alessandro\AppData\Local\Android\sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.21)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.33027.164
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] VS Code (version 1.71.2)
    • VS Code at C:\Users\Alessandro\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.48.0

[√] Connected device (4 available)
    • LG H930 (mobile)  • LGH9308e11f266 • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows        • windows-x64    • Microsoft Windows [Versione 10.0.19044.2728]
    • Chrome (web)      • chrome         • web-javascript • Google Chrome 111.0.5563.111
    • Edge (web)        • edge           • web-javascript • Microsoft Edge 111.0.1661.54

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment]
Thanks for the report, @aleripe! This is a known issue being tracked at https://github.com/flutter/flutter/issues/59541. Closing this issue as a duplicate, so please follow up on it for further updates.
