### ISSUE TITLE
MenuAnchor ```clipBehaviour``` property isn't wired up to the widget

### ISSUE THREAD

**Issue by whiskeyPeak** [flutter/flutter#123628]
Modifying the ```clipBehaviour``` property doesn't change the behaviour of the clip. 

https://user-images.githubusercontent.com/73116038/228339077-459b3adc-9b28-43c4-bd13-34b22d6a5b33.mp4

This is because even though the ```clipBehaviour``` property is passed down the tree, it isn't actually set.  On line 3315 of file menu_anchor.dart, the ```clipBehaviour``` property is hard coded as Clip.hardEdge.
This is occurring on both stable and master.

Will fill a pr shortly :)

**Comment by darshankawar** [comment]
Thanks for the report and potential fix.

https://github.com/flutter/flutter/blob/47c92c00b05a499b24b749137c20d4f3798667a7/packages/flutter/lib/src/material/menu_anchor.dart#L3315
