### ISSUE TITLE
Inscruitable error

### ISSUE THREAD

**Issue by WorikQCI** [flutter/flutter#123633]
This is not an issue about the error itself.

It is the message from the compiler.

```
warning: Unable to read contents of XCFileList '/Target Support Files/Pods-Runner/Pods-Runner-frameworks-Release-output-files.xcfilelist' (in target 'Runner' from project 'Runner')
error: Unable to load contents of file list: '/Target Support Files/Pods-Runner/Pods-Runner-frameworks-Release-input-files.xcfilelist' (in target 'Runner' from project 'Runner')
error: Unable to load contents of file list: '/Target Support Files/Pods-Runner/Pods-Runner-frameworks-Release-output-files.xcfilelist' (in target 'Runner' from project 'Runner')
warning: Run script build phase '[CP] Embed Pods Frameworks' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
** BUILD FAILED **
```

There are two problems that are immediatly apparent::

1. `warning: Unable to read contents of XCFileList '/Target Support Files/Pods-Runner/Pods-Runner-frameworks-Release-output-files.xcfilelist' (in target 'Runner' from project 'Runner')`

The path: `/Target Support Files/` does not exist

2.  `warning: Run script build phase`  This error ocurs running `flutter build macos`.  That is the "script build phase" as far as I know.

Obviously I am inexperienced, only 9 months in to Flutter development, but these error messages are less than helpful

## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
4. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment]
@WorikQCI 
Thanks for the report. Is there a way for you to provide code sample that generates the reported log ?
Also, see if [this](https://github.com/flutter/flutter/issues/115804) issue helps to understand the scenario a bit better ?

**Comment by huycozy** [comment]
Thanks for your response, @WorikQCI 
It seems you have solved it yourself. So I will close this issue from here. Next time, when you see it again, please try to be more specific on `Steps to reproduce` along with the output of `flutter doctor -v` and complete error log so that we may verify the issue properly.
