### ISSUE TITLE
Dialog.fullscreen has bottom barrier in iOS

### ISSUE THREAD

**Issue by jgarciamccausland** [flutter/flutter#123611]
I am trying to implement a fullscreen dialog using Dialog.fullscreen but I am getting a bottom barrier. I would like to keep the top barrier but have the fullscreen dialog positioned so that it starts at the absolute bottom of the screen without the barrier. 

This is occurring on iOS devices (tested on both iPhones and iPads) without a physical button. Android seems to be working as expected. 

```
onTap:() {
  showDialog<void>(
    context: currentContext,
    builder: (BuildContext context) {
      return const Dialog.fullscreen(
        child: Center(child: Text("Fullscreen Dialog"),),
      );
    },
  );
},
```

https://user-images.githubusercontent.com/91960896/228292070-6e144ec1-67fb-4b65-9502-d429bf724721.mov

![Screenshot 2023-03-28 at 11 25 56 AM](https://user-images.githubusercontent.com/91960896/228288144-6050f8f1-1655-4395-8928-47213003cec7.png)

![Screenshot 2023-03-28 at 11 25 41 AM](https://user-images.githubusercontent.com/91960896/228288161-e5bf2ac2-7819-4f9a-b16d-a106b9ddb768.png)

**Comment by jgarciamccausland** [comment]
@TahaTesser Since you worked on the Dialog.fullscreen feature I figure you may have some additional insight. Do you know if this is intentional? Or if there is a way around this?

**Comment by TahaTesser** [comment]
Hi @jgarciamccausland 

You can disable safe area in the `showDialog` to get rid of the safe area paddings.

```dart
          showDialog<void>(
              context: context,
              useSafeArea: false,
              builder: (BuildContext context) {
                return const Dialog.fullscreen(
                  child: Center(
                    child: Text('Fullscreen Dialog'),
                  ),
                );
              },
            );
```

<img src="https://user-images.githubusercontent.com/48603081/228463352-ecdf837c-bb73-41b6-b625-beb8b8ff8b20.png" height="450" />	|

> I would like to keep the top barrier but have the fullscreen dialog positioned so that it starts at the absolute bottom of the screen without the barrier.

For this use case, you can first disable the safe area for the `showDialog` and then add wrap `Dialog.fullscreen` with your own `SafeArea` widget.
```dart
            showDialog<void>(
              context: context,
              useSafeArea: false,
              builder: (BuildContext context) {
                return const SafeArea(
                  bottom: false,
                  child: Dialog.fullscreen(
                    child: Center(
                      child: Text('Fullscreen Dialog'),
                    ),
                  ),
                );
              },
            );
```


<img src="https://user-images.githubusercontent.com/48603081/228463371-f45350b1-96de-4902-8ab3-e6c6664d7013.png" height="450" />	|



Ths should solve your issue, feel free to comment below with any questions.

**Comment by jgarciamccausland** [comment]
Ahh, brilliant. I ended up disabling the safe area but knowing we can implement the initial design with the second option is fantastic. Thank you very much.
