### ISSUE TITLE
Flutter Engine load - add-to-app scenario

### ISSUE THREAD

**Issue by hemantchauhan** [flutter/flutter#123685]
I am creating a package module in Flutter to add to my native iOS App. 

## Steps to Reproduce

Add in the native app, flutter frameworks created by  `flutter build iOS-framework` command.
In my `AppDelegate`, I am running `FlutterEngine().run` to pre-load engine.
This makes `main()` method of my Flutter code to run and `MyCalendarApp ` initiates which has a child `FutureBuilder` which gets executed while the `FlutterViewController` is not even pushed yet.

```
void main() {
  // This call ensures the Flutter binding has been set up before creating the
  // MethodChannel-based model.
  WidgetsFlutterBinding.ensureInitialized();
  runApp(
    const MyCalendarApp(),
  );
}
```

In AppDelegate - 

```
flutterEngine = FlutterEngine(name: flutterEngineName);
flutterEngine.run()
```

**Expected results:**  MyCalendarApp code should be initiated when I push the actual flutter viewcontroller

**Actual results:**   FutureBuilder runs on Native App launch due to MyCalendarApp initialisation. 

I have read [add-to-app/performance](https://docs.flutter.dev/development/add-to-app/performance#creating-and-running-a-dart-isolatel) and I understand it works this way.
So how can i make sure that my FutureBuilder will only be called when i push the `FlutterViewController`?
<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by huycozy** [comment]
Could you provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) for this case? 

Also, please provide the output of `flutter doctor -v` as well. Thanks!
