### ISSUE TITLE
Large regression in web_size__compile_test

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#123691]
SkiaPerf is reporting a several MB regression in uncompressed size on the engine roll here https://github.com/flutter/flutter/commit/5cd942f1545123c059079eb2df31702188bb3949:

https://flutter-flutter-perf.skia.org/e/?begin=1680063663&end=1680068938&keys=X41e9925328f9df4124939a70b0c3ec7a&selected=commit%3D34052%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DMoto_G__4_%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253Dbasic_material_app_canvaskit_wasm_uncompressed_bytes%252Ctest%253Dweb_size__compile_test%252C&xbaroffset=34052

Eyeballing the commits, it seems like this is due to https://github.com/flutter/engine/pull/40737, but I'm marking this P2 for initial triage.

cc @hterkelsen @eyebrowsoffire

**Comment by zanderso** [comment]
Also https://flutter-flutter-perf.skia.org/e/?begin=1680046748&end=1680074162&keys=X30be105b706881c87490b8befc483ed1&num_commits=50&request_type=1&xbaroffset=34052

**Comment by hterkelsen** [comment]
Our current build flags for CanvasKit are our best compromise of size and performance. We are still looking into how we can improve code size but this regression isn't a P2.
