### ISSUE TITLE
TextSpan's default  text color should be black when the themeMode is light

### ISSUE THREAD

**Issue by gkdgo** [flutter/flutter#123663]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 
TextSpan's default  text color should be black when the themeMode is light
**Actual results:** 
TextSpan's default  text color is white
<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

Future<void> main() async {
  return runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(context) {
    return const MaterialApp(
      themeMode: ThemeMode.light,
      home: PageHome(),
    );
  }
}

class PageHome extends StatefulWidget {
  const PageHome({Key? key}) : super(key: key);

  @override
  State<PageHome> createState() => _PageHomeState();
}

class _PageHomeState extends State<PageHome> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Home'),
      ),
      body: Column(
        children: [
          Container(
              color: Colors.green,
              child: RichText(
                text: const TextSpan(
                  text: 'Home',
                ),
              )),
          const Text('Home'),
        ],
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

</details>
<img width="278" alt="image" src="https://user-images.githubusercontent.com/55651847/228462622-6ed716ee-e743-4335-96e5-e8c9f470352f.png">

**Comment by exaby73** [comment]
Hello @gkdgo. What is your system theme set to in the MacOS settings?

**Comment by gkdgo** [comment]
> Hello @gkdgo. What is your system theme set to in the MacOS settings?

hi @exaby73 , I have updated the code above  , and I add `themeMode: ThemeMode.light` and a `Text('Home')` for contrast 
btw, my system setting is light and I have test then in both light and dark system mode

**Comment by exaby73** [comment]
Using `Text.rich` instead of `RichText` produces the desired result. `RichText` is a low-level widget. In most situations, `Text.rich` should be used. This is working as expected. Therefore, I will close this issue. Thank you
