### ISSUE TITLE
Request to put Flutter widgets on top of a full-screen OEM widget (e.g. camera)

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#12362]
I have not found an issue specific to camera so opening one. Once we figure out how to render OEM views with Flutter controls (video, maps, etc), this will likely get resolved as well.

**Comment by sethladd** [comment]
Does https://pub.dartlang.org/packages/image_picker help? You can open the camera with that plugin.

**Comment by MichaelSowah** [comment]
@mehmetf there are no issues because anytime you bring it up you told by the team that they bring up the "render OEM views with Flutter controls (video, maps, etc),", we also understand as much as I would love that because all the apps my team is trying to port to flutter has camera feature as key...

@sethladd  yes and no because the apps we are working on needs custom camera UI and controls which the https://pub.dartlang.org/packages/image_picker dose not support....my team and I have been patiently waiting for some of these to complete some new apps as wells complete the porting of 3 other apps to Flutter...Looking forward to this

**Comment by chinmaygarde** [comment]
For reference, support for rendering video and external textures is being prototyped and reviewed in https://github.com/flutter/engine/pull/4159.

**Comment by sethladd** [comment]
Ah, I misread the title. I thought you wanted to launch a camera from a user tapping on a custom control. That we can do today with the plugin.

Would it be accurate to characterize your requirement this way: place custom widgets, drawn by Flutter, on top of a live camera view ?

**Comment by MichaelSowah** [comment]
@sethladd yes that's exactly what my team needs. We  want to be able to layer our own UI over the default UI. to able to control the look of the camera and even possible also for the image picker would be great. **_eg: my on snap icon, flash icon and my appBar posssible._**

**Comment by Hixie** [comment]
I can see multiple ways to address this:

* inlining a texture, the way we do video, where the video comes from the camera.
* inlining an OEM view
* dedicated support in the compositor

Currently this specific feature is not a high priority for the Flutter team, though it may get addressed by the video solution if it's possible to get a texture out of the camera APIs on the platform.

**Comment by sethladd** [comment]
@MichaelSowah thanks, I've updated the title of this issue. Let me know if we need to tweak it.

**Comment by roughike** [comment]
I actually got halfway there a week or so ago. 

On Android, I was able to put a native Android View under the FlutterView. The problem for me was that I wasn't able to get rid of the black background that FlutterView has. 

If the Scaffold body was possible to have a see-through background, the native View behind it (in this case, a camera view) could be seen.

**Comment by zoechi** [comment]
Is this issue still relevant?

**Comment by mehmetf** [comment]
It is and it will be largely solved by platform views AFAIK @amirh

**Comment by amirh** [comment]
@mehmetf I believe this can be done with AndroidView and UiKitView (which are currently in developers preview).

**Comment by markusaksli-nc** [comment]
Closing this since AndroidView and UiKitView are in stable and the [camera](https://pub.dev/packages/camera) package can be used to address the original issue.
