### ISSUE TITLE
Typo: gustbook instead of guestbook

### ISSUE THREAD

**Issue by daviderb** [flutter/flutter#123759]
Typo: instead of "guestbook," the text reads "You store each message of the chat as a document in a gustbook collection, which is a top-level collection."

**Comment by exaby73** [comment]
Hello @daviderb. Could you link to where this typo occurs?

**Comment by daviderb** [comment]
https://firebase.google.com/codelabs/firebase-get-to-know-flutter#5

Sorry for the omission.

**Comment by domesticmouse** [comment]
PTAL @nohe427

**Comment by nohe427** [comment]
Thanks, will look at in the morning

**Comment by nohe427** [comment]
This looks to have been resolved in this commit : https://github.com/flutter/codelabs/commit/65984dde9fdfa3fa1b7b9f353845d834532b3e52

We can close this bug. The internal state and external states have been synchronized since then

**Comment by daviderb** [comment]
+1

**Comment by domesticmouse** [comment]
Thanks @nohe427!
