### ISSUE TITLE
Chip has non-internationalized string "Delete $label"

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#12378]
The raw string [here in chip.dart](https://github.com/flutter/flutter/blob/528d28ba0353e70b7eab31feb68bdd4e0de1ca42/packages/flutter/lib/src/material/chip.dart#L138) needs to be internaltionalized.

**Comment by Hixie** [comment]
This default is problematic for many reasons, e.g. $label is a Widget and Widgets don't have user-friendly toStrings. See https://github.com/flutter/flutter/issues/11496.
