### ISSUE TITLE
Does Flutter support push notifications?

### ISSUE THREAD

**Issue by Ghostrick** [flutter/flutter#12374]
Can I use a flutter to realize android's push notification?

**Comment by roughike** [comment]
Yes, Flutter has a plugin for push notifications.

To receive push messages on both Android & iOS, you can use the [Firebase Messaging package](https://pub.dartlang.org/packages/firebase_messaging).

**Comment by Ghostrick** [comment]
@roughike Thank you!

**Comment by sgon00** [comment]
Firebase is not really a solution. It's blocked in many countries.

**Comment by matejthetree** [comment]
This should get more visibility

**Comment by yuehernkang** [comment]
Is there support for local notification?

**Comment by zoechi** [comment]
@yuehernkang perhaps https://pub.dartlang.org/packages/scheduled_notifications ?

**Comment by snotyak** [comment]
@zoechi That only supports Android.

**Comment by mitchhymel** [comment]
@yuehernkang If you just need basic local notifications (custom text and actions), you can try this plugin: https://github.com/mitchhymel/local_notifications . Should work on both Android and ios.

**Comment by collinjackson** [comment]
Thanks to everyone who offered suggestions. I don't think there's any action required here.

**Comment by csga5000** [comment]
So it's clear, firebase is google's long term plan for push notifiactions, they've entirely depricated GCM. "We will turn off most GCM services in April 2019"

https://developers.google.com/cloud-messaging/faq

**Comment by wedneyyuri** [comment]
@collinjackson Do you have plans to add support for push notification without Firebase? Would be good to see a solution for IOS without this dependency.

**Comment by PixelSnake** [comment]
Imho it is a terrible decision by the devs to limit push notifications to firebase. Notifications are something my app should be able to send to the user without some third party dependency and the need for an internet connection.

**Comment by csga5000** [comment]
See my comment @pixelsnake, it's not a third party dependency, at least for Apple, it's Google owned and the official way to do them, they are deprecating gcm (google cloud messaging).  At that point, iOS is easier to setup using firebase since you're already using them for good, so I can see why they did it this way.  If you really want to use Apple's push notifications directly then you can do so by coding that part in iOS and use platform channels if needed

**Comment by gdeglin** [comment]
I help work on OneSignal and we created a push SDK for Flutter https://github.com/OneSignal/OneSignal-Flutter-SDK

**Comment by lifenautjoe** [comment]
@gdeglin , Beware, I spent around 10 hours trying to get the the OneSignal Flutter SDK. iOS does not work nor there is currently a plan to make it work....

See https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/57

**Comment by Allan-Nava** [comment]
@lifenautjoe I have the same issue for iOS, any news?

**Comment by csga5000** [comment]
I'm not sure why I'm getting thumbs downed.  I am stating what I'm hearing from google.  Let me know if you think I'm wrong or why you have a problem with something.  But to maybe clarify one thing further

As linked above: https://developers.google.com/cloud-messaging/faq GCM is depricated so there won't be flutter support for this.

This references issue "push notifications" which seems to be what people are discussing - pushing notifications from a server to the phone.  If you're interested in local or scheduled notifications that's a different matter.  I find those to be usefull less often than ones that originate from a server, but there are cases for them and I haven't looked into what is required to implement those in a flutter application

**Comment by guopeng1994** [comment]
how about to overwrite the some functions in AppDelegate file, then when didRegisterForRemoteNotificationsWithDeviceToken finish with token, we could use channel to tell dart that we have got the token, then in dart, we could get token and submit it to the server.

i don't know if this way could be work. so does any one resolved  this problem??

**Comment by micimize** [comment]
The devs aren't willfully neglecting this feature - #13328 Is where "generic push notifications" is being tracked

**Comment by chornbe** [comment]
> I'm not sure why I'm getting thumbs downed. I am stating what I'm hearing from google. Let me know if you think I'm wrong or why you have a problem with something. But to maybe clarify one thing further
> 
> As linked above: https://developers.google.com/cloud-messaging/faq GCM is depricated so there won't be flutter support for this.
> 
> This references issue "push notifications" which seems to be what people are discussing - pushing notifications from a server to the phone. If you're interested in local or scheduled notifications that's a different matter. I find those to be usefull less often than ones that originate from a server, but there are cases for them and I haven't looked into what is required to implement those in a flutter application

What about silent push notifications? I was under the impression Firebase didn't support them. I'm also wicked unhappy to have to support multiple push engines on my servers. (sigh) :(

**Comment by codesundar** [comment]
I have shared my knowledge on integrating a firebase push notification with flutter 

Link: [Flutter push notification](https://codesundar.com/flutter-push-notification/)

**Comment by kaumudpa** [comment]
It still does not support Rich Notifications (Notifications with Image) on iOS, Anybody has workaround for this???

**Comment by kroikie** [comment]
@ghostrick

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/962. Any further collaboration will be done there.

**Comment by Ericahyana** [comment]
Is it possible to make push notifications with **Amazon SNS**?

**Comment by the-kid89** [comment]
> Is it possible to make push notifications with **Amazon SNS**?

FCM is the only way to send a push notification to an Android phone and APNS is the only way to send a push notification to iOS.
