### ISSUE TITLE
[Impeller] Figure out why we need the MSL compiler backend for Vulkan and how it's impacting GLES

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#123795]
I tried to refactor the compiler to use a CompilerGLSL for vulkan with vulikan_semantics set to true, but this somehow broke GLES and may have had impact on Vulkan. It's not clear right now why. We should figure that out. I made this change because I found that the compiler was sometimes complaining about the Metal Shading Language being too low for Vulkan targets. For now I'm working around this by setting the MSL version to 3.0.0 (which should be sufficiently high for all features), on the assumption that this doesn't matter for Vulkan anyway.

The real solution seems like having some kind of GLSL compiler with vulkan_semantics set to true, but there are too many other things to fix first at the moment.

**Comment by chinmaygarde** [comment]
Looking into this as part of the subpass rework.
