### ISSUE TITLE
Codelab class name typo: ChatMessageListItem instead of ChatMessage

### ISSUE THREAD

**Issue by lucamtudor** [flutter/flutter#12370]
On step 7 of the codelab (https://codelabs.developers.google.com/codelabs/flutter/index.html#6), the beginning of section **Add a SizeTransition widget** says:

> Modify the `ChatMessageListItem` object's build() ......

The class name is `ChatMessage`. (ChatMessageListItem is probably a leftover from an earlier version of the codelab)

**Comment by sethladd** [comment]
Thanks for the feedback!

cc @LarkAscending @collinjackson

**Comment by LarkAscending** [comment]
Good catch - it was indeed left over...

Updated!!
