### ISSUE TITLE
[Impeller] Investigate why malioc diff produces different results for Vulkan shaders on macOS vs Linux hosts

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#123705]

**Comment by zanderso** [comment]
I confirmed that this is due to the ifdef here:
https://github.com/flutter/engine/blob/7d190aa0e19f6cb7313ef9a73404578e5510598d/impeller/compiler/compiler.cc#L461

The enclosed line is included on a Linux host, but not on a macOS host.
