### ISSUE TITLE
[Impeller] Add tooling to make it easier to use vulkan validation layers on android

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#123788]
[Android instructions](https://developer.android.com/ndk/guides/graphics/validation-layer)

Right now, doing the straightforward thing of just copying the libs into `android/app/src/main/jniLibs` seems to break the `--local-engine` flag in the tool (at runtime libflutter.so can't be found).

We should see if we can make it easier to do this - this will be important because without the validation layers it's often really hard to figure out what's going wrong on Vulkan on a particular device. We should also have a flag to turn validation on in impeller, which right now requires a custom engine build on Android.

**Comment by chinmaygarde** [comment]
I've been following the instructions in https://github.com/flutter/engine/blob/main/impeller/docs/android_validation_layers.md for enabling validations.

**Comment by dnfield** [comment]
Ahh those are using `vklibs` instead of `jniLibs` which probably plays better with the tooling.

**Comment by chinmaygarde** [comment]
So, I just tried it your way (I didn't look at those docs first) and it worked for me that way too.

**Comment by dnfield** [comment]
It works but I get a runtime exception about not finding libflutter.so if I don't manually copy it over
