### ISSUE TITLE
[Impeller] Update impellerc to create fat shader blobs.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#123741]
When targeting Android, the shader blobs must contain SPIRV as well OpenGL ES shaders along with the necessary metadata. `impellerc` must be able to generate fat shader blobs similar to the `lipo` tool for dylibs. We never had this issue with iOS/macOS because there is only the Metal backend.

**Comment by chinmaygarde** [comment]
cc @jonahwilliams

**Comment by chinmaygarde** [comment]
On Android, we will end up using both Vulkan and OpenGL ES. So I do think this is necessary.

**Comment by chinmaygarde** [comment]
The increase in size of the compressed Flutter engine binary (that contains the prepackaged shaders) for all of Impeller is ~100K with one rendering backend. Having two backends in a binary (like Android) won't necessarily be 2x the size due to shared components but that is a reasonable (very) conservative estimate.

Uncompressed ([because that is easier to analyze](https://storage.googleapis.com/flutter_infra_release/flutter/ef5c349f04d84c5171c6b97bbed85c430d576834/android-arm64-release/sizes/index.html)), the shaders are 90 KB and backend 28 KB. So we expect to duplicate just these. But the shaders compress really well in the APK/IPA.

OTOH, just Skia GPU and SKSL (the runtime shader compiler) are 553 and 192.32 KB respectively. So just the online shader compiler is larger than the Impeller prepackaged shaders. Impellers shader compiler is significantly larger but all that is in ImpellerC and run at build time only. Impeller can't generate and compile shaders at runtime so there is less code to package.

During the transition we expect to have both Impeller and Skia in the binary since we want folks to be able to opt out in case of unexpected issues. But we are working towards a Skia-GPU (and its deps) less engine. Early experiments show a [binary size decrease of at least 7%](https://github.com/flutter/flutter/issues/126606#issuecomment-1546418113).

Either way, Impeller will be significantly smaller than the current backend once we complete the transition and remove the legacy backend.

References to screenshots in the analysis I linked earlier:
<img width="1424" alt="Screenshot 2023-05-18 at 10 13 43 AM" src="https://github.com/flutter/flutter/assets/44085/f743f298-4295-40c6-ae95-1c3e9e52fa87">
<img width="1441" alt="Screenshot 2023-05-18 at 10 14 44 AM" src="https://github.com/flutter/flutter/assets/44085/c85ef27f-ec16-454e-849f-738bab8eb447">
<img width="1440" alt="Screenshot 2023-05-18 at 10 17 55 AM" src="https://github.com/flutter/flutter/assets/44085/5473d526-3546-40ce-80e0-bbadfdc7b5e1">

**Comment by jonahwilliams** [comment]
Strawman design: When compiling for Android, we invoke impellerc twice - once for each backend type, GLES/VUlkan. Then a third time with each of the previous input files to merge them together into a combined format.

Might be easier than refactoring impellerc to create two different compilers.

**Comment by chinmaygarde** [comment]
Thats a good idea. I was thinking of something like blobcat but refactored to also create fat shader blobs instead of single backend shader libraries. But we don't ship blobcat as an artifact and we need that for runtime stages.

The argument parsing in impellerc is pretty rudimentary. But perhaps it can take multiple commands, `impellerc compiler <all existing args>` and then an `impellerc lipo <options>`.
