### ISSUE TITLE
Refactor: stop implementing `NativeWrapperClass`es

### ISSUE THREAD

**Issue by dcharkes** [flutter/flutter#123756]
Implementing subtypes of `NativeWrapperClass`es can lead to issues when passing such native wrapper to a native call, as it will try to unwrap a native field that doesn't exist (likely leading to a segfault).

The `NativeWrapperClass`es should be marked `base` so that none of their subtypes can be implemented:

* https://github.com/dart-lang/sdk/issues/51896

Flutter has classes which extend `NativeWrapperClass`es _and_ are mocked in tests, and Flutter has already opted in to 3.0, so adding the class modifiers to `dart:nativewrappers` is a breaking change for Flutter.

```
org-dartlang-sdk:///flutter/lib/ui/compositing.dart:13:7: Error: The type 'Scene' must be 'base', 'final' or 'sealed' because the supertype 'NativeFieldWrapperClass1' is 'base'.
org-dartlang-sdk:///flutter/lib/ui/painting.dart:2537:7: Error: The type 'EngineLayer' must be 'base', 'final' or 'sealed' because the supertype 'NativeFieldWrapperClass1' is 'base'.
org-dartlang-sdk:///flutter/lib/ui/compositing.dart:231:7: Error: The type 'SceneBuilder' must be 'base', 'final' or 'sealed' because the supertype 'NativeFieldWrapperClass1' is 'base'.
org-dartlang-sdk:///flutter/lib/ui/painting.dart:1941:7: Error: The type '_Image' must be 'base', 'final' or 'sealed' because the supertype 'NativeFieldWrapperClass1' is 'base'.
org-dartlang-sdk:///flutter/lib/ui/painting.dart:2071:7: Error: The type 'Codec' must be 'base', 'final' or 'sealed' because the supertype 'NativeFieldWrapperClass1' is 'base'.
org-dartlang-sdk:///flutter/lib/ui/painting.dart:2580:7: Error: The type 'Path' must be 'base', 'final' or 'sealed' because the supertype 'NativeFieldWrapperClass1' is 'base'.
org-dartlang-sdk:///flutter/lib/ui/painting.dart:3193:7: Error: The type '_PathMeasure' must be 'base', 'final' or 'sealed' because the supertype 'NativeFieldWrapperClass1' is 'base'.
org-dartlang-sdk:///flutter/lib/ui/painting.dart:3535:7: Error: The type '_ColorFilter' must be 'base', 'final' or 'sealed' because the supertype 'NativeFieldWrapperClass1' is 'base'.
org-dartlang-sdk:///flutter/lib/ui/painting.dart:3809:7: Error: The type '_ImageFilter' must be 'base', 'final' or 'sealed' because the supertype 'NativeFieldWrapperClass1' is 'base'.
org-dartlang-sdk:///flutter/lib/ui/painting.dart:3891:7: Error: The type 'Shader' must be 'base', 'final' or 'sealed' because the supertype 'NativeFieldWrapperClass1' is 'base'.
org-dartlang-sdk:///flutter/lib/ui/painting.dart:4322:7: Error: The type 'FragmentProgram' must be 'base', 'final' or 'sealed' because the supertype 'NativeFieldWrapperClass1' is 'base'.
org-dartlang-sdk:///flutter/lib/ui/painting.dart:4573:7: Error: The type 'Vertices' must be 'base', 'final' or 'sealed' because the supertype 'NativeFieldWrapperClass1' is 'base'.
org-dartlang-sdk:///flutter/lib/ui/painting.dart:4831:7: Error: The type 'Canvas' must be 'base', 'final' or 'sealed' because the supertype 'NativeFieldWrapperClass1' is 'base'.
org-dartlang-sdk:///flutter/lib/ui/painting.dart:5991:7: Error: The type 'Picture' must be 'base', 'final' or 'sealed' because the supertype 'NativeFieldWrapperClass1' is 'base'.
org-dartlang-sdk:///flutter/lib/ui/painting.dart:6111:7: Error: The type 'PictureRecorder' must be 'base', 'final' or 'sealed' because the supertype 'NativeFieldWrapperClass1' is 'base'.
org-dartlang-sdk:///flutter/lib/ui/painting.dart:6359:7: Error: The type 'ImmutableBuffer' must be 'base', 'final' or 'sealed' because the supertype 'NativeFieldWrapperClass1' is 'base'.
org-dartlang-sdk:///flutter/lib/ui/painting.dart:6461:7: Error: The type 'ImageDescriptor' must be 'base', 'final' or 'sealed' because the supertype 'NativeFieldWrapperClass1' is 'base'.
org-dartlang-sdk:///flutter/lib/ui/semantics.dart:680:16: Error: The type 'StringAttribute' must be 'base', 'final' or 'sealed' because the supertype 'NativeFieldWrapperClass1' is 'base'.
org-dartlang-sdk:///flutter/lib/ui/semantics.dart:771:7: Error: The type 'SemanticsUpdateBuilder' must be 'base', 'final' or 'sealed' because the supertype 'NativeFieldWrapperClass1' is 'base'.
org-dartlang-sdk:///flutter/lib/ui/semantics.dart:1052:7: Error: The type 'SemanticsUpdate' must be 'base', 'final' or 'sealed' because the supertype 'NativeFieldWrapperClass1' is 'base'.
org-dartlang-sdk:///flutter/lib/ui/text.dart:2681:7: Error: The type 'Paragraph' must be 'base', 'final' or 'sealed' because the supertype 'NativeFieldWrapperClass1' is 'base'.
org-dartlang-sdk:///flutter/lib/ui/text.dart:2958:7: Error: The type 'ParagraphBuilder' must be 'base', 'final' or 'sealed' because the supertype 'NativeFieldWrapperClass1' is 'base'.
```

[log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8785282172851374161/+/u/build_host_debug_flutter_build_archives:artifacts_flutter_build_archives:embedder_flutter_build_archives:flutter_patched_sdk_flutter_build_archives:dart_sdk_archive_flutter_web_sdk_flutter_tools_font-subset_flutter_shell_platform_linux:flutter_gtk/stdout)

A possible migration path would be to define APIs like `Path` as abstract classes that do not extend `NativeFieldWrapperClass1`.  Apps would then call a factory to construct an instance of the engine's implementation that can be passed to native. cc @jason-simmons @dnfield 

If possible, we should get these class modifiers into Dart 3.0. FYI @leafpetersen

**Comment by chinmaygarde** [comment]
From Triage: This is on the docket but not before the next branch (this Wednesday) cut as there are expected to be failures in the g3 roll.

**Comment by dcharkes** [comment]
The branch cut has happened a while back.

Following the chats on April 3, @jason-simmons, @dnfield is there someone on your side that can pick this up?

I have already migrated all subtypes in the Dart SDK, to test the Dart change locally in Flutter only requires adding the keywords as in https://dart-review.googlesource.com/c/sdk/+/291761.

Some context from the chat:

The pattern for replacing would be to have a hidden implementation class that extends `NativeFieldWrapperClass` and that implements a public API. The current class would then be the public API class that users can continue to implement. And the current class constructor would be a forwarding factory constructor to the private implementation class.

This requires explicit `as` with the private implementation class in the places where these objects are passed to native. These `as` checks would catch the issues that currently could lead to crashes because some user class has implemented a `NativeFieldWrapperClass`.

The pattern in the VM (for finalizers instead of native field wrappers) looks like this:

```dart
@patch
@pragma("vm:entry-point")
abstract class Finalizer<T> {
  @patch
  factory Finalizer(void Function(T) callback) = _FinalizerImpl<T>;
}

@pragma("vm:entry-point")
class _FinalizerImpl<T> extends FinalizerBase implements Finalizer<T> {
```

**Comment by dnfield** [comment]
The way this works for some classes already is that the class holds a private member, e.g. https://github.com/flutter/engine/blob/16454640846e3396e6495f2be4358b5f1eb21b4f/lib/ui/painting.dart#L1709-L1720

I can try to take a look at this.

**Comment by jason-simmons** [comment]
I had made some progress on redefining the engine's public `NativeFieldWrapperClass` APIs as abstract interfaces and moving the native API calls to private implementation classes.

I'm working towards finishing that today and will try to get a PR out soon.

**Comment by dcharkes** [comment]
@jason-simmons Did we complete this work? I just noticed https://github.com/dart-lang/sdk/issues/51896 is still open.

**Comment by jason-simmons** [comment]
https://github.com/flutter/engine/commit/65e2426f16e29d14ed75d9164cb27e91768cafb1 landed, which marked all engine classes that `extend NativeFieldWrapperClass1` as `base` classes.

I noticed that some new native classes were added in the experimental GPU package that are not marked as `base`.  I'll look into fixing that now.

**Comment by jason-simmons** [comment]
There are also some Fuchsia-specific native wrapper classes in the Flutter engine tree that are not `base` and will need to be updated.

**Comment by dcharkes** [comment]
> There are also some Fuchsia-specific native wrapper classes in the Flutter engine tree that are not `base` and will need to be updated.

I believe you are referring to these in the flutter engine repo:

shell/platform/fuchsia/dart-pkg/zircon/lib/src/handle_waiter.dart
shell/platform/fuchsia/dart-pkg/zircon/lib/src/handle_disposition.dart
shell/platform/fuchsia/dart-pkg/zircon/lib/src/system.dart
shell/platform/fuchsia/dart-pkg/zircon/lib/src/handle.dart

I don't see any obvious place where these are used as implements, so I'll just make PR to mark them as base and see if it is green.

**Comment by jason-simmons** [comment]
I landed a PR for the Fuchsia classes already (https://github.com/flutter/engine/commit/dc6ec258859434a9aa22091f9c243781f68d7c51)

**Comment by dcharkes** [comment]
I believe we have migrated all in Flutter now, thanks @jason-simmons!

I'll close this issue and proceed with doing the breaking change upstream.
