### ISSUE TITLE
[Impeller] Tracking: Monitor Metal shader compiler flakes on CI.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#123733]
Right now, we retry on compiler flakes that seem to plague CI jobs on certain builders. We haven't been able to reproduce these locally or on iOS devices.

Followup after the tests were enabled with retries in https://github.com/flutter/flutter/issues/117122.

**Comment by jonahwilliams** [comment]
When we hit this issue its almost always a flake with a particular bot that needs to be reimaged. Given that this is under control, can we close this issue?

**Comment by chinmaygarde** [comment]
sgtm
