### ISSUE TITLE
[Windows] The cursor can not be moved by left/right keys when using Pinyin input method

### ISSUE THREAD

**Issue by jzhgithub18** [flutter/flutter#123749]
There was a problem enabling Chinese input method. When using Pinyin input method, pressing the left and right keys could not move the cursor.
I want is just like this, but the cursor con't move left.
![image](https://user-images.githubusercontent.com/112080579/228735485-532ce326-e452-4622-895a-4a5d6bf5b679.png)

flutter sdk version: 3.7.7

**Comment by exaby73** [comment]
Hello @jzhgithub18. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`
- The output of `flutter run -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by jzhgithub18** [comment]
<details>

<summary>flutter doctor -v</summary>
[√] Flutter (Channel stable, 3.7.7, on Microsoft Windows [版本 10.0.19043.2251], locale zh-CN)
    • Flutter version 3.7.7 on channel stable at C:\work\flutter\flutter_windows\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (3 weeks ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\jiangzhihao01\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME =
      C:\Users\jiangzhihao01\AppData\Local\Android\Sdk;C:\Users\jiangzhihao01\AppData\Local\Android\Sdk\platform-tools
    • Java binary at: C:\ProgramData\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33516.290
    • Windows 10 SDK version 10.0.20348.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.76.2)
    • VS Code at C:\Users\jiangzhihao01\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.50.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.19043.2251]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 111.0.5563.112
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 111.0.1661.54

[√] HTTP Host Availability
    • All required HTTP hosts are available
</details>

**Comment by jzhgithub18** [comment]
there are chinese characters in the input

**Comment by exaby73** [comment]
Could you provide the exact characters you have inputted? I am not a Chinese speaker so I am not able to do it myself

**Comment by jzhgithub18** [comment]
any characters, is not the chararcter problem, when i want input a Chinese just like "程序员"，i need input pinyin "chengxuyuan" 
![image](https://user-images.githubusercontent.com/112080579/229130263-a5ff0d3f-cb0f-4bc2-96f9-e77c8fdd2ccf.png)
notice the picture，in the end of “chengxuyuan” has a red cursor. normal user can move the cursor by left or right keys of the keyboard.
![image](https://user-images.githubusercontent.com/112080579/229130988-2896691c-30c0-4d05-b2c4-3e021324fa7e.png)
and i can delete letter arround cursor ,and can add other letter.
![Uploading image.png…]()

but in flutter i can't do it.

**Comment by exaby73** [comment]
Are you able reproduce this issue with the master channel of Flutter as well?

**Comment by jzhgithub18** [comment]
able reproduce this issue with the master channel of Flutter,
Channel master, 3.9.0-20.0.pre.55, 
<details>

<summary>flutter doctor -v </summary>

Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[√] Flutter (Channel master, 3.9.0-20.0.pre.55, on Microsoft Windows [版本 10.0.19043.2251], locale zh-CN)
    • Flutter version 3.9.0-20.0.pre.55 on channel master at C:\work\flutter\flutter_windows\flutter      
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d940f60b46 (39 minutes ago), 2023-03-31 07:36:05 -0700
    • Engine revision 013e936fee
    • Dart version 3.0.0 (build 3.0.0-387.0.dev)
    • DevTools version 2.22.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\jiangzhihao01\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME =
      C:\Users\jiangzhihao01\AppData\Local\Android\Sdk;C:\Users\jiangzhihao01\AppData\Local\Android\Sdk\platform      -tools
    • Java binary at: C:\ProgramData\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33516.290
    • Windows 10 SDK version 10.0.20348.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).  

[√] VS Code (version 1.77.0)
    • VS Code at C:\Users\jiangzhihao01\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.50.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.19043.2251]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 111.0.5563.147
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 111.0.1661.54

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
</details>

**Comment by exaby73** [comment]
This issue looks similar to https://github.com/flutter/flutter/issues/79933. Could you try with sogou input and see if you are hitting the same issue?

**Comment by jzhgithub18** [comment]
This issue is not the same issue, https://github.com/flutter/flutter/issues/79933 is the IME position, my issue is the cursor can  't move by user. souguo is ok, because using sougou the pinyin letters don't display in flutter TextField.

**Comment by huycozy** [comment]
I can reproduce this issue on the latest stable and master channels.

### Issue summary
- Using Pinyin input method to enter Chinese text, then the cursor can not move between texts
- The issue does not happen on macOS or Linux (Ubuntu) but on Windows
- Reproducible with a simple `TextField`

| Windows | macOS | Linux | Web |
| --------------- | --------------- |  --------------- |  --------------- | 
❌ | ✅ |  ✅ |   ✅ | 

✅: No Issue ❌: Issue reproduced

### Demo (Windows)
https://user-images.githubusercontent.com/104349824/229695151-0ec5b963-69aa-4c2e-b36b-5b95d237f3d6.mp4

<details>
<summary>flutter doctor -v (stable & master)</summary>

```bash
[√] Flutter (Channel stable, 3.7.9, on Microsoft Windows [Version 10.0.19045.2728], locale en-US)
    • Flutter version 3.7.9 on channel stable at C:\WIP\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 62bd79521d (4 days ago), 2023-03-30 10:59:36 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\AndroidSDK
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = C:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio Electric Eel 2022.1.1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.4)
    • Visual Studio at D:\DOWNLOADWORK\VS2022
    • Visual Studio Community 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio Electric Eel 2022.1.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.77.0)
    • VS Code at C:\Users\ADMIN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.60.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2728]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 111.0.5563.147
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 111.0.1661.54

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.9.0-20.0.pre.111, on Microsoft Windows [Version 10.0.19045.2728], locale en-US)
    • Flutter version 3.9.0-20.0.pre.111 on channel master at C:\WIP\flutter_master
    ! Warning: `flutter` on your path resolves to C:\WIP\flutter\bin\flutter, which is not inside your current Flutter
      SDK checkout at C:\WIP\flutter_master. Consider adding C:\WIP\flutter_master\bin to the front of your path.
    ! Warning: `dart` on your path resolves to C:\WIP\flutter\bin\dart, which is not inside your current Flutter SDK
      checkout at C:\WIP\flutter_master. Consider adding C:\WIP\flutter_master\bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f076b7bac3 (22 minutes ago), 2023-04-04 00:58:34 -0400
    • Engine revision b5d2c056a0
    • Dart version 3.0.0 (build 3.0.0-403.0.dev)
    • DevTools version 2.22.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\AndroidSDK
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = C:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio Electric Eel 2022.1.1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.4)
    • Visual Studio at D:\DOWNLOADWORK\VS2022
    • Visual Studio Community 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio Electric Eel 2022.1.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.77.0)
    • VS Code at C:\Users\ADMIN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.60.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2728]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 111.0.5563.147
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 111.0.1661.54

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by gspencergoog** [comment]
This used to work.  Marking as a regression. (Desktop Triage)

**Comment by jzhgithub18** [comment]
@gspencergoog @huycozy 
when i input the Chinese language.
in windows and macos platform
final myConnection = TextInput.attach(myInputClient, myConfig);

It always appears in the upper left corner of the window when I am using it.
image
![image](https://user-images.githubusercontent.com/112080579/231992817-173568d3-592d-40a3-8128-afffa1e101fe.png)

I expectation the Candidate Window can be normal in the below of Pinyin.
image
![image](https://user-images.githubusercontent.com/112080579/231992869-a6b56709-28f8-4680-af41-b72885f5ab53.png)

and i know the textfiled is ok, and there have a way to set the Candidate Window postion.

my flutter version is Channel stable, 3.7.7, on Microsoft Windows

**Comment by jzhgithub18** [comment]
When will this issue be fixed.

**Comment by gnprice** [comment]
For when an issue might be fixed, see: https://github.com/flutter/flutter/wiki/Issue-hygiene#when-will-my-bug-be-fixed

**Comment by yaakovschectman** [comment]
Interesting and probably important detail to note:  
When typing in-progress text with the IME and attempting to navigate with the arrow keys, then start typing, the new text appears where the cursor _should_ be, not where it _appears_ to be. For example, with the IME enabled, if you type `abc`, then hit the left arrow once, then type `d`, the resulting text is `abdc`, not `abcd`, even though the cursor is _rendered_ at the end `abdc|`. I believe this may be a bug only in rendering.

**Comment by gnprice** [comment]
> the new text appears where the cursor _should_ be, not where it _appears_ to be. […] I believe this may be a bug only in rendering.

Interesting, yeah.

That clue reminds me of a couple of previous bugs we've had that were of the same kind, where the caret is rendered in the wrong place (and so it gets reported, understandably, as "the cursor doesn't move"), but typing more text shows that the movement/navigation works fine and the bug is purely in rendering. Specifically:
* #122477
* #50563
  * (which had some nonobvious duplicates: #98516 and #118403)
* both of which were fixed in: #122480

Don't know how related the actual cause of this bug might be to those, but mentioning them in case they turn out to be helpful context.

**Comment by yaakovschectman** [comment]
I found a further discovery on this matter. When sending the update to the framework for the cursor position, the length of the entire composition is added to the cursor position, meaning the cursor position is always at the end of the composition at minimum. I have yet to test if this is always true or only when not using deltas. The individual who contributed this change is currently on several-month-long leave, so it may be difficult to confirm what the intention was.

**Comment by yaakovschectman** [comment]
We just merged a solution to this. Please check either with a ToT local engine build or master branch of Flutter once engine#45667 change is rolled that the issue does not persist.

**Comment by yaakovschectman** [comment]
As we merged a fix, and have not heard anything further, I am going to close this.
