### ISSUE TITLE
Build for iOS device failed ios_bundle_flutter_assets failed: Exception: Failed to codesign???????

### ISSUE THREAD

**Issue by UnivexDont** [flutter/flutter#123767]
Target debug_ios_bundle_flutter_assets failed: Exception: Failed to codesign /Users/XXXXX/Library/Developer/Xcode/DerivedData/Runner-aqeizhxvgmpxwwhiezkvbxsypfrm/Build/Products/Debug-iphoneos/App.framework/App with identity XXXXXXXXXXXXXX

When I compiled and ran the iOS Device, flutter_assets failed. When I removed assets from pubspec.yaml and compiled again, it passed. I am using Xcode 14.3.

`Xcode 14.3`
`Flutter 3.7.5`
`MACOS 13.3`

**Comment by exaby73** [comment]
Hello @UnivexDont. Are you running the app or building an IPA? Could you share the command you're trying to run? Also, does this happen with any type of asset?

**Comment by UnivexDont** [comment]
> > Hello @UnivexDont. Are you running the app or building an IPA? Could you share the command you're trying to run? Also, does this happen with any type of asset?
> 
> After executing xattr -cr in the Assets directory which contains both .png and .tflite files, the compilation issue has been resolved. However, when I try to run the app using xcode run, I encountered another issue. The problem is as follows. ![1680184258257](https://user-images.githubusercontent.com/29479617/228858133-fd599209-e5f9-4bf3-a551-938f9e1b0f17.jpg)

It works fine with Android.
