### ISSUE TITLE
LUCI not updating github check status

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#123787]
On https://github.com/flutter/engine/pull/40756, the github check has been pending for >1 day, but the LUCI check is showing that it is successful. This is blocking the Skia autoroller.

**Comment by keyonghan** [comment]
For reference, `Linux Android AOT Engine` is stuck in `In progress` in checkrun: https://github.com/flutter/engine/pull/40756/checks?check_run_id=12367269510
<img width="1046" alt="Screenshot 2023-03-30 at 9 35 22 AM" src="https://user-images.githubusercontent.com/54558023/228905062-98fc3221-1043-4323-b787-e2e1d1ea500e.png">
but the build has finished: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Android%20AOT%20Engine/50763/overview

Sounds an issue when updating checkrun status to GitHub from cocoon backend.

To unblock, @drewroengoogle could you help trigger only the hanging task via: http://go/flutter-luci-playbook#manually-trigger-try-pre-submit-builds? We can take a look at the backend log to see why the status failed to get updated.

**Comment by drewroengoogle** [comment]
The try build has been restarted

**Comment by keyonghan** [comment]
```
> ERROR 2023-03-29T14:11:27.769Z GitHub Error: (500) #0 GitHub.handleStatusCode (package:github/src/common/github.dart:489:9) #1 GitHub.request (package:github/src/common/github.dart:426:7) <asynchronous suspension> #2 GitHub.requestJson (package:github/src/common/github.dart:324:22) <asynchronous suspension> #3 GithubChecksUtil.updateCheckRun.<anonymous closure> (package:cocoon_service/src/foundation/github_checks_util.dart:88:9) <asynchronous suspension> #4 RetryOptions.retry (package:retry/retry.dart:131:16) <asynchronous suspension> #5 GithubChecksService.updateCheckStatus (package:cocoon_service/src/service/github_checks_service.dart:105:5) <asynchronous suspension> #6 PresubmitLuciSubscription.post (package:cocoon_service/src/request_handlers/presubmit_luci_subscription.dart:66:7) <asynchronous suspension> #7 RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:53:24) <asynchronous suspension> #8 SubscriptionHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/subscription_handler.dart:139:19) <asynchronous suspension> #9 SubscriptionHandler.service (package:cocoon_service/src/request_handling/subscription_handler.dart:138:5) <asynchronous suspension> #10 main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:288:11) <asynchronous suspension>
```

We may want to check if we catch the error for retry. The status update happens in `presubmit_luci_subscription` api.

**Comment by drewroengoogle** [comment]
> I am wondering if we ever touched the retry logic, due to missing the error in the `retryIf`. A log should help validate that. Yeah, I agree 500 doesn't tell us much. It may help to expand the error from upstream.

It definitely retried 3 times. In the logs right before the error, it obtained the Github token 3 times, once per attempt.

```
> INFO 2023-03-29T17:11:31.057Z neat_cache: reading cache entry for "configgithubToken-flutter/engine"
> INFO 2023-03-29T17:11:35.613Z neat_cache: reading cache entry for "configgithubToken-flutter/engine"
> INFO 2023-03-29T17:11:43.300Z neat_cache: reading cache entry for "configgithubToken-flutter/engine"
```

Given the error coming from Github is a 500, implying an issue on Github's side, what do you recommend? Do you think there be some logic to attempt to update the checkrun later?

**Comment by keyonghan** [comment]
There is limited thing we can do when GitHub error happens. We can try marking the message as no processed to have pub/sub re-process the message. But it may cause repetitive processes of the same message multiple times. Let's monitor a bit to see if this is a transient issue.

**Comment by drewroengoogle** [comment]
Sounds good. For now I will lower the priority since the autoroller is unblocked.

**Comment by keyonghan** [comment]
Another thing we try is change the constant 2s delay with a backoff factor to extend the time between retries.

**Comment by keyonghan** [comment]
Closing as seems transient GitHub error. Please reopen if you see this again.
