### ISSUE TITLE
Temple OS Support

### ISSUE THREAD

**Issue by PhantomLel** [flutter/flutter#123800]
I recently looked into Flutter as an option for my multi-billion dollar idea. However, I noticed a severe lack of support for the Temple OS platform which comprises most of my user base. Is support for the most superior operating system in the roadmap? If not, I sincerely hope you will consider this revolutionary proposition.

**Comment by iapicca** [comment]
troll of the day

**Comment by Hixie** [comment]
@PhantomLel We don't currently support TempleOS, but as with any potential target platform, we would be open to PRs that added support if they came with a commitment to run CI. There are also some practical limitations to supporting TempleOS which would have to be overcome (like the lack of a networking stack, which would interfere with our distribution mechanism which is based on git), though targeting variants of TempleOS such as Shrine might address those issues.

I'm going to close this issues for now but if you have the resources to commit to maintaining a port please don't hesitate to reach out to me on our Discord and we can arrange something.
