### ISSUE TITLE
Request to rename Firestore's project directory

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#12388]
We've been asked to rename our directory for the Cloud Firestore project.

New directory name: cloud_firestore

(was: firebase_firestore)

Thanks!

**Comment by sethladd** [comment]
cc @collinjackson @kroikie

**Comment by kroikie** [comment]
@sethladd

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/961. Any further collaboration will be done there.
