### ISSUE TITLE
[pigeon] Document how to return FlutterError in Swift

### ISSUE THREAD

**Issue by theodelrieu** [flutter/flutter#123851]
Hello,

I'm writing the Swift part of our application, and I need to return additional error details to the Dart part.
To that end, I wanted to use `FlutterError`, which has a `details` field.

However, the following code fails:

```swift
  completion(Result.failure(FlutterError(code: "someCode", message: "msg", details: 42)))
```

and I get this error:

>Swift Compiler Error (Xcode): 'FlutterError' is not convertible to 'any Error'

I dug up a bit, and came across the `wrapError` function in the generated Swift code:

```swift
private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}
``` 

So it seems that the only way to get additional info passed to Dart is to return a `FlutterError`, which doesn't seem to implement the `Error` protocol.

I can workaround that for the time being by returning an ad-hoc structure. From what I understand, the Objective-C generator supports FlutterError since a few versions, was there an oversight on the Swift one?

**Comment by stuartmorgan** [comment]
You just need to add [this line](https://github.com/flutter/packages/blob/7781aee45b36321c894734a42898d0921027f620/packages/pigeon/platform_tests/test_plugin/ios/Classes/TestPlugin.swift#L8) to your code to make it usable in that context.

We need to update the error handling section in the readme to explain this.

**Comment by tarrinneal** [comment]
There is an upcoming documentation refresh coming for pigeon, I'll make sure this is included in that.

**Comment by stuartmorgan** [comment]
This is tracking the documentation change.

**Comment by stuartmorgan** [comment]
It occurs to me that it may not work to have multiple plugins used by the same app declare that same extension. We need to validate that, and if it doesn't work add a custom error type to the Swift generator instead.

**Comment by stuartmorgan** [comment]
> It occurs to me that it may not work to have multiple plugins used by the same app declare that same extension. We need to validate that, and if it doesn't work add a custom error type to the Swift generator instead.

I validated that it works fine; we're safe to use this in our plugins.

@tarrinneal Your docs PR listed it as partially addressing this; was there more you wanted to document, or is the note that's there now enough?

**Comment by tarrinneal** [comment]
I originally marked it as complete, but we decided to hold off until it was validated.
