### ISSUE TITLE
'version `GLIBC_2.34' not found' error when running a Flutter demo release version on Debian.

### ISSUE THREAD

**Issue by AoEiuV020** [flutter/flutter#123853]
## Steps to Reproduce

The highest version of glibc on Debian is only 2.31, so I believe Flutter should not rely on a higher version like 2.34.

1. Here's the GitHub link to my demo project: https://github.com/AoEiuV020/FlutterDemo
2. The demo was created using Flutter version 3.7.8. use command ‘flutter create demo'
3. I used GitHub Actions (Ubuntu 22.04) to build this demo, The resulting build can be found here: https://github.com/AoEiuV020/FlutterDemo/releases/tag/3.7.8
4. I tried running this Linux version app on a Debian 11 system, 
5. I received the error message 'version `GLIBC_2.34' not found'.

What seems strange to me is that the app I built locally on Ubuntu 22.04 with Flutter 3.7.8 runs fine on Debian, but the app built using GitHub Actions seems to have this problem.

<details>
<summary>Code sample</summary>

```shell
flutter create demo
```

</details>

<details>
  <summary>Logs</summary>

```
./FlutterDemo-3.7.8-linux/demo: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./FlutterDemo-3.7.8-linux/demo)
```

```
Analyzing flutter...                                                    
No issues found! (ran in 1.8s)
```

```
[✓] Flutter (Channel stable, 3.7.8, on Debian GNU/Linux 11 (bullseye) 5.10.0-21-amd64, locale en_US.UTF-8)
    • Flutter version 3.7.8 on channel stable at /home/aoeiuv/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 90c64ed42b (10 days ago), 2023-03-21 11:27:08 -0500
    • Engine revision 9aa7816315
    • Dart version 2.19.5
    • DevTools version 2.20.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Debian GNU/Linux 11 (bullseye) 5.10.0-21-amd64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.

```

</details>

![image](https://user-images.githubusercontent.com/11682198/229089658-8d69d5f2-ea75-4cf8-bbfd-177d81c59782.png)

![image](https://user-images.githubusercontent.com/11682198/229090014-b48103e3-8be5-4dcd-acb5-2b9cd973bc2c.png)

![image](https://user-images.githubusercontent.com/11682198/229092603-4e18be20-ebba-4aba-8f6d-2295a4b70b22.png)

**Comment by stuartmorgan** [comment]
> Flutter should not rely on a higher version like 2.34.

This is not an issue with Flutter, but with how you are building your application. As you pointed out:

> What seems strange to me is that the app I built locally on Ubuntu 22.04 with Flutter 3.7.8 runs fine on Debian, but the app built using GitHub Actions seems to have this problem.

If the issue were with Flutter, it wouldn't work when you built your app differently.

See https://stackoverflow.com/questions/2856438/how-can-i-link-to-a-specific-glibc-version for discussion of the general issue.

Closing as this is not a Flutter issue.
