### ISSUE TITLE
[go_router] uni_links seems to conflict with the default router behavior for deeplinking

### ISSUE THREAD

**Issue by droidpl** [flutter/flutter#123813]
## Steps to Reproduce

1. Use the default code from the deeplink sample: https://docs.flutter.dev/cookbook/navigation/set-up-universal-links
2. Implement the configuration for the app and test the link https://yourdomain.com/details
3. Check it works with the app in foreground and with it completely closed
4. Now add the latest dependency of uni_links (just the dependency, no changes in the code)
5. Check the deeplink stops working

Tested this behavior on iOS, not sure if Android does the same

**Expected results:** 
We should be able to capture the behavior of the deeplink at least from both libraries or a message indicating that there is some incompatibility (if it's really possible).

**Actual results:**
Nor `go_router` nor `uni_links` seem to behave properly in this case. 

I observed `uni_links` always receives null now (this implementation worked fine with navigator). I also observed that if I pass a hash fragment in the URL it seems to be correctly captured by unilinks (https://mydomain.com/#/details)

In none of the situations `go_router` is handling the routing properly

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
 import 'package:go_router/go_router.dart';

 void main() => runApp(MaterialApp.router(routerConfig: router));

 /// This handles '/' and '/details'.
 final router = GoRouter(
   routes: [
     GoRoute(
       path: '/',
       builder: (_, __) => Scaffold(
         appBar: AppBar(title: const Text('Home Screen')),
       ),
       routes: [
         GoRoute(
           path: 'details',
           builder: (_, __) => Scaffold(
             appBar: AppBar(title: const Text('Details Screen')),
           ),
         ),
       ],
     ),
   ],
 );
```

</details>

#### Flutter doctor

```
» flutter analyze
• No issues found!
```

```
» flutter doctor -v
[✓] Flutter (Channel stable, 3.7.8, on macOS 13.1 22C65 darwin-x64, locale en-ES)
    • Flutter version 3.7.8 on channel stable at /Applications/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 90c64ed42b (9 days ago), 2023-03-21 11:27:08 -0500
    • Engine revision 9aa7816315
    • Dart version 2.19.5
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /usr/local/share/android-sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME =
      /usr/local/share/android-sdk:/usr/local/share/android-sdk/platform-tools:/usr/local/share/android-sdk:/usr/local/opt/openssl@3/bin:/usr/local/opt/icu4c/bin:/Users/javierdepedrolopez/.nvm/versions/
      node/v17.0.1/bin:/Users/javierdepedrolopez/bin:/usr/local/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/usr/local/bin:/Applications/Visual
      Studio Code.app/Contents/Resources/app/bin:/Applications/flutter/bin
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 71.3.6
    • Dart plugin version 223.8214.16

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.3)
    • IntelliJ at /Users/javierdepedrolopez/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 72.1.4
    • Dart plugin version 223.8888

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.3)
    • IntelliJ at /Users/javierdepedrolopez/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/223.8836.41/IntelliJ IDEA.app
    • Flutter plugin version 71.3.6
    • Dart plugin version 223.8214.16

[✓] VS Code (version 1.76.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.1 22C65 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 111.0.5563.146

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @droidpl, from the documentation, if you opt-in to use the flutter based deeplink handling, the plugin stops working. See https://docs.flutter.dev/development/ui/navigation/deep-linking#migrating-from-plugin-based-deep-linking so it would appear that they are incompatible. 

Are you opt-ing in for the flutter based deeplinking?

**Comment by danagbemava-nc** [comment]
> With or without the flag: links on uni_links that don't have a hash fragment stop working. They come as null

This will have to be reported on the `uni_links` repo since they have their native code for handling the routes.

>  With the flag set: if you import the library, the behavior on go_router stops working. No matter if the flag is set.

Did this scenario work when you used `Navigator`?

**Comment by droidpl** [comment]
Yes that worked before

**Comment by danagbemava-nc** [comment]
> I have the feeling that those libraries may be overriding something on the native level that go router uses to make it work

Hi @droidpl, yes, according to the documentation the plugins are incompatible with the flutter opt-in deep-linking. So you'd have to go with one or the other. 

If you are going with the plugin-based deep-linking, you can use the plugin to parse the route and then pass the location to go_router to handle the navigation

**Comment by droidpl** [comment]
Yes that is what I was trying, not using the flag and using only uni_links but that was not working with non fragment urls without the flag.

I've ended up removing uni_links and firebase deeplinks to let go_router handle everything bh it's own and that seems to work fine.

I think we have two next actions here:
- Understand why go_router without the flag makes uni_link to stop working.
- It would be nice if we could include some messaging that talks about the incompatibility while executing the app. I found it hard to debug (even if its stated in the docs) and not as transparent to understand what was going on

**Comment by danagbemava-nc** [comment]
I'm not sure we can do anything at runtime to show that the plugins are incompatible with the opt-in deep-linking handling. 

The uni_links plugin also hasn't been updated for about 2 years now, there's a chance there could be a bug in the plugin itself. 

The only thing I think we can do is add more documentation as to how the plugins & the opt-in might cancel each other out, but I'm not sure if that has been investigated enough

**Comment by droidpl** [comment]
Worth to mention here then that in the case of Firebase deeplinks it also happens. If you add the library in your project it also cancels the behavior of `GoRouter` just by having it in your project and that one seems more maintained. Yeah maybe just a mention about what is the behavior of a library that interrupts should be enough so people can look for it

**Comment by danagbemava-nc** [comment]
Hi @droidpl, I seem to have lost track of what to address here, can you provide a summary of the issue at hand and also update the issue title to reflect the same? 

Thank you

**Comment by droidpl** [comment]
@danagbemava-nc apologies for the delay replying, I missed this notification.

The requests here would be either:
- To fix the fact that just adding 3P libraries into your project that do something with deeplinks break the behaviour of go_router
- If we don't want or can't fix that, at least make that very clear providing some details of why that is the case so people don't spend a lot of time debugging this issue


Last thing as a bonus, if you think it makes sense, investigate why go_router even with the new deeplink flag unset changes the behavior of existing libraries as described above with unilinks

Hope this brings some extra clarity 😊

**Comment by danagbemava-nc** [comment]
Hi @droidpl, thanks for the clarification. Just to confirm, this is only an issue when you use go_router and not navigator, correct?

**Comment by droidpl** [comment]
Correct only with go_router
