### ISSUE TITLE
[animations] Using OpenContainer from Animations package in Flutter causes swipe gestures to return multiple screens back

### ISSUE THREAD

**Issue by madamoniem** [flutter/flutter#123870]
I am using the ```animations``` package in Flutter, and I have run into an issue https://pub.dev/packages/animations.

Here is the code that I use when trying to navigate to another screen in my flutter app, while adding a transition.

```
OpenContainer(
closedElevation: 0,
openElevation: 0,
closedColor:
    Colors.transparent,
transitionDuration:
    const Duration(
        milliseconds: 500),
transitionType:
    ContainerTransitionType
        .fadeThrough,
openBuilder:
    (context, action) {
  return PowPage(
    data: data,
    document: document,
  );
},
closedBuilder:
    (context, action) {
  return OrganizationCard(
    data: data,
    document: document,
    lengthI: lengthI,
  );
},
),
```

The page this leads to, also uses the same code several times. Here is an example of where it's used after being navigated to using ```OpenContainer``` previously;

```
OpenContainer(
  closedElevation: 0,
  closedColor: Colors.transparent,
  transitionDuration: const Duration(milliseconds: 500),
  transitionType: ContainerTransitionType.fadeThrough,
  openBuilder: (context, action) {
    return const PowForum();
  },
  closedBuilder: (context, action) {
    return Icon(
      Icons.forum,
      size: 30,
      color: CustomColors.cardColor,
    );
  },
),
```

When a user taps on the first widget, uses ```OpenContainer``` to navigate to ```PowPage```, then clicks on another ```OpenContainer``` widget to navigate to another page, and then tries to use Android gestures to navigate to different pages, it goes back to the first ever page that didn't use ```OpenContainer```. So when a user swipes from left to right on their device to go back without using the arrows, it just sends them several screens back. 

This is even more odd since using ```Navigator.pop()``` works, and leads the user to the correct previous page, but when using a swipe gesture to go back to the previous page, it "pops" all pages that used ```OpenContainer```.

Thank you.

**Comment by huycozy** [comment]
Hi @madamoniem 
Can you please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this? 

Also, it would be appreciated if you could provide a video of the issue so that it's easier for us to replicate and verify this issue.

In addition, please provide the `animations` version you are using along with the output of `flutter doctor -v` as well. Thanks!
