### ISSUE TITLE
My project can run with release scheme(iOS device not simulator), but when I archived I get Failed, my Disbution cert My distribution certificate has been configured.

### ISSUE THREAD

**Issue by UnivexDont** [flutter/flutter#123857]
Archive logs:
```
`17 warnings generated.
    1 warning generated.
    mkdir -p
    /Users/thao/Library/Developer/Xcode/DerivedData/Runner-aqeizhxvgmpxwwhiezkvbxsypfrm/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPat
    h/Release-iphoneos/Runner.app/Frameworks
    Symlinked...
    rsync --delete -av --filter P .*.?????? --links --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "-
    PrivateHeaders" --filter "- Modules" "../../../IntermediateBuildFilesPath/UninstalledProducts/iphoneos/package_info_plus.framework"
    "/Users/thao/Library/Developer/Xcode/DerivedData/Runner-aqeizhxvgmpxwwhiezkvbxsypfrm/Build/Intermediates.noindex/ArchiveIntermediates/Runner/InstallationBui
    ldProductsLocation/Applications/Runner.app/Frameworks"
    building file list ... rsync: link_stat
    "/Users/thao/Private/QuantAI/App/mosoexp/ios/../../../IntermediateBuildFilesPath/UninstalledProducts/iphoneos/package_info_plus.framework" failed: No such
    file or directory (2)
    done

    sent 29 bytes  received 20 bytes  98.00 bytes/sec
    total size is 0  speedup is 0.00
    rsync error: some files could not be transferred (code 23) at
    /AppleInternal/Library/BuildRoots/97f6331a-ba75-11ed-a4bc-863efbbaf80d/Library/Caches/com.apple.xbs/Sources/rsync/rsync/main.c(996) [sender=2.6.9]
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Building targets in dependency order
    note: Run script build phase 'Run Script' will be run during every build because the option to run the script phase "Based on dependency analysis" is
    unchecked. (in target 'Runner' from project 'Runner')
    note: Run script build phase 'Thin Binary' will be run during every build because the option to run the script phase "Based on dependency analysis" is
    unchecked. (in target 'Runner' from project 'Runner')

    Result bundle written to path:
    	/var/folders/3r/ptdgzwkd4y72zwkryhpz5h7c0000gn/T/flutter_tools.FNz0IT/flutter_ios_build_temp_dirwVCxm7/temporary_xcresult_bundle`

```

My system Enviroment:
1.MacOS 13.3.(m1Max)
2.Xcode 14.3.
3.Flutter && Dart :
Flutter 3.7.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision c07f788888 (5 weeks ago) • 2023-02-22 17:52:33 -0600
Engine • revision 0f359063c4
Tools • Dart 2.19.2 • DevTools 2.20.1
4.cocoapods:1.11.3

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/29479617/229116296-ce3a38ec-696f-41ef-b4d0-a198c3ae947f.png">
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/29479617/229116365-eccac46a-68ad-4e11-97a0-d1f778da0cd7.png">
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/29479617/229116485-12b9d86a-e480-42d8-8576-86e1f613d520.png">
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/29479617/229116581-ba148c24-23b7-4626-890d-f352677d8069.png">

**Comment by virtualmarc** [comment]
Looks like the same problem I have in #123852 
Theres a workaround in my ticket, that can fix the issues, as long as the script is not regenerated.

**Comment by UnivexDont** [comment]
> Looks like the same problem I have in #123852 Theres a workaround in my ticket, that can fix the issues, as long as the script is not regenerated.

I was able to successfully archive after following the steps in issue #123852 and modifying the post script. Do you know if this is an issue with Xcode 14.3 or with Flutter?

**Comment by smiera** [comment]
I have the same problem.
```
[✓] Flutter (Channel stable, 3.7.9, on macOS 13.2.1 22D68 darwin-arm64)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
```
https://github.com/flutter/flutter/issues/123852 - this helps.

**Comment by smiera** [comment]
No errors in Xcode 14.2

**Comment by smiera** [comment]
not sure if this is related, but after updating to Xcode 14.3, there is one more error when running app in simulator:
```
File not found: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphoneos.a
```

Fix [here](https://stackoverflow.com/a/75867043/857923)

**Comment by UnivexDont** [comment]
> I had same error

I got this problem too.

**Comment by UnivexDont** [comment]
https://github.com/flutter/flutter/issues/123852

**Comment by darshankawar** [comment]
Thanks for the report everyone.
Per https://github.com/flutter/flutter/issues/123852#issuecomment-1492855357 comment, since this seems to be related to cocoapods and seem to have been fixed at their end, https://github.com/CocoaPods/CocoaPods/pull/11828, until they release a new version of cocoapod, can everyone facing this issue in this thread try https://github.com/CocoaPods/CocoaPods/pull/11828#issuecomment-1493406248 as mentioned and see if that helps to fix the issue at respective end ?

**Comment by jmagman** [comment]
@darshankawar let's duplicate all of these https://github.com/CocoaPods/CocoaPods/issues/11808 reports to  https://github.com/flutter/flutter/issues/123890.

While this is a CocoaPods issue and has been fixed there, the Flutter team will investigate a workaround.  Please follow along in https://github.com/flutter/flutter/issues/123890 for updates.
