### ISSUE TITLE
[Impeller] SK_LEGACY_IGNORE_DRAW_VERTICES_BLEND_WITH_NO_SHADER is not emulated.

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#123834]
The Flutter engine builds Skia with `#ifdef SK_LEGACY_IGNORE_DRAW_VERTICES_BLEND_WITH_NO_SHADER` enabled.

This makes `SkCanvas::drawVertices` override the blend mode with `SkBlendMode::kDst` if the `SkPaint` has no shader.
(see https://github.com/flutter/flutter/issues/118262)

Impeller does not currently implement this.  Flutter applications that rely on this behavior will need to explicitly specify `BlendMode.dst` when calling `Canvas.drawVertices`.

**Comment by jonahwilliams** [comment]
See also: https://github.com/flutter/flutter/issues/118262

IIRC canvaskit doesn't currently respect this either.

**Comment by chinmaygarde** [comment]
This seems like an easy fix in the Aiks layer. Can we just match behavior or are we not convinced we should.

**Comment by chinmaygarde** [comment]
If we don't have a strong opinion, I suggest matching current mobile Skia behavior since we are replacing it. Just to make the transition the least surprising as possible.
