### ISSUE TITLE
SingleChildScrollView viewport jumps around when scrolling.

### ISSUE THREAD

**Issue by whiskeyPeak** [flutter/flutter#123840]
Widgets inside a ```SingleChildScrollView``` jump around to the right as if the viewport keeps changing constraints. Something interesting that I have noticed is that the viewport doesn't seem to be using MSAA? 

Normally when a widget is positioned in the centre where its width constraints are an odd number, both of its sides (left and right) become blurry. However with all of the scrolling widgets (```SingleChildScrollView```, ```ListView```, ```GridView```...) the edges are always sharp. I think this may be related to what I am experiencing here. 
This is happening on both stable 3.7 and master 3.9.0-20.0

From the video below, not only are the containers always jumping around, but the inkwell for the ```MenuItemButton``` always goes out 1px further to the right.

Video: 

https://user-images.githubusercontent.com/73116038/229033662-96e50d49-e789-46fd-bab5-e37bbce543a2.mp4

<details>
<summary>Repro code:</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: SizedBox(
            height: 200,
            width: 200,
            child: SingleChildScrollView(
              child: Container(
                color: Colors.red,
                child: Column(
                  children: [
                    SizedBox(
                      width: double.infinity,
                      height: 42,
                      child: Material(
                        color: Colors.blue,
                        child: InkWell(
                          onTap: () {},
                        ),
                      ),
                    ),
                    Container(
                      width: double.infinity,
                      height: 42,
                      color: Colors.green,
                    ),
                    MenuItemButton(
                      onPressed: () {},
                      child: const Text('Tap me'),
                    ),
                    MenuItemButton(
                      onPressed: () {},
                      child: const Text('Tap me'),
                    ),
                    MenuItemButton(
                      onPressed: () {},
                      child: const Text('Tap me'),
                    ),
                    MenuItemButton(
                      onPressed: () {},
                      child: const Text('Tap me'),
                    ),
                    MenuItemButton(
                      onPressed: () {},
                      child: const Text('Tap me'),
                    ),
                    MenuItemButton(
                      onPressed: () {},
                      child: const Text('Tap me'),
                    ),
                    MenuItemButton(
                      onPressed: () {},
                      child: const Text('Tap me'),
                    ),
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

CC @Piinks

**Comment by exaby73** [comment]
Hello @whiskeyPeak. Please refrain from mentioning team members directly.

I have found a similar issue (https://github.com/flutter/flutter/issues/110957). Are you hitting this?

**Comment by whiskeyPeak** [comment]
I don't think so. The issue you linked talks about widgets/text jumping around even when no scrollView is present. My case is specifically about the right side of the scrollView extending by 1 pixel when scrolling or using an inkwell widget.

**Comment by exaby73** [comment]
Are you able to reproduce this issue on both desktop and web? On MacOS, I cannot seem to reproduce this issue at all

**Comment by whiskeyPeak** [comment]
Whoops, sorry for the long reply. This issue isn't reproduceable on web

**Comment by kirill-21** [comment]
> Are you able to reproduce this issue on both desktop and web? On MacOS, I cannot seem to reproduce this issue at all

It may be related  to system/browser scaling, from by experience widgets jiggling behaviour is different depending on the scaling value

**Comment by exaby73** [comment]
So testing this on Linux and Windows, I am still not able to reproduce this. @whiskeyPeak If what @kirill-21 is saying is true, so you have any scaling set on your distro? Or even fractional scaling?
