### ISSUE TITLE
how to save image  camera plans

### ISSUE THREAD

**Issue by arupnaskarbkp** [flutter/flutter#123838]
await controller.startImageStream((image) async {
   how to save image image.plans ?
    });

how to save image without take picture function?

**Comment by mathlouly** [comment]
imagine.plans returns a list, taking the first position of the list, you can access the bytes, with that you can write these bytes in a file according to the imageFormatGroup that was passed in the camera configuration, example

```dart
var bytes = cameraImageData.planes.first.bytes;
final path = await getExternalStorageDirectory();
final file = File('${path?.path}/img.jpg');
file.writeAsBytes(bytes);
```

**Comment by arupnaskarbkp** [comment]
not working
