### ISSUE TITLE
Google testing didn't run on a PR

### ISSUE THREAD

**Issue by gnprice** [flutter/flutter#123889]
On #123842, I'd have expected the "Google testing" check to run, but I don't see it anywhere in the list of checks.

* It's had plenty of time to start; the last update to the PR was over 2 hours ago.
* It's [documented](https://github.com/flutter/flutter/wiki/Understanding-google-testing) to start when a Flutter hacker approves the PR.

  The PR's author (me) is a Flutter hacker, so I'd expect that to count, just like it counts toward the two approvals required by the autosubmit bot. And I think I've seen that working on other PRs.

Is this intended behavior in some way? Or is there a bug or an operational issue?

Possible related issues:
* Sometimes the check does appear, but stays in "Pending" status indefinitely: #123289
* Other issues linked to from that one.

**Comment by Jasguerrero** [comment]
Thanks for filling the issue. As you mentioned google testing should start after the PR is approved by a member (opening a PR as a member does not count as an approval)

**Comment by gnprice** [comment]
Thanks for the swift reply.

I've made a small edit to that wiki page https://github.com/flutter/flutter/wiki/Understanding-Google-Testing to make that point explicit, in case I'm not the only person who's been confused about it.
