### ISSUE TITLE
Error when building engine for windows x86

### ISSUE THREAD

**Issue by chandarlee** [flutter/flutter#123868]
I want to build windows x86 flutter engine. I am compiling the x86 engine on a x64 windows 11 PC.
And when I  setup `gn` with `python .\flutter\tools\gn --windows-cpu=x86 --runtime_mode=jit_release --no-prebuilt-dart-sdk --verbose` encounter errors like belows.

> ERROR Unresolved dependencies.
//flutter:gen_snapshot(//build/toolchain/win:clang_x86)
  needs //third_party/dart/runtime/bin:gen_snapshot(//build/toolchain/win:clang_x64)
//flutter/impeller/blobcat:flatc_blobcat_flatbuffers(//build/toolchain/win:clang_x86)
  needs //third_party/flatbuffers:flatc(//build/toolchain/win:clang_x64)
//flutter/impeller/entity:genlib_gles_entity_shaders(//build/toolchain/win:clang_x86)
  needs //flutter/impeller/blobcat:blobcat(//build/toolchain/win:clang_x64)
//flutter/impeller/entity:genlib_gles_framebuffer_blend_entity_shaders(//build/toolchain/win:clang_x86)
  needs //flutter/impeller/blobcat:blobcat(//build/toolchain/win:clang_x64)
//flutter/impeller/entity:genlib_gles_modern_entity_shaders(//build/toolchain/win:clang_x86)
  needs //flutter/impeller/blobcat:blobcat(//build/toolchain/win:clang_x64)
//flutter/impeller/entity:genlib_vk_entity_shaders(//build/toolchain/win:clang_x86)
  needs //flutter/impeller/blobcat:blobcat(//build/toolchain/win:clang_x64)
//flutter/impeller/entity:genlib_vk_framebuffer_blend_entity_shaders(//build/toolchain/win:clang_x86)
  needs //flutter/impeller/blobcat:blobcat(//build/toolchain/win:clang_x64)
//flutter/impeller/entity:genlib_vk_modern_entity_shaders(//build/toolchain/win:clang_x86)
  needs //flutter/impeller/blobcat:blobcat(//build/toolchain/win:clang_x64)
//flutter/impeller/entity:impellerc_gles_entity_shaders(//build/toolchain/win:clang_x86)
  needs //flutter/impeller/compiler:impellerc(//build/toolchain/win:clang_x64)
//flutter/impeller/entity:impellerc_gles_framebuffer_blend_entity_shaders(//build/toolchain/win:clang_x86)
  needs //flutter/impeller/compiler:impellerc(//build/toolchain/win:clang_x64)
//flutter/impeller/entity:impellerc_gles_modern_entity_shaders(//build/toolchain/win:clang_x86)
  needs //flutter/impeller/compiler:impellerc(//build/toolchain/win:clang_x64)
//flutter/impeller/entity:impellerc_vk_entity_shaders(//build/toolchain/win:clang_x86)
  needs //flutter/impeller/compiler:impellerc(//build/toolchain/win:clang_x64)
//flutter/impeller/entity:impellerc_vk_framebuffer_blend_entity_shaders(//build/toolchain/win:clang_x86)
  needs //flutter/impeller/compiler:impellerc(//build/toolchain/win:clang_x64)
//flutter/impeller/entity:impellerc_vk_modern_entity_shaders(//build/toolchain/win:clang_x86)
  needs //flutter/impeller/compiler:impellerc(//build/toolchain/win:clang_x64)
//flutter/impeller/renderer:genlib_vk_compute_shaders(//build/toolchain/win:clang_x86)
  needs //flutter/impeller/blobcat:blobcat(//build/toolchain/win:clang_x64)
//flutter/impeller/renderer:impellerc_vk_compute_shaders(//build/toolchain/win:clang_x86)
  needs //flutter/impeller/compiler:impellerc(//build/toolchain/win:clang_x64)
//flutter/impeller/runtime_stage:flatc_runtime_stage_flatbuffers(//build/toolchain/win:clang_x86)
  needs //third_party/flatbuffers:flatc(//build/toolchain/win:clang_x64)
//flutter/impeller/scene/importer:flatc_importer_flatbuffers(//build/toolchain/win:clang_x86)
  needs //third_party/flatbuffers:flatc(//build/toolchain/win:clang_x64)
//flutter/impeller/scene/shaders:genlib_gles_shaders(//build/toolchain/win:clang_x86)
  needs //flutter/impeller/blobcat:blobcat(//build/toolchain/win:clang_x64)
//flutter/impeller/scene/shaders:genlib_vk_shaders(//build/toolchain/win:clang_x86)
  needs //flutter/impeller/blobcat:blobcat(//build/toolchain/win:clang_x64)
//flutter/impeller/scene/shaders:impellerc_gles_shaders(//build/toolchain/win:clang_x86)
  needs //flutter/impeller/compiler:impellerc(//build/toolchain/win:clang_x64)
//flutter/impeller/scene/shaders:impellerc_vk_shaders(//build/toolchain/win:clang_x86)
  needs //flutter/impeller/compiler:impellerc(//build/toolchain/win:clang_x64)
//flutter/lib/snapshot:generate_snapshot_bin(//build/toolchain/win:clang_x86)
  needs //third_party/dart/runtime/bin:gen_snapshot(//build/toolchain/win:clang_x64)
//flutter/testing:vmservice_snapshot(//build/toolchain/win:clang_x86)
  needs //third_party/dart/runtime/bin:gen_snapshot(//build/toolchain/win:clang_x64)
//third_party/dart/runtime/bin:generate_snapshot_bin(//build/toolchain/win:clang_x86)
  needs //third_party/dart/runtime/bin:gen_snapshot(//build/toolchain/win:clang_x64)
//third_party/dart/utils/gen_kernel:bootstrap_gen_kernel(//build/toolchain/win:clang_x86)
  needs //third_party/dart/runtime/vm:kernel_platform_files(//build/toolchain/win:clang_x64)
//third_party/dart/utils/gen_kernel:gen_kernel_dill(//build/toolchain/win:clang_x86)
  needs //third_party/dart/runtime/vm:kernel_platform_files(//build/toolchain/win:clang_x64)
//third_party/dart/utils/kernel-service:frontend_server(//build/toolchain/win:clang_x86)
  needs //third_party/dart/runtime/vm:kernel_platform_files(//build/toolchain/win:clang_x64)
//third_party/dart/utils/kernel-service:frontend_server_dill(//build/toolchain/win:clang_x86)
  needs //third_party/dart/runtime/vm:kernel_platform_files(//build/toolchain/win:clang_x64)
//third_party/dart/utils/kernel-service:kernel-service_snapshot_dill(//build/toolchain/win:clang_x86)
  needs //third_party/dart/runtime/vm:kernel_platform_files(//build/toolchain/win:clang_x64)
//third_party/dart/utils/kernel-service:kernel_service_dill(//build/toolchain/win:clang_x86)
  needs //third_party/dart/runtime/vm:kernel_platform_files(//build/toolchain/win:clang_x64)

Is it supported compiling x86 engine on x64 windows PC? And how to fix above problem? Thanks.

**Comment by chandarlee** [comment]
> I want to build windows x86 flutter engine. I am compiling the x86 engine on a x64 windows 11 PC. And when I setup `gn` with `python .\flutter\tools\gn --windows-cpu=x86 --runtime_mode=jit_release --no-prebuilt-dart-sdk --verbose` encounter errors like belows.
> 
> > ERROR Unresolved dependencies.
> > //flutter:gen_snapshot(//build/toolchain/win:clang_x86)
> > needs //third_party/dart/runtime/bin:gen_snapshot(//build/toolchain/win:clang_x64)
> > //flutter/impeller/blobcat:flatc_blobcat_flatbuffers(//build/toolchain/win:clang_x86)
> > needs //third_party/flatbuffers:flatc(//build/toolchain/win:clang_x64)
> > //flutter/impeller/entity:genlib_gles_entity_shaders(//build/toolchain/win:clang_x86)
> > needs //flutter/impeller/blobcat:blobcat(//build/toolchain/win:clang_x64)
> > //flutter/impeller/entity:genlib_gles_framebuffer_blend_entity_shaders(//build/toolchain/win:clang_x86)
> > needs //flutter/impeller/blobcat:blobcat(//build/toolchain/win:clang_x64)
> > //flutter/impeller/entity:genlib_gles_modern_entity_shaders(//build/toolchain/win:clang_x86)
> > needs //flutter/impeller/blobcat:blobcat(//build/toolchain/win:clang_x64)
> > //flutter/impeller/entity:genlib_vk_entity_shaders(//build/toolchain/win:clang_x86)
> > needs //flutter/impeller/blobcat:blobcat(//build/toolchain/win:clang_x64)
> > //flutter/impeller/entity:genlib_vk_framebuffer_blend_entity_shaders(//build/toolchain/win:clang_x86)
> > needs //flutter/impeller/blobcat:blobcat(//build/toolchain/win:clang_x64)
> > //flutter/impeller/entity:genlib_vk_modern_entity_shaders(//build/toolchain/win:clang_x86)
> > needs //flutter/impeller/blobcat:blobcat(//build/toolchain/win:clang_x64)
> > //flutter/impeller/entity:impellerc_gles_entity_shaders(//build/toolchain/win:clang_x86)
> > needs //flutter/impeller/compiler:impellerc(//build/toolchain/win:clang_x64)
> > //flutter/impeller/entity:impellerc_gles_framebuffer_blend_entity_shaders(//build/toolchain/win:clang_x86)
> > needs //flutter/impeller/compiler:impellerc(//build/toolchain/win:clang_x64)
> > //flutter/impeller/entity:impellerc_gles_modern_entity_shaders(//build/toolchain/win:clang_x86)
> > needs //flutter/impeller/compiler:impellerc(//build/toolchain/win:clang_x64)
> > //flutter/impeller/entity:impellerc_vk_entity_shaders(//build/toolchain/win:clang_x86)
> > needs //flutter/impeller/compiler:impellerc(//build/toolchain/win:clang_x64)
> > //flutter/impeller/entity:impellerc_vk_framebuffer_blend_entity_shaders(//build/toolchain/win:clang_x86)
> > needs //flutter/impeller/compiler:impellerc(//build/toolchain/win:clang_x64)
> > //flutter/impeller/entity:impellerc_vk_modern_entity_shaders(//build/toolchain/win:clang_x86)
> > needs //flutter/impeller/compiler:impellerc(//build/toolchain/win:clang_x64)
> > //flutter/impeller/renderer:genlib_vk_compute_shaders(//build/toolchain/win:clang_x86)
> > needs //flutter/impeller/blobcat:blobcat(//build/toolchain/win:clang_x64)
> > //flutter/impeller/renderer:impellerc_vk_compute_shaders(//build/toolchain/win:clang_x86)
> > needs //flutter/impeller/compiler:impellerc(//build/toolchain/win:clang_x64)
> > //flutter/impeller/runtime_stage:flatc_runtime_stage_flatbuffers(//build/toolchain/win:clang_x86)
> > needs //third_party/flatbuffers:flatc(//build/toolchain/win:clang_x64)
> > //flutter/impeller/scene/importer:flatc_importer_flatbuffers(//build/toolchain/win:clang_x86)
> > needs //third_party/flatbuffers:flatc(//build/toolchain/win:clang_x64)
> > //flutter/impeller/scene/shaders:genlib_gles_shaders(//build/toolchain/win:clang_x86)
> > needs //flutter/impeller/blobcat:blobcat(//build/toolchain/win:clang_x64)
> > //flutter/impeller/scene/shaders:genlib_vk_shaders(//build/toolchain/win:clang_x86)
> > needs //flutter/impeller/blobcat:blobcat(//build/toolchain/win:clang_x64)
> > //flutter/impeller/scene/shaders:impellerc_gles_shaders(//build/toolchain/win:clang_x86)
> > needs //flutter/impeller/compiler:impellerc(//build/toolchain/win:clang_x64)
> > //flutter/impeller/scene/shaders:impellerc_vk_shaders(//build/toolchain/win:clang_x86)
> > needs //flutter/impeller/compiler:impellerc(//build/toolchain/win:clang_x64)
> > //flutter/lib/snapshot:generate_snapshot_bin(//build/toolchain/win:clang_x86)
> > needs //third_party/dart/runtime/bin:gen_snapshot(//build/toolchain/win:clang_x64)
> > //flutter/testing:vmservice_snapshot(//build/toolchain/win:clang_x86)
> > needs //third_party/dart/runtime/bin:gen_snapshot(//build/toolchain/win:clang_x64)
> > //third_party/dart/runtime/bin:generate_snapshot_bin(//build/toolchain/win:clang_x86)
> > needs //third_party/dart/runtime/bin:gen_snapshot(//build/toolchain/win:clang_x64)
> > //third_party/dart/utils/gen_kernel:bootstrap_gen_kernel(//build/toolchain/win:clang_x86)
> > needs //third_party/dart/runtime/vm:kernel_platform_files(//build/toolchain/win:clang_x64)
> > //third_party/dart/utils/gen_kernel:gen_kernel_dill(//build/toolchain/win:clang_x86)
> > needs //third_party/dart/runtime/vm:kernel_platform_files(//build/toolchain/win:clang_x64)
> > //third_party/dart/utils/kernel-service:frontend_server(//build/toolchain/win:clang_x86)
> > needs //third_party/dart/runtime/vm:kernel_platform_files(//build/toolchain/win:clang_x64)
> > //third_party/dart/utils/kernel-service:frontend_server_dill(//build/toolchain/win:clang_x86)
> > needs //third_party/dart/runtime/vm:kernel_platform_files(//build/toolchain/win:clang_x64)
> > //third_party/dart/utils/kernel-service:kernel-service_snapshot_dill(//build/toolchain/win:clang_x86)
> > needs //third_party/dart/runtime/vm:kernel_platform_files(//build/toolchain/win:clang_x64)
> > //third_party/dart/utils/kernel-service:kernel_service_dill(//build/toolchain/win:clang_x86)
> > needs //third_party/dart/runtime/vm:kernel_platform_files(//build/toolchain/win:clang_x64)
> 
> Is it supported compiling x86 engine on x64 windows PC? And how to fix above problem? Thanks.

args.gn file looks like this: 

> skia_enable_pdf = false
full_dart_sdk = false
skia_use_expat = false
skia_use_vulkan = true
skia_use_fontconfig = false
skia_use_dng_sdk = false
skia_enable_flutter_defines = true
use_goma = false
disable_vma_stl_shared_mutex = true
shell_enable_vulkan = true
skia_use_legacy_layer_bounds = true
embedder_for_target = false
dart_include_wasm_opt = false
is_official_build = true
android_full_debug = false
disable_hidden_visibility = false
skia_use_icu = true
is_clang = true
stripped_symbols = true
bssl_use_clang_integrated_as = true
skia_use_vma = false
skia_use_sfntly = false
skia_use_wuffs = true
skia_gl_standard = ""
dart_target_arch = "x86"
flutter_use_fontconfig = false
dart_component_kind = "static_library"
enable_desktop_embeddings = true
flutter_runtime_mode = "jit_release"
goma_dir = "None"
dart_version_git_info = true
target_os = "win"
skia_use_x11 = false
enable_coverage = false
target_cpu = "x86"
dart_runtime_mode = "release"
dart_lib_export_symbols = false
is_debug = true
skia_use_gl = true

**Comment by chandarlee** [comment]
> > Is it supported compiling x86 engine on x64 windows PC? And how to fix above problem? Thanks.
> 
> @chandarlee Can you check [this](https://github.com/flutter/flutter/issues/115983) open proposal and see if it helps to answer this question ?

@darshankawar I have not found anything helps.

**Comment by darshankawar** [comment]
Thanks for the feedback. My intention with sharing that issue was to inform that issue maybe related and the use case you are trying may not be supported yet, but that's my guess.

I am going ahead and labeling this issue for team's thoughts.

**Comment by loic-sharma** [comment]
@chandarlee Hello, thank you for opening this issue! Flutter doesn't support 32-bit Windows as a target. Please upvote this issue: https://github.com/flutter/flutter/issues/37777

I'll close this off as a duplicate. Please let us know if I misunderstood your question and we can reopen this issue.
