### ISSUE TITLE
Add example in FlatButton, RaisedButton, etc that shows setting the text of the button

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#12382]
I checked the FlatButton and I couldn't find the simple of example of "a button with text". There isn't an obvious "declare the text of the button here". I assume it's the child widget?

https://docs.flutter.io/flutter/material/FlatButton-class.html

It would be sufficient, IMO, to show a simple example snippet in the top of the docs.

**Comment by sethladd** [comment]
cc @Hixie

**Comment by edutrul** [comment]
I agree!
for instance here's a piece of code to update in documentation
```
            new RaisedButton(
              onPressed: _play,
              child: new Text('Play!'),
              color: Colors.blueAccent,
            ),
```

**Comment by Hixie** [comment]
Yeah we should add sample code and screen shots to those API docs.
