### ISSUE TITLE
iOS project’s cache is still very large after flutter clean on the flutter 3.7.8 & dart 2.19.5 & MacOS 12.6.3

### ISSUE THREAD

**Issue by DevChen** [flutter/flutter#123982]
flutter 3.7.8
 dart 2.19.5 
 MacOS 12.6.3 
 Xcode 14.2
 Android Studio Electric Eel | 2022.1.1 Patch 2

after flutter clean，progect-->ios-->pods  ，no clean 

<img width="941" alt="截屏2023-04-03 09 59 06" src="https://user-images.githubusercontent.com/1814350/229395294-a91fd27e-4056-4d98-8eef-374ebf38303d.png">
<img width="947" alt="截屏2023-04-03 10 02 07" src="https://user-images.githubusercontent.com/1814350/229395320-5869da80-dd89-464f-97bf-4886fa514d0f.png">

**Comment by darshankawar** [comment]
@DevChen 
Running `flutter clean` essentially does following on a sample app:

```
dhs@Dhss-MacBook-Pro test_app % flutter clean
Cleaning Xcode workspace...                                         4.0s
Cleaning Xcode workspace...                                         3.9s
Deleting storybook...                                              520ms
Deleting .dart_tool...                                              45ms
Deleting Generated.xcconfig...                                       1ms
Deleting flutter_export_environment.sh...                            0ms
Deleting Flutter.podspec...                                          0ms
Deleting ephemeral...                                                0ms
Deleting ephemeral...                                                0ms
Deleting ephemeral...                                                0ms
Deleting .flutter-plugins-dependencies...                            0ms
Deleting .flutter-plugins...                                         0ms
dhs@Dhss-MacBook-Pro test_app % 

```
If you want to clear cache, try running `flutter pub cache clean` or `flutter pub cache repair`.
Also check this document for your further reference: https://docs.flutter.dev/perf/app-size#ios
