### ISSUE TITLE
[codelabs] Use records in next-gen-ui

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#123949]
lib/assets.dart

```dart
typedef Shaders = ({FragmentShader orb, FragmentShader ui});

Future<Shaders> loadShaders() async => (
      orb: (await _loadShader(AssetPaths.orbShader)),
      ui: (await _loadShader(AssetPaths.uiShader)),
    );
```

CC @domesticmouse

**Comment by kevmoo** [comment]
While you're hacking

```dart

abstract final class AppColors {
  static final orbColors = [
    const Color(0xFF71FDBF),
    const Color(0xFFCE33FF),
    const Color(0xFFFF5033),
  ];

  static final emitColors = [
    const Color(0xFF96FF33),
    const Color(0xFF00FFFF),
    const Color(0xFFFF993E),
  ];
}
```

**Comment by kevmoo** [comment]
...and above!

**Comment by domesticmouse** [comment]
It appears this doesn't work on the latest beta? Any ideas on when this will be available for testing outside of master?

**Comment by kevmoo** [comment]
Likely with the next beta roll – so...soon 😄

**Comment by domesticmouse** [comment]
I'll hold this change until then. Btw, what is your suggested replacement for the `AppColors` class? A record plus a typedef, or just a record? I'm guessing the latter?

**Comment by kevmoo** [comment]
A class with just static members could be final abstract. That's it.

**Comment by domesticmouse** [comment]
> A class with just static members could be final abstract. That's it.

Hilariously, I'm seeing a red underline for your suggested `AppColors` code in VSCode when running `Flutter 3.9.0-20.0.pre.80` but `flutter analyze` reports no issues found.

There's some bugs that need to be ironed out here.

**Comment by craiglabenz** [comment]
I've never seen the `abstract final class` series of keywords. This is completely new to me.

**Comment by domesticmouse** [comment]
> I've never seen the `abstract final class` series of keywords. This is completely new to me.

IIUC it's new in Dart 3. My understanding is that `final class` is Dart 3's version of Kotlin's `sealed class`.

**Comment by kevmoo** [comment]
@gintominto5329 – `const` should be fine there, too
