### ISSUE TITLE
Add validation of Java Gradle and AGP version compatibility to `flutter analyze --suggestions` 

### ISSUE THREAD

**Issue by reidbaker** [flutter/flutter#123917]
Update flutter analyze --suggestions 
“Flutter doctor but for project” 

Updating this tool will let us exercise the new version mapping code that can be reused in a more visable place. 

Consider adding usage data showing how often this issue was detected and/or fixed.
Example:
https://github.com/flutter/flutter/blob/42f61b32c537e664575b2efc7e154529f78184a2/packages/flutter_tools/lib/src/ios/xcodeproj.dart#L230-L234
Anonymous data collected from that go/flutter-xcode-show-build-settings-timeout-data

**Comment by navaronbracke** [comment]
@reidbaker Would `flutter doctor (-v)` warn the user if their Gradle / Android Studio / AGP is out of sync, per #123916 ?

Having to specifically run `flutter analyze --suggestions` might not always be obvious in my opinion.
Unless the tool runs that command behind the scenes somewhere?

**Comment by Hixie** [comment]
Landed.
