### ISSUE TITLE
StatefulWidget inside DefaultTabController <-- TabBarView, re-initState when showDialog

### ISSUE THREAD

**Issue by kaquay** [flutter/flutter#12398]
the StatefulWidget call initState when dialog show or dismiss( touch outside). I cannot pop to dismiss Dialog also ( Another exception was thrown: Looking up a deactivated widget's ancestor is unsafe.)

**Comment by sethladd** [comment]
Thanks for the feedback!

Is the issue that initState is being called, when you don't expect it to be called?

**Comment by kaquay** [comment]
yes. I expect that initState just call one time .

**Comment by Hixie** [comment]
Can you attach some sample code to explain what you mean? I'm not really sure I follow what the problem is.

**Comment by kaquay** [comment]
thank for your attention, it's has been fixed by using static globalKey

**Comment by frey1esm** [comment]
@kaquay Could you show your code, then close the issue if it's resolved.
