### ISSUE TITLE
Simple and compound queries needed for Cloud Firestore plugin

### ISSUE THREAD

**Issue by pauldemarco** [flutter/flutter#12396]
The Cloud Firestore plugin needs the `.where` clause implemented for simple and compound queries.

[Reference link](https://cloud.google.com/firestore/docs/query-data/queries)

**Comment by sethladd** [comment]
cc @collinjackson @kroikie

**Comment by collinjackson** [comment]
I implemented this for rtdb and it should be coming soon for firestore

**Comment by bjornbjorn** [comment]
How is this one coming along? :)

**Comment by mit-mit** [comment]
@collinjackson was this completed in https://github.com/flutter/plugins/pull/258 ?

**Comment by pulyaevskiy** [comment]
I feel like this could be closed, flutter/plugins#258 addressed this.

**Comment by kroikie** [comment]
@pauldemarco

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/960. Any further collaboration will be done there.
