### ISSUE TITLE
Hi @huycozy

### ISSUE THREAD

**Issue by Hemazyn** [flutter/flutter#123909]
Please how do we fix this.
![Screenshot 2023-04-01 at 12 26 10 AM](https://user-images.githubusercontent.com/75551864/229249559-68396bd7-ba62-41de-ad19-242b31abd61c.png)

null
This binary was built with the incorrect architecture to run on this machine.
Flutter requires the Rosetta translation environment. If you are on an ARM Mac, try running:
  sudo softwareupdate --install-rosetta --agree-to-license

**Comment by iapicca** [comment]
@Hemazyn 
please post logs, not screenshots
what's the output of `flutter doctor -v`?

**Comment by Hemazyn** [comment]
Thanks for reaching out to me, concerning the issue I ask of help with on GitHub.

The output was

null
This binary was built with the incorrect architecture to run on this machine.
Flutter requires the Rosetta translation environment. If you are on an ARM Mac, try running:
  sudo softwareupdate --install-rosetta --agree-to-license

When I entered “flutter doctor -v”

Though I was able to get the issue aside from not able to install rosetta due to Mac compatibility, that was when I uninstall my android studio and then enter the “flutter doctor -v” and it run successfully.

Thanks for reaching out to me I really appreciate, and I will love to be able to reach out to you whenever I have issues concerning Flutter.

**Comment by iapicca** [comment]
@Hemazyn 
please run `sudo softwareupdate --install-rosetta --agree-to-license`
and after that post the full `flutter doctor -v` output
thanks

**Comment by Hemazyn** [comment]
Happy Palm Sunday HUYCOZY,
I did just as you said but the output was “Rosetta 2 is not supported on
this device”.
Though it has worked.

**Comment by iapicca** [comment]
> Happy Palm Sunday HUYCOZY, I did just as you said but the output was “Rosetta 2 is not supported on this device”. Though it has worked.

@Hemazyn 
**_on what device are you installing flutter?_**
if it's a mac w/ apple silicone `rosetta 2` is a requirement (see [docs](https://docs.flutter.dev/get-started/install/macos#system-requirements))

**Comment by Hemazyn** [comment]
2017 MacBook air

**Comment by iapicca** [comment]
please make sure you installed the intel version of flutter from the link in this [page](https://docs.flutter.dev/get-started/install/macos#get-sdk)

**Comment by Hemazyn** [comment]
Thanks, I'll check it out.

**Comment by Hemazyn** [comment]
! Warning: `dart` on your path resolves to /usr/local/Cellar/dart-sdk/2.19.6/libexec/bin/dart, which is not inside your current Flutter SDK checkout at
      /Users/Emmanuel/Downloads/flutter. Consider adding /Users/Emmanuel/Downloads/flutter/bin to the front of your path.

This was when I ran flutter doctor -v.

**Comment by iapicca** [comment]
that's ok, just a warning when you install dart w/ `homebrew`

**Comment by huycozy** [comment]
@Hemazyn It seems the original issue has been solved so I will close this issue from here. For the following issue, please read https://github.com/flutter/flutter/issues/115651#issuecomment-1409619007 for more information.
