### ISSUE TITLE
WIndows: "Unable to find git in your PATH." if terminal is not in admin mode

### ISSUE THREAD

**Issue by badrulconfido** [flutter/flutter#123995]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Follow all steps to install Flutter on WIndows, including installing Git before hand
2. Make sure that git works if you type it into Powershell as a regular user. If not put the git /cmd folder into your Windows PATH
3. Open up Power shell as a regular / non-admin user then type flutter doctor -v
Causes an error.

Not try opening in Admin mode and doing the same - it should work this time.

### Actual results

Error: Unable to find git in your PATH.

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

Error: Unable to find git in your PATH.

**Comment by badrulconfido** [comment]
Afraid that did not solve the issue. So the links suggested "You can't use a git-pulled SDK and must use a download SDK .zip".
However my flutter sdk came from the .zip file and not a git pull.

One comment mentions checking out another link which in turn suggests that git report may be marked as unsafe which in turn leads you to another link which tells you to try the following but neither of these worked:
```
git config --global --add safe.directory C:\Users\badrulxxx\flutter\.git
git config --global --add safe.directory C:\Users\badrulxxx\flutter\
```

**Comment by darshankawar** [comment]
Good to know your issue is resolved. Closing as such.
