### ISSUE TITLE
import 'package:provider/provider.dart'; and import 'package:english_words/english_words.dart'; and pair, wordpair,context.watch are giving arror

### ISSUE THREAD

**Issue by aalishan808** [flutter/flutter#123968]
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by stuartmorgan** [comment]
Issues with third-party packages need to be reported to the developers of those packages.

Closing as this is not a Flutter issue.
