### ISSUE TITLE
TabBarView and PageView horizontal a11y scrolling behavior

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#12390]
When swiping through the elements on a page in a TabBarView/PageView and the last element is reached, the view scrolls to the next page (similarly to the behavior seen in a vertical scrolling view). This behavior is incorrect. You shouldn't be able to switch pages by just swiping left/right. You should only be able to switch pages with either two finger scrolling (Android) or three-finger swipes (iOS).

**Comment by goderbauer** [comment]
In terms of Android's OEM widgets, these type of scrollers are exposed as ViewPager.

https://developer.android.com/reference/android/support/v4/view/ViewPager.html

**Comment by jonahwilliams** [comment]
Fixed via https://github.com/flutter/flutter/pull/20210
