### ISSUE TITLE
Issue with firebase_firestore plugin alongside the firebase_auth plugin

### ISSUE THREAD

**Issue by tomialagbe** [flutter/flutter#12399]
## Steps to Reproduce

I've been having issues building my flutter project since i added the firebase_firestore plugin.
I added the firebase_firestore plugin to my pubspec.yaml as shown below:

```
dependencies:
  flutter:
    sdk: flutter
        font_awesome_flutter: "4.7.2"
        open_iconic_flutter: "0.1.0"
        image_picker: "^0.1.1"
        firebase_firestore: "^0.0.1"
        firebase_auth: "^0.2.3"
```

## Logs
Run your application with `flutter run` and attach all the log output.

Launching lib/main.dart on SM G950F in debug mode...
Initializing gradle...                                1.1s
Resolving dependencies...                            37.0s
Running 'gradlew assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/common/internal/zzbb;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Gradle build failed: 1

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor

[√] Flutter (on Microsoft Windows [Version 10.0.15063], locale en-US, channel alpha)
    • Flutter at C:\Users\Tomi\flutter
    • Framework revision 701d534ba9 (3 weeks ago), 2017-09-12 14:01:51 -0700
    • Engine revision 31d03de019
    • Tools Dart version 1.25.0-dev.11.0

[√] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at C:\Users\Tomi\AppData\Local\Android\sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] IntelliJ IDEA Ultimate Edition (version 2016.3)
    X Flutter plugin version 12.1 - the recommended minimum version is 16.0.0
    • Dart plugin version 163.13137
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins
    X This install is older than the minimum recommended version of 2017.1.0.

[√] IntelliJ IDEA Ultimate Edition (version 2017.2)
    • Flutter plugin version 17.0
    • Dart plugin version 171.4694.29

[√] Connected devices
    • SM G950F • ce031713e364ac480d • android-arm • Android 7.0 (API 24)

**Comment by sethladd** [comment]
cc @collinjackson @kroikie

**Comment by collinjackson** [comment]
This will be fixed today.

**Comment by JMichaelYang** [comment]
Ran into the same issue, tried running a gradlew app:dependencies and came up with this. 

+--- project :firebase_auth
|    +--- com.google.guava:guava:20.0
|    +--- com.google.firebase:firebase-core:11.0.+ -> 11.4.2
|    |    \--- com.google.firebase:firebase-analytics:11.4.2 (*)
|    \--- com.google.firebase:firebase-auth:11.0.+ -> 11.0.4 (*)
+--- project :firebase_firestore
|    +--- com.google.firebase:firebase-firestore:11.4.+ -> 11.4.2
|    |    +--- com.google.android.gms:play-services-basement:11.4.2 (*)
|    |    +--- com.google.firebase:firebase-common:11.4.2 (*)
|    |    +--- com.google.android.gms:play-services-tasks:11.4.2 (*)
|    |    +--- com.squareup.okhttp:okhttp:2.7.2
|    |    |    \--- com.squareup.okio:okio:1.6.0
|    |    \--- com.google.guava:guava:20.0
|    \--- com.google.firebase:firebase-core:11.4.+ -> 11.4.2 (*)

Looks like things should be alright based on that but still getting the error.

**Comment by tomialagbe** [comment]
Please has this issue been resolved ?

**Comment by kroikie** [comment]
@tomialagbe

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/959. Any further collaboration will be done there.
