### ISSUE TITLE
Flutter not playing audio in release mode

### ISSUE THREAD

**Issue by chiptech-mitchell** [flutter/flutter#123958]
I have a flutter app that plays an audio alert when it receives a push notification. however I have noticed that recently (after making several changes to upgrade to flutter 3.7.8) this audio no longer plays when the app is in release mode while it functions as expected in debug mode. When running the app in release mode I have seen this message in the debug console Dart Error: Dart_LookupLibrary: library 'package:my_app/infrastructure/notifications/push_notification_service.dart' not found. so it does appear that this package (this is an internal .dart file in my lib directory and not an external package) this may be a red herring but as it mentions the push notification service I don't believe it is.

I'm kind of at a loss as to why this would be suddenly become an issue and only in release mode and its hard to debug release mode.

####Expected behaviour
a push notification is received along with a custom audio alert (overriding device volume and playing at max) and vibrations
####Actual behaviour 
a push notification is received and the vibrations are activated but no audio alert

So far I have tried

- inspecting the APK just incase the audio asset was missing
- removing my newly added proguard rules
- adding a new rule -keep class com.yourapp.package.name.infrastructure.notifications.** { *; }
- building the app with --no-shrink --no-obfuscate

Any help or suggestions would be appreciated

Unfortunately I don't have a reproducible example    

debug console
![image](https://user-images.githubusercontent.com/109489679/229335661-cf1e9511-14df-4d5b-af56-347b53142513.png)

There are several info level lint warnings, mostly to do with deprecated members and un awaited futures that I am unable to resolve at this point in time.

```
[√] Flutter (Channel stable, 3.7.8, on Microsoft Windows [Version 10.0.22621.1485], locale en-NZ)
    • Flutter version 3.7.8 on channel stable at C:\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 90c64ed42b (12 days ago), 2023-03-21 11:27:08 -0500
    • Engine revision 9aa7816315
    • Dart version 2.19.5
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\mitchell.quarrie\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Professional 2022 17.5.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
    • Visual Studio Professional 2022 version 17.5.33516.290
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] VS Code, 64-bit edition (version 1.76.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.60.0

[√] Connected device (4 available)
    • SM N975F (mobile) • RF8MA0HH0NR • android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.22621.1485]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 111.0.5563.147
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 111.0.1661.62

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by danagbemava-nc** [comment]
Hi @chiptech-mitchell, we can't offer any guidance or assistance without a minimal reproducible code sample. 

As a side note, is the method you're calling annotated with `@pragma('vm:entry-point')`?

**Comment by chiptech-mitchell** [comment]
> Hi @chiptech-mitchell, we can't offer any guidance or assistance without a minimal reproducible code sample.
> 
> As a side note, is the method you're calling annotated with `@pragma('vm:entry-point')`?

I have been unable to reproduce it as I don't know what is wrong, no the method hasn't been annotated with  `@pragma('vm:entry-point')`

**Comment by chiptech-mitchell** [comment]
I tried annotating the method and it appears to be working, I checked our previous release from mid to late last year and it was working even without out that annotation, is it a new thing or were we just lucky?

**Comment by danagbemava-nc** [comment]
I don't remember when exactly that was introduced but it has been there for some time now. 
You can find out more about what that annotation does in https://mrale.ph/dartvm/compiler/aot/entry_point_pragma.html & https://stackoverflow.com/questions/64314719/what-do-pragmavmprefer-inline-mean-in-flutter.

Closing as this issue appears to be solved. 

Thank you
