### ISSUE TITLE
Cleanup code signing machines

### ISSUE THREAD

**Issue by XilaiZhang** [flutter/flutter#124054]
Remove signer bots from flutter pools, re-assign machines back to the available pool, remove signer configs from chrome internal.

**Comment by godofredoc** [comment]
@yusuf-goog can you please helps us close this one?

**Comment by yusuf-goog** [comment]
From @XilaiZhang :
yeah the flutter-devicelab-mac-signing-2/3 bots in https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=os&c=status&d=asc&f=pool%3Aluci.flutter.prod&k=pool&s=id

**Comment by yusuf-goog** [comment]
Add CL to remove those bots from the pool.

**Comment by XilaiZhang** [comment]
> Add CL to remove those bots from the pool.

Thank you. +1 ed

**Comment by yusuf-goog** [comment]
@kentnguyen99 the 2 machines:

flutter-devicelab-mac-signing-2
flutter-devicelab-mac-signing-3

have been removed from the pool allocation and are ready to be reimaged and reused as necessary. When possible, please reimage them as swarming host and we can put them back into circulation.

**Comment by yusuf-goog** [comment]
@kentnguyen99 after they are reimaged, please let me know and I will create the entries to put them back into appropriate pool.

**Comment by godofredoc** [comment]
@yusuf-goog @kentnguyen99 can we close this issue?

**Comment by kentnguyen99** [comment]
Re-image both flutter-devicelab-mac-signing-2 and flutter-devicelab-mac-signing-3 as swarming machines have been completed.  
flutter-devicelab-mac-signing-2 - New hostname = flutter-devicelab-mac-48
flutter-devicelab-mac-signing-3 - New hostname = flutter-devicelab-mac-49

**Comment by godofredoc** [comment]
Thanks!
