### ISSUE TITLE
[ci] "Not a valid object name FETCH_HEAD" on pathified_analyze

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#124046]
I've just spotted a [build failure](https://cirrus-ci.com/task/4549995962040320) in `master` with the following error:

```
./script/tool_runner.sh make-deps-path-based --target-dependencies-with-non-breaking-updates
Unhandled exception:
ProcessException: fatal: Not a valid object name FETCH_HEAD
  Command: git merge-base FETCH_HEAD HEAD
#0      _throwIfProcessFailed (package:git/src/top_level.dart:39:5)
#1      runGit (package:git/src/top_level.dart:17:5)
<asynchronous suspension>
#2      GitVersionFinder.getBaseSha (package:flutter_plugin_tools/src/common/git_version_finder.dart:116:30)
<asynchronous suspension>
#3      MakeDepsPathBasedCommand._getNonBreakingUpdatePackages (package:flutter_plugin_tools/src/make_deps_path_based_command.dart:241:28)
<asynchronous suspension>
#4      MakeDepsPathBasedCommand.run (package:flutter_plugin_tools/src/make_deps_path_based_command.dart:70:15)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      main.<anonymous closure> (package:flutter_plugin_tools/src/main.dart:96:12)
<asynchronous suspension>
Exit status: 255
```

Does this script need to `git fetch` or before it runs, so [FETCH_HEAD is populated](https://git-scm.com/docs/git-fetch#_description)?

**Comment by ditman** [comment]
Similar to this? https://github.com/flutter/flutter/issues/120116

**Comment by ditman** [comment]
This failed at the same time as [this other one](https://cirrus-ci.com/task/6502728612970496?logs=upgrade_flutter#L7)

> ```
> fatal: unable to access 'https://github.com/flutter/flutter.git/': Failed to connect to github.com
> port 443 after 30 ms: Connection refused) 
> ```

So it might have been a Github timeout earlier in the pathified_analyze run?

**Comment by stuartmorgan** [comment]
> Does this script need to `git fetch` or before it runs, so [FETCH_HEAD is populated](https://git-scm.com/docs/git-fetch#_description)?

That's done [here](https://github.com/flutter/packages/blob/main/.ci/scripts/prepare_tool.sh#L6-L7), so it does seem like this was a network issue.
