### ISSUE TITLE
Flutter Plugin - Camera - exposure works on Android 8.1 phone but not on my Android 7.0 phone

### ISSUE THREAD

**Issue by atreeon** [flutter/flutter#124017]
I am testing an app that makes use of the camera plugin with two different physical phones
1. Android version 7.0 on Moto G5
2. Android version 8.1 on Blackberry BBF100-2 (aka Key 2)

I access the camera and takes pictures using the following code
```
        _cameraController!.initialize().then((_) async {
          if (!mounted) {
            return;
          }

          await _cameraController!.setFlashMode(FlashMode.off);
          await Future.delayed(Duration(milliseconds: 1000));

          _image = await _cameraController!.takePicture();
```

Using the plugin in my app, a good picture is taken when installed on my Blackberry Key2 (Android)
![FlutterApp_Key2](https://user-images.githubusercontent.com/4139336/229530404-3849ea83-6d2b-4d6b-b94c-ea538fa8eff6.jpg)

but exactly the same code on the Moto G5 I get a dark screen
![FlutterApp_Moto](https://user-images.githubusercontent.com/4139336/229530604-b871e7fe-cdc4-447f-aa74-595aca7f4d9e.jpg)

To test whether the camera works properly on the Moto G5, I took a picture with the flash disabled and I get a good image:
![CameraApp_Moto](https://user-images.githubusercontent.com/4139336/229530746-a72352e6-4c1a-4fab-91a9-58f3fa23c4fd.jpg)

I have to disable the flash in my application but on 8.1 Blackberry Key2 the image comes out fine (even in low light).

Because it works on one but not the other it looks like a bug.  The plugin says it is supported on SDK 21 (Android 6.0).  Any ideas or fixes?

**Comment by huycozy** [comment]
Thanks for the report! This is a known issue being tracked at https://github.com/flutter/flutter/issues/55284 which also happens on a specific device (similar to yours: Moto G 5S Plus).

Closing this issue as a duplicate, so please follow up on it for further updates.
