### ISSUE TITLE
[CP] Add readlink -f flag to CocoaPods script to workaround Xcode 14.3 issue

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#124081]
### issue_link

https://github.com/flutter/flutter/issues/123890

### Commit Hash

d4934fb

### Target

stable

### pr_link

https://github.com/flutter/flutter/pull/124079

### Impacted Users

Users when publishing iOS and macOS Flutter apps

### Impact Description

Users will be able to `flutter run` and `flutter build` their iOS and macOS apps, but will not be able to archive their app, which is necessary for publication to the App Store.  The archive errors out.

### Workaround

1. Downgrade from Xcode 14.3 to Xcode 14.2.
or
2. Until CocoaPods publishes the fix in [1.12.1](https://github.com/CocoaPods/CocoaPods/releases), install the master version of the cocoapods gem: https://stackoverflow.com/questions/2823492/install-gem-from-github-branch

### Risk

medium

### Test Coverage

yes

### Validation Steps

1. Install Xcode 14.3
2. On current Flutter stable run `flutter create test_create && cd test_create`

iOS:
1. Run `flutter build ipa`.  See error.

macOS:
1. Run `flutter build macos --config-only`
2. `open macos/Runner.xcworkspace`
3. Product > Archive.  See error.

On this PR archiving will succeed.

**Comment by jmagman** [comment]
@christopherfujino would be a good person to review the cp stable request.

**Comment by ryzizub** [comment]
Can't wait to get this to stable channel 🔥

**Comment by itsjustkevin** [comment]
> Can't wait to get this to stable channel 🔥

You don't have to wait. https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel 😎

**Comment by rafaellop** [comment]
Unfortunately the fix with `readlink -f` doesn't work for older xcode/macos reporting error: "readlink: illegal option -- f" when trying to `flutter build ipa`. My env is:

[✓] Flutter (Channel stable, 3.7.12, on macOS 12.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)

**Comment by jmagman** [comment]
> Unfortunately the fix with `readlink -f` doesn't work for older xcode/macos reporting error: "readlink: illegal option -- f" when trying to `flutter build ipa`. My env is:
> 
> [✓] Flutter (Channel stable, 3.7.12, on macOS 12.0) [✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)

Can you file a new issue describing what you're seeing and how to reproduce it?  Flutter explicitly doesn't add the flag unless you're running > Xcode 14.3

https://github.com/flutter/flutter/blob/5d3c1ca870a11248ca3df944ce337078a3d15738/packages/flutter_tools/lib/src/migrations/cocoapods_script_symlink.dart#L36-L40

**Comment by rafaellop** [comment]
Added https://github.com/flutter/flutter/issues/125286
