### ISSUE TITLE
Raster Thread Animation

### ISSUE THREAD

**Issue by JsouLiang** [flutter/flutter#124096]
If we can design way for some animations to be executed on the Raster thread.
In Chromium, we can make Opacity animation, transform animation they can run animation on the Raster thread that mean they don't block the UI thread when the animation calculate the interpolation value.
In iOS, we also can define CAAnimation , by CAAnimation we can define some animation properties that will send to the raster thread and don't block the UI thread.
In Android, the animation can run in RenderThread also mean don't block the UI thread.
In Flutter, we should provide a mechanism for animations to run without blocking the UI thread
@chinmaygarde @jonahwilliams

**Comment by jonahwilliams** [comment]
What work that's being performed on the UI thread do you want to offload to the UI thread? Interpolating an opacity value is trivially cheap.

**Comment by jonahwilliams** [comment]
Ultimately the UI and raster threads work cooperatively. If some work is too expensive to do on the UI thread, moving it to the raster thread will just move where the blocking occurs. If this was causing jank before, it will cause jank after.

**Comment by ajihyf** [comment]
Yes, we have many ways to optimize the UI thread and reduce its load. However, on the one hand, optimization requires a certain amount of effort and time, and in some business scenarios, UI design might be used to cover up the issue; on the other hand, some UI thread-blocking tasks can be difficult to predict and avoid (e.g., GC pauses, page transitions).

Front-end developers often use CSS animations during long CPU tasks (such as rendering complex React components) without worrying about the animation itself being choppy.

Although Android does not directly expose Render Thread animations (RenderNodeAnimator) to developers, they are extensively used in System UI. For example, Material Design's Ripple animation, animated drawable redrawing, and transitions between activities (to be precise, these are compositor animations, but at least they are not driven by the UI thread).

As a high-performance framework aiming to replace the system UI, I believe Flutter should provide a similar, more stable animation driving method.
