### ISSUE TITLE
JAVA_HOME is set to an invalid directory however it has been well established

### ISSUE THREAD

**Issue by arkrist** [flutter/flutter#124013]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1.I run 'flutter doctor' on my Macbook M2 and have Android license status unknown issue.
2.By running 'flutter doctor --android-licenses' it gives me an error 'JAVA_HOME is set to an invalid directory: /Library/Java/JavaVirtualMachines/jdk1.8.0_361.jdk/Contents/Home'.

### Actual results

By running 'flutter doctor --android-licenses' it gives me an error 'JAVA_HOME is set to an invalid directory: /Library/Java/JavaVirtualMachines/jdk1.8.0_361.jdk/Contents/Home', however JAVA_HOME has a correct path to Java 20. I verified all, there is no another java versions on my mac, only java 20. The path indicates correctly the java installation. Anyway flutter gives me this issue all the time. Reinstalling java, flutter did not solve the problem as well.

Thank you in advance for your help.

### Logs

flutter doctor --android-licenses

### Flutter Doctor output

ERROR: JAVA_HOME is set to an invalid directory: /Library/Java/JavaVirtualMachines/jdk1.8.0_361.jdk/Contents/Home

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

Android sdkmanager tool was found, but failed to run
(/Users/kariskina/Library/Android/sdk/cmdline-tools/latest/bin/sdkmanager): "exited code 1".
Try re-installing or updating your Android SDK,
visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed
instructions.

**Comment by exaby73** [comment]
Hello @arkrist. There is an issue where Flutter chooses the bundled Java installation with Android Studio over the JAVA_HOME variable. See https://github.com/flutter/flutter/issues/110807, https://github.com/flutter/flutter/issues/106416. Could you try to reinstall your Android SDK and retry the command?

**Comment by arkrist** [comment]
Hello @exaby73. As it has been mentioned before, the reinstallation of Android SDK does not change the issue.

**Comment by exaby73** [comment]
Could you try setting JAVA_HOME to the `bin` directory with the executables instead and try again?

**Comment by arkrist** [comment]
thank you, @exaby73, for the proposition, but unfortunately it did not changed the issue.

**Comment by arkrist** [comment]
@exaby73, it gives the following ERROR: JAVA_HOME is set to an invalid directory: /Library/Java/JavaVirtualMachines/jdk1.8.0_361.jdk/Contents/Home

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

Android sdkmanager tool was found, but failed to run
(/Users/[username]/Library/Android/sdk/cmdline-tools/latest/bin/sdkmanager): "exited code
1".
Try re-installing or updating your Android SDK,
visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed
instructions.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      AndroidLicenseValidator.runLicenseManager
(package:flutter_tools/src/android/android_workflow.dart:462:9)
<asynchronous suspension>
#2      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:26)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#6      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#9      run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>

**Comment by exaby73** [comment]
I'll label this issue for visibility

**Comment by andrewkolos** [comment]
I suspect this error is coming from the [`sdkmanager` tool](https://developer.android.com/tools/sdkmanager), which is part of the Android SDK. It is used by `flutter doctor` [to check Android license acceptance](https://github.com/flutter/flutter/blob/fda9ecfef76b57ae459675fdf262342a77c2c6ba/packages/flutter_tools/lib/src/android/android_workflow.dart#L389)).

As mentioned by @exaby73, `flutter` prefers to use the JDK bundled with Android Studio if it is installed and flutter can find it. @arkist, do you have Android Studio installed? The reason I ask is that, given your logs, the `JAVA_HOME` that `sdkmanager` is finding (`/Library/Java/JavaVirtualMachines/jdk1.8.0_361.jdk/Contents/Home`) doesn't look like one that points to a Java installation that comes bundled with Android Studio (e.g. `Applications/Android Studio.app/Contents/jbr/Contents/Home` on macOS).

**Comment by gnprice** [comment]
What output do you get if you try to run the command `/Library/Java/JavaVirtualMachines/jdk1.8.0_361.jdk/Contents/Home/bin/java`?

As @andrewkolos says, that error output appears to be coming from `sdkmanager`. The situation where the `sdkmanager` tool prints that error is when you have a JAVA_HOME set, but there is not an executable file at `"$JAVA_HOME"/bin/java`. When a directory doesn't have an executable file at the path "bin/java" inside it, that directory is not a valid directory to use for JAVA_HOME.

> however JAVA_HOME has a correct path to Java 20.

Do you mean that `/Library/Java/JavaVirtualMachines/jdk1.8.0_361.jdk/Contents/Home` is a correct path to Java 20, or that you have JAVA_HOME set to some other value which is a correct path to Java 20?

If `/Library/Java/JavaVirtualMachines/jdk1.8.0_361.jdk/Contents/Home` isn't the path you're trying to use for Java, then two pieces of information that would be helpful in identifying why the `flutter` tool is ending up with `sdkmanager` using that path would be:
* the complete output of `flutter doctor -v`
* the output of `echo "$JAVA_HOME"`

**Comment by arkrist** [comment]
Thank you all for the help. 

The problem has been solved! While running 'flutter doctor', a new version of Flutter has been proposed. After upgrading it, everything works well.

**Comment by arkrist** [comment]
Thank you all for the help.

The problem has been solved! While running 'flutter doctor', a new version of Flutter has been proposed. After upgrading it, everything works well.

**Comment by arkrist** [comment]
Thank you all for the help.

The problem has been solved! While running 'flutter doctor', a new version of Flutter has been proposed. After upgrading it, everything works well.
