### ISSUE TITLE
analyzer_benchmark should run on only one configuration

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#124065]
https://flutter-flutter-perf.skia.org/e/?begin=1679430121&end=1680558012&keys=Xa03ccf6a992a062e4a6e0676492cc4fb&requestType=0&selected=commit%3D34150%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DMoto_G__4_%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253Dflutter_repo_watch_maximum%252Ctest%253Danalyzer_benchmark%252C&xbaroffset=34149

This benchmark is bimodal because some of the Linux hosts have 8 cores and others have 4 cores. The bimodal nature of the benchmark means that SkiaPerf generates spurious reports and/or masks real regressions. Instead the benchmark should be pinned to a single configuration.

As a separate issue, I think this benchmark does not need a phone attached, but I'm not 100% sure about that.

cc @keyonghan

**Comment by keyonghan** [comment]
> This benchmark is bimodal because some of the Linux hosts have 8 cores and others have 4 cores. The bimodal nature of the benchmark means that SkiaPerf generates spurious reports and/or masks real regressions. Instead the benchmark should be pinned to a single configuration.

Yeah, we have two types of devicelab bots: 4 cores and 8 cores. Which do you want to enforce?

> As a separate issue, I think this benchmark does not need a phone attached, but I'm not 100% sure about that.

Validated it works on a vm bot, but the benchmark is much slower:

```
    "flutter_repo_batch": 172.325934,
    "flutter_repo_batch_minimum": 168.90769,
    "flutter_repo_batch_maximum": 174.241438,
    "flutter_repo_watch": 159.38031566666666,
    "flutter_repo_watch_minimum": 154.742325,
    "flutter_repo_watch_maximum": 167.512652,
    "mega_gallery_batch": 19.769443999999996,
    "mega_gallery_batch_minimum": 19.116,
    "mega_gallery_batch_maximum": 21.044355,
    "mega_gallery_watch": 19.275951000000003,
    "mega_gallery_watch_minimum": 19.206895,
    "mega_gallery_watch_maximum": 19.345438
```
https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/bd8e22d53a5c66633fa991eae3552f5d71c82c6e0c6cfcdadc73160cb5f8687c/+/build.proto

Do we not care about the number, but just the trend? If not, then we can switch it to the vm if a new trend series sounds okay.

**Comment by zanderso** [comment]
Is it possible to specify a bigger VM instance so that the slowdown isn't so big? Either way, let's try moving to a VM and get a sense for whether that's a problem.

**Comment by keyonghan** [comment]
A 32-core VM gives [relatively lower metrics](https://logs.chromium.org/logs/flutter/led/keyonghan_google.com/5d02c19fd1ed6744312e3a6f5598c9846588280bbb2fa2333cd1097d55ad565a/+/u/run_analyzer_benchmark/test_stdout), though not that much:
```
    "flutter_repo_batch": 157.02144266666667,
    "flutter_repo_batch_minimum": 155.004229,
    "flutter_repo_batch_maximum": 158.313348,
    "flutter_repo_watch": 155.359091,
    "flutter_repo_watch_minimum": 153.770459,
    "flutter_repo_watch_maximum": 156.545673,
    "mega_gallery_batch": 19.723341,
    "mega_gallery_batch_minimum": 18.779556,
    "mega_gallery_batch_maximum": 21.449513,
    "mega_gallery_watch": 19.044307333333336,
    "mega_gallery_watch_minimum": 18.900754,
    "mega_gallery_watch_maximum": 19.163864
```

https://github.com/flutter/flutter/pull/124147 to move it to a 8-core fleet as `bringup: true`.
