### ISSUE TITLE
Prefer command line settings to plist/androidmanifest settings

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#124049]
Right now the engine prefers some settings to the value in Info.plist even if the command line specifies a different value. This is almost certainly unexpected for developers manually specifying command line arguments.

We should change the code here https://github.com/flutter/engine/blob/95a962fea38bb27cba07edadb525857d1f712ae9/shell/platform/darwin/ios/framework/Source/FlutterDartProject.mm#L99 so that the settings are read from the command line _after_ the plist is parsed. Unfortunately, the settings for Android are handled in a few different spots and will have to be audited differently. We also have to audit whether the tool is ever specifying a setting explicitly with the default value or not.

For now, I am changing the behavior of this for `enable-impeller` to try to get it in for the next stable without too much disruption.

**Comment by chinmaygarde** [comment]
@jonahwilliams @zanderso Any opinions on changing this behavior now? I'm leaning towards keeping it consistent for now.

**Comment by jonahwilliams** [comment]
I'd just leave it the same, no one has really complained.

**Comment by chinmaygarde** [comment]
I clicked the wrong button when closing this. This wasn't closed as completed, instead it's closed as working as intended. Manifest preferences still take priority.
