### ISSUE TITLE
[cocoon] Stop monitoring flutter/plugins repo.

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#124050]
The `flutter/plugins` repo is [now archived](https://github.com/flutter/flutter/issues/113764), so there's no need that cocoon does anything with it. (The repo is still accessible from cocoon's "repo" dropdown.)

The ecosystem team uses now `flutter/packages` as the main mono-repo for work.

Feel free to remove `flutter/plugins` from cocoon whenever!

Thanks!

**Comment by keyonghan** [comment]
Cleaned up via https://github.com/flutter/cocoon/pull/2861.

**Comment by ditman** [comment]
Awesome, thanks @keyonghan!
