### ISSUE TITLE
WebViewClient Test Failing

### ISSUE THREAD

**Issue by jhewitt** [flutter/flutter#124032]
Tests on the WebViewClient are failing in the CI build when being built using fastlane.
[16:00:06]: ▸ io.flutter.plugins.webviewflutter.WebViewClientTest > onReceivedError FAILED
[16:00:06]: ▸ java.lang.ClassCastException at WebViewClientTest.java:50
[16:00:06]: ▸ io.flutter.plugins.webviewflutter.WebViewClientTest > urlLoading FAILED
[16:00:06]: ▸ java.lang.ClassCastException at WebViewClientTest.java:50
[16:00:06]: ▸ io.flutter.plugins.webviewflutter.WebViewClientTest > setReturnValueForShouldOverrideUrlLoading FAILED
[16:00:06]: ▸ java.lang.ClassCastException at WebViewClientTest.java:50
[16:00:06]: ▸ io.flutter.plugins.webviewflutter.WebViewClientTest > convertWebResourceRequestWithNullHeaders FAILED
[16:00:06]: ▸ java.lang.ClassCastException at WebViewClientTest.java:50
[16:00:06]: ▸ io.flutter.plugins.webviewflutter.WebViewClientTest > onPageStarted FAILED

**Comment by huycozy** [comment]
Hi @jhewitt 
In order to address the issue properly, please provide the information indicated below:
- Does the issue reproduce in the local environment? If so, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of `flutter doctor -v`
- The complete stack trace if any
- Which target environment did this issue happen in? (Android/iOS..)

Thanks!

**Comment by jhewitt** [comment]
This issue does not occur in the local environment, I do not run the pub unit tests when building locally.

jameshewitt@JenaMac HOL-SmartLink-Mobile % fvm flutter doctor -v
[!] Flutter (Channel stable, 3.7.9, on macOS 13.2.1 22D68 darwin-arm64, locale en-US)
    • Flutter version 3.7.9 on channel stable at /Users/jameshewitt/fvm/versions/3.7.9
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.17.6/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/jameshewitt/fvm/versions/3.7.9. Consider adding /Users/jameshewitt/fvm/versions/3.7.9/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 62bd79521d (5 days ago), 2023-03-30 10:59:36 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/jameshewitt/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.77.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • Jim’s iPhone 8 (mobile) • e72309dfcebe660adf8627801bf98da509523e93 • ios            • iOS 16.4 20E247
    • macOS (desktop)         • macos                                    • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)            • chrome                                   • web-javascript • Google Chrome 111.0.5563.146

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

I am running locally using fvm to control paths.

This is happening in GitHub actions when using fastlane to build the Android application, the iOS application is being built without issue.

**Comment by huycozy** [comment]
Thanks for your response. 
I also run [WebViewClientTest.java](https://github.com/flutter/packages/blob/main/packages/webview_flutter/webview_flutter_android/android/src/test/java/io/flutter/plugins/webviewflutter/WebViewClientTest.java) to check this in local and see all tests are passed. Which `webview_flutter` plugin version are you using? Does the issue happen on previous plugin version?
