### ISSUE TITLE
A few tests seem to not be running a lot less frequently and not backfiling

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#124018]
https://ci.chromium.org/p/flutter/builders/prod/Mac_ios%20native_platform_view_ui_tests_ios
https://ci.chromium.org/p/flutter/builders/prod/Linux%20web_tool_tests
https://ci.chromium.org/p/flutter/builders/prod/Linux_android%20flutter_gallery_v2_chrome_run_test

<img width="567" alt="Screenshot 2023-04-03 at 7 44 22 AM" src="https://user-images.githubusercontent.com/6343103/229544742-03cac973-da36-47ee-9f09-16539b7fab3d.png">

**Comment by drewroengoogle** [comment]
It looks like 3 of those tests didn't actually start, but were marked as started. I manually restarted them and will check to ensure the backfill endpoint triggers the gray tests.

@keyonghan I checked the logs and for each commit that had a test that wasn't updated, I found a log similar to:
```
Failed to update tasks when backfilling: DetailedApiRequestError(status: 503, message: The service was unable to fulfill your request. Please try again. [code=8a75])
```

**Comment by keyonghan** [comment]
Several fixes have been landed to fix the issue (earlier https://github.com/flutter/flutter/issues/122117), but seems we still hit this occasionally.

I will take this bug for further triage or fix.

Some ideas:
1) check pub/sub team what the error mean to us
2) retry scheduling when we hit such error

**Comment by keyonghan** [comment]
Based on past week's observation, these are several server errors we hit from our client side:

- Failed to update tasks when backfilling: BuildBucketException: [502]
- Failed to update tasks when backfilling: BuildBucketException: [504]: Request deadline exceeded
- Failed to update tasks when backfilling: Connection closed before full header was received
- Failed to update tasks when backfilling: DetailedApiRequestError(status: 502, message: No error details. HTTP status was: 502.)
- Failed to update tasks when backfilling: DetailedApiRequestError(status: 503, message: Policy checks are unavailable.)

**Comment by keyonghan** [comment]
After https://github.com/flutter/cocoon/pull/2589, we haven't seen any instance for days. Please reopen if it re-occurs.
