### ISSUE TITLE
Clipboard.getData: no documentation for possible "format" values, nor how to get "any" format

### ISSUE THREAD

**Issue by gisborne** [flutter/flutter#124073]
https://api.flutter.dev/flutter/services/Clipboard/getData.html:

> The format argument specifies the media type, such as text/plain, of the data to obtain.

Great. What possible values are there?

Also, I want to make a utility that will work with any clipboard value. How do provide a wildcard or otherwise receive any or all clipboard values?

**Comment by danagbemava-nc** [comment]
Hi @gisborne, text is the only format that the clipboard supports atm. Support for other formats is being tracked in https://github.com/flutter/flutter/issues/23603. 

Kindly subscribe to the issue linked above for updates. 

Closing from here as duplicate. 

Thank you
