### ISSUE TITLE
Performance regression

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#12403]
Looks like engine roll https://github.com/flutter/flutter/pull/12395 introduced a regression for two benchmarks:
* flutter_gallery_ios__transition_perf/frames missed_frame_build_budget_count
* flutter_gallery_ios__transition_perf/average_frame_build_time_millis

/cc @cbracken

**Comment by cbracken** [comment]
This was reverted in flutter/engine#4175

**Comment by cbracken** [comment]
Rolled in #12413
