### ISSUE TITLE
'flutter create' may be flakey

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter#12402]
My flutter sources include https://github.com/flutter/flutter/pull/12391, which adds at least one new IntelliJ configuration file, that defines an Android facet.

I'm trying to track down why new projects sometimes do not get an Android facet, which is required for Android Studio. After opening a debugger on AS and single-stepping to get the _exact_ command, I tried running it from the command line. Here's what I saw:
```bash
# /path/to/flutter --no-color create --template app --description "A new Flutter application." --org yourcompany.com flutter_app
Creating project flutter_app...
Wrote 62 files.
...
```
I deleted the `flutter_app` directory.
Later (after shutting down the debugger, among other things), I ran the same command again and got this:
```bash
# /path/to/flutter --no-color create --template app --description "A new Flutter application." --org yourcompany.com flutter_app
Creating project flutter_app...
Wrote 65 files.
...
```
So, 62 files the first time, 65 the second. The file I added to define the Android facet is one of the ones that is missing in the first run. 

When run from Android Studio it always writes 62 files. Out of dozens of tries, it wrote 65 files when run from the command line, with just one exception.
@devoncarew 

Edit: added absolute path indicator

**Comment by Hixie** [comment]
What are the files that are included sometimes and excluded sometimes?

What is the exact (github hash) version of the `flutter` tool run in both cases?

**Comment by stevemessick** [comment]
If you're asking whether I'm sure I was using the same `flutter` tool the answer is yes. The command generated by the IDE included an absolute path to `flutter` and I copied that to the command line to be sure it was the same. I don't include absolute paths in bug reports. The commit hash I'm currently using is 517315de487b28b46b516b2f14ae2dffc4a8ecac, from yesterday. That one does not have my PR in it, so it only writes 64 files. Still, 62 are generated from the IDE.

When I try to compare the contents I get unexplainable results. More than two files are added. I tried to interrupt the process during the `pub get` phase of `flutter create` but I'm not sure what Android Studio may have done to the project. Here's a zip file containing a project created by Android Studio (with the "ide" suffix) and one from the command line tool (the "cmdln" suffix).

[AndroidStudioProjects.zip](https://github.com/flutter/flutter/files/1357501/AndroidStudioProjects.zip)

**Comment by Hixie** [comment]
Some tools you might be able to use to determine what's going on:
* use `--verbose` on the tool command line to output more data
* instrument the `flutter create` handler to tell you which files it's outputting (if `--verbose` doesn't)
* put in a proxy Filesystem object (ask @tvolkert for help with this) so you can log every access to the file system and see what it's doing in the two cases

**Comment by devoncarew** [comment]
Without diving too deep into this, the `flutter create` command can 'repair' projects in place - you can run flutter create over an existing project and it'll regen missing files. Perhaps the count different - 62 sometimes and 65 others - is due to some of the files already existing before create is run? If you're generating into new directories each time then this wouldn't explain it.

Also - one caveat to working on the flutter tool - you do need to delete the cached snapshot after each change. This may not apply to template file changes, but can't hurt. I used to have local diffs to just never run the flutter tool from the snapshot; in lieu of that, you can delete `bin/cache/flutter_tools.snapshot`.

**Comment by Hixie** [comment]
(Alternatively, make sure you commit your changes locally each time. When working on the tool I always run the command as `amend && flutter ...` where `amend` is a script that amends the current commit.)

**Comment by stevemessick** [comment]
The IDE writes some files before running `flutter create`, which will not be overwritten. I must've started the IDE's project creator then interrupted it before running the command line that only wrote 62 files. Thanks for the debugging suggestions, that did help me figure out what's going on.
