### ISSUE TITLE
[Impeller] Vulkan backend on Android leads to graphical corruption.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#124040]
Flipping the flag from OpenGL to Vulkan yields graphical corruption with no Vulkan validation failures on an Android 7 device. This issue tracks an investigation of the fix.

The flag to flip the default from OpenGL to Vulkan is blocked on explaining and fixing this corruption.

**Comment by dnfield** [comment]
Can you share some screenshots? I noticed a lot of weirdness around text, has that been resolved?

**Comment by DavidKuennen** [comment]
@dnfield Tried impeller on the latest stable version and Text was not rendering at all correctly on Android, so I had to disable it.

**Comment by chinmaygarde** [comment]
@DavidKuennen Impeller is still very much WIP on Android/Vulkan as we are working towards exiting preview on iOS first.

**Comment by dnfield** [comment]
On the latest stable you're still getting the GL backend. It's fair to post issues there, although you're really better off making sure it still reproduces on master/main - but at that point you'll be getting Vulkan which is still a bit rough around the edges.

**Comment by DavidKuennen** [comment]
@chinmaygarde I see, thank you for this clarification and your hard work. Looking forward to give our users the better experience when it's ready. :-)
