### ISSUE TITLE
Global key error come and go with no time

### ISSUE THREAD

**Issue by simar1810** [flutter/flutter#124189]
```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building Overlay-[LabeledGlobalKey<OverlayState>#4a31e](state: OverlayState#27df8(entries: [OverlayEntry#5fdb2(opaque: true; maintainState: false), OverlayEntry#41328(opaque: false; maintainState: true), OverlayEntry#30238(opaque: true; maintainState: false), OverlayEntry#3bc4a(opaque: false; maintainState: true), OverlayEntry#88615(opaque: false; maintainState: false), OverlayEntry#14304(opaque: false; maintainState: true), OverlayEntry#52dd3(opaque: false; maintainState: false), OverlayEntry#cd91d(opaque: false; maintainState: true)])):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 1999 pos 12: '_elements.contains(element)': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///D:/wellnessz/lib/main.dart:27:14
When the exception was thrown, this was the stack: 
#2      _InactiveElements.remove (package:flutter/src/widgets/framework.dart:1999:12)
#3      Element._retakeInactiveElement (package:flutter/src/widgets/framework.dart:3892:30)
#4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3935:35)
#5      MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6512:36)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:3682:18)
#7      RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:6041:32)
#8      MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6537:17)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#11     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#13     StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#17     ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#20     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#21     ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#22     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#23     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#25     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#26     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#27     StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#30     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#31     ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#32     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#33     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#35     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#36     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#37     StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#40     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#41     ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#42     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#44     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#45     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#46     StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#47     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#48     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6384:14)
#49     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#50     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6384:14)
#51     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#53     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#54     ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#55     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#57     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#58     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#59     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2743:19)
#60     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:863:21)
#61     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
#62     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#63     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
#64     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1076:5)
#65     _invoke (dart:ui/hooks.dart:145:13)
#66     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
#67     _drawFrame (dart:ui/hooks.dart:112:31)
(elided 2 frames from class _AssertionError)
====================================================================================================

======== Exception caught by widgets library =======================================================
The following assertion was thrown while finalizing the widget tree:
Duplicate GlobalKeys detected in widget tree.

The following GlobalKeys were specified multiple times in the widget tree. This will lead to parts of the widget tree being truncated unexpectedly, because the second time a key is seen, the previous instance is moved to the new location. The keys were:
- [LabeledGlobalKey<_OverlayEntryWidgetState>#a5593]
  [LabeledGlobalKey<_OverlayEntryWidgetState>#92ad8]
This was determined by noticing that after widgets with the above global keys were moved out of their previous parent, that previous parent never updated during this frame, meaning that it either did not update at all or updated before the widgets were moved, in either case implying that it still thinks that it should have a child with those global keys.
The specific parent that did not update after having one or more children forcibly removed due to GlobalKey reparenting is:
- _Theatre(skipCount: 1, dependencies: [Directionality], renderObject: _RenderTheatre#6681d NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE DETACHED)
A GlobalKey can only be specified on one widget at a time in the widget tree.
When the exception was thrown, this was the stack: 
#0      BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:3083:15)
#1      BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:3108:8)
#2      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:866:19)
#3      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
#6      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1076:5)
#7      _invoke (dart:ui/hooks.dart:145:13)
```

**Comment by huycozy** [comment]
In order to address the issue properly, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well. Thank you!

**Comment by simar1810** [comment]
[√] Flutter (Channel stable, 3.7.7, on Microsoft Windows [Version 10.0.22621.1413], locale en-US)
    • Flutter version 3.7.7 on channel stable at C:\src1\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (4 weeks ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Asus\AppData\Local\Android\sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 8.1.0 (API 27) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.1413]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 111.0.5563.147
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 111.0.1661.62

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

**Comment by simar1810** [comment]
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:wellnessz/constants.dart';
import 'package:wellnessz/screens/home_screen.dart';
import 'package:wellnessz/screens/info_page.dart';
import 'package:wellnessz/screens/introduction_screen.dart';
import 'package:wellnessz/screens/login_screen.dart';
import 'package:wellnessz/screens/otp_page.dart';
import 'package:wellnessz/screens/splash_screen.dart';
import 'package:wellnessz/screens/welcome_screen.dart';
import 'package:wellnessz/widgets/loading_screen.dart';

import 'models/user_data.dart';

void main()  {
  // WidgetsFlutterBinding.ensureInitialized();
  runApp( WellnessZ());
}

class WellnessZ extends StatelessWidget {
  // const WellnessZ({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    try {
      return ChangeNotifierProvider(
        create: (context) => UserData(),
        child: MaterialApp(
          debugShowCheckedModeBanner: false,
          home: SplashScreen(),
          theme: ThemeData(
            primaryColor: kPrimeGreen,
            brightness: Brightness.light,
            fontFamily: 'Karla',
            colorScheme: ColorScheme.fromSwatch().copyWith(
                secondary: kHeavyGrey,
                primary: kPrimeGreen
            ),
          ),
          initialRoute: HomePage.id,
          // onGenerateRoute: (settings) {
          //   switch (settings.name) {
          //     case HomePage.id:
          //       return PageTransition(child:  const HomePage(), type: PageTransitionType.bottomToTop,duration: const Duration(milliseconds: 800));
          //     case WelcomeScreen.id:
          //       return PageTransition(child:  WelcomeScreen(), type: PageTransitionType.rightToLeft,duration: const Duration(milliseconds: 800));
          //     case InfoPage.id:
          //       return PageTransition(child:  InfoPage(), type: PageTransitionType.rightToLeft,duration: const Duration(milliseconds: 800));
          //     case IntroScreen.id:
          //       return PageTransition(child:  IntroScreen(), type: PageTransitionType.leftToRight,duration: const Duration(milliseconds: 800));
          //     case LoginScreen.id:
          //       return PageTransition(child:  LoginScreen(), type: PageTransitionType.bottomToTop,duration: const Duration(milliseconds: 800));
          //     case OtpPage.id:
          //       return PageTransition(child:  OtpPage(), type: PageTransitionType.bottomToTop,duration: const Duration(milliseconds: 800));
          //     case SplashScreen.id:
          //       return PageTransition(child:  SplashScreen(), type: PageTransitionType.leftToRight,duration: const Duration(milliseconds: 800));
          //
          //   // Add more cases for your app's routes here
          //     default:
          //       return null;
          //   }
          // },
          routes: {
            WelcomeScreen.id: (context) => WelcomeScreen(),
            InfoPage.id: (context) => InfoPage(),
            IntroScreen.id: (context) => IntroScreen(),
            LoginScreen.id: (context) => LoginScreen(),
            OtpPage.id: (context) => OtpPage(),
            HomePage.id: (context) => HomePage(),
            SplashScreen.id: (context) => SplashScreen(),
          },
        ),
      );
    }catch(e){
      AnimationController animationController = AnimationController(vsync: this as TickerProvider, duration: const Duration(milliseconds: 1200));
      return LoadingScreen(animationController);
    }
  }
}

**Comment by simar1810** [comment]
This is main.dart file, I have total of 8 screens with many widgets should i provide that also?

**Comment by huycozy** [comment]
Your sample code is containing undefined components/classes. For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Please provide such a sample.
