### ISSUE TITLE
flutter pub add a git dependency by git-ssh

### ISSUE THREAD

**Issue by tongzifang** [flutter/flutter#124107]
### Is there an existing issue for this?

- [x] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

flutter pub add my_package --git-url=git@git.myserver.com:fht/my_package.git --git-ref=0.0.1 --verbose

### Actual results

ERR : The --git-url must be a valid url: Illegal scheme character.

### Logs

ERR : The --git-url must be a valid url: Illegal scheme character.
    | 
    | Usage: pub add [options] [dev:]<package>[:descriptor] [[dev:]<package>[:descriptor]
    |        ...]
    | -h, --help               Print this usage information.
    |     --[no-]offline       Use cached packages instead of accessing the network.
    | -n, --dry-run            Report what dependencies would change but don't change
    |                          any.
    |     --[no-]precompile    Build executables in immediate dependencies.
    | -C, --directory=<dir>    Run this in the directory <dir>.
    | 
    | Run "pub help" to see global options.
    | See https://dart.dev/tools/pub/cmd/pub-add for detailed documentation.

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.7.7, on macOS 13.2.1 22D68 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.7.7 on channel stable at /Users/tongzi/FlutterDev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (4 周前), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/tongzi/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/tongzi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.76.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 111.0.5563.146

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

**Comment by tongzifang** [comment]
[   +8 ms] executing: sysctl hw.optional.arm64
[   +3 ms] Exit code 0 from: sysctl hw.optional.arm64
[        ] hw.optional.arm64: 1
[        ] executing: [/Users/tongzi/FlutterDev/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +7 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 2ad6cd72c040113b47ee9055e722606a490ef0da
[        ] executing: [/Users/tongzi/FlutterDev/flutter/] git tag --points-at 2ad6cd72c040113b47ee9055e722606a490ef0da
[  +20 ms] Exit code 0 from: git tag --points-at 2ad6cd72c040113b47ee9055e722606a490ef0da
[        ] 3.7.7
[   +4 ms] executing: [/Users/tongzi/FlutterDev/flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/stable
[        ] executing: [/Users/tongzi/FlutterDev/flutter/] git ls-remote --get-url origin
[   +6 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +12 ms] executing: [/Users/tongzi/FlutterDev/flutter/] git rev-parse --abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[        ] executing: sw_vers -productName
[   +8 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[   +8 ms] Exit code 0 from: sw_vers -productVersion
[        ] 13.2.1
[        ] executing: sw_vers -buildVersion
[   +7 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 22D68
[        ] executing: uname -m
[   +2 ms] Exit code 0 from: uname -m
[        ] arm64
[  +15 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +15 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +49 ms] executing: [/Users/tongzi/AndroidStudioProjects/qmzs_flutter_module/] /Users/tongzi/FlutterDev/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --color add
qmsd_flutter_user_feedback --git-url=git@git.zmcms.cn:fht/qmsd-flutter-user-feedback.git --git-ref=0.0.1 --verbose
FINE: Pub 2.19.4
ERR : The --git-url must be a valid url: Illegal scheme character.
    | 
    | Usage: pub add [options] [dev:]<package>[:descriptor] [[dev:]<package>[:descriptor]
    |        ...]
    | -h, --help               Print this usage information.
    |     --[no-]offline       Use cached packages instead of accessing the network.
    | -n, --dry-run            Report what dependencies would change but don't change
    |                          any.
    |     --[no-]precompile    Build executables in immediate dependencies.
    | -C, --directory=<dir>    Run this in the directory <dir>.
    | 
    | Run "pub help" to see global options.
    | See https://dart.dev/tools/pub/cmd/pub-add for detailed documentation.
FINE: Exception type: UsageException
FINE: package:args/command_runner.dart 448:7                 Command.usageException
    | package:pub/src/command/add.dart 446:9                 AddCommand._parseDescriptorOldStyleArgs
    | package:pub/src/command/add.dart 345:17                AddCommand._parsePackage
    | package:pub/src/command/add.dart 168:36                AddCommand.runProtected.<fn>
    | dart:_internal                                         ListIterable.toList
    | package:pub/src/command/add.dart 168:66                AddCommand.runProtected
    | package:pub/src/command.dart 190:45                    PubCommand.run.<fn>
    | dart:async                                             new Future.sync
    | package:pub/src/utils.dart 111:12                      captureErrors.wrappedCallback
    | package:stack_trace                                    Chain.capture
    | package:pub/src/utils.dart 124:11                      captureErrors
    | package:pub/src/command.dart 190:13                    PubCommand.run
    | package:args/command_runner.dart 212:27                CommandRunner.runCommand
    | package:pub/src/command_runner.dart 176:24             PubCommandRunner.runCommand
    | package:pub/src/command_runner.dart 161:20             PubCommandRunner.run
    | package:dartdev/dartdev.dart 49:47                     runDartdev
    | /opt/s/w/ir/x/w/sdk/pkg/dartdev/bin/dartdev.dart 11:9  main
    | ===== asynchronous gap ===========================
    | dart:async                                             Future.catchError
    | package:pub/src/utils.dart 111:52                      captureErrors.wrappedCallback
    | package:stack_trace                                    Chain.capture
    | package:pub/src/utils.dart 124:11                      captureErrors
    | package:pub/src/command.dart 190:13                    PubCommand.run
    | package:args/command_runner.dart 212:27                CommandRunner.runCommand
    | package:pub/src/command_runner.dart 176:24             PubCommandRunner.runCommand
    | package:pub/src/command_runner.dart 161:20             PubCommandRunner.run
    | package:dartdev/dartdev.dart 49:47                     runDartdev
    | /opt/s/w/ir/x/w/sdk/pkg/dartdev/bin/dartdev.dart 11:9  main
IO  : Writing 11200 characters to text file /Users/tongzi/.pub-cache/log/pub_log.txt.
MSG : Logs written to /Users/tongzi/.pub-cache/log/pub_log.txt.
[ +100 ms] "flutter add" took 215ms.
[   +2 ms] pub finished with exit code 64
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:586:7)
           <asynchronous suspension>
           #2      PackagesInteractiveGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:349:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +123 ms] ensureAnalyticsSent: 119ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 64

**Comment by darshankawar** [comment]
@tongzifang 
Looks like this need to be reported in dedicated repo: https://github.com/dart-lang/pub/issues.
Closing from here. If you get directed here, please write in comments and I'll reopen it.
