### ISSUE TITLE
FlutterWindowsEngineTest.TestExit is very flaky

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#124162]
It appears that most of the host unopt windows builders are having to retry to rerun this single test. I'm not sure if we have any automatic flakiness detection for these, but filling so we don't lose track of it.

For example: https://luci-milo.appspot.com/ui/p/flutter/builders/try/Windows%20Engine%20Drone/64316/overview

When these tests flake we have to rerun the entire shard, which may be constributing to windows capacity issues.

@yaakovschectman @cbracken

**Comment by loic-sharma** [comment]
This test was added by https://github.com/flutter/engine/pull/40802.@yaakovschectman could you investigate?

**Comment by jonahwilliams** [comment]
Yeah
