### ISSUE TITLE
web-wasm runtime error - Uncaught RuntimeError: unreachable

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#124148]
Core tracking bug in Dart: https://github.com/dart-lang/sdk/issues/52075

See this fork of the material 3 demo:
https://github.com/kevmoo/flutter_samples_fork/tree/web_wasm/experimental/material_3_demo

```
flutter build web --wasm
cd build/web_wasm
local_static_http_server
```

Toggle on "Brightness" or "Material 3" in the left sidebar

```
main.dart.wasm:0x2ab0d4 Uncaught RuntimeError: unreachable
    at __MaterialSwitchState&State&TickerProviderStateMixin&ToggleableStateMixin._handleTap.1 (main.dart.wasm:0x2ab0d4)
    at __MaterialSwitchState&State&TickerProviderStateMixin&ToggleableStateMixin._handleTap tear-off (main.dart.wasm:0x2ab0ee)
    at GestureRecognizer.invokeCallback (main.dart.wasm:0x211d3f)
    at TapGestureRecognizer.handleTapUp (main.dart.wasm:0x212f54)
    at BaseTapGestureRecognizer._checkUp (main.dart.wasm:0x212e3b)
    at BaseTapGestureRecognizer.acceptGesture (main.dart.wasm:0x21287d)
    at GestureArenaManager.sweep (main.dart.wasm:0x213594)
    at _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (main.dart.wasm:0x387064)
    at _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEventImmediately (main.dart.wasm:0x19f59c)
    at _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (main.dart.wasm:0x19ecb2)
```

```
Flutter 3.9.0-22.0.pre.8 • channel master • git@github.com:flutter/flutter.git
Framework • revision 50f7910e80 (87 minutes ago) • 2023-04-04 11:41:47 -0700
Engine • revision e860fa87d2
Tools • Dart 3.0.0 (build 3.0.0-406.0.dev) • DevTools 2.23.0
```

**Comment by eyebrowsoffire** [comment]
I looked at this briefly, but couldn't figure out the exact issue. Here's what I figured out. The following method in `ToggleableStateMixin` here:

```
  void _handleTap([Intent? _]) {
    if (!isInteractive) {
      return;
    }
    switch (value) {
      case false:
        onChanged!(true);
      case true:
        onChanged!(tristate ? null : false);
      case null:
        onChanged!(false);
    }
    context.findRenderObject()!.sendSemanticsEvent(const TapSemanticEvent());
  }
```
is being compiled to the following wasm:
```
  (func $__MaterialSwitchState&State&TickerProviderStateMixin&ToggleableStateMixin._handleTap.1 (;8573;) (param $var0 (ref $type11))
    local.get $var0
    ref.cast $type3825
    call $__MaterialSwitchState&State&TickerProviderStateMixin&ToggleableStateMixin.isInteractive
    i32.eqz
    if
      return
    end
    local.get $var0
    call $_MaterialSwitchState.value
    drop
    unreachable
  )
```
The switch statement is never being actually emitted, and instead an `unreachable` is emitted. I'm not sure why. I thought maybe somehow the switch on a nullable bool was confusing dart2wasm, but I tried to create a minimal reproducible case with this simple program:
```
import 'dart:math' as math;

bool? get value {
  final r = math.Random().nextInt(3);
  if (r == 0) {
    return true;
  } else if (r == 1) {
    return false;
  } else {
    return null;
  }
}

void main() {
    switch (value) {
      case false:
        print('false!');
      case true:
        print('true!');
      case null:
        print('null!');
    }
}
```
Unfortunately, that does not reproduce the issue, this code emits valid code for the switch statement. So I'm not 100% sure what it is about this code that is causing some part of the compile process (maybe TFA?) to choke.

**Comment by kevmoo** [comment]
This should be an issue in Dart land, too...right?

CC @askeksa-google

**Comment by osa1** [comment]
This is a dart2wasm bug so I copied the issue to https://github.com/dart-lang/sdk/issues/52075. We can close this one.

(I can't close it myself as I don't have the permission)

**Comment by kevmoo** [comment]
> This is a dart2wasm bug so I copied the issue to [dart-lang/sdk#52075](https://github.com/dart-lang/sdk/issues/52075). We can close this one.
> 
> (I can't close it myself as I don't have the permission)

We'll leave this open for tracking. Updated the top comment to link!

**Comment by osa1** [comment]
Fixed in https://github.com/dart-lang/sdk/commit/b180aa3c555751ac31ce2aee3435f687fc0a0e59.

**Comment by kevmoo** [comment]
Verified fixed!
