### ISSUE TITLE
[Proposal] Allow override double tap time out

### ISSUE THREAD

**Issue by juanmasilf** [flutter/flutter#124121]
## Use case

Hey! I'm writing a Flutter app to read Comics and Graphic novels. In this app the user can switch between pages by tapping the edges of the screen but also the user can double tap to zoom the page's image. I'm noticing that exists a delay between the user taps on the screen and the tap action is being triggered. This delay is caused by the DoubleTapGestureRecognizer because is waiting 300 milliseconds after the user taps the screen to decide if the user double tapped the screen or just tapped it once.

I want to increment the responsiveness of my switch between pages by reducing the amount of time that the DoubleTapGestureRecognizer takes to recognize if it is a double tap or not. I can't accomplish this because the number of milliseconds for the DoubleTapGestureRecognizer timer is a constants of the Flutter framework (`kDoubleTapTimeout`) making it imposible to override.

## Proposal

I propose to give the developer more control on the DoubleTapGestureRecognizer by making it overridable. Maybe it can be a named parameter on constructor.

Suggestion code:

```
class DoubleTapGestureRecognizer extends GestureRecognizer {
  /// Create a gesture recognizer for double taps.
  ///
  /// {@macro flutter.gestures.GestureRecognizer.supportedDevices}
  DoubleTapGestureRecognizer({
    super.debugOwner,
    super.supportedDevices,
    AllowedButtonsFilter? allowedButtonsFilter,
    double? doubleTapTimeout,
  }) : super(allowedButtonsFilter: allowedButtonsFilter ?? _defaultButtonAcceptBehavior);

 final double? doubleTapTimeout;
```

```
void _startDoubleTapTimer() {
    _doubleTapTimer ??= Timer(doubleTapTimeout ?? kDoubleTapTimeout, _reset);
  }
```

**Comment by huycozy** [comment]
Thanks for the detailed report! But this is a known issue being tracked at https://github.com/flutter/flutter/issues/106170. 

Closing this issue as a duplicate, so please follow up on it for further updates.
