### ISSUE TITLE
Elevated Buttons inside SliverAppBar don't respond to tap when pressing on icons or text inside the button.

### ISSUE THREAD

**Issue by vzegna** [flutter/flutter#124154]
[Summary]
The elevated buttons in my app stopped working properly after upgrading Flutter version to 3.7.8 stable.
The buttons don't respond to tap if they have children inside, such as text or icons inside or a combination of widgets within a column or row.
The buttons only respond to touch when pressing on an empty area within the button, and not directly on text or icons.
I haven't changed anything in my code and I have double checked it multiple times, I cannot find anything wrong with my ElevatedButtons. This seems like a framework issue.

[Reason for prioritization]
Users cannot reliably utilize features in the app because they cannot click on buttons, unless they click on empty space within the button, outside of the text area.

[Flutter doctor output]
flutter doctor -v
[✓] Flutter (Channel stable, 3.7.9, on macOS 13.3 22E252 darwin-arm64, locale en-US)
    • Flutter version 3.7.9 on channel stable at /Users/valentino/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 62bd79521d (5 days ago), 2023-03-30 10:59:36 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/valentino/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.77.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (5 available)
    • Pixel 6 Pro (mobile)        • 1C141FDEE005NN            • android-arm64  • Android 13 (API 33)
    • sdk gphone64 arm64 (mobile) • emulator-5554             • android-arm64  • Android 13 (API 33)
      (emulator)
    • iPhone XS Max (mobile)      • 00008020-000130A82600013A • ios            • iOS 16.4 20E247
    • macOS (desktop)             • macos                     • darwin-arm64   • macOS 13.3 22E252
      darwin-arm64
    • Chrome (web)                • chrome                    • web-javascript • Google Chrome
      111.0.5563.146

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by exaby73** [comment]
Hello @vzegna Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by vzegna** [comment]
After further investigation, I realized this issue only happens for ElevatedButtons (or IconButtons too) when they are placed inside a SliverAppBar. I will provide a sample code soon.
