### ISSUE TITLE
Question about google_sign_in package

### ISSUE THREAD

**Issue by hamzaj9** [flutter/flutter#124114]
Hello,

I got an email saying that Google detected the use of an embedded webview in requests to Google's OAuth 2.0 authorization endpoint in the past 120 days associated with one or more of your OAuth client IDs listed in this email.

we use google_sign_in package in our application. Does this package still use embedded webiew for Android or iOS?
Since any affected authorization endpoint requests will be blocked starting July 24, 2023.

**Comment by exaby73** [comment]
Hello @hamzaj9. Could you provide a little more details about the email you got? Any links to documentation that I can refer to? If you are sharing the contents of the email, please redact any sensitive information

**Comment by exaby73** [comment]
Thank you for the information :) Labelling the issue for insights from the team

**Comment by stuartmorgan** [comment]
> Does this package still use embedded webiew for Android or iOS?

The plugin wraps the native SDKs (`play-services-auth` and `GoogleSignIn` respectively); questions about how those SDKs are implemented would need to be addressed to the relevant products via their feedback channels.

(I'm not sure what you mean by "still" here, but the plugin has never directly used webviews on Android or iOS so far as I can see.)

**Comment by alexobviously** [comment]
We also got a similar email from google and the only method our app uses for google auth is `google_sign_in`.
