### ISSUE TITLE
Error copying from clipboard on ios devices

### ISSUE THREAD

**Issue by AcarFurkan** [flutter/flutter#124190]
I copy the product link from the application named n11 and try to paste it into the textfield, but it gives an error. When I try to get the same link from the clipboard, it prints as blank, but if I go to WhatsApp and paste it, I can paste it.
n11 app link:https://www.n11.com/

you can see this in the video
https://user-images.githubusercontent.com/65075121/230012390-77c20cde-c309-4719-843d-abb2cf344696.mp4
l just added a textfield initial application 
![WhatsApp Image 2023-04-05 at 10 49 07 AM](https://user-images.githubusercontent.com/65075121/230016089-1a9cfd9b-ffe4-4d37-966e-ac0153bcdab5.jpeg)

**Comment by huycozy** [comment]
Hi @AcarFurkan 
I checked this issue on iPhone 14 Pro, iOS 16.4 but can not reproduce this issue. The given url can be pasted.

<details>
<summary>Demo</summary>

<img width="400" src="https://user-images.githubusercontent.com/104349824/230050343-f405a33c-298f-4d12-b852-97d09d605c5d.png">

</details>

Which iOS device are you using? (OS, model) 
Also, what is the Flutter version that you are running? (Please provide the output of `flutter doctor -v`)

**Comment by huycozy** [comment]
I have tried installing n11 app but I don't have an account. Also, it doesn't seem to be working oversea. To make the issue actionable, in order to others can also investigate this, please provide the product link so that I may try it. Thanks!

**Comment by AcarFurkan** [comment]
l got it but if share product link it works l dont understand this part.

**Comment by AcarFurkan** [comment]
@huycozy  if you want you can try with my account
You can see how I did it in the video above.
email: furkanacaryedek@gmail.com
password: f123123123

**Comment by huycozy** [comment]
I can not log in with that account. Maybe it's limiting the region. You should check with other apps as well. If you are unable to see if it has any pattern with all apps, feel free to close the issue and write a comment when you have more information. Thanks!
