### ISSUE TITLE
Flutter enter in a weird state 

### ISSUE THREAD

**Issue by mazen930** [flutter/flutter#124115]
Whenever i run any flutter command : flutter doctor , flutter pub get ,etc .. 
i stuck in resolving dependency then it time out with failure message as 
```
pub get failed
command: "/Users/user_name/Flutter/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --color --directory ../../../Flutter/flutter/packages/flutter_tools get --example"
pub env: {
  "FLUTTER_ROOT": "/Users/user_name/Flutter/flutter",
  "PUB_ENVIRONMENT": "flutter_cli:get",
  "PUB_CACHE": "/Users/user_name/.pub-cache",
}
exit code: 69
```

This happens when install multiple plugins that i believe they are contradict with each other (dependency conflict) and flutter couldn't resolve them and was stuck so i upgrade versions to help it , after doing that i run flutter command the clean cached one then i become stuck in the mentioned above situation , (i even try to get back to normal one without any plugins but failed aslo )

**Comment by mazen930** [comment]
I will add here what i try so far but still not working 
 1- clear cache folder inside flutter/bin and do cache repair or even flutter doctor

**Comment by exaby73** [comment]
Hello @mazen930. Which version of Flutter are you running? If `flutter doctor -v` doesn't work, try running `flutter --version` and provide the output of either command

**Comment by exaby73** [comment]
Could you confirm that this is not because of your internet? If you have a proxy, or firewall set up, could you disable it and retry? 

Could you also try running `flutter precache -v` and provide any exceptions that is thrown, if any?

**Comment by mazen930** [comment]
After dig in i found that the server didn't reply to my requests (this happens when resolving dependencies takes place  ), however if i ping flutter.com it works fine , internet is also working fine , seems like the server ban my ip or something , so when i change it i t works fine ,(one thing to mention it was working just fine with old ip then suddenly it stops working)
Anyway i will close the commit , just one thing to say is it's good to have informative message as "Network error " or something as it mislead me
