### ISSUE TITLE
Use symlinks for Android flutter/dart dependencies 

### ISSUE THREAD

**Issue by reidbaker** [flutter/flutter#124124]
When working on https://github.com/flutter/flutter/issues/123917 I ran a scan of flutter/flutter/dev/integration-test/flutter_gallery
The result was https://scans.gradle.com/s/bm3mhj5ekf5bm/deprecations?expanded=WyIzIl0 
In that result gradle says that subproject/files outside the project root is deprecated and removed in gradle 8.0. 
https://docs.gradle.org/7.3.3/userguide/upgrading_version_7.html#deprecated_flat_project_structure

I believe that flutter uses symlinks inside the project for dependencies on build targets other than Android. If that is the case symlinks should be used in android projects. 

The result is that one of the major blockers preventing flutter users from adopting gradle 8.0 will be removed.

**Comment by reidbaker** [comment]
Potentially this is not an issue anymore? 
https://docs.gradle.org/7.4/userguide/upgrading_version_7.html#non_hierarchical_project_structures, https://github.com/gradle/gradle/pull/19135
h/t @stuartmorgan

**Comment by stuartmorgan** [comment]
From discussion in https://github.com/gradle/gradle/issues/18644 it seems like the gradle folks decided there wasn't a good replacement for certain use cases; hopefully if this is re-deprecated later, it will be in conjunction with some new option that might be a better fit for us.

(It's unclear to me if symlinks would actually have worked; it sounds like part of the motivation here was about being able to do file watching on a specific directory, and symlinks would presumably defeat that.)
