### ISSUE TITLE
Not working play sound

### ISSUE THREAD

**Issue by Srikaleeswarar** [flutter/flutter#124100]
I created audioplayers: ^3.0.1 plugin. Not playing sound.
final player = Audioplayers();
player.play(Assetsource("click.mp3");

error: 
resetdrmstate: mdrminfo=null mdrmprovisioningthread=null mpreparedrminprogress=false mactivedrmscheme=false

Please help me

**Comment by danagbemava-nc** [comment]
Hi @Srikaleeswarar, `audioplayers` is a third-party plugin. Any issues you face using it should be reported on their [repo](https://github.com/bluefireteam/audioplayers/issues?q=is:issue+is:open+sort:updated-desc). 

Closing from here as this is not a flutter issue. 

Thank you

**Comment by Srikaleeswarar** [comment]
Thankyou.
