### ISSUE TITLE
How to use process.start() to run an external command with root permission on macos? 

### ISSUE THREAD

**Issue by irocn** [flutter/flutter#124298]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I can't implement the below:

`Process.start("mycmd", []);` here, mycmd need root permission.

### Actual results

If I run the below:

`sudo open "/Applications/MyApp.app"`, it will have the following error infromation:

server aborted with Permission denied (os error 13)

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by darshankawar** [comment]
@irocn 
I think this issue need to be reported in https://github.com/dart-lang/sdk/issues.
Closing from here. If you get directed here, write in comments and I'll reopen it.
