### ISSUE TITLE
Clipping (SizedBox, Container, AnimatedContainer, ...) has weird front-clipping

### ISSUE THREAD

**Issue by devingryu** [flutter/flutter#124283]
What I'm trying to do is stacking exact same bordered text, and clipping one of them to partially color it.
Below is the code.
```dart
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final String text = "Hello World!";

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Stack(
          children: [
            BorderedText(
              text: text,
              fill: Colors.white,
              border: Colors.blue,
            ),
            SizedBox(
              width: 120,
              child: BorderedText(
                text: text,
                fill: Colors.blue,
                border: Colors.white,
              ),
            )
          ]
      )
          ),
    );
  }
}

class BorderedText extends StatelessWidget {
  const BorderedText({Key? key, required this.text, required this.fill, required this.border}) : super(key: key);
  final String text;
  final Color fill;
  final Color border;

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: <Widget>[
        Text(
          text,
          maxLines: 1,
          softWrap: false,
          overflow: TextOverflow.clip,
          style: TextStyle(
              fontSize: 40,
              foreground: Paint()
                ..style = PaintingStyle.stroke
                ..strokeWidth = 10
                ..color = border
          ),
        ),
        Text(
          text,
          maxLines: 1,
          softWrap: false,
          overflow: TextOverflow.clip,
          style: TextStyle(
              fontSize: 40,
              color: fill
          ),
        ),
      ],
    );
  }
}
```
![First output](https://user-images.githubusercontent.com/79868575/230230936-c3801c73-38ea-497c-b275-55ac00d2f5b2.png)
This is the output, and you can see that the front is clipped.
If i set the width larger than the text width, it is showing properly.
![Second output](https://user-images.githubusercontent.com/79868575/230231268-a1ba6bde-4c3f-4215-a535-ca675b4ac8a4.png)

This is sticking out when I set the text to other language
![third output](https://user-images.githubusercontent.com/79868575/230231610-d655b9ab-d58c-47a3-abbe-f76b3ef3aa07.png)

What could be the problem? Thanks in advance.

-- Edit
flutter doctor result
```bash
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.10, on Microsoft Windows [Version 10.0.22621.1413], locale ko-KR)
[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.3)
[√] Android Studio (version 2022.2)
[√] Connected device (3 available)
[√] HTTP Host Availability
```
OS: Windows 11 22H2
Device: Mi 12 Lite(Taoyao, Android 13), Pixel 3a API 33

**Comment by danagbemava-nc** [comment]
Hi @devingryu, I think wrapping the whole `Stack` with the `SizedBox` will yield the results you expect instead of just one of the stack children. 
This might be due to how the `Stack` layout works. See https://api.flutter.dev/flutter/widgets/Stack-class.html & https://api.flutter.dev/flutter/rendering/RenderStack-class.html for more information regarding this. 

| Your code sample | Wrapping the main stack with a SizedBox (without specifying any width/height) |
| -- | -- |
| <img width="610" alt="Screenshot 2023-04-06 at 08 35 56" src="https://user-images.githubusercontent.com/88313112/230322381-6ff6a9fe-e293-4086-b90e-b6fd9e81702c.png"> | <img width="610" alt="Screenshot 2023-04-06 at 08 36 21" src="https://user-images.githubusercontent.com/88313112/230322399-1ea92f64-5ff1-4c1b-b017-3729f03b070e.png"> |

**Comment by danagbemava-nc** [comment]
Can you check if https://stackoverflow.com/questions/71368043/create-karaoke-effect-flutter offers any hints that might be helpful to you?

**Comment by devingryu** [comment]
> Can you check if https://stackoverflow.com/questions/71368043/create-karaoke-effect-flutter offers any hints that might be helpful to you?
This suggests exactly the same way I tried.

> This might be due to how the Stack layout works. See https://api.flutter.dev/flutter/widgets/Stack-class.html & https://api.flutter.dev/flutter/rendering/RenderStack-class.html for more information regarding this.
Actually I found out that this issue is not with the stack but with clipping and custom Paint. Just a clipping single BorderedText with SizedBox works weird.
Back in 2021(flutter 1.22.5), when I tried exact same task, I didn't suffered with this issue. Even the code I'm trying is exactly the same. This is what I captured in 2021.01.17.
![image](https://user-images.githubusercontent.com/79868575/230446247-68155d7d-4d7b-4eeb-b5d2-d6a095bb1ef0.png)

So I'm pretty sure this is the bug of the SDK.

**Comment by devingryu** [comment]
Probable the best option I can choose currently is wrapping BorderedText with ClipRect.
It's still clipping the front, but the difference is both of them are clipped.
However, the another issue is that now it clips the end.

![image](https://user-images.githubusercontent.com/79868575/230640107-bbda2e46-b0c0-4206-8a7b-7ed9beedd76d.png)

I'm not sure why this is actually happening, but it seems that calculating width of the text with foreground style is related.
`TextPainter` doesn't count foreground style when calculating the width, so it seems that this behavior is pretty natural if clipping widgets use it to get size.

**Comment by danagbemava-nc** [comment]
Hi @devingryu, can you provide the new code sample using ClipRect? 

Btw, have you tried creating your own RenderObject for this? I think you might have more control over the sizes and styles as compared to using the `Stack` widget in this case.

**Comment by devingryu** [comment]
> can you provide the new code sample using ClipRect?

I just wrapped BorderedText widget with ClipRect.
```Dart
class BorderedText extends StatelessWidget {
  const BorderedText(
      {Key? key, required this.text, required this.fill, required this.border})
      : super(key: key);
  final String text;
  final Color fill;
  final Color border;

  @override
  Widget build(BuildContext context) {
    return ClipRect(child:
      Stack(
        children: <Widget>[
          Text(
            text,
            maxLines: 1,
            softWrap: false,
            overflow: TextOverflow.clip,
            style: TextStyle(
                fontSize: 60,
                foreground: Paint()
                  ..style = PaintingStyle.stroke
                  ..strokeWidth = 10
                  ..color = border),
          ),
          Text(
            text,
            maxLines: 1,
            softWrap: false,
            overflow: TextOverflow.clip,
            style: TextStyle(fontSize: 60, color: fill),
          ),
        ],
      )
    );
  }
}
```

> Btw, have you tried creating your own RenderObject for this? I think you might have more control over the sizes and styles as compared to using the Stack widget in this case.

I could, but making custom RenderObject should be chosen as a last resort.

**Comment by devingryu** [comment]
> So I went back to stable 2.10.5. and below is what I see. I presume these are the behaviours you expected, is that correct?

Yes, that’s what I’m currently getting. But it’s not exactly what I want.
The right screenshot appears to work well because it clips both blue and white text. However, upon closer inspection, it looks different if you compare with unclipped text. You can see the output in the comment I posted 4 days ago.

My point is, I think this clipping behavior is a bug, since it was not happening in Flutter 1.X.X.
I may just use clipped text, so you may not think about my problem. However, if this behavior is a bug, you should mark this as a bug (and probably fix this later).
So, is this behavior a bug or not?

**Comment by danagbemava-nc** [comment]
Hi @devingryu, I'm can't say for sure, that's what I'm trying to confirm. I checked on flutter 1.22.5 and I see nearly the same behaviour as I showed previously. 

| without clipping the stack | clipping the stack | 
| -- | -- |
| <img src="https://user-images.githubusercontent.com/88313112/231395592-99697fe3-d8fa-4025-9408-89d6f68da705.PNG" /> | <img src="https://user-images.githubusercontent.com/88313112/231395570-42ffab8d-146f-46a0-bc6e-5a5c85b011b6.PNG" /> |

**Comment by danagbemava-nc** [comment]
Could you update us when you're able to? 

Thank you
