### ISSUE TITLE
Support running tests on a device

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter#12427]
## Steps to Reproduce

- `flutter test` runs tests only on the host machine  
- `flutter drive` requires the tests to run outside the device but allows to remote control code that runs on the device (that's pretty close but very cumbersome)  
- `flutter run -t test/my_device_test.dart` does run the tests fine, but doesn't exit after the tests are completed and I wasn't able to find a way to exit with an code != 0 when tests fail.

The last option would be perfectly fine for me, if it properly reported failed tests with an exit code != 0. Currently I can exit in `tearDownAll(() => exit(0))` and then parse the console output for test failures.

I want to run some tests that actually hit the Firebase database.
This is probably useful for other tests that depend on plugins where the plugin implementation shouldn't be mocked out.

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-AT, channel alpha)
    • Flutter at /Users/zoechi/flutter/flutter
    • Framework revision 701d534ba9 (3 weeks ago), 2017-09-12 14:01:51 -0700
    • Engine revision 31d03de019
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /usr/local/opt/android-sdk
    • Platform android-26, build-tools 26.0.1
    • ANDROID_HOME = /usr/local/opt/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.0, Build version 9A235
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.5)
    • Flutter plugin version 17.0
    • Dart plugin version 172.4155.35

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)
```

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by Hixie** [comment]
You can use `flutter drive` with a trivial driver script that doesn't do anything except wait for the process to announce it's done on the device.

Unfortunately not all our target platforms support closing a process. (Specifically, you can't quit a process on iOS. Doing so causes the OS to act as if the process had crashed.)

**Comment by zoechi** [comment]
@Hixie thanks! Seems to work fine.

**Comment by swissonid** [comment]
Hi, @zoechi 
would it be possible to share how you have done the solution mention by @Hixie ?
That would be nice. Because I'm sitting right now in the same situation as you did.

**Comment by zoechi** [comment]
@swissonid I wrote tests and treated that file containing the tests like the application code driven by `flutter drive`

```dart
main() {
  enableFlutterDriverExtension();
  printLog(logLevel ?? Level.FINE);

  tearDownAll(() {
// Make the app exit at the end. The test runner can't do this by itself.
// The test runner needs some time to get the result printed, thus the delay.
    Future.delayed(const Duration(milliseconds: 50), () => exit(0));
  });

  /// tests go here
}
```
The driver test file is just
```dart
import 'dart:async';

import 'package:flutter_driver/flutter_driver.dart';

Future<void> main() async {
  await FlutterDriver.connect();
}
```

**Comment by swissonid** [comment]
Thx @zoechi worked for me. Only from curiosity do you know a way to keep the connection open and profit from the hot reload feature. That would catapult the TDD workflow into a new level.

**Comment by zoechi** [comment]
Run the test (the one with `enableFlutterDriverExtension()`) with `flutter run` instead of `flutter drive`. 
You'll need to comment or mark as skipped the tests you are not currently working on to only run a single test.

**Comment by swissonid** [comment]
Thx a lot. It works just perfectly. 👍

**Comment by dan-leech** [comment]
It worked but now I get error: `file:///home/dan/Android/FlutterSDK/flutter/packages/flutter/lib/src/semantics/binding.dart:5:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui show AccessibilityFeatures;`

When run "The driver test file" `flutter drive --target=test_driver/main.dart`

Any idea how make it work?

**Comment by dan-leech** [comment]
It seems all works with `flutter run -t test_driver/main_test.dart` and it uses `test_driver/main.dart`

**Comment by devxpy** [comment]
@Hixie Is it possible to run the *driver script* on the device too?

This restriction of driver scripts only running on the host means its impossible to share any flutter code between driver and the app.

**Comment by devxpy** [comment]
Petition to be able to call private methods in [extension.dart](https://github.com/flutter/flutter/blob/master/packages/flutter_driver/lib/src/extension/extension.dart)!
