### ISSUE TITLE
"Google testing" failing because tests include g3fix but not the open source change

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#124246]
For example in cl/522070961 it is applying a g3fix I created for https://github.com/flutter/flutter/pull/124039 so the Google testing CL DOES have internal change, but it does NOT have the open source change, because FRoB does not by default include a PR's base commit and #124039 has not yet rolled internally.

**Comment by christopherfujino** [comment]
Ahh ok, I think  cl/522089421 by @CaseyHillers will temporarily work around this by not applying my g3fix to PRs.

But then, I think "Google testing" will again starting failing once #124039 rolls.

**Comment by CaseyHillers** [comment]
@christopherfujino can this be closed?

**Comment by christopherfujino** [comment]
I'm seeing green google testing checks so I think so

**Comment by CaseyHillers** [comment]
Thanks for confirming. For future archaeologists, the internal bug is b/276657506 which has the related fixes and investigation.
