### ISSUE TITLE
MaterialRectCenterArcTween motion doesn't match spec

### ISSUE THREAD

**Issue by Sfshaza** [flutter/flutter#12422]
If you look at the upward and downward arc in the [Material motion spec](https://material.io/guidelines/motion/movement.html#movement-movement-within-screen-bounds), and compare it to the motions for `MaterialRectCenterArcTween`, you'll see that the downward arc motion doesn't match the spec.  (Chris B noticed this.  ;) )

It would be nice if the developer could choose the arc's behavior (concave or convex...) but I guess that wouldn't match the material design spec either.

@cbracken

**Comment by markusaksli-nc** [comment]
Hi @cbracken 
Is this issue still valid? The referenced spec link no longer provides us an example to check this and there is no sample code to compare it to the current spec.
Thank you

**Comment by markusaksli-nc** [comment]
Closing this issue for now since it no longer seems relevant. If there is a problem here compared to some part of the current material design spec feel free to link it and reopen.
