### ISSUE TITLE
[pigeon] Java `Result<T>` doesn't allow communicating nullability

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#124268]
As far as I can tell there's no way to pass nullability annotations through a generic in Java. To allow for expressing nullability of return values, we should make a breaking change to add a new `NullableResult<T>`, which is the same as `Result<T>` except for the annotations we put on the argument to `success`. (The breaking part being that some methods that currently have a `Result` parameter will change to a `NullableResult` parameter.)

For now I'm suppressing the `UnknownNullability` warning on `Result<T>`'s `success` method.

@tarrinneal I think we should do this at the same time we replace `Reply` with `Result` for https://github.com/flutter/flutter/issues/118243 since we'll be making a related breaking change for Java at that point (although this one will affect more code).

**Comment by tarrinneal** [comment]
@stuartmorgan is error suppression worse than added boilerplate and complexity? Is it required for kotlin compat?

**Comment by stuartmorgan** [comment]
It's not just about suppressing the error, it's about not being able to accurately express the nullability semantics.

> worse than added boilerplate and complexity

The boilerplate should just be a small amount of Pigeon-generated Java; since generating boilerplate to increase type safety is literally the whole point of Pigeon, that tradeoff seems reasonable to me 🙂  The added complexity for the client seems smallish; not ideal, but making it impossible to express the correct semantics seems worse to me. (This is something I really dislike about the Obj-C generator when I use it, actually; all returns are nullable even when they aren't because of the out-error patterns that is standard for Obj-C. We can't fix it there without doing something very non-idiomatic, but we can here.)

> Is it required for kotlin compat?

To have the correct nullability in the types for any Kotlin code interacting with this, yes. (That's probably not a major consideration though, since I imagine people who are consuming this code from Kotlin are using the Kotlin generator.)
