### ISSUE TITLE
Golden tests running with impeller like `impeller_Play_AiksTest_CanRenderSweepGradientManyColorsRepeat_Metal` are flaky

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#124295]
I'm surprised this iOS embedder memory leak fix kicked off a `flutter gold` check, and even more surprised it caused `Golden file changes have been found for this pull request.`

https://github.com/flutter/engine/pull/40957

**Comment by jmagman** [comment]
The unexpected `flutter gold` check is still pending and blocking the PR: https://github.com/flutter/engine/pull/40957

**Comment by keyonghan** [comment]
@Piinks Could you help take a look?

**Comment by Piinks** [comment]
I believe the image is flaky, I filed https://github.com/flutter/flutter/issues/124277

@mdebbar maintains the engine instance of Gold.

**Comment by mdebbar** [comment]
I took a look at the failing goldens: https://flutter-engine-gold.skia.org/search?crs=github&issue=40957&negative=true&patchsets=1&positive=true

They fall in 2 buckets:

1. Images with tiny differences from their golden baseline (e.g. [this](https://flutter-engine-gold.skia.org/diff?grouping=name%3Dimpeller_Play_AiksTest_CanRenderSweepGradientManyColorsMirror_Metal%26source_type%3Dflutter-engine&left=4abc84c36564effcf2d8de10c1bc32a4&right=585f87c6dd02f25becb7318e4a3882ff&changelist_id=40957&crs=github): new pixel is `#C42AA3` vs baseline pixel `#C426A3`. This is correctly auto-approved by `fuzzy`.
2. Images with a pixel that's drastically different from the baseline (e.g. [this](https://flutter-engine-gold.skia.org/diff?grouping=name%3Dimpeller_Play_AiksTest_CanRenderSweepGradientManyColorsRepeat_Metal%26source_type%3Dflutter-engine&left=bcd0f949323cf4e6c2ca47017953482d&right=1159e3a44da94916772887889d193c3e&changelist_id=40957&crs=github): new pixel is `#FFDBAF` vs baseline pixel `#6200A2`). Look at the highlighted pixel in the center:

| New | Baseline |
|-|-|
| ![image](https://user-images.githubusercontent.com/1278212/231548043-8f8d0f39-8f52-479b-9cb6-d73885105193.png) | ![image](https://user-images.githubusercontent.com/1278212/231548150-76445822-2320-4945-97d2-d30ae104b90e.png) |

Unfortunately, Gold's fuzzy matching doesn't handle this case well.

That said, this feels like a flakiness in impeller that needs to be addressed. The specific pixel sometimes gets painted yellow, and sometimes purple.

**Comment by chinmaygarde** [comment]
From Triage: We discussed this w.r.t what to do with gold tests that run on results obtained from a specific GPU. We are not going to guarantee pixel perfect results across GPUs (even from a specific vendor). Based on guidance from the Skia GPU team, the amelioration was that the Gold failures be reasoned about out-of-band and neither the autorollers or the presubmit checks block PRs. I believe this has been done already. You should not see a red check mark on your presubmits and the autorollers should not care about this difference. The delta will still be triaged as I said, but out of bank.

> and blocking the PR.

Did you see the gold failures trigger a red check or was it in the pending state? Also, was the autosubmit/autoroller refusing to process this?

Dan (OOO) also had WIP where gold would instances would only use a specific GPU type. But I am not sure that work was done. In any case, this shouldn't block PRs.

cc @gaaclarke.

**Comment by Piinks** [comment]
> Dan (OOO) also had WIP where gold would instances would only use a specific GPU type. But I am not sure that work was done. 

Would it be easier to specify the GPU as a parameter for the golden file image? Gold supports thousands of params for image tests, we could just have separate images for each GPU by adding the GPU as a key of the image.

**Comment by Piinks** [comment]
These are the current params I can see we differentiate images for in the engine instance:

![image](https://user-images.githubusercontent.com/16964204/232568108-2fb3db04-6bc1-4c72-8571-fdb5d2b29204.png)

**Comment by gaaclarke** [comment]
@Piinks Here is what dan's PR is doing: https://github.com/flutter/engine/pull/41216/files#diff-356abf8d8d08b3ba08c35d6399e2a21d3107aa16c55f4303bb3b8f96195bbcc0R239

The code looks good, but I'm not sure if that's going to give us the result we want in skia gold (it sounds like it?)

**Comment by Piinks** [comment]
Oh nice, that looks like exactly that, although slightly different, I'll leave mention on the PR. :+1:

**Comment by chinmaygarde** [comment]
This is WAI.  The ameliorations for different GPU returning different results were that the golden runs were being checked out of band, a global conservative fuzz factor applied to gold checks, and the restriction of devices that can perform these gold checks (most notably removing the Intel Iris devices).
