### ISSUE TITLE
Keyboard instantly disappears when entering a Text Field in a dialog 

### ISSUE THREAD

**Issue by andrewpmoore** [flutter/flutter#124265]
I've been struggling with an issue where I've got an `AlertDialog` with a `TextField` but every time the keyboard pops and the screen resizes the keyboard instantly disappears. The `TextController` is held in state.

Looking for solutions I've found exactly the same thing with tutorials on the web for this. For example 

`import 'package:flutter/material.dart';
void main() => runApp(MyApp());

    class MyApp extends StatelessWidget {
        // This widget is the root of your application.
        @override
        Widget build(BuildContext context) {
            return MaterialApp(
                title: 'Flutter Alert Demo',
                debugShowCheckedModeBanner: false,
                theme: ThemeData(
                    primarySwatch: Colors.blue,
                ),    
                //home: MyHomePage(title: 'Flutter Demo Home Page'),
                home: AlertDialogTextField(),
            );
        }
    }
    class AlertDialogTextField extends StatelessWidget {
        TextEditingController _textFieldController = TextEditingController();

        _displayDialog(BuildContext context) async {
            return showDialog(
                context: context,
                builder: (context) {
                    return AlertDialog(
                        title: Text('AlertDemo with TextField '),
                        content: TextField(
                            controller: _textFieldController,
                            decoration: InputDecoration(hintText: "Enter Text"),
                        ),
                        actions: [
                            new FlatButton(
                                child: new Text('SUBMIT'),
                                onPressed: () {
                                    Navigator.of(context).pop();
                                },
                            )
                        ],
                    );
                }
            );
        }

        @override
        Widget build(BuildContext context) {
            return Scaffold(
                appBar: AppBar(
                    title: Text('Alert Dialog Demo'),
                ),
                body: Center(
                    child: FlatButton(
                        child: Text(
                            'Show Alert',
                            style: TextStyle(fontSize:  20.0 ),),
                            padding: EdgeInsets.fromLTRB(20.0,12.0,20.0,12.0),
                            shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(8.0)
                            ),
                            color: Colors.blue,
                            onPressed: () => _displayDialog(context),
                        ),
                    ),
                );
            }
        }

`

This is running on an Android Pixel 6 pro (android 13) on Stable 3.7.10. 

I've tried using Global keys, TextFormFields etc, but all exhibit the same issue of as soon as the text field is in focus, the keyboard shows for a split second and goes again.

**Comment by huycozy** [comment]
Hi @andrewpmoore 
I'm checking this on `Samsung Galaxy Tab A7 Lite, Android 13 OneUI 5.0, SM-T225` but can't see the issue. When the keyboard shows up, it still persists then I can enter the text normally. 

Could you provide a recorded video of the wrong behavior? (Also, it doesn't seem to be related but I just add here that your sample code is using a deprecated `FlatButton`, need to update it to be compatible with new Flutter SDK)

**Comment by andrewpmoore** [comment]
@huycozy Yeah it was an old tutorial I attached as it exhibits the same issue as my app and was easier to attach without cutting my app down to a small recruitable bit of code. Other tutorials of doing this also do the same.

https://user-images.githubusercontent.com/1093845/230414128-10a4dc8d-42d4-4442-a86a-5b3e408b254a.mp4

Here's the output of flutter doctor
```
[√] Flutter (Channel stable, 3.7.10, on Microsoft Windows [Version 10.0.25314.1010], locale en-GB)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.0)
[√] Android Studio (version 2022.1)
[√] Android Studio (version 2022.2)
[√] VS Code (version 1.64.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

```
