### ISSUE TITLE
[CP] Always set orientation preferences on iOS 16+

### ISSUE THREAD

**Issue by burghoffdavid** [flutter/flutter#124208]
### issue_link

https://github.com/flutter/flutter/issues/116711

### Commit Hash

[dd1dc7](https://github.com/flutter/engine/commit/dd1dc7258b996af218c49c3f69a5f3ea95d6546f)

### Target

stable

### pr_link

https://github.com/flutter/engine/pull/40953

### Impacted Users

iOS apps running iOS 16+ that should be locked to portrait.

### Impact Description

Apps that were designed with only one orientation in mind currently break, since locking the orientation via Flutter is not working at the moment.

### Workaround

None AFAIK

### Risk

low

### Test Coverage

yes

### Validation Steps

1. `flutter create app`
2. Open it in XCode, check "Requires Full Screen"
![Screenshot 2023-04-05 at 16 23 01](https://user-images.githubusercontent.com/37399963/230110659-63d9268a-d95a-45f6-a7b4-b702bb5ed207.png)

4. Add the following to main.dart
````dart
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
  ]);
  runApp(const MyApp());
}
````
5. Launch App on any iPad running iOS 16+
6. Check if orientation is locked (Landscape not possible)

**Comment by itsjustkevin** [comment]
Round 2 @jmagman!  Could you give this one a quick look?

**Comment by jmagman** [comment]
This request is incorrectly targeting the engine->framework roll instead of the engine, I'll update the description with all the correct links.

This was requested enough it's probably worth hotfixing.

**Comment by jmagman** [comment]
@burghoffdavid are you sure you're requesting that https://github.com/flutter/engine/pull/38230 be cherry-picked? That fixed https://github.com/flutter/flutter/issues/116711 which isn't specific to iPads.  You originally linked to https://github.com/flutter/flutter/issues/121007 which is really https://github.com/flutter/flutter/issues/119473 which was pointed out in https://github.com/flutter/flutter/issues/119473#issuecomment-1408393814 to be https://github.com/flutter/flutter/issues/111587 which I already said probably isn't worth a hotfix https://github.com/flutter/flutter/issues/121107#issuecomment-1472396570.

**Comment by burghoffdavid** [comment]
Hey first of all sorry for the confusion 🙈  

I just double checked: 
1. Switched to flutter stable (`flutter --version` output): 
````
Flutter 3.7.9 • channel stable • git@github.com:burghoffdavid/flutter.git
Framework • revision 62bd79521d (6 days ago) • 2023-03-30 10:59:36 -0700
Engine • revision ec975089ac
Tools • Dart 2.19.6 • DevTools 2.20.1
````
2. `flutter create appstable`
3. Add SystemChrome call as mentioned above:
 ````dart
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
  ]);
  runApp(const MyApp());
}
````
4. Open it in XCode, check "Requires Full Screen"
5. Run App on both iPad + iPhone 
6. Result: iPhone stays in portrait up, while iPad ignores system chrome settings
![Screenshot 2023-04-05 at 23 27 33](https://user-images.githubusercontent.com/37399963/230215471-beaa9e98-b7b4-467f-a35b-f17fff3f087d.png)

I then switched to the cherry picked branch :
````
Flutter 3.7.11-0.0.pre.1 • channel
cp-ios-16-orientation-fix-ipad •
git@github.com:burghoffdavid/flutter.git
Framework • revision 8685dd6a26 (4 months ago) • 2022-12-13
16:15:18 -0500
Engine • revision dd1dc7258b
Tools • Dart 3.0.0 (build 3.0.0-19.0.dev) • DevTools 2.20.0
````

I then created a new app, with the same adjustments in XCode + main mentioned above. This time, the iPad stayed in portrait:

![Screenshot 2023-04-05 at 23 34 03](https://user-images.githubusercontent.com/37399963/230216896-f7484899-ceed-4a7c-abb3-536e66287de2.png)

Therefore the cherry pick seems to be fixing the issue I was encountering and it seems to specific to iPads. 

Let me know if this cleared it up or if you need anything else.

**Comment by jmagman** [comment]
Updated all the links in the description.  Engine cherry-pick at https://github.com/flutter/engine/pull/40953/.

@itsjustkevin I think we should take this one for the next stable hotfix.  🙂

**Comment by CaseyHillers** [comment]
Released in https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel#3711-apr-12-2023
