### ISSUE TITLE
App doesn't throw error when null value is provided to GridView.builder and ListView.builder and IDE will be 50-80% slower

### ISSUE THREAD

**Issue by TheGlorySaint** [flutter/flutter#124203]
@ Moderator || please change Title when this one is not right. I was also thinking about Title: Can't provide null to GridView.builder or ListView.builder.

When using an `GridView.builder` or `ListView.builder` (I only have tested it with those, but logical every similar Widget should be effected) and null is provided to the Widget, then no exception is thrown. The `itemCount` is nullable so, I expect, null can be provided. While that issue leaves the screen blank when building new or freezes, the preferred IDE, in my case VS Code, but effects also Android Studio, will get slower for about 50 to 80%.

Found on latest Stable, Master and Dev

## Steps to Reproduce

1. Clone reproducible issue from https://github.com/TheGlorySaint/GridViewListViewNoError
2. Execute `flutter run` on the code sample
3. Code should run fine
4. Now uncomment line 50 to 63 and/or 78 to 84
5. Save File
6. Hot Reload, Hot Restart or build App completely new
7. IDE (VS Code or Android Studio) will get 50-80% slower, for example when wanting to terminate Simulator, with "Debugger Stop Button"

**Expected results:**

Either that you can provide null to the ListView/GridView.builder or that you can't provide null and an error/exception is thrown white the null value used text.

**Actual results:**
You can't provide null to ListView/GridView.builder and/or there is no exception/error thrown.

<details>
<summary>Code sample</summary>

https://github.com/TheGlorySaint/GridViewListViewNoError
</details>

<details>
  <summary>Logs</summary>

```
flutter doctor -v
[✓] Flutter (Channel master, 3.9.0-22.0.pre.28, on macOS 13.3 22E252 darwin-arm64, locale de-DE)
    • Flutter version 3.9.0-22.0.pre.28 on channel master at /opt/homebrew/Caskroom/flutter/3.7.9/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1a6a20cdc6 (8 hours ago), 2023-04-05 06:39:09 +0100
    • Engine revision 4219c72ac8
    • Dart version 3.0.0 (build 3.0.0-408.0.dev)
    • DevTools version 2.23.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/dqss/Library/Android/sdk
    • Platform android-33-ext5, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.77.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (4 available)
    • iPhone 14 Pro (mobile)        • 549F21F9-460D-46A6-BE18-0D4F52F67873     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • Chrome (web)                  • chrome                                   • web-javascript • Google Chrome 111.0.5563.146

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by moffatman** [comment]
The problem is that you have `shrinkWrap` (which requires building all children) and an infinite number of children (null `itemCount` and the `itemBuilder` never returns null). So flutter will continue to build children infinitely. I don't think there is any possible way to detect this condition before hand :laughing:.

See https://en.wikipedia.org/wiki/Halting_problem

**Comment by TheGlorySaint** [comment]
@moffatman You can also set `shrinkWrap` to false (adjust the Column) and this issue also exist.

Shouldn't then the `itemCount` be required?

**Comment by moffatman** [comment]
@TheGlorySaint Please share a code sample with column adjusted as you say. I can use the following without any issue:

```dart
      Column(
        children: [
          // ...
          Flexible(
            child: ListView.builder(
              itemCount: null,
              itemBuilder: (BuildContext context, int index) {
                return Text('$index');
              }
            )
          ),
          // ...
        ]
      )
```

**Comment by huycozy** [comment]
I have tried applying `Flexible` (to the provided sample code above) as Moffat suggested and see it works:

<img width="400" src="https://user-images.githubusercontent.com/104349824/230280466-b24ee304-3ed9-4567-bd30-208bd5bad838.png">

@TheGlorySaint Can you try and confirm it also works for you?

**Comment by TheGlorySaint** [comment]
@moffatman @huycozy I can confirm that wrapping it into a Flexible and null is provided to the `itemCount` works.

Still, there is the issue that when `shrinkWrap = true` is provided, no exception is thrown. Nowhere is stated that either `shrinkWrap = true` with an `itemCount` must be provided or wrapped into a Flexible Widget.

**Comment by TheGlorySaint** [comment]
@huycozy

At this example, you need to provide a `shrinkWrap = true` else you get an `Vertical viewport was given unbounded height.` error. You can't wrap the `GridView` with an `Flexible` or `Expanded` Widget else you get `"RenderFlex children have non-zero flex but incoming height constraints are unbounded."`

```dart 
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int? nullLengthGridView;
  int? workingLengthGridView = 4;
  int? nullLengthListView;
  int? workingLengthListView = 4;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: CustomScrollView(
        slivers: [
          SliverToBoxAdapter(
            child: Padding(
              padding: const EdgeInsets.all(15),
              child: DecoratedBox(
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(15),
                  boxShadow: const [
                    BoxShadow(
                      color: Colors.black38,
                      spreadRadius: 0,
                      blurRadius: 10,
                    ),
                  ],
                ),
                child: Padding(
                  padding: const EdgeInsets.all(15),
                  child: Column(
                    children: [
                      const Align(
                        alignment: Alignment.topLeft,
                        child: Text(
                          'Grid',
                        ),
                      ),
                      const SizedBox(height: 20),
                      GridView.builder(
                        physics: const NeverScrollableScrollPhysics(),
                        gridDelegate:
                            const SliverGridDelegateWithFixedCrossAxisCount(
                          crossAxisCount: 2,
                          crossAxisSpacing: 10,
                          mainAxisSpacing: 10,
                          childAspectRatio: 2,
                        ),
                        shrinkWrap: true,
                        itemCount: 5,
                        itemBuilder: (BuildContext context, int index) {
                          return Text(
                            '$index',
                            style: const TextStyle(
                              fontSize: 20,
                            ),
                          );
                        },
                      ),
                    ],
                  ),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
```

**Comment by moffatman** [comment]
You could refactor this to use a sliver grid instead here. 

I don't think it's possible to add an error. Since it's valid to use shrinkWrap=true, itemCount=null, and itemBuilder which only returns widgets for some limited values of `i`.

**Comment by emiliodallatorre** [comment]
The possibility to leave `itemCount` null is provided because there are cases in which a `ListView` can expand indefinitely, by building dynamically all the elements - I want to point out that a `ListView` in Flutter is `RecyclerView` in classic Android development.

So, having the possibility to let the list just create the items when you have theme on the screen, allows you to have an infinite but unrendered number of them.
Adding `shrinkWrap` is the problem, because you are requiring the `ListView` to have a finite size.

I think that the way we could have to recognize this error and stops silent fails of the behavior would be just to check in the constructors that `shrinkWrap` is `false` if `itemCount` is null - this for @moffatman stating that it's difficult to prevent this error.

**Comment by moffatman** [comment]
@emiliodallatorre 

You can use `itemCount: null` and still have a finite number of items. The ListView will stop building more items the first time you return `null` from the `itemBuilder`.

So this is valid:

```dart
ListView.builder(
  itemCount: null,
  shrinkWrap: true,
  itemBuilder: (BuildContext context, int index) {
    if (index > 10 {
      return null;
    }
    return Text('Item $index');
  }
)
```

While this will run forever:

```dart
ListView.builder(
  itemCount: null,
  shrinkWrap: true,
  itemBuilder: (BuildContext context, int index) {
    return Text('Item $index');
  }
)
```

And there's no way from within the ListView we can tell them apart, since they are just arbitrary opaque callbacks. Of course in this trivial example, we know we could have put `itemCount: 11`. But there may be some more complex use cases where the number of items is expensive to compute at the beginning. So that's why I believe we can't take any action on this change. Except for maybe updating the documentation of shrinkWrap?

**Comment by emiliodallatorre** [comment]
> @emiliodallatorre
> 
> You can use `itemCount: null` and still have a finite number of items. The ListView will stop building more items the first time you return `null` from the `itemBuilder`.
> 
> So this is valid:
> 
> ```dart
> ListView.builder(
>   itemCount: null,
>   shrinkWrap: true,
>   itemBuilder: (BuildContext context, int index) {
>     if (index > 10 {
>       return null;
>     }
>     return Text('Item $index');
>   }
> )
> ```
> 
> While this will run forever:
> 
> ```dart
> ListView.builder(
>   itemCount: null,
>   shrinkWrap: true,
>   itemBuilder: (BuildContext context, int index) {
>     return Text('Item $index');
>   }
> )
> ```
> 
> And there's no way from within the ListView we can tell them apart, since they are just arbitrary opaque callbacks. Of course in this trivial example, we know we could have put `itemCount: 11`. But there may be some more complex use cases where the number of items is expensive to compute at the beginning. So that's why I believe we can't take any action on this change. Except for maybe updating the documentation of shrinkWrap?

Wow...!
I thought an `ItemBuilder` should return a `Widget`, not a `Widget?`. This is a complete game-changer for me; thank you so much!
