### ISSUE TITLE
[Impeller] Flaky impeller golden test in the engine

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#124277]
After https://github.com/flutter/engine/pull/40824, there appears to be a flaky golden file test in the engine that is blocking other PRs from landing (example: https://github.com/flutter/engine/pull/40924).

![Screenshot 2023-04-05 at 4 48 25 PM](https://user-images.githubusercontent.com/16964204/230220735-1eccfcad-e723-47af-b22d-77ab70207173.png)

The individual dots to the right show different colors, meaning a unique image was generated for each commit.
This is with the fuzzy matching algorithm set for this test:

![Screenshot 2023-04-05 at 4 51 07 PM](https://user-images.githubusercontent.com/16964204/230220881-050e661e-cee4-45c7-8eb1-d7bb24931a18.png)

Also, it looks like this image is even flaking in post submit, because the same test is listed as untriaged on the main branch: https://flutter-engine-gold.skia.org/ 

In the framework we have the tree go red if an unapproved image shows up in post submit, maybe the engine implementation should do the same.

cc @mdebbar @dnfield @chinmaygarde @gaaclarke

**Comment by gaaclarke** [comment]
@Piinks do you understand why these differences aren't filed as acceptable given the fuzzy parameters?

In the short term it was speculated that using an opaque background should make this test more stable so I'll try that out.

**Comment by Piinks** [comment]
I don't, maybe @mdebbar and @yjbanov know?

**Comment by yaakovschectman** [comment]
Should pending engine PRs wait until this is handled, or should they land if everything else passes?

**Comment by chinmaygarde** [comment]
They should land if everything else passes.

**Comment by yjbanov** [comment]
> I don't, maybe @mdebbar and @yjbanov know?

I don't know why the test fails with the given parameters. However, I would recommend against using [pixel percentages](https://github.com/flutter/engine/blob/6a6d8ccb46a70a83fa6c377b736a7aec51a4ad2d/impeller/golden_tests/golden_digest.cc#L9) for delta thresholds. Frequently a golden will contain a lot of empty space that's irrelevant to the test (as is the case in the issue report) and using percentage would allow too many pixels to deviate. Instead, consider using the strategy of "no more than P pixels can deviate, and no one pixel can deviate by more than C", where P is the absolute number of pixels (usually a low number, like 20, and doesn't change from golden to golden), and C is the maximum allowed color delta ([example](https://github.com/flutter/flutter/blob/df48b922ca241ef99ad3b4fa7fe63a7fd9eef9dd/packages/flutter_goldens_client/lib/skia_client.dart#L372)).

**Comment by chinmaygarde** [comment]
@zanderso Correct me if I am wrong but we are no longer gating rollers on these diffs, have a conservative fuzz factor on diffs but still expect manual intervention, [reducing the noise by not running these tests on the Intel Iris 5100](https://github.com/flutter/flutter/issues/124877) which was known to be problematic (was it for the flakes or the shader compiler? 🤷). Closing this as done.

**Comment by dnfield** [comment]
The Iris 5100 change was because it doesn't support compute subgroups. However, it's also a small portion of our overall mac testing pool and may have had other strange issues specific to it.
