### ISSUE TITLE
Fix UIWindowSceneGeometryPreferencesIOS leak

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#124288]
Seen as a leak in the memory graph.  `UIWindowSceneGeometryPreferencesIOS` is missing an `autorelease`: 
```objc
        UIWindowSceneGeometryPreferencesIOS* preference =
            [[UIWindowSceneGeometryPreferencesIOS alloc]
                initWithInterfaceOrientations:_orientationPreferences];
```
https://github.com/flutter/engine/blob/610cdf0ae1172f5836956221eb80614dd7a0c38e/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm#L1816-L1818

**Comment by giovanni256** [comment]
Hi there.
I updated from Flutter 3.7 to 3.9.

Since this update, my iOS app is really slow and is lagging too much.
Could it be related to this issue or should I open a new one?

Ty

**Comment by jmagman** [comment]
> Could it be related to this issue or should I open a new one?

Extremely unlikely to be related.  You should file a new issue and completely fill out the template.  Thanks!
