### ISSUE TITLE
 Failed to build iOS app - Could not build the precompiled application for the device.

### ISSUE THREAD

**Issue by mahmoudElgohary** [flutter/flutter#124278]
## Steps to Reproduce

app work at android but not at iOS

I'm try to run 
```
flutter clean             
flutter pub get
flutter pub cache repair
```
then 

```
flutter create .          
flutter pub get
flutter run -v
```

this is the output from `flutter run -v`

[output.txt](https://github.com/flutter/flutter/files/11163429/output.txt)

I attached `flutter doctor -v` 
[doctor_out.txt](https://github.com/flutter/flutter/files/11163430/doctor_out.txt)

**Comment by darshankawar** [comment]
@mahmoudElgohary 
The main error seems to be :

```
build/ios/Debug-iphoneos/TOCropViewController/TOCropViewController.framework/TOCropViewController
           ld: file not found: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphoneos.a
```

And may be related to https://github.com/CocoaPods/CocoaPods/issues/11808, so try to upgrade your cocoapods version and try again to see if it helps or not.

**Comment by mahmoudElgohary** [comment]
> @mahmoudElgohary The main error seems to be :
> 
> ```
> build/ios/Debug-iphoneos/TOCropViewController/TOCropViewController.framework/TOCropViewController
>            ld: file not found: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphoneos.a
> ```
> 
> And may be related to [CocoaPods/CocoaPods#11808](https://github.com/CocoaPods/CocoaPods/issues/11808), so try to upgrade your cocoapods version and try again to see if it helps or not.

Same problem

**Comment by oblivioussing** [comment]
> 
The same issue, and upgrading to the latest version still doesn't work

**Comment by aj-ed** [comment]
Can confirm this works after https://stackoverflow.com/a/75729977/856088

**Comment by mahmoudElgohary** [comment]
worked with me after remove cocopods  

https://stackoverflow.com/a/35316717

and install it again 
https://guides.cocoapods.org/using/getting-started.html

thanks @darshankawar  @aj-ed

**Comment by jmagman** [comment]
This is a duplicate of https://github.com/flutter/flutter/issues/124340 caused by a change of behavior in Xcode 14.3.  Please upgrade to Flutter 3.7.11 and remove any changes you made to your Podfile to work around the issue.

If you are still seeing issues, please file a new GitHub issue and completely fill out the template.
