### ISSUE TITLE
Unable to login to flutter dashboard

### ISSUE THREAD

**Issue by drewroengoogle** [flutter/flutter#124209]
I noticed this morning that I'm unable to login to flutter-dashboard in order to rerun a job.

Steps to reproduce:
* Click "SIGN IN" at the top
* Choose my google account on the account selection page
* Redirect back to flutter-dashboard, but not showing as logged in, as the "SIGN IN" button is still visible

Additional reproduction step:
* Click a task
* Click "Rerun"
* Prompted to login, choose my google account on the account selection page
* The task is not rerun

In the past, I have been able to refresh and login successfully, but that does not seem to be the case. I also noticed that an endpoint is returning a 403 when looking at the network tab:
**Request**
```
Request URL: https://content-people.googleapis.com/v1/people/me?sources=READ_SOURCE_TYPE_PROFILE&personFields=photos%2Cnames%2CemailAddresses
Request Method: GET
Status Code: 403 
Remote Address: [2607:f8b0:4009:807::200a]:443
Referrer Policy: strict-origin-when-cross-origin
```

**Response**
```
{
  "error": {
    "code": 403,
    "message": "People API has not been used in project 308150028417 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/people.googleapis.com/overview?project=308150028417 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.Help",
        "links": [
          {
            "description": "Google developers console API activation",
            "url": "https://console.developers.google.com/apis/api/people.googleapis.com/overview?project=308150028417"
          }
        ]
      },
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "SERVICE_DISABLED",
        "domain": "googleapis.com",
        "metadata": {
          "service": "people.googleapis.com",
          "consumer": "projects/308150028417"
        }
      }
    ]
  }
}
```

Did something change recently in the login flow that requires the People API?

**Comment by drewroengoogle** [comment]
cc: @keyonghan Potentially

**Comment by keyonghan** [comment]
There has been some issue going on with the sign in button. But somehow I am able to click the button and sign in without an issue.

Please see if you can dup this with https://github.com/flutter/flutter/issues/123026.

/cc @ricardoamador related to the sign in migration.

**Comment by drewroengoogle** [comment]
> Please see if you can dup this with #123026.

I'll close this and add the information to that issue instead. Thanks Keyong!
