### ISSUE TITLE
Artifacts missing code signing metadata - Mac Host Engine

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#124322]
Link to build: https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/flutter-prod-builder_chops-service-accounts.iam.gserviceaccount.com/d244e5bb17874a24ec23cd80050bff90946091237d71132f16a3cb08d25ccf7a/+/build.proto

Files missing metadata:

- [ ] darwin-x64/FlutterEmbedder.framework.zip
- [ ] darwin-x64-release/FlutterMacOS.dSYM.zip
- [x] darwin-x64/FlutterMacOS.framework.zip
- [x] darwin-x64-profile/FlutterMacOS.framework.zip
- [x] darwin-x64-release/FlutterMacOS.framework.zip

**Comment by XilaiZhang** [comment]
Ouch sorry for wasting your time sir, and thanks for the info! I will look into why FlutterMacOS.framework.zip ones are missing.

Meanwhile, should we ignore the binaries in FlutterMacOS.dSYM.zip and FlutterEmbedder.framework.zip, or should they be codesigned as well?
For context, they look like new binaries detected, and is not in the [previous list of binaries we codesign](https://github.com/christopherfujino/codesign.py/blob/master/codesign.py#L12). If we are planning to sign them, should we sign them with entitlements? Thank you!

**Comment by godofredoc** [comment]
@jmagman @christopherfujino should these binaries be code signed?

**Comment by christopherfujino** [comment]
> @jmagman @christopherfujino should these binaries be code signed?

I'm investigating

**Comment by jmagman** [comment]
I don't think dSYMs would ever need to be codesigned.  And I guess if the iOS and macOS embedder frameworks are codesigned then `FlutterEmbedder` should be as well, but that could be added as a feature request.  I haven't heard about any customers hitting issues.

**Comment by christopherfujino** [comment]
> Link to build: https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/flutter-prod-builder_chops-service-accounts.iam.gserviceaccount.com/d244e5bb17874a24ec23cd80050bff90946091237d71132f16a3cb08d25ccf7a/+/build.proto
> 
> Files missing metadata:
> 
> * [ ]  darwin-x64/FlutterEmbedder.framework.zip
Still checking on this one...

> * [ ]  darwin-x64-release/FlutterMacOS.dSYM.zip
This was never codesigned with codesign.py, however as they are just debug symbols and not executable, I do not believe they need to codesigned or notarized. We may need to update the infra script to have a concept of files that ARE binaries but we KNOW they don't need to be codesigned.

The framework zips at least already appear in codesign.py:

> * [ ]  darwin-x64/FlutterMacOS.framework.zip

https://github.com/christopherfujino/codesign.py/blob/master/codesign.py#L128

> * [ ]  darwin-x64-profile/FlutterMacOS.framework.zip

https://github.com/christopherfujino/codesign.py/blob/master/codesign.py#L139

> * [ ]  darwin-x64-release/FlutterMacOS.framework.zip

https://github.com/christopherfujino/codesign.py/blob/master/codesign.py#L128

**Comment by godofredoc** [comment]
@XilaiZhang do we need to add a metadata file to signal we don't need to sign a given artifact? also can you please share where I can find the entitlements for `FlutterMacOS.framework.zip`?

**Comment by XilaiZhang** [comment]
For FlutterMacOS.framework.zip I looked at the [the google cloud bucket](https://pantheon.corp.google.com/storage/browser/_details/flutter_infra_release/flutter/experimental/f2f4774b6ff95f8c1724d55dba6007de90752266/darwin-x64/FlutterMacOS.framework.zip;tab=live_object?authuser=0), and it does not contain the entitlement files. the entitlements should got embedded through sky/tools/create_macos_framework.py, in https://github.com/flutter/engine/pull/40508/files which landed two weeks ago. Umm which version of create_macos_framework.py did we use to produce this artifact?

**Comment by godofredoc** [comment]
Thanks @XilaiZhang, I'll send the CPs to stable, beta

**Comment by XilaiZhang** [comment]
updated https://github.com/flutter/cocoon/pull/2594 and created https://github.com/flutter/engine/pull/40984 for review. They two together should resolve this issue.

**Comment by godofredoc** [comment]
Thanks @XilaiZhang it seems like we can close https://github.com/flutter/cocoon/pull/2594. Let's keep the embedder signing PR.

**Comment by XilaiZhang** [comment]
> Thanks @XilaiZhang it seems like we can close [flutter/cocoon#2594](https://github.com/flutter/cocoon/pull/2594). Let's keep the embedder signing PR.

Thanks a lot sir! closed 2594, and left a comment on embedder pr and the recipe pr.
