### ISSUE TITLE
video_player cannot play m3u8 video segment by hevc(h265) on ios

### ISSUE THREAD

**Issue by fangwy** [flutter/flutter#124376]
video_player cannot play m3u8 video cut by hevc on ios
test url 
http://resdev.eatdesk.net/static/upload/2023040712/video/d9e347ebe9884e19c580558cb97271d6/d9e347ebe9884e19c580558cb97271d6.m3u8
It can be played using VLC

xcode 
![image](https://user-images.githubusercontent.com/19532592/230554158-f71d58ca-69e4-472a-b2d7-9dec546237e1.png)

**Comment by huycozy** [comment]
I've tried checking your url above with https://www.hlsplayer.net but it can not play. 

It looks like you are having a similar issue at https://github.com/flutter/flutter/issues/116021. Please take a look at https://github.com/flutter/flutter/issues/116021#issuecomment-1329595006 and try the SwiftUI code there with your url to check if it can work or not. If it also doesn't work, feel free to close this issue. Thanks!

**Comment by fangwy** [comment]
above with https://www.hlsplayer.net/ but it can not play
but mac VLC APP can play
![image](https://user-images.githubusercontent.com/19532592/230594022-45fe5b6e-3492-4a9c-a9f9-e33f0b2aa307.png)
![image](https://user-images.githubusercontent.com/19532592/230594164-992721f9-f279-41ed-8cdd-7d20ca82c42c.png)
![image](https://user-images.githubusercontent.com/19532592/230594213-6dff117f-662f-41f1-b002-89edd1c49560.png)

**Comment by stuartmorgan** [comment]
> but mac VLC APP can play

`video_player` on iOS is a wrapper for the OS-provided `AVPlayer`, not VLC, and `AVPlayer` cannot play the video (testing using a trivial native app as requested in an earlier comment). That means `video_player` cannot support it; closing as infeasible.

If you want to play videos that work in VLC but not AVPlayer, you'd need to use a plugin that's based on VLC.
