### ISSUE TITLE
Documentation with wrong code - Flutter ShaderMask Class

### ISSUE THREAD

**Issue by vfthome** [flutter/flutter#124323]
![Screenshot_1](https://user-images.githubusercontent.com/103903008/230436520-6764dd9f-4831-4fec-93ca-b6c3af083ab6.png)

This code is not working, the text does not display the gradient, code is wrong.

**Comment by huycozy** [comment]
The sample code is missing `TextStyle(color: Colors.white)` for Text as I can see. It works as the video when applying that attribute. 
I can see it also missing on both [api.flutter.dev](https://api.flutter.dev/) and [master-api.flutter.dev](https://master-api.flutter.dev/).
