### ISSUE TITLE
Pigeon generated Objective-C code produces warning A function declaration without a prototype is deprecated in all versions of C

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#124343]
In the implementation:
```
url_launcher_ios-6.1.3/ios/Classes/messages.g.m:27:57 A function declaration without a prototype is deprecated in all versions of C
```

```objc
NSObject<FlutterMessageCodec> *FULUrlLauncherApiGetCodec() {
```
should have a `void`:
```objc
NSObject<FlutterMessageCodec> *FULUrlLauncherApiGetCodec(void) {
```

https://github.com/flutter/packages/blob/36d412490a5fb90811902c5d91c95a9debf39b49/packages/pigeon/lib/objc_generator.dart#L781-L782

Not sure why none of our scripts in CI caught the warning.

cc @tarrinneal https://github.com/flutter/packages/pull/3037

**Comment by stuartmorgan** [comment]
> Not sure why none of our scripts in CI caught the warning.

Hm, where exactly are you seeing this? Is it an Xcode version thing maybe?

(I just build the url_launcher_ios example in Xcode 14.0 and didn't see it for example.)

**Comment by jmagman** [comment]
I'm on 14.3, guess this is new.  I'll check on 14.2 when I get a chance.

**Comment by stuartmorgan** [comment]
Yep, it's new in clang 15/Xcode 14.3 based on some threads I found. E.g., https://developer.apple.com/forums/thread/725753
