### ISSUE TITLE
Simply display the next Flutter Version when suggesting to upgrade

### ISSUE THREAD

**Issue by nagringapp** [flutter/flutter#124367]
## Use case
As a developer, I would like to know with is the next version when flutter display a message to upgrade its version.

## Current message

A new version of Flutter is available!
To update to the latest version, run "flutter upgrade". 

## Proposal

The version 3.7.4 of Flutter is available!
To update to the latest version, run "flutter upgrade". 

## Reason

It's is good to know if it's a breaking change without the need to open the website, for minor changes.

**Comment by huycozy** [comment]
Thanks for the report! This is a known issue being tracked at https://github.com/flutter/flutter/issues/68936.
Closing this issue as a duplicate, so please follow up on it for further updates.
