### ISSUE TITLE
when l run my project showing errors

### ISSUE THREAD

**Issue by armssecondson** [flutter/flutter#124377]
Cannot resolve symbol '@mipmap/ic_launcher'

**Comment by huycozy** [comment]
Please see answers on this StackOverflow question for more details https://stackoverflow.com/questions/68846562/flutter-android-resource-linking-failed-mipmap-ic-launcher-not-found

Your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any. Closing for now.
