### ISSUE TITLE
Versions in pubspec don't change after running "flutter pub upgrade"

### ISSUE THREAD

**Issue by ghaith-abtah-5** [flutter/flutter#124370]
When I run the command "flutter pub upgrade" or "flutter pub upgrade --major-versions" from the terminal, it says that a number of dependencies changed but the "pubspec.ymal" file doesn't update the versions.
____________________________
**My "pubspec.yaml" dependencies:**

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  responsive_sizer: ^3.1.1
  flutter_svg: ^2.0.0+1
  analyzer: ^5.2.0
  dio: ^5.0.0
  json_serializable: ^6.5.4
  json_annotation: ^4.8.0
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  pretty_dio_logger: ^1.2.0-beta-1
  shared_preferences: ^2.0.15
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  flutter_bloc: ^8.1.1
  bloc_concurrency: ^0.2.0
  **go_router: ^6.0.1**
  fluttertoast: ^8.1.2
  lottie: ^2.2.0
  equatable: ^2.0.5
  scrollable_positioned_list: ^0.3.4
  font_awesome_flutter: ^10.3.0
  easy_localization: ^3.0.1
  **sqflite: ^2.2.4+1**
  awesome_notifications: ^0.7.4+1
  image_picker: ^0.8.6+1
  path: ^1.8.2
  permission_handler: ^10.2.0
  cached_network_image: ^3.2.3
  pinput: ^2.2.31
  flutter_uploader: ^3.0.0-beta.4
  google_maps_flutter: ^2.2.5
  geolocator: ^9.0.2
  intl: ^0.17.0
  qr_flutter: ^4.0.0
  mobile_scanner: ^3.0.0
  flutter_polyline_points: ^1.0.0
  firebase_core: ^2.7.1
  firebase_messaging: ^14.3.0
  background_locator_2: ^2.0.6
  device_info_plus: ^8.1.0
  awesome_dialog: ^3.0.2
  firebase_dynamic_links: ^5.0.17
  flutter_logs: ^2.1.10
  video_player: ^2.6.1
  photo_view: ^0.14.0
  carousel_slider: ^4.2.1
  chewie: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
____________________________
 **My "flutter pub upgrade" or "flutter pub upgrade --major-versions" result:**
 
   _fe_analyzer_shared 58.0.0
  _flutterfire_internals 1.1.0
  analyzer 5.10.0
  archive 3.3.6
  args 2.4.0
  async 2.10.0 (2.11.0 available)
  awesome_dialog 3.0.2
  awesome_notifications 0.7.4+1
  background_locator_2 2.0.6
  bloc 8.1.1
  bloc_concurrency 0.2.1
  boolean_selector 2.1.1
  build 2.3.1
  build_config 1.1.1
  build_daemon 3.1.1 (4.0.0 available)
  build_resolvers 2.2.0
  build_runner 2.3.3 (2.4.1 available)
  build_runner_core 7.2.7
  built_collection 5.1.1
  built_value 8.4.4
  cached_network_image 3.2.3
  cached_network_image_platform_interface 2.0.0
  cached_network_image_web 1.0.2
  carousel_slider 4.2.1
  characters 1.2.1 (1.3.0 available)
  checked_yaml 2.0.2
  chewie 1.4.0
  clock 1.1.1
  code_builder 4.4.0
  collection 1.17.0 (1.17.1 available)
  convert 3.1.1
  cross_file 0.3.3+4
  crypto 3.0.2
  csslib 0.17.2
  cupertino_icons 1.0.5
  dart_style 2.3.0
  dartz 0.10.1
  device_info_plus 8.1.0
  device_info_plus_platform_interface 7.0.0
  dio 5.1.1
  easy_localization 3.0.1
  easy_logger 0.0.2
  equatable 2.0.5
  fake_async 1.3.1
  ffi 2.0.1
  file 6.1.4
  firebase_core 2.9.0
  firebase_core_platform_interface 4.6.0
  firebase_core_web 2.3.0
  firebase_dynamic_links 5.1.0
  firebase_dynamic_links_platform_interface 0.2.4
  firebase_messaging 14.4.0
  firebase_messaging_platform_interface 4.3.0
  firebase_messaging_web 3.3.0
  fixnum 1.1.0
  flutter 0.0.0 from sdk flutter
  flutter_bloc 8.1.2
  flutter_blurhash 0.7.0
  flutter_cache_manager 3.3.0
  flutter_lints 2.0.1
  flutter_localizations 0.0.0 from sdk flutter
  flutter_logs 2.1.10
  flutter_plugin_android_lifecycle 2.0.9
  flutter_polyline_points 1.0.0
  flutter_svg 2.0.4
  flutter_test 0.0.0 from sdk flutter
  flutter_uploader 3.0.0-beta.4
  flutter_web_plugins 0.0.0 from sdk flutter
  fluttertoast 8.2.1
  font_awesome_flutter 10.4.0
  freezed 2.3.2
  freezed_annotation 2.2.0
  frontend_server_client 3.2.0
  geolocator 9.0.2
  geolocator_android 4.1.7
  geolocator_apple 2.2.5
  geolocator_platform_interface 4.0.7
  geolocator_web 2.1.6
  geolocator_windows 0.1.1
  get_it 7.2.0
  glob 2.1.1
  **go_router 6.5.5**
  google_maps_flutter 2.2.5
  google_maps_flutter_android 2.4.10
  google_maps_flutter_ios 2.2.1
  google_maps_flutter_platform_interface 2.2.6
  graphs 2.2.0
  html 0.15.2
  http 0.13.5
  http_multi_server 3.2.1
  http_parser 4.0.2
  image_picker 0.8.7+1
  image_picker_android 0.8.6+6
  image_picker_for_web 2.1.12
  image_picker_ios 0.8.7+2
  image_picker_platform_interface 2.6.3
  internet_connection_checker 1.0.0+1
  intl 0.17.0 (0.18.0 available)
  io 1.0.4
  js 0.6.5 (0.6.7 available)
  json_annotation 4.8.0
  json_serializable 6.6.1
  lints 2.0.1
  logging 1.1.1
  lottie 2.3.2
  matcher 0.12.13 (0.12.15 available)
  material_color_utilities 0.2.0 (0.3.0 available)
  meta 1.8.0 (1.9.1 available)
  mime 1.0.4
  mobile_scanner 3.2.0
  nested 1.0.0
  octo_image 1.0.2
  package_config 2.1.0
  path 1.8.2 (1.8.3 available)
  path_parsing 1.0.1
  path_provider 2.0.14
  path_provider_android 2.0.24
  path_provider_foundation 2.2.1
  path_provider_linux 2.1.10
  path_provider_platform_interface 2.0.6
  path_provider_windows 2.1.5
  pedantic 1.11.1
  permission_handler 10.2.0
  permission_handler_android 10.2.0
  permission_handler_apple 9.0.8
  permission_handler_platform_interface 3.9.0
  permission_handler_windows 0.1.2
  petitparser 5.1.0 (5.3.0 available)
  photo_view 0.14.0
  pinput 2.2.31
  platform 3.1.0
  plugin_platform_interface 2.1.4
  pointycastle 3.7.2
  pool 1.5.1
  pretty_dio_logger 1.3.1
  process 4.2.4
  provider 6.0.5
  pub_semver 2.1.3
  pubspec_parse 1.2.2
  qr 2.1.0 (3.0.1 available)
  qr_flutter 4.0.0
  responsive_sizer 3.1.1
  rive 0.9.1 (0.10.3 available)
  rxdart 0.27.7
  scrollable_positioned_list 0.3.5
  shared_preferences 2.1.0
  shared_preferences_android 2.1.0
  shared_preferences_foundation 2.2.0
  shared_preferences_linux 2.2.0
  shared_preferences_platform_interface 2.2.0
  shared_preferences_web 2.1.0
  shared_preferences_windows 2.2.0
  shelf 1.4.0
  shelf_web_socket 1.0.3
  sky_engine 0.0.99 from sdk flutter
  smart_auth 1.0.8
  source_gen 1.2.7
  source_helper 1.3.3
  source_span 1.9.1 (1.10.0 available)
  **sqflite 2.2.6**
  sqflite_common 2.4.3
  stack_trace 1.11.0
  stream_channel 2.1.1
  stream_transform 2.1.0
  string_scanner 1.2.0
  synchronized 3.0.1
  term_glyph 1.2.1
  test_api 0.4.16 (0.5.1 available)
  timing 1.0.1
  typed_data 1.3.1
  universal_platform 1.0.0+1
  uuid 3.0.7
  vector_graphics 1.1.4
  vector_graphics_codec 1.1.4
  vector_graphics_compiler 1.1.4
  vector_math 2.1.4
  video_player 2.6.1
  video_player_android 2.4.4
  video_player_avfoundation 2.4.3
  video_player_platform_interface 6.1.0
  video_player_web 2.0.16
  wakelock 0.6.2
  wakelock_macos 0.4.0
  wakelock_platform_interface 0.3.0
  wakelock_web 0.4.0
  wakelock_windows 0.2.1
  watcher 1.0.2
  web_socket_channel 2.3.0
  win32 3.1.3 (4.1.1 available)
  xdg_directories 1.0.0
  xml 6.2.2
  yaml 3.1.1
____________________________
**Reproduce steps:**

add "go_router: ^6.0.1" to "pubspec.yaml" manually or by running "flutter pub add go_router" then run "flutter pub upgrade" or "flutter pub upgrade --major-versions" from terminal
____________________________
**My "flutter doctor -v" result:**

[✓] Flutter (Channel stable, 3.7.10, on macOS 13.3 22E252 darwin-arm64, locale
    en-SY)
    • Flutter version 3.7.10 on channel stable at /Users/ghaithabtah/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b12645012 (3 days ago), 2023-04-03 17:46:48 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1

Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/ghaithabtah/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/ghaithabtah/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 223.8214.16

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13
      (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.3
      22E252 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google
      Chrome 111.0.5563.146

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by stuartmorgan** [comment]
That's the expected behavior; only major version changes are made in pubspec.yaml. you can read about how it works at https://dart.dev/tools/pub/cmd/pub-upgrade

Closing as this is expected behavior.
