### ISSUE TITLE
Semantics widget should allow specifying custom actions

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#12434]
Some developers want to specify custom a11y actions for their app that are different from the default a11y actions of a widget. For this, it would be cool if the Semantics widget would allow specifying a set of SemanticActions and handlers.

Example: One dev wants to expose a drop down menu as an "Adjustable" where swiping up and down switches between the options.

Related: https://github.com/flutter/flutter/issues/12433

**Comment by Hixie** [comment]
Where possible, if we expose this, we should then make our widgets use this whenever they have custom actions. That is, we should just have the one way for widgets to do this, not the way our widgets do it and the way we have everyone else do it.
