### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: The process cannot access the file because it is being used by another process., errno = 32

### ISSUE THREAD

**Issue by atulkumar6556** [flutter/flutter#124311]
## Command
```
flutter run -d windows
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: The process cannot access the file because it is being used by another process.
, errno = 32
```
#0      _File.throwIfError (dart:io/file_impl.dart:629:7)
#1      _File.openSync (dart:io/file_impl.dart:473:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:598:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:622:5)
#4      ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:150:16)
#5      ErrorHandlingF

**Comment by huycozy** [comment]
Hi @atulkumar6556 
What is your current Flutter version? (Please provide the output of `flutter doctor -v`)
Please also retry on the latest Flutter master channel to see if the issue still persists or not. 

```
flutter channel master
flutter upgrade
```

**Comment by atulkumar6556** [comment]
> flutter doctor -v

 Flutter version 3.9.0-22.0.pre.84 on channel master {installed directory}

**Comment by huycozy** [comment]
Can you confirm the issue still persists on the master channel or not? If it still occurs, please provide the complete output of `flutter run -v` so that we may verify the issue better. Thanks!
