### ISSUE TITLE
Investigate making Material AppBar flexible / adaptive

### ISSUE THREAD

**Issue by leighajarett** [flutter/flutter#124330]
Most mobile apps have some sort of app bar. Right now we offer a few different app bar widgets, in both Material and Cupertino. However, there are different properties for each and it's difficult to manually adapt the two. We should consider if there's a wya to expose specific properties / make properties more composable so that we can recreate a `CupertinoNavigationBar` from Material `AppBar`. 

In this investigation, we should ensure that it's still easy to create a Material and a HIGs style app bar. We should also consider properties that allow for more custom app bars to be created. 

Note also the specific request here: https://github.com/flutter/flutter/issues/16069

**Comment by tirth-multipl** [comment]
my bad 👍

**Comment by HansMuller** [comment]
Investigation is complete. See https://github.com/flutter/flutter/pull/143538, https://github.com/flutter/flutter/pull/127340, https://github.com/flutter/flutter/pull/143196, https://github.com/flutter/flutter/pull/143325. Examples of building some common iOS app bars with these primitives are forthcoming.
