### ISSUE TITLE
ci.yaml validation check not running or taking 1+ hours to run?

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#124332]
Example roll PR https://github.com/flutter/flutter/pull/124321

P0 because this will block all PRs.

**Comment by ricardoamador** [comment]
Switched traffic to the previous version and now rerunning all stuck pull requests.

**Comment by ricardoamador** [comment]
This appears to have only affected flutter as looking at the other repositories so far, packages and engine, there were recent pull requests after the deployment of the service that were not affected. Will be looking further. Though this is no longer a P0.

**Comment by dnfield** [comment]
I'm seeing this on engine in the PR I linked above.

**Comment by dnfield** [comment]
(It appears to be recovering now, or it just waited long enough to get scheduled)

**Comment by ricardoamador** [comment]
Closing this issue as the fix is being tracked here: https://github.com/flutter/flutter/issues/124238
