### ISSUE TITLE
Way to check if VoiceOver/TalkBack is on

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#12436]
Some customers want to be able to present a slightly different UI to a11y users. For that, they need to check if VoiceOver or TalkBack is used by the user.

Note: It is not enough to just check if a11y is turned on as on Android some apps turn this on to be able to read the screen content.

**Comment by goderbauer** [comment]
iOS:
* https://developer.apple.com/documentation/uikit/1615187-uiaccessibilityisvoiceoverrunnin
* https://developer.apple.com/documentation/uikit/uiaccessibilityvoiceoverstatuschanged?language=objc

**Comment by Hixie** [comment]
What specifically do they want to trigger this from? Speech synthesis features? Any kind of accessibility feature? e.g. what should happen if the user has some combination of high contrast, increased font size, animations disabled, alternate inputs, screen reading, etc?

**Comment by goderbauer** [comment]
The request here is to know if the user is currently using a Screen Reader (e.g. Talkback or VoiceOver). What other a11y features are enabled should not have any affect on this.

The idea is to use this information to slightly change the behavior of the UI. E.g. when a ScreenReader is used it is usually considered bad if elements (like an alert) time out after a while and disappear. So this request will enable developer to detect that a screen reader is in use and they can then disable the timeout in this specific case.

**Comment by goderbauer** [comment]
Another use case: It is also recommended that important interaction elements are placed at the top of the screen when a screen reader is used. For that purpose, some apps apparently put the functionality of the FAB in the top toolbar when a screen reader is in use.

**Comment by randikapw** [comment]
Can some one kindly share a simple sample code peace for check whether the screen reader is on or not

**Comment by pejalo** [comment]
@randikapw 
From the docs:
https://docs.flutter.io/flutter/widgets/MediaQuery-class.html
https://docs.flutter.io/flutter/widgets/MediaQueryData-class.html
https://docs.flutter.io/flutter/widgets/MediaQueryData/accessibleNavigation.html
Try: `MediaQuery.of(context).accessibleNavigation`
