### ISSUE TITLE
Words within Text widget overlap on Pixel 6 inside WebView

### ISSUE THREAD

**Issue by georgivzh** [flutter/flutter#124358]
## Steps to Reproduce

I have a flutter app with a WebView (webview_flutter). The website that is opened in the WebView is also a flutter app built as a web app. Every Text widget inside the web app displays its text like squashed text. Each word of a sentence inside the Text widget overlaps with the next word.This happens only in the web app in the WebView. Outside it the text looks fine.

Scenario:
1. Create a very basic app with a **Test** widget in it
2. and build it for web and then upload it on some host so to be accessed by your phone app.
3. Open the web app in webview_flutter.

**Expected results:** 
Text is displayed with whitespaces.

**Actual results:** 
Text words overlap.

<details>
<summary>Code sample</summary>

```
Container(child: Text("A Flutter SDK constraint is satisfied only if pub is running in the context of the flutter executable, and the Flutter SDK’s"))

```

</details>
test
<details>
  <summary>Logs</summary>

```
```

```
```

```
√] Flutter (Channel stable, 3.7.8, on Microsoft Windows [Version 10.0.19045.2788], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.3)
[√] Android Studio (version 2022.1)
[√] VS Code (version 1.76.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

```

The issue reproduces only on Google Pixel 6.
It is working on two different LG phones + on Google Chrome when run directly on my machine.

I use most recent webview_flutter version.

</details>

![Screenshot_20230407-011843](https://user-images.githubusercontent.com/22403960/230506880-6d384d5f-2f79-4570-9408-e95edc5afd9d.png)

**Comment by huycozy** [comment]
Hi @georgivzh 
I checked this on my device (Realme 6, Android 11) but can not reproduce this issue. Can you share the deployed site so that I can try it on my end?

Also, do you see the issue on the desktop browser when toggling device toolbar? 
![Screenshot 2023-04-07 at 16 22 00](https://user-images.githubusercontent.com/104349824/230583091-58d776cd-c677-4f99-b9de-10c5345faddc.png)

And please also try loading your site with Android native webview to see if the issue still happens or not. ([sample Android webview native code](https://github.com/huycozy/Android-Native-Webview.git))

Thank you!

**Comment by georgivzh** [comment]
Hello @huycozy,
No, I don't see the issue on a desktop browser. And I don't see it anywhere among 3 devices - only on a Google Pixel 6. It started reproducing recently. I think when I upgraded the Flutter SDK. 

I prepared a simple Flutter web site (with just one Text widget) for the test:
[https://test-web-app-53fdf.firebaseapp.com/](https://test-web-app-53fdf.firebaseapp.com/)
I can still reproduce it.

**Comment by georgivzh** [comment]
Ok, some news, I built the web app with Flutter SDK 3.0.1 and the text looks fine there!

**Comment by huycozy** [comment]
Thanks for checking this on lower Flutter versions! 

This looks similar to https://github.com/flutter/flutter/issues/111352. Can you also check [Flutter Gallery](https://gallery.flutter.dev) if it also can be reproducible? 
It would be appreciated if you could try checking some cases reported there to see if it's the same issue as this one.

**Comment by georgivzh** [comment]
Yes, it reproduces in Flutter gallery too.

![Screenshot_20230410-211431](https://user-images.githubusercontent.com/22403960/230966032-58bc82bc-e045-4944-b4b9-c53a9c5bdd48.png)

**Comment by huycozy** [comment]
Thanks for helping to verify it. I will close this issue in favor of https://github.com/flutter/flutter/issues/111352 (as it's `P3` priority), so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!

**Comment by georgivzh** [comment]
OK, but why it's P3? It's nearly unusable like this...

**Comment by huycozy** [comment]
You might want to take a look at this: [How issue prioritization works](https://github.com/flutter/flutter/wiki/Issue-hygiene#priorities)
