### ISSUE TITLE
[Impeller] Move impeller-cmake to flutter org and test on CI

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#124456]
[impeller-cmake](https://github.com/bdero/impeller-cmake) and [impeller-cmake-example](https://github.com/bdero/impeller-cmake-example) should be moved to the Flutter org, and be tested on CI. The end goal for this issue is to have a GOMA-enabled build of impeller-cmake-example running on macOS or Linux against flutter/engine PRs and in post-submit. I expect initially these checks will be non-blocking since consumers of `impeller-cmake` will have impeller sources and dependencies pinned using the current git submodules setup. When we see the checks turn red, we can fix `impeller-cmake` or `impeller-cmake-example` out-of-band.

Using GOMA locally on Linux will be tricky since cmake prefers absolute paths, but using GOMA locally on macOS should work using the `xcode-symlinks` trick that we use for the engine.

- [x] Update `impeller-cmake` to allow building against an out-of-tree full engine checkout
- [x] Update `impeller-cmake-example` to allow building against an out-of-tree full engine checkout
- [x] Update `impeller-cmake-example` to use the clang toolchain used by a full engine checkout
- [x] Update `impeller-cmake-example` with a "preset" that uses the engine clang and does a GOMA build
- [ ] Move the repos to the Flutter org
- [x] Add the Flutter LICENSE file to both repos and add copyright headers to all source and build files.
- [x] Add a new engine tree CI recipe that does a GOMA-enabled build on mac or Linux. This probably won't be able to use engine_v2, and will need a bespoke setup.
- [x] Update the engine `.ci.yaml` to get the new build running on CI.

**Comment by zanderso** [comment]
Note to self: cmake CIPD package for mac is at [https://chrome-infra-packages.appspot.com/p/infra/3pp/tools/cmake/mac-amd64](https://chrome-infra-packages.appspot.com/p/infra/3pp/tools/cmake/mac-amd64/+/build_id:8787856497187628321)

**Comment by chinmaygarde** [comment]
From the discussion in the weekly, we are not going to be attempting this. I thought it was fine to move it to flutter.googlesource.com though. Is that right @zanderso? In any case, I am closing this as wont-fix.
