### ISSUE TITLE
MaterialButton On pressed is not working in android smarttv focus color right left top down all remote are functioning correctly but on pressed is not workin

### ISSUE THREAD

**Issue by umairali4433** [flutter/flutter#124462]
MaterialButton On pressed is not working in android smarttv focus color right left top down all remote are functioning correctly but on pressed is not working

    MaterialButton(
                  onPressed: () {
                    Navigator.push(
                      context,
                      PageRouteBuilder(
                        pageBuilder: (context, animation1, animation2) => Search(),
                        transitionDuration: Duration(seconds: 0),
                      ),
                    );
                  },
                  focusColor: Colors.green,
                  child: Icon(
                    Icons.search,
                    color: Colors.white,
                    size: 30,
                  ),
                ),

**Comment by Jiggy9** [comment]
Use the GestureDetector widget to detect taps on the button to make the onPressed function work on Android smartTV:

```GestureDetector(
  onTap: () {
    Navigator.push(
      context,
      PageRouteBuilder(
        pageBuilder: (context, animation1, animation2) => Search(),
        transitionDuration: Duration(seconds: 0),
      ),
    );
  },
  child: MaterialButton(
    focusColor: Colors.green,
    child: Icon(
      Icons.search,
      color: Colors.white,
      size: 30,
    ),
  ),
)
```
Hope this works.

**Comment by darshankawar** [comment]
@umairali4433 
Can you provide `flutter doctor -v` ?

Is the behavior only occuring using `MaterialButton` or with other buttons as well like `TextButton`, `ElevatedButton` ?
