### ISSUE TITLE
Mac Unopt fails with xcode 14c18 and runtime ios-16-2_14c18

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#124408]
When running led for experiment, hit below error when using `ios-16-2_14c18`. Seems the test is hard coded to use ios-16-0?

https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/070e54c3aacfa80d53e64f91fb140f986fa5ce7ec402fb03e560a24f3795d5e3/+/build.proto

```
2023-04-06 21:13:46.488 xcodebuild[27444:141559] Writing error result bundle to /var/folders/x3/yz6g4v5s1n102xxx70s2007m0000gp/T/ResultBundle_2023-06-04_21-13-0046.xcresult
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:iOS Simulator, OS:16.0, name:iPhone 8 }

	The requested device could not be found because no available devices matched the request.

	Available destinations for the "Scenarios" scheme:
		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
```

/cc @jmagman @zanderso

**Comment by zanderso** [comment]
Yeah, I guess [the script](https://github.com/flutter/engine/blob/main/testing/scenario_app/run_ios_tests.sh#L51) could take that as a command line argument?

**Comment by keyonghan** [comment]
Makes sense. Recipe side change is here: https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/engine/engine_unopt.py#200

**Comment by jmagman** [comment]
> Yeah, I guess [the script](https://github.com/flutter/engine/blob/main/testing/scenario_app/run_ios_tests.sh#L51) could take that as a command line argument?

That's unfortunately unlikely to work for this test, it's the pseudo golden tests that are comparing screenshots, which would be different on every iOS release.  They need to be regenerated and validated by an engineer.  That's one of the reasons we need to be able to have multiple simulator runtimes available.

However with the build+test separation, there's no reason that test can't be pulled off into its own builder which only needs the whatever version of Xcode but iOS 16 simulator runtime.

**Comment by jmagman** [comment]
@keyonghan So I think this failure is expected and this builder as-is needs to run with the iOS 16 simulator runtime.  Let me know how you want to proceed 🙂  (and thanks again for working on this problem!)

**Comment by keyonghan** [comment]
> @keyonghan So I think this failure is expected and this builder as-is needs to run with the iOS 16.0 simulator runtime. Let me know how you want to proceed 🙂 (and thanks again for working on this problem!)

Thanks for the info Jenn. I would like to keep this bug open and hold until the hermetic xcode installation is ready.

**Comment by YaoShuwei** [comment]
same to me. Just happend when I upgrade to Xcode 14.3(14E222b)

**Comment by keyonghan** [comment]
Just a heads up. LEDs to validate my theory to install xcode/runtime hermetically:
Install xcode 14c18 with runtime ios-16-0: 
First time: [cold cache](https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/62112cdcb9472e0ef6e3462223448f3d7f09f1956c1a701eefbcf8f2ae48d016/+/build.proto)
Second run: [hit cache](https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/aa3c658539bc117c82b21c9a33c1aba558067f39f420355b597d66ed588cb4fe/+/build.proto)

**Comment by zanderso** [comment]
Do I see correctly that Xcode was updated? Was this issue addressed?

**Comment by keyonghan** [comment]
Version has been bumped to 14c18 with runtime 16.0. But tests started failing in staging. Example:
https://ci.chromium.org/ui/p/flutter/builders/staging/Mac%20Unopt/301/overview

```
Command run successfully in 0.14 seconds: xcrun simctl delete IosUnitTestsSimulator
Traceback (most recent call last):
  File "/Volumes/Work/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 1229, in <module>
    sys.exit(main())
  File "/Volumes/Work/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 1212, in main
    run_objc_tests(args.ios_variant, args.objc_filter)
  File "/Volumes/Work/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 745, in run_objc_tests
    run_cmd(test_command, cwd=ios_unit_test_dir, shell=True)
  File "/Volumes/Work/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 113, in run_cmd
    raise Exception(
Exception: Command "xcodebuild -sdk iphonesimulator -scheme IosUnitTests -destination name='IosUnitTestsSimulator' test FLUTTER_ENGINE=ios_debug_sim" exited with code 70.
```

**Comment by jmagman** [comment]
> Version has been bumped to 14c18 with runtime 16.0. But tests started failing in staging.

The 16.2 runtime is missing:
```
		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device, error:iOS 16.2 is not installed. To use with Xcode, first download and install the platform }
```

`Mac Unopt` needs the latest simulator (16.2) and 16.0.  From https://github.com/flutter/flutter/issues/125216#issuecomment-1516657893 



> `mac_unopt` needs the latest simulator runtime for the `Tests for ios_debug_sim_arm64` step:
> 
> ```
> Ineligible destinations for the "IosUnitTests" scheme:
> ...
> error:iOS 16.2 is not installed. To use with Xcode, first download and install the platform }
> ```
> 
> https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8783283434209877409/+/u/test:_Tests_for_ios_debug_sim_arm64/stdout
> 
> And it also needs iOS 16.0 for the scenario tests. That's hardcoded because it corresponds to particular golden screenshots that often change with an OS version bump so need to be regenerated. https://github.com/flutter/engine/blob/32a8f98d19dfb140b20ff506e3ade6f71416aaa9/testing/scenario_app/run_ios_tests.sh#L51 and https://github.com/flutter/engine/blob/32a8f98d19dfb140b20ff506e3ade6f71416aaa9/testing/scenario_app/run_ios_tests.sh#L61
> 
> So in that PR should the runtimes be:
> 
> ```
>                     "runtime_versions": [
>                         "ios-16-2_14c18",
>                         "ios-16-0_14a5294e"
>                     ],
> ```

**Comment by jmagman** [comment]
> So in that PR should the runtimes be:
> 
> ```
>                     "runtime_versions": [
>                         "ios-16-2_14c18",
>                         "ios-16-0_14a5294e"
>                     ],
> ```
And you can see in https://ci.chromium.org/ui/p/flutter/builders/staging/Mac%20Unopt/301/overview that it's missing 16.2.
```
    "runtime_versions": [
      "ios-16-0_14a5294e"
    ],
```
