### ISSUE TITLE
[SmsRetrieverHelper] SMS verification code request failed: unknown status code: 18002 Invalid PlayIntegrity token; app not Recognized by Play Store.

### ISSUE THREAD

**Issue by dharambudh1** [flutter/flutter#124470]
I am getting an error while fetching the sms code from the verification completed callback. I am getting an SMS on the physical device, but it fails to get set in the text field.

Error: 
"E/FirebaseAuth(32222): [SmsRetrieverHelper] SMS verification code request failed: unknown status code: 18002 Invalid PlayIntegrity token; app not Recognized by Play Store."

![alt text](https://i.postimg.cc/Vs74K9kp/Screenshot-2023-04-09-at-12-38-37-PM.png "img")

In the screenshot, there's my authentication service class, which I've created, in that the code sent callback is working as expected, but the verification completed callback is never getting called.

Line no. 22 is never getting called.

Flutter Version:
Flutter (Channel stable, 3.7.0, on macOS 13.3 22E252 darwin-arm64, locale en-IN)

Plugin Version:
firebase_app_check: ^0.1.2
firebase_auth: ^4.4.0
firebase_core: ^2.9.0

Important:

I've set up Firebase "Phone Authentication" in Firebase Console & App
I've set up Firebase "App Check" in Firebase Console & App
I've set up SHA Keys (Debug & Release) in Firebase Console

**Comment by iapicca** [comment]
@dharambudh1 this sound like a [firebase](https://firebase.flutter.dev/) issue rather than flutter's
maybe the issue should be opened [here](https://github.com/firebase/flutterfire/issues)

**Comment by dharambudh1** [comment]
@iapicca, I am confused as well. I am not sure about it. 
Either it's a Flutter framework issue or a Firebase plugin issue.

**Comment by dharambudh1** [comment]
@iapicca, I am confused as well. I am not sure about it. 
Either it's a Flutter framework issue or a Firebase plugin issue.

**Comment by iapicca** [comment]
> @iapicca, I am confused as well.

@dharambudh1 
I'm not confused, it's definitely a Firebase plugin issue

**Comment by dharambudh1** [comment]
Okay @iapicca, I'm closing this issue from here.
