### ISSUE TITLE
 Implementing out-of-process raster in Flutter Engine

### ISSUE THREAD

**Issue by ajihyf** [flutter/flutter#124489]
## Description

Presently, Flutter generates a DisplayList and sends it out in the same thread. When dealing with raster caches, we also need to wait for the previous cache to finish before compositing them synchronously. 

In contrast, Chromium utilizes an out-of-process raster architecture that transfers Skia GPU commands onto a separate GPU thread. The paint operation in this architecture is quite similar to  DLOp  in Flutter. Is there potential for implementing an OOP-R like architecture within Flutter to enhance concurrency?
@flar 

## References

- The Chromium project's out-of-process raster architecture: https://docs.google.com/presentation/d/1eOjb7CIbXAj3AXGjgWC_RnEY-qUe5ZMc8jfFXE-WPoE

**Comment by chinmaygarde** [comment]
We do have a separate raster thread for preparing and uploading commands to the GPU. So you are already getting the concurrency. Except, this thread isn't out of process. Not sure what problem you are trying to solve in in an application framework like Flutter.

If you have a specific use case for the OOP-R besides concurrency, then let us know. But closing this as WAI.
