### ISSUE TITLE
[Impeller] ToColor converts an SkColor instead of a DlColor.

### ISSUE THREAD

**Issue by flar** [flutter/flutter#124455]
It likely doesn't matter, but the DisplayList should only contain DlColor objects yet the `ToColor` converter in Impeller takes an SkColor as an argument. It turns out these two types can be implicitly converted between each other with no work, but the ToColor method should probably be declared to take a DlColor (and a search done to make sure that there are no instances of SkColor left that it needs to convert).

**Comment by matanlurey** [comment]
I'm going to take this issue to test if my dev environment is setup correctly 😸
