### ISSUE TITLE
Add a "fast fail" argument to `flutter test` to stop after a failure

### ISSUE THREAD

**Issue by sayadzad** [flutter/flutter#124406]
## Use case

Tests may take an hour or more to run, especially in a CI environment with limited resources. If there was an argument for `flutter test` (similar to pytest's `--exitfirst`), then a failure that happens within the first 10 minutes, etc. can stop further test execution. This can allow developers to fix tests and re-run them locally, saving a lot of time and money in a CI.

## Proposal

Add an argument such as `flutter test --exit-first` that will stop further text execution when a failure is hit.

**Comment by gnprice** [comment]
This is a feature I would be glad to see!

To offer a use case different from the one mentioned above: I'd use this feature regularly in an interactive context.
* Sometimes there's a problem that is causing many tests to fail, but all in basically the same way. In that situation I want to focus on just one failure, the first failure, and iterate on debugging that. It's possible to do this by adding a `--name` argument (and that's what I often do); but if the passing tests are fast, then it'd be more convenient to just say `--exit-first` and let it stop at the first failing test automatically.
* Sometimes there's a problem that *was* causing many tests to fail, and I've made what I think might be a fix. I'd like to run all the tests to confirm that; but if I'm wrong, then that will swamp my terminal history with failures. So what I want is precisely `--exit-first`. (What I do now is usually to approximate it by hand: run just a few tests at first, then more, then all of them. I'd rather have the computer take care of it.)

I'm not sure if `flutter test` is the layer this feature would actually be implemented at, though. It might belong at the level of the `dart test` implementation, and then the role of `flutter test` would just be to pass the option through.

**Comment by mpep2** [comment]
`dart test` already has a `--fail-fast` argument, then why isn't `flutter test` passing it to that?
