### ISSUE TITLE
Error while trying to run my project

### ISSUE THREAD

**Issue by JdotDEV** [flutter/flutter#124481]
I am getting this error log while i am trying to run the project:
Please help me with this

`Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
Running Gradle task 'assembleDebug'...
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app-debug.apk...
E/AndroidRuntime(21711): FATAL EXCEPTION: main
E/AndroidRuntime(21711): Process: com.flyweb, PID: 21711
E/AndroidRuntime(21711): java.lang.RuntimeException: Unable to instantiate application com.flyweb.WebNX package com.flyweb: java.lang.ClassNotFoundException: Didn't find class "com.flyweb.WebNX" on path: DexPathList[[zip file "/data/app/~~o9IEapjR34IVDcvaSnVSTQ==/com.flyweb-Hkwf2So6MZXh4GPT_bfNVg==/base.apk"],nativeLibraryDirectories=[/data/app/~~o9IEapjR34IVDcvaSnVSTQ==/com.flyweb-Hkwf2So6MZXh4GPT_bfNVg==/lib/x86_64, /data/app/~~o9IEapjR34IVDcvaSnVSTQ==/com.flyweb-Hkwf2So6MZXh4GPT_bfNVg==/base.apk!/lib/x86_64, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime(21711): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1364)
E/AndroidRuntime(21711): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6695)
E/AndroidRuntime(21711): 	at android.app.ActivityThread.access$1500(ActivityThread.java:256)
E/AndroidRuntime(21711): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2090)
E/AndroidRuntime(21711): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(21711): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(21711): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(21711): 	at android.app.ActivityThread.main(ActivityThread.java:7842)
E/AndroidRuntime(21711): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21711): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(21711): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/AndroidRuntime(21711): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.flyweb.WebNX" on path: DexPathList[[zip file "/data/app/~~o9IEapjR34IVDcvaSnVSTQ==/com.flyweb-Hkwf2So6MZXh4GPT_bfNVg==/base.apk"],nativeLibraryDirectories=[/data/app/~~o9IEapjR34IVDcvaSnVSTQ==/com.flyweb-Hkwf2So6MZXh4GPT_bfNVg==/lib/x86_64, /data/app/~~o9IEapjR34IVDcvaSnVSTQ==/com.flyweb-Hkwf2So6MZXh4GPT_bfNVg==/base.apk!/lib/x86_64, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime(21711): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
E/AndroidRuntime(21711): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(21711): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(21711): 	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
E/AndroidRuntime(21711): 	at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:52)
E/AndroidRuntime(21711): 	at android.app.Instrumentation.newApplication(Instrumentation.java:1189)
E/AndroidRuntime(21711): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1356)
E/AndroidRuntime(21711): 	... 10 more
E/AndroidRuntime(21997): FATAL EXCEPTION: main
E/AndroidRuntime(21997): Process: com.flyweb, PID: 21997
E/AndroidRuntime(21997): java.lang.RuntimeException: Unable to instantiate application com.flyweb.WebNX package com.flyweb: java.lang.ClassNotFoundException: Didn't find class "com.flyweb.WebNX" on path: DexPathList[[zip file "/data/app/~~o9IEapjR34IVDcvaSnVSTQ==/com.flyweb-Hkwf2So6MZXh4GPT_bfNVg==/base.apk"],nativeLibraryDirectories=[/data/app/~~o9IEapjR34IVDcvaSnVSTQ==/com.flyweb-Hkwf2So6MZXh4GPT_bfNVg==/lib/x86_64, /data/app/~~o9IEapjR34IVDcvaSnVSTQ==/com.flyweb-Hkwf2So6MZXh4GPT_bfNVg==/base.apk!/lib/x86_64, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime(21997): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1364)
E/AndroidRuntime(21997): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6695)
E/AndroidRuntime(21997): 	at android.app.ActivityThread.access$1500(ActivityThread.java:256)
E/AndroidRuntime(21997): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2090)
E/AndroidRuntime(21997): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(21997): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(21997): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(21997): 	at android.app.ActivityThread.main(ActivityThread.java:7842)
E/AndroidRuntime(21997): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21997): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(21997): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/AndroidRuntime(21997): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.flyweb.WebNX" on path: DexPathList[[zip file "/data/app/~~o9IEapjR34IVDcvaSnVSTQ==/com.flyweb-Hkwf2So6MZXh4GPT_bfNVg==/base.apk"],nativeLibraryDirectories=[/data/app/~~o9IEapjR34IVDcvaSnVSTQ==/com.flyweb-Hkwf2So6MZXh4GPT_bfNVg==/lib/x86_64, /data/app/~~o9IEapjR34IVDcvaSnVSTQ==/com.flyweb-Hkwf2So6MZXh4GPT_bfNVg==/base.apk!/lib/x86_64, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime(21997): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
E/AndroidRuntime(21997): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(21997): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(21997): 	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
E/AndroidRuntime(21997): 	at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:52)
E/AndroidRuntime(21997): 	at android.app.Instrumentation.newApplication(Instrumentation.java:1189)
E/AndroidRuntime(21997): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1356)
E/AndroidRuntime(21997): 	... 10 more
E/AndroidRuntime(22044): FATAL EXCEPTION: main
E/AndroidRuntime(22044): Process: com.flyweb, PID: 22044
E/AndroidRuntime(22044): java.lang.RuntimeException: Unable to instantiate application com.flyweb.WebNX package com.flyweb: java.lang.ClassNotFoundException: Didn't find class "com.flyweb.WebNX" on path: DexPathList[[zip file "/data/app/~~o9IEapjR34IVDcvaSnVSTQ==/com.flyweb-Hkwf2So6MZXh4GPT_bfNVg==/base.apk"],nativeLibraryDirectories=[/data/app/~~o9IEapjR34IVDcvaSnVSTQ==/com.flyweb-Hkwf2So6MZXh4GPT_bfNVg==/lib/x86_64, /data/app/~~o9IEapjR34IVDcvaSnVSTQ==/com.flyweb-Hkwf2So6MZXh4GPT_bfNVg==/base.apk!/lib/x86_64, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime(22044): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1364)
E/AndroidRuntime(22044): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6695)
E/AndroidRuntime(22044): 	at android.app.ActivityThread.access$1500(ActivityThread.java:256)
E/AndroidRuntime(22044): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2090)
E/AndroidRuntime(22044): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(22044): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(22044): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(22044): 	at android.app.ActivityThread.main(ActivityThread.java:7842)
E/AndroidRuntime(22044): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(22044): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(22044): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/AndroidRuntime(22044): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.flyweb.WebNX" on path: DexPathList[[zip file "/data/app/~~o9IEapjR34IVDcvaSnVSTQ==/com.flyweb-Hkwf2So6MZXh4GPT_bfNVg==/base.apk"],nativeLibraryDirectories=[/data/app/~~o9IEapjR34IVDcvaSnVSTQ==/com.flyweb-Hkwf2So6MZXh4GPT_bfNVg==/lib/x86_64, /data/app/~~o9IEapjR34IVDcvaSnVSTQ==/com.flyweb-Hkwf2So6MZXh4GPT_bfNVg==/base.apk!/lib/x86_64, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime(22044): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
E/AndroidRuntime(22044): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(22044): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(22044): 	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
E/AndroidRuntime(22044): 	at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:52)
E/AndroidRuntime(22044): 	at android.app.Instrumentation.newApplication(Instrumentation.java:1189)
E/AndroidRuntime(22044): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1356)
E/AndroidRuntime(22044): 	... 10 more`

**Comment by darshankawar** [comment]
@JdotDEV 
Can you provide `flutter doctor -v` along with gradle version you are using ?
Also if possible, provide a minimal code sample that shows the reported error log.

**Comment by JdotDEV** [comment]
> @JdotDEV Can you provide `flutter doctor -v` along with gradle version you are using ? Also if possible, provide a minimal code sample that shows the reported error log.

Flutter doctor

[√] Flutter (Channel stable, 3.7.9, on Microsoft Windows [Version 10.0.22621.1413], locale en-IN)
    • Flutter version 3.7.9 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 62bd79521d (11 days ago), 2023-03-30 10:59:36 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\isaty\AppData\Local\Android\sdk
    • Platform android-UpsideDownCake, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] VS Code (version 1.77.1)
    • VS Code at C:\Users\isaty\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.62.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 32) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.1413]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 111.0.5563.148
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 112.0.1722.34

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



android\build.gradle

buildscript {
    ext.kotlin_version = '1.6.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        // FIREBASE PACKAGES
        classpath 'com.google.gms:google-services:4.3.10'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}






app\build.gradle

buildscript {
    repositories {
        // ...
        maven { url 'https://plugins.gradle.org/m2/' } // Gradle Plugin Portal
    }
    dependencies {
        // ...
        // OneSignal-Gradle-Plugin
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.10.2, 0.99.99]'
    }
}

apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

// FIREBASE PACKAGES
apply plugin: 'com.google.gms.google-services'

android {
    compileSdkVersion 33

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    lintOptions {
        checkReleaseBuilds false
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }


    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.flyweb"
        minSdkVersion 19
        targetSdkVersion 33
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        manifestPlaceholders = [
                onesignal_app_id: 'e0868418-0ef5-40e3-ab54-71f7126daef1',
                onesignal_google_project_number: '300944171144'
        ]
        // FIREBASE PACKAGES
        multiDexEnabled true
    }

    signingConfigs {
        release {
            storeFile file(storeFile_)
            storePassword storePassword_
            keyAlias keyAlias_
            keyPassword keyPassword_
        }
        debug {
            storeFile file(storeFile_)
            storePassword storePassword_
            keyAlias keyAlias_
            keyPassword keyPassword_
        }
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    // FIREBASE PACKAGES
    implementation 'com.android.support:multidex:2.0.1'
    implementation "androidx.constraintlayout:constraintlayout:2.1.3"

    // Import the Firebase BoM
    implementation platform('com.google.firebase:firebase-bom:29.3.1')

    // Add the dependency for the Firebase SDK for Google Analytics
    // When using the BoM, don't specify versions in Firebase dependencies
    implementation 'com.google.firebase:firebase-analytics'
}

**Comment by darshankawar** [comment]
Can you remove the onesignal dependency / implementation and try again without it and see if you still get the same error or not ?
