### ISSUE TITLE
RefreshIndicator drag distance is too long after add SliverOverlapAbsorber and SliverOverlapInjector 

### ISSUE THREAD

**Issue by RakaAlrian** [flutter/flutter#124412]
I have a NestedScrollView, I set the headerSliverBuilder with a SliverToBoxAdapter and a pinned SliverAppBar. Then I set the body of NestedScrollView with a ListView inside RefreshIndicator. But then I got an issue, the listview goes behind the pinned SliverAppBar even when the list is not filling the screen. For that issue I implement this [comment](https://github.com/flutter/flutter/issues/62194#issuecomment-665843016) with a little modification _(wrap builder with RefreshIndicator)_ and it kinda fix the issue.

But turns out, that fix create another issue, now my refresh indicator need a longer drag distance to trigger the refresh.

<details>
<summary>Code sample</summary>

```dart
class BugRefreshIndicator extends StatefulWidget {
  const BugRefreshIndicator({super.key});

  @override
  State<StatefulWidget> createState() => _BugRefreshIndicatorState();
}

class _BugRefreshIndicatorState extends State<BugRefreshIndicator> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.amber,
      ),
      body: NestedScrollView(
        headerSliverBuilder: (context, innerBoxIsScrolled) {
          return [
            SliverToBoxAdapter(
              child: Container(
                height: .1.sh,
                alignment: Alignment.center,
                child: Text("Some Widget"),
              ),
            ),
            SliverOverlapAbsorber(
              handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
              sliver: SliverAppBar(
                pinned: true,
                automaticallyImplyLeading: false,
              ),
            ),
          ];
        },
        body: RefreshIndicator(
          onRefresh: () async {},
          child: Builder(
            builder: (context) {
              return CustomScrollView(
                slivers: [
                  SliverOverlapInjector(
                    handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
                  ),
                  SliverList(
                    delegate: SliverChildBuilderDelegate(
                      (context, index) => Text("Index: $index"),
                      childCount: 5,
                    ),
                  ),
                ],
              );
            },
          ),
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Flutter doctor</summary>

```
[√] Flutter (Channel stable, 3.7.1, on Microsoft Windows [Version 10.0.22621.1413], locale id-ID)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Android Studio (version 2021.2)
[√] IntelliJ IDEA Community Edition (version 2020.2)
[√] VS Code (version 1.77.1)
[√] Connected device (1 available)
[√] HTTP Host Availability

• No issues found!
```

</details>

<details>
<summary>Video</summary>

https://user-images.githubusercontent.com/57884963/230657341-c258ae62-c02e-4766-9fbc-d4173a9285ed.mp4

</details>

<details>
<summary>Expected</summary>

https://user-images.githubusercontent.com/57884963/230661750-5142f9ec-867c-4b00-8658-1a09c793301a.mp4

</details>

**Comment by exaby73** [comment]
Hello @RakaAlrian. Are you able to reproduce this issue on the latest master channel?

**Comment by RakaAlrian** [comment]
> Hello @RakaAlrian. Are you able to reproduce this issue on the latest master channel?

Yes, I can reproduce the issue on master channel

<details>
<summary>flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 3.10.0-2.0.pre.29, on Microsoft Windows [Version 10.0.22621.1413], locale id-ID)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Android Studio (version 2021.2)
[√] IntelliJ IDEA Community Edition (version 2020.2)
[√] VS Code (version 1.77.1)
[√] Connected device (1 available)
[√] Network resources

• No issues found!
```

</details>

**Comment by exaby73** [comment]
In your code sample, you are setting the height as `height: .1.sh,`. What value are you actually putting over there?

**Comment by RakaAlrian** [comment]
> In your code sample, you are setting the height as `height: .1.sh,`. What value are you actually putting over there?

I'm using [flutter_screenutil](https://pub.dev/packages/flutter_screenutil), and .1.sh mean 0.1 of screen height. But actually the value doesn't mater, I tried change it to constant values(50, 100, 200, etc) and the issue still exist.

**Comment by exaby73** [comment]
I don't think the drag distance is actually affected. Adding a bit of delay into the `RefreshIndicator`, you can see the loading indicator actually clipping with the `SliverAppBar`. Using a normal `ListView`, I was able to drag the same distance and trigger the `RefreshIndicator`. Difference is that in your case, part of the indicator is hidden by the `SliverAppBar`.

<img width="300" src="https://user-images.githubusercontent.com/50555895/231092535-a0dbb89a-8ca6-4291-8fe5-048098994d1c.png">

**Comment by exaby73** [comment]
What about wrapping the `NestScrollView` itself in the `RefreshIndicator`?
