### ISSUE TITLE
Project not compiled for windows 11

### ISSUE THREAD

**Issue by alex9153** [flutter/flutter#124438]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Run project

### Actual results

not compiled ... and clean project not helped

### Logs

Launching lib\main.dart on Windows in debug mode...
main.dart:1
LINK : fatal error LNK1168: �� 㤠���� ������ D:\Projects\homm3\homm3_server_new\build\windows\runner\Debug\homm3_server_new.exe ��� ����� [D:\Projects\homm3\homm3_server_new\build\windows\runner\homm3_server_new.vcxproj]
Exception: Build process failed.
Exited (sigterm)

### Flutter Doctor output

[flutter] flutter doctor -v
[√] Flutter (Channel stable, 3.7.5, on Microsoft Windows [Version 10.0.22621.1413], locale ru-RU)
    • Flutter version 3.7.5 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c07f788888 (6 weeks ago), 2023-02-22 17:52:33 -0600
    • Engine revision 0f359063c4
    • Dart version 2.19.2
    • DevTools version 2.20.1

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\\Android\sdk
    • Platform android-33-ext4, build-tools 33.0.2
    • Java binary at: C:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33403.182
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] VS Code (version 1.77.0)
    • VS Code at C:\Users\Aleks\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.60.0

[√] Connected device (4 available)
    • SM T970 (mobile)  • R52N71EFXPN • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.22621.1413]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 111.0.5563.147
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 111.0.1661.62

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
exit code 0

**Comment by alex9153** [comment]
Only reboot computer fix this problem

**Comment by huycozy** [comment]
Hi @alex9153 
Can you reproduce this issue again? And does it happen on a newly created project?

The issue should be actionable with clear steps to reproduce it. If you can reproduce it, please provide the complete output of `flutter run -v` so that we may verify the issue. Thanks!
