### ISSUE TITLE
It does not make the direct call, it only puts the number

### ISSUE THREAD

**Issue by RicharU1** [flutter/flutter#124469]
I'm having a problem , when I make a direct call it doesn't make it, it just takes me to the calls application and puts the number, I have to call it, is there a way to call automatically?

**Comment by iapicca** [comment]
@RicharU1 
this doesn't sound like a bug report or a feature request,
if you need help maybe is better to ask on [discord](https://discord.com/invite/N7Yshp4) of [stackoverflow](https://stackoverflow.com/tags/flutter)

**Comment by stuartmorgan** [comment]
In the future, please fill in the issue template when filling an issue.

Assuming (since you've provided no example code or details) that you are talking about the `url_launcher` plugin, how the launched application handles a URL is up to that application, not the plugin.
