### ISSUE TITLE
iOS app is too slow and is lagging

### ISSUE THREAD

**Issue by giovanni256** [flutter/flutter#124430]
## Details
Hi there.

I updated my app from Flutter 3.7 to 3.9.0-pre20.
The app was running smoothly but since the update I'm having a lot of problems because the app is really slow.
I'm getting performance issues on each page.

I'm also updating to the latest master channel version available.

Since is not so easy, I upload some files to help to find out the issue while I'm creating the reproducible example.
I tracked it using Flutter DevTools.

During the recording I was opening some pages and then going back.
The app was lagging everytime.

**Target Platform:** Only iOS (Android is working perfectly)
**Target OS version/browser:** iOS 15.5
**Devices:** iOS Simulator, iPhone 13, iPhone 12 Pro

## Logs

<details>
<summary>Logs</summary>

```
warning • Publishable packages can't have 'git' dependencies • pubspec.yaml:37:5 • invalid_dependency
warning • Publishable packages can't have 'git' dependencies • pubspec.yaml:43:5 • invalid_dependency
warning • Publishable packages can't have 'git' dependencies • pubspec.yaml:79:5 • invalid_dependency
warning • Publishable packages can't have 'git' dependencies • pubspec.yaml:95:5 • invalid_dependency
```

```
[✓] Flutter (Channel master, 3.9.0-22.0.pre.67, on macOS 12.4 21F79 darwin-x64, locale it-IT)
    • Flutter version 3.9.0-22.0.pre.67 on channel master at /Users/macnew/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e6257302db (26 hours ago), 2023-04-06 12:58:18 -0700
    • Engine revision 9620c64824
    • Dart version 3.0.0 (build 3.0.0-411.0.dev)
    • DevTools version 2.23.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/macnew/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.69.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • iPhone 13 (mobile) • FDB8321C-CE66-4466-A084-940086AAE6CC • ios        • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64 • macOS 12.4 21F79 darwin-x64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

## Flutter DevTools CPU Profiler
[dart_devtools_2023-04-07_23_47_09.326.json.zip](https://github.com/flutter/flutter/files/11182713/dart_devtools_2023-04-07_23_47_09.326.json.zip)

Sorry for the external link, the file is too big.

**Comment by jonahwilliams** [comment]
You should be able to zip these files and attach them to the issue.

Alternative  please upload these files to something that doesn't look like a phishing site.

**Comment by giovanni256** [comment]
> You should be able to zip these files and attach them to the issue.
> 
> Alternative please upload these files to something that doesn't look like a phishing site.

HI there, I'm still working on a reproducible example.
Sorry for the file, I just avoided to upload a ZIP.

[dart_devtools_2023-04-07_23_47_09.326.json.zip](https://github.com/flutter/flutter/files/11182713/dart_devtools_2023-04-07_23_47_09.326.json.zip)

**Comment by jonahwilliams** [comment]
Thanks!

**Comment by jonahwilliams** [comment]
1. It looks like the application you're profiling has voice over on? Can you confirm if this is expected. There is a bit more work to be done each frame but that hasn't changed recently

2. This is a CPU profile which will show cases where you're blocking on the UI thread, but doesn't show the overall frame workload. You'll want to upload a timeline trace insterad

**Comment by giovanni256** [comment]
> 1. It looks like the application you're profiling has voice over on? Can you confirm if this is expected. There is a bit more work to be done each frame but that hasn't changed recently
> 2. This is a CPU profile which will show cases where you're blocking on the UI thread, but doesn't show the overall frame workload. You'll want to upload a timeline trace insterad

1. As voice over do you mean the vocal description of screen content? If yes, this is unexpected since I don't want that.

2. How can I get a timeline trace and export it for sharing?

Thanks for your help!

**Comment by jonahwilliams** [comment]
I can't tell you why semantics are enabled. Can you share a smaller example that reproduces some of these issues?

This timeline trace is showing both 100ms + raster times, but I'm also seeing 100ms+ ui thread times. Its possible you checked out a particular bad version from master, but its also possible we're doing something quite wrong with this app.

**Comment by giovanni256** [comment]
> I can't tell you why semantics are enabled. Can you share a smaller example that reproduces some of these issues?
> 
> This timeline trace is showing both 100ms + raster times, but I'm also seeing 100ms+ ui thread times. Its possible you checked out a particular bad version from master, but its also possible we're doing something quite wrong with this app.

I really don't know why this is happening.
I just upgraded from 3.7.0 to the master branch.
I had some problems with the plugins that I Need to use, so I'm using some of them with my repo using the "Git" source.

I also want to tell you that before the upgrade, I tested the app with Flutter 3.7 and It was working well.

I'm still working on the example.

Thank you and happy Easter!

**Comment by jonahwilliams** [comment]
You could also try getting a xcode frame capture: https://developer.apple.com/documentation/metal/debugging_tools/enabling_frame_capture?language=objc

This will tell us exactly what we're spending so much time on in the GPU

**Comment by giovanni256** [comment]
> You could also try getting a xcode frame capture: https://developer.apple.com/documentation/metal/debugging_tools/enabling_frame_capture?language=objc
> 
> This will tell us exactly what we're spending so much time on in the GPU

Hi there!
I'm getting these errors:

`libsystem_kernel.dylib`mach_msg_trap:
    0x7fff7016c970 <+0>:  movq   %rcx, %r10
    0x7fff7016c973 <+3>:  movl   $0x100001f, %eax          ; imm = 0x100001F 
    0x7fff7016c978 <+8>:  syscall 
->  0x7fff7016c97a <+10>: retq   
    0x7fff7016c97b <+11>: nop    
`

I'm getting warnings on:
`Malloc 48 Bytes
0x6000024733f0
0x600002473de0
0x600002578c90
0x60000257a0d0
0x60000257a190
0x6000025b0d20

Malloc 32 Bytes
0x600002b3bac0
0x600002b6b100
0x600002bb1cc0

Malloc 16 Bytes
0x6000029e0270
0x6000029ec680
0x6000029ec6a0
`

**Comment by jonahwilliams** [comment]
Sorry I can't do anything with that. You'll need to post the entire error and validation message

**Comment by giovanni256** [comment]
> 

I'm not getting error in the console, these are the errors shown from the Xcode Frame Capture

**Comment by giovanni256** [comment]
Since I'm still working on the reproducible example, I tried to downgrade Flutter to 3.7.11 and the app is working well in debug mode but when I try to build the IPA I get the error in issue #123051 

I also tried to upgrade to the latest master channel updates but even if the IPA builds up, the app is still too slow.

**Comment by giovanni256** [comment]
Hi there, I finally found the issue that you should tell to anyone who wants to upgrade to Flutter 3.9 or above.

The problem was in Xcode that needs to be 14.2 or above.
I also upgraded the Xcode Command Lines and finally the app is working as expected.

Thanks to anyone who spent time to help me!
