### ISSUE TITLE
Internationalization DateFormat issue

### ISSUE THREAD

**Issue by MopheusDG** [flutter/flutter#124460]
Hi, I'm having a very small issue and not sure if it's a bug or what when following this steps for Internationalization: https://docs.flutter.dev/development/accessibility-and-localization/internationalization

Everything works fine, but if I use this Dateformat('MMM') in English shows "Apr", but in spanish shows "abr", is this normal ? Why in spanish it's not "Apr" ?

Thanks.

**Comment by danagbemava-nc** [comment]
April in Spanish is `abril`. See https://www.lawlessspanish.com/vocabulary/calendar/ & https://langster.org/en/blog/seasons-days-and-months-in-spanish

Closing as this is not a flutter issue.

Thank you

**Comment by MopheusDG** [comment]
Hi @danagbemava-nc I know it's "Abril", I'm from Argentina. My question is why is "Apr" in English with the first letter in uppercase and "abr" in spanish with all letters in lowercase. Is this a language issue too ?
