### ISSUE TITLE
Web Accessibility: Tabs on the Flutter TabBar switches automatically without clicking on Tab when Voiceover is ON

### ISSUE THREAD

**Issue by aakashawalkar** [flutter/flutter#124494]
## Steps to Reproduce

1. Execute `flutter run -d chrome` on the code sample
2. Decrease browser window zoom level to 90%
3. Try navigating through the data under the Tabs, Tabs will switch automatically without even clicking on it

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

Code Repo:  [Click here](https://github.com/mfdcoder/flutter-form-voiceover/tree/staging)

Code files: 
- main.dart
- tabbar.dart

</details>

<details>
  <summary>Logs</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.10, on macOS 13.2.1 22D68 darwin-x64, locale en-IN)
[✓]  Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.77.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

[✓] No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @aakashawalkar 
When navigating between Tabs, I see it works as expected, please see:

https://user-images.githubusercontent.com/104349824/230896152-4c81e377-3288-4a04-a6ad-fe4ac23afca6.mov

I'm not sure I'm missing any steps, could you provide a recorded video to represent this issue?

**Comment by aakashawalkar** [comment]
Hi @huycozy, PFA

Steps to reproduce:
1] Set zoom level to 90%
2] Navigate to `TAB 2` via VO commands
3] Try navigating the data/content under `TAB 2`, the user is automatically switched to `TAB 1`

https://user-images.githubusercontent.com/97581635/230906622-a51586cb-285a-46b8-89ee-905ae56139b7.mov

**Comment by aakashawalkar** [comment]
When Voiceover is ON, to press/click - Windows: `Ctrl + Alt + Space` /  Mac: `Ctrl + Option + Space`

**Comment by huycozy** [comment]
Thanks! I can select Tab 2 now, but the issue doesn't happen even when the zoom is 90%.

https://user-images.githubusercontent.com/104349824/231095279-59d32d1f-d554-4260-b394-5d5e6d1cbd47.mov

What is your Chrome version? (Please provide the output of `flutter doctor -v`). Also, can you please try on Safari as well?

**Comment by aakashawalkar** [comment]
Hi @huycozy,
The actual problem is NOT about pressing/clicking on`TAB 2`. The actual problem is while navigating or iterating the 'data content' under `TAB 2`, then the tab is switched automatically to `TAB 1`.

**Comment by huycozy** [comment]
>then the tab is switched automatically to TAB 1.

Hi, I know you are trying to show this issue, but please take a look at my recorded video above, the issue doesn't happen when I switch to TAB 2 (the tab is not switched automatically to TAB 1).

**Comment by aakashawalkar** [comment]
> the issue doesn't happen when I switch to TAB 2 (the tab is not switched automatically to TAB 1).

Hi, according to your video, you may not navigate through the data under the tabs because the highlight indicator is just on the tabs.

Also, I have modified the data under both tabs.
Here is a video for your reference. In video you will able to see that as soon as I move 'Four, Value Four' data under `TAB 2`, the tab is automatically switched to `TAB 1' and VO continues to read data under `TAB 2`. 


https://user-images.githubusercontent.com/97581635/231958438-a7f93a16-0a97-4282-81e3-95a191a50aba.mov

**Comment by huycozy** [comment]
Thanks for your patience but I still can not reproduce this issue. I also try updating the Tab 2 data for more clear:

https://user-images.githubusercontent.com/104349824/232038951-82d7640f-6279-4abb-9098-dd4a22d34092.mov

Do you run the web with a specific rendering mode?

**Comment by aakashawalkar** [comment]
@huycozy, Thank you for taking the time to work on this. 

I am running the app using 'flutter run -d chrome'

The steps followed by you are correct. You need to do one additional step i.e. Navigate to the first record of `TAB 2` using the keyboard

**Comment by huycozy** [comment]
I think I found the clear steps to reproduce this. It doesn't relate to window zoom level, it can even reproduce when zoom level is 100%.

The key step is holding `Ctrl + Option` keys when navigating to TAB 2's content area. If I release and press these keys again, and then go to TAB 2's content area, the issue doesn't happen. 

Could you try this to see if they are the correct steps? (and try with window zoom level 100% too)

**Comment by aakashawalkar** [comment]
I am able to reproduce the issue only on zoom levels other than 100% but it is reproducible on my QA's machine at 100%.
I think this issue is not just dependent on browser zoom levels but also on different screen sizes.

**Comment by huycozy** [comment]
Adding more insights about this, it looks like the issue is not really a TabBar's issue, because the issue doesn't happen when I omit other widgets from your sample code (complex widget tree with other custom widgets), keep only MyTabBar widget in the tree.  Please also try this case from your end as well.

I would suggest you keep an eye on it if you are able to replicate it consistently and see if it has any pattern. And please write a comment when you have clear steps to reproduce it. Also, the sample code should be minimal so that we can address it better. Thank you!
