### ISSUE TITLE
[google_maps_flutter] Google map package makes IOS Runner run in Intel mode (Macbook M1)

### ISSUE THREAD

**Issue by vantoan19** [flutter/flutter#124441]
After installing google_maps_flutter and add API_KEY to AppDelegate.swift, the Runner process start up in Intel mode (while my laptop is using M1 Silicon CPU), which affects the performance a lot and the CPU usage is always between 100-300%. 

Does anyone have any idea? 
Thank you so much in advance!

**Comment by stuartmorgan** [comment]
This is tracked in https://github.com/flutter/flutter/issues/94491; closing as a duplicate.
