### ISSUE TITLE
Inconsistent behaviour with library using mirrors

### ISSUE THREAD

**Issue by Tomucha** [flutter/flutter#12440]
## Steps to Reproduce

Create basic example Flutter project "Flutter Demo Home Page" (the one with "plus FAB" and counter in the center). Or any simple project, I don't think it matters.

Add  `pointycastle: "^0.10.0+5"` to your dependencies and "get packages".

Create a new instance of AESFastEngine, for example like this:

```dart
  void _incrementCounter() {
    setState(() {
      print("AES is here");
      new AESFastEngine();
      _counter++;
    });
  }

```

Run app on Android (I tested Nexus 5x and few tablets). Full restart!

The app will start and you will see "Flutter Demo Home Page". Push the "plus FAB button" and you should see something like:

```
Launching lib/main.dart on Nexus 5X in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Built build/app/outputs/apk/app-debug.apk (21.4MB).
Installing build/app/outputs/apk/app.apk...
Syncing files to device Nexus 5X...

I/flutter ( 2441): AES is here

```
... which I see in my console. So far so good.

Now change some white space (for example), and try hot-reload. You should see:

```
Initializing hot reload...
Hot reload was rejected:
'package:reflectable/src/reflectable_mirror_based.dart': error: line 13 pos 1: import of dart:mirrors with --enable-mirrors=false
import 'dart:mirrors' as dm;
... etc
```

## Problem

Yes, I get it! I cannot use mirrors in Flutter app. The point is - AESFastEngine imports mirrors (indirectly), but (IMHO) doesn't use them. So from the example above - I can run my app (full restart), but I cannot "hot redeploy" it. Which is just **painfull**.

Can you do something about it? If you cannot fix hot-redeploy, maybe consider crashing immediately with the first start?

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.12.6 16G29, locale cs-CZ, channel master)
    • Flutter at /Users/tomucha/opt/flutter
    • Framework revision dc47238602 (3 weeks ago), 2017-09-15 12:26:00 +0200
    • Engine revision 0e8ffa24e0
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/tomucha/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.2)
    • Flutter plugin version 16.0
    • Dart plugin version 172.3757.55

[✓] Connected devices
    • Nexus 5X • 0103fbe4e54e98c7 • android-arm • Android 8.0.0 (API 26)

**Comment by eseidelGoogle** [comment]
Reminds me of https://github.com/flutter/flutter/issues/9413.

**Comment by Tomucha** [comment]
... by "hot-redeploy" I mean "Hot Reload" :-)

**Comment by Hixie** [comment]
cc @rmacnak-google @a-siva
