### ISSUE TITLE
i have issue on pod install

### ISSUE THREAD

**Issue by nadeemabualarayes** [flutter/flutter#124589]
husseinshreem@Nadeems-MacBook-Pro ios % pod install

[!] Invalid `Podfile` file: undefined method `exists?' for File:Class.

from /Users/husseinshreem/Development/example/Vanilla-HR-new-version/ios/Podfile:34 
 flutter_install_all_ios_pods File.dirname(File.realpath( _ _ FILE _ _ ))
end

**Comment by darshankawar** [comment]
@nadeemabualarayes 
Check [this](https://github.com/flutter/flutter/issues/118295) similar issue and underlying comments for solution.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.
