### ISSUE TITLE
Error (Xcode): Oops; flutter has exited unexpectedly: "RangeError (index): Invalid value: Valid value range is empty: 0".

### ISSUE THREAD

**Issue by mozartee** [flutter/flutter#124502]
![image](https://user-images.githubusercontent.com/5276499/230873214-9bf311a5-4027-4c69-8d40-632b7136c926.png)

When I run my flutter app,It may be field with 'Error (Xcode): Oops; flutter has exited unexpectedly: "RangeError (index): Invalid value: Valid value range is empty: 0".' Even if I create a new application.

And the 'flutter doctor' like this:
![image](https://user-images.githubusercontent.com/5276499/230876000-aca4dc90-9d3a-4dab-8f27-d851a38cd325.png)

**Comment by exaby73** [comment]
Hello @mozartee. Looks like you have an older version of Xcode installed. Could you update Xcode to version 14 and try again?

**Comment by mozartee** [comment]
Thanks @exaby73, but it run successfully in my another MacBook Pro with the same MacOS System and Xcode version.

**Comment by exaby73** [comment]
Could you provide the output of `flutter run -v`?

**Comment by exaby73** [comment]
I cannot reproduce this issue. Therefore I'll label it for visibility and insights

**Comment by mozartee** [comment]
I got success with update the macOS from 12.6.1 to 12.6.5, uninstall VSCode, and install the M1 version. It's crazy! 😅

Thanks for help!
