### ISSUE TITLE
[ASK Question] How To Run Process.start/run unix shell In Flutter Android App?

### ISSUE THREAD

**Issue by Alexaagatha** [flutter/flutter#124509]
Sorry I asked here because I've asked on stack but no one answered

I'm trying to make a termux-like app but using flutter,

I just want to run my executable in code dart

code:

```dart
      Directory directory_app = await getApplicationDocumentsDirectory();

      File file = File(path.join(directory_app.path, "cli-test"));
      Future<void> extractCliFromAsset() async {
        var content = await rootBundle.load("assets/cli-test");
        await file.writeAsBytes(content.buffer.asUint8List(), mode: FileMode.writeOnly);
      }

      if (!file.existsSync()) {
        await extractCliFromAsset();
      }

      Process shell = await Process.start(
        file.path,
        [
          "run"
        ],
        workingDirectory: directory_app.path,
        runInShell: false,
      );

      shell.stderr.listen((event) {
        stderr.add(event);
      });

      shell.stdout.listen((event) {
        stdout.add(event);
      });
```

then the error permission denied appears,

I've tried doing chmod to give write storage access,

I've Tried Doing use package
 1. https://pub.dev/packages/shell
 2. https://pub.dev/packages/process_run

I've Tried Save Executable on storage external,
I've Tried change runInShell, change environment 

but nothing works the program I'm running doesn't ask for root at all

how to be able to run unix shell cli programs in android app?

i want my flutter app to run unix shell without root

**Comment by exaby73** [comment]
Hello @Alexaagatha. Are there any logs in the logcat in Android Studio that might help debug this issue? You can also look at how Termux did it. It's open source, and the code is available at https://github.com/termux/termux-app. Other than that, you can find more resources to ask questions like this on https://flutter.dev/community. Since this is not an issue with Flutter itself, I will close this issue. Thank you

**Comment by Alexaagatha** [comment]
> Hello @Alexaagatha. Are there any logs in the logcat in Android Studio that might help debug this issue? You can also look at how Termux did it. It's open source, and the code is available at https://github.com/termux/termux-app. Other than that, you can find more resources to ask questions like this on https://flutter.dev/community. Since this is not an issue with Flutter itself, I will close this issue. Thank you

![Screenshot from 2023-04-10 20-20-26](https://user-images.githubusercontent.com/123380752/230908914-e2aba749-d92f-4cb6-94e8-56ffa6a6ff7c.png)

**Comment by Alexaagatha** [comment]
![Screenshot from 2023-04-10 20-31-12](https://user-images.githubusercontent.com/123380752/230910793-090a5e04-5680-41e2-b4ad-032d35100b77.png)

I tried in adb shell and normal but not flutter app

**Comment by exaby73** [comment]
I'm guessing you can't run commands from that directory with rooting your device. Try something like `ls` or `echo`
