### ISSUE TITLE
Broken Hyperlink in https://codelabs.developers.google.com/codelabs/flutter-firebase/#8

### ISSUE THREAD

**Issue by abnerh69** [flutter/flutter#12450]
**## Steps to Reproduce**

Go to: https://codelabs.developers.google.com/codelabs/flutter-firebase/#8
under "Use an AnimatedList" find FirebaseAnimatedList hyperlink and click on it.  Goes to GitHub 404 (Page not found)

Thanks for this amazing framework tool!

Abner

**Edit:**
I did found this mistake because in code example for FirebaseAnimatedList, on itemBuilder there are 3 parameters, but on IntelliJ IDEA, it seems to need one more parameter (int).  Please check it.  Thanks again.

**Comment by Hixie** [comment]
This seems to be resolved now, I can't find that link on the codelab anymore.
