### ISSUE TITLE
/examples/rendering/touch_demo.dart is broken

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#1245]
When I do `flutter start -t touch_demo.dart`, I get a white screen on the device and that's it.

I'm running at commit abb17ea93f and I did a `pub get`.

**Comment by Hixie** [comment]
@abarth may have looked at this demo recently

**Comment by abarth** [comment]
This example is now at //examples/layers/rendering/touch_demo.dart and is working for me.  Are you still seeing a problem?

**Comment by abarth** [comment]
Please re-open if you're still having trouble.
