### ISSUE TITLE
Cannot customize size of SegmentedButton

### ISSUE THREAD

**Issue by math1man** [flutter/flutter#124539]
## Steps to Reproduce

1. Execute `flutter run` on the code sample

**Expected results:**

`SegmentedButton` and `OutlinedButton` should be the same height.

**Actual results:**

`SegmentedButton` height is unchanged from the default style.

I believe the root of the issue is that `minimumSize`, `maximumSize`, and `fixedSize` are omitted from [here](https://github.com/flutter/flutter/blob/05e1ffe4803d63f18966f5ac30017a7309d25c45/packages/flutter/lib/src/material/segmented_button.dart#L281-L299). From local testing, even that change might not be sufficient though.

While I was looking into the implementation, I also noticed that there's a bug on [this line](https://github.com/flutter/flutter/blob/05e1ffe4803d63f18966f5ac30017a7309d25c45/packages/flutter/lib/src/material/segmented_button.dart#L347) as well. It should specify `enabledState` instead of `disabledState`.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.light(useMaterial3: true).copyWith(
        visualDensity: VisualDensity.standard,
      ),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatefulWidget {
  @override
  State<MyWidget> createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> {
  var value = true;

  static const buttonStyle = ButtonStyle(
    minimumSize: MaterialStatePropertyAll(
      Size(48, 32),
    ),
  );

  @override
  Widget build(BuildContext context) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        SegmentedButton<bool>(
          style: buttonStyle,
          showSelectedIcon: false,
          selected: {value},
          onSelectionChanged: (selected) {
            setState(() {
              value = selected.single;
            });
          },
          segments: const [
            ButtonSegment<bool>(
              value: true,
              label: Text('True'),
            ),
            ButtonSegment(
              value: false,
              label: Text('False'),
            ),
          ],
        ),
        const SizedBox(width: 8),
        OutlinedButton(
          style: buttonStyle,
          onPressed: () {
            setState(() {
              value = !value;
            });
          },
          child: const Text('Button'),
        ),
      ],
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

I created and demo'ed the example code in DartPad. I don't have actual logs.
</details>

**Comment by BrunoRabbit** [comment]
Hi @math1man, segmented button and outlined button have different internal sizes, so the result is different, u can try to add a container with height and width which will come out with your result, please try this
```
SizedBox(
          width: 120,
          height: 50, // ! Must be same as OutlinedButton size
          child: SegmentedButton<bool>(
            showSelectedIcon: false,
            selected: {value},
            onSelectionChanged: (selected) {
              setState(() {
                value = selected.single;
              });
            },
            segments: const [
              ButtonSegment<bool>(
                value: true,
                label: Text('True'),
              ),
              ButtonSegment(
                value: false,
                label: Text('False'),
              ),
            ],
          ),
        ),
        const SizedBox(width: 8),
        SizedBox(
          height: 50, // this size
          width: 80,
          child: OutlinedButton(
            onPressed: () {
              setState(() {
                value = !value;
              });
            },
            child: const Text('Button'),
          ),
        ),
        ```

**Comment by math1man** [comment]
That correctly changes the size, but the text alignment is broken:

![image](https://user-images.githubusercontent.com/4040946/230986724-c1b64200-5040-4e3a-b0ba-5631d05bb2e2.png)

> segmented button and outlined button have different internal sizes

From what I can tell, `OutlinedButton` has a customizable internal size and `SegmentedButton` doesn't. This issue is requesting feature parity so that you can control the size of `SegmentedButton` the same way as other material buttons.

**Comment by rydmike** [comment]
Potential duplicate, or at least very related:

- [ ] https://github.com/flutter/flutter/issues/121493

Other known `SegmentedButton` issue(s):

- [ ] https://github.com/flutter/flutter/issues/123308

**Comment by rydmike** [comment]
I agree with you @math1man, a very highly needed use case is to make `SegmentedButton` match whatever height (default/custom) you used on `OutlinedButton`, `ElevatedButton` and `FilledButton`.

With old `ToggleButtons` this is doable, but not with `SegmentedButton`. I noticed this issue as well when making FlexColorScheme and trying to use any kind of sizing (theme or widget props) on it. I was also unable to change the `SegementedButton` to anything.

![Screenshot 2023-04-11 at 1 06 15](https://user-images.githubusercontent.com/39990307/231008452-9db0499f-895c-4e4d-8387-562aea4e3b0e.png)


Some more info about why that is so, can be found here https://github.com/flutter/flutter/issues/121493#issuecomment-1480138494

**Comment by exaby73** [comment]
Looks like a valid proposal.Thanks @math1man for raising this and @rydmike for the additional information on it :)

**Comment by math1man** [comment]
I think it would be reasonable to duplicate this to https://github.com/flutter/flutter/issues/121493. That issue describes this issue in full and then some.
