### ISSUE TITLE
Significant size increases across all iOS builds

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#124572]
See: https://flutter-flutter-perf.skia.org/e/?begin=1681173515&end=1681183285&keys=Xb21246d4468ffbe9c99b6dd606e4b490&selected=commit%3D34297%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253Drelease_size_bytes%252Ctest%253Dcomplex_layout_ios__compile%252C&xbaroffset=34296

https://flutter-flutter-perf.skia.org/e/?begin=1681168801&end=1681183285&keys=X955c14461efc5582079c46ce5fa7e29c&selected=commit%3D34297%26name%3D%252Carch%253Darm%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253Dflutter_framework_uncompressed_bytes%252Ctest%253Dhello_world_ios__compile%252C&xbaroffset=34295

Compressed size bytes has nearly doubled on hello_world

This happend on https://github.com/flutter/flutter/pull/124562 . I suspect it was probably https://github.com/flutter/engine/pull/40844 .

**Comment by jason-simmons** [comment]
The size of the `ios-release/Flutter.xcframework/ios-arm64/Flutter.framework/Flutter` artifact has increased by 80% for some builds around the time of the engine_v2 switch.

(Other configurations of the iOS engine do not seem to be affected)

Not every recent engine commit has the larger `ios-release/arm64` binary. Possibly some commits are getting artifacts uploaded by the old CI recipe?

**Comment by godofredoc** [comment]
After https://github.com/flutter/engine/pull/41097 files sizes are now identical:

Old artifact:
* gsutil cp gs://flutter_infra_release/flutter/b8f1fa4e7032b15a3a2d744317e7cf9c0431c357/ios-release/artifacts.zip

New artifact:
* gsutil cp gs://flutter_infra_release/flutter/experimental/b8f1fa4e7032b15a3a2d744317e7cf9c0431c357/ios-release/artifacts.zip

Sizes:
*  `9655624 Apr 11 19:25 new/Flutter.xcframework/ios-arm64/Flutter.framework/Flutter`
*  `9655624 Apr 11 19:17 old/Flutter.xcframework/ios-arm64/Flutter.framework/Flutter`
