### ISSUE TITLE
[Impeller] Reconsider usefulness of impeller::GPUTracer.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#124520]
I am not aware of any debugging or profiling workflows where anyone working on Impeller has used the GPUTracer. This could also be perhaps this isn't wired up in all backends. The hooks are also not exposed in the tooling so E2E tests are also not using this.

If we are not using this and if it isn't part of a larger arc of work on profiling, can we back this out?

**Comment by chinmaygarde** [comment]
cc @luckysmg who added it initially and may have context on use that isn't documented. cc @bdero @jonahwilliams @dnfield and perhaps others who typically have involved profiling workflows on the usefulness of this.

**Comment by jonahwilliams** [comment]
I wasn't really aware of this class. Generally speaking I've had good luck just using the Xcode UI, as I'd need to use Xcode to view the trace anyway

**Comment by dnfield** [comment]
I wasn't aware of this but have manually added code that does the same at times - although I also have not found adding such code to be more helpful than just using what Xcode does out of the box.

Is this something that's expressible in vulkan? If it's highly Metal specific then maybe it belongs in some other utility class, but it's really something that would only be useful for local development AFAICT.

**Comment by chinmaygarde** [comment]
> Is this something that's expressible in vulkan?

I believe there are [RenderDoc specific hooks](https://renderdoc.org/docs/in_application_api.html) we can tap into but not everyone uses RenderDoc this way either. Instead using it like we use Xcode.

If this isn't getting enough (any?) use, I vote for removing this support.

**Comment by luckysmg** [comment]
> If this isn't getting enough (any?) use, I vote for removing this support.

+ 1 ^_^
