### ISSUE TITLE
Flutter web on mobile browser when Desktop Site is on

### ISSUE THREAD

**Issue by coba-cobaoke** [flutter/flutter#124569]
I am currently having a project of flutter web and it is running well when I open it in browser of my pc and mobile phone. But I get the problem when opening in mobile browser and turn on the ```Desktop site```... the button inside my project can not be pressed and I can not do anything. That case only happens when ```Desktop site``` is on, when I turn it off, it runs well. Actually I also open this question on https://stackoverflow.com/questions/75926555/opening-flutter-web-on-a-phone-using-dekstop-mode. So far I have been trying to debug the project from mobile browser using ```flutter run -d chrome --web-renderer html``` and ```flutter run -d chrome --web-renderer canvaskit``` and then check the console and everything seems fine. Is there a way to solve this case ?

Here is the capture of the console

<img width="1206" alt="Screenshot 2023-04-11 at 11 34 03" src="https://user-images.githubusercontent.com/77085182/231057192-8782445a-5f15-45d3-a136-15e2144d2c4b.png">

**Comment by exaby73** [comment]
Hello @coba-cobaoke. Is this issue reproducible with the default counter application? Also, can you provide me with the output to `flutter doctor -v`?

**Comment by coba-cobaoke** [comment]
> Hello @coba-cobaoke. Is this issue reproducible with the default counter application? Also, can you provide me with the output to `flutter doctor -v`?

Yes, I have tried using the default counter and it goes well but when I return to my code the button really can not be clicked at all. Here is my flutter doctor -v

```
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.2.1 22D68 darwin-x64, locale en-ID)
    • Flutter version 3.3.10 on channel stable at /Users/umsi06/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (4 months ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/umsi06/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • ANDROID_HOME = /Users/umsi06/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.77.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.2.1 22D68 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 112.0.5615.49

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by exaby73** [comment]
Using an emulator and Chrome, I cannot reproduce this. Is there a specific browser you're using that I can try to reproduce this issue on?

**Comment by coba-cobaoke** [comment]
> Using an emulator and Chrome, I cannot reproduce this. Is there a specific browser you're using that I can try to reproduce this issue on?

I am using Chrome in my mobile phone and I connect my mobile phone to my pc to see the console log. So when I access my project, I open it using localhost:5011 in my phone browser and turn on the ```Desktop site```

**Comment by exaby73** [comment]
Looks like you're running an older version of Flutter. Could you upgrade to the latest stable 3.7.11 and try again?

**Comment by coba-cobaoke** [comment]
> Looks like you're running an older version of Flutter. Could you upgrade to the latest stable 3.7.11 and try again?

Hi I have updated my flutter into the newest version, here is the log... but I still get the same problem.. I can not click anything when ```Desktop site``` is on

[✓] Flutter (Channel stable, 3.7.11, on macOS 13.2.1 22D68 darwin-x64, locale
    en-ID)
    • Flutter version 3.7.11 on channel stable at
      /Users/umsi06/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f72efea43c (3 days ago), 2023-04-11 11:57:21 -0700
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/umsi06/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • ANDROID_HOME = /Users/umsi06/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.2.1 22D68 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 112.0.5615.49
    ! Device 10.11.38.125:5555 is offline.

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by coba-cobaoke** [comment]
> Are you able to reproduce this issue on only physical devices or emulators as well? And if so, if you have access to other physical devices, could you check if you can reproduce on all if them or only certain ones.

Hi actually there is no log of issue that I can send to you, everything seems fine and when I click the button (```Desktop site``` mode is on) there is no error log, it just unable to be clicked

**Comment by exaby73** [comment]
I get there are no logs. What I am trying to understand is why you are able to reproduce this and I am not. Could you provide information about the devices and emulators you tried this issue on and which of them were you able to reproduce the issue on?

And speaking of logs, how are you checking logs? Are you checking it through [Remote Debugging](https://developer.chrome.com/docs/devtools/remote-debugging/)?
