### ISSUE TITLE
devicelab win arm bot is getting "device doctor healthcheck error: [WinError 2]"

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#124521]
The new https://chromium-swarm.appspot.com/bot?id=flutter-win-7 win arm bot is getting the following error:

```device doctor healthcheck error: [WinError 2] The system cannot find the file specifieddevice doctor healthcheck error: [WinError 2] The system cannot find the file specified```

**Comment by keyonghan** [comment]
No `device doctor` is installed in the bot yet. See
```
cd /opt
ls
```
It gives `s` only. The `flutter` folder is expected (which is installed using salt). Please check if salt runs successfully.

**Comment by yusuf-goog** [comment]
win-7 is nw up and running.
