### ISSUE TITLE
Analyzer broken

### ISSUE THREAD

**Issue by BerndWessels** [flutter/flutter#12457]
Not sure if this is a Flutter issue or a Dart/IDE issue, but it seems that simple Dart code can totally confuse the Analyzer.

Did anybody come across something like that and is there a fix?

## Steps to Reproduce

Repo to reproduce and details can be found here 

https://github.com/davidmarne/flutter_built_redux/issues/6

**Comment by Hixie** [comment]
I recommend filing this in the Analyzer's bug database at https://github.com/dart-lang/sdk/issues

**Comment by Hixie** [comment]
cc @pq

**Comment by pq** [comment]
Thanks @Hixie .

Maybe @bwilkerson @scheglov have thoughts.  I can take a look later today...

**Comment by Hixie** [comment]
@pq I've assigned this bug to you for now but please close it once you've determined if it should be filed in the Dart bug database or if it's INVALID/WONTFIX. Thanks!

**Comment by pq** [comment]
A little follow-up on the initial report.  The rub is we're not able to repro.  Closing this and tracking the original in case anyone gets any leads that help reproduce.
