### ISSUE TITLE
Text with ellipsis overflow with HTML web-renderer overlaps itself 3.7.10

### ISSUE THREAD

**Issue by razfazz** [flutter/flutter#124582]
The closed issue [ 3.7.10 3.7.10 on 3.7.9](https://github.com/flutter/flutter/issues/116877) appears again after updating to  (Channel stable, 3.7.10)

**Comment by huycozy** [comment]
It's strange, the text is displaying well from my end. 

![Screenshot 2023-04-12 at 11 31 08](https://user-images.githubusercontent.com/104349824/231350747-bda1539e-d0fc-42e8-8e25-0f2fd55f0e37.png)

Can you confirm there is no specific theme/font on your setup? What is the display language of your Chrome browser?
Please also try below complete sample code to see if it still persists.

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp(home: TestLayout()));
}

class TestLayout extends StatefulWidget {
  const TestLayout({Key? key}) : super(key: key);

  @override
  State<TestLayout> createState() => _TestLayoutState();
}

class _TestLayoutState extends State<TestLayout> {
  @override
  Widget build(BuildContext context) {
    return Material(
      child:  Column(
        mainAxisSize: MainAxisSize.max,
        children: [
          const Expanded(
            child: Center(
              child: Text("test test \n\n XMLHttpRequest error.", textAlign: TextAlign.center,),
            ),
          ),
          Divider(
            thickness: 2.0,
            color: Theme.of(context).colorScheme.secondary.withOpacity(0.2),
          ),

        ],
      ),
    );
  }
}
```
</details>

**Comment by razfazz** [comment]
i must apologize here. i had activated a flutter web preloader which apparently overwrote the body with a certain font, which then led to the strange behavior.
