### ISSUE TITLE
Run then stuck at "Syncing files to device Android SDK built for x86..."

### ISSUE THREAD

**Issue by 188751671** [flutter/flutter#124549]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I installed Android Studio, and it worked fine with the emulator with SDK 11.
But on intellij, after Run, it stuck at "Syncing files to device Android SDK built for x86..."
 Flutter version is latest on Mac X64

### Actual results

Lost connection to device.
adb: device offline

### Logs

<details>

```console

Launching lib/main.dart on Android SDK built for x86 in debug mode...
Upgrading build.gradle
Running Gradle task 'assembleDebug'...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app-debug.apk...
Debug service listening on ws://127.0.0.1:51184/15ubwt3ymUE=/ws
Syncing files to device Android SDK built for x86...
Lost connection to device.
adb: device offline

```

</details>

**Comment by darshankawar** [comment]
@188751671 
Do you get this error `adb: device offline` consistently everytime you try to run ?
Have you checked if the emulator is online and is listed when you run `flutter devices` ?

Also check if [this](https://stackoverflow.com/a/21330228) helps.
