### ISSUE TITLE
[Impeller] DRM/ Partial Repaint for Impeller 

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#124526]
On the Metal and Vulkan backends of Impeller, the process for enabling DRM is fairly straightforward, though there are a few Impeller specific implementation changes and some required benchmarking.

To start with, the damage rect will be fully computed before Impeller has started the frame workload. Flow will inform Impeller of this damage rect indirectly by first applying a clip to the canvas: https://github.com/flutter/engine/blob/main/flow/compositor_context.cc#L153-L169

For Impeller, we should device a better technique of sending the clip rect that lets us actually reduce surface sizes. Additionally, sending the ClipRect and then clearing will force more work from impeller than vice versa.

Now, the expectation is that the texture we acquire from the metal layer will be rendered into with a load instead of a clear so that the older content persists. However, in Impeller we use this texture as the resolve texture for the root multisample render pass. It does not seem like we can use a resolve texture without implicitly clearing it. See WrapCurrentMetalLayerDrawable in surface_mtl.mm.

If so, we may need to use a different texture for the resolve texture and the blit that texture (according to the damage) rect into the actual metal layer's texture. This would be marginally more expensive, so we'd need to benchmark. We could perform this operation conditionally based on whether or not the damage rect was sufficiently large.

FYI @knopp

**Comment by knopp** [comment]
IIRC before partial repaint (and impeller) the actual metal surface was only requested in `submit callback`. In submit callback you should be able to access `SubmitInfo`, which contains both `frame_damage` (part of front buffer that needs to be recomposed) as well as `buffer_damage`, which is part of the frame that will be written to.

The reason why for partial repaint the metal surface is requested in `AcquireFrame` is that we need to know, which of the three different drawables used by `CAMetalLayer` we're gonna get. This affects `existing_damage` which must be taken into account when computing dirty region. The `existing_damage` basically means the area where the current drawable lags behind the front buffer. 

We need to track this per drawable. Metal does this weird thing that it sometimes keeps flipping between only two of the drawables for dozens of frames meaning that third drawable gets quite out of sync.

So at very least for the non-impeller path, while the metal drawable gets requested in acquire frame, it is not actually used until submit (at which point we know the `buffer_damage`).

**Comment by jonahwilliams** [comment]
Making good progress here: https://github.com/flutter/engine/pull/40959, though clip rect seems to be slightly off. I think I'm probably make a small mistake somewhere. Don't know why the frame count claims to be lower, but I added some additional short circuiting that might be tickling that a bit.

Testing on the blinking cursor in flutter gallery

Without Patch (Impeller)

![image](https://user-images.githubusercontent.com/8975114/232631376-ef22a263-472f-4237-8e36-df3bccf55efa.png)

With Patch (Impeller)

![image](https://user-images.githubusercontent.com/8975114/232631295-0d2d586d-1f7e-42ea-9c7f-2cd868f9fa75.png)

Skia

![image](https://user-images.githubusercontent.com/8975114/232631324-c631a7e8-8c32-4ac5-b8a8-ef084e8cc1a7.png)

**Comment by jonahwilliams** [comment]
ahh, the issue is a bug in our blit pass...that can be fixed
