### ISSUE TITLE
didChangeAppLifecycleState - different behaviour iOS vs Android

### ISSUE THREAD

**Issue by adamgic** [flutter/flutter#124591]
Method `didChangeAppLifecycleState` of WidgetsBindingObserver for iOS gets called reliably, for Android missing callbacks for entering App Switcher and App start.

## Steps to Reproduce

1. Execute `flutter run` on the code sample for Android device
2. Wait for app to load on a screen 
3. Swipe from bottom to show App Switcher 
4. Tap App UI to go back to the app

**Expected results:** 
`didChangeAppLifecycleState` function gets called as it is for iOS
(e.g. two calls - one with AppLifecycleState.inactive, one with AppLifecycleState.resumed parameter)

**Actual results:** 
No calls to `didChangeAppLifecycleState` happen.
The same for App start - no calls to `didChangeAppLifecycleState`.

@gspencergoog could you please have a look?

Kind regards,
AG

<details>
<summary>Code sample</summary>

```dart
class _ScreenWidgetState extends State<ScreenWidget> with WidgetsBindingObserver {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    super.dispose();
    WidgetsBinding.instance.removeObserver(this);
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) async {
  	...
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by gspencergoog** [comment]
I'm able to reproduce this issue.

Here's code for a more complete reproduction case:

```dart
import 'dart:math' as math;
import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp(
    title: 'Actions Demo',
    home: Scaffold(
      body: LifecycleTest(),
    ),
  ));
}

class LifecycleTest extends StatefulWidget {
  const LifecycleTest({super.key});

  @override
  State<StatefulWidget> createState() => _LifecycleTestState();
}

class _LifecycleTestState extends State<LifecycleTest> with WidgetsBindingObserver {
  late AppLifecycleState _state;
  List<AppLifecycleState> _stateHistory = <AppLifecycleState>[];

  @override
  void initState() {
    super.initState();
    _state = WidgetsBinding.instance.lifecycleState ?? AppLifecycleState.detached;
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    super.dispose();
    WidgetsBinding.instance.removeObserver(this);
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    _stateHistory.add(_state);
    _stateHistory = _stateHistory.sublist(math.max(0, _stateHistory.length - 10));
    _state = state;
  }

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Center(
        child: Column(children: <Widget>[
          Text('Current State: ${_state.name}'),
          const Text('State History:'),
          for (AppLifecycleState historicalState in _stateHistory)
            Text('  ${historicalState.name}'),
        ],),
      ),
    );
  }
}
```

**Comment by gspencergoog** [comment]
I've determined that Android doesn't send `onPause` events for these things, as one might expect.  Instead, we're going to have to listen to `Activity.onWindowFocusChanged` and see if any of the windows still have focus.  If not, then we should go `inactive`, and if so then we should go to `resumed`.  The hard part about that is going to be walking the windows to see if they're focused, and making sure we don't duplicate state changes if we leave in the state change for onResume (which I suspect we should, just to be safe). Also, since the Android documentation says we can't rely on an order for lifecycle events and focus events, we'll need to listen to both, and deduplicate the events.

**Comment by goderbauer** [comment]
(triage): Looks like the PR is under active discussion.
