### ISSUE TITLE
DecorationImage - lerp and scale

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#12452]
BoxDecoration wants to lerp and scale DecorationImage.

**Comment by Hixie** [comment]
This should now be easy since we could just have it create a _CombinedImageDecoration that creates a _CombinedImageDecorationPainter that paints both images dissolved, the way Porter and Duff intended.

**Comment by alamboley** [comment]
Hi @Hixie any update on the scale applied to the DecorationImage? It seems it is not supported yet, right?

**Comment by Hixie** [comment]
Not yet, but it should be relatively easy to implement if anyone wants to submit a PR.

**Comment by AyushBherwani1998** [comment]
@shihaohong I would like to work on this issue. 

I checked the source code, the [paintImage](https://api.flutter.dev/flutter/painting/paintImage.html) method which is used to paint Image on the canvas, has scale property. If we add the scale property in `DecorationImage` we can use that in `paintImage` method. WDYT?

**Comment by shihaohong** [comment]
I'm not as familiar with the `painting` layer, but if you're able to put together a PR and a sample app in the description describing the desired behavior, I'd be happy to take a look at it!

**Comment by AyushBherwani1998** [comment]
Sure, I'll send a PR. I'm just not sure how can I write a test for scale, cause I'm also not much familiar with `Canvas` and painting. I'll try from my end. Let's see how it goes.

**Comment by AyushBherwani1998** [comment]
@shihaohong I have submitted a PR. Looking forward to the reviews :)

**Comment by hasnentai** [comment]
@shihaohong I would like to work on the lerp issue.

**Comment by hasnentai** [comment]
@Hixie I would like to work on lerp for `DecorationImage`
I have a confusion..!!! Many Classes like `ColorFilter`  `ImageProvider` dose do not have a lerp method implemented.
Shall I implement the Lerp for all the classes or we can have a temporary fix like 
`image: t < 0.5 ? a.image : b.image, // TODO(ianh): cross-fade the image`
