### ISSUE TITLE
Is there any way to implement forgot password and send verification mail  firebase

### ISSUE THREAD

**Issue by vuppalasivakumar** [flutter/flutter#12459]
Hi everyone,
Is there any way to implement forgot password and sending verification mail through firebase in flutter.

**Comment by Hixie** [comment]
cc @collinjackson

**Comment by FastNinja** [comment]
Looking at the implementation - the Firebase SDK already has `sendPasswordResetEmail` 
method.
Wouldn't it be just a matter of _exposing_ this method in Flutter Auth plugin?

P.S. happy to do a PR
P.P.S. just wanted to reinforce that `forget password` functionality is sort of essentials in any serious app experience.

**Comment by dericgw** [comment]
I agree. Unless I am missing something, I do not see a way to update the password either, so one of those two should be available.

**Comment by Arno-Z** [comment]
@dericgw Would you consider sharing the FCF's you used for this here?

Thanks!

**Comment by Arno-Z** [comment]
Thanks Deric

Arno

arno@zwaag.net
+31648780789

On Mar 8, 2018 02:46, "Deric Cain" <notifications@github.com> wrote:

@Arno-Z <https://github.com/arno-z> Sure thing! Here is the code that I
used (tested and working as of today):

const functions = require('firebase-functions');const admin =
require('firebase-admin');
// Credentials neededconst serviceAccount = require('./service-account.json');
admin.initializeApp({
  credential: admin.credential.cert(serviceAccount)
});
exports.updateUserPassword = functions.https.onRequest((request, response) => {
  const { uid, email, password } = request.body;
    admin.auth().updateUser(uid, {
      email,
      password
    }).then((updateResponse) => {
      return response.send({
        error: false,
        message: 'The user has been updated.',
        result: updateResponse,
      });
    }).catch((error) => {
      return response.send({
        error: true,
        message: error,
        result: null,
      });
    });
})

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/flutter/flutter/issues/12459#issuecomment-371349399>,
or mute the thread

**Comment by FastNinja** [comment]
Hi all,

the Flutter Plugin was updated - so you can send reset password link just cal:
```sendPasswordResetEmail``` from `FirebaseAuth`.

The issue can be closed as done.

**Comment by brusinovic** [comment]
I wouldn't call it done yet? SendPasswordResetEmail is implemented but **sending account verification** email message is still missing.

**Comment by tuancaraballo** [comment]
Any updates on this? Flutter hasn't worked for me. Happy to open a pr for this.

**Comment by zoechi** [comment]
@tuancaraballo doesn't seem to be a PR waiting yet, os a PR from you would be welcome.

**Comment by sdresche17** [comment]
Could someone elaborate on the password reset method? I imported the most recent firebase_auth.dart, yet when I go to call FirebaseAuth.sendPasswordResetEmail it says the method doesn't exist.

**Comment by Arno-Z** [comment]
I have this working with firebase_auth version 0.5.15:

_sendLostPassWordLink() {
  final form = formKey.currentState;
  if (form.validate()) {
    _auth.sendPasswordResetEmail(email: passwordController.text).then((result){
      Scaffold.of(context).showSnackBar(
        const SnackBar(content: const Text('Requesting password reset email')),
      );
    }).catchError((error){
      Scaffold.of(context).showSnackBar(
        // ignore: use_of_void_result
        const SnackBar(content: const Text('Password reset failed, did
you enter the correct address?')),
      );
    });
  }}

**Comment by 5ummit** [comment]
Can someone add an explanation to docs please?

**Comment by BarbaricGamester** [comment]
Hey, I was struggling with this since yesterday, fortunately I checked out the given methods by the FirebaseUser class instead of the FirebaseAuth class, I found a method for sending verification email.

`fireBaseUser.sendEmailVerification();`

**Comment by AmitJoki** [comment]
Are there plans to implement this: https://firebase.google.com/docs/auth/admin/email-action-links?  As of now, we only have a generic default method and it provides no room for customization.

It would be nice to port the following which is part of Android SDK

```
String link = FirebaseAuth.getInstance().generateEmailVerificationLink(
      email, actionCodeSettings);
```
to Flutter.

**Comment by willvlad** [comment]
Any update on this? Flutter still doesn't seem to expose a way to access actionCodeSettings?

**Comment by kroikie** [comment]
@vuppalasivakumar

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/957. Any further collaboration will be done there.
