### ISSUE TITLE
double.fromEnvironment does not exist

### ISSUE THREAD

**Issue by Mastersam07** [flutter/flutter#124665]
The current dart-define docs read:

```
Additional key-value pairs that will be available as constants from the String.fromEnvironment, bool.fromEnvironment, int.fromEnvironment, and
double.fromEnvironment constructors.
```
while dart-define-from-file reads:

```
The path of a json format file where flutter define a global constant pool. 
Json entry will be available as constants from the String.fromEnvironment, bool.fromEnvironment, int.fromEnvironment, 
and double.fromEnvironment constructors; the key and field are json values
```

<img width="1440" alt="Screenshot 2023-04-03 at 19 31 34" src="https://user-images.githubusercontent.com/31275429/229720102-2020e1a9-c1fb-470b-89e6-ffb84096a51b.png">

However, there is no fromEnvironment constructor for double.

**Comment by exaby73** [comment]
I can see this in the following lines. Labeling the issue

https://github.com/flutter/flutter/blob/e21c149b99a6f6612e801c1e416e6407718feedb/packages/flutter_tools/lib/src/runner/flutter_command.dart#L612-L636
