### ISSUE TITLE
emoji display exception on ios 16.2

### ISSUE THREAD

**Issue by David-C-gd-y** [flutter/flutter#124683]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

physical equipment： iPhone Xr

Use the <TextField> widget to input emoji. Only the keycap series starts with #️⃣ *️⃣ 0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣. Any keycap will cause garbled characters for subsequent input characters, similar to ꪈ

However, on ios 15.x devices, there is no such problem....

### Expected results

Display emoji correctly

### Actual results

not  keycap series beginning，it shows good， otherwise, it will display garbled characters

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, [3.7.10](https://web.mchat.com/3.7.10), on macOS [13.0](https://web.mchat.com/13.0) 22A8380 darwin-arm64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version [33.0.2](https://web.mchat.com/33.0.2))
[✓] Xcode - develop for iOS and macOS (Xcode [14.3](https://web.mchat.com/14.3))
[✓] Chrome - develop for the web
[✓] Android Studio (version [2022.1](https://web.mchat.com/2022.1))
[✓] VS Code (version [1.77.2](https://web.mchat.com/1.77.2))
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!`

```

</details>

**Comment by huycozy** [comment]
Thanks for the report! This is a known issue being tracked at https://github.com/flutter/flutter/issues/36062 (please take a look at the [demo](https://github.com/flutter/flutter/issues/36062#issuecomment-1344265853)). Related PR on skia that seems can fix the issue: https://github.com/google/skia/pull/129.

Closing this issue in favor of linked issue, so please follow up on it for further updates.
