### ISSUE TITLE
webview_flutter 4.0.7  on iOS loadHtmlString api cannot parse "<p><img src=\"https://img1.baidu.com/it/…..but 

### ISSUE THREAD

**Issue by YelenaLemon** [flutter/flutter#124667]
WebViewController controller = WebViewController();
String html = "<p><img src=\"https://img1.baidu.com/it/u=1228645897,2925386248&fm=253&fmt=auto&app=120&f=JPEG?w=1280&h=800\" style=\"max-width:100%;\"/></p>"

Void load(){
  controller.loadHtmlString(html);
}

Network images cannot be parsed
on iOS  cannot parse, but webview_flutter_web on web and  Android Can be used

**Comment by YelenaLemon** [comment]
String html = "<p><img src=\"https://img1.baidu.com/it/u=1228645897,2925386248&fm=253&fmt=auto&app=120&f=JPEG?w=1280&h=800\" style=\"max-width:100%;\"/></p>"

**Comment by huycozy** [comment]
Hi @YelenaLemon 
Could you share your complete sample code so that we may verify this? I check your html string and see it can display normally on iOS

<details>
<summary>Demo</summary>

<img width="400" src="https://user-images.githubusercontent.com/104349824/231452948-f224613f-5a77-432f-b65b-dc9a6284e455.png">

</details>

**Comment by YelenaLemon** [comment]
> Hi @YelenaLemon Could you share your complete sample code so that we may verify this? I check your html string and see it can display normally on iOS
> 
> Demo
> <img alt="" width="400" src="https://user-images.githubusercontent.com/104349824/231452948-f224613f-5a77-432f-b65b-dc9a6284e455.png">
I didn't expect your reply and verification to be so quick. Thank you very much!
Today, I brought my iPhone to work and tried again. Indeed, the network image was also loaded. So I tried the emulator again and it worked. But I didn't change anything, maybe because of the cache. I will consult you for other questions in the future. Thank you very much.

**Comment by huycozy** [comment]
Thanks for your response. Closing as the issue doesn't happen anymore.
