### ISSUE TITLE
Dialog should regularly assert that its context did not go away

### ISSUE THREAD

**Issue by JFixby** [flutter/flutter#12465]
call
```
var alert = new AlertDialog(
          title: new Text("text"),
          content: new Text("text"),
        );

        showDialog<bool>(context: item.context, child: alert);
```

```
[ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:

                                                         NoSuchMethodError: The getter '_debugLifecycleState' was called on null.
                                                         Receiver: null
                                                         Tried calling: _debugLifecycleState
                                                         #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:44)
                                                         #1      StatefulElement.inheritFromWidgetOfExactType.<anonymous closure> (package:flutter/src/widgets/framework.dart:3721)
                                                         #2      StatefulElement.inheritFromWidgetOfExactType (package:flutter/src/widgets/framework.dart:3755)
                                                         #3      Theme.of (package:flutter/src/material/theme.dart:126)
                                                         #4      showDialog (package:flutter/src/material/dialog.dart:466)
```

**Comment by JFixby** [comment]
https://github.com/flutter/flutter/issues/10811

**Comment by JFixby** [comment]
Example is also has this issue:
https://docs.flutter.io/flutter/material/AlertDialog-class.html

**Comment by JFixby** [comment]
```
$ flutter doctor
[✓] Flutter (on Linux, locale en_US.UTF-8, channel master)
    • Flutter at /home/reyer/reyer/flutter/master
    • Framework revision 0a85db2958 (4 days ago), 2017-10-06 07:13:27 +0300
    • Engine revision 459f722b86
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /home/reyer/Android/Sdk
    • Platform android-26, build-tools 26.0.2
    • ANDROID_HOME = /home/reyer/Android/Sdk
    • Java binary at: /home/reyer/.local/share/umake/android/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /home/reyer/.local/share/umake/android/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 17.0
    • Dart plugin version 172.4155.35

[✓] Connected devices
    • Moto C Plus                  • ZW222422WM    • android-arm • Android 7.0 (API 24)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 6.0 (API 23) (emulator)
```

**Comment by JFixby** [comment]
Basically the bug is the following.
1) You create UI and use `context`;
2) UI creates dialog using the `context`. The dialog will be shown at some event.
3) Event happens and the dialog is shown and it is ok.
- BUT when the UI was destroyed between steps 2 and 3 (someone called `setState()`)
the dialog builder is not aware of the context change and this leads to the crash/

**Comment by Hixie** [comment]
Yeah, you can't remove the context from which you spawned the dialog. Otherwise we don't know e.g. what localizations to use for the dialog (IIRC).

**Comment by Hixie** [comment]
The framework should report this in a much better way.

**Comment by JFixby** [comment]
I don't understand the concept of context and why it is neccessay to pass it to each component constructor.
I thought it was some king of a crutch an Android UI. But now it is again here in the Flutter.

**Comment by Hixie** [comment]
Not sure what a context is in Android. In Flutter a BuildContext is just the widget that is responsible for giving you inherited widgets, like Localizations, Directionality, DefaultTextStyle, Theme, etc. Without a context, the dialog wouldn't know what language to use, whether to be in left-to-right mode or right-to-left mode, what font to use for text, what colour to use for buttons, etc. Since all those things can animate, or at least change dynamically, the context has to last as long as the dialog.

However, you can pass in whatever context you want. For example, you could pass in the context of the root widget of your route, rather than passing in the context of some inner-most widget that you're planning on taking away.

See also https://master-docs-flutter-io.firebaseapp.com/flutter/widgets/BuildContext-class.html

I'll try to include all this information in the documentation when I update it as part of making the error message here clearer.

**Comment by Hixie** [comment]
The documentation claims (now) that it's ok for this context to go away after the call to showDialog.
Can you see if you're still running into this? If so, we should figure out where the context is being squirreled away and prevent that from happening.
