### ISSUE TITLE
What changed with SliderTrackShape

### ISSUE THREAD

**Issue by NameWang** [flutter/flutter#124646]
I need to customize the slider .

My code:
```
class CustomTrackShape extends RoundedRectSliderTrackShape {
  const CustomTrackShape();

  @override
  Rect getPreferredRect({
    required RenderBox parentBox,
    Offset offset = Offset.zero,
    required SliderThemeData sliderTheme,
    bool isEnabled = false,
    bool isDiscrete = false,
  }) {
    final double trackHeight = sliderTheme.trackHeight!;
    final double trackWidth = parentBox.size.width;
    final double trackLeft = offset.dx;
    final double trackTop =
        offset.dy + (parentBox.size.height - trackHeight) / 2;
    return Rect.fromLTWH(trackLeft, trackTop, trackWidth, trackHeight);
  }

  @override
  void paint(
    PaintingContext context,
    Offset offset, {
    required RenderBox parentBox,
    required SliderThemeData sliderTheme,
    required Animation<double> enableAnimation,
    required TextDirection textDirection,
    required Offset thumbCenter,
    bool isDiscrete = false,
    bool isEnabled = false,
    double additionalActiveTrackHeight = 0,
  }) {
    super.paint(
      context,
      offset,
      parentBox: parentBox,
      sliderTheme: sliderTheme,
      enableAnimation: enableAnimation,
      textDirection: textDirection,
      thumbCenter: thumbCenter,
      //
      additionalActiveTrackHeight: 0,
    );
  }
}
```

It works a few months ago , after I upgrade to the latest version , there is the fault:

`CustomTrackShape.paint' ('void Function(PaintingContext, Offset, {double additionalActiveTrackHeight, required Animation<double> enableAnimation, bool isDiscrete, bool isEnabled, required RenderBox parentBox, required SliderThemeData sliderTheme, required TextDirection textDirection, required Offset thumbCenter})') isn't a valid override of 'RoundedRectSliderTrackShape.paint' ('void Function(PaintingContext, Offset, {double additionalActiveTrackHeight, required Animation<double> enableAnimation, bool isDiscrete, bool isEnabled, required RenderBox parentBox, Offset? secondaryOffset, required SliderThemeData sliderTheme, required TextDirection textDirection, required Offset thumbCenter})'). (Documentation) The member being overridden (slider_theme.dart:188). `

How to fix it

**Comment by darshankawar** [comment]
@NameWang 
Can you provide `flutter doctor -v` and a complete reproducible code sample along with the error log you get ?


> It works a few months ago ,

Which version you were on before upgrading ?

**Comment by NameWang** [comment]
`import 'dart:ui' as ui;

import 'package:flutter/material.dart';

class ChannelSlider extends StatelessWidget {
  final double value;
  final double min;final double max;
  final List<Color> colors;

  final ValueChanged<double>? onChangeEnd;

  final ValueChanged<double> onChanged;


  const ChannelSlider({
    required this.value,
    required this.colors,required this.max,required this.min,
    required this.onChangeEnd,
    required this.onChanged,
    Key? key,
  }) : super(key: key);


  @override
  Widget build(BuildContext context) {
    return  Theme(
                  data: _sliderTheme( colors),
                  child: Slider(
                    value: value,
                    min: min,
                    max: max,
                    onChangeEnd: onChangeEnd,
                    onChanged: onChanged,
                  ),
                ) ;
  }
}

class ChannelSliderTrack extends SliderTrackShape with BaseSliderTrackShape  {
 // final Color selectedColor;
  final List<Color> colors;

  const ChannelSliderTrack( this.colors);

  @override
  void paint(
      PaintingContext context,
      Offset offset, {
        required RenderBox parentBox,
        required SliderThemeData sliderTheme,
        required Animation<double> enableAnimation,
        required TextDirection textDirection,
        required Offset thumbCenter,
        bool isDiscrete = false,
        bool isEnabled = false,
        double additionalActiveTrackHeight = 0,
      }) {
    assert(sliderTheme.disabledActiveTrackColor != null);
    assert(sliderTheme.disabledInactiveTrackColor != null);
    assert(sliderTheme.activeTrackColor != null);
    assert(sliderTheme.inactiveTrackColor != null);
    assert(sliderTheme.thumbShape != null);

    final trackRect = getPreferredRect(
      parentBox: parentBox,
      offset: offset,
      sliderTheme: sliderTheme,
      isEnabled: isEnabled,
      isDiscrete: isDiscrete,
    );
    final trackRadius = Radius.circular(trackRect.height / 2);
    final activeTrackRadius = Radius.circular(trackRect.height / 2 );

    final activePaint = Paint()..color = Colors.transparent;

    final inactivePaint = Paint()
      ..shader = ui.Gradient.linear(
        Offset.zero,
        Offset(trackRect.width, 0),
        colors,
        _impliedStops(),
      );

    Paint leftTrackPaint;
    Paint rightTrackPaint;
    switch (textDirection) {
      case TextDirection.ltr:
        leftTrackPaint = activePaint;
        rightTrackPaint = inactivePaint;
        break;
      case TextDirection.rtl:
        leftTrackPaint = inactivePaint;
        rightTrackPaint = activePaint;
        break;
    }

    //const thumbRadius = 14;

    final shapeRect = RRect.fromLTRBAndCorners(
      trackRect.left ,
      (textDirection == TextDirection.ltr)
          ? trackRect.top - (additionalActiveTrackHeight / 2)
          : trackRect.top,
      trackRect.right ,
      (textDirection == TextDirection.ltr)
          ? trackRect.bottom + (additionalActiveTrackHeight / 2)
          : trackRect.bottom,
      topLeft: (textDirection == TextDirection.ltr)
          ? activeTrackRadius
          : trackRadius,
      bottomLeft: (textDirection == TextDirection.ltr)
          ? activeTrackRadius
          : trackRadius,
      topRight: (textDirection == TextDirection.ltr)
          ? activeTrackRadius
          : trackRadius,
      bottomRight: (textDirection == TextDirection.ltr)
          ? activeTrackRadius
          : trackRadius,
    );

    context.canvas.drawRRect(shapeRect, leftTrackPaint);
    context.canvas.drawRRect(shapeRect, rightTrackPaint);
  }

  List<double> _impliedStops() {
    assert(colors.length >= 2, 'colors list must have at least two colors');
    final separation = 1.0 / (colors.length - 1);
    return List<double>.generate(
      colors.length,
          (int index) => index * separation,
      growable: false,
    );
  }
}

ThemeData _sliderTheme(List<Color> colors) =>
    ThemeData.light().copyWith(
      sliderTheme: SliderThemeData(
        trackHeight: 16,
        thumbColor: Colors.white,
        trackShape: ChannelSliderTrack( colors),
      ),
    );`

**Comment by darshankawar** [comment]
Check the documentation on `paint` method of that class to see if it helps: https://api.flutter.dev/flutter/material/SliderTrackShape/paint.html

**Comment by NameWang** [comment]
I saw it.
This is new:Offset? secondaryOffset.
It works now,Thanks

**Comment by darshankawar** [comment]
Good to know. Closing as solved.
