### ISSUE TITLE
Windows Firewall production issue

### ISSUE THREAD

**Issue by DanielBerrioB** [flutter/flutter#124622]
## Steps to Reproduce

Hi!
I'm new in Desktop development and I'm trying to figure it out how to allow Firewall rules in my Flutter Windows app. I'm facing this right now:

![image](https://user-images.githubusercontent.com/34080611/231289043-3703ee2f-4bb6-47ed-9abe-79336e4d5cc0.png)

I think this problem is because I'm using multicast_dns (https://pub.dev/packages/multicast_dns), but I'm not pretty sure how to allow this capability in my project. I know that there's a file called `runner.exe.manifest`, but I've been stumbling over it.

If anyone can help me it'd be great!

Thanks!

**Actual results:** 

Not be able to run the project without those firewall rules.

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by stuartmorgan** [comment]
> I'm trying to figure it out how to allow Firewall rules in my Flutter Windows app

Individual apps don't control firewall rules; if they could, it would defeat the purpose of having a system-level security feature.

Closing as this is out of scope for Flutter.
