### ISSUE TITLE
debuggingEnabled ? how to set debuggingEnabled in new version?

### ISSUE THREAD

**Issue by RobotJohns** [flutter/flutter#124649]
old version 👍 
 WebView(
        javascriptMode: JavascriptMode.unrestricted,
        backgroundColor: const Color(0x00000000),
        debuggingEnabled: !kReleaseMode,
        initialUrl: _gameUrl,
        onWebViewCreated: (WebViewController webViewController) {
          _loadFinished = false;
          _webViewController = webViewController;
        },

new version  how to set?

**Comment by darshankawar** [comment]
@RobotJohns 
Look for the same in this section of the plugin readMe: https://pub.dev/packages/webview_flutter#api-changes

```
The following features have been moved to an Android implementation class. See section Platform-Specific Features for details on accessing Android platform-specific features.
WebView.debuggingEnabled -> static AndroidWebViewController.enableDebugging
```

See if above helps to answer your question.
