### ISSUE TITLE
Web tests may be too sharded

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#124682]
Here is an example where there is 6.5+ minutes of overhead to run 40s of tests:

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Production%20Engine%20Drone/108269/overview

This may be an artifact of the long source checkout time when there is a cold cache, but even in the case of a warm cache the checkout time appears to be around 30s, so including the other steps, there will still be more overhead than time running tests.

cc @keyonghan @godofredoc @eyebrowsoffire @yjbanov

**Comment by zanderso** [comment]
@yjbanov saw this in my open tabs and decided to give it a ping since we were talking about it last-week-ish.

**Comment by eyebrowsoffire** [comment]
I'm addressing this in https://github.com/flutter/engine/pull/56206

**Comment by zanderso** [comment]
Hey Jackson, that PR was pretty big =) Would you mind explaining here for posterity what was done to address this issue?

**Comment by eyebrowsoffire** [comment]
Instead of having a shard per web test suite, it's now one shard per browser-platform combo that we test on, so just four shards (Mac-Safari, Linux-Chrome, Linux-Firefox, Windows-Chrome). This is compared to like 60-ish shards we had before.
