### ISSUE TITLE
Compute/ComputeSubgroupTest.* from impeller_unittests cannot run on Iris 5100 mac minis

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#124678]
In step 18 from https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Engine%20Drone/158661/overview
```
[----------] 5 tests from Compute/ComputeSubgroupTest
[ RUN      ] Compute/ComputeSubgroupTest.QuadsToPolyline/Metal
../../flutter/impeller/renderer/compute_subgroup_unittests.cc:723: Failure
Value of: context->GetCapabilities()->SupportsComputeSubgroups()
  Actual: false
Expected: true
[  FAILED  ] Compute/ComputeSubgroupTest.QuadsToPolyline/Metal, where GetParam() = 4-byte object <00-00 00-00> (161 ms)
[ RUN      ] Compute/ComputeSubgroupTest.HeartCubicsToStrokeVertices/Metal
../../flutter/impeller/renderer/compute_subgroup_unittests.cc:502: Failure
Value of: context->GetCapabilities()->SupportsComputeSubgroups()
  Actual: false
Expected: true
[  FAILED  ] Compute/ComputeSubgroupTest.HeartCubicsToStrokeVertices/Metal, where GetParam() = 4-byte object <00-00 00-00> (8 ms)
[ RUN      ] Compute/ComputeSubgroupTest.QuadAndCubicInOnePath/Metal
../../flutter/impeller/renderer/compute_subgroup_unittests.cc:385: Failure
Value of: context->GetCapabilities()->SupportsComputeSubgroups()
  Actual: false
Expected: true
[  FAILED  ] Compute/ComputeSubgroupTest.QuadAndCubicInOnePath/Metal, where GetParam() = 4-byte object <00-00 00-00> (10 ms)
[ RUN      ] Compute/ComputeSubgroupTest.LargePath/Metal
../../flutter/impeller/renderer/compute_subgroup_unittests.cc:174: Failure
Value of: context->GetCapabilities()->SupportsComputeSubgroups()
  Actual: false
Expected: true
[  FAILED  ] Compute/ComputeSubgroupTest.LargePath/Metal, where GetParam() = 4-byte object <00-00 00-00> (7 ms)
[ RUN      ] Compute/ComputeSubgroupTest.PathPlayground/Metal
../../flutter/impeller/renderer/compute_subgroup_unittests.cc:49: Failure
Value of: context->GetCapabilities()->SupportsComputeSubgroups()
  Actual: false
Expected: true
[  FAILED  ] Compute/ComputeSubgroupTest.PathPlayground/Metal, where GetParam() = 4-byte object <00-00 00-00> (10 ms)
[----------] 5 tests from Compute/ComputeSubgroupTest (198 ms total)
```

cc @dnfield

**Comment by dnfield** [comment]
I saw this and meant to file a bug. Will look into it today.

**Comment by dnfield** [comment]
The Iris 5100 GPU models don't support subgroups. Need to update the tests to detect and skip those.

**Comment by dnfield** [comment]
Scratch that, there are only a few of them and only in the try pool, they should not be allowed to run these tests -  otherwise try jobs will pass and post submit will fail if a regression occurs.

**Comment by dnfield** [comment]
https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=os&c=status&d=asc&f=pool%3Aluci.flutter.try&f=gpu%3A8086%3A0a2e&k=gpu&s=id is a list of those bots

**Comment by zanderso** [comment]
cc @keyonghan is it possible to exclude the list of bots @dnfield linked from running in all engine pools?

**Comment by ricardoamador** [comment]
One possible solution here after taking a quick look would be to choose machine_type n1-standard-8. Now I have not gotten to look at all the other mac bot but after sampling a few other bots they all were n1-standard-8 machine_types. The mac bots listed here are all n1-standard-4 machine_type. I am almost certain you cannot exclude a value so we would need to pick something common to the others and not these which so far is that machine type.

**Comment by keyonghan** [comment]
> cc @keyonghan is it possible to exclude the list of bots @dnfield linked from running in all engine pools?

I would expect https://github.com/flutter/engine/pull/41159 to use only mac8,1 for these targets.
