### ISSUE TITLE
[flutter_adaptive_scaffold] : Example app is not running in Android

### ISSUE THREAD

**Issue by Harishwarrior** [flutter/flutter#124600]
The example app present in the flutter_adaptive_scaffold is throwing an error when running in Android and works well in other platform.

```
Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
package identifier or launch activity not found.
Please check C:\Users\warri\StudioProjects\packages\packages\flutter_adaptive_scaffold\example\android\app\src\main\AndroidManifest.xml for errors.
No application found for TargetPlatform.android_x64.
Is your project missing an android\app\src\main\AndroidManifest.xml?
Consider running "flutter create ." to create one.
```

**Comment by huycozy** [comment]
Thanks for filling the issue and PR, @Harishwarrior 
Even though the example can run normally on my devices without the fixes (adding package name), the fix seems to make sense as I've seen a couple of similar issues on SO as well (and I had the same issue before but don't remember exactly what it is, and the fix is adding package name too as in your PR).

**Comment by Harishwarrior** [comment]
> Thanks for filling the issue and PR, @Harishwarrior 
> Even though the example can run normally on my devices without the fixes (adding package name), the fix seems to make sense as I've seen a couple of similar issues on SO as well (and I had the same issue before but don't remember exactly what it is, and the fix is adding package name too as in your PR). 

The default flutter app has this package name in Android manifest only. But, someone applied a suggestion by Android studio accidentally which moved to it to app build gradle. I guess it depends on the Android version also.

**Comment by reidbaker** [comment]
I dont think we should need to add package name back into the manifest. I looked at the code an namespace appears to be [set correctly.](https://github.com/flutter/packages/blob/main/packages/flutter_adaptive_scaffold/example/android/app/build.gradle) 
Also Flutter does not support x86 release builds https://docs.flutter.dev/deployment/android#what-are-the-supported-target-architectures 

To build I am using `flutter build apk --target-platform=android-x86 --debug` which works. I am currently downloading the dependencies to run an x86 emulator to test launching for myself.

**Comment by Harishwarrior** [comment]
> I dont think we should need to add package name back into the manifest. I looked at the code an namespace appears to be [set correctly.](https://github.com/flutter/packages/blob/main/packages/flutter_adaptive_scaffold/example/android/app/build.gradle) Also Flutter does not support x86 release builds https://docs.flutter.dev/deployment/android#what-are-the-supported-target-architectures
> 
> To build I am using `flutter build apk --target-platform=android-x86 --debug` which works. I am currently downloading the dependencies to run an x86 emulator to test launching for myself.

FYI:
I am using this emulator where the issue first occurred:
![image](https://user-images.githubusercontent.com/38380040/231551538-729cfddf-7c19-421c-9aba-ac46ccc6fd25.png)

**Comment by reidbaker** [comment]
This stackoverflow post https://stackoverflow.com/questions/54636718/no-application-found-for-targetplatform-android-x86/72190449#72190449 indicates that potentially this is fixed by either a flutter clean or a fresh build. 

Closing as not reproducible for now but thanks for filing and attempting to fix an issue in flutter. We appreciate the effort.

**Comment by Harishwarrior** [comment]
> This stackoverflow post https://stackoverflow.com/questions/54636718/no-application-found-for-targetplatform-android-x86/72190449#72190449 indicates that potentially this is fixed by either a flutter clean or a fresh build. 
> 
> Closing as not reproducible for now but thanks for filing and attempting to fix an issue in flutter. We appreciate the effort.  

Okay. My suggestion is to improve the error message above. Something like "Try Flutter clean".
