### ISSUE TITLE
iOS crash NSInvalidArgumentException-[SemanticsObject accessibilityFrame]

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#12469]
## Steps to Reproduce

This crash showed up in Sentry logs for Hamilton; we don't have a repro case yet but I wanted to file an issue in case anyone has an idea for what might be wrong or runs into it. I have been able to use the app on iOS with Voiceover successfully, it didn't crash. Seems to happen on various iOS devices and versions, it's not a super common crasher though (12 users so far).

```
NSInvalidArgumentException
Application threw exception NSInvalidArgumentException: -[__NSCFNumber window]: unrecognized selector sent to instance 0xbadd59bd747dbead

Flutter 0x1005a917c -[SemanticsObject accessibilityFrame]
Called from: UIKit-[NSObject(UIAccessibility) accessibilityActivationPoint]
Runner 0x1000359b8 mainRunner/main.m:7
Called from: libdyld start
```

Seems to be a crash here in [`AccessibilityBridge`](https://github.com/flutter/engine/blob/dd68239b436da462da6fcbc59b94d5b34b305986/shell/platform/darwin/ios/framework/Source/accessibility_bridge.mm#L200):

```
  CGFloat scale = [[_bridge->view() window] screen].scale;
```

I believe that the view is set in [`FlutterViewController`](https://github.com/flutter/engine/blob/faabc10178ce9b241f532c4f45d50b2dc4de2cae/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm#L678):

```
  _platformView->ToggleAccessibility(self.view, enabled);
```

Why would the `_bridge()->view()` be an `__NSCFNumber`?

**Comment by Hixie** [comment]
@collinjackson @xster Is this still happening in more recent builds?

**Comment by xster** [comment]
Issue is no longer in their Sentry. Closing.
