### ISSUE TITLE
Make NavigationBar more prominent on the BottomNavigationBar API docs

### ISSUE THREAD

**Issue by leighajarett** [flutter/flutter#124687]
When testing out some cross-platform design adaptations, I realized I had been using `BottomNavigationBar` instead of the updated `NavigationBar`. `BottomNavigationBar` is featured in a few tutorials and (for me) comes up first when I google "navigation bars flutter" -- so it might be useful to point developers to the new widget to avoid them using out of date material components.

**Comment by M-Madhavreddy** [comment]
Hi ,I came across your project and noticed that you are using the deprecated BottomNavigationBar widget. I would like to contribute to your project by updating it to use the updated NavigationBar widget. Is that something you would be interested in?
