### ISSUE TITLE
Issue from website page FAQ

### ISSUE THREAD

**Issue by nitinthewiz** [flutter/flutter#12474]
From URL: https://flutter.io/faq.md

FAQ hides behind top bar.

When I click on one of the question links in the FAQ, the question hides behind the top bar. This is bad UX and easily fixed by 

1. calculating the height of the bar and moving the anchor down by those many pixels. 
2. Or, you know, not using Fluid containers.
3. Or setting .site-header position to anything other than fixed.

Cheers!

**Comment by sethladd** [comment]
Thanks for the feedback. Patch welcome! (and yes, this is a problem, hope we can get a fix soon)

**Comment by Hixie** [comment]
I fixed this today!
