### ISSUE TITLE
3.7.11 release failed to push packaging artifacts

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#124708]
3.7.11 tag was pushed, but the artifacts are not showing on https://docs.flutter.dev/release/archive?tab=macos for any platform.

**Comment by CaseyHillers** [comment]
Issue was the tool proxy command did not indicate the packaging builds were scheduled. We'll send workflow updates to paste the packaging console at the end.

Larger issue uncovered here is the engine tag was incorrect.

**Comment by godofredoc** [comment]
Should we open a new bug to track the incorrect engine tag. The issue in this bug is working as intended proxy tool just tags and pushes and luci scheduler is the one triggering the packaging builds as post-submit to stable | beta branches.

**Comment by CaseyHillers** [comment]
Marking this as closed. We resolved the incorrect engine tag in https://flutter-review.googlesource.com/c/recipes/+/41665
