### ISSUE TITLE
flutter web : Gaussian blur does not support browser like safari / firefox 

### ISSUE THREAD

**Issue by zjrwdl** [flutter/flutter#124764]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Use this code to be sure:
<img width="495" alt="image" src="https://user-images.githubusercontent.com/6874049/231644968-09dc54bc-032c-461a-9d0e-ddcb4cfb20be.png">

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/6874049/231638750-59190e36-9a81-43ad-bf05-5e4a21d9580c.png">

### Expected results

I want to make a gassia blur effect

### Actual results

the result does what i expect in  browser like Chrome and Edge, but not  in safari  or firefox.
I tried two versions of flutter, which are 3.3.8 and 3.7.10，the result is the same.

### Code sample
<img width="495" alt="image" src="https://user-images.githubusercontent.com/6874049/231645009-63d93cf9-ecd1-4619-b51b-a11e44eab804.png">

### Screenshots or Video

in chrome :
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/6874049/231641154-ef729c33-4655-4673-b370-509d14e88006.png">

in safari:
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/6874049/231641177-95613101-f2c5-4253-bb9d-13ef6110cf03.png">

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.10, on macOS 11.6 20G165 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

**Comment by huycozy** [comment]
I checked this on Safari and Chrome but the results look similar on both browsers.

| Chrome | Safari |
| --------------- | --------------- |
<img width="400" src="https://user-images.githubusercontent.com/104349824/231689296-2128bf3e-77b7-49e1-8179-66ecc79acd92.png"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/231689315-8c7dcc3c-d764-43a1-94a7-c7552c1ddbce.png">

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.7.11, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.7.11 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f72efea43c (31 hours ago), 2023-04-11 11:57:21 -0700
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 112.0.5615.49

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.10.0-4.0.pre.25, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.10.0-4.0.pre.25 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b95b86f820 (3 hours ago), 2023-04-12 23:39:38 +0000
    • Engine revision 372946ec7e
    • Dart version 3.0.0 (build 3.0.0-431.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 112.0.5615.49

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

Can you share a complete and minimal sample code for this? And please retry on the latest stable and master channels as well. Thanks!

**Comment by zjrwdl** [comment]
> I checked this on Safari and Chrome but the results look similar on both browsers.
> 
> Chrome	Safari
> <img alt="" width="400" src="https://user-images.githubusercontent.com/104349824/231689296-2128bf3e-77b7-49e1-8179-66ecc79acd92.png">	<img alt="" width="400" src="https://user-images.githubusercontent.com/104349824/231689315-8c7dcc3c-d764-43a1-94a7-c7552c1ddbce.png">
> flutter doctor -v (stable and master)
> Can you share a complete and minimal sample code for this? And please retry on the latest stable and master channels as well. Thanks!

demo code : https://github.com/zjrwdl/gaussian_issue_in_safari/blob/main/main.dart
The demo app runs normally, but when I put the code in the demo into my project and run it, I will encounter the problem that the Gaussian blur does not take effect in safari browser. 
I tried to change the code in the red wireframe to , 
<img width="948" alt="image" src="https://user-images.githubusercontent.com/6874049/232687442-02385feb-bb72-46cf-aef7-9d1d37e20f7f.png">
height: MediaQuery.of(context).size.height - 1,
and the Gaussian blur effect of this code also took effect in my project in safari browser.
It's weird, but it works.

**Comment by zjrwdl** [comment]
I know the reason. If you configure the parameter --web-renderer html at startup, you can reproduce this problem:
Chrome supports Gaussian blur in html mode, but firefox and safari do not support it

**Comment by huycozy** [comment]
Thanks for your response. As far as I can see, this issue seems to happen on Firefox only whilst it renders the same on Chrome and Safari.

| Chrome | Safari | Firefox |
| --------------- | --------------- | --------------- |
<img width="400" src="https://user-images.githubusercontent.com/104349824/232971797-7dc3cd82-8168-4ff4-bf79-d0f8039c5905.png"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/232971794-7dcee6ce-0ba4-4c0a-bbe7-591e0f45b515.png"> | <img width="400" src="https://user-images.githubusercontent.com/104349824/232971777-a99070a7-9d27-425c-9b4f-9a56f6fc5111.png">

And this is a known issue being tracked at https://github.com/flutter/flutter/issues/51575. I will also leave there my comment as well for updating the labels.

Closing this issue as a duplicate, so please follow up on it for further updates.
