### ISSUE TITLE
[CP] [Impeller] Improve accuracy of glyph spacing

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#124714]
### issue_link

https://github.com/flutter/flutter/issues/124310

### Commit Hash

https://github.com/flutter/engine/commit/aa74ecc04f5680ec1cfe349b0e193ed2fa0c1dd1

### Target

beta

### pr_link

https://github.com/flutter/engine/pull/41123

### Impacted Users

Impeller users

### Impact Description

This causes text to be horizontally misaligned. See screenshots in https://github.com/flutter/engine/pull/41101 and https://github.com/flutter/flutter/issues/124310

### Workaround

No workaround

### Risk

low

### Test Coverage

yes

### Validation Steps

See https://github.com/flutter/engine/pull/41101. Draw text "The quick brown fox jumps over the lazy dog" in a reasonably small font and see if the "i" and "c" in "quick" are reasonably spaced apart.

**Comment by bdero** [comment]
FYI @jonahwilliams @zanderso

**Comment by jonahwilliams** [comment]
LGTM

**Comment by jonahwilliams** [comment]
is this merge to stable or merge to beta? I'm not sure where we are in the process right now actually. I don't think we want to CP into the last stable since this change depends on more recent changes

**Comment by zanderso** [comment]
LGTM, this should target the 3.10 beta.

**Comment by bdero** [comment]
Fixed the description to mention beta and updated the PR to extend 3.10-candidate.1
