### ISSUE TITLE
Built-in support for preloading Canvaskit

### ISSUE THREAD

**Issue by jacobsimionato** [flutter/flutter#124775]
There are a number of different issues related to optimizing the Flutter Web load time, but here I wanted to request a specific feature which I think may be low hanging fruit.

Can we provide an easy way for developers to start preloading the correct version of Canvaskit.wasm early in the load sequence? E.g. add some logic to flutter.js to kick off a Canvaskit preload immediately?

I think in some conditions, this may provide quite a worthwhile load time improvement. For example in my example app, loading on a 10mbit connection, I think the network is nowhere near saturated in the region with the red arrow, because there are just a couple of smaller resources that are preparing to fetch and then actually fetch. If Canvaskit was already downloading at this stage, it might improve the overall load time by ~15% which would be significant.

![Screen Shot 2023-04-13 at 4 34 06 pm](https://user-images.githubusercontent.com/6869388/231676854-d13b8162-4f8a-4ed5-aa47-df2781c507ec.png)

The reason I think this specific change may be worth prioritizing despite all the other optimization efforts is:
- Due to the fact that there are now multiple flavours of Canvaskit that can be chosen at runtime (e.g. the Chromium vs non-Chromium variants), this is more difficult for developers to add themselves compared to preloading other static app resources. For fonts etc, developers can easily just add a preload tag to their HTML and achieve the optimal shallow tree shown in https://github.com/flutter/flutter/issues/118115. But for CanvasKit, this would require JS code that duplicates the logic in the Flutter engine to detect the browser version and programatically preload the correct version of Canvaskit.

- For a simple app, Canvaskit.wasm is over 50% of the total binary size. So for most apps, it's much more important to preload Canvaskit compared to other resources - starting CanvasKit early gives you the best chance of saturating the network connection.

Related issues (both more general):
- https://github.com/flutter/flutter/issues/76009
- https://github.com/flutter/flutter/issues/118115

**Comment by jacobsimionato** [comment]
David, I'm curious what it would take to get this into flutter.js. I know that flutter.js doesn't necessarily know the Canvaskit URL to use right now, but maybe it could somehow? Or maybe there is a better solution that doesn't use flutter.js...

**Comment by kevmoo** [comment]
> David, I'm curious what it would take to get this into flutter.js. I know that flutter.js doesn't necessarily know the Canvaskit URL to use right now, but maybe it could somehow? Or maybe there is a better solution that doesn't use flutter.js...

We know the canvaskit URL in the framework. We could wire this into flutter.js

**Comment by ditman** [comment]
Canvaskit is no longer a single thing, there's at least two variants (optimized for chromium, and with polyfills for other browsers), and the determination of which one gets downloaded happens in the engine:

https://github.com/flutter/engine/blob/ad222b0c93b9c79c3ec88c49e7c3be27b42f75f5/lib/web_ui/lib/src/engine/canvaskit/canvaskit_api.dart#L3833-L3856

In order for the preload to work, we would need to:

* Expose the values-that-only-the-engine knows through the index.html at build time (this would need special g3 code)
* Replicate in flutter.js the same loading logic that happens in the engine (linked above) to prefetch the correct file that is going to be used by the browser.

Not sure there's a fast way of doing the above, particularly keeping in sync the flutter.js loader with whatever the engine does (they live in two separate repos currently).

Another option might be to let flutter.js download and setup its own canvaskit.js/wasm, and then tell flutter where can it find it. I thought bits of this are already supported by the framework, but I'm not sure what needs to be done to get it going! /cc @yjbanov (can we discuss this during the design sprint?)

**Comment by jacobsimionato** [comment]
If there is time to work on this soon, I'd love a timeframe estimate. I implemented Canvaskit preloading in a Google app recently, but I suspect it's broken now because it doesn't take the Chromium/non-Chromium distinction into account, so I want to know whether to add some new more dynamic hack, or wait for built-in support :-D. See b/278815833 for details.

**Comment by ctm-michael** [comment]
This is an important improvement to make, I also would love to see this!

**Comment by ditman** [comment]
I think we need to do this one first:

https://github.com/flutter/flutter/issues/128061

So we can release changes to the engine and flutter.js in a coordinated fashion.

**Comment by eyebrowsoffire** [comment]
This is supported with the new `FlutterLoader.load` API in `flutter.js` that landed here: https://github.com/flutter/flutter/pull/141396
