### ISSUE TITLE
Android sdkmanager tool was found, but failed to run

### ISSUE THREAD

**Issue by anthonyking11** [flutter/flutter#124776]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I run Flutter doctor --android-licenses and the recieve the following message...

PS C:\> flutter doctor --android-licenses
[=======================================] 100% Computing updates...
5 of 7 SDK package licenses not accepted.
Review licenses that have not been accepted (y/N)?
Android sdkmanager tool was found, but failed to run
(C:\Users\antho\AppData\Local\Android\sdk\cmdline-tools\latest\bin\sdkmanager.bat): "exited code -1".
Try re-installing or updating your Android SDK,
visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

I have uninstall and reinstall Android Studio and JDK multiple times to be on the latest.

### Actual results

PS C:\> flutter doctor --android-licenses
[=======================================] 100% Computing updates...
5 of 7 SDK package licenses not accepted.
Review licenses that have not been accepted (y/N)?
Android sdkmanager tool was found, but failed to run
(C:\Users\antho\AppData\Local\Android\sdk\cmdline-tools\latest\bin\sdkmanager.bat): "exited code -1".
Try re-installing or updating your Android SDK,
visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.7.11, on Microsoft Windows [Version 10.0.22621.1555], locale en-US)
    • Flutter version 3.7.11 on channel stable at C:\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f72efea43c (2 days ago), 2023-04-11 11:57:21 -0700
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\antho\AppData\Local\Android\sdk
    • Platform android-UpsideDownCake, build-tools 33.0.2
    • Java binary at:
      C:\Users\antho\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\221.6008.13.2211.9619390\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.24)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.33328.57
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2022.1)
    • Android Studio at C:\Users\antho\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\221.6008.13.2211.9619390
    • Flutter plugin version 73.0.1
    • Dart plugin version 221.6103.1
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[✓] VS Code (version 1.77.3)
    • VS Code at C:\Users\antho\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.62.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1555]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 112.0.5615.49
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 112.0.1722.39

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

**Comment by exaby73** [comment]
Hello @anthonyking11. Could you provide the output to `flutter doctor --android-licenses -v`?

**Comment by anthonyking11** [comment]
PS C:\> flutter doctor --android-licenses
[=======================================] 100% Computing updates...
5 of 7 SDK package licenses not accepted.
Review licenses that have not been accepted (y/N)?
Android sdkmanager tool was found, but failed to run
(C:\Users\antho\AppData\Local\Android\sdk\cmdline-tools\latest\bin\sdkmanager.bat): "exited code -1".
Try re-installing or updating your Android SDK,
visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.
PS C:\> y
y: The term 'y' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS C:\>

**Comment by exaby73** [comment]
> Hello @anthonyking11. Could you provide the output to flutter doctor --android-licenses -v?

Please add the `-v` flag and post the output

**Comment by wiloser** [comment]
i meet the error too.so you have a resolution for it?

**Comment by anthonyking11** [comment]
> PS C:> flutter doctor --android-licenses -v Android sdkmanager not found. Update to the latest Android SDK and ensure that the cmdline-tools are installed to resolve this.
> 
> #0 throwToolExit (package:flutter_tools/src/base/common.dart:10:3) #1 AndroidLicenseValidator.runLicenseManager (package:flutter_tools/src/android/android_workflow.dart:422:7) #2 Doctor.diagnose (package:flutter_tools/src/doctor.dart:366:38) #3 DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48) #4 FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1426:12) #5 FlutterCommand.run. (package:flutter_tools/src/runner/flutter_command.dart:1257:27) #6 AppContext.run. (package:flutter_tools/src/base/context.dart:150:19) #7 CommandRunner.runCommand (package:args/command_runner.dart:209:13) #8 FlutterCommandRunner.runCommand. (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9) #9 AppContext.run. (package:flutter_tools/src/base/context.dart:150:19) #10 FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5) #11 run.. (package:flutter_tools/runner.dart:64:9) #12 AppContext.run. (package:flutter_tools/src/base/context.dart:150:19) #13 main (package:flutter_tools/executable.dart:91:3)

**Comment by exaby73** [comment]
@anthonyking11 Could you re-run the command with `-vv`? Complete command is `flutter doctor --android-licenses -vv`?

**Comment by ravi-golivio** [comment]
I am also facing the same issue. Here is the log output when running `flutter doctor --android-licenses -vv`

```
flutter doctor --android-licenses -vv
[  +11 ms] executing: sysctl hw.optional.arm64
[   +5 ms] Exit code 0 from: sysctl hw.optional.arm64
[        ] hw.optional.arm64: 1
[        ] executing: [/Users/ravilodhi/Downloads/flutter/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[  +11 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[        ] f72efea43c3013323d1b95cff571f3c1caa37583
[        ] executing: [/Users/ravilodhi/Downloads/flutter/] git tag --points-at
f72efea43c3013323d1b95cff571f3c1caa37583
[  +60 ms] Exit code 0 from: git tag --points-at
f72efea43c3013323d1b95cff571f3c1caa37583
[        ] 3.7.11
[   +4 ms] executing: [/Users/ravilodhi/Downloads/flutter/] git rev-parse
--abbrev-ref --symbolic @{upstream}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/stable
[        ] executing: [/Users/ravilodhi/Downloads/flutter/] git ls-remote
--get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +12 ms] executing: [/Users/ravilodhi/Downloads/flutter/] git rev-parse
--abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[        ] executing: sw_vers -productName
[   +8 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[   +7 ms] Exit code 0 from: sw_vers -productVersion
[        ] 13.3.1
[        ] executing: sw_vers -buildVersion
[   +9 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 22E261
[        ] executing: uname -m
[   +3 ms] Exit code 0 from: uname -m
[        ] arm64
[   +7 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[  +20 ms] Artifact Instance of 'MaterialFonts' is not required, skipping
update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping
update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping
update.
[  +10 ms] executing: [/Users/ravilodhi/Downloads/flutter/] git rev-parse
--abbrev-ref HEAD
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[        ] Skipping request to fetchTags - on well known channel stable.
[        ] executing: [/Users/ravilodhi/Downloads/flutter/] git tag --points-at
HEAD
[  +13 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 3.7.11
[   +4 ms] executing: /usr/libexec/java_home -v 1.8
[   +9 ms] Exit code 0 from: /usr/libexec/java_home -v 1.8
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/android/prefs/AndroidLocationsProvider has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:669)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:651)
[ +186 ms] "flutter doctor" took 301ms.
[   +2 ms] Android sdkmanager tool was found, but failed to run
           (Library/Android/sdk/cmdline-tools/latest/bin/sdkmanager): "exited
code 1".
           Try re-installing or updating your Android SDK,
           visit
https://flutter.dev/docs/get-started/install/macos#android-setup for
           detailed instructions.
[   +1 ms] 
           #0      throwToolExit
(package:flutter_tools/src/base/common.dart:10:3)
           #1      AndroidLicenseValidator.runLicenseManager
           (package:flutter_tools/src/android/android_workflow.dart:462:9)
           <asynchronous suspension>
           #2      DoctorCommand.runCommand
           (package:flutter_tools/src/commands/doctor.dart:50:26)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand
(package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure>
           (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +169 ms] ensureAnalyticsSent: 169ms
[   +1 ms] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

**Comment by exaby73** [comment]
Could you try clearing your gradle cache and try again?

**Comment by anthonyking11** [comment]
`PS C:\> flutter doctor --android-licenses -vv
[   +9 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +66 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f72efea43c3013323d1b95cff571f3c1caa37583
[        ] executing: [C:\flutter/] git tag --points-at f72efea43c3013323d1b95cff571f3c1caa37583
[  +69 ms] Exit code 0 from: git tag --points-at f72efea43c3013323d1b95cff571f3c1caa37583
[        ] 3.7.11
[  +11 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[  +53 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +50 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +61 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +53 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +38 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +34 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +25 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +54 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[        ] Skipping request to fetchTags - on well known channel stable.
[        ] executing: [C:\flutter/] git tag --points-at HEAD
[  +63 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 3.7.11
[   +6 ms] executing: C:\Program Files\Android\Android Studio\jbr\bin\java -version
[ +108 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jbr\bin\java -version
[   +1 ms] openjdk version "17.0.6" 2023-01-17
           OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
           OpenJDK 64-Bit Server VM (build 17.0.6+0-b2043.56-9586694, mixed mode)
[=======================================] 100% Computing updates...
6 of 7 SDK package licenses not accepted.
Review licenses that have not been accepted (y/N)?
[+1301 ms] "flutter doctor" took 1,689ms.
[   +6 ms] Android sdkmanager tool was found, but failed to run
           (C:\Users\antho\AppData\Local\Android\Sdk\cmdline-tools\latest\bin\sdkmanager.bat): "exited code -1".
           Try re-installing or updating your Android SDK,
           visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.
[   +2 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      AndroidLicenseValidator.runLicenseManager
(package:flutter_tools/src/android/android_workflow.dart:462:9)
           <asynchronous suspension>
           #2      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:26)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1257:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[ +123 ms] ensureAnalyticsSent: 121ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1`

**Comment by anthonyking11** [comment]
I have tried to clear gradle cache but unable to locate with %USERPROFILE%\.gradle\caches

**Comment by exaby73** [comment]
Could you check if `C:\Users\antho\AppData\Local\Android\Sdk\cmdline-tools\latest\bin\sdkmanager.bat` exists on your machine?

**Comment by anthonyking11** [comment]
`PS C:\Users\antho\AppData\Local\Android\Sdk\cmdline-tools\latest\bin> cd sdkmanager.bat
Set-Location: Cannot find path 'C:\Users\antho\AppData\Local\Android\Sdk\cmdline-tools\latest\bin\sdkmanager.bat' because it does not exist.`

**Comment by exaby73** [comment]
Does the file `sdkmanager.bat` exist in that location?

**Comment by anthonyking11** [comment]
`sdkmanager.bat` exist in `C:\Users\antho\AppData\Local\Android\Sdk\tools\bin`

**Comment by exaby73** [comment]
Could you tell me what you `JAVA_HOME` variable is set to? You can try running `echo $env:JAVA_HOME` in your ternimal

**Comment by anthonyking11** [comment]
C:\Program Files\Java\jdk-17

**Comment by exaby73** [comment]
Please try reinstalling the Android SDK and confirm if it fixes your issue. Else I'll label the issue for further insights from the team

**Comment by ibrahimmerchiche1997** [comment]
me too,I have this errors in my cmd:
![Capture d’écran 2023-04-24 185857](https://user-images.githubusercontent.com/65645808/234078301-bc2d6e6d-de95-41ce-a8d2-ce43af79bdbf.png)

**Comment by turnbew** [comment]
This issue happened with me either. 

What helped me to change the JAVA_HOME environment variable value on local (Windows), 

FROM 

c:<Path To Android Studio>\jre 

TO 

c:<Path to Android Studio>\jbr

In my case path was: \Program Files\Android\Android Studio

and then worked.

**Comment by azhar966** [comment]
same problem with me i did all mandatory steps but still error occurred
.
Android sdkmanager tool was found, but failed to run
(C:\Users\Micro\AppData\Local\Android\sdk\cmdline-tools\latest\bin\sdkmanager.bat): "exited code 1".
Try re-installing or updating your Android SDK,
visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

**Comment by christopherfujino** [comment]
@andrewkolos I *think* this is related to https://github.com/flutter/flutter/issues/122609#issuecomment-1496910242, right?

> To my limited knowledge, sdkmanager, which is used to verify the acceptance of the license, depends on Java. In order, it looks for JAVA_HOME and then java on PATH. I imagine this is also the case for the rest of the Android SDK.

Should we be setting `JAVA_HOME` to be the Android Studio version when invoking sdkmanager as part of `flutter doctor --android-licenses`?

**Comment by asoap** [comment]
I managed to fix this on my end.  Note, I'm new to all of this.  I basically had Android Studio installed 4 years ago, played around with it.  Now coming back to play with Flutter.  

What worked for me:

I downloaded the lastest Java Development Kit.  As of the time of this writing that is JDK-20. 

I installed it and then I had to manually update my environment variables.  

JAVA_HOME  = C:\Program Files\Java\jdk-20
JDK_HOME = C:\Program Files\Java\jdk-20

I then re-ran "flutter doctor"  and "flutter doctor --android-licenses".  Now I didn't get the error and it actually accepted the licensce.  I'm guessing everyone here having the issue is using an older version of JDK?

**Comment by Pradeva** [comment]
Sir, thank you very much. I can finally fix the problem.

**Comment by sv-17** [comment]
> Sir, thank you very much. I can finally fix the problem.

can you tell what made it work?

**Comment by Pradeva** [comment]
before i changed my JAVA_HOME in my Environment Variables it was Jdk 18. it cause error for my sdk. then it tells me to update my jdk. so i install java version 20 and change my JAVA_HOME to jdk 20. and it just work perfectly.

after that all you need to do is type flutter doctor --android-licenses in you cmd

**Comment by Srinu1919** [comment]
I tried almost all the solutions available on internet for this issue and none helped but finally a simple solution solved my problem and i.e

So when you copy and paste the Jdk location for "JAVA_HOME" it automatically adds a semicolumn `C:\Program Files\Java\jdk-20;` which can be seen by editing the text and not just edit. and just by removing that semicolumn my problem is solved

**Comment by Noweisri** [comment]
> I managed to fix this on my end. Note, I'm new to all of this. I basically had Android Studio installed 4 years ago, played around with it. Now coming back to play with Flutter.
> 
> What worked for me:
> 
> I downloaded the lastest Java Development Kit. As of the time of this writing that is JDK-20.
> 
> I installed it and then I had to manually update my environment variables.
> 
> JAVA_HOME = C:\Program Files\Java\jdk-20 JDK_HOME = C:\Program Files\Java\jdk-20
> 
> I then re-ran "flutter doctor" and "flutter doctor --android-licenses". Now I didn't get the error and it actually accepted the licensce. I'm guessing everyone here having the issue is using an older version of JDK?

It worked for me, FINALLY, thank you.

**Comment by Muhi** [comment]
I ran in to the same problem but I am on a Mac. 
It looks like when running Flutter --android-licenses command It didn't like that I had a symlink set in my .bash for the path and JAVA_HOME. I had to point it to the actual location of the java install.
I hope this helps any Mac users.

**Comment by KARIMY6** [comment]
Hi
After installed the latest java and set 'JAVA_HOME = C:\Program Files\Java\jdk-20 JDK_HOME = C:\Program Files\Java\jdk-20'
the problem is solved

**Comment by TemesgenA** [comment]
> I managed to fix this on my end. Note, I'm new to all of this. I basically had Android Studio installed 4 years ago, played around with it. Now coming back to play with Flutter.
> 
> What worked for me:
> 
> I downloaded the lastest Java Development Kit. As of the time of this writing that is JDK-20.
> 
> I installed it and then I had to manually update my environment variables.
> 
> JAVA_HOME = C:\Program Files\Java\jdk-20 JDK_HOME = C:\Program Files\Java\jdk-20
> 
> I then re-ran "flutter doctor" and "flutter doctor --android-licenses". Now I didn't get the error and it actually accepted the licensce. I'm guessing everyone here having the issue is using an older version of JDK?

This worked for me. Thanks

**Comment by israa-alsarwi** [comment]
> I managed to fix this on my end. Note, I'm new to all of this. I basically had Android Studio installed 4 years ago, played around with it. Now coming back to play with Flutter.
> 
> What worked for me:
> 
> I downloaded the lastest Java Development Kit. As of the time of this writing that is JDK-20.
> 
> I installed it and then I had to manually update my environment variables.
> 
> JAVA_HOME = C:\Program Files\Java\jdk-20 JDK_HOME = C:\Program Files\Java\jdk-20
> 
> I then re-ran "flutter doctor" and "flutter doctor --android-licenses". Now I didn't get the error and it actually accepted the licensce. I'm guessing everyone here having the issue is using an older version of JDK?

it works than you
