### ISSUE TITLE
`CupertinoListSection` should take a parameter to change the color of the divider color

### ISSUE THREAD

**Issue by stMerlHin** [flutter/flutter#124744]
## Use case
Am using `CupertinoListSection.insetGrouped` to create a list of clicable item in ios style. Everything is rendering good but we cannot set the color of the divider to a preferred one. Setting the theme to light make the divider filled with black which is not so good to look for me. I would like to have capability to set my custom color to the divider.

![image](https://user-images.githubusercontent.com/77164238/231610585-22a31748-092f-47e5-bb93-b4ae4b5836dc.png)

## Proposal
Add `dividerColor` parameter to `CupertinoListSection`.

**Comment by stMerlHin** [comment]
Hey @darshankawar, I would like to work on it if no one is meant to yet.

**Comment by leighajarett** [comment]
@stMerlHin if you are actively working on this, please assign the issue to yourself :)
