### ISSUE TITLE
Need introductory sample for flutter_sprites

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#1247]
Currently it's difficult to get started.

**Comment by eseidelGoogle** [comment]
@vlidholt plans to work on adding some flutter_sprites examples to the material_gallery and thus will solve this.

**Comment by eseidelGoogle** [comment]
@vlidholt has been adding docs recently and may already have addressed this?

**Comment by Hixie** [comment]
Obsolete, we've removed flutter_sprites for now.
