### ISSUE TITLE
[flutter_markdown] online markdown editor will freeze

### ISSUE THREAD

**Issue by k2s** [flutter/flutter#124728]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. open https://dart-lang.github.io/markdown/
2. paste following code:

```
[]()  | 
------|------
Row 1 | row 2
```

### Expected results

Optimal would be to render table without header (Bitbucket's markdown) or at least it should not freeze the app.

### Actual results

the web page will freeze

### Code sample

```
[]()  | 
------|------
Row 1 | row 2
```

### Flutter Doctor output

<details><summary>Doctor output</summary>

can't provide becasue the editor is not hosted by me

</details>

**Comment by stuartmorgan** [comment]
Issues with `markdown` need to be filed in [it's repository](https://github.com/dart-lang/markdown).

Closing as this doesn't appear to be related to the Flutter package.
