### ISSUE TITLE
FireStore plugin doesn't expose document ID

### ISSUE THREAD

**Issue by renefloor** [flutter/flutter#12471]
According to the documentation you can do something like this:
```
db.collection("cities").get().then(function(querySnapshot) {
    querySnapshot.forEach(function(doc) {
        console.log(doc.id, " => ", doc.data());
    });
});
```
The flutter example does this
```
          children: snapshot.data.documents.map((document) {
            return new ListTile(
              title: new Text(document['title']),
              subtitle: new Text(document['author']),
            );
```
This is almost the same, but with flutter you already have the data of the document. The FireStore plugin should also expose the document ID.

**Comment by renefloor** [comment]
@collinjackson

**Comment by Pacane** [comment]
I've temporarily got around this issue by assigning an ID manually as a field for my object, but I'd expect to have a getter or something mapped to the real document ID.

**Comment by Skylled** [comment]
This is a blocker for me switching my project to Firestore. It's currently impossible for me to assign a DocumentReference as a value to another Document.

**Comment by collinjackson** [comment]
Thanks for the ping, I should have an update on this shortly.

**Comment by bjornbjorn** [comment]
Also ran into this the other day. I imagine most people switching to Firestore will run into this at some point - sooner or later you'll need the documentID.

**Comment by collinjackson** [comment]
Fixed by flutter/plugins#244, but I want to tweak the API a bit and write a test for it once flutter/plugins#254 lands.

**Comment by dshukertjr** [comment]
Okay, so how can one get the document id or the path inside the iteration like this:
````children: snapshot.data.documents.map((document) {
            return new ListTile(
              title: new Text(document['title']),
              subtitle: new Text(document['author']),
            );`

**Comment by zoechi** [comment]
@dshukertjr I think this would be a good question for StackOverflow. 
Closed issues aren't tracked and comments easily get lost.

**Comment by kroikie** [comment]
@renefloor

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/955. Any further collaboration will be done there.

**Comment by chornbe** [comment]
As a ride-along to this, am I missing (or is just not available) the ability to set a custom id? A users collection with the unique email address as the ID would be super helpful, as one example.
