### ISSUE TITLE
Create a yapf/pylint for our Recipes Repository for common formatting of our code

### ISSUE THREAD

**Issue by ricardoamador** [flutter/flutter#124737]
As stated it would be good to have some common formatting rules for the Recipes python code within infra. 

Supposedly this was setup at one point but that will need to be investigated.

**Comment by godofredoc** [comment]
It is already defined here: https://cs.opensource.google/flutter/recipes/+/main:.style.yapf

**Comment by godofredoc** [comment]
Tricium recipe fix: https://flutter-review.googlesource.com/c/recipes/+/43000

**Comment by godofredoc** [comment]
Tricium service configs:

* https://flutter-review.googlesource.com/c/infra/+/43100
* https://flutter-review.googlesource.com/c/infra/+/43140

**Comment by ricardoamador** [comment]
@godofredoc Is this complete? If so feel free to close.

**Comment by godofredoc** [comment]
Yes, let's close it.
