### ISSUE TITLE
Remove CodeQL python checks from flutter/buildroot

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#124702]
The linting strategy for python code in an engine checkout is to use pylint in the regular engine CI linting shards.

cc @godofredoc

**Comment by zanderso** [comment]
Example PR where I saw the checks https://github.com/flutter/buildroot/pull/712

**Comment by godofredoc** [comment]
Some data points about this request:

* CodeQL is a SAST tool with a purpose different than pylint.
* Removing CodeQL limits the ability of security to find dangerous workflows introduced by new python scripts in the repository.
* Not fixing dangerous workflows found by tools like CodeQL will add a lot of noise on an eventual security audit.
