### ISSUE TITLE
This is expected behavior. When there are multiple gesture recognizers at play that could potentially recognize a gesture there is a slight delay in figuring out who should handle the gesture, see also: https://docs.flutter.dev/development/ui/advanced/gestures#gesture-disambiguation

### ISSUE THREAD

**Issue by zappaz00** [flutter/flutter#124790]
Sorry, but where are you see multiple gesture recognizers?

              This is expected behavior. When there are multiple gesture recognizers at play that could potentially recognize a gesture there is a slight delay in figuring out who should handle the gesture, see also: https://docs.flutter.dev/development/ui/advanced/gestures#gesture-disambiguation

_Originally posted by @goderbauer in https://github.com/flutter/flutter/issues/121674#issuecomment-1487685461_

**Comment by ToniHeiss** [comment]
Inkwell has an onTap, which is a gesture detector.

**Comment by darshankawar** [comment]
@zappaz00 
Above comment should help to answer your question. Also, see if [this](https://medium.com/koahealth/combining-multiple-gesturedetectors-in-flutter-26d899d008b2) article helps further.

Closing for now. If you disagree, write in comments and I'll reopen it.
