### ISSUE TITLE
Add parentNavigatorKey / navigatorKey to ShellRoute example in go_router_builder

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#124734]
ShellRoute support in go_router_builder (https://github.com/flutter/packages/pull/3439) should have some tests in place to verify that [`_generateNavigatorKeyGetterCode`](https://github.com/flutter/packages/blob/6bf2ea8facf742cfa0f1785a0d8e48fb68032a56/packages/go_router_builder/lib/src/route_config.dart#L109) is working. The [go_router_builder example](https://github.com/flutter/packages/blob/main/packages/go_router_builder/example/lib/shell_route_with_keys_example.dart)  should include usages of parentNavigatorKey + navigatorKey so the unit tests cover this functionality.

**Comment by chunhtai** [comment]
I do see there is $parentNavigatorKey and $navigatorKey in the example, is there something missing?

**Comment by kevmoo** [comment]
> I do see there is $parentNavigatorKey and $navigatorKey in the example, is there something missing?

I think that's the problem.

**Comment by johnpryan** [comment]
Nevermind, I was misunderstanding how this feature works.
