### ISSUE TITLE
[shared_preferences] ` not supported in -source 7` errors building on Android

### ISSUE THREAD

**Issue by XutongGithub** [flutter/flutter#124839]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

my yaml file use shared_preferences 2.1.0 and run, Android is report an error.

### Actual results

.../flutter/.pub-cache/hosted/pub.flutter-io.cn/shared_preferences_android-2.1.1/android/src/main/java/io/flutter/plugins/sharedpreferences/Messages.java:84: error: static interface methods are not supported in -source 7
    static @NonNull MessageCodec<Object> getCodec() {
                                                 ^
  (use -source 8 or higher to enable static interface methods)
.../flutter/.pub-cache/hosted/pub.flutter-io.cn/shared_preferences_android-2.1.1/android/src/main/java/io/flutter/plugins/sharedpreferences/Messages.java:103: error: lambda expressions are not supported in -source 7
              (message, reply) -> {
                               ^
  (use -source 8 or higher to enable lambda expressions)
2 errors

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.3.0, on macOS 12.6.1 21G217 darwin-x64, locale en-CN)
    • Flutter version 3.3.0 on channel stable at .../Desktop/FZDev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (8 months ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/fjrb/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at .../Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

**Comment by JherysVargas** [comment]
I have the same problem, any solution?

**Comment by XutongGithub** [comment]
邮件已收到。谢谢！

**Comment by huangsir0** [comment]
I have the same problem, any solution?

**Comment by theideasaler** [comment]
A temporary fix for your pipeline is you can set a fixed version number for your shared_preferences by removing `^` from `^2.1.0` until shared_preference package got it fixed.

```yaml
shared_preferences: 2.10.0
```

**Comment by Thioby** [comment]
Temporary solution override dependencies:

```
dependency_overrides:
  shared_preferences_android: 2.1.0
  shared_preferences_ios: 2.1.0
```

**Comment by XutongGithub** [comment]
> 

but this dependency is in shared_preferences, it's not easy to change.

**Comment by XutongGithub** [comment]
> 

it don't work for me.

**Comment by moneyBreak** [comment]
> dependency_overrides:
>   shared_preferences_android: 2.1.0
>   shared_preferences_ios: 2.1.0

 it work for me!But i can't understand only ```dependency_overrides:``` is useful.```dependency``` can't be answer.

**Comment by moneyBreak** [comment]
> > 
> 
> it doesn't work for me.

hi , i know our problem. you should run ```flutter clean```  before reset ```shared_preferences: 2.1.0``` in ```publspec.yaml```. good luck~

**Comment by Thioby** [comment]
> it work for me!But i can't understand only `dependency_overrides:` is useful.`dependency` can't be answer.

Because shared_preferences has internally dependencies  with `^` to 
```
  shared_preferences_android: 
  shared_preferences_ios: 
```
that's when you run `pub get`, pub downloads lates broken version `2.1.1`
You can force version on application lvl using `dependency_overrides`

**Comment by XutongGithub** [comment]
> > it work for me!But i can't understand only `dependency_overrides:` is useful.`dependency` can't be answer.
> 
> Because shared_preferences has internally dependencies with `^` to
> 
> ```
>   shared_preferences_android: 
>   shared_preferences_ios: 
> ```
> 
> that's when you run `pub get`, pub downloads lates broken version `2.1.1` You can force version on application lvl using `dependency_overrides`

excellent reply @Thioby

**Comment by XutongGithub** [comment]
> <img alt="Screenshot 2023-04-14 at 1 41 52 PM" width="1357" src="https://user-images.githubusercontent.com/22536559/231985060-3e49a872-dbb2-4b66-a9e5-7b35d1e39316.png">
> 
> I used shared_preferences_android: package also. But I got the same error.

you can use shared_preferences_android: 2.1.0 @vinodlee

**Comment by huycozy** [comment]
Hi everyone facing this issue, 
I try reproducing this issue but don't see the crash. I initially added `shared_preferences: ^2.1.0` and `shared_preferences_android: 2.1.0` and then upgrading to `shared_preferences_android: ^2.1.1` but the crash doesn't occur.

Is that possible to reproduce this in a specific scenario?

**Comment by moneyBreak** [comment]
> excellent reply

you need clear your cache.run ```flutter pub deps```to look your dependenceis tree.
if ```dependencies_override``` is valid. you will look ```shared_preferences_android```  is inside 
 ```shared_preferences```, not contain .
if not changed,try ```flutter pub cache repair``` then ```flutter pub get```,to rebuild your dependencies tree .it always effect. wish it helpful~

**Comment by moneyBreak** [comment]
> you need clear your cache.run `flutter pub deps`to look your dependenceis tree. if `dependencies_override` is valid. you will look `shared_preferences_android` is inside `shared_preferences`, not contain . if not changed,try `flutter pub cache repair` then `flutter pub get`,to rebuild your dependencies tree .it always effect. wish it helpful~
> 
> > <img alt="Screenshot 2023-04-14 at 1 41 52 PM" width="1357" src="https://user-images.githubusercontent.com/22536559/231985060-3e49a872-dbb2-4b66-a9e5-7b35d1e39316.png">
> > I used shared_preferences_android: package also. But I got the same error.

@huycozy. look this

**Comment by moneyBreak** [comment]
> Hi everyone facing this issue, I try reproducing this issue but don't see the crash. I initially added `shared_preferences: ^2.1.0` and `shared_preferences_android: 2.1.0` and then upgrading to `shared_preferences_android: ^2.1.1` but the crash doesn't occur.
> 
> Is that possible to reproduce this in a specific scenario?

you may need clear your cache with```flutter clean``` or ```flutter pub cache repair```
it show everytime when i want run```flutter build apk --split-per-abi --no-sound-null-safety``` to build my release apk until set ```shared_preferences_android: 2.1.0``` in ```dependencies_override```.

**Comment by stuartmorgan** [comment]
`shared_preferences_android` 2.1.1 has been retracted, so updating packages will no longer resolve to it unless it's already in your lock file. If you've added a `dependency_overrides` entry for it, that should be safe to remove now.

**Comment by Adrift001** [comment]
警告: [options] 源值7已过时, 将在未来所有发行版中删除
警告: [options] 目标值7已过时, 将在未来所有发行版中删除
警告: [options] 要隐藏有关已过时选项的警告, 请使用 -Xlint:-options。
/Users/swifter/.pub-cache/hosted/pub.dev/shared_preferences_android-2.1.1/android/src/main/java/io/flutter/plugins/sharedpreferences/Messages.java:84: 错误: -source 7 中不支接口方法
    static @NonNull MessageCodec<Object> getCodec() {
                                                 ^
  (请使用 -source 8 或更高版本以启用 静态接口方法)
/Users/swifter/.pub-cache/hosted/pub.dev/shared_preferences_android-2.1.1/android/src/main/java/io/flutter/plugins/sharedpreferences/Messages.java:103: 错误: -source 7 中不ambda 表达式
              (message, reply) -> {
                               ^
  (请使用 -source 8 或更高版本以启用 lambda 表达式)

**Comment by XutongGithub** [comment]
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/13117057/232357124-a5397813-a302-4813-92b6-e23a1e2c7d5f.png">
update Android SDK 33 and JDK 11 can solve this problem.

**Comment by Adrift001** [comment]
@XutongGithub 升级了flutter, 升了gradle, 改了shared_preferences, 加了几个编译参数, 现在可以了. 还是用JDK17.

**Comment by AhhhhDong** [comment]
@Adrift001 具体改了什么，能贴一下参考下吗

**Comment by Adrift001** [comment]
@ AhhhhDong 
#### 首先更新到最新的flutter
#### 修改下面内容
pubspec.yaml
```
  shared_preferences: ^2.1.0
```
android/gradle.properties
```
org.gradle.jvmargs=-Xmx1536M --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED
```
android/gradle/wrapper/gradle-wrapper.properties
```
distributionUrl=https\://services.gradle.org/distributions/gradle-7.3-all.zip
```
