### ISSUE TITLE
[CP] Metal toImage/toImageSync before surface setup

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#124836]
### issue_link

https://github.com/flutter/flutter/issues/124181

### Commit Hash

flutter/engine@f09106065eaba080fa81dee7caba3a118faadc9a

### Target

beta

### pr_link

https://github.com/flutter/engine/pull/41189

### Impacted Users

End-customers on iOS

### Impact Description

Images may get stuck in a failure/error state due to a race condition during application startup.

### Workaround

None.

### Risk

low

### Test Coverage

yes

### Validation Steps

Run the test, or run the app in the linked issue in release mode.

**Comment by zanderso** [comment]
CP LGTM
