### ISSUE TITLE
[image_picker] incorrect resize image function

### ISSUE THREAD

**Issue by shabanov-krl** [flutter/flutter#124849]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. pick image with original size 4272x2848 and set params maxWidth=3000, maxHeight=3000

### Expected results

1. get image 3000x2000

### Actual results

1. get image 4272x2848

### Alleged reason
1. [android src](https://github.com/flutter/packages/blob/e4ec15590935e50bb23eadd6481db2535161450c/packages/image_picker/image_picker_android/android/src/main/java/io/flutter/plugins/imagepicker/ImageResizer.java#L31)
2. [ios src](https://github.com/flutter/packages/blob/e4ec15590935e50bb23eadd6481db2535161450c/packages/image_picker/image_picker_ios/ios/Classes/FLTImagePickerImageUtil.m)

![image](https://user-images.githubusercontent.com/46450095/231978351-ba8791dd-9b51-4a39-84ae-1eec6e60a85f.png)

if remove `!` on 79 line it will work correctly

### Versions 
1. image_picker: ^0.8.7+2

### Platforms
1. android - reproduced
2. ios - i guess will reproduce
3. web - didn't check

### Code sample

<details><summary>Code sample</summary>

```dart
  final XFile? result = await ImagePicker().pickImage(
    source: ImageSource.gallery,
    maxHeight: 3000,
    maxWidth: 3000,
  );
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.1, on Ubuntu 22.04.2 LTS 5.15.0-69-generic, locale ru_RU.UTF-8)
    • Flutter version 3.7.1 on channel stable at /home/shabanov/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7048ed95a5 (2 месяца назад), 2023-02-01 09:07:31 -0800
    • Engine revision 800594f1f4
    • Dart version 2.19.1
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/shabanov/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.18+10-post-Ubuntu-0ubuntu122.04)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (version 2022.1)
    • Android Studio at /home/shabanov/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390
    • Flutter plugin version 73.0.1
    • Dart plugin version 221.6103.1
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.75.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.58.0

[✓] Connected device (4 available)
    • SM A325F (mobile)            • RF8R90KRH3M   • android-arm64  • Android 13 (API 33)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Ubuntu 22.04.2 LTS 5.15.0-69-generic
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 110.0.5481.177

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @shabanov-krl 
Can you take a look at [this](https://github.com/flutter/flutter/issues/88901) issue and see if it resembles your case ?

**Comment by shabanov-krl** [comment]
similar [issue](https://github.com/flutter/flutter/issues/88901)
