### ISSUE TITLE
Drawer -> NavigationDrawer needs migration guide and docs

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#124887]
Follow up to https://github.com/flutter/flutter/issues/103551

Drawer has M3 support, but per @guidezpl it is meant to be replaced by NavigationDrawer. This type of migration is most painful for developers, so we should provide better help.

Dart fix is not capable of helping here.

Drawer is styled for M2 & M3 spec.
NavigationDrawer is style for M3 and the intended replacement for Drawer.

To resolve this issue we should do these things:

- [ ] Document on Drawer that NavigationDrawer is the M3 counterpart and replacement.
- [ ] Create a migration guide for https://docs.flutter.dev/release/breaking-changes
- [ ] Send a message to flutter-announce mentioning this and including a link to the migration guide
- [ ] (Eventually) deprecate Drawer?

**Comment by Piinks** [comment]
Related: 
- #124884 
- #124885

**Comment by HansMuller** [comment]
We don't plan to deprecate or remove the Drawer component. Applications can choose to use the M3 NavigationDrawer component and we would recommend doing so in new `useMaterial3: true` applications.  Migrating existing code from Drawer to NavigationDrawer is optional.

**Comment by TahaTesser** [comment]
> - [ ] Document on Drawer that NavigationDrawer is the M3 counterpart and replacement.
> ~~- [ ] Create a migration guide for https://docs.flutter.dev/release/breaking-changes~~
> ~~- [ ] Send a message to flutter-announce mentioning this and including a link to the migration guide~~
> ~~- [ ] (Eventually) deprecate Drawer?~~


I support that if there aren't breaking changes, we can remove other tasks and fix this issue with a documentation update and i can fix that.

**Comment by HansMuller** [comment]
Thanks, that sounds good.
