### ISSUE TITLE
`toImage` without a long `DeviceHostTransfer` 

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#124828]
## Use case

(I am willing to PR!)

Hi thanks for the great Flutter framework! I wonder whether it is a must for `toImage` to have a big `DeviceHostTransfer`? IMHO if using the (implicit) layer cache of Flutter engine layers, this may not be needed? Please correct me if I am wrong!

The timeline screenshot below is caused by `toImage` on a few complex layers that is roughly as large as the screen size. You can focus only on the second `DoMakeRasterSnapshot` block (since the first and thread can be optimized away indeed). As can be seen, there is a large part spent doing DeviceHostTransfer.

P.S. Sample timeline if you are interested:

![image](https://user-images.githubusercontent.com/5236035/231906269-5ff9104b-914a-4fba-9c52-7848aaa2a2c5.png)

**Comment by fzyzcjy** [comment]
Corresponding PR: https://github.com/flutter/engine/pull/41198

**Comment by jonahwilliams** [comment]
Certain kinds of images are specified as host images, and removing the host transfer changes the behavior.
