### ISSUE TITLE
ANR: IndexedOutOfBoundsException when picking image file without an extension

### ISSUE THREAD

**Issue by aloh86** [flutter/flutter#124821]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I discovered this issue as I was using image_picker to pick a photo that Android asked me to rename before downloading because the image name was so long (given a GUID of some sort). I renamed the photo not knowing I had to include the extension. When I picked the image using image_picker the app crashed. 

**Important prerequisite to reproduce**
This issue only happens on certain versions of Android (e.g. Android 7.0/API 24). Certain versions of the Android picker allow images to be renamed without an extension. Other, newer versions of the allow renaming without an extension, but the file is no longer considered an image and not visible in the image picker without a valid image extension (e.g. jpg or png).

1. On mobile device or emulator (preferably with Android 7.0/API 24), open web browser and download a jpg or png image from the internet.
2. Rename the file so that the extension including the dot is removed (e.g. save "image.jpg" as "image").
3. From development device download simplified code repo at:
4. Run app and pick the download image in step 1.
5. Observe app crash.

Issue occurs on both `flutter channel stable` and `flutter channel master`.

### Expected results

File should be picked with no ANR/exception.

### Actual results

An IndexOutOfBoundsException is being thrown and never caught causing app to crash.

### Code sample

<details><summary>Code sample</summary>
Requires installation of image_picker plugin.

```dart
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'image picker ext. bug',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Extension bug demo"),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'Download a file jpg or png file and rename it with no extension (e.g. rename image.jpg to image).'
  'Picking that image with the image_picker will crash the app.',
            ),
            ElevatedButton(
                onPressed: () async {
                  final ImagePicker picker = ImagePicker();
                  final XFile? image = await picker.pickImage(source: ImageSource.gallery);
                },
                child: Text("Pick image")
            )
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[device-2023-04-04-211959.webm](https://user-images.githubusercontent.com/1497463/231890617-58ea7177-d596-4805-980d-590defb38c5e.webm)

</details>

### Logs

<details><summary>Logs</summary>

```
E/AndroidRuntime( 3761): FATAL EXCEPTION: main
E/AndroidRuntime( 3761): Process: com.example.image_picker_ext_bug, PID: 3761
E/AndroidRuntime( 3761): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/document/5 flg=0x1 }} to activity {com.example.image_picker_ext_bug/com.example.image_picker_ext_bug.MainActivity}: java.lang.StringIndexOutOfBoundsException: length=8; regionStart=0; regionLength=-1
E/AndroidRuntime( 3761): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4053)
E/AndroidRuntime( 3761): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4096)
E/AndroidRuntime( 3761): 	at android.app.ActivityThread.-wrap20(ActivityThread.java)
E/AndroidRuntime( 3761): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1516)
E/AndroidRuntime( 3761): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 3761): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime( 3761): 	at android.app.ActivityThread.main(ActivityThread.java:6077)
E/AndroidRuntime( 3761): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3761): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
E/AndroidRuntime( 3761): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
E/AndroidRuntime( 3761): Caused by: java.lang.StringIndexOutOfBoundsException: length=8; regionStart=0; regionLength=-1
E/AndroidRuntime( 3761): 	at java.lang.String.substring(String.java:1931)
E/AndroidRuntime( 3761): 	at io.flutter.plugins.imagepicker.FileUtils.getBaseName(FileUtils.java:134)
E/AndroidRuntime( 3761): 	at io.flutter.plugins.imagepicker.FileUtils.getPathFromUri(FileUtils.java:70)
E/AndroidRuntime( 3761): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:567)
E/AndroidRuntime( 3761): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:544)
E/AndroidRuntime( 3761): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:807)
E/AndroidRuntime( 3761): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:430)
E/AndroidRuntime( 3761): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:811)
E/AndroidRuntime( 3761): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:771)
E/AndroidRuntime( 3761): 	at android.app.Activity.dispatchActivityResult(Activity.java:6915)
E/AndroidRuntime( 3761): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4049)
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.9, on Microsoft Windows [Version 10.0.19044.2728], locale en-US)
This is taking an unexpectedly long time...[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Chrome - develop for the web
[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.3)
    ✗ Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
      development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.76.0)
[✓] Connected device (4 available)
[✓] HTTP Host Availability
```

</details>

**Comment by stuartmorgan** [comment]
This should be a very simple fix; [this code](https://github.com/flutter/packages/blob/9852b41ff46771c24bca26919fc345d69bdd0b1a/packages/image_picker/image_picker_android/android/src/main/java/io/flutter/plugins/imagepicker/FileUtils.java#L134) just needs to handle the case where there's no `.` in the file name.

@tarrinneal Could you take this?

**Comment by aloh86** [comment]
Thanks, @stuartmorgan. I forked packages and tested out a solution which worked for me. Would it be OK if I attempt a PR at this? It would be my first contribution though so I gotta read through the docs on contributing.

```
private static String getBaseName(String fileName) {
    int endIndex = fileName.lastIndexOf('.');
    
    if (-1 == endIndex) {
      fileName = fileName.concat('.');
    }
    // Basename is everything before the last '.'.
    return fileName.substring(0, fileName.lastIndexOf('.'));
}
```

**Comment by tarrinneal** [comment]
> Thanks, @stuartmorgan. I forked packages and tested out a solution which worked for me. Would it be OK if I attempt a PR at this? It would be my first contribution though so I gotta read through the docs on contributing.

We're always happy to receive community pr's. Let me know if you have any questions!

**Comment by tarrinneal** [comment]
> Thanks, @stuartmorgan. I forked packages and tested out a solution which worked for me. Would it be OK if I attempt a PR at this? It would be my first contribution though so I gotta read through the docs on contributing.
> 
> ```
> private static String getBaseName(String fileName) {
>     int endIndex = fileName.lastIndexOf('.');
>     
>     if (-1 == endIndex) {
>       fileName = fileName.concat('.');
>     }
>     // Basename is everything before the last '.'.
>     return fileName.substring(0, fileName.lastIndexOf('.'));
> }
> ```

I'd recommend just returning the file name rather than concat-ing the '.' then removing it again.

**Comment by tarrinneal** [comment]
@aloh86 Were you still planning on submitting a pr for this issue?

**Comment by aloh86** [comment]
@tarrinneal Thanks for checking in. I was working on it, but I think you should take over. I have more on my plate at work than I thought.

I did take a look at the code, and noticed that the tests check against file names with periods in them (e.g. a.b.png), so if a file is missing an extension, but has a period in it, you may have to check whether the substring after the last period is a valid MIME type.

```
private static String getBaseName(String fileName, String extensionFromMimeType) {
    int endIndex = fileName.lastIndexOf('.');

    if (-1 == endIndex) {
      return fileName;
    }

    String extensionFromFileName  = fileName.substring(endIndex);
    final MimeTypeMap mime = MimeTypeMap.getSingleton();
    // Covers the case where a file is missing an extension, but has one or more periods.
    // (e.g. File name a.b is checked to see if 'b' is valid registered mime extension.)
    if (!extensionFromMimeType.equals(extensionFromFileName) && !mime.hasExtension(extensionFromFileName.replaceFirst(".", ""))) {
      return fileName;
    }

    // Basename is everything before the last '.'.
    return fileName.substring(0, fileName.lastIndexOf('.'));
  }
```

**Comment by stuartmorgan** [comment]
> I did take a look at the code, and noticed that the tests check against file names with periods in them (e.g. a.b.png)

It checks that because a draft of the code during review of the PR that added it incorrectly returned what was before the first `.` as the basename (i.e., it returned `a` in that example), which isn't how basenames vs extensions are defined and was therefore incorrect.

> you may have to check whether the substring after the last period is a valid MIME type.

I assume you mean extension, not MIME type, but there's really no such thing as a "valid" or "invalid" extension. A file called `a.b` has a basename of `a` and an extension of `b`, whether that's what the person naming it meant or not.

**Comment by tarrinneal** [comment]
> Note from android triage: it looks like this has been left without someone to take over, is that correct @stuartmorgan @tarrinneal? Happy to take over if so, but let me know if there is actually someone working on this.

It's on my list, but my bandwidth is pretty tight atm. If you have time, feel free. If not, I can claim it.
