### ISSUE TITLE
web skia tests hitting skia gold upload failures

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#124864]
For example here: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Engine%20Drone/717958/overview
```
stderr: Error running command: ''invalid test config: field "gitHash", "commit_id", or "change_list_id" must be set.. At jsonio.go:153 goldclient.go:314 goldclient.go:277 cmd_imgtest.go:363 cmd_imgtest.go:294 command.go:860 command.go:974 command.go:902 command.go:895 main.go:54 proc.go:255 asm_amd64.s:1581''
```

**Comment by zanderso** [comment]
cc @eyebrowsoffire @mdebbar

**Comment by yjbanov** [comment]
Looks serious, tentatively making it a P1. Also assigning to @mdebbar who has a PR out with a potential fix.

**Comment by mdebbar** [comment]
@zanderso or @chinmaygarde (the current engine sheriff) have you seen any occurrence of this failure since Friday 04/14? (that's when https://github.com/flutter/engine/pull/41207 landed).

**Comment by zanderso** [comment]
@eyebrowsoffire was the gardener on Friday and Monday, but I suspect if this was still happening it was probably masked by the bot_update timeouts that were happening in that timeframe.

**Comment by mdebbar** [comment]
Since I haven't heard any new reports in the last 2 weeks, I'm going to assume that this was fixed by the PR. Please feel free to reopen if you see this failure again.
