### ISSUE TITLE
[Impeller] Enable debug checker-boarding options for offscreen rendered layers.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#124819]
Today, we allow developers to enable debug checker-boarding of offscreen rendered layers as well raster cached images. Impeller will not support the raster cache but it needs to replicate offscreen rendered layer contents (the so called "save layered" contents).

Today, this checker-boarding is implemented in flow via Skia APIs directly (which is also why it doesn't work with Impeller since it bypasses the display list). But with all the work to collapse and elide render passes, it makes sense to have a context or render pass option that makes Impeller checkerboard contents that were actually rendered via a separate render pass.

**Comment by chinmaygarde** [comment]
cc @flar @bdero @jonahwilliams

**Comment by bdero** [comment]
There's some code that renders a checkerboard here which looks almost backend agnostic (just needs an Impeller-backed DlImage), but tracing through the usage it looks like maybe it only ends up getting used for backdrop filters?: https://github.com/flutter/engine/blob/main/flow/paint_utils.cc

**Comment by chinmaygarde** [comment]
I don't think it is consistently used. And it would be for it to be accurately implemented in flow if there are Impeller internal optimizations.

**Comment by chinmaygarde** [comment]
Fixed in https://github.com/flutter/engine/pull/41199 by @bdero
