### ISSUE TITLE
[CP] [Impeller] Check coverage after screen clip

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#124813]
### issue_link

https://github.com/flutter/flutter/issues/124658

### Commit Hash

https://github.com/flutter/engine/commit/9b72a5ddf17ee55332d4743874d322f55c87720a

### Target

beta

### pr_link

https://github.com/flutter/engine/pull/41167

### Impacted Users

Impeller users.

### Impact Description

When rendering tiny things in SaveLayers (< 1 pixel in size), the texture size rounds down to be zero size and we end up failing to render the frame. The app doesn't crash, but the screen freezes. This bug has been lurking in the Impeller codebase for a while, but recently got introduced in a loud way with the cupertino date picker.

### Workaround

No workarounds.

### Risk

low

### Test Coverage

yes

### Validation Steps

There are a couple of easy ways to verify this fix works:
1. Run the `AiksTest.CanRenderTinyOverlappingSubpasses` playground, which will crash instantly if the failure is present -- and display green if fixed: `autoninja -C ../out/host_debug_unopt/ -j 1000 flutter/impeller:impeller_unittests && ../out/host_debug_unopt/impeller_unittests --timeout=0 --gtest_filter="Play/AiksTest.CanRenderTinyOverlappingSubpasses/Metal" --enable_playground`
2. Run this test app and press the "CLICK ME" button to open the cupertino date picker -- if the screen freezes/nothing happens, the issue is present: https://github.com/flutter/flutter/issues/124658#issuecomment-1505540285

**Comment by bdero** [comment]
cc @zanderso @jonahwilliams

**Comment by zanderso** [comment]
CP LGTM

**Comment by jonahwilliams** [comment]
LGTM
