### ISSUE TITLE
Video is stuck

### ISSUE THREAD

**Issue by GaoWhitebird** [flutter/flutter#124804]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I am using video player for the splash video

### Expected results

App should play video when it's starting every time.

### Actual results

It is working at the first but sometimes, video is stuck and not playing.

### Code sample

<details><summary>Code sample</summary>

```dart
videoController = VideoPlayerController.asset('assets/video/splash_video.mp4');
    videoController.initialize().then((_) {
        setState(() {
          videoController.play();  
        });
      });
    videoController.addListener(() {
      if(videoController.value.position == videoController.value.duration) {
        setState(() {
        });
      }
    });
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.7.9, on Microsoft Windows [Version 10.0.19044.2846], locale en-US)
This is taking an unexpectedly long time...[√] Windows Version (Installed version of Windows is version 10 or higher)
Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[!] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.24)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[√] Android Studio (version 3.6)
[√] Android Studio (version 2022.1)
[√] VS Code (version 1.77.2)
[√] Connected device (4 available)
[√] HTTP Host Availability
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @GaoWhitebird 
Is the behavior occuring only while using the specific video you are using ? If so, can you provide us the video file or make a repo that we can clone and verify ?
Can you try the same using [plugin example](https://github.com/flutter/packages/tree/main/packages/video_player/video_player/example) and see if the behavior persists or not ?

**Comment by GaoWhitebird** [comment]
This is the video what I am using as assets.

https://we.tl/t-BGOV8Z2NY9

**Comment by darshankawar** [comment]
@GaoWhitebird 
I used the video you shared, in plugin example and ran on iOS simulator which played properly as shown below:


https://user-images.githubusercontent.com/67046386/232039482-b3789c51-0944-4b24-9698-04989de5e6f0.mov
