### ISSUE TITLE
[CP] (Engine) fix background crash when FlutterViewController is destroyed after engine destroyed context

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#124811]
### issue_link

https://github.com/flutter/flutter/issues/98656, https://github.com/flutter/flutter/issues/123776

### Commit Hash

6641c74a91afe8c8d5e3300e15e555cdfee140a1

### Target

beta

### pr_link

https://github.com/flutter/engine/pull/41166

### Impacted Users

iOS Apps that has custom Objective-C or Swift code to manage the life cycle of the Flutter engine.

### Impact Description

Production iOS App crashes in the background. It only crashes when headless mode is enabled and app destroys the engine context before dealloc the FlutterViewController.

### Workaround

No

### Risk

low

### Test Coverage

yes

### Validation Steps

testing/scenario_app/ios/Scenarios/ScenariosTests/FlutterEngineTest.m::testReleaseViewControllerAfterDestroyContextInHeadlessMode covers the scenario. Run the test without the fix will crash.

**Comment by CaseyHillers** [comment]
@cyanglaz as FYI, to make it into next week's hotfix this will need an approval by Monday

**Comment by jmagman** [comment]
I think this is a good one to hotfix, I approve 🙂
