### ISSUE TITLE
Build unittests on mac arm64

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#124840]
Today, because we set the `host_cpu` to x64, unittests don't get built for e.g. `host_debug_unopt_arm64` on macOS.

If you override the gn arguments (`enable_unittests = true`), the tests build fine. On my machine, they mostly seem to run fine as well. However, in a few attempts on CI, I saw some failures. 

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8783970492851834417/+/u/test:_Host_Tests_for_host_debug_unopt_arm64/stdout saw a failure in `FlutterMutatorViewTest.TransformedFrameIsCorrect`. 

`EmbedderTest.CompositorMustBeAbleToRenderKnownSceneWithSoftwareCompositor` also fails due to golden byte differences: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8783974394687752593/+/u/test:_Host_Tests_for_host_debug_unopt_arm64/stdout

The golden test likely either needs to be skipped on one platform or have an updated golden byte (or, even better, use SkiaGold and make sure that the platform details are added in such a way that we end up with a golden for each platform).

/cc @jmagman @cyanglaz @cbracken

**Comment by cbracken** [comment]
They'll build today if you use --force-mac-arm64. It's pretty straightforward to auto build them for Mac cross-compiles too though, and probably makes sense to do so given we know that an arm64-native goma toolchain isn't forthcoming.

I'll put together a quick patch.

**Comment by cbracken** [comment]
Looks like the issue with `FlutterMutatorViewTest.TransformedFrameIsCorrect` is a floating point diff in the 15th decimal place of the m41 element of the layer's sublayerTransform CATransform3D. We probably shouldn't be doing exact floating point comparisons. I can bang up a utility function with a precision.

**Comment by cbracken** [comment]
Alright - we now build with unit tests enabled by default and I've landed a fix for `FlutterMutatorViewTest.TransformedFrameIsCorrect`. 

Will take a look at `EmbedderTest.CompositorMustBeAbleToRenderKnownSceneWithSoftwareCompositor`, then once that's fixed we can run the tests on arm64 builds (on arm64 hosts only) in luci.

**Comment by jonahwilliams** [comment]
Closing as this has been fixed
