### ISSUE TITLE
The dashboard is hanging instead of returning empty list for branches without results

### ISSUE THREAD

**Issue by ricardoamador** [flutter/flutter#124874]
The dashboard is not loading for any branch other than the main/master branches in the supported repositories. It is throwing and error for element not found and just displays the loading icon:

![image](https://user-images.githubusercontent.com/32242716/232116805-175858ef-74dc-43be-bdc6-ae8081a5057c.png)

**Comment by ricardoamador** [comment]
This is already a known issue.

**Comment by yusuf-goog** [comment]
@ricardoamador does this issue need an owner, or are you working on this.

**Comment by yusuf-goog** [comment]
We do not expect branches to ever not have any results. So there might be another underlying issue here as well.

**Comment by ricardoamador** [comment]
This is not an issue as we no longer display an other branches other than the default in the dashboard. Will reopen if this changes.
