### ISSUE TITLE
ToggleButtons -> SegmentedButtons needs migration guide and docs

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#124884]
Follow up to https://github.com/flutter/flutter/issues/103529

This is a rare and unfortunate case where we have created a new widget to replace an old one. This type of migration is most painful for developers, so we should provide better help.

Dart fix is not capable of helping here.

ToggleButtons is styled for M2 spec.
SegmentedButtons is style for M3 and the intended replacement for ToggleButtons.

To resolve this issue we should do these things:

- [ ] Document on useMaterial3 that it does not apply to ToggleButtons
- [ ] Document on ToggleButtons that SegmentedButtons are the M3 coutnerpart and replacement.
- [ ] Create a migration guide for https://docs.flutter.dev/release/breaking-changes
- [ ] Send a message to flutter-announce mentioning this and including a link to the migration guide
- [ ] (Eventually) deprecate ToggleButtons
  - This is not clear yet, are we going to maintain M2 and M3 spec after useMaterial3 is on by default?

**Comment by Piinks** [comment]
Related: 
- #124885 
- #124887

**Comment by HansMuller** [comment]
We don't plan to deprecate or remove the M2 style ToggleButtons component. Applications can choose to use the M3 SegmentedButtons component and we would recommend doing so in new `useMaterial3: true` applications.  Migrating existing code from ToggleButtons to SegmentedButtons is optional.

**Comment by TahaTesser** [comment]
@HansMuller 
This would also be similar to the `Drawer` API update?

**Comment by HansMuller** [comment]
Yes, it's roughly the same message.
