### ISSUE TITLE
[CP][ci.yaml] Disable packaging_test on release candidates

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#124815]
### issue_link

None

### Commit Hash

b1f8d5df647894920fb5d1773df1c53b038c09fc

### Target

beta

### pr_link

https://github.com/flutter/flutter/pull/124814

### Impacted Users

Release team

### Impact Description

These checks will fail on the release branch, but they're not expected to run in the first place. This causes unnecessary noise to be added to the release infra.

### Workaround

Could ignore these tests

### Risk

low

### Test Coverage

yes

**Comment by CaseyHillers** [comment]
@XilaiZhang can you review this CP request, and `cp: approved` if it makes sense to you.

**Comment by XilaiZhang** [comment]
sure approved. just for my learning purposes, would disabling packaging test fix https://github.com/flutter/flutter/issues/124708?

**Comment by XilaiZhang** [comment]
Ahh i see, there are now moved to tool proxy, approved!

**Comment by CaseyHillers** [comment]
Closing as this was merged in, and is only an infra change.
