### ISSUE TITLE
AppLifecycleState.detached is not working at least in real devices!!!

### ISSUE THREAD

**Issue by lenzreinhard** [flutter/flutter#124945]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Implemente a method in the state:

@override
  void didChangeAppLifecycleState(AppLifecycleState state) async {
    super.didChangeAppLifecycleState(state);
    print(state);
    switch (state) {
      case AppLifecycleState.detached:
        {
         print("Called method detached!")
          break;
        }
      case AppLifecycleState.inactive:
        break;
      case AppLifecycleState.resumed:
        break;
      case AppLifecycleState.paused:
        break;
    }
  }

The output doesn't show anything when the app was suddenly closed.

Please review it and send me a feedback, thank you! 

### Expected results

I/flutter (25327): AppLifecycleState.inactive
I/flutter (25327): AppLifecycleState.detached
I/flutter (25327): AppLifecycleState.stop

### Actual results

I/flutter (25327): AppLifecycleState.inactive
I/flutter (25327): AppLifecycleState.stop

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Can you please share a complete sample code and more detailed `Steps to reproduce` the issue? 

>The output doesn't show anything when the app was suddenly closed.

Please be more specific on this case. How to reproduce this case in advance? 

Thank you!

**Comment by lenzreinhard** [comment]
Well, to reproduce this error in the main class add the code that I've sent you and in debug mode try to swipe up the app (force to close without pressing the back button), that on android device connected....and then you will se that the detached lifecycle didn't get hit.

In other words the app lifecycle detached isn't working.


Lenz.

________________________________

**Comment by huycozy** [comment]
@lenzreinhard 
As described in [AppLifecycleState](https://api.flutter.dev/flutter/dart-ui/AppLifecycleState.html) documentation, this state is representing when the application is still hosted on a flutter engine but is detached from any host views.

This state will be detected when pressing Back button. Also, this is the limitation of platforms (please see https://github.com/flutter/flutter/issues/57594#issuecomment-1231965622) and I think there is no reliable approach to achieve this (I'm assuming you're trying to implement something on your app in this case).

Closing this as it is intentional behavior.
