### ISSUE TITLE
Hybrid composition makes app crash on startup

### ISSUE THREAD

**Issue by TheCarpetMerchant** [flutter/flutter#124918]
[hybrid_comp_test.zip](https://github.com/flutter/flutter/files/11239536/hybrid_comp_test.zip)

This project crashes without any logs.
I have been trying to work with Hybrid composition, but I get the `updateAcquireFence: Did not find frame.` error on every frame.
So I've tried making a minimal reproduction, but cannot get it to work.

Stackoverflow answers say to enable clear text traffic in the manifest (for some reason), but this did nothing for the `updateAcquireFence` error.

**Comment by darshankawar** [comment]
Thanks for the report @TheCarpetMerchant 
For the error you are getting `updateAcquireFence: Did not find frame`, this seems to be an issue using hybrid composition using platform-views in general and there have been issues reported using packages such as webview_flutter which uses the platform-views in the background. See this issue for example: https://github.com/flutter/flutter/issues/106999 and this comment which states the crash occurs using VD or hybrid composition: https://github.com/flutter/flutter/issues/106999#issuecomment-1173483917

See if it helps in further reference for your use case.

**Comment by TheCarpetMerchant** [comment]
My Platform view isn't wrapped in a scrollable, but the Android TextView has scrolling behavior.

**Comment by darshankawar** [comment]
I cloned the repo and ran it on Android emulator but getting below error upon compiling:

```
E/AndroidRuntime(13309): Process: com.example.hybrid_comp_test, PID: 13309
E/AndroidRuntime(13309): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.example.hybrid_comp_test/com.example.hybrid_comp_test.hybrid_comp_test.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.example.hybrid_comp_test.hybrid_comp_test.MainActivity" on path: DexPathList[[zip file "/data/app/~~9kIClf48nRqceFIdEc71cg==/com.example.hybrid_comp_test-jrlZFBAz21sXNeJJkCg_Eg==/base.apk"],nativeLibraryDirectories=[/data/app/~~9kIClf48nRqceFIdEc71cg==/com.example.hybrid_comp_test-jrlZFBAz21sXNeJJkCg_Eg==/lib/x86, /data/app/~~9kIClf48nRqceFIdEc71cg==/com.example.hybrid_comp_test-jrlZFBAz21sXNeJJkCg_Eg==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
E/AndroidRuntime(13309): 	at android.app.ActivityThread.p
```
Can you provide exact steps to replicate ?

**Comment by TheCarpetMerchant** [comment]
I have no idea how you got this error. I just downloaded the zip provided and compiled the project with Flutter 3.7.10 on an Android API 33 emulator. Compilation works, but running the app just crashes without anything in the logcat.

**Comment by darshankawar** [comment]
For some reason I am still getting the same error as I mentioned earlier. Can you run `flutter run -v` and see if you get any meaningful entries pointing to any errors in it ? If so, please share the same here. Also please try on any other emulator / device and see if you get any other logs that can help us to properly analyze the issue.

**Comment by TheCarpetMerchant** [comment]
I've put it in a repo, please try cloning and running it : https://github.com/TheCarpetMerchant/hybrid_comp_test
If you still get this weird error (why would the package name get re-written ?), please just give this issue to someone else.

**Comment by darshankawar** [comment]
Thanks for the repo. I cloned and ran it on Android emulator which built properly and seeing blank screen as below. It didn't crash for me.

<img width="228" alt="Screenshot 2023-04-25 at 11 35 53 AM" src="https://user-images.githubusercontent.com/67046386/234188337-11869e61-0444-4e0e-b131-b260bcc38d08.png">

```
Changed 10 dependencies!
Using hardware rendering with device Android SDK built for x86. If you notice
graphics artifacts, consider enabling software rendering with
"--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Upgrading build.gradle
Running Gradle task 'assembleDebug'...                             69.3s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app-debug.apk...        1,091ms


```

**Comment by TheCarpetMerchant** [comment]
It shouldn't be a black screen. If you look into the `NativeView.kt`, it should show "Text", in an Android TextView.

I just ran it again and it crashed (The flutter logo shows up and then the app closes immediately, without any message in the logcat). Here's flutter doctor for comparison :
<details>
<summary>Flutter doctor</summary>
[√] Flutter (Channel stable, 3.7.10, on Microsoft Windows [Version 10.0.19044.2846], locale fr-BE)
    • Flutter version 3.7.10 on channel stable at D:\Code\Flutter\sdk\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b12645012 (3 weeks ago), 2023-04-03 17:46:48 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.77.3)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.44.0

[√] VS Code, 64-bit edition (version 1.77.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.44.0

[√] Connected device (1 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64 • Android 13 (API 33) (emulator)

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
</details>

**Comment by darshankawar** [comment]
@TheCarpetMerchant Thanks for the further update. One of my team member verified this issue at his end and he's also getting same error as I posted earlier: https://github.com/flutter/flutter/issues/124918#issuecomment-1511242035
Would be good if you could get some logs from the logcat so that it'll help us to make this issue actionable.

**Comment by TheCarpetMerchant** [comment]
Okay, after googling about verbose logcat I caught it. It's just the package name that was incorrect, for some reason. It's weird that it manages to compile, and I guess it wasn't showing up in the basic log because the error occurs before Flutter runs.
Kinda annoying, but now I know to pay attention to these possibilities in the future. Thanks for your help !
