### ISSUE TITLE
Handle plurals correctly in MaterialLocalizations

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#12495]
Per _nameToPluralValue in GlobalMaterialLocalizations (see https://github.com/flutter/flutter/pull/12410)

The rules for mapping from an integer value to "one" or "two" etc. are locale specific and an additional "few" category is needed. See http://cldr.unicode.org/index/cldr-spec/plural-rules

The necessary information is in the `intl` package although it may not be exposed as a public API at the moment.

**Comment by Hixie** [comment]
@HansMuller I looked at that URL but I couldn't figure out how to implement "few" from this.

**Comment by TahaTesser** [comment]
Hi @HansMuller 
Is this issue valid?
https://api.flutter.dev/flutter/intl/Intl/pluralLogic.html
Thank you

**Comment by YeungKC** [comment]
@TahaTesser 

I also think this issue is invalid.

**Comment by TahaTesser** [comment]
Hi @YeungKC
Thanks

Closing
If anyone disagree, please write in the comments and I will reopen it.
Thank you
