### ISSUE TITLE
Xcode Cloud build fails in flutter app

### ISSUE THREAD

**Issue by rajapriyapt** [flutter/flutter#124960]
I'm using flutter and integrated the repository to Xcode cloud to compile the app and everything is connected properly. 
While running the build, I get the below error and build fails always. I have followed the below steps to resolve the issue and nothing seems to work

- Pod Deintegrate
- Pod install
- Clean derived data from Xcode
- Restarted Xcode

`unable to open configuration settings file Pods-Runner.release.xcconfig:1`
![ff7763c2-9867-4fe6-bc58-7421d0fff1b2](https://user-images.githubusercontent.com/3005476/232416441-5b426a5d-c499-49f2-8fd1-0c3a36e60829.png)

**Comment by huycozy** [comment]
Hi @rajapriyapt 
This seems to be related to your configuration with XCode. Can you confirm if it only reproduces with a newly created  Flutter project?  Also, are you following this [guideline](https://docs.flutter.dev/deployment/cd#xcode-cloud)?
Please provide the output of `flutter doctor -v` as well.

Some SO answers that may help you to trace the issue:

- https://stackoverflow.com/questions/74134200/xcode-cloud-unable-to-open-configuration-settings-file
- https://stackoverflow.com/questions/73581450/xcode-cloud-build-error-unable-to-open-target-file
- https://stackoverflow.com/questions/74554127/xcode-unable-to-open-configuration-settings-file

**Comment by rajapriyapt** [comment]
@huycozy Latest screenshot of the failed build
![fither](https://user-images.githubusercontent.com/3005476/232500836-2d5751c0-1a88-48d8-8815-dfe7aa7dcd53.png)

**Comment by huycozy** [comment]
>have added all the 3 custom ci scripts as per the doc.

Which custom ci scripts are you mentioning?
Please try using [post-clone-script](https://docs.flutter.dev/deployment/cd#post-clone-script) on a new Flutter project to see if you can reproduce the issue. If the issue doesn't happen, it may be caused by your additional configuration. 

You may also retry on the latest Flutter channels to see if the issue persists or not.
