### ISSUE TITLE
Webview POST Load request does ignore headers.

### ISSUE THREAD

**Issue by thedevtech** [flutter/flutter#124998]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

use loadRequest with method: LoadRequestMethod.post, and headers.

Headers are just ignored. Se the request in your sever side. It looses headers. May be ACCEPT VERSION is replaced, but the others are lost.

### Expected results

Expect to see all headers in server.

### Actual results

Header are just ignored in low level method calls, and therefore are not sent to server.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @thedevtech,

Please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with steps to reproduce so that we can investigate this issue. 

What platform(s) are you experiencing this issue on? Can you also capture the requests to make sure that the headers are not being sent?

Thank you

**Comment by thedevtech** [comment]
Hi Daniel, I ll try to do that.

BUT the issue is very very easy to check in Android. The 'headers'
parameter is just ignored and not passed in.

best regards.





Em ter., 18 de abr. de 2023 às 03:52, Daniel Agbemava <
***@***.***> escreveu:

**Comment by danagbemava-nc** [comment]
Hi @thedevtech, please also provide the version of `webview_flutter` & `webview_flutter_android`(you can find this in your pubspec.lock) that you're using. 

Thank you

**Comment by thedevtech** [comment]
hi Daniel,

  webview_flutter:
    dependency: "direct main"
    description:
      name: webview_flutter
      sha256:
"47663d51a9061451aa3880a214ee9a65dcbb933b77bc44388e194279ab3ccaf6"
      url: "https://pub.dev"
    source: hosted
    version: "4.0.7"
  webview_flutter_android:
    dependency: transitive
    description:
      name: webview_flutter_android
      sha256:
da98c8cdaebea4cf89481853f37ca93ccc8d31fc386f5b3c928aea3b6e83268c
      url: "https://pub.dev"
    source: hosted
    version: "3.3.0"
  webview_flutter_platform_interface:
    dependency: transitive
    description:
      name: webview_flutter_platform_interface
      sha256:
"8b2262dda5d26eabc600a7282a8c16a9473a0c765526afb0ffc33eef912f7968"
      url: "https://pub.dev"
    source: hosted
    version: "2.0.1"
  webview_flutter_wkwebview:
    dependency: transitive
    description:
      name: webview_flutter_wkwebview
      sha256:
dcd9ad0ef0f608f399d7a54d0b289597385e59a89f04983a672b9348faddfd98
      url: "https://pub.dev"
    source: hosted
    version: "3.1.0"

Thanks very much,

Em qua., 19 de abr. de 2023 às 03:25, Daniel Agbemava <
***@***.***> escreveu:

**Comment by thedevtech** [comment]
Thanks very much, now it is clear ... 

Setting custom headers on POST requests 
Currently, setting custom headers when making a post request with the WebViewController's loadRequest method is not supported on Android. If you require this functionality, a workaround is to make the request manually, and then load the response data using loadHtmlString instead.
