### ISSUE TITLE
flutter doesn't recognize Chrome installed through flatpak (linux)

### ISSUE THREAD

**Issue by radeksvarz** [flutter/flutter#124978]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Using Ubuntu (or derivatives like Pop OS)
1. Install Chrome using Flatpak 
2. install flutter SDK on Linux (Ubuntu) - stable version 3.3
3. run `flutter doctor -v`

Results in:

```
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
```

4. Set CHROME_EXECUTABLE to Flatpak Chrome:
`export CHROME_EXECUTABLE="~/.local/share/flatpak/exports/bin/com.google.Chrome"`

Results in:
```
[✗] Chrome - develop for the web (Cannot find Chrome executable at ~/.local/share/flatpak/exports/bin/com.google.Chrome)
    ! ~/.local/share/flatpak/exports/bin/com.google.Chrome is not executable.
```

### Actual results

Flutter does not recognise the flatpak's Chrome execution script as the executable

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console
:~$ flutter doctor -v
[✓] Flutter (Channel stable, 3.3.10, on Pop!_OS 22.04 LTS 6.2.6-76060206-generic, locale en_DK.UTF-8)
    • Flutter version 3.3.10 on channel stable at /media/xxx/optane/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (4 months ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Chrome - develop for the web (Cannot find Chrome executable at ~/.local/share/flatpak/exports/bin/com.google.Chrome)
    ! ~/.local/share/flatpak/exports/bin/com.google.Chrome is not executable.

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Pop!_OS 22.04 LTS 6.2.6-76060206-generic

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.

```

</details>

**Comment by huycozy** [comment]
Hi @radeksvarz 
I think there is a change related to flatpak application path (I don't often use flatpak  so I'm not sure about this) that may cause Chrome executable file does not exist in `.local/share/flatpak`.

But after digging this a bit, I see the workable path is: `/var/lib/flatpak/app/com.google.Chrome/x86_64/stable/active/export/bin/com.google.Chrome`. And after setting `CHROME_EXECUTABLE` to that path, flutter doctor can recognize and run well:

```
[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /var/lib/flatpak/app/com.google.Chrome/x86_64/stable/active/export/bin/com.google.Chrome
```

Please try using that path to see if it works.

**Comment by radeksvarz** [comment]
Hi @huycozy 

I do not think the issue is in the path itself, but rather in the fact, that flatpak's file is the bash script.

Anyway PopOS's flatpak does not have anything in /var/lib/flatpak/app
it is rather created in the .local folder. I found a similar path to yours: 

`export CHROME_EXECUTABLE="~/.local/share/flatpak/app/com.google.Chrome/x86_64/stable/active/export/bin/com.google.Chrome"` which is for the Chrome flatpak start script:

```
-rwxr-xr-x 1 abc abc   89 Apr 22 06:12 com.google.Chrome*
```

This is the output:
```
[✗] Chrome - develop for the web (Cannot find Chrome executable at
    ~/.local/share/flatpak/app/com.google.Chrome/x86_64/stable/active/export/bin/com.google.C
    hrome)
    !

      ~/.local/share/flatpak/app/com.google.Chrome/x86_64/stable/active/export/bin/com.google
      .Chrome is not executable.
```

**Comment by huycozy** [comment]
Can you please try checking this on the latest Flutter stable and master channels to see if it works or not?

**Comment by radeksvarz** [comment]
I tested on the `[✓] Flutter (Channel stable, 3.7.12, on Pop!_OS 22.04 LTS 6.2.6-76060206-generic, locale
    en_DK.UTF-8)`

the outcome is the same.

But I found the workaround - to use the absolute path instead of ~ related.

This I can finally confirm to work both with 3.7.12 and 3.3.10.

**Comment by huycozy** [comment]
Glad you found a workaround. I think it's OS specific issue and need to customize the corresponding environment for it to work. So, is it safe to close the issue?

**Comment by radeksvarz** [comment]
I also found it working using $HOME instead of tilde.

Not sure whether it is OS only specific, though.

**Comment by darshankawar** [comment]
Good to know you solved it using absolute path and `$HOME`, so I'll go ahead and close as resolved. If you disagree, write in comments and I'll reopen it.
