### ISSUE TITLE
flutter drive --write-sksl-on-exit results in No data was received

### ISSUE THREAD

**Issue by gslender** [flutter/flutter#124934]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Flutter project using stable 3.7.11 has a flutter drive integration test that writes sksl data when exiting, but under the beta / 3.10 upcoming release it no longer works.

Fairly complex to setup a standalone test, but change from stable to beta results in the output of "No data was received" and yet everything else has remained the same.

### Expected results

A valid sksl file is produced and written to disk after tests were successfully run on a physcial device.

### Actual results

No data was received. To ensure SkSL data can be generated use a physical device then:
  1. Pass "--cache-sksl" as an argument to flutter run.
  2. Interact with the application to force shaders to be compiled.

### Code sample

There is not a small code sample possible to demonstrate this problem - I'm hoping the Flutter team have a test example flutter drive suite that they can confirm is working as previously under 3.7.x

### Logs

Running with --verbose didn't produce any further details as to why the sksl data wasn't generated and written

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 3.10.0-1.1.pre, on macOS 13.2.1 22D68 darwin-arm64, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.77.3)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by gslender** [comment]
This is the full command line that is being run that under flutter v3.7.x works everytime and produce sksl shader output

```
flutter drive --profile --cache-sksl --write-sksl-on-exit flutter_01.sksl.json --target=test_driver/main.dart
```

Even added the --purge-persistent-cache and it made zero difference.

**Comment by gslender** [comment]
Equally, just using this also produces no SkSL data when pressing 'M' key as you previously were able to - seems like a bug

```
flutter run --profile --cache-sksl --purge-persistent-cache
```

**Comment by gslender** [comment]
Could be releated #100779

**Comment by gslender** [comment]
Also tried master and got the same result

```
Flutter 3.10.0-6.0.pre.27 • channel master • https://github.com/flutter/flutter.git
Framework • revision 2d57261069 (11 hours ago) • 2023-04-15 20:34:24 -0400
Engine • revision da0805a9cf
Tools • Dart 3.1.0 (build 3.1.0-11.0.dev) • DevTools 2.23.1
```

**Comment by gslender** [comment]
FYI @cbracken

**Comment by huycozy** [comment]
Hi @gslender 
Which target platform are you seeing this issue on? If it's Android, have you modified MainActivity class? Please check [this](https://github.com/flutter/flutter/issues/105580#issuecomment-1211674634) to see if it can help to solve this.

For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Please try to provide such a sample. Thanks!

**Comment by gslender** [comment]
This is on Apple Mac M1 and with Flutter's basic app - if you just create the standard basic increment counter app and then try the flutter run --profile --cache-sksl --purge-persistent-cache using the 'M' key to produce the SkSL data to be written, it will show you that it fails (in the beta and master channels).

**Comment by gslender** [comment]
Sorry... and I'm using a iPhone that is connected to the M1 as the build target. Obviously you need to use a hardware device to run the shaders from.

**Comment by huycozy** [comment]
Thanks for your response, I can see this issue on a new Flutter project. 

- It only happens on iOS whilst it works as expected on Android. 
- The issue is not reproducible on **stable**, but on **beta** and **master** channels

<details>
<summary>flutter doctor -v (stable, beta, master)</summary>

```bash
[✓] Flutter (Channel stable, 3.7.11, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.7.11 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f72efea43c (31 hours ago), 2023-04-11 11:57:21 -0700
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 112.0.5615.49

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.10.0-6.0.pre.29, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.10.0-6.0.pre.29 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 858d4ff634 (6 hours ago), 2023-04-16 23:21:38 -0400
    • Engine revision 360ca05311
    • Dart version 3.1.0 (build 3.1.0-11.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D                         • android-arm64  • Android 11 (API 30)
    • iPhone (mobile)  • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.7.2 19H218
    • macOS (desktop)  • macos                                    • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome                                   • web-javascript • Google Chrome 112.0.5615.121

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

```bash
[!] Flutter (Channel beta, 3.10.0-1.1.pre, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.10.0-1.1.pre on channel beta at /Users/huynq/Documents/GitHub/flutter_beta
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_beta. Consider adding /Users/huynq/Documents/GitHub/flutter_beta/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_beta. Consider adding /Users/huynq/Documents/GitHub/flutter_beta/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ecdb7841df (5 days ago), 2023-04-11 20:47:40 -0700
    • Engine revision 870e640e7e
    • Dart version 3.0.0 (build 3.0.0-417.1.beta)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 112.0.5615.121

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by chinmaygarde** [comment]
3.10 has Impeller enabled by default on iOS. SKSL training is unnecessary since all shaders are precompiled with Impeller and there is no runtime shader compilation. Packaging SKSL should be a no-op but not recommended since it will only add to the binary size.

Is there a crash or hang? Or is it a case of incorrect feedback that SKSL training is unnecessary with Impeller?

**Comment by gslender** [comment]
No crash. Just incorrect feedback and now creates concern that you're jumping the gun on impeller given that it's barely finished on iOS and you've not got it finished on Android and now we have a split deployment situation that previously we didn't have.

Any chance decisions like that can be optional (like it was) and the developer can decide to use or not use impeller??

**Comment by chinmaygarde** [comment]
Impeller on iOS has been in preview in a stable branch and [all known ship blockers reported by previewers have been fixed](https://github.com/flutter/flutter/milestone/77?closed=1). Applications are shipping with it turned on already. The decision was to get one platform and backend over the finish line first so there aren't multiple half baked platforms with a prolonged preview period on each. The Android preview is next with the desktop platforms to follow.

Having said that, its perfectly fine and understandable to be skittish about a change of this nature. If you find urgent issues with Impeller or feel more comfortable not using the backend at all, you can opt-out of it by setting the [`FLTEnableImpeller` plist](https://docs.flutter.dev/perf/impeller#ios) entry to be false. [Its just that the default has been flipped](FLTEnableImpeller) with this beta.

I'd like to understand if a workflow is broken though. Training runs with Impeller turned on should give you no SKSL data since its not used. With the old backend, you should get data. Packaging data but using Impeller should be benign if wasteful and should only happen if you used an old version of the application to gather training data (vs. doing it on CI). Shader captures on Android and iOS were different so the training runs had to be separate too already. When Android gets to preview, the migration should be similar. So I am not sure I understand how the switch introduces a split deployment.

Even if you decide to opt-out of using Impeller, I urge you to report any issues you see with that backend enabled so we may continue to improve it. We do plan on retiring the old backend and it is no longer receiving any work. The when depends on feedback first from previewers and then when its on by default. So while the opt-out works now, it will stop working in the future.

**Comment by gslender** [comment]
Understood. I don't like where the Flutter team are going, which is constantly evolving iOS and leaving Android, leaving web and desktop even further behind. The original promise of a single framework that makes building apps across many platforms is splintered. This, like many differences across the framework, is becoming increasingly a burden to manage and makes developers reconsider if perhaps other competing frameworks are worth looking into - it's not ideal that you couldn't just wait until impellers isn't evolved adequately across all the supported platforms.

**Comment by chinmaygarde** [comment]
Noted. And you're right that Impeller being available everywhere all at once would have been ideal. The scope of the update makes this interesting to pull off. Adding more platforms with a hard transition greatly increases the number of things we didn't anticipate going wrong. We are constantly asking ourselves how best to affect this so we're not, in your words, "jumping the gun". Being deliberate about getting one platform right™ at a time seemed more manageable and the feedback received for one platform helps the rest. But its good to know that there is at least a cohort out there that is more comfortable waiting for all updates to be ready everywhere with a single "rip the bandaid" event.

Getting back to the issue reported here, writing SKSL on exit returning no SKSL when it is not used or needed for training seems like intended behavior to me. So, again, does this break an existing workflow? There is no change in API and, if anything, not training SKSL is one less thing for the developer to do.

**Comment by gslender** [comment]
Appreciate your response and acknowledging the problems from our point of view. We support 6 platforms using Flutter, and the distance between features supported on iOS vs Windows Desktop grow deeper each time something like this occurs. All a bit annoying, and certainly would prefer that the tail (Windows/macOS Desktop) has more focus than the head does at times.

As for your question re breaking workflow - of course it did, but we made adjustments and worked around it - our workflow involved automated testing on devices, producing SKSL data and then building the apps with that new SKSL data. Having it not be produced without explanation (as it was) came as a surprise and unexpected change that wasn't required everywhere. When you create workflows from a single codebase with an aim to reduce difference, when someone inserts differences it can be a little frustrating to see as being a positive thing™

We do appreciate the team's work on Flutter - but would like the tail to get a little more attention so as to ensure the benefit of a single framework for all platforms isn't lost amognst the excitement of expanding and extending it.

**Comment by gslender** [comment]
Given this is now expected behaviour and you're not likely to undo this change, and you can simply work around the problem, I'd suggest you close this. Updating the output would be ideal and save a lot of heartache for developers that aren't aware of the expected change.
