### ISSUE TITLE
LUCI should tell which build failed

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#124986]
Sorry if I'm just missing it or we already have an issue filed for this, but AFAICT there's no easy way to tell which of the sub builds here had a problem

<img width="870" alt="Screenshot 2023-04-17 at 11 15 45 AM" src="https://user-images.githubusercontent.com/6343103/232574651-7e965d13-8330-4ca1-8bef-9bac965cba14.png">

**Comment by ricardoamador** [comment]
This ticket duplicates https://github.com/flutter/flutter/issues/123645.
