### ISSUE TITLE
`flutter attach` doesn't respect `--local-engine`

### ISSUE THREAD

**Issue by moffatman** [flutter/flutter#124970]
If I build my app with a local engine, then try to attach with `--local-engine`, the `attach` command will act like it doesn't know anything about my local engine, and exit when it finds some code that depends on my `dart:ui` changes.

I am pretty sure it started here: https://github.com/flutter/flutter/pull/113227, for now I've used a partial revert of the `Artifacts` change in `attach.dart` to use `globals.artifacts` instead of injection and it's working for me again.

cc @Jasguerrero

**Comment by christopherfujino** [comment]
@moffatman thanks for filing this and I'm sorry it took this long to get back to you. However, unfortunately I cannot reproduce this at HEAD. Can you provide exact reproductions steps, such as:

0. engine change you made that should be observable
1. engine targets you built
2. how you built/started your flutter app
3. exact flags you attached with
4. unexpected behavior

**Comment by moffatman** [comment]
@christopherfujino Thx for looking at it. Maybe it's only an issue with the "special" target I'm using?

0. I think the most important part is engine changes to `dart:ui`. Here I have some changes to text layout, with corresponding use in the framework as well. But without my adjustments to the tool, it fails to sync to the target.
1. The target is `ios_debug`, and I have `host_debug` counterpart built as well.
2. This is using the Apple Silicon `iOSAppOnMac` target. It runs an iOS app unmodified within macOS, I use it for development because it's much faster and more pleasant than a simulator and still supports iOS plugins. I build using `flutter build ios --debug --local-engine ios_debug`, then launch the app by opening `ios/Runner.xcworkspace` in Xcode and running with target "My Mac (Designed for iPad)". This target isn't implemented as a direct `flutter run` target, it only works for attaching.

3 and 4 are shown in the output below
```
callum@Callums-MacBook-Pro ~/C/chan (master)> flutter attach -d designed-for-ipad --app-id com.moffatman.chan -
-local-engine ios_debug
Building flutter tool...
Resolving dependencies... (1.2s)
Got dependencies.
Waiting for a connection from Flutter on Mac Designed for iPad...
../flutter/packages/flutter/lib/src/widgets/widget_span.dart:147:9: Error: Type 'ui.PlaceholderFloating' not
found.
  final ui.PlaceholderFloating floating;
        ^^^^^^^^^^^^^^^^^^^^^^
../flutter/packages/flutter/lib/src/widgets/widget_span.dart:84:24: Error: Undefined name
'PlaceholderFloating'.
    this.floating = ui.PlaceholderFloating.none,
                       ^^^^^^^^^^^^^^^^^^^
../flutter/packages/flutter/lib/src/rendering/editable.dart:2272:33: Error: Member not found: 'stretchUp'.
        ui.PlaceholderAlignment.stretchUp => true,
                                ^^^^^^^^^
../flutter/packages/flutter/lib/src/rendering/paragraph.dart:133:37: Error: Member not found: 'stretchUp'.
            ui.PlaceholderAlignment.stretchUp => null,
                                    ^^^^^^^^^
../flutter/packages/flutter/lib/src/rendering/paragraph.dart:705:33: Error: Member not found: 'stretchUp'.
        ui.PlaceholderAlignment.stretchUp => true,
                                ^^^^^^^^^
../flutter/packages/flutter/lib/src/widgets/widget_span.dart:147:12: Error: 'PlaceholderFloating' isn't a type.
  final ui.PlaceholderFloating floating;
           ^^^^^^^^^^^^^^^^^^^
../flutter/packages/flutter/lib/src/widgets/widget_span.dart:176:7: Error: No named parameter with the name
'floating'.
      floating: floating,
      ^^^^^^^^
../flutter/packages/flutter/lib/src/painting/text_painter.dart:132:31: Error: Member not found: 'stretchUp'.
      ui.PlaceholderAlignment.stretchUp ||
                              ^^^^^^^^^
Syncing files to device Mac Designed for iPad...                   12.9s
```

And my tool change to fix it

```
diff --git a/packages/flutter_tools/lib/executable.dart b/packages/flutter_tools/lib/executable.dart
index 2fb826f17d..b5ecf5a3bc 100644
--- a/packages/flutter_tools/lib/executable.dart
+++ b/packages/flutter_tools/lib/executable.dart
@@ -156,7 +156,6 @@ List<FlutterCommand> generateCommands({
   AssembleCommand(verboseHelp: verboseHelp, buildSystem: globals.buildSystem),
   AttachCommand(
     verboseHelp: verboseHelp,
-    artifacts: globals.artifacts,
     stdio: globals.stdio,
     logger: globals.logger,
     terminal: globals.terminal,
diff --git a/packages/flutter_tools/lib/src/commands/attach.dart b/packages/flutter_tools/lib/src/commands/attach.dart
index 6bd6539181..8dc5257cdb 100644
--- a/packages/flutter_tools/lib/src/commands/attach.dart
+++ b/packages/flutter_tools/lib/src/commands/attach.dart
@@ -23,6 +23,7 @@ import '../daemon.dart';
 import '../device.dart';
 import '../device_port_forwarder.dart';
 import '../fuchsia/fuchsia_device.dart';
+import '../globals.dart' as globals;
 import '../ios/devices.dart';
 import '../ios/simulators.dart';
 import '../macos/macos_ipad_device.dart';
@@ -65,7 +66,6 @@ class AttachCommand extends FlutterCommand {
   AttachCommand({
     bool verboseHelp = false,
     HotRunnerFactory? hotRunnerFactory,
-    required Artifacts? artifacts,
     required Stdio stdio,
     required Logger logger,
     required Terminal terminal,
@@ -73,8 +73,7 @@ class AttachCommand extends FlutterCommand {
     required Platform platform,
     required ProcessInfo processInfo,
     required FileSystem fileSystem,
-  }): _artifacts = artifacts,
-      _hotRunnerFactory = hotRunnerFactory ?? HotRunnerFactory(),
+  }): _hotRunnerFactory = hotRunnerFactory ?? HotRunnerFactory(),
       _stdio = stdio,
       _logger = logger,
       _terminal = terminal,
@@ -145,7 +144,6 @@ class AttachCommand extends FlutterCommand {
   }
 
   final HotRunnerFactory _hotRunnerFactory;
-  final Artifacts? _artifacts;
   final Stdio _stdio;
   final Logger _logger;
   final Terminal _terminal;
@@ -267,7 +265,7 @@ known, it can be explicitly provided to attach via the command-line, e.g.
       throwToolExit('Did not find any valid target devices.');
     }
 
-    final Artifacts? overrideArtifacts = device.artifactOverrides ?? _artifacts;
+    final Artifacts? overrideArtifacts = device.artifactOverrides ?? globals.artifacts;
     await context.run<void>(
       body: () => _attachToDevice(device),
       overrides: <Type, Generator>{
```

**Comment by christopherfujino** [comment]
> @christopherfujino Thx for looking at it. Maybe it's only an issue with the "special" target I'm using?
> 
> 0. I think the most important part is engine changes to `dart:ui`. Here I have some changes to text layout, with corresponding use in the framework as well. But without my adjustments to the tool, it fails to sync to the target.
> 1. The target is `ios_debug`, and I have `host_debug` counterpart built as well.
> 2. This is using the Apple Silicon `iOSAppOnMac` target. It runs an iOS app unmodified within macOS, I use it for development because it's much faster and more pleasant than a simulator and still supports iOS plugins. I build using `flutter build ios --debug --local-engine ios_debug`, then launch the app by opening `ios/Runner.xcworkspace` in Xcode and running with target "My Mac (Designed for iPad)". This target isn't implemented as a direct `flutter run` target, it only works for attaching.
> 
> 3 and 4 are shown in the output below
> 
> ```
> callum@Callums-MacBook-Pro ~/C/chan (master)> flutter attach -d designed-for-ipad --app-id com.moffatman.chan -
> -local-engine ios_debug
> Building flutter tool...
> Resolving dependencies... (1.2s)
> Got dependencies.
> Waiting for a connection from Flutter on Mac Designed for iPad...
> ../flutter/packages/flutter/lib/src/widgets/widget_span.dart:147:9: Error: Type 'ui.PlaceholderFloating' not
> found.
>   final ui.PlaceholderFloating floating;
>         ^^^^^^^^^^^^^^^^^^^^^^
> ../flutter/packages/flutter/lib/src/widgets/widget_span.dart:84:24: Error: Undefined name
> 'PlaceholderFloating'.
>     this.floating = ui.PlaceholderFloating.none,
>                        ^^^^^^^^^^^^^^^^^^^
> ../flutter/packages/flutter/lib/src/rendering/editable.dart:2272:33: Error: Member not found: 'stretchUp'.
>         ui.PlaceholderAlignment.stretchUp => true,
>                                 ^^^^^^^^^
> ../flutter/packages/flutter/lib/src/rendering/paragraph.dart:133:37: Error: Member not found: 'stretchUp'.
>             ui.PlaceholderAlignment.stretchUp => null,
>                                     ^^^^^^^^^
> ../flutter/packages/flutter/lib/src/rendering/paragraph.dart:705:33: Error: Member not found: 'stretchUp'.
>         ui.PlaceholderAlignment.stretchUp => true,
>                                 ^^^^^^^^^
> ../flutter/packages/flutter/lib/src/widgets/widget_span.dart:147:12: Error: 'PlaceholderFloating' isn't a type.
>   final ui.PlaceholderFloating floating;
>            ^^^^^^^^^^^^^^^^^^^
> ../flutter/packages/flutter/lib/src/widgets/widget_span.dart:176:7: Error: No named parameter with the name
> 'floating'.
>       floating: floating,
>       ^^^^^^^^
> ../flutter/packages/flutter/lib/src/painting/text_painter.dart:132:31: Error: Member not found: 'stretchUp'.
>       ui.PlaceholderAlignment.stretchUp ||
>                               ^^^^^^^^^
> Syncing files to device Mac Designed for iPad...                   12.9s
> ```
> 
> And my tool change to fix it
> 
> ```
> diff --git a/packages/flutter_tools/lib/executable.dart b/packages/flutter_tools/lib/executable.dart
> index 2fb826f17d..b5ecf5a3bc 100644
> --- a/packages/flutter_tools/lib/executable.dart
> +++ b/packages/flutter_tools/lib/executable.dart
> @@ -156,7 +156,6 @@ List<FlutterCommand> generateCommands({
>    AssembleCommand(verboseHelp: verboseHelp, buildSystem: globals.buildSystem),
>    AttachCommand(
>      verboseHelp: verboseHelp,
> -    artifacts: globals.artifacts,
>      stdio: globals.stdio,
>      logger: globals.logger,
>      terminal: globals.terminal,
> diff --git a/packages/flutter_tools/lib/src/commands/attach.dart b/packages/flutter_tools/lib/src/commands/attach.dart
> index 6bd6539181..8dc5257cdb 100644
> --- a/packages/flutter_tools/lib/src/commands/attach.dart
> +++ b/packages/flutter_tools/lib/src/commands/attach.dart
> @@ -23,6 +23,7 @@ import '../daemon.dart';
>  import '../device.dart';
>  import '../device_port_forwarder.dart';
>  import '../fuchsia/fuchsia_device.dart';
> +import '../globals.dart' as globals;
>  import '../ios/devices.dart';
>  import '../ios/simulators.dart';
>  import '../macos/macos_ipad_device.dart';
> @@ -65,7 +66,6 @@ class AttachCommand extends FlutterCommand {
>    AttachCommand({
>      bool verboseHelp = false,
>      HotRunnerFactory? hotRunnerFactory,
> -    required Artifacts? artifacts,
>      required Stdio stdio,
>      required Logger logger,
>      required Terminal terminal,
> @@ -73,8 +73,7 @@ class AttachCommand extends FlutterCommand {
>      required Platform platform,
>      required ProcessInfo processInfo,
>      required FileSystem fileSystem,
> -  }): _artifacts = artifacts,
> -      _hotRunnerFactory = hotRunnerFactory ?? HotRunnerFactory(),
> +  }): _hotRunnerFactory = hotRunnerFactory ?? HotRunnerFactory(),
>        _stdio = stdio,
>        _logger = logger,
>        _terminal = terminal,
> @@ -145,7 +144,6 @@ class AttachCommand extends FlutterCommand {
>    }
>  
>    final HotRunnerFactory _hotRunnerFactory;
> -  final Artifacts? _artifacts;
>    final Stdio _stdio;
>    final Logger _logger;
>    final Terminal _terminal;
> @@ -267,7 +265,7 @@ known, it can be explicitly provided to attach via the command-line, e.g.
>        throwToolExit('Did not find any valid target devices.');
>      }
>  
> -    final Artifacts? overrideArtifacts = device.artifactOverrides ?? _artifacts;
> +    final Artifacts? overrideArtifacts = device.artifactOverrides ?? globals.artifacts;
>      await context.run<void>(
>        body: () => _attachToDevice(device),
>        overrides: <Type, Generator>{
> ```

Ok thanks, this is quite a bit different from what I tried, so I'll try this out later this week.

**Comment by christopherfujino** [comment]
Actually, while you're at it, do you think you can give me a minimal reproducible dart:ui diff and flutter app code? Like, it looks like you added a new Dart type and referenced it from your app code?

**Comment by moffatman** [comment]
I added this new enum `PlaceholderFloating` defined in `ui/text.dart`. I also added it to the signature of `ParagraphBuilder.addPlaceholder` as an optional parameter. I additionally added a new member to the `PlaceholderAlignment` enum. I don't have any references in my app code, it's just used in the framework.

The erorrs seen in framework code:
- The new enum `PlaceholderFloating` is not recognized as a type
- The new optional parameter to `ParagraphBuilder.addPlaceholder` is not recognized
- The new member in `PlaceholderAlignment` is not found

**Comment by christopherfujino** [comment]
> I added this new enum `PlaceholderFloating` defined in `ui/text.dart`. I also added it to the signature of `ParagraphBuilder.addPlaceholder` as an optional parameter. I additionally added a new member to the `PlaceholderAlignment` enum. I don't have any references in my app code, it's just used in the framework.
> 
> The erorrs seen in framework code:
> 
> * The new enum `PlaceholderFloating` is not recognized as a type
> * The new optional parameter to `ParagraphBuilder.addPlaceholder` is not recognized
> * The new member in `PlaceholderAlignment` is not found

Thanks, should be easy enough to try out
