### ISSUE TITLE
The Magic of Flutter slides - presenter notes on Stateless vs Stateful

### ISSUE THREAD

**Issue by swavkulinski** [flutter/flutter#12493]
## Steps to Reproduce
OPEN: https://docs.google.com/presentation/d/1B3p0kP6NV_XMOimRV09Ms75ymIjU5gr6GGIX74Om_DE/edit?usp=sharing

Slide 23 - presenter notes say

CURRENT:

"Stateful is create for immutable elements that only rely on the object configuration information
StatelessWidgets are used for elements that can dynamically change based on state-changes in the system
Everytime that state changes, setChange() is called by the object
"

EXPECTED

Other way around.

## Logs

NA

## Flutter Doctor

NA

**Comment by SeraphimSerapis** [comment]
Thanks for noticing! I fixed the notes.

**Comment by sethladd** [comment]
Thanks!
