### ISSUE TITLE
Tooltip should be shown above the touch point, not below

### ISSUE THREAD

**Issue by markmclaren2** [flutter/flutter#12491]
Currently the tooltip will appear below the widget, so it is obscured by my finger.  Some users may not even realise that a tooltip has appeared.  Please make tooltip appear above the widget.

**Comment by markmclaren2** [comment]
Sorry I was looking at the tooltip property of IconButton, but it's easy to make tooltip appear above widget by wrapping the button in a Tooltip widget

**Comment by stemarco** [comment]
I think the original feature request for IconButton is still valid. The default display of IconButton tooltip should not be obscured by the user's finger.

**Comment by zoechi** [comment]
@stemarco this issue is long closed. If you think there is something that needs to be fixed please create a new issue with filled out issue template.
