### ISSUE TITLE
Error on console when starting app on AVD

### ISSUE THREAD

**Issue by JGeek00** [flutter/flutter#124908]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

This happens when I run the project form VSCode when the Android emulator is not running. What I do is open my project on VSCode, click on Run and then on Run without debugging. Most of the times it works fine, but sometimes it throws this error. It happens with every project but I think it only happens with an AVD running Android 13. To solve the issue I have to uninstall the app from the AVD and run it again. If I just stop the process and run it again I still have the same error. It's like at some point the installed app on the AVD becomes corrupted.

### Expected results

The app should start on the AVD without any issues.

### Actual results

I have this error on the console and the app on the AVD is stuck on the splash screen.
<img width="1414" alt="image" src="https://user-images.githubusercontent.com/47545344/232178625-4e881810-721f-4383-ab3f-b6e0a5ad7074.png">

### Code sample

I think the code doesn't have anything to do here, because i have seen it with all my projects.

### Screenshots or Video

<img width="1414" alt="image" src="https://user-images.githubusercontent.com/47545344/232178672-391b4082-2df4-4054-9076-11f15fbdff8d.png">

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.7, on macOS 13.2.1 22D68 darwin-arm64, locale es-ES)
    • Flutter version 3.7.7 on channel stable at /Users/juan/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (5 weeks ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/juan/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/juan/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.77.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 112.0.5615.49

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by JGeek00** [comment]
I have removed the cache folder as it's suggested on that thread. Will see if that fixes the issue. As I said, the issue wasn't there all time.

**Comment by darshankawar** [comment]
Let us know what you find out after clearing cache folder.

**Comment by JGeek00** [comment]
Hi again. It has been working fine since last time I commented this. But the error has appeared again. Same messages in console and the app is stuck on the splash screen. It's something like the app installed on the AVD becomes corrupted, because I have to uninstall it to make it to work again.

**Comment by darshankawar** [comment]
> Does the same error occur running your project through command line / terminal instead of from VSCode ?

Also, try creating a new Flutter project inside VSCode and outside of it as well and see if you still get same error or not.

**Comment by JGeek00** [comment]
I have removed that AVD and created a new one. Will see if that works.

**Comment by JGeek00** [comment]
I tried creating a new AVD but still after around 3 weeks it has the same error. The problem is that this happens after around 3 weeks of development. If I create a new flutter project now it will work.

**Comment by darshankawar** [comment]
Can you please provide the complete error log in properly formatted text ?

**Comment by JGeek00** [comment]
What do you mean with properly formatted text? The only thing that's displayed on the console are these three lines that I added on the screenshot of the first message. Don't know if there's another way to get a more detailed log.

**Comment by darshankawar** [comment]
> What do you mean with properly formatted text?

To copy the console log you are seeing and paste it here in proper format, ie, inside ``` quote, instead of sharing screenshots of the console log.

@JGeek00 If you upgrade to latest stable or master version and try again, can you confirm if the same behavior persists or not ?

**Comment by JGeek00** [comment]
Same issue again. This time with a different project.
```
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
main.dart:1
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
E/flutter ( 4221): [ERROR:flutter/runtime/dart_isolate.cc(144)] Could not prepare isolate.
E/flutter ( 4221): [ERROR:flutter/runtime/runtime_controller.cc(422)] Could not create root isolate.
E/flutter ( 4221): [ERROR:flutter/shell/common/shell.cc(614)] Could not launch engine with configuration.
```

**Comment by darshankawar** [comment]
What flutter version are you on ? Can you possibly be on latest stable or master and try again ?

**Comment by JGeek00** [comment]
> What flutter version are you on ? Can you possibly be on latest stable or master and try again ?
> 
> 

I'm using the latest version available on the stable channel. I think it's 3.10.5.

**Comment by darshankawar** [comment]
> Same issue again. This time with a different project.

Can you provide some details about this project ? Since it doesn't seem to be occuring with standalone / new Flutter project, there could be some plugins  / implementation that might be causing it and you'll probably need to revisit or try to narrow down the reported behavior before sharing the problem / issue you are facing.
