### ISSUE TITLE
[CP] Enable Gradle 8 on flutter 3.7 

### ISSUE THREAD

**Issue by reidbaker** [flutter/flutter#124993]
### issue_link

[124838](https://github.com/flutter/flutter/issues/124838)

### Commit Hash

n/a 

### Target

stable

### pr_link

https://github.com/flutter/flutter/pull/124990

### Impacted Users

Users who wish to use gradle 8.0 as encouraged by AndroidStudio Flamingo but cannot adopt full null safety. 

### Impact Description

Flutter users running 3.7 can adopt gradle 8.0 

### Workaround

They can use the 3.10 beta or not update to gradle 8.0

### Risk

medium

### Test Coverage

no

### Validation Steps

run `flutter build apk` on any app using an older version of gradle. Update any app to use gradle 8.0.* and run the command again. 

With this change the build should pass. Without this change the build should fail on 3.7 (and pass on 3.10).

**Comment by CaseyHillers** [comment]
@camsim99 can you review this CP? If it looks good, can you add the label "cp: approved"?

**Comment by CaseyHillers** [comment]
FYI @godofredoc. I'll ship this stable Wednesday after you've shipped the beta hotfix due to the priority on this CP.

**Comment by MacLeeIn** [comment]
Follow

**Comment by CaseyHillers** [comment]
Released in 3.7.12
