### ISSUE TITLE
[flutter_localizations] Add compatibility with intl 0.18.0

### ISSUE THREAD

**Issue by netgfx** [flutter/flutter#124959]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Try to follow the tutorial here: https://docs.flutter.dev/development/accessibility-and-localization/internationalization

And install flutter_localizations

### Expected results

flutter_localizations is installed without any issues

### Actual results

getting:

```
Because every version of flutter_localizations from sdk depends on intl 0.17.0 and myapp depends on intl ^0.18.0, flutter_localizations from sdk is forbidden.
So, because myapp depends on flutter_localizations from sdk, version solving failed.
pub finished with exit code 65
```

### Code sample

<details><summary>Code sample</summary>

```dart
flutter pub add flutter_localizations --sdk=flutter
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.7.10, on Microsoft Windows [Version 10.0.19045.2846], locale el-GR)
[√] Windows Version (Installed version of Windows is version 10 or higher)      
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.5.0)   
[√] Android Studio (version 2021.1)
[√] VS Code, 64-bit edition (version 1.77.3)
[√] Connected device (3 available)
[√] HTTP Host Availability
```

</details>

**Comment by HannesGitH** [comment]
i had a similar problem with awesome_notifications using an older intl and solved it like this: https://github.com/rafaelsetragni/awesome_notifications/pull/727
