### ISSUE TITLE
[flutter_adaptive_scaffold] Use NavigationBar instead of BottomNavigationBar for Material 3 Apps

### ISSUE THREAD

**Issue by fmt-Println-MKO** [flutter/flutter#124984]
## Use case

NavigationBar is the implementation based on Material 3.
NavigationBar should be used instead of BottomNavigationBar to have a common M3 design.

## Proposal
exchange BottomNavigationBar with NavigationBar as adaptive scaffold claims to be M3

**Comment by huycozy** [comment]
@fmt-Println-MKO I see there is an issue (https://github.com/flutter/flutter/issues/127088) that seems to be introduced by the PR of this issue. Can you please take a look?
