### ISSUE TITLE
Amazon Fire Tv problem with video player

### ISSUE THREAD

**Issue by Jonhs2323** [flutter/flutter#124947]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Hello, I Have this problem with flutter video_player plugin on an amazon fire tv the video resize when quality switch automatically 

### Expected results

Hello, I Have this problem with flutter video_player plugin on an amazon fire tv the video resize when quality switch automatically 

### Actual results

Hello, I Have this problem with flutter video_player plugin on an amazon fire tv the video resize when quality switch automatically 

### Code sample

Hello, I Have this problem with flutter video_player plugin on an amazon fire tv the video resize when quality switch automatically 

### Screenshots or Video

[<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]
![211071823-166260c3-f42f-4e56-9b15-703189078333](https://user-images.githubusercontent.com/130933538/232340696-54decbf8-6d69-4f70-880a-7c7ccc3947cd.png)

</details>

### Logs

This The problem

### Flutter Doctor output

This The problem

**Comment by darshankawar** [comment]
@Jonhs2323 
Can you provide `flutter doctor -v` ? Also try to switch to latest master or stable and try again to see if you still see same behavior or not.

Maybe similar to : https://github.com/flutter/flutter/issues/46460

**Comment by Jonhs2323** [comment]
The issue is the same i found the risolution but master release does't exists #125153 this is the resolution

**Comment by Jonhs2323** [comment]
My flutter version: [✓] Flutter (Channel master, 3.9.0-21.0.pre.9, on macOS 13.1 22C65 darwin-arm64, locale it-IT)
    • Flutter version 3.9.0-21.0.pre.9 on channel master at /Users/gabry/Documents/sdk/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0046a25e39 (2 weeks ago), 2023-04-03 12:56:56 -0400
    • Engine revision 01aa040721
    • Dart version 3.0.0 (build 3.0.0-402.0.dev)
    • DevTools version 2.22.2

**Comment by darshankawar** [comment]
Please try either on latest stable (3.7.12) or on latest master (3.10.0-10.0.pre.14) to see if the reported behavior still persists or not.

**Comment by Jonhs2323** [comment]
How to switch to this release ?

**Comment by Jonhs2323** [comment]
How to switch to this release?

**Comment by darshankawar** [comment]
if you are on master already, then `flutter upgrade`. If you want to switch to latest stable, then:

flutter channel stable
flutter upgrade

**Comment by Jonhs2323** [comment]
I switch on latest stable and latest master but the problem is the same

**Comment by darshankawar** [comment]
Can you try using the video_player [plugin example](https://github.com/flutter/packages/tree/main/packages/video_player/video_player/example) to see if you still get same behavior or not ? I am unable to verify this locally due to lack of specified device.

**Comment by Jonhs2323** [comment]
Im using Betterplayer because i use drm content

**Comment by darshankawar** [comment]
https://pub.dev/packages/better_player is a third party package, so if you are using it, then you'll need to report this issue in dedicated repo. If you are facing the issue using video_player which is Flutter's first party package, then we can make this issue actionable, but I think per https://github.com/flutter/flutter/issues/46460#issuecomment-1510520351, the issue should be fixed using video_player.

**Comment by Jonhs2323** [comment]
On video_player package Is possible to use drm content?

**Comment by darshankawar** [comment]
No. You may follow-up in this issue: https://github.com/flutter/flutter/issues/24923.
I'll close this as a duplicate for drm content and please open original issue in better player's dedicated repo as mentioned earlier.
