### ISSUE TITLE
Codelab: can not use firebase_auth_web

### ISSUE THREAD

**Issue by tndevDE** [flutter/flutter#124936]
firebase_auth seems to be incompatible with firebase_ui_auth, as both require a different intl version as a dependency.

`\Codelabs\firebase-get-to-know-flutter\step_02> flutter pub add firebase_auth_web`
`Because firebase_auth >=4.4.1 depends on firebase_auth_web ^5.3.1 which depends on intl ^0.17.0, firebase_auth >=4.4.1 requires intl ^0.17.0.
And because every version of firebase_ui_auth depends on flutter_localizations from sdk which depends on intl 0.18.0, firebase_auth >=4.4.1 is incompatible with firebase_ui_auth.
So, because gtk_flutter depends on both firebase_auth ^4.4.1 and firebase_ui_auth ^1.1.17, version solving failed.`

**Comment by tndevDE** [comment]
I have switched to the stable version of flutter and now it works. 

But in the description of "Codelab: Get to know Firebase for Flutter" it says you can also use the beta version.

> You also need the following:

> A browser of your choice, such as Google Chrome.
An IDE or text editor of your choice configured with the Dart and Flutter plugins, such as [Android Studio]> (https://developer.android.com/studio) or [Visual Studio Code](https://code.visualstudio.com/).
The latest stable version of [Flutter](https://flutter.dev/docs/get-started/web#set-up) or **beta** if you enjoy living on the edge.
A Google Account for the creation and management of your Firebase project.
The [Firebase CLI](https://firebase.google.com/docs/cli) logged in to your Google Account.

**Comment by darshankawar** [comment]
There's an open PR to update the intl version to latest: https://github.com/firebase/flutterfire/pull/10317 which will possibly fix the issue.

For time being, you can use [this](https://github.com/firebase/flutterfire/issues/10199#issuecomment-1368981937) solution. 

Keeping this issue open for team's attention and to decide if anything need to be updated in respective codelab.

/cc @domesticmouse

**Comment by domesticmouse** [comment]
Thoughts @ericwindmill?

**Comment by ericwindmill** [comment]
This is a known issue with the Firebase for Flutter packages themselves. It has been fixed.
