### ISSUE TITLE
ListView.builder should let clients specify a divider

### ISSUE THREAD

**Issue by dguralnick** [flutter/flutter#12492]
The [ListView](https://docs.flutter.io/flutter/widgets/ListView-class.html) class should let clients specify a divider to be added between each Widget in the list. When all children are available ahead of time [ListTile.divideTiles](https://docs.flutter.io/flutter/material/ListTile/divideTiles.html) works, but there is no easy way to get the same effect with the [ListView.builder](https://docs.flutter.io/flutter/widgets/ListView/ListView.builder.html) interface aside from wrapping/decorating each built element.

**Comment by carstenhag** [comment]
Is there any progress on this? It seems really weird that there is no inbuilt way to do this.

**Comment by SUPERETDUPER** [comment]
When this issue is complete make sure to update the flutter tutorial here : https://flutter.io/get-started/codelab/

It uses a hack to add dividers so once this is complete it should use the built in API.

**Comment by zoechi** [comment]
Have you tried https://docs.flutter.io/flutter/material/Divider-class.html?

**Comment by HansMuller** [comment]
Support for ListView separators was added here: https://github.com/flutter/flutter/pull/18619

@willlarche - maybe `new ListView.separated()` could be incorporated into a codelab update.

**Comment by alanrussian** [comment]
@HansMuller doesn't using `ListView.separated` with a Divider not follow the Material spec? It looks like `ListView.separated` adds a divider _between_ each item. IIRC the Material spec mandated that the divider should be placed at the bottom of each item, on top of its padding.

The old spec says this ("Placement: Along the bottom edge of content tiles") but I guess the new spec website doesn't. Maybe it was changed?

**Comment by HansMuller** [comment]
The [current spec](https://material.io/design/components/lists.html#anatomy) isn't terribly strong on this point but it does include this:

> **Do.**
> Place a divider between rows with lots of content, such as those with three-line lists.

Most of the spec examples with dividers seem to put them (just) in between items.

**Comment by d-silveira** [comment]
@HansMuller  Am I misinterpreting the issue, or isn't ListView.separated incompatible with ListView.builder? Which is what the whole point of this issue, in which case it should not be closed with this argument!

**Comment by HansMuller** [comment]
I don't intend to add support for automatically including dividers for the general ListView.builder case.

@dguralnick - if ListView.separated didn't address your requirements, I'll be happy to reopen this issue.

**Comment by JosephDunivan** [comment]
@SUPERETDUPER @HansMuller 
> https://flutter.io/get-started/codelab/#step-4-create-an-infinite-scrolling-listview
 The so called "hack" does not work if you generate a list with json or database because it will replaced odd index values with a divider instead of the actual element with a divider underneath it. It's hardly a solution. Why has this issue been closed exactly?

**Comment by HansMuller** [comment]
I hope we didn't refer to it as a "hack".

If you have a list of N database or JSON items then creating a ListView whose itemCount is N * 2 and doing the arithmetic to distinguish item indices from data indices in the item builder shouldn't be a problem.

The solution would be the same for an unbounded list. In either case the item index is the index of the list item - a divider or a data item - rather than the data item. The index of the data item is `i ~/ 2`.

**Comment by SUPERETDUPER** [comment]
@HansMuller 

I think the issue should be reoppened and divider functionality should be added to `ListView.builder`.
A couple advantages to doing this
- Make people less confused (ex. @JosephDunivan )
- Define a best practice/standard (ex. decorate items or add a divider every second item)
- Reduce amout of code the developer must write (and therefor the chance of bugs)
- Make it feel less hackish

Being able to have dividers between items seems like a standard feature. There could be a simple boolean switch in the constructor.
