### ISSUE TITLE
tester.longPress() in tester.runAsync() not working

### ISSUE THREAD

**Issue by codercengiz** [flutter/flutter#124973]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

It works when I write my test like this
```dart
    testWidgets('Should open debug page when long press on app logo',
        (tester) async {
      await tester.pumpWidget(MyApp());
      var logo = find.byKey(Key('logo'));
      expect(logo, findsOneWidget);
      await tester.longPress(logo);
      await tester.pump();
      expect(find.byKey(Key('debug_page_dialog')), findsOneWidget);
         });
```

But when I wrapped it with `tester.runAsync` it is not working, test fails.
```dart
 testWidgets(
      'Should open debug page when long press on app logo',
      (tester) async {
        await tester.runAsync(() async {
          await tester.pumpWidget(MyApp());
          var logo = find.byKey(Key('elofleet_logo'));
          expect(logo, findsOneWidget);
          await tester.longPress(logo);
          await tester.pump();
          expect(find.byKey(Key('debug_page_dialog')), findsOneWidget);
        });
      },
    );
```
I saw this is the reason
It does not wait this call `await pump(kLongPressTimeout + kPressTimeout);` on source code of `flutter_test` (flutter_test/lib/src/controller.dart).

And I should use  `tester.runAsync()` to wait response from my real test server.

### Expected results

It should work, but it can not wait so it can not pass the next line

### Actual results

Test fails

### Code sample

<details><summary>Code sample</summary>

```dart
 testWidgets(
      'Should open debug page when long press on app logo',
      (tester) async {
        await tester.runAsync(() async {
          await tester.pumpWidget(MyApp());
          var logo = find.byKey(Key('elofleet_logo'));
          expect(logo, findsOneWidget);

      await tester.longPress(logo);
      await tester.pump();
          expect(find.byKey(Key('debug_page_dialog')), findsOneWidget);
        });
      },
    );
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.10, on Arch Linux 6.2.10-arch1-1, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Community Edition (version 2021.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @codercengiz 
I think your case is similar to https://github.com/flutter/flutter/issues/95203, so please follow-up in it for further updates.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.
