### ISSUE TITLE
Flutter Engine static linking

### ISSUE THREAD

**Issue by RossComputerGuy** [flutter/flutter#124902]
## Use case

Embedded situations, portability, static binaries.

## Proposal

As Flutter's engine can be built for embedded uses, it would be a good idea to support static library linking. Then it would be a matter of linking whatever program uses the embedded engine with `flutter_engine.a`.

**Comment by stuartmorgan** [comment]
> Then it would be a matter of linking whatever program uses the embedded engine with `flutter_engine.a`.

In order to do this safely, the program would need to be built with exactly the same compiler, with the same flags. What's the realistic use case where that is being done with a different build system, such that the engine build needs to produce a static library as an end product?

**Comment by RossComputerGuy** [comment]
My OS's runtime is programmed in Zig and so static linking all dependencies would allow for a more portable build of the OS's applications and compositor. There are other programming languages which also tend to prefer static linking, I think Golang is one of those. Static linking would allow for a smaller runtime environment in general and OTA updates wouldn't break as much when only an application or the runtime itself needs to update but not the OS.

**Comment by stuartmorgan** [comment]
That doesn't answer the question I was asking; you're explaining what your goal is, not how it would be accomplished. How do you propose safely linking your code to a static library built with a different build system?

**Comment by RossComputerGuy** [comment]
Idk how to explain, linking in Zig just works pretty much. Zig's compiler uses LLVM for linking, Flutter's built with clang so it should just work.

**Comment by RossComputerGuy** [comment]
I tried implementing this myself in https://github.com/flutter/engine/pull/41234/commits/cc9447e0195a2030ad69466bbcb3bc2fcfc8e654 but I kept on running into issues:
```
flutter-engine-debug> Generating GN files in: /nix/store/j5w2697rq89qxhvi8xbbwfk3gkrad0lc-flutter-engine-debug-3.7.10/lib/flutter-engine/out/x86_64-linux-debug
flutter-engine-debug> ERROR Input to target not generated by a dependency.
flutter-engine-debug> The file:
flutter-engine-debug>   /nix/store/j5w2697rq89qxhvi8xbbwfk3gkrad0lc-flutter-engine-debug-3.7.10/lib/flutter-engine/out/x86_64-linux-debug/libflutter_engine.a
flutter-engine-debug> is listed as an input or source for the target:
flutter-engine-debug>   //flutter/shell/platform/embedder:embedder-archive
flutter-engine-debug> but no targets in the build generate that file.
flutter-engine-debug> If you have generated inputs, there needs to be a dependency path between the
flutter-engine-debug> two targets in addition to just listing the files. For indirect dependencies,
flutter-engine-debug> the intermediate ones must be public_deps. data_deps don't count since they're
flutter-engine-debug> only runtime dependencies. If you think a dependency chain exists, it might be
flutter-engine-debug> because the chain is private. Try "gn path" to analyze.
```
I haven't been able to determine the solution.

**Comment by darshankawar** [comment]
Keeping this issue open and labeling for tracking and ongoing discussion.

**Comment by chinmaygarde** [comment]
This isn't something we want to support for all the challenges @stuartmorgan mentioned. Dynamic symbols resolution works in most environments (I've [seen it used in Go](https://github.com/go-flutter-desktop/go-flutter) too). Re. the portability, having an engine with a stable ABI (which it does) and an embedder (perhaps in Zig) talking to it seems more portable and upgradable than moving everything into one blob. Besides, for AOT, you are still going to need dylibs since gen_snapshot doesn't doesn't dump archives.

You are free to tinker on the build system but this isn't something we are going to invest in or vend artifacts for at this time (which would be extremely large).

Closing this as wont-fix.
