### ISSUE TITLE
Native context menu for TextField

### ISSUE THREAD

**Issue by ansjdev** [flutter/flutter#124948]
## Use case

The TextField widget lacks support for native context menu, such as translation or sharing (In my case of Android)

Screenshot of a native app(Google) running on a Pixel 6 Pro emulator with API 33.
![image](https://user-images.githubusercontent.com/120151924/232341951-1594db9b-fbec-4830-a87e-3e03cb5c16d0.png)

Screenshot of a native app running on my Xiaomi smartphone with MIUI 14 and Android 13.
![image](https://user-images.githubusercontent.com/120151924/232341980-27dc381e-2d15-446d-84f5-d90f2610f443.png)

Screenshot of my Flutter app running on a Pixel 6 Pro emulator with API 33, showing a text field with only default context menu of Flutter and without native context menu like translate or share.
![image](https://user-images.githubusercontent.com/120151924/232342033-c9576d20-8bef-48be-9215-258b1dbfa668.png)

I couldn't find any packages to solve my problem.

## Proposal

Add support for native context menu on all platforms.

**Comment by danagbemava-nc** [comment]
Hi @ansjdev, this is being tracked in https://github.com/flutter/flutter/issues/107578.

Kindly subscribe to the original issue for updates. 

Closing from here as duplicate. 

Thank you
