### ISSUE TITLE
I/libperfctl(28667): Can't open /proc/perfmgr/perf_ioctl: Permission denied

### ISSUE THREAD

**Issue by DiegoLimeiradaSilva** [flutter/flutter#124969]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Good morning, debugging on a POCO F4 GT physical device, I have the message on the console in excess.
![Captura de Tela 2023-04-17 às 10 52 06](https://user-images.githubusercontent.com/8137926/232504625-2d8d714f-0b2e-4cbf-8171-abc28fc262fe.png)

### Expected results

the message that disturbs the log does not appear

### Actual results

I/libperfctl(28667): Can't open /proc/perfmgr/perf_ioctl: Permission denied
W/1.raster(28667): type=1400 audit(0.0:1806101): avc: denied { search } for name="perfmgr" dev="proc" ino=4026532433 scontext=u:r:untrusted_app_30:s0:c75,c257,c512,c768 tcontext=u:object_r:proc_perfmgr:s0 tclass=dir permissive=0 app=br.com.mts.mtsistemascrm2

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.7.11, on macOS 13.3 22E252 darwin-x64, locale pt-BR)
    ! Warning: `dart` on your path resolves to /usr/local/Cellar/dart-sdk/2.19.5/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/diegolimeiradasilva/fvm/versions/stable. Consider adding /Users/diegolimeiradasilva/fvm/versions/stable/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.77.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Comment by darshankawar** [comment]
@DiegoLimeiradaSilva 
What OS and api level is your device on ? Is it only occuring on this specific device or on other devices too ?
Check [this](https://stackoverflow.com/questions/52782894/error-reading-cpu-usage-proc-stat-permission-denied) and see if it helps.

**Comment by DiegoLimeiradaSilva** [comment]
![Screenshot_2023-04-18-07-00-33-152_com.android.settings.jpg](https://user-images.githubusercontent.com/8137926/232743247-fd22c8ec-2cab-4f08-b07a-86341814625b.jpg)

Hi. My Android version os 13.

**Comment by darshankawar** [comment]
Can you try couple of things ?

1. Create a new Flutter project and run it on same device to see if you still get same error or not.


2. Switch to latest master and run your scenario again to see if you still get same error or not.

`flutter channel master -> flutter upgrade`

**Comment by DiegoLimeiradaSilva** [comment]
I created a project from scratch did not give the problem. I installed the latest version and created a new project, the error did not occur. So it's probably a package. which I use in my 2 projects. Now all that's left is to investigate. Thank you very much.

**Comment by darshankawar** [comment]
Good to know. Closing based on above comment as this doesn't seem to be framework related.
