### ISSUE TITLE
Revert migration of mac host engine to engine v2

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#124911]
https://github.com/flutter/engine/pull/41233

Some notes for a triaging chat:

```
It looks like somehow the framework is using an ancient engine version.

I flutter create a brand new project and run it with flutter run -d mac and I get:
Building macOS application...
2023-04-14 19:09:24.908 deleteme[83098:3926602] NSApp should be of type FlutterApplication, not NSApplication.
System requests for the application to terminate will not be sent to the Flutter framework, so the framework will be unable to cancel those requests.
Modify the application's NSPrincipleClass to be FlutterApplication in the Info.plist to fix this.
[ERROR:flutter/shell/common/shell.cc(89)] Dart Error: Can't load Kernel binary: Invalid SDK hash.
[ERROR:flutter/runtime/dart_isolate.cc(144)] Could not prepare isolate.
[ERROR:flutter/runtime/runtime_controller.cc(422)] Could not create root isolate.
[ERROR:flutter/shell/common/shell.cc(606)] Could not launch engine with configuration.
```

```
First off the kernel hash is mismatched which indicates something's way off between the engine and framework and second, the "NSApp should be of type FlutterApplication, not NSApplication." was removed over a week ago in https://github.com/flutter/engine/pull/40929, before the branch.

The framework claims to be using an engine.verison of 0a5ed019cea52f4134cc731925d540bb0a0cb5b4 which is definitely pretty close to tip of tree and definitely doesn't have the error message code listed above...
```

```
% cat bin/internal/engine.version
0a5ed019cea52f4134cc731925d540bb0a0cb5b4
% grep -r "NSApp should be of type" bin/cache/artifacts/engine/darwin-x64/FlutterMacOS.framework
Binary file bin/cache/artifacts/engine/darwin-x64/FlutterMacOS.framework/Versions/A/FlutterMacOS matches
```

```
% git reset --hard 0a5ed019cea52f4134cc731925d540bb0a0cb5b4
HEAD is now at 0a5ed019ce Roll Skia from 22e417bea884 to f489b4a06e19 (6 revisions) (#41225)
% git grep "NSApp should be of type"
%
```

```
% git bisect good
016bcc10001e675948534efa4ab568d3e2df85fd is the first bad commit
commit 016bcc10001e675948534efa4ab568d3e2df85fd
Author: engine-flutter-autoroll <engine-flutter-autoroll@skia.org>
Date:   Fri Apr 14 21:21:26 2023 -0400

    Roll Flutter Engine from f7945293aced to 0a5ed019cea5 (2 revisions) (#124901)

    https://github.com/flutter/engine/compare/f7945293aced...0a5ed019cea5

    2023-04-14 skia-flutter-autoroll@skia.org Roll Skia from 22e417bea884 to f489b4a06e19 (6 revisions) (flutter/engine#41225)
    2023-04-14 skia-flutter-autoroll@skia.org Roll Dart SDK from 36b37d0a8db7 to 5687f08b854d (1 revision) (flutter/engine#41224)

    If this roll has caused a breakage, revert this CL and stop the roller
    using the controls here:
    https://autoroll.skia.org/r/flutter-engine-flutter-autoroll
    Please CC jacksongardner@google.com,rmistry@google.com,zra@google.com on the revert to ensure that a human
    is aware of the problem.

    To file a bug in Flutter: https://github.com/flutter/flutter/issues/new/choose

    To report a problem with the AutoRoller itself, please file a bug:
    https://bugs.chromium.org/p/skia/issues/entry?template=Autoroller+Bug

    Documentation for the AutoRoller is here:
    https://skia.googlesource.com/buildbot/+doc/main/autoroll/README.md

 bin/internal/engine.version | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```

**Comment by godofredoc** [comment]
The issue here is that `0a5ed019cea52f4134cc731925d540bb0a0cb5b4` seems to have built the artifacts using older than a week commits.

**Comment by godofredoc** [comment]
\cc @cbracken @gspencergoog

**Comment by godofredoc** [comment]
Using https://ci.chromium.org/p/flutter/builders/prod/Mac%20mac_host_engine/3098 validated all the artifacts were built using the right version of the code.

**Comment by godofredoc** [comment]
Framework `f89caf7caff0da241da6e65d1ba199b196a8e7a8` with engine `4552a6e105f129dfb8e60fe10e3d3ad7d6208234` that does not contain the engine v2 migration`f6e64a87407f3b728258999f3f53512b68393d55` is working correctly.

**Comment by godofredoc** [comment]
Even with `016bcc10001e675948534efa4ab568d3e2df85fd` with engine `0a5ed019cea52f4134cc731925d540bb0a0cb5b4` does not replicate the issue in my machine.

@cbracken are you using an x86 mac?

**Comment by godofredoc** [comment]
Just checked on x86 mac and everything is working correctly for flutter/016bcc10001e675948534efa4ab568d3e2df85fd with engine/0a5ed019cea52f4134cc731925d540bb0a0cb5b4

**Comment by godofredoc** [comment]
Added https://flutter-review.googlesource.com/c/recipes/+/41960 to ensure global generator artifacts start from a clean builder/src/out folder.

**Comment by godofredoc** [comment]
This is happening again, and seems to be happening only when we create a project on top of an existing one:

Reproducing steps
```
cd <flutter checkout>
git reset --hard 76b30c30a79a7498dec4365f39255339d0586526
mkdir ~/delete && cd delete && flutter create . && flutter run --device-id macos
# Up to this point everything succeeds
cd <flutter checkout>
git fetch upstream && git merge upstream master && git reset --hard 9cc5f5558afe58a929ed4013326063940a6af027
cd  ~/delete && flutter create . && flutter run --device-id macos
```

**Comment by godofredoc** [comment]
Found the issue. It is caused by the double zip|unzip of FlutterMacOS.framework.zip created by recipes, for example if we hard reset to a version using recipe artifacts FlutterMacOS.framework.zip will be zipped twice and the tool logic will unzip it twice. When using an existing checkout with the binaries already cached reseting to a version using gn+ninja targets will download  FlutterMacOS.framework.zip that is single zipped but because there was already a FlutterMacOS.framework.zip from old version it will unzip the old version on top of the new version.

Tests did not fail because CI always start with a clean checkout and the tool functionality works correctly with the single zipped file, but this will be annoying for users with an existing checkout as they will need to manually clean the caches.

A few options to fix the issue:

* Reland the migration of mac host engine and remove the double zipping functionality.
* Double zip the artifact in engine v2 to match the artifact from recipes.
* Make the tool delete FlutterMacOS.framework.zip  if they exist in cache before downloading and extracting the new version.

@jmagman @christopherfujino what is the best fix for this?

**Comment by zanderso** [comment]
```
git fetch upstream && git merge upstream master && git reset --hard 9cc5f5558afe58a929ed4013326063940a6af027
cd  ~/delete && flutter create . && flutter run --device-id macos
```

This would be a very unusual flow for an end-user to follow. Does this happen on CI in some context?

**Comment by christopherfujino** [comment]
@jmagman should not rsync have handled this?

**Comment by christopherfujino** [comment]
Or is that the new recipes have an extra layer of zipping?

**Comment by godofredoc** [comment]
@zanderso no it doesn't happen in CI because all the tests start with a clean checkout. Only people with cached artifacts from pre v2 updating to a v2 artifacts commit see this issue.

**Comment by godofredoc** [comment]
We can double zip the v2 artifact to make it consistent with the legacy artifact, or maybe this is a good time to get rid of this tech debt?

**Comment by christopherfujino** [comment]
> We can double zip the v2 artifact to make it consistent with the legacy artifact, or maybe this is a good time to get rid of this tech debt?

I am planning to do this Q2, but it won't happen in the next 2 weeks

**Comment by godofredoc** [comment]
If you provide some pointers I can help sending a fix, or alternatively I can add the double zipping temporarily to unblock the migration to engine v2 builds.

**Comment by godofredoc** [comment]
Mac Host Engine migration was reverted again. Now the issue is several builds failing with:

```
/Volumes/Work/s/w/ir/x/w/flutter/dev/integration_tests/ui/macos/Runner/MainFlutterWindow.swift:6:8: error: no such module 'FlutterMacOS'
[        ] import FlutterMacOS
```

Roll PR with failures: https://github.com/flutter/flutter/pull/125260/checks?check_run_id=12911268600

**Comment by godofredoc** [comment]
Commit to replicate the issue: b2cebe040938c30a0d4e51a97a71c5af07b0b99a

**Comment by godofredoc** [comment]
Replicating with https://github.com/flutter/flutter/pull/119969/checks
