### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method myMethod on channel com

### ISSUE THREAD

**Issue by ekanath25** [flutter/flutter#124979]
I am facing an issue with calling a native method written in Java from Flutter v2.10, I am getting this error Unhandled Exception: MissingPluginException(No implementation found for method myMethod on channel com.example.flutter_to_native/myMethodChannel). 

I have verified the method name and platform channel both are the same in Flutter and Java. 

Java code
`package com.example.flutter_to_native;

import androidx.annotation.NonNull;
import android.os.Bundle;

import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.embedding.android.FlutterActivity;
import io.flutter.embedding.engine.FlutterEngineCache;
import io.flutter.embedding.engine.plugins.FlutterPlugin;
import io.flutter.plugin.common.MethodCall;
import io.flutter.plugin.common.MethodChannel;
import io.flutter.plugin.common.MethodChannel.MethodCallHandler;
import io.flutter.plugin.common.MethodChannel.Result;
import io.flutter.plugins.GeneratedPluginRegistrant;

public class MainActivity extends FlutterActivity {
  private static final String CHANNEL = "com.example.flutter_to_native/myMethodChannel";

  @Override
  public void configureFlutterEngine(FlutterEngine flutterEngine) {
    GeneratedPluginRegistrant.registerWith(flutterEngine);

    new MethodChannel(flutterEngine.getDartExecutor().getBinaryMessenger(), CHANNEL)
        .setMethodCallHandler(
            (call, result) -> {
              if (call.method.equals("myMethod")) {
                // Implement your method logic here
                result.success("Method executed successfully");
              } else {
                System.out.print("herere caleed");
                result.success("Method executed successfully");
                result.notImplemented();
              }
            }
        );
  }
}

Flutter code
-------------

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  static const platform =
      MethodChannel('com.example.flutter_to_native/myMethodChannel');
  String _responseFromNativeCode = 'Waiting for Response...';

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  Future<void> responseFromNativeCode() async {
    String response = "";
    try {
      final String result = await platform.invokeMethod('myMethod');
      response = result;
    } on PlatformException catch (e) {
      response = "Failed to Invoke: '${e.message}'.";
    }
    setState(() {
      _responseFromNativeCode = response;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
            RaisedButton(
              child: Text('Call Native Method'),
              onPressed: responseFromNativeCode,
            ),
            Text(_responseFromNativeCode),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
`
Please help with this. Thanks in advance

**Comment by darshankawar** [comment]
@ekanath25 
Please check the documentation to implement platform specific code with Flutter https://docs.flutter.dev/development/platform-integration/platform-channels#example-project and check if it helps in your case.
The error you are getting most probably indicates the implementation is not correct and is missing a method call, so you can also check on support channels like StackOverflow for solution on missing code implementation.

I'll close this as it doesn't seem to be a bug but a missing code implementation. If you disagree, write in comments and I'll reopen it.
