### ISSUE TITLE
Using a resource not listed in flutter.yaml should show a red X

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#125]
<a href="https://github.com/eseidelGoogle"><img src="https://avatars.githubusercontent.com/u/11857803?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [eseidelGoogle](https://github.com/eseidelGoogle)**
_Tuesday Aug 11, 2015 at 21:01 GMT_
_Originally opened as https://github.com/flutter/engine/issues/565_

---

We need to make it a visual as well as console error to use a resource not listed in that file or skyx packing won't work correctly.

Probably a change to ResourceBundle?  @abarth

**Comment by abarth** [comment]
We have a console error but not a visual error.

**Comment by Hixie** [comment]
We now just don't render the image. Do you want more? Some sort of uglified red square with a cross or something?

**Comment by jonahwilliams** [comment]
We might want to revist implementing something similar for the web. In the case where the user has a FileImage, we should show something like a red box instead of crashing. We should make that image behavior as general as reasonably possible too

**Comment by Hixie** [comment]
Fixed by https://github.com/flutter/flutter/pull/74972.
