### ISSUE TITLE
Flutter debug app crashing on IOS  when disconnected to debugger

### ISSUE THREAD

**Issue by crazidev** [flutter/flutter#125041]
If I debug my application using flutter run and after then I stop the debugger, the debugging app on iOS crashes when opening it next time, and with this challenge I'm unable to run flutter attach because the app doesn't start, and help to keep the flutter app opening and running after debugging?

**Comment by darshankawar** [comment]
@crazidev 
Can you provide `flutter doctor -v`, steps to replicate along with complete error log you are getting ?
