### ISSUE TITLE
FirebaseSortedList throws exception when items update. Why ?

### ISSUE THREAD

**Issue by oyakitori** [flutter/flutter#12508]
First, congratulations an many thanks for those fantastic libraries. I love Firebase and Flutter.

## Why unsupported ?

I ran into unsupported exceptions from my AnimatedFirebaseList when its underlying data was updated, while node addition/deletion worked just fine...

Diving into the code, I saw this in firebase_sorted_list.dart
```dart
@override
  void operator []=(int index, DataSnapshot value) {
    throw new UnsupportedError("List cannot be modified.");
  }

```

So I daringly modified the code with this : 

```dart
@override
  void operator []=(int index, DataSnapshot value) {
    //throw new UnsupportedError("List cannot be modified.");
    _snapshots[index] = value;
  }
```

And it worked just fine, with live updates and all ! Is there a reason for not implementing this code ?
Does it justify a pull request for just a line of code ?
Regards

**Comment by Hixie** [comment]
cc @collinjackson

**Comment by kroikie** [comment]
@oyakitori

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/953. Any further collaboration will be done there.
