### ISSUE TITLE
Load "flutter loader plugin" using Gradle's `plugins {}` block, rather than imperative `apply`

### ISSUE THREAD

**Issue by bartekpacia** [flutter/flutter#125009]
## Current situation

The default, `flutter create`d app has the `android/settings.gradle` file with the following content:

```gradle
include ":app"

def localPropertiesFile = new File(rootProject.projectDir, "local.properties")
def properties = new Properties()

assert localPropertiesFile.exists()
localPropertiesFile.withReader("UTF-8") { reader -> properties.load(reader) }

def flutterSdkPath = properties.getProperty("flutter.sdk")
assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
apply from: "$flutterSdkPath/packages/flutter_tools/gradle/app_plugin_loader.gradle"
```

This line: 

```gradle
apply from: "$flutterSdkPath/packages/flutter_tools/gradle/app_plugin_loader.gradle"
```

imperatively applies the [`app_plugin_loader.gradle` script](https://github.com/flutter/flutter/blob/3.7.11/packages/flutter_tools/gradle/app_plugin_loader.gradle) to load the Flutter plugins (that have Android implementation).

## Preferred situation

We could create a new Gradle plugin (strictly speaking: a new Gradle settings plugin) to make the logic more declarative. I'm thinking about:

> Note: this is a new default `settings.gradle` (with changes made in #123511):

```groovy
pluginManagement {
    def flutterSdkPath = {
        def properties = new Properties()
        file("local.properties").withInputStream { properties.load(it) }
        def flutterSdkPath = properties.getProperty("flutter.sdk")
        assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
        return flutterSdkPath
    }
    settings.ext.flutterSdkPath = flutterSdkPath()

    // Flutter Gradle Plugin ships together with the Flutter SDK
    includeBuild("${settings.ext.flutterSdkPath}/packages/flutter_tools/gradle")

    plugins {
        // Add the default Flutter Gradle Plugin
        id "dev.flutter.flutter-gradle-plugin" version "1.0.0" apply false

        // Add the Flutter plugin loader Gradle Plugin
        id "dev.flutter.flutter-plugin-loader" version "1.0.0" apply false
    }
}

include ':app'
```

### Docs

From Gradle docs ([Developing Custom Gradle Plugins](https://docs.gradle.org/current/userguide/custom_plugins.html#sec:writing_a_simple_plugin)):

```kotlin
class GreetingPlugin : Plugin<Project> {
    override fun apply(project: Project) {
        project.task("hello") {
            doLast {
                println("Hello from the GreetingPlugin")
            }
        }
    }
}

// Apply the plugin
apply<GreetingPlugin>()
```

> Note that the [Plugin](https://docs.gradle.org/current/javadoc/org/gradle/api/Plugin.html) class is a generic type. This example has it receiving the [Project](https://docs.gradle.org/current/dsl/org.gradle.api.Project.html) type as a type parameter. A plugin can instead receive a parameter of type [Settings](https://docs.gradle.org/current/dsl/org.gradle.api.initialization.Settings.html), in which case the plugin can be applied in a settings script, or a parameter of type [Gradle](https://docs.gradle.org/current/dsl/org.gradle.api.invocation.Gradle.html), in which case the plugin can be applied in an initialization script.

## Use case

This doesn't have any immediate benefit to developers. It'll make us more compliant with best practices, though.

The biggest benefit that I see is that it'll allow us to migrate the `app_plugin_loader` from Groovy to Kotlin without users having to change the path in `settings.gradle` manually (somewhat related issue: #121541).

Other Gradle-related improvement issues:
- #121552
- #123934
- #124167

**Comment by gnprice** [comment]
Seems like a useful change. Thanks for writing this up.

```groovy
        id "dev.flutter.flutter-plugin-loader" version "1.0.0" apply false
```

Would this leave out the `apply false`? Or is there a different point where this new settings plugin would get applied?

**Comment by bartekpacia** [comment]
Oops, that looks like my mistake – it won't be applied then.

It should be:

```groovy
plugins {
    // Add the default Flutter Gradle Plugin
    id "dev.flutter.flutter-gradle-plugin" version "1.0.0" apply false

    // Add the Flutter plugin loader Gradle Plugin
    id "dev.flutter.flutter-plugin-loader" version "1.0.0" // or "apply true"
}
```

**Comment by gmackall** [comment]
@bartekpacia Can you make this title sound different from https://github.com/flutter/flutter/pull/123511, or emphasize the difference?

**Comment by bartekpacia** [comment]
Done.
