### ISSUE TITLE
[dart:ui] Introduce PlatformDispatcher.warmUpFrame API

### ISSUE THREAD

**Issue by loic-sharma** [flutter/flutter#125008]
## Background

[`FlutterView.render`'s documentation](https://github.com/flutter/engine/blob/c4396f9f602f7fb1dcc0f3160c9ab51bcd2aea1e/lib/ui/window.dart#L266-L268) claims that it must be called during `PlatformDispatcher.onBeginFrame` or `PlatformDispatcher.onDrawFrame`. This is not actually true today, the framework calls `FlutterView.render` outside of the lifetime of a frame in the following scenarios:

1. At app startup, the framework renders views without waiting for the first vsync
2. During hot reload, the framework renders views without waiting for the next vsync

See [`SchedulerBinding.scheduleWarmUpFrame`](https://github.com/flutter/flutter/blob/e99eb402227f01f69047c26b40f8abb0485d42f8/packages/flutter/lib/src/scheduler/binding.dart#L914-L929).

## Solution

* [ ] Introduce `PlatformDispatcher.warmUpFrame`. This API starts a frame immediately and calls `PlatformDispatcher.onBeginFrame` followed by `PlatformDispatcher.onDrawFrame`.
* [ ] Update the framework to use `PlatformDispatcher.warmUpFrame` whenever `FlutterView.render` must be called without waiting for a vsync
  * [ ] On initial launch
  * [ ] On hot reload
* [ ] Make the engine ignore `FlutterView.render`s that are called outside the lifetime of a frame

**Comment by goderbauer** [comment]
We are going with a different approach.
