### ISSUE TITLE
When I click on the TextField, the keyboard position is displayed strangely.

### ISSUE THREAD

**Issue by tape-a** [flutter/flutter#125095]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Hello. I'm having a problem while developing web using Flutter, so I have a question. 
The current development environment is as follows.
1) Flutter v3.7.11
2) iPhone12 & Safari

![테스트화면_20230419_01](https://user-images.githubusercontent.com/107022217/232975328-1730817f-0590-4e80-8abf-7774195174b5.jpg)
I created a web page like the picture above. 

### Expected results

I expected that when the TextField at the bottom is clicked, 
the keyboard is displayed and the Widgets are displayed on top of it. 
![정상동작_20230419_02](https://user-images.githubusercontent.com/107022217/232975454-921dc054-f773-419d-951e-591ac196b023.jpg)

### Actual results

However, sometimes widgets are moved twice as much as the height of the keyboard.
Is it possible to make the keyboard appear right below the TextField?
![비정상동작_20230419_03](https://user-images.githubusercontent.com/107022217/232975507-61f0c094-8f6e-4891-9c40-dc8291b03274.jpg)

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  MyApp({super.key});

  final List<Widget> list = List.generate(
    10,
    (index) => Container(
      width: 200,
      height: 200,
      margin: const EdgeInsets.all(10.0),
      child: ElevatedButton(
        onPressed: () {},
        child: const Text("TEST"),
      ),
    ),
  );

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        border: Border.all(color: Colors.red, width: 5),
      ),
      child: MaterialApp(
        home: Scaffold(
          body: Container(
            decoration: BoxDecoration(
              border: Border.all(color: Colors.blue, width: 5),
            ),
            child: SingleChildScrollView(
              child: Column(
                children: [
                  ...list,
                  Container(
                    width: double.infinity,
                    decoration: BoxDecoration(
                      border: Border.all(color: Colors.green, width: 5),
                    ),
                    child: const TextField(),
                  ),
                  const SizedBox(height: 50),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Actual test screen video</summary>

https://user-images.githubusercontent.com/107022217/232975833-8bc5e81e-31d8-48cf-a1de-a44ab5cd54f6.mp4

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.11, on Microsoft Windows [Version 10.0.22621.1555], locale ko-KR)
[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.0)
[√] Android Studio (version 2022.1)
[√] VS Code (version 1.75.0)
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment]
Thanks for the report with detailed information, @tape-a  
But this is a known issue being tracked at https://github.com/flutter/flutter/issues/124205. I can see this issue from my end and I will add there my comment (link to this issue) as well.

Closing this issue as a duplicate, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
