### ISSUE TITLE
Url Launcher not working with yahoo mail

### ISSUE THREAD

**Issue by subins829** [flutter/flutter#125028]
Couldn't open YahooMail with UrlLauncher in Android (IOS working fine).
working fine with other apps like Gmail, Outlook, Default Mail client

**Comment by huycozy** [comment]
Hi @subins829 
Please provide the information indicated below:
- If the issue can not reproduce with [plugin sample code](https://github.com/flutter/packages/tree/main/packages/url_launcher/url_launcher), please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example). 
- The output of `flutter doctor -v`
- Reproduction steps, Expected results, Actual results

Thank you!

**Comment by subins829** [comment]
static Future<void> sendEmail(String receiver, {String? subject}) async {
    final queryString = subject != null
        ? encodeQueryParameters(<String, String>{'subject': subject})
        : null;

    final Uri emailLaunchUri = Uri(
      scheme: 'mailto',
      path: receiver,
      query: queryString,
    );

    try {
      await launchUrl(emailLaunchUri);
    } catch (e) {
      print(e);
    }
  }

**Comment by subins829** [comment]
![image](https://user-images.githubusercontent.com/90414446/232768129-87cc6d9a-31bf-476d-abb1-4b67653e5701.png)
