### ISSUE TITLE
Wish for option to show dots in stepper

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#12500]
A current customer of Flutter asked for "mobile dots" with our Stepper class: https://material.io/guidelines/components/steppers.html#steppers-types-of-steps

For example:

<img width="360" alt="components-acux-stepper-mbldots" src="https://user-images.githubusercontent.com/5479/31467457-e29e1782-ae8e-11e7-91b4-3e4a47c37113.png">

**Comment by chrislondon** [comment]
The mobile dot stepper is pretty important.  The others are less important but we may like to use them in the future:

![screenshot from 2017-10-11 15-34-15](https://user-images.githubusercontent.com/889164/31468270-54b3c8d4-ae9a-11e7-905a-232280e2e2d1.png)

![screenshot from 2017-10-11 15-34-37](https://user-images.githubusercontent.com/889164/31468275-592b081e-ae9a-11e7-9cb1-60ff56e67e33.png)

**Comment by lschmierer** [comment]
I need this too

**Comment by eseidelGoogle** [comment]
This should be very straightforward to create as a custom widget.  PageView has some dots I believe which probably could be re-used.

**Comment by amirh** [comment]
Hi, after chatting with @HansMuller we are not sure if it makes sense to include a full mobile stepper widget in the framework, as it is pretty easy to implement using the primitives that are already available in the framework, and as the material spec for mobile stepper leaves a lot of room for flexibility.
Here’s a quick mobile stepper implementation example we put together:
https://github.com/amirh/flutter_playground/blob/mobile-stepper/lib/main.dart

Can you build what you need by doing something similar to this example?

**Comment by matthew-carroll** [comment]
@sethladd @amirh @HansMuller @eseidel  Should we go ahead and close this ticket?

**Comment by HansMuller** [comment]
The Material Stepper component is no longer part of the latest spec, https://material.io/design/components so I am going to close this issue.
