### ISSUE TITLE
flutter配置好运行命令得到zsh: operation not permitted: flutter

### ISSUE THREAD

**Issue by RookieAdzukiBean** [flutter/flutter#125089]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

在bash_profile和zshrc中都配置了相关信息
export PUB_HOSTED_URL=https://pub.flutter-io.cn
export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
export PATH=/Users/apple/Documents/flutter/bin:$PATH

### Actual results

在终端运行flutter相关命令得到zsh: operation not permitted: flutter
我在issues中看到类似相关问题，并且试了加文件完整性权限给到终端以及flutetr，还是没办法解决，以及电脑重启执行csrutil disable，再次进入电脑执行命令依旧不行，期望帮忙解决，最近准备转战flutter，谢谢

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<img width="570" alt="image" src="https://user-images.githubusercontent.com/44829134/232960725-054449c7-c6c2-4b95-8da0-831ce08c3bb4.png">

apple@appledeMacBook-Pro ~ % flutter doctor -v
zsh: operation not permitted: flutter
apple@appledeMacBook-Pro ~ %

**Comment by huycozy** [comment]
You should grant Full Disk Access to the Terminal app. Please check answers from [this](https://github.com/flutter/flutter/issues/65101) for more details.

Your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any. Closing, as this isn't an issue with Flutter itself. Thanks!
