### ISSUE TITLE
Duplicate symbol issue when using Firebase Database plugin and Firebase Firestore plugin

### ISSUE THREAD

**Issue by KevinTheGray** [flutter/flutter#12501]
Can't seem to get a project working with both plugins on iOS and Android.  If I remove one or the other I can build and run the project.  

## Steps to Reproduce
add `firebase_database: "^0.1.0"` to `pubspec.yaml`
add `firebase_firestore: "^0.0.1+1"` to `pubspec.yaml`
try to build/run to a device.  haven't tried simulators/emulators but I assume it would be the same issue.

## Logs
on iOS i see
```
duplicate symbol _getQuery in:
        /Users/KG/Developer/Posse/flutterfirestore/flutterfirestore/build/ios/Release-iphoneos/firebase_database/libfirebase_database.a(FirebaseDatabasePlugin.o)
        /Users/KG/Developer/Posse/flutterfirestore/flutterfirestore/build/ios/Release-iphoneos/firebase_firestore/libfirebase_firestore.a(FirestorePlugin.o)
    ld: 1 duplicate symbol for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
on Android
`> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzbco;`

## Flutter Doctor
```
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-US, channel master)
    • Flutter at /Users/KG/Developer/Flutter/flutter
    • Framework revision dc41544793 (29 hours ago), 2017-10-10 12:04:29 -0400
    • Engine revision 459f722b86
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /Users/KG/Library/Android/sdk
    • Platform android-26, build-tools 26.0.2
    • ANDROID_HOME = /Users/KG/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.0, Build version 9A235
    • ios-deploy 1.9.2
    • CocoaPods version 1.2.1

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.0 Preview.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2.5)
    • Flutter plugin version 18.1
    • Dart plugin version 172.4155.35
```

**Comment by mit-mit** [comment]
I suspect this is some kind of version incompatibility; it's a consistent repro for me also (simple `flutter build apk` is enough to repro).

I did try align the Firebase versions by updating `firebase_firestore/android/build.gradle` to:
```
    dependencies {
        compile 'com.google.firebase:firebase-core:11.4.2'
        compile 'com.google.firebase:firebase-firestore:11.4.2'
    }
```

and updating `/firebase_database/android/build.gradle` to:
```
    dependencies {
        compile 'com.google.firebase:firebase-core:11.4.2'
        compile 'com.google.firebase:firebase-auth:11.4.2'
        compile 'com.google.firebase:firebase-database:11.4.2'
    }
```

but then I get a different error:
```
* What went wrong:
Execution failed for task ':app:transformClassesWithDexForRelease'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lio/flutter/plugins/firebase/database/BuildConfig;
```

**Comment by mit-mit** [comment]
cc @collinjackson @kroikie any idea what is going on here?

**Comment by pauldemarco** [comment]
There are some incorrect package names hanging around, still referring to io.flutter.plugins.firebase.database.

The fork here https://github.com/pauldemarco/plugins has them resolved, and I've been adding some missing features that I needed. Note though, I've only had time to implement on the android side.

Added features:
- DocumentReference can now create CollectionReference `collection('users').document('uid1').collection('posts')`
- DocumentReference now has id property.
- Date and Time firestore values now being translated to and from Dart's DateTime, safe to use over platform.
- FieldValue sentinals for delete() and serverTimestamp() implemented
- GeoPoint type created, safe to use over platform.

**Comment by mit-mit** [comment]
Great catch @pauldemarco !

I created a PR for just the package name fix in https://github.com/flutter/plugins/pull/238.

@KevinTheGray the combination of https://github.com/flutter/plugins/pull/238 and https://github.com/flutter/plugins/pull/229 should fix the issue you had.

**Comment by mit-mit** [comment]
@pauldemarco also super exiting to hear about the added features you are working on! Look forward to seeing a PR with those.

**Comment by ArduinoArno** [comment]
I suspect i have that exact same issue with an iOS build right now:
    
**Log from build:**
duplicate symbol _getQuery in:
        /Users/arno/AndroidStudioProjects/flutter-waarnemer/build/ios/Debug-iphonesimulator/cloud_firestore/libcloud_firestore.a(CloudFirestorePlugin.o)
        /Users/arno/AndroidStudioProjects/flutter-waarnemer/build/ios/Debug-iphonesimulator/firebase_database/libfirebase_database.a(FirebaseDatabasePlugin.o)
    ld: 1 duplicate symbol for architecture x86_64
Could not build the application for the simulator.

**flutter doctor:**
[✓] Flutter (on Mac OS X 10.13.1 17B48, locale en-NL, channel alpha)
    • Flutter at /Users/arno/flutter
    • Framework revision e8aa40eddd (3 weeks ago), 2017-10-17 15:42:40 -0700
    • Engine revision 7c4142808c
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at /Users/arno/Library/Android/sdk
    • Platform android-27, build-tools 27.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.1, Build version 9B55
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0.beta.2

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 8.1.0 (API 27) (emulator)
    • iPhone X                  • 9DE45820-B145-491C-8A25-71599CBD8386 • ios         • iOS 11.1 (simulator)

**pubspec.yaml**
dependencies:
  flutter:
    sdk: flutter
  image_picker: "^0.1.1"                                            
  google_sign_in: "^0.3.1"                                          
  firebase_analytics: "^0.0.4"                                      
  firebase_auth: "^0.2.3"                                           
  firebase_database: "^0.0.12"                                      
  firebase_storage: "^0.0.5"                                        
  cloud_firestore: "^0.0.1"

**pods:**
Using BoringSSL (9.1)
Using Firebase (4.5.0)
Using FirebaseAnalytics (4.0.4)
Using FirebaseAuth (4.3.1)
Using FirebaseCore (4.0.10)
Using FirebaseDatabase (4.1.0)
Using FirebaseFirestore (0.9.1)
Using FirebaseInstanceID (2.0.5)
Using FirebaseStorage (2.0.2)
Using Flutter (1.0.0)
Using GTMOAuth2 (1.1.5)
Using GTMSessionFetcher (1.1.12)
Using GoogleSignIn (4.1.1)
Using GoogleToolboxForMac (2.1.3)
Using Protobuf (3.4.0)
Using cloud_firestore (0.0.1)
Using firebase_analytics (0.0.1)
Using firebase_auth (0.0.1)
Using firebase_database (0.0.1)
Using firebase_storage (0.0.1)
Using gRPC (1.7.1)
Using gRPC-Core (1.7.1)
Using gRPC-ProtoRPC (1.7.1)
Using gRPC-RxLibrary (1.7.1)
Using google_sign_in (0.0.1)
Using image_picker (0.0.1)
Using leveldb-library (1.20)
Using nanopb (0.3.8)

**Comment by pulyaevskiy** [comment]
Just started getting this same error with latest dependencies:

```
/MyProject/build/ios/Debug-iphonesimulator/Runner.app/Runner
    duplicate symbol _getQuery in:
        /MyProject/build/ios/Debug-iphonesimulator/cloud_firestore/libcloud_firestore.a(CloudFirestorePlugin.o)
        /MyProject/build/ios/Debug-iphonesimulator/firebase_database/libfirebase_database.a(FirebaseDatabasePlugin.o)
    ld: 1 duplicate symbol for architecture x86_64
```

Pubspec:

```
dependencies:
  flutter:
    sdk: flutter
  google_sign_in: "^2.0.0"
  firebase_auth: "^0.4.0"
  cloud_firestore: "^0.2.0"
  firebase_database: "^0.3.0"
  meta: any
  built_value: "^4.2.1"
  built_redux: "^7.0.0"
  timeago: "^1.2.0"
```

**Comment by kroikie** [comment]
@KevinTheGray

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/954. Any further collaboration will be done there.
