### ISSUE TITLE
When .ci.yaml test was removed in the framework, but not TESTOWNER, there was no validation failure

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#125055]
Seen in https://github.com/flutter/flutter/pull/125044#issuecomment-1513573105.

I think this should have resulted in a validate failure?
https://github.com/flutter/cocoon/blob/4354e68fdd4d12ffb8bd85e545519f9366d46e5e/app_dart/bin/validate_task_ownership.dart

cc @keyonghan

**Comment by ricardoamador** [comment]
ci.yaml is the file that is being checked against the TESTOWNERS file meaning if the test is not in the .ci.yaml file it is not checked against TESTOWNERSHIP which makes sense.  I do not think validating the other way is valuable as we are looking for owners for present tests.
