### ISSUE TITLE
FireStore query support

### ISSUE THREAD

**Issue by bramvbilsen** [flutter/flutter#12509]
First of all, great job making the FireStore plugin available so quickly!
I'd love to start playing around with FireStore, but found that queries weren't implemented yet. Is there any ETA on when this would arrive?

**Comment by Skylled** [comment]
This can be closed.

**Comment by Hixie** [comment]
Great!

**Comment by kroikie** [comment]
@bramvbilsen

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/952. Any further collaboration will be done there.
