### ISSUE TITLE
Timeouts on CI setup steps should be infra failures and not cancelled when step times out

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#125012]
Main build https://ci.chromium.org/p/flutter/builders/prod/Windows%20windows_android_aot_engine/2483 was marked "canceled" which did not close the tree. It timed out waiting for subbuild https://ci.chromium.org/p/flutter/builders/prod/Windows%20Production%20Engine%20Drone/26055.  That subbuild was "canceled" trying to check out source code.

In the dashboard the main build was marked "canceled".  Both the main and subbuild probably should have failed with an infrastructure failure instead of "canceled"
![Screenshot 2023-04-17 at 6 20 19 PM](https://user-images.githubusercontent.com/682784/232644708-64c6655e-f7f3-41a2-99ba-4a33a0625e17.png)
![Screenshot 2023-04-17 at 6 20 58 PM](https://user-images.githubusercontent.com/682784/232644869-57eef00f-2c0d-4085-b0b7-254196498001.png)

However timeouts of test steps should close the tree so we know to investigate.

**Comment by jmagman** [comment]
See https://github.com/flutter/flutter/issues/125037 for why the cancellations are a problem.

**Comment by keyonghan** [comment]
This is affecting engine tree as well, causing new changes keep merged without validating all tests: https://github.com/flutter/flutter/issues/126294
