### ISSUE TITLE
Can't run flutter repo (in China) after cloning flutter repo

### ISSUE THREAD

**Issue by kunalshah** [flutter/flutter#12504]
## Steps to Reproduce

I just cloned flutter repo and then run the flutter command in order to download the all required dependencies. However, dependencies (e.g. dart sdk) can not be downloaded because google servers are blocked in China. It doesn't work with VPN as well! 

Is it possible to download the dependencies from github (instead of google servers), because github works well in China?

Output:

➜  softwares flutter -v
Downloading Dart SDK 1.25.0-dev.11.0...
** Resuming transfer from byte position 3497984
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:43 --:--:--     0
curl: (35) Server aborted the SSL handshake

**Comment by InMatrix** [comment]
Sorry about the inconvenience. We're investigating this issue, but it probably will take us some time to have a solution. Please watch #11681 to monitor progress. In the meantime, I'd suggest you seek help from other Flutter users in China on this forum: http://flutter-dev.cn/bbs/. Thanks!

**Comment by InMatrix** [comment]
Cc: @kevmoo

**Comment by xster** [comment]
I imagine this is fixed now https://github.com/flutter/flutter/wiki/Using-Flutter-in-China
