### ISSUE TITLE
Re-open ListView/ScrollView - Scrolling jumps to the bottom regardless of items on M1 iOS Simulator 

### ISSUE THREAD

**Issue by mafreud** [flutter/flutter#125034]
Though this issue was closed, I am still facing it.

https://github.com/flutter/flutter/issues/79641

```
Flutter: 3.7.11
Dart: 2.19.6
```

Other devs seem to have the same issue.
https://stackoverflow.com/questions/65476069/ios-simulator-scrolls-too-fast-on-apple-m1

**Comment by danagbemava-nc** [comment]
Hi @mafreud, are you using `google_maps_flutter` or any similar plugin that doesn't yet support arm simulators in your project?

**Comment by mafreud** [comment]
Hi @danagbemava-nc . How do I know whether a package supports Apple Silicon or not?

**Comment by danagbemava-nc** [comment]
You can check the podspec file of the plugin for lines similar to the ones shared below

https://github.com/flutter/packages/blob/c6f207ca73ce1bb8bf07d11f0d70e194fea4fc6e/packages/google_maps_flutter/google_maps_flutter_ios/ios/google_maps_flutter_ios.podspec#L25

https://github.com/ponnamkarthik/FlutterToast/blob/5c1dd53eef3b7f8ad4fbe7318e9facfaf621c362/ios/fluttertoast.podspec#L19-L20

**Comment by mafreud** [comment]
@danagbemava-nc Thank you. I will check it out.
