### ISSUE TITLE
It's not easy to match render tree / layer tree with the "Raster Stats" tab in Dev Tools

### ISSUE THREAD

**Issue by moffatman** [flutter/flutter#125019]
The Raster Stats tab shows each layer snapshot named as `Layer x` where `x` is its "unique ID" in the engine. But that ID is not exposed in any way to the flutter framework, so you can't figure out where the snapshot fits in the render tree / layer tree which is printable in the console.

It would be good to see the engine IDs in the layer tree and render tree printout to compare with the raster snapshots.

**Comment by chinmaygarde** [comment]
From Triage: The suggestion was to use the service protocol to get this information.

**Comment by kenzieschmoll** [comment]
This feature has been removed to Dart DevTools due to misleading / inaccurate timing information.
