### ISSUE TITLE
[CP] [Impeller] Remove glyph pixel rounding during text frame conversion

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#125059]
### issue_link

https://github.com/flutter/flutter/issues/124310

### Commit Hash

https://github.com/flutter/engine/commit/b955dc53a93da0d2dfdb4c1bc8f37308e24533dd

### Target

beta

### pr_link

https://github.com/flutter/engine/pull/41304

### Impacted Users

Impeller users

### Impact Description

Addendum to https://github.com/flutter/flutter/issues/124714. Reverts a previous fix that is causing some Skia-shaped text to become misaligned when rendered in Impeller.

### Workaround

No workarounds.

### Risk

low

### Test Coverage

yes

### Validation Steps

Run `Play/AiksTest.TextFrameSubpixelAlignment/Metal` and observe that the individual glyphs are not jumping around separately (see video in https://github.com/flutter/engine/pull/41285).

```
autoninja -C ../out/host_debug_unopt/ -j 1000 flutter/impeller:impeller_unittests && ../out/host_debug_unopt/impeller_unittests --timeout=0 --gtest_filter="Play/AiksTest.TextFrameSubpixelAlignment/Metal" --enable_playground
```

**Comment by jonahwilliams** [comment]
LGTM

**Comment by zanderso** [comment]
CP LGTM
