### ISSUE TITLE
This has been fixed in SkParagraph.

### ISSUE THREAD

**Issue by cj3479** [flutter/flutter#125121]
This has been fixed in SkParagraph.

_Originally posted by @jason-simmons in https://github.com/flutter/flutter/issues/69566#issuecomment-1054871867_
@jason-simmons 

which commit to fix the issue, please give the commit link

**Comment by huycozy** [comment]
Can you please be more specific on this? Does the issue still happen on the latest Flutter channels?
It will be understandable for the effort of finding commits that were merged a long time ago.
