### ISSUE TITLE
Update golden image and unskip `TwoPlatformViewsWithOtherBackDropFilterTests`

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#125167]
This test was skipped in https://github.com/flutter/engine/pull/41341 due to issues with the golden being different when generated on an arm Mac vs Intel Mac.  Figure why they are so different, or just run the scenario tests on ARM since it's getting harder to find developers with ARM Macs to generate these goldens.
Unskip the test when it passes in CI.

cc @jason-simmons

**Comment by cyanglaz** [comment]
If we decide to move the ci to arm machines, it would also be great if we update the simulators to use iPhone SE 16.2 at the same time.

See: https://github.com/flutter/flutter/issues/125227#issuecomment-1516969439

**Comment by cyanglaz** [comment]
testing on arms have been already enabled in ci, but the tests are not running. The tests will start to run on arm machines when https://github.com/flutter/flutter/issues/125273 is resolved.

**Comment by cyanglaz** [comment]
The RMSE between the image generated from intel and arm machine is reported to be around 0.56 per @jason-simmons 

To ensure both intel and arm machines run this test, I can see that we would have 2 options:
1. Increase the RMSE threshold to 0.6 so both types of machines can pass using the same golden image. I'm not sure how much of difference is 0.5 vs 0.6. Theoretically, this lowers the bar for the tests to pass, which might let some minor bug going through. Thoughts? @gaaclarke 
2. Having 2 sets of goldens, 1 for arm and 1 for intel, keep the threshold for both to 0.5. This doesn't have the potential issue from option 1 but increase the maintenance burden. Anyone who updates the goldens will require owning both machines. Most of the developers don't own both machines, so I don't think it is the preferred way to go.

**Comment by keyonghan** [comment]
> testing on arms have been already enabled in ci, but the tests are not running. The tests will start to run on arm machines when https://github.com/flutter/flutter/issues/125273 is resolved.

The tracking issue should not be a blocker here and all bots have been in a good state now. Let me know if you notice any weird behavior.

**Comment by gaaclarke** [comment]
> Increase the RMSE threshold to 0.6 so both types of machines can pass using the same golden image. I'm not sure how much of difference is 0.5 vs 0.6. Theoretically, this lowers the bar for the tests to pass, which might let some minor bug going through. Thoughts? @gaaclarke

If it gets us moving, I think that sounds fine.   I think these golden image tests should be migrated to Skia Gold though.  I've recently done it for impeller so I can guide the iOS team if they want to.  (cc @jmagman). Skia Gold will let you keep multiple golden images to check against.  Skia Gold is far from perfect but the more usage it gets, hopefully the more momentum to improve it will get.
