### ISSUE TITLE
Flutter release build fails on force pushes due to stale content

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#125159]
See https://ci.chromium.org/ui/p/dart-internal/builders/flutter/Linux%20flutter_release/5/overview

```
! [rejected]              HEAD -> stable (stale info)
```

The expectation is that this would force push to the branch.

**Comment by CaseyHillers** [comment]
I sent https://flutter-review.googlesource.com/c/recipes/+/43480 to revert this back to force

**Comment by sealesj** [comment]
Thank you for sending that, approved
