### ISSUE TITLE
Make `FutureBuilder.future` Required

### ISSUE THREAD

**Issue by caseycrogers** [flutter/flutter#125188]
## Use case

1. I create a future builder
2. I write the contents of `builder`
3. I forget to provider a `future`
4. I run my app and the future builder never receives data
5. I waste time debugging only to realize the simple mistake

In a toy example, step 5 is very fast. But if I've made a ton of changes at once in many places (eg a large refactor) step 5 can easily take several minutes. And if I'm using `FutureBuilder` heavily, this coding error can happen fairly often.

## Proposal

Make `future` a required constructor argument.
In the (non-existent???) case where a developer intentionally didn't pass a variable (null or otherwise) for `future`, they can instead just write `future: null`.
In the typical case where a developer did intend to provide a variable, they will now get a compiler warning if they forget (and/or they'll never forget in the first place because their IDE auto-generates required arguments).

```dart
  const FutureBuilder({
    super.key,
    this.initialData,
    required this.future,
    required this.builder,
  }) : assert(future != null), assert(builder != null);
```

Also, by the exact same logic, `StreamBuilder.stream` should be a required argument too.

**Comment by danagbemava-nc** [comment]
Hi @caseycrogers, I believe this is the same issue as https://github.com/flutter/flutter/issues/83081. 

Kindly follow up in the issue linked above for updates. 

Closing from here as duplicate. If you disagree, kindly leave a comment below and I will reopen this. 

Thank you

**Comment by caseycrogers** [comment]
I'd suggest keeping this bug open for two reasons:
1. It is more concise meaning it's more likely to get traction
2. The other issue is subtly different. It focuses around the values being non-null. This issue is much less of a breaking change-it simply proposes that `future` be required (regardless of whether or not it is null)
