### ISSUE TITLE
[camera] Some mobile phone recorded videos have formatting issues

### ISSUE THREAD

**Issue by git-boya** [flutter/flutter#125185]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

camera: ^0.10.3
mobile: iPhone se2/iOS 16.4.1

The recorded video has been recognized as audio in some browsers.
this is a video:

https://user-images.githubusercontent.com/17589102/233264332-d4a853dc-ac98-46db-9c92-6dc605873ebe.mp4

i use ffmpeg -i print video information: audio stream is #0:0, video stream is #0:1
![image](https://user-images.githubusercontent.com/17589102/233264683-769cbac9-c07f-455d-bf13-3fdeb0c1a282.png)

### Actual results

The recorded video has been recognized as audio in some browsers.
for example: Chromium version < 86

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.11, on macOS 13.3.1 22E261 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 3.7.11 on channel stable at /Users/ieducc/develop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f72efea43c (8 days ago), 2023-04-11 11:57:21 -0700
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/ieducc/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 79B21A4A-5B47-4DF8-94B8-20386F071EC8 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • macOS 13.3.1 22E261 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 112.0.5615.121

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @git-boya 

>The recorded video has been recognized as audio in some browsers.

Can you be more specific on this? Are you checking the output video with `ffmpeg` CLI or somehow? 

And please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that help to reproduce this issue so that others can check the issue as well. Thank you!
