### ISSUE TITLE
flutter/engine@3.7.11 shares no commit history with flutter/engine@3.7.10 or flutter/engine@master

### ISSUE THREAD

**Issue by eseidel** [flutter/flutter#125180]
flutter/engine@3.7.11 shares no commit history with flutter/engine@3.7.10 or flutter/engine@master

Maybe I'm doing the git commands wrong?  It seems like 3.7.11 is pushed from some fork?  If true, does that mean 3.7.11 is bloating the size of the git repo?

```
eseidel@erics-mbp upstream_engine % git merge-base 3.7.9 main 
ec5de9b810ef0cde91cece0a23ee8517fd40a880
eseidel@erics-mbp upstream_engine % git merge-base 3.7.10 main
ec5de9b810ef0cde91cece0a23ee8517fd40a880
eseidel@erics-mbp upstream_engine % git merge-base 3.7.11 main
eseidel@erics-mbp upstream_engine % echo $?
1
```

It's almost as though 3.7.11 was pushed from some fork with different commit ids?

**Comment by eseidel** [comment]
It looks like `origin/stable` and `3.7.11` in the flutter/engine repo are actually copies of flutter/fluter?

Am I reading that right? @zanderso @CaseyHillers?

**Comment by eseidel** [comment]
Examples:
https://github.com/flutter/engine/tree/stable
https://github.com/flutter/engine/tree/3.7.11

**Comment by CaseyHillers** [comment]
You're right. Last week's release had a bug in adding the engine tagging (bash is hard).

This week's https://github.com/flutter/engine/tree/3.7.12 is correct. If possible, I recommend upgrading to 3.7.12 if possible, or excluding 3.7.11 from your pipelines.

There's not an easy way for us to handle this, and we suspect deleting the tag will cause more issues than it will solve.

If you're interested, I'm happy to delete the engine 3.7.11 tag if it's causing issues.

**Comment by eseidel** [comment]
I can work around this myself, for sure.  But I think you also may just want to delete the offending tags (I don't believe you can edit tags without breaking things) and let the garbage collector eventually make all future checkouts of flutter/engine be 100s of megabytes smaller. :)

**Comment by eseidel** [comment]
Oh, I should be clear, it's not just a tag.  There is also a branch https://github.com/flutter/engine/tree/stable which contains flutter/flutter. :). Note the unexpected "engine" in that branch url!

My guess is that the right resolution is to list all heads in the repo and nuke any which refer to flutter/flutter. (A quick way might be to list all heads and run merge-base against main).  I don't know the git commands off the top of my head for such, but I'm sure it's possible.

**Comment by CaseyHillers** [comment]
I've gone ahead and deleted beta|stable from engine. As a one off, I deleted the branches as well via the GitHub UI. Long term fix is in https://flutter-review.googlesource.com/c/recipes/+/42221.

I've gone ahead and deleted the 3.7.11 tag from engine. Thanks @eseidel for reporting this!

**Comment by eseidel** [comment]
I have no objection to beta/stable existing in engine (so long as they point to engine cis), that's really all your call as to what you wish to expose there.

Thank you for deleting the bad tag, hopefully that's the last flutter/flutter head in engine?  If it's not, engine will still contain all the Flutter commit blobs until the last head is pruned. :)
