### ISSUE TITLE
When pressing back on Android Samsung browser, it does not go to the previous page within the web app.

### ISSUE THREAD

**Issue by imjjmoa** [flutter/flutter#125184]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Go to 'https://flutter.github.io/samples/gallery.html'
2. Click on 'Launch App' and go to 'https://gallery.flutter.dev/'
3. Click on 'Material > App bar' and go to  'https://gallery.flutter.dev/#/demo/app-bar'
4. Press the back button on the Android navigation bar to go to the previous page.

### Expected results

Go back to 'https://gallery.flutter.dev/'
(In android Chrome browser, it works as above)

(WillPopScope, onWillPop() work.)

### Actual results

Leave the flutter page and go back to 'https://flutter.github.io/samples/gallery.html'.

(WillPopScope, onWillPop() doesn't seem to work.)

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![KakaoTalk_Image_2023-04-20-14-06-34_001](https://user-images.githubusercontent.com/38598865/233263645-6d1875d8-fd74-441a-9919-fc4f63753b7e.png)
![KakaoTalk_Image_2023-04-20-14-06-34_002](https://user-images.githubusercontent.com/38598865/233263652-0ce7c668-4182-48de-a39f-d0cca6c41f04.png)

<Press backbutton>
![KakaoTalk_Image_2023-04-20-14-06-34_003](https://user-images.githubusercontent.com/38598865/233263671-053d9f41-de12-45cf-be38-8498c5a7e74a.png)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.10, on macOS 13.0 22A380 darwin-arm64, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

</details>

**Comment by imjjmoa** [comment]
I'm missing one screenshot, so I'm attaching it again. In the 2nd screenshot, when I press back, it doesn't take me to the previous page ('https://gallery.flutter.dev/') within the webapp, it takes me out of the webapp altogether, as shown in the following photo.

![KakaoTalk_Image_2023-04-20-14-06-34_003](https://user-images.githubusercontent.com/38598865/233264713-35e91031-16f8-4682-854c-72107d67a093.png)

**Comment by huycozy** [comment]
Hi @imjjmoa 
This looks like a Gallery's issue. Please open the issue there for better support. See [gallery repository issue](https://github.com/flutter/gallery/issues).

Closing, as this isn't an issue with Flutter itself. If you disagree and think this issue belongs to Flutter framework, please provide a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and I will reopen it for further discussion. Thank you!

**Comment by imjjmoa** [comment]
> Hi @imjjmoa This looks like a Gallery's issue. Please open the issue there for better support. See [gallery repository issue](https://github.com/flutter/gallery/issues).
> 
> Closing, as this isn't an issue with Flutter itself. If you disagree and think this issue belongs to Flutter framework, please provide a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and I will reopen it for further discussion. Thank you!

To clarify, the issue is not with the Gallery, but with the WillPopScope widget's onWillPop() not working.
I created a sample page with Flutter Web, and it looks like this

Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: () async => false,
      child: Scaffold(),
    );
  }

Then, when you press the back button, the back action is not executed in the case of Chrome browser. On the other hand, the above code does not work in Samsung browser.

**Comment by huycozy** [comment]
I re-open the issue for further discussion. Can you please provide a complete and minimal sample code for this case?

**Comment by huycozy** [comment]
Thanks for the sample code. It looks like this is caused by `Block backward redirections` setting on Samsung Internet browser. Please try turning off it to see if it works (Menu > Privacy > Block backward redirections)

<img width="400" src="https://user-images.githubusercontent.com/104349824/233911830-13757504-1559-4674-b42b-bf33e1415e86.png">

**Comment by imjjmoa** [comment]
Thank you. It's a Samsung browser issue.
