### ISSUE TITLE
Unable to rerun dashboard integration test

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#125171]
A task on the dashboard failed, and I received an error toast when I tried to rerun it.
The task was Windows tools_integration_tests 5_6
Logs: https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20tool_integration_tests_5_6/7182/overview

Error: 
![image](https://user-images.githubusercontent.com/16964204/233217827-4c14fcc6-0e53-44a3-988d-5d7c754da900.png)

I think the failure is a flake, but since I cannot rerun the task, I cannot fix the tree. We have to wait until the commit above it runs.

**Comment by keyonghan** [comment]
By any chance you had logged in when rerunning the task?

**Comment by Piinks** [comment]
Yup. Can confirm I was logged in - or at least my picture was present in the top corner

![image](https://user-images.githubusercontent.com/16964204/233218901-935d2313-071d-419b-95a0-0de6f63c47f0.png)

**Comment by keyonghan** [comment]
Is this related to the recent google sign in button change? /cc @ricardoamador @ditman

**Comment by keyonghan** [comment]
I tried clicking `rerun` on a failed task, it works. @Piinks could you try refreshing your page to give it a shot?
I am lowering the priority as the newer commit is running the failed task, and the `rerun` here is not a blocker to all.

**Comment by ricardoamador** [comment]
@keyonghan It could be but I don't think so. @Piinks can you clear your browser data for the dashboard? I see a few requests resulting in an invalid token which might be you? But I do see a successful request for a different task which I believe was keyongs.

**Comment by ricardoamador** [comment]
I was able to rerun that task without issue.

**Comment by ditman** [comment]
The current version of the plugin does *not* detect when the user session expires, and that's possibly what was happening to @Piinks (and also why others can't reproduce).

A better solution would be to monitor the http errors coming from these attempts, and simulating the user being "signed out".

@Piinks a fast workaround for this is for you to do a full-page reload so the sign in plugin realizes that your session is expired and either re-logins you, or prompts you to push the button.

I'll try to add the "auto sign-out" feature to Cocoon this friday!

**Comment by Piinks** [comment]
Can confirm, I did a hard reload of the page and was able to rerun a task. I wasn't prompted to log in again, but it worked. :)

**Comment by Piinks** [comment]
I did not notice a card anywhere when I refreshed

**Comment by ditman** [comment]
Working on this right now.

**Comment by ditman** [comment]
The dashboard will now disable a couple of actions if it detects that they can't be performed (RERUN and "Refresh GitHub Commits"). This is informed by the server returning an error to the request.

So in @Piinks case, what she would have seen after my latest change is the "RERUN" button getting disabled after her first (failed) attempt, and the Google Sign In button appearing on the top nav-bar for her to re-login. A full page reload, would re-authenticate her as well.

**Comment by Piinks** [comment]
Thank you! 🎉
