### ISSUE TITLE
Unable to parse `PurchaseWrapper` using `originalJson`

### ISSUE THREAD

**Issue by tkshnwesper** [flutter/flutter#125135]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Paste the code in the **Code sample** inside a purchase stream listener where you iterate over the list of `PurchaseDetails`.
2. Trigger Google Play purchase.

### Expected results

Based on my understanding, the `originalJson` should get parsed by `PurchaseWrapper`. Not sure if there is any other way to serialize and parse `PurchaseDetails`.

### Actual results

The `originalJson` has an `autoRenewing` field not an `isAutoRenewing` field. However, the `PurchaseWrapper` tries to read an `isAutoRenewing` fields from the map. [Relevant code](https://github.com/flutter/packages/blob/main/packages/in_app_purchase/in_app_purchase_android/lib/src/billing_client_wrappers/purchase_wrapper.g.dart#L18). Error occurs because no default value is set.

Sample `originalJson`:
```json
{
    "orderId": "GPA.1230-6498-2301-93021",
    "packageName": "com.package.name",
    "productId": "product_id",
    "purchaseTime": 1681906581244,
    "purchaseState": 0,
    "purchaseToken": "purchase_token_xyz",
    "quantity": 1,
    "autoRenewing": true,
    "acknowledged": false
}
```

Same with `isAcknowledged` field. But in the case of `isAcknowledged`, there is a default value, so no error is thrown. [Relevant code](https://github.com/flutter/packages/blob/main/packages/in_app_purchase/in_app_purchase_android/lib/src/billing_client_wrappers/purchase_wrapper.g.dart#L21).

### Code sample

<details><summary>Code sample</summary>

```dart
GooglePlayPurchaseDetails googlePlayPurchaseDetails = purchaseDetails;
final json = googlePlayPurchaseDetails.billingClientPurchase.originalJson;

final decodedJson = jsonDecode(json);
final purchaseDetails = GooglePlayPurchaseDetails.fromPurchase(
	PurchaseWrapper.fromJson(decodedJson));
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![image](https://user-images.githubusercontent.com/7362366/233077870-099a2616-0a8b-44ce-af36-a9911cfa339c.png)

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.11, on macOS 12.6.4 21G526 darwin-x64, locale en-IN)
    • Flutter version 3.7.11 on channel stable at /Users/<redacted>/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f72efea43c (8 days ago), 2023-04-11 11:57:21 -0700
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/<redacted>/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)         • macos         • darwin-x64     • macOS 12.6.4 21G526 darwin-x64
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 112.0.5615.121

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @tkshnwesper 



> The `originalJson` has an `autoRenewing` field not an `isAutoRenewing` field. However, the `PurchaseWrapper` tries to read an `isAutoRenewing` fields from the map. [Relevant code](https://github.com/flutter/packages/blob/main/packages/in_app_purchase/in_app_purchase_android/lib/src/billing_client_wrappers/purchase_wrapper.g.dart#L18). Error occurs because no default value is set.

What error occurs if you use `isAutoRenewing` field ? I think this is the field expected, something like:

```
PurchaseWrapper billingClientPurchase = purchase.billingClientPurchase;
    
    if (!billingClientPurchase.isAutoRenewing) {
      // Subscription is cancelled and will not renew when it expires. You should still deliver/ enable the content.
    }
```



> Not sure if there is any other way to serialize and parse `PurchaseDetails`.

For this, check if [this](https://github.com/flutter/flutter/issues/83342) issue and underlying comments help in your case.

**Comment by tkshnwesper** [comment]
Hi @darshankawar , thank you for your response.

> What error occurs if you use `isAutoRenewing` field ?

The error occurs before I get to use the field, while parsing the json:

![error text](https://user-images.githubusercontent.com/7362366/233077870-099a2616-0a8b-44ce-af36-a9911cfa339c.png)

For context on why I am doing this:

1. When `List<PurchaseDetails>` come through `.purchaseStream`, I serialize the `PurchaseDetails` objects and store them on my server. This is done to recover the object later, in case the user closes the app before entitlements are granted.
	```dart
	GooglePlayPurchaseDetails googlePlayPurchaseDetails = purchaseDetails;
	final json = googlePlayPurchaseDetails.billingClientPurchase.originalJson;
	// upload `json` to server
	```
2. Once entitlements are granted, the app recreates the `PurchaseDetails` object from the serialized object stored on the server and calls `.completePurchase`.
	```dart
	// download `json` from server
	// ...
	final decodedJson = jsonDecode(json);
	final purchaseDetails = GooglePlayPurchaseDetails.fromPurchase(
		PurchaseWrapper.fromJson(decodedJson));
	InAppPurchase.instance.completePurchase(purchaseDetails);
	```

The issue that you linked describes another way of retrieving `PurchaseDetails` of past purchases, however, what I am attempting should also technically work if my understanding is correct.

Here's a [snippet](https://github.com/DimaDake/billing/blob/master/library/src/main/java/com/android/billingclient/api/Purchase.java#L68) from billing library's source code someone uploaded

```java
  public boolean isAutoRenewing() {
    return mParsedJson.optBoolean("autoRenewing");
  }
```

In the above snippet, they parse `autoRenewing`, not `isAutoRenewing`.

However, `isAutoRenewing` is being parsed in the in_app_purchase's wrapper over Android billing client. See [code](https://github.com/flutter/packages/blob/main/packages/in_app_purchase/in_app_purchase_android/lib/src/billing_client_wrappers/purchase_wrapper.g.dart#L18).

```dart
PurchaseWrapper _$PurchaseWrapperFromJson(Map json) => PurchaseWrapper(
	  // ...
      isAutoRenewing: json['isAutoRenewing'] as bool,
	  // ...
    );
```

The actual `originalJson` has `autoRenewing` field, so in_app_purchase's Android wrapper will not be able to parse it. In fact, it throws an error because no default value is set (see above code).

```json
{
    "autoRenewing": true,
    "acknowledged": false
}
```

The wrapper actually creates a hash map from billing client's `Purchase` object ([code](https://github.com/flutter/packages/blob/main/packages/in_app_purchase/in_app_purchase_android/android/src/main/java/io/flutter/plugins/inapppurchase/Translator.java#L70)) before sending it across platform channels:

```java
  static HashMap<String, Object> fromPurchase(Purchase purchase) {
    HashMap<String, Object> info = new HashMap<>();
	// ...
    info.put("isAutoRenewing", purchase.isAutoRenewing());
	// ...
    return info;
  }
```

To summarize,

1. `originalJson` is parsed by the billing client on android to create a `Purchase` object ([code](https://github.com/DimaDake/billing/blob/master/library/src/main/java/com/android/billingclient/api/Purchase.java#L19))
2. `Purchase` object is converted to `HashMap` and sent to Flutter via platform channels ([code](https://github.com/flutter/packages/blob/main/packages/in_app_purchase/in_app_purchase_android/android/src/main/java/io/flutter/plugins/inapppurchase/Translator.java#L59))
3. `HashMap` is parsed to a `PurchaseWrapper` ([code](https://github.com/flutter/packages/blob/main/packages/in_app_purchase/in_app_purchase_android/lib/src/billing_client_wrappers/purchase_wrapper.g.dart#L9))
4. `PurchaseWrapper` is used to create `GooglePlayPurchaseDetails` ([code](https://github.com/flutter/packages/blob/main/packages/in_app_purchase/in_app_purchase_android/lib/src/types/google_play_purchase_details.dart#L26))

The problem happens in **Step 3** because `PurchaseWrapper` tries to parse `isAutoRenewing` and breaks compatibility with `originalJson`.

**Comment by tkshnwesper** [comment]
I've made a PR to highlight the changes required:
https://github.com/flutter/packages/pull/3765

**Comment by stuartmorgan** [comment]
> Based on my understanding, the `originalJson` should get parsed by `PurchaseWrapper`.

This is not correct; `originalJson` is the JSON of the underlying purchase, and corresponds to https://developer.android.com/reference/com/android/billingclient/api/Purchase#getOriginalJson(). It is not the JSON serialization of the Dart `PurchaseWrapper` object.

> Not sure if there is any other way to serialize and parse `PurchaseDetails`.

There is no public API that will give you a persistable version of `PurchaseDetails`; `fromJson` is an implementation detail, and is not intended for persistence. If you want to persist and recreate `PurchaseDetail` objects you should do so via your own code, in a format you control.

Closing as the premise of the issues is incorrect.
