### ISSUE TITLE
CupertinoDatePicker: add itemExtent as a parameter

### ISSUE THREAD

**Issue by lorenzOliveto** [flutter/flutter#125127]
## Use case

We're using the  CupertinoDatePicker to let user select a date, the problem that we're facing at the moment is that our app needs to be completely accessible, so the text needs to resize accordingly to the users' settings.

When the text becomes too big (setting the `dateTimePickerTextStyle` in the `CupertinoTheme`) the CupertinoDatePicker clips it.

| a11y settings  | CupertinoDatePicker |
| ------------- | ------------- |
| ![Simulator Screenshot - iPhone 14 Pro Max - 2023-04-19 at 12 42 32](https://user-images.githubusercontent.com/3470464/233051397-ee83ec3b-002b-4288-9ef8-4e84ba11bd84.png) | ![Simulator Screenshot - iPhone 14 Pro Max - 2023-04-19 at 12 42 37](https://user-images.githubusercontent.com/3470464/233051482-a616d057-9b97-4a9f-97fb-e515abc1e580.png)  |

## Proposal

The proposal is to add the optional parameter `itemExtent`, as we already have in `CupertinoPicker`,  with the default value of 32 (the current value used as `_kItemExtent`) so we can increase it when the `MediaQuery.of(context).textScaleFactor` increases.

**Comment by k3ny-dg** [comment]
Hi, 

Were you planning on fixing this issue yourself, or is it open for someone else to resolve? 

Thanks!

**Comment by lorenzOliveto** [comment]
Hi, leaving it open for someone else since I have not much time to work on it ATM.
I'll be happy to work on it when I have more time available.
