### ISSUE TITLE
Flutter doctor not responding

### ISSUE THREAD

**Issue by xiushu53** [flutter/flutter#125179]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Downloa Flutter on "docs.flutter.dev/get-started/install/macos"
2. Make development directory
3. " cd development"
4. "unzip 〜/Downloads/flutter_macos_3.7.12-stable.zip"
5. Set the path 'export PATH="$PATH:/Users/MyAcount/development/flutter/bin' in 〜/.zshrc
6. Check the path "which flutter", then output "/Users/MyAcount/development/flutter/bin/flutter"
7. Run "flutter doctor --verbose"
8. But not resonsing…

**Description**:
I am trying to install Flutter on my Intel Macbook. I have followed the instructions on the Flutter website, but when I run `flutter doctor`, I get no response.

**Info**

- MacBookPro: 16-inch, 2019, Intel Corei7
- OS: MacOS Ventura 13.3.1
- Flutter: 3.7.12 

### Actual results

I get no response.

**troubleshooting**

I have tried the following troubleshooting steps:

- Disabling my firewall
- Using the correct version of Flutter
- Setting my path variables correctly
- Reinstalling Flutter and old version(3.0.0) too

I am still having the same problem.

No flutter-related log files were generated in the /var/log directory.

II hope this information is helpful. Thank you for your time.

### Logs

None

### Flutter Doctor output

None

**Comment by xiushu53** [comment]
Thank you, @darshankawar 

I checked the output by running `echo $PATH` and the same with `which flutter`.

I set the path in the `$HOME/.zshrc` file, run `source $HOME/.zshrc` and restart.

I also tried running `.../bin/fultter doctor` directly from the flutter file, not from the configured PATH, with the same result (it starts, but no further response).

In addition, I downloaded the git repo instead of the SDK and tried to install it, but when running `flutter precahe`, after downloading the relevant files, the `Building flutter tool... ` just kept showing up, and there was no response even after waiting for about 30 minutes. Then, when I interrupted the run, I got `Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)`.

**Comment by darshankawar** [comment]
> `Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)`.

This probably indicates a network related error. Can you confirm if you have a stable / fast network connection ?
Alternatively, check if it could be occurring due to local intermittent DNS issue or not.

**Comment by xiushu53** [comment]
Thank you, @darshankawar , for your sound advice.

I have tried. I was then able to successfully download the flutter tools by forcing the `webfilterproxyd` MacOS process to terminate.
I was then able to complete the `flutter doctor` run.

Thank you very much for your response to this issue.

**Comment by darshankawar** [comment]
Good to know your issue is resolved. Closing based on above comment.
