### ISSUE TITLE
Facing issue with Ignorepointer with Webview

### ISSUE THREAD

**Issue by anurag13mo** [flutter/flutter#125284]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Wrap your Webview widget with ignorepointer and observe the behaviour. In my case i can touch the webview even after setting ignoring to true. It is only observed in IOS.

### Expected results

I shouldn't be able to interact the webview if ignoring set to true.

### Actual results

I can interact with the webview.

### Code sample

IgnorePointer(
ignoring:true,
child:InAppWebview()
)

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code (version 1.77.3)
    • VS Code at C:\Users\Anurag.Mohapatra\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.62.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1555]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 112.0.5615.121
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 112.0.1722.48

[√] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by darshankawar** [comment]
@anurag13mo 


> gnorePointer(
> ignoring:true,
> child:InAppWebview()
> )

This seems to be pointing to https://pub.dev/packages/flutter_inappwebview which is third party package. 
Also, for Flutter's first party package `webview_flutter`, there's already a similar issue open describing your case: https://github.com/flutter/flutter/issues/30143 in which you can follow-up for further updates.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.
