### ISSUE TITLE
[image_picker][ios] No picture added when selecting the last picture in gallery

### ISSUE THREAD

**Issue by gipson1001** [flutter/flutter#125222]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. use _picker.pickMultiImage() to open image picker
2. select the last picture in the gallery, then nothing happens

### Expected results

The selected picture should be returned as XFile obj

### Actual results

Nothing happens

### Code sample

<details><summary>Code sample</summary>

```dart
        List<XFile> files = await _picker.pickMultiImage(
            maxHeight: 2048, maxWidth: 2048, requestFullMetadata: false);
        if (files != null && files.length > 0) {
          List<Uint8List> list = [];
          for (XFile item in files) {
            list.add(await item.readAsBytes.call());
          }
          showAddDialog(list);
        }
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
>maxHeight: 2048, maxWidth: 2048, requestFullMetadata: false

I try picking the last picture in the Gallery with the same configuration on [plugin sample code](https://github.com/flutter/packages/tree/main/packages/image_picker/image_picker/example) but it works as expected without issue. What is your device information? (OS, model) and does the issue only happen with this configuration? 

Please add more information that will help to address the issue properly. Thanks!

**Comment by gipson1001** [comment]
I'm using old dart and flutter.

Flutter 3.3.10 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 135454af32 (4 months ago) • 2022-12-15 07:36:55 -0800
Engine • revision 3316dd8728
Tools • Dart 2.18.6 • DevTools 2.15.0

**Comment by huycozy** [comment]
Which image_picker version are you using? Does the issue happen on the latest version `image_picker: ^0.8.7+3`? 
And what is the affected device (OS, model)?
