### ISSUE TITLE
Engine -> framework roll failing on cocoon pixel tests

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#125213]
https://github.com/flutter/flutter/pull/125210

cc @CaseyHillers cc sheriff @chinmaygarde

**Comment by Hixie** [comment]
These tests are catching bugs when we break our rendering, something I think is very valuable.

What is the change this in this particular case? Antialiasing?

**Comment by Hixie** [comment]
We've rolled since this issue was filed (tests were temporarily disabled and just got re-enabled).

cc @jason-simmons
