### ISSUE TITLE
SwiftCompiler

### ISSUE THREAD

**Issue by Brusadze** [flutter/flutter#125288]
### Is there an existing issue for this?

- [x] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Hi, im trying to run my app to ios simulator and im getting this error:

Swift Compiler Error (Xcode): Cannot call value of non-function type 'String?'
/Users/sopho/Dev/Tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.7.2+3/ios/C
lasses/MyCookieManager.swift:293:43

it runs perfectly on android simulator. im not using any inapwebview in my app, any ideas?

thanks

### Actual results

Swift Compiler Error (Xcode): Cannot call value of non-function type 'String?'
/Users/sopho/Dev/Tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.7.2+3/ios/C
lasses/MyCookieManager.swift:293:43

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by danagbemava-nc** [comment]
If you are not using flutter_inappwebview directly then it is likely a dependency of one of your packages. See https://github.com/pichillilorenzo/flutter_inappwebview/issues/1376

Closing from here as this is not a flutter issue. 

Thank you
