### ISSUE TITLE
Suggestion for scrolling options

### ISSUE THREAD

**Issue by MaxYablochkin** [flutter/flutter#125294]
#91605

Will there be scrolling in Flutter as in the first example? 

Both scrolls are native (from XML), but the difference is that the first scroll resets to its original position when you change your finger direction, thus not following your finger to return to the original position. The second scroll, on the contrary, follows the user's finger, like in Flutter.

https://user-images.githubusercontent.com/102767277/233617515-3c86e913-388c-4588-a3ed-0bd46314687b.mp4

https://user-images.githubusercontent.com/102767277/233617919-d6604cd2-9bc8-4660-9c21-0bfb9557f5c4.mp4

**Comment by darshankawar** [comment]
Thanks for the report @MaxYablochkin 
Sounds like you are looking to propose enhancement in current scrolling feature for M3. If so, can you please elaborate on your proposal with respect to current vs expected scrolling mechanism ?

**Comment by MaxYablochkin** [comment]
👋 @darshankawar 
I only opened this issue for the purpose of asking about scrolling.

**Comment by darshankawar** [comment]
Ok, can you take a look at [this](https://github.com/flutter/flutter/issues/116782) and see if it helps to answer your question ?
