### ISSUE TITLE
Dart SDK not found on OSX

### ISSUE THREAD

**Issue by puleen** [flutter/flutter#12522]
```
[/Users/puleen/Projects/flutter/bin/cache/dart-sdk.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /Users/puleen/Projects/flutter/bin/cache/dart-sdk.zip or
        /Users/puleen/Projects/flutter/bin/cache/dart-sdk.zip.zip, and cannot find /Users/puleen/Projects/flutter/bin/cache/dart-sdk.zip.ZIP, period.
```

**Comment by cbracken** [comment]
Thanks for reporting! I've updated the report for formatting. 

Looks like the dart-sdk.zip file is somehow corrupt. In this case we should probably detect the failure, delete the corrupt archive and retry.

As a workaround, would you mind trying the following to see if it fixes the issue for you?
```
rm -rf /Users/puleen/Projects/flutter/bin/cache
```

then re-run `flutter doctor`.

**Comment by puleen** [comment]
I ended up setting up flutter all over again today and did not experience the same issue again.

**Comment by cbracken** [comment]
Thanks for confirming. Sounds like we should detect this situation and provide a more useful error message and perhaps prompt the user to check if they'd like us to try re-downloading and installing the SDK and other cached components.
