### ISSUE TITLE
(Pop_! OS/Ubuntu) flutter_tools depends on test 1.22.0 which doesn't match any versions,   version solving failed.

### ISSUE THREAD

**Issue by bakaemon** [flutter/flutter#125252]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Install Flutter from snap (or download the repo)
2. Run flutter doctor

### Expected results

It should just show the output of regular flutter doctor.

### Actual results

```
Running "flutter pub get" in flutter_tools...
Resolving dependencies in ../snap/flutter/common/flutter/packages/flutter_tools... 
Because flutter_tools depends on test 1.22.0 which doesn't match any versions,
  version solving failed.
pub get failed
command: "/home/bakaemon/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart
__deprecated_pub --color --directory
../snap/flutter/common/flutter/packages/flutter_tools get --example"
pub env: {
  "FLUTTER_ROOT": "/home/bakaemon/snap/flutter/common/flutter",
  "PUB_ENVIRONMENT": "flutter_cli:get",
  "PUB_CACHE": "/home/bakaemon/.pub-cache",
}
exit code: 1



#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      _DefaultPub._runWithStdioInherited
(package:flutter_tools/src/dart/pub.dart:468:7)
<asynchronous suspension>
#2      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:346:5)
<asynchronous suspension>
#3      PubDependencies.update
(package:flutter_tools/src/flutter_cache.dart:125:5)
<asynchronous suspension>
#4      Cache.updateAll (package:flutter_tools/src/cache.dart:677:9)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:1376:7)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#12     run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>

```

### Code sample

None

### Flutter Doctor output

None

**Comment by huycozy** [comment]
Hi @bakaemon 
Does this issue happen on a newly created Flutter project? And can you confirm you have already done all steps from Flutter install guideline [here](https://docs.flutter.dev/get-started/install/linux)?

**Comment by bakaemon** [comment]
> Hi @bakaemon 
> Does this issue happen on a newly created Flutter project? And can you confirm you have already done all steps from Flutter install guideline [here](https://docs.flutter.dev/get-started/install/linux)?

If anything I can assure you, is that this is my sixth time setup Flutter on a machine. This has become my routine to setup and I haven't encounter any problem until now.

**Comment by huycozy** [comment]
Just curious, I wonder why you need to re-install Flutter? Was it successful last time? If so, what was the previous version?

**Comment by bakaemon** [comment]
I just a distro hopper, that's all.

**Comment by huycozy** [comment]
Can you check if the issue also happens when [installing Flutter manually](https://docs.flutter.dev/get-started/install/linux#install-flutter-manually)?

**Comment by robertlindsey224** [comment]
I have the same issues, Has anyone been able to fix it?

**Comment by bakaemon** [comment]
@robertlindsey224 hey confidentially I just able to get it fixed this morning by delete the hidden flutter folder on home user folder. It seems the old config or whatever causing the error in the first place was there.

**Comment by robertlindsey224** [comment]
Where is this folder located?

**Comment by robertlindsey224** [comment]
> @robertlindsey224 hey confidentially I just able to get it fixed this morning by delete the hidden flutter folder on home user folder. It seems the old config or whatever causing the error in the first place was there.

Where can I find the folder to be deleted?

**Comment by huycozy** [comment]
@robertlindsey224 You can try several ways to find hidden folders (see [this](https://www.makeuseof.com/view-hidden-files-and-folders-linux/)).

@bakaemon Given your last message, I feel safe to close this issue as solved.

**Comment by robertlindsey224** [comment]
The flutter file is not in my Users folder, and my OS is Windows

**Comment by bakaemon** [comment]
> The flutter file is not in my Users folder, and my OS is Windows 

I think in your case you should open new issue regarding your problem with Windows OS and ask if there is similar solution like mine for Windows.
