### ISSUE TITLE
Performance regression in hot reload benchmarks in dart 2 preview mode

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#12520]
#12496 appears to have caused a very significant regression in the following hot_mode_dev_cycle__preview_dart_2_benchmark benchmarks:
  * hotReloadDevFSSyncMilliseconds
  * hotReloadFlutterReassembleMilliseconds
  * hotReloadMillisecondsToFrame
  * hotReloadVMReloadMilliseconds
  * hotRestartMillisecondsToFrame

**Comment by aam** [comment]
Thanks @cbracken , this is as expected until dartbug.com/31043 is fixed. See discussion on this on https://github.com/flutter/engine/pull/4184 too.

Support for `--preview-dart-2` option is still work in progress and is not quite at the point where it can be reliably stable.

**Comment by cbracken** [comment]
Thanks for the background. Should the benchmarks be readjusted until then?

**Comment by aam** [comment]
Yeah, we could reset the baseline for restart benchmark.
Meanwhile we have https://github.com/flutter/flutter/pull/12535, which actually should bring back reload benchmarks closer to pre #12496 levels.

**Comment by cbracken** [comment]
Closing. Summary - @aam's PR brought all but one of the benchmarks back to previous levels and the baseline for the last one has been reset.
