### ISSUE TITLE
How to implement a macos app prompt password to launch it with admin privilege?

### ISSUE THREAD

**Issue by irocn** [flutter/flutter#125279]
On MacOS I still don't find a better solution to implement this requirement.

Now I use the flutter framework to develop app GUI and the GUI will load library in Rust, this library need some privilege as service to listen port.

I can load library use sudo on terminal, but don't load the libray by GUI. It will cause "**permission error(13 'permission denied')**" . 

any suggestion is very appreciated.

**Comment by darshankawar** [comment]
> I can load library use sudo on terminal, but don't load the libray by GUI. It will cause "**permission error(13 'permission denied')**" .

@irocn Does this mean the app prompt password / permission is being triggered only through terminal but not by macos app itself and you are expecting that the macos app should be asking / prompting for the password ?

**Comment by darshankawar** [comment]
Ok, see if [this](https://github.com/flutter/flutter/issues/96369) issue relates to your use case or not.
If not, can you provide steps to replicate along with complete error to analyze this further ?

**Comment by stuartmorgan** [comment]
> the macos app itself can prompt for the password to hold the admin/root privilege to launch itself like sudo on terminal.

An application on macOS cannot control its own launch permissions. This is not related to Flutter, that's just not how macOS works.

If you want special permissions you need to launch an authorized subprocess, using native code. This could be fine directly in your application, or you could build a plugin for that use case.

Closing as authorized sub-agents are out of scope for Flutter itself.
