### ISSUE TITLE
[CP] [beta] [flutter_tools] Fix SentinelException from getIsolate()

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#125231]
### issue_link

https://github.com/flutter/flutter/issues/125064

### Commit Hash

https://github.com/flutter/flutter/commit/d85e2fb810b60bf6d5a697a42c4721329e6b5c2c

### Target

beta

### pr_link

https://github.com/flutter/flutter/pull/125237

### Impacted Users

Potentially all Flutter devs debugging from VS Code with the new SDK DAPs

### Impact Description

@christopherfujino has observe some unhandled exceptions when debugging using the new SDK DAPs on beta. These are race conditions where the debugger tries to fetch an isolate that has exited (which can occur while the debug adapter is in the process of sending the request).

A new release of DDS (2.7.9) includes fixes to handle these Sentinel responses where appropriate.

### Workaround

The SDK DAPs can be disabled, but the legacy DAPs are not being updated with the latest language features so it's important to migrate users off them to the new SDK DAPs.

### Risk

low

### Test Coverage

yes

### Validation Steps

I've had no luck reproducing the issue (since it's a race), but there are automated tests in the Dart SDK/DDS package, and I have manually verified some by modifying the DDS code to force some conditions with delays to verify the fix.

**Comment by christopherfujino** [comment]
@zanderso can you approve this? Thus far the vast majority of tool crashers on our beta branch is from the debug adapter code, and we're above are accepted crash rate threshold.

**Comment by itsjustkevin** [comment]
Friendly ping @zanderso
