### ISSUE TITLE
CameraException(Previous capture has not returned yet., takePicture was called before the previous capture returned.)

### ISSUE THREAD

**Issue by Ayan-Qolaris** [flutter/flutter#125202]
When I call cameraController!.takePicture() the app crashes with the following error: **CameraException(Previous capture has not returned yet., takePicture was called before the previous capture returned.)**

I am using the latest version of camera: **camera: ^0.10.4**

**Comment by darshankawar** [comment]
@Ayan-Qolaris 
Can you provide `flutter doctor -v` ? Also, is this error occuring on emulator or physical device ?
If on emulator, can you try on other emulator and check if the same error occurs or not ? See this for reference: https://github.com/flutter/flutter/issues/120774#issuecomment-1438549918

Also, if occuring on physical device, please provide device details and steps to replicate that causes this error.
