### ISSUE TITLE
Autosubmit bot refuses to merge an earlier requested changes but later approved PR

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#125280]
See: https://github.com/flutter/engine/pull/41370#issuecomment-1517218286 and https://github.com/flutter/flutter/pull/125211#issuecomment-1517218307

/cc @ricardoamador

**Comment by ricardoamador** [comment]
Oooh, that is odd. I will take a look tomorrow first thing.

**Comment by ricardoamador** [comment]
Okay nevermind, I see the issue. I will submit a change tomorrow. Since github keeps all of the reviews around we need to manage the time the reviews were submit and if they occur after a change request review.
