### ISSUE TITLE
Isolate example crashes when the isolate completes

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#12526]
## Steps to Reproduce

1. Run these commands:
```
cd flutter/examples/layers/
flutter run -t services/isolate.dart
```

2. Click the Start button

=> App crashes when the progress reaches 100%

```
F/libc    (16109): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x5c in tid 16132 (ui_thread)
```

**Comment by mit-mit** [comment]
@a-siva but we discussed in email; can you assign it to the engineer that is looking at this?

**Comment by a-siva** [comment]
Created pull request https://github.com/flutter/engine/pull/4218

**Comment by a-siva** [comment]
Landed https://github.com/flutter/engine/pull/4218 to fix this issue.

**Comment by sethladd** [comment]
Thanks!

**Comment by sethladd** [comment]
Do we have a test for his?

**Comment by a-siva** [comment]
examples/layers

**Comment by mit-mit** [comment]
@a-siva looks like `isolate_test.dart` just runs the `main()` method? I think we need to extend that test with a `tap` on the 'Start' button?

**Comment by sroddy** [comment]
@mit-mit @a-siva Not sure it is related, but I tested the `isolate.dart` example and now it crashes as soon as I press the start button, instead of at 100% of the progress as it was in alpha 0.0.16. Using the debugger, this is the last Dart line it manages to reach:
```Isolate.spawn(_calculate, message).then<Null>((Isolate isolate) {```
It also seems that it doesn't enter the _calculate function from the other isolate.

When I run it from console/intellij I just see a `Lost connection to device.` error.

If I try to run it from the xcode project, I receive this:
```
2017-11-09 01:49:29.252669+0100 Runner[23488:362570] Observatory listening on http://127.0.0.1:60411/
2017-11-09 01:49:34.046035+0100 Runner[23488:362585] [VERBOSE-3:dart_init.cc(350)] Check failed: Dart_IsolateMakeRunnable(isolate). ```

I'm experiencing this same issue in alpha 0.0.17, and I'm experiencing it also in my own code every time I try to spawn an Isolate.

**Comment by mit-mit** [comment]
Are you on master or alpha? I also still get a crash in alpha, but have it working on master.

**Comment by sroddy** [comment]
I just tried to run it with a completely new `master` directory and I'm able to reproduce it consistently. Here is my flutter doctor:

```[✓] Flutter (on Mac OS X 10.12.6 16G1036, locale it-IT, channel master)
    • Flutter at /Users/sroddy/flutter/flutter
    • Framework revision 436aa93086 (2 hours ago), 2017-11-09 07:12:36 +0100
    • Engine revision bc2acf7bdd
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /Users/sroddy/Library/Android/sdk
    • Platform android-26, build-tools 26.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.0.1, Build version 9A1004
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.2.5)
    • Flutter plugin version 18.4
    • Dart plugin version 172.4343.25

[✓] Connected devices
    • iPhone SE • BA3ECA04-6D6A-41DE-9AB7-02CDCD6D56F1 • ios • iOS 11.0 (simulator)```

**Comment by mit-mit** [comment]
I can repro now! It *does* work on Android Emulator, and physical iOS devices, but if I run an iPhone SE in the Simulator I also get the "Lost connection to device." error when I click the button.

@sroddy would you mind opening a new bug for this?

**Comment by sroddy** [comment]
yes, no prob.
