### ISSUE TITLE
Duplicated arm64 build in two windows builds

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#125262]
Windows Host Engine and Windows windows_arm64 and Windows windows_arm_host_engine both generate windows-arm64/artifacts.zip

Examples:

* gs://flutter_infra_release/flutter/b2cebe040938c30a0d4e51a97a71c5af07b0b99a/windows-arm64/artifacts.zip
* https://ci.chromium.org/p/flutter/builders/prod/Windows%20Host%20Engine/21752
* https://ci.chromium.org/p/flutter/builders/prod/Windows%20Host%20Engine/21750
* gs://flutter_infra_release/flutter/32a8f98d19dfb140b20ff506e3ade6f71416aaa9/windows-arm64/artifacts.zip

**Comment by godofredoc** [comment]
@christopherfujino is windows-arm64/artifacts.zip being used in production? should it be moved to the arm64 build?

**Comment by godofredoc** [comment]
\cc @zanderso

**Comment by christopherfujino** [comment]
> @christopherfujino is windows-arm64/artifacts.zip being used in production? should it be moved to the arm64 build?

I'm 99% sure they are not used (I don't see the path in the tool codebase and I didn't even know we were building them).

**Comment by christopherfujino** [comment]
Looks like the builder was added in https://github.com/flutter/engine/pull/38739. I'm not sure if anyone is using these or the intention was to support this in the tool but no one got around to it. @pbo-linaro can you add further context?

**Comment by godofredoc** [comment]
ok it seems like the artifacts are duplicated in Windows Host Engine https://flutter-review.googlesource.com/c/recipes/+/38132

**Comment by godofredoc** [comment]
I'll send two CLs one to remove the arm64 builds from engine.py and a reland of the migration to v2

**Comment by godofredoc** [comment]
CL to remove arm64 from Windows Host Engine build: https://flutter-review.googlesource.com/c/recipes/+/42340

**Comment by godofredoc** [comment]
PR to move the engine v2 builds to prod: https://github.com/flutter/engine/pull/41409

**Comment by pbo-linaro** [comment]
@godofredoc Can you confirm artifacts are still built in some way now? Or is it broken? I'm a bit loss in the reverts/PR/CL of those last days...

@christopherfujino I think @godofredoc sent some context for this. From what I understood, there were two automated systems to build the same artifacts, the goal having been to migrate to the second one in last January.

Supporting windows-arm64 is still a wip (a design document is currently written for this), so it would be nice if artifacts could stay built for this platform. Thanks!

**Comment by godofredoc** [comment]
@pbo-linaro the artifacts will continue to get build and uploaded but now they will be using the new builders(engine v2):

* https://flutter-review.googlesource.com/c/recipes/+/42420
* https://github.com/flutter/engine/pull/41409

**Comment by pbo-linaro** [comment]
Thanks for the confirmation!
