### ISSUE TITLE
 Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)

### ISSUE THREAD

**Issue by HanJiuYuan** [flutter/flutter#125287]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Triggered if using native communication Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)

### Logs

Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)

### Flutter Doctor output

E/flutter (16549): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (16549):

**Comment by HanJiuYuan** [comment]
@Override
    public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
    
        new MethodChannel(flutterEngine.getDartExecutor().getBinaryMessenger(), Method_Channel).setMethodCallHandler(
                (call, result) -> {
                   
                    if (call.method.equals("getSMS")) {
                        String batteryLevel = getBatteryLevel();
                        if (batteryLevel != null) {
                            result.success(batteryLevel);
                        } else {
                            result.error("UNAVAILABLE", "", null);
                        }
                    } else {
                        result.notImplemented();
                    }
                });
    }
**This is the code for my Android communication**

**Comment by darshankawar** [comment]
Thanks for the report @HanJiuYuan 
The error you are getting most probably indicates an implementation issue. I suggest you take a look at https://docs.flutter.dev/development/platform-integration/platform-channels#example and check if you are missing any code implementation that is causing the error.

**Comment by HanJiuYuan** [comment]
> Thanks for the report @HanJiuYuan The error you are getting most probably indicates an implementation issue. I suggest you take a look at https://docs.flutter.dev/development/platform-integration/platform-channels#example and check if you are missing any code implementation that is causing the error.

Thanks for the report @HanJiuYuan
The error you are getting most probably indicates an implementation issue. I suggest you take a look at https://docs.flutter.dev/development/platform-integration/platform-channels#example and check if you are missing any code implementation that is causing the error.

**Comment by HanJiuYuan** [comment]
> Thanks for the report @HanJiuYuan The error you are getting most probably indicates an implementation issue. I suggest you take a look at https://docs.flutter.dev/development/platform-integration/platform-channels#example and check if you are missing any code implementation that is causing the error.



> Thanks for the report @HanJiuYuan The error you are getting most probably indicates an implementation issue. I suggest you take a look at https://docs.flutter.dev/development/platform-integration/platform-channels#example and check if you are missing any code implementation that is causing the error.

I have checked this code and there is no problem. Thank you for your cooperation@darshankawar 
This is probably done by introducing shared_preferences as a plugin. The default channel is associated with the main project engine. When we use the new engine to draw the videoPlayer ui layer, videoPlayer uses channel to interact with native data. The channel is sent to the channel of new engine, but the new engine is not bound with shared_preferences. So you get an error Unable connection on channel

**Comment by darshankawar** [comment]
Thanks for the update.



> This is probably done by introducing shared_preferences as a plugin. The default channel is associated with the main project engine. When we use the new engine to draw the videoPlayer ui layer, videoPlayer uses channel to interact with native data. The channel is sent to the channel of new engine, but the new engine is not bound with shared_preferences. So you get an error Unable connection on channel

Can you provide a sample repo that we can clone and run to verify / analyze it and eventually make it actionable ?

**Comment by HanJiuYuan** [comment]
> Can you provide a sample repo that we can clone and run to verify / analyze it and eventually make it actionable ?

Okay, sure. I'll get it for you later
