### ISSUE TITLE
Update iOS engine scenario goldens to work with iOS 16.2 simulator

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#125227]
https://github.com/flutter/engine/pull/41370 Updated the engine tests to run on Xcode 14.2.  Update the engine scenario screenshots to match the iOS 16.2 simulator runtime and remove `ios-16-0_14a5294e` from the runtime list.

https://github.com/flutter/engine/blob/32a8f98d19dfb140b20ff506e3ade6f71416aaa9/testing/scenario_app/run_ios_tests.sh#L51
https://github.com/flutter/engine/blob/32a8f98d19dfb140b20ff506e3ade6f71416aaa9/testing/scenario_app/run_ios_tests.sh#L61

Does iPhone 8 still a valid simulator device?  If not we may finally need to solve the issue where these tests don't pass with the bottom home bar (not button) due to its inconsistent and flaky transparency.

**Comment by jmagman** [comment]
cc @vashworth @cyanglaz

**Comment by cyanglaz** [comment]
iPhone 8 can still support all the iOS(s)
Since we are here, we can also move it to iPhone SE, which is newer than iPhone 8 and probably will support newer versions down the road.

**Comment by jmagman** [comment]
> iPhone 8 can still support all the iOS(s) 

The issue is that Xcode isn't shipping it as a simulator device.

> iPhone SE does not have the home bar issue.

Ah great idea, you're right that iPhone SE _is_ still supported out-of-the-box.
<img width="377" alt="Screenshot 2023-04-20 at 11 16 11 AM" src="https://user-images.githubusercontent.com/682784/233452964-abeb14a3-694a-4921-8cfb-fcb19ef889e9.png">

**Comment by cyanglaz** [comment]
We probably should do this after moving engine to arm macs, so we don't have to replacing all the goldens twice.

**Comment by jmagman** [comment]
> We probably should do this after moving engine to arm macs, so we don't have to replacing all the goldens twice.

Or do it at the same time 🙂

**Comment by chinmaygarde** [comment]
I'm curious why the goldens depend on the iOS simulator version.
