### ISSUE TITLE
Release team does not have access to code review or submit CLs on dart-internal

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#125224]
I have no access to mark code review or submit CLs. If a breakage occurs, this blocks the release team from being able to make changes to dart-internal during releases.

**Comment by CaseyHillers** [comment]
@yusuf-goog (oncall) can you take a look at this before Friday? This ensures I have time to test it before our next release

**Comment by godofredoc** [comment]
Any reason why not adding release team to flutter-infra?

**Comment by CaseyHillers** [comment]
Why not make it accessible to anyone? At the least, it seems like this should be accessible by Googlers

**Comment by godofredoc** [comment]
> Why not make it accessible to anyone? At the least, it seems like this should be accessible by Googlers
Dart-internal is restricted to a limited set of people because of SLSA requirements.

**Comment by godofredoc** [comment]
Let's move this discussion to an internal bug. The solution to this specific request is to add release eng people to flutter-infra.

**Comment by CaseyHillers** [comment]
For the short term, we've added the release team to the infra groups. Long term would be to open up this repo to everyone, and allow authorized users to send CLs.
