### ISSUE TITLE
[camera] Apply LUTs over camera preview

### ISSUE THREAD

**Issue by WriteCodeEveryday** [flutter/flutter#125322]
## Use case

As a user, I would like to show the preview of what an image might look like after applying a .cube LUT

## Proposal

The camera preview should accept a LUT or alternatively allow us to grab the preview frames as they come in and paint them before passing them to the drawing widget.

I do not have an exact understanding of how this works but it would be amazing to decouple fetching the images from the drawing of the preview image to allow image modifications to be done to the preview.

**Comment by iapicca** [comment]
> The camera preview should accept a LUT or 

@WriteCodeEveryday I suspect the goal of camera is to replicate the features of android, ios (and web?) camera,
that being said...

> alternatively allow us to grab the preview frames as they come in and paint them before passing them to the drawing widget.

I totally agree in the need of being able to manipulate camera's output w/o reinventing the wheel,
maybe something like this 

```dart
RawCameraPreview(
  controller: _myCameraController,
  builder: (BuildContext context, Uint8List rawImage) => NonPlatformViewWidget(
      image: rawImage,
      filter: _myFilter,
   ),
);
```

**Comment by stuartmorgan** [comment]
> or alternatively allow us to grab the preview frames as they come in and paint them

If you really want to do this, you could ignore the preview and use `startImageStream`, post-processing however you like and then rendering that.

> it would be amazing to decouple fetching the images from the drawing of the preview image

This is not feasible without forcing everyone to use an implementation like the `startImageStream` approach, which is far less efficient. The current system has the camera drawing directly to a texture, which isn't separable without adding a GPU->CPU->GPU round-trip.

Closing as out of scope; this isn't something we would build into the plugin, and the ability to do it (in Dart) already exists. If you want *native*-side transforms, a custom plugin is going to be the best option.

**Comment by WriteCodeEveryday** [comment]
> you could ignore the preview and use startImageStream, post-processing however you like and then rendering that.

It's not that this isn't functional but the YUV420 to Image pipeline in order to use https://pub.dev/packages/dart_lut is just not performant enough.  Native apps have the ability to add filtering but the dart alternative for flutter is just not equivalent in performance and requires more code than a native app.
