### ISSUE TITLE
[camerax] Implement zoom configuration

### ISSUE THREAD

**Issue by camsim99** [flutter/flutter#125371]
In the camera plugin, there are a number of methods related to retrieving information about the zoom level and its configuration. These must be implemented in the CameraX plugin, as well:

- [x] Implement getMaxZoomLevel()
- [x] Implement getMinZoomLevel()
- [ ] Implement setZoomLevel()

**Comment by panzikeji** [comment]
May I ask how to set a custom scale in the end

**Comment by camsim99** [comment]
> May I ask how to set a custom scale in the end

You can use [`setZoomLevel`](https://github.com/flutter/packages/blob/94ba82ce52946395bba49cc3e11f47c84eb43213/packages/camera/camera/lib/src/camera_controller.dart#L644) for all package implementations except `camera_android_camerax`, hence this issue.
