### ISSUE TITLE
Flutter Web does not load after the second load

### ISSUE THREAD

**Issue by nilsreichardt** [flutter/flutter#125393]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

**Update (07.05.2023):** We can reproduce it with the default Flutter counter app. See https://github.com/flutter/flutter/issues/125393#issuecomment-1537513023.

Unfortunately, there are no steps to reproduce currently because this issue has one of our users. A few months ago I had the same issue with an empty Flutter App (just `runApp(MaterialApp())` but the app had some dependencies). The only way I was able to fix it was to use `flutter clean` before every `flutter build`.

However, now one of our users of our Sharezone app (https://alpha.web.sharezone.net) has the same issue. Loading the Flutter web app for the first time works, a second load doesn't work anymore. It's just an empty, white page. Resetting the browser data restarts the problem (1. load works, second load doesn't work anymore).

In this case `flutter clean` does not work because we deploy our app via GitHub Actions (without caching).

### Expected results

The website should always load.

### Actual results

After the first load, the website is always just white.

### Code sample

As I mentioned previously, currently there is no code sample. Complete source code of our app: https://github.com/sharezoneApp/sharezone-app/tree/main/app

### Screenshots or Video

https://user-images.githubusercontent.com/24459435/233851188-fc5723d5-6c95-491c-b979-d6442faf0306.mp4

### Logs

The user cannot get logs because he has no access to a Mac or MacBook (required to read out the iOS Safari logs.)

### Flutter Doctor output

```
[✓] Flutter (Channel stable, 3.7.10, on macOS 13.2.1 22D68 darwin-arm64 (Rosetta), locale en-DE)
    • Flutter version 3.7.10 on channel stable at /Users/nils/fvm/versions/3.7.10
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b12645012 (3 weeks ago), 2023-04-03 17:46:48 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/nils/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2023.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
    • IntelliJ at /Users/nils/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
    • IntelliJ at /Users/nils/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.4345.14/IntelliJ
      IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

Scanning for devices is taking a long time...[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64 (Rosetta)
    • Chrome (web)    • chrome • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by danagbemava-nc** [comment]
Hi @nilsreichardt, is the user only experiencing this on iPadOS, or are they experiencing this on other OSes? 

Can you provide the OSes they're experiencing the issue on and their versions?

> A few months ago I had the same issue with an empty Flutter App (just runApp(MaterialApp()) but the app had some dependencies).

Do you recall the version of flutter you experienced this issue with?

**Comment by EckigerLuca** [comment]
Hi @danagbemava-nc, I am experiencing the problem only on the iPad.
It's running the newest version, 16.4.1 (20E252).
It's a device managed by my school/city and they use [Relution](https://relution.io/).
My classmates and I realized, that we all have the same issue when using the school iPad. Students using their private iPad don't encounter such an issue. Even the Flutter Gallery isn't working, it's the same problem: loads once and then never again until the website data is deleted.
I managed to gain access to the safari logs, they are empty. No error in the console or anything else. [Here](https://1drv.ms/u/s!AtGZCqqbHJpqgYQJ7XEfPSAhr6PAWQ?e=mDdvOa) is the `.har` file.

**Comment by nilsreichardt** [comment]
Hey @danagbemava-nc, @EckigerLuca is the user who is experiencing the issue. He already wrote some details and is also experiencing the issue with Flutter Gallery, what is great because now it's much easier to debug.

> Do you recall the version of flutter you experienced this issue with?

For myself, it was the latest stable version in December 2022. I had the issue with Chrome, even when debugging. Starting the web app worked, making a hot restart ended up in the described issue: just a white empty page. 

But our alpha version is running with `3.7.10`. Not sure which version is the Flutter Gallery uses.

**Comment by danagbemava-nc** [comment]
> Not sure which version is the Flutter Gallery uses.

Fyi, the flutter gallery is running on the master channel. 

> My classmates and I realized, that we all have the same issue when using the school iPad. Students using their private iPad don't encounter such an issue. Even the Flutter Gallery isn't working, it's the same problem: loads once and then never again until the website data is deleted.

I wonder if the management software may be interfering with the webapp somehow. 

@EckigerLuca, would it be possible to get the logs when you open the app for the first time (and it works) along with the logs for several refreshes? I wonder if some files are not loading after the first load

**Comment by EckigerLuca** [comment]
@danagbemava-nc the only file I can provide is a `webarchive`, I was not able to export a HAR file.
What I can say about the loading behavior is that on the first load all files are being received, on the second/third/... load just an empty HTML file arrives.
[sharezone_safari_logs.zip](https://github.com/flutter/flutter/files/11361595/sharezone_safari_logs.zip)

**Comment by danagbemava-nc** [comment]
Hi @EckigerLuca, just to confirm, the empty HTML file would be the index.html file, correct?

**Comment by EckigerLuca** [comment]
Hi @danagbemava-nc, yes the `index.html` is ‚empty‘. There‘s just something like
```html
<html>
</html>
```
 inside, so no real content.

**Comment by danagbemava-nc** [comment]
Thanks for the info @EckigerLuca. 

There's a similar issue like this in https://github.com/flutter/flutter/issues/61464 but that seems to affecting chrome on windows. 

I just checked and flutter gallery uses auto renderer, so for iPad this will be HTML whereas sharezone is using Canvaskit however, the bug seems to reproduce with both web apps so it does not seem limited to a specific renderer. 

A recording of the issue can be found in the original post. 

According to the report, the devices that are experiencing this issue are being managed by a certain software (See https://github.com/flutter/flutter/issues/125393#issuecomment-1526124246). 

Labeling for further investigation as I cannot reproduce this locally.

**Comment by nilsreichardt** [comment]
@yjbanov I chatted with @EckigerLuca and we can also reproduce the issue for him using the standard Flutter counter app.

Source code: https://github.com/nilsreichardt/flutter_second_load_bug/tree/660dae70394a0286b1e631d938b9731c5b1cd9ed
Website: https://flutter-second-load-bug.web.app/#/

Demo by @EckigerLuca: Loading the first time works, the second time it's not working anymore.

https://user-images.githubusercontent.com/24459435/236695497-cb6a72ed-0dbe-45f5-9564-7af5e8d8c88f.mp4

This indicates that the bug has nothing to do with our [Sharezone](https://github.com/SharezoneApp/sharezone-app) app.

I used Flutter v3.7.12 to create the Flutter counter app and I used `flutter build web` to build the web app. The app is deployed to Firebase Hosting.

> such as some sort of software installed on the device, an intermediate server such as a proxy, or something else.

As a side note: @EckigerLuca has the issue in every network: School Wi-Fi, personal hotspot and at home with the personal Wi-Fi.

> It could also be an issue with the service worker. Do you use the service worker? Does the issue persist if you remove it?

At Sharezone we just use the default service worker (see [index.html](https://github.com/SharezoneApp/sharezone-app/blob/aee3c829db92f2e641e558c36c5f21ff3d8e385a/app/web/index.html)). It's the same service worker as the default Flutter counter app uses.

**Comment by yjbanov** [comment]
For now there doesn't seem to be any indication of an issue in Flutter itself. I recommend contacting Relution to see if they can figure it out on their end. They might be blocking certain web API or altering content when it passes through their proxies, at which point there's not much we can do.

If you find out that Flutter can take some concrete action to fix this, please file a new issue with the proposed change.
