### ISSUE TITLE
Large regression in simple_animation_perf raster times on iOS

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#125358]
Skia perf is reporting a large regression in raster times in simple_animation_perf_ios on the engine -> framework roll here https://github.com/flutter/flutter/commit/7aa01f53f84103063c9cb5e120d3b0803bdd03cf.

https://flutter-flutter-perf.skia.org/e/?begin=1681864286&end=1682132777&keys=Xa4798bffcf47abd116a5522e391d5af2&requestType=0&selected=commit%3D34485%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253Daverage_frame_rasterizer_time_millis%252Ctest%253Dsimple_animation_perf_ios%252C&xbaroffset=34485

The benchmark briefly recovered on the framework commit https://github.com/flutter/flutter/commit/8a815c1d1d0d590fc3ef4dbbec1f967036685cbe, and then regressed again on the framework commit https://github.com/flutter/flutter/commit/702f0144e0998d031b59c0042e5380c1ae0fab8f.

The two framework commits couldn't have caused changes in this benchmark.

**Comment by chinmaygarde** [comment]
The pattern looks suspiciously similar to the time being capped to the next frame interval at 16ms. The workload could be GPU bound and based on the device state, some runs push the time past the frame interval.

<img width="2212" alt="Screenshot 2023-04-24 at 10 34 09 AM" src="https://user-images.githubusercontent.com/44085/234073289-246d9872-96f0-42ea-91ca-b4b2457c7dff.png">

cc @jason-simmons who is going to verify on an iPhone 11.

**Comment by zanderso** [comment]
Timeline from a recent run: https://storage.googleapis.com/flutter_logs/flutter/3ab8cd2615975c38c9ca838f2aa6f83c9baebf7b/simple_animation_perf_ios/4966d800-14b1-413b-9161-d2ffe14b05e6/simple_animation_perf.timeline.json

**Comment by jonahwilliams** [comment]
From the timeline, almost every frame is blocking on waitForNextDrawable. The reason we're dropping a frame doesn't appear in the timeline though

**Comment by jonahwilliams** [comment]
it could be an ill-timed GC, for example

**Comment by zanderso** [comment]
Is the cause important? The engine should be able to recover more gracefully from a dropped frame regardless of the cause, right?

**Comment by jonahwilliams** [comment]
the cause could be, if its related to the engine roll, or instead some sort of devicelab issue.

FWIW, we technically have the same exact issue on the Skia backend, we just hit it less often as interrupting the raster workload is less likely to cause a dropped frame.

**Comment by jason-simmons** [comment]
Bisected this to https://github.com/flutter/engine/commit/be9185ec

**Comment by jonahwilliams** [comment]
Lets revert for now but this one is a bit of a head scratcher IMO. I can investigate offline with this app to determine why this change caused a regression

**Comment by zanderso** [comment]
SkiaPerf reports that the raster time has recovered, but also GPU util has returned to its previous levels:

https://flutter-flutter-perf.skia.org/e/?begin=1681966145&end=1682436727&keys=X30fe72b4e3d00a32925673001ce20400&requestType=0&selected=commit%3D34530%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253Daverage_gpu_usage%252Ctest%253Dcomplex_layout_scroll_perf_ios__timeline_summary%252C&xbaroffset=34530.

**Comment by jonahwilliams** [comment]
Yeah, the GPU utilization dropping / increasing was the expected change - however I still need to track down what exactly caused the regression
