### ISSUE TITLE
How to modify the color of the long press pop-up menu?

### ISSUE THREAD

**Issue by xiaohucode** [flutter/flutter#125391]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

How to modify the color of the long press pop-up menu?
![截屏2023-04-23 20 59 05](https://user-images.githubusercontent.com/24434389/233841318-f4535014-feb8-43ad-8af2-387eea2cff92.png)

### Actual results

I hope to turn it black

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```
[✓] Flutter (Channel master, 3.9.0-22.0.pre.27, on macOS 12.6 21G115 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.9.0-22.0.pre.27 on channel master at /Users/xcode/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9235eb64e2 (3 weeks ago), 2023-04-05 01:30:11 -0400
    • Engine revision 4219c72ac8
    • Dart version 3.0.0 (build 3.0.0-408.0.dev)
    • DevTools version 2.23.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/xcode/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/xcode/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.74.2)
    • VS Code at /Users/xcode/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (4 available)
    • iPhone 14 Pro Max (mobile) • 4CEB6FBA-0B66-455F-9AEB-D80D5D700DD1 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 112.0.5615.137

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by emirariemir** [comment]
The **text editing menu** is controlled by the underlying operating system, so changing its appearance requires modifying the platform-specific code for each platform your app targets.

For iOS, you can customize the appearance of the text editing menu by using the `UITextField` class in Objective-C or Swift. Specifically, you can set the `tintColor` property of the text field to the desired color. To achieve this in Flutter, you can create a platform channel that communicates with the native code and exposes a method to change the `tintColor` property of the text field. Let me give you an example:

1. Create a platform channel in your Flutter app:
```
final MethodChannel _channel = MethodChannel('com.example/text_editing_menu');

Future<void> setEditingMenuColor(Color color) async {
  final int alpha = color.alpha;
  final int red = color.red;
  final int green = color.green;
  final int blue = color.blue;
  final List<int> rgbaValues = [red, green, blue, alpha];
  await _channel.invokeMethod('setEditingMenuColor', rgbaValues);
}

```

2. In your native iOS code (_native iOS code is typically located in the Runner target, under the Runner folder in the project navigator_), implement a method that changes the `tintColor` property of the text field:
```
@objc func setEditingMenuColor(_ arguments: [Int], result: FlutterResult) {
  let color = UIColor(red: CGFloat(arguments[0]) / 255.0,
                      green: CGFloat(arguments[1]) / 255.0,
                      blue: CGFloat(arguments[2]) / 255.0,
                      alpha: CGFloat(arguments[3]) / 255.0)
  DispatchQueue.main.async {
    UITextField.appearance().tintColor = color
  }
  result(nil)
}

```

3. Register the platform channel in your native iOS code (_the `registrar` variable refers to the `FlutterPluginRegistrar` instance that is passed to your plugin's register method_):
```
let channel = FlutterMethodChannel(name: "com.example/text_editing_menu", binaryMessenger: messenger)
let instance = SwiftMyPlugin()
registrar.addMethodCallDelegate(instance, channel: channel)
```

4. Call the `setEditingMenuColor` (_or whatever you name you created_) method in your Flutter app to change the color of the text editing menu:
`setEditingMenuColor(Colors.red);`

This example sets the color of the text editing menu to red, but you can replace this with any color you want. **Note that this code only changes the text editing menu color on iOS**, so you'll need to implement similar functionality for other platforms if you want to customize the text editing menu appearance there as well.

Let me know if that works for you!

**Comment by AcarFurkan** [comment]
you probably want something like this
https://stackoverflow.com/questions/72499847/custom-text-selection-toolbar-in-flutter

**Comment by emirariemir** [comment]
I managed to customize the text editing toolbar (or context menu, I'm still not sure what to call this pop-up) with the help of Flutter documentation.

By using the `TextField` property `contextMenuBuilder`, you can change the background color of the toolbar to your desired color. Here is the code that worked for me:
```
TextField makeTextField() {
  return TextField(
      enableInteractiveSelection: true,
      contextMenuBuilder: (BuildContext context, EditableTextState editableTextState) {
        return AdaptiveTextSelectionToolbar(
          anchors: editableTextState.contextMenuAnchors,
          children: editableTextState.contextMenuButtonItems.map((ContextMenuButtonItem buttonItem) {
            return CupertinoButton(
              borderRadius: null,
              color: const Colors.blue, // Here you can change the background color
              disabledColor: const Colors.red,
              onPressed: buttonItem.onPressed,
              padding: const EdgeInsets.all(10.0),
              pressedOpacity: 0.7,
              child: SizedBox(
                width: 200.0,
                child: Text(
                  CupertinoTextSelectionToolbarButton.getButtonLabel(context, buttonItem),
                ),
              ),
            );
          }).toList(),
        );
      });
}
```

I suggest you take a look at this [documentation](https://api.flutter.dev/flutter/material/TextField/contextMenuBuilder.html) about `contextMenuBuilder`, maybe you can figure out from here or could be a good starting point for your desired functionality.

**Comment by xiaohucode** [comment]
> 在 Flutter 文档的帮助下，我设法自定义了文本编辑工具栏（或上下文菜单，我仍然不确定如何称呼此弹出窗口）。
> 
> 通过使用`TextField`属性`contextMenuBuilder`，您可以将工具栏的背景颜色更改为您想要的颜色。这是对我有用的代码：
> 
> ```
> TextField makeTextField() {
>   return TextField(
>       enableInteractiveSelection: true,
>       contextMenuBuilder: (BuildContext context, EditableTextState editableTextState) {
>         return AdaptiveTextSelectionToolbar(
>           anchors: editableTextState.contextMenuAnchors,
>           children: editableTextState.contextMenuButtonItems.map((ContextMenuButtonItem buttonItem) {
>             return CupertinoButton(
>               borderRadius: null,
>               color: const Colors.blue, // Here you can change the background color
>               disabledColor: const Colors.red,
>               onPressed: buttonItem.onPressed,
>               padding: const EdgeInsets.all(10.0),
>               pressedOpacity: 0.7,
>               child: SizedBox(
>                 width: 200.0,
>                 child: Text(
>                   CupertinoTextSelectionToolbarButton.getButtonLabel(context, buttonItem),
>                 ),
>               ),
>             );
>           }).toList(),
>         );
>       });
> }
> ```
> 
> 我建议您查看有关 的[文档](https://api.flutter.dev/flutter/material/TextField/contextMenuBuilder.html)`contextMenuBuilder`，也许您可​​以从这里弄清楚或者可能是您所需功能的良好起点。



> I managed to customize the text editing toolbar (or context menu, I'm still not sure what to call this pop-up) with the help of Flutter documentation.
> 
> By using the `TextField` property `contextMenuBuilder`, you can change the background color of the toolbar to your desired color. Here is the code that worked for me:
> 
> ```
> TextField makeTextField() {
>   return TextField(
>       enableInteractiveSelection: true,
>       contextMenuBuilder: (BuildContext context, EditableTextState editableTextState) {
>         return AdaptiveTextSelectionToolbar(
>           anchors: editableTextState.contextMenuAnchors,
>           children: editableTextState.contextMenuButtonItems.map((ContextMenuButtonItem buttonItem) {
>             return CupertinoButton(
>               borderRadius: null,
>               color: const Colors.blue, // Here you can change the background color
>               disabledColor: const Colors.red,
>               onPressed: buttonItem.onPressed,
>               padding: const EdgeInsets.all(10.0),
>               pressedOpacity: 0.7,
>               child: SizedBox(
>                 width: 200.0,
>                 child: Text(
>                   CupertinoTextSelectionToolbarButton.getButtonLabel(context, buttonItem),
>                 ),
>               ),
>             );
>           }).toList(),
>         );
>       });
> }
> ```
> 
> I suggest you take a look at this [documentation](https://api.flutter.dev/flutter/material/TextField/contextMenuBuilder.html) about `contextMenuBuilder`, maybe you can figure out from here or could be a good starting point for your desired functionality.

Yes, that's what I want. Thank you

**Comment by emirariemir** [comment]
You're welcome.
