### ISSUE TITLE
Clang roll failing due to Fuchsia RBE not being populated with it

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#125361]
The clang roll here https://github.com/flutter/engine/pull/41340 failed due to builds timing out. When I patch the toolchain in locally, goma hits a local fallback for every compile, and reports the error:

`Failed to get resource output for ../../buildtools/mac-x64/clang/bin/clang++`

AFAIU, this indicates that the toolchain is not populated in the Fuchsia RBE.

The one we're trying to roll to is here https://chrome-infra-packages.appspot.com/p/fuchsia/third_party/clang/mac-amd64/+/git_revision:e8cfbfd05a951b85f80156dffc8eeecb34c7271c, which is the most recent with the `integration` tag.

Marking P2 because our clang toolchain hasn't rolled in over 8 weeks. Marking `team: infra` based on an assumption that this requires follow-up with Fuchsia infra folks.

cc @jason-simmons @godofredoc @petrhosek

**Comment by keyonghan** [comment]
Following with fuchsia infra.

**Comment by zanderso** [comment]
@godofredoc Since a local goma build with the new toolchain also fails and uses the local fallback, I think I don't understand how the goma recipe module is related. Same question about the cipd package. Which cipd package? Do we all need to update our local goma installs to use the new clang toolchain, as well?

**Comment by godofredoc** [comment]
Maybe? The recipe module is downloading the goma client from cipd which may be outdated because our fork.  
https://cs.opensource.google/flutter/recipes/+/main:recipe_modules/goma/api.py;l=100

For the local builds can you please give it a try using the latest integration goma client from `"fuchsia/third_party/goma/client/${platform}"`?

**Comment by keyonghan** [comment]
https://flutter-review.googlesource.com/c/recipes/+/42580 to update to use fuchsia goma client to unblock.

@godofredoc let me know if you want something different. Like syncing the flutter goma client in cipd, or others.

**Comment by godofredoc** [comment]
Re-opened @keyonghan change and added a small update to support arm64 in mac using the x64 package.

https://flutter-review.googlesource.com/c/recipes/+/42680

**Comment by zanderso** [comment]
Toolchain roll landed.
