### ISSUE TITLE
Some source files of flutter framework on master branch use `switch` block without `case`

### ISSUE THREAD

**Issue by stMerlHin** [flutter/flutter#125376]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I would like to contribute to flutter framework development by fixing some issues. To do so, I  followed the steps described in the [flutter wiki page](https://github.com/flutter/flutter/wiki/Setting-up-the-Framework-development-environment).
I saw in some source files of the master branch that `switch` bloc format is not respected so intelliJ underline the correspondent line and keep saying The `'case' shouldn't complete normally`.

I check other branch like `flutter-3.7-candidate.10`, everything seems good.

I wonder if there is a defined branch from which we are supposed to make 'git checkout -b'.

1. clone flutter repo
2.  switch to master branch
3. open `packages/flutter/lib/src/cupertino/dialog.dart'
4. locate `_placeChildInSlot` (at line 897 when I was writing thes lines).
5. take a look at the method body

### Expected results

you should see 
 ```dart
 void _placeChildInSlot(RenderObject child, _AlertDialogSections slot) {
    switch (slot) {
      case _AlertDialogSections.contentSection:
        renderObject.contentSection = child as RenderBox;
      case _AlertDialogSections.actionsSection:
        renderObject.actionsSection = child as RenderBox;
    }
  }
```

You can see that the first `case` does not has `break` instruction.

### Actual results

.

### Code sample

.

### Flutter Doctor output

.

**Comment by stuartmorgan** [comment]
> You can see that the first `case` does not has `break` instruction.

This is intentional; see https://github.com/dart-lang/language/blob/main/accepted/future-releases/0546-patterns/feature-specification.md#implicit-break

Flutter on `master` only runs on Dart 3, so uses Dart 3 features.
