### ISSUE TITLE
Move some `Mac_arm64_ios` bot capacity from staging pool (5 bots) to try pool (1 bot)

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#125342]
To start running `Mac_arm64_ios run_debug_test_macos` in presubmit again, more bots should be allocated to the try pool.

1 bot:
https://chromium-swarm.appspot.com/botlist?f=device_os%3AiOS-16&f=os%3AMac-12&f=cpu%3Aarm64&f=pool%3Aluci.flutter.try

Staging has 5 unused bots 

https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=os&c=status&d=asc&f=device_os%3AiOS-16&f=os%3AMac-12&f=cpu%3Aarm64&f=pool%3Aluci.flutter.staging&k=pool&s=id

Move at least a few to the try pool.

Unblocks https://github.com/flutter/flutter/pull/125341.
See https://github.com/flutter/flutter/issues/118827 and https://github.com/flutter/flutter/pull/118828.

**Comment by jmagman** [comment]
cc @yusuf-goog

**Comment by jmagman** [comment]
@yusuf-goog, @vashworth is going to take over https://github.com/flutter/flutter/issues/118830, let her know if you need any other info to load balance these bots.

**Comment by keyonghan** [comment]
@yusuf-goog We may want to make sure the staging bots are in a good state before moving.

**Comment by jmagman** [comment]
I'm going to close https://github.com/flutter/flutter/pull/125341 for now, when this issue is complete it can be resurrected.

**Comment by yusuf-goog** [comment]
Will moving 2 be enough?

**Comment by jmagman** [comment]
> @jmagman Will moving 2 be enough?

I don't know, seems like it should be based on queue times, etc and adjusted from there.

**Comment by vashworth** [comment]
Is https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-38 even working? Looking at it's task list, looks like it hasn't run any tasks since Dec 2022? Is that right?

**Comment by vashworth** [comment]
Hmmm looks like `Mac_arm64_ios run_debug_test_macos` is the only test that even would fit the criteria for these bots anyways, so yeah I think we can try reenabling it. I'll create a PR

**Comment by vashworth** [comment]
PR out: https://github.com/flutter/flutter/pull/133788
