### ISSUE TITLE
Hot reload's warm up frame should not call `FlutterView.render`

### ISSUE THREAD

**Issue by loic-sharma** [flutter/flutter#125326]
## Problem

When the user hot reloads, the framework produces a frame immediately without waiting for the vsync using [`SchedulerBinding.scheduleWarmUpFrame`](https://github.com/flutter/flutter/blob/c9004ff822cf76848365f5dd8e034596fcbceba1/packages/flutter/lib/src/scheduler/binding.dart#L929). This warm up frame incorrectly calls `FlutterView.render` outside of the scope of `PlatformDispatcher.onBeginFrame` and `PlatformDispatcher.onDrawFrame`, which is not allowed as per [`FlutterView.render`'s docs](https://github.com/flutter/engine/blob/6ec35667c431d424c49c588cb8f0348acefb66ef/lib/ui/window.dart#L330-L332).

This eventually calls into `Animator::Render`, which [attempts to reuse the pending producer continuation](https://github.com/flutter/engine/blob/609e71543cb4bc996348ae316ff00a0ed252518c/shell/common/animator.cc#L153-L159). Normally the [producer continuation is created by the vsync](https://github.com/flutter/engine/blob/609e71543cb4bc996348ae316ff00a0ed252518c/shell/common/animator.cc#L81-L95) in `Animator::BeginFrame`. However, in the hot reload scenario we skipped waiting for a vsync, never called `Animator::BeginFrame`, and never created a producer continuation. As a result, the pending producer continuation is likely already committed and the scene will be dropped.

You can confirm this behavior by setting a breakpoint here and hot reloading: https://github.com/flutter/engine/blob/609e71543cb4bc996348ae316ff00a0ed252518c/shell/common/animator.cc#L157

## Solution

First, we should test what breaks in google3 if the engine errors if `FlutterView.render` is called outside the scope of `PlatformDispatcher.onBeginFrame` and `PlatformDispatcher.onDrawFrame`.

Assuming the google3 test indicates this change is reasonable:

1. Update hot reload's warm up frame to not call `FlutterView.render`. Hot reload should likely set [`sendFramesToEngine`](https://github.com/flutter/flutter/blob/ad0dbc8de5f98c6b8a374ae1b) to `false`.
2. Update the engine to error if `FlutterView.render` is called outside the scope of `PlatformDispatcher.onBeginFrame` and `PlatformDispatcher.onDrawFrame`

**Comment by Hixie** [comment]
The warm-up frames aren't actually expected to render, they're just doing all the `build` and `layout` work that will be necessary when we _do_ get a scheduled frame, because there's no reason to wait the 3ms or whatever between the hot reload and the vsync to actually get started on that work. So what happens is we do almost all the (framework-side) work that is needed, then when the frame actually happens, we just push up the layer tree unmodified (mostly; we might have to do a few updates for running animations).

If we could find a way to actually use the frame that would be great, but it's not critical to the purpose of the warm-up frame.

**Comment by dkwingsmt** [comment]
Thanks for clarification. This issue should be intended.

**Comment by Hixie** [comment]
when we have a question like this, we should update the documentation to answer it, so nobody else ever has to wonder.

**Comment by loic-sharma** [comment]
To clarify, the problem is that hot reload's warm up frame calls `FlutterView.render` outside of the scope of `PlatformDispatcher.onBeginFrame` and `PlatformDispatcher.onDrawFrame`. This is not allowed as per [`FlutterView.render`'s docs](https://github.com/flutter/engine/blob/6ec35667c431d424c49c588cb8f0348acefb66ef/lib/ui/window.dart#L330-L332).

For background, for multi-view we'd like the engine's pipeline to apply backpressure for scenes _across_ frames but not for scenes within a frame. To do so, the engine needs to be able to distinguish the start and end of a frame. The engine can do so only if `FlutterView.render` is called properly within the scope of `PlatformDispatcher.onBeginFrame` and `PlatformDispatcher.onDrawFrame`.

**Comment by Hixie** [comment]
Oh if the problem is that there's a logic error then we should just fix it. Send a PR. :-) Happy to review.
If we could make it possible to push a frame out-of-cycle that'd be even better.

**Comment by loic-sharma** [comment]
Yup agreed. @goderbauer and I were planning to try a google3 test where we make this an error and see what breaks. If the breaks are reasonable/expected, we'd move forward with this issue and:

1. Update hot reload's warm up frame not to call `FlutterView.render`
2. Make it an error to call `FlutterView.render` outside of an engine frame lifecycle

We have quite a queue of multi-view work items to chug through so I haven't had a chance to start working on this yet. Apologies for any confusion on this issue's description

**Comment by dkwingsmt** [comment]
This issue should be no longer valid now that we've decided that warm up frames should always go through the engine pipeline. See https://github.com/flutter/flutter/issues/142851 for the reason and the related work we've done to ensure it.
