### ISSUE TITLE
[Impeller] Use CanvasSpy or DlOpSpy in more embedders

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#125318]
When rendering platform views, Flutter will break the scene up into N layers and render these to different surfaces, using combinations of clear and clips. Generally, if there is nothing either over a platform view or under it, one or more of these layers is likely to be "trivial", that is result in no drawing at all.

Nevertheless, we will still go through a lot of work to process this layer, wait on the drawable, queue up clip commands that do nothing, et cetera. Though this doesn't really hurt GPU utilization, it does hurt overall raster time.

We should be able to detect these cases, and shortcircuit more of the workload. Rather than just making the engine better at detecting difference clips, this is a feature request for the display list to be able to determine that it doesn't actually render anything. That way we can stop before we even dispatch to impeller or attempt to acquire the drawable.

For example:

This second render pass contains only clips and a solid fill that gets clipped out. The resulting texture is entirely transparent.

![image](https://user-images.githubusercontent.com/8975114/233705480-ab98468d-4358-4dc9-9c07-c412b0c8a3a3.png)

**Comment by jonahwilliams** [comment]
From the raster side of things, the first SurfaceFrame::Submit could be elided entirely.


![image](https://user-images.githubusercontent.com/8975114/233706870-013e2144-04ec-4e68-9529-ac9e1e1f51f4.png)

**Comment by jonahwilliams** [comment]
FYI @flar

**Comment by flar** [comment]
Some of the embedding mechanisms already do this (though the implementation could be improved).

See:

- https://github.com/flutter/engine/blob/8b3966c1f47ecf5190a614b83a26e7bdf558e7b7/shell/common/canvas_spy.h#L58
- https://github.com/flutter/engine/blob/8b3966c1f47ecf5190a614b83a26e7bdf558e7b7/shell/common/dl_op_spy.h#L36

**Comment by jonahwilliams** [comment]
We found that all the issues caused by "extra rendering" are because we use the full bounds of the platform views and not the clipped bounds. There is no benefit to switching to the DlOpSpy by itself
