### ISSUE TITLE
Linux desktop app idle cpu usage is 45%

### ISSUE THREAD

**Issue by mrcsh** [flutter/flutter#125388]
## Details
When our app is compiled to for Linux it never uses less than 45% CPU utilization.  The web-app seems to be worse where chrome/brave threads sit at around 50%.  The web-app percentages are with release builds, the Linux desktop does drop a few percent with a release build, but never below 40%.  I ran the CPU profiler on the Linux app and _drawFrame was taking over 70% of the recorded time.  I could not find a single reference to any of our app code in the displayed profiler output.

I have put log statements in various widget's build functions to see if to see if any of our higher level widget are drawing more than they should, I cannot find the source of the background utilization in our code. 

On macos the background utilization is 18% which while better is still significant.

It does seem like we are doing something to trigger such high CPU utilization but so far the profiler has not been helpful at indicating what might be causing the issue.

I have attached the exported data from the profiler.  The data was collected at the default medium sample rate.  I also tried another run at high but the results were similar.

Looking at the raw data I did find 2 traces that had our code.  We have a background timer that refreshes authentication info every 2 minutes.  We have other timer that refreshes some other info about every 10 seconds, but during the sample run that data would not cause any UI updates.

I did run the profiler on android and there was almost nothing, with _RawReceivePort._handleMessage and _startMicrotaksLoop being the top (and only) two routines shown in the Call Tree display.

The profile was captured about 30 seconds after app startup when all of our startup code should be done, the app was just sitting there, not occluded by any other window and the window never received pointer focus.

I did try to see if I could build the app with the master channel but there were two many incompatible dependencies. If it will be useful I can try to see if they can be resolved but they got only worse after my first pass updating versions.

I have attached the exported profiler data for the linux app.

**Target Platform: linux, web, macos **
**Target OS version/browser: linux Fedora 37, macos 13.2.1, chrome Version 112.0.5615.165 (Official Build) (64-bit), brave [Version 1.50.125 Chromium: 112.0.5615.165 (Official Build) (64-bit)]**
**Devices:**

## Logs

<details>
<summary>Logs</summary>

```
 csh  …  lochbox  dart analyze                                                                                                                           master 
Analyzing lochbox...                   10.0s
No issues found!
 csh  …  lochbox  cd ../core/                                                                                                                            master 
 csh  …  core  !dart                                                                                                                                     master 
dart analyze
Analyzing core...                      2.7s
No issues found!
```
[dart_devtools_2023-04-23_05_36_42.672.json.gz](https://github.com/flutter/flutter/files/11303708/dart_devtools_2023-04-23_05_36_42.672.json.gz)

```
[✓] Flutter (Channel stable, 3.7.12, on Fedora Linux 37 (Thirty Seven) 6.2.11-200.fc37.x86_64, locale en_US.UTF-8)
    • Flutter version 3.7.12 on channel stable at /server/home/csh/lib/flutter3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (5 days ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/csh/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /server/home/csh/lib/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 15.0.7 (Fedora 15.0.7-2.fc37)
    • cmake version 3.26.3
    • ninja version 1.10.2
    • pkg-config version 1.8.0

[✓] Android Studio (version 2022.1)
    • Android Studio at /server/home/csh/lib/android-studio
    • Flutter plugin version 72.0.2
    • Dart plugin version 221.6096
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.77.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.62.0

[✓] Connected device (5 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • sdk gphone64 x86 64 (mobile) • emulator-5556 • android-x64    • Android 12 (API 32) (emulator)
    • sdk gphone64 x86 64 (mobile) • emulator-5558 • android-x64    • Android 12 (API 31) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Fedora Linux 37 (Thirty Seven) 6.2.11-200.fc37.x86_64
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 112.0.5615.165

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

**Comment by mrcsh** [comment]
I forgot to mention the baseline CPU utilization is being measured with top/bpytop.

**Comment by huycozy** [comment]
Hi @mrcsh 
I think it's not easy to figure out where the issue is coming from without a reproduction sample.
It can be caused by 3rd party plugins or wrong implementation in the code. Or it could be an existing animation issue at https://github.com/flutter/flutter/issues/101591 or be related to the general issue at https://github.com/flutter/flutter /issues/88996.

I would recommend narrowing down the issue by isolating the project's modules and finding the most relevant screen/widget then providing more information about the issue that would be helpful for investigation. Thank you!

**Comment by mrcsh** [comment]
Thanks, I think I will try to get additional perf info using some of the tools in the other related issues, and see where that leads.  Unless there is an animation that is always running (with no visible effect) I'm not sure the animation issue is relevant.
