### ISSUE TITLE
[CP] [web] Fix HashUrlStrategy.addPopStateListener

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#125317]
### issue_link

https://github.com/flutter/flutter/issues/125228

### Commit Hash

* [8d9f17e07](https://github.com/flutter/engine/commit/8d9f17e07633b0f8f2400bf00c95c4fac18f599e) (flutter/engine)

### Target

**beta**

### pr_link

* https://github.com/flutter/engine/pull/41459

### Impacted Users

All flutter web users that use the hash (default) routing.

### Impact Description

Back browser button is broken in apps that use hash routes.

Hash routes are the default routing strategy of all flutter web apps.

### Workaround

Users may add affordances on their apps to go "back" but if end users click the back button, the app spits out a bunch of errors and does nothing.

Users may be able to change the routing strategy to a Path based one, or a custom one with this issue fixed, but that's not a trivial workaround (especially migrating to the Path strategy, which needs adaptations on the user's server-side, and possibly breaks all links).

### Risk

low

### Test Coverage

yes

### Validation Steps

* Create a new app for the web
* Add a dependency on `go_router`
<details>
  <summary>• Replace <tt>lib/main.dart</tt> with the following:</summary>

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

/// This sample app shows an app with two screens.
///
/// The first route '/' is mapped to [HomeScreen], and the second route
/// '/details' is mapped to [DetailsScreen].
///
/// The buttons use context.go() to navigate to each destination. On mobile
/// devices, each destination is deep-linkable and on the web, can be navigated
/// to using the address bar.
void main() => runApp(const MyApp());

/// The route configuration.
final GoRouter _router = GoRouter(
  routes: <RouteBase>[
    GoRoute(
      path: '/',
      builder: (BuildContext context, GoRouterState state) {
        return const HomeScreen();
      },
      routes: <RouteBase>[
        GoRoute(
          path: 'details',
          builder: (BuildContext context, GoRouterState state) {
            return const DetailsScreen();
          },
        ),
      ],
    ),
  ],
);

/// The main app.
class MyApp extends StatelessWidget {
  /// Constructs a [MyApp]
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerConfig: _router,
    );
  }
}

/// The home screen
class HomeScreen extends StatelessWidget {
  /// Constructs a [HomeScreen]
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Home Screen')),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            ElevatedButton(
              onPressed: () => context.go('/details'),
              child: const Text('Go to the Details screen'),
            ),
          ],
        ),
      ),
    );
  }
}

/// The details screen
class DetailsScreen extends StatelessWidget {
  /// Constructs a [DetailsScreen]
  const DetailsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Details Screen')),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <ElevatedButton>[
            ElevatedButton(
              onPressed: () => context.go('/'),
              child: const Text('Go back to the Home screen'),
            ),
          ],
        ),
      ),
    );
  }
}

```
</details>

* When hitting "back" in the browser, the app should error as described in the linked issue.
* If the fix is applied, the application just goes to the previous page when clicking "back" in the browser.

**Comment by ditman** [comment]
Summoning @kevmoo to this cherry-pick issue.

**Comment by ditman** [comment]
(I'll update this CP request with the appropriate hashes to the flutter/flutter repo once the engine rolls into the framework)

**Comment by itsjustkevin** [comment]
@yjbanov could you give a second look to this cherry-pick request?

**Comment by itsjustkevin** [comment]
@ditman holding out a bit until the pr_link is updated with the cherry-pick to the beta branch, as noted in your comment before.

**Comment by ditman** [comment]
@itsjustkevin the flutter/engine changes of this CP have successfully rolled into flutter/flutter. I've updated the hashes above.

(This is a cherry-pick for flutter/engine, not 100% sure how this is handled!)

**Comment by yjbanov** [comment]
LGTM for a cherry-pick.

**Comment by itsjustkevin** [comment]
Thanks @ditman for engine changes, we don’t utilize the engine roll hash, just the engine change that has landed on main.

however, before we approve the cherry pick, we would need you to open a cherry pick to the release branch with the hash of the change that has landed on main.

mince that is done, please replace the link in the pr_link section with the link to the cherry-pick PR.

**Comment by ditman** [comment]
@itsjustkevin if I understand correctly, you want me to create a PR applying [this change](https://github.com/flutter/flutter/commit/d727aaf2e1278bea6c3300eca5db088ea5799d04) into the "release branch", but what's the **release branch**? Is it any of the `flutter-3.10-candidate.X` or something else? How do I find out what's the correct X? The latest one?

**Comment by itsjustkevin** [comment]
@ditman I need to completely rewrite the [cherry-pick process wiki](https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process), thanks for calling this out.

The issue template for creating the cherry-pick request has most of the information you need.  Under the pr_link section, there are links to the [beta](https://github.com/flutter/flutter/blob/beta/bin/internal/release-candidate-branch.version) and [stable](https://github.com/flutter/flutter/blob/stable/bin/internal/release-candidate-branch.version) release branches.

For a cherry-pick to beta, you would want to create a cherry-pick pr to `flutter-3.10-candidate.1`. 

I hope to further automate this process to the point where the cherry-pick request is automatically created once an appropriate approver has reviewed the request.

**Comment by ditman** [comment]
Ah, I totally missed those links, sorry!

I'm going to create a CP against `beta` then, which is where this bug was identified (`3.10.0-1.3.pre`). AFAIK, no need to backport this to 3.7.

**Comment by ditman** [comment]
@itsjustkevin I updated the pr_link to the PR into the beta branch, here goes:

* https://github.com/flutter/flutter/pull/125435

**Comment by ditman** [comment]
Ah no, the above cannot be right, because I'm cherry-picking the flutter/flutter hash, and not the beta branch of the flutter/engine. I'll talk to somebody :/

**Comment by ditman** [comment]
Create `flutter/engine` cherry-pick on the `beta` branch, and updated the `pr_link` above to:

* https://github.com/flutter/engine/pull/41459
