### ISSUE TITLE
When I touch the screen, I get an InputTransport error: ~ receive message failed, errno=11, seq = 17355 in Console.

### ISSUE THREAD

**Issue by azhon** [flutter/flutter#125395]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1.create a flutter app
2.run to android device
3. touch the screen, tap or move

### Expected results

no error log

### Actual results

![111](https://user-images.githubusercontent.com/20559556/233889420-3d2049cb-25e1-45f5-9e95-de5c22e89336.png)

### Code sample

<details><summary>Code sample</summary>

```dart
void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Module Bridge',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Container(
        color: Colors.white,
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
E/InputTransport( 6058): channel 'f019581 com.azhon.flutter_module_bridge/com.azhon.flutter_module_bridge.MainActivity (client)' ~ receive message failed, errno=11, seq = 17358
E/InputTransport( 6058): channel 'f019581 com.azhon.flutter_module_bridge/com.azhon.flutter_module_bridge.MainActivity (client)' ~ receive message failed, errno=11, seq = 17360
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.5, on macOS 12.5 21G72 darwin-x64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[!] Android Studio (version 2022.1)
    ✗ Unable to find bundled Java version.
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
[✓] VS Code (version 1.73.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

</details>

**Comment by huycozy** [comment]
Have you modified `MainActivity` class? Can you check if the issue also happens on a newly created Flutter project?

**Comment by azhon** [comment]
`MainActivity` has not been modified.  it also exists on the newly created Flutter project.

But I tested with two devices(HUAWEI P30、HUAWEI MATE 30 Pro) and
<img width="379" alt="111" src="https://user-images.githubusercontent.com/20559556/234152511-847bd79c-deac-4518-b010-66ef243fd401.png">
 found that only `HUAWEI MATE 30 Pro` has this problem, it seems to be happening on a specific device.

**Comment by huycozy** [comment]
Does it cause any effect to the app? Can you please try running an Android native default project and check if the same log from the console output?

**Comment by azhon** [comment]
No effect.   Running an Android native default project, has the same log from the console output.
Looks like that might be `HarmonyOS` system bug.

**Comment by huycozy** [comment]
It could be the log on OEM devices. It doesn't seem to be a Flutter framework issue, I will close this issue from here. I would suggest you file an issue to HarmonyOS's developer community for better support. Thanks!
