### ISSUE TITLE
[DisplayList] Improve DisplayList detection of non-operations

### ISSUE THREAD

**Issue by flar** [flutter/flutter#125338]
Sometimes the DisplayList is asked to record operations that can be demonstrated will have no effect. Much of the time this property can be easily determined up front while recording the DL, such as:

- The bounds of the primitive are empty
- The alpha of the color is zero
- The clip is empty

None of these conditions are tested which means we produce DisplayList objects that have extra Operation records that will perform no work.

This situation is important enough that some parts of the Flutter engine work around the problem by reading back the list of operations to see if any of them actually impact the destination surface. See:

- https://github.com/flutter/engine/blob/8b3966c1f47ecf5190a614b83a26e7bdf558e7b7/shell/common/canvas_spy.h#L58
- https://github.com/flutter/engine/blob/8b3966c1f47ecf5190a614b83a26e7bdf558e7b7/shell/common/dl_op_spy.h#L36

These classes could be eliminated if the DL performed the same tests as it was constructing the list of operations and could then return either or both of an empty bounds or a zero count of operations.

See: https://github.com/flutter/flutter/issues/125318 and https://github.com/flutter/engine/pull/40578 for examples of where this deficiency had to be worked around.

**Comment by flar** [comment]
CC @jonahwilliams

**Comment by flar** [comment]
original fix was reverted

**Comment by chinmaygarde** [comment]
Just referencing notes from the conversation on this issue during the Impeller weekly: @jonahwilliams mentioned that stuff like hairlines were missing.

**Comment by flar** [comment]
Missing how? Hairlines have no impact on whether an operation is a NOP...?

**Comment by flar** [comment]
https://github.com/flutter/engine/pull/42330 was reverted

**Comment by flar** [comment]
Please don't close issues that were re-opened for a reason. The indicated PR was reverted, so this issue is currently waiting for a new PR to land before it can be closed.

**Comment by Jasguerrero** [comment]
Why is this getting closed by rebasing local forks? Looks like it was me first and then once again 5h ago, just an fyi 
@flar

**Comment by flar** [comment]
Ah, mystery identified! It won't matter soon because the re-reland is ready to go, but this is an odd behavior of github.
