### ISSUE TITLE
Flutter Element Embedding is not working properly between different origins

### ISSUE THREAD

**Issue by diegomors** [flutter/flutter#125330]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

First of all, thanks Flutter community, specially to @ditman, @kevmoo and @malloc-error, by provide this feature. I belive this feature breaks any possible roadblocks to using Flutter on the web, allowing us to easily integrate and even migrate just parts of an existing website. It's really amazing!

**Note:** the issue may be better explained at [flutter/samples/issues/1742](https://github.com/flutter/samples/issues/1742).

## Use case

I wanna to use this feature to embed a Flutter Web app inside another website. Like a chat bot made in Flutter to embed in different e-commerce platforms as customers of the chat bot (B2B).

## Steps to reproduce

1. I cloned the [Flutter Element Embedding demo](https://github.com/flutter/samples/tree/main/experimental/element_embedding_demo).
2. I pushed just [element_embedding_demo folder](https://github.com/flutter/samples/tree/main/experimental/element_embedding_demo) to [my repository](https://github.com/diegomors/element_embedding_demo/tree/main) instead of fork all the [samples repository](https://github.com/flutter/samples).
3. I built the app using the version below and published as the original at [demo-embedding](https://demo-embedding.flutterhub.dev/#/).
  ```
  Flutter 3.10.0-7.0.pre.2 • channel master • https://github.com/flutter/flutter.git
  Framework • revision c368d64d88 (4 days ago) • 2023-04-17 11:51:25 -0400
  Engine • revision 30e1c43082
  Tools • Dart 3.1.0 (build 3.1.0-11.0.dev) • DevTools 2.23.1
  ```
4. I separated the Flutter Element Embedding demo into Flutter app and the 3rd party website at [new branch](https://github.com/diegomors/element_embedding_demo/tree/third-party_integration).
5. I created the [flutter_embed.js](https://github.com/diegomors/element_embedding_demo/blob/third-party_integration/app/web/flutter_embed.js) at Flutter app to change the `getBaseURI` (explained at workaround section below). 
6. I changed the [index.html](https://github.com/diegomors/element_embedding_demo/blob/3575b9b41398432a5a1702809d6bf357a62c0b2e/third-party/index.html#L25) at 3rd party website to point to the `flutter_embed.js`. 
7. Thus the Flutter app was loaded inside the 3rd party website and then I published the [flutter app](https://demo-app.flutterhub.dev/#/) and [3rd party website](https://demo-third-party.flutterhub.dev/#/).

### Expected results

I believe it can be fixed considering the `currentScript.src` instead of `base.getAttribute("href")` in `flutter.js` and `main.dart.js`. I'd love the community help to solve that or I'd like to know how can I change the Flutter engine to adapt `main.dart.js` file generation to fix by myself.

### Actual results

The `flutter.js` and `main.dart.js` doesn't using the correct path reference when the Flutter app come from other origin. This is needed to get other files correctly through `main.dart.js` and when it isn't happen, the app not works properly.

### Code sample

<details><summary>I changed the `flutter.js` by modifying the name to `flutter_embed.js` to use the origin dynamically. However it should be done similarly at `main.dart.js` too.</summary>

Before at `flutter.js` [link](https://github.com/flutter/flutter/blob/c9004ff822cf76848365f5dd8e034596fcbceba1/packages/flutter_tools/lib/src/web/file_generators/js/flutter.js#L15)

  ```
  function getBaseURI() {
      const base = document.querySelector("base");
      return (base && base.getAttribute("href")) || "";
   }
  ```

After at `flutter_embed.js` [link](https://github.com/diegomors/element_embedding_demo/blob/3575b9b41398432a5a1702809d6bf357a62c0b2e/app/web/flutter_embed.js#L15)

  ```
  function getBaseURI() {
      return new URL(document.currentScript.src).origin;
  }
  ```

</details>

### Screenshots or Video

<details>
<summary>The workaround using `flutter_embed.js` managed to load the `main.dart.js` correctly and then the app partially, however the `main.dart.js` doesn't have the right path to get files correctly and the app is not working properly.</summary>

![Screenshot 2023-04-21 at 15 17 30](https://user-images.githubusercontent.com/4834401/233725293-38458c69-312e-4d01-bc04-7f0ecce70cce.png)

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.10.0-7.0.pre.2, on macOS 13.3.1 22E261 darwin-arm64,
    locale en-BR)
    • Flutter version 3.10.0-7.0.pre.2 on channel master at
      /Users/diegomoraes/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c368d64d88 (4 days ago), 2023-04-17 11:51:25 -0400
    • Engine revision 30e1c43082
    • Dart version 3.1.0 (build 3.1.0-11.0.dev)
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/diegomoraes/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.3.1 22E261 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 112.0.5615.137

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by ditman** [comment]
@diegomors there's an (undocumented for now) parameter called `assetBase` that does what you need. Please, try to set it to the root location of your `main.dart.js` (and other assets) so flutter knows what's the base of all its assets.

For this you need at least Flutter `beta` and `flutter.js` for initialization. (You should be able to undo your changes to `flutter.js` file, actually).

```
      onEntrypointLoaded: async (engineInitializer: any) => {
        let appRunner = await engineInitializer.initializeEngine({
          hostElement: target,
          assetBase: "https://demo-app.flutterhub.dev/",
        });
        await appRunner.runApp();
      }
```


I've used this parameter for a future embedding demo that I'm open-sourcing in the next few weeks, but since it's still not available in `stable`, it's not properly documented on the flutter.dev site.
