### ISSUE TITLE
Update some CI servers to java 17

### ISSUE THREAD

**Issue by reidbaker** [flutter/flutter#125325]
Android has a bug https://github.com/flutter/flutter/issues/125181 where the latest AGP (google vended tooling for building android apps) does not work with the latest 3.7, 3.10 or master. 
To use the latest AGP version the host machine must have java 17 which was bundled with Android Studio Flamingo released last week to stable. 
While working on a fix I discovered that our build servers have java 11 and cannot build my patch.

**Comment by reidbaker** [comment]
It is possible that deployment of this bug is blocked by 
https://github.com/flutter/flutter/issues/122213 
and 
https://github.com/flutter/flutter/issues/123636

**Comment by reidbaker** [comment]
It appears that this bug is blocking test adoption of AGP version 8.0. There are some packages (webview_flutter_android) that have updated to AGP version 8 but their example apps have not and the examples are what are used to tests. 

Notes
Java 17 required by AGP 8.0 
https://developer.android.com/build/releases/gradle-plugin#jdk-17-agp
Java 11 bytecode started shipping in AGP 7.4. 
https://developer.android.com/build/releases/past-releases/agp-7-4-0-release-notes#jvm-11-bytecode

**Comment by reidbaker** [comment]
Example failed build
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8783182333869110145/+/u/run_test.dart_for_build_tests_shard_and_subshard_1_3/test_stdout
```
A problem occurred evaluating project ':app'.
[        ] > Failed to apply plugin 'com.android.internal.application'.
[        ]    > Android Gradle plugin requires Java 17 to run. You are currently using Java 11.
[        ]       Your current JDK is located in /b/s/w/ir/cache/java
[        ]       You can try some of the following options:
[        ]        - changing the IDE settings.
[        ]        - changing the JAVA_HOME environment variable.
[        ]        - changing `org.gradle.java.home` in `gradle.properties`.
```

**Comment by camsim99** [comment]
Assigned and priority set by conversation with @reidbaker

**Comment by yusuf-goog** [comment]
New instances for the following packages have been created with openjdk 17 and tagged with `version:17`:

https://chrome-infra-packages.appspot.com/p/flutter/java/openjdk
https://chrome-infra-packages.appspot.com/p/flutter_internal/java/openjdk

I ran a sampling of builds with these packages to sanity check them, and it seems to be working. There are a couple of failures that have been send to @reidbaker for further analysis.

It should be ready to use for testing/deployment.

**Comment by reidbaker** [comment]
We have had a series of flakes that I think have been resolved but now some servers have been able to be run with java 17 and at least one windows, linux and mac machine is amongst the group. Resolving.
