### ISSUE TITLE
test_ownership check not working

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#125328]
I believe the TESTOWNERS check should have failed for https://github.com/flutter/flutter/pull/125226 since I renamed the `flutter_tool_startup__windows` etc platform tasks to `flutter_tool_startup`.  However the check says:
```
Windows flutter_tool_startup__windows: jensjoha
Linux flutter_tool_startup__linux: jensjoha
Mac_benchmark flutter_tool_startup__macos: jensjoha
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8783275320364821969/+/u/validate_test_ownership/stdout

We also saw this on https://github.com/flutter/flutter/pull/125044#issuecomment-1513573105

cc @keyonghan #87310

**Comment by jmagman** [comment]
The check did fail when I tried to update the TESTOWNERS in the same PR:
```
# Test ownership check failed.
Builders missing owner: [Windows flutter_tool_startup__windows, Linux flutter_tool_startup__linux, Mac_benchmark flutter_tool_startup__macos]
Please define ownership in https://github.com/flutter/flutter/blob/master/TESTOWNERS
```
https://github.com/flutter/flutter/pull/125226/checks?check_run_id=12935458956

**Comment by keyonghan** [comment]
Test owner validation assumes `task name` same as the target name apart from the platform. Instead, we should use the `task_name` property to be consistent with the real `<task>.dart`
