### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by KumarLakshmanan** [flutter/flutter#125379]
https://codelabs.developers.google.com/codelabs/flutter-in-app-purchases#4

in this step you need to specify to add the `<uses-permission android:name="com.android.vending.BILLING" />` permission to the manifest file

**Comment by danagbemava-nc** [comment]
Using `<uses-permission android:name="com.android.vending.BILLING">` is deprecated. If you are using the latest version of the plugin, the right permission `<uses-permission android:name="com.google.android.play.billingclient.version" />` will be automatically injected into your `AndroidManifest.xml`. 

If there's a specific issue you're facing with the plugin, kindly file a new issue and provide detailed steps to reproduce it. 

Closing from here as that permission is no longer valid. 

Thank you
