### ISSUE TITLE
Alerting for stalled autoroller PRs

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#125451]
The Engine -> Framework roll PR here https://github.com/flutter/flutter/pull/125412 had it's presubmit checks queuing for >10 hours before it was noticed.

Ideally we wouldn't have issues where the presubs can get stuck in queueing or never start, but when it does happen, and queue times are so far out of SLO, the infra gardener and engine sheriff should be notified so that we can get things unstuck.

cc @ricardoamador @keyonghan

**Comment by keyonghan** [comment]
We also need to collect the start_time of `check run` and `check status` when calling API or graphQL.

**Comment by keyonghan** [comment]
Validated that we did get the log expected 
```
auto_submit: Pull request https://github.com/flutter/engine/pull/48879 from engine repo auto roller has been running over 2 hours due to: [Windows windows_unopt, Windows windows_host_engine, Windows windows_android_aot_engine, Mac mac_ios_engine, Linux mac_unopt, Mac mac_host_engine, Mac mac_clang_tidy, Linux mac_android_aot_engine, Linux linux_unopt, Linux linux_web_engine, Linux linux_license, Linux linux_android_debug_engine, Linux linux_android_aot_engine, Linux linux_host_desktop_engine, Linux linux_host_engine, Linux linux_arm_host_engine, Linux linux_clang_tidy, Linux linux_fuchsia, Linux Fuchsia FEMU, Windows windows_arm_host_engine, triage, Linux Web Framework tests, Linux Framework Smoke Tests, cla/google, ci.yaml validation]
```

Also set up an alert `Stale engine PR` for both engine and infra gardeners.
