### ISSUE TITLE
[CP] Update to clean up messaging for `package:unified_analytics`

### ISSUE THREAD

**Issue by eliasyishak** [flutter/flutter#125446]
### issue_link

https://github.com/flutter/flutter/issues/124808

### Commit Hash

51b23bc, ca3a900

### Target

beta

### pr_link

https://github.com/flutter/flutter/pull/125445

### Impacted Users

All flutter users

### Impact Description

With the new analytics package being introduced, we wanted to automatically opt out users that have already opted out in the past in the new system. This makes the necessary changes to flutter to allow the package to handle the legacy opt out. Originally, we incorrectly put that logic into flutter when it should have lived in the package.

### Workaround

No workarounds at the moment.

### Risk

low

### Test Coverage

yes

### Validation Steps

Events won't be sent for legacy opted out users. It can also be checked by looking at `$HOME/.dart-tool/dart-flutter-telemetry.config`

**Comment by itsjustkevin** [comment]
@christopherfujino could you take a look?

**Comment by christopherfujino** [comment]
LGTM

**Comment by eliasyishak** [comment]
Completed yesterday, closing

**Comment by itsjustkevin** [comment]
Reopening, will close once it’s landed in a release.
