### ISSUE TITLE
[google_sign_in]: `source release 1.8 requires target release 1.8` error with older AGP/Gradle versions

### ISSUE THREAD

**Issue by MohamedSafvanKP-MSIL** [flutter/flutter#125482]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. take the latest google_sign_in: ^6.1.0 pub upgrade
2. it will point to google_sign_in_android: ^6.1.11 
3. and run the application.

note: it is working with google_sign_in_android: 6.1.9 
issue facing from the latest version.

### Expected results

The build should run as google_sign_in_android: 6.1.9 version.

### Actual results

Execution failed for task ':google_sign_in_android:compileReleaseJavaWithJavac'.
> warning: source release 1.8 requires target release 1.8

 Build got failed.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':google_sign_in_android:compileReleaseJavaWithJavac'.
> warning: source release 1.8 requires target release 1.8
```
in android build.gradle using same java versions.
```console
        targetCompatibility JavaVersion.VERSION_1_8
        sourceCompatibility JavaVersion.VERSION_1_8
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.8, on macOS 13.2 22D49 darwin-arm64, locale en-IN)
    • Flutter version 3.7.8 on channel stable at /Users/mohmedsafvankp/flutter_sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 90c64ed42b (5 weeks ago), 2023-03-21 11:27:08 -0500
    • Engine revision 9aa7816315
    • Dart version 2.19.5
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/mohmedsafvankp/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2023.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.76.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 31) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.2 22D49 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

**Comment by stuartmorgan** [comment]
Interesting; I didn't include an explicit `targetCompatibility` because current docs say it defaults to the value of `sourceCompatibility`. It sounds like that wasn't always the case, so I'll add it in.

What version of the Android Gradle Plugin and of Gradle are you using in your project?

**Comment by caua-n** [comment]
I have the same issue, cant debug and cant compile. Nothing 
![image](https://user-images.githubusercontent.com/122560967/234281846-eab00b9d-7afd-4093-ac05-a17e8ca48cf0.png)

**Comment by stuartmorgan** [comment]
> I have the same issue

What version of the Android Gradle Plugin and of Gradle are you using in your project?

**Comment by MohamedSafvanKP-MSIL** [comment]
@stuartmorgan  kindly find my grade version details:
classpath 'com.android.tools.build:gradle:4.1.1'
and 
https\://services.gradle.org/distributions/gradle-6.5-all.zip

**Comment by EwanZaidi** [comment]
Same issue with me, how can I fix it? Need to deploy to play store immediately

**Comment by stuartmorgan** [comment]
If you need an immediate workaround, you can pin an earlier version of `google_sign_in_android`, as noted in the original report. Alternately, I expect that updating the version of AGP and Gradle used in your project would resolve the issue.

**Comment by caua-n** [comment]
> > I have the same issue
> 
> What version of the Android Gradle Plugin and of Gradle are you using in your project?

classpath 'com.android.tools.build:gradle:4.1.0'

**Comment by MohamedSafvanKP-MSIL** [comment]
Now when I'm using the latest google_sign_in_android: ^6.1.13
Unble to sync the native Android project.
getting following errors.
```
1: Task failed with an exception.
-----------
* Where:
Build file '/Users/mohmedsafvankp/.pub-cache/hosted/pub.dev/google_sign_in_android-6.1.13/android/build.gradle' line: 24

* What went wrong:
A problem occurred evaluating project ':google_sign_in_android'.
> No signature of method: build_n3eadu0qz7ey661tsmy5sjq1.android() is applicable for argument types: (build_n3eadu0qz7ey661tsmy5sjq1$_run_closure2) values: [build_n3eadu0qz7ey661tsmy5sjq1$_run_closure2@73fd87a2]

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating project ':google_sign_in_android'.
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.lambda$apply$0(DefaultScriptPluginFactory.java:133)
```

and 
```
Task failed with an exception.
-----------
* Where:
Script '/Users/mohmedsafvankp/flutter_sdk/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 463

* What went wrong:
A problem occurred configuring project ':google_sign_in_android'.
> Cannot invoke method substring() on null object

```
