### ISSUE TITLE
[Proposal] `InputDecorationTheme.merge()`

### ISSUE THREAD

**Issue by navaronbracke** [flutter/flutter#125471]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I had an internal question stating that someone wanted to merge `InputDecoration`s, like how `IconThemeData` has a `merge()` method. However InputDecoration does not have a merge method.

### Proposal

Add a `merge` method to `InputDecoration`, using the `copyWith()` method.

**Comment by HansMuller** [comment]
This seems like a reasonable proposal although we don't have plans to pursue it in the near term. We'd welcome a PR that adds the feature.

**Comment by TahaTesser** [comment]
@HansMuller 

Need feedback on this https://github.com/flutter/flutter/pull/129010#issuecomment-1595018996

**Comment by TahaTesser** [comment]
@navaronbracke 

if I am not mistaken, the proposal for `merge` is for the `InputDecorationTheme`.  As you mentioned `IconThemeData`.  


Here I made an explainer for this, stating the difference.


![Untitled drawio (1)](https://github.com/flutter/flutter/assets/48603081/cba239e3-b89f-473a-ae7f-148bb52a3bea)

Currently we can use `applyDefaults` to override defaults for the `InputDecoration`.  I use the same in my date picker PR for input mode. https://github.com/flutter/flutter/pull/128950


I'm adding [InputDecorationTheme.merge](https://github.com/flutter/flutter/pull/129011)

So the idea is to merge the `theme.inputDecorationTheme` using `InputDecorationTheme.theme` and apply to it to input decoration. Do you concur?

**Comment by TahaTesser** [comment]
> So if I understand correctly (thanks for the diagram!), the theme has a merge method, and applyDefaults acts like merge, but for a single InputDecoration? (although it takes an InputDecorationTheme, not an InputDecoration)

That's right. `appylyDefaults` calls `InputDecoration.copyWith` (just like `something.merge` does). Effectively it's `merge` for `InputDecoration`.

>  If that is the case, then I do agree (although we maybe should mention in the docs that applyDefaults can be used to merge one InputDecoration with another)

True.

**Comment by navaronbracke** [comment]
One thing though, the original request I got that lead me to filing the issue was that a colleague wanted to do:

```
final InputDecoration i1 = InputDecoration();
final InputDecoration i2 = InputDecoration();

final InputDecoration merged = i1.merge(i2);
```

which isn't possible with `applyDefaults()` _directly_ ?

**Comment by TahaTesser** [comment]
You really want to merge themes this way not decoration itself.

Merge `ThemeData.inputDecorationTheme` with a local theme then use it to update input decoration for a widget for instance.

Unless some object like theme data returns `InputDecoration` directly then i can see the reasons to merge multiple InputDecorations, Is it the case?

**Comment by navaronbracke** [comment]
> Merge ThemeData.inputDecorationTheme with a local theme then use it to update input decoration for a widget for instance.

That's what I would have done, yes. I just had a quick chat with the colleague that brought up the idea.
Apparently he could not style the fill color using the input decoration for error states.

Not sure if that is still the case (it's been a while since the original problem came up)
