### ISSUE TITLE
[go_router] How to remove other routes in the routing line?

### ISSUE THREAD

**Issue by lizhuoyuan** [flutter/flutter#125464]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

My current routing line is A -> B -> C -> D now, I am on page D , i want to remove B . What should I do? I searched in the issue and found no answer

### Proposal

Provide a method to remove a route in the routing line

**Comment by huycozy** [comment]
Can you please be more specific on the reason/use case that needs to remove a route?

**Comment by lan2000** [comment]
I have encountered similar situations but did not find a better answer.

[[How to close a specific Flutter AlertDialog?](https://stackoverflow.com/questions/63262042/how-to-close-a-specific-flutter-alertdialog)](https://stackoverflow.com/questions/63262042/how-to-close-a-specific-flutter-alertdialog)

[[how to close a specific dialog in flutter?](https://stackoverflow.com/questions/74554870/how-to-close-a-specific-dialog-in-flutter)](https://stackoverflow.com/questions/74554870/how-to-close-a-specific-dialog-in-flutter?noredirect=1)

**Comment by huycozy** [comment]
Thank you for more information. I see there's an open issue addressing the case you described https://github.com/flutter/flutter/issues/99112 (removeRoute is also mentioned there).

Closing this issue in favor of that issue, so please follow up on it for further updates.
