### ISSUE TITLE
PlatformViewLink getting white background, when upgrade flutter to 3.7.12

### ISSUE THREAD

**Issue by manhtran-itr** [flutter/flutter#125460]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Our app uses the Chime SDK framework and customing the native view in Android using PlatformViewLink. It works OK until we upgrade from 3.0.5 to the newest Flutter version 3.7.12. 

We found that if we switch to AndroidView, it works but when switching to PlatformViewLink, it gets white color for the whole view. 

### Expected results

The PlatformViewLink should display the video screen

### Actual results

The PlatformViewLink displays the white screen.

### Code sample

<details><summary>Code sample</summary>

```dart
      return PlatformViewLink(
        viewType: 'ChimeDefaultVideoRenderView',
        surfaceFactory:
            (BuildContext context, PlatformViewController controller) {
          return AndroidViewSurface(
            controller: controller as AndroidViewController,
            gestureRecognizers: const <Factory<OneSequenceGestureRecognizer>>{},
            hitTestBehavior: PlatformViewHitTestBehavior.opaque,
          );
        },
        onCreatePlatformView: (PlatformViewCreationParams params) {
          final AndroidViewController controller =
              PlatformViewsService.initExpensiveAndroidView(
            id: params.id,
            viewType: 'ChimeDefaultVideoRenderView',
            layoutDirection: TextDirection.ltr,
            creationParams: creationParams,
            creationParamsCodec: const StandardMessageCodec(),
            onFocus: () => params.onFocusChanged,
          );
          controller
              .addOnPlatformViewCreatedListener(params.onPlatformViewCreated);
          controller.create();
          return controller;
        },
      );
```

</details>

### Screenshots or Video

<details>
</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Hi @manhtran-itr 

Please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) in a repository so that we can clone and run to investigate this issue. And please provide the output of `flutter doctor -v` as well.

Also, you may try this on the latest Flutter master channel to see if it works or not. 

Thanks!
