### ISSUE TITLE
FadeInImage should support altering saturation

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#12541]
According to the Material Design guidelines images that are loading should also alter saturation, as to produce a feeling of images being developed.

https://material.io/guidelines/patterns/loading-images.html#loading-images-behavior

**Comment by Hixie** [comment]
cc @yjbanov

**Comment by bleroux** [comment]
@guidezpl 
It seems that animating saturation while loading an image was only in M1: https://m1.material.io/patterns/loading-images.html#loading-images-usage.
Can you confirm that there is no such requirement in M2 and M3?

**Comment by guidezpl** [comment]
Can confirm there's no such requirement as of now.

**Comment by bleroux** [comment]
Thanks!
Closing this issue as it was specific to Material 1.
