### ISSUE TITLE
DlOpSpy could be replaced by operation culling in DisplayListBuilder

### ISSUE THREAD

**Issue by flar** [flutter/flutter#125403]
The DlOpSpy class introduced in https://github.com/flutter/engine/pull/40578 could likely be replaced by simple tests on the DisplayList object itself if a fix for https://github.com/flutter/flutter/issues/125338 is landed.

**Comment by chinmaygarde** [comment]
Closing in favor of https://github.com/flutter/flutter/issues/125318
