### ISSUE TITLE
if serviceWorker is null, do not console.warn()

### ISSUE THREAD

**Issue by sgehrman** [flutter/flutter#125404]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

First of all this form is very annoying. I don't know why you thought this would help. I liked it better when flutter was cool.

I have a flutter web app. I can't use the service worker inside a Safari extension (cashes variable is null)

So I removed the serviceWorker and now I get a message in the console that is annoying.

Exception while loading service worker: Error: Service worker not supported (or configured).
    at FlutterServiceWorkerLoader.loadServiceWorker (flutter.js:122:11)
    at FlutterLoader.loadEntrypoint (flutter.js:358:33)

if the service worker is null why are you even trying to serviceWorkerLoader.loadServiceWorker?

see the code below in that other annoying box below.

Here's in my index.html

```
  <script>
    window.addEventListener('load', function (ev) {
      // Download main.dart.js
      _flutter.loader.loadEntrypoint({
        // service worker doesn't work on Safari.  cashes var not available
        // serviceWorker: {
        //   serviceWorkerVersion: serviceWorkerVersion,
        // },
        onEntrypointLoaded: function (engineInitializer) {
          engineInitializer
            .initializeEngine({
              renderer: 'canvaskit',
              canvasKitBaseUrl: '/canvaskit/'
            })
            .then(function (appRunner) {
              appRunner.runApp();
            });
        },
      });
    });
  </script>
```
  

### Expected results

no console message on web site load.

### Actual results

Exception while loading service worker: Error: Service worker not supported (or configured).
    at FlutterServiceWorkerLoader.loadServiceWorker (flutter.js:122:11)
    at FlutterLoader.loadEntrypoint (flutter.js:358:33)
  

### Code sample

<details><summary>Code sample</summary>

```
  class FlutterLoader {
    /**
     * Initializes the Flutter web app.
     * @param {*} options
     * @returns {Promise?} a (Deprecated) Promise that will eventually resolve
     *                     with an EngineInitializer, or will be rejected with
     *                     any error caused by the loader. Or Null, if the user
     *                     supplies an `onEntrypointLoaded` Function as an option.
     */
    async loadEntrypoint(options) {
      const { serviceWorker, ...entrypoint } = options || {};

      // A Trusted Types policy that is going to be used by the loader.
      const flutterTT = new FlutterTrustedTypesPolicy();

if (serviceWorker != null) {   <<=========================== ADD THIS
      // The FlutterServiceWorkerLoader instance could be injected as a dependency
      // (and dynamically imported from a module if not present).
      const serviceWorkerLoader = new FlutterServiceWorkerLoader();
      serviceWorkerLoader.setTrustedTypesPolicy(flutterTT.policy);
      await serviceWorkerLoader.loadServiceWorker(serviceWorker).catch(e => {
        // Regardless of what happens with the injection of the SW, the show must go on
        console.warn("Exception while loading service worker:", e);
      });

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console

$ flutter doctor -v
[✓] Flutter (Channel stable, 3.7.12, on Debian GNU/Linux 11 (bullseye) 5.10.0-21-amd64, locale en_US.UTF-8)
    • Flutter version 3.7.12 on channel stable at /home/steve/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (6 days ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc4)
    • Android SDK at /home/steve/Android/Sdk
    • Platform android-33, build-tools 31.0.0-rc4
    • Java binary at: /home/steve/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Debian clang version 11.0.1-2
    • cmake version 3.15.2
    • ninja version 1.8.2
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.2)
    • Android Studio at /home/steve/android-studio
    • Flutter plugin version 68.1.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.77.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.62.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Debian GNU/Linux 11 (bullseye) 5.10.0-21-amd64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 112.0.5615.165



```

</details>

**Comment by huycozy** [comment]
>         // serviceWorker: {

Hi @sgehrman, I'm not sure why you comment this out. Is it accidental or intentional? Can you be more specific?

Also, I can not reproduce the error from my end. Can you please share a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this?

**Comment by huycozy** [comment]
Thanks for filing the issue, @sgehrman
I've tried reproducing this by commenting `serviceWorker` out but I only see this message from the console in the browser:

```
Null serviceWorker configuration. Skipping.
```

And I can't see such the exception log. I wonder if something is missing in the reproduction steps above.
