### ISSUE TITLE
[webview_flutter] Windows support

### ISSUE THREAD

**Issue by yegor-pelykh** [flutter/flutter#125434]
### Is there an existing issue for this?

- [x] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

The package `webview_flutter` does not have Windows support.

### Proposal

Could you please implement Windows support?

**Comment by stuartmorgan** [comment]
Duplicate of https://github.com/flutter/flutter/issues/37597
