### ISSUE TITLE
engine v2 recipes should have depot_tools on path

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#125442]
In https://github.com/flutter/engine/pull/41455 I'm getting failures that appear to be related to not finding depot_tools.

The old recipes have lines like this:

```py
  # Various scripts we run assume access to depot_tools on path for `ninja`.
  with api.context(cwd=cache_root, env=env,
                   env_prefixes=env_prefixes), api.depot_tools.on_path():
```

But the v2 builders seem to not have it, or at least not where I can obviously find it.

**Comment by dnfield** [comment]
An example of a failing build:

https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20Engine%20Drone/78192/overview

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8782899262658411697/+/u/gn_--runtime-mode_release_--no-lto_--windows-cpu_arm64/stdout

Which is failing with this script:

https://github.com/flutter/buildroot/blob/37fa2f05f6b009a1a92879c03b0871d97100aa2d/tools/find_depot_tools.py#L45

**Comment by dnfield** [comment]
(This is currently blocking our ability to roll the vs_toolchain in the engine repo, which is required to roll angle and vulkan-deps)

**Comment by godofredoc** [comment]
Can you please a link to the main build?

**Comment by dnfield** [comment]
https://flutter-review.googlesource.com/c/recipes/+/42462 fixed this
