### ISSUE TITLE
ValueListenableBuilder not updating

### ISSUE THREAD

**Issue by handika231** [flutter/flutter#125450]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

i try using valuelistenablebuilder instead of setState method. 
i have issue with this, when I using code like this:

ValueListenableBuilder(
      valueListenable: _counter,
      builder: (context, value, child) {
        return child!;
      },
      child: ... )
UI not update, but if not using child like this:
   builder: (context, value, child) {
        return Scaffold(
          floatingActionButton: FloatingActionButton(
            onPressed: () {
              _counter.value++;
            },
          ),
          appBar: AppBar(
            backgroundColor: Colors.black,
            title: const Text('Home Page'),
            foregroundColor: Colors.white,
            centerTitle: true,
          ),
          body: Center(
            child: Text(
              'Value counter : ${_counter.value}',
              style: const TextStyle(fontSize: 30),
            ),
          ),
        );
      },

UI can updated

### Expected results

i expect that there is change in ui

### Actual results

But, what happens is that the UI is not updated, have to do hot reload to make changes

### Code sample

<details><summary>Code sample</summary>

```dart
class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  final ValueNotifier _counter = ValueNotifier(0);
  @override
  Widget build(BuildContext context) {
    return ValueListenableBuilder(
      valueListenable: _counter,
      builder: (context, value, child) {
        return child!;
      },
      child: Scaffold(
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            _counter.value++;
          },
        ),
        appBar: AppBar(
          backgroundColor: Colors.black,
          title: const Text('Home Page'),
          foregroundColor: Colors.white,
          centerTitle: true,
        ),
        body: Center(
          child: Text(
            'Value counter : ${_counter.value}',
            style: const TextStyle(fontSize: 30),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
$ flutter doctor -v
[√] Flutter (Channel stable, 3.7.11, on Microsoft Windows [Version 10.0.22621.1555], locale id-ID)
    • Flutter version 3.7.11 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f72efea43c (13 days ago), 2023-04-11 11:57:21 -0700
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Android\Sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = C:\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\HP Gaming\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32616.157
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[√] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.2.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 212.5080.8

[√] IntelliJ IDEA Ultimate Edition (version 2022.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2021.3.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 222.3739.24

[√] VS Code (version 1.77.3)
    • VS Code at C:\Users\HP Gaming\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.27.0

[√] Connected device (5 available)
    • CPH1819 (mobile)                   • BYDEKJOBJZIN4DIF • android-arm64  • Android 10 (API 29)
    • Android SDK built for x86 (mobile) • emulator-5554    • android-x86    • Android 7.1.1 (API 25) (emulator)
    • Windows (desktop)                  • windows          • windows-x64    • Microsoft Windows [Version 10.0.22621.1555]
    • Chrome (web)                       • chrome           • web-javascript • Google Chrome 112.0.5615.138
    • Edge (web)                         • edge             • web-javascript • Microsoft Edge 112.0.1722.58

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by sunnyxibei** [comment]
you should call the counter's value inside the builder 

class _HomePageState extends State<HomePage> {
  final ValueNotifier _counter = ValueNotifier(0);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          _counter.value++;
        },
      ),
      appBar: AppBar(
        backgroundColor: Colors.black,
        title: const Text('Home Page'),
        foregroundColor: Colors.white,
        centerTitle: true,
      ),
      body: Center(
        child: ValueListenableBuilder(
          valueListenable: _counter,
          builder: (context, value, child) {
            return Text(
              'Value counter : ${_counter.value}',
              style: const TextStyle(fontSize: 30),
            );
          },
        ),
      ),
    );
  }
}
