### ISSUE TITLE
[image_picker]: Adding portrait mode in iOS/Android camera for image_picker

### ISSUE THREAD

**Issue by csarigumba** [flutter/flutter#125486]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I would like to use the Portrait mode feature of the camera of either the iOS or Android. Currently, I'm using the imagepicker library to capture images. However, I noticed that there is no option available to enable portrait mode in the library. Can someone please guide me on how to enable the portrait mode feature in the camera using the imagepicker library?

Thanks!

### Proposal

Package

**Comment by darshankawar** [comment]
For reference: there's a similar open request for camera package. https://github.com/flutter/flutter/issues/113670
Treating this as a similar proposal for image_picker package.

**Comment by stuartmorgan** [comment]
The UI for taking photos in `image_picker` is OS-provided, and has very limited configurability. There's no way to configure this in the system APIs as far as I can tell, so this isn't something that can be provided in the plugin.

Closing as out of scope. Non-trivial camera use cases need to use a camera plugin, not `image_picker`.

**Comment by csarigumba** [comment]
@stuartmorgan @darshankawar 

Thank you for your feedback. 
I'd like to ask one more question: In Flutter, how can I capture a photo with depth mode? Is it possible? I would greatly appreciate it if you could point me in the right direction. Thanks!
