### ISSUE TITLE
Log messages are missing leading spaces when running in iOS Simulator

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#12544]
Leading spaces from log messages are omitted when a message is printed with `print` while running in the iOS simulator. This makes various trees that you can print to debug Flutter apps hard to read..

Example (output of semantics tree after pressing "S" in terminal:

```
SemanticsNode#0(Rect.fromLTRB(0.0, 0.0, 640.0, 1136.0))
└SemanticsNode#1(Rect.fromLTRB(0.0, 0.0, 320.0, 568.0) scaled by 2.0x)
└SemanticsNode#2(Rect.fromLTRB(0.0, 0.0, 320.0, 568.0))
└SemanticsNode#3(Rect.fromLTRB(150.0, 234.0, 170.0, 334.0))
└SemanticsNode#4(Rect.fromLTRB(0.0, 40.0, 20.0, 60.0), actions: [tap])
```

Expected output:

```
SemanticsNode#0(Rect.fromLTRB(0.0, 0.0, 640.0, 1136.0))
 └SemanticsNode#1(Rect.fromLTRB(0.0, 0.0, 320.0, 568.0) scaled by 2.0x)
  └SemanticsNode#2(Rect.fromLTRB(0.0, 0.0, 320.0, 568.0))
   └SemanticsNode#3(Rect.fromLTRB(150.0, 234.0, 170.0, 334.0))
    └SemanticsNode#4(Rect.fromLTRB(0.0, 40.0, 20.0, 60.0), actions: [tap])
```

/cc @cbracken

**Comment by cbracken** [comment]
Seems like a likely bet this is a quick fix to the simulator log scrape regex.

**Comment by cbracken** [comment]
Verified that a minor tweak to `_mapRegex` fixes this issue on an iOS 11 simulator. I need to test this on iOS 8, 9, and 10 simulators as well.

**Comment by xster** [comment]
Seems like this is no longer an issue on head.
