### ISSUE TITLE
[Android TV][TextField] Soft keyboard is not responsive once text field received focus

### ISSUE THREAD

**Issue by sck-v** [flutter/flutter#125541]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run sample app on a real device - emulator seems to be working fine and looks like only certain devices are affected
2. Use d-pad to gain focus on a text field
3. Activate it, ensure keyboard is opened
4. Try to navigate through keyboard
5. Flutter activity still have focus and d-pad is navigating through elements behind keyboard

https://user-images.githubusercontent.com/1435744/234511819-95506352-b0c3-48db-a7fa-39647041e6f7.MOV

### Actual results

Soft keyboard should be navigable

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.7.11, on macOS 13.3.1 22E261 darwin-x64, locale ru)
    ! Warning: `dart` on your path resolves to /usr/local/Cellar/dart/2.15.1/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/ivan_kryak/fvm/versions/3.7.11. Consider adding /Users/ivan_kryak/fvm/versions/3.7.11/bin to the front of your path.
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.77.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 2 categories.
</details>

**Comment by huycozy** [comment]
Hi @sck-v 
What is your TV model? Do you notice any special logs from the console output? 

Also, can you please check this on the latest Flutter master channel? Thanks!

**Comment by sck-v** [comment]
We have multiple reports from various of devices, so no exact correlation here

- Direct TV Stream box
- Google Chromecast
- Sony BRAVIA, Model 55A805
- LG, Model 24LM520S-WU / webOS TV Version 3.8.0-6140301 (dreadlocks2-dunggir)

I will check master branch and get back to you

**Comment by huycozy** [comment]
Unfortunately, I don't have any similar device to test this. Can you please also check this on an Android native project with simple EditText?

**Comment by huycozy** [comment]
When listening the key events from d-pad (Android TV emulator), I notice events are not reported with d-pad input but with host machine keyboard input (macOS). There are only events when entering/existing the keyboard but not with input events or arrow keys.

<details>
<summary>Demo - Android TV emulator</summary>

https://user-images.githubusercontent.com/104349824/235080622-76f1a96b-f55a-41d1-8455-8f01f0fa0cda.mp4

</details>

Can you please try below sample code and notice if you can see d-pad input key events from the console?

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  RawKeyboard.instance.addListener((e) {
    debugPrint('${e.character} - ${e.logicalKey} - ${e.physicalKey}');
  });
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Container(
            margin: const EdgeInsets.all(20),
            child:
            const TextField(
              decoration: InputDecoration.collapsed(hintText: 'Enter'),
            ),
            // _buildTextComposer(),
          ),
        ),
      ),
    );
  }

  _buildTextComposer() {
    return RawKeyboardListener(
      focusNode: FocusNode(),
      onKey: (e) {
        debugPrint('2. ${e.character} - ${e.logicalKey} - ${e.physicalKey}');
      },
      child: const Center(
        child: TextField(
          decoration: InputDecoration(hintText: "Enter something"),
        ),
      ),
    );
  }
}
```
</details>
