### ISSUE TITLE
Getting worng data format :confused: :confused:

### ISSUE THREAD

**Issue by lar-asmaoui** [flutter/flutter#125554]
Hi,

I run this code and I got data like this :
28.0028.0028.0028.0028.0028.00

I want to print each value per each line.please help.
--------------------------------------------------------------
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_libserialport/flutter_libserialport.dart';

class SerialPorts extends ChangeNotifier {
List _ports = SerialPort.availablePorts;
String _res = "";
SerialPort? printerPort;
SerialPort? scalePort;

List get availablePorts => _ports;

double get getData => double.parse(_res);
set setData(String data) {
_res = data;
notifyListeners();
}

void setPortName(String name) {}

void listAllPorts() {
_ports = SerialPort.availablePorts;
notifyListeners();
}

Future connect(String portName) async {
try {
printerPort = SerialPort(portName);
printerPort!.open(mode: 1);
printerPort!.config = SerialPortConfig()
..baudRate = 9600
..bits = 8
..stopBits = 1
..parity = SerialPortParity.none
..rts = SerialPortRts.flowControl
..cts = SerialPortCts.flowControl
..dsr = SerialPortDsr.flowControl
..dtr = SerialPortDtr.flowControl
..setFlowControl(SerialPortFlowControl.rtsCts);
if (printerPort!.isOpen) {
read();
notifyListeners();
}
} catch (e) {
print(e.toString());
printerPort!.close();
notifyListeners();
}
}

Future read() async {
try {
SerialPortReader reader = SerialPortReader(printerPort!, timeout: 3000);
Stream upcomingData = reader.stream.map(
(data) => String.fromCharCodes(data).replaceAll('\r\n', ''),
);
upcomingData.listen((data) {
_res += data.replaceAll('\r\n', '');
print(_res);
});
notifyListeners();
} on SerialPortError catch (err, _) {
if (printerPort!.isOpen) {
printerPort!.close();
print(SerialPort.lastError);
notifyListeners();
}
}
}

void disconnect() {
printerPort!.dispose();
scalePort!.dispose();
printerPort!.close();
scalePort!.close();
print("disconnected !!");
notifyListeners();
}
}

**Comment by stuartmorgan** [comment]
Issues with third-party packages need to be reported to the package's authors.

Closing as this is not an issue in Flutter itself.
