### ISSUE TITLE
Dart pad slowed down.

### ISSUE THREAD

**Issue by nero-angela** [flutter/flutter#125532]
## What happened?
When I run the following [DartPad](https://dartpad.dev/?id=499b8d1e6a210006ea6536bedea35c32) in chrome browser, a few months ago I got results around 600ms and 300ms, but when I ran the same code recently I got results of 2900ms and 1000ms. Results are three times slower than before.

## Steps to reproduce problem
[DartPad link](https://dartpad.dev/?id=499b8d1e6a210006ea6536bedea35c32)
<details><summary>source code</summary>

```dart
void main() async {
  print("========= fetchA =========");
  /// expected time : 600ms
  await executionTime('fetchA', fetchA);

  print("========= fetchB =========");
  /// expected time : 300ms
  await executionTime('fetchB', fetchB);

}

Future<List<int>> fetchA() async {
  return [
    await Future.delayed(const Duration(milliseconds: 300), () {
      print(1);
      return 1;
    }),
    await Future.delayed(const Duration(milliseconds: 200), () {
      print(2);
      return 2;
    }),
    await Future.delayed(const Duration(milliseconds: 100), () {
      print(3);
      return 3;
    }),
  ];
}

Future<List<int>> fetchB() async {
  return await Future.wait([
    Future.delayed(const Duration(milliseconds: 300), () {
      print(1);
      return 1;
    }),
    Future.delayed(const Duration(milliseconds: 200), () {
      print(2);
      return 2;
    }),
    Future.delayed(const Duration(milliseconds: 100), () {
      print(3);
      return 3;
    }),
  ]);
}

Future<void> executionTime(
  String label,
  Future Function() businessLogic,
) async {
  final stopwatch = Stopwatch()..start();
  await businessLogic();
  print('$label : ${stopwatch.elapsedMilliseconds}ms');
}
```
</details> 

## Additional info
This is a code written for synchronous and asynchronous learning in DartPad, but I have identified a problem that takes a long time to run unlike before. At first, I reported it to the https://github.com/dart-lang/dart-pad/issues/2499, but I made it a flutter issue at @domesticmouse's suggestion.

### 23.04.25 dart pad result
- Based on Flutter 3.7.12 Dart SDK 2.19.6
<img width="1053" alt="today dart pad result" src="https://user-images.githubusercontent.com/26322627/234233626-42ddebfb-67da-45ca-acf7-66927f734ab7.png">

### Previous dart pad result
<img width="1053" alt="past dart pad result" src="https://user-images.githubusercontent.com/26322627/234224363-a7d8370a-9036-437b-a944-3d5d5cb00f8e.png">

### Local dart project result
When I create a dart project and run the same code locally, there seems to be no problem.
<img width="711" alt="스크린샷 2023-04-26 오후 12 17 36" src="https://user-images.githubusercontent.com/26322627/234460817-24c697ef-e2f6-47f5-96f0-6f99e5245c7b.png">

### Browser
Browser: Chrome
Version: 112.0.5615.137

It is the same even if I turn off all AdBloc plug-ins and run it, and there is no error in the console.

### Machine
Operating system: MacOS Ventura
Version: 13.1

**Comment by domesticmouse** [comment]
Actually, my gaffe, this isn't Flutter related. Re-opening in DartPad's issue tracker.
