### ISSUE TITLE
[camera] flash triggers when changing flash mode (Android)

### ISSUE THREAD

**Issue by felixriehm** [flutter/flutter#125550]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Install and execute the camera plugin example project (-> https://github.com/flutter/packages/tree/main/packages/camera/camera/example/camera/camera/example) on an android smartphone
2. Select back camera
3. Select flash mode "FlashMode.always" (**flash does not trigger**, ok)
4. Take a picture (flash triggers, ok)
5. Change flash mode to  "FlashMode.auto" (**flash triggers**, not ok)

=> Flash tiggers everytime when you change the flash mode to "FlashMode.always" or "FlashMode.auto"

### Expected results

When changing the flash mode to "FlashMode.always" or "FlashMode.auto" the flash should not trigger.

### Actual results

Flash tiggers everytime when you change the flash mode to "FlashMode.always" or "FlashMode.auto"

### Code sample

Just install and execute the camera plugin example project -> https://github.com/flutter/packages/tree/main/packages/camera/camera/example

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.7.7, on macOS 13.2.1 22D68 darwin-arm64, locale en-DE)
    • Flutter version 3.7.7 on channel stable at /Users/felix/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (7 weeks ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/felix/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Users/felix/Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/felix/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 72.1.3
    • Dart plugin version 222.4560

[✓] VS Code (version 1.77.3)
    • VS Code at /Users/felix/Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • SM A047F (mobile) • R58TB15K7TF • android-arm64  • Android 13 (API 33)
    • macOS (desktop)   • macos       • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!


```

</details>

**Comment by danagbemava-nc** [comment]
Hi @felixriehm, what device are you experiencing this issue on? 
I tested the example code and I do not see the behavior you're reporting. See the recording below

What version of `camera` & `camera_android` do you have in your project? You can find the `camera_android` version in 
your pubspec.lock. 

<details>
<summary>recording</summary>

https://user-images.githubusercontent.com/88313112/234572458-7a184577-d359-4113-95d6-402e3b62e293.mp4
</details>

**Comment by felixriehm** [comment]
Hey @danagbemava-nc thanks for the reply. I have attached a recording of the issue.

Smartphone: Galaxy A04s
Model name: SM-A047F/DSN
One UI Core Version 5.1
Android Verion: 13

camera: camera: 0.10.4
camera_android: 0.10.5


https://user-images.githubusercontent.com/13718034/234633720-d98e30a3-17a5-4776-a20b-dd4bc56cbbaa.mp4

**Comment by danagbemava-nc** [comment]
Hi @felixriehm, is this issue only reproducing on the galaxy a04s?

I attempted to reproduce this on another device (a Poco X3 NFC), but I ran into https://github.com/flutter/flutter/issues/97501 so I couldn't verify this on that device.

**Comment by felixriehm** [comment]
@danagbemava-nc unfortunately i only have the galaxy a04s

**Comment by danagbemava-nc** [comment]
Thanks for the info. 

Labeling for further investigation as I cannot reproduce this locally. I tested on a Pixel 7, Poco X3 NFC & a Nokia 6. 

The Nokia 6 and Pixel 7 both behave the same, i.e, the flash isn't triggered when toggling the flash mode and when I tested on the Poco X3 NFC, I run into another issue as reported in https://github.com/flutter/flutter/issues/125550#issuecomment-1524959130.

This could be affecting just a specific set of devices, currently galaxy a04s.

**Comment by felixriehm** [comment]
for all coming to this via google:

i have used this now https://pub.dev/packages/camerawesome

supports image stream via "image analysis"

**Comment by camsim99** [comment]
This issue should be fixed in the [CameraX implementation](https://pub.dev/packages/camera_android_camerax) of the camera plugin, so please try it out!

If you find a similar issue with that implementation (or any other issues), please feel free to file a separate issue.

**Comment by felixriehm** [comment]
I have tested it with my Galaxy A04s. Works now! Thanks @camsim99!
