### ISSUE TITLE
Mixing platform in subbuilds are causing to use the wrong base drone builder

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#125574]
Here is an example of a mac sub-build using a base Linux Drone: https://luci-milo.appspot.com/p/flutter/builders/try.shadow/Linux%20Engine%20Drone/75

**Comment by godofredoc** [comment]
\cc @jmagman

**Comment by godofredoc** [comment]
\cc @keyonghan this is also impacting caches.

**Comment by jmagman** [comment]
I'm not sure where that drone build is coming from, is it there the main/orchestrator builder is on a different OS than the subbuilds?  For example the `mac_unopt` main build doesn't need to run on a Mac, so it was moved to Linux to free up capacity https://ci.chromium.org/p/flutter/builders/prod/Linux%20mac_unopt/156 https://github.com/flutter/engine/pull/41184

**Comment by godofredoc** [comment]
The problem is here https://cs.opensource.google/flutter/recipes/+/main:recipe_modules/shard_util_v2/api.py;l=217, the orchestrator platform is being used to select the subbuild drone.

**Comment by jmagman** [comment]
@godofredoc does that mean the orchestrator always needs to run the same OS as the subbuilds?  I spent a good amount of time last week trying to move the orchestrator builds off Mac to free up capacity.  
https://github.com/flutter/engine/pull/41181
https://github.com/flutter/engine/pull/41181

And I know web has Linux orchestrator builds that kick off on several platforms.

**Comment by jmagman** [comment]
@godofredoc can we specify the named caches needed in the sub builds? Or is the only option to revert the changes back to using Mac for the orchestrators?

**Comment by godofredoc** [comment]
Work around: https://flutter-review.googlesource.com/c/recipes/+/43324

**Comment by godofredoc** [comment]
Reland: https://flutter-review.googlesource.com/c/recipes/+/44444
