### ISSUE TITLE
engine deps scanning is broken

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#125573]
The workflow to scan the engine source code dependencies is currently broken. https://github.com/flutter/engine/actions/workflows/third_party_scan.yml

**Comment by godofredoc** [comment]
\cc @sealesj

**Comment by sealesj** [comment]
The source code scanning is continuing regularly within the `Scorecards supply-chain security` action https://github.com/flutter/engine/actions/runs/4812132516/jobs/8566980774, but looking at the output of the runs, it looks like scanning isn't happening as expected there

**Comment by godofredoc** [comment]
Should we fix third_party_scan.yml and remove from scorecards?

**Comment by sealesj** [comment]
Fixed with https://github.com/flutter/engine/pull/41528
