### ISSUE TITLE
Engine v2 subbuilds are not running tests

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#125500]
Example main build:
https://ci.chromium.org/p/flutter/builders/prod/Linux%20mac_unopt/134

Should be running a `Tests for ios_debug_sim_arm64` and `Scenario App Integration Tests` steps in the `ios_debug_sim_arm64` subbuild:
https://github.com/flutter/engine/blob/36730dd4e4b195cde399d500600c3536b1a07b83/ci/builders/mac_unopt.json#L206
https://github.com/flutter/engine/blob/36730dd4e4b195cde399d500600c3536b1a07b83/ci/builders/mac_unopt.json#L219

However, the test steps are missing:
https://ci.chromium.org/p/flutter/builders/prod/Linux%20Production%20Engine%20Drone/131491

Another example is `Host Tests for host_debug_unopt`:
https://github.com/flutter/engine/blob/36730dd4e4b195cde399d500600c3536b1a07b83/ci/builders/mac_unopt.json#L41

which isn't running a step in the `host_debug_unopt` subbuild:
https://ci.chromium.org/p/flutter/builders/prod/Linux%20Production%20Engine%20Drone/131488

@godofredoc @zanderso

**Comment by godofredoc** [comment]
This is a regression caused by removing type=local from the test configurations.

**Comment by godofredoc** [comment]
Fix: https://flutter-review.googlesource.com/c/recipes/+/42600

**Comment by godofredoc** [comment]
This is the PR the created the regression: https://github.com/flutter/engine/pull/41465
