### ISSUE TITLE
Widget factories should really be properties

### ISSUE THREAD

**Issue by MichaelPriebe** [flutter/flutter#125508]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Something I am frustrated by is that some widgets use factories instead of properties to make the widget look different, for example `FilledButton` has the factories `tonal`, `icon`, and `tonalIcon`.

Now think of if you needed to use these different factories based on some conditions, the only way would be to make a giant if statement, what you will also notice is that you have to repeat a ton of properties that are shared among the buttons.

```dart
if (important) {
  if (icon != null) {
    return FilledButton.icon(
      icon: icon!,
      label: const Text('Repeated Property'),
      onPressed: () => print('Repeated Property!'),
    );
  } else {
    return FilledButton(
      child: const Text('Repeated Property'),
      onPressed: () => print('Repeated Property!'),
    );
  }
} else {
  if (icon != null) {
    return FilledButton.tonalIcon(
      icon: icon!,
      label: const Text('Repeated Property'),
      onPressed: () => print('Repeated Property!'),
    );
  } else {
    return FilledButton.tonal(
      child: const Text('Repeated Property'),
      onPressed: () => print('Repeated Property!'),
    );
  }
}
```

### Proposal

Factories for widgets should rarely be used, their purpose can be achieved by properties in a single constructor.

```dart
return FilledButton(
  tonal: important, // bool
  icon: icon, // Widget?
  child: const Text('Much better!'),
  onPressed: () => print('Much better!'),
);
```

**Comment by darshankawar** [comment]
@MichaelPriebe Thanks for the report. Can you check [this](https://github.com/flutter/flutter/issues/119401) issue and see if it resembles your use case ?

**Comment by callmephil** [comment]
Factories are designed to improve performance as well as reduce build complexity.  

I would not recommend your approach especially if you often re-render your view, It would be like using a Container for padding instead of padding directly.

If you have the need to dynamically change the style of your button, Flutter allows you to create your own in many ways!
