### ISSUE TITLE
Error in codelabs: dart3/step_01/lib/main.dart - wrong placement for super.initState()

### ISSUE THREAD

**Issue by RandalSchwartz** [flutter/flutter#125527]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Line 38 has super.initState() in the wrong position in an override of initState.  It should be first, not last.

### Expected results

documentation is correct

### Actual results

documentation is wrong

### Code sample

n/a

### Flutter Doctor output

n/a

**Comment by danagbemava-nc** [comment]
Hi @RandalSchwartz, thanks for filing this. Can you provide a link to the codelab in question? 

Thanks

**Comment by RandalSchwartz** [comment]
The link is in the issue title. :)

**Comment by danagbemava-nc** [comment]
https://github.com/flutter/codelabs/blob/f34ebd822620e677914a2e38625c269ef3cd4a4b/dart3/step_01/lib/main.dart#L38

/cc @domesticmouse
