### ISSUE TITLE
CircleAvatar in ListView not rendering image until scrolled

### ISSUE THREAD

**Issue by miquelbeltran** [flutter/flutter#12553]
## Steps to Reproduce

I have a created a sample project in which I load a list of users from GitHub and display them on a ListView. Code here: https://github.com/miquelbeltran/flutter_github_users

I am using CircleAvatar to display the users' avatars: https://github.com/miquelbeltran/flutter_github_users/blob/master/lib/userlist/user_item.dart#L12

```
    var circleAvatar = new CircleAvatar(
      backgroundImage: new NetworkImage(_user.avatarUrl),
    );
```

Previously I used the Image widget in the same way and did not have any problem, but since I switched to CircleAvatar I have the following problem: 

- The CircleAvatar will not display the users' picture until I have scrolled a bit. 

The expected behavior:

- The avatars are displayed as soon as the Widget is created and the image is loaded.

The issue happens both on "slow mode" and a normal release apk.

The issue happens on Android, have not tested on iOS.

If you want to run and reproduce the issue, just run the project with `flutter run` and **pull to refresh** to load the initial list of users.

See with the screenshots:

![screenshot_20171015-132002](https://user-images.githubusercontent.com/2494376/31584363-35086aec-b1ad-11e7-8879-f5a3613fec8a.png)

![screenshot_20171015-132006](https://user-images.githubusercontent.com/2494376/31584365-4174be02-b1ad-11e7-8639-1f1bb8de3258.png)

![screenshot_20171015-132010](https://user-images.githubusercontent.com/2494376/31584367-45b5ec16-b1ad-11e7-9231-8540c6231b73.png)

## Logs

`flutter run` doesn't show anything.

Run `flutter analyze` and attach any output of that command also.

```
Analyzing /home/miquel/dev/flutter_github_users...
  error • The constructor returns type 'dynamic' that isn't of expected type 'Widget' at test/widget_test.dart:15:29 • strong_mode_invalid_cast_new_expr
  error • Undefined class 'MyApp' at test/widget_test.dart:15:33 • undefined_class
  hint • Unused import at test/widget_test.dart:10:8 • unused_import
3 issues found.
(Ran in 7.0s)
```

They seem to be related to the unit tests and unrelated to this case.

## Flutter Doctor

Paste the output of running `flutter doctor` here.

```
[✓] Flutter (on Linux, locale en_US.UTF-8, channel alpha)
    • Flutter at /home/miquel/dev/flutter
    • Framework revision 4424892c79 (5 days ago), 2017-10-10 16:45:11 -0700
    • Engine revision 2a84f18c79
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /home/miquel/Android/Sdk
    • Platform android-26, build-tools 26.0.1
    • Java binary at: /home/miquel/dev/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /home/miquel/dev/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 18.1
    • Dart plugin version 172.4155.35

[✓] Connected devices
    • ONE E1003 • 42bd2643 • android-arm • Android 6.0.1 (API 23)
```

**Comment by Hixie** [comment]
Strange...

**Comment by Hixie** [comment]
If you instrument the network image loading code, do you get any indications of what's going on?

**Comment by miquelbeltran** [comment]
Hi @Hixie I set a breakpoint inside the _loadAsync from NetworkImage in image_provider.dart and I could not find any issues, both the response and the decoded image object seem to be OK.

But what I could find is that the method paintImage from images.dart doesn't get called until I scroll.

On _paintBackgroundImage, line 372 the `image` is null, so the paintImage function doesn't get called.

I think that somehow a listener that triggers the repaint is not called after the image is downloaded, but I am not proficient enough with Flutter to debug further. I hope this info helps you.

**Comment by Hixie** [comment]
Thanks, that's helpful.

**Comment by Hixie** [comment]
Thanks for the GitHub repo with the repro test case, it was invaluable in reproducing this bug and tracking it down.

Fix in https://github.com/flutter/flutter/pull/13927/files#diff-f41d041ddd3fe665cc9e123f992bb5e0R1569.
