### ISSUE TITLE
Windows build support self-contained build (single exe file)

### ISSUE THREAD

**Issue by insinfo** [flutter/flutter#125575]
### Use case

let we can easy to redeploy our programm, copy then run.

### Proposal

flutter build for windows can build output a single exe file.
build all dll, into one big single exe file, 

I believe that for this it would be enough for the flutter SDK to be distributed with static libraries to be compiled with the final executable.

**Comment by stuartmorgan** [comment]
Duplicate of https://github.com/flutter/flutter/issues/75200
