### ISSUE TITLE
improve error message when cocopods is not available

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#12557]
When I try and `flutter run` an app on an ios device that uses plugins, I see:

```
Launching lib/main.dart on iPhone 7 in debug mode...
Warning: CocoaPods version 1.0.0 or greater not installed. Skipping pod install.
  CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
  Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
  For more info, see https://flutter.io/platform-plugins
To install:
  brew install cocoapods
  pod setup

CocoaPods not available for project using Flutter plugins
Error launching application on iPhone 7.
```

Some feedback:
- the first error is good (from the `Warning:` to right after `To install:`) but could be a bit more terse
- the 2nd error isn't very clear (`CocoaPods not available...`), and doesn't use sentence structure (which it should, to match the other errors). We may want to drop this error text as we've already told the user why the launch didn't work.

**Comment by Hixie** [comment]
This should be easy to fix:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/ios/cocoapods.dart

**Comment by Jesse-Bakker** [comment]
I think this can be closed
