### ISSUE TITLE
[CP] Spell Check Fixes

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#125524]
### issue_link

https://github.com/flutter/flutter/issues/124882

### Commit Hash

85ec874

### Target

beta

### pr_link

https://github.com/flutter/flutter/pull/125517

### Impacted Users

Anyone that has enabled spell check by passing a SpellCheckConfiguration to TextField or CupertinoTextField

### Impact Description

This cherry pick is a combination of many small bug fixes for the spell check feature.  Most changes were visual tweaks, but there was also one API change (the `BuildContext` parameter of `buildButtonItems` was removed).  The changes only affect users that actively enable the new spell check feature by passing the `spellCheckConfiguration` parameter to TextField or CupertinoTextField, which should be relatively few users.

### Workaround

The only workaround is to disable spell check by not passing in the spellCheckConfiguration parameter to TextField or CupertinoTextField.

### Risk

medium

### Test Coverage

yes

### Validation Steps

  1. Try this on iOS and Android with both a TextField and CupertinoTextField for each.
  2. Run an app with both a TextField and a CupertinoTextField with spell check enabled, such as the example app below.
  3. Type some gibberish into each field, and observe that misspelled words get a red underline.
  4. Tap on some of the misspelled words in each field.

Expected: You should see the appropriate spell check UI for the current device.  A maximum of three suggestions should be displayed at a time.  Tapping on a suggestion should replace the word and put the cursor at the end of the word.

<details>

<summary>Example app</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        //brightness: Brightness.dark,
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: const Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextField(
              spellCheckConfiguration: SpellCheckConfiguration(
              ),
            ),
            CupertinoTextField(
              spellCheckConfiguration: SpellCheckConfiguration(
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

<video width="150" src="https://user-images.githubusercontent.com/389558/234087667-651b0fde-348c-467e-ba00-27b6b3966a27.mov" />

**Comment by CaseyHillers** [comment]
@HansMuller can you review this CP request? If it looks good to you, can you add the "cp: approved" label
