### ISSUE TITLE
[windows 10] Flutter doctor fails to get dart-sdk

### ISSUE THREAD

**Issue by RaniSharim** [flutter/flutter#12555]
I cloned the reapo, added flutter/bin to the path as instructed.
After running 'flutter doctor' i get the following output

```
Checking Dart SDK version...
Downloading Dart SDK 1.25.0-dev.11.0...
Unzipping Dart SDK...
Exception calling "ExtractToFile" with "3" argument(s): "The process cannot access the file 'D:\installations\flutter\bin\cache\dart-sdk\bin\dart.exe' because it is being used by another process."
At C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:1033 char:25
```

The error is really weird, since nothing else should be using the file. I tried to reboot, same error.

After that , \flutter\bin\cache\dart-sdk is empty, and running 'flutter docter' fails on 'pub update'

**Comment by RaniSharim** [comment]
I was able to circumvent the error by installing 7-zip and adding it to the path

**Comment by goderbauer** [comment]
@RaniSharim It looks like your PowerShell version is too old and doesn't have the build-in unzip command. Updating your PowerShell would probably fix the problem (installing 7zip works as well because we also try that as a fall back).

**Comment by RaniSharim** [comment]
Your install code has the following line:
} ElseIf (Get-Command Expand-Archive -errorAction SilentlyContinue) {
    **# Use PowerShell's built-in unzipper, if available (requires PowerShell 5+).**
    Expand-Archive $dartSdkZip -DestinationPath $cachePath

I have powershell 5 installed:

PS C:\Users\aharon> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      15063  502

**Comment by goderbauer** [comment]
You're right. Not sure what caused this. I am closing this since the issue was resolved by installing 7zip. Please re-open if you continue to have problems
