### ISSUE TITLE
Would it be possible to capture a photo with depth?

### ISSUE THREAD

**Issue by csarigumba** [flutter/flutter#125556]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I'd like to capture an image with depth mode, which provides depth data similar to the portrait mode in cameras (not related to orientation). Can this be achieved using Flutter? I'm seeking confirmation and further details on how to implement this behavior. Thank you!

Related to https://github.com/flutter/flutter/issues/125486

### Proposal

images

**Comment by danagbemava-nc** [comment]
Hi @csarigumba, I don't believe this is possible at the moment but there is a feature request for something similar to what you previously requested in https://github.com/flutter/flutter/issues/113670. 

Kindly subscribe to that issue for updates. 

Closing from here as duplicate.

Thank you
