### ISSUE TITLE
[v2 + codesign] Linux mac_android_aot_engine no longer supports a pinned xcode version

### ISSUE THREAD

**Issue by XilaiZhang** [flutter/flutter#125570]
during mac code signing, we are using `notarytool` which only works with xcode 13+.
the pinned version of xcode 14 was removed from `Linux mac_android_aot_engine` in https://github.com/flutter/engine/pull/41181/files.
This would cause Linux mac_android_aot_engine to fail on post submit by [pulling in xcode12](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20mac_android_aot_engine/197/overview).

**Comment by jmagman** [comment]
I didn't know there was anything in the `mac_android_aot_engine` subbuilds that needs Xcode.  Feel free to add the necessary property:
https://github.com/flutter/engine/blob/e965485fb41878034788c1c55b985ad9df8bb016/ci/builders/mac_unopt.json#L33-L37
Here:
https://github.com/flutter/engine/blob/main/ci/builders/mac_android_aot_engine.json

**Comment by XilaiZhang** [comment]
Verified that linux mac android aot is now passing in this week's release. Will close the issue now. https://flutter-dashboard.appspot.com/#/build?taskFilter&authorFilter&messageFilter&hashFilter&showMac=true&showWindows=true&showiOS=true&showLinux=true&showAndroid=true&showStaging=false&repo=engine&branch=flutter-3.10-candidate.1
