### ISSUE TITLE
Alert dialogs no longer has a transparent overlay

### ISSUE THREAD

**Issue by vlidholt** [flutter/flutter#12562]
## Steps to Reproduce

Alert dialogs used to show the background with a transparent overlay, it now just shows a gray background. See the attached images for an example. The case is the same in the Flutter Gallery.

Old Flutter
![img_2130](https://user-images.githubusercontent.com/1539812/31619534-ca0eee44-b262-11e7-88fc-a6c248b613b5.png)

New Flutter
![img_2131](https://user-images.githubusercontent.com/1539812/31619519-bd65b704-b262-11e7-806d-fa432bcd8344.png)

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.13 17A405, locale en-US, channel alpha)
    • Flutter at /Users/vik/Projects/flutter
    • Framework revision 4424892c79 (6 days ago), 2017-10-10 16:45:11 -0700
    • Engine revision 2a84f18c79
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/vik/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.0, Build version 9A235
    • ios-deploy 1.9.2
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2.5)
    • Flutter plugin version 18.1
    • Dart plugin version 172.4155.35

[✓] Connected devices
    • iPhone X • 1241C7FA-2C9D-41F3-8C82-93D5312F8E94 • ios • iOS 11.0 (simulator)
```

**Comment by sethladd** [comment]
Thanks for the report!

**Comment by Hixie** [comment]
Do we have a regression window for this? This seems really bad!

**Comment by HansMuller** [comment]
I'm looking at this, will try and narrow down the regression timing

**Comment by vlidholt** [comment]
Thanks for looking into this!

**Comment by HansMuller** [comment]
We've been unable to reproduce the problem you're seeing. Modal dialog backgrounds render correctly (we ran the gallery example) on Android and iOS hardware and the software emulators. We did try the iPhone X emulator running on the same engine build and the same version of the framework as you reported. Seems to be OK. The only difference between our test setup and yours is that we're running Mac OS 10.12.16 and you're running 10.13.

Are you seeing this problem on any devices?

![image](https://user-images.githubusercontent.com/1377460/31633091-14f3ebe2-b274-11e7-9ef2-ca1060358591.png)

**Comment by vlidholt** [comment]
I'm seeing the same issue on both the iOS Simulator and on Devices. Running the latest Flutter from alpha branch, have done a `flutter upgrade`. Seeing the issue both in my own app and in the Flutter Gallery.

![flutterissue](https://user-images.githubusercontent.com/1539812/31634550-f349ef14-b291-11e7-9fc0-56a50625a93c.gif)

**Comment by vlidholt** [comment]
Sorry guys, just realized why this happened. I had to hack Flutter to do my bidding with getting the colors right with the color opacity issue. Really sorry to bother you. :/
