### ISSUE TITLE
[Impeller] Glyphs from Apple Color Emoji on iOS look less saturated.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#125668]
Repro:

Run the program at https://github.com/indjec/ui-label

The emoji in the UIKit label seem to have more saturated colors than the emoji from Flutter. Perhaps a wide gamut issue? @gaaclarke might know?

**Comment by jonahwilliams** [comment]
wide gamut is off right now so its not that.

**Comment by dnfield** [comment]
I mean they might need wide gamut to render with the right colors

**Comment by chinmaygarde** [comment]
Is this compared to UIKit or Skia?

**Comment by chinmaygarde** [comment]
I did a side by side comparison with Skia and they looked the same to me. Assuming this is outdated.
