### ISSUE TITLE
[CP] Update dartdoc to 6.2.2.

### ISSUE THREAD

**Issue by jcollins-g** [flutter/flutter#125662]
### issue_link

https://github.com/dart-lang/dartdoc/issues/3392

### Commit Hash

fb36bba

### Target

beta

### pr_link

https://github.com/flutter/flutter/pull/125661

### Impacted Users

Flutter developers viewing API documentation

### Impact Description

Users may miss that class modifiers apply to a part of a Dart API without this change, as the old way of displaying them in the breadcrumb is easy to miss. As class modifiers are a core feature of Dart 3.0 it makes sense to have them show up prominently in documentation. @mit-mit requested that we make an effort to get this in for the initial release.

Changing versions to 6.2.2 also brings in one other bugfix that (to my knowledge) does not impact Flutter.  See the release notes and linked PR/issue for more information:  https://github.com/dart-lang/dartdoc/releases/tag/v6.2.2

### Workaround

The user could look up and see the breadcrumbs in the top line instead of relying on this new UI element.

### Risk

low

### Test Coverage

yes

### Validation Steps

Check the page for any class that has a class modifier, including `abstract` as it is now handled the same way.   If the fix is correctly applied, the class will show a chip as you can see on https://master-api.flutter.dev/flutter/animation/Animatable-class.html.

![Screenshot 2023-04-27 at 6 02 24 PM](https://user-images.githubusercontent.com/14116827/235029817-b632bf04-2f8a-48a5-8318-57cfd2878dd1.png)

If it is not correctly applied, the word `abstract` will be on the top breadcrumb line and missing next to the header line in the main section.

**Comment by itsjustkevin** [comment]
@Piinks could you validate this cherry-pick?

**Comment by Piinks** [comment]
LGTM
