### ISSUE TITLE
[all plugins] Conditionalize `namespace` in build.gradle due to `No signature of method: build_[...].android() is applicable for argument types`  error with AGP <4.2

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#125621]
We recently added `namespace` to all of our plugins' build.gradle files to make them compatible with AGP 8.0 (see #125181). I thought I had tested that this would be ignored with older versions of AGP, but it turns out that I only tested with AGP 4.2, and [that's actually the first version where `namespace` works](https://github.com/flutter/flutter/issues/125181#issuecomment-1525894244). Developers with AGP 4.1 (which `flutter create` used in the Flutter 2.x timeframe) and earlier are reporting being broken (#125607, #125605).

This tracks reverting the addition of `namespace` while we figure out how to move forward without breaking 4.1 and earlier.

**Comment by stuartmorgan** [comment]
I hope to have new versions of all plugins without `namespace` published later today. In the meantime, the workaround is to either:
- Pin older versions of the affected plugin in your pubspec.yaml
- Update to a newer version of AGP and Gradle

(Updating AGP may require other changes in your project as well, but over time using old versions of AGP is going to increasingly cause compatibility issues in general for projects, such as not being able to use current versions of some library dependencies, and not being able to use current versions of Android Studio, so is something anyone still using AGP 4.x should be seriously investigating regardless of this specific issue.)

**Comment by lucas404x** [comment]
For me, at least all the libraries work well after updating Android Studio, the build.gradle and the distributionUrl from android/gradle/wrapper/gradle-wrapper.properties.

**Comment by stuartmorgan** [comment]
https://github.com/flutter/flutter/issues/125181#issuecomment-1525624250 has [a possible workaround](https://github.com/fluttercommunity/plus_plugins/compare/main...fix-agp-prior-7) that doesn't require a full revert, which I'll evaluate before proceeding here.

**Comment by stuartmorgan** [comment]
For anyone affected by this, we've determined that the problem is specific to versions older than 4.2, so for the many people on 4.1 an incremental workaround for the issue while we get the plugins updated, which may be easier than updating all the way to a recent version of AGP, is to update to [AGP 4.2](https://developer.android.com/build/releases/past-releases/agp-4-2-0-release-notes) and Gradle 6.7.1 (old projects that haven't been updated likely have Gradle 6.7 rather than the required 6.7.1).

**Comment by stuartmorgan** [comment]
> [#125181 (comment)](https://github.com/flutter/flutter/issues/125181#issuecomment-1525624250) has [a possible workaround](https://github.com/fluttercommunity/plus_plugins/compare/main...fix-agp-prior-7) that doesn't require a full revert, which I'll evaluate before proceeding here.

This didn't work with AGP 4.1 in my testing, but @reidbaker came up with a version that we've tested in AGP 4.1 and AGP 8.0 (and AGP 4.2 and AGP 7.3 just for good measure) and works in all cases. It's not a workaround, but directly checks the availability of the relevant property:

```
    if (project.android.hasProperty("namespace")) {
        namespace 'your.namespace.here'
    }
```

We'll be updating all of our plugins to use that.
