### ISSUE TITLE
Autosubmit not landing some PRs

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#125685]
@TahaTesser mentioned in https://github.com/flutter/flutter/pull/125483#issuecomment-1527122269

> Looks like even tho the tree is green, autosubmit doesn't merge the PR. Similar to this https://github.com/flutter/flutter/pull/125599#issuecomment-1525387603

When I came across this, the comment was 6 hours old, all checks and the tree were green and the bot had still not merged with the autosubmit label, so I merged it manually.

The other referenced PR looks like it was eventually merged by the bot, but there may be something not working quite right here.

**Comment by keyonghan** [comment]
Wondering if the initial `autosubmit` label was somehow not picked up by backend, e.g. when the new deployment happens. 
/cc @ricardoamador

**Comment by ricardoamador** [comment]
No there is something in the new code that if failing when it calls to github. I just have not found where it is failing. Still looking through the code. This only happens currently with configurable version.

**Comment by ricardoamador** [comment]
Ah okay I found the issue. Github UI throws a 404 if the user is not a member of the team (or a team in general) you are attempting to get membership status on. Fix is on the way for configurable autosubmit.
