### ISSUE TITLE
The clickable area of a button placed on BottomAppBar is too narrow if material3 is enabled and the screen has unsafe are at the bottom

### ISSUE THREAD

**Issue by fujidaiti** [flutter/flutter#125667]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

*Please see the snapshots below at first!*

I fond this phenomenon when I copied and pasted [an example code](https://api.flutter.dev/flutter/material/BottomAppBar-class.html#material.BottomAppBar.3) posted on the document of BottomAppBar class and ran it on a simulator of iPhone 14 Pro, which has unsafe area at the bottom of the screen. I've included a minimal code to reproduce this issue below instead of the example code for simplicity.
I also found that disabling material3 in ThemeData solves this problem, so it seems to be material3 specific.
```dart
MaterialApp(
    theme: ThemeData(useMaterial3: false),
    ...
```

### Expected results

BottomAppBar should provide enough space for its children to layout.

### Actual results

It seems that the layout area of BottomAppBar's child is too narrow (see the snapshots below, the available layout are is indicated by a red box).

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(useMaterial3: true),
      home: Scaffold(
        body: const Placeholder(),
        bottomNavigationBar: BottomAppBar(
          child: ColoredBox(
            color: Colors.red,
            child: Row(
              children: [
                IconButton(
                  onPressed: () {},
                  icon: const Icon(Icons.menu),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

The outputs of the above code on iPhone 14 Pro simulator (`material3:true` on the left, false on the right):
<img width="320" alt="minimal-m3" src="https://user-images.githubusercontent.com/68946713/235048295-a4eeeb8e-5752-47d0-8f6d-39313a40b76c.gif"><img width="320" alt="minimal-m2" src="https://user-images.githubusercontent.com/68946713/235048315-5d7411be-191f-46d2-94d0-cdf33d15c624.gif">

The layout areas (`material3:true` on the left, false on the right):
<img width="300" alt="minimal-m2" src="https://user-images.githubusercontent.com/68946713/235048980-052da6f1-79cc-4548-86c4-4e21e4923ee2.png">
<img width="300" alt="minimal-m3" src="https://user-images.githubusercontent.com/68946713/235048989-e5836748-6146-4771-8767-2d6d9b3bf92f.png">

The output of the example code on iPhone 14 Pro simulator:
<img width="320" alt="example-m2" src="https://user-images.githubusercontent.com/68946713/235048268-2b13aa9b-0f3b-4a3e-9c9e-c190149e7ec9.gif">

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.10, on macOS 13.3.1 22E261 darwin-arm64,
    locale ja-JP)
    • Flutter version 3.7.10 on channel stable at
      /opt/homebrew/Caskroom/flutter/3.0.5/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b12645012 (3 weeks ago), 2023-04-03 17:46:48
      -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version
    33.0.0)
    • Android SDK at /Users/daichi/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google
      Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • 54FFCD7B-2299-4A1C-8775-A97FFAAA951D • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)        • macos                                •
      darwin-arm64   • macOS 13.3.1 22E261 darwin-arm64
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @fujidaiti, this was initially reported in https://github.com/flutter/flutter/issues/119526 and has since been fixed on the master channel. 

The fix should make it to the stable branch sometime in the future. 

I'll be closing this since it has already been fixed on the master channel. 

If you run into this issue on the master channel kindly leave a comment below and I will reopen this. 

Thank you
