### ISSUE TITLE
Set an explicit Gradle, AGP, and Android Studio policy enforced by flutter tooling 

### ISSUE THREAD

**Issue by reidbaker** [flutter/flutter#125653]
Android Studio flamingo created a number of fires for flutter engineering. 
Some covering gradle 8 support, AGP 8.0 support and Java 17 support. 

In many ways flutter does not control compatibility or interoperability between dependencies required to build android apps. Flutter should document the supported version and enforce those as part of flutter build/run in addition to exposing them in flutter doctor or similar command. 

This is not unlike what iOS does 

here's an example https://github.com/flutter/flutter/blob/215fa3557b7e846e473d01fdad84bad584586e1f/packages/flutter_tools/lib/src/macos/xcode_validator.dart#L43
that shows it in doctor
this is the code that's checked when we go to build the project, and bails early with an error if the version isn't high enough https://github.com/flutter/flutter/blob/215fa3557b7e846e473d01fdad84bad584586e1f/packages/flutter_tools/lib/src/ios/mac.dart#L630
used here https://github.com/flutter/flutter/blob/215fa3557b7e846e473d01fdad84bad584586e1f/packages/flutter_tools/lib/src/ios/mac.dart#L139-L141

**Comment by reidbaker** [comment]
Feedback to not include Android Studio because it is not actually required to build flutter android apps. Focus on the tools required to build.

**Comment by christopherfujino** [comment]
related, I just filed https://github.com/flutter/flutter/issues/127431

**Comment by reidbaker** [comment]
yes it is still a p3. It will get an assignee when it is closer to being worked on.

**Comment by reidbaker** [comment]
The fix for https://github.com/flutter/flutter/issues/138523 will likely require a minimum gradle version at 6.0 or higher.

**Comment by gmackall** [comment]
Doc describing suggested versions and implementation here
https://docs.google.com/document/d/1qeeM5QG-jiafttSgvc7yvC19IDRggFFZQTktBVxL6sI/edit?pli=1&resourcekey=0-HLEAiBOMxAlQxDs-mEeffw

**Comment by gmackall** [comment]
https://github.com/flutter/flutter/issues/140913

**Comment by gmackall** [comment]
Closing as the only remaining piece is https://github.com/flutter/flutter/issues/142653, which cannot be done until sufficient time has passed with the warnings in place
