### ISSUE TITLE
The engine notify twice for the same value when use numeric keyboard input Duplicate(https://github.com/flutter/flutter/issues/65811)

### ISSUE THREAD

**Issue by 1AlexFix1** [flutter/flutter#125638]
Hello, originally problem not fixed, but closed https://github.com/flutter/flutter/issues/65811

[✓] Flutter (Channel stable, 3.7.12, on macOS 13.1 22C65 darwin-arm64, locale ru-RU)
    • Flutter version 3.7.12 on channel stable at /Users/a.kotkov/Develop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (10 days ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/a.kotkov/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • 706C80D4-58D6-4210-8D81-04BDB180283E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

Problem Not Fixed

**Comment by 1AlexFix1** [comment]
https://github.com/flutter/flutter/issues/65811#issuecomment-1376703308
Hello, Problem not Fixed

**Comment by darshankawar** [comment]
@1AlexFix1 
Per most recent [comment](https://github.com/flutter/flutter/issues/65811#issuecomment-1376703308) from linked issue, it was verified on master version as fixed. Have you already verified on latest master to see if you still get same behavior or not ?

If the issue still persists on latest master too, is it only occuring with specific numeric keyboard or with default soft keyboard also ?

`flutter channel master`
`flutter upgrade`
