### ISSUE TITLE
Track/setup SLO/alert on Engine `bot_update` step execution time

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#125642]
The `bot_update` step execution time varies based on repo caches, network, GoB, etc. It is not uncommon the step execution time bumps randomly for different reaons.

This bug tracks creating charts to monitor the step, setting up appropriate SLO, and alerting sheriff/gardener when the number goes beyond SLO.

Related: https://github.com/flutter/flutter/issues/120121

**Comment by zanderso** [comment]
Here is an example that I would have expected to be flagged https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Unopt/29344/overview

**Comment by keyonghan** [comment]
With the second layer cache, this step has been consistently stable within minutes.
