### ISSUE TITLE
[camera] option to increase fps / activate slow motion mode

### ISSUE THREAD

**Issue by BernardoGui** [flutter/flutter#125683]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

When streaming the camera images, the frame rate seems to be capped at 30 fps on Android and iOS for front and rear cameras. At least the rear cameras are capable of higher frame rates.

A general use case is slow-motion capture. 
My use case is heart rate variability measurement via PPG of the fingertip. 30 hz is just too low, but my camera should be capable of 240 fps, which would suffice. slow-motion

### Proposal

Please add the option to increase the frame rate of the camera stream to values above 30 fps, if this is supported by the camera.

**Comment by darshankawar** [comment]
@BernardoGui 
There's a similar open proposal describing your case, https://github.com/flutter/flutter/issues/54339 so please follow-up in it for further updates. Closing this as a duplicate.
