### ISSUE TITLE
Didn't find class "android.window.OnBackInvokedCallback" and "android.graphics.ImageDecoder$OnHeaderDecodedListener"

### ISSUE THREAD

**Issue by DuJerry** [flutter/flutter#125601]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I packaged the app for release, 

I am sure that I can run normally in debug mode.

### Expected results

The app should run more efficiently and normally in debug mode

### Actual results

When I run it on the real machine, the following two errors occur, causing the program to be stuck at the white screen stage.

Rejecting re-init on previously-failed class java.lang.Class<io.flutter.embedding.android.d$a>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/window/OnBackInvokedCallback;

Rejecting re-init on previously-failed class java.lang.Class<io.flutter.embedding.engine.d>: java.lang.NoClassDefFoundError : Failed resolution of: Landroid/graphics/ImageDecoder$OnHeaderDecodedListener;

### Code sample

    android build.gradle

    compileSdkVersion flutter.compileSdkVersion
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName

         ndk {
            abiFilters "armeabi-v7a", "arm64-v8a"
        }
    }

pubspec.yaml

name: client
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+27

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  flutter_cache_manager: ^3.3.0
  better_player: #^0.0.83
    git:
      url: https://github.com/tintran-dev/betterplayer.git
  json_annotation: ^4.8.0
  mqtt5_client: ^3.3.7
  just_audio: ^0.9.32
  yuro_annotation: ^0.2.0
  yuro:
    path: ../../github/yuro_kit/yuro
  yuro_plugin:
    path: ../../github/yuro_kit/yuro_plugin
  plugins:
    path: packages/plugins
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.5.4
  isar_generator: ^3.1.0 
  yuro_generator: ^0.2.2

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/raw/

flutter_intl:
  enabled: true
  main_locale: 'zh'

### Screenshots or Video

![屏幕截图 2023-04-27 103617](https://user-images.githubusercontent.com/9245629/234746363-4628a9ca-4892-45db-a327-c4fe648f5a64.png)

This is the content of the classes.dex file in the apk viewed with Android Studio after packaging

![屏幕截图 2023-04-27 104157](https://user-images.githubusercontent.com/9245629/234746446-3d3dfb07-7b57-4008-a062-9d89c5b5d135.png)
![屏幕截图 2023-04-27 104208](https://user-images.githubusercontent.com/9245629/234746457-4d20c23d-bb2e-4f1e-a647-73a8201e4435.png)

### Logs

[log.log](https://github.com/flutter/flutter/files/11339014/log.log)

### Flutter Doctor output

[√] Flutter (Channel stable, 3.7.12, on Microsoft Windows [版本 10.0.22621.1635], locale zh-CN)
    • Flutter version 3.7.12 on channel stable at C:\Users\dugang\AppData\Local\Android\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (9 days ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\dugang\AppData\Local\Android\Sdk
    • Platform android-33-2, build-tools 33.0.2
    • ANDROID_HOME = C:\Users\dugang\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33424.131
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] VS Code (version 1.77.3)
    • VS Code at C:\Users\dugang\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.62.0

[√] Connected device (4 available)
    • D1s d (mobile)    • DB04206T40119 • android-arm    • Android 7.1.2 (API 25)
    • Windows (desktop) • windows       • windows-x64    • Microsoft Windows [版本 10.0.22621.1635]
    • Chrome (web)      • chrome        • web-javascript • unknown
    • Edge (web)        • edge          • web-javascript • Microsoft Edge 112.0.1722.58

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

**Comment by DuJerry** [comment]
Has anyone encountered the same problem?

**Comment by korvan** [comment]
I have the same issue. OnHeaderDecodedListener appeared in sdk 28, so app crashes if you try to run it on device with Android version < 9. I can't find call of this function in any of included plugins. And wonder if Flutter sdk uses it itself.

**Comment by darshankawar** [comment]
@DuJerry See if [this](https://github.com/flutter/flutter/issues/113597#issuecomment-1282241630) helps in your case.
If not, please try to narrow down the issue to the code without third party package implementation and see if using it, you still get same behavior or not.

**Comment by DuJerry** [comment]
I used vscode to create an initial project of a counter, and after using the `flutter build apk` command to package it, I found that the two errors mentioned above also appeared when I ran it.

**Comment by darshankawar** [comment]
Thanks for the update. Do you by any chance have `uncaught exceptions` enabled in vscode ?
Does the same error occur if you create a new project through command line / terminal outside of IDE ?
