### ISSUE TITLE
data not available 

### ISSUE THREAD

**Issue by vishallsinghrajput** [flutter/flutter#125674]
import 'package:flutter/material.dart';
import 'package:hive/hive.dart';
import 'package:path_provider/path_provider.dart';

class HomeBottonPage extends StatefulWidget {
  const HomeBottonPage({Key? key}) : super(key: key);

  @override
  State<HomeBottonPage> createState() => _HomeBottonPageState();
}

class _HomeBottonPageState extends State<HomeBottonPage> {
  var controller = TextEditingController();
  Box<dynamic>? box;

 // get storeDate => box;

  @override
  void initState() {
    initializeBox();
    super.initState();
  }

  void storeData() {
    setState(() {
      box?.put("email", controller.text);
    });
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      child: Center(
        child: Column(
          children: [
            TextFormField(
              controller: controller,
              decoration: InputDecoration(
                  labelText: "Email",
                  hintText: "Enter Email",
              ),
            ),
            ElevatedButton(
             onPressed: storeData, child:Text("Store Data in hive")),
            Text(box?.get("email")?? "Data Not Available"),
          ],
        ),
      ),
    );
  }

  Future<void> initializeBox()  async {
    var dir = getApplicationDocumentsDirectory();
    Hive.init(dir.asStream() as String?);
    box = await Hive.openBox("student");
  }
}

**Comment by danagbemava-nc** [comment]
Hive is a third-party package. Any issues you face from using it should be reported on their repo. 

Closing from here as this is not a flutter issue. 

Thank you
