### ISSUE TITLE
Attempted to send a key down event when no keys are in keysPressed.

### ISSUE THREAD

**Issue by alanmv01** [flutter/flutter#125672]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a flutter project
`flutter create key_press_error_demo`
2. cd into project and run in Chrome
```
cd key_press_error_demo
flutter run -d Chrome
```
3. Press the Windows key (sometimes called Meta or Super)

### Expected results

Nothing special should happen.

### Actual results

══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following assertion was thrown during a platform message callback:
Assertion failed:
file:///home/alan/Programs/flutter/packages/flutter/lib/src/services/raw_keyboard.dart:683:7
event is! RawKeyDownEvent || _keysPressed.isNotEmpty
"Attempted to send a key down event when no keys are in keysPressed. This state can occur if the key
event being sent doesn't properly set its modifier flags. This was the event:
RawKeyDownEvent#499d8(logicalKey: LogicalKeyboardKey#4b191(keyId: \"0x200000106\", keyLabel: \"Meta
Left\", debugName: \"Meta Left\"), physicalKey: PhysicalKeyboardKey#700e3(usbHidUsage:
\"0x000700e3\", debugName: \"Meta Left\"), repeat: false) and its data:
RawKeyEventDataWeb#5923c(code: MetaLeft, key: Meta, location: 1, metaState: 0, keyCode: 91)"

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3        assertFailed
packages/flutter/src/services/raw_keyboard.dart 683:49                            handleRawKeyEvent
packages/flutter/src/services/hardware_keyboard.dart 951:30                       handleRawKeyMessage
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                _async
packages/flutter/src/services/hardware_keyboard.dart 923:51                       handleRawKeyMessage
packages/flutter/src/services/platform_channel.dart 214:49                        <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                _async
packages/flutter/src/services/platform_channel.dart 213:58                        <fn>
packages/flutter/src/services/binding.dart 393:35                                 <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                _async
packages/flutter/src/services/binding.dart 390:98                                 <fn>
lib/_engine/engine/platform_dispatcher.dart 1199:13                               invoke2
lib/ui/channel_buffers.dart 25:12                                                 invoke
lib/ui/channel_buffers.dart 65:7                                                  push
lib/ui/channel_buffers.dart 131:16                                                push
lib/_engine/engine/platform_dispatcher.dart 378:25                                invokeOnPlatformMessage
lib/_engine/engine/raw_keyboard.dart 142:39                                       [_handleHtmlEvent]
lib/_engine/engine/raw_keyboard.dart 12:7                                         <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 367:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 372:39  dcall
════════════════════════════════════════════════════════════════════════════════════════════════════

### Code sample

<details><summary>Code sample</summary>

```dart
// The default code created by `flutter create` suffices to reproduce the error.
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.12, on Debian GNU/Linux 12 (bookworm) 6.1.0-7-amd64, locale en_IN)
    • Flutter version 3.7.12 on channel stable at /home/alan/Programs/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (10 days ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/alan/Programs/Android/Sdk/
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /home/alan/Programs/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • Debian clang version 14.0.6
    • cmake version 3.25.1
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[✓] Android Studio (version 2022.2)
    • Android Studio at /home/alan/Programs/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at /home/alan/Programs/idea
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Debian GNU/Linux 12 (bookworm) 6.1.0-7-amd64
    • Chrome (web)    • chrome • web-javascript • Chromium 112.0.5615.138 built on Debian 12.0, running on Debian 12.0

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by Skynse** [comment]
I get a somewhat similar error on my laptop. For me, it has to do with the Fn key being enabled. When I disable it in BIOS, the error disappears. But I can't live without the fn being swapped for the normal F keys.

**Comment by alanmv01** [comment]
This issue got closed: https://github.com/flutter/flutter/issues/124301

I have created this new issue just to share some additional info regarding my set up if at all it helps.

This happens both on my laptop and desktop. 
```
$ uname -a
Linux <hostname> 6.1.0-7-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.20-2 (2023-04-08) x86_64 GNU/Linux
```

```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/
```

I was running i3wm as window manager. But I think this can safely be ignored as the reason for the issue because, I was able to reproduce the error in XFCE and on sway window (running wayland).

I have also tested with google-chrome and the error occurs there too.

There is no such output in the web-server or linux "run" types.

**Comment by alanmv01** [comment]
> I get a somewhat similar error on my laptop. For me, it has to do with the Fn key being enabled. When I disable it in BIOS, the error disappears. But I can't live without the fn being swapped for the normal F keys.

Interesting. I will try this and post if I am able to reproduce this.

**Comment by huycozy** [comment]
Thanks for your report, @alanmv01. This issue is reproducible on the latest `stable` and `master` channels.

### Additional info

- From my end, I only can reproduce this by pressing on `Right Windows` key which is `Meta Right`  on the logs. When checking with `Left Windows` key, it will trigger Activities overview as default behavior on OS (Ubuntu distro).

- The issue is only happening on Web while it works well on Linux.

- Also, this is a known issue (https://github.com/flutter/flutter/issues/99297) but it seems its [PR](https://github.com/flutter/engine/pull/32061) is only fixing for `Meta Left`.

Labeling the issue for more insights. 

<details>
<summary>Logs</summary>

```console
A Dart VM Service on Chrome is available at: http://127.0.0.1:34251/xrMCMqV6rYk=
The Flutter DevTools debugger and profiler on Chrome is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:34251/xrMCMqV6rYk=
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following assertion was thrown during a platform message callback:
Assertion failed:
file:///home/huynq/Documents/Working/flutter_master/packages/flutter/lib/src/services/raw_keyboard.dart:6
95:7
event is! RawKeyDownEvent || _keysPressed.isNotEmpty
"Attempted to send a key down event when no keys are in keysPressed. This state can occur if the key
event being sent doesn't properly set its modifier flags. This was the event:
RawKeyDownEvent#6b492(logicalKey: LogicalKeyboardKey#8222a(keyId: \"0x200000107\", keyLabel: \"Meta
Right\", debugName: \"Meta Right\"), physicalKey: PhysicalKeyboardKey#700e7(usbHidUsage:
\"0x000700e7\", debugName: \"Meta Right\"), repeat: false) and its data:
RawKeyEventDataWeb#46cd7(code: MetaRight, key: Meta, location: 2, metaState: 0, keyCode: 92)"

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 288:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3        assertFailed
packages/flutter/src/services/raw_keyboard.dart 695:49                            handleRawKeyEvent
packages/flutter/src/services/hardware_keyboard.dart 953:30                       handleRawKeyMessage
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                _async
packages/flutter/src/services/hardware_keyboard.dart 925:51                       handleRawKeyMessage
packages/flutter/src/services/platform_channel.dart 212:49                        <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                _async
packages/flutter/src/services/platform_channel.dart 211:58                        <fn>
packages/flutter/src/services/binding.dart 479:35                                 <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                _async
packages/flutter/src/services/binding.dart 476:98                                 <fn>
lib/_engine/engine/platform_dispatcher.dart 1273:13                               invoke2
lib/ui/channel_buffers.dart 25:12                                                 invoke
lib/ui/channel_buffers.dart 65:7                                                  push
lib/ui/channel_buffers.dart 131:16                                                push
lib/_engine/engine/platform_dispatcher.dart 404:25                                invokeOnPlatformMessage
lib/_engine/engine/raw_keyboard.dart 142:39                                       [_handleHtmlEvent]
lib/_engine/engine/raw_keyboard.dart 12:7                                         <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 367:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 372:39  dcall
════════════════════════════════════════════════════════════════════════════════════════════════════
```
</details>

<details>
<summary>flutter doctor -v (stable & master)</summary>

```bash
[!] Flutter (Channel stable, 3.7.12, on Ubuntu 22.04.1 LTS 5.19.0-38-generic, locale en_US.UTF-8)
    • Flutter version 3.7.12 on channel stable at /home/huynq/Documents/Working/flutter
    ! Warning: `dart` on your path resolves to /usr/lib/dart/bin/dart, which is not inside your current Flutter SDK checkout at /home/huynq/Documents/Working/flutter. Consider adding /home/huynq/Documents/Working/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (6 days ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /home/huynq/Android/Sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /home/huynq/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/huynq/Documents/android-studio
    • Flutter plugin version 67.0.1
    • Dart plugin version 211.7817
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.71.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.1 LTS 5.19.0-38-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 112.0.5615.121

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```bash
[!] Flutter (Channel master, 3.10.0-15.0.pre.28, on Ubuntu 22.04.1 LTS 5.19.0-38-generic, locale en_US.UTF-8)
    • Flutter version 3.10.0-15.0.pre.28 on channel master at /home/huynq/Documents/Working/flutter_master
    ! Warning: `flutter` on your path resolves to /home/huynq/Documents/Working/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /home/huynq/Documents/Working/flutter_master. Consider adding /home/huynq/Documents/Working/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /usr/lib/dart/bin/dart, which is not inside your current Flutter SDK checkout at /home/huynq/Documents/Working/flutter_master. Consider adding /home/huynq/Documents/Working/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4dbeb3fb06 (7 minutes ago), 2023-04-27 11:19:34 -0400
    • Engine revision 381f714972
    • Dart version 3.1.0 (build 3.1.0-49.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /home/huynq/Android/Sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /home/huynq/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/huynq/Documents/android-studio
    • Flutter plugin version 67.0.1
    • Dart plugin version 211.7817
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.71.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.1 LTS 5.19.0-38-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 112.0.5615.121

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by NyxTrail** [comment]
@huycozy In my case, the error occurs for the left windows key. Unfortunately I cannot check the right Windows key since I use a small form factor keyboard that does not have the right Windows key.

Perhaps, in your case the error does not occur for the left windows key because Ubuntu is consuming it and the press event does not propagate to the application?

**Comment by alanmv01** [comment]
@huycozy In my case, the error occurs for the left windows key. Unfortunately I cannot check the right Windows key since I use a small form factor keyboard that does not have the right Windows key.

Perhaps, in your case the error does not occur for the left windows key because Ubuntu is consuming it and the press event does not propagate to the application?

**Comment by alanmv01** [comment]
Update: I did a quick and dirty test in XFCE by binding my left Windows key to the XFCE Application menu. With this, I was no longer receiving the error. May be this confirms that having a binding for a key (at least at the window manager level) consumes it and flutter does not see the key press?
