### ISSUE TITLE
Add sample code for SliverAppBar [stretch, onStretchTrigger]

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#125651]
Following up on a note form @HansMuller :)

> I'm working on a SliverAppBar feature and was just looking at https://api.flutter.dev/flutter/material/SliverAppBar/onStretchTrigger.html. I wasn't sure what it was for.  You wrote a beautiful example in https://github.com/flutter/flutter/pull/42250. Someday it might be nice to include it in the API docs.

**Comment by rexthecoder** [comment]
@Piinks Are you working on this issue? If not can you assign me to it 🌝

**Comment by Piinks** [comment]
You are welcome to, @rexthecoder! Although, it looks like @istiak-ahmed78 has opened a PR. You're welcome to give feedback on it. If you ever see an unassigned issue and would like to work on it, feel free to!

**Comment by rexthecoder** [comment]
> You are welcome to, @rexthecoder! Although, it looks like @istiak-ahmed78 has opened a PR. You're welcome to give feedback on it. If you ever see an unassigned issue and would like to work on it, feel free to!

Okay sure, I will check other issues. Thanks
