### ISSUE TITLE
[CP] AGP 8.0 support for integration tests

### ISSUE THREAD

**Issue by reidbaker** [flutter/flutter#125688]
### issue_link

https://github.com/flutter/flutter/issues/125181

### Commit Hash

3a6c4eb 

### Target

beta

### pr_link

https://github.com/flutter/flutter/pull/125686

### Impacted Users

Android devs using the recommended AGP version by stable Android Studio

### Impact Description

https://github.com/flutter/flutter/issues/125181#issuecomment-1525894244
AGP 8.0 requires a ecosystem wide change. All dependencies must set namespace in build.gradle. This change adds namespace as a required parameter in a backwards compatible way. 

Strong confidence existing tests will cover ensuring that AGP users less than 8.0 will continue to work. Cannot add a test for AGP 8 because it required java 17 to execute and there are no java 17 tests on stable branch. See https://github.com/flutter/flutter/issues/125325

### Workaround

Users can either not update AGP or not have integration tests. 

### Risk

medium

### Test Coverage

yes

### Validation Steps

Attempt to build any integration test that uses AGP 8.0.

**Comment by itsjustkevin** [comment]
@stuartmorgan and @camsim99 could you take a look at this cherry-pick?  Need some more experts to take a look.

**Comment by stuartmorgan** [comment]
LGTM. We shipped the same change in all of our 1P plugins this morning.
