### ISSUE TITLE
Error: 'AnimatedItemBuilder' is imported from both 'package: flutter/src/widgets/animated_scroll_view.dart' and 'package: implicitly_animated_reorde y_animated list.dart:4 rable_list/src/implicitly_animated_list_base.dart'

### ISSUE THREAD

**Issue by shatriakini** [flutter/flutter#125754]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

use sliverlist

### Expected results

no error

### Actual results

error imported from both 

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

![WhatsApp Image 2023-04-30 at 11 16 23](https://user-images.githubusercontent.com/90294236/235335697-9581d26c-9d19-41e3-92e7-68ded91c9cdc.jpeg)

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by stuartmorgan** [comment]
Issues with third-party packages, in this case `implicitly_animated_reorderable_list` need to be reported to the authors of the package. Closing as this is not an issue in Flutter.

In the future, please follow the instructions in the issue template when filling an issue, and provide your logs as text, not screenshots.
