### ISSUE TITLE
[camera] ANR on Android when calling `startVideoRecording`

### ISSUE THREAD

**Issue by saveKenny** [flutter/flutter#125761]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Run `await _cameraController.startVideoRecording()` using the camera package (10.0.4) on Android 13 physical device in debug mode.

### Expected results

The app starts video recording and continues the run

### Actual results

No errors are returned. The app crashes with these logs:

I/.tenant_app.dev(26963): Thread[4,tid=26969,WaitingInMainSignalCatcherLoop,Thread*=0xb400007db3c65b20,peer=0x144001f8,"Signal Catcher"]: reacting to signal 3
I/.tenant_app.dev(26963): 
I/.tenant_app.dev(26963): Wrote stack traces to tombstoned
F/crash_dump64(27421): crash_dump.cpp:485] failed to attach to thread 476: Permission denied
F/crash_dump64(27424): crash_dump.cpp:485] failed to attach to thread 507: Permission denied

### Code sample

<details><summary>Code sample</summary>
This code is from the camera_controller.dart of the camera package. As you can see, calling startVideoRecording will end with UnimplementedError.

```dart
/// Start a video recording.
  ///
  /// You may optionally pass an [onAvailable] callback to also have the
  /// video frames streamed to this callback.
  ///
  /// The video is returned as a [XFile] after calling [stopVideoRecording].
  /// Throws a [CameraException] if the capture fails.
  Future<void> startVideoRecording(
      {onLatestImageAvailable? onAvailable}) async {
    _throwIfNotInitialized('startVideoRecording');
    if (value.isRecordingVideo) {
      throw CameraException(
        'A video recording is already started.',
        'startVideoRecording was called when a recording is already started.',
      );
    }

    Function(CameraImageData image)? streamCallback;
    if (onAvailable != null) {
      streamCallback = (CameraImageData imageData) {
        onAvailable(CameraImage.fromPlatformInterface(imageData));
      };
    }

    try {
      await CameraPlatform.instance.startVideoCapturing(
          VideoCaptureOptions(_cameraId, streamCallback: streamCallback));
      value = value.copyWith(
          isRecordingVideo: true,
          isRecordingPaused: false,
          recordingOrientation: Optional<DeviceOrientation>.of(
              value.lockedCaptureOrientation ?? value.deviceOrientation),
          isStreamingImages: onAvailable != null);
    } on PlatformException catch (e) {
      throw CameraException(e.code, e.message);
    }
  }
  
  /// Starts a video recording.
  ///
  /// The length of the recording can be limited by specifying the [maxVideoDuration].
  /// By default no maximum duration is specified,
  /// meaning the recording will continue until manually stopped.
  /// With [maxVideoDuration] set the video is returned in a [VideoRecordedEvent]
  /// through the [onVideoRecordedEvent] stream when the set duration is reached.
  ///
  /// This method is deprecated in favour of [startVideoCapturing].
  Future<void> startVideoRecording(int cameraId, {Duration? maxVideoDuration}) {
    throw UnimplementedError('startVideoRecording() is not implemented.');
  }

  /// Starts a video recording and/or streaming session.
  ///
  /// Please see [VideoCaptureOptions] for documentation on the
  /// configuration options.
  Future<void> startVideoCapturing(VideoCaptureOptions options) {
    return startVideoRecording(options.cameraId,
        maxVideoDuration: options.maxDuration);
  }
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
I/.tenant_app.dev(26963): Thread[4,tid=26969,WaitingInMainSignalCatcherLoop,Thread*=0xb400007db3c65b20,peer=0x144001f8,"Signal Catcher"]: reacting to signal 3
I/.tenant_app.dev(26963): 
I/.tenant_app.dev(26963): Wrote stack traces to tombstoned
F/crash_dump64(27421): crash_dump.cpp:485] failed to attach to thread 476: Permission denied
F/crash_dump64(27424): crash_dump.cpp:485] failed to attach to thread 507: Permission denied
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.6, on macOS 13.2.1 22D68 darwin-x64, locale en-IL)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.76.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

</details>

**Comment by stuartmorgan** [comment]
The stub implementation from the platform interface base class, which is what you've shown there (and is not from camera_controller.dart), will never be used. That's why there's no `UnimplementedError` in your log.

This is the app being killed due to an ANR. Please provide:
- full code to reproduce the issue (not just a single line)
- the `camera_android` version from your pubspec.lock file
- the stack trace from the tombstone, referenced in the log.
