### ISSUE TITLE
[go_router_builder] go_router versions that are not yet to be supported can be installed

### ISSUE THREAD

**Issue by noriHanda** [flutter/flutter#125786]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Install go_router_builder (i.e. `flutter pub add -d go_router_builder`)
2. Install go_router (i.e. `flutter pub add go_router`)

### Expected results

go_router_builder should block installing go_router versions that does not support.

### Actual results

This installs go_router 7.0.0 now despite the fact that the latest go_router_builder 1.2.2 does not support it.

The reason why I know go_router_builder 1.2.2 does not support the lastest go_router is that running build_runner creates this error: `Error: The getter 'params' isn't defined for the class 'GoRouterState'.`

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.7.12, on macOS 13.3.1 22E261 darwin-arm64, locale ja-JP)
    • Flutter version 3.7.12 on channel stable at /Users/norihanda/fvm/versions/3.7.12
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.19.6/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/norihanda/fvm/versions/3.7.12. Consider adding /Users/norihanda/fvm/versions/3.7.12/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (13 days ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/norihanda/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Users/norihanda/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9862592/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/norihanda/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/norihanda/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9862592/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at /Users/norihanda/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.2)
    • IntelliJ at /Users/norihanda/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/223.8617.56/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at /Users/norihanda/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.8109.175/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (3 available)
    • iPhone SE (3rd gen) (mobile) • 03B36089-EC37-44F8-9ECB-81202133AA60 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)              • macos                                • darwin-arm64   • macOS 13.3.1 22E261 darwin-arm64
    • Chrome (web)                 • chrome                               • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
@noriHanda 
After running `flutter pub add go_router`, the console shows below:

<img width="508" alt="Screenshot 2023-05-02 at 4 33 23 PM" src="https://user-images.githubusercontent.com/67046386/235649542-074ffc3f-49fd-4791-a0d1-c4643b9902f9.png">

Since it no longer depends on `go_router_builder`, you are seeing the result as you mentioned in actual results section which seems to be expected. What do you think ?

**Comment by noriHanda** [comment]
@darshankawar 
Thank you for a reply!
To make sure we are on the same page, `go_router_builder` depends on `go_router`, but not the other way around, right?

So my point is, `go_router_builder 1.2.2` does not support `go_router 7.0.0`, yet we are able to install `go_router 7.0.0` since it is marked as "resolvable" for some reason.

You can see the fact that `go_router_builder 1.2.2` does not support `go_router 7.0.0` by running `build_runner` because `go_router_builder 1.2.2` generates `GoRouteState.params` instead of `GoRouteState.pathParameters` when a path holds parameters.

**Comment by darshankawar** [comment]
Thanks for the update and feedback. I'll keep this issue open and label for team's input for current behavior reported.

**Comment by koji-1009** [comment]
Hi, this issue has been resolved by https://github.com/flutter/packages/pull/3858.
Please try to update to go_router_builder [v2.0.0](https://pub.dev/packages/go_router_builder/changelog#200).

**Comment by noriHanda** [comment]
@koji-1009 Ah, it looks perfect now. Looks like I wasn't patient enough to wait for this update lol. Thank you for the heads up :)
