### ISSUE TITLE
ExpansionTile InkSplash doesn't respect Shape's borderRadius 

### ISSUE THREAD

**Issue by Mayb3Nots** [flutter/flutter#125779]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Similar issue #86603. 

Other failed workaround attempts were to

- Assign `clipBehaviour` to `ExpansionTile`
- Wrapped `InkWell` with `borderRadius`
- Wrapped `ClipRRect` with `borderRadius`

The only workaround that worked is to wrap `ExpansionTile` with `Card` or `Material` suggested in [this SO thread](https://stackoverflow.com/a/70756898/5408464)

The core underlying problem is the `ListTile` under the hood, which has seen many instances of the [same problem.](https://stackoverflow.com/questions/60040972/flutter-listtile-splash-ripple-effect-not-matching-border) Usually the workaround is the wrap the `ListTile` in an `InkWell` however this is not possible with `ExpansionTile`.

1. Run the sample code.
2. Tap on the ListTile to see that the InkSplash doesn't clip the shape's borderRadius

I would like to help to resolve this issue but I am not clear on the proper way to fix this. Is passing the `shape` property to `ListTile` the correct move?

### Expected results

InkSplash should not exceed shape's border

### Actual results

InkSplash exceeds shape's border

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

const Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: darkBlue,
      ),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      clipBehavior: Clip.antiAlias,
      borderRadius: BorderRadius.circular(20),
      child: ExpansionTile(
        clipBehavior: Clip.antiAlias,
        shape: RoundedRectangleBorder(
          side: const BorderSide(color: Colors.black, width: 3),
          borderRadius: BorderRadius.circular(20),
        ),
        collapsedShape: RoundedRectangleBorder(
          side: const BorderSide(color: Colors.black, width: 3),
          borderRadius: BorderRadius.circular(20),
        ),
        title: const Text("InkSplash not respecting shape's borderRaidus"),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://user-images.githubusercontent.com/68549184/235405431-1e752b20-75eb-4c2c-a495-81f8067e91af.mov

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.3.1 22E261 darwin-arm64,
    locale en-MY)
    • Flutter version 3.7.12 on channel stable at /Users/samuel/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (13 days ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version
    33.0.2)
    • Android SDK at /Users/samuel/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12
      (API 31) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS
      13.3.1 22E261 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google
      Chrome 112.0.5615.137
    ! Error: Samuel’s iPhone is busy: Waiting to connect and unlock the device.
      Xcode will continue when Samuel’s iPhone is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @Mayb3Nots 
I think the underlying issue is related to `InkSplash` and that leads me to [this](https://github.com/flutter/flutter/issues/73163) open issue proposing changes to it and `InkRipple` features respectively that you can take a look and follow-up for further updates.

Also check this for further reference: https://github.com/flutter/flutter/issues/20922#issuecomment-1077821379

**Comment by TahaTesser** [comment]
@Mayb3Nots 
Thanks for filing the issue, I can reproduce the behavior

> Is passing the `shape` property to `ListTile` the correct move?

That's right, it looks like the underlying `ListTile` doesn't know about the `ExpansionTile` shape to clip it. 
You don't need to wrap any clipping widget since `ListTile` already has clipping capabilities, just pass the shape


Here I created a simpler code sample

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(useMaterial3: true),
      home: const Example(),
    );
  }
}

class Example extends StatelessWidget {
  const Example({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('ExpansionTile'),
      ),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 20),
          child: ExpansionTile(
            backgroundColor: Colors.red,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(20),
            ),
            collapsedShape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(20),
            ),
            title: const Text('Title'),
          ),
        ),
      ),
    );
  }
}

``` 
	
</details>


### You can see without passing the shape, `ListTile` doesn't clip.


https://user-images.githubusercontent.com/48603081/235712592-26d6a9a1-061a-410b-9f80-1e5c485e06a7.mov


###  When passing the shape


https://user-images.githubusercontent.com/48603081/235712606-850ba82b-c9bb-4f8d-aac1-ac8e2a036c14.mov

**Comment by TahaTesser** [comment]
@Mayb3Nots 
Feel free to file a PR for this with the test.

**Comment by Mayb3Nots** [comment]
> @Mayb3Nots
> 
> > I would like to help to resolve this issue but I am not clear on the proper way to fix this
> 
> Feel free to file a PR for this with the test.

Hi @TahaTesser while working on this, I slowly realized that this may be a little more complicated than I thought. Because the `shape` and `collapsedShaped` properties are used for the "external" widget that surrounds the `ListTile`, so if we just pass in the `shape` property to the `ListTile`, the `ListTile` will inherit all the properties like `color` and `border` which is not what we want.

This is fine if we dont expand it since the shape is the same as the `ListTile`
![IMG_3310B5944272-1](https://user-images.githubusercontent.com/68549184/236613971-b986318b-7d6b-4e13-a115-d4bcff233617.jpeg)


Problem arise when we expands it with children.
![IMG_B74A1359D78A-1](https://user-images.githubusercontent.com/68549184/236613957-cf60556d-0653-4c32-a735-30d7c03aabaf.jpeg)


 And also do we have to take into account for the collapsed and expanded state?

I am thinking maybe just passing in a dedicated `listTileShape` property? What do you think?
