### ISSUE TITLE
Remove single view assumption in Canvas

### ISSUE THREAD

**Issue by dkwingsmt** [flutter/flutter#125780]
`Canvas.cc` depends on the device pixel ratio of window 0 in `Canvas::drawShadow`:

```
  // Not using SafeNarrow because DPR will always be a relatively small number.
  SkScalar dpr = static_cast<float>(UIDartState::Current()
                                        ->platform_configuration()
                                        ->get_window(0)
                                        ->viewport_metrics()
                                        .device_pixel_ratio);

```

We need to get rid of the `get_window(0)` in order to support multi-view.

**Analysis:**
One trivial solution is to make `Canvas` provide a DPR or make it tied to a view. However, it's too much of a change that will only be used for this feature.

Deeper analysis shows that this DPR is just multiplied with the provided elevation:

https://github.com/flutter/engine/blob/main/impeller/display_list/dl_dispatcher.cc#L1113

Technically we could make this work today by multiplying elevation by DPR in the framework. But this breaks the API.

cc @jonahwilliams @goderbauer @loic-sharma

**Comment by jonahwilliams** [comment]
The way I would solve this is:

1. Keep the existing implementation in draw shadow that looks up from the primary window
2. Introduce a new drawShadowV2 that explicitly takes a device pixel ratio
3. Mark the old method as deprecated.

We would probably need to keep it around for quite a while ... but it seems like the only way to make this transition without surprising folks. Expecting the elevation to be multipled by dpr already wouldn't require a new API or any breaking changes, but its a surprising change in behavior and it would be difficult for folks to know if they're doing it wrong.

**Comment by dkwingsmt** [comment]
Yeah, I agree. What about some more meaningful (but lengthy) name such as `drawShadowInLogicalPixel`?

**Comment by jonahwilliams** [comment]
Imagine you have the following code:

```
canvas.drawShadow(path, 4);
```

You see a deprecation warning, so you quickly find and replace without reading the message

```
canvas.drawShadow2(path, 4);
```

Now your code is broken, but you don't actually notice - perhaps because you're on a 1.0 DPR device (or 1.25). If instead you introduced another named parameter, it might be more obvious it required another argument.

On the other hand, maybe this is something that dart fix can just handle?

**Comment by dkwingsmt** [comment]
Duplicate of https://github.com/flutter/flutter/issues/130165.
