### ISSUE TITLE
Create a migrator from min api 16 to min api 19 by using flutter.minSupportedSdk

### ISSUE THREAD

**Issue by reidbaker** [flutter/flutter#125703]
see https://github.com/flutter/flutter/pull/125702
https://docs.flutter.dev/reference/supported-platforms
https://docs.google.com/document/d/1wWNly2SZRDqupSsHkBWDI_lS2MohBGEwPSXF6W05NOc/edit

A migrator is good for customers who built with flutter create and for our own tooling that needs to build at stable and master.

**Comment by stuartmorgan** [comment]
Ideally we should do 17->19 and 18->19 as well; IIRC when we did iOS 9->11 we auto-migrated both 9 and 10 (even though we'd never had a template with 10).

**Comment by reidbaker** [comment]
@stuartmorgan Do you think the migrator should be from number to number or from number to flutter.minSupportedSdkVersion

**Comment by stuartmorgan** [comment]
Good point; migrating to the variable should minimize the need for future migrations.

**Comment by gmackall** [comment]
Closing as completed in https://github.com/flutter/flutter/pull/129729
