### ISSUE TITLE
Problems with rendering a container in Transform.scale

### ISSUE THREAD

**Issue by CodingTurtle2** [flutter/flutter#125768]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

A container is bigger than the screen and you use transform.scale to make all elememts like customdrawer, texts and containers smaller.

### Expected results

The whole container is made smaller and also the stuff, which was outside of the screen, can be seen.

### Actual results

The container is visible, but not the stuff that was previously visible outside of the screen.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}
class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MainApp(),
    );
  }
}
class MainApp extends StatefulWidget {
  const MainApp({super.key});
  @override
  State<MainApp> createState() => _MainAppState();
}
class _MainAppState extends State<MainApp> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Wrap(
        children: [
          Transform.scale(
            alignment: Alignment.topCenter,
            scale: 0.5,
            child: Container(
              width: 6000,
              height: 6000,
              color: Colors.red,
            ),
          )
        ],
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![Bildschirmfoto vom 2023-04-30 14-17-01](https://user-images.githubusercontent.com/104490184/235352538-fe60bd16-3602-4fab-9880-50eeb69aca38.png)

</details>

### Logs

<details><summary>Logs</summary>

```console
Performing hot reload...
Syncing files to device Linux...
Reloaded 1 of 640 libraries in 249ms (compile: 26 ms, reload: 134 ms, reassemble: 71 ms).
```
(Nothing special)
</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.10, on Fedora Linux 38 (Workstation Edition)
    6.2.12-300.fc38.x86_64, locale de_DE.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for
      more details.
[✗] Chrome - develop for the web (Cannot find Chrome executable at
    google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.76.2)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

! Doctor found issues in 2 categories.
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @CodingTurtle2 
Although I see the same behavior as you reported upon running the given code sample, but I didn't completely understand what exactly is the issue along with expected behavior you are looking to have. Also, would like to know the use case you are trying to achieve and usage of `wrap` widget around `Transform.scale` to achieve it.

**Comment by CodingTurtle2** [comment]
I use wrap because otherwise there are render errors because the box is too big.
I thought that it was a bug, because the container is cut off and not completely displayed. I wanted to use it to fit many elements to the width of the screen by enlarging or shrinking them.
But I rather use a custompaint widget right now, which I can also use to scale elements/widgets.
Thanks for the answer!

**Comment by darshankawar** [comment]
Thanks for the update and feedback. Based on your comment above, it seems your issue is resolved by using custompaint, so I'll go ahead and close as resolved. If you disagree, write in comments and I'll reopen it.
