### ISSUE TITLE
Add a project upgrade mechanism

### ISSUE THREAD

**Issue by xster** [flutter/flutter#12573]
We often make changes to the default `flutter create` template. It would be good to have an automated upgrade mechanism that takes various existing native code, yaml, artifacts etc and apply the latest change

- [x] Let `flutter create` leave some sort of version stamp in the produced artifacts indicating the version of the tool when the project was created
- [x] Add some mechanism to compare flutter versions. See how it can be harmonized with version.dart. 
- [ ] Add a `flutter project upgrade` command that takes in a number of 'steps' recipes in a folder that does modifications gated by version comparison conditions. This should warn the users to keep their git working directory clean before proceeding.
- [ ] Let it have a --dry-run option to print a diff patch of the changes.

**Comment by xster** [comment]
Tasks:

- [ ] Let `flutter create` leave some sort of version stamp in the produced artifacts indicating the version of the tool when the project was created
- [ ] Add some mechanism to compare flutter versions. See how it can be harmonized with version.dart. 
- [ ] Add a `flutter project upgrade` command that takes in a number of 'steps' recipes in a folder that does modifications gated by version comparison conditions. 
- [ ] Let it have a --dry-run option to print a diff patch of the changes.

**Comment by xster** [comment]
I'm currently targeting explicit Dart awareness of Flutter revision numbers and applying direct file changes. 

Maybe one day in the future, it might be worth exploring a automatic codeless way of maintaining and auto applying diffs on various versioned .yaml/.json/.xml/.etc templates but so far, the use cases lean more towards direct targeted changes.

**Comment by cbracken** [comment]
Worth explicitly noting that this will need to support interactive steps with confirmation. In #18102 (migrate iOS devicelab tests to universal binaries), supporting migration came up, but there are some (probably rare) cases where an app may legitimately be 64-bit only, so I think we'd want to confirm before updating.

**Comment by zoechi** [comment]
I great first step would be a version number stored with the generated files and `flutter doctor` reporting if the projects generated files are up-to-date  
(even without providing an automated way to upgrade them).

I created https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#generated-project-files-outdated and this seemed to help quite a few times already.

**Comment by xster** [comment]
Merging into #40460 since there's more details now.
