### ISSUE TITLE
`plugin_lint_mac` test fails on Xcode 14.3: a function declaration without a prototype is deprecated in all versions of C

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#125812]
```
pod lib lint packages/integration_test/ios/integration_test.podspec --no-clean
```
fails on Xcode 14.3 in CI:
```
App/main.m:4:9: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8782535317087304833/+/u/run_plugin_lint_mac/test_stdout

This is because
```
int main() {}
```
causes the warning in 14.3.  This was reported in https://github.com/CocoaPods/CocoaPods/issues/11846 and fixed in CocoaPods 1.12.1 in https://github.com/CocoaPods/CocoaPods/pull/11847 which changed it to:
```
int main(void) {}
```

CI version of CocoaPods needs to be updated to 1.12.2.  This is blocked by https://github.com/flutter/flutter/issues/122057.

**Comment by godofredoc** [comment]
Docs on how to create/update ruby packages: go/flutter-ruby

**Comment by godofredoc** [comment]
Removing from ticket queue. This requires recompiling ruby for arm and x64 along with its dependencies and infra gardeners do not have the context on how to do it.

**Comment by jmagman** [comment]
> This requires recompiling ruby for arm and x64 along with its dependencies and infra gardeners

I don't think we need new versions of ruby or bundler, just the gems themselves.

**Comment by godofredoc** [comment]
Umbrella bug for updating the ruby self contained package: https://github.com/flutter/flutter/issues/136377

**Comment by DiegoGW** [comment]
This issue is also impacting Wonderous app (https://github.com/gskinnerTeam/flutter-wonderous-app.git).

![Screenshot 2023-10-12 at 12 12 50](https://github.com/flutter/flutter/assets/11681325/eb7737c2-7e8a-465a-8054-92f9ee078e4e)

**Comment by godofredoc** [comment]
@vashworth can you please help us validate this bug is fixed?

**Comment by godofredoc** [comment]
Removing myself from this bug as only the final confirmation is needed.
