### ISSUE TITLE
list.contains and list.any not working in flutter 3.7.0

### ISSUE THREAD

**Issue by halhwadi** [flutter/flutter#125808]
There is an issue in list.contains and list.any methods in flutter version 3.7.0, the list is not able to check the match items

This block of code run correctly in Dart Pad but not in flutter:
```
`void main() {
  
  
  List<String> token =['hus18qkdQ7xhMq7wmtlueg:APA91bGS4gMfPsSHDcG1G_8LirNIO1rF4iBGQXTE7sGAVz7TtbNgF0HGfBNY9sN1QYn6WVRX4rIV-lDtdcodtAiXv5AIcBLgKzQX1ELXZyEYiwC6LiCm3fihobno1sBQwGt3Zy24Omdm',  'f1Q9fIy8TKavWdJAdjeCze:APA91bFlaSUXatQCLdOfqvux4t3ouX35dQP9m3spyi9OgoAoq9BrFhGMiHF-dVPc2Fps_sOVMYXoL22hqbT6FFe88OalsTNRLUs6a5o8QJkDbUmiIIb2Hv4BbrWCtEkujhbCooPE8ieU',  'cAHG-8BaQkCWB-6Bm4iJq7:APA91bEWa3JORLh2oZim-H75sAbSoETBtJ-rxzDkiIXkL3lFhYOmv8GPL1txkVRQrWPV05NMP6BYEg6336FcexrlvDGVwOe8_n1CxZY1HBR9dwp9eHailsJWiQvqoy2RhtDKD0Efy6wi',  'fb9Wn-EDSpi1vB8WJlb75z:APA91bGtuLJH4b_dXG0Ox7CmZyS5hhGtu-DcwZXn4smb8uXu5cVzx29lWXEmlAtHnGytEFZUsyZS2f0C9bcPbwcrUih60qJDSBb6fwq6gfJk1Ig-qYoWDglZgeAc-HpCTYaauKwlCFSF',  'diUBj0CLQe-y1zax_Hsjon:APA91bFprxQ4AxfUNc0OCh2T34rZSelX-3l8xX89Pgr8y0E9VqX3T9iOh5E40dlR7TlXCkQYjpA5zc2NV9OyenXlNKBsCbquppyh1sHQxHZGJ20kYcdfYG9BCBQyjWyKLWVA9cES7ZUa',  'ftLcwbBbSDG-2de6wEkITF:APA91bEEG4HA7gLWCdEnFBTGnM551R4oITJ4qbWqWxtsDuryams6Lnzhj61DAME_uyV1Iw5JDgAm3VJLOyMxHsHT1QoZYa-xnl9y_mg-8LijXq9_94E-UNYXkFnoAPGjjomKs-tTpzYD'];
 
  if (token.any((item) => item == 'ftLcwbBbSDG-2de6wEkITF:APA91bEEG4HA7gLWCdEnFBTGnM551R4oITJ4qbWqWxtsDuryams6Lnzhj61DAME_uyV1Iw5JDgAm3VJLOyMxHsHT1QoZYa-xnl9y_mg-8LijXq9_94E-UNYXkFnoAPGjjomKs-tTpzYD'))
  {
    print('avaliable');
  }
  else {
    print('not avaliable');
  }

}`
```

Flutter doctor:
 Flutter (Channel stable, 3.7.0, on Microsoft Windows [Version 10.0.22621.1555], locale en-AE)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.4)
[√] Android Studio (version 2022.1)
[√] Connected device (4 available)
[√] HTTP Host Availability

dart version 2.19.0

**Comment by danagbemava-nc** [comment]
Hi @halhwadi, you are using an older version of flutter and an older version of dart. 

What you have is a plain dart program which means this is not a flutter issue. Kindly upgrade to the latest version of flutter stable (3.7.12) to see if you still face this issue.  Your dart version after the upgrade should be 2.19.6

If you experience this issue after upgrading to the latest version of flutter, kindly file an issue on the dart repo. 

Closing from here.

Thank you

PS: I run the code sample on both dartpad & locally with (flutter 3.7.12) and I saw the same result in both cases.
