### ISSUE TITLE
App state is lost when changing display density on Android

### ISSUE THREAD

**Issue by aam** [flutter/flutter#12588]
1) In Flutter Gallery app navigate to 'Shrine basic shopping app',  add an item to the shopping cart.
2) go to Android Settings/Display/Advanced/Display size, move the slider selecting new value.
3) Switch back to Flutter Gallery app, note that you land on Flutter Gallery main page, and when you go to 'Shrine', shopping cart is empty there as well.

Root cause seems to be that Flutter framework doesn't handle `density` in it's AndroidManifest.xml configuration changes handler, which results in app restart, losing it's state.

**Comment by Hixie** [comment]
The general problem is https://github.com/flutter/flutter/issues/6827.
We should probably set the flag to not restart when this particular change is made though.

**Comment by jonahwilliams** [comment]
For new apps created with `flutter create`, they will have the correct flag set to not restart.  Existing apps, however, will have to adjust their `AndroidManifest.xml` to included density and screenLayout.

**Comment by Hixie** [comment]
we should make sure to document that on the changelog and on flutter-dev
and ideally, even handle it automatically. @xster was setting up the infrastructure to do that iirc.

**Comment by xster** [comment]
#12573, though I'm not currently working on it

**Comment by jonahwilliams** [comment]
Since we're not currently working on the tool and this has been fixed since march I'm going to close the issue. Making an automatic fix should be a separate bug
