### ISSUE TITLE
Sector demo button shadow disappearance

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1258]
When you enable the "remove" button by clicking the "add" button, it gains a shadow, which it immediately loses once the animation is done. Also, if you poke at it sometimes you can get it to only render 2 of the shadows on one of the buttons instead of all 3.

I've tracked this at least as far as BoxPainter, though I suspect the engine or skia. (That is to say, I've proved to myself that the shadow description is present in the BoxDecoration that we try to paint in the BoxPainter, but I haven't traced it past that step to the next step, which is the actual Dart-side paint calls.)

**Comment by Hixie** [comment]
```
08:33 <        abarth> to test, you can hack up the constructor for PictureRecorder
08:33 <        abarth> to pass a Rect
08:33 <        abarth> that's goes from -1000, -1000 to 1000, 1000
```

**Comment by abarth** [comment]
That doesn't seem to make a difference...

**Comment by Hixie** [comment]
dupe of https://github.com/flutter/flutter/issues/1576
