### ISSUE TITLE
Support non-uniform Borders with a non-zero borderRadius

### ISSUE THREAD

**Issue by theobouwman** [flutter/flutter#12583]
https://github.com/flutter/flutter/blob/9ce3ba314eed296812f2176d7a5bbc66e01ba199/packages/flutter/lib/src/painting/box_border.dart#L462

```dart
new BoxDecoration(
    color: color,
    border: new Border(
      left: new BorderSide(color: color),
      top: new BorderSide(color: color),
      bottom: new BorderSide(color: color),
    ),
    borderRadius: new BorderRadius.only(
      topLeft: new Radius.circular(radius),
      bottomLeft: new Radius.circular(radius),
    ),
)
```
Why can't I do this.

I get this error:

```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
A borderRadius can only be given for uniform borders.
'package:flutter/src/painting/box_border.dart': Failed assertion: line 462 pos 12: 'borderRadius ==
null'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
https://github.com/flutter/flutter/issues/new

When the exception was thrown, this was the stack:

The following RenderObject was being processed when the exception was fired:
RenderDecoratedBox#9302a relayoutBoundary=up6
creator: DecoratedBox ← Container ← Listener ← _GestureSemantics ← RawGestureDetector ←
GestureDetector ← _CupertinoSegmentControlItem ← Row ← Padding ← Column ← CupertinoSegmentControl
← MediaQuery ← ⋯
decoration: BoxDecoration
RenderPadding#09d88 relayoutBoundary=up7 NEEDS-PAINT
RenderParagraph#85b48 relayoutBoundary=up8 NEEDS-PAINT
```

## Flutter Doctor
```
[✓] Flutter (on Mac OS X 10.13 17A405, locale en-GB, channel master)
    • Flutter at /Users/theobouwman/Development/flutter
    • Framework revision ad72c78342 (19 hours ago), 2017-10-16 10:58:39 -0700
    • Engine revision 7c4142808c
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /Users/theobouwman/Library/Android/sdk
    • Platform android-26, build-tools 26.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.0, Build version 9A235
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.5)
    • Flutter plugin version 17.0
    • Dart plugin version 172.4155.35

[✓] Connected devices
    • iPhone X • 6EE42D9C-C0E5-4E0B-AB0C-AC343B53C4EF • ios • iOS 11.0 (simulator)
```

**Comment by Hixie** [comment]
The first line of the error message gives you the answer: "A borderRadius can only be given for uniform borders."

**Comment by Hixie** [comment]
(The reason being, there's no real separation between the "top" and "left" borders if there's a "topLeft" corner.)

**Comment by theobouwman** [comment]
okay I understand. but how could I accomplish my needs?

**Comment by Hixie** [comment]
What are your needs?

**Comment by theobouwman** [comment]
I want to have a top, left and bottom border with a topleft and bottomleft borderRadius.
The cupertino_segement_control plugin I created (https://github.com/theobouwman/flutter_cupertino_segment_control/blob/master/lib/cupertino_segment_control.dart#L19) is currently limited to 3 items because I cannot find a way to create a BoxDecoration with 3 borders and 2 rounded corners.

**Comment by Hixie** [comment]
Can you post an image showing how it should render?

**Comment by 0916174** [comment]
Guess you can close this, right?

**Comment by bramvbilsen** [comment]
Is it something like this that you want?
![screenshot_1525892150](https://user-images.githubusercontent.com/16825392/39833798-64077818-53cb-11e8-907e-7187c1f818a7.png)
I've created a `CustomRoundedRectangleBorder` class for this, perhaps it'd be nice to have this in Flutter.
@Hixie Do you think that'd go through as a PR?

**Comment by jeroen-meijer** [comment]
That'd be nice. PR will get a higher chance of approval if you add some documentation. Is this `CustomRoundedRectangleBorder` available anywhere, on your git perhaps?

**Comment by bramvbilsen** [comment]
@jeroen-meijer I've actually filed the PR yesterday. You can find it here: https://github.com/flutter/flutter/pull/17441

**Comment by nokia6290** [comment]
Has this been fixed?

I've encountered a similar problem. Except in my case I can create a custom BorderRadius but it hides text completely that should be in the middle..

**Comment by TaroXin** [comment]
Is there a solution? I think I have the same problem

![image](https://user-images.githubusercontent.com/19855713/45683323-d73c8400-bb08-11e8-9bf8-cff81dd24866.png)

The same is true for log printed information

**Comment by Hixie** [comment]
We don't currently support, out-of-the-box, having colors on individual sides when there's rounded corners, because we don't really know what that means. Check out the code in this PR, though, which @bramvbilsen mentioned above: https://github.com/flutter/flutter/pull/17441/files
It may be of use. It would be great if someone made it into a package!

**Comment by dalewking** [comment]
I get that if you specified a border radius on a particular corner and the border on the 2 adjacent sides were different then it is kind of undefined what it should do.

However if I specify a border radius on a corner and the border specified on the 2 adjacent sides are the same, that should be allowed and is defined. You simply do the same thing for that corner that you would do in the uniform case.

So if I specify only bottom left and bottom right rounded corners why should it matter if only the top border is different?

**Comment by mdnpascual** [comment]
I too would like to have this feature. 

I would like to have the bottom one possible but I'm getting blocked with the borderRadius requiring uniform borders.

![mokup](https://user-images.githubusercontent.com/1689277/56166944-0ed2b800-5f94-11e9-8e7d-3c47b290c82b.jpg)

**Comment by valerybodak** [comment]
If you just want to implement the following border with the rounded corners for Container then you can use LinearGradient.

<img width="683" alt="Screen Shot 2019-04-20 at 4 19 52 PM" src="https://user-images.githubusercontent.com/26433088/56457777-2f31b680-6388-11e9-81c4-92a46a8e341a.png">

Please see my implementation:

```
Container(
          decoration: new BoxDecoration(
              gradient: new LinearGradient(
                stops: [0.02, 0.02],
                colors: [Colors.red, Colors.white],
              ),
              boxShadow: [AppTheme.Decorations.containerShadow],
              borderRadius: new BorderRadius.all(const Radius.circular(6.0))))

```

**Comment by ozc** [comment]
Even defining corners one by one leads to this error. 

Have not checked the Flutter codebase for this, but it should be easier than checking the uniformity border. Just leave the control to the user, and instead of checking if the border is uniform, just check which corner does not meet criteria and throw an error for that corner.

**Comment by BesartLaci** [comment]
@valerybodak  thanks :) works like a charm ^^
i found also some other aproach for setting Borders and Corners sepearated
https://stackoverflow.com/a/58141303

**Comment by nicoroy2561** [comment]
This should be added to the main Flutter library, or normal Containers should be allowed to paint different borders if rounded+colored. Having to change widget upon trying to make a border curved isn't ideal.

**Comment by wilburt** [comment]
Please, is there any update on this?

**Comment by peruho** [comment]
Agreed with @ozc. 
If I don't have a border radius on any of the corners from a side I don't want to show, where is the problem? Instead of checking uniformity on border width or colors, checking the criteria of each corder should do the trick.
I'm facing a similar problem than @mdnpascual

**Comment by Yann39** [comment]
Same problem here, I need top left and top right border radius, but I don't want any bottom border. Can't see any reason not to allow this :

```dart
BoxDecoration(
  border: Border(
    right: BorderSide(width: 1.0, color: Colors.blue),
    left: BorderSide(width: 1.0, color: Colors.blue),
    top: BorderSide(width: 1.0, color: Colors.blue),
  ),
  borderRadius: BorderRadius.only(topLeft: Radius.circular(6.0), topRight: Radius.circular(6.0)),
)
```

**Comment by TechSatya** [comment]
This one is a very common use-case, but sadly not supported yet.

I'm getting this;
![Screen Shot 2020-05-02 at 12 24 16 PM](https://user-images.githubusercontent.com/27278747/80857510-68298a00-8c70-11ea-9fd0-7979e3b5ced5.png)

But I want to remove the right border completely.

Workaround:
```
Container(
                          decoration: BoxDecoration(
                            border: Border(
                              top: BorderSide(width: 2.0, color: Colors.white),
                              bottom: BorderSide(width: 2.0, color: Colors.white),
                              right: BorderSide(width: 2.0, color: Colors.white),
                            ),
                            borderRadius: BorderRadius.only(topLeft: Radius.circular(30), bottomLeft: Radius.circular(30)),
                            color: Colors.transparent
                          ),
                          child: FlatButton(...),
                        )
```

**Comment by Sparks1998** [comment]
I know I am late but for those who still have the same problem got to this site and you will find your answer https://stackoverflow.com/questions/56928862/flutter-rounded-rectangle-border-with-different-colours-for-each-side

**Comment by Hixie** [comment]
The Border system is entirely extensible; I encourage everyone who has specific needs here to write a custom ShapeBorder subclass that does what you would like and post it as a package on pub.dev.

Here's an example of a different shape as a pub package: 
    https://pub.dev/packages/superellipse_shape

The code is pretty straight forward:
    https://github.com/Salby/superellipse_shape/blob/master/lib/superellipse_shape.dart

**Comment by shamilovtim** [comment]
Still needs to be fixed

**Comment by Hixie** [comment]
@shamilovtim yup, that's why it's still open. We haven't fixed this yet because it's not 100% clear how to fix it without making this a very elaborate solution and we'd rather that elaborate borders be done in packages (there's lots of sample code above in this bug if anyone wants to make such a package).

**Comment by shamilovtim** [comment]
If it's so complex that you can't officially support it but so easy that just anyone can plop down a third party package with some copy and paste then we've got a bit of a contradiction

**Comment by Hixie** [comment]
It's not complicated in either case, it's more that there are many different ways you could do it, and we'd rather the framework didn't end up being a one-size-fits-all swiss army knife, but rather a solid base on which to build things. (The elaborate solutions such as those described earlier in this bug are relatively simple, code-wise.)

**Comment by spiderion** [comment]
`  Widget doubleColorMarginBackground(Widget child) {
    return Container(
        child:
            Container(decoration: BoxDecoration(color: lyveWhite), margin: EdgeInsets.all(6), child: child),
        margin: EdgeInsets.all(6),
        decoration: new BoxDecoration(
            gradient: new LinearGradient(stops: [0.5, 0.5], colors: [Colors.blue, Colors.red]),
            borderRadius: new BorderRadius.all(const Radius.circular(6.0))));
  }`

**Comment by bramvbilsen** [comment]
I see this is still open 2 years later. As @Hixie explained, the border system is entirely extensible. I made a PR for creating non-uniform borders a while ago, but it did not get accepted because as discussed above, it'd make more sense to make a package out of it. Whether you agree with that or not, the code for the PR is still available, so if someone really needs it, you can get the code (not tested since I made the pr) here: https://github.com/flutter/flutter/pull/17441
I never ended up making it a package, but feel free to do so.

**Comment by chornbe** [comment]
I fully admit to not understanding why each corner could be different radii. The classic example is a simple little box with top left and top right corners radiused at, say, 10, while the bottom right and bottom left are radiused at 0 (square). Not really understanding why this won't work in a container's decoration definition... especially considering the corners are explicitly named. 

              /* borderRadius: BorderRadius.only(
                  topLeft: Radius.circular(10),
                  topRight: Radius.circular(10),
                  bottomLeft: Radius.circular(0),
                  bottomRight: Radius.circular(0),
                ), */

**Comment by Hixie** [comment]
@chornbe Can you post a screenshot of what you'd like it to look like? See also some of the earlier comments here with sample code and suggestions that people create packages for this.

**Comment by chornbe** [comment]
Yeah, here's a snippet from a screen cap. In the highlighted area, left, is how I did it - close enough for my liking, for this rev-1 rewrite (replacing a native iOS / Swift app and a React Native Android app). 

The highlighted dropped-in part on the right is what I'm going for. It seems I can have *some* curved corners with a uniform border, or I can have border on *some* sides (with no radius corners), but no both. 

What you see there is really three containers; a transparent overall container, the tab container (with the next), and an AnimatedContainer below it for the body. When you tap the tabbed-looking container, the lower container increases in side and appears to slide up. 

![example](https://user-images.githubusercontent.com/7502201/88713077-bb34a100-d0e8-11ea-96e0-b63a54bc13a1.png)

**Comment by Hixie** [comment]
Ah, I see. For that I would just create a new ShapeBorder class that does the path you want.

**Comment by chornbe** [comment]
Ah, subclass it as its own thing, and draw the path?

**Comment by Hixie** [comment]
Yup. There's a bunch of examples of classes that implement ShapeBorder in the framework. Mostly in the `painting` library I think.

**Comment by chornbe** [comment]
Also, after reading through the comments, if I could suggest something...? I assume the vertical and horizontal lines are drawn independently of each other as paths or whatever drawLine(...) function the platform and layers under it provide...? , And if there are border radii, they too are drawn as arcs, independently? If so, maybe a future Border (et al) expansion could add/include not only border:(...) properties for top, bottom, left, and right, but could also have addressable topLeft:(...), topRight:(...), bottomleft:(...), and bottomRight:(...) arcs or paths that have their own sets of properties.  They could simply be ignored, individually, if the radius is null or 0 for any given one. Given that, the example in bramvbilsen's post above would be fairly trivial to draw. 

#foodforthought

**Comment by Hixie** [comment]
If the styles are uniform we use this code (which does it all as one path):
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/painting/box_border.dart#L211

If the styles are not uniform we use this code (which doesn't support rounded corners):
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/painting/borders.dart#L675

**Comment by lekanbar** [comment]
Just published a simple package, directly based on @bramvbilsen's code, check here for anyone interested: https://pub.dev/packages/custom_rounded_rectangle_border

**Comment by fluttercorner** [comment]
[How to add Border Radius to Container in Flutter ?](https://fluttercorner.com/how-to-add-border-radius-to-container-in-flutter/)

**Comment by amatshiye** [comment]
I ended using ClipRRect. Hope we get this feature on a container 

`ClipRRect(
      borderRadius: BorderRadius.only(
        topLeft: _topRadius,
        topRight: _topRadius,
      ),
      child: Container(
        decoration: BoxDecoration(
          color: Colors.white,
          border: Border(
            bottom: BorderSide(color: AppColors.bostonBlue),
          ),
        ),
),`

**Comment by KevinVan720** [comment]
If anyone is still looking for an alternative solution, check out this package: https://pub.dev/packages/morphable_shape.

**Comment by okarpov** [comment]
still not fixed. no way to disable/hide/recolor any single border if radius is applyed

**Comment by tantana5** [comment]
I want draw something like that
![image](https://user-images.githubusercontent.com/19582951/116285895-d2f49f00-a7b8-11eb-8c83-887791619e2b.png)

Here is my code, but it throw the fu*king error: "A borderRadius can only be given for a uniform Border...."
```
BoxDecoration(
  border: Border(
    top: BorderSide(color: Colors.red),
    left: BorderSide(color: Colors.red),
    right: BorderSide(color: Colors.red),
    bottom: BorderSide(color: Colors.transparent),
  ),
  borderRadius: BorderRadius.only(
    topLeft: Radius.circular(8),
    topRight: Radius.circular(8),
  ),
  color: Colors.white,
)
```
So I edited the bottom border "Colors.transparent"-> "Colors.red" just like the line above, It worked fine. 
I don't know what they think when they do that? Very very stupid!!!

**Comment by rfitz123** [comment]
An edge case that makes sense to be supported within `BoxDecoration` is if the corners with a non-zero border radius *are* uniform even if the border as a whole is not uniform. I believe this is @chornbe use case as well. I understand there are ways to implement this already mentioned above, but this case feels like a limitation of the implementation, whereas not supporting rounded corners between two mismatched borders makes sense because someone would have to define the behavior there.

Example:
```
BoxDecoration(
    border: Border(left: greenBorder, right: greenBorder, bottom: greenBorder),
    borderRadius: const BorderRadius.vertical(bottom: Radius.circular(8)),
)
```

**Comment by chornbe** [comment]
Agreed, yes. 

The argument will come back as “what to do with rounded corners” (I’ve had this conversation more than once LOL), and IMO, you simply do that by (default) clockwise drawing (optional counter clockwise?). So if you have rounded borders, to create an example, the top-right rounded corner would be drawn with the same parameters as the top edge, the bottom right drawn the same as the right, the bottom left drawn the same as the bottom, and the top left drawn as the left.

**Comment by rydmike** [comment]
This is still an annoying little limitation in Flutter SDK, imo at least. For example ToggleButtons paints its own widget with borders to avoid this limitation.

I recently as fun challenge asked people on Twitter to try draw this in Flutter: 
![image](https://user-images.githubusercontent.com/39990307/131267671-e711336d-8149-4330-a0e6-2fd76608c0fd.png)

Just to see what FlutterDev's would come up it. Here is the Tweet: https://twitter.com/RydMike/status/1431999590547476483

The initial reaction was, I can just do this with `BoxDecoration` easily, until they hit the limitation and start scratching their heads for workarounds and hack together some really wonderful options in the thread. 

I collected all reasonably working workaround solutions in this DartPad:
https://dartpad.dev/?id=691628e75729aa75d3143740f87e91b3&null_safety=true

You can get it in a Gits here too: https://gist.github.com/rydmike/691628e75729aa75d3143740f87e91b3

---

I did not know about this old issue post about this issue when I made the Tweet. I actually found found this issue when I was searching for a mentioned PR in the Tweet thread, a PR that is supposed to include a fix for this issue. I did not find any such PR, but maybe there is one, or perhaps the person was referring to this case: https://github.com/flutter/flutter/pull/17441 that includes a rather nice solution that was later published as a package too.

**Comment by chornbe** [comment]
I did it by using a stack. Stupid work around. But it worked. Yay, more code!!! :(

**Comment by chaudharydeepanshu** [comment]
Still waiting for a solution on this. This is a pretty basic requirement. -_-

**Comment by shamilovtim** [comment]
Years after working on Flutter this most basic of tickets still isn't resolved. In fact, none of the basic requests for Flutter that I've seen have ever been fixed. Made the right bet on React Native.

**Comment by chornbe** [comment]
I've retired all but on of our flutter projects, rewritten in native code. I'm done - absolutely, wholly, completely done - with cross platform going forward. I don't care if this or anything else ever gets fixed in Flutter. Typical Google.

**Comment by chaudharydeepanshu** [comment]
Lol. Yeah, I have also moved to jetpack compose recently for my new projects and tbh I'm in love with jetpack compose.
And now Flutter UI designing feels dull and over-complexed.

I was just waiting for this fix so that I can add this type of design also to my calendar package:

| Current | Hoping for after this fix| 
--- | --- |
| ![WhatsApp Image 2022-08-03 at 9 48 09 PM](https://user-images.githubusercontent.com/85361211/182662338-55e7bcc8-95aa-4aa3-9ec3-5175375f5c01.jpeg) | ![WhatsApp Image 2022-08-03 at 9 48 09 PM](https://user-images.githubusercontent.com/85361211/182662393-ea2bb4f6-34e0-481c-ad2f-ffca5b1411a8.jpg) |

**Comment by nicoroy2561** [comment]
This is getting off-topic, but I'll just mention that after working for 2+ years with Flutter, this is no longer something I feel as a big limitation. It did feel weird coming from web development to not have the ability to set different borders out of the box, but workarounds are pretty easy to implement once you get used to it.
Not even mentioning there's a solution from within this thread as well.

While I agree it's taking the Flutter team a long time to merge this one in / fix this specific need, it's by no means a deal breaker if you know what you are doing.

**Comment by chornbe** [comment]
Agreed. The strengths and the problems with Flutter are both *way* bigger than this.

**Comment by chaudharydeepanshu** [comment]
I know its not a deal breaker but still adding extra code in the app for something so trivial looks pretty bad. 

Also, solutions suggested above are great but none of then really looked great in my case where there is too much complexity with styling already going on. 
For example the above solutions doesn't work great if the code is written with Ink widgets in mind as most are good replacement for container but container affects ripple effect for which then I had to add one more workaround for ripple. So you can see why I feel this way.

But yeah I can totally make it work but then the code looks pretty bad.

So, **once this gets fixed it will be just few line code**.

**Comment by chornbe** [comment]
It's never getting fixed. "Code looking bad"...? All code looks bad; our entire existence is to minimize the bad and make it readable for the next guy. Just write the code, wrap it in a widget, done. Who cares how it looks as long as it works and isn't a performance dog. No one's going to look at that one stupid hack and not hire you ever again because you found a way to do a thing that the language and platform didn't do intrinsically - which is also 100% of our job. Our entire job is to make the Taj Mahal from legos. Even the Taj Mahal has areas that will always need work. If you're stressing about code that doesn't "look good" doing a custom border, I'd say you solved all the real problems and you're just being pedantic.

**Comment by chaudharydeepanshu** [comment]
> It's never getting fixed. "Code looking bad"...? All code looks bad; our entire existence is to minimize the bad and make it readable for the next guy. Just write the code, wrap it in a widget, done. Who cares how it looks as long as it works and isn't a performance dog. No one's going to look at that one stupid hack and not hire you ever again because you found a way to do a thing that the language and platform didn't do intrinsically - which is also 100% of our job. Our entire job is to make the Taj Mahal from legos. Even the Taj Mahal has areas that will always need work. If you're stressing about code that doesn't "look good" doing a custom border, I'd say you solved all the real problems and you're just being pedantic.

Yeah totally agree with you on that man.

No issues I will create a package myself fixing the caveats in above solutions and then I will share it with the community.

**Comment by akarabach** [comment]
any updates here ? 5 years long...

**Comment by nzkn** [comment]
Still not fixed?

**Comment by TheStrongest** [comment]
It's strange that this issue is yet to get a fix after 5 years.

**Comment by chornbe** [comment]
Welcome to Flutter development. :\

**Comment by dalewking** [comment]
I just want to note that this issue is with BoxBorder, but there is also ShapeBorder that does not have this issue (I am using that on another project that I want the shape rounded on 2 corners). So perhaps that is usable for some of the use cases.

**Comment by ilyosbekkk** [comment]
is there any updates on this issue?

**Comment by eldarkk** [comment]
For hiding some borders, Stack with white layer above saved my month.

**Comment by ak1987** [comment]
A very old-school css solution from ancient times when rounded corners were made by 4 background images in 4 divs.
The code above gives top-rounded container with no bottom border:

```
Container(
                  color: AppColors.appBar,
                  child: Container(
                    height: 20,
                    decoration: const BoxDecoration(
                      color: Colors.red,
                      borderRadius: BorderRadius.vertical(top: Radius.circular(22), bottom: Radius.circular(0)),
                      // color: AppColors.scaffold
                    ),
                    child: Container(
                      height: 20,
                      margin: const EdgeInsets.only(top: 1, left: 1, right: 1),
                      decoration: const BoxDecoration(
                        color: Colors.green,
                        borderRadius: BorderRadius.vertical(top: Radius.circular(20), bottom: Radius.circular(0)),
                        // color: AppColors.scaffold
                      ),
                    ),
                  ),
                ),
```

**Comment by bernaferrari** [comment]
I (finally) made a package for a shape border that does non-uniform borders. https://github.com/bernaferrari/non_uniform_border

I'm also submitting a PR for adding it into Border (BoxDecoration). I don't like, I prefer ShapeDecoration, but then you can choose between using my package or BoxDecoration.
