### ISSUE TITLE
Add scrollPhysics: param to CupertinoPicker

### ISSUE THREAD

**Issue by KeithBacalso** [flutter/flutter#125859]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I have a project that has can be deployed in both iOS and Android. Our scrolling should be the same as the BouncingScrollPhysics of iOS. Problem is that there is no `scrollPhysics` param in `CupertinoPicker` to do that. 

Package in pub.dev that solved this issue:
custom_cupertino_picker
https://pub.dev/packages/custom_cupertino_picker/install

### Proposal

* I would like to propose a feature where the user is given the freedom to change the scrollPhysics of CupertinoPicker.

**Comment by moffatman** [comment]
I solved it myself using this method

```dart
ScrollConfiguration(
  behavior: ScrollConfiguration.of(context).copyWith(
    physics: _ModifiedBouncingScrollPhysics() // replace with your physics
  ),
  child: CupertinoPicker.builder(/* ... */)
)
```

**Comment by KeithBacalso** [comment]
> Thanks for the report @KeithBacalso
> 
> > Package in pub.dev that solved this issue:
> > custom_cupertino_picker
> > https://pub.dev/packages/custom_cupertino_picker/install
> 
> If this package offers the feature that you are proposing, maybe you can go with it instead of having the same feature in the framework ? Since not each and every feature / functionality can be implemented out of the box, hence there are community packages that helps with offering the feature. What do you think ?

@darshankawar The package I gavew is fine, but there is one thing that did not follow the original CupertinoPicker style from Flutter in that package is the `highlighted or selected item` notice Flutter's uses container, while the package uses border.

**Comment by darshankawar** [comment]
Thanks for the update and feedback @KeithBacalso 
Please check @moffatman's comment / solution above and see if it helps in your case or not.
https://github.com/flutter/flutter/issues/125859#issuecomment-1532089194

**Comment by KeithBacalso** [comment]
> Thanks for the update and feedback @KeithBacalso Please check @moffatman's comment / solution above and see if it helps in your case or not. [#125859 (comment)](https://github.com/flutter/flutter/issues/125859#issuecomment-1532089194)

@darshankawar woah yes it does I dont think there is a StackOverflow solution for that, but thanks so much @moffatman  😀

**Comment by darshankawar** [comment]
Good to know. Closing as resolved.
