### ISSUE TITLE
[CP] fix DartDebugException thread was not found

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#125834]
### issue_link

https://github.com/flutter/flutter/issues/125832

### Commit Hash

https://github.com/flutter/flutter/commit/b2f22321329f3c4d8b621a3997af99d6ccc0ffbb

### Target

beta

### pr_link

https://github.com/flutter/flutter/pull/125831

### Impacted Users

Any flutter developer debugging a flutter app from VSCode

### Impact Description

While trying to resume a paused Dart VM isolate, the flutter tool (and thus the debug session) will crash.

### Workaround

Retrying the debug session may work. This seems like a race condition, so retrying may or may not work.

### Risk

low

### Test Coverage

yes

### Validation Steps

I was not able to reproduce this locally (it's most likely some race condition), so validation can only happen post release in crash reporting.

**Comment by christopherfujino** [comment]
@bkonyi can you approve this CP request?

**Comment by CaseyHillers** [comment]
Adding the label "cp: approved" on behalf of @bkonyi as they approved the CP PR.
