### ISSUE TITLE
We want iOS bottomsheet to look natively 

### ISSUE THREAD

**Issue by crazidev** [flutter/flutter#125853]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

In flutter when sliding up the bottomsheet, it Doesn't scale the previous screen or bottomsheet like the native iOS bottomsheet

https://user-images.githubusercontent.com/108380155/235563774-319cb59b-958a-4a49-8cc5-f8f4f3e69f35.MOV

If you look the preview screen is animating with scaling effect when sliding up bottomsheet 

### Proposal

we want this feature on iOS devices, we will be glad if this feature is added to the next flutter release version

**Comment by darshankawar** [comment]
Thanks for the report @crazidev 
Have you already checked if the feature is offered by any community package that you can leverage already ?

**Comment by crazidev** [comment]
Yes it's not offered anywhere, I think only the flutter main developers can add that features because that transition affects the screen displayed behind, and it should be done on all screen on iOS that bottomsheet is active

**Comment by MinseokKang003** [comment]
@crazidev Just passing by, see [https://pub.dev/packages/modal_bottom_sheet](https://pub.dev/packages/modal_bottom_sheet)

**Comment by crazidev** [comment]
Thank you for this, I appreciate
