### ISSUE TITLE
UIPasteControl prompting for user consents

### ISSUE THREAD

**Issue by martnst** [flutter/flutter#125892]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. See my reproducer at https://github.com/martnst/flutter_uipastecontrol_bug incl. screencast
2. Run the app in the Simulator
3. Ensure you have a string / text in your clipboard so that the paste button is enabled. 
4. Press the UIPasteConrol button 

### Expected results

The app / iOS prompts the user of for consent to allow pasting content. 

### Actual results

The UIPasteControl should read from the clipboard without prompting. 

### Code sample

See https://github.com/martnst/flutter_uipastecontrol_bug

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

See screencast inlcuded in reproducer repo.

</details>

### Logs

<details><summary>Logs</summary>

Sorry, I could not find any helpful logs. 
</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
flutter doctor -v 
[✓] Flutter (Channel stable, 3.7.11, on macOS 13.3.1 22E261 darwin-arm64, locale en-DE)
    • Flutter version 3.7.11 on channel stable at /opt/homebrew/Caskroom/flutter/3.7.11/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f72efea43c (3 weeks ago), 2023-04-11 11:57:21 -0700
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/martin/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (3 available)
    • iPhone 14 (mobile) • 8D3C3921-4613-42E4-A473-03391B97639F • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 13.3.1 22E261 darwin-arm64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @martnst, this is a known issue. It is being tracked in https://github.com/flutter/flutter/issues/103163.

Kindly subscribe to the original issue for updates.

Closing from here as duplicate. 

Thank you

**Comment by martnst** [comment]
@danagbemava-nc  thanks for looking into it. 

Well… I am not sure if that's the exact same issue. For sure, it is related. 

However, #103163 is about adding / improving support for pasting in flutter. To me, this reads more like a feature request. What I did, though, is implementing the `UIPasteControl` myself rather than waiting for the new feature. Doing so, I encounter unexpected behavior, thus a Bug. 

That's different, isn't it? 

Bests, 
Martin

**Comment by danagbemava-nc** [comment]
Hi @martnst, if you're manually calling the UIPasteControl API I'm not sure there's anything for us to do on our end since we don't have any control over how the native apis respond. It does seem like this happens in native ios development too. See https://developer.apple.com/forums/thread/714296

**Comment by martnst** [comment]
Hi @danagbemava-nc, thanks for pointing out the thread on the Apple developer forum. The reason why I brought it up here in at Flutter was, that it seems to be depending on value of `CupertinoThemeData.barBackgroundColor` as you can see in Screencast provided with my reproducer. 

That said, I keep investigating the problem.
