### ISSUE TITLE
'package:flutter/src/material/dropdown.dart': Failed assertion: line 1260 pos 12: 'widget.items!.where((DropdownMenuItem<T> item) => item.value == widget.value).length == 1': is not true.

### ISSUE THREAD

**Issue by abdullah-pak7** [flutter/flutter#125873]
Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.

**Comment by abdullah-pak7** [comment]
import 'package:flutter/material.dart';

class DropDownImage extends StatefulWidget {

  @override
  State<DropDownImage> createState() => _DropDownImageState();
}

class _DropDownImageState extends State<DropDownImage> {
  
  String? selectedCountry;
  List<Map> countiesJson = [
    {
      'id': 1,
      'image': 'assets/images/pak_flag.png',
      'name': 'pak',
      'code': '+92',
    },
    {
      'id': 2,
      'image': 'assets/images/qatar_flag.png',
      'name': 'qtr',
      'code': '+974',
    },
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Container(
              child: DropdownButtonHideUnderline(
                child: ButtonTheme(
                  alignedDropdown: true,
                  child: DropdownButton(
                    hint: Text('Select Code'),
                    value: selectedCountry,
                    onChanged: (newValue){
                      setState(() {
                        this.selectedCountry = newValue;
                      });
                    },
                    items: countiesJson.map((countryItem) {
                      return DropdownMenuItem(
                        child: Row(
                          children: [
                            Image.asset(countryItem['image'], width: 20,),
                            SizedBox(width: 15,),
                            Text(countryItem['code']),
                          ],
                        ),
                      );
                    }).toList(),
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

**Comment by danagbemava-nc** [comment]
Hi @abdullah-pak7, your issue is that you're not giving a value to the `DropdownMenuItem`. 

Pass the intended value to the `DropdownMenuItem` and make sure that the values are `unique` and you will not run into this issue. 

Closing from here as this is an implementation issue. 

Thank you
