### ISSUE TITLE
Tree is red on build_test missing the os= dimension

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#125897]
os= dimension is now required to ensure the proper drone bots are being selected.

**Comment by drewroengoogle** [comment]
It looks like with the recent PR (#125898) that the tests that were failing have progressed past the point they failed. Will continue to monitor

**Comment by godofredoc** [comment]
@drewroengoogle can we send a PR to move the tree builds back to prod?

**Comment by drewroengoogle** [comment]
Builds were takes out of bringup, and have passed! Closing.
