### ISSUE TITLE
Adding a Carousel Widget

### ISSUE THREAD

**Issue by MaxYablochkin** [flutter/flutter#125980]
### Proposal

Part of: #91605

Adding a new [Carousel](https://m3.material.io/components/carousel/overview) component widget according to Material 3 specifications

<img width="676" alt="unnamed1" src="https://user-images.githubusercontent.com/102767277/235957677-de3c4721-d41f-4ca3-b966-1fabc4ec0814.png">

### Use case

1. Default carousel
2. Carousel with reduced motion settings turned on

https://user-images.githubusercontent.com/102767277/235958580-c5db0309-b173-4d64-9f00-4ac4ed1ad838.mp4

**Comment by huycozy** [comment]
I think it makes sense to have a such widget that meets the M3 specs. Also, I see there are some packages already implemented that you may try using: [carousel_slider](https://pub.dev/packages/carousel_slider), [flutter_carousel_widget](https://pub.dev/packages/flutter_carousel_widget). 

Labeling this issue for more opinions. May be similar: https://github.com/flutter/flutter/issues/25074.

**Comment by HansMuller** [comment]
An M3 compliant carousel would be a welcome contribution as a separate package. Looks like a fun project.

**Comment by fredgrott** [comment]
A question for @HansMuller it would seem that MD3 Carousel is or should be a refactor of say carousel slider since is uses PageView underneath to allow the transforms to be applied to both the current index and current index-1 and current index+1 which then would give the correct animation and other effects implied in the spec of the MD3 Carousel.

Have I got the gist of it as it would be fun from the transforms part especially if one allowed to some other transforms as well...

I will take a shot later this week to implement one re-using carousel slider code, should be some fun indeed.

**Comment by HansMuller** [comment]
The Framework team at Google isn't working on it however @fredgrott might be

**Comment by followthemoney1** [comment]
Please can someone ping me when will be an the example of how this can be implemented right now until the Google team answers there :)

**Comment by fredgrott** [comment]
Okay here is what I know...

Normal page view will not work as the builder above the viewport builder is the wrong builder...What is needed is a new page view that has the right layout builder above the viewport builder.

There are already some carousels that take the approach of redoing page view with the right layout builder. That combined with the right breakpoints and the scrolling recipe from the cookbook example than gives a full MD3 carousel.

**Comment by paadevelopments** [comment]
I had to build this why we wait for a Flutter support. 
![sample](https://github.com/flutter/flutter/assets/68792231/782a155c-ddbe-40d0-88bd-0d73c3b63da0)

Also available on [Pub](https://pub.dev/packages/m3_carousel).

**Comment by fredgrott** [comment]
Good job @paadevelopments

**Comment by RubenCesario** [comment]
According to the Material Carousel homepage (https://m3.material.io/components/carousel/overview) the component is in the "Planned" state. Is it possible to know when developments will begin? Alternatively, can the Flutter team recommend a package to consider as 'official' while waiting for it to be developed internally?

**Comment by mattermoran** [comment]
There are 2 PRs for it. [Part 1](https://github.com/flutter/flutter/pull/148094) was merged recently and [Part 2](https://github.com/flutter/flutter/pull/149775) one should be available soon. 
It was featured in the [Notable Commits](https://github.com/flutter/flutter/issues/121415#issuecomment-2155457043)

**Comment by mattermoran** [comment]
Also you don't have to wait until it's available on stable. In the meanwhile you can copy the widget code ([just one file](https://github.com/flutter/flutter/blob/7e87f1f5bb5cdafa1efa1600d48b9e0a41dc4af1/packages/flutter/lib/src/material/carousel.dart)) into your project and use it. here's the [example](https://github.com/flutter/flutter/blob/7e87f1f5bb5cdafa1efa1600d48b9e0a41dc4af1/examples/api/lib/material/carousel/carousel.0.dart) from second PR.

**Comment by QuncCccccc** [comment]
Since #149775 has landed, I'm closing this issue:)
