### ISSUE TITLE
[macOS] Make mouse state consistent across multiple view controllers

### ISSUE THREAD

**Issue by loic-sharma** [flutter/flutter#125931]
This scenario is broken on macOS:

1. Hover over view `0`
2. Hover over view `1`

The macOS `FlutterViewController` stores the mouse's state in a `_mouseState` property. This state should be shared across multiple view controllers to ensure the correct pointer data is sent to the Flutter engine.

See [`FlutterViewController dispatchMouseEvent:`](https://github.com/flutter/engine/blob/c39dba4da01f8cc52a53e66892c42ebac4657d47/shell/platform/darwin/macos/framework/Source/FlutterViewController.mm#L696)

Follow-up to: https://github.com/flutter/flutter/issues/112205

/cc @dkwingsmt

**Comment by dkwingsmt** [comment]
Fixed by https://github.com/flutter/flutter/pull/127060.
