### ISSUE TITLE
Flutter in app purchase Android product does not lists

### ISSUE THREAD

**Issue by hongwei729** [flutter/flutter#125944]
I have a flutter app which has in app purchase function.
It works fine on ios 
But in android, it doesn't list products
I couldn't see any error log for that
I can see only this log
![Screenshot_1](https://user-images.githubusercontent.com/114906830/235848823-3d20173b-c1d1-4dc0-b3e5-407201269d20.png)

**Comment by darshankawar** [comment]
@hongwei729 
When you open an issue, please use new issue template and fill out requested details so that we'll have enough info to work with. Also, please don't post screenshot of errors as it is not helpful. Please provide `flutter doctor -v`, a complete minimal reproducible code sample along with complete error log in properly formatted text.

**Comment by hongwei729** [comment]
@darshankawar 
Sorry.
I couldn't see the new issue template
Bellow screenshot is my flutter doctor -v log
And there is no error log for the in app purchase
I couldn't see it and just gives blank list for available products 

And this is the code parts to query products

 final ProductDetailsResponse productDetailResponse =
    await _inAppPurchase.queryProductDetails(_kProductIds.toSet());

After run this part, I could see result like bellow:
productDetailResponse.error = null
productDetailResponse.productDetails  is empty


![Screenshot_2](https://user-images.githubusercontent.com/114906830/235989738-7c2f179e-9cbf-4ca8-82fc-fae36be015da.png)

**Comment by darshankawar** [comment]
@hongwei729 
When you start the purchase flow, are you canceling it or are the purchases failing ?
If so, in this case, the productId might be coming back with empty list. See this issue for your reference: https://github.com/flutter/flutter/issues/96775 and check if it resembles your use case or not.

**Comment by darshankawar** [comment]
Thanks for the update. Please take a look at the [plugin example](https://github.com/flutter/packages/tree/main/packages/in_app_purchase/in_app_purchase/example) and see if it helps in your case.
If not, please provide us a complete minimal reproducible code sample that we can directly use to verify the reported behavior.

**Comment by hongwei729** [comment]
@darshankawar 
I have run the example exactly.
But it still gives same result.

![Screenshot_20230505-152346](https://user-images.githubusercontent.com/114906830/236399107-1b9b7763-7149-4dc2-b962-eaa53ee91cd5.jpg)

Here I am attaching the Payment Running Widget class which I used in app.
Actually, it's exactly same with the sample code.
Only difference is I used 
const Set<String> _kIds = {'1week699','1month','1year','1_month','firstmonthpay','month11','1 month pro member'};

[SubscriptionWidget_backup.zip](https://github.com/flutter/flutter/files/11404107/SubscriptionWidget_backup.zip)

**Comment by darshankawar** [comment]
See below links and check if they help in your case:

https://github.com/flutter/flutter/issues/112822
https://stackoverflow.com/questions/68026027/flutter-in-app-purchase-productdetails-is-empty-any-idea-why
