### ISSUE TITLE
Flutter Driver: Missing TextInput functionality.

### ISSUE THREAD

**Issue by JFixby** [flutter/flutter#12599]
Basically I want to write a flutter-driver test where user types in `login` and `password` in TextInput fields and clicks `login button`.

I checked the flutter driver code and it seems like currently this is not possible.

**Comment by Hixie** [comment]
We've since added this functionality.

**Comment by paul-hammant** [comment]
https://www.google.com/search?q=sendKeys+site%3Ahttps%3A%2F%2Fdocs.flutter.io%2Fflutter%2Fflutter_driver%2F yields nothing. It'd be great to know what as added by way of functionality

**Comment by zoechi** [comment]
@paul-hammant can you please create a new issue to request doc update.
This one is long closed.

**Comment by paul-hammant** [comment]
OK
