### ISSUE TITLE
[Impeller] `AiksTest.BlendModeSaveLayer` playground tests fail on vulkan

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#125906]
## description

The following vulkan playground tests fail to render correctly.

- AiksTest.BlendModeSaveLayerScreen
- AiksTest.BlendModeSaveLayerOverlay
- AiksTest.BlendModeSaveLayerDarken
- AiksTest.BlendModeSaveLayerLighten
- AiksTest.BlendModeSaveLayerColorDodge
- AiksTest.BlendModeSaveLayerColorBurn
- AiksTest.BlendModeSaveLayerHardLight
- AiksTest.BlendModeSaveLayerSoftLight
- AiksTest.BlendModeSaveLayerDifference
- AiksTest.BlendModeSaveLayerExclusion
- AiksTest.BlendModeSaveLayerMultiply
- AiksTest.BlendModeSaveLayerHue
- AiksTest.BlendModeSaveLayerSaturation
- AiksTest.BlendModeSaveLayerColor
- AiksTest.BlendModeSaveLayerLuminosity

**OS:** macOS
**variant:** x86_64 debug
**engine hash:** 7d87410a51d5a8c8b080ff14513ef3d89b61f104

## seen result
Black screens are rendered

## expected results

I expect the rendered output to be the same as `Play/AiksTest.BlendModeSaveLayer*/Metal`

**Comment by bdero** [comment]
These (and the checkerboard test) are failing Impeller validation checks on the GLES backend: 
```
[FATAL:flutter/impeller/base/validation.cc(47)] Break on 'ImpellerValidationBreak' to inspect point of failure: EntityPassTarget Flip should never be called for a non-MSAA target.
```

**Comment by bdero** [comment]
The above validation was a GLES-only issue. Fix: https://github.com/flutter/engine/pull/41676

For Vulkan, I also got some unrelated Metal errors related to blit validation (might actually be a MoltenVK bug):
```
-[MTLDebugBlitCommandEncoder internalValidateCopyFromTexture:sourceSlice:sourceLevel:sourceOrigin:sourceSize:toTexture:destinationSlice:destinationLevel:destinationOrigin:options:]:388: failed assertion `Copy From Texture Validation
destinationTexture must not be a framebufferOnly texture.
```

Getting past those, I'm noticing in captures that the backdrop pass isn't receiving the clear color: 
![Screenshot 2023-05-02 at 4 06 51 PM](https://user-images.githubusercontent.com/919017/235804665-0c964db1-5337-40ee-91d3-6e5fb8cdcfc7.png)

**Comment by bdero** [comment]
Confirmed that getting rid of the DrawPaint->Clear color optimization fixes it. Going to revert it for the moment and then reland once I work out a fix for the other platforms.
