### ISSUE TITLE
MultipartRequest is not working correctly on Flutter WEB

### ISSUE THREAD

**Issue by ProfEPT-ricardo-sj** [flutter/flutter#125914]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

```
Stream<List<int>> pseudoFileGenerator(int size) async* {
  List<int> list = [];
  for (int i = 0; i < size; i++) {
    list.add(i);
    if (i % 1024 == 0) {
      print('1kb');
      yield List.from(list);
      list = [];
    }
  }
  if (list.isEmpty == false) {
    yield List.from(list);
  }
}

//--------------------------------------------------------------------------------
sendMultpart(url) async{

      http.MultipartRequest multipartRequest = http.MultipartRequest('POST', url);
     
      http.MultipartFile multipartFile = http.MultipartFile(
        'campoField',
        pseudoFileGenerator(size),
        size,
        filename: '',
        contentType: mimeType,
      );

      multipartRequest.files.add(
        multipartFile,
      );

      await multipartRequest.send();

}
```

### Expected results

when i call **sendMultpart(...)**  on flutter for windows all code is done right: A chunk of bytes is load in memory and than sent to server, than another chunk of bytes is read and sent to server until done!

The problem is on **WEB** version of flutter. when I run this code on **flutter web** all the bytes is first load on memory and only after that the information is sent to server.

With this behavior my web code version need first load all file on memory to after that send to server. This is a very wrong behavior.

I expected that the web version work in same way of the windows version.

### Actual results

The result of this is that I lose the chance to put my project on flutter in the company I work.
Now we have to migrate to another tecnology.

### Code sample

Stream<List<int>> pseudoFileGenerator(int size) async* {
  List<int> list = [];
  for (int i = 0; i < size; i++) {
    list.add(i);
    if (i % 1024 == 0) {
      print('1kb');
      yield List.from(list);
      list = [];
    }
  }
  if (list.isEmpty == false) {
    yield List.from(list);
  }
}

//--------------------------------------------------------------------------------
sendMultpart(url) async{

      http.MultipartRequest multipartRequest = http.MultipartRequest('POST', url);
     
      http.MultipartFile multipartFile = http.MultipartFile(
        'campoField',
        pseudoFileGenerator(size),
        size,
        filename: '',
        contentType: mimeType,
      );

      multipartRequest.files.add(
        multipartFile,
      );

      await multipartRequest.send();

}

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.12, on Microsoft Windows [versÆo 10.0.22621.1555], locale pt-BR)
[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)
[X] Android toolchain - develop for Android devices
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.4)
[√] Android Studio (version 2022.1)
[√] VS Code (version 1.77.3)
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 2 categories.
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @ProfEPT-ricardo-sj, the http package lives in a different repo https://github.com/dart-lang/http/issues.

Any issues you face when using the package should be reported on their repo. 

Closing from here. If you are redirected here after filing the issue there, kindly leave a comment below and I will reopen this issue.

Thank you
