### ISSUE TITLE
Target `mac_android_aot_engine` is using `xcode_12a7209`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#125923]
See https://luci-milo.appspot.com/ui/p/flutter/builders/try/Linux%20mac_android_aot_engine/351/overview
Subbuild: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Engine%20Drone/751650/overview

```
Executing command [
  '/Volumes/Work/s/w/ir/cache/osx_sdk/xcode_12a7209/mac_toolchain',
  'install',
  '-kind',
  'ios',
  '-xcode-version',
  '12a7209',
  '-output-dir',
  '/Volumes/Work/s/w/ir/cache/osx_sdk/xcode_12a7209/XCode.app',
  '-cipd-package-prefix',
  'flutter_internal/ios/xcode',
  '-with-runtime=True',
]
```

I guess the target should use consistent xcode as other targets in Engine. If so, we should add the xcode property to the config file:
```
"properties": {
                "$flutter/osx_sdk": {
                    "sdk_version": "14e222b"
                }
            },
```

**Comment by godofredoc** [comment]
@XilaiZhang is this the build that got the xcode version hardcoded for code signing to work?

**Comment by keyonghan** [comment]
Yeah, the version was pinned in https://github.com/flutter/engine/pull/41518. Confirmed the recent builds are using the correct xcode. Closing.
