### ISSUE TITLE
Devicelab linux 2 causes test flakiness due to device not found

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#125996]
Both flakes in https://github.com/flutter/flutter/issues/125957 happened on linux2
One flake in https://github.com/flutter/flutter/issues/125955 happened on linux2

From recent runs, this test bed seems stable. Creating this bug to track in case the flake still happens.

**Comment by keyonghan** [comment]
Another flaky bug caused by linux 2: https://github.com/flutter/flutter/issues/127469

**Comment by keyonghan** [comment]
Flake still repros on this test bed: https://github.com/flutter/flutter/issues/129262

**Comment by keyonghan** [comment]
@kentnguyen99 Could you help check the state of this testbed? High chance the device is unhealthy, or the cable is loose, etc.

**Comment by kentnguyen99** [comment]
@keyonghan Will check on this and get back to you soon.

**Comment by ricardoamador** [comment]
I am going to remove this from the ticket queue as it is not a P0 or P1.

**Comment by ricardoamador** [comment]
Oh sorry I see. This is a devicelab issue.

**Comment by kentnguyen99** [comment]
@keyonghan I ran "adb devices" command and showed device attached to machine Linux-2.
flutter@flutter-devicelab-linux-2:~$ adb devices
List of devices attached
ZY223CXXGL	device

**Comment by yusuf-goog** [comment]
@kentnguyen99 can you please replace the usb cable from the host to the phone on this testbed. We would like to determine if that is causing some dropped connections to the phone.

**Comment by kentnguyen99** [comment]
@yusuf-goog Swapping different USB cable is done on linux-2 is done.

**Comment by yusuf-goog** [comment]
obsolete issue, closing
