### ISSUE TITLE
[Desktop] Cannot close app if using `dart:ui` directly

### ISSUE THREAD

**Issue by loic-sharma** [flutter/flutter#126033]
### Problem

On the `master` channel, "raw" `dart:ui` apps without widgets cannot be closed using the `x` in the title bar:

* **Windows** - The window remains open
* **macOS** - The window closes, however, both the app and `flutter run` do not exit. On `stable`, the window, app, and `flutter run` all exit.
* **Linux** - First close attempt does nothing, second close attempt prints the error `** (layers:754): WARNING **: 10:07:23.518: Error returned from System.requestAppExit: Requested method is not implemented` and the app exits.

### Background

https://github.com/flutter/flutter/issues/30735 allowed Flutter apps to listen to application exits using the `System.exitApplication` handler registered by `ServicesBinding`. This works as expected for Flutter apps that have widgets.

However, "raw" Flutter apps that use `dart:ui` directly without widgets don't register a `ServicesBinding`, and the `System.exitApplication` handler is never registered. As a result, the embedder's application exit messages aren't processed and the app does not exit.

### Reproduction

1. Switch to the master channel
1. Run the `hello_world` raw layer example on Windows or macOS:
    1. cd `./flutter/examples/layers`
    2. If on Windows: `flutter create --platforms=windows .`
    3. If on Linux: `flutter create --platforms=linux .`
    4. `flutter run ./raw/hello_world.dart`
2. Close the app using the `x` button on the app's title bar

The app should shutdown, however, it stays open.

/cc @yaakovschectman @gspencergoog

**Comment by loic-sharma** [comment]
This is the first commit that reproduces this bug: https://github.com/flutter/flutter/commit/323a2d574aacdedd25c820a9ffd011e687d4210b

It is an engine roll that contains this change: https://github.com/flutter/engine/pull/40493

**Comment by gspencergoog** [comment]
@robert-ancell @jpnurmi  Nevermind, I think I've got a solution for Linux already.

**Comment by yaakovschectman** [comment]
Should be solved for Windows now

**Comment by gspencergoog** [comment]
Should also be resolved for Linux and macOS.
