### ISSUE TITLE
[pigeon] re-enable "treat warnings as errors"

### ISSUE THREAD

**Issue by hellohuanlin** [flutter/flutter#126006]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

We enabled "treat warnings as errors" for Swift pigeon's unit test [in this PR](https://github.com/flutter/packages/pull/3889), which got reverted, because our recent migration to Xcode 14.3 that introduced [a new warning](https://forums.swift.org/t/swift-5-8-new-warnings-for-any-collections/63484) about type inference for "Any collection". 

### Background

The original diagnosis was introduced in https://github.com/apple/swift/commit/1d21b4e, which checks against type inference for heterogeneous collection: 

```
let foo = ["Hello", 999] // (1)
// Error: Heterogeneous collection literal could only be inferred to '[Any]'; add explicit type annotation if this is intentional. 

let bar = [nil] // (2)
// Error: Heterogeneous collection literal could only be inferred to '[Any?]'; add explicit type annotation if this is intentional. 
```

The fix is simply to add type annotation: 
```
let foo: [Any] = ["Hello", 999] // (1)
let bar: [Any?] = [nil] // (2)
```

This is reasonable diagnosis, since the heterogenous collection loses the concrete type info for the elements, so we need to explicitly indicate this is indeed what we want. 

Though for (2), it could use better error message - it's not exactly a "heterogeneous" collection. But anyways, this diagnosis is basically saying, **if a collection can only be inferred to [Any] or [Any?] (either heterogeneous collection or [nil]), you have to explicitly tell compiler this is indeed what you want**. 

### Changes in Xcode 14.3 / Swift 5.8

Before Swift 5.8, when passing a literal into a function, the type annotation requirement is considered as satisfied: 

```
func takeFoo(_ foo: [Any?]) {
  print(foo)
}
takeFoo([nil])
takeFoo(["Hello", 3])
```

This was fine, because the argument explicitly indicate that we want `[Any?]` type, hence no warnings or errors. However, **in Swift 5.8, the above will trigger the same diagnosis (tho as a warning not an error).** 

```
NullableReturnsTests.swift:43:53: error: heterogeneous collection literal could only be inferred to '[Any?]'; add explicit type annotation if this is intentional
    let inputEncoded = binaryMessenger.codec.encode([nil])
                                                    ^~~~~
                                                          as [Any?]
```

This change seems to be [introduced by mistake](https://forums.swift.org/t/swift-5-8-new-warnings-for-any-collections/63484/16), and should be reverted in [Swift 5.9](https://github.com/apple/swift/issues/63982#issuecomment-1497812107), so possibly Xcode `14.3.1` or `14.4`. 

### Proposal

The fix should be easy: 
```
takeFoo([nil] as [Any?])
```
or:  
```
let foo: [Any?] = [nil]
takeFoo(foo)
```

**Comment by stuartmorgan** [comment]
> We enabled "treat warnings as errors" for Swift pigeon https://github.com/flutter/packages/pull/3889, which got reverted

You enable warnings as errors *for the unit test code itself* in that PR. The plugin, which contains the generated code, already had that setting enabled, and wasn't reverted.

**Comment by hellohuanlin** [comment]
> You enable warnings as errors for the unit test code itself in that PR. 

updated. thx for clarification.
