### ISSUE TITLE
Flaky FlutterChannelsTest tests

### ISSUE THREAD

**Issue by flar** [flutter/flutter#126084]
I'm seeing rollers fail on the `Linux Mac Unopt` task with various failures in the FlutterChannelsTest. For example: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20mac_unopt/946/overview

The run with the most failures included the following failures, but other runs on the same bot (it does 3 retries) had only a subset of these failures:

```
Failing tests:
	-[FlutterChannelsTest testBasicMessageChannelInvokeHandlerAfterChannelReleased]
	-[FlutterChannelsTest testBasicMessageChannelTaskQueue]
	-[FlutterChannelsTest testEventChannelTaskQueue]
	-[FlutterChannelsTest testMethodChannelInvokeHandlerAfterChannelReleased]
	-[FlutterChannelsTest testMethodChannelTaskQueue]
```

**Comment by flar** [comment]
See also https://github.com/flutter/flutter/issues/126013 reported by @dnfield

**Comment by flar** [comment]
Looking through the logs for "successful" runs of this task, it looks like these tests are usually run more than once, so this is a sever flake that is wasting automated testing resources. See https://ci.chromium.org/p/flutter/builders/try/Linux%20mac_unopt

**Comment by dnfield** [comment]
This is a duplicate of #126013

**Comment by jmagman** [comment]
@flar I merged https://github.com/flutter/engine/pull/41747, please reopen https://github.com/flutter/flutter/issues/126013 if you see this flaking again.
