### ISSUE TITLE
CupertinoSliverNavigationBar should snap between large and middle title

### ISSUE THREAD

**Issue by MitchellGoodwin** [flutter/flutter#126028]
### Use case

On iOS 16, when a page is partially scrolled so either the large or middle title is partially shown, the page will snap to fully show one or the other. So if a scroll goes past 50% of the way to the next state, it will snap to finish. But if the scroll stops before the 50% point, it will snap back to the previous point.

### Proposal

This is how it currently works on iOS 16:

https://user-images.githubusercontent.com/58190796/236073966-8d9129f0-b11d-43f6-b465-a23cdd800838.mov

Currently in Cupertino it will just stop wherever it was left in the scroll. We should match the behavior on iOS to not create any jarring differences.

Ideally the logic will be easily shareable with other nav bars, for possible adaptive logic between them.

**Comment by Piinks** [comment]
This is something @HansMuller worked on by combining the newer atomic slivers. There is some sample code demonstrating this auto-scroll behavior, snapping it into one state or the other. Integrating it into CupertinoSliverNavigationBar should resolve this:

https://api.flutter.dev/flutter/widgets/ScrollEndNotification-class.html#widgets.ScrollEndNotification.1
