### ISSUE TITLE
flutter -d chrome fails with "Error: Expected a value of type 'FontCollectionNamespace', but got one of type 'Null'"

### ISSUE THREAD

**Issue by yvs2014** [flutter/flutter#126073]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

flutter run -d chrome

### Expected results

work as it was before flutter update

### Actual results

Error: Expected a value of type 'FontCollectionNamespace', but got one of type 'Null'
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 288:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 121:3   castError
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/types.dart 245:34   as
dart-sdk/lib/_internal/js_shared/lib/js_util_patch.dart 77:5                  getProperty
lib/_engine/engine/canvaskit/canvaskit_api.dart 143:40                        CanvasKitExtension.get$35FontCollection
lib/_engine/engine/canvaskit/fonts.dart 49:34                                 [_registerWithFontProvider]
lib/_engine/engine/canvaskit/fonts.dart 160:5                                 registerDownloadedFonts
lib/_engine/engine/initialization.dart 201:27                                 initializeEngineServices
...

### Code sample

<details><summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(context) => const MaterialApp(home: Scaffold(body: Text('algo')));
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console

[✓] Flutter (Channel beta, 3.10.0-1.5.pre, on Ubuntu 23.04 6.2.0-20-generic, locale C.UTF-8)
    • Flutter version 3.10.0-1.5.pre on channel beta at /home/yvs/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b1c77b7ed3 (2 days ago), 2023-05-02 21:11:36 -0600
    • Engine revision 50e509c2bd
    • Dart version 3.0.0 (build 3.0.0-417.4.beta)
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /home/yvs/Android/Sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /snap/android-studio/125/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.3)
    • Android Studio at /snap/android-studio/125/android-studio
    • Flutter plugin version 71.0.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio
    • Android Studio at /home/yvs/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 23.04 6.2.0-20-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.5672.63

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
@yvs2014 Thanks for the report. A similar issue was fixed recently https://github.com/flutter/flutter/issues/123737.
So can you switch to latest master and try again to see if you still get the same error or not ? Also try to clear your browser cache as stated in the linked issue and try again.

**Comment by yvs2014** [comment]
1) clearing cache (manually and via chrome menu) doesn't help

2) switching to the latest master 3.11.0-1.0.pre.65:  it works
(would be nice to get it in beta)

Thanks for the hints

**Comment by darshankawar** [comment]
Good to know. Since it works on latest master, I'll go ahead and close this.
The fix will be in beta per https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#beta
