### ISSUE TITLE
Flutter plugins with native dependencies using in sample project or nested plugin - not working 

### ISSUE THREAD

**Issue by Natraj1765** [flutter/flutter#126043]
### Is there an existing issue for this?

- [x] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [x] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1.Create a new flutter plugin with native dependencies and push it to pub dev
2.Create another flutter plugin which should include the previous pushed plugin ex my_plugin : 0.0.1 include inside of pubspec.yaml
3.While using like above the native dependencies are not get inside of nested plugin.
4.The point is when we push the plugin with native dependencies it won't produce the dependencies in the sample project and as well nested plugins. Ex - Native dependencies androidx which is include in the first plugin and if we try to use that first plugin in sample project or nested plugin it not taking dependencies.

 

### Expected results

1.Expected result is the dependencies should be take in sample project and nested plugin.
2.Because we developing the plugin globally it have the dependencies so end user when we use that it should work. 

### Actual results

1.Its not produce the dependencies.

### Code sample

    api "androidx.camera:camera-core:${camerax_version}"
    api "androidx.camera:camera-camera2:${camerax_version}"
    api "androidx.camera:camera-lifecycle:${camerax_version}"
    api "androidx.camera:camera-view:${camerax_version}"

### Logs

src/main/kotlin/com/sample/plugin/sample_plugin_flutter/CustomViewClass.kt: (17, 38): Unresolved reference: camera

### Flutter Doctor output

<img width="682" alt="Screenshot 2023-05-04 at 11 24 55 AM" src="https://user-images.githubusercontent.com/91648574/236122338-8112cdb8-1a70-4412-a0fa-029d6bc57cf5.png">

**Comment by huycozy** [comment]
Can you please be more specific on the steps by pseudo-naming the components inside plugins? 

For eg:
1. Create `pluginA` with `cameraX` dependencies then publish it to pub.dev
2. Create `pluginB` that uses `pluginA` as a dependency
3. Native dependencies (`cameraX`) are not found on `pluginB`?
4. Native dependencies (`cameraX`) can't be used on `pluginA` example project?

Also, because the plugins are public (published on pub.dev), it would be appreciated if you could provide the repositories so that we may verify the issue properly. Thanks!

**Comment by Natraj1765** [comment]
1.Using android hostview from flutter
2.Added camerax component in android part that view return to flutter with the help of hosting androidview.
3.For this scenario we defined the camera dependencies inside of flutter plugin android build.gradle
4.While using this plugin in sample project throws error like un resolved camera reference
error message - src/main/kotlin/com/sample/plugin/sample_plugin_flutter/CustomViewClass.kt: (17, 38): Unresolved reference: camera
Thanks!

**Comment by huycozy** [comment]
Can you provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this?

Please also retry on the latest stable/master channel to see if the issue is fixed or not. Thanks!

**Comment by Natraj1765** [comment]
Hi @huycozy, now we can able to use native dependencies in sample project. But in plugin class we have jar file dependencies that can't able to use in sample project. 
Steps:
1.Create plugin with jar(any third party) file and add camera dependencies.
2.Create flutter sample project and include that created plugin (locally or pub.dev)
3.Now in sample project native code i can able to use the camera dependencies but can't able to access jar file classes.

**Comment by huycozy** [comment]
In order to address the issue properly, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Thanks!
