### ISSUE TITLE
Xcode roll increased the size of app_framework_uncompressed_bytes

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#126004]
On an unrelated commit that just marked a test `bringup: true`, iOS and macOS uncompressed and release size regressed due to an increase in `app_framework_uncompressed_bytes`:

https://flutter-flutter-perf.skia.org/e/?begin=1682634606&end=1683136208&keys=Xb6ca173484be41194ec56dc0abcbc1e1&requestType=0&selected=commit%3D34660%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253Dnone%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253Dapp_framework_uncompressed_bytes%252Ctest%253Dhello_world_macos__compile%252C&xbaroffset=34658

Before: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_benchmark%20hello_world_macos__compile/1525/overview
```
{
      "dependency": "xcode",
      "version": "14c18"
}
```

After: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_benchmark%20hello_world_macos__compile/1532/overview
```
{
      "dependency": "xcode",
      "version": "14e222b"
}
```

cc @jmagman

**Comment by jmagman** [comment]
I'm not sure how `app_framework_uncompressed_bytes` would have been impacted by an Xcode bump, it's the AOT snapshot.  You'd think that would happen in a dart -> engine roll...

**Comment by zanderso** [comment]
For reference, this value is computed here https://github.com/flutter/flutter/blob/master/dev/devicelab/lib/tasks/perf_tests.dart#L1557.

I wonder if the new XCode version is populating that directory with some extra stuff?

**Comment by jmagman** [comment]
Xcode bump at https://github.com/flutter/flutter/pull/125716.


> I wonder if the new XCode version is populating that directory with some extra stuff?

I don't think so since that directory is entirely constructed by `flutter assemble`.  

https://github.com/flutter/flutter/blob/f704c68924149467dcbfb0d325b86c60e383b669/packages/flutter_tools/lib/src/build_system/targets/ios.dart#L490
https://github.com/flutter/flutter/blob/f704c68924149467dcbfb0d325b86c60e383b669/packages/flutter_tools/lib/src/build_system/targets/ios.dart#L516-L542

@cyanglaz is going to run it locally on both Xcode 14.2 and 14.3 to confirm that's the cause of the regression, and investigate.

**Comment by cyanglaz** [comment]
Local result Xcode 14.2: 

```
  "data": {
    **"app_framework_uncompressed_bytes": 2935520,**
    "flutter_framework_uncompressed_bytes": 26489136,
    "release_initial_compile_millis": 57756,
    "release_size_bytes": 15644604,
    "release_full_compile_millis": 24617,
    "debug_initial_compile_millis": 20709,
    "debug_full_compile_millis": 20706,
    "debug_second_compile_millis": 7716,
    "debug_compile_after_edit_millis": 9287
  },
```

**Comment by cyanglaz** [comment]
Local result Xcode 14.3

```
Task result:
{
  "success": true,
  "data": {
    "app_framework_uncompressed_bytes": 2935520,
    "flutter_framework_uncompressed_bytes": 26489136,
    "release_initial_compile_millis": 26382,
    "release_size_bytes": 15644602,
    "release_full_compile_millis": 24398,
    "debug_initial_compile_millis": 20858,
    "debug_full_compile_millis": 20865,
    "debug_second_compile_millis": 7701,
    "debug_compile_after_edit_millis": 9092
  },
  "detailFiles": [],
  "benchmarkScoreKeys": [
    "app_framework_uncompressed_bytes",
    "flutter_framework_uncompressed_bytes",
    "release_initial_compile_millis",
    "release_size_bytes",
    "release_full_compile_millis",
    "debug_initial_compile_millis",
    "debug_full_compile_millis",
    "debug_second_compile_millis",
    "debug_compile_after_edit_millis"
  ],
  "reason": "success"
}
```

**Comment by cyanglaz** [comment]
local result Xcode 14.3:
```
"data": {
    "app_framework_uncompressed_bytes": 3100640,
    "flutter_framework_uncompressed_bytes": 26489136,
    "release_initial_compile_millis": 38842,
    "release_size_bytes": 15693806,
    "release_full_compile_millis": 24910,
    "debug_initial_compile_millis": 20370,
    "debug_full_compile_millis": 20513,
    "debug_second_compile_millis": 7643,
    "debug_compile_after_edit_millis": 9183
  },
```

**Comment by cyanglaz** [comment]
`app_framework_uncompressed_bytes` does regressed because of xcode upgrade.

**Comment by jason-simmons** [comment]
There was a size increase in the `snapshot_assembly.o` object compiled from the `snapshot_assembly.S` source generated by Dart's `gen_snapshot`.

With Xcode 14.3 `snapshot_assembly.o` now includes the `__eh_frame` stack unwinding section.

**Comment by zanderso** [comment]
There's also a 200KB compressed increase in flutter gallery on iOS:

https://flutter-flutter-perf.skia.org/e/?begin=1682925020&end=1683212749&queries=sub_result%3Drelease_size_bytes%26test%3Dflutter_gallery_ios__compile&requestType=0&selected=commit%3D34663%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253Drelease_size_bytes%252Ctest%253Dflutter_gallery_ios__compile%252C.

So the increase scales up with the size of the app. Marking this P2 since I suspect this may set off alarm bells in the internal roll.

**Comment by zanderso** [comment]
From chat:

> @mraleph: on https://dart-review.googlesource.com/c/sdk/+/241282
> In general we don't need these sections but if you have native tool like Instruments profiler or crash handler then it most likely needs these to properly unwind things.

**Comment by mraleph** [comment]
The change has rolled and the size dropped down to the previous value:

https://flutter-flutter-perf.skia.org/e/?begin=1682634606&end=1683403222&keys=Xb6ca173484be41194ec56dc0abcbc1e1&requestType=0&selected=commit%3D34660%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253Dnone%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253Dapp_framework_uncompressed_bytes%252Ctest%253Dhello_world_macos__compile%252C&xbaroffset=34658
