### ISSUE TITLE
[Impeller] PaintingStyle.stroke is unimplemented for Text.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#126010]
b/279220093

**Comment by ClemPalf** [comment]
Hi,

Any progress on the issue ?
Also, if anyone has a quick workaround I am all ears!

Regards,

**Comment by UlasAkgun** [comment]
+1 to this, thank you @jonahwilliams for stepping into this issue!

**Comment by UlasAkgun** [comment]
+1 to this, thank you @jonahwilliams for stepping into fixing this issue!

**Comment by yalong0521** [comment]
Is there any latest progress on this issue?

**Comment by serbixote** [comment]
any update on this? 🙏🏼
