### ISSUE TITLE
[Impeller] Glyphs should be cached with applied skew/rotate transformations

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#126099]
This will allow us to match Skia fidelity. Additionally, we may be able to decrease the padding and always use NN sampling when drawing glyphs.

**Comment by chinmaygarde** [comment]
Its good to document Skia behavior but let's attempt this once we have cases where our approach keels over.

**Comment by chinmaygarde** [comment]
Jonah: This is less of a priority now that we switch sampling modes to linear in the presence of a transformation. This is still not the best we can do but good enough.

**Comment by jonahwilliams** [comment]
We're not going to do this
