### ISSUE TITLE
Proposal: incorporate `flutter_reactive_widget` into Flutter

### ISSUE THREAD

**Issue by lukehutch** [flutter/flutter#126181]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

State management in Flutter is extremely complex, and without question, figuring out how to handle state correctly is the steepest part of the learning curve for new users. I initially gave up on Flutter when I saw the ugly state management boilerplate I needed to use every time I wanted a part of the UI to be reactive to a state change.

I developed https://github.com/lukehutch/flutter_reactive_widget in response to this. This is a significantly simpler approach to state management and reactivity than other mechanisms.

### Proposal

I propose adding `flutter_reactive_widget` to Flutter. This will make the learning and use of Flutter accessible to a wider audience, out of the box.

**Comment by iapicca** [comment]
I strongly oppose this,
we can debate all day long 
if it's the right decision or not for flutter to be agnostic regarding state management, DI etc
personally I like things as they are, but that's just my opinion
if the team will decide to adopt an "external" state management there are many strong candidates
- [riverpod](https://pub.dev/packages/riverpod)
- [bloc](https://pub.dev/packages/bloc)
- [mobx](https://pub.dev/packages/mobx)
and the list goes on...

[flutter_reactive_widget](https://pub.dev/packages/flutter_reactive_widget) seems to be just syntactic sugar around [ValueNotifier](https://api.flutter.dev/flutter/foundation/ValueNotifier-class.html)
with zero test coverage and **huge** red flags like global variables
```dart
final _currReactiveWidgetState = <_ReactiveWidgetState>[];
```

...please don't

**Comment by lukehutch** [comment]
OK.
