### ISSUE TITLE
[go_router] Match error found during build phase, Exception: no routes for location

### ISSUE THREAD

**Issue by Mohdx** [flutter/flutter#126123]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I'm frustrated with go_router error "Match error found during build phase, Exception: no routes for location: cart".

I'm using **FirebaseMessaging** _onBackgroundMessage_ method, to navigate to specific route using [go_router](https://pub.dev/packages/go_router) package.
### It works fine when the app is in the foreground or background but not when the app is terminated

Steps I've been doing:

1. AppRoute calss
```
class AppRoute {
  static const String home = 'home';
  static const String logIn = 'log_in';
  static const String cart = 'cart';

  static GoRouter routes = GoRouter(
    initialLocation: '/',
    debugLogDiagnostics: kDebugMode,
    errorBuilder: (context, state) => ErrorScreen('${state.error}'),
    // changes on the listenable will cause the router to refresh it's route
    refreshListenable: Global.appSettings,
    routes: <GoRoute>[
      GoRoute(
        name: home,
        path: '/',
        pageBuilder: (BuildContext context, GoRouterState state) {
          return MaterialPage(
            key: state.pageKey,
            child: Structure(query: state.queryParameters),
          );
        },
        routes: <GoRoute>[
          GoRoute(
            path: cart,
            // redirect method is called before the app navigate to a new page
            redirect: (BuildContext context, GoRouterState state) {
              return AuthGuard.isRedirect(state, logIn);
            },
            builder: (BuildContext context, GoRouterState state) {
              return const CartView();
            },
          ),
        ],
      ),
      GoRoute(
        path: '/$logIn',
        name: '/$logIn',
        builder: (BuildContext context, GoRouterState state) {
          return LogIn(query: state.queryParameters);
        },
      ),
    ],
  );

  static Future<GoRouter> get() async => routes;
}
```

2. in main.dart
```
Future<void> main() async {
  SystemChromeService.inject();

  await HiveInjector.inject();

  // Load the user's preferred theme while the splash screen is displayed.
  await Global.appSettings.loadSettings();

  ErrorWidget.builder = (FlutterErrorDetails err) => ErrorScreen('$err');

  FirebaseTool.getFirebaseToken().whenComplete(
    () => FirebaseTool.setFirebaseTopics(),
  );

  // App listens to the [appSettings] for changes, then passes it further
  // down to the widget tree.
  runApp(const MyApp());
}

```

3. FirebaseTool calss
```
class FirebaseTool {
  static Future<void> getFirebaseToken() async {
    final FirebaseModel firebase = HiveInjector.getFire();

    try {
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );
      final FirebaseMessaging firebaseMessaging = FirebaseMessaging.instance;
      await firebaseMessaging.requestPermission();

      firebase.token = (await firebaseMessaging.getToken() ?? '');
      firebase.save();
    } catch (e) {
      Helper.log('firebase initialize error: $e');
    }
    Helper.log('firebaseToken: ${firebase.token}');
  }

  static Future<void> setFirebaseTopics() async {
    final FirebaseModel firebase = HiveInjector.getFire();

    if (!firebase.topics.contains('all')) {
      await FirebaseMessaging.instance.subscribeToTopic('all');
      firebase.topics.add('all');
    }

    firebase.save();

    Helper.log('firebaseTopics: ${firebase.topics}');

    _notificationListener();
  }

  static void _notificationListener() {
    FirebaseMessaging.onBackgroundMessage(_backgroundMessage);
    FirebaseMessaging.onMessage.listen((m) => _backgroundMessage(m));
    FirebaseMessaging.onMessageOpenedApp.listen((m) => _backgroundMessage(m));
  }

  static Future<void> _backgroundMessage(RemoteMessage message) async {
    final String route = message.data['route'].toString();
    final String routeName = route.split('/').first;

    Helper.log('route name: $route');
    Helper.log('message body: ${message.notification?.body}');

    AppRoute.get().then((router) {
      switch (routeName.toLowerCase()) {
        case 'cart':
          return router.go('/${AppRoute.cart}');
      }
    });
  }
}
```

### Expected results

Expected result to work the same when the app is in foreground or background and also terminated.

### Actual results

 Match error found during build phase, Exception: no routes for location: cart (only if the app is terminated)

**Comment by darshankawar** [comment]
Thanks for the report @Mohdx 


> I'm frustrated with go_router error "Match error found during build phase, Exception: no routes for location: cart".

Can you take a look at [this](https://github.com/flutter/flutter/issues/118323) similar issue and [solution](https://github.com/flutter/flutter/issues/118323#issuecomment-1414477607) and see if it helps in your case ?



> I'm using **FirebaseMessaging** _onBackgroundMessage_ method, to navigate to specific route using [go_router](https://pub.dev/packages/go_router) package.

`firebase_messaging` is a third party plugin. Can you confirm if you still get the same error without using this plugin and only using `go_router` ? If so, we'll need updated code sample without firebase_messaging and any other third party package code implementation (only including go_router).

**Comment by Mohdx** [comment]
Dear [@darshankawar]([darshankawar](https://github.com/darshankawar)) 
Thanks a lot for your suggestion. 
I've tried to redirect to `/cart` from terminated state, using `go_router` only and it works!

I'll look further into `firebase_messaging` _onBackgroundMessage_ method.
if you have any advice redirecting to specific route from terminated state on firebase notification `onMessageOpenedApp` click or on _onBackgroundMessage_, please let me know

**Comment by darshankawar** [comment]
Good to know it works with `go_router` properly. 
If you think this is an issue with `firebase_messaging`, you'll need to report it in dedicated repo: https://github.com/firebase/flutterfire/issues

I'll close this as resolved based on your above comment. If you disagree, write in comments and I'll reopen it.
