### ISSUE TITLE
Anomalous method signatures in L10N-generated classes

### ISSUE THREAD

**Issue by zmeggyesi** [flutter/flutter#126145]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I have a Flutter build running in Kubernetes via Gitlab CI. The pod auto-upgrades itself on each run to the latest version:
```
$ flutter --version
Flutter 3.7.12 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d9e56e694 (2 weeks ago) • 2023-04-17 21:47:46 -0400
Engine • revision 1a65d409c7
Tools • Dart 2.19.6 • DevTools 2.20.1
```

As of today, the `AppLocalization` classes generated on the pod contain function signatures such as 
```
/// login failed toast
///
/// In en, this message translates to:
/// **'Login failed!\n{message}'**
String loginFailed(String message, Object Botschaft);
```
which is quite obviously invalid, and causes the build to fail due to signature mismatches between the generated file and how the rest of the code calls it. On Windows, MacOS, and other Linux installations, the generated files contain the correct method signatures:
```
/// login failed toast
///
/// In en, this message translates to:
/// **'Login failed!\n{message}'**
String loginFailed(String message);
```

I have searched the Flutter SDK repo, as well as _all of GitHub_, and found no instances of this, but I can think of no other source for this than the localizations package.

### Expected results

The generated localization files should contain method signatures such as 
```
/// login failed toast
///
/// In en, this message translates to:
/// **'Login failed!\n{message}'**
String loginFailed(String message);
```

### Actual results

The generated localization files **actually** contain method signatures such as 
```
/// login failed toast
///
/// In en, this message translates to:
/// **'Login failed!\n{message}'**
String loginFailed(String message, Object Botschaft);
```

### Code sample

<details><summary>Code sample</summary>

Likely not applicable

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

Verbose logs at 11 MiB, uploaded instead of inlining.
[raw.txt](https://github.com/flutter/flutter/files/11404910/raw.txt)

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Flutter 3.7.12 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d9e56e694 (2 weeks ago) • 2023-04-17 21:47:46 -0400
Engine • revision 1a65d409c7
Tools • Dart 2.19.6 • DevTools 2.20.1
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.12, on Ubuntu 22.04.1 LTS 5.10.162+, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
    ✗ CMake is required for Linux development.
      It is likely available from your distribution (e.g.: apt install cmake), or can be downloaded from https://cmake.org/download/
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
    ✗ pkg-config is required for Linux development.
      It is likely available from your distribution (e.g.: apt install pkg-config), or can be downloaded from https://www.freedesktop.org/wiki/Software/pkg-config/
[!] Android Studio (not installed)
[✓] Connected device (1 available)
[✓] HTTP Host Availability
! Doctor found issues in 4 categories.
```

</details>

**Comment by huycozy** [comment]
>As of today, the AppLocalization classes generated on the pod contain function signatures such as

Hi @zmeggyesi 
What is your arb string? Can you please provide a minimal sample code that is running on that pod?

**Comment by huycozy** [comment]
As I can see from you Dockerfile, you are pulling `flutter_linux_3.7.1-stable.tar.xz`. Can you try using the latest Flutter stable or master channel to see if it works?  (stable `3.7.12` and master `3.11.0.x`)

Also, you you can ssh to that pod, let's try generating localization string manually with command: `flutter gen-l10n` and then check if the result can change or not.

**Comment by zmeggyesi** [comment]
@huycozy I pointed it out in the initial report that I upgrade flutter on each run. 
```
$ flutter --version
Flutter 3.7.12 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d9e56e694 (2 weeks ago) • 2023-04-17 21:47:46 -0400
Engine • revision 1a65d409c7
Tools • Dart 2.19.6 • DevTools 2.20.1
```
is the version that generated the anomalous signatures.

**Comment by huycozy** [comment]
I also can not replicate this on my local machine (macOS). It seems to create a local Kubernetes environment takes more time, could you please provide `steps to reproduce` this issue? The steps could be with Gitlab CI or local Docker (I'm not sure if it can be reproduced, but worth a try) would be appreciated. Thank you!
