### ISSUE TITLE
Material sheet shadows not rendering properly in ListView

### ISSUE THREAD

**Issue by dguralnick** [flutter/flutter#12618]
## Steps to Reproduce

1.  Run the app below.
2.  See that the [Material](https://docs.flutter.io/flutter/material/Material-class.html) sheet shadows render properly.
3.  Scroll and see that the shadows disappear.

I noticed that the shadows *do* properly render if you do one of the following:
- Comment out both the subtitle and trailing elements of the ListTile - having either one causes the issue, but with both gone the shadows render.
- Wrap each Sheet with bottom padding instead of inserting it between elements.

Also interesting, if you fling the list, it looks like the elements coming on screen at the edge of the list *do* have the shadow visible, but it quickly disappears when they get painted again.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Shadow bug reproduction',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
        scaffoldBackgroundColor: Colors.grey.shade100,
      ),
      home: new MyHomePage(),
    );
  }
}

const padding = const Padding(padding: const EdgeInsets.only(top: 20.0));

class MyHomePage extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text('Shadow behavior repro'),
      ),
      body: new Column(
        children: [
          new Expanded(
            child: new ListView(
              children: new List.filled(20, new Sheet())
                  .expand((sheet) => [padding, sheet]).toList(),
            ),
          ),
        ],
      ),
    );
  }
}

class Sheet extends StatelessWidget {
  @override
  Widget build(BuildContext context) => new Material(
      elevation: 2.0,
      child: new ListTile(
        title: const Text('List Tile Title'),
        // Note commenting out both subtitle and trailing
        // 'fixes' the shadow issue - they render properly w/ scrolling.
        subtitle: const Text('List Tile Subtitle'),
        trailing: const ExpandIcon(),
      ),
    );
}
```

Before scrolling:
![image](https://user-images.githubusercontent.com/8662178/31746724-c4bdc3cc-b41d-11e7-8395-06bdb9c20938.png)

After scrolling:
![image](https://user-images.githubusercontent.com/8662178/31746762-e901f9f6-b41d-11e7-8304-601bf61943d2.png)

**Comment by dguralnick** [comment]
I wonder if this is related to @zzzev issue?

https://github.com/flutter/flutter/issues/12206

**Comment by DaveShuckerow** [comment]
It's worth noting the difference between this and #12206:  

This issue involves widgets that are on top of a background not casting a shadow, while the other is about widgets next to each other not casting a shadow.

**Comment by ds84182** [comment]
I just ran into this today. If you use `addRepaintBoundaries: false` to the ListView widget then the problem goes away. I'm guessing that RepaintBoundary clips off the shadow sometimes when it repaints the child.

**Comment by Hixie** [comment]
cc @chinmaygarde any ideas?

**Comment by Hixie** [comment]
cc @cbracken This is a top priority for the current milestone.

**Comment by jason-simmons** [comment]
The shadows are being clipped because they are drawn outside the cull rectangle (canvasBounds) that is provided when the Skia picture is recorded.
