### ISSUE TITLE
DateTime Comparison .isBefore(), isAfter() does not work on .toUtc() converted time in flutter

### ISSUE THREAD

**Issue by 0xharkirat** [flutter/flutter#126136]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I am using dart core DateTime package. This gives correct result when not using .toUtc();
but when I convert .toUtc(); it gives this behaviour

My code:
```
final DateTime now = DateTime.now().toUtc();
final DateTime startTime = DateTime(now.year, now.month, now.day, 6, 49); // 6:49 a.m
final DateTime endTime = DateTime(now.year, now.month, now.day, 6, 50); // 6:50 a.m
print('current time $now');
print('start time $startTime');
print('end time $endTime');
print('is current time before start time: ${now.isBefore(startTime)}');
print('is current time after end time: ${now.isAfter(endTime)}');
print('');
print('');
```

### Expected results

Expected Result:
```
current time 2023-05-05 06:48:26.455Z
start time 2023-05-05 06:49:00.000
end time 2023-05-05 06:50:00.000
is current time before start time: true
is current time after end time: false
```

### Actual results

My output: 
```
current time 2023-05-05 06:48:26.455Z
start time 2023-05-05 06:49:00.000
end time 2023-05-05 06:50:00.000
is current time before start time: false
is current time after end time: true
```

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @0xharkirat, this should be reported on the dart-land/sdk repo so that the dart team can investigate this. 

Closing from here since DateTime is a dart-core library. 

Thank you
