### ISSUE TITLE
flutter.github.io => flutter.io

### ISSUE THREAD

**Issue by afandria** [flutter/flutter#1261]
Some of the help documents and error messages reference `flutter.github.io`, but I think the site should instead be `flutter.io`. The former gives me a 404 (There isn't a GitHub Pages site here.) when I visit it.

**Comment by sethladd** [comment]
Thanks for noticing! I'll search through the site, but if you have specific examples, please let us know.

**Comment by afandria** [comment]
No problem! I'd use Github search on `flutter.github.io` to find them. There are 13 code results.

**Comment by afandria** [comment]
https://github.com/flutter/flutter/search?utf8=%E2%9C%93&q=%22flutter.github.io%22&type=Code

**Comment by sethladd** [comment]
Great! PR is up for review.

**Comment by sethladd** [comment]
Let us know if you find any other broken links. Appreciate the report.
