### ISSUE TITLE
[engine] Allow supplying custom gn args through gn wrapper.

### ISSUE THREAD

**Issue by selfisekai** [flutter/flutter#126197]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

using gn args that do not have their actual cli flags (yet)

### Proposal

copy dart's solution:
```sh
python3 ./tools/gn --gn-args 'use_default_linux_sysroot=false'
```

**Comment by chinmaygarde** [comment]
From Triage: For custom workflows, we've resorted to just editing the generated args.gn file directly. Though this way is more convenient. The upside of having all the flags be explicit is that they usually have help text along with it.
