### ISSUE TITLE
why not support  get birthdate or gender 

### ISSUE THREAD

**Issue by MTEV** [flutter/flutter#126153]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case
GoogleSignIn
why not support retrieve gender or  birthdate 
 
 

### Proposal
GoogleSignIn
 
any app in the world  need  birthdate  or gender

**Comment by stuartmorgan** [comment]
`google_sign_in` is a wrapper around the Google Sign-In SDK; it cannot provide features that are not part of those SDKs.

**Comment by MTEV** [comment]
> `google_sign_in` is a wrapper around the Google Sign-In SDK; it cannot provide features that are not part of those SDKs.

do  you  know how i can  get birthdate and gender because it's important for registration in my app
