### ISSUE TITLE
[Codelab] "Get to know Firebase for Flutter" code snippet is outdated

### ISSUE THREAD

**Issue by m-sugawara** [flutter/flutter#126128]
[In the sample code in the repository](https://github.com/flutter/codelabs/blob/main/firebase-get-to-know-flutter/step_09/lib/yes_no_selection.dart#L28), the `ElevatedButton` for `YesNoSelection` has been replaced with a `FilledButton`, but [the documentation](https://firebase.google.com/codelabs/firebase-get-to-know-flutter#8) still uses the `ElevatedButton`.
Since `useMaterial3: true` is specified in `ThemeData`, it looks like the following.

https://user-images.githubusercontent.com/9859181/236377007-abfcc6bf-bf42-49f0-b8b6-8c136ee46606.mov

**Comment by danagbemava-nc** [comment]
cc @domesticmouse

**Comment by domesticmouse** [comment]
PTAL @nohe427

**Comment by vj-codes** [comment]
@m-sugawara this is fixed, please close the issue
