### ISSUE TITLE
Build error or package_info

### ISSUE THREAD

**Issue by sharonzcts** [flutter/flutter#126186]
* What went wrong:
Execution failed for task ':package_info:compileDebugJavaWithJavac'.
> Failed to calculate the value of task ':package_info:compileDebugJavaWithJavac' property 'options.generatedSourceOutputDirectory'.
   > Querying the mapped value of map(java.io.File property(org.gradle.api.file.Directory, fixed(class org.gradle.api.internal.file.DefaultFilePropertyFactory$FixedDirectory, C:\gitProjects\gpsi\cts\ctsmobileapps2\TitanGPSInstallApp\fluidmobility_install-app\build\package_info\generated\ap_generated_sources\debug\out)) org.gradle.api.internal.file.DefaultFilePropertyFactory$ToFileTransformer@7f46204b) before task ':package_info:compileDebugJavaWithJavac' has completed is not supported

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
Exception: Gradle task assembleDebug failed with exit code 1

--------------------------------------------------------------------------
Keep getting the error above. I'm not using package_info directly, maybe another plugin I'm using causing the problem. But I don't know how to resolve the issue.

**Comment by stuartmorgan** [comment]
`package_info` was discounted several years ago, so will not receive any updates. You can use `flutter pub deps` to find out what is including it and adjust your dependencies accordingly.
