### ISSUE TITLE
Having issue when using F

### ISSUE THREAD

**Issue by enter-a-Name-pls** [flutter/flutter#126130]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

when i installed flutter by FVM shows this: Error (255): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (8 tries left)
the version i try to install is flutter 3.3.8

### Actual results

Error (255): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
Running pub upgrade...
Null check operator used on a null value
package:pub/src/entrypoint.dart 159:60                 Entrypoint.lockFilePath
package:pub/src/entrypoint.dart 102:21                 Entrypoint._loadLockFile
package:pub/src/entrypoint.dart 99:42                  Entrypoint.lockFile
package:pub/src/entrypoint.dart 294:21                 Entrypoint.acquireDependencies.<fn>
package:pub/src/log.dart 428:18                        progress
package:pub/src/entrypoint.dart 288:26                 Entrypoint.acquireDependencies
package:pub/src/command/upgrade.dart 128:13            UpgradeCommand._runUpgrade
package:pub/src/command/upgrade.dart 117:13            UpgradeCommand.runProtected
package:pub/src/command.dart 189:45                    PubCommand.run.<fn>
dart:async                                             new Future.sync
package:pub/src/utils.dart 109:12                      captureErrors.wrappedCallback
dart:async                                             runZonedGuarded
package:pub/src/utils.dart 126:5                       captureErrors
package:pub/src/command.dart 189:13                    PubCommand.run
package:args/command_runner.dart 209:27                CommandRunner.runCommand
package:pub/src/command_runner.dart 176:24             PubCommandRunner.runCommand
package:pub/src/command_runner.dart 161:20             PubCommandRunner.run
package:dartdev/dartdev.dart 45:56                     runDartdev
C:\b\s\w\ir\x\w\sdk\pkg\dartdev\bin\dartdev.dart 11:9  main
This is an unexpected error. The full log and other details are collected in:

    C:\Users\cj173\AppData\Local\Pub\Cache\log\pub_log.txt

Consider creating an issue on https://github.com/dart-lang/pub/issues/new
and attaching the relevant parts of that log file.
.
Error (255): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (8 tries left)
Running pub upgrade...

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

</details>


### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```
[✓] Flutter (Channel stable, 3.7.12, on Microsoft Windows [版本 10.0.22621.525], locale zh-CN)
    • Flutter version 3.7.12 on channel stable at C:\Users\cj173\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (2 weeks ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✗] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\cj173\AppData\Local\Android\sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2022.2)
    • Android Studio at E:\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.22621.525]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 113.0.5672.64
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 112.0.1722.68

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.

</details>

**Comment by darshankawar** [comment]
@enter-a-Name-pls 
As the error log indicates, it seems to be coming from `pub` package and it says to open an issue in dedicated repo, 

```
Consider creating an issue on https://github.com/dart-lang/pub/issues/new
and attaching the relevant parts of that log file.
```
so please follow the link and open the issue in that repo.
Closing from here.
