### ISSUE TITLE
[go_router_builder] Tests failing to run due to change in source_gen

### ISSUE THREAD

**Issue by tarrinneal** [flutter/flutter#126177]
There has been an update to source_gen that appears to break source_gen_test (@kevmoo), this has broken our tests in go_router_builder as well.

This issue is not isolated to go_router_builder as can be seen with this issue https://github.com/kevmoo/source_gen_test/issues/42 mentioned on source_gen_test.

/cc @stuartmorgan and @kevmoo

**Comment by kevmoo** [comment]
Should be fixed now! Get the latest!

**Comment by kevmoo** [comment]
I'll let you close this out @tarrinneal once you verify!

**Comment by tarrinneal** [comment]
Thanks for fixing that so quickly @kevmoo !

**Comment by tarrinneal** [comment]
> I'll let you close this out @tarrinneal once you verify!
@kevmoo 
The latest version isn't up on pub still, so I can't pull it in.

**Comment by kevmoo** [comment]
gah! forgot! published!

**Comment by tarrinneal** [comment]
Fixed! Thanks @kevmoo !
