### ISSUE TITLE
AppBar color does not use Theme.colorScheme.primary, or docs are wrong

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#126168]
From https://twitter.com/cfdevelop/status/1654267064071380995?s=51&t=8nbBOjm4Aq2ePrI4j-37hA

According to [the docs](https://api.flutter.dev/flutter/material/AppBar-class.html):
> The default app bar backgroundColor is the overall theme's ColorScheme.primary if the overall theme's brightness is Brightness.light

But that does not appear to happen in this case:

```dart
import 'package:flutter/material.dart';

void main() => runApp(
      MaterialApp(
        theme: ThemeData(
          brightness: Brightness.light,
          useMaterial3: true,
          colorScheme: ColorScheme.fromSwatch(
            primarySwatch: Colors.blue,
          ).copyWith(
            primary: Colors.pink,
          ),
        ),
        debugShowCheckedModeBanner: false,
        home: Scaffold(
          appBar: AppBar(),
          body: const SizedBox.shrink(),
        ),
      ),
    );
```

Instead of a pink app bar, it is white.

I am not sure if this is a bug, or if the docs are incorrect.

![image](https://user-images.githubusercontent.com/16964204/236524690-6341a6d9-e2e6-47e6-abe2-b82465107cad.png)

**Comment by mrwebbeast** [comment]
@Piinks Which Flutter version you are using ?
