### ISSUE TITLE
Run `flutter packages upgrade` doesn't provide output about what it does or did

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter#12627]
## Steps to Reproduce

![image](https://user-images.githubusercontent.com/405837/31775173-223dc748-b4e8-11e7-8108-45768ad146ff.png)

## Logs

Run your application with `flutter run` and attach all the log output.

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor

```
(issue162_group_message) $ flutter doctor
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-AT, channel master)
    • Flutter at /Users/zoechi/flutter/flutter
    • Framework revision f74cd91761 (6 hours ago), 2017-10-19 10:14:38 +0200
    • Engine revision 7c4142808c
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /usr/local/opt/android-sdk
    • Platform android-26, build-tools 26.0.2
    • ANDROID_HOME = /usr/local/opt/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.0.1, Build version 9A1004
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.5)
    • Flutter plugin version 18.1
    • Dart plugin version 172.4155.35

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)
```

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

I also got the same output when I was on alpha channel.
Sometimes `flutter packages get` and `flutter packages upgrade` work, sometimes they don't but I get no useful output in any case about whether the command did something or not, not even when using the verbose flag.

I only see if something happened when the `pubspec.lock` file (which I commit) shows some changes.

**Comment by zoechi** [comment]
This is still an issue. 
I think that the desired output is shown occassionally, but most of the time it is not.

**Comment by zoechi** [comment]
Expected output

![image](https://user-images.githubusercontent.com/405837/33703599-1c9a335a-db29-11e7-8354-1ad6dc2aba45.png)

**Comment by zoechi** [comment]
Any feedback on this? 
Is this a missing feature or was this output removed intentionally from `pub upgrade`s output? 
I miss that dearly every day.

**Comment by pulyaevskiy** [comment]
It would definitely be very useful to see output of `pub upgrade` as shown above. Currently there is no (easy) way to know if my dependencies are outdated.

**Comment by pulyaevskiy** [comment]
Well, there is a workaround though:

```bash
export FLUTTER_ROOT="/Users/something/flutter"
pub upgrade
```

**Comment by zoechi** [comment]
@pulyaevskiy works great.
I had to temporarily comment out
```
  flutter_driver:
    sdk: flutter
```

**Comment by epomatti** [comment]
Same here... not only it did not show output, but also it didn't upgrade my outdated packages.

**Comment by samuelg123** [comment]
Is this fixed?

**Comment by raphaaugustosilva** [comment]
Same here...

**Comment by danilofuchs** [comment]
I think the way Yarn handles it for node.js is ideal. When you run `yarn outdated`, it shows a rich, colourful output stating which packages need to be updated based on semver and a URL to check for release notes.
![Screen Shot 2020-02-20 at 11 21 01](https://user-images.githubusercontent.com/17657014/74943212-16909380-53d3-11ea-8a01-07d57362f63b.png)

**Comment by jessehao** [comment]
It would be nice if a `flutter pub outdated` cmd included.

**Comment by RadheshyamSingh** [comment]
I am able to list down the latest version for dependencies in pubspec.yaml using command 'flutter pub outdated'

![Screenshot 2020-09-30 at 9 00 24 AM](https://user-images.githubusercontent.com/16194335/94640135-6c2f0600-02fb-11eb-817b-afbd31180dd8.png)

**Comment by bensal-kb** [comment]
Opening the same project in android studio and adding the package works

**Comment by mit-mit** [comment]
@jonahwilliams @jonasfj this is a top-10 voted Flutter issue. I think this is an artifact of the `flutter pub` wrapper, right? Is a solution here to make `flutter pub` be a more direct passthrough to `dart pub`?

**Comment by jonasfj** [comment]
This is should be fixed with https://github.com/flutter/flutter/pull/74060 :tada: 

We can still do some improvements to get colors out, etc..
