### ISSUE TITLE
<Flutter/Flutter.h> cannot be imported when a pod transitive depends on Flutter

### ISSUE THREAD

**Issue by intspt** [flutter/flutter#126251]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

run the project in bug_demo directory.

### Expected results

Build Success.

### Actual results

Build Failed.

### Code sample

https://github.com/intspt/bug_demo

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![image](https://user-images.githubusercontent.com/8318578/236781211-79aca032-d8a4-4ad3-9197-18a311cc8ce5.png)

</details>

### Logs

<details><summary>Logs</summary>

```console
In file included from /Users/spt/Developer/bug_demo/bug_demo/ios/NativePod/Classes/test.m:1:
/Users/spt/Developer/bug_demo/bug_demo/ios/NativePod/Classes/test.h:1:9: fatal error: 'Flutter/Flutter.h' file not found
#import <Flutter/Flutter.h>
        ^~~~~~~~~~~~~~~~~~~
1 error generated.
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.3.1 22E261 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.7.12 on channel stable at /Users/spt/.flutterHomeOfficial3.0
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision 4d9e56e694 (3 weeks ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • Pub download mirror https://pub.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/spt/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_SDK_ROOT = /Users/spt/Library/Android/sdk
    • Java binary at: /Users/spt/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9862592/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/spt/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9862592/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (5 available)
    • M2012K11AC (mobile)        • 3514df5f                             • android-arm64  • Android 13 (API 33)
    • iPhone (mobile)            • 00008020-000954E136A1002E            • ios            • iOS 16.4.1 20E252
    • iPhone 14 Pro Max (mobile) • C247BDBA-F6F2-4DF3-8E25-A511C760D87D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 13.3.1 22E261 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by intspt** [comment]
In the normal_demo, cocoapods added the directory of Flutter.framework to the FRAMEWORK_SEARCH_PATHS of NativePod. Because shared_preferences dependencies will be inherited to NativePod.
image

But in the bug_demo, Flutter is a fake pod. FRAMEWORK_SEARCH_PATHS is processed by podhelper, which misses the scenarios of transitive dependencies, so an error will be reported during compilation.
image

**Comment by darshankawar** [comment]
@intspt 
I cloned the repo and tried to run but it gave me below errors:

```
    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `NativePod` from `NativePod`
    [!] The `NativePod` pod failed to validate due to 2 errors:
        - ERROR | license: Sample license type.
        - WARN  | homepage: The homepage has not been updated from default
        - WARN  | github_sources: Github repositories should use an `https`
        link.
        - WARN  | summary: The summary is not meaningful.
        - ERROR | description: The description is empty.


```

**Comment by intspt** [comment]
> @intspt I cloned the repo and tried to run but it gave me below errors:
> 
> ```
>     Fetching external sources
>     -> Fetching podspec for `Flutter` from `Flutter`
>     -> Fetching podspec for `NativePod` from `NativePod`
>     [!] The `NativePod` pod failed to validate due to 2 errors:
>         - ERROR | license: Sample license type.
>         - WARN  | homepage: The homepage has not been updated from default
>         - WARN  | github_sources: Github repositories should use an `https`
>         link.
>         - WARN  | summary: The summary is not meaningful.
>         - ERROR | description: The description is empty.
> ```

I'm sorry that I didn't encounter this error, but I have modified it according to the prompts, you can try again.

**Comment by stuartmorgan** [comment]
> ### Steps to reproduce
> run the project in bug_demo directory.

And what are the conceptual steps to get to the state you've cerated in bug_demo? I've read the comments in the PR several times and I'm still not clear on what exactly you are doing, and what the use case is.

**Comment by hyiso** [comment]
Similar problem.

After upgrade to 3.10, a third Pod depends on a Flutter plugin pod while throw compiling error: 'Flutter/Flutter.h' not found.

After steps:
1. commenting out `next unless target.dependencies.any? { |dependency| dependency.name == 'Flutter' }` in root `podhelper.rb` file
2. `pod install` again in iOS host project.

Then Build/Run host App succeeded.

**Comment by hyiso** [comment]
> > ### Steps to reproduce
> > run the project in bug_demo directory.
> 
> And what are the conceptual steps to get to the state you've cerated in bug_demo? I've read the comments in the PR several times and I'm still not clear on what exactly you are doing, and what the use case is.

IMO, the PR is trying to change the condition for finding pods depending on  'Flutter' directly to be suitable for  pods depending on 'Flutter' transitively.

That is, for example:
Plugin A -> Flutter
Pod B -> Plugin A

Before, post_install settings only affects 'Plugin A'
After, post_install settings also affects 'Pod B'

**Comment by stuartmorgan** [comment]
> Pod B -> Plugin A

This is the part I'm still not clear on: what is the use case for this? Flutter plugins are not "real" Pods intended to be published for use as such, that's just a mechanism for integrating them into Flutter application builds.

**Comment by stuartmorgan** [comment]
> so that **other iOS developers don't have to install Flutter SDK**.

So are you also internally publishing your own copy of the `Flutter` pod as well?

**Comment by hyiso** [comment]
> > so that **other iOS developers don't have to install Flutter SDK**.
> 
> So are you also internally publishing your own copy of the `Flutter` pod as well?

Yes, internal `Flutter` pod usually contains Flutter.dSYM, so that the host App CI/CD job can automatically upload Flutter Engine symbols to sentry(or other platform)

**Comment by hyiso** [comment]
All these pods are used only in `Release` mode.

 in `Debug` mode, the Flutter SDK and Flutter plugin source are used(for Flutter developers)

**Comment by intspt** [comment]
> > ### Steps to reproduce
> > run the project in bug_demo directory.
> 
> And what are the conceptual steps to get to the state you've created in bug_demo? I've read the comments in the PR several times and I'm still not clear on what exactly you are doing, and what the use case is.

The purpose of this change is not to solve this bug (although this change can indeed solve this bug). The real purpose is that Flutter currently forges a pod named Flutter, but this fake pod is still inconsistent with the real pod in some scenarios (such as the bug scenario).
All in all, the core goal of the change is to make the fake Flutter pod behave the same as the real Flutter pod.

PS:
As said in this comment, https://github.com/flutter/flutter/blob/f31dae2a8073be6ac54647a6e0a5d79dd6d80a34/packages/flutter_tools/bin/podhelper.rb#L210, after vendored_frameworks is replaced by path/to/nothing, the relevant Compilation settings are handled by podhelper. But the processing result is not consistent with the value of vendored_frameworks when Flutter.xcframework. So this change is necessary.

**Comment by jmagman** [comment]
Sorry for the long delay getting back to this.  I was on an extended leave.  I understand the problem now, thanks for the detailed demo apps.

I can change your `bug_demo` podspec to:
```diff
  spec.dependency 'shared_preferences'
+ spec.dependency 'Flutter'
```
And the Flutter import works fine because you told CocoaPods you want to import and link on Flutter.  Which is more correct because interestingly, in `normal_demo` CocoaPods is adding the transitive dependency to the search path:
```
FRAMEWORK_SEARCH_PATHS = $(inherited) "${PODS_CONFIGURATION_BUILD_DIR}/shared_preferences" "${PODS_ROOT}/../Flutter" "${PODS_XCFRAMEWORKS_BUILD_DIR}/Flutter"
```
But it's not adding `-framework "Flutter"` to `OTHER_LDFLAGS`.  So I guess it's assuming `CLANG_MODULES_AUTOLINK` is always set to YES (probably a safe assumption). When I set that to `NO` in your normal_demo and try to use a `Flutter` symbol, it fails as expected:
```
ld: Undefined symbols:
  _OBJC_CLASS_$_FlutterError, referenced from:
       in test.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

That being said, your solution seems fine to make Flutter tooling closer to CocoaPods's kind of strange assumption about transitive dependencies.  Which isn't an overarching goal for Flutter tooling, but if it saves you some trouble then it seems harmless?

> When integrating to host iOS project, the published Flutter plugin pods are used so that other iOS developers don't have to install Flutter SDK.

By the way is it a custom build of Flutter?  If not, can you use [Option C](https://docs.flutter.dev/add-to-app/ios/project-setup#option-c---embed-application-and-plugin-frameworks-in-xcode-and-flutter-framework-with-cocoapods) and not publish your own internal version of Flutter.xcframework.
