### ISSUE TITLE
[iOS] Update CocaPods spec for Flutter.

### ISSUE THREAD

**Issue by sagishm** [flutter/flutter#126225]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Hi,
I'm use the pod of Flutter with CocoaPods and that looks like this not maintained anymore.
You will update that or this will not update anymore?
last version is 3.0.0 and that not align to the last release.

Thanks

### Proposal

https://cocoapods.org/pods/Flutter

**Comment by darshankawar** [comment]
@sagishm 
You will probably need to raise this in dedicated repo as you mentioned in proposal section.

https://github.com/CocoaPods/Specs/commit/356ee3df7a09c61367060f38540e495901dd668a

I'll close this issue from here. If you disagree, write in comments and I'll reopen it.

**Comment by darshankawar** [comment]
@sagishm Thanks for the feedback. Cocoapods is a third party dependency manager. Even though it lists Flutter Dev Team, I am not sure if below listed installation guide I have seen in any of the podfiles in Flutter projects:

<img width="581" alt="Screenshot 2023-05-08 at 5 38 18 PM" src="https://user-images.githubusercontent.com/67046386/236820028-2e4ad635-854e-4cd9-acd8-2d9fb2a391ff.png">

For Flutter repo, this is an example to upgrade cocoapods version: https://github.com/flutter/flutter/pull/103655

**Comment by sagishm** [comment]
@darshankawar yes this the way i used to install Flutter with CocoaPods, but like i said and you can see in this link: https://github.com/CocoaPods/Specs/tree/master/Specs/c/0/4/Flutter

this pod is not updated lot of times, the last version there is 3.0.0 and that not possible to update to last Flutter version (3.7.*)
Your example is related to CocoaPods version and not to the Flutter dependency that manage by Flutter Dev Team.

**Comment by stuartmorgan** [comment]
> Cocoapods is a third party dependency manager.

This is about publishing the Flutter framework as a Pod, which has some niche use cases. My understanding is that this was initially published by someone else, but it has since been taken over by the Flutter Team, and is currently done manually (see https://github.com/flutter/flutter/issues/26712).

**Comment by darshankawar** [comment]
Thanks for clarifying @stuartmorgan. This request was a bit confusing as I couldn't find any reference or links to properly triage it.

**Comment by sagishm** [comment]
@stuartmorgan thanks for clarify.
@darshankawar  that mean this Pod is not management by Flutter Dev team?

**Comment by stuartmorgan** [comment]
> I'm use the pod of Flutter with CocoaPods

Could you elaborate on your use case exactly? How/why are you using that pod?

I followed up on this, and the only thing we're actively maintaining the pod for at this point is our own `pod lint` tests. `flutter build ios-framework --cocoapods` allows creating a local Podspec that points to your own Flutter installation, which is the recommend way of integrating into direct pod-based workflows.
