### ISSUE TITLE
[tool_crash] _CastError: (#0      new WebPlugin.fromYaml (package:flutter_tools/src/platform_plugins.dart:548:34))

### ISSUE THREAD

**Issue by Utsavrai1** [flutter/flutter#126271]
## Command
```
flutter pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_CastError: (#0      new WebPlugin.fromYaml (package:flutter_tools/src/platform_plugins.dart:548:34))
```
#0      new WebPlugin.fromYaml (package:flutter_tools/src/platform_plugins.dart:548:34)
#1      new Plugin._fromMultiPlatformYaml (package:flutter_tools/src/plugins.dart:142:21)
#2      new Plugin.fromYaml (package:flutter_tools/src/plugins.dart:78:21)
#3      _pluginFromPackage (package:flutter_tools/src/flutter_plugins.dart:63:17)
#4      findPlugins (package:flutter_tools/src/flutter_plugins.dart:88:28)
<asynchronous suspension>
#5      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1080:32)
<asynchronous suspension>
#6      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:357:5)
<asynchronous suspension>
#7      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:179:5)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
```
```
[✓] Flutter (Channel stable, 3.7.12, on Microsoft Windows [Version 10.0.22621.1555], locale en-IN)
    • Flutter version 3.7.12 on channel stable at C:\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (3 weeks ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\utsav\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.26)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.33529.622
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[✓] VS Code (version 1.78.0)
    • VS Code at C:\Users\utsav\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.62.0

[✓] Connected device (4 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)          • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.1555]
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 112.0.5615.138
    • Edge (web)                 • edge          • web-javascript • Microsoft Edge 113.0.1774.35

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 4d9e56e694b656610ab87fcf2efbcd226e0ed8cf

**Comment by tomg2012** [comment]
Hi,  have you tried running `flutter pub upgrade --major-versions` to see if it's a compatibility issue with one of your Flutter packages?

**Comment by Utsavrai1** [comment]
on running flutter pub upgrade --major-versions i got this 

Resolving dependencies...
  async 2.10.0 (2.11.0 available)
  boolean_selector 2.1.1
  characters 1.2.1 (1.3.0 available)
  clock 1.1.1
  collection 1.17.0 (1.17.1 available)
  cupertino_icons 1.0.5
  fake_async 1.3.1
  ffi 1.2.1 (2.0.1 available)
  flutter 0.0.0 from sdk flutter
  flutter_lints 2.0.1
  flutter_test 0.0.0 from sdk flutter
  js 0.6.5 (0.6.7 available)
  lints 2.0.1 (2.1.0 available)
  matcher 0.12.13 (0.12.16 available)
  material_color_utilities 0.2.0 (0.5.0 available)
  meta 1.8.0 (1.9.1 available)
  path 1.8.2 (1.8.3 available)
  sky_engine 0.0.99 from sdk flutter
  source_span 1.9.1 (1.10.0 available)
  stack_trace 1.11.0
  stream_channel 2.1.1
  string_scanner 1.2.0
  td 0.0.1 from path packages\td
  term_glyph 1.2.1
  test_api 0.4.16 (0.5.2 available)
  vector_math 2.1.4
No dependencies changed.
12 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.

No changes to pubspec.yaml!

Oops; flutter has exited unexpectedly: "type 'Null' is not a subtype of type 'String' in type cast".
A crash report has been written to C:\Users\utsav\Desktop\Flutter\apitest\flutter_02.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+type+%27Null%27+is+not+a+subtype+of+type+%27String%27+in+type+cast

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://github.com/flutter/flutter/issues/new?title=%5Btool_crash%5D+_CastError%3A+%28%230++++++new+WebPlugin.fromYaml+%28package%3Aflutter_tools%2Fsrc%2Fplatform_plugins.dart%3A548%3A34%29%29&body=%23%23+Command%0A%60%60%60%0Aflutter+pub+upgrade+--major-versions%0A%60%60%60%0A%0A%23%23+Steps+to+Reproduce%0A1.+...%0A2.+...%0A3.+...%0A%0A%23%23+Logs%0A_CastError%3A+%28%230++++++new+WebPlugin.fromYaml+%28package%3Aflutter_tools%2Fsrc%2Fplatform_plugins.dart%3A548%3A34%29%29%0A%60%60%60%0A%230++++++new+WebPlugin.fromYaml+%28package%3Aflutter_tools%2Fsrc%2Fplatform_plugins.dart%3A548%3A34%29%0A%231++++++new+Plugin._fromMultiPlatformYaml+%28package%3Aflutter_tools%2Fsrc%2Fplugins.dart%3A142%3A21%29%0A%232++++++new+Plugin.fromYaml+%28package%3Aflutter_tools%2Fsrc%2Fplugins.dart%3A78%3A21%29%0A%233++++++_pluginFromPackage+%28package%3Aflutter_tools%2Fsrc%2Fflutter_plugins.dart%3A63%3A17%29%0A%234++++++findPlugins+%28package%3Aflutter_tools%2Fsrc%2Fflutter_plugins.dart%3A88%3A28%29%0A%3Casynchronous+suspension%3E%0A%235++++++refreshPluginsList+%28package%3Aflutter_tools%2Fsrc%2Fflutter_plugins.dart%3A1080%3A32%29%0A%3Casynchronous+suspension%3E%0A%236++++++FlutterProject.ensureReadyForPlatformSpecificTooling+%28package%3Aflutter_tools%2Fsrc%2Fproject.dart%3A357%3A5%29%0A%3Casynchronous+suspension%3E%0A%237++++++PackagesInteractiveGetCommand.runCommand+%28package%3Aflutter_tools%2Fsrc%2Fcommands%2Fpackages.dart%3A357%3A5%29%0A%3Casynchronous+suspension%3E%0A%238++++++FlutterCommand.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command.dart%3A1257%3A27%29%0A%3Casynchronous+suspension%3E%0A%239++++++AppContext.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A150%3A19%29%0A%3Casynchronous+suspension%3E%0A%2310+++++CommandRunner.runCommand+%28package%3Aargs%2Fcommand_runner.dart%3A209%3A13%29%0A%3Casynchronous+suspension%3E%0A%2311+++++FlutterCommandRunner.runCommand.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command_runner.dart%3A283%3A9%29%0A%3Casynchronous+suspension%3E%0A%2312+++++AppContext.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A150%3A19%29%0A%3Casynchronous+suspension%3E%0A%2313+++++FlutterCommandRunner.runCommand+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command_runner.dart%3A229%3A5%29%0A%3Casynchronous+suspension%3E%0A%2314+++++run.%3Canonymous+closure%3E.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Frunner.dart%3A64%3A9%29%0A%60%60%60%0A%60%60%60%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Flutter+%28Channel+stable%2C+3.7.0%2C+on+Microsoft+Windows+%5BVersion+10.0.22621.1555%5D%2C+locale+en-IN%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+version+3.7.0+on+channel+stable+at+C%3A%5CFlutter%5Cflutter%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Upstream+repository+https%3A%2F%2Fgithub.com%2Fflutter%2Fflutter.git%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Framework+revision+b06b8b2710+%284+months+ago%29%2C+2023-01-23+16%3A55%3A55+-0800%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Engine+revision+b24591ed32%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Dart+version+2.19.0%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+DevTools+version+2.20.1%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Windows+Version+%28Installed+version+of+Windows+is+version+10+or+higher%29%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Android+toolchain+-+develop+for+Android+devices+%28Android+SDK+version+33.0.2%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Android+SDK+at+C%3A%5CUsers%5Cutsav%5CAppData%5CLocal%5CAndroid%5Csdk%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Platform+android-33%2C+build-tools+33.0.2%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Java+binary+at%3A+C%3A%5CProgram+Files%5CJava%5Cjdk-17%5Cbin%5Cjava%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Java+version+Java%28TM%29+SE+Runtime+Environment+%28build+17.0.7%2B8-LTS-224%29%0D%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+All+Android+licenses+accepted.%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Chrome+-+develop+for+the+web%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Chrome+at+C%3A%5CProgram+Files%5CGoogle%5CChrome%5CApplication%5Cchrome.exe%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Visual+Studio+-+develop+for+Windows+%28Visual+Studio+Build+Tools+2019+16.11.26%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Visual+Studio+at+C%3A%5CProgram+Files+%28x86%29%5CMicrosoft+Visual+Studio%5C2019%5CBuildTools%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Visual+Studio+Build+Tools+2019+version+16.11.33529.622%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Windows+10+SDK+version+10.0.19041.0%0A%0A%1B%5B33m%5B%21%5D%1B%5B39m+Android+Studio+%28version+2022.2%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Android+Studio+at+C%3A%5CProgram+Files%5CAndroid%5CAndroid+Studio%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F9212-flutter%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Dart+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F6351-dart%0A++++%1B%5B31m%E2%9C%97%1B%5B39m+Unable+to+find+bundled+Java+version.%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Try+updating+or+re-installing+Android+Studio.%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+VS+Code+%28version+1.78.0%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+VS+Code+at+C%3A%5CUsers%5Cutsav%5CAppData%5CLocal%5CPrograms%5CMicrosoft+VS+Code%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Flutter+extension+version+3.62.0%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+Connected+device+%283+available%29%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Windows+%28desktop%29+%E2%80%A2+windows+%E2%80%A2+windows-x64++++%E2%80%A2+Microsoft+Windows+%5BVersion+10.0.22621.1555%5D%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Chrome+%28web%29++++++%E2%80%A2+chrome++%E2%80%A2+web-javascript+%E2%80%A2+Google+Chrome+112.0.5615.138%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+Edge+%28web%29++++++++%E2%80%A2+edge++++%E2%80%A2+web-javascript+%E2%80%A2+Microsoft+Edge+113.0.1774.35%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m+HTTP+Host+Availability%0A++++%1B%5B32m%E2%80%A2%1B%5B39m+All+required+HTTP+hosts+are+available%0A%0A%1B%5B33m%21%1B%5B39m+Doctor+found+issues+in+1+category.%0A%0A%60%60%60%0A%0A%23%23+Flutter+Application+Metadata%0A%2A%2AType%2A%2A%3A+app%0A%2A%2AVersion%2A%2A%3A+1.0.0%2B1%0A%2A%2AMaterial%2A%2A%3A+true%0A%2A%2AAndroid+X%2A%2A%3A+false%0A%2A%2AModule%2A%2A%3A+false%0A%2A%2APlugin%2A%2A%3A+false%0A%2A%2AAndroid+package%2A%2A%3A+null%0A%2A%2AiOS+bundle+identifier%2A%2A%3A+null%0A%2A%2ACreation+channel%2A%2A%3A+stable%0A%2A%2ACreation+framework+version%2A%2A%3A+b06b8b2710955028a6b562f5aa6fe62941d6febf%0A%0A&labels=tool%2Csevere%3A+crash

**Comment by Utsavrai1** [comment]
I also received this after running flutter pub outdated.

Showing outdated packages.
[*] indicates versions that are not the latest available.

Package Name              Current   Upgradable  Resolvable  Latest

direct dependencies: all up-to-date.

dev_dependencies: all up-to-date.

transitive dependencies:
characters                *1.2.1    *1.2.1      *1.2.1      1.3.0
collection                *1.17.0   *1.17.0     *1.17.0     1.17.1
ffi                       *1.2.1    *1.2.1      *1.2.1      2.0.1
js                        *0.6.5    *0.6.5      *0.6.5      0.6.7
material_color_utilities  *0.2.0    *0.2.0      *0.2.0      0.5.0
meta                      *1.8.0    *1.8.0      *1.8.0      1.9.1

transitive dev_dependencies:
async                     *2.10.0   *2.10.0     *2.10.0     2.11.0
lints                     *2.0.1    *2.0.1      *2.0.1      2.1.0
matcher                   *0.12.13  *0.12.13    *0.12.13    0.12.16
path                      *1.8.2    *1.8.2      *1.8.2      1.8.3
source_span               *1.9.1    *1.9.1      *1.9.1      1.10.0
test_api                  *0.4.16   *0.4.16     *0.4.16     0.5.2
all dependencies are up-to-date.

**Comment by tomg2012** [comment]
Thanks for the additional information!

This is a duplicate of issue [#115738](https://github.com/flutter/flutter/issues/115738) 

It may have guidance that will help your situation.

**Comment by Utsavrai1** [comment]
I have downgraded to v3.3.10 and it is working fine.
