### ISSUE TITLE
[autosubmit] Support release branches

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#126282]
Today, autosubmit will skip processing PRs that are not on the default branch (main). Instead, it should process them the same, and submit once the checks are green.

**Comment by CaseyHillers** [comment]
\cc @ricardoamador

**Comment by ricardoamador** [comment]
It appears that a pull request can no luci status checks but still be a repo that we run status checks on. These are hardcoded values which we expect a status check on.
