### ISSUE TITLE
I was told by the console to report this idk what the problem is

### ISSUE THREAD

**Issue by bhfish2020** [flutter/flutter#126204]
I apologize if this is the incorrect way to do this, I am doing what console told me to do. I am on M1, i used cmd+shift+k to show the keyboard on a textfield that was below the fold of the type pad. It gave me an error and told me to report it here
<img width="1920" alt="Screen Shot 2023-05-06 at 12 40 53 PM" src="https://user-images.githubusercontent.com/123224534/236643672-7508a2a7-5224-4122-97f0-86c4ee053fac.png">

**Comment by jonahwilliams** [comment]
If you don't want to file a bug, you don't need to file a bug.
