### ISSUE TITLE
Signing key error during android build step 

### ISSUE THREAD

**Issue by reidbaker** [flutter/flutter#126267]
```
Execution failed for task ':app:packageDebugAndroidTest'.
> A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
   > com.android.ide.common.signing.KeytoolException: Failed to read key AndroidDebugKey from store "/home/chrome-bot/.android/debug.keystore": Integrity check failed: java.security.NoSuchAlgorithmException: Algorithm HmacPBESHA256 not available
```

Examples 
* https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Android%20Emulator%20Tests/7164/overview
* https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20build_tests_2_3/42157/overview
* https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8781555852982790881/+/u/run_plugin_dependencies_test/test_stdout

**Comment by RossComputerGuy** [comment]
I just ran into this issue on my own setup, seems `rm ~/.android/debug.keystore*` fixes the issue. Leaving this comment here until the actual issue is resolved.

**Comment by reidbaker** [comment]
My understanding of this issue is that the root of the problem is when you have a set of signing keys built with one version of java being used by an app compiled with a different version of java. This happens in CI because we run java 11 and java 17 on similar machines and was causing flakes. For most developers it should happen at most once per machine you develop on as you update and not again unless you downgrade  your AS/Java versions.

**Comment by godofredoc** [comment]
@reidbaker I believe this has been fixed can you please confirm?

**Comment by reidbaker** [comment]
Closing, but I would expect customers to hit this up to once per machine as they update to java 17.
