### ISSUE TITLE
Flutter IOS - Thread 1: EXC_BAD_ACCESS (code=1, address=0x0) error in xcode

### ISSUE THREAD

**Issue by Pedro-rdn** [flutter/flutter#126264]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I updated my `xcode` from version `13.4.1` to version `14.3`, when I run my flutter app the following error appears in the `SharedPreferencesPluguin`.

### Expected results

in this part of the code `let messenger = registrar.messenger()` following error appears `Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)`

### Actual results

The package uses the following version specification:

   shared_preferences: ^2.0.12

### Code sample

<details><summary>Code SharedPreferencesPluguin</summary>

```swift
import Foundation

#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#endif

public class SharedPreferencesPlugin: NSObject, FlutterPlugin, UserDefaultsApi {
  public static func register(with registrar: FlutterPluginRegistrar) {
    let instance = SharedPreferencesPlugin()
    // Workaround for https://github.com/flutter/flutter/issues/118103.
#if os(iOS)
    let messenger = registrar.messenger()
#else
    let messenger = registrar.messenger
#endif
    UserDefaultsApiSetup.setUp(binaryMessenger: messenger, api: instance)
  }
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
2023-05-08 10:06:39.748064-0300 Runner[11700:114618] <SKPaymentQueue: 0x6000007a4670>: No observers found that respond to "paymentQueue:shouldAddStorePayment:forProduct:", will not check for purchase intents
2023-05-08 10:06:39.789407-0300 Runner[11700:114875] 10.3.0 - [FirebaseMessaging][I-FCM002022] APNS device token not set before retrieving FCM Token for Sender ID '33811314958'. Notifications to this FCM Token will not be delivered over APNS.Be sure to re-retrieve the FCM token once the APNS device token is set.
2023-05-08 10:06:39.791714-0300 Runner[11700:114879] 10.3.0 - [FirebaseMessaging][I-FCM001000] FIRMessaging Remote Notifications proxy enabled, will swizzle remote notification receiver handlers. If you'd prefer to manually integrate Firebase Messaging, add "FirebaseAppDelegateProxyEnabled" to your Info.plist, and set it to NO. Follow the instructions at:
https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in_firebase_messaging
to ensure proper integration.
(lldb) 
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.0, on macOS 13.1 22C65 darwin-x64, locale pt) • Flutter version 3.7.0 on channel stable at /Users/pedro/fvm/versions/3.7.0 • Upstream repository https://github.com/flutter/flutter.git • Framework revision b06b8b2710 (3 months ago), 2023-01-23 16:55:55 -0800 • Engine revision b24591ed32 • Dart version 2.19.0 • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2) • Android SDK at /Users/pedro/Library/Android/sdk • Platform android-33, build-tools 33.0.2 • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495) • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3) • Xcode at /Users/pedro/Downloads/Xcode 2.app/./Contents/Developer • Build 14E222b • CocoaPods version 1.11.3

[✓] Chrome - develop for the web • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1) • Android Studio at /Applications/Android Studio.app/Contents • Flutter plugin can be installed from: 🔨 https://plugins.jetbrains.com/plugin/9212-flutter • Dart plugin can be installed from: 🔨 https://plugins.jetbrains.com/plugin/6351-dart • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2022.1.4) • IntelliJ at /Applications/IntelliJ IDEA CE.app • Flutter plugin can be installed from: 🔨 https://plugins.jetbrains.com/plugin/9212-flutter • Dart plugin can be installed from: 🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.76.0) • VS Code at /Applications/Visual Studio Code.app/Contents • Flutter extension version 3.62.0

[✓] Connected device (3 available) • iPhone 14 Pro (mobile) • CD024760-9AF2-42C8-B34D-C1F79D73141C • ios • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator) • macOS (desktop) • macos • darwin-x64 • macOS 13.1 22C65 darwin-x64 • Chrome (web) • chrome • web-javascript • Google Chrome 113.0.5672.63

[✓] HTTP Host Availability • All required HTTP hosts are available
```

</details>

**Comment by tomg2012** [comment]
Hi, have you tried upgrading shared_preferences to the latest version?

`shared_preferences: ^2.1.0`

**Comment by Pedro-rdn** [comment]
I tried it now, got the same error

**Comment by tomg2012** [comment]
You upgraded xcode, did you also upgrade your cocoapods dependencies? 

```
pod clean
pod install
```
if you need to upgrade your dependencies, then run `pod update` as well.

It may also help to run  `flutter clean` as well.

**Comment by darshankawar** [comment]
Thanks for the report @Pedro-rdn 
Can you provide the complete error log that shows the error line reported as in title ?
The logs you shared doesn't seem to be related to shared_preferences package.

Maybe related to https://github.com/flutter/flutter/issues/118103 as mentioned in the code snippet shared.

**Comment by briouyaasmae** [comment]
I have same error

**Comment by briouyaasmae** [comment]
This snippet of code cause the error 
   
    public static func register(with registrar: FlutterPluginRegistrar) {
        let flutterChannel = FlutterMethodChannel(
            name: Definitions.CHANNEL_FLUTTER_PLUGIN,
            binaryMessenger: registrar.messenger())
        
        SwiftAwesomeNotificationsPlugin()
            .AttachAwesomeNotificationsPlugin(
                usingRegistrar: registrar,
                throughFlutterChannel: flutterChannel)
    }

**Comment by Pedro-rdn** [comment]
i solved the error, the problem was not shared preferences, it was ios 16, i solved it by deleting the ios folder and running `flutter create .` in the project and resetting the folder
