### ISSUE TITLE
DrawRawPoints has unsafe sharing of point buffer between UI and Raster thread.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#126239]
Canvas.DrawRawPoints allows a caller to provide a float32 list containing the already encoded point data. The displaylist steals the pointer for this data here: https://github.com/flutter/engine/blob/main/lib/ui/painting/canvas.cc#L539 but does not copy it.

I believe this could lead to race conditions in accessing the underlying data. if the point list is small and is relocated I don't believe the data ptr will remain valiid?

**Comment by chinmaygarde** [comment]
[There is a copy here](https://github.com/flutter/engine/blob/5c8115a5f1520202415ecb98cb7f4abef7d5f818/display_list/dl_builder.cc#L872).
