### ISSUE TITLE
[linux, engine]: can't reuse event channel with same name on Linux

### ISSUE THREAD

**Issue by Gustl22** [flutter/flutter#126209]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

- Checkout repository: https://github.com/bluefireteam/audioplayers/blob/fbc658d2f69d581d2ca15c81c535047263fbfdf2
- Execute [environmental setup](https://github.com/bluefireteam/audioplayers/blob/main/contributing.md#environment-setup) with melos to get reference to the current platform interface.
- Execute this [test](https://github.com/bluefireteam/audioplayers/blob/fbc658d2f69d581d2ca15c81c535047263fbfdf2/packages/audioplayers/example/integration_test/lib_test.dart#L349): `flutter test --name "Reuse same platform event channel(\s*\(variant: .*\))?$" -d linux integration_test/lib_test.dart`

### Expected results

It should not fail.

The main question is: "Should platform channels with the same name be reusable". It's hard to write platform channel tests for our lib, as each test should be executeable independently. But that's not possible for the native side. As it always involves some initialization and deserialization / disposing, which lives in the same process for the whole test execution. Therefor it should be possible to use the exact same name for a previously disposed event channel.

### Actual results

```
MissingPluginException(No implementation found for method listen on channel xyz.luan/audioplayers/events/somePlayerId)
```

See: https://github.com/bluefireteam/audioplayers/actions/runs/4903980917/jobs/8756730803

If I explicitely [remove the channel from the binary messenger](https://github.com/bluefireteam/audioplayers/blob/a5f65dd5a5761c558a1b7e65fda8364f810cd7b8/packages/audioplayers_linux/linux/audioplayers_linux_plugin.cc#L230), the tests pass:
```
  fl_binary_messenger_set_message_handler_on_channel(
          binaryMessenger, ("xyz.luan/audioplayers/events/" + playerId).c_str(), nullptr, nullptr, nullptr);
```

But this should be done via [g_clear_object](https://github.com/bluefireteam/audioplayers/blob/a5f65dd5a5761c558a1b7e65fda8364f810cd7b8/packages/audioplayers_linux/linux/audio_player.cc#LL446C5-L446C19) already.

Also see: https://github.com/flutter/engine/pull/21316#issuecomment-1537231198

### Code sample

<details><summary>Code sample</summary>

It's not minimal, but it is not really necessary / hard to setup, as it involves platform channels.
https://github.com/bluefireteam/audioplayers/blob/fbc658d2f69d581d2ca15c81c535047263fbfdf2

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
  The following MissingPluginException was thrown while activating platform stream on channel
  xyz.luan/audioplayers/events/somePlayerId:
  MissingPluginException(No implementation found for method listen on channel
  xyz.luan/audioplayers/events/somePlayerId)
  
  When the exception was thrown, this was the stack:
  #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:313:7)
  <asynchronous suspension>
  <asynchronous suspension>
  (elided one frame from package:stack_trace)
  ════════════════════════════════════════════════════════════════════════════════════════════════════
  ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
  The following MissingPluginException was thrown while de-activating platform stream on channel
  xyz.luan/audioplayers/events/somePlayerId:
  MissingPluginException(No implementation found for method cancel on channel
  xyz.luan/audioplayers/events/somePlayerId)
  
  When the exception was thrown, this was the stack:
  #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:313:7)
  <asynchronous suspension>
  <asynchronous suspension>
  (elided one frame from package:stack_trace)
  ════════════════════════════════════════════════════════════════════════════════════════════════════
  ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
  The following message was thrown:
  Multiple exceptions (2) were detected during the running of the current test, and at least one was
  unexpected.
  ════════════════════════════════════════════════════════════════════════════════════════════════════
  Test failed. See exception logs above.
  The test description was: Reuse same platform event channel id
```

See: https://github.com/bluefireteam/audioplayers/actions/runs/4903980917/jobs/8756730803

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.0, on Ubuntu 22.04.2 LTS 5.15.0-71-generic, locale en_US.UTF-8)
    • Flutter version 3.7.0 on channel stable at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (3 months ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/gustl/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_SDK_ROOT = /home/gustl/Android/Sdk
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+10-Ubuntu-0ubuntu122.04)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at /snap/intellij-idea-ultimate/426
    • Flutter plugin version 73.0.4
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.2 LTS 5.15.0-71-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 112.0.5615.121

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

</details>

Also see: https://github.com/flutter/engine/pull/21316#issuecomment-1537231198

**Comment by stuartmorgan** [comment]
Have you verified the order your code is running in? If there's an overlap, such that the `dispose` of the first channel is called just *after* the registration of the second one, that would explain the error you are seeing.

**Comment by Gustl22** [comment]
Yes I'm pretty sure, there's no overlap. See also the explanation in `actual results`, where the test succeeds, when removing the channel manually in the same native synchronous execution block.

**Comment by stuartmorgan** [comment]
> See also the explanation in `actual results`, where the test succeeds, when removing the channel manually in the same native synchronous execution block.

That's consistent with an overlap theory though. The event channel's handler has a self reference that is removed when the channel is closed; forcibly removing that reference by overwriting the handler would potentially change the order of operations.

In particular, this statement is problematic:

> But this should be done via [g_clear_object](https://github.com/bluefireteam/audioplayers/blob/a5f65dd5a5761c558a1b7e65fda8364f810cd7b8/packages/audioplayers_linux/linux/audio_player.cc#LL446C5-L446C19) already

You are assuming the channel object is *destroyed* at that line, which is only true if it's the last reference. Have you verified that? Are you sure it's already been closed at that point?

**Comment by Gustl22** [comment]
I thought `g_clear_object` is the only thing to do in order to close the event channel and its according stream:
https://github.com/flutter/engine/blame/6db93ea20e8a864bdd2c33a0c16c2a92673fcfb7/shell/platform/linux/fl_event_channel.cc#L123

I added prints at various places to verify the ref cound:
```
g_print("event channel ref count %i\n", (((GObject*)(eventChannel))->ref_count));
```

- Directly after `fl_event_channel_new`, the variable has ref count of 2
- This is the same until I call  `g_clear_object` in the dispose block.
- Then the variable is null and I cannot get the count anymore, but it should be 0 by then, otherwise the variable wouldn't have been cleared (?).

On the other hand if I do `g_object_unref(eventChannel)` after the object pointer is passed to the specific player, the count then is 1, but if I call `g_clear_object`, I get a warning `instance of invalid non-instantiatable type '(null)'`.

Do I need to call sth else to dispose the stream before clearing the channel, maybe?
Thanks for your support.

**Comment by stuartmorgan** [comment]
Looking at the full API again, I think I was confused by the destruction callback name; I thought the channel would be closed from the Dart side, but since it's a broadcast channel there wouldn't be a case where closing it from that side would make sense.

CC @robert-ancell @cbracken 

I suspect the interleaving is likely an internal behavior we need to fix in the engine, where:
- setting the second handler from the second event channel object overwrites the first handler
- which triggers the destruction callback for the older event channel object
- which eraser the handler that was just set by the second event channel object.

We'll need to check in a debug engine; the above is just based on reading source and the observed behavior. (If that is the case, we should see if message channels have the same issue.) But IIRC on other platforms channels explicitly *don't* "own" the handler as part of their lifetime, avoiding this kind of issue; I don't remember if there was a specific reason we did it differently on Linux. If my guess above is correct we can presumably fix the simple case by making replacing in the handler map a two-step process (delete old, add new), but more complex cases where the lifetime of the first object is longer for external reasons would still be an issue.

Labeling for more investigation.

**Comment by Gustl22** [comment]
Thx, @stuartmorgan . Yes maybe a simple test where creating and clearing the event channel two times can bring more light in this case: https://github.com/flutter/engine/blob/fa83e4c41bb172b0c7b2af26a2685376baf04abc/shell/platform/linux/fl_event_channel_test.cc#L81
Honestly I'm no C++ developer and don't even know how I would execute these tests. Also the `audioplayers` project is quite bulky, so also some mistake could be hidden there, which I really tried hard to exclude. Unfortunately there're no other projects which use multiple temporary event channels on linux (best candidate would be the `video_player`).

**Comment by robert-ancell** [comment]
Looks like this was fixed for method channels in 3c4f535e9993bbad3b87779e0faef54b7c725bed, but the same fix is not applied for event channels.

**Comment by robert-ancell** [comment]
And the above fix looks like it leaks messenger :(

**Comment by stuartmorgan** [comment]
Oops :( We just need to replace that line with a `g_clear_object`, right?
