### ISSUE TITLE
Staging_build_linux framework_tests_misc failing at tip of tree 

### ISSUE THREAD

**Issue by reidbaker** [flutter/flutter#126278]
Marked flakey but failing 
https://github.com/flutter/flutter/blob/master/.ci.yaml#L2469

Has not had a passing test in over a year. 
https://ci.chromium.org/p/flutter/builders/staging/Staging_build_linux%20framework_tests_misc?cursor=id%3E8814429255333607313&limit=200

Has never had a passing run 
https://ci.chromium.org/ui/p/flutter/builders/staging/Staging_build_linux%20framework_tests_misc/2/overview 

We should delete this code.

**Comment by TahaTesser** [comment]
@reidbaker 
`good first contribution` for this kinda issue is unusual so I'm guessing it was added by mistake.

**Comment by keyonghan** [comment]
@yusuf-goog Shall we remove these targets?

**Comment by reidbaker** [comment]
It was intentional since the only task is to delete the code. I figured it would be pretty easy.

**Comment by yusuf-goog** [comment]
@MahmoudZayad we do not need this build anymore, and it is a good candidate for fully removing the entire  "Staging_build_linux framework_tests_misc" target.

**Comment by reidbaker** [comment]
Pr approved waiting on green tree and google testing passing.
