### ISSUE TITLE
Remove Result and Generic from `Page` and `Route`

### ISSUE THREAD

**Issue by caseycrogers** [flutter/flutter#126243]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Flutter's built in navigation system is incredibly complicated. A core part of this is because it is doing A LOT of different things. While it is fundamentally a matter of opinion, I would argue that a lot of the things it's trying to do are scope creep with no clear separation of concerns and trimming these features would make `Navigator`:
1. More accessible
2. Easier to extend
3. Easier to maintain

I think the lowest hanging fruit for cutting down unnecessary complexity would be the type generic on `Page` and `Route`. This is a highly niche feature (allowing routes to return values on pop) that probably sees low usage outside of the Flutter built-ins, yet it produces a type generic and `dynamic result` arg that bleeds out into every part of the Navigation experience. It's also trivial for anyone using the navigation API to [implement this functionality themself](https://github.com/flutter/flutter/issues/126243#issuecomment-1538910404). This makes it extremely low ROI.

### Proposal

While it can be scary and painful to cut a feature (especially because this will definitely break a lot of devs' code and packages), imo this is an #embraceTheYakShave moment. I think very few people would argue this feature should be in Navigator if we were rebuilding it from scratch today. It's an especially incoherent feature if people are using a declarative navigation style where `pop` often isn't even called directly anyway (the page stack is simply rebuilt).

Note: I'm currently working on a PR to prototype out this change. I'll see if I can get it into a first-pass state, but I imagine this is probably way too big a change for me to be handling all on my own.

**Comment by caseycrogers** [comment]
Here's my current prototype of how to pop with a result without the type generics built into Navigator, using `popup_menu` as an example. This solution is just a first pass, it probably needs a lot more polish and/or a slightly different approach may be better. Open to feedback here. This is primarily to demonstrate that we can rip out an ENORMOUS amount of complexity from `navigator.dart`, `route.dart` etc for only a very minimal loss of usability to the result API.

Declare a mixin that holds the result in the route and add it to `PopupRoute`:
https://github.com/flutter/flutter/blob/e11a2213e2bbd9f0c3e86303fe3c1ec354d9faf8/packages/flutter/lib/src/widgets/routes.dart#L1779
```dart
abstract class PopupRoute<T> extends ModalRoute with ResultRouteMixin<T> { ... }

mixin ResultRouteMixin<T> {
  T? _result;

  T? get result => _result;

  set result(T? newValue) {
    assert(_result == null, 'Result should only be set once.');
    _result = result;
  }
}
```

In `PopUpMenu`, to return the result:
https://github.com/flutter/flutter/blob/431dfc83263b395299523b0ea1e2eba69cd68002/packages/flutter/lib/src/material/popup_menu.dart#L341
```dart
  void handleTap() {
    widget.onTap?.call();

    // This is a little sloppy, could be cleaned up.
    (ModalRoute.of(context)! as ResultRoute<T>).result = widget.value;
    Navigator.pop(context);
  }
```

in `showMenu`, to receive the result:
https://github.com/flutter/flutter/blob/431dfc83263b395299523b0ea1e2eba69cd68002/packages/flutter/lib/src/material/popup_menu.dart#L939
```dart
Future<T?> showMenu<T>({ ... }) {
  .
  .
  .

  final NavigatorState navigator = Navigator.of(context, rootNavigator: useRootNavigator);
  final _PopupMenuRoute<T> route = _PopupMenuRoute<T>( ... );
   navigator.push(route);
   // `popped` is now just `Future<void>`.
   return route.popped.then((_) => route.result);
}
```

**Comment by goderbauer** [comment]
cc @chunhtai 

The migration path for existing users of this feature looks rather cumbersome...

**Comment by chunhtai** [comment]
I am not sure removing the result and generic type can be reduce much complexity, but it would be a pain for customers that do need this feature. I think unless there exist a better or cleaner way to pass data around routes, this change would probably create more chaos. That being said, I think we can probably hide the generic type and result in `Page`. I can't find a way to really make use of this result if you are using Page. @goderbauer do you recall why we include the result in Page API?

**Comment by caseycrogers** [comment]
"That being said, I think we can probably hide the generic type and result in Page"

I like this idea-if there's a good way to hide it from `Page` I think this is a good incremental step. But if `Page` needs to create `Route` and `Route` still needs a generic, how do we square that circle? Have `createRoute` return `Route<dynamic>`? I'll try prototyping this change out and see how it propagates. Maybe there's no loss in type safety here because `pop` and `push` crush everything down to a dynamic anyway?

This kind of begs the question: why don't we get rid of the type generic on `Route` too because we're already losing type safety on the value's setters and getters (`pop` and `push`) so the generic isn't even improving safety anyway? Maybe this is the best of all worlds? Massive reduction in complexity for minimal/no breaking change and we don't lose any safety anyway because the generic was just providing the illusion of type safety. At that point, the marginal value of removing the `[dynamic result]` argument from the various pop/push related methods would be pretty low ROI and I'd agree not worth the disruption to customers.

**Comment by caseycrogers** [comment]
Bumping this for your all's thoughts! I'm ready to get this PR in reviewable shape if I get a thumbs up on one direction or another from you all.

**Comment by chunhtai** [comment]
I think removing the generic type from page sounds fine to me. The route still needs the generic type though
