### ISSUE TITLE
Flake in DeviceLab commands_test

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#12623]
[commands_test](https://github.com/flutter/flutter/blob/1a3097025dbc13969c6ada32cc559023984fdda1/dev/devicelab/manifest.yaml#L138) failed with the following flake:

```
drive:stderr: [critical] FlutterDriver: Application has not started in 30 seconds. Giving up.
drive:stdout: 01:00 [32m+0[0m[31m -1[0m: (setUpAll) [1m[31m[E][0m[0m
drive:stdout:   HttpException: Connection closed before full header was received, uri = http://127.0.0.1:8100/ws
```

Full report in https://gist.github.com/tvolkert/d5afa0f068a541511de9cb232b303098

**Comment by zoechi** [comment]
Is this issue still relevant?

**Comment by tvolkert** [comment]
Haven't seen it since - gonna close.
