### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method VideoOutputManager.Create on channel com.alexmercerind/media_kit_video)

### ISSUE THREAD

**Issue by ZG-123** [flutter/flutter#126242]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

**使用media_kit_video时，我新创建了一个window，就报这个错误，视频也解析不出来，这是为什么，有人碰到过吗**

### Proposal

Unhandled Exception: MissingPluginException(No implementation found for method VideoOutputManager.Create on channel com.alexmercerind/media_kit_video)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:313:7)
<asynchronous suspension>
#1      VideoControllerNative.create (package:media_kit_video/src/video_controller_native.dart:81:5)
<asynchronous suspension>
#2      _CameraViewItemState.initState.<anonymous closure> (package:example/Widgets/Camera/camera_view.dart:155:20)
<asynchronous suspension>

**Comment by danagbemava-nc** [comment]
Hi @ZG-123, `media_kit_video` is a third-party plugin. Any issues you face using said plugin should be reported on it's repo https://github.com/alexmercerind/media_kit/issues?q=is:issue+is:open+sort:updated-desc

Closing as this is not a flutter issue. 

Thank you

**Comment by ZG-123** [comment]
问题已经解决
