### ISSUE TITLE
GoRouter - Disable automatic handling of deeplink

### ISSUE THREAD

**Issue by esDotDev** [flutter/flutter#126277]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

In my app I use deeplink to unlock specific features. So the user will deeplink in with something like 
"redeem/SOME_CODE", I will parse "SOME_CODE" and if it is a correct code, I will unlock a feature for them.

The previously worked fine with GR4.x, but with 6.x I am now getting a 404 error "No route for: SOME_CODE". I do not want it to attempt to find a route for this path. 

How can I disable this automatic redirect? I want to parse the deeplink contents myself, and if I want to go to a specific route after parsing it, I can simply do that using the imperative API.

### Proposal

Provide some method to disable the automatic behavior that is trying to be helpful but is just causing problems.

**Comment by darshankawar** [comment]
@esDotDev I think your case is similar to the one described here https://github.com/flutter/flutter/issues/103659, so please follow-up in it for further updates. Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.
