### ISSUE TITLE
Expose focusNode for widget testing in TextFormField

### ISSUE THREAD

**Issue by jfacoustic** [flutter/flutter#126292]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I'd like to test that a TextFormField lost focus when clicking a GestureDetector.  FocusNode is exposed for TextFields, but not for TextFormFields:

```dart
      final emailFieldFinder = find.byKey(const Key('email-field'));
      await tester.enterText(emailFieldFinder, _email);
      await tester.pumpAndSettle();

      final body = find.byKey(const Key('gesture-detector'));
      await tester.tap(body);
      await tester.pumpAndSettle();
      
     // If emailField is a TextField, you can access focusNode, but not if it's a TextFormField:
     expect(tester.widget<TextFormField>(emailFieldFinder).focusNode!.hasFocus, false); // throws an error.
```

### Proposal

Allow access to focusNode from a TextFormField (as well as other TextField values that might be useful for testing):

```dart
final field = TextFormField(...);
field.focusNode...
```

**Comment by darshankawar** [comment]
> FocusNode is exposed for TextFields, but not for TextFormFields:



> Allow access to focusNode from a TextFormField

@jfacoustic  `FocusNode` seems to be already available for `TextFormField`.

<img width="354" alt="Screenshot 2023-05-09 at 12 11 29 PM" src="https://user-images.githubusercontent.com/67046386/237015359-43ded093-7b32-4b04-925a-c9bf209f7fd2.png">


> ```dart
> expect(tester.widget<TextFormField>(emailFieldFinder).focusNode!.hasFocus, false); // throws an error.
> ```

Can you provide the error log that is thrown ?
