### ISSUE TITLE
flutter doctor reports "Unable to find bundled Java version." with newest Android Studio version

### ISSUE THREAD

**Issue by xieenming** [flutter/flutter#126244]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Download/install Android Studio newest version, e.g. Flamingo 2022.2.1 (https://developer.android.com/studio).
2. In the Android Studio folder, you can see that there is no more android-studo/jre but there is a new folder **android-studio/jbr** . The android-studio/jbr/bin folder contains the binary files like java, javac, etc.
3. Launch `flutter doctor` (my flutter version is 3.7.5) in your command line.

On StackOverflow, there is a post according to this issue: https://stackoverflow.com/questions/51281702/unable-to-find-bundled-java-version-on-flutter

### Expected results

`flutter doctor` does not report "Unable to find bundled Java version." error.

### Actual results

flutter doctor reports "Unable to find bundled Java version." error. See screenshot below:

Seems like `flutter doctor` has not updated to recognize the new organization in Android Studio for JRE/JDK

### Code sample

flutter doctor

### Screenshots or Video

![Screenshot from 2023-05-08 11-56-09](https://user-images.githubusercontent.com/68989498/236730509-e4a1b230-4003-4b02-9082-ca79f6cd14b2.png)

### Logs

no log

### Flutter Doctor output

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.5, on Ubuntu 20.04.6 LTS 5.15.0-71-generic, locale
    en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (version 2022.2)
    ✗ Unable to find bundled Java version.
[✓] IntelliJ IDEA Community Edition (version 2022.1)
[✓] IntelliJ IDEA Community Edition (version 2022.2)
[✓] VS Code (version 1.77.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

**Comment by xieenming** [comment]
After doing `ln -s jbr jre` in folder android-studio (https://stackoverflow.com/a/75119315), `flutter doctor` does not report issue:

![Screenshot from 2023-05-08 12-09-05](https://user-images.githubusercontent.com/68989498/236731983-0b921378-139f-4e73-8ea0-2fdcad493959.png)

**Comment by danagbemava-nc** [comment]
Hi @xieenming, you are on an older version of flutter. This issue was initially reported in https://github.com/flutter/flutter/issues/106674 and has since been fixed on the latest versions of flutter. It was cherry-picked into stable 3.7.6. See https://github.com/flutter/flutter/issues/121505

Kindly upgrade to the latest version of flutter stable (3.7.12) 

Closing from here as this has already been fixed. If you still face this issue after upgrading to the latest version of the stable channel, kindly leave a comment below and I will reopen this. 

Thank you
