### ISSUE TITLE
code in firebase codelab uses wrong/outdated property of GoRoute state

### ISSUE THREAD

**Issue by Lutzewald** [flutter/flutter#126236]
hey,

in the codelab https://firebase.google.com/codelabs/firebase-get-to-know-flutter#4 the code in the main.dart refers to state.queryParams which seems to be incorrect when using go_router: ^7.0.0

build error is fixed when accessing state.queryParameters instead

**Comment by danagbemava-nc** [comment]
Hi @Lutzewald, thanks for pointing it out.
The parameter has indeed been renamed https://pub.dev/packages/go_router/changelog#700

cc @domesticmouse

**Comment by domesticmouse** [comment]
PTAL @nohe427
