### ISSUE TITLE
When flutter reports an exception "thrown building Widget", tell users the exact widget type (will PR)

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#126306]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Start from a production error in my own app:

```
RenderBox.size(box.dart:2031)
ComponentElement._firstBuild(framework.dart:4950)
ComponentElement.mount(framework.dart:4944)
Element.inflateWidget(framework.dart:3953)
Element.updateChild(framework.dart:3682)
ComponentElement.performRebuild(framework.dart:4993)
Element.rebuild(framework.dart:4690)
ComponentElement._firstBuild(framework.dart:4950)
ComponentElement.mount(framework.dart:4944)
...
```

with flutter_error_details:
context: "thrown building Widget"
library: "widget library"

(These are from Sentry)

From the information above, I guess it means "when doing Widget.build, some code goes wrong and touches `SomeRenderObject.size` and thus errors".

The problem is that, *which* Widget indeed? There are a ton of widgets, let alone third-party widgets, that may touch the RenderBox.size directly or indirectly. Thus, this issue proposes to show more information about this.

(By the way, I guess in normal situations it should appear in stack trace, but I am unsure why here it does not appear - maybe it is inlined?)

**Comment by danagbemava-nc** [comment]
Hi @fzyzcjy, it turns out there's an existing issue for this. See https://github.com/flutter/flutter/issues/103264

Closing from here as duplicate. 

If you disagree, kindly leave a comment below and I will reopen this. 

Thank you

**Comment by fzyzcjy** [comment]
@danagbemava-nc Hi, thanks for the reply but it seems it is not a duplicate.

I am proposing

> context: "thrown building Widget"

become

> context: "thrown building MyFancyWidgetClassName"

while that issue proposes that, the *stack trace* adds some extra information.

**Comment by danagbemava-nc** [comment]
That issue suggests adding the Widget information to the stacktrace.
Your PR may not address the issue above tho, so I'll be reopening this.

**Comment by fzyzcjy** [comment]
Thanks. Btw adding information to *stacktrace* IMHO is not that easy...

**Comment by goderbauer** [comment]
I don't understand what problem this issue is describing that we need to solve. Do you have a code sample that crashes in the way you describe and shows not sufficient information to trace the crash back?

**Comment by fzyzcjy** [comment]
Yes I realize finally it is because the stack trace *itself* I have pasted in this issue is incorrect (see https://github.com/getsentry/sentry-dart/issues/1429). Then I guess the exact type should be sufficient most of the time.

**Comment by goderbauer** [comment]
Based on the previous comment I am going to close this for now then since there currently is nothing actionable to do.
