### ISSUE TITLE
libtxt: Implement OpenType locl support

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#12630]
Some fonts have different variant glyphs based on the locale. This is critical for Chinese, Chinese (Simplified), Japanese, and Korean; it is also used for other scripts (e.g. Latin vs Romanian).

OpenType encodes this using the `locl` feature tag.

There are some resources to test this online, e.g. the [LOCL Test font](https://github.com/adobe-fonts/locl-test).

It is common to not know what locale to use. In that case, we should default to no locale and allow the font to pick its default.

- [ ] Pass the locale through from the framework to the engine. Each `TextSpan` should take an optional `Locale`; by default it should inherit the value from `ParagraphStyle` which should have a `Locale` also.
- [ ] Use the locale in the engine to configure the font rendering by setting it in the `minikin::TextStyle` structure.
- [ ] Test this.

**Comment by Hixie** [comment]
This is important for milestone 3, but we can flip the libtxt switch before we do this.

**Comment by najeira** [comment]
How do I pass the locale to the ui.TextStyle?

**Comment by Hixie** [comment]
If you're down at that level of the system, you can just pass it to the ui.TextStyle constructor.
If you're at a higher level, we haven't yet added it to the framework. I've filed https://github.com/flutter/flutter/issues/16408 to cover this.
