### ISSUE TITLE
Flutter web: Google sign in work on web in localhost but when deploy it in firebase, the pop up not showing or showing a moment and disappear 

### ISSUE THREAD

**Issue by AnassErraidi** [flutter/flutter#126333]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I use google sign in web: google_sign_in: ^6.1.0

I have an application that authenticate with firebase Authentication witch work, I add google sign in and it work in android, for web I modify it to work : in localhost chrome work fine but when release it in Firebase Hosting , the app work but the google sign in pop up not showing or appear a moment and disappear
here my app: https://myshopforall.web.app/

  googleSignIn.disconnect();
      await Firebase.initializeApp();
      User? user;
      FirebaseAuth auth = FirebaseAuth.instance;
      auth.signOut();

      // The `GoogleAuthProvider` can only be
      // used while running on the web
      GoogleAuthProvider authProvider = GoogleAuthProvider();
      authProvider.setCustomParameters({'prompt': 'select_account'});

      // authProvider.setCustomParameters({
      //   prompt: "select_account"
      // });
      try {
        // await googleSignIn.signOut();
        // await auth.signOut();
        final UserCredential userCredential =
        await auth.signInWithPopup(authProvider);
        user = userCredential.user;
      } catch (e) {
        print(e);
      }

### Expected results

to show popup that let the user choose witch google account to log with after login successfully authenticate and enter an advanced user account

### Actual results

in localhost chrome work fine but when release it in Firebase Hosting , the app work but the google sign in pop up not showing or appear a moment and disappear
here my app: https://myshopforall.web.app/

### Code sample

<details><summary>Code sample</summary>

```dart
googleSignIn.disconnect();
await Firebase.initializeApp();
User? user;
FirebaseAuth auth = FirebaseAuth.instance;
auth.signOut();

  // The `GoogleAuthProvider` can only be
  // used while running on the web
  GoogleAuthProvider authProvider = GoogleAuthProvider();
  authProvider.setCustomParameters({'prompt': 'select_account'});

  // authProvider.setCustomParameters({
  //   prompt: "select_account"
  // });
  try {
    // await googleSignIn.signOut();
    // await auth.signOut();
    final UserCredential userCredential =
    await auth.signInWithPopup(authProvider);
    user = userCredential.user;
  } catch (e) {
    print(e);
  }
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.7.12, on macOS 13.3.1 22E772610a darwin-arm64,
    locale en-MA)
    • Flutter version 3.7.12 on channel stable at
      /Users/anasserraidi/Developer/flutter
    ! Warning: `dart` on your path resolves to
      /opt/homebrew/Cellar/dart/2.19.5/libexec/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/anasserraidi/Developer/flutter.
      Consider adding /Users/anasserraidi/Developer/flutter/bin to the front of
      your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (3 weeks ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it
      is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/anasserraidi/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.3.1 22E772610a
      darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.5672.92

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

</details>

**Comment by DaniyalDolare** [comment]
I dont understand why are you using these line while you want to sign in
```
googleSignIn.disconnect();
auth.signOut();
```

But still I test google sign in on local as well on firebase deployment, it is working fine for me.

Here the code I am using for sign in for web:

```
if (kIsWeb) {
      final FirebaseAuth _auth = FirebaseAuth.instance;
      // The `GoogleAuthProvider` can only be used while running on the web
      GoogleAuthProvider authProvider = GoogleAuthProvider();
      try {
        final UserCredential userCredential =
            await _auth.signInWithPopup(authProvider);

        return userCredential.user;
      } catch (e) {
        debugPrint('error on web signin: $e');
        rethrow;
      }
    }
```


And this were the version of all dependencies:

```
firebase_auth: ^4.5.0
google_sign_in: ^6.1.0
firebase_core: ^2.1.1
```

Here's the link of app if you want to check:
[https://productivity-app-e63c8.web.app/#/](https://productivity-app-e63c8.web.app/#/)

**Comment by DaniyalDolare** [comment]
@AnassErraidi can you also give the sign in page ui code which is calling the sign in code. I think there might be some issue.
Or the lines googleSignIn.disconnect();  auth.signOut(); are causing issue.

**Comment by darshankawar** [comment]
@AnassErraidi 
Check above comments / solution and see if it works in your case or not.
Also see [this](https://stackoverflow.com/questions/71805651/flutter-google-login-pop-up-wont-appear-to-select-an-account) link and check if it helps.

**Comment by AnassErraidi** [comment]
do you add this line to index.html
 <meta name="google-signin-client_id"
          content="webClientId.apps.googleusercontent.com">

**Comment by DaniyalDolare** [comment]
@AnassErraidi 
I have found your issue.
I went to your deployed website and open the console to see any error are thrown or not. So here is the error I got
```
[firebase_auth/unauthorized-domain] This domain is not authorized for OAuth operations for your Firebase project. Edit the list of authorized domains from the Firebase console.
iframe.js:300 Info: The current domain is not authorized for OAuth operations. This will prevent signInWithPopup, signInWithRedirect, linkWithPopup and linkWithRedirect from working. 
Add your domain (myshopforall.web.app) to the OAuth redirect domains list in the Firebase console -> Authentication -> Settings -> Authorized domains tab.
```

So you just have to add your domain in firebase console as instructed. There is no issue in the code or any package. Hope it helps.
Close the issue if solved.

**Comment by darshankawar** [comment]
Closing as resolved based on above comment.
