### ISSUE TITLE
Is it possible to send segment events data directly to Algolia?

### ISSUE THREAD

**Issue by jeyaraman22** [flutter/flutter#126311]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

while going through algolia documentation, came across this page, which mentions that we can configure the segment to send events data directly to algolia.
- while sending events to segment we have to pass the algolia params as mentioned below:

analytics.track('Product Clicked', {
  product_id: '507f1f77bcf86cd799439011',
  sku: 'G-32',
  category: 'Games',
  name: 'Monopoly: 3rd Edition',
  brand: 'Hasbro',
  variant: '200 pieces',
  price: 18.99,
  quantity: 1,
  coupon: 'MAYDEALS',
  position: 3,
  url: 'https://www.example.com/product/path',
  image_url: 'https://www.example.com/product/path.jpg',

 /// Algolia-related properties
 index: 'my-algolia-index',
eventType: 'click',
queryID: 'fd0bbaadc287937s7671d00f1d053b88',
objectID: '131280270'
});

but we couldn't able to get any of the above required params from the flutter algolia plugins ( in my case I've used algolia_helper_flutter: ^0.2.3).

Ref link: https://www.algolia.com/doc/guides/sending-events/connectors/segment/

NOTE: All the segment and algolia configurations were properly done as per the documents.

### Proposal

Expection: Need the algolia params to pass along with segment events data.

**Comment by danagbemava-nc** [comment]
Hi @jeyaraman22, `algolia_flutter_helper` is a third-party plugin. Any issues you face using it should've reported on their [repo](https://github.com/algolia/algoliasearch-helper-flutter/issues?q=is:issue+is:open+sort:updated-desc). 

Closing from here as this is not a flutter issue. 

Thank you
