### ISSUE TITLE
[web:a11y] primary/secondary role managers

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#126384]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

This is a technical debt issue, not a bug report or a feature request.

Each `SemanticsObject` may have zero or more roles associated with it. Which ones are assigned depends on the combination of flags and actions. This works, but code readability isn't great. For instance, it's not clear who is responsible for the `role` ARIA attribute. Any role manager can assign one, potentially stepping on another role manager. It's not clear in what order role managers are updated.

A better approach might be to assign one _primary_ role, and internally the primary role manager may add as many _secondary_ role managers as it needs. Only the primary role is responsible for assigning the `role` label. It also determine the order, in which it and secondary role managers update the node.

Examples:

* Primary role "button" may have secondary roles "labelled" and "focusable".
* Primary role "text" may have secondary role "labelled". It _may_ also add "focusable" if `isFocusable` is set on the object.
* Primary role "text field" may not have any secondary roles because of bespoke needs for labelling, focus management, etc.

### Expected results

Cleaner code

### Actual results

Code not so clean

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by fideldonson** [comment]
I would add that the ARIA role="text" is not a valid value for the role attribute. It is not supported in major browsers and Safari - where it actually had an effect - recently removed support for it.

**Comment by yjbanov** [comment]
role="text" was fixed as part of a separate issue. This issue is also done now.
