### ISSUE TITLE
Tree closed on new pigeon analyzer lint

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#126393]
The tree is closed on an analysis failure in the pigeon example app https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20flutter_plugins/12113/overview.

The version of analyzer it depends on now resolves to 5.12.0 where previously it resolved to 5.11.1. Not sure who the right owner is here but cc @dkwingsmt  the gardener and @stuartmorgan.

**Comment by stuartmorgan** [comment]
Re-opening since the manual roll needs to land in flutter/flutter before it's fully fixed.
