### ISSUE TITLE
[autosubmit] Issue incorrectly closed when using "Part of" in PR description

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#126356]
https://github.com/flutter/flutter/issues/126002 was closed due to https://github.com/flutter/flutter/pull/126012.

I wouldn't have expected anything in that description to indicate the issue should be closed, as there's a few more PRs that need to be sent.

**Comment by CaseyHillers** [comment]
\cc @ricardoamador

**Comment by keyonghan** [comment]
I don't think this is handled by autosubmit bot. Should be something on GitHub side.

**Comment by ricardoamador** [comment]
Yeah I did a code search and cannot find anything. Let me look at the setting for github to see if there are any rules that are doing this.

**Comment by CaseyHillers** [comment]
I think what confuses me is the GitHub docs in https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword don't mention this

**Comment by keyonghan** [comment]
> It is odd that the closed issue (the one referenced in the 'Part of' line) says it was closed by autosubmit.

An issue, auto closed by merging a PR, is closed by the `author` who merged the PR. So this makes sense as closed by autosubmit. The problem is how this issue was triggered by the PR:thinking:, where casey's posted doc doesn't mention anything from GitHub side.

**Comment by ricardoamador** [comment]
I think I found the issue. You linked the issue but not by a keyword.
![image](https://github.com/flutter/flutter/assets/32242716/2621641d-53ca-477f-8484-b88676408ad4)
I believe this is why it was merged automatically.

**Comment by ricardoamador** [comment]
Anyone with write access can make this link unfortunately so it may not have been you. I am not sure if there is a paper trail for this though. I am going to close this is as not an issue.

**Comment by CaseyHillers** [comment]
Thanks Ricardo for investigating! I'll mark this as closed as it seems like user error.
