### ISSUE TITLE
Replace "Android" with "Mountain View" in gallery on iOS

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#12637]
Our build of Gallery targeting App Store should not mention Android. Right now, to accomplish this, I manually comment out aspects of the source code.

This is a request to change the source code (somehow) such that I can build and publish the Gallery without manually modifying the source code, and have a high chance of approval.

**Comment by sethladd** [comment]
One suggestion was to create a new entry point (another .dart file) which I can pass to `flutter build` or `flutter run`, and this new .dart only link/import in aspects of the app required for App Store.

**Comment by sethladd** [comment]
That is probably also a sufficient solution. :) I will update the title of this issue to be more focused on the problem.

**Comment by cbracken** [comment]
Fixed by #12699
