### ISSUE TITLE
Support single-threaded fallback for Skwasm renderer

### ISSUE THREAD

**Issue by eyebrowsoffire** [flutter/flutter#126351]
For browser that do not fully support `OffscreenCanvas` and rendering on a web worker, we need a fallback that allows us to just do all our rendering on the main thread and not spawn a web worker.

**Comment by Oleh-Sv** [comment]
Do such browsers still exist?

**Comment by eyebrowsoffire** [comment]
> Do such browsers still exist?

Yes. Notably, Safari does not support WebGL in their OffscreenCanvas API, and therefore you can't use WebGL on a web worker. Also, even for browsers that do support `OffscreenCanvas`, we need this fallback to support applications that run in a non-`crossOriginIsolated` context, as `crossOriginIsolated` is required for multi-threaded wasm modules (`SharedArrayBuffer` support essentially). See https://developer.mozilla.org/en-US/docs/Web/API/crossOriginIsolated

**Comment by Oleh-Sv** [comment]
@eyebrowsoffire JFYI Safari supports webGL in OffscreenCanvas from version 17.0 (actual version)

**Comment by eyebrowsoffire** [comment]
This was fixed with https://github.com/flutter/engine/pull/56282

Note that this doesn't mean skwasm/wasm is supported on Firefox and Safari yet, there are still some more changes to make it compatible with non-Chromium browsers. But we do now ship a single-threaded variant of the skwasm renderer that works in non-crossOriginIsolated browsing contexts.
