### ISSUE TITLE
When Nested List , First list is Vertical then 2nd  scrollDirection: Axis.horizontal,

### ISSUE THREAD

**Issue by xaakib** [flutter/flutter#126323]
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════
'package:flutter/src/widgets/overscroll_indicator.dart': Failed assertion: line 243 pos 14: 'notification.metrics.axis == widget.axis': is not true.
overscroll_indicator.dart:243
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════
'package:flutter/src/widgets/overscroll_indicator.dart': Failed assertion: line 243 pos 14: 'notification.metrics.axis == widget.axis': is not true.
overscroll_indicator.dart:243
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════
'package:flutter/src/widgets/overscroll_indicator.dart': Failed assertion: line 243 pos 14: 'notification.metrics.axis == widget.axis': is not true.
overscroll_indicator.dart:243
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════
'package:flutter/src/widgets/overscroll_indicator.dart': Failed assertion: line 243 pos 14: 'notification.metrics.axis == widget.axis': is not true.
overscroll_indicator.dart:243
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════
'package:flutter/src/widgets/overscroll_indicator.dart': Failed assertion: line 243 pos 14: 'notification.metrics.axis == widget.axis': is not true.

**Comment by huycozy** [comment]
@xaakib 
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly.

More specifically, please provide the information indicated below:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of `flutter doctor -v`
- Reproduction steps, Expected results, Actual results
- Which environment did this issue happen in? (Android/iOS/Web/MacOS/Windows/Linux)

Thank you!

**Comment by DaniyalDolare** [comment]
You havent added any code, just pasted the error. Buts here what you are looking for:
Using nested lists, these error are common, It's mainly because the size of the list is unknown before rendering and flutter can't render something whose size in unknown in a widget whose size is unbounded like Column or Row, Try wrapping list in SizedBox and give some size to it or else use Expanded or Flexible widgets.

**Comment by yazanalkamsheh** [comment]
This error is the result of using a list within another list. I solved the problem by surrounding the inner list with a NotificationListener<ScrollNotification>(
     onNotification: (ScrollNotification notify) {
      return true;
      }

> ════════════════════════════════════════════════════════════════════════════════
> 
> ════════ Exception caught by gesture ═══════════════════════════════════════════ 'package:flutter/src/widgets/overscroll_indicator.dart': Failed assertion: line 243 pos 14: 'notification.metrics.axis == widget.axis': is not true. overscroll_indicator.dart:243 ════════════════════════════════════════════════════════════════════════════════
> 
> ════════ Exception caught by gesture ═══════════════════════════════════════════ 'package:flutter/src/widgets/overscroll_indicator.dart': Failed assertion: line 243 pos 14: 'notification.metrics.axis == widget.axis': is not true. overscroll_indicator.dart:243 ════════════════════════════════════════════════════════════════════════════════
> 
> ════════ Exception caught by gesture ═══════════════════════════════════════════ 'package:flutter/src/widgets/overscroll_indicator.dart': Failed assertion: line 243 pos 14: 'notification.metrics.axis == widget.axis': is not true. overscroll_indicator.dart:243 ════════════════════════════════════════════════════════════════════════════════
> 
> ════════ Exception caught by gesture ═══════════════════════════════════════════ 'package:flutter/src/widgets/overscroll_indicator.dart': Failed assertion: line 243 pos 14: 'notification.metrics.axis == widget.axis': is not true. overscroll_indicator.dart:243 ════════════════════════════════════════════════════════════════════════════════
> 
> ════════ Exception caught by gesture ═══════════════════════════════════════════ 'package:flutter/src/widgets/overscroll_indicator.dart': Failed assertion: line 243 pos 14: 'notification.metrics.axis == widget.axis': is not true.

This error is the result of using a list within another list. I solved the problem by surrounding the inner list with a 
`NotificationListener<ScrollNotification>(
   onNotification: (ScrollNotification notify) {
         return true;
  }`

**Comment by yazanalkamsheh** [comment]
> ════════════════════════════════════════════════════════════════════════════════
> 
> ════════ Exception caught by gesture ═══════════════════════════════════════════ 'package:flutter/src/widgets/overscroll_indicator.dart': Failed assertion: line 243 pos 14: 'notification.metrics.axis == widget.axis': is not true. overscroll_indicator.dart:243 ════════════════════════════════════════════════════════════════════════════════
> 
> ════════ Exception caught by gesture ═══════════════════════════════════════════ 'package:flutter/src/widgets/overscroll_indicator.dart': Failed assertion: line 243 pos 14: 'notification.metrics.axis == widget.axis': is not true. overscroll_indicator.dart:243 ════════════════════════════════════════════════════════════════════════════════
> 
> ════════ Exception caught by gesture ═══════════════════════════════════════════ 'package:flutter/src/widgets/overscroll_indicator.dart': Failed assertion: line 243 pos 14: 'notification.metrics.axis == widget.axis': is not true. overscroll_indicator.dart:243 ════════════════════════════════════════════════════════════════════════════════
> 
> ════════ Exception caught by gesture ═══════════════════════════════════════════ 'package:flutter/src/widgets/overscroll_indicator.dart': Failed assertion: line 243 pos 14: 'notification.metrics.axis == widget.axis': is not true. overscroll_indicator.dart:243 ════════════════════════════════════════════════════════════════════════════════
> 
> ════════ Exception caught by gesture ═══════════════════════════════════════════ 'package:flutter/src/widgets/overscroll_indicator.dart': Failed assertion: line 243 pos 14: 'notification.metrics.axis == widget.axis': is not true.

This error is the result of using a list within another list. I solved the problem by surrounding the inner list with a NotificationListener<ScrollNotification>(
     onNotification: (ScrollNotification notify) {
      return true;
