### ISSUE TITLE
[Impeller] Blur BackdropFilter performance degradation.

### ISSUE THREAD

**Issue by vjamrich** [flutter/flutter#126353]
## Details

**Target Platform:** iOS
**Target OS version/browser:** iOS 16.3.1 (20D67)
**Devices:** iPhone 12

Usage of multiple `BackdropFilter()` widgets with `ImageFilter.blur()` in a `ListView()` has significantly degraded performance on Impeller compared to Skia. In the example below, the widget tree contains 5 identical stateless widgets with a `BackdropFilter()` child widget.

1. **Skia:** Raster thread average 6ms/frame, max 5ms/frame ([screenshot](https://github.com/flutter/flutter/assets/59235105/9e538146-5be2-41bc-91fe-0bd903f10c08))
2. **Impeller:** Raster thread average 16ms/frame, max 24ms/frame ([screenshot](https://github.com/flutter/flutter/assets/59235105/36de820f-2bfb-40fd-b4cf-0bc45b3edec4))

Interestingly, the Impeller started dropping frames (increased max to 24ms/frame) after approximately 15 seconds of scrolling up and down on the spot.

```
import 'dart:ui';

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}


class MyApp extends StatelessWidget {

  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: "BackdropFilter() Performance",
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}


class MyHomePage extends StatelessWidget {

  const MyHomePage({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("BackdropFilter() Performance"),
      ),
      body: Stack(
        fit: StackFit.expand,
        children: <Widget>[
          Image.network(
            "https://docs.flutter.dev/assets/images/dash/Dash.png",
            fit: BoxFit.cover,
          ),
          ListView.builder(
            physics: const AlwaysScrollableScrollPhysics(),
            itemCount: 5,
            itemBuilder: (BuildContext context, int index) {
              return const Padding(
                padding: EdgeInsets.all(8.0),
                child: BlurredContainer(),
              );
            },
          ),
        ],
      ),
    );
  }
}


class BlurredContainer extends StatelessWidget {

  final double height;
  final double width;

  const BlurredContainer({
    this.height = 50.0,
    this.width = double.infinity,
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {

    const double sigma = 10.0;

    return ClipRect(
      child: BackdropFilter(
        filter: ImageFilter.blur(sigmaX: sigma, sigmaY: sigma),
        child: Container(
          height: height,
          width: width,
          color: Colors.white30,
        ),
      ),
    );
  }
}

```

## Logs

<details>
<summary>Logs</summary>

```
No issues found! (ran in 4.1s)
```

```
[✓] Flutter (Channel stable, 3.7.10, on macOS 13.0 22A380 darwin-x64, locale en-GB)
    • Flutter version 3.7.10 on channel stable at /usr/local/Caskroom/flutter/3.0.5/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b12645012 (5 weeks ago), 2023-04-03 17:46:48 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/macbook/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2022.1.4)
    • IntelliJ at /Users/macbook/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.6008.13/IntelliJ IDEA CE.app
    • Flutter plugin version 69.0.4
    • Dart plugin version 221.5921.27

[✓] IntelliJ IDEA Community Edition (version 2022.3.1)
    • IntelliJ at /Users/macbook/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/223.8214.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • Viktor’s iPhone 12 (mobile) • 00008101-00080C182229001E • ios            • iOS 16.3.1 20D67
    • macOS (desktop)             • macos                     • darwin-x64     • macOS 13.0 22A380 darwin-x64
    • Chrome (web)                • chrome                    • web-javascript • Google Chrome 112.0.5615.137
    ! Error: Viktor’s iPhone 12 is busy: Fetching debug symbols for Viktor’s iPhone 12. Xcode will continue when Viktor’s iPhone 12 is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by zanderso** [comment]
@vjamrich Thanks!

@flar @bdero Wondering if this is addressed by the recent fixes on master channel?

**Comment by vjamrich** [comment]
> That said, you should really just use an ImageFIltered and not stack a backdrop filter

Using ImageFiltered would unfortunately not be a valid solution as it only applies filter to it's child rather then the content underneath. Therefore, it would not result in the same 'frosted glass' effect as showed in the example above (effect widely popularized and available in iOS)

**Comment by jonahwilliams** [comment]
You can absolutely express these sorts of effects with an ImageFiltered, though you may need to re-arrange the widget tree.

**Comment by spkersten** [comment]
@jonahwilliams How you that work in cases like this: 

https://github.com/flutter/flutter/assets/4456832/c5881191-3efd-4d7d-a0a6-49772bb8d9b7

**Comment by jonahwilliams** [comment]
I think that is a completely reasonable way to use a backdrop filter, but it also doesn't look anything like the example you posted above? Can you show us how you are using the backdrop filter in your applicaiton?

**Comment by vjamrich** [comment]
> it also doesn't look anything like the example you posted above

I apologize for the confusion, the example you are referring to was not posted by me (the author of this issue). The provided code aims to highlight the performance degradation rather then showcase the specific scenarios of how BackdropFilter is used within my app.

> Can you show us how you are using the backdrop filter in your applicaiton?

Please see the wireframe below for the different uses of the BackdropFilter within my app.
The background on each screen (1.) consists of a stateful widget, which changes colour, shape, and size based on various user interactions such as scroll location.
All orange elements within a wireframe contain a BackdropFilter widget and are animated based on user interaction.

The first example shows the BackdropFilter widgets (2.) (max 5 at the same time) in a ListView (please note the background is animated and does not consist of a stateless widget). In the second example, a modal (3.) is displayed on top.

The third example contains a 'Tinder' like swipeable cards (4.) stacked on top of each other (maximum two at the same time)

![backdrop_examples](https://github.com/flutter/flutter/assets/59235105/f2833ab7-2c39-45fa-b30d-074fbd87c3fb)

Overall, while in some cases the widget tree can be rearranged to achieve a similar effect using ImageFiltered, this solution is not viable when using widgets from third-party libraries. Further more, this renders the usage of multiple Cupertino widgets at once unusable. This poses as a risk, as according to the [Flutter 2023 roadmap](https://github.com/flutter/flutter/wiki/Roadmap) we plan to make a signifficant progress in updating and growing set of the Cupertino widgets.

> we expect to make significant progress on our Cupertino widget set this year, bringing it up to date and growing the number of supported widgets

**Comment by jonahwilliams** [comment]
Sorry for the mixup! In your example, it seems like there would only be one backdrop filter "active" at a time, right? or do you keep the backdrop filters in the tree with a sigma of 0?

**Comment by vjamrich** [comment]
All of the BackdropFilter widgets in the example above would be 'active' as they are always visible. E.g. in the stack the cards are not fully overlapping (the user can see both of them at the same time) and therefore setting sigma to 0 to one of them would not work. The same goes for modal as the background behind the modal is transparent.

In other pages though I try to set the sigma to 0 whenever the widget would not be directly visible.

**Comment by jonahwilliams** [comment]
Makes sense, I have a few ideas here. I'll use the example code you posted above

**Comment by chinmaygarde** [comment]
This is fixed in https://github.com/flutter/engine/pull/42039. @bdero There was some concern that this was too big to cherry-pick. Can you provide guidance on viability for cherry-picking?

**Comment by bdero** [comment]
I don't have a strong opinion about whether we cherry-pick this or not. Most of the PR is just adding an item to the Contents API surface.
