### ISSUE TITLE
Failure to validate Provenance is causing cocoon builds to fail deployment

### ISSUE THREAD

**Issue by ricardoamador** [flutter/flutter#126343]
The 'Verify Provenance' step is failing for the daily cocoon builds causing it to not be deployed.
https://pantheon.corp.google.com/cloud-build/builds;region=global/a24eaca6-7e47-45c6-8d0d-52be01e9d322;step=1?project=flutter-dashboard
Last deploy was May 5th.

**Comment by drewroengoogle** [comment]
It seems that a new version of slsa-verifier has an extra dependency that isn't automatically installed? Taking a further look to see why that's the case.

**Comment by drewroengoogle** [comment]
Short term fix - Rolled back commit that caused failure, blocked dependabot from updating. Lowering priority

Long term fix, I'll open an issue with slsa-verifier to see if they have any insight
