### ISSUE TITLE
Failed assertion:  '!_dirty': is not true.

### ISSUE THREAD

**Issue by gaabrielricci** [flutter/flutter#126361]
```
class SelectPicker2State extends State<SelectPicker2> {
  String selectedItem = "";
  
  @override
  void didUpdateWidget(covariant SelectPicker2 oldWidget) {
    listToShow = widget.list;
    if (mounted) {
      setState(() {});
    }

    if (oldWidget.list.length == 0) {
      if (widget.initialItem != null && widget.initialItem != "") {
        _selectInitialItem();
      }
    }

    super.didUpdateWidget(oldWidget);
  }


 _selectInitialItem() {
      for (SelectPickerIten? element in listToShow) {
        if (element != null && element.id == widget.initialItem && widget.initialItem != null && widget.initialItem != "") {
          **selectedItem = "${element.id} - ${element.title}";
          widget.onSelect(element);**
          break;
        }
      }
  }

}
```

if i coment this line:
          **selectedItem = "${element.id} - ${element.title}";
          widget.onSelect(element);**
the error stop

**Comment by gaabrielricci** [comment]
Apologies for the delay. I'm not able to reproduce the error in a new project to share all the code, but I've identified exactly where the problem occurs. I have a customized SelectPicker that receives an "onSelect" function as a parameter, and in didUpdateWidget I eventually execute this function, it is at this moment that the problem is occurring, the function is not nullable, however in the first call of didUpdateWidget it is null, and that's where the error happens


![doctor](https://github.com/flutter/flutter/assets/27814206/3b3ee50b-8d09-4623-8628-d66c0933c3de)
flutter doctor
![did](https://github.com/flutter/flutter/assets/27814206/60ea68c8-0d6d-42b7-bc3a-aeede120fd65)
code

**Comment by darshankawar** [comment]
> I have a customized SelectPicker that receives an "onSelect" function as a parameter, and in didUpdateWidget I eventually execute this function, it is at this moment that the problem is occurring, the function is not nullable, however in the first call of didUpdateWidget it is null, and that's where the error happens

Thanks for the update @gaabrielricci Would be good to provide a text format code snippet for this so that we can make this issue actionable. Also please verify if you are able to see the same issue on latest stable or master as well or not.
