### ISSUE TITLE
When errors are thrown in `initState`/`didUpdateWidget`/etc, the error message says "The following ... was thrown building Widget" which is confusing, thus may add more error boundaries

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#126328]
Just "proposal 2" of https://github.com/flutter/flutter/issues/126310, created as a separated issue since @darshankawar suggests

> Mimic how we catch errors for the "build" to add a few error try-catch blocks for initState/didUpdateWidget.
Drawback: May make performance worse.

More specifically, currently the try-catch seems a bit too coarse - that's why initState/didUpdateWidget/etc only says "thrown *building* widget" instead of "thrown in *initState*". By adding more try-catch, this can be avoided.

**Comment by fzyzcjy** [comment]
@huycozy Hi, please refer to https://github.com/flutter/flutter/issues/126310#issuecomment-1539621078 for why I do this :)

**Comment by huycozy** [comment]
Hi @fzyzcjy 
Yes, I have read the linked issue :), but it doesn't to be clear about what should it be.

>Proposal 2: More error boundaries
Mimic how we catch errors for the "build" to add a few error try-catch blocks for initState/didUpdateWidget.
Drawback: May make performance worse.

It seems there are already some error catches on the `build` currently. So it would be appreciated if you also could add them here to make the proposal more transparent and easy to understand. Thank you!

**Comment by fzyzcjy** [comment]
Post edited :)

**Comment by goderbauer** [comment]
Don't you get a stack trace with those errors that shows you the exact method that was throwing? IMO, that should be enough information and technically the initState/didUpdateWidget/etc are all happening in the BUILD phase.

**Comment by goderbauer** [comment]
I am going to close this one then since the stack trace is pretty explicit.
