### ISSUE TITLE
20% increase in time in GC in complex_layout_scroll_perf_bad

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#126337]
SkiaPerf is reporting that the change here: https://github.com/flutter/flutter/pull/125656

Caused the benchmark to spend roughly 20% more time doing GC on the UI thread.

https://flutter-flutter-perf.skia.org/e/?begin=1683112223&end=1683159967&keys=X21c0a020b979825e3cfa2d1dca24743a&num_commits=50&request_type=1&xbaroffset=34681

It looks like this did not effect frame rate, but would cause e.g. increased CPU utilization.

Looking at the change, I wonder if usage of the new Dart 3 pattern matching features causes more object allocation.

cc @LongCatIsLooong @goderbauer @jonahwilliams

**Comment by LongCatIsLooong** [comment]
Looks like the changes made to text_span.dart caused it. I'll revert that part.
