### ISSUE TITLE
Because flutter_tools depends on shelf 1.4.0 which doesn't match any versions, version solving failed

### ISSUE THREAD

**Issue by Mhdmidhlaj** [flutter/flutter#126321]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

flutter doctor
git clone -b master https://github.com/flutter/flutter.git

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>
>flutter doctor Building flutter tool... Running pub upgrade... Because flutter_tools depends on shelf 1.4.0 which doesn't match any versions, version solving failed. Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left) Waiting for 1 seconds, press CTRL+C to quit ..

### Flutter Doctor output

Resolving dependencies in ..\..\languages\flutter\packages\flutter_tools... (2.4s)
Because flutter_tools depends on shelf 1.4.0 which doesn't match any versions, version solving failed.
pub get failed

**Comment by huycozy** [comment]
Hi @Mhdmidhlaj, 
I try adding `shelf: 1.4.0` to the project but it can be added normally without issue. Could you provide the output of `flutter doctor -v`?
