### ISSUE TITLE
My application user interface cannot be displayed on some Windows 10 PCs

### ISSUE THREAD

**Issue by RellyLee** [flutter/flutter#126424]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Building Applications

### Expected results

My application user interface can be displayed on all Windows 10 PCs
![image](https://github.com/flutter/flutter/assets/16131563/53a1471c-48b1-4680-9aea-7ed373704fb5)

### Actual results

My application user interface  cannot be displayed on some Windows 10 PCs
![image](https://github.com/flutter/flutter/assets/16131563/ba207942-6aa8-45f9-975c-11a6c334e6b2)

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Hi @RellyLee 
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly.

Please check if the issue also occurs on a new Flutter project. If it's not reproducible, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well.

Thank you!

**Comment by RellyLee** [comment]
> Hi @RellyLee When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly.
> 
> Please check if the issue also occurs on a new Flutter project. If it's not reproducible, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well.
> 
> Thank you!

I found that this issue is caused by the power policy of Windows. When my laptop is unplugged and the power mode is in balanced mode, the client user interface will not be displayed when I restart it. When I set the power mode to high-performance mode, the client user interface will display when I restart it. How should I set the user interface to display in any power mode in the client code?

**Comment by RellyLee** [comment]
> Hi @RellyLee When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly.
> 
> Please check if the issue also occurs on a new Flutter project. If it's not reproducible, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well.
> 
> Thank you!
@huycozy 
I found that this issue is caused by the power policy of Windows. When my laptop is unplugged and the power mode is in balanced mode, the client user interface will not be displayed when I restart it. When I set the power mode to high-performance mode, the client user interface will display when I restart it. How should I set the user interface to display in any power mode in the client code?

**Comment by huycozy** [comment]
This is quite strange. Is it possible that it is related to a plugin you are using? Can you check if the issue happens on a new Flutter project (counter app)? 

Also, which Flutter version are you using? Please provide the output of `flutter doctor -v`.

**Comment by RellyLee** [comment]
@huycozy
The version of Flutter I am using is 3.7.12. Additionally, I attempted to run a new Flutter program on a laptop with this issue and found that the program could not start

**Comment by huycozy** [comment]
Can you please check if there are any special logs from the output console? Please provide the complete output of `flutter run -v` so that we may verify the issue. 

And it would be appreciated if you could also verify this on the latest stable and master channels as well. Thank you!

```
flutter channel master
flutter upgrade
```
