### ISSUE TITLE
LUCI presubmit status not being communicated to GitHub checks

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#126450]
On https://github.com/flutter/flutter/pull/126445, I am seeing that the GitHub checks are unresolved, but when I click through to the LUCI status, the build has finished successfully.

Here's an example: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20engine_dependency_proxy_test/1213/overview.

**Comment by sealesj** [comment]
Looking into this

**Comment by godofredoc** [comment]
This is on github side https://www.githubstatus.com/incidents/pr3498h3qkfy

**Comment by godofredoc** [comment]
Please retry impacted builds.

**Comment by zanderso** [comment]
@godofredoc This probably deserves an announcement to the team, so that people know what is going on.

**Comment by godofredoc** [comment]
From our side there is no much we can do apart from retrying the build to send the status signal back. In these cases LUCI and flutter infra generate the right signals but github decides to ignore them.

**Comment by godofredoc** [comment]
@sealesj can you please send a PSA with the link to the github outage notifying that check updates may be ignored by github.

**Comment by keyonghan** [comment]
@sealesj You may also want to include go/flutter-luci-playbook#manually-trigger-try-pre-submit-builds in the PSA to allow people an easy rerun on missing checks.

**Comment by godofredoc** [comment]
Not without some additional work to keep state mapping one to one from github check api ids to luci builds. The current communication flow goes like this:

* Something happens at github and it sends a webhook event that cocoon communicates to LUCI
* LUCI generates a new build and communicates async to cocoon using pubsub
* cocoon processes pubsub messages build started, finished, failed and send messages to github to update the checks
* no state is saved mapping check ids to LUCI builds

**Comment by keyonghan** [comment]
> But I think we can optimize the process from cocoon API: before triggering a new build, check if any existing build. If yes and the status is pass, we can simply update the check run status. Created https://github.com/flutter/flutter/issues/126458 to track this feature request.

Thanks @godofredoc for the context, as of now we are not tracking checkrun ids. This optimization is not possible unless extra infra support on checkrun+build mapping. Added this to the tracking bug.

**Comment by mdebbar** [comment]
What if we ask the LUCI team to add a button to resend the pubsub message?

**Comment by keyonghan** [comment]
> What if we ask the LUCI team to add a button to resend the pubsub message?

Pubsub message is maintained from cocoon, and LUCI doesn't handle that.

**Comment by keyonghan** [comment]
Seems github is still hitting outages. This needs monitoring.

**Comment by sealesj** [comment]
Since the original github outages have recovered, closing this and keeping open our tracking for future work at https://github.com/flutter/flutter/issues/126458
