### ISSUE TITLE
Linux analyzer_benchmark timeout set to 60 minutes, but killed after 30 minutes

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#126451]
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20analyzer_benchmark/2658/overview

https://github.com/flutter/flutter/blob/master/.ci.yaml#L201

Marking P1 because this will intermittently be closing the tree until the ci.yaml setting is respected.

**Comment by keyonghan** [comment]
The target `timeout` is the whole build execution time limit, whereas the test step is confined by `test_timeout_secs` property (similar to https://github.com/flutter/flutter/blob/master/.ci.yaml#L866).

The infra is missing the doc. @sealesj Could you help update https://github.com/flutter/cocoon/blob/main/CI_YAML.md to include the info about the above two timeout? That way test owners are able to self service on updating these numbers.

**Comment by keyonghan** [comment]
Infra property `test_timeout_secs` should do the trick. @zanderso please give it a shot, and let us know if we are missing anything from the doc or anything else.

**Comment by keyonghan** [comment]
I am removing the ticket queue. Please add it back if anything else is needed.

**Comment by zanderso** [comment]
Wondering if it's possible to make the property types/meanings more consistent? In particular, I see that `timeout` is an integer valued number of minutes, and `test_timeout_secs` is a string valued number of seconds. Could they both be the same type and units?

**Comment by keyonghan** [comment]
> Wondering if it's possible to make the property types/meanings more consistent? In particular, I see that timeout is an integer valued number of minutes, and test_timeout_secs is a string valued number of seconds. Could they both be the same type and units?

This is some technical debt we can improve. We can change `unit` for sure, but as for `type`, we need to look into how yaml file is being parsed from cocoon backend. Created https://github.com/flutter/flutter/issues/126592 to track.
