### ISSUE TITLE
Regression with web build size tests

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#126478]
## skiaperf

https://flutter-flutter-perf.skia.org/e/?begin=1683669749&end=1683752296&keys=X5fca5a031b9159f9008ccc2a5e12abae&num_commits=50&request_type=1&xbaroffset=34777

## introduced in PR

https://github.com/flutter/flutter/pull/126445

**Comment by gaaclarke** [comment]
cc @eyebrowsoffire since the only web pr in that roll was his

**Comment by eyebrowsoffire** [comment]
This is expected, because we added text rendering support to skwasm, which increased the binary size. The build directory will be slightly larger, but this doesn't actually affect download size for anything that isn't building against wasm.
