### ISSUE TITLE
GridView render bug (device specific)

### ISSUE THREAD

**Issue by joechan-cq** [flutter/flutter#126492]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

A simple gridview-example on MIX2 with Flutter 3.x.

### Expected results

Gridview render normally.

### Actual results

On the top and bottom line of GridView, it renders error. It seems that render was effected by the overscroll-inkwell.

It is ok if `childAspectRatio` was setted to > 1.0.
It occurs only on Flutter3.x (I test 3.0.5 and 3.7.11), on Flutter2.5.3, It's ok.

I think the bug is device-specific, my device is MIX2 which is lineageos(Android 11), 5.99 inch display, 1080x2160 resolution, 400dpi. Another device(MIX2S) is ok. 

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

class GridLogDemo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    var colors = [
      Colors.red,
      Colors.black,
      Colors.blue,
      Colors.green,
      Colors.pink
    ];
    return Scaffold(
      appBar: AppBar(
        title: const Text('GridView'),
      ),
      body: Container(
        child: GridView.builder(
          gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
            crossAxisCount: 3,
            childAspectRatio: 1.0,
          ),
          itemBuilder: (BuildContext context, index) {
            return Container(
              color: colors[index % 5],
              child: Center(
                child: Text(
                  '这是第$index个视图',
                  style: TextStyle(color: Colors.white),
                ),
              ),
            );
          },
          itemCount: 100,
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Video demonstration</summary>

https://github.com/flutter/flutter/assets/9456005/44a602ac-905e-4e21-8f04-a2e059501a2f

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.11, on macOS 13.2.1 22D68 darwin-arm64
    (Rosetta), locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 14.2)
    ! CocoaPods 1.10.1 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.78.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

```

</details>

**Comment by darshankawar** [comment]
@joechan-cq 
Good that you mentioned `LineageOS` which led me to [this](https://github.com/flutter/flutter/issues/105093) open issue which I think is the same one you are facing.
So please follow-up in that issue for further updates. You may also share your findings in that issue for better tracking.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.
