### ISSUE TITLE
Medium now requires login to read the release blog post

### ISSUE THREAD

**Issue by TheCarpetMerchant** [flutter/flutter#126459]
The [3.10 announcement](https://medium.com/flutter/whats-new-in-flutter-3-10-b21db2c38c73) requires login in to a Medium account to read.
Please move away from Medium so information about Flutter is accessible to all.

**Comment by TahaTesser** [comment]
Hi @TheCarpetMerchant 
This was fixed, you shouldn't need a login now to read the release blog post.
