### ISSUE TITLE
hi i have a problem your CarouseSlider

### ISSUE THREAD

**Issue by phloxtreme** [flutter/flutter#126457]
![Screenshot_21](https://github.com/flutter/flutter/assets/101604125/425dd84c-dedb-4500-81c4-180863f04bbc)

**Comment by phloxtreme** [comment]
![Screenshot_22](https://github.com/flutter/flutter/assets/101604125/52871cc6-dd58-4f51-ae8b-6a5cfd56c4b1)

**Comment by TahaTesser** [comment]
Hi @phloxtreme 
This is a third-party package, please file an issue on their repository. 
https://github.com/serenader2014/flutter_carousel_slider
