### ISSUE TITLE
flutter 中文 两端对齐无效 textAlign: TextAlign.justify

### ISSUE THREAD

**Issue by giantss** [flutter/flutter#126422]
same problem 

```dart
 Text( '信用卡，相信大家都不陌生，年轻人几乎人手一张，许多年轻人早已经习惯了使用信用卡超前消费，买买买一时爽，一直买买买一直爽？NO！如果信用卡刷爆了还不上，一旦逾期，你知道会有哪些后果吗？', textAlign: TextAlign.justify)
```

expect
![图片](https://user-images.githubusercontent.com/997812/56895294-47f24880-6abb-11e9-8356-e18d6ab721d5.png)

actually 
![图片](https://user-images.githubusercontent.com/997812/56895238-124d5f80-6abb-11e9-8390-8c698b535a7f.png)

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.5.9-pre.44, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.0)
[√] VS Code, 32-bit edition
[√] Connected device (2 available)

• No issues found!

_Originally posted by @ssddi456 in https://github.com/flutter/flutter/issues/29583#issuecomment-487558445_

**Comment by huycozy** [comment]
Thanks for the report! This is a known issue being tracked at https://github.com/flutter/flutter/issues/35734. 

Closing this issue as a duplicate, so please follow up on it for further updates.
