### ISSUE TITLE
Make suggestionsBuilder in SearchAnchor async

### ISSUE THREAD

**Issue by ips-jm** [flutter/flutter#126531]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Hey,
I really like the new SearchBar / SearchAnchor.bar Widget!
However I think most of the suggestions will come from an async api call based on the input instead of prepared datasets.

### Proposal

Something like this would be really nice:
```
SearchAnchor.bar(
  suggestionsBuilder: (context, controller) async {
    final suggestionList = await getSuggestions(controller.text);
    return suggestionList.map((suggestion) => 
      ListTile(
        title: Text(suggestion),
        onTap: () {
          //Some action
        },
      )
    );
  })
```

**Comment by deakjahn** [comment]
Just an aside, I also saw it in the What's new and I'm very much interested but I couldn't find any documentation. You did, apparently... :-)

**Comment by ips-jm** [comment]
> Just an aside, I also saw it in the What's new and I'm very much interested but I couldn't find any documentation. You did, apparently... :-)

Just experimented a bit until it worked tbh :)

**Comment by deakjahn** [comment]
Yup, I've just realized you have to approach it from the anchor. A bit misleading because `SearchBar` itself comes up with the nice UI and then you're stuck, not knowing where to go next. Well, it's too early, it will be documented for sure.

**Comment by deakjahn** [comment]
Anyway, I second, third and more your async request, yes, very important.

**Comment by sun-jiao** [comment]
Hi, @ips-jm and @deakjahn ! I found a temporary solution, just use the `FutureBuilder`:

```
SearchAnchor.bar(
    suggestionsBuilder: (context, controller) {
      final searchFuture = search(controller.text);
      return [FutureBuilder(
        future: searchFuture,
        builder: (context, snapshot){
          if (snapshot.connectionState == ConnectionState.done) {
            final list = snapshot.data;
            if (list != null){
              return ListView.builder(
                shrinkWrap: true,
                physics: const NeverScrollableScrollPhysics(),
                itemCount: list.length,
                itemBuilder: (BuildContext context, int index) {
                  return ListTile(
                    title: Text(list[index]),
                  );
                },
              );
            }
          }
          return const LinearProgressIndicator();
        },
      )];
    },
  )
```

But ... yeah, this is inelegant and odd to place a ListView in a single element List and use it as children of another ListView. That's why I called it temporary.

I'll open a pull request to make it asynchronous.

**Comment by jonmountjoy** [comment]
It would be great if there was some kind of internal guidelines on the design of new UI components.  There are very few that should be synchronous - and search is certainly not one of them.

**Comment by ips-jm** [comment]
Thank you @sun-jiao for all your work! 

Is there an ETA when this will roll out in the stable channel?

**Comment by sun-jiao** [comment]
@ips-jm could you consider closing this issue?
