### ISSUE TITLE
TextField requires two taps to get focus on Flutter Web iOs Safari

### ISSUE THREAD

**Issue by jpiabrantes** [flutter/flutter#126506]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Open https://alpacalaw-a8eb0.web.app/ (a website that uses Flutter Web) on an iOs device
2. Tap the the textfield and try to write

Or watch video below.

### Expected results

Ability to write after one tap.

### Actual results

Needs two taps to be able to write.

### Code sample

It's a simple TextField.

### Screenshots or Video

https://github.com/flutter/flutter/assets/2369107/a9deebef-2d93-43f9-ac77-18b407c11ed9

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.2 22D49 darwin-arm64, locale
    en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 14.2)
    ! CocoaPods 1.10.1 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.2)
[✓] IntelliJ IDEA Community Edition (version 2021.2.4)
[✓] VS Code (version 1.76.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @jpiabrantes, can you upgrade to the latest version of flutter stable (3.10.0) to see if you still experience this issue? I deployed an app using flutter 3.10.0 and I cannot reproduce the bug. See the recording below 

<details>
<summary>recording</summary>

https://github.com/flutter/flutter/assets/88313112/adcf01bb-8ba0-4cc9-a630-c36bfe74e1c5

</details>

**Comment by jpiabrantes** [comment]
Hi @danagbemava-nc , I have upgrade it now and still have the same problem. I have updated the website https://alpacalaw-a8eb0.web.app/ with the new build. Can you reproduce the error on that site? If not, then the difference is the device that we are using.

**Comment by danagbemava-nc** [comment]
Hi @jpiabrantes, I can still reproduce with yours but I cannot reproduce with the site I deployed. Can you check it out here https://bundle-oasis.web.app to see if it reproduces for you on this site as well?

**Comment by jpiabrantes** [comment]
@danagbemava-nc you're right! I have the whole widget tree inside of a `SelectionArea` widget. If I remove the `SelectionArea` then I can no longer reproduce this bug.

**Comment by danagbemava-nc** [comment]
Hi @jpiabrantes, thanks for the update. I can reproduce with the `SelectionArea` on `stable` but it does not seem to reproduce on the `master` channel. 

Can you confirm whether or not it reproduces for you on the `master` channel as well?

Thanks you
