### ISSUE TITLE
Double tap spacebar in a TextField should turn into a period and a space

### ISSUE THREAD

**Issue by megamattron** [flutter/flutter#12652]
On both iOS and Android a common keyboard shortcut is to double tap the space bar to end a sentence. The system basically then translates "  " into ". "

I'm not quite sure why this isn't happening on Flutter, I would have guessed it would be done by the keyboard itself but perhaps it's done by the TextField on each platform.

To replicate this feature currently I am using a TextInputFormatter like this:

```
class DoubleSpaceToPeriodInputFormatter extends TextInputFormatter {
  @override
  TextEditingValue formatEditUpdate(TextEditingValue oldValue, TextEditingValue newValue) {
    // This is pretty lazy and will just keep appending periods if you keep hitting space
    if (newValue.text.endsWith('  ')) {
      final String withPeriod = newValue.text.substring(0, newValue.text.length - 2) + '. ';
      return newValue.copyWith(text: withPeriod);
    }
    return newValue;
  }
}
```

However I'm guessing it's something that should be supported by default to better match text entry behavior with native apps.

**Comment by xster** [comment]
This should be fixed on head. Feel free to re-open if you're still experiencing issues with this.
