### ISSUE TITLE
I've this issue please tell me the solution

### ISSUE THREAD

**Issue by Rafia-Syed** [flutter/flutter#126537]
Checking Android licenses is taking an unexpectedly long time...[☠] Android toolchain - develop for Android devices (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Android toolchain - develop for Android devices exceeded maximum allowed duration of 0:04:30.000000

**Comment by danagbemava-nc** [comment]
Hi @Rafia-Syed, what version of java are you using?

Please provide the full output of `flutter doctor -v` 

Thank you

**Comment by Rafia-Syed** [comment]
> Hi @Rafia-Syed, what version of java are you using?
> 
> Please provide the full output of `flutter doctor -v`
> 
> Thank you

PS C:\WINDOWS\system32> flutter doctor -v
[√] Flutter (Channel stable, 3.7.12, on Microsoft Windows [Version 10.0.19044.2965], locale en-US)
    • Flutter version 3.7.12 on channel stable at E:\MOBILE App Dev\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (3 weeks ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

Checking Android licenses is taking an unexpectedly long time...[☠] Android toolchain - develop for Android devices (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Android toolchain - develop for Android devices exceeded maximum allowed duration of 0:04:30.000000
    •

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33627.172
    X The current Visual Studio installation is incomplete. Please reinstall Visual Studio.

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.2965]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 113.0.5672.92
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 113.0.1774.35

[☠] HTTP Host Availability (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X Exception: HTTP Host Availability exceeded maximum allowed duration of 0:04:30.000000
    •

! Doctor found issues in 3 categories.
this output
and thankyou for replying

**Comment by danagbemava-nc** [comment]
Hi @Rafia-Syed, if you have set a JAVA_HOME value, you can type `java -version` in your command prompt and you will see the version. 

Can you try the solutions in the StackOverflow thread below to see if it helps?

https://stackoverflow.com/questions/73721268/flutter-exception-android-toolchain-develop-for-android-devices-exceeded-max

**Comment by Rafia-Syed** [comment]
Hi @danagbemava-nc 
that's me Java version
C:\Users\pc>java -version
java version "18.0.1.1" 2022-04-22
Java(TM) SE Runtime Environment (build 18.0.1.1+2-6)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.1.1+2-6, mixed mode, sharing)


I checked the StackOverflow but i've this type of error shown below

C:\Users\pc>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.12, on Microsoft Windows [Version 10.0.19044.2965], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.5)
[√] Android Studio (version 2022.2)
[☠] Android Studio (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X FileSystemException: Exists failed, path = ''C:\Program.plugins' (OS Error: The filename, directory name, or
      volume label syntax is incorrect.
      , errno = 123)
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.

**Comment by Rafia-Syed** [comment]
@danagbemava-nc 
Thank you my problem is solved now
