### ISSUE TITLE
[Web] No autofill suggestions for new or existing save passwords

### ISSUE THREAD

**Issue by zs-dima** [flutter/flutter#126574]
Issue reproduced in the Flutter 3.10, latest Chrome browser.

> https://github.com/flutter/flutter/issues/87735

Copied from issue above:
multiple issues with Auto fill feature.

Note : i have already linked the google account and turned on the sync

1. When textfield comes in focus, it didnot open the password suggestions automatically , Note : i have added the code for AutoFillHints.newPassword and tried AutoFillHints.password.
2. When i manually right click password textfield and click the suggest password from the options from context menu, it suggest random password in dropdown but when i click the dropdown, it is not getting populated in the textfied, until if i have some text in the textfield and try the same process again.
3. When i move from the one tab to another and comes back, when i right click and choose the option suggest password , it is not even showing that dropdown for password suggestions.
4. Later i re-run the application and added the password and save it, if i comes back again to sigin screen, it is not proposing me the auto fill options of the email and password which was saved in the google account.

**Comment by huycozy** [comment]
@zs-dima As mentioned on https://github.com/flutter/flutter/issues/87735, it seems it's available on master channel. Please retry on the latest master channel and confirm this. 

```
flutter channel master
flutter upgrade
```
