### ISSUE TITLE
[Impeller] drawVertices/drawPath performance on Impeller

### ISSUE THREAD

**Issue by rlueders** [flutter/flutter#126581]
I am seeing pretty horrible performance on Impeller.  I tired to capture some of the performance issues in the videos below.  I had to compress the videos so much, to meet size constraints, it might be hard to see the differences.   You can probably see that when the 2d elevation profile slides out from the right, there is some jank. Then when opening the 3d elevation profile, there is significant jank.   This is probably harder to tell in the video, but when dragging around the 3d elevation profile on skia, it is supper smooth and responsive. However, on impeller, it is very slow. 

All of this runs supper smooth on skia, but very janky on impeller. These videos were captured on a physical iphone 12 pro max.

https://github.com/flutter/flutter/assets/41687333/b46e7054-c73f-43b2-a580-20411d3c92d1

https://github.com/flutter/flutter/assets/41687333/9785767b-7ab0-4a32-9ef5-dc6d67e16a38

**Comment by rlueders** [comment]
> Do you any code that you can share for this? How are these shapes being drawn? Can you record a timeline trace at least?
> 
> Happy to dig into why this is slower, but I don't have a lot to go off of here. The videos, while illustrative, don't help much unfortunately

The 2d elevation profile is drawn in a customer painter using canvas.drawPath().  The 3d profile is drawn in a customer painter using canvas.drawVerticies().

Ill try to get a timeline trace later today.  Are you looking for an export from the CPU Profiler in Dev Tools?

**Comment by jonahwilliams** [comment]
Thank you! that helps narrow it down. Actually, the most useful thing you could do is share that painter and some data that I can run through it (vertices and path). Would that be possible?

**Comment by rlueders** [comment]
Ill need to see how and if I can get some sample data out.  But, I would think any sufficiently large test should cause the performance problem.  In the video samples above, for the path I am calling path.lineTo() about 2,500 times, and the call to draw verticies looks like below, where positions has a length of about 50k.

    final Vertices vertices = Vertices.raw(VertexMode.triangles, positions, colors: colors) ;
    canvas.drawVertices(vertices, BlendMode.dst, paint)

**Comment by jonahwilliams** [comment]
I understand, however I would greatly prefer to see how the painter works and get some real data so I can be sure my local experiments will generalize.

**Comment by rlueders** [comment]
Sorry, I don't think I can spend anymore time on this. I need to redirect my efforts to finding an alternative to Flutter.  Thanks for looking into it.

**Comment by jonahwilliams** [comment]
No problem, good luck!
