### ISSUE TITLE
BUG in [v3.10.0]: Upgrade is not backwards compatiable

### ISSUE THREAD

**Issue by ollyde** [flutter/flutter#126522]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Have an existing flutter project with packages and libraries
2. Upgrade to Flutter 3.10
3. Watch as no 3rd party library works.

### Expected results

It should compile.

### Actual results

It fails to compile.

### Code sample

NA

### Screenshots or Video

NA

### Logs

There are many logs on different packages but mainly the syntax on root widgets has changed. A big no-no.

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.10.0, on macOS 13.3.1 22E772610a darwin-arm64, locale en-NO)
    • Flutter version 3.10.0 on channel stable at /Users/oliverdixon/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (2 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/oliverdixon/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/oliverdixon/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.78.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.3.1 22E772610a darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.5672.92

[✓] Network resources
    • All expected network resources are available.

**Comment by kishan-dhankecha** [comment]
As new version has breaking changes and new core language features included in Dart SDK, you should only update your project version to this latest release if all your dependencies are also supports this changes.

If you update your Dart SDK constraints to `sdk: '>=3.0.0 <4.0.0'` in your `pubspec.yaml` but your dependencies still has max SDK version support as `3.0.0`, dependency version solving will fail.

**Comment by ollyde** [comment]
@kishan-dhankecha we use 100s of 3rd party libraries. Updating dart should have been a warning not an error. This is a huge bug and I'm surprised it passed.

**Comment by ollyde** [comment]
@kishan-dhankecha trying at the moment but getting pod install errors on MacOS, this update isn't good :-(

**Comment by stuartmorgan** [comment]
> If you update your Dart SDK constraints to `sdk: '>=3.0.0 <4.0.0'` in your `pubspec.yaml` but your dependencies still has max SDK version support as `3.0.0`, dependency version solving will fail.

This is not correct; `<3.0.0` has been special-cased in the resolver.

(Also, the original post doesn't appear to be describing resolver failures, although it's impossible to tell without logs, which were not included.)

**Comment by ollyde** [comment]
@kishan-dhankecha thanks for your help.

For anyone else
On this update I had to manually run
**Inside macos**
```
sudo gem pristine ffi 
pod install
```
Then update
```
environment:
  sdk: '>=3.0.0 <4.0.0'
```

Seems to work good now

**Comment by stuartmorgan** [comment]
Closing, as the general statement here that new versions should be fully backwards compatible with existing packages is explicitly not how Flutter works:

https://docs.flutter.dev/resources/compatibility

In the future, please provide specific error messages and logs, as requested by the template, when filling issues.

**Comment by faheemletitgo** [comment]
I am build issues with flutter web
