### ISSUE TITLE
Flutter is not smooth in release mode. (Samsung S7)

### ISSUE THREAD

**Issue by BCGen** [flutter/flutter#12656]
Hi, after I install Flutter Gallery from play store, it's very smooth, like native app. so I decide to try flutter.

but after I finish the example Building Beautiful UIs with Flutter, and run in release mode, 
when scrolling listview (listview.builder), it's not very smooth, even a little jittery.

then I try to run github example - https://codelabs.developers.google.com/codelabs/flutter/index.html#0  
It's also not smooth and jittery(both alpha and master).

Thanks.

## Flutter Doctor
```
[√] Flutter (on Microsoft Windows [Version 10.0.15063], locale zh-TW, channel alpha)
    • Flutter at C:\tools\flutter
    • Framework revision e8aa40eddd (3 days ago), 2017-10-17 15:42:40 -0700
    • Engine revision 7c4142808c
    • Tools Dart version 1.25.0-dev.11.0

[√] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at C:\Users\b5489\AppData\Local\Android\sdk
    • Platform android-26, build-tools 26.0.2
    • ANDROID_HOME = C:\Users\b5489\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] IntelliJ IDEA Ultimate Edition (version 2017.2)
    • Flutter plugin version 18.1
    • Dart plugin version 172.4155.35

[√] Connected devices
    • SM G930F • android-arm • Android 7.0 (API 24)
```

**Comment by mit-mit** [comment]
cc @sethladd any known issues with listview.builder?

**Comment by sethladd** [comment]
cc @Hixie for thoughts. I seem to remember there are a few options here.

**Comment by p30arena** [comment]
Hi there! what happened to this issue?

**Comment by wilin52** [comment]
@zoechi 
I also met the problem recently.
I have a device Huawei Mate9 Pro ,scrolls not smoothly but it's better in Samsung s8/ OnePlus 3T.
Does it performs differently in various devices?

I create a sample Repository: No InkWell inside list . And using AlwaysScrollableScrollPhysics, but didn't work.
https://github.com/wilin52/custom_scroll_view_demo_scroll_not_smoothly

**Comment by x4080** [comment]
Yes, i found it to be true, snapdragon 845 seems to eliminate the jank but older devices like snapdragon 625 or 800 shows jank when scrolling listview not 60fps

Are flutter using gpu rendering? Because in developer options in Android, it cannot detect the gpu rendering

**Comment by x4080** [comment]
Oh and i did compare it with native Android app with more complex listview content

And in iPhone, listview perform so much better than Android counterpart

I tested it on iPhone se so not the newest and greatest

**Comment by Gatunox** [comment]
The same is true on iOS, Iphone XR

**Comment by njovy** [comment]
Any updates regarding this issue?
I am having the exact same issue on Android device. It's really bad.

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what
happens, logs and the output of 'flutter doctor -v' please.
All system setups can be slightly different so it's always better to open new issues and reference related
issues.
Thank you everyone
