### ISSUE TITLE
[Impeller] Could not find an option named "disable-impeller"

### ISSUE THREAD

**Issue by sangddn** [flutter/flutter#126559]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

In Flutter 3.10 (stable), when running on iOS devices with the option to disable Impeller. Apparently there's so such flag as noted [here](https://docs.flutter.dev/perf/impeller#:~:text=Flutter%20enables%20Impeller%20by%20default,to%20the%20flutter%20run%20command).

`flutter run --disable-impeller` 

### Actual results

Error thrown: Could not find an option named "disable-impeller".

### Logs

<details>
<summary>Logs</summary>

```console

% flutter run --disable-impeller

Could not find an option named "disable-impeller".


Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.2.1 22D68 darwin-arm64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.78.0)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by jonahwilliams** [comment]
the option is called `--no-enable-impeller`, sorry the documentation is incorrect. We'll fix that
