### ISSUE TITLE
Android emulator failing to start on CI

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#126568]
On the Dart roll here https://github.com/flutter/engine/pull/41943

https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Android%20Emulator%20Tests/7535/overview

It looks like the VMs don't have hardware acceleration?
```
09:45:14.745939 140321047887424 ERROR   main-common.c:1398                 | x86_64 emulation currently requires hardware acceleration!
```

Routing to infra and android. cc @reidbaker @sealesj

**Comment by ricardoamador** [comment]
@zanderso I am going to close this and use https://github.com/flutter/flutter/issues/126571 for tracking the Chromium bug to investigate this.
