### ISSUE TITLE
Emulator tests do not have kvm permission

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#126571]
The engine tree is red on this failure.

failure: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Android%20Emulator%20Tests/5577/overview

## error log
```
Created filesystem with 11/4224 inodes and 1302/16896 blocks
09:51:09.444312 140586245877312 VERBOSE main-common.c:1359                 | CPU Acceleration: DISABLED
09:51:09.444328 140586245877312 VERBOSE main-common.c:1360                 | CPU Acceleration status: This user doesn't have permissions to use KVM (/dev/kvm).
The KVM line in /etc/group is: [LINE_NOT_FOUND]

If the current user has KVM permissions,
the KVM line in /etc/group should end with ":" followed by your username.

If we see LINE_NOT_FOUND, the kv
09:51:09.444347 140586245877312 VERBOSE main-common.c:1373                 | handleCpuAcceleration: feature check for hvf
C   30.093s Main  Timed out. Dumping threads.
C   30.093s Main  ********************************************************************************
C   30.093s Main  Stack dump for thread 'TimeoutThread-1-for-MainThread'
C   30.093s Main  ********************************************************************************
C   30.098s Main  File: "/b/s/w/ir/cache/vpython/store/cpython-n8umfpv0s1ufm2q1s4irhb59jc/contents/lib/python3.8/threading.py", line 890, in _bootstrap
C   30.098s Main    self._bootstrap_inner()
C   30.098s Main  File: "/b/s/w/ir/cache/vpython/store/cpython-n8umfpv0s1ufm2q1s4irhb59jc/contents/lib/python3.8/threading.py", line 932, in _bootstrap_inner
C   30.098s Main    self.run()
C   30.098s Main  File: "/b/s/w/ir/cache/avd/src/third_party/catapult/devil/devil/utils/reraiser_thread.py", line 94, in run
C   30.098s Main    self._ret = self._func(*self._args, **self._kwargs)
C   30.098s Main  File: "/b/s/w/ir/cache/avd/src/third_party/catapult/devil/devil/utils/timeout_retry.py", line 156, in <lambda>
C   30.099s Main    lambda: func(*args, **kwargs), name=thread_name)
C   30.099s Main  File: "/b/s/w/ir/cache/avd/src/build/android/pylib/local/emulator/avd.py", line 735, in listen_for_serial
C   30.099s Main    with contextlib.closing(s.accept()[0]) as conn:
C   30.099s Main  File: "/b/s/w/ir/cache/vpython/store/cpython-n8umfpv0s1ufm2q1s4irhb59jc/contents/lib/python3.8/socket.py", line 292, in accept
C   30.099s Main    fd, addr = self._accept()
C   30.099s Main  ********************************************************************************
```

**Comment by sealesj** [comment]
Looking into this

**Comment by zanderso** [comment]
x-ref https://github.com/flutter/flutter/issues/126568 cc @ricardoamador

**Comment by ricardoamador** [comment]
The issue here was a Dart image that pushed causing the KVM to not be accessible.
This Dart image was pushed 10 hours ago `dart-bionic-23051000-e6ac32cc415` and seems to have a change that caused KVM to not be executable by the account that runs the tests in the fuchsia VMs.  Reverting to `dart-bionic-23043000-9b6d3f3a509` will fix the issue and reduce this from P0.

**Comment by ricardoamador** [comment]
The Image has been reverted and the autoroller has been paused so the "bad" image (`dart-bionic-23051000-e6ac32cc415`) that has caused the KVM issue has been rolled back to the previous image: `dart-bionic-23043000-9b6d3f3a509`. All of the bots have been restarted and verified with the new image.

**Comment by ricardoamador** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1444900

Downgrading the priority and leaving this open for tracking purposes.

**Comment by ricardoamador** [comment]
Okay it the error was fixed here by the chromium team: https://chrome-internal-review.googlesource.com/c/infra/puppet/+/5918626

The next step is to enable the auto-roller for the dart image so we can confirm the fix with our infra.

**Comment by ricardoamador** [comment]
Updated with a fix from the dart team here: https://chrome-internal-review.googlesource.com/c/infra/infra_internal/+/5924348

Rerunning the roller succeeded: https://ci.chromium.org/ui/p/infra-internal/builders/prod/ccompute-dart-image-autoroller/b8780811598114499665/overview

Leaving open to make sure the tests are not failing in the next iteration.

**Comment by ricardoamador** [comment]
Emulator is running successfully on the new image https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/ricardoamador_google.com/a569dc689b4678f54d45341ab60f17754332af50569def4cb5dc0debbb182c99/+/build.proto?server=chromium-swarm.appspot.com
