### ISSUE TITLE
unable to migrate

### ISSUE THREAD

**Issue by miteshsharma766** [flutter/flutter#126530]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

when i run

### Actual results

The plugin `location` requires your app to be migrated to the Android embedding v2. Follow the steps on https://flutter.dev/go/android-project-migration and re-run this command.

### Logs

The plugin `location` requires your app to be migrated to the Android embedding v2. Follow the steps on https://flutter.dev/go/android-project-migration and re-run this command.

### Flutter Doctor output

<details>
<summary>Doctor output</summary>
The plugin `location` requires your app to be migrated to the Android embedding v2. Follow the steps on https://flutter.dev/go/android-project-migration and re-run this command.

**Comment by darshankawar** [comment]
@miteshsharma766 
What exactly is the issue are you facing ? Is it the message you are seeing, or trying to follow the link in the message is giving you any error ? Or are you seeing `nothing to migrate` after following the link ?

If so, this was fixed already as mentioned here: https://github.com/flutter/flutter/issues/118231#issuecomment-1377374340 so you'll need to be on latest stable or master to see it working.
