### ISSUE TITLE
(PR created) Let `runAsync` allow re-entrance, or allow users to know whether it is already running async tasks

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#126545]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

When implementing and using https://github.com/fzyzcjy/flutter_convenient_test, I realize it is hard to avoid `runAsync`'s re-entrance. Currently, if a runAsync is inside another one, it errors `Reentrant call to runAsync() denied`. However, this proposal proposes that, we can allow the second function to be called directly. 

Example where this comes into a problem: Suppose I have a `Future<void> login() { ... }` which does some operations that needs runAsync, and another `logout() { ... }`. Then, when implementing `prepareUser() { logout(); somethingElse(); login(); }`, It is tempting to wrap `prepareUser` with a runAsync, but that cause the reentrant problem.

### Proposal

Rough code:

1. Change flutter_test as

```diff
diff --git a/packages/flutter_test/lib/src/binding.dart b/packages/flutter_test/lib/src/binding.dart
index be9abeb568..11ee9d4837 100644
--- a/packages/flutter_test/lib/src/binding.dart
+++ b/packages/flutter_test/lib/src/binding.dart
@@ -376,6 +376,8 @@ abstract class TestWidgetsFlutterBinding extends BindingBase
   /// [LiveTestWidgetsFlutterBinding] (tests running using `flutter run`).
   test_package.Timeout get defaultTestTimeout;
 
+  bool get runningAsyncTasks; // NOTE MODIFIED add
+
   /// The current time.
   ///
   /// In the automated test environment (`flutter test`), this is a fake clock
@@ -1141,6 +1143,8 @@ class AutomatedTestWidgetsFlutterBinding extends TestWidgetsFlutterBinding {
   FakeAsync? _currentFakeAsync; // set in runTest; cleared in postTest
   Completer<void>? _pendingAsyncTasks;
 
+  bool get runningAsyncTasks => _pendingAsyncTasks != null; // NOTE MODIFIED add
+
   @override
   Clock get clock {
     assert(inTest);
@@ -1643,6 +1647,8 @@ class LiveTestWidgetsFlutterBinding extends TestWidgetsFlutterBinding {
   bool _viewNeedsPaint = false;
   bool _runningAsyncTasks = false;
 
+  bool get runningAsyncTasks => _runningAsyncTasks; // NOTE MODIFIED add
+
   /// The strategy for [pump]ing and requesting new frames.
   ///
   /// The policy decides whether [pump] (with a duration) pumps a single frame
```

2. `runAsync` (or `runAsyncReEntrance` can be:

```dart
    if (runningAsyncTasks) {
      return await callback();
    } else {
      return await runAsync(callback);
    }
```

**Comment by pdblasi-google** [comment]
I'd like to understand this a bit more before digging into the PR.

I think the intent of the `runAsync` method was to only be called at the top level, preferably using the `WidgetTester` provided by `testWidgets`. It sounds like you are directly referencing the `TestWidgetsFlutterBinding.instance` or passing around the reference to the binding, which is opening you up to running into this issue more than I would expect an average user to.

In your example, each of the methods could be implemented without using `runAsync` internally, then when you are writing a test _calls_ to those methods would be passed to `runAsync`. That way any `await`s that are internal to the call would be run in the same true async context as the outermost call and work as expected.

Could you expand on the use case and why it would be useful to re-enter the `runAsync` method outside of the top level?

**Comment by fzyzcjy** [comment]
> In your example, each of the methods could be implemented without using runAsync internally
Could you expand on the use case and why it would be useful to re-enter the runAsync method outside of the top level?

Sure! It is because I hope the tests are more neat. The https://github.com/fzyzcjy/flutter_convenient_test, or the https://www.cypress.io/ style (cypress is a famous web testing framework), seems to be that, try to make the test script as neat as possible. For example,

```dart
final whateverFinder = ...;
while(whateverFinder.evaluate().isEmpty) await tester.pumpAndSettle();
await tester.tap(whateverFinder);
await takeScreenshotAndSaveItForDebug();
```

is converted into

```dart
await whateverFinder.tap(); // automatically include auto-retry, take debug screenshot, etc
```

Thus you can see the main idea - make tests neat and simple. Now back to the runAsync thing. Without that, I have to wrap each calls in top level with an extra runAsync:

```dart
await tester.runAsync(() async => switchUser(...));
expect(tester.binding.takeException(), null);
```

but with the proposal,

```dart
await switchUser(...);
```

and done.

**Comment by pdblasi-google** [comment]
So, I feel like there are two separate use cases here:

The first case you give, where you're combining many `WidgetTester` calls into a single one for convenience, shouldn't _need_ `runAsync` because app interactions should not need to run truly async and can be handled with the various pump methods.

The second case with `switchUser` seems like it could possibly be the case that `runAsync` is intended to solve, where during a test with FakeAsync, someone needs to run something that requires running asynchronously separately from the `WidgetTester` methods.

In the first case, we don't really want calls to `runAsync` because they're expensive and require creating brand new `Zone`s for each call. In the second case, we probably don't want the `runAsync` to be transparent, because it hides the fact that the call is running in a truly asynchronous setting.

I've looked over your `flutter_convenient_test` package a bit (admittedly at a high level), but I can't see a case where you'd need to have a re-entrant version of `runAsync`. Could you point me to a specific place in the codebase where you ran into this and it can't be resolved without a re-entrant `runAsync`?

**Comment by fzyzcjy** [comment]
Hi thanks for the reply!

> The first case you give, where you're combining many WidgetTester calls into a single one for convenience, shouldn't need runAsync

Yes I agree. That's just to show the philosophy, not to show the need of runAsync

> In the second case, we probably don't want the runAsync to be transparent, because it hides the fact that the call is running in a truly asynchronous setting.

For a (traditional) Flutter widget test, definitely - I can see the philosophy of Flutter widget test is that it needs to be super clear and prefer low-level full-control things. For example, users need to manually pump etc.

However, for flutter_convenient_test's philosophy, which mimics Cypress (popular for Web testing), I want to make users write as little work as possible, and make it transparent is indeed a good thing.

> I've looked over your flutter_convenient_test package a bit (admittedly at a high level), but I can't see a case where you'd need to have a re-entrant version of runAsync. Could you point me to a specific place in the codebase where you ran into this and it can't be resolved without a re-entrant runAsync?

There is no needs inside that package itself, but as mentioned above (the `switchUser` example), it can be needed by users of flutter_convenient_test (e.g. my internal code for my app).

**Comment by pdblasi-google** [comment]
With that context, I think this would be better supported with a custom `TestWidgetsFlutterBinding` in your `flutter_convenient_test` package that either adds a new reentrant version or simply overrides `runAsync` and allows reentrance.

As you mentioned, `flutter_test` has different priorities than testing frameworks built on top of it. Making `runAsync` reentrant, even by opting-in to reentrance, would allow users to get into states that weren't intended and would be difficult to resolve and maintain long term. That may be a beneficial cost-benefit tradeoff for higher level testing frameworks, but I don't believe it's beneficial at the `flutter_test` level.

Thanks for the discussion and your continued contributions to improving Flutter!

**Comment by fzyzcjy** [comment]
> a custom TestWidgetsFlutterBinding in your flutter_convenient_test package that either adds a new reentrant version or simply overrides runAsync and allows reentrance.

Good idea! I will do that. 

You are welcome!

**Comment by pdblasi-google** [comment]
> Good idea! I will do that.

One thing to note on this is there's a known issue with custom bindings and `integration_test` right now where you'd have to make sure your custom binding is initialized before the bootstrapping script is run. It is on my list to fix, but not high enough on that list for me to have a timeline of when _I'll_ get to it.

You can see #113097 for further info on that issue.

**Comment by fzyzcjy** [comment]
I see. Thank you!
