### ISSUE TITLE
[Impeller] Index buffer must be optional.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#126572]
Currently all rendering commands require an index buffer. This is generally useful, but in certain cases adds pure overhead.

For example, if we're computing a triangle strip geometry in the compute shaders, its nice to not have to generate a placeholder index buffer on the CPU.

By default the vertex_buffer_builder will generate a trivial index buffer (0, 1, 2, 3) which is just adding more overhead in encoding.

**Comment by jonahwilliams** [comment]
For example, in https://github.com/flutter/engine/pull/41803 using a generative art example - I have to allocate a 1.5MB index buffer (full of 0, 1, 2, 3...) in order to use the command. This accounts for roughly 30% of CPU time.

**Comment by dnfield** [comment]
Ahh right, my compute stuff would be a good test case for this. Ok.

**Comment by jonahwilliams** [comment]
Here is a patch I ahve kicking around. It doesn't work unfortuantely, I dont know if I'm missing another condition, if I don't know how the arguments to drawPrimitives work, or if something is going wrong in Bind.

```
--- a/impeller/core/formats.h
+++ b/impeller/core/formats.h
@@ -308,6 +308,8 @@ enum class IndexType {
   kUnknown,
   k16bit,
   k32bit,
+  // Do not use the index buffer.
+  kNone,
 };
 
 +    const PrimitiveType primitive_type = pipeline_desc.GetPrimitiveType();
+
+    if (command.index_type == IndexType::kNone) {
+      std::cerr << "none index" << std::endl;
+      auto vtx_buffer = command.GetVertexBuffer();
+      auto mtl_vtx_buffer =
+          DeviceBufferMTL::Cast(*(vtx_buffer.buffer)).GetMTLBuffer();
+      [encoder setVertexBuffer:mtl_vtx_buffer
+                        offset:vtx_buffer.range.offset
+                       atIndex:30u];
+      [encoder drawPrimitives:ToMTLPrimitiveType(primitive_type)
+                  vertexStart:0
+                  vertexCount:command.index_count];
+      return true;
+    }
+
     if (command.index_type == IndexType::kUnknown) {
       return false;
     }
@@ -503,8 +519,6 @@ bool RenderPassMTL::EncodeCommands(const std::shared_ptr<Allocator>& allocator,
       return false;
     }
 
-    const PrimitiveType primitive_type = pipeline_desc.GetPrimitiveType();
-


--- a/impeller/core/vertex_buffer.h
+++ b/impeller/core/vertex_buffer.h
@@ -16,7 +16,7 @@ struct VertexBuffer {
   IndexType index_type = IndexType::kUnknown;
 
   constexpr operator bool() const {
-    return static_cast<bool>(vertex_buffer) && static_cast<bool>(index_buffer);
+    return static_cast<bool>(vertex_buffer); // && static_cast<bool>(index_buffer);
   }
 };
 

 ```
 
 Then pick a command that doesnt really use the index buffer and try this out.

**Comment by dnfield** [comment]
You were close. I have this working locally.

**Comment by dnfield** [comment]
You don't need to set the vertex buffer again because it already got set earlier. You also should be using `command.base_vertex` instead of assuming `0`.

The thing that seems odd to me is continuing to call it `index_count`.

**Comment by dnfield** [comment]
Opening a patch momentarily.
