### ISSUE TITLE
BUG in [v3.10.0]: Invalid argument(s): Illegal argument in isolate message: object is unsendable

### ISSUE THREAD

**Issue by monkeyWie** [flutter/flutter#126520]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

When I upgrade to v3.10.0, this code throw exception.

### Expected results

No exception.

### Actual results

Throw exception:
```
Invalid argument(s): Illegal argument in isolate message: object is unsendable - Library:'dart:async' Class: _AsyncCompleter@4048458 (see restrictions listed at `SendPort.send()` documentation for more information)
```

### Code sample

<details><summary>Code sample</summary>

```dart
var childReceive = ReceivePort();
      sendPort.send(childReceive.sendPort);

      childReceive.listen((message) async {
        late _Result result;
        try {
          if (message is _StartParam) {
            result = _StartResult();
            (result as _StartResult).port = await _libgopeed.start(message.cfg);
          }
          if (message is _StopParam) {
            result = _StopResult();
            await _libgopeed.stop();
            childReceive.close();
            Isolate.exit(sendPort);
          }
        } on Exception catch (e) {
          result.exception = e;
        }
        sendPort.send(result);
      });
    }, mainReceive.sendPort);
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.0, on Microsoft Windows [版本 10.0.22621.1555], locale zh-CN)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.5)
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment]
Hi @monkeyWie 
Does it work on the previous Flutter/Dart version? Can you please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this?

**Comment by monkeyWie** [comment]
Yes it work well on 3.7.12.

**Comment by jason-simmons** [comment]
Recent versions of the Dart SDK have tightened the rules for which objects can be sent across isolates (see https://api.dart.dev/stable/3.0.0/dart-isolate/SendPort/send.html and https://github.com/dart-lang/sdk/commit/67683c39)

**Comment by monkeyWie** [comment]
@huycozy This is minimal reproducible code sample:
```
import 'dart:async';
import 'dart:isolate';

void main() async {
  var server = Server();
  var port = await server.start();
  print(port);
}

class Server {
  Config fetchConfig() {
    return Config(0);
  }

  Future<int> start() async {
    var startCompleter = Completer<int>();

    var mainReceive = ReceivePort();
    await Isolate.spawn((SendPort sendPort) {
      var config = fetchConfig();
      sendPort.send(config);
      print(config);
    }, mainReceive.sendPort);

    mainReceive.listen((message) {
      if (message is Config) {
        startCompleter.complete(message.port);
      }
    });
    return startCompleter.future;
  }
}

class Config {
  int port;
  Config(this.port);
}
```
The code work well on flutter 3.7.12 dart 2.19.6.

**Comment by huycozy** [comment]
@monkeyWie Thanks for your response. Please check the links Jason mentioned above. Also, if you still have issue with this, I would recommend opening an issue on [dart-lang/sdk](https://github.com/dart-lang/sdk/issues) for better support (Sorry for not mentioning this repository earlier).

Closing the issue from here.
