### ISSUE TITLE
[web] TextButton, IconButton & InkWell are not working properly after 3.10 release

### ISSUE THREAD

**Issue by rmahmadkhan** [flutter/flutter#126558]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Use latest Flutter version: `3.10.0`
2. This issue is happening with TextButton, Icon Button and InkWell
3. It is happening on web, not on mobile.
4. Use the following reproducible code

### Expected results

1. The buttons should be clickable when hovered over them.
2. It should show hover effect when cursor is dragged on it.

### Actual results

1. Buttons are showing hover effect at weird positions other than the right on button.
2. Buttons are not clickable when cursor is dragged on the it.

### Code sample

<details><summary>Code sample</summary>

```dart
TextButton(
        onPressed: widget.onTap,
        onHover: (hovered) {
          setState(() => isHovered = hovered);
        },
        child: Text(
          'Sample text',
          overflow: TextOverflow.ellipsis,
          maxLines: 2,
          style: TextStyle(
            color: Colors.blue,
            fontSize: 14,
            decoration: isHovered ? TextDecoration.underline : null,
            decorationThickness: 2,
          ),
        ),
      )
```

</details>

### Screenshots or Video

https://github.com/flutter/flutter/assets/46877003/4aafd455-31a9-4b0d-bff7-8b7cc13ec258

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.10.0, on macOS 13.0 22A380 darwin-arm64
    (Rosetta), locale en-PK)
    ! Warning: `dart` on your path resolves to
      /usr/local/Cellar/dart/2.19.6/libexec/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/ahmad/Development/flutter. Consider
      adding /Users/ahmad/Development/flutter/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version
    33.0.0-rc4)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.74.3)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
@rmahmadkhan 
Thanks for the report. I tried the code sample you provided on latest stable and ran it on web but didn't get the reported behavior. See video below:


https://github.com/flutter/flutter/assets/67046386/337eb827-436c-446b-8c80-543864b635d7


<details>
<summary> runnable code sample </summary>

```

import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    home: ParentWidget(),
  ));
}

class ParentWidget extends StatefulWidget {
  const ParentWidget({super.key});

  @override
  State<ParentWidget> createState() => _ParentWidgetState();
}

class _ParentWidgetState extends State<ParentWidget> {
  bool isHovered = false;  //  same result with true
  
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: TextButton(
          onPressed: () {},
          onHover: (hovered) {
            setState(() => isHovered = hovered);
          },
          child: Text(
            'Sample text',
            overflow: TextOverflow.ellipsis,
            maxLines: 2,
            style: TextStyle(
              color: Colors.blue,
              fontSize: 14,
              decoration: isHovered ? TextDecoration.underline : null,
              decorationThickness: 2,
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

If above code sample doesn't represent your case to replicate the issue, please provide complete one that we can use to verify the issue properly.

**Comment by rmahmadkhan** [comment]
Thank you for the response. I tried reproducing the issue from scratch but everything is working fine.

But idk why my app works fine on 3.7.12 but when I upgrade it to 3.10, the buttons which are place in simple rows and columns start having issues.

I'm closing this issue as it seems to be specific to my ui.... :(

**Comment by rmahmadkhan** [comment]
hi @LionelWill 
This issue was caused by [responsive_framework](https://pub.dev/packages/responsive_framework). It is a known issue there as well. Check [Can't click buttons on flutter 3.10](https://github.com/Codelessly/ResponsiveFramework/issues/140#top) #140

**Comment by LionelWill** [comment]
Thank you very much.
