### ISSUE TITLE
flutter_localizations issue when trying to run "flutter run"

### ISSUE THREAD

**Issue by antixirus** [flutter/flutter#126555]
- [x] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [x]  I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

Hi there, since I upgraded to Flutter v 3 I have been receiving this error when trying to build my project:

    C:\src\flutter\bin\flutter.bat --no-color pub get
    Resolving dependencies...
    Because fstore depends on flutter_localizations from sdk which depends on path 1.8.3, path 1.8.3 is required.
    So, because fstore depends on path 1.8.2, version solving failed.
    Process finished with exit code 1

This is what I get when retrieving "doctor --verbose"

    PS C:\src\ladas> flutter.bat doctor --verbose

    [√] Flutter (Channel stable, 3.10.0, on Microsoft Windows [Version 10.0.19045.2846], locale en-ID)

    • Flutter version 3.10.0 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (2 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

    [√] Windows Version (Installed version of Windows is version 10 or higher)

    [√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)

    • Android SDK at C:\Users\LEN\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

    [√] Chrome - develop for the web

    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

    [X] Visual Studio - develop for Windows

    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

    Android Studio (version 2022.2)

    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • VS Code at C:\Users\LEN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.64.0

    [√] Connected device (3 available)

    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2846]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 113.0.5672.93
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 113.0.1774.35

    [√] Network resources

    • All expected network resources are available.

    ! Doctor found issues in 1 category.

This is my pubspec.yaml content that includes the following:

    name: fstore
    publish_to: "none"
    description: Mobile commerce app by Flutter

    # Release version: v3.8.1 (Do not change this line)
    # A version number is three numbers separated by dots, like 1.2.43 - followed by an optional build number separated by a +.
    # In Android, build-name is used as versionName while build-number used as versionCode.Read more about Android versioning at https://developer.android.com/studio/publish/versioning
    # In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion. Read more about iOS versioning at https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
    version: 1.0.0+3000

    environment:
      sdk: ">=2.17.6 <3.0.0"

    dependencies:
      flutter:
        sdk: flutter
      flutter_localizations:
        sdk: flutter

      inspireui: 1.4.2

      flutterflow:
        path: packages/flutterflow/

      flux_firebase:
        path: packages/flux_firebase/

      # Base
      intl: 0.17.0
      crypto: 3.0.2
      path_provider: 2.0.14
      url_launcher: 6.1.10
      flutter_secure_storage: 8.0.0
      hive: 2.2.3
      hive_flutter: 1.1.0
      http: 0.13.5
      http_auth: 1.0.1
      share: 2.0.4
      tuple: 2.0.1
      collection: 1.17.0
      quiver: 3.2.1
      async: 2.10.0
      html: 0.15.2
      vector_math: 2.1.4
      path: 1.8.2
      flutter_svg: 1.1.6 # depend on pay_android
      multiple_localization: 0.3.0

      notification_permissions: 0.6.1
      flutter_local_notifications: ^13.0.0
      onesignal_flutter: 3.5.0

      # STATE MANAGEMENT
      provider: 6.0.5
      get_it: 7.3.0

      # SPLASH SCREEN, ONBOARD
      lottie: 2.3.0
      rive: 0.10.3

      # WEB TOOLS
      html_unescape: 2.0.0
      webview_flutter: 4.0.6
      webview_flutter_web: 0.2.2+1
      responsive_builder: 0.6.4
      flutter_inappwebview: 5.7.2+3

      # HTML render
      flutter_widget_from_html_core: 0.9.1
      fwfh_svg: 0.7.2+1
      fwfh_cached_network_image: 0.7.0+4
      fwfh_url_launcher: 0.9.0+1
      fwfh_chewie: 0.7.1+1
      fwfh_webview: 0.7.0+1
      fwfh_text_style: 2.22.8+1
    
      # VIDEO
      youtube_player_iframe: ^4.0.4

      # MAP
      google_maps_flutter: 2.2.5
      geocode: 1.0.2
      location: 4.4.0

      # AUTHENTICATION
      local_auth: 2.1.6
      the_apple_sign_in: 1.1.1
      flutter_facebook_auth: 5.0.8
      google_sign_in: 6.0.2
      sms_autofill: 2.3.0

      # PERMISSION
      permission_handler: 10.2.0
    
      # FILES, IMAGES
      file_picker: 5.2.6
      cached_network_image: 3.2.3
      image: 4.0.15
      transparent_image: 2.0.1
      image_picker: 0.8.7
      flutter_native_image: 0.0.6+1
      flutter_cache_manager: 3.3.0
      wechat_assets_picker:  8.4.0   
      photo_manager: 2.5.2

      # TOOLS
      google_fonts: 4.0.3
      random_string: 2.3.1
      json_annotation: 4.8.0
      freezed_annotation: 2.2.0
      timeago: 3.3.0 # use intl 0.18.0
      universal_platform: 1.0.0+1
      uuid: 3.0.7
      easy_debounce: 2.0.3
      devicelocale: 0.6.0
      visibility_detector: 0.3.3 # depend on google_mobile_ads
      rate_my_app: 1.1.4
      flutter_linkify: 5.0.2
      gms_check: 1.0.1
      new_version_plus: 0.0.3 # depend on razorpay_flutter
      video_player: 2.6.1
      google_mobile_ads: 2.3.0
      speech_to_text: 6.1.1

      # UI
      flutter_spinkit: 5.1.0
      smooth_page_indicator: 1.1.0
      animated_text_kit: 4.2.2
      flash: 2.0.5+1
      flutter_staggered_grid_view: 0.6.2
      pin_code_fields: 7.4.0
      country_pickers: 2.0.0
      dropdown_search: 5.0.6
      intro_slider: 4.2.0
      flutter_zoom_drawer:
        git:
          url: https://github.com/inspireui/flutter_zoom_drawer
          ref: 4b5d760a98f6d1f314aabe5e1b3c102294fe9595
      extended_image: 7.0.2
      dotted_decoration: 2.0.0
      awesome_card: 1.1.7
      qr_code_scanner: 1.0.1
      flutter_calendar_carousel: 2.4.1 # use intl 0.18.0
      sticky_headers: 0.3.0+2
      jumping_dot: ^0.0.4
      infinite_carousel: ^1.0.2
      charts_flutter_new: 0.12.0
      tiktoklikescroller: ^0.2.3
      readmore: ^2.2.0
      flutter_animate: 4.1.0
      flutter_async_autocomplete: ^0.1.1

      ### Native Payment
      razorpay_flutter: 1.3.4
      paytm_allinonesdk: 1.2.1
      pay_with_paystack:
        git:
          url: https://github.com/inspireui/pay_with_paystack
          ref: b84c3dffcbf18028af8a4929024f73659ed5dc04
      flutter_paystack:
        git:
          url: https://github.com/inspireui/flutter_paystack
          ref: fdd0dc5b5d4591a6b508b97fe84270e10cc18875

      #### For Listing App
      carousel_slider: 4.2.1

      #### For Shopify GraphQL
      graphql: 5.1.3

      ### Flutter 3 fix warning
      flutter_swiper_null_safety:
        git: https://github.com/inspireui/flutter_swiper_null_safety
      flare_flutter:
        git:
          url: https://github.com/inspireui/Flare-Flutter.git
          ref: fd4bcba22aae4c028286e453deeb78f3311e689a
          path: flare_flutter
      pull_to_refresh:
        git: https://github.com/inspireui/flutter_pulltorefresh
      intl_phone_number_input:
        git: https://github.com/inspireui/intl_phone_number_input
      country_code_picker:
        git:
          url: https://github.com/inspireui/CountryCodePicker
          ref: 0d3978023a94415ab1339de445f15c737adec9b1
      flutterwave_standard:
        git:
          url: https://github.com/inspireui/Flutterwave
          ref: dd7da29b031fa5a9166b58ffc090eb0a69333b96

      ###---- Some extra feature is disable by default -----###
      ### 💳 Facebook Ads
      ### Search "Enable Facebook Ads" & uncomment to use  - https://tppr.me/9Pkf9
      # facebook_audience_network: 1.0.1

      ### ⬇️ Enable In App Update on Android feature
      ### Uncomment file lib/common/tools/in_app_update_for_android.dart
      #  in_app_update: 4.0.1

    dev_dependencies:
      flutter_lints: 2.0.1
      flutter_native_splash: 2.2.19
      build_runner: 2.3.3
      freezed: 2.3.2
      json_serializable: 6.6.0

    ### Enable to use Flutter Test Driver
    #  flutter_driver:
    #    sdk: flutter
    #  test: 1.16.5
    #  dependency_validator: ^3.2.2  # pub run dependency_validator

    ### Enable Generate Icon library
    #  flutter_launcher_icons:
    #    git:
    #      url: https://github.com/inspireui/flutter_launcher_icons.git
    #      ref: 7aab578231120ef39d37db34e07dce3c7995ee14

    #  Run this script to generate the app icon: flutter pub run flutter_launcher_icons:main

    flutter_icons:
      android: "launcher_icon"
      ios: true
      image_path: "assets/images/app_icon.png"

    flutter:
      uses-material-design: true
      assets:
        - lib/config/
        - lib/config/states/
        - lib/config/stories/
        - assets/icons/brands/
        - assets/icons/credit_cards/
        - assets/icons/tabs/
        - assets/icons/payment/
        - assets/icons/logins/
        - assets/images/
        - assets/images/country/
        - assets/images/favicon/
        - assets/map_styles/
        - assets/html/
        - google_fonts/

    ### Uncomment to use custom font
    #  fonts:
    #    - family: Your Custom Font
    #      fonts:
    #      - asset: google_fonts/GE-Hili-Book.ttf

    flutter_intl:
      enabled: true
      use_deferred_loading: true
    
How do I resolve this issue as I am still a beginner when it comes to flutter?

**Comment by stuartmorgan** [comment]
> path: 1.8.2

You cannot pin an exact version of a dependency that conflicts with the version used by Flutter itself. Closing, as this is expected behavior.

You are pinning a large number of you dependencies; I would recommend reading https://dart.dev/tools/pub/dependencies#best-practices, particularly the first entry. `pubspec.lock`, not `pubspec.yaml`, is the recommended way to ensure consistent builds.
