### ISSUE TITLE
Hard to pass ambient data to dialogs

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#12655]
We have a few dialogs that are shown as part of an implementation detail of a static/top-level function:

- `showTimePicker`
- `showDatePicker`
- `showAboutDialog`

It is currently hard (impossible?) to override ambient data, such as `Localizations` and `MediaQuery`. `Theme` is special-cased by `showDialog`.

## Options

- [ ] We can do for `Localizations` and `MediaQuery` what we do for `Theme`, i.e. have `showDialog` special-case them and introduce shadow-only concepts similar to `shadowThemeOnly`, but I'm not sure how well this approach scales.
- [ ] Give developers an option to either use a `show*` function or instantiate the underlying dialog widget directly and pass it to `showDialog`. This way the developer can wrap the widget in a `Localizations` or `MediaQuery` themselves.
- [ ] https://github.com/flutter/flutter/pull/12172

**Comment by CrazyStaff** [comment]
Why have it to be so complicated generally by using MediaQuery.
Wouldn't it be easier for developers to use just

**showTimePicker**(
  ...
   **alwaysUse24HourFormat: true**
);

**Comment by zoechi** [comment]
Can https://docs.flutter.io/flutter/material/MaterialApp/builder.html be used for that?
