### ISSUE TITLE
The supplied javaHome seems to be invalid. I cannot find the java executable.

### ISSUE THREAD

**Issue by ammarkoz** [flutter/flutter#126528]
After installing flutter and all requirements. I am trying to run a Flutter app and I keep getting but I keep getting this error in all compilers.
in VS code
![image](https://github.com/flutter/flutter/assets/21055095/1eccdbab-9d10-4f11-b82a-4687093b559b)

in Android studio 
![image](https://github.com/flutter/flutter/assets/21055095/57fa6c47-8395-4b35-9ca0-bfc801568ad8)

and flutter doctor is all good 
![image](https://github.com/flutter/flutter/assets/21055095/99662e29-4ea8-4b97-8a4a-ce133cd457fe)

My java version 
![image](https://github.com/flutter/flutter/assets/21055095/938e0ea0-52b8-4dc0-9ae6-f8903cdcfbd1)

I added JAVA_HOME  manually like some fixed method saying nut it is the same 
![image](https://github.com/flutter/flutter/assets/21055095/a924a102-529b-4b4a-a8ab-ba11d3944665)

**Comment by darshankawar** [comment]
@ammarkoz 
I see that you are on 3.3.10 version, can you upgrade to latest stable as there have been changes made to AS after 3.7 release as mentioned in this similar / related issue: https://github.com/flutter/flutter/issues/118502 it also has solutions in the comments that you can try and see if they work for you in your case.

**Comment by ammarkoz** [comment]
What you mean? What should I update?

**Comment by darshankawar** [comment]
Upgrade your stable version to latest or take a look at the linked issue and underlying comments which has solutions and check if they work for your case.

**Comment by ammarkoz** [comment]
if u mean java, 20 is the last stable version of java

**Comment by darshankawar** [comment]
Sorry, I misread your flutter version before, I thought you were on 3.3.10, but actually you are on 3.10 which is fine.
I am not sure about java 20, but have you already looked at below solutions and issue ?

https://github.com/flutter/flutter/issues/118502#issuecomment-1383215722
https://github.com/flutter/flutter/issues/118502#issuecomment-1383219790
https://github.com/flutter/flutter/issues/118502#issuecomment-1383229562
