### ISSUE TITLE
ListView.builder with large number of items has janky scroll on LG G5

### ISSUE THREAD

**Issue by roughike** [flutter/flutter#12668]
[SO discussion: Why my flutter app's listview scroll not as smooth as the flutter gallery app?](https://stackoverflow.com/questions/46761036/why-my-flutter-apps-listview-scroll-not-as-smooth-as-the-flutter-gallery-app/)

The performance issue was reported to be present on Galaxy S7 too, but I didn't create a separate issue, as #12656 already existed.

**Comment by sethladd** [comment]
For the record, what is "large number" ?

Can we add in a repro code snippet to this issue? Something that's easy to run?

Should we point people to an alternative list mechanism on the API docs of https://docs.flutter.io/flutter/widgets/ListView-class.html ?

**Comment by roughike** [comment]
I'll try to gather more information from the asker of that StackOverflow question. I realize that creating issues of second hand information is not ideal, but thought you guys would still be interested.

**Comment by sethladd** [comment]
Understood. Thanks for understanding, too.

**Comment by Hixie** [comment]
Looks like the StackOverflow thread has a response that satisfied the questioner. I'm not sure what more we can do here. If there's ever more specific information, please don't hesitate to file a new bug.
