### ISSUE TITLE
[Impeller] Clip backdrop filter regions before applying expensive filters.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#126696]
From the issue https://github.com/flutter/flutter/issues/126353 , it looks like when applying a backdrop blur to a limited region of the screen that we're actually applying a blur to the entire backdrop texture. We should investigate why this is happening, as we could get some performance back by clipping or blitting this into a smaller texture first.

**Comment by bdero** [comment]
Ugh, yes, there's no general clipping mechanism in the filter graph right now. Some time ago I threw in a special clipping parameter for the blend filter specifically to reduce the extreme advanced blend performance cliff, but never got around to generalizing it.

Getting the transforms just right will be a bit tricky in the two pass blur, but we aught to add this mechanism to FilterContents generally and pass it in when applying backdrop filters for starters.

**Comment by vjamrich** [comment]
Applying blur only to the desired region would result in an unwanted effect. In the example below, I am applying the blur only to the region directly below the white rectangle. Therefore, it does not consider the different coloured background before actually overlapping it. This results in a sudden 'colour change' between two frames when crossing the coloured regions (focus on the moment in the screen recording when the rectangle touches the red region).

https://github.com/flutter/flutter/assets/59235105/48e6c949-4201-469c-8c84-d466d097fc53

Ideally, the the blur would be applied to a little bit larger region (depending on the sigma) and then the output being cropped.

**Comment by jonahwilliams** [comment]
Yes thats the idea. We know exactly how big of an area we'll end up sampling from.

**Comment by jonahwilliams** [comment]
Performance looks much better after @bdero 's fix:

### Before

![image](https://github.com/flutter/flutter/assets/8975114/d44ded90-16d7-4320-8df2-ffbb1a041fe8)


### After

![image](https://github.com/flutter/flutter/assets/8975114/e48a56ac-422e-45b6-9910-a2d50f4fc733)

**Comment by chinmaygarde** [comment]
Closing this as completed in https://github.com/flutter/engine/pull/42039. It seems though that there were some loose ends to tie up. Can we file a separate issue for those?
