### ISSUE TITLE
Black bar in gallery app, in Pages

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1266]
I seem to be able to trigger this by following these steps:

* Go to Tabs
* Swipe around
* Go back
* Go to Pages

![screenshot_20160115-142635](https://cloud.githubusercontent.com/assets/5479/12367058/334ac06c-bb94-11e5-9240-467cac6d1ef1.png)

FWIW if I kill the Gallery app, then load it up, then go straight to Pages, then I do not see a black bar. And now I don't see the black bar anymore :/

**Comment by sethladd** [comment]
cc @HansMuller

**Comment by abarth** [comment]
I fixed a similar bug recently.  I wonder if you had an old version.  Are you still able to reproduce the issue?

**Comment by sethladd** [comment]
Not sure what version (master? alpha?) was used to build it, but happy to try again with a new build. Let's keep this open until at least the next version of the gallery is built and tested.

**Comment by sethladd** [comment]
Unable to repro.
