### ISSUE TITLE
[google_maps_flutter]: Add elevation option for custom built markers

### ISSUE THREAD

**Issue by karthikk9828** [flutter/flutter#126628]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I have created a custom widget with an oval shape and some shadow around it and converted this widget into BitmapDescriptor by taking a screenshot of the widget(https://pub.dev/packages/screenshot).
Since my widget is oval shaped and has a shadow, the screenshot taken is rectangular and the shadow is clipped. If Itry adding some padding around the widget, the tappable area of the marker is getting messed up if there are overlapping markers nearby. It would be nice to provide an option to add `elevation` to `Marker()` object.

### Proposal

It would be nice to provide an option to add elevation to Marker() object.

**Comment by darshankawar** [comment]
Thanks for the report @karthikk9828 
Are you referring to `google_maps_flutter` package's Marker() object to have `elevation` property ?

**Comment by karthikk9828** [comment]
@darshankawar 
Yes, It would be great

**Comment by stuartmorgan** [comment]
We are constrained by the underlying SDKs that the plugin wraps, and they do not have a marker elevation property, so this is not something we can implement.
