### ISSUE TITLE
Flutter web crash on ios / android (safari, chrome, firefox)

### ISSUE THREAD

**Issue by Devslops** [flutter/flutter#126638]
**flutter doctor -v**
[✓] Flutter (Channel stable, 3.7.12, on Ubuntu 20.04.6 LTS 5.15.0-71-generic, locale fr_FR.UTF-8)
    • Flutter version 3.7.12 on channel stable at /home/user/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (il y a 3 semaines), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at /home/user/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/221.5080.210
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.65.20230510

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 113.0.5672.63

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Versions with issue tested** : 3.7.8 / 3.7.12 / 3.10.0

**Issue description :** Tested on iphones devices (Iphone 11-12-13-14, safari, chrome, firefox) the web app crash randomly in release mode when the view is drawn. The view is partialy drawn before web app crashes (crash when trying to draw the problematic widget).
After hours of research, the problem is related to the combinaison of borderRadius and border in container boxDecoration.

**Code with issue :** 
```dart
decoration: BoxDecoration(
  borderRadius: BorderRadius.circular(10),
  border: Border.all(
    color: grey14,
  ),
),  
```
**Code that works :** 
```dart
decoration: BoxDecoration(
  borderRadius: BorderRadius.circular(10),
),  
```
```dart
decoration: BoxDecoration(
  border: Border.all(
    color: grey14,
  ),
),  
```

```dart
 ClipRRect(
  borderRadius: BorderRadius.circular(5),
  child: Container(
    decoration: BoxDecoration(
      border: Border.all(
        color: grey14,
      ),
  ),
```

I couldn't reproduce the bug in debug mode, including on an ios emulator.
Build command execute to host my web app in production : flutter build web --verbose --profile --web-renderer html --pwa-strategy=none --dart-define=BASE_URL="$BASE_URL"

The only logs i have on production (safari, chrome, firefox browser console) are :
![imageedit_11_6098901460](https://github.com/flutter/flutter/assets/55704281/d381450a-1ae2-438c-b744-49cdfa090e97)
The last exception "Another exception was thrown: Instance of 'ErrorSummary" is endlessly spammed (the phone gets very hot :))
![image](https://github.com/flutter/flutter/assets/55704281/9b66da87-89da-4cf1-8179-b91ff8278e48)

On android, i've had same issue but the app does not crash all the time, it seems to depend on phone performances. The error doesn't seem to happen all the time (the logs are the same as on ios)

**Comment by JulienS69** [comment]
Hi, thank you so much for your solution. I had the same problem for a long time on browsers like Safari, with repeated spam of the same exception. Indeed, having both the border and border radius in the same widget caused a lot of issues. 

Thank you very much! Hoping for a fix to this problem very soon!

**Comment by huycozy** [comment]
Hi @Devslops 
I try this on both profile and release mode but can not reproduce the issue:

<details>
<summary>Demo</summary>

![Image from iOS](https://github.com/flutter/flutter/assets/104349824/6e924ebb-6ec0-463b-acf6-b4ece08b281b)

</details>

Can you provide the complete minimal sample code? Also, please check this [issue](https://github.com/flutter/flutter/issues/120787) if it's similar to your case as well.

**Comment by Devslops** [comment]
Hi @huycozy 

Steps to reproduce the environment of the issue:
- build app via : flutter build web --verbose --profile --web-renderer html --pwa-strategy=none
- host it on an nginx server via docker (image used : fischerscode/flutter-sudo:3.7.12)

**Comment by huycozy** [comment]
@Devslops Does the issue only happen if you host the web on a docker container? If so, please share the deployed web if it's exposed publicly so that we can try checking it.

Also, can you reproduce it with the local server from your machine directly (without using docker)?

**Comment by cksoft0807** [comment]
i notice a similar error. the app crashes with the -web-renderer html option in the browser on ios devices or the ios simulator. in the desktop browser everything works. canvaskit option also seems to work.

the app is complex, so i can't provide an example, but removing some "borderradius" seems to help a bit.
