### ISSUE TITLE
Converting Image to PNG data using `toByteData` does not work in all cases in the HTML renderer

### ISSUE THREAD

**Issue by eyebrowsoffire** [flutter/flutter#126611]
Converting Image to PNG data using `toByteData` does not work in all cases in the HTML renderer. In particular, cases where the image is sourced from RGBA data, it just completely fails to convert to PNG data.

**Comment by nt4f04uNd** [comment]
https://github.com/flutter/flutter/issues/119065 looks related

**Comment by eyebrowsoffire** [comment]
> #119065 looks related
Yep you're right. I'll close this as a duplicate of that issue.
