### ISSUE TITLE
Handle error 0x80070422 when downloading on Windows (related to windows update settings)

### ISSUE THREAD

**Issue by 09abhishek** [flutter/flutter#12664]
I am facing this error while updating SDK for Dart!
```
C:\Users>flutter doctor
Checking Dart SDK version...
Downloading Dart SDK 1.25.0-dev.11.0...
Start-BitsTransfer : The service cannot be started, either because it is disabled or because it has no enabled devices associated with it. (Exception from HRESULT: 0x80070422)
At C:\Users\git\flutter\bin\internal\update_dart_sdk.ps1:44 char:19
+ Start-BitsTransfer <<<<  -Source $dartSdkUrl -Destination $dartSdkZip
    + CategoryInfo          : InvalidOperation: (:) [Start-BitsTransfer], COMException
    + FullyQualifiedErrorId : StartBitsTransferCOMException,Microsoft.BackgroundIntelligentTransfer.Management.NewBitsTransferCommand

Error: Unable to update Dart SDK. Retrying...

Waiting for 3 seconds, press CTRL+C to quit ...
Terminate batch job (Y/N)?
```

**Note:**

Trusted Installer is running in my PC : 

![image](https://user-images.githubusercontent.com/16036641/31850719-ddea5f78-b674-11e7-9aa2-1116b52bb9ea.png)

Help me plz!

**Comment by 09abhishek** [comment]
Guys This issue has been solved by me... I just changed the setting of Windows Update! previously it was set no to find the updates automatically. I reverted the change back to normal to find the updates of windows..  now I am able to download the SDK!!

Please close this issue!
Thanks!

**Comment by Hixie** [comment]
cc @goderbauer fyi
maybe we should detect this condition somehow?

**Comment by 09abhishek** [comment]
@goderbauer @Hixie 
If you want to reproduce the error : just you guys need to stop two services : windows update service and Trusted installer, which will automatically lead to Exception (from HRESULT: 0x80070422) error while downloading SDK!

**Comment by amara21** [comment]
This error code occurs when you try to update your Windows 10 and it prevents you from doing it. An error message will appear on the screen which says installation failed.
You can fix this 0x80070422 error and can update your Windows 10 but for that, you are required to follow some steps.
1: Disable Network List Service
2: Disable IPv6 in Network Center
3: Verify Enable featured software data
If you want to know more fixes of this error then visit- [Windows 10 Update Error 0x80070422](url=http://www.pcerror-fix.com/6-solutions-fix-windows-10-update-error-0x80070422)

**Comment by iapicca** [comment]
Hi @09abhishek 
I'm closing this issue as it refer to an older version of Flutter.
If you are you still experiencing this issue with the latest version of Flutter,
you may want to open a new issue or comment below;
either way please provide your updated `flutter doctor -v`.
It would be helpful to have also your` flutter run --verbose`
and a self contained app on github (or the steps to reproduce it).
Thank you
