### ISSUE TITLE
Google maps flutter is laggy on Huawei P20 Pro

### ISSUE THREAD

**Issue by karthikk9828** [flutter/flutter#126635]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Use google_maps_flutter in a flutter project
2. Run the app in **Huawei P20 Pro with the screen resolution set at FHD+ (2220x1080)**
3. Try to move the map

### Expected results

Map should move smoothly

### Actual results

Map is laggy and screen gets stuck.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@karthikk9828 
Which version of Flutter are you seeing the behavior on ? Can you also provide a short video showing the behavior ?

**Comment by karthikk9828** [comment]
https://github.com/flutter/flutter/assets/44114533/380a72e9-2c11-4bcc-b957-fa72a3943a8d

@darshankawar 
Sorry for the late response. Please check this recording. Map is not moving at all

**Comment by darshankawar** [comment]
@karthikk9828 
Can you try to use the [plugin example](https://github.com/flutter/packages/tree/main/packages/google_maps_flutter/google_maps_flutter/example) on same device and see if you still get same behavior or not ?

**Comment by karthikk9828** [comment]
@darshankawar 
Should I try the custom implementation of moving the map using gesture recognizers as shown here?
https://github.com/flutter/packages/blob/main/packages/google_maps_flutter/google_maps_flutter/example/lib/scrolling_map.dart

**Comment by karthikk9828** [comment]
@darshankawar 
FYI If I change the screen resolution from FHD+ to HD+ on Huawei P20 Pro, map seems to be smooth
In some devices even after changing resolution this issue still exists

**Comment by darshankawar** [comment]
@karthikk9828 
I believe you are hitting same issue as https://github.com/flutter/flutter/issues/111268 so I suggest you to follow-up in that issue for further updates. Closing this as a duplicate. You may share your findings in that issue for better tracking. If you disagree, write in comments and I'll reopen it.
