### ISSUE TITLE
when i use showModalBottomSheet have some problem ，is work on verison 3.7.12 but not work on 3.10.0

### ISSUE THREAD

**Issue by kevin-lemon** [flutter/flutter#126653]
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.0, on Microsoft Windows [版本 10.0.22621.1555], locale zh-CN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.1)
[√] IntelliJ IDEA Ultimate Edition (version 2022.2)
[√] Connected device (5 available)
[√] Network resources
in flutter 3.10.0：
![image](https://github.com/flutter/flutter/assets/20926872/7db5a705-fdc9-4835-a652-205820828dcf)
in flutter 3.7.11：
<img width="239" alt="1683884826506" src="https://github.com/flutter/flutter/assets/20926872/4f739f54-c361-487c-98af-51a487e60cbd">

code:   
 showModalBottomSheet(
        context: context!,
        backgroundColor: Colors.transparent,
        isScrollControlled: true,
        routeSettings: RouteSettings(name: routeName),
        builder: (ctx) => AnimatedPadding(
              padding: MediaQuery.of(ctx).viewInsets,
              duration: const Duration(milliseconds: 0),
              child: Container(
                decoration: BoxDecoration(
                    color: Colors.white,
                    borderRadius: BorderRadius.only(
                        topLeft: Radius.circular(16.dp),
                        topRight: Radius.circular(16.dp))),
                child: SafeArea(
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      createTitleView(ctx),
                      Container(
                        height: 1.hdp,
                        color: AppColor.background,
                      ),
                      createContent()
                    ],
                  ),
                ),
              ),
            ));
  }

in 3.10.0  the keyboard Obscure showModalBottomSheet
but in 3.7.11 is work  showModalBottomSheet can move

**Comment by huycozy** [comment]
@kevin-lemon You can try this sample code to see if it works for your case:

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Tutorial',
      home: HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Flutter Tutorial'),
      ),
      body: Column(
        children: [
          Center(
            child: ElevatedButton(
              onPressed: () {
                showModalBottomSheet(
                  context: context,
                  builder: (context) => Padding(
                    padding: EdgeInsets.only(bottom: MediaQuery.of(context).viewInsets.bottom),
                    child: const SizedBox(height: 200, child: TextField()),
                  ),
                );
              },
              child: const Text(
                'showModalBottomSheet',
              ),
            ),
          ),
        ],
      ),
    );
  }
}

```
</details>

If it doesn't work, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this.

**Comment by ChrisElliotUK** [comment]
I have found that `MediaQuery.of(context).viewInsets.bottom` is not working correctly. When I print the value when I open a keyboard it prints as zero. (checked on iOS)

**Comment by kevin-lemon** [comment]
> I have found that `MediaQuery.of(context).viewInsets.bottom` is not working correctly. When I print the value when I open a keyboard it prints as zero. (checked on iOS)

i have same problem  on android 12 iqoo neo5 MediaQuery.of(context).viewInsets not work

**Comment by kevin-lemon** [comment]
i have same problem  on android 12 iqoo neo5 MediaQuery.of(context).viewInsets not work with flutter 3.10.1  but is work with flutter 3.7.11

same  code on flutter 3.10.0：
<img width="860" alt="微信截图_20230512203819" src="https://github.com/flutter/flutter/assets/20926872/45614697-ff30-423d-a6fb-c6c6214a7cb3">
same  code on flutter 3.7.11：
<img width="827" alt="微信截图_20230512205715" src="https://github.com/flutter/flutter/assets/20926872/4c635868-6aaa-4901-8d94-0374b28f1d61">


I find  on flutter 3.7.11 if open keyborad  other page will build  but on flutter 3.10.0  is not build  ,nothing happend!

same on bottomsheet,  3.7.11 will build on keyboard open,but on 3.10.0   is noting happend when open keyboard.

**Comment by mhbdev** [comment]
> MediaQuery.of(context).viewInsets.bottom

If you have an Scaffold implemented in your code make sure you set `resizeToAvoidBottomPadding` to `false`. I had the same problem in which viewInsets.bottom was always returning zero. by setting this parameter to false my problem is gone.

**Comment by ChrisElliotUK** [comment]
tried [this](https://github.com/flutter/flutter/issues/126653#issuecomment-1545723965) but it didn't work for me.

**Comment by kevin-lemon** [comment]
> 

`import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return ScreenUtilInit(
        designSize: const Size(375, 812),
        builder: (context, child) {
          return const MaterialApp(
            home: HomePage(),
          );
        });
  }
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Flutter Tutorial'),
      ),
      body: Column(
        children: [
          Center(
            child: ElevatedButton(
              onPressed: () {
                showModalBottomSheet(
                  context: context,
                  builder: (context) => Padding(
                    padding: EdgeInsets.only(bottom: MediaQuery.of(context).viewInsets.bottom),
                    child: const SizedBox(height: 200, child: TextField()),
                  ),
                );
              },
              child: const Text(
                'showModalBottomSheet',
              ),
            ),
          ),
        ],
      ),
    );
  }

}`

I find when us   `flutter_screenutil: 5.7.0 `，is happend on flutter  3.10.0，but on flutter 3.7.1 use   `flutter_screenutil: 5.7.0 ` is ok.

**Comment by kevin-lemon** [comment]
is flutter screenUtils bug.

**Comment by shayant98** [comment]
Does not work when adding "IsScrollControlled" to true and also adding a padding with viewInset. Any idea on a workaround. our app consists of many forms in bottomsheets, this degrades UX
