### ISSUE TITLE
[Impeller] TextDecoration dashed and dotted are rendering as solid.

### ISSUE THREAD

**Issue by ronjb** [flutter/flutter#126673]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

The code `Text('underline, dotted', TextStyle(decoration: TextDecoration.underline, decorationStyle: TextDecorationStyle.dotted))` renders like this:

<img width="204" alt="Screenshot 2023-05-12 at 8 19 01 AM" src="https://github.com/flutter/flutter/assets/1015193/fd7e936b-c0c3-4067-96d0-92675a5f7f5d">

with a solid line, when it should render like this:

<img width="183" alt="Screenshot 2023-05-12 at 8 19 16 AM" src="https://github.com/flutter/flutter/assets/1015193/c390b51e-777b-4c71-b557-6fb6d8c2bc2e">

### Expected results

I tried all the decoration styles for underline and expected this (which is what I see without Impeller):

<img width="312" alt="Screenshot 2023-05-12 at 8 16 59 AM" src="https://github.com/flutter/flutter/assets/1015193/898d89d2-5a77-4ca6-bb3c-92d30c43c0c7">

### Actual results

But got this with Impeller:

<img width="344" alt="Screenshot 2023-05-12 at 8 09 20 AM" src="https://github.com/flutter/flutter/assets/1015193/c14e9c0a-d0b8-4383-a185-c72f3d59ac27">

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: const Text('Impeller Text Decoration Test'),
      ),
      body: ListView(
        children: const <Widget>[
          DecoratedText(TextDecoration.underline, TextDecorationStyle.solid),
          DecoratedText(TextDecoration.underline, TextDecorationStyle.dashed),
          DecoratedText(TextDecoration.underline, TextDecorationStyle.dotted),
          DecoratedText(TextDecoration.underline, TextDecorationStyle.double),
          DecoratedText(TextDecoration.underline, TextDecorationStyle.wavy),
        ],
      ),
    );
  }
}

class DecoratedText extends StatelessWidget {
  const DecoratedText(this.decoration, this.decorationStyle, {super.key});

  final TextDecoration decoration;
  final TextDecorationStyle decorationStyle;

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Text(
        '${decoration.desc}, ${decorationStyle.desc}',
        style: TextStyle(
          fontSize: 22,
          decoration: decoration,
          decorationStyle: decorationStyle,
        ),
      ),
    );
  }
}

extension on Object {
  String get desc => toString().split('.').last;
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

<img width="344" alt="Screenshot 2023-05-12 at 8 09 20 AM" src="https://github.com/flutter/flutter/assets/1015193/c14e9c0a-d0b8-4383-a185-c72f3d59ac27">

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.3.1 22E772610a darwin-arm64, locale en-US)
    • Flutter version 3.10.0 on channel stable at /Users/ronbooth/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (3 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/ronbooth/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • iPad mini (6th generation) (mobile) • 46CD1EBD-35A0-466C-B2BF-2F36D4A57344 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)                     • macos                                • darwin-arm64   • macOS 13.3.1
      22E772610a darwin-arm64
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome
      113.0.5672.92

[✓] Network resources
    • All expected network resources are available.```

</details>

**Comment by jason-simmons** [comment]
The Flutter engine's text subsystem renders the dashed and dotted decorations using `DlPaint.setPathEffect(DlDashPathEffect)`.  That API is not currently implemented by Impeller's `DlDispatcher`.

@bdero @jonahwilliams

**Comment by chinmaygarde** [comment]
Is the [extended paragraph information we now have sufficient](https://github.com/flutter/engine/pull/41735) to address this?

**Comment by jonahwilliams** [comment]
We need to implement this ourselves, we have all of the information but need to generate the additional geometry.

**Comment by phuc-tranh-otsv** [comment]
I also get this issue when use decoration: TextDecoration.underline & decorationStyle: TextDecorationStyle.dashed.
Flutter 3.10.6

**Comment by phuc-tranh-otsv** [comment]
My solution is **disable** Impeller on iOS.
- With Debug mode: pass **--no-enable-impeller** to the flutter run command.
- With Release mode: add <key>FLTEnableImpeller</key> <false /> in Info.plist file.

**Comment by matanlurey** [comment]
Quick update from discussing this issue with @jonahwilliams, recorded here so I remember what to work on tomorrow :)

- We noted that [`dl_path_effect.h`](https://github.com/flutter/engine/blob/659cdfc5a56840baed7f5481bbe4c22a173e851c/display_list/effects/dl_path_effect.h) is misleading, other path effects are supported and used today.
- Despite the directory, [`paragraph_skia.cc`](https://github.com/flutter/engine/blob/659cdfc5a56840baed7f5481bbe4c22a173e851c/third_party/txt/src/skia/paragraph_skia.cc) is _not_ vendored, and is authored by us. For example, here is where [`drawLine`](https://github.com/flutter/engine/blob/659cdfc5a56840baed7f5481bbe4c22a173e851c/third_party/txt/src/skia/paragraph_skia.cc#L116-L123) is implemented today.
- Impeller's [`dl_dispathcer.cc`'s `setPathEFfect`](https://github.com/flutter/engine/blob/659cdfc5a56840baed7f5481bbe4c22a173e851c/impeller/display_list/dl_dispatcher.cc#L522-L526) might stay as a NOP for Impeller, and instead we'd use the above `SkParagraph` to finalize the implementation.

**Comment by bdero** [comment]
Not sure what you're planning on doing for this, but in case we end up going with an impeller-centric solution, this is pulled/refined from the Impeller chat a few months back:

Dashes are supposed to follow curves for a certain length and can't just be lines. So to get correct results we'd need to analytically segment path components. An easy solution would be to use a more numerical approach: Create a component-agnostic routine in `impeller::Path` that allows sampling a position for a given distance around a given contour (optimizing this subproblem if/when necessary -- depending on how correct we need to be, ‎De Casteljau alone may not be suitable for walking the beziers), and then use this utility to carve out a new `impeller::Path` based on the given dot/dash pattern (sampling a bunch of points per dash and tiny 2-point line contours per dot so that square points appear rotated in the correct direction).

**Comment by jonahwilliams** [comment]
I think the dashes dots can be implemented by taking the dash information from the Skia dash info and building a path with the correct start/stop commands. We don't need to worry about general purpose path dashing, there is no support for that via the dart API.

**Comment by matanlurey** [comment]
Hey Brandon, thanks for that, super interesting.

I'm going to try Jonah's proposed approach mostly because it's the least amount of work to (as he pointed out) implement our public API, but I do appreciate the pointers!

**Comment by bdero** [comment]
Oh, does Skia have an API to "bake" decorations into an `SkPath` that we can piggyback off of? My comment is more about how we could approach the baking part if not. Just to be clear, I'm not saying we should bake text decoration support into Aiks/`impeller::Path`. ;)

**Comment by jonahwilliams** [comment]
oh, I was just thinking like:

```dart
var dx = 0.0;
var path = Path();
bool on = true;
while (dx <= length) {
  if (on) {
     path.moveTo(dx, dy);
     dx += onLength;
     path.lineTo(math.min(dx, length) dy);
     path.close();
   } else {
     dx += offLength;
   }
   on = !on;
}
```

But like, in C++

**Comment by bdero** [comment]
Oh derp, it took me a while to register that these text decorations only need to be straight lines... yeah disregard. 😄

**Comment by matanlurey** [comment]
Coming back to this issue, and adding some notes I took when I chatted with @jonahwilliams (paraphrased by me):

@matanlurey:

> How do I map [this](https://github.com/flutter/engine/blob/1351810348317ce69ef2c163fd1b246354fd20d4/impeller/display_list/dl_unittests.cc#L450-L461) to `TextDecoration`?

@jonahwilliams:

> `SkParagraph` is an interceptor, i.e. "I see that this is text with an underline".
> It tells the _Canvas_ to `drawText` _and_ to `drawLine`.
> _DisplayList_ and _Impeller_ will just see `drawText`, `drawLine`.
> ... and `SkTextBlob` is the _result_ of this intercepted call.
>
> `dart:ui` draws a `Paragraph` (string, font, sizes, etc) that goes directly through Skia (well, `SkParagraph`)
> `SkParagraph` has a delegate you set (i.e. [`SkiaParagprah`](https://github.com/flutter/engine/blob/659cdfc5a56840baed7f5481bbe4c22a173e851c/third_party/txt/src/skia/paragraph_skia.cc#L46C1-L46C66), which is different than `SkParagraph`)
> "Here is a `SkTextBlob` and other configuration, figure out how to draw that"

So the overall flow is:

```mermaid
flowchart LR
  dart_ui["`dart:ui`"]
  sk_paragraph["`SkParagraph`"]
  steps["{text, layout, shaping}"]
  delegate["delegate to renderer"]
  dart_ui --> sk_paragraph
  sk_paragraph --> steps
  steps --> delegate
```

`SkTextBlob`, on the Impeller backend, will `drawTextBlob` "what is the font object, and glyph IDs."
- We feed it back into Skia to get the atlas (delegates further to CoreText/FreeType/etc), eventually HarfBuzz

A recommend place to start to understand the flow is changing the stroke width to underline "bigger" and go from there.

**Comment by Hixie** [comment]
given our current infrastructure and architecture the best way to test this is probably to add a golden test in the framework repo and flag the new behaviour as ok before the roll goes in.

**Comment by matanlurey** [comment]
@Hixie:

> given our current infrastructure and architecture the best way to test this is probably to add a golden test in the framework repo and flag the new behaviour as ok before the roll goes in.

My understanding is there no way to do golden tests with Impeller in the framework layer.

Quoting @jonahwilliams in chat, emphasis mine:

> We are testing most of this code, text decorations are unique. The problem isn't GPU readback or not, its """"just""" engine configuration issues means that **we don't compile the library that does text and impeller in a configuration that support golden tests**
>
> To fix this, **we need to take the software backend support we have in the playground unittests and extend it to work with flutter_tester**, and then the rest of the engine unit tests will """just""" work.

**Comment by jonahwilliams** [comment]
I'm not aware of a mechanism that allows us to use Skia gold _on device_. The current framework golden tests are software backend only which does not support Impeller.

**Comment by Hixie** [comment]
Yeah it would have to be a hand-rolled test rather than Skia Gold, probably. cc @Piinks

**Comment by matanlurey** [comment]
Just to be clear, my understanding is there is no way to do that _today_. It's not a matter of "Impeller doesn't work on Skia Gold", it's "Impeller doesn't have any sort of way to do automated golden-file testing when bundled with the framework".

(At least not without building out something very custom, correct me if I'm wrong @jonahwilliams)

**Comment by jonahwilliams** [comment]
Not with flutter_test, only with a physical backend. I'm not aware of a way to send skia gold results from a devicelab test.

**Comment by jonahwilliams** [comment]
If we can do that though, that would certainly be a solution.

**Comment by Piinks** [comment]
> I'm not aware of a way to send skia gold results from a devicelab test.

I think folks have looked into this in the past and have found it possible, but then either left the team or moved onto another project.

If we can generate an image and have access to the goldctl binary, we can send images to the Gold server.

The goldctl binary is distributed through cipd, and for authentication it currently uses the luci context, but it can also authenticate through a service account like it did when we were using cirrus.
