### ISSUE TITLE
Firebase_messaging issue at FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler); after upgrading flutter sdk to 3.7.12

### ISSUE THREAD

**Issue by madhugill** [flutter/flutter#126658]
Hi,

I am stuck from last 2-3 days in a firebase_messaging plugin related issue when I am using 
FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);  //mentioned logs below for the reference

if I comment out this line error goes but notification not working in that case in background.

Note: I am facing this issue since I have upgraded my flutter sdk to 3.7.12 from 2.10.0

**Logs:**

E/MethodChannel#plugins.flutter.io/firebase_messaging( 5016): Failed to handle method call
E/MethodChannel#plugins.flutter.io/firebase_messaging( 5016): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference
E/MethodChannel#plugins.flutter.io/firebase_messaging( 5016): 	at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundExecutor.setCallbackDispatcher(FlutterFirebaseMessagingBackgroundExecutor.java:58)
E/MethodChannel#plugins.flutter.io/firebase_messaging( 5016): 	at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService.setCallbackDispatcher(FlutterFirebaseMessagingBackgroundService.java:89)
E/MethodChannel#plugins.flutter.io/firebase_messaging( 5016): 	at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingPlugin.onMethodCall(FlutterFirebaseMessagingPlugin.java:469)
E/MethodChannel#plugins.flutter.io/firebase_messaging( 5016): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#plugins.flutter.io/firebase_messaging( 5016): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#plugins.flutter.io/firebase_messaging( 5016): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#plugins.flutter.io/firebase_messaging( 5016): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#plugins.flutter.io/firebase_messaging( 5016): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#plugins.flutter.io/firebase_messaging( 5016): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#plugins.flutter.io/firebase_messaging( 5016): 	at android.os.Looper.loopOnce(Looper.java:201)
E/MethodChannel#plugins.flutter.io/firebase_messaging( 5016): 	at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#plugins.flutter.io/firebase_messaging( 5016): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
E/MethodChannel#plugins.flutter.io/firebase_messaging( 5016): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_messaging( 5016): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#plugins.flutter.io/firebase_messaging( 5016): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/flutter ( 5016): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference
E/flutter ( 5016): 	at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundExecutor.setCallbackDispatcher(FlutterFirebaseMessagingBackgroundExecutor.java:58)
E/flutter ( 5016): 	at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService.setCallbackDispatcher(FlutterFirebaseMessagingBackgroundService.java:89)
E/flutter ( 5016): 	at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingPlugin.onMethodCall(FlutterFirebaseMessagingPlugin.java:469)
E/flutter ( 5016): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/flutter ( 5016): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter ( 5016): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/flutter ( 5016): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter ( 5016): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter ( 5016): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 5016): 	at android.os.Looper.loopOnce(Looper.java:201)
E/flutter ( 5016): 	at android.os.Looper.loop(Looper.java:288)
E/flutter ( 5016): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
E/flutter ( 5016): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 5016): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/flutter ( 5016): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/flutter ( 5016): )
E/flutter ( 5016): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
E/flutter ( 5016): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
E/flutter ( 5016): <asynchronous suspension>
E/flutter ( 5016): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:518:43)
E/flutter ( 5016): <asynchronous suspension>
E/flutter ( 5016): #3      MethodChannelFirebaseMessaging.registerBackgroundMessageHandler (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:182:7)
E/flutter ( 5016): <asynchronous suspension>

---------------------------------------------

**pubspec.yaml**

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.1
  firebase_messaging: ^14.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

--------------------------------------

**flutter doctor**

[✓] Flutter (Channel stable, 3.7.12, on macOS 11.5.2 20G95 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    ! CocoaPods 1.10.1 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

Please help me out.

Thank You.

**Comment by darshankawar** [comment]
@madhugill 
`firebase_messaging` related issues need to be reported in dedicated repo: https://github.com/firebase/flutterfire/issues
Closing from here.
