### ISSUE TITLE
Hot reload always back to initialRoute go_router

### ISSUE THREAD

**Issue by isshort** [flutter/flutter#126662]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Hello to everyone , i just upgrade  flutter from 3.7.0 to 3.10.0 & dart sdk to dart 3 
When i edit my source code then save it(CTRL+S) its always go back to the  initial router it was happened since I upgraded the flutter version .

I recorded the video as bellow. 

https://github.com/flutter/flutter/assets/37234355/20350822-240d-497b-8e0e-331ee21ec11d

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.2.1 22D68 darwin-arm64, locale ky-KG)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.78.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

</details>

### Expected results

go router should not return to the first page after saving the code
### Actual results

go router should not return to the first page after saving the code
### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by erdenejargalb** [comment]
I have same issue. Navigator.of(context).push not working changed to pushNamed also doesn't work.

**Comment by isshort** [comment]
> @darshankawar  Thanks for your quick response. it the problem was occurred in my published  project then I  created new flutter project but the problem still persists.
the source code is as bellow 


### Code sample

 

```dart
void main() {
   runApp(const MyApp());
   }

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      routerConfig: AppRouter.router,
    );
  }
}

class AppRouter {
  static GoRouter get router => GoRouter(routes: [
        GoRoute(
          path: '/',
          builder: (context, state) => const HomeView(),
        ),
        GoRoute(
          path: '/new',
          builder: (context, state) => const NewsView(),
        )
      ]);
}

 
class HomeView extends StatelessWidget {
  const HomeView({super.key});
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Home Title'),
      ),
      body: Center(
          child: ElevatedButton(
              onPressed: () {
                context.go('/new');
              },
              child: const Text('Go to another page'))),
    );
  }
}

class NewsView extends StatelessWidget {
  const NewsView({super.key});
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('NewsView Title  as'),
      ),
    );
  }
}


```

**Comment by isshort** [comment]
The problem was with AppRouter class get attributes I removed the get attributes as bellow  and the problem was fixed. 

  ```Dart
class AppRouter {
  AppRouter._();
  static GoRouter router = GoRouter(
    routerNeglect: true,
    debugLogDiagnostics: true,
    redirect: (context, state) {
      return null;
    },
    routes: [
      GoRoute(
        path: '/',
        builder: (context, state) => const HomeView(),
      ),
      GoRoute(
        path: '/new',
        builder: (context, state) => const NewsView(),
      )
    ],
  );
}
```

**Comment by darshankawar** [comment]
@isshort 
Check if the [recent breaking changes](https://pub.dev/packages/go_router/changelog#700) introduced in the package helps in your case or not.

**Comment by FaFre** [comment]
Same problem with

```dart
return MaterialApp.router(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        brightness: Brightness.light,
      ),
      routerConfig: GoRouter(
        routes: [
          GoRoute(
            path: '/',
            redirect: (context, state) => '/list',
          ),
          GoRoute(
            path: '/list',
            builder: (context, state) => const ItemListPage(),
            routes: [
              GoRoute(
                path: 'filter',
                builder: (context, state) => const FilterPage(),
              )
            ],
          ),
        ],
      ),
    );
  }
```

**Comment by maRci002** [comment]
Maybe duplication of  #105553
