### ISSUE TITLE
CircularProgressIndicator.adaptive radius propery 

### ISSUE THREAD

**Issue by Shahmirzali-Huseynov** [flutter/flutter#126693]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I want to increase the size of the CupertinoActivityIndicator. `strokeWidth` in `CircularProgressIndicator.adaptive` does not affect to the size of the CupertinoActivityIndicator.

### Proposal

can you add the `radius` property to `CircularProgressIndicator.adaptive` ? 

<img width="449" alt="Screenshot 2023-05-12 at 20 05 53" src="https://github.com/flutter/flutter/assets/49102327/b06aa226-959f-4e4f-8188-0e6454f5681a">

<img width="507" alt="Screenshot 2023-05-12 at 20 08 33" src="https://github.com/flutter/flutter/assets/49102327/f8fdf458-2d51-410d-b694-c90ce23f18ed">

**Comment by maRci002** [comment]
```dart
const SizedBox(
  height: 150,
  width: 150,
  child: CircularProgressIndicator.adaptive(),
);
```

**Comment by Juliotati** [comment]
@Shahmirzali-Huseynov  `strokeWidth` is for android.
You'll have to wrap it in a SizedBox like @maRci002 mentioned

**Comment by Shahmirzali-Huseynov** [comment]
Thanks for your answers, Actually, I noticed that the `strokeWidth` property is not about size 🙂. and SizedBox is not working. 

my solution: Transform.scale

```
Center(
      child: Transform.scale(
        scale: Platform.isIOS ? 1.5 : 1,
        child: CircularProgressIndicator.adaptive(
          backgroundColor: context.primaryColors.primary100,
        ),
      ),
    );
```
