### ISSUE TITLE
Outdated signature in packages/integration_test/lib/integration_test_driver_extended.dart documentation

### ISSUE THREAD

**Issue by githubmonkey** [flutter/flutter#126690]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

The documentation for IntegrationDriver recommends this snippet in some places

```
await integrationDriver(
    onScreenshot: (String screenshotName, List<int> screenshotBytes) async {
      final File image = File('$screenshotName.png');
      image.writeAsBytesSync(screenshotBytes);
      // Return false if the screenshot is invalid.
      return true;
    },
  );
```

After moving to Flutter 3.10 the onScreenshot signature is caught by the dart analyzer. Changing it to this fixed the issue for me. 

```
    onScreenshot: (String screenshotName, List<int> screenshotBytes, [Map<String, Object?>? args]) async {
``` 

### Expected results

No error

### Actual results

error: The argument type 'Future<bool> Function(String, List<int>)' can't be assigned to the parameter type 'Future<bool> Function(String, List<int>, [Map<String, Object?>?])?'. (argument_type_not_assignable at [xxx] test_driver/integration_test.dart:13)

### Code sample

<details><summary>Code sample</summary>

See here: (https://api.flutter.dev/flutter/package-integration_test_integration_test_driver_extended/integrationDriver.html)

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by LuffyKing** [comment]
I can confirm this as well, and @githubmonkey's solution works.

**Comment by LuffyKing** [comment]
I can confirm this as well, and @githubmonkey's solution works.
