### ISSUE TITLE
[pub outdated] Show both original and overridden dependency information

### ISSUE THREAD

**Issue by JCKodel** [flutter/flutter#126699]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Due to an incompatibility with Flutter 3.10, I have to use a dev version of one package, until the final version is released.

I track outdated packages with `flutter pub outdated` command, but, when there are overridden packages, the real version information is hidden.

For example:

My pubspec.yaml states:

```yaml
dependencies:
  # This was added by VSCode pub add package extension, so
  # it grabs the latest version automatically
  adaptive_dialog: ^1.8.3

dependency_overrides:
  # This fixes an issue where this package cannot be used
  # in Flutter 3.10
  adaptive_dialog:  1.9.0-no-macos.2
```

I want to know when the version `1.8.3` can be upgraded, but `flutter pub outdated` hides this information:

```console
> flutter pub outdated
Showing outdated packages.
[*] indicates versions that are not the latest available.

Package Name     Current                         Upgradable                      Resolvable                      Latest

direct dependencies:
adaptive_dialog  *1.9.0-no-macos.2 (overridden)  *1.9.0-no-macos.2 (overridden)  *1.9.0-no-macos.2 (overridden)  1.8.3
dynamic_color    *1.6.3                          *1.6.3                          *1.6.3                          1.6.4
intl             *0.18.0                         *0.18.0                         *0.18.0                         0.18.1

dev_dependencies: all up-to-date.
You are already using the newest resolvable versions listed in the 'Resolvable' column.
Newer versions, listed in 'Latest', may not be mutually compatible.
```

### Proposal

Overriden dependencies should not override the normal output of `flutter pub outdated`, just add this information:

```console
> flutter pub outdated
Showing outdated packages.
[*] indicates versions that are not the latest available.

Package Name     Current              Upgradable          Resolvable          Latest

direct dependencies:
adaptive_dialog  1.8.3                1.8.3               1.8.3               1.8.3
              ^  *1.9.0-no-macos.2   *1.9.0-no-macos.2    *1.9.0-no-macos.2   (overridden)  
dynamic_color    *1.6.3              *1.6.3               *1.6.3              1.6.4
intl             *0.18.0             *0.18.0              *0.18.0             0.18.1

dev_dependencies: all up-to-date.
You are already using the newest resolvable versions listed in the 'Resolvable' column.
Newer versions, listed in 'Latest', may not be mutually compatible.
```

Notice how `adaptive_dialog` has now 2 rows: the original (and needed) one and the overridden, so we can visualize

1) If the package 1.8.3 is already out of date (so we can perhaps disable the override)

2) If the override is the latest version available (so we can test release candidates)

**Comment by stuartmorgan** [comment]
`flutter pub` is just a wrapper around `dart pub`; `dart pub` feature requests need to be filed in [the pub issue tracker](https://github.com/dart-lang/pub/issues).
