### ISSUE TITLE
[Impeller] Investigate framebuffer blend based backdrop blurs.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#126695]
A BackdropFilter applies some filter effect to all rendering "behind" the location of the screen where it is drawn. Mechanically, this works by stopping the current entity pass, saving the result as a texture, running that texture through the filter, and then filling that texture back onto the screen. This is require because the backdrop filter itself applies to "everything" and not particular widget subtrees. When there are multiple backdrop filters in a scene, this results in these full screen texture fills running multiple times, which can be extra expensive.

One optimization we could try for iOS to avoid the pass ending/texture fill switcharoo would be to implement a directional blur with the framebuffer blend feature. This would allow us to sample from the current pass without ending it, which would reduce the amount of texture work there. BUT, this would remove our ability to do the texture shrinking trick that we do for general purpose blurs.

To evaluate this tradeoff, we could use the example applications posted in https://github.com/flutter/flutter/issues/126353 . 

![image](https://github.com/flutter/flutter/assets/8975114/7002b883-f6e7-4227-8018-49436a13d709)

**Comment by jonahwilliams** [comment]
Another advantage is that it makes techniques like https://github.com/flutter/flutter/issues/126696 easier, since all we need to do is adjust the geometry.

**Comment by bdero** [comment]
This has come up a couple up before in the weekly IIRC. I don't think the immense fragment load increase can offset the RT switches and two (smaller than the parent pass) texture allocations.

**Comment by jonahwilliams** [comment]
Probably true! though it might work okay for the other filters - not that they are used very often at all.

However, I suspect the real gain would come from fixing https://github.com/flutter/flutter/issues/126696 . If we can't get the math right for the clipping, then this approach would probably still have less fragment load if the backdrop filter only covers a small region of the screen.

**Comment by chinmaygarde** [comment]
@jonahwilliams says we can close this as we have better alternatives.
