### ISSUE TITLE
Problem accurred "flutter_keyboard_visibility"  No signature of method  issue comes after flutter upgrade 3.7.12 to 3.10.0 

### ISSUE THREAD

**Issue by rahulr3096** [flutter/flutter#126694]
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\laptop\AppData\Local\Pub\Cache\hosted\pub.dev\flutter_keyboard_visibility-5.4.2\android\build.gradle' line: 24

* What went wrong:
A problem occurred evaluating project ':flutter_keyboard_visibility'.
> No signature of method: build_2lhbhim0jxkma38rf9d3xuzsq.android() is applicable for argument types: (build_2lhbhim0jxkma38rf9d3xuzsq$run_closure2) values: [build_2lhbhim0jxkma38rf9d3xuzsq$
run_closure2@6c8f0022]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
Running Gradle task 'assembleDebug'...                              7.0s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by stuartmorgan** [comment]
Issues with third-party packages need to be reported to the package authors, rather than the Flutter project.

**Comment by mostafasaadamin** [comment]
are you find any solution?!
