### ISSUE TITLE
AnchorElement can't find project files in hosted web app

### ISSUE THREAD

**Issue by Sarraj-Sahar** [flutter/flutter#126752]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

You will need to have an assets folder with a file under it, so I created a repo with a simplified version of my code [here](https://github.com/Sarraj-Sahar/download_pdf_from_asset_test), if you download the project and run it locally, everything should work fine: the pdf file under assets gets downloaded when you click the download button. But the issue is when I tried **hosting** the web app [here](https://download-pdf-from-asset-test.vercel.app/#/) the file is no longer "found". When I try to download it , it downloads a "404.html" file and says file not found.

The first thing that I thought of was yes it makes sense that it wouldn't find the specified file since it wouldn't know where "**assets**/..." is since I am not running the app locally but in the same project, I am getting images from the "**assets**" folder and they are loading successfully even on the hosted version so it "does know" where the path is...

Again the issue only exists with the hosted version of the app.

### Expected results

Files under the assets folder should be "found" and downloaded on the hosted version of the app.

### Actual results

When I try to download a file from my hosted web app, the app does not find the file.

### Code sample

<details><summary>Code sample</summary>

```dart
// Please see the linked repo above , to run this code sample you will need to add some assets

import 'dart:html';

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Column(
            children: [
              Image.asset(
                "assets/mochi.png",
                height: 90,
              ),
              Padding(
                padding: EdgeInsets.all(8.0),
                child: ElevatedButton(
                  onPressed: () {
                    AnchorElement anchorElement = new AnchorElement(
                        href: "assets/Sahar_Sarraj_Resume.pdf");
                    anchorElement.download = "sahar_resume";
                    anchorElement.click();
                  },
                  child: Text("Download"),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[screen-capture.webm](https://github.com/flutter/flutter/assets/82158584/d74b57d2-f39b-454c-be70-72dab4c15a0c)

</details>

**Comment by huycozy** [comment]
Thanks for the report! Reproduced this issue on the latest stable and master channels. 

It works as expected when running it locally (both debug and release modes) but has the issue when hosting the built web with local web server. I was testing with python server in local machine:

```
127.0.0.1 - - [15/May/2023 16:21:52] code 404, message File not found
127.0.0.1 - - [15/May/2023 16:21:52] "GET /assets/house.png HTTP/1.1" 404 -
127.0.0.1 - - [15/May/2023 16:21:57] "GET / HTTP/1.1" 304 -
```

Labeling the issue for further insights.

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.10.0 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (35 hours ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.5672.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.11.0-6.0.pre.63, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.11.0-6.0.pre.63 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7b8f7a2a64 (5 hours ago), 2023-05-14 17:42:29 -0400
    • Engine revision 326de1d849
    • Dart version 3.1.0 (build 3.1.0-110.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.5672.92

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by christopherfujino** [comment]
@ditman is this supposed to work?

**Comment by Sarraj-Sahar** [comment]
@christopherfujino exactly my question, I'm not too sure if this is actually a bug or if it's "normal" for it not to work. But then the question would be how can I implement downloading assets in hosted web apps?

**Comment by ditman** [comment]
@christopherfujino, @Sarraj-Sahar absolutely, we use dozens of assets across many web apps (including the gallery)

I think the problem is that:

```
href: "assets/Sahar_Sarraj_Resume.pdf"
```

Is not "asset-aware"; it doesn't know what Flutter does to assets when it builds (see https://github.com/flutter/flutter/issues/80784).

The PDF is actually deployed to:

* https://download-pdf-from-asset-test.vercel.app/assets/assets/Sahar_Sarraj_Resume.pdf (note the `assets/assets`, this has to do with defining a directory to "grab all asets" in the pubspec.yaml IIRC).

The solution for the web is to use the `ui.webOnlyAssetManager` to retrieve the correct URL of the asset `'assets/Sahar_Sarraj_Resume.pdf'`. Here's an example: 

Web maps plugin translating a URL into the correct location of an asset:

https://github.com/flutter/packages/blob/eabaaccd0580a2e9f171f048a68070ea6f63a566/packages/google_maps_flutter/google_maps_flutter_web/lib/src/convert.dart#L264

That was defined like so:

https://github.com/flutter/packages/blob/eabaaccd0580a2e9f171f048a68070ea6f63a566/packages/google_maps_flutter/google_maps_flutter/example/lib/marker_icons.dart#L80-L81C40

**Comment by Sarraj-Sahar** [comment]
thank you @ditman ! , it works now.

**Comment by ditman** [comment]
I think this is a good candidate for "weirdness of the web platform". I'll keep track of this issue for future documentation enhancements!

**Comment by christopherfujino** [comment]
> I think this is a good candidate for "weirdness of the web platform".

Are you writing an encyclopedia? :P

**Comment by ditman** [comment]
> Are you writing an encyclopedia? :P

@christopherfujino at first I thought a single page on flutter.dev would be enough... but after a couple of years in the team I'm not so sure anymore :P
