### ISSUE TITLE
Issue from website page Internationalizing Flutter Apps

### ISSUE THREAD

**Issue by ghqureshi** [flutter/flutter#12670]
From URL: https://flutter.io/tutorials/international/index.md

Hi, I tried to follow the instructions. I did update the pubspec.yaml file.

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

But import statement gave following error in IntelliJ

"Target of URI doesn't exists: 'package:flutter_localizations/flutter_localizations.dart'

**Comment by ghqureshi** [comment]
Hi.. I found a missing step. In IntelliJ I need to do 'Package Get'.  I am new to development but I think a link to this page will help https://flutter.io/using-packages/#searching-for-packages

**Comment by sethladd** [comment]
cc @mit-mit

**Comment by mit-mit** [comment]
Hi @ghqureshi we are supposed to prompt you to help you remember that step. Can you take a look at this bug https://github.com/flutter/flutter-intellij/issues/1417, and let me know if you saw that dialog?

**Comment by campio97** [comment]
Hello, i have this problem.
I run `flutter pub get` but when i import `import 'package:flutter_localizations/flutter_localizations.dart';` in my main.dart file, visual studio say "import 'package:flutter_localizations/flutter_localizations.dart';".
All the other dependencies work.
### **pubspec.yaml**
`dependencies:`
___`flutter:`
______`sdk: flutter`
___`flutter_localizations: `
______`sdk: flutter`
___`flutter_cupertino_localizations: ^1.0.1` Doesn't work too.
`.`
`.`
`.`

**Comment by mit-mit** [comment]
This is a very old bug; can you kindly file a new bug, an include detailed repro steps.

**Comment by Maik3345** [comment]
> Hello, i have this problem.
> I run `flutter pub get` but when i import `import 'package:flutter_localizations/flutter_localizations.dart';` in my main.dart file, visual studio say "import 'package:flutter_localizations/flutter_localizations.dart';".
> All the other dependencies work.
> 
> ### **pubspec.yaml**
> `dependencies:`
> ___`flutter:`
> ______`sdk: flutter`
> ___`flutter_localizations: `
> ______`sdk: flutter`
> ___`flutter_cupertino_localizations: ^1.0.1` Doesn't work too.
> `.`
> `.`
> `.`

Hi @campio97, for fix this error i try creted one new project with flutter and pass my lib files and other configurations. then build the application for the web and work correctly. try it
