### ISSUE TITLE
I found that there is a performance issue with the SelectionArea component. 

### ISSUE THREAD

**Issue by jxq0308** [flutter/flutter#126791]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1.After long pressing the selection button, it often fails to select the correct word
2.the toolbar cannot pop up when the handle is selected

### Expected results

After selecting at least one word, drag the handle and a copy button will pop up

### Actual results

Optimize the performance of selectword by selecting at least one word

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```
SelectionArea(
                                    focusNode: _robotFocusNode,
                                    onSelectionChanged: (text) {
                                      print("================选择变更robot");
                                      if (_robotSelectableRegionState != null) {
                                        _robotSelectableRegionState!
                                            .showToolbar();
                                      }
                                    },
                                    contextMenuBuilder:
                                        (c, selectableRegionState) {
                                      _robotSelectableRegionState =
                                          selectableRegionState;
                                      return AdaptiveTextSelectionToolbar
                                          .selectableRegion(
                                        selectableRegionState:
                                            selectableRegionState,
                                      );
                                    },
                                    magnifierConfiguration:
                                        TextMagnifierConfiguration.disabled,
                                    child: MarkdownWidget(
                                      key: _markdownKey,
                                      data: widget.msg,
                                    ),
                                  )
</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```
![2](https://github.com/flutter/flutter/assets/22001732/ff957a4f-a685-4a96-b1db-79aa84a3854d)

</details>

**Comment by huycozy** [comment]
Thanks for the report! This is a known issue being tracked at https://github.com/flutter/flutter/issues/126652. 

Closing this issue as a duplicate, so please follow up on it for further updates.
