### ISSUE TITLE
package:camera_android:0.10.8 breaks framework tests

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#126710]
I believe the change for this happened in https://github.com/flutter/packages/pull/3822/files#diff-2d52b2f7f5cade86264e5d4a9e40b52a90d78eef1b38af8914c90a822d238bd1

Here is an example integration test that failed: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8781280338522918225/+/u/run_test.dart_for_tool_integration_tests_shard_and_subshard_2_4/test_stdout

```
[+2499 ms] Compiling build file '/b/s/w/ir/x/w/.pub-cache/hosted/pub.dev/camera_android-0.10.8/android/build.gradle' using BuildScriptTransformer.
[ +299 ms] Creating configuration androidTestUtil
[        ] Warning: The plugin camera_android requires Android SDK version 33.
[        ] For more information about build configuration, see https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
[   +1 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
[        ] You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
[        ] See https://docs.gradle.org/7.6.1/userguide/command_line_interface.html#sec:command_line_warnings
[ +491 ms] Running Gradle task 'assembleDebug'... (completed in 80.5s)
[   +3 ms] "flutter apk" took 81,025ms.
[  +13 ms] ensureAnalyticsSent: 0ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[   +3 ms] exiting with code 1

[ +100 ms] FAILURE: Build failed with an exception.
[   +2 ms] * Where:
[        ] Build file '/b/s/w/ir/x/w/.pub-cache/hosted/pub.dev/camera_android-0.10.8/android/build.gradle' line: 52
[        ] * What went wrong:
[        ] A problem occurred evaluating project ':camera_android'.
[        ] > Could not set unknown property 'baseline' for task ':camera_android:lint' of type com.android.build.gradle.tasks.LintGlobalTask.
```

In the pub roll https://github.com/flutter/flutter/pull/126367

I am going to temporarily pin this package to un-block the roll.

**Comment by christopherfujino** [comment]
@reidbaker can you or someone on your team take a look at this one?

**Comment by reidbaker** [comment]
@camsim99 you are the most familiar with camera changes. 

here is what I see which is odd. It is like we are trying to run lint but this example does not know about lint baseline. 
```
 FAILURE: Build failed with an exception.
[   +2 ms] * Where:
[        ] Build file '/b/s/w/ir/x/w/.pub-cache/hosted/pub.dev/camera_android-0.10.8/android/build.gradle' line: 52
[        ] * What went wrong:
[        ] A problem occurred evaluating project ':camera_android'.
[        ] > Could not set unknown property 'baseline' for task ':camera_android:lint' of type com.android.build.gradle.tasks.LintGlobalTask.

```

**Comment by alexandru-drincianu** [comment]
Is there a way to get past this until the fix?

**Comment by nadeemabualarayes** [comment]
same error

**Comment by venus-yangbo** [comment]
same error too

**Comment by linhnguyen2307** [comment]
> Is there a way to get past this until the fix?
before official fix for this issue, i have comment this line at at location : ~\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\camera_android-0.10.8\android\build.gradle
lint {
        //baseline = file("lint-baseline.xml")
    }

after that re-run project and it's work

**Comment by mhanzla80** [comment]
I was also facing this issue but by upgrading my project gradle version to latest fix my problem.

In `gradle-wrapper.properties` update `distributionUrl` to
`distributionUrl=https\://services.gradle.org/distributions/gradle-7.6.1-all.zip`

and also update `classpath` in `android/build.gradle` to
`classpath 'com.android.tools.build:gradle:7.4.2'`
