### ISSUE TITLE
[go_router_builder] Allow required query parameters

### ISSUE THREAD

**Issue by ValentinVignal** [flutter/flutter#126796]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

In some scenario, some routes (ex: `/my-route/:route-id`) requires to always have a parameter (ex: `/my-route/:route-id?my-param=my-value`)

I would like to enforce the generated code and developers to always specify this parameter:

```dart
MyRoute(routeId: 'routeId', myParam: 'myValue').location; // <- OK
MyRoute(routeId: 'routeId').location; // <- KO: `myParam` is required
```

by doing:

```dart
@TypedRoute<MyRoute>(path: '/my-route/:route-id')
class MyRoute extends GoRouteData {
  MyRoute({
    required this.routeId,
    required this.myParam,
  });

  final String routeId;
  final String myParam;
}
```

Right now, I can only use `assert`s: 

```dart
@TypedRoute<MyRoute>(path: '/my-route/:route-id')
class MyRoute extends GoRouteData {
  MyRoute({
    required this.routeId,
    this.myParam = '',
  }): assert(myParam.isNotEmpty);

  final String routeId;
  final String myParam;
}
```

but this doesn't give a check at compilation time, it only fails at running time.

### Proposal

It would be nice to support required query parameters:

```dart
@TypedRoute<MyRoute>(path: '/my-route/:route-id')
class MyRoute extends GoRouteData {
  MyRoute({
    required this.routeId,
    required this.myParam,
  });

  final String routeId;
  final String myParam;
}
```

**Comment by dancamdev** [comment]
@chunhtai is there any reason why this shouldn't be a thing?

I worked on integrating required extra parameters, technically this should be feasible as well and wouldn't break existing code.

**Comment by chunhtai** [comment]
what happen if user type the url bar directly without the required query parameter. Does it just crash the app?

**Comment by ValentinVignal** [comment]
> what happen if user type the url bar directly without the required query parameter. Does it just crash the app?

I guess it would. But it would also crash today if the wrong type is given to a parameter, ex: 


```dart
@TypedRoute<MyRoute>(path: '/my-route:route-id')
class MyRoute extends GoRouteData {
  MyRoute({
    required this.routeId,
    this.myParam',
  });

  final int routeId;
  final int myParam;
}
```

would crash today if the use types `/my-route/route-id?my-param=my-value` as `"route-id"` and `"my-value"` are not ints.

**Comment by chunhtai** [comment]
I see, yeah i guess that is inevitable if we move toward type safe routing. This is off-topic, but I think we should have a way to handle type mismatch.

**Comment by chunhtai** [comment]
That would be a catch all. I was imagining a route by route error handling
