### ISSUE TITLE
TextStyle foreground attribute is broken in 3.10

### ISSUE THREAD

**Issue by sgruhier** [flutter/flutter#126740]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Just create a TextField with a foreground attribute
```dart
        Text(
              'SAMPLE TEXT',
              style: Theme.of(context).textTheme.bodyLarge!.copyWith(
                    fontSize: 40,
                    fontWeight: FontWeight.bold,
                    foreground: Paint()
                      ..style = PaintingStyle.stroke
                      ..strokeWidth = 3
                      ..color = Colors.red,
                  ),
            )
```

### Expected results

<img width="342" alt="Screenshot 2023-05-13 at 12 16 35" src="https://github.com/flutter/flutter/assets/3385/b72b378d-568d-4eab-a176-4e2ee57e2590">

### Actual results

<img width="345" alt="Screenshot 2023-05-13 at 11 44 47" src="https://github.com/flutter/flutter/assets/3385/d8932b78-3846-4412-a2ee-5d647b045d1e">

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Text(
          'SAMPLE TEXT',
          style: Theme.of(context).textTheme.bodyLarge!.copyWith(
                fontSize: 40,
                fontWeight: FontWeight.bold,
                foreground: Paint()
                  ..style = PaintingStyle.stroke
                  ..strokeWidth = 3
                  ..color = Colors.red,
              ),
        ),
      ),
    );
  }
}

</details>


### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>


### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by Sarraj-Sahar** [comment]
I believe just changing the strokeWidth to 1 (or making the fontSize bigger if you want to keep the storkeWidth to 3) would achieve the expected result. Your Text appears to be "filled" instead of bordered because the strokeWidth was too "wide" in proportion to the fontSize.

```dart
Text(
 'SAMPLE TEXT',
          style: Theme.of(context).textTheme.bodyLarge!.copyWith(
                fontSize: 40,
                fontWeight: FontWeight.bold,
                foreground: Paint()
                  ..style = PaintingStyle.stroke
                  ..strokeWidth = 1
                  ..color = Colors.red,
              ),
        )
```
<img width="274" alt="image" src="https://github.com/flutter/flutter/assets/82158584/15817b33-c644-40de-ad33-5d8b9cd82aaa">

**Comment by sgruhier** [comment]
I tested smaller stokeWidth with same result.
Here is what I have with your example on flutter 3.10.0
<img width="333" alt="image" src="https://github.com/flutter/flutter/assets/3385/1b8172db-7d97-4e8e-9527-b77b153a90ae">

and what I have with flutter 3.7.11
<img width="345" alt="image" src="https://github.com/flutter/flutter/assets/3385/9673e225-6774-4b1e-a391-93a40bfc1c1d">


Both doesn't look like yours. How did you get that rendering?

**Comment by Sarraj-Sahar** [comment]
I am using the master channel: Flutter 3.9.0-17.0.pre.836. I am very intrigued on the result you're getting with flutter 3.7.11, yours seems to be showing even the "internal" crossing line in each letter. I wonder if that's the intended behavior or a bug ?

**Comment by Sarraj-Sahar** [comment]
@darshankawar can a team member please check this out and confirm which rendering is the intended one?

**Comment by sgruhier** [comment]
I confirm it's an impeller issue. with no-enable-impeller it works fine on 3.10.0
