### ISSUE TITLE
Issue from website page Developing Packages 

### ISSUE THREAD

**Issue by ghqureshi** [flutter/flutter#12671]
From URL: https://flutter.io/developing-packages.md

I am new to development . In most of the tutorials examples include instructions for IntelliJ. It would be great if this page contains some info how to do a particular task in IntelliJ or give pointer to some external links.

**Comment by sethladd** [comment]
cc @mit-mit

**Comment by mit-mit** [comment]
Do you mean for core steps like how to Run an app? If so, did you see the documentation on https://flutter.io/intellij-ide/ ?

**Comment by Hixie** [comment]
It's not really clear what this is requesting, and no response was received to the last message. Closing. Please open a new bug with more details if you still desire a change to be made. Thanks!
