### ISSUE TITLE
[tool_crash] FileSystemException: readSync failed, OS Error: Input/output error, errno = 5

### ISSUE THREAD

**Issue by hoanvuso** [flutter/flutter#126764]
## Command
```
flutter pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: readSync failed, OS Error: Input/output error, errno = 5
```
#0      _RandomAccessFile.readSync (dart:io/file_impl.dart:760:7)
#1      _File.readAsBytesSync (dart:io/file_impl.dart:552:23)
#2      _File.readAsStringSync (dart:io/file_impl.dart:584:18)
#3      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:96:16)
#4      _pluginFromPackage (package:flutter_tools/src/flutter_plugins.dart:44:36)
#5      findPlugins (package:flutter_tools/src/flutter_plugins.dart:83:28)
<asynchronous suspension>
#6      PackagesGetCommand.usageValues (package:flutter_tools/src/commands/packages.dart:101:36)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1271:15)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.5.3, on macOS 13.3.1 22E261 darwin-x64, locale
    en-US)
    • Flutter version 2.5.3 at /Volumes/DATA/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (1 year, 7 months ago), 2021-10-15 10:46:35
      -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✗] Android toolchain - develop for Android devices
    ✗ ANDROID_HOME = /Users/macbook/Library/Android/sdk
      but Android SDK not found at this location.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 14.3, Build version 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 113.0.5672.92

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.2.1+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 18116933e77adc82f80866c928266a5b4f1ed645
### Plugins
android_path_provider-0.3.0
better_player-0.0.79
cached_video_player-1.0.3
connectivity_plus-2.2.0
connectivity_plus_linux-1.2.0
connectivity_plus_macos-1.2.1
connectivity_plus_web-1.2.0
connectivity_plus_windows-1.2.0
contacts_service-0.6.3
device_info-2.0.3
device_info_plus-4.0.0
device_info_plus_linux-2.1.1
device_info_plus_macos-2.2.3
device_info_plus_web-2.1.0
device_info_plus_windows-2.1.1
downloads_path_provider_28-0.1.2
emoji_picker_flutter-1.1.2
esys_flutter_share-1.0.2
file_picker-3.0.4
firebase_core-1.10.6
firebase_core_web-1.5.3
firebase_messaging-10.0.9
firebase_messaging_web-2.2.5
flutter_app_badger-1.4.0
flutter_downloader-1.7.3
flutter_inappwebview-5.3.2
flutter_local_notifications-4.0.1+2
flutter_plugin_android_lifecycle-2.0.5
flutter_webview_plugin-0.4.0
fluttertoast-8.0.8
geocoder-0.2.1
geolocator-8.0.1
geolocator_android-3.0.1
geolocator_apple-2.0.0+2
geolocator_web-2.1.1
google_maps_flutter-2.1.5
image_gallery_saver-1.7.1
jitsi_meet-4.0.0
jitsi_meet_web_plugin-2.0.0
local_auth-1.1.11
location-4.4.0
location_web-3.1.1
open_file-3.2.1
package_info_plus-1.4.2
package_info_plus_linux-1.0.5
package_info_plus_macos-1.3.0
package_info_plus_web-1.0.5
package_info_plus_windows-1.0.5
path_provider-2.0.8
path_provider_android-2.0.9
path_provider_ios-2.0.7
path_provider_linux-2.1.4
path_provider_macos-2.0.4
path_provider_windows-2.0.4
permission_handler-8.3.0
photo_manager-1.3.10
qr_code_scanner-0.6.1
share-2.0.4
shared_preferences-2.0.11
shared_preferences_android-2.0.9
shared_preferences_ios-2.0.8
shared_preferences_linux-2.0.3
shared_preferences_macos-2.0.2
shared_preferences_web-2.0.2
shared_preferences_windows-2.0.3
sqflite-2.0.1
syncfusion_flutter_pdfviewer-19.4.56-beta
syncfusion_flutter_pdfviewer_macos-19.4.56-beta
syncfusion_flutter_pdfviewer_web-19.4.56-beta
url_launcher-6.1.2
url_launcher_android-6.0.13
url_launcher_ios-6.0.13
url_launcher_linux-2.0.2
url_launcher_macos-2.0.2
url_launcher_web-2.0.5
url_launcher_windows-2.0.2
video_player-2.2.17
video_player_web-2.0.4
wakelock-0.5.6
wakelock_macos-0.4.0
wakelock_web-0.4.0
webview_flutter-2.8.0
webview_flutter_android-2.8.2
webview_flutter_wkwebview-2.7.1

**Comment by darshankawar** [comment]
@hoanvuso 
You are on an old version of Flutter. Latest version is 3.10.0. I recommend to upgrade to latest and try again to see if you still get same error or not. If so, write in comments and I'll reopen it.
Closing for now, as the version you are on is obsolete.
