### ISSUE TITLE
Flutter Web 3.10.0 (canvaskit) loadingProgress is always null on loadingBuilder for Image.network

### ISSUE THREAD

**Issue by Sulav-Beehave** [flutter/flutter#126797]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Switch to channel **stable**
2. Upgrade to **3.10**
3. Set renderer to **canvaskit** while initializing the application
4. Use Image.network() with loading builder to show loading indicator 

### Expected results

The loadingProgress should have been instance of ImageChunkEvent while the image is being loaded. The loadingProgress is normally used to show loading indicator for image while it is loading.

### Actual results

The loadingProgress is always null which makes it impossible to show loading indicator while image is being loaded. The issue is only in canvaskit renderer on web. It works fine on html renderer as well as every other platforms (mobile, desktop)

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            SizedBox(
              height: 400,
              width: 400,
              child: _buildNetworkImage(),
            )
          ],
        ),
      ),
    );
  }

  Widget _buildNetworkImage() {
    return Image.network(
      'https://storage.googleapis.com/cms-storage-bucket/ed2e069ee37807f5975a.jpg',
      loadingBuilder: (context, child, loadingProgress) {
        if (loadingProgress == null) {
          return child;
        }

        return const Center(
          child: CircularProgressIndicator(strokeWidth: 1.5),
        );
      },
      fit: BoxFit.fitWidth,
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
I can see when it runs on `canvaskit` renderer`, it always null. On HTML renderer, the result is better but it is still not correct.

<details>
<summary>HTML Logs</summary>

```console
loadingProgress:ImageChunkEvent#f230e(cumulativeBytesLoaded: 0, expectedTotalBytes: 100)
loadingProgress:null
```
</details>

Also, this is a known issue being tracked at https://github.com/flutter/flutter/issues/66342. 

Closing this issue as a duplicate, so please follow up on it for further updates. Thank you!

**Comment by Sulav-Beehave** [comment]
The issue that is being tracked at https://github.com/flutter/flutter/issues/66342 seems to be a bit different than this issue. The issue of ImageChunkEvent not being sent at all on canvaskit renderer is bit different. On the logs that you posted for html it is expected behaviour according to https://github.com/flutter/flutter/issues/66342#issuecomment-702425740 comment. The loadingProgress was working upto version 3.3 for canvaskit but the issue that has been linked has been opened on year 2020. Could you reopen the issue as the bugs are different?

**Comment by huycozy** [comment]
I checked this again on Flutter 3.3.10 (canvaskit) and see below logs:
```
loadingProgress:null
loadingProgress:ImageChunkEvent#449e6(cumulativeBytesLoaded: 128892, expectedTotalBytes: 128892)
loadingProgress:null
```

It's similar to the logs that are showing at https://github.com/flutter/flutter/issues/66342#issue-706307068. I will update the label for that issue, please follow it for further updates. You can also leave there your comment and react an upvote to the original comment will help to raise the issue.
