### ISSUE TITLE
[CP] Fix for CupertinoPicker and ListWheelViewport crash

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#126782]
### issue_link

https://github.com/flutter/flutter/issues/126491

### Commit Hash

ae82f3cbce6a9fc1c9e65e6200275373e11de419

### Target

stable

### pr_link

https://github.com/flutter/flutter/pull/126804

### Impacted Users

Flutter devs who use CupertinoPicker or ListWheelViewport with certain configurations

### Impact Description

It impacts only development builds, will not cause any problems in release builds.

### Workaround

N/A

### Risk

low

### Test Coverage

yes

**Comment by CaseyHillers** [comment]
@piinks can you review this CP request? If it looks good to you, add the "cp: approved" label.

**Comment by CaseyHillers** [comment]
@nt4f04uNd for the PR link section, can you open a new PR that CP's this to the current stable branch? The current stable is on flutter-3.10-candidate.1

**Comment by nt4f04uNd** [comment]
> @nt4f04uNd for the PR link section, can you open a new PR that CP's this to the current stable branch? The current stable is on flutter-3.10-candidate.1

Ahh, got you, done. It wasn't clear from the template, to be honest. Where can one look up which release branch they should open their PR against beforehand?

**Comment by Piinks** [comment]
CP LGTM

**Comment by XilaiZhang** [comment]
landed on stable

**Comment by nt4f04uNd** [comment]
@XilaiZhang is there something left to do here?

**Comment by XilaiZhang** [comment]
we are currently working on packaging and publishing the stable. once it is published then we can close this issue.
