### ISSUE TITLE
Checking Flutter Doctor appearing Crash 

### ISSUE THREAD

**Issue by abdullah-naeem-laangah** [flutter/flutter#126755]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

https://github.com/flutter/flutter/issues

![image](https://github.com/flutter/flutter/assets/133358893/5eb0a60d-39f7-4aab-a10a-13b7e6f15311)

### Actual results

Checking Flutter Doctor appearing Crash 

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<C:\Users\BURHAN SAMI>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.0, on Microsoft Windows [Version 10.0.19045.2965], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[☠] Android toolchain - develop for Android devices (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Android toolchain - develop for Android devices exceeded maximum allowed duration of 0:04:30.000000
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.2)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 2 categories.>

```

</details>

**Comment by andoriyaprashant** [comment]
This is a common flutter doctor issue @abdullah-naeem-laangah 

The Android toolchain is missing the "cmdline-tools" component. To fix this issue, you need to run the following command in your terminal:

![Screenshot 2023-05-14 112554](https://github.com/flutter/flutter/assets/121665385/910012ac-4034-423b-a60e-1d5598696238)


Make sure to replace "path/to/sdkmanager" with the path to your Android SDK installation directory.

Additionally, the Android license status is unknown. You can accept the SDK licenses by running the following command:

![Screenshot 2023-05-14 112559](https://github.com/flutter/flutter/assets/121665385/ff7eb614-d708-48fd-97d2-1b704a5e48f7)

And  Vs code is not installed
Make sure to install the "Desktop development with C++" workload, including all of its default components. 

And after this, you can run flutter doctor again to ensure that everything is working properly.

**Comment by abdullah-naeem-laangah** [comment]
Still not working

**Comment by abdullah-naeem-laangah** [comment]
![image](https://github.com/flutter/flutter/assets/133358893/05e9b3f7-db1e-4a8c-912f-8ec2592633fc)
and this is too 
![image](https://github.com/flutter/flutter/assets/133358893/5808a07d-d080-4001-94b4-435abea4f035)

**Comment by abdullah-naeem-laangah** [comment]
Thanks Bro

**Comment by andoriyaprashant** [comment]
@abdullah-naeem-laangah now you can close this issue

**Comment by darshankawar** [comment]
@abdullah-naeem-laangah 
https://github.com/flutter/flutter/issues/126755#issuecomment-1546815731 seems to help resolve the issue you reported, so I'll go ahead and close. If you disagree, write in comments and I'll reopen it.
