### ISSUE TITLE
bottomNavigationBar with a black line in bottom 

### ISSUE THREAD

**Issue by sundogya** [flutter/flutter#126765]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1.Develop on Mac mini m1  macos 13.3.1 (a) 
2.Android Studio Flamingo | 2022.2.1 Patch 1
3.Devices:Redmi K40 whith pixelexpirence 13
or Other Android devices

### Expected results

bottomNavigationBar without a balck line on the bottom

### Actual results

bottomNavigationBar whith a balck line on the bottom

### Code sample

```
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch:Colors.pink,
      ),
      home: Scaffold(
          appBar: AppBar(
            title: const Center(child: Text('Demo')),
          ),
          body: const Text('Haha'),
          bottomNavigationBar: Container(
              decoration: const BoxDecoration(color: Colors.white),
              padding: const EdgeInsets.symmetric(vertical: 12),
              child: const Padding(
                padding: EdgeInsets.symmetric(horizontal: 26, vertical: 8),
                child: GNav(
                    padding: EdgeInsets.symmetric(horizontal: 20, vertical: 8),
                    gap: 8,
                    tabBackgroundColor: Color(0x33Fc548E),
                    activeColor: Color(0xFFFC548E),
                    color: Colors.black54,
                    tabs: [
                      GButton(
                        icon: Icons.home,
                        text: 'Home',
                      ),
                      GButton(
                        icon: Icons.category,
                        text: 'Cate',
                      ),
                      GButton(
                        icon: Icons.add_circle_outline,
                        text: 'Publish',
                      ),
                      GButton(
                        icon: Icons.account_circle,
                        text: 'Mine',
                      )
                    ]),
              )))
    );
  }
}

```

### Screenshots or Video

![WeChat62829fda39431b270c5b1fcaedbca851](https://github.com/flutter/flutter/assets/13327808/0309ef30-1424-431f-81a6-852515e33101)

![WechatIMG1](https://github.com/flutter/flutter/assets/13327808/49e37d57-599d-4375-a933-d74d662f0147)

**Comment by huycozy** [comment]
Hi @sundogya 
As I can see from your sample code, you are using 3rd package or undefined widgets (GNav, GButton).

For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins/packages or complex production code. Please provide such a sample.

**Comment by maRci002** [comment]
That is Android's navigator's color, you can change for instance by changing:

```dart
AppBar(
  title: const Center(child: Text('Demo')),
),
```

To:

```dart
import 'package:flutter/services.dart';

AppBar(
  title: const Center(child: Text('Demo')),
  systemOverlayStyle: SystemUiOverlayStyle.light.copyWith(systemNavigationBarColor: Colors.blue),
),
```

**Comment by sundogya** [comment]
> 

Thanks ,got it!
systemOverlayStyle works.

**Comment by sundogya** [comment]
> That is Android's navigator's color, you can change for instance by changing:
> 
> ```dart
> AppBar(
>   title: const Center(child: Text('Demo')),
> ),
> ```
> 
> To:
> 
> ```dart
> import 'package:flutter/services.dart';
> 
> AppBar(
>   title: const Center(child: Text('Demo')),
>   systemOverlayStyle: SystemUiOverlayStyle.light.copyWith(systemNavigationBarColor: Colors.blue),
> ),
> ```

Thanks ,i got it !
And systemOverlayStyle works well.

**Comment by huycozy** [comment]
It seems the issue has been solved with the solution above. Closing from here.
