### ISSUE TITLE
Document how to add l10n support for new languages

### ISSUE THREAD

**Issue by ghqureshi** [flutter/flutter#12672]
From URL: https://flutter.io/tutorials/international/index.md

Its really difficult to follow the example. In my view, there should be a file/section which contains all the pieces together to copy and paste and see the results.

**Comment by sethladd** [comment]
Thanks for the feedback. Can you help us by letting us know which parts were difficult to follow?

What would you recommend as the simplest "copy and paste" example?

**Comment by ghqureshi** [comment]
I was not able to follow the instructions as it give errors cuz the
reference class was configured in next step..:)

1. I think order should be reverse or such that whenever a user copy/paste
the snip code .. there shouldn't be any error i.e. complete code per snip
2. The example should mention a simple scenario e.g. changing the title of
the app based on device locale. Sometimes, its easier to understand by
reverse engineering. What I mean its  helps if you can see/test a working
code and trace it back to figure out how the dots are connected. Instead of
trying to do it right at first place and later on find out its not working;
thus giving it up. (due to lack of understanding.. I am not complaining
about the document)

Indeed its a good document but need some fine tuning so that people like
can take benefit too.

Thanks
Ghaz

**Comment by brianegan** [comment]
I got this working as well, but did feel it was a bit of a "tough handoff" to the intl package docs for further reading. I had to put the whole process together myself in my head and write a makefile to make it easily repeatable as I changed / added strings.

Would be cool to even have a step-by-step overview of the process:

  1. Define your strings using the intl package
  2. Notice: the `initializeMessages` referenced will not exist! Why not? We need to generate it.
  3. How to generate the messages.
  4. Ok, now that we have our messages, we need to give them to Flutter. How does that work? Let's make our LocalizationsDelegate!
  5. Delegates in hand, now I want to sue em! Add the Delegate to the App widget.

Thanks for listening and all the hard work on the docs!

**Comment by HansMuller** [comment]
We've updated https://flutter.io/tutorials/internationalization/. There's complete source code for a rough and ready minimal i18n app as well as one based on the intl package. There's an appendix that reviews how to use the intl tools.

I don't think we've quite reached the cookbook style that @brianegan suggested, but hopefully it's an improvement.

**Comment by reni99** [comment]
Does the example from the tutorial work or is there an open issue I did not find? As I change the language from en to es on iPhone Simulator, the language does not change.

**Comment by sqoopdata** [comment]
@reni99 I ran into a similar problem. But when I deploy on a real device, it works.

**Comment by reni99** [comment]
@sqoopdata ahh I see. Maybe I just tested it on real device. Need to check it for simulator.

**Comment by zoechi** [comment]
It doesn't seem to explain how to add a language that is not in the list https://github.com/flutter/flutter/blob/286cdf43f018583e84ded36e0eb26211db6bdd3f/packages/flutter_localizations/lib/src/material_localizations.dart#L42-L65

**Comment by HansMuller** [comment]
@zoechi That's a good point and it's an issue that's come up quite a few times. I've put documenting how to add framework support for a language on this summer's todo list.

**Comment by mmcc007** [comment]
@reni99 @sqoopdata FYI: After getting internationalization working, I ran into a problem with integration testing. Flutter driver does not work with internationalization (at least on emulators). Not good for regression testing, etc... #27785

**Comment by mmcc007** [comment]
FYI: Looks like the problem I ran into with integration testing has been resolved. Using the flutter driver callback handler it's possible to get the localizations (text values) for the current locale running in the app and use them in the test.
https://github.com/mmcc007/screenshots/commit/0c3df71931083b6c81c9f7c9f3eee6515ec4351f

**Comment by HansMuller** [comment]
How to add support for a new language in an app is (finally!) documented here: https://flutter.dev/docs/development/accessibility-and-localization/internationalization#adding-support-for-a-new-language.
