### ISSUE TITLE
[go_router] rebuilds the entire stack on every push and pop

### ISSUE THREAD

**Issue by moneer-octedia** [flutter/flutter#126770]
Hi I understand there are other issues filled about go_router maintaining state in this issue my problem is that the entire stack gets rebuilt. I'm working on a shopping app and made the mistake of going with go_router since it's the official package and when you push catalog screens that contain products on top of one another and then the product details screen you can have quit a bit of screens in the stack any push or pop rebuilds everything which causing me a big performance issue

here is an example app to demo
https://github.com/moneer-octedia/go_router_rebuild_strategy

if you add break points in page_builder call back you will get it on any push and pop

I hope I'm missing something because otherwise I have to rewrite a large part of my app.

thanks

**Comment by huycozy** [comment]
Thanks for the report! This is a known issue being tracked at https://github.com/flutter/flutter/issues/123570.

Closing this issue as a duplicate, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
