### ISSUE TITLE
engine tree red on hung "collect builds" tasks

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#126711]
Almost every task has failed at https://flutter-dashboard.appspot.com/#/build?taskFilter&authorFilter&messageFilter&hashFilter&showMac=true&showWindows=true&showiOS=true&showLinux=true&showAndroid=true&showStaging=false&repo=engine&branch=master

Example failure: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20linux_arm_host_engine/3706/overview

Error test: `Infra Failure: Step('collect builds.collect.wait') (canceled) (retcode: -15)`

**Comment by keyonghan** [comment]
This is a LUCI foundation issue, and has recovered.
