### ISSUE TITLE
Long press event reporting error

### ISSUE THREAD

**Issue by 309791679** [flutter/flutter#126788]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

//Long press will report an error
W/System.err(20077): java.lang.NoSuchMethodException: android.view.ViewRootImpl.getWindowFlags [int]
W/System.err(20077): 	at java.lang.Class.getMethod(Class.java:2103)
W/System.err(20077): 	at java.lang.Class.getMethod(Class.java:1724)
W/System.err(20077): 	at com.miui.contentcatcher.Interceptor.D(Unknown Source:14)
W/System.err(20077): 	at com.miui.contentcatcher.Interceptor.K(Unknown Source:119)
W/System.err(20077): 	at com.miui.contentcatcher.Interceptor.J(Unknown Source:91)
W/System.err(20077): 	at com.miui.contentcatcher.Interceptor.h(Unknown Source:6)
W/System.err(20077): 	at z0.a$a.handleMessage(Unknown Source:59)
W/System.err(20077): 	at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err(20077): 	at android.os.Looper.loopOnce(Looper.java:210)
W/System.err(20077): 	at android.os.Looper.loop(Looper.java:299)
W/System.err(20077): 	at android.app.ActivityThread.main(ActivityThread.java:8261)
W/System.err(20077): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(20077): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
W/System.err(20077): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

### Expected results

Not reporting an error anymore

### Actual results

Not reporting an error anymore

### Code sample

<details><summary>Code sample</summary>

```
Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    )
```
</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console

Flutter 3.10.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 84a1e904f4 (5 days ago) • 2023-05-09 07:41:44 -0700
Engine • revision d44b5a94c9
Tools • Dart 3.0.0 • DevTools 2.23.1

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.10.0, on Microsoft Windows [版本 10.0.19043.1889], locale zh-CN)
    • Flutter version 3.10.0 on channel stable at \flutter_windows_3.10.0-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (5 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\z\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: \android studio\android-studio2021.2.1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32901.215
    • Windows 10 SDK version 10.0.19041.0
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2021.2)
    • Android Studio at \android studio\android-studio2021.2.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Connected device (3 available)
    • M2012K11AC (mobile) • 22b38ce • android-arm64  • Android 13 (API 33)
    • Windows (desktop)   • windows • windows-x64    • Microsoft Windows [版本 10.0.19043.1889]
    • Edge (web)          • edge    • web-javascript • Microsoft Edge 113.0.1774.42

[√] Network resources
    • All expected network resources are available.


```

</details>

**Comment by huycozy** [comment]
Hi @309791679  
Where did you perform the long press (on a widget or the app screen)? And have you modified any native code on `android`? 

Please also provide the complete output of `flutter run -v` so that we may verify the issue. Thanks!
