### ISSUE TITLE
Update Datatable Component in Flutter Material 2 to Material 3

### ISSUE THREAD

**Issue by vinodh013** [flutter/flutter#126720]
Datatable needs to be updated from material 2 to material 3 as it is one of the crucial components in business applications 

There is no component in figma for datatables. so please check on this issue

**Comment by huycozy** [comment]
As far as I can see, there is only M2 specs for Datatable here: https://m2.material.io/components/data-tables. I'm not sure if you've seen it before. So please share it here if any. Thanks!

**Comment by TahaTesser** [comment]
cc: @guidezpl

**Comment by vinodh013** [comment]
@huycozy  Yes, There is only M2 specs for Datatable . there is no M3 component for datable.

**Comment by guidezpl** [comment]
It's the same component, I encourage you to learn more about how Material 3 is achieved through the `useMaterial3` flag API documentation.
