### ISSUE TITLE
web_plugin_registrant.dart

### ISSUE THREAD

**Issue by HARIS4820** [flutter/flutter#126766]
Could not load source 'org-dartlang-app:/web_plugin_registrant.dart': -32602 No source for [ScriptRef id: 3, uri: org-dartlang-app:/web_plugin_registrant.dart]  with serverPath: web_plugin_registrant.dart.

**Comment by darshankawar** [comment]
@HARIS4820 
Please don't only paste the error, but try to use new issue template, fill out requested details so that we'll have enough info to work with. 
Provide `flutter doctor -v`, a minimal code sample, steps to replicate and complete error log in properly formatted text.
