### ISSUE TITLE
NestedScrollView: missing ScrollUpdateNotifications

### ISSUE THREAD

**Issue by robertoscaramuzzi** [flutter/flutter#12676]
Run the following code then hold one of the non-red tiles and slowly scroll up. Notice how in the console no ScrollUpdateNotifications are printed until the blue tile disappears behind the red tile (the header).

This happens for me on a physical Android device, in case it matters.

```dart
import 'package:flutter/material.dart';

class HeaderBug extends StatelessWidget {
  @override
  Widget build(BuildContext context) => new Directionality(
        textDirection: TextDirection.ltr,
        child: new NestedScrollView(
          headerSliverBuilder: (_, __) => [
                new SliverPersistentHeader(
                  pinned: true,
                  delegate: new _Delegate(),
                )
              ],
          body: new NotificationListener<Notification>(
            onNotification: _handleNotification,
            child: new ListView(
              shrinkWrap: true,
              children: [
                new Tile(Colors.blue),
                new Tile(Colors.green),
                new Tile(Colors.orange),
                new Tile(Colors.grey),
                new Tile(Colors.white),
              ],
            ),
          ),
        ),
      );
}

bool _handleNotification(Notification n) {
  if (n is ScrollUpdateNotification) print("$n");
  return true;
}

class Tile extends StatelessWidget {
  final Color _color;

  Tile(this._color);

  @override
  Widget build(BuildContext context) =>
      new Container(height: 200.0, width: 300.0, color: _color);
}

class _Delegate extends SliverPersistentHeaderDelegate {
  @override
  Widget build(BuildContext context, _, __) => new Tile(Colors.red);

  @override
  bool shouldRebuild(SliverPersistentHeaderDelegate oldDelegate) => true;

  @override
  double get maxExtent => 200.0;

  @override
  double get minExtent => 200.0;
}

void main() {
  runApp(new HeaderBug());
}
```

**Comment by Hixie** [comment]
Can you elaborate on why this is a blocker?

**Comment by robertoscaramuzzi** [comment]
Because I'm listening to ScrollUpdateNotifications to sync two ListViews and this breaks the syncing (the two ListViews are off by the height of the header). I know you suggested offline another way to sync the lists, but that's a lot more work than what I'm doing now.

**Comment by Hixie** [comment]
Roger, thanks.

**Comment by Hixie** [comment]
Your example above uses NestedScrollView; is that important to reproducing the bug?

**Comment by robertoscaramuzzi** [comment]
Not sure. That's the only way I've tried it.

**Comment by robertoscaramuzzi** [comment]
Removed customer:blocker since the alternative way of accomplishing linking ListViews worked out.

**Comment by Hixie** [comment]
NestedScrollView actually has multiple scroll views, each firing their own scroll notifications and so forth. I wonder if maybe what's going on is you're getting notifications until the outer one is done scrolling, but not getting the notifications from the inner one. Not sure why that would happen, maybe we're swallowing them somewhere?

**Comment by Hixie** [comment]
I hadn't looked at the code above closely before. The problem is simple. The notification listener is wrapping the list view, not the nested scroll view, so you are only getting the notifications from the inner list view.

If you move the listener to above the nested scroll view, it seems to work as expected.
