### ISSUE TITLE
Suggestion to improve cross-platformability performance 

### ISSUE THREAD

**Issue by SriramBharadwaj1** [flutter/flutter#126729]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Flutter apps have a lot of code on them. This makes the cross platform ability of flutter apps less desirable in critical applications.

something analogous to jvm can be built with flutter to have the “write once run anywhere “ ability in flutter

### Proposal

I propose the building of a cross platform rendering software which will extract the platform specific code as an exportable file for each platform which gives a performance equivalent or better than that of shipping the whole app.

So, developer will code using dart framework and release versions for each major platform. The users can then install their native equivalent app from their respective play store, App Store or Microsoft store etc etc.

[proposed label] a:adaptivity

**Comment by stuartmorgan** [comment]
> So, developer will code using dart framework and release versions for each major platform. The users can then install their native equivalent app from their respective play store, App Store or Microsoft store etc etc.

This is already how Flutter works, so it's not at all clear what you are proposing.

Closing as unactionable; if you want to propose specific technical changes in Flutter's implementation please file a new proposal with significantly more technical detail (ideally including a design document) explaining what exactly the proposal is and how it differs from Flutter currently.

**Comment by SriramBharadwaj1** [comment]
where do I learn how flutter works sir.
I wish to learn flutter and join the core team
