### ISSUE TITLE
ColorScheme incorrect copyWith for optional colors

### ISSUE THREAD

**Issue by AlexeyKatsuro** [flutter/flutter#126744]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create `ColorScheme` with the assigned `primary` color  as `Colors.red`
2. Create a copy of scheme by `copyWith(primary: Colors.blue)` and assign `primary` as `Colors.bule`

### Expected results

The ColorScheme copy has `primaryContainer` as a Blue

### Actual results

The ColorScheme copy has `primaryContainer` still Red

### Code sample

<details><summary>Code sample</summary>

```dart
void main() {
  var colorSchema = const ColorScheme.light(primary: Colors.red);
  print(colorSchema.primary == colorSchema.primaryContainer); // true
  print(colorSchema.primaryContainer == Colors.red); // true

  colorSchema = colorSchema.copyWith(primary: Colors.blue);
  print(colorSchema.primary == colorSchema.primaryContainer); // Actual - false , Expected - true
  print(colorSchema.primaryContainer == Colors.blue); // Actual - false , Expected - true
}
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

[✓] Flutter (Channel stable, 3.10.0, on macOS 12.6 21G115 darwin-x64, locale en-GB)
    • Flutter version 3.10.0 on channel stable at /Users/alexey/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (4 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/alexey/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Connected device (3 available)
    • iPhone 14 (mobile) • BB1654F1-A425-4365-93D7-F3141210347F • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 113.0.5672.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by TahaTesser** [comment]
Hi @AlexeyKatsuro 
This seems working as expected.

When you use `const ColorScheme.light(primary: Colors.red)`, you're creating a new  `ColorScheme` using primary color, this is stored `colorSchema` and you get the following expected colors.
>   print(colorSchema.primary == colorSchema.primaryContainer); // true
>   print(colorSchema.primaryContainer == Colors.red); // true


`colorSchema = colorSchema.copyWith(primary: Colors.blue);` then simply copies all the previous colors and overrides only `primary`.

Doc  

>   /// Creates a copy of this color scheme with the given fields
>   /// replaced by the non-null parameter values.
>   ColorScheme copyWith({

  
`primary` is non-null in `colorSchema = colorSchema.copyWith(primary: Colors.blue)`.  and  `primaryContainer` is `null` here so it is not overridden.

This is making a copy of the original `colorScheme and overriding only the `primary`, `primaryContainer` is untouched in this duplication so the `primaryContainer` remains as it is.

Here you can see this visually.

![Screenshot 2023-05-15 at 12 22 34](https://github.com/flutter/flutter/assets/48603081/36d697b5-1d0b-4b31-99c8-d0f2f2f91597)

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(useMaterial3: true),
      home: const Example(),
    );
  }
}

class Example extends StatelessWidget {
  const Example({super.key});

  @override
  Widget build(BuildContext context) {
    const ColorScheme colorSchemaOriginal = ColorScheme.light(primary: Colors.red);

    final  ColorScheme colorSchemaUpdated = colorSchemaOriginal.copyWith(primary: Colors.blue);
    TextTheme textTheme = Theme.of(context).textTheme;

    return Scaffold(
      appBar: AppBar(
        title: const Text('Sample'),
      ),
      // Create 2 grid view in a column that shows colors from `colorSchemaOriginal` and `colorSchemaUpdated`.
      body: Column(
        children: <Widget>[
          Text('colorSchemaOriginal', style: textTheme.headlineMedium ,),
          Expanded(
            child: GridView.count(
              crossAxisCount: 10, // set the number of columns
              children: <Widget>[
                Container(
                  alignment: Alignment.center,
                  color: colorSchemaOriginal.primary,
                  child: const Text('Primary'),
                ),
                Container(
                  alignment: Alignment.center,
                  color: colorSchemaOriginal.primaryContainer,
                  child: const Text('Primary Variant'),
                ),
                Container(
                  alignment: Alignment.center,
                  color: colorSchemaOriginal.secondary,
                  child: const Text('Secondary'),
                ),
                Container(
                  alignment: Alignment.center,
                  color: colorSchemaOriginal.secondaryContainer,
                  child: const Text('Secondary Variant'),
                ),
                Container(
                  alignment: Alignment.center,
                  color: colorSchemaOriginal.surface,
                  child: const Text('Surface'),
                ),
                Container(
                  alignment: Alignment.center,
                  color: colorSchemaOriginal.background,
                  child: const Text('Background'),
                ),
                Container(
                  alignment: Alignment.center,
                  color: colorSchemaOriginal.error,
                  child: const Text('Error'),
                ),
                Container(
                  alignment: Alignment.center,
                  color: colorSchemaOriginal.onPrimary,
                  child: const Text('On Primary'),
                ),
                Container(
                  alignment: Alignment.center,
                  color: colorSchemaOriginal.onSecondary,
                  child: const Text('On Secondary'),
                ),
                Container(
                  alignment: Alignment.center,
                  color: colorSchemaOriginal.onSurface,
                  child: const Text('On Surface'),
                ),
                Container(
                  alignment: Alignment.center,
                  color: colorSchemaOriginal.onBackground,
                  child: const Text('On Background'),
                ),
                Container(
                  alignment: Alignment.center,
                  color: colorSchemaOriginal.onError,
                  child: const Text('On Error'),
                ),
              ],
            ),
          ),
                    Text('colorSchemaUpdated', style: textTheme.headlineMedium ,),

          Expanded(
            child: GridView.count(
              crossAxisCount: 10, // set the number of columns
              children: <Widget>[
                Container(
                  alignment: Alignment.center,
                  color: colorSchemaUpdated.primary,
                  child: const Text('Primary'),
                ),
                Container(
                  alignment: Alignment.center,
                  color: colorSchemaUpdated.primaryContainer,
                  child: const Text('Primary Variant'),
                ),
                Container(
                  alignment: Alignment.center,
                  color: colorSchemaUpdated.secondary,
                  child: const Text('Secondary'),
                ),
                Container(
                  alignment: Alignment.center,
                  color: colorSchemaOriginal.secondaryContainer,
                  child: const Text('Secondary Variant'),
                ),
                Container(
                  alignment: Alignment.center,
                  color: colorSchemaOriginal.surface,
                  child: const Text('Surface'),
                ),
                Container(
                  alignment: Alignment.center,
                  color: colorSchemaUpdated.background,
                  child: const Text('Background'),
                ),
                Container(
                  alignment: Alignment.center,
                  color: colorSchemaUpdated.error,
                  child: const Text('Error'),
                ),
                Container(
                  alignment: Alignment.center,
                  color: colorSchemaUpdated.onPrimary,
                  child: const Text('On Primary'),
                ),
                Container(
                  alignment: Alignment.center,
                  color: colorSchemaUpdated.onSecondary,
                  child: const Text('On Secondary'),
                ),
                Container(
                  alignment: Alignment.center,
                  color: colorSchemaUpdated.onSurface,
                  child: const Text('On Surface'),
                ),
                Container(
                  alignment: Alignment.center,
                  color: colorSchemaUpdated.onBackground,
                  child: const Text('On Background'),
                ),
                Container(
                  alignment: Alignment.center,
                  color: colorSchemaUpdated.onError,
                  child: const Text('On Error'),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

``` 
	
</details>

Hope this solves your doubt.

**Comment by AlexeyKatsuro** [comment]
Hello @TahaTesser!

Thank you for your detailed answer and with an example code.
But I cannot agree with the correctness of this approach, because it violates some logic. 

See. I use the default constructor and assign only the `primary` color, I don't care about other colors as the `primaryContainer`, and rely on the default behavior of the material design system. And by default, the `primaryContainer` links to `primary` color. 
And obviously, if I want to redefine the `primary` color in my color scheme, I expect that the default behavior of the material design of the system will be preserved, and all the colors that link to `primary` color by default will also change, but this does not happen, instead they retain the old values. 

Current behavior makes sense only if I assigned both the `primary` color and the `primaryContainer` from the very beginning, in this case I do not rely on the default behavior of the material design system, and accordingly if I copy only the `primary` color, then in this case the `primaryContainer` will remain unchanged since I abandoned the default linking between `primary` color, `primaryContainer`.

If the example with `primary` and `primaryContainer` did not convince you, look at the pair `inverseSurface` and `onInverseSurface`. 
By default:
- `inverseSurface` links `onSurface`
- `onInverseSurface` links `surface`

```dark
final lightSurfaced = ColorScheme.light();
final darkSurfaced = lightSurfaced.copyWith(
  surface: Colors.black,
  onSurface: Colors.white,
);
```
Intuitively it is clear that when we change `surface` and `onSurface` colors `inverseSurface` and `onInverseSurface` should changed too. But this is not the case.

Instead, we have to write like this to make it work the right way:

```dart
final lightSurfaced = ColorScheme.light();
final darkSurfaced = lightSurfaced.copyWith(
  surface: Colors.black,
  onSurface: Colors.white,
  inverseSurface: Colors.white,
  onInverseSurface: Colors.black,
);
```
Thus, in order to copy the scheme and save the default links between colors, you must literally look into the source code of `ColorScheme` and see all the dependencies between colors in order to correctly call the `copyWith` method with the correct arguments to save default links.

Good thing that `ColorScheme` implementation has backing fields. The only thing that should be replaced is using backing field `_primaryContainer` instead `this.primaryContainer` at `copyWith` method, and do this for all colors that have backing field.  It is strange to me that this was not done initially, because this is the only reason to create these backing fields

```diff
ColorScheme copyWith({
  Color? primary,
  Color? primaryContainer,
  ...
}) {
  return ColorScheme(
    primary : primary ?? this.primary,
-    primaryContainer : primaryContainer ?? this.primaryContainer,
+   primaryContainer : primaryContainer ?? _primaryContainer,
    ...
  );
}
```

@TahaTesser What are you think about it?

**Comment by TahaTesser** [comment]
Hi @AlexeyKatsuro 

> And obviously, if I want to redefine the primary color in my color scheme, I expect that the default behavior of the material design of the system will be preserved, and all the colors that link to primary color by default will also change, but this does not happen, instead they retain the old values.


`.copyWith` simply makes a copy, it won't change any null properties .  


It is a common method to copy all properties except non-null properties. In your code you're making a copy and overriding only one parameter, result is as expected.

You'll see other widgets with same method and behavior.  Please try these widgets with their `copyWith`

![Screenshot 2023-05-24 at 13 41 11](https://github.com/flutter/flutter/assets/48603081/7d335d85-5251-4685-a1b4-254f3fbaa78d)


The use case you're describing is not expected from `copyWith`. Please ask this question on Stackoverflow, you might get the right solution.
