### ISSUE TITLE
flutter daemon terminated consider re-starting android studio

### ISSUE THREAD

**Issue by codermurphy** [flutter/flutter#126727]
I have the same problem, how do you solve it

_Originally posted by @Sandeepsunil01 in https://github.com/flutter/flutter/issues/124906#issuecomment-1510356393_

**Comment by Sandeepsunil01** [comment]
Just downgraded platform-tools in Android SDK and it worked for me.

**Comment by codermurphy** [comment]
> Just downgraded platform-tools in Android SDK and it worked for me.
All right. I have already downloaded it. But the problem is not solved. anyway thanks

**Comment by Sandeepsunil01** [comment]
Is this happening, when you connect a real device?

**Comment by darshankawar** [comment]
@codermurphy 
Please provide complete details of the issue by providing error log, steps to replicate and environment details such as `flutter doctor -v` so that we can address it properly. Please don't use an issue comment to open an issue as the config / settings may not be same for each case.

**Comment by codermurphy** [comment]
> 

yes.

**Comment by darshankawar** [comment]
@codermurphy 
Could be related to network connection as `network resources` section shows it is unable to connect to the listed sites.

Also, `HRMPKC221D522229: offline` see if the device is properly connected or detected by the system or not. Maybe related to the cable you are using ?

**Comment by codermurphy** [comment]
> @codermurphy Could be related to network connection as `network resources` section shows it is unable to connect to the listed sites.
> 
> Also, `HRMPKC221D522229: offline` see if the device is properly connected or detected by the system or not. Maybe related to the cable you are using ?

The network is fine, I've changed the cable but it doesn't work. adb works fine when i connect android device using WIFI.

The bug only occurs when I connect the device with usb

My computer model is  MacBook Pro（13-inch, 2017, Two Thunderbolt 3 ports）;I guess it might be a problem with the usb docking station

**Comment by Sandeepsunil01** [comment]
What's the version of Platform-tools installed?

**Comment by codermurphy** [comment]
> What's the version of Platform-tools installed?

34.0.1

**Comment by darshankawar** [comment]
> I guess it might be a problem with the usb-c docking station

Is there a way to check on any other machine to see if you still get same behavior because I am unable to replicate this.

**Comment by codermurphy** [comment]
> > I guess it might be a problem with the usb-c docking station
> 
> Is there a way to check on any other machine to see if you still get same behavior because I am unable to replicate this.

I use a MacBook pro(13-inch, 2015) with a usb port and it works fine

**Comment by darshankawar** [comment]
@codermurphy 
Is this only occuring when you are running from Android Studio IDE ? Can you try from command line / terminal and see if it works or not ?

**Comment by codermurphy** [comment]
> @codermurphy Is this only occuring when you are running from Android Studio IDE ? Can you try from command line / terminal outside of IDE and see if it works or not ?

The current situation is that when I connect the Android device, the adb service does not start properly. So I can't start App from terminal.

The android emulator works fine,adb service can be found emulator.

When no device is connected:

adb start-server
* daemon not running; starting now at tcp:5037
* daemon started successfully

lsof -i tcp:5037
COMMAND   PID  USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
adb     18919 ogawa   10u  IPv4 0x621ea86f3bbedcaf      0t0  TCP localhost:5037 (LISTEN)

Then connect the usb to the device:

adb devices
* daemon not running; starting now at tcp:5037
ADB server didn't ACK
Full server startup log: /var/folders/sg/tzftct_50n52j_7721x5_4lw0000gn/T//adb.501.log
Server had pid: 18993
--- adb starting (pid 18993) ---
adb I 05-18 14:27:17 18993 223040 main.cpp:63] Android Debug Bridge version 1.0.41
adb I 05-18 14:27:17 18993 223040 main.cpp:63] Version 34.0.1-9979309
adb I 05-18 14:27:17 18993 223040 main.cpp:63] Installed as /Users/ogawa/Library/Android/sdk/platform-tools/adb
adb I 05-18 14:27:17 18993 223040 main.cpp:63] Running on Darwin 22.4.0 (x86_64)
adb I 05-18 14:27:17 18993 223040 main.cpp:63] 
adb I 05-18 14:27:17 18993 223044 usb_osx.cpp:325] reported max packet size for HRMPKC221D522229 is 512
adb I 05-18 14:27:17 18993 223040 auth.cpp:416] adb_auth_init...
adb I 05-18 14:27:17 18993 223040 auth.cpp:152] loaded new key from '/Users/ogawa/.android/adbkey' with fingerprint D0758EFCE8CA568C75566B64DE13B2A94F2B6CB54C83E4C627196CF36F8B98FA
adb I 05-18 14:27:17 18993 223053 transport.cpp:335] HRMPKC221D522229: read thread spawning
adb I 05-18 14:27:17 18993 223054 transport.cpp:307] HRMPKC221D522229: write thread spawning
adb I 05-18 14:27:17 18993 223040 transport.cpp:1727] fetching keys for transport HRMPKC221D522229
adb I 05-18 14:27:17 18993 223040 auth.cpp:468] Calling send_auth_response
adb I 05-18 14:27:17 18993 223040 adb.cpp:177] HRMPKC221D522229: offline

* failed to start daemon
adb: failed to check server version: cannot connect to daemon

The daemon service was killed.

when i use wireless device,adb service works fine

**Comment by darshankawar** [comment]
Please check [this](https://stackoverflow.com/questions/23415746/how-to-resolve-the-adb-server-didnt-ack-error#:~:text=Restart%20your%20phone.,force%20close%20in%20Activity%20Monitor.&text=If%20it%20says%20something%20like,successfully'%2C%20you%20are%20good.) and see if it helps.

**Comment by Sandeepsunil01** [comment]
I had the same problem I downgraded the platform-tools to 31.0.2 and now everything working fine.

**Comment by codermurphy** [comment]
> I had the same problem I downgraded the platform-tools to 31.0.2 and now everything working fine.

it doesn't work

**Comment by codermurphy** [comment]
> Please check [this](https://stackoverflow.com/questions/23415746/how-to-resolve-the-adb-server-didnt-ack-error#:~:text=Restart%20your%20phone.,force%20close%20in%20Activity%20Monitor.&text=If%20it%20says%20something%20like,successfully'%2C%20you%20are%20good.) and see if it helps.

it doesn't work

**Comment by darshankawar** [comment]
As your flutter doctor log shows:

```
Exception: Unable to run "adb", check your Android SDK installation and
      ANDROID_SDK_ROOT environment variable:
      /Users/ogawa/Library/Android/sdk/platform-tools/adb
```

Have you already followed properly the env variable pointing to the location / path and your SDK installation is correct ?

**Comment by codermurphy** [comment]
> As your flutter doctor log shows:
> 
> ```
> Exception: Unable to run "adb", check your Android SDK installation and
>       ANDROID_SDK_ROOT environment variable:
>       /Users/ogawa/Library/Android/sdk/platform-tools/adb
> ```
> 
> Have you already followed properly the env variable pointing to the location / path and your SDK installation is correct ?

SDK path is correct
echo $ANDROID_SDK_ROOT
/Users/ogawa/Library/Android/sdk

**Comment by darshankawar** [comment]
Thanks for the update. I am running out of ideas on the reported behavior, so keeping it open for team's attention and input.

**Comment by christopherfujino** [comment]
> adb start-server
> * daemon not running; starting now at tcp:5037
> ADB server didn't ACK
> Full server startup log: /var/folders/sg/tzftct_50n52j_7721x5_4lw0000gn/T//adb.501.log
> Server had pid: 21230
> --- adb starting (pid 21230) ---
> adb I 05-15 15:30:09 21230 273474 main.cpp:63] Android Debug Bridge version 1.0.41
> adb I 05-15 15:30:09 21230 273474 main.cpp:63] Version 34.0.1-9979309
> adb I 05-15 15:30:09 21230 273474 main.cpp:63] Installed as /Users/ogawa/Library/Android/sdk/platform-tools/adb
> adb I 05-15 15:30:09 21230 273474 main.cpp:63] Running on Darwin 22.4.0 (x86_64)
> adb I 05-15 15:30:09 21230 273474 main.cpp:63] 
> adb I 05-15 15:30:09 21230 273477 usb_osx.cpp:325] reported max packet size for HRMPKC221D522229 is 512
> adb I 05-15 15:30:09 21230 273474 auth.cpp:416] adb_auth_init...
> adb I 05-15 15:30:09 21230 273474 auth.cpp:152] loaded new key from '/Users/ogawa/.android/adbkey' with fingerprint D0758EFCE8CA568C75566B64DE13B2A94F2B6CB54C83E4C627196CF36F8B98FA
> adb I 05-15 15:30:09 21230 273481 transport.cpp:335] HRMPKC221D522229: read thread spawning
> adb I 05-15 15:30:09 21230 273482 transport.cpp:307] HRMPKC221D522229: write thread spawning
> adb I 05-15 15:30:09 21230 273474 transport.cpp:1727] fetching keys for transport HRMPKC221D522229
> adb I 05-15 15:30:09 21230 273474 auth.cpp:468] Calling send_auth_response
> adb I 05-15 15:30:09 21230 273474 adb.cpp:177] HRMPKC221D522229: offline
> 
> * failed to start daemon
> error: cannot connect to daemon

sounds like there is a regression in a new release of ADB?

**Comment by gmackall** [comment]
You might be hitting this: 
https://developer.android.com/tools/releases/platform-tools#3401_march_2023, 
particularly the linked issue: https://b.corp.google.com/issues/270205252?pli=1
so we believe that this is an adb problem and not a flutter problem. Can you try with a different version of adb?

**Comment by codermurphy** [comment]
> so we believe that this is an adb problem and not a flutter problem. Can you try with a different version of adb?

I tried many versions, but it still doesn't work

**Comment by codermurphy** [comment]
solved.

My mac csrutil status is disabled.then i make csrutil enable,it does work
