### ISSUE TITLE
BottomAppBar no longer notched after upgrading to 3.10

### ISSUE THREAD

**Issue by EMUNES** [flutter/flutter#126731]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

After upgrading to 3.10, I find the bottom app bar is no longer notched. Before upgrading, it works fine. And I can't find breaking changes directly related to this problem.

### Expected results

The bottom app bar should be notched in the center. And the center-docked floating action button should have no conflict or overlap with the notched bottom app bar.

### Actual results

The bottom app is flat and filled with color. The floating action button is placed upon the bottom app bar.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:posnote/views/home_page.dart';

class PersonalPage extends ConsumerWidget {
  // Current page is person.
  final currentPageOption = HomePageOptions.personal;
  const PersonalPage({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).canvasColor,
        centerTitle: true,
        elevation: 0,
        title: Text("Personal"),
      ),
      body: Container(
        child: Text("This is body."),
      ),
      bottomNavigationBar: BottomAppBar(
        color: Colors.orange,
        shape: const CircularNotchedRectangle(),
        notchMargin: 10,
        child: Row(
          crossAxisAlignment: CrossAxisAlignment.center,
          mainAxisAlignment: MainAxisAlignment.spaceAround,
          children: [
            Expanded(
              child: IconButton(
                icon: const Icon(Icons.analytics),
                onPressed: () => ref
                    .read(pageIndexProvider.notifier)
                    .onPageChange(HomePageOptions.analysis.index),
              ),
            ),
            const Expanded(
              child: SizedBox(),
            ),
            Expanded(
              child: IconButton(
                icon: const Icon(Icons.person),
                onPressed: () => ref
                    .read(pageIndexProvider.notifier)
                    .onPageChange(HomePageOptions.personal.index),
              ),
            ),
          ],
        ),
      ),
      // Go back to the card page.
      floatingActionButton: IconButton(
        icon: const Icon(Icons.home),
        iconSize: 30,
        onPressed: () => ref
            .read(pageIndexProvider.notifier)
            .onPageChange(HomePageOptions.card.index),
      ),
      floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![Screenshot from 2023-05-13 12-54-49](https://github.com/flutter/flutter/assets/53288091/e7a28c46-aea7-4fe2-b04e-d9b62ff15de9)

</details>

### Logs

<details><summary>Logs</summary>

```console
NO PROBLEM about logs, neither warning or error.
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.0, on Pop!_OS 22.04 LTS
    6.2.6-76060206-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Community Edition (version 2023.1)
[✓] VS Code (version 1.78.1)
[✓] Proxy Configuration
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @EMUNES, this was initially reported in https://github.com/flutter/flutter/issues/123283 and has since been fixed on the master channel. 

Per our triage policy, I'll be closing this since it has already been fixed on the master channel. If you run into this issue on the master channel or newer, kindly leave a comment below and I will reopen this issue. 

Thank you
