### ISSUE TITLE
[Material3] DropdownMenu Semantics for default icons

### ISSUE THREAD

**Issue by recjason** [flutter/flutter#126898]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Add a `DropdownMenu` with any number of items to a view.
2. Run against semantics test: https://docs.flutter.dev/accessibility-and-localization/accessibility?tab=voiceover#testing-accessibility-on-mobile

### Expected results

Should pass semantics test.

### Actual results

Fails on the arrows (up/down) on the right hand side.

Can address by providing the same icons in as properties and additionally setting the semantics labels:

```dart
trailingIcon: Icon(
  Icons.arrow_drop_down,
  semanticLabel:
      MaterialLocalizations.of(context).collapsedIconTapHint,
),
selectedTrailingIcon: Icon(
  Icons.arrow_drop_up,
  semanticLabel:
      MaterialLocalizations.of(context).expandedIconTapHint,
),
```

### Code sample

<details><summary>Code sample [dartpad]</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: Center(
          child: DropdownMenu(
            dropdownMenuEntries: [
              DropdownMenuEntry(
                value: 1,
                label: 'First',
              )
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Reproducible in https://dartpad.dev/ - stable channel
```

</details>

**Comment by huycozy** [comment]
Hi @recjason 
I tested this with below sample test but it passed. Verified on iOS device.

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

import 'package:reproduce_issues/dropdown_a11y_126898.dart' as a11y;
import 'package:reproduce_issues/dropdown_a11y_126898.dart';

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  group('test', () {
    testWidgets('a11y', (tester) async {
      a11y.main();
      final SemanticsHandle handle = tester.ensureSemantics();
      await tester.pumpWidget(MyApp());

      // Checks that tappable nodes have a minimum size of 44 by 44 pixels
      // for iOS.
      await expectLater(tester, meetsGuideline(iOSTapTargetGuideline));

      // Checks that touch targets with a tap or long press action are labeled.
      await expectLater(tester, meetsGuideline(labeledTapTargetGuideline));

      // Checks whether semantic nodes meet the minimum text contrast levels.
      // The recommended text contrast is 3:1 for larger text
      // (18 point and above regular).
      await expectLater(tester, meetsGuideline(textContrastGuideline));
      handle.dispose();
    });
  });
}

```
</details>

Can you provide a complete sample code along with its test?
