### ISSUE TITLE
setAllowsBackForwardNavigationGestures not working in flutter webview

### ISSUE THREAD

**Issue by ostup17** [flutter/flutter#126812]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I'm using the `webview_flutter plugin: ^4.2.0` and `webview_flutter_wkwebview: ^3.4.2`

And here's my problem, my iPhone swipe doesn't work at all to return to the previous page. Do not understand why? Maybe you have some ideas?

### Expected results

I expect that when I swipe (step back), I will show the previous open page

### Actual results

In fact, the swipe does not work at all

Everything works on android

I just moved from version 3 to version 4+, in version three, I would do like this -

`gestureNavigationEnabled: true`
And that would work great.

### Code sample

<details><summary>Code sample</summary>

```dart
final _key = UniqueKey();
late final WebViewController webViewController;
void initState() {
    super.initState();
    webViewController = WebViewController();
    if (webViewController is WebKitWebViewController) {
      (webViewController as WebKitWebViewController)
          .setAllowsBackForwardNavigationGestures(true);
    }
    webViewController
      ..enableZoom(false)
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..loadRequest(Uri.parse(url));
  }

WebViewWidget(
                  controller: webViewController,
                  key: _key,
                )
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by ostup17** [comment]
My flutter `doctor -v`

```
[✓] Flutter (Channel stable, 3.7.11, on macOS 13.3.1 22E772610a darwin-x64, locale ru-KG)
    • Flutter version 3.7.11 on channel stable at /usr/local/Caskroom/flutter/3.7.0/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f72efea43c (5 weeks ago), 2023-04-11 11:57:21 -0700
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/ostapenkodaniil/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554                        • android-x86    • Android 11 (API 30) (emulator)
    • iPhone 14 Pro (mobile)             • 7493A752-CA3F-44F2-9B4A-BD262B325B9B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)                    • macos                                • darwin-x64     • macOS 13.3.1 22E772610a darwin-x64
    • Chrome (web)                       • chrome                               • web-javascript • Google Chrome 113.0.5672.92

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by darshankawar** [comment]
Thanks for the report @ostup17 
Have you already looked at the migration guide for the plugin https://pub.dev/packages/webview_flutter#migrating-from-30-to-40 and see if it helps in your case ?

**Comment by ostup17** [comment]
> Thanks for the report @ostup17 Have you already looked at the migration guide for the plugin https://pub.dev/packages/webview_flutter#migrating-from-30-to-40 and see if it helps in your case ?

Yes, I have looked at it and used it successfully. The only function that didn't start working is setAllowsBackForwardNavigationGestures which used to be gestureNavigationEnabled: true

**Comment by darshankawar** [comment]
Thanks for the report. Keeping this issue open for team's insights on reported behavior.

**Comment by pooonjuice** [comment]
not
```
if (webViewController is WebKitWebViewController) {
   (webViewController as WebKitWebViewController)
      .setAllowsBackForwardNavigationGestures(true);
}
```
but
```
if (controller.platform is WebKitWebViewController) {
   (controller.platform as WebKitWebViewController)
       .setAllowsBackForwardNavigationGestures(true);
 }
```

it worked.

**Comment by ostup17** [comment]
what controller are you talking about?
Can you add the controller creation code?

> not
> 
> ```
> if (webViewController is WebKitWebViewController) {
>    (webViewController as WebKitWebViewController)
>       .setAllowsBackForwardNavigationGestures(true);
> }
> ```
> 
> but
> 
> ```
> if (controller.platform is WebKitWebViewController) {
>    (controller.platform as WebKitWebViewController)
>        .setAllowsBackForwardNavigationGestures(true);
>  }
> ```
> 
> it worked.

what controller are you talking about?
Can you add the controller creation code?

**Comment by ostup17** [comment]
> not
> 
> ```
> if (webViewController is WebKitWebViewController) {
>    (webViewController as WebKitWebViewController)
>       .setAllowsBackForwardNavigationGestures(true);
> }
> ```
> 
> but
> 
> ```
> if (controller.platform is WebKitWebViewController) {
>    (controller.platform as WebKitWebViewController)
>        .setAllowsBackForwardNavigationGestures(true);
>  }
> ```
> 
> it worked.

Yes, it worked well, thanks!
