### ISSUE TITLE
[CP] [Impeller] Ignore the Z basis when scaling text

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#126870]
### issue_link

https://github.com/flutter/flutter/issues/126510

### Commit Hash

https://github.com/flutter/engine/commit/6dc9b28677b7d3e65594864347a2c1e3c1b19481

### Target

stable

### pr_link

https://github.com/flutter/engine/pull/42053

### Impacted Users

Impeller users.

### Impact Description

When the current transform is scaled non-uniformly, the text in the atlas may wind up being generated at an incorrect size, resulting in either pixelated or crunchy looking text.

### Workaround

No workarounds.

### Risk

low

### Test Coverage

yes

### Validation Steps

* Run the new test in https://github.com/flutter/engine/pull/42053.
* Run the reproduction app in https://github.com/flutter/flutter/issues/126510.

**Comment by bdero** [comment]
cc @zanderso

**Comment by zanderso** [comment]
cp lgtm

**Comment by zanderso** [comment]
cc @XilaiZhang

**Comment by XilaiZhang** [comment]
thanks for the info! Landed
