### ISSUE TITLE
Intent Plugin Alarm Error

### ISSUE THREAD

**Issue by ZwoBot84** [flutter/flutter#12680]
## Steps to Reproduce
 

I want to set an repeating Alarm for each day of the Week, but the Plugin can’t handle the required List of Days.

 

My Code looks like this:

 

_openReminder() async {
AndroidIntent intent = new AndroidIntent(
action: 'android.intent.action.SET_ALARM',
arguments: {
'android.intent.extra.alarm.DAYS': [1,2,3,4,5,6,7 ],
'android.intent.extra.alarm.HOUR': 21,
'android.intent.extra.alarm.MINUTES': 30,
'android.intent.extra.alarm.SKIP_UI': true,
'android.intent.extra.alarm.MESSAGE': 'DayTracker',
'android.intent.extra.alarm.IS_PM': true
  });

## Logs

But this is the Error I got:

 

E/flutter ( 6221): PlatformException(error, Unsupported type [7, 1, 2, 3, 4, 5, 6], null)

E/flutter ( 6221): #0 StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:514)

E/flutter ( 6221): #1 MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:154)

E/flutter ( 6221):

E/flutter ( 6221): #2 AndroidIntent.launch (package:android_intent/android_intent.dart:45)

**Comment by mravn-google** [comment]
The plugin only knows how to populate the Android Bundle with scalar values. See:
https://github.com/flutter/plugins/blob/master/packages/android_intent/android/src/main/java/io/flutter/plugins/androidintent/AndroidIntentPlugin.java#L47

We should be able to generalize this.
