### ISSUE TITLE
[CP] [Impeller] Fix division by zero for transparent shadows

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#126855]
### issue_link

https://github.com/flutter/flutter/issues/126854

### Commit Hash

dd67063fc9219dc5eb5b989e89c784560c7ac483

### Target

stable

### pr_link

https://github.com/flutter/engine/pull/42048

### Impacted Users

iOS users who turn on wide gamut color support

### Impact Description

The impact if visual glitches around the borders of modal dialogs.  We don't know of a case where this could affect the rendering of content that is interactive.

### Workaround

Opting out of wide gamut color by changing the flag.

### Risk

low

### Test Coverage

yes

### Validation Steps

Run the app on iOS with the FLTEnableWideGamut flag set to true.  Present modal dialogs (I'm not sure if there are further steps required).

**Comment by CaseyHillers** [comment]
@zanderso can you review this CP request? If it looks good to you, add the "cp: approved" label.

**Comment by zanderso** [comment]
cp lgtm

**Comment by gaaclarke** [comment]
PR updated, thanks.
