### ISSUE TITLE
[CP] rename AssetManifest.bin to AssetManifest.smcbin

### ISSUE THREAD

**Issue by andrewkolos** [flutter/flutter#126839]
### issue_link

https://github.com/flutter/flutter/issues/124883

### Commit Hash

d3e0e03

### Target

stable

### pr_link

https://github.com/flutter/flutter/pull/126837

### Impacted Users

Windows developers

### Impact Description

As of Flutter 3.10, images do not render on flutter web apps when the host machine has Internet Download Manager installed.

### Workaround

Developer needs to downgrade to 3.7. Otherwise, every user of a flutter web app has to configure their installation of Internet Download Manager to not intercept requests for a file named `AssetManifest.bin`.

### Risk

low

### Test Coverage

yes

### Validation Steps

On Windows, download Internet Download Manager and enable the browser extension. Using a flutter installation (with a clean/deleted cache), create a flutter app. Add an image asset to the app and have the app render it. Running the app on Chrome, the image should display without issue, and Internet Download Manager should not open a download dialog.

**Comment by jonahwilliams** [comment]
LGTM

**Comment by XilaiZhang** [comment]
(this probably got filtered out because it missed the merge-to-stable tag)

**Comment by itsjustkevin** [comment]
I made sure it was merged, didn't miss it.

**Comment by XilaiZhang** [comment]
sorry for the confusion, was trying to say the [filter](https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22cp%3A+approved%22) we used yesterday might have missed it yesterday, but thanks for triaging!
