### ISSUE TITLE
[CP] [Impeller] Always use BGRA10_XR for wide gamut

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#126856]
### issue_link

https://github.com/flutter/flutter/issues/125276

### Commit Hash

762a796770a75f4e27cb043723ea35c19bcb7723

### Target

stable

### pr_link

https://github.com/flutter/engine/pull/42045

### Impacted Users

iOS users who turn on wide gamut color support

### Impact Description

There is a crash when using the app when certain operations happen.  It isn't guaranteed that all usage results in the crash.  The crash is quite divorced from the code the developer is writing.

### Workaround

Disable wide gamut color.  This may not be shippable for some customers though.

### Risk

low

### Test Coverage

yes

### Validation Steps

There are reproduction steps in https://github.com/flutter/flutter/issues/125276.

**Comment by CaseyHillers** [comment]
@jonahwilliams can you review this CP request? If it looks good to you, add the "cp: approved" label.

**Comment by jonahwilliams** [comment]
LGTM
