### ISSUE TITLE
TextAffinity constructor has no documentation

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#12683]

**Comment by zoechi** [comment]
https://docs.flutter.io/flutter/dart-ui/TextAffinity-class.html is an enum
and does not have a constructor. 
Is this still relevant?

**Comment by markusaksli-nc** [comment]
Closing this since [TextAffinity](https://api.flutter.dev/flutter/dart-ui/TextAffinity-class.html) has documentation.
