### ISSUE TITLE
Provide access to the current locale information

### ISSUE THREAD

**Issue by krisgiesing** [flutter/flutter#1268]
Authors will want to use the current locale information to drive their widget logic, similar to what MediaQuery provides.

The casual reader might think that LocaleQuery provides this interface, but it doesn't.

**Comment by Hixie** [comment]
One example of this would be figuring out whether to use a 24-hour variant for the time picker or a 12-hour variant.

**Comment by eseidelGoogle** [comment]
I thought @jason-simmons already had to do this when wiring up package:intl

**Comment by krisgiesing** [comment]
There's a hook on the binding to be notified when the locale changes, but I think we want a convenience wrapper so that widget classes don't need to carry their own state (similar to the aforementioned MediaQuery). MaterialApp already uses the hook to invoke an application-level callback that takes the locale as input and exports an application-specific localized data package, which is then exposed to the widget hierarchy.  But the locale itself isn't exposed unless the application writes some wiring logic to mirror the locale info in the application specific localized data.

**Comment by eseidelGoogle** [comment]
Will this block i18n? https://github.com/flutter/flutter/issues/393

**Comment by Hixie** [comment]
This would definitely make our i18n story more compelling.

**Comment by Hixie** [comment]
`Localization.localeOf()` is now a thing: https://master-docs-flutter-io.firebaseapp.com/flutter/widgets/Localizations/localeOf.html
