### ISSUE TITLE
A little suggestion for flutter desktop

### ISSUE THREAD

**Issue by kw214** [flutter/flutter#126807]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Personally, I feel that flutter does not support the desktop very well, and progress is slow.
Not only that, firebase's support for the desktop has caught up with the slow speed of the tortoise.

### Expected results

none

### Actual results

none

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by stuartmorgan** [comment]
Closing as unactionable, as there is no specific request to track.
