### ISSUE TITLE
Ambiguity in transform.scale constructor docs

### ISSUE THREAD

**Issue by Peddinti-Sriram-Bharadwaj** [flutter/flutter#126822]
**### What information is missing?**
in this website [https://api.flutter.dev/flutter/widgets/Transform/Transform.scale.html](url), the following lines are causing ambiguity :-
'''The scaleX argument provides the scalar by which to multiply the x-axis, and the scaleY argument provides the scalar by which to multiply the y-axis. Either may be omitted, in which case that axis defaults to 1.0.'''

this part in the page Transform.scale is unclear.

What does it mean that the axis defaults to 1.0?
Was it supposed to be that the scaling factor defaults to 1.0?

**### How would you like us to fix this problem?**
I request you to provide a bit more comprehensive statement about this explanation.
As a beginner to flutter coming from web background, I find this unclear to undestand

If at all the statement was supposed to be '' scale defaults to 1.0", please let me know about it, so that I can contribute to the page by making a pull request with the appropriate change made to the sentence.

**Comment by arafaysaleem** [comment]
This issue looks fixed.

**Comment by piedcipher** [comment]
This issue is fixed by #128182. Closing!
