### ISSUE TITLE
Documentation needs to updated to new service name

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#126838]
Reference to `_dartobservatory._tcp` in documentation needs to be changed to `_dartVmService._tcp` before it is deprecated. 

https://docs.flutter.dev/add-to-app/ios/project-setup
https://github.com/flutter/engine/pull/39139

cc @bkonyi

**Comment by andoriyaprashant** [comment]
Hey @vashworth can you please review my pull request 
https://github.com/flutter/engine/pull/42044#issue-1710429208

**Comment by bkonyi** [comment]
@vashworth can you point me towards the right place to edit this documentation? I'm not sure where to look :-)
