### ISSUE TITLE
flutter and dart command return nothing in windows 11 

### ISSUE THREAD

**Issue by alenpaulvarghese** [flutter/flutter#126897]
#### related  #118211
- [x] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Downloaded the latest zip from https://docs.flutter.dev/get-started/install/windows
2. Unzipped the flutter folder to `C:\Users\<username>\Code\flutter`
3. Added the PATH variable `C:\Users\<username>\Code\flutter\bin\`
4. Restart PC
5. Enter the flutter command in terminal

windows version :- 11 22H2 22621.1702
flutter version :- 3.10.0

### Actual results

![image](https://github.com/flutter/flutter/assets/38587581/7b280543-f5b2-4edf-b5b2-47729a99ab18)

### Logs

<details>
<summary>Logs</summary>

```console

flutter is returning nothing

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

same

```

</details>

**Comment by huycozy** [comment]
Hi @alenpaulvarghese 
It seems to be an issue with permission on that path. Please try granting permission for Flutter SDK directory or retry installing Flutter on different drive to see if it works.

**Comment by huycozy** [comment]
Please check [this](https://learn.microsoft.com/en-us/answers/questions/696965/windows-11-folder-read-write-permissions-dont-work) if it can work for you.

**Comment by alenpaulvarghese** [comment]
I tried all 3 methods, and its still not working. the first method, it was already enabled. 
second and third, I tried signing out and typing in the command still it shows nothing.

**Comment by huycozy** [comment]
Can you try cd to `C:\Users\<username>\Code\flutter\bin\` and then call `flutter` to see if it works?

```console
cd C:\Users\<username>\Code\flutter\bin\
flutter
```

Also, you can try [this](https://stackoverflow.com/a/61643789/5921933) as well.

**Comment by alenpaulvarghese** [comment]
![image](https://github.com/flutter/flutter/assets/38587581/d4ffeeef-bce0-4cc5-8035-3c410db06eb6)

**Comment by huycozy** [comment]
Can you try adding Flutter SDK/project directory to anti-virus whitelist and check if it works?

**Comment by alenpaulvarghese** [comment]
I am not using any antivirus other than windows defender. I tried adding flutter into the exclusion list but that didn't fix it either.

**Comment by alenpaulvarghese** [comment]
Found out the issue, I think anaconda was responsible for messing up my PATHS. Solved by using the following answer from SA https://stackoverflow.com/a/66836989/13033981
