### ISSUE TITLE
Best practices for managing multiple apps with some shared code

### ISSUE THREAD

**Issue by stephanie-finch** [flutter/flutter#126877]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Our team would like to spin up multiple different apps that have some portions of code shared. We'd love to get more documentation on best practices on how to manage multi-app codebases. Someone from Google IO's Flutter adventure chat recommended us to request for more documentation here.

### Proposal

More official documentation/videos would be great for things like:
- How to manage packages to share code between apps (or if there are other options), and how to more easily manage dependencies for pubspec.yaml between all the packages
- How to best structure the codebase (e.g., it took us a while to realize VS Code has to open up from a parent directory that contains all packages for hot reloading in our local packages to work)
- How to manage deploy scripts for multiple apps
- Tradeoffs between mono repo vs multi repo

**Comment by darshankawar** [comment]
Thanks for the report @stephanie-finch 
Can you provide us an example related to multiple different apps with shared code ?

**Comment by jascodes** [comment]
@maRci002 Will hot reload work?

**Comment by maRci002** [comment]
> @maRci002 Will hot reload work?

Yes it will.

Multi-repo in a single app is called overengineering https://youtu.be/olG9yVuTlWE. However, reusing packages between apps provides a more efficient and streamlined approach.
