### ISSUE TITLE
Exclude some platforms from a package.

### ISSUE THREAD

**Issue by Abdelazeem777** [flutter/flutter#126911]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I need to use the android platform only from some package and exclude the other platforms.

that's because I only use this package for the Android platform only but for iOS I am using a different package.
but this package is including some libraries in ios which make conflict with some other packages.
that's why I need to completely exclude it from my project.

### Proposal

Something like:
```yaml
dependencies:
    package_name:
        ignore_ios: true

```

**Comment by iapicca** [comment]
@Abdelazeem777  isn't tree shaken already?

**Comment by Abdelazeem777** [comment]
Unfortunately not, 
it still crashes in the build because of some conflicts with other pods

**Comment by iapicca** [comment]
> Unfortunately not, it still crashes in the build because of some conflicts with other pods

@Abdelazeem777
it may be an issue with the plugin
maybe it did not follow [federated plugin development](https://docs.flutter.dev/packages-and-plugins/developing-packages) properly

can you provide an example?

**Comment by Abdelazeem777** [comment]
@iapicca 
the package name is  [fawry_sdk](https://pub.dev/packages/fawry_sdk)

and I already checked the conditional import but I couldn't use it with conditions for android and ios

**Comment by Abdelazeem777** [comment]
Is there any tag or attribute that I can use to remove the ios implementation manually from pubspec.yaml?
