### ISSUE TITLE
Update to version 3.10，BoxDecoration ->DecorationImage has a display error, repeatedly sliding the screen can easily cause it to appear

### ISSUE THREAD

**Issue by nxsheng** [flutter/flutter#126988]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Container->BoxDecoration->DecorationImage->CachedNetworkImageProvider

### Expected results

Correct display

### Actual results

Error display

### Code sample

```
Container(
                      width: 50,
                      height: 50,
                      decoration: BoxDecoration(
                          color: (UtilsCommon.isDarkMode(context)) ? Color(0xFF202020) : Color(0xFFEEEEEE),
                          shape: BoxShape.rectangle,
                          borderRadius: BorderRadius.circular(5.0),
                          image: DecorationImage(
                              image: CachedNetworkImageProvider("${Config.OSSHOST}${element.thumb!}/M"),
                              fit: BoxFit.cover)),
                    ),

```
### Screenshots or Video

![WechatIMG2161](https://github.com/flutter/flutter/assets/9835312/daadafa8-d245-403a-b66a-7d510b73b9b7)

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@nxsheng 
`CachedNetworkImageProvider` comes from third party package https://github.com/Baseflow/flutter_cached_network_image

If you think the behavior is specific to this package, you'll need to report it in dedicated repo. If you are able to replicate the reported behavior without any third party package or using https://docs.flutter.dev/cookbook/images/network-image please provide us complete minimal reproducible code sample.
