### ISSUE TITLE
LocaleQuery is difficult to extend

### ISSUE THREAD

**Issue by krisgiesing** [flutter/flutter#1269]
If an author wanted to provide two different kinds of localization-customized data to the same widget subtree, they would not be able to use LocaleQuery to do so, because it only provides one static `of` method.

**Comment by Hixie** [comment]
They could use a new Inherited widget for their thing (e.g. by subclassing LocaleQuery).

**Comment by krisgiesing** [comment]
They wouldn't really get any benefit out of using LocaleQuery in that case. They might as well subclass InheritedWidget directly.

**Comment by Hixie** [comment]
Hans removed LocaleQuery entirely.
