### ISSUE TITLE
After updating to flutter 3.10 there is something wrong with keyboard recognition in flutter.

### ISSUE THREAD

**Issue by bazl-E** [flutter/flutter#126989]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

make a simple project 
1- try to make a bottom sheet  with property of goes up with presence of keyboard
2- make a form screen the while you are on top most filed try to scroll without dismissing keyboard

### Expected results

before flutter 3.10 [](url)

https://github.com/flutter/flutter/assets/84278736/6cf62f05-f799-458b-9bf9-d235eac19dc1

### Actual results

after updating to flutter 3.10

https://github.com/flutter/flutter/assets/84278736/4ba57c9c-95a6-46f7-88c7-1eb7b810b770

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.2.1 22D68 darwin-arm64, locale
    en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.78.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by SudipZluck** [comment]
Same Problem

**Comment by huycozy** [comment]
@bazl-E It seems you're hitting a similar issue at https://github.com/flutter/flutter/issues/126653. You can try adding padding as sample code at https://github.com/flutter/flutter/issues/126653#issuecomment-1545636696. 

If it doesn't work, it could be caused by 3rd package or implementation code. So Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so that we may verify this. Thanks!

**Comment by bazl-E** [comment]
> @bazl-E ,I found the solution to it, its cause is using the flutter_screenutils package, setting useInheritedMediaQuery: true in ScreenUtilInit() will solve it.
> 
> `import 'package:flutter/material.dart'; import 'package:flutter_screenutil/flutter_screenutil.dart';
> 
> void main() { runApp(const MyApp()); }
> 
> class MyApp extends StatelessWidget { const MyApp({super.key});
> 
> // This widget is the root of your application. @OverRide Widget build(BuildContext context) { return ScreenUtilInit( // Add this line to solve useInheritedMediaQuery: true, builder: (context, child) => MaterialApp( debugShowCheckedModeBanner: false, theme: ThemeData( colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple), useMaterial3: true, ), home: const LoginPage(), ), ); } }`

@SudipZluck Thank you this one fixed my issue 😍😍
