### ISSUE TITLE
'package:flutter/src/gestures/binding.dart': Failed assertion: line 352 pos 12: '!locked': is not true.

### ISSUE THREAD

**Issue by victormaur0** [flutter/flutter#126991]
```
The following assertion was thrown while handling a pointer data packet:
'package:flutter/src/gestures/binding.dart': Failed assertion: line 352 pos 12: '!locked': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:352:12)
#3      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:320:7)
#4      GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:293:9)
#5      _invoke1 (dart:ui/hooks.dart:158:13)
#6      PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:382:7)
#7      _dispatchPointerDataPacket (dart:ui/hooks.dart:91:31)
(elided 2 frames from class _AssertionError)
```

**Comment by victormaur0** [comment]
The following assertion was thrown while handling a pointer data packet:
'package:flutter/src/gestures/binding.dart': Failed assertion: line 352 pos 12: '!locked': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:352:12)
#3      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:320:7)
#4      GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:293:9)
#5      _invoke1 (dart:ui/hooks.dart:158:13)
#6      PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:382:7)
#7      _dispatchPointerDataPacket (dart:ui/hooks.dart:91:31)
(elided 2 frames from class _AssertionError)

**Comment by darshankawar** [comment]
@victormaur0 
Can you provide `flutter doctor -v` and complete reproducible code sample that shows the reported error ?
When you open a new issue, please try to use new issue template and fill out requested details so that we'll have enough info to work with.
