### ISSUE TITLE
[Impeller] Is using Impeller for rendering argb data for a video player more performant than texture access?

### ISSUE THREAD

**Issue by Aaron009** [flutter/flutter#126950]
## Details

Problem Description:
I'm currently working on a video player project using Flutter and I'm thinking of using Impeller for rendering. My use case is a page that may contain multiple video players, similar to the functionality provided in the Telegram app. It's very smooth in Telegram, but when trying to replicate it in Flutter, the performance seems to drop significantly and become very laggy. Most of the video players on the market use texture integration for rendering, but it will lead to poor performance when rendering multiple video players.

I wonder if impeller for argb rendering would improve performance for this user. Improve performance of multiple video players on a single page?

If Impeller can indeed improve rendering performance, I hope that the Impeller development team can provide some guidance or suggestions, and would appreciate it.

Steps to reproduce:

Create a page with multiple video players and try to play all videos at the same time. I've noticed that in this case, the performance of the application drops significantly.

**Comment by jonahwilliams** [comment]
I'm not sure that I understand your question. Impeller is a renderer for Flutter canvas operations, it doesn't really have anything to do with how a video player works, and IIRC these plugins are just using inline texture composition.
