### ISSUE TITLE
Spaces in Android SDK path cause problems on Windows

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#12698]
See https://github.com/flutter/flutter/issues/9976#issuecomment-301178898.

**Comment by mit-mit** [comment]
Tagging first-hour and m3 as this is a likely internationalisation problem.

**Comment by goderbauer** [comment]
Has anybody tried this recently? I believe @cbracken and @bkonyi fixed some issues with spaces for Flutter recently.

**Comment by cbracken** [comment]
I resolved issues in `flutter_tools` involving spaces in the Flutter SDK path and in the project path. What @bkonyi looked at were spaces in package paths (in the VM's loader). AFAIK neither of us has looked at spaces in the Android SDK (or Xcode, for that matter) paths.

**Comment by cbracken** [comment]
I've verified this currently works on macOS. Following up with Linux and Windows today.

**Comment by cbracken** [comment]
Verified this works on Windows too.

In case it helps anyone else, when setting the ANDROID_HOME environment variable on Windows (cmd.exe - not sure about PowerShell) quotes are unnecessary (and in fact wrong).

**Good:**
```bat
set ANDROID_HOME=C:\some\path\with spaces\Android\sdk
```
**Bad:**
```bat
set ANDROID_HOME="C:\some\path\with spaces\Android\sdk"
```
