### ISSUE TITLE
Impeller much more janky when closing screens with Cupertino

### ISSUE THREAD

**Issue by mark8044** [flutter/flutter#126986]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

With version 3.10 (Impeller enabled), right now swiping to close screen on my app is very very janky.  Noticeable stutter on the screens as you swipe to close them (Cupertino transitions).  With 3.7 swiping to close a screen was smooth as silk, even if you stopped half way and just swipe left and right it was super fast.

With Impeller its extremely janky, even more so when the screen being swiped away and the underlying screen have images on them (more heavy content).

Now, I understand this bug report will likely be quickly closed as I cannot provide reproducible code, but just putting this here in case anyone on the team wants to keep this in the back of their mind.  My app can continue on the App Store with 3.7 version, but this could be problem for others freshly releasing apps based on 3.10

### Expected results

No jank

### Actual results

Lots of jank

### Code sample

My app is extremely large with many many page routes, thus impossible to rip out sample code

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.0, on macOS 12.6.5 21G531 darwin-x64, locale en-US)
    • Flutter version 3.10.0 on channel stable at /Users/ch/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (3 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/-------/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Connected device (2 available)
    • iPhone 14 Pro (mobile) • --- • ios        • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64 • macOS 12.6.5 21G531 darwin-x64

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by jonahwilliams** [comment]
We're always working on performance and looking for ways to make applications run better. Unfortunately, without videos/images/timeline traces or any clues as to why your particular application is slow, we can't tell you if we're aware of or have fixes planned for the issue you are experiencing.

**Comment by mark8044** [comment]
> 

Yup, totally understand where you are coming from.  This is more of an FYI-- perhaps as you are working on other issues, this will ring a bell one day

**Comment by jonahwilliams** [comment]
You might try the 2.11 beta and see if there are any major changes there. However if you can't give us any hints as to what your code is doing, there isn't much use in keeping this issue open. If you have questions or concerns that aren't a good fit for the issue tracker, you can also reach us on the flutter discord.
