### ISSUE TITLE
Add the ability to pass a CSP nonce to flutter.js that will be used when loading additional scripts

### ISSUE THREAD

**Issue by jacobsimionato** [flutter/flutter#126977]
Strict CSPs require that any script tags that are created have a `nonce` attribute that specifies the same nonce included in the CSP header, to ensure all scripts that are loaded are trusted. Currently, Flutter is only compatible with the weaker `strict-dynamic` mode.

Flutter loads many scripts dynamically, e.g. flutter.js loads main.dart.js, and main.dart.js loads additional parts. And the engine loads canvaskit etc. It'd be great if the developer could pass flutter.js a nonce, and then Flutter could use that when loading all additional scripts. E.g.
```
_flutter.loader.loadEntrypoint({
          entrypointUrl: 'my_app/main.dart.js',
          nonce: my_nonce,
          onEntrypointLoaded: function(engineInitializer) {
            engineInitializer.initializeEngine().then(function(appRunner) {
              appRunner.runApp();
            });
          }
        });
```

It's worth considering if Flutter can automatically find the right nonce to use somehow e.g. there are approaches internally that copy the nonce from other script tags in the DOM. Overall, though, I think adding it as an explicit parameter passed by the app developer seems less likely to cause breakages and confusion.

This is not blocking anyone at the moment, but it likely will eventually when an app that is already using a `strict` CSP wants to integrate Flutter without accepting a security regression.

See internal bug b/274360267 for more details.

**Comment by ditman** [comment]
This could be a potential fix for a big part of: https://github.com/flutter/flutter/issues/80221

**Comment by ditman** [comment]
This should be available soon in `master`!

**Comment by jacobsimionato** [comment]
David, I tried this out, but I got an error where main.dart.js could not be loaded because there is no nonce on that script tag.

I think perhaps we need to move the nonce parameter to loadEntrypoint rather than initializeEngine because we need it before main.dart is even loaded. See internal change cl/572795063 as an example. This worked for me locally. I'd send a PR, but I'm not sure if there are other places that rely on the current behavior, or if maybe I'm missing something?

**Comment by ditman** [comment]
@jacobsimionato what's the CSP configuration that we want to support? Currently, it's this:

```
script-src 'self' 'nonce-YOUR_NONCE_VALUE' 'wasm-unsafe-eval';
font-src https://fonts.gstatic.com;
style-src 'nonce-YOUR_NONCE_VALUE';
```

Do we want to remove `'self'` from `script-src`?

**Comment by jacobsimionato** [comment]
Yeah I think so! I'm struggling to figure out what the implications of that are though. I thought nonces were required for every script tag, regardless of whether 'self' is present here?

This is the content security policy for the app that is failing:
```
Content-Security-Policy: require-trusted-types-for 'script'
Content-Security-Policy: script-src 'report-sample' 'nonce-YOUR_NONCE_VALUE' 'unsafe-inline' 'unsafe-eval';object-src 'none';base-uri 'self';report-uri
```

I get the error:
```
Refused to load the script 'https://<URL of the app>/web/main.dart.js' because it violates the following Content Security Policy directive: "script-src 'report-sample' 'nonce-HA8EXnECp_fqWPFwvPxA6A' 'unsafe-inline' 'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

**Comment by ditman** [comment]
This is a good proposal, I think I can add a `nonce` to `loadEntrypoint` that then gets forwarded automagically to `initializeEngine`. I think the change should only affect `flutter.js`, actually!

**Comment by jacobsimionato** [comment]
That sounds ideal! Thank you :-D

**Comment by ditman** [comment]
> then gets forwarded automagically to initializeEngine

I spoke too soon, and the code to achieve this is **a big mess**. For now, the nonce will need to be set in 2 places :/
