### ISSUE TITLE
Functions missing in sound API

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#127]
<a href="https://github.com/vlidholt"><img src="https://avatars.githubusercontent.com/u/1539812?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [vlidholt](https://github.com/vlidholt)**
_Thursday Aug 13, 2015 at 23:45 GMT_
_Originally opened as https://github.com/flutter/engine/issues/611_

----

In order of priority:
- SoundTrack:s cannot be looped (needed for background music)
- There are no callbacks when SoundTrack:s complete
- SoundTrack:s cannot control the volume (would be required for fading/mixing different music tracks)
- SoundEffect:s should use Android's SoundPool classes instead of MediaPlayer (required for the following bullets)
- SoundEffect:s are missing looping, volume, pitch, and pan controls (required for positional audio)
- SoundEffectStream:s are not being properly deleted when finished playing and thus leaking memory
- SoundTrack:s are not being properly deleted when finished playing and thus leaking memory
- All other missing callbacks for SoundTrack and SoundEffect.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/eseidelGoogle"><img src="https://avatars.githubusercontent.com/u/11857803?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [eseidelGoogle](https://github.com/eseidelGoogle)**
_Thursday Aug 13, 2015 at 23:48 GMT_

----

Thank you! This is very helpful.

**Comment by FlutterIssues** [comment]
<a href="https://github.com/vlidholt"><img src="https://avatars.githubusercontent.com/u/1539812?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [vlidholt](https://github.com/vlidholt)**
_Tuesday Nov 03, 2015 at 23:52 GMT_

----

API here: https://github.com/vlidholt/sky_engine/blob/master/skysprites/lib/src/sound.dart

**Comment by vlidholt** [comment]
Split this issue up in a number of smaller issues, closing.

**Comment by sethladd** [comment]
Related: https://github.com/flutter/flutter/issues/729
