### ISSUE TITLE
Add a controller to SelectionArea

### ISSUE THREAD

**Issue by cgutierr-zgz** [flutter/flutter#127025]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I want to request a controller for the `SelectionArea` Widget.
Right now I find it almost impossible to select al items under a SelectionArea by default programmatically, the only way is after a user input the `selectableRegionState` is created.

This is a current implementation
```dart
SelectionArea(
                        onSelectionChanged: (value) => print(value?.plainText),
                        contextMenuBuilder: (context, selectableRegionState) {
                          this.selectableRegionState = selectableRegionState; // <- This is when i initialize the state

                          return Text('....'); // your context menu
                        },
                        child: Stack(
                          alignment: Alignment.center,
                          children: ...state.result.map(TextQuad.new), // A widget with text's
                        ),
),
```

### Proposal
```dart
SelectionArea(
                       controller: controller, // <- new
                        onSelectionChanged: (value) => print(value?.plainText),
                        child: Stack(
                          alignment: Alignment.center,
                          children: ...state.result.map(TextQuad.new), // A widget with text's
                        ),
                      ),
```
---
And use it like:

`controller.selectAll();`

**Comment by HansMuller** [comment]
CC @chunhtai

**Comment by Renzo-Olivares** [comment]
Hi @cgutierr-zgz, this should be possible if you provide a key to `SelectionArea`, you can access its `selectableRegion` through there. This is possible after https://github.com/flutter/flutter/pull/152882, `selectionAreaKey.selectableRegion.selectAll()`. Let me know if this works for you.

**Comment by BenjiFarquhar** [comment]
Can we get `selectWord` on the `selectionAreaKey.selectableRegion`? I've lost tap behavior of `SelectionArea` due to using `GestureDetector` over the `Text`, but don't want to lose doubleTap to select the word.
