### ISSUE TITLE
Request for a feature; Single EXE for windows

### ISSUE THREAD

**Issue by rodi-10** [flutter/flutter#127086]
Good day Flutter team,

I have a client that is requesting for a single exe for deployment, and I've stumble upon these threads; #105655, #81134 which is being tagged as duplicate for this #75200 thread. We are wondering if there's a new recent change in flutter windows that can do this since it's been years since #75200 has been posted.

Thankyou.

Here's my flutter doctor -v
[√] Flutter (Channel stable, 3.7.7, on Microsoft Windows *)
    • Flutter version 3.7.7 on channel stable at *
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (2 months ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at *
    • Platform android-33-ext5, build-tools 33.0.2
    • Java binary at: *
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at *

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.4)
    • Visual Studio at *
    • Visual Studio Community 2022 version 17.5.33530.505
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.1)
    • Android Studio at *
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] VS Code, 64-bit edition (version 1.76.1)
    • VS Code at *
    • Flutter extension version 3.64.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1702]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 113.0.5672.93
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 113.0.1774.42

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by darshankawar** [comment]
@rodi-10 
I don't think there's any change since [this](https://github.com/flutter/flutter/issues/75200) issue was closed as not feasible citing the reasons as mentioned in it.

You can take a look at https://agnelselvan.medium.com/how-to-build-a-single-exe-file-from-flutter-windows-build-c91b9bb7281f and https://medium.com/codex/build-windows-exe-file-in-flutter-f940f336fd98 to see if they help in your case or not.

Closing this issue.

**Comment by rodi-10** [comment]
As of now, Found a third party app for this, its called Enigma Virtual Box.. This will package every files to single exe. NOT INSTALLER

Tutorial from yt: youtube.com/watch?v=LEk2Ry5ERZQ&t=93s

Tested output files from both local and virtualBox
