### ISSUE TITLE
[Impeller] Remove the list failing Vulkan unit-tests that the test harness skips.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#127069]
[This list is out of date](https://github.com/flutter/engine/blob/a22dd64383358d40e0edd08fc0837cb0c93f1283/testing/impeller_vulkan_test_status.csv).

**Comment by chinmaygarde** [comment]
cc @gaaclarke

**Comment by gaaclarke** [comment]
Got rid of this in f499709cd23af81e261c62079b4be0311aa6f7c2
