### ISSUE TITLE
Improve resilience of Gradle wrapper download

### ISSUE THREAD

**Issue by aam** [flutter/flutter#12708]
from [travis log](https://travis-ci.org/flutter/flutter/jobs/292640911), `+./bin/flutter update-packages` failed with

```
Downloading Gradle Wrapper...
Download failed.
URL: https://android.googlesource.com/platform/tools/base/+archive/0b5c1398d1d04ac245a310de98825cb7b3278e2a/templates/gradle/wrapper.tgz
Error: 429 Too Many Requests
```

**Comment by jmagman** [comment]
Is there a `Retry-After` header we can check?

**Comment by zanderso** [comment]
The `Cache` is using `fetchUrl` from `base/net.dart`, but appears not to be specifying to retry failed requests some number of times (with exponential backoff) as allowed by that API. Optionally, `fetchUrl` could check the response header for guidance.

**Comment by Hixie** [comment]
See also https://github.com/flutter/flutter/issues/19235

**Comment by dnfield** [comment]
Can we close this? It looks like we now have retries for it, and I can't recall seeing this error for some time. Retries appear to have been added in https://github.com/flutter/flutter/pull/64512 - @jonahwilliams

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
