### ISSUE TITLE
Persistent Bottom Sheet tap target for swipes isn't forgiving enough?

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1270]
Testing the persistent bottom sheet in the gallery app. I'm finding that if I don't start my swipe down absolutely inside of the sheet, I can't get it to swipe down. If I start my swipe seemingly just a few pixels above the the line, the swipe down doesn't take effect.

Not sure if we have leeway to accept a swipe that starts within a small margin above the sheet itself, but that would make this component more user friendly.

**Comment by sethladd** [comment]
cc @HansMuller

**Comment by guidezpl** [comment]
I agree, however, I'm worried adding this behavior may block interaction with underlying elements. Also, the bottom sheets on existing platforms don't use extra padding for the swipe down to dismiss action (Google Maps, for example). For these reasons and to remain consistent, I will close this issue. Feel free to reopen
