### ISSUE TITLE
Update ListTile to match M3 specs

### ISSUE THREAD

**Issue by jamesgorman2** [flutter/flutter#127075]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

_I am currently finalising a PR that addresses these issues._

### Steps to reproduce

See code sample.

### Expected results

- IconButtons are not correctly aligned in a ListTile
    - padding causes `IconButton`s to not align with `Icon`s
    - This also impacts CheckboxListTile, RadioListTile and SwitchListTile. It does not impact ExpansionTile.

- ListTile text uses M2 baseline alignment rather than box-stacking
    - M3  spec is to stack the text boxes and centre or top align depending on size

- ListTile missing overline text element
    - Both M2 & M3 have an overline label available above the headline that is not present

- ListTile cannot create 64x114 video leader for M3 (*)
    - height is restricted to 56dp

- ListTile incorrect trailing icon and text colour M3
    - uses `onSurface`, should be `onSurfaceVariant`

- ListTile 8dp padding not applied for 56dp high leading image in one-line tile M3

- ListTile 12dp padding not applied for three-line M3
    - uses default 8dp padding
    - it would also not be applied if 64dp high video was available as per (*)

- ListTile having video leader flush with start requires manually setting all padding
    - Use case: Ergonomic issue - requires the developer to know not to see the vertical padding.
    - Proposal: Declarative properties on ListTIle to tell it the type of the leading or trailing element.
    Eg:
        - https://github.com/jamesgorman2/flutter/blob/1a1b07772db26a76004526a9d74118382160ed1d/packages/flutter/lib/src/material/list_tile.dart#L335
        - https://github.com/jamesgorman2/flutter/blob/1a1b07772db26a76004526a9d74118382160ed1d/packages/flutter/lib/src/material/list_tile.dart#L1208

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        visualDensity: VisualDensity.standard,
      ),
      home: Scaffold(
        body: SingleChildScrollView(
          child: Column(
            children: [
              const SizedBox(height: 8),
              ListTile(
                tileColor: Colors.black26,
                leading: const SizedBox(
                  height: 56,
                  width: 56,
                  child: Placeholder(),
                ),
                title: const Text('56x56 image'),
                onTap: () {},
              ),
              ListTile(
                tileColor: Colors.black12,
                
                leading: const SizedBox(
                  height: 64,
                  width: 114,
                  child: Placeholder(),
                ),
                title: const Text('64x114 video'),
                onTap: () {},
              ),
              ListTile(
                tileColor: Colors.black26,
                isThreeLine: true,
                leading: const SizedBox(
                  height: 64,
                  width: 114,
                  child: Placeholder(),
                ),
                title: const Text('Three line video'),
                subtitle: const Text('Should have 12 dp padding top and bottom'),
                onTap: () {},
              ),
              ListTile(
                tileColor: Colors.black12,
                title: const Text('One line icon'),
                trailing: const Icon(Icons.more),
                onTap: () {},
              ),
              ListTile(
                tileColor: Colors.black26,
                title: const Text('One line iconButton'),
                trailing: IconButton(
                  onPressed: () {},
                  icon: const Icon(Icons.more),
                ),
                onTap: () {},
              ),
              ListTile(
                tileColor: Colors.black12,
                isThreeLine: true,
                title: const Text('Three line icon'),
                subtitle: const Text('Top right aligned'),
                trailing: const Icon(Icons.more),
                onTap: () {},
              ),
              ListTile(
                tileColor: Colors.black26,
                isThreeLine: true,
                title: const Text('Three line iconButton'),
                subtitle: const Text('8 dp down and left from the plain icon'),
                trailing: IconButton(
                  onPressed: () {},
                  icon: const Icon(Icons.more),
                ),
                onTap: () {},
              ),
              const ExpansionTile(
                backgroundColor: Colors.black12,
                title: Text('Exansion tile'),
                subtitle: Text('You can see the 1px gap above when hovering or holding'),
                children: [
                  ListTile(
                    title: Text('Expansion child'),
                  ),
                ],
              ),
              const ExpansionTile(
                backgroundColor: Colors.black26,
                title: Text('Exansion tile'),
                subtitle: Text('Expand both of us to see the double line'),
                children: [
                  ListTile(
                    title: Text('Expansion child'),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel m3_list_tile, 3.11.0-6.0.pre.132, on macOS 12.6.5 21G531 darwin-arm64, locale en-AU)
    ! Upstream repository git@github.com:jamesgorman2/flutter.git is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to git@github.com:jamesgorman2/flutter.git to dismiss this error.
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] Android Studio (version 2022.2)
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.2)
[✓] IntelliJ IDEA Community Edition (version 2022.1.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.1)
[✓] IntelliJ IDEA Community Edition (version 2023.1.1)
[✓] IntelliJ IDEA Community Edition (version 2023.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
[✓] VS Code (version 1.76.1)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment]
Thanks for the report and PR. 

>IconButtons are not correctly aligned
padding causes IconButtons to not align with Icons

Can you please share the M3 specs that align with this? On [Lists layout specs](https://m3.material.io/components/lists/specs#eeeb78e0-265d-4e81-96ba-c2340c348a90), it only mentions horizontal paddings.

**Comment by jamesgorman2** [comment]
Sure. 
Here are the centre- and top-aligned checkbox layouts, and a couple of configurations showing how icons, checkboxes and trailing support vertically align. The text is the guts of the vertical alignment stuff from the end of the layout section. 

<img width="200" alt="Screen Shot 2023-05-18 at 10 44 53 pm" src="https://github.com/flutter/flutter/assets/7088248/9cf54fa5-37ba-462d-b70e-994aa89e96a7">
<img width="200" alt="Screen Shot 2023-05-18 at 10 45 13 pm" src="https://github.com/flutter/flutter/assets/7088248/8fd23957-cbbe-41f2-bf2e-af0c1d0ee4fc">
<img width="200" alt="Screen Shot 2023-05-18 at 10 47 41 pm"
 src="https://github.com/flutter/flutter/assets/7088248/d35d679e-420a-4d1b-98c1-c0b825685a1f">
<img width="200" alt="Screen Shot 2023-05-18 at 10 47 48 pm" src="https://github.com/flutter/flutter/assets/7088248/32f568da-2c77-406c-9220-e61bc7581860">
<img width="200" alt="Screen Shot 2023-05-18 at 11 04 30 pm" src="https://github.com/flutter/flutter/assets/7088248/f737f1d0-1d07-486f-ac9a-60202795b561">


From the design kit, they distinguish icon, radio, checkbox and switch, but only the switch has a different size, but the same unpadded layout (ie, it shares its padding with the list tile).

<img width="200" alt="Screen Shot 2023-05-18 at 10 52 29 pm" src="https://github.com/flutter/flutter/assets/7088248/096f2720-933b-44e4-ada9-6ec4d959013e">
<img width="200" alt="Screen Shot 2023-05-18 at 10 58 14 pm" src="https://github.com/flutter/flutter/assets/7088248/df04ecd0-c641-4f51-87b1-a5d74a560a67">

**Comment by huycozy** [comment]
Thanks for your response. But it seems I haven't understood your idea. Do you mean the padding of the `IconButton` (circled in red below) is redundant? Should it equal Icon padding (=0)?

- Your sample code:
![Screenshot 2023-05-19 at 12 37 53](https://github.com/flutter/flutter/assets/104349824/f9a94c3c-3e59-43b6-8659-e9525b90974b)

- M3 design (not exactly the same since it's leading element, but just used to compare the padding)
![Screenshot 2023-05-19 at 12 35 58](https://github.com/flutter/flutter/assets/104349824/9cd5252b-505d-4043-a9e1-b21f0695641a)

So I think IconButton padding displays as intended.

**Comment by jamesgorman2** [comment]
> Do you mean the padding of the IconButton (circled in red below) is redundant? Should it equal Icon padding (=0)?

Sort of.  

To the end user, it should appear as if a clickable icon/standard icon button in a list tile has no padding except that described by the list tile.

A clickable icon does need a larger tap target area (such as described by the IconButton's padding). In the list tile, this is already provided by the red padding marks.

An example where this causes an inconsistency in the current Flutter implementation is between the expand/shrink icon in ExpantionTile and the radio/checkbox of CheckboxTile and RadioTile. In both these cases the icon represents the state of the tile, so I would expect them to be similarly aligned, but the ExpansionTile uses an Icon, while the others use an IconButton, so they do not align.

From the spec, it needs a little reading between the lines. They clearly specify radio buttons and checkboxes as having the same layout as a standard icon button, but in the list spec they use them as if the padding (state layer) is part of the list tile and the alignment is on the visual element.

If you used a filled, tonal or outline icon button, then yes the current behaviour is correct since the visual boundary and the  tap area are the same.

**Comment by huycozy** [comment]
Thanks for your response. Labeling the issue for more opinions. 

IMO, I would recommend you file a separate issue and PR for above issues for better tracking and reviews PR (ListTile/ExpansionTile/padding/color/etc).

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.10.1, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.10.1 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (26 hours ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.11.0-6.0.pre.153, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.11.0-6.0.pre.153 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e49d35d3a6 (35 minutes ago), 2023-05-18 22:26:29 -0400
    • Engine revision bca11a423f
    • Dart version 3.1.0 (build 3.1.0-125.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by TahaTesser** [comment]
@huycozy 
Please take the necessary actions to consolidate this issue for `ListTile` and pick one of the other `ExpansionTile` to put all the `ExpansionTile` issues

**Comment by TahaTesser** [comment]
Hi @jamesgorman2 

# ListTile

Hi @jamesgorman2

We need some clarifications on the issues you raised.

1. Trailing padding

> IconButtons are not correctly aligned in a ListTile

> • padding causes `IconButton`s to not align with `Icon`s

> To the end user, it should appear as if a clickable icon/standard icon button in a list tile has no padding except that described by the list tile.

Here is the training element positioned before the padding. Also note this is not actually an icon button but a checkbox, this doesn't have a lot of inner padding. 

![Screenshot 2023-05-23 at 14 16 53](https://github.com/flutter/flutter/assets/48603081/1016cd67-36aa-4870-956c-776d9556a440)



Both Compose and Flutter follows the specs here. You can see the icon button appears to be more left due to its own padding. This doesn’t icon button to make appear like an “icon button in a list tile has no padding except that described by the list tile”. 

Here is a comparsion of [Compose](https://developer.android.com/reference/kotlin/androidx/compose/material3/package-summary#ListItem(kotlin.Function0,androidx.compose.ui.Modifier,kotlin.Function0,kotlin.Function0,kotlin.Function0,kotlin.Function0,androidx.compose.material3.ListItemColors,androidx.compose.ui.unit.Dp,androidx.compose.ui.unit.Dp)) and Flutter.  You can see the icon button before the padding and this padding isn’t adjusted if IconButton is provided.

![Screenshot 2023-05-23 at 14 20 07](https://github.com/flutter/flutter/assets/48603081/ab17ee1e-15ba-40de-8c8b-d7dbe33ae903)
![Screenshot 2023-05-23 at 14 20 17](https://github.com/flutter/flutter/assets/48603081/760ffc01-f130-4010-bdc3-1697bb1b5054)


I also couldn’t find any mention of such behavior in the specs or guidelines
[https://m3.material.io/components/lists/guidelines](https://m3.material.io/components/lists/guidelines), please let me know if I missed it. 

1. baseline alignment

> ListTile text uses M2 baseline alignment rather than box-stacking

> • M3 spec is to stack the text boxes and centre or top align depending on size

Can you share where this is mentioned? 

3. ListTile missing overline text element

This is not specific to M3, and also exists in M2 specs but has never been requested until this issue. As a result, it wasn’t part of the M3 migration. This could be a welcome feature, which should be done in a separate PR.

![Screenshot 2023-05-23 at 14 37 14](https://github.com/flutter/flutter/assets/48603081/13acf169-1575-42ba-a65c-9fef6d2b4dec)

4. Video leader (and leading image)

This is not specific to M3, also exists in M2 specs. AFAIK, there is no specific component for this in M2 and M3, these are just specs on embedding image and video

There is no such video leader component in the native implementation for M2 and M3. 

Just the specs in M2 as well.  Not an actual component AFAIK

![Screenshot 2023-05-23 at 14 40 09](https://github.com/flutter/flutter/assets/48603081/0cca2068-85ac-417f-9963-36b287416169)



5. ListTile incorrect trailing icon and text colour M3

> ◦ uses `onSurface`, should be `onSurfaceVariant`
> 

`onSurfaceVariant` is used for the icon. 
[https://github.com/flutter/flutter/blob/8e3319fd8e3ea475e9cbf332e514a11672b9f590/packages/flutter/lib/src/material/list_tile.dart#L1596](https://github.com/flutter/flutter/blob/8e3319fd8e3ea475e9cbf332e514a11672b9f590/packages/flutter/lib/src/material/list_tile.dart#L1596)
[https://github.com/flutter/flutter/blob/8e3319fd8e3ea475e9cbf332e514a11672b9f590/packages/flutter/lib/src/material/list_tile.dart#L476-L480](https://github.com/flutter/flutter/blob/8e3319fd8e3ea475e9cbf332e514a11672b9f590/packages/flutter/lib/src/material/list_tile.dart#L476-L480)

6. ListTile 8dp padding not applied for 56dp high leading image in one-line tile M3

As mentioned above, there is no image or video component to make this padding changes. Even on the Android side.

7. ListTile 12dp padding not applied for three-line M3

Good catch. This should be an easy fix if the golden changes are worthwhile.

8. ListTile having video leader flush with start requires manually setting all padding

Same point as above for this.

**Comment by jamesgorman2** [comment]
>  baseline alignment
> Can you share where this is mentioned?

https://m3.material.io/components/lists/overview

> Alignment: Elements in a list item are middle-aligned unless it is at or above 88dp (such as when a list item contains three lines of text) at which point everything is top aligned

**Comment by jamesgorman2** [comment]
> Trailing padding
> I also couldn’t find any mention of such behavior in the specs or guidelines
> https://m3.material.io/components/lists/guidelines, please let me know if I missed it.

There is no explicit spec for icon buttons in lists. See https://github.com/flutter/flutter/issues/127075#issuecomment-1553035734 and
https://github.com/flutter/flutter/issues/127075#issuecomment-1554180188

**Comment by jamesgorman2** [comment]
> Video leader (and leading image)
> This is not specific to M3, also exists in M2 specs. AFAIK, there is no specific component for this in M2 and M3, these are just specs on embedding image and video

As best I read it they are a spec for elements of a specific size. Their content doesn't matter - image and video are just how they are referred to in the spec.

**Comment by TahaTesser** [comment]
Regarding https://github.com/flutter/flutter/issues/127075#issuecomment-1562573832

Is this any different from the current ListTile? Does it misalign children? Can you please provide an isolated example of this?  


Regarding https://github.com/flutter/flutter/issues/127075#issuecomment-1562580585.

The explanation doesn't match the specs or the native explanation.
