### ISSUE TITLE
"wrapping hell" like this

### ISSUE THREAD

**Issue by cjztool** [flutter/flutter#12706]
```
class A xxxx { 
	@override
	Widget build(BuildContext context) {
		return new B(
			child:new C(
				child:new D(
					child:new E(
						child:new F(
							child:new G(
				...
							),
						),
					),
				),
			),
		);
	}
}
```
will Flutter improve API ?

**Comment by sethladd** [comment]
Thanks for the feedback!

The best advice we can offer now is to refactor your largely nested structures into methods and new widgets. Encapsulation helps a lot.

For example, we might recommend:

```
class A xxxx { 
        Widget constructD() {
          return new D(
	     child:new E(
	        child:new F(
                   child:new G(
				...
                    ),
                 ),
              ),
            ),
        }

	@override
	Widget build(BuildContext context) {
		return new B(
			child:new C(
				child: constructD()
			),
		);
	}
}
```

cc @mit-mit @devoncarew for https://github.com/flutter/flutter-intellij/issues/1250

fyi @kasperl @sandholm

**Comment by sethladd** [comment]
Really appreciate the feedback. Right now, we have no immediate plans to change the code structure, but we encourage encapsulation and refactoring out into methods and other widget classes. I'll close this now but the feedback is received and is helpful.

**Comment by JosephDunivan** [comment]
I'm having trouble refactoring widgets that use future builder to take in json data in a Listbuilder. If I try to abstract the code then I lose access to my variables. Is there anywhere I can learn more about what to do?

**Comment by zoechi** [comment]
@JosephDunivan 
Please consider asking support questions in one of the other channels listed at http://flutter.io/support . I think this is a good question for StackOverflow if you add the code that demonstrates your problem.
