### ISSUE TITLE
[release] exception on mac packaging release builder

### ISSUE THREAD

**Issue by XilaiZhang** [flutter/flutter#127051]
Mac packaging_release_builder encountered an uncaught exception during the 3.10.1 stable hotfix release. Seems like an assertion error was reported.

[example recipe exception](https://luci-milo.appspot.com/ui/p/dart-internal/builders/flutter/Mac%20packaging_release_builder/96/overview)

**Comment by godofredoc** [comment]
This is caused by duplicated dimensions coming from dimensions and drone_dimensions. Drone dimensions need to replace top level dimensions on duplicates.

**Comment by godofredoc** [comment]
Fix: https://flutter-review.googlesource.com/c/recipes/+/44741
