### ISSUE TITLE
[go_router] Preserve route name case when caching `_nameToPath`

### ISSUE THREAD

**Issue by Khalidm98** [flutter/flutter#127016]
### Is there an existing issue for this?

- [x] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. implement multiple screens (I have more than 50) that will be linked to routes
2. configure routes with `path`, `name`, and `builder` params
3. run `flutter build apk --obfuscate --split-debug-info=build/app/outputs/split-debug-info`

### Expected results

App should be working fine as it does in development, all named routes should be linked to its configured paths

### Actual results

named routes overwrite each other; since I use `--obfuscate` when generating the apk, and use the `(Screen).toString()` as route name. Code obfuscation alters the class names, making 2 routes have the same name but in different case.
I checked the following:
`(Login).toString() = uwb`
`(Register).toString() = Uwb`

`RouteConfiguration.namedLocation()` includes this logic:
```
...
final String keyName = name.toLowerCase();
assert(_nameToPath.containsKey(keyName), 'unknown route name: $name');
...
```

`RouteConfiguration._cacheNameToPath()` includes this logic:
```
if (route.name != null) {
  final String name = route.name!.toLowerCase();
  assert(
      !_nameToPath.containsKey(name),
      'duplication fullpaths for name '
      '"$name":${_nameToPath[name]}, $fullPath');
  _nameToPath[name] = fullPath;
}
```

This makes the router navigate to `Login` screen whether I use `context.goNamed((Login).toString())` or `context.goNamed((Register).toString())`

I could change the way I am naming my routes, but the way I do it makes it easier for development; so if I refactor the screen name, it will be changed in all places, also it doesn't require me to remember every name for every route, or force me to add an extra name to screen mapper.

I couldn't find any use case for using `name.toLoweCase()` neither in the docs nor in the package code, I think removing `toLowerCase()` in these 2 places will fix the issue and will not affect the logic anyhow.

### Code sample

```dart
final router = GoRouter(
  routes: [
    GoRoute(
      path: '/login',
      name: (Login).toString(),
      builder: (_, __) => Login(),
    ),
    GoRoute(
      path: '/register',
      name: (Register).toString(),
      builder: (_, __) => Register(),
    ),
    ...
  ],
);
```

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

```console
[✓] Flutter (Channel stable, 3.3.3, on macOS 13.3.1 22E261 darwin-arm, locale en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by darshankawar** [comment]
Thanks for the report @Khalidm98 
Can you provide us complete minimal reproducible code sample (ex: main.dart) that we can directly copy paste and run to verify the reported behavior ?
Also, please try the same scenario on latest stable or master version with package's latest version to check if the behavior persists or not.

**Comment by darshankawar** [comment]
Thanks for the update. I wasn't able to replicate the behavior using above code sample, but based on the report, keeping it open and labeling for team's input.

**Comment by maRci002** [comment]
Relying on [`Type`](https://api.flutter.dev/flutter/dart-core/Type-class.html)'s `toString` is not recommended.

https://docs.flutter.dev/deployment/obfuscate#caveat

> **Caveat**
> Be aware of the following when coding an app that will eventually be an obfuscated binary.
> 
> Code that relies on matching specific class, function, or library names will fail. For example, the following call to `expect()` won’t work in an obfuscated binary:
> ```dart
> expect(foo.runtimeType.toString(), equals('Foo'));
> ```

I think you should add `name` static property to your routes:

```dart
class ResetPassword extends StatelessWidget {
  const ResetPassword({super.key});

 static const name = 'ResetPassword';

 // ...
```

Then using it:

```dart
    GoRoute(
      path: '/password/reset',
      name: ResetPassword.name,
      builder: (_, __) => const ResetPassword(),
    ),
```

**Comment by Khalidm98** [comment]
I used to follow your approach in the beginning, but I don't like the idea of storing unnecessary static variables;
- they take memory space as long as the app is not terminated.
- they add development time and require maintenance
specially if the variable can be calculated from somewhere, like calling `toString()`.

I know the memory occupied by 100 screen names with average 16 letters per name is not that much (200 bytes), I am just trying to make the development as much straight forward as I can.

Thanks ✌️

**Comment by maRci002** [comment]
The only thing you can use while fix is done:
```dart
(ResetPassword).hashCode.toString();
```

**Comment by Khalidm98** [comment]
I think this will do for now. Thanks for the suggestion.
Sorry for the late reply. I have been busy for the last couple of days.  ✌️

**Comment by Khalidm98** [comment]
I think we can close this issue now; since [#4196](https://github.com/flutter/packages/pull/4196) is merged.
