### ISSUE TITLE
[Impeller] Add a SwiftShader Vulkan backend to the playground.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#127070]
Today, we require a native Vulkan driver for playgrounds. @gaaclarke ported the Golden tests to use SwiftShader. We should do the same for the playgrounds as well.

**Comment by gaaclarke** [comment]
The run_tests.py can use swiftshader for vulkan now.  It was introduced in 1bed04a4375abfaf238eb4f1eb056386633076eb

You can use the `VK_ICD_FILENAMES` to select swiftshader.

**Comment by jonahwilliams** [comment]
This is completed, correct?

**Comment by chinmaygarde** [comment]
AFAICT, this was done only to the goldens test harness. I am not able to run SwiftShader with the windowed playgrounds. But perhaps it is a matter of documentation?

**Comment by gaaclarke** [comment]
I think it's just a matter of setting the environment variable, `VK_ICD_FILENAMES`.  It doesn't do it by default.

**Comment by chinmaygarde** [comment]
Dang. It JustWorks™! I ensured it wasn't using the GPU. Is there way to seek SwiftShader as a fallback from within the playgrounds instead of having to set the environment variable? In any case, closing as completed.
<img width="1115" alt="Screenshot 2024-02-01 at 2 51 39 PM" src="https://github.com/flutter/flutter/assets/44085/ee026089-6511-4d77-b83d-acd9e81737c3">

**Comment by gaaclarke** [comment]
@chinmaygarde the golden runner hunts down swiftshader and sets it up: https://github.com/flutter/engine/blob/63bcc15738cbc0f4c602e0f4d59333d85c9cc45d/impeller/golden_tests/golden_playground_test_mac.cc#L153

We could at least make it easier by adding our own flag or environment variable that turns on that hunting logic.

**Comment by chinmaygarde** [comment]
Done in https://github.com/flutter/engine/pull/50298
