### ISSUE TITLE
Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) 

### ISSUE THREAD

**Issue by denghejun** [flutter/flutter#127084]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) 

### Expected results

No error

### Actual results

Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) 
Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) 
Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) 
Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) 
Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) 

### Code sample

<details><summary>Code sample</summary>

```dart
NO
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
➜  ~ flutter doctor -v
[✓] Flutter (Channel stable, 3.10.0, on macOS
    12.6.5 21G531 darwin-x64, locale en-CN)
    • Flutter version 3.10.0 on channel stable at
      /Users/me/Code/flutter
    • Upstream repository
      https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (9 days ago),
      2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror
      https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices
    (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/me/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/jav
      a
    • Java version OpenJDK Runtime Environment
      (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at
      /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google
      Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨
      https://plugins.jetbrains.com/plugin/9212-flu
      tter
    • Dart plugin can be installed from:
      🔨
      https://plugins.jetbrains.com/plugin/6351-dar
      t
    • Java version OpenJDK Runtime Environment
      (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Community Edition (version
    2022.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA
      CE.app
    • Flutter plugin version 73.0.2
    • Dart plugin version 222.4345.14

[✓] Connected device (3 available)
    • iPhone (mobile) • 00008101-001814E13A30001E •
      ios            • iOS 16.1.1 20B101
    • macOS (desktop) • macos                     •
      darwin-x64     • macOS 12.6.5 21G531
      darwin-x64
    • Chrome (web)    • chrome                    •
      web-javascript • Google Chrome 113.0.5672.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) 
</details>

**Comment by darshankawar** [comment]
@denghejun 
Please provide us a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the log you are reporting, so that we can make this issue actionable.
