### ISSUE TITLE
DesktopTextSelectionToolbar Doesn't Match Material Design

### ISSUE THREAD

**Issue by anlumo** [flutter/flutter#127044]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Vaguely related to #74255.

Apparently `DesktopTextSelectionToolbar` (or `AdaptiveTextSelectionToolbar`) is the class to go to for a generic context menu for non-text elements on desktop platforms, despite the name. However, it does not match the [Material Design Guidelines](https://m3.material.io/components/menus/overview) concerning menus. The spacing and text size is wrong and there are no separators.

Also, the menu doesn't close when the user clicks outside.

### Proposal

It's possible to show the right context menu using the `showMenu` function of the material library. However, calculating the right position of the menu is quite convoluted:

```dart
InkWell(
  onSecondaryTapUp: (details) {
    final overlayBox = Overlay.of(context).context.findRenderObject()!;
    final localPosition = (overlayBox as RenderBox).globalToLocal(details.globalPosition);
    showMenu(
      context: context,
      position: RelativeRect.fromLTRB(
        localPosition.dx,
        localPosition.dy,
        localPosition.dx,
        localPosition.dy,
      ),
      items: [
        const PopupMenuItem<dynamic>(child: Text('Cut')),
        const PopupMenuItem<dynamic>(child: Text('Copy')),
        const PopupMenuItem<dynamic>(child: Text('Paste')),
        const PopupMenuItem<dynamic>(child: Text('Delete')),
      ],
    );
  },
  child: child, // whatever needs to have a context menu
)
```

Also, this doesn't allow right-dragging selection (right mouse down, move cursor to the desired context menu item, right mouse up to activate).

Additionally, this code doesn't translate to mobile. I would have to do a completely different implementation there.

It would be nice to have a canonical implementation for context menus on generic elements.

**Comment by huycozy** [comment]
Hi @anlumo 

>However, it does not match the [Material Design Guidelines](https://m3.material.io/components/menus/overview) concerning menus.

Can you please be more specific on this? It would be appreciated if there is a sample code of `DesktopTextSelectionToolbar` to present the issue.

>Also, this doesn't allow right-dragging selection (right mouse down, move cursor to the desired context menu item, right mouse up to activate).

I notice this behavior doesn't exist on other apps native on macOS. The context menu will be shown on click down, not click up. Can you share the application that has the behavior you're describing?

>Additionally, this code doesn't translate to mobile. I would have to do a completely different implementation there.
It would be nice to have a canonical implementation for context menus on generic elements.

I think this could be another proposal.

**Comment by anlumo** [comment]
> Can you please be more specific on this?

Certainly! Here's my demo app:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'SearchBar Bug',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const Scaffold(
        body: Row(
          children: [
            Expanded(
              child: ColoredBox(color: Colors.lightGreen, child: MainSection()),
            ),
            Expanded(
              child: ColoredBox(color: Colors.lightBlue, child: MainSectionWithToolbar()),
            ),
          ],
        ),
      ),
    );
  }
}

class MainSection extends StatelessWidget {
  const MainSection({
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    return Center(
        child: InkWell(
            onSecondaryTapDown: (details) {
              final overlayBox = Overlay.of(context).context.findRenderObject()!;
              final localPosition = (overlayBox as RenderBox).globalToLocal(details.globalPosition);
              showMenu(
                context: context,
                position: RelativeRect.fromLTRB(
                  localPosition.dx,
                  localPosition.dy,
                  localPosition.dx,
                  localPosition.dy,
                ),
                items: [
                  const PopupMenuItem<dynamic>(child: Text('Item 1')),
                  const PopupMenuItem<dynamic>(child: Text('Item 2')),
                  const PopupMenuItem<dynamic>(child: Text('Item 3')),
                  const PopupMenuItem<dynamic>(child: Text('Item 4')),
                ],
              );
            },
            child: const Text('Proper Context Menu')));
  }
}

class MainSectionWithToolbar extends StatelessWidget {
  const MainSectionWithToolbar({
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    return Center(
        child: InkWell(
            onSecondaryTapDown: (details) {
              ContextMenuController().show(
                  context: context,
                  contextMenuBuilder: (context) {
                    return AdaptiveTextSelectionToolbar.buttonItems(buttonItems: [
                      ContextMenuButtonItem(label: 'Item 1', onPressed: () {}),
                      ContextMenuButtonItem(label: 'Item 2', onPressed: () {}),
                      ContextMenuButtonItem(label: 'Item 3', onPressed: () {}),
                      ContextMenuButtonItem(label: 'Item 4', onPressed: () {}),
                    ], anchors: TextSelectionToolbarAnchors(primaryAnchor: details.globalPosition));
                  });
            },
            child: const Text('Text Selection Toolbar')));
  }
}
```

[Here's the anchor link to the specific Material Design layout I'm referring to](https://m3.material.io/components/menus/specs#cd6409d5-9523-4099-9db7-42d1e1d2d194).

Run this on the desktop target (I'm using Windows, but it should be the same on Linux and macOS). Right-click on both texts and note the differences. Also note how it's impossible to close the `AdaptiveTextSelectionToolbar`.

> The context menu will be shown on click down, not click up.

Yes, my demo above also does that. Note that this does not fix the issue that you can't select anything from the context menu without releasing the button first. This is why as a workaround I've moved to using tapup, so it's not that confusing to the user.

**Comment by anlumo** [comment]
![image](https://github.com/flutter/flutter/assets/644763/b40a97b2-b078-4b95-9b90-ad31a07bc61e)

**Comment by huycozy** [comment]
Thank you for providing more information. Labeling the issue for further insights!

Related umbrella issue: https://github.com/flutter/flutter/issues/74255

**Comment by justinmc** [comment]
DesktopTextSelectionToolbar was intended first and foremost for right clicking in text fields on Windows and Linux.  I don't think there's a Material spec for that, but it makes sense that it looks more like the right click menus on Linux and Windows than `showMenu` does.  That said I'm definitely up for changing it since we have no strict guideline for its current look.

For the ability to close the menu, see the example in the [ContextMenuController docs](https://master-api.flutter.dev/flutter/widgets/ContextMenuController-class.html).  Maybe we should add _ContextMenuRegion to the framework so it's easier to do this?
