### ISSUE TITLE
Link does not work

### ISSUE THREAD

**Issue by UserY1** [flutter/flutter#127072]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

// Link does not work in this example.
// https://pub.dev/packages/url_launcher/example

Link(
  uri: Uri.parse(
      'https://pub.dev/documentation/url_launcher/latest/link/link-library.html'),
  target: LinkTarget.blank,
  builder: (BuildContext ctx, FollowLink? openLink) {
    return TextButton.icon(
      onPressed: openLink,
      label: const Text('Link Widget documentation'),
      icon: const Icon(Icons.read_more),
    );
  },
),

### Expected results

Page should open.

### Actual results

Page does not open (error "Could not launch link...").

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:url_launcher/link.dart';
//import 'package:url_launcher/url_launcher.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'URL Launcher',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'URL Launcher'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: ListView(
        children: <Widget>[
          Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Link(
                uri: Uri.parse(
                    'https://pub.dev/documentation/url_launcher/latest/link/link-library.html'),
                target: LinkTarget.blank,
                builder: (BuildContext ctx, FollowLink? openLink) {
                  return TextButton.icon(
                    onPressed: openLink,
                    label: const Text('Link Widget documentation'),
                    icon: const Icon(Icons.read_more),
                  );
                },
              ),
            ],
          ),
        ],
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel master, 3.11.0-6.0.pre.134, on Microsoft Windows [Version 10.0.19044.1526], locale ru-RU)
    • Flutter version 3.11.0-6.0.pre.134 on channel master at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f31dae2a80 (20 minutes ago), 2023-05-17 17:18:51 -0700
    • Engine revision d970370779
    • Dart version 3.1.0 (build 3.1.0-118.0.dev)
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\Yura\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Enterprise 2022 17.1.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Enterprise
    • Visual Studio Enterprise 2022 version 17.1.32421.90
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.2)

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by SudipZluck** [comment]
All are working fine, try to flutter clean or create one new fresh project then install package and try again it should work,
Version 3.10.1

**Comment by huycozy** [comment]
@UserY1 Perhaps you are missing this on `AndroidManifest.xml`:

```xml
    <queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="https" />
        </intent>
    </queries>
```

Let's try adding it to see if it can work.

**Comment by UserY1** [comment]
> @UserY1 Perhaps you are missing this on `AndroidManifest.xml`:
> 
> ```
>     <queries>
>         <intent>
>             <action android:name="android.intent.action.VIEW" />
>             <data android:scheme="https" />
>         </intent>
>     </queries>
> ```
> 
> Let's try adding it to see if it can work.

Thanks, it worked.

On iOS (16.2), everything works without adding an LSApplicationQueriesSchemes entry to Info.plist. She probably needs only for sms and tel.

**Comment by huycozy** [comment]
Glad it works for you. Closing the issue as solved.
