### ISSUE TITLE
☂️ Make `useMaterial3: true` by default

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#127064]
Making [Material 3](https://m3.material.io/) the default is the last big step in our long (long) transition from [Material 2](https://m2.material.io/) to [Material 3](https://github.com/flutter/flutter/issues/91605).  Currently apps must opt-in to Material 3 with the [`useMaterial3`](https://api.flutter.dev/flutter/material/ThemeData/useMaterial3.html) flag that appears in all of the [ThemeData factory constructors](https://api.flutter.dev/flutter/material/ThemeData-class.html).

```dart
  return MaterialApp(
    theme: ThemeData(useMaterial3: true),
    // ...
  );
```

Once this issue has been resolved, `useMaterial3: true` will be the default. It will still be possible to configure applications for  Material 2 by specifying `useMaterial3: false`.

Once this change has landed in a stable release, the `useMaterial3` flag will be deprecated and eventually removed per Flutter's [deprecation policy](https://docs.flutter.dev/resources/compatibility#deprecation-policy).

https://github.com/flutter/flutter/pull/129724 Exists to ensure that the the Flutter repo doesn't regress. There's  a similar CL for Google internal tests: cl/543770414.

## Step 1 - All tests pass when `useMaterial3` is true by default
Tests that do not pass when useMaterial is temporarily set to true by default in theme_data.dart (roughly line flutter/flutter#442) will either be split into a pair of tests, one that specifies M3 and one that specifies M2, or a single provisional test that specifies M2. For the latter, the test should be added to Step 3 below.

- [x] flutter/flutter#129683
- [x] flutter/flutter#128914
- [x] flutter/flutter#128839
- [x] flutter/flutter#128300
- [x]  flutter/flutter#128712
- [x] flutter/flutter#128725
- [x] flutter/flutter#128747
- [x] flutter/flutter#128628 
- [x] flutter/flutter#128543 
- [x] flutter/flutter#128521 
- [x] flutter/flutter#128155 
- [x] flutter/flutter#128088 
- [x] flutter/flutter#128080
- [x] flutter/flutter#128071 
- [x] flutter/flutter#128065 
- [x] flutter/flutter#128058
- [x] flutter/flutter#128300
- [x] flutter/flutter#129570
- [x] https://github.com/flutter/cocoon/pull/2837
- [x] https://github.com/fzyzcjy/flutter_portal/pull/103
- [x] https://github.com/superlistapp/super_editor/pull/1173
- [x] https://github.com/flutter/cocoon/pull/2846
- [x] https://github.com/flutter/packages/pull/4316

## Step 2 - ThemeData `useMaterial3` is true by default

- [x] https://github.com/flutter/flutter/pull/129724
- [x] https://github.com/flutter/flutter/pull/130764

## Step 3 - Add M2 and M3-specific tests
-- The remaining work for Step 3 has been moved to https://github.com/flutter/flutter/issues/139076 -- 

Tests that were modified with `useMaterial3: false` will likely need an M3 version. Examples that were modified with `useMaterial3: false` should be updated (along with their tests) to M3.

A list of all the test files that are likely to need to be updated can be found in the [M2-M3 Updates TODO spreadsheet](https://docs.google.com/spreadsheets/d/1TEmxXloSu0cHNQuBn6xjH895-lnSOqH3pln6JVACorc/edit?usp=sharing).

**Comment by mit-mit** [comment]
@HansMuller can this be closed?

**Comment by HansMuller** [comment]
Although nearly all of the work has been completed, this issue is still open because there are holes in the test coverage. See "Step 3 ..." in the issue's description above.

**Comment by FMorschel** [comment]
Has this been done? I see that all 25 issues are complete

**Comment by HansMuller** [comment]
@FMorschel - good question. It essentially _has_ been done however we're still updating some tests per "Step 3" in the description.

**Comment by FMorschel** [comment]
I see! Thank you for answering!

**Comment by parlough** [comment]
@HansMuller Would someone be able to create a doc to add to https://docs.flutter.dev/release/breaking-changes for this change?

**Comment by rydmike** [comment]
@HansMuller, as this landed in 3.16, why is it still open?

**Comment by HansMuller** [comment]
I will close it as soon as we've created a separate issue for the tests that remain to be written per [M2-M3 Updates TODO spreadsheet](https://docs.google.com/spreadsheets/d/1TEmxXloSu0cHNQuBn6xjH895-lnSOqH3pln6JVACorc/edit?usp=sharing). Should be very soon.

**Comment by HansMuller** [comment]
The remaining test updating work has been moved to https://github.com/flutter/flutter/issues/139076
