### ISSUE TITLE
"stless" template shortcut doesn't use super parameters

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#127037]
If you open VSCode or IntelliJ and type `stless` followed by the tab key, it generates a StatelessWidget template:

```dart
class Foo extends StatelessWidget {
  const Foo({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const Placeholder();
  }
}
```

This violates the [use_super_parameters](https://dart-lang.github.io/linter/lints/use_super_parameters.html) lint rule, so the user has to apply the quick fix to make the analyzer warning go away:

```dart
class Foo extends StatelessWidget {
  const Foo({super.key});

  @override
  Widget build(BuildContext context) {
    return const Placeholder();
  }
}
```

**Comment by timsneath** [comment]
These two code snippets are the same?

**Comment by timsneath** [comment]
It looks like the snippet is SDK version dependent? Here's what I got when I used the snippet on a brand new project:

```
class MyWidget extends StatelessWidget {
  const MyWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return const Placeholder();
  }
}
```

But when I run it on a project with the min SDK version set to 2.12.0, I get this:

```dart
class MyWidget extends StatelessWidget {
  const MyWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const Placeholder();
  }
}
```

Neat!

**Comment by johnpryan** [comment]
Ah, very nice. Seems like VSCode is doing the right thing then.
