### ISSUE TITLE
Unable to Run New Project

### ISSUE THREAD

**Issue by adepauldami** [flutter/flutter#127029]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Error occcured executing new flutter project, but old ones that were created before now executes.

### Actual results

Android Execution Error

```Exception in thread "main" java.lang.RuntimeException: Could not determine wrapper version.
	at org.gradle.wrapper.GradleWrapperMain.wrapperVersion(GradleWrapperMain.java:111)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.lang.RuntimeException: No build receipt resource found.
	at org.gradle.wrapper.GradleWrapperMain.wrapperVersion(GradleWrapperMain.java:97)
	... 1 more
Exception: Gradle task assembleDebug failed with exit code 1```

![Screenshot at 2023-05-17 15-39-01](https://github.com/flutter/flutter/assets/70479594/02005497-10f2-419f-8954-c82dfb989589)
![Screenshot at 2023-05-17 15-40-04](https://github.com/flutter/flutter/assets/70479594/5ad86ec0-1a85-4b3a-b858-dcf74a43102c)

Linux Execution Error
ninja: error: unknown target 'install'
Exception: Build process failed

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by SudipZluck** [comment]
@adepauldami Turn on the internet on your system, when it assembles gradle to build apk, will solve your issue maybe.

**Comment by darshankawar** [comment]
@adepauldami 
It seems the main error is:

```
Linux Execution Error
ninja: error: unknown target 'install'
Exception: Build process failed
```

The ninja program is unable to find the target. `Ninja` isn't part of Flutter but maybe snaps installs it. Are you using snap to install Flutter on Linux ?

Can you also provide `flutter doctor -v` and complete verbose log of the error ?
