### ISSUE TITLE
Trying to run Legacy Code But not working

### ISSUE THREAD

**Issue by architsangal** [flutter/flutter#127194]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Install a previous version of flutter by downloading a old version like [2.10.5](https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_2.10.5-stable.tar.xz)
2. run flutter doctor
3. run flutter run 

### Actual results

Launching lib/main.dart on Chrome in debug mode...
../local/flutter/.pub-cache/hosted/pub.dartlang.org/another_flushbar-1.12.30/lib/flushbar.dart:350:31: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../local/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.
    SchedulerBinding.instance.addPostFrameCallback(
                              ^^^^^^^^^^^^^^^^^^^^
Waiting for connection from debug service on Chrome...             25.2s
Failed to compile application.

### Logs

Long message but ended with:

[        ]     |       "name": "vector_math",
[        ]     |       "rootUri": "file:///home/archit/local/flutter/.pub-cache/hosted/pub.dartlang.org/vector_math-2.1.1",
[        ]     |       "packageUri": "lib/",
[        ]     |       "languageVersion": "2.14"
[        ]     |     },
[        ]     |     {
[        ]     |       "name": "foo",
[        ]     |       "rootUri": "../",
[        ]     |       "packageUri": "lib/",
[   +1 ms]     |       "languageVersion": "2.16"
[        ]     |     }
[        ]     |   ],
[        ]     |   "generated": "2023-05-19T13:45:22.268951Z",
[        ]     |   "generator": "pub",
[        ]     |   "generatorVersion": "2.16.2"
[        ]     | }
[   +1 ms] MSG : Changed 25 dependencies!
[  +43 ms] Running "flutter pub get" in foo... (completed in 3.5s)
[ +125 ms] Generating /home/archit/foo/foo/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[   +5 ms] Wrote 96 files.
[        ] 
           All done!
[   +1 ms] In order to run your application, type:
           
             $ cd foo
             $ flutter run
           
           Your application code is in foo/lib/main.dart.
           
[   +1 ms] "flutter create" took 3,995ms.
[ +256 ms] ensureAnalyticsSent: 253ms
[   +3 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +6 ms] exiting with code 0

### Flutter Doctor output

[✓] Flutter (Channel stable, 2.10.5, on Ubuntu 22.04.2 LTS 5.19.0-41-generic, locale en_IN)
    • Flutter version 2.10.5 at /home/archit/local/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (1 year, 1 month ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /home/archit/Android/Sdk
    • Platform android-33-ext5, build-tools 33.0.2
    • Java binary at: /snap/android-studio/125/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /snap/android-studio/125/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.64.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 113.0.5672.126

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by architsangal** [comment]
I used github actions too giving similar results: https://github.com/architsangal/Portfolio/actions/runs/5024837491/jobs/9011019006

**Comment by huycozy** [comment]
Hi @architsangal 
The fix is suggested clearly in the error message:

>Try calling using ?. instead.

For eg:

```dart
SchedulerBinding.instance?.addPostFrameCallback
```

Moreover, since the error comes from 3rd party package (another_flushbar), you should report issue there. I also see an existing issue related to this (https://github.com/cmdrootaccess/another-flushbar/issues/81).

And please also check [Migrating to null safety](https://dart.dev/null-safety/migration-guide) for more information. 

Closing since the error is showing as expected. Your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any.
