### ISSUE TITLE
Firestore Plugin - "Reply already submitted"

### ISSUE THREAD

**Issue by pauldemarco** [flutter/flutter#12714]
The Firestore plugin will sometimes throw:
```
E/FlutterView(32087): Uncaught exception in binary message listener
E/FlutterView(32087): java.lang.IllegalStateException: Reply already submitted
E/FlutterView(32087):   at io.flutter.view.FlutterView$3.reply(FlutterView.java:719)
E/FlutterView(32087):   at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:209)
E/FlutterView(32087):   at io.flutter.view.FlutterView.handlePlatformMessage(FlutterView.java:709)
E/FlutterView(32087):   at android.os.MessageQueue.nativePollOnce(Native Method)
E/FlutterView(32087):   at android.os.MessageQueue.next(MessageQueue.java:323)
E/FlutterView(32087):   at android.os.Looper.loop(Looper.java:136)
E/FlutterView(32087):   at android.app.ActivityThread.main(ActivityThread.java:6682)
E/FlutterView(32087):   at java.lang.reflect.Method.invoke(Native Method)
E/FlutterView(32087):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
E/FlutterView(32087):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

This manifests itself platform-side when the `handle` argument throws a NPE, [see comment here](https://github.com/flutter/plugins/blob/1c38afea94bf14465c550e9e3938e7659db1b049/packages/firebase_firestore/android/src/main/java/io/flutter/plugins/firebase/firestore/FirestorePlugin.java#L155)

I assume from the code comment that this has been experienced, if not, I can throw together an MWE if needed.

**Comment by sethladd** [comment]
Thanks for the report!

cc @kroikie

**Comment by Skylled** [comment]
I can consistently reproduce this by subscribing to a `DocumentReference`'s snapshots.

**Comment by kroikie** [comment]
@pauldemarco

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/951. Any further collaboration will be done there.
