### ISSUE TITLE
preferredCameraDevice: CameraDevice.front does not work

### ISSUE THREAD

**Issue by AriJang** [flutter/flutter#127155]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I am using image_picker for get video file from recording.

This is my pubspec.yaml setting for image_picker
image_picker: ^0.8.6

This is my code for pick video file.
ImagePicker().pickVideo(
  source: ImageSource.camera,
  preferredCameraDevice: CameraDevice.front,
);

I want to use front camera for recording but this filed (preferredCameraDevice: CameraDevice.front) does not work in Android devices. 
It works in iOS devices. 

Can you answer for this ?
I have tried to find some answer but I can not find proper answers even if there are some similar issues.

### Expected results

To launch camera mode with front camera

### Actual results

always launched camera mode with rear camera in Android devices.
(iOS devices have no problem)

### Code sample

ImagePicker().pickVideo(
  source: ImageSource.camera,
  **preferredCameraDevice: CameraDevice.front,**
);

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```
 % flutter doctor -v
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.3.1 22E772610a darwin-arm64, locale ko-KR)
    • Flutter version 3.10.0 on channel stable at /Users/jang-kiseong/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (9 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/jang-kiseong/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • SM G998N (mobile) • R3CR10PTFKN • android-arm64  • Android 13 (API 33)
    • macOS (desktop)   • macos       • darwin-arm64   • macOS 13.3.1 22E772610a darwin-arm64
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 113.0.5672.126
    ! Error: iPhone has recently restarted. Xcode will continue when iPhone is unlocked. (code -14)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

</details>

**Comment by danagbemava-nc** [comment]
Hi @AriJang, this is working as documented in the plugin. See 

https://github.com/flutter/packages/blob/1e214d716ed4bbaa7179d62f43b6acfb04a89799/packages/image_picker/image_picker/lib/image_picker.dart#L47-L51

This is a limitation of the android platform and not the image picker. 

Closing this as working as documented. 

Thank you
