### ISSUE TITLE
Move Fuchsia content handler out of flutter/engine repository

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#12710]
Writing down one of the asks from @abarth into an issue.

This mostly involves moving the Fuchsia content handler to use @chinmaygarde's new embedder API.  This will also certainly require extending the embedder API to support the necessary cases.

One tricky one which was pointed out to me is that currently SceneBuilder knows about Fuchsia childViews, and presumably that should be factored out such that that code can live in the Fuchsia side of the embedding?

**Comment by chinmaygarde** [comment]
A meta-issue tracking all the embedder specific features that need to be implemented [is filed here](https://github.com/flutter/flutter/issues/12717).

**Comment by chinmaygarde** [comment]
This is done.
