### ISSUE TITLE
1 cannot be a double

### ISSUE THREAD

**Issue by ozayr** [flutter/flutter#127190]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

function requires a record (double? x , double? y)
when the result of a calculation eg k/z = 1 should ideally be 1.0 (variable seems to be getting demoted)
the functions throws with expected (double? , double?) but got one of type (int,int)

### Expected results

there should be no error, I have tried explicitly casting the value as below

x = 1
x.toDouble()
x as double
x + .0

nothing works

### Actual results

function throws 

### Code sample

i have this riverpod provider
```
final imagePrevScaleProvider = StateProvider<
    (
      double? prevScaleX,
      double? prevScaleY,
    )>((ref) {
  return (null, null);
});
```
i am calculating a scaling factor

```
final scaleXFromOriginal = dimensions.newWidth! / image.width;
final scaleYFromOriginal = dimensions.newHeight! / image.height;
```

when i set the provider

```
 ref.read(imagePrevScaleProvider.notifier).update((state) => (
          scaleXFromOriginal,
          scaleYFromOriginal,
        ));
```
throws, never used to have issue before 

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.1, on Microsoft Windows [Version 10.0.22621.1702], locale en-ZA)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.3)
[√] Android Studio (version 2022.1)
[√] VS Code (version 1.78.2)
[√] Connected device (3 available)
[√] Network resources

• No issues found!

**Comment by huycozy** [comment]
Hi @ozayr 
It seems your question is best suited for dart-lang sdk. Please open the issue in the dedicated [repository](https://github.com/dart-lang/sdk/issues) with minimal sample code without 3rd party package/plugin (riverpod/provider) for better support.

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it. Thank you!
