### ISSUE TITLE
Support running multiple FlutterViews on separate threads in a single process

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#12711]
A request from @abarth:

Currently, Fuchsia runs multiple Flutter apps inside the same process (multi-tenanting), but because of restrictions from the Blink code, all these apps apps share a thread.  We'd like to (at least) run the Dart code for these apps on separate threads.  My guess is that this problem should be quite tractable after you complete the libtxt migration (given that Minikin was already thread-safe).

@jason-simmons 

@abarth can provide more details as to the exact needs.

**Comment by chinmaygarde** [comment]
A meta-issue tracking all the embedder specific features that need to be implemented [is filed here](https://github.com/flutter/flutter/issues/12717).

**Comment by chinmaygarde** [comment]
Update: Still waiting on the Fuchsia roll. Currently my top priority.

**Comment by chinmaygarde** [comment]
This is done.
