### ISSUE TITLE
[CP] Fix issue about saveLayer ignoring opacity of paint with advanced blend mode

### ISSUE THREAD

**Issue by ColdPaleLight** [flutter/flutter#127100]
### issue_link

https://github.com/flutter/flutter/issues/126532

### Commit Hash

d06b4aba6e0453386e7f4325241ced81c0f2bce9

### Target

stable

### pr_link

https://github.com/flutter/engine/pull/42126

### Impacted Users

Impeller users.

### Impact Description

Without this patch, if both opacity and Advanced blend are set during SaveLayer, then opacity will be ignored

### Workaround

No workarounds.

### Risk

low

### Test Coverage

yes

### Validation Steps

* Run the new test in https://github.com/flutter/engine/pull/41972
* Run the reproduction app in https://github.com/flutter/flutter/issues/126532.

**Comment by zanderso** [comment]
CP lgtm
