### ISSUE TITLE
A problem occurred configuring root project 'android'.

### ISSUE THREAD

**Issue by arrullin** [flutter/flutter#127164]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

When I run my Flutter Application it logs this in my debug console
> `A problem occurred configuring root project 'android'.`
> `java.util.concurrent.ExecutionException: org.gradle.api.GradleException: Failed to create Jar file C:\Users\santo\.gradle\caches\jars-9\77f1b6119df996df354847f2f9be857a\gradle-7.1.2.jar.`

### Expected results

It should run without any errors

### Actual results

I'm getting error

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by santosharron** [comment]
This could happen because there is no storage left on your device to run the script files.
I would recommend you to Open the task manger and force stop Java(TM) Platform SE binary and delete
> `C:\Users\{current user}\.gradle\caches\jars-9\jars-9.lock file`

And Clear the Cache Files on your gradle folder
