### ISSUE TITLE
Proposal to add option to Disable [NavigationRailDestination]s

### ISSUE THREAD

**Issue by matheus-kirchesch-btor** [flutter/flutter#127108]
### Is there an existing issue for this?

- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)
- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)

### Use case

Any kind of routing that is permission based.

### Proposal

* Add optional member in the [NavigationRailDestination] on file [NavigationRailDestinations] class do mark it disabled.
* On the file [navigation_rail.dart] at the class [_RailDestination] add a nullable mark to the VoidCallback onTap member.
* On the file [navigation_rail.dart] at the class [_NavigationRailState] you add [widget.destinations[i].disabled? null :] before the callback that is there right now.

The reason I don't do that myself on a PR is that I don't know the rules. And also I am not sure the best practices when disabling a widget, Flutter conventions etc..., so I guess applying an opacity to help indicate it is disabled.

Thanks.

**Comment by darshankawar** [comment]
Thanks for the report @matheus-kirchesch-btor 
Can you please elaborate on the use case a bit so as to clearly understand the purpose behind this feature request ?

**Comment by matheus-kirchesch-btor** [comment]
Ofc, I have an open pr with the solution [https://github.com/flutter/flutter/pull/127113].

As you can see in the bellow picture, the user does not have access to this third destination that I just made up right now to exemplify:
![image](https://github.com/flutter/flutter/assets/68293882/155c52bf-c3f9-40c9-a197-4507b03df18f)

So, what this does is allow the NavigationRail (which is a very good and modern looking sort of drawer for desktops) to be used for role based access control, currently I am verifying if the current user has a specific feature that decides if the destination is accessible.

I had a two of options
1 - Remove the destination (this is a weird solution because if you have only 1 the NavRail has an assert that fails)
2 - Gray it out and make it unclickable so that the user is not clicking a button that does nothing

I could have just removed the assert, but I saw that there are PR's open for that and they are not moving, and I also think the destinations should appear for everybody.
