### ISSUE TITLE
[flutter 3.10.1][iOS] platform-view on simulator crashes

### ISSUE THREAD

**Issue by kevin-lemon** [flutter/flutter#127158]
flutter doctor -v     
[✓] Flutter (Channel stable, 3.10.1, on macOS 13.3.1 22E261 darwin-arm64, locale
    zh-Hans-CN)
    • Flutter version 3.10.1 on channel stable at /Users/lemon/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (2 days ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/lemon/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • 1A16F378-D536-4653-BBD7-AE117390E2E6 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)        • macos                                •
      darwin-arm64   • macOS 13.3.1 22E261 darwin-arm64
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 113.0.5672.126

[!] Network resources                   
    ✗ A network error occurred while checking "https://maven.google.com/":
      Operation timed out

crash logs：
[long_text_2023-05-18-15-15-48.txt](https://github.com/flutter/flutter/files/11514956/long_text_2023-05-18-15-15-48.txt)
[long_text_2023-05-18-15-29-08.txt](https://github.com/flutter/flutter/files/11514958/long_text_2023-05-18-15-29-08.txt)

**Comment by danagbemava-nc** [comment]
Hi @kevin-lemon, please provide a complete minimal reproducible code sample along with steps to reproduce. 

Please also share the plugins you're experiencing the issue with along with the full output of `flutter doctor -v`. In the future, please do not provide screenshots of crash logs but rather provide the logs in a text format instead. Please also provide the full crash logs. 

Thank you

**Comment by kevin-lemon** [comment]
> Hi @kevin-lemon, please provide a complete minimal reproducible code sample along with steps to reproduce.
> 
> Please also share the plugins you're experiencing the issue with along with the full output of `flutter doctor -v`. In the future, please do not provide screenshots of crash logs but rather provide the logs in a text format instead. Please also provide the full crash logs.
> 
> Thank you
i update thanks for help

**Comment by kevin-lemon** [comment]
already update

**Comment by danagbemava-nc** [comment]
Hi @kevin-lemon,

Please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with steps to reproduce so that we can investigate this issue. 

Thank you

**Comment by kevin-lemon** [comment]
> Please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with steps to reproduce so that we can investigate this issue.
> 
> Thank you

i cant provide ，because I use gaode aMap ios plugins  view  is too big ，cant make minimal complete code，have other way can help to fix？

**Comment by danagbemava-nc** [comment]
Hi @kevin-lemon, what plugin are you using? 

Have you tested on a physical device to see if the crash reproduces there as well?

**Comment by danagbemava-nc** [comment]
Hi @kevin-lemon, please update when you're able to. 

Thank you

**Comment by kevin-lemon** [comment]
> Hi @kevin-lemon, please update when you're able to.
> 
> Thank you

it work on physical， thanks for help！

**Comment by kevin-lemon** [comment]
> Hi @kevin-lemon, thanks for the update.
> 
> Please provide a minimal reproducible code sample when you can so that we can investigate the source of the crash and fix it for other users as well. I tried the webview_flutter code sample and it worked just fine so there might be something about your code that we need to look into.
> 
> Thank you

it no problem on physical thanks
