### ISSUE TITLE
Update package:intl to 0.18.1 flutter_localizations throws dependency error 

### ISSUE THREAD

**Issue by securexperts** [flutter/flutter#127170]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Pubspec.yaml

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  permission_handler: ^10.2.0
  http: ^0.13.6

-> Error
Resolving dependencies...
Because for_your_memories depends on flutter_localizations from sdk which depends on intl 0.18.0, intl 0.18.0 is required.
So, because for_your_memories depends on intl ^0.18.1, version solving failed.
Process finished with exit code 1

### Expected results

Flutter_localizations would work in combination with into 0.18.1

### Actual results

Resolving dependencies...
Because for_your_memories depends on flutter_localizations from sdk which depends on intl 0.18.0, intl 0.18.0 is required.
So, because for_your_memories depends on intl ^0.18.1, version solving failed.
Process finished with exit code 1

### Code sample

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  permission_handler: ^10.2.0
  http: ^0.13.6

### Screenshots or Video

none

### Logs

/Users/romanbanz/development/flutter/bin/flutter --no-color pub get
Resolving dependencies...
Because for_your_memories depends on flutter_localizations from sdk which depends on intl 0.18.0, intl 0.18.0 is required.
So, because for_your_memories depends on intl ^0.18.1, version solving failed.
Process finished with exit code 1

### Flutter Doctor output

flutter doctor -v
[✓] Flutter (Channel stable, 3.10.1, on macOS 13.3.1 22E772610a darwin-arm64, locale en-GB)
    • Flutter version 3.10.1 on channel stable at /Users/romanbanz/development/flutter3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (2 days ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/romanbanz/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Users/romanbanz/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/romanbanz/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/romanbanz/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
    • IntelliJ at /Users/romanbanz/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 73.1.1
    • Dart plugin version 231.9065

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
    • IntelliJ at /Users/romanbanz/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9011.34/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.1)
    • IntelliJ at /Users/romanbanz/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.8770.65/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • DADCE2B2-EA77-4CC0-8046-B066FF9704FD • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.3.1 22E772610a darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by ziyadgodil** [comment]
Hi @securexperts ,
Try importing intl: ^ 0.18.0

**Comment by danagbemava-nc** [comment]
Hi @securexperts, this has been fixed on the master channel and should be available sometime in the future. See

https://github.com/flutter/flutter/blob/6456d603c073dc419d1d0a6ffe7eee47cf56fd88/packages/flutter_localizations/pubspec.yaml#L11

For now, your options are

- use intl: ^0.18.0 or 
- force a dependency override in your pubspec.yaml

You can do so by adding the line below to your pubspec.yaml

```
dependency_overrides:
  intl: ^0.18.1
```

Closing as this has already been fixed on the master channel. 

Thank you
