### ISSUE TITLE
How to Use Play Asset Delivery in Flutter Projects with Unity

### ISSUE THREAD

**Issue by hu1won** [flutter/flutter#127161]
My current project is Flutter project including Unity. I created an aab extension file through Flutter Build, but the capacity has exceeded 150MB, so I can't upload it to Google console.

I am referring to Play Asset Delivery because I believe that the Asset part of Unity occupies a lot of capacity. But I know how to do it for an APP that only consists of Unity, but I don't know what to do with my APP that works with Flutter. In my case, please help me with how to solve it. Please..

+ In pub.dev, there is [flutter_play_asset_delivery: ^0.0.2](https://pub.dev/packages/flutter_play_asset_delivery), can I use this? If that's right, please tell me how to use it in detail.

**Comment by darshankawar** [comment]
@hu1won 
Your question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here as this isn't a bug or a feature request.
