### ISSUE TITLE
[pigeon] Add package name to channel names

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#127106]
Currently Pigeon's channel name generation is `'dev.flutter.pigeon.${api.name}.${func.name}'`, which assumes that there will never be two plugins using Pigeon with the same API name and method name, which isn't a safe assumption.

We should add the package name before the API name, since packages must all have unique names within an application already.

**Comment by stuartmorgan** [comment]
The Dart generator already has logic to determine the package name based on the output paths; we can move that logic to generator_tools, and base it on the input path instead. We'll need a fallback command line parameter for the rare case where the input files aren't in the package (there's already a TODO for this).

**Comment by stuartmorgan** [comment]
https://github.com/flutter/flutter/issues/128560 looks like an in-the-wild crash due to this issue.

@tarrinneal You or I should see about getting this into our queue relatively soon.

**Comment by tarrinneal** [comment]
> #128560 looks like an in-the-wild crash due to this issue.
> 
> @tarrinneal You or I should see about getting this into our queue relatively soon.

Will do.

**Comment by stuartmorgan** [comment]
This was fixed in https://github.com/flutter/packages/pull/4443
