### ISSUE TITLE
Concurrent building for multiple devices still not working

### ISSUE THREAD

**Issue by alex9153** [flutter/flutter#127195]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

run commands at the same time 
flutter run -d emulator1
flutter run -d emulator2

### Expected results

the project runs in 2 and more devices

### Actual results

```
Launching lib\main.dart on sdk gphone x86 64 in debug mode...
Target debug_android_application failed: PathExistsException: Cannot copy file to 'D:\Projects\homm3\homm3_app\build\app\intermediates\flutter\debug\flutter_assets\resources/images/units/battle/fortress/gorgon_u/Cbgorg30.png', path = 'D:\Projects\homm3\homm3_app\resources\images\units\battle\fortress\gorgon_u\Cbgorg30.png' (OS Error: Невозможно создать файл, так как он уже существует.
, errno = 183)


FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1201

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 33s
Running Gradle task 'assembleDebug'...                             34,6s
Exception: Gradle task assembleDebug failed with exit code 1
```

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.1, on Microsoft Windows [Version 10.0.22621.1702], locale ru-RU)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.5)
[√] Android Studio (version 2022.1)
[√] VS Code (version 1.78.2)
[√] Connected device (7 available)
[√] Network resources

• No issues found!

**Comment by darshankawar** [comment]
Thanks for the report @alex9153 
There are couple of similar issues open describing your case:

https://github.com/flutter/flutter/issues/118974
https://github.com/flutter/flutter/issues/56973

I suggest you to follow-up in them for further updates and can also share your findings in them for better tracking. Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.
