### ISSUE TITLE
Gradle error when trying to run app

### ISSUE THREAD

**Issue by rmpooria** [flutter/flutter#127176]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

i installed android studio,made flutter project and when i try to run it i get "Exception in thread "main" java.util.zip.ZipException: zip END header not found" error.i tried deleting my .gradle file 3 time,tried deleting android studio and reinstalling it,tried running it on visual studio code and i still get the error

### Actual results

nothing happen after i run my project just bunch of errors appear on screen

### Logs

<details>
<summary>Logs</summary>

```console

Exception in thread "main" java.util.zip.ZipException: zip END header not found
        at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
        at org.gradle.wrapper.Install.unzip(Install.java:214)
        at org.gradle.wrapper.Install.access$600(Install.java:27)
        at org.gradle.wrapper.Install$1.call(Install.java:74)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

 [√] Flutter (Channel stable, 3.10.1, on Microsoft Windows [Version 10.0.22621.1702], locale en-US)
    • Flutter version 3.10.1 on channel stable at C:\Users\rmpooria\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (2 days ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\rmpooria\AppData\Local\Android\sdk
    • Platform android-33-ext5, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code, 64-bit edition (version 1.77.3)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.64.0

[√] Connected device (4 available)
    • M2102J20SG (mobile) • 6654ad73 • android-arm64  • Android 12 (API 31)
    • Windows (desktop)   • windows  • windows-x64    • Microsoft Windows [Version 10.0.22621.1702]
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 113.0.5672.94
    • Edge (web)          • edge     • web-javascript • Microsoft Edge 110.0.1587.63

[√] Network resources
    • All expected network resources are available. 

```

</details>

**Comment by ziyadgodil** [comment]
Hi @rmpooria 
I recently Solved this problem. This Problem came from gradle file is corrupted in my system. I'm using Windows so this steps almost same in Linux also. This answer is for any gradle version.

Open File Manager: enable Show hidden folder from top menu bar.

You may find this location : .gradle>wrapper>dists.

In Linux: Home > .gradle > wrapper > dists.

In Windows: C:>Users>{PC Name}>.gradle>wrapper>dists

**Comment by rmpooria** [comment]
> Hi @rmpooria I recently Solved this problem. This Problem came from gradle file is corrupted in my system. I'm using Windows so this steps almost same in Linux also. This answer is for any gradle version.
> 
> Open File Manager: enable Show hidden folder from top menu bar.
> 
> You may find this location : .gradle>wrapper>dists.
> 
> In Linux: Home > .gradle > wrapper > dists.
> 
> In Windows: C:>Users>{PC Name}>.gradle>wrapper>dists

if you mean deleting gradle.7.5.all yes i tried that and then android studio reinstalled it but i still get same error

**Comment by huycozy** [comment]
Hi @rmpooria 
It seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any. You can check [this answer](https://stackoverflow.com/questions/67901965/flutter-gradle-task-assembledebug-failed-with-exit-code-1-zip-end-header-not-fou) if it's helpful. 

Closing the issue from here as it's not a Flutter framework issue.
