### ISSUE TITLE
Create utility function to pass `ProcessResult` along with anticipated exit code + implement within flakes

### ISSUE THREAD

**Issue by eliasyishak** [flutter/flutter#127135]
This utility function will be used in integration tests to check the result of a process to ensure the exit code expected is returned, if the exit code returned is not what was expected, the function will print out the `stdout`, `stderr`, and `exit_code`

**Comment by eliasyishak** [comment]
fyi @christopherfujino

**Comment by christopherfujino** [comment]
Ooh, if you want to be fancy this can be a matcher. Here's some prior art: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/src/common.dart#LL91C62-L91C62

**Comment by eliasyishak** [comment]
After #127414 landed, implementing in flakes identified below

- Addressing issue https://github.com/flutter/flutter/issues/125115
