### ISSUE TITLE
FocusNode is erroneously marked as skipTraversal during _FocusState.didUpdateWidget

### ISSUE THREAD

**Issue by saintmac-google** [flutter/flutter#127120]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Consider this pseudo code:
```dart
class MyWidget extends StatefulWidget {
  _MyWidgetState createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> {
  var skip = false;
  void onSomeEvent() { setState(() {skip = !skip;}); }
  Widget build(BuildContext context) {
    return Focus(
      descendantsAreTraversable: !skip,
      child: Focus(
        child: someChild,
        ),
    );
  }
}
```
When `onSomeEvent()` gets invoked, the inner focus will see its `skipTraversal` property flipped to true. The reason is `_FocusState.didUpdateWidget` sets the flag according to the "effective" skip traversal status, which is true since the parent has `descendantsAreTraversable` set to false. If we invoke the same function again, the parent node will indicate that the children are traversable, but the inner node now has its property set to skip.

My recommendation is to change the way we update the property in `_FocusState.didUpdateWidget` to:
```dart
if (widget._skipTraversal != null) {
  focusNode.skipTraversal = widget._skipTraversal;
}
```
This is similar to how the `canRequestFocus`property is handled.

### Expected results

the `skipTraversal` of the inner Focus should not be changed

### Actual results

`skipTraversal` is changed to true

### Code sample

<details><summary>Code sample</summary>

```dart
class MyWidget extends StatefulWidget {
  _MyWidgetState createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> {
  var skip = false;
  void onSomeEvent() { setState(() {skip = !skip;}); }
  Widget build(BuildContext context) {
    return Focus(
      descendantsAreTraversable: !skip,
      child: Focus(
        child: someChild,
        ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @saintmac-google 
Can you check if your case is similar to https://github.com/flutter/flutter/issues/113005 ?

**Comment by saintmac-google** [comment]
it is the same issue indeed.

**Comment by darshankawar** [comment]
Thanks for the update. Closing as duplicate. Please follow-up in linked issue for further updates.
