### ISSUE TITLE
ListView Not Scrolling Horizontally inside Row (only working for mobile)

### ISSUE THREAD

**Issue by prashantprojection** [flutter/flutter#127169]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create A Row
2. Inside Create a Container with any child field
3. Next children of Row will be Expanded Widget
4. Inside Expanded Widget Create a ListView Builder or Separated
5. Set its scroll Direction To Horizontally by (Axis.horizontal)
6. With item count that can't fill in screen and generate some random items but for horizontal

### Expected results

On dragging or scrolling mouse wheel the list suppose to move when entries inside are over that can actually fit on screen.

### Actual results

everything working perfectly fine with no crash just the scrolling or dragging it is not working for web and windows development

### Code sample

<details><summary>Code sample</summary>

```dart
Row(
          children: [
            Container(
              width: 100,
              height: 100,
              alignment: Alignment.center,
              child: Text(widget.text, style: const TextStyle(fontSize: 35)),
            ),
            VerticalDivider(
              thickness: 2,
              color: Colors.grey.withOpacity(0.25),
            ),
            Expanded(
              child: SizedBox(
                width: MediaQuery.of(context).size.width,
                child: ListView.separated(
                    scrollDirection: Axis.horizontal,
                    itemCount: widget.imageList.length,
                    itemBuilder: (context, item) => widget.imageList[item],
                    separatorBuilder: (context, index) => const SizedBox(width: 2)),
              ),
            )
          ],
        ),
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
All logs are clear nothing wrong in logs
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.0, on Microsoft Windows [Version 10.0.22621.1325], locale en-IN)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.6.0)
[!] Android Studio (not installed)
[✓] VS Code (version 1.78.2)
[✓] Connected device (2 available)
[✓] Network resources
```

</details>

**Comment by prashantprojection** [comment]
Please make it seamless for every platform

**Comment by ziyadgodil** [comment]
Hi @prashantprojection 
I have checked your code you are using expanded inside row but you have to give height to row otherwise it will threw error pf repaintboundry.
i have modified your code little bit and solve your issue you can try the code mentioned below and edit it as your requirement.

Container(
              height: 100,
              child: Row(
                children: [
                  Container(
                    width: 100,
                    height: 100,
                    alignment: Alignment.center,
                    child: Text("Test", style: const TextStyle(fontSize: 35)),
                  ),
                  VerticalDivider(
                    thickness: 2,
                    color: Colors.grey.withOpacity(0.25),
                  ),
                  Expanded(
                    child: SizedBox(
                      child: ListView.separated(
                          scrollDirection: Axis.horizontal,
                          itemCount: imageList.length,
                          itemBuilder: (context, item) => Container(
                            height: 100,
                            width: 100,
                            color: Colors.blue,
                            child:Text(imageList[item]),
                          ),
                          separatorBuilder: (context, index) => const SizedBox(width: 2)),
                    ),
                  )
                ],
              ),
            ),
            
and here is imagelist 

  var imageList = [
    "first",
    "second",
    "second",
    "second",
    "second",
    "second",
    "second",
    "second",
    "second",
    "second",
    "second",
    "second",
    "second",
    "second",
    "second",
  ];

**Comment by darshankawar** [comment]
@prashantprojection 
Check above comment / solution and see if it works for your case.
