### ISSUE TITLE
textfield with long text very slow in the chrome

### ISSUE THREAD

**Issue by zhushuihua** [flutter/flutter#127187]
### Is there an existing issue for this?

- [x] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Textfield with long text very slow in the chrome, whilst it works ok before flutter 3.10

### Expected results

It is working for the flutter version prior 3.10, but now it is freezing for chrome, however it is not freezing in the safari.
I am seeing the same problem in the 3.10.1 as well.

### Actual results

It is freezing in the chrome...

### Code sample

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  late final TextEditingController _controller =
      TextEditingController(text: 'abcdefghiji' * 20000);
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(38.0),
          child: TextField(
            maxLines: 10,
            controller: _controller,
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }
}

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Hi @zhushuihua 
I can see the issue on the latest stable channel. However, if increasing the text amount to 100.000, the app is frozen and is hanging. That is a known issue being tracked at https://github.com/flutter/flutter/issues/90063.

Closing this issue in favor of #90063, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
