### ISSUE TITLE
AssetBundle built twice during run

### ISSUE THREAD

**Issue by xster** [flutter/flutter#12728]
One instance of the AssetBundle is built in HotRunner for _updateDevFS and another separate instance by the BuildFlxCommand via assemble.  

Seems redundant and takes 500 and 300ms on my powerful machine.

Can we reuse?

**Comment by jonahwilliams** [comment]
The TLDR is no, we can't re-use the asset bundles for _updateDevF anymore because the second is only created from a re-entrant call from xcode/gradle and used to generate the platform specific bundling.
