### ISSUE TITLE
Update MaterialColor API docs to migrate to ColorScheme for Material3 apps

### ISSUE THREAD

**Issue by seriann** [flutter/flutter#127228]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I'm new to Flutter and I'm trying to configure a custom color scheme while respecting Material 3 color conventions. According to the Material 3 documentation, a tonal palette consists of thirteen tones, including white and black. A tone value of 100 represents maximum lightness and results in white. Each tone value between 0 and 100 expresses the amount of light present in the color.

I'm attempting to use the MaterialColor class to implement my custom colors, but it seems to be following the Material 2 convention instead.

I have referred to the Material 3 documentation (https://m3.material.io/styles/color/the-color-system/key-colors-tones#6bdb9471-b70d-42c9-8ace-76743c1fff13) and noticed that the color system and conventions described there differ from what I'm experiencing with the MaterialColor class.

Here are some screenshots illustrating the differences:

Material 3 Color Conventions:
![image](https://github.com/flutter/flutter/assets/69601489/eb449891-1f7a-475b-91e7-9fccc3615072)

MaterialColor class:
![image](https://github.com/flutter/flutter/assets/69601489/61050a47-2ee7-41dc-96d6-0da00672ca6c)
![image](https://github.com/flutter/flutter/assets/69601489/c34c9c72-7039-4d47-b36b-ffdc4874aa69)

Material 2 Color Conventions:
https://m2.material.io/design/color/the-color-system.html#color-usage-and-palettes
![image](https://github.com/flutter/flutter/assets/69601489/a07b9a97-1098-4fb4-9674-c32aae67cecc)

### Proposal

Maybe an update to that class to support new Material 3 colors conventions?

**Comment by leighajarett** [comment]
Hi there! Thanks for filing this. Actually we have a new class specific to Material3 colors called ColorScheme - https://api.flutter.dev/flutter/material/ColorScheme-class.html. I'm adding an example to the MaterialColor API docs to make it clear that for Material 3 design you should use the ColorScheme class.
