### ISSUE TITLE
Error in TextField value when TexFiled is render inside showModalBottomSheet

### ISSUE THREAD

**Issue by klm-lab** [flutter/flutter#127220]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Execute `flutter run` on the code sample
2. Click on plus icon to show the bottom Modal
3. Enter any value in textFiled with label Name
4. Enter any value in textField with label Description
5. Change value of textField with label Name

### Expected results

Every text field should have its own correct value instead of merging values

### Actual results

Value from both input merge themselves

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Learn',
      home: MyHomePage(),
    );
  }
}


class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  void _showModalBottomSheet(BuildContext ctx) {
    showModalBottomSheet(
        context: ctx,
        builder: (_) {
          return Container(
            height: 800,
            child: Column(
              children: [
                TextField(
                  decoration: const InputDecoration(labelText: 'Name'),
                  onChanged: (_) {},
                ),
                TextField(
                  decoration: const InputDecoration(labelText: 'Description'),
                  onChanged: (_) {},
                )
              ],
            ),
          );
        });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Flutter App'),
        actions: [
          IconButton(
              onPressed: () {
                _showModalBottomSheet(context);
              },
              icon: const Icon(Icons.add))
        ],
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          _showModalBottomSheet(context);
        },
        child: const Icon(Icons.add),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/58208740/7ce2e4bf-a762-484d-a569-a9fddf20d72f

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.10.1, on Microsoft Windows [version 10.0.22621.1702], locale fr-FR)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.2)
[√] IntelliJ IDEA Ultimate Edition (version 2023.1)
[√] Connected device (3 available)
[√] Network resources

```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @klm-lab 
I tried your code sample running with latest master version on Pixel emulator but I was unable to replicate the reported behavior.

<img width="311" alt="Screenshot 2023-05-22 at 12 03 57 PM" src="https://github.com/flutter/flutter/assets/67046386/a0cd43b3-d5b9-4518-ac89-877babef7337">

From the video you shared, I see that you have French language enabled as input. I tried with Spanish, but didn't see the behavior.
Can you also try with English and see if you still get same behavior ? Also, what's the keyboard type you are using to input along with emulator details ?

**Comment by klm-lab** [comment]
Thanks @darshankawar for the support.
I try again with an emulator on latest android 13 with English and French input language. No issue at all. Works fine.
But with a real device with Android 10 the bug appears even if i change the input language. 

Thank you

**Comment by darshankawar** [comment]
Thanks for the update @klm-lab 
I will try to verify this on Android 10 device which I don't have currently, but mean time, can you try the same using latest master and see if issue persists or not ?

`flutter channel master`
`flutter upgrade`

**Comment by klm-lab** [comment]
@darshankawar 
Unfortunately, The issue persits

**Comment by darshankawar** [comment]
Thanks for the update. I couldn't get Android 10 device to verify, but tried by creating an emulator with API 29 on which the behavior doesn't seem to replicate.

<img width="259" alt="Screenshot 2023-05-24 at 11 20 14 AM" src="https://github.com/flutter/flutter/assets/67046386/ef24f62c-a11b-40e8-9f60-c3ba465b1821">
<img width="331" alt="Screenshot 2023-05-24 at 11 27 04 AM" src="https://github.com/flutter/flutter/assets/67046386/9c62fe08-7f18-417b-a0f8-0495d639441b">


> But with a real device with Android 10 the bug appears even if i change the input language.

Is there a way for you to confirm if this is only happening on device and not on emulator with api 29 ?
