### ISSUE TITLE
Support underlining spelling errors in Flutter inputs

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#12720]
I believe both iOS and Android support this as an option.  I saw this in a customer: mulligan mock just now.

Here is an example from iOS 11 messages app:
![img_2005](https://user-images.githubusercontent.com/11857803/32019933-8361c480-b983-11e7-818b-a5a90ad3dae5.PNG)

**Comment by justinmc** [comment]
I think this can be closed now that @camsim99's spell check project was completed for both Android and iOS. There are other spell check related issues around for more specific features and bugs.
