### ISSUE TITLE
Flutter upgrade not just working 

### ISSUE THREAD

**Issue by Somtobro** [flutter/flutter#127288]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Flutter upgrade 

### Actual results

Stuck

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by ziyadgodil** [comment]
Hi @Somtobro 
Can you please provide log of error which kind of proplem are you getting ?
because it is hard to solve error without knowing what exactly happening.

**Comment by danagbemava-nc** [comment]
Hi @Somtobro, what version of flutter are you on and which version were you trying to upgrade to? 

At what point in the upgrade process is it stuck?

Please share the logs of the command output as well.

Thank you

**Comment by Somtobro** [comment]
I've fixed it...I stepped through the psh1 script and downloaded some zip files manaully.
It got stuck at Downloading the Dart SDK zip file
