### ISSUE TITLE
☂️ Umbrella issue for Material2 API doc updates

### ISSUE THREAD

**Issue by leighajarett** [flutter/flutter#127216]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

As we prepare to make Material 3 the default, we should make it clear that while Material 2 widgets will continue to exist, some have Material 3 counterparts that may be more useful and better match Material 3 app styles. 

### Proposal

There are a few Material 2 widgets whose API docs need to be updated:
| M2 widget | M3 widget | Tracking issue / PR | 
| --- | ----------- |  ----------- |
| `ToggleButtons` | `SegmentedButtons` | <ul><li>[x] https://github.com/flutter/flutter/pull/127021</li></ul> |
| `BottomNavigationBar` | `NavigationBar` | <ul><li>[x] https://github.com/flutter/flutter/issues/127213</li></ul> |
| `Drawer` | `NavigationDrawer` | <ul><li>[x] https://github.com/flutter/flutter/issues/127214</li></ul> |
| `DropdownButton` | `DropDownMenu` |  <ul><li>[x] https://github.com/flutter/flutter/issues/127215</li></ul> |
| `PopupMenuButton` | `MenuAnchor` |  <ul><li>[x] https://github.com/flutter/flutter/issues/127215</li></ul>|
|`MaterialColor`| `ColorScheme`| <ul><li>[x] https://github.com/flutter/flutter/issues/127228 |
|`ButtonBar` | `OverflowBar ` | <ul><li>[x] https://github.com/flutter/flutter/issues/128430</li></ul> |
|`ActionChip` | Showcase suggest and assist |  <ul><li>[x] https://github.com/flutter/flutter/issues/128028</li></ul> |
|`ThemeData` | List out the properties that should be used for Material3 |  <ul><li>[x] https://github.com/flutter/flutter/issues/130949</li></ul> |

**Comment by guidezpl** [comment]
Great list, thank you.

I would also add `ColorScheme.fromSwatch` ⇒ `ColorScheme.fromSeed` and `ColorScheme.fromImageProvider` 

For posterity, there are also:
- new constructors: `IconButton.filled`, `IconButton.filledTonal`, and `IconButton.outlined`, `TabBar.secondary`, 
- new top-level widgets: `SearchBar` and `SearchAnchor`

But I think these are well enough documented among themselves.

**Comment by HansMuller** [comment]
We should also provide a way to issue runtime advice about M2-M3 migration, see https://github.com/flutter/flutter/issues/130932#issuecomment-1654671674

**Comment by HansMuller** [comment]
@TahaTesser, @Piinks - I think that you-all have resolved the final unchecked issue on this one.

**Comment by Piinks** [comment]
Thanks for taking a look @TahaTesser! I concur, should we close this then and follow up in #91772?
