### ISSUE TITLE
Appbar overlay on released version when using a streambuilder

### ISSUE THREAD

**Issue by maghrabyy** [flutter/flutter#127260]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Appbar is bugged on the released version only when i use a streambuilder inside the badgeContent on a Badge widget. It shows a white overlay on the appbar when i run the released version and it works just fine on the debug version.

I tried to use a plain Text widget without a streambuilder inside the badgeContent to check whether the problem is from the Badge package or from the streambuilder itself and it just worked fine without the overlay that appears on the release version, concluding that the problem is probably from the Streambuilder on the Appbar and not from the Badge package

I'm using `flutter build apk --release`

to build the apk release version.

### Expected results

This how it looks like on debug version which is supposed to look the same in release version as well:
![ASIEW](https://github.com/flutter/flutter/assets/53936761/b30c6493-61be-4968-a3c8-097c50b91b7e)

### Actual results

This is how it actually looks like on release version:
![Ehv3D](https://github.com/flutter/flutter/assets/53936761/6ad596dd-726a-43ce-abf8-b32889df038e)

### Code sample

<details><summary>Code sample</summary>

```dart
appBar: AppBar(
      elevation: 0,
      title: showProfileIcon == true
          ? IconButton(
              onPressed: () {
                Navigator.pushNamed(context, ProfilePage.id);
              },
              icon: const Icon(FontAwesomeIcons.solidUser))
          : null,
      actions: showShoppingCartIcon == true
          ? [
              badges.Badge(
                position: badges.BadgePosition.topEnd(top: 0, end: 2),
                showBadge: true,
                ignorePointer: false,
                badgeContent: StreamBuilder(
                    stream: _firestore
                        .collection('ShoppingCart')
                        .doc(_auth.currentUser!.uid)
                        .snapshots(),
                    builder: (context, AsyncSnapshot snapshot) {
                      if (!snapshot.hasData) {
                        return const Text('.');
                      } else {
                        int cartListItemsLength =
                            snapshot.data['Cart'].length;
                        return Positioned(
                          top: 3.0,
                          left: 4.0,
                          child: Text(
                            cartListItemsLength.toString(),
                            style: const TextStyle(color: kPrimaryColor),
                          ),
                        );
                      }
                    }),
                badgeStyle: const badges.BadgeStyle(
                  shape: badges.BadgeShape.circle,
                  badgeColor: kLightGreyColor,
                  elevation: 0,
                ),
                child: IconButton(
                    onPressed: () {
                      Navigator.pushNamed(context, ShoppingCart.id);
                    },
                    icon: const Icon(FontAwesomeIcons.cartShopping)),
              ),
            ]
          : customActions),
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[]
```

</details>

**Comment by darshankawar** [comment]
@maghrabyy 
If you are seeing a grey screen in release version of the app, it is indicative of an error. See this similar issue for your reference: https://github.com/flutter/website/issues/7773

You may want to revisit code implementation and see if it is causing any error that is leading to a grey screen as posted. If you think it is not true, then please provide us a complete minimal reproducible code sample that we can directly run to verify the reported behavior.

**Comment by maghrabyy** [comment]
It just worked fine when i decided to get rid of the Badge package and use the Badge class of material library.
However, it was giving that grey overlay error when I've tried many different methods that wasn't including the usage of the Badge package.
but eventually I released it was from the Badge package.

**Comment by darshankawar** [comment]
Good to know you identified the root cause. Since the package is third party, I'll go ahead and close as not a framework issue. You may need to open this issue in dedicated package's repo. If you disagree, write in comments and I'll reopen it.
