### ISSUE TITLE
[Impeller] Better handling of multi-contour paths with non-zero fill mode.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#127273]
Currently Impeller uses a fast path for tessellation if SkPath reports that the path is convex. If not, we fall back to using libtess. Unfortunately, SkPath doesn't track the convexity per-countour. IN some cases, we may have multiple countours each made up of convex shapes. These shapes could be individually tessellated using libtess or the convex tessellator, and then drawn with overdraw prevention enabled. This would be much faster than throwing the entire thing at libtess.

Naturally this only works for the non-zero fill mode.

**Comment by chinmaygarde** [comment]
From Triage: @jonahwilliams says "we can't really figure out if something is a hole of not without doing a whole bunch of math" which is probably not worth it.
