### ISSUE TITLE
flutter analyze fails on code generated by the Dart intl package tools

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#12726]
Summary: 
- `flutter analyze` finds errors in code generated by the Dart intl tools
- It's not possible to exclude the intl-generated code from the analyzer with an analysis_options.yaml file.
- Even if was possible, it's unlikely developers would know to include `package:flutter/analysis_options_user.yaml`
- Maybe`flutter create` should generate analysis_options.yaml file with some instructive comments.

Here's how I encountered this issue.

If I apply `flutter analyze` to the attached example it fails:

```
$ flutter analyze
Running "flutter packages get" in l10n_intl...
Analyzing /usr/local/google/home/hansmuller/flutter/l10n_intl...
  lint • Don't import implementation files from another package at lib/l10n/messages_all.dart:10:8 • implementation_imports
```

messages_all.dart is generated by the intl package. If I add an analysis_options.yaml file that contains:
```
analyzer:
  exclude:
    - 'lib/l10n/messages_all.dart'
```

Then I get a nonsense error:
```
  warning • The getter 'delegate' isn't defined for the class 'GlobalMaterialLocalizations' at lib/main.dart:103:37 • undefined_getter
1 issue found.
```

If I add `include: package:flutter/analysis_options_user.yaml` to the analysis_options.yaml file the original error returns.

If I add `// ignore: implementation_imports` above the offending line in messages_all.dart, then the analyzer is happy.  But of course I don't want to change a generated file.

[l10n_intl.zip](https://github.com/flutter/flutter/files/1416473/l10n_intl.zip)

**Comment by devoncarew** [comment]
@HansMuller, is there a more specific issue for the website?

I don't see analysis issues w/ this file:

```
include: package:flutter/analysis_options_user.yaml

analyzer:
  exclude:
    - 'lib/l10n/messages_all.dart'
```

(which doesn't match up with what you're seeing above).

Agree that we should set users up for success here - I'll see about change to package:intl to generate lint free code. The generate code probably doesn't need to be free of all possible lints, but shouldn't run afoul of recommended best practices.

**Comment by sethladd** [comment]
Is the generated code Dart 2 and/or strong mode compliant? That's probably the min bar.

**Comment by devoncarew** [comment]
Good question; I assume so, but cc'ing @alan-knight to be sure.

**Comment by alan-knight** [comment]
Yes, the generated should be entirely Dart 2 (as of this moment) compliant. It's run regularly under DDC, which is the strictest of our compilers.

It seems to me that running the user's lint options on generated code is kind of like running it on the code of dependent packages. It makes the linter do extra work to tell the user about things they can't fix if they wanted to. And since the user can change the lint preferences, it seems like almost any code could run afoul of someone's lint settings.

**Comment by devoncarew** [comment]
It's a tricky area for sure. The sea of possible lints is large. If we had a core set of lints we knew we wanted most code to follow (dart best practices for example), there might be a clearer answer to that.

One idea currently being discussed is whether we should add the ability to ignore all issues of a certain severity for a file. So, something like:

```
// ignore-for-file: hint
```

Would ignore hint level issues (which I believe most lints are). /cc @bwilkerson

**Comment by zoechi** [comment]
See also https://github.com/dart-lang/linter/issues/320
I'm going to close because it is tracked in the linter repo anyway.
