### ISSUE TITLE
`flutter_test` should support testing the new `Display` API

### ISSUE THREAD

**Issue by pdblasi-google** [flutter/flutter#127225]
With the new `PlatformDispatcher.displays` and `FlutterView.display` properties, `flutter_test` should have the same capability to mock and modify them as other properties on `PlatformDispatcher` and `FlutterView`.

* A new `TestDisplay` class will be created that allows for setting values that are read only in the `Display` implementation similar to `TestFlutterView`
    * Setters will have the same name as the get only property, not follow the old TestWindow patterns with separate names
* When no display is available (running in headless mode), a default TestDisplay will be created with properties that match up with default values for the view that would be embedded in it.
* When one or more displays are available on the PlatformDispatcher, they will be wrapped in `TestDisplay`s similarly to `TestFlutterView`s
* `TestFlutterView.display` will reference the same `TestDisplay` as `TestPlatformDispatcher.displays[view.displayId]` so that any mocked values will be in sync regardless of how they are accessed.

**Comment by pdblasi-google** [comment]
cc: @dnfield

**Comment by dnfield** [comment]
Mostly SGTM - right now the tester binary simulates having a "real" display the same way it does a real "window"/"view" object. But having mocking functionality available for this would be good.

**Comment by pdblasi-google** [comment]
Good to know! It'll be a lot easier if we don't have to special case headless mode and can just always wrap what the engine gives us. That's what I was hoping for, but I didn't know for sure if it did that.

I think at some point it'd be valid to extend this such that you can add fake displays, but I don't want to take that on as part of this initial support.

**Comment by dnfield** [comment]
I think the key need for the internal customer requesting this is the ability to fake the values coming from the `PlatformDispatcher.instance.implicitView!.display` so they can test various responses to changes in that size.

**Comment by pdblasi-google** [comment]
They won't be able to access mocked values through `PlatformDispatcher.instance`, but they should be able to do it through `WidgetsBinding.instance.platformDispatcher.implicitView` or `View.of(context)`. It's a limitation of the static accessor for `PlatformDispatcher`.

**Comment by pdblasi-google** [comment]
@goderbauer @dnfield

Would it ever be valid for a `FlutterView` to have a size/geometry larger than the `Display` that it's on?

**Comment by dnfield** [comment]
> @goderbauer @dnfield
> 
> Would it ever be valid for a `FlutterView` to have a size/geometry larger than the `Display` that it's on?

I think that should be possible (e.g. if the window is visible on multiple displays, or if the window exceeds the bounds of the display and thus is only partially rendered).

**Comment by pdblasi-google** [comment]
@dnfield

That's what I thought as well. I wouldn't even have asked the question if it had been about _Widgets_, but I didn't know if there was something special about a `FlutterView` as "a surface that can be drawn upon" that would limit it to never be larger than the display that it was on, even if Widgets contained in it were larger than both the view and the display.

If a `FlutterView` can potentially span across multiple displays, are we going to run into issues with having just a singular `display` property exposed instead of a `List<Display>`?

**Comment by dnfield** [comment]
The OS-level APIs give you whatever display the view is primarily on, and some OSes won't render it to multiple displays even if it stretches off the display - but it still can be larger than its display.
