### ISSUE TITLE
[Impeller] flutter_map OverlayImage disappears when above a certain Zoom level

### ISSUE THREAD

**Issue by W2NJL** [flutter/flutter#127272]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I'm running Flutter v3.10.1 with Impeller enabled.  I use the flutter_map plugin, with their version 3.10, though this is also observed with their latest flutter_map 4.0.

Using iOS 16.4 with the iPhone 14 Pro Max emulator on an Android Studio setup, with Impeller, with an OverlayImage enabled in a FlutterMap instance, the overlay image disappears once I zoom at level 10 or above.

This does not occur with Impeller disabled.

Here is an Issue I opened at the flutter_map repo further detailing the scenario:  [https://github.com/fleaflet/flutter_map/issues/1528](https://github.com/fleaflet/flutter_map/issues/1528)

### Expected results

The expected behavior is for the OverlayImage to persist to the maximum zoom level.

### Actual results

The OverlayImage disappears with Impeller enabled beyond Zoom level 9.  

### Code sample

<details><summary>Code sample</summary>

```dart
 FlutterMap(options: MapOptions(




        center:  LatLng(40, -74
             ),
      zoom:
          9,
      interactiveFlags: InteractiveFlag.pinchZoom |
          InteractiveFlag.drag |
          InteractiveFlag.doubleTapZoom
    ),
    children: [





      TileLayer(

          urlTemplate:
          'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
          subdomains: [
            'a',
            'b',
            'c'
          ]),

      OverlayImageLayer(

          overlayImages: <OverlayImage>[OverlayImage(bounds: LatLngBounds(LatLng(38, -77), LatLng(42, -72)), opacity: 140,imageProvider: NetworkImage('https://i.ibb.co/371Qjyv/4b95d868037040e18ba4c1b6063ebeb7-0.png')),]
      ),

    ]);
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

I just made two videos, one with Impeller enabled and zooming into the overlay:
https://vimeo.com/828616405?share=copy

And one with Impeller disabled, and the same zoom:
https://vimeo.com/828616262?share=copy

</details>

### Logs

<details><summary>Logs</summary>

I observed the following output when I enabled Impeller in debug mode running Flutter 3.7.12:

```console
Requested texture size exceeds maximum supported size of (8669, 9058)
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Flutter (Channel stable, 3.10.1, on macOS 13.3.1 22E772610a darwin-arm64, locale en-US)
    • Flutter version 3.10.1 on channel stable at /users/nicklangan/flutter/flutter
    ! Warning: `flutter` on your path resolves to /Users/nicklangan/flutter/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /users/nicklangan/flutter/flutter. Consider adding
      /users/nicklangan/flutter/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nicklangan/flutter/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /users/nicklangan/flutter/flutter. Consider adding
      /users/nicklangan/flutter/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (4 days ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nicklangan/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.76.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 9AE4F8CF-1EFC-4F17-B6F8-439EFE4EB781 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.3.1 22E772610a darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.


```

</details>

**Comment by chinmaygarde** [comment]
From Triage: This could happen if the offscreen layer is absurdly large. Impeller will bail out when trying to allocate a layer this large. But @bdero and @jonahwilliams worked on a related patch to apply clips to the computed coverage of the offscreen layer so it fits within the allocation limits. We should apply the correction in this case as well.

**Comment by chinmaygarde** [comment]
We believe this is fixed on `main` with the coverage hint patch. But we need to verify this still.
