### ISSUE TITLE
[Impeller] Inset box shadow renders incorrectly.

### ISSUE THREAD

**Issue by vasilich6107** [flutter/flutter#127232]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

run example from lib
https://github.com/artflutter/flutter_inset_box_shadow

- checkout the repo
- run code from `example` folder

### Skia
<img width="372" alt="image" src="https://github.com/flutter/flutter/assets/6721286/f006d9a6-7ce1-437d-97d5-7e3711beaec1">

### Impeller
<img width="367" alt="image" src="https://github.com/flutter/flutter/assets/6721286/fa920860-7a22-4353-a8d9-cc3078529aa1">

### Code sample

https://github.com/artflutter/flutter_inset_box_shadow/tree/main/example/lib

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.1, on macOS 13.3.1 22E772610a darwin-arm64 (Rosetta), locale en-UA)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Community Edition (version 2022.3.3)
[✓] VS Code (version 1.78.1)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 category.
```
 
</details>

**Comment by jonahwilliams** [comment]
Your images are 404ing...

**Comment by jonahwilliams** [comment]
Thanks! you also haven't actually posted your doctor information, so its unclear if you are on a hotfix or not. Please fill out the template

**Comment by jonahwilliams** [comment]
Thanks, when I run this on Skia I don't see images like you've posted:

Skia:

![flutter_03](https://github.com/flutter/flutter/assets/8975114/5eaab367-303a-4a57-b2b9-7b45eb601339)

Impeller:

![flutter_04](https://github.com/flutter/flutter/assets/8975114/7a687594-ed1e-4a33-a782-0be67be05cda)


Is this the right code sample? Do I need a particular version of that package?

**Comment by jonahwilliams** [comment]
Thanks, I can reproduce this on stable on master

**Comment by bdero** [comment]
I'm still working on this fidelity issue. The yak shave lead to an explosion of blend-related issues that I've been fixing in prep for this. Properly incorporating the mask blur in the general case is going to be very expensive. But, we can counter-act the additional mask blur expense for some color sources (including the app in this issue) by applying color filters on the CPU.

**Comment by bdero** [comment]
@pkumar8888 please file a new issue with your code repro -- I think the problem you're running into is different. Your code doesn't appear to contain a color blend, which was the failure catalyst for the code sample given in this bug.
