### ISSUE TITLE
[CP] [Impeller] Fix the issue that 'coverage_coords' is incorrectly calculated in 'FillPathGeometry::GetPositionUVBuffer'

### ISSUE THREAD

**Issue by ColdPaleLight** [flutter/flutter#127250]
### issue_link

https://github.com/flutter/flutter/issues/127183

### Commit Hash

45a72f0c6aacd97622703d6bfb9e67b24e1be522

### Target

stable

### pr_link

https://github.com/flutter/engine/pull/42180

### Impacted Users

Impeller users.

### Impact Description

When drawing path with ImageShader, the rendering result is incorrect.

### Workaround

No workarounds

### Risk

low

### Test Coverage

yes

### Validation Steps

* Run the new test in https://github.com/flutter/engine/pull/42155
* Run the reproduction app in https://github.com/flutter/flutter/issues/127183.

**Comment by dnfield** [comment]
CP LGTM
