### ISSUE TITLE
[path_provider] Update win32 to 5.x

### ISSUE THREAD

**Issue by temzints** [flutter/flutter#127289]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

`Because path_provider_windows >=2.1.6 depends on win32 >=2.1.0 <5.0.0 and app depends on win32 ^5.0.2, path_provider_windows >=2.1.6 is forbidden.`

### Proposal

Bump dependency `win32` to 5.x in  `path_provider_windows`

**Comment by ziyadgodil** [comment]
Hi @temzints  
Try adding win32: lower version then 5.0.0
instead of win32: ^5.0.2

**Comment by timsneath** [comment]
For the APIs used by path_provider_windows, v5 should be compatible with v4. So a pull request similar to this one should be ideal: https://github.com/flutter/packages/pull/3820/files

(For those paying attention, I don't expect we'll need to update the major version for win32 for a while now. The changes in v5 move the unstable WinRT APIs into a separate package, leaving win32 to focus on APIs that won't change.)

**Comment by hatemragab** [comment]
for current you can fix it by 
```
dependency_overrides:
  win32: ^2.0.0
```
