### ISSUE TITLE
Flutter ARM64 Install

### ISSUE THREAD

**Issue by AndyChriss123** [flutter/flutter#127264]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Install flutter manually on the target ARM64 based board, OrangePI4 as per the guide on the official flutter webpage.
2. Create a new app "my_app" and attempt to run the demo app using flutter run.

### Actual results

I get the following error in the terminal:

eos@orangepi4-lts:~/VSsandbox/my_app$ flutter run
Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                           

(my_app:4163): Gdk-ERROR **: 12:35:04.021: The program 'my_app' received an X Window System error.
This probably reflects a bug in the program.
The error was 'GLXBadFBConfig'.
  (Details: serial 252 error_code 167 request_code 152 (GLX) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
   
   I have also tried cross-compiling from a AMDX64 linux host (laptop) for linux arm64 but I received an error stating that this feature is not currently supported.
   I have also tried using flutter-pi with no succes (but not only is this unrelated but I'm also not using a RaspberryPi board)
   I realize that this can most probably be considered as a duplicate request and it only fits in this category (I am having difficulty installing Flutter or getting it to work) from my perspective because I can't even run the demo app but all of the other related issues seem to refer to ARM64 based processors only when talking about mobile devices at least as far as I was able to understand.
   So far I had success with accomplishing everything I wanted to do on a Linux (AMD)x64 machine and I thank you for developing this incredible development environment.
To sum it up, basically what I want to know is whether if it is possible at the moment to develop and deploy flutter apps to an ARM64 processor based board running a linux distro, wether if I have to set up a development environment on the specific architecture or cross-compile from another device. At the moment I am not interested in web development or android/ios development, only linux desktop apps.

Thank you very much for your time!

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

ARM64 OrangePI4 BOARD
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.1, on Armbian 23.02.2 Jammy 5.15.80-rockchip64, locale en_US.UTF-8)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] Connected device (1 available)
[✓] Network resources

! Doctor found issues in 3 categories.

```

</details>
<details>
<summary>Doctor output</summary>

```console

AMD64 Linux LAPTOP
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.1, on Ubuntu 22.04.2 LTS 5.19.0-41-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.2)
[✓] VS Code
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by stuartmorgan** [comment]
Is there a reason you think this is related to arm64 support? The error message in your logs appears to be a runtime issue with graphics support on your device.

**Comment by AndyChriss123** [comment]
Thank you very much for stopping by to help out.
I come from an industrial environment and I've been successfully developing HMIs but this is the first time I'm using a cross-platform development environment like Flutter in order to build an UI on a Desktop machine so there are a lot of obvious things that I'm unaware of.
Thanks to your answer I got a little bonus insight so thank you very much for that, I posted the log only as a requirement from the issue posting interface but now I'm glad I did.
The existence of flutter-pi (as RaspberryPi is just another ARM64 based board) and the failed attempt of cross-compiling from linux laptop due to the error: Cross compiling from x64 machine to arm64 feature is not currently supported has led me to believe that it might not be possible to develop flutter apps for Linux arm64 Desktop environment at the moment.
I'm not a big fan of using up people's time unless I have already gained a lot of knowledge about a certain field/environment so this question is the entire reason I made this request (though if you are happy to provide more information on this specific matter that would help me a lot):

Is it possible to develop flutter apps in a straight-forward (officially supported) manner on/for ARM64 processor based Desktop devices?

**Comment by stuartmorgan** [comment]
See https://github.com/flutter/flutter/issues/60678#issuecomment-1021631389

> this question is the entire reason I made this request

The issue tracker is for bug reports and feature requests; for questions consider one of the resources listed here: https://flutter.dev/community#community-grid
