### ISSUE TITLE
CameraDevice.front not working on Android

### ISSUE THREAD

**Issue by LynkKid** [flutter/flutter#127259]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Hello,

I have encountered an issue related to using CameraDevice.front on the Android platform, and I would like to report this problem. When I attempt to access CameraDevice.front, I am facing difficulties and unable to utilize the front camera on Android devices. This issue seems to be affecting the functionality of the CameraDevice.front feature, which is crucial for certain applications and functionalities.

I have tested this problem on multiple Android devices running different versions of the operating system, and the issue persists across all of them. I have also checked the necessary permissions and ensured that the camera hardware is functioning properly on these devices.

### Expected results

The CameraDevice.front should successfully provide access to the front camera of the Android device.

### Actual results

The CameraDevice.front fails to function correctly and does not provide access to the front camera. This issue prevents me from utilizing the front camera in my application.

This problem severely impacts the functionality and user experience of applications that rely on the front camera. It would be greatly appreciated if the development team could investigate and resolve this issue as soon as possible.

Thank you for your attention to this matter.

Best regards,

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @LynkKid, this is an android limitation not an issue with the image_picker plugin.

See this section from the plugin documentation. 

https://github.com/flutter/packages/blob/d94759e4600cb39ba9cdacd1d8f9a96ebead2049/packages/image_picker/image_picker/lib/image_picker.dart#L47-L51

Closing from here as this is an android platform limitation and not an issue with the image_picker plugin. 

Thank you
