### ISSUE TITLE
No three-line ExpansionTile

### ISSUE THREAD

**Issue by jamesgorman2** [flutter/flutter#127256]
Component issue of https://github.com/flutter/flutter/issues/127075

as per title

### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

**Comment by huycozy** [comment]
Closing this issue in favor of https://github.com/flutter/flutter/issues/127252 (https://github.com/flutter/flutter/issues/127075#issuecomment-1556865733).
