### ISSUE TITLE
[WEB] Incorrect icon alignment with HTML renderer when using icon tree shaking

### ISSUE THREAD

**Issue by pogorv12** [flutter/flutter#127270]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. flutter create my-project
2. flutter build web --web-renderer html --release
3. Upload and open in browser

### Expected results

Action button has [+] in the middle of the button.

This could be achieved with [ flutter build web --web-renderer canvaskit --release ] command.

### Actual results

[+] character is misaligned and shifted down for the visible number of pixels.

The back button in the AppBar behave similarly.  

Not sure when the issue appeared exactly, but I spotted it after when flutter been upgraded to version 3.10.0.
Material2 has the same behavior. 

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // TRY THIS: Try running your application with "flutter run". You'll see
        // the application has a blue toolbar. Then, without quitting the app,
        // try changing the seedColor in the colorScheme below to Colors.green
        // and then invoke "hot reload" (save your changes or press the "hot
        // reload" button in a Flutter-supported IDE, or press "r" if you used
        // the command line to start the app).
        //
        // Notice that the counter didn't reset back to zero; the application
        // state is not lost during the reload. To reset the state, use hot
        // restart instead.
        //
        // This works for code too, not just values: Most code changes can be
        // tested with just a hot reload.
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // TRY THIS: Try changing the color here to a specific color (to
        // Colors.amber, perhaps?) and trigger a hot reload to see the AppBar
        // change color while the other colors stay the same.
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          //
          // TRY THIS: Invoke "debug painting" (choose the "Toggle Debug Paint"
          // action in the IDE, or press "p" in the console), to see the
          // wireframe for each widget.
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```
</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

| HTML | canvaskit | 
| -- | -- |
| <img src="https://github.com/flutter/flutter/assets/59342958/874cac9b-409b-4fd4-9988-f93d5489668d" /> | <img src="https://github.com/flutter/flutter/assets/59342958/406faff1-a829-47c7-8b44-d9fe856e74e2" /> |

</details>

### Flutter Doctor output

[√] Flutter (Channel stable, 3.10.1, on Microsoft Windows [Version 10.0.19042.1706], locale be-BY)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.3)
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.78.2)
[√] Connected device (4 available)
[√] Network resources

**Comment by danagbemava-nc** [comment]
Hi @pogorv12, what device are you experiencing this issue on? I tested on a Pixel 7 with the HTML renderer and it seems to work just fine for me. I am using the chrome inspector tool to display my device screen in the screenshot below. I tested in release mode and it was the same thing as well. 

<img width="1080" alt="Screenshot 2023-05-22 at 09 42 10" src="https://github.com/flutter/flutter/assets/88313112/8f293139-f550-4432-a8b7-c5b78a15577e">

**Comment by pogorv12** [comment]
Hello! @danagbemava-nc 

I've tested the issue on Sony Xperia 5-II, Ipad, iPhone, Xiaomi Mi2, Lenovo Laptop on windows. All devices where i made tests had the issue. 

You can try my render on [](https://vp-test-app-1.web.app/#/). It is with auto rendering, so try on a  smartphone.

I expect that the problem could be with renderer... or with my particular renderer. 
First time I spotted the issue  on 3.10.0... then I updated to 3.10.1...then I downgraded to 3.10.0... then i tried to downgrade further but no luck as it's available only to 3.10. Than I back to 3.10.1. Issue remains. 

Should i try to reinstall flutter completely or any libraries?  Maybe you can advice exact ones?

**Comment by RoarGronmo** [comment]
Similar issues with me, I have seen this at least from v3.0 of flutter.

We use codemagic.io on hosting publishing the web version with html.

Example emulation vs published 

emulation:
![image](https://github.com/flutter/flutter/assets/11217296/a6de69b0-2adb-4cc9-bb80-65f3646924ec)
All seems fit


published:
![image](https://github.com/flutter/flutter/assets/11217296/45f8446e-f827-47d5-812e-65fcd31f38ba)
Down shifted some pixels

**Comment by xi-guan-dev-delta** [comment]
Seems like it's caused by the tree-shake-icons. Will be back to normal when add `--no-tree-shake-icons` when run flutter build.

**Comment by taufiq-husain** [comment]
Omg this was driving me crazy for the past few days and I'd been wondering what I did wrong. It only happens in production web app (build web --release or any other mode for web). Something changed in flutter that is causing this. I finally tried the --no-tree-shake-icons way and it fixed everything back! Phew! Basically alignment of icons next to text is ruined with normal flutter build (which includes tree shake option now).

**Comment by jacobsimionato** [comment]
I believe Google apps have seen this too - see internal b/278484455

**Comment by mdebbar** [comment]
@guidezpl it's related to font tree-shaking, but not to that issue specifically.

The current theory is that this is happening because the tree-shaking procedure removes the `" "` (whitespace) glyph from the font. But our text height measurements rely on the size of `" "` in the given font. When that glyph is missing, the browser uses its fallback fonts and that causes our measurements to be off.

cc @christopherfujino @jonahwilliams can we have a special case to keep `" "` in the font even if it's not used by the app?

**Comment by christopherfujino** [comment]
> The current theory is that this is happening because the tree-shaking procedure removes the `" "` (whitespace) glyph from the font. But our text height measurements rely on the size of `" "` in the given font. When that glyph is missing, the browser uses its fallback fonts and that causes our measurements to be off.
> 
> cc @christopherfujino @jonahwilliams can we have a special case to keep `" "` in the font even if it's not used by the app?

Ahh, interesting. This solution SGTM

**Comment by RoarGronmo** [comment]
Any schedule for this fix ?

**Comment by RoarGronmo** [comment]
Current observation:
Now using Chrome emulator on published applications (using codemagic) the icons seems to ba aligned ok, but on device phone (samsung s9+ with android 10, one ui 2.5) they are still downshifted some icons.

ok in chrome (emulated in windows)
![image](https://github.com/flutter/flutter/assets/11217296/0acc4370-d22e-48d3-8b0e-191044e1f118)
chrome version: 113.0.5672.129

not ok in samsung s9+ (mobile chrome)
![image](https://github.com/flutter/flutter/assets/11217296/d0bb5fb3-6874-4524-aa99-fbcb6adfdea7)
chrome version: 
chrome version: 113.0.5672.162

**Comment by christopherfujino** [comment]
@pogorv12 can you try again on https://github.com/flutter/flutter/commit/44e7206aa1497a3feee8dfe5a833483a62880b9d to verify my fix?

**Comment by pogorv12** [comment]
> @pogorv12 can you try again on [44e7206](https://github.com/flutter/flutter/commit/44e7206aa1497a3feee8dfe5a833483a62880b9d) to verify my fix?

Hi!  I don't really know how I can test your commit, but I've recently updated to flutter 3.10.3 and the issue is still there.

**Comment by christopherfujino** [comment]
> > @pogorv12 can you try again on [44e7206](https://github.com/flutter/flutter/commit/44e7206aa1497a3feee8dfe5a833483a62880b9d) to verify my fix?
> 
> Hi! I don't really know how I can test your commit, but I've recently updated to flutter 3.10.3 and the issue is still there.

You would need to do something like (assuming you're on macOS or Linux):

```
cd /path/to/flutter
git fetch
git checkout 44e7206aa1497a3feee8dfe5a833483a62880b9d
```

**Comment by christopherfujino** [comment]
I see you're on windows, but it should be more or less the same commands in the command prompt or powershell.

**Comment by maRci002** [comment]
> Expected to find fonts for (MaterialIcons, packages/cupertino_icons/CupertinoIcons, CoffeeTimerIcons), but found (MaterialIcons, CoffeeTimerIcons).

add this line to your dependencies in `pubspec.yaml`:
```yaml
cupertino_icons: ^1.0.0
```

**Comment by antonkarliner** [comment]
> add this line to your dependencies in `pubspec.yaml`:
> 
> ```yaml
> cupertino_icons: ^1.0.0
> ```

Thanks, this error is gone, but others stay

**Comment by maRci002** [comment]
> but others stay

Create a new issue and mention this issue / PR.
