### ISSUE TITLE
[CP] [web] Fix event offset on transformed widgets.

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#127229]
### issue_link

https://github.com/flutter/flutter/issues/126661

### Commit Hash

flutter/engine@4f3f7bb

### Target

stable

### pr_link

https://github.com/flutter/engine/pull/42171

### Impacted Users

customer: quake, customer: crowd (Flutter Web users with HtmlElementViews and transforms)

### Impact Description

Browsers don't apply "scale" transform to the offsetX,offsetY of PointerEvents (mouse). This causes that hit testing in Flutter web apps that mix HTML Element Views and `scale`-transformed widgets won't behave normally.

https://github.com/flutter/flutter/assets/31738080/8092b6b6-0a55-41ca-bc50-6176a73f7ad6

This PR changes the implementation of the "hover" to use viewport-based coordinates, rather than the bogus `offsetX, offsetY`.

### Workaround

People can set `pointer-events: none` on their HTML Elements, but normally those are added because the interaction is needed, so **no**, there's not a good workaround for this.

### Risk

low

### Test Coverage

yes

### Validation Steps

Use some of the example apps from the (several) bug reports:

* https://github.com/flutter/flutter/issues/126661
* https://github.com/flutter/flutter/issues/126754
* cl/529245972

**Comment by CaseyHillers** [comment]
@yjbanov can you review this CP request? If it looks good to you, add the "cp: approved" label.

**Comment by ditman** [comment]
(I've also requested a review from @yjbanov in the CP PR)

**Comment by yjbanov** [comment]
![lgtm](https://user-images.githubusercontent.com/211513/32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d.png)
