### ISSUE TITLE
Barrier dismissible dialogs pops on back button press

### ISSUE THREAD

**Issue by Ivaskuu** [flutter/flutter#12722]
## Steps to Reproduce

```
showDialog
(
  context: context,
  barrierDismissible: false,
  child: new SimpleDialog
  (
    children: <Widget>
    [
      ...
    ],
  )
);
```

I think that barrier dismissible dialogs shouldn't be closed by pressing the back button (the system one).

**Comment by Hixie** [comment]
Can you elaborate on this? Why?

**Comment by Ivaskuu** [comment]
Well, the objective of a barrier dismissible dialog is that it can't and shouldn't be closed. That implies maybe a crucial choice the user must do in an app. And the barrierDismissible proprety is there for that. But the problem is that by tapping the back softkey, it fires the Navigator.pop() method and the dialog disappears.

**Comment by matthiasbruns** [comment]
Having the same problem.
Non cancelable dialogs should not be cancelled when pressing the back button in Android.
The back button should pop the view history instead, which should lead to a back navigation into the last view.

**Comment by wilburt** [comment]
Any update on this yet?

**Comment by Hixie** [comment]
if you want to block the back button, use a willpop handler, see the WillPopScope widget.

**Comment by zoechi** [comment]
Is there still something to do?

**Comment by Hixie** [comment]
I guess not, my last comment more or less summarises what to do.

**Comment by cyberIndia** [comment]
willPop is not helping in the case. the flow does not reach the onWillPop when back button is pressed during the dialog. it does after it's been dismissed...

**Comment by danielRi** [comment]
Dont get me wrong your solution definetly helps, but now the user can´t navigate back with the back button at all, the back button does nothing now. I think this issue should still be open.

**Comment by SwissCheese5** [comment]
Definitely still a problem without a solid solution.

**Comment by csedeepakyadav** [comment]
// working perfectly fine
// tested

dialogPoint() {
    showDialog(
        barrierDismissible: false,
        context: _scaffoldKey.currentState.context,
        builder: (BuildContext context) {
         
          return StatefulBuilder(builder: (context, setState) {
            return WillPopScope(
              onWillPop: () async => false,
              child: Dialog(

                // your content here
              ),
            );
          });
        });
  }
