### ISSUE TITLE
ListViewBuilder for Slivers

### ISSUE THREAD

**Issue by dennisgb** [flutter/flutter#127314]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Hello,

I have created a calendar as a list of days in a horizontal scroll view. I would like to make it infinitely with a ScrollViewBuilder, but the problem is, that it consists of SliverStickyHeaders. Is there anything comparable to ListViewBuilder for Slivers?

Thanks and regards

Dennis

### Proposal

Something comparable to ListViewBuilder for Slivers.

**Comment by Andree98** [comment]
What about a `SliverList` with a `SliverChildBuilderDelegate`?

`SliverList(
                  delegate: SliverChildBuilderDelegate(
                    (context, index) => Text('$index'),
                  ),
                );`

**Comment by dam-ease** [comment]
Thanks for filing this issue @dennisgb. Kindly check the solution mentioned in this [comment](https://github.com/flutter/flutter/issues/127314#issuecomment-1557158167) to see if it helps to resolve your issue. Also, there is a similar issue currently open #51107, kindly follow up on the issue for further updates. 

Thank you!

**Comment by dennisgb** [comment]
> What about a `SliverList` with a `SliverChildBuilderDelegate`?
> 
> `SliverList( delegate: SliverChildBuilderDelegate( (context, index) => Text('$index'), ), );`

Instead of Text I want to use SliverStickyHeader so this solution does not work unfortunately because it requires a widget.
