### ISSUE TITLE
Many builds cancelled due to slow bot_setup step

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#127336]
Example https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Production%20Engine%20Drone/173677/overview

<img width="934" alt="Screenshot 2023-05-22 at 10 44 02 AM" src="https://github.com/flutter/flutter/assets/6343103/75811fe6-f575-4e69-96a4-2b0ec694586c">

**Comment by zanderso** [comment]
I'm going to re-run the failed builds to try to reopen the tree.

**Comment by zanderso** [comment]
From chat, this is also affecting roll PRs.

**Comment by zanderso** [comment]
The step is consistently taking 15+ minutes across many jobs.

**Comment by zanderso** [comment]
cc @keyonghan @godofredoc

**Comment by yusuf-goog** [comment]
We are working on this. This is related to a slow checkout. It is expected to recover on its own.

 Please cc gardner as well on these issues.

**Comment by zanderso** [comment]
@yusuf-goog The new process for infra issues says to file the issue, add it to the queue, and then ping the gardener on Discord on the tree-status chat. So, I pinged you on Discord.

**Comment by zanderso** [comment]
Re-runs are still getting cancelled. Tree is still closed.

**Comment by godofredoc** [comment]
Seems like this is still failing very freq, can we open a bug with the GoB team?

In addition to that we'll need to implement our own caching mechanism for checkouts as we are being hit very badly by extremely slow checkout.

**Comment by yusuf-goog** [comment]
Created a ticket with GoB team : b/283853706

**Comment by yusuf-goog** [comment]
The builds seem to be recovering now, last many of them have all run successfully.

**Comment by yusuf-goog** [comment]
GoB team confirmed that there was an incident during the time we had the errors. They are tracking.

**Comment by yusuf-goog** [comment]
Closing this since the builds have recovered and we have identified a GoB event that was likely responsible for the outage. 

The GoB team is investigating that event on their side.

**Comment by zanderso** [comment]
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20linux_web_engine/1535/overview

**Comment by yusuf-goog** [comment]
2 of those seem to be related to a GoB issue, the others are something different (looks like they are hitting the 1 hour timeouts)

**Comment by yusuf-goog** [comment]
I will ping the GoB ticket. They seem to be seeing issues even after a rollback of a known issue was performed yesterday.

**Comment by godofredoc** [comment]
The timeouts are related to capacity, we probably need to remove shards in the build step for the web engine or move them to an 8 core machine. A single build of web engine is requesting 12 32 cores machine when total capacity is 15 shared between flutter and engine.

**Comment by zanderso** [comment]
fyi @eyebrowsoffire

**Comment by godofredoc** [comment]
https://github.com/flutter/flutter/issues/124682 for additional context

**Comment by keyonghan** [comment]
The second layer of cache has been rolled out, and the engine tree is in a good state now. Please reopen if this reproduces.
