### ISSUE TITLE
TextEditingController gets triggered twice when deleting characters from TextField

### ISSUE THREAD

**Issue by kamami** [flutter/flutter#127398]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Just use the official example for controlled text input on the latest stable release:

https://docs.flutter.dev/cookbook/forms/text-field-changes

### Expected results

The characters should not show up twice in the console when deleting them:

<img width="221" alt="image" src="https://github.com/flutter/flutter/assets/43880037/63c4079f-a371-477d-a157-436afb0531eb">

### Actual results

The last character gets printed twice to the console when deleting it:

<img width="221" alt="image" src="https://github.com/flutter/flutter/assets/43880037/43322219-c9cc-4744-932b-0b3faaf88c8a">

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Retrieve Text Input',
      home: MyCustomForm(),
    );
  }
}

// Define a custom Form widget.
class MyCustomForm extends StatefulWidget {
  const MyCustomForm({super.key});

  @override
  State<MyCustomForm> createState() => _MyCustomFormState();
}

// Define a corresponding State class.
// This class holds data related to the Form.
class _MyCustomFormState extends State<MyCustomForm> {
  // Create a text controller and use it to retrieve the current value
  // of the TextField.
  final myController = TextEditingController();

  @override
  void initState() {
    super.initState();

    // Start listening to changes.
    myController.addListener(_printLatestValue);
  }

  @override
  void dispose() {
    // Clean up the controller when the widget is removed from the widget tree.
    // This also removes the _printLatestValue listener.
    myController.dispose();
    super.dispose();
  }

  void _printLatestValue() {
    print('Second text field: ${myController.text}');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Retrieve Text Input'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          children: [
            TextField(
              onChanged: (text) {
                print('First text field: $text');
              },
            ),
            TextField(
              controller: myController,
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.1, on macOS 13.3.1 22E261 darwin-arm64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.78.1)
[✓] Connected device (2 available)
[✓] Network resources
```

</details>

**Comment by arcanine33** [comment]
same problem...

**Comment by kamami** [comment]
This breaks my search completely... Did you find any workaround so far?

**Comment by dam-ease** [comment]
Thanks for filing this issue @kamami. This https://github.com/flutter/flutter/issues/45804#issuecomment-1234656811 is similar to this issue. Closing this as there is a similar issue currently open #45804, kindly follow up on the issue for further updates.

Thank you!
