### ISSUE TITLE
[CP] [Impeller] Use untransformed text bounds to calculate the size of ColorSourceTextContents

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#127346]
### issue_link

https://github.com/flutter/flutter/issues/127103

### Commit Hash

d95dfc83f3c3e7353553d7da8189f2ed013a442a

### Target

stable

### pr_link

https://github.com/flutter/engine/pull/42218

### Impacted Users

Impeller users

### Impact Description

Fixes rendering failures in text with shaders on Impeller when a transform is applied

### Workaround

disable Impeller

### Risk

low

### Test Coverage

yes

### Validation Steps

Run the example app in https://github.com/flutter/flutter/issues/127103 on an iOS device with Impeller

**Comment by chinmaygarde** [comment]
LGTM. cc @zanderso
