### ISSUE TITLE
[in_app_purchase]能提供苹果支付中storekit2的flutter插件吗

### ISSUE THREAD

**Issue by tqhnet** [flutter/flutter#127367]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

我在插件中想使用storekit2的API

### Proposal

[in_app_purchase]能提供苹果支付中storekit2的flutter插件吗
https://developer.apple.com/documentation/storekit/in-app_purchase/

**Comment by huycozy** [comment]
Thanks for filing the proposal. For more information: https://flutter.dev/go/ios-storekit2

_Note: I updated issue's description to English_

**Comment by huycozy** [comment]
This is a known issue being tracked at https://github.com/flutter/flutter/issues/116383. 

Closing this issue as a duplicate, so please follow up on it for further updates.
