### ISSUE TITLE
google_signin plugin crashes app if plist.info is incorrectly configured

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#12734]
## Steps to Reproduce

1. Follow the first six steps of https://codelabs.developers.google.com/codelabs/flutter-firebase/
1. Mess up on the step to add `<key>CFBundleURLTypes</key>`, for example paste it at the wrong location in the XML tree
1. Run app

=> the app crashes:

```
Syncing files to device iPhone X...                   1.0s

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on iPhone X is available at: http://127.0.0.1:8112/
For a more detailed help message, press "h". To quit, press "q".
[Firebase/Analytics][I-ACS032003] iAd framework is not linked. Search Ad Attribution Reporter is disabled.
[Firebase/Analytics][I-ACS023012] Firebase Analytics enabled
)
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010d12d1cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00000001120cbf41 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010d1a1b95 +[NSException raise:format:] + 197
	3   Runner                              0x000000010c062681 -[GIDSignIn signInWithOptions:] + 242
	4   Runner                              0x000000010c05f06d -[GIDSignIn signIn] + 64
	5   Runner                              0x000000010befa555 -[GoogleSignInPlugin handleMethodCall:result:] + 1461
	6   Flutter                             0x000000010d9fe9b1 __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 118
	7   Flutter                             0x000000010da11667 _ZN5shell15P<…>
Lost connection to device.
```

Can we fail more graciously?

**Comment by jmnyv** [comment]
Would be appreciated. I have sign in working for android and _as far as I can tell_, I have everything correctly set up for iOS. However, I'm getting this exact error message, so I suppose I don't. The error message could do more to point in the direction of a solution. :)

**Comment by el7r** [comment]
I'm facing the exact same issue, works perfectly on Android, however it crashes on iOS with the same error message in the log.

**Comment by el7r** [comment]
In my case, I found out that I had duplicate CFBundleURLTypes in PList.info, 
for Facebook Plugin and Google Sign in as explained in this answer on stackoverflow
https://stackoverflow.com/a/52494306

merging the dicts fixed the issue.

**Comment by kdela** [comment]
I've found working solution (looks correct and works for me):
https://stackoverflow.com/a/46580118

**Comment by cyanglaz** [comment]
We exposed more relevant error message when the `CFBundleURLTypes` is incorrectly configured. We would still crash the app since it is never a good idea to ship the prod without the correct configuration for the Google Sign In plugin.
I am closing the issue.  if any related issue is found, please feel free to open it with more details.

**Comment by mrruby** [comment]
I have forgotten this step 

"Then add the CFBundleURLTypes attributes below into the [my_project]/ios/Runner/Info.plist file.


<key>CFBundleURLTypes</key>
<array>
    <dict>
        <key>CFBundleTypeRole</key>
        <string>Editor</string>
        <key>CFBundleURLSchemes</key>
        <array>
            
            
            <string>com.googleusercontent.apps.861823949799-vc35cprkp249096uujjn0vvnmcvjppkn</string>
        </array>
    </dict>
</array>
”

**Comment by Flucadetena** [comment]
In my case I pasted the wrong REVERSED CLIENT ID. Double, triple check it ;P
