### ISSUE TITLE
[CP] [Impeller] Use 32 bit Gaussian function in the 2-pass blur

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#127341]
### issue_link

https://github.com/flutter/flutter/issues/126487

### Commit Hash

https://github.com/flutter/engine/commit/87a03e107df750773fecf9a17b0bd6609aed2348

### Target

stable

### pr_link

https://github.com/flutter/engine/pull/42216

### Impacted Users

Impeller users

### Impact Description

Blurs with resolved sigmas greater than 255 disappear without this fix.

### Workaround

There are no workarounds.

### Risk

low

### Test Coverage

yes

### Validation Steps

Verify that the new playground/golden test added in https://github.com/flutter/engine/pull/42069 works, or run the reproduction app in https://github.com/flutter/flutter/issues/126487.

**Comment by jonahwilliams** [comment]
LGTM

**Comment by chinmaygarde** [comment]
LGTM
