### ISSUE TITLE
get the number of pointers in `ScaleGestureRecognizer`'s `handleEvent`

### ISSUE THREAD

**Issue by kseino** [flutter/flutter#127309]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

we have a use case to handle pointer event, depending on the number of pointers in the `ScaleGestureRecognizer`'s `handleEvent`.
do we have any way to get the number of pointers?

```
class CustomScaleGestureRecognizer extends ScaleGestureRecognizer {
  @override void handleEvent(PointerEvent event) {
    super.handleEvent(event);
    // handle only when two-fingered.
  }
}
```

### Proposal

```
class CustomScaleGestureRecognizer extends ScaleGestureRecognizer {
  @override void handleEvent(PointerEvent event) {
    super.handleEvent(event);
    if (pointerCount == 2) {
      // do something
    }
  }
}
```

**Comment by goderbauer** [comment]
> we have a use case to handle pointer event, depending on the number of pointers in the ScaleGestureRecognizer's handleEvent.

Can you describe what that use case is?
