### ISSUE TITLE
Clarify install directory in Mac OS setup docs

### ISSUE THREAD

**Issue by pnewsam** [flutter/flutter#12732]
This is probably very obvious to someone more experienced, but I got a bit confused after I git cloned flutter into a nested directory, as opposed to my home ~ directory, and shell wouldn't recognize the 'flutter' command even after I'd correctly added it to the $PATH var.

In Mac OS setup docs @ https://flutter.io/setup-macos
> 
> Clone the repo
> 
> If this is the first time you’re installing Flutter on this machine, clone the alpha branch of the repository and then add the flutter tool to your path:

Maybe it would be helpful to specify where to clone the dir?

**Comment by trinnguyen** [comment]
Beginner here too, I just finished setting up and running the first Flutter app.
- You can clone git to any folder
- Ensure adding the correct path to `flutter/bin` folder inside the cloned dir to $PATH. The `flutter` exec file is inside `bin` folder. Simply execute this command in the root of your git cloned dir.

```
export PATH=`pwd`/flutter/bin:$PATH
```
- Command `flutter` should be fine to go now, ensure that you are staying in the same Terminal screen as above `export...` command
- Should update the $PATH on `~/.bash_profile` for permanent usage: https://flutter.io/setup-macos/#update-your-path

**Comment by pnewsam** [comment]
Sorry, I guess I was unclear.  ````export PATH=`pwd`/flutter/bin:$PATH```` worked fine for me for initial setup. I ran into problems when I tried to update my path permanently. Under 'Update your path' the docs suggest to add this command to bash profile:

`export PATH=$HOME/flutter/bin:$PATH`

I did that, but because I had git cloned flutter into a directory that was not my $HOME directory, shell couldn't find the flutter command.

**Comment by trinnguyen** [comment]
Ah, should replace the `$HOME/flutter` by the path to root of your git folder. I think they assume cloning flutter to the $HOME folder. 

`export PATH=[PATH_TO_GIT_FOLDER]/bin:$PATH`

**Comment by sethladd** [comment]
What do you think about https://github.com/flutter/website/pull/718 ?

**Comment by pnewsam** [comment]
That looks great, thanks!

**Comment by mjohnsullivan** [comment]
Changed now merged to master; thanks for the feedback!
