### ISSUE TITLE
[CP] [Impeller] Limit blur kernel to 1000x1000 pixels

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#127342]
### issue_link

https://github.com/flutter/flutter/issues/127151

### Commit Hash

https://github.com/flutter/engine/commit/3267fa29491a2a6715d2b53e0b5f9b452572ad30

### Target

stable

### pr_link

https://github.com/flutter/engine/pull/42217

### Impacted Users

Impeller users

### Impact Description

There is no upper bound for the blur kernel size, which can trigger the blur filter to allocate arbitrarily large textures. This results in at best failure to render frames, and at worst a crash.

### Workaround

Users can work around this by bounding blur sigmas to a reasonable size in the framework.

### Risk

low

### Test Coverage

yes

### Validation Steps

Run the new playground/golden test in https://github.com/flutter/engine/pull/42154, or the reproduction app in https://github.com/flutter/flutter/issues/127151.

**Comment by jonahwilliams** [comment]
LGTM
