### ISSUE TITLE
Video automatically plays when on iOS Safari and using Flutter Web.

### ISSUE THREAD

**Issue by maylortaylor** [flutter/flutter#127332]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Make a Flutter Web app, go to the website on an iPhone using Safari.
2. Load the app and navigate to the screen with the video player, on first load of the screen the video will not automatically play.
3. Navigate away from the video player screen and then back to the video player screen and the video will automatically play.
4. 

### Expected results

I expect that the video won't automatically start playing when I visit the Flutter made web page on an iOS device using Safari.

### Actual results

I have a Flutter website that has a video play after you click a thumbnail (using GestureDetector). This works fine on Chrome, Edge, and all desktop browsers I have tried. It also works as expected on my Pixel 5 phone using Chrome browser. However, when I try the same page on an iOS Pro 12 Max using Safari browser, the videos automatically starts playing about 80% of the time. Usually doesn't happen the first time the screen is loaded but when I navigate to the next screen or back to a previous screen the video will start playing even though I have not called the **play()** function.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

void main() {
  runApp(MyApp());
}

String pageName = "ScreenOnePage";

class MyApp extends StatefulWidget {
  MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      routes: {
        "HomePage": (context) => HomePage(),
        "ScreenOnePage": (context) => const ScreenPage(title: 'Video_Player bug | Screen One',),
        "ScreenTwoPage": (context) => const ScreenPage(title: 'Video_Player bug | Screen Two',),
      },
      home: HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  HomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const Column(
      children: [
        Text("Home Screen"),
        Flexible(child: ScreenPage(title: 'Video_Player bug | Screen One')),
      ],
    );
  }
}

class ScreenPage extends StatefulWidget {
  const ScreenPage({super.key, required this.title});
  final String title;

  @override
  State<ScreenPage> createState() => _ScreenPageState();
}

class _ScreenPageState extends State<ScreenPage> {
  late VideoPlayerController videoPlayerController;
  bool isPlaying = false;
  String filename = "test_video.mp4";
  String thumbnail = "test_thumbnail.PNG";

  @override
   void initState() {
    super.initState();

    videoPlayerController = VideoPlayerController.asset('assets/$filename');
    
    videoPlayerController.initialize().then((_) {
        if (mounted) {
          setState(() {});
          // videoPlayerController.setVolume(0); // if autoplaying must mute video
          // videoPlayerController.pause(); // auto pause video to fix iOS Safari web
        }
    });
  }

  @override
  void dispose() {
    super.dispose();
    videoPlayerController.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: isPlaying ? Container() :
       GestureDetector(
        onTap: () {
          setState(() {
            videoPlayerController.play();
            isPlaying = true;
          });
        },
         child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Stack(
                alignment: Alignment.center,
                children: [
                  Image.asset(
                    thumbnail,
                    width: 300,
                    height: 300,
                    fit: BoxFit.fill,
                  ),
                  const Icon(
                    Icons.play_arrow,
                    color: Colors.white,
                    size: 100.0,
                  )
                ],
              ),
              Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                Flexible(
                  child: IconButton(
                    onPressed:() {
                      pageName = "ScreenOnePage";
                      Navigator.pushNamed(context, pageName);
                    },
                    icon: Icon(
                      Icons.arrow_back,
                      color: Colors.black,
                      size: 40,
                      semanticLabel: 'Back $pageName',
                    )
                  ),
                ),
                Flexible(
                  child: IconButton(
                    onPressed:() {
                      pageName = "ScreenTwoPage";
                      Navigator.pushNamed(context, pageName);
                    },
                    icon: Icon(
                      Icons.arrow_forward,
                      color: Colors.black,
                      size: 40,
                      semanticLabel: 'Next $pageName',
                    )
                  ),
                ),
              ],)
            ],
         ),
       )
    );
  }
}


```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/7232060/6d018133-332d-48ac-9b85-92788f7b89ce

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.10.0, on Microsoft Windows [Version 10.0.22624.1755], locale en-US)
    • Flutter version 3.10.0 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (13 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\maylo\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.8.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.8.30717.126
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.70.0)
    • VS Code at C:\Users\maylo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.60.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22624.1755]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 113.0.5672.126
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 113.0.1774.50
    ! Device emulator-5562 is offline.

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @maylortaylor 
What is your current version of `video_player`? 

Also, in order to address the issue properly, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so that we may verify this. 

Thank you!

**Comment by maylortaylor** [comment]
> Hi @maylortaylor What is your current version of `video_player`?
> 
> Also, in order to address the issue properly, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so that we may verify this.
> 
> Thank you!

I am using version **2.6.1** and I will get you that code soon.

**Comment by maylortaylor** [comment]
> Hi @maylortaylor What is your current version of `video_player`?
> 
> Also, in order to address the issue properly, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so that we may verify this.
> 
> Thank you!

Okay I updated the original post to include a full working example. You will have to add your assets into a top-level **/assets** folder. I also only got this bug while testing it on iOS Safari on a phone. So to test it in the environment I had you will need to deploy it to Flutter Web or somehow navigate to the **localhost** test URL on your iOS phone using Safari.

**Comment by huycozy** [comment]
Thanks for your update. But the issue is not reproducible from my end after trying many times. Perhaps it only occurs in the scenario you described above with multiple screens? Can you provide a code sample corresponding to it?

**Comment by maylortaylor** [comment]
> Thanks for your update. But the issue is not reproducible from my end after trying many times. Perhaps it only occurs in the scenario you described above with multiple screens? Can you provide a code sample corresponding to it?

Okay - I have updated the original post's code to have multiple screens. It's ugly but and constantly uses "**pushNamed()**" to navigate to the next screen but this is essentially how my app works. (actually I have my videos inside a "card_swiper" flutter widget). I suspect maybe this could be the issue since the "card_swiper" plugin might have all the videos loaded on the screen at the same time.

**Comment by huycozy** [comment]
Thank you for the updated sample code. But the issue doesn't appear on my end with `iPhone 7, iOS 15.7.2` and Safari browser. 

<details>
<summary>Demo video</summary>

https://github.com/flutter/flutter/assets/104349824/2d6197ef-1b89-4375-8ccc-a90b016f552b
</details>

>I suspect maybe this could be the issue since the "card_swiper" plugin might have all the videos loaded on the screen at the same time.

Does the issue happen with above your minimal sample code (without using `card_swiper`)? If it doesn't happen and is only reproducible with `card_swiper`, I would recommend opening an issue on `card_swiper`'s repository for better support there.
