### ISSUE TITLE
Please support Chakma language as supported language

### ISSUE THREAD

**Issue by bksubhuti** [flutter/flutter#127317]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

There are about 550,000 people who are Chakma in the world.
We support many languages using your locale features l10n directory as described in the tutorials.

English, Myanmar, Sinhala, Vietnamese, Chinese, Hindi, Bengali
We make a tool for reading the Theravada Buddhist Language called Pāḷi and need to support asian languages.

It would be easier if you added this to a supported locale.
Then we could just add the ccp (chakma) locale tag as normal with other language locales.

We have a request to support Chakma language, but it is not on the supported list so I followed the instructions below for Norwegian and changed a few things.  
https://github.com/flutter/website/tree/main/examples/internationalization/add_language

I got it to work, but I'm getting warnings which doesn't affect usage, but affects peace of mind.  We have over 2000 users in Android and 300+ windows and also ship on Apple.

The error in the Debug Output is this for mac ios or windows (and probably android too).
```

════════ Exception caught by widgets ═══════════════════════════════════════════
The following message was thrown:
Warning: This application's locale, ccp, is not supported by all of its localization delegates.

• A CupertinoLocalizations delegate that supports the ccp locale was not found.

If the application is built using GlobalMaterialLocalizations.delegate, consider using GlobalMaterialLocalizations.delegates (plural) instead, as that will automatically declare the appropriate Cupertino localizations.
2

The declared supported locales for this app are: en, my, si, zh, vi, hi, ru, bn, ccp

See https://flutter.dev/tutorials/internationalization/ for more information about configuring an app's locale, supportedLocales, and localizationsDelegates parameters.
════════════════════════════════════════════════════════════════════════════════

```

I have added quite a few attempts to fix this, 
such as creating the custom class and adding it.
```
              localizationsDelegates: const [
                CcpMaterialLocalizations.delegate,
                AppLocalizations.delegate,
                ...GlobalMaterialLocalizations.delegates,
                GlobalWidgetsLocalizations.delegate,
                GlobalCupertinoLocalizations.delegate,
              ],

```

and also implementing CupertinoLocalizations as suggested from chatgpt (bard is still not so smart)

class CcpMaterialLocalizations extends GlobalMaterialLocalizations
    implements CupertinoLocalizations {
  const CcpMaterialLocalizations({

Our app is functional with all of this stuff.
Our app correctly Renders Chakma
There are about 550,000 people who are Chakma in the world.

It would be easier if you added this to a supported locale.  Therefore we request it.
Then we could just add the ccp locale tag as normal with other language locales.

### Proposal

If you support ccp Chakma locale life would be easier for us and other developers that specialize in Asian languages or Buddhist texts.  Then we could just add the local like the other languages as such:

```
class App extends StatelessWidget {
  //final List<AppTheme> themes = MyTheme.fetchAll();
  final String _enLocale = 'en';
  final String _myLocale = 'my';
  final String _siLocale = 'si';
  final String _zhLocale = 'zh';
  final String _viLocale = 'vi';
  final String _hiLocale = 'hi';
  final String _ruLocale = 'ru';
  final String _bnLocale = 'bn';
  final String _chakmaLocale = 'ccp';

  final StreamingSharedPreferences rxPref;

  const App({required this.rxPref, Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) => MultiProvider(
          providers: [
            Provider.value(
              value: rxPref,
            ),
            // placing at top of MaterialApp to access in differnt routes
            ChangeNotifierProvider<ThemeChangeNotifier>(
                create: (_) => ThemeChangeNotifier()),
            ChangeNotifierProvider<LocaleChangeNotifier>(
                create: (_) => LocaleChangeNotifier()),
            ChangeNotifierProvider<ScriptLanguageProvider>(
                create: (_) => ScriptLanguageProvider()),
            ChangeNotifierProvider<ReaderFontProvider>(
                create: (_) => ReaderFontProvider()),
            ChangeNotifierProvider<OpenningBooksProvider>(
                create: (_) => OpenningBooksProvider())
          ],
          builder: (context, _) {
            final themeChangeNotifier =
                Provider.of<ThemeChangeNotifier>(context);
            final localChangeNotifier =
                Provider.of<LocaleChangeNotifier>(context);
            return MaterialApp(
              debugShowCheckedModeBanner: false,
              themeMode: themeChangeNotifier.themeMode,
              theme: themeChangeNotifier.themeData,
              darkTheme: themeChangeNotifier.darkTheme,
              locale: Locale(localChangeNotifier.localeString, ''),
              onGenerateRoute: RouteGenerator.generateRoute,
              localizationsDelegates: const [
                CcpMaterialLocalizations.delegate,
                AppLocalizations.delegate,
                ...GlobalMaterialLocalizations.delegates,
                GlobalWidgetsLocalizations.delegate,
                GlobalCupertinoLocalizations.delegate,
              ],
              supportedLocales: [
                Locale(_enLocale, ''), // English, no country code
                Locale(_myLocale, ''), // Myanmar, no country code
                Locale(_siLocale, ''), // Sinahala, no country code
                Locale(_zhLocale, ''), // Chinese, no country code
                Locale(_viLocale, ''), // Vietnamese, no country code
                Locale(_hiLocale, ''), // Hindi, no country code
                Locale(_ruLocale, ''), // Russian, no country code
                Locale(_bnLocale, ''), // Bengali, no country code
                Locale(_chakmaLocale), // Chakma, //wished to be supported lang
              ],
              home: const SplashScreen(),
            );
          } // builder
          );
}


```

Our code is pushed to the repository:
https://github.com/bksubhuti/tipitaka-pali-reader
AppStore app id .. Tipitaka Pali Reader

Below is a picture of implemented Chakma
The error/warning message does not crash on Mac or iOS but shows up when Chakma Language is invoked.
![image](https://github.com/flutter/flutter/assets/18184280/058ac894-8f0d-4761-b671-ef239e095353)

**Comment by goderbauer** [comment]
Hello and thank you for the request. Sadly, we do not have resources to maintain languages that are not officially supported by Google.

**Comment by HridittwaChakma** [comment]
Sure
