### ISSUE TITLE
Can we customise the IndicatorShape in Flutter Navigation Rail 

### ISSUE THREAD

**Issue by subins829** [flutter/flutter#127390]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Need to customise the indicator shape in Navigation Rail

### Proposal

Need to customise the indicator shape in Navigation Rail

**Comment by danagbemava-nc** [comment]
Yes, you can customise the indicator shape. The `NavigationRail` widget has an indicatorShape property. See https://api.flutter.dev/flutter/material/NavigationRail/indicatorShape.html

If you are looking for something else, please provide more details in your issue.

Closing as this is already possible. 

Thank you
