### ISSUE TITLE
[CP] Fix macOS apps being rejected from app store

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#127350]
### issue_link

https://github.com/flutter/flutter/issues/126705

### Commit Hash

https://github.com/flutter/flutter/commit/7e1a0d4086b29ddaef8625c0be64e322e0c665e9

### Target

beta

### pr_link

https://github.com/flutter/flutter/pull/127349

### Impacted Users

Developers of macOS apps who want to publish

### Impact Description

Although the flutter macOS app will work locally, when submitting it to the app store the dev will be rejected saying the framework is invalid.

### Workaround

Manually deleting the entitlements.txt and without_entitlements.txt files from their build outputs.

### Risk

low

### Test Coverage

yes

**Comment by godofredoc** [comment]
CP: LGTM

**Comment by borjandev** [comment]
@godofredoc @christopherfujino did you guys verify that the rejection issue has been solved? I tried the TOT on master branch, which is c313083a884ea1399b8520b7c599dced4b583d56 at the moment, and still the same rejection happens. (unless I am missing some extra step?)

**Comment by godofredoc** [comment]
> 

Let's keep the conversation in the bug to simplify tracking.
