### ISSUE TITLE
 Linux_samsung_s10 new_gallery_impeller__transition_perf failing with infra failure with no steps/logs

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#127324]
https://ci.chromium.org/ui/p/flutter/builders/staging/Linux_samsung_s10%20new_gallery_impeller__transition_perf/4655/overview

**Comment by zanderso** [comment]
cc @yusuf-goog

**Comment by ricardoamador** [comment]
Rerunning this test is bringing the bots down.

**Comment by yusuf-goog** [comment]
@kentnguyen99 please check on the samsung s10 device connected to linux-26. It seems to be down. Please try to determine what the state is and check if there is any indication of what might have caused it. (any dialog on screen, power off etc.)

@zanderso there was a planned building power outage over the weekend, this could be the effect of that (especially if we find the device powered off).

**Comment by zanderso** [comment]
@yusuf-goog I saw the PSA last week. You might reply to that message with an update so that everyone knows the status.

**Comment by zanderso** [comment]
It looks like this test is passing now.
