### ISSUE TITLE
[core library] Iterable method first throws StateError, will returning null be more run time safe?

### ISSUE THREAD

**Issue by prashant-kellton2** [flutter/flutter#127389]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

```
  /// Returns the first element.
  ///
  /// Throws a [StateError] if `this` is empty.
  /// Otherwise returns the first element in the iteration order,
  /// equivalent to `this.elementAt(0)`.
  E get first {
    Iterator<E> it = iterator;
    if (!it.moveNext()) {
      throw IterableElementError.noElement();
    }
    return it.current;
  }
```

### Proposal

I would like to request a proposal of adding an additional method i.e firstOrNull, which would return null in case the iterable is empty

```
/// Returns the first element or null if this is empty.
/// Otherwise returns the first element in the iteration order,
/// equivalent to this.elementAt(0).
  E? get firstOrNull {
    Iterator<E> it = iterator;
    if (!it.moveNext()) {
      return null;
    }
    return it.current;
  }
```
as with this I won't have to worry about handling the StateError, now my only question is that will it be helpful to any other developer?

**Comment by danagbemava-nc** [comment]
Hi @prashant-kellton2, this is a dart language/sdk issue and should be reported on their repo. See https://github.com/dart-lang/language/issues/836 & https://github.com/dart-lang/sdk/issues/42947 for similar issues around this topic. 

Closing from here as this is out of scope for the flutter repo. 

Thank you
