### ISSUE TITLE
Devicelab linux 26 has been manually quarantined due to device not found

### ISSUE THREAD

**Issue by ricardoamador** [flutter/flutter#127326]
The device attached to flutter-devicelab-linux-26 might need to be physically restarted. A restart could not fix the issue and adb did not list any attached devices.

**Comment by kentnguyen99** [comment]
External connection to Android device has been restored. Devices is back online and ready for service, I rebooted both machine and Android device.

flutter@flutter-devicelab-linux-26:~$ adb devices
List of devices attached
RF8MB1350NT	device
