### ISSUE TITLE
[autosubmit] Do not remove label when mergability cannot be determined

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#127426]
Several autoroller PRs get stuck because GitHub cannot determine mergability at the given time. This is common when a recent PR has been submitted in the same minute that autosubmit checks mergability.

Instead, autosubmit should no-op, and wait for the next queue check for the PR.

```
auto label is removed for flutter/flutter, pr: 127411, Mergeability of pull request flutter/flutter/127411 could not be determined at time of merge..
```

**Comment by CaseyHillers** [comment]
\cc @ricardoamador

**Comment by justinmc** [comment]
I noticed that this happened here: https://github.com/flutter/flutter/pull/127019#issuecomment-1561801616

Just posting in case it's useful.

**Comment by ricardoamador** [comment]
This is fixed. The current method is to leave the label if the MergeableState is UNKNOWN and remove the label if the MergeableState is conflicting. These are the three states provided in the Graphql api.
