### ISSUE TITLE
When traffic data is enabled on the Google Maps Flutter. The areas without traffic have a green line

### ISSUE THREAD

**Issue by wazini-john** [flutter/flutter#127464]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I am using google_maps_flutter on my flutter app. But the areas without traffic have green polylines.
1. Can they be removed entirely ?
2. Can they be edited out using the map styles ?(If true, how can I remove them ?)

### Proposal

Remove them entirely by either mapstyles or give a choice of selecting the color

**Comment by darshankawar** [comment]
@wazini-john 
Can you provide an example using code sample that shows point number 1 and 2 as you mentioned (with screenshots) and what exactly are you  expecting  to happen ?
