### ISSUE TITLE
[CP] Fix macOS desktop builds being rejected by app store pt 2

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#127424]
### issue_link

https://github.com/flutter/flutter/issues/126705

### Commit Hash

https://github.com/flutter/flutter/commit/11cb29174f5b60b79bb79b816ee3241613ae41eb

### Target

beta

### pr_link

https://github.com/flutter/flutter/pull/127423

### Impacted Users

devs with macos apps who publish to the appstore

### Impact Description

App will be rejected by app store validation.

### Workaround

User can manually delete the entitlements files from the build directory.

### Risk

low

### Test Coverage

yes

**Comment by godofredoc** [comment]
CP LGTM
