### ISSUE TITLE
`flutter_desktop_darwin_unittests` is disabled in debug builds since it is flakey

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#127441]
I tried to turn `flutter_desktop_darwin_unittests` debug tests back on with all the other tests but it failed randomly.

Example failures: https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Engine%20Drone/196691/overview

Maintained disabled state in https://github.com/flutter/engine/pull/42261

This may be related to https://github.com/flutter/flutter/issues/127436 or https://github.com/flutter/flutter/issues/104789

**Comment by cbracken** [comment]
Deduplicating against #104789.
