### ISSUE TITLE
In a list, how to give a different style to "first" or "last" item

### ISSUE THREAD

**Issue by deborah-ufw** [flutter/flutter#12744]
In a List, we divide the items with a boxDecoration bottom border.

The last item in the list also has the border, but it looks funky. 

How can we remove the style for the last (or first) item?

Alternatively, how would a list be set up correctly to achieve the same effect?

![image](https://user-images.githubusercontent.com/378599/32080196-309573ce-ba63-11e7-8459-5a8442a0688c.png)

**Comment by Hixie** [comment]
If you are generating the list, you can make any item have whatever border you want. It's all just code.
