### ISSUE TITLE
[url_launcher] unable to load the url to open a publicly available application

### ISSUE THREAD

**Issue by muhammadmateen027** [flutter/flutter#127495]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Install the flutter version `3.7.12`
2. Add any version of `url_launcher` (I have tested with 6.1.11, 6.1.1)
3. add the below snippet to load the [URL](https://apps.apple.com/de/app/towio-messenger/id1562839005)
4. It is not able to open the app in Safari

### Expected results

url_launcher should open this screen:
<img width="1028" alt="image" src="https://github.com/flutter/flutter/assets/24449076/34fd05ad-de61-4273-b18e-73365c53492d">

### Actual results

![image](https://github.com/flutter/flutter/assets/24449076/97968126-e02e-4f53-b7a6-86b5ad91b705)

### Code sample

<details><summary>Code sample</summary>

```dart
try {
   await launchUrl(url.toUri());
} catch (e, s) {
   print(e);
   print(s);
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[log] PlatformException(Error, Error while launching https://apps.apple.com/de/app/towio-messenger/id1562839005, null, null)
[log] #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
<asynchronous suspension>
#2      WurthUrlLauncher.launchUri (package:photodoc/classes/wurth_url_launcher.dart:19:9)
<asynchronous suspension>
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.7.12, on macOS 13.0 22A380 darwin-arm64, locale en-DE)
    ! Warning: `dart` on your path resolves to /Users/mateen/flutter/bin/cache/dart-sdk/bin/dart, which is not inside your current Flutter SDK checkout at /Users/mateen/fvm/versions/3.7.12. Consider adding /Users/mateen/fvm/versions/3.7.12/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[!] Android Studio
    ✗ Unable to find bundled Java version.
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
[✓] VS Code (version 1.77.3)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 2 categories.
```

</details>

**Comment by stuartmorgan** [comment]
Exactly the same thing happens if you try to open that URL yourself in Safari; simulators don't have app store access. This is unrelated to the `url_launcher` plugin.
