### ISSUE TITLE
InputDecorator should allow a widget in the prefix area.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#12747]
One of our customers, mulligan, would like to have a leading pulldown menu on a text field.  This is hard to achieve if you would like to have the divider in the input decorator extend underneath the pulldown as well as the text input area.

I propose to add a prefixWidget (and suffixWidget) to InputDecoration that the InputDecorator would be able to place instead of the prefix text.  Of course, setting both prefixText and prefixWidget would not be allowed.

**Comment by HansMuller** [comment]
This makes sense and InputDecorator is already factored this way internally.

**Comment by zoechi** [comment]
This was fixed by #19514

**Comment by virgule-xyz** [comment]
Is there a way to have also a prefix/suffix for the InputDecoration in case of errors, like the errorText etc. ?

For example I have a TextInput that have a filled icon as prefix, and the icon need to be filled in red in case of error. Actually I can manage the border color and text color, but I have no access to the prefix and suffix :(
