### ISSUE TITLE
[Impeller] Add a fatal log if the iOS simulator does not support Metal.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#127408]
Some CI configurations may allow for the creation of [simulators without Metal access](https://github.com/flutter/flutter/issues/126768#issuecomment-1558338283). To prevent the  renderer from launching in an unsupported configuration, we should have a fatal log if the Metal device cannot be found.

**Comment by dnfield** [comment]
What happens if the user explicitly requested software rendering? See steps in https://github.com/flutter/flutter/issues/127500

**Comment by dnfield** [comment]
I agree we should make it fatal if the user/tool requested impeller and impeller can't run, but if we want to really make this always fatal then we have to remove the enable-software-rendering from the tool - or make that flag fatal as well.
