### ISSUE TITLE
flutter listen doesn't work if current directory doesn't have a "lib" subdirectory

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1274]
For example, go to `//flutter/examples/widgets` and run `flutter listen -t spinning_mixed.dart`.

**Comment by abarth** [comment]
flutter listen isn't a thing anymore

**Comment by abarth** [comment]
Oops, I was wrong.

**Comment by danrubel** [comment]
Subsumed by https://github.com/flutter/flutter/issues/6199 and the fact that [`flutter run` is now hot](https://github.com/flutter/flutter/issues/5280).
