### ISSUE TITLE
Next Gen UI demo crashes mobile browsers

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#127418]
The [next gen ui demo](https://flutter.github.io/samples/web/next_gen_ui_demo/) crashes the tab in both Chrome on Android and Safari on iOS.

Steps to reproduce:
  - Open https://flutter.github.io/samples/web/next_gen_ui_demo/ in your mobile browser of choice
  - Navigate the step 15 to kick in both shaders and animations
  - Leave open for a couple of minutes
  - Watch tab reload or crash

/cc @khanhnwin

**Comment by johnpryan** [comment]
I can reproduce the issue on iOS+Safari, but not Android+Chrome. On iOS, the app uses almost 1GB of memory before crashing:
![Screenshot 2023-05-23 at 2 40 36 PM](https://github.com/flutter/flutter/assets/1145719/ad264e9b-15e2-442e-bfa7-5727adfb1c24)

**Comment by domesticmouse** [comment]
Is there anything we are obviously leaking in the memory tooling? I don’t have the headspace to debug things with my jetlag

**Comment by eyebrowsoffire** [comment]
I noticed that something on the animation on this class is leaking listeners: https://github.com/flutter/codelabs/blob/7ed4d4ce2d2f0ec13746da661e1b163497fbd5a0/next-gen-ui/step_06/lib/title_screen/title_screen_ui.dart#L255

In the debugger I see it notifying status listeners and there are thousands of listeners registered.

**Comment by CoderDake** [comment]
It might be possible to use [dart-lang/leak_tracker](https://github.com/dart-lang/leak_tracker/blob/main/doc/TROUBLESHOOT.md) to target a potential memory leak. It is quite new, so I'm sure @polina-c would love feedback on your experience using it too.

**Comment by domesticmouse** [comment]
> It might be possible to use [dart-lang/leak_tracker](https://github.com/dart-lang/leak_tracker/blob/main/doc/TROUBLESHOOT.md) to target a potential memory leak. It is quite new, so I'm sure @polina-c would love feedback on your experience using it too.

Looks like this code is leaking enough to cause `leak_tracker` to fail in an unintended manner:

```console
flutter: leak_tracker: 3169 memory leak(s): not disposed: 3169, not GCed: 0, GCed late: 0
flutter: leak_tracker: 3229 memory leak(s): not disposed: 3229, not GCed: 0, GCed late: 0
flutter: leak_tracker: 3289 memory leak(s): not disposed: 3289, not GCed: 0, GCed late: 0
flutter: leak_tracker: 3349 memory leak(s): not disposed: 3349, not GCed: 0, GCed late: 0
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:leak_tracker/src/leak_tracking/_object_record.dart': Failed assertion: line 48 pos 14: '!notGCed.containsKey(code)': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      ObjectRecords._assertNotWatched.<anonymous closure> (package:leak_tracker/src/leak_tracking/_object_record.dart:48:14)
#3      ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#4      ObjectRecords.assertIntegrity.<anonymous closure> (package:leak_tracker/src/leak_tracking/_object_record.dart:77:47)
#5      ObjectRecords.assertIntegrity (package:leak_tracker/src/leak_tracking/_object_record.dart:80:6)
#6      ObjectTracker._checkForNewNotGCedLeaks (package:leak_tracker/src/leak_tracking/_object_tracker.dart:164:14)
#7      ObjectTracker.leaksSummary (package:leak_tracker/src/leak_tracking/_object_tracker.dart:154:5)
#8      LeakChecker.checkLeaks (package:leak_tracker/src/leak_tracking/_leak_checker.dart:55:34)
#9      new LeakChecker.<anonymous closure> (package:leak_tracker/src/leak_tracking/_leak_checker.dart:26:63)
#10     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#11     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#12     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
```

**Comment by domesticmouse** [comment]
I've got a PR that adds `leak_tracker`, but I'm unsure how to fix the outstanding leaks of `Picture`s. Halp?

PR: https://github.com/flutter/samples/pull/1851

**Comment by polina-c** [comment]
Use the example in leak traker test: https://github.com/dart-lang/leak_tracker/blob/main/test/flutter/leak_tracking/end_to_end_test.dart , to test cover you leaking widgets for leaks.

To investigate non-disposed leaks, temporary enable collection of stack trace on tracking start in LeakTrackingTestConfig.

**Comment by jonahwilliams** [comment]
I'm skeptical that we're going to find an easy fix for this bug with the leak tracker. The performance/memory implications of toImageSync on the web are known to be terrible and I don't think we're going to be able to work around it .

**Comment by kevmoo** [comment]
@jonahwilliams – I'm seeing crashing and memory crazy on native, too. I think there IS an issue w/ the demo, aside from the `toImageSync` bits

**Comment by jonahwilliams** [comment]
that would be more telling!

**Comment by domesticmouse** [comment]
I have https://github.com/flutter/samples/pull/1851 which adds `leak_tracker` which shows we are leaking `Picture`s, which I believe are being leaked from @jonahwilliams' shader code. I have added `dispose()` calls in various places to clean up things, including https://github.com/gskinnerTeam/flutter-focusable-control-builder/pull/5

**Comment by kevmoo** [comment]
focusable_control_builder 1.0.2 is out w/ the fix here!

**Comment by yjbanov** [comment]
> focusable_control_builder 1.0.2 is out w/ the fix here!

Has it landed? Can we close?

**Comment by domesticmouse** [comment]
The `focusable_control_builder` patch fixed an issue with leaking focus nodes, but it doesn't deal with leaking `Picture`s in the sample code that I don't have a fix for. I'll go ahead and close this now as we are going to delete this sample after the I/O Connect event in China
