### ISSUE TITLE
Switch to IKG file tracking from analyzer when in `--preview-dart-2`

### ISSUE THREAD

**Issue by aam** [flutter/flutter#12745]
IKG has an API to report list of files used for compilation as well as incremental updates to that list. Flutter tools should use that instead of analyzer (https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/dart/dependencies.dart).

Note that IKG API will be used to provide list of files when it is loaded from [File]ByteStore. @scheglov

**Comment by aam** [comment]
@a-siva

**Comment by scheglov** [comment]
Honestly, I don't understand the comment about `ByteStore`.
Cache is important for performance, but information is provided either way, cached or not.

I agree withe the goal of the issue of course - it is better to use one system to get all information.

**Comment by aam** [comment]
@scheglov, Flutter tools needs to start tracking sources files that comprise the dart app. This list should be coming from IKG instead of analyzer. Currently we get that list before we do kernel generation, so the thinking is that there should be a way to get list of files known to IKG after [we create new instance of IKG](https://github.com/dart-lang/sdk/blob/master/pkg/front_end/lib/incremental_kernel_generator.dart#L138).

On other hand, we might say that the list of dart sources will be provided by IKG first time we actually do the kernel generation. I think this is what IKG API currently provides, which probably will be acceptable too, but will require more refactoring on Flutter tools side to support old and new ways of doing things(with and without `--preview-dart-2` flag).

**Comment by a-siva** [comment]
@scheglov  to answer your question about the comment on ByteStore we wanted to make sure that IKG will be able to provide us this list of files even in the case when it comes up first by reading the full state from the FileStore (the case of 'flutter build' to 'flutter run' transition).

**Comment by scheglov** [comment]
OK, understood.
Yes, it will.

**Comment by aam** [comment]
cc @askeksa-google @kmillikin - this needs to be addressed to remove dependency on analyzer to produce list of files that have to be tracked for hot-reload in Flutter.

**Comment by jonahwilliams** [comment]
This was completed earlier this year
