### ISSUE TITLE
[Linux] Migrate up_client_get_devices to up_client_get_devices2 in platform channels example

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#127506]
[`up_client_get_devices`](https://upower.freedesktop.org/docs/UpClient.html#up-client-get-devices) was deprecated in libupower 0.99.8. Migrate to `up_client_get_devices2` when it's available on all the bots.

Our current Linux fleet runs on a mix of Linux releases:
* Prod: Focal with libupower 0.99.11 which deprecates `up_client_get_devices` and includes `up_client_get_devices2`.
* Trybots: Bionic with libupower 0.99.7 which does not deprecate `up_client_get_devices` and does not include `up_client_get_devices2`.

Until the bots are all migrated, we make the call to `up_client_get_devices` and ignore deprecations. Once the migration has completed, I'll update the call to the new one.

**Comment by yusuf-goog** [comment]
Fix is kicked off on a focal machine: https://chromium-swarm.appspot.com/task?id=6267b5f00b601610

**Comment by yusuf-goog** [comment]
Setting as P0 because the tree is currently red. Fix is running right now.

**Comment by godofredoc** [comment]
@yusuf-goog I believe we can close this bug, am I right?

**Comment by yusuf-goog** [comment]
Yes, this is good to go, fix is in and tree is green.
