### ISSUE TITLE
Firebase codelab has confusingly worded pre-reqs

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#12755]
The prereqs are confusingly stated. The first two bullets say "an IntelliIDE" is required, but the next paragraps says you can use an IntelliJ IDE or Android Studio.

This bug was found during a "dryrun" of the Firebase codelab in AAR by @floitschG, @mravn-google, and @mit-mit.

**Comment by LarkAscending** [comment]
@sethladd 

What I thought when I saw this text is `oh, right, Android Studio is an IntelliJ IDE`...
