### ISSUE TITLE
CP template no longer in list of issue templates

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#127592]
It looks like after https://github.com/flutter/flutter/pull/127507, the CP template is no longer in the list at https://github.com/flutter/flutter/issues/new/choose

**Comment by CaseyHillers** [comment]
```
YAML syntax error: (): could not find expected ':' while scanning a simple key at line 12 column 1. [Learn more about this error.](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/common-validation-errors-when-creating-issue-forms)
```

Would be great if GitHub linted these types of issues. I'm not seeing this one in the linter I'm using.
