### ISSUE TITLE
[Impeller] Engine gets confused when enable_impeller and enable_software_rendering are both true.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#127500]
Steps:

Create an app that displays an image.

Open a simulator.

Run `flutter run --enable-software rendering`.

The image will fail to render.

This has the same root cause as https://github.com/flutter/flutter/issues/126768#issuecomment-1558165539

IMHO we need the following:

- Better runtime behavior when enable_impeller is true but impeller can't/won't be enabled (because no valid MTLDevice is available or because the user explicitly requested software rendering).
- Better behavior in the tool when a user requests both impeller (implicitly or explicitly) and software rendering (explicitly).

**Comment by dnfield** [comment]
After @jason-simmons' patch, at least we get a better error message now:

```

══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following _Exception was thrown resolving an image frame:
Exception: No Impeller context is available

When the exception was thrown, this was the stack

Image provider: AssetImage(bundle: null, name: "csl.webp")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#e566b(), name: "csl.webp", scale: 1.0)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by JAicewizard** [comment]
I also get `Exception: No Impeller context is available` when running tests with the simple command `flutter test integration_test/main.dart -r expanded`, so with impeller enabled but no software rendering as far as I am aware (however the emulator runs in github CI, so it could be that the emulator forces software rendering on impeller?)

**Comment by dnfield** [comment]
Make sure you are using a recent macOS image - older github CI actions don't have GPU passthrough enabled.

**Comment by JAicewizard** [comment]
We are using `macos-latest` which is 12.6.6, I also cant find anything on github CI actions having GPU pass-through at all though.

**Comment by juanleondev** [comment]
I'm using CircleCI wit xcode 13.3.0 and also getting 
`Exception: No Impeller context is available`

**Comment by ekuprel** [comment]
I see the same thing with latest flutter-dart versions running on Ventura.  It stopped working when I recently upgraded to latest MacOS

XCode: Version 14.3.1 (14E300c)
Dart:  Dart 3.0.6 (stable) (Tue Jul 11 18:49:07 2023 +0000) on "macos_x64"

**flutter doctor**
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F770820d darwin-x64, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.80.0)
[✓] Connected device (3 available)
[✓] Network resources

**flutter pub outdated**
Showing outdated packages.
[*] indicates versions that are not the latest available.

Package Name  Current  Upgradable  Resolvable  Latest  

direct dependencies:
intl          *0.18.0  *0.18.0     *0.18.0     0.18.1  

dev_dependencies: all up-to-date.
You are already using the newest resolvable versions listed in the 'Resolvable' column.
Newer versions, listed in 'Latest', may not be mutually compatible.

**Code:**
 DrawerHeader(
                child: emptyWidget,
                decoration: BoxDecoration(
                    color: Colors.blue,
                    image: DecorationImage(
                        image: AssetImage("images/drawer-header.png"),
                        fit: BoxFit.cover)),

**Comment by rishabhsharma3617** [comment]
I am getting the same one on 3.10.4 and on the ios versions < 14, is there any workaround to this other than disabling impeller engine ?
I also have opened a new issue for the same - 
https://github.com/flutter/flutter/issues/134273
<img width="329" alt="Screenshot 2023-09-08 at 11 00 55 AM" src="https://github.com/flutter/flutter/assets/41324252/3f8b67a9-40fe-43ca-869b-f81fffde44e4">

**Comment by dnfield** [comment]
This is no longer possible - the engine now crashes in this scenario.
