### ISSUE TITLE
OutlinedButton within a SelectionArea widget shows selection cursor instead of clickable cursor

### ISSUE THREAD

**Issue by jpiabrantes** [flutter/flutter#127578]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Place an `OutlinedButton` within a `SelectionArea` widget.

### Expected results

When hovering the text of the OutlinedButton I expect to see the clickable cursor.

### Actual results

I see instead the selection cursor (see screenshot bellow).

### Code sample

<details><summary>Code sample</summary>

```dart
SelectionArea(
child: OutlinedButton(
                onPressed: () => {},
                child: Text('Encontrar Semelhantes',
                    style: TextStyle(color: Colors.white)),
              ),
)
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

<img width="1440" alt="Screenshot 2023-05-25 at 13 47 55" src="https://github.com/flutter/flutter/assets/2369107/b20618d6-c88e-4091-b52d-a58f5980b5b8">

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.1, on macOS 13.2 22D49 darwin-arm64, locale
    en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.2)
[✓] IntelliJ IDEA Community Edition (version 2021.2.4)
[✓] VS Code (version 1.76.2)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @jpiabrantes, this was initially reported in https://github.com/flutter/flutter/issues/104595 and has since been fixed on the master channel. 

Per our triage policy, I'll be closing this since it has already been fixed on the master channel. If you face this issue on the master channel, kindly provide the version of the master channel you used and I will reopen this issue. 

Thank you
