### ISSUE TITLE
Generated Podfile should include boilerplate for manual additions

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#12754]
The Podfile we generate should include boilerplate for manual additions.

Originally reported by @frederickcook via StackOverflow:
https://stackoverflow.com/questions/45410906/import-cocoapods-pod-for-ios-with-flutter

**Comment by iapicca** [comment]
Hi @cbracken  is this issue still meant to be open?

**Comment by xster** [comment]
It is. The default Podfile template is still not friendly to users wanting to add some custom entries into its dependencies.

**Comment by jmagman** [comment]
I'd like to close this in favor of https://github.com/flutter/flutter/issues/45197.  Then everything in the Podfile would be for manual additions and never need to be overwritten, and it would just call some Ruby method that handles all the Flutter-related pod logic.

**Comment by jmagman** [comment]
Re-open if you think we would still want boilerplate for manual additions in conjunction with https://github.com/flutter/flutter/issues/45197.
