### ISSUE TITLE
Firebase codelab should suggest a single, fixed code starting point

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#12756]
re: https://codelabs.developers.google.com/codelabs/flutter-firebase/#2

The code lab suggest that a developer can start by doing one of the following:

1. From a prior completion of Friendlychat
1. By downloading https://github.com/flutter/friendlychat-steps/tree/master/full_steps/step_0_offline
1. By doing `flutter create` and then patching `main.dart` with https://raw.githubusercontent.com/flutter/friendlychat-steps/master/full_steps/step_0_offline/lib/main.dart.

We don't think option 1 is a good suggestion: You never know what state the developer might be in after completing Friendly chat. It's very important in codelabs that all developers start from exactly the same state.

We don't think option 3 is a good suggestion: If you use those steps, the code doesn't pass analysis (the tests created by `flutter create` refer to different types than the ones in the patched file), and further `flutter create` is a moving target, and it's better for the codelab to be fixed.

We suggest we only list option 2.

This bug was found during a "dryrun" of the Firebase codelab in AAR by @floitschG, @mravn-google, and @mit-mit.

**Comment by collinjackson** [comment]
We originally switched to option 3 because the template in friendlychat-steps kept getting out of date with flutter's alpha branch, and it seemed better for developers to start the codelab with a fairly recent template. I'm fine with option 2, but we should probably have someone owning the process of updating the codelab templates periodically.

**Comment by LarkAscending** [comment]
Thanks for this suggestion! Very interesting points.

Are there examples of _You never know what state the developer might be in after completing Friendly chat._ ?? The codelabs are designed to fit together and be done in sequence. I've never heard of or encountered issues with doing that and would like to understand more...

Re: _the code doesn't pass analysis_ this is actually an issue that's being fixed: https://github.com/flutter/flutter-intellij/issues/1429

**Comment by mit-mit** [comment]
I don't agree the linked bugs suggest the issue is being fixed. After the paste, the app is not correct: it has a non passing test. That is an error, not a warning.

**Comment by mit-mit** [comment]
About the state question: our main concern is developers who didn't complete the prior codelab completely. But I agree that's a bit speculatory.

**Comment by collinjackson** [comment]
I'll defer to Elaine on whether to keep option 3 or not, but if we want to keep it, we could add a sentence suggesting that they comment out the automatically generated `test/widget_test.dart`.

**Comment by LarkAscending** [comment]
Removed 3. and added the following note to 4. Open Friendlychat in IntelliJ:
If your project includes a `test` directory that contains the file `widget_test.dart`, remove this file before continuing.
