### ISSUE TITLE
Firebase codelab has incorrectly formatted instruction

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#12759]
RE: https://codelabs.developers.google.com/codelabs/flutter-firebase/#5

The line "Modify the signature of `_handleSubmitted()to` indicate " should be changed to "Modify the signature of `_handleSubmitted()` to indicate "

This bug was found during a "dryrun" of the Firebase codelab in AAR by @floitschG, @mravn-google, and @mit-mit.

**Comment by LarkAscending** [comment]
Fixed.
