### ISSUE TITLE
[autosubmit] landing release prs hourly

### ISSUE THREAD

**Issue by XilaiZhang** [flutter/flutter#127522]
context: https://github.com/flutter/flutter/pull/127507

During releases, sometimes release engineers merge in 10+ cherry picks in a single day, and post submit tests would take a non trivial amount of time to finish. This could cause delays in release and extra babysitting for the release engineers. 

Would be great if auto submit could land release prs automatically on an hourly basis. (release engineers might still need to check dashboard periodically to ensure there are no breakages)

**Comment by XilaiZhang** [comment]
cc @CaseyHillers @ricardoamador

**Comment by ricardoamador** [comment]
I will take a look!

**Comment by XilaiZhang** [comment]
Thank you Ricardo!

**Comment by godofredoc** [comment]
@XilaiZhang with the autosubmit working on release candidate branches cherry pick owners should be landing the CPs themselves.

@itsjustkevin can we update the process docs to ask CP owners to add the label after getting approval?

**Comment by XilaiZhang** [comment]
Thanks for explaining! Yeah an announcement to cp authors would be great. in most of my rotations it seems like I was merging in all cps at once

**Comment by CaseyHillers** [comment]
/cc @itsjustkevin 

We want to make it so that release PRs require an approval from the release team before they submit, so I'm not sure we want to announce CP authors to use autosubmit.

Kevin, do you have links to the infra tickets to restrict release PRs to require review by the release team?

**Comment by itsjustkevin** [comment]
@godofredoc i am worried that requesters may start labeling before approval is gained.  

@CaseyHillers i have it for action on my list to input those infra tickets we discussed.

**Comment by godofredoc** [comment]
If we are expecting approvals from release eng, maybe we can add something to branch protection the drawback is that it will also block approvals on patches to release candidate branches during 1P rolls.

**Comment by godofredoc** [comment]
@XilaiZhang should we close this bug as obsolete?

**Comment by XilaiZhang** [comment]
feel free to close it.

Thanks Kevin and Casey for diligently merging cp prs! (yeah haven't seen 10+ unmerged cp prs recently)

**Comment by ricardoamador** [comment]
Psssh Autosubmit for the win!
