### ISSUE TITLE
Emit CocoaPods #include in Debug.xcconfig, Release.xcconfig

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#12752]
CocoaPods 1.3.1 emits the following warnings when the Pods-Runner xcconfig is included in `Generated.xcconfig`, rather than directly in `Debug.xcconfig` or `Release.xcconfig`:

```
[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig` or include the `Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig` in your build configuration (`Flutter/Debug.xcconfig`).
```

Ideally Debug.xcconfig should contain:
```
#include "../Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig"
```

And Release.xcconfig should contain:
```
#include "../Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig"
```

**Comment by daniele777** [comment]
help i have this warning

nclude the `Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig` in your build configuration (`Flutter/Debug.xcconfig`).

using pod install in windows how to solve??? thx
