### ISSUE TITLE
Flutter iOS build should check that ARCHS is arm64 only

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#12753]
## Steps to Reproduce

1. Use `flutter create` to create a new Flutter app.
2. In Xcode select the `Runner` project, then select the `Runner` target from the configuration sidebar. Then select the `Build Settings` tab. Then change `Architectures` to be `Standard architectures` (which includes armv7).
3. Build the project, then select Product > Archive.

The build will fail with linker errors since Flutter.framework only includes `arm64` (64-bit device) and `x86_64` (simulator) architectures. Until #2089 is implemented, Flutter is not able to build `armv7` builds. 

We should attempt to identify if `armv7` is included in the architectures list and if so, emit an actionable error message that requests the user configures the architecture settings to those supported by Flutter:

![screen shot 2017-10-26 at 18 16 33](https://user-images.githubusercontent.com/351029/32083738-e3fd7c66-ba79-11e7-9790-4d53a27ef35f.png)

**Comment by zoechi** [comment]
Is this still an issue? Is this still blocked?

**Comment by xster** [comment]
Not true anymore since we did #2089
