### ISSUE TITLE
flutter listen restarts the app when the IDE creates a temporary file

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1275]
For example, if you happen to open a file and start editing it, if your IDE creates a .# lock file, it'll cause the app to reload. We should only reload when "real" changes are made (not lock files, backup files, etc).

**Comment by eseidelGoogle** [comment]
@jason-simmons hit this when he tried to use `flutter listen` with vim today as well.

**Comment by eseidelGoogle** [comment]
FYI @devoncarew and @johnmccutchan, we'll likely hit this when wiring up your new hot code support.

**Comment by spierce7** [comment]
I'm seeing this a lot on IntelliJ. `flutter listen` will trigger a build when I change window focus. I'm assuming IntelliJ is modifying one of it's project files.

**Comment by sethladd** [comment]
@devoncarew what's the plan with `flutter listen` ?

**Comment by devoncarew** [comment]
I would like to roll this into flutter run (the --resident version). It should watch the file system and notify the user when there are changed files. An additional cli arg (`--watch`? `--auto`?) would be available which would automatically re-start the app in changes.

@Hixie for thoughts

**Comment by Hixie** [comment]
SGTM

**Comment by danrubel** [comment]
Subsumed by https://github.com/flutter/flutter/issues/6199 and the fact that [`flutter run` is now hot](https://github.com/flutter/flutter/issues/5280).
