### ISSUE TITLE
Flutter Video Player - Android Controller input gets stuck on on pressing left key (dpad left key)

### ISSUE THREAD

**Issue by sa1dude23** [flutter/flutter#127581]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Flutter video player is not accepting any input from Android Controller or Physical or Logical Keyboard when arrow left key is pressed.

`I/flutter (10294): RawKeyDownEvent#23f68(logicalKey: LogicalKeyboardKey#860f3(keyId: "0x100000302", keyLabel: "Arrow Left", debugName: "Arrow Left"), physicalKey: PhysicalKeyboardKey#52951(usbHidUsage: "0x00070050", debugName: "Arrow Left"), repeat: false)`
It do not print anything in log after left key is pressed.

Once the left key is  pressed the player does not accept any input unless I press Right key and everything gets to normal

### Expected results

The Inputs should not get stuck

### Actual results

The Inputs are getting stuck and not able to do anything in player till right key is pressed

### Code sample

<details><summary>Code sample</summary>

```dart
 FireTVRemoteListener(
                      onUp: () => '',
                      onDown: () => '',
                      onLeft: ()  {

                        setState(() {
                          isBackward = true;
                          _controller.seekTo(Duration(seconds: _controller.value.position.inSeconds - 4));
                          isBackward = false;
                        }
                        );
                      },
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>
```console
I/flutter (10294): RawKeyDownEvent#23f68(logicalKey: LogicalKeyboardKey#860f3(keyId: "0x100000302", keyLabel: "Arrow Left", debugName: "Arrow Left"), physicalKey: PhysicalKeyboardKey#52951(usbHidUsage: "0x00070050", debugName: "Arrow Left"), repeat: false)[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.5, on Microsoft Windows [Version 10.0.19045.2965], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)                       
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.3)
[√] Connected device (4 available)
[√] HTTP Host Availability


</details>
```

**Comment by darshankawar** [comment]
Thanks for the report @sa1dude23 
Are you trying to use the video player on Android TV or using emulator or physical device on which this behavior is occuring ?

Also, can you upgrade to latest stable or latest master version and run your scenario again to see if the issue still persists or not ?

**Comment by sa1dude23** [comment]
It is happening for Android TV - Both Actual TV and Emulator. Tried with both DEBUG and RELEASE builds.

Regarding the upgrade part I will test it today and post you an update.
