### ISSUE TITLE
Replace ChangeNotifier with ValueNotifier in codelab

### ISSUE THREAD

**Issue by polina-c** [flutter/flutter#127596]
https://codelabs.developers.google.com/codelabs/flutter-codelab-first#0
https://github.com/flutter/codelabs/tree/main/namer

The lab uses ChangeNotifier to listen for the changes. Nowadays ValueNotifier<WordPair> is lighter and easier option to listen to changes.

**Comment by polina-c** [comment]
@domesticmouse

**Comment by domesticmouse** [comment]
Hey @filiph is this something you'd like to take on, or should I handle?

**Comment by domesticmouse** [comment]
Digging into this and I noticed that the `ChangeNotifier` derived `MyAppState` object contains two pieces of state: 

  - `current` of type `WordPair`
  - `favorites` of type `<WordPair>[]`

While we could munge these two objects together with a record to shove it inside a `ValueNotifier`, the `favorites` is a mutable list, which makes this a bad fit which ever way you dice this onion.

Closing this as a bad fit.

**Comment by filiph** [comment]
First of all, sorry for the late reply! I'm a bit all over the place these days, unfortunately.

Second, thanks @polina-c for the suggestion and @domesticmouse for the reply.

I agree that `ValueNotifier` would be lighter, but as @domesticmouse says, it loses its simplicity when there are several things to keep track of. Suddenly, we would be telling newcomers to Flutter to create several valuenotifiers, provide them separately, and do things like `someState.value = blah` (explaining setters in the process). Also, as @domesticmouse says, mutable lists don't work as expected with `ValueNotifier` — we'd have to introduce something like `UnmodifiableListView`, which again is something newcomers can easily wait to learn much later.
