### ISSUE TITLE
TextField Keyboard Arrow Up & Down Misbehavior

### ISSUE THREAD

**Issue by selvam920** [flutter/flutter#127557]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

When you press arrow up or down key in windows textbox there is no action in the textbox but in flutter textfield moving cursor back or forward position.

### Expected results

No action for up and down arrow keys

### Actual results

moving cursor

### Code sample

TextField()

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.10.2, on Microsoft Windows [Version 10.0.22621.1702], locale en-US)
[✓] Windows Version (Installed version of Windows is version 10 or higher)

**Comment by selvam920** [comment]
can you check windows notepad, if one line and clicking up or down arrow there is no action means no cursor movement and more than two line up or down arrow moving cursor previous line or next line.

**Comment by huycozy** [comment]
I see the difference between Flutter Windows app and Notepad app. 

But Notepad++ and VSCode do the same as Flutter. Checking this on macOS's app (TextEdit/Sublime Text) also have the same behavior with Flutter and Notepad++ on Windows. So I think this is intended behavior.

I'm not sure if there is any specs or design document for the behavior you described. If you know, please share it here. Thank you!

**Comment by selvam920** [comment]
can you check windwos desktop app textbox?

**Comment by huycozy** [comment]
@selvam920 I'm not very familiar with .Net. Is its behavior as you expect?

I'm still looking forward to what is pointed out in https://github.com/flutter/flutter/issues/127557#issuecomment-1563811587 (specs, design, etc). This may be a proposal but perhaps the relevant documents should be considered.

**Comment by szetakyu** [comment]
Any progress? I face the same problem. I need to get rid of this.

**Comment by selvam920** [comment]
@huycozy  how to disable default behavior? bcoz whenever arrow up or down changing the selected index in the list view

**Comment by huycozy** [comment]
@szetakyu Can you take a look at above comments and please share more ideas about this?

>bcoz whenever arrow up or down changing the selected index in the list view

@selvam920 Can you please share a minimal sample code for this issue?

**Comment by szetakyu** [comment]
I do not think it is a problem for me now. I used the TextEditingController example (https://api.flutter.dev/flutter/widgets/TextEditingController-class.html#:~:text=A%20controller%20for%20an%20editable%20text%20field.%20Whenever,updates%20value%20and%20the%20controller%20notifies%20its%20listeners.) and get rid of the default behaviour.
