### ISSUE TITLE
Firebase instruction for SDK manager is incorrect in Android Studio 3.0

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#12758]
RE: https://codelabs.developers.google.com/codelabs/flutter-firebase/#4

The instruction says SDK manager is under: **Android Studio > SDK Manager**

In Android Studio 3.0 it's under: **Tools > Android > SDK Manager**

This bug was found during a "dryrun" of the Firebase codelab in AAR by @floitschG, @mravn-google, and @mit-mit.

**Comment by LarkAscending** [comment]
Are we moving away from describing the steps in the Welcome screen (faster) to the main AS menu? We chose this approach before I/O... IIRC the reasoning was AS takes a long time to launch and even after launch there is an additional delay before the Tools menu gets populated. I believe Gradle has to initialize. At least it was common after starting AS to go to **Tools** and not see any **Android** submenu...

**Comment by mit-mit** [comment]
Oh, that explains it.

I think we should describe both UI paths. Lots of potential Flutter Devs will have AS running already.

**Comment by LarkAscending** [comment]
This is new info...the codelab users are likely to already have AS running?

We can advertise both UI paths - but is it helpful? (There's a 3rd way, too, from the command line). In documentation, generally it's better to pick one way and go with it. More ways to do something != better, especially when it's not your product.

**Comment by LarkAscending** [comment]
Picked this way: **Android Studio > Tools > Android > SDK Manager > SDK Tools**
