### ISSUE TITLE
HarmonyOS 3.0.0.212 Serious Bug！！！

### ISSUE THREAD

**Issue by WJHCode** [flutter/flutter#127556]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1、调用bool resull = await LocalAuthentication().authenticate(localizedReason: 'localizedReason')
2、在弹出系统指纹识别弹窗后点击取消；
3、多次重复步骤2，result返回true。

### Expected results

1、调用bool resull = await LocalAuthentication().authenticate(localizedReason: 'localizedReason')
2、在弹出系统指纹识别弹窗后点击取消；
3、多次重复步骤2，result返回true。

### Actual results

1、调用bool resull = await LocalAuthentication().authenticate(localizedReason: 'localizedReason')
2、在弹出系统指纹识别弹窗后点击取消；
3、多次重复步骤2，result返回true。

### Code sample

1、调用bool resull = await LocalAuthentication().authenticate(localizedReason: 'localizedReason')
2、在弹出系统指纹识别弹窗后点击取消；
3、多次重复步骤2，result返回true。

### Screenshots or Video

1、调用bool resull = await LocalAuthentication().authenticate(localizedReason: 'localizedReason')
2、在弹出系统指纹识别弹窗后点击取消；
3、多次重复步骤2，result返回true。

### Logs

1、调用bool resull = await LocalAuthentication().authenticate(localizedReason: 'localizedReason')
2、在弹出系统指纹识别弹窗后点击取消；
3、多次重复步骤2，result返回true。

### Flutter Doctor output

1、调用bool resull = await LocalAuthentication().authenticate(localizedReason: 'localizedReason')
2、在弹出系统指纹识别弹窗后点击取消；
3、多次重复步骤2，result返回true。

**Comment by huycozy** [comment]
Hi @WJHCode 
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly (See appropriate template [here](https://github.com/flutter/flutter/issues/new/choose))

And unfortunately, I am not familiar with Chinese. So please try to describe the issue in English so we can identify it properly (using Google translate may not be accurate)

**Comment by stuartmorgan** [comment]
HarmonyOS isn't one of Flutter's supported platforms. If there are issues with its ability to run Android applications well, you'd need to report that to the OS developers.
