### ISSUE TITLE
Camera_windows changing resolution selection does not affect file size

### ISSUE THREAD

**Issue by Jsnt1004** [flutter/flutter#127674]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Select Medium resolution from your example app and a photo shows on my filesystem as 1920x1280 and 331kb jpeg, 10 seconds of MP4 video is 28.8Mb...changing resolution to Max gives new files with the same sizes and resolutions despite the resolution being correctly set in createCamera with _serializeResolutionPreset(resolutionPreset)

Checking with the windows camera app gives 134kb and 2.37Mb when set on Medium (also jpeg and MP4) so it seems that the resolutionpreset isn't working correctly

### Expected results

resolutionPreset should actually change the resolution and give broadly similar results to the default windows camera.  

### Actual results

Select Medium resolution from your example app and a photo shows on my filesystem as 1920x1280 and 331kb jpeg, 10 seconds of MP4 video is 28.8Mb...changing resolution to Max gives new files with the same sizes and resolutions despite the resolution being correctly set in createCamera with _serializeResolutionPreset(resolutionPreset)

Checking with the windows camera app gives 134kb and 2.37Mb when set on Medium (also jpeg and MP4) so it seems that the resolutionpreset isn't working correctly...whether that is just by accident or not I don't know since as you will see from the screenshots Microsoft can't get the resolutions in order.  The photo resolution does not correlate to the resolutionPresets whilst the video does (albeit with no Low resolution mode available and the rear camera mirrored-but I have a code to correct that)  

### Code sample

<details><summary>Code sample</summary>

```dart
Select Medium resolution from your example app and a photo shows on my filesystem as 1920x1280 and 331kb jpeg, 10 seconds of MP4 video is 28.8Mb...changing resolution to max gives new files with the same sizes and resolutions despite the resolution being correctly set in createCamera with _serializeResolutionPreset(resolutionPreset)

Checking with the windows camera app gives 134kb and 2.37Mb when set on Medium (also jpeg and MP4) so it seems that the resolutionpreset isn't working correctly
```

</details>
//use your own example code!

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>
![photoset2](https://github.com/flutter/flutter/assets/70710178/896369d0-a009-4f25-8e25-5165b0e1f68f)
![video](https://github.com/flutter/flutter/assets/70710178/c34eb5d2-b463-4035-b197-6d4f5e00d312)

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
There is no output because the code produces images and video as expected just not at the  resolution expected
```

</details>

**Comment by huycozy** [comment]
Hi @Jsnt1004 
This looks similar to a known issue being tracked at https://github.com/flutter/flutter/issues/122966. 

Closing this issue in favor of #122966, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
