### ISSUE TITLE
Map crashes on pop - IOS

### ISSUE THREAD

**Issue by niktses** [flutter/flutter#127649]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

When popping a screen with a map the app crashes.

I see it in firebase crashlytics constantly and it is has dropped the crash free users to 99% so it is a really common issue for us.

Could have started after upgrading to 3.10.

From my testing i believe that this happens when the map is popped while loading the various info like restaurants etc.

If you pop the screen while the map is loading a couple of times you will reproduce it.

I encountered in in the crashlytics reporting as crashes suddently and I was unable to reproduce it in a physical device but with a simulator it happens every time. I used iphone 14 pro max 16.4.

### Expected results

Not crashing

### Actual results

Crashing

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      onGenerateRoute: (settings) => MaterialPageRoute(
        builder: (context) => const TestScreen(),
      ),
    );
  }
}

class TestScreen extends StatefulWidget {
  const TestScreen({Key? key}) : super(key: key);

  @override
  _TestScreenState createState() => _TestScreenState();
}

class _TestScreenState extends State<TestScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Column(
        children: [
          const Expanded(
            child: GoogleMap(
              initialCameraPosition: CameraPosition(
                target: LatLng(37.42796133580664, -122.085749655962),
                zoom: 14.4746,
              ),
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(32),
            child: ElevatedButton(
              onPressed: () {
                Navigator.of(context).push(
                  MaterialPageRoute(
                    builder: (context) => const TestScreen(),
                  ),
                );
              },
              child: Text('Press me'),
            ),
          ),
        ],
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
 Flutter (Channel stable, 3.10.2, on macOS 13.1 22C65 darwin-arm64, locale en-GR)
    • Flutter version 3.10.2 on channel stable at /Users/nikostsesmelis/Tools/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (2 days ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

```

</details>

**Comment by darshankawar** [comment]
@niktses 
It seems you are hitting https://github.com/flutter/flutter/issues/127489 which has been fixed on latest master, so you may want to test it on master.  I'll close this as a duplicate and already fixed. If you disagree, write in comments and I'll reopen it.
