### ISSUE TITLE
Remove engine benchmarks builds?

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#127678]
The builds outputs do not seem to be used anywhere.

https://ci.chromium.org/p/flutter/builders/prod/Linux%20Benchmarks%20%28no-upload%29:

Builds host_release and runs [testing/benchmark/generate_metrics.sh](https://cs.opensource.google/flutter/engine/+/master:testing/benchmark/generate_metrics.sh?q=testing%2Fbenchmark%2Fgenerate_metrics.sh&ss=flutter%2Fengine) which runs multiple binaries redirecting their outputs to files but nothing is being done with those files.

https://ci.chromium.org/p/flutter/builders/prod/Linux%20Benchmarks is building the engine release config, running the script and uploading the results to datastore in the flutter-cirrus project. Nothing seems to be reading the flutter-cirrus datastore.

**Comment by godofredoc** [comment]
\cc @zanderso can we remove these builds?

**Comment by zanderso** [comment]
AFAIU, this cannot be removed from prod with our current capabilities. The `Linux Benchmarks (no-upload)` variant is the pre-submit check for `Linux Benchmarks`. See in the `.ci.yaml` here: https://github.com/flutter/engine/blob/main/.ci.yaml#L179. `Linux Benchmarks` has `presubmit: false` set. If it's implemented, we could set a `postsubmit: false` property on `Linux Benchmarks (no-upload)`.

**Comment by godofredoc** [comment]
I was suggesting to remove both `Linux Benchmarks` and `Linux Benchmarks (no-upload)` if we still see value in running those binaries we can move it as a test on the existing linux host engine - host_release build and we will keep the same coverage in presubmit.

**Comment by zanderso** [comment]
It looks like the `flutter-cirrus` datastore is what is populating https://flutter-engine-perf.skia.org/e/. I may have been confused by our previous discussions, since the name of the datastore seems wrong. There's a comment here that it should have been retired after some point, and the data sent to a different place instead: https://github.com/flutter/engine/blob/main/testing/benchmark/bin/parse_and_send.dart#L112.

**Comment by godofredoc** [comment]
Skia perf data is ingested through json files saved into gs://flutter-skia-perf-prod/. I could not find any workflow that is reading datastore and uploading files to the skia bucket.

**Comment by godofredoc** [comment]
Actually let me look for a vm in the flutter-cirrus project.

**Comment by godofredoc** [comment]
Benchmarks are being uploaded correctly.
