### ISSUE TITLE
Remove legacy `beta`/`stable` builder configs

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#127632]
Release branches have been using same builder configs as main branch, but using branched recipes. All legacy `beta` and `stable` builder configs should be removed from infra/config.

**Comment by itsjustkevin** [comment]
@keyonghan do we have an assignee for this issue?

**Comment by keyonghan** [comment]
Not for now. I guess most fixit bugs in the pool are missing an assignee now, but it means anyone from the team could grab and work on it in the coming two weeks.

**Comment by keyonghan** [comment]
https://flutter-review.googlesource.com/c/infra/+/46640 completes this.
