### ISSUE TITLE
How to view exported CPU profiling results in Flutter Devtools? (Can PR for doc later)

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#127639]
Hi, I am looking at the CPU profiling results in Flutter devtools. The GUI is super janky, so I want to export it and view externally, just like how we view timelines with Perfetto or chrome://tracing. There does exist an "Export" button, but I am not sure what is the format of the exported data. It looks like plain JSON, and I have tried flamegraph tools without success (surely). The doc https://docs.flutter.dev/tools/devtools/cpu-profiler also does not mention how to use the exported data. A quick google search and Discord search also do not reveal answers.

I am worried this is just an ad-hoc format and no viewers at all support it, that's why I create this issue. Is there anyone who uses export button in the profiling - I wonder what (external) viewer do you usually use?

I am happy to PR for doc once I know how can I use the exported data!

![image](https://github.com/flutter/flutter/assets/5236035/de58169a-3d39-4c08-a6d3-96c5a7ad5f96)

**Comment by huycozy** [comment]
Hi @fzyzcjy 
It seems this question is best suited for [devtools](https://github.com/flutter/devtools), so please ask the same there for answers if any. But I will keep this open and label this as a documentation issue for more insights. Thank you!

**Comment by fzyzcjy** [comment]
Thanks! I opened it there as well: https://github.com/flutter/devtools/issues/5849

**Comment by huycozy** [comment]
@fzyzcjy I see https://github.com/flutter/devtools/issues/5849 has been closed. Is it safe to close this issue respectively?
