### ISSUE TITLE
Flutter Engine build failure: UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 1001: illegal multibyte sequence

### ISSUE THREAD

**Issue by p1318k** [flutter/flutter#127659]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I performed a build on Windows following the Flutter Engine Build Guide(https://github.com/flutter/flutter/wiki/Compiling-the-engine#compiling-for-windows). However, I encountered the following build error, and it did not proceed further.

### Expected results

build success

### Actual results

build failed

### Code sample

nothing

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```
PS C:\engine\src> ninja -C .\out\host_debug_unopt\
ninja: Entering directory `.\out\host_debug_unopt\'
[1/6284] ACTION //third_party/angle:angle_program_version_id(//build/toolchain/win:clang_x64)
FAILED: gen/angle/ANGLEShaderProgramVersion.h
C:/Users/kimki/.vpython-root/3a4476/Scripts/python.exe ../../third_party/angle/src/program_serialize_data_version.py gen/angle/ANGLEShaderProgramVersion.h gen/angle_code_affecting_program_serialize
Traceback (most recent call last):
  File "../../third_party/angle/src/program_serialize_data_version.py", line 40, in <module>
    angle_shader_program_version_hash_result = GenerateHashOfAffectedFiles(angle_code_files)
  File "../../third_party/angle/src/program_serialize_data_version.py", line 18, in GenerateHashOfAffectedFiles
    for chunk in iter(lambda: f.read(4096), ""):
  File "../../third_party/angle/src/program_serialize_data_version.py", line 18, in <lambda>
    for chunk in iter(lambda: f.read(4096), ""):
UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 1001: illegal multibyte sequence
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by p1318k** [comment]
It worked by modifing "program_serialize_data_version.py".
I don't have any idea for making a pull request for flutter engine. 
So, I leave a comment here.

** Before**
def GenerateHashOfAffectedFiles(angle_code_files):
    hash_md5 = hashlib.md5()
    for file in angle_code_files:
        assert (file != "")
        with open(file, 'r') as f:
            for chunk in iter(lambda: f.read(4096), ""):
                hash_md5.update(chunk.encode())
    return hash_md5.hexdigest(), hash_md5.digest_size

**After** : add {**_encoding='UTF-8_**} as a parameter for opening file. 
def GenerateHashOfAffectedFiles(angle_code_files):
    hash_md5 = hashlib.md5()
    for file in angle_code_files:
        assert (file != "")
        with open(file, 'r'**_, encoding='UTF-8'_**) as f:
            for chunk in iter(lambda: f.read(4096), ""):
                hash_md5.update(chunk.encode())
    return hash_md5.hexdigest(), hash_md5.digest_size

**Comment by huycozy** [comment]
Hi @p1318k, thanks for your report.
Adding encoding seems to be a reasonable fix. But can you please be more specific about:

- What is your current Python version?
- Did you make any modifications to the engine that you built?
- Which engine hash are you building at?

**Comment by p1318k** [comment]
> Hi @p1318k, thanks for your report. Adding encoding seems to be a reasonable fix. But can you please be more specific about:
> 
> * What is your current Python version?
> * Did you make any modifications to the engine that you built?
> * Which engine hash are you building at?

@huycozy Please refer to the following answer.

* Python3.11
* No other modifications.
* flutter engine repo hash : 470652849224c3a94b1a6b2ee8c1ad71655080de

Feel free to ask me if you need more information.

**Comment by huycozy** [comment]
Per [Compiling for Windows](https://github.com/flutter/flutter/wiki/Compiling-the-engine#compiling-for-windows):

> Also, be sure that Python27 is before any other python in your Path.

Could you retry this with Python 2 to see if it works? (also see this [SO answer](https://stackoverflow.com/a/58300358/5921933))

**Comment by p1318k** [comment]
> Per [Compiling for Windows](https://github.com/flutter/flutter/wiki/Compiling-the-engine#compiling-for-windows):
> 
> 
> 
> > Also, be sure that Python27 is before any other python in your Path.
> 
> 
> 
> Could you retry this with Python 2 to see if it works? (also see this [SO answer](https://stackoverflow.com/a/58300358/5921933)) 

It is same with Python2. It seems not depend on Python version.

**Comment by huycozy** [comment]
Thanks for checking it. Labeling the issue to have more insights.

**Comment by loic-sharma** [comment]
Thanks for creating this issue! I haven't ran into this issue before. Could you check a few things:

1. Please double-check your depot_tools installation: https://commondatastorage.googleapis.com/chrome-infra-docs/flat/depot_tools/docs/html/depot_tools_tutorial.html#_setting_up
    1. Is depot tools at the front of your path? Check that depot_tools is first for `where.exe python`
    2. Check that you've followed the `Warning` and `Note` in the Windows section
2. Try updating using `gclient sync -D` in an administrator prompt. Check there aren't any errors.
3. Try cleaning your build using `ninja -C .\out\host_debug_unopt -t clean`

**Comment by p1318k** [comment]
> Thanks for creating this issue! I haven't ran into this issue before. Could you check a few things:
> 
> 1. Please double-check your depot_tools installation: https://commondatastorage.googleapis.com/chrome-infra-docs/flat/depot_tools/docs/html/depot_tools_tutorial.html#_setting_up
>    
>    1. Is depot tools at the front of your path? Check that depot_tools is first for `where.exe python`
>    2. Check that you've followed the `Warning` and `Note` in the Windows section
> 2. Try updating using `gclient sync -D` in an administrator prompt. Check there aren't any errors.
> 3. Try cleaning your build using `ninja -C .\out\host_debug_unopt -t clean`

@loic-sharma Here is the answer.

1. "depot_tools"
- I just follow the guide for flutter engine development configuration. Nothing special for my local enviroment.
(https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment)

2. No error.

3. Same error issued.

**Comment by p1318k** [comment]
> Would you mind sharing the output of `where.exe python`?

The result is this. I have tried to use latest version of python3 before.
`
$ where.exe python
C:\Python27\python.exe
C:\depot_tools\python.bat
C:\Users\kimki\AppData\Local\Microsoft\WindowsApps\python.exe
`

**Comment by loic-sharma** [comment]
Depot tool's python - `C:\depot_tools\python.bat` is not at the front of your path. Please update your path such that depot tools is at the beginning as per the instructions here: https://commondatastorage.googleapis.com/chrome-infra-docs/flat/depot_tools/docs/html/depot_tools_tutorial.html#_setting_up

Also, could you check that `DEPOT_TOOLS_WIN_TOOLCHAIN=0` is set? This is necessary to build ANGLE if you are not a Googler.

If you still run into issues after this, could you try building ANGLE directly? See these instructions: https://chromium.googlesource.com/angle/angle/+/HEAD/doc/DevSetup.md
