### ISSUE TITLE
Compatibility Issue with Flutter Release 3.10 and Non-Null-Safety Projects

### ISSUE THREAD

**Issue by bhanuka96** [flutter/flutter#127643]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I recently upgraded to Flutter release 3.10 and encountered an issue with my existing projects that are not null-safety. Upon attempting to run my old projects, I received an error message stating that they only support Dart 3.0.0.

As the new release introduces null-safety as a default feature.

how to work non-null-safety projects to work with the latest release?

### Expected results

Worked

### Actual results

Failed

### Code sample

<details><summary>pubspec.yaml</summary>

```dart
environment:
  sdk: ">=2.11.0 <3.0.0"
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Downgrade to this version from 3.10, now working</summary>

```console
Flutter 3.7.12 • channel unknown • unknown source
Framework • revision 4d9e56e694 (5 weeks ago) • 2023-04-17 21:47:46 -0400
Engine • revision 1a65d409c7
Tools • Dart 2.19.6 • DevTools 2.20.1
```

</details>

**Comment by huycozy** [comment]
Hi @bhanuka96 
This is expected change since Dart 3, please check [100% sound null safety](https://dart.dev/resources/dart-3-migration#100-sound-null-safety) for more information. You should migrate your project and its dependencies to this change. Closing as it's not Flutter's issue.
