### ISSUE TITLE
Firebase codelab is missing details for how to enable debug mode

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#12761]
RE: https://codelabs.developers.google.com/codelabs/flutter-firebase/#6

For this step to succeed you have to enable debug mode. Towards this, the codelab links to https://support.google.com/firebase/answer/7201382?hl=en&utm_id=ad. However, this has no details for how to accomplish the task, and we really struggled in xCode. Can we please add details for how to complete this step?

This bug was found during a "dryrun" of the Firebase codelab in AAR by @floitschG, @mravn-google, and @mit-mit.

**Comment by LarkAscending** [comment]
_However, this has no details for how to accomplish the task, and we really struggled in xCode._
Are more details available on what was difficult in Xcode?

The linked topic was the correct one several months ago; now there is a [real topic](https://firebase.google.com/docs/analytics/debugview) on the Firebase site. It says essentially the same things but gives more information. If we changed the link to point here, would that help?

**Comment by mit-mit** [comment]
The only help given for iOS is:

"specify the following command line argument in Xcode :
-FIRDebugEnabled"

It took us almost 10 mins of googling to figure out how to actually do that.

**Comment by LarkAscending** [comment]
Yes, sounds like you were caught between the vague Firebase doc and the missing Xcode doc. 

This could be very good feedback for the Firebase documentation team. Would it make sense to file a bug by clicking the pencil icon on the [Debugging Events](https://firebase.google.com/docs/analytics/debugview) page? If there's a suggestion for how to fix it, the change can happen pretty fast. 

While we don't want the codelab to go into the weeds here, updating the link and adding the following nudges to get folks going in the right direction:
_For iOS, configure your Xcode scheme to pass the FIRDebugEnabled argument on launch. For Android, use adb to set the debug.firebase.analytics.app property._

As soon as the Firebase doc has this info, we should consider removing it from the codelab. Names of properties and arguments are the kind of detail that can change without notice and cause the codelab to go out-of-date.

**Comment by sunojvijayan** [comment]
For those like me who need more clarity

1. open X-code
2. Product\schema\edit schema
3. Select Run on the left tab. Select argument on the right and click + on "Arguments Passed on Launch" and add this "-FIRDebugEnable"

<img width="862" alt="screenshot 2019-01-31 at 7 37 30 am" src="https://user-images.githubusercontent.com/7021745/52020199-5d42ef80-252b-11e9-832f-f54435aeb8bf.png">

4. In my case when i ran "flutter run" , it still didn't work. So I had to run the project from X-code once. After that even from the cli it worked.

Hope this is helpful to someone.
