### ISSUE TITLE
Feature request: Allow frame rate limiting in debug tools

### ISSUE THREAD

**Issue by jonaird** [flutter/flutter#127648]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I am using shaders to implement a motion blur feature. My implementation of the motion blur is frame rate dependent. It measures the position delta of a widget in between frames and applies a radial blur accordingly. I would like to use the debug tool feature which slows down animations to verify that my shader is displaying correctly but while the animations do slow down, Flutter still renders at 60 frames per second and thus my shader doesn’t display as it normally would. 

Being able to limit frame rate would also help debug other kinds of scenarios as well as to see what your app might look like on low power devices. 

### Proposal

What I’m proposing is a feature in the debug tools that allows the developer to add a frame rate limiter while in debug mode.

**Comment by huycozy** [comment]
Hi @jonaird 
Can you check if [Slow animations](https://docs.flutter.dev/tools/devtools/inspector#slow-animations) can work for this case?

Also, per mentioned at https://github.com/flutter/flutter/issues/35162#issuecomment-609000841, it seems [flutter_displaymode](https://pub.dev/packages/flutter_displaymode) is also useful.

**Comment by huycozy** [comment]
>Slow animations maintains 60fps but slows the animations.

Can you please be more specific? 

>while the animations do slow down, Flutter still renders at 60 frames per second and thus my shader doesn’t display as it normally would.

Can you also share a recorded video or an example for this as well?

Also, please try [statsfl](https://pub.dev/packages/statsfl) package if it works and confirm if it presents for your expectation.
