### ISSUE TITLE
Firebase codelab section has non-clear ending point

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#12760]
RE: https://codelabs.developers.google.com/codelabs/flutter-firebase/#5

It's not clear where the iOS-only step "Configure Google Sign-In on iOS" section ends. 

We think it ends after "This URL type will handle the callback when a user logs into your app.", but if so, a new section heading seems to be missing before "If you run the app".

This bug was found during a "dryrun" of the Firebase codelab in AAR by @floitschG, @mravn-google, and @mit-mit.

**Comment by LarkAscending** [comment]
Inserted a heading `Run Friendlychat`
