### ISSUE TITLE
Firebase codelab has incorrect statement about variable

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#12762]
RE: https://codelabs.developers.google.com/codelabs/flutter-firebase/#6

"Now add a private member variable named" should be changed to "Now add a private member variable named" (the variable shown in the code snippet is not private).

This bug was found during a "dryrun" of the Firebase codelab in AAR by @floitschG, @mravn-google, and @mit-mit.

**Comment by LarkAscending** [comment]
Did you mean "Now add a member variable named"? If so, fixed.

**Comment by mit-mit** [comment]
Yes, precisly, thanks!
