### ISSUE TITLE
We wish we could instruct flutter doctor to not check for Android and iOS

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#12768]
For Fuchsia, we love the flutter doctor tool. It's output, however, assumes iOS and Android on a Mac. We'd love to be able to say "run flutter doctor, but don't bother checking Android and iOS".

Strawman: `flutter doctor --without=android,ios` or similar.

(we anticipate wrapping the flutter doctor command, so we're comfortable with verbose command lines for now)

**Comment by franzsilva** [comment]
Probably could get a fix for that quite quick. Would it work if it could be an argument like:
flutter doctor --only-fuchsia
Spotted on the code where its done.

**Comment by franzsilva** [comment]
Added the funcitonality, Let me know if you would like another type of argument
#13200

**Comment by mhelmetag** [comment]
It looks like a PR (#13200) was just missing some specs but had this partially figured out. I would probably change that singular `--fuchsia` to the `--without` (or `--only`) syntax as that also allows it to extend to it to include or exclude editor configs too.

If there's still interest, I'd like to finish this up.

**Comment by jonahwilliams** [comment]
Fixed via https://github.com/flutter/flutter/pull/61481
