### ISSUE TITLE
`video_player_test` is failing consistently

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#127610]
Hit the failure in https://github.com/flutter/packages/pull/4074, and retry didn't help. Other packages PRs seem all broken on this issue.
Example: failed cirrus task: https://cirrus-ci.com/task/6279854664974336?logs=firebase_test_lab#L2002

```
More details are available at [ https://console.firebase.google.com/project/flutter-cirrus/testlab/histories/bh.c2e144806129f3ee/matrices/8130142388132602987 ].
Test failure for example/integration_test/video_player_test.dart after 2 attempts
[video_player_android completed in 5m 43s]
The following packages had errors:
  video_player/video_player:
    example/integration_test/video_player_test.dart failed tests
  video_player_android:
    example/integration_test/video_player_test.dart failed tests
See above for full details.
```

/cc @stuartmorgan

**Comment by stuartmorgan** [comment]
It looks like the GitHub Pages site for https://flutter.github.io/assets-for-api-docs is gone/down, and it hosts the content for that test.

We should move it in-repo, but @gspencergoog any idea what happened to the repo's site?

**Comment by stuartmorgan** [comment]
Looping in @bparrishMines as gardener.

**Comment by keyonghan** [comment]
@stuartmorgan from the hackers-infra discord, the default branch has been switched from `master` to `main`. Will this cause the issue?

**Comment by gspencergoog** [comment]
Crap.  Yes, that's the issue.

**Comment by gspencergoog** [comment]
Okay, @godofredoc updated the GitHub pages entry to point to the right branch, so it should work again.

**Comment by gspencergoog** [comment]
Okay, looks like the test is passing now.
