### ISSUE TITLE
Engine -> Framework roll is failing on a crash in `gen_snapshot`:

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#127666]
Starting in https://github.com/flutter/flutter/pull/127650, windows framework presubmit tests are failing with a crash in `gen_snapshot`:

```
Type::arguments_offset() got 32, Type_arguments_offset expected 28
FunctionType::named_parameter_names_offset() got 44, FunctionType_named_parameter_names_offset expected 40
FunctionType::packed_parameter_counts_offset() got 48, FunctionType_packed_parameter_counts_offset expected 44
FunctionType::packed_type_parameter_counts_offset() got 52, FunctionType_packed_type_parameter_counts_offset expected 48
FunctionType::parameter_types_offset() got 40, FunctionType_parameter_types_offset expected 36
FunctionType::type_parameters_offset() got 32, FunctionType_type_parameters_offset expected 28
TypeParameter::index_offset() got 38, TypeParameter_index_offset expected 34
../../third_party/dart/runtime/vm/dart.cc: 242: error: CheckOffsets failed. Try updating offsets by running ./tools/run_offsets_extractor.sh
```

Eyeballing the list of commits in the Dart roll (https://github.com/flutter/engine/pull/42341), I'm guessing the cause might be https://dart.googlesource.com/sdk.git/+/f96d179ae45ed0b949f9f9146e6d4122ba6aa2cc ? cc @alexmarkov

**Comment by zanderso** [comment]
I'm going to start a revert on the Dart roll to unblock the Engine -> Framework roll.

**Comment by alexmarkov** [comment]
Dart change reverted in https://dart-review.googlesource.com/c/sdk/+/306000.

**Comment by zanderso** [comment]
The Engine roller is moving again, and the Dart revert is landed upstream, so I will close this.
