### ISSUE TITLE
[Windows] Document how to do the "show window" migration manually

### ISSUE THREAD

**Issue by loic-sharma** [flutter/flutter#127695]
## Background
Flutter 3.10 app startup has a race condition that can result in the window not being shown. https://github.com/flutter/flutter/pull/127046 updated the app template to fix this issue. Windows projects will need to be updated after the next Flutter release. An automatic migration was added for projects that have not modified their Windows entry point. However, the automatic migration may not be able to modify projects that have modified their Windows entry point.

Part of: https://github.com/flutter/flutter/issues/119415
See: https://github.com/flutter/flutter/pull/127046#discussion_r1198028570

## Solution
After the next Flutter release, document how to do this migration manually.

Example migration:

```patch
diff --git a/examples/hello_world/windows/runner/flutter_window.cpp b/examples/hello_world/windows/runner/flutter_window.cpp
index f68aa9c26c0f5..7f66913a0293c 100644
--- a/examples/hello_world/windows/runner/flutter_window.cpp
+++ b/examples/hello_world/windows/runner/flutter_window.cpp
@@ -35,6 +35,11 @@ bool FlutterWindow::OnCreate() {
     this->Show();
   });
 
+  // Flutter can complete the first frame before the "show window" callback is
+  // registered. The following call ensures a frame is pending to ensure the
+  // window is shown. It is a no-op if the first frame hasn't completed yet.
+  flutter_controller_->ForceRedraw();
+
   return true;
 }
```

**Comment by dkwingsmt** [comment]
Slight rephrase suggestion:
```
+  // Flutter can complete the first frame before the "show window" callback is
+  // registered. The following call ensures a frame is pending to ensure the window is shown.
+  // It is an no-op if the first frame hasn't completed yet.
```

**Comment by parlough** [comment]
I'm not super familiar with this, but it sounds like a migration guide at https://docs.flutter.dev/release/breaking-changes would be useful. Even if the fix is simple, it brings attention to its necessity. Would that make sense for this? If so, would you be able to write one up?

**Comment by loic-sharma** [comment]
@parlough Funny you should ask, I just opened https://github.com/flutter/website/pull/9269 🥳
