### ISSUE TITLE
Would like a Graphics Bandwidth benchmark

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#12766]
@abarth mentioned to me that we should be tracking our graphics bandwidth.  Which can be approximated by the sum of the total size (bytes) of layers drawn to the GPU every frame / # of frames drawn.

My understanding is that this number is a trade-off with high-end performance and that using more bandwidth (caching more in textures) will improve performance on high-end devices, but that eventually we saturate the GPU bandwidth on low end devices.

I'm not aware of any benchmarks we currently have to track this number.

Did I get that right? @abarth @yjbanov @chinmaygarde

**Comment by liyuqian** [comment]
CC @brianosman : does Skia have an API to count the size of layers used? For example, if `saveLayer` is called many times, such metric should go up.

**Comment by bsalomon** [comment]
We don't have anything in Skia that counts layer sizes, surface sizes etc. Those would be pretty easy to layer on top of Skia. Texture bandwidth also occurs every time you draw an image, or we internally draw something like an image (e.g. an alpha mask representation of a glyph, blur etc). Then there's bandwidth to the framebuffer every time we draw anything on the GPU. Counting this inside Skia would be quite complicated. If I were to attempt to measure this I'd investigate whether there are GL/Vulkan/... perf analysis tools that could do it for me.

**Comment by liyuqian** [comment]
CC @dreveman as we were just discussing this hours ago. We think that we could utilize some platform-specific APIs to do this. Fuchsia currently does have some bandwidth benchmarks running.

**Comment by jonahwilliams** [comment]
We track GPU frame times and memory usage with Impeller now. Bandwith itself is a trickier concept but I think what we have is good enough
