### ISSUE TITLE
src/build/vs_toolchain.py not respecting caches and always forcing downloads

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#127603]
The vs_toolchain is always being forced downloaded independently if the cache exists or not.

```
________ running 'python3 src/third_party/dart/tools/generate_package_config.py' in 'C:\b\s\w\ir\cache\builder'
________ running 'python3 src/third_party/dart/tools/generate_sdk_version_file.py' in 'C:\b\s\w\ir\cache\builder'
________ running 'python3 src/build/vs_toolchain.py update' in 'C:\b\s\w\ir\cache\builder'
Windows toolchain out of date or doesn't exist, updating (Pro)...
  current_hashes: 
  desired_hash: 27370823e7
Copying gs://chrome-wintoolchain/27370823e7.zip...
```

Fixing this issue will make checkouts in windows 2+ minutes faster.

**Comment by godofredoc** [comment]
@zanderso do you know who can help us with this bug?

**Comment by zanderso** [comment]
We copy-paste this script from Chromium, so probably no one on Flutter has deep knowledge of it. It downloads the toolchain in a subdirectory of `depot_tools`. Does `depot_tools` get cached at all?

**Comment by godofredoc** [comment]
The toolchain location can be controlled using the `DEPOT_TOOLS_WIN_TOOLCHAIN_ROOT` env variable.

Fix: https://flutter-review.googlesource.com/c/recipes/+/45046

**Comment by keyonghan** [comment]
Does the issue still persist?

**Comment by godofredoc** [comment]
Fixed with https://flutter-review.googlesource.com/c/recipes/+/51662
