### ISSUE TITLE
Scaffold status bar tap effect lost with custom scroll controller

### ISSUE THREAD

**Issue by KevinTheGray** [flutter/flutter#12764]
## Steps to Reproduce

- be using iOS 
- build a view like this
```dart
return new Scaffold(
      body: new ListView.builder(
        controller: new ScrollController(),
        itemCount: 101,
        itemBuilder: (BuildContext context, int index) {
          return new Padding(
            padding: new EdgeInsets.all(40.0),
            child: new Container(
              height: 200.0,
              width: 200.0,
              color: Colors.green,
            ),
          );
        },
      ),
    );
```
- scroll down a bit
- tap status bar and notice it does not scroll to top

## Flutter Doctor
flutter doctor
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-US, channel master)
    • Flutter at /Users/KG/Developer/Flutter/flutter
    • Framework revision 3cd2b436b8 (2 days ago), 2017-10-25 10:25:47 -0400
    • Engine revision ec19da1c80
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /Users/KG/Library/Android/sdk
    • Platform android-26, build-tools 26.0.2
    • ANDROID_HOME = /Users/KG/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.0.1, Build version 9A1004
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio 3.0RC2.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.2.5)
    • Flutter plugin version 18.2
    • Dart plugin version 172.4343.25

**Comment by collinjackson** [comment]
I think this is working as intended. You must use `PrimaryScrollController.of(context)` to get the scroll controller instead of creating it yourself. This is how the `Scaffold` is able to influence the position of the `ListView`.

Here's an example:

```
import 'package:flutter/material.dart';

void main() {
  runApp(new MaterialApp(
    home: new Container(
      color: Colors.white,
      child: new MyAppHome(),
    ),
  ));
}

class MyAppHome extends StatefulWidget {
  MyAppHomeState createState() => new MyAppHomeState();
}

class MyAppHomeState extends State<MyAppHome> {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      floatingActionButton: new Builder(
        builder: (BuildContext context) {
          return new FloatingActionButton(
            child: new Icon(Icons.arrow_downward),
            onPressed: () {
              ScrollController controller = PrimaryScrollController.of(context);
              controller.animateTo(
                controller.position.maxScrollExtent,
                duration: const Duration(milliseconds: 300),
                curve: Curves.elasticInOut,
              );
            },
          );
        }
      ),
      body: new ListView.builder(
        itemCount: 101,
        itemBuilder: (BuildContext context, int index) {
          return new Padding(
            padding: new EdgeInsets.all(40.0),
            child: new Container(
              height: 200.0,
              width: 200.0,
              color: Colors.green,
            ),
          );
        },
      ),
    );
  }
}
```

**Comment by collinjackson** [comment]
I'm not sure if there's an action to be taken on this issue. Perhaps we should document on the `controller` property of `ScrollView` that passing an explicit controller prevents the scroll view from scrolling to the top in response to a tap on the status bar.

**Comment by KevinTheGray** [comment]
@collinjackson thanks, this works for me.  just tested it in my app and that does indeed fix the issue.  if you'd like to close, you can

**Comment by collinjackson** [comment]
I'll close for now, but if anyone feels the documentation could be improved, feel free to reopen

**Comment by craigomac** [comment]
Should I expect this behaviour to work with a `CustomScrollView` containing slivers also?

**Comment by wwwdata** [comment]
Ok, I could solve my problem by just using the `ScrollController` from the `Scaffold` inside my CustomScrollView. You can also inline this with a `Builder` widget like this

```dart
Scaffold(
  body: 
    Builder(builder: (BuildContext context) => 
      CustomScrollView(controller: PrimaryScrollController.of(context))
....
```

**Comment by zinwalin** [comment]
specifically,  as a workaround, just make ScrollController controller = PrimaryScrollController.of(context);
