### ISSUE TITLE
Migrate android_emulator tests to engine v2

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#127680]
This may require to add contexts support to engine v2 builds.

This can be achieved by adding a contexts property to the build configuration that will map to available contexts from the recipes implementation. Contexts will be python contexts configured at runtime using [exit stack](https://docs.python.org/3/library/contextlib.html#contextlib.ExitStack) and will provide a well defined set of env variables that scripts can use from within the context.

**Comment by godofredoc** [comment]
@ricardoamador thoughts?

**Comment by ricardoamador** [comment]
Should be doable. I will take a look.

**Comment by ricardoamador** [comment]
Okay so this can be done. The current changes to support devicelab will need to be modified as they aren't very flexible. I will go ahead and the exit stack to the devicelab tests.
