### ISSUE TITLE
Include `google_maps_flutter_web` in `google_maps_flutter`

### ISSUE THREAD

**Issue by aitor-gomila** [flutter/flutter#127747]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Currently flutter_google_maps only supports Android and iOS. google_maps_flutter_web would allow for web, and possibly windows/linux/macos if adapted to use webview.

### Proposal

The package is already meant to be used as a plugin with `google_maps_flutter`

**Comment by stuartmorgan** [comment]
Duplicate of https://github.com/flutter/flutter/issues/80688
