### ISSUE TITLE
Failed to lookup host

### ISSUE THREAD

**Issue by devmarwat** [flutter/flutter#127746]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Just call any host address and the error will be reproduced

### Expected results

Exception has occurred.
SocketException (SocketException: Failed host lookup: 'cloud.xxx.io' (OS Error: No address associated with hostname, errno = 7))

### Actual results

All the team is aware of but I think they are unable to handle this.
I got tired of this I have not even coded a line after this error for 10 days.

### Code sample

<details><summary>Code sample</summary>

```dart
myServer='cloud.xxxx.io';
get.connection(myServer);
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 3.11.0-14.0.pre.33, on Microsoft Windows [Version 10.0.19045.2965], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[!] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.2)
    ! Unable to locate a Windows 10 SDK. If building fails, install the Windows 10 SDK in Visual Studio.
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.78.2)
[√] Connected device (4 available)
[√] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by Hassanmrwt** [comment]
https://youtu.be/lRtrcG_Sz8U
Here is the detailed video I earlier made on this issue.

**Comment by huycozy** [comment]
Hi @Hassanmrwt 
I see your comment at https://github.com/flutter/flutter/issues/126650 but your exception does seem to be the same.  
When I try with the complete sample code at https://github.com/flutter/flutter/issues/126650#issue-1707263945 on the latest master channel, I can't see any issue.

Can you also try that sample code on the latest master channel and confirm?
