### ISSUE TITLE
Fresh `gclient sync` fails on harfbuzz

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#127706]
gclient sync fails on harfbuzz.  Navigating to `https://fuchsia.googlesource.com/third_party/harfbuzz` fails too.  My guess is that the dependency has gotten moved.

## steps to reproduce

1) Start a new engine checkout and attempt to run `gclient sync` on it

## error log

```
aaclarke@aaclarke-ubi:~/dev/engine/src$ gclient sync
Updating depot_tools...
/usr/local/google/home/aaclarke/dev/engine/.gclient_entries missing, .gclient file in parent directory /usr/local/google/home/aaclarke/dev/engine might not be the file you want to use.
96>WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "https://fuchsia.googlesource.com/third_party/harfbuzz" "/usr/local/google/home/aaclarke/dev/engine/src/third_party/_gclient_harfbuzz_cd50lksj"' in /usr/local/google/home/aaclarke/dev/engine failed; will retry after a short nap...
96>WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "https://fuchsia.googlesource.com/third_party/harfbuzz" "/usr/local/google/home/aaclarke/dev/engine/src/third_party/_gclient_harfbuzz_cd50lksj"' in /usr/local/google/home/aaclarke/dev/engine failed; will retry after a short nap...
Syncing projects:  95% (122/128) src/third_party/skia                      
src/third_party/harfbuzz (ERROR)
```

**Comment by gaaclarke** [comment]
Looks like flutter is using our own fork of harfbuzz, but skia is depending on the missing fuchsia harfbuzz.

**Comment by zanderso** [comment]
The engine DEPS file is pulling harfbuzz here: https://github.com/flutter/engine/blob/3b5b5fc96b8f934a63fc8b57e7f27b09ca67179c/DEPS#L271. `flutter_git` is `https://flutter.googlesource.com`.

**Comment by zanderso** [comment]
I'm surprised that the engine `gclient sync` would be pulling transitive DEPS from Skia.

**Comment by dnfield** [comment]
We do a recurse_deps on vulkan-deps. I don't think that pulls it in. We don't recurse Skia's deps AFAIK...

**Comment by dnfield** [comment]
@gaaclarke AFAIK this should only happen if you're on an old commit of the engine... I raised this as an issue in an internal bug where Fuchsia discussed wanting to delete this.

**Comment by gaaclarke** [comment]
Ugh, you know what the problem is.  When following the steps for setting up a new repo it clones your fork of the engine.  If you haven't updated that in years it's going to be all goofed up.  This happened to me last time too.

**Comment by gaaclarke** [comment]
It's a chicken and an egg problem were you can't pull from upstream until you gclient sync, and your sync will fail unless you update.

**Comment by gaaclarke** [comment]
I think ideally we'd change the `.gclient` to point to `flutter/engine.git` then have steps to add your fork to origin and move `flutter/engine.git` to `upstream.

**Comment by dnfield** [comment]
```
git fetch upstream
git reset --hard upstream/main
```

doesn't work without a gclient sync?

**Comment by gaaclarke** [comment]
> doesn't work without a gclient sync?

no because in the beginning you just have an empty directory with a `.gclient` file, so you can't issue git commands.

**Comment by gaaclarke** [comment]
I edited the wiki to recommend doing a `gclient sync` on `flutter/engine.git` then replacing that with the users fork afterwards.  This guarantees that the first `gclient sync` will work.

https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment/f257558aa874febcbb5629035d6c48a82510ecfb

**Comment by zanderso** [comment]
If you go to the GitHub page for your fork (for me `https://github.com/zanderso/engine`), there's an alert telling me when my fork is out of date.

**Comment by gaaclarke** [comment]
I guess alternatively we could have added a step that asks people to hit that "sync fork" button before doing `gclient sync`.  You know if someone messes up the step about updating `origin` though it's probably not the end of the world since probably 50% of the people building the engine aren't contributing changes, they're just poking around and don't even need a fork.
