### ISSUE TITLE
primarySwatch is allowed to be null but many consumers don't null-check it

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1277]
Either we should always fill it out, or we should null-check it reliably.

**Comment by abarth** [comment]
Probably we should require it to be non-null.

**Comment by Hixie** [comment]
iirc dark theme doesn't have a primary swatch

**Comment by abarth** [comment]
Can you show me the place in the spec that causes you to believe that?

**Comment by abarth** [comment]
My current theory is that the primary swatch should be an input to the theme but not an output.
