### ISSUE TITLE
Flutter fails to run on physical iOS device

### ISSUE THREAD

**Issue by jeffreywolberg** [flutter/flutter#127753]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. `flutter create test_app`
2. `cd test_app`
3. `flutter run`
(ensure you're running on a physical device)

### Actual results

When it tries to run on either my physical iPhone or iPad devices, it successfully builds and installs the app, however when it tries to launch it, flutter immediately fails. The app successfully builds and runs on Flutter Web and macOS. I assume this is not an iOS signing issue as it successfully completes the signing and linking steps. I have attached the output of my `flutter run -v`, `flutter run`, and the log I get when trying to (unsuccessfully) launch the app using Xcode->Product->Run. 

I have reviewed both [#86699](https://github.com/flutter/flutter/issues/86699) and [#72161](https://github.com/flutter/flutter/issues/72161) and my error is not the same as theirs. I have tried almost every trick in the book, including restarting my devices, running `flutter clean`, clearing the cache, deleting the ios build folder, trying a lower flutter version, ensuring my apple signing certificates are up to date, etc. It's incredibly frustrating.

When I try to run it using Xcode->Product->Run, I get the following banner
<img width="260" alt="image" src="https://github.com/flutter/flutter/assets/54825193/ca398753-3c79-4537-9d9d-f57e1c8ca781">

It seems that the issue is that flutter is failing to retrieve the process that the app is running in (it returns -1). Why is this the case? My app was running fine on my iPad around a week ago, and all of a sudden things stopped working.

### Logs

[flutter_run_verbose_output.txt](https://github.com/flutter/flutter/files/11582615/flutter_run_verbose_output.txt)
[xcode_product_run_output.txt](https://github.com/flutter/flutter/files/11582612/xcode_product_run_output.txt)
[flutter_run_output.txt](https://github.com/flutter/flutter/files/11582613/flutter_run_output.txt)

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.2, on macOS 13.0.1 22A400 darwin-arm64, locale en) 
    • Flutter version 3.10.2 on channel stable at /Users/jeffrey/Coding/frameworks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (4 days ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/jeffrey/Coding/frameworks/android
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/jeffrey/Coding/frameworks/android
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web 
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • Jeffrey’s iPad Pro (mobile) • 00008112-001E652E2E23C01E • ios            • iOS 16.4.1 20E252
    • macOS (desktop)             • macos                     • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm64
    • Chrome (web)                • chrome                    • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @jeffreywolberg 
Can you provide information when clicking on Details? And please check if the issue also occurs on emulator as well. 

Also, can you share the sample project (newly create project above) via GitHub repository or a compressed file? Thank you!
