### ISSUE TITLE
Propose to get selected item on selectedItemBuilder's callback of DropdownButton

### ISSUE THREAD

**Issue by tattuu** [flutter/flutter#127773]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

When using the selectedItemBuilder, the same number of widgets as items must be included in the list and returned.

However, it seems error-prone to have to return a list with the same number of elements.
Also, it didn't seem like a good practice to return even widgets that are not displayed on the screen.

### Proposal

How about a DropdownButton `selectedItemBuilder` that returns only one widget instead of a `List<Widget>`?

I believe that typically, only one selected item is displayed on the screen.
Is it necessary to return all widgets?

And to actually make that change, the `selectedItemBuilder` must include the value of the changed `value property` as an argument, not just the context.

#### current
```dart
// Define in advance
var selectedFruit = "orange";
final fruits = <String>["orange", "apple", "strawberry", "banana", "grape"];

DropdownButton<String>(
    selectedItemBuilder: (context) => fruits.map(Text.new).toList(),
    value: selectedFruit,
    items: fruits
          .map(
            (String fruit) =>
                DropdownMenuItem(value: fruit, child: Text(fruit)),
          )
          .toList(),
    onChanged: (String? value) {
        setState(() {
            selectedFruit = value!;
        });
    },
),
```

#### proposal
```dart
// Define in advance
var selectedFruit = "orange";
final fruits = <String>["orange", "apple", "strawberry", "banana", "grape"];

DropdownButton<String>(
    // Adding a second argument(The type of the second argument is the type specified for the value property.)
    // The only value to return is a single widget to be displayed on the screen.
    selectedItemBuilder: (context, selectedValue) => Text(selectedValue),
    value: selectedFruit,
    items: fruits
          .map(
            (String fruit) =>
                DropdownMenuItem(value: fruit, child: Text(fruit)),
          )
          .toList(),
    onChanged: (String? value) {
        setState(() {
            selectedFruit = value!;
        });
    },
),
```

**Comment by Piinks** [comment]
Hey @tattuu the newer DropdownMenu widget may have what you need here, have you seen DropdownMenu.onSelected?
