### ISSUE TITLE
Firebase subscribeToTopic failed on ios Device flutter app

### ISSUE THREAD

**Issue by efazalk** [flutter/flutter#127781]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I have configured firebase correctly and I am getting messages on Android device and iOS Simulator.
But I run the device on physical iPhone app is stuck on splash screen and Firebase Crashlytics catch exception on main.dart line:38 which is 
await FirebaseMessaging.instance.subscribeToTopic('ALL');
I am not able to figure out the issue.

### Expected results

App should run without error

### Actual results

Fatal Exception: FlutterError
0  ???                            0x0 StandardMethodCodec.decodeEnvelope + 652 (message_codecs.dart:652)
1  ???                            0x0 MethodChannel._invokeMethod + 310 (platform_channel.dart:310)
2  ???                            0x0 MethodChannel.invokeMapMethod + 510 (platform_channel.dart:510)
3  ???                            0x0 MethodChannelFirebaseMessaging.subscribeToTopic + 367 (method_channel_messaging.dart:367)
4  ???                            0x0 (null).main + 38 (main.dart:38)

### Code sample

<details><summary>Code sample</summary>

Future<void> main() async {
  WidgetsBinding widgetsBinding = WidgetsFlutterBinding.ensureInitialized();
  FlutterNativeSplash.preserve(widgetsBinding: widgetsBinding);

  await Firebase.initializeApp();

  FlutterError.onError = (errorDetails) {
    FirebaseCrashlytics.instance.recordFlutterFatalError(errorDetails);
  };

  PlatformDispatcher.instance.onError = (error, stack) {
    FirebaseCrashlytics.instance.recordError(error, stack, fatal: true);
    return true;
  };

  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

  FirebaseMessaging messaging = FirebaseMessaging.instance;
  await FirebaseMessaging.instance.subscribeToTopic('ALL');

  messaging.setForegroundNotificationPresentationOptions(
      alert: true, badge: true, sound: true);

  await SystemChrome.setPreferredOrientations(
    [DeviceOrientation.portraitUp],
  );

  await messaging.requestPermission(
      alert: true, badge: true, provisional: false, sound: true);

  var tk = await FirebaseMessaging.instance.getToken();

</details>

### Screenshots or Video

<details>

https://github.com/flutter/flutter/assets/27408112/4329944c-c303-4dfc-bf0e-140a08abbb8f

</details>

### Logs

<details><summary>Logs</summary>

Error from Crashlytics

0
message_codecs.dart - Line 652
StandardMethodCodec.decodeEnvelope + 652

1
platform_channel.dart - Line 310
MethodChannel._invokeMethod + 310

2
platform_channel.dart - Line 510
MethodChannel.invokeMapMethod + 510

3
method_channel_messaging.dart - Line 367
MethodChannelFirebaseMessaging.subscribeToTopic + 367
arrow_right 

4
main.dart - Line 38
(null).main + 38

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

[✓] Flutter (Channel stable, 3.10.1, on macOS 13.0.1 22A400 darwin-x64, locale en-GB)
    • Flutter version 3.10.1 on channel stable at /Users/ocean_computers/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (12 days ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/ocean_computers/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/ocean_computers/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 111.0.5563.64

[✓] Network resources
    • All expected network resources are available.

• No issues found!

</details>

**Comment by danagbemava-nc** [comment]
`firebase_messaging` is a third-party package. Any issues you face using it should be reported on their repo. 

Closing from here. 

Thank you
