### ISSUE TITLE
Small version update to in_app_purchase has undocumented breaking changes

### ISSUE THREAD

**Issue by kinex** [flutter/flutter#127766]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a Flutter project and add this to your pubspec.yaml:
`in_app_purchase: 3.1.5`
2. In your test app access members `GooglePlayProductDetails.skuDetails`, `PurchaseWrapper.skus` and `SkuDetailsWrapper` 
3. Make sure the project builds successfully.
4. Update pubspec.yaml as follows:
`in_app_purchase: ^3.1.5`
5. Upgrade the packages in your project with:
`flutter packages upgrade`

### Expected results

The project should build successfully also after upgraded packages. If there were breaking changes the package should increase its major/minor version number and document the breaking changes in the change log.

### Actual results

The build fails as there are breaking changes, but only the patch number of the package version was increased. Errors include:
```
The getter 'skuDetails' isn't defined for the type 'GooglePlayProductDetails'.
The getter 'skus' isn't defined for the type 'PurchaseWrapper'.
Undefined class 'SkuDetailsWrapper'.
```
There could be also other breaking changes, I listed here only those which I see in my project. The current change log of `in_app_purchase` does not mention any breaking changes after 3.1.5.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by stuartmorgan** [comment]
> 2\. In your test app access members `GooglePlayProductDetails.skuDetails`, `PurchaseWrapper.skus` and `SkuDetailsWrapper`

You haven't provided a complete code sample. Didn't you have to import `in_app_purchase_android` to use these?

**Comment by kinex** [comment]
I have the required imports there. For example the `PurchaseWrapper.skus` was removed in this PR https://github.com/flutter/packages/commit/dc5ff42b1b9d634567f1967229e59ffb93a300af#diff-0558ff471d6a86549f67812fa1dcb914552ebe309db0677170e00efa12ce3338L116. See also your comment https://github.com/flutter/packages/pull/3752#issuecomment-1551207633 . If there is a breaking change in the public API of a dependent package, it is a breaking change also in the main package.

**Comment by stuartmorgan** [comment]
> I have the required imports there.

But when you add imports on a new package, you should also be adding a dependency on that package, with version constraints, in your pubspec. Your steps to reproduce don't include that step, making the import inherently dangerous. You've explicitly created a situation where you are using an API without saying what version of that API you need.

See also https://dart-lang.github.io/linter/lints/depend_on_referenced_packages.html

> For example the `PurchaseWrapper.skus` was removed in this PR [flutter/packages@dc5ff42#diff-0558ff471d6a86549f67812fa1dcb914552ebe309db0677170e00efa12ce3338L116](https://github.com/flutter/packages/commit/dc5ff42b1b9d634567f1967229e59ffb93a300af#diff-0558ff471d6a86549f67812fa1dcb914552ebe309db0677170e00efa12ce3338L116). See also your comment [flutter/packages#3752 (comment)](https://github.com/flutter/packages/pull/3752#issuecomment-1551207633) .

That comment was about `in_app_purchase_android`, which was correctly versioned as breaking.

> If there is a breaking change in the public API of a package that depends on the main package, it is a breaking change also in the main package.

This statement is not correct; the API surface of a package is the set of things it exports. Is there's some documentation that gave you the impression that a package's entire transitive package dependency tree is part of its versioned API?

**Comment by kinex** [comment]
My understanding was that for federated plugins you don't need to include platform packages in the pubspec.yaml, but actually also the documentation [here](https://docs.flutter.dev/packages-and-plugins/developing-packages) says "they aren’t included into an app, unless they contain platform-specific functionality accessible to the end user". 

`in_app_purchase` is a slightly special plugin since I don't think it is possible to implement an app with subscriptions without accessing those platform specific APIs.

Anyway, for easier maintenance I will continue taking the "risk" and include only the main package into the pubspec.yaml. I want to use the latest version of the main package anyway and let it decide which versions of the platform packages are required. 

What you could have improved in my opinion, is the change log of [in_app_purchase_android](https://pub.dev/packages/in_app_purchase_android/changelog). Version 0.3.0 does not mention anything about the breaking changes I mention in this ticket.

**Comment by stuartmorgan** [comment]
> My understanding was that for federated plugins you don't need to include platform packages in the pubspec.yaml

This is true in the common case where plugin clients only use APIs provided by the app-facing package.

It's true that's less common for IAP; the expectation in that case is that you express your dependencies accordingly.

> Anyway, for easier maintenance I will continue taking the "risk" and include only the main package into the pubspec.yaml.

It's not clear to me how setting yourself up for unexpected compilation failures eases maintenance; this is essentially equivalent to using `any` for your direct dependencies. It's your choice of course, but it's not going to be a plugin bug when this inevitably happens again.

(Note that if we had done what you originally requested here, and made a major version change to the app-facing package, you would not have gotten the update without explicitly upgrading your packages... which is exactly the behavior that adding the pubspec dependencies you are currently missing would have. So you are deliberately choosing, for your own project, to *not* have the behavior you wanted us to require for all clients.)

**Comment by kinex** [comment]
As a temporary workaround I can use `in_app_purchase: 3.1.5` instead of the default `in_app_purchase: ^3.1.5` in my `pubspec.yaml` until I get the migration completed. I guess the end result would be the same if I had `in_app_purchase_android: ^0.2.0` in my `pubspec.yaml`, but I still prefer letting the main package decide which versions of the dependencies are needed and keep my own `pubspec.yaml` minimal. But no worries I will not report this as an issue again even if the build fails sometimes (has not happened often) :-)

**Comment by stuartmorgan** [comment]
> but I still prefer letting the main package decide which versions of the dependencies are needed

By definition, a package you are using cannot decide what version of another package *your code is directly using* is needed by your code.

It really seems like you are conflating direct dependencies (packages you call directly) and transitive dependencies (packages which are only *internal* implementation details of packages you are calling).

**Comment by kinex** [comment]
> > but I still prefer letting the main package decide which versions of the dependencies are needed
> 
> By definition, a package you are using cannot decide what version of another package _your code is directly using_ is needed by your code.
> 
To clarify I meant only federated plugins here. In other cases I do specify the package versions in my pubspec.yaml even though there may be other packages which depend on the same packages which I use directly. 

The federated plugin `in_app_purchase` needs the specific version of `in_app_purchase_android`, so I let `in_app_purchase` decide which version of `in_app_purchase_android` we use. I think it is simpler that way even though the build may break sometimes but it is rare. I have used this strategy as long long as `in_app_purchase` has existed and it works for me.

**Comment by stuartmorgan** [comment]
> To clarify I meant only federated plugins here. In other cases I do specify the package versions in my pubspec.yaml even though there may be other packages which depend on the same packages which I use directly.

Federated plugins are not special in this regard, so there is no reason to treat them differently. The situation is exactly the same: your own code and a package you use both use another package. There's no special coupling within the packages in a federated plugin, they just use the public API surfaces like any other package.

> The federated plugin `in_app_purchase` needs the specific version of `in_app_purchase_android`

It needs a version compatible with the constraint in its pubspec, that's it. Sometimes that's a broad range, sometimes a narrow one, depending on what exactly it's using. Just like any other inter-package dependencies.

> so I let `in_app_purchase` decide which version of `in_app_purchase_android` we use. I think it is simpler that way

Considering the two options that have been described here:
1. You express your dependency correctly in your pubspec, updating it at your convenience just like all your other dependencies. You are never unexpectedly broken.
2. You leave your dependency unexpressed. Sometimes you are randomly broken. When you are, you figure out after the fact what version of the package you want to constrain to, but instead of just having that constraint, you reverse-engineer a constraint for a **different package** that has nothing to do with your usage of the API surface of that package, but which will, as a side effect, cause a constraint on the transitive dependency.

I'm not seeing how the second is simpler.

> even though the build may break sometimes but it is rare.

Breaking changes are generally rare in our packages, yes. Which means updating the constraint in your pubspec would also be rare, were it there.

> I have used this strategy as long long as `in_app_purchase` has existed and it works for me.

Since the mobile implementations were separated there has only been one other breaking change. So this strategy has worked for you 50% of the time, and has saved you exactly one change, ever, to your pubspec.

You can of course do whatever you want in your project, but if you are going to argue in the Flutter issue tracker (which lots of people read) that this a good idea, I'm going to continue to explain why it's an anti-pattern do that others (hopefully) don't emulate it.

**Comment by enricoi** [comment]
@kinex  have you find a solution to get GooglePlayProductDetails.skuDetails? I used 'skuDetails.freeTrialPeriod' to know if show free trial offer ui or not but now I don't know how to do with the updated package. Thanks
