### ISSUE TITLE
Firebase codelab freezes step 6, error message_codecs.dart line 514

### ISSUE THREAD

**Issue by lubi888** [flutter/flutter#12777]
I think there's something wrong with the codelab example. I have gone over all the notes again and am still freezing up. Check this Stackoverflow for screenshots: [screen-freeze-after-msg-send](https://stackoverflow.com/questions/46848740/screen-freeze-after-msg-send-upon-google-login-flutter-firebase-codelab-friendl)

Stuck on [step 6](https://codelabs.developers.google.com/codelabs/flutter-firebase/#5)

Same error always no matter whether on phone or emulator:

`message_codecs.dart` line 514
> throw new PlatformException(code: errorCode, message: errorMessage, details: errorDetails)

3 Reasons why there's something awry:

1. Don't think it's a firebase issue as when I check the console firebase has recognized 2 new users for this app (thus I believe the SHA-1/256 is setup correctly, as is app identifier). Thus, the app is connecting to firebase correctly and it is, therefore, and issue with the message text itself.
2. The [sample code](https://github.com/flutter/friendlychat-steps/tree/master/full_steps) doesn't run either on my computer. step_1_set_up_firebase runs as it's continuation of the primary flutter codelab. However, none of the code from any of the progressive steps works (step_2_sign_in and higher).
3. There may be something deeper going on as it appears Flutter could be hitting an Android Problem of [SPAN_EXCLUSIVE_EXCLUSIVE](https://stackoverflow.com/questions/13670374/android-span-exclusive-exclusive-spans-cannot-have-a-zero-length) had to disable the 3rd party SwiftKey keyboard to stop the SPAN error from coming up. Using the Gboard means that the app still freezes but there are now no more SPAN_EXCLUSIVE errors.

----------
flutter analyze
No issues found!
Ran in 5.4s

a@bDell $ flutter doctor
[✓] Flutter (on Linux, locale en_IE.UTF-8, channel master)
    • Flutter at /home/iveagh/dart/flutter
    • Framework revision 4e48a737eb (3 weeks ago), 2017-10-06 19:24:34 -0700
    • Engine revision 459f722b86
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /home/iveagh/Android/Sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /home/iveagh/IDEs/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at /home/iveagh/IDEs/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 18.1
    • Dart plugin version 172.4155.35

[✓] Connected devices
    • Nexus 5 • 021cxxxxxxxyyyzzzz• android-arm • Android 6.0.1 (API 23)

---------
On another small note, the docs for this page are different than the provided example code:
```
// Add the _ensureLoggedIn() method definition in ChatScreenState.

Future<Null> _ensureLoggedIn() async {
  GoogleSignInAccount user = googleSignIn.currentUser;
  if (user == null)
```
The code example does not have _ensureLoggedIn() inside the ChatScreenState but as its own method at the top of main.dart.
I have tried to run the code in both ways, as in codebase (own method) and inside ChatScreenState, and I still get the same exception thrown: line 514.

**Comment by lubi888** [comment]
I just used the sample code "step_2_sign_in" from "codelab2full_steps" and then recreated a whole new firebase project. Have now finally been able to get past step 6 to part [9](https://codelabs.developers.google.com/codelabs/flutter-firebase/#8) where I can now see messages in firebase database. Looks great!

**Comment by kroikie** [comment]
@lubi888

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/950. Any further collaboration will be done there.
