### ISSUE TITLE
[Impeller] Imparity of blur result with MaskFilter.blur in custom painter with skia on master

### ISSUE THREAD

**Issue by junaid1460** [flutter/flutter#127770]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. clone https://github.com/junaid1460/flutter_impeller_reported_bugs
2. This project has old reported issues as well, but tabbed to show it. choose mask blur tab
<img width="442" alt="Screenshot 2023-05-28 at 4 43 52 PM" src="https://github.com/flutter/flutter/assets/3303745/e5973583-366c-46ac-ba77-ff117630a050">

3. Repeat step to with with and without `--no-enable-impeller`

### Expected results

![Simulator Screenshot - iPhone 14 Pro Max - 2023-05-28 at 10 51 20](https://github.com/flutter/flutter/assets/3303745/44a71bc4-1c02-446a-9ee5-da972bed886c)

### Actual results

![Simulator Screenshot - iPhone 14 Pro Max - 2023-05-28 at 10 47 17](https://github.com/flutter/flutter/assets/3303745/ae61fc23-fbaa-4c25-a7e6-e015467aa07d)

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

class CustomPaintMaskBlur extends StatefulWidget {
  const CustomPaintMaskBlur({super.key});

  @override
  State<CustomPaintMaskBlur> createState() => _CustomPaintMaskBlurState();
}

class _CustomPaintMaskBlurState extends State<CustomPaintMaskBlur> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text('Custom Paint Mask Blur'),
        ),
        body: SizedBox.expand(
          child: CustomPaint(
            painter: _ExamplePainter(),
          ),
        ));
  }
}

class _ExamplePainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    Path path_0 = Path();
    path_0.moveTo(size.width * 0.4969963, size.height * 0.2225648);
    path_0.cubicTo(
        size.width * 0.3010403,
        size.height * 0.2494297,
        size.width * 0.2630477,
        size.height * 0.4639523,
        size.width * 0.2850391,
        size.height * 0.6040218);
    path_0.cubicTo(
        size.width * 0.2850391,
        size.height * 0.6892674,
        size.width * 0.2085379,
        size.height * 0.6246876,
        size.width * 0.1895880,
        size.height * 0.7013233);
    path_0.cubicTo(
        size.width * 0.1706381,
        size.height * 0.7779591,
        size.width * 0.3566271,
        size.height * 0.8106794,
        size.width * 0.6528056,
        size.height * 0.7762360);
    path_0.cubicTo(
        size.width * 0.9489841,
        size.height * 0.7417940,
        size.width * 0.7405367,
        size.height * 0.5954106,
        size.width * 0.7398350,
        size.height * 0.4051119);
    path_0.cubicTo(
        size.width * 0.7391333,
        size.height * 0.2148145,
        size.width * 0.7419401,
        size.height * 0.1889823,
        size.width * 0.4969963,
        size.height * 0.2225648);
    path_0.close();

    final paint = Paint()
      ..maskFilter = const MaskFilter.blur(BlurStyle.normal, 164.0)
      ..shader = LinearGradient(
        colors: [
          const Color(0xff00AF54).withOpacity(0.3),
          const Color(0xffFFE972).withOpacity(0.3)
        ],
        begin: Alignment.topLeft,
        end: Alignment.bottomRight,
      ).createShader(Rect.fromLTWH(0, 0, size.width, size.height));

    canvas.drawPath(path_0, paint);
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) {
    return false;
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]
![Simulator Screenshot - iPhone 14 Pro Max - 2023-05-28 at 10 47 17](https://github.com/flutter/flutter/assets/3303745/d88dfc15-bd76-43c4-bb98-b922e2b78156)
![Simulator Screenshot - iPhone 14 Pro Max - 2023-05-28 at 10 47 53](https://github.com/flutter/flutter/assets/3303745/14a5eada-ebf1-40ac-beb3-bb93857b5a21)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.11.0-14.0.pre.59, on macOS 13.1 22C65 darwin-arm64, locale en-IN)
    • Flutter version 3.11.0-14.0.pre.59 on channel master at /Users/mj/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bca7644070 (16 hours ago), 2023-05-27 15:40:24 -0400
    • Engine revision b1698020bd
    • Dart version 3.1.0 (build 3.1.0-155.0.dev)
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/mj/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2021.3)
    • Android Studio at /////////
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 69.0.5
    • Dart plugin version 222.3739.24

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (4 available)
-----

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by junaid1460** [comment]
xref: https://github.com/flutter/flutter/issues/127013#issuecomment-1566091187

**Comment by agladyshev** [comment]
I have a similar CustomPaint shape in my project, but in my case I also apply canvas.rotate to the shape. If MaskFilter.blur is applied using Impeller combined with rotation, some weird glitching happen.
<details>
  <summary>Skia, no rotation</summary>

![skia_1](https://github.com/flutter/flutter/assets/9337778/f277ee75-40e4-4696-9692-047c7d37d8f7)

</details>
<details>
  <summary>Impeller, no rotation</summary>

![impeller_1](https://github.com/flutter/flutter/assets/9337778/3ed4f1ef-d0a0-4daa-a562-bfbba9240f01)

</details>

</details>
<details>
  <summary>Skia, canvas.rotate(0.2)</summary>

![skia_rotate_0 2](https://github.com/flutter/flutter/assets/9337778/496af130-314b-4311-b2e7-8bd2cde63445)



</details>

<details>
  <summary>Impeller, canvas.rotate(0.2)</summary>

![impeller_rotate_0 2](https://github.com/flutter/flutter/assets/9337778/335b7960-7ab7-412d-b0ab-fd8ce3a7b7c5)


</details>

<details>
  <summary>Impeller, canvas.rotate(0.27)</summary>

![impeller_rotate_0 27](https://github.com/flutter/flutter/assets/9337778/dc767e58-68dd-49f8-95fa-ee3e814efda3)

</details>

canvas.rotate(0.3) make the shape disappear completely with Impeller.
Using negative values for rotate get some weirdness until it disappears around canvas.rotate(-2);

Let me know if a detailed report would help.

<details>
  <summary>flutter doctor</summary>

```

[✓] Flutter (Channel stable, 3.13.0, on macOS 13.2.1 22D68 darwin-arm64, locale en-GE)
    • Flutter version 3.13.0 on channel stable at /Users/agladyshev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (8 days ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/agladyshev/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (4 available)
    • CPH2465 (mobile)        • aac06da7                             • android-arm64  • Android 13 (API 33)
    • iPhone 13 mini (mobile) • 62BEDD3B-F627-44FF-8ABC-FDCDE20216A5 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • iPhone 14 (mobile)      • 1D25EBA8-F6E3-4EF2-A0A9-F97C03BD9D4A • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

```

</details>

**Comment by junaid1460** [comment]
To point out this is still not solved here screenshots from latest master for reference

## [Impeller]
![Simulator Screenshot - iPhone 14 Pro Max - 2023-08-29 at 11 03 21](https://github.com/flutter/flutter/assets/3303745/13f1b70f-1833-46fd-92ea-b73d79e88276)

![Simulator Screenshot - iPhone 14 Pro Max - 2023-08-29 at 11 03 18](https://github.com/flutter/flutter/assets/3303745/097cdc83-e565-4a92-92d0-d0b359682aa7)

## [Skia]
![Simulator Screenshot - iPhone 14 Pro Max - 2023-08-29 at 11 05 43](https://github.com/flutter/flutter/assets/3303745/45f9fb48-1992-4e34-945f-8306e43322e7)
![Simulator Screenshot - iPhone 14 Pro Max - 2023-08-29 at 11 05 46](https://github.com/flutter/flutter/assets/3303745/4e1e5951-dbd5-4822-8e22-1c6489d639ff)

**Comment by junaid1460** [comment]
```
➜  test git:(master) ✗ flutter --version     
Flutter 3.14.0-12.0.pre.78 • channel master • https://github.com/flutter/flutter.git
Framework • revision 6dae269881 (79 minutes ago) • 2023-08-29 00:22:24 -0400
Engine • revision c7c61ff973
Tools • Dart 3.2.0 (build 3.2.0-118.0.dev) • DevTools 2.26.2
```

**Comment by junaid1460** [comment]
Also feel free to reach out to me before release if needed a testing eye, I can test out on my app, fairly large codebase

**Comment by adar2378** [comment]
Any update on this fix?

**Comment by gaaclarke** [comment]
I captured this in the frame debugger.  What we learned from that is that it is really drawing something.  I'm not sure why the colors are so much more saturated in the frame debugger.  Even where it should be white, it is pinkish.

<img width="1633" alt="Screenshot 2023-10-20 at 3 24 48 PM" src="https://github.com/flutter/flutter/assets/30870216/be70f08e-5edf-4fe5-bcf0-c1b4b6a9e0aa">

If the blur sigma is dropped to 1.0, skia and impeller look identical.  The difference in implementation appears to be solely a result of the blur logic and what happens when there is a large sigma.

I also tried disabling wide gamut, to make sure there wasn't something weird happening there.  That didn't change the issue.

**Comment by gaaclarke** [comment]
I discussed this a bit with the team.  The fact that the blur algorithm is a bit different than Skia's is known.  We believe we should bring our math in closer alignment with Skia's (within reasonable performance).  Across the board our blurs seem a bit more diffuse right now.

Jonah mentioned there is some know discrepancies.  There is an issue for it [here](https://github.com/flutter/flutter/issues/131580), and [here](https://github.com/jonahwilliams/engine/blob/song_2/impeller/entity/contents/filters/gaussian_blur_filter_contents_2.cc#L35-L142) is where you'll find the code.

**Comment by gaaclarke** [comment]
I looked at this a bit more, here is the diff between skia and impeller on a black background so it's easier to see:
## impeller
<img src="https://github.com/flutter/flutter/assets/30870216/2d79d200-e807-4840-9c63-fe0a0d3a530f" width=200></img>
## skia
<img src="https://github.com/flutter/flutter/assets/30870216/a58d5899-7d19-461c-aa07-cd9628f42311" width=200></img>
## diff
<img width="200" alt="Screenshot 2023-10-26 at 10 37 52 AM" src="https://github.com/flutter/flutter/assets/30870216/6ee401e2-ce52-4954-a8fb-2b7f753a3109">

**Comment by gaaclarke** [comment]
We have a longer term fix for this in https://github.com/flutter/flutter/issues/131580

In the meantime it was postulated by @bdero that the way we are scaling things down on a curve but not scaling down the kernel is leading to the differences in blurring.  We could try to come up with a curve for the kernel size as a quick fix to what we already have.  As a test I scaled the sigma by .5 and it started to look more like skia.  For smaller sigmas it is definitely wrong.  So I think it's promising to try to scale the kernel for now.

## impeller (sigma * 0.5)
<img src="https://github.com/flutter/flutter/assets/30870216/8d1e6aa4-4c2b-4dbf-845b-e4821902e412" width=200></img>
## skia (sigma * 1.0)
<img src="https://github.com/flutter/flutter/assets/30870216/dc8b8878-6d3e-44c9-9db0-d0f242158801" width=200></img>
