### ISSUE TITLE
Bot is not adding labels to PRs

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#127722]
There are an unusually high number of unlabeled PRs in this repository: https://github.com/flutter/flutter/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-asc+no%3Alabel

It looks like the github-actions bot is removing labels for some reason that were previously added by the flutter-dashboard bot: 

![](https://cdn.discordapp.com/attachments/608021351567065092/1111757443987423263/Screenshot_2023-05-26_at_1.46.40_PM.png)

Labeling this as a P1 as this will cause PRs to slip through regular team triaging.

**Comment by keyonghan** [comment]
@goderbauer Do you still see issue after https://github.com/flutter/flutter/pull/127690?
@CaseyHillers Is there any way to restore those removed labels by the action?

**Comment by goderbauer** [comment]
I saw `framework` label get removed incorrectly from this PR 24 minutes ago: https://github.com/flutter/flutter/pull/127308. That was after https://github.com/flutter/flutter/pull/127690 landed, but I don't know how long it takes for that change to be effective...

**Comment by goderbauer** [comment]
This is still happening. Examples: https://github.com/flutter/flutter/pull/127823 and https://github.com/flutter/flutter/pull/127839.

**Comment by CaseyHillers** [comment]
For context, the incorrect labeling is resulting some PRs from getting delayed in triage.

I'm going to take a look at this tomorrow. Due to the way GitHub actions work, I can't verify the changes in presubmit.

If there's no progress, i'll go ahead and revert this action from the framework, and instead use a low traffic repo like Cocoon.

**Comment by CaseyHillers** [comment]
Looking at https://github.com/flutter/flutter/pull/128058, this appears to be fixed. 

Future work will continue to be tracked in https://github.com/flutter/flutter/issues/126002

**Comment by goderbauer** [comment]
Thank you! I manually went through the backlog of unlabeled PRs and labeled them so those don't fall through the cracks.
