### ISSUE TITLE
Regarding the useSafeArea property of showModalBottomSheet

### ISSUE THREAD

**Issue by tattuu** [flutter/flutter#127771]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I want to include safeArea only in specific parts, not on all sides (top, bottom, left, right). However, showModalBottomSheet currently does not support that.

Therefore, I would like to propose the following.

### Proposal

How about implementing a specification that allows specifying left, top, right, and bottom, similar to the SafeArea widget, for the useSafeArea property of showModalBottomSheet?

### current
```
showModalBottomSheet(
    useSafeArea: true,
)
```

###  proposal
* proposal1
```
showModalBottomSheet(
    useSafeAreaLeft: true,
    useSafeAreaTop: true,
    useSafeAreaRight: true,
    useSafeAreaBottom: true,
)
```

* proposal2
```
showModalBottomSheet(
    useSafeArea: SafeArea() // use SafeArea widget
)
```

As this is my first issue to submit to the Flutter project, I apologize if I have provided any incorrect information. 
I would appreciate it if you could reply whenever you have time.

**Comment by huycozy** [comment]
Hi @tattuu 
For the 1st proposal, I'm not sure which scenario to use horizontal SafeArea (useSafeAreaLeft, useSafeAreaRight)? Can you please be more specific?

For 2nd proposal, it already used `SafeArea` widget inside when `useSafeArea` is true. 
https://github.com/flutter/flutter/blob/490fa3b46aa7983f66bd84875144d781a6589a31/packages/flutter/lib/src/material/bottom_sheet.dart#L1038-L1044
