### ISSUE TITLE
[iOS] Improve CupertinoTextSelectionToolbar visual fidelity

### ISSUE THREAD

**Issue by luccasclezar** [flutter/flutter#127756]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

CupertinoTextSelectionToolbar is very different from the native implementation, some problems are:

1. When changing pages, the whole content fades to the divider color instead of the actual background color;
2. Font size should be slightly bigger
3. There's no horizontal scroll to change pages
4. The whole layout instantly changes width when changing pages
5. The last page shows a disabled nextButton, when natively the button is hidden on the last page.

Here is a comparison between the current flutter cupertino toolbar and the native one.

|Flutter|Native|
|-|-|
|<video src="https://github.com/flutter/flutter/assets/12024080/7cf81075-46ec-4970-b118-cc27b60ddac0"></video>|<video src="https://github.com/flutter/flutter/assets/12024080/468c7d5b-ba93-4bd4-8f6e-8ec2644b9866"></video>|

### Proposal

Flutter should improve these areas to have a better toolbar on iOS.

The good news is that I'm requesting to be assigned this issue as I already fixed all these problems and will be creating a PR shortly. 😁

**Comment by danagbemava-nc** [comment]
Closing this as #127757 has been merged.
