### ISSUE TITLE
keyboard arrow keys moves in reverse in rtl textfield

### ISSUE THREAD

**Issue by Mojtaba118** [flutter/flutter#127783]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. create a textfield
2. set text align to right
3. set text direction to rtl
4. try filling text field with rtl languages like arabic or persian
5. now use arrow keys to move between characters
6. you'll see that arrow left and right is reversed.

### Expected results

press left arrow key to move to left in textfield.
press right arrow key to move to right in textfield.

### Actual results

pressing on left arrow key moves the indicator to right.
pressing on right arrow key moves the indicator to left.

### Code sample

<details><summary>Code sample</summary>

```dart
TextField(
              textAlign: TextAlign.right,
              textDirection: TextDirection.rtl,
            );
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.1, on macOS 13.4 22F66 darwin-arm64, locale en-US)
    • Flutter version 3.10.1 on channel stable at /Users/noormac/Develop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (12 days ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/noormac/Develop/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/noormac/Develop/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Users/noormac/../../Applications/Google Chrome Dev.app/Contents/MacOS/Google Chrome Dev

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.2)
    • VS Code at /Users/noormac/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (6 available)
    • SM G610F (mobile)           • 520354f64d56940d • android-arm    • Android 8.1.0 (API 27)
    • sdk gphone64 arm64 (mobile) • emulator-5554    • android-arm64  • Android 12 (API 31) (emulator)
    • sdk gphone64 arm64 (mobile) • emulator-5556    • android-arm64  • Android 12 (API 31) (emulator)
    • sdk gphone64 arm64 (mobile) • emulator-5558    • android-arm64  • Android 12 (API 31) (emulator)
    • macOS (desktop)             • macos            • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)                • chrome           • web-javascript • Google Chrome 115.0.5790.3 dev

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by justinmc** [comment]
@dam-ease Can you try the same thing in a non-Flutter web input?  When I try this in the Google search field on Chrome on Mac, I see the same behavior as Flutter.  The arrows and movement are reversed.  (But trying it in the address bar, it's not reversed).

So to me it seems like this is working as intended, if I'm understanding correctly.

**Comment by dam-ease** [comment]
Hi @justinmc. With Google Search Field, the text isn't aligned to the left but another example is the github comment field (Video below).

<details><summary>Video</summary>
<p>

https://github.com/flutter/flutter/assets/53122008/ff1e56d7-aead-4e8f-92bd-de06e4a981bd

</p>
</details>

**Comment by mamaly12** [comment]
I also have the same problem. My arrow key works in the wrong direction when I use RTL inputs.

Any help would be appreciated.

**Comment by gnprice** [comment]
This appears to be the same issue as #78660, so let's consolidate the discussion there.
