### ISSUE TITLE
[CP] [Impeller] fix UV and color blending

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#127710]
### issue_link

https://github.com/flutter/flutter/issues/127486

### Commit Hash

43630887f496eb45cbd542cd44088caf5c6c11c5

### Target

stable

### pr_link

https://github.com/flutter/engine/pull/42360

### Changelog Description

Combinations of UV mapping and color blending would cause Flutter to double apply the UV mapping, which rendered either nothing or noise.

### Impacted Users

Impeller users 

### Impact Description

Incorrect rendering

### Workaround

There is no workaround other than disabling Impeller.

### Risk

low

### Test Coverage

yes

### Validation Steps

Code samples in the issue https://github.com/flutter/flutter/issues/127486 demonstrate the fix.

**Comment by zanderso** [comment]
The need for this CP should be confirmed by @jonahwilliams before landing.

cc @chinmaygarde

**Comment by jonahwilliams** [comment]
LGTM
