### ISSUE TITLE
DataTable: allow padding values to be adjusted

### ISSUE THREAD

**Issue by dguralnick** [flutter/flutter#12775]
A couple issues seen in the screenshot:
* Single column tables are full width, but multi column tables are not
* Long data cells are wrapped, but column names are not

Also, the API provides no way to control padding along the sides of the table, which may be desired if customizing the component to match alignment of adjacent components.

![image](https://user-images.githubusercontent.com/8662178/32130219-d94c39cc-bb48-11e7-9f9e-e115f1826c2b.png)

Sample code to play with:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
        scaffoldBackgroundColor: Colors.grey.shade100,
      ),
      home: new MyHomePage(title: 'Table behavior demo'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  Widget build(BuildContext context) {

    final cols1 = [
      new DataColumn(
        label: const Text('Column title 1'),
      ),
    ];

    final cols2 = [
      new DataColumn(
        label: const Text('Column title 1'),
      ),
      new DataColumn(
        label: const Text('Long column title'),
      ),
      new DataColumn(
        label: const Text('Title'),
      ),
    ];

    final rows1 = new List.generate(3, (_) =>
        new DataRow(
           cells: [
              new DataCell(new Text('loooooonnnnnng')),
            ]));

    final rows2 = new List.generate(3, (_) =>
        new DataRow(
           cells: [
              new DataCell(new Text('loooooonnnnnng gets wrapped')),
              new DataCell(new Text('short')),
              new DataCell(new Text('vs')),
            ]));

    return new Scaffold(
      appBar: new AppBar(
        title: new Text(title),
      ),
      body: new Column(
        children: [
          new Material(
            child: new DataTable(columns: cols1, rows: rows1),
          ),
          new Padding(padding: const EdgeInsets.only(top: 10.0)),
          new Material(
            child: new DataTable(columns: cols2, rows: rows2),
          ),
        ],
      ),
    );
  }
}
```

**Comment by Hixie** [comment]
(If possible please file one bug per issue, thanks!)

> Single column tables are full width, but multi column tables are not

What's actually going on here is that if there's only one column that contains text, then we make that column flexible (so it expands to fit the screen). This is working as intended.

> Long data cells are wrapped, but column names are not

This is a bit buggy for sure (the column titles should be getting ellipsised, and it seems to matter whether the title has spaces in it or not, which is clearly bogus), but the general approach here is as intended: columns are supposed to get shrunk when the table is too big, and column titles are supposed to be short according to the Material design specification (use the tooltip field to give the full title).

> Also, the API provides no way to control padding along the sides of the table, which may be desired if customizing the component to match alignment of adjacent components.

I'm not quite sure I follow here. Can you elaborate?

**Comment by dguralnick** [comment]
RE width: if this is WAI, is there a good way to force a multi-column table to take up the full width of its parent?

RE padding: in the screenshot above, if I wanted "Column title 1" to left-aligned with "Flutter Demo Home Page", there was no way to do this by adjusting the table (AFAICT). The table's internal padding is not adjustable. I realize it's probably defaulting to a value from the material spec, but sometimes we need to change the leftmost alignment for aesthetics.

**Comment by Hixie** [comment]
You can make any widget be forced to fill the parent by wrapping it in a `SizedBox.expand` widget.

For the padding issue, the padding numbers are hard-coded to match what the Material design specification specifies. We could certainly make that more configurable. If this is something you would like to see, I recommend submitting a PR to add the relevant properties to the `DataTable` class in `data_table.dart`. It should be relatively straight-forward -- the most time-consuming part of that would probably be writing the test, which would need to verify that the padding worked, e.g. by using `tester.getTopLeft(find.text('Column title 1'))` to find where the top left of the column title ended up.

**Comment by GeneralBlaze** [comment]
Please how can one go about setting the data cells to take up a certain width? Sometimes they take up just too much space

**Comment by shihaohong** [comment]
Hi @GeneralBlaze, try StackOverflow first to see if anybody has figured out a way to achieve that effect. If you got here because it seems like there isn't a clear answer anywhere, it's likely that it's not supported by Flutter or not easily achievable at the moment. If that's the case, please file a feature request on GitHub.
