### ISSUE TITLE
GTK 3.0 development libraries || Fedora

### ISSUE THREAD

**Issue by Si-kaR** [flutter/flutter#127763]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Pardon me if I am filling this slot wrongly, I am a bit new to the GitHub

Trying to install flutter for app development, I have run into a series of problems. I have successfully resolved many, however these remaining two problems seem a bit more presistent. 

I use fedora, and I have gotten very little help from searching online. 

### Actual results

[griphen@fedora licenses]$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.2, on Fedora Linux 38 (Workstation Edition) 6.2.15-300.fc38.x86_64,
    locale en_GB.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.
[✓] Chrome - develop for the web
[✗] Linux toolchain - develop for Linux desktop
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Community Edition (version 2022.1)
[✓] VS Code (version 1.78.2)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 2 categories.

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

[griphen@fedora licenses]$ flutter doctor -v
[✓] Flutter (Channel stable, 3.10.2, on Fedora Linux 38 (Workstation Edition) 6.2.15-300.fc38.x86_64,
    locale en_GB.UTF-8)
    • Flutter version 3.10.2 on channel stable at /home/griphen/.flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (4 days ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /home/griphen/.android/Android/Sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✗] Linux toolchain - develop for Linux desktop
    • clang version 16.0.4 (Fedora 16.0.4-1.fc38)
    • cmake version 3.26.4
    • ninja version 1.11.1
    • pkg-config version 1.8.0
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)

[✓] Android Studio (version 2022.2)
    • Android Studio at /home/griphen/.android/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at /opt/idea
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.2)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Fedora Linux 38 (Workstation Edition)
      6.2.15-300.fc38.x86_64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

**Comment by navaronbracke** [comment]
For the two Android issues:
1) You need Android's command-line tools. See https://developer.android.com/tools/sdkmanager
2) You'll have to accept the licenses that come with the Android SDK. Either use the command shown by the doctor check `flutter doctor --android-licenses`
or use `path/to/sdkmanager --licenses`. See https://developer.android.com/tools/sdkmanager#accept-licenses

You might need to tackle 1 first, not sure if the SDK manager is already bundled from the start.

For the GTK 3.0 issue, I suggest you look into installing that dependency for your distro. (Not a Linux dev, so I don't know off the top of my head how to do this)

**Comment by stuartmorgan** [comment]
What is the Flutter bug you are trying to report? Is `flutter doctor` incorrect about the presence of the GTK libraries?

**Comment by Si-kaR** [comment]
[✗] Linux toolchain - develop for Linux desktop
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)


After running flutter docto, this output is what's left to be checked right. 

I tried the apt install libgtk-3-dev but that didn't work. and I have no idea how I'll get it right. So far I have resolved every other issue but this one.

**Comment by Si-kaR** [comment]
Thanks @navaronbracke  . I had eventually been able to fix the license issue with the help community forum. Didn't know I had fallen asleep behind my device. 
I was about to continue searching for the result when I saw the response/comments here.


@stuartmorgan, I replied to your question about 13 minutes. To iterate, I'm stuck on the last unchecked box below. 

[✗] Linux toolchain - develop for Linux desktop
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)


Unless maybe it is not an issue?

**Comment by Si-kaR** [comment]
Thanks @navaronbracke  . I had eventually been able to fix the license issue with the help community forum. Didn't know I had fallen asleep behind my device. 
I was about to continue searching for the result when I saw the response/comments here.


@stuartmorgan, I replied to your question about 13 minutes. To iterate, I'm stuck on the last unchecked box below. 

[✗] Linux toolchain - develop for Linux desktop
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)


Unless maybe it is not an issue?

@stuartmorgan Is flutter doctor incorrect about the presence of the GTK libraries?      I have no idea, cuz I don't even know whether the ✗ GTK 3.0 development libraries  are installed anywhere in my device or not. Personally I haven't explicitly installed it anywhere so it's difficult approachingn the issue

**Comment by Si-kaR** [comment]
Thank you all so much!  I have resolved this final GTK3 Development issue as well. 
As @navaronbracke advised, I installed the GTK dependencies for my distro and I have nothing unchecked now. Below are the resources for the problems I faced;

1. GTK 3 Development Libraries: Needed to install on device:  https://snapcraft.io/install/gtk-3-examples/fedora
Note: I didn't use snapd... I just went on to use the dnf install

2. Android License: https://www.fluttercampus.com/guide/201/android-sdkmanager-not-found-error-flutter/

Below is what can be seen after running              flutter doctor           and            flutter doctor -v
Thank you @navaronbracke 
Thank you @stuartmorgan 
👋🙂








[griphen@fedora ~]$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.2, on Fedora Linux 38 (Workstation Edition) 6.2.15-300.fc38.x86_64,
    locale en_GB.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Community Edition (version 2022.1)
[✓] VS Code (version 1.78.2)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!



















[griphen@fedora ~]$ flutter doctor -v
[✓] Flutter (Channel stable, 3.10.2, on Fedora Linux 38 (Workstation Edition) 6.2.15-300.fc38.x86_64,
    locale en_GB.UTF-8)
    • Flutter version 3.10.2 on channel stable at /home/griphen/.flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (4 days ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /home/griphen/.android/Android/Sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (Red_Hat-17.0.7.0.7-4.fc38) (build 17.0.7+7)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 16.0.4 (Fedora 16.0.4-1.fc38)
    • cmake version 3.26.4
    • ninja version 1.11.1
    • pkg-config version 1.8.0

[✓] Android Studio (version 2022.2)
    • Android Studio at /home/griphen/.android/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at /opt/idea
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.2)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Fedora Linux 38 (Workstation Edition)
      6.2.15-300.fc38.x86_64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

• No issues found!
