### ISSUE TITLE
[1P Packages] Update code samples of packages that use video_player in their examples. 

### ISSUE THREAD

**Issue by gabrielokura** [flutter/flutter#127754]
Since https://github.com/flutter/packages/pull/3513 is adding a new `URI`-typed factory method, the following packages needs to update it's deprecated examples:

 - camera/camera
 - camera/camera_android
 - camera/camera_android_camerax
 - camera/camera_avfoundation
 - image_picker/image_picker
 - image_picker/image_picker_android
 - image_picker/image_picker_ios

The fix should be similar to this code

```dart
// deprecated
final VideoPlayerController vController = kIsWeb
        ? VideoPlayerController.network(videoFile!.path)
        : VideoPlayerController.file(File(videoFile!.path));
        
// fixed
final VideoPlayerController vController = kIsWeb
        ? VideoPlayerController.networkUrl(Uri.parse(videoFile!.path))
        : VideoPlayerController.file(File(videoFile!.path));
```

Also, this update will fix the analyze's tests: 

```
[31mThe following packages had errors:�[0m
[31m  camera/camera�[0m
[31m  camera_android�[0m
[31m  camera_android_camerax�[0m
[31m  camera_avfoundation�[0m
[31m  image_picker/image_picker�[0m
[31m  image_picker_android�[0m
[31m  image_picker_ios�[0m
[31mSee above for full details.�[0m
```

**Comment by stuartmorgan** [comment]
Triaging under the expectation of the linked PR landing; it's not valid until that PR does land however.
