### ISSUE TITLE
[CP] Impeller image decoding on iOS in the background

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#127705]
### issue_link

https://github.com/flutter/flutter/issues/126878

### Commit Hash

882703b7fb4e28045b06f0d2245b6eebcfac5c20

### Target

stable

### pr_link

https://github.com/flutter/engine/pull/42362

### Changelog Description

This needs to pick 10951022cc275a41a2c383338d997e81c0f19e75 as well, because otherwise the conflicts get pretty difficult to resolve.

Avoids using MTLCommandEncoders in the background on iOS when decoding images. Doing this is reported to cause pink squares or no image at all on physical iOS devices. 

### Impacted Users

iOS users who put the apps with images in the background

### Impact Description

Images may fail to render completely or show up as a bright pink square.

### Workaround

No.

### Risk

low

### Test Coverage

yes

### Validation Steps

Run the unit test.

**Comment by zanderso** [comment]
CP LGTM
