### ISSUE TITLE
Issue from website page IDE Setup

### ISSUE THREAD

**Issue by darrencole** [flutter/flutter#12770]
From URL: https://flutter.io/intellij-setup.md

Correct me if I'm wrong but isn't it true that Android Studio doesn't support Dart? However, the setup documentation says "Both IntelliJ CE and Android Studio are free to use and supported for Flutter development." Since Dart is a big part of Flutter development, this might be confusing to a newbie like myself who is trying to select the most appropriate IDE.

regards,

**Comment by sethladd** [comment]
cc @mit-mit @devoncarew

**Comment by devoncarew** [comment]
Actually, Android Studio does support Dart; Android Studio generally supports the same plugins and plugin API as other IntelliJ platforms. The Flutter plugin does depend on the Dart plugin - they both can install into Android Studio. Thanks for the note!

**Comment by sethladd** [comment]
We may want to take a fresh look at this page.

The headers "Installing IntelliJ" and "Flutter IntelliJ IDE plugins" and "n IntelliJ IDE" might lead to confusion if we then also say "Android Studio".

**Comment by mit-mit** [comment]
Yes, this can be clearer. Attempting fix in https://github.com/flutter/website/pull/728

**Comment by sethladd** [comment]
thanks!
