### ISSUE TITLE
Font family fallback not working on web 

### ISSUE THREAD

**Issue by ismaelAbogabal** [flutter/flutter#127809]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Try to download multiple font files into the assets folder for example 
   1. Poppines
   2. NotoColorEmoji
2.  Configure it in the theme file so ```Poppins``` is the main family and ```NotoColorEmoji``` is a fallback one 
3. Add a text file with an icon like ⬇️ and encounter the issue 

The issue is that ```NotoColorEmoji!``` has zero effect on the text it will not work unless its set as the main family 
Same thing the Poppins not working unless its the main font family so may by the font fallback system isn't working on web 

### Expected results

Showing the glyph as it comes from the Noto font 

### Actual results

Showing the icons of the platform. 

### On theme.dart file 

```dart 
   textTheme: ThemeData().textTheme.apply(
            fontFamily: 'Poppins',
            fontFamilyFallback: [
              'NotoColorEmoji',
            ],
            bodyColor: AppColors.textColor,
          )
          
```
### On the UI file 

```dart 
Text("⬇️ some text")  
```        

### Flutter Doctor output

[√] Flutter (Channel stable, 3.10.1, on Microsoft Windows [Version 10.0.22621.1702], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.26)
[√] Android Studio (version 2022.2)
[√] IntelliJ IDEA Ultimate Edition (version 2023.1)
[√] Connected device (4 available)
[√] Network resources

**Comment by huycozy** [comment]
Hi @ismaelAbogabal 
I've triggered `fontFamilyFallback` by removing `fontFamily` and I see it works as expected:

<details>
<summary>Demo (Web)</summary>

![Screenshot 2023-05-30 at 15 18 21](https://github.com/flutter/flutter/assets/104349824/7aa4cc10-3234-42fc-803c-83952e815c26)
</details>

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      theme: ThemeData(
        useMaterial3: true,
        textTheme: ThemeData().textTheme.apply(
          // fontFamily: 'Poppins',
          fontFamilyFallback: [
            'NotoColorEmoji',
          ],
        ),
      ),
      home: const MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(child: Text("⬇️ some text")),
    );
  }
}
```
</details>

Is that the expected result? Or am I missing something?

**Comment by huycozy** [comment]
@ismaelAbogabal For HTML renderer, this feature isn't implemented on Web yet. Please follow up on https://github.com/flutter/flutter/issues/32233 for further updates. 

Closing this issue as a duplicate. Thank you!
