### ISSUE TITLE
[iOS][A11y] Switch control can't select date in day picker

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#127863]
b/236668547

### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. click select data
2. turn on switch controll

### Expected results

The focus is able to reach selectable dates in the picker

### Actual results

The focus can't reach selectable dates in the picker

### Code sample

<details><summary>Code sample</summary>

```dart
import 'dart:async';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  DateTime currentDate = DateTime.now();

  Future<void> _selectDate(BuildContext context) async {
    final pickedDate = await showDatePicker(
      context: context,
      initialDate: currentDate,
      firstDate: DateTime(2015),
      lastDate: DateTime(2050),
    );
    if (pickedDate != null && pickedDate != currentDate) {
      setState(() {
        currentDate = pickedDate;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("DatePicker"),
      ),
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text(currentDate.toString()),
            ElevatedButton(
              onPressed: () => _selectDate(context),
              child: const Text('Select date'),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by chunhtai** [comment]
It seems like the switch control only focus item with certain UIAccessibilityTrait, we should figure out how. We can try to use accessibility inspector to see what traits are set for native date picker.

An example native date picker
https://developer.apple.com/documentation/swiftui/datepicker

**Comment by QuncCccccc** [comment]
Just tried to reproduce this issue and noticed that if we turn on speech in Switch Control, then we can select date(see the first demo below), but if we keep the speech off, date is not selectable.

https://github.com/flutter/flutter/assets/36861262/67662f74-db91-4744-ba49-a793b5b0477c

https://github.com/flutter/flutter/assets/36861262/61804033-42c4-401a-9b92-cd7c21f2f191

**Comment by QuncCccccc** [comment]
Setting the `Semantics.button` to true for the date item can fix this problem. Currently other than the `button` property, I don't find other traits to make the date selectable. Will create a PR for the fix to unblock the team.
