### ISSUE TITLE
Tree closed on FTL infra failures

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#127884]
For example https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20firebase_android_embedding_v2_smoke_test/13154/overview

**Comment by zanderso** [comment]
cc @dnfield

**Comment by zanderso** [comment]
`Failed  │ oriole-33-en-portrait  │ App failed to install`

**Comment by zanderso** [comment]
cc @reidbaker is this failure expected until https://github.com/flutter/engine/pull/42351 rolls in?

**Comment by reidbaker** [comment]
No this got caught by android tests running on post submit. I need to update the test apps to meet api 33 guidelines. 
@godofredoc is there a way to make api 33 device testing only non blocking? if not then I will need to revert https://flutter-review.googlesource.com/c/recipes/+/45048

**Comment by reidbaker** [comment]
https://flutter-review.googlesource.com/c/recipes/+/45181

**Comment by vashworth** [comment]
Some presubmit tests failed on this: https://github.com/flutter/flutter/pull/127875

**Comment by godofredoc** [comment]
@reidbaker unfortunately is not possible to mark a portion of the configs non blocking.

**Comment by godofredoc** [comment]
CL to move firebaselab configurations to .ci.yaml: https://flutter-review.googlesource.com/c/recipes/+/45182
