### ISSUE TITLE
[Impeller] Different font weight vs Skia (light on dark)

### ISSUE THREAD

**Issue by PiN73** [flutter/flutter#127810]
Starting from Flutter 3.10, Impeller is used by default on iOS. Small text seems to render noticeably different

### Steps to reproduce

1. Create new app

2. Place light text on dark background

```dart
ColoredBox(
  color: Colors.black,
  child: Text('Hello', style: TextStyle(color: Colors.white)),
)
```

3. Run the app with Flutter 3.10.2 on iOS

### Expected results

The text should render like in Skia

<img alt=dark_skia src=https://github.com/flutter/flutter/assets/18294052/ed152db3-1e1c-4020-bd62-a22ac771550e height=160>

### Actual results

The text renders thinner

<img alt=dark_impeller src=https://github.com/flutter/flutter/assets/18294052/1540425d-b156-4970-b5a6-21018206f106 height=160>

### Details

<details><summary>Full code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Material(
        color: Colors.black,
        child: Center(
          child: Text(
            'Hello',
            style: TextStyle(
              color: Colors.white,
            ),
          ),
        ),
      ),
    );
  }
}
```

To reproduce old **Skia** behavior on Flutter 3.10
```console
flutter run --no-enable-impeller
```

To crop and scale screenshot (iPhone 14):
```console
convert screenshot.png -gravity center -crop 100x40+0+0 -scale 800% out.png
```

</details>

<details><summary>Tools versions</summary>

```console
Flutter (Channel stable, 3.10.2, on macOS 13.3.1 22E261 darwin-arm64, locale en-RU)
Xcode - develop for iOS and macOS (Xcode 14.3)
Android Studio (version 2022.2)

Flutter 3.10.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9cd3d0d9ff (6 days ago) • 2023-05-23 20:57:28 -0700
Engine • revision 90fa3ae28f
Tools • Dart 3.0.2 • DevTools 2.23.1
```

All the same on master:
```console
Flutter 3.11.0-14.0.pre.70 • channel master •
https://github.com/flutter/flutter.git
Framework • revision bd11ef06fd (8 hours ago) • 2023-05-29 11:50:25 -0400
Engine • revision f768be1078
Tools • Dart 3.1.0 (build 3.1.0-155.0.dev) • DevTools 2.23.1
```

</details>

**Comment by PiN73** [comment]
Note: if we swap the colors (dark on light), Impeller font weight matches Skia (could have been fixed in #119234)

### Skia
<img alt=light_skia src=https://github.com/flutter/flutter/assets/18294052/361c2a81-a573-4c00-9437-880ef0650015 height=160>

### Impeller
<img alt=light_impeller src=https://github.com/flutter/flutter/assets/18294052/35204c3d-d3aa-478f-83a8-96e1802ffa71 height=160>

The only thing which still looks wrong is kerning

**Comment by PiN73** [comment]
Just noticed that native version looks more similar to Impeller than Skia

<img alt=dark_swiftui src=https://github.com/flutter/flutter/assets/18294052/fc81669e-ad97-4240-8ba9-90af250a50f8 height=160>

```swift
import SwiftUI

struct ContentView: View {
    var body: some View {
        Text("Hello")
        .font(.system(size: 14))
        .foregroundColor(.white)
        .frame(maxWidth: .infinity, maxHeight: .infinity)
        .ignoresSafeArea()
        .background(.black)
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}
```

So maybe it was Skia that was wrong 🤔

**Comment by huycozy** [comment]
Hi @PiN73 
Thanks for the detailed report! However, this is a known issue being tracked at https://github.com/flutter/flutter/issues/120857. You can take a look at https://github.com/flutter/flutter/issues/120857#issuecomment-1434118870 that also compared different between Skia and Impeller. Per your last test on iOS native, it matched with Impeller output. 

Since Impeller is enabled by default from 3.10, I assume this issue has been fixed. If you still go with Skia, please follow https://github.com/flutter/flutter/issues/120857 for further updates. 

Closing the issue as a duplicate. Thank you!
