### ISSUE TITLE
flutter video player too many requests to get a mp4 video

### ISSUE THREAD

**Issue by amirmhmdi** [flutter/flutter#127833]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

**ExoPlayer make 3 requests to load video file** from my http server. For each request, the server returns the entire file.

First HTTP request: no range header - server return all video file
Second HTTP request: Range request server return part of video file
Third HTTP request: Range: request server return the rest of previous range request file

I searched on exoplayer issue and find this one => https://github.com/google/ExoPlayer/issues/6635

I change the Mp4 file with the Ffmpeg and move moov box to the first of mp4 but it doesn't wok correctly, when I change moov box to the first of video exoplayer does not send Range request any more. It just send one simple http request without range request and it wait until get all file.

I used both latest video player version and latest flutter version and the old flutter version both are the same.

### Expected results

when a mp4 video url I want to load, I expect one or more range request with response 206.

### Actual results

but exoplayer request and give all video content more than three time.

First HTTP request: no range header - server return all video file
Second HTTP request: Range request server return all video file
Third HTTP request: Range: request server return all video file

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key key}) : super(key: key);

  
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  VideoPlayerController controller;

  @override
  void initState() {
    controller = VideoPlayerController.network(
      "https://pinno.app/api/internal/cdb/contents/6454a6bb-218b-47df-acf6-708695b2abab/0/37519438",
    );
    controller.initialize().then((value) {
      controller.play();
      controller.setLooping(true);
      setState(() {});
    });
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: SelectableText("http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8"),
      ),
      body: Center(
          child: controller.value.isInitialized
              ? AspectRatio(aspectRatio: controller.value.aspectRatio, child: VideoPlayer(controller))
              : const CircularProgressIndicator()), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6.5 20G527 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] VS Code (version 1.78.0)
[✓] Connected device (1 available)

```

</details>

**Comment by dam-ease** [comment]
Hi @amirmhmdi. Thanks for filing this issue. From this [thread](https://github.com/google/ExoPlayer/issues/6635), exoplayer seems to be working as intended. Can you confirm that the issue happens in native Android or if it is just limited to Flutter?

**Comment by amirmhmdi** [comment]
Hi @dam-ease 
Thank you for your quick response
I am not really expert in exoplayer and it configs but I do what this thread said but I still have problem with it.
It is simple, every sample application which it use videoplayer plugin, for every mp4 file exoplayer make too meny connecion to server and get multiple time the whole file.

**Comment by dam-ease** [comment]
Hi @amirmhmdi. The issue is coming from exoplayer, not `video_player`. `video_player` makes use of `exoplayer` https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md#2186-2023-04-18, which is one version from the latest. Since the issue is coming from the underlying `exoplayer`, you can try investigating on the native side to see if you can report the issue to them. Unfortunately, there’s nothing for the Flutter team to do here as this is how `exoplayer` works.
