### ISSUE TITLE
[releases] Skip needs test logic on release PRs

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#127808]
Release branches are CPs of existing commits, and should not run the bot. This adds extra noise to the release PRs.

We should add a check like `pr.base.branch == Config.defaultBranch(pr.slug())` to early exit on the Cocoon logic.

**Comment by CaseyHillers** [comment]
See https://github.com/flutter/flutter/pull/127696

**Comment by itsjustkevin** [comment]
@CaseyHillers could you point to where the logic is for this issue?  Seems like it could be a few hours or less fix.

**Comment by CaseyHillers** [comment]
I sent https://github.com/flutter/flutter/issues/127808 for the fix
