### ISSUE TITLE
Weird interactions between Form#onChanged and FormState#reset

### ISSUE THREAD

**Issue by niktekusho** [flutter/flutter#127841]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Open and run the example at https://dartpad.dev/?id=fc62719dac640d4bc2e92d61becbeb92
2. Write some text in the form field and submit the form

### Expected results

Form is cleared as expected after the submit.

### Actual results

Form is "cleared" with the value inputted by the user.

Using a debugger, I could see that the `widget.initialValue` used here is actually the text the user entered and not an empty string or null.
https://github.com/flutter/flutter/blob/164fd993d70c635b8f6adced275859a7de8566cc/packages/flutter/lib/src/material/text_form_field.dart#L366-L372

### Code sample

<details><summary>Code sample</summary>

View on Dartpad: https://dartpad.dev/?id=fc62719dac640d4bc2e92d61becbeb92

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.1, on macOS 13.3.1 22E772610a darwin-x64, locale en-IT)
    • Flutter version 3.10.1 on channel stable at /usr/local/Caskroom/flutter/3.10.0/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (2 weeks ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/<redacted>/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • iPad (10th generation) (mobile) • <redacted> • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)                 • macos                                • darwin-x64     • macOS 13.3.1 22E772610a darwin-x64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 113.0.5672.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

Might be related to #113327

**Comment by niktekusho** [comment]
Might be related to #113327

**Comment by huycozy** [comment]
Hi @niktekusho 
I see there's an open issue addressing the case you described https://github.com/flutter/flutter/issues/123009 that seems to be similar. Can you check if it is?

**Comment by niktekusho** [comment]
> Hi @niktekusho I see there's an open issue addressing the case you described #123009 that seems to be similar. Can you check if it is?

Hi @huycozy, it could probably be related but in my example, the `Form.onChanged` is regularly called and the TextFormField is wired with a TextEditingController.

**Comment by huycozy** [comment]
Yes, I notice Form's `onChanged is invoked when calling `reset()` whilst `TextFormField` is not (this makes a difference with https://github.com/flutter/flutter/issues/123009).

But if you remove Form's `onChanged` callback, it works as expected. Going further with this clue, you are calling `_formKey.currentState!.validate()` inside the callback, it does rebuild in the underlying methods. This is intended behavior. Also, if you want to validate the form on each change, your current `AutovalidateMode.onUserInteraction` is enough for that purpose.

>As I said though, I'm confused by the inspection I did with the debugger where widget.initialValue is not an empty string (or null) but it's exactly what the user wrote submitting the field.

I'm not sure I can get this point if it's related to the issue.  When you call `reset`, the `initialValue` is putted back to the field if you declared it on parameter.

**Comment by anhlevfx** [comment]
I'm facing the same issue, TextFormField with a custom controller won't reset to empty when I call reset() of formState. Because if initialValue is null, it will be set by the current value of the controller in constructor of the widget `initialValue: controller != null ? controller.text : (initialValue ?? ''),`. The problem is TextEditingController was created in parent scope, so the value doesn't change when we rebuild TextFormField before calling reset(). So, I think if not rebuild the widget, reset() will work.
