### ISSUE TITLE
in_app_purchase_android v0.3.0 migration guide

### ISSUE THREAD

**Issue by xvrh** [flutter/flutter#127844]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

[in_app_purchase_android v0.3.0](https://pub.dev/packages/in_app_purchase_android) seems to be a BIG breaking release. (if I'm not wrong, it comes from this PR: https://github.com/flutter/packages/pull/3752)

Classes changed name, lot of properties were removed and replaced by a totally different model.

I can't find a proper changelog or migration guide about all the changes and how to update our usage (`subscriptionPeriod`, `freeTrialPeriod`, `introductoryPricePeriod` etc...).

This issue asked about it https://github.com/flutter/flutter/issues/127766 but the discussion turned into how to specify the pubspec constraints and the documentation question was marked off-topic.

### Proposal

Provide a changelog or migration guide.

**Comment by stuartmorgan** [comment]
> This issue asked about it #127766 but the discussion turned into how to specify the pubspec constraints and the documentation question was marked off-topic.

The issue didn't "turn into" a discussion about pubspec contraints, the issue that was reported was specifically requesting an unnecessary breaking version change in the app facing package, and the reason for that request was due to a misuse of dependency management. How packages are versioned is unrelated to migration documentation.

**Comment by stuartmorgan** [comment]
cc @JeroenWeener

**Comment by Acuari0** [comment]
where is product_details_wrapper.dart ??

**Comment by JeroenWeener** [comment]
Hi @Acuari0,

`product_details_wrapper.dart` can be found `lib/src/billing_client_wrappers/`.

**Comment by mcianci** [comment]
@JeroenWeener could you please include also the tut for introductory price?

**Comment by owjoh** [comment]
Does anybody know of a tutorial for getting the free-trial from a product? I can never get the offers to be returned and only the base plan details are returned

**Comment by mcianci** [comment]
> Hi @mcianci!
> 
> I just updated [this PR](https://github.com/flutter/packages/pull/4137) to include the use case of introductory prices. Please let me know if they cover what you need.

Hi @JeroenWeener. Following the tut it compiles correctly but for some reason it doesn't detect introductory prices that I have configured on the store. Need to take a deeper look. Thanks

**Comment by JeroenWeener** [comment]
@owjoh I tested fetching trial subscriptions with the example app. In doing so, I discovered an oversight in the migration guide.

A `ProductDetailsWrapper` belongs to a single `SubscriptionOfferDetails`, even though it contains multiple in the original object. To fetch the one represented by this `ProductDetailsWrapper`, one should get the one at index `ProductDetailsWrapper.subscriptionIndex`. See the updated migration guide in https://github.com/flutter/packages/pull/4137 for the complete example.


I created a subscription in the Play Console with a free trial offer and was able to fetch both of them.

Subscription in Play Console
<img width="1707" alt="Screen Shot 2023-06-13 at 14 57 58" src="https://github.com/flutter/flutter/assets/9049645/c478f11c-2ecc-43c7-a2f7-21b428ead471">

Example app
![unnamed](https://github.com/flutter/flutter/assets/9049645/7b49c103-17f1-41e3-8e8c-7ccdf9548fba)

Example app code
<img width="513" alt="Screen Shot 2023-06-13 at 15 15 05" src="https://github.com/flutter/flutter/assets/9049645/72aa06e9-04dc-4504-a462-413e7e460b8a">

Please let me know if the updated migration guide helps you solve your issue or if you need more help.

(I notice that your screenshot does not mark the offer as 'backward compatible'. Offers do not have to be backward compatible, but if your code doesn't work after these steps, it could be the next thing we can look into.)

**Comment by JeroenWeener** [comment]
@mcianci I updated the migration guide slightly (see previous comment) for subscription use cases, including introductory prices. Could you have a look and let me know if the new example code helps you in solving your problem?
