### ISSUE TITLE
Transparent Video video_player package

### ISSUE THREAD

**Issue by bermanapps** [flutter/flutter#127805]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I cannot play a video with a transparent background.

### Proposal

I need the ability to play a video which has a transparent background, so that I can play the video, with a custom background of my choice.

**Comment by huycozy** [comment]
Can you please be more specific? Do you have any sample visuals (image/gif/video) for the expected result?

**Comment by bermanapps** [comment]
Lets say like this. Placing this video on an image background.

https://github.com/flutter/flutter/assets/28511238/32248e68-0afe-4bfb-8f2c-1821c3be7183

**Comment by huycozy** [comment]
I tried extracting the video into frames (using this [website](https://ezgif.com/video-to-jpg)) and I see the black background as well. That being said, the provided video doesn't not transparent background and `video_player` is rendering as expected. 

Also, if you could give more information about the feasibility of this on native libraries (Android/iOS) or native apps, it would be helpful to investigate.
