### ISSUE TITLE
Text rendered in a pixelated way in versions higher than version 3.10, especially when it appears next to an emoticon or svg, on IOS.

### ISSUE THREAD

**Issue by BrandowBuenos** [flutter/flutter#127889]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Install flutter versions in stable version above 3.10
2. Run the application with this version
3. Compare the same app using different versions of flutter, like the latest master version or versions below the mentioned one

### Expected results

Currently, text rendering is pixelated, coarse and out of harmony with what should be between font, contrast and images.

### Actual results

I expect results like using master builds or versions lower than 3.10.

### Code sample

<details><summary>Code sample</summary>

```dart
All text widgets reproduce this error, especially when it appears next to an emoticon or svg
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

## Before 3.10
![IMG_5153](https://github.com/flutter/flutter/assets/52222495/060db3f5-1a71-4795-8a86-b9da53a86a63)
![IMG_5154](https://github.com/flutter/flutter/assets/52222495/6eeee529-e067-4368-933f-8f9e077353ae)
https://github.com/flutter/flutter/assets/52222495/8a769a53-6f76-4fe9-9223-8e99ad8a6220

## After 3.10
![IMG_5158](https://github.com/flutter/flutter/assets/52222495/63c9db5c-1534-4903-89b3-af9c3767bf9d)
![IMG_5159](https://github.com/flutter/flutter/assets/52222495/2043eea8-02a9-4fa9-ad15-a2806eb63022)
https://github.com/flutter/flutter/assets/52222495/241ceb34-a5aa-43b6-9d3d-45c34bf06164

### 🔥 PS: The error clearly appears in the last video. pay attention to the bottomNavigationBar font weights during seconds 03 - 05 and then in seconds 09 - 11.

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.2, on macOS 13.4 22F66 darwin-arm64, locale
    en-BR)
    • Flutter version 3.10.2 on channel stable at
      /Users/brandowbuenos/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (7 days ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/brandowbuenos/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-arm64 • macOS 13.4 22F66 darwin-arm64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by armandojimenez** [comment]
I see the same with custom fonts and SVGs

**Comment by Lucasmaia435** [comment]
> I see the same with custom fonts and SVGs

Me too.

**Comment by danagbemava-nc** [comment]
Hi @BrandowBuenos, the issue has been fixed on the `master` channel which is why you do not see it there. It was likely fixed by this pr https://github.com/flutter/engine/pull/41780. 

We have a cherry-pick process that you can go through to request that the fix be cherry-picked into the current stable. See https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process#frequently-asked-questions for the steps you can follow. 

Per our triage policy, I'll be closing this since it has already been fixed on the master channel.

Thank you
