### ISSUE TITLE
[Impeller] Consider switching to doubles for `impeller::Scalar`.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#127982]
We will eventually have to truncate down to floats before sending the data to GPU. But this way, the truncation will happen much later.

Consider the case where a rectangle whose dimensions are close to FLT_MAX is scaled up using the transformation stack and then subsequently scaled back down such that it still fits with the +-FLT_MAX. Today, the truncation will happen immediately while scaling up.

`dart:ui` also uses doubles throughout and the silent truncation isn't what users expect.

If we choose to do this, we would have to update the code generators to use float type scalars and perform implicit conversions.

**Comment by chinmaygarde** [comment]
cc @dnfield @gaaclarke @jonahwilliams

**Comment by jonahwilliams** [comment]
Important to note that dart:ui doesn't entirely use doubles, a few APIs accept Offsets (which are double based) only to convert them to floats via Float32List. (see drawPoints, drawRawPoints, drawAtlas, drawVertices).

**Comment by jonahwilliams** [comment]
We should not do this IMO, it would be churn for very little value. I'm closing the bug, re-open if you disagree
