### ISSUE TITLE
libtxt: per-character font fallback

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#12792]
Currently with libtxt if you have a text file that contains a variety of Unicode characters (and you don't have a font on your system that has all of them), it won't display properly, because it doesn't do per-character font fallback.

The old text system did do per-character font fallback.

You can test this using the "Test Font Fallback" feature of the `dev/manual_tests/text.dart` test (see https://github.com/flutter/flutter/pull/12791).

This is critical for i18n.

**Comment by Hixie** [comment]
cc @jason-simmons

**Comment by jason-simmons** [comment]
This has landed
