### ISSUE TITLE
FocusTraversalGroup issue: prefixIcon/suffixIcon gets focus in NumericFocusOrder

### ISSUE THREAD

**Issue by bahadirarslan** [flutter/flutter#127991]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I am developing an application for iPads and there are forms for users. So I thought I had to think about focus traversal so I followed the original documentation in my app just instead of using buttons I used TextField widgets.

### Expected results

I am expecting only TextField to get focus, not prefix or suffix icon buttons. Also soft keyboard's tab button work as expected.

### Actual results

TextField widgets that have prefixIcon or suffixIcon cause trouble because IconButtons get the focus when I press the tab button.

I am trying this on an iPad simulator so when I press the Tab button on my Mac it is shifting focus to another widget. But if I use the soft keyboard on the simulator it is not shifting focus, just inserting space char.

### Code sample

<details><summary>Code sample</summary>

Here is the sample code
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: SafeArea(
          child: FocusTraversalGroup(
              policy: OrderedTraversalPolicy(),
              child: Center(
                child: SizedBox(
                  width: MediaQuery.of(context).size.width * .75,
                  child: Column(
                    children: [
                      const FocusTraversalOrder(order: NumericFocusOrder(1.0), child: TextField()),
                      const Divider(),
                      FocusTraversalOrder(
                        order: const NumericFocusOrder(2.0),
                        child: TextField(
                            decoration: InputDecoration(
                          suffixIcon: IconButton(
                            icon: const Icon(Icons.delete),
                            onPressed: () {},
                          ),
                        )),
                      ),
                      const Divider(),
                      FocusTraversalOrder(
                        order: const NumericFocusOrder(3.0),
                        child: TextField(
                            decoration: InputDecoration(
                                prefixIcon: IconButton(
                                  icon: const Icon(Icons.add),
                                  onPressed: () {},
                                ),
                                suffixIcon: IconButton(
                                  icon: const Icon(Icons.delete),
                                  onPressed: () {},
                                ))),
                      ),
                    ],
                  ),
                ),
              )),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![Screen_Recording_2023-05-31_at_23_29_22_AdobeExpress](https://github.com/flutter/flutter/assets/130344/4bd118f8-aaf5-45fa-a9db-0494bcdf7c88)

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
bahadirarslan@Bahadirs-MBP mylog % flutter doctor -v
[✓] Flutter (Channel stable, 3.10.2, on macOS 13.3.1 22E261 darwin-arm64, locale en-TR)
    • Flutter version 3.10.2 on channel stable at /Users/bahadirarslan/Development/SDKS/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (8 days ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/bahadirarslan/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • My iPad (mobile) • 710F34BB-E394-48B1-8FE7-6C7FAFADD142 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)  • macos                                • darwin-arm64   • macOS 13.3.1 22E261 darwin-arm64
    • Chrome (web)     • chrome                               • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by bahadirarslan** [comment]
> I check this on other platforms as well (Web, macOS) and see it always focuses on `prefixIcon` or `suffixIcon` with Tab key. And I think it's correct behavior. 
> 
> 
> 
> For the solution, you can try `ExcludeFocus` on widgets that you don't want to gain focus, for eg:
> 
> ```dart
> 
> suffixIcon: ExcludeFocus(
> 
>   child: IconButton(
> 
>     icon: const Icon(Icons.delete),
> 
>     onPressed: () {},
> 
>   ),
> 
> ),
> 
> ```
> 
> 
> 
> <details>
> 
> <summary>Complete modified sample code</summary>
> 
> 
> 
> ```dart
> 
> import 'package:flutter/material.dart';
> 
> 
> 
> void main() {
> 
>   runApp(const MainApp());
> 
> }
> 
> 
> 
> class MainApp extends StatelessWidget {
> 
>   const MainApp({super.key});
> 
> 
> 
>   @override
> 
>   Widget build(BuildContext context) {
> 
>     return MaterialApp(
> 
>       home: Scaffold(
> 
>         body: SafeArea(
> 
>           child: FocusTraversalGroup(
> 
>               policy: OrderedTraversalPolicy(),
> 
>               child: Center(
> 
>                 child: SizedBox(
> 
>                   width: MediaQuery.of(context).size.width * .75,
> 
>                   child: Column(
> 
>                     children: [
> 
>                       const FocusTraversalOrder(order: NumericFocusOrder(1.0), child: TextField()),
> 
>                       const Divider(),
> 
>                       FocusTraversalOrder(
> 
>                         order: const NumericFocusOrder(2.0),
> 
>                         child: TextField(
> 
>                             decoration: InputDecoration(
> 
>                               suffixIcon: ExcludeFocus(
> 
>                                 child: IconButton(
> 
>                                   icon: const Icon(Icons.delete),
> 
>                                   onPressed: () {},
> 
>                                 ),
> 
>                               ),
> 
>                             )),
> 
>                       ),
> 
>                       const Divider(),
> 
>                       FocusTraversalOrder(
> 
>                         order: const NumericFocusOrder(3.0),
> 
>                         child: TextField(
> 
>                             decoration: InputDecoration(
> 
>                                 prefixIcon: ExcludeFocus(
> 
>                                   child: IconButton(
> 
>                                     icon: const Icon(Icons.add),
> 
>                                     onPressed: () {},
> 
>                                   ),
> 
>                                 ),
> 
>                                 suffixIcon: ExcludeFocus(
> 
>                                   child: IconButton(
> 
>                                     icon: const Icon(Icons.delete),
> 
>                                     onPressed: () {},
> 
>                                   ),
> 
>                                 ))),
> 
>                       ),
> 
>                     ],
> 
>                   ),
> 
>                 ),
> 
>               )),
> 
>         ),
> 
>       ),
> 
>     );
> 
>   }
> 
> }
> 
> ```
> 
> </details>
> 
> 
> 
> Please try this and confirm if it works for you.

Actually I am not sure it is supposed to work like this but anyway you suggested me what I am looking for :) I think `ExcludeFocus` will help me. 

Thank you

**Comment by huycozy** [comment]
You're welcome. Closing the issue as solved.
