### ISSUE TITLE
Google sign in version 6.1.0 requires http 0.13.5

### ISSUE THREAD

**Issue by GeorgePagounis** [flutter/flutter#127926]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Hello, I have 2 dependencies on my pubspec.yaml :

google_sign_in: ^6.1.2
http: ^1.0.0

but get the following message:

Because google_sign_in >=6.1.0 depends on google_sign_in_web ^0.12.0 which depends on http ^0.13.5, google_sign_in >=6.1.0 requires http ^0.13.5.
So, because /project_name/ depends on both google_sign_in ^6.1.2 and http ^1.0.0, version solving failed.

Of course I can just downgrade the http package, but this version is over 10 months old. Is there a plan to integrate the latest http package with google_sign_in in the future?

### Proposal

Google sign in should work with latest http package.

**Comment by stuartmorgan** [comment]
> Of course I can just downgrade the http package

You could also allow `">=0.13.6 <2.0.0"` and let the resolver handle it, since there is no new functionally in 1.0.0.

> Of course I can just downgrade the http package, but this version is over 10 months old.

Requiring `^0.13.5` is not the same thing as requiring `0.13.5`. The dependency in question is nine **days** out of date, not 10 months.

**Comment by stuartmorgan** [comment]
Since it's unlikely that we violate any of the new class restrictions in 1.0.0 we should be able to relax all our existing dependencies to include 1.x.

**Comment by GeorgePagounis** [comment]
Ah ok, thanks for clearing that up!

> Requiring `^0.13.5` is not the same thing as requiring `0.13.5`. The dependency in question is nine **days** out of date, not 10 months.
