### ISSUE TITLE
Give the possibility to chose hit behaviour for ReorderableList's items

### ISSUE THREAD

**Issue by Scerbelo12** [flutter/flutter#127941]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Hi,

I'm currently working with a ReorderableList, which items are composed by a row with some TextFormField's separated by empty spaces. With the current ReorderableList implementation, it's not possible to drag the items if the drag starts from an empty space in the row (SizedBox / Padding added to the TextFormField). After inspecting the source code, I found that the problem is related to the build method of the ReorderableDragStartListener, which returns a Listener with default behavior property (HitTestBehavior.deferToChild). 

### Proposal

I think it would be nice to have the possibility to chose the behavior of the items of the ReorderableList, cause it should't be a complicated thing to implement and it would be useful in some cases. From my understanding, it should be enough to add a property 'behavior' to the ReorderableList and ReorderableDragStartListener and  pass it to the Listener returned by the build method of ReorderableDragStartListener, which is currently implemented as follows:

```
class ReorderableDragStartListener extends StatelessWidget {
  const ReorderableDragStartListener({
    super.key,
    required this.child,
    required this.index,
    this.enabled = true,
  });

  @override
  Widget build(BuildContext context) {
    return Listener(
      onPointerDown: enabled
          ? (PointerDownEvent event) => _startDragging(context, event)
          : null,
      child: child,
    );
  }

  @protected
  MultiDragGestureRecognizer createRecognizer() {
    return ImmediateMultiDragGestureRecognizer(debugOwner: this);
  }

  void _startDragging(BuildContext context, PointerDownEvent event) {
    final DeviceGestureSettings? gestureSettings =
        MediaQuery.maybeOf(context)?.gestureSettings;
    final SliverReorderableListState? list =
        SliverReorderableList.maybeOf(context);
    list?.startItemDragReorder(
      index: index,
      event: event,
      recognizer: createRecognizer()..gestureSettings = gestureSettings,
    );
  }
}
```

**Comment by huycozy** [comment]
Hi @Scerbelo12, can you share the minimal sample code you are having the issue with?
