### ISSUE TITLE
[CP] Beta-Support minification for apps using AGP 8.0

### ISSUE THREAD

**Issue by reidbaker** [flutter/flutter#127969]
### issue_link

https://github.com/flutter/flutter/pull/127628

### Commit Hash

9376a2a

### Target

beta

### pr_link

https://github.com/flutter/flutter/pull/127968

### Changelog Description

Export proguard rules for integration_test so that it can be used in project that depend on AGP 8.0 

### Impacted Users

Flutter android devs using AGP 8.0 and integration_test package

### Impact Description

Cannot compile integration tests. 

### Workaround

Do not use AGP 8.0 or disable integration tests. 

### Risk

medium

### Test Coverage

yes

### Validation Steps

Easy repro steps in the linked bug but there is an integration test in framework to ensure the fix works. 
That said there could be side effects to the proguard rules since they apply to the whole app build. The risks there are minimal because integration_test package is used for testing not production.

**Comment by CaseyHillers** [comment]
@stuartmorgan can you review this CP request? If it looks good to you, add the "cp: approved" label.

**Comment by CaseyHillers** [comment]
This will ship in this week's 3.12 beta, and is no longer necessary
