### ISSUE TITLE
libtxt: Wavy underlines don't go all the way to the end of the text span

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#12794]
With libtxt, wavy underlines are always drawn an integral number of half-periods.
This means that text is sometimes not entirely underlined.

For example:
 
![screenshot_20171030-173957](https://user-images.githubusercontent.com/551196/32202390-a098bac6-bd99-11e7-9b72-8edc6d26f7d7.png)

You can test this using the "Test Underlines" feature of the dev/manual_tests/text.dart test (see #12791).

This is not a blocker. It's a regression because we used to render wavy partial underlines (non-integral multiple of the half period) but since our old rendering wasn't quite correct either it's not a big deal.

**Comment by cbracken** [comment]
@GaryQian believes this is likely no longer an issue, and will double-check this and close if so.

**Comment by GaryQian** [comment]
Just kidding this still exists. Ill fix it!

**Comment by GaryQian** [comment]
https://github.com/flutter/engine/pull/9468 manually calculates the bezier required to finish the wavy underline for any given width.

**Comment by GaryQian** [comment]
The fix depends on https://github.com/flutter/flutter/pull/35066 to roll into framework.
