### ISSUE TITLE
libtxt: crashes

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#12795]
Running the "TextSpan Fuzzer" feature of the dev/manual_tests/text.dart test (see #12791) crashes the engine in a few seconds.

This is critical for stability. It's not a regression; the old text rendering code crashed a lot also.

(The test doesn't yet try to avoid running out of memory, because right now the test doesn't run long enough for that to happen. In due course we'll have to update the test to avoid crashing due to OOM.)

**Comment by Hixie** [comment]
@jason-simmons Assigning this to you since you said this is what you were working on.

**Comment by jason-simmons** [comment]
This should be stable now
