### ISSUE TITLE
In app purchase subscription stream provides wrong AppStorePurchaseDetails on iOS

### ISSUE THREAD

**Issue by Haris2v** [flutter/flutter#127927]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Create a single subscription in the app store connect account and run the following commands on iOS side multiple times to buy and restore subscriptions

  InAppPurchase.instance.buyNonConsumable(purchaseParam: purchaseParam);
or
InAppPurchase.instance.restorePurchases();

For example: 
buyNonConsumable() and on successful test transaction, delete the app and reinstall the app. Then execute the restorePurchases() to restore your subscription.

Repeat the above step 5 to 7 times and then you will start receiving wrong and huge list of AppStorePurchaseDetails in subscription stream. 

### Expected results

As there is only one non-consumable subscription, there should be only one transaction details object on 
purchasing or restoring a subscription by using the following code: 

 InAppPurchase.instance.buyNonConsumable(purchaseParam: purchaseParam);
or
InAppPurchase.instance.restorePurchases();

This feature works perfectly fine on android side. 

### Actual results

By doing either buyNonConsumable or restorePurchases on iOS side, most of the times it returns a huge list of AppStorePurchaseDetails. 

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

![Screenshot 2023-05-31 at 1 29 49 PM](https://github.com/flutter/flutter/assets/49231547/89bb7f24-7bf2-4242-ad02-890bfd984a68)

### Flutter Doctor output

<details><summary>Doctor output</summary>

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.1, on macOS 13.4 22F66 darwin-x64, locale en-PK)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.75.1)
[✓] Connected device (4 available)
[✓] Network resources

! Doctor found issues in 1 category.

</details>

**Comment by maRci002** [comment]
https://pub.dev/packages/in_app_purchase#completing-a-purchase

> **Completing a purchase** [#](https://pub.dev/packages/in_app_purchase#completing-a-purchase)
> The InAppPurchase.purchaseStream will send purchase updates after initiating the purchase flow using InAppPurchase.buyConsumable or InAppPurchase.buyNonConsumable. After verifying the purchase receipt and the delivering the content to the user it is important to call InAppPurchase.completePurchase to tell the underlying store that the purchase has been completed. Calling InAppPurchase.completePurchase will inform the underlying store that the app verified and processed the purchase and the store can proceed to finalize the transaction and bill the end user's payment account.
> 

> > Warning: Failure to call InAppPurchase.completePurchase and get a successful response within 3 days of the purchase will result a refund.

Consider calling [completePurchase](https://pub.dev/documentation/in_app_purchase/latest/in_app_purchase/InAppPurchase/completePurchase.html) or direct call to [finishTransaction](https://pub.dev/documentation/in_app_purchase_storekit/latest/store_kit_wrappers/SKPaymentQueueWrapper/finishTransaction.html), otherwise:

If you don't finish the transaction by calling the `finishTransaction` method, the transaction will remain in a pending state in the payment queue. This means that the transaction is not fully completed or processed, and it can potentially cause issues if not handled properly.

Here are a few things that can happen if you don't finish the transaction:

1. Duplicate Purchases: If the user attempts to make the same purchase again while a previous transaction for the same product is still pending, it can result in duplicate purchases. This can lead to a negative user experience and potential refund requests.

2. Incomplete Restore Purchases: When the user tries to restore purchases, any pending transactions in the payment queue may interfere with the restore process. Incomplete transactions can prevent the restoration of previously purchased non-consumable items.

3. Unresolved Transaction State: Leaving transactions pending indefinitely can lead to an inconsistent or unresolved transaction state. This can make it difficult to track and manage the user's purchase history accurately.

To ensure a clean and reliable in-app purchase process, it's important to properly handle and finish transactions by calling the `finishTransaction` method. This should be done after you have successfully provided access to the purchased content or handled any failures or cancellations. By finishing the transaction, you ensure that it is properly completed, removed from the payment queue, and prevent any potential issues related to pending transactions.

**Comment by huycozy** [comment]
@Haris2v Please check your implementation again and correct it if you haven't called `completePurchase` as @maRci002 suggested above to see if the issue still persists or not. You can take a look at [plugin example](https://github.com/flutter/packages/tree/main/packages/in_app_purchase/in_app_purchase/example) as reference.

**Comment by Haris2v** [comment]
@maRci002 @huycozy  Could you please look at this code

Here is how I'm doing a purchase for subscription:

`  Future<void> purchaseItem(ProductDetails productDetails) async {
  Map<String, PurchaseDetails> _purchases =
      Map.fromEntries(purchases.map((PurchaseDetails purchase) {
    return MapEntry<String, PurchaseDetails>(purchase.productID, purchase);
  }));
  loading = true;
  if (Platform.isIOS) {
    late PurchaseParam purchaseParam;
    purchaseParam = PurchaseParam(
      productDetails: productDetails,
      applicationUserName: null,
    );
    try {
      var transactions = await SKPaymentQueueWrapper().transactions();
      if (transactions.isNotEmpty) {
        for (var skPaymentTransactionWrapper in transactions) {
          SKPaymentQueueWrapper().finishTransaction(skPaymentTransactionWrapper);
        }
        loading = false;
      } else {
        inAppPurchaseInstance.buyNonConsumable(purchaseParam: purchaseParam);
      }
    } catch (e) {
      debugPrint('--> error in iOS purchase: $e');
    }
  } else {
    final GooglePlayPurchaseDetails? oldSubscription =
        getOldSubscription(productDetails as GooglePlayProductDetails, _purchases);

    final GooglePlayPurchaseParam purchaseParam = GooglePlayPurchaseParam(
        productDetails: productDetails,
        changeSubscriptionParam: oldSubscription != null
            ? ChangeSubscriptionParam(
                oldPurchaseDetails: oldSubscription,
                prorationMode: ProrationMode.immediateWithTimeProration)
            : null);
    inAppPurchaseInstance.buyNonConsumable(purchaseParam: purchaseParam);
  }
}
  `
  
  **And here goes subscription stream listener:**
  
  `  
final Stream<List<PurchaseDetails>> purchaseUpdated = purchaseViewModel.inAppPurchaseInstance.purchaseStream;
  purchaseViewModel.subscription = purchaseUpdated.listen((purchaseDetailsList) {
    if(purchaseDetailsList.isNotEmpty) {
      _listenToPurchaseUpdated(purchaseDetailsList, purchaseViewModel);
    }
  }, onDone: () {
    purchaseViewModel.subscription.cancel();
  }, onError: (error) {
    purchaseViewModel.subscription.resume();
  });`
  
  **and here is _listenToPurchaseUpdated() method**
  
` Future<void> _listenToPurchaseUpdated(List<PurchaseDetails> purchaseDetailsList, InAppPurchaseViewModel purchaseViewModel) async {

 if (purchaseDetails.pendingCompletePurchase) {
        await purchaseViewModel.inAppPurchaseInstance.completePurchase(purchaseDetails);
      } else {
// do other work here
}} `


Honestly I have added the finishTransaction() method a month ago to my code. But don't know if transactions are still being duplicated or those are are the old transactions that are appearing in stream. I'll let you know but the issue is if older transactions are completed through this code, then why they are appearing again and again. And the most strange this is those number of transactions are not same every time. Sometimes I got only one transaction, sometimes I got 71 and sometimes I got 42 and so on. 

**Please note this issue only appears on a physical iOS device and on simulators I never faced this issue**

**Comment by maRci002** [comment]
It's hard to read your pieces of code, but you can check out the flow: https://github.com/flutter/flutter/issues/119620#issuecomment-1428135797

**Comment by maRci002** [comment]
I think your best bet to log every useful attributes of [`PurchaseDetails`](https://pub.dev/documentation/in_app_purchase_platform_interface/latest/in_app_purchase_platform_interface/PurchaseDetails-class.html).
 - [purchaseID](https://pub.dev/documentation/in_app_purchase_platform_interface/latest/in_app_purchase_platform_interface/PurchaseDetails/purchaseID.html)
 - [productID](https://pub.dev/documentation/in_app_purchase_platform_interface/latest/in_app_purchase_platform_interface/PurchaseDetails/productID.html)
 - [status](https://pub.dev/documentation/in_app_purchase_platform_interface/latest/in_app_purchase_platform_interface/PurchaseDetails/status.html)
 - [transactionDate](https://pub.dev/documentation/in_app_purchase_platform_interface/latest/in_app_purchase_platform_interface/PurchaseDetails/transactionDate.html)
 - [verificationData](https://pub.dev/documentation/in_app_purchase_platform_interface/latest/in_app_purchase_platform_interface/PurchaseDetails/verificationData.html)

You will see there should not be any duplicates of same `purchaseID`

**Comment by huycozy** [comment]
@Haris2v Please try the suggestion above. And you can also try running plugin example to see if the issue still persists or not (need to update your product IDs there)

**Comment by Haris2v** [comment]
@huycozy  I have tried @maRci002 recommendations and there are no new duplicates on my side. But the main issue is how I can remove the duplicated transactions from older devices.

**Comment by maRci002** [comment]
> @huycozy I have tried @maRci002 recommendations and there are no new duplicates on my side.

What do you mean by "on my side"?

> But the main issue is how I can remove the duplicated transactions from older devices.

https://pub.dev/packages/in_app_purchase#completing-a-purchase

> Calling `InAppPurchase.completePurchase` will inform the underlying store that the app verified and processed the purchase and the store can proceed to finalize the transaction and bill the end user's payment account.
> 

> > Warning: Failure to call `InAppPurchase.completePurchase` and get a successful response within 3 days of the purchase will result a refund.

If yo don't call `InAppPurchase.completePurchase` / `finishTransaction` then the transaction will be automatically refunded, it will no longer appear in the payment queue when you query it using `SKPaymentQueue.default().transactions`. The refunded transaction will not be visible to your app, and you won't be able to retrieve its details or status.

Which means they will disappear.

**Comment by maRci002** [comment]
> but out of 10 times round about 3 to 4 times duplicate transactions appear in `SKPaymentQueue.default().transactions`

How do you know they are duplicates? What are their status?

**Comment by Haris2v** [comment]
Closing this as no one is here to truly understand the situation.
