### ISSUE TITLE
flutter format doesn't work with --dry-run or --machine

### ISSUE THREAD

**Issue by passsy** [flutter/flutter#12797]
## Steps to Reproduce

running `flutter format lib -n` errors with: `Cannot use --dry-run and --overwrite at the same time.`

running `flutter format lib -m` errors with: `Cannot use --overwrite and --machine at the same time.`

in both cases I don't have explicitly set `--overwrite` (`-w`).

```
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-DE, channel unknown)
    • Framework revision e8aa40eddd (13 days ago), 2017-10-17 15:42:40 -0700
    • Engine revision 7c4142808c
    • Tools Dart version 1.25.0-dev.11.0
```

## Bug
the [flutter format command](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/format.dart#L40) always appends `-w` which causes this problem

## Workaround

call `dartfmt` instead of `flutter format`

## Possible solutions

1. don't expose all `dartfmt` arguments
2. append `-w` only if `-n` or `-m` are not set

## Scenario

I intend to use `flutter format` on CI to enforce a common code style. `-m` would allow better output in json format.

**Comment by rock3r** [comment]
+1 for this, I'm hitting the very same issue.

**Comment by zanderso** [comment]
This looks done:
https://github.com/flutter/flutter/blob/c725f107a178edf04a8ecf857597dc0c131c8933/packages/flutter_tools/lib/src/commands/format.dart#L69

**Comment by henghadawang** [comment]
> +1 for this, I'm hitting the very same issue. For now I can "just" pass `--set-exit-if-changed` instead, but that means source files will be changed (as `-w` is always added) which is not something I'd want in a CI.


Use  `flutter format lib -n`  to solve

**Comment by felix-ht** [comment]
The trick is to but the options before the format command:

**Works**
`flutter format -n lib`

**Fails**
```bash
flutter format lib -n
Cannot use --dry-run and --overwrite at the same time.
```
