### ISSUE TITLE
`flutter analyze --flutter-repo` should analyze `analysis_options.yaml`

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#127989]
`flutter analyze --flutter-repo` currently does not analyze the `analysis_options.yaml` at the root of the repository. This caused us to miss some warnings about deprecated lints in that file. The command should be updated to analyze that file as well since it is part of the repository and it may have issues reported by the analyzer.

Steps to repro the failure to report deprecated lints in that file:

1. Add the deprecated lint `iterable_contains_unrelated_type` to the [analysis_options.yaml](https://github.com/flutter/flutter/blob/master/analysis_options.yaml) at the root of the repository.
2. Verify that the analyzer reports a deprecated lint when analyzing this specific file alone: `flutter analyze analysis_options.yaml`.
3. Run `flutter analyze --flutter-repo` and observe that no deprecated lint is reported.

Expected Output:

```
   info • 'iterable_contains_unrelated_type' is deprecated and should be replaced by 'collection_methods_unrelated_type' • analysis_options.yaml:113:7 •
          deprecated_lint_hint_with_replacement
```

Actual Output: nothing reported.

**Comment by goderbauer** [comment]
While looking at this I noticed that the Flutter tool actually jumps through some extra hoops to only analyze the `dev`, `examples`, and `packages` directory:

https://github.com/flutter/flutter/blob/19719e33c8e79612e4d2d153ba1fa0a13ba4f513/packages/flutter_tools/lib/src/runner/flutter_command_runner.dart#L312-L318

I wonder why we decided to do that? It seems like it would be easier to just run the analyze command on the root of the repository and use the `excludes` section in the `analysis_options.yaml` file to exclude the only directory we don't want to analyze: `bin`. (We already use the `excludes` section to exclude other parts of the repo from analysis.) This would also ensure that the `analysis_options.yaml` file itself at the root of the repo is analyzed.

In theory, with this approach we could even deprecated the `--flutter-repo` special flag and just run `flutter analyze .` in the root of the repository everywhere (e.g. on CI)...

**Comment by whesse** [comment]
The fix landed for this issue runs the analyzer on all subdirectories of the flutter checkout, and that can include user-created directories that don't contain flutter source at all.

For example, to make a hermetic image for flutter, Golem puts the pub cache in a pub-cache directory, and sets the analysis server temp directory to .dartServer, both in the root directory of flutter.  I see notes where other users put config directories here rather than in their home directory.  Only files that are part of the flutter repo should be analyzed by this command.
