### ISSUE TITLE
Preserve previous log after a hot reload

### ISSUE THREAD

**Issue by iota9star** [flutter/flutter#127909]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

In most cases, we modify code to fix previous issues. If we can preserve the previous logs, it would be easy for us to compare with the previous logs. The previously printed information may also contain critical information, and if cleared, we need to repeat the process to react. If we save the logs before the hot update, it will be cumbersome.

### Proposal

As the title suggests, after each hot reload, preserve the previous logs and do not clear them.

**Comment by huycozy** [comment]
Hi @iota9star 
As far as I can see, the proposal is best suited to separated IDEs for better support there. 

For Intellij: https://github.com/flutter/flutter-intellij
For VSCode: https://github.com/Dart-Code/Dart-Code

I'm not sure if this can be related to Flutter tool. Please correct me if I'm missing anything from your proposal.

**Comment by iota9star** [comment]
It should be specific to the IDE platform, I will close this issue.
