### ISSUE TITLE
[tool_crash] StateError: Bad state: No running isolate (inspector is not set).

### ISSUE THREAD

**Issue by bstardust** [flutter/flutter#127913]
## Command
```
flutter run -d chrome --web-port=5000 --web-renderer html
```

## Steps to Reproduce
1. App runs normally, and then crashes unexpectedly without specific steps to reproduce ¯\\\_(ツ)_/¯
2. Started happening today (May 31st 2023) and its occurred 3 times so far, everything was working fine without crashing for the last few weeks of build
3. Not sure what exactly is causing the crash, or how to remedy, apologies for the vague bug

## Logs
StateError: Bad state: No running isolate (inspector is not set).
```
#0      ChromeProxyService.inspector (package:dwds/src/services/chrome_proxy_service.dart:79:7)
#1      ChromeProxyService._prewarmExpressionCompilerCache (package:dwds/src/services/chrome_proxy_service.dart:222:34)
<asynchronous suspension>
```
```
[33m[!][39m Flutter (Channel master, 3.8.0-16.0.pre.35, on macOS 13.3.1 22E261
    darwin-arm64, locale en-AU)
    [32m•[39m Flutter version 3.8.0-16.0.pre.35 on channel master at
      /Users/baba/Dev/flutter
    [33m![39m Warning: `dart` on your path resolves to
      /opt/homebrew/Cellar/dart-sdk/2.19.4/libexec/bin/dart, which is not inside
      your current Flutter SDK checkout at /Users/baba/Dev/flutter. Consider
      adding /Users/baba/Dev/flutter/bin to the front of your path.
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 4811269379 (3 months ago), 2023-02-24 01:47:48 -0500
    [32m•[39m Engine revision 167c97bc3b
    [32m•[39m Dart version 3.0.0 (build 3.0.0-266.0.dev)
    [32m•[39m DevTools version 2.22.1
    [32m•[39m If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    [32m•[39m Android SDK at /Users/baba/Library/Android/sdk
    [32m•[39m Platform android-33, build-tools 33.0.0
    [32m•[39m Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 14.3)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 14E222b
    [32m•[39m CocoaPods version 1.12.1

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2022.1)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)

[32m[✓][39m VS Code (version 1.78.2)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.64.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m iPhone 14 Pro Max (mobile) • 37F48206-A7CD-4AC5-B258-7A374D92A852 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    [32m•[39m macOS (desktop)            • macos                                •
      darwin-arm64   • macOS 13.3.1 22E261 darwin-arm64
    [32m•[39m Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 113.0.5672.126

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+3
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: 4811269379c253b3be833636ad3af2f24d6d8a6b
### Plugins
camera-0.10.5+2
camera_android-0.10.8+2
camera_avfoundation-0.9.13+2
camera_web-0.3.1+4
cloud_firestore-4.7.1
cloud_firestore_web-3.5.1
cloud_functions-4.3.1
cloud_functions_web-4.5.1
firebase_auth-4.6.1
firebase_auth_web-5.5.1
firebase_core-2.13.0
firebase_core_web-2.5.0
firebase_messaging-14.6.1
firebase_messaging_web-3.5.1
firebase_storage-11.2.1
firebase_storage_web-3.6.1
flutter_plugin_android_lifecycle-2.0.15
google_sign_in-6.1.2
google_sign_in_android-6.1.14
google_sign_in_ios-5.6.2
google_sign_in_web-0.12.0+1
image_cropper-3.0.3
image_cropper_for_web-1.0.3
image_picker-0.8.7+5
image_picker_android-0.8.6+16
image_picker_for_web-2.1.12
image_picker_ios-0.8.7+4
libphonenumber_plugin-0.3.1
libphonenumber_web-0.3.0
path_provider-2.0.15
path_provider_android-2.0.27
path_provider_foundation-2.2.3
path_provider_linux-2.1.11
path_provider_windows-2.1.6
shared_preferences-2.1.1
shared_preferences_android-2.1.4
shared_preferences_foundation-2.2.2
shared_preferences_linux-2.2.0
shared_preferences_web-2.1.0
shared_preferences_windows-2.2.0
url_launcher-6.1.11
url_launcher_android-6.0.34
url_launcher_ios-6.1.4
url_launcher_linux-3.0.5
url_launcher_macos-3.0.5
url_launcher_web-2.0.17
url_launcher_windows-3.0.6
video_player-2.6.1
video_player_android-2.4.8
video_player_avfoundation-2.4.6
video_player_web-2.0.16
video_player_web_hls-1.0.0+3

**Comment by danagbemava-nc** [comment]
Hi @bstardust, this was initially reported in https://github.com/flutter/flutter/issues/121641 and has since been fixed on the latest versions of the master channel. 

Kindly upgrade to the latest version of master. 

Closing as this has already been fixed. 

Thank you
