### ISSUE TITLE
[CP] Stable-Support minification for apps using AGP 8.0 

### ISSUE THREAD

**Issue by reidbaker** [flutter/flutter#127964]
### issue_link

https://github.com/flutter/flutter/pull/127628

### Commit Hash

9376a2a 

### Target

stable

### pr_link

https://github.com/flutter/flutter/pull/127963

### Changelog Description

Export proguard rules for integration_test so that it can be used in project that depend on AGP 8.0 

### Impacted Users

Flutter android devs using AGP 8.0 and integration_test package

### Impact Description

Cannot compile integration tests. 

### Workaround

Do not use AGP 8.0 or disable integration tests. 

### Risk

medium

### Test Coverage

yes

### Validation Steps

Easy repro steps in the linked bug but there is an integration test in framework to ensure the fix works. 
That said there could be side effects to the proguard rules since they apply to the whole app build. The risks there are minimal because integration_test package is used for testing not production.

**Comment by reidbaker** [comment]
Do I need to file a separate pr and seperate bug to also get this change into beta?

**Comment by itsjustkevin** [comment]
Thanks for the question @reidbaker, yes, please file another cherry-pick to the beta channel.

**Comment by CaseyHillers** [comment]
@reidbaker is OOO, and there's been no action here. Closing this out due to inactivity, but anyone is welcome to reopen it resolving the CP conflicts.

**Comment by camsim99** [comment]
@gmackall @christopherfujino @stuartmorgan Going to try to push this through. Can someone review https://github.com/flutter/flutter/pull/127963?
