### ISSUE TITLE
Deprecate `ButtonBar`

### ISSUE THREAD

**Issue by larssn** [flutter/flutter#127955]
As can be seen in https://github.com/flutter/flutter/issues/79171, the `ButtonBar` doesn't support the new button types, and it was promised that it would soon be deprecated. That was in April 2021.

It still hasn't been deprecated, and it still doesn't support the new button types.

It is slightly confusing to work with a class that doesn't support an aspect of Flutter, with no indication that it doesn't do so.

I'm not sure if it's gonna stay or not, but I thought I'd highlight the issue.

**Comment by HansMuller** [comment]
Thanks for the reminder! You are correct, ButtonBar and ButtonBarTheme should be (should have been) deprecated. ButtonBar use cases can be handled by OverflowBar, see for example https://github.com/flutter/flutter/pull/85358.
