### ISSUE TITLE
[google_maps_flutter] Map renders already removed markers

### ISSUE THREAD

**Issue by dovahkiin98** [flutter/flutter#128042]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1- Add marker with a certain ID
2- Update the marker, either by updating the entire object or only updating the location
3- Sometimes there will be 2 markers on the map

### Expected results

The old marker should be removed

### Actual results

2 Markers when there is only 1 defined

### Code sample

<details><summary>Code sample</summary>
This is how I'm adding the marker

```dart
markers: {
              if (controller.markerPosition != null)
                Marker(
                  markerId: const MarkerId('pin'),
                  draggable: false,
                  consumeTapEvents: true,
                  onTap: () {
                    controller.onMarkerTap();
                  },
                  // consumeTapEvents: false,
                  position: controller.markerPosition!,
                ),
}
```

And what I'm doing is changing the `markerPosition`
</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.10.2, on Microsoft Windows [Version 10.0.22624.1755], locale en-GB)
    • Flutter version 3.10.2 on channel stable at J:\Programming\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (8 days ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at J:\Programming\Android\Android_SDK
    • Platform android-UpsideDownCake, build-tools 33.0.1
    • ANDROID_HOME = J:\Programming\Android\Android_SDK
    • ANDROID_SDK_ROOT = J:\Programming\Android\Android_SDK
    • Java binary at: J:\Programming\Android\Android_Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.4)
    • Visual Studio at J:\VisualStudio\Community
    • Visual Studio Community 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.1)
    • Android Studio at J:\Programming\Android\Android_Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[!] Android Studio (version 2023.1)
    • Android Studio at J:\Programming\Android\Android_Studio_Canary
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[√] IntelliJ IDEA Community Edition (version 2023.2)
    • IntelliJ at J:\IntelliJ IDEA
    • Flutter plugin version 73.1.1
    • Dart plugin version 232.5150.113

[√] VS Code (version 1.78.2)
    • VS Code at C:\Users\ahmad\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.52.0

[√] Connected device (4 available)
    • SM G973F (mobile) • RF8M41ABZFZ • android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.22624.1755]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 113.0.5672.127
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 113.0.1774.57

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by huycozy** [comment]
Hi @dovahkiin98 
Which `google_maps_flutter` plugin version are you using? 

> Update the marker, either by updating the entire object or only updating the location

Can you be more specific about this step? How to do it? Please provide a minimal & complete sample code that doesn’t include 3rd party plugins or complex production code so that we may verify this.

**Comment by TraceDeTrail** [comment]
Hello, 
I have a similar problem... (Test 1)

I try to move a marker along a polyline on a Google map in Flutter (mobile). Marker moving is linked to a GestureDetector widget. I used Flutter 3.10.2 and Google Maps for Flutter 2.2.8

Test 1 : I tried to move an unique marker but the marker doesn't follow the polyline and bypasses it to reach the target point and the marker at the first position is always displayed

https://youtube.com/shorts/JaWEmARjSmc

Test 2 : I create a marker at each new location but some markers are not deleted and I can't find the reason why... (the markers set no longer contains any elements!)

https://youtube.com/shorts/nFbppmS6vtw

`
 Map<MarkerId, Marker> markers = <MarkerId, Marker>{};
  Map<PolylineId, Polyline> polylines = <PolylineId, Polyline>{};
  TrackResult? track = null;
  late GoogleMap map;
  late GoogleMapController gMapController;
  MarkerId id = MarkerId("position");

 @override
  Widget build(BuildContext context) {
    map = GoogleMap(
      onMapCreated: (GoogleMapController controller) {
        gMapController = controller;
      },
      compassEnabled: false,
      rotateGesturesEnabled: false,
      scrollGesturesEnabled: true,
      zoomGesturesEnabled: true,
      tiltGesturesEnabled: true,
      myLocationEnabled: false,
      myLocationButtonEnabled: false,
      zoomControlsEnabled: false,
      markers: Set<Marker>.of(markers.values),
      polylines: Set<Polyline>.of(polylines.values),
      initialCameraPosition: CameraPosition(
        target: LatLng(46.377254, 2.592773),
        zoom: 5.0,
      ),
    );
    return Scaffold(
        appBar: AppBar(
          backgroundColor: Colors.blue,
          title: Text("Move marker along polyline"),
        ),
        body: Stack(
            fit: StackFit.expand,
            alignment: AlignmentDirectional.bottomStart,
            children: [
              map,
              if (track != null)
                AnimatedSize(
                    duration: Duration(milliseconds: 100),
                    child: GestureDetector(
                        child: Stack(
                            alignment: AlignmentDirectional.bottomStart,
                            children: [
                              Container(
                                color: Colors.white.withAlpha(150),
                                width: MediaQuery.of(context).size.width,
                                height: 70,
                              )
                            ]),
                        onPanUpdate: (details) {
                          double dist = details.globalPosition.dx *
                              track!.distance /
                              MediaQuery.of(context).size.width;
                          AltiPoint pt = track!.getPointDist(dist);
                          LatLng coords =
                              Utils.getCoordinatesFromXY(pt.x, pt.y);

                          setState(() {

                            //TEST1 Move existing marker

                            // if (!markers.containsKey(id))
                            //   markers[id] = Marker(
                            //       markerId: id, zIndex: 3, position: coords);
                            // else
                            //   markers[id] =
                            //       markers[id]!.copyWith(positionParam: coords);
                            //TEST2 Use new marker
                            markers.removeWhere(
                                (key, value) => key.value.contains("position"));
                            MarkerId id2 =
                                MarkerId("position${coords.toString()}");
                            markers[id2] = Marker(
                                markerId: id2, zIndex: 3, position: coords);
                          });
                        },
                        onPanEnd: (details) {
                          setState(() {
                            //TEST1
                            // if (markers.containsKey(id)) {
                            //   markers.remove(id);
                            // }
                            //TEST2
                            markers.removeWhere(
                                (key, value) => key.value.contains("position"));
                          });
                        }))
            ]));
  }
`

**Comment by Sillco** [comment]
I've encountered this issue where multiple markers are appearing on the map after updating a marker in Flutter. This issue can be reproduced using the following steps:

- Add a marker with a specific ID.
- Update the marker by either updating the entire marker object or only changing the location.

After updating, occasionally, two markers are displayed on the map instead of one.

Expected Behavior:

- After updating the marker, only one marker should be visible on the map.


Actual Behavior:

- Multiple markers are displayed on the map, causing confusion and clutter.


Additional Details:

Flutter version: [Insert your Flutter version here]
Device/Emulator:  huawei mate 9 android 9 / simulator iphone 14 pro ios 16
Operating System: macOS 
This issue disrupts the user experience and needs to be addressed. I believe it may be a bug in the Flutter framework related to marker updates. I'm happy to provide any additional information or assist with testing if needed.

Thank you for your attention to this matter.

**Comment by Sillco** [comment]
@huycozy in my case i am using the latest version of google maps and flutter.

**Comment by huycozy** [comment]
@Sillco Can you please share a minimal sample code for this case?

**Comment by TraceDeTrail** [comment]
@huycozy 
Here is a sample code that reproduces the problem (tested on iOS):

`import 'dart:async';
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatefulWidget {
  const MainApp({super.key});

  @override
  State<MainApp> createState() => _MainAppState();
}

class _MainAppState extends State<MainApp> {
  LatLng currentPos = const LatLng(46, 2);
  late MarkerId id;
  Map<MarkerId, Marker> markers = <MarkerId, Marker>{};

  @override
  Widget build(BuildContext context) {
    id = MarkerId("position${currentPos.toString()}");
    markers[id] = Marker(markerId: id, zIndex: 3, position: currentPos);

    Timer.periodic(const Duration(milliseconds: 2000), (Timer t) {
      currentPos = LatLng(markers[id]!.position.latitude + 0.025,
          markers[id]!.position.longitude + 0.025);
      id = MarkerId("position${currentPos.toString()}");
      setState(() {
        markers.removeWhere((key, value) => key.value.contains("position"));
        markers[id] = Marker(markerId: id, position: currentPos);
      });
    });

    return MaterialApp(
        home: Scaffold(
      appBar: AppBar(title: const Text('GoogleMaps démo')),
      body: Center(
        child: GoogleMap(
          compassEnabled: false,
          rotateGesturesEnabled: false,
          myLocationEnabled: false,
          myLocationButtonEnabled: false,
          zoomControlsEnabled: false,
          markers: Set<Marker>.of(markers.values),
          initialCameraPosition: const CameraPosition(
            target: LatLng(55, 8),
            zoom: 5.0,
          ),
        ),
      ),
    ));
  }
}`

https://youtube.com/shorts/6Mceonv_ruE

**Comment by huycozy** [comment]
Thank @TraceDeTrail for providing a reproduction sample. I can see this issue on Android and iOS whilst it works as expected on Web.

| Android | iOS | Web |
| --------------- | --------------- |  --------------- | 
❌ | ❌ | ✅ | 

✅: No Issue ❌: Issue reproduced

<details>
<summary>Demo</summary>

| Android | Web |
| --------------- | --------------- |
<video src="https://github.com/flutter/flutter/assets/104349824/defc1703-c4fd-4135-aceb-190a72ee97d8"/> | <video src="https://github.com/flutter/flutter/assets/104349824/792976fa-64ae-45bd-a10a-34eacad12952"/>

</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.10.4, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.10.4 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 682aa387cf (2 days ago), 2023-06-05 18:04:56 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 964AY0WL20 • android-arm64  • Android 12 (API 32)
    • macOS (desktop)   • macos      • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 114.0.5735.106

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.12.0-2.0.pre.20, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.12.0-2.0.pre.20 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1bd1b5014c (2 hours ago), 2023-06-07 18:16:30 -0700
    • Engine revision a5f7d5d75f
    • Dart version 3.1.0 (build 3.1.0-171.0.dev)
    • DevTools version 2.24.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 964AY0WL20 • android-arm64  • Android 12 (API 32)
    • macOS (desktop)   • macos      • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 114.0.5735.106

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by huycozy** [comment]
Adding `regression` label since there is a similar issue reported at https://github.com/flutter/flutter/issues/128420. It's mentioned that an old version (`google_maps_flutter: 2.2.6`) is working. I checked this again and confirm it works as expected on that version.

- google_maps_flutter: 2.3.0 ❌
- google_maps_flutter: 2.2.6 ✅

✅: No Issue ❌: Issue reproduced

**Comment by stuartmorgan** [comment]
The most notable change in that range is the `unawaited_futures` change (2.2.8), which introduce some `await`s in maps. I may have regressed this; looking at the change again, some of the things I intended to be no-ops would actually introduce delays in updating ivars, which may be the cause.

**Comment by stuartmorgan** [comment]
That was indeed the cause of the regression; the fix is out for review.

**Comment by Sillco** [comment]
Thank you, @stuartmorgan . we will be waiting for it.
