### ISSUE TITLE
[Flutter-markdown] Please support render video

### ISSUE THREAD

**Issue by thientrong98** [flutter/flutter#128014]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Please support render video

### Proposal

Please support render video

**Comment by dam-ease** [comment]
Hi @thientrong98. Thanks for filing this. It's not possible to embed a video in Markdown but it can be faked. Also, per this comment https://github.com/flutter/flutter/issues/81783#issuecomment-934753675, this proposal seems to not be feasible.
