### ISSUE TITLE
PointerInterceptor does not work with DropdownButton

### ISSUE THREAD

**Issue by ajayld** [flutter/flutter#128057]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Show a sample HTML page in a webview and add a DropdownButton widget just above the webview. 
2. Make the DropdownButton widget as the child of the PointerInterceptor widget.
3. Open the dropdown menu by clicking the down arrow on the DropdownButton widget.
4. Try clicking on the menu item that overlaps the webview.

### Expected results

 The dropdown menu item should be clickable.

### Actual results

The clicks register only with the webview and the dropdown menu item is not clickable.

### Code sample

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String dropdownValue = "United Kingdom";
  List<String> listOfValues = ["United Kingdom", "Canada", "Russia"];
  String htmlContent = """<!DOCTYPE html>
    <html>
      <meta charset='UTF-8'>
      <meta name='viewport' content='width=device-width, initial-scale=1.0'>
      <head>Sample Heading</head>
    <body>
        <p>Sample Body</p>
    </body>
    </html>""";

  @override
  Widget build(BuildContext context) {
    WebViewXController? webViewController;

    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          Padding(
            padding: const EdgeInsets.all(8.0),
            child: DecoratedBox(
              decoration: BoxDecoration(
                border: Border.all(
                    color: Colors.black, width: 1), //border of dropdown button
                borderRadius:
                    BorderRadius.circular(5), //border radius of dropdown button
              ),
              child: PointerInterceptor(
                child: DropdownButton<String>(
                  value: dropdownValue,
                  selectedItemBuilder: (BuildContext context) {
                    return listOfValues
                        .map<Widget>((String e) => Align(
                              alignment: Alignment.centerLeft,
                              child: Padding(
                                  padding: const EdgeInsets.all(8.0),
                                  child: Text(dropdownValue)),
                            ))
                        .toList();
                  },
                  items: const [
                    //add items in the dropdown
                    DropdownMenuItem(
                      value: "United Kingdom",
                      child: Text("United Kingdom"),
                    ),
                    DropdownMenuItem(value: "Canada", child: Text("Canada")),
                    DropdownMenuItem(
                      value: "Russia",
                      child: Text("Russia"),
                    )
                  ],
                  onChanged: (String? value) {
                    setState(() {
                      if (null != value) {
                        dropdownValue = value;
                      }
                    });
                  },
                  icon: const Padding(
                      //Icon at tail, arrow bottom is default icon
                      padding: EdgeInsets.all(8.0),
                      child: Icon(Icons.keyboard_arrow_down)),
                  underline: Container(), //remove underline
                  isExpanded: true, //make true to make width 100%
                ),
              ),
            ),
          ),
          SizedBox(
            height: 400,
            child: WebViewX(
              width: 1920,
              height: 400,
              onWebViewCreated: (webViewControllerParam) {
                  webViewController = webViewControllerParam;
                  webViewController?.loadContent(
                      htmlContent, SourceType.html);
              },
            ),
          )
        ],
      ),
    );
  }
}

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

https://github.com/flutter/flutter/assets/12118129/2e11b64c-6369-4424-b919-4c736049b516

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.2, on macOS 12.6.3 21G419 darwin-x64, locale en-IN)
    • Flutter version 3.10.2 on channel stable at /Users/apple/Desktop/Workspace/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (9 days ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = Users/apple/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)         • macos         • darwin-x64     • macOS 12.6.3 21G419 darwin-x64
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 114.0.5735.90

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment]
Hi @ajayld 
As I can see from your sample code, it is using 3rd package and still has error on type casting. Please provide a minimal and workable sample code that doesn’t include 3rd party plugins/packages so that we may verify this. Thank you!
