### ISSUE TITLE
cloud_firestore: implement DocumentReference delete() functionality

### ISSUE THREAD

**Issue by bjornbjorn** [flutter/flutter#12802]
Using the ```cloud_firestore``` package I expect to be able to [delete a document](https://cloud.google.com/firestore/docs/manage-data/delete-data), maybe something like this:

```
Firestore.instance.document('books/${bookDocumentId}').delete();
```

Looks like delete() or deleteDocument() has not been implemented yet?

**Comment by felixaram** [comment]
Any update on this?
