### ISSUE TITLE
Abstract interface class shows a confusing error when extending it from a different file

### ISSUE THREAD

**Issue by bkkoluch** [flutter/flutter#128027]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create an `abstract interface class X`
2. Extend it from a different file

### Expected results

I believe the more appropriate message would be `The class 'X' can't be extended outside of its file because it's an interface class.`, in my opinion `library` in this case is very confusing, unless that's a deliberate wording. The same case occurs for `sealed class` (and probably other ones). I know `interface class` are meant to be implemented, but they can still be extended in the same file.

### Actual results

Geting an error saying `The class 'X' can't be extended outside of its library because it's an interface class.`

### Code sample

<details><summary>Code sample</summary>

```dart
use_case.dart

abstract interface class UseCase<Type, Params> {
  Type call(Params params);
}

class TestUseCase extends UseCase<String, String> {
  @override
  String call(String params) => 'Test';
}

test.dart

class TestUseCase2 implements UseCase<String, String> {
  @override
  String call(String params) => 'Test';
}

class TestUseCase3 extends UseCase<String, String> {
  @override
  String call(String params) => 'Test';
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.0, on macOS 12.6 21G115 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.3)
[✓] VS Code (version 1.72.0)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by danagbemava-nc** [comment]
Hi @bkkoluch, this is a language issue not an issue with the flutter framework. Kindly file an issue on the dart language or sdk repo so that it can be handled appropriately. 

Closing as this is out of scope for this repo. 

Thank you

**Comment by bkkoluch** [comment]
> Hi @bkkoluch, this is a language issue not an issue with the flutter framework. Kindly file an issue on the dart language or sdk repo so that it can be handled appropriately.
> 
> Closing as this is out of scope for this repo.
> 
> Thank you

Thank you for the reply, sorry for the confusion here 👍.
