### ISSUE TITLE
Create a canonical demo showcasing differing IA between Material and Cupertino

### ISSUE THREAD

**Issue by xster** [flutter/flutter#12805]
Create a demo with custom themed visuals that has different root level navigation structures on Android and iOS to 

1- Demonstrate that it's possible and easy to share screens with minimal code addition and
2- Use as a canonical example for platform switching code

**Comment by Hixie** [comment]
@xster Can you elaborate on what you mean by IA?

**Comment by xster** [comment]
I meant with some chrome level structural differences like drawers and app bar action buttons with overflows on one hand and tab bars and tabs and actions on inside the content slivers on iOS etc.

**Comment by xster** [comment]
This is still slated for Q1
