### ISSUE TITLE
 flutter web ui.platformViewRegistry.registerViewFactory fails to load for the second time under ios13.0 system；Above 14.0 is correct；

### ISSUE THREAD

**Issue by iamzhibo** [flutter/flutter#128015]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1、Load web pages using ui.platformViewRegistry.registerViewFactory
2、first success
3、Failed to open the second time

### Expected results

content can be loaded

### Actual results

Failed to open the second time

### Code sample

  String _localVideoPlayerId = 'Iframe${DateTime.now().millisecondsSinceEpoch}';
  @override
  Widget build(BuildContext context) {
    ui.platformViewRegistry.registerViewFactory(
        _localVideoPlayerId,
        (int viewId) => IFrameElement()
          ..allowFullscreen = true
          ..height = '360'
          ..src = 'https://www.baidu.com'
          ..style.border = 'none');
    return Scaffold(
        appBar: AppBar(
          title: const Text('WebViewX Page'),
        ),
        body: Center(
          child: Container(
            color: Colors.red,
            // padding: const EdgeInsets.only(left: 16, right: 16),
            height: 500,
            child: HtmlElementView(viewType: _localVideoPlayerId),
          ),
        ));
  }

### Screenshots or Video

It loads the first time, fails the second time

### Flutter Doctor output

 Flutter (Channel stable, 3.7.12, on Mac OS X 10.15.7 19H2 darwin-x64, locale zh-Hans-US)
    • Flutter version 3.7.12 on channel stable at /Users/ares/zb/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (6 周前), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

**Comment by huycozy** [comment]
I checked this issue on iPhone 11 Pro, iOS 13.7 but it works normally even reloading more than twice.
<details>
<summary>Demo</summary>

![Screenshot 2023-06-01 at 18 22 38](https://github.com/flutter/flutter/assets/104349824/2deb85e4-ae52-4296-b6a1-01bed4b9e4b2)
</details>

Can you be more specific on actual result? How does it look like?

**Comment by iamzhibo** [comment]
System below 13 is wrong，your system is high

**Comment by huycozy** [comment]
Can you share the specific affected version?  How does the issue look like? (Please provide a recorded video with description in detail so that the issue is more clear). Thanks!

**Comment by iamzhibo** [comment]
https://github.com/flutter/flutter/assets/118972991/63997fad-4ad2-4f6c-940a-6153f5dbcfc9

**Comment by iamzhibo** [comment]
https://github.com/flutter/flutter/assets/118972991/515bd85a-2c8d-451e-a443-1f26d1af012b

**Comment by iamzhibo** [comment]
Two versions are provided, please help to see, thank you

**Comment by iamzhibo** [comment]
https://github.com/flutter/flutter/assets/118972991/632ffd92-05fa-4083-9dc6-5e68a8e2c8ee

**Comment by huycozy** [comment]
Unfortunately, I don't have such OS version. My minimum iOS version is 13.7. Can you try checking if there is any special log from Safari?

If you are not familier with this, you can go with below steps:
1. Connect your iPhone to Mac device
2. Open web on iPhone
3. Open Safari browser on Mac device > Develop menu > iPhone > Select corresponding tab on iPhone (the web has issue)
4. Check logs from Console tab on new opened window

Also, can you try on the latest master Flutter channel?

**Comment by iamzhibo** [comment]
The latest version of flutter has been tested.the same problem
1、Safari logs no errors.

**Comment by iamzhibo** [comment]
Safari logs no errors

**Comment by iamzhibo** [comment]
Safari logs no errors.
If the h5 player is embedded, the player has sound, but the node cannot be seen

The latest version of flutterr has the same problem, already tried

**Comment by iamzhibo** [comment]
Can you help me with this problem.thank you very much

**Comment by darshankawar** [comment]
I was able to replicate the reported behavior on iOS Simulator 12.4 (iphone 6 plus). Running the provided code sample on simulator's browser (safari), it shows below screen upon second try:

<img width="362" alt="Screenshot 2023-06-06 at 11 34 11 AM" src="https://github.com/flutter/flutter/assets/67046386/fc224d34-8f11-49d5-aaf0-f5c52a0215ef">

While, on, iOS 13+, it works as expected and also verified [here.](https://github.com/flutter/flutter/issues/128015#issuecomment-1571868913)

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.10.3, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.10.3 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f92f44110e (4 days ago), 2023-06-01 18:17:33 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.11.0-20.0.pre.15, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.11.0-20.0.pre.15 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6c8cf3a9d0 (54 minutes ago), 2023-06-05 23:52:07 -0400
    • Engine revision aaa7574375
    • Dart version 3.1.0 (build 3.1.0-163.0.dev)
    • DevTools version 2.24.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by iamzhibo** [comment]
Are you going to fix this?

**Comment by yjbanov** [comment]
One thing I noticed is that you are registering the factory in the `build` method. A factory should only be registered once during the lifetime of the app, but `build` methods are called many times.

**Comment by iamzhibo** [comment]
_localVideoPlayerId unique and same case.

**Comment by ditman** [comment]
I'm afraid I can't test this anymore, I don't have any device in iOS13 (not even the simulators let me go below 15), I'm going to un-assign myself from here and let it bounce back to triage.

**Comment by yjbanov** [comment]
iOS 12 is outside our support matrix, and this issue seems like a Safari bug, so would likely require hacks to fix. If you need to support iOS 12, consider using older Flutter SDK that supports it.
