### ISSUE TITLE
Mocking final (and base?) classes in tests

### ISSUE THREAD

**Issue by Albert221** [flutter/flutter#128047]
Now that we have Dart 3's class modifiers we (and 3rd parties) can make our classes `final` or `base`.

But final or base classes cannot be mocked. We cannot create mocks in `mockito` or `mocktail` way nor just extend them and provide our custom stubs. This is a big obstacle in writing tests like these:

```dart
// This class could be 3rd party or from the same package (but other library than test file).
final class SomeDependency {
  final value = false;
}

class MyClass {
  MyClass(this.dep);

  final SomeDependency dep;

  bool getValue() {
    return dep.value;
  }
}

class _MockSomeDependency extends Mock implements SomeDependency {}

void main() {
  test('MyClass.getValue returns the correct value', () {
    final dep = SomeDependency();
    when(() => dep.value).thenReturn(true);
    final myClass = MyClass(dep);

    expect(myClass.getValue(), true);
  });
}

```

This is now impossible because:
> The class 'SomeDependency' can't be implemented outside of its library because it's a final class.

How can developers achieve this now? Would `dart:mirrors` reflection (which is disabled in Flutter and hence my issue is here, not in Dart repo) help?

**Comment by rrousselGit** [comment]
That's not really a Flutter issue.
The correct place is probably github.com/dart-lang/language.

There are some related issues there already, with decent discussions

**Comment by stuartmorgan** [comment]
See https://github.com/dart-lang/language/issues/3111 and related issues. Closing as this is not a Flutter-level issue.
