### ISSUE TITLE
[web] Move flutter.js file to the flutter/engine repo.

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#128061]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

flutter.js is mostly interfacing with code written in the flutter/engine repo. Any changes to the way flutter.js bootstraps Flutter web need changes that are hard to implement because they need to be landed *in lockstep*.

### Proposal

Changes would be much easier to land if flutter.js was vended by the engine and consumed by the flutter_tool.

Move this:
* https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/web/file_generators/js/flutter.js

Somewhere here:
* https://github.com/flutter/engine

Then modify the engine builds so they vend `flutter.js` in a location that can then be loaded from the `flutter_tools` package.

**Comment by yjbanov** [comment]
I think we should make it a layered system:

* `dart.js` is provided by the Dart SDK at the lowest level and provides API for bootstrapping Dart code (e.g. dart2wasm modules).
* `engine.js` is provided by the engine and provides engine bootstrapping API, managing custom elements, lifecycle, etc.
* `flutter.js` adds the framework/tool-level cause on top.

**Comment by yjbanov** [comment]
Also, each higher-level module would import the lower-level one, e.g. `flutter.js` would import `engine.js`, and `engine.js` would import `dart.js`.

**Comment by yjbanov** [comment]
However, it's possible that the _current_ code that lives inside `flutter.js` belongs in the engine, so we could split that engine-specific code out and move it into `engine.js`. I'd still keep `flutter.js` for the framework-side shenanigans, such as service worker.

**Comment by ditman** [comment]
Yes, I think that currently *most* of flutter.js should be "engine.js" (or maybe dart.js) and then leave flutter.js just be the "glue" that ties everything together.

If we go this route of having a "layered" approach, would it make sense that programmers can build their own "flutter-bootstrap.js" out of the different bits offered by flutter.js?

**Comment by yjbanov** [comment]
I like the philosophy of enabling developers rather than doing everything for them. We won't have the same creativity and scale to tailor for every use-case. So each layer should be an API that upper layers can build more specific solutions with. Similarly, developers should be able to plug into any of the layers appropriate to their use-case.

So yeah, developers should be able to import `engine.js` directly and build their own solution. For example, if they don't like how the out-of-the-box service worker works, or the API for managing a Flutter app on the page, they should be able to replace it.

**Comment by kevmoo** [comment]
For complexity and request count, it'd be nice if there weren't a LOT more JS files to manage.

We could glue JS together at build-time, right?

**Comment by ditman** [comment]
> For complexity and request count, it'd be nice if there weren't a LOT more JS files to manage.
>
> We could glue JS together at build-time, right?

Yes, we can still vend a "flutter.js" file (named like that for backwards compatibility) that we bundle *somehow* with our own tooling,  but also make sure the independent bricks are available via imports so users can build their own version. (We don't care how/if users glue their own version)

**Comment by jacobsimionato** [comment]
+1 to the gluing option - that way we can get the modularity we want without sacrificing the hard-won initial load time improvements we've had recently by adding extra round trips to the bootstrap process. It'd be great if for a vanilla Flutter Web app generated with `flutter create`, all the bootstrap scripts mentioned above were inlined directly into index.html as proposed in https://github.com/flutter/flutter/issues/118115. Then at least the default option is fast, and advanced users can make their own trade offs as necessary.

Seeing as Flutter.js is already exposed via a generator function, could you just have that function return a concatenated output with dart.js, engine.js, flutter.js etc in the appropriate order or something?

**Comment by ditman** [comment]
> Seeing as Flutter.js is already exposed via a generator function, could you just have that function return a concatenated output with dart.js, engine.js, flutter.js etc in the appropriate order or something?

Yes, `flutter.js` should be the name of the script that (hopefully) behaves the same as what we have now, except we generate it differently.

**Comment by ditman** [comment]
@eyebrowsoffire already did this, and is starting to play to build flutter.js from sources with esbuild. See: https://github.com/flutter/engine/commit/43db22e9b68c3e8ed5150c3b272c1d2717162e0d
