### ISSUE TITLE
Flutter gives enable by default notification for ios and its quite

### ISSUE THREAD

**Issue by newbieflutter** [flutter/flutter#128062]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I am creating a new app on latest flutter. What I noticed for ios suddenly the notification is enabled by default and its quite. In my earlier app this was not the case where I set the permission handler.

### Expected results

We expected that by default the notification is not enabled for ios.

### Actual results

The actual results now is that for ios notification is enabled and is set as quite. So is there any changes to the latest flutter sdk causing this ? Because recently I have updated the sdk.

### Code sample

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
       
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});


  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
     
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
   
    return Scaffold(
      appBar: AppBar(
   
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
       
        title: Text(widget.title),
      ),
      body: Center(
    
        child: Column(
        
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

[✓] Flutter (Channel master, 3.11.0-11.0.pre.3, on macOS 13.3.1 22E772610a darwin-arm64, locale en-MY)
    • Flutter version 3.11.0-11.0.pre.3 on channel master at /Users/ss/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ab573048e7 (12 days ago), 2023-05-20 11:32:26 -0400
    • Engine revision aac0919568
    • Dart version 3.1.0 (build 3.1.0-129.0.dev)
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/ss/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.2)
    • VS Code at /Users/ss/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.3.1 22E772610a darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.90

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by dam-ease** [comment]
Hi @newbieflutter. I'm unable to reproduce this. Tested with a new project on the latest `master` and `stable` channels and the default is currently "denied". Also, this doesn't seem like something the team would do. Kindly confirm again on your end.

**Comment by newbieflutter** [comment]
Hi,
    I can confirm by creating another new  simple app its enabled by default. I cant recall what version I was before this upgrade.

**Comment by dam-ease** [comment]
Hi @newbieflutter. Can you provide a step-by-step action to reproduce this issue including a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that prints out notification status?

**Comment by newbieflutter** [comment]
Hi Ease,
               As I have described above the simple example codes is what I exactly do. So nothing else I do which I why I am quite confused why the notification is enabled and quite on ios? There after I check the notification status in the apple phone it show it enabled and quite.

**Comment by darshankawar** [comment]
@newbieflutter 
Can you elaborate as what do you mean by notifications is enabled by default ? What result do you see ?
Also, can you try the same with native iOS app and see if you get same behavior or not ?

**Comment by newbieflutter** [comment]
Hi Darshan,
                    What I mean is that the notification permission is enabled by default so there is no room for the to ask the user permission for notification. I tried the native iOS app but I dont see it in the notification list either. So looks like only from the flutter side this issue is occuring.
