### ISSUE TITLE
Read `--flavor` from Flutter

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter#128046]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

`flavor` for tools can be useful to switch between different product variants and correspond to different platform resources and codes. However, the value of `flavor` can not be read from the Flutter (Dart) side directly. To do so in the current circumstance, we need to write duplicate definitions like `flutter run --flavor dev --dart-define=app-flavor=dev` to get it available to read at the Flutter side directly.

### Proposal

Inject the `flavor` variable into environments, or provide another ability to read from the Flutter code directly.

**Comment by maRci002** [comment]
I like this approach:

Specify your entry point `--target lib/main_mock.dart` and create own `AppConfig`

```dart
import 'package:flutter/material.dart';

void main() {
  const config = AppConfig(
    apiEndPoint: 'https://xxx.com',
    environment: Environment.mock,
    appDisplayName: '[MOCK] My App',
    child: App(),
  );

  runApp(config);
}

// Define somewhere
enum Environment { prod, dev, mock }

class AppConfig extends InheritedWidget {
  const AppConfig({
    super.key,
    required super.child,
    required this.environment,
    required this.appDisplayName,
    required this.apiEndPoint,
  });

  final Environment environment;
  final String appDisplayName;
  final String apiEndPoint;
  // final http.Client httpClient; <-- add mock client or default http client and you won't have to check flavor in runtime

  static AppConfig of(BuildContext context) {
    return context.dependOnInheritedWidgetOfExactType<AppConfig>()!;
  }

  @override
  bool updateShouldNotify(AppConfig oldWidget) {
    return environment != oldWidget.environment || appDisplayName != oldWidget.appDisplayName || apiEndPoint != oldWidget.apiEndPoint;
  }
}
```

**Comment by huycozy** [comment]
@AlexV525 It seems we can work around this by using a MethodChannel. Also, I see this has been responded at https://github.com/flutter/flutter/issues/31441#issuecomment-598309551, so I'm not sure if it's feasible now with current system.

**Comment by AlexV525** [comment]
> @AlexV525 It seems we can work around this by using a MethodChannel. Also, I see this has been responded at [#31441 (comment)](https://github.com/flutter/flutter/issues/31441#issuecomment-598309551), so I'm not sure if it's feasible now with current system.

https://github.com/flutter/flutter/issues/31441#issuecomment-598309551 seems valid at that time. But IIRC incremental builds and reusable builds with dart defines have been improved since then. Also, switching flavors and writing the flavor into the environment will not be unexpected because the value is relatively fixed since they'll need manual configuration steps which is not dynamic.

**Comment by maRci002** [comment]
In case of web you cannot provide `flavor` so it will never be universal solution.

**Comment by AlexV525** [comment]
This is great! Thanks @andrewkolos
