### ISSUE TITLE
[Impeller] Verify the integrity of the Vulkan pipeline cache.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#128126]
Today, there are [placeholders for pipeline cache validation](https://github.com/flutter/engine/blob/af8dab09866946a2e19f94197ecc92e8ee214f46/impeller/renderer/backend/vulkan/pipeline_cache_vk.cc#L18). These must be replaced with actual validation per the [guidance in this article](https://medium.com/@zeuxcg/creating-a-robust-pipeline-cache-with-vulkan-961d09416cda). We can use flatbuffers for the validation headers.

**Comment by jonahwilliams** [comment]
If we don't think we need to do this can we close the issue?

**Comment by chinmaygarde** [comment]
This was recommended as best practice. It may have been more relevant early on when Vulkan drivers were not as stable. But I think we should still do this for safety.
