### ISSUE TITLE
[CP] Add `namespace` to module build file templates

### ISSUE THREAD

**Issue by camsim99** [flutter/flutter#128136]
### issue_link

https://github.com/flutter/flutter/issues/126403

### Commit Hash

31a665c

### Target

stable

### pr_link

~https://github.com/flutter/flutter/pull/126963~
https://github.com/flutter/flutter/pull/128360

### Changelog Description

Adds [`namespace` configuration](https://developer.android.com/build/configure-app-module#set-namespace) to module `build.gradle` file templates that is required when using >= Gradle 8.0.

### Impacted Users

Flutter devs using add-to-app on Android wanting to use Gradle 8.0+

### Impact Description

Flutter developers generating Flutter modules to use for android-add-to-app with an Android app using Gradle 8.0+ will receive a vague error describing an issue with `namespace` in its `build.gradle` configuration files as described in https://github.com/flutter/flutter/issues/126403#issue-1703425186.

### Workaround

A developer may work around the issue by adding the `namespace` configuration manually to the module's `build.gradle` configuration files.

### Risk

low

### Test Coverage

yes

### Validation Steps

Once you checkout my fix, you need to find an existing Android app or create one to use for testing. Modify it if necessary to use Gradle 8.0+. Then, create a Flutter module to add to an existing Android app using the command listed [here](https://docs.flutter.dev/add-to-app/android/project-setup#create-a-flutter-module). Finally, try running the app or building the apk and verify that it is successful.

**Comment by itsjustkevin** [comment]
@reidbaker for review.

**Comment by reidbaker** [comment]
> @reidbaker for review.

On vacation for 2 weeks you will need another reviewer

**Comment by itsjustkevin** [comment]
Handoff to @gmackall and @stuartmorgan for review.

**Comment by gmackall** [comment]
Is this missing a link to the cherry-pick pr? The pr_link points to to the pr to master

**Comment by CaseyHillers** [comment]
Yes, CP authors need to send the CP PR as well. Otherwise, we don't have the ability to assess the risk it has on the branch.

**Comment by camsim99** [comment]
@CaseyHillers @Jasguerrero I think this is ready for another look!
