### ISSUE TITLE
Screenshot during integration test sometimes contains "crosshair"

### ISSUE THREAD

**Issue by chris-rutkowski** [flutter/flutter#128100]
Minimal project in Git: https://github.com/chris-rutkowski/my_screenshot

### Steps to reproduce

Have an Integration (E2E) test:

1. Tap a button
2. pump and settle
3. Take a screenshot and compare it with a golden image

```
await tester.tap(Key('button');
await tester.pumpAndSettle();
final bytes = await binding.takeScreenshot('screenshot');
await expectLater(bytes, matchesGoldenFile('snapshot.png'));
```

**The result is flaky**, sometimes **crosshair** is caught on the screenshot, sometimes not - as in the example.

An attached example is from a different project, but with exactly the same steps - tap a button, pump and settle, and eventually take and compare the screenshot.

- Can we remove the crosshair from being displayed?
- Should the `pumpAndSettle` await till the crosshair is removed from the previous steps?

This issue can be mitigated by trivial `await Future.delayed(const Duration(seconds: 1))`, but this is mitigation, not a solution.

### Proof of an issue

![expired_tab-ios-en_testImage](https://github.com/flutter/flutter/assets/58718695/525e1662-d6a0-4564-883d-714767fd208d)

### Expected

![expired_tab-ios-en_masterImage](https://github.com/flutter/flutter/assets/58718695/e2f1c235-dffe-44df-a7f3-36f27fd65c69)

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.2, on macOS 13.0 22A380 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.78.2)
[✓] Connected device (4 available)
[✓] Network resources
```

</details>

**Comment by dam-ease** [comment]
HI @chris-rutkowski. I'm currently unable to reproduce this issue with the sample code provided both on Android and iOS. Can you provide further explanation or instances in which this issue occurs? Also, can you create a new flutter project to confirm this issue occurs?

**Comment by chris-rutkowski** [comment]
@dam-ease 

Thank you for taking the time to look into this problem. Here's the relevant context:

- On our CI (GitHub Action, macos-13), we're seeing a high failure rate of around 75%. The screenshot comparison fails due to the presence of a crosshair which does not appear in our pre-recorded images.
- The issue seems elusive as it's not replicable on my local Mac setup, where screenshots consistently do not show the crosshair.
- I tried reproducing this problem in a sample repository, but couldn't. It's possible that the issue might be prevalent in a more resource-intensive application.

In essence, the undesired appearance of this crosshair is causing difficulties. If possible, I'd like to find a way to turn off its visibility during integration tests, as it currently isn't providing any meaningful value.

**Comment by dam-ease** [comment]
Hi @chris-rutkowski.
Few suggestions:

- Try adding `await binding.convertFlutterSurfaceToImage();` after first instance of `pumpAndSettle()`
```dart
app.main();
await tester.pumpAndSettle();
await binding.convertFlutterSurfaceToImage();
await tester.pumpAndSettle();
``` 

- Then run `flutter test integration_test --update-goldens` for the test framework to create the missing golden files, instead of comparing them and then go ahead to run the usual tests.

<details><summary>Code Sample</summary>
<p>

```dart
void main() {
  final binding = IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  group('end-to-end test', () {
    testWidgets('tap on the floating action button, verify counter', (tester) async {
      app.main();
      await tester.pumpAndSettle();
      await binding.convertFlutterSurfaceToImage();
      await tester.pumpAndSettle();
      expect(find.text('0'), findsOneWidget);
      final Finder fab = find.byTooltip('Increment');
      await tester.tap(fab);
      await tester.pumpAndSettle();
      // expect(find.text('1'), findsOneWidget);
      final bytes = await binding.takeScreenshot('screenshot');
      await expectLater(bytes, matchesGoldenFile('snapshots/value-1.png'));
    });
  });
}
``` 

</p>
</details>
