### ISSUE TITLE
[go_router] cant get parameter as bool and int with queryParameter 

### ISSUE THREAD

**Issue by vrman** [flutter/flutter#128153]
here is how  i pass parameter as queryParameter , it accept all types , <String, dynamic> :
```
routes.goNamed(
    'confirm',
    queryParameters: {
      'isLogin': true,
    },
  );
```

but here when i want to get that parameter i need to pars that to type because queryParameters is <String, String> and queryParametersAll is <String, List<String>> too .
```
GoRoute(
    name: 'confirm',
    path: 'confirm',
    builder: (context, state) {
      return AuthConfirmPage(
        isLogin: bool.parse(state.queryParameters['isLogin']!),
      );
    },
  ),

```

what is the correct way to solve this problem ?

**Comment by maRci002** [comment]
I think when you provide your own `queryParameters` it should be either `String` / `null` / `Iterable<String>` just like [`Uri`](https://api.flutter.dev/flutter/dart-core/Uri/Uri.html) does.

> When queryParameters is used, the query is built from the provided map. Each key and value in the map is percent-encoded and joined using equal and ampersand characters. A value in the map must be either null, a string, or an [Iterable](https://api.flutter.dev/flutter/dart-core/Iterable-class.html) of strings. An iterable corresponds to multiple values for the same key, and an empty iterable or null corresponds to no value for the key.

`Map<String, dynamic /*String?|Iterable<String>*/ >? queryParameters,`

**Comment by darshankawar** [comment]
@vrman 
Try above comment and see if it helps in your case or not.

**Comment by vrman** [comment]
no its not helping me , still get exception when i want to get bool or other types instead string from queryParameters

**Comment by maRci002** [comment]
> no its not helping me , still get exception when i want to get bool or other types instead string from queryParameters

So, are you saying that you want to preserve the `bool` type when you pass it to `queryParameters`? Let me ask you something: What should happen when a user uses the top navigation browser buttons, like pressing the forward and backward buttons? In that case, the `queryParameters`, which have already been serialized, are read from the browser as a string type.

**Comment by vrman** [comment]
> 

Yes your right , agree with you in that scenario , but this pattern is so pain when you need type safe routing.
thanks

**Comment by maRci002** [comment]
> Yes your right , agree with you in that scenario , but this pattern is so pain when you need type safe routing.

When you are using JSON you are doing the same.
https://docs.flutter.dev/data-and-backend/json#serializing-json-inside-model-classes

I suggest you writing your own custom constructor, then you can reuse it:

```dart
  factory AuthConfirmPage.fromQueryParameters(Map<String, String> queryParameters) {
    return AuthConfirmPage(
      isLogin: bool.parse(queryParameters['isLogin']),
    );
  }

  Map<String, String> toQueryParameters() {
    return {
      'isLogin': isLogin.toString(),
    };
  }
```
