### ISSUE TITLE
Remove unnecessary typed_data imports from flutter/packages

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#128140]
https://github.com/flutter/flutter/pull/104231 involved adding a bunch of temporary `ignore`s to flutter/packages, with a TODO to remove them once 3.1 reached stable; we still have 39 instances.

We need to search for that issue number in the repository to find all those TODOs, and remove the stale ignore directives.

**Comment by dimabran** [comment]
Is it only the `ignore` that needs to be deleted, or the import as well?

**Comment by stuartmorgan** [comment]
As both the issue title and the TODO comments says, the imports need to be removed. Removing just the `ignore` won't pass CI.

**Comment by dimabran** [comment]
Done, I keep getting these errors in the CI `Undefined name 'Uint8List'` in [type_conversion_test.dart](https://github.com/flutter/packages/blob/d8a6728a3a628bc91e6b884deaf31444c8cc7ae2/packages/camera/camera_android/test/type_conversion_test.dart) From what I understand the typed_data is in the dart foundation package now, which is not present, should i add it?
