### ISSUE TITLE
Can't open AVD manager

### ISSUE THREAD

**Issue by anchpop** [flutter/flutter#12815]
I'm using Android Studio on Windows 10. For some reason, I can't seem to open the AVD manager. The button appears disabled. I've tried starting Android Studio as administrator, I have virtualization enabled in my BIOS, I can't think of anything else!

I created a new flutter project with `flutter create projectname` and then created a project with the same name (in androidstudio) the parent directory of the flutter project. 

I really don't know what's going wrong, I don't even know what I should show for debugging purposes. I hope these will help!

![image](https://user-images.githubusercontent.com/3711047/32258518-3e590ac0-be91-11e7-95ef-172bfbf470d3.png)

![image](https://user-images.githubusercontent.com/3711047/32258660-2f6a479e-be92-11e7-8686-97b0150620a3.png)

![image](https://user-images.githubusercontent.com/3711047/32258668-3e83311e-be92-11e7-9c22-a95dbe56d2b2.png)

![image](https://user-images.githubusercontent.com/3711047/32258679-4a1322d2-be92-11e7-8544-dd38a68c3238.png)

![image](https://user-images.githubusercontent.com/3711047/32258914-a780255e-be93-11e7-975b-4049dad6dd3b.png)

p.s. Sorry if this isn't the right place to post this! I'm trying to figure out flutter and didn't know where else to ask

**Comment by mravn-google** [comment]
I believe we saw the same issue on a MacBook in the codelab at the Firebase Dev Summit last night.

**Comment by mit-mit** [comment]
cc @devoncarew @stevemessick is this a side-effect of https://github.com/flutter/flutter-intellij/issues/1458 ?

**Comment by mit-mit** [comment]
@anchpop so sorry to hear; you have reached the right place, and we will get this resolved! 

One question: Which version of the Flutter plugin do you have? (You can look this up by starting Android Studio, going to the Preferences menu item, and then selecting Plugins, and then Flutter.)

**Comment by stevemessick** [comment]
@mit-mit No, this is unrelated to flutter/flutter-intellij#1458.
Unfortunately, the project window does not show us which directory is the root of the project. I suspect that if the correct directory were opened as the root of the project that the AVD button would be enabled. (It worked for me.)

**Comment by anchpop** [comment]
@stevemessick which directory should be opened as the root of the project? Let's say I have `documents/flutterprojects/myproject`, where myproject was the directory created by running `flutter create myproject`. What should I make or open in Android studio?

**Comment by stevemessick** [comment]
myproject

**Comment by mit-mit** [comment]
@stevemessick I had this exact same issue with 18.3, and it's gone now with 18.4.

@anchpop can you try to update your Flutter plugin in Android Studio?

**Comment by stevemessick** [comment]
@mit-mit Here's the code that controls enablement of the AVD Manager button, from `org.jetbrains.android.actions.RunAndroidAvdManagerAction:`
```java
  public void update(@NotNull AnActionEvent e) {
    final Project project = e.getProject();
    e.getPresentation().setEnabled(
      project != null &&
      !ProjectFacetManager.getInstance(project).getFacets(AndroidFacet.ID).isEmpty() &&
      AndroidSdkUtils.isAndroidSdkAvailable());
  }
```
In English: There has to be a project open, it has to have an Android facet, and an Android SDK has to be available. It has nothing to do with the Flutter plugin. `flutter create` has included an Android facet since sometime last summer.

If you open the parent directory of your Flutter project in Android Studio you get a window that looks a lot like the screenshot in the OP. The Android view is selected and nothing shows in the list. If you open the Flutter project, the Project view is selected, and you can see the Android facet within.

I think you can close this issue.

**Comment by anchpop** [comment]
This was the solution! Thank you everyone
