### ISSUE TITLE
Floating SnackBar incompatible with certain FloatingActionButtonLocations

### ISSUE THREAD

**Issue by jdsareault** [flutter/flutter#128150]
### Is there an existing issue for this?

- [x] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create an app with a Scaffold and a FloatingActionButton
2. Set FloatingActionButtonLocation so that the button is at the top of the screen, such as FloatingActionButtonLocation.startTop.
3. Call a SnackBar with behavior of SnackBarBehavior.floating.

### Expected results

Display a SnackBar on a visible portion of the screen. Either at the bottom of the screen, or below the FloatingActionButton. 

### Actual results

SnackBar tries to float above the FloatingActionButton, causing it to display off-screen (or above the SafeArea, and partially off-screen). 

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: MyHomePage(title: 'Snackbar Position Issue'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  final String title;

  const MyHomePage({
    Key? key,
    required this.title,
  }) : super(key: key);

  void _showSnackBar(BuildContext context) {
    SnackBar mySnackBar = const SnackBar(
      content: Text('Snack Time'),
      behavior: SnackBarBehavior.floating,
      width: 300,
    );
    ScaffoldMessenger.of(context).showSnackBar(mySnackBar);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: const Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text('Press the Ice Cream to call SnackBar'),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          _showSnackBar(context);
        },
        tooltip: 'Call SnackBar',
        child: const Icon(Icons.icecream),
      ),
      floatingActionButtonLocation: FloatingActionButtonLocation.startTop,
    );
  }
}


```

</details>

### Screenshots or Video

<details>
<summary>Screenshots of SnackBar visible halfway off-screen</summary>

![Screenshot from 2023-06-02 18-43-32](https://github.com/flutter/flutter/assets/12886815/c2e4b113-7f11-4471-ab67-75dde789fbd9)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.3, on Pop!_OS 22.04 LTS 5.18.10-76051810-generic, locale en_US.UTF-8)
    • Flutter version 3.10.3 on channel stable at /home/user/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f92f44110e (23 hours ago), 2023-06-01 18:17:33 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/user/Android/Sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /home/user/Downloads/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.3)
    • Android Studio at /home/user/Downloads/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.78.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.66.0

[✓] Connected device (3 available)
    • Pixel 3a XL (mobile) • 94PAX0EFHR • android-arm64  • Android 12 (API 32)
    • Linux (desktop)      • linux      • linux-x64      • Pop!_OS 22.04 LTS 5.18.10-76051810-generic
    • Chrome (web)         • chrome     • web-javascript • Google Chrome 109.0.5414.74

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
Hi @jdsareault 
This is working as expected.  Snackbar isn't resized by itself for this type configuration. 

The documentation for `SnackBarBehavior.floating,` states:
>   /// This behavior will cause [SnackBar] to be shown above other widgets in the
>   /// [Scaffold]. This includes being displayed above a [BottomNavigationBar]
>   /// and a [FloatingActionButton].


Putting FAB on top and then using this snack behavior will produce this error message. You can avoid using this behaviour for this location of FAB conditionally or resize the Snackbar yourself to avoid this error.

**Comment by TahaTesser** [comment]
As per the offline discussion with @bleroux, it makes sense to put Snackbar in a floating state but at the bottom screen when FAB is at the top. This also requires updating the docs. 

Assigning @bleroux

**Comment by bleroux** [comment]
Reopening because the initial PR was reverted.
I will soon file a new PR.
