### ISSUE TITLE
Isolate Method Channels cannot be called asynchronously on iOS

### ISSUE THREAD

**Issue by kevmo314** [flutter/flutter#128133]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

See this repository: https://github.com/kevmo314/method_channel_ios

The repository has two commits, one `flutter create --platforms=ios` and the other to reproduce the issue: https://github.com/kevmo314/method_channel_ios/commit/0f7543abbaa1df1abafe6aa4305996a9ec0674c6

1. In the app, press Start
2. You should observe these logs:
```
[ +119 ms] flutter: isolateEntryPoint
[   +2 ms] flutter: got call triggered
```
3. Press Trigger
4. `got call triggered` does not print

### Expected results

`got call triggered` should print out twice, once for pressing Start and once for pressing Trigger.

### Actual results

`got call triggered` prints out once.

In the code, Start calls the corresponding MethodChannel, which:

1. Creates a new isolate
2. Sends a message on the isolate's method channel

This first step works. Then, when Trigger is pressed, the same channel invokes the same method as Start but this time it does not successfully make it to the isolate.

Curiously, the same pattern works correctly on Android.

### Code sample

See this repository: https://github.com/kevmo314/method_channel_ios

Unfortunately it's not super minimal because it involves native code but I hope the reproduction commit is sufficiently small.

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
% flutter doctor -v
[✓] Flutter (Channel stable, 3.10.3, on macOS 13.4 22F66 darwin-arm64, locale en-US)
    • Flutter version 3.10.3 on channel stable at /Users/kevin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f92f44110e (20 hours ago), 2023-06-01 18:17:33 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /opt/homebrew/share/android-commandlinetools
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 560193BB-B122-47B8-AD17-4F57A738C779 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by stuartmorgan** [comment]
Your engine is locally scoped to the `start` method handler, and nothing retains it, so it is being destroyed as soon as that handler ends, shutting down the engine.

Closing as this is the correct behavior for the given code; that code is managing engine lifetimes incorrectly.

**Comment by kevmo314** [comment]
Thanks for catching that! Wouldn't it make sense to throw an error if `invokeMethod()` is called on a channel bound to a destroyed engine?

For what it's worth, this issue was so painful because it was silently failing without any obvious avenue to debug that it caused my friend to abandon Flutter all together.
