### ISSUE TITLE
AssetEntityImageProvider._loadAsync

### ISSUE THREAD

**Issue by meet7-sagar23** [flutter/flutter#128101]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(Thumbnail request error, java.util.concurrent.ExecutionException: l2.q: Failed to load resource
There were 3 root causes:
s2.x$h(MediaMetadataRetriever failed to retrieve a frame without throwing, check the adb logs for .*MetadataRetriever.* prior to this exception for details)
s2.x$h(MediaMetadataRetriever failed to retrieve a frame without throwing, check the adb logs for .*MetadataRetriever.* prior to this exception for details)
s2.x$h(MediaMetadataRetriever failed to retrieve a frame without throwing, check the adb logs for .*MetadataRetriever.* prior to this exception for details)
 call GlideException#logRootCauses(String) for more detail, null, null). Error thrown Instance of 'ErrorDescription'.
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:653)
       at MethodChannel._invokeMethod(platform_channel.dart:315)
       at AssetEntityImageProvider._loadAsync(image_provider.dart:116)

### Expected results

Not to crash

### Actual results

App is crashing

### Code sample

The crash was detected on Firebase Crashlytics.

### Screenshots or Video

<details><summary>Device Details</summary>

```console
	* Brand:Motorola
	* Model:Moto G31
	* Orientation:Portrait
	* RAM free: 1.6 GB
	* Disk free: 38.51 GB
```

</details>

### Logs

<details><summary>Logs</summary>

```console
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(Thumbnail request error, java.util.concurrent.ExecutionException: l2.q: Failed to load resource
There were 3 root causes:
s2.x$h(MediaMetadataRetriever failed to retrieve a frame without throwing, check the adb logs for .*MetadataRetriever.* prior to this exception for details)
s2.x$h(MediaMetadataRetriever failed to retrieve a frame without throwing, check the adb logs for .*MetadataRetriever.* prior to this exception for details)
s2.x$h(MediaMetadataRetriever failed to retrieve a frame without throwing, check the adb logs for .*MetadataRetriever.* prior to this exception for details)
 call GlideException#logRootCauses(String) for more detail, null, null). Error thrown Instance of 'ErrorDescription'.
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:653)
       at MethodChannel._invokeMethod(platform_channel.dart:315)
       at AssetEntityImageProvider._loadAsync(image_provider.dart:116)
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.4 22F66 darwin-arm64, locale en-IN)
    • Flutter version 3.7.12 on channel stable at /Users/sagar.ghag23/fvm/versions/3.7.12
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (6 weeks ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/sagar.ghag23/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/sagar.ghag23/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.5672.126

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @meet7-sagar23 
Can you check if the crash can be reproducible when running in release mode? 

Also, are there any affected devices else? And what is the percentage occurrence of the crash on devices? 

Moreover, can you share the `pubspec.yaml` file content? Thank you!
