### ISSUE TITLE
Text(Form)Field must double-clicked for input in SelectionArea - Web App on IOS Device

### ISSUE THREAD

**Issue by cksoft0807** [flutter/flutter#128116]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Place TextFormField in SelectionArea
2. build with --web-renderer canvaskit 
3. Open with Browser on IOS Device

 SelectionContainer.disabled around TextFormFiled does not help

### Expected results

after clicking, text input possible

### Actual results

I must perform a double click

### Code sample

<details><summary>Code sample</summary>

```dart
           SelectionArea(
              child: Column(
                children: [
                  TextFormField(
                    decoration: InputDecoration(hintText: 'Test 123'),
                  ),
                  SelectionContainer.disabled(
                    child: TextFormField(
                      decoration: InputDecoration(hintText: 'Test 123'),
                    ),
                  ),
                ],
              ),
            ),
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>

</summary>

```console
[✓] Flutter (Channel stable, 3.10.2, on macOS 13.0 22A380 darwin-arm64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.78.2)
[✓] Connected device (2 available)
[✓] Network resources
```

</details>

**Comment by huycozy** [comment]
Hi @cksoft0807,
I see there's an open issue that is similar to the case you described https://github.com/flutter/flutter/issues/107327. I will close this issue in favor of that issue, so please follow up on it for further updates. Thank you!
