### ISSUE TITLE
Allow icon background color to be set separately from theme color in Android switcher

### ISSUE THREAD

**Issue by lukehutch** [flutter/flutter#128165]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

The Android app switcher UI (brought up by hitting the square icon at the bottom of the screen, on most phones) brings up a view of all the open apps, with the app icon in a circle above the screen view. The background of the icon view is the `primarySwatch` theme color of the app. In the following example, that color is purple:

![image](https://github.com/flutter/flutter/assets/811305/ce3d0ff0-fb0a-4cce-b377-dacace4df580)

### Proposal

I want to be able to theme the app *without* changing the background color of the icon in the app switcher view.

The icon background color should default to white (that seems to be what Google uses by default in the launcher, when icons don't have a background color), and to change it from white, you should have to set it manually in the app's `ThemeData`, using a setting different from `primarySwatch`.

**Comment by maRci002** [comment]
Can you tell me on Android how to achive this?

Currently you can do something like this:

```dart
    SystemChrome.setApplicationSwitcherDescription(
      ApplicationSwitcherDescription(
        label: title,
        primaryColor: color.value,
      ),
    );
```

This is how it is implemented on the engine:

https://github.com/flutter/engine/blob/2a3401c9bbb5a9a9aec74d4f735d18a9dd3ebf2d/shell/platform/android/io/flutter/plugin/platform/PlatformPlugin.java#L197-L218

However [`Title`](https://api.flutter.dev/flutter/widgets/Title-class.html) widget manages `SystemChrome.setApplicationSwitcherDescription` calls which is used by `MaterialApp` just change [`color` property](https://api.flutter.dev/flutter/material/MaterialApp/color.html)

**Comment by lukehutch** [comment]
Right now I'm doing

```dart
final themeData = ThemeData(
  primarySwatch: Colors.deepPurple,
  useMaterial3: true,
);

then in `MaterialApp` I use `theme: themeData`.

I added the code you gave, in `main`, before `runApp`, and it did not solve the problem. The switcher icon still has a purple background, even though I set `primaryColor: Color.white.value`.
```

**Comment by lukehutch** [comment]
OK, I found a solution, it is to set `color: Colors.white` inside `MaterialApp`. The solution was here:

https://stackoverflow.com/a/76386962/3950982

Still, I think that the default of using the `primarySwatch` as the icon background color is a bad default (Google's launcher uses white as the default icon background color), so I'll leave this bug open to address that issue specifically.

Probably the switcher background color should be white, unless overridden by setting `color` in `MaterialApp`.

**Comment by maRci002** [comment]
> OK, I found a solution, it is to set `color: Colors.white` inside `MaterialApp`.

Yes I already mentioned it:

> However [`Title`](https://api.flutter.dev/flutter/widgets/Title-class.html) widget manages `SystemChrome.setApplicationSwitcherDescription` calls which is used by `MaterialApp` just change [`color` property](https://api.flutter.dev/flutter/material/MaterialApp/color.html)

**Comment by lukehutch** [comment]
I see, thanks. Sorry, I didn't understand that comment before.

**Comment by dam-ease** [comment]
Hi @lukehutch. I see the latest concern looks similar to the issue you filed #122484.  I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you.

**Comment by lukehutch** [comment]
@dam-ease Sorry, I thought that older bug had been closed! Will refine what I'm asking for there. Thanks.
