### ISSUE TITLE
[go_router] documentation cannot read

### ISSUE THREAD

**Issue by gkdgo** [flutter/flutter#128104]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

access https://pub.flutter-io.cn/documentation/go_router/latest/topics/Navigation-topic.html
https://pub.flutter-io.cn/documentation/go_router/latest/topics/Redirection-topic.html
https://pub.flutter-io.cn/documentation/go_router/latest/topics/Web-topic.html
<img width="552" alt="iShot_2023-06-02_14 49 09" src="https://github.com/flutter/flutter/assets/55651847/d236036a-1ff3-44fa-932b-f471ba21093b">

### Expected results

<img width="824" alt="iShot_2023-06-02_14 50 12" src="https://github.com/flutter/flutter/assets/55651847/ef7bcbdd-9535-4c8f-bc95-6a9d848f6d21">

### Actual results

<img width="820" alt="iShot_2023-06-02_14 50 17" src="https://github.com/flutter/flutter/assets/55651847/94525e19-d297-4dd1-9638-060fdecfe690">

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @gkdgo, this is not a go_router issue. You should report this on either the mirrored pub repo or the pub repo so that it can be looked at. 
The site is responsible for the hosting of the documentation. The documentation on pub.dev itself works, so it's likely an issue with pub.flutter-io.cn. 

Closing from here. 

Thank you
