### ISSUE TITLE
Fix stale `ignore: prefer_const_constructors` from flutter/packages

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#128141]
We have some TODOs related to ignores in flutter/packages related to making classes const which can now be cleaned up by addressing the TODO (adding `const`, and removing the `ignore`). They can be found by searching for:

```
// TODO(goderbauer): Make this const when this package requires Flutter 3.8 or later.
```

Any package we make this change in will need to be updated to have a minimum Flutter version of 3.10 (the first stable after 3.8, where the constructors became const).

**Comment by SpruceVedant** [comment]
> We have some ignores in flutter/packages related to making classes const which can now be cleaned up. They can be found by searching for:
> 
> ```
> // TODO(goderbauer): Make this const when this package requires Flutter 3.8 or later.
> ```
> 
> (In some cases we may need to update minimum Flutter versions in packages while changing this.)

Hey, I have searched for the specific comment mentioned in the issue description, 
```// TODO(goderbauer): Make this const when this package requires Flutter 3.8 or later``` ,  but I couldn't locate it in the codebase.

However I managed to find many instances of : 
   ```// ignore: prefer_const_constructors``` and ``` // ignore: prefer_const_constructors_in_immutables```  in flutter/packages and I think these statements are stale and can be cleaned up right can you verify ?

**Comment by stuartmorgan** [comment]
> Hey, I have searched for the specific comment mentioned in the issue description,
> `// TODO(goderbauer): Make this const when this package requires Flutter 3.8 or later` , but I couldn't locate it in the codebase.

There are [many occurrences](https://github.com/search?q=%22Make+this+const+when+this+package+requires+Flutter+3.8+or+later%22&type=code).

> However I managed to find many instances of :
> `// ignore: prefer_const_constructors` and ` // ignore: prefer_const_constructors_in_immutables` in flutter/packages and I think these statements are stale and can be cleaned up right, can you verify ?

It depends on when and why they were added. You're welcome to investigate them on a case by case basis if you want to, but that's not what this issue is about. This is about the specific car described here.

**Comment by SpruceVedant** [comment]
> > Hey, I have searched for the specific comment mentioned in the issue description,
> > `// TODO(goderbauer): Make this const when this package requires Flutter 3.8 or later` , but I couldn't locate it in the codebase.
> 
> There are [many occurrences](https://github.com/search?q=%22Make+this+const+when+this+package+requires+Flutter+3.8+or+later%22&type=code).
> 
> > However I managed to find many instances of :
> > `// ignore: prefer_const_constructors` and ` // ignore: prefer_const_constructors_in_immutables` in flutter/packages and I think these statements are stale and can be cleaned up right, can you verify ?
> 
> It depends on when and why they were added. You're welcome to investigate them on a case by case basis if you want to, but that's not what this issue is about. This is about the specific case described here.

Now I get it , I was searching for it in the wrong place got confused , now I have found all of the instances of
 ```ignore: prefer_const_constructors``` in the packages repository, Thank you for clarifying!!

**Comment by SpruceVedant** [comment]
> We have some ignores in flutter/packages related to making classes const which can now be cleaned up. They can be found by searching for:
> 
> ```
> // TODO(goderbauer): Make this const when this package requires Flutter 3.8 or later.
> ```
so just ```ignore: prefer_const_constructors``` needs to be removed or ```//Todo``` 's also ?
> 
> (In some cases we may need to update minimum Flutter versions in packages while changing this.)

  can you elaborate regarding updating Flutter versions?

**Comment by ayinloya** [comment]
Like the comment mentions, do we add the const to the widget the `ignore: prefer_const_constructor` is on?

**Comment by stuartmorgan** [comment]
I have updated the issue description to clarify what this involves.

A PR that removes the `ignore`s without addressing the TODO won't pass analysis, and thus won't pass our CI.
