### ISSUE TITLE
Multiple button themes

### ISSUE THREAD

**Issue by tologonkudaiberdiuulu** [flutter/flutter#128167]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Hi, team! In my application I have three sections: ads, services and properties. And each has their own elevated button, textfield, textbutton, etc.. themes. I think it would be good to have multiple themes for such things. I know I can create three different buttons, textfields or anything else for each section as well, or make three different projects and make them integrate to one. But it would be good if flutter itself makes it

### Proposal

Can you provide multiple theming in themedata itself.
Say, `
textTheme: const TextTheme(
        displayLarge: TextStyle(fontFamily: 'Manrope', color: Colors.black),
displayLarge1: TextStyle(fontFamily: 'Roboto', color: Colors.grey),
      ),
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          foregroundColor: Colors.white,
          backgroundColor: AppColors.mainColor,
          elevation: 0,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(10),
          ),
          padding: const EdgeInsets.symmetric(
            vertical: 16,
            horizontal: 50,
          ),
          textStyle: const TextStyle(
            fontSize: 17,
            color: Colors.white,
            fontFamily: 'Manrope',
            fontWeight: FontWeight.bold,
          ),
        ),
elevatedButtonTheme1: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          foregroundColor: Colors.red,
          backgroundColor: AppColors.mainColor,
          elevation: 2,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(20),
          ),
          padding: const EdgeInsets.symmetric(
            vertical: 16,
            horizontal: 50,
          ),
          textStyle: const TextStyle(
            fontSize: 22,
            color: Colors.green,
            fontFamily: 'Roboto',
            fontWeight: FontWeight.bold,
          ),
        ),
      ),`

And use them further like 
`ElevatedButton(style: Theme.of(context).elevatedButtonTheme.style1, onPressed() {}, child: Text('Something'))`

**Comment by tologonkudaiberdiuulu** [comment]
@HansMuller think about I have 50 buttons in each section. I should wrap every time? Maybe for small apps it can be solution. But for big apps it would be difficult. And in every time when I want to change one section's design I have to change in all places

**Comment by HansMuller** [comment]
If the buttons all have a common ancestor, then you only need to put the  button theme above the common ancestor (once).

**Comment by Piinks** [comment]
Hi @tologonkudaiberdiuulu thanks for bringing this up! We're not likely to do this, so I am going to close this issue. Support for additional features like this can be provided using TheemExtensions: https://api.flutter.dev/flutter/material/ThemeExtension-class.html
