### ISSUE TITLE
succeeded LUCI build not reporting back to GitHub

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#128134]
https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20module_test/29522/overview

On the Engine -> Framework roll here https://github.com/flutter/flutter/pull/128119

Is not updating its status on GitHub, and so the roll has been stuck for 4 hours.

Related: https://github.com/flutter/flutter/issues/125451

cc @keyonghan @jonahwilliams

**Comment by keyonghan** [comment]
For each presubmit check run, two LUCI pubsub messages are expected: one is `Started` and the other one is `Completed`.
However for `Linux module_test`: https://github.com/flutter/flutter/pull/128119/checks?check_run_id=13961572186, there is only one message (started):
```
INFO 2023-06-02T15:27:19.585Z /api/presubmit-luci-subscription
```

This sounds a LUCI notification missing when build finishes. I will create a LUCI bug to track. At the same time, rerun the hanging task to unblock the roll.

**Comment by keyonghan** [comment]
https://crbug.com/1451004 to track LUCI buildbucket pubsub message miss.

**Comment by keyonghan** [comment]
LUCI side confirmed messaged sent out to our topic, but our side did not seem to receive it. Sounds a message missing from pub/sub. The module we are using is stale and may not be reliable. http://b/268253534 tracks migrating to the new buildbucket pubsub modules (EOQ).

Moving this out of ticket queue to keep tracking from Flutter side.

**Comment by ricardoamador** [comment]
This is most likely the same issue as this: https://github.com/flutter/flutter/issues/135640. A fix was submitted and it appears we are no longer blocking on this but now we need to investigate why the discrepancy with ciYaml targets being returned.

**Comment by keyonghan** [comment]
Several fixes have been in, and please reopen if you see this again.
