### ISSUE TITLE
upgrade devicelab linux to ubuntu focal release

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#128279]
@kentnguyen99 We need to update the devicelab machines to ubuntu focal (Ubuntu 20.04.6 LTS) release.

Lets start with updating https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-linux-14 in the staging pool.

I believe the following commands should allow you to do this. But please verify that is the case:

```
sudo apt update
sudo apt upgrade
sudo apt dist-upgrade

sudo apt instlal update-manager-core
```
In the file `/etc/update-manager/release-upgrades` make sure the line says:

`Prompt=lts`
```
sudo do-release-upgrade
```

**Comment by kentnguyen99** [comment]
Machine linux-14 has been upgraded to Ubuntu 20.04.6 as requested.

flutter@flutter-devicelab-linux-14:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal

**Comment by yusuf-goog** [comment]
Great. Lets keep this bug open to track the whole fleet upgrade. Tomorrow, once this machine has a change to run for a bit, we can perform upgrade on a prod pool machine: [flutter-devicelab-linux-1](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-linux-1)

**Comment by yusuf-goog** [comment]
@kentnguyen99 linux-14 seems to be functioning correctly, please go ahead and update linux-1 to focal.

**Comment by kentnguyen99** [comment]
Upgrading Ubuntu 20.04.6 onto machine linux-1 has been completed.
flutter@flutter-devicelab-linux-1:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal

**Comment by yusuf-goog** [comment]
linux-1 seems to be working well. Lets go ahead and upgrade 5 more each from staging and prod pools.

**Comment by kentnguyen99** [comment]
Below Linux machines have been upgraded to Ubuntu 20.04.6 LTS.
Production:
- linux-2
- linux-3
- linux-4
- linux-5
- linux-6
Staging:
- linux-13
- linux-17
- linux-18
- linux-26
- linux-27

**Comment by yusuf-goog** [comment]
@kentnguyen99 the focal machines are looking stable.

Lets go ahead and upgrade all the staging machines and 8 more of the prod machines.

**Comment by kentnguyen99** [comment]
Upgrading Ubuntu 20.04 all Linux machines on Production side have been completed.

**Comment by kentnguyen99** [comment]
Upgrading Ubuntu 20.04 all Linux machines in Staging pool have been completed.
