### ISSUE TITLE
Flutter Doctor response about the connected devices

### ISSUE THREAD

**Issue by mariam-wahba** [flutter/flutter#128233]
Can Anyone help me ? 

When i write flutter doctor, it replies to me with this msg

Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ Exception: Unable to run "adb", check your Android SDK installation and ANDROID_SDK_ROOT environment variable:
      /Users/software/Library/Android/sdk/platform-tools/adb

first point I have no idea what's that
Second I found out that although that i'm sure that downloaded everything correctly and i used to see the Folder Android with it's sdk Folder in the Library path and i'm sure that when i downloaded it i located in the library by myself, but physically the Folder android in not there which is wierd it should be there.

Also in my android studio the tab that lists the connected devices disappeared and a message showed up the Flutter Daemon terminated and i restarted the android studio many times as what i've found in my searches also checked many times about my devices connection usb debugger is on. Moreover, One of the suggestions thats i change my port to 5038 and when it tells me could not connect on port 5037 which very very wierd.

i need help as soon as possible

**Comment by huycozy** [comment]
Can you please share the complete output of `flutter doctor -v`?

Also, please check this [SO](https://stackoverflow.com/questions/65262594/flutter-unable-to-run-adb-check-your-android-sdk-installation-and-android-sdk) thread if it can help.

**Comment by mariam-wahba** [comment]
Here is the output of flutter doctor -v
[✓] Flutter (Channel stable, 3.10.3, on macOS 13.4 22F66 darwin-x64, locale en-EG)
    • Flutter version 3.10.3 on channel stable at /Users/software/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f92f44110e (5 days ago), 2023-06-01 18:17:33 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/software/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ Exception: Unable to run "adb", check your Android SDK installation and ANDROID_SDK_ROOT environment variable:
      /Users/software/Library/Android/sdk/platform-tools/adb
    • #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
      #1      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device_discovery.dart:75:7)
      <asynchronous suspension>
      #2      PollingDeviceDiscovery._populateDevices (package:flutter_tools/src/device.dart:563:36)
      <asynchronous suspension>
      #3      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
      <asynchronous suspension>
      #4      DeviceManager.refreshAllDevices (package:flutter_tools/src/device.dart:231:40)
      <asynchronous suspension>
      #5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:683:34)
      <asynchronous suspension>
      #6      Future.any.onValue (dart:async/future.dart:615:5)
      <asynchronous suspension>


[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

**Comment by huycozy** [comment]
@mariam-wahba Have you checked the linked SO thread I provided above? Does it work for you? 
Also, can you try running `adb` command in the Terminal to see if it works or not? It should output like this:

```console
➜  ~ adb
Android Debug Bridge version 1.0.41
Version 31.0.3-7562133
Installed as /Users/huynq/Library/Android/sdk/platform-tools/adb
....
```
