### ISSUE TITLE
Add ability to optionally enable or disable ripple when clicking on a text field in SearchView

### ISSUE THREAD

**Issue by MaxYablochkin** [flutter/flutter#128237]
#91605

1. Remove ripples when clicking on a text field in SearchView
<details>
<summary>Screenshots/Videos</summary>

![Screenshot_1685963864](https://github.com/flutter/flutter/assets/102767277/fcfa0496-48a5-4536-ac79-52f892d30686)

[untitled.webm](https://github.com/flutter/flutter/assets/102767277/0a6c1b67-3ff3-4f0a-ae0b-01ac7ab78318)

</details>

2. Add the ability to edit text in the SearchView text field using selection pointers, magnifier, and more.

**Comment by huycozy** [comment]
Hi @MaxYablochkin 
Thanks for filing the issue, but each issue should be specific. There is more than one issue in this proposal. Please try to provide detailed information in the issue template so we can address it properly.

With regard to each issue:
>Remove ripples when clicking on a text field in SearchView

I can see the ripple/splash effect on Search bar but can't see it on Search view (Please check my demo video below). Meanwhile, the effect exists on Search view from your video. Can you please check this again with 2nd example on [SearchAnchor class](https://api.flutter.dev/flutter/material/SearchAnchor-class.html)?

>Add the ability to edit text in the SearchView text field using selection pointers, magnifier, and more.

I can see it's quite difficult to get focus and display the magnifier on TextField. But what about `more` here? I would recommend you file a separate issue for this. Thank you!

<details>
<summary>Demo</summary>

https://github.com/flutter/flutter/assets/104349824/16d5463c-2166-4fc7-8d7a-4d1645de1485
</details>

**Comment by huycozy** [comment]
Thanks, I can see the ripple/splash effect when using dark theme. Labeling this issue as a proposal to give an option to turn on/off it.

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for pinned [SearchAnchor] while scrolling.

void main() {
  runApp(const PinnedSearchBarApp());
}

class PinnedSearchBarApp extends StatefulWidget {
  const PinnedSearchBarApp({super.key});

  @override
  State<PinnedSearchBarApp> createState() => _PinnedSearchBarAppState();
}

class _PinnedSearchBarAppState extends State<PinnedSearchBarApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
          useMaterial3: true, colorScheme: const ColorScheme.dark()),
      home: Scaffold(
        body: SafeArea(
          child: CustomScrollView(
            slivers: <Widget>[
              SliverAppBar(
                clipBehavior: Clip.none,
                shape: const StadiumBorder(),
                scrolledUnderElevation: 0.0,
                titleSpacing: 0.0,
                backgroundColor: Colors.transparent,
                floating:
                true, // We can also uncomment this line and set `pinned` to true to see a pinned search bar.
                title: SearchAnchor.bar(
                  suggestionsBuilder:
                      (BuildContext context, SearchController controller) {
                    return List<Widget>.generate(
                      5,
                          (int index) {
                        return ListTile(
                          titleAlignment: ListTileTitleAlignment.center,
                          title: Text('Initial list item $index'),
                        );
                      },
                    );
                  },
                ),
              ),
              // The listed items below are just for filling the screen
              // so we can see the scrolling effect.
              SliverToBoxAdapter(
                child: Padding(
                  padding: const EdgeInsets.all(20),
                  child: SizedBox(
                    height: 100.0,
                    child: ListView.builder(
                      scrollDirection: Axis.horizontal,
                      itemCount: 10,
                      itemBuilder: (BuildContext context, int index) {
                        return SizedBox(
                          width: 100.0,
                          child: Card(
                            child: Center(child: Text('Card $index')),
                          ),
                        );
                      },
                    ),
                  ),
                ),
              ),
              SliverToBoxAdapter(
                child: Padding(
                  padding: const EdgeInsets.symmetric(horizontal: 20),
                  child: Container(
                    height: 1000,
                    color: Colors.deepPurple.withOpacity(0.5),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```
</details>

**Comment by Piinks** [comment]
I think this can already be achieved through the theme: 

```
ThemeData(splashFactory: NoSplash.splashFactory),
```

@MaxYablochkin does that resolve your issue?
