### ISSUE TITLE
iOS: Notification Service Extension with firebase_messaging plugin fails to compile

### ISSUE THREAD

**Issue by num46664** [flutter/flutter#12828]
## Steps to Reproduce

I created a new flutter project in IntelliJ, followed the instructions in the [firebase_messaging readme](https://github.com/flutter/plugins/tree/master/packages/firebase_messaging) for both android and iOS integration.

I copied the `main.dart` from [the example](https://github.com/flutter/plugins/tree/master/packages/firebase_messaging/example)

at this point everything works as intended, and I can build the project in IntelliJ, it runs, and receives notifications.

I am now trying to use the iOS Notification Service Extension in order to change notification content before displaying it as described [here](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/ModifyingNotifications.html) 

I opened `ios/Runner.xcworkspace` in Xcode and followed the instructions at the previous link to set up the Notification Service.  As soon as this is done the project no longer compiles in IntelliJ. (It does compile and run as intended through Xcode)

### Flutter Run
The part of the logs that stand out to me is this bit:

````

Ld /Users/baraka/Source/firebase_msg_test_2/build/ios/Debug-iphoneos/notification-service.appex/notification-service normal arm64
               cd /Users/baraka/Source/firebase_msg_test_2/ios
               export IPHONEOS_DEPLOYMENT_TARGET=11.0
               export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/baraka/flutter/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin"
               /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk -L/Users/baraka/Source/firebase_msg_test_2/build/ios/Debug-iphoneos -L/Users/baraka/Source/firebase_msg_test_2/build/ios/Debug-iphoneos/GoogleToolboxForMac -L/Users/baraka/Source/firebase_msg_test_2/build/ios/Debug-iphoneos/Protobuf -L/Users/baraka/Source/firebase_msg_test_2/build/ios/Debug-iphoneos/firebase_messaging -L/Users/baraka/Source/firebase_msg_test_2/build/ios/Debug-iphoneos/nanopb -L/Users/baraka/Source/firebase_msg_test_2/build/ios/Debug-iphoneos/path_provider -F/Users/baraka/Source/firebase_msg_test_2/build/ios/Debug-iphoneos -F/Users/baraka/Source/firebase_msg_test_2/ios/Pods/FirebaseAnalytics/Frameworks -F/Users/baraka/Source/firebase_msg_test_2/ios/Pods/FirebaseCore/Frameworks -F/Users/baraka/Source/firebase_msg_test_2/ios/Pods/FirebaseInstanceID/Frameworks -F/Users/baraka/Source/firebase_msg_test_2/ios/Pods/FirebaseMessaging/Frameworks -F/Users/baraka/Source/firebase_msg_test_2/ios/Pods/../../../../flutter/bin/cache/artifacts/engine/ios -filelist /Users/baraka/Library/Developer/Xcode/DerivedData/Runner-fguijgcpftvfzkdeuczcdxyozfgv/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/notification-service.build/Objects-normal/arm64/notification-service.LinkFileList -miphoneos-version-min=11.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/baraka/Library/Developer/Xcode/DerivedData/Runner-fguijgcpftvfzkdeuczcdxyozfgv/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/notification-service.build/Objects-normal/arm64/notification-service_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fapplication-extension -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -Xlinker -add_ast_path -Xlinker /Users/baraka/Library/Developer/Xcode/DerivedData/Runner-fguijgcpftvfzkdeuczcdxyozfgv/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/notification-service.build/Objects-normal/arm64/notification_service.swiftmodule -ObjC -lGoogleToolboxForMac -lProtobuf -lc++ -lfirebase_messaging -lnanopb -lpath_provider -lsqlite3 -lz -framework AddressBook -framework FirebaseAnalytics -framework FirebaseCore -framework FirebaseCoreDiagnostics -framework FirebaseInstanceID -framework FirebaseMessaging -framework FirebaseNanoPB -framework Flutter -framework StoreKit -framework SystemConfiguration -e _NSExtensionMain -Xlinker -dependency_info -Xlinker /Users/baraka/Library/Developer/Xcode/DerivedData/Runner-fguijgcpftvfzkdeuczcdxyozfgv/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/notification-service.build/Objects-normal/arm64/notification-service_dependency_info.dat -o /Users/baraka/Source/firebase_msg_test_2/build/ios/Debug-iphoneos/notification-service.appex/notification-service
           ld: library not found for -lfirebase_messaging
           clang: error: linker command failed with exit code 1 (use -v to see invocation)
````

The rest of the log is [here](https://github.com/flutter/flutter/files/1435784/log.txt) but I don't think that the notification service needs to be linking all of these libraries and frameworks. I checked the build settings in Xcode, and the notification service isn't set to link anything.

`flutter analyze`  shows no issues found.

## Flutter Doctor

````
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-GB, channel master)
    • Flutter at /Users/baraka/flutter
    • Framework revision 80e159d469 (4 hours ago), 2017-11-01 10:29:37 -0700
    • Engine revision ddd51597d0
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.0)
    • Android SDK at /Users/baraka/Library/Android/sdk
    • Platform android-27, build-tools 27.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.0.1, Build version 9A1004
    • ios-deploy 1.9.2
    • CocoaPods version 1.1.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2.5)
    • Flutter plugin version 18.3
    • Dart plugin version 172.4343.25

[✓] Connected devices
    • Nexus 4          • 07ad4650db91e966                         • android-arm • Android 4.4 (API 19)
    • Richard’s iPhone • 17a4fc503dedd88b69f26902292adbec900c6056 • ios         • iOS 11.0.3

````

**Comment by num46664** [comment]
@cbracken has anyone taken a look at this?

**Comment by num46664** [comment]
@zoechi I am no longer working on the project where this was an issue. But this remained an issue while I was working on it. 

@rmtmckenzie might know more about the status of this.

**Comment by zoechi** [comment]
@num46664 ok, thanks for the update!

**Comment by rmtmckenzie** [comment]
I'll try to give this a check in the next few days and report back whether it's still an issue when I get a chance.

**Comment by sandeepcmsm** [comment]
@zoechi It's still happening in flutter 1.0.

**Comment by sandeepcmsm** [comment]
@cbracken any updates on this issue?

**Comment by henadark** [comment]
@zoechi I have the same issue. If add notification service extension to project where external package is absent (for example "flutter_youtube") - it is ok. But if install some package, I have error
`ld: framework not found XCDYouTubeKit
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Even if **Enable Bitcode** and **Require Only App-extension-Safe API** set to _NO_ in **Build Settings** of extension

**Comment by Ethras** [comment]
same issue here

**Comment by zoechi** [comment]
@Ethras Using "add reaction" on the initial comment would increase priority while `+1` comments are rather pointless and cause lots of people to get notified for no reason.
To get notified yourself use the [Subscribe] button to the top right instead.

**Comment by saitbnzl** [comment]
I came across this issue with OneSignal plugin. Although [this comment](https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/42#issuecomment-459476383) says adding all dependencies to the NotificationServiceExtension target solves the problem, I couldn't get it work yet.

And idk why but while **flutter build** and Xcode build fails, **flutter run** works.

**Comment by baipeng1009472720** [comment]
目前没有好的解决办法 只能在目标里面加上依赖。。

**Comment by jmagman** [comment]
I'm reproducing something very similar in an add-to-app scenario.  I might be able to fix the issue I'm seeing, but I'm not sure it's the same one as is reported here.
If anyone is still reproducing, can you cd into your flutter app directory and give the output of:
1. pwd
2. xcodebuild -showBuildSettings -configuration Debug | grep -E "SRCROOT|LIBRARY_SEARCH_PATHS"
3. cat ios/Flutter/Generated.xcconfig

**Comment by tango5614** [comment]
I met the same issue, this solution works for me:
![bug](https://user-images.githubusercontent.com/35095715/61613131-0674d200-ac93-11e9-92a5-7e3f35257268.png)
Select notification in your **TARGETS**, go to the **Build Phases** tab, drag all these three framework into the **Link Binary With Libraries**, then rebuild.

**Comment by saitbnzl** [comment]
Can someone please explain the underlying issue here? This issue is blocking push notification development, not related to firebase_messaging only. Workarounds are temporary. This always comes back, sometimes in XCode, sometimes Flutter CLI.

**Comment by saitbnzl** [comment]
I've found another workaround. And I thinks it's better than others. Here is my finding:

I have noticed when I create notification extension service target some linker flags gets added automatically. I have removed them all:

1. Select the extension target.
2. Go to Build Settings, 
3. Search for "Other Linker Flags"
4. Remove all the flags.

The issue never occured since I've done this. I think it's already better than adding unnecessary frameworks to extension target. So I'm happy with this right now. If it's a really permanent solution, I would say "a perfect workaround" :)

**Comment by bestK** [comment]
> I've found another workaround. And I think it's better than others. Here is my finding:
> 
> I have noticed some linker flags gets added automatically when I create notification service extension target. I have removed them all:
> 
> 1. Select the extension target.
> 2. Go to Build Settings.
> 3. Search for "Other Linker Flags".
> 4. Remove all the flags.
> 
> The issue has never occured since I've done this. I think it's already better than adding unnecessary frameworks to extension target. So I'm happy with this right now. If it's a really permanent solution, I would say "a perfect workaround" :)
> 
> Edit: Looks solid. Nothing breaks it in my cases.

Work for me , thanks dude

**Comment by kroikie** [comment]
@num46664

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/946. Any further collaboration will be done there.

**Comment by mohsinka** [comment]
@tango5614 Thank you for your help. I spent a whole one day on this until you helped me out here. Thanks again 🙏🏼
