### ISSUE TITLE
FadeInImage should have a color attribute

### ISSUE THREAD

**Issue by nietsmmar** [flutter/flutter#128229]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I want to avoid using `Opacity()` to improve performance. But I can't use the `color` Attribute in `FadeInImage` as proposed here https://api.flutter.dev/flutter/widgets/Opacity-class.html#transparent-image. 

### Proposal

Provide the `color` Attribute in the `FadeInImage` widget.

**Comment by prasadsunny1** [comment]
@huycozy Does this request makes sense? Should this be tried?

**Comment by huycozy** [comment]
@prasadsunny1 This issue has been prioritized with P3 as it's a feature request. You might want to take a look at this: [How issue prioritization works](https://github.com/flutter/flutter/wiki/Issue-hygiene#priorities)
