### ISSUE TITLE
Improve documentation for Timeline, TimelineTask, and checkerboardOffscreenLayers

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#128270]
As I'm debugging performance issues in my app, I'm running into documentation that seems incomplete.

**Timeline and TimelineTask**
In the [Using the Performance View](https://docs.flutter.dev/development/tools/devtools/performance) guide, we're linked to `Timeline` and `TimelineTask`, but neither in the guide, nor in the class docs, is it shown how to use the `Timeline` or `TimelineTask` classes. I recommend including a nominal example of each one. Based solely on the existing docs, I'm not confident how I should wrap my existing behavior to achieve the desired timeline logging. If I get it wrong, I might draw incorrect conclusions about the logged code paths.

**checkerboardOffscreenLayers**
In the [Flutter performance profiling](https://docs.flutter.dev/perf/ui-performance#identifying-problems-in-the-gpu-graph) guide, we're told to use the `PerformanceOverlayLayer.checkerboardOffscreenLayers` to find offscreen layers. But it's not clear how to access that property. The [property docs](https://api.flutter.dev/flutter/rendering/PerformanceOverlayLayer/checkerboardOffscreenLayers.html) say nothing about where/how to access the property. Nor do the docs for [PerformanceOverlayLayer](https://api.flutter.dev/flutter/rendering/PerformanceOverlayLayer-class.html).

I recommend adding nominal examples that use these artifacts to achieve the desired goal. That way, developers know exactly where and how to apply this tools to help diagnose performance problems.

EDIT: Here's supporting evidence that others are confused, too: https://stackoverflow.com/questions/66717877/how-do-i-enable-performanceoverlaylayer-checkerboardoffscreenlayers-in-flutter

EDIT 2: After using the info in that StackOverflow post to enable the checkerboard, I'm not sure what to do with the information. I'm rendering pages of a document with Flutter. Every page in the document shows a checkerboard. I assume that this is because I wrapped each page with a `RepaintBoundary`. If that's the case, those `RepaintBoundary`s were added as a major performance improvement - I certainly don't want to get rid of them. So now I'm wondering what these offscreen layer checkerboards are supposed to communicate to me. How is a developer expected to act on this information?

**Comment by atsansone** [comment]
This calls for changes to the API docs for the 3 given components.

**Comment by kenzieschmoll** [comment]
@johnpryan this seems similar to what we were discussing last week. Another example where a user found it confusing how to use these APIs: https://github.com/flutter/devtools/issues/5835#issuecomment-1557582512

**Comment by Hixie** [comment]
The checkerboard features have been removed, so there's nothing to document there anymore.
The Timeline features are documented in the API docs, including sample code. If that documentation is insufficient I would recommend filing a Dart issue, as the Timeline API is not specific to Flutter.
