### ISSUE TITLE
☂️ `package:unified_analytics` implementation in flutter tool

### ISSUE THREAD

**Issue by eliasyishak** [flutter/flutter#128251]
Tracker issue for the migration from GA3 to GA4 with the use of [`package:unified_analytics`](https://pub.dev/packages/unified_analytics)

Tasks:
- Setup the analytics instance to use the same logic as package:usage for initialization
  - [x] https://github.com/flutter/flutter/pull/134756
- Migration of doctor events from [`DoctorResultEvent`](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/reporting/events.dart#L106C7-L139)
  - [x] PR in `dart-lang/tools` to add event: https://github.com/dart-lang/tools/pull/178
  - [x] PR in `flutter/flutter` to use new event: https://github.com/flutter/flutter/pull/136647
- Migration of build events from [`BuildEvent`](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/reporting/events.dart#L151-L189)
  - [x] PR in `dart-lang/tools` to add event: https://github.com/dart-lang/tools/pull/187
  - [x] PR in `flutter/flutter` to use new event: https://github.com/flutter/flutter/pull/137562
- Migration of hot reload events from [`HotEvent`](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/reporting/events.dart#L36C7-L58)
  - [x] PR in `dart-lang/tools` to add event: https://github.com/dart-lang/tools/pull/193
  - [x] PR in `flutter/flutter` to use new event: https://github.com/flutter/flutter/pull/137717
- 🚫 Migration of event [`PubResultEvent`](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/reporting/events.dart#L142-L148) -- **Migration is not necessary since pub will be sending its own events soon**
  - [x] PR in `dart-lang/tools` to add event: https://github.com/dart-lang/tools/pull/194
  - [x] PR in `flutter/flutter` to use new event: https://github.com/flutter/flutter/pull/138012
- Migration of event [`CommandResultEvent`](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/reporting/events.dart#L191-L193) and [`Usage.command`](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/reporting/usage.dart#L32-L34)
  - [x] PR in `dart-lang/tools` to add event: https://github.com/dart-lang/tools/pull/199
  - [x] PR in `flutter/flutter` to use new event: https://github.com/flutter/flutter/pull/138165
  - [x] PR in `dart-lang/tools` to add `commandHasTerminal` param: https://github.com/dart-lang/tools/pull/204
  - [x] PR in `flutter/flutter` to include `commandHasTerminal` param: https://github.com/flutter/flutter/pull/138806
- 🚫 ~~Migration of event [`AnalyticsConfigEvent`](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/reporting/events.dart#L223-L233)~~
  - [x] Not necessary because [`package:unified_analytics`](https://github.com/dart-lang/tools/blob/main/pkgs/unified_analytics/lib/src/analytics.dart#L586-L588) already emits an event on opt out/in
- Migration of event [`CodeSizeEvent`](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/reporting/events.dart#L236-L244)
  - [x] PR in `dart-lang/tools` to add event: https://github.com/dart-lang/tools/pull/200
  - [x] PR in `flutter/flutter` to use new event: https://github.com/flutter/flutter/pull/138351
- 🚫 ~~Migration of event [`ErrorHandlingEvent`](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/reporting/events.dart#L247-L249)~~
  - [x] Not necessary because there are no callers of this event
- 🚫 ~~Migration of event [[`NullSafetyAnalysisEvent`]](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/reporting/events.dart#L256-L262)~~
  - [x] PR in `dart-lang/tools` to add event: https://github.com/dart-lang/tools/pull/202
  - [x] PR in `flutter/flutter` to use new event: https://github.com/flutter/flutter/pull/138419
- Migration of event [`UsageEvent`](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/reporting/events.dart#L11-L27) – these events are all ios/macos related
  - [x] PR in `dart-lang/tools` to add event: https://github.com/dart-lang/tools/pull/206
  - [x] PR in `flutter/flutter` to use new event: https://github.com/flutter/flutter/pull/138806
- Migration of [`sendException`](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/reporting/usage.dart#L313-L320)
  - [x] PR in `dart-lang/tools` to add event: https://github.com/dart-lang/tools/pull/206
  - [x] PR in `flutter/flutter` to use new event: https://github.com/flutter/flutter/pull/138806
- Migration of timing events ([`sendTiming`](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/reporting/usage.dart#L295-L311) method)
  - [x] PR in `dart-lang/tools` to add event: https://github.com/dart-lang/tools/pull/208
  - [x] **REVERTED** PR in `flutter/flutter` to use new event: https://github.com/flutter/flutter/pull/138896
    - [x] PR for Relanding in `flutter/flutter`: https://github.com/flutter/flutter/pull/139299
- Migration of the `CustomDimensions` which are sent from the `FlutterCommand.verifyThenRunCommand`
  - [x] PR in `dart-lang/tools` to add event: https://github.com/dart-lang/tools/pull/211
  - [x] PR in `flutter/flutter` to use new event: https://github.com/flutter/flutter/pull/139383

## Post migration updates needing to be made
- Send enabled features with each event
  - [x] PR in `dart-lang/tools` to add parameter: https://github.com/dart-lang/tools/pull/217
  - [x] PR in `flutter/flutter` to use new parameter: https://github.com/flutter/flutter/pull/139934
- Remove legacy code from flutter/flutter
  - [ ] PR in `flutter/flutter`: TBD

## Cherrypicks into stable
- [x] PR in `flutter/flutter`: https://github.com/flutter/flutter/pull/141019

**Comment by eliasyishak** [comment]
This finally complete! The CP that was merged in today into stable includes the migration for usage values. All other events are expected to make it into stable for the February 2024 release

**Comment by jmagman** [comment]
I'm not sure if this was intentionally reopened, but I'll close again, and ongoing work can be tracked individually instead of in the umbrella.
