### ISSUE TITLE
How to paste images to textfield flutter

### ISSUE THREAD

**Issue by Lucifer-Otis** [flutter/flutter#128205]
Im trying to create a flutter notes app , In  textField,  I couldn't paste a image to it like ios notes app

reference images: 
![photo_2_2023-06-04_16-31-16](https://github.com/flutter/flutter/assets/77739521/6ff87ff0-6ab2-459c-8ca6-719357a24036)
![photo_1_2023-06-04_16-31-16](https://github.com/flutter/flutter/assets/77739521/e6019f12-45c4-4c26-bc1d-5efab0b12673)

**Comment by Renzo-Olivares** [comment]
This feature isn't supported in `TextField` yet, a different issue https://github.com/flutter/flutter/issues/23603 and https://github.com/flutter/flutter/issues/92506 are tracking this functionality. Closing this as a duplicate, but feel free to re-open if your use-case does not fall under those issues.
