### ISSUE TITLE
Extension: The member 'setState' can only be used within instance members of subclasses

### ISSUE THREAD

**Issue by machinescream** [flutter/flutter#128225]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

write an extension on State and try to call setState in it.

### Expected results

no warning

### Actual results

warning

### Code sample

<details><summary>Code sample</summary>

```dart
extension SafeUpdate<T extends StatefulWidget> on State<T> {
  void safeSetState(VoidCallback fn) {
    if (!mounted) return;
    setState(fn);
  }
}
```
</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>
![Screenshot 2023-06-05 at 10 48 23](https://github.com/flutter/flutter/assets/42138594/5af8bbda-7a7c-4a14-a7ff-819134e72a57)
</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.3.1 22E261 darwin-arm64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
[✓] VS Code (version 1.77.3)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

```

</details>

**Comment by machinescream** [comment]
> I think it's quite clear in the warning message. Instead, you can move `setState()` to `fn`'s callback, for eg:
> 
> ```dart
> safeSetState(
>     () {
>         setState((){});
>     }
> )
> ```
> 
> Is it applicable to your case?

Hi, thank you for your response. I would say it's not really what I want to achieve. From user perspective it should be something like this?
```dart
safeSetState((){
  counter++;
  setState((){});
});
```
Example above can cause some misunderstanding because you already have written setState and expecting that State will rebuild, but it's not without another vanilla setState. extension - is some kind of part of the class, for me it's not really clear why rule define it like "outside of the class". And also I don't wanna use mixin, because it's much more boilerplate rather than extension.

**Comment by huycozy** [comment]
As far as I understand, you're expecting to use that extension function in every State, right? But it doesn't seem to be feasible with extension approach. 

Per [setState method](https://api.flutter.dev/flutter/widgets/State/setState.html):

>Calling [setState](https://api.flutter.dev/flutter/widgets/State/setState.html) notifies the framework that the internal state of this object has changed in a way that might impact the user interface in this subtree, which causes the framework to schedule a [build](https://api.flutter.dev/flutter/widgets/State/build.html) for this [State](https://api.flutter.dev/flutter/widgets/State-class.html) object.

It means that `setState` will notify to rebuild a specific `State object`.

Also, I'm not sure how your mixin idea looks like, but I see there are some applicable approaches for this case:

#### 1. Using `abstract class` 

<details>
<summary>Sample code</summary>

```dart
abstract class BaseWidget extends StatefulWidget {
  const BaseWidget({super.key});
}

abstract class BaseState<T extends BaseWidget> extends State<T> {
  void safeSetState(VoidCallback fn) {
    if (!mounted) return;
    setState(fn);
  }

  @override
  Widget build(BuildContext context) {
    return const Placeholder();
  }
}

class MyApp extends BaseWidget {
  const MyApp({super.key});

  @override
  BaseState<MyApp> createState() => _MyAppState();
}

class _MyAppState extends BaseState<MyApp> {
  int _counter = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: GestureDetector(
          onTap: () {
            safeSetState(() {
              _counter++;
            });
          },
          child: Container(
            padding: const EdgeInsets.all(20),
            color: Colors.blue,
            child: Text(_counter.toString()),
          ),
        ),
      ),
    );
  }
}
```
</details>

#### 2. Using `extension` on a concrete State class

<details>
<summary>Sample code</summary>

```dart
class StateImpl<T extends StatefulWidget> extends State<T> {
  @override
  Widget build(BuildContext context) {
    throw UnimplementedError();
  }

  void safeSetState(VoidCallback fn) {
    if (!mounted) return;
    setState(fn);
  }
}

extension SafeUpdate<T extends StatefulWidget> on StateImpl<T> {
  void safeSetStateExt(VoidCallback fn) => safeSetState(fn);
}

class TestSolution extends StatefulWidget {
  const TestSolution({Key? key}) : super(key: key);

  @override
  State<TestSolution> createState() => _TestSolutionState();
}

class _TestSolutionState extends StateImpl<TestSolution> {
  int _counter = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: GestureDetector(
          onTap: () {
            safeSetStateExt(() {
              _counter++;
            });
          },
          child: Container(
            padding: const EdgeInsets.all(20),
            color: Colors.blue,
            child: Text(_counter.toString()),
          ),
        ),
      ),
    );
  }
}
```
</details>
