### ISSUE TITLE
[CP] Fix raster cache optional value check logic

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#128362]
### Issue Link

https://github.com/flutter/flutter/issues/128308

### Commit Hash

https://github.com/flutter/engine/commit/4e80c6fa15c8ff52ae1f5a314791a454ecc295c5

### Target

beta

### PR Link

https://github.com/flutter/engine/pull/42599

### Changelog Description

Fixes a performance regression on Android.

### Impacted Users

All users targeting Android

### Impact Description

Severely reduced performance on Android in apps that rely on the Engine's raster cache.

### Workaround

There is no workaround.

### Risk

low

### Test Coverage

yes

### Validation Steps

CI benchmarks show that performance has recovered.

**Comment by zanderso** [comment]
Note that this is a CP request for the forthcoming 3.12 beta.

cc @jonahwilliams for review
cc @Jasguerrero

**Comment by jonahwilliams** [comment]
LGTM
