### ISSUE TITLE
Large regression in android raster times on roll to 7f12e3497428

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#128308]
I suspect the culprit is https://github.com/flutter/engine/pull/42528/files#diff-dff260fd920e7b018971e37036d11916295c2c9614370942f6493f46ec5616d8 , because a change in the raster cache behavior would explain the android only regression.

**Comment by jonahwilliams** [comment]
https://github.com/flutter/engine/compare/f9f72388a4da...7f12e3497428

**Comment by zanderso** [comment]
The benchmark recovered after https://github.com/flutter/engine/pull/42592 rolled into the framework.
