### ISSUE TITLE
flutter_gallery__transition_perf worst_frame_rasterizer_time_millis regression (skia)

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#12839]
The Skia roll in https://github.com/flutter/engine/pull/4265 (rolled into Flutter in https://github.com/flutter/flutter/pull/12687) regressed`flutter_gallery__transition_perf` `worst_frame_rasterizer_time_millis` by more than 2x:

<img width="237" alt="screen shot 2017-10-26 at 3 03 07 pm" src="https://user-images.githubusercontent.com/211513/32079254-d71b9444-ba5e-11e7-982c-3e2cdd0580c1.png">

cc @chinmaygarde @cbracken @jason-simmons

**Comment by jason-simmons** [comment]
This is associated with a change in Skia caching policy:
  https://github.com/google/skia/commit/a2ac30da36c80f616c909c671a240f2d468db124

The average_frame_rasterizer_time_millis is unaffected by the change.  I don't know if the additional work on the worst-case rasterizer frame is new, or if it was always done somewhere but just wasn't being credited to the rasterizer timing.

@bsalomon

**Comment by chinmaygarde** [comment]
Should be fixed by https://github.com/flutter/engine/pull/4327.
