### ISSUE TITLE
Focus or shortcut handling state ends up broken if app window is hidden by a CallbackAction (at least on macOS)

### ISSUE THREAD

**Issue by mwalkerr** [flutter/flutter#128377]
I apologize for not providing the code to reproduce this. Scheduling the window hide asynchronously fixes the issue for me so I'm not blocked by this and not entirely sure it'll actually be considered a bug. Just wanted to open the ticket in case someone else runs into something similar and to give the maintainers a heads up that this may be something to look at.

And for the Googling, I was trying to find related issues by searching "FocusableActionDetector not working" and "FocusableActionDetector stops working", so adding those terms here in case anyone else finds themselves searching the same thing.

### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Add a `FocusableActionDetector` and an action handler for some shortcut
2. Use window_manager to `.hide()` the window in that action handler
3. Show the window again using eg. hotkey_manager
4. The `FocusableActionDetector` shortcuts are no longer registered

To fix
1. Change the window `.hide()` call to happen after some delay (eg. 10ms)
2. Show the window again and confirm the shortcuts still work

### Expected results

Window can be hidden synchronously from an action handler without breaking the focus / shortcut handling state

### Actual results

Shortcuts are no longer recognized by the `FocusableActionDetector`

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Resolving dependencies...
  args 2.4.1 (2.4.2 available)
+ bloc 8.1.2
  collection 1.17.1 (1.17.2 available)
+ flutter_bloc 8.1.3
  http 0.13.6 (1.0.0 available)
  matcher 0.12.15 (0.12.16 available)
  material_color_utilities 0.2.0 (0.5.0 available)
+ nested 1.0.0
+ provider 6.0.5
  source_span 1.9.1 (1.10.0 available)
  test_api 0.5.1 (0.6.0 available)
Changed 4 dependencies!
➜  epte git:(main) ✗ flutter doctor -v
[✓] Flutter (Channel stable, 3.10.1, on macOS 13.2.1 22D68 darwin-x64, locale en-US)
    • Flutter version 3.10.1 on channel stable at /Users/monroe/ws/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (3 weeks ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 73.0.3
    • Dart plugin version 223.8950

[✓] IntelliJ IDEA Community Edition (version 2019.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.63.2)
    • VS Code at /Users/monroe/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.2.1 22D68 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @mwalkerr 
Can you check if [this](https://github.com/flutter/flutter/issues/109912#issuecomment-1222023472) helps in your case ? 

If not, a minimal code sample would help us to properly address the reported behavior.

**Comment by mwalkerr** [comment]
@darshankawar I tried numerous combinations of setting focusNodes, requesting focus with them, recreating them, etc. I ultimately just re-ran `runApp()` and used a UniqueKey() to try to start from a clean slate, but that didn't work either.

I'll try to follow up once I have some time with a minimal reproducible example.

**Comment by mwalkerr** [comment]
After experiencing this again and playing around with it, I've realized this happens when the window is closed before the keyup event is received. When the window comes back, it seems like the FocusableActionDetector is still maintaining some state as if the key is still pressed. I've found that pressing the key again restores the shortcut detection.

**Comment by darshankawar** [comment]
Thanks for the update. Does it mean the issue is workable currently by pressing the key again as mentioned ? Or you think this should be addressed ? If so, a minimal code sample with steps to replicate would be helpful to address it properly.

**Comment by mwalkerr** [comment]
Can you clarify "workable"? Pressing the key again does fix the state and allow other keys to be pressed.

I have an ephemeral UI that's presented when a shortcut is pressed and is dismissed after an option in the UI is selected with "enter". Due to this issue, the next time the UI is shown, the other keypress shortcuts I've configured in the `FocusableActionDetector` aren't working until "enter" is pressed again. For now I'm going to avoid using `FocusableActionDetector` and just handle the shortcuts manually using the raw keyboard listener.

I think this is a valid bug if my use case described above is one that is considered supported by Flutter. Also, I'm using the tool called Karabiner on macOS. It's possible that's part of the issue but I haven't dug deeper to confirm

**Comment by darshankawar** [comment]
Thanks for the feedback @mwalkerr 
Would be good to have a minimal code sample along with steps to replicate so that we can make this issue actionable.
