### ISSUE TITLE
flutter gen-l10n specify l10n.yaml location 

### ISSUE THREAD

**Issue by gkdgo** [flutter/flutter#128393]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

sometimes the l10n.yaml file is not in the root of project, I want to specify the location when run `flutter gen-l10n`

### Proposal

maybe like this 
```
flutter gen-l10n --config=lib/l10n/l10n.yaml
```

**Comment by huycozy** [comment]
Thanks for the report! This is a known issue being tracked at https://github.com/flutter/flutter/issues/55795
Closing this issue as a duplicate, so please follow up on it for further updates.
