### ISSUE TITLE
Using --dart-define when build ios not loaded at first run, only work after hot restart

### ISSUE THREAD

**Issue by thangldvn** [flutter/flutter#128304]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run app in debug mode
2. Check environment variables on --dart--define

### Actual results

Return empty string when get environment variables using String.fromEnvironment(), this environment only shown after hot restart app, 
Currently i am using Flutter 3.7.3
This issue only happen when build app ios, works fine in build app android
Same issue on stackoverflow: https://stackoverflow.com/questions/76349221/flutter-dart-define-not-loading-on-first-build-only-on-hot-restart-for-ios
### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by dam-ease** [comment]
Hi @thangldvn. Thanks for filing this issue. I am unable to reproduce this on both Android and iOS with the latest `stable` version. Kindly confirm this issue on the latest version and also confirm you added the `const` keyword when trying to get environment variables using `String.fromEnvironment()`.

**Comment by thangldvn** [comment]
i have found the issue; that is my project has been removed 2 files: Debug.xcconfig and Release.xcconfig, after i create new files, it was placed in wrong folder (not in ios/Flutter/ Folder). Then i move 2 files in to ios/Flutter/ and now it works fine
