### ISSUE TITLE
FlutterJNI.nativeSpawn SIGSEGV(SEGV_MAPERR) Address Not Mapped To Object

### ISSUE THREAD

**Issue by helixs** [flutter/flutter#128373]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I'm developing an application using Flutter and encountered an error named FlutterJNI.nativeSpawn that contains the following details:
```
pid: 17008 (com.ext.demo), tid: 17008 (com.ext.demo)

Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8
x0 000000790ff55f40 x1 0000007905273c48 x2 0000007905273c30 x3 0000000000000002
x4 0000000000000000 x5 0000000000000000 x6 0000000000000000 x7 0000000000000000
x8 0000000000000000 x9 07cf58f7a948240c x10 0000007aa3f120a8 x11 00000000ffffffff
x12 0000007aa3f135fc x13 0000000456dc5238 x14 0000000456dc5230 x15 0000000000000000
x16 0000007a81d6fa70 x17 0000007a81d5df2c x18 0000007aa4ae2000 x19 0000007fffe61488
x20 0000007fffe613b0 x21 0000007fffe613e0 x22 0000007fffe613f8 x23 000000790ff55f40
x24 0000000000000000 x25 00000078d05940e0 x26 0000007fffe61ef4 x27 000000788f478058
x28 0000000012cfd640 x29 0000000000000000
sp 0000007fffe61250 lr 000000795af923fc pc 000000795af92400

caused by:
SIGSEGV(SEGV_MAPERR) Address Not Mapped To Object

backtrace:
#00 pc 0000000000320400 /data/app/~~92-uRQbtwDL9hO1iwZeGOQ==/com.ext.demo-ZJHIElP-twsi1ssegf5c0w==/lib/arm64/libflutter.so
#01 pc b400007aa401b500

Java Stack:
⇢ main (2) RUNNABLE
io.flutter.embedding.engine.FlutterJNI.nativeSpawn(Native Method)
io.flutter.embedding.engine.FlutterJNI.spawn(FlutterJNI.java:5)
io.flutter.embedding.engine.FlutterEngine.spawn(FlutterEngine.java:3)
io.flutter.embedding.engine.FlutterEngineGroup.createAndRunEngine(FlutterEngineGroup.java:15)
```
SIGSEGV(SEGV_MAPERR) Address Not Mapped To Object
I've tried to investigate this issue by examining logs and debugging it. However, I still couldn't determine the root cause of the problem or how to resolve it.

I suspect that this may be caused by a problem with the native code implementation or how the code is interacting with the Android operating system. I've reviewed the relevant documentation and followed best practices, but the problem persists.

I would appreciate some guidance or solutions from the Flutter community to help me address this issue. Thank you!

Environment:
Flutter Version: 3.3.10
Operating System:Android

Crash probability: not mandatory, sporadic:
Frequent creation and destruction of Flutter engines through FlutterEngineGroup can lead to crashes

### Expected results

normal use

### Actual results

Low probability of occurrence of crashes

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @helixs 
What flutter version are you seeing this crash on ?
In order to properly address the issue, we would atleast need some reproducible code or steps.

**Comment by darshankawar** [comment]
Can you also provide the dart code (ex: main.dart) so that we can try to use both and replicate ?

**Comment by helixs** [comment]
main.dart demo:
```dart
@pragma('vm:entry-point')
void jumpAnyPage(List<String> params) {
  _launchApp();
  AnyPageRouterParser.push(params);
}
void _launchApp() {
  runZonedGuarded<Future<void>>(() async {
    WidgetsFlutterBinding.ensureInitialized();
    var app = MaterialApp.router(
        routeInformationParser: routeInformationParser,
        routerDelegate: routerDelegate);
      runApp(app);

  }, (error, stack) {
 
  });

}
```
I observed that in most cases, the situation is like this: our App's main page MainActivity has 4 tab pages, one of which is created using FlutterFragment. When a new secondary page is opened and the App stays in the background for a long time, after a few hours, when returning to the App and then back to MainActivity, MainActivity is recycled and onCreate is executed again, causing FlutterFragment to execute provideFlutterEngine method again, leading to a crash with a memory address error. Do you know any methods to avoid this problem?

**Comment by helixs** [comment]
I reproduced this issue by setting "Don't keep activities" to "On" in developer mode, which triggered the `onDestroy() `method of `MainActivity` and `FlutterFragment` when returning to `MainActivity`. Then, the `onCreate()` method was executed again. In this extreme case, you want to know if calling` engine.destroy()` and `EngineGroup.createAndRunEngine() `would conflict?
