### ISSUE TITLE
[flutter_tools] null check error looking up HOME directory in package:unified_analytics

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#128343]
On stable/3.10.3

Similar to but distinct from https://github.com/flutter/flutter/issues/127055

```
TypeError: Null check operator used on a null value
at getHomeDirectory(utils.dart:83)
at new Analytics(analytics.dart:113)
at getDefaultAnalytics(globals.dart:97)
at analytics(globals.dart:93)
at _exit(runner.dart:278)
at run.<anonymous closure>.<anonymous closure>(runner.dart:96)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at main(executable.dart:91)
at <asynchronous gap>(async)
```

@eliasyishak I'm guessing this was fixed upstream in https://github.com/dart-lang/tools/commit/389925fcfe79edd682e7547ce6f8d05bd0d786a8#diff-06e4843e1547dbdd0d7aa5d02ca158a065f977e4331187f7ad88506f8cd90696R103 ?

**Comment by eliasyishak** [comment]
Yeah this should be handled now. The previous PR was created to fix issues with permissions on the home directory... and while we were at it, we also handled situations when we were unable to get the home directory from the environment variables.

Both cases will result in the factory returning the NoOp analytics class

**Comment by christopherfujino** [comment]
If that already rolled to the tool's master channel we can close this bug.

**Comment by eliasyishak** [comment]
I think I just traced the dependencys from flutter_tools --> engine --> dart sdk --> dart-lang/tools to this commit https://github.com/dart-lang/tools/tree/d723a55062959713f715ca3f10190a72c79634ef which includes the latest version of `package:unified_analytics` so I think we can close

**Comment by christopherfujino** [comment]
> I think I just traced the dependencys from flutter_tools --> engine --> dart sdk --> dart-lang/tools to this commit https://github.com/dart-lang/tools/tree/d723a55062959713f715ca3f10190a72c79634ef which includes the latest version of `package:unified_analytics` so I think we can close

Thanks!
