### ISSUE TITLE
labeler action is being skipped on flutter/engine

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#128448]
See https://github.com/flutter/engine/actions/workflows/labeler.yml

Does the action need to be installed so it can run?

**Comment by CaseyHillers** [comment]
@godofredoc as an admin, do you know if the action needs any other installation steps so it can run?

**Comment by drewroengoogle** [comment]
@CaseyHillers Does this line need to be changed to flutter/engine?
https://github.com/flutter/engine/blob/main/.github/workflows/labeler.yml#L14

**Comment by CaseyHillers** [comment]
Thanks Drew! I sent https://github.com/flutter/engine/pull/42634
