### ISSUE TITLE
Analyze size returns error

### ISSUE THREAD

**Issue by Silfalion** [flutter/flutter#128402]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

run `flutter build apk -t lib/main_development.dart --flavor development --target-platform android-arm64 --analyze-size`

### Expected results

a breakdown of the app size

### Actual results

_TypeError: Null check operator used on a null value

### Code sample

<details><summary>Code sample</summary>

```dart
There is no dart code since it's for the whole project
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console

Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter build apk -t lib/main_development.dart --flavor development --target-platform android-arm64 --analyze-size -v

## exception

_TypeError: Null check operator used on a null value

```
#0      _ProgramInfoBuilder.createInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:419:75)
#1      _ProgramInfoBuilder.getInfoNodeFor (package:vm_snapshot_analysis/v8_profile.dart:374:14)
#2      ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#3      _ProgramInfoBuilder.build (package:vm_snapshot_analysis/v8_profile.dart:338:16)
#4      toProgramInfo (package:vm_snapshot_analysis/v8_profile.dart:282:8)
#5      _treemapFromSnapshot (package:vm_snapshot_analysis/treemap.dart:158:27)
#6      treemapFromJson (package:vm_snapshot_analysis/treemap.dart:85:5)
#7      SizeAnalyzer.analyzeZipSizeAndAotSnapshot (package:flutter_tools/src/base/analyze_size.dart:123:59)
#8      AndroidGradleBuilder._performCodeSizeAnalysis (package:flutter_tools/src/android/gradle.dart:567:60)
#9      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:548:15)
<asynchronous suspension>
#10     AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:208:5)
<asynchronous suspension>
#11     BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:116:5)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
<asynchronous suspension>
#18     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#20     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, 3.10.3, on Linux Mint 21.1
    5.15.0-73-generic, locale en_US.UTF-8)
    [32m•[39m Flutter version 3.10.3 on channel stable at
      /home/sil/development/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision f92f44110e (5 days ago), 2023-06-01 18:17:33
      -0500
    [32m•[39m Engine revision 2a3401c9bb
    [32m•[39m Dart version 3.0.3
    [32m•[39m DevTools version 2.23.1

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK
    version 33.0.1)
    [32m•[39m Android SDK at /home/sil/Android/Sdk
    [32m•[39m Platform android-33-ext4, build-tools 33.0.1
    [32m•[39m Java binary at:
      /opt/android-studio-2022.2.1/android-studio/jbr/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at google-chrome

[32m[✓][39m Linux toolchain - develop for Linux desktop
    [32m•[39m Ubuntu clang version 14.0.0-1ubuntu1
    [32m•[39m cmake version 3.22.1
    [32m•[39m ninja version 1.11.1.git.kitware.jobserver-1
    [32m•[39m pkg-config version 0.29.2

[32m[✓][39m Android Studio (version 2022.2)
    [32m•[39m Android Studio at /opt/android-studio-2022.2.1/android-studio
    [32m•[39m Flutter plugin version 73.0.2
    [32m•[39m Dart plugin version 222.4582
    [32m•[39m Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[32m[✓][39m Android Studio
    [32m•[39m Android Studio at /opt/android-studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[32m[✓][39m VS Code (version 1.78.2)
    [32m•[39m VS Code at /usr/share/code
    [32m•[39m Flutter extension version 3.64.0

[32m[✓][39m Connected device (2 available)
    [32m•[39m Linux (desktop) • linux  • linux-x64      • Linux Mint 21.1
      5.15.0-73-generic
    [32m•[39m Chrome (web)    • chrome • web-javascript • Google Chrome
      114.0.5735.90

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!
```


```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[32m[✓][39m Flutter (Channel stable, 3.10.3, on Linux Mint 21.1
    5.15.0-73-generic, locale en_US.UTF-8)
    [32m•[39m Flutter version 3.10.3 on channel stable at
      /home/sil/development/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision f92f44110e (5 days ago), 2023-06-01 18:17:33
      -0500
    [32m•[39m Engine revision 2a3401c9bb
    [32m•[39m Dart version 3.0.3
    [32m•[39m DevTools version 2.23.1

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK
    version 33.0.1)
    [32m•[39m Android SDK at /home/sil/Android/Sdk
    [32m•[39m Platform android-33-ext4, build-tools 33.0.1
    [32m•[39m Java binary at:
      /opt/android-studio-2022.2.1/android-studio/jbr/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at google-chrome

[32m[✓][39m Linux toolchain - develop for Linux desktop
    [32m•[39m Ubuntu clang version 14.0.0-1ubuntu1
    [32m•[39m cmake version 3.22.1
    [32m•[39m ninja version 1.11.1.git.kitware.jobserver-1
    [32m•[39m pkg-config version 0.29.2

[32m[✓][39m Android Studio (version 2022.2)
    [32m•[39m Android Studio at /opt/android-studio-2022.2.1/android-studio
    [32m•[39m Flutter plugin version 73.0.2
    [32m•[39m Dart plugin version 222.4582
    [32m•[39m Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[32m[✓][39m Android Studio
    [32m•[39m Android Studio at /opt/android-studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[32m[✓][39m VS Code (version 1.78.2)
    [32m•[39m VS Code at /usr/share/code
    [32m•[39m Flutter extension version 3.64.0

[32m[✓][39m Connected device (2 available)
    [32m•[39m Linux (desktop) • linux  • linux-x64      • Linux Mint 21.1
      5.15.0-73-generic
    [32m•[39m Chrome (web)    • chrome • web-javascript • Google Chrome
      114.0.5735.90

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!
```

</details>

**Comment by darshankawar** [comment]
I tried to replicate it using a sample flavors app and without flavors app as well, but I was unable to see the reported error. The command ran properly and generated expected result as below:

```
  assets/
    flutter_assets                                                        198 KB
  AndroidManifest.xml                                                       1 KB
  res/
    CG.png                                                                  1 KB
  resources.arsc                                                           65 KB
  kotlin/
    collections                                                             1 KB
    kotlin.kotlin_builtins                                                  4 KB
    reflect                                                                 1 KB
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
A summary of your APK analysis can be found at: /Users/dhs/.flutter-devtools/apk-code-size-analysis_01.json

```

Based on the report and error, I'll keep the issue open for tracking.

**Comment by Silfalion** [comment]
Thank you so much for taking the time to look into it. Considering your test, this may be due to a package? Using quite a few of them:

**Comment by mkustermann** [comment]
Closing this issue - as I believe the https://github.com/dart-lang/sdk/commit/766a2be5a4d6b08da89eea0a6030cbc566735fad should've fixed this and that fix is available in flutter's `master` channel now.

@Silfalion If you still run into the issue please re-open.
