### ISSUE TITLE
[web] Canvaskit doesn't support WOFF2 fonts (was: flutter web 3.10 font size extra large)

### ISSUE THREAD

**Issue by xyun52** [flutter/flutter#128485]
*.Woff is still supported in 3.7, but not in 3.10. After Woff compression, it is only 1.5M, but *.OTF is 7.4M

![微信截图_20230608135706](https://github.com/flutter/flutter/assets/5417624/0ed11c3c-1729-452d-8a5f-119ede2f3a55)

**Comment by dam-ease** [comment]
Hi @xyun52.
Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by xyun52** [comment]
As long as Chinese is displayed, the font 'notasanssc' will be automatically loaded

![image](https://github.com/flutter/flutter/assets/5417624/a96fb6f1-32fc-457b-b680-3b3f2395d966)

**Comment by huycozy** [comment]
Hi @xyun52 
I can see this issue when typing Chinese on simple TextField. But it also appears on the latest Flutter master channel and `3.7.12`. The font size is ~7.4 MB (the [loaded font url](https://fonts.gstatic.com/s/notosanssc/v26/k3kXo84MPvpLmixcA63oeALhL4iJ-Q7m8w.otf)).

>*.Woff is still supported in 3.7, but not in 3.10. After Woff compression, it is only 1.5M, but *.OTF is 7.4M

I'm not quite clear about this. Can you please be more specific? Which Flutter `3.7.x` version is not affected?

**Comment by xyun52** [comment]
![微信截图_20230612101721](https://github.com/flutter/flutter/assets/5417624/6f03f3cf-1574-4d1e-81a8-56ce8e87e780)

![3 10](https://github.com/flutter/flutter/assets/5417624/872fc9af-54d3-4735-b8c9-235760f8279e)

[demos.zip](https://github.com/flutter/flutter/files/11716931/demos.zip)

**Comment by huycozy** [comment]
Thanks for your response. But when I run your sample code above on Flutter 3.10.4, it seems to be loaded:

<details>
<summary>Demo</summary>

<img width="600" src="https://github.com/flutter/flutter/assets/104349824/1158fadb-5860-46b5-b920-629beba11728">
</details>

Checking this with Flutter 3.7.5, the font is loaded with same size as well. 

However, I notice there is a message from the output console:

```console
Failed to load font NSC at assets/fonts/noto-sans-sc-regular.woff2
Verify that assets/fonts/noto-sans-sc-regular.woff2 contains a valid font.
```

Do you see the same?

**Comment by xyun52** [comment]
So how to make it effective

**Comment by huycozy** [comment]
@xyun52 It seems the message at https://github.com/flutter/flutter/issues/128485#issuecomment-1586616116 is an intended output message with `woff2` font, please see [Supported font formats](https://docs.flutter.dev/cookbook/design/fonts#supported-font-formats) and proposal for it at https://github.com/flutter/flutter/issues/109108.

Regarding the original issue about large `otf` font, I also checked again this on Flutter 3.7.5 and noticed that "external" `otf` **(*)** font is not fetched when the page loaded. Meanwhile, I can see that "external" font is fetched when running on latest stable and master channel.

#### Flutter 3.7.5: 

- MaterialIcons-Regular.otf (1.6MB)

#### Flutter 3.10.4:

- MaterialIcons-Regular.otf (1.6MB)
- k3kXo84MPvpLmixcA63oeALhL4iJ-Q7m8w.otf (7.4 MB) **(*)**

Labeling the issue for more insights.

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.10.4, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.10.4 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 682aa387cf (2 days ago), 2023-06-05 18:04:56 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 964AY0WL20 • android-arm64  • Android 12 (API 32)
    • macOS (desktop)   • macos      • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 114.0.5735.106

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.12.0-3.0.pre.66, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.12.0-3.0.pre.66 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2b1f882e20 (3 hours ago), 2023-06-11 19:40:28 -0400
    • Engine revision 9bb0a59074
    • Dart version 3.1.0 (build 3.1.0-196.0.dev)
    • DevTools version 2.24.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 964AY0WL20 • android-arm64  • Android 12 (API 32)
    • macOS (desktop)   • macos      • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 114.0.5735.106

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by HeinrichJanzing** [comment]
Similarly to @xyun52, we too included the Noto Sans font for simplified chinese as an asset, in woff2, to avoid dependency on the google fonts API and to reduce the download size.

In line with what @huycozy describes in [his preceding comment](https://github.com/flutter/flutter/issues/128485#issuecomment-1587193925), the woff2 file from our assets is always downloaded. 
- In Flutter 3.7 and below, it is effectively used by the app and the font fallback mechanism is not triggered (no font downloads from google CDN).
- In Flutter 3.10 and above, we see the same error message. There's an additional download from the google fonts CDN of a cryptically named otf file.

While it was maybe not officially supported, it seems Flutter web _was_ able to use woff2 asset font files before 3.10? From [the relevant docs ](https://docs.flutter.dev/cookbook/design/fonts#supported-font-formats):

> Flutter does not support .woff and .woff2 fonts for all platforms.

I interpreted that as _"Depending on your platform, it may or may not work."_  If the intention is/was to say it should not be used anywhere, I would have expected something like:

> Flutter does not support .woff and .woff2 fonts for any platform.

**Comment by ditman** [comment]
During this week's triage we talked about this; and suspect this is the problem:

* At some point between 3.7 and 3.10, we must have removed support for `brotli` (de)compression from our custom `canvaskit.wasm` build.
* Client-side `brotli` (de)compression seems to be required for `canvaskit` to be able to use `woff2` fonts.

We're currently looking into how to add `woff2` (`brotli`?) support back.

In the meantime, @HeinrichJanzing, @xyun52, could you please **convert your WOFF2 font assets to WOFF?** WOFF should be supported, and in our (limited) testing it "only" incurs a ~0.3x penalty in font file size (instead of the 5x that's reported in this issue).

Apologies for the breakage!

**Comment by HeinrichJanzing** [comment]
@ditman I have tested plain `woff` and that does still seem to work in 3.10, adding about 25% to the size in our case. 

That gives us an acceptable workaround for the time being - thanks! Good to hear this will be fixed, too.

**Comment by ditman** [comment]
Thanks for confirming that the workaround works! We'll keep you posted with regards to woff2 fonts (I'm going to tweak the title of this issue so it's easier to find!

**Comment by xyun52** [comment]
@ditman Have you made any progress

**Comment by harryterkelsen** [comment]
Unassigning for now because I don't plan on working on this in the near future. We could add brotli support back into CanvasKit for woff2 fonts, but it would come at the cost of increasing the code size of CanvasKit for everyone, regardless of if their app uses woff2 or not. We have plans to be able to defer load WASM modules at runtime for cases like this (i.e. load brotli/woff2 support when a woff2 font is loaded at runtime) to ameliorate this, but it would be a more substantial change.

**Comment by Mr-Pepe** [comment]
It seems the Flutter team changed their mind? 

See https://github.com/flutter/engine/pull/55908

**Comment by mdebbar** [comment]
Fixed in https://github.com/flutter/engine/pull/55908
