### ISSUE TITLE
Android engine v2 recipes are not uploading the size treemaps

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#128482]
For example in step 27 of https://ci.chromium.org/ui/p/flutter/builders/staging/Linux%20Android%20AOT%20Engine/705/overview, the engine v1 recipe generates and uploads the size treemap.

But there is no equivalent step in the engine v2 recipe:

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Production%20Engine%20Drone/198545/overview

This data is needed to diagnose and fix Engine binary size regressions.

cc @godofredoc

**Comment by zanderso** [comment]
https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/engine/engine.py#329

**Comment by zanderso** [comment]
Assigned to @godofredoc based on feedback on https://github.com/flutter/engine/pull/42663. Feel free to assign back to me if/when the needed engine v2 functionality is available.

**Comment by godofredoc** [comment]
Support for magic env variables has landed https://github.com/flutter/flutter/issues/128585
