### ISSUE TITLE
Using uncommon file extensions for flutter-internal files risks customer web servers refusing to serve them

### ISSUE THREAD

**Issue by andrewkolos** [flutter/flutter#128456]
## Background

Within the build output of any flutter app, there exists a unique file, the asset manifest (currently named `AssetManifest.smcbin`). This file contains metadata about assets that are available to the app at runtime. In particular, it provides the framework a cross-platform means to discover [higher-resolution variants of image assets](https://docs.flutter.dev/ui/assets-and-images#resolution-aware).

https://github.com/flutter/flutter/pull/122505 changed the extension and underlying format of the file. Before this, it was JSON (`AssetManifest.json`). This changed the file to be a serialized binary object (`AssetManifest.bin`, encoded using [StandardMessageCodec](https://api.flutter.dev/flutter/services/StandardMessageCodec-class.html)). A [follow-up hotfix](https://github.com/flutter/flutter/pull/126837) changed the filename again to `AssetManifest.smcbin`, which is the current name as of writing.

## Issue

Ideally, changing the extension (or any other aspect) of `AssetManifest.smcbin` should not impact customers, as this file is a framework-internal implementation detail. However, customers deploying flutter web apps have been impacted with vague, frustrating issues. Here are known examples, with some affecting several customers:

* https://github.com/flutter/flutter/issues/124883
  * This is what prompted the change from `AssetManifest.bin` to `AssetManifest.smcbin`, which may have been a mistake in hindsight. See the following issues in this list.
* https://github.com/flutter/flutter/issues/128230
  * By default, some (most?) production IIS web servers are configured to not serve files for which it does not recognize the extension. Clients requesting these files will get a vague 404 response.
* https://github.com/flutter/flutter/issues/127038
  * Similar to the previous issue. To my knowledge, the web server did not know what to use for the `content-type` header, so it wouldn't serve the file.

The main purpose of this issue is to document this (to be added as a code comment) and raise awareness of this issue, as it could be a problem for other features that rely on requesting files with uncommon extensions (hopefully none).

**Takeaway questions:** is there a way for us to improve this situation for customers? Is there some sort of way to, in the build output, hint to web servers that this file is safe to serve to clients? Can we make these type of issues easier to catch and debug? Is there some other , well-known, file extension we could use that would be safer (such as `.bin`, at the risk of reintroducing #124883).

**Comment by christopherfujino** [comment]
Regarding https://github.com/flutter/flutter/issues/124883, do we know what heuristic IDM is using to block the file? If it's just the extension name we could name this file anything, like .txt right?

**Comment by andrewkolos** [comment]
> Regarding #124883, do we know what heuristic IDM is using to block the file? If it's just the extension name we could name this file anything, like .txt right?

The exact reason for why IDM was doing this is unclear. However, changing the file extension away from `.bin` was sufficient to address this issue, which is why we chose to do it (the risk of doing this was unknown at the time). The file extension doesn't matter to the flutter framework, so, as far as it's concerned, we can rename the file to be anything, even something inaccurate like `.txt` (though this may risk a web server serving this with an incorrect `content-type` header--not sure how much it matters).

**Comment by christopherfujino** [comment]
> even something inaccurate like `.txt` (though this may risk a web server serving this with an incorrect `content-type` header--not sure how much it matters).

Since this file is an implementation detail of the framework, I wouldn't think of this in terms of "accurate" vs "inaccurate", all that matters is that we download and read the correct filename string.

**Comment by eyebrowsoffire** [comment]
> > even something inaccurate like `.txt` (though this may risk a web server serving this with an incorrect `content-type` header--not sure how much it matters).
> 
> Since this file is an implementation detail of the framework, I wouldn't think of this in terms of "accurate" vs "inaccurate", all that matters is that we download and read the correct filename string.
> 
> I say this from the perspective of Flutter. It would be great if we could verify any future changes with IIS.

It's not always as simple as that, due to CORS restrictions and such. Often web servers have special treatment of HTTP headers based on the content type that they have inferred, and that can sometimes affect the way the scripts on the page can actually access these resources. In this case, it's likely that this file will always be same-origin, which means that most of the time this won't be a problem, but serving a resource with an incorrect content type can sometimes have surprising results.

**Comment by eyebrowsoffire** [comment]
> > Often web servers have special treatment of HTTP headers based on the content type that they have inferred
> 
> You mean inferred based on file extension, or contents?
It's common for web servers to choose content type solely based off of file extension, and choose their HTTP header behavior based off of the content type.

> > can sometimes affect the way the scripts on the page can actually access these resources
> 
> like not being able to read the raw bytes?
Yes, the browser blocks you from reading the HTTP response if the CORS requirements aren't met. Again, I'm not sure if that specifically is likely to happen here, but in general the extension type of a file can definitely be a signal to the web server to change its behavior, so I think we should try to be reasonably accurate with our file extensions to be as compatible as possible with standard web servers.

**Comment by yjbanov** [comment]
I think the constraint is that we do not control the server. We should design it in a way that works with existing website hosting servers.

**Comment by yjbanov** [comment]
@andrewkolos Feel free to assign a priority for this one. I'm not sure how to prioritize it myself.

**Comment by andrewkolos** [comment]
There's been some good discussion of this issue here and on the #hackers-web Discord channel (6/8/23).

My plan is to revert the hotfix that renamed`AssetManifest.smcbin` to `AssetManifest.bin`, closing #128230 and reopening #124883. `.bin` is a file extension that is appropriate while also being more commonly recognized by software.

In the future (e.g. next minor version), we could change how the asset manifest works for flutter web specifically. For example, we could directly embed the contents of the asset manifest into the web entrypoint, or, if we continue to have problems with the binary format, we could generate a second JSON version of the asset manifest and have flutter web use that instead.
