### ISSUE TITLE
[tool_crash] StateError: Bad state: Future already completed

### ISSUE THREAD

**Issue by zrwander** [flutter/flutter#128488]
## Command
```
flutter --no-color attach --machine --device-id=YSE0222218000999 lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: Future already completed
```
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:35:31)
#1      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:324:17)
<asynchronous suspension>
```
```
[!] Flutter (Channel unknown, 3.3.5, on macOS 13.1 22C5050e darwin-x64, locale zh-Hans-CN)
    ! Flutter version 3.3.5 on channel unknown at /Users/klook/flutter
    ! Upstream repository unknown
    • Framework revision d9111f6402 (8 months ago), 2022-10-19 12:27:13 -0700
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/klook/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • ABR AL00 (mobile) • YSE0222218000999 • android-arm64  • Android 12 (API 31)
    • macOS (desktop)   • macos            • darwin-x64     • macOS 13.1 22C5050e darwin-x64
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 114.0.5735.106

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: module
**Version**: 6.43.0-RC12
**Material**: true
**Android X**: true
**Module**: true
**Plugin**: false
**Android package**: com.klook.klook_app_flutter
**iOS bundle identifier**: com.klook.klookAppFlutter
**Creation channel**: stable
**Creation framework version**: 20e59316b8b8474554b38493b8ca888794b0234a
### Plugins
astronomia
auto_orientation-2.2.1
cable_flutter
cloud_firestore_web-3.0.2
connectivity_plus-2.3.6+1
connectivity_plus_linux-1.3.1
connectivity_plus_macos-1.2.4
connectivity_plus_web-1.2.3
connectivity_plus_windows-1.2.2
datadome_flutter_dio-1.2.0
device_info_plus-8.1.0
firebase_core-2.1.0
firebase_core_web-2.0.0
firebase_crashlytics-3.0.2
flutter_keyboard_visibility-5.4.0
flutter_keyboard_visibility_linux-1.0.0
flutter_keyboard_visibility_macos-1.0.0
flutter_keyboard_visibility_web-2.0.0
flutter_keyboard_visibility_windows-1.0.0
flutter_native_image-0.0.6+1
flutter_native_timezone
flutter_plugin_android_lifecycle-2.0.8
flutter_sim_country_code-0.1.1
fluttertoast-8.1.1
geetest
http_proxy-a0a5195e929c22f54f26a42731801dbfefa4220f
image_gallery_saver-1.7.1
image_picker-0.8.6+4
image_picker_android-0.8.5+7
image_picker_for_web-2.1.11
image_picker_ios-0.8.7
thaw-37fd5c428ac0f18882643376b26f26bdbbedac2d
marketkit_flutter
modal_progress_hud_nsn-0.3.0
package_info_plus-3.0.3
path_provider-2.0.11
path_provider_android-2.0.21
path_provider_ios-2.0.8
path_provider_linux-2.1.2
path_provider_macos-2.0.0
path_provider_windows-2.1.4
permission_handler-9.2.0
permission_handler_android-9.0.2
permission_handler_apple-9.0.2
permission_handler_windows-0.1.0
screen_refresh_rate
shared_preferences-2.0.7
shared_preferences_linux-2.0.0
shared_preferences_macos-2.0.0
shared_preferences_web-2.0.0
shared_preferences_windows-2.0.0
smart_auth-1.0.8
sqflite-2.0.0+3
url_launcher-6.1.0
url_launcher_android-6.0.15
url_launcher_ios-6.0.15
url_launcher_linux-2.0.0
url_launcher_macos-2.0.0
url_launcher_web-2.0.0
url_launcher_windows-2.0.0
video_player-2.5.2
video_player_android-2.3.11
video_player_avfoundation-2.3.0
video_player_web-2.0.7
volume_control-0.1.5
wakelock-0.6.1+1
wakelock_macos-0.4.0
wakelock_web-0.4.0
webview_flutter-3.0.4
webview_flutter_android-2.8.14
webview_flutter_wkwebview-2.7.5

**Comment by dam-ease** [comment]
Hi @zrwander. Can you please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so that we may verify this?

Also, can you try upgrading to the latest flutter stable version to confirm if this issue still persists?

Thank you!
