### ISSUE TITLE
[google_maps_flutter] [android] ghost marker will be appeared > version 2.2.6

### ISSUE THREAD

**Issue by derjohng** [flutter/flutter#128420]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

google_maps_flutter 2.2.8~2.3.0 will cause ghost markers as below screen record. 
The yellow markers are all same MarkerId. That should show only one yellow circle marker.

After rollback to  google_maps_flutter: 2.2.6, the issue will be gone.

### Expected results

no ghost markers

### Actual results

cause ghost markers

### Code sample

<details><summary>Code sample</summary>

```dart

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/1803036/ea719e11-e747-498a-bd2e-8b195d802907

</details>

### Logs

<details><summary>Logs</summary>

```console
No Log
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.3, on macOS 13.3.1 22E772610a darwin-x64, locale zh-Hant-TW)
    • Flutter version 3.10.3 on channel stable at /Users/derjohng/Projects/FlutterBin
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f92f44110e (6 days ago), 2023-06-01 18:17:33 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1
```

</details>

**Comment by huycozy** [comment]
Thanks for the report! This is a known issue being tracked at https://github.com/flutter/flutter/issues/128042.

Closing this issue as a duplicate, so please follow up on it for further updates.
