### ISSUE TITLE
How to constrain the slider thumb so its' left and right corners stay inside the track?

### ISSUE THREAD

**Issue by gidrokolbaska** [flutter/flutter#128418]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

no steps

### Actual results

currently, there is no possibility to keep the thumb inside the track. I know we can always create custom Slider. I've copied all the slider code, but just can't seem to understand what should I change so the thumb actually stays inside the track

### Logs

n/a

### Flutter Doctor output

n/a

**Comment by TahaTesser** [comment]
Hi @gidrokolbaska 
This is relatively complex to attempt in the current implementation. I've plans to improve Slider, this will be addressed in the improvements.

**Comment by Piinks** [comment]
> Nvm, I’ve figured it out with an extremely dirty workaround which works for my case:D

So glad you were able to find a workaround, I am going to close this issue then. @TahaTesser can you post the tracking issue for the main slider update? Thanks!

**Comment by TahaTesser** [comment]
> > Nvm, I’ve figured it out with an extremely dirty workaround which works for my case:D
> 
> So glad you were able to find a workaround, I am going to close this issue then. @TahaTesser can you post the tracking issue for the main slider update? Thanks!

Ohh good idea, here it is https://github.com/flutter/flutter/issues/125329
