### ISSUE TITLE
[CP] Do not try to load main/default asset image if only higher-res variants exist

### ISSUE THREAD

**Issue by andrewkolos** [flutter/flutter#128450]
### Issue Link

https://github.com/flutter/flutter/issues/127090

### Commit Hash

759ebef

### Target

stable

### PR Link

https://github.com/flutter/flutter/pull/128449

### Changelog Description

Restores the ability to define an asset that _only_ has resolution-aware variants.

### Impacted Users

all Flutter devs

### Impact Description

Impacts the shipping production app. Customer apps on running on devices with low pixel densities may not be able to display assets.

### Workaround

Yes. The user can still declare the resolution-aware variants explicitly in pubspec.yaml. They can also add the parent directory as an entry in pubspec.yaml.

### Risk

low

### Test Coverage

yes

### Validation Steps

The original issue has a repro that can be tested with a low DPR device (like an iPhone 3 SE)

**Comment by andrewkolos** [comment]
cc @jonahwilliams

**Comment by jonahwilliams** [comment]
CP LGTM
