### ISSUE TITLE
Enable catch for exception returned from underline Flutter

### ISSUE THREAD

**Issue by jdevp** [flutter/flutter#128415]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I'm using `source: ImageSource.gallery` for users to select images, in which case users can accidentally select video files instead of images. If that happens, Flutter will return the following exception but it is not catchable by the Image Picker package. Therefore, my app will try to load invalid data and crashes. Please add a function to catch whatever error raised by Flutter in the package so the app will know if a valid image data is loaded.

`D/skia    (28235): --- Failed to create image decoder with message 'unimplemented'`

I posted the same question here.

https://stackoverflow.com/questions/76419277/in-flutter-how-do-i-check-that-an-image-returns-from-image-picker-is-valid?noredirect=1#comment134757812_76419277

### Proposal

Modify the package so that the exception from underline Flutter will be caught at package level.

**Comment by dam-ease** [comment]
Hi @jdevp. ImagePicker package is such that you can see only images using `source: ImageSource.gallery` and won't show other file types. You can check using the example in the package doc: https://pub.dev/packages/image_picker/example.

In case this doesn't describe your use case, kindly help provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that produces this issue.

**Comment by jdevp** [comment]
@dam-ease You are correct. However, under `source: ImageSource.gallery` , you can have images and video files as well. If your Flutter widget is expected to receive images but users choose a video file, then your app is going to crash. Currently, there is way to tell images apart from video files.  My workaround for now is based on the file's suffix but that's not the correct way.

**Comment by danagbemava-nc** [comment]
Hi @jdevp, what version of `image_picker` are you using? It seems like this was supposed to have been fixed with https://github.com/flutter/plugins/pull/2293

**Comment by jdevp** [comment]
I'm using the following. I'll try with the latest version.
image_picker: ^0.8.6+3
    On Monday, July 3, 2023 at 03:53:30 AM EDT, Daniel Agbemava ***@***.***> wrote:  
 
 


Hi @jdevp, what version of image_picker are you using? It seems like this was supposed to have been fixed with flutter/plugins#2293

**Comment by danagbemava-nc** [comment]
Please provide a small reproducible code sample if you still reproduce it in the latest version. 

Thank you
