### ISSUE TITLE
Create camera plugin supporting live preview

### ISSUE THREAD

**Issue by mravn-google** [flutter/flutter#12849]
Use new texture support (#2319) to create and publish a Flutter plugin for interacting with the device camera, including live preview.

**Comment by netdur** [comment]
Thank you very much

**Comment by franzsilva** [comment]
Awesome!!!!

**Comment by MichaelSowah** [comment]
any updates on this

**Comment by sigurdm** [comment]
I have a plugin almost working. It needs some polishing, and a fix needs to go into engine.
I hope to publish a v. 0.0.1 this week.

**Comment by sigurdm** [comment]
It won't happen before after New Year - but a fix has gone into engine (https://github.com/flutter/engine/commit/eee4a1ed821e98922476f2ce0b1e99ce1a606704) (not rolled yet).
The current plugin is at https://github.com/sigurdm/camera if you are curious.
It still needs some polish before publishing it on pub.

**Comment by MichaelSowah** [comment]
@sigurdm is the engine fix likely to roll soon and has it landed on master yet?

**Comment by MichaelSowah** [comment]
@sigurdm any updates? Happy New Year

**Comment by sigurdm** [comment]
When https://github.com/flutter/flutter/pull/13871 lands on master, it will include the engine fix.

**Comment by sigurdm** [comment]
And happy new year!

**Comment by MichaelSowah** [comment]
if you don't mind me asking...will it be anytime soon?

**Comment by sigurdm** [comment]
The engine fix has finally landed!
I hope to publish a first 0.0.1 version of the camera plugin soonish

**Comment by MichaelSowah** [comment]
great, I can't wait

**Comment by sigurdm** [comment]
... and we're online: https://pub.dartlang.org/packages/camera

**Comment by mravn-google** [comment]
Woot!

**Comment by MichaelSowah** [comment]
I just tried it and got these errors Initializing gradle...                                0.9s
Resolving dependencies...                             2.1s
Running 'gradlew assembleDebug'...
Configuration 'debugCompile' in project ':app' is deprecated. Use 'debugImplementation' instead.
Configuration 'profileCompile' in project ':app' is deprecated. Use 'profileImplementation' instead.
Configuration 'releaseCompile' in project ':app' is deprecated. Use 'releaseImplementation' instead.
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
Configuration 'androidTestCompile' in project ':app' is deprecated. Use 'androidTestImplementation' instead.
Configuration 'debugProvided' in project ':camera' is deprecated. Use 'debugCompileOnly' instead.
Configuration 'releaseProvided' in project ':camera' is deprecated. Use 'releaseCompileOnly' instead.
Configuration 'debugProvided' in project ':path_provider' is deprecated. Use 'debugCompileOnly' instead.
Configuration 'releaseProvided' in project ':path_provider' is deprecated. Use 'releaseCompileOnly' instead.
C:\Users\MichaelSowah\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\camera-0.0.1\android\src\main\java\io\flutter\camera\CameraPlugin.java:251: error: cannot find symbol
      implements PluginRegistry.RequestPermissionsResultListener {
                               ^
  symbol:   class RequestPermissionsResultListener
  location: interface PluginRegistry
C:\Users\MichaelSowah\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\camera-0.0.1\android\src\main\java\io\flutter\camera\CameraPlugin.java:73: error: cannot find symbol
    registrar.addRequestPermissionsResultListener(new CameraRequestPermissionsListener());
             ^
  symbol:   method addRequestPermissionsResultListener(CameraPlugin.CameraRequestPermissionsListener)
  location: variable registrar of type Registrar
C:\Users\MichaelSowah\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\camera-0.0.1\android\src\main\java\io\flutter\camera\CameraPlugin.java:252: error: method does not override or implement a method from a supertype
    @Override
    ^
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':camera:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Gradle build failed: 1

**Comment by MichaelSowah** [comment]
am on alpha

**Comment by MichaelSowah** [comment]
camera preview does not show, I just run the example in the plugin

**Comment by franzsilva** [comment]
Maybe Switching to master might work. because probably its a new feature on the engine that allows this. Im going to test it on a new flutter project using Flutter on master branch

**Comment by franzsilva** [comment]
Ok tested it out, Just wanted to add a couple of comments. 

Tested on Master, Works Beautiful. The only problem is that with a newly created project the android/app/build.gradle. the minSdkVersion is placed as 16. and the plugin is configured to have a minimum version of 21, so when i changed it to 21 it worked like a charm. Not sure if its meant to be minimum 21.

**Comment by mravn-google** [comment]
Our project templates have minSdkVersion 16, because that is what Flutter itself requires. Any plugin you use may declare a larger number than that, and your app must declare have at least the max of those numbers.

**Comment by MichaelSowah** [comment]
true works beautifully...now my can come into production. I am also interested in this https://github.com/flutter/flutter/issues/13846 and possibly build one but would love to do it with some one

**Comment by MichaelSowah** [comment]
Configuration 'androidTestCompile' in project ':app' is deprecated. Use 'androidTestImplementation' instead. that I keep seeing anytime I run the app

**Comment by mravn-google** [comment]
Does your android/app/build.gradle use androidTestCompile? If so, just replace with androidTestImplementation. The deprecation comes with the 3.x version of the Android Studio Gradle plugin compared to 2.x.

**Comment by mravn-google** [comment]
Done. Closing.

**Comment by MichaelSowah** [comment]
@mravn-google thanks

**Comment by rubencg195** [comment]
@mravn-google @MichaelSowah  can I use more than one camera instance or texture component with live preview?. It is for a Google Cardboard/AR Application.

**Comment by sigurdm** [comment]
Hi @rubencg195 - you can use several texture components simultaneously. (For example showing several videos)
I don't think any of Android or iOS supports opening several cameras at the same time, nothing in the flutter plugin limits it - but you will probably get an error from the system.
More details:
https://stackoverflow.com/questions/30100273/is-it-possible-to-open-front-and-back-cameras-at-the-same-time-in-camera2
https://stackoverflow.com/questions/31586266/how-to-record-video-of-front-and-back-camera-at-a-time-in-ios.

**Comment by rubencg195** [comment]
Thank you for your help @sgraham, would it be possible to access the back camera raw data and show it in two different textures or web-gl textures?.

**Comment by sigurdm** [comment]
Yes. Using the camera plugin you can get a `CameraController` instance representing e.g. the back camera. You can insert any number of "new CameraPreview(controller)" widgets in your app, they will all show the same preview.
There is no way currently to manipulate the raw data of the camera preview inside dart.

**Comment by rubencg195** [comment]
Thank you very much @sigurdm this is whay I want to do, I will try to do it with Flutter. I attach below some of the results with react-native-camera.

### Expected behaviour
Having two instances of the camara controller.

![image](https://user-images.githubusercontent.com/25628940/36954074-154ae580-1fe5-11e8-906b-9309a1328f86.png)


### Actual behaviour
When creating two camera instances, one is black.

![image](https://user-images.githubusercontent.com/25628940/36954057-ee4035c6-1fe4-11e8-86e1-23a555f247b5.png)

![image](https://user-images.githubusercontent.com/25628940/36954509-287a48aa-1fe8-11e8-95c6-ccdfb6ca0c35.png)

**Comment by sigurdm** [comment]
You seem to be using react native and not Flutter? :)
https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md
If that's the case, I'm afraid I cannot help you out.

**Comment by rubencg195** [comment]
Yes, I just wanted to show you the error I had in RN, and what I plan to do in Flutter.

**Comment by ayomide101** [comment]
Is there anyway to retrieve the camera byte data while it's being previewed? Can't seem to find an implementation that supports such

**Comment by arloan** [comment]
Need instance preview frame data also, taking shot into a image file is too much time consuming for many scenarios. I'm still not able to find a solution yet.

**Comment by hariprasadiit** [comment]
camera plugin uses classes introduced in `iOS 10`, so live preview is not working on versions below that
any chance that live preview will be made available for `iOS 9.3`?

**Comment by zoechi** [comment]
This issue is long closed. Please create new issues for additional feature requests.
