### ISSUE TITLE
Use OpenCV for the camera plugin

### ISSUE THREAD

**Issue by Levi-Lesches** [flutter/flutter#128495]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Hello Flutter team, 

I was trying to migrate my OpenCV camera code from Python's `cv2` to Dart, but found there wasn't any established way to do that yet. I'd really like to port our code from Python to a compiled language because we were getting more runtime errors than I care to debug, and our program's performance wasn't great either. So, I wrote bindings for OpenCV in Dart.

### Proposal

I decided to use `dart:ffi` to integrate OpenCV into Dart myself. Along the way, I realized that OpenCV is written in C++, and ffi only supports C, but I worked it out: 
- I wrote a C-compatible "wrapper" API around the object-oriented parts of OpenCV. For example, instead of 
```cpp
// Instead of this object-oriented code...
cv::VideoCapture cap(0);
cap.read()
// ...you use a C-style wrapper API
VideoCapture* cap = VideoCapture_getByIndex(0);
VideoCapture_read(cap);
```
- Next, I compiled that wrapper into a `.dll`/`.so` and ran `package:ffigen` on the header file
- Finally, I was able to write a simple wrapper class to make a cleaner, more Dart-like API:
```dart
import "dart:io";
import "dart:typed_data";
import "dart:ffi" as ffi;
import "package:ffi/ffi.dart";

import "generated_bindings.dart";

const path = r"opencv\wrappers\winbuild\Debug\wrapper.dll";

class Camera {
  final OpenCV native;  // the ffigen-generated bindings
  final int index;  // index of the camera

  // objects and data to be allocated for OpenCV
  final arena = Arena();
  late final ffi.Pointer<VideoCapture> camera;
  late final ffi.Pointer<Mat> image;

  Camera(this.index) { ... }  // call constructors
  void dispose() { ... } /// call destructors

  // Some simple functions
  bool get isOpened => native.VideoCapture_isOpened(camera) != 0;
  bool read() => native.VideoCapture_read(camera, image) != 0;
  void display() => native.imshow(image);

  // A more complex example:
  Future<bool> saveScreenshot(File file, {int quality = 75}) async {
    if (!read()) return false;
    final buffer = arena<ffi.Uint8>(50000);
    final size = native.encodeJpg(image, quality, buffer);
    if (size == 0) return false;
    final Uint8List data = ffi.Uint8Pointer(buffer).asTypedList(size);
    file.writeAsBytes(data, flush: true);
    return true;
  }
}
```
- Tested with a simple "stream webcam and display it like `cv2.imshow`": 
```dart
import "package:opencv_test/camera.dart";

Future<void> main2(Camera camera) async {
  print("Camera is: ${camera.isOpened ? 'Connected' : 'Not connected'}");
  // if (!camera.isOpened) return;
  while (true) {
    final success = camera.read();
    if (!success) { print("Something went wrong!"); break; }
    camera.display();
    Future<void>.delayed(Duration(milliseconds: (1000/60).round()));
  }
}

void main() async {
  final camera = Camera(0);
  try { await main2(camera); }
  finally { camera.dispose(); }
}
```
I think this could be valuable to integrate into Flutter to quickly enable Mac and Linux support and tie them into Windows support as well. I'd also like to use this as a Dart package in general, so I'm not sure what's the best option here, especially in terms of distributing/compiling OpenCV (technically and legally). I can keep going, writing more C wrappers for more OpenCV APIs, or take a more structured approach instead. I'd love to hear your thoughts and help push this forward if possible.

**Comment by dcharkes** [comment]
Cool stuff @Levi-Lesches!

I'm not the right person to comment on "integrate into Flutter", I'll leave that to the Flutter team.

From an `dart:ffi` use point of view, some feedback on code style:

* You can use `arena` from `package:ffi` to call `dispose` at the end (it has support for async and does try/finally internally).
* You should consider making `Camera` implement `Finalizable` and attaching a `NativeFinalizer` to do the dispose with a direct call to the C function. That way users who forget to call dispose still have the native resources cleaned up.
* If you're not already doing so, use package:ffigen to automatically generate the Dart bindings for your C header file.

Some feedback on bundling the dll in a package:

* For flutter, currently the way to do it is with `flutter create --template=plugin_ffi`.
* For dart, there currently is no convenient way. The best practise is to have a `bin/setup.dart` script that does the bundling.
* Currently, there is no way to release for both flutter/dart in a single package (see for example package:realm and package:realm_dart as a workaround). We're actively working on addressing this: https://github.com/dart-lang/sdk/issues/50565.

**Comment by Levi-Lesches** [comment]
> You can use arena from package:ffi to call dispose at the end (it has support for async and does try/finally internally).

I was using `arena` to allocate the `buffer`, but not in the way you're saying. Do you mean allocating the `VideoCapture` itself in an arena?

> You should consider making Camera implement Finalizable and attaching a NativeFinalizer to do the dispose with a direct call to the C function. 

Ah, cool. I just learned about ffi on Sunday but I do remember skimming that page on the API docs

> We're actively working on addressing this: https://github.com/dart-lang/sdk/issues/50565.

Hm, interesting thread -- thanks, I'll keep an eye on that one!

> For flutter, currently the way to do it is with flutter create --template=plugin_ffi.

I didn't know about this one. I'll wait to hear from the "right person" on whether Flutter wants to integrate this into the official `camera` plugin before making my own "other camera that does the same stuff" package. Do you know if using OpenCV like this will work on Android and iOS as well? I'd imagine so, since it's still C++/C, but I'm not sure.

> For dart, there currently is no convenient way. 

That's what I thought, sadly. What should the `bin\setup.dart` file look like? Download my C wrappers, clone OpenCV and compile them? For now, it's not an issue for me because this was meant for a private project, but I'd be happy to take the extra steps to publish this as well.

**Comment by stuartmorgan** [comment]
I'm not clear on what exactly is being proposed here. What functionality are you proposing adding to `camera`?

The "Use Case" section of the proposal seems to be describing a specific technical solution (I'm not sure to what) rather than a use case to solve.

**Comment by Levi-Lesches** [comment]
Essentially, the "Use Case" is "bring the camera plugin to more platforms", but yes, this is a technical proposal to use OpenCV to at least integrate the desktop platforms. I was motivated to do this because I saw that the `camera_windows` plugin is still unstable, and my project uses Linux, and I figured I can help speed things along for the desktop users out there. I'm not really proposing a new feature, just offering help in terms of offering my experience, writing PRs, and testing, if the Flutter team is interested. I just couldn't find a good issue template for that :)

**Comment by stuartmorgan** [comment]
Generally that would be done via discussion on a goal-based issue (e.g., "Implement `camera` for Linux", which is https://github.com/flutter/flutter/issues/41710), which is why we don't have a template for it.

The goal of the `camera` plugin is to provide Flutter developers access to the system-provided camera APIs (e.g., AVFoundation, MediaRecorder, Media Foundation), so building on top of (and distributing) a third-party library is out of scope. If you're interested in making it generally available, creating a new plugin would be the path forward. You have a couple of options there:
- You could make a completely new stand-alone plugin that people could use instead of `camera`.
- You could create unendorsed federated implementations of `camera` using `camera_platform_interface`, such that people could use `camera` but with your underlying implementation.

(This is analogous to, for instance, `video_player` being a wrapper around system video playback, but there being third-party video player plugins using other stacks such as VLC.)

Closing as this is out of scope for the Flutter project. Please feel free to file issues if you encounter any Flutter-level impediments to developing your plugin!
