### ISSUE TITLE
Unable to run Flutter with hot reload on iOS 17

### ISSUE THREAD

**Issue by ArkinSolomon** [flutter/flutter#128531]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Have a functioning Flutter project that builds on iOS 16.4
2. Update to MacOS Sonoma developer beta, iOS 17 developer beta, and the Xcode 15 beta
3. Run `flutter doctor -v` and see that everything checks out
4. Run `flutter run --debug -v` and see that it doesn't work

### Actual results

I had a project that was working fine, with iOS 16, but I recently updated to the iOS 17 developer beta. The project runs fine from Xcode using Product > Run, but it's a pain to have to rebuild every time. Note that the logs show that I am using the beta tool, but I get the same output on the stable tool.

I have switched the selected Xcode to the beta using `xcode-select` and `xcode-select -p` reflects that (`/Applications/Xcode-beta.app/Contents/Developer`). 

I noticed this line near the end of the log:
```
[+2503 ms] 2023-06-08 14:40:10.025 ios-deploy[24347:205465] [ !! ] Unable to locate DeviceSupport directory with suffix 'DeveloperDiskImage.dmg'. This probably means you don't have Xcode installed, you will need to launch the app manually and logging output will not be shown!
```
I did look in the `/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform` folder, but there is no folder for 17. I have installed (and tried reinstalling) iOS 17 support through Xcode settings > Platforms > iOS 17.0 beta. I also found [this thread](https://developer.apple.com/forums/thread/730947) and posted to it, but no one has responded yet. Anybody know what to do?

Again I'd like to point out that Product > Run does work, however I can't run it through VSCode or terminal, I can only run it through Xcode.

Also note that `flutter build ios` works fine.

### Logs

[log.txt](https://github.com/flutter/flutter/files/11692551/log.txt)

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

[✓] Flutter (Channel beta, 3.11.0-0.1.pre, on macOS 14.0 23A5257q darwin-x64, locale en-US)
    • Flutter version 3.11.0-0.1.pre on channel beta at /Users/arkinsolomon/fvm/versions/beta
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 350d2c3a6c (2 weeks ago), 2023-05-23 15:52:05 -0700
    • Engine revision 7eca5cd1c5
    • Dart version 3.1.0 (build 3.1.0-63.1.beta)
    • DevTools version 2.23.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Build 15A5160n
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2022.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (3 available)
    • Arkin’s iPhone (mobile) • <REDACTED-IPHONE-IDENTIFIER> • ios            • iOS 17.0 21A5248v
    • macOS (desktop)         • macos                        • darwin-x64     • macOS 14.0 23A5257q darwin-x64
    • Chrome (web)            • chrome                       • web-javascript • Google Chrome 114.0.5735.106

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

</details>

**Comment by jasonian** [comment]
> I also found [this thread](https://developer.apple.com/forums/thread/730947) and posted to it, but no one has responded yet.

From two days ago:

https://developer.apple.com/forums/thread/730947?answerId=754878022#754878022

**Comment by ArkinSolomon** [comment]
Alright so somebody from Apple responded to the thread on the Apple developer forum:

> Sounds like Flutter may need to update their assumptions about how the system works. (I don't know why Flutter relies on that folder; that's a question for Flutter.)

**Comment by darshankawar** [comment]
Thanks for the report @ArkinSolomon 
Please check [this](https://stackoverflow.com/questions/63198476/unable-to-run-ios-app-on-ios-14-with-flutter) SO link and see if it helps in your case.

**Comment by ArkinSolomon** [comment]
I came across that, and it points to [the same GitHub](https://github.com/filsv/iOSDeviceSupport) as mentioned in the [Apple developer thread](https://developer.apple.com/forums/thread/730947). However, as they mentioned in the thread, these device files do not exist within the `/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform` folder anymore. I'm assuming they changed the system for iOS 17.

**Comment by darshankawar** [comment]
Thanks for the feedback. I'll keep this issue open and label for tracking and team's attention, as currently I don't have the said configuration, ie, latest macOS and iOS version.

**Comment by leighajarett** [comment]
@vashworth sounds like what you had mentioned

**Comment by vashworth** [comment]
Yes, this is the issue I had as well. Flutter uses a third-party tool called `ios-deploy` that is used to install the app on the device, launch the app, start debug server, and stream device logs. `ios-deploy` depends on the DeveloperDiskImage which should be located within Xcode-beta.app > Contents > Developer > Platforms > iPhoneOS.platform > DeviceSupport > 17.x as mentioned above. It could be that it's not there because it's in beta or it could be a permanent change. Either way, we're looking into alternatives.

**Comment by mdddj** [comment]
Same issue, unable to start debugging on xcode15 and iOS17

**Comment by Ssiswent** [comment]
The same, I could run my Flutter project with Xcode 15, but I can't run with VS Code or Terminal.
<img width="845" alt="image" src="https://github.com/flutter/flutter/assets/37449310/67f85938-312b-4bb5-bb01-d5212f316eb0">

**Comment by vashworth** [comment]
We're working to fix this issue, but in the meantime you can do the following as a workaround:
1. Open your_project/ios/Runner.xcworkspace in Xcode
2. Select "Product > Run" or click the Play button in Xcode
3. In a terminal, in the directory of your project, run `flutter attach`
4. Select the device you're running the app on

If you're given a message like "There are multiple Dart VM Services available", proceed to the following steps:

5. Open the running Xcode and check the console for a log statement like:
```
flutter: The Dart VM service is listening on http://127.0.0.1:54585/O7W9iUI66Bo=/
```
6. Identify the port number - it's the number following the `127.0.0.1:`, in the above example the port is 54585.
7. The "There are multiple Dart VM Services available" error message should have printed a list of commands. Copy and paste the `flutter attach` command from the list with the `device-vmservice-port` matching the port you identified in step 6.
The command should be like:
```
flutter attach --app-id "com.example.your_project" --device-vm-service-port 54585
```
8. Run the command

**Comment by Ssiswent** [comment]
> We're working to fix this issue, but in the meantime you can do the following as a workaround:
> 
> 1. Open your_project/ios/Runner.xcworkspace in Xcode
> 2. Select "Product > Run" or click the Play button in Xcode
> 3. In a terminal, in the directory of your project, run `flutter attach`
> 4. Select the device you're running the app on
> 
> If you're given a message like "There are multiple Dart VM Services available", proceed to the following steps:
> 
> 5. Open the running Xcode and check the console for a log statement like:
> 
> ```
> flutter: The Dart VM service is listening on http://127.0.0.1:54585/O7W9iUI66Bo=/
> ```
> 
> 6. Identify the port number - it's the number following the `127.0.0.1:`, in the above example the port is 54585.
> 7. The "There are multiple Dart VM Services available" error message should have printed a list of commands. Copy and paste the `flutter attach` command from the list with the `device-vmservice-port` matching the port you identified in step 6.
>    The command should be like:
> 
> ```
> flutter attach --app-id "com.example.your_project" --device-vm-service-port 54585
> ```
> 
> 8. Run the command

Thanks! This is really useful.
I can use `attach` request in VS Code to debug my flutter project.
<img width="609" alt="image" src="https://github.com/flutter/flutter/assets/37449310/4cb7b786-6879-40e7-921b-44a68563506c">

**Comment by sportakal** [comment]
Thanks for support.

I need to run profile on physical device iOS 17 beta. How could i do it?

I need exactly run this command
`flutter run --profile --cache-sksl --purge-persistent-cache` than capture SkSL shaders. I can't run profile mode on emultaor and my physical device is iOS 17 beta.

**Comment by bibaswan-bhawal** [comment]
https://developer.apple.com/forums/thread/730947?answerId=756665022#756665022

This might be of interest to the flutter team working on this issue

**Comment by stuartmorgan** [comment]
> This might be of interest to the flutter team working on this issue

Unfortunately the thing they are referring to as being supported going forward is unrelated to the tool that Flutter relies on to interact with devices. While the underlying cause of that thread--specific changes in Xcode structure--is the same, the functionality is not.

**Comment by vashworth** [comment]
> I need to run profile on physical device iOS 17 beta. How could i do it?
> 
> I need exactly run this command `flutter run --profile --cache-sksl --purge-persistent-cache` than capture SkSL shaders. I can't run profile mode on emultaor and my physical device is iOS 17 beta.

To run in profile mode, you will also need to run through Xcode. 
1. Open your_project/ios/Runner.xcworkspace in Xcode
2. Select "Product > Scheme > Edit Scheme"
3. Change Build Configuration for Run to Profile.
![Screenshot 2023-07-07 at 9 47 52 AM](https://github.com/flutter/flutter/assets/15619084/4f8599c6-f8d8-4f29-9f5c-60664b23b2e6)
4. In the Arguments tab, add any launch arguments you want to include.
![Screenshot 2023-07-07 at 9 48 17 AM](https://github.com/flutter/flutter/assets/15619084/e0496aaf-9a5b-4fa6-a1aa-43a80da5f22a)
5. Close scheme editor. Select "Product > Run" or click the Play button in Xcode
6. In a terminal, in the directory of your project, run `flutter attach --profile`
7. Select the device you're running the app on

If you're given a message like "There are multiple Dart VM Services available", proceed to the follow steps 5-8 from https://github.com/flutter/flutter/issues/128531#issuecomment-1587984546

**Comment by VladBontaValentin** [comment]
Any updates for this issue?

**Comment by Imgkl** [comment]
> We're working to fix this issue, but in the meantime you can do the following as a workaround:
> 
> 1. Open your_project/ios/Runner.xcworkspace in Xcode
> 2. Select "Product > Run" or click the Play button in Xcode
> 3. In a terminal, in the directory of your project, run `flutter attach`
> 4. Select the device you're running the app on
> 
> If you're given a message like "There are multiple Dart VM Services available", proceed to the following steps:
> 
> 5. Open the running Xcode and check the console for a log statement like:
> 
> ```
> flutter: The Dart VM service is listening on http://127.0.0.1:54585/O7W9iUI66Bo=/
> ```
> 
> 6. Identify the port number - it's the number following the `127.0.0.1:`, in the above example the port is 54585.
> 7. The "There are multiple Dart VM Services available" error message should have printed a list of commands. Copy and paste the `flutter attach` command from the list with the `device-vmservice-port` matching the port you identified in step 6.
>    The command should be like:
> 
> ```
> flutter attach --app-id "com.example.your_project" --device-vm-service-port 54585
> ```
> 
> 8. Run the command

This doesn't work for me. When i run the flutter attach command, throws this error.


```
❯ flutter attach --app-id "myappID" --device-vm-service-port 59409
Could not find an option named "device-vm-service-port".


Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
```

**Comment by montythemack** [comment]
I tried flutter attach but it doesn't recognize my device in the list?

**Comment by np8698** [comment]
I tried to use the XCode 15 beta 5 version. And it works perfectly with my iPhone, which is updated to IOS 17 developer beta version.
Make sure to download the ios 17 simulator pack in XCode for it to work.

**Comment by montythemack** [comment]
> I tried to use the XCode 15 beta 5 version. And it works perfectly with my iPhone, which is updated to IOS 17 developer beta version.
> 
> Make sure to download the ios 17 simulator pack in XCode for it to work.

This worked for me with the simulator but not a physical device on iOS 17

**Comment by bibaswan-bhawal** [comment]
Also note it works fine when running from Xcode the issues is the flutter run command is broken

**Comment by JaredEzz** [comment]
Still having this issue. Thanks for all the hard work on it

**Comment by Ethan-Katz** [comment]
I am still getting 'could not run build/ios/iphoneos/runner.app on device' 
Im currently using the workaround but will there be a fix?

**Comment by vashworth** [comment]
New tooling has been added to Flutter 3.13 and Flutter 3.14.0-0.1.pre, which should allow `flutter run` to work with iOS 17 physical devices.

If new issues are discovered, please file new issues for them.

**Comment by mshere9** [comment]
Latest Beta & Flutter Latest Version resolved the issue.
