### ISSUE TITLE
Travis flake: No output has been received in the last 10 minutes

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#12857]
Travis flakes with:

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated

**Comment by zoechi** [comment]
I assume this is stale.
