### ISSUE TITLE
Textures are converted from Linear RGB to sRGB

### ISSUE THREAD

**Issue by ds84182** [flutter/flutter#12854]
The color in screenshot version is #007BC6, but from a video texture the color is #00B9E4.

![](https://cdn.discordapp.com/attachments/290514446412021760/375747851122114560/Screenshot_20171102-163313.png)
![](https://cdn.discordapp.com/attachments/290514446412021760/375747851122114562/Screenshot_20171102-163320.png)

I made a small thing on DartPad to confirm that the color is being converted from linear RGB to sRGB [here](https://dartpad.dartlang.org/673bd4ce019caf10cd99719b41f3f65d).

**Comment by eseidelGoogle** [comment]
Is this related to https://github.com/flutter/flutter/issues/10655?

**Comment by ds84182** [comment]
I think so.

black26 (which has an alpha of 0x42) blended with white (0xFF) usually yields #bdbdbd. However, Flutter produces #dfdfdf (on my phone). Converting Flutter's output (0xDF) from sRGB to Linear gives 0xBC. Converting the expected 0xBD from sRGB to Linear gives 0x82, which would be produced from a blend with 0x7D.

So if all drawing is done in Linear and converted to sRGB, shouldn't all the color constants be in Linear space instead of sRGB?

Might be interesting to try...

**Comment by ds84182** [comment]
Anyways, right now on Android [the resulting SkImage doesn't have a color space assigned](https://github.com/flutter/engine/commit/9a960f82f56454e2e45e8e71f2e78529f0225c27#diff-fab26f494839312a78ac197fd731e2afR51), [same thing for iOS](https://github.com/flutter/engine/commit/9a960f82f56454e2e45e8e71f2e78529f0225c27#diff-2d9e493e7bcefbaea32db2dbe1119e0cR65). Developers should be able to choose between sRGB and linear, with sRGB being the default [since SkPaint's color is assumed to be sRGB anyways](https://github.com/google/skia/blob/master/site/user/sample/color.md#best-practices-for-color-correct-skia).

For now I can work around this by converting my sRGB colors to linear so Flutter will convert them back to sRGB. The only problem with this is color inaccuracies for color components below 0x7F, but hopefully it shouldn't be _too_ much of a problem.

**Comment by ds84182** [comment]
Alright, looks like this has been fixed on master. Closing.
