### ISSUE TITLE
Defaults generator uses invalid tokens

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter#128578]
As identified in https://github.com/flutter/flutter/pull/128244, some of the templates use non-existent tokens. These usages should be replaced with valid tokens or removed.

![image](https://github.com/flutter/flutter/assets/6655696/a9aa511b-aea5-499a-94a8-d7312a2b23c3)

**Comment by QuncCccccc** [comment]
The improvement is provided here: https://github.com/flutter/flutter/pull/140872, so I'm closing this issue:)
