### ISSUE TITLE
Bluetooth, cameras, wifi...

### ISSUE THREAD

**Issue by GorIvanov** [flutter/flutter#128579]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I would like to contact flutter developers. I hope you read github.
You are creating a cross-platform framework that should behave the same on all platforms and have common interaction mechanisms. Now there are more than 10 options for plugins for working with bluetooth on pub.dev. I believe that you, as developers of a cross-platform framework, are obliged to develop and make part of the framework all the basic mechanisms for working with such things as bluetooth, cameras, wifi, and the like, as is done for example in QT.

### Proposal

I would like to contact flutter developers. I hope you read github.
You are creating a cross-platform framework that should behave the same on all platforms and have common interaction mechanisms. Now there are more than 10 options for plugins for working with bluetooth on pub.dev. I believe that you, as developers of a cross-platform framework, are obliged to develop and make part of the framework all the basic mechanisms for working with such things as bluetooth, cameras, wifi, and the like, as is done for example in QT.

**Comment by stuartmorgan** [comment]
> I believe that you, as developers of a cross-platform framework, are obliged to develop

I would encourage you to read https://github.com/flutter/flutter/wiki/Issue-hygiene#when-will-my-bug-be-fixed, as the first paragraph discusses Flutter's development structure.

> and make part of the framework all the basic mechanisms

While bundling every piece of functionality into the framework is a possible approach, it is not the one Flutter chooses to use. We believe that modular access to specific OS features via plugins provides a number of advantages.

> such things as bluetooth, cameras, wifi, and the like

- Bluetooth is tracked in https://github.com/flutter/flutter/issues/53493.
- The Flutter team already maintains the `camera` plugin.
- Wifi was previously a first-party plugin, but was migrated to the community-owned `network_info_plus` plugin; we have no plans to reverse that decision.

Closing as there is no specific feature request to track here. Please feel free to file individual issues for any other specific functionality you believe should be implemented.
