### ISSUE TITLE
share preferences on ios 16.3.1 and latter 

### ISSUE THREAD

**Issue by mehransahandi** [flutter/flutter#128538]
some of shared preferences doesn't save data after ios 16.3.1 data once app is published to app store, on debugging there is no problem but. 
in my code I have a few data saved in shared preferences, after 4-5 which are saved the rest doesn't  I also do not receive any error or crashes.

**Comment by darshankawar** [comment]
@mehransahandi 
Can you provide `flutter doctor -v`, a runnable code sample along with current results you are seeing along with expected behavior ?

**Comment by mehransahandi** [comment]
Flutter (Channel stable, 3.7.12, on macOS 13.4 22F66 darwin-arm64, locale en-DE)
    • Flutter version 3.7.12 on channel stable at /Users/msahandi/Flutter/flutter
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.13.3/libexec/bin/dart, which is not inside your current Flutter SDK checkout at
      /Users/msahandi/Flutter/flutter. Consider adding /Users/msahandi/Flutter/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (7 weeks ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/msahandi/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • INM-7 (mobile)  • 00008101-000E099E22B9001E • ios            • iOS 16.5 20F66
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 114.0.5735.106

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by darshankawar** [comment]
> a runnable code sample along with current results you are seeing along with expected behavior ?

Also this please.

**Comment by mehransahandi** [comment]
My Main question is, why after the update in ios to 16.3.1 the app behavior is changed,
actually, there is no problem on the code side, as it was working before the update and as well as during debugging, there should be something related to ios update which shared preference, I also found out it actually take very long time to execute and once you reload the app, it works

**Comment by darshankawar** [comment]
See if [this](https://pub.dev/packages/shared_preferences#migration-and-prefixes) helps in your case or not.

**Comment by darshankawar** [comment]
> why after the update in ios to 16.3.1 the app behavior is changed,
> actually, there is no problem on the code side, as it was working before the update and as well as during debugging, there should be something related to ios update which shared preference, I also found out it actually take very long time to execute and once you reload the app, it works

This probably also indicates that apple support would be a good platform to reach out to.

**Comment by mehransahandi** [comment]
I tried also apple support but nothing yet, this is an serious problem and I guess will effect many apps, I probably going to use db instead of shared preferences as there is no really solution

**Comment by darshankawar** [comment]
Check [this](https://stackoverflow.com/questions/66715945/sharedpreference-loses-data-when-updating-the-flutter-app-on-app-store-and-play) and see if it helps.
