### ISSUE TITLE
devicelab win arm machines having OS issues

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#128536]
@kentnguyen99 please check the new windows arm bots.

win-7 seems to be functioning correctly. Example, run command to find location of cmd.exe:

`where cmd.exe`

and it returns as expected. Other new bots (e.g. win-10) is having problems:

```
where cmd.exe
'where' is not recognized as an internal or external command,
operable program or batch file.
```

Please check the windows version information of win-11 and paste here. Win-7 version info:

```
>systeminfo | findstr /i "OS Version"   
Host Name:                 FLUTTER-WIN-7
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22621 N/A Build 22621
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
System Manufacturer:       Microsoft Corporation
BIOS Version:              Microsoft Corporation 7.31.139, 1/1/1601
```

**Comment by yusuf-goog** [comment]
@kentnguyen99 during setup of the devices, was there anything that you performed differently between the initial win-7 machine and the others?

**Comment by kentnguyen99** [comment]
All Arm Windows has been resolved and fixed, it was "Windows Environment  Path" missing %SystemRoot%\system32.
