### ISSUE TITLE
center BackButtonIcon ios/macos

### ISSUE THREAD

**Issue by Geara0** [flutter/flutter#128555]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Currently BackButtonIcon is not centered in its box:
<img width="71" alt="Screenshot 2023-06-09 at 09 40 38" src="https://github.com/flutter/flutter/assets/78842812/898b4846-c147-4672-bff5-8bfb6f1af1b8">

### Proposal

This looks better:
<img width="57" alt="Screenshot 2023-06-09 at 09 41 59" src="https://github.com/flutter/flutter/assets/78842812/b59fbbc0-7867-4dda-a9fb-05d981d0f113">

All you need to do is replace `return Icons.arrow_back_ios` with `return Icons.arrow_back_ios_new` in action_buttons.dart -> BackButtonIcon

**Comment by Geara0** [comment]
Origins of problem (i guess):
https://github.com/google/material-design-icons/issues/824

**Comment by Jainakin** [comment]
can you please assign me this issue, thanks!
