### ISSUE TITLE
Preferred Camera Device is not working on Android

### ISSUE THREAD

**Issue by always-together12** [flutter/flutter#128515]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I want to take a picture using the front camera.
but it always opens the rear camera

final file = await ImagePicker().pickImage(
                        source: ImageSource.camera,
                        preferredCameraDevice: CameraDevice.front,
);

### Expected results

I want to open the front camera by default

### Actual results

it always opens the rear camera

### Code sample

<details><summary>Code sample</summary>

```dart
final file = await ImagePicker().pickImage(
                        source: ImageSource.camera,
                        preferredCameraDevice: CameraDevice.front,
);
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Hi @always-together12 
Which device are you working on? And what's your current `image_picker` plugin version?

I check this issue on my device (Pixel 3a, Android 12) but it works as expected. I'm using [image_picker sample code](https://github.com/flutter/packages/tree/main/packages/image_picker/image_picker/example).

**Comment by always-together12** [comment]
I tested it on both Real Device(Samsung Galaxy S23 Android 10) and Emulator(Pixel 5 Android 10).
All are not working

**Comment by huycozy** [comment]
Thanks for your response. I've just checked again documentation and found [this](https://github.com/flutter/packages/blob/c9865e8c63dca018d7b071b0b9dfa19201fb0cb1/packages/image_picker/image_picker/lib/image_picker.dart#L49-L51):

```
  /// Defaults to [CameraDevice.rear]. Note that Android has no documented parameter for an intent to specify if
  /// the front or rear camera should be opened, this function is not guaranteed
  /// to work on an Android device.
```

Related PR: https://github.com/flutter/plugins/pull/3037

And this also has been explained at https://github.com/flutter/flutter/issues/55644#issuecomment-691079453. You can try a hack there to see if it works on your device. 

I'm therefore going to close this issue as not an issue with the plugin, but a current limitation on Android.
