### ISSUE TITLE
Compass Features Without Touch Map

### ISSUE THREAD

**Issue by dineshtechnoproject** [flutter/flutter#128509]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

In Map When i tap Custom Compass button after that Compass Feature start.The map will now rotate based on the direction you're facing, with the compass needle pointing to the north.

### Proposal

Tracking Order By Delivery Driver

**Comment by darshankawar** [comment]
@dineshtechnoproject 
Can you take a look at below issues and see if they resemble your case ?


https://github.com/flutter/flutter/issues/26117
https://github.com/flutter/flutter/issues/28191
