### ISSUE TITLE
Keyboard show/hide will cause the widget repaint inside 'showModalBottomSheet'

### ISSUE THREAD

**Issue by Coder7777** [flutter/flutter#128542]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1, call the showModalBottomSheet
2, put the focus on the TextField
3, the keyboard will popup
4, observe the date & time will be refreshed (rerender many times)
5, hide the keyboard 
6, observe the date & time will be refreshed again (rerender many times)

### Expected results

keyboard show/hide should not emit the repaint / rerender unless calling 'setState' manually.
Even I drag and release the bottom sheet, it is still rerendered automatically (**### the time will change automatically**).

### Actual results

I put some widgets on Container, and then show them via showModalBottomSheet. 
I can input some text on the 'showModalBottomSheet' layer, but once TextField gets the focus and popup the keyboard,
the widgets on the 'showModalBottomSheet' will be rerendered automatically, and the data of those widgets fetched from the HTTP request, finally it causes many unnecessary HTTP requests to be sent. 
It wastes network and performance and makes everything mass.

### Code sample

<details><summary>Code sample</summary>
 

```
showModalBottomSheet(
        context: context,
        isScrollControlled: true,
        builder: (context) {
          return SizedBox(
            height: 600,
            child: Scaffold(
              appBar: AppBar(
                title: const Text("ShowModalBottomSheet"),
              ),
              body: SafeArea(
                child: Column(
                  mainAxisSize: MainAxisSize.max,
                  children: [
                    SizedBox(
                      height: 80,
                      child: Text(
                        "${DateTime.now()}",
                        style: const TextStyle(fontSize: 18, color: Colors.red),
                      ),
                    ),
                    const TextField(
                      decoration: InputDecoration(
                        border: OutlineInputBorder(),
                        hintText: 'Enter a search term',
                      ),
                    ),
                  ],
                ),
              ),
            ),
          );
        }); 
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

https://github.com/flutter/flutter/assets/17242425/a2fad94e-6c1a-4dd6-9ecc-7a9266fb46db

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.2, on macOS 13.3.1 22E772610a darwin-arm64, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.71.2)
[✓] VS Code (version 1.78.2)
[✓] Connected device (3 available)
[✓] Network resources
```

</details>

**Comment by darshankawar** [comment]
@Coder7777 
Can you switch to latest master and run your scenario again to see if the issue persists or not ?

`flutter channel master`
`flutter upgrade`

**Comment by Coder7777** [comment]
> @Coder7777 Can you switch to latest master and run your scenario again to see if the issue persists or not ?
> 
> `flutter channel master` `flutter upgrade`

I follow you recommended, then I can not run my project now. what should I do?

`
Launching lib/main_dev.dart on Pixel 6a in debug mode...
Unhandled exception:
Unexpected Kernel Format Version 101 (expected 103)
#0      BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:686:9)
#1      Timeline.timeSync (dart:developer/timeline.dart:171:22)
#2      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:673:21)
#3      _InitializationFromSdkSummary._prepareSummary (package:front_end/src/fasta/incremental_compiler.dart:2488:12)
#4      _InitializationFromUri.initialize (package:front_end/src/fasta/incremental_compiler.dart:2562:23)
<asynchronous suspension>
#5      IncrementalCompiler._ensurePlatformAndInitialize (package:front_end/src/fasta/incremental_compiler.dart:1423:25)
<asynchronous suspension>
#6      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:312:11)
<asynchronous suspension>
#7      IncrementalCompiler.compile (package:vm/incremental_compiler.dart:75:50)
<asynchronous suspension>
#8      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:599:11)
<asynchronous suspension>
#9      listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1312:11)
<asynchronous suspension>
the Dart compiler exited unexpectedly.
the Dart compiler exited unexpectedly.
`




flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.12.0-3.0.pre.37, on macOS 13.3.1 22E772610a darwin-arm64, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.79.0)
[✓] VS Code (version 1.71.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

**Comment by Coder7777** [comment]
> > @Coder7777 Can you switch to latest master and run your scenario again to see if the issue persists or not ?
> > `flutter channel master` `flutter upgrade`
> 
> I follow you recommended, then I can not run my project now. what should I do?
> 
> `Launching lib/main_dev.dart on Pixel 6a in debug mode... Unhandled exception: Unexpected Kernel Format Version 101 (expected 103) #0 BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:686:9) #1 Timeline.timeSync (dart:developer/timeline.dart:171:22) #2 BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:673:21) #3 _InitializationFromSdkSummary._prepareSummary (package:front_end/src/fasta/incremental_compiler.dart:2488:12) #4 _InitializationFromUri.initialize (package:front_end/src/fasta/incremental_compiler.dart:2562:23) <asynchronous suspension> #5 IncrementalCompiler._ensurePlatformAndInitialize (package:front_end/src/fasta/incremental_compiler.dart:1423:25) <asynchronous suspension> #6 IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:312:11) <asynchronous suspension> #7 IncrementalCompiler.compile (package:vm/incremental_compiler.dart:75:50) <asynchronous suspension> #8 FrontendCompiler.compile (package:frontend_server/frontend_server.dart:599:11) <asynchronous suspension> #9 listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1312:11) <asynchronous suspension> the Dart compiler exited unexpectedly. the Dart compiler exited unexpectedly.`
> 
> flutter doctor
> 
> Doctor summary (to see all details, run flutter doctor -v): [✓] Flutter (Channel master, 3.12.0-3.0.pre.37, on macOS 13.3.1 22E772610a darwin-arm64, locale en-CA) [✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0) [✓] Xcode - develop for iOS and macOS (Xcode 14.3.1) [✓] Chrome - develop for the web [✓] Android Studio (version 2021.3) [✓] VS Code (version 1.79.0) [✓] VS Code (version 1.71.2) [✓] Connected device (3 available) [✓] Network resources
> 
> • No issues found!



I fixed that dev environment. 
However, the topic mentioned issue is still there. 
It always rerenders while the TextField got the focus and popup keyboard.


Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.12.0-3.0.pre.37, on macOS 13.3.1 22E772610a darwin-arm64, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.71.2)
[✓] VS Code (version 1.79.0)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

**Comment by Coder7777** [comment]
I think that is a flutter bug. 

I try to simulate a similar scenario by 'showBottomSheet', and that result is expected. The widget shown on 'showBottomSheet' will not be effected by keyboard show/hide (the time never changed).

But 'showModalBottomSheet' is fitter for my scenario than 'showBottomSheet'. 

Please see the screen recording I made.

 ```
Scaffold.of(context).showBottomSheet<void>(
      (context) {
        return SizedBox(
          height: 500,
          child: Scaffold(
            resizeToAvoidBottomInset: false,
            appBar: AppBar(
              title: const Text("ShowBottomSheet"),
            ),
            body: SafeArea(
              child: ListView(
                children: [
                  SizedBox(
                    height: 40,
                    child: Text(
                      "${DateTime.now()}",
                      style: const TextStyle(fontSize: 18, color: Colors.red),
                    ),
                  ),
                  const TextField(
                    decoration: InputDecoration(
                      border: OutlineInputBorder(),
                      hintText: 'Enter a search term',
                    ),
                  ),
                ],
              ),
            ),
          ),
        );
      },
    );
```


https://github.com/flutter/flutter/assets/17242425/351f7fc8-1bf1-49fd-8231-fbfe15ce284c

**Comment by darshankawar** [comment]
Thanks for the update. See [this](https://stackoverflow.com/questions/56313800/why-does-the-software-keyboard-cause-widget-rebuilds-on-open-close) and check if it helps in your case or not.
