### ISSUE TITLE
Engine -> Framework roll blocked on Flutter CLI dds test failure.

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#128546]
Starting with the roll attempt here https://github.com/flutter/flutter/pull/128477

The Engine -> Framework roll is failing on a tool integration test on Windows

https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20tool_integration_tests_3_6/16539/overview

**Comment by zanderso** [comment]
cc @bkonyi

**Comment by jason-simmons** [comment]
Reproduced this in a local Windows environment.

This started with https://github.com/dart-lang/sdk/commit/74285a6e31c515a0dab881ac94933a3a239ce931

@mraleph

**Comment by mraleph** [comment]
The test is sending `app.detach` and then it gets `app.stop` back and also it gets `{id: 1, result: true}` as well, just the test crashes before this response is processed.

According to [daemon protocol doc](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/doc/daemon.md#appstop-1) getting `app.stop` back after detaching is a normal thing. So the question is why test harness does not expect it? 

My guess would be that this code:

```
    // Set up the response future before we send the request to avoid any
    // races. If the method we're calling is app.stop then we tell _waitFor not
    // to throw if it sees an app.stop event before the response to this request.
    final Future<Map<String, Object?>> responseFuture = _waitFor(
      id: requestId,
      ignoreAppStopEvent: method == 'app.stop',
    );
```  

Should actually be doing `      ignoreAppStopEvent: method == 'app.stop' || method == 'app.detach',`?

**Comment by zanderso** [comment]
I think the `Lost connection to device` is coming from here:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/resident_runner.dart#L1444

The daemon's `detach()` method calls the `ResidentRunner`'s `detach()`, which does *not* set `_exited` to `true`. When the connection to the service is closed, `_serviceDisconnected` is called in the `whenComplete`, which prints the message:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/resident_runner.dart#L1423

So it seems like the `Lost connection` message might be expected. I'd guess that it's also printed without the Dart roll.

**Comment by jason-simmons** [comment]
The "Lost connection to device" message is not printed when running without https://github.com/dart-lang/sdk/commit/74285a6e31c515a0dab881ac94933a3a239ce931.

With https://github.com/dart-lang/sdk/commit/74285a6e31c515a0dab881ac94933a3a239ce931 (and `ignoreAppStopEvent: method == 'app.stop' || method == 'app.detach'`) the sequence of events is:

```
       ATTACH  : =stdin=>   [{"id":1,"method":"app.detach","params":{"appId":"fbe85cdf-c1cf-47e5-8920-8c9d979644b7"}}]
       ATTACH  :            Expecting response to request 1...
       ATTACH  : <=stdout=  [  +51 ms] DevFS: Deleting filesystem on the device (file:///C:/Users/jsimmons/AppData/Local/Temp/flutter_attach_test.a39f3a1cb87c865/flutter_attach_test.a39f3a1/)
       ATTACH  : <=stdout=  [   +1 ms] DevFS: Deleted filesystem on the device (file:///C:/Users/jsimmons/AppData/Local/Temp/flutter_attach_test.a39f3a1cb87c865/flutter_attach_test.a39f3a1/)
       ATTACH  : <=stdout=  [  +13 ms] Service protocol connection closed.
       ATTACH  : <=stdout=  [        ] Lost connection to device.
       ATTACH  : <=stdout=  [{"event":"app.stop","params":{"appId":"fbe85cdf-c1cf-47e5-8920-8c9d979644b7"}}]
       ATTACH  : <=stdout=  [   +8 ms] "flutter attach" took 6,351ms.
       ATTACH  : <=stdout=  [{"id":1,"result":true}]
       ATTACH  :            OK (response to request 1)
       ATTACH  :            Waiting for process to end...
       ATTACH  : <=stdout=  [  +80 ms] ensureAnalyticsSent: 75ms
       ATTACH  : <=stdout=  [        ] Running 1 shutdown hook
       ATTACH  : <=stdout=  [        ] Shutdown hooks complete
       ATTACH  : <=stdout=  [        ] exiting with code 0
       ATTACH  :            Process exited (0)
   15s    RUN  :            Closing VM service...
          RUN  :            Stopping application...
          RUN  : =stdin=>   [{"id":1,"method":"app.stop","params":{"appId":"e2acfda8-93b9-4f0d-90c4-22ec7baee517"}}]
```

The "Service protocol connection closed" and "Lost connection" logs and the `app.stop` event happen before receiving the result of the `app.detach` command.

Without https://github.com/dart-lang/sdk/commit/74285a6e31c515a0dab881ac94933a3a239ce931 the sequence is:

```
       ATTACH  : =stdin=>   [{"id":1,"method":"app.detach","params":{"appId":"cb4971c6-746a-4456-a239-13824292389c"}}]
       ATTACH  :            Expecting response to request 1...
       ATTACH  : <=stdout=  [  +47 ms] DevFS: Deleting filesystem on the device (file:///C:/Users/jsimmons/AppData/Local/Temp/flutter_attach_test.5a4de813a3b8a0c8/flutter_attach_test.5a4de813/)
       ATTACH  : <=stdout=  [   +2 ms] DevFS: Deleted filesystem on the device (file:///C:/Users/jsimmons/AppData/Local/Temp/flutter_attach_test.5a4de813a3b8a0c8/flutter_attach_test.5a4de813/)
       ATTACH  : <=stdout=  [  +12 ms] Application finished.
       ATTACH  : <=stdout=  [{"id":1,"result":true}]
       ATTACH  :            OK (response to request 1)
       ATTACH  :            Waiting for process to end...
       ATTACH  : <=stdout=  [{"event":"app.stop","params":{"appId":"cb4971c6-746a-4456-a239-13824292389c"}}]
       ATTACH  : <=stdout=  [   +8 ms] "flutter attach" took 6,306ms.
       ATTACH  : <=stdout=  [   +6 ms] Service protocol connection closed.
       ATTACH  : <=stdout=  [  +75 ms] ensureAnalyticsSent: 77ms
       ATTACH  : <=stdout=  [        ] Running 1 shutdown hook
       ATTACH  : <=stdout=  [        ] Shutdown hooks complete
       ATTACH  : <=stdout=  [        ] exiting with code 0
       ATTACH  :            Process exited (0)
   15s    RUN  :            Closing VM service...
          RUN  :            Stopping application...
          RUN  : =stdin=>   [{"id":1,"method":"app.stop","params":{"appId":"80f610e8-65c5-4ac3-b3de-07178c468c90"}}]
```

**Comment by DanTup** [comment]
Does the test pass with that change? I'm not sure why the ordering has changed, but I'm not sure the order was guaranteed before. In the debug adapter I've written this comment, suggesting I expected this could happen:

https://github.com/flutter/flutter/blob/f65584317eded039f6ab5557efcb098935a89276/packages/flutter_tools/lib/src/debug_adapters/flutter_adapter.dart#L348-L350

I can't say for certain all clients of this daemon are as tolerable, but something caused me to handle it here, so I suspect it's happened in the past (without the change above)? 🤔

**Comment by jason-simmons** [comment]
The test passes with the `ignoreAppStopEvent: method == 'app.stop' || method == 'app.detach'` patch in `_sendRequest`.

AFAICT the app process in the test is shutting down as expected and is not crashing.

Apparently https://github.com/dart-lang/sdk/commit/74285a6e31c515a0dab881ac94933a3a239ce931 changed the timing of when flutter_tools receives notification of the VM service protocol closing, causing the daemon to send the `app.stop` event earlier.  But if the daemon does not enforce an ordering between `app.stop` and the response to `app.detach`, then the test should not depend on the order.

**Comment by eyebrowsoffire** [comment]
The changes rolled into the framework without any breakage. Closing
