### ISSUE TITLE
upgraded from 3.7 to 3.10 and TextFields stopped opening the keyboard

### ISSUE THREAD

**Issue by drkhannah** [flutter/flutter#128577]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

upgrade from 3.7 to 3.10

tap on a TextField

key board wont come up on physical device, android or iOS

keyboard only comes up if you long press and drag in TextField

### Expected results

tapping TextField should open the keyboard for editing the TextFormField

### Actual results

no keyboard is displayed when taping a TextFormField

no errors in console when tapping TextFormField

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Hi @drkhannah 
Which devices are you facing this issue? (OS, model) 
Does the issue occur with a simple `TextField`? Please provide the output of `flutter doctor -v` as well. Thanks!

**Comment by drkhannah** [comment]
All devices, iOS, Android, physical and simulator, all TextFormFields

**Comment by huycozy** [comment]
In order to address the issue properly, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so that we may verify this. Also, please provide the output of `flutter doctor -v` as well. Thank you!

**Comment by mikhael28** [comment]
The issue is that the TextField is wrapped wrapped in a GestureDetector.

**Comment by huycozy** [comment]
It could be an issue with GestureDetector as mentioned above. Please check again if it's your case, @drkhannah.

**Comment by mikhael28** [comment]
I had this same issue, so pretty sure that is the problem. A big bug to get shipped out, makes me wonder how many people are using bleeding edge Flutter in prod.

**Comment by darshankawar** [comment]
> The issue is that the TextField is wrapped wrapped in a GestureDetector.

@mikhael28 `GestureDetector` recognizes tap input by default and if wrapping it with TextFormField or any input field which also gets activated upon tapping in it, could be causing a gesture conflict and hence you could be seeing the error.

**Comment by bleroux** [comment]
I'm not sure if this is the same issue, but "TextField wrapped in a GestureDetector" issue was fixed recently: https://github.com/flutter/flutter/issues/129161

And there is a cherry pick underway: https://github.com/flutter/flutter/issues/129577
