### ISSUE TITLE
[in_app_purchase]: Subscription renewal transaction date is wrong

### ISSUE THREAD

**Issue by PeperMarkreel** [flutter/flutter#128505]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Subscribe to the purchaseStream
2. Wait for the end of current subscription period, query restorePurchases again
3. Get a PurchaseDetails that contains a transactiondate of the transaction at the start of the subscription (and not the transaction date of the renewal). 

Other reports of the same issue:
https://stackoverflow.com/questions/75484108/flutter-cant-detect-subscription-renewal-in-app-purchase

### Expected results

I expect the that transactionDate of the PurchaseDetails to contain the transactionDate of the most recent transaction. 

### Actual results

The transactionDate of the PurchaseDetails class after the renewal date/time contains the dateTime of the initial transaction from back when the subscription started. 

### Code sample

<details><summary>Code sample</summary>

```dart
I do nothing special & not sure if this is necessary, would really like to avoid making a minimal code sample if possible. I used the code from the example app as starting point. 
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.10.4, on Microsoft Windows [Version 10.0.22621.1702], locale en-NL)
    • Flutter version 3.10.4 on channel stable at c:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 682aa387cf (3 days ago), 2023-06-05 18:04:56 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code (version 1.78.2)
    • VS Code at C:\Users\snip\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1702]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 114.0.5735.110
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 114.0.1823.41

[√] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by dam-ease** [comment]
Hi @PeperMarkreel. Thanks for filing this issue. This seems to be similar to #83342. Kindly confirm it is.

**Comment by PeperMarkreel** [comment]
Hi @dam-ease, thanks for the response and the link. Sorry, I did not found that ;). This is probably the same issue indeed. Comment https://github.com/flutter/flutter/issues/83342#issuecomment-1139068945 describes it the best.

**Comment by darshankawar** [comment]
Closing as duplicate.
