### ISSUE TITLE
Update `CheckedPopupMenuItem‎` for Material 3

### ISSUE THREAD

**Issue by Curstantine** [flutter/flutter#128576]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Use a `ListTile` inside `PopupMenuItem` as suggested in the comments to include a leading icon.
2. `TextTheme.bodyLarge` is used on the `title` instead of the `TextTheme.labelLarge` as mentioned in the M3 spec.

### Expected results

`ListTile` with a `title` style of `TextTheme.labelLarge`.

### Actual results

`ListTile` with a `title` style of `TextTheme.bodyLarge`. The defaults of the `ListTile` is not being overriden by the `PopupMenuItem` when used with it.

1. Menu:
![image](https://github.com/flutter/flutter/assets/69104500/7f17323b-0ccf-4225-8543-0caba14c95e3)

2. ListTile: 
![image](https://github.com/flutter/flutter/assets/69104500/080aacd2-c477-468a-b84e-7d09ba032c3f)

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
	runApp(const App());
}

class App extends StatelessWidget {
	const App({super.key});

	@override
	Widget build(context) {
		return MaterialApp(
			theme: ThemeData.dark(useMaterial3: true),
			home: Scaffold(body: Center(child: PopupMenuButton(
				offset: const Offset(0, 56),
				itemBuilder: (context, ) {
					final theme = Theme.of(context);
					final text = theme.textTheme;
					final colors = theme.colorScheme;

					return [
						const CheckedPopupMenuItem(
							checked: true,
							child: Text("Checked"),
						),
						const PopupMenuItem(
							child: ListTile(
								leading: Icon(Icons.check_rounded),
								title: Text("Checked"),
							),
						),
						PopupMenuItem(
							child: ListTile(
								leading: const Icon(Icons.check_rounded),
								title: Text("Checked", style: text.labelLarge?.copyWith(color: colors.onSurface)),
							),
						)
					];
				}
			)))
		);
	}
}
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.2, on Arch Linux 6.3.5-arch1-1, locale en_US.UTF-8)
    • Flutter version 3.10.2 on channel stable at /home/<REDACTED>/Sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (2 weeks ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc2)
    • Android SDK at /opt/android-sdk
    • Platform android-33, build-tools 34.0.0-rc2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+7)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 15.0.7
    • cmake version 3.26.4
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • <REDACTED> (mobile) • <REDACTED> • android-arm64 • Android 12 (API 31)
    • Linux (desktop)     • linux      • linux-x64     • Arch Linux 6.3.5-arch1-1

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by huycozy** [comment]
Hi @Curstantine 
As far as I can see, it's displaying as expected:


- [`md.sys.typescale.label-large.size`](https://m3.material.io/styles/typography/type-scale-tokens#d74b73c2-ac5d-43c5-93b3-088a2f67723d): 14
- [`md.sys.typescale.body-large.size`](https://m3.material.io/styles/typography/type-scale-tokens#d74b73c2-ac5d-43c5-93b3-088a2f67723d:~:text=md.sys.typescale.body%2Dlarge.size): 16

| labelLarge | bodyLarge |
| --------------- | --------------- |
<img width="400" src="https://github.com/flutter/flutter/assets/104349824/d982aa8f-8473-4b10-b369-0cb707d30456"> | <img width="400" src="https://github.com/flutter/flutter/assets/104349824/119661e6-9e45-4cff-8647-01d7a6af8986">

Verified on the latest Flutter master channel. 

When applying `labelLarge` style to ListTile's title, it's displaying with `md.sys.typescale.label-large.size`. Is there anything that I'm missing here?

**Comment by Curstantine** [comment]
Sorry, I accidentally pressed on the close button.

In the specification, a menu item should use label large, which is respected in flutter if you directly use a Text widget inside a `PopupMenuItem`, but this senari

**Comment by huycozy** [comment]
>when using a ListTile, this text style restriction is ignored.

Sorry, but I'm still not clear this. As the demo below, ListTile and Text have been rendered the same size (labelLarge) as expected. 

| ListTile | Text |
| --------------- | --------------- |
<img width="400" src="https://github.com/flutter/flutter/assets/104349824/50194096-7a8f-4d6e-be47-2c7ccb4ba3d8"> | <img width="400" src="https://github.com/flutter/flutter/assets/104349824/5ef64971-ab48-4d22-aedd-1fd7fbb4b91c">

>ListTile with a title style of TextTheme.bodyLarge

Can you please share the screenshot of your actual result along with the target environment info? (I don't think this is an issue on specific platform, though)

**Comment by Curstantine** [comment]
It does style when we override it, yes. But not on its own.

When a ListTile is used inside a PopupMenuItem, it should default to the `labelLarge` since the preferred way of adding icons and such to a PopupMenuItem is by using a ListTile.

ListTile uses its own default `bodyLarge` when it should've been defaulted to `labelLarge` when the parent is a MenuItem.

The reason I filed this issue is because it gets repetitive to override the text style everytime a MenuItem needs a leading/trailing icon.

As I pointed out in the second code, the PopupMenuItem overrides the default bodyLarge text style when a Text widget is used directly, but not when a ListItem nests a `title` Text widget.

```dart
[
	PopupMenuItem(
		child: Text("Text"), // Uses the TextStyle.labelLarge style
	),
	PopupMenuItem(
		child: ListTile(
			title: Text("ListTile"), // Uses the TextStyle.bodyLarge style when it should've been the TextStyle.labelLarge style
		),
	)
]
```

**Comment by huycozy** [comment]
Ah, I see the issue now. I was not able to identify this because your original sample code has overrided `labelLarge` style to ListTile's title to work around this. I think you should mention expected "default" style in the original comment (same as your [comment above](https://github.com/flutter/flutter/issues/128576#issuecomment-1588634981))

M3 specs: https://m3.material.io/components/menus/specs#ad796ca6-3d66-4e7e-9322-c0d93bff5423

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.10.4, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.10.4 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 682aa387cf (2 days ago), 2023-06-05 18:04:56 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 964AY0WL20 • android-arm64  • Android 12 (API 32)
    • macOS (desktop)   • macos      • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 114.0.5735.106

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.12.0-3.0.pre.81, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.12.0-3.0.pre.81 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f8000aa75 (78 minutes ago), 2023-06-12 21:51:08 -0400
    • Engine revision d02b15ef34
    • Dart version 3.1.0 (build 3.1.0-201.0.dev)
    • DevTools version 2.24.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.79.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (4 available)
    • Pixel 3a (mobile) • 964AY0WL20                               • android-arm64  • Android 12 (API 32)
    • iPhone (mobile)   • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.7.2 19H218
    • macOS (desktop)   • macos                                    • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)      • chrome                                   • web-javascript • Google Chrome 114.0.5735.106

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by TahaTesser** [comment]
Hi @Curstantine 
This is working as expected. `ListTile` and `PopupMenuItem` are two separate widgets using their correct default text styles.

> `ListTile` with a `title` style of `TextTheme.bodyLarge`. The defaults of the `ListTile` is not being overriden by the `PopupMenuItem` when used with it.

`PopupMenuItem` isn't supposed to detect differences and override their style. Please share a link to specs if this is incorrect



>  Use a `ListTile` inside `PopupMenuItem` as suggested in the comments to include a leading icon.

Check out [CheckedPopupMenuItem](https://master-api.flutter.dev/flutter/material/CheckedPopupMenuItem-class.html) to achieve.  If you can wanna still use ListTile, you can provide a custom style.


Closing as this isn't actionable.

**Comment by Curstantine** [comment]
@TahaTesser 
[`CheckedPopupMenu`](https://master-api.flutter.dev/flutter/material/CheckedPopupMenuItem-class.html) still uses the incorrect text style, and more to the point, it does not allow you to specify your own icon over the internal checkmark icon. [Refer to the code posted in this comment to compare](https://github.com/flutter/flutter/issues/128576#issuecomment-1587237410).

The [`PopupMenuItem`](https://api.flutter.dev/flutter/material/PopupMenuItem-class.html) documentation mentions that:
> Typically the [child](https://api.flutter.dev/flutter/material/PopupMenuItem/child.html) of a [PopupMenuItem](https://api.flutter.dev/flutter/material/PopupMenuItem-class.html) is a [Text](https://api.flutter.dev/flutter/widgets/Text-class.html) widget. More elaborate menus with icons can use a [ListTile](https://api.flutter.dev/flutter/material/ListTile-class.html).

**Comment by TahaTesser** [comment]
`‎CheckedPopupMenuItem‎` is a wrapper on `ListTile`.  As the name suggests, it provides a check icon. 

> The [`PopupMenuItem`](https://api.flutter.dev/flutter/material/PopupMenuItem-class.html) documentation mentions that:
> > Typically the [child](https://api.flutter.dev/flutter/material/PopupMenuItem/child.html) of a [PopupMenuItem](https://api.flutter.dev/flutter/material/PopupMenuItem-class.html) is a [Text](https://api.flutter.dev/flutter/widgets/Text-class.html) widget. More elaborate menus with icons can use a [ListTile](https://api.flutter.dev/flutter/material/ListTile-class.html) 

You can use  `ListTile` and customize the leading icon and style as the doc suggests.

**Comment by Curstantine** [comment]
But that would imply you modify every item in your list with a new text style if you want to have an icon that is not a checkmark. Even then, as I mentioned earlier, even `CheckedPopupItem` is using the incorrect text style. It is using the style of the default ListTile instead of the one specified in menu specification.

Link to the related spec: https://m3.material.io/components/menus/specs#ad796ca6-3d66-4e7e-9322-c0d93bff5423

**Comment by TahaTesser** [comment]
A

**Comment by TahaTesser** [comment]
That sounds fair. It is a little too tide to `ListTile`.  
Now I can also there is an animation for the leading icon. If we use `ListTile`, we have to copy the animation too.

I'll fix this.

**Comment by TahaTesser** [comment]
Fixing this for Material 3 specs will also bring quality improvements.

**Comment by TahaTesser** [comment]
(blocked by https://github.com/flutter/flutter/issues/128877)
