### ISSUE TITLE
Add AppKitView (and related render, service layer support) to framework

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#128519]
For macOS PlatformView support, we'll need to add a dedicated AppKit view widget similar to UiKitView, as well as the related render layer support (RenderAppKitView) and service layer support.

Part of https://github.com/flutter/flutter/issues/41722

**Comment by wanjm** [comment]
how many work left for this issue?
and is this issue the last work for https://github.com/flutter/flutter/issues/41722

**Comment by yaakovschectman** [comment]
There is an in progress PR to add a superclass that can be inherited by iOS and macOS platform views, currently awaiting approval. Once that's merged, we can add the AppKitView classes.

**Comment by wanjm** [comment]
when will AppKitView be added? and when will platform view for macos be ready?

**Comment by cbracken** [comment]
@yaakovschectman are we good to close this now?

**Comment by yaakovschectman** [comment]
Ah, yes I think so.
