### ISSUE TITLE
[Impeller] Investigate potential lack of coherent memory allocations on Android devices.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#128556]
The host buffers we use on the Impeller Vulkan backend try to request coherent host memory so that we don't have to explicitly flush. From experimentation, we weren't actually getting coherent host memory back which was the cause of the corruption in https://github.com/flutter/flutter/issues/124040 . This can be fixed locally by adding an explicit flush, which is safe to do.

Switching the VMA flags we are setting from requested to required results in a failed allocation.

> Break on 'ImpellerValidationBreak' to inspect point of failure: Unable to allocate a device buffer: ErrorFeatureNotPresent

That said, we don't really ever expose the device buffer ptr so it should be safe to insert a flush.

**Comment by chinmaygarde** [comment]
I think this can be closed. We no longer request it and explicitly flush dirty pages anyway.
