### ISSUE TITLE
Firestore get() support

### ISSUE THREAD

**Issue by lschmierer** [flutter/flutter#12866]
In order to get data directly from the Firestore database, the `get` method is needed.

`snapshots` returns cached data immediately (and updated data from network maybe later), but in some use cases it is necessary to get server data directly.

**Comment by Hixie** [comment]
cc @collinjackson @kroikie

**Comment by dragonfax** [comment]
Its also not possible to check if a document is already created, without the get(). Snapshot stream will just never return anything.

We also need DocumentSnapshot.exists() to go along with this.

**Comment by kroikie** [comment]
@lschmierer

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/945. Any further collaboration will be done there.
