### ISSUE TITLE
[flutter_image] Add example app

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#128699]
Currently (as highlighted in the Scores on pub.dev) we don't provide any kind of example doc or app for `flutter_image`. We should have a simple example app for it that demonstrates its functionality.

**Comment by IsmailAbdirahman** [comment]
I would like to be assigned this

**Comment by stuartmorgan** [comment]
Per our docs "If you don't have permissions to assign yourself an issue you want to work on, don't worry about it, just submit the PR".

**Comment by sompuradhruv** [comment]
hey I can help fix this

**Comment by Kavan2003** [comment]
I want to solve this Issue

**Comment by stuartmorgan** [comment]
Anyone interested in adding an example is welcome to send a PR; it's not necessary to comment here first (unless you have specific questions about the task.)

**Comment by Nitin-Poojary** [comment]
To fix this issue, do I need to add an example app [here](https://github.com/flutter/packages/tree/main/packages/flutter_image)?

**Comment by Nitin-Poojary** [comment]
@stuartmorgan Are there any testing requirements for the example app?

**Comment by stuartmorgan** [comment]
Examples should have at least some minimal tests that they work; we've had issues in the past with bugs in examples, and want to have the test framework already in place for adding tests when fixing those bugs.

**Comment by Nitin-Poojary** [comment]
While exploring options to test NetworkImageWithRetry, I encountered packages like network_image_mock and mocktail_image_network. However, these packages are designed for Image.network and NetworkImage, and don't directly address testing for NetworkImageWithRetry. I'm wondering how I can test NetworkImageWithRetry. Would it be appropriate to ask this question on Discord or?

**Comment by stuartmorgan** [comment]
@Nitin-Poojary I'm not sure what you are asking exactly. Tests for the example should be testing that the example works, not that the longest works.

**Comment by Nitin-Poojary** [comment]
@stuartmorgan I'm a bit confused about the testing aspect. The purpose of the example app is to showcase how to use the NetworkImageWithRetry widget provided by the flutter_image package, correct? So, to test the app, would it involve verifying if NetworkImageWithRetry successfully returns an Image or throws an exception? Or am I misunderstanding the something? I would appreciate clarification on this matter.

**Comment by stuartmorgan** [comment]
The test of the app should ensure that the example app is doing what the example app is supposed to do, not that the library is working (that's what other, existing, tests are for). For instance, an example app that shows an image should have a simple test that it's showing an image, because if it's not then the example app isn't doing what it's supposed to do.

For a very simple app, the test will also be very simple; it's essentially a sanity check that the app works. Some example apps are more complicated, and need more complex tests, but most don't.
