### ISSUE TITLE
version：3.10.+    iOS crash

### ISSUE THREAD

**Issue by StephentTom** [flutter/flutter#128675]
### Is there an existing issue for this?

- [ ] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [ ] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Back-and-forth interface

### Expected results

iOS：reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'

### Actual results

iOS：reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'

### Code sample

。。。

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.10.1, on Microsoft Windows [versÆo 10.0.22621.1778], locale pt-BR)
    • Flutter version 3.10.1 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (4 weeks ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\Pedro\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Ferramentas de Build do Visual Studio 2019 16.11.26)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Ferramentas de Build do Visual Studio 2019 version 16.11.33529.622
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.79.0)
    • VS Code at C:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.66.0

[✓] VS Code (version 1.80.0-insider)
    • VS Code at C:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code Insiders
    • Flutter extension version 3.66.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [versÆo 10.0.22621.1778]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 114.0.5735.110
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 114.0.1823.43

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by OneupLee** [comment]
same problem when i use mapbox_map_flutter plugin

**Comment by darshankawar** [comment]
Looking at the crash log, it seems to be similar to https://github.com/flutter/flutter/issues/127489 which has been fixed in master, so please switch to latest master and run your scenario again to see the fix working.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.
