### ISSUE TITLE
[Impeller] Vulkan Fidelity: clip boundaries seem ... wrong?

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#128605]
Is this a stencil issue? or a sampling issue? hard to tell. Look at how wavy the arc'd clip path is.

![flutter_06](https://github.com/flutter/flutter/assets/8975114/1ecd03dd-689f-4051-9ef6-dc267f4d88b8)

**Comment by whiskeyPeak** [comment]
I get this when my app is initially launched and connected to my Linux machine. Simply closing and opening the app again removes those weird artifacts.
