### ISSUE TITLE
M3 Search scroll behavior 

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter#128695]
https://m3.material.io/components/search/guidelines#b340d738-9c8a-4258-876e-b4ac892616c1 describes an option for showing/hiding the search bar when scrolling.

https://github.com/flutter/flutter/assets/6655696/7159369e-b84d-41d1-8840-8841a414db1f

It would be nice if the component supported this, or alternatively, if a code sample was provided to achieve this effect. cc @QuncCccccc

**Comment by QuncCccccc** [comment]
Hi @guidezpl, we have an example examples/api/lib/material/search_anchor/search_anchor.1.dart to show the scroll behavior:)

**Comment by guidezpl** [comment]
wonderful, thanks! I missed it
