### ISSUE TITLE
Request for Markdown Preview Feature during Editing in Flutter 

### ISSUE THREAD

**Issue by yaviral17** [flutter/flutter#128682]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

> ## Request for Markdown Preview Feature during Editing in Flutter

Currently, when using Flutter, **there is support for Markdown rendering and previewing**. However, the **lack of a dynamic preview feature while editing** can be cumbersome and hinder the workflow. I believe that **introducing a live Markdown preview during the editing phase** would greatly improve the experience.

With this feature, users would be able to see the visual representation of their Markdown content as they type and make changes in real-time. This functionality would provide an immediate and visual feedback loop, enabling users to quickly iterate and refine their Markdown content, resulting in a more efficient and error-free editing process.

I believe that the introduction of a Markdown preview feature during editing in Flutter would be highly appreciated by developers and would significantly improve the editing workflow.

### Proposal

I am writing to propose a new feature for Flutter that would greatly enhance the editing experience for developers working with Markdown in their applications. Specifically, I would like to have the implementation of a real-time Markdown preview functionality during the editing process. I don't thing this could be fixed by any package as here we have to edit and render at the same time . 

### Example

> ![ezgif-1-4a3c580e2e](https://github.com/flutter/flutter/assets/58760825/965b2c51-ad5e-4dbe-a026-4c3089f0bad2)

**Comment by huycozy** [comment]
Thanks for the report, @yaviral17 

This is a known issue being tracked at https://github.com/flutter/flutter/issues/86465. Closing this issue as a duplicate, so please follow up on it for further updates.
