### ISSUE TITLE
Getting validation issues because of image_picker_ios for my flutter app after uploading to App Store. I'm using Xcode 15 beta on macOS sanoma

### ISSUE THREAD

**Issue by dev-naiksan** [flutter/flutter#128639]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create project archive which uses image_picker plugin
2. Try publishing it on App Store

### Expected results

Successfully publish on App Store

### Actual results

Received an email from Apple Appstore team.

_Dear Developer,
We identified one or more issues with a recent delivery for your app, "App-Name" 3.1.5 (3106). Please correct the following issues, then upload again.
ITMS-90338: Non-public API usage - The app links to non-public libraries in Frameworks/image_picker_ios.framework/image_picker_ios: /System/Library/PrivateFrameworks/AVFCapture.framework/AVFCapture, /System/Library/PrivateFrameworks/AVFCore.framework/AVFCore. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/
Best regards,
The App Store Team_

### Code sample

<details><summary>Code sample</summary>

```dart
//
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.0, on macOS 14.0 23A5257q darwin-arm64, locale en-IN)
    • Flutter version 3.10.0 on channel stable at /Users/naiksan/Flutter/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (5 weeks ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/naiksan/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/naiksan/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Community Edition (version 2023.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 73.0.4
    • Dart plugin version 231.8109.91

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 14.0 23A5257q darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 109.0.5414.87

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by stuartmorgan** [comment]
> ITMS-90338: Non-public API usage - The app links to non-public libraries in Frameworks/image_picker_ios.framework/image_picker_ios: /System/Library/PrivateFrameworks/AVFCapture.framework/AVFCapture, /System/Library/PrivateFrameworks/AVFCore.framework/AVFCore. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions

You'll need to follow up with Apple to get more information here. They refer to possible method name collisions with "the private Apple APIs listed above", but there is no list of method names there, only frameworks. If we happen to have a method named the same thing as something in a private AVFoundation framework, we need to know what that method name is so that we can rename it.

**Comment by stuartmorgan** [comment]
@TimBudarick Yours is coming from the `scan` plugin, which is a third-party plugin. You'll need to follow up with its developers.

**Comment by stuartmorgan** [comment]
@dev-naiksan Is the version of Xcode in your `doctor` output (14.3.1) the version you published with, or did you use a beta?

**Comment by dev-naiksan** [comment]
Yes. I was not aware the beta Xcode restrictions. Sorry for the trouble guys. Thanks for the responses. Closing this.

**Comment by EloWeld** [comment]
But sorry. What I need to do if I already updated my iPhone to IOS 17? If it will be Xcode stable version - there are an error "couldn't locate device support files". Only with Xcode 15 I can build an app.
