### ISSUE TITLE
An exception occurs under linux

### ISSUE THREAD

**Issue by lwylwc** [flutter/flutter#128686]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

In the gnome linux environment, the following phenomena will occur. I think flutter has opened too many network asynchronous tasks when loading pictures. Can the next version add an API to control concurrent picture downloads?
![DINGTALK_IM_486911070](https://github.com/flutter/flutter/assets/15844588/615e21ed-39d8-4c5c-bfa6-a277afefee60)

### Expected results

If under the linux arm chip architecture, under the gnome desktop environment, if you load a large number of pictures from 50 to 100, there will be an interface that cannot continue to execute the task and needs to wait,But there is no such problem at all on other platforms

### Actual results

![DINGTALK_IM_486911070](https://github.com/flutter/flutter/assets/15844588/19874ecf-8a16-4e9f-9179-227ada4b1fee)
Swipe quickly and the above situation will appear

### Code sample

<details><summary>Code sample</summary>
 ListView.builder(
        itemCount: 100,
        itemBuilder: (BuildContext context, int index) {
          //子Widget
          return Container(
            height: 50,
            child: Image.network("Different web image URLs"),
          );
        });

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>
![DINGTALK_IM_486911070](https://github.com/flutter/flutter/assets/15844588/13535549-d698-4adc-82d3-ad4703ca27d6)

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

</details>
![DINGTALK_IM_377370628](https://github.com/flutter/flutter/assets/15844588/9e20338c-9daa-42a5-868c-c6ea6f5a7ab8)

**Comment by lwylwc** [comment]
[✓] Flutter (Channel stable, 3.0.5, on Orange OS 5.10.110-4+, locale en_US.UTF-8)
    • Flutter version 3.0.5 at /home/l/Downloads/devlop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (11 months ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 15.0.7
    • cmake version 3.26.4
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[!] Flutter IDE Support (No supported IDEs installed)
    • IntelliJ - https://www.jetbrains.com/idea/
    • Android Studio - https://developer.android.com/studio/
    • VS Code - https://code.visualstudio.com/

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-arm64 • Orange OS 5.10.110-4+

[✓] HTTP Host Availability
<img width="603" alt="截屏2023-06-13 13 49 46" src="https://github.com/flutter/flutter/assets/15844588/c5895395-1002-442f-8a3e-846e74f3b640">

    • All required HTTP hosts are available

**Comment by lwylwc** [comment]
@darshankawar  flutter doctor
[✓] Flutter (Channel stable, 3.0.5, on Orange OS 5.10.110-4+, locale en_US.UTF-8)
    • Flutter version 3.0.5 at /home/l/Downloads/devlop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (11 months ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 15.0.7
    • cmake version 3.26.4
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[!] Flutter IDE Support (No supported IDEs installed)
    • IntelliJ - https://www.jetbrains.com/idea/
    • Android Studio - https://developer.android.com/studio/
    • VS Code - https://code.visualstudio.com/

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-arm64 • Orange OS 5.10.110-4+

[✓] HTTP Host Availability
    • All required HTTP hosts are available
<img width="603" alt="截屏2023-06-13 13 49 46" src="https://github.com/flutter/flutter/assets/15844588/1b99cb3b-0edf-47f3-b418-0fab4021cba1">

**Comment by lwylwc** [comment]
@darshankawar flutter  run --verbose
[f0vi24Ff.txt](https://github.com/flutter/flutter/files/11731404/f0vi24Ff.txt)

**Comment by darshankawar** [comment]
@lwylwc 
Please upgrade your flutter version to latest stable and run your scenario again to see if the issue persists or not.

**Comment by lwylwc** [comment]
@darshankawar  flutter doctor has a problem
Snapshot not compatible with the current VM configuration: the snapshot requires 'release no-code_comments no-dwarf_stack_traces_mode lazy_dispatchers no-dedup_instructions no-asserts use_field_guards use_osr no-branch_coverage x64 linux no-compressed-pointers null-safety' but the VM has 'release no-code_comments no-dwarf_stack_traces_mode lazy_dispatchers no-dedup_instructions no-asserts use_field_guards use_osr no-branch_coverage arm64 linux no-compressed-pointers null-safety'

**Comment by lwylwc** [comment]
@darshankawar I have replaced arm's dart-sdk

**Comment by darshankawar** [comment]
@lwylwc Ok, what does that mean ? Are you still facing issue running flutter doctor ?

**Comment by lwylwc** [comment]
@darshankawar Flutter doctor failed after using the new SDK ,

**Comment by lwylwc** [comment]
@darshankawar My Linux architecture is arm64. Where can I download the corresponding SDK version

**Comment by darshankawar** [comment]
https://docs.flutter.dev/get-started/install/linux#get-sdk Check this and see if it helps.
