### ISSUE TITLE
Use "Chrome for Testing" for unit tests instead of Chromium continuous builds

### ISSUE THREAD

**Issue by eyebrowsoffire** [flutter/flutter#128626]
The Chrome team is now shipping a special build of Chrome specifically for testing: https://googlechromelabs.github.io/chrome-for-testing/

This solves many of the existing difficulties with using Chromium continuous builds, so we should try to migrate. This version won't autoupdate, and we can use official releases for each platform, instead of the "closest build" we could find in the continuous builds archive. This also, I believe, will make it easier to create an autoroller for.

**Comment by ditman** [comment]
Chromedriver is now available in the downloads, and they have a very nice JSON endpoint so we can grab the download URLs per version, platform, etc...

(And I duplicated this issue, like a fool! https://github.com/flutter/flutter/issues/130859)

**Comment by eyebrowsoffire** [comment]
Fixed with https://github.com/flutter/engine/pull/46683 and https://github.com/flutter/flutter/pull/136214
