### ISSUE TITLE
auto-download of clang-format

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#12864]
re: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md

I believe this repo relies on auto-formatting!?

Is the right command to run `pub global run flutter_plugin_tools format` ?

What does that require to run? Mine fails trying to locate 'clang-format'

**Comment by mit-mit** [comment]
cc @goderbauer @collinjackson

**Comment by goderbauer** [comment]
That's the right command.

You need clang-format-5 in your path or you can pass its location via the `--clang-format` flag. In addition to that, you need the latest dart in your path and I believe that's it.

**Comment by mit-mit** [comment]
Where does one get clang-format?

**Comment by goderbauer** [comment]
Personally, I am now using the one that comes with the engine (located at `engine/src/buildtools/mac-x64/clang/bin/clang-format`). Previously, I used one installed with `brew`.

**Comment by goderbauer** [comment]
It might be worth adding a download step to flutter_plugin_tools that downloads the correct clang-format from wherever the engine is downloading it from during `gclient sync`. Similarly to how it already downloads the java formatter.

**Comment by mit-mit** [comment]
That sounds like a good solution.

**Comment by recastrodiaz** [comment]
On a Mac, I installed clang-format-5.0 with https://github.com/Homebrew/homebrew-core/pull/27694:

```SH
brew install https://raw.githubusercontent.com/DennisOSRM/homebrew-core/813160d88fc1101aa173c745e031e251acbb96d9/Formula/clang-format@5.rb
```

I can then run the format tool with:
```SH
pub global run flutter_plugin_tools format --clang-format=clang-format-5.0
```

**Comment by dustin-graham** [comment]
@recastrodiaz thanks!

**Comment by stuartmorgan** [comment]
Adding `cipd` support to the tool for this would add a lot of complexity for relatively little benefit. I think it's fine to require people to either install `clang-format`, or use the patch command that the CI outputs.
