### ISSUE TITLE
Cannot full screen in android device

### ISSUE THREAD

**Issue by hatungpsg** [flutter/flutter#128661]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. use webview for a video from vimeo
2. fullscreen button is disappear in android device but working fine in IOS device
3. Based on https://help.vimeo.com/hc/en-us/articles/12425790245777-Troubleshoot-Fullscreen-button-missing-from-the-player, it's due to full screen mode cannot be activated.

### Expected results

Full screen button should be there

### Actual results

Full screen button is disappear

### Code sample

<details><summary></summary>

```dart
return Scaffold(
      appBar: HomeScreenAppBar('Courses'),
      body: SizedBox(
          width: double.infinity,
          height: double.infinity,
          child: IgnorePointer(
            ignoring: isLoading,
            child: Stack(
              children: [
                WebView(
                  initialUrl:
                      "https://www.youtube.com/watch?v=cx_y3uHnnaY",
                  javascriptMode: JavascriptMode.unrestricted,
                  onPageFinished: (value) async {
                    if (WebViewControllerObject.webViewControllers.length >
                        widget.index) {
                      WebViewControllerObject.webViewControllers[widget.index]
                          .runJavascript(
                              "if(document.getElementsByTagName('header')[0]){document.getElementsByTagName('header')[0].style.display='none'}"
                              "if(document.getElementsByClassName('bde-section-80292-100 bde-section')[0]){document.getElementsByClassName('bde-section-80292-100 bde-section')[0].style.display='none'}"
                              'document.documentElement.style.touchAction = "pan-x pan-y";'
                              'document.addEventListener("gesturestart", function (e) { e.preventDefault(); });'
                              'document.addEventListener("dblclick", function (e) { e.preventDefault(); });');
                    }
                    await _checkIfBack();
                    setState(() {
                      isLoading = false;
                    });
                  },
                  navigationDelegate: (NavigationRequest request) {
                    url = request.url;

                    if (request.url.contains("wa.link") ||
                        request.url.contains("wa.me") ||
                        request.url.contains("whatsapp")) {
                      final Uri _url = Uri.parse(request.url);
                      _launchUrl(_url);
                      return NavigationDecision.prevent;
                    }

                    return NavigationDecision.navigate;
                  },
                  onProgress: (progress) {
                    if (!url.contains("wa.link") &&
                        !url.contains("wa.me") &&
                        !url.contains("whatsapp")) {
                      setState(() {
                        isLoading = true;
                      });
                    }
                  },
                  onWebViewCreated: (WebViewController webViewController) {
                    WebViewControllerObject.webViewControllers
                        .insert(widget.index, webViewController);
                  },
                ),
                isLoading
                    ? Container(
                        color: Colors.white,
                        child: Container(
                          color: dark ? Colors.black : Colors.white,
                          child: const Center(child: CircularProgressIndicator()),
                        ),
                      )
                    : Container(),
              ],
            ),
          )),
    );
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>
in android, click on full screen button won't give any response.
https://github.com/flutter/flutter/assets/88617481/ade50559-2fb3-4b0f-a9ce-28bed71eda09

this is on iphone
https://github.com/flutter/flutter/assets/88617481/b0f2a8a5-7777-4261-b8a8-1df3a6815d82

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘
[√] Flutter (Channel stable, 3.7.1, on Microsoft Windows [Version 10.0.22000.1936], locale en-US)
    • Flutter version 3.7.1 on channel stable at C:\Users\hatungwo\Downloads\flutter_windows_3.7.1-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7048ed95a5 (4 months ago), 2023-02-01 09:07:31 -0800
    • Engine revision 800594f1f4
    • Dart version 2.19.1
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:/Users/hatungwo/AppData/Local/Android/Sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = C:/Users/hatungwo/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version openjdk version "11.0.13" 2021-10-19
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32929.385
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version openjdk version "11.0.13" 2021-10-19

[√] VS Code (version 1.79.0)
    • VS Code at C:\Users\hatungwo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.66.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.1936]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 114.0.5735.110
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 114.0.1823.43

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
Process finished with exit code 0
```

</details>

**Comment by MSatyam-Mishra** [comment]
Can you share code.

**Comment by dam-ease** [comment]
Hi @hatungpsg. Thanks for filing this issue. Can you try upgrading to the latest flutter `stable` version to verify this issue still persist??
If it does, kindly share a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) to help triage this further.
Thank you.

**Comment by hatungpsg** [comment]
> Please share your code

Code updated. Please take a look

**Comment by dam-ease** [comment]
Hi @hatungpsg. Are you using the latest version of the `webview_flutter` package? Also, kindly try reproducing this with the latest `stable` version and the latest version of the `webview_flutter` package to confirm this issue still persists.

**Comment by hatungpsg** [comment]
> Hi @hatungpsg. Are you using the latest version of the `webview_flutter` package? Also, kindly try reproducing this with the latest `stable` version and the latest version of the `webview_flutter` package to confirm this issue still persists.

Hi @dam-ease , i just have a chance to use latest webview_flutter. 
When i use latest webview_flutter, i cannot even see the video appear. 

Here is my code for 4.2.2 webview flutter
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(
    const MaterialApp(
      home: WebViewApp(),
    ),
  );
}

class WebViewApp extends StatefulWidget {
  const WebViewApp({super.key});

  @override
  State<WebViewApp> createState() => _WebViewAppState();
}

class _WebViewAppState extends State<WebViewApp> {
  late final WebViewController controller;
  String url = 'https://www.youtube.com/watch?v=cx_y3uHnnaY';

  @override
  void initState() {
    controller = WebViewController()
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setNavigationDelegate(
        NavigationDelegate(
          onNavigationRequest: (navigation) {
            if (navigation.url != url) {
              return NavigationDecision.prevent;
            }
            return NavigationDecision.navigate;
          },
        ),
      )
      ..loadRequest(Uri.parse(url));
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Flutter WebView'),
      ),
      body: WebViewWidget(
        controller: controller,
      ),
    );
  }
}

**Comment by dam-ease** [comment]
Hi @hatungpsg. This might be similar to https://github.com/flutter/flutter/issues/27101. Can you confirm it is?

**Comment by dam-ease** [comment]
Hi @hatungpsg. This might be similar to https://github.com/flutter/flutter/issues/27101. Can you confirm it is?

**Comment by hatungpsg** [comment]
> Hi @hatungpsg. This might be similar to #27101. Can you confirm it is?

Yea. I think it's the same. 
I fix the full screen issue by using flutter_inappwebview. 
would like to know is that a plan to fix full screen issue in webview_flutter?

**Comment by dam-ease** [comment]
Hi @hatungpsg. Thanks for confirming. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you.
