### ISSUE TITLE
Want launchUrl() to download a file

### ISSUE THREAD

**Issue by jgfoster** [flutter/flutter#128615]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I would like to link to a file and have it downloaded instead of displayed in a new tab.

### Proposal

Support the [`download`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attributes) feature available with the `<a>` tag in HTML.

**Comment by stuartmorgan** [comment]
`url_launcher` is just intended for opening URLs, so downloading is out of scope. That's something that would be best be handled by a separate package; it's likely that there are already packages that have that functionality.
