### ISSUE TITLE
[Impeller] Color::Blend appears to have bugs and only be used in tests

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#128606]
@jonahwilliams @bdero fyi

We should remove this if it's really test-only.

If it's not test-only, we should fix it. Comparing, for example, the `kOverlay` implementation to skia:

Impeller:

```cpp
      return apply_rgb_srcover_alpha([&](auto s, auto d) {
        if (d * 2 < dst.alpha) {
          return 2 * s * d;
        }
        return src.alpha * dst.alpha - 2 * (dst.alpha - s) * (src.alpha - d);
      });
```

Skia:

```cpp
                return apply_rgb_srcover_a([&](auto s, auto d) {
                    return mma(s, 1-dst.a, d, 1-src.a) +
                           select(two(d) <= dst.a,
                                  two(s * d),
                                  src.a * dst.a - two((dst.a - d) * (src.a - s)));
                });
```

Skia has `dst.a - d` where we have `dst.alpha - s` (and a similar swap in the next one). Skia also has `if 2 * d <= dst.a` where we have `if 2 * d < dst.alpha` (so we're missing the equals part of less than or equals).

**Comment by dnfield** [comment]
@JsouLiang fyi as well since I think you did the original implementation of this.

**Comment by jonahwilliams** [comment]
See https://github.com/flutter/engine/pull/42692

**Comment by bdero** [comment]
Nice find @dnfield !

**Comment by chinmaygarde** [comment]
So we can remove these right?

**Comment by dnfield** [comment]
@bdero is using them for something that is currently in flight AFAIU.

**Comment by bdero** [comment]
We will need to use these for optimization purposes while fixing https://github.com/flutter/flutter/issues/127232.
