### ISSUE TITLE
[CP] rename generated asset manifest file back to AssetManifest.bin (from AssetManifest.smcbin)

### ISSUE THREAD

**Issue by andrewkolos** [flutter/flutter#128622]
### Issue Link

https://github.com/flutter/flutter/issues/128230

### Commit Hash

cfe4fed

### Target

stable

### PR Link

https://github.com/flutter/flutter/pull/128621

### Changelog Description

Renames the asset manifest (an internal file generated by the tool and used by the framework to resolve assets) from `AssetManifest.smcbin` back to `AssetManifest.bin`. This plays more nicely with web servers.

### Impacted Users

all web developers, at least those serving their site using Microsoft IIS

### Impact Description

Flutter web apps served on Microsoft IIS won't be able to load and display image assets unless the server is explicitly configured to serve `AssetManifest.smcbin`. This is because `.smcbin` is not a widely-recognized file extension, unlike `.bin`.

### Workaround

Yes, see https://github.com/flutter/flutter/issues/128230#issuecomment-1580277570 for an example.

### Risk

medium

### Test Coverage

yes

### Validation Steps

1. Build a flutter web app that displays an image.
2. Serve the app through IIS (should be available on Windows by default).
3. Access the site through a web browser and make sure the image the asset is displayed properly.

**Comment by andrewkolos** [comment]
CC @jonahwilliams @eliasyishak

**Comment by jonahwilliams** [comment]
LGTM
