### ISSUE TITLE
Error in Intellij IDEA 2017.2.5 after press "control/s"

### ISSUE THREAD

**Issue by micrcx** [flutter/flutter#12863]
This internal crash sometimes appears in the onConsole window while editing the code in Intellij IDEA 2017.2.5 after you press "control/s" bottons.

```
Initializing hot reload...
Unable to hot reload. No instance of Flutter is currently running.
Unhandled exception:
Bad state: No element
#0      List.first (dart:core-patch/array.dart:160)
#1      HotRunner._reloadSources.<anonymous closure> (package:flutter_tools/src/run_hot.dart:504)
#2      _rootRunUnary (dart:async/zone.dart:1128)
#3      _CustomZone.runUnary (dart:async/zone.dart:1012)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:129)
#5      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#6      _Future._propagateToListeners (dart:async/future_impl.dart:665)
#7      _Future._completeWithValue (dart:async/future_impl.dart:478)
#8      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:510)
#9      _rootRun (dart:async/zone.dart:1120)
#10     _CustomZone.run (dart:async/zone.dart:1001)
#11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:928)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)
```

**Comment by Hixie** [comment]
cc @mit-mit @devoncarew

**Comment by mit-mit** [comment]
cc @rmacnak-google

**Comment by micrcx** [comment]
I'm sorry to be late with the reply. I've slow reaction. In principle, this crash can be ignored, you just need to re-run the application for execution.

**Comment by mit-mit** [comment]
Glad to hear that you were able to recover from this @micrcx. But we should fail more elegantly and not crash like this, so i'm going to reopen the bug.

**Comment by micrcx** [comment]
/home/micrcx/flutter/bin/flutter --no-color doctor
[✓] Flutter (on Linux, locale en_US.UTF-8, channel alpha)
    • Flutter at /home/micrcx/flutter
    • Framework revision e8aa40eddd (3 weeks ago), 2017-10-17 15:42:40 -0700
    • Engine revision 7c4142808c
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /home/micrcx/Android/Sdk
    • Platform android-26, build-tools 26.0.1
    • Java binary at: /home/micrcx/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /home/micrcx/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 18.4
    • Dart plugin version 172.4343.25

[✓] Connected devices
    • LG V520 • LGV5203c426e47 • android-arm • Android 7.0 (API 24)

Process finished with exit code 0

**Comment by mit-mit** [comment]
@devoncarew should this be ported to the intellij tracker?

**Comment by devoncarew** [comment]
It looks like the Flutter app is no longer running, but that info hasn't been fully communicated to all of flutter_tools (it hasn't closed the connection to IntelliJ, or sent IntelliJ the close event). I'm not sure how this would have happened, but my guess is that this is a flutter_tools issue.

**Comment by Hixie** [comment]
Leaving in current milestone; hot reload trust issue.

**Comment by Hixie** [comment]
Closing. There is insufficient information to reproduce and we haven't heard of other reports. Please file a new bug if you see this again.
