### ISSUE TITLE
[path_provider] [Android] Path Provider not working when excluding `com.google.android.gms` and another dependency relies on `com.google.android.gms:play-services-location`

### ISSUE THREAD

**Issue by Myzel394** [flutter/flutter#128691]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

**You can use https://github.com/Myzel394/flutter-path_provider-bug to get a minimum reproducible**

1. Create new Flutter project
2. Add `path_provider`
3. Add any other dependency that relies on `com.google.android.gms:play-services-location`, in my case, it's [`nearby_connections`](https://pub.dev/packages/nearby_connections) - you can see that it relies on that dependency here: https://github.com/mannprerak2/nearby_connections/blob/master/android/build.gradle#L40
4. Exclude `com.google.android.gms` in `android/app/build.gradle`, like I did here: https://github.com/Myzel394/flutter-path_provider-bug/blob/master/android/app/build.gradle#L75
5. Try calling `getTemporaryDirectory`

### Expected results

The path should be returned correctly. **Note that when you do not have a dependency that relies on `com.google.android.gms:play-services-location` and you exclude `com.google.android.gms`, `path_provider` works fine**.

### Actual results

The following error is thrown:

```console
E/flutter ( 4707): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 4707): #0      PathProviderApi.getTemporaryPath (package:path_provider_android/messages.g.dart:44:7)
E/flutter ( 4707): <asynchronous suspension>
E/flutter ( 4707): #1      getTemporaryDirectory (package:path_provider/path_provider.dart:55:24)
E/flutter ( 4707): <asynchronous suspension>
E/flutter ( 4707): #2      _MyHomePageState.build.<anonymous closure> (package:bug/main.dart:86:35)
E/flutter ( 4707): <asynchronous suspension>
E/flutter ( 4707): 
```

### Code sample

You can find the minimum reproducible here: https://github.com/Myzel394/flutter-path_provider-bug

### Logs

<details><summary>Logs</summary>

```console
W/1.ui    ( 4707): type=1400 audit(0.0:72390): avc: granted { execmem } for scontext=u:r:untrusted_app:s0:c20,c257,c512,c768 tcontext=u:r:untrusted_app:s0:c20,c257,c512,c768 tclass=process app=com.example.bug
W/1.ui    ( 4707): type=1400 audit(0.0:72391): avc: granted { execmem } for scontext=u:r:untrusted_app:s0:c20,c257,c512,c768 tcontext=u:r:untrusted_app:s0:c20,c257,c512,c768 tclass=process app=com.example.bug
W/1.ui    ( 4707): type=1400 audit(0.0:72392): avc: granted { execmem } for scontext=u:r:untrusted_app:s0:c20,c257,c512,c768 tcontext=u:r:untrusted_app:s0:c20,c257,c512,c768 tclass=process app=com.example.bug
W/1.ui    ( 4707): type=1400 audit(0.0:72393): avc: granted { execmem } for scontext=u:r:untrusted_app:s0:c20,c257,c512,c768 tcontext=u:r:untrusted_app:s0:c20,c257,c512,c768 tclass=process app=com.example.bug
W/1.ui    ( 4707): type=1400 audit(0.0:72394): avc: granted { execmem } for scontext=u:r:untrusted_app:s0:c20,c257,c512,c768 tcontext=u:r:untrusted_app:s0:c20,c257,c512,c768 tclass=process app=com.example.bug
E/cutils-trace( 4707): Error opening trace file: No such file or directory (2)
W/1.ui    ( 4707): type=1400 audit(0.0:72399): avc: granted { execmem } for scontext=u:r:untrusted_app:s0:c20,c257,c512,c768 tcontext=u:r:untrusted_app:s0:c20,c257,c512,c768 tclass=process app=com.example.bug
W/1.ui    ( 4707): type=1400 audit(0.0:72400): avc: granted { execmem } for scontext=u:r:untrusted_app:s0:c20,c257,c512,c768 tcontext=u:r:untrusted_app:s0:c20,c257,c512,c768 tclass=process app=com.example.bug
E/flutter ( 4707): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 4707): #0      PathProviderApi.getTemporaryPath (package:path_provider_android/messages.g.dart:44:7)
E/flutter ( 4707): <asynchronous suspension>
E/flutter ( 4707): #1      getTemporaryDirectory (package:path_provider/path_provider.dart:55:24)
E/flutter ( 4707): <asynchronous suspension>
E/flutter ( 4707): #2      _MyHomePageState.build.<anonymous closure> (package:bug/main.dart:86:35)
E/flutter ( 4707): <asynchronous suspension>
E/flutter ( 4707): 
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.1, on Fedora Linux 38 (Workstation Edition) 6.3.6-200.fc38.x86_64, locale en_US.UTF-8)
    • Flutter version 3.10.1 on channel stable at /home/myzel394/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (4 weeks ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /home/myzel394/Android/Sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /home/myzel394/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.10121639/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.3)
    • Android Studio at /var/lib/snapd/snap/android-studio/125/android-studio
    • Flutter plugin version 72.1.1
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2022.2)
    • Android Studio at /home/myzel394/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.10121639
    • Flutter plugin version 74.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2021.2)
    • Android Studio at /home/myzel394/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683
    • Flutter plugin version 71.2.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at /var/lib/snapd/snap/intellij-idea-ultimate/426
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • Pixel 7 Pro (mobile) • 2C121FDH300388 • android-arm64  • Android 13 (API 33)
    • Linux (desktop)      • linux          • linux-x64      • Fedora Linux 38 (Workstation Edition) 6.3.6-200.fc38.x86_64
    • Chrome (web)         • chrome         • web-javascript • Google Chrome 114.0.5735.106

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by Myzel394** [comment]
I already tried adding MicroG - but the error still persists :/

**Comment by dam-ease** [comment]
Thanks for filing this issue @Myzel394. I am able to reproduce this issue with the code sample provided.

<details><summary>flutter doctor -v</summary>
<p>

```
[✓] Flutter (Channel stable, 3.10.4, on macOS 13.4 22F66 darwin-arm64, locale
    en-NG)
    • Flutter version 3.10.4 on channel stable at /Users/dammya/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 682aa387cf (6 days ago), 2023-06-05 18:04:56 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/dammya/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/dammya/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] VS Code (version 1.78.0)
    • VS Code at /Users/dammya/.Trash/Visual Studio Code 20.07.05.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (4 available)
    • sdk gphone arm64 (mobile) • emulator-5554                        •
      android-arm64  • Android 11 (API 30) (emulator)
    • iPhone 14 (mobile)        • 5FE8DE93-0F4C-45BA-8BED-BC9CD69B35D1 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)           • macos                                •
      darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)              • chrome                               •
      web-javascript • Google Chrome 114.0.5735.106

[✓] Network resources
    • All expected network resources are available.

• No issues found!
``` 

```
[✓] Flutter (Channel master, 3.11.0-2.0.pre.55, on macOS 13.4 22F66 darwin-arm64, locale en-NG)
    • Flutter version 3.11.0-2.0.pre.55 on channel master at /Users/dammya/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 835b892d7f (5 weeks ago), 2023-05-07 01:30:22 +0530
    • Engine revision 23f730efbf
    • Dart version 3.1.0 (build 3.1.0-83.0.dev)
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/dammya/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/dammya/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] VS Code (version 1.78.0)
    • VS Code at /Users/dammya/.Trash/Visual Studio Code 20.07.05.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (4 available)
    • sdk gphone arm64 (mobile) • emulator-5554                        • android-arm64  • Android 11 (API 30) (emulator)
    • iPhone 14 (mobile)        • 5FE8DE93-0F4C-45BA-8BED-BC9CD69B35D1 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)           • macos                                • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)              • chrome                               • web-javascript • Google Chrome 114.0.5735.106

[✓] Network resources
    • All expected network resources are available.

• No issues found!

``` 

</p>
</details>

**Comment by stuartmorgan** [comment]
Odd, that error looks like Pigeon channel setup failed; I would expected Java dependency issues to cause failures handling messages, not setting up the handlers. It kind of looks like the old issue with an exception in one plugin's registration method prevents other plugins from registering, but that should be fixed. We'll need to debug to see what exactly is failing.

> 4\. Exclude `com.google.android.gms` in `android/app/build.gradle`, like I did here: https://github.com/Myzel394/flutter-path_provider-bug/blob/master/android/app/build.gradle#L75

What's the context here? Why are you excluding dependencies?

**Comment by Myzel394** [comment]
@stuartmorgan I am trying to degoogle my app. I'd be okay with MicroG, but no GMS.

**Comment by stuartmorgan** [comment]
> It kind of looks like the old issue with an exception in one plugin's registration method prevents other plugins from registering, but that should be fixed.

It's a variant of the same thing; the `registerWith` of `nearby_connections` is throwing class not found errors. The reason the earlier fix doesn't work here is that since those are errors, not exceptions, the `Exception` case doesn't catch it. That means the rest of the registration doesn't run, breaking any plugins that come after it.

In theory we could catch *everything*, but since errors aren't intended to be caught I don't think that's a direction we should go unless we see evidence that this is a problem that happens in cases less niche than this one. If someone is going to deliberately remove necessary dependencies from plugins they are using, I think it's reasonable to expect them to debug (this was trivial to isolate by just running the provided project under the Android Studio debugger with exception breakpoints enabled), rather than try to make the engine handle it gracefully.

**Comment by Myzel394** [comment]
@stuartmorgan do you know how to resolve this issue? I'm not an expert on Android related development.

>  The reason the earlier fix doesn't work here is that since those are errors, not exceptions, the Exception case doesn't catch it. That means the rest of the registration doesn't run, breaking any plugins that come after it.

Do you mean the file `android/app/src/main/java/io.flutter.plugins/GeneratedPluginRegistrant`? I can see this block of code:

```java
    try {
      flutterEngine.getPlugins().add(new com.pkmnapps.nearby_connections.NearbyConnectionsPlugin());
    } catch(Exception e) {
      Log.e(TAG, "Error registering plugin nearby_connections, com.pkmnapps.nearby_connections.NearbyConnectionsPlugin", e);
    }
```
did I understand you correctly, I could just remove this code, hence no more errors are thrown and then everything should work fine, or I could also catch the error?

**Comment by stuartmorgan** [comment]
> @stuartmorgan do you know how to resolve this issue?

Not trying to both use a plugin that relies on certain dependencies while also removing those dependencies from your build would resolve the issue you are having.

> did I understand you correctly, I could just remove this code

I was not suggesting removing that code, no. Doing so manually would likely require forking `flutter`.

> hence no more errors are thrown and then everything should work fine

They certainly wouldn't be thrown from that specific call any more; whether there are other things that would be broken by missing class files that would throw errors later, I have no idea. It is also certainly not the case that everything would work fine if remove the registration of a plugin that you are trying to use.

> or I could also catch the error?

In theory, yes, subject to all of the same caveats.

The Flutter team cannot provide support here, as you are explicitly making a change to your build that breaks your application.

**Comment by Myzel394** [comment]
> Not trying to both use a plugin that relies on certain dependencies while also removing those dependencies from your build would resolve the issue you are having.

I am building my application in two variants: One with gms, and another completely floss, without any Google related stuff. For the floss version same features will be disabled, that's why I also have no problem excluding gms, despite `nearby_connections` relying on it. Features related to that package will not be available in the floss version.

Thanks for your answer, I think I will go with the error catch approach, since that seems to be the easiest one.

**Comment by stuartmorgan** [comment]
> Thanks for your answer, I think I will go with the error catch approach, since that seems to be the easiest one.

The easiest approach to building a variant of your application without gms would almost certainly be to have that variant not include plugins based on gms, rather than including the plugins, deliberately breaking them in catastrophic ways, and hoping that you can contain the resulting errors.

**Comment by stuartmorgan** [comment]
You said "Features related to that package will not be available". All I'm suggesting is that the right way to have the features of that package not available in that variant is to *not include it* in that variant, rather than including it in a completely broken, inoperable form that can also break other parts of your application. Not including something doesn't require a different plugin.

That's all the advice I can offer here. If you are looking for further help with your own code, consider one of the resources listed at https://flutter.dev/community#community-grid

**Comment by Myzel394** [comment]
In case anyone stumbles across this issue:

I now created a local package using https://docs.flutter.dev/packages-and-plugins/developing-packages and basically created "fake" classes for my error causing package (`nearby_connections` in my case), and used `dependency_override` to override my local package for the FLOSS version - and it works fine!
