### ISSUE TITLE
`PopupMenuButton` should support `materialTapTargetSize` just like other buttons

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter#128697]
Google issue b/227523375

**Comment by justinmc** [comment]
@hannah-hyj (When you're back) Any thoughts on what we can do with this issue?

**Comment by hannah-hyj** [comment]
You can set buttonStyle to PopupMenuButton,

A default PopupMenuButton has an IconButton as its child, and it already has Interactive size Constraints  
 https://github.com/flutter/flutter/blob/97eef6afc5feed457852993f84f716dd3606f258/packages/flutter/lib/src/material/icon_button.dart#L750-L752

so I don't think there is an action item.
