### ISSUE TITLE
[Impeller] Vulkan: Top line of text is cropped sometimes in wonderous app

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#128624]
## description

I've seen this with the opengles backend and the vulkan backend.  It's shown up in a couple places in the app, not just here.

I checked against the skia backend and this was not a problem.

## doctor

```
[✓] Flutter (Channel main, 3.12.0-3.0.pre.44, on macOS 13.4 22F66 darwin-arm64, locale en)
    • Flutter version 3.12.0-3.0.pre.44 on channel main at /Users/aaclarke/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e84fa2ce47 (4 hours ago), 2023-06-09 23:06:21 +0500
    • Engine revision bc6e047570
    • Dart version 3.1.0 (build 3.1.0-180.0.dev)
    • DevTools version 2.24.0
```

## engine version

64d0cc34e7949bd6e5b3891670e124c5cb233fa0

## os

Android

## screenshot

![Screenshot_20230609-143436](https://github.com/flutter/flutter/assets/30870216/5b5a3fd2-af72-4d33-b0da-5cb9bece4f36)

cc @bdero

**Comment by bdero** [comment]
Is this happening on the Metal backend too? If that's the case, then this is definitely a regression introduced after the 3.10 branch cut.

**Comment by bdero** [comment]
I checked wondrous at engine head and am not reproducing it on iOS.

![Screen Shot 2023-06-09 at 4 26 00 PM](https://github.com/flutter/flutter/assets/919017/3600abcd-6c2e-4b1b-9ed8-bf611c38c39f)

**Comment by gaaclarke** [comment]
@bdero did you see there is another funky text bug in that screenshot for ios?

**Comment by bdero** [comment]
Hmm, I'm not spotting an issue. What is it?

**Comment by gaaclarke** [comment]
> Hmm, I'm not spotting an issue. What is it?

Look at the words "First" "state" and "connect", see the space before the t's.

**Comment by bdero** [comment]
Oh, do you mean the curve connecting them? `ct` and `st` have special glyphs in [Raleway](https://www.theleagueofmoveabletype.com/raleway):
<img width="429" alt="image" src="https://github.com/flutter/flutter/assets/919017/310aea52-15e0-41ae-b862-c4b735a87054">

**Comment by jonahwilliams** [comment]
Please check if this is fixed after https://github.com/flutter/engine/pull/42746 lands

**Comment by jonahwilliams** [comment]
(I cannot repro it before or after, but it probably depends on screen size)

**Comment by gaaclarke** [comment]
> Oh, do you mean the curve connecting the letters? `ct` and `st` have special glyphs in [Raleway](https://www.theleagueofmoveabletype.com/raleway):

🤮 ...looks like it's an optional feature of that font.   I don't see that feature being turned on in the source code for wonderous ( https://api.flutter.dev/flutter/dart-ui/FontFeature-class.html ).

**Comment by jonahwilliams** [comment]
🤣

**Comment by jonahwilliams** [comment]
I can repro this, will need a slightly different fix

**Comment by jonahwilliams** [comment]
I can still see this happening. Need to investigate

**Comment by gaaclarke** [comment]
Did we ever determine why that optional feature for the font was turned on?  I think that's a bug we should file.

**Comment by jonahwilliams** [comment]
its not a bug, its just the font and working by design.

**Comment by gaaclarke** [comment]
> its not a bug, its just the font and working by design.

I'm pretty sure those ligatures are supposed to be off by default unless you turn them on with font features, I couldn't find that happening in the flutter code.  I also believe the skia renderer was rendering without them.  I'll double check that tomorrow.

**Comment by jonahwilliams** [comment]
ahh, I guess that would be an issue - though I'd hope we're going through exactly the same code paths here 😓

**Comment by jonahwilliams** [comment]
I tried reverting https://github.com/flutter/engine/pull/42417 locally and it had no effect. I also tried out the opengl backend and it has the same artifact.

Also stepped through the shader and nothing seemed wildly off (no NaNs), though that is trickier to verify

I wonder if this is an issue with the sizes of those particular glyphs? Need to build a reduce test case

**Comment by bdero** [comment]
IIRC, the ligatures have been rendering on [both Impeller and Skia](https://github.com/gskinnerTeam/flutter-wonderous-app/issues/53) since we first began debugging Impeller against Wondrous.

**Comment by gaaclarke** [comment]
@bdero when I run wonderous locally I don't see the discretionary ligatures, do you have some local change?  The wonderous source code is not turning them on:

*//lib/styles/styles.dart*
```
  final Map<String, TextStyle> _contentFonts = {
    'en': TextStyle(fontFamily: 'Raleway', fontFeatures: const [
      FontFeature.enable('kern'),
    ]),
  };
```

I wrote a tiny app that tested turning the ligatures off and on and they render correctly.  I'm just left scratching my head wondering why they are showing up in Brandon's screenshots.

**Comment by jonahwilliams** [comment]
I think you should move ligature discussion to a new issue if you're going to continue it. The topline of text issue is complicated enough.

Anyway. Here is a simpler app that reproduces the issue on an S10:

https://gist.github.com/jonahwilliams/0a21a2b7b96c89d8d1d5d400396ef413

Something I've noticed is that the crop *_doesn't_* change on a vertical scroll - which tells me we may have incorrect font metrics for certain glyphs.

![image](https://github.com/flutter/flutter/assets/8975114/2e9b5673-24cf-4fbc-ab97-0597c1e1ca0e)

**Comment by jonahwilliams** [comment]
Note that this does not repro on my Pixel 6, but does on a Samsung S10.

**Comment by jonahwilliams** [comment]
Also does not repro on iPhone 13.

**Comment by jonahwilliams** [comment]
Not only that, but the text itself is jittery as I scroll which does not happen on Pixels either. I wonder if there is some sort of "helpful" correction being applied somewhere? Though I'm not sure where that would be.

**Comment by gaaclarke** [comment]
> I think you should move ligature discussion to a new issue if you're going to continue it. The topline of text issue is complicated enough.

That is my plan, I can't file an issue until I'm sure there is a problem.  The only evidence of a problem is Brandons screenshots on this issue.  I'll cull these messages once we have enough information to close the inquiry.

**Comment by jonahwilliams** [comment]
From running locally, I can see that the glyphs in the atlas are rendered right against the edge of the glyph atlas, obviously cutting off parts of the glyph and/or antialiased pixels on some of them. Given that we should be rendering everything with 2px padding it seems like something is off...

**Comment by jonahwilliams** [comment]
Something I am noticing is that on Android Skia starts from the bottom of the atlas...

**Comment by chinmaygarde** [comment]
Perhaps this is caused by incorrect UV mapping needing after we [added the 2px padding](https://github.com/flutter/flutter/issues/119955)? Also, atlases on Android generated by Skia won't use the CoreText. There could be differences in glyph AA in atlases. So maybe we need more padding perhaps?

**Comment by jonahwilliams** [comment]
I tried adding more padding but it made no difference :( . I think the glyph bounds themselves are wrong or need some other adjustment

**Comment by jason-simmons** [comment]
Reproduced this on a Pixel 3.

The glyphs render correctly if I remove the `sk_font.setHinting(SkFontHinting::kSlight)` call in `text_render_context_skia.cc`.

**Comment by jonahwilliams** [comment]
FYI @bdero 

IRC the goal of adding that flag was better fidelity on iOS at the time, but obvs its not helping us on Android so we could disable it with an ifdef for now.

That said, we should probably figure out how to handle these flags correctly.

**Comment by jonahwilliams** [comment]
If I comment out that line, then I can still reproduce this issue on an S10 on Flutter gallery. ☹️

**Comment by chinmaygarde** [comment]
Just adding a note that glyph offsets on Android [are also reproducible with stroked text](https://github.com/flutter/engine/pull/41735) (perhaps even more so?). This is perhaps the same underlying issue.
