### ISSUE TITLE
android app crash on BT keyboard connect/disconnect

### ISSUE THREAD

**Issue by nohkumado** [flutter/flutter#128638]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. flutter create anapp
2. compile with android studio
3. run it on a android 11 tablet
4. switch on (or let it go to sleep) a BT keyboard
-> crash 

### Expected results

not crashing?

### Actual results

crashing....

logs show nothing, probably wrongly configured?
bboett@rodoosha:~/AndroidStudioProjects/flutter_sample$ flutter logs
Showing LIFETAB P1091X logs:
I/flutter (21100): The Dart VM service is listening on http://127.0.0.1:37783/sGjftN60Su0=/

if someone can tell me how to configure this i would be glad

### Code sample

<details><summary>Code sample</summary>

I have an exam companion where i need sporadically to write some comments, i noticed the crash with that app first,
but since this behaviour is allready present with the default app....

```dart
not needed
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
Logcat: 
Debug service listening on ws://127.0.0.1:40121/Wf_2ajPmJUQ=/ws
Syncing files to device LIFETAB P1091X...
[  +45 ms] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[        ] <- recompile package:flutter_sample/main.dart e850e4b9-148d-4757-b6b7-7b7e811fbd15
[        ] <- e850e4b9-148d-4757-b6b7-7b7e811fbd15
[        ] Bundle processing done.
[  +51 ms] Updating files.
[        ] DevFS: Sync finished
[        ] Synced 0.0MB.
[        ] <- accept
[  +11 ms] Connected to _flutterView/0xb4000077e81ad870.
[+3443 ms] V/PhoneWindow(19353): DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@cd941ee, this = DecorView@6abc68f[MainActivity]
[   +2 ms] V/PhoneWindow(19353): DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@cd941ee, this = DecorView@6abc68f[MainActivity]
[  +54 ms] E/ion     (19353): ioctl c0044901 failed with code -1: Invalid argument
[   +5 ms] D/ViewRootImpl(19353): setSurfaceViewCreated, created:true
[+23466 ms] D/ViewRootImpl(19353): setSurfaceViewCreated, created:false
[ +445 ms] I/GED     (19353): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 2, oppidx_max 2, oppidx_min 0
[        ] I/GED     (19353): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 2, oppidx_max 2, oppidx_min 0
[  +17 ms] D/View    (19353): [Warning] assignParent to null: this = DecorView@6abc68f[MainActivity]
[   +7 ms] I/InputTransport(19353): Destroy ARC handle: 0xb4000076d8236550
[  +91 ms] V/PhoneWindow(19353): DecorView setVisiblity: visibility = 4, Parent = null, this = DecorView@4804667[]
[   +4 ms] D/ViewRootImpl[MainActivity](19353): hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
[   +7 ms] I/InputTransport(19353): Create ARC handle: 0xb4000076d81e0690
[   +1 ms] V/PhoneWindow(19353): DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@9b492b2, this = DecorView@4804667[MainActivity]
[   +1 ms] I/Choreographer(19353): Skipped 34 frames!  The application may be doing too much work on its main thread.
[  +53 ms] D/ViewRootImpl(19353): setSurfaceViewCreated, created:true
[+3939 ms] I/.flutter_sampl(19353): Compiler allocated 4303KB to compile void android.view.ViewRootImpl.performTraversals()


```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
bboett@rodoosha:~/AndroidStudioProjects$ flutter doctor -v
[✓] Flutter (Channel beta, 3.11.0-0.1.pre, on Ubuntu 23.04 6.2.0-20-generic, locale de_DE.UTF-8)
    • Flutter version 3.11.0-0.1.pre on channel beta at /home/bboett/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 350d2c3a6c (vor 2 Wochen), 2023-05-23 15:52:05 -0700
    • Engine revision 7eca5cd1c5
    • Dart version 3.1.0 (build 3.1.0-63.1.beta)
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/bboett/Android/Sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /home/bboett/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 15.0.7
    • cmake version 3.25.1
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[✓] Android Studio (version 2022.2)
    • Android Studio at /home/bboett/android-studio
    • Flutter plugin version 73.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.2)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • LIFETAB P1091X (mobile) • DEA2E007AA4025B7 • android-arm64  • Android 11 (API 30)
    • Linux (desktop)         • linux            • linux-x64      • Ubuntu 23.04 6.2.0-20-generic
    • Chrome (web)            • chrome           • web-javascript • Chromium 113.0.5672.126 snap

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @nohkumado 
Can you please try checking if there is any crash from native thread with below adb command?

```console
adb logcat | grep -F "`adb shell ps | grep <your-app-id>  | tr -s [:space:] ' ' | cut -d' ' -f2`"
```

> switch on (or let it go to sleep) a BT keyboard

Also, what is that sleep key? Can you capture your Bluetooth keyboard?

**Comment by huycozy** [comment]
Thanks for your update but I also can't find crash log from your adb log output above. 

>so i had to time the thing to install app, run app, switch on the keyboard ( as going to sleep i have to wait for it to go to sleep...) wait for the test app to restart, and cut the log....

Can you please be more specific on `Steps to reproduce`? What is _"wait for the test app to restart"_ step? (Do you perform `Hot restart`?)

I also try Keychron K1 keyboard (connect/disconnect) but can't reproduce this issue.

**Comment by huycozy** [comment]
I can't find a specific log that is related to Flutter. Can you try this on a default Android native app with your keyboard?

**Comment by nohkumado** [comment]
I have a self written shell written on android studio in java for android, works like a charm....
monitored through adb and logcat, nothing unusual is happening....

**Comment by huycozy** [comment]
>I have a self written shell written on android studio in java for android, works like a charm....

Can you share what is that? Is that an Android native app?

It's not easy for us if there is no more information related to Flutter. So I would suggest you try connecting to another Android device as well.

Also, I notice there is no message like "Lost connection to device." from your original output logs above. It should be there if the app is terminated, I think.

**Comment by nohkumado** [comment]
Bruno Böttcher
--
35 rue de la république, FR-6720 Schwindratzheim
email: ***@***.***, ***@***.***
Fon:+33 3 88 89 91, Mob:+33 6 76 55 82 68
-------------------------------------------------
Dev: Java/Perl/PHP OS:GNU/LINUX, Android

huycozy ***@***.***> schrieb am Mi., 14. Juni 2023, 13:57:

> I have a self written shell written on android studio in java for android,
> works like a charm....
>
> Can you share what is that? Is that an Android native app?
>
Yes, Java Android App https://github.com/nohkumado/nohutils

It's not easy for us if there is no more information related to Flutter. So
> I would suggest you try connecting to another Android device as well.
>
unfortunately its the only tablet i have, but i just tested on my phone:
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app-debug.apk...
Debug service listening on ws://127.0.0.1:43821/P5LaiV_01Us=/ws
Syncing files to device Pixel 4a...
I/o.examen_helper( 4547): Compiler allocated 4413KB to compile void
android.view.ViewRootImpl.performTraversals()
I/flutter ( 4547): ++++++++normal +++++++ constraints :
BoxConstraints(w=392.7, h=826.9)
I/flutter ( 4547): ++++++++normal +++++++ constraints :
BoxConstraints(w=392.7, h=826.9)
W/Parcel  ( 4547): Expecting binder but got null!
W/OnBackInvokedCallback( 4547): OnBackInvokedCallback is not enabled for
the application.
W/OnBackInvokedCallback( 4547): Set
'android:enableOnBackInvokedCallback="true"' in the application manifest.
E/OpenGLRenderer( 4547): Unable to match the desired swap behavior.
W/RemoteInputConnectionImpl( 4547): requestCursorAnchorInfo on inactive
InputConnection
I/flutter ( 4547): ++++++++normal +++++++ constraints :
BoxConstraints(w=392.7, h=826.9)
W/Parcel  ( 4547): Expecting binder but got null!
I/flutter ( 4547): ++++++++normal +++++++ constraints :
BoxConstraints(w=392.7, h=826.9)
I/flutter ( 4547): ++++++++normal +++++++ constraints :
BoxConstraints(w=392.7, h=826.9)

screen blanks as the kbd is switched on and connected, apps comes back in
blank state, sometimes with a streak of viable restarts, sometimes just a
black screen....
nothing noteworthy in the adb log :(

tested it with the flutter sample app, that one survives on the phone...
but for each switch on switch off of the keyboard i get this in the studio
logcat:
W/OnBackInvokedCallback( 8300): OnBackInvokedCallback is not enabled for
the application.
W/OnBackInvokedCallback( 8300): Set
'android:enableOnBackInvokedCallback="true"' in the application manifest.
D/VRI[MainActivity]( 8300): updatePointerIcon called after view was removed
E/OpenGLRenderer( 8300): Unable to match the desired swap behavior.

so i don't see anything, but this "view was removed" indicates that at
least the view was redrawn?

> Also, I notice there is no message like "Lost connection to device." from
> your original output logs above. It should be there if the app is
> terminated, I think.
>
probably yes, android studio marks the app as dead though.....

**Comment by huycozy** [comment]
Thanks for your update. I just looked back your provided log file at https://github.com/flutter/flutter/issues/128638#issuecomment-1586990728 and found some logs related to `BistoWorker` that may be a potential log for further investigation.

<details>
<summary>BistoWorker cash log</summary>

```console
06-12 11:44:54.940  1247  1247 E BluetoothPhonePolicy: Received unexpected intent, action=android.bluetooth.device.action.ACL_CONNECTED
06-12 11:44:54.967 15046 15122 I BistoWorker: (REDACTED) bluetoothConnectionStateChanged. Action: %s
06-12 11:44:54.970 15046 15102 I BistoWorker: (REDACTED) Failed to get bistoDeviceInfo %s
06-12 11:44:54.987  4003  2530 I Nearby  : (REDACTED) is blocked device type %s, isAuto=%s, isIot=%s, isLatchsky=%s, isChinaWearable=%s, isTv=%s, isWearable=%s (supportWearOs=%s), isChromeOsDevice=%s (supportChromeOs=%s)
06-12 11:44:54.988   588  1159 I BufferQueueProducer: [StatusBar#0](this:0xb40000741bb37e28,id:5,api:1,p:1268,c:588) queueBuffer: fps=0.32 dur=3167.81 max=3167.81 min=3167.81
06-12 11:44:54.990 15046 15102 I DeviceDetector: Is not a headset device
06-12 11:44:54.993  4003  4003 I NearbyDiscovery: (REDACTED) onAclChange: state=%s, device=%s
06-12 11:44:54.995   567   685 I hwcomposer: [HWCDisplay] [Display_0 (type:1)] fps:0.315308,dur:3171.50,max:3171.50,min:3171.50  
06-12 11:44:54.995  4003  4138 I NearbyDiscovery: (REDACTED) FastPair: lock scan rate if needed, device=%s, bondState=%s
06-12 11:44:54.996 15046 15101 W BistoWorker: Failed to get bisto device info.
06-12 11:44:54.996 15046 15101 W BistoWorker: com.google.android.apps.search.assistant.surfaces.bisto.interactor.deviceinfo.i
06-12 11:44:54.996 15046 15101 W BistoWorker: 	at com.google.android.apps.gsa.shared.bisto.a.e.a(PG:2)
06-12 11:44:54.996 15046 15101 W BistoWorker: 	at com.google.android.apps.gsa.shared.bisto.a.c.call(Unknown Source:2)
06-12 11:44:54.996 15046 15101 W BistoWorker: 	at com.google.apps.tiktok.tracing.ey.call(PG:3)
06-12 11:44:54.996 15046 15101 W BistoWorker: 	at com.google.common.util.concurrent.ea.a(PG:1)
06-12 11:44:54.996 15046 15101 W BistoWorker: 	at com.google.common.util.concurrent.cw.run(PG:4)
06-12 11:44:54.996 15046 15101 W BistoWorker: 	at com.google.common.util.concurrent.eb.run(PG:1)
06-12 11:44:54.996 15046 15101 W BistoWorker: 	at com.google.common.util.concurrent.dp.run(PG:1)
06-12 11:44:54.996 15046 15101 W BistoWorker: 	at com.google.common.util.concurrent.dq.run(PG:4)
06-12 11:44:54.996 15046 15101 W BistoWorker: 	at com.google.android.libraries.j.z.run(PG:1)
06-12 11:44:54.996 15046 15101 W BistoWorker: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-12 11:44:54.996 15046 15101 W BistoWorker: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-12 11:44:54.996 15046 15101 W BistoWorker: 	at com.google.android.libraries.j.h.run(PG:2)
06-12 11:44:54.996 15046 15101 W BistoWorker: 	at java.lang.Thread.run(Thread.java:923)
06-12 11:44:54.996 15046 15101 W BistoWorker: 	at com.google.android.libraries.j.ai.run(PG:5)
06-12 11:44:54.996  4003  4138 I NearbyDiscovery: (REDACTED) FastPairScanner: isScreenOn=%s, scanWithScreenOff=%s, isLocationEnabled=%s, disableLocationRequirement=%s, isDiscoveryScanningEnabled=%s, during24GhzWifiWarmingUpPeriod=%s
06-12 11:44:54.997  4003  4138 D BluetoothAdapter: isLeEnabled(): ON
```
</details>

---
But there are some doubts I need to confirm again by your last comment:

>screen blanks as the kbd is switched on and connected, apps comes back in
blank state, sometimes with a streak of viable restarts, sometimes just a
black screen....
nothing noteworthy in the adb log :(

>tested it with the flutter sample app, that one survives on the phone...
but for each switch on switch off of the keyboard i get this in the studio

Do you mean the crash doesn't occur on Flutter default sample project (counter app)? If so, it behaves the same as my result. There is only one issue with `restart` the app (I'm also hitting this issue as well)

I'm guessing your original issue (`blank state`) is on a complex project (not on Flutter default sample project), right? Have you modified any native code (Android)? If not so, can you please:
1. Running Flutter default sample project again from the console: `flutter run -v`, then try to reproduce the crash and provide the complete output. It may be a long log so please 
2. Check the issue with `debug` and `release` mode to see if there is any difference

---

(Also, can you please format your comment for better readability? It will make it easier for anyone interested to the issue. 
You may want to refer to [writing and formatting syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) for beautifully formatted issue description. Thank you!)

**Comment by nohkumado** [comment]
thanks for still looking into this!
> Do you mean the crash doesn't occur on Flutter default sample project (counter app)? If so, it behaves the same as my result. There is only one issue with restart the app (I'm also hitting this issue as well)
indeed, or the recovery is much better with the sample app
> I'm guessing your original issue (blank state) is on a complex project (not on Flutter default sample project), right? Have you modified any native code (Android)? 
that's correct lets say i have the `sample` app, straight from `flutter create` and an app `exam`

I wanted to run the run on the console, but flutter kept pestering me to upgrade, and the upgrade changed things!

Now, even `exam` doesn't crash anymore, it flickers (long in debug much much shorter in release, normal you would say) but i still loose my data, if you could point me out where to insert a save-safeguard, that would be most helpful, i have an exam to monitor sunday  and if i could use my tool....? 

nevertheless, i produced the logs, in case something strange can be seen inside them:

-  [sample_debug.log](https://github.com/flutter/flutter/files/11758540/sample_debug.log)
-  [sample_release.log](https://github.com/flutter/flutter/files/11758543/sample_release.log)
-  [exam_debug.log](https://github.com/flutter/flutter/files/11758550/exam_debug.log)
-  [exam_release.log](https://github.com/flutter/flutter/files/11758554/exam_release.log)

**Comment by huycozy** [comment]
Glad to see the crash doesn't occur anymore. I checked the provided logs above and they seem to be normal log. 

But I'm not sure what is flickered in your app? Does it happen on a Flutter default sample app? If it only happens on your `exam` app, it might be caused by plugins/implementation that I don't have clues right now. You should narrow down to the issue by isolate module/package/plugin in your project and find the potential cause.

Regarding to `reset` data when connect/disconnect issue. I would recommend you file another issue for better tracking there. Please try to fill all information indicated in the template and use a minimal sample code as well. TBH, I think it will take more time to solve the issue, so you should use another keyboard in urgent case.
