### ISSUE TITLE
Adding a record in a record list in web is throwing TypeErrorImpl 

### ISSUE THREAD

**Issue by sjtsh** [flutter/flutter#128642]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Using dart 3.1.0-136.0.dev, flutter 3.11.0-12.0.pre.9 on channel master 
2. Running the application on Chrome but have tried it on Edge as well, working fine on Windows
3. Add the variable typed List<(double, int)> and initialize it with some data, working fine for empty lists
4. Try to add any data of type (double, int) into it such as (6.0, 10)

### Expected results

Expected to print out the list after the new record is added

### Actual results

Rather throws TypeErrorImpl

### Code sample

  ```
List<(double, int)> currentNav = [
    (100.0, 1),
    (0.0, 1),
  ];

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () {
        currentNav.add((6.0, 10));
        print(currentNav);
      },
      child: Container(
        height: 100,
        width: 100,
        color: Colors.red,
      ),
    );
  }
```

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
```
The following TypeErrorImpl was thrown while handling a gesture:
Expected a value of type '(double, int)', but got one of type '(int, int)'

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 127:3       castError
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 738:12  cast
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/types.dart 2319:12      as
dart-sdk/lib/_internal/js_dev_runtime/private/js_array.dart 82:14                 add]
packages/trythisout/main.dart 41:3                                                <fn>
packages/flutter/src/gestures/recognizer.dart 275:24                              invokeCallback
packages/flutter/src/gestures/tap.dart 654:11                                     handleTapUp
packages/flutter/src/gestures/tap.dart 311:5                                      [_checkUp]
packages/flutter/src/gestures/tap.dart 244:7                                      handlePrimaryPointer      
packages/flutter/src/gestures/recognizer.dart 630:9                               handleEvent
packages/flutter/src/gestures/pointer_router.dart 98:12                           [_dispatch]
packages/flutter/src/gestures/pointer_router.dart 143:9                           <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/linked_hash_map.dart 21:13          forEach
packages/flutter/src/gestures/pointer_router.dart 141:17                          [_dispatchEventToRoutes]  
packages/flutter/src/gestures/pointer_router.dart 127:7                           route
packages/flutter/src/gestures/binding.dart 465:19                                 handleEvent
packages/flutter/src/gestures/binding.dart 445:14                                 dispatchEvent
packages/flutter/src/rendering/binding.dart 331:11                                dispatchEvent
packages/flutter/src/gestures/binding.dart 400:7
[_handlePointerEventImmediately]
packages/flutter/src/gestures/binding.dart 363:5                                  handlePointerEvent        
packages/flutter/src/gestures/binding.dart 320:7                                  [_flushPointerEventQueue] 
packages/flutter/src/gestures/binding.dart 293:9                                  [_handlePointerDataPacket]
lib/_engine/engine/platform_dispatcher.dart 1260:13                               invoke1
lib/_engine/engine/platform_dispatcher.dart 272:5                                 invokeOnPointerDataPacket 
lib/_engine/engine/pointer_binding.dart 168:39                                    [_onPointerData]
lib/_engine/engine/pointer_binding.dart 791:20                                    <fn>
lib/_engine/engine/pointer_binding.dart 720:14                                    <fn>
lib/_engine/engine/pointer_binding.dart 317:16                                    loggedHandler
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 570:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 575:39  dcall

Handler: "onTap"
Recognizer:
  TapGestureRecognizer#7418b
════════════════════════════════════════════════════════════════════════════════════════════════════        
Another exception was thrown: Expected a value of type '(double, int)', but got one of type '(int, int)'
Another exception was thrown: Expected a value of type '(double, int)', but got one of type '(int, int)'
```

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 3.11.0-12.0.pre.9, on Microsoft Windows [Version 10.0.19045.2965], locale      
    en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web                                                
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.5.2)  
[√] Android Studio (version 2022.1)                                             
[√] VS Code (version 1.78.2)
[√] Connected device (3 available)
[√] Network resources

• No issues found!

**Comment by Snonky** [comment]
On the web a number without a fractional (like `6.0`) is always considered an `int`. You can read up on that [here](https://dart.dev/guides/language/numbers#types-and-type-checking).

The solution to your problem would be changing the type of `currentNav` to `List<(num, int)>`. 

`num` is the supertype of `int` and `double` and is guaranteed to never ne subtyped by anything else. You can safely use it to accept `double` and `int` which alleviates the web platform's inconsistency.

**Comment by sjtsh** [comment]
Thank you @Snonky didnt know that.

**Comment by darshankawar** [comment]
Based on https://github.com/flutter/flutter/issues/128642#issuecomment-1586157513, closing this as not an issue. If you disagree, write in comments and I'll reopen it.
