### ISSUE TITLE
Dart pub cache clear not existing

### ISSUE THREAD

**Issue by nik2208** [flutter/flutter#128717]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1:install a separate instance of flutter
2:run flutter doctor

### Expected results

Found an existing Pub cache at /Users/nicola/.pub-cache.
It can be repaired by running `dart pub cache repair`.
It can be reset by running `dart pub cache **clean**`.
Found an existing Dart Analysis Server cache at /Users/nicola/.dartServer.
It can be reset by deleting /Users/nicola/.dartServer.

### Actual results

Found an existing Pub cache at /Users/nicola/.pub-cache.
It can be repaired by running `dart pub cache repair`.
It can be reset by running `dart pub cache **clear**`.
Found an existing Dart Analysis Server cache at /Users/nicola/.dartServer.
It can be reset by deleting /Users/nicola/.dartServer.

### Code sample

```bash
% dart pub cache clear
Could not find a subcommand named "clear" for "dart pub cache".

Did you mean one of these?
  clean


Usage: dart pub cache [arguments...]
...
```

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by dam-ease** [comment]
Hi @nik2208. I see there's an open issue addressing the case you described #128663.
Please comment, upvote and follow up on that issue. I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by nik2208** [comment]
oh ok.. sorry abt that
