### ISSUE TITLE
[in_app_purchase] queryPastPurchases ignores the passed-in applicationUserName

### ISSUE THREAD

**Issue by jesper372** [flutter/flutter#128773]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

`InAppPurchaseAndroidPlatformAddition.queryPastPurchases` retrieves all uncompleted purchases, irrespective of the argument passed to its `applicationUserName` parameter. This is problematic, because only those purchases pertaining to the current user should be validated and completed when retrieving uncompleted purchases.

To reproduce:

1) comment out the call to `completePurchase`, so that purchases will remain uncompleted and get returned by `queryPastPurchases` 
2) call `InAppPurchase.instance.buyConsumable`, and pass in a valid UUID to the `applicationUserName` argument in the `GooglePlayPurchaseParam`
3) repeat step 2, this time with a different UUID
4) call `InAppPurchaseAndroidPlatformAddition.queryPastPurchases`, and pass in the UUID from either step 2 or 3 to its `applicationUserName` parameter

### Expected results

Only the uncompleted purchases pertaining to the UUID passed in to `applicationUserName` are returned when calling `InAppPurchaseAndroidPlatformAddition.queryPastPurchases`.

### Actual results

All uncompleted purchases are returned when calling `InAppPurchaseAndroidPlatformAddition.queryPastPurchases`, i.e. the UUID passed in to `applicationUserName` is ignored.

**Comment by dam-ease** [comment]
Hi @jesper372. Thanks for filing this issue. Can you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) to help triage this further?

**Comment by jesper372** [comment]
@dam-ease Here is a minimal complete reproducible example, to be used on Android. The program has two products available for sale (when testing, replace their IDs with your own product IDs). To reproduce the issue:

1. Purchase one of the products. Note that the program deliberately makes the verification of the purchase fail, in order that the purchase appear in a subsequent call to `InAppPurchaseAndroidPlatformAddition.queryPastPurchases` (see step 3). Also, note that when the purchase is made, a specific UUID is being passed to the `applicationUserName` argument in `GooglePlayPurchaseParam`.
2. Purchase the other product. Note that again, the verification deliberately fails, and that for this product, a different UUID to that in step 1 is passed to the `applicationUserName` argument in `GooglePlayPurchaseParam`.
3. Press the "Retrieve uncompleted purchases" button. This has the effect of calling `InAppPurchaseAndroidPlatformAddition.queryPastPurchases`, **with one of the above UUIDs** passed as the `applicationUserName` argument.

**Expected result**
In step 3, I would expect only one uncompleted purchase to be retrieved; specifically, the purchase whose `applicationUserName` argument / UUID matches that passed to the `applicationUserName` argument in `InAppPurchaseAndroidPlatformAddition.queryPastPurchases`.

**Actual result**
In step 3, **both** uncompleted purchases are retrieved, i.e. the UUID passed as the `applicationUserName` argument to `InAppPurchaseAndroidPlatformAddition.queryPastPurchases` has effectively been ignored.

```
import 'dart:async';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:in_app_purchase/in_app_purchase.dart';
import 'package:in_app_purchase_android/in_app_purchase_android.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const MyApp());
}

const String _cons1y = 'cons1y';
const String _co4 = 'co4';
const List<String> _productIds = <String>[_cons1y, _co4];

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final InAppPurchase _inAppPurchase = InAppPurchase.instance;
  late StreamSubscription<List<PurchaseDetails>> _subscription;
  List<ProductDetails> _products = <ProductDetails>[];
  bool _isAvailable = false;
  bool _purchasePending = false;
  bool _loading = true;
  String? _queryProductError;
  final uuid1 = '1293a822-417d-4edb-9b7c-4ee406b7b7d8';
  final uuid2 = 'b3df5d70-7ca6-4e30-bb07-01873c5bc500';

  @override
  void initState() {
    super.initState();
    final Stream<List<PurchaseDetails>> purchaseStream = _inAppPurchase.purchaseStream;
    _subscription = purchaseStream.listen((List<PurchaseDetails> purchaseDetailsList) {
      _processPurchases(purchaseDetailsList);
    }, onDone: () {
      _subscription.cancel();
    }, onError: (Object error) {
    });
    initStoreInfo();
  }

  Future<void> initStoreInfo() async {
    final bool isAvailable = await _inAppPurchase.isAvailable();
    if (!isAvailable) {
      setState(() {
        _isAvailable = isAvailable;
        _products = <ProductDetails>[];
        _purchasePending = false;
        _loading = false;
      });
      return;
    }

    final ProductDetailsResponse productDetailResponse = await _inAppPurchase.queryProductDetails(_productIds.toSet());
    if (productDetailResponse.error != null) {
      setState(() {
        _queryProductError = productDetailResponse.error!.message;
        _isAvailable = isAvailable;
        _products = productDetailResponse.productDetails;
        _purchasePending = false;
        _loading = false;
      });
      return;
    }

    if (productDetailResponse.productDetails.isEmpty) {
      setState(() {
        _queryProductError = null;
        _isAvailable = isAvailable;
        _products = productDetailResponse.productDetails;
        _purchasePending = false;
        _loading = false;
      });
      return;
    }

    setState(() {
      _isAvailable = isAvailable;
      _products = productDetailResponse.productDetails;
      _purchasePending = false;
      _loading = false;
    });
  }

  @override
  void dispose() {
    _subscription.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final List<Widget> stack = <Widget>[];
    if (_queryProductError == null) {
      stack.add(
        ListView(
          children: <Widget>[
            _buildProductList(),
            Center(
              child: SizedBox(
                width: 280.0,
                child: ElevatedButton(
                  style: TextButton.styleFrom(
                      foregroundColor: Colors.white, backgroundColor: Colors.green[800]
                  ),
                  onPressed: _isAvailable && !_loading && !_purchasePending ? () {
                    _retrievePastPurchasesIfAndroid();
                  } : null,
                  child: const Text('Retrieve uncompleted purchases'),
                ),
              ),
            ),
          ],
        ),
      );
    } else {
      stack.add(Center(
        child: Text(_queryProductError!),
      ));
    }
    if (_purchasePending) {
      stack.add(
        const Stack(
          children: <Widget>[
            Opacity(
              opacity: 0.3,
              child: ModalBarrier(dismissible: false, color: Colors.grey),
            ),
            Center(
              child: CircularProgressIndicator(),
            ),
          ],
        ),
      );
    }

    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('IAP Example'),
        ),
        body: Stack(
          children: stack,
        ),
      ),
    );
  }

  Card _buildProductList() {
    if (_loading) {
      return const Card(child: ListTile(leading: CircularProgressIndicator(), title: Text('Fetching products...')));
    }
    if (!_isAvailable) {
      return const Card();
    }
    final List<ListTile> productList = <ListTile>[];
    productList.addAll(_products.map(
      (ProductDetails productDetails) {
        return ListTile(
          title: Text(productDetails.title),
          subtitle: Text(productDetails.description),
          trailing: TextButton(
            style: TextButton.styleFrom(foregroundColor: Colors.white, backgroundColor: Colors.green[800]),
            onPressed: () {
              PurchaseParam purchaseParam;
              if (Platform.isAndroid) {
                purchaseParam = GooglePlayPurchaseParam(
                  productDetails: productDetails,
                  applicationUserName: productDetails.id == _cons1y ? uuid1 : uuid2,
                );
              } else {
                purchaseParam = PurchaseParam(
                  productDetails: productDetails,
                  applicationUserName: productDetails.id == _cons1y ? uuid1 : uuid2,
                );
              }
              _inAppPurchase.buyConsumable(purchaseParam: purchaseParam, autoConsume: false);
            },
            child: Text(productDetails.price),
          ),
        );
      },
    ));

    return Card(child: Column(children: productList));
  }

  Future<void> _retrievePastPurchasesIfAndroid() async {
    if (Platform.isAndroid) {
      // Attempt to retrieve uncompleted purchases for user with id "uuid1" only:
      final purchaseDetailsResponse = await _inAppPurchase
          .getPlatformAddition<InAppPurchaseAndroidPlatformAddition>()
          .queryPastPurchases(applicationUserName: uuid1);
      if (purchaseDetailsResponse.error != null) return;
      final purchaseDetails = purchaseDetailsResponse.pastPurchases;
      await _processPurchases(purchaseDetails);
    }
  }

  void _showPendingUI() {
    setState(() {
      _purchasePending = true;
    });
  }

  void _handlePendingPurchaseCancelled(PurchaseDetails purchaseDetails) {
    setState(() {
      _purchasePending = false;
    });
  }

  Future<void> _deliverProduct(PurchaseDetails purchaseDetails) async {
    setState(() {
      _purchasePending = false;
    });
  }

  void _handleError(IAPError error) {
    setState(() {
      _purchasePending = false;
    });
  }

  Future<bool> _verifyPurchase(PurchaseDetails purchaseDetails) async {
    // Simulate verification of the purchase failing (say, because the backend is not reachable):
    return false;
  }

  void _handleInvalidPurchase(PurchaseDetails purchaseDetails) {
    setState(() {
      _purchasePending = false;
    });
  }

  Future<void> _processPurchases(List<PurchaseDetails> purchaseDetailsList) async {
    for (final PurchaseDetails purchaseDetails in purchaseDetailsList) {
      if (purchaseDetails.status == PurchaseStatus.pending) {
        _showPendingUI();
      } else if (purchaseDetails.status == PurchaseStatus.canceled) {
        _handlePendingPurchaseCancelled(purchaseDetails);
      } else {
        if (purchaseDetails.status == PurchaseStatus.error) {
          _handleError(purchaseDetails.error!);
        } else if (purchaseDetails.status == PurchaseStatus.purchased) {
          final bool valid = await _verifyPurchase(purchaseDetails);
          if (valid) {
            _deliverProduct(purchaseDetails);
          } else {
            _handleInvalidPurchase(purchaseDetails);
            return;
          }
        }
        if (purchaseDetails.pendingCompletePurchase) {
          await _inAppPurchase.completePurchase(purchaseDetails);
          if (Platform.isAndroid) {
            final androidAddition =
            InAppPurchase.instance.getPlatformAddition<InAppPurchaseAndroidPlatformAddition>();
            await androidAddition.consumePurchase(purchaseDetails);
          }
        }
      }
    }
  }
}
```

**Comment by dam-ease** [comment]
Hi @jesper372. Thanks for filing this issue. I tried reproducing this using the UUID provided in the code sample, at step 3, I am unable to view uncompleted purchases. Can you possibly provide a UUID with uncompleted purchases?

**Comment by dam-ease** [comment]
Meant to refer to productId and not UUID. Thanks for the detailed explanation.

**Comment by gmackall** [comment]
My understanding is that the underlying Play Billing Library uses the users google account, and that the `applicationUserName` that is passed in to `buyConsumable` (through `purchaseParams`) is then used by [setObfuscatedAccountId](https://github.com/flutter/packages/blob/eed8df711a3daff0e8017f9d62c5689338a4e0d6/packages/in_app_purchase/in_app_purchase_android/android/src/main/java/io/flutter/plugins/inapppurchase/MethodCallHandlerImpl.java#L323) to be associated with the users google account. 

The [documentation for this method specifically](https://developer.android.com/reference/com/android/billingclient/api/BillingFlowParams.Builder#setObfuscatedAccountId(java.lang.String)) calls out that the obfuscated account id should be uniquely associated with the account, which would mean that (as is done in this example) setting it differently for different purchases (while the user is using the same google account) would be a misuse of the underlying apis.

As far as I can tell, the reason that it is unused is that (if the `applicationUserName` is set correctly when making purchases) the filtering would either be "all" (if the `applicationUserName` passed to `queryPastPurchases` is the one uniquely associated with the account) or "none" (otherwise). As for why it exists as a parameter, I would assume that it has to do with it being useful for the iOS implementation of this method, back when it existed on iOS. It could probably be removed now.

I'm still relatively new as a code owner for the android implementation of in_app_purchase, though, so let me know if any of the above sounds off, or you have more questions.
