### ISSUE TITLE
Bring back fade transition to Material page transition

### ISSUE THREAD

**Issue by xster** [flutter/flutter#12877]
Was removed in #9472 for performance reasons. Mitigate performance issue and bring back the transition effect.

**Comment by eseidelGoogle** [comment]
@chinmaygarde had some planned compositor optimizations.  You might ask him if he has any planned which would make this easier.

**Comment by passsy** [comment]
@Hixie please reopen

**Comment by xster** [comment]
Reopening since it was reverted. 

Might help doing https://github.com/flutter/flutter/issues/13173 first.

**Comment by brianegan** [comment]
Has there been any movement on this one? I feel like this is a pretty visible / janky bug to expose to users... all "back" transitions look really rough.

**Comment by sethladd** [comment]
I noticed that on Android at least, the back animation (the material sheet sliding down) seems to simply disappear half-way through the animation down. I'm assuming this is a bug, because it used to be very beautiful :)

**Comment by levrik** [comment]
@Hixie Was this disabled again on Android? Wanted to propose Flutter for some new project but now I'm not sure anymore if people would be positive about Flutter.

**Comment by Hixie** [comment]
There's a flag you can flip right now to decide if it should be enabled or not:
[`MaterialPageRoute.debugEnableFadingRoutes`](https://master-docs-flutter-io.firebaseapp.com/flutter/material/MaterialPageRoute/debugEnableFadingRoutes.html)

It currently defaults to false though we may change it to true in the next few days. We're working on a real fix though to make it fast so we can enable it proudly.

**Comment by levrik** [comment]
@Hixie Thank you! Looking forward to the real fix 🙂

**Comment by sfunke** [comment]
No progress on this issue (beta 0.3.2)?
**This is very visible jank and gives a wrong impression of Flutter to potential adopters.**
Setting `MaterialPageRoute.debugEnableFadingRoutes`to true seems no real solution for production use.

I propose to reopen, since all linked issues here are closed as well.

**Comment by eseidelGoogle** [comment]
@xster @Hixie I believe this is still being worked on correct?  Is this the right bug to track the work?

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/issues/13736 is the issue where this is being tracked.
We currently have multiple engineers focused on fixing the performance issues involved in a fade transition; it is one of our top issues currently.
