### ISSUE TITLE
[iOS] OutOfMemory

### ISSUE THREAD

**Issue by daniloapr** [flutter/flutter#128705]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Leaving the app open is causing a crash with the following report in Sentry:

OutOfMemory: The OS most likely terminated your app because it overused RAM.

It is consistenly happening in some devices, but I can't reproduce it in others. One of the devices 

Devices with such reports:
iPhone10,6 (iPhone X GSM)| iOS 16.4.1
iPhone12,1 (iPhone 11) | iOS 16.3.1
iPhone12,3 (iPhone 11 Pro) | iOS 16.5, 16.4.1, 16.4
iPhone12,5 (iPhone 11 Pro Max) | iOS 16.5
iPhone13,2 (iPhone 12) | iOS 16.4.1
iPhone15,3 (iPhone 14 Pro Max) | iOS 16.0.3

All device have reported 2.1 GiB to 4.7 GiB of Usable Memory

It's happening in two different Flutter apps. Both of them don't have (or don't seem to have) memory intensive operations.

### Expected results

Not crashing the app

### Actual results

OutOfMemory: The OS most likely terminated your app because it overused RAM.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.1, on macOS 13.3.1 22E772610a darwin-arm64, locale en-BR)
    • Flutter version 3.10.1 on channel stable at /Users/danilorego/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (4 weeks ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/danilorego/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (4 available)
    • Danilo’s iPhone (mobile) • 00008101-001538162200801E            • ios            • iOS 16.5 20F66
    • iPhone 11 Pro (mobile)   • FDAD8C42-BBB9-4593-9E7C-DFC73F829667 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)          • macos                                • darwin-arm64   • macOS 13.3.1 22E772610a darwin-arm64
    • Chrome (web)             • chrome                               • web-javascript • Google Chrome 114.0.5735.106
    ! Error: Apple Watch de Danilo has recently restarted. To use Apple Watch de Danilo with Xcode, unlock it and its companion iPhone (code 19)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by pranavo72bex** [comment]
Any Update regarding this issue?

**Comment by darshankawar** [comment]
@daniloapr 
Can you provide us the complete error log ?
Going by the error you shared `OutOfMemory: The OS most likely terminated your app because it overused RAM.`, it could be happening due to usage of images in your app which might be consuming more memory.

See if [this](https://stackoverflow.com/questions/75246192/why-is-my-flutter-app-crashing-randomly-and-how-to-find-potential-memory-leak) is helpful in your case or not.
