### ISSUE TITLE
Linux Fuchsia SDK roller broken on memfs dependency

### ISSUE THREAD

**Issue by eyebrowsoffire** [flutter/flutter#128703]
Linux Fuchsia SDK -> Flutter Engine roller is broken. Here is an example roll failure: https://github.com/flutter/engine/pull/42742

```
Using prebuilt Dart SDK binary. If you are editing Dart sources and wish to compile the Dart SDK, set `--no-prebuilt-dart-sdk`.
Generating GN files in: out/fuchsia_debug_x64
ERROR Unresolved dependencies.
//flutter/shell/platform/fuchsia/runtime/dart/utils:utils(//build/toolchain/fuchsia:fuchsia)
  needs //build/fuchsia/pkg:memfs(//build/toolchain/fuchsia:fuchsia)
//flutter/shell/platform/fuchsia/runtime/dart/utils:utils_product(//build/toolchain/fuchsia:fuchsia)
  needs //build/fuchsia/pkg:memfs(//build/toolchain/fuchsia:fuchsia)
```

`memfs` was removed from the Fuchsia Linux SDK here: https://fxrev.dev/867584.

However, flutter still references it in the embedder here: https://github.com/flutter/engine/blob/6e2c71adccade018c824e1f39585b4724ed2e77e/shell/platform/fuchsia/runtime/dart/utils/BUILD.gn#LL46C16-L46C16

**Comment by tamird** [comment]
This should've been closed by https://github.com/flutter/engine/pull/42773 but the bot squashed the commits and threw away the messages.
