### ISSUE TITLE
engine_v2: unable to add duplicate build with different flags

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#128710]
## Description

I'm trying to add a duplicate build for the android debug engine that is not archived and uses different GN flags.  This is a build used just by engine developers for development, that I want to make sure doesn't get broken.

When attempting to name it something new (example: android_debug_arm64_validation_layers) the build fails because there is the assumption that that is the name of the directory GN generates.

I switched the name back to `android_debug_arm64` but a different infra failure happens:

```
Infra Failure: Step('Download for build 8778477949171989393 and cas key android_debug_arm64') (retcode: 1)
```

infra failure: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20linux_android_debug_engine/11612/overview
pr: https://github.com/flutter/engine/pull/42724

**Comment by godofredoc** [comment]
This is working as intended, build names are expected to match the output directory to be able to archive them and reuse on global generators or test.

If the build output is not needed you can add a gn_archive property to the build config e.g. https://cs.opensource.google/flutter/engine/+/master:ci/builders/standalone/linux_license.json;l=6?q=archive&ss=flutter%2Fengine:ci%2Fbuilders%2F&start=11. Please note that this will ignore the archive and will prevent from using the build outputs in global generators and tests.

**Comment by gaaclarke** [comment]
closing as it's WAI
