### ISSUE TITLE
Material 3 showTimePicker issues with selected time container 

### ISSUE THREAD

**Issue by ahmadhanis** [flutter/flutter#128785]
Having an issue with timepicker when the material 3 theme enable in the project.

`theme: ThemeData(
        useMaterial3: true,`

<img width="260" alt="image" src="https://github.com/flutter/flutter/assets/36687333/f62e91da-71f9-4b0c-9a8f-4e9b16f559e7">

disabling material 3, it works just fine.

<img width="236" alt="image" src="https://github.com/flutter/flutter/assets/36687333/6307be13-b75e-4c85-9e34-5b55b89d0def">

**Comment by TahaTesser** [comment]
Hi @ahmadhanis 
Can you please provide a reproducible code sample and `flutter doctor -v ` results?

**Comment by ahmadhanis** [comment]
> Hi @ahmadhanis Can you please provide a reproducible code sample and `flutter doctor -v ` results?

[√] Flutter (Channel stable, 3.10.0, on Microsoft Windows [Version 10.0.22621.1702], locale en-MY)
    • Flutter version 3.10.0 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (5 weeks ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\USER\AppData\Local\Android\sdk
    • Platform android-33-ext5, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33516.290
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] VS Code (version 1.79.0)
    • VS Code at C:\Users\USER\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.66.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows 
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 114.0.5735.110
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 114.0.1823.43

[√] Network resources
    • All expected network resources are available.

I'm using the DateTimeField to trigger showTimePicker

                   DateTimeField(
                    controller: _timecontroller,
                    validator: (val) => val == null
                        ? AppLocalization.of(context)
                            .getTranslatedValue("Select time")
                            .toString()
                        : null,
                    decoration: InputDecoration(
                      labelText: AppLocalization.of(context)
                          .getTranslatedValue("Set Appointment Time")
                          .toString(),
                      icon: const Icon(
                        Icons.access_time,
                        // color: Color.fromRGBO(57, 195, 219, 1),
                      ),
                    ),
                    format: formattime,
                    onShowPicker: (context, currentValue) async {
                      final time = await showTimePicker(
                        builder: (context, child) {
                          return Localizations.override(        
                            context: context,
                            locale: _locale,
                            child: child,
                          );
                        },
                        context: context,
                        initialTime: TimeOfDay.fromDateTime(
                            currentValue ?? DateTime.now()),
                      );
                      if (time != null) {
                        timecal =
                            formattimecal.format(DateTimeField.convert(time)!);
                        debugPrint(timecal);
                      }
                      return DateTimeField.convert(time);
                    },
                  )

Build method theme with useMaterial3 set to true.

     theme: ThemeData(
        useMaterial3: true,
        colorScheme: lightColorScheme,
        textTheme: GoogleFonts.quicksandTextTheme(
          Theme.of(context).textTheme.apply(),
        ),
      ),

**Comment by ahmadhanis** [comment]
Solved the issue with overriding theme. Maybe not be the best solution. 

                        return Localizations.override(
                            context: context,
                            locale: _locale,
                            child: Theme(
                                data: ThemeData.light(useMaterial3: true),
                                child: SizedBox(
                                  child: child,
                                )),
                          );

**Comment by TahaTesser** [comment]
@ahmadhanis 
We'd still like to reproduce and address this issue.  However `DateTimeField` seems to be part of a third-party [package](https://pub.dev/packages/date_field).  If you could reproduce this without this package. please share the complete Flutter sample.

Thank you!

**Comment by andryot** [comment]
The usage of `useMaterial3` flag in copyWith is causing the reported behaviour.
### Steps to Reproduce

1. Execute flutter run on the code sample
2. Press the Show Time Picker button

**Expected results:**
The time picker hour an minute are not overflowing. The colon that separates hours and minutes is clearly visible and in the middle.

**Actual results:**
The time picker hour an minute are overflowing and the colon is overflown.
<details>
<summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData().copyWith(useMaterial3: true),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: TextButton(
          onPressed: () =>
              showTimePicker(context: context, initialTime: TimeOfDay.now()),
          child: const Text("Show Time Picker"),
        ),
      ),
    );
  }
}
```
</details>



|  ThemeData(useMaterial3: true)| ThemeData().copyWith(useMaterial3: true) |
| ------------- | ------------- |
| ![simulator_screenshot_B1E0C0E5-8034-4DD7-8EA7-4BE463B446CE](https://github.com/flutter/flutter/assets/37480708/c348795e-7829-4df2-b2c8-eb041133ddae) | ![simulator_screenshot_321EB744-77BA-49F9-AB06-76B9739891A2](https://github.com/flutter/flutter/assets/37480708/eabc2626-7e2b-4bf5-b3c2-6a507166233b)  |

<details>
<summary>Flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4 22F66 darwin-arm64, locale en-SI)
    • Flutter version 3.10.5 on channel stable at /Users/andraz/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (4 days ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/andraz/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/andraz/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.79.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • 6B531CA5-88BA-4934-807F-500D95958DC2 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.4 22F66
      darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Brave Browser
      110.1.48.164

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
</details>
