### ISSUE TITLE
Setting `forceElevated` to `true` on a `SliverAppBar.large` or `SliverAppBar.medium` casues a duplicate title.

### ISSUE THREAD

**Issue by dickermoshe** [flutter/flutter#128750]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Create a Sliver App Bar with the `large` or `medium` constructor.
You will see the title appear in the flexible bottom and on the top.

### Expected results

Force elevated should only affect the color and shadows of the expanded app bar.
It should not affect how the title appears.

### Actual results

The title appears twice

### Code sample

<details><summary>Code sample</summary>

[DartPad](https://dartpad.dev/?id=5e64cb30af841cce98b2bae4490c0f08  )

```dart
import 'package:flutter/material.dart';

const Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: darkBlue,
      ),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: CustomScrollView(
          slivers:[SliverAppBar.medium(title:Text("Hi"),forceElevated:true)]
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

<img width="506" alt="image" src="https://github.com/flutter/flutter/assets/75931499/3d2000c9-d2fa-4946-8993-b76950dc4e74">

</details>

### Logs

<details><summary>Logs</summary>

```console
I'm using dartpad and have no way to retrieve them
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
I'm using dartpad and have no way to retrieve them
```

</details>

**Comment by TahaTesser** [comment]
Hi @dickermoshe 
This is working as expected. 

When the content is scrolled under the app bar is elevated and the regular title is visible.  
`forceElevated` simply forces an elevation even if the content isn't scrolled under the app bar, as a result, you see the regular title. 

Both title and forceElevated are working as expected, however, if you still wanna have elevation and regular title without scrolling under. You can remove the large title in the `flexibleSpace` parameter or the regular title, e.g `const SizedBox.shrink()`.

Hope this answers your issue.
