### ISSUE TITLE
Unable To Run My App On My IQOO Physical Device Connected Through USB 

### ISSUE THREAD

**Issue by anmol420** [flutter/flutter#128784]
I just made a simple app which says hello and has only one file - `main.dart`. 

When I tried to run it pressing `Ctrl+F5`, it started as I expected it. But the debug console is stuck at -

```dart
Launching lib\main.dart on I2208 in debug mode...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
I/flutter (29862): The Dart VM service is listening on ************************************
```

It is not processing further and even when I check the phone, it is showing a black screen.

I tried `flutter clean` and `flutter doctor -v` still no help was found.

Please Suggest Me A Way To Fix It.

**Comment by huycozy** [comment]
Hi @anmol420 
Are you using Vivo phone? What is the device's Android version? 

There was an old issue that has been pointed out this issue an issue with Vivo phone on Android 11 and it's not issue with Flutter. If you are using the same Android version, it seems to be solved by upgrading to Android 12.

More generally, in case you can not downgrade the OS, please check these issues if they are similar to your case: https://github.com/flutter/flutter/issues/106086 (crash while launching) and https://github.com/flutter/flutter/issues/81906 (devtools is not attaching).

**Comment by anmol420** [comment]
Hello @huycozy !

Yeah IQOO is a Vivo product. But the android version I am using is Android 13 and everything in my phone is up to date. 

I saw #106086  and #81906 but could not find much useful content into it.

Even on checking StackOverflow, I am getting the things which I already did in the past but nothing happened.

**Comment by huycozy** [comment]
I forgot to mention the issue with Android version above (it's https://github.com/flutter/flutter/issues/82520 for reference and [related comment](https://github.com/flutter/flutter/issues/82520#issuecomment-1001462546))

Regarding your issue with Android 13, there was also an old issue for it here https://github.com/flutter/flutter/issues/117019 but it's unfortunately being closed as it's Vivo's issue (please see https://github.com/flutter/flutter/issues/117019#issuecomment-1352876225 for more information)

I'm therefore going to close this bug for now. Please try to contact Vivo's developers for better support there.

**Comment by anmol420** [comment]
I saw the above references you provided and came to the conclusion that such issues are common in *VIVO* and *IQOO* phones and it was fixed in Android 12 but issue again came up in Android 13.

Anyways, thank you for your help and support. I will now run my app using the terminal (as it is the one which is working).
