### ISSUE TITLE
Pan and zoom widget

### ISSUE THREAD

**Issue by xinoxapps** [flutter/flutter#12878]
Would be very useful if the scroll view can be extended with the following features:

- Zoom in and out
- Scroll in all directions, 
- Optional lock on horz or vert.

Use case: Shop App
Scroll a photo in all directions and pinch zoom-in/out.

**Comment by Hixie** [comment]
Having a widget to do zoom and pan of a child widget definitely seems like a worthy feature for us to have, though I don't think it would be part of ScrollView per se.

**Comment by sroddy** [comment]
It may be worth to add that from the perspective of an iOS developer that has no knowledge of the Android world, scroll views (i.e. `UIScrollView`) are bidirectional and have zoom/pan/pagination support by default.
The fact that Flutter ones are instead locked in one direction and way less powerful can lead to some sort of confusion, at least in the beginning.

**Comment by zoechi** [comment]
Somewhat related #25164

**Comment by 0SM0S** [comment]
Are there any news regarding this issue?

**Comment by justinmc** [comment]
@0SM0S I'm just about to land a demo in the gallery app (examples/flutter_gallery) that shows how to do this sort of thing.  The PR is https://github.com/flutter/flutter/pull/25164 and the relevant file is [here](https://github.com/flutter/flutter/blob/b4efb7eb1e6274df653424a2bbc1d71100ced60c/examples/flutter_gallery/lib/demo/pan_and_zoom_demo_transform_interaction.dart).

My goal is to solve this issue by pulling that code out into its own widget as a part of Flutter itself, but maybe that example code will help in the meantime.

**Comment by justinmc** [comment]
Gallery demo was merged. After the next release you'll be able to find it under Studies => 2D Tranformations. Hopefully widget coming soon.

**Comment by VladyslavBondarenko** [comment]
Related to https://github.com/flutter/flutter/issues/20175

**Comment by justinmc** [comment]
InteractiveViewer can do this now.  Direction locking is not yet implemented, but I've created a separate issue specifically for that: https://github.com/flutter/flutter/issues/58043

**Comment by czaku** [comment]
@justinmc is that available in 1.17.4 ? Been trying to find it and no idea where is it going to be released..

**Comment by justinmc** [comment]
Direction locking is being implemented in https://github.com/flutter/flutter/pull/61019 as `alignPanAxis`.
