### ISSUE TITLE
[Impeller] Vulkan: parallelize encoding of the swapchain images

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#128899]
## observed behavior
In the vulkan backend we are creating swapchains with 2-3 images, but we are only accessing one image at a time.  `SwapchainImplVK::AcquireNextDrawable` is blocking until `SwapchainImplVK::Present` is complete via the `FrameSynchronizer::aquire` fence so that only swapchain image is used at a time.

## expected behavior
I expect `SwapchainImplVK::AcquireNextDrawable` to return as long as the swapchain images are not exhausted.  That way the next frames can start encoding while the previous ones are rendering.

## links
- [SwapchainImplVK::AcquireNextDrawable fence wait](https://github.com/gaaclarke/engine/blob/d22442d41a2f3b062661d32d94819c6cf6455b1a/impeller/renderer/backend/vulkan/swapchain_impl_vk.cc#L325)

**Comment by gaaclarke** [comment]
I verified that we only have 1 image inflight at a time with the following print statements.  I ran the gallery in debug mode and used the app and the count never got over 1 despite poor performance.
```diff
--- a/impeller/renderer/backend/vulkan/swapchain_impl_vk.cc
+++ b/impeller/renderer/backend/vulkan/swapchain_impl_vk.cc
@@ -307,6 +307,8 @@ std::shared_ptr<Context> SwapchainImplVK::GetContext() const {
   return context_.lock();
 }
 
+static std::atomic<int> swapchain_images = 0;
+
 SwapchainImplVK::AcquireResult SwapchainImplVK::AcquireNextDrawable() {
   auto context_strong = context_.lock();
   if (!context_strong) {
@@ -336,6 +338,8 @@ SwapchainImplVK::AcquireResult SwapchainImplVK::AcquireNextDrawable() {
       *sync->render_ready,                   // signal semaphore
       nullptr                                // fence
   );
+  swapchain_images.fetch_add(1);
+  FML_LOG(ERROR) << "swapchain images: " << swapchain_images.load();
 
   if (acq_result == vk::Result::eSuboptimalKHR ||
       acq_result == vk::Result::eErrorOutOfDateKHR) {
@@ -437,6 +441,8 @@ bool SwapchainImplVK::Present(const std::shared_ptr<SwapchainImageVK>& image,
   present_info.setImageIndices(indices);
   present_info.setWaitSemaphores(*sync->present_ready);
 
+  swapchain_images.fetch_add(-1);
+
   switch (auto result = present_queue_.presentKHR(present_info)) {
     case vk::Result::eErrorOutOfDateKHR:
```

I also verified that on this device we are requesting 4 images with the following print statement:
```diff
--- a/impeller/renderer/backend/vulkan/swapchain_impl_vk.cc
+++ b/impeller/renderer/backend/vulkan/swapchain_impl_vk.cc
@@ -194,6 +194,7 @@ SwapchainImplVK::SwapchainImplVK(const std::shared_ptr<Context>& context,
       caps.maxImageCount == 0u ? caps.minImageCount + 1u
                                : caps.maxImageCount  // max zero means no limit
   );
+  FML_LOG(ERROR) << "swapchain_info.minImageCount:" << swapchain_info.minImageCount;
   swapchain_info.imageArrayLayers = 1u;
   swapchain_info.imageUsage = vk::ImageUsageFlagBits::eColorAttachment;
   swapchain_info.preTransform = caps.currentTransform;
@@ -307,6 +308,8 @@ std::shared_ptr<Context> SwapchainImplVK::GetContext() const {
   return context_.lock();
 }
```

**Comment by gaaclarke** [comment]
I increased the `swapchain_info.minImageCount` to 64 and `kMaxFramesInFlight` to 8 and the count still never increased over 1.  So it doesn't seem like the GPU is holding onto all the images except one and parallelizing the work on them.

**Comment by jonahwilliams** [comment]
Another possibility is that the command encoding is taking so long that the GPU is always able to run ahead of the workload and so we never get more than 1 frame in flight

**Comment by gaaclarke** [comment]
I'm just noticing in the code that there are 2 different mechanisms to throttle parallelization of encoding threads:
1) `impeller::Renderer::kDefaultMaxFramesInFlight`
1) `impeller::kMaxFramesInFlight` in `swapchain_impl_vk.cc`

I'm not sure it is a problem or related, I just wanted to note it in case this requires more investigation.

**Comment by jonahwilliams** [comment]
This is done, or was always done - but we have multiple frames in flight as of today.

**Comment by jonahwilliams** [comment]
(We shouldn't parallelize entity pass work because then we'll compete with ourselves for resources)
