### ISSUE TITLE
Account for bottom safe area for interactive widgets

### ISSUE THREAD

**Issue by xster** [flutter/flutter#12883]
![img_2770](https://user-images.githubusercontent.com/156888/32411204-b9a98494-c192-11e7-8c49-8104475ec166.PNG)

**Comment by xster** [comment]
![img_2771](https://user-images.githubusercontent.com/156888/32411229-2921b6ac-c193-11e7-9b1e-cfd78e3855d1.PNG)

**Comment by xster** [comment]
Do after #12895 is available

**Comment by Hixie** [comment]
I believe @cbracken has a fix for this now.

**Comment by xster** [comment]
@cbracken sounds like you're doing this now. Can I assign this to you?

**Comment by cbracken** [comment]
Yes please :)

**Comment by xster** [comment]
This is actually a dupe of #12099.
