### ISSUE TITLE
Flutter google map compass for ios view

### ISSUE THREAD

**Issue by testingsrk** [flutter/flutter#128893]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

So basically we are not able to use the compass function the same as the Google actual app does after starting any specific route for one destination map screen goes straight automatically by compass but with integrated SDK i am not able to use that function so can someone help me on that someone

### Proposal

![image](https://github.com/flutter/flutter/assets/136633874/46652a8c-6095-40ce-a9ba-fdc5093f5dbe)

**Comment by darshankawar** [comment]
Thanks for the report @testingsrk 
Can you take a look at [this](https://github.com/flutter/flutter/issues/37588) issue and check if it helps in your case or not.
