### ISSUE TITLE
[Impeller]: Incorrect display of text if an emoji is present on screen

### ISSUE THREAD

**Issue by azatech** [flutter/flutter#128879]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I've viewed CLOSED issues https://github.com/flutter/flutter/issues/127935 and https://github.com/flutter/flutter/issues/126514

I am still facing the same issue in 3.10.4

1. Create a Flutter app for iOS with Impeller enabled, add some text to the layout
2. Try to add text with an emoji

### Expected results

Adding an emoji does not alter the visualization of the remaining text.

### Actual results

Adding an emoji does actually alter how the rest of the text is displayed on the screen.

### Code sample

<details><summary>Code sample</summary>

```dart
class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    final items = ListItems().items;
    return Scaffold(
      appBar: AppBar(
        title: const Text('Impeller emoji bug 3.10.4'),
      ),
      body: ListView.builder(
        itemCount: items.length,
        prototypeItem: ListTile(
          title: Text(items.first),
        ),
        itemBuilder: (context, index) {
          return ListTile(
            title: Text(items[index]),
          );
        },
      ),
    );
  }
}

class ListItems {
  final items = [
    'Impeller test 1',
    'Impeller test 2',
    'Impeller test 3',
    'Impeller test 4',
    'Impeller test 5',
    'Impeller test 6',
    'Impeller test 7',
    'Impeller test 8',
    'Impeller test 9',

    'Impeller test 10',
    'Impeller test 11',
    'Impeller test 12',
    'Impeller test 13',
    'Impeller test 14',
    'Impeller test 15',
    'Impeller test 16',
    'Impeller test 17',
    'Impeller test 18',
    'Impeller test 19',

    'Impeller test 20',
    'Impeller test 21',
    'Impeller test 22',
    'Impeller test 23',
    'Impeller test 24',
    'Impeller test 25',
    'Impeller test 26',
    'Impeller test 27',
    'Impeller test 28',
    'Impeller test 29',

    'Bug appears if you seeing any emoji on screen 🛑🛑🛑',

    'Impeller test 30',
    'Impeller test 31',
    'Impeller test 32',
    'Impeller test 33',
    'Impeller test 34',
    'Impeller test 35',
    'Impeller test 36',
    'Impeller test 37',
    'Impeller test 38',
    'Impeller test 39',

    'Impeller test 40',
    'Impeller test 41',
    'Impeller test 42',
    'Impeller test 43',
    'Impeller test 44',
    'Impeller test 45',
    'Impeller test 46',
    'Impeller test 47',
    'Impeller test 48',
    'Impeller test 49',
  ];
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/29102853/46c9cbe6-5b00-4b68-abf7-20387fbea466

https://github.com/flutter/flutter/assets/29102853/9451fc2f-5022-48b2-9a59-170b8e026767

![impeller_bug_2_impeller_bug_3 10 4](https://github.com/flutter/flutter/assets/29102853/7c876b95-3257-4541-b3fb-fd74f5a0e854)
![impeller_bug_3 10 4](https://github.com/flutter/flutter/assets/29102853/fe503322-5e77-4db7-a604-60992b844a00)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.4, on macOS 13.4 22F66 darwin-arm64, locale
    en-UA)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] Connected device (6 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by sunjianan9900** [comment]
> Hi @azatech. This seems to have been fixed on the latest master channel. You can confirm by switching and testing this on the latest `master`. I'll close this issue since it has been fixed. Thank you!

May I inquire how long this issue will approximately take to be merged into the stable version? It is relatively impactful to the user experience compared to other issues.

**Comment by dam-ease** [comment]
Hi @azatech. Please see https://github.com/flutter/flutter/wiki/Flutter-build-release-channels which explains the timelines for releases. This fix will be included in a future release.
