### ISSUE TITLE
[cocoon] can not rerun all failed tasks 

### ISSUE THREAD

**Issue by XilaiZhang** [flutter/flutter#128837]
the request handler at api/reset-prod-task seem to not rerun all failed tasks when supplied with parameters `commit`, `repo` and `task: all`

logs seen on the appengine side: [logs](https://pantheon.corp.google.com/logs/query;query=resource.type%3D%22gae_app%22%0Aresource.labels.module_id%3D%22default%22%0Aresource.labels.version_id%3D%22version-e291958%22%0A%22reset-prod-task%22;cursorTimestamp=2023-06-13T23:01:28.004Z?serviceId=default&project=flutter-dashboard)

**Comment by XilaiZhang** [comment]
cc @CaseyHillers

**Comment by godofredoc** [comment]
@XilaiZhang can you please post the full curl command?

**Comment by godofredoc** [comment]
Also can you please provide more details:

* what "seems no rerun all failed tasks mean"? did it run some tasks but not all, it didn't run any task
* was this on main or a release candidate branch?

**Comment by XilaiZhang** [comment]
right yeah i was following https://g3doc.corp.google.com/company/teams/flutter/infrastructure/playbook.md?cl=head#rerun-all-failed-tasks-for-a-commit to rerun the failed tasks on a release branch, but none of the failed task was rerun.

>what "seems no rerun all failed tasks mean"? did it run some tasks but not all, it didn't run any task

right yeah it didn't run any task

>was this on main or a release candidate branch?

its on a release branch

**Comment by ricardoamador** [comment]
Came across this today. @XilaiZhang it seems the code is expecting to find a branch parameter though I cannot say for sure what it is expecting as the curl command was never provided. Are you okay with closing this and reopening if you hit this again?

**Comment by ricardoamador** [comment]
Ah nevermind. I see the issue. If you want to run this against a release branch you need to specify the actual branch name otherwise it assumes the default branch which would be either main or master.

https://github.com/flutter/cocoon/blob/main/app_dart/lib/src/request_handlers/reset_prod_task.dart#L73
