### ISSUE TITLE
[Impeller] Code paths that end up in `*FilterContents` and supply a geometry that's larger than the max allowable RT size or subpass size fail to render anything and produce no warnings/errors.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#128807]
This test fails to render antyhing and produces no helpful error output in the wild, but validation errors in a unit test:

```cpp
TEST_P(EntityTest, ColorFilterContentsWithLargeGeometry) {
  Entity entity;
  entity.SetTransformation(Matrix::MakeScale(GetContentScale()));
  auto src_contents = std::make_shared<SolidColorContents>();
  src_contents->SetGeometry(
      Geometry::MakeRect(Rect::MakeLTRB(-300, -500, 30000, 50000)));
  src_contents->SetColor(Color::Red());

  auto dst_contents = std::make_shared<SolidColorContents>();
  dst_contents->SetGeometry(
      Geometry::MakeRect(Rect::MakeLTRB(300, 500, 20000, 30000)));
  dst_contents->SetColor(Color::Blue());

  auto contents = ColorFilterContents::MakeBlend(
      BlendMode::kSourceOver, {FilterInput::Make(dst_contents, false),
                               FilterInput::Make(src_contents, false)});
  entity.SetContents(std::move(contents));
  ASSERT_TRUE(OpenPlaygroundHere(entity));
}
```

We can hit this code path in a few ways:

- Certain usages of `drawVertices`
- Setting `invertColors` to true on `Paint`. 
- I think we can hit it via some kind of mask blur but I'm not sure.

**Comment by bdero** [comment]
I'd recommend adding support for the coverage hint to the remaining filters to solve this problem. So far we've only landed it for the GaussianBlur, but it should be supported by every filter. The coverage hint is fed to every single entity just before rendering.

Aside from solving this fidelity problem, doing so will also be a great performance win in general.
