### ISSUE TITLE
Not able to run iOS app in real device for debugging 

### ISSUE THREAD

**Issue by dineshsuneldcs** [flutter/flutter#128867]
Target debug_unpack_ios failed: Exception: Binary /Users/dineshsunel/Library/Developer/Xcode/DerivedData/Runner-gkmwxkkejvvrccautgfnpoopoizq/Build/Products/Debug-iphoneos/Flutter.framework/Flutter does not contain . Running lipo -info:

App is running in simulator , also I am able to generate IPA via Archive from Xcode.

XCode Version - 14.3 (main)
For Xcode version 14.3 I have already added Device Support files for 16.5 following this link https://github.com/filsv/iOSDeviceSupport

Xcode Version - 15.0 beta ( also not working for it)

Iphone OS version - 16.5

flutter doctor -v
[✓] Flutter (Channel stable, 3.10.4, on macOS 13.4 22F66 darwin-arm64, locale en-IN)
    • Flutter version 3.10.4 on channel stable at /Users/dineshsunel/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 682aa387cf (9 days ago), 2023-06-05 18:04:56 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/dineshsunel/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A5160n
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • EEC31633-45B9-45EF-8AFA-FB744DB736C5 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 114.0.5735.133

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by huycozy** [comment]
It looks like you are facing a situation that is similar to known issues (https://github.com/flutter/flutter/issues/125497, https://github.com/flutter/flutter/issues/125130). Please check if you have `arm64` on EXCLUDED_ARCHS and try removing EXCLUDED_ARCHS's values if any.

**Comment by dineshsuneldcs** [comment]
@huycozy  Thanks a Lot , Solution links you provided worked.
