### ISSUE TITLE
Debug adapter maps some file paths to the wrong location

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#128880]
In the debug adapter, we map `org-dartlang-sdk` URIs onto local file paths so that the IDE can open them:

https://github.com/flutter/flutter/blob/40bb615b0c96b2ca2ec2777fe9ea6aa20c815b14/packages/flutter_tools/lib/src/debug_adapters/flutter_base_adapter.dart#L99-L105

@CoderDake discovered that some mappings were not working in VS Code, for example `dart:core-patch/growable_array.dart`.

It turns out that `growable_array.dart` exists here:

```
flutter/bin/cache/dart-sdk/lib/_internal/vm/lib/growable_array.dart
```

but not here:

```
flutter/bin/cache/pkg/sky_engine/lib/_internal/vm/lib/growable_array.dart
```

This means the IDE fails to find the file.

Are we mapping to the wrong location? Should we be mapping to `dart-sdk` instead of `pkg/sky_engine` (except for `ui` which only exists in `sky_engine`)? Or are there other differences between these locations (other than sky_engine missing lots of files)? Do we need to conditionally map some URIs to one and some to the other (besides `ui`)?

I can make the change, but I'd like to ensure I understand the differences between these folders before I do, but I'm not where I can find the answer to that (@christopherfujino is this something you know, or can point me in the right direction?)

**Comment by christopherfujino** [comment]
> Should we be mapping to dart-sdk instead of pkg/sky_engine (except for ui which only exists in sky_engine)?

This sounds right to me, but I would only be guessing. @jonahwilliams is this correct?

**Comment by jonahwilliams** [comment]
seems reasonable, if it works

**Comment by DanTup** [comment]
It will certainly solve the issue I hit - but I don't know if it'll introduce other issues so I was hoping to better understand the relationship between those folders. For example:

- Will there ever be (`.dart`) files (besides `ui`) in `sky_engine` that are not in `dart-sdk`?
- Will the  (`.dart`) files that exist in both locations ever be different?

(I can check those for how things are _today_, but I don't know if the answer today guarantees the same tomorrow - if they are always the same, why does `sky_engine` contain a subset of duplicate files from the sdk?)

**Comment by jonahwilliams** [comment]
sky_engine is more or less what the analyzer uses for flutter project. my thought at the time was that it would have all the sources, but I guess not.

**Comment by DanTup** [comment]
Actually, this won't work :( The analyzer goes to sky_engine... so if the user Go-to-Definitions to a file, they end up in `sky_engine`. So if we map the debugger to dart-sdk, we're back to having two files the same and two sets of breakpoints.

So I guess we need to figure out the differences here. Which set of sources are the "correct" ones. If they are dart-sdk, then anayzer may be going to the wrong place. If sky_engine is correct, then we need to figure out why it doesn't contain all of the files.

**Comment by jonahwilliams** [comment]
The sources of sky_engine are glued together in the flutter/engine build. My money is on sky_engine being incorrect, and then the solution may be adding the missing files (and deleting any that are entirely unused).

https://github.com/flutter/engine/blob/944bf3fa31b5f3a863ad10a2dcd54db113f972aa/sky/packages/sky_engine/BUILD.gn#L129

**Comment by DanTup** [comment]
@jonahwilliams thanks! Is there someone that might be able to confirm (and hopefully fix) this? I don't think I know enough to propose a fix (at least not without some solid pointers :-) )

**Comment by DanTup** [comment]
I'm not sure what to do with that information 😆

**Comment by DanTup** [comment]
@zanderso is this something you might know about (I see you've committed to the file Jonah linked above)? Full context is above, but the question is about the relationship between `cache/pkg/sky_engine` and `cache/dart-sdk`. The `sky_engine` folder is missing many source files that are in `dart-sdk/lib` (though a lot of files are duplicated between them). The analyzer and debugger both currently use `sky_engine`, but this results in missing sources when the debugger tries to navigate to some files (such as `lib/_internal/vm/lib/growable_array.dart`, because it's only in `dart-sdk`).

Should `sky_engine` include the full set of sources? Or should the anlayzer and debugger both use `dart-sdk`?

**Comment by christopherfujino** [comment]
> @zanderso is this something you might know about (I see you've committed to the file Jonah linked above)? Full context is above, but the question is about the relationship between `cache/pkg/sky_engine` and `cache/dart-sdk`. The `sky_engine` folder is missing many source files that are in `dart-sdk/lib` (though a lot of files are duplicated between them). The analyzer and debugger both currently use `sky_engine`, but this results in missing sources when the debugger tries to navigate to some files (such as `lib/_internal/vm/lib/growable_array.dart`, because it's only in `dart-sdk`).
> 
> Should `sky_engine` include the full set of sources? Or should the anlayzer and debugger both use `dart-sdk`?

Zach is out for the week, though he's probably the best person to answer the question.

**Comment by zanderso** [comment]
It sounds like https://github.com/flutter/engine/blob/main/sky/packages/sky_engine/BUILD.gn needs some updates for changes to the dart-sdk directory structure.

**Comment by DanTup** [comment]
@zanderso is that something that needs special knowledge, or is it something I could do? (I have no idea what a `gn` file is 🙃)

**Comment by DanTup** [comment]
> If you're not familiar with building the engine, then it might be tricky.

I am not at all :-)

But I suspect the instructions for this are good, so I'm happy to try it. However, I guess my real question was about how I know what to update. For example from a comment above:


- we have: `flutter/bin/cache/dart-sdk/lib/_internal/vm/lib/growable_array.dart`
- we do not have: `flutter/bin/cache/pkg/sky_engine/lib/_internal/vm/lib/growable_array.dart`

So I need to figure out what change I need to make that would cause `_internal/vm/lib/growable_array.dart` to be copied into `sky_engine`. Most of the file linked above just includes other `.gn` files that exist inside the SDK folders - however there doesn't seem to be a `.gn` file inside `_internal`, `_internal/vm` or `_internal/vm/lib`.

It's not clear to me what the fix is here.. Should there be `.gn` file in there somewhere?

**Comment by zanderso** [comment]
Ah, I see. `_internal/vm/lib` in the Dart repo is missing the `.gni` file that contains the list of sources. One probably needs to be added there, and then https://github.com/flutter/engine/blob/main/sky/packages/sky_engine/BUILD.gn can be updated.

**Comment by DanTup** [comment]
> Ah, I see. `_internal/vm/lib` in the Dart repo is missing the `.gni` file that contains the list of sources.

I can't find any info about these files - are they hand-maintained? Can I just create one with the a list of all `.dart` files in the folder? (I feel like if it was that simple, they would've been automated? 🤔)

(If there's a better place/person for me to ask/find answers to these questions, feel free to point me elsewhere!). Thanks!

**Comment by DanTup** [comment]
@aam @rmacnak-google friendly ping :)

This turns out to also be the cause of https://github.com/Dart-Code/Dart-Code/issues/4759. In a Dart project we locate the `assert` source in `lib\_internal\vm\lib\errors_patch.dart` but in Flutter it's missing and we produce an error.

I have a sort-of fix for it (we won't put non-existent paths into debugger sources, so instead the user just won't be able to jump to that source) however it results in different behaviour between Dart/Flutter.

**Comment by aam** [comment]
We could add .gni to `_internal/vm/lib`, but those files seem to be not used for anything else, so prone to get out of date.
Ideally `vm_platform_strong.dill.d` deps file produced from compiling the flutter platform (`flutter/lib/snapshot:strong_platform`)https://github.com/flutter/engine/blob/6caee3236d379dfb91d806c8b91c68e18fc7239e/lib/snapshot/BUILD.gn#L217 becomes a source of all dart sources that goes into flutter sky, sources that are available for debugging.

**Comment by DanTup** [comment]
> Ideally `vm_platform_strong.dill.d` deps file produced from compiling the flutter platform becomes a source of all dart sources that goes into flutter sky, sources that are available for debugging.

I recognise some of these words but I don't really know what any of this means 😄 Is this a simple fix someone (or I) could make, or something that would require a lot of effort?

I'm happy to help if I can, but this is somewhat out of my area of knowledge.

**Comment by DanTup** [comment]
@zanderso @aam is there anything I (with my limited knowledge of this area) can do to progress this issue? It's not clear to me from the above whether this is a simple fix (and something I could do with some pointers) or better left for someone else.

**Comment by aam** [comment]
Perhaps it would be easier to maintain status quo, land https://dart-review.googlesource.com/c/sdk/+/348180 and then patch flutter engine with something like this 
```
diff --git a/sky/packages/sky_engine/BUILD.gn b/sky/packages/sky_engine/BUILD.gn
index 916c2b1078..3431e24645 100644
--- a/sky/packages/sky_engine/BUILD.gn
+++ b/sky/packages/sky_engine/BUILD.gn
@@ -10,6 +10,7 @@ import("//third_party/dart/sdk/lib/_http/http_sources.gni")
 import(
     "//third_party/dart/sdk/lib/_internal/js_runtime/interceptors_sources.gni")
 import("//third_party/dart/sdk/lib/_internal/js_shared/js_types_sources.gni")
+import("//third_party/dart/sdk/lib/_internal/vm/lib/vm_internal.gni")
 import("//third_party/dart/sdk/lib/async/async_sources.gni")
 import("//third_party/dart/sdk/lib/collection/collection_sources.gni")
 import("//third_party/dart/sdk/lib/convert/convert_sources.gni")
@@ -110,6 +111,13 @@ copy("internal") {
       [ "$root_gen_dir/dart-pkg/sky_engine/lib/internal/{{source_file_part}}" ]
 }
 
+copy("vm_internal") {
+  lib_path = rebase_path("_internal/vm/lib/", "", dart_sdk_lib_path)
+  sources = rebase_path(vm_internal_sdk_sources, "", lib_path)
+  outputs =
+      [ "$root_gen_dir/dart-pkg/sky_engine/lib/_internal/vm/lib/{{source_file_part}}" ]
+}
+
 copy("io") {
   lib_path = rebase_path("io", "", dart_sdk_lib_path)
   sources = rebase_path(io_sdk_sources, "", lib_path)
@@ -219,6 +227,7 @@ group("copy_dart_sdk") {
     ":js_util",
     ":math",
     ":typed_data",
+    ":vm_internal",
   ]
```

How easy it is to reproduce the problem in VSCode(or observatory/devtools)?

**Comment by DanTup** [comment]
@aam thanks!

I guess the simplest thing to check is whether the file at:

```
flutter/bin/cache/dart-sdk/lib/_internal/vm/lib/growable_array.dart
```

Also exists at:

```
flutter/bin/cache/pkg/sky_engine/lib/_internal/vm/lib/growable_array.dart
```

Ultimately, the goal is that all of the files we might end up loading in the debugger that we would normally map to `dart-sdk` in a Dart app also existing in `pkg/sky_engine` for Flutter, because that's what we treat as the Dart SDK for Flutter.

It should also be possible by stepping into that file through the debugger and checking whether VS Code downloaded the source from the VM or opened the file at that location (you can tell this by opening the file manually in VS Code and see if you end up with "two copies" of the same file.. if you do, it's probably not worked).

If the file ends up in the right place I'm happy to test this part, although I don't know what's involved in doing that before it lands in Flutter (I've built the Dart SDK before, but only to use on its own, never to use in the Flutter SDK).

> https://dart-review.googlesource.com/c/sdk/+/348180

Out of interest, how was this file generated? Is it possible it will become out of sync if new files are added?

**Comment by aam** [comment]
> If the file ends up in the right place I'm happy to test this part, although I don't know what's involved in doing that before it lands in Flutter (I've built the Dart SDK before, but only to use on its own, never to use in the Flutter SDK).

If you are able to build flutter engine and run flutter with it, then patching dart sdk could be done in that flutter engine checkout folder - it sits under `third_party/dart`. Then you need to make sure you use `--no-prebuilt-dart-sdk` when running `gn` for flutter engine build.
For example, 
```
$ flutter/tools/gn --no-prebuilt-dart-sdk --runtime-mode debug --unoptimized && flutter/tools/gn --no-prebuilt-dart-sdk --runtime-mode debug --unoptimized  --android --android-cpu arm64 && ninja -C out/host_debug_unopt && ninja -C out/android_debug_unopt_arm64```


> Out of interest, how was this file generated? Is it possible it will become out of sync if new files are added?

The file was created by hand, so yes it could get out of sync.

**Comment by DanTup** [comment]
> If you are able to build flutter engine and run flutter with it

This isn't something I've done before, but I see there are instructions on the wiki (https://github.com/flutter/flutter/wiki/Compiling-the-engine#compiling-for-windows) so I'll give it a go, thanks :)


> The file was created by hand, so yes it could get out of sync.

Ah.. Do new files get added often? It would be a shame to fix this and then have the issue come back.. If the file can't be generated, I wonder if we could have a test or something to verify one folder doesn't contain things the other does not (with exclusions were appropriate) 🤔

**Comment by aam** [comment]
> Ah.. Do new files get added often? It would be a shame to fix this and then have the issue come back.. If the file can't be generated, I wonder if we could have a test or something to verify one folder doesn't contain things the other does not (with exclusions were appropriate) 🤔

I believe files are added/deleted rarely, but sure it's a concern. That's why I mentioned that this solution maintains existing status quo, that is how rest of packages are being included into flutter sky package.

Potentially flutter engine can list and copy files from that folder automatically itself - for example like https://github.com/flutter/engine/pull/50017

**Comment by DanTup** [comment]
@aam sorry for the delay - I just tested this out on master and it seems to have done the job. For example I can correctly hit sources from `_internal/vm` when assertions fail:

![image](https://github.com/flutter/flutter/assets/1078012/0474cc7e-a6fc-4c64-9117-049f1e74d82d)

Thanks! :-)
