### ISSUE TITLE
[Impeller] Investigate command encoding and submission overhead on Vulkan.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#128805]
Instructions for getting symbols in a build:

https://github.com/flutter/flutter/wiki/Crashes#android-local-engine-builds

This profile was generated from a few seconds of Running wondrous on a Pixel 6 Pro, after swiping through a bit to ensure images are loaded. (Image loading performance is a whole nother issue).

![image](https://github.com/flutter/flutter/assets/8975114/eb259e44-ddcb-4f08-8c14-48e0202e5e82)

* RenderPassVK::OnEncodeCommands (243 ms)
  * (132ms) 50% of thread time spent in impeller::UpdateBindingLayouts, 90% of that attributable to impeller::TextureVK::SetLayout, all of which is attributable to driver calls to vulkan::command_buffer::pipeline_barrier
  * (49ms) entirely vkCmdBeginRenderPass
  * (39ms) impeller::EncodeCommands -> AllocateAndBindDescriptorSets

* RenderPassVK::OnSubmitCommands (87ms)
  * (43ms) QueueVK::Submit -> vulkan::queue::submit
  * (33ms) impeller::FenceWaiterVK::AddFence -> lock_guard.
 
 
 A lot of this overhead may be unavoidable, and so we may need to use a worker thread to do the actual encoding.

**Comment by gaaclarke** [comment]
Should we instead be chaining `VkImageMemoryBarrier` structs together and calling `vkCmdPipelineBarrier` once?  I see 2 instances of `SetLayout` showing up in that profile, so looks like potentially they could be batched.

**Comment by jonahwilliams** [comment]
Probably worth trying, but I don't really know. its kind of hard to tell if there are multple calls happening in the flamegraph but I didn't find the Top/Bottom traces useful either. I'd probably try logging to see if there are multiple texture layout transitions happening per render pass first.

**Comment by jonahwilliams** [comment]
I will upload traces as soon as I figure out how to in the Android UI.

Also, yes this is multiple frames. As a rough %, we're spending about half of overall frame time in encoding & submission though

**Comment by jonahwilliams** [comment]
I actually have a patch for doing encoding concurrently, however its a bit harder to do on Vulkan because I can't just rely on `[commandBuffer enqueue]` to magically handle the ordering.

I tried some approaches that used fences for signaling and ordering but it was slower overall. My current approach is just create a single worker thread and only use that for encoding so that we keep our existing ordering guarantees:

https://github.com/flutter/engine/compare/master...jonahwilliams:engine:concurrent_encode

This is still too slow though, and after a few frames we end up falling behind again (though rather than blocking at the end of the frame we block on waitForNextDrawable - sounds familiar)

**Comment by gaaclarke** [comment]
@chinmaygarde here's a frame capture from gallery where there are 2 render passes.  Is it expected that we have 4 fences per frame?

The last 2 fences don't seem to have any work associated with them.  I think I would expect 1 fence and 1 semaphore for this frame, no?  I suspect interrupting the GPU 4 times in a frame to synchronize with the CPU is not what we want, if I'm understanding this trace correctly.

<img width="728" alt="Screenshot 2023-06-13 at 2 12 40 PM" src="https://github.com/flutter/flutter/assets/30870216/28e7d9bb-0776-42d1-9621-48c180cf66a1">

**Comment by jonahwilliams** [comment]
That is the Greenish TextureSourceVK::

**Comment by jonahwilliams** [comment]
actually not true, we can have multiple layout transitions in the root entity pass if there was more than one filter

**Comment by jonahwilliams** [comment]
I think at this point we have more actionable issues and this has been investigated. Closing
