### ISSUE TITLE
[Impeller] Use compute to scale images/textures.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#128884]
Today, when an image needs to get scaled, we end up calling `SkPixmap::scalePixels` 

https://github.com/flutter/engine/blob/c0964f5d0ea3efbcdf0716d6c3785c8d1723bb84/lib/ui/painting/image_decoder_impeller.cc#L223-L240

This ends up with Skia creating a surface with an image shader and using a `drawPaint` call to scale the image. This may end up using either Skia's software or GPU backend depending on how things are configured and what's available.

We should be able to create facilities in Impeller to scale textures/bitmaps. If the bitmap is smaller than the max texture size we could load it into a texture and do this in compute (or use one of the MPS image scaling shaders on metal).

If the bitmap is larger than the max texture size we would need a CPU routine ... or keep using Skia.

**Comment by jonahwilliams** [comment]
I don't we're going to do this with compute. We've switched to using blit passes where possible
