### ISSUE TITLE
[Impeller] Vulkan: Minimize fences to 1 per frame

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#128838]
One frame of rendering the "card" page in the gallery is using 4 fences.  I suspect that is causing undo synchronizations between the gpu and cpu during a frame.

The first 2 fences are associated with getting notifications when resources can be cleaned up ( https://github.com/flutter/engine/blob/main/impeller/renderer/backend/vulkan/command_encoder_vk.cc#L173-L179 ).  Synchronizing mid-frame to clean up resources is probably not what we want, but doing it once per frame is ideal.

I'm unsure what the last 2 fences are for.  Are we submitting empty command buffers?

## screenshot
<img width="760" alt="Screenshot 2023-06-13 at 5 02 36 PM" src="https://github.com/flutter/flutter/assets/30870216/5631809b-bba2-4058-b879-e6841eade722">

**Comment by jonahwilliams** [comment]
I think the way this might work is that we make the vk_context responsible for holding the tracked objects, and then insert the fence only on a queue submission in SwapchainImplVK::Present

**Comment by gaaclarke** [comment]
One of the 2 mystery`vkQueueSubmit`s is coming from the swapchain: https://github.com/flutter/engine/blob/5ff90e13818c9e388a30159f45445b07e060a887/impeller/renderer/backend/vulkan/swapchain_impl_vk.cc#L406

This shouldn't need a fence either, given implicit ordering.

**Comment by gaaclarke** [comment]
The 4th one is also from the swapchain and is used to signal a semaphore:

https://github.com/flutter/engine/blob/5ff90e13818c9e388a30159f45445b07e060a887/impeller/renderer/backend/vulkan/swapchain_impl_vk.cc#L422

**Comment by gaaclarke** [comment]
https://github.com/flutter/engine/pull/42865 showed a 25% reduction in average rasterization time.  That makes my theory about gpu/cpu synchronization more credible, so we should definitely try removing the other 2 fences.

**Comment by gaaclarke** [comment]
I was able to artificially remove the fences by pooling them up then trashing them in the swapchain: https://github.com/gaaclarke/engine/tree/pool-tracked-objects

## before
```
"average_frame_build_time_millis": 1.720138666666665,
  "90th_percentile_frame_build_time_millis": 3.431,
  "99th_percentile_frame_build_time_millis": 20.739,
  "worst_frame_build_time_millis": 40.0,
  "missed_frame_build_budget_count": 8,
  "average_frame_rasterizer_time_millis": 8.94635733333333,
  "90th_percentile_frame_rasterizer_time_millis": 14.131,
  "99th_percentile_frame_rasterizer_time_millis": 33.339,
  "worst_frame_rasterizer_time_millis": 41.068,
  "missed_frame_rasterizer_budget_count": 25,
  "frame_count": 375,
  "frame_rasterizer_count": 375,
  "new_gen_gc_count": 0,
  "old_gen_gc_count": 0,
  "frame_build_times": [

  "average_frame_build_time_millis": 1.633390374331552,
  "90th_percentile_frame_build_time_millis": 3.121,
  "99th_percentile_frame_build_time_millis": 19.762,
  "worst_frame_build_time_millis": 39.646,
  "missed_frame_build_budget_count": 5,
  "average_frame_rasterizer_time_millis": 8.959279999999996,
  "90th_percentile_frame_rasterizer_time_millis": 14.067,
  "99th_percentile_frame_rasterizer_time_millis": 30.636,
  "worst_frame_rasterizer_time_millis": 39.244,
  "missed_frame_rasterizer_budget_count": 18,
  "frame_count": 374,
  "frame_rasterizer_count": 375,
  "new_gen_gc_count": 0,
  "old_gen_gc_count": 0,
  "frame_build_times": [
```
## after
```
  "average_frame_build_time_millis": 1.556695538057742,
  "90th_percentile_frame_build_time_millis": 3.444,
  "99th_percentile_frame_build_time_millis": 13.528,
  "worst_frame_build_time_millis": 35.791,
  "missed_frame_build_budget_count": 3,
  "average_frame_rasterizer_time_millis": 9.182036745406817,
  "90th_percentile_frame_rasterizer_time_millis": 12.831,
  "99th_percentile_frame_rasterizer_time_millis": 30.393,
  "worst_frame_rasterizer_time_millis": 101.764,
  "missed_frame_rasterizer_budget_count": 19,
  "frame_count": 381,
  "frame_rasterizer_count": 381,
  "new_gen_gc_count": 0,
  "old_gen_gc_count": 0,
  "frame_build_times": [

  "average_frame_build_time_millis": 1.5191420911528155,
  "90th_percentile_frame_build_time_millis": 3.186,
  "99th_percentile_frame_build_time_millis": 13.263,
  "worst_frame_build_time_millis": 36.629,
  "missed_frame_build_budget_count": 3,
  "average_frame_rasterizer_time_millis": 10.673589812332432,
  "90th_percentile_frame_rasterizer_time_millis": 13.417,
  "99th_percentile_frame_rasterizer_time_millis": 101.121,
  "worst_frame_rasterizer_time_millis": 105.586,
  "missed_frame_rasterizer_budget_count": 27,
  "frame_count": 373,
  "frame_rasterizer_count": 373,
  "new_gen_gc_count": 0,
  "old_gen_gc_count": 0,
  "frame_build_times": [
```

## evaluation

While removing fences should remove sync points between the cpu and gpu, that time seems insignificant in our case.  I thought that was stalling gpu execution but I was wrong.  There's no need to investigate this further.
