### ISSUE TITLE
Provide a ListTile selection-mode example

### ISSUE THREAD

**Issue by pauldemarco** [flutter/flutter#12882]
Official layout widgets like ListView/GridView should have a selection mode when an item is long-pressed.

Once in selection mode, ListTile/GridTile becomes toggleable, and the AppBar allows the appropriate options to 'Select all, Cancel, or perform actions on items (share, etc)'.

From material design spec: https://material.io/guidelines/patterns/selection.html#selection-usage

**Comment by eseidelGoogle** [comment]
I suspect this is possible to implement on top of existing ListTile, etc. but I agree some help (at least an example) here would be nice.

**Comment by sethladd** [comment]
@pauldemarco if you can't figure out how to build this with our primitives, please let us know

**Comment by pauldemarco** [comment]
This should be fairly straight forward to build from existing widgets, just seeing if an official widget was in the works :smile:.  Feel free to close.

**Comment by Hixie** [comment]
We don't currently plan to do this any time soon, but I agree that it would make sense for us to have something to do this.

**Comment by allanwolski** [comment]
Could you provide an example of how to build this currently?

**Comment by HansMuller** [comment]
A flutter gallery demo that showed how to set this up would be useful.

**Comment by dsourav** [comment]
I have just found something to select multiple item of a listview in flutter through this code.hope this will help you.happy coding ..thanks to this [post.](https://stackoverflow.com/questions/52052464/does-flutter-have-a-contextual-action-bar-for-selecting-multiple-item-from-a-lis)


```import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'NonStopIO',
      theme: new ThemeData(
        primarySwatch: Colors.red,
      ),
      home: new MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool longPressFlag = false;
  List<Element> indexList = new List();

  onelement_selected(int index){
    setState((){
      indexList[index].isselected=!indexList[index].isselected;
    });

  }
  void longPress() {
    setState(() {
      if (indexList.isEmpty) {
        longPressFlag = false;
      } else {
        longPressFlag = true;
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    for(var i=0;i<15;i++){
      indexList.add(Element(isselected: false));
    }

    return new Scaffold(
      appBar: new AppBar(
        title: new Text('Selected ${indexList.length}  ' + indexList.toString()),
      ),
      body: new ListView.builder(
        itemCount: 15,
        itemBuilder: (context, index) {
          return new CustomWidget(
            index: index,
            isselected: indexList[index].isselected,
            
            longPressEnabled: longPressFlag,
            callback: () {
             onelement_selected(index);
             if (indexList.contains(index)) {
                indexList.remove(index);
              } else {
                indexList.add(Element());
              }

              longPress();
            },
          );
        },
      ),
      floatingActionButton: new FloatingActionButton(
        onPressed: () {},
        tooltip: 'Increment',
        child: new Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

class CustomWidget extends StatefulWidget {
  final int index;
  final bool longPressEnabled;
  final VoidCallback callback;
  final bool isselected;

  const CustomWidget({Key key, this.index, this.longPressEnabled, this.callback,this.isselected}) : super(key: key);

  @override
  _CustomWidgetState createState() => new _CustomWidgetState();
}

class _CustomWidgetState extends State<CustomWidget> {
  bool selected = false;

  @override
  Widget build(BuildContext context) {
    return new GestureDetector(
      onLongPress: () {
        widget.callback();
      },
      onTap: () {
        if (widget.longPressEnabled) {
          widget.callback();
        }
      },
      child: new Container(
        margin: new EdgeInsets.all(5.0),
        child: new ListTile(
          title: new Text("Title ${widget.index}"),
          subtitle: new Text("Description ${widget.index}"),
        ),
        decoration: widget.isselected
            ? new BoxDecoration(color: Colors.black38, border: new Border.all(color: Colors.black))
            : new BoxDecoration(),
      ),
    );
  }
}
class Element{
   bool isselected;
  Element({this.isselected});
 }

**Comment by fahadjaved824** [comment]
ListView, GridView and CustomScrollView all of them have a problem that they Build few childs at a time, when we scroll than they made new childs and dispose previous at the top of list respectively. If I select a child at the top and change its state but when I came back after scrolling from bottom it was unselect because its was rebuild from the start not just Context. How will I solve this problem????

**Comment by govindbhardwaj** [comment]
@fahadjaved824 [Here](https://gist.github.com/govindbhardwaj/bd6fb604ebdef7755283b25ea14b0b3b.js) is a sample of what I've done to get the functionality.

`import 'package:flutter/material.dart';

class PublishersSettings extends StatefulWidget {
  Function(List<String>) onSelectionChanged;
  PublishersSettings();
  @override
  _PublishersSettingsState createState() => _PublishersSettingsState();
}

class _PublishersSettingsState extends State<PublishersSettings> {
  final GlobalKey<ScaffoldState> _scaffoldKey = new GlobalKey<ScaffoldState>();
  List<String> selectedChoices = List();
  List<Publisher> publishersList = [];
  PublisherService publisherService = PublisherService();
  
  @override
  void initState() {
    super.initState();
    this.loadPublishers(); //getting publishers from the API
  }

  loadPublishers() async {
    var publishers = await accountService.getPublishersByUser();
    setState(() {
      this.publishersList = publishers ?? [];
      this.selectedChoices = this
          .publishersList
          .where((publisher) => publisher.subscribed)
          .map((publisher) => publisher.publisherName)
          .toList();
    });
  }

  Icon _getBackIcon(TargetPlatform platform) {
    assert(platform != null);
    switch (platform) {
      case TargetPlatform.android:
      case TargetPlatform.fuchsia:
        return const Icon(Icons.arrow_back);
      case TargetPlatform.iOS:
        return const Icon(Icons.arrow_back_ios);
    }
    return null;
  }

  _buildChoiceList() {
    List<Widget> choices = List();

    //adding just a message to the view first
    choices.add(
      Padding(
        padding: const EdgeInsets.all(15.0),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              "Publishers subscriptions will be auto-saved in realtime.",
              style: TextStyle(
                  color: Colors.grey,
                  decoration: TextDecoration.underline,
                  fontStyle: FontStyle.italic),
              textAlign: TextAlign.center,
            )
          ],
        ),
      ),
    );
    
    //creating choice chips according to the list
    //Main Logic
    choices.add(
      Container(
        height: MediaQuery.of(context).size.height -
            (MediaQuery.of(context).size.height / 3),
        width: MediaQuery.of(context).size.width,
        child: ListView.builder(
          itemCount: this.publishersList.length,
          itemBuilder: (BuildContext ctxt, int index) {
            return Padding(
              padding: const EdgeInsets.all(8.0),
              child: ChoiceChip(
                shape: ContinuousRectangleBorder(
                  borderRadius: BorderRadius.all(
                    Radius.circular(20),
                  ),
                ),
                elevation: 4,
                label: Container(
                  height: MediaQuery.of(context).size.height / 20,
                  width: MediaQuery.of(context).size.width / 1.5,
                  child: Padding(
                    padding: const EdgeInsets.only(top: 10.0),
                    child: Text(
                      this.publishersList[index].publisherName,
                      style: selectedChoices
                              .contains(publishersList[index].publisherName)
                          ? TextStyle(
                              color: Colors.white,
                              fontSize: 15,
                              fontWeight: FontWeight.bold)
                          : TextStyle(
                              color: Color.fromRGBO(242, 127, 27, 10.0),
                              fontSize: 15,
                              fontWeight: FontWeight.bold),
                    ),
                  ),
                ),
                selected: selectedChoices
                    .contains(this.publishersList[index].publisherName),
                avatar: selectedChoices
                        .contains(publishersList[index].publisherName)
                    ? Icon(
                        Icons.check_circle,
                        color: Colors.white,
                      )
                    : null,
                backgroundColor: Colors.white,
                selectedColor: Color.fromRGBO(242, 127, 27, 10.0),
                onSelected: (selected) async {
                  setState(() {
                    selectedChoices
                            .contains(this.publishersList[index].publisherName)
                        ? selectedChoices
                            .remove(this.publishersList[index].publisherName)
                        : selectedChoices
                            .add(this.publishersList[index].publisherName);
                  });
                },
              ),
            );
          },
        ),
      ),
    );

    //done button 
    choices.add(Container(
      alignment: Alignment.center,
      child: Padding(
        padding: const EdgeInsets.only(top: 10.0),
        child: FlatButton(
          child: Text(
            "Done",
            style: TextStyle(fontSize: 15),
          ),
          textColor: Colors.white,
          color: Colors.blue,
          onPressed: () async {
            Navigator.pop(context);
          },
          shape:
              RoundedRectangleBorder(borderRadius: BorderRadius.circular(5.0)),
        ),
      ),
    ));
    return choices;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      key: _scaffoldKey,
      appBar: AppBar(
        backgroundColor: Color.fromRGBO(242, 127, 27, 10.0),
        title: Text('Publishers Preferences',
            style: TextStyle(
              color: Colors.white,
              fontSize: 30.0,
            )),
        leading: IconButton(
          icon: _getBackIcon(Theme.of(context).platform),
          color: Colors.white,
          onPressed: () async {
            Navigator.pop(context);
          },
        ),
      ),
      body: Wrap(
        children: _buildChoiceList(),
      ),
    );
  }
}
`
