### ISSUE TITLE
Get to Know Firebase for Flutter Codelab Part 3 Update

### ISSUE THREAD

**Issue by DFilkins919** [flutter/flutter#128840]
Hi,

Not a mistake but on step 3 "Create and configure a Firebase project" under the section to Enable Firestore it states in the Build menu to click "Cloud Firestore"  but under the build section it seems to be renamed to just "Firestore Database."

Nothing major, just might want to update.

Thanks.

**Comment by darshankawar** [comment]
Thanks for the report @DFilkins919 

<img width="924" alt="Screenshot 2023-06-14 at 12 09 04 PM" src="https://github.com/flutter/flutter/assets/67046386/c8957992-db0f-448c-97ab-b6216c03f149">


Actual:

<img width="229" alt="Screenshot 2023-06-14 at 12 07 50 PM" src="https://github.com/flutter/flutter/assets/67046386/0b61ed9f-fac6-4a18-9207-08e79dcd2876">


/cc @domesticmouse

**Comment by domesticmouse** [comment]
PTAL @nohe427 @ericwindmill

**Comment by ericwindmill** [comment]
A fix is in flight via CL 572560350

**Comment by domesticmouse** [comment]
I believe this is now fixed.
