### ISSUE TITLE
ChromeProxyService: Failed to evaluate expression 'completer.complete': InternalError: Expression evaluation in async frames is not supported.

### ISSUE THREAD

**Issue by devmarwat** [flutter/flutter#128882]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

  ```
FilePickerResult? result;
  _pickImage() async {
    result = await FilePicker.platform.pickFiles(
      type: FileType.image,
    );
    if (result != null) {
      uploadImage();
    }
  }

  uploadImage() async {
    Storage storage = Storage(client);
    await storage.createFile(
        bucketId: "images",
        fileId: ID.unique(),
        file: InputFile.fromBytes(
            bytes: result!.files.first.bytes!, filename: ID.unique()));
  }
```

### Expected results

Uploading image but getting subject error.

### Actual results

Exception

### Code sample

<details><summary>Code sample</summary>

```dart
  FilePickerResult? result;
  _pickImage() async {
    result = await FilePicker.platform.pickFiles(
      type: FileType.image,
    );
    if (result != null) {
      uploadImage();
    }
  }

  uploadImage() async {
    Storage storage = Storage(client);
    await storage.createFile(
        bucketId: "images",
        fileId: ID.unique(),
        file: InputFile.fromBytes(
            bytes: result!.files.first.bytes!, filename: ID.unique()));
  }

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Everything is fine with this.
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @devmarwat 
Can you provide `flutter doctor -v` and a complete minimal reproducible code sample that shows the reported error ?
You also seem to be using `Storage` package which seem to be third party. Does the same error occur without using it ?

**Comment by devmarwat** [comment]
The error is coming from http browser client 
![16868561767092761199986507425761](https://github.com/flutter/flutter/assets/94502841/a45ea631-adf7-4d12-8643-75b4b74b86db)

**Comment by devmarwat** [comment]
I think the exception is due to use of async and await in flutter web.

**Comment by devmarwat** [comment]
If we catch the error and to display to UI is says 👇👇
![Uploading IMG20230615235431.jpg…]()

**Comment by devmarwat** [comment]
![IMG20230615235431](https://github.com/flutter/flutter/assets/94502841/ad60db99-633c-4e8b-bbc4-f55bb8cd04f0)

**Comment by darshankawar** [comment]
> Can you provide `flutter doctor -v` and a complete minimal reproducible code sample that shows the reported error ?

Also please don't paste screenshots as they don't help to properly analyze the error. Please provide details in formatted text.
