### ISSUE TITLE
[flutter_tools] `PathAccessException: Cannot create file, path = '<path-to-home-dir>/.dart-tool/dart-flutter-telemetry-session.json' (OS Error: Permission denied, errno = 13)`

### ISSUE THREAD

**Issue by eliasyishak** [flutter/flutter#128826]
Error occurring for `package:unified_analytics` for creating the session json file

```
PathAccessException: PathAccessException: Cannot create file, path = '<path-to-home-dir>/.dart-tool/dart-flutter-telemetry-session.json' (OS Error: Permission denied, errno = 13)
at _File.throwIfError	(file_impl.dart:675)
at _File.createSync	(file_impl.dart:306)
at ForwardingFile.createSync	(forwarding_file.dart:26)
at Initializer.createSessionFile	(initializer.dart:78)
at Initializer.run	(initializer.dart:120)
at new AnalyticsImpl	(analytics.dart:289)
at new Analytics	(analytics.dart:67)
at getDefaultAnalytics	(globals.dart:98)
at analytics	(globals.dart:94)
at _exit	(runner.dart:302)
at run.<anonymous closure>.<anonymous closure>	(runner.dart:120)
at <asynchronous gap>	(async)
at AppContext.run.<anonymous closure>	(context.dart:150)
at <asynchronous gap>	(async)
at main	(executable.dart:91)
at <asynchronous gap>	(async)
```

**Comment by Turskyi** [comment]
@eliasyishak I fixed that problem, by removing the "locked" check in the <path-to-home-dir> folder details.
<img width="270" alt="Screenshot 2023-06-13 at 10 20 11 PM" src="https://github.com/flutter/flutter/assets/44470418/168b6445-5b40-48df-b00f-1040a9a723ad">

**Comment by eliasyishak** [comment]
Hi, @Turskyi... did you encounter this error as well before? We saw this on our beta channel error logs

**Comment by Turskyi** [comment]
> Hi, @Turskyi... did you encounter this error as well before? We saw this on our beta channel error logs

No. I did not have this problem before. It started after upgrading flutter to 3.10.4.

**Comment by christopherfujino** [comment]
> Closing this issue since this should be resolved in the latest version of `package:unified_analytics`

Has it rolled to framework master? (that is, is the fix in [2.0.0](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/pubspec.yaml#L51)?) We usually wait to close issues until the fix is available in the Flutter master channel.

**Comment by eliasyishak** [comment]
Yes, version `2.0.0` for the package includes the permissions check. I tested it myself using the master channel and seems to handle the error when i set my home dir to read only

**Comment by christopherfujino** [comment]
> Yes, version `2.0.0` for the package includes the permissions check. I tested it myself using the master channel and seems to handle the error when i set my home dir to read only

Ahh you're right, that same check should cover here, good call.
