### ISSUE TITLE
The title in the sliver appbar is not properly centered if centerTitle is true when navigating to other routes

### ISSUE THREAD

**Issue by milindgoel15** [flutter/flutter#128809]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a fresh project
2. Add a new page and use the material page route to navigate to it
3. Run the project on Android.
4. Navigate to another page
5. the title is not centered in the sliver appbar.

Also, I checked the issue on the master channel and it was not there. So it's probably fixed but I couldn't find any issue. Please check if that fix can be cherry-picked into stable.

### Expected results

The title is centered properly

### Actual results

The title appears to be shifted towards right.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
          colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
          useMaterial3: true,
          appBarTheme: const AppBarTheme(centerTitle: true)),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('App bar'),
        actions: [
          IconButton(
            onPressed: () {
              Navigator.push(
                context,
                MaterialPageRoute(builder: (context) => const Settings()),
              );
            },
            icon: const Icon(Icons.settings),
          ),
        ],
      ),
      body: const Center(
        child: Text('home'),
      ),
    );
  }
}

class Settings extends StatelessWidget {
  const Settings({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: CustomScrollView(
        slivers: [
          SliverAppBar.large(
            leading: IconButton(
              onPressed: () => Navigator.pop(context),
              icon: const Icon(Icons.arrow_back_outlined),
            ),
            title: Text(
              "settings",
              style: TextStyle(
                color: Theme.of(context).colorScheme.primary,
              ),
            ),
          ),
          const SliverToBoxAdapter(
            child: Column(
              children: [
                Text("settings"),
                SizedBox(
                  height: 100,
                ),
                SizedBox(
                  height: 100,
                ),
                SizedBox(
                  height: 100,
                ),
                SizedBox(
                  height: 100,
                ),
                SizedBox(
                  height: 100,
                ),
                SizedBox(
                  height: 100,
                ),
                SizedBox(
                  height: 100,
                ),
                SizedBox(
                  height: 100,
                ),
                SizedBox(
                  height: 100,
                ),
              ],
            ),
          )
        ],
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]
On flutter 3.7.12, the issue is not there:
![3 7 12](https://github.com/flutter/flutter/assets/45682747/67f9eccb-89ff-4c51-a1e4-c9bdb771872b)

Flutter stable 3.10.4 has it:
![stable 3 10](https://github.com/flutter/flutter/assets/45682747/c6ef5bed-3c47-4579-89a1-dbb1e607bd84)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Flutter 3.10.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 682aa387cf (8 days ago) • 2023-06-05 18:04:56 -0500
Engine • revision 2a3401c9bb
Tools • Dart 3.0.3 • DevTools 2.23.1

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.4, on Microsoft Windows [Version 10.0.22621.1778], locale en-IN)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Chrome - develop for the web
[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.6.0)
    ✗ Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[✓] Android Studio (version 2022.2)
[✓] VS Code, 64-bit edition (version 1.79.0)
[✓] Connected device (4 available)
[✓] Network resources
```

</details>

**Comment by TahaTesser** [comment]
Hi @milindgoel15 
This is fixed by https://github.com/flutter/flutter/pull/122542. However, the fix isn't available in the `stable 3.10.x` channel yet,  currently it is available on `beta` and above.


It should be available in the next major stable release. Closing as fixed.

**Comment by milindgoel15** [comment]
I have just tested the beta and the center title is fixed. I came across another problem, the font size of the title is not respected as it was in the stable.

This is my appbar theme config:
```dart
    appBarTheme: AppBarTheme(
      elevation: 0,
      scrolledUnderElevation: 8,
      toolbarHeight: 64,
      color: darkDynamic.background,
      surfaceTintColor: darkDynamic.secondaryContainer,
      titleTextStyle: TextStyle(
        color: darkDynamic.onBackground,
        fontSize: 20,
        fontFamily: "CircularStd",
      ),
      systemOverlayStyle: const SystemUiOverlayStyle(
        statusBarColor: Colors.transparent,
        statusBarIconBrightness: Brightness.light,
        systemNavigationBarIconBrightness: Brightness.light,
      ),
    ),
```

Beta:
![image](https://github.com/flutter/flutter/assets/45682747/02aec162-881d-4b42-99ea-e07559489d66)

Stable:
![image](https://github.com/flutter/flutter/assets/45682747/b860f951-e2cf-4b4d-911e-685ae98244c1)

**Comment by TahaTesser** [comment]
This is expected. Too large an expanded title will get cut off, so this is limited just like the regular app bar title.  See https://github.com/flutter/flutter/pull/125038
You can try it on Android Compose as well by changing the device font size.

**Comment by milindgoel15** [comment]
So the font size will have no impact on medium and large app bars from now? 

According to the [m3 docs](https://m3.material.io/components/top-app-bar/specs), font sizes of both medium and large should be headline small and headline medium respectively. So how do we set them now? While making sure the regular app bar title stays on the title large font size.

**Comment by TahaTesser** [comment]
> So the font size will have no impact on medium and large app bars from now? Although by testing the stable channel, the fontsize doesn't affect sliver appbars only the normal appbar. So it was already respecting the headline font size from m3 docs.

There might be some confusion. Please file a new issue with all the details and a complete sample. (as the current issue isn't related)

> According to the [m3 docs](https://m3.material.io/components/top-app-bar/specs), font sizes of both medium and large should be headline small and headline medium respectively.


The defaults already match M3 specs.

https://github.com/flutter/flutter/blob/40bb615b0c96b2ca2ec2777fe9ea6aa20c815b14/packages/flutter/lib/src/material/app_bar.dart#L2393-L2419
