### ISSUE TITLE
Add retry logic around Installing Google Cloud SDK on bots

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#12888]
Travis log:

+echo 'Installing Google Cloud SDK...'
Installing Google Cloud SDK...
+curl https://sdk.cloud.google.com
+bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   443    0   443    0     0    711      0 --:--:-- --:--:-- --:--:--   712
curl: (56) SSLRead() return error -9806
The command "./dev/bots/travis_setup.sh" failed and exited with 56 during .

**Comment by Hixie** [comment]
We will need some retry logic around that step.

**Comment by Hixie** [comment]
Where do we use this these days?

**Comment by amirh** [comment]
I haven't seen this since we moved off Travis, closing the issue.
