### ISSUE TITLE
Flutter video_player doesn't plays .mkv

### ISSUE THREAD

**Issue by AALAMILLO** [flutter/flutter#128819]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Hi everyone it seems that the video_player package for flutter doesn't plays the .mkv extension. I have tried with chewie, better player and also video_player but I don't have success. Any ideas? Or you are working on that? Thanks a lot

### Proposal

The documentation about the compatible codecs doesn't have mkv.

**Comment by stuartmorgan** [comment]
Please see https://pub.dev/packages/video_player#supported-formats; `video_player` does not control the set of supported formats.
