### ISSUE TITLE
[shared_preferences] Crash during use the SharedPreferences, when UserDefaults includes Date type object.

### ISSUE THREAD

**Issue by maciek-atmoapps-com** [flutter/flutter#128948]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Add into to UserDefaults record with type ‚Date’ eg:
Add in AppDelegate (in application method before ‚return’ statement)
`UserDefaults.standard.set(Date.init(), forKey: "datatest1")`
2. Add shared_preferences dependency into flutter app.
3. Use SharedPreferences instance with access to all shared preferences.
```
  SharedPreferences.setPrefix('');
  await SharedPreferences.getInstance();
```

### The issue?
iOS handle following data types in user preferences: NSData, NSString, NSNumber, NSDate, NSArray, or NSDictionary. See [NSUserDefaults spec](https://developer.apple.com/documentation/foundation/nsuserdefaults#2926904). If UserDefaults include Date type object, application will crash during reading preferences.
Following case can occur especially when migrating from a native app to flutter.

### Expected results

App should be not crash.
Key (in user preferences) which included date object should include timestamp value.

### Actual results

App crash:

```
Unsupported value: Thu Jun 15 14:22:20 2023 of type __NSTaggedDate
*** Assertion failure in void WriteValueOfType(CFTypeRef, CFMutableDataRef, FlutterStandardCodecObjcType, CFTypeRef)(), FlutterStandardCodec.mm:341
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Unsupported value for standard codec'
*** First throw call stack:
(0x18043fc60 0x197c6bee4 0x181be5de0 0x107a16bf4 0x107a16748 0x184e197cc 0x184c0b18c 0x1803af5d4 0x107a16b44 0x107a16af0 0x107a16748 0x107a183f4 0x107a1491c 0x104afe3cc 0x104aff0d0 0x104afe2c8 0x107a14890 0x10746cb80 0x1800ff094 0x180100094 0x1800acd44 0x1800ac994 0x1803fb014 0x1803b84f8 0x1803cb174 0x1a0ee6988 0x182bce7d8 0x182967c70 0x1048befa4 0x104c804d0)
libc++abi: terminating with uncaught exception of type NSException
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001bacffbbc libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`:
->  0x1bacffbbc <+8>:  b.lo   0x1bacffbd8               ; <+36>
    0x1bacffbc0 <+12>: stp    x29, x30, [sp, #-0x10]!
    0x1bacffbc4 <+16>: mov    x29, sp
    0x1bacffbc8 <+20>: bl     0x1bacfb60c               ; cerror_nocancel
Target 0: (Runner) stopped.
Lost connection to device.
Failed to send request: {"jsonrpc":"2.0","id":"20","method":"getObject","params":{"isolateId":"isolates/682427186373043","objectId":"classes/5801"}}
```

### Code sample

<details><summary>Code sample</summary>

AppDelegate.swift

```swift
import UIKit
import Flutter

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    UserDefaults.standard.set(Date.init(), forKey: "datatest1")
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
```
main.dart

```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  SharedPreferences.setPrefix('');
  await SharedPreferences.getInstance();
  runApp(const MyApp());
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.3.1 22E261 darwin-x64, locale pl-PL)
    • Flutter version 3.10.5 on channel stable at /Users/maciek/development/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (2 days ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/maciek/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/maciek/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.78.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (4 available)
    • Pixel 6 (mobile)         • 18241FDF600335                           • android-arm64  • Android 13 (API 33)
    • Marcin’s iPhone (mobile) • e73d6caac7f8be993c64c168731a1809fe5e1c91 • ios            • iOS 15.7.6 19H349
    • macOS (desktop)          • macos                                    • darwin-x64     • macOS 13.3.1 22E261 darwin-x64
    • Chrome (web)             • chrome                                   • web-javascript • Google Chrome 114.0.5735.106

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment]
This is explicitly called out [in the README](https://pub.dev/packages/shared_preferences#migration-and-prefixes):

> If the prefix is set to a value such as '' that causes it to read values that were not originally stored by the SharedPreferences, initializing SharedPreferences may fail if any of the values are of types that are not supported by SharedPreferences.

 The solution is https://github.com/flutter/packages/pull/3794; we don't have an issue related to that yet, so we can use this to track it.

**Comment by YankoSoulisimo** [comment]
We face a similar issue in our latest iOS release, though we have been using the shared_preferences plugin for the last two years and had no similar problems, precisely in our case it is an array of Date objects. Suddenly, this array became a problem. Here's what I've found in the iOS implementation code of the plugin that handles dates and converts them to milliseconds:

`+(void)mapDateToMilliseconds:(NSDictionary *)dictionary mappedDictionary:(NSMutableDictionary *)mappedDictionary {
    for (NSString* key in [dictionary allKeys]) {
        id value = [dictionary objectForKey:key];
        
        if ([value isKindOfClass:[NSDictionary class]]) {
            NSDictionary *newDictionary = (NSDictionary *)value;
            NSMutableDictionary *newMappedDictionary = [NSMutableDictionary dictionary];
            
            [self mapDateToMilliseconds:newDictionary mappedDictionary:newMappedDictionary];
            mappedDictionary[key] = newMappedDictionary;
        } else if ([value isKindOfClass:[NSArray class]]) {
            NSMutableArray *newArray = [[NSMutableArray alloc] init];
            
            for (id element in ((NSArray *)value)) {
                if ([element isKindOfClass:[NSDictionary class]]) {
                    NSMutableDictionary *newMappedDictionary = [NSMutableDictionary dictionary];
                    
                    [self mapDateToMilliseconds:(NSDictionary *)element mappedDictionary:newMappedDictionary];
                    [newArray addObject:newMappedDictionary];
                } else {
                    [newArray addObject:element];
                }
            }
            
            mappedDictionary[key] = newArray;
        } else if ([value isKindOfClass:[NSDate class]]) {
            mappedDictionary[key] = [NSNumber numberWithDouble:floor([((NSDate *)value) timeIntervalSince1970] * 1000)];
        } else {
            mappedDictionary[key] = value;
        }
    }
}`

In our case our array with dates is falling here:

          `NSMutableArray *newArray = [[NSMutableArray alloc] init];
            
            for (id element in ((NSArray *)value)) {
                if ([element isKindOfClass:[NSDictionary class]]) {
                    NSMutableDictionary *newMappedDictionary = [NSMutableDictionary dictionary];
                    
                    [self mapDateToMilliseconds:(NSDictionary *)element mappedDictionary:newMappedDictionary];
                    [newArray addObject:newMappedDictionary];
                } else {
                    [newArray addObject:element];
                }
            }
            
            mappedDictionary[key] = newArray;`
            
Here, in the "else" condition the elements of our array are not tested if they're Dates, instead the'r added the way they are - namely as dates, and that causes the crash later. Our workaround was to convert our dates in advance, or one could put them in a dictionary, which this code would handle.

**Comment by stuartmorgan** [comment]
@YankoSoulisimo The code you have shown there is from a different, third-party plugin. If you have issues with it you'll need to contact its developers.

**Comment by YankoSoulisimo** [comment]
Ooops, you are right and sorry. I just saw you made a fix. Thanks!

**Comment by czarny** [comment]
@stuartmorgan 
This change does not add new type to shared_preferences. It allows to use date type objects stored by native code by one way migration to timestamps. Currently user preferences including such value causes crash and allowing to omit them resolves problem only partly. Reading all values from user preferences will be useful especially during migration from native app to flutter. Also please note problem exists only on iOS/macOS because plist format (which allows to store date obejcts) is used only on these platforms. Other platforms use json or xml to store preferences so current types match perfectly.

**Comment by stuartmorgan** [comment]
> This change does not add new type to shared_preferences.

This isn't a change, it's an issue (crashing when attempting to load the shared instance under specific circumstances). The solution we have planned to that general issue is the `allowList` PR linked above.

> It allows to use date type objects stored by native code by one way migration to timestamps.

It sounds like you are referring to the other PR, not to this issue. As I said in the PR, we would not accept that PR as-is, and the next step if you want to advance something like it would be to file a new issue.

> Currently user preferences including such value causes crash and allowing to omit them resolves problem only partly.

It prevents throwing an exception that kills the application, allowing the application to run normally and access all the other preferences, which is a significant improvement.

> Reading all values from user preferences will be useful especially during migration from native app to flutter.

Reading all values is impossible under the current structure of the plugin. Please file a new issue if you want to propose that; actually implementing it would require a design document proposing new APIs handling all possible types and structures.

> Also please note problem exists only on iOS/macOS because plist format (which allows to store date obejcts) is used only on these platforms. Other platforms use json or xml to store preferences so current types match perfectly.

This is not accurate; both JSON and XML allow storage of complex type structures that cannot be retrieved using the current APIs.
