### ISSUE TITLE
[Impeller] JIT construction of PSO variants causes jank on Vulkan.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#128963]
Split off from https://github.com/flutter/flutter/issues/128919

Unlike Metal, constructing new PSO variants in vulkan is incredibly expensive - on the order of milliseconds. Current the content_context.cc setup will attempt to construct a default PSO for every shader we have. Unfortunately some of the defaults don't match what the application will end up using, so aside from wasting time at startup we're guaranteeing that we'll need to compile a PSO in a frame workload.

In no particular order:

* All PSOs are generated with sample count of 1, whereas 4 is the default MSAA config
* Several PSOs appear to have an unknown pixel format, meaning they're not actually valid. Perhaps a race between knowing which pixel format to use and the offscreen format.
* The primitive type defaults to kTriangle but some shaders only use kTriangleStrip like clips. This should be configured.
* SrcOver is the default blend mode, but SrcOver to Src cooercsion will commonly apply to several variants and should be pre-cached.
* Stencil operations frequently mismatch. The default is kEqual, but textures use kAlways and strokes use kLess

**Comment by jonahwilliams** [comment]
Also, several filters that render offscreen only use src blend mode.

**Comment by chinmaygarde** [comment]
From discussion in chat, the consensus seems to be to front-load creation of all pipeline derivatives while minimizing the number of derivatives needed in the first place by whittling down `impeller::ContentContextOptions`.

In rough order of implementation:

1. Create a separate worker pool or QoS class for Vulkan tasks. These tasks must not compete with I/O tasks.
2. Create better default prototypes for in `impeller::ContentContextOptions` by following @jonahwilliams s guidance in the main comment.
3. Smarter pipeline cache persistence. Right now, the cache is persisted to disk after a set number of frames. Any derivatives generated past this point will not be cached and reused.
4. Allow disabling pipeline caches during development to better gauge startup performance.
5. Minimize `impeller::ContentContextOptions` to get rid of options that can be implemented via dynamic pipeline states or using render pass compatibility guidelines.
6. Fully front-load PSO variant creation.

**Comment by jonahwilliams** [comment]
Apparent "not enough to fix X" is enough to trigger the auto close bot.

**Comment by ditman** [comment]
> Apparent "not enough to fix X" is enough to trigger the auto close bot.

Yikes, sorry about that! Not entirely sure how to prevent this form my end, maybe updating my fork through the github UI rather than the command line :S

**Comment by jonahwilliams** [comment]
nah no worries, we can just create a new issue.

**Comment by jonahwilliams** [comment]
Closing in favor of https://github.com/flutter/flutter/issues/129050
