### ISSUE TITLE
ScrollController not attached to any scroll views. 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 107 pos 12: '_positions.isNotEmpty'

### ISSUE THREAD

**Issue by zhangcheng1989** [flutter/flutter#128939]
The following assertion was thrown while handling a gesture:
ScrollController not attached to any scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 107 pos 12: '_positions.isNotEmpty'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:107:12)
#3      PageController.jumpToPage (package:flutter/src/widgets/page_view.dart:214:41)
#4      CommonUtil.navToPage (package:app/utils/common_util.dart:449:43)
#5      MarketEntityListWiget._buildBuyEntityWidget.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:app/widgets/nft/market_entity_list_widget.dart:605:60)
#6      MarketNftRentSuccessWidget._buildBtnWidget.<anonymous closure> (package:app/widgets/nft/market_nft_rent_success_widget.dart:105:34)
#7      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1096:21)
#8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:253:24)
#9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:627:11)
#10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:306:5)
#11     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:276:7)
#12     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:163:27)
#13     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:464:20)
#14     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:440:22)
#15     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:336:11)
#16     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:395:7)
#17     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:357:5)
#18     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:314:7)
#19     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:295:7)
#20     _invoke1 (dart:ui/hooks.dart:164:13)
#21     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:361:7)
#22     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:31)
(elided 2 frames from class _AssertionError)
Handler: "onTap"
Recognizer: TapGestureRecognizer#fde7b
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(232.5, 636.5)
  finalLocalPosition: Offset(45.0, 27.7)
  button: 1
  sent tap down

**Comment by dam-ease** [comment]
Hi @zhangcheng1989  
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly. (See [Report a bug](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml) template)

Closing this issue, since not enough information has been provided.
