### ISSUE TITLE
I Guess This Is A Bug

### ISSUE THREAD

**Issue by anmol420** [flutter/flutter#128961]
I tried running app through terminal typing `flutter run`.
 Then I pressed `Ctrl+C` and then typed `n`, *still the app got terminated*. 

I guess this could be a bug.
![image](https://github.com/flutter/flutter/assets/76034132/fcc64540-262b-4d1f-b7c4-74b34ea53831)

**Comment by dam-ease** [comment]
Hi @anmol420. This is not a bug. See https://github.com/flutter/flutter/issues/62357#issuecomment-665767891
