### ISSUE TITLE
Refactor the flutter_sprites library so it uses sublibraries instead of parts

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1289]
Right now it's not clear how the flutter_sprites library is organised -- it's just one big pile of files all inlined into the same namespace, with no clear separation of concerns. This means e.g. _privates can't be hidden from other parts of the library, there's no easy way to reduce bugs (e.g. the box2d analyzer crash from https://github.com/flutter/flutter/pull/1043), etc.

**Comment by devoncarew** [comment]
It looks like this is the last use of parts in the flutter repo. If we move away from parts here, we could make the code for flutter analyze much simpler, and we could more reliably analyze all the files in the repo (we currently miss some categories of files).

**Comment by Hixie** [comment]
This is obsolete.
