### ISSUE TITLE
The frame rate was only 30fps on Flutter's latest version of Windows 3.10.5, but I used the same code on version 3.10.2, which exceeded 60fps

### ISSUE THREAD

**Issue by wxjrkm520** [flutter/flutter#128941]
## Details

FLUTTER VERSION:3.10.5
Target Platform: WINDOWS

```dart
class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }
  @override
  void initState() {
    super.initState();
    Timer.periodic(const Duration(microseconds: 500), (timer) {
      setState(() {
        _counter++;
      });
    });
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.transparent,
      body: Center(
        child: Stack(
          children: <Widget>[
            Center(
              child: Transform.translate(
                offset: Offset(-_counter / 2000, -_counter / 2000),
                child: RepaintBoundary(
                  child: Container(
                    padding: const EdgeInsets.all(8.0),
                    color: Colors.deepOrange,
                    child: Text('$_counter'),
                  ),
                ),
              ),
            ),
            Positioned(
              left: _counter / 2000,
              top: _counter / 2000,
              child: Container(
                padding: const EdgeInsets.all(8.0),
                color: Colors.deepOrange,
                child: Text('$_counter'),
              ),
            ),
            Stack(
              children: [
                Text(
                  '$_counter',
                  style: Theme.of(context).textTheme.headlineMedium,
                ),
              ],
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), 
    );
  }
}
```
Mainly the following code：
``` dart
Timer.periodic(const Duration(microseconds: 500), (timer) {
      setState(() {
        _counter++;
      });
});
```
3.10.5:
![图片](https://github.com/flutter/flutter/assets/49952604/49aaadc1-a603-4da0-993a-eba18a9dc30a)

3.10.2:
![图片](https://github.com/flutter/flutter/assets/49952604/867e6ba2-5ee8-47c4-b7d9-7258e85840f7)

**Comment by darshankawar** [comment]
Thanks for the report @wxjrkm520 
Does it occur in `--profile` mode or in debug mode only ? Can you run `flutter run --profile --trace-skia` and provide us the trace file ?
Also, please run the same scenario on latest master as well to check whether the behavior persists or not.

**Comment by wxjrkm520** [comment]
There is no problem running on the mobile end, but running on PC Windows can cause such problems

**Comment by wxjrkm520** [comment]
I found that the problem lies in the raster thread, where the UI only takes 0.1-0.5ms, while the raster thread takes 16ms+

**Comment by huycozy** [comment]
Hi @wxjrkm520 
After observing this for longer, I noticed that the FPS changes over time:

60 -> 30 -> 60 -> 30 ....

(Verifying this on the latest stable version  `3.10.5`.

Do you notice the same result on both above Flutter versions?

**Comment by wxjrkm520** [comment]
> Hi @wxjrkm520 After observing this for longer, I noticed that the FPS changes over time:
> 
> 60 -> 30 -> 60 -> 30 ....
> 
> (Verifying this on the latest stable version `3.10.5`.
> 
> Do you notice the same result on both above Flutter versions?

yes,same result!

**Comment by huycozy** [comment]
Thanks for your response. I just checked this on the latest master and notice the issue doesn't seem to appear anymore. Could you please switch to master channel and confirm this?

```
flutter channel master
flutter upgrade
```

**Comment by wxjrkm520** [comment]
When I tested on my company's computer, this problem seemed to have been resolved.(in profile mode)

I found that if the frame count suddenly increases, the version of the master branch will slowly decrease the frame count!

And the time consumption of Raster threads is also very stable!

Excellent solution to this problem, thank you very much!!

I will test again on my personal computer after returning home, as this issue was discovered on my personal computer. Please wait for good news.

**Comment by wxjrkm520** [comment]
The problem has been perfectly solved, thank you
