### ISSUE TITLE
Foldable - showModalBottomSheet covered by "taskbar" in unfold state

### ISSUE THREAD

**Issue by x4080** [flutter/flutter#128985]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run showModalBottomSheet that has buttom on the bottom
2. In foldable state works perfectly
3. In unfoldable state, button covered by "taskbar"

Please note : I use only foldable emulator since I dont have foldable device yet - the emulator is inconsistent too, since sometimes taskbar appear and sometimes not

### Expected results

Both are not covered by "taskbar"

### Actual results

2. In foldable state works perfectly
3. In unfoldable state, button covered by "taskbar"

### Code sample

...

### Screenshots or Video

<img width="723" alt="Screenshot 2023-06-16 at 08 20 02" src="https://github.com/flutter/flutter/assets/10181090/c41e0e58-299e-4d85-bd9f-b6bdee0b451a">
<img width="376" alt="Screenshot 2023-06-16 at 08 20 21" src="https://github.com/flutter/flutter/assets/10181090/05760e01-a4d5-4f2e-a365-9b5088f4a84a">

### Logs

...

### Flutter Doctor output

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.4, on macOS 13.4 22F66 darwin-arm64, locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.79.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

**Comment by darshankawar** [comment]
Thanks for the report @x4080 
I used [this](https://api.flutter.dev/flutter/material/showModalBottomSheet.html#material.showModalBottomSheet.1) example and ran it on fold-out avd in which I couldn't replicate the reported behavior.

<img width="507" alt="Screenshot 2023-06-16 at 2 18 22 PM" src="https://github.com/flutter/flutter/assets/67046386/b8ebc85f-08f7-485c-900a-1098c3026738">

<img width="881" alt="Screenshot 2023-06-16 at 2 21 02 PM" src="https://github.com/flutter/flutter/assets/67046386/f9c824b0-8a5d-40e1-bb27-ccaf49db091b">
<img width="363" alt="Screenshot 2023-06-16 at 2 21 57 PM" src="https://github.com/flutter/flutter/assets/67046386/1256d3d2-275d-4bc1-8b13-3d9145ce49b5">

Can you use the same example code and run at your end to see if you still get same behavior or not ?

**Comment by x4080** [comment]
@darshankawar thanks. I'll try it out
