### ISSUE TITLE
google sign in web How to detach appClientId

### ISSUE THREAD

**Issue by minjinDelable** [flutter/flutter#128922]
I want to separate the firebase of the commercial environment and the development environment and apply it to one project. What can you do?
Metatags appear to read only one value. Can you divide the two prices?

**Comment by darshankawar** [comment]
@minjinDelable 
Your question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here, as this doesn't seem to be a bug or a feature request for the package.
