### ISSUE TITLE
Updating the codelab instructions for adding dependencies in flutter apps

### ISSUE THREAD

**Issue by samindaw** [flutter/flutter#128918]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

This is regarding the codelab [firebase-get-to-know-flutter](https://firebase.google.com/codelabs/firebase-get-to-know-flutter).
 
Checkout the repo and start working on the [step_02](https://github.com/flutter/codelabs/blob/main/firebase-get-to-know-flutter/step_02). Note the following dependencies already added to the `pubspec.yaml` file.
```
  cupertino_icons: ^1.0.2
  google_fonts: ^5.0.0
  go_router: ^8.0.1
```
When reaching the instructions in  [4 Configure Firebase](https://firebase.google.com/codelabs/firebase-get-to-know-flutter#3) to add additional packages as dependencies I face following error during addition of the package `firebase_ui_auth` package.
```
$ flutter pub add firebase_ui_auth
...
...
Because google_fonts >=4.0.5 depends on http ^1.0.0 and every version of desktop_webview_auth depends on http ^0.13.3, google_fonts >=4.0.5 is incompatible with desktop_webview_auth.
Thus, google_fonts >=4.0.5 is incompatible with firebase_ui_auth.
So, because gtk_flutter depends on both google_fonts ^5.0.0 and firebase_ui_auth any, version solving failed.
```
Looks like `google_fonts` package  is incompatible with any of the existing versions of  `firebase_ui_auth`.

### Proposal

It is possible there'd be a future version of `firebase_ui_auth` would not yield any compatibility issues.  However as a more permanent solution  I's suggest the following. 

1. Remove the already added 3 dependencies from the `pubspec.yaml` file.
2. Instead of adding the dependencies one at a time with separate commands, Add them all with a single command as follows
```
$ flutter pub add cupertino_icons google_fonts go_router firebase_core firebase_auth cloud_firestore provider firebase_ui_auth
```` 
Which should resolve the best combination of compatible versions for all dependencies all at once.

**Comment by darshankawar** [comment]
Thanks for the report @samindaw 
A similar issue was reported in flutterfire repo for which the solution is as [mentioned](https://github.com/firebase/flutterfire/issues/11123#issuecomment-1591077611).
Take a look at it and see if it helps to resolve your use case or not.

**Comment by samindaw** [comment]
thanks @darshankawar.  Yes, that should essentially resolve the problem as well. 

I originally reported this problem 4 days ago as a bug (#128652), and in there I was advised to create a proposal instead. But in between now and then I forgot to check again if the problem had gotten a fix. 

I'm marking this as resolved.
