### ISSUE TITLE
Enable entering text via keyboard in emulator (Android)

### ISSUE THREAD

**Issue by deborah-ufw** [flutter/flutter#12898]
## Steps to Reproduce

Launch a Flutter app with a text input field in an emulator (Android).

Tap on the field, keyboard comes up.

Expected behavior:
- I can use my keyboard to enter my very long text

Actual behavior
- I have to use my mouse to click out a sentence on the emulator's virtual soft keyboard

**Comment by eseidelGoogle** [comment]
Sounds like https://github.com/flutter/flutter/issues/11177?

**Comment by deborah-ufw** [comment]
Right you are. I searched issues for "keyboard" but did not see that one. I put a thumbs up on that one and am closing this one. Thanks!
