### ISSUE TITLE
the text widget didn't show ellipsis when i set text \n\n\n\n

### ISSUE THREAD

**Issue by OnClickListener2048** [flutter/flutter#128916]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. create a text widget
2. enter text data like  \n like 4 times and set the maxline of text 3,set the text overflow TextOverflow.ellipsis,
3. the text widget dosen't reveal the ellipsis.

### Expected results

I think under this situation the text widget should consider exceed the maxline and show the ellipsis

### Actual results

didn't show ellipsis 

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

class AnimatedSwitcherWidget extends StatefulWidget {
  const AnimatedSwitcherWidget({Key? key}) : super(key: key);

  @override
  State<AnimatedSwitcherWidget> createState() => _AnimatedSwitcherWidgetState();
}

class _AnimatedSwitcherWidgetState extends State<AnimatedSwitcherWidget> {
  bool isSelected = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("AnimatedSwitcher"),
      ),
      body: Center(
        child: AnimatedSwitcher(
          duration: const Duration(milliseconds: 1000),
          child: ElevatedButton(
            onPressed: () {
              setState(() {
                isSelected = !isSelected;
              });
            },
            child: const Text(
              "AnimatedSwitcher  \n\n\n\n  AnimatedSwitcher",
              maxLines: 3,
              overflow: TextOverflow.ellipsis,
            ),
          ),
          layoutBuilder: (Widget? currentChild, List<Widget> previousChildren) {
            return currentChild ??
                ElevatedButton(
                  onPressed: () {
                    setState(() {
                      isSelected = !isSelected;
                    });
                  },
                  child: const Text("AnimatedSwitcher2222"),
                );
          },
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/flutter/flutter/assets/22124534/36540a00-f987-4ae3-b325-ff192c3f8407)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by dam-ease** [comment]
Hi @OnClickListener2048. There seems to be a currently open issue similar to the case you described #50168. Kindly confirm this is as well.

**Comment by OnClickListener2048** [comment]
Hi @dam-ease  I think it's the same problem,but i don't see any solution in that issue for over three years, what should i do with it.

**Comment by dam-ease** [comment]
Hi @OnClickListener2048. You can comment on the currently open issue and upvote the issue as well. Closing this as a duplicate.
