### ISSUE TITLE
[engine v2] add symbols.zip to android_profile_arm64

### ISSUE THREAD

**Issue by XilaiZhang** [flutter/flutter#128907]
based on [current builder config](https://github.com/flutter/engine/blob/main/ci/builders/linux_android_aot_engine.json) it seems like currently we are not producing symbols.zip in android_profile_arm64. We might want to add it back in android_profile_arm64

**Comment by XilaiZhang** [comment]
cc @godofredoc followup from triage

**Comment by godofredoc** [comment]
This is the list of configs the symbols were being uploaded to https://flutter.googlesource.com/recipes/+/a0469282e638ed1d016e30a40effa9b3ccd317f2/recipes/engine/engine.py#681
