### ISSUE TITLE
Shell subprocess crashed with segmentation fault while running flutter test --coverage only

### ISSUE THREAD

**Issue by milodude** [flutter/flutter#128953]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I run flutter test and all tests are passing properly as expected. Afterwards I run flutter test --coverage and some tests start failing

### Expected results

Tests run with parameter --coverage run as expected

### Actual results

Tests failing with flutter_tester process at pid 15033 exited with code=-11  when running under verbose
Shell subprocess crashed with segmentation fault.
unhandled error during finalization of test:TestDeviceException(Shell subprocess crashed with segmentation fault.)

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[https://drive.google.com/file/d/176glISaVxDEBiMIntpsnZ35Z4LD3vkPE/view?usp=drive_link](video)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4 22F66 darwin-arm64, locale es-419)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.79.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by dam-ease** [comment]
Hi @milodude. Can you please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this?

**Comment by milodude** [comment]
@dam-ease I have solved the issue in a strange way. I was not able to provide you with an example since the tests were failing when I was running all of them at the same time with --coverage.  
These are the steps I did before getting all of them as passed.
1- I run one of the failing tests individually with 
`flutter test {path_of_single_file} --coverage`
-I had no failures and all the tests inside of it passed.
2- I run again flutter test --coverage
- The error I submitted did not appear anymore and one of the data layer tests was in fact broken
3- I fix it and the run flutter test --coverage one more time. 
- All my tests passed.

My final conclusion is that there is some kind of cache file that is being written in order to grab the tests from there in order to improve performance. This file was corrupted somehow and I started getting this error.  One I ran my test individually with the --coverage parameter individually this file was generated for this particular test again. If this is not the case and I am talking non sense, please let me know in order to understand why this was happening in the first place.

**Comment by dam-ease** [comment]
Hi @milodude. This may or may not be the case depending on your use case. Thanks for confirming it works.
