### ISSUE TITLE
with error "ExtendedTextSelectionState" is missing implementations for <TextInputClient.didChangeInputControl>&&<TextInputClient.performSelector>

### ISSUE THREAD

**Issue by nocoah** [flutter/flutter#128933]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

when i run command  ->    flutter build apk
it takes error!

my flutter version information is below:

C:\Users\nocoah>flutter --version
Flutter 3.7.1 • channel master • https://github.com/flutter/flutter.git
Framework • revision 7048ed95a5 (4 months ago) • 2023-02-01 09:07:31 -0800
Engine • revision 800594f1f4
Tools • Dart 2.19.1 • DevTools 2.20.1

i had tried like these:

delete folder build
delete pubspec.lock
flutter clean
flutter pub get

### Actual results

Flutter assets will be downloaded from https://mirrors.tuna.tsinghua.edu.cn/flutter. Make sure you trust this source!

 Building with sound null safety 

Flutter assets will be downloaded from https://mirrors.tuna.tsinghua.edu.cn/flutter. Make sure you trust this source!
/C:/Users/nocoah/AppData/Local/Pub/Cache/hosted/mirrors.tuna.tsinghua.edu.cn%2547dart-pub%2547/extended_text-9.1.2/lib/src/selection/extended_text_selection.dart:151:7: Error: The non-abstract class 'ExtendedTextSelectionState' is missing implementations for these members:
 - TextInputClient.didChangeInputControl
 - TextInputClient.performSelector
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ExtendedTextSelectionState extends State<ExtendedTextSelection>
      ^^^^^^^^^^^^^^^^^^^^^^^^^^
/E:/flutter/packages/flutter/lib/src/services/text_input.dart:1163:8: Context: 'TextInputClient.didChangeInputControl' is defined here.
  void didChangeInputControl(TextInputControl? oldControl, TextInputControl? newControl) {}
       ^^^^^^^^^^^^^^^^^^^^^
/E:/flutter/packages/flutter/lib/src/services/text_input.dart:1184:8: Context: 'TextInputClient.performSelector' is defined here.
  void performSelector(String selectorName) {}
       ^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* Where:
Script 'E:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1155

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'E:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 32s
Running Gradle task 'assembleRelease'...                           33.7s
Gradle task assembleRelease failed with exit code 1

### Flutter Doctor output

C:\Users\nocoah>flutter doctor -v
Flutter assets will be downloaded from https://mirrors.tuna.tsinghua.edu.cn/flutter. Make sure you trust this source!
[√] Flutter (Channel master, 3.7.1, on Microsoft Windows [版本 10.0.19044.2965], locale zh-CN)
    • Flutter version 3.7.1 on channel master at E:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7048ed95a5 (4 months ago), 2023-02-01 09:07:31 -0800
    • Engine revision 800594f1f4
    • Dart version 2.19.1
    • DevTools version 2.20.1
    • Pub download mirror https://mirrors.tuna.tsinghua.edu.cn/dart-pub
    • Flutter download mirror https://mirrors.tuna.tsinghua.edu.cn/flutter

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\nocoah\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: E:\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 17+35-2724)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.5)
    • Visual Studio at E:\vs2022
    • Visual Studio Community 2022 version 17.0.32112.339
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.2)
    • Android Studio at E:\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17+35-2724)

[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at E:\IntelliJ IDEA 2021.1.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.19044.2965]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 113.0.5672.64
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 110.0.1587.63

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by huycozy** [comment]
Hi @nocoah 
This is an issue with [extended_text](https://pub.dev/packages/extended_text) which is a 3rd party package so you should report there for better support. 

Regarding your issue, I see there was a known issue (https://github.com/fluttercandies/extended_text/issues/137). It might be fixed on newer package version.

Closing the issue as it's not Flutter framework or 1st party plugin issue.
