### ISSUE TITLE
Flutter needs accelerated image processing primitives

### ISSUE THREAD

**Issue by lukehutch** [flutter/flutter#128972]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I am dumbfounded by the lack of powerful offscreen accelerated image processing primitives on Flutter, when it has such an incredible renderer.

I am trying to do some basic image processing in my UI (loading a JPEG from a file, displaying the image in a cropping UI, cropping and resizing the image to a target aspect ratio and dimensions, re-encoding as a JPEG).

The only way I can find to do even these most basic of image operations on Flutter is to make use of the [`image`](https://pub.dev/packages/image) library. This library is the go-to library for image processing in Flutter. However, it [does all image processing one pixel at a time in Dart](https://github.com/brendan-duncan/image/blob/main/lib/src/transform/copy_resize.dart#L83), so it is very slow. `image` even [implements its own codecs in Dart](https://github.com/brendan-duncan/image/blob/main/lib/src/formats/jpeg/jpeg_data.dart), and these are extremely slow too!

There are numerous 3rd party libraries that try to speed up certain operations, e.g. cropping, or compressing/decompressing, by moving those operations to Android/iOS:

https://pub.dev/packages/native_image_cropper
https://pub.dev/packages/flutter_image_compress

[`graphx`](https://github.com/roipeker/graphx) at least seems to use the [codecs](https://github.com/roipeker/graphx/blob/master/lib/src/io/resource_loader.dart) of `Canvas` to decompress/compress images more quickly than `image`. However it does not provide any image cropping, resizing, mirroring/rotating features etc.

As a more general observation, image processing in Flutter generally uses `Uint8List` to represent the decoded ARGB bytes of the image, but some libraries even convert this by repacking into a `List<int>` (this is horrifically inefficient). Also I would expect images to be kept in memory in their *compressed* form, not their uncompressed form, with uncompressed pixels only cached if there is frequent reuse of the uncompressed form. I believe the most common formats can be rendered directly, without uncompressing on the CPU first, in most acceleration APIs today?

### Actual results

Image processing is painfully slow on Flutter currently.

Flutter really (*really*) needs some powerful offscreen image processing primitives, which are hardware-accelerated wherever possible on the target architecture.

Even supporting just a few basic operations (encode/decode, resize, crop, mirror, rotate, mask, blur, sharpen) would be huge.

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.10.4, on Fedora Linux 38 (Workstation Edition)
    6.3.6-200.fc38.x86_64, locale en_US.utf8)
    • Flutter version 3.10.4 on channel stable at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 682aa387cf (10 days ago), 2023-06-05 18:04:56 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/luke/Android/Sdk
    • Platform android-UpsideDownCake, build-tools 33.0.1
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 16.0.5 (Fedora 16.0.5-1.fc38)
    • cmake version 3.26.4
    • ninja version 1.11.1
    • pkg-config version 1.8.0

[✓] Android Studio (version 2022.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 73.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.79.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.66.0

[✓] Connected device (3 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 13
      (API 33) (emulator)
    • Linux (desktop)            • linux         • linux-x64      • Fedora Linux
      38 (Workstation Edition) 6.3.6-200.fc38.x86_64
    • Chrome (web)               • chrome        • web-javascript • Google
      Chrome 114.0.5735.106

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by jonahwilliams** [comment]
I'm a bit confused about what you're asking about.

package:image implements codecs for conversion between image formats. These formats are usually compressed, and decoding or encoding/converting between these formats and raw pixel data is a fundamentally serial and CPU bound operation (though of course, its better to run this work on background threads). There are no GPUs that I am aware of that natively support these formats.

On the other hand, resizing/cropping/mirriring, et cetera are absolutely all performed by a GPU on you are dealing with a ui.Image. So for example, create a canvas, draw an image, apply a blur, call toImage on that canvas, then ask for the png bytes. Boom, you have GPU accelerated image processing.

```
var recorder = PictureRecorder();
var canvas = Canvas(recorder);
canvas.drawImage(Offset.zero, myImage);
canvas.transform( ... some transformation ...)
var picture = recorder.endRecording();
picture.toImage(100, 100).then((ui.Image) {
  var png = ui.Image.toByteData(format: ... whatever you want )
}

```

Is that what you are asking for?

**Comment by lukehutch** [comment]
@jonahwilliams Yes, that looks like what I was looking for, thanks. I didn't realize you could use `Canvas` in that way. I did a lot of digging, and all I found just before seeing your response was a way to [render widgets off-screen](https://github.com/flutter/flutter/issues/40064#issuecomment-1553409024).

Your response makes me wonder why the `image` library doesn't do exactly this for image rescaling etc. -- it would be dramatically faster. Part of the reason why I couldn't find the `Canvas` solution is that everybody seems to be using the `image` library if they want to do image processing, so that reinforced the assumption that there was no efficient alternative.

Many thanks!

**Comment by jonahwilliams** [comment]
IIRC image does not depend on Flutter, which is probably why.
