### ISSUE TITLE
FML needs a platform/fuchsia implementation.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#12897]
The only major component of this implementation is a message loop. The `flutter/fml:fml_unittests` target should build and successfully exit. For a simple implementation, refer to the [Linux backend](https://github.com/flutter/engine/blob/master/fml/platform/linux/message_loop_linux.cc).

**Comment by tvolkert** [comment]
@chinmaygarde is this still relevant?

**Comment by chinmaygarde** [comment]
After the shell refactor, Fuchsia is now a custom embedder and patches in its own message loops and other utilities via the per shell settings object.
