### ISSUE TITLE
[packages] Switch from `submit-queue` to `flutter-luci` for PR tree state

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#128954]
Currently flutter/packages uses [`submit-queue`](https://github.com/apps/submit-queue) as the "test" in PRs that reflects current tree status (i.e., whether the latest commit's post-submits are all green) to prevent PRs landing into a closed tree. This mostly works, but sometimes it becomes stale in some PRs (e.g., showing red forever even once the tree is green again) for reasons we don't understand. Ideally we would move to the same tooling that flutter/flutter and flutter/engine use, which is `tree-status` (managed by Cocoon, IIUC), so that:
- flutter/packages is more consistent with our other repos, making it easier for engineers who move between repos, and
- we can debug and fix issues like the staleness problem, since we control the logic.

My understanding that check will only get LUCI post-submit statuses, which means this is blocked on https://github.com/flutter/flutter/issues/114373 since currently about half of our post-submits are on Cirrus.

**Comment by stuartmorgan** [comment]
We no longer have any Cirrus post-submit tests (only one pre-submit)

**Comment by stuartmorgan** [comment]
(Closing was a mis-click)

We no longer have any Cirrus post-submit tests (only one pre-submit), so this is unblocked. We've been having a lot of issues with staleness with this check recently, so now that we're unblocked I would very much like to have the packages repo moved over to the check used by the engine and framework repos.

@yusuf-goog Please re-assign if you're not the right owner for this.

**Comment by ricardoamador** [comment]
@keyonghan is this done? I recall you did some work around this.

**Comment by ricardoamador** [comment]
Ah gotcha. Thank you for clarifying!

**Comment by keyonghan** [comment]
All cirrus tasks are in LUCI, remaining work
- [ ] Enable tree status in packages repo
- [ ] Disable submit-queue (uninstall the app) from packages repo
- [ ] Stop creating/updating post-submit checkruns to packages repo

**Comment by keyonghan** [comment]
https://github.com/flutter/cocoon/pull/3232 landed. A manual push to enable the cronjob works:

<img width="1096" alt="Screenshot 2023-11-07 at 1 25 27 PM" src="https://github.com/flutter/flutter/assets/54558023/2deb26e4-a20b-4d36-b235-3dab7bf949ba">

@stuartmorgan could you try uninstalling the submit-queue app from the repo?

**Comment by stuartmorgan** [comment]
> @stuartmorgan could you try uninstalling the submit-queue app from the repo?

I'm not an admin for the repo, so if it's something you don't have the ability to do, I almost certainly don't either.

**Comment by keyonghan** [comment]
@godofredoc Is this something you can help with?

**Comment by keyonghan** [comment]
> * [ ]  Stop creating/updating post-submit checkruns to packages repo

We cannot remove the post-submit checkruns from packages repo considering the auto-publish GitHub action [waits for all post-submit tests to pass](https://github.com/flutter/plugins/blob/main/.github/workflows/release.yml#L37-L47) before publishing. Created https://github.com/flutter/flutter/issues/138092 to track this. (removing this action item from this bug)

**Comment by keyonghan** [comment]
Submit-queue was uninstalled, and now packages repo is consistent with other repos with `tree-status`. Closing here with https://github.com/flutter/flutter/issues/138092 to track a general post-submit tests passing event.
