### ISSUE TITLE
[autosubmit] Autosubmit should check for the presence of Google Testing.

### ISSUE THREAD

**Issue by itsjustkevin** [flutter/flutter#128955]
## Request

The `autosubmit` label should check for the presence of the Google Testing check before allowing pull requests to be submitted on Master / Main.

## Context

There are numerous instances where a user submits a pull request by adding the `autosubmit` label to their PR.

[Example](https://github.com/flutter/flutter/pull/124558)

Due to the nature of Google Testing running on a cron job, there are times where autosubmit sees that all checks are green and code review is satisfied, then submits the PR.  Occasionally, this happens in a timeframe where the PR has not had the google testing check attached, which can result in failures being identified in post submit.

## Impact

Contributors may be confused as to why a PR that passed all presubmit checks has to suddenly be reverted, or spend time searching for a mistake they made.

**Comment by itsjustkevin** [comment]
CC: @godofredoc @ricardoamador  @christopherfujino

**Comment by ricardoamador** [comment]
This is a duplicate of https://github.com/flutter/flutter/issues/122543

**Comment by itsjustkevin** [comment]
Thanks @ricardoamador closing this and commenting on https://github.com/flutter/flutter/issues/122543.
