### ISSUE TITLE
Allow creating cross context SkImages from arbitrary bitmaps.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#12891]
In order to support decoding and texture upload of GIF image frames on the IO thread, it would be great if SkImage provided a utility to create a cross context image from the arbitrary bitmaps or just a pair of SkDecoder and frame a frame index. This would be very similar to the `SkImage::MakeCrossContextFromEncoded` call that currently only takes the compressed image bytes as input.

**Comment by chinmaygarde** [comment]
cc @brianosman @amirh

**Comment by brianosman** [comment]
I'm proposing that this be implemented as SkImage::MakeCrossContextFromPixmap(). That matches the output from SkCodec, and is the lowest level object we have to describe a block of raster data. Make sense?

**Comment by chinmaygarde** [comment]
Sounds good to me.

**Comment by brianosman** [comment]
New API has landed:
https://skia.googlesource.com/skia.git/+/63bc48d09323a62c8c67237fc66ad6ec7105e973

**Comment by amirh** [comment]
Thanks!

**Comment by chinmaygarde** [comment]
This has been implemented and rolled. Thanks!
