### ISSUE TITLE
Widget Cheat Sheet

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#129]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Wednesday Aug 19, 2015 at 23:14 GMT_
_Originally opened as https://github.com/flutter/engine/issues/701_

----

We need a Widget cheat sheet that has all the various widgets graphically presented along with their arguments and a brief description of what they do.

This should be something that's easy to maintain since it'll get out of date quickly.

**Comment by Hixie** [comment]
Closing in favour of https://github.com/flutter/flutter/issues/1433
