### ISSUE TITLE
[Impeller] `new_gallery_impeller__transition_perf` gives noisy results

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#129046]
About 1/5 times the measurement for `average_frame_rasterizer_time_millis` will spike 2x.

Skia perf link: [Skia Perf](https://flutter-flutter-perf.skia.org/e/?end=1687038803&keys=Xc266cefa78856177cd92ded480267478&selected=commit%3D35358%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DSM-G973U1%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253Daverage_frame_rasterizer_time_millis%252Ctest%253Dnew_gallery_impeller__transition_perf%252C)

<img width="1702" alt="Screenshot 2023-06-16 at 4 01 01 PM" src="https://github.com/flutter/flutter/assets/30870216/36d8a30b-1e04-484d-8e25-35eff0be8720">

**Comment by gaaclarke** [comment]
This lead to a bit of a red herring with https://github.com/flutter/engine/pull/42865

**Comment by chinmaygarde** [comment]
Were you able to get to the bottom of this or is an investigation still pending?

**Comment by chinmaygarde** [comment]
This started happening a bit after the Vulkan switch. Since it is flaky, it is reasonable to assume this was a Vulkan switch thing.

**Comment by gaaclarke** [comment]
> Were you able to get to the bottom of this or is an investigation still pending?

I have no theories yet.  I'm still trying to understand better what is happening generally.  It's unfortunate since this is the prime benchmark we want to address for vulkan and we can't trust its results until it is more consistent.  Adding more samples may not help.  We still don't know if it gets in a consistent bad state or if there are some outliers that are messing up the average.  Plus, a 10ms average is okay, a 20ms average is not.

We could start recording the standard deviation, which could help answer that question.  Once we have that number we could consider different approaches to removing outliers.

---

I considered running the test multiple times and take the median result:

If it happens 1/5 times, if we ran the test this many times, here are the chances that it will show up in the median result:
1) P(2,3) = 9.6%
1) P(3,5) = 5.12%
2) P(4,7) = 2.87% 

That isn't viable since the test takes so long anyways.

**Comment by gaaclarke** [comment]
I reproduced the problem locally with standard deviation tracking on:
## no problem
```
  "average_frame_build_time_millis": 1.6860165745856353,
  "90th_percentile_frame_build_time_millis": 3.345,
  "99th_percentile_frame_build_time_millis": 16.757,
  "worst_frame_build_time_millis": 60.396,
  "missed_frame_build_budget_count": 5,
  "average_frame_rasterizer_time_millis": 10.033743093922645,
  "stddev_frame_rasterizer_time_millis": 6.294969048563838,
  "90th_percentile_frame_rasterizer_time_millis": 14.044,
  "99th_percentile_frame_rasterizer_time_millis": 92.39,
  "worst_frame_rasterizer_time_millis": 112.953,
  "missed_frame_rasterizer_budget_count": 31,
  "frame_count": 362,
  "frame_rasterizer_count": 362,
  "new_gen_gc_count": 0,
  "old_gen_gc_count": 0,
```
## with problem
```
  "average_frame_build_time_millis": 1.8367261538461537,
  "90th_percentile_frame_build_time_millis": 4.699,
  "99th_percentile_frame_build_time_millis": 20.199,
  "worst_frame_build_time_millis": 28.106,
  "missed_frame_build_budget_count": 8,
  "average_frame_rasterizer_time_millis": 22.573616564417176,
  "stddev_frame_rasterizer_time_millis": 22.880952199932253,
  "90th_percentile_frame_rasterizer_time_millis": 80.363,
  "99th_percentile_frame_rasterizer_time_millis": 109.876,
  "worst_frame_rasterizer_time_millis": 117.538,
  "missed_frame_rasterizer_budget_count": 92,
  "frame_count": 325,
  "frame_rasterizer_count": 326,
  "new_gen_gc_count": 0,
  "old_gen_gc_count": 0,
  "frame_build_times": [
```
## evaluation
The increase in stddev means a huge increase in variance, which can also be seen in the 90th percentile increase.  I'm not sure we want to find some way to filter this out, best to try to diagnose and fix the cause.

**Comment by jonahwilliams** [comment]
This was fixed by the change to make addFences less blocking on qualcomm socs

https://flutter-flutter-perf.skia.org/e/?queries=device_type%3DSM-G973U1%26test%3Dnew_gallery_impeller__transition_perf&selected=commit%3D35458%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DSM-G973U1%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253D99th_percentile_frame_rasterizer_time_millis%252Ctest%253Dnew_gallery_impeller__transition_perf%252C

https://github.com/flutter/engine/pull/43131
