### ISSUE TITLE
Flutter_markdown: add scroll view to markdown table

### ISSUE THREAD

**Issue by shuotwang** [flutter/flutter#129052]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

As the screen shot shows, if I have a very wide table, the contents are too narrow to read. It would be good if I can pan this table around with a much more human-readable column width. 

The reason why I do not wrap the whole Markdown widget into a scrollable widget is that it will cause bad experience for other contents, for example, if text content is also scrollable, I need to pan around for each lone text line. It would be good if only large contents like tables and code blocks have the scroll behavior. 

<img width="284" alt="截屏2023-06-16 下午6 07 14" src="https://github.com/flutter/flutter/assets/35218239/2a754627-6340-4876-8c30-cc99a5b8d203">

### Proposal

the Table widget inside markdown builder function could be wrapped with a scrollable widget just like how it's done with code blocks, and provide the block constraints settings. Or, the constraints could be just the constraints of its parent widget. If the size of table (probably together with a minimum tableColumnWidth setting) exceeds the constrains, scroll gesture is enabled.

**Comment by tylerjvollick** [comment]
Any updates on this? I'm facing the same issue with markdown tables we're trying to render with too many columns for the given horizontal space.

**Comment by phong010198** [comment]
I'm facing the same issue. Need horizontal scroll when using FixedColumnWidth
```dart
styleSheet: MarkdownStyleSheet(
  tableColumnWidth: FixedColumnWidth(value),
),
```

**Comment by Bazni** [comment]
The fix works well. Is a PR on going or should I try opening one?
