### ISSUE TITLE
Flutter integration test appears to re-run after a successful test

### ISSUE THREAD

**Issue by leeleeleeleeleeleelee** [flutter/flutter#129097]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I have a very basic Flutter test. After a successful test (using ChromeDriver) called via below, a failure is encountered as the test appears to run again.

initiate test by: flutter drive \ --driver=test_driver/integration_test.dart \ --target=integration_test/app_test.dart \ -d edge

Test:

```
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

import 'package:rova/main.dart' as app;

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  group('end-to-end test', () {
    testWidgets('Select the Submit Incident link, verify frame opens', (tester) async {

      //setup
      app.main();
      await tester.pumpAndSettle();

      //do
      final Finder login = find.text('Login');
      await tester.tap(login);
      await Future.delayed(const Duration(seconds: 5)); //allow time for login to process
      await tester.pumpAndSettle();
      
      final Finder button = find.text('Submit Incident');
      await tester.tap(button);
      await tester.pumpAndSettle();

      //test
      expect(find.text('INCIDENT SUBMISSION'),findsOneWidget);
    });
  });
}
```

Any help appreciated

### Expected results

The test stops at All tests passed!, and TearDown is successful.

### Actual results

The test passes, however then comes up with a Failure:

> Launching integration_test/app_test.dart on Edge in debug mode...
> Asset manifest contains a null or empty uri.
> Waiting for connection from debug service on Edge...               74.8s
> This app is linked to the debug service: ws://127.0.0.1:62166/bV0WQwjk6d0=/ws
> Debug service listening on ws://127.0.0.1:62166/bV0WQwjk6d0=/ws
> 00:00 +0: end-to-end test Select the Submit Incident link, verify frame opens
> 00:13 +1: (tearDownAll)
> 00:13 +2: All tests passed!
> Failure Details:
> Failure in method: Select the Submit Incident link, verify frame opens
> ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
> The following assertion was thrown running a test:
> The finder "zero widgets with text "Submit Incident" (ignoring
> offstage widgets)" (used in a call to "tap()") could not find any
> matching widgets.
> 
> When the exception was thrown, this was the stack:
> dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 288:49  throw_
> packages/flutter_test/src/controller.dart 1293:7                              [_getElementPoint]
> packages/flutter_test/src/controller.dart 1232:12                             getCenter
> packages/flutter_test/src/controller.dart 554:18                              tap
> app_test.dart 29:19                                                           <fn>
> dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50            <fn>
> dart-sdk/lib/async/zone.dart 1407:47                                          _rootRunUnary
> dart-sdk/lib/async/zone.dart 1308:19                                          runUnary
> dart-sdk/lib/async/future_impl.dart 147:18                                    handleValue
> dart-sdk/lib/async/future_impl.dart 784:44                                    handleValueCallback
> dart-sdk/lib/async/future_impl.dart 813:13                                    _propagateToListeners
> dart-sdk/lib/async/future_impl.dart 584:5                                     [_completeWithValue]
> dart-sdk/lib/async/future_impl.dart 657:7                                     <fn>
> dart-sdk/lib/async/zone.dart 1399:13                                          _rootRun
> dart-sdk/lib/async/zone.dart 1301:19                                          run
> dart-sdk/lib/async/zone.dart 1209:7                                           runGuarded
> dart-sdk/lib/async/zone.dart 1249:23                                          callback
> dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
> dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
> dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 177:15           <fn>
> 
> The test description was:
>   Select the Submit Incident link, verify frame opens
> ═════════════════════════════════════════════════════════════════
> 
> end of failure 1

I cannot work out why it is passing the test, then seemingly failing.  The text "Submit Incident" is not found on the "second" test, as the page has closed to the Testing Finished page.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

import 'package:rova/main.dart' as app;

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  group('end-to-end test', () {
    testWidgets('Select the Submit Incident link, verify frame opens', (tester) async {

      //setup
      app.main();
      await tester.pumpAndSettle();

      //do
      final Finder login = find.text('Login');
      await tester.tap(login);
      await Future.delayed(const Duration(seconds: 5)); //allow time for login to process
      await tester.pumpAndSettle();
      
      final Finder button = find.text('Submit Incident');
      await tester.tap(button);
      await tester.pumpAndSettle();

      //test
      expect(find.text('INCIDENT SUBMISSION'),findsOneWidget);
    });
  });
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
https://pastebin.com/v9XwWrjZ
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.19042.2965], locale en-AU)
    • Flutter version 3.10.5 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (5 days ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.79.2)
    • VS Code at C:\Users\46767\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.66.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.2965]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 114.0.5735.134
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 114.0.1823.51

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
exit code 0
```

</details>

**Comment by huycozy** [comment]
Hi @leeleeleeleeleeleelee 
Can you also please provide the sample code at `package:rova/main.dart`?

May be related to https://github.com/flutter/flutter/issues/129041.

**Comment by leeleeleeleeleeleelee** [comment]
Thank you @huycozy , as requested:


```
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '/manager.dart';
import 'package:aad_oauth/model/config.dart';

import 'providers/user.dart';

void main() => runApp(const Rova());

final navigatorKey = GlobalKey<NavigatorState>();

class Rova extends StatelessWidget {
  const Rova({Key? key}) : super(key: key);
  static final Config authConfig = Config(
	tenant: '########-####-####-####-############',
	clientId: '########-####-####-####-############',
    scope: 'User.Read.All',
    navigatorKey: navigatorKey,
    webUseRedirect: kIsWeb ? false : true,
    loader: const CircularProgressIndicator(),
  );

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider<UserProvider>(create: (_) => UserProvider()),
      ],
      child: MaterialApp(
        title: 'ROVA',
        theme: ThemeData(
          colorSchemeSeed: const Color(0xff218FA3),
          useMaterial3: true,
        ),
        debugShowCheckedModeBanner: false,
        home: Manager(authConfig: authConfig),
        navigatorKey: navigatorKey,
      ),
    );
  }
}
```

**Comment by huycozy** [comment]
@leeleeleeleeleeleelee Thanks for your response. But I see the sample code contains 3rd party package and undefined component. Can you please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or production code so that we may verify this?
