### ISSUE TITLE
integration_test Whether macOS desktop applications are supported

### ISSUE THREAD

**Issue by sliderss** [flutter/flutter#129080]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I am currently doing automated UI testing for macOS, using integration_test, but even the simplest example doesn't work, so I wanted to ask flutter if there is something else that supports automated UI testing for macOS desktop. Automated UI testing that supports all desktop applications is even better

### Proposal

myself@myselfdeMacBook-Pro integration_test % flutter test login_test.dart

Changing current working directory to: /Users/myself/code/shalibaron/2023.5.31/Shalibaron/dsi-ui/dsi-console
00:02 +0: Add and remove a todo                                                                                                                
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following LateError was thrown running a test:
LateInitializationError: Field 'shalihome' has not been initialized.

When the exception was thrown, this was the stack:
#0      ManagerConfigSingleton.shalihome (package:shalitalk/system/data/userInfo.dart)
#1      ManagerConfigSingleton.CheckUserInfoExist (package:shalitalk/system/data/userInfo.dart:161:21)
#2      main.<anonymous closure> (file:///Users/myself/code/shalibaron/2023.5.31/Shalibaron/dsi-ui/dsi-console/lib/integration_test/login_test.dart:26:45)
#3      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:170:29)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  Add and remove a todo
════════════════════════════════════════════════════════════════════════════════════════════════════
00:02 +0 -1: Add and remove a todo [E]                                                                                                         
  Test failed. See exception logs above.
  The test description was: Add and remove a todo
  

To run this test again: /Users/myself/flutter/bin/cache/dart-sdk/bin/dart test /Users/myself/code/shalibaron/2023.5.31/Shalibaron/dsi-ui/dsi-console/lib/integration_test/login_test.dart -p vm --plain-name 'Add and remove a todo'
00:02 +0 -1: (tearDownAll)                                                                                                                     
Warning: integration_test plugin was not detected.

If you're running the tests with `flutter drive`, please make sure your tests
are in the `integration_test/` directory of your package and use
`flutter test $path_to_test` to run it instead.

If you're running the tests with Android instrumentation or XCTest, this means
that you are not capturing test results properly! See the following link for
how to set up the integration_test plugin:

https://flutter.dev/docs/testing/integration-tests#testing-on-firebase-test-lab

00:02 +0 -1: Some tests failed.

**Comment by stuartmorgan** [comment]
`integration_test` supports macOS, as well as the other desktop platforms. The only part that's not supported, which is what the warning is about, is driving macOS integration tests from Xcode and getting the results in the Xcode test UI.

The failure here is in code in your application (an uninitialized late variable); the warning is harmless, and unrelated to the failure.
