### ISSUE TITLE
[Impeller] JIT construction of PSO variants causes jank on Vulkan.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#129050]
Split off from https://github.com/flutter/flutter/issues/128919

Continuation of https://github.com/flutter/flutter/issues/128963

Unlike Metal, constructing new PSO variants in vulkan is incredibly expensive - on the order of milliseconds. Current the content_context.cc setup will attempt to construct a default PSO for every shader we have. Unfortunately some of the defaults don't match what the application will end up using, so aside from wasting time at startup we're guaranteeing that we'll need to compile a PSO in a frame workload.

In no particular order:

All PSOs are generated with sample count of 1, whereas 4 is the default MSAA config
Several PSOs appear to have an unknown pixel format, meaning they're not actually valid. Perhaps a race between knowing which pixel format to use and the offscreen format.
The primitive type defaults to kTriangle but some shaders only use kTriangleStrip like clips. This should be configured.
SrcOver is the default blend mode, but SrcOver to Src cooercsion will commonly apply to several variants and should be pre-cached.
Stencil operations frequently mismatch. The default is kEqual, but textures use kAlways and strokes use kLess

**Comment by jonahwilliams** [comment]
See also: https://github.com/flutter/flutter/issues/128963#issuecomment-1593732223

**Comment by chinmaygarde** [comment]
From the weekly sync, the time to setup a PSO variant is now significantly faster after @jonahwilliams landed his patch [to give Vulkan a dedicated worker pool with threads having elevated priorities](https://github.com/flutter/engine/commit/de489e35e3463925ab8593c2ed546a2100aeba14). The setup seems to be about as fast as the Metal backend. Lowering the priority of this issue but still keeping it open as this could violate Impeller consistent performance guarantee.

**Comment by chinmaygarde** [comment]
Closing as there isn't an action item here. We might use more dynamic states as they become available on Vulkan.
