### ISSUE TITLE
Google Maps Flutter not removing previous markers

### ISSUE THREAD

**Issue by jasminder** [flutter/flutter#129078]
I have created an app where, as user location gets updated, his marker on map also gets updated. I am using a custom image for the marker. But, the issue I am facing is that the old marker is still visible on the map. Sometimes, there is only 1 marker as it should be, but, some other times, there are multiple markers on the screen, like 5-6 markers.  However, if I implement a button to hide and then show the map again on the screen, it works and previous markers are gone and there is only 1 marker.  I am using google_maps_flutter version 2.2.5 and flutter version 3.7.12.  A more detailed question with code is [here](https://stackoverflow.com/questions/76495074/flutter-google-maps-marker-duplicate)
The red dots represent the current user location.
![duplicate marker](https://github.com/flutter/flutter/assets/1322355/6df03868-e273-4604-b08d-e2f202e9de22)

**Comment by Sillco** [comment]
I would suggest trying out version 2.2.6 of google_maps_flutter as it has fixed the issue you are currently facing. From my knowledge, the error you described does not reproduce in this version. Additionally, I recommend checking the latest version, 2.3.1, as there might be further improvements and fixes, including any regression issues that could be causing the problem. It's worth exploring the latest version to see if it resolves the marker visibility issue you mentioned.

**Comment by jasminder** [comment]
I tried with 2.2.6 and 2.3.0 and it didn't work. Couldn't test with 2.3.1 as that is incompatible with current Dart and Flutter version on my machine.

**Comment by huycozy** [comment]
@jasminder Based on your description, it seems to be similar to an issue (https://github.com/flutter/flutter/issues/128042) that has been fixed recently and available on the latest plugin version (please see the [changelog](https://pub.dev/packages/google_maps_flutter/changelog#231)). 

Please try using the latest version and confirm if the issue is fixed. For the incompatible issue on your project, you should isolate the screen that loads map and verify it only.

**Comment by jasminder** [comment]
Just tested with 2.2.6 again and 2.3.1 too. It did not work. I will provide the reproducible code soon.

**Comment by jasminder** [comment]
I tested again and although, 2.2.6 does not work, but, 2.3.1 seems to work so far. Thanks for the help.
