### ISSUE TITLE
Add "willPop" and "willPush" to NavigatorObserver

### ISSUE THREAD

**Issue by paolosoares** [flutter/flutter#12901]
These might be useful for debugging issues that would prevent a route from being pushed, or to peek into a route's settings to trigger any preloading operations.

**Comment by Hixie** [comment]
@paolosoares Can you elaborate on the use cases you want us to address? I would like to carefully consider them in more detail.

**Comment by alanrussian** [comment]
One issue Mulligan has is with regards to deep linking and changing accounts. We'd like to have some infrastructure that automatically handles account selection when a deep link comes through with a different account. The idea would be that in will(Pop|Push), we would clear out our global account model and issue a request to populate the account. Then, the route's widget will try to request for data using the current account, which it will wait for using our accountModel.getCurrentAccount() => Future<Account> API. If the account model weren't cleared before the widget was displayed, it would get the stale account. 

Paolo can speak more to how we're getting around this, but it looks like for now we're going to have all our routes extends a common class that will do this for us.

**Comment by Hixie** [comment]
One of the things I may be looking at in the coming weeks is a pluggable route handling system, so when a deep link comes in, you get to do whatever you want with it, and then tell the framework what set of routes it should represent. That sounds like it might address your use case as well?

**Comment by alanrussian** [comment]
Sounds like it might work. I'll defer to @paolosoares though since he's doing most of the work on this.

**Comment by tvolkert** [comment]
Per @paolosoares this is no longer needed because didPush() and didPop() are called before the first build.  Closing, but we may want to reconsider if we change the semantics of those methods.

/cc @Hixie
