### ISSUE TITLE
[video-player] allowBackgroundPlayback not work on ios 

### ISSUE THREAD

**Issue by xypmhxy** [flutter/flutter#129076]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

On the ios system I set allowBackgroundPlayback and the background mode airdrop audio option is also set in xcode. Unfortunately, when I switch to the background, the video is still paused, but the audio resource will not be paused. How can I fix this problem

### Expected results

it work

### Actual results

when I switch to the background, the video is still paused, but the audio resource will not be paused. 

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Hi @xypmhxy 
Which plugin version are you using? Can you please share a minimal sample code that reproduces this issue?

**Comment by xypmhxy** [comment]
> Hi @xypmhxy Which plugin version are you using? Can you please share a minimal sample code that reproduces this issue?

This is my sample code 
class _MyHomePageState extends State<MyHomePage> {
  VideoPlayerController? _videoPlayerController;

  @override
  void initState() {
    _videoPlayerController = VideoPlayerController.network('https://media.w3.org/2010/05/sintel/trailer.mp4',
        videoPlayerOptions: VideoPlayerOptions(allowBackgroundPlayback: true));
    _videoPlayerController?.initialize().then((value) {
      _videoPlayerController?.play();
      setState(() {});
    });
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: (_videoPlayerController?.value.isInitialized ?? false)
            ? AspectRatio(
                aspectRatio: _videoPlayerController!.value.aspectRatio, child: VideoPlayer(_videoPlayerController!))
            : const SizedBox(
                width: 64,
                height: 64,
                child: CircularProgressIndicator(),
              ),
      ),
    );
  }
}

**Comment by huycozy** [comment]
Thanks for your update. But when I bring app to the background, video and audio are also paused and are resumed after being back to the foreground. Verified on `iPhone 7, iOS 15.7.2`. 

Which device are you checking this issue? 

Also, can you clarify the `Expected result`? You have enabled Audio in background mode and your current result is corresponding to that configuration. Is there any application that works as your expectation (iOS native app)?

**Comment by xypmhxy** [comment]
> 



> Thanks for your update. But when I bring app to the background, video and audio are also paused and are resumed after being back to the foreground. Verified on `iPhone 7, iOS 15.7.2`.
> 
> Demo video
> Which device are you checking this issue?
> 
> Also, can you clarify the `Expected result`? You have enabled Audio in background mode and your current result is corresponding to that configuration. Is there any application that works as your expectation (iOS native app)?

Thank you for your reply. My situation is the same as yours. I expect the result to be able to continue playing in the background. For users, they should be able to play the sound instead of continuing to play after returning to the app. Isn't this allowBackgroundPlayback the role?

**Comment by huycozy** [comment]
I see, thanks for confirming. That is a known issue being tracked at https://github.com/flutter/flutter/issues/62739. Closing this issue as a duplicate, so please follow up on it for further updates.
