### ISSUE TITLE
Add `InputDecorationTheme.merge`

### ISSUE THREAD

**Issue by TahaTesser** [flutter/flutter#129009]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Check out this comment for [context](https://github.com/flutter/flutter/pull/128950#issuecomment-1593399007).

`InputDecorationTheme.merge` is needed to preserve the `ThemeData.InputDecorationTheme` defaults for widgets that depend on `InputDecorationTheme`.

This allows overriding properties some properties while keeping the `ThemeData` defaults. 

### Proposal

Add `InputDecorationTheme.merge`

**Comment by navaronbracke** [comment]
@TahaTesser Should I close https://github.com/flutter/flutter/issues/125471 as a duplicate then?

**Comment by TahaTesser** [comment]
> @TahaTesser Should I close #125471 as a duplicate then?

Oops, I did search for it before filing this one. Looks like I couldn't find by searching `InputDecorationTheme` as this is a theme property, not an `InputDecoration` property. 

I can close this one.

**Comment by TahaTesser** [comment]
@navaronbracke 
The funny thing is that I found https://github.com/flutter/flutter/issues/127330 when searching for your issue and fixed that too.
