### ISSUE TITLE
Not able to build ipa

### ISSUE THREAD

**Issue by Daphneyong11** [flutter/flutter#129001]
Had tried check with previous issue, but not sure may had duplicate issue.

### Steps to reproduce

1. Build a flutter using webview plugin
2. Run command 'flutter build ipa' on macOS with Xcode installed
3. Hit the error with IPA failed to built

### Actual results

It runs into an error as below:

Failed to build iOS app
Error (Xcode): Undefined symbol: _FWFWKWebViewHostApiGetCodec

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

Encountered error while archiving for device.

### Logs

<details>
<summary>Logs</summary>

```console

<!-- sw-v@SW-Venturas-Mac northbankclub % flutter build ipa

Archiving com.northbankclub.mobile...
Automatically signing iOS for device deployment using specified development team
in Xcode project: <hide for privacy>
Running Xcode build...                                                  
Xcode archive done.                                         18.6s
Failed to build iOS app
Error (Xcode): Undefined symbol: _FWFWKWebViewHostApiGetCodec


Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)


Encountered error while archiving for device.-->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- [✓] Flutter (Channel stable, 3.10.5, on macOS 13.0 22A380 darwin-x64, locale
    en-MY)
    • Flutter version 3.10.5 on channel stable at /Users/sw-v/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (2 days ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/sw-v/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-x64 • macOS 13.0 22A380 darwin-x64

[✓] Network resources
    • All expected network resources are available.-->

```

</details>

**Comment by dam-ease** [comment]
Hi @Daphneyong11. Can you please provide your full `flutter build ipa -v`. If the logs are too long, you may attach them as txt file.
Thank you

**Comment by Daphneyong11** [comment]
[flutter build ipa -v log.txt](https://github.com/flutter/flutter/files/11783356/flutter.build.ipa.-v.log.txt)
Sorry for the late reply

**Comment by dam-ease** [comment]
Hi @Daphneyong11. Thanks. From your pubspec, I see you aren't using the latest version of the `webview_flutter` package. Can you try using the latest to see if this issue still persists?

**Comment by Daphneyong11** [comment]
Hi, it is possible not to alter the webview_flutter package, since need a lot of adjustment to the main.dart while need to solve this problem as fast as possible

**Comment by dam-ease** [comment]
Oh, to be sure the issue is or isn't with the package or with flutter, you'd have to test using the latest versions. You can create a new flutter project, add the latest version of the package and test if the issue reproduces.

**Comment by Daphneyong11** [comment]
ok, seem like the trouble is on the old webplugin, I made a simple new one with webview only and it works. Seem like need to put in lots of effort to turn the old code to the new one. 

Anyways, thanks.

**Comment by dam-ease** [comment]
Yes, thanks for confirming.
