### ISSUE TITLE
"File chooser dialog can only be shown with a user activation." during integration test.

### ISSUE THREAD

**Issue by Capricorn25Dec** [flutter/flutter#129096]
How can I bypass this issue while performing an integration test for Flutter web using Flutter integration_test framework?  
![image](https://github.com/flutter/flutter/assets/57892790/4506d5dc-cba4-4249-9ad0-1bcf33e5c135)
Or can anyone suggest another way of doing automation for Flutter Web instead of Flutter integration test, really appreciate that?

**Comment by darshankawar** [comment]
@Capricorn25Dec 
Your question is better suited for support channels like StackOverflow or flutter's reddit help page.
Closing from here, as this isn't a bug report or feature request.
