### ISSUE TITLE
firebase_storage Multiple dex files define

### ISSUE THREAD

**Issue by pauldemarco** [flutter/flutter#12904]
## Steps to Reproduce

1.  Add **firebase_storage** + **firebase_auth** as dependencies to pubspec.yaml
1.  Attempt to `flutter run`

## Logs

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/common/api/internal/zzcc;
```

**Comment by pauldemarco** [comment]
Things just seem to be working today, not sure the cause, but I'll close this for now.

**Comment by dac3971** [comment]
@pauldemarco this exact error is happening for me with firebase_auth + firebase_database.  Any clue what's going on here?

**Comment by rbprakash** [comment]
Hi , me too facing the problem while integrating the firebase "firebase-perf" plugin, I am using gradle version 2.2.1, and play service 11.6.0 then getting same error

**Comment by ronindev101** [comment]
@pauldemarco What changes did you make this work? I'm getting same exception when i add any firebase plugins.

**Comment by AppleEducate** [comment]
I am also having this issue with firebase plugins

**Comment by ronindev101** [comment]
@AppleEducate  Following combination worked for me.

  firebase_analytics: "^0.3.0"
  firebase_admob: ^0.5.0
  cloud_firestore: "^0.6.2"
  firebase_database: ^0.4.4

and 
 com.android.tools.build:gradle:3.0.1
'com.google.firebase:firebase-core:12.0.1'
'com.google.firebase:firebase-auth:12.0.1'
'com.google.firebase:firebase-database:12.0.1

Also, i need to invalidate all caches for some reason to work.
