### ISSUE TITLE
Flutter Build IPA not correctly setting entitlements

### ISSUE THREAD

**Issue by ajatprabha** [flutter/flutter#129075]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I'm currently experiencing an issue when building an IPA using Flutter where the entitlements are not being correctly included in the built IPA. More specifically, the `aps-environment` entitlement is missing.

This is the command I am using to build the IPA:

```shell
flutter build ipa --release --no-codesign --build-number=n --build-name=x.y.z
```

The `aps-environment` entitlement is correctly set in the "Capabilities" tab of the Xcode project settings when I enable "Push Notifications". It works fine when I build the archive using Xcode directly.

However, when I use the `flutter build ipa` command, the resulting IPA doesn't include the `aps-environment` entitlement.

I have also tried manually specifying the path to the entitlements file using the `FLUTTER_XCODE_CODE_SIGN_ENTITLEMENTS` environment variable so that it is directly used in the xcodebuild command, but the issue persists.

<details><summary>This is the command that Flutter runs:</summary>

```shell
/usr/bin/arch -arm64e xcrun xcodebuild -configuration Release
  VERBOSE_SCRIPT_LOGGING=YES -workspace Runner.xcworkspace -scheme Runner
  -sdk iphoneos -destination generic/platform=iOS
  CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGNING_IDENTITY=""
  SCRIPT_OUTPUT_STREAM_FILE=/var/folders/v_/3z5h46t965s2htdvsnvdjdzh0000gn/T/flutter_tools.YwAXEw/flutter_ios_build_temp_dirGIxoPD/pipe_to_stdout
  -resultBundlePath /var/folders/v_/3z5h46t965s2htdvsnvdjdzh0000gn/T/flutter_tools.YwAXEw/flutter_ios_build_temp_dirGIxoPD/temporary_xcresult_bundle
  -resultBundleVersion 3
  FLUTTER_SUPPRESS_ANALYTICS=true
  COMPILER_INDEX_STORE_ENABLE=NO
  CODE_SIGN_ENTITLEMENTS=Runner/Runner.entitlements
  -archivePath /Users/user/Workspace/venn/build/ios/archive/Runner archive
```

</details>

Steps to reproduce:

1. Create/Use a flutter project that uses `aps-environment` entitlement.
2. Create a Release archive from XCode, proceed to to distribute it on App Store Connect.
3. It shows the `aps-environment` entitlement
4. Build the archive using the following `flutter build ipa` command
5. Xcode doesn't detect the `aps-environment` entitlement for the IPA built using the Flutter command.

Please let me know if you need any further information. I appreciate your assistance on this issue.

### Expected results

The `aps-environment` entitlement should exist.

<details><summary>Screenshot</summary>

<img width="1112" alt="Screenshot 2023-06-18 at 2 14 48 PM" src="https://github.com/flutter/flutter/assets/11836668/3c128067-838d-4c86-a14a-7891d6644092">

</details>

### Actual results

The `aps-environment` entitlement does not exist.

<details><summary>Screenshot</summary>

<img width="1112" alt="Screenshot 2023-06-18 at 2 19 06 PM" src="https://github.com/flutter/flutter/assets/11836668/e7ad6e9f-3a43-4b00-8b48-0436067d82af">

</details>

### Code sample

N/A

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.3.1 22E772610a darwin-arm64, locale en-IN)
    • Flutter version 3.10.5 on channel stable at /Users/user/.flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (4 days ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Users/user/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9862592/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/user/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.79.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile)        • 326C2F3F-F4D3-415A-8D54-6B6B251BD5CE • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)                   • macos                                • darwin-arm64   • macOS 13.3.1 22E772610a darwin-arm64
    • Chrome (web)                      • chrome                               • web-javascript • Brave Browser 114.1.52.122

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by ajatprabha** [comment]
I'm able to build, if these flags are not added.

https://github.com/flutter/flutter/blob/c29b57067831cefb3e3364b0a998be7a32615ff3/packages/flutter_tools/lib/src/ios/mac.dart#L311-L319

What would be the suggested way to handle this?

**Comment by darshankawar** [comment]
@ajatprabha 
Check [this](https://github.com/flutter/flutter/issues/113977) similar / related issue and https://github.com/flutter/flutter/issues/113977#issuecomment-1315596412 to see if it helps in your case or not.

**Comment by techouse** [comment]
Looks like using `--no-codesigning` excludes the entitlements.

This is what I'm doing in my CI/CD:

- `flutter build ipa --release --no-codesign` to build an Xcode Archive
- use fastlane `match` to get my certificate and provisioning profile
- use fastlane `gym` to package it up into an IPA
- use fastlane `pilot` to upload to TestFlight

What's weird is that this works fine. But later I noticed that my APS and associated domains entitlements were missing from the uploaded bundle.

I did some digging and then found out that if I build the IPA using fastlane `gym` directly it complains that the priovisioning profile is missing the entitlements. The same error is reported when running `flutter build ipa --release`. So my provisioing profile is broken.

**Comment by techouse** [comment]
When using `flutter build ipa --release --no-codesign` the entitlements don't get preserved / added to the Xcode Archive. Here's how to fix it:

1. Build an unsigned Xcode Archive using `flutter build ipa --release --no-codesign`
2. Extract `ios/Flutter/Generated.xcconfig` from the Flutter build directory
3. Use Fastlane [update_code_signing_settings](https://docs.fastlane.tools/actions/update_code_signing_settings/) to set code signing to `manual` and set all your provisioning profiles and entitlements
4. Use Fastlane [gym](http://docs.fastlane.tools/actions/gym/) to build the IPA. Here set all your signing certificates and export provisioning profiles. Don't forget to specify the extacted `ios/Flutter/Generated.xcconfig`.
5. Use [pilot](http://docs.fastlane.tools/actions/pilot/) to upload to TestFlight
