### ISSUE TITLE
[image_picker] 0.8.9 compatibility issue 

### ISSUE THREAD

**Issue by zakblacki** [flutter/flutter#129093]
> Because image_picker >=0.8.9 depends on image_picker_platform_interface ^2.8.0 which doesn't match any versions, image_picker >=0.8.9 is forbidden.
> So, because project depends on image_picker ^0.8.9, version solving failed

```
environment:
  sdk: '>=3.0.3 <4.0.0'
```

`Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.19045.3086], locale en-US)
    • Flutter version 3.10.5 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (5 days ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\zakbl\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 34.0.0
    • ANDROID_HOME = C:\Users\zakbl\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Java\jdk-17\bin\java
    • Java version Java(TM) SE Runtime Environment (build 17.0.7+8-LTS-224)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code (version 1.79.2)
    • VS Code at C:\Users\zakbl\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.64.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 114.0.5735.134
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 114.0.1823.43

[√] Network resources
    • All expected network resources are available.

• No issues found!`

**Comment by stuartmorgan** [comment]
> • Pub download mirror https://pub.flutter-io.cn

`image_picker_platform_interface` 2.8.0 [definitely exists](https://pub.dev/packages/image_picker_platform_interface). If you are using a mirror that doesn't have it, you'll need to report the issue to the administrators of the mirror.
