### ISSUE TITLE
Documentation - codelabs - correction: replace the word "NavigationRail" with the word "SafeArea" in sentence

### ISSUE THREAD

**Issue by iugmali** [flutter/flutter#129086]
In [this section of the documentation for writing a new flutter app](https://codelabs.developers.google.com/codelabs/flutter-codelab-first#6), Filip Hracek (@filiph) wrote:

_"The second child of the Row is the Expanded widget. Expanded widgets are extremely useful in rows and columns—they let you express layouts where some children take only as much space as they need (**NavigationRail**, in this case) and other widgets should take as much of the remaining room as possible (Expanded, in this case). One way to think about Expanded widgets is that they are "greedy". If you want to get a better feel of the role of this widget, try wrapping the **NavigationRail** widget with another Expanded. The resulting layout looks something like this:"_

When trying to follow the instructions, I run into an error because Expanded becomes a child of SafeArea widget. The correct sentence is replacing the word NavigationRail with the word SafeArea.

**Comment by huycozy** [comment]
I think the author is referring to `NavigationRail`. But anyway welcome your issue to improve codelabs better with details :)

**Comment by iugmali** [comment]
> I think the author is referring to `NavigationRail`. But anyway welcome your issue to improve codelabs better with details :)
> 
> cc: @domesticmouse

If you wrap NavigationRail with the Expanded widget, the code is going to be:

```
class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Row(
        children: [
          SafeArea(
            child: Expanded(
              child: NavigationRail(
                extended: false,
                destinations: [
                  NavigationRailDestination(
                    icon: Icon(Icons.home),
                    label: Text('Home'),
                  ),
                  NavigationRailDestination(
                    icon: Icon(Icons.favorite),
                    label: Text('Favorites'),
                  ),
                ],
                selectedIndex: 0,
                onDestinationSelected: (value) {
                  print('selected: $value');
                },
              ),
            ),
          ),
          Expanded(
            child: Container(
              color: Theme.of(context).colorScheme.primaryContainer,
              child: GeneratorPage(),
            ),
          ),
        ],
      ),
    );
  }
}
```

It's going to throw an error, because it´s using Expanded as a child of SafeArea, but Expanded can only be a child of Column, Row, or Flex. The correct way is to wrap SafeArea with the Expanded widget, and the code is goint to be:

```
class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Row(
        children: [
          Expanded(
            child: SafeArea(
              child: NavigationRail(
                extended: false,
                destinations: [
                  NavigationRailDestination(
                    icon: Icon(Icons.home),
                    label: Text('Home'),
                  ),
                  NavigationRailDestination(
                    icon: Icon(Icons.favorite),
                    label: Text('Favorites'),
                  ),
                ],
                selectedIndex: 0,
                onDestinationSelected: (value) {
                  print('selected: $value');
                },
              ),
            ),
          ),
          Expanded(
            child: Container(
              color: Theme.of(context).colorScheme.primaryContainer,
              child: GeneratorPage(),
            ),
          ),
        ],
      ),
    );
  }
}
```

Then it will have the behavior described in the codelab.

**Comment by domesticmouse** [comment]
PTAL @filiph

**Comment by filiph** [comment]
Sorry for the late reply. Good find!

I'm torn on this. Although the `NavigationRail` _is_ wrapped with `SafeArea`, so it makes sense to mention it, it's also true that it's the `NavigationRail` that is the example of a child that "take[s] only as much space as [it] need[s]".

There's really no 100% answer to this, I'm afraid. I'd stay with `NavigationRail` since it's a good example of a widget that doesn't expand. But I'm also _this close_ to saying let's change it. Gah! Decisions decisions.

**Comment by iugmali** [comment]
I understand that it makes sense to mention NavigationRail. 

Maybe a simple change, replacing "_try wrapping the NavigationRail widget with another Expanded_" for "_try wrapping the NavigationRail widget with another Expanded **instead of wrapping with SafeArea**_" will prevent running into error messages, since Expanded cannot be a child of SafeArea.

**Comment by filiph** [comment]
Ohh! Sorry, I'm an idiot. I stopped reading that paragraph in the middle and didn't realize there's more to it.

You're absolutely right!

I have made the change. @domesticmouse, would you please politely ask the robots to rebuild the codelab again?

**Comment by domesticmouse** [comment]
Fix is in flight.

Googlers: cl/563941861
