### ISSUE TITLE
crash in debug mode 

### ISSUE THREAD

**Issue by 015-Michelle** [flutter/flutter#129155]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1.uninstall my app
2.run app in android studio
3.input id/pwd , then successful login 
then crash : 

F/libc    (  994): Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x7a08f00000 in tid 1934 (1.ui), pid 994 (xxx.xx)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'HONOR/YAL-AL10/HWYAL:10/HUAWEIYAL-AL10/10.1.0.162C00:user/release-keys'
Revision: '0'
ABI: 'arm64'
SYSVMTYPE: Maple
APPVMTYPE: Art
Timestamp: 2023-06-20 15:01:00+0800
pid: 994, tid: 1934, name: 1.ui  >>> com.xxx.xxx <<<
uid: 11373
signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x7a08f00000
    x0  00000000ffbe8410  x1  0000000000000000  x2  0000000000000000  x3  0000007a08f00000
    x4  0000007a08e6146b  x5  0000000000000038  x6  0000007a06447b41  x7  00000000000008c9
    x8  0000000000000007  x9  0000000000000000  x10 0000007baad13330  x11 000000000005e000
    x12 000000000005e000  x13 0000000000000002  x14 0000000000000000  x15 0000007b5214e450
    x16 0000007b52077000  x17 0000007a079c0e11  x18 0000007b48f9c000  x19 0000007b56189800
    x20 0000007baad13398  x21 0000007baad133b8  x22 0000007a00008081  x23 0000007baad134b8
    x24 0000007a07778291  x25 0000007a08cf40b4  x26 0000007b56189800  x27 0000007a07778270
    x28 000000080000007a  x29 0000007b5214e470
    sp  0000007b52076000  lr  0000007b1ae82bec  pc  0000007b1af296e8
backtrace:
      #00 pc 00000000000a96e8  [anon:dart-code]

### Expected results

don't crash 

### Actual results

It can crash during the first run time in debug mode , and sometimes also crash if it runs long time.

I'm not sure how to locate the problem because of the error log.

flutter 3.10.2
dart 3.0.2
harmonyOS 3.0.0

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

F/libc    (  994): Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x7a08f00000 in tid 1934 (1.ui), pid 994 (xxx.xx)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'HONOR/YAL-AL10/HWYAL:10/HUAWEIYAL-AL10/10.1.0.162C00:user/release-keys'
Revision: '0'
ABI: 'arm64'
SYSVMTYPE: Maple
APPVMTYPE: Art
Timestamp: 2023-06-20 15:01:00+0800
pid: 994, tid: 1934, name: 1.ui  >>> com.xxx.xxx <<<
uid: 11373
signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x7a08f00000
    x0  00000000ffbe8410  x1  0000000000000000  x2  0000000000000000  x3  0000007a08f00000
    x4  0000007a08e6146b  x5  0000000000000038  x6  0000007a06447b41  x7  00000000000008c9
    x8  0000000000000007  x9  0000000000000000  x10 0000007baad13330  x11 000000000005e000
    x12 000000000005e000  x13 0000000000000002  x14 0000000000000000  x15 0000007b5214e450
    x16 0000007b52077000  x17 0000007a079c0e11  x18 0000007b48f9c000  x19 0000007b56189800
    x20 0000007baad13398  x21 0000007baad133b8  x22 0000007a00008081  x23 0000007baad134b8
    x24 0000007a07778291  x25 0000007a08cf40b4  x26 0000007b56189800  x27 0000007a07778270
    x28 000000080000007a  x29 0000007b5214e470
    sp  0000007b52076000  lr  0000007b1ae82bec  pc  0000007b1af296e8
backtrace:
      #00 pc 00000000000a96e8  [anon:dart-code]

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.2, on macOS 13.3.1 22E261 darwin-arm64 (Rosetta), locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.66.2)
[✓] Connected device (3 available)
[!] Network resources             
    ✗ An HTTP error occurred while checking "https://github.com/": Connection closed before full header was received

! Doctor found issues in 1 category.

</details>

**Comment by dam-ease** [comment]
Hi @015-Michelle 
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly.
More specifically, please provide the information indicated below:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of `flutter doctor -v`

Kindly provide more information on this issue.
