### ISSUE TITLE
[CP] Fix an issue that only one PlatformView can be clipped

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#129185]
### Issue Link

https://github.com/flutter/flutter/issues/125620

### Commit Hash

727b441

### Target

beta

### PR Link

https://github.com/flutter/engine/pull/43007

### Changelog Description

Fixes an issue on iOS where only one PlatformView can be clipped.

### Impacted Users

Some Flutter apps show and clip multiple PlatformViews in a single page.

### Impact Description

On iOS, PlatformViews are not clipped correctly, sometimes drawn outside of parent widgets. 

See below screenshot (copied from https://github.com/flutter/flutter/issues/127717), the intended behavior is that both PlatformView should be shown in circles. 

![image](https://github.com/flutter/flutter/assets/3756895/30d17f73-7595-435f-b3a9-451887336634)

### Workaround

No

### Risk

low

### Test Coverage

yes

### Validation Steps

Repro steps can be found in https://github.com/flutter/flutter/issues/127717

**Comment by itsjustkevin** [comment]
@zanderso could you take a look?

**Comment by zanderso** [comment]
For a beta CP to 3.12 this seems fine to me, but I'm noticing that there was a review requested from @stuartmorgan on the original PR, and I'm wondering if he has any thoughts.

**Comment by XilaiZhang** [comment]
Thanks for reviewing everyone!
