### ISSUE TITLE
Expandable `DataRow`

### ISSUE THREAD

**Issue by FMorschel** [flutter/flutter#129164]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I have a `DataTable` where some info is grouped to make my screen cleaner and less cramped. But whenever my users want to see the full data they have to go to another page. I would like an option on `DataRow` where I could expand it with a button.

### Proposal

I think this will be easily done once #21594 is completed.

Here is an example of what I meant by expandable `DataRow`:

https://www.gyrocode.com/articles/jquery-datatables-how-to-expand-collapse-all-child-rows/:

https://github.com/flutter/flutter/assets/52160996/4354b870-fa2f-4155-aced-3831e7ba347d

**Comment by dam-ease** [comment]
Hi @FMorschel. There seems to be a package that offers this feature https://pub.dev/packages/flutter_expandable_table/example. Can you confirm this fits into your use case??

**Comment by annymosse** [comment]
@dam-ease I try it last week it doesn't work, it have the following:
- fixed column width composed by containers (doesn't provide flexibility for dynamic width content).
-  poor API.
- the `Expandable` feature which exist in the HTML alternative can't produced by this package.
