### ISSUE TITLE
[Impeller] Correct way of examining Impeller performance issues?

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#129118]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

For triage: I guess this can be categorized as "proposal to add some doc" or "proposal to add some features for easy debugging".

Background: I am experimenting Impeller and want to debug and fix the performance problems of my real app, and probably submit PRs if the slowness is from Impeller's code itself. However, I need to firstly know the best-practice of examining its performance issues.

What I have searched: I have checked https://docs.flutter.dev/perf/impeller and https://github.com/flutter/engine/blob/main/impeller/docs/read_frame_captures.md, but I am not sure whether that's the correct thing to look at - for example, it may be bottlenecked by CPU work. The impeller says it is "Instrumentable", so I am not sure whether I can easily read a flamechart or whatever, with all tags clearly showing which part takes how much time (like "enhanced tracing" for widgets). Therefore, I am creating this issue, hoping to see how you (Impeller developers) debug performance issues in everyday life. I have also guessed I could use standard CPU profilers, but given that there are the helpful "enhanced tracing" feature for Flutter framework, I guess there could also been something like this for Impeller and it is just I do not know that yet.

I am happy to make a PR, either to add doc (after I know and play with the correct approach), or to add some features for easy performance problem debugging.

By the way, a side question: Where should I find the doc of Impeller? Currently I only found https://github.com/flutter/engine/tree/main/impeller and https://github.com/flutter/engine/tree/main/impeller/docs. And https://www.youtube.com/watch?v=vd5NqS01rlA video.

### Proposal

see above

**Comment by fzyzcjy** [comment]
Update: Thanks @jonahwilliams for replying on Discord. Quote the reply here for anyone needed:

> I would start by looking at devtools to verify that the performance issue is on the Raster thread. Then you can either run the Xcode CPU profilter to see what is taking so long on the raster thread. Though if the timeline traces show a lot of time in waitForNextDrawable, then the issue is usually on the GPU and you should instead look at frame captures

**Comment by darshankawar** [comment]
@fzyzcjy 
Does above comment help to answer your original question of ways to examine impeller perforrmance issues ?

**Comment by fzyzcjy** [comment]
@darshankawar Yes, I will firstly try that path. I am happy to contribute some doc if needed.

**Comment by fzyzcjy** [comment]
Somehow related: An example of examining impeller slowness https://github.com/flutter/flutter/issues/129149#issuecomment-1598694268

**Comment by darshankawar** [comment]
I added `wait` label based on your previous comment or you can also close this until you complete your findings per your comment and reopen if required.

**Comment by fzyzcjy** [comment]
I think this can be triaged as: feature / improvement of doc

**Comment by chinmaygarde** [comment]
We use multiple profilers to analyze performance issues. Stuff like Xcode and Instruments (in which we label all GPU resources) and RenderDoc. Profiling workflows are documented separately in the docs folder but I am sure we can add to these. As far as one "correct" way to profile everything, I don't think there is one. It is workload and platform dependent. If the existing docs are insufficient, let us know. For specific work items related to documentation, there is a "Documentation" section in https://github.com/orgs/flutter/projects/21 that we can prioritize.

**Comment by fzyzcjy** [comment]
Thank you!
