### ISSUE TITLE
[Impeller] Differentiate two `EncodeCommandsInReactor` with the same name.

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#129149]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

When previewing Impeller (on Android, just want to see its performance), I see slowness like the screenshot below. However, searching `EncodeCommandsInReactor` yields *two* different classes. Thus I wish I could know which one is the real one.

![image](https://github.com/flutter/flutter/assets/5236035/a24a7631-2749-4919-9765-3f76a642beae)

### Proposal

-

**Comment by jonahwilliams** [comment]
The timeline API isn't really meant for debugging like this. The render passes may or may not have useful names, but you won't know what in particular is taking a long time unless you use a CPU profiler. There is one in android studio but that requires symbols

**Comment by fzyzcjy** [comment]
@jonahwilliams I see, thanks! I am going to use the profiler (as you suggested earlier), and just raised this issue/PR because during looking at the trace I thought it would be easier for future people.

**Comment by fzyzcjy** [comment]
@jonahwilliams As you warned, it requires symbols. When using the standard toolchain (stable flutter), it only yields `libflutter.so+0x.....`. The DWARF mode (works well for arm, https://android.googlesource.com/platform/system/extras/+/master/simpleperf/doc/README.md#comparing-dwarf-based-and-stack-frame-based-call-graphs) also seem to need debug information. Thus, I wonder how do you get symbols for libflutter.so? My guesses:

1. Download symbols from https://github.com/flutter/flutter/issues/101100, and magically insert that libflutter.so instead of the traditional one into my APK.
2. Or, use a custom built engine with symbols? But I do not have enough memory and CPU on my computer to do LTO, and last time I have tried a profile built without LTO - it was terribly slow in the rasterizer part.

Thanks!

**Comment by jonahwilliams** [comment]
I generally use a local engine build. I would disable LTO, it only has a marginal performance impact and mostly exists to reduce code size (which is irrelevant if you build with symbols). Something like `./tools/gn --android --android-cpu=arm64 --no-stripped --no-lto --no-goma`

Then you need to also disable Gradle symbol stripping:  https://github.com/flutter/flutter/wiki/Crashes#android-local-engine-builds

**Comment by fzyzcjy** [comment]
@jonahwilliams Get it, thank you and I will have a try!

**Comment by fzyzcjy** [comment]
@jonahwilliams Thank you for the guidance, I successfully ran Android Studio profiler. For example, a simple scrolling of a page yields jank:

![image](https://github.com/flutter/flutter/assets/5236035/2df1b014-1f78-42ef-ac72-1ba73ba163d5)
![image](https://github.com/flutter/flutter/assets/5236035/09044315-1cf8-4416-9e62-a9ba5a0692a7)

The profiling can yield similar results:

![image](https://github.com/flutter/flutter/assets/5236035/d956c05c-ad0c-4560-bd6f-d555a90f7311)
![image](https://github.com/flutter/flutter/assets/5236035/61e76c94-0d19-4d64-80e3-2f8655287c07)

**Comment by huycozy** [comment]
Thanks for the update, @fzyzcjy. Looks like I can see two `EncodeCommand..` from your CPU profiling on Android Studio though it's not very clear. Keeping this issue open and labeling it for further discussion.

**Comment by chinmaygarde** [comment]
This isn't something we are going to attempt. To differentiate pass workloads, you'd need to use a GPU profiler.
