### ISSUE TITLE
I have tried may time to get download directory's path through path provider and it shows: getDownloadsPath is not supported on Android

### ISSUE THREAD

**Issue by dishankgajera** [flutter/flutter#129181]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I have tried may time to get download directory's path through path provider and it shows: `getDownloadsPath()` is not supported on Android

E/flutter (23814): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unsupported operation: getDownloadsPath is not supported on Android
E/flutter (23814): #0      PathProviderAndroid.getDownloadsPath (package:path_provider_android/path_provider_android.dart:85:5)
E/flutter (23814): #1      getDownloadsDirectory (package:path_provider/path_provider.dart:201:40)
E/flutter (23814): #2      DownloadNetworkFileController.downloadImage.<anonymous closure> (package:picsy_mobile_app/package/image_downloader/image_downloader.dart:62:43)

### Expected results

Get download folder's path

### Actual results

E/flutter (23814): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unsupported operation: getDownloadsPath is not supported on Android
E/flutter (23814): #0      PathProviderAndroid.getDownloadsPath (package:path_provider_android/path_provider_android.dart:85:5)
E/flutter (23814): #1      getDownloadsDirectory (package:path_provider/path_provider.dart:201:40)
E/flutter (23814): #2      DownloadNetworkFileController.downloadImage.<anonymous closure> (package:picsy_mobile_app/package/image_downloader/image_downloader.dart:62:43)

### Code sample

    final appDir = await pathProvider.getDownloadsDirectory();

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel unknown, 3.7.7, on Microsoft Windows [Version 10.0.22621.1848], locale en-US)
    ! Flutter version 3.7.7 on channel unknown at C:\src\flutter
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[!] Android Studio (version 2021.2)
    X Unable to determine bundled Java version.
[√] Android Studio (version 2022.2)
[√] VS Code (version 1.79.0)
[√] Connected device (4 available)
[√] HTTP Host Availability

! Doctor found issues in 3 categories.

```

</details>

**Comment by huycozy** [comment]
Hi @dishankgajera 
It's a correct error message. `getDownloadsPath` is not supported currently. Please see [Supported platforms and paths](https://pub.dev/packages/path_provider#supported-platforms-and-paths).

Closing this issue as it's not a plugin bug.

**Comment by nik007frontbit** [comment]
so how i can now get the download dictinory path
