### ISSUE TITLE
[image_picker][android] App restarts 

### ISSUE THREAD

**Issue by Soliardi-Chyngyz** [flutter/flutter#129153]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Good day
I don’t understand why you are closing topics, because you don’t solve the problem, and the retrieveLostData () method is far from a solution. The problem remains relevant even in the latest version 0.8.9

The action scenario is as follows, there is a flow on 3 pages and each of them calls imagePicker.pickImage(source.Camera) 2-3 times...
everything is as usual,
the first round is all right, but starting from the second, the application starts to restart, it really feels like the memory is being overloaded and the device is trying to throw off this load. So the question is to the author and everyone, we need to find a way to clear the memory when returning from the .pickImage () method

The problem inside the package is unambiguous and it is not yet clear where exactly, ideally you need a method like
await ImagePicker().clean();

### Expected results

no restarts

### Actual results

app restarts on pickImage

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@Soliardi-Chyngyz 
Can you provide us a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with steps to replicate that shows the reported behavior ? Also provide the device details on which the said behavior occurs.

**Comment by stuartmorgan** [comment]
Please see https://github.com/flutter/flutter/issues/48016#issuecomment-971918009

Closing as a duplicate.
