### ISSUE TITLE
can not link ios simulator or ios device

### ISSUE THREAD

**Issue by yeniugo** [flutter/flutter#129154]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. vs code with flutter plugin
2. debug with a app with a new app
3. the app can install in simulator or ios device,but it can not lauch app,and the error is Error connecting to the service protocol: failed to connect to http://xxxxxxx:xxxxxx/xxxxxx/

### Expected results

the app can install in simulator or ios device,but it can not lauch app,and the error is Error connecting to the service protocol: failed to connect to http://xxxxxxx:xxxxxx/xxxxxx/

### Actual results

the app can install in simulator or ios device,but it can not lauch app,and the error is Error connecting to the service protocol: failed to connect to http://xxxxxxx:xxxxxx/xxxxxx/

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
Waiting for xxxx iPhone to connect...
Launching lib/main.dart on xxxx iPhone in debug mode...
main.dart:1
Automatically signing iOS for device deployment using specified development team in Xcode project: xxxx
Xcode build done.                                           39.7s
(lldb) 2023-06-20 14:53:28.778252+0800 Runner[82154:7937086] [VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(35)] Using the Impeller rendering backend.
Warning: Unable to create restoration in progress marker file
fopen failed for data file: errno = 2 (No such file or directory)
Errors found! Invalidating cache...
Error connecting to the service protocol: failed to connect to http://192.168.100.123:59656/JH7yFYj4Sv4=/
Exited
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.4, on macOS 13.4 22F66 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.79.0)
[!] Proxy Configuration
    ! NO_PROXY is not set
[✓] Connected device (4 available)
    ! Error: (null) needs to connect to determine its availability. Check the connection between the device and its companion iPhone, and the connection between the iPhone and Xcode. Both devices may also need to be
      restarted and unlocked. (code 1)
[✓] Network resources
```

</details>

**Comment by huycozy** [comment]
Hi @yeniugo 
You should narrow down the issue by checking if it's caused by 3rd party plugins/packages or your implementation. In case you have a clue and can reproduce this issue consistently, please provide a sample code along with output of `flutter run -v` so we can verify this issue properly. Thanks!
