### ISSUE TITLE
ci.yaml validation is stuck as pending on all PRs

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#129134]
All recent PRs are not receiving any LUCI checks on them:

* https://github.com/flutter/flutter/pull/129125
* https://github.com/flutter/flutter/pull/129130

**Comment by CaseyHillers** [comment]
github-webhook-subscription is failing with:

```
Failed to process Instance of 'PushMessage'. (500) Null check operator used on a null value
#0      GitHub.request (package:github/src/common/github.dart:372:13)
#1      PaginationHelper.fetchStreamed (package:github/src/common/util/pagination.dart:38:33)
<asynchronous suspension>
#2      PaginationHelper.jsonObjects (package:github/src/common/util/pagination.dart:95:5)
<asynchronous suspension>
```

I'm surprised there is nothing in g/flutter-infra-alerts

**Comment by CaseyHillers** [comment]
I tried to rollback to the previous version, but I lack permissions

**Comment by CaseyHillers** [comment]
I sent https://github.com/SpinlockLabs/github.dart/pull/377 to the upstream package to make the failing field non-nullable. In that case, it should fail earlier instead of when making requests.

**Comment by CaseyHillers** [comment]
Lowering this from P0 -> P2. Today's rollout has fixed the issue. Ideally, https://github.com/flutter/flutter/issues/129138 needs to be fixed so teams outside the US aren't blocked a whole day on a bad rollout.

**Comment by jonahwilliams** [comment]
This is still happening for me: https://github.com/flutter/engine/pull/43014

**Comment by ricardoamador** [comment]
@jonahwilliams did you rerun it because it in your PR.

**Comment by jonahwilliams** [comment]
I did not. Is the validation just significantly delayed

**Comment by ricardoamador** [comment]
Today's roll out did not fix the issue. I am investigating as there are still error messages for this issue happening all over the logs.

**Comment by ricardoamador** [comment]
It does. I am testing the fix now. It just so happens that your request went to the old instance. I will expand the traffic to the test instance to 100% as it looks like it is working.

**Comment by ditman** [comment]
@ricardoamador this is affecting our rollers in flutter/packages as well, a couple of examples:

* https://github.com/flutter/packages/pull/4270
* https://github.com/flutter/packages/pull/4269

**Comment by ricardoamador** [comment]
Yeah it looks like someone deployed a new version over the fixed version and re-introduced the issue again.

**Comment by ditman** [comment]
Thanks for taking a look, the check has succeeded in my manual roll attempt!

**Comment by ricardoamador** [comment]
Yeah no problem. I shifted traffic back which seems to have unstuck it.
