### ISSUE TITLE
[cocoon] flutter-infra team should be authorized to migrate traffic of flutter-dashboard

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#129138]
Oncalls need to be able to quickly rollback changes. To do that, using the appengine "split traffic" functionality is required.

**Comment by CaseyHillers** [comment]
\cc @drewroengoogle do you know how LatchKey can be updated to enable this permission, but not other write permissions, like deploying new versions?

**Comment by drewroengoogle** [comment]
I agree that we should be able to split traffic. Will open an internal CL to address this

**Comment by drewroengoogle** [comment]
It looks like we need the [appengine.serviceAdmin](https://cloud.google.com/iam/docs/understanding-roles#appengine.serviceAdmin) role:

```
Read-only access to all application configuration and settings.

Write access to module-level and version-level settings. Cannot deploy a new version.
```

**Comment by drewroengoogle** [comment]
The engprod team (and oncall) has the ability to migrate traffic between different versions now!
