### ISSUE TITLE
[macos] FlutterInputs and FlutterOutputs contains duplicates

### ISSUE THREAD

**Issue by vixez** [flutter/flutter#129126]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a project with multiple packages
2. Archive it for MacOS using XCode 

### Expected results

The archiving is succesful.

### Actual results

The build fails with the following error:
```
[ +264 ms] error: Multiple commands produce '/Users/glennruysschaert/Code/get-driven-flutter-cms/build/macos/Build/Products/Release/App.framework/Versions/A/Resources/flutter_assets/packages/gd_ui/lib/assets/lottie/chevron.json'
[        ]     note: That command depends on command in Target 'Flutter Assemble' (project 'Runner'): script phase “Run Script”
[        ]     note: That command depends on command in Target 'Flutter Assemble' (project 'Runner'): script phase “Run Script”
[        ] error: Multiple commands produce
'/Users/glennruysschaert/Code/get-driven-flutter-cms/build/macos/Build/Products/Release/App.framework/Versions/A/Resources/flutter_assets/packages/gd_ui/lib/assets/lottie/loading_dotted_spinner.json'
[        ]     note: That command depends on command in Target 'Flutter Assemble' (project 'Runner'): script phase “Run Script”
[        ]     note: That command depends on command in Target 'Flutter Assemble' (project 'Runner'): script phase “Run Script”
[        ] error: Multiple commands produce
'/Users/glennruysschaert/Code/get-driven-flutter-cms/build/macos/Build/Products/Release/App.framework/Versions/A/Resources/flutter_assets/packages/gd_ui/lib/assets/lottie/loading_overlay.json'
[        ]     note: That command depends on command in Target 'Flutter Assemble' (project 'Runner'): script phase “Run Script”
[        ]     note: That command depends on command in Target 'Flutter Assemble' (project 'Runner'): script phase “Run Script”
[   +8 ms] error: Multiple commands produce
'/Users/glennruysschaert/Code/get-driven-flutter-cms/build/macos/Build/Products/Release/App.framework/Versions/A/Resources/flutter_assets/packages/gd_ui/lib/assets/lottie/loading_spinner.json'
[        ]     note: That command depends on command in Target 'Flutter Assemble' (project 'Runner'): script phase “Run Script”
[        ]     note: That command depends on command in Target 'Flutter Assemble' (project 'Runner'): script phase “Run Script”
```

When I check `FlutterInputs.xcfilelist` and `FlutterOutputs.xcfilelist` I can see the mentioned files are there indeed multiple times, but with an extra `/`. Is this what causes this error?

Here you can see an example, right after `assets` you can see a single and double forward slash.

`/Users/glennruysschaert/Code/get-driven-flutter-cms/build/macos/Build/Products/Release/App.framework/Versions/A/Resources/flutter_assets/packages/gd_ui/lib/assets/lottie/chevron.json
`
and 
`/Users/glennruysschaert/Code/get-driven-flutter-cms/build/macos/Build/Products/Release/App.framework/Versions/A/Resources/flutter_assets/packages/gd_ui/lib/assets//lottie/chevron.json`

I tried removing the duplicates and archiving again, but the `xcfilelist` gets regenerated so that didn't help.

### Code sample

/

### Logs

<details><summary>Logs</summary>

https://pastebin.com/ftFk5pZd

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.10.5, on macOS 13.2.1 22D68 darwin-x64, locale en-GB)
    • Flutter version 3.10.5 on channel stable at /Users/glennruysschaert/development/flutter
    ! Warning: `dart` on your path resolves to /usr/local/Cellar/dart/2.18.0/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/glennruysschaert/development/flutter. Consider adding
      /Users/glennruysschaert/development/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (6 days ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/glennruysschaert/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/glennruysschaert/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.79.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.2.1 22D68 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.133

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by huycozy** [comment]
Hi @vixez 
It seems you are using [lottie](https://pub.dev/packages/lottie), right? Can you try removing that package along with its usage/assets and retry?

**Comment by vixez** [comment]
@huycozy 
Hello, 

When I remove the assets from the error (keeping the Lottie package), the build succeeds.
This error only occurs in Xcode when archiving with the assets.

When I run this command in terminal, without removing the assets, the build succeeds.

`flutter build macos --release -t lib/main-cms_production_store.dart --obfuscate --split-debug-info=build/symbols --no-tree-shake-icons -v`

**Comment by vixez** [comment]
@huycozy 
When I remove `FlutterInputs.xcfilelist` and `FlutterOutputs.xcfilelist` from the `Run script` under `Input File Lists` and `Output File Lists`, with the assets still there, the archive succeeds.

**Comment by huycozy** [comment]
Thanks for your update. I also tried adding a Lottie asset file to new Flutter project, then building/archiving but it's succeeded. And asset file is listed in `FlutterInputs.xcfilelist` and `FlutterOutputs.xcfilelist` but is not duplicated. 

Can you try `clean` and `archive` again?

>/Users/glennruysschaert/Code/get-driven-flutter-cms/build/macos/Build/Products/Release/App.framework/Versions/A/Resources/flutter_assets/packages/gd_ui/lib/assets/lottie/chevron.json

Also, I took a look at this log, it seems you are using assets from another package (`gd_ui`) inside project, right? Can you share project structure?
