### ISSUE TITLE
[cocoon] GitHub webhook failures should result in g/flutter-infra-alerts emails

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#129135]
The PubSub subscription should be configured to notify the oncall when the error rate is above normal (i.e. more than 5 requests a minute).

See https://github.com/flutter/flutter/issues/129134 which was manually triaged

**Comment by keyonghan** [comment]
Alert should have been configured to sent to the gardener, but the threshold may need an adjustment.
@ricardoamador could you confirm if you got any notification?

**Comment by ricardoamador** [comment]
No I do not see any alerts. I see a bunch of flex failure alerts but nothing specific to pubsub.

**Comment by ricardoamador** [comment]
Okay I think this has been happening for a while and I did not look far back enough. I just rolled out a fix for https://github.com/flutter/flutter/issues/129134 and I received an email for the alert to the github-webhook being resolved.

**Comment by ricardoamador** [comment]
This is resolved.
