### ISSUE TITLE
The cached Flutter version is causing a parse failure in version reading

### ISSUE THREAD

**Issue by whesse** [flutter/flutter#129127]
Since the change #124558, cache flutter version to disk, running flutter update-packages is causing an error

The cached version seems to be handled in a place where the output of a git describe is expected,
and that output would additionally have a partial commit hash at the end. The regexp parsing expects it to be there.
This error is in [flutter]/packages/flutter_tools/lib/src/version.dart:990.

I'm not sure if this is causing other problems or not.  I am running tests in a checkout of framework with engine.version overwritten by a monorepo commit hash, and a custom FLUTTER_STORAGE_BASE_URL

/src/flutter$ bin/flutter update-packages -v
[  +13 ms] Could not interpret results of "git describe": 3.12.0-4.0.pre.114

but

/src/flutter$ git describe --match *.*.* --long --tags HEAD
3.12.0-3.0.pre-114-g323c296922

I am also uncertain where the 3.12.0-4.0 version number is coming from, since I don't see the number 4 on git or anywhere
in files called "version" that are checked in.

**Comment by whesse** [comment]
This may also be the cause of the current failure on tool_tests: https://ci.chromium.org/ui/p/flutter/builders/luci.flutter.prod/Linux%20tool_tests_commands

**Comment by christopherfujino** [comment]
Investigating now

**Comment by christopherfujino** [comment]
Oh, look like this was the fix? https://github.com/flutter/flutter/pull/129131/files

**Comment by whesse** [comment]
It looks likely.  The problem disappeared after that fix.
