### ISSUE TITLE
(With fix included) "Crashes - Android Local Engine Builds" does not work, it should also disable stripping for other folders

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#129166]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

When following https://github.com/flutter/flutter/issues/129149#issuecomment-1598164928 to get symbols, I failed and the symbols are still stripped. Then I realized it is because of the code section in https://github.com/flutter/flutter/wiki/Crashes#android-local-engine-builds:

    packagingOptions{
        doNotStrip "*/armeabi/*.so"
        doNotStrip "*/armeabi-v7a/*.so"
        doNotStrip "*/x86/*.so"
    }

forgets the arm 64 architecture, i.e. the `arm64-v8a` folder. Therefore, one way is to add a new line for that, another way is to simply strip everything:

    packagingOptions{
        doNotStrip "**/*.so"
    }

### Expected results

-

### Actual results

-

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by jonahwilliams** [comment]
I can just make this change real quick, thanks for the heads up!

**Comment by jonahwilliams** [comment]
Closing as fixed

**Comment by fzyzcjy** [comment]
You are welcome!
