### ISSUE TITLE
switch case gives different results in debug and release mode

### ISSUE THREAD

**Issue by niksen75** [flutter/flutter#129277]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Found a similar issue which has been closed, but the issue persists #125625 when switching on an enum.

Steps to reproduce: call MyString(MyEnum.b) returns 'b' in debug mode, but 'a' in release mode

### Expected results

MyString(MyEnum.a) returns 'a' as expected

### Actual results

however, MyString(MyEnum.b) and MyString(MyEnum.c) also returns 'a' - not as expected

### Code sample

<details><summary>Code sample</summary>

```dart
enum MyEnum {
  a, 
  b, 
  c
}

String MyString(MyEnum value) {
switch (value) 
  case MyEnum.a:
    return "a";
  case MyEnum.b:
    return "b";
  case MyEnum.c:
    return "c";
  default:
    return 'default';
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4 22F66 darwin-x64, locale en-GB)
    • Flutter version 3.10.5 on channel stable at /Users/nickyovergaardpedersen/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (8 days ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.79.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 00008110-001E38E63EE2401E • ios            • iOS 16.5 20F66
    • macOS (desktop)            • macos                     • darwin-x64     • macOS 13.4 22F66 darwin-x64
    • Chrome (web)               • chrome                    • web-javascript • Google Chrome 114.0.5735.133

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by TahaTesser** [comment]
Hi @niksen75 
The fix for https://github.com/flutter/flutter/issues/125625 is probably available on the stable channel which uses ` Dart version 3.0.5`


As with the issue above,  just like the other one. Please file an issue in the Dart SDK repository https://github.com/dart-lang/sdk,

**Comment by niksen75** [comment]
Thanks. Have submitted an issue in the Dart SDK repo https://github.com/dart-lang/sdk/issues/52750
