### ISSUE TITLE
How do I get the device's physicalSize in initState() ?

### ISSUE THREAD

**Issue by TheCarpetMerchant** [flutter/flutter#129201]
Before Flutter 3.10, you had `WidgetsBinding.instance.window.physicalSize.aspectRatio`, which was accessible in `initState()`.
But now that this is being deprecated, I don't know how to get this. `View.of(context)` requires a valid context.

**Comment by huycozy** [comment]
Can you please be more specific on this? I haven't seen a deprecated warning with [aspectRatio](https://github.com/flutter/engine/blob/cfbd3652532d3e67d6bf9468857e13dd941d1db2/lib/ui/geometry.dart#L400) and its usage:

![Screenshot 2023-06-21 at 14 44 28](https://github.com/flutter/flutter/assets/104349824/83360f92-418c-46bb-a144-7c468cb1a560)

**Comment by TheCarpetMerchant** [comment]
The deprecation is on `window`, not `aspectRatio`.

**Comment by maRci002** [comment]
You can use this inside `initState`:
```dart
final mediaQuery = (context.getElementForInheritedWidgetOfExactType<MediaQuery>()!.widget as MediaQuery).data;
final physicalSize = mediaQuery.size * mediaQuery.devicePixelRatio;
```

Or if you don't have any `BuildContext`:
```dart
final physicalSize = PlatformDispatcher.instance.views.first.physicalSize;

final largestPhysicalSize = PlatformDispatcher.instance.views
    .map((v) => v.physicalSize)
    .reduce((curr, next) => curr.width * curr.height > next.width * next.height ? curr : next);
```

**Comment by huycozy** [comment]
@TheCarpetMerchant  Per the suggestion on this, you can try using `PlatformDispatcher` instead (as @maRci002's sample code above)

https://github.com/flutter/flutter/blob/ae1e6f70d947ec389761c03363c2beefeddd9112/packages/flutter/lib/src/foundation/binding.dart#L216-L221

Closing as solved. Thanks!

**Comment by TheCarpetMerchant** [comment]
Okay but where in PlatformDispatcher is this information ?

**Comment by TheCarpetMerchant** [comment]
@maRci002 Thank you !
