### ISSUE TITLE
Feature to be added

### ISSUE THREAD

**Issue by amirmhrzan123** [flutter/flutter#129237]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

The video player doesnt support BT2020 colorspace videos. The videos are discolored when it is played iin mobile
Try url below.
https://rcwl-prod.s3.eu-west-2.amazonaws.com/files/15d8fd20-80fe-4829-9c28-8766ae5bbd25/PRE_AND_POST_NATAL/FINAL_FULL_BODY_PREG_WORKOUT_WITH_HILS.mp4

### Proposal

I dont have a proposal for this. i am having issue playiing this bt2020 of videos due to discoloration. Please can you suggest anythying.

**Comment by huycozy** [comment]
Closing this issue in favor of https://github.com/flutter/flutter/issues/129238. Please follow up on it for further updates.
