### ISSUE TITLE
Support for rendering equations

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#12927]
We heard this requirement from an internal team; creating an issue here to start a discussion on the best way to support this.

They would like to use Latex(like) markup to render equations in a Flutter app.

They considered using WebView support which will be coming up however they are concerned about having multiple webviews active in the app at the same time. Their UI contains several tiles as a preview list for articles, each tile having some text snippet which might contain formulae.

**Comment by eseidelGoogle** [comment]
Latex equations are typically static.  This feels like something that could be done well from some sort of shared library (C++, etc.) which took latex as a source and spit out rendered images.  One could pretty easily write a Flutter plugin around such a library.

**Comment by eseidelGoogle** [comment]
I would love to learn more about the desires/requirements here (privately or otherwise), as I'm not aware of any blockers from producing a latex-rendering plugin for Flutter today, even one which integrates into layout with other Flutter widgets.   Having https://github.com/flutter/flutter/issues/7053 resolved would likely remove some boilerplate from doing so, but shouldn't be a blocker.

**Comment by mehmetf** [comment]
Sample Libraries that can be used for a plugin provided that conversion to images is good enough:

Java Library for converting Latex to SVG: https://github.com/opencollab/jlatexmath
For iOS: https://github.com/kostub/iosMath

**Comment by Hixie** [comment]
I don't expect the Flutter team to provide a LaTeX rendering package. I don't think anything is in the way of someone doing that, though, just like a charting library was created for Flutter or how an SVG library is being written.

I'm going to close this issue on the basis that it doesn't represent something we need to do, but if anyone ever tries to do this and runs into any trouble, please don't hesitate to reach out or file specific bugs.

**Comment by shahzadakram67** [comment]
Please check this example [Flutter Tex](https://github.com/shahzadakram67/flutter_tex)

**Comment by wxlpp** [comment]
https://github.com/NanoMichael/cLaTeXMath

**Comment by shahxadakram** [comment]
Please check this  flutter package https://github.com/shahxadakram/flutter_tex

**Comment by yarcowang** [comment]
plus Markdown (js: marked)
plus Latex(js: katex)
At least, they have javascript versions...
(I'm sorry, I can only make request...)

**Comment by takdw** [comment]
@shahxadakram That is a pretty neat package. Doesn't play well with complex layouts though. I have to figure out another way of integrating it in my app. Thanks for the share.

**Comment by shahxadakram** [comment]
> @shahxadakram That is a pretty neat package. Doesn't play well with complex layouts though. I have to figure out another way of integrating it in my app. Thanks for the share.

Would you like to mention the issues, I made some amendments in the latest version, Please check that , https://pub.dev/packages/flutter_tex, You can create issue regarding any problem in package.

**Comment by mikeroneer** [comment]
> @shahxadakram That is a pretty neat package. Doesn't play well with complex layouts though. I have to figure out another way of integrating it in my app. Thanks for the share.

Hi @takdw! Do you have any updates on that? Could you find a way to address this issue?
