### ISSUE TITLE
ci.yaml validation Pending indefinitely

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#129213]
As on https://github.com/flutter/flutter/pull/129199#issuecomment-1599595842, where the autosubmit bot removed the autosubmit label because ci.yaml validation never finished.

This was also affecting Jonah over the weekend:

- https://github.com/flutter/engine/pull/42971/checks?sha=d8f0047a107a11017b47c297bad492689330ceee
- https://github.com/flutter/engine/pull/42962/checks?sha=f956fa22413429c496e4d7903ff58e422764c1f1

**Comment by christopherfujino** [comment]
nvm, this is a dupe of https://github.com/flutter/flutter/issues/129134

**Comment by andrewkolos** [comment]
Did you mean to close this since it's a dupe? Feel free to reopen.

**Comment by christopherfujino** [comment]
> Did you mean to close this since it's a dupe? Feel free to reopen.

thanks
