### ISSUE TITLE
Flutter deeplinking not working with http or https as scheme

### ISSUE THREAD

**Issue by chrisDK1977** [flutter/flutter#129260]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Adding the following to the AndroidManifest.xml of some app

        <intent-filter android:autoVerify="true">
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="https" android:host="myapp.myserver.de"/>
        </intent-filter>
        
        <intent-filter android:autoVerify="true">
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="myAppName" android:host="myapp.myserver.de"/>
        </intent-filter>

### Expected results

Both should work.

### Actual results

Deeplinking with https is not working on android 12 but on android 11

### Code sample

Adding the following to the AndroidManifest.xml of some app

        <intent-filter android:autoVerify="true">
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="https" android:host="myapp.myserver.de"/>
        </intent-filter>
        
        <intent-filter android:autoVerify="true">
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="myAppName" android:host="myapp.myserver.de"/>
        </intent-filter>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

C:\SDKs\flutter_latest\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 3.7.12, on Microsoft Windows [Version 10.0.19044.3086], locale de-DE)
    • Flutter version 3.7.12 on channel stable at C:\SDKs\flutter_latest\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (9 weeks ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:/Users/XXX/AppData/Local/Android/Sdk
    • Platform android-33-ext5, build-tools 33.0.2
    • ANDROID_HOME = C:/Users/XXX/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31229.75
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2021.2.3
    • Flutter plugin version 73.1.1
    • Dart plugin version 231.9065

[√] Connected device (5 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Android SDK built for x86 (mobile) • emulator-5556 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19044.3086]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 114.0.5735.134
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 114.0.1823.51

[√] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by dam-ease** [comment]
Hi @chrisDK1977
Can you try using this if it works in your case?:
```
<intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <!-- Accepts URIs that begin with YOUR_SCHEME://YOUR_HOST -->
                <data android:scheme="http" android:host="myapp.myserver.de" />
                <data android:scheme="https" />
            </intent-filter>
```

**Comment by yogeshButani** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the [existing issues](https://github.com/flutter/flutter/issues)
> * [x]  I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)
> 
> ### Steps to reproduce
> Adding the following to the AndroidManifest.xml of some app
> 
> ```
>     <intent-filter android:autoVerify="true">
>         <action android:name="android.intent.action.VIEW" />
>         <category android:name="android.intent.category.DEFAULT" />
>         <category android:name="android.intent.category.BROWSABLE" />
>         <data android:scheme="https" android:host="myapp.myserver.de"/>
>     </intent-filter>
>     
>     <intent-filter android:autoVerify="true">
>         <action android:name="android.intent.action.VIEW" />
>         <category android:name="android.intent.category.DEFAULT" />
>         <category android:name="android.intent.category.BROWSABLE" />
>         <data android:scheme="myAppName" android:host="myapp.myserver.de"/>
>     </intent-filter>
> ```
> 
> ### Expected results
> Both should work.
> 
> ### Actual results
> Deeplinking with https is not working on android 12 but on android 11
> 
> ### Code sample
> Adding the following to the AndroidManifest.xml of some app
> 
> ```
>     <intent-filter android:autoVerify="true">
>         <action android:name="android.intent.action.VIEW" />
>         <category android:name="android.intent.category.DEFAULT" />
>         <category android:name="android.intent.category.BROWSABLE" />
>         <data android:scheme="https" android:host="myapp.myserver.de"/>
>     </intent-filter>
>     
>     <intent-filter android:autoVerify="true">
>         <action android:name="android.intent.action.VIEW" />
>         <category android:name="android.intent.category.DEFAULT" />
>         <category android:name="android.intent.category.BROWSABLE" />
>         <data android:scheme="myAppName" android:host="myapp.myserver.de"/>
>     </intent-filter>
> ```
> 
> ### Screenshots or Video
> Screenshots / Video demonstration
> ### Logs
> Logs
> ### Flutter Doctor output
> C:\SDKs\flutter_latest\flutter\bin\flutter.bat doctor --verbose [√] Flutter (Channel stable, 3.7.12, on Microsoft Windows [Version 10.0.19044.3086], locale de-DE) • Flutter version 3.7.12 on channel stable at C:\SDKs\flutter_latest\flutter • Upstream repository https://github.com/flutter/flutter.git • Framework revision [4d9e56e](https://github.com/flutter/flutter/commit/4d9e56e694b656610ab87fcf2efbcd226e0ed8cf) (9 weeks ago), 2023-04-17 21:47:46 -0400 • Engine revision 1a65d409c7 • Dart version 2.19.6 • DevTools version 2.20.1
> 
> [X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 33.0.2) • Android SDK at C:/Users/XXX/AppData/Local/Android/Sdk • Platform android-33-ext5, build-tools 33.0.2 • ANDROID_HOME = C:/Users/XXX/AppData/Local/Android/Sdk • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189) • All Android licenses accepted.
> 
> [√] Chrome - develop for the web • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
> 
> [√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.5) • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community • Visual Studio Community 2019 version 16.9.31229.75 • Windows 10 SDK version 10.0.19041.0
> 
> [√] Android Studio (version 2020.3) • Android Studio at C:\Program Files\Android\Android Studio • Flutter plugin can be installed from: https://plugins.jetbrains.com/plugin/9212-flutter • Dart plugin can be installed from: https://plugins.jetbrains.com/plugin/6351-dart • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
> 
> [√] IntelliJ IDEA Ultimate Edition (version 2023.1) • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2021.2.3 • Flutter plugin version 73.1.1 • Dart plugin version 231.9065
> 
> [√] Connected device (5 available) • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator) • Android SDK built for x86 (mobile) • emulator-5556 • android-x86 • Android 11 (API 30) (emulator) • Windows (desktop) • windows • windows-x64 • Microsoft Windows [Version 10.0.19044.3086] • Chrome (web) • chrome • web-javascript • Google Chrome 114.0.5735.134 • Edge (web) • edge • web-javascript • Microsoft Edge 114.0.1823.51
> 
> [√] HTTP Host Availability • All required HTTP hosts are available

yes i am facing the same issue, app is not opening even link also not generating... it always giving null in return instead of link...ive tried many solution but nothing works...also deeplinking in androidmanifest.xml is correct but not getting link....please reply this issue ..is i am the only one who is suffering from this issue?

**Comment by yogeshButani** [comment]
> Hi @chrisDK1977 Can you try using this if it works in your case?:
> 
> ```
> <intent-filter android:autoVerify="true">
>                 <action android:name="android.intent.action.VIEW" />
>                 <category android:name="android.intent.category.DEFAULT" />
>                 <category android:name="android.intent.category.BROWSABLE" />
>                 
>                 <data android:scheme="http" android:host="myapp.myserver.de" />
>                 <data android:scheme="https" />
>             </intent-filter>
> ```

yes i am facing the same issue, app is not opening even link also not generating... it always giving null in return instead of link...ive tried many solution but nothing works...also deeplinking in androidmanifest.xml is correct but not getting link....please reply this issue ..is i am the only one who is suffering from this issue?

**Comment by 0xManjeet** [comment]
facing same issue.

**Comment by 0xManjeet** [comment]
> > Hi @chrisDK1977 Can you try using this if it works in your case?:
> > ```
> > <intent-filter android:autoVerify="true">
> >                 <action android:name="android.intent.action.VIEW" />
> >                 <category android:name="android.intent.category.DEFAULT" />
> >                 <category android:name="android.intent.category.BROWSABLE" />
> >                 
> >                 <data android:scheme="http" android:host="myapp.myserver.de" />
> >                 <data android:scheme="https" />
> >             </intent-filter>
> > ```
> 
> yes i am facing the same issue, app is not opening even link also not generating... it always giving null in return instead of link...ive tried many solution but nothing works...also deeplinking in androidmanifest.xml is correct but not getting link....please reply this issue ..is i am the only one who is suffering from this issue?

I think it's because of this: https://developer.android.com/training/app-links/verify-android-applinks#web-assoc

**Comment by yogeshButani** [comment]
did you solve this issue?, i think it is the issue of uni_links package in newer flutter sdk versions..i tried so many solutions but its not working, if you find the solution then please let me know

**Comment by chrisDK1977** [comment]
Sorry for the late response... it does not fix the problem - it still exists.

**Comment by dam-ease** [comment]
Hi @chrisDK1977. Thanks for the response. Can you please upgrade to the latest `stable` version to confirm this issue still persists? Also, are you using the `uni_links` package? If not, kindly provide more info on how we can reproduce this on our end.
