### ISSUE TITLE
[Impeller] Texture scaling is off for drawVertices.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#129204]
After https://github.com/flutter/engine/pull/43017, we'll avoid creating textures that are too large for the device when drawing vertices that have an image shader on them.

However, we're not handling the scaling as nicely as Skia does in e.g. the panorama example app (https://github.com/zesage/panorama/). That should be fixable but I'm tired of looking at it right now :)

**Comment by dnfield** [comment]
Skia:

![DB220A1F-5625-46CC-9DC5-62796D9AA3E8](https://github.com/flutter/flutter/assets/8620741/0b7f6c1f-f18a-425b-a2fa-12bc58cb2467)

Impeller (after my patch):

![FA3D7421-3256-4775-ADA0-3AF8D424FE46](https://github.com/flutter/flutter/assets/8620741/a8d58f5f-2cac-4ae1-babc-63df377ccb77)

**Comment by jonahwilliams** [comment]
that looks ... pretty wrong. That's definitely more than just nearest neighbor scaling right? it looks like we're clamping values.

Wait, is this a float16 issue 😓

**Comment by jonahwilliams** [comment]
@dnfield in the frame capture is it the first or second pass in drawVertices that looks wrong?

**Comment by dnfield** [comment]
I haven't done a frame capture of this recently.

I think this is just a pure and simple scaling issue somewhere

**Comment by dnfield** [comment]
I fixed this in the patch, it won't be an issue.
