### ISSUE TITLE
[CP] Use the arm64 dsymutil on Mac M1 machines

### ISSUE THREAD

**Issue by XilaiZhang** [flutter/flutter#129216]
### Issue Link

https://github.com/flutter/flutter/issues/128098

### Commit Hash

51928f2

### Target

beta

### PR Link

https://github.com/flutter/engine/pull/43022

### Changelog Description

Use the right binary architectures on scripts running dsymutil.

### Impacted Users

flutter release engineers running dart internal

### Impact Description

engine builds will fail on dart internal

### Workaround

if you got lucky and the architecture is right you won't hit this problem

### Risk

low

### Test Coverage

yes

### Validation Steps

engine build should not hit `Bad CPU type in executable` error when built through dart internal

**Comment by XilaiZhang** [comment]
would be great if @godofredoc @zanderso could help take a look. Thank you!

**Comment by godofredoc** [comment]
LGTM

**Comment by XilaiZhang** [comment]
Thanks for reviewing!
