### ISSUE TITLE
Break point goes to un-verified break point

### ISSUE THREAD

**Issue by Puspharaj** [flutter/flutter#129252]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

its randomly happens or not hard to reproduce. Might be VSCODE bug too. Please verify. 

[](https://youtu.be/uQkvgEp-lEY

)### Actual results

break points cannot turn into un-verified breakpoints 

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by darshankawar** [comment]
@Puspharaj 
You may want to file this https://github.com/Dart-Code/Dart-Code/issues. I see a similar issue that you can take a look at https://github.com/Dart-Code/Dart-Code/issues/2742

Closing from here.
