### ISSUE TITLE
There's no way for InheritedElement to know that a dependent has been deactivated

### ISSUE THREAD

**Issue by s0nerik** [flutter/flutter#129207]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I'm finishing the promising-looking, easy-to-use approach to state management, which requires that `InheritedElement` is notified when the dependent has been removed from the dependents list to properly close all value change subscriptions upon dependent element deactivation.

### Proposal

Call the `dependency.onDependentRemoved(this)` right after `dependency._dependents.remove(this)` inside the `Element.deactivate()`

**Comment by goderbauer** [comment]
Duplicate of https://github.com/flutter/flutter/issues/128432.
