### ISSUE TITLE
`WidgetTester`'s "end of test verifications" cause integration tests to always fail when Android `UiAutomation` is used

### ISSUE THREAD

**Issue by bartekpacia** [flutter/flutter#129231]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Context

I'm working on Patrol – a test framework for Flutter apps. One of its main features is the ability to interact with native UI, like permission dialogs, notifications, WebViews, and just about any other native UI (e.g. system settings app, GMail app – basically everything). It does this by leveraging the platform's native UI automation frameworks – XCUITest on iOS, and UiAutomator on Android.

Unfortunately, I've found a problem (which I believe is a bug in `flutter`, or maybe `flutter_test`) that causes tests to fail _after they finish_. 

The bug occurs when the following conditions are met:
- The app uses Flutter 3.10.x
- The tests are run on Android (tested with API 31, possibly many/all others)
- The test use Android's native automation API ([`UiAutomation`](https://developer.android.com/reference/android/app/UiAutomation)) at least once

### Steps to reproduce

1. Clone [the Patrol repository](https://github.com/leancodepl/patrol) and `cd` into `packages/patrol/example`
1. Start up Android emulator (I used Pixel 4 API 31)
1. `flutter run` to generate `gradlew` and to make sure that the example app builds and runs just fine
1. Install Patrol CLI, which is needed to run Flutter integration tests that use Patrol's native UI automation feature. Use the latest prerelease version:

    ```
    dart pub global activate \
      --source git https://github.com/leancodepl/patrol.git \
      --git-path packages/patrol_cli \
      --git-ref patrol_cli-v2.0.0-dev.3
    ```
  
      We'll release 2.0 very soon, but it almost certainly won't change this behavior, i.e. the bug will still be reproducible.

1. Remove the workaround for the this problem. To do this, open `packages/patrol/lib/src/common.dart` and remove [the following lines](https://github.com/leancodepl/patrol/blob/a49dfccb3b975c0d7f5f57e630f11b030a319b06/packages/patrol/lib/src/common.dart#L115-L121):

    ```dart
    widgetTester.binding.platformDispatcher.onSemanticsEnabledChanged = () {
      // This callback is empty on purpose. It's a workaround for tests
      // failing on Android on Flutter 3.10 (#1265)
      //
      // See #1265 and #1352.
      // TODO(bartekpacia): Create bug report to Flutter.
    };
    ```

    > Of course, if you add these lines back, the problem will no longer occur. But this is quite an ugly workaround.
1. `patrol test --target integration_test/example_test.dart` to run a simple integration test ([example_test.dart](
https://github.com/leancodepl/patrol/blob/a49dfccb3b975c0d7f5f57e630f11b030a319b06/packages/patrol/example/integration_test/example_test.dart))

1. Observe test failure (ignore the (broken) update prompt):

    ```console
    $ patrol test -t integration_test/example_test.dart
    
    Update available! 2.0.0-dev.3 → 1.1.11
    Run patrol update to update
    
    No device specified, using the first one (emulator-5554)
    • Building apk with entrypoint test_bundle.dart...
    ✓ Completed building apk with entrypoint test_bundle.dart (3.3s)
    • Executing tests of apk with entrypoint test_bundle.dart on emulator-5554...
	    See the report at: file:///Users/bartek/dev/leancode/patrol/packages/patrol/example/build/app/reports/androidTests/connected/index.html
    ✗ Failed to execute tests of apk with entrypoint test_bundle.dart on emulator-5554 (Gradle test execution failed with code 1) (15.9s)
    Exception: Gradle test execution failed with code 1
    See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
     FAIL  test_bundle.dart on emulator-5554
    ```

1. Open the report (path visible in the output above) in a web browser to see detailed error message:

    ![Screenshot 2023-06-21 at 8 42 56 AM](https://github.com/flutter/flutter/assets/40357511/e19fe56b-3464-4f6e-ac37-3eeeff20f8cc)

### Expected results

I expect no problems, i.e. the tests should pass.

More specifically, I expect all `SemanticsHandle`s to be correctly disposed at the end of the test.

### Actual results

Once the test _almost_ finishes running (i.e. the anonymous function passed to `testWidgets()` returns, but before it finishes running), the following `FlutterError` is thrown:

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following assertion was thrown running a test:
A SemanticsHandle was active at the end of the test.
All SemanticsHandle instances must be disposed by calling
dispose() on the SemanticsHandle.

When the exception was thrown, this was the stack:
#0      WidgetTester._verifySemanticsHandlesWereDisposed (package:flutter_test/src/widget_tester.dart:1051:7)
#1      WidgetTester._endOfTestVerifications (package:flutter_test/src/widget_tester.dart:1042:5)
#2      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:998:22)
<asynchronous suspension>

The test description was:
counter state is the same after going to Home and switching
apps
```

### Investigation – why is this happening?

I heavily relied on `adb` while debugging (specifically: `$ adb logcat -v color`).

**1. Inside the test**

1. `$.native.pressHome()` is called. ([See Flutter-side method](https://github.com/leancodepl/patrol/blob/a49dfccb3b975c0d7f5f57e630f11b030a319b06/packages/patrol/lib/src/native/native_automator.dart#L488-L500)) ([See Android-side method](https://github.com/leancodepl/patrol/blob/a49dfccb3b975c0d7f5f57e630f11b030a319b06/packages/patrol/android/src/main/kotlin/pl/leancode/patrol/Automator.kt#L101-L105))
3. [`UiDevice#pressHome()`](https://developer.android.com/reference/androidx/test/uiautomator/UiDevice#pressHome()) is called inside the Android part of the Patrol plugin. **This initializes UiAutomation**.

    > `$` is an object of type `PatrolTester`, and `native` is an object of type `NativeAutomator`. Ignore these Patrol-specific things – they do not matter to the issue.

**2. Inside Android OS**

1. [`UiAutomation`](https://developer.android.com/reference/android/app/UiAutomation) is initialized. This is evidenced by the logs:

```
06-16 11:46:33.920 22227 22263 I flutter : Patrol (native): pressHome() started
06-16 11:46:33.923 22227 22254 D PatrolServer: pressHome()
06-16 11:46:33.938 22227 22286 V UiAutomation: Init UiAutomation@8d52720[id=6, flags=0]
```

The line `UiAutomation: Init UIAutomation@...` [comes from here](https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-13.0.0_r54/core/java/android/app/UiAutomation.java#1555).

**3. Inside Flutter Engine**

Flutter Engine listens for accessibility-related events, and initalizing`UiAutomation` is one of them. This causes the `update_accessibility_features` function to be called, [here](https://github.com/flutter/engine/blob/3.10.4/lib/ui/window/platform_configuration.cc#L57-L59).

  1. Bridging/forwarding events between the Engine and the Framework is done [here, in `hooks.dart`](https://github.com/flutter/engine/blob/3.10.4/lib/ui/hooks.dart#L79-L82) and also [here, in `platform_dispatcher.dart`](https://github.com/flutter/engine/blob/2a3401c9bbb5a9a9aec74d4f735d18a9dd3ebf2d/lib/ui/platform_dispatcher.dart#L1100-L1111)
  1. PlatformDispatcher calls `onSemanticsEnabledChanged()` [here](https://github.com/flutter/engine/blob/3.10.4/lib/ui/platform_dispatcher.dart#L1092), which is picked up by `SemanticsBinding` (but that's no longer inside the Engine)

**4. Inside Flutter Framework**

1. [`SemanticsBinding` listens for `PlatformDispatcher.onSemanticsEnabledChanged()`](https://github.com/flutter/flutter/blob/682aa387cfe4fbd71ccd5418b2c2a075729a1c66/packages/flutter/lib/src/semantics/binding.dart#L21-L22) and when it happens, it [handles it](https://github.com/flutter/flutter/blob/3.10.4/packages/flutter/lib/src/semantics/binding.dart#L105-L112) – by creating a new `SemanticsHandle`.

**5. Inside `flutter_test`**

The test ultimately finishes, but [`SemanticsBinding._handle`](https://github.com/flutter/flutter/blob/682aa387cfe4fbd71ccd5418b2c2a075729a1c66/packages/flutter/lib/src/semantics/binding.dart#L102-L103), created when `PlatformDispatcher.onSemanticsEnabledChanged()` was called, lives on.

When the test finishes, `WidgetTester` does some verification and cleanup by calling [`_endOfTestVerifications`](https://github.com/flutter/flutter/blob/682aa387cfe4fbd71ccd5418b2c2a075729a1c66/packages/flutter_test/lib/src/widget_tester.dart#L1040), which in turn calls [`_verifySemanticsHandlesWereDisposed`](https://github.com/flutter/flutter/blob/682aa387cfe4fbd71ccd5418b2c2a075729a1c66/packages/flutter_test/lib/src/widget_tester.dart#L1045-L1060). This function makes sure that all `SemanticsHandle`s that were created during the test are disposed. **But this is not the case**, because the additional `SemanticsHandle` (`SemanticsBinding._handle`) (created by UiAutomation being initalized) is still active when the test finishes (because UiAutomation is still running).

### Possible solutions

The first is the workaround that is already present in Patrol – to replace the existing implementation of `widgetTester.binding.platformDispatcher.onSemanticsEnabledChanged` with an empty function. But as I said above, this is ugly.

Another solution would be to let developers disable `WidgetTester._endOfTestVerifications`, but I understand that it may result in some strange issues.

I think that the best solution would be to figure out how to gracefully shutdown `UiAutomation` before `WidgetTester._endOfTestVerifications` are run, but that's probably out of scope of Flutter.

### More info

- Q: Why is [`UiAutomation`](**url**) counted as an accessibility service?
  A: [`UiAutomation`](https://developer.android.com/reference/android/app/UiAutomation) relies on platform accessibility APIs to interact with the native UI. It's kind of a special type of accessibility service. See also [this SO question](https://stackoverflow.com/questions/64772554/uiautomation-vs-accessibilityservice).
- This possibility of a problem like this occurring is indirectly hinted at [in this comment](https://github.com/flutter/flutter/issues/81534#issuecomment-1061360011)
- I'm pretty sure it was introduced in #121571, which changed how semantics handles are counted during tests (i.e. made it more strict)
- The problem was first reported in [this issue](https://github.com/leancodepl/patrol/issues/1265), and the workaround was implemented in [this PR](https://github.com/leancodepl/patrol/pull/1352).

### Code sample

A simple failing test was linked to above ([example_test.dart](https://github.com/leancodepl/patrol/blob/a49dfccb3b975c0d7f5f57e630f11b030a319b06/packages/patrol/example/integration_test/example_test.dart)).

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

Here's `example_test.dart` running:

[example_test.webm](https://github.com/flutter/flutter/assets/40357511/cd680cbb-d92b-4a05-ba92-46fff7f5d5da)

It _almost_ completes successfully. It's only marked as failed at the very end of the test, because the `FlutterError` I talk about above is thrown.

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4 22F66 darwin-arm64, locale en-PL)
    • Flutter version 3.10.5 on channel stable at /Users/bartek/fvm/versions/3.10.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (7 days ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/bartek/androidsdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/bartek/androidsdk
    • Java binary at: /Users/bartek/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.10121639/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/bartek/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.10121639/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.3)
    • IntelliJ at /Users/bartek/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 74.0.4
    • Dart plugin version 231.9161.14

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.3)
    • IntelliJ at /Users/bartek/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9161.38/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 31) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 114.0.5735.133

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Thanks for your detailed issue, @bartekpacia 
When try running your example code (`packages/patrol/example`) on Pixel 4 API 31, I encountered this error that I'm not sure if you have experienced the same? Looks like it's an issue with [flutter_native_timezone](https://pub.dev/packages/flutter_native_timezone) package. 

```console
/Users/huynq/Documents/NEVERCODE.IO/RepoduceProjects/OPClone/patrol/packages/patrol/example/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:24: error: cannot find symbol
      flutterEngine.getPlugins().add(new com.whelksoft.flutter_native_timezone.FlutterNativeTimezonePlugin());
                                                                              ^
  symbol:   class FlutterNativeTimezonePlugin
  location: package com.whelksoft.flutter_native_timezone
1 error
```

<details>
<summary>Complete error log</summary>

```console
Launching lib/main.dart on sdk gphone64 x86 64 in debug mode...
main.dart:1
/Users/huynq/Documents/NEVERCODE.IO/RepoduceProjects/OPClone/patrol/packages/patrol/example/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:24: error: cannot find symbol
      flutterEngine.getPlugins().add(new com.whelksoft.flutter_native_timezone.FlutterNativeTimezonePlugin());
                                                                              ^
  symbol:   class FlutterNativeTimezonePlugin
  location: package com.whelksoft.flutter_native_timezone
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s
Exception: Gradle task assembleDebug failed with exit code 1
Exited
```
</details>

**Comment by bartekpacia** [comment]
Hi @huycozy, thanks for triaging this. Sorry for the problem - I didn't have it. I'll look into it!

**Comment by bartekpacia** [comment]
Also, what I provided is not _ a minimal reproducible sample_, but it is _a reproducible sample_.

I hope I explained the problem clearly enough so that it's easy to understand and debug, but if it's not, then I'm happy to create a truly, absolutely bare minimum sample, without Patrol. Unfortunately, currently I don't have bandwidth to do it.

**Comment by huycozy** [comment]
Hi @bartekpacia 
I passed above `flutter_native_timezone` error by `flutter clean`. But now I have another error with your `patrol_cli`:

```console
       FAILURE: Build failed with an exception.

        * What went wrong:
        Execution failed for task ':permission_handler_android:compileDebugJavaWithJavac'.
        > Compilation failed; see the compiler error output for details.
```

This is [verbose log](https://pastes.io/izvfikzwqj) if you might want to take a look. This looks similar to an existing issue on your package: https://github.com/leancodepl/patrol/issues/1252. `flutter clean` can not make it work in this case.

----

Regarding main issue with WidgetTester, I found there was an issue (https://github.com/flutter/flutter/issues/18015) that contains similar error messages there. Can you check if the issue still persists on a physical device? 

Also, it seems the current condition is corresponding to what [goderbauer](https://github.com/goderbauer) mentioned at https://github.com/flutter/flutter/issues/18015#issuecomment-393265862.


https://github.com/flutter/flutter/blob/15d594c2567afaa7e39b0174e163aee599a7a8f8/packages/flutter_test/lib/src/widget_tester.dart#L1053-L1068

Please check if you can add implementation corresponding to that condition to solve this issue.

**Comment by bartekpacia** [comment]
@huycozy, sorry for the problems. I have not seen this issue before - it's quite strange.

Please try running `./gradlew :clean` in addition to `flutter clean`, and if that doesn't help, consider removing `~/.gradle/caches` altogether. Let me know if that helps - I'm determined to reproduce this issue :)

---

> Can you check if the issue still persists on a physical device?

I tried to on Motorola Moto G6 (Android 9), and Samsung Galaxy S9 (Android 10), but unfortunately, I couldn't reproduce the issue because of unrelated test failures. I don't have access to more physical devices.

I can reproduce it on various emulators, though.

**Comment by bartekpacia** [comment]
> Please check if you can add implementation corresponding to that condition to solve this issue.

That's an interesting good idea - thanks. I could try initializing the `UiAutomation` service _before_ the test starts.

**Comment by bartekpacia** [comment]
I'm happy to say that I moving `UiAutomation` initialization to happen earlier (before `testWidgets()` starts) fixed the problem this issue talks about. In case you're curious, [here's the PR](https://github.com/leancodepl/patrol/pull/1395).

**Comment by bartekpacia** [comment]
No action from Flutter is required. Thank you @huycozy!

**Comment by huycozy** [comment]
You are welcome! Glad you solved it :)
