### ISSUE TITLE
Cannot change fontFamily on ThemeData.dark() or ThemeData.light()

### ISSUE THREAD

**Issue by TaylorHo** [flutter/flutter#129209]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a custom theme, based on the dark theme (can be the light one too): `ThemeData.dark().copyWith();`
2. Try adding a custom fontFamily: `ThemeData.dark().copyWith(fontFamily: 'CustomFont');`
3. You will notice that ThemeData.dark() does not implement the fontFamily attribute (theme ThemeData does, but ThemeData.dark() does not)

### Expected results

At the `ThemeData.dark()` and the `ThemeData.light()` should be possible to change the font family.

### Actual results

The `ThemeData.dark()` and the `ThemeData.light()` don't allow me to change the font family.

### Code sample

<details><summary>Code sample</summary>

```dart
void main() {
  runApp(
    MaterialApp(
      theme: ThemeData.dark().copyWith(
        fontFamily: 'MyCustomFont', // this does not work
      ),
      home: const MyApp(),
    );
  );
}
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4 22F66 darwin-arm64, locale en-BR)
    • Flutter version 3.10.5 on channel stable at /Users/tho/src/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (7 days ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/tho/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.133

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by TaylorHo** [comment]
It's a simple change.

If it is decided that this will be done, I can implement and open a PR adjusting it.

**Comment by Kavan2003** [comment]
I want to get this issue

**Comment by huycozy** [comment]
Thanks for filing the issue. I see there's an open issue addressing a similar case: https://github.com/flutter/flutter/issues/98534. Even though it didn't mention exactly `dark` or `light` but it would be better to centralize on that issue.

Closing this issue in favor of https://github.com/flutter/flutter/issues/98534, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
