### ISSUE TITLE
[google_maps_flutter] App is closing on ios

### ISSUE THREAD

**Issue by UkioMaeni** [flutter/flutter#129264]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I open the page where GoogleMap is expected and attached to iOS. Broken with rotation with dimensions and td.
Stacktrace https://pastebin.com/iEjg2ER3

### Expected results

The attachment fails only on iOS

### Actual results

The attachment fails

### Code sample

<details><summary>Code sample</summary>

```dart
страница с виджетом:
import 'dart:async';

import 'package:ezride/pages/mainapp/menupages/search/search.dart';
import 'package:flutter/material.dart';
import 'package:flutter_svg/svg.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

class UIMap extends StatefulWidget{
  int cityId;
  double latitude;
  double longitude;
  Completer<GoogleMapController> mapController;
  late GoogleMapController _controller;
  Function update;
  String city;
   UIMap({required this.cityId, required this.city, required this.update, required this.mapController, required this.latitude,required this.longitude, super.key});

  @override
  State<UIMap> createState() => _UIMapState();
}

class _UIMapState extends State<UIMap> {
  double latitudeRide=0;
  double longitudeRide=0;
  CameraPosition initial =CameraPosition(
      bearing: 192.8334901395799,
      target: LatLng(37.43296265331129, -122.08832357078792),
      tilt: 59.440717697143555,
      zoom: 19.151926040649414
   );

  @override
  void initState() {
    initial=CameraPosition(
      target: LatLng(widget.latitude, widget.longitude),
      zoom:  16
    );

    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Stack(
      alignment: Alignment.center,
      children: [
        GoogleMap(
        initialCameraPosition: initial,
        mapType: MapType.normal,
        onMapCreated: (controller)async{
          widget.mapController.complete(controller);
          widget._controller= await widget.mapController.future;
        },
        onCameraIdle: () async{
         final ss=await widget._controller.getLatLng(const ScreenCoordinate(x: 0, y: 0));
         setState(() {
           latitudeRide=ss.latitude;
           longitudeRide=ss.longitude;
         });
        },
        
        ),
        SvgPicture.asset("assets/svg/marker.svg"),
        Positioned(
          bottom: 42,
          right: 27,
          child: InkWell(
            onTap: (){
              DataCreate newDate=DataCreate(widget.cityId, widget.city, latitudeRide, longitudeRide);
              widget.update(newDate);
              Navigator.of(context).popUntil((route) => route.settings.name == '/menu');
            },
            child: Container(
              height: 56,
              width: 56,
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(28),
                color: Color.fromRGBO(58,121,215,1)
              ),
              child: Icon(Icons.arrow_forward,color: Colors.white,size: 30,),
            ),
          ),
        )
      ],
      
    );
  }
}

info.plist и appDelegate.swift настроены согласно документации



```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.7.9, on Microsoft Windows [Version 10.0.19045.3086], locale ru-RU)
    • Flutter version 3.7.9 on channel stable at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 62bd79521d (3 months ago), 2023-03-30 10:59:36 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)     
    • Android SDK at C:\Users\UkioMaeni\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = C:\Users\UkioMaeni\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java       
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.4)
    • Visual Studio at D:\VS
    • Visual Studio Community 2022 version 17.5.33530.505
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.3086]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 114.0.5735.134
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 114.0.1823.37

[√] HTTP Host Availability
    • All required HTTP hosts are available

```

</details>

**Comment by darshankawar** [comment]
@UkioMaeni 
Thanks for the report. I tried translating in English so it is readable. 
Is the crash occuring on simulator or on physical device too ?
Can you run the code provided without third party package implementation (ex: flutter_svg) and see if you are still able to replicate the crash ?
Also it seems you have iOS native app being used with Flutter. Please also provide `appDelegate.swift` complete code that we can use to verify the issue properly.

**Comment by UkioMaeni** [comment]
> @UkioMaeni Thanks for the report. I tried translating in English so it is readable. Is the crash occuring on simulator or on physical device too ? Can you run the code provided without third party package implementation (ex: flutter_svg) and see if you are still able to replicate the crash ? Also it seems you have iOS native app being used with Flutter. Please also provide `appDelegate.swift` complete code that we can use to verify the issue properly.

without flutter_svg it breaks too.
The crash occurs on both the real device and the emulator.
This is a pure flutter project.
AppDelegate.swift
`
import UIKit
import Flutter
import GoogleMaps
import FirebaseCore

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
        FirebaseApp.configure()
        // FirebaseMessaging.instance.delegate = self
        GMSServices.setMetalRendererEnabled(true)
        GMSServices.provideAPIKey("YOUR_API_KEY")

        if CLLocationManager.locationServicesEnabled() {
          let locationManager = CLLocationManager()
          locationManager.requestWhenInUseAuthorization()
        }
        
        GeneratedPluginRegistrant.register(with: self)
        // Perform your specific error-throwing operation here    
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
`

**Comment by darshankawar** [comment]
Thanks for the update. Does it crash consistently everytime you try to run ?
Can you also take a look at [plugin example](https://github.com/flutter/packages/tree/main/packages/google_maps_flutter/google_maps_flutter/example) and run on affected simulator / device and see if you still get the same error ?
