### ISSUE TITLE
image_picker app crashes on Iphone when "Take Photo" is chosen

### ISSUE THREAD

**Issue by NickRun** [flutter/flutter#12929]
Using example code:

```dart
class _MyHomePageState extends State<MyHomePage> {

  File imageFile;

  getImage() async {
    var _fileName = await ImagePicker.pickImage();
    setState(() {
      imageFile = _fileName;
    });
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text('Image Picker Example'),
      ),
      body: new Center(
        child: imageFile == null
          ? new Text('No image selected.')
          : new Image.file(imageFile),
      ),
      floatingActionButton: new FloatingActionButton(
        onPressed: getImage,
        tooltip: 'Pick Image',
        child: new Icon(Icons.add_a_photo),
      ),
    );
  }
}
```

Using "flutter run" on device iPhone iOS 11.1 (not simulator)

"Choose Photo" works as expected. But when I attempt to "Take Photo" the app closes and Flutter CLI logs "Lost connection to device."

Flutter doctor output:

[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-US, channel master)
    • Flutter at /Users/username/flutter
    • Framework revision b04b89ac95 (57 minutes ago), 2017-11-08 20:39:05 +0100
    • Engine revision dd6585bb9a
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.0)
    • Android SDK at /Users/username/Library/Android/sdk
    • Platform android-27, build-tools 27.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.1, Build version 9B55
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.5)
    • Flutter plugin version 18.3
    • Dart plugin version 172.4343.25

[✓] Connected devices
    • iPhone • f570f4c99b953a8ef20ebb6be9b307e2eaf1743d • ios • iOS 11.1

**Comment by eseidelGoogle** [comment]
Looks like @roughike is working in this space?

**Comment by eseidelGoogle** [comment]
I don't recall who on our team wrote the original image_picker plugin, but @goderbauer might know.

**Comment by roughike** [comment]
Does the nfo.plist file have `NSCameraUsageDescription` specified? If I remember correctly, it won't work and may crash without it.

The documentation doesn't mention anything about this though.

**Comment by NickRun** [comment]
@roughike `NSCameraUsageDescription` was used as a value for `Application Category` by default. I'm not sure how that was generated.

I was able to get it work by adding key `Privacy - Camera Usage Description` and a description for the value.

**Comment by iamjavademon** [comment]
I just knew it. It was omitted in documentation. I better add it.
