### ISSUE TITLE
Enable the Java format check unit tests

### ISSUE THREAD

**Issue by loic-sharma** [flutter/flutter#129221]
## Background

https://github.com/flutter/engine/pull/36123 adds tests to verify formatting pre-push checks work. The Java format check was disabled as the Java dependency isn't available on all platforms: https://github.com/flutter/engine/blob/22401c23e94c6e4ffeb58c171b0d151a614c60e9/DEPS#L767

## Solution

If the Java dependency is available, enable the Java format check unit tests: https://github.com/flutter/engine/blob/08aaa88bf67fcd5a18d4309d89c1e940a544e49a/ci/test/format_test.dart#L190-L192

**Comment by eseidel** [comment]
Fixing in https://github.com/flutter/engine/pull/54450.
