### ISSUE TITLE
I have a weak laptop and I need suitable Emulator.

### ISSUE THREAD

**Issue by MUGDAD-78** [flutter/flutter#129348]
Hello, I can't run the emulator beacuse of my laptop, it's i3 Cpu and 4GB Ram. Can I run an emulator with it, If I can please give me the steps.

**Comment by dam-ease** [comment]
Hi @MUGDAD-78 
This issue doesn't seem to describe a bug or a feature request. Please see https://flutter.dev/community for resources and asking questions like this.
Closing, as this isn't an issue with Flutter itself.
Thank you
