### ISSUE TITLE
Support webgpu to provide stronger 2D/3D rendering capabilities

### ISSUE THREAD

**Issue by WREQI** [flutter/flutter#129336]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Can't solve it

### Proposal

I hope to support webgpu and provide stronger 2D/3D capabilities. Is Flutter currently planning on this? If there is an approximate time, when can it be launched? Next year? Will WebGPU be used to replace Skits in the future to achieve higher performance?

**Comment by jonahwilliams** [comment]
WebGPU is a cross platform API for programming a GPU, while both Skia and Impeller are higher level libraries that provide 2d graphics APIs on top of some GPU abstraction layer like opengl, Vulkan, metal, or web GPU. While we have no immediate plans to add a new WebGPU backend, we're not planning on adding one in the near term.
