### ISSUE TITLE
Health_Doctor check errors that all machines macs "Device doctor tool error: b'* daemon not running"

### ISSUE THREAD

**Issue by kentnguyen99** [flutter/flutter#129361]
Health_Doctor check that all Mac machines "Device doctor tool error: b'* daemon not running"
<img width="1336" alt="Screenshot 2023-06-22 at 10 22 57 AM" src="https://github.com/flutter/flutter/assets/120754754/2bb8875d-4db9-4bf8-ac9d-27285b14a173">
<img width="1376" alt="Screenshot 2023-06-22 at 10 26 07 AM" src="https://github.com/flutter/flutter/assets/120754754/d7a9bee0-ce9d-46a6-a085-fbc5a6bf5bfb">

**Comment by kentnguyen99** [comment]
@keyonghan Can you take a look "Device doctor tool"? All the sudden all Mac machines failed with same errors.

**Comment by keyonghan** [comment]
This is a result of https://github.com/flutter/flutter/issues/100654.
https://chrome-internal-review.googlesource.com/c/infradata/config/+/6078356 to fix.

**Comment by kentnguyen99** [comment]
Hey @keyonghan, I click on the link above and don't see instructions nor steps to fix issue.  Can you share the steps how to fix issue for Mac machines?  Thanks.

**Comment by keyonghan** [comment]
That is a CL to fix from server side. All Mac_android prod bots are using `flutter_mac_android.py` config file to check bot status. The above CL excludes the quarantine scenario when `daemon not running` error returns. This is not doable from bot/lab side unfortunately.

Thanks for detecting and filing this bug @kentnguyen99 !
