### ISSUE TITLE
Images and buttons not rendering after application resumes from background on release mode

### ISSUE THREAD

**Issue by sannykhan3777** [flutter/flutter#129342]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Run on android(Real device)
It 2 pages app.
**STEPS TO REPRODUCE**
1) Clone repo https://github.com/sannykhan3777/reproduceissuerepo.git
2) Run the app using "flutter run --release" OR make release apk and install it on real device.
3) After 2 seconds wait it will go from splash to next page.
4) Click back button of mobile so that app becomes in background.
5) open the app again from background and after it will not render images and button anymore.

### Expected results

This I want. (Actually it comes on debug if I go back and come again to app but not in release)
![WhatsApp Image 2023-06-22 at 12 32 24 PM](https://github.com/flutter/flutter/assets/52849890/43b9a718-00fa-48b4-a7ad-fc8c2e2530df)

### Actual results

This is what I'm getting when I click back and app goes to background and when I open again this app in release mode on real devices.
![WhatsApp Image 2023-06-22 at 12 34 02 PM](https://github.com/flutter/flutter/assets/52849890/f8b24aed-a1e7-423d-87d7-b85df01c2cd6)

### Code sample

Clone repo https://github.com/sannykhan3777/reproduceissuerepo.git

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel unknown, 3.10.3, on Microsoft Windows [Version 10.0.22621.1848], locale en-PK)
    ! Flutter version 3.10.3 on channel unknown at C:\src\flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.78.1)
[√] Connected device (4 available)
[√] Network resources

! Doctor found issues in 2 categories.

PS: I just downgraded to 3.10.3 but same problem persist with 3.10.5 stable. I was on that channel before. Then I checkout this version just to see but not working

**Comment by hussenIbrahim** [comment]
Get.width and Get.height causing this issue , from some reason those values is Zero

**Comment by huycozy** [comment]
Hi @sannykhan3777 
In order to address the issue properly, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party packages/plugins or complex production code so that we may verify this. Thank you!

**Comment by ftprashant** [comment]
I got the same issue. Have you been able to find any solution?

**Comment by huycozy** [comment]
@ftprashant It would be helpful if you can provide a sample code as I mentioned above.

**Comment by sannykhan3777** [comment]
I found solution.
@hussenIbrahim was right.
I release mode on the first screen it was taking Get.height and Get.width = zero.
So just on first page I used  height = Mediaquery.of(context).size.height and width = Mediaquery.of(context).size.width
