### ISSUE TITLE
Couldn't save email and password to iCloud Passwords & Keychain from our App

### ISSUE THREAD

**Issue by howznguyen** [flutter/flutter#129346]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Our app is using dart (flutter) language. To apply Auto Fill to Login feature (email and password), I read the documenti from this link (https://api.flutter.dev/flutter/material/TextField/autofillHints.html). The Setup iOS app's associated domains is required so I followed step by step as the following documentation: https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_associated-domains

Firstly, I created a web association for our Project
Secondly, I put this code in `<dict>` into the file `Runner.entitlements` in our app:
```
<key>com.apple.developer.associated-domains</key>
	<array>
		<string>webcredentials:{my_web_association_domain}</string>
		<string>applinks:{my_web_association_domain}</string>
	</array>
<key>com.apple.developer.authentication-services.autofill-credential-provider</key>
<true/>
```
Next, I waited more than 24 hours and ran our app again. Our app still couldn't save passwords to your device's iCloud Passwords & Keychain even though I ran `--release` command.
My references for Set up iOS app's associated domains is:
https://developer.apple.com/documentation/xcode/supporting-associated-domains 
https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_associated-domains

Because of this problem, I also have some questions:
Is there something wrong with my iOS app's associated domains setup because I can autofill our app in Android? Could you provide me a step by step video or a file of "Autofill Services TextField for IOS" for flutter? 

### Actual results

I want to show Popup save Password after login successfull

![image](https://github.com/flutter/flutter/assets/54036529/441eb8ab-5cbc-47cc-b8d6-8b991a88ed7a)

### Flutter Doctor output
```
 [✓] Flutter (Channel unknown, 2.0.6, on macOS 13.3.1 22E772610a darwin-arm,
    locale en-US)
    • Flutter version 2.0.6 at /Users/cv16001mac/flutter
    • Framework revision 1d9032c7e1 (2 years, 2 months ago), 2021-04-29 17:37:58
      -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/cv16001mac/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 14.3, Build version 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 114.0.5735.133
```

**Comment by huycozy** [comment]
Hi @howznguyen 
The goal of this Github repo is not to give assistance on personal code or external setup but to improve Flutter framework reporting bugs or feature requests.

It seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any. And please also see flutter's [community](https://flutter.dev/community) for resources as well. 

Closing as it's not a Flutter bug or feature request. If you disagree, please write in the comments and I will reopen it.
