### ISSUE TITLE
All Mac Android bots in the Try pool are in the quarantined state preventing PR from being merged

### ISSUE THREAD

**Issue by ricardoamador** [flutter/flutter#129373]
All Mac Android Bots in the Try pool are currently quarantined which is preventing Pull Requests from being submitted.

![image](https://github.com/flutter/flutter/assets/32242716/95b5d767-b406-45e0-be23-f4d3bfc86a8c)

Specifically preventing Mac_android entrypoint_dart_registrant from running.

Related change to possibly fix this: https://chrome-internal-review.googlesource.com/c/infradata/config/+/6078356

**Comment by godofredoc** [comment]
When reviewing/landing changes to bot_config files please ensure that you are rolling in two steps: staging first, let them run for a couple of days and then roll the changes to prod.
