### ISSUE TITLE
[url_launcher_android] Generating release apk fails due to url_launcher_android artifacts/dependencies  failing to resolve

### ISSUE THREAD

**Issue by Retr0sec7** [flutter/flutter#129387]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Add url_launcher to pubsec.yaml
2. Run `flutter build apk --release`

Note: I don't understand the actual root cause of this issue. This is also happening with another package. I don't have the latest version of flutter, as it works with a newer null safety rules which impact my project and can't update it yet

### Expected results

`√  Built build\app\outputs\flutter-apk\app-release.apk (43.2MB).`

### Actual results

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':url_launcher_android:debugUnitTestRuntimeClasspath'.
   > Failed to transform bcprov-jdk18on-1.72.jar (org.bouncycastle:bcprov-jdk18on:1.72) to match attributes {artifactType=processed-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: C:\Users\Dragon\.gradle\caches\modules-2\files-2.1\org.bouncycastle\bcprov-jdk18on\1.72\d8dc62c28a3497d29c93fee3e71c00b27dff41b4\bcprov-jdk18on-1.72.jar.
         > Failed to transform 'C:\Users\Dragon\.gradle\caches\modules-2\files-2.1\org.bouncycastle\bcprov-jdk18on\1.72\d8dc62c28a3497d29c93fee3e71c00b27dff41b4\bcprov-jdk18on-1.72.jar' using Jetifier. Reason: IllegalArgumentException, message: Unsupported class file major version 59. (Run with --stacktrace for more details.)

### Code sample

None

### Screenshots or Video

No needed

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.6, on Microsoft Windows [Version 10.0.19045.3086], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.4)
[√] Android Studio (version 2022.1)
[√] VS Code (version 1.79.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @Retr0sec7 
It seems the issue is caused by Gradle. Please check answers from [this thread](https://stackoverflow.com/questions/59482329/flutter-problems-could-not-resolve-all-artifacts-for-configuration-classpath) if there is a helpful solution for your issue.
