### ISSUE TITLE
[pigeon] Autogenerated files, enums, and structs in different files

### ISSUE THREAD

**Issue by martin-headspace** [flutter/flutter#129354]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

We utilize Pigeon, a tool for generating the necessary files to facilitate communication between our Flutter app(s) and our native platforms. To achieve this, we run the following command:

```sh
flutter pub run pigeon \
            --input=lib/services_schema.dart \
            --dart_out="$output_dir/pigeon.dart" \
            --swift_out="$output_dir/pigeon.swift" \
            --kotlin_out="$output_dir/pigeon.kt"
```

The output of this operation consists of three files, each containing a comprehensive set of encoders, decoders, classes, structs, and other constructs required for seamless communication with their respective counterparts.

However, there are several compelling reasons why having all these critical constructs in a single file is problematic. Firstly, it deviates from our current directory structure, making it more challenging for our developers to navigate and comprehend the codebase effectively. 

Moreover, the practice of lumping all autogenerated constructs into one file presents a significant challenge for our InfoSec engineers and reviewers. With a monolithic file, it becomes increasingly difficult to perform targeted security audits and code reviews. The ability to isolate specific components and review them individually is vital for identifying vulnerabilities, ensuring compliance, and maintaining a robust security posture.

### Proposal

We propose the addition of a flag to the Pigeon command that enables developers to generate each enum, struct, class, and other constructs on separate files. This flag will enhance the flexibility and organization of the code generated by Pigeon.

To illustrate this proposed functionality, we suggest the following command syntax:

```sh
flutter pub run pigeon \
            --input=lib/services_schema.dart \
            --dart_out="$output_dir/pigeon.dart" \
            --swift_out="$output_dir/pigeon.swift" \
            --kotlin_out="$output_dir/pigeon.kt" \
            --separated
```

By including the --separated flag in the command, Pigeon will generate multiple files, each corresponding to a specific enum, struct, class, or other construct.

Here's a sample Pigeon schema that demonstrates the desired outcome:

```dart
import 'package:pigeon/pigeon.dart';

class Person {
  String name;
  int age;
}

@HostApi()
abstract class CommunicationHostApi {
  void sendMessage(String message);
}

@FlutterApi()
abstract class CommunicationFlutterApi {
  void receiveMessage(String message);
}
```

When the Pigeon command is executed with the --separated flag, the resulting output will include multiple files, such as:
**Person.swift**
```swift
import Foundation

class Person {
  var name: String?
  var age: Int?
}

```
**CommunicationHostApi.swift**
```swift
import Foundation

@objc
protocol CommunicationHostApi {
  func sendMessage(_ message: String)
}

```
**CommunicationFlutterApi.swift**
```swift
import Foundation

@objc
protocol CommunicationFlutterApi {
  func receiveMessage(_ message: String)
}

```

This separation of constructs into individual files improves code organization, simplifies navigation, and aligns with best practices for modularization and maintainability.

By implementing the proposed flag, developers will have more control over the generated code structure and can adapt it to their project's specific needs and directory structure.

**Comment by stuartmorgan** [comment]
> Moreover, the practice of lumping all autogenerated constructs into one file presents a significant challenge for our InfoSec engineers and reviewers. With a monolithic file, it becomes increasingly difficult to perform targeted security audits and code reviews. The ability to isolate specific components and review them individually is vital for identifying vulnerabilities, ensuring compliance, and maintaining a robust security posture.

Could you elaborate on this? The amount of code is the same regardless of the number of files, so it's not clear to me how reviewing for security vulnerabilities—which requires reviewing all of the code regardless—would be affected by the file structure.


> Here's a sample Pigeon schema that demonstrates the desired outcome:
> 
> ```dart
> import 'package:pigeon/pigeon.dart';
> 
> class Person {
>   String name;
>   int age;
> }
> 
> @HostApi()
> abstract class CommunicationHostApi {
>   void sendMessage(String message);
> }
> 
> @FlutterApi()
> abstract class CommunicationFlutterApi {
>   void receiveMessage(String message);
> }
> ```

If the goal is separation of concerns by file, why are you using a single input file for three different things? You could get the output you have shown as your desired results right now by having each of these in a separate pigeon file.
