### ISSUE TITLE
[google_sign_in] Sign in window is not clickable on some Android devices.

### ISSUE THREAD

**Issue by awfulminded** [flutter/flutter#129305]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I just installed the google sign in package. Everything works on the emulator and on some Android devices, but on a couple of those on which I tested the application, an error occurs that the google authorization pop-up screen is simply not clickable. Also, any links on it, such as privacy policy, are not clickable. At the same time, the application does not crash and continues to work after closing google auth window.

### Expected results

The google authorization window should be clickable and after selecting an account, it should authorize the user

### Actual results

Google sign in window is not clickable, even privacy policy or some other links

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:google_sign_in/google_sign_in.dart';

class GoogleSigninApi {
  static final _googleSignIn = GoogleSignIn();

  static Future<GoogleSignInAccount?> login() => _googleSignIn.signIn();
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/100774881/09cf6f90-84c8-45bb-90e8-f15d524d816c

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.10.4, on Microsoft Windows [Version 10.0.22621.819], locale ru-RU)
    • Flutter version 3.10.4 on channel stable at D:\FlutterSDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 682aa387cf (2 weeks ago), 2023-06-05 18:04:56 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\Administrator\AppData\Local\Android\Sdk
    • Platform android-33-ext4, build-tools 33.0.2
    • ANDROID_HOME = C:\Users\Administrator\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\Administrator\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code (version 1.75.0)
    • VS Code at C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.66.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.819]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 114.0.5735.134
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 114.0.1823.51

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
@awfulminded 
Can you provide device / emulator devices on which this behavior occurs ?
Also, can you try the google sign in native Android app on same device / emulator and check if you are able to tap on the elements ?

**Comment by awfulminded** [comment]
> @awfulminded Can you provide device / emulator devices on which this behavior occurs ? Also, can you try the google sign in native Android app on same device / emulator and check if you are able to tap on the elements ?

Google sign in is working properly in apk and production mode from google play store on:
Samsung A 51
Samsung Galaxy A30s
and Pixel 5 API 31 Emulator

And not working on Redmi 10C (showed in the video)

Im sorry but i dont really understand what you mean by trying google sign in in native android app

**Comment by darshankawar** [comment]
> Im sorry but i dont really understand what you mean by trying google sign in in native android app

I meant try the google sign in on same affected device (Redmi) accessing your gmail or any other Android native app that uses google sign in and see if you are able to observe same behavior or not. That way we'll come to know if the behavior is specific to Flutter's google sign-in package or happens on native app as well.
