### ISSUE TITLE
flutter start fails to log connected Android device 

### ISSUE THREAD

**Issue by paulb777** [flutter/flutter#1293]
~/flutter/flutter/my_app (alpha) $ flutter start
Downloading darwin-x64 artifacts from the cloud, one moment please...
Downloading android-arm artifacts from the cloud, one moment please...
warning: Unexpected failure parsing device information from adb output:
List of devices attached
Please report a bug at https://github.com/flutter/flutter/issues/new
Installing SkyShell.apk on device.
~/flutter/flutter/my_app (alpha) $ adb devices
List of devices attached
07e4bc510075ff5c	device

**Comment by abarth** [comment]
Thanks for the report.  /me will investigate on Tuesday.

**Comment by abarth** [comment]
Fix in https://github.com/flutter/flutter/pull/1294
