### ISSUE TITLE
iOS Simulator Crashes When Spawning New Isolate

### ISSUE THREAD

**Issue by sroddy** [flutter/flutter#12939]
## Steps to Reproduce

Related discussion here: #12526 

1) On `master` run `flutter/examples/layers/services/isolate.dart` on iPhone SE
2) Click the Start button
3) The app crashes when spawning the isolate

## Logs

Using the debugger, this is the last Dart line it manages to reach:
```Isolate.spawn(_calculate, message).then<Null>((Isolate isolate) {```
It also seems that it doesn't enter the _calculate function from the other isolate.

When I run it from console/intellij I just see a `Lost connection to device.` error.

If I try to run it from the xcode project, I receive this:
```
2017-11-09 01:49:29.252669+0100 Runner[23488:362570] Observatory listening on http://127.0.0.1:60411/
2017-11-09 01:49:34.046035+0100 Runner[23488:362585] [VERBOSE-3:dart_init.cc(350)] Check failed: Dart_IsolateMakeRunnable(isolate). 
```

I'm experiencing this same issue in alpha 0.0.17, and I'm experiencing it also in my own code every time I try to spawn an Isolate.

## Flutter Doctor
```
[✓] Flutter (on Mac OS X 10.12.6 16G1036, locale it-IT, channel master)
    • Flutter at /Users/sroddy/flutter/flutter
    • Framework revision 436aa93086 (2 hours ago), 2017-11-09 07:12:36 +0100
    • Engine revision bc2acf7bdd
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /Users/sroddy/Library/Android/sdk
    • Platform android-26, build-tools 26.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.0.1, Build version 9A1004
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.2.5)
    • Flutter plugin version 18.4
    • Dart plugin version 172.4343.25

[✓] Connected devices
    • iPhone SE • BA3ECA04-6D6A-41DE-9AB7-02CDCD6D56F1 • ios • iOS 11.0 (simulator)
```

**Comment by mit-mit** [comment]
Note: this repros on the iOS Simulator, but not on a physical iPod SE!

**Comment by mit-mit** [comment]
cc @a-siva

**Comment by sroddy** [comment]
I just realised that this bug could earn a bit more priority given the fact that:
- if you spawn an isolate, the iOS simulator instantly crashes
- if you spawn an isolate, any real iOS device doesn't crash, but it will crash as soon as you try to quick restart the app or hot-reload it.

This makes development with Isolates almost impossible (I needed to add an option in my code to run that code on the main isolate during app development)

**Comment by mit-mit** [comment]
cc @a-siva @zanderso

**Comment by abnerh69** [comment]
Hi,  I am using Simulator 10.0 (SimulatorApp-835.5)  and it crashes all flutter apps.  
on a Real Device (iPad  iOS 11.2) it runs but Hot Reload doesn't works at all.

Please, I am working on a real app (project) and finishing date to 12/31/2017.
Any advice?  Thanks.
 
Environment:

IntelliJ IDEA 2017.3 (Community Edition)
Build #IC-173.3727.127, built on November 27, 2017
JRE: 1.8.0_152-release-1024-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

flutter doctor
[✓] Flutter (on Mac OS X 10.12.6 16G1036, locale es-VE, channel alpha)
    • Flutter at /Users/abnershernandez/Development/flutter
    • Framework revision fd7853faad (8 days ago), 2017-12-05 16:12:55 -0800
    • Engine revision b57fca02b5
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.d4cfecb1065d322d3670df7e9ec9a0cc2d4b90f0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /Users/abnershernandez/Library/Android/sdk
    • Android NDK location not configured (this optional configuration is useful for native profiling support)
    • Platform android-26, build-tools 26.0.2
    • ANDROID_HOME = /Users/abnershernandez/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.1.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.3)
    • Flutter plugin version 19.1
    • Dart plugin version 173.3727.108

[✓] Connected devices
    • iPad de Pos • ab8a02b04cdb6be384d4ec6834ed88e780ec8206 • ios • iOS 11.2
    • iPad Air 2  • DC7FBCA6-91B5-43DE-BECC-A54F4E999B60     • ios • iOS 11.1 (simulator)

**Comment by mit-mit** [comment]
cc @a-siva @zanderso may be have an update, please?

**Comment by rmacnak-google** [comment]
The engine isn't loading anything into the second isolate (which is why Dart_IsolateMakeRunnable fails). Strangely, the script URI set for both the main isolate and the second isolate doesn't point to Dart source or a snapshot, but points to the asset directory on the host.

On AOT, isolates start loaded, which is why it works there.

@chinmaygarde has been looking at isolate / view lifecycles recently.

**Comment by chinmaygarde** [comment]
@rmacnak-google, @a-siva and I were looking into this the other day and it turns out that even secondary isolates need the main isolates script path to mark them as runnable. I must admit that I was unaware of this requirement for spawning isolates from source. iOS in debug is the only mode that supports running from sources which is why this issue only manifested on simulators.

@rmacnak-google has posted a patch and fixed the issue https://github.com/flutter/engine/pull/4467

Long term, https://github.com/flutter/engine/pull/4433 attempts to simplify the lifecycle management of isolates and also adds a unit test target for isolate creation. I will add a unit test for this specific case in that test harness.

**Comment by thosakwe** [comment]
So, is there currently no fix for this yet?

**Comment by sroddy** [comment]
Have you tried to run your code on master? The issue seems to be solved for me

**Comment by a-siva** [comment]
@thosakwe the issue has been resolved and closed, can you confirm if it is fixed for you on master? If you are still seeing issues send us a reproduction scenario.

**Comment by thosakwe** [comment]
Will check today... Ping me in a few hours if I haven't responded
