### ISSUE TITLE
lost connection to device when using google_maps_flutter: ^2.2.6

### ISSUE THREAD

**Issue by wahyu-handayani** [flutter/flutter#129332]
I am currently showing map in my screen using google_maps_flutter: ^2.2.6 package, but whenever I try to restart my code or reload multiple times the map screen (re-show maps screen continuously) it will get lost connection to device without any error log. It's always fine whenever load the screen for the first time, but not when 4 times or 5 times reload. Is there a way to solve this ? I have checked the configuration api key in android manifest, appdelegete.swift. Also I have done adding permission for location access inside info.plist and android manifest
I am also opening this issue in https://stackoverflow.com/questions/76528481/lost-connection-to-device-when-using-flutter-maps

**Comment by huycozy** [comment]
Hi @wahyu-handayani 
Please try to clarify the information indicated below
- Reproduction steps (please try to observe to see if it has any pattern and then provide `step by step` to reproduce it)
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example). If you can replicate the issue with one of the plugin examples [here](https://github.com/flutter/packages/tree/main/packages/google_maps_flutter/google_maps_flutter/example), please confirm.
- A demo (recorded video) would be appreciated
- The output of `flutter doctor -v`
- Which target environment did this issue happen in? (Android/iOS/..)
