### ISSUE TITLE
"Failed assertion....  In either case, please report this assertion by filing a bug on GitHub:"

### ISSUE THREAD

**Issue by Thrasherop** [flutter/flutter#129401]
Hello all! 

I recently encountered an error in my flutter application. The error said this: 

```
package:flutter/src/rendering/shifted_box.dart': Failed assertion: line 352 pos 12: 'child!.hasSize': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:

```

So here I am doing as I am told. Here is the source code file that I am working with: https://pastebin.com/jF2uVGTL 
This error goes away if I comment out the textfield widget on lines 187-189. 

According to my pubspec, I am using environment sdk version `environment: sdk: '>=2.18.1 <3.0.0'`.

I know it is a little out of date, so I apologize if it has been fixed. I don't have time to upgrade and test if it still exists, but I didn't want to just leave this bug unmentioned.

**Comment by huycozy** [comment]
Hi @Thrasherop 
Your pastebin link is not found. Please try to provide the minimal and complete sample code so that we may verify the issue properly. And please provide the output of `flutter doctor -v` as well. Thanks!
