### ISSUE TITLE
[Impeller] Vulkan swapchain recreation is incorrect when rotating screen.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#129459]
![flutter_01](https://github.com/flutter/flutter/assets/8975114/e56ba806-7629-4c7c-bd3e-79a2eb154113)

**Comment by jonahwilliams** [comment]
```
I/ViewRootImpl@def1a0[MainActivity](19287): MSG_RESIZED_REPORT: frame=(112,0,2280,1080) ci=(0,63,126,0) vi=(0,63,126,0) or=2
I/ViewRootImpl@def1a0[MainActivity](19287): MSG_RESIZED_REPORT: frame=(112,0,2280,1080) ci=(0,63,126,0) vi=(0,63,126,0) or=2
E/flutter (19287): [ERROR:flutter/impeller/base/validation.cc(49)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not present queue: SuboptimalKHR
I/ViewRootImpl@def1a0[MainActivity](19287): ViewPostIme pointer 0
E/flutter (19287): [ERROR:flutter/impeller/base/validation.cc(49)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not present queue: SuboptimalKHR
E/flutter (19287): [ERROR:flutter/impeller/base/validation.cc(49)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not present queue: SuboptimalKHR
E/flutter (19287): [ERROR:flutter/impeller/base/validation.cc(49)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not present queue: SuboptimalKHR
E/flutter (19287): [ERROR:flutter/impeller/base/validation.cc(49)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not present queue: SuboptimalKHR
E/flutter (19287): [ERROR:flutter/impeller/base/validation.cc(49)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not present queue: SuboptimalKHR
E/flutter (19287): [ERROR:flutter/impeller/base/validation.cc(49)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not present queue: SuboptimalKHR
E/flutter (19287): [ERROR:flutter/impeller/base/validation.cc(49)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not present queue: SuboptimalKHR
E/flutter (19287): [ERROR:flutter/impeller/base/validation.cc(49)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not present queue: SuboptimalKHR
E/flutter (19287): [ERROR:flutter/impeller/base/validation.cc(49)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not present queue: SuboptimalKHR
E/flutter (19287): [ERROR:flutter/impeller/base/validation.cc(49)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not present queue: SuboptimalKHR
E/flutter (19287): [ERROR:flutter/impeller/base/validation.cc(49)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not present queue: SuboptimalKHR
E/flutter (19287): [ERROR:flutter/impeller/base/validation.cc(49)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not present queue: SuboptimalKHR
E/flutter (19287): [ERROR:flutter/impeller/base/validation.cc(49)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not present queue: SuboptimalKHR

```

**Comment by dnfield** [comment]
based on https://community.khronos.org/t/vk-suboptimal-khr-is-it-safe-to-use-it-as-window-resize-detection/107848 it looks like this happens when the surface properties change so this is expected?

**Comment by jonahwilliams** [comment]
Handling the rotation change and recreating the swapchain is easy enough, however there seem to be two caveats:

* We also need to take the transform and plumb it through to the CTM for rendering to be correct.
* Rotating back to portrait doesn't seem to always trigger the suboptimalkhr which means we might need to poll.

**Comment by chinmaygarde** [comment]
The expectation was that we wouldn't be in the business of figuring that out post acquisition. If the surface is suboptimal, just treat the `present` result as a success. There is going to be another frame incoming shortly anyway where the `AcquireNextDrawable` call will fail and the swapchain impl recreated.

Perhaps the fix is as simple as just adding a fallthrough in the present that returns success?

**Comment by jonahwilliams** [comment]
xref: https://developer.android.com/games/optimize/vulkan-prerotation

**Comment by matanlurey** [comment]
Discussed with @jonahwilliams this AM.

This problem still persists, because `VK_SUBOPTIMAL_KHR` is provided inconsistently (it only works at _all_ on Android 10+, and there are reports that some devices that _should_ support this enum do not). To focus on fidelity over performance at the moment, we're likely going to adopt [polling](https://developer.android.com/games/optimize/vulkan-prerotation#using_polling) - in the future we'll want to pre-rotate images (https://github.com/flutter/flutter/issues/129580).

**Comment by matanlurey** [comment]
FYI it appears to work fine on a Pixel 5, I might need to use a Samsung phone to see this particular issue?

**Comment by matanlurey** [comment]
@htoor3 I think you accidentally re-closed this?

**Comment by htoor3** [comment]
@matanlurey hmm that's strange, that was definitely not on purpose! It appears that I updated my fork of the engine and GH automations auto closed the issue?
