### ISSUE TITLE
Snap and Raspberry Pi 4

### ISSUE THREAD

**Issue by AllyTechEngineering** [flutter/flutter#129449]
Hi, the directions for installing flutter using snap are missing one important step: when you setup your Raspberry Pi 4 the default OS is 32bit. Maybe I missed it but I did not see that in the instructions. After doing a Google search I found out that you need the 64bit OS. My suggestion would be to add that in your "how to" so that others don't get confused. 

Thanks!

**Comment by darshankawar** [comment]
@AllyTechEngineering 


> the directions for installing flutter using snap are missing one important step:

Can you provide us the link / documentation you are referring to ?

**Comment by AllyTechEngineering** [comment]
Hi, https://snapcraft.io/install/flutter/raspbian  unless I missed it, there is no mention of Debian 11 for 64 bit ARM

**Comment by darshankawar** [comment]
Thanks for the link @AllyTechEngineering 
I think you'll need to report this in one of the links they mentioned:

<img width="680" alt="Screenshot 2023-06-29 at 11 16 50 AM" src="https://github.com/flutter/flutter/assets/67046386/a193ff1a-02cd-4f17-9c9b-192e7d336c03">

Closing from here.
