### ISSUE TITLE
Firestore crashes with signal 6 (SIGABRT)

### ISSUE THREAD

**Issue by lschmierer** [flutter/flutter#12945]
## Steps to Reproduce

The line
```Dart
final users = await Firestore.instance.collection('users').snapshots.first;
```
lets my application crash with signal 6 (SIGABRT).

The strange thing is that the same code seemed to have worked a few days ago.
I am pretty much sure that I have not changed anything in the meantime (like upgrading Flutter or upgrading packages, etc.).

## Logs
`flutter run`:
```
F/flutter (12329): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(34)] Check failed: env->ExceptionCheck() == JNI_FALSE. 
F/libc    (12329): Fatal signal 6 (SIGABRT), code -6 in tid 12329 (nuzzle.snuzzle3)
```

`flutter analyze` reports no issues.

## Flutter Doctor
```
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-DE, channel master)
    • Flutter at /Users/lschmierer/flutter
    • Framework revision 436aa93086 (9 hours ago), 2017-11-09 07:12:36 +0100
    • Engine revision bc2acf7bdd
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /Users/lschmierer/Library/Android/sdk
    • Platform android-26, build-tools 26.0.2
    • ANDROID_HOME = /Users/lschmierer/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.2.5)
    • Flutter plugin version 18.1
    • Dart plugin version 172.4155.35

[✓] Connected devices
    • Pixel • FA69N0312108 • android-arm • Android 8.0.0 (API 26)
```

**Comment by eseidelGoogle** [comment]
I believe that occurs when there is an exception on the Java side.  I'm sorta surprised we don't log more.  @collinjackson or @kroikie might know.

**Comment by eseidelGoogle** [comment]
With regards to exception messages, it looks like https://github.com/flutter/flutter/pull/12938 might be improving things.

**Comment by jason-simmons** [comment]
That assertion corresponds to FlutterView.handlePlatformMessage throwing an exception while receiving a message sent from Dart to the native platform code.

FlutterView.handlePlatformMessage should catch exceptions thrown by plugin Java code.  However, one case where it will throw is if the FlutterView has been detached by the time the platform message arrives.

What state is the application in when this happens?  Is it running in steady state or has it been paused or moved to the background?

Possibly FlutterView should just log and return an empty response if it received a platform message while detached.

**Comment by lschmierer** [comment]
This happens in the state of normal execution.
I am calling it in `initState()`.

I tried to reproduce the issue, but in a clean new project it seems to work as expected.

**Comment by lschmierer** [comment]
It turns out that this error occurs when the `firestore` pllugin is used together with the `firebase_auth` plugin.

Following app demonstrates the issue: https://github.com/lschmierer/flutter_test

**Comment by jason-simmons** [comment]
The example throws an exception with this stack:
```
java.lang.NoSuchMethodError: No static method zzb(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzbp; or its super classes (declaration of 'com.google.android.gms.common.internal.zzbp' appears in /data/app/yourcompany.com.flutterapp-2/base.apk)
[        ] I/flutter ( 9767):   at com.google.firebase.firestore.FirebaseFirestore.zze(Unknown Source)
[        ] I/flutter ( 9767):   at com.google.firebase.firestore.FirebaseFirestore.getInstance(Unknown Source)
[        ] I/flutter ( 9767):   at io.flutter.plugins.firebase.cloud_firestore.CloudFirestorePlugin.getCollectionReference(CloudFirestorePlugin.java:51)
[        ] I/flutter ( 9767):   at io.flutter.plugins.firebase.cloud_firestore.CloudFirestorePlugin.getQuery(CloudFirestorePlugin.java:60)
[        ] I/flutter ( 9767):   at io.flutter.plugins.firebase.cloud_firestore.CloudFirestorePlugin.onMethodCall(CloudFirestorePlugin.java:143)
[        ] I/flutter ( 9767):   at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
[        ] I/flutter ( 9767):   at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:113)
[        ] I/flutter ( 9767):   at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] I/flutter ( 9767):   at android.os.MessageQueue.next(MessageQueue.java:323)
[        ] I/flutter ( 9767):   at android.os.Looper.loop(Looper.java:136)
[        ] I/flutter ( 9767):   at android.app.ActivityThread.main(ActivityThread.java:6121)
[        ] I/flutter ( 9767):   at java.lang.reflect.Method.invoke(Native Method)
[        ] I/flutter ( 9767):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
[        ] I/flutter ( 9767):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

```
This happens due to version skew between the libraries linked by the firebase_auth plugin and the cloud_firestore plugin.

You can work around this by patching the firebase_auth plugin to request version 11.4.+ of the Firebase library dependencies in order to match cloud_firestore.

**Comment by bjornbjorn** [comment]
I'm still getting the SIGABRT fatal crash on Android using these packages:

```
  firebase_auth: "0.3.1"
  cloud_firestore: "0.0.4"
  firebase_analytics: "0.1.1"
  # The following are required for Auth
  google_sign_in: "1.0.1"
  flutter_webview_plugin: "0.0.9"
  flutter_facebook_connect: "0.0.3"
```
The only one updated recently is cloud_firestore (0.0.4). Is this fix not out yet in the various packages - or do we need to do something else to fix this?

**Comment by mit-mit** [comment]
Just took at quick look at https://storage.googleapis.com/pub-packages/packages/firebase_auth-0.3.1.tar.gz, and that still has:
```
        compile 'com.google.firebase:firebase-core:11.+'
        compile 'com.google.firebase:firebase-auth:11.+'
```

Re-opening but: @jason-simmons can we please get all these published to pub? (Also need to get changelog.md's updated)

**Comment by mit-mit** [comment]
cc @collinjackson can we get all Firebase plugins published in versions using the same compile dependency?

**Comment by collinjackson** [comment]
I'll do it. Thanks!

**Comment by TobiasBales** [comment]
Any updates on this?

**Comment by zoechi** [comment]
Just a thought.

What about creating an artificial pub package for GMS with a new version for each GMS version, 
and add it as dependency to all plugins?

This way `flutter packages upgrade` would produce an error about incompatible dependencies
if the used plugins don't depend on the same GMS version.

A downside is that `pub` currently doesn't produce good errors for conflicts.

**Comment by asaarnak** [comment]
`"Multiple dex files define Lcom/google/android/gms/internal/zzdyr;"`
This error appeared for me using `firebase_database`
The temporary workaround that fixed the issue for me.
Modified [firebase_database/android/build.gradle#L33-L35](https://github.com/flutter/plugins/blob/master/packages/firebase_database/android/build.gradle#L33-L35) in `/home/user/.pub-cache/hosted/pub.dartlang.org/firebase_database-0.1.4/android/build.gradle:38`
```
dependencies {
        compile 'com.google.firebase:firebase-core:11.+'
        compile 'com.google.firebase:firebase-auth:11.+'
        compile 'com.google.firebase:firebase-database:11.+'
}
```

**Comment by baksoy** [comment]
Here's a combo that worked for me:

```
  google_sign_in: 0.3.1
  firebase_analytics: 0.0.4
  firebase_auth: 0.2.0
  firebase_database: 0.1.3
  firebase_storage: 0.0.5
```
Also, go into Flutter Plugins - firebase_auth - android - build.gradle and change to 	

```
dependencies {
        compile 'com.google.firebase:firebase-core:11.+'
        compile 'com.google.firebase:firebase-auth:11.+'
    }
```
 Do the same for firebase_database and firebase_storage. 

After trying several combinations, this is what worked for me for both iOS and Android.

**Comment by bjornbjorn** [comment]
FWIW here's what worked for me:

```
  google_sign_in: "1.0.1"
  flutter_webview_plugin: "0.0.9"
  flutter_facebook_connect: "0.0.3"
  firebase_auth: "0.3.1"
  cloud_firestore: "0.0.4"
```
And then modifying firebase_auth-0.3.1 package to use the same firebase-core versions as cloud_firestore:

**~/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.3.1/android/build.gradle**

```
 dependencies {
        compile 'com.google.guava:guava:20.0'
        compile 'com.google.firebase:firebase-core:11.+'
        compile 'com.google.firebase:firebase-auth:11.+'
    }
```

**Comment by lschmierer** [comment]
@asaarnak @baksoy @bjornbjorn It is much easier if you just use latest (unpublished) version directly from the git repo.
Just stick to some commit hash where the firebase dependencies are compatible.

I am using e.g.
```
  firebase_auth:
    git:
      url: https://github.com/flutter/plugins.git
      ref: 098161db7de5935e82e8ec0d61cea2c795cd0377
      path: packages/firebase_auth
  cloud_firestore:
    git:
      url: https://github.com/flutter/plugins.git
      ref: 098161db7de5935e82e8ec0d61cea2c795cd0377
      path: packages/cloud_firestore
```

**Comment by kroikie** [comment]
@lschmierer

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/944. Any further collaboration will be done there.
