### ISSUE TITLE
[image_picker] Provide max limit for number of images

### ISSUE THREAD

**Issue by madicd** [flutter/flutter#129443]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Our use case requires the user to select maximum 5 images.
We support Android, iOS and Windows.

### Proposal

```
await picker.pickMultiImage(maxImageCount: 5)
```

**Comment by stuartmorgan** [comment]
Duplicate of https://github.com/flutter/flutter/issues/85772
