### ISSUE TITLE
Got `Missing Xcode dependency: Python module "six".` when launch.

### ISSUE THREAD

**Issue by kyleduo** [flutter/flutter#12947]
## Steps to Reproduce

I've installed flutter SDK and Python module "six", but when I execute `flutter doctor` ro `flutter run` in command line. I got this error message:

```
➜  myapp flutter run -d E2710BE3-F621-4DBB-9121-33814113E1D3

Launching lib/main.dart on iPhone X in debug mode...
Missing Xcode dependency: Python module "six".
Install via 'pip install six' or 'sudo easy_install six'.
Could not build the application for the simulator.
Error launching application on iPhone X.
```

**BUT** I can successfully launch the `myapp` project in intellij IDEA.

## Logs

```
➜  myapp flutter run -d E2710BE3-F621-4DBB-9121-33814113E1D3

Launching lib/main.dart on iPhone X in debug mode...
Missing Xcode dependency: Python module "six".
Install via 'pip install six' or 'sudo easy_install six'.
Could not build the application for the simulator.
Error launching application on iPhone X.
```

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.13.1 17B48, locale zh-Hans-CN, channel alpha)
    • Flutter at /Users/kyle/github/flutter
    • Framework revision e8aa40eddd (3 weeks ago), 2017-10-17 15:42:40 -0700
    • Engine revision 7c4142808c
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /Users/kyle/Documents/developer/sdk
    • Platform android-26, build-tools 26.0.2
    • ANDROID_HOME = /Users/kyle/Documents/developer/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[-] iOS toolchain - develop for iOS devices (Xcode 9.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.1, Build version 9B55
    ✗ Missing Xcode dependency: Python module "six".
      Install via 'pip install six' or 'sudo easy_install six'.
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 18.4
    • Dart plugin version 172.3317.48

[✓] Connected devices
    • ONEPLUS A3010 • 64e8ab32                             • android-arm • Android 8.0.0 (API 26)
    • iPhone X      • E2710BE3-F621-4DBB-9121-33814113E1D3 • ios         • iOS 11.1 (simulator)
```

**Comment by eseidelGoogle** [comment]
Doctor is saying:
```
 ✗ Missing Xcode dependency: Python module "six".
      Install via 'pip install six' or 'sudo easy_install six'.
```

I believe this happens when having a non-default python in your path (which doesn't already have module `six` installed).

**Comment by kyleduo** [comment]
@eseidelGoogle Thanks for your answer and you are right. I've both python 3.5 and python 3.6 installed and problem solved after I uninstall them and reinstall python 3.6 again.

**Comment by KamalPatra** [comment]
@kyleduo  How you did that? I am facing the same problem
[!] iOS toolchain - develop for iOS devices (Xcode 9.3)
    ✗ Missing Xcode dependency: Python module "six".
      Install via 'pip install six' or 'sudo easy_install six'.

**Comment by wonkim** [comment]
Please try:
brew reinstall python@2
pip install six

**Comment by pedro-marques** [comment]
@wonkim solution fixed it for me, thanks.

**Comment by hanson1024** [comment]
@wonkim show error 
Traceback (most recent call last):
File "/home/XXXX/bin/pip", line 7, in <module>
    from pip import main
  File "/home/XXXX/local/lib/python2.7/site-packages/pip/__init__.py", 
line 5, in <module>
    import logging
  File "/usr/lib/python2.7/logging/__init__.py", line 26, in <module>
    import sys, os, time, cStringIO, traceback, warnings, weakref, 
collections
  File "/home/XXXX/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref

solution : 
If you're on OSX and are using homebrew, check your packages installed with brew by running brew list, and if "python@2" appears in that list, and Python 2.7 is your system Python, you can remove the brew installed package with "brew remove python@2 --ignore-dependencies"

[python2.7 broken by weakref import error, please help!](https://askubuntu.com/questions/981663/python2-7-broken-by-weakref-import-error-please-help)

**Comment by mindfocus** [comment]
> pip3 install six
works for me on macOs

**Comment by KamalPatra** [comment]
Thanks for the solution but I already did it and it worked.. Thanks again!!
