### ISSUE TITLE
issues on step 02

### ISSUE THREAD

**Issue by arnopash** [flutter/flutter#129423]
Hello! Trying to take the lesson "Get to know Firebase for Flutter" [(here),](https://firebase.google.com/codelabs/firebase-get-to-know-flutter#3) but receive some strange issues.

Right after configuring flutterfire and creation of firebase_options.dart file, the app stops working. On iOS emulator, it is now infinitely tries to launch the app, while keeps showing me "Running pod install".

![Image 23 06 23 at 15 53](https://github.com/flutter/flutter/assets/123197573/f166f801-5346-4ad2-a9a4-9f282a8be054)

When I try to run it on Android emulator, I receive the following error right after "Running Gradle task 'assembleDebug'":

Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
main.dart:1

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mapDebugSourceSetPaths'.
> Error while evaluating property 'extraGeneratedResDir' of task ':app:mapDebugSourceSetPaths'
   > Failed to calculate the value of task ':app:mapDebugSourceSetPaths' property 'extraGeneratedResDir'.
      > Querying the mapped value of provider(java.util.Set) before task ':app:processDebugGoogleServices' has completed is not supported

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Exception: Gradle task assembleDebug failed with exit code 1
Exited

The code itself, compared to the files in the git repository, are exactly the same.
I am almost sure that I am doing something wrong, but I cannot find what exactly. Already tried to do the same process 6 times, all with the same issues. Please help to point me what exactly I am doing wrong... Maybe any additional info needed from my side to provide?
Thanks in advance!

P.S. Please be noted that I am a newbie and just started to learn:)

**Comment by darshankawar** [comment]
@arnopash 
Can you try [this](https://github.com/flutter/flutter/issues/126914#issuecomment-1549852896) and see if it helps in your case ?

**Comment by darshankawar** [comment]
Closing as resolved.
