### ISSUE TITLE
[ios] http connection issue: nw_path_necp_check_for_updates Failed to copy updated result (22) 

### ISSUE THREAD

**Issue by delfme** [flutter/flutter#129454]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Since upgrading to master 3.12.0-7.0.pre.22, we are facing issue with http connection.

To reproduce:
1) create a CupertinoClient as per code below
2) make http connection to whatever web api

http client will stall and console will print this error:
 nw_path_necp_check_for_updates Failed to copy updated result (22) 

It seems this issue occurred also in the past, maybe a regression?
https://github.com/flutter/flutter/issues/111940

### Expected results

http connection should work.

### Actual results

Http connection stall every few minutes and client cannot fetch remote data.

### Code sample

<details><summary>Code sample</summary>

Code is simple, as per instructions from http package Readme.
Use below `ConnectionService.client` to call whatever rest api on iOS.
Note: we needed to use CupertinoClient coz connectivity with standard dart client was pretty unstable.

```dart

class ConnectionService {
  static const String _debugPrefix = 'ConnectionService:';

  static final config = URLSessionConfiguration.ephemeralSessionConfiguration()
    ..allowsCellularAccess = false
    ..allowsConstrainedNetworkAccess = false
    ..allowsExpensiveNetworkAccess = false;

  // Initialize client. It will be CupertinoClient on iOS and IOClient on android
  static dynamic client = (Platform.isIOS) ? CupertinoClient.fromSessionConfiguration(config)
      : IOClient();
```

</details>

### Logs

<details><summary>Logs</summary>
Error from console is:
```console
 nw_path_necp_check_for_updates Failed to copy updated result (22) 
```

Note: we have this issue with both cupertino_http:  1.0.0 and 0.1.2

</details>

### Flutter Doctor output

[✓] Flutter (Channel master, 3.12.0-7.0.pre.22, on macOS 12.6.5 21G531 darwin-arm64, locale en-IT)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] Connected device (3 available)
[✓] Network resources

**Comment by darshankawar** [comment]
@delfme 
Looking at the error and code sample, I think it is best to be reported in https://github.com/dart-lang/http/issues.
See some issues from that repo for reference: https://github.com/dart-lang/http/issues?q=is%3Aissue+CupertinoClient+is%3Aopen+

Closing from here. If you disagree, write in comments and I'll reopen it.

**Comment by delfme** [comment]
@darshankawar thx for reviewing this. Opened issue there
