### ISSUE TITLE
Proposal to add `flutter duplicate` command. 

### ISSUE THREAD

**Issue by bdytx5** [flutter/flutter#129492]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Use case:
JUST A HEADS UP: i know this command is not needed in an ideal world and probably goes against a lot of the goals of this project. The truth is that ios and android change at a pace that is much faster than the flutter community can adapt to. This command works like magic for me in my debugging process. Read with an open mind and imagine the potential time savings and issue reduction potential :) 

I am facing a problem where I need to test broken Flutter projects and diagnose their issues. I need a solution that allows me to create a duplicate project where I can isolate potential strange errors that results from platform specific issues (ios strange xcode bugs as well as android bugs).

Problem description:
The current process of testing broken Flutter projects requires manual duplication of the project, copying relevant files, and modifying configurations. This process is time-consuming and error-prone, as it involves multiple manual steps. Moreover, there is no built-in tool or command in Flutter specifically designed for creating duplicate projects for diagnostic purposes.

Alternative solutions:
I have explored various approaches to testing broken Flutter projects, such as manually duplicating the project directory, creating a new project from scratch. However, these approaches are not efficient and often require manual intervention, which can lead to errors and inconsistencies.

### Proposal
[example covers most ios, but I am less familar with android] 
I propose adding a new command, flutter duplicate, to the Flutter toolset. This command would allow developers to quickly create a duplicate project for diagnostic purposes. The flutter duplicate command would take two command line arguments: the source directory (SRC_DIR) and the destination directory (DST_DIR).

Upon executing the flutter duplicate command, it would perform the following steps:

1. Create a new Flutter project in the destination directory with the same name as the source directory.
2. Copy all files and directories from the source directory to the new project directory, excluding the ios, and android directories.
3. Copy the contents of the lib directory from the source directory to the new project's lib directory.
4. Overwrite the iOS Podfile and Info.plist files in the new project with those from the source directory.
5. Overwrite the pubspec.yaml file in the new project with the one from the source directory.
6. The proposed flutter duplicate command would serve as a diagnostic tool, allowing developers to create a duplicate project specifically for testing and analyzing broken code. It would streamline the process of setting up a test environment and enable developers to safely experiment and diagnose issues without impacting the original project.

This feature is unique in its diagnostic focus, and I have not found any existing packages on pub.dev/flutter that offer similar functionality.

Thank you for considering this proposal. I believe that adding the flutter duplicate command to the Flutter toolset would significantly improve the diagnostic capabilities for testing broken Flutter projects.

HERE IS A SAMPLE SCRIPT 

```shell
#!/bin/bash

# Source and destination directories as command line arguments
SRC_DIR=$1
DST_DIR=$2

# Flutter project name will be the same as the source directory name
PROJECT_NAME=$(basename $SRC_DIR)

# Make sure the destination directory exists
mkdir -p $DST_DIR

# Change to the destination directory
cd $DST_DIR

# Create a new Flutter project with the same name
flutter create $PROJECT_NAME

# Change to the new project directory
cd $PROJECT_NAME

# Overwrite the lib directory and copy other directories at the same level
rsync -av --exclude=ios --exclude=android --exclude=lib $SRC_DIR/ .

# Copy the lib directory
cp -R $SRC_DIR/lib/* lib/

# Overwrite iOS Podfile and Info.plist
cp $SRC_DIR/ios/Podfile ios/
cp $SRC_DIR/ios/Runner/Info.plist ios/Runner/

# Overwrite pubspec.yaml
cp $SRC_DIR/pubspec.yaml .

echo "Script execution finished successfully."
```

**Comment by bdytx5** [comment]
`#!/bin/bash

# Source and destination directories as command line arguments
SRC_DIR=$1
DST_DIR=$2

# Flutter project name will be the same as the source directory name
PROJECT_NAME=$(basename $SRC_DIR)

# Make sure the destination directory exists
mkdir -p $DST_DIR

# Change to the destination directory
cd $DST_DIR

# Create a new Flutter project with the same name
flutter create $PROJECT_NAME

# Change to the new project directory
cd $PROJECT_NAME

# Overwrite the lib directory and copy other directories at the same level
rsync -av --exclude=ios --exclude=android --exclude=lib $SRC_DIR/ .

# Copy the lib directory
cp -R $SRC_DIR/lib/* lib/

# Overwrite iOS Podfile and Info.plist
cp $SRC_DIR/ios/Podfile ios/
cp $SRC_DIR/ios/Runner/Info.plist ios/Runner/

# Overwrite pubspec.yaml
cp $SRC_DIR/pubspec.yaml .

echo "Script execution finished successfully."
`

**Comment by darshankawar** [comment]
Thanks for the report and proposal @bdytx5 
Can you take a look at [this](https://stackoverflow.com/questions/65989116/how-to-duplicate-my-own-created-flutter-project-with-new-one) link and see if it helps to serve your purpose ?

**Comment by bdytx5** [comment]
im not sure my proposal is quite the same. I imagine a command that primarily focuses on copying dart specific files, along with necessary native settings/plist's/yaml's and leaving out any other native files that could be causing issues. But i would have to go into their code to see exactly what is being copied

**Comment by darshankawar** [comment]
Thanks for the update. Keeping this issue open for team's input on proposal.

**Comment by christopherfujino** [comment]
@bdytx5 would copying the whole project dir, deleting platform specific directories, and then running a fresh `flutter create .` on the project do this? Or are you wanting to preserve certain platform config files from the source project? And if so, which files?

**Comment by bdytx5** [comment]
certain configs related to device permission (eg info.plist) as well as things like the Podfile are important. Just basically the minimal amount of config files to get the project to run. The idea is to get a refreshed set of build files/generated files that normally cause strange errors.

**Comment by AlexV525** [comment]
That would be nice if it's a Dart CLI plugin, then you can call it like `flutter_duplicate` and you'll get better maintainance. Integrating this feature into flutter_tools seems to be a little bit of overhead IMO.

**Comment by christopherfujino** [comment]
> certain configs related to device permission (eg info.plist) as well as things like the Podfile are important. Just basically the minimal amount of config files to get the project to run. The idea is to get a refreshed set of build files/generated files that normally cause strange errors.

I'm sorry, I don't think we would implement this as is. Unfortunately I don't know of a fool-proof, reliable way to differentiate which files we should regenerate, and which to preserve as user configurable. I think we would need to be able to determine that, in order to consider this proposal.
