### ISSUE TITLE
[Firebase] [Kotlin] Problem with Kotlin compilation (Apk crashes on start)

### ISSUE THREAD

**Issue by Vlxdi** [flutter/flutter#129494]
Hi, Flutter team!

I've recently have experienced an issue with my project. My build APK isn't opening on my phone properly. Whenever I tap the app icon, it opens for a moment and then crashes immediately. Additionally, when I run the command `flutter build apk --release` in the console, I receive several errors indicating a problem with the Kotlin version.

The error:

`C:/Users/�����/.gradle/caches/transforms-3/99c39af4f8a8c6bb15f38e76173c7613/transformed/jetified-firebase-analytics-ktx-21.3.0-api.jar!/META-INF/java.com.google.android.libraries.firebase.firebase_analytics_ktx_granule.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
FAILURE: Build failed with an exception.* 
What went wrong :Execution failed for task ':app:compileReleaseKotlin'.`

I use Firebase, which has something to do with the kotlin, therefore both make up the error, I've tried deleting the .gradle cache multiple times, as well as running ` flutter clean` and rebuilding the apk. The program runs in a web browser without issues. Moreover, for some reason it says in the error "The binary version of its metadata is 1.8.0, expected version is 1.6.0.", EVEN though my `ext.kotlin_version` is set to `1.8.0` which is the version wanted from the metadata.

Here are my gradle files
[app_build.gradle.txt](https://github.com/flutter/flutter/files/11858101/app_build.gradle.txt)
[build.gradle.txt](https://github.com/flutter/flutter/files/11858102/build.gradle.txt)

Please write me if you need any additional information that I can provide you with.

**Comment by darshankawar** [comment]
@Vlxdi 
I think this is similar to already open issue you filed : https://github.com/flutter/flutter/issues/129369, so let's track in that instead of creating duplicate ones.
Closing this as such.
