### ISSUE TITLE
Back arrow icon broken on iOS

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#12943]
## Steps to Reproduce

Add the following to `main.dart`:

```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: new Page1(),
    );
  }
}

class Page1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text('Page 1'),
      ),
      body: new Center(
        child: new RaisedButton(
          onPressed: () {
            Navigator.of(context).push(
              new MaterialPageRoute(builder: (BuildContext context) {
                return new Page2();
              }),
            );
          },
          child: new Text('Go to page 2'),
        ),
      ),
    );
  }
}

class Page2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text('Page 2'),
      ),
    );
  }
}
```

1. Run on Android
   => App behaves as expected

1. Run on iOS
  => After clicking the 'Page 2' button to navigate to Page2, get a page with a broken icon for the back arrow

   ![image](https://user-images.githubusercontent.com/13644170/32608655-5888b576-c55d-11e7-915c-96cea92d5015.png)

**Comment by mit-mit** [comment]
cc @Hixie, am I doing something wrong, or is this really broken?

**Comment by eseidelGoogle** [comment]
Does your pubspec.yaml have uses_material_design: true or whatever the modern equivalent is?

@xster might know.  This doesn't look like https://github.com/flutter/flutter/issues/12739, so likely just the material font is not being included in your app.

**Comment by mit-mit** [comment]
Yes, `pubspec.yaml` has `uses-material-design: true`

**Comment by Hixie** [comment]
Top of tree?

**Comment by Hixie** [comment]
If this affects iOS uniformly then this is a critical regression, so marking TODAY until we know for sure that it isn't.

**Comment by xster** [comment]
I'll check it out

**Comment by xster** [comment]
It's what I was suspecting. The glyphs' codepoints all changed in a new font .ttf but our mapping wasn't updated. There's probably a lot more icons broken.

**Comment by xster** [comment]
Was updated in #12876. We need to run the script.

**Comment by xster** [comment]
Ummmm actually not as simple as re-running the script. It seems like between our last font update to now, the material icons repo trimmed their .ttf by 7kBs and ~50 glyphs are gone. So not only codepoints changed, the glyph isn't even in the font anymore. 

It's a non-backward compatible change.
