### ISSUE TITLE
Engine try jobs failing to fetch cloudkms key for codesigning

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#129458]
On engine PR: https://github.com/flutter/engine/pull/43157/checks?check_run_id=14515251392

The LUCI build: https://ci.chromium.org/p/flutter/builders/try/Linux%20mac_android_aot_engine/3979?

Has several failing sub-builds, which failed to access the cloudkms key for https://ci.chromium.org/p/flutter/builders/try/Mac%20Engine%20Drone/245677?

**Comment by christopherfujino** [comment]
LUCI thinks this was a release branch because the branch name started with `flutter-`: https://flutter.googlesource.com/recipes/+/refs/heads/main/recipe_modules/repo_util/api.py#514

**Comment by christopherfujino** [comment]
We're pattern matching on all the outputs of https://flutter.googlesource.com/recipes/+/refs/heads/main/recipe_modules/repo_util/api.py#325

`git branch -a --contains $COMMIT`

Which will include the name of the feature branch. I think the fix would be to filter out branch refs that don't start with `remotes/origin/`

**Comment by godofredoc** [comment]
Fix: https://flutter-review.googlesource.com/c/recipes/+/46480

**Comment by ricardoamador** [comment]
@godofredoc can you take another look at this. Looks like there is a permissions issue again.
https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20mac_host_engine/12739/overview

**Comment by godofredoc** [comment]
Validated with https://github.com/flutter/engine/pull/43157/checks?check_run_id=14571245760 that https://flutter-review.googlesource.com/c/recipes/+/46480 fixes the issue.
