### ISSUE TITLE
[Impeller] Swapchain acquisition can time out on S10.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#129461]
Noticed on wonderous when opening the menus.

**Comment by jonahwilliams** [comment]
maybe we should treat this error condition similar to an out of date result.

**Comment by chinmaygarde** [comment]
What is the error code returned? Presumably, this is on the `acquireNextImage` call?

**Comment by jonahwilliams** [comment]
eTimeout on acquireNextImage

**Comment by chinmaygarde** [comment]
Hmm, [we specify an infinite timeout on that call](https://github.com/flutter/engine/blob/a9f446e25f0c0f092d8a0f5cdb1024967989c660/impeller/renderer/backend/vulkan/swapchain_impl_vk.cc#L336). So didn't think this could happen. Reading up on the spec.

**Comment by chinmaygarde** [comment]
Ok, [this answer seems to be instructive](https://stackoverflow.com/a/52670291).

**Comment by jonahwilliams** [comment]
I guess this was running on my concurrent encode patch, and in theory we could definitely exhaust the swapchain images there...

**Comment by chinmaygarde** [comment]
Closing this for now but we can re-open when we move present to its own thread.
