### ISSUE TITLE
There's a problem with the web view you've created

### ISSUE THREAD

**Issue by hg096** [flutter/flutter#129503]
https://pub.dev/packages/webview_flutter/example

First, I showed you the example code here, but I lacked a lot of tutorials and I lacked how to debug it debug. I tried googling by myself to solve this problem, but in the webview tutorial where I googled and get answers, it was just how to use the webview that was judged to be the previous version. The guidelines for using Webview are very, very unfriendly, the related updates are too fast, and the usage method is also unfriendly, so we are unable to use the package. I hope you will understand and accept the problem in this area seriously.

**Comment by darshankawar** [comment]
@hg096 
It is not clear to me what exactly are the issue you are reporting against the package. Can you elaborate by providing actual issue or error you are facing ? A code sample using the package, platform on which you are seeing any problems with it would be helpful to properly address the issue.
