### ISSUE TITLE
Flutter Android plugin add ml model

### ISSUE THREAD

**Issue by dhirajnikam** [flutter/flutter#129564]
I can add ml model in flutter app Android folders but i was not able to add one in flutter plugin that u was building the option was grey out 
And when open in Android studio the native code is full of import errors
I'm using hybrid composition
Is there any way I can load my model in native

**Comment by darshankawar** [comment]
@dhirajnikam 
Your question is better suited for support channels like StackOverflow, so please ask the same there.
Closing as this issue isn't a feature request or a bug report.
