### ISSUE TITLE
[image_picker]: Cannot open .jpeg files

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#129522]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. using iOS simulator 
2. pick flower image from gallery (*.jpeg)
3. observe logs

<img width="483" alt="Screenshot 2023-06-25 at 4 34 37 PM" src="https://github.com/flutter/flutter/assets/666539/55df6304-7b17-4a12-8279-dcbb721a37cb">

### Expected results

it works

### Actual results

[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(invalid_image, Cannot load representation of type public.jpeg, NSItemProviderErrorDomain, null)

### Code sample

<details><summary>Code sample</summary>

```dart
final file = await ImagePicker().pickImage(
  source: source,
  maxHeight: maxHeight,
  maxWidth: maxHeight,
  imageQuality: imageQuality,
  preferredCameraDevice: preferredCameraDevice,
);

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4 22F66 darwin-arm64, locale en-US)
    • Flutter version 3.10.5 on channel stable at /Users/lukepighetti/development/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (12 days ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/lukepighetti/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (3 available)
    • iPhone 14 (16.2) (mobile) • 51B3F17C-CB32-4B1C-B7DA-C8C783B9349A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)           • macos                                • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)              • chrome                               • web-javascript • Google Chrome 114.0.5735.133

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @lukepighetti 
It seems the issue seems to be occuring while only selecting the first picture, ie, top-left as you pointed out, which led me to https://developer.apple.com/forums/thread/665265 that indicates it could be specific to iOS simulators only. Can you possibly try the same on device and see if you get same error or not ?

As, the error does show the picture format is .jpeg, can you also confirm what is the format of other pictures ?
See this for your reference: https://github.com/flutter/flutter/issues/82602#issuecomment-1223457187
