### ISSUE TITLE
[xdg_directories] [Linux] Depends on `process 4.2.4` which is not compatible with file `7.x.x`

### ISSUE THREAD

**Issue by Gustl22** [flutter/flutter#129543]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Use a project with `file: ^7.0.0` and at the same time `xdb_directories: ^1.0.0` or `path_provider: ^2.0.0`.

This affects all Linux implementations, e.g. in [`path_provider`](https://github.com/flutter/packages/blob/main/packages/path_provider/path_provider_linux/pubspec.yaml), [xdg_directories](https://github.com/flutter/packages/blob/2d573fe913ebddeacb4ea869461b3b419aa48b5b/packages/xdg_directories/pubspec.yaml#L16), as one can't upgrade to `file >= 7.0.0`

### Expected results

Build successfully with `file: ^7.0.0`

### Actual results

```
Because path_provider_linux >=2.1.8 depends on xdg_directories >=0.2.0 <2.0.0 and path_provider_linux >=2.0.0 <2.1.8 depends on xdg_directories ^0.2.0, path_provider_linux >=2.0.0 requires xdg_directories >=0.2.0 <2.0.0.
And because path_provider >=2.0.8 depends on path_provider_linux ^2.0.1, path_provider >=2.0.8 requires xdg_directories >=0.2.0 <2.0.0.
And because xdg_directories >=0.2.0 depends on process ^4.0.0 which depends on file ^6.0.0, path_provider >=2.0.8 requires file ^6.0.0.
So, because audioplayers_example depends on both file ^7.0.0 and path_provider ^2.0.12, version solving failed.
```

Same for `integration_test`
```
Because every version of integration_test from sdk depends on file 6.1.4 and example depends on file ^7.0.0, integration_test from sdk is forbidden.
So, because example depends on integration_test from sdk, version solving failed.
```

### Code sample

<details><summary>Code sample</summary>

```yaml
# pubspec.yaml
#...
dependencies:
  flutter:
    sdk: flutter
  http: '>=0.13.1 <2.0.0'
  file: ^7.0.0
  path_provider: ^2.0.12
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
#  integration_test:
#    sdk: flutter
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.10.2, on Microsoft Windows [Version 10.0.22631.1900], locale de-DE)
    • Flutter version 3.10.2 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (5 weeks ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\src\android\Sdk
    • Platform android-33, build-tools 34.0.0
    • ANDROID_HOME = C:\src\android\Sdk
    • Java binary at: C:\Program Files\Java\jdk-17.0.1\bin\java
    • Java version Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2022 17.5.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
    • Visual Studio Build Tools 2022 version 17.5.33516.290
    • Windows 10 SDK version 10.0.22621.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2022.3.1
    • Flutter plugin version 74.0.4
    • Dart plugin version 231.9065

[√] VS Code (version 1.77.3)
    • VS Code at C:\Users\Gustl\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.1900]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 114.0.5735.134
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 113.0.1774.50

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by Gustl22** [comment]
Alternatively remove `process` dependency on `xdg_directories` and use `dart:io` instead.
See https://github.com/google/process.dart/pull/75 @stuartmorgan

**Comment by stuartmorgan** [comment]
Why was I pinged in this issue?

**Comment by Gustl22** [comment]
Sorry to rope you in here @stuartmorgan you were involved in the PR
https://github.com/flutter/packages/pull/117
I misread the git blame log. Maybe @gspencergoog has more intel. 

I wonder if the `process` package could be replaced with `dart:io` `ProcessManager`.

https://github.com/google/process.dart/blob/master/lib/src/interface/local_process_manager.dart
https://github.com/dart-lang/io/blob/master/lib/src/process_manager.dart

Sorry to bother you. It's not urgent. At least not for me.

**Comment by stuartmorgan** [comment]
> Sorry to bother you. It's not urgent.

Please do not ping people then. We have a triage process; bypassing it by pinging people adds overhead to our work.

**Comment by Gustl22** [comment]
Fair enough, I had a deeper look and the some features are missing with the `io` package. 

Nether the less, the `process` package wasn't maintained in a while (e.g. no feedback to open PRs since October 2022) and I don't think they have any triage process unless some more important people / institutions make them aware of it, especially if they are strongly connected.
