### ISSUE TITLE
Black screen appears when popping route with open keyboard

### ISSUE THREAD

**Issue by Thiru-01** [flutter/flutter#129560]
### Is there an existing issue for this?

- [x] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [x] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Open the app and navigate to a screen with an input field.
2. Tap on the input field to open the keyboard.
3. Navigate to a different screen using a route.
4. Attempt to pop the route while the keyboard is still open.

### Expected results

The app should return to the previous screen, properly dismissing the keyboard without any visual issues.

### Actual results

Instead of returning to the previous screen, a black screen is displayed when popping the route while the keyboard is open.

### Code sample

```dart
IconButton(
        onPressed: () async {
          Navigator.of(context).pop();
        },
        color: CustomColors.primaryColor,
        icon: const FaIcon(
          FontAwesomeIcons.arrowLeftLong,
))
```

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.22621.1848], locale en-IN)
    ! Warning: `dart` on your path resolves to C:\Program Files\Dart\dart-sdk\bin\dart.exe, which is not inside your
      current Flutter SDK checkout at C:\Flutter\flutter. Consider adding C:\Flutter\flutter\bin to the front of your
      path.
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.0)
[√] Android Studio (version 2021.2)
[√] VS Code, 64-bit edition (version 1.71.2)
[√] Connected device (4 available)
[√] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by dam-ease** [comment]
Hi @Thiru-01 
Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by Thiru-01** [comment]
Hi @dam-ease
``` dart 
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: KeyboardScreen(),
    );
  }
}

class KeyboardScreen extends StatefulWidget {
  @override
  _KeyboardScreenState createState() => _KeyboardScreenState();
}

class _KeyboardScreenState extends State<KeyboardScreen> {
  final FocusNode _focusNode = FocusNode();

  @override
  void initState() {
    super.initState();
    // Request focus on the dummy node when the screen loads
    FocusScope.of(context).requestFocus(_focusNode);
  }

  @override
  void dispose() {
    // Unfocus the dummy node when the screen is disposed
    _focusNode.unfocus();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () {
        // Hide the keyboard when the user taps outside any input field
        FocusManager.instance.primaryFocus?.unfocus();
      },
      child: Builder(
        builder: (BuildContext context) {
          return Scaffold(
            resizeToAvoidBottomInset: false,
            appBar: AppBar(
              title: Text('Keyboard Screen'),
            ),
            body: Center(
              child: ElevatedButton(
                onPressed: () {
                  Navigator.of(context).pop();
                },
                child: Text('Pop Route'),
              ),
            ),
          );
        },
      ),
    );
  }
}
```

To reproduce the issue:

1. Create a new Flutter project and replace the default lib/main.dart file with the code sample provided.
2. Run the app on a device or emulator.
3. Tap on the button to navigate to the KeyboardScreen.
4. Tap on the text field to open the keyboard.
5. Tap on the "Pop Route" button to go back to the previous screen while the keyboard is still open.
6. Observe that a black screen appears instead of returning to the previous screen.

**Comment by dam-ease** [comment]
Hi @Thiru-01. It seems you have provided an incomplete code sample. Can't see a TextField widget with the sample provided. For the issue to be workable, it needs to be reproducible with a minimal complete code sample that doesn’t include 3rd party plugins or complex production code. Kindly provide such a sample.
Thank you

**Comment by Thiru-01** [comment]
Hi @dam-ease. After further investigation and experimentation, I have found that the issue is due to the custom routing implementation used in the app. When utilizing the MaterialRoute provided by Flutter, the app works perfectly, and the black screen issue no longer occurs.

Thank you for your response

Closing this issue.
