### ISSUE TITLE
Install Flutter read-only for shared use 

### ISSUE THREAD

**Issue by jgfoster** [flutter/flutter#129565]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I am teaching Flutter in an undergraduate CS class and would like to have Flutter installed on our classroom computers. Following [these instructions](https://docs.flutter.dev/get-started/install/linux#install-flutter-manually) installs over a GiB of files which we can live with if is done once on each classroom machine. Unfortunately, each user needs write access to the install directory (which is not allowed on shared locations on shared computers) so each user needs to install the 1.5 GiB into their home directory which is not only a huge waste of space but is over a network (the home directory is mapped from a remote server). 

### Proposal

All Flutter to run from a read-only location. Whatever user-specific data needs to be collected should be in a user-specific location.

**Comment by stuartmorgan** [comment]
How does this differ from https://github.com/flutter/flutter/issues/91255 ? It seems like the same core request.

**Comment by jgfoster** [comment]
Yes, sorry, I looked for something similar but didn't find it!
