### ISSUE TITLE
[Impeller] Text pixelation, FontWeight, TextShadows, Blurs, Curves are not the same as Skia (worse)

### ISSUE THREAD

**Issue by emeban44** [flutter/flutter#129566]
I was so hyped about Impeller and could not wait till it was put on by default so I could try it out in my app. 

Firstly I noticed that the first start jank was gone. Which was super cool! Finally no early jank in iOS!

Not long after that, I started noticing some weird stuff. Some things just felt way off and I wanted to "not see them" but after taking deep looks, I can say that Impeller still needs progress in certain areas.

1. FontWeight is not the same as in Skia for the font PTSans (FontWeight.w700). My app design and main buttons really depend on that font-weight but in Impeller, it is way thinner and it portrays the shadow behind the font in such a messy way. 
 - Font used: PTSans
 - font weight used: 700

2. Shadows and blurs behind Text (and I am not sure if this just for text, but I think in general the shadows and blurs need checking). They feel off and look messy. My app design kind of falls by a grade or two, because of that.

3. Some widgets are pixelated (pixels can be seen from a distance)!!!! Example: CircularPercentIndicator line is blurry (pixelated). You can see pixels with the naked eye. Also the texts! I would not believe my eyes but texts inside my app had pixels on the edges. It looked like app development in 1990s. 

4. Some curve animations are rendering pixelated widgets during them, I don't know how to explain. Examples: Curves.fastOutSlowIn in horizontal directions (Widget with white borders shows visible pixels during the curve duration). Also easeIn and easeOut curves in vertical directions feel like they have some kind of fever, they are laggy as the Bambi on ice.

All in all, I love that you solved the early on jank issues which are gone now. But please check the text pixelations, the curves animations, the fontweights and so on.

I really love flutter and I believe in Impeller, it just needs further polishing and it is 100% not production ready for my app.

My app is a multiplayer quiz game, and depends on some heavy designs (lot of borders, shadows, blurs, curves, differents fonts with different weights, etc.)

I hope this will help with Impellers future and impact on Flutter.

If you need anything more, tell me.

**Comment by jonahwilliams** [comment]
> If you need anything more, tell me.

We'd really like to solve all of these issues, but without any sort of code sample or pictures of what you're seeing its going to be very difficult to triage. I suspect most of these problems are either known and being worked on or already fixed, but its hard to say from a textual description.

**Comment by emeban44** [comment]
Thank you the fast reply man! 

Look, I believe that someone else must have reported the same things, these are pretty common and straight forward ones.

Impeller is still extremely young, so it is ok.

If problems persists in future versions, I will then write proper code examples with pictures and so on.

I believe somebody else will cover these errors by then. 

cheers

**Comment by jonahwilliams** [comment]
OK, if you don't want to fill out these details then I would not file a bug in the future.
