### ISSUE TITLE
< flutter web>Embed flutter web into webpage using iframe, refresh event fails, gesture fails.

### ISSUE THREAD

**Issue by iamzhibo** [flutter/flutter#129545]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1、Start a flutter web project.
2、Embed flutter web into other websites using iframe.
3、There is a problem with gestures not working.

### Expected results

There is a problem with gestures not working.
The ios browser works normally, but the Android browser fails

### Actual results

Android normal down refresh

### Code sample

<details><summary>h5 Demo</summary>
<p>

```html
<!DOCTYPE html>
<html style="font-size: 24px">

<head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
    <meta content="width=device-width,initial-scale=1,user-scalable=no" name="viewport">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-touch-fullscreen" content="yes">
    <meta name="format-detection" content="telephone=no,address=no">
    <meta name="apple-mobile-web-app-status-bar-style" content="white">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>测试</title></title>
    <style>
        body,html{
            padding: 0;
            margin: 0;
            height: 100%;
        }
        .liveH5-page {
            position: relative;
            height: 100%;
            scrollbar-width: none; /* firefox */
            -ms-overflow-style: none; /* IE 10+ */
            overflow-y: auto;
            }
            .live-page-iframe {
                position: relative;
                overflow: auto;
                -webkit-overflow-scrolling: touch;
                width: 100vw;
                height: 100%;
                background-color: white;
            }
            .liveH5-page::-webkit-scrollbar {
            display: none; /* Chrome Safari */
            }
    </style>
</head>

<body>
<div class="liveH5-page">
    <iframe class="live-page-iframe" src='flutter web url' ref="iframe" id="iframe" scrolling="no" frameborder="0"></iframe>
</div>
</body>
</html>

``` 

</p>
</details> 

<details><summary>Flutter Code</summary>
<p>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: RefreshIndicatorExample(),
    );
  }
}

class RefreshIndicatorExample extends StatefulWidget {
  const RefreshIndicatorExample({super.key});

  @override
  State createState() => _RefreshIndicatorExampleState();
}

class _RefreshIndicatorExampleState extends State {
  final GlobalKey _refreshIndicatorKey = GlobalKey();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('RefreshIndicator Sample'),
      ),
      body: RefreshIndicator(
        key: _refreshIndicatorKey,
        color: Colors.white,
        backgroundColor: Colors.blue,
        strokeWidth: 4.0,
        onRefresh: () async {
// Replace this delay with the code to be executed during refresh
// and return a Future when code finishes execution.
          return Future.delayed(const Duration(seconds: 3));
        },
// Pull from top to show refresh indicator.
        child: ListView.builder(
          itemCount: 25,
          itemBuilder: (BuildContext context, int index) {
            return ListTile(
              title: Text('Item $index'),
            );
          },
        ),
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: () {
// Show refresh indicator programmatically on button tap.
          _refreshIndicatorKey.currentState?.activate();
        },
        icon: const Icon(Icons.refresh),
        label: const Text('Show Indicator'),
      ),
    );
  }
}

``` 

</p>
</details> 

### Screenshots or Video

https://github.com/flutter/flutter/assets/118972991/859e8116-d1b2-417b-b3e5-26e88cfbb5a6

### Logs

Flutter 3.7.12 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d9e56e694 (10 周前) • 2023-04-17 21:47:46 -0400
Engine • revision 1a65d409c7
Tools • Dart 2.19.6 • DevTools 2.20.1

### Flutter Doctor output

Flutter 3.7.12

**Comment by dam-ease** [comment]
Hi @iamzhibo. You seem to be on an older version of Flutter, can you upgrade to the latest version to confirm this issue still persists?

**Comment by iamzhibo** [comment]
Flutter 3.10.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 796c8ef792 (13 天前) • 2023-06-13 15:51:02 -0700
Engine • revision 45f6e00911
Tools • Dart 3.0.5 • DevTools 2.23.1

**Comment by dam-ease** [comment]
Hi @iamzhibo. Thanks for confirming. This might be related to https://github.com/flutter/flutter/issues/118558. Can you confirm it is??

**Comment by iamzhibo** [comment]
Hello, is this problem solved?

**Comment by dam-ease** [comment]
Hi @iamzhibo. You can confirm this by switching to the latest `master` channel. You can also comment on that issue, upvote the original comment and follow up on the issue for updates. If this issue is similar to what you are describing, kindly let me know so I can close this in favour of the already open issue.

**Comment by iamzhibo** [comment]
Flutter 3.10.5 • channel .have the same problem

**Comment by dam-ease** [comment]
Hi @iamzhibo. The latest master is `3.12.0-12.0.pre.51`. You can switch to the master channel to confirm this.
