### ISSUE TITLE
AnimatedList does not take SafeArea into account when building the list 

### ISSUE THREAD

**Issue by jiahaog** [flutter/flutter#129539]
Internal bug: b/288213176

### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Please see the code sample

### Expected results

This is how it works for a `ListView`, and we would expect the same for a `AnimatedList`

![A flutter app with a ListView, which leaves a space for the safearea](https://github.com/flutter/flutter/assets/7111741/d263c017-9ffc-4f76-9358-cf1372eb8b47)

### Actual results

This is what it actually looks like. ![A flutter app with an animated list, which does not leave a space for the safearea](https://github.com/flutter/flutter/assets/7111741/16af5520-df06-4910-811d-3912b7b6a223)

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  void initState() {
    SystemChrome.setEnabledSystemUIMode(SystemUiMode.edgeToEdge);
    SystemChrome.setSystemUIOverlayStyle(
      SystemUiOverlayStyle(
        statusBarColor: Colors.transparent,
        statusBarIconBrightness: Brightness.dark,
        systemNavigationBarColor: Colors.transparent,
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      extendBody: true,
      appBar: AppBar(
        title: Text(widget.title, style: TextStyle(fontFamily: 'ProductSans')),
      ),
      body: _buildBody(context),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }

  Widget _buildBody(BuildContext context) {
    // AnimatedList does not take into account SafeArea.
    return AnimatedList(
      initialItemCount: 100,
      itemBuilder: (_, index, __) => Text('$index'),
    );
  }
}
```

</details>

### Flutter Doctor output

Reproducible on the master channel, on `5a7ab5a147f6b50ba7dc8c82d3ea0040fc0f081f`

**Comment by AdamMusa** [comment]
Hello, @TahaTesser  may I fix this ?

**Comment by TahaTesser** [comment]
@AdamMusa 
Please take a look at issues with [good first contribution](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+contribution%22) label

**Comment by AdamMusa** [comment]
Thank you @TahaTesser

**Comment by TahaTesser** [comment]
reverted in https://github.com/flutter/flutter/pull/129645

**Comment by TahaTesser** [comment]
cc: @HansMuller 
We'd need to update internal tests to pass with this fix.

**Comment by jiahaog** [comment]
Relanded in https://github.com/flutter/flutter/pull/129860, I think we can close this now, thanks everyone!
