### ISSUE TITLE
[Impeller] Support lossy texture compression in the Vulkan backend.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#129501]
We use lossy texture compression where available on iOS using `MTLTextureCompressionTypeLossy`. This is typically only available on newer iOS GPUs (A15 Bionic and above I believe). However, the memory savings are massive the visual differences unnoticeable.

We should opt into using the same kind of texture compression on Vulkan on Android. Universal support for this, like on iOS, is absent. But it is available on certain ARM Mali GPUs. ARM calls this ARM Fixed-Rate Compression (AFRC) and it available to opt-in via the [`VK_EXT_image_compression_control`](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_EXT_image_compression_control.html) extension. This extension isn't widely available [~3% on vulkan.gpuinfo.org on Android](https://vulkan.gpuinfo.org/listextensions.php?platform=android) as of this writing. But, notably, it is available on all Pixels 6 and above and may be the norm moving forward on higher end ARM Mali devices.

Unlike Metal, AFRC allows you to pick the compression ratio. Moving from a 2x to a whopping 4x ratio. More information about this and other Vulkan optimizations is in a recent talk about [Vulkan best-practices for mobile](https://youtu.be/BD1zXW7Uz8Q?t=1781).
<img width="834" alt="Screenshot 2023-06-25 at 12 20 30 AM" src="https://github.com/flutter/flutter/assets/44085/3d4cd2b6-27e4-4d03-a451-1e6165e32310">

**Comment by chinmaygarde** [comment]
cc @jonahwilliams @bdero. I am not sure what the compression ratios are on Metal. I don't remember these being documented. But even a 2x savings would be great.

**Comment by jonahwilliams** [comment]
2x ish on metal iirc

**Comment by jonahwilliams** [comment]
It sounds like for the render target textures, ARM chips are already applying some level of automatic framebuffer compression:

https://arm-software.github.io/vulkan_best_practice_for_mobile_developers/samples/performance/afbc/afbc_tutorial.html

**Comment by jonahwilliams** [comment]
We can also set a default compression instead of explicitly picking a value. That might be a good place to start.

```
    vk::ImageCompressionControlEXT compression;
    compression.flags = vk::ImageCompressionFlagBitsEXT::eFixedRateDefault;
```

**Comment by chinmaygarde** [comment]
> ARM chips are already applying some level of automatic framebuffer

That is AFBC which ensures lossless compression. The bandwidth savings are realized with AFBC but there are no memory savings. AFRC (that this issue describes) books the memory savings as well in exchange for minor artifacts due to lossy compression.
