### ISSUE TITLE
Issue from website page IDE Setup

### ISSUE THREAD

**Issue by felipecarvalho** [flutter/flutter#12963]
I think the better method to configure the Flutter plugin in IntelliJ/Android Studio is initialize a new Flutter Project, and set the path manually in this new project.

This part of the documentation is a bit confusing, to newbies.

**Comment by sethladd** [comment]
cc @mit-mit @devoncarew

**Comment by mit-mit** [comment]
I like this idea. @devoncarew WDYT?

**Comment by devoncarew** [comment]
I don't follow completely.

> I think the better method to configure the Flutter plugin in IntelliJ/Android Studio is initialize a new Flutter Project, and set the path manually in this new project.

The new project wizard does have a place to set the path to the flutter sdk (or download if it's not installed). Newly created projects from the wizard should already have a correctly configured path to the flutter sdk.

**Comment by felipecarvalho** [comment]
@devoncarew The new version of plugin solve this, sorry. Thanks!

**Comment by devoncarew** [comment]
No worries :) Thanks for the feedback

**Comment by mit-mit** [comment]
Actually, I still think this is a good suggestion, reopening
