### ISSUE TITLE
Theme updates aren't hitting 60Hz

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1296]
The tree walk is killing us (I checked with a Dart profile, and while it's noisy, the tree walk is definitely near the top).

**Comment by Hixie** [comment]
![screenshot_20160119-090445](https://cloud.githubusercontent.com/assets/551196/12425899/d37ae630-be8b-11e5-889b-0c7fee56b70f.png)

**Comment by Hixie** [comment]
That's with a patch that avoids the tree walk. I'm not convinced that's much of an improvement. I'll upload the patch momentarily.

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/pull/1299

**Comment by Hixie** [comment]
![screenshot_20160119-093009](https://cloud.githubusercontent.com/assets/551196/12426596/47cff0f4-be8f-11e5-893d-6b48e5fbe1af.png)

**Comment by Hixie** [comment]
That's with also moving from Set to HashSet. Not much change.

**Comment by Hixie** [comment]
![screenshot_20160119-095450](https://cloud.githubusercontent.com/assets/551196/12427206/bd769580-be92-11e5-81cd-56d13b1da2da.png)

**Comment by Hixie** [comment]
That last one is with also caching the upwards walk, since on hte profile `inheritFromWidgetOfExactType` was one of the top functions.

**Comment by Hixie** [comment]
I've updated the PR to include that fix too. Looking at the profile there's nothing obvious there anymore. It's just General Slowness.

**Comment by Hixie** [comment]
![screenshot_20160123-132904](https://cloud.githubusercontent.com/assets/551196/12532954/ab81a7f2-c1d5-11e5-93b0-e0b3360c7c0f.png)

**Comment by abarth** [comment]
That looks a lot better.  What did you change?

**Comment by Hixie** [comment]
Closed on the basis that the PR fixed it.
