### ISSUE TITLE
Not able to analyze iOS build size using 'flutter build ios --analyze-size'

### ISSUE THREAD

**Issue by siddew201** [flutter/flutter#129605]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

- We need to braking down the iOS build size
- We have run 'flutter build ios --analyze-size'
- We are getting following error

```
Oops; flutter has exited unexpectedly: "PathNotFoundException: Cannot open file,
path = 'build/flutter_size_02/snapshot.arm64.json' (OS Error: No such file or
directory, errno = 2)".
A crash report has been written to
/Users/siddharthtiwari/Documents/tata-neu-app/app/tata_neu_app/flutter_01.log.
```

### Expected results

- We should get high level summary of the size breakdown in the terminal and appropriate JSON file in DevTools.

### Actual results

Getting following error

```
Oops; flutter has exited unexpectedly: "PathNotFoundException: Cannot open file,
path = 'build/flutter_size_02/snapshot.arm64.json' (OS Error: No such file or
directory, errno = 2)".
A crash report has been written to
/Users/siddharthtiwari/Documents/tata-neu-app/app/tata_neu_app/flutter_01.log.
```

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]
<img width="1299" alt="Screenshot 2023-06-27 at 10 20 54 AM" src="https://github.com/flutter/flutter/assets/104554752/50e62c80-1642-46a2-bc42-e6cca511f5eb">

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```
[flutter_01.log](https://github.com/flutter/flutter/files/11877768/flutter_01.log)

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.2.1 22D68 darwin-arm (Rosetta), locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.79.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
</details>

**Comment by darshankawar** [comment]
@siddew201 
I was able to run the command successfully on a demo app using latest stable version:

```
      libswiftCoreMedia.dylib                                             391 KB
      webview_flutter_wkwebview.framework                                 463 KB
      libswiftCoreLocation.dylib                                          392 KB
      rive_common.framework                                                 2 MB
      camera_avfoundation.framework                                       215 KB
    embedded.mobileprovision                                               92 KB
    Info.plist                                                              3 KB
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
A summary of your iOS bundle analysis can be found at: /Users/dhs/.flutter-devtools/ios-code-size-analysis_02.json

To analyze your app size in Dart DevTools, run the following command:
dart devtools --appSizeBase=ios-code-size-analysis_02.json
Built /Users/dhs/Documents/NCFlutter/test_app/build/storybook/ios/iphoneos/Runner.app.
dhs@Dhss-MacBook-Pro test_app % 

```

Does it replicate consistently everytime you run the command ? 
Also, I see that you are not on latest or recent stable version. Can you upgrade to latest and run the scenario again to see if error persists still ?
