### ISSUE TITLE
Some Emoji on iOS cannot be rendered correctly

### ISSUE THREAD

**Issue by jiangkang** [flutter/flutter#129629]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create A Text or TextField Widget
2. Find and enter 0️⃣ in the input method emoji panel that comes with iOS, and let Text or TextField render it

### Expected results

Text and TextField can be rendered correctly 0️⃣

### Actual results

0️⃣ Can't be rendered correctly on iOS

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

class Demo extends StatefulWidget {
  const Demo({super.key});

  @override
  State<Demo> createState() => _DemoState();
}

class _DemoState extends State<Demo> {
  String _content = "";

  final TextEditingController _controller = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("1️⃣"),
        centerTitle: true,
      ),
      body: SafeArea(
          child: Padding(
        padding: const EdgeInsets.all(8.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            Text(
              _content,
              style: const TextStyle(fontSize: 32, color: Colors.black),
            ),
            const SizedBox(height: 30),
            TextField(
              decoration: const InputDecoration(border: OutlineInputBorder()),
              controller: _controller,
              onChanged: (value) {
                setState(() {
                  _content = value;
                });
              },
            ),
          ],
        ),
      )),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

<img width="377" alt="image" src="https://github.com/flutter/flutter/assets/12570868/cc44df05-5aaa-4c98-a7b8-65427b652af7">

https://github.com/flutter/flutter/assets/12570868/c20c44d5-892f-4f9e-9424-14832964ffc1

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4 22F66 darwin-arm64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.3)
[✓] VS Code (version 1.79.2)
[!] Proxy Configuration
    ! NO_PROXY is not set
[✓] Connected device (3 available)
[✓] Network resources
```

</details>

**Comment by jason-simmons** [comment]
See https://github.com/flutter/flutter/issues/115517

**Comment by darshankawar** [comment]
@jiangkang 
Based on above comment, let's track this in linked issue which has more details and root-cause.
Closing this in favor of the linked issue. If you disagree, write in comments and I'll reopen it.
