### ISSUE TITLE
support for marker rotation and anchor in google_maps_flutter_web

### ISSUE THREAD

**Issue by Henk-Keijzer** [flutter/flutter#129620]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

markers are always pointing north in the web package of google_maps_flutter_web, whereas on Android and iOS they can be rotated (on the fly, at the moment the position of the marker is changed).

### Proposal

Are there any plans to implement marker rotation and marker anchor in the google_maps_flutter_web package? It works perfectly in the Android and iOS packages, but not in web.

**Comment by darshankawar** [comment]
@Henk-Keijzer 
I think this is similar to https://github.com/flutter/flutter/issues/80578 for which you can refer https://github.com/flutter/flutter/issues/80578#issuecomment-1325576070.

I'll close this in favor of the linked issue.
