### ISSUE TITLE
How to create a graph of the scrolling_summary.json

### ISSUE THREAD

**Issue by artem-2024** [flutter/flutter#129693]
Excuse me
When i run the commd : **flutter drive --driver=integration_test/perf_driver.dart --target=integration_test/perf_test.dart --profile --trace-startup --no-dds
**  
I get a file ：scrolling_summary.json
How to create a graph of the results？
I try use **chrome://tracing** the file， but it not work for me

**Comment by danagbemava-nc** [comment]
Hi @artem-2024, is this still an issue with the latest versions of flutter?
