### ISSUE TITLE
Introduce Builder in Overlay

### ISSUE THREAD

**Issue by clragon** [flutter/flutter#129677]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

A common requirement in UI is the following:

I want to have some widgets which are "above" or "independant" of my "pages".
Usually this is a `AppBar`, `Drawer` or `BottomSheet`. 

Currently, doing this is rather unwieldy. To accomplish this feat, we have to do the following:
- remove all our Routes from `MaterialApp`
- put a central Page into the `MaterialApp.home` parameter
- add our top level widgets to the central page
- add a new `Navigator` as child of our top level widgets, with all our Routes

If we then want to control our pages in our top level widgets, we additionally have to keep a `GlobalKey<NavigatorState>` around somewhere in that page to which all top level widgets need to have access to, because they arent inside of the `BuildContext` of our nested `Navigator`. 

Another requirement, not as common but still not uncommon is that we might want to have some kind of proxy widget that does nothing but redirect, for example an authentication guard or a deep link handler. These obviously need access to the Navigator but have to live in a central spot, so not inside of a Page. As a result, we need a `GlobalKey<NavigatorState>`. 

### Proposal

I think that this could possibly be solved a bit more elegantly. 
Assume we could do the following:

```dart
MaterialApp(
  routes: { /* ... */ },
  builder: (context, child) => Column(
    children: [
      /// This contains the stack of Navigator pages.
      Expanded(child: child),
      /// This is any Widget that we want to display next to all pages,
      /// but also needs access to `Navigator.of(context)`.
      BottomNavigationBar(),
    ],
  ),
);
```

With this, we can insert our top level navigation elements into our Navigator without creating a new nested Navigator. 
They directly have access to the Navigator in BuildContext, so our setup is simplified.

The same `builder` parameter would be available on a `Navigator` (and `Overlay`), not just on `MaterialApp`.
It would have the signature `Widget Function(BuildContext context, Widget child) builder` where `context` is the `BuildContext` below the Navigator (the one of `Overlay`) and `child` is the stack of pages (`_Theater`).

This means we can now insert top level Widgets which have access to navigation through context. This eliminates the need for a `GlobalKey` that has to be passed to all top level Widgets which need navigation and it also eliminates the need for a second nested `Navigator` in many cases. I believe this could simplify many apps which have the usual bottom navigation bar structure and benefit many other applications as well.

As for the implementation, if I have understood the framework code correctly, we could implement this quite easily with the following:

![image](https://github.com/flutter/flutter/assets/11785085/81e59a6c-fc88-4983-b3e0-20858c0ff010)

`Overlay` declares a `builder` parameter, which it calls with its child inside of its `build` method [here](https://github.com/flutter/flutter/blob/796c8ef79279f9c774545b3771238c3098dbefab/packages/flutter/lib/src/widgets/overlay.dart#L713).
`Navigator` declares a `builder` parameter, which is passed to `Overlay`.
`MaterialApp` delcares a `builder` parameter, which is passed to `Navigator`.

`MaterialApp.builder` already exists, but its `context` is the one of the `MaterialApp` and its child is `Navigator`, so we do not have access to the `Navigator` in the current `MaterialApp.builder`. I am not sure if updating the builder to include the `Navigator` (and `Overlay`) in its `context` and changing its child to a `_Theater` would be considered a breaking change, since `child` it is not explicitly promised to be `Navigator`. If this isnt a breaking change, I believe there might be no benefit to have both builders, and the new one could simply replace the old one. 

This change cannot be provided by a package in a simple manner, as the package would have to uproot the entire `MaterialApp`, `Navigator` and `Overlay`.

**Comment by goderbauer** [comment]
I don't understand what this is asking for.

> The builder would be passed through Navigator all the way up to MaterialApp.

What does this mean? The Navigator doesn't know about MaterialApp and cannot pass anything to it.

> This means we can now insert top level Widgets which have access to navigation through context.

If the widget lives above the navigator, how does it gain access to the navigator via context? Context lockups only happen upwards.

**Comment by clragon** [comment]
> What does this mean? The Navigator doesn't know about MaterialApp and cannot pass anything to it.

Apologies, I formulated this slightly confusingly.
I mean something like the following:

`Overlay` declares a `builder`, which is called with the `_Theater`
`Navigator` declares a `builder`, which is passed to `Overlay`
`MaterialApp` passes its `builder` to `Navigator` instead of consuming it.

Why do I think this would be useful?

By inserting a `Builder` below `Overlay` but above its children, we can create UI elements which have access to `Navigator` and `Overlay` in their `BuildContext` and can appropriately use them, while also having a lifetime that is not bound to any `Route` (or any `OverlayEntry`). Such UI components are commonly components like `BottomNavigationBar` or global `AppBar`s which need to navigate, but live not inside any given `Route`.

I do not have extensive framework knowledge, but I dont think this should be causing any issues with `BuildContext`.

> If the widget lives above the navigator

As I have clarified above, the Widget would not live above the `Navigator`, it would neither live above the `Overlay` but below it.
The important difference is that it lives above the `OverlayEntry`s.

**Comment by caseycrogers** [comment]
I'm pretty agnostic to the exact implementation, but I'd like to just throw in a strong +1 to this feature request.

Right now it's extremely painful to include an app bar or navigation bar in my app that does not get rebuilt/animated on page transition (and is thus above the navigator).

If my app bar is under the navigator, it can call `pop`, but it gets animated along with pages.

If my app bar is above the navigator, it doesn't get animated with the pages, but I have to do a complicated song and dance with a global key and some other nonsense to get a valid reference to my navigator.

Here's the Flutter idiomatic (from what I've seen) way to handle navigation right now (if you're using Nav 2 and not 1 or GoRouter-just the proliferation alone of "official" choices is a big hit to dev ex). This is copied from my current production app:
```dart
// Global key. Ewww.
final GlobalKey<NavigatorState> _navKey = GlobalKey();

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    // I forget exactly why, but without this Flutter keeps trying to pop
    // from MaterialApp's navigator instead of this one.
    return WillPopScope(
      onWillPop: () async {
        return !await _navKey.currentState!.maybePop();
      },
      child: Navigator(
        key: _navKey,
        pages: [
          ...
        ],
        onPopPage: (route, dynamic result) { ... },
      ),
    );
  }
}
```

**Comment by clragon** [comment]
To elaborate a bit, I have written a very awful hack that represents the behaviour I want.

The demo can be found on this gist:
<https://gist.github.com/clragon/18038b16e9bbdc5e14d4a6e5840517d1>

In there I have abused `visitChildElements` and proxies to lift the `NavigatorState` and `OverlayState` above the `builder` of `MaterialApp` artificially.
With the proposed change of this github issue, such a hack would be unnecessary.

here is a demo video of the result:

https://github.com/flutter/flutter/assets/11785085/c8bfd788-277d-412b-bd00-622dac2ee761

We have a bottom bar that is outside of our Navigator, 
without needing 2 Navigators nested inside of each other
and without passing any `GlobalKey` to our bottombar.
Produced with the following code:

```dart
  @override
  Widget build(BuildContext context) => MaterialApp(
        initialRoute: '/1',
        routes: {
          '/1': (context) => const Page(index: 1),
          '/2': (context) => const Page(index: 2),
          '/3': (context) => const Page(index: 3),
          '/4': (context) => const Page(index: 4),
        },
        builder: (context, child) => Proxy(
          child: child!,
          builder: (context, child) => Scaffold(
            body: child!,
            bottomNavigationBar: const NavBottomBar(),
          ),
        ),
      );
}
```

and 

```dart
    return BottomNavigationBar(
      useLegacyColorScheme: false,
      currentIndex: _index,
      onTap: (index) {
        switch (index) {
          case 0:
            Navigator.of(context).pushNamed('/1');
            setState(() => _index = 0);
            break;
          case 1:
            Navigator.of(context).pushNamed('/2');
            setState(() => _index = 1);
            break;
          // and so on
      },
```

note the `Proxy` widget.

Because this is a dirty hack and not a real implementation, this only works in release mode.
`BottomNavigationBar` has an `assert` that checks for a `Overlay` runtime type and `ProxyOverlay` does not fulfill that, even though it has the same interface.

The overall change necessary to allow us to create shouldnt be as complicated as this hack though;

I believe it would look something like this:

in `overlay.dart`

constructor:
```diff
   const Overlay({
     super.key,
     this.initialEntries = const <OverlayEntry>[],
     this.clipBehavior = Clip.hardEdge,
+    this.builder, // of type `TransitionBuilder?`
   });
```

build method:
```diff
+   builder ??= ((context, child) => child!);

-   _Theater(
+   return builder(context, _Theater(
       skipCount: children.length - onstageCount,
       clipBehavior: widget.clipBehavior,
       children: children.reversed.toList(growable: false),
```

in `navigator.dart`

constructor:
```diff
   const Navigator({
     super.key,
     this.pages = const <Page<dynamic>>[],
     this.onPopPage,
     this.initialRoute,
     this.onGenerateInitialRoutes = Navigator.defaultGenerateInitialRoutes,
     this.onGenerateRoute,
     this.onUnknownRoute,
     this.transitionDelegate = const DefaultTransitionDelegate<dynamic>(),
     this.reportsRouteUpdateToEngine = false,
     this.clipBehavior = Clip.hardEdge,
     this.observers = const <NavigatorObserver>[],
     this.requestFocus = true,
     this.restorationScopeId,
     this.routeTraversalEdgeBehavior = kDefaultRouteTraversalEdgeBehavior,
+    this.builder, // of type `TransitionBuilder?`
   });
```

build method:
```diff
                  child: Overlay(
                   key: _overlayKey,
                   clipBehavior: widget.clipBehavior,
                   initialEntries: overlay == null ?  _allRouteOverlayEntries.toList(growable: false) : const <OverlayEntry>[],
+                  builder: widget.builder,
                 ),
```

in `app.dart`

build method:
```diff
         child: Navigator(
           clipBehavior: Clip.none,
           restorationScopeId: 'nav',
           key: _navigator,
           initialRoute: _initialRouteName,
           onGenerateRoute: _onGenerateRoute,
           onGenerateInitialRoutes: widget.onGenerateInitialRoutes == null
             ? Navigator.defaultGenerateInitialRoutes
             : (NavigatorState navigator, String initialRouteName) {
               return widget.onGenerateInitialRoutes!(initialRouteName);
             },
           onUnknownRoute: _onUnknownRoute,
           observers: widget.navigatorObservers!,
           reportsRouteUpdateToEngine: true,
+          builder: widget.builder,
         ),
```

also build method:
```diff
     Widget result;
-     if (widget.builder != null) {
-       result = Builder(
-         builder: (BuildContext context) {
-           return widget.builder!(context, routing);
-         },
-       );
     } else {
```
(Since the builder would be passed to the `Navigator`, I am not sure how this could would play out.)
I have simplified the necessary changes strongly, but I think it should demonstrate the points of code that would be touched by this. 

With all of these changes, it would then be possible to do the exact same thing as shown in my gist but without the weird hacky `Proxy` widget. 

BottomNavigationBar isnt the only target application for such a change.
Many widgets that passthrough a child but apply various navigation tasks or showing other widgets in the overlay at the very root of the application could be achieved very easily and cleanly. In my own application I have a bunch of Widgets which could benefit from this. For example a widget that redirects based on deeplinks, or a widget that shows overlays based on hovering over a URL or a widget pushing a route based on server status. 

I hope this explains the idea @goderbauer

**Comment by clragon** [comment]
After thinking about it some more, I have come to the conclusion that my example is dangerous and flawed;

Lifting the OverlayState is conceptually okay only as long as we do not add widgets that have an actual size.
A BottomBar that needs access to OverlayState therefore would never work, because it assumes that it is inside of an Overlay and therefore within the boundaries of its Stack and so can place OverlayEntrys on top of itself. This is not the case with a builder wrapped around `_Theater`.

I dont think it would make sense to introduce such a feature when its possible to easily use it wrongly.

Lifting only the NavigatorState might be acceptable (meaning, our builder parameter is resolved inside of NavigatorState and not passed further down to OverlayState). This would still achieve alot of the things I wanted, namely we could remain only needing one Navigator and we could naivgate via BuildContenxt.
Though it would also mean that if we want an Overlay to be accessible in our wrapper widgets we would have to add an extra one.
