### ISSUE TITLE
[Impeller] Brandon's screenshots are showing discretionary ligatures in Wonderous

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#129643]
@bdero 's screenshots in https://github.com/flutter/flutter/issues/128624#issuecomment-1585245234 are showing discretionary ligatures.  It's my understanding that they should not be rendering.  I'm unable to reproduce the problem locally either by running the wonderous app or creating a simple app that turns the ligatures on and off.

It's still uncertain if this is an issue or if @bdero has a local change that is causing the discrepancy.  @bdero can you please give more background to why those are showing up in your screenshots?

**Comment by bdero** [comment]
gskinner's marketing material as well as their Skia+Impeller bug screenshots show the discretionary ligatures. 

Impeller doesn't make decisions about text frame construction. In Flutter, the text shaper (SkParagraph) produces text frames which are then dispatched to Impeller or Skia.

I'm not familiar with the inner workings of SkParagraph, but @jason-simmons might have color to add here.

**Comment by gaaclarke** [comment]
@bdero what version of wonderous are you running?  I'm running `c2be9688db680199edc0d49b1d536ad8bf176987`.  It could be they changed the code at some point.

**Comment by jason-simmons** [comment]
I tried running Wonderous (commit `a387ca18db42ff2d593efe918e88b42cf372cec9`) with the latest Flutter engine.  I was unable to reproduce this with Impeller on iOS or Android.

If there is a combination of app and engine where these ligatures render with Impeller but not Skia, then I can look into it.

**Comment by gaaclarke** [comment]
Okay, i just found they they did remove the ligatures in 4fe946e587de4bc9405f392d909f8e9d73408eb6.  That's the explanation.  Thanks, I just wanted to make sure we didn't miss some problem when those screenshots showed up.
