### ISSUE TITLE
Easier spacing between Column's children

### ISSUE THREAD

**Issue by GCSBOSS** [flutter/flutter#129685]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I wanted to have an easier way to set spacing between form elements, or any widget really, in a column (or row).

> [StackOverflow Question](https://stackoverflow.com/questions/52774921/space-between-columns-children-in-flutter)

The currently the [available ways](https://stackoverflow.com/posts/58357507/revisions) to accomplish this are very verbose or tiresome for larger codebases.

### Proposal

To mimic CSS standards for flex box or grid layouts, it would be nice if `Column` and  friends would [support a `gap:`](https://stackoverflow.com/questions/52774921/space-between-columns-children-in-flutter#comment98444002_52774984) parameter to define an integer spacing in between each children.

**Comment by danagbemava-nc** [comment]
Hi, there's an existing issue requesting this in https://github.com/flutter/flutter/issues/55378. 

Kindly subscribe to the original issue for updates.

Closing from here as duplicate. 

Thank you
