### ISSUE TITLE
Update flutter SDK in an enterprise app

### ISSUE THREAD

**Issue by starsoheil2007** [flutter/flutter#129607]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Hi
We have an enterprise app that wrote by flutter 2.5.3 about 2 years age, and we have about 2 million users now. 
Now we updated flutter SDK to 3.10.5 but when we build new Signed apk by before application's keystore and we want to update on before version of application that installed on device, We faced with this error "app not installed as package appears to be invalid".
Please consider this error appear on update only and in clean install everything is ok.
But we can't tell every user to uninstall old version and install new version from Google Play.
Please guide me to fix this issue.

### Actual results

app not installed as package appears to be invalid on update application.

### Logs

<details>
<summary>Logs</summary>
I check all logcat in install update process and we don't have any Exceptions.
</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.22621.1702], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 2022.2)
[√] Connected device (2 available)

</details>

**Comment by dam-ease** [comment]
Hi @starsoheil2007. Thanks for filing this issue. This might not be an issue with flutter itself.
Does this happen when you run the application or when building the new signed apk, if the later, then you might want to try out some of the solutions [here](https://www.rootupdate.com/app-not-installed-as-package-appears-to-be-invalid-fixed/). Kindly let me know if any of the solutions fit into your use case

**Comment by starsoheil2007** [comment]
Hi @dam-ease 
Thanks for your response.
I checked your link and one of solutions was suitable for me. (Uninstall old version and install new version). I don't want to do this. I used same Keystore to sign new APK but this error appear again. 
I searched many times in the internet. 
I you have any other suggestion for me, please tell to me.
Thank you
