### ISSUE TITLE
[Impeller] Raster time regression on default precision changes

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#129641]
[ttps://github.com/flutter/engine/pull/43183](https://github.com/flutter/engine/pull/43183) changed the default precision of the vertex stage back to highp, as well as the fragment stage of the rrect blur. This was intended to fix fidelity issues, but we did regress raster time a bit:

https://flutter-flutter-perf.skia.org/e/?begin=1687771256&end=1687828539&keys=X54649286414cd6c02eda6b3401877fbe&num_commits=50&request_type=1&xbaroffset=35487

This seemed to primarily effect the moto g4. We should investigate whether we can claw some of this loss back by carefully opting part of the vertex stage back into mediump, or confirm its not due to the change in rrect blur.

In general, positional data needs to be highp, but uvs and colors can be mediump.

**Comment by chinmaygarde** [comment]
This seems like working as intended.
