### ISSUE TITLE
program crashed while installing package intl

### ISSUE THREAD

**Issue by MuthuKrishnan3002** [flutter/flutter#129610]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

flutter pub add intl

### Expected results

it is expected to resolve all dependencies and install the package in system

### Actual results

https://github.com/flutter/flutter/issues/new?title=%5Btool_crash%5D+FileSystemException%3A+Cannot+open+file%2C+OS+Error%3A+The+process+cannot+access+the+file+because+it+is+being+used+by+another+process.%0D%0A%2C+errno+%3D+32&body=%23%23+Command%0A%60%60%60%0Aflutter+pub+get%0A%60%60%60%0A%0A%23%23+Steps+to+Reproduce%0A1.+...%0A2.+...%0A3.+...%0A%0A%23%23+Logs%0AFileSystemException%3A+Cannot+open+file%2C+OS+Error%3A+The+process+cannot+access+the+file+because+it+is+being+used+by+another+process.%0D%0A%2C+errno+%3D+32%0A%60%60%60%0A%230++++++_File.throwIfError+%28dart%3Aio%2Ffile_impl.dart%3A675%3A7%29%0A%231++++++_File.openSync+%28dart%3Aio%2Ffile_impl.dart%3A490%3A5%29%0A%232++++++_File.writeAsBytesSync+%28dart%3Aio%2Ffile_impl.dart%3A644%3A31%29%0A%233++++++_File.writeAsStringSync+%28dart%3Aio%2Ffile_impl.dart%3A668%3A5%29%0A%234++++++ForwardingFile.writeAsStringSync+%28package%3Afile%2Fsrc%2Fforwarding%2Fforwarding_file.dart%3A150%3A16%29%0A%235++++++ErrorHandlingFile.writeAsStringSync.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handling_io.dart%3A267%3A22%29%0A%236++++++_runSync+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handling_io.dart%3A590%3A14%29%0A%237++++++ErrorHandlingFile.writeAsStringSync+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handling_io.dart%3A266%3A5%29%0A%238++++++_renderTemplateToFile+%28package%3Aflutter_tools%2Fsrc%2Fflutter_plugins.dart%3A33%3A8%29%0A%239++++++_writeMacOSPluginRegistrant+%28package%3Aflutter_tools%2Fsrc%2Fflutter_plugins.dart%3A863%3A3%29%0A%2310+++++injectPlugins+%28package%3Aflutter_tools%2Fsrc%2Fflutter_plugins.dart%3A1159%3A11%29%0A%3Casynchronous+suspension%3E%0A%2311+++++FlutterProject.ensureReadyForPlatformSpecificTooling+%28package%3Aflutter_tools%2Fsrc%2Fproject.dart%3A374%3A5%29%0A%3Casynchronous+suspension%3E%0A%2312+++++PackagesGetCommand.runCommand+%28package%3Aflutter_tools%2Fsrc%2Fcommands%2Fpackages.dart%3A326%3A7%29%0A%3Casynchronous+suspension%3E%0A%2313+++++FlutterCommand.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command.dart%3A1336%3A27%29%0A%3Casynchronous+suspension%3E%0A%2314+++++AppContext.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A150%3A19%29%0A%3Casynchronous+suspension%3E%0A%2315+++++CommandRunner.runCommand+%28package%3Aargs%2Fcommand_runner.dart%3A212%3A13%29%0A%3Casynchronous+suspension%3E%0A%2316+++++FlutterCommandRunner.runCommand.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command_runner.dart%3A296%3A9%29%0A%3Casynchronous+suspension%3E%0A%2317+++++AppContext.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A150%3A19%29%0A%60%60%60%0A%60%60%60%0A%5B%21%5D+Flutter+%28Channel+unknown%2C+0.0.0-unknown%2C+on+Microsoft+Windows+%5BVersion+10.0.22621.1848%5D%2C+locale+en-IN%29%0A++++%21+Flutter+version+0.0.0-unknown+on+channel+unknown+at+C%3A%5Csrc%5Cflutter%0A++++++Currently+on+an+unknown+channel.+Run+%60flutter+channel%60+to+switch+to+an+official+channel.%0A++++++If+that+doesn%27t+fix+the+issue%2C+reinstall+Flutter+by+following+instructions+at+https%3A%2F%2Fflutter.dev%2Fdocs%2Fget-started%2Finstall.%0A++++++Cannot+resolve+current+version%2C+possibly+due+to+local+changes.%0A++++++Reinstall+Flutter+by+following+instructions+at+https%3A%2F%2Fflutter.dev%2Fdocs%2Fget-started%2Finstall.%0A++++%21+Unknown+upstream+repository.%0A++++++Reinstall+Flutter+by+following+instructions+at+https%3A%2F%2Fflutter.dev%2Fdocs%2Fget-started%2Finstall.%0A++++%E2%80%A2+Framework+revision++%28%29%2C+1970-01-01+05%3A30%3A00.000%0A++++%E2%80%A2+Engine+revision+2a3401c9bb%0A++++%E2%80%A2+Dart+version+3.0.3%0A++++%E2%80%A2+DevTools+version+2.23.1%0A++++%E2%80%A2+If+those+were+intentional%2C+you+can+disregard+the+above+warnings%3B+however+it+is+recommended+to+use+%22git%22+directly+to+perform+update+checks+and+upgrades.%0A%0A%5B%E2%9C%93%5D+Windows+Version+%28Installed+version+of+Windows+is+version+10+or+higher%29%0A%0A%5B%21%5D+Android+toolchain+-+develop+for+Android+devices+%28Android+SDK+version+33.0.2%29%0A++++%E2%80%A2+Android+SDK+at+C%3A%5CUsers%5CMuthuNMK%5CAppData%5CLocal%5CAndroid%5Csdk%0A++++%E2%80%A2+Platform+android-33%2C+build-tools+33.0.2%0A++++%E2%9C%97+Android+SDK+file+not+found%3A+C%3A%5CUsers%5CMuthuNMK%5CAppData%5CLocal%5CAndroid%5Csdk%5Cbuild-tools%5C33.0.2%5Caapt.%0A++++%E2%80%A2+Try+re-installing+or+updating+your+Android+SDK%2C%0A++++++visit+https%3A%2F%2Fflutter.dev%2Fdocs%2Fget-started%2Finstall%2Fwindows%23android-setup+for+detailed+instructions.%0A%0A%5B%E2%9C%93%5D+Chrome+-+develop+for+the+web%0A++++%E2%80%A2+Chrome+at+C%3A%5CProgram+Files%5CGoogle%5CChrome%5CApplication%5Cchrome.exe%0A%0A%5B%E2%9C%97%5D+Visual+Studio+-+develop+for+Windows%0A++++%E2%9C%97+Visual+Studio+not+installed%3B+this+is+necessary+for+Windows+development.%0A++++++Download+at+https%3A%2F%2Fvisualstudio.microsoft.com%2Fdownloads%2F.%0A++++++Please+install+the+%22Desktop+development+with+C%2B%2B%22+workload%2C+including+all+of+its+default+components%0A%0A%5B%E2%9C%93%5D+Android+Studio+%28version+2022.2%29%0A++++%E2%80%A2+Android+Studio+at+C%3A%5CProgram+Files%5CAndroid%5CAndroid+Studio%0A++++%E2%80%A2+Flutter+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F9212-flutter%0A++++%E2%80%A2+Dart+plugin+can+be+installed+from%3A%0A++++++%F0%9F%94%A8+https%3A%2F%2Fplugins.jetbrains.com%2Fplugin%2F6351-dart%0A++++%E2%80%A2+Java+version+OpenJDK+Runtime+Environment+%28build+17.0.6%2B0-b2043.56-9586694%29%0D%0A%0A%5B%E2%9C%93%5D+Connected+device+%283+available%29%0A++++%E2%80%A2+Windows+%28desktop%29+%E2%80%A2+windows+%E2%80%A2+windows-x64++++%E2%80%A2+Microsoft+Windows+%5BVersion+10.0.22621.1848%5D%0A++++%E2%80%A2+Chrome+%28web%29++++++%E2%80%A2+chrome++%E2%80%A2+web-javascript+%E2%80%A2+Google+Chrome+114.0.5735.134%0A++++%E2%80%A2+Edge+%28web%29++++++++%E2%80%A2+edge++++%E2%80%A2+web-javascript+%E2%80%A2+Microsoft+Edge+114.0.1823.58%0A%0A%5B%E2%9C%93%5D+Network+resources%0A++++%E2%80%A2+All+expected+network+resources+are+available.%0A%0A%21+Doctor+found+issues+in+3+categories.%0A%0A%60%60%60%0A%0A%23%23+Flutter+Application+Metadata%0A%2A%2AType%2A%2A%3A+app%0A%2A%2AVersion%2A%2A%3A+1.0.0%2B1%0A%2A%2AMaterial%2A%2A%3A+true%0A%2A%2AAndroid+X%2A%2A%3A+false%0A%2A%2AModule%2A%2A%3A+false%0A%2A%2APlugin%2A%2A%3A+false%0A%2A%2AAndroid+package%2A%2A%3A+null%0A%2A%2AiOS+bundle+identifier%2A%2A%3A+null%0A%2A%2ACreation+channel%2A%2A%3A+null%0A%2A%2ACreation+framework+version%2A%2A%3A+null%0A%0A&labels=tool%2Csevere%3A+crash

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Failed to find the latest git commit date: VersionCheckError: Command exited with code 128: git -c log.showSignature=false log HEAD -n 1 --pretty=format:%ad --date=iso
Standard out: 
Standard error: fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

Returning 1970-01-01 05:30:00.000 instead.
[!] Flutter (Channel unknown, 0.0.0-unknown, on Microsoft Windows [Version 10.0.22621.1848], locale en-IN)
    ! Flutter version 0.0.0-unknown on channel unknown at C:\src\flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
      Cannot resolve current version, possibly due to local changes.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    • Framework revision  (), 1970-01-01 05:30:00.000
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\MuthuNMK\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.2
    X Android SDK file not found: C:\Users\MuthuNMK\AppData\Local\Android\sdk\build-tools\33.0.2\aapt.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1848]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 114.0.5735.134
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 114.0.1823.58

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

</details>

**Comment by darshankawar** [comment]
@MuthuKrishnan3002 
It seems you are not on a proper framework version, as your `flutter doctor` shows unknown version and that could be causing the error you are reporting. 
Also, it seems the version you are trying to checkout had some errors as mentioned. Try to get / install clean stable version and run your scenario again to see if you still get same error or not.
