### ISSUE TITLE
[Impeller] Be smarter about Vulkan pipeline cache persistence.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#129660]
Today, Vulkan pipeline caches are persisted to disk after a set number of frames ([50 frames from the start or rendering](https://github.com/flutter/engine/blob/6f9cc079605cc71c112a2c8c151fa923e8979e40/impeller/renderer/backend/vulkan/pipeline_library_vk.cc#L668)). Any PSOs created after this point are not persisted. These are usually pipeline derivatives.

This issue tracks caching and persisting more PSOs. The work item may be effected by the efforts to front load PSO derivates creation altogether.

**Comment by chinmaygarde** [comment]
cc @jonahwilliams

**Comment by jonahwilliams** [comment]
potentially dumb idea: every time we add cache a new PSO varaint add a new 50 frame countdown. restart the countdown if an additional variant is added or if they have been pending for too long?

**Comment by chinmaygarde** [comment]
> potentially dumb idea

I would have nodded in agreement if you'd said it was a really great idea.

I like the simplicity. Just save the the cache every 50 frames if there has been a new variant added. I bet that gives us a lot of time before we have to think of anything smarter.

**Comment by psionic12** [comment]
Does metal backend in Impeller also do the pso persistence? As far as I know there's no such thing like `vkGetPipelineCacheData` in metal (correct me if I'm wrong).

**Comment by chinmaygarde** [comment]
@psionic12 Pipeline persistence in general isn't something that we care too much about since all PSO prototypes should be created in a pool and be ready well before the first frame is rendered.

We thought we would have to depend on persistence much more when we initially suspected that variants of PSO would take a super long to construct. But so far, we haven't determined that to be overly concerning after changes to pool worker priorities.

Persistence is much more of a concern in the Skia backend because all PSOs (including prototypes) are created just in time.

Having better persistence mechanism is good since we could save some work on subsequent launches. But it should be immaterial for jank.

For variant construction, we are tracking reducing the number of variants and front-loading their construction instead of having a better persistence mechanism (due to issues with first time launch performance). That preference is reflected in the relatively low priority of this issue.

**Comment by psionic12** [comment]
@chinmaygarde can I understand as this: this issue is to improve Vulkan backend PSOs caching and persisting mechanism because it aggravated jank problems, as for any other backend withouts PSOs persisting, so be it for now?

**Comment by chinmaygarde** [comment]
I filed this somewhat speculatively. We haven't observed the need for this. Closing this as wont-fix.

**Comment by jonahwilliams** [comment]
We now re-persist the pipeline cache N frames after a new variant is created
