### ISSUE TITLE
LUCI infra failure: "build.summary_markdown: too big to accept"

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#129790]
https://chromium-swarm.appspot.com/task?id=63218ab260e2c010&o=true&w=true

```
[W2023-06-29T13:34:13.388307-07:00 19826 0 client.go:357] RPC failed permanently: rpc error: code = InvalidArgument desc = build.summary_markdown: too big to accept (4426 > 4000 bytes) {"host":"cr-buildbucket.appspot.com", "method":"UpdateBuild", "service":"buildbucket.v2.Builds"}
[I2023-06-29T13:34:13.388348-07:00 19826 0 options.go:227] dropped 4 items over 3.1829302s
[E2023-06-29T13:34:13.388433-07:00 19826 0 annotate.go:273] original error: rpc error: code = InvalidArgument desc = build.summary_markdown: too big to accept (4426 > 4000 bytes)

goroutine 1:
From frame 0 to 0, the following wrappers were found:
  internal reason: MultiError 1/1: following first non-nil error.

#0 bbagent/main.go:510 - main.readyToFinalize()
  reason: fatal error in buildbucket.UpdateBuild
```

**Comment by keyonghan** [comment]
The real failure is 
```

**Comment by keyonghan** [comment]
But the markdown summary should be fixed as well.
@christopherfujino do we have a separate bug to track the test failure?

**Comment by keyonghan** [comment]
> The real failure is
> 
> ```
> Waiting for application to render first frame...
> [2023-06-29 13:01:20.017507] [STDOUT] stdout: [+10013 ms] First frame is taking longer than expected...
> [2023-06-29 13:01:20.017637] [STDOUT] stdout: [        ] View ID: _flutterView/0x10483b420
> [2023-06-29 13:01:20.032007] [STDOUT] stdout: [  +14 ms] Isolate isolates/3315763852458143 state:
> [2023-06-29 13:01:20.037333] [STDOUT] stdout: [   +5 ms] {"type":"Isolate","id":"isolates/3315763852458143","number":"3315763852458143","name":"main","isSystemIsolate":false,"isolateGroupId":"isolateGroups/2187587266607717932","isolateFlags":[{"name":"copy_parent_code","valueAsString":"false"},{"name":"is_system_isolate","valueAsString":"false"}],"startTime":1688068868723,"runnable":true,"livePorts":0,"pauseOnExit":false,"pauseEvent":{"type":"Event","kind":"Resume","timestamp":1688068868787,"isolateGroup":{"type":"@IsolateGroup","id":"isolateGroups/2187587266607717932","number":"2187587266607717932","name":"main.dart","isSystemIsolateGroup":false},"isolate":{"type":"@Isolate","id":"isolates/3315763852458143","number":"3315763852458143","name":"main","isSystemIsolate":false,"isolateGroupId":"isolateGroups/2187587266607717932"}},"breakpoints":[],"exceptionPauseMode":"None","rootLib":{"type":"@Library","id":"libraries/@342330433","fixedId":true,"name":"","uri":"package:flutter_view/main.dart"},"extensionRPCs":["ext.ui.window.impellerEnabled","ext.dart.io.getHttpEnableTimelineLogging","ext.dart.io.setHttpEnableTimelineLogging","ext.dart.io.httpEnableTimelineLogging","ext.dart.io.getSocketProfile","ext.dart.io.startSocketProfiling","ext.dart.io.pauseSocketProfiling","ext.dart.io.socketProfilingEnabled","ext.dart.io.clearSocketProfile","ext.dart.io.getVersion","ext.dart.io.getHttpProfile","ext.dart.io.getHttpProfileRequest","ext.dart.io.clearHttpProfile","ext.flutter.exit","ext.flutter.connectedVmServiceUri","ext.flutter.activeDevToolsServerAddress","ext.flutter.timeDilation","ext.flutter.debugDumpRenderTree","ext.flutter.debugDumpSemanticsTreeInTraversalOrder","ext.flutter.debugDumpSemanticsTreeInInverseHitTestOrder","ext.flutter.profileRenderObjectPaints","ext.flutter.profileRenderObjectLayouts","ext.flutter.debugDumpApp","ext.flutter.debugDumpFocusTree","ext.flutter.showPerformanceOverlay","ext.flutter.didSendFirstFrameEvent","ext.flutter.didSendFirstFrameRasterizedEvent","ext.flutter.fastReassemble","ext.flutter.profileWidgetBuilds","ext.flutter.profileUserWidgetBuilds"]}
> [2023-06-29 13:01:20.037395] [STDOUT] stdout: [        ] Received VM events:
> [2023-06-29 13:01:20.037463] [STDOUT] stdout: [        ] Flutter.ServiceExtensionStateChanged: [ExtensionData {extension: ext.flutter.activeDevToolsServerAddress, value: http://127.0.0.1:9104/}]
> [2023-06-29 13:01:20.037493] [STDOUT] stdout:            Flutter.ServiceExtensionStateChanged: [ExtensionData {extension: ext.flutter.connectedVmServiceUri, value: http://127.0.0.1:51102/n18v17LclxU=/}]
> ```

@vashworth Do we have an ios bug tracking this issue already?

**Comment by vashworth** [comment]
> @vashworth Do we have an ios bug tracking this issue already?

I just made a issue to track this error: https://github.com/flutter/flutter/issues/129836

**Comment by keyonghan** [comment]
> > @vashworth Do we have an ios bug tracking this issue already?
> 
> I just made a issue to track this error: #129836

Thank you @vashworth !

**Comment by ricardoamador** [comment]
It might be possible that some functionality was removed recently which caused this. This seems to not be happening very frequently, leaving as P2.

**Comment by godofredoc** [comment]
We haven't seen this issue in a long time. Closing as not replicable.
