### ISSUE TITLE
`waiting for customer response` being incorrectly removed

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#129771]
Triagers have noticed that `waiting for customer response` is being seemingly randomly removed from issues. Examples:
- https://github.com/flutter/flutter/issues/129738 where it was removed almost immediately after being added.
- https://github.com/flutter/flutter/issues/128945 where it was removed after about a week, but without any comments.
- https://github.com/flutter/flutter/issues/128921 where is was removed once with no triggering event, and then again either for a comment by someone other than the OP, or maybe randomly but coincidentally after the comment.

Having this label being randomly removed will make it much harder for us to keep un-actionable issues from accumulating in the issue systme.

**Comment by godofredoc** [comment]
@stuartmorgan  Is this still happening? we started the migration to the core action but it seems like we'll need to rollback to my fork because the processing in the core action does not scale well beyond a couple hundred open bugs + prs.

The errors linked to the bug were most likely during the transition period when we were adjusting the parameters.

**Comment by stuartmorgan** [comment]
When was that transition period? The first one in the list happened 5 hours ago.

**Comment by iDarkQ** [comment]
it happened just as well with one of my issues #128935. (Although I already responded, I don't know if it matters).

**Comment by godofredoc** [comment]
Hi @iDarkQ in your bug the label was removed correctly after the P2 label was added:

![image](https://github.com/flutter/flutter/assets/54371434/42a45cb1-773b-4a20-8f23-c3b3c089b00b)

**Comment by iDarkQ** [comment]
@godofredoc Hi, sorry yeah I haven't noticed it. Thanks

**Comment by keyonghan** [comment]
@stuartmorgan Do you still happen to see the issue with the revert?

**Comment by keyonghan** [comment]
Thanks @stuartmorgan . Closing here, and feel free to reopen.
