### ISSUE TITLE
Specific emoji not displaying correctly on ios

### ISSUE THREAD

**Issue by kaisar945** [flutter/flutter#129703]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Focus input box
2. Input 0️⃣ emoji

### Expected results

correct display

### Actual results

not displayed correctly

### Code sample

<details><summary>Code sample</summary>

```dart
SizedBox(
            height: 120,
            child: TextField(
              decoration: InputDecoration(
                fillColor: const Color(0xfff5f5f5),
                filled: true,
                border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(8),
                    borderSide: const BorderSide(color: AppColors.dividing_line, width: 0.7)),
                hintText: widget.replyUserName != null ? '@${widget.replyUserName}' : '写评论',
                contentPadding: const EdgeInsets.all(10),
                focusedBorder: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(8),
                    borderSide: const BorderSide(color: AppColors.dividing_line, width: 0.7)),
              ),
              onTap: () => onTextFieldTap(),
              cursorColor: AppColors.f333,
              cursorHeight: 18,
              keyboardType: TextInputType.multiline,
              maxLength: widget.count,
              maxLines: 6,
              style: const TextStyle(fontSize: 14, color: Colors.black),
              textAlign: TextAlign.start,
              controller: controller,
              autofocus: true,
            ),
          ),
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]
![image](https://github.com/flutter/flutter/assets/5535373/3c4551f2-3cd7-4def-b696-7bae6684acbe)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @kaisar945, this is a known issue and it's being tracked in https://github.com/flutter/flutter/issues/115517. 

Kindly follow up in the original issue for updates. 

Closing from here as duplicate. 

Thank youj
