### ISSUE TITLE
Support top notch bezels on Android

### ISSUE THREAD

**Issue by xster** [flutter/flutter#12979]
Support top notch like iPhone X on Android phones like the Essential Phone. It currently adds letterbox bars.

![img_2803](https://user-images.githubusercontent.com/156888/32682883-5501f320-c62c-11e7-885e-b00b1fc55e50.png)

There's probably a flag we need to set in the AndroidManifest and then pass in the right values in the engine to MediaQuery

**Comment by xster** [comment]
Compare with apps supporting notch (Google Play Music)

![img_2804](https://user-images.githubusercontent.com/156888/32683011-e3219962-c62c-11e7-82b3-f303e282990f.jpg)

**Comment by cbracken** [comment]
@xster is this still an issue? After the work I landed for the iPhone X, it appeared to be working on the Essential phone.

**Comment by xster** [comment]
SG. Let's keep those in separate bugs.
