### ISSUE TITLE
MediaQuery padding not respected when changing global font size

### ISSUE THREAD

**Issue by xster** [flutter/flutter#12978]
Didn't find a dupe. When changing accessible font size in the gallery drawer, the system padding (status bar etc) is no longer respected.

![flutter_01](https://user-images.githubusercontent.com/156888/32682009-2dce2c6a-c627-11e7-9116-c8434b715797.png)

Going back to system default size restores it. 

cc @goderbauer

**Comment by goderbauer** [comment]
@gspencergoog

**Comment by zoechi** [comment]
Looks good on my Pixel XL even when I set the font size to largest.

**Comment by rami-a** [comment]
This does not appear to be the case any more. Since the bug was opened a few years ago, it must have been fixed since then. Closing for now, please re-open if you can still repro.
