### ISSUE TITLE
[Impeller] Vulkan: Clearing signaled fences and calling dtors stalls fence waiter.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#129737]
This will delay all further deallocations. On this run on CI, the waiter was stalled for more than 5 frames. That means the tracked resources in the command buffer were not collected during this time. This increases peak memory usage and probably also puts pressure on the allocator as it cannot reuse memory and must allocate newer arenas. [The trace is added here](https://github.com/flutter/engine/blob/4e49b9deb72d1c33fa8dc9f0a5358cda42d8d07c/impeller/renderer/backend/vulkan/fence_waiter_vk.cc#L168).

<img width="1315" alt="Screenshot 2023-06-28 at 12 28 33 PM" src="https://github.com/flutter/flutter/assets/44085/7338ade5-7543-4963-8de7-d9f5ba766bf7">

**Comment by jonahwilliams** [comment]
I guess you can't say "fix" and issue too close together.

**Comment by chinmaygarde** [comment]
We have fixed the issue of the dtors being slow which effectively fixes the stall. We should figure out if there is anything to do w.r.t tossing the dtors onto the pool and off the waiter thread so we can never stall on a user workload.
