### ISSUE TITLE
RaisedButton at the bottom of a Stack still appears at the top of the Stack in Fuchsia

### ISSUE THREAD

**Issue by maryx** [flutter/flutter#12975]
## Steps to Reproduce
In regular Flutter, if I have something like this (edited the sample app):
```dart
    return new Scaffold(
      appBar: new AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: new Text(widget.title),
      ),
      body: new Stack(
        children: <Widget>[
          new RaisedButton(
            onPressed: _incrementCounter,
            child: new Icon(Icons.add),
          ),
          new Container(
            width: 300.0,
            height: 300.0,
            color: Colors.pink,
          ),
        ],
      ),
      floatingActionButton: new RaisedButton(
        onPressed: _incrementCounter,
        child: new Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
```
I get something like this, where the RaisedButton is correctly hidden by the Container.
![screenshot from 2017-11-10 13 17 44](https://user-images.githubusercontent.com/3357543/32679232-7c58c550-c61a-11e7-81c1-1f98abba55a8.png)

In Fuchsia Flutter, if I have something like this in a build function:
```
    return new Scaffold(
      body: new Stack(
        children: <Widget>[
          new RaisedButton(
            onPressed: _justPrint,
            child: new Icon(Icons.add),
          ),
          new Container(
            color: Colors.pink,
            height: 300.0,
            width: 500.0,
          ),
        ],
      ),
    );
```
I get this. Notably, pressing on the RaisedButton doesn't call my onPressed function.
![wp_20171110_001](https://user-images.githubusercontent.com/3357543/32679295-cb0011cc-c61a-11e7-99ad-adeccb234df1.jpg)

## Logs
Let me know what logs I should post

## Flutter Doctor
[✓] Flutter (on Linux, locale en_US.UTF-8, channel unknown)
    • Flutter at /usr/local/google/home/me/fuchsia/third_party/dart-pkg/git/flutter
    • Framework revision 21145144e9 (11 days ago), 2017-10-30 12:28:31 -0700
    • Engine revision ec19da1c80
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /usr/local/google/home/me/Android/Sdk
    • Platform android-26, build-tools 26.0.1
    • Java binary at: /opt/android-studio-2.4/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b736)

[✓] Android Studio (version 2.4)
    • Android Studio at /opt/android-studio-2.4
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b736)

[✓] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 18.1
    • Dart plugin version 172.3968.27

[✓] Connected devices
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 7.1.1 (API 25) (emulator)

**Comment by eseidelGoogle** [comment]
I believe this is expected behavior from the PhysicalModelLayer.  Thoughts @abarth?

**Comment by Hixie** [comment]
This is working as intended; the `elevation` of the RaisedButton is higher than the elevation of the rest of the `Stack`. You can wrap things in a `Material` with its own `elevation` to put them higher.

**Comment by maryx** [comment]
I'm confused as to why this elevation behavior is to be expected only on Fuchsia, not on the regular Android emulator.

Thanks, wrapping my Container in a Material and increasing the elevation worked.

**Comment by Hixie** [comment]
@maryx We don't implement true elevation on Android, because it's not something Android supports.

**Comment by maryx** [comment]
Ah, ok, thanks for the explanation. Closing issue.
