### ISSUE TITLE
[Impeller] Swapchain re-creation has unresolved issues on some non-ARM devices.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#129774]

**Comment by chinmaygarde** [comment]
This was brought up in the weekly sync by @jonahwilliams. Creating a stub so we make sure we followup.

**Comment by jonahwilliams** [comment]
Actually this issue isn't ARM vs non-ARM: devices older than Android 10 don't support checking for suboptimal KHR, so instead we need to query the current swapchain transform every N frames to determine if it needs to be recreated.

**Comment by jonahwilliams** [comment]
oh, wait no this phone says its Android 11 WTF

**Comment by chinmaygarde** [comment]
The polling was completed in https://github.com/flutter/engine/pull/44361 by @matanlurey. I think that the last remaining item but I may be wrong.

**Comment by jonahwilliams** [comment]
That matches my understanding. There may be optimizations we can make to this process if we establish some version floor where devices _correctly_ report suboptimalKHR, but we can file that as a follow up.
