### ISSUE TITLE
[in_app_purchase][iOS] The Callback from the apple store doe not include the applicationUsername value passed while purchasing the package.

### ISSUE THREAD

**Issue by imsujan276** [flutter/flutter#129758]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Buy a subscription using in_app_purchase.
2. subscription purchase success
3. you receive a webhook callback from the Apple app store connect to your server.
4.  on decoding the JWT token, I do not see any key related to the passed **applicationUserName** value

JSON callback I got in server:
```
{
  "notificationType": "DID_RENEW",
  "notificationUUID": "910a5366...",
  "data": {
    "appAppleId": 1667...,
    "bundleId": "com.example.app",
    "bundleVersion": "18",
    "environment": "Sandbox",
    "signedTransactionInfo": "eyJhbGciOiJFUzI1NiIsIng1YyI....",
    "signedRenewalInfo": "eyJhbGciOiJFUzI1NiIsIng1YyI6WyJNS...",
    "status": 1
  },
  "version": "2.0",
  "signedDate": 1688...
}
```

On decoding the **signedTransactionInfo**, I got the following

```
{
  "transactionId": "2000000359348309",
  "originalTransactionId": "2000000352850885",
  "webOrderLineItemId": "2000000030762156",
  "bundleId": "com.example.app",
  "productId": "com.example.app.premium",
  "subscriptionGroupIdentifier": "21307423",
  "purchaseDate": 1688025839000,
  "originalPurchaseDate": 1687171395000,
  "expiresDate": 1688026139000,
  "quantity": 1,
  "type": "Auto-Renewable Subscription",
  "inAppOwnershipType": "PURCHASED",
  "signedDate": 1688025830811,
  "environment": "Sandbox",
  "transactionReason": "RENEWAL",
  "storefront": "CAN",
  "storefrontId": "143455"
}
```

I tried checking it with the **transactionId**, but it also changes after a few tries on the same user.

### Expected results

The callback JWT to include the **applicationUserName** value so that we can check the user by the value and perform task

### Actual results

The callback JWT does not include any attribute related to the value passed in **applicationUsername** param.

### Code sample

<details><summary>Code sample to buy a subscription</summary>

```dart
    await iapInstance.buyNonConsumable(
        purchaseParam: PurchaseParam(
          productDetails: productDetails,
          applicationUserName: authCubit.state.authUserModel.user.uniqueId,
        ),
      );
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.10.4, on macOS 13.4.1 22F82 darwin-x64, locale en-US)
    • Flutter version 3.10.4 on channel stable at /Volumes/D/flutter/Flutter-SDK
    ! Warning: `flutter` on your path resolves to /Volumes/D/Flutter/Flutter-SDK/bin/flutter, which is not inside your current Flutter
      SDK checkout at /Volumes/D/flutter/Flutter-SDK. Consider adding /Volumes/D/flutter/Flutter-SDK/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /usr/local/Cellar/dart/3.0.4/libexec/bin/dart, which is not inside your current Flutter
      SDK checkout at /Volumes/D/flutter/Flutter-SDK. Consider adding /Volumes/D/flutter/Flutter-SDK/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 682aa387cf (3 weeks ago), 2023-06-05 18:04:56 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update
      checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/suzzan/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/suzzan/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/suzzan/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.4.1 22F82 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by dam-ease** [comment]
Hi @imsujan276. Thanks for filing this issue. [The documentation](https://developer.apple.com/documentation/storekit/skmutablepayment/1506088-applicationusername?language=objc) advocates the use of a UUID for `applicationUsername`, and suggests that as long as a UUID _is_ used, it will persist. The case you described might be similar to https://github.com/flutter/flutter/issues/109672. Can you confirm if it is??

**Comment by imsujan276** [comment]
Hi @dam-ease. Thank you for your response. Before posting this issue, I went through [#109672](https://github.com/flutter/flutter/issues/109672). 

I am not using the **applicationUsername**  in the app but using it in the callback only. What I am facing is that I am not getting the ** applicationUsername** in the callback from the app store connect. So, I assume that we are not facing similar issue.

**Comment by danagbemava-nc** [comment]
Hi @imsujan276, if you're not setting the `applicationUsername` in the app then I'm not sure this is an issue with the iap plugin. It may be that the appstore is just not returning it. At what point in your iap flow is the callback that you set the `applicationUsername` called? 
As requested above, is the applicationUsername that you set a valid UUID? 

Can you also try setting the applicationUsername in the app to see if it is returned in the app?

Thank you

**Comment by imsujan276** [comment]
Yes, I am sending a valid UUID while buying the subscription.

**Comment by danagbemava-nc** [comment]
Hi @imsujan276, have you tried setting applicationUsername before you receive the callback from the app store to see if you receive it after the transaction is processed?

**Comment by imsujan276** [comment]
Yeah, as you can see in the code sample, I am passing the UUID as uniqueId.

```
await iapInstance.buyNonConsumable(
        purchaseParam: PurchaseParam(
          productDetails: productDetails,
          applicationUserName: authCubit.state.authUserModel.user.uniqueId,
        ),
      );
```

**Comment by danagbemava-nc** [comment]
Hi @imsujan276,  my apologies, I missed that part. 

Looking at the decoded transaction, it looks like it's for a subscription renewal. Do you have the same issue with a new subscription/purchase? Unfortunately, the docs aren't very clear on which state returns the data.

Also, if you try to verify the receipt does it come back with the data?

Please note that the field will not come back as applicationUsername but as either appAccountName or app_account_name depending on which method is used. 

Thank you

**Comment by imsujan276** [comment]
Created a new flutter project, transferred all the codes, and setup In-App purchase and it worked. I do not know how but strangely it worked.

**Comment by dam-ease** [comment]
Hi @imsujan276. Thanks for confirming. I guess it's safe to close this issue then. If you encounter the issue again or have more info on this kindly comment. Thank you!
