### ISSUE TITLE
widgets/basic_test.dart failures when switching to M3

### ISSUE THREAD

**Issue by bleroux** [flutter/flutter#129713]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

When switching to M3 (see https://github.com/flutter/flutter/pull/127501), there are two tests failures in packages/flutter/test/widgets/basic_test.dart:

https://github.com/flutter/flutter/blob/70b9dd707014ff7e715982e64ef16403a2738472/packages/flutter/test/widgets/basic_test.dart#L456

https://github.com/flutter/flutter/blob/70b9dd707014ff7e715982e64ef16403a2738472/packages/flutter/test/widgets/basic_test.dart#L509

Those failures are related to M3 typography which sets line height to 1.43.

### Expected results

All tests run successfully

### Actual results

2 tests fail

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: <114.0>
  Actual: <157.60000038146973>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure>.<anonymous closure> (file:///home/bruno/Nevercode/flutter/packages/flutter/test/widgets/basic_test.dart:504:7)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///home/bruno/Nevercode/flutter/packages/flutter/test/widgets/basic_test.dart line 504
The test description was:
  multiple baseline aligned children
════════════════════════════════════════════════════════════════════════════════════════════════════

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: <30.0>
  Actual: <38.60000038146973>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure>.<anonymous closure> (file:///home/bruno/Nevercode/flutter/packages/flutter/test/widgets/basic_test.dart:557:7)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///home/bruno/Nevercode/flutter/packages/flutter/test/widgets/basic_test.dart line 557
The test description was:
  baseline aligned children account for a larger, no-baseline child size
════════════════════════════════════════════════════════════════════════════════════════════════════
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by HansMuller** [comment]
These failures may have been resolved by https://github.com/flutter/flutter/pull/129683 (which just landed).

**Comment by bleroux** [comment]
https://github.com/flutter/flutter/pull/129683 sets `useMaterial3` to false, I thought It was something we want to avoid?
I was thinking about the day when `useMaterial3` will be be deprecated but this is probably more of a long term goal.

**Comment by HansMuller** [comment]
The process we're following for changing the default value of `useMaterial3` from false to true is outlined here: https://github.com/flutter/flutter/issues/127064. Currently we're on "step 1", which is to say that we've updated the repo so that changing the default would not cause any presubmit tests to fail. The PRs listed in step 1 were tested with `useMaterial3: true` by default, but landed without that change. The actual change to the default will not happen for a couple of weeks.
