### ISSUE TITLE
Embedder uses too many surfaces for platform views

### ISSUE THREAD

**Issue by knopp** [flutter/flutter#129710]
Here is example application that has 4 platform views interleaved with Flutter content:

<img width="883" alt="Screenshot 2023-06-28 at 14 22 26" src="https://github.com/flutter/flutter/assets/96958/9dca6dcd-6fe0-4eb9-8300-1a58465d0f5d">

It uses a total of 5 surfaces, each one has size of entire window (because resizing surfaces is expensive). However there is no content directly painted over platform view so this entire scene could be rendered to the background surface and the end result would be same, saving 4 surfaces.

Another example - 4 platform views with Flutter content painted above the views:

<img width="883" alt="Screenshot 2023-06-28 at 14 21 51" src="https://github.com/flutter/flutter/assets/96958/26c9ecb2-24b9-4716-815d-04adc1a5c220">

This still uses 5 surfaces, but the same visual result can be represented by only two surfaces - content that is painted below platform views in first surface and content that is painted above platform views in second surface.

Same scene, painted with https://flutter.dev/go/optimized-platform-view-layers:

https://github.com/flutter/flutter/assets/96958/091da832-bfbc-44a2-8da5-d55d84024c96

Initially, there are two surface, but as they move to not paint over platform views, only one surface remains.

**Comment by stuartmorgan** [comment]
Won't this potentially create a lot of view allocation and destruction during animation?

**Comment by llooz** [comment]
Hi @knopp, 
do you think that https://github.com/flutter/engine/pull/43301 could have a positive impact on https://github.com/flutter/flutter/issues/129632?

**Comment by knopp** [comment]
> Hi @knopp,
> do you think that [flutter/engine#43301](https://github.com/flutter/engine/pull/43301) could have a positive impact on #129632?

Unlikely, because iOS doesn't use the embedder API and the platform view implementation is very much different between these two. It *might* eventually get migrated to embedder API, which in my opinion should improve platform view performance quite a bit, but I'm not aware of any timeline for this.

**Comment by jwinarske** [comment]
@knopp Is this example available somewhere?  I have started work on platform views support for Wayland compositor on Linux, and this would be a great starting point.

**Comment by knopp** [comment]
> @knopp Is this example available somewhere? I have started work on platform views support for Wayland compositor on Linux, and this would be a great starting point.

https://github.com/knopp/layer_playground

Might not be up-to-date with latest platform view API in Flutter though.

**Comment by jwinarske** [comment]
@knopp great thanks!

**Comment by renanyoy** [comment]
This fix removed the ability to use Opacity(...) on platform views, platform views are only displayed when opacity = 1 now and hidden otherwise.

**Comment by knopp** [comment]
I seem to be unable to reproduce this with [layer_playground](https://github.com/knopp/layer_playground) example:

<img width="797" alt="Screenshot 2023-12-05 at 10 55 56" src="https://github.com/flutter/flutter/assets/96958/a7bf0d38-aa95-4730-bc06-73eb25454f0f">

(blue rectangles are platform views wrapped with 0.5 Opacity). So there must be some additional factor.
