### ISSUE TITLE
flutter_markdown doesn't work style the blockquote

### ISSUE THREAD

**Issue by HelenCrisM** [flutter/flutter#129798]
```
 Markdown(
                      physics: const BouncingScrollPhysics(),
                      data: bodyPost,
                      shrinkWrap: true,
                      styleSheet: MarkdownStyleSheet(
                        blockquote: const TextStyle(
                          color: Colors.grey,
                          fontStyle: FontStyle.italic,
                          fontSize: 40,
                        ),
                      ),
                    ),
```

**Comment by darshankawar** [comment]
@HelenCrisM 
There are already [open issues](https://github.com/flutter/flutter/issues?q=label%3A%22p%3A+flutter_markdown%22+blockquote+is%3Aopen) related to `flutter_markdown` and `blockquote` that you can go through and check which one resembles your issue or not.

**Comment by HelenCrisM** [comment]
I already saw the other issues but I didn't found  any related to my problem

**Comment by HelenCrisM** [comment]
Markdown(
physics: const BouncingScrollPhysics(),
data: bodyPost,
shrinkWrap: true,
styleSheet: MarkdownStyleSheet(
blockquoteDecoration: const BoxDecoration(color: null),
blockquote: const TextStyle(
color: Colors.grey,
fontStyle: FontStyle.italic,
fontSize: 40,
),
),
),


with blockquoteDecoration I could be able to not show the default background color, but I don't know why the blockquote doesn't work, I tried to change the text color to grey, but doesn't work. 

![screenshot](https://github.com/flutter/flutter/assets/132611595/4c289e4a-25ae-448c-aace-8b8cd5c678b1)

**Comment by darshankawar** [comment]
I think you are hitting https://github.com/flutter/flutter/issues/81720 which most likely discusses same issue as you are reporting. So I suggest you to follow-up in it for further updates.
You can try [this](https://github.com/flutter/flutter/issues/81720#issuecomment-1324810923) workaround and see if it helps in your case or not.

Closing as a duplicate. If you disagree, write in comments and I'll reopen it.
