### ISSUE TITLE
[quick_actions] ios add option to use localizedSubtitle

### ISSUE THREAD

**Issue by CyberNyanta** [flutter/flutter#129759]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Can we add to ShortcutItem localizedSubTitle filed to use?

![image](https://github.com/flutter/flutter/assets/10977301/d1710409-b73e-440b-9607-948213b0eacf)
 

### Proposal

Add option to add subtitle, not sure it's possible on Android 
but it's already even in ios 
packages/quick_actions/quick_actions_ios/ios/Classes/ShortcutItemParser.swift
<img width="460" alt="image" src="https://github.com/flutter/flutter/assets/10977301/3bb579f2-1dc1-4364-997d-db165d064d6a">

**Comment by zhusupq** [comment]
Any update?
