### ISSUE TITLE
[Desktop] How long do we have to wait to use the desktop's multi-window feature? This is an important feature for desktop developers.

### ISSUE THREAD

**Issue by ImagineBoom** [flutter/flutter#129761]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Desktop-side software usually sets up pages in a second window, so multi-window functionality is required.

### Proposal

We've seen multi-window project, but we don't get a known wait time.

**Comment by danagbemava-nc** [comment]
Hi @ImagineBoom, there is no eta on this feature at the moment. 

Kindly subscribe to the original tracking issue for further updates. https://github.com/flutter/flutter/issues/30701

Closing from here as duplicate. 

Thank you
