### ISSUE TITLE
NestedScrollView with sliver headers scrolling doesn't have a fade animation anymore

### ISSUE THREAD

**Issue by appcapsergen** [flutter/flutter#129767]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Install flutter 3.10.3 to see how it's supposed to work and 3.10.4 or 3.10.5 to see it being broken.
2. Use a NestedScrollView with sliver headers. Make sure there's at least a SliverAppBar at the top with FlexibleSpaceBar with collapseMode: CollapseMode.pin.
3. Scroll down and see if the app bar fades away or not.

### Expected results

https://github.com/flutter/flutter/assets/94898347/615f576a-4ab1-47cd-803a-8aabdbbd01c7

### Actual results

https://github.com/flutter/flutter/assets/94898347/11d8a743-9b7c-4bd6-8ee2-b1ed0ad80536

### Code sample

<details><summary>Code sample</summary>

```dart
NestedScrollView(
  controller: scrollController,
  physics: const ClampingScrollPhysics(),
  headerSliverBuilder: (BuildContext context, _) => <Widget>[
    _buildAppBar(context),
    _buildTabBar(context),
  ],
  body: _buildTabBarView(context),
);
```

</details>

### Screenshots or Video

See Expected/Actual results

### Logs

N/A

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.3, on macOS 13.4.1 22F82 darwin-arm64, locale en-NL)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.73.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by dam-ease** [comment]
Hi @appcapsergen. Thanks for filing this issue. This seems to be a duplicate of a currently open issue https://github.com/flutter/flutter/issues/128636. Kindly confirm it is

**Comment by appcapsergen** [comment]
> Hi @appcapsergen. Thanks for filing this issue. This seems to be a duplicate of a currently open issue #128636. Kindly confirm it is

Yes, that does seem to be the same!! Thank you 😄
