### ISSUE TITLE
My flutter windows app crashes on Windows 7

### ISSUE THREAD

**Issue by armin1440** [flutter/flutter#129716]
### Steps to reproduce

I have a flutter windows app and I want to install it on windows 7. I make a msi or exe setup file and I install it on a device which has windows 7 installed on. Then I open it and start using it.

### Expected results

It should work perfectly fine with no crashes.

### Actual results

It crashes and I have to close the program. It does not follow certain behavior. Sometimes it crashes right after I click on a button and sometimes it crashes after multiple clicks on the button. I managed to log in my app only once.

### Code sample

<details><summary>No Code Sample Included</summary>
</details>

### Logs

<details><summary>The content of Microsoft crash dump output file</summary>

```console
Version=1
EventType=APPCRASH
EventTime=133324069424034173
ReportType=2
Consent=1
ReportIdentifier=234ce5b5-157c-11ee-bca8-0050568d0296
IntegratorReportIdentifier=234ce5b4-157c-11ee-bca8-0050568d0296
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=weight_and_balance.exe
Sig[1].Name=Application Version
Sig[1].Value=2.9.8.298
Sig[2].Name=Application Timestamp
Sig[2].Value=649983b6
Sig[3].Name=Fault Module Name
Sig[3].Value=flutter_windows.dll
Sig[4].Name=Fault Module Version
Sig[4].Value=0.0.0.0
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=64790a95
Sig[6].Name=Exception Code
Sig[6].Value=40000015
Sig[7].Name=Exception Offset
Sig[7].Value=0000000000d1688f
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=6.1.7601.2.1.0.256.1
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=0f3a
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=0f3a7c0b74c0a6caf2a585a46e394e51
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=eabd
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=eabd85054cf1c101dd5df0be785f7823
UI[2]=C:\Program Files (x86)\Your Company\Weight & Balance\New folder\weight_and_balance.exe
UI[3]=weight_and_balance has stopped working
UI[4]=Windows can check online for a solution to the problem.
UI[5]=Check online for a solution and close the program
UI[6]=Check online for a solution later and close the program
UI[7]=Close the program
LoadedModule[0]=C:\Program Files (x86)\Your Company\Weight & Balance\New folder\weight_and_balance.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\system32\kernel32.dll
LoadedModule[3]=C:\Windows\system32\KERNELBASE.dll
LoadedModule[4]=C:\Windows\system32\dwmapi.dll
LoadedModule[5]=C:\Windows\system32\msvcrt.dll
LoadedModule[6]=C:\Windows\system32\GDI32.dll
LoadedModule[7]=C:\Windows\system32\USER32.dll
LoadedModule[8]=C:\Windows\system32\LPK.dll
LoadedModule[9]=C:\Windows\system32\USP10.dll
LoadedModule[10]=C:\Program Files (x86)\Your Company\Weight & Balance\New folder\auto_updater_plugin.dll
LoadedModule[11]=C:\Program Files (x86)\Your Company\Weight & Balance\New folder\WinSparkle.dll
LoadedModule[12]=C:\Windows\system32\RPCRT4.dll
LoadedModule[13]=C:\Windows\system32\VERSION.dll
LoadedModule[14]=C:\Windows\system32\WININET.dll
LoadedModule[15]=C:\Windows\system32\api-ms-win-downlevel-user32-l1-1-0.dll
LoadedModule[16]=C:\Windows\system32\api-ms-win-downlevel-shlwapi-l1-1-0.dll
LoadedModule[17]=C:\Windows\system32\shlwapi.DLL
LoadedModule[18]=C:\Windows\system32\api-ms-win-downlevel-version-l1-1-0.dll
LoadedModule[19]=C:\Windows\system32\api-ms-win-downlevel-normaliz-l1-1-0.dll
LoadedModule[20]=C:\Windows\system32\normaliz.DLL
LoadedModule[21]=C:\Windows\system32\iertutil.dll
LoadedModule[22]=C:\Windows\system32\api-ms-win-downlevel-advapi32-l1-1-0.dll
LoadedModule[23]=C:\Windows\system32\advapi32.DLL
LoadedModule[24]=C:\Windows\SYSTEM32\sechost.dll
LoadedModule[25]=C:\Windows\system32\USERENV.dll
LoadedModule[26]=C:\Windows\system32\profapi.dll
LoadedModule[27]=C:\Windows\system32\SHELL32.dll
LoadedModule[28]=C:\Windows\system32\UxTheme.dll
LoadedModule[29]=C:\Windows\system32\CRYPT32.dll
LoadedModule[30]=C:\Windows\system32\MSASN1.dll
LoadedModule[31]=C:\Windows\system32\MSIMG32.dll
LoadedModule[32]=C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.7601.18837_none_fa3b1e3d17594757\COMCTL32.dll
LoadedModule[33]=C:\Windows\system32\ole32.dll
LoadedModule[34]=C:\Windows\system32\OLEAUT32.dll
LoadedModule[35]=C:\Program Files (x86)\Your Company\Weight & Balance\New folder\flutter_windows.dll
LoadedModule[36]=C:\Windows\system32\IPHLPAPI.DLL
LoadedModule[37]=C:\Windows\system32\NSI.dll
LoadedModule[38]=C:\Windows\system32\WINNSI.DLL
LoadedModule[39]=C:\Windows\system32\PSAPI.DLL
LoadedModule[40]=C:\Windows\system32\WINMM.dll
LoadedModule[41]=C:\Windows\system32\WS2_32.dll
LoadedModule[42]=C:\Windows\system32\IMM32.dll
LoadedModule[43]=C:\Windows\system32\MSCTF.dll
LoadedModule[44]=C:\Windows\system32\OPENGL32.dll
LoadedModule[45]=C:\Windows\system32\GLU32.dll
LoadedModule[46]=C:\Windows\system32\DDRAW.dll
LoadedModule[47]=C:\Windows\system32\DCIMAN32.dll
LoadedModule[48]=C:\Windows\system32\SETUPAPI.dll
LoadedModule[49]=C:\Windows\system32\CFGMGR32.dll
LoadedModule[50]=C:\Windows\system32\DEVOBJ.dll
LoadedModule[51]=C:\Windows\system32\bcrypt.dll
LoadedModule[52]=C:\Windows\system32\OLEACC.dll
LoadedModule[53]=C:\Windows\system32\UIAutomationCore.DLL
LoadedModule[54]=C:\Windows\system32\PROPSYS.dll
LoadedModule[55]=C:\Windows\system32\dxgi.dll
LoadedModule[56]=C:\Windows\system32\d3d9.dll
LoadedModule[57]=C:\Windows\system32\d3d8thk.dll
LoadedModule[58]=C:\Windows\system32\MSVCP140.dll
LoadedModule[59]=C:\Windows\system32\VCRUNTIME140.dll
LoadedModule[60]=C:\Windows\system32\api-ms-win-crt-runtime-l1-1-0.dll
LoadedModule[61]=C:\Windows\system32\ucrtbase.DLL
LoadedModule[62]=C:\Windows\system32\api-ms-win-core-timezone-l1-1-0.dll
LoadedModule[63]=C:\Windows\system32\api-ms-win-core-file-l2-1-0.dll
LoadedModule[64]=C:\Windows\system32\api-ms-win-core-localization-l1-2-0.dll
LoadedModule[65]=C:\Windows\system32\api-ms-win-core-synch-l1-2-0.dll
LoadedModule[66]=C:\Windows\system32\api-ms-win-core-processthreads-l1-1-1.dll
LoadedModule[67]=C:\Windows\system32\api-ms-win-core-file-l1-2-0.dll
LoadedModule[68]=C:\Windows\system32\api-ms-win-crt-heap-l1-1-0.dll
LoadedModule[69]=C:\Windows\system32\api-ms-win-crt-string-l1-1-0.dll
LoadedModule[70]=C:\Windows\system32\api-ms-win-crt-stdio-l1-1-0.dll
LoadedModule[71]=C:\Windows\system32\api-ms-win-crt-convert-l1-1-0.dll
LoadedModule[72]=C:\Program Files (x86)\Your Company\Weight & Balance\New folder\VCRUNTIME140_1.dll
LoadedModule[73]=C:\Windows\system32\api-ms-win-crt-locale-l1-1-0.dll
LoadedModule[74]=C:\Windows\system32\api-ms-win-crt-filesystem-l1-1-0.dll
LoadedModule[75]=C:\Windows\system32\api-ms-win-crt-time-l1-1-0.dll
LoadedModule[76]=C:\Windows\system32\api-ms-win-crt-environment-l1-1-0.dll
LoadedModule[77]=C:\Windows\system32\api-ms-win-crt-math-l1-1-0.dll
LoadedModule[78]=C:\Windows\system32\api-ms-win-crt-utility-l1-1-0.dll
LoadedModule[79]=C:\Program Files (x86)\Your Company\Weight & Balance\New folder\connectivity_plus_plugin.dll
LoadedModule[80]=C:\Program Files (x86)\Your Company\Weight & Balance\New folder\printing_plugin.dll
LoadedModule[81]=C:\Program Files (x86)\Your Company\Weight & Balance\New folder\pdfium.dll
LoadedModule[82]=C:\Windows\system32\WINSPOOL.DRV
LoadedModule[83]=C:\Windows\system32\COMDLG32.dll
LoadedModule[84]=C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.7601.18837_none_a4d981ff711297b6\COMCTL32.dll
LoadedModule[85]=C:\Program Files (x86)\Your Company\Weight & Balance\New folder\url_launcher_windows_plugin.dll
LoadedModule[86]=C:\Windows\system32\CRYPTBASE.dll
LoadedModule[87]=C:\Windows\system32\IconCodecService.dll
LoadedModule[88]=C:\Windows\system32\WindowsCodecs.dll
LoadedModule[89]=C:\Windows\system32\WINTRUST.dll
LoadedModule[90]=C:\Windows\system32\CLBCatQ.DLL
LoadedModule[91]=C:\Windows\system32\bcryptprimitives.dll
LoadedModule[92]=C:\Windows\system32\dbghelp.dll
LoadedModule[93]=C:\Windows\system32\dwrite.dll
LoadedModule[94]=C:\Windows\System32\netprofm.dll
LoadedModule[95]=C:\Windows\System32\nlaapi.dll
LoadedModule[96]=C:\Windows\system32\dhcpcsvc6.DLL
LoadedModule[97]=C:\Windows\system32\dhcpcsvc.DLL
LoadedModule[98]=C:\Windows\system32\CRYPTSP.dll
LoadedModule[99]=C:\Windows\system32\rsaenh.dll
LoadedModule[100]=C:\Windows\system32\RpcRtRemote.dll
LoadedModule[101]=C:\Windows\System32\npmproxy.dll
LoadedModule[102]=C:\Windows\System32\mswsock.dll
LoadedModule[103]=C:\Windows\system32\DNSAPI.dll
LoadedModule[104]=C:\Windows\system32\rasadhlp.dll
LoadedModule[105]=C:\Windows\System32\fwpuclnt.dll
LoadedModule[106]=C:\Windows\System32\wship6.dll
LoadedModule[107]=C:\Windows\System32\wshtcpip.dll
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=weight_and_balance
AppPath=C:\Program Files (x86)\Your Company\Weight & Balance\New folder\weight_and_balance.exe

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.10.1, on Microsoft Windows [Version 10.0.22621.1848], locale en-US)
    • Flutter version 3.10.1 on channel stable at D:\Programs\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (6 weeks ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
    • Android SDK at C:\Users\novin\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.0.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.6.3)
    • Visual Studio at D:\Programs\Microsoft Visual Studio Community 17.2.6
    • Visual Studio Community 2022 version 17.6.33801.468
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1848]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 114.0.5735.135
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 113.0.1774.50

[√] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by FusoraTech** [comment]
Your windows Install seems in a improper condition. Make sure it is Win7 SP1 and updated, this error is common when missing the update https://support.microsoft.com/kb/2670838

**Comment by armin1440** [comment]
This update is already installed

**Comment by darshankawar** [comment]
> I make a msi or exe setup file and I install it on a device which has windows 7 installed on. Then I open it and start using it.

What package did you use to make the msi ?

**Comment by armin1440** [comment]
I use "Advanced Installer" and "Msix packaging tool" which are not flutter packages. I also use "msix" package to get .msix file.
Then I use "Msix Packaging tool" to extract its contents and then use "Advanced Installer" to make a msi setup file. The app is installed on windows 10 & 11 properly.

**Comment by darshankawar** [comment]
Can you provide us the entire crash log ?

**Comment by armin1440** [comment]
@darshankawar how can I do this? Please note that I have provided a crash dump file in my first message above. Is there anything I can send?

**Comment by darshankawar** [comment]
@armin1440 
Is there a way for you to check if there are Window 7 supported msi packages that you can use ?

**Comment by armin1440** [comment]
What do you mean by "Windows 7 supported msi packages" ? Can you explain or provide an example. I do not understand.

**Comment by darshankawar** [comment]
Sorry I meant to ask if there's a Windows 7 specific msi package creator with which the crash occurs or not. Since you mentioned that with Windows 10 and 11 OS, the msi package works, so I was wondering if it has to do with the msi package you used, but I'll label this for team's attention and input.

**Comment by loic-sharma** [comment]
@armin1440 We don't have enough information to reproduce this issue yet. Could you try making a minimal app that reproduces this crash and sharing that?

**Comment by armin1440** [comment]
> Sorry I meant to ask if there's a Windows 7 specific msi package creator with which the crash occurs or not. Since you mentioned that with Windows 10 and 11 OS, the msi package works, so I was wondering if it has to do with the msi package you used, but I'll label this for team's attention and input.

I have tried a different way of making a setup file (which was an exe file) and it also did not work. I am not aware of other ways of creating msi packages.

**Comment by armin1440** [comment]
> @armin1440 We don't have enough information to reproduce this issue yet. Could you try making a minimal app that reproduces this crash and sharing that?
> 
> Also, could you try running your app using a debugger to get the crash's call stack? For example, here's how to do that using Visual Studio: https://learn.microsoft.com/visualstudio/debugger/how-to-debug-an-executable-not-part-of-a-visual-studio-solution

I can not provide a minimal app since the default flutter project after creating a new project works fine on windows 7 and all I know is that my project crashes. I will try using a debugger and tell you the results

**Comment by armin1440** [comment]
@loic-sharma Here is the call stack:
`rpcrt4.dll!000007fefe429004()`
and its screen shot:
![Screen Shot 2023-07-09 at 17 39 04 (2)](https://github.com/flutter/flutter/assets/60127896/00277133-84c5-4e9e-9497-2b27b55b44a0)
and here is output text:
```
The thread 0x1550 has exited with code 0 (0x0).
Exception thrown at 0x000007FEFDB8BE0D (KernelBase.dll) in weight_and_balance.exe: 0x00000006: The handle is invalid.
Exception thrown at 0x000007FEFDB8BE0D (KernelBase.dll) in weight_and_balance.exe: 0x00000006: The handle is invalid.
Exception thrown at 0x000007FEFDB8BE0D (KernelBase.dll) in weight_and_balance.exe: 0x00000006: The handle is invalid.
Exception thrown at 0x000007FEFE429004 (rpcrt4.dll) in weight_and_balance.exe: 0xC0000005: Access violation reading location 0x0000000000000010.
```

I see the exception multiple times but I provided the data above just after the first one. I also saw another exception that I have provided its screen shot and output text below:

![Screen Shot 2023-07-09 at 17 44 16 (2)](https://github.com/flutter/flutter/assets/60127896/7e2165ed-d67e-4f4a-9716-00cd08c8b011)

output: 
```
Exception thrown at 0x000007FEFDB8BE0D (KernelBase.dll) in weight_and_balance.exe: 0x00000006: The handle is invalid.
Exception thrown at 0x0000000077BDB69A (ntdll.dll) in weight_and_balance.exe: 0xC0000008: An invalid handle was specified.
```

Thank you in advance!

**Comment by loic-sharma** [comment]
@armin1440 Thanks! Could you load Flutter's symbols so that the call stack has more information?

<details>
<summary>Instructions on how to load Flutter's symbols...</summary>

Find your **Flutter SDK path** using the terminal: `flutter doctor --verbose`.

Let's say I have the following output:
   
```
PS C:\> flutter doctor --verbose
[✓] Flutter (Channel stable, 3.7.0, on Microsoft Windows [Version 10.0.22621.1105], locale en-US)
    • Flutter version 3.7.0 on channel stable at C:\Code\f\flutter
...
```

My **Flutter SDK path** is `C:\Code\f\flutter`.

Now, configure Visual Studio to add Flutter's symbols path:

1. Open the Debugging options using `DEBUG` > `Options...`.
2. Make sure that `Enable Just My Code` is unchecked:
   
   ![image](https://user-images.githubusercontent.com/737941/214984504-e71485c2-8c02-4f0b-9ef6-16dfb48975fa.png)

   This allows the Visual Studio debugger to step into external code, like the Flutter engine.

3. Navigate to the `Symbols` pane and use the `+` button to add `<Flutter SDK path>/bin/cache/artifacts/engine/windows-x64`
   as a symbol location:

   ![Pasted image 20230126161935](https://user-images.githubusercontent.com/737941/214984655-353ba5d8-6ca5-4678-bc97-4932c4b3e63e.png)

4. Close the `Options` window

Now, let's actually load the engine's symbols:

1. Open the `Modules` window using `DEBUG` > `Windows` > `Modules` (or `Ctrl+Alt+U`):

   ![Pasted image 20230126161915](https://user-images.githubusercontent.com/737941/214985815-ba128e85-b107-4fbf-ae58-7814b840bfaf.png)

2. In the `Modules` window, right click the `flutter_windows.dll` item and select `Load Symbols`:

   ![Pasted image 20230126162141](https://user-images.githubusercontent.com/737941/214986218-4f53e12c-ccb6-4c8c-8419-ca8772a5e561.png)

3. The engine's symbols should now be loaded:

   ![Pasted image 20230126162222](https://user-images.githubusercontent.com/737941/214986347-4bd31006-f960-4311-ad7e-9030b32067eb.png)

</details>

**Comment by armin1440** [comment]
As far as I know, windows 10 or newer is required to install flutter. How possibly can I install flutter on windows 7?

**Comment by armin1440** [comment]
@loic-sharma Thank you for your help. I tried to load symbols but I got an error when I selected the .pdb file from the location you said. Here is the error:

`a matching symbol file was not found in this folder`

I tried the directory windows-x64-release and it successfully loaded symbols. But the call stack didn't change. Here is the call stack after loading symbols:

![image](https://github.com/flutter/flutter/assets/60127896/80b3a651-ceb4-40ae-8744-c7c2563e2856)

**Comment by loic-sharma** [comment]
@armin1440 Thanks for following up. It seems we won't be able to debug this using the crash callstack then. Could you share a minimal app that reproduces this issue?

**Comment by armin1440** [comment]
@loic-sharma actually I have run the sample application of flutter without any problem. But my project won't. So I can not send a minimal app. Can I send a more complicated app with some packages included in pubspec.yaml ?

**Comment by loic-sharma** [comment]
@armin1440 Go ahead, but if building/running the app is too complicated I may ask you to simplify it :)

**Comment by armin1440** [comment]
@loic-sharma I tried to make a simple application to reproduce the issue but it did not crash! Do you have any clue what might cause my app to crash so I can focus on it to reproduce the issue?

**Comment by loic-sharma** [comment]
@armin1440 I would start from your app and remove code/features/packages to create a minimal app. Perhaps a process like:

1. Try to remove a feature or package
2. Check if the crash still reproduces:
    1. If the app crashes, loop back to step 1 and repeat the process of removing features/packages
    2. Else if the app no longer crashes:
        2. Re-add the feature or package.
        3. If this is a package, check whether a simple application that uses this package reproduces the issue
        4. If this is a feature, check if the feature can be split into sub-features. If yes, loop back to step 1 and repeat the process with the split sub-features

**Comment by iampopal** [comment]
Our all also crush on windows 7 using Flutter 3.10
