### ISSUE TITLE
[go_router] Maintain GoRouter listener

### ISSUE THREAD

**Issue by kNoAPP** [flutter/flutter#129800]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

As per the migration guide provided at https://docs.google.com/document/d/16plvWc9ablQsUs7w6bWDpTZ7PwMP4YUhV-qMQ3iljE0/edit the GoRouter team asked for an issue to be opened here if there was a use-case for listening to a GoRouter.

I use GoRouter listeners in conjunction with Riverpod & Google Analytics to track user navigation across pages.
```dart
final goRouterProvider = Provider<GoRouter>((ref) {
  final analyticsService = ref.watch(analyticsServiceProvider);
  final redirectionHandler = ref.watch(redirectionHandlerProvider);

  final router = Routes.generateRouter(redirectionHandler);

  void listener() {
    final uri = Uri.parse(router.location);
    analyticsService.setCurrentScreen(screenName: uri.path);
  }

  router.addListener(listener);
  ref.onDispose(() => router.removeListener(listener));

  return router;
});
```
The ability to do this has now been removed in v9.0.0 which is disappointing.

### Proposal

Consider keeping the ability to listen to GoRouter instances.

**Comment by bivens-dev** [comment]
What you have described here (leaving Riverpod aside here for a moment and just focusing on the analytics use case) is a very basic and well understood use case that almost any serious application would want to support.

I didn’t actually get from the migration guide how that would change moving forward with GoRouter. So I guess my question would be: how do I use an analytics service (such as GA) to accurately measure screen views using GoRouter moving forward with this proposed change?

**Comment by a1573595** [comment]
I need a GoRouter listener to complete my crashlytics and analyze reports, please do not remove this feature.

**Comment by stuartmorgan** [comment]
@chunhtai From triage: we're not sure how you want to move forward with this; please either assign a priority or close, depending on your plan.
