### ISSUE TITLE
Font rendering quality on Windows high-DPI is blurred / extremely poor

### ISSUE THREAD

**Issue by anaisbetts** [flutter/flutter#129889]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run the default Flutter app
2. Font quality is sometimes correct, but often very poor, and seems to distort / "snap" between renderings, see attached video:

This is not reproduceable on a different machine I use, I'm not sure what is causing this machine in particular to have blurred text. Other apps do not have an issue.

### Expected results

Font rendering is clear

### Actual results

Font rendering is blurred

### Code sample

Repros with Flutter default new project template

### Screenshots or Video

Video demonstration

https://github.com/flutter/flutter/assets/1396/e89a8f85-0b93-490a-be03-a53a7b5c6da4

### Logs

See DxDiag report here: https://gist.github.com/anaisbetts/eb0a45e112f5e54d7439f2d17ac653d2

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel [user-branch], 3.12.0-12.0.pre, on Microsoft Windows [Version 10.0.25393.1], locale en-DE)
    ! Flutter version 3.12.0-12.0.pre on channel [user-branch] at C:\Users\ani\code\flutter\flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at
      https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision 1b887c72b5 (4 days ago), 2023-06-28 17:16:19 -0700
    • Engine revision 241ca5c1d6
    • Dart version 3.1.0 (build 3.1.0-257.0.dev)
    • DevTools version 2.24.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Enterprise 2022 17.0.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Enterprise
    • Visual Studio Enterprise 2022 version 17.0.32126.317
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.79.0-insider)
    • VS Code at C:\Users\ani\AppData\Local\Programs\Microsoft VS Code Insiders
    • Flutter extension version 3.62.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.25393.1]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 114.0.5735.199
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 113.0.1774.57

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

</details>

**Comment by anaisbetts** [comment]
This seems to be affecting other apps on this computer, though not nearly as severely (Electron apps seem to be affected only intermittently, whereas Flutter apps are _always_ affected). I'll leave this open so others can find it, but it's likely that this is a computer issue

**Comment by ds84182** [comment]
Can you check your global texture filtering settings in Nvidia Control Panel? It looks like once a part of the scene hits raster cache the resulting texture isn't sampled correctly. fwiw I also have a 3080 and I don't see this problem.

**Comment by anaisbetts** [comment]
@ds84182 Resetting my nVidia Control Panel settings seems to have fixed this, thanks for the tip!
