### ISSUE TITLE
[Windows] ☂️ Support Arm64

### ISSUE THREAD

**Issue by loic-sharma** [flutter/flutter#129803]
* [x] https://github.com/flutter/flutter/issues/115983
* [ ] https://github.com/flutter/flutter/issues/129649
* [ ] https://github.com/flutter/flutter/issues/129804

**Comment by pbo-linaro** [comment]
Is it normal this issue was closed as completed?

**Comment by loic-sharma** [comment]
This is a duplicate of https://github.com/flutter/flutter/issues/62597, I didn't take the time to change the closed reason 😅
