### ISSUE TITLE
[packages][video_player] FATAL EXCEPTION: ExoPlayer:Loader:Loader:HlsSampleStreamWrapper

### ISSUE THREAD

**Issue by VladimirCores** [flutter/flutter#129899]
Hello Flutter team. 

I'm building an app for 24 / 7 video translation of different streams (HLS/progressive) from video hosting providers (YouTube and Vimeo). It runs on Android miniboard devices (RPi4, Odroid and others). I have tried different versions of Android (13/6) and different devices with different "rendering" modes (hardware/software decoding of FFmpeg). **On long run the application crash all the time** (after 4-12 hours depends on the device). I'm going to prepare a demo project if you need it, but could you take a look at the error:
```
E/AndroidRuntime( 2357): FATAL EXCEPTION: ExoPlayer:Loader:Loader:HlsSampleStreamWrapper
E/AndroidRuntime( 2357): Process: com.invisart.app.frame, PID: 2357
E/AndroidRuntime( 2357): java.lang.OutOfMemoryError: Failed to allocate a 6904 byte allocation with 185104 free bytes and 180KB until OOM, target footprint 201326592, growth limit 201326592; giving up on allocation because <1% of heap free after GC.
E/AndroidRuntime( 2357): 	at java.util.Arrays.copyOf(Arrays.java:3766)
E/AndroidRuntime( 2357): 	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:125)
E/AndroidRuntime( 2357): 	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:542)
E/AndroidRuntime( 2357): 	at java.lang.StringBuilder.append(StringBuilder.java:176)
E/AndroidRuntime( 2357): 	at java.lang.String.replace(String.java:2793)
E/AndroidRuntime( 2357): 	at com.google.android.exoplayer2.util.Log.appendThrowableString(Log.java:295)
E/AndroidRuntime( 2357): 	at com.google.android.exoplayer2.util.Log.e(Log.java:254)
E/AndroidRuntime( 2357): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:440)
```

Here is a code of how video controller switches the source:
```dart
Future<void> _initVideoController([bool restore = false]) async {
    try {
      final resourceLink = _currentVideoLink!.resourceLink!;
      print('> Main > Current Video = ${_currentVideoLink!.info} | ${resourceLink}');
      _controller = VideoPlayerController.networkUrl(Uri.parse(resourceLink),
          videoPlayerOptions: VideoPlayerOptions(
            mixWithOthers: false,
            allowBackgroundPlayback: false,
          ))
        ..setLooping(false);
      // print('> Main > _initVideoController: listener added');
      nameStream.add(_currentVideoLink!.info.title);
      // print('> Main > _initVideoController: title updated');
      await _controller!.initialize();
      // print('> Main > _initVideoController: initialized');
      if (restore) await _controller!.seekTo(Duration(seconds: _currentTimeValue));
      await _controller!.play();
      // print('> Main > _initVideoController: play');
      _onFocusChange();
      _controller!.addListener(_onVideoProgress);
      isPlayerReady.add(true);
      isPlayerBuffering.add(false);
    } catch (e) {
      print('> Main > _initVideoController: error = ${e}');
      // print('> Main > _initVideoController: error _currentVideoLink = ${_currentVideoLink}');
      statEvent(StatsEvent.UI_VIDEO_PLAYER_ERROR, e.toString());
      if (++_retriesOnError > Settings.SAME_VIDEO_RETRY) {
        print('> Main > max retries -> load next video');
        _nextVideoPlease();
      } else {
        _retryInitVideoController(seconds: 1);
      }
    }
  }
  ```
Here is a demo project: https://github.com/VladimirCores/Flutter_Video_Days
Run it on device with low memory for few hours (maybe 6 hours).

**Comment by huycozy** [comment]
Hi @VladimirCores 
I got this error when running your sample project. Looks like you need to refactor the project with supported Gradle settings in order to make it runnable.

>Exception: [!] Your app is using an unsupported Gradle project. To fix this problem, create a new project by running `flutter create -t app <app-directory>` and then move the dart code, assets and pubspec.yaml to the new project.
Exited

Also, this looks like an issue with ExoPlayer, you may take a look at its repository issue [here](https://github.com/google/ExoPlayer/issues) and check if there is any similar cases.

If you believe this is an issue with `video_player` plugin, I would suggest you provide a more minimal sample code if possible. It would be appreciated if you can provide a single `main.dart` file that can be run independently. 
And please also provide the detailed step by step to reproduce the issue, along with affected devices you are checking this on. Thank you!
