### ISSUE TITLE
[tool_crash] _CastError: (#0      BatchedExpressionEvaluator._evaluateBatch (package:dwds/src/services/batched_expression_evaluator.dart:125:39))

### ISSUE THREAD

**Issue by ChaserVasya** [flutter/flutter#129815]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=chrome --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
start debug flutter app on web

## Logs
_CastError: (#0      BatchedExpressionEvaluator._evaluateBatch (package:dwds/src/services/batched_expression_evaluator.dart:125:39))
```
#0      BatchedExpressionEvaluator._evaluateBatch (package:dwds/src/services/batched_expression_evaluator.dart:125:39)
<asynchronous suspension>
```
```
[!] Flutter (Channel unknown, 3.7.0, on Microsoft Windows [Version 10.0.19045.3086], locale ru-RU)
    ! Flutter version 3.7.0 on channel unknown at C:\Dev\Programs\flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    • Framework revision b06b8b2710 (5 months ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✗] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\vchas\AppData\Local\Android\sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: C:\Program Files\ojdkbuild\java-11-openjdk-11.0.15-1\bin\java
    • Java version OpenJDK Runtime Environment 18.9 (build 11.0.15+9-LTS)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.9)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.32106.194
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (version 2022.2)
    • Android Studio at C:\Dev\Programs\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 114.0.5735.199
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 114.0.1823.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: b8f7f1f9869bb2d116aa6a70dbeac61000b52849
### Plugins
audio_session-0.1.16
audioplayers-3.0.1
audioplayers_android-2.0.0
audioplayers_darwin-3.0.1
audioplayers_linux-1.0.4
audioplayers_web-2.2.0
audioplayers_windows-1.1.3
connectivity_plus-3.0.6
device_info_plus-8.2.2
file_picker-5.2.10
file_selector_linux-0.9.1+3
file_selector_macos-0.9.2
file_selector_windows-0.9.2
firebase_core-2.14.0
firebase_core_web-2.6.0
firebase_messaging-14.6.3
firebase_messaging_web-3.5.3
flutter_inappwebview-5.7.2+3
flutter_js-0.6.0
flutter_launch-0.3.0
flutter_local_notifications-13.0.0
flutter_native_timezone-2.0.0
flutter_plugin_android_lifecycle-2.0.15
flutter_ringtone_player-3.2.0
flutter_webview_plugin-0.4.0
fluttertoast-8.2.2
image_picker-0.8.9
image_picker_android-0.8.7+3
image_picker_for_web-2.2.0
image_picker_ios-0.8.8
image_picker_linux-0.2.1
image_picker_macos-0.2.1
image_picker_web-3.0.0+1
image_picker_windows-0.2.1
just_audio-0.9.34
just_audio_web-0.4.8
path_provider-2.0.15
path_provider_android-2.0.27
path_provider_foundation-2.2.3
path_provider_linux-2.1.11
path_provider_windows-2.1.7
phone_number-1.0.0
printing-5.10.4
share_plus-6.3.4
share_plus_web-3.1.0
shared_preferences-2.1.2
shared_preferences_android-2.1.4
shared_preferences_foundation-2.2.2
shared_preferences_linux-2.2.0
shared_preferences_web-2.1.0
shared_preferences_windows-2.2.0
sqflite-2.2.8+4
url_launcher-6.1.11
url_launcher_android-6.0.36
url_launcher_ios-6.1.4
url_launcher_linux-3.0.5
url_launcher_macos-3.0.5
url_launcher_web-2.0.17
url_launcher_windows-3.0.6
windows_printing-0.0.3

**Comment by danagbemava-nc** [comment]
Hi @ChaserVasya, you are using an older version of flutter. This was initially reported in https://github.com/flutter/flutter/issues/119084 and has since been fixed on the latest versions of flutter. 

Kindly upgrade to the latest version of flutter stable. 

Closing this since it has already been fixed. 

If you run into this issue on the latest version of flutter stable (3.10.5), kindly leave a comment below and I will reopen this. 

Thank you
