### ISSUE TITLE
[Web] Visible weird lines using text fields when entering Korean.

### ISSUE THREAD

**Issue by JAICHANGPARK** [flutter/flutter#129898]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

When I type Korean in the text field, a thick underline appears behind it.
It's the first time I've seen a thick underline follow.
Customers have inquired about something strange.

### Flutter Doctor 
[✓] Flutter (Channel beta, 3.12.0-1.1.pre, on macOS 13.4.1 22F82 darwin-arm64,
    locale en-KR)
    • Flutter version 3.12.0-1.1.pre on channel beta at
      /Users/jeffrey/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e2e0aa7037 (12 days ago), 2023-06-20 19:48:59 -0700
    • Engine revision 45712dd2f1
    • Dart version 3.1.0 (build 3.1.0-163.1.beta)
    • DevTools version 2.24.0

### web renderer 
- canvas kit

### Expected results

It is normal to see only a simple thin underline

### Actual results

https://github.com/flutter/flutter/assets/19484515/3a55cf8e-4593-4426-9883-53a3739fd1dd

### Code sample

<details><summary>Code sample</summary>

```dart
  Padding(
      padding: const EdgeInsets.all(8.0),
      child: TextField( ),
    ),
```

</details>

### Screenshots or Video

<img width="353" alt="Screenshot 2023-07-03 at 12 00 28 PM" src="https://github.com/flutter/flutter/assets/19484515/e2fcf722-a374-40dd-ab81-97c86059d369">

https://github.com/flutter/flutter/assets/19484515/b05a9058-a39d-4e98-8bff-e254603ff14a

https://github.com/flutter/flutter/assets/19484515/15578cf5-4acf-48ad-b170-f10b0cb5b44c

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel beta, 3.12.0-1.1.pre, on macOS 13.4.1 22F82 darwin-arm64,
    locale en-KR)
    • Flutter version 3.12.0-1.1.pre on channel beta at
      /Users/jeffrey/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e2e0aa7037 (12 days ago), 2023-06-20 19:48:59 -0700
    • Engine revision 45712dd2f1
    • Dart version 3.1.0 (build 3.1.0-163.1.beta)
    • DevTools version 2.24.0

```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @JAICHANGPARK 
I am unable to replicate the reported behavior on latest beta and master channels using Korean as input language.


https://github.com/flutter/flutter/assets/67046386/8ad9e567-498b-4de6-8a1a-d3c4e191caac

I selected below Korean variant to verify. Which one among the list are you using ?

<img width="504" alt="Screenshot 2023-07-03 at 3 21 53 PM" src="https://github.com/flutter/flutter/assets/67046386/f2c8b527-dabc-487d-9256-61259e5850b9">

**Comment by JAICHANGPARK** [comment]
@darshankawar Thanks for checking ! 
I am also generally using the **2-set korean** setting.

- Chrome Version :  114.0.5735.198 (Official Build) (arm64)
- macOS: 13.4.1 

<img width="658" alt="image" src="https://github.com/flutter/flutter/assets/19484515/b9fb100c-e1fa-4781-b3b8-e9f51a9cde12">

**Comment by JAICHANGPARK** [comment]
https://flutter.github.io/samples/web/form_app/#/form_widgets

https://github.com/flutter/flutter/assets/19484515/fda4e671-4307-45a0-9d27-ade8e9f2ade0

**Comment by darshankawar** [comment]
Thanks for the update. I am still unable to replicate it. Can you try couple of things as below ?

1. Check on non-Flutter web app to confirm if the behavior occurs on it as well or not.
2. Check on Flutter desktop platform as well (for ex: flutter run -d macos) to confirm if the behavior is limited to web only or also occurs on desktop as well.

**Comment by JAICHANGPARK** [comment]
@darshankawar Thanks :) 

I checked some cases.

### 1.1.  In the case of the YouTube search box 
It seems to be working well. 

https://github.com/flutter/flutter/assets/19484515/eceed473-9d2f-4f2d-85e7-12021380f7f8

### 1.2.  In the case of the Google search box 

It's working well. 

https://github.com/flutter/flutter/assets/19484515/75ec0e02-b35a-4196-b135-74253eac0672

### 2. I built it as a desktop app and tested it.
It's working well. 
In the desktop app, the underline is not visible.

https://github.com/flutter/flutter/assets/19484515/dfadbd66-3ba8-4cbf-b2e1-91f13f99c65c

**Comment by Patrick386** [comment]
This is a very old bug related to KEY inputs, it occurs even on desktop Windows and comes along with the 'hardware_keyboard' error. https://github.com/flutter/flutter/issues/126247

**Comment by darshankawar** [comment]
Thanks for the reference @Patrick386 , but the linked issue talks about `hardware_keyboard` error, but in this case, there's no such error, just the visible underline while inputing using Korean language.

Since I am unable to replicate the reported behavior, based on the report, I'll keep it open and label for team's attention.

**Comment by JAICHANGPARK** [comment]
On the Windows, there is no problem. It's fine 👍 

https://github.com/flutter/flutter/assets/19484515/23b83df8-2dad-4833-bbf4-1b2c46f06286

**Comment by htoor3** [comment]
I'm also unable to replicate this - I'm on MacOS and tried it on Chrome using 2-Set Korean.  I only see the thin underline that we usually see. 

@JAICHANGPARK are you only seeing this on Chrome? Does the issue occur on Firefox and Safari?

One possibility: it almost looks like it's not hiding the IME underline of the underlying input element - thus both the Flutter-rendered underline and the browser/system underline is being rendered.  

Do you have any system or browser settings to force the rendering of the composition underline?
