### ISSUE TITLE
[Impeller] Texture to Texture blit for advanced blends is misconfigured on Vulkan.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#129853]
E/flutter ( 6698): -----------------------------------------------------------------
E/flutter ( 6698): [ERROR:flutter/impeller/base/validation.cc(49)] Break on 'ImpellerValidationBreak' to inspect point of failure: 
E/flutter ( 6698): --- Vulkan Debug Report  ----------------------------------------
E/flutter ( 6698): |                Severity: Error
E/flutter ( 6698): |                    Type: { Validation }
E/flutter ( 6698): |                 ID Name: VUID-VkImageMemoryBarrier-oldLayout-01213
E/flutter ( 6698): |               ID Number: 1338377618
E/flutter ( 6698): |       Queue Breadcrumbs: [NONE]
E/flutter ( 6698): |  CMD Buffer Breadcrumbs: [NONE]
E/flutter ( 6698): |         Related Objects: Image [472435957199965806] [ImpellerOnscreenResolve]
E/flutter ( 6698): |                 Trigger: Validation Error: [ VUID-VkImageMemoryBarrier-oldLayout-01213 ] Object 0: handle = 0x68e6e0000068e6e, name = ImpellerOnscreenResolve, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x4fc60592 | vkCmdPipelineBarrier(): .pImageMemoryBarriers[0].newLayout Image barrier Layout=VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL is not compatible with VkImage 0x68e6e0000068e6e[ImpellerOnscreenResolve] usage flags 0x10. The Vulkan spec states: If srcQueueFamilyIndex and dstQueueFamilyIndex define a queue family ownership transfer or oldLayout and newLayout define an image layout transition, and oldLayout or newLayout is VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL then image must have been created with VK_IMAGE_USAGE_TRANSFER_DST_BIT (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkImageMemoryBarrier-oldLayout-01213)
E/flutter ( 6698): -----------------------------------------------------------------

**Comment by jonahwilliams** [comment]
I think I broke this, looking.

**Comment by jonahwilliams** [comment]
I did not break this, though I get slightly different errors. It looks if we're going to use the root resolve texture as a blit src, we need to tag it in the usage.

**Comment by chinmaygarde** [comment]
We are able to reproduce this in Wondrous if we turn on validation.
