### ISSUE TITLE
[go_router] Come up with a better way to get the current location without context

### ISSUE THREAD

**Issue by ghaith-abtah-5** [flutter/flutter#129833]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

After the last update go_router 9.0.0, you have removed the location parameter from GoRouter and cannot be accessed any more without a context.
```
final GoRouter router = GoRouter(
     routes: [
          GoRoute(
                path: Routes.splashRoute,
                builder: (BuildContext context, GoRouterState state) {
                initSplashModule();
                return const SplashScreen();
                 },
               routes: [...],
               ],
            ),
           // other routes
        ],
     );
```
I cannot anymore use router.location to determine where am I in the application and there are certain scenarios where I cannot provide a context to GoRouterState.of(context).location, deep link or firebase messages that will pop or push some other routes from or to the navigation stack depending on the current location and state.
It was the easiest way to get the location and I can implement a way to do this on my own but it will take so much time and effort to get to the go_router package level.

### Proposal

What was the reason to remove the location parameter and is there any chance that it will be back without a context in future versions?

**Comment by jamesli-se** [comment]
Hi @ghaith-abtah-5 , please see the release note:
Removes GoRouter.location and GoRouter.canPop. Use GoRouterState.of().location and Navigator.of().canPop instead.
so you can use GoRouterState.of().location to replace GoRouter.location.

**Comment by huycozy** [comment]
Hi @ghaith-abtah-5 
As mentioned in [Migration guide](https://flutter.dev/go/go-router-v9-breaking-changes), you can work around this by following code (it is not guaranteed to work in later versions, though)

```dart
GoRouter _router;
final String location = _router.routerDelegate.currentConfiguration.uri.toString();
final bool canPop = _router.routerDelegate.canPop;
```

Please let us know your opinion if it applies to your case or not.

**Comment by ghaith-abtah-5** [comment]
Thanks for reply.
I cannot relay on this method because of "it is not guaranteed to work in later versions", and there was no warning or deprecation annotation that you are going to remove the location property.
As I said, I can try to save the current route and implement this on my own but it will take time and effort.
What is the reason that it was removed without any warning?

**Comment by huycozy** [comment]
Hi @ghaith-abtah-5,
The Migration guide has been updated after 9.0.2, you can try below sample migration code:

```dart
final RouteMatch lastMatch = _router.routerDelegate.currentConfiguration.last;
final RouteMatchList matchList = lastMatch is ImperativeRouteMatch ? lastMatch.matches : _router.routerDelegate.currentConfiguration;
final String location = matchList.uri.toString();
```

>there was no warning or deprecation annotation that you are going to remove the location property.

Even though this is announced in the Changelog (this is a breaking change since 9.0.0), it should be warned in the API documentation. Thanks!

**Comment by chunhtai** [comment]
The reason we remove the location is to avoid people looking up GoRouter.of(context).location since it will not rebuild the widget if it changes.

but i agree the current workaround is ugly

**Comment by chrisdlangham** [comment]
Here is a crazy idea. How about we have a method named 'location' that implements this workaround, then we don't have any breaking changes. Once we have a proper alternative solution then remove this location method.

**Comment by NullByte08** [comment]
Inspired by @chrisdlangham 's idea I have created this:

```dart
extension GoRouterExtension on GoRouter {
  String location() {
    final RouteMatch lastMatch = routerDelegate.currentConfiguration.last;
    final RouteMatchList matchList = lastMatch is ImperativeRouteMatch ? lastMatch.matches : routerDelegate.currentConfiguration;
    final String location = matchList.uri.toString();
    return location;
  }
}
```
for anyone else to use it. Just simply use it like this:

```dart
GoRouter.of(context).location()
```

**Comment by billy1380** [comment]
> Inspired by @chrisdlangham 's idea I have created this:
> 
> ```dart
> extension GoRouterExtension on GoRouter {
>   String location() {
>     final RouteMatch lastMatch = routerDelegate.currentConfiguration.last;
>     final RouteMatchList matchList = lastMatch is ImperativeRouteMatch ? lastMatch.matches : routerDelegate.currentConfiguration;
>     final String location = matchList.uri.toString();
>     return location;
>   }
> }
> ```
> 
> for anyone else to use it. Just simply use it like this:
> 
> ```dart
> GoRouter.of(context).location()
> ```

make it a property and you are golden:
``` dart
extension GoRouterLocation on GoRouter {
  String get location {
    final RouteMatch lastMatch = routerDelegate.currentConfiguration.last;
    final RouteMatchList matchList = lastMatch is ImperativeRouteMatch
        ? lastMatch.matches
        : routerDelegate.currentConfiguration;
    return matchList.uri.toString();
  }
}```

**Comment by draskosaric** [comment]
Can I somehow  get the access to parameters sent to current route?

**Comment by chunhtai** [comment]
alright I will just add a getter to get routeMatchList in GoRouter. Though this is not critical as there is work around, but it is getting quite annoying when developing an app

**Comment by shibien** [comment]
is it me or when I use this new way to get current location, it shows instead the previous location and not the current one ?... Is anyone having the same issue ?

**Comment by Vedsaga** [comment]
> is it me or when I use this new way to get current location, it shows instead the previous location and not the current one ?... Is anyone having the same issue ?

Nope nope, actually it does current location.

**Comment by chris-wickens** [comment]
> is it me or when I use this new way to get current location, it shows instead the previous location and not the current one ?... Is anyone having the same issue ?

Yes, if I use `context.push` instead of `context.go` the `_router.routerDelegate.currentConfiguration.uri` shows the previous location. I've switched to using `context.go` and it works now. If you previously awaited the push method's completion to do further work consider using GoRoute's onExit callback instead.

Possibly related: https://github.com/flutter/flutter/issues/132930

**Comment by Tanmay-R-Choudhary** [comment]
> is it me or when I use this new way to get current location, it shows instead the previous location and not the current one ?... Is anyone having the same issue ?

For me, it is rebuilding all the routes that were previously injected in the stack (im using context.push to navigate). This might just be me though, as all the pages in my project have the same path: /:param1/:param2

I fetch additional data, via api call, based on the params and show content according to the response on the page.  If I use context.go, everything works fine.

The reason I need to use context.push is to support back button presses on mobile. I found a related issue, that was seemingly, resolved in previous versions. I dont know if its the same bug. I solved the issue by adding the following code (which I found in a comment on the previous issue I mentioned):

Minimum code:
`
extension GoRouterLocation on GoRouter {
  String get location {
    final RouteMatch lastMatch = routerDelegate.currentConfiguration.last;
    final RouteMatchList matchList = lastMatch is ImperativeRouteMatch
        ? lastMatch.matches
        : routerDelegate.currentConfiguration;
    return matchList.uri.toString();
  }
}

// in the route list ->
GoRoute(
      path: '/:num',
      builder: (context, state) {
        if (state.matchedLocation != GoRouter.of(context).location) {
          return const SizedBox.shrink();
        }

        context.read<AppBloc>().add(Reload(url: state.pathParameters['num']!)); // api call

        return const Renderer();
      },
    ),
`

Here is the link to the comment: https://github.com/flutter/flutter/issues/123570#issuecomment-1572621300

**Comment by iapicca** [comment]
> I was happy with Vrouter but it's dependencies not being updated in two years just broke my app.
> 
> Vrouters ability to get the current url was nicer tbh
> 
> ```
> selected: (context.vRouter.url == "my_url"),
> ```

I thought the point was NOT to use `context`

**Comment by kevlar700** [comment]
> > I was happy with Vrouter but it's dependencies not being updated in two years just broke my app.
> > Vrouters ability to get the current url was nicer tbh
> > ```
> > selected: (context.vRouter.url == "my_url"),
> > ```
> 
> I thought the point was NOT to use `context`

Good point though I prefer the context syntax too. For without context I used a key with Vrouter
```
navKeyGLO.currentState!.to(path);
```

**Comment by mErrenst** [comment]
Not a GoRouter feature but a workaround I discovered:

window.location isn't updated every time so that mostly shows the last element for me but window.history does get updated on every route.

```
import 'package:universal_html/html.dart' as html;

final location = html.window.history.state?['state']?['location'];
```

You will of course need to do a null check with that ;)
