### ISSUE TITLE
Inner ScrollView does not scroll the parent SingleChildScrollView

### ISSUE THREAD

**Issue by mehroze-zaidi** [flutter/flutter#129874]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Just run my code.

### Expected results

I want to scroll parent SingleChildScrollView after the inner scroll view (with a specific height) is fully scrolled. Please note I have specific requirements constraint the height of the inner ListView.

### Actual results

I'm not able to scroll when the inner Listview is completely scrolled but I can scroll if the inner Listview has padding from left or right and when I try to scroll from that padded area I can scroll parent ScrollView in my case It's SingleChildScrollView.

### Code sample

<details><summary>Code sample</summary>

```dart
SingleChildScrollView( child: Column(children: [


      SizedBox(
        height: 700,
        child:ListView.builder(
            itemCount:
          20, itemBuilder: (context, index) {
            return const ListTile(leading: Icon(Icons.icecream,
              color: Colors.amber,), title: Text("Ice Cream"),);
          },),
        ),
     
      
      SizedBox(
        height: 300,
        child: ListView.builder(
          itemCount: 20, itemBuilder: (context, index) {
          return const ListTile(
            leading: Icon(Icons.cake, color: Colors.red,),
            title: Text("Cake"),);
        },),
      ),


    ],),)
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.4, on macOS 13.4 22F66 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Community Edition (version 2022.2.3)
[✓] VS Code (version 1.79.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by mehroze-zaidi** [comment]
@ianloic Please have a look at this issue.

**Comment by HassanBalousha** [comment]
Add NeverScrollableScrollPhysics and shrinkWrap on all listviews 

Example : 
```
ListView(
          physics: NeverScrollableScrollPhysics(),
          shrinkWrap: true, 
          ...
```

**Comment by mehroze-zaidi** [comment]
> Add NeverScrollableScrollPhysics and shrinkWrap on all listviews
> 
> Example :
> 
> ```
> ListView(
>           physics: NeverScrollableScrollPhysics(),
>           shrinkWrap: true, 
>           ...
> ```

If I do this I won't be able to scroll my inner ListViews as they have a constraint height.

**Comment by HassanBalousha** [comment]
remove height 300,700 and put this code inside all listview

`  physics: NeverScrollableScrollPhysics(),
          shrinkWrap: true, `

**Comment by huycozy** [comment]
@mehroze-zaidi It seems @HassanBalousha's solution can solve your issue. Please try it to see if it's applicable to your case.

**Comment by mehroze-zaidi** [comment]
@huycozy @HassanBalousha Hi! I hope you both guys are doing well. Perhaps I wasn't able to explain my question enough so here is my issue: I have SingleChildScrollView as a parent and in that, I have two listviews each list view is wrapped with SizedBox with a specific height (like 700), what I want is, when I scroll up all the views that are in the first list, the first Listview should scroll up and then I'll be able to scroll next Listview, Please have a look into the code for more good understanding. Your help means a lot to me. Thank you in advance. 
**Note1: Setting fixed height is required behavior in my case, I can't use the technique you mentioned because my client wants this behavior that I mentioned.**  
**Note2: I'm getting this required behavior in Chrome but not on a mobile device** 
For better understanding, you guys can also visit Stackoverflow as I asked the same question there. 
Link: https://stackoverflow.com/questions/73166712/i-want-to-scroll-up-after-the-all-childs-of-listview-have-been-scrolled-up-pare

**Comment by mehroze-zaidi** [comment]
@anaisbetts

**Comment by anaisbetts** [comment]
I have nothing to do with this bug and have no idea why I am being mentioned

**Comment by huycozy** [comment]
@mehroze-zaidi Since you need this on Web, I re-check this on Chrome and see it works as you expected:

https://github.com/flutter/flutter/assets/104349824/100406a5-67c1-4c0b-94a9-22903d157682

If it's still not your expectation, can you please provide a demo visual (video/gif..) for that?

**Comment by anaisbetts** [comment]
@mehroze-zaidi No. Please do not CC me on bugs. I do not work on Flutter and I am not employed by Google.
