### ISSUE TITLE
help me out,i see this while running my projects

### ISSUE THREAD

**Issue by wivvv** [flutter/flutter#12988]
#	Gradle sync failed: Unexpected lock protocol found in lock file. Expected 3, found 0.
				Consult IDE log for more details (Help | Show Log)

**Comment by wivvv** [comment]
![image](https://user-images.githubusercontent.com/26006349/32700243-49446d30-c7d3-11e7-8732-e9e1a957f703.png)

**Comment by sethladd** [comment]
cc @mit-mit @devoncarew

**Comment by mit-mit** [comment]
@wivvv can you clarify when you see this? I.e., some repro steps would be nice. Also please include the output of `flutter doctor`

**Comment by Hixie** [comment]
Without specific information on how or when this happens, we're not able to act on it, so I'm going to close this issue. Please don't hesitate to file a new bug if you still see this.
