### ISSUE TITLE
[go_router_builder] [go_router]

### ISSUE THREAD

**Issue by lukaszciastko** [flutter/flutter#129884]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Create a route configuration (/) with child Routes (a, b) and a redirection to any of the child Routes from the main Route.

### Expected results

Route /a should load when navigating to /.

### Actual results

An error is thrown: One of `build` or `buildPage` must be implemented.
I have to override the build method of HomeRoute for this to work.

### Code sample

<details><summary>Code sample</summary>

```dart
@TypedGoRoute<HomeRoute>(
  path: '/',
  routes: [
    TypedGoRoute<ARoute>(
      path: 'a',
    ),
    TypedGoRoute<BRoute>(
      path: 'b',
    )
  ],
)
@immutable
class HomeRoute extends GoRouteData {
  @override
  FutureOr<String?> redirect(BuildContext context, GoRouterState state) {
    return '/a';
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.1 22C65 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Community Edition (version 2022.2.5)
[✓] VS Code (version 1.79.2)
[✓] Connected device (2 available)
[✓] Network resources
```

</details>

**Comment by huycozy** [comment]
Hi @lukaszciastko 
It seems this is WAI. Please check https://github.com/flutter/flutter/issues/103368#issuecomment-1589690425 to have ideas for your case. 

In case you have a different scenario, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)  so that we may verify this. Thank you!
