### ISSUE TITLE
[rfw] Many unit test failures in browser mode

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#129843]
In bringing up `--platform=chrome` Dart unit test CI in flutter/packages, `rfw` fails a bunch of tests. Mostly it looks like use of Int64, which isn't supported, but there's at least on number formatting issue due to the int vs double problem as well.

For now I'm opting the entire package out of web testing via a `dart_test.yaml` file that requires `vm`, but since the package appears to support web, presumably this should be fixed.

FYI @Hixie

**Comment by Hixie** [comment]
How do I run the tests that fail?

**Comment by stuartmorgan** [comment]
`flutter test --platform=chrome` is what the new CI is running.

**Comment by Hixie** [comment]
blocked on https://github.com/flutter/flutter/pull/131026 and https://github.com/flutter/engine/pull/43874.

**Comment by Hixie** [comment]
https://github.com/flutter/packages/compare/main...Hixie:packages:rfwweb is what I have so far.

**Comment by stuartmorgan** [comment]
If `rfw` isn't supposed to support web we could just add a platform list to its pubspec instead; I just thought it was supposed to and the test failures were test issues or minor bugs.

**Comment by Hixie** [comment]
We want rfw to support web. It's basically there with that branch, it's just blocked on a couple of fixes I had to make to the engine and the framework (see above). Once they've all rolled in I'll see if anything else needs doing.

**Comment by Hixie** [comment]
Now blocked on https://github.com/flutter/flutter/pull/131348
