### ISSUE TITLE
Performance overlay can overlook other work on the main isolate

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#129894]
consider the following app:

```dart
import 'dart:async';

import 'package:flutter/material.dart';

void main() {
  runApp(const BugReport());
}

class BugReport extends StatefulWidget {
  const BugReport({super.key});

  @override
  State<BugReport> createState() => _BugReportState();
}

class _BugReportState extends State<BugReport> {
  int count = 0;

  Future<void> _spinLoop() async {
    count++;
    List<int> primes = <int>[];
    for (int i = 1; i < 100000; i++) {
      bool isPrime = true;
      for (int j = 2; j < i; j++) {
        if (i % j == 0) {
          isPrime = false;
          break;
        }
      }
      if (isPrime) {
        primes.add(i);
      }
    }
    print('$count :: ${primes.sublist(0, 10)}');
    await Future<void>.delayed(const Duration(milliseconds: 2));
    scheduleMicrotask(_spinLoop);
  }

  @override
  void initState() {
    super.initState();
    scheduleMicrotask(_spinLoop);
  }

  @override
  Widget build(BuildContext context) {
    return Directionality(
      textDirection: TextDirection.ltr,
      child: Material(
        child: Stack(
          fit: StackFit.passthrough,
          children: [
            Positioned(
              top: 0,
              left: 0,
              right: 0,
              child: PerformanceOverlay.allEnabled(
                checkerboardOffscreenLayers: true,
                checkerboardRasterCacheImages: true,
                rasterizerThreshold: 1,
              ),
            ),
            Center(
              child: CircularProgressIndicator(),
            ),
          ],
        ),
      ),
    );
  }
}
```

The performance overlay for this app will show that no frames are being missed - each frame is _easily_ within the frame budget:

<img width="797" alt="Screenshot 2023-07-02 at 5 54 13 PM" src="https://github.com/flutter/flutter/assets/15253456/57fda0ee-1eea-4690-8e8c-3bdc9a99e188">

... yet the work being done in `_spinLoop` causes the app to very seriously jank - going at ~3fps on my M1 Macbook Pro.

**Comment by zanderso** [comment]
Curious whether this is surfaced more reasonably in DevTools.

**Comment by tvolkert** [comment]
DevTools seems to think it's humming along nicely as well.  https://drive.google.com/file/d/1dU4VCz5BtAgFkoh_5qPol-yryBMuA7rm/view

**Comment by zanderso** [comment]
Rather than modifying/complicating what the performance overlay or DevTools are reporting about work that is on the critical path of a frame. I'd suggest we investigate new ways of reporting that non-frame-related event handlers or microtasks are taking up too much time on the UI Isolate. That could be as simple as DevTools alerting when non-frame-related work goes over N milliseconds per vsync on the UI Isolate, and that data should already be in the timeline, I think.

FYI @kenzieschmoll

**Comment by tvolkert** [comment]
That sounds reasonable to me.  And then perhaps our tooling could direct them to using isolates.

**Comment by Hixie** [comment]
The Performance Overlay is intentionally not reporting such issues, because it has no way to know that the delays aren't intentional: the spinning code is preventing the framework from even scheduling the frame. You should be able to see it in the timeline though, using devtools.

**Comment by tvolkert** [comment]
@Hixie see [the comment above](https://github.com/flutter/flutter/issues/129894#issuecomment-1942058868) -- DevTools also doesn't show it.

**Comment by Hixie** [comment]
I see "SceneDisplayLag" in the trace which seems to indicate there was lag, but I agree that the Dart code itself doesn't seem to be getting flagged. Maybe we could emit a Timeline event for any time a microtask or Timer goes off? or maybe any time we enter Dart at all? I'll file a bug on Dart for that: https://github.com/dart-lang/sdk/issues/55630
