### ISSUE TITLE
@asset metadata annotation as an alternative to pubspec.yml:assets

### ISSUE THREAD

**Issue by dragonfax** [flutter/flutter#12986]
I would love it if I could just mark the filenames for assets in my source code with a an @asset annotation, rather than having to add them individually to the pubspec.yml. Managing that list in pubspec and keeping it updated can be chore and makes it easy to miss new assets that are needed, or leave in assets that are no longer used.

I'm assuming during compilation the flutter tools could gather these annotated strings, unique them, and add them to the pubspec provided asset list, internally, when building the app.

```dart
new ListTile(
 leading: new Image.asset(@asset "assets/icons/item_icon.png"),
 title: new Text("Some item")
)
```

**Comment by sethladd** [comment]
cc @mit-mit

**Comment by mit-mit** [comment]
Thanks for the suggestion, we will do some planning in this area closer to the end of the quarter, and will take this under consideration

**Comment by jonahwilliams** [comment]
We should avoid any sort of asset or font system that requires the tooling to parse all of a project's dart code to determine files to include. I'm marking this as as a declined request and closing.
