### ISSUE TITLE
MissingPluginException(No implementation found for method HttpMetric#stop on channel plugins.flutter.io/firebase_performance)

### ISSUE THREAD

**Issue by rishabhsharma3617** [flutter/flutter#129825]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Integrate firebase_performance 0.8.3+3 to your flutter project !!
- use Firebase network monitor tool 
 And it will start to throw this exception randomly 

### Expected results

It shouldnt break !!

### Actual results

I am getting this [error](https://github.com/firebase/flutterfire/issues/8057) 

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
firebase_performance is a third-party package. Any issues you face using it should be reported on their repo so that it can be looked it. 

Closing from here as this is not a flutter issue.

Thank you
