### ISSUE TITLE
Update http dependancy to the latest version

### ISSUE THREAD

**Issue by Chiyembekezo** [flutter/flutter#129936]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Your dependency is still relying on http: ^0.13.3. rive ^0.11.4 is still lagging behind

[bus_application_flutter] flutter pub get
Resolving dependencies...
Because rive >=0.7.17 depends on http ^0.13.3 and bus_application_flutter depends on http ^1.010, rive >=0.7.17 is forbidden.
So, because bus_application_flutter depends on rive ^0.11.4, version solving failed.
exit code 1

### Proposal

Update your http dependency for rive_common: 0.1.0 and rive: ^0.11.4 to the latest version http ^1.1.0

**Comment by danagbemava-nc** [comment]
This is not a flutter issue. This is from the rive package. This has been reported on their repo. See https://github.com/rive-app/rive-flutter/issues/321#issuecomment-1570032172

Closing from here as this is not a flutter issue. 

Thank you
