### ISSUE TITLE
after trying to input text in textfromfield emulator keyboard dosen't shows up also not taking any text. using flutter version - 3.10

### ISSUE THREAD

**Issue by getRabbi** [flutter/flutter#129937]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

[showSoftInput() view=io.flutter.embedding.android.FlutterView{d9d3093 VFE...... .F....ID 0,0-1440,2956 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INP](https://stackoverflow.com/questions/76459967/showsoftinput-view-io-flutter-embedding-android-flutterviewd9d3093-vfe)

### Actual results

after trying to input text in textfromfield emulator keyboard dosen't shows up also not taking any text. tried updataing permission but didn't work

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

```

</details>
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.0, on Microsoft Windows [Version 10.0.22621.1413], locale en-US)     
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.2)
[√] Android Studio (version 2022.1)
[√] VS Code (version 1.79.2)
[√] Connected device (4 available)
[√] Network resources

• No issues found!

**Comment by darshankawar** [comment]
@getRabbi 
In order to properly address the issue, please provide us [complete runnable minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without any custom code / third party package implementation, that shows the reported behavior.
