### ISSUE TITLE
[shared_preferences] Variable binding in a condition requires an initializer

### ISSUE THREAD

**Issue by amit-agendaboa** [flutter/flutter#129983]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Add shared_preferences: 2.2.0 in dependencies.

### Expected results

should working fine.

### Actual results

**I am getting this error after updating to shared_preferences: 2.2.0.**

Swift Compiler Error (Xcode): Variable binding in a condition requires an initializer
/Users/appleapple/.pub-cache/hosted/pub.dev/shared_preferences_foundation-2.3.0/darwin/Classes/SharedPreferencesPlugin.swift:57:21

Uncategorized (Xcode): Command CompileSwiftSources failed with a nonzero exit code

Could not build the application for the simulator.
Error launching application on iPhone SE (3rd generation).

### Code sample

<details><summary>Code</summary>

shared_preferences: 2.2.0

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

<img width="1139" alt="Screen Shot 2023-07-05 at 12 23 58 PM" src="https://github.com/flutter/flutter/assets/120711183/a69b2199-a09c-4031-b273-462fe2baa55c">
<img width="1049" alt="Screen Shot 2023-07-05 at 12 21 14 PM" src="https://github.com/flutter/flutter/assets/120711183/068420c2-a024-4dc8-beb5-a6aeefc1de1a">

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.5, on macOS 12.6.7 21G651 darwin-x64, locale en-US)
    • Flutter version 3.10.5 on channel stable at /Users/appleapple/Documents/flutterSdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (3 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/appleapple/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E500a
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (5 available)
    • Redmi Y2 (mobile)                   • 73e697d                              • android-arm    • Android 9 (API 28)
    • iPhone (mobile)                     • 00008020-001C4D3E0E52002E            • ios            • iOS 13.4.1 17E262
    • iPhone SE (3rd generation) (mobile) • DB6CD68A-5CED-4D74-A2E7-FFA249CC9A18 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)                     • macos                                • darwin-x64     • macOS 12.6.7 21G651
      darwin-x64
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by yoer** [comment]
I have also encountered this issue after the automatic upgrade to the new version. Please fix it as soon as possible.

**Comment by danagbemava-nc** [comment]
Hi @amit-agendaboa, your flutter doctor shows that you are using an older version of Xcode. Kindly upgrade to the latest version of xcode to see if you still face this issue. @yoer, If you are also using an older version of xcode, kindly make sure you upgrade to the latest version of xcode. 

I tested a sample app with the latest version of shared_preferences on iOS and it worked just fine for me.

I'm using xcode 14.3.1.

**Comment by stuartmorgan** [comment]
@tarrinneal It looks like `if let foo` is only supported in more recent language versions; we should change it to use the more compatible `if let foo = foo`.

**Comment by SARVADHIABHISHEK** [comment]
i fixed this issue after opening project in xcode and generate error than after find where is issue and changed some thing

here is  error : 
if let allowList  {
allowSet = Set(allowSet)
}

solved issue like this:
if let allowList **=  allowSet** {
allowSet = Set(allowSet)
}

kindly update code with solved issue i mentioned requir thing in blod

**Comment by SARVADHIABHISHEK** [comment]
> 
i fixed this issue after opening project in xcode and generate error than after find where is issue and changed some thing

here is error :
if let allowList {
allowSet = Set(allowSet)
}

solved issue like this:
if let allowList = allowSet {
allowSet = Set(allowSet)
}

kindly update code with solved issue i mentioned requir thing in bold

**Comment by miladrashidizade** [comment]
Hello there, I have some problem, but I'm using the easy_localization: ^3.0.0 package.
Please fix it sooner.

**Comment by amit-agendaboa** [comment]
@danagbemava-nc my Mac does't support to upgrade new OS, it is 2015 early. hence I can't update Xcode to 14.3.1.

**Comment by Yoon-Do** [comment]
Hi @amit-agendaboa, i had the same problem as you and solved it, reply me if you have the same!
- add "shared_preferences_foundation: 2.2.2" in Pubspec.yaml

Good luck to you.

**Comment by amit-agendaboa** [comment]
yes I have already solved it by adding "shared_preferences_foundation: 2.2.2" in dependency_overrides in Pubspec.yaml.

Thanks @Yoon-Do

**Comment by miladrashidizade** [comment]
Thank you @Yoon-Do 
I overridden the shared_preferences_foundation package in Pubspec.yaml.

dependency_overrides:
  shared_preferences_foundation: "<=2.2.2"

**Comment by alidaoud** [comment]
> 

This worked for me, Thanks man you saved my day 😀🙌

**Comment by alidaoud** [comment]
> Hi @amit-agendaboa, i had the same problem as you and solved it, reply me if you have the same!
> 
> * add "shared_preferences_foundation: 2.2.2" in Pubspec.yaml
> 
> Good luck to you.

This worked for me, Thanks man you saved my day 😀🙌
