### ISSUE TITLE
Key Up Event Not Captured If System Shortcut Activated MacOS

### ISSUE THREAD

**Issue by MousyBusiness** [flutter/flutter#129971]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run the sample code and observe left CMD key printing up and down events
2. Take a Mac screenshot using CMD+SHIFT+CTRL+4 
3. Observe that we received the meta down, but the meta up was never registered, nor does the window lose focus 

### Expected results

Receive key up events reliably

### Actual results

Key up events can be missed

### Code sample
```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Bug Report',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Bug'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  void initState() {
    super.initState();
    RawKeyboard.instance.addListener(_handleKeyEvent);
  }

  void _handleKeyEvent(RawKeyEvent event) {
    if (event is RawKeyDownEvent) {
      if (event.logicalKey == LogicalKeyboardKey.metaLeft ||
          event.logicalKey == LogicalKeyboardKey.metaLeft) {
        print("Meta down");
      }
    }

    if (event is RawKeyUpEvent) {
      if (event.logicalKey == LogicalKeyboardKey.metaLeft ||
          event.logicalKey == LogicalKeyboardKey.metaLeft) {
        print("Meta up");
      }
    }
  }

  @override
  void dispose() {
    RawKeyboard.instance.removeListener(_handleKeyEvent);
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(

          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'Keyboard Bug',
            ),
          ],
        ),
      ),
    );
  }
}
```

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.2.1 22D68 darwin-arm64)
```

**Comment by darshankawar** [comment]
Thanks for the report @MousyBusiness 
Although I am able to replicate the reported behavior as below:

1. Upon tapping `cmd` button, it shows both meta events:

```
flutter: Meta down
flutter: Meta up
flutter: Meta down
flutter: Meta up
flutter: Meta down
flutter: Meta up
```

2. Upon taking screenshot, only `Meta down` is reported:

```

Performing hot restart...                                               
Restarted application in 722ms.
flutter: Meta down
```

I came across this old issue mentioning same issue as you reported: https://github.com/flutter/flutter/issues/38076 which was potentially fixed with likely root-cause as mentioned https://github.com/flutter/flutter/issues/38076#issuecomment-543840156

I also saw [this](https://github.com/flutter/flutter/issues/45574) related issue that you can take a look and confirm if it resembles your case or not, because it does mention about `flagsChanged` method as discussed in above linked issue as well, so maybe that is still causing the issue as reported here.
