### ISSUE TITLE
Running integration tests on Flutter canvaskit website

### ISSUE THREAD

**Issue by corjanbos** [flutter/flutter#129910]
Hi all,

We are developing a Flutter POS application and build it as a website (web-renderer=canvaskit). We have written loads of integration tests which all run fine within the Flutter framework but we would also like to run integration tests on our staging k8s cluster which does not have Flutter installed (and we also don't want that). Until now we have screened a lot of testing tools but none were able to run satisfying integration tests on our Flutter web application. 

Does anyone have a idea about what testing framework/tool/kit is able to run integration tests (non x-y coordinates) on a Flutter built canvaskit website?

Thank you in advance.

**Comment by huycozy** [comment]
Hi @corjanbos 
It seems your question is best suited for support channels in flutter's [community](https://flutter.dev/community) so please ask the same there for solutions if any.

With regard to the testing tools, have you tried Selenium? If you need to inspect elements, using `RendererBinding.instance.ensureSemantics()` could be an option if it's applicable, I think.

**Comment by corjanbos** [comment]
Hi @huycozy ,

Thank you. Selenium does not work, also taken your suggestion into account. But I will repost my question.
