### ISSUE TITLE
BASE64 Padding problem

### ISSUE THREAD

**Issue by FonsecaDevs** [flutter/flutter#129907]
### Is there an existing issue for this?

- [ ] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [ ] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Hiii, in some cases base64 token don't has full length and trow a exception, and need padding outside function.
Then my sugestion is add this padding inside function "base64.decode(token)"

Thank you!

### Proposal

int paddingLength = 4 - token.length % 4;
if (paddingLength < 4) {
     token += '=' * paddingLength;
}

**Comment by danagbemava-nc** [comment]
Hi @FonsecaDevs, this is dart-sdk issue and should be reported on their repo https://github.com/dart-lang/sdk/issues?q=is:issue+is:open+sort:updated-desc

Please check for duplicates before you file the issue. 

Closing from here as this is not a flutter issue. 

Thank you
