### ISSUE TITLE
Memory regression: flutter_gallery__back_button_memory

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#12996]
https://github.com/flutter/flutter/pull/12974 caused a regression on the flutter_gallery__back_button_memory benchmark:

* 52x for diff_total_kb
* 3x for end_total_kb

**Comment by jason-simmons** [comment]
This originated with https://github.com/flutter/engine/commit/f5bdf9b0fc647216fb571de45ee72be6fa83774f

FlutterView.destroy() is not deleting the underlying FlutterNativeView.  When the activity is recreated, it constructs a new FlutterView, but the old instance (and its Dart isolate) are still alive and continue to hold on to objects such as cached Skia images.

@zanderso
