### ISSUE TITLE
[ref to #128221] Screen flickering on iOS with & without Impeller enabled 

### ISSUE THREAD

**Issue by delfme** [flutter/flutter#129947]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

This is new issue opened after https://github.com/flutter/flutter/issues/128221 has been just closed due to inactivity.
But I was on it debugging and looks like I got to nail down the issue. 
CC: @dam-ease , @zanderso , @zmtzawqlp 

I added a log to `didHaveMemoryPressure` to see if images flickering was somehow linked to underneath cache activity and I think I nailed down the issue.
It seems that flickering occurs rigth when `didHaveMemoryPressure` is being invoked and log
"Warning!! Low Memory, didHaveMemoryPressure" is printed on console. When log is not printed, I see no flickering and viceversa when flickering occurs, the log is also printed.

My best guess with this is that flutter engine frees up image cache while at same time it is loading images (see code paragraph). Issue occurs with both `ExtendedNetworkImage` and `CachedNetworkImage`. It is like by cleaning data while images are getting rendered, engines finds itself rendering the very data it just cleaned and flickering occurs.

### Expected results

Screen not flickering.

### Actual results

Please see video attached in below section.

Notes:
- Issue occurs even if no Platform view is on the scene.
- Issue occurs consistently, but no error is thrown by console. Here is timeline: 
https://drive.google.com/file/d/1WJKpqR0RABBM64xHRMfOp7FuX10q07v5/view?usp=sharing

### Code sample

After latest research, it seems that this code causes flickering if it is called when `didHaveMemoryPressure` is invoked meantime.

```
precacheImage(
      ExtendedNetworkImageProvider(
           image_url,
           cache: true,
           cacheMaxAge: const Duration(days: 2),
      ),
      context,
 );
```

Note: Issue occurs with both `ExtendedNetworkImage` and `CachedNetworkImage`.

### Screenshots or Video

Here is a video reproducing issue:

https://github.com/flutter/flutter/assets/53510751/fb4b297c-e722-4706-9697-dd50516652dd

### Logs

Console throws no errors when issue occurs. As mentioned above, I just noticed that `didHaveMemoryPressure` log is printed when issue occurs.

### Flutter Doctor output

[✓] Flutter (Channel master, 3.11.0-18.0.pre.76, on macOS 12.6.5 21G531 darwin-arm64, locale en-IT)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] Connected device (3 available)
[✓] Network resources

**Comment by darshankawar** [comment]
@delfme Let's track this in the original issue as it already has all the details and people involved. I'll reopen the issue so that you can share these details in it for better tracking.
Closing this.
