### ISSUE TITLE
When I try to open a PDF in the default Browser using launchUrl nothing happens

### ISSUE THREAD

**Issue by TimAlber** [flutter/flutter#129981]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

On Android:
1. Find a URL that points to a PDF file
2. Try to open that Link using launchUrl
3. Notice that nothing happens

On iOS this Bug does not exist.
When opening an normal Web Page this bug does not exist either. Only for PDFs.
I use this version of url_launcher: ^6.1.11

### Expected results

The default Browser should open and display the PDF file

### Actual results

Nothing happens, no Error displayed either

### Code sample

<details><summary>Code sample</summary>

```dart
if (!await launchUrl(
  Uri.parse(url),
  mode: LaunchMode.externalApplication,
)) {
  const snackBar = SnackBar(
    content: Text(
      'Error opening URL',
    ),
  );
  ScaffoldMessenger.of(context).showSnackBar(snackBar);
}
```

</details>

### Logs

There was no Error thrown in the Logs.

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.4 22F66 darwin-arm64, locale de-DE)
    • Flutter version 3.10.0 on channel stable at /Users/tial/Documents/flutter-install/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (8 weeks ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/tial/Library/Android/Sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/tial/Library/Android/Sdk
    • ANDROID_SDK_ROOT = /Users/tial/Library/Android/Sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.3)
    • VS Code at /Users/tial/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by SurajS0925** [comment]
@TimAlber 
I believe that in this case, would be better you be using [webview_flutter: ^3.0.2](https://pub.dev/packages/webview_flutter) instead of launcher, hope that helps you!

**Comment by danagbemava-nc** [comment]
Hi @TimAlber, thanks for filing the issue. 

Please provide an example of said URL and the version of `url_launcher_android` that is being used in your project. You can find this in your pubspec.lock

Thank you

**Comment by TimAlber** [comment]
The Version of `url_launcher_android` : `6.0.31`
The PDF is hosted on a Webserver that is only available inside a VPN that the Android Simulator is in.

**Comment by danagbemava-nc** [comment]
Hi @TimAlber, I tested with this url https://www.gpo.gov/fdsys/pkg/CDOC-110hdoc50/pdf/CDOC-110hdoc50.pdf and the browser is launched on my device, although chrome tries to download the file automatically. 

If you try opening any other PDF, does it work as expected or does it also fail?

https://github.com/flutter/flutter/assets/88313112/59c78f46-f37f-4730-8fca-01ee0aecdbc7

**Comment by aliaksei-liavonik** [comment]
+1 with the same behavior.
On Android devices(physical and emulator) just a white screen is opening without any content(nothing is downloading also), but on iOS inAppWebView looks perfectly fine.

Code to reproduce:
```
final url = Uri.parse(
    'https://www.africau.edu/images/default/sample.pdf'); // Or any other pdf from the internet
if (await canLaunchUrl(url)) {
  await launchUrl(url, mode: LaunchMode.inAppWebView);
}
```

Flutter version: 3.10.0
url_launcher: "6.1.11"
url_launcher_android: ""6.0.35"

**Comment by danagbemava-nc** [comment]
Hi @aliaksei-liavonik, that is already being tracked in https://github.com/flutter/flutter/issues/105205

**Comment by TimAlber** [comment]
When I use a PDF that is available on the Internet i have the same behavior as you in the video.
When I use a PDF that is only available inside my VPN the bug happens as described.

**Comment by danagbemava-nc** [comment]
Hi @TimAlber, can you try the following native android example app to see if you still face the issue? 

https://www.geeksforgeeks.org/how-to-open-an-external-url-on-button-click-in-android-using-jetpack-compose/
