### ISSUE TITLE
`flutter upgrade` recommends upgrading when running upgrade

### ISSUE THREAD

**Issue by SeraphimSerapis** [flutter/flutter#12991]
## Steps to Reproduce

When using the CLI to upgrade the local Flutter installation (using `flutter upgrade`), the CLI provides a warning that the installations is XY days old and that `flutter upgrade` should be run in order to update the installation.

<img width="568" alt="screen shot 2017-11-13 at 2 51 38 pm" src="https://user-images.githubusercontent.com/160543/32729147-13316058-c883-11e7-9d1d-f8404a7ff59f.png">

## Expected behavior

When running `flutter upgrade` this warning should be suppressed.

**Comment by ratsey** [comment]
Still an issue.

```
E:\Users\jens\Projects\Car Fanatic>flutter upgrade
Upgrading Flutter from E:\flutter...
From https://github.com/flutter/flutter
   63b24639f..8717a5e6f  master     -> origin/master
Already up-to-date.

Upgrading engine...
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ WARNING: your installation of Flutter is 29 days old.                      ║
  ║                                                                            ║
  ║ To update to the latest version, run "flutter upgrade".                    ║
  ╚════════════════════════════════════════════════════════════════════════════╝

Already up-to-date.

```

**Comment by zoechi** [comment]
run `git clean -xffd` `git pull` `flutter doctor` in your Flutter install directory.
