### ISSUE TITLE
Path.addArc with paintstyle.stroke offsets issue. 

### ISSUE THREAD

**Issue by shelidizel** [flutter/flutter#129909]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I am using path.addarc plus paintstyle.stroke with a stroke width of greater than 50 to create an arc. When i try to find offsets within my arc using path.contains(offset), It seems like the offsets found are a small part within the center of my arc are found but towards the side of the arc, they aren't found.

### Expected results

All the visible parts within the path will return true using path.contains(offset)

### Actual results

A small part within the path return true using path.contains(offset).

### Code sample

<details><summary>Code sample</summary>

```dart
import 'dart:math';

import 'package:flutter/material.dart';

void main() {
  runApp(const MyHomePage());
}



class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, });

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  List<Offset> hoverPositions = [];

  @override
  void initState() {
    // TODO: implement initState
    hoverPositions.clear();
    print('hover positions cleared');
    super.initState();
  }

  
 

  @override
  Widget build(BuildContext context) {
    
    return Listener(
      onPointerHover: (event) {
        setState(() {
          hoverPositions.add(event.localPosition);
        });  
      },
      child: CustomPaint(
        painter: DemoPainter(
          hoverPositions: hoverPositions,
          
        ),
        size: Size(MediaQuery.of(context).size.height/2, MediaQuery.of(context).size.width/2),
        
      ),
    );
  }
}

class DemoPainter extends CustomPainter {
  
  List<Offset> hoverPositions = [];
  DemoPainter({required this.hoverPositions});

  bool isArcHovered = false;

  @override
void paint(Canvas canvas, Size size) {
  Offset center = Offset(size.width / 2, size.height / 2);
  var rect = Rect.fromCircle(center: center, radius: size.width / 4);

  Path path = Path();

  final radius = size.width / 4;
  final startAngle = 0.0;
  var endAngle = pi/4;

  path.addArc(rect, startAngle, endAngle);

  if(hoverPositions.isNotEmpty){
    for (var hoverPosition in hoverPositions) {
      if(path.contains(hoverPosition)){
        print('Hover position within');
        isArcHovered = true;
        hoverPositions.clear();
        
      } else if (path.contains(hoverPosition) == false) {
        print('hover position without');
        isArcHovered = false;
      }
    }
    
    
  } 



  Paint paint = Paint()
    ..color = isArcHovered? Colors.red.withOpacity(.7) : Colors.red
    ..strokeWidth = 50
    ..style = PaintingStyle.stroke;

  canvas.drawPath(path, paint);
}

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) {
    return true;
  }
}


```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
C:\Users\Sheldon\custom_painter> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.0, on Microsoft Windows [Version 10.0.19045.3086], locale en-KE)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.1)
[√] VS Code (version 1.79.2)
[√] Connected device (3 available)
[√] Network resources
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @shelidizel, what platform(s) are you experiencing this issue on? Can you share a screen recording/screenshot of the issue? 

Can you also check on the latest version of flutter stable (3.10.5) to see if you still have this issue? 

Thank you

**Comment by shelidizel** [comment]
> Hi @shelidizel, what platform(s) are you experiencing this issue on? Can you share a screen recording/screenshot of the issue?
> 
> Can you also check on the latest version of flutter stable (3.10.5) to see if you still have this issue?
> 
> Thank you

Yea, I still have the same issue with flutter stable (3.10.5)

**Comment by danagbemava-nc** [comment]
Hi @shelidizel, can you share some logs or recording that captures the issue? I'm not entirely sure about the steps to reproduce.  

Thank you
