### ISSUE TITLE
Make assets available during tests.

### ISSUE THREAD

**Issue by dragonfax** [flutter/flutter#12999]
Its kind of a no-brainer that you might want to validate your assets in some way. Especially when you have multiple people working on the same project (not all of them developers). Furthermore its common to want to test the code that processes those assets, without having to hardcode versions of the assets in the tests, that might not match up with the live assets as they change through time. Finally of course, there is testing widgets that use the asset bundle, and need valid assets from it to behave properly.

https://github.com/flutter/flutter/issues/8490 seems to confirm that reading assets during test is not possible.

**Comment by victoraldir** [comment]
I ran into the same problem/limitation trying to test some .json config based behaviour in my app. I can't load assets for unit tests. Any idea if it's under the radar for the next beta release?

**Comment by eseidelGoogle** [comment]
@gspencergoog ran into this recently and may have thoughts.

**Comment by gspencergoog** [comment]
My issue was more around opening files for unit tests (having to do with the differing paths under the continuous integration environments), but being able to load assets in tests would have solved my problem too. This seems like something a lot of reasonable developers would want to do.

**Comment by kentcb** [comment]
Yeah, I want to store some data for some test scenarios as assets and load them from my tests. I'd almost argue that you might want the assets to differ for a test build versus an app build...

**Comment by carlos-martin** [comment]
I have the same issue as @victoraldir  has.
I'm creating my unit test for a multi language app. All the translation that I have are stored in JSON files and I cannot find the way to load those files from the test cases.

**Comment by SKLn-Rad** [comment]
Any news on this?
Having an issue right now where I cannot unit test an app I plan to white label as I cannot read from the rootBundle.

**Comment by filiph** [comment]
-- Tangent --

If you're using @matanlurey's `DiskAssetBundle` or similar approach, and you're seeing `Directory listing failed, path = 'assets/something/' (OS Error: No such file or directory, errno = 2)`, make sure you run your tests with `flutter test test` instead of just `flutter test`.

This tripped me up just now — my tests ran okay on my own device but failed on Travis, and I had no idea why.

Details: When you run `flutter test`, it changes the current working directory to `test` and then runs. On the other hand, if you run `flutter test test`, it stays in your app's root directory. Therefore, globs that work with `flutter test test` won't work with `flutter test`, and vice versa.

**Comment by matanlurey** [comment]
Thanks! I can update my example.

**Comment by juckele** [comment]
I'm not sure if this is because I'm on windows, but the DiskAssetBundle was actually putting assets at different paths than the glob, so "data/*.csv" made keys for "assets\data\sources.csv" and then the load of "assets/data/sources.csv" failed.

**Comment by mitenko** [comment]
thanks @matanlurey for the DiskAssetBundle. I ran into one issue with the implementation which is paths were being loaded in with backslashes ('assets\image.png') but the key in the load() calls had forward slashes. Obviously a platform thing (tests are running on windows). I solved this with the following: `
  @override
  Future<ByteData> load(String key) async {
    return _cache[key.replaceAll('/', '\\')];
  }`

**Comment by chunhtai** [comment]
The other workaround will be mocking the message channel within the test.
`
await tester.runAsync(() async {
    BinaryMessages.setMockMessageHandler('flutter/assets', (message) {
        // The key is the asset key.
        String key = utf8.decode(message.buffer.asUint8List());
        // Manually load the file.
        var file = new File('../${key}');
        final Uint8List encoded = utf8.encoder.convert(file.readAsStringSync());
        return Future.value(encoded.buffer.asByteData());
   });
   // continue your test, now your widget should be able to load the asset

`

Since we have this method to mock the asset channel, I suggest we close this issue. Thoughts?

**Comment by chunhtai** [comment]
It seems like the mocking can be done during the test setup. I will prepare a pr that will mock the channel by default, and does not require any additional workaround in test.

**Comment by chunhtai** [comment]
merged, the asset should be able to load without any workaround

**Comment by matanlurey** [comment]
Thanks!

**Comment by juckele** [comment]
Has the fix for this issue been deployed?

I'd used Matan's DiskAssetBundle.dart [here](https://github.com/juckele/starbuilder/tree/86ad363c76e7a6501a23943c0fcd6bc4f250db36/test), with a todo to remove the the DiskAssetBundle when this issue was closed. I've been looking at working more on this project and saw this issue was closed, so I tried updating [this ](https://github.com/juckele/starbuilder/blob/86ad363c76e7a6501a23943c0fcd6bc4f250db36/test/character_save_load.test.dart#L66) line:
`await MainDb.loadDatabaseWithAssetBundle(assetBundle);`
to
`await MainDb.loadDatabaseWithAssetBundle(rootBundle);`

These lines eventually indirectly execute [this ](https://github.com/juckele/starbuilder/blob/86ad363c76e7a6501a23943c0fcd6bc4f250db36/lib/database_source.dart#L11) line, simplified here as:
`String csvData = await assetBundle.loadString('assets/data/sources.csv');`

Using the rootBundle instead of Matan's DiskAssetBundle causes the following stack trace:
```
package:flutter/src/services/asset_bundle.dart 221:7  PlatformAssetBundle.load
===== asynchronous gap ===========================
dart:async                                            _AsyncAwaitCompleter.completeError
package:flutter/src/services/asset_bundle.dart        PlatformAssetBundle.load
===== asynchronous gap ===========================
dart:async                                            _asyncThenWrapperHelper
package:flutter/src/services/asset_bundle.dart        PlatformAssetBundle.load
package:flutter/src/services/asset_bundle.dart 67:33  AssetBundle.loadString

Unable to load asset: assets/data/sources.csv
```

Flutter Version:
```Flutter 1.7.8+hotfix.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 20e59316b8 (4 weeks ago) • 2019-07-18 20:04:33 -0700
Engine • revision fee001c93f
Tools • Dart 2.4.0
```

Is this expected to work to use the root bundle to access the asset without any workaround? Is there some other asset bundle that needs to be used instead of the rootBundle?

**Comment by chunhtai** [comment]
This only support testWidgets in 
'package:flutter_test/flutter_test.dart'

The mocking happened when it initialize flutter test binding that only happens in testWidgets.
Something like this should work

```
import 'dart:convert';

import 'package:flutter/services.dart';
import 'package:star_builder/character.dart';
import 'package:star_builder/database.dart';
//import "package:test/test.dart";
import 'package:flutter_test/flutter_test.dart';
import 'DiskAssetBundle.dart';

final bobString = """
{
  "Basic Info": {
    "Name": "Bob",
    "Race": "Human",
    "BaseClass": "Mystic",
    "Theme": "Colonist"
  },
  "Base Ability Scores": {
    "Str": 12,
    "Dex": 12,
    "Con": 12,
    "Int": 12,
    "Wis": 13,
    "Cha": 12
  }
}
""";

StarfinderCharacter getBob(){
  StarfinderCharacter character = StarfinderCharacter.fromBasicInfo(
      "Bob", "Human", "", "Mystic", "Colonist");
  character.setAbilities([12, 12, 12, 12, 13, 12]);
  return character;
}

final dualityString = """
{
  "Basic Info": {
    "Name": "\\"Duality\\"",
    "Race": ["Lashunta", "Damaya"],
    "BaseClass": "Technomancer",
    "Theme": "Cyberborn"
  },
  "Base Ability Scores": {
    "Str": 10,
    "Dex": 14,
    "Con": 8,
    "Int": 18,
    "Wis": 10,
    "Cha": 13
  }
}
""";

StarfinderCharacter getDuality(){
  StarfinderCharacter character = StarfinderCharacter.fromBasicInfo(
      "\"Duality\"", "Lashunta", "Damaya", "Technomancer", "Cyberborn");
  character.setAbilities([10,14,8,18,10,13]);
  return character;
}

void main() {
  setUp(() async {
    AssetBundle assetBundle =
    await DiskAssetBundle.loadAssets(MainDb.getAssetNames());
    await MainDb.loadDatabaseWithAssetBundle(rootBundle);
  });

  group("Character", () {
    testWidgets('Save Test - Bob', (WidgetTester tester) async {
      expect(getBob().save(), jsonEncode(jsonDecode(bobString)));
    });
    testWidgets('Load Test - Bob', (WidgetTester tester) async {
      expect(getBob().save(), StarfinderCharacter.load(bobString).save());
    });

    testWidgets('Save Test - "Duality"', (WidgetTester tester) async {
      expect(getDuality().save(), jsonEncode(jsonDecode(dualityString)));
    });
    testWidgets('Load Test - "Duality"', (WidgetTester tester) async {
      expect(getDuality().save(), StarfinderCharacter.load(dualityString).save());
    });
  });
}

```

**Comment by juckele** [comment]
Got it, thanks.

To clarify for anyone else who's running into this, Chuntai's fix requires using flutter_test.dart instead of test.dart:
```
//import "package:test/test.dart";
import 'package:flutter_test/flutter_test.dart';
```

and testWidgets instead of test:
```
// test('TestName"', () async { ... }
testWidgets('TestName"', (WidgetTester tester) async { ... }
```

**Comment by spideythewebhead** [comment]
Hi, if i am not mistaken, and you have files like images,csv,json etc and you want to load them in unit tests, one way is like the above instead of `test` use `testWidgets`, another way i have found is using the `File` and use it normally, for example: File('assets/my.json')

**Comment by albertusangga** [comment]
Since assets are available during tests now, if you are doing golden testing with image asset and it is flaky, #38997 might be helpful to look at.
