### ISSUE TITLE
Stream data disappears from StreamBuilder when we Drag a widget using LongPressDraggable

### ISSUE THREAD

**Issue by SriHarsh27** [flutter/flutter#129900]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. On the Android side, create an EventChannel.StreamHandler inside the configureFlutterEngine callback to pass String value.
2. On the Flutter side:
- create a TextStream widget which implements StreamBuilder that takes the Stream<String> as a required parameter (Get the broadcastStream from the WidgetViewModel).
- create a WidgetViewModel which extends ChangeNotifier and inside the class implement the EventChannel and receive the broadcastStream which returns event in the form of String.
- create a BaseWidget which implements Postioned and LongPressDraggable widget. Child and feedback parameter of LongPressDraggable is TextStream widget.

Attaching the Stackoverflow post with the code: https://stackoverflow.com/questions/76571124/stream-data-disappears-from-streambuilder-when-we-drag-a-widget-using-longpressd

### Expected results

When we drag a widget using Draggable / LongPressDraggable, then the last updated stream data should remain on the screen while drag / drop is performed.

### Actual results

When we drag a widget using LongPressDraggable, then the last updated stream data disappears (Shows other value from the StreamBuilder when snapshot has no data) while drag / drop is performed.

### Code sample

[https://stackoverflow.com/questions/76571124/stream-data-disappears-from-streambuilder-when-we-drag-a-widget-using-longpressd](url)

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.3.9, on Ubuntu 20.04.5 LTS 5.14.0-1059-oem,
    locale en_IN)
    • Flutter version 3.3.9 on channel stable at
      /home/u1646493/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (7 months ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/u1646493/Android/Sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at:
      /home/u1646493/.local/share/Trash/files/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.13.2
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/u1646493/.local/share/Trash/files/android-studio
    • Flutter plugin version 65.2.1
    • Dart plugin version 203.8452
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[!] Android Studio (version 2022.2)
    • Android Studio at
      /home/u1646493/Documents/android-studio-2022.2.1.20-linux/android-studio
    • Flutter plugin version 74.0.2
    • Dart plugin version 222.4582
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2023.1)
    • IntelliJ at /home/u1646493/Documents/idea-IC-231.8109.175
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.5 LTS
      5.14.0-1059-oem
    • Chrome (web)    • chrome • web-javascript • Chromium 114.0.5735.106 snap

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

</details>

**Comment by huycozy** [comment]
Hi @SriHarsh27 
The goal of this Github repo is not to give assistance on personal code, but to improve Flutter framework reporting bugs or feature requests.

If you encounter behavior that you believe could be a bug, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that represents the problem. Since your case is related to native code, it would be helpful if you can provide sample code in a GitHub repository.

Instead, if you think that the issue might depend on your implementation, please also see flutter's [community](https://flutter.dev/community) for resources and ask questions like this.

**Comment by SriHarsh27** [comment]
I am attaching the Github repository for the example project. 
Link: [https://github.com/SriHarsh27/Example](url)

Please try dragging / dropping the widget on the screen. You may notice Stream value disappears after drag is started. 

I think this kind of behavior is a bug. Please let me know if you're able to reproduce the same.

**Comment by huycozy** [comment]
Thanks for the update. I checked your code and notice you only emit one value from stream:

```kotlin
textEventSink?.success("Harsh")
```

I tried integrating with snippet code at [this](https://flutterawesome.com/get-stream-data-through-native-java-to-flutter-using-event-channel/) example and see the stream data persisted even when dragging widget. You can try it and see if it works for you or not.
