### ISSUE TITLE
Print zone-aware stack traces

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#130]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Wednesday Aug 19, 2015 at 23:16 GMT_
_Originally opened as https://github.com/flutter/engine/issues/702_

---

It's my understanding that when you use "async", zones keep track of the stack traces such that you can get sane usable stack traces. We should enable that by default in debug mode (at least).

CC @sethladd who may know what I'm talking about (since I don't...).

**Comment by FlutterIssues** [comment]
<a href="https://github.com/abarth"><img src="https://avatars.githubusercontent.com/u/112007?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [abarth](https://github.com/abarth)**
_Thursday Aug 20, 2015 at 16:25 GMT_

----

Any pointers on how to do this?

**Comment by eseidelGoogle** [comment]
@Hixie may be doing this as part of his big test refactor?

https://github.com/flutter/flutter/issues/3810 also has some context on this issue, may be a dupe.

**Comment by Hixie** [comment]
I'm not actively working on this specific thing, but the work I'm doing is teaching me what I need to know to be able to do it.

**Comment by Hixie** [comment]
I know enough now to know that I didn't know enough when filing the bug.
