### ISSUE TITLE
Update the dependency versions in firebase codelab

### ISSUE THREAD

**Issue by xster** [flutter/flutter#13007]
Some of the package version references at https://codelabs.developers.google.com/codelabs/flutter-firebase/#4 are slightly out of date.

**Comment by Fandekasp** [comment]
I'd love to make a PR for this if someone can help me with https://github.com/flutter/flutter/issues/13079

**Comment by Sfshaza** [comment]
This codelab has been obsoleted and replaced (at the same URL) by a new Firebase + Flutter codelab.

Closing.
