### ISSUE TITLE
Flutter Web mobile keyboard inconsistent  behavior redrawing app, cuts it out sometimes

### ISSUE THREAD

**Issue by maximalniq** [flutter/flutter#130070]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

The app is cut out sometimes, and the index.html page is shown as background.

1. Open the flutter web app
2. Tap on TextField 10 times
3. 1-2 out of the 10 times the app will redraw as shown

### Expected results

![Screenshot_20230706_153810_Edge](https://github.com/flutter/flutter/assets/17831615/870c926c-7278-4ee0-ae80-a4648a69ffce)

### Actual results

![Screenshot_20230706_153350_Edge](https://github.com/flutter/flutter/assets/17831615/89276394-f3b8-45d9-a0cc-a8bab50b1a00)

### Code sample

<details><summary>Code sample</summary>

![Screenshot 2023-07-06 164155](https://github.com/flutter/flutter/assets/17831615/947e95e7-08c0-45dd-b647-beddc940553f)

```dart
[Scaffold(
      resizeToAvoidBottomInset: false,
      body: GestureDetector(
        onTap: () {
          _showSliderNotifier.value = false;
        },
        child: Stack(children: [
          Container(
            decoration: const BoxDecoration(
                gradient: LinearGradient(
              begin: Alignment.topLeft,
              end: Alignment.bottomRight,
              colors: [
                Color.fromRGBO(73, 71, 190, 1),
                Color.fromRGBO(226, 87, 254, 1),
              ],
            )),
          ),
          SingleChildScrollView(
            child: Column(
            // all widgeds here, listview, logic etc... and Positioned Containers, including Textfield
            )
           )]
```

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.22621.1848], locale en-US)
    • Flutter version 3.10.5 on channel stable at E:\Programs\flutter sdk\flutter_windows_2.5.3-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (3 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.1)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31402.337
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and   
      include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1848]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 114.0.5735.90
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 114.0.1823.67

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
]
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @maximalniq 
Can you provide us complete runnable but minimal reproducible code sample without any third party package implementation that helps to replicate the reported behavior ?

Also, if you try with bare minimum counter app code and follow the steps as you mentioned, does the reported behavior persist ?

**Comment by maximalniq** [comment]
Sure, I tested with a minimal code, but kind of the same use of widgets and manage to reproduce the issue

Note: I had to tap TextField at least 20 times, before the app started to cut itself out after the virtual keyboard is shown.

`import 'package:flutter/material.dart';

class TestMobileKeyboard extends StatefulWidget {
  const TestMobileKeyboard({super.key});

  @override
  // ignore: library_private_types_in_public_api
  _TestMobileKeyboardState createState() => _TestMobileKeyboardState();
}

class _TestMobileKeyboardState extends State<TestMobileKeyboard>
    with WidgetsBindingObserver {
  bool desktopView = false;
  final globalKey = GlobalKey<ScaffoldState>();

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    // ignore: unused_local_variable
    Widget? currentPage;
    MediaQueryData queryData;
    queryData = MediaQuery.of(context);
    double queryWidth = queryData.size.width;
    double queryHeight = queryData.size.height;
    // print(queryHeight / 3.31);
    // print((queryWidth / 360).toInt());
    // print(queryWidth);
    desktopView = queryWidth > 800;
    // ignore: unused_local_variable
    double gridHeight;
    // ignore: unused_local_variable
    double listHeight;

    if (desktopView) {
      gridHeight = queryHeight / 1.18;
      listHeight = queryHeight / 1.185;
    } else {
      gridHeight = queryHeight / 1.18;
      listHeight = queryHeight / 1.17;
    }

    return Scaffold(
      resizeToAvoidBottomInset: false,
      body: Stack(children: [
        Container(
          decoration: const BoxDecoration(
              gradient: LinearGradient(
            begin: Alignment.topLeft,
            end: Alignment.bottomRight,
            colors: [
              Color.fromRGBO(73, 71, 190, 1),
              Color.fromRGBO(226, 87, 254, 1),
            ],
          )),
        ),
        SingleChildScrollView(
          child: Column(
            children: [
              Stack(children: [
                Center(child: Container(height: 60, color: Colors.transparent)),
                BackButt(
                  onPressed: () {
                    Navigator.of(context).popUntil((route) => route.isFirst);
                  },
                ),
                Stack(
                  children: [
                    Container(
                      // color: Colors.white,
                      height: gridHeight,
                      decoration: const BoxDecoration(
                        color: Colors.white,
                        borderRadius: BorderRadius.only(
                          topRight: Radius.circular(15.0),
                          topLeft: Radius.circular(15.0),
                        ),
                        boxShadow: [
                          BoxShadow(
                              blurRadius: 5,
                              color: Colors.white,
                              spreadRadius: 2.5)
                        ],
                      ),
                    ),
                    Positioned(
                      bottom: 0,
                      left: 0,
                      right: 0,
                      child: Padding(
                        padding: const EdgeInsets.only(top: 8, bottom: 8),
                        child: Container(
                          color: Colors.transparent,
                          // width: queryWidth / 1.5,
                          child: FittedBox(
                            fit: BoxFit.scaleDown,
                            child: Container(
                              height: queryHeight / 20,
                              width: queryWidth / 2.2,
                              decoration: const BoxDecoration(
                                color: Colors.white,
                                borderRadius:
                                    BorderRadius.all(Radius.circular(30.0)),
                                boxShadow: [
                                  BoxShadow(
                                      blurRadius: 5,
                                      color: Colors.grey,
                                      spreadRadius: 2.5)
                                ],
                              ),
                              child: Padding(
                                  padding: const EdgeInsets.only(right: 20),
                                  child: SingleChildScrollView(
                                    child: Stack(
                                      children: [
                                        Center(
                                            child: TextField(
                                          onTap: () {},
                                          keyboardType: TextInputType.multiline,
                                          minLines: 1,
                                          maxLines:
                                              null, // Allow any number of lines
                                          maxLength: 100,
                                          cursorColor: Colors.grey,
                                          textAlign: TextAlign.center,
                                          onChanged: (value) {},
                                          decoration: const InputDecoration(
                                            contentPadding:
                                                EdgeInsets.symmetric(
                                                    horizontal: 20.0,
                                                    vertical: 15.0),
                                            hintText: "     ...",
                                            border: InputBorder.none,
                                            counterText: '',
                                          ),
                                        )),
                                      ],
                                    ),
                                  )),
                            ),
                          ),
                        ),
                      ),
                    ),
                  ],
                ),
              ]),
            ],
          ),
        ),
      ]),
    );
  }
}`

**Rarely this happens:**

![Screenshot_20230707_150917_Edge](https://github.com/flutter/flutter/assets/17831615/99d56190-35f7-4a2c-ac0d-f637f2dcc510)

**Most of the time, this happens:**

![Screenshot_20230707_150933_Edge](https://github.com/flutter/flutter/assets/17831615/532d6624-92ba-4714-92ed-25a20ee91a00)

**Comment by darshankawar** [comment]
Thanks for the update @maximalniq 
Can you try with `resizeToAvoidBottomInset: true` ? https://api.flutter.dev/flutter/material/Scaffold/resizeToAvoidBottomInset.html

**Comment by maximalniq** [comment]
It was set to 'resizeToAvoidBottomInset: true' at first, when I tried to fix it I set it to
'resizeToAvoidBottomInset: false'  , both ways the app gets cut out like shown.

**Comment by darshankawar** [comment]
Thanks for the update. It seems you are hitting https://github.com/flutter/flutter/issues/124205, so please follow-up in it for further updates. Closing this as a duplicate.
