### ISSUE TITLE
[camera] startVideoRecording "onAvailable" error when Android Version < 13

### ISSUE THREAD

**Issue by BoyKopchok** [flutter/flutter#130017]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

await _cameraController.startVideoRecording(onAvailable: (image) => _processCameraImage(image: image));

### Expected results

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: CameraException(videoRecordingFailed, CAMERA_ERROR (3): endConfigure:512: Camera 1: Error configuring streams: Function not implemented (-38))

### Actual results

Camera Stop and crash.

**Comment by faisalmushtaq007** [comment]
i am getting the same issue 
_cameraController?.startVideoRecording(onAvailable: _processCameraImage); 
not working. It stucks on the first frame.

**Comment by huycozy** [comment]
Hi @BoyKopchok 
I can't see the issue on my device `Realme 6, Android 11` using plugin sample code (even with implementing callback `onAvailable`). Verified with `camera_android: ^0.10.8+3`.

Can you please share:
- Please provide the complete output of `flutter run -v`
- A minimal and runnable sample code. If the [plugin sample code](https://github.com/flutter/packages/tree/main/packages/camera/camera/example) is reproducible on your device, please confirm it.
- `camera_android` version from your `pubspec.lock` file
