### ISSUE TITLE
Flutter should publish a roadmap.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#13009]
Flutter should publish a rough roadmap detailing the current priorities of developers working on the Flutter framework, engine, developer tooling, plugins, etc..

The closest approximation to a roadmap currently is the [milestones page on the Github issue tracker](https://github.com/flutter/flutter/milestone). But something that details the high level priorities would be helpful. Example is [here](https://www.nativescript.org/roadmap).

**Comment by chinmaygarde** [comment]
Mentioned by @nni123 & @MichaelSowah on Gitter. cc @eseidelGoogle, @sethladd

**Comment by sethladd** [comment]
Thanks for the suggestion.

Things we're working on, which we've mentioned in various forums before so might as well collect here :)

(standard disclaimers apply, we can't guarantee dates, this list may change, etc)

* Accessibility
* i18n (this is ready for early testers, we have some docs here: https://flutter.io/tutorials/internationalization/)
* Localization (including our widgets)
* Inline video (demo plugin here: https://github.com/sigurdm/video_player)
* Inline maps
* Firestore support in FlutterFire (early API has landed, feedback welcome)
* Dart 2 support (as Dart 2 comes online, we hope to be one of the first to turn it on)
* Running Dart code when the phone is off or the app isn't in the foreground
* Saving state when the app is killed (in partnership with @takhion)
* Animated GIFs
* Exploring libtxt as a new way to render text
* Attention to detail for Cupertino, iPhone X, iOS 11

**Comment by tomaszpolanski** [comment]
Do you accept contributions for i18n/l10n?
If so, I would love to help. Now I need to support the Polish language (which is not yet supported by Flutter) for my app, so I could contribute to the code and the translations as well for Flutter.

Btw, thanks for the awesome work!

**Comment by eseidelGoogle** [comment]
Work on i18n is tracked in https://github.com/flutter/flutter/projects/17.  @HansMuller is leading that effort, I would encourage you to reach out to him directly or via one of the relevant bugs.

With regards to specific localizations, we're in the process of wiring up Flutter to use Google's localization infrastructure which handles many many languages (including polish).  I expect we'll see updates to our list of supported languages through that soon.  Again @HansMuller would know more.

**Comment by Arno-Z** [comment]
I would welcome better FireStore support very much. Right now the early API crashes when used in combination with auth and/or analytics.

**Comment by sethladd** [comment]
@Arno-Z sorry to hear that! please open a bug for us. Even though it's early for our implementation, it shouldn't crash.

**Comment by Arno-Z** [comment]
@sethladd sure, i will clone the firestore example from the 0.0.3 API and add the auth and analytics component and file a proper bug report.

**Comment by MichaelSowah** [comment]
@sethladd So that info could be organized somewhere on the site or somewhere and updated from time to time and @chinmaygarde mentioned, @nni123 and I clearly mentioned that there's no need for dates, just the list would be fine...This really does help us make informed decisions

**Comment by sethladd** [comment]
@MichaelSowah please let us know (by "thumbs up" an issue) what is critical for you. thanks!

**Comment by MichaelSowah** [comment]
@sethladd I have done that for all of them already and some I have already seen being worked on but just waiting for some of them to land in the alpha channel

**Comment by MichaelSowah** [comment]
@sethladd one is the
 Inline video (demo plugin here: https://github.com/sigurdm/video_player) - which am waiting for it to land in the alpha channel 

and the others like 

- Running Dart code when the phone is off or the app isn't in the foreground - this will help me do 
background tasks

- Saving state when the app is killed (in partnership with @Takhion)

**Comment by sethladd** [comment]
@MichaelSowah great, sounds like we're on track to help you out :)

**Comment by MichaelSowah** [comment]
Yeah, largely, just waiting for the inline video thing to land in the alpha channel and I can resume work and almost even complete it...while the others are being worked on

**Comment by bjornbjorn** [comment]
@Arno-Z @sethladd there is already a bug for the Firebase Auth / Firestore combo crash on Android, it's tracked here: https://github.com/flutter/flutter/issues/12945

But yeah, overall the Firestore Flutter plugin needs some serious love:

- It will crash your app if you return anything else than a String it seems (?) (At least if you return a [Timestamp](https://github.com/flutter/flutter/issues/12437), a [GeoPoint](https://github.com/flutter/flutter/issues/12468) or a DocumentReference).

- You don't get the [DocumentID](https://github.com/flutter/flutter/issues/12471) for the documents returned

- you can't [delete a document](https://github.com/flutter/flutter/issues/12802).

- You can't [use .where() to query the Firestore](https://github.com/flutter/flutter/issues/12396).

What works fine right now is **returning all documents in a collection without documentIDs.**

It seems these issues are being worked on though so I am hopeful 🙏 👍

**Comment by eseidelGoogle** [comment]
@bjornbjorn thank you for filing issues.  @collinjackson and @kroikie are actively working on improving the firestore plugin.  The issues you filed are the right way to get those bugs addressed, thanks!

**Comment by sethladd** [comment]
Great list, thank you @bjornbjorn !

I'm going to close comments on this issue. We'd love "thumbs up" votes on issues, and/or open new issues. Thank you all for the feedback!
