### ISSUE TITLE
[google_sign_in_web] Force unwrap blocking access for people with company private profile picture

### ISSUE THREAD

**Issue by kamilpowalowski** [flutter/flutter#130002]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. On your company Google account, go to https://myaccount.google.com/personal-info?hl=en and set Choose who can see your profile picture to "Your organization and people you interact with"
2. Try to sign in using https://pub.dev/packages/google_sign_in_web (on Flutter Web)
![Screenshot 2023-07-04 at 16 51 05](https://github.com/flutter/flutter/assets/83073/45a21d59-0d84-4626-8608-3904d38bf40d)

### Expected results

The user should be signed in to their Google account.

### Actual results

Application crashes because the picture is not and the library tries to unwrap it. 

### Code sample

<details><summary>Code sample</summary>
error is made by line `photoUrl: payload['picture']! as String,`
```dart
  return GoogleSignInUserData(
    email: payload['email']! as String,
    id: payload['sub']! as String,
    displayName: payload['name']! as String,
    photoUrl: payload['picture']! as String,
    idToken: credentialResponse.credential,
  );
```

according to https://github.com/flutter/packages/blob/704207985a21113866e2bbc912ab73e9b743a022/packages/google_sign_in/google_sign_in_platform_interface/lib/src/types.dart#L122 picture and name can be null, but given code uses force unwrap to access it.

</details>

### Screenshots or Video

<details>
<summary>Console log of visible bug</summary>

![Screenshot 2023-07-05 at 13 37 51](https://github.com/flutter/flutter/assets/83073/ef9bf784-8ba6-4953-a5a4-bbdc552a3fc3)

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F82 darwin-arm64, locale en-US)
    • Flutter version 3.10.5 on channel stable at /Users/kamilpowalowski/fvm/versions/3.10.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (3 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/kamilpowalowski/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode-14.3.1.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (2 available)
    • macOS (desktop)                • macos                     • darwin-arm64   • macOS 13.4.1 22F82 darwin-arm64
    • Chrome (web)                   • chrome                    • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by ditman** [comment]
I'll "triage" this issue, this is a great find. Thanks for submitting a fix as well!
