### ISSUE TITLE
BlendMode.screen has no effect on iOS

### ISSUE THREAD

**Issue by zhxst** [flutter/flutter#130059]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I'm using custom painter with canvas.
I have tested it on flutter 3.10.5 and 3.12.0_beta.

1. draw a black circle use canvas.drawCircle
`canvas.drawCircle(center, 100, blackPaint);`
2. apply a green color with BlendMode.screen:
`canvas.drawColor(Colors.green, BlendMode.screen);`

### Expected results

The final result should be a green circle on screen.

### Actual results

It works fine on android, but on iOS, the circle is still black.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatefulWidget {
  const MainApp({super.key});

  @override
  State<MainApp> createState() => _MainAppState();
}

class _MainAppState extends State<MainApp> with SingleTickerProviderStateMixin {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: AspectRatio(
          aspectRatio: 1,
          child: SizedBox(
            width: double.infinity,
            child: CustomPaint(
              painter: SimplePainter(),
            ),
          ),
        ),
      ),
    );
  }
}

class SimplePainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    final blackPaint = Paint()
      ..style = PaintingStyle.fill
      ..color = Colors.black;

    final center = size.center(Offset.zero);
    canvas.drawCircle(center, 100, blackPaint);

    canvas.drawColor(Colors.green, BlendMode.screen);
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) {
    return false;
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F82 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.10.5 on channel stable at /Users/zhx/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (3 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/zhx/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode_14.3.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.69.20230703

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (2 available)
    • MI 8 (mobile)   • ba9b410d • android-arm64 • Android 10 (API 29)
    • macOS (desktop) • macos    • darwin-arm64  • macOS 13.4.1 22F82 darwin-arm64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
</details>

**Comment by darshankawar** [comment]
Thanks for the report @zhxst 
I verified the code sample on latest master and it seems to work as expected.

<img width="361" alt="Screenshot 2023-07-06 at 6 24 29 PM" src="https://github.com/flutter/flutter/assets/67046386/222f89b9-8b9f-418e-a09a-8353b13d3f5c">

Check the same by switching to latest master.

`flutter channel master`
`flutter upgrade`

**Comment by zhxst** [comment]
> Thanks for the report @zhxst I verified the code sample on latest master and it seems to work as expected.
> 
> <img alt="Screenshot 2023-07-06 at 6 24 29 PM" width="361" src="https://user-images.githubusercontent.com/67046386/251455965-222f89b9-8b9f-418e-a09a-8353b13d3f5c.png">
> Check the same by switching to latest master.
> 
> `flutter channel master` `flutter upgrade`

Thank you. You are right. It worked on the master channel.

**Comment by darshankawar** [comment]
Thanks for the update. Closing this as the functionality works as expected on master channel.
