### ISSUE TITLE
SearchAnchor ListTiles returned from the suggestionsBuilder does not get updated

### ISSUE THREAD

**Issue by raymond-itag** [flutter/flutter#130075]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Add a SearchAnchor widget in the build method of a Stateful Widget in this case
2. Update the title of the tag object that was created a ListTile of in the search anchors suggestionsBuilder function

### Expected results

The ListTile should now have a title of 'something else' but it does not,

### Actual results

Title of the ListTile does not change

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '130075',
      theme: ThemeData(
        // colorScheme: ColorScheme.fromSeed(seedColor: Colors.orange),
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<Tag> tags = [Tag('name1', 'description1'), Tag('name2', 'description2')];
  SearchController searchController = SearchController();

  List<ListTile> createTiles() {
    return tags.map((t) {
      return ListTile(title: Text(t.name), subtitle: Text(t.description));
    }).toList();
  }

  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    super.dispose();
    searchController.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Wrap(
        // mainAxisAlignment: MainAxisAlignment.spaceAround,
        // crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          ListView(
            shrinkWrap: true,
            children: createTiles(),
          ),
          SearchAnchor(
            searchController: searchController,
            isFullScreen: false,
            builder: (BuildContext context, SearchController controller) {
              return Padding(
                padding: const EdgeInsets.all(16),
                child: IconButton.filled(
                  icon: const Icon(Icons.search_outlined),
                  onPressed: () {
                    searchController.openView();
                  },
                ),
              );
            },
            viewTrailing: [
              ElevatedButton(
                onPressed: () {
                  debugPrint('updating name of first tag to "something else"');
                  setState(() {
                    tags[0].name = 'something else';
                  });
                },
                child: Text('Update name of the first tag'),
              ),
            ],
            viewHintText: 'Search',
            suggestionsBuilder: (BuildContext context, SearchController controller) {
              return createTiles();
            },
          ),
        ],
      ),
    );
  }
}

class Tag {
  Tag(this.name, this.description);
  String name;
  String description;
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel master, 3.12.0-14.0.pre.26, on Microsoft Windows [Version 10.0.19044.3086], locale nb-NO)
    • Flutter version 3.12.0-14.0.pre.26 on channel master at c:\Android\flutter-3.0.0
    ! Warning: `flutter` on your path resolves to C:\Android\flutter.bat, which is not inside your current Flutter SDK checkout at c:\Android\flutter-3.0.0. Consider adding c:\Android\flutter-3.0.0\bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision aa5f4a28e9 (6 days ago), 2023-06-30 18:16:21 -0700
    • Engine revision e6b8292705
    • Dart version 3.1.0 (build 3.1.0-262.0.dev)
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\RaymondHolmboe\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Stable\Community
    • Visual Studio Community 2022 version 17.6.33723.286
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code, 64-bit edition (version 1.73.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.3086]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 114.0.5735.135
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 110.0.1587.57

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

</details>

**Comment by darshankawar** [comment]
@raymondholmboe 
You probably are seeing the reported behavior due to your `suggestionsBuilder` isn't async. Since it doesn't seem to support async calls yet, see https://github.com/flutter/flutter/issues/126531, can you try using `FutureBuilder` instead and see if it helps in your case ?

**Comment by raymond-holmboe** [comment]
It won't help me to do it async, my scenario is to update the already existing ListTiles that once had been returned from the suggestionsBuilder. The reason being that I want to retrieve the thumbnail image for each ListTile async later, from the server, so that the suggestions are still snappy for my incremental search, even though they lack a thumbnail for a couple of seconds. In this example it's the ListTile title, but for all practical purposes it's the same thing, to be able to update the ListTile later.

**Comment by darshankawar** [comment]
Can you provide us runnable but minimal reproducible code sample that we can directly copy paste and run to verify it further ?

**Comment by raymondholmboe** [comment]
Replaced the existing code sample with now one main.dart file. In it, you see two lists, one outside the SearchAnchor and one inside the SearchAnchor, when you click the button inside the SearchAnchor called "Update name of the first tag", then you can see the listview outside the SearchAnchor is properly updating, but the one inside the SearchAnchor is not.

**Comment by darshankawar** [comment]
Thanks for the update. I tried replicating using latest master version with which I think I saw expected behavior as below:


https://github.com/flutter/flutter/assets/67046386/9d791ecb-1db9-4179-8d12-f9c6aebe1eb6

The inside one updates after tapping on done button from the keyboard.

**Comment by raymond-holmboe** [comment]
Yes, same as what I'm seeing, but I would expect the inside one to update on `setState` also

**Comment by raymond-itag** [comment]
Yes, same as what I'm seeing, but I would expect the inside one to update on setState also

**Comment by darshankawar** [comment]
> but I would expect the inside one to update on setState also

Check [this](https://stackoverflow.com/questions/72624006/flutter-text-field-not-updating-with-setstate) SO link and underlying comments and see if it helps in your case or not.

**Comment by raymond-itag** [comment]
Could not get that working, but I found a workaround:
In `suggestionsBuilder` callback I stored the `BuildContext`. Then when I need the list to update, I called `setState` on the ancestor state:
```
                    var state = suggestionsBuilderContext?.findAncestorStateOfType();
                    state?.setState(() {});
```
If anyone else can get this working with a `StatefulBuilder` or `InheritedWidget`, I'll be happy to use that instead

**Comment by darshankawar** [comment]
> In `suggestionsBuilder` callback I stored the `BuildContext`. Then when I need the list to update, I called `setState` on the ancestor state:

Thanks for the update and I think this would a way to go considering the hierarchy / structure of widgets in your code implementation. 

> If anyone else can get this working with a `StatefulBuilder` or `InheritedWidget`, I'll be happy to use that instead

StackOverflow would be a good place to know more about this case.
