### ISSUE TITLE
!_debugLocked': is not true.

### ISSUE THREAD

**Issue by mithleshgurjar11** [flutter/flutter#130006]
======== Exception caught by widgets library =======================================================
The following assertion was thrown building Navigator-[LabeledGlobalKey<NavigatorState>#0ad28](dirty, dependencies: [HeroControllerScope, UnmanagedRestorationScope], state: NavigatorState#ec9f0(tickers: tracking 4 tickers)):
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 5234 pos 12: '!_debugLocked': is not true.

**Comment by danagbemava-nc** [comment]
Hi @mithleshgurjar11, 

Please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with steps to reproduce so that we can investigate this issue. 

Thank you
