### ISSUE TITLE
[camera] .startVideoRecording not working, stuck at first frame image.

### ISSUE THREAD

**Issue by faisalmushtaq007** [flutter/flutter#130052]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

  i am getting the same issue 
_cameraController?.startVideoRecording(onAvailable: _processCameraImage); 
not working. It stucks on the first frame.

```
W/CameraDevice-JV-1(16256): Stream configuration failed due to: endConfigure:679: Camera 1: Unsupported set of inputs/outputs provided
E/CameraCaptureSession(16256): Session 1: Failed to create capture session; configuration failed
I/Camera  (16256): CameraCaptureSession onConfigureFailed
I/Camera  (16256): CameraCaptureSession onClosed
```

### Expected results

```
W/CameraDevice-JV-1(16256): Stream configuration failed due to: endConfigure:679: Camera 1: Unsupported set of inputs/outputs provided
E/CameraCaptureSession(16256): Session 1: Failed to create capture session; configuration failed
I/Camera  (16256): CameraCaptureSession onConfigureFailed
I/Camera  (16256): CameraCaptureSession onClosed
```

### Actual results

it needs to record video and also give frame streams.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Flutter Doctor output

 Flutter (Channel stable, 3.10.5, on macOS 13.4 22F66 darwin-arm64, locale en-IN)
    • Flutter version 3.10.5 on channel stable at /Users/lelafeitsolutions/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (3 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/lelafeitsolutions/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.75.1)
    • VS Code at /Users/lelafeitsolutions/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • CPH2487 (mobile) • d61e2731 • android-arm64  • Android 13 (API 33)
    • macOS (desktop)  • macos    • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)     • chrome   • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

**Comment by huycozy** [comment]
Hi @faisalmushtaq007 
I saw your comment at https://github.com/flutter/flutter/issues/130017 but this issue is about different behavior (only stucking, not crashing).

Please provide the information indicated below so we can investigate issue better:
- Which device are you seeing this issue? (OS, model) 
- What is the current `camera_android` version (check it from `pubspec.lock` file)
- It would be appreciated if you can provide a recorded video of this issue

Thank you!
