### ISSUE TITLE
Caching issue when using deferred load on the web

### ISSUE THREAD

**Issue by dmitry-fbm** [flutter/flutter#130082]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

When using deferred load the compiler breaks js code into chunks such as `main.dart.js_XX.part.js`; this naming remains the same after deploying a new version, hence causing browser to keep reusing cached version. In case of `main.dart.js` and `flutter_service_worker.js`  it's possible to add version string manually, such as `"/main.dart.js?v=" + serviceWorkerVersion`, but not for dynamically loaded scripts. In particular the issue concerns dictionaries; for instance this code generates fixed names:

```dart
import 'messages_AA.dart' deferred as messages_AA;
...
import 'messages_ZZ.dart' deferred as messages_ZZ;
```
We need a mechanism that would trigger re-caching of changed chunks - ideally based on file hash so that only really changed content would re-cache. 

### Expected results

After code or dictionary change corresponding content should be re-cached by browsers.

### Actual results

Browsers keep using obsolete cached version unless the page is explicitly refreshed.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'messages_AA.dart' deferred as messages_AA;
...
import 'messages_ZZ.dart' deferred as messages_ZZ;
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by Sulisong** [comment]
I also encountered this problem

**Comment by darshankawar** [comment]
Thanks for the report @dmitry-fbm 
Can you take a look at [this](https://github.com/flutter/flutter/issues/127459) issue and underlying comments to check if it resembles your case or not ?

**Comment by dmitry-fbm** [comment]
> Can you take a look at [this](https://github.com/flutter/flutter/issues/127459) issue and underlying comments to check if it resembles your case or not ?

@darshankawar yes thank you. Sorry for duplicate, missed that one. Same thing, also had `DeferredLoadException` in logs.

**Comment by darshankawar** [comment]
Thanks for confirming. Closing as duplicate.
