### ISSUE TITLE
flutter/packages tests need default apps, or a way to set them, on Linux

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#130074]
Some Linux tests in flutter/packages, notably `url_launcher`, need default handlers set for common schemes (http, https, file) in order for the tests to work. Trying to run them currently on LUCI fails, as discussed [in the PR trying to enable them](https://github.com/flutter/packages/pull/4223#issuecomment-1593724934). (Ignore the `xvfb` part of the discussion there; it's separate, and already resolved.)

For Cirrus we handled this [in the Dockerfile](https://github.com/flutter/packages/blob/main/.ci/Dockerfile#L37-L40). I tried running the same things in a script on LUCI to see what would happen, and got:
- `xdg-settings set default-web-browser ...` to set default browser:
    `xdg-settings: unknown desktop environment`
- `xdg-mime default ...` to set default `file:` handler:
    ```
     touch: cannot touch '/home/chrome-bot/.local/share/applications/mimeapps.list': No such file or directory
     /b/s/w/ir/cache/chrome/chrome/xdg-mime: 780: cannot create /home/chrome-bot/.local/share/applications/mimeapps.list.new: 
     Directory nonexistent
    ```

So the tools exist, but don't appear to work. While Docker support is one way to possibly resolve this, it would be significant overkill. All we really need to unblock this is either:
- a way for a script to successfully set `http`, `https`, and `file` default handlers, or
- some handlers for those schemes baked into the image (we don't need generic control of other handlers, and I don't foresee needing more than those three). The handlers can be literally anything, we just need `g_app_info_get_default_for_uri_scheme` and `g_file_query_default_handler` to return something when the plugin tests query for handlers.

**Comment by stuartmorgan** [comment]
@yusuf-goog Any idea why we're getting "unknown desktop environment" on the bots? Is there something unusual about the Ubuntu installation we're using?

**Comment by yusuf-goog** [comment]
Our OS installs should be pretty standard on the bots. Let me dig into this a little.

**Comment by yusuf-goog** [comment]
@stuartmorgan can you point me to a place where this is being called in your code

**Comment by stuartmorgan** [comment]
In the hacked-up version in the PR it's at https://github.com/flutter/packages/pull/4223/files#diff-de7f095046616ef631c46a111e377c517ddb46a625d2df03abe827ce0f161c0c

(It's not being called anywhere in landed code because it doesn't work. Unless you mean for Cirrus, in which case it's only in the Dockerfile lines I linked above, not in our code.)

**Comment by yusuf-goog** [comment]
This is fixed by changes in: https://github.com/flutter/packages/pull/4442 which has been rolled into https://github.com/flutter/packages/commit/53e544678fb4cdf265fd7813c4667bbe154ef128
