### ISSUE TITLE
[Impeller] Using color filters on SVGs results in incorrect rendering.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#130078]
This is an umbrella bug I'm using to deduplicate a number of related bugs getting filed in flutter_svg to so we can track it more easily in the Impeller sync up.

@bdero is probably fixing most or all of these with some changes to the way that blends are handled.

@chinmaygarde fyi

**Comment by chinmaygarde** [comment]
From Bug Backlog Grooming: @dnfield  This is an umbrella bug without enough context. Is it obsolete?
