### ISSUE TITLE
Codelab step 6 clarifications

### ISSUE THREAD

**Issue by xster** [flutter/flutter#13008]
In https://codelabs.developers.google.com/codelabs/flutter-firebase/#5
The instruction that says: "Add the bundle ID and the reverse URL of your client id to the main dictionary of your app's Info.plist file:"
may be a bit ambiguous since the bundle ID is already in the app's Info.plist under the key `CFBundleIdentifier`. 

Looking at the example below, it seems like it's really asking to add both the bundle ID and firebase's reversed client ID as array entries to the key `CFBundleURLSchemes`.

**Comment by xster** [comment]
It may also be safer to add `$(PRODUCT_BUNDLE_IDENTIFIER)` as array entry instead of literally typing out the string again. In case the user decides to change it later via the Runner target's General tab settings, there won't be risks of it diverging.

**Comment by sethladd** [comment]
cc @LarkAscending @mjohnsullivan

**Comment by LarkAscending** [comment]
Agreed... these config steps might have been subject to some drift on the iOS side. The variable is a big improvement. Will update this.

/cc @collinjackson

**Comment by LarkAscending** [comment]
Looks like the Info.plist direction was there pre-IO and none of the testers flagged it. (@xster this means you too!)

@sethladd sure we can add the reference to `$(PRODUCT_BUNDLE_IDENTIFIER)` as a manual step for FlutterFire. Question is, is there any Firebase scenario where a user wouldn't want this value in  GoogleService-Info.plist? In other words, should we ask Firebase to add this variable to their default GoogleService-Info.plist file? Maybe they just haven't caught up with the handy new variable from the iOS folks....and would appreciate the nudge.

**Comment by Sfshaza** [comment]
This codelab has been obsoleted and replaced by a new Firebase + Flutter codelab (at the same URL).

Closing
