### ISSUE TITLE
NavigationDecision.prevent Not works on ios 

### ISSUE THREAD

**Issue by santhoshkumar4035** [flutter/flutter#130054]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Can you give any suggestion to solve this problem.

### Expected results

How to solve this issue in ios .

### Actual results

after login using webview_flutter's webview i'll check it current url contains my redirect url then it matches i'll pop my page , but this flows worked in android perfectly , but  in ios after checking result url with my redirect url, and this condition was true and NavigationDecision.prevent after this it directly goes to onWebResourceError (Error), fields , this fields contains "Frame load interupted " error , how to solve this issue.

         

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```
 navigationDelegate: (navigation) async {
            if (navigation.url.toString().contains(AppConstant.redirectUrl)) {
              return NavigationDecision.prevent;
            }
            return NavigationDecision.navigate;
          },
          onPageFinished: (url) {
            if (url.contains(AppConstant.redirectUrl)) {
              final uri = Uri.parse(url);
              final String code = uri.queryParameters['code'] ?? '';
              Navigator.pop(context, [code, codeVerifier]);
            }
          },
          onWebResourceError: (error) {
            _webViewController!.clearCache();
          },
          javascriptMode: JavascriptMode.unrestricted,
          initialUrl: authorizeurl,
        ));
        
</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>
'Frame load interupted'

**Comment by darshankawar** [comment]
@santhoshkumar4035 
Check [this](https://github.com/flutter/flutter/issues/65502#issuecomment-696237384) solution and [this](https://github.com/flutter/flutter/issues/65502#issuecomment-1370804778) implementation which should help to resolve your issue.

Closing for now. Also, your issue is more of `how to` implementation rather than a bug which indicates it as a support question so you can raise it in StackOverflow.
