### ISSUE TITLE
[Impeller] OpenGL: Support offscreen MSAA

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#130045]
`glFramebufferTexture2DMultisampleEXT` is available through `GL_EXT_multisampled_render_to_texture` and `EXT_framebuffer_multisample`. There's also a relevant Apple extension `APPLE_framebuffer_multisample`, but GLES on Apple targets is best effort.

One caveat is that Impeller's 2D renderer (Entity layer) relies on the ability to store multisample stencil attachments between RenderPasses, but crucially, the full multisample color attachment is _always_ resolved to a single-sample resolve texture and _never_ stored as a full multisample color texture (although impeller's HAL design does allow for this).
Avoiding multisample color storage is crucial on Android due to the extreme bandwidth requirements.

**Comment by bdero** [comment]
In order to make this work, I believe we'd also need `GL_ARB_texture_multisample`, so that we can allocate/bind multisample stencil textures to the FBO.

**Comment by jonahwilliams** [comment]
Example of how to use it: https://github.com/ARM-software/opengl-es-sdk-for-android/blob/master/samples/advanced_samples/MultisampledFBO/jni/MultisampledFBO.cpp

**Comment by matanlurey** [comment]
I'm going to take this issue, since it's important for us validating OpenGL versus Vulkan performance.

**Comment by matanlurey** [comment]
Ok here is my working understanding so far, mostly for @jonahwilliams to correct:

## We conditionally create MSAA targets

For example, in `entity_pass.cc`:

```cc
RenderTarget target;
if (context->GetCapabilities()->SupportsOffscreenMSAA()) {
  target = RenderTarget::CreateOffscreenMSAA(
      *context,                          // context
      *renderer.GetRenderTargetCache(),  // allocator
      size,                              // size
      "EntityPass",                      // label
      RenderTarget::AttachmentConfigMSAA{
          .storage_mode = StorageMode::kDeviceTransient,
          .resolve_storage_mode = StorageMode::kDevicePrivate,
          .load_action = LoadAction::kDontCare,
          .store_action = StoreAction::kMultisampleResolve,
          .clear_color = clear_color},   // color_attachment_config
      GetDefaultStencilConfig(readable)  // stencil_attachment_config
  );
} else {
  target = RenderTarget::CreateOffscreen(
      *context,                          // context
      *renderer.GetRenderTargetCache(),  // allocator
      size,                              // size
      "EntityPass",                      // label
      RenderTarget::AttachmentConfig{
          .storage_mode = StorageMode::kDevicePrivate,
          .load_action = LoadAction::kDontCare,
          .store_action = StoreAction::kDontCare,
          .clear_color = clear_color,
      },                                 // color_attachment_config
      GetDefaultStencilConfig(readable)  // stencil_attachment_config
  );
}
```

The difference is the render target is configured with `store_action = StoreAction::kMultisampleResolve`.

## In our other backends, this is conditionally applied

For example, `render_pass_mtl.mm`:

```cc
static bool ConfigureResolveTextureAttachment(
    const Attachment& desc,
    MTLRenderPassAttachmentDescriptor* attachment) {
  bool needs_resolve =
      desc.store_action == StoreAction::kMultisampleResolve ||
      desc.store_action == StoreAction::kStoreAndMultisampleResolve;

  if (needs_resolve && !desc.resolve_texture) {
    VALIDATION_LOG << "Resolve store action specified on attachment but no "
                      "resolve texture was specified.";
    return false;
  }

  if (desc.resolve_texture && !needs_resolve) {
    VALIDATION_LOG << "A resolve texture was specified even though the store "
                      "action doesn't require it.";
    return false;
  }

  if (!desc.resolve_texture) {
    return true;
  }

  attachment.resolveTexture =
      TextureMTL::Cast(*desc.resolve_texture).GetMTLTexture();

  return true;
}
```

## OpenGLES needs a change in `OnEncodeCommands`

@jonahwilliams:

> Mostly just copy-pasta the code from: https://github.com/ARM-software/opengl-es-sdk-for-android/blob/master/samples/advanced_samples/MultisampledFBO/jni/MultisampledFBO.cpp into https://github.com/flutter/engine/blob/main/impeller/renderer/backend/gles/render_pass_gles.cc#L142
>
> ...
>
> Look at `RenderPassGLES::OnEncodeCommands`
> that is where the render target object is processed, there will be different configurations for MSAA vs non-MSAA. MSAA will have a separate resolve and msaa texture, and a sample count set

```cc
// render_pass_gles.cc

//----------------------------------------------------------------------------
/// Setup color data.
///
pass_data->color_attachment = color0.texture;
pass_data->clear_color = color0.clear_color;
pass_data->clear_color_attachment = CanClearAttachment(color0.load_action);
pass_data->discard_color_attachment =
    CanDiscardAttachmentWhenDone(color0.store_action);
```

We'll want to (conditionally) encode this in `pass_data`, and then do the work in `EncodeCommandsInReactor`.

For example, this is roughly how `MultisampledFBO.cpp` does it, with `+`s added by me to make it easier to read:

```diff
/* Generate FBOs and render buffers for non-antialiased and multisampled rendering. */
- if (!setupFBO(&frameBufferNoAA, &texColorBufferNoAA, &depthBufferNoAA, textureSizes[currentTextureSize], textureFormats[currentTextureFormat], 0)) return false;
+ if (!setupFBO(&frameBufferMSAA, &texColorBufferMSAA, &depthBufferMSAA, textureSizes[currentTextureSize], textureFormats[currentTextureFormat], currentSamples)) return false;
```

<details>

<summary>Note that it passes `currentSamples` for MSAA, which is calculated via (expand to read)</summary>

```cc
/* Find the best texture format supporting the greatest number of samples. */
GLint bestSamples = 0;
GLint bestTextureFormat = 0;
for (unsigned int i = 0; i < sizeof textureFormats / sizeof (GLuint); i++)
{
  if (textureFormatSamples[i] >= bestSamples)
  {
    bestSamples = textureFormatSamples[i];
    bestTextureFormat = i;
  }
}

currentSamples = bestSamples;
```

</details>

Their `setupFBO` function then uses `currentSamples`:

```diff
bool setupFBO(GLuint* fbo, GLuint* colorBuffer, GLuint* depthBuffer, GLuint textureSize, GLenum internalFormat, GLuint samples)
{
GL_CHECK(glTexStorage2D(GL_TEXTURE_2D, 1, internalFormat, textureSize, textureSize));
+ GL_CHECK(glFramebufferTexture2DMultisampleEXT(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_TEXTURE_2D, *colorBuffer, 0, samples));

GL_CHECK(glBindRenderbuffer(GL_RENDERBUFFER, *depthBuffer));
+ GL_CHECK(glRenderbufferStorageMultisampleEXT(GL_RENDERBUFFER, samples, GL_DEPTH_COMPONENT16, textureSize, textureSize));
}
```

We'll have to make similar calls, except _conditionally_. For example, if samples is `0`, we'll assume (?) MSAA is not available.

**Comment by matanlurey** [comment]
Let's assume `currentSamples = 4` for now, when MSAA is supported (i.e. not having 4-sample is equivalent to not supporting).

I might need both the resolve and MSAA texture stored (`*colorBuffer` is the multi-sample texture). The way MSAA works you have two textures (resolving into a real texture). `RenderTargetObject` has two textures (multi-sample, resolve texture) -setting `render_texture` in `pass_data`.

**Comment by matanlurey** [comment]
Picking this up again after being quasi-OOO/traveling.

There is some scaffolding in place (https://github.com/flutter/engine/pull/46381) and some debugging work done https://github.com/flutter/engine/pull/46392), so next step is just to finish plumbing everything through and see what breaks :)

**Comment by matanlurey** [comment]
Here is `render_target.ToString()` where...

**`opacity: 1.0`**:

```txt
RenderPassGLES::OnEncodeCommands: 
Color[0]=(Texture=(StorageMode=DevicePrivate,Type=Texture2D,Format=R8G8B8A8UNormInt,Size=(1080, 2274),MipCount=1,SampleCount=1,Compression=Lossless),LoadAction=Clear,StoreAction=Store,ClearColor=(R=1.0,G=1.0,B=1.0,A=1.0)),Stencil=(Texture=(StorageMode=DeviceTransient,Type=Texture2D,Format=R8G8B8A8UNormInt,Size=(1080, 2274),MipCount=1,SampleCount=1,Compression=Lossless),LoadAction=Clear,StoreAction=DontCare,ClearStencil=0)
```

**`opacity: 0.5`**:

Note `OnEncodeCommands` is invoked with two different inputs:

```txt
RenderPassGLES::OnEncodeCommands:
Color[0]=(Texture=(StorageMode=DevicePrivate,Type=Texture2D,Format=R8G8B8A8UNormInt,Size=(825, 825),MipCount=1,SampleCount=1,Compression=Lossless),LoadAction=Clear,StoreAction=Store,ClearColor=(R=0.0,G=0.0,B=0.0,A=0.0)),Stencil=(Texture=(StorageMode=DeviceTransient,Type=Texture2D,Format=S8UInt,Size=(825, 825),MipCount=1,SampleCount=1,Compression=Lossless),LoadAction=Clear,StoreAction=DontCare,ClearStencil=0)

RenderPassGLES::OnEncodeCommands:
Color[0]=(Texture=(StorageMode=DevicePrivate,Type=Texture2D,Format=R8G8B8A8UNormInt,Size=(1080, 2274),MipCount=1,SampleCount=1,Compression=Lossless),LoadAction=Clear,StoreAction=Store,ClearColor=(R=1.0,G=1.0,B=1.0,A=1.0)),Stencil=(Texture=(StorageMode=DeviceTransient,Type=Texture2D,Format=R8G8B8A8UNormInt,Size=(1080, 2274),MipCount=1,SampleCount=1,Compression=Lossless),LoadAction=Clear,StoreAction=DontCare,ClearStencil=0)
```
