### ISSUE TITLE
[url_launcher] [file_selector] Could not open files on android

### ISSUE THREAD

**Issue by sabin26** [flutter/flutter#130066]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run the code sample
2. Pick a file [jpg, jpeg, png, pdf]

Device: Samsung Galaxy A52s 5G (Android 13)

### Expected results

The picked file should be launched properly.

### Actual results

[Video included] For pdf, the file opened and closed suddenly with a message: _Failed to download._ 
[Video included] For images, the file is not viewable.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:file_selector/file_selector.dart';
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher_string.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'App Demo',
      theme: ThemeData(useMaterial3: true),
      home: const MyHomePage(title: 'App Demo'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  MyHomePageState createState() => MyHomePageState();
}

class MyHomePageState extends State<MyHomePage> {
  void _selectAndOpenFile() async {
    // Set allowed file types
    final allowedTypes = ['jpg', 'jpeg', 'png', 'pdf'];

    // Select a file
    final file = await openFile(
        acceptedTypeGroups: [XTypeGroup(extensions: allowedTypes)]);

    if (file == null) {
      // User canceled the picker
      return;
    }

    // Get the file path
    final filePath = file.path;

    // Get the file uri
    //final uri = Uri.file(filePath);
    await launchUrlString(filePath);

    // Check if the file can be launched
    // if (await canLaunchUrl(uri)) {
    //   // Launch the file
    //   await launchUrlString(filePath);
    // } else {
    //   // Handle the error
    //   print('Could not launch $uri');
    // }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: const Center(
        child: Text('Press the button to select and open a PDF file'),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _selectAndOpenFile,
        tooltip: 'Select File',
        child: const Icon(Icons.attach_file),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/61322712/f7266187-c73d-471a-b277-63e500cf8b22

https://github.com/flutter/flutter/assets/61322712/0b16c487-ac7e-4d42-bc34-d40720c01127

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 3.12.0, on Microsoft Windows [Version 10.0.19045.3086], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.3)
[√] Android Studio (version 2022.2)
[√] VS Code (version 1.79.2)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment]
> ```dart
> await launchUrlString(filePath);
> ```

A file path is not a URL, so this is not a valid call to `url_launcher`. As the docs for `launchUrlString` say, you are responsible for validating the URL passed to it, and if it's not valid the behavior is not guaranteed.

Closing as the issue here is in the provided code, not the plugin.

**Comment by sabin26** [comment]
Hi @stuartmorgan ! As you may have seen the code sample, I passed the file path received directly from the `file_selector` plugin which is first party and **provided a valid path**. I have tested this on Windows & Web on Windows (Chrome & Edge) which worked flawlessly right out of the box. 

Given that android is a different platform and needs to be configured if necessary, I did apply the configurations mentioned in the `url_launcher` documentation which is adding `queries` to manifest for all the schemes to be used.

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="content" /> <!--  scheme that file_selector plugin provides the path in -->
        </intent>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="file" />
        </intent>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="http" />
        </intent>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="https" />
        </intent>
    </queries>
   ...
</manifest>
```

There is no mention of additional configurations as per the readme. So, I assume there is none. 

Aside from that, I am able to reproduce the same with a modified code sample and this time passing the `Uri` instead of just string path as you mentioned. Even after being parsed to a `Uri` (if not valid, it would have definitely thrown error) & being checked by `canLaunchUrl` (which returns `true`), I am still able to reproduce the same issue as shown in the _**video samples**_ (root thread).

### Updated Code Sample

```dart
import 'package:file_selector/file_selector.dart';
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'App Demo',
      theme: ThemeData(useMaterial3: true),
      home: const MyHomePage(title: 'App Demo'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  MyHomePageState createState() => MyHomePageState();
}

class MyHomePageState extends State<MyHomePage> {
  void _selectAndOpenFile() async {
    // Set allowed file types
    final allowedTypes = ['jpg', 'jpeg', 'png', 'pdf'];

    // Select a file
    final file = await openFile(
        acceptedTypeGroups: [XTypeGroup(extensions: allowedTypes)]);

    if (file == null) {
      // User canceled the picker
      return;
    }

    // Get the file path
    final filePath = file.path;
    print('log: path is: $filePath');

    // Get the file uri
    final uri = Uri.parse(filePath);
    print('log: uri is: $uri');

    // Check if the file can be launched
    if (await canLaunchUrl(uri)) {
      // Launch the file
      print('log: Launching uri');
      try {
        await launchUrl(uri, mode: LaunchMode.externalNonBrowserApplication);
      } on Exception catch (err) {
        print('log: $err');
      }
    } else {
      // Handle the error
      print('log: Could not launch $uri');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: const Center(
        child: Text('Press the button to select and open an Image or a PDF file'),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _selectAndOpenFile,
        tooltip: 'Select File',
        child: const Icon(Icons.attach_file),
      ),
    );
  }
}
```

After picking any file, the **application picker comes from the OS itself** to choose from & after selecting an application (eg: Gallery for images, Samsung Notes for pdf), it is unable to view them. I can't understand this situation. So, I really appreciate if you could point me to the right direction. Also, if something additional needed to be configured, it would be helpful if it was clearly stated on the readme. Thanks!

**Comment by stuartmorgan** [comment]
> ```
> <data android:scheme="content" /> 
> ```

I missed that you were attempting to directly pass a `content:` URI.

Android's security and permissions system doesn't allow every application to read every `content:` URI, so you are passing them a URI they don't have permission to access. My understanding is that passing `content:` URIs between applications on Android for a use case such as yours requires the [`FLAG_GRANT_READ_URI_PERMISSION`](https://developer.android.com/reference/android/content/Intent#FLAG_GRANT_READ_URI_PERMISSION) flag.

That is out of scope for `url_launcher`, which is not intended for use cases other than simply handing a URL off to the system for handling. If you want to create inter-application intents with specific behaviors, you need a plugin designed for that, such as [`android_intent_plus`](https://pub.dev/packages/android_intent_plus).

**Comment by sabin26** [comment]
Thank you so much! Using `android_intent_plus` plugin worked for me.

```dart
await AndroidIntent(
  action: 'action_view', // follow exact case i.e. no upper case else it will throw exception
  data: file.path, // Can pass any url: content/http/https etc.
  type: file.mimeType, // Mime is necessary for network urls (http,https) else it will open in the browser
  flags: [Flag.FLAG_GRANT_READ_URI_PERMISSION], // Read permission necessary for content url
).launch();
```

To anyone stumbling across this issue, don't forget to add `queries` for schemes in android manifest.
