### ISSUE TITLE
flutter/packages CI scripts need access to channel

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#130071]
The flutter/packages repository needs to test with both Flutter `master` and Flutter `stable`, and sometimes specific tests need to know which mode they are running under (e.g,. tests with golden files or that rely on auto-formatting need to be skipped on one of the two channels, because it's periodically impossible to pass on both).

With Cirrus, we put the channel into the environment, so scripts just check `Platform.environment['CHANNEL']`. Ideally we would have the LUCI recipe propagate the existing `channel` property from the CI config into the environment as `CHANNEL` so everything would keep working the same way, but I'm open to other options.

**Comment by keyonghan** [comment]
The channel is already a property: https://github.com/flutter/packages/blob/main/.ci.yaml#L122, this can be done by directly adding the `channel` to `env`.

**Comment by stuartmorgan** [comment]
@yusuf-goog Is this something you could take care of adding to the recipe?

**Comment by yusuf-goog** [comment]
Yes, I'll take care of it.

**Comment by yusuf-goog** [comment]
fix in https://flutter-review.googlesource.com/c/recipes/+/46900

**Comment by yusuf-goog** [comment]
@stuartmorgan please confirm the fix is working for you

**Comment by stuartmorgan** [comment]
It does indeed (https://github.com/flutter/packages/pull/4404), thanks for turning that around quickly!
