### ISSUE TITLE
Web: Flutter icons don't update on release

### ISSUE THREAD

**Issue by ollyde** [flutter/flutter#130000]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Related to 
https://github.com/flutter/flutter/issues/68704
https://github.com/flutter/flutter/issues/32540
https://github.com/flutter/flutter/issues/68704

```uses-material-design: true```

```
Icon(
          Icons.send_sharp,
          size: 22,
        ),

```
All were closed, it's hard to get a working example since it relates to pushing to a web server.

With ```flutter run -d chrome --release``` and dev mode it works fine.

But when building and releasing the app, new icons don't get added to the release version, extremely annoying.

`flutter build web --web-renderer canvaskit --release --dart-define=FLUTTER_WEB_USE_SKIA=true --dart-define=FLUTTER_WEB_USE_EXPERIMENTAL_CANVAS_TEXT=true --no-tree-shake-icons`

### Expected results

The material icons used in Flutter should work on web..

### Actual results

Icons don't show on web. All browsers.

### Code sample

Icon(
          Icons.send_sharp,
          size: 22,
        ),

### Screenshots or Video

NA

### Logs

NA

### Flutter Doctor output

<details>
<summary>flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.2, on macOS 13.4.1 22F82 darwin-arm64, locale en-NO)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Community Edition (version 2023.1.2)
[✓] VS Code (version 1.79.2)
[✓] Connected device (2 available)
[✓] Network resources
```
</details>

**Comment by danagbemava-nc** [comment]
Hi @ollyde, thanks for filing the issue. 

What server is your app hosted on? Do you see any errors in your network/console tab in a browser when the icons fail to load? 

Can you also remove these arguments from your build command to see if it makes any difference `--dart-define=FLUTTER_WEB_USE_SKIA=true --dart-define=FLUTTER_WEB_USE_EXPERIMENTAL_CANVAS_TEXT=true`?

Finally, can you try again on flutter 3.10.5 to see if you still face this issue?

Thank you

**Comment by ollyde** [comment]
@danagbemava-nc hosting on a K8 Nginx container (docker) is behind a Cloudflare proxy on strict mode.

Might be a provider caching issue I though, but using an alternative library such as font awesome I don't get the same issue on refresh. It seems as if the font packager is broken, when running in dev, then local release then release it works. But just compiling to release there are missing icons.

**Comment by danagbemava-nc** [comment]
Do you compile the application locally before deploying or is it compiled by some ci setup and then deployed? 

Also, do you notice any files failing to load when you open the hosted app?

**Comment by ollyde** [comment]
Indeed, the shell script below.

We don't have any caching on the K8.

```
# $NAMESPACE

kubectl config use-context admin@k8s-apple-main
kubectl config set-context admin@k8s-apple-main --namespace=$NAMESPACE

flutter clean 
flutter pub get
flutter build web --web-renderer canvaskit --release --dart-define=FLUTTER_WEB_USE_SKIA=true --dart-define=FLUTTER_WEB_USE_EXPERIMENTAL_CANVAS_TEXT=true --no-tree-shake-icons

# Build and tag (TODO Waiting AMD64 NodePools to be available)
docker build --platform linux/amd64 -t apple-web .
docker tag apple-web rg.nl-ams.scw.cloud/apple-container-service/apple-web

# Push Image Scaleway
docker push rg.nl-ams.scw.cloud/apple-container-service/apple-web

# Redeploy node api
kubectl patch deployment web-deployment -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
```

**Comment by danagbemava-nc** [comment]
I used the build command you shared to deploy a sample app to firebase hosting, [here](https://bundle-oasis.web.app). The icons work just fine. 

Would it be possible for you to check on the master channel to see if you still have this issue?

**Comment by danagbemava-nc** [comment]
Hi @ollyde, I tested on both and in both cases, it worked just fine. However, the master branch is always head of the stable branch so perhaps the tool might have been upgraded.

**Comment by ollyde** [comment]
I wouldn’t test on master since things are temporary there many times 😎

It might to do with other libraries as well

**Comment by danagbemava-nc** [comment]
That is a possibility. Can you share the full verbose output of the build command? Maybe there might be some hints in there. Could you also try with a smaller app through your deployment process to see if the bug still reproduces?

**Comment by danagbemava-nc** [comment]
Hi @ollyde, unfortunately, I'm not familiar with K8 so I'm not sure how to begin testing this.  

Were you able to test with a small project to see if the bug still reproduces through your deployment process?

**Comment by ollyde** [comment]
@danagbemava-nc doesn't really matter about K8. The issue is the icons are not backing packaged on compilation. I have noticed that when running in dev mode for Chrome then building for release they do package up.

**Comment by danagbemava-nc** [comment]
Hi @ollyde, as I stated in my comment [here](https://github.com/flutter/flutter/issues/130000#issuecomment-1624869381). I did build for release mode and do a deployment so it doesn't happen in all scenarios.

Your build & release process seems vastly different from what I tried, along with the sample I used which is why I asked that you try to pass the counter app through your build process to see if the bug also reproduces there so that we can determine if it is a general issue or maybe some packages/plugins in your main application are somehow not making the icons work. 

Are you by any chance using non const icons in your app? Can you also provide the full verbose output of the build command so that we can check to see if any files are missing? 

Thank you

**Comment by ollyde** [comment]
@danagbemava-nc our build is just using standard flutter build release here

```
flutter clean 
flutter pub get
flutter build web --web-renderer canvaskit --release --dart-define=FLUTTER_WEB_USE_SKIA=true --dart-define=FLUTTER_WEB_USE_EXPERIMENTAL_CANVAS_TEXT=true
```

We don't use const on the icons no, for multiple reasons; is that how the packaging selector works with icons, it matches "const Icons." ?

**Comment by danagbemava-nc** [comment]
My apologies, I actually wanted to know if you were using non-const `IconData` but I believe the --no-tree-shake-icons should take care of that. I was thinking of a different issue. 

Can you also provide the full verbose output of the build command so that we can check to see if any files are missing?

Can you also check your network tab to see if any files are not loaded when you open the page?

**Comment by ollyde** [comment]
> My apologies, I actually wanted to know if you were using non-const `IconData` but I believe the --no-tree-shake-icons should take care of that. I was thinking of a different issue.
> 
> Can you also provide the full verbose output of the build command so that we can check to see if any files are missing?
> 
> Can you also check your network tab to see if any files are not loaded when you open the page?

The build command won't show assets missing. I'm looking at the packed assets, and it looks like it's including all icons each release (1.3mb vector file) so something is broken :-P

**Comment by danagbemava-nc** [comment]
What is the size when you compile it locally on your machine?

**Comment by ollyde** [comment]
@danagbemava-nc I'm going to a festival with no phones allowed for 8 days now. So will post back probably in around 10-12 days 😂🙈

**Comment by danagbemava-nc** [comment]
Kindly update us when you get back. 

(Enjoy the festival)

**Comment by ollyde** [comment]
> What is the size when you compile it locally on your machine?

What are you asking here exactly, it seems as if the icons are same as the production size, 1.3mb

**Comment by danagbemava-nc** [comment]
I wanted to know if there was any difference between the icon size when it is built locally vs when it is built on production. Since it's the same, it doesn't seem like there's an issue with the build process. 

I'm not sure where the issue could be but since this has been reported previously with no clear resolution, I'll be labeling this for further insight from the team.

**Comment by yjbanov** [comment]
This looks like a tool issue. To summarize, starting from a clean project (e.g. after running `flutter clean`) build the project for web in release mode. The icon font file will be missing. A workaround is to build for debug mode first, then for release. Is that correct?

Forwarding to the tool team for now.

**Comment by christopherfujino** [comment]
@andrewkolos can you try to repro this?

**Comment by andrewkolos** [comment]
Similarly to earlier attempts in this thread, I failed to repro. Here are my steps (on master):

1. Create a new flutter project using `flutter create web_icon_test && cd web_icon_test`
2. Somewhere in your main Widget, add an `Icon` (e.g. `Icon(Icons.send_sharp, size: 22)`)
3. `flutter build web --web-renderer canvaskit --release --dart-define=FLUTTER_WEB_USE_SKIA=true --dart-define=FLUTTER_WEB_USE_EXPERIMENTAL_CANVAS_TEXT=true`
4. Serve the build output directory (e.g., for NPM users, `npx serve build/web`)
5. Navigate to the server in a browser.
6. Icon renders without issue.

I then experimented with adding another icon, and building/serving the app without using `flutter clean`. The icons still rendered without issue.

**Comment by christopherfujino** [comment]
> Similarly to earlier attempts in this thread, I failed to repro. Here are my steps (on master):
> 
> 1. Create a new flutter project using `flutter create web_icon_test && cd web_icon_test`
> 2. Somewhere in your main Widget, add an `Icon` (e.g. `Icon(Icons.send_sharp, size: 22)`)
> 3. `flutter build web --web-renderer canvaskit --release --dart-define=FLUTTER_WEB_USE_SKIA=true --dart-define=FLUTTER_WEB_USE_EXPERIMENTAL_CANVAS_TEXT=true`
> 4. Serve the build output directory (e.g., for NPM users, `npx serve build/web`)
> 5. Navigate to the server in a browser.
> 6. Icon renders without issue.
> 
> I then experimented with adding another `Icon`, and building/serving the app _without_ using `flutter clean`. The icons still rendered without issue.

@ollyde given this won't reproduce locally, I'm guessing the issue comes down to something in either your server infrastructure or CDN.

**Comment by ollyde** [comment]
@christopherfujino indeed I tried disabling cache on the CDN and a few other things, I'm not longer in the flutter space at the moment, working on cotforhire.com (cto facilitation service) so now in SvelteKit hell 😂

**Comment by christopherfujino** [comment]
> @christopherfujino indeed I tried disabling cache on the CDN and a few other things, I'm not longer in the flutter space at the moment, working on cotforhire.com (cto facilitation service) so now in SvelteKit hell 😂
> 
> I will close for now, if that's ok?

SGTM. Hopefully the next time you try Flutter for Web we'll have a better solution for cache busting :)
