### ISSUE TITLE
pop until specific route name flutter 

### ISSUE THREAD

**Issue by abdullah-te** [flutter/flutter#130067]
Navigator.of(context).popUntil(ModalRoute.withName(RouteNames.loginScreen));

======== Exception caught by widgets library =======================================================
The following assertion was thrown building Navigator-[GlobalObjectKey<NavigatorState> _WidgetsAppState#3640d](dirty, dependencies: [HeroControllerScope, UnmanagedRestorationScope, _FocusTraversalGroupMarker], state: NavigatorState#729ab(tickers: tracking 3 tickers)):
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 5242 pos 12: '!_debugLocked': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:

**Comment by danagbemava-nc** [comment]
Hi @abdullah-te,

Please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with steps to reproduce so that we can investigate this issue. 

Thank you
