### ISSUE TITLE
Undue breaking change in buildTransitions breaks dependencies

### ISSUE THREAD

**Issue by Andrflor** [flutter/flutter#130062]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Have any package that use buildTransations (like GetX for example)
Have flutter after aaaea51dd2237792cfb4e823feaf42234763a16d
flutter run

### Expected results

Should compile and run

### Actual results

Won't compile no more

### Problem source

The commit aaaea51dd2237792cfb4e823feaf42234763a16d introduced an unnecessary breaking change in the buildTransitions function signature. This breaking share will break any lib, (like here the very popular GetX) in all versions that use the function because of the unnecessary breaking change.

Could that added parameter be made optional so apps will compile again without having to modify all the packages that are using buildTransitions? 
[extact modification reference](https://github.com/flutter/flutter/pull/114303/files/f50b6e2fefadf4c8783b7aee01c0109c17adbe21#r1247119721)

### Logs

```
ERROR: ../../.pub-cache/git/getx-c826fa0539ceb8029dde54bd20b832374c6c4551/lib/get_navigation/src/routes/get_transition_mixin.dart:608:57: Error: Too few positional arguments: 6 required, 5 given.
ERROR:           return PageTransitionsTheme().buildTransitions(
ERROR:                                                         ^
ERROR: ../../.pub-cache/git/getx-c826fa0539ceb8029dde54bd20b832374c6c4551/lib/get_navigation/src/routes/get_transition_mixin.dart:644:57: Error: Too few positional arguments: 6 required, 5 given.
ERROR:           return PageTransitionsTheme().buildTransitions(
ERROR:                                                         ^
ERROR: Target kernel_snapshot failed: Exception
```

### Flutter Doctor output

NA

**Comment by nurbekm7** [comment]
Have the same issue now. Will rollback flutter version. hope it will help

**Comment by huycozy** [comment]
@Andrflor @nurbekm7 This looks like is a predicted change. But I don't have a minimal sample code to replicate this issue now, would you mind providing one? It will help to present the issue more visually for the situation you are facing to have a basis for further discussion.

**Comment by huycozy** [comment]
I take a look at this again and see it quite clearly with mentioned commit above. This could be a Backwards-incompatible API issue or documentation issue as discussed in the PR https://github.com/flutter/flutter/pull/114303. Labeling the issue for more information.

**Comment by zhcet19** [comment]
Rollbacking Flutter version helps in my case

**Comment by guyromb** [comment]
Which version to roll back to to fix this?

**Comment by HansMuller** [comment]
Reverting the change, sorry about the disruption: https://github.com/flutter/flutter/pull/130144

**Comment by HansMuller** [comment]
Making the platform parameter optional would still break subclassers. We could create a new one-off method, gradually migrate everyone to that and then deprecate the current method, but that would be a rather large undertaking. Not sure how to get through this change at the moment.

**Comment by ipcjs** [comment]
Ok, I create the #130158 to track the issue.🤔️
