### ISSUE TITLE
modal bottom sheet doesn't work anymore

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#1301]
modal bottom sheet doesn't work anymore

Just shows the overlay, not the sheet.
https://youtu.be/osem8PnkcD4

@HansMuller

**Comment by abarth** [comment]
This might be fixed.  /me tries.

**Comment by abarth** [comment]
Fixed at HEAD.

**Comment by HansMuller** [comment]
This is a duplicate of https://github.com/flutter/flutter/issues/1250
