### ISSUE TITLE
Migrate `onBenchmark` callback to `ui_web`

### ISSUE THREAD

**Issue by eyebrowsoffire** [flutter/flutter#130175]
The `onBenchmark` callback is communicated between framework and engine by stuffing it into a global JS variable called `_flutter_internal_on_benchmark`, similar to how `JSUrlStrategy` used to work. We should migrate this to an explicit API in `ui_web` to avoid headaches with JS interop stuff.

**Comment by Snowden1996** [comment]
The `onBenchmark` callback can be migrated to `ui_web` by following these steps:
1. Open the `ui_web` directory in your editor.
2. Create a new file called `benchmark.dart`.
3. Copy the following code into the file:

import 'package:flutter/foundation.dart';
/// A callback that is called when a benchmark is completed.
typedef BenchmarkCallback = void Function(
  String name,
  Duration duration,
);
/// Registers a callback to be called when a benchmark is completed.
void registerBenchmarkCallback(BenchmarkCallback callback) {
  _benchmarkCallback = callback;
}
/// The callback that is called when a benchmark is completed.
BenchmarkCallback _benchmarkCallback;
​

4. In your app, call the `registerBenchmarkCallback` method to register the callback.
5. In your benchmark, call the `benchmark` method to start the benchmark.
6. In your benchmark, call the `stop` method to stop the benchmark.
The `benchmark` method takes two arguments: the name of the benchmark and the duration of the benchmark. The `stop` method does not take any arguments.
When the benchmark is complete, the `onBenchmark` callback will be called with the name of the benchmark and the duration of the benchmark.
Here is an example of how to use the `onBenchmark` callback:

import 'package:flutter/foundation.dart';
import 'package:flutter/ui_web.dart';
void main() {
  // Register the callback.
  registerBenchmarkCallback((name, duration) {
    print('Benchmark $name completed in $duration.');
  });
  // Start the benchmark.
  benchmark('My Benchmark', Duration(seconds: 1));
  // Stop the benchmark.
  stop();
}
​

I hope this helps!
