### ISSUE TITLE
Performance overlay is not working

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#13018]
## Steps to Reproduce

On master -
1. flutter run any app (flutter_gallery repro the issue for me)
2. hit 'P'

The app just freezes.

## Logs
$ flutter run
Building flutter tool...
Downloading package sky_engine...
Downloading common tools...
Downloading linux-x64 tools...
Downloading linux-x64 tools...
Downloading android-arm-profile/linux-x64 tools...
Downloading android-arm-release/linux-x64 tools...
Downloading android-x86 tools...
Downloading android-x64 tools...
Downloading android-arm tools...
Downloading android-arm-profile tools...
Downloading android-arm-release tools...
Running "flutter packages get" in flutter_gallery...
Launching lib/main.dart on Pixel in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Built build/app/outputs/apk/app-debug.apk (28.3MB).
Installing build/app/outputs/apk/app.apk...
I/FlutterActivityDelegate( 6423): onResume setting current activity to this
Syncing files to device Pixel...

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on Pixel is available at: http://127.0.0.1:8104/
For a more detailed help message, press "h". To quit, press "q".

D/skia    ( 6423): OpList failed to instantiate.
I/chatty  ( 6423): uid=10142(io.flutter.examples.gallery) gpu_thread identical 85 lines
D/skia    ( 6423): OpList failed to instantiate.
D/skia    ( 6423): OpList failed to instantiate.
I/chatty  ( 6423): uid=10142(io.flutter.examples.gallery) gpu_thread identical 2 lines
D/skia    ( 6423): OpList failed to instantiate.
D/skia    ( 6423): OpList failed to instantiate.
D/skia    ( 6423): OpList failed to instantiate.
D/skia    ( 6423): OpList failed to instantiate.

## Flutter Doctor

$ flutter doctor
[✓] Flutter (on Linux, locale en_US.UTF-8, channel master)
    • Flutter at /usr/local/google/home/amirha/git/flutter
    • Framework revision efe2892081 (4 minutes ago), 2017-11-14 10:53:39 -0800
    • Engine revision 242ce44af5
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /usr/local/google/home/amirha/Android/Sdk
    • Platform android-26, build-tools 26.0.2
    • Java binary at: /usr/local/google/home/amirha/progs/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio-with-blaze-2.3
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /usr/local/google/home/amirha/progs/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 18.0
    • Dart plugin version 172.4155.35

[✓] Connected devices
    • Pixel • FA6890301419 • android-arm • Android 8.1.0 (API 27)

**Comment by amirh** [comment]
@chinmaygarde

**Comment by jason-simmons** [comment]
This was introduced in https://github.com/flutter/engine/commit/0a7155d4e1e254c2642d2c273cc1f484be3845b9

Stopwatch::Visualize() in flutter/flow/instrumentation.cc is unable to draw the graph path using the new surface/canvas configuration

@brianosman
