### ISSUE TITLE
JVM crash running flutter/packages Android unit tests

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#130148]
In trying to migrate Android unit tests from Cirrus to LUCI, I'm getting a persistent failure:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ff08d62f299, pid=227753, tid=227850
#
# JRE version: OpenJDK Runtime Environment (11.0+28) (build 11+28)
# Java VM: OpenJDK 64-Bit Server VM (11+28, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0xcec299]  ResolvedMethodTable::add_method(Handle)+0x49
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /b/s/w/ir/x/w/packages/packages/camera/camera_android/android/hs_err_pid227753.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
```

(example run: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8776224627502626177/+/u/Run_package_tests/native_unit_tests/stdout)

It looks like this may be a bug with a specific version of OpenJDK 11: https://bugs.openjdk.org/browse/JDK-8210457. What's the exact version of 11 that we are using? Can we get at newer 11?

**Comment by stuartmorgan** [comment]
FYI @yusuf-goog, this is another migration blocker.

**Comment by yusuf-goog** [comment]
According to https://bugs.openjdk.org/browse/JDK-8210457 it looks like the fix is in v13, and backported to:

12.0.2
11.0.5-oracle
11.0.4

The current version 11 package in cipd doesn't provide a minor version number, just 11, so I can't tell right now. Let me update to the newest version:11 package.

**Comment by yusuf-goog** [comment]
@stuartmorgan I created openjdk 12.0.2 cipd packages for linux, and they are tagged as `version:12`. Please try these out and let me know.

**Comment by stuartmorgan** [comment]
It looks like it fixes the crash, but creates a bunch of unit test failures: https://github.com/flutter/packages/pull/4406

I'll need to investigate more next week to see if we just need to adjust things in our tests (I'm pretty sure at least one failure falls into that bucket), or if it's a more significant problems.

**Comment by yusuf-goog** [comment]
@stuartmorgan looks like the java 12 package is deployed and your tracking the unit test failures in the other tracker, so closing this bug. Please reopen if you need a change to the java package.
