### ISSUE TITLE
Request: Add support for Desktop platforms (macOS, Windows, Linux) for video_player plugin

### ISSUE THREAD

**Issue by RoleWong** [flutter/flutter#130127]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

It would be extremely helpful if support for Desktop platforms (macOS, Windows, Linux) could be added to the video_player plugin. This way, developers can deliver a seamless video playback experience to users across various platforms.

I have tried some other solutions, including:
- Using WebView and HTML video player, which is a viable solution for the web but may not be ideal for the desktop environment.
- Creating separate native code for each platform, which increases the development time and complexity.
- Using `media_kit ` but it has version confiction with `package_info_plus`.

While these alternatives can work, having official support for Desktop platforms directly in this plugin would be far more convenient and better for the developer community.

### Proposal

As a developer who focuses on cross-platform application development, I noticed that there is currently no support for Desktop platforms in the video_player plugin. With the growing popularity of Flutter as a solution for multiple platforms, support for desktop platforms like macOS, Windows, and Linux would be a valuable addition to this `video_player`.

Thanks a lot!

**Comment by danagbemava-nc** [comment]
Hi @RoleWong, see the following issues for proposals for support on the individual desktop platforms. 

https://github.com/flutter/flutter/issues/41688
https://github.com/flutter/flutter/issues/37673
https://github.com/flutter/flutter/issues/39091

Closing from here as duplicate. 

Thank you
