### ISSUE TITLE
ScrollNotification.metrics.axisDirection should be AxisDirection.up when scroll up

### ISSUE THREAD

**Issue by pedia** [flutter/flutter#13010]
## Steps to Reproduce

1 Create ListView and listen ScrollNotification
```
class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: new NotificationListener(
          onNotification: (ScrollNotification notify) {
            print("scroll direction: ${notify.metrics.axisDirection}");
          },
          child: new ListView.builder(
            itemCount: 20,
            itemBuilder: (BuildContext context, int index) {
              return new ListTile(title: new Text("Item $index"));
            },
          )),
    );
  }
}
```

2 Scroll up ListView, ScrollNotification.metrics.axisDirection always is AxisDirection.down, should be AxisDirection.up.

## Logs
> flutter run
scroll direction: AxisDirection.down
scroll direction: AxisDirection.down
...
scroll direction: AxisDirection.down

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.12.6 16G1036, locale en-HK, channel master)
    • Flutter at /Users/odd/wa/flutter/flutter
    • Framework revision 62ed4f5911 (7 hours ago), 2017-11-13 17:06:11 -0800
    • Engine revision 11d68f63da
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /Users/odd/Library/Android/sdk
    • Platform android-26, build-tools 26.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.1, Build version 9B55
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Connected devices
    • ONEPLUS A5000 • bd636bb3                             • android-arm • Android 7.1.1 (API 25)
    • iPhone X      • 2B869FE0-C8D2-4755-9C69-D0F91CED8588 • ios         • iOS 11.1 (simulator)

**Comment by Hixie** [comment]
This is actually as intended, though the documentation definitely needs clarifying.

The ScrollMetrics.axisDirection is the direction in which positive scroll offsets increase in the viewport. The ScrollNotification.scrollMetrics is the description of the viewport's metrics (not the scroll notification's state). There's no way to tell from a ScrollNotification how much the viewport has scrolled by or in what direction, currrently.

**Comment by pedia** [comment]
@Hixie 
I changed material/refresh_indicator.dart add pull up load more feature.
Does Flutter need it?

```dart
new TwoDirectionIndicator(
        displacement: 40.0,
        onLoadMore: () {},
        onRefresh: () {},
        ...
```

**Comment by Hixie** [comment]
That sounds great! I would recommend publish it as a package first, if it's self-contained. Then, if it's popular, it would make sense to add to the framework. I'm reluctant to add it straight to the framework because it's not something that [the specification describes](https://material.io/guidelines/patterns/swipe-to-refresh.html).

**Comment by sparksisnotspark** [comment]
@pedia I need the pull up load more feature. I have no idea to do this.  How to do this?

**Comment by pedia** [comment]
@sparksisnotspark I pub a simple solution: https://pub.dartlang.org/packages/pdrpulm

**Comment by tomasbaran** [comment]
This issue has been closed and I have no idea why. @Hixie, you mentioned it was intended to show:

-  `AxisDirection.down`: when scrolling DOWN
-  `AxisDirection.down`: also when scrolling UP

I'm sorry but it doesn't make any sense. I'm not great at reading documentations but if I read it well, shouldn't it give us `AxisDirection.down` when scrolling UP according to the docs: https://api.flutter.dev/flutter/painting/AxisDirection-class.html? 

Can someone please reopen the issue? I don't know how to do it...

**Comment by tomasbaran** [comment]
I'm not familiar with the technical challenges here, @Hixie is the guy for that but for me, Flutter beginner, it looks like a find a lot worse but functional a workaround: https://stackoverflow.com/questions/57440701/handle-scroll-direction-in-flutter 

It looks so much more complicated vs. how it could/should work if `AxisDirection.up` worked. Now I basically had to mess up my code convert stateless widget -> stateful and add listeners and setStates and other things... :( It's a bummer it's not working as simple as adding one line of code as it sounds like it should.

**Comment by Hixie** [comment]
Not sure why this was closed; documentation still needs updating.

@tomasbaran I recommend filing a separate bug if you have a specific concern outside of just updating the documentation.

**Comment by Iccr** [comment]
is there any updates for it. As for me its ScrollNotification scrollInfo always gives down still.

**Comment by mucahitbircan** [comment]
it gives always right when Axis.horizontal

**Comment by kuemme01** [comment]
Still a problem :o(

**Comment by UlyssesAlves** [comment]
As @Hixie said,

> The ScrollMetrics.axisDirection is the direction in which positive scroll offsets increase in the viewport.
> There's no way to tell from a ScrollNotification how much the viewport has scrolled by or in what direction, currrently.

One possible workaround, which I have validated and looks like to be working good for my needs, is to create two local variables in your state object, one to store the starting offset and other to store the ending offset of the scrolling animation, like so:

`` double _startOffset = 0.0, _endOffset = 0.0;

To get these values, you'll need a ScrollController attached to your ListView, and you need of course to instantiate this controller, like in initState() method, for example.

```
// Declare this in your state object scope.
`` ScrollController _scrollController;

// Instantiate the controller in initState(), or maybe on the same line where you declare it (but you'll need to test it to verify if it also works).
`` _scrollController = ScrollController();
```

Now, to get scroll notifications, wrap your ListView inside a NotificationListener, fill the _startOffset and _endOffset with the intened values when scroll notifications fire, and then compare the two variables with one another. If _endOffset is greater than _startOffset, it means the scrolling was from left to right in case of an horizontal scroller (or from up to bottom with vertical scrollers), and if _endOffset is less than _startOffset, it means the scrolling took place from right to left (or from bottom to top).

```
NotificationListener<ScrollNotification>(
                onNotification: (scrollNotification) {
                  if (scrollNotification is ScrollStartNotification) {
                    print('Start offset: ${_scrollController.offset}');
                    _startOffset = _scrollController.offset;
                  }

                  if (scrollNotification is ScrollEndNotification) {
                    print('End offset: ${_scrollController.offset}');
                    _endOffset = _scrollController.offset;

                    if (_endOffset > _startOffset) {
                      print('Scrolling from the left to the right.');
                    } else if (_endOffset < _startOffset) {
                      print('Scrolling from the right to the left.');
                    }
                  }

                  return true;
                },
                child: ListView(
                  scrollDirection: Axis.horizontal,
                  controller: _scrollController,
```
