### ISSUE TITLE
Improve confusing process around cherry-picking patches into stable/beta

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#130152]
I filed a CP request into stable (3.10) today. I will also be requesting to CP it into beta next week (3.13). I'm waiting until next week because if I file a request into 3.12, that will no longer be the beta next week and users tracking beta may not even see it. But this results in confusion for me as an engineer and for users: if the fix gets approved for 3.10 and 3.13, that means users who moved to beta on 3.11 or 3.12 won't have it (but if they stayed on 3.10 they would or if they used 3.13 they would). This seems to go against encouraging more users to proactively use beta.

Right now, if I filed the CP request on 3.12 and no human though to tell me that 3.13 is being cut next week (or I just missed the message), it would be entirely possible that users who are staying up to date with beta will never get that fix (by the time they upgrade their beta cut they're already on 3.13 next week). It seems very likely to me that if I filed a CP on 3.12 it could get approved and merged and lost in the void.

It would be better if the template encouraged me to pick a _minimum version_ to pick into (with the last stable as the floor, i.e. 3.10). It would then direct me to file merge PRs for all betas since then (so 3.11, 3.12). Additionally, something in the release process would include a check about whether the newly cut beta includes all CPs from the previous beta (so my commit from last night in the engine that will miss the cut for 3.13 would get flagged as having been CPed into 3.12). I'm fine if that process involves reaching out to me again to open a PR on 3.13, but I want to make sure it doesn't fall through the cracks.

/cc @itsjustkevin @zanderso

**Comment by dnfield** [comment]
https://github.com/flutter/flutter/issues/130149 is the 3.10 CP I am referring to.

**Comment by itsjustkevin** [comment]
Thank you for the feedback here @dnfield.  

Your points are extremely valid.  As you point out, there could be situations where a cherry-pick to beta late in the cycle could lead to that same fix not being applied to the next beta cut.

In an ideal world, all cherry-picks from a previous beta would always be present in the newest beta, but that is not the case.  The only check we have in place for this situation is a human check which is prone to failure. 

@CaseyHillers this seems like something that would be implemented at the roll tooling level.  Any ideas?

**Comment by XilaiZhang** [comment]
From triage: cherry pick process has been updated and improved.
