### ISSUE TITLE
Issue during the "Using FFI in a Flutter plugin"  google codelab

### ISSUE THREAD

**Issue by mjm1158** [flutter/flutter#130103]
I was fallowing the steps in the "Using FFI in a Flutter plugin" Code lab and at that end of Step 5 when we finally perform:

$ cd example
$ flutter run

I received the error:

CUSTOMBUILD : error : Couldn't resolve the package 'ffi' in 'package:ffi/ffi.dart'. [D:\Users\<me>\FlutterTutori
alProjects\ffigen_app\example\build\windows\flutter\flutter_assemble.vcxproj]
ojects\ffigen_app\example\build\windows\flutter\flutter_assemble.vcxproj]
../lib/ffigen_app.dart(42,9): error GC9768DF9: Undefined name 'malloc'. [D:\Users\<me>\FlutterTutorialProjects\f
figen_app\example\build\windows\flutter\flutter_assemble.vcxproj]
../lib/ffigen_app.dart(31,29): error GE5CFE876: The method 'toNativeUtf8' isn't defined for the class 'String'. 
[D:\Users\<me>\FlutterTutorialProjects\ffigen_app\example\build\windows\flutter\flutter_assemble.vcxproj]       
D:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(24
8,5): error MSB8066: Custom build for 'D:\Users\<me>\FlutterTutorialProjects\ffigen_app\example\build\windows\CM
akeFiles\efd172ba2c5d7bcddb1dd36bad3a64b6\flutter_windows.dll.rule;D:\Users\Matt\FlutterTutorialProjects\ffigen_
app\example\build\windows\CMakeFiles\02491e7eeab2873862a02128e357b7db\flutter_assemble.rule' exited with code 1.
 [D:\Users\<me>\FlutterTutorialProjects\ffigen_app\example\build\windows\flutter\flutter_assemble.vcxproj]

After a lot of experimenting and comparing with the files in the git-clone Codelab source, I got the project to compile. My solution was to change 

dev_dependencies:
  ffigen: ^8.0.2

in my project to 

dev_dependencies:
  ffigen: ^8.0.0

as seen in Codelab's step 5 files. 

Before doing this I look for differences between my source and the Codelab's source. I did observe a difference in the " duktap_bindings_generated.dart " file. Specifically, on line 5270, my version says:

typedef va_list = ffi.Pointer<ffi.Char>;

But the codelab's version is:

typedef va_list = __builtin_va_list;
typedef __builtin_va_list = ffi.Pointer<ffi.Char>;

This doesn't seem like a huge difference to me but because of this difference and the fact that I was rolling back the ffigen version slightly I re ran the command..

flutter pub run ffigen --config ffigen.yaml 

... though I actually typed ...

dart run ffigen --config ffigen.yaml

... because the "flutter pub" versions says "Depracted. Use 'dart run' instead." 

The difference is still there after the rollback and the re run of ffigen but the project compiles now like its supposed to at the end of step 5. So I'm stumped as to why  changing ffigen back to 8.0.0 from 8.0.2 would make a difference but it does and so I'm sharing my experience in case it helps anyone.

**Comment by dcharkes** [comment]
> I was fallowing the steps in the "Using FFI in a Flutter plugin" Code lab and at that end of Step 5 when we finally perform:
> 
> $ cd example $ flutter run
> 
> I received the error:
> 
> CUSTOMBUILD : error : Couldn't resolve the package 'ffi' in 'package:ffi/ffi.dart'. 

That is weird, it almost looks like `flutter pub get` failed.

All the subsequent failures are because `package:ffi` was not resolved.

The weird thing is that `flutter run` should automatically run `flutter pub get`.

> [D:\Users<me>\FlutterTutori alProjects\ffigen_app\example\build\windows\flutter\flutter_assemble.vcxproj] ojects\ffigen_app\example\build\windows\flutter\flutter_assemble.vcxproj] ../lib/ffigen_app.dart(42,9): error GC9768DF9: Undefined name 'malloc'. [D:\Users<me>\FlutterTutorialProjects\f figen_app\example\build\windows\flutter\flutter_assemble.vcxproj] ../lib/ffigen_app.dart(31,29): error GE5CFE876: The method 'toNativeUtf8' isn't defined for the class 'String'. [D:\Users<me>\FlutterTutorialProjects\ffigen_app\example\build\windows\flutter\flutter_assemble.vcxproj] D:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(24 8,5): error MSB8066: Custom build for 'D:\Users<me>\FlutterTutorialProjects\ffigen_app\example\build\windows\CM akeFiles\efd172ba2c5d7bcddb1dd36bad3a64b6\flutter_windows.dll.rule;D:\Users\Matt\FlutterTutorialProjects\ffigen_ app\example\build\windows\CMakeFiles\02491e7eeab2873862a02128e357b7db\flutter_assemble.rule' exited with code 1. [D:\Users<me>\FlutterTutorialProjects\ffigen_app\example\build\windows\flutter\flutter_assemble.vcxproj]
> 
> After a lot of experimenting and comparing with the files in the git-clone Codelab source, I got the project to compile. My solution was to change
> 
> dev_dependencies: ffigen: ^8.0.2
> 
> in my project to
> 
> dev_dependencies: ffigen: ^8.0.0
> 
> as seen in Codelab's step 5 files.

This caused `flutter pub get` to run again because dependencies changed.

> Before doing this I look for differences between my source and the Codelab's source. I did observe a difference in the " duktap_bindings_generated.dart " file. Specifically, on line 5270, my version says:
> 
> typedef va_list = ffi.Pointer<ffi.Char>;
> 
> But the codelab's version is:
> 
> typedef va_list = __builtin_va_list; typedef __builtin_va_list = ffi.Pointer<ffi.Char>;

That should be fine, an extra indirection but still the same type.
(Most likely because you run the tutorial on a different OS, or the compiler on your system has a different version of the header files.)

> This doesn't seem like a huge difference to me but because of this difference and the fact that I was rolling back the ffigen version slightly I re ran the command..
> 
> flutter pub run ffigen --config ffigen.yaml
> 
> ... though I actually typed ...
> 
> dart run ffigen --config ffigen.yaml
> 
> ... because the "flutter pub" versions says "Deprecated. Use 'dart run' instead."

@domesticmouse the code lab should be updated.

> The difference is still there after the rollback and the re run of ffigen but the project compiles now like its supposed to at the end of step 5. So I'm stumped as to why changing ffigen back to 8.0.0 from 8.0.2 would make a difference but it does and so I'm sharing my experience in case it helps anyone.

Does it fail again if you roll forward to 8.0.2 again?

**Comment by mjm1158** [comment]
I don't know... let's check

Eee gadz this is bizarre.I tried changing the dependency back to 8.0.2 and
it throws no error when compiling now.

Since I made it to the end of the Codelab I'm working with the code at the
end of Step 7 now. There is a part in Step 6 or Step 7 where we use a
different plug-in to build some files, don't know if that would have an
effect.

I honestly have no idea why it was giving me so much trouble. And now it's
happy so that's just weird.

**Comment by dcharkes** [comment]
> I had this similar problem but I fixed it by moving
> 
> ```
>   ffi: ^2.0.2
> ```
> 
> from `dev_dependencies` to `dependencies`.
> 
> I'm not proficient in Flutter, but the new code in `ffigen_app.dart` used it directly as `import 'package:ffi/ffi.dart' as ffi;`, so I guess it needed it as a non-dev dependencies.

cc @domesticmouse

**Comment by domesticmouse** [comment]
Googlers: Fix is in cl/549469143

**Comment by domesticmouse** [comment]
Fix has been landed. This should be all good now.
