### ISSUE TITLE
WebP animations are corrupted

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#13017]
Some WebP animations are not playing well, e.g see screen recording:

![corrupted-webp-animation](https://user-images.githubusercontent.com/1024117/32797358-610d28cc-c926-11e7-86af-21fa5ec12fc9.gif)

Which is what we get when playing this sample animation:
![sample-webp-animation](https://mathiasbynens.be/demo/animated-webp-supported.webp)

This is potentially a Skia issue, as I observe the same issue when using the Skia sample animatedGif app with this file.

**Comment by amirh** [comment]
@leonscroggins

**Comment by amirh** [comment]
Fixed in https://skia-review.googlesource.com/c/skia/+/71560

Keeping this open until we roll Skia

**Comment by amirh** [comment]
This has resurfaced with the last skia roll, looks like the Skia fix was rolled back https://skia.googlesource.com/skia/+/2009c20309a2a91d1fb9020385b56eeae06a1fb1

**Comment by LeonScroggins** [comment]
Yeah, sorry about that. Re-fixing with https://skia-review.googlesource.com/c/skia/+/72281, which I'm submitting now
