### ISSUE TITLE
[Impeller] Vulkan textures can be destroyed on raster thread, delaying workload.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#130157]
The glyph atlas hold onto a shared ptr to the glyph atlas texture. This might still be holding the texture after the fence waiter returns. If a new texture is created, this could force the destruction of this texture on the raster thread which may delay other workloads:

![image](https://github.com/flutter/flutter/assets/8975114/44bebfbd-bc91-411d-a786-32a1f8194b7c)

**Comment by jonahwilliams** [comment]
This is actually a more general issue. I don't think the current fencewaiter design guarantees that the fence waiter is the one to destruct the texture. Here is a slow frame from CI, not the glyph atlas though:

![image](https://github.com/flutter/flutter/assets/8975114/58dc67b2-79ff-4af6-a797-8be49cb1a66f)

because in theory the fence can get signaled before the frame is done and then the entity pass or whatever would be the last reference

**Comment by jonahwilliams** [comment]
I researched a bit how this is done elsewhere, specifically Dawn seems to invert what we do. Rather than trying to give ownership of the buffer to the fencewaiter, they give the buffer a reference to the fence. When the buffer wrapper is destructed it gets moved onto a new thread to release the native resource along with the fence

**Comment by chinmaygarde** [comment]
Fixed in https://github.com/flutter/engine/pull/43579
