### ISSUE TITLE
[Impeller] Check viability of Pixel 6 for device lab and local testing.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#130104]
From the weekly sync. We are going to attempt to get these devices in the lab. @zanderso was going to reach out to the infra team to get these in the lab but @jonahwilliams wanted to make sure any device we added had the extensions we might realistically need.

We settled on Pixel 6.

I couldn't find Pixel 6 on go/impeller-android-devices but a [verified Pixel 6a reports this](https://vulkan.gpuinfo.org/displayreport.php?id=16031). An [**unverified** Pixel 6 reports this](https://vulkan.gpuinfo.org/displayreport.php?id=17843).

@jonahwilliams mentioned [VK_ANDROID_external_memory_android_hardware_buffer](https://vulkan.gpuinfo.org/listdevicescoverage.php?extension=VK_ANDROID_external_memory_android_hardware_buffer) which both seem to support. Not sure he was looking for anything else.

**Comment by jonahwilliams** [comment]
That is everything! If so this is good then

**Comment by chinmaygarde** [comment]
Cool. @zanderso should be unblocked from reaching out to the infra folks then. I suspect it will take a while with the move and all.
