### ISSUE TITLE
SnackBar can not get automatically disappear when action is set

### ISSUE THREAD

**Issue by Foldblade** [flutter/flutter#130196]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Maybe related with #126756. I'm using Channel beta, 3.12.0-1.1.pre, upgrade my old Flutter projects from Flutter 2 to 3, also upgrade to Material Design 3. I found that `SnackBar` can not get automatically disappear when action is set.

My use case is, use `SnackBar` with action button to "Undo" the deletion operation. If the user does not click the action button, the snackbar will automatically disappear and the deletion operation is done. This works well in my old version's APP, but it don't work when I upgrading my APP these days.

I'm not sure is this a new feature or bug. Please give me some advice, thank you!

### Expected results

With my code sample, the SnackBar can disappear after 1 seconds. Or, without setting `duration`, automatically disappear after 4 seconds according to the default value.

![图片](https://github.com/flutter/flutter/assets/25426917/a40e7e3c-1eba-4c27-a7b7-cec0f9f9c579)

### Actual results

Even if I set `duration: const Duration(seconds: 1)`, the SnakBar can not automatically disappear. Please see the video below.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<String> alphabet = ['A', 'B', 'C', 'D', 'E'];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          backgroundColor: Theme.of(context).colorScheme.inversePrimary,
          title: Text(widget.title),
        ),
        body: Column(
          children: [
            const Text("Slide to delete"),
            Scrollbar(
              child: ListView.builder(
                  shrinkWrap: true,
                  itemCount: alphabet.length,
                  itemBuilder: (BuildContext context, int index) {
                    return Dismissible(
                      background:
                          Container(color: Theme.of(context).colorScheme.error),
                      key: UniqueKey(),
                      child: ListTile(
                        title: Text(alphabet[index]),
                      ),
                      onDismissed: (DismissDirection direction) {
                        final deletedElement = alphabet[index];
                        ScaffoldMessenger.of(context).showSnackBar(
                          SnackBar(
                            content:
                                Text("${alphabet[index]} had been removed."),
                            duration: const Duration(seconds: 1),
                            action: SnackBarAction(
                                label: "Undo",
                                onPressed: () {
                                  setState(() {
                                    alphabet.insert(index, deletedElement);
                                  });
                                }),
                            behavior: SnackBarBehavior.floating,
                          ),
                        );
                        setState(() {
                          alphabet.removeAt(index);
                        });
                      },
                    );
                  }),
            ),
          ],
        ));
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/25426917/e86a6bfc-49e4-4d28-bc93-73b936ae520a

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel beta, 3.12.0-1.1.pre, on Microsoft Windows [10.0.19045.3086])
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop Windows apps (Visual Studio Community 2019 16.11.27)
[✓] Android Studio (version 2021.1)
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
[✓] VS Code (version 1.80.0)
[✓] Proxy Configuration
[✓] Connected device (4 available)
[✓] Network resources
```

</details>

**Comment by Foldblade** [comment]
Oh, I noticed these in [SnackBar's document](https://api.flutter.dev/flutter/material/SnackBar-class.html):

> A SnackBar with an action will not time out when TalkBack or VoiceOver are enabled. This is controlled by [AccessibilityFeatures.accessibleNavigation](https://api.flutter.dev/flutter/dart-ui/AccessibilityFeatures/accessibleNavigation.html).

Although the TalkBack's switch status is off in my System's setting, but I found that I have some third-party Apps using Accessibility Features, like LITIAOTIAO (李跳跳 hello.litiaotiao.app) and MyGesture (me.hisn.mygesture). Turned them off, and the Snackbar works as expected.

But if I keep these third-party Apps which use Accessibility Features on, is there any way to set a longer time out duration instead of "not time out"? Sorry for my mistake, this issue seems like a new Feature request now😢

**Comment by dam-ease** [comment]
Hi @Foldblade. Thanks for filing this issue. As you rightly said, from the documentation,

> A SnackBar with an action will not time out when TalkBack or VoiceOver are enabled. This is controlled by [AccessibilityFeatures.accessibleNavigation](https://api.flutter.dev/flutter/dart-ui/AccessibilityFeatures/accessibleNavigation.html).

So this isn't an issue with flutter but you might file a different proposal/feature request to handle your use case. Kindly let me know when you do, so I can close this.
Thank you
