### ISSUE TITLE
PageView Swipe Functionality Lost After Upgrading to Flutter 3.10 with SelectableText.rich

### ISSUE THREAD

**Issue by burhanaksendir** [flutter/flutter#130198]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Ensure that you have Flutter version 3.10 installed.
2. Create a new Flutter project and replace the existing code in the main.dart file with the provided code.
3. Run the Flutter application on a device or emulator.
4. Observe that the app launches with a SelectableText widget inside a PageView.builder widget.
5. Attempt to swipe left or right on the PageView to switch between pages.
6. Notice that the swipe functionality is not working as expected and the pages are not changing.

### Expected results

When running the Flutter application, the PageView.builder should display multiple pages containing the SelectableText.rich widget. The PageView should retain its swipe functionality, allowing the user to swipe left or right to navigate between the pages. The SelectableText widget should also function as intended, allowing the user to select and copy text within the widget.

### Actual results

After upgrading to Flutter version 3.10 and running the application, the PageView.builder displays multiple pages with the SelectableText.rich widget. However, the swipe functionality of the PageView is disabled. It is not possible to swipe left or right to navigate between the pages. The expected swipe behavior is lost, making it difficult to switch between pages within the PageView.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

const String sampleText = '''
Alice was beginning to get very tired of sitting by her sister on the bank, and of having nothing to do: once or twice she had peeped into the book her sister was reading, but it had no pictures or conversations in it, “and what is the use of a book,” thought Alice “without pictures or conversations?”
So she was considering in her own mind (as well as she could, for the hot day made her feel very sleepy and stupid), whether the pleasure of making a daisy-chain would be worth the trouble of getting up and picking the daisies, when suddenly a White Rabbit with pink eyes ran close by her.
''';

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('SelectableText Sample'),
        ),
        body: PageView.builder(
          itemCount: 3,
          itemBuilder: (BuildContext context, int index) {
            return MyPage(index: index);
          },
        ),
      ),
    );
  }
}

class MyPage extends StatelessWidget {
  final int index;

  const MyPage({super.key, required this.index});

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(16.0),
      child: const Center(
        child: SelectableText.rich(
          TextSpan(
            text: sampleText,
            style: TextStyle(fontSize: 20.0),
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F82 darwin-arm64, locale tr-TR)
    • Flutter version 3.10.5 on channel stable at /Volumes/Media/Development/Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (4 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1
```

</details>

**Comment by huycozy** [comment]
Hi @burhanaksendir 
Which platform are you seeing the issue? I check this on Android, it works as expected as below demo. Verified the issue on the latest stable 3.10.5.

<details>
<summary>Demo</summary>

https://github.com/flutter/flutter/assets/104349824/f62d76d2-f88e-4b44-bbd3-8d1830f5f139
</details>

**Comment by burhanaksendir** [comment]
Hi @huycozy 
Thank you for pointing that out. I forgot to mention.
The issue I'm referring to is occurring on iOS. I tested it with iOS 16.5.1 on both a real device and a simulator.

```
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F82 darwin-arm64, locale tr-TR)
    • Flutter version 3.10.5 on channel stable at /Volumes/Media/Development/Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (4 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1
    
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1
```

**Comment by huycozy** [comment]
Thanks for your update. I can see the issue on iOS now, pages can not be swiped. Reproduced the issue on the latest stable and master channel. Could you please share the last version you see it working on? (this will help shorten the scope of regression investigation)

**Comment by huycozy** [comment]
Thanks for your update. I can see the issue on iOS now, pages can not be swiped if the gesture is inside SelectableText. If I swipe pages outside SelectableText area (bottom or top), the PageView gesture does work again.

Reproduced the issue on the latest stable and master channel. Could you please share the last version you see it working on? (this will help shorten the scope of regression investigation)

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.10.5 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (3 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D                         • android-arm64  • Android 11 (API 30)
    • iPhone (mobile)  • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.7.2 19H218
    • macOS (desktop)  • macos                                    • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome                                   • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.12.0-15.0.pre.80, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.12.0-15.0.pre.80 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3163306d88 (4 minutes ago), 2023-07-10 23:09:08 -0400
    • Engine revision 95316fbc25
    • Dart version 3.1.0 (build 3.1.0-292.0.dev)
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by burhanaksendir** [comment]
It was working smoothly with Flutter 3.7.12. I also downgraded Flutter back to 3.7.12. Below is the output of 'flutter doctor' that I'm attaching. Thank you."

<details><summary>flutter doctor -v (3.7.12)</summary>
<p>

[✓] Flutter (Channel stable, 3.7.12, on macOS 13.4.1 22F82 darwin-arm64, locale tr-TR)
    • Flutter version 3.7.12 on channel stable at /Volumes/Media/Development/Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (3 months ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Volumes/Media/Development/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Volumes/Media/Development/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • iPhone SE (3rd generation) (mobile) • 098B16AE-626F-42C4-ACE2-EB2266CCF840 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)                     • macos                                • darwin-arm64   • macOS 13.4.1 22F82 darwin-arm64
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 114.0.5735.198

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

</p>
</details>

**Comment by alekoleg** [comment]
Faced the same issue.

**Comment by Piinks** [comment]
Hmm, this reminds me of https://github.com/flutter/flutter/issues/127017
@Renzo-Olivares is this the same issue in a different scenario?

**Comment by Renzo-Olivares** [comment]
@Piinks this looks like the same issue. I'll take a look and confirm.

**Comment by alekoleg** [comment]
@Renzo-Olivares any updates on this one? Maybe some additional info is needed?

**Comment by alekoleg** [comment]
@burhanaksendir Have you found any workarounds for now?

**Comment by burhanaksendir** [comment]
> @burhanaksendir Have you found any workarounds for now?

Hi  @alekoleg 

"Not yet, but I've managed to come up with a solution. If you're interested, I upgraded Flutter to version 3.13.0, and I made some adjustments to the sample code.

Upgrade Flutter to version 3.13.0.
Modify the sample code as follows:

```
SelectionArea(
          child: Text.rich(
            TextSpan(
              text: sampleText,
              style: TextStyle(fontSize: 20.0),
            ),
          ),
        )
```

**Comment by Renzo-Olivares** [comment]
Hi @alekoleg the description of the problem and workaround can be found here https://github.com/flutter/flutter/issues/127017#issuecomment-1564992595 . Essentially it is to wrap the outer scroll view in a `MediaQuery` widget and define a custom `gestureSettings` that lowers the `touchSlop` so the outer recognizer can win before the `SelectableText` recognizers.

```dart
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

const String sampleText = '''
Alice was beginning to get very tired of sitting by her sister on the bank, and of having nothing to do: once or twice she had peeped into the book her sister was reading, but it had no pictures or conversations in it, “and what is the use of a book,” thought Alice “without pictures or conversations?”
So she was considering in her own mind (as well as she could, for the hot day made her feel very sleepy and stupid), whether the pleasure of making a daisy-chain would be worth the trouble of getting up and picking the daisies, when suddenly a White Rabbit with pink eyes ran close by her.
''';

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('SelectableText Sample'),
        ),
        body: MediaQuery(
          data: MediaQueryData(
            gestureSettings: DeviceGestureSettings(touchSlop: 8.0),
          ),
          child: PageView.builder(
            itemCount: 3,
            itemBuilder: (BuildContext context, int index) {
              return MyPage(index: index);
            },
          ),
        ),
      ),
    );
  }
}

class MyPage extends StatelessWidget {
  final int index;

  const MyPage({super.key, required this.index});

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(16.0),
      child: const Center(
        child: SelectableText.rich(
          TextSpan(
            text: sampleText,
            style: TextStyle(fontSize: 20.0),
          ),
        ),
      ),
    );
  }
}
```
