### ISSUE TITLE
[CP] Reland wait vsync on UI thread and update viewport inset to avoid jitter

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#130284]
### Issue Link

https://github.com/flutter/flutter/issues/130028

### Commit Hash

cf67f83

### Target

beta

### PR Link

https://github.com/flutter/engine/pull/43522

### Changelog Description

Fixes a crash when the engine is is being destroyed and the keyboard animation display link fires at the same time.

### Impacted Users

Flutter developers

### Impact Description

Random crash.

### Workaround

No

### Risk

low

### Test Coverage

yes

### Validation Steps

It is hard to reproduce the crash manually. The `testKeyboardAnimationWillNotCrashWhenEngineDestroyed` unit test is the most reliable way to reproduce the test and validate the fix: 
https://github.com/flutter/engine/blob/main/shell/platform/darwin/ios/framework/Source/FlutterViewControllerTest.mm#L443

**Comment by CaseyHillers** [comment]
@dnfield can you review this CP request? If it looks good to you, add the "cp: approved" label.

**Comment by dnfield** [comment]
lgtm
