### ISSUE TITLE
Troubleshoot Firestore deletion behavior and add more tests

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#13028]
@pulyaevskiy had some additional plans for the Firestore plugin on flutter/plugins#258

> I've been trying to nail down this weird behavior with deleting items and it seems to be that this is an issue with underlying platform SDKs... but I'm not sure.
> 
> In short: deleting a document (while subscribed to a Query matching this document) results in following sequence of snapshot events with DocumentChanges:
> 
> 1. DocumentChangeType.removed with `hasPendingWrites: false` and `isFromCache: false` - OK
> 2. DocumentChangeType.added with `hasPendingWrites: false` and `isFromCache: true` - ???
> 3. DocumentChangeType.removed with `hasPendingWrites: false` and `isFromCache: false` - ???
> 
> Tested with `AnimatedList` and `Dismissible` items: deleted item appears in the list for a second and disappears again.
> 
> Wondering if anyone knows what am I doing wrong here?
> 
> I will be pushing some more changes this week in regards to SnapshotMetadata and adding some more tests.

**Comment by Skylled** [comment]
Expected order of events:

1. Call `.delete()` on DocumentReference.
2. Object is removed from cache.
3. Local change is propagated to server.

Perceived actual order of events:

1. Call `.delete()` on DocumentReference.
2. Delete request is sent to server.
3. New version of QuerySnapshot is received minus removed document.
4. Cache fills in the blank, thinking it has better info than server.
5. Cache updates with removal.

Does this seem accurate to someone more familiar?

**Comment by pulyaevskiy** [comment]
It would be great if someone else can actually test this. 

According to the documentation when a doc is added we get 1 `added` event which is fired immediately and should have `hasPendingWrites: true`. If a Query explicitly requests metadata updates then we should get another event for the same document with `hasPendingWrites: false` meaning it was successfully sent to the server.

I'd expect similar behavior with deletes, meaning:

1. Call `.delete()` on DocumentReference
2. Received new `QuerySnapshot` with one `removed` event for the doc and `hasPendingWrites: true` (fired immediately)
3 (optional) If Query requests metadata updates after the doc is saved on the server receive another `QuerySnapshot` with one `removed` event for the same doc and `hasPendingWrites: false`

Actual results that I get currently:

1. Call `.delete()` on DocumentReference
2. Received `DocumentChangeType.removed` with `hasPendingWrites: false` and `isFromCache: false`
3. `DocumentChangeType.added` with `hasPendingWrites: false` and `isFromCache: true`
4. `DocumentChangeType.removed` with `hasPendingWrites: false` and `isFromCache: false`

**Comment by harrygt** [comment]
Having the exact same issue. Have verified that we also get the same set of events. 

Any luck with finding a solution?

**Comment by latesr** [comment]
I am also getting the same behaviour.

If I delete a document whilst listening on a Stream<QuerySnapshot> I get:

1. DocumentChangeType.removed, length: 1
2. DocumentChangeType.added, length: 1
3. DocumentChangeType.removed, length: 1

Any luck finding out what's going on?

**Comment by pulyaevskiy** [comment]
Personally I switched away from using change deltas to use full document snapshots. It might be less performant but a lot easier to  maintain, I just refresh the whole internal list each time a receive an update.

This works quite well for me in combination with Redux store and built_value generated models with proper identity hashCodes and `==`. UI only gets refreshed when objects are actually different.

**Comment by lukepighetti** [comment]
I'm not sure if this is the problem I'm running into but I would really appreciate some guidance. I have a FirebaseAnimatedList whose children are wrapped in Dismissible. Everything works great but I get the 'A dismissed Dismissible widget is still part of the tree.' error and I haven't found any way to force an item off FirebaseAnimatedList. (This is for firebase_database)

**Comment by pulyaevskiy** [comment]
This _might_ have been fixed recently in https://github.com/firebase/firebase-ios-sdk/issues/1045. I haven't tested it myself though.

**Comment by collinjackson** [comment]
I think we might be able to test for this now.

**Comment by kroikie** [comment]
@collinjackson

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/941. Any further collaboration will be done there.

**Comment by BondarenkoStas** [comment]
@collinjackson I guess it's safe to close this one (flutterfire mirror)?

**Comment by xnio94** [comment]
@lukepighetti did you found a solution
