### ISSUE TITLE
[Video Player] [Android Only ] toggle full screen causes the app to skip frames and ths OS restarts

### ISSUE THREAD

**Issue by ahmed-hararaa** [flutter/flutter#130219]
**Device Log Check The  End**

D/CCodecBufferChannel(23190): [c2.android.aac.decoder#901] DEBUG: elapsed: n=6 [in=0 pipeline=0 out=2 smoothness=4]
D/PipelineWatcher(23190): DEBUG: elapsed 2 / 6
D/BufferPoolAccessor2.0(23190): bufferpool2 0xb400006faeb63c28 : 5(40960 size) total buffers - 5(40960 size) used buffers - 1/7 (recycle/alloc) - 14/5438 (fetch/transfer)
D/CCodecBufferChannel(23190): [c2.android.aac.decoder#901] DEBUG: elapsed: n=6 [in=0 pipeline=0 out=2 smoothness=4]
D/PipelineWatcher(23190): DEBUG: elapsed 2 / 6
D/CCodecBufferChannel(23190): [c2.android.aac.decoder#901] DEBUG: elapsed: n=6 [in=0 pipeline=0 out=2 smoothness=4]
D/PipelineWatcher(23190): DEBUG: elapsed 2 / 6
D/BufferPoolAccessor2.0(23190): bufferpool2 0xb400006faeb63c28 : 5(40960 size) total buffers - 5(40960 size) used buffers - 1/7 (recycle/alloc) - 14/5691 (fetch/transfer)
D/CCodecBuffers(23190): [c2.android.aac.decoder#901:1D-Input.Impl[N]] codec released a buffer owned by client (index 1)
D/CCodecBufferChannel(23190): [c2.android.aac.decoder#901] DEBUG: elapsed: n=6 [in=0 pipeline=0 out=2 smoothness=4]
D/PipelineWatcher(23190): DEBUG: elapsed 2 / 6
D/BufferPoolAccessor2.0(23190): bufferpool2 0xb400006faeb63c28 : 5(40960 size) total buffers - 5(40960 size) used buffers - 1/7 (recycle/alloc) - 14/5939 (fetch/transfer)
D/CCodecBufferChannel(23190): [c2.android.aac.decoder#901] DEBUG: elapsed: n=6 [in=0 pipeline=0 out=2 smoothness=4]
D/PipelineWatcher(23190): DEBUG: elapsed 2 / 6
D/CCodecBufferChannel(23190): [c2.android.aac.decoder#901] DEBUG: elapsed: n=6 [in=0 pipeline=0 out=2 smoothness=4]
D/PipelineWatcher(23190): DEBUG: elapsed 2 / 6
D/BufferPoolAccessor2.0(23190): bufferpool2 0xb400006faeb63c28 : 5(40960 size) total buffers - 5(40960 size) used buffers - 1/7 (recycle/alloc) - 14/6191 (fetch/transfer)
D/CCodecBufferChannel(23190): [c2.android.aac.decoder#901] DEBUG: elapsed: n=6 [in=0 pipeline=0 out=2 smoothness=4]
D/PipelineWatcher(23190): DEBUG: elapsed 2 / 6
D/CCodecBuffers(23190): [c2.android.aac.decoder#901:1D-Input.Impl[N]] codec released a buffer owned by client (index 0)
D/CCodecBuffers(23190): [c2.android.aac.decoder#901:1D-Input.Impl[N]] codec released a buffer owned by client (index 0)
D/CCodecBufferChannel(23190): [c2.android.aac.decoder#901] DEBUG: elapsed: n=6 [in=0 pipeline=0 out=2 smoothness=4]
D/PipelineWatcher(23190): DEBUG: elapsed 2 / 6
D/BufferPoolAccessor2.0(23190): bufferpool2 0xb400006faeb63c28 : 5(40960 size) total buffers - 5(40960 size) used buffers - 1/7 (recycle/alloc) - 14/6433 (fetch/transfer)
D/CCodecBufferChannel(23190): [c2.android.aac.decoder#901] DEBUG: elapsed: n=6 [in=0 pipeline=0 out=2 smoothness=4]
D/PipelineWatcher(23190): DEBUG: elapsed 2 / 6
D/BufferPoolAccessor2.0(23190): bufferpool2 0xb400006faeb63c28 : 5(40960 size) total buffers - 5(40960 size) used buffers - 1/7 (recycle/alloc) - 14/6672 (fetch/transfer)
D/CCodecBufferChannel(23190): [c2.android.aac.decoder#901] DEBUG: elapsed: n=6 [in=0 pipeline=0 out=2 smoothness=4]
D/PipelineWatcher(23190): DEBUG: elapsed 2 / 6
D/CCodecBufferChannel(23190): [c2.android.aac.decoder#901] DEBUG: elapsed: n=6 [in=0 pipeline=0 out=2 smoothness=4]
D/PipelineWatcher(23190): DEBUG: elapsed 2 / 6
D/BufferPoolAccessor2.0(23190): bufferpool2 0xb400006faeb63c28 : 5(40960 size) total buffers - 5(40960 size) used buffers - 1/7 (recycle/alloc) - 14/6924 (fetch/transfer)
D/CCodecBufferChannel(23190): [c2.android.aac.decoder#901] DEBUG: elapsed: n=6 [in=0 pipeline=0 out=2 smoothness=4]
D/PipelineWatcher(23190): DEBUG: elapsed 2 / 6
D/BufferPoolAccessor2.0(23190): bufferpool2 0xb400006faeb63c28 : 5(40960 size) total buffers - 5(40960 size) used buffers - 1/7 (recycle/alloc) - 14/7163 (fetch/transfer)
D/CCodecBufferChannel(23190): [c2.android.aac.decoder#901] DEBUG: elapsed: n=6 [in=0 pipeline=0 out=2 smoothness=4]
D/PipelineWatcher(23190): DEBUG: elapsed 2 / 6
D/CCodecBuffers(23190): [c2.android.aac.decoder#901:1D-Input.Impl[N]] codec released a buffer owned by client (index 3)
D/CCodecBufferChannel(23190): [c2.android.aac.decoder#901] DEBUG: elapsed: n=6 [in=0 pipeline=0 out=2 smoothness=4]
D/PipelineWatcher(23190): DEBUG: elapsed 2 / 6
D/CCodecBuffers(23190): [c2.android.aac.decoder#901:1D-Input.Impl[N]] codec released a buffer owned by client (index 0)
D/CCodecBuffers(23190): [c2.android.aac.decoder#901:1D-Input.Impl[N]] codec released a buffer owned by client (index 1)
D/CCodecBuffers(23190): [c2.android.aac.decoder#901:1D-Input.Impl[N]] codec released a buffer owned by client (index 0)
D/BufferPoolAccessor2.0(23190): bufferpool2 0xb400006faeb63c28 : 5(40960 size) total buffers - 5(40960 size) used buffers - 1/7 (recycle/alloc) - 14/7424 (fetch/transfer)
D/CCodecBuffers(23190): [c2.android.aac.decoder#901:1D-Input.Impl[N]] codec released a buffer owned by client (index 0)
D/CCodecBuffers(23190): [c2.android.aac.decoder#901:1D-Input.Impl[N]] codec released a buffer owned by client (index 0)
W/BpBinder(23190): Slow Binder: BpBinder transact took 50021ms, interface=android.app.IActivityTaskManager, code=66 oneway=false
W/Looper  (23190): PerfMonitor longMsg : seq=19655 plan=09:42:39.187 late=181ms wall=50028ms running=1ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 procState=2
W/BpBinder(23190): Slow Binder: BpBinder transact took 49334ms, interface=android.gui.IGraphicBufferProducer, code=2 oneway=false
W/Looper  (23190): PerfMonitor looperActivity : package=co.equinesolutions.jcl/com.example.ifederation_mobile.MainActivity time=0ms latency=50202ms running=0ms  procState=2 ClientTransaction{ callbacks=[android.app.servertransaction.ActivityConfigurationChangeItem] } historyMsgCount=12 (msgIndex=1 wall=132ms seq=19649 h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0) (msgIndex=2 wall=87ms seq=19650 running=28ms runnable=5ms late=125ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver) (msgIndex=7 wall=50028ms seq=19655 running=1ms late=181ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
I/Choreographer(23190): Skipped 3008 frames!  The application may be doing too much work on its main thread.
I/OpenGLRenderer(23190): Davey! duration=50169ms; Flags=1, IntendedVsync=18389637556197, Vsync=18439770887525, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=18439787452339, AnimationStart=18439787453589, PerformTraversalsStart=18439787454423, DrawStart=18439802076089, SyncQueued=18439804355777, SyncStart=18439804643746, IssueDrawCommandsStart=18439804688329, SwapBuffers=18439806969944, FrameCompleted=18439807553069, DequeueBufferDuration=1384271, QueueBufferDuration=285625, GpuCompleted=0, 
W/Looper  (23190): PerfMonitor doFrame : time=21ms vsyncFrame=0 latency=50150ms procState=2 historyMsgCount=18 (msgIndex=1 wall=87ms seq=19650 running=28ms runnable=5ms late=125ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver) (msgIndex=6 wall=50028ms seq=19655 running=1ms late=181ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
D/CCodecBuffers(23190): [c2.android.aac.decoder#901:1D-Input.Impl[N]] codec released a buffer owned by client (index 0)
D/CCodecBufferChannel(23190): [c2.android.aac.decoder#901] DEBUG: elapsed: n=6 [in=0 pipeline=0 out=2 smoothness=4]
D/PipelineWatcher(23190): DEBUG: elapsed 2 / 6
D/BufferPoolAccessor2.0(23190): bufferpool2 0xb400006faeb63c28 : 5(40960 size) total buffers - 5(40960 size) used buffers - 1/7 (recycle/alloc) - 14/7662 (fetch/transfer)
D/CCodecBufferChannel(23190): [c2.android.aac.decoder#901] DEBUG: elapsed: n=6 [in=0 pipeline=0 out=2 smoothness=4]
D/PipelineWatcher(23190): DEBUG: elapsed 2 / 6
D/CCodecBufferChannel(23190): [c2.android.aac.decoder#901] DEBUG: elapsed: n=6 [in=0 pipeline=0 out=2 smoothness=4]
D/PipelineWatcher(23190): DEBUG: elapsed 2 / 6
D/CCodecBuffers(23190): [c2.android.aac.decoder#901:1D-Input.Impl[N]] codec released a buffer owned by client (index 0)
D/BufferPoolAccessor2.0(23190): bufferpool2 0xb400006faeb63c28 : 5(40960 size) total buffers - 5(40960 size) used buffers - 1/7 (recycle/alloc) - 14/7920 (fetch/transfer)
D/CCodecBufferChannel(23190): [c2.android.aac.decoder#901] DEBUG: elapsed: n=6 [in=0 pipeline=0 out=2 smoothness=4]
D/PipelineWatcher(23190): DEBUG: elapsed 2 / 6
D/CCodecBuffers(23190): [c2.android.aac.decoder#901:1D-Input.Impl[N]] codec released a buffer owned by client (index 1)
D/BufferPoolAccessor2.0(23190): bufferpool2 0xb400006faeb63c28 : 5(40960 size) total buffers - 5(40960 size) used buffers - 1/7 (recycle/alloc) - 14/8155 (fetch/transfer)
D/CCodecBufferChannel(23190): [c2.android.aac.decoder#901] DEBUG: elapsed: n=6 [in=0 pipeline=0 out=2 smoothness=4]
D/PipelineWatcher(23190): DEBUG: elapsed 4 / 6
W/BpBinder(23190): Slow Binder: BpBinder transact took 608ms, interface=android.app.IActivityTaskManager, code=66 oneway=false
W/Looper  (23190): PerfMonitor looperActivity : package=co.equinesolutions.jcl/com.example.ifederation_mobile.MainActivity time=0ms latency=737ms running=1ms  procState=2 ClientTransaction{ callbacks=[android.app.servertransaction.ActivityConfigurationChangeItem] } historyMsgCount=12 (msgIndex=1 wall=118ms seq=22178 running=1ms late=1ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0) (msgIndex=2 wall=78ms seq=22179 running=22ms runnable=9ms late=116ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver) (msgIndex=9 wall=608ms seq=22186 running=1ms late=146ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
I/Choreographer(23190): Skipped 42 frames!  The application may be doing too much work on its main thread.
I/OpenGLRenderer(23190): Davey! duration=718ms; Flags=1, IntendedVsync=18454581533870, Vsync=18455281533842, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=18455284049781, AnimationStart=18455284051136, PerformTraversalsStart=18455284051917, DrawStart=18455296165094, SyncQueued=18455296879938, SyncStart=18455297778531, IssueDrawCommandsStart=18455297822021, SwapBuffers=18455299831292, FrameCompleted=18455300754938, DequeueBufferDuration=1230104, QueueBufferDuration=332916, GpuCompleted=0, 
W/Looper  (23190): PerfMonitor doFrame : time=18ms vsyncFrame=0 latency=702ms procState=2 historyMsgCount=19 (msgIndex=1 wall=78ms seq=22179 running=22ms runnable=9ms late=116ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver) (msgIndex=8 wall=608ms seq=22186 running=1ms late=146ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
W/BpBinder(23190): Slow Binder: BpBinder transact took 222ms, interface=android.gui.IGraphicBufferProducer, code=2 oneway=false
D/CCodecBuffers(23190): [c2.android.aac.decoder#901:1D-Input.Impl[N]] codec released a buffer owned by client (index 0)
D/CCodecBufferChannel(23190): [c2.android.aac.decoder#901] DEBUG: elapsed: n=6 [in=0 pipeline=0 out=2 smoothness=4]
D/PipelineWatcher(23190): DEBUG: elapsed 2 / 6
D/BufferPoolAccessor2.0(23190): bufferpool2 0xb400006faeb63c28 : 5(40960 size) total buffers - 5(40960 size) used buffers - 1/7 (recycle/alloc) - 14/8393 (fetch/transfer)
D/CCodecBuffers(23190): [c2.android.aac.decoder#901:1D-Input.Impl[N]] codec released a buffer owned by client (index 0)
D/CCodecBuffers(23190): [c2.android.aac.decoder#901:1D-Input.Impl[N]] codec released a buffer owned by client (index 0)
D/CCodecBufferChannel(23190): [c2.android.aac.decoder#901] DEBUG: elapsed: n=6 [in=0 pipeline=0 out=2 smoothness=4]
D/PipelineWatcher(23190): DEBUG: elapsed 2 / 6
D/AudioTrack(23190): stop(sessionID=5761)
D/AudioTrack(23190): stop(697): prior state:STATE_ACTIVE
D/AudioTrack(23190): stop(697): called with 4145152 frames delivered
I/CCodecConfig(23190): query failed after returning 19 values (BAD_INDEX)
D/CCodecConfig(23190): c2 config diff is   c2::i32 coding.drc.compression-mode.value = 3
W/Codec2Client(23190): query -- param skipped: index = 1342179345.
W/Codec2Client(23190): query -- param skipped: index = 2415921170.
W/Codec2Client(23190): query -- param skipped: index = 1610614798.
D/AudioTrack(23190): stop(sessionID=5761)
D/AudioTrack(23190): stop(697): prior state:STATE_FLUSHED
D/AudioTrack(23190): ~AudioTrack(sessionID=5761)
D/AudioTrack(23190): stop(sessionID=5761)
D/AudioTrack(23190): stop(697): prior state:STATE_FLUSHED
D/BufferPoolAccessor2.0(23190): bufferpool2 0xb400006faeb63c28 : 5(40960 size) total buffers - 5(40960 size) used buffers - 1/7 (recycle/alloc) - 14/8595 (fetch/transfer)
D/CCodecBufferChannel(23190): [c2.android.aac.decoder#901] DEBUG: elapsed: n=6 [in=0 pipeline=0 out=2 smoothness=4]
D/PipelineWatcher(23190): DEBUG: elapsed 2 / 6
D/CCodecBuffers(23190): [c2.android.aac.decoder#901:Output[N]] popFromStashAndRegister: output format changed to AMessage(what = 0x00000000) = {
D/CCodecBuffers(23190):   int32_t aac-drc-album-mode = 0
D/CCodecBuffers(23190):   int32_t aac-drc-boost-level = 127
D/CCodecBuffers(23190):   int32_t aac-drc-cut-level = 127
D/CCodecBuffers(23190):   int32_t aac-drc-effect-type = 3
D/CCodecBuffers(23190):   int32_t aac-drc-heavy-compression = 3
D/CCodecBuffers(23190):   int32_t aac-drc-output-loudness = -1
D/CCodecBuffers(23190):   int32_t aac-encoded-target-level = -1
D/CCodecBuffers(23190):   int32_t aac-max-output-channel_count = 8
D/CCodecBuffers(23190):   int32_t aac-target-ref-level = 64
D/CCodecBuffers(23190):   int32_t channel-count = 2
D/CCodecBuffers(23190):   string mime = "audio/raw"
D/CCodecBuffers(23190):   int32_t sample-rate = 48000
D/CCodecBuffers(23190): }
D/CCodecConfig(23190): c2 config diff is   c2::i32 coding.drc.compression-mode.value = 1
D/CCodecBuffers(23190): [c2.android.aac.decoder#901:Output[N]] popFromStashAndRegister: output format changed to AMessage(what = 0x00000000) = {
D/CCodecBuffers(23190):   int32_t aac-drc-album-mode = 0
D/CCodecBuffers(23190):   int32_t aac-drc-boost-level = 127
D/CCodecBuffers(23190):   int32_t aac-drc-cut-level = 127
D/CCodecBuffers(23190):   int32_t aac-drc-effect-type = 3
D/CCodecBuffers(23190):   int32_t aac-drc-heavy-compression = 1
D/CCodecBuffers(23190):   int32_t aac-drc-output-loudness = -1
D/CCodecBuffers(23190):   int32_t aac-encoded-target-level = -1
D/CCodecBuffers(23190):   int32_t aac-max-output-channel_count = 8
D/CCodecBuffers(23190):   int32_t aac-target-ref-level = 64
D/CCodecBuffers(23190):   int32_t channel-count = 2
D/CCodecBuffers(23190):   string mime = "audio/raw"
D/CCodecBuffers(23190):   int32_t sample-rate = 48000
D/CCodecBuffers(23190): }
I/nesolutions.jc(23190): getDeviceIsSupportElevoc() The device is not support elevoc
D/AudioTrack(23190): set(sessionId=5761)
D/AudioTrack(23190): set(): streamType -1, sampleRate 48000, format 0x1, channelMask 0x3, frameCount 15376, flags #0, notificationFrames 0, sessionId 5761, transferType 3, uid -1, pid -1
D/AudioTrack(23190): setVolume: left = 1.000000 right = 1.000000
D/AudioTrack(23190): stop(sessionID=5761)
D/AudioTrack(23190): stop(698): prior state:STATE_STOPPED
D/PipelineWatcher(23190): DEBUG: elapsed 0 / 0
W/Choreographer(23190): Frame time is 0.059961 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
W/BpBinder(23190): Slow Binder: BpBinder transact took 93862ms, interface=, code=11 oneway=false
W/Looper  (23190): PerfMonitor longMsg : seq=43573 plan=09:47:10.171 late=1ms wall=93863ms running=2ms runnable=2ms h=android.view.ViewRootImpl$ViewRootHandler c=android.view.-$$Lambda$ViewRootImpl$DJd0VUYJgsebcnSohO6h8zc_ONI procState=2
**I/Choreographer(23190): Skipped 5634 frames!  The application may be doing too much work on its main thread.
W/System.err(23190): android.os.DeadObjectException
W/System.err(23190): 	at android.os.BinderProxy.transactNative(Native Method)
W/System.err(23190): 	at android.os.BinderProxy.transact(BinderProxy.java:540)
W/System.err(23190): 	at android.app.IActivityTaskManager$Stub$Proxy.handleFreeformModeRequst(IActivityTaskManager.java:7796)
W/System.err(23190): 	at android.app.Activity.getWindowingMode(Activity.java:7417)
W/System.err(23190): 	at android.util.MiuiMultiWindowUtils.updatewindowConfiguration(MiuiMultiWindowUtils.java:1265)
W/System.err(23190): 	at com.android.internal.policy.DecorView.getResources(DecorView.java:2062)
W/System.err(23190): 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:701)
W/System.err(23190): 	at android.view.View.measure(View.java:25777)
W/System.err(23190): 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3503)
W/System.err(23190): 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2323)
W/System.err(23190): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2584)
W/System.err(23190): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2047)
W/System.err(23190): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8351)
W/System.err(23190): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1058)
W/System.err(23190): 	at android.view.Choreographer.doCallbacks(Choreographer.java:880)
W/System.err(23190): 	at android.view.Choreographer.doFrame(Choreographer.java:813)
W/System.err(23190): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1043)
W/System.err(23190): 	at android.os.Handler.handleCallback(Handler.java:938)
W/System.err(23190): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(23190): 	at android.os.Looper.loop(Looper.java:236)
W/System.err(23190): 	at android.app.ActivityThread.main(ActivityThread.java:7876)
W/System.err(23190): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(23190): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
W/System.err(23190): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
W/System.err(23190): android.os.DeadObjectException
W/System.err(23190): 	at android.os.BinderProxy.transactNative(Native Method)
W/System.err(23190): 	at android.os.BinderProxy.transact(BinderProxy.java:540)
W/System.err(23190): 	at android.app.IActivityTaskManager$Stub$Proxy.handleFreeformModeRequst(IActivityTaskManager.java:7796)
W/System.err(23190): 	at android.app.Activity.getWindowingMode(Activity.java:7417)
W/System.err(23190): 	at android.util.MiuiMultiWindowUtils.updatewindowConfiguration(MiuiMultiWindowUtils.java:1265)
W/System.err(23190): 	at com.android.internal.policy.DecorView.getResources(DecorView.java:2062)
W/System.err(23190): 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:701)
W/System.err(23190): 	at android.view.View.measure(View.java:25777)
W/System.err(23190): 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3503)
W/System.err(23190): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2986)
W/System.err(23190): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2047)
W/System.err(23190): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8351)
W/System.err(23190): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1058)
W/System.err(23190): 	at android.view.Choreographer.doCallbacks(Choreographer.java:880)
W/System.err(23190): 	at android.view.Choreographer.doFrame(Choreographer.java:813)
W/System.err(23190): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1043)
W/System.err(23190): 	at android.os.Handler.handleCallback(Handler.java:938)
W/System.err(23190): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(23190): 	at android.os.Looper.loop(Looper.java:236)
W/System.err(23190): 	at android.app.ActivityThread.main(ActivityThread.java:7876)
W/System.err(23190): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(23190): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
W/System.err(23190): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)**

**Comment by dam-ease** [comment]
Hi @ahmed-hararaa. Thanks for filing this issue. Please can you provide more information on this issue.

- What version of flutter and Video Player Plugin can you reproduce this?
- Can you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
- Also, a step by step process to reproduce this would be great

Thank you

**Comment by ahmed-hararaa** [comment]
@dam-ease 
i tested it with different flutter versions and video player plugin.
to be honest it't only happens on my physical device (xiaomi k20) works fine in (android emulator/ ios simulator/ ios devices).

**Comment by dam-ease** [comment]
Hi @ahmed-hararaa. Thanks for confirming. Are you able to test on other physical android devices? If yes, is it specific to xiaomi k20?? Also, would be great if you could provide reproducible steps to verify on our end as well.
