### ISSUE TITLE
Codelab Hot Reload changes random word

### ISSUE THREAD

**Issue by crowne** [flutter/flutter#130221]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
  -  Related issue https://stackoverflow.com/questions/58580517/flutter-web-does-hot-restart-instead-of-hot-reload-is-hot-reload-supporte
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

While following this [codelab](https://codelabs.developers.google.com/codelabs/flutter-codelab-first#3)

I get to the step "First Hot Reload", which  states

> Notice how the app changes immediately but the random word stays the same.

I'm not seeing this behaviour.
I'm running on Windows 10, the app is launched in Edge
When I save the page is refreshed including a new different random word.

According to this issue
https://stackoverflow.com/questions/58580517/flutter-web-does-hot-restart-instead-of-hot-reload-is-hot-reload-supporte

Hot reload is not supported by flutter web yet.
Hopefully we can get the Codelab docs updated.

### Expected results

random word stays the same

### Actual results

random word changes

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
C:\flutter\demo› flutter doctor -v
[✓] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.19045.3086], locale en-GB)
    • Flutter version 3.10.5 on channel stable at C:\util\flutter\flutter-3.10.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (4 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.80.0)
    • VS Code at C:\Users\Neil.Crow\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.3086]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 114.0.5735.199
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 114.0.1823.67

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

</details>

**Comment by danagbemava-nc** [comment]
cc @domesticmouse

**Comment by domesticmouse** [comment]
Just confirming, are you running this app inside of the Android emulator, a web browser, or as a windows native executable?

**Comment by crowne** [comment]
I'm running it from VS Code using Edge (Web) as the target device

**Comment by domesticmouse** [comment]
Hot reload on web doesn't work currently. 

@parlough any idea where we document this shortcoming of Flutter web?

@filiph want to add a note to the codelab about Flutter web not supporting hot reload?

**Comment by parlough** [comment]
> @parlough any idea where we document this shortcoming of Flutter web?

It's a brief, easy-to-miss mention on the hot reload page. Likely because web support became a larger focus after much of the mentions of hot reload were already added. 

https://docs.flutter.dev/tools/hot-reload#:~:text=Flutter%20web%20currently%20supports%20hot%20restart%20but%20not%20hot%20reload.

I've opened https://github.com/flutter/website/issues/9007 to improve other cases which could benefit from this clarification.

**Comment by filiph** [comment]
FWIW, there notice is already there, in the set up section:

> It might be tempting to select the web as your development target. The downside of this choice is that you lose one of Flutter's most useful development features: Stateful Hot Reload. Flutter can't hot-reload web applications.

I realize it might seem prudent to re-mention it any time we use hot reload in the codelab, but that seemed excessive when I was writing the codelab. ("Remember, this won't work if you're using the web as your development target.")
