### ISSUE TITLE
[CP] Check for a null command buffer in InlinePassContext::EndPass

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#130288]
### Issue Link

https://github.com/flutter/flutter/issues/130167

### Commit Hash

189f823e7b4103b6b438a57b4601455b3073b75a

### Target

beta

### PR Link

https://github.com/flutter/engine/pull/43525

### Changelog Description

Fix a missing null check in Impeller

### Impacted Users

Impeller users

### Impact Description

Engine crash when rendering some content with Impeller

### Workaround

No

### Risk

low

### Test Coverage

yes

### Validation Steps

Run the sample app in https://github.com/flutter/flutter/issues/130167

**Comment by CaseyHillers** [comment]
@bdero can you review this CP request? If it looks good to you, add the "cp: approved" label.

**Comment by bdero** [comment]
LGTM
