### ISSUE TITLE
flutter when opening or building android folder and run app and try to generate apk

### ISSUE THREAD

**Issue by mariam-wahba** [flutter/flutter#130228]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Hello,

I'm trying to just even run android app of a flutter project and then want to generate a signed apk..... Although i can run the app if i opened from the whole project file and everything is ok and the app is running good....it only happens if i open the android folder and i need to generate a signed apk as i have a deadline

and here is my build.gradle 

```
buildscript {
    ext.kotlin_version = '1.7.0'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.0.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.13'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.1'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
```

and the other build.gradle

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"


android {
    compileSdkVersion 33

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.xlab.premium.premium"
        minSdkVersion 20
        targetSdkVersion 33
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
    }
//    subprojects {
//        project.configurations.all {
//            resolutionStrategy.eachDependency { details ->
//                if (details.requested.group == 'com.android.support'
//                        && !details.requested.name.contains('multidex') ) {
//                    details.useVersion "27.1.1"
//                }
//            }
//        }
//    }

    buildTypes {
        release {
            signingConfig signingConfigs.debug
//            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }

    }
    namespace 'com.xlab.premium.premium'
}

flutter {
    source '../..'
}

dependencies {
    implementation("com.android.support:multidex:1.0.3")
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    // Import the BoM for the Firebase platform
    implementation platform('com.google.firebase:firebase-bom:29.0.1')

    // Declare the dependencies for the Firebase Cloud Messaging and Analytics libraries
    // When using the BoM, you don't specify versions in Firebase library dependencies
    implementation 'com.google.firebase:firebase-messaging'
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.firebase:firebase-crashlytics'
    implementation 'com.android.support:multidex:1.0.3'
}


```
and gradle properties file

```
#Fri Jun 23 08:50:38 CEST 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-8.2-bin.zip
```

### Actual results

this happens  

```
FAILURE: Build failed with an exception.

* Where:
Script 'D:\flutter_windows_3.10.5-stable\flutter\packages\flutter_tools\gradle\flutter.gradle
' line: 994

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Could not create task ':app:copyFlutterAssetsRelease'.
      > Could not create task ':app:mergeReleaseAssets'.
         > Cannot use @TaskAction annotation on method IncrementalTask.taskAction$gradle_core
() because interface org.gradle.api.tasks.incremental.IncrementalTaskInputs is not a valid pa
rameter to an action method.
```

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

flutter doctor --verbose
```
[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.19045.3086], locale
    en-US)
    • Flutter version 3.10.5 on channel stable at D:\flutter_windows_3.10.5-stable\flutter   
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (4 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\welcome\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor
      --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its       
      default components

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] Connected device (4 available)
    • MAR LX1A (mobile) • QTC4C19807003317 • android-arm64  • Android 10 (API 29)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version     
      10.0.19045.3086]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 114.0.5735.199   
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 114.0.1823.67   

[√] Network resources
```

**Comment by darshankawar** [comment]
@mariam-wahba 
Not sure if this is causing due to the gradle version you are using, (gradle-8.2-bin.zip) which is recently released.
Can you take a look at [this](https://docs.flutter.dev/release/breaking-changes/android-java-gradle-migration-guide#:~:text=Flutter%20uses%20the%20version%20of,one%20of%20the%20following%20approaches.) and see if following the steps mentioned and the gradle version prescribed, do you still get the same error or not ?

**Comment by mariam-wahba** [comment]
@darshankawar i tried this and it tells me could not load gradle wrapper although i restarted the android studio.... shall i use android studio electric eel instead??

**Comment by darshankawar** [comment]
What error are you getting ?
Did you try with `distributionUrl=https\://services.gradle.org/distributions/gradle-7.6.1-all.zip ` ?



> shall i use android studio electric eel instead??

I don't think that's a solution.

**Comment by mariam-wahba** [comment]
after some trials i only can generate a flutter apk when i write in the terminal "flutter build apk" but still when i open the android folder to generate the signed apk....the android could not build bec of these error  Multiple build operations failed.
    Could not create task ':flutter_plugin_android_lifecycle:generateDebugUnitTestConfig'.
    Could not create task ':google_maps_flutter_android:generateDebugUnitTestConfig'.
    Could not create task ':image_picker_android:generateDebugUnitTestConfig'.
    Could not create task ':path_provider_android:generateDebugUnitTestConfig'.
    Could not create task ':shared_preferences_android:generateDebugUnitTestConfig'.
    Could not create task ':url_launcher_android:generateDebugUnitTestConfig'.
    Could not create task ':video_player_android:generateDebugUnitTestConfig'.
    Could not create task ':webview_flutter_android:generateDebugUnitTestConfig'.
Could not create task ':flutter_plugin_android_lifecycle:generateDebugUnitTestConfig'.
this and base files have different roots: D:\premium\Src\premium\build\flutter_plugin_android_lifecycle and C:\Users\welcome\AppData\Local\Pub\Cache\hosted\pub.dev\flutter_plugin_android_lifecycle-2.0.15\android.  

here is my pubspec.ymal 
 name: premium
description: HR Management System.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.18+18

environment:
  sdk: ">=2.13.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  http: ^0.13.4
  connectivity_plus: ^2.3.8
  url_launcher: ^6.0.20
  cached_network_image: ^3.1.0
  easy_localization: ^3.0.0
  easy_localization_loader: ^1.0.0
  get_it: ^7.2.0
  prefs: ^3.3.0
  dio: ^4.0.1
  font_awesome_flutter: ^10.1.0
  rflutter_alert: ^2.0.4
  oktoast: ^3.1.5
  modal_bottom_sheet: ^3.0.0-pre
  carousel_slider: ^4.0.0
  flutter_carousel_slider: ^1.0.9
  full_screen_image: ^2.0.0
  stop_watch_timer: ^2.0.0
  permission_handler: ^10.0.0
  permission_handler_platform_interface: ^3.7.0
  geolocator: ^9.0.1
  location_permissions: ^4.0.1
  dotted_border: ^2.0.0+1
  file_picker: ^4.4.0
  path_provider: ^2.0.6
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.2
  flutter_local_notifications: ^9.5.3+1
  firebase_crashlytics: ^3.3.2
  firebase_analytics: ^10.4.2
  multi_select_flutter: ^4.0.0
  mime: ^1.0.1
  jiffy: ^5.0.0
  open_file: 3.2.1
  syncfusion_flutter_charts: ^20.2.40
  image_picker: ^0.8.4+4
  flutter_swipe_action_cell: ^3.0.4
  infinite_scroll_pagination: ^3.1.0
  flutter_animator: ^3.2.1
  flutter_widget_from_html_core: ^0.8.5+3
#  flutter_html: ^2.2.1
  #  readmore: ^2.2.0
  linkwell: ^2.0.6
  #  better_video_player: ^1.2.8
  pod_player_new: ^0.0.1
  build_runner:
  flutter_gen_runner: ^5.0.1

  flutter_web_browser: ^0.17.0
  google_maps_flutter: ^2.1.2
  google_maps_flutter_web: ^0.4.0+1
  google_maps_flutter_platform_interface: ^2.1.5
  flutter_cached_pdfview: ^0.4.1
  webviewx: ^0.2.1

  percent_indicator: ^4.2.2
  countup: ^0.1.4
  flutter_multi_select_items: ^0.4.2
  flutter_cupertino_date_picker_fork: ^1.0.7

dependency_overrides:
  meta: ^1.7.0

dev_dependencies:


  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/

    - assets/locale/fr.json
    - assets/locale/en.json
    - assets/locale/ar.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


here is my android/build.gradle

buildscript {
    ext.kotlin_version = '1.7.0'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.13'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.1'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

here is gradle.properties 

distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions//gradle-7.6.1-all.zip

**Comment by darshankawar** [comment]
@mariam-wahba 
Looking at the error log provided:

```
Could not create task ':flutter_plugin_android_lifecycle:generateDebugUnitTestConfig'.
this and base files have different roots: D:\premium\Src\premium\build\flutter_plugin_android_lifecycle and C:\Users\welcome\AppData\Local\Pub\Cache\hosted\pub.dev\flutter_plugin_android_lifecycle-2.0.15\android.  
```

It seems you are hitting https://github.com/flutter/flutter/issues/105395, so please follow-up in it for further updates.

Regarding your original issue, if you create a new Flutter project from Android Studio and go inside android folder, try to create build apk, does it run or gives any errors ?
