### ISSUE TITLE
select tag in flutter webview can't work correctly

### ISSUE THREAD

**Issue by NickYoung-max** [flutter/flutter#130242]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

flutter webview using webview_windows [https://pub.dev/packages/webview_windows](url),html tag like `<select>...</select>` is not work correctly,it's mostly because of the focus event.Every time the mouse clicked, flutter view get focus first,then webview lose focus, and then flutter view lose focus and webview get focus finally.Normally ,a select tag should pop up a menu but nothing happended.How can I do to make the select tag work collectly in flutter webview?

### Expected results

pop up a select menu

### Actual results

select menu can't pop up.

### Code sample

[https://pub.dev/packages/webview_windows](url)，download the webview_windows example code then open devTools and  set the location.href to `https://www.w3cschool.cn/html5/html5-select.html`, 
![image](https://github.com/flutter/flutter/assets/38856823/c11ba1ac-0f3f-4fde-97ce-e68f8037a6b2)

### Screenshots or Video

![image](https://github.com/flutter/flutter/assets/38856823/d50c9ee4-c1d0-4c04-9828-07d9a3147def)

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

[√] Flutter (Channel stable, 3.7.0, on Microsoft Windows [Version 10.0.19045.3086], locale zh-CN)
[√] Windows Version (Installed version of Windows is version 10 or higher)                       
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    X No Java Development Kit (JDK) found; You must have the environment variable JAVA_HOME set and the java binary in your PATH. You can download the JDK from
      https://www.oracle.com/technetwork/java/javase/downloads/.                                                                                               
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.2)
[!] Android Studio (version 2022.2)
    X Unable to find bundled Java version.
[√] Connected device (3 available)
[√] HTTP Host Availability

**Comment by stuartmorgan** [comment]
Issues with third-party packages need to be reported to the authors of those packages.

**Comment by NickYoung-max** [comment]
> Issues with third-party packages need to be reported to the authors of those packages.

I thing it's a flutter issues too,because flutter view steal focus everytime when mouse clicked on webview,that's the reason why a select tag can't pop up.Try to run the example code of webview_windows,or a project with webview, you can see the problem.

**Comment by stuartmorgan** [comment]
> I thing it's a flutter issues too

It is not, it's an issue with the plugin's implementation.

> because flutter view steal focus everytime when mouse clicked on webview

The thing you are clicking on is a `Texture` in the Flutter view. A Flutter view getting focus when you click on it is not a bug.

> that's the reason why a select tag can't pop up.

Then you should report the issue to the plugin developers so that they can investigate the issue with how they are managing their off-screen view's synthetic focus.
