### ISSUE TITLE
Give the option to disable TapAndHorizontalDragGestureRecognizer and LongPressGestureRecognizer for TextFormFields and TextFields

### ISSUE THREAD

**Issue by Scerbelo12** [flutter/flutter#130224]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

At the moment, it's impossible to make a TextFormField or a TextField a descendant of a draggable widget (like for example  a ReorderableListView or a Slidable (from flutter_slidable)) without making impossible to use the latter. 
That's due the fact that TextSelectionGestureDetectorBuilder gesture's (TapAndHorizontalDragGestureRecognizer and LongPressGestureRecognizer) are always the winners of the Gesture Arena.

So, for example, if we have the following Slidable:

```
  Slidable(
        child: Row(
          children: [
            SizedBox(width: 100, child: TextFormField()),
            SizedBox(width: 100, child: TextFormField()),
          ],
        ),
      );
```

it will be impossible to slide the row starting to drag from a point in the TextFormField area.

### Proposal

Give the possibility to disable the features relative to text selection in the TextFormFields and TextFields, so that they can be use as descendants of widgets that respond to a drag gesture. Using the enabled property of the TextFormFields and TextFields doesn't solve the problem, cause I would still like to be able to edit the content of the fields.

**Comment by dam-ease** [comment]
Hi @Scerbelo12. Thanks for filing this. flutter_slidable is a community package. Can you also provide reorderablelistview example and also try using IgnorePointer class if it helps in your use case?

**Comment by Scerbelo12** [comment]
Hi, yes I know that is a community package but the problem is related to the TextFields, not the package. 

Example with reorderablelistview:

```
ReorderableListView(children: [
                      Row(
                        children: [
                          SizedBox(width: 100, child: TextFormField()),
                          SizedBox(width: 100, child: TextFormField()),
                        ],
                      ),
                    ], onReorder: (p1, p2) {}),

```
IgnorePointer does not solve the problem since it makes impossible to tap on the TextField to edit the content.

**Comment by Scerbelo12** [comment]
Hi @dam-ease, can I assume that my proposal is going to be implemented?

**Comment by Scerbelo12** [comment]
Hi @Renzo-Olivares , can I assume that my proposal is going to be implemented?

**Comment by Renzo-Olivares** [comment]
Hi @Scerbelo12 I'm currently exploring methods to fix the issue described. I don't have a current timeline on the fix but there is a workaround I can point you to https://github.com/flutter/flutter/issues/127017#issuecomment-1564992595 . Essentially it is to wrap the outer scroll view in a `MediaQuery` widget and define a custom `gestureSettings` that lowers the `touchSlop` so the outer recognizer can win before the `TextField` recognizers.

**Comment by Scerbelo12** [comment]
Thanks, hope you can fix it soon

**Comment by urusai88** [comment]
I have TextField in PageView. I want to keep TextField vertical scrolling, so i can't wrap TextField in IgnorePointer, but TapAndHorizontalDragGestureRecognizer wins when user trying to scroll horizontally to another page

**Comment by Renzo-Olivares** [comment]
Hi @Scerbelo12, as of https://github.com/flutter/flutter/pull/147341 you can now have a TextField as a descendant of a draggable widget and still have the draggable win the GestureArena. Are you still interested in this proposal?

**Comment by Renzo-Olivares** [comment]
@Scerbelo12, wanted to check back in if this option is still desired. The conflicts between TextField and ancestor draggable widgets have been mostly resolved https://github.com/flutter/flutter/pull/147341 and this proposal seemed like workaround for these issues. If there are still conflicts would be happy to try to resolve them.
