### ISSUE TITLE
[video_player_android] Migrate to `androidx.media3` 

### ISSUE THREAD

**Issue by camsim99** [flutter/flutter#130272]
As of ExoPlayer version 2.19.0, `com.google.android.exoplayer2` was deprecated in favor of `androidx.media3`. To update the `video_player_android` plugin to use this latest version of ExoPlayer, it will need to be migrated to `androidx.media3` (see [migration guide](https://developer.android.com/guide/topics/media/media3/getting-started/migration-guide) for guidance).

To do this, take over or modify the [dependabot PR](https://github.com/flutter/packages/pull/4427).

**Comment by emakar** [comment]
@camsim99 
hi!
this pr migrates exoplayer to media3 https://github.com/flutter/packages/pull/6535
