### ISSUE TITLE
Firebase database exception on permission denied

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter#13027]
## Steps to Reproduce

In Firebase when I access a path where I don't have sufficient permissions,
I get

```
[  +43 ms] W/RepoOperation(10726): setValue at /test_db/joinRequestCreate/hFWyZYmtgocsWs69TnpHXuEbBRv1/-Kyz7h7zFCbqxZKNrdOD failed: DatabaseError: Permission denied
```
as log output, but that's easy to miss. 

I think there should be a way to get an exception on the client side for permission denied

firebase_database plugin version 0.0.14

**Comment by Hixie** [comment]
cc @collinjackson

**Comment by collinjackson** [comment]
Catching crashes and reporting them as errors for this plugin is a reasonable developer expectation. 

I'd be happy to review pull requests for this functionality, if anyone has the time.

**Comment by kroikie** [comment]
@zoechi

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/942. Any further collaboration will be done there.
