### ISSUE TITLE
Pasting text in a TextField in an AlertDialog doesn't work

### ISSUE THREAD

**Issue by bramvbilsen** [flutter/flutter#13021]
Trying to paste text inside a `TextField` in an `AlertDialog` doesn't work. No text gets pasted.
This happends on my Galaxy S8+

```
Flutter • channel alpha • https://github.com/flutter/flutter.git
Framework • revision 4424892c79 (5 weeks ago) • 2017-10-10 16:45:11 -0700
Engine • revision 2a84f18c79
Tools • Dart 1.25.0-dev.11.0
```

**Comment by bramvbilsen** [comment]
I'm working with this code:
```
              new IconButton(
                icon: new Icon(Icons.person_add),
                onPressed: () => showDialog(
                  context: context,
                  child: new AlertDialog(
                    title: new Text("Add new friend"),
                    content: new TextField(
                      decoration: new InputDecoration(
                        labelText: "Friend ID"
                      ),
                      onChanged: (String text) {
                        friendIdInput = text;
                      },
                    ),
                    actions: <Widget>[
                      new FlatButton(
                        child: new Text("Cancel"),
                        onPressed: () => Navigator.pop(context),
                      ),
                      new FlatButton(
                        child: new Text("Add"),
                        onPressed: () => addFriend(friendIdInput),
                      )
                    ],
                  )
                ),
              ),
```

**Comment by Hixie** [comment]
Does it work outside of a dialog?

**Comment by bramvbilsen** [comment]
It does in every other `TextField` I have in my app so I assume it does.

**Comment by Hixie** [comment]
Very strange.

**Comment by bramvbilsen** [comment]
Is it working for you?

**Comment by Hixie** [comment]
I haven't tried it, but I trust that it's not working. I just can't think why it wouldn't work. I haven't tried to debug it yet.

**Comment by bramvbilsen** [comment]
I'll also try some different scenarios when I find the time. I'll keep you up to date!

**Comment by jason-simmons** [comment]
fwiw, I tried adding the `showDialog` code above to the sample app created by `flutter create`, and cut/copy/paste worked as expected within the dialog's text field.

(This was on a Moto G4 and a Google Pixel)

**Comment by HansMuller** [comment]
I've checked copy and paste with two different Android phones using this test case: https://gist.github.com/HansMuller/9b7e4a4f40000f4f54b29f853146e65d
```
// Checked with
// GT I9505 • ab139e2d • android-arm • Android 4.4.2 (API 19)
// N9137 • 49c16865 • android-arm • Android 8.1.0 (API 27)
// Nexus 5 • 05f0097ed007ad8c • android-arm • Android 5.1.1 (API 22)
```
It was also checked against a [Moto G4 and Google Pixel](https://github.com/flutter/flutter/issues/13021#issuecomment-344763004).

At this point, a year later, all appears to be well so I'm going to close this bug. If the test case still fails on a particular device, or if a different version of the test case fails, please reopen this bug.

**Comment by AngeloAvv** [comment]
@bramvbilsen have you solved the problem? I'm facing the same issue.
