### ISSUE TITLE
[CP] Avoid crash when backdrop filter is null for PlatformViews 

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#130290]
### Issue Link

https://github.com/flutter/flutter/issues/127095

### Commit Hash

01bb6af

### Target

beta

### PR Link

https://github.com/flutter/engine/pull/43528

### Changelog Description

Avoid crash when a null backdrop filter is applied to PlatformView

### Impacted Users

Flutter devs, end-customers

### Impact Description

App crash

### Workaround

No

### Risk

low

### Test Coverage

yes

### Validation Steps

Use the sample code in https://github.com/flutter/flutter/issues/127095#issuecomment-1592872318 to reproduce the crash and validate the fix.

**Comment by CaseyHillers** [comment]
@hellohuanlin  can you review this CP request? If it looks good to you, add the "cp: approved" label.

**Comment by CaseyHillers** [comment]
Adding "cp: approved" as the PR was approved by @hellohuanlin
