### ISSUE TITLE
View messed up in examples/flutter_gallery

### ISSUE THREAD

**Issue by kangwang1988** [flutter/flutter#13024]
## Enviroment
     iPhone6
     iOS10.3.3
## Codebase Commit
    flutter/examples/flutter_gallery
    e8aa40eddd3b91ba1a2d0c2c1e34db0f38e4290e [e8aa40e]
## Steps to Reproduce
    Launch the application and after some operations, the view is messed up.
    I made a screen recording which is available over youtube.
    https://youtu.be/iSOVdTdq60E
   
![img_3939](https://user-images.githubusercontent.com/817851/32817080-f80f2024-c9f6-11e7-9333-285f2ee9f5b6.png)

**Comment by eseidelGoogle** [comment]
@chinmaygarde this looks like some sort of skia font rendering corruption?

**Comment by eseidelGoogle** [comment]
Are you able to share your `flutter doctor` output?

**Comment by xster** [comment]
I can repro this too. Considering the iPhone and the use of scale transforms in `SectionTitle` of the demo, I'm going to dupe it into #12934

**Comment by kangwang1988** [comment]
[✓] Flutter (on Mac OS X 10.13.1 17B48, locale en-CN, channel alpha)
    • Flutter at /Users/kylewong/Codes/Flutter/flutter
    • Framework revision e8aa40eddd (4 weeks ago), 2017-10-17 15:42:40 -0700
    • Engine revision 7c4142808c
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /Users/kylewong/Library/Android/sdk
    • Platform android-26, build-tools 26.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.1, Build version 9B55
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.3)
    • Flutter plugin version 18.4
    • Dart plugin version 172.3968.27

**Comment by xster** [comment]
@kangwang1988 if my guess is right, you should be ok for now on Android or on an iOS simulator while we work on a fix.
