### ISSUE TITLE
Android Studio 3.0 with Flutter & Dart plugin not recognizing USB or virtual devices when clicking Play

### ISSUE THREAD

**Issue by tomnta** [flutter/flutter#13020]
## Steps to Reproduce

Run "Flutter Devices" in Windows 10 Command Prompt shows that a device is connected.

> flutter devices
> 1 connected device:
> SM N950U1 • ce06xxxxxxxx • android-arm • Android 7.1.1 (API 25)

However, pressing Run in Android Studio 3.x returns this error popup:

> No connected devices found; please connect a device, or see flutter.io/setup for getting started instructions.

https://flutter.io/setup/ guides the user to this link https://flutter.io/setup-windows/#android-setup

And that page has no directions on how to setup the IDE to recognize that you have a device attached or to have it work with the virtual device.

The same error window pops up when you select a virtual device and press Play in Android Studio.  However, pressing Play on an Android project works fine with virtual and USB devices.

## Logs

> Run your application with `flutter run` and attach all the log output.
> Run `flutter analyze` and attach any output of that command also.

N/A.  The command line tool works fine.  The Android Studio plugin has issues.

## Flutter Doctor

[√] Flutter (on Microsoft Windows [Version 10.0.14393], locale en-US, channel alpha)
    • Flutter at C:\Users\Tom\flutter
    • Framework revision e8aa40eddd (4 weeks ago), 2017-10-17 15:42:40 -0700
    • Engine revision 7c4142808c
    • Tools Dart version 1.25.0-dev.11.0

[√] Android toolchain - develop for Android devices (Android SDK 27.0.0)
    • Android SDK at C:\Users\Tom\AppData\Local\Android\sdk
    • Platform android-27, build-tools 27.0.0
    • Java binary at: F:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at F:\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

Flutter plugin version 19

**Comment by Hixie** [comment]
cc @devoncarew

**Comment by macfeaster** [comment]
Just curious, have you configured the Flutter plugin in IntelliJ under the Languages & Frameworks section? If this is not configured, Flutter will not be able to launch the app via Android Studio.

**Comment by pawelkw** [comment]
Same problem here. Same config as OP.

**Comment by mit-mit** [comment]
The Flutter IDE plugin is expected to show the exact same list of devices as `flutter devices` does. If they don't, then that a bug. I'm going to port this bug over to the intellij specific tracker.

**Comment by mit-mit** [comment]
This issue was moved to flutter/flutter-intellij#1525
