### ISSUE TITLE
[CP] Fix FlutterViewController retain cycle

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#130285]
### Issue Link

https://github.com/flutter/flutter/issues/126560

### Commit Hash

f329796

### Target

beta

### PR Link

https://github.com/flutter/engine/pull/43523

### Changelog Description

Fixes FlutterViewController retain cycle.

### Impacted Users

Flutter devs

### Impact Description

Flutter iOS Add to app experience memory leak.

### Workaround

No

### Risk

low

### Test Coverage

yes

### Validation Steps

The demo code in https://github.com/flutter/flutter/issues/126560

**Comment by CaseyHillers** [comment]
@LongCatIsLooong can you review this CP request? If it looks good to you, add the "cp: approved" label.
