### ISSUE TITLE
By integrating flutter into macos by product integration, the input fields in flutter do not work, but it is possible to type normally by running the flutter project input fields alone

### ISSUE THREAD

**Issue by ChinaFishNews** [flutter/flutter#130236]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Current environment 
flutter version: 2.10.3 
macos Version: 13.2.1 (22D68)

By integrating flutter into macos by product integration, 

    if (!_window.contentViewController) {
        _window.contentViewController = self.flutterVC;
    }
    [_window setFrame:windowRect display:YES animate:NO];
    [_window setAlphaValue:1.0];
    [_window orderFront:nil];
    _window.parentWindow = nil;

There is now an input field on the flutter view

### Expected results

can type normally in the input field

### Actual results

the input fields in flutter do not work，Typing doesn't show up，but it is possible to type normally by running the flutter project input fields alone

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @ChinaFishNews, you are using an older version of flutter. 

Kindly upgrade to the latest version of flutter stable (currently 3.10.5) to see if you still experience this issue. 

If you do, please provide a complete minimal reproducible code sample(preferably in a repo that we can clone), along with the updated output of flutter doctor -v so that we can investigate this issue. 

Thank you
