### ISSUE TITLE
an issue about hasData method.

### ISSUE THREAD

**Issue by normidar** [flutter/flutter#130200]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I am using FutureBuilder or StreamBuilder,
Some time I return null in my Stream or Future.

I return the `null` data, so hasData() should return true.

but now:
`bool get hasData => data != null;`

### Expected results

```
// return true if I return null in future
bool get hasData =>....;
```

### Actual results

if I return null in my future or stream it returned ture. 

async.dart: 281

### Code sample

<details><summary>Code sample</summary>

```dart
return StreamBuilder(
      stream: binder.getData(),
      builder: (context, snapshot) {
        Log.debug(() =>
            'data_single_matcher.dart path:${binder.getLogInfo()} data: ${snapshot.data}');
        if (snapshot.hasError) {
          final error = snapshot.error;
          print("DataSingleMatcherError:$error");
          return Center(child: Text(error.toString()));
        }
        if (snapshot.hasData) {
          if (snapshot.data == null) {
            Log.debug(() =>
                'data_single_matcher.dart path:${binder.getLogInfo()} has data but data is null');
          }
          final dataset = snapshot.data as T;
          return builder(context, dataset);
        } else {
          Log.debug(() =>
              'data_single_matcher.dart path:${binder.getLogInfo()} no data');
          return const Center(child: CircularProgressIndicator());
        }
      },
    );
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
% flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F82
    darwin-arm64, locale ja-JP)
    ! Warning: `dart` on your path resolves to
      /opt/homebrew/Cellar/dart/2.18.6/libexec/bin/dart, which is not
      inside your current Flutter SDK checkout at
      /Users/user/Documents/flutter. Consider adding
      /Users/user/Documents/flutter/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK
    version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] Android Studio (version 2022.1)
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
[✓] VS Code (version 1.80.0)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by dam-ease** [comment]
Hi @normidar. Thanks for filing this issue. Can you provide more information on this issue:

- What response are you getting instead of the expected true? Is there an error log, if yes, can you attach it to the issue?
- Can you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn't contain any third party plugin or complex reproduction code such that I'm able to reproduce?

Thank you

**Comment by normidar** [comment]
I found a solution: Use `connectionState` to check the data is finished.

So I will close this issue.

---

https://github.com/flutter/flutter/blob/7decd77d0e41eb00b1299949358f5a2b2e11dcb1/packages/flutter/lib/src/widgets/async.dart#L281

But I still wondering about it. 
Why not `bool get hasData => connectionState != ConnectionState.waiting;`?
