### ISSUE TITLE
Black screen on Android Emulator

### ISSUE THREAD

**Issue by itsJoKr** [flutter/flutter#13029]
## Steps to Reproduce

Freshly installed Android Studio. I tried to run my app on Android emulator but my app fails to render and I get a black screen. When I connect my real device, everything works fine. iOS simulator also works fine. Also, the default "new project" flutter app works fine on Android emulator! Tested on Android O and M emulators.

When the app is opening, I get this black box on the bottom-left corner for half a second and after that, the whole screen goes black. If I keep clicking on the screen, it often keeps flashing again with this same black box.

<img width="404" alt="screen shot 2017-11-15 at 17 30 30" src="https://user-images.githubusercontent.com/11093480/32851012-1cf018a2-ca34-11e7-9af5-65e69072784d.png">

## Logs

There are no any errors in `flutter run` logs. But when the screen is flashing I get this log, not sure if helpful:  `D/skia    ( 4813): OpList failed to instantiate.`

Here are the verbose logs: https://hastebin.com/ehojeqitil.sql

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.12.6 16G1036, locale en-US, channel alpha)
    • Flutter at /Users/jokr/Documents/flutter/flutter
    • Framework revision e8aa40eddd (4 weeks ago), 2017-10-17 15:42:40 -0700
    • Engine revision 7c4142808c
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at /Users/jokr/Library/Android/sdk
    • Platform android-27, build-tools 27.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.1, Build version 9B55
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.2.5)
    • Flutter plugin version 19.0
    • Dart plugin version 172.4343.25

[✓] Connected devices
    • Android SDK built for x86 64 • emulator-5554                        • android-x64 • Android 6.0 (API 23) (emulator)
    • iPhone 7                     • A4A35184-4527-499F-B58A-66D0EF65A193 • ios         • iOS 11.1 (simulator)
    • iPhone X                     • E39C9791-6662-43FE-B77F-4DFACEECBEE3 • ios         • iOS 11.1 (simulator)

EDIT: Here's the repo if anyone is interested: https://github.com/itsJoKr/iOS4Android

**Comment by itsJoKr** [comment]
Fixed by adding `--enable-software-rendering`. Found here:  https://github.com/flutter/flutter/issues/12428

**Comment by eseidelGoogle** [comment]
Using --enable-software-rendering should not be required.

We've had many reports like this.  e.g. https://github.com/flutter/flutter/issues/11947 https://github.com/flutter/flutter/issues/11484 https://github.com/flutter/flutter/issues/10617 

@741g  from the android emulator team was able to help us with a previous time this occurred.  I thought we had fixed all these, but presumably not.

I'm not sure how we should be debugging these in the wild?

**Comment by 741g** [comment]
This could be a new, different breakage. It doesn't look like a black screen error, rather something else is going wrong. I'll look into it.

**Comment by eseidelGoogle** [comment]
The "OpList fails to instantiate" error could just be a Skia regression?  See also https://github.com/flutter/flutter/issues/12980 and https://github.com/flutter/flutter/issues/13018 which mention that error.  FYI @chinmaygarde

**Comment by itsJoKr** [comment]
Just to add. Usually, these three lines will be logged many times, especially when I try clicking and then it starts to flash.

[        ] D/EGL_emulation( 4325): eglMakeCurrent: 0xa1299b00: ver 2 0 (tinfo 0xad08b000)
[        ] D/skia    ( 4325): OpList failed to instantiate.
[  +15 ms] I/chatty  ( 4325): uid=10083(u0_a83) gpu_thread identical 2 lines

**Comment by 741g** [comment]
The eglMakeCurrent ver there gives us a clue as to which GLES version is used on the emulator; it's not indicative of an error in the emulator driver.

OpList failed to instantiate, however, could be.

**Comment by brianosman** [comment]
Wondering if this was before/after https://github.com/flutter/engine/commit/e03cab39d764c2a15c341b4a8576352bb878263f was landed in the engine?

**Comment by eseidelGoogle** [comment]
The `flutter doctor` output in the original report shows using an flutter/engine which is about a month old.  flutter/engine@7c4142808c

**Comment by itsJoKr** [comment]
@brianosman @eseidel 

I've switched the channel to master and upgraded flutter. I don't see black screen issue anymore on the same project.

**Comment by eseidelGoogle** [comment]
Fantastic!
