### ISSUE TITLE
[CP] Pick fix for impeller clips in to 3.13 beta

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#130294]
### Issue Link

#130084

### Commit Hash

flutter/engine@06c9362

### Target

beta

### PR Link

https://github.com/flutter/engine/pull/43534

### Changelog Description

See https://github.com/flutter/flutter/issues/130149

### Impacted Users

https://github.com/flutter/flutter/issues/130149

### Impact Description

https://github.com/flutter/flutter/issues/130149

### Workaround

None.

### Risk

low

### Test Coverage

yes

**Comment by itsjustkevin** [comment]
@bdero can you review this CP request? If it looks good to you, add the "cp: approved" label.

**Comment by bdero** [comment]
LGTM
