### ISSUE TITLE
[Android][add_to_app] Limited Support for Sharing the Same Engine Across Multiple FlutterViews

### ISSUE THREAD

**Issue by 0xZOne** [flutter/flutter#130235]
Flutter allows users to reuse the same engine with multiple FlutterActivity/FlutterFragment (or FlutterView) through the way of attaching/detaching. 

This feature is very useful in the *add_to_app* scenario, where business logic can share data across different pages(FlutterView) by reusing the same engine.

However, Flutter's support for reusing the same engine with multiple FlutterViews is not very good. 

- [x] It does not support users to customize the timing of attaching FlutterActivity/FlutterFragment to the engine.
- [x] ~~Attaching a new Flutter to an engine that has already been attached by another FlutterView will cause issues.~~

<details><summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel main, 3.12.0-15.0.pre.59, on macOS 13.1 22C65 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.12.0-15.0.pre.59 on channel main at /Users/zero/fvm/versions/main
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5345221701 (3 hours ago), 2023-07-09 21:01:34 -0400
    • Engine revision 09c6ce4243
    • Dart version 3.1.0 (build 3.1.0-285.0.dev)
    • DevTools version 2.25.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/zero/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_SDK_ROOT = /Users/zero/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • zero的iPhone (mobile) • 50131fb4dcef9d96405ec953e272bd5c24468370 • ios            • iOS 16.2 20C65
    • macOS (desktop)      • macos                                    • darwin-x64     • macOS 13.1 22C65 darwin-x64
    • Chrome (web)         • chrome                                   • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by johnmccutchan** [comment]
Hey there,

I have some questions about what is motiving your PRs here:

* Re https://github.com/flutter/engine/pull/43595 - What benefits are you trying to achieve by delaying attaching the `Engine` to a `FlutterView`? Is there a performance problem with all of the views being automatically attached?

* Re https://github.com/flutter/engine/pull/43487 - This PR seems to be changing the semantics of our API and not allowing more than 1 FlutterView to be attached to an engine at a given time.

**Comment by 0xZOne** [comment]
> Hey there,
> 
> I have some questions about what is motiving your PRs here:
> 
> * Re [Enabling the host application to control the timing of attaching the |FlutterView| to the engine engine#43595](https://github.com/flutter/engine/pull/43595) - What benefits are you trying to achieve by delaying attaching the `Engine` to a `FlutterView`? Is there a performance problem with all of the views being automatically attached?

In the scenario where multiple FlutterViews reuse the same engine, sometimes we may not want to attach the engine immediately when |onCreateView|. Because the FlutterView may not be the one we want to attach.

Consider the following scenario: A native page contains multiple tabs, and each tab is a FlutterFragment. During initialization, FlutterFragments of different tabs are created almost simultaneously, but only the one that needs to be displayed currently requires attachment to the engine, while the others need to be attached only when they receive the |onResume| callback.

> * Re [Detaches the previous |FlutterView| from the shared |FlutterEngine| before attaching a new one engine#43487](https://github.com/flutter/engine/pull/43487) - This PR seems to be changing the semantics of our API and not allowing more than 1 FlutterView to be attached to an engine at a given time.

You are right. Only one FlutterView will be attached to the engine at a time. However, in order to facilitate the sharing of state in dart between multiple FlutterViews, we need to reuse the engine. In other words, a new FlutterView may attach to the engine at any time, and detach the previously attached FlutterView on the engine.

**Comment by 0xZOne** [comment]
In add-to-app scenarios, it is common for multiple FlutterViews to reuse a single engine, for example, [FlutterBoost](https://github.com/alibaba/flutter_boost/).

**Comment by johnmccutchan** [comment]
> > Hey there,
> > I have some questions about what is motiving your PRs here:
> > 
> > * Re [Enabling the host application to control the timing of attaching the |FlutterView| to the engine engine#43595](https://github.com/flutter/engine/pull/43595) - What benefits are you trying to achieve by delaying attaching the `Engine` to a `FlutterView`? Is there a performance problem with all of the views being automatically attached?
> 
> In the scenario where multiple FlutterViews reuse the same engine, sometimes we may not want to attach the engine immediately when |onCreateView|. Because the FlutterView may not be the one we want to attach.
> 

This scenario makes sense to me as one we may want to support.

> > * Re [Detaches the previous |FlutterView| from the shared |FlutterEngine| before attaching a new one engine#43487](https://github.com/flutter/engine/pull/43487) - This PR seems to be changing the semantics of our API and not allowing more than 1 FlutterView to be attached to an engine at a given time.
> 
> You are right. Only one FlutterView will be attached to the engine at a time. However, in order to facilitate the sharing of state in dart between multiple FlutterViews, we need to reuse the engine. In other words, a new FlutterView may attach to the engine at any time, and detach the previously attached FlutterView on the engine.

Flutter wants to preserve the ability to have more than one FlutterView attached to a FlutterEngine. It seems like you could achieve your goal of only having one View attached to an engine manually inside your application code.

**Comment by 0xZOne** [comment]
> > > Hey there,
> > > I have some questions about what is motiving your PRs here:
> > > 
> > > * Re [Enabling the host application to control the timing of attaching the |FlutterView| to the engine engine#43595](https://github.com/flutter/engine/pull/43595) - What benefits are you trying to achieve by delaying attaching the `Engine` to a `FlutterView`? Is there a performance problem with all of the views being automatically attached?
> > 
> > 
> > In the scenario where multiple FlutterViews reuse the same engine, sometimes we may not want to attach the engine immediately when |onCreateView|. Because the FlutterView may not be the one we want to attach.
> 
> This scenario makes sense to me as one we may want to support.
> 
That's fantastic! 👍 

> > > * Re [Detaches the previous |FlutterView| from the shared |FlutterEngine| before attaching a new one engine#43487](https://github.com/flutter/engine/pull/43487) - This PR seems to be changing the semantics of our API and not allowing more than 1 FlutterView to be attached to an engine at a given time.
> > 
> > 
> > You are right. Only one FlutterView will be attached to the engine at a time. However, in order to facilitate the sharing of state in dart between multiple FlutterViews, we need to reuse the engine. In other words, a new FlutterView may attach to the engine at any time, and detach the previously attached FlutterView on the engine.
> 
> Flutter wants to preserve the ability to have more than one FlutterView attached to a FlutterEngine. It seems like you could achieve your goal of only having one View attached to an engine manually inside your application code.

To some extent, yes.
