### ISSUE TITLE
flutter app crash when pop i'm using flutter_google_maps

### ISSUE THREAD

**Issue by rasheed-ct** [flutter/flutter#130326]
i'm working on a map screen map screen working fine but when i pop app crash 

 

 google map widget

     `GoogleMap(
                  compassEnabled: true,
                  mapType: MapType.normal,

                  onTap: (LatLng latLang) {
                    print(latLang);
                  },
                  initialCameraPosition: CameraPosition(
                    target: controller.initialLocation.value,
                    zoom: 17,
                  ),
                  // markers: controller.markers!,
                  onMapCreated: (GoogleMapController ctrl) {
                    // controller.generateMarkers();
                  },
                  markers: controller.markers

              )`

error: 
   
   `Caused by: java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=com.example.meta_comm, sha256=[0cc55f53b115aaec07d064350e2563d838420a3725f4f650921500be03cc6f90], atk=false, ver=232316040.true (go/gsrlt)
W/MobStoreFlagStore(31444): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
W/MobStoreFlagStore(31444): 	at android.os.Parcel.createException(Parcel.java:2357)
W/MobStoreFlagStore(31444): 	at android.os.Parcel.readException(Parcel.java:2340)
W/MobStoreFlagStore(31444): 	at android.os.Parcel.readException(Parcel.java:2282)
W/MobStoreFlagStore(31444): 	at fe.c(:com.google.android.gms.dynamite_mapsdynamite@232316040@23.23.16 (150700-0):2)
W/MobStoreFlagStore(31444): 	at ry.a(:com.google.android.gms.dynamite_mapsdynamite@232316040@23.23.16 (150700-0):4)
W/MobStoreFlagStore(31444): 	at jl.e(:com.google.android.gms.dynamite_mapsdynamite@232316040@23.23.16 (150700-0):2)
W/MobStoreFlagStore(31444): 	at kj.t(:com.google.android.gms.dynamite_mapsdynamite@232316040@23.23.16 (150700-0):2)
W/MobStoreFlagStore(31444): 	at kj.u(:com.google.android.gms.dynamite_mapsdynamite@232316040@23.23.16 (150700-0):3)
W/MobStoreFlagStore(31444): 	at kj.e(:com.google.android.gms.dynamite_mapsdynamite@232316040@23.23.16 (150700-0):2)
W/MobStoreFlagStore(31444): 	at kn.handleMessage(:com.google.android.gms.dynamite_mapsdynamite@232316040@23.23.16 (150700-0):78)
W/MobStoreFlagStore(31444): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/MobStoreFlagStore(31444): 	at android.os.Looper.loop(Looper.java:223)
W/MobStoreFlagStore(31444): 	at android.os.HandlerThread.run(HandlerThread.java:67)`

2nd error

 `FATAL EXCEPTION: GLThread 914
E/AndroidRuntime(31444): Process: com.example.meta_comm, PID: 31444
E/AndroidRuntime(31444): java.lang.NullPointerException: Attempt to get length of null array
E/AndroidRuntime(31444): 	at java.nio.ByteBufferAsIntBuffer.put(ByteBufferAsIntBuffer.java:122)
E/AndroidRuntime(31444): 	at com.google.maps.api.android.lib6.gmm6.vector.gl.buffer.n.i(:com.google.android.gms.dynamite_mapsdynamite@232316040@23.23.16 (150700-0):2)
E/AndroidRuntime(31444): 	at com.google.maps.api.android.lib6.gmm6.vector.gl.buffer.n.d(:com.google.android.gms.dynamite_mapsdynamite@232316040@23.23.16 (150700-0):3)
E/AndroidRuntime(31444): 	at com.google.maps.api.android.lib6.gmm6.vector.gl.drawable.d.s(:com.google.android.gms.dynamite_mapsdynamite@232316040@23.23.16 (150700-0):3)
E/AndroidRuntime(31444): 	at com.google.maps.api.android.lib6.gmm6.vector.gl.drawable.ao.s(:com.google.android.gms.dynamite_mapsdynamite@232316040@23.23.16 (150700-0):9)
E/AndroidRuntime(31444): 	at com.google.maps.api.android.lib6.gmm6.vector.bx.s(:com.google.android.gms.dynamite_mapsdynamite@232316040@23.23.16 (150700-0):29)
E/AndroidRuntime(31444): 	at com.google.maps.api.android.lib6.gmm6.vector.bq.b(:com.google.android.gms.dynamite_mapsdynamite@232316040@23.23.16 (150700-0):157)
E/AndroidRuntime(31444): 	at com.google.maps.api.android.lib6.gmm6.vector.at.run(:com.google.android.gms.dynamite_mapsdynamite@232316040@23.23.16 (150700-0):48)
I/Process (31444): Sending signal. PID: 31444 SIG: 9
Lost connection to device. `

please help **me**

**Comment by dam-ease** [comment]
Hi @rasheed-ct. Thanks for filing this issue. Do you mean to pop to a previous screen or out of the app completely? Please can you provide more information on this:
More specifically, please provide the information indicated below:

- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of flutter doctor -v
- The output of your flutter run -v (might be quite long, you can attach a .txt file)
- Reproduction steps

Thank you.
