### ISSUE TITLE
Better detection of missing dependencies before trying to run commands

### ISSUE THREAD

**Issue by Lewiscowles1986** [flutter/flutter#130308]
## Command

```
flutter build macos --release
```

## Steps to Reproduce

1. follow guide from [Building on MacOS](https://appflowy.gitbook.io/docs/essential-documentation/contribute-to-appflowy/software-contributions/environment-setup/building-on-macos) on an arm64 Apple
2. upon running `cargo make --profile production-mac-arm64 appflowy` (triggers above linked command)

## Logs

<details>
<summary>ProcessException: Process exited abnormally:
xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH Command: /usr/bin/arch, OS error code: 72
</summary>

```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:125:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:278:19)
<asynchronous suspension>
#2      XcodeProjectInterpreter.getInfo (package:flutter_tools/src/ios/xcodeproj.dart:321:30)
<asynchronous suspension>
#3      buildMacOS (package:flutter_tools/src/macos/build_macos.dart:96:41)
<asynchronous suspension>
#4      BuildMacosCommand.runCommand (package:flutter_tools/src/commands/build_macos.dart:62:5)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
<asynchronous suspension>
#11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```

```
[32m[✓][39m Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F82 darwin-arm64, locale en-GB)
    [32m•[39m Flutter version 3.10.5 on channel stable at /opt/homebrew/Caskroom/flutter/3.10.5/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 796c8ef792 (4 weeks ago), 2023-06-13 15:51:02 -0700
    [32m•[39m Engine revision 45f6e00911
    [32m•[39m Dart version 3.0.5
    [32m•[39m DevTools version 2.23.1

[31m[✗][39m Android toolchain - develop for Android devices
    [31m✗[39m Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[33m[!][39m Xcode - develop for iOS and macOS
    [31m✗[39m Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    [32m•[39m CocoaPods version 1.12.1

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[32m[✓][39m VS Code (version 1.80.0)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[32m[✓][39m Connected device (2 available)
    [32m•[39m macOS (desktop) • macos  • darwin-arm64   • macOS 13.4.1 22F82 darwin-arm64
    [32m•[39m Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.198

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 3 categories.

```

</details>

## Flutter Application Metadata

**Type**: app
**Version**: 0.2.5
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 135454af32477f815a7525073027a3ff9eff1bfd

### Plugins

app_links-3.4.3
appflowy_backend
connectivity_plus-4.0.1
device_info_plus-9.0.1
file_picker-5.3.1
flowy_infra_ui
flowy_infra_ui_web
flutter_plugin_android_lifecycle-2.0.15
fluttertoast-8.2.2
hotkey_manager-0.1.7
integration_test
package_info_plus-4.0.1
path_provider-2.0.15
path_provider_android-2.0.27
path_provider_foundation-2.2.3
path_provider_linux-2.1.11
path_provider_windows-2.1.6
rich_clipboard-1.0.1
rich_clipboard_android-1.0.1
rich_clipboard_ios-1.0.0
rich_clipboard_linux-1.0.1
rich_clipboard_macos-1.0.1
rich_clipboard_web-1.0.2
rich_clipboard_windows-1.0.2
screen_retriever-0.1.6
shared_preferences-2.1.1
shared_preferences_android-2.1.4
shared_preferences_foundation-2.2.2
shared_preferences_linux-2.2.0
shared_preferences_web-2.1.0
shared_preferences_windows-2.2.0
sign_in_with_apple-4.3.0
sign_in_with_apple_web-1.0.1
url_launcher-6.1.11
url_launcher_android-6.0.34
url_launcher_ios-6.1.4
url_launcher_linux-3.0.5
url_launcher_macos-3.0.5
url_launcher_web-2.0.17
url_launcher_windows-3.0.6
webview_flutter-4.2.1
webview_flutter_android-3.7.1
webview_flutter_wkwebview-3.4.4
window_manager-0.3.4

So this was not my first error. I Had to also perform the following in order to get the guide to work

```
brew install cocoapods
brew install flutter
```

**Comment by huycozy** [comment]
Hi @Lewiscowles1986 
I wonder if this issue should be reported to AppFlowy to better support there. If you think this is a Flutter bug or feature request, please try to provide information indicated in the appropriate template so that we can address this issue properly (See appropriate template: [Report a bug](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml), [Feature request](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=3_feature_request.yml)). (The issue should be reproducible with minimal sample code)

Also, looking at the exception, it seems you have more than one XCode version on your machine. Please try [this](https://stackoverflow.com/a/72423768/5921933) if it works for your case.

**Comment by Lewiscowles1986** [comment]
Ah I apologize, I literally used the link the CLI generated, and did not give a second thought to the URL 😊
