### ISSUE TITLE
[Impeller] Android text magnifier not offsetting correctly with coverage hint optimization.

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#130355]
~The EntityPass subpass coverage computation as well as the Aiks bounds tracking do not account for how subpass matrix filters modify the coverage of subpasses.~

@jason-simmons first noticed this problem in the form of the Android material text magnifier displaying at the wrong offset.

~I added a minimal repro for the underlying issues here: https://github.com/flutter/engine/pull/43484~

**Comment by bdero** [comment]
So the problems I'm describing in this issue _do_ exist, but they're not currently manifesting the noticeable issue on the Android magnifier widget.

I investigated this more deeply and discovered it's actually a behavioral issue with the implementation of the Matrix filter itself. So I renamed this issue to focus on the actual bug as opposed to a prospective solutions.

**Comment by chinmaygarde** [comment]
Cross referencing a duplicate https://github.com/flutter/flutter/issues/131182 here that may have another test case.
