### ISSUE TITLE
Hello darshankawar,

### ISSUE THREAD

**Issue by vidhi002** [flutter/flutter#130383]
Hello darshankawar,

I am attaching the screenshots you requested. I will test with latest master in a while.

Thanks!

![WhatsApp Image 2021-01-15 at 10 13 50 (2)](https://user-images.githubusercontent.com/19885531/104732070-6bd84080-571b-11eb-9e4b-aa17a9aac5be.jpeg)
![WhatsApp Image 2021-01-15 at 10 13 50 (1)](https://user-images.githubusercontent.com/19885531/104732075-6d096d80-571b-11eb-8c31-e9d001f9dff2.jpeg)
![WhatsApp Image 2021-01-15 at 10 13 50](https://user-images.githubusercontent.com/19885531/104732076-6d096d80-571b-11eb-953d-396fe5b7c5b4.jpeg)
![WhatsApp Image 2021-01-15 at 10 13 51](https://user-images.githubusercontent.com/19885531/104732077-6e3a9a80-571b-11eb-91d1-7968575d8c59.jpeg)

_Originally posted by @mwolffalonso in https://github.com/flutter/flutter/issues/73874#issuecomment-760939004_

**Comment by danagbemava-nc** [comment]
Hi @vidhi002, `share` has been deprecated. `share_plus` is the recommended plugin to use. If you are facing any issues using `share_plus`, kindly report this on their repo.

Closing from here as this is not a flutter issue.

Thank you
