### ISSUE TITLE
Add Decoration to ButtonStyleButton's styling

### ISSUE THREAD

**Issue by williamhjcho** [flutter/flutter#130335]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Hello 👋 

For our specific use case, we wanted to add a (radial) gradient background to the button.

### What we tried

Using the button's `child` property required us to both remove the button's paddings (otherwise it doesn't touch the button's edges) and to expand it internally (which was causing layout issues).

### What we had to do to make it work

- Copied the whole `ButtonStyleButton` implementation, 
- replaced this [`ConstrainedBox`](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/button_style_button.dart#L380) for a `Container` 
- Created a subclass of `ButtonStyle` with an added `final MaterialStateProperty<Decoration?>? decoration` property (when the button is disabled, the gradient changes color as well)
- added a `resolve`d `effectiveDecoration` & insert it to the `Container` above

### Proposal

The existing `ButtonStyleButton` & `ButtonStyle` already allow many configuration options.

Suggested proposals would be to add a dedicated `Gradient` property, or to be more generic and use a `Decoration` property instead.
One important note on my solution: since the `Container` is above `Material`, which handles the clipping behavior, the `Decoration` might also need special handling to the resolved `shape`.
One simple way would be just to check for an existing resolved decoration and do conditional widget wrapping(s)?

**Comment by HansMuller** [comment]
Supporting ButtonStyle.decoration or more likely ButtonStyle.boxDecoration, is a good idea.  Support appears to be coming for ImageDecoration.lerp, https://github.com/flutter/flutter/pull/130533, which would make BoxDecoration.lerp (and consequently ButtonStyle.lerp) DTRT when there was an image specified.

**Comment by TahaTesser** [comment]
While this is being fixed, you can create a gradient style button like this without copying `ButtonStyleButton` implementation.

![Screenshot 2023-10-27 at 13 59 05](https://github.com/flutter/flutter/assets/48603081/45b60493-e60d-4e39-9ef3-fa6b19baa570)



```dart
class Example extends StatelessWidget {
  const Example({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ElevatedButton(
          clipBehavior: Clip.antiAlias,
          style: ElevatedButton.styleFrom(
            padding: EdgeInsets.zero,
          ),
          onPressed: () {},
          child: Ink(
            decoration: const BoxDecoration(
              gradient: LinearGradient(
                colors: [Colors.cyan, Colors.yellow],
                begin: Alignment.topLeft,
                end: Alignment.bottomRight,
              ),
            ),
            child: Container(
              height: 48.0,
              width: 120.0,
              alignment: Alignment.center,
              child: const Text(
                'Button',
                style: TextStyle(color: Colors.white),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

```

**Comment by HansMuller** [comment]
Fixed in https://github.com/flutter/flutter/pull/142762
