### ISSUE TITLE
error in url_launcher_ios-6.1.4/ios/Classes/FLTURLLauncherPlugin.h:4:8

### ISSUE THREAD

**Issue by MTEV** [flutter/flutter#130338]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

url_launcher: ^6.1.8

and last version same issue 

just. run

### Expected results

Failed to build iOS app
Could not build the precompiled application for the device.
Lexical or Preprocessor Issue (Xcode): 'Flutter/Flutter.h' file not found
/Users/dev.my/.pub-cache/hosted/pub.dev/url_launcher_ios-6.1.4/ios/Classes/FLTURLLauncherPlugin.h:4:8

Lexical or Preprocessor Issue (Xcode): 'Flutter/Flutter.h' file not found
/Users/dev.my/.pub-cache/hosted/pub.dev/url_launcher_ios-6.1.4/ios/Classes/messages.g.m:7:8

Error launching application on my’s iPhone.

### Actual results

error
in url_launcher_ios-6.1.4/ios/Classes/FLTURLLauncherPlugin.h:4:8

### Code sample

flutter run

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.0.1 22A400 darwin-x64, locale
    en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.80.0)
[✓] Connected device (3 available)
[✓] Network resources

**Comment by huycozy** [comment]
Hi @MTEV 
Can you please share your `pubspec.yaml` and `pubspec.lock` file content? And please confirm if you also have the same result when running [url_launcher_ios sample code](https://github.com/flutter/packages/tree/main/packages/url_launcher/url_launcher_ios/example).
