### ISSUE TITLE
GTK 3.0 development libraries are required for Linux development on debian

### ISSUE THREAD

**Issue by levis-creator** [flutter/flutter#130343]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I have run this command after manual installation of flutter in debian

### Actual results

I followed with this issue https://github.com/flutter/flutter/issues/63749#top over here but all dependency are already  installed when i run this command  `sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev`

the output i get is:

 `Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
clang is already the newest version (1:14.0-55.6).
cmake is already the newest version (3.26.4-4).
ninja-build is already the newest version (1.11.1-1).
pkg-config is already the newest version (1.8.1-1).

libgtk-3-dev is already the newest version (3.24.37-2).

liblzma-dev is already the newest version (5.4.1-0.2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
`

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>

`[✓] Flutter (Channel stable, 3.10.5, on Debian GNU/Linux trixie/sid
    6.3.0-2-amd64, locale en_US.UTF-8)
    • Flutter version 3.10.5 on channel stable at /home/black/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (4 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/black/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at:
      /home/black/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.445
      9.24.2221.10121639/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✗] Linux toolchain - develop for Linux desktop
    • Debian clang version 14.0.6
    • cmake version 3.26.4
    • ninja version 1.11.1
    • pkg-config version 0.29.2
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install
      libgtk-3-dev)

[✓] Android Studio (version 2022.2)
    • Android Studio at
      /home/black/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.445
      9.24.2221.10121639
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.68.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Debian GNU/Linux trixie/sid
      6.3.0-2-amd64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.`</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by stuartmorgan** [comment]
What does each of the following return?
```sh
pkg-config --exists gtk+-3.0
pkg-config --exists glib-2.0
pkg-config --exists gio-2.0
```

**Comment by levis-creator** [comment]
after doing a system update and upgrade they are not showing any output


> What does each of the following return?
> 
> ```shell
> pkg-config --exists gtk+-3.0
> pkg-config --exists glib-2.0
> pkg-config --exists gio-2.0
> ```

After doing an system update and upgrade they are not showing  showing any output

**Comment by stuartmorgan** [comment]
But what are the return values of the commands? (I.e., `$?` after each one)

**Comment by levis-creator** [comment]
Hi just reinstalled flutter after a dist_upgrade and its working without any issue

**Comment by levis-creator** [comment]
> But what are the return values of the commands? (I.e., `$?` after each one)

greetings again i have just reinstalled flutter after `apt dist-upgrade` and it is working finely, thank you very much for taking your time to respond to my troubles
