### ISSUE TITLE
How to implement download image from Firebase storage url in flutter web?

### ISSUE THREAD

**Issue by donuthappy** [flutter/flutter#130320]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

```
final islandRef = storageRef.child("images/island.jpg");

try {
  const oneMegabyte = 1024 * 1024;
  final Uint8List? data = await islandRef.getData(oneMegabyte);
  // Data for "images/island.jpg" is returned, use this as needed.
} on FirebaseException catch (e) {
  // Handle any errors.
}
```
I tried but didn't work well.

### Proposal

**_Error: XMLHttpRequest error._**
I got error like this.

**Comment by danagbemava-nc** [comment]
See this section of the firebase_storage_web documentation https://pub.dev/packages/firebase_storage_web#downloading-files-with-getdata. 

Closing from here as this is not a flutter issue. If you run into any more issues with firebase, please report it on their repo. 

Thank you
