### ISSUE TITLE
When sharing multiple images and also a text to whatsapp the text it´s duplicated in all images being shared #73874

### ISSUE THREAD

**Issue by vidhi002** [flutter/flutter#130381]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

When sharing multiple images and also a text to whatsapp the text it´s duplicated in all images being shared #73874

### Proposal

When sharing multiple images and also a text to whatsapp the text it´s duplicated in all images being shared #73874

**Comment by danagbemava-nc** [comment]
Hi @vidhi002, `share` has been deprecated. `share_plus` is the recommended plugin to use. If you are facing any issues using `share_plus`, kindly report this on their repo. 

Closing from here as this is not a flutter issue. 

Thank you
