### ISSUE TITLE
ManualResetWaitableEventTest.Timeouts in FXL is time sensitive.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#13037]
This causes failures on the Window buildbot. Example of such a failure is https://uberchromegw.corp.google.com/i/client.flutter/builders/Windows%20Engine/builds/929/steps/Test%20FXL/logs/stdio

**Comment by goderbauer** [comment]
Closing as dup of https://github.com/flutter/flutter/issues/13654.
