### ISSUE TITLE
hey, any fix on this issues ? im still getting the issues (when sharing multiple image the text also duplicated, and on telegram is not showing any text) using share either share_plus package. any help will highly appreciated, thankyou.

### ISSUE THREAD

**Issue by vidhi002** [flutter/flutter#130382]
hey, any fix on this issues ? im still getting the issues (when sharing multiple image the text also duplicated, and on telegram is not showing any text) using share either share_plus package. any help will highly appreciated, thankyou.

_Originally posted by @linxkaa in https://github.com/flutter/flutter/issues/73874#issuecomment-882369779_

**Comment by darshankawar** [comment]
@vidhi002 
Closing based on https://github.com/flutter/flutter/issues/130383#issuecomment-1631954181
