### ISSUE TITLE
When the screen contains emojis, the text font becomes bold.

### ISSUE THREAD

**Issue by gjrjf** [flutter/flutter#130477]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. All you have to do is include the emoji on the screen.
2. Then all the text fonts on the screen become bold (bold).
3. It only happens on iOS.

The first screen shot is what I intend.
However, problems arise when users use emojis.

A new Flutter version came out, but we haven't been using it for 2 months. because of this problem

### Expected results

Normal, font thickness as I developed

### Actual results

Depending on whether there are bold letters or emojis, the font thickness will continue to change.
It really hurts the user experience.

### Code sample

<details><summary>Code sample</summary>

```dart
Text(
  'some.text',
  style: TextStyle(
      color: Color.fromRGBO(168, 168, 168, 1),
      letterSpacing: ScreenUtility().width(-0.75),
      fontSize: ScreenUtility().setSp(15),
      fontWeight: FontWeight.w500
  ),
)
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![IMG_0122](https://github.com/flutter/flutter/assets/19974022/57de1355-9608-441b-85b0-8626ce195a6d)
![IMG_0123](https://github.com/flutter/flutter/assets/19974022/b5dcbf27-4912-45e7-9769-07feda109b8e)

https://github.com/flutter/flutter/assets/19974022/cae2860b-3c55-4d22-85cd-4e4ebe65d7d5

</details>

### Logs

<details><summary>Logs</summary>

```console
There are no logs.
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.3.1 22E261 darwin-x64, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
[✓] VS Code (version 1.73.0)
[✓] Connected device (3 available)
[✓] Network resources

```

</details>

**Comment by danagbemava-nc** [comment]
Hi @gjrjf, this was initially reported in https://github.com/flutter/flutter/issues/126514 and has since been fixed on the beta/master channels.
 
It seems like the change is not possible to CP into the stable branch which is why it has not been done. See https://github.com/flutter/flutter/issues/126514#issuecomment-1592315132. 

You will either need to switch to the beta/master channels or disable impeller until the next stable release. See https://github.com/flutter/flutter/issues/126514#issuecomment-1592324167

Closing from here as this has already been fixed on the beta/master channels. 

Thank you

**Comment by keemeesuu** [comment]
3.10.6 is the same issue 🤢

**Comment by im-x** [comment]
3.10.6 is the same issue
