### ISSUE TITLE
Update Flutter release.yml configuration

### ISSUE THREAD

**Issue by itsjustkevin** [flutter/flutter#130432]
As labeling has changed through the new triage process, our release.yml file needs to be updated to support automated release notes.

**Comment by itsjustkevin** [comment]
@HansMuller we have the `f: material` and `framework` label.  For automated release notes:

1. Should these be separate categories?
2. If so, for cases where both labels are present, should material take precedence?

**Comment by HansMuller** [comment]
The `f: material` label is used for the Material library, usually in conjunction with `framework`. The `framework` label applies to everything else. So (yes) `f: material` should take precedence.
