### ISSUE TITLE
Unknown cmd bug I reinstalled my flutter but nothing change

### ISSUE THREAD

**Issue by asbe12** [flutter/flutter#130498]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

For one reason I decide to reinstall my Android Studio Because I was struggling to create new dart project in there

So I reinstall and It happen Idk what should I do

### Expected results

If someone can solve this problem or did happen to him/her please check it out 

### Actual results

When I write on cmd flutter doctor it is happening 

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

C:\src\flutter\bin>flutter doctor

Oops; flutter has exited unexpectedly: "FileSystemException: Exists failed, path = 'C:\src\flutterC:\Program' (OS Error:
Dosya adı, dizin adı veya birim etiketi sözdizimi hatalı.
, errno = 123)".
A crash report has been written to C:\src\flutter\bin\flutter_02.log.
This crash may already be reported. Check GitHub for similar crashes.
https://github.com/flutter/flutter/issues?q=is%3Aissue+FileSystemException%3A+Exists+failed%2C+path+%3D+%27C%3A%5Csrc%5CflutterC%3A%5CProgram%27+%28OS+Error%3A+Dosya+ad%C4%B1%2C+dizin+ad%C4%B1+veya+birim+etiketi+s%C3%B6zdizimi+hatal%C4%B1.%0D%0A%2C+errno+%3D+123%29

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://github.com/flutter/flutter/issues/new?title=%5Btool_crash%5D+FileSystemException%3A+Exists+failed%2C+OS+Error%3A+Dosya+ad%C4%B1%2C+dizin+ad%C4%B1+veya+birim+etiketi+s%C3%B6zdizimi+hatal%C4%B1.%0D%0A%2C+errno+%3D+123&body=%23%23+Command%0A%60%60%60%0Aflutter+doctor%0A%60%60%60%0A%0A%23%23+Steps+to+Reproduce%0A1.+...%0A2.+...%0A3.+...%0A%0A%23%23+Logs%0AFileSystemException%3A+Exists+failed%2C+OS+Error%3A+Dosya+ad%C4%B1%2C+dizin+ad%C4%B1+veya+birim+etiketi+s%C3%B6zdizimi+hatal%C4%B1.%0D%0A%2C+errno+%3D+123%0A%60%60%60%0A%230++++++_Directory.existsSync+%28dart%3Aio%2Fdirectory_impl.dart%3A92%3A7%29%0A%231++++++ForwardingFileSystemEntity.existsSync+%28package%3Afile%2Fsrc%2Fforwarding%2Fforwarding_file_system_entity.dart%3A43%3A33%29%0A%232++++++ErrorHandlingDirectory.existsSync.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handling_io.dart%3A492%3A22%29%0A%233++++++_runSync+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handling_io.dart%3A590%3A14%29%0A%234++++++ErrorHandlingDirectory.existsSync+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handling_io.dart%3A491%3A12%29%0A%235++++++AndroidStudio.latestValid+%28package%3Aflutter_tools%2Fsrc%2Fandroid%2Fandroid_studio.dart%3A244%3A64%29%0A%236++++++AppContext._generateIfNecessary.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A104%3A42%29%0A%237++++++_LinkedHashMapMixin.putIfAbsent+%28dart%3Acollection-patch%2Fcompact_hash.dart%3A535%3A23%29%0A%238++++++AppContext._generateIfNecessary+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A92%3A20%29%0A%239++++++AppContext.get+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A121%3A32%29%0A%2310+++++AppContext.get+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A119%3A24%29%0A%2311+++++AppContext.get+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A119%3A24%29%0A%2312+++++androidStudio+%28package%3Aflutter_tools%2Fsrc%2Fglobals.dart%3A65%3A45%29%0A%2313+++++runInContext.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fcontext_runner.dart%3A104%3A32%29%0A%2314+++++AppContext._generateIfNecessary.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A104%3A42%29%0A%2315+++++_LinkedHashMapMixin.putIfAbsent+%28dart%3Acollection-patch%2Fcompact_hash.dart%3A535%3A23%29%0A%2316+++++AppContext._generateIfNecessary+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A92%3A20%29%0A%2317+++++AppContext.get+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A121%3A32%29%0A%2318+++++AppContext.get+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A119%3A24%29%0A%2319+++++AppContext.get+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A119%3A24%29%0A%2320+++++androidLicenseValidator+%28package%3Aflutter_tools%2Fsrc%2Fandroid%2Fandroid_workflow.dart%3A30%3A65%29%0A%2321+++++DoctorCommand.runCommand+%28package%3Aflutter_tools%2Fsrc%2Fcommands%2Fdoctor.dart%3A53%3A32%29%0A%2322+++++FlutterCommand.verifyThenRunCommand+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command.dart%3A1568%3A12%29%0A%3Casynchronous+suspension%3E%0A%2323+++++FlutterCommand.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command.dart%3A1336%3A27%29%0A%60%60%60%0A%60%60%60%0Aencountered+exception%3A+FileSystemException%3A+Exists+failed%2C+path+%3D+%27C%3A%5Csrc%5CflutterC%3A%5CProgram%27+%28OS+Error%3A+Dosya+ad%C4%B1%2C+dizin+ad%C4%B1+veya+birim+etiketi+s%C3%B6zdizimi+hatal%C4%B1.%0D%0A%2C+errno+%3D+123%29%0A%0A%230++++++_Directory.existsSync+%28dart%3Aio%2Fdirectory_impl.dart%3A92%3A7%29%0A%231++++++ForwardingFileSystemEntity.existsSync+%28package%3Afile%2Fsrc%2Fforwarding%2Fforwarding_file_system_entity.dart%3A43%3A33%29%0A%232++++++ErrorHandlingDirectory.existsSync.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handling_io.dart%3A492%3A22%29%0A%233++++++_runSync+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handling_io.dart%3A590%3A14%29%0A%234++++++ErrorHandlingDirectory.existsSync+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Ferror_handling_io.dart%3A491%3A12%29%0A%235++++++AndroidStudio.latestValid+%28package%3Aflutter_tools%2Fsrc%2Fandroid%2Fandroid_studio.dart%3A244%3A64%29%0A%236++++++AppContext._generateIfNecessary.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A104%3A42%29%0A%237++++++_LinkedHashMapMixin.putIfAbsent+%28dart%3Acollection-patch%2Fcompact_hash.dart%3A535%3A23%29%0A%238++++++AppContext._generateIfNecessary+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A92%3A20%29%0A%239++++++AppContext.get+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A121%3A32%29%0A%2310+++++androidStudio+%28package%3Aflutter_tools%2Fsrc%2Fglobals.dart%3A65%3A45%29%0A%2311+++++runInContext.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fcontext_runner.dart%3A113%3A32%29%0A%2312+++++AppContext._generateIfNecessary.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A104%3A42%29%0A%2313+++++_LinkedHashMapMixin.putIfAbsent+%28dart%3Acollection-patch%2Fcompact_hash.dart%3A535%3A23%29%0A%2314+++++AppContext._generateIfNecessary+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A92%3A20%29%0A%2315+++++AppContext.get+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A121%3A32%29%0A%2316+++++androidValidator+%28package%3Aflutter_tools%2Fsrc%2Fandroid%2Fandroid_workflow.dart%3A29%3A51%29%0A%2317+++++_DefaultDoctorValidatorsProvider.validators+%28package%3Aflutter_tools%2Fsrc%2Fdoctor.dart%3A139%3A44%29%0A%2318+++++Doctor.validators+%28package%3Aflutter_tools%2Fsrc%2Fdoctor.dart%3A230%3A47%29%0A%2319+++++Doctor.startValidatorTasks+%28package%3Aflutter_tools%2Fsrc%2Fdoctor.dart%3A236

### Flutter Doctor output

Actually flutter doctor is not working every code 

For example I need to write cmd C:\src\flutter\bin\flutter doctor to work ( I did the path )

**Comment by huycozy** [comment]
Hi @asbe12 

>Actually flutter doctor is not working every code

Does it mean you see this error in every flutter command (doctor/run/build/etc) and every time? Can you please share this file `C:\src\flutter\bin\flutter_02.log`?

This is similar to https://github.com/flutter/flutter/issues/99954.
