### ISSUE TITLE
@dam-ease This is not solved. Flutter does not work with any app extensions in Xcode 15 right now.

### ISSUE THREAD

**Issue by Allenxuxu** [flutter/flutter#130408]
@dam-ease This is not solved. Flutter does not work with any app extensions in Xcode 15 right now.

_Originally posted by @emawby in https://github.com/flutter/flutter/issues/128947#issuecomment-1607842910_

**Comment by dam-ease** [comment]
Hi @Allenxuxu. Thanks for filing this. I'll reopen the original issue and continue discussions there.
