### ISSUE TITLE
iOS developers would like to map their knowledge to Flutter

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#13049]
I am an experienced iOS developer, and I'm now interested in Flutter. How can I quickly onboard to Flutter by mapping my iOS context and experience to the equivalent in Flutter?

**Comment by sethladd** [comment]
For example, KVO.

**Comment by kangwang1988** [comment]
KVC,Collection operation,NSPredicate for array operation, in addition.

**Comment by Sfshaza** [comment]
This was released today:  https://flutter.io/flutter-for-ios/
