### ISSUE TITLE
TextField cursor tap position issue

### ISSUE THREAD

**Issue by kamilez** [flutter/flutter#13045]
## Steps to Reproduce

1. Run Gallery application and select "Text fields" item.
2. Tap on the TextField and write any text.
3. Unfocus TextField with written text.
4. Tap at the vertical center on the TextField and see that cursor shows up at the position of the tap and its draggable indicator is visible too.
5. Unfocus TextField once again.
6. Tap a little bit below the bottom line/divider of the TextField with written text.
7. See that cursor shows up at the beginning of the written text without indicator.

Expected: IMO in both cases indicator should behave the same way and be visible. Tapping out of the TextField area shouldn't focus the field or should set its cursor position at the horizontal position of the tap.

## Flutter Doctor
```
[✓] Flutter (on Linux, locale en_US.UTF-8, channel alpha)
    • Flutter at /home/kamil/Flutter
    • Framework revision e8aa40eddd (4 weeks ago), 2017-10-17 15:42:40 -0700
    • Engine revision 7c4142808c
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /home/kamil/Programs/Android/
    • Platform android-26, build-tools 26.0.2
    • ANDROID_HOME = /home/kamil/Programs/Android/
    • Java binary at: /home/kamil/Programs/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /home/kamil/Programs/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)
```

**Comment by jason-simmons** [comment]
The TextField widget wraps its entire contents (including the InputDecoration) in a GestureDetector that sets focus to the text field on a tap event.

This has some nice properties (e.g. the field will gain focus if you tap on the decoration's icon).  But if you tap outside the bounds of the EditableText, then the Editable will not receive the tap event and will default to positioning the cursor at the start of the text.

**Comment by n4lik** [comment]
I agree but, can't imagine that someone who already set text in textfield clicking anywhere at the end and outside the bounds would like to have cursor at the beginning. At least android doesn't have such a feature so maybe is not needed in flutter too ;)

**Comment by eseidelGoogle** [comment]
This "place cursor nearest to tap" is something that our Blink engine has a bunch of code to know how to do.  It's used on the web for instance when text fields have large padding, if you tap in the padding it places the cursor nearest to your tap.

I suspect we're not even forwarding the out-of-bounds tap to the Text in these cases.

**Comment by HansMuller** [comment]
Yes it's been a very long time. Sorry about that. 

The current behavior of TextField is as @eseidel [mentioned](https://github.com/flutter/flutter/issues/13045#issuecomment-345266202). Tapping on a TextField gives it the focus and places the insertion point as close as possible to the tap. This is consistent with Android.

I don't think there's bug here (anymore).

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
