### ISSUE TITLE
Downgrading Flutter Version on Codemagic

### ISSUE THREAD

**Issue by 3DThing** [flutter/flutter#130440]
Hello everyone,

I'm wondering if there is a way to downgrade the Flutter version on Codemagic. I'm facing a potential issue where my application fails to build due to incompatibility with the latest SDK versions. Previously, everything built successfully, but now I suspect that the newer versions are causing the problem.

I would appreciate any guidance or suggestions on how to proceed with downgrading the Flutter version on Codemagic. Has anyone encountered a similar situation before? Are there any best practices or known workarounds for this issue?

Looking forward to hearing your thoughts and experiences.

Thank you!

**Comment by stuartmorgan** [comment]
Questions about third-party services need to be directed to those services.

Closing as this is not a Flutter bug.
