### ISSUE TITLE
`WebServiceWorker` refers to the asset manifest using an outdated name

### ISSUE THREAD

**Issue by andrewkolos** [flutter/flutter#130455]
https://github.com/flutter/flutter/blob/7e683c023acda7b07b4b36711b9b8a6701ddb863/packages/flutter_tools/lib/src/build_system/targets/web.dart#L510

`assets/AssetManifest.json` should be corrected to `assets/AssetManifest.bin` to re-enable eager caching of the file

**Comment by vijaymehrotra** [comment]
can i work on this issue

**Comment by vijaymehrotra** [comment]
can i solve this issue

**Comment by andrewkolos** [comment]
> `assets/AssetManifest.json` should be corrected to `assets/AssetManifest.bin` to re-enable eager caching of the file

The filename here will likely change again if https://github.com/flutter/flutter/pull/131382 lands
