### ISSUE TITLE
[canvaskit] Use ImageFilter.filterBounds to adjust ImageFilter paintbounds

### ISSUE THREAD

**Issue by harryterkelsen** [flutter/flutter#130453]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

The CanvasKit backend in Flutter Web calculates rough paint bounds when rendering. However, for ImageFilters the paint bounds are inaccurate because they do not reflect how the image filter changes the bounds of the content it filters.

### Proposal

Use `ImageFilter.filterBounds` (or equivalent API) when it is made available in CanvasKit (potential PR https://skia-review.googlesource.com/c/skia/+/721299)

**Comment by hterkelsen** [comment]
Potentially addressed here? https://github.com/flutter/engine/pull/43353
