### ISSUE TITLE
All builds on mac-26 are failing due to "bad marshal data (unknown type code)"

### ISSUE THREAD

**Issue by drewroengoogle** [flutter/flutter#130447]
One example build: https://luci-milo.appspot.com/p/flutter/builders/prod/Mac_ios%20hot_mode_dev_cycle_macos_target__benchmark/11788?

The related stderr shows this before starting step 1: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8775741855698505921/+/u/stderr

**Comment by drewroengoogle** [comment]
@kentnguyen99 Have you run into any errors or issues like this before? I'm not sure where to go from here, but I've quarantined the bot for now.

**Comment by kentnguyen99** [comment]
@drewroengoogle I ran errors check and all passed without errors.

**Comment by keyonghan** [comment]
@drewroengoogle Could you help follow up with LUCI team to see if any insight?
I checked the swarming_bot.log from the bot, no issues.
From the swarming task page, only saw:
```
[I2023-07-12T14:31:05.066133-07:00 1775 0 options.go:227] dropped 0 items over 5.971335259s
[I2023-07-12T14:31:05.211297-07:00 1775 0 main.go:814] Returning exit code from user subprocess: 1
[I2023-07-12T14:31:05.211316-07:00 1775 0 main.go:815] Temp logging final build status: STARTED
```

**Comment by drewroengoogle** [comment]
> @drewroengoogle Could you help follow up with LUCI team to see if any insight?

Followed up with the LUCI team, will update with any findings!

**Comment by drewroengoogle** [comment]
I was recommended by the LUCI team the following:

"since you quarantined this machine, I would blow away the swarming bot directory and reprovision it (if that's easy) and if not, I think blowing away just the cache directory under the swarming bot directory could be enough"

CC: @keyonghan

**Comment by keyonghan** [comment]
@kentnguyen99 could you try deleting `/opt/s` and re-provision the bot via salt?

**Comment by kentnguyen99** [comment]
@keyonghan I removed both /opt/s and /opt/salt directories off machine then re-provision again but errors still exist.

**Comment by keyonghan** [comment]
> @keyonghan I removed both /opt/s and /opt/salt directories off machine then re-provision again but errors still exist.

That helps. Thanks for the fix @kentnguyen99 
The bot is passing tests now: https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-26
