### ISSUE TITLE
[GoRouter, Url_launcher] Open a new tab in the browser

### ISSUE THREAD

**Issue by Patrick386** [flutter/flutter#130404]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I want to open a new tab in the browser and navigate to a specific page in a Flutter web app. 
I'm using GoRouter, and I would like to know how to open a new tab with a URL path that includes parameters. 
For example, I tried using the url_launcher package to open a new tab with the URL Ex: '[www.flutter.dev/download/:id](http://www.flutter.dev/download/:id)', but I couldn't pass the parameter. 
When I set the host to 'flutter.dev', it automatically adds the '#' hashcode to the URL, which makes it unable to recognize the address. Is there a way to achieve this?

```
    final url = Uri(    
      host: 'flutter.dev',
      scheme: 'https',
      path: '/download/$id',   
    );
    if (await canLaunchUrl(url)) {
      await launchUrl(url,webOnlyWindowName: isNewTab ? '_blank' : '_self');
    } else {
      throw 'Could not launch';
    }
```

### Expected results

Url_Runcher:
 - **https://flutter.dev/download/yzlAkX01milTgEl**
 

 

### Actual results

 Browser:
 - **https://flutter.dev/#/download/yzlAkX01milTgEl**
 
 '#' 

### Code sample

<details><summary>Code sample</summary>

```dart

[
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:url_launcher/url_launcher.dart';

void main() {
  runApp(MyApp());
}
void openNewTabWithId(BuildContext context, String id) async {
  if (kIsWeb) {
    final url = Uri(
      scheme: 'https',
      host: 'flutter.dev',
      path: 'downloadTransfer/$id',
    );

    final urlString = url.toString();

    if (await canLaunch(urlString)) {
      await launch(urlString, target: '_blank');
    } else {
      throw 'Could not launch the URL';
    }
  } else {
    // Handle navigation for non-web platforms
    // ...
  }
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter App',
      routerDelegate: GoRouterDelegate(
        routes: {
          '/': (context) => HomePage(),
          '/download/:id': (context, state) => DownloadPage(id: state.params['id']),
          // Define other routes here
        },
        errorPageBuilder: (context, state) => ErrorPage(),
      ),
    );
  }
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Home'),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: () async {
            final id = 'download_id_here';
           openNewTabWithId(context, id);
          },
          child: Text('Open Download Page'),
        ),
      ),
    );
  }
}

class DownloadPage extends StatelessWidget {
  final String id;

  const DownloadPage({required this.id});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Download Page'),
      ),
      body: Center(
        child: Text('Download Page - ID: $id'),
      ),
    );
  }
}

class ErrorPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Error Page'),
      ),
      body: Center(
        child: Text('404 - Page Not Found'),
      ),
    );
  }
}
]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.0 22A380 darwin-arm64 (Rosetta), locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.4)
[✓] VS Code (version 1.71.1)
[✓] VS Code (version 1.75.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by Patrick386** [comment]
The domain address and code provided are just examples. When developing a Flutter web app, a hash code is always added to the domain. flutter.dev is not my own Flutter web app. 
How can I receive the parameter value passed from url_launcher in go_router in a Flutter web app?

**Comment by danagbemava-nc** [comment]
@Patrick386, have you tried using the `PathUrlStrategy` instead of the default `HashUrlStrategy`? 

> How can I receive the parameter value passed from url_launcher in go_router in a Flutter web app?

You will need to make sure that the route you're trying to open has a parameter matching that value.
