### ISSUE TITLE
EditableTextState does not dispose TextSelectionOverlay.

### ISSUE THREAD

**Issue by polina-c** [flutter/flutter#130469]
PR that marks leak: https://github.com/flutter/flutter/pull/130470
Creation call stack: https://raw.githubusercontent.com/polina-c/spikes/master/notes/failures/2023-July-12/text_selection_theme_111.txt

To repro, remove leakTrackingTestConfig in flutter/test/material/text_selection_theme_test.dart, and observe the tests failing.

**Comment by polina-c** [comment]
@HansMuller , can you please explain why you assigned the issue to me?
I am developing leak_tracker, that detects the leaks, but Flutter engineers are more suitable to fix them.
Also, we need to validate that leak_tracker alerting and documentation is good enough to be incorporated into flutter and recommended for flutter users.

**Comment by HansMuller** [comment]
Changed the assignment. @Renzo-Olivares - finding the source of this kind of problem can be very difficult, please give @polina-c any feedback you have about the usability of the leak_tracker's report.

**Comment by polina-c** [comment]
Found leak tracker creates side effect: https://github.com/flutter/flutter/pull/131373
Reassigned this issue to me for now.

**Comment by Renzo-Olivares** [comment]
Hi @polina-c I was going through the leak and was able to fix the not-disposed objects, but was still going through the not-GCed ones. https://github.com/flutter/flutter/pull/131377.

**Comment by polina-c** [comment]
Okay @Renzo-Olivares, I fixed issues in leak_tracker. Returning this one to you. Thank you for your patience.

To see callstack for object creation, set this config:

```
leakTrackingTestConfig: const LeakTrackingTestConfig.debugnotDisposed()
```
