### ISSUE TITLE
Unexpected `Router` history behavior in DevTools after `3b4ac4d5cc59344170833b93a968ace003f184f0` 

### ISSUE THREAD

**Issue by bkonyi** [flutter/flutter#130433]
**Environment:**

Checkout DevTools at either:
- https://github.com/flutter/devtools/commit/617377e579b9525d528fe354a183c5221e5fd10c (a commit that still uses the `location` parameter in `SystemNavigator.routeInformationUpdated`)
- https://github.com/flutter/devtools/commit/a71029e5c748a2c3147ba05f1b19b13d5f9919cd (which migrates away from the deprecated `location` parameter)

Pin `dds_service_extensions` to `1.3.3` in the `pubspec.yaml` for `devtools_app`

Checkout https://github.com/flutter/flutter/commit/3b4ac4d5cc59344170833b93a968ace003f184f0 in the Flutter framework (this should be compatible with both DevTools versions above).

**Reproduction steps:**:
Once you have DevTools launched and connected to a Dart / Flutter application:

- Navigate away from the Performance page to the CPU Profiler (there's an unrelated routing bug where Perfetto does some navigation on page load that messes up the history). 
- Navigate to the Debugger
- Hit the back button in the browser

**Expected behavior:**
The forward button is enabled and navigates back to the Debugger from the CPU Profiler

**Actual behavior:**
The forward button flickers after navigating back to the Debugger and ends up disabled

**Side note:** Using the commit before 3b4ac4d5cc59344170833b93a968ace003f184f0 with https://github.com/flutter/devtools/commit/617377e579b9525d528fe354a183c5221e5fd10c produces the expected behavior.

FYI @kenzieschmoll

**Comment by chunhtai** [comment]
This is due to the query parameter escapes. will put up a pr to fix this

**Comment by chunhtai** [comment]
This should be fixed by https://github.com/flutter/flutter/pull/130457
