### ISSUE TITLE
Google pay is possible on Flutter web?

### ISSUE THREAD

**Issue by donuthappy** [flutter/flutter#130466]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

As of my knowledge, as of September 2021, Google Pay is not officially supported on Flutter Web. Google Pay is primarily designed for native mobile platforms such as Android and iOS.

Flutter Web focuses on creating web applications that can run on different web browsers, and it relies on the web platform's payment APIs for handling payment processing. While there are payment integration options available for Flutter Web, such as Stripe or PayPal, Google Pay specifically is not yet supported natively.

However, it's always a good idea to stay up to date with the latest developments in Flutter and Google Pay. Google or the Flutter team may announce support for Google Pay on Flutter Web in the future.

In the meantime, if you need payment integration in your Flutter web application, you can explore other options like Stripe, PayPal, or custom payment gateways depending on your specific requirements.

### Proposal

But Google pay is possible on Flutter web for now?
I need this function.

**Comment by darshankawar** [comment]
@donuthappy 
https://pub.dev/packages/pay seems to be official plugin for Flutter and there's already an open issue for web support: https://github.com/google-pay/flutter-plugin/issues/30, so you can follow-up in it.
Closing from here.
