### ISSUE TITLE
Google Map markers icons extremely small on Android and iOS

### ISSUE THREAD

**Issue by edipko** [flutter/flutter#130452]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Open google map on Android or iOS
Web operates as expected

### Expected results

Google maps displays markers with similar size on Android, iOS, and web.  The markers should also scale similarly

### Actual results

Markers are very small on Android and iOS and do not scale with zoom.
Markers are correct size on Web and scale with zoom

### Code sample

import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter/src/widgets/framework.dart';
import 'package:flutter/src/widgets/placeholder.dart';
import 'package:flutter_image_compress/flutter_image_compress.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:geolocator/geolocator.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:spotonresponse/data/Models/KeysModel.dart';
import 'package:spotonresponse/view/screens/incident/incident_details.dart';
import 'package:spotonresponse/view/screens/status_map/status_map_details.dart';
import 'package:http/http.dart' as http;
import '../../../data/Models/incident_list_model.dart';
import '../../../data/Models/project_list_model.dart';
import '../../../data/Navigation/navigation.dart';
import '../../../data/assets_path.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'dart:ui' as ui;
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:http/http.dart' as http;
import 'dart:typed_data';

class StatusMapScreen extends StatefulWidget {
  ProjectDetails projectDetails;
  IncidentListModel incidentListModel;
  Map<String, dynamic> incidentData;

  StatusMapScreen({
  super.key,
  required this.incidentListModel,
  required this.projectDetails,
  required this.incidentData,
  });

  @override
  _StatusMapScreenState createState() => _StatusMapScreenState();
}

class _StatusMapScreenState extends State<StatusMapScreen> {
  late GoogleMapController mapController;
  final LatLng greensburgLatLng = LatLng(40.3050, -79.4620); // Greensburg, PA
  final LatLng pittsburghLatLng = LatLng(40.4406, -79.9959); // Pittsburgh, PA
  final LatLng pittsburgh1LatLng = LatLng(40.4506, -79.9959); // Pittsburgh, PA
  final LatLng pittsburgh2LatLng = LatLng(40.4606, -79.9959); // Pittsburgh, PA
  final LatLng pittsburgh3LatLng = LatLng(40.4506, -79.9859); // Pittsburgh, PA
  final LatLng camera = LatLng(40.4506, -80.0059);

  final String customIconUrl =
      'https://app.spotonresponse.com/MapMarkers/tnc.png';
  final String customIconUrl2 = "https://app.spotonresponse.com/MapMarkers/WalmartIcon.png";
  final String customIconUrl3 = "https://app.spotonresponse.com/MapMarkers/food.png";
  final String customIconUrl4 = "https://app.spotonresponse.com/MapMarkers/fuel.png";

  Set<Marker> _markers = Set<Marker>();

  @override
  void initState() {
    super.initState();
    _addMarkers();
  }

  void _addMarkers() async {
    // Download the marker image
    Uint8List markerIconBytes = await _getMarkerIcon(customIconUrl);
    Uint8List markerIconBytes2 = await _getMarkerIcon(customIconUrl2);
    Uint8List markerIconBytes3 = await _getMarkerIcon(customIconUrl3);
    Uint8List markerIconBytes4 = await _getMarkerIcon(customIconUrl4);

    setState(() {
      _markers.add(
        Marker(
          markerId: MarkerId('Greensburg'),
          position: greensburgLatLng,
        ),
      );

      _markers.add(
        Marker(
          markerId: MarkerId('Pittsburgh'),
          position: pittsburghLatLng,
          icon: BitmapDescriptor.fromBytes(markerIconBytes, size: Size.square(33)),
        ),
      );

      _markers.add(
        Marker(
          markerId: MarkerId('Pittsburgh1'),
          position: pittsburgh1LatLng,
          icon: BitmapDescriptor.fromBytes(markerIconBytes2, size: Size.square(33)),
        ),
      );

      _markers.add(
        Marker(
          markerId: MarkerId('Pittsburgh2'),
          position: pittsburgh2LatLng,
          icon: BitmapDescriptor.fromBytes(markerIconBytes3, size: Size.square(33)),
        ),
      );

      _markers.add(
        Marker(
          markerId: MarkerId('Pittsburgh3'),
          position: pittsburgh3LatLng,
          icon: BitmapDescriptor.fromBytes(markerIconBytes4, size: Size.square(33)),
        ),
      );
    });
  }

  Future<Uint8List> _getMarkerIcon(String url) async {
    final response = await http.get(Uri.parse(url));
    return response.bodyBytes;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Map with Markers'),
      ),
      body: GoogleMap(
        markers: _markers,
        onMapCreated: (GoogleMapController controller) {
          mapController = controller;
        },
        initialCameraPosition: CameraPosition(
          target: camera,
          zoom: 12,
        ),
      ),
    );
  }
}

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here
**WEB:**
<img width="570" alt="gm-web" src="https://github.com/flutter/flutter/assets/4700917/707e2911-2de0-4af6-b310-9d9f2915a5c0">

**Android:**
<img width="413" alt="gm-android" src="https://github.com/flutter/flutter/assets/4700917/df98872f-db00-4a3d-827a-ad61da30da39">

**iOS:**
<img width="406" alt="gm-ios" src="https://github.com/flutter/flutter/assets/4700917/cd059125-2347-49da-83ad-7f357412f590">
]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
% flutter doctor -v
[✓] Flutter (Channel stable, 3.10.1, on macOS 13.4.1 22F82 darwin-x64, locale en-US)
    • Flutter version 3.10.1 on channel stable at /Users/edipko/TOOLS/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (8 weeks ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/edipko/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_SDK_ROOT = /Users/edipko/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.4746.57

[✓] VS Code (version 1.79.2)
    • VS Code at /Users/edipko/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554                        • android-x64    • Android 13 (API 33) (emulator)
    • iPhone 14 Pro Max (mobile)   • 8B9AC2CA-F1DE-480A-B782-DF62909FED4D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)              • macos                                • darwin-x64     • macOS 13.4.1 22F82 darwin-x64
    • Chrome (web)                 • chrome                               • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by huycozy** [comment]
Thanks for filing the issue, @edipko. I see there's an open issue addressing the case you described https://github.com/flutter/flutter/issues/34657. 

Your case is also mentioned at https://github.com/flutter/flutter/issues/34657#issuecomment-1317051585 and https://github.com/flutter/flutter/issues/34657#issuecomment-1317466472. 

I also tried a workaround at https://github.com/flutter/flutter/issues/34657#issuecomment-615458858 and see it works as expected (but it's for asset image marker). 
<details>
<summary>Demo workaround</summary>

![Screenshot 2023-07-13 at 15 54 13](https://github.com/flutter/flutter/assets/104349824/4776c0d3-0be3-4d82-a675-3c652344fa99)
</details>



I will close this issue in favor of that issue, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
