### ISSUE TITLE
Clicking on Icons.photo_camera, then cancelling, and then clicking a second time throws exception

### ISSUE THREAD

**Issue by baksoy** [flutter/flutter#13051]
## Steps to Reproduce
When going through codelab https://codelabs.developers.google.com/codelabs/flutter-firebase
if you click on the Icons.photo_camera to take/pick an image and cancel, then click on Icons.photo_camera a second time and cancel again, it lands on the message_codecs.dart file to the exception "throw new PlatformException(code: errorCode, message: errorMessage, details: errorDetails);" within the following method:

@override
  dynamic decodeEnvelope(ByteData envelope) {
    // First byte is zero in success case, and non-zero otherwise.
    if (envelope.lengthInBytes == 0)
      throw const FormatException('Expected envelope, got nothing');
    final ReadBuffer buffer = new ReadBuffer(envelope);
    if (buffer.getUint8() == 0)
      return StandardMessageCodec._readValue(buffer);
    final dynamic errorCode = StandardMessageCodec._readValue(buffer);
    final dynamic errorMessage = StandardMessageCodec._readValue(buffer);
    final dynamic errorDetails = StandardMessageCodec._readValue(buffer);
    if (errorCode is String && (errorMessage == null || errorMessage is String) && !buffer.hasRemaining)
      throw new PlatformException(code: errorCode, message: errorMessage, details: errorDetails);
    else
      throw const FormatException('Invalid envelope');
  }

## `flutter run`
**When I run with `flutter run`, the app does NOT freeze. It freezes when run from INTELLIJ. Here is flutter run:**
-MacBook-Pro:friendlychat-flutter-codelab developer$ flutter run
Launching lib/main.dart on iPhone X in debug mode...
Running pod install...                                1.5s
Running Xcode build...                               10.0s
    CADisplay.name = LCD;
    CADisplay.deviceName = PurpleMain;
    CADisplay.seed = 1;
    tags = 0;
    currentMode = <FBSDisplayMode: 0x60400046f540; 375x812@3x (1125x2436/3) 60Hz p3>;
    safeOverscanRatio = {0.89999997615814209, 0.89999997615814209};
    nativeCenter = {562.5, 1218};
    pixelSize = {1125, 2436};
    bounds = {{0, 0}, {375, 812}};
    CADisplay = <CADisplay:LCD PurpleMain>;
}
[Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add [FIRApp configure] to your application initialization. Read more: https://goo.gl/ctyzm8.
[Firebase/Analytics][I-ACS023007] Firebase Analytics v.3900000 started
[Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
[Firebase/Messaging][I-IID001001] FIRInstanceID AppDelegate proxy enabled, will swizzle app delegate remote notification handlers. To disable add "FirebaseAppDelegateProxyEnabled" to your Info.plist and set it to NO
[Firebase/Analytics][I-ACS003007] Successfully created Firebase Analytics App Delegate Proxy automatically. To disable the proxy, set the flag FirebaseAppDelegateProxyEnabled to NO in the Info.plist
[Firebase/Analytics][I-ACS032003] iAd framework is not linked. Search Ad Attribution Reporter is disabled.
[Firebase/Analytics][I-ACS023012] Firebase Analytics enabled
Syncing files to device iPhone X...                   1.1s

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on iPhone X is available at: http://127.0.0.1:8100/
For a more detailed help message, press "h". To quit, press "q".

PlatformException(multiple_request, Cancelled by a second request, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:514:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:154:18)
<asynchronous suspension>
#2      ImagePicker.pickImage (package:image_picker/image_picker.dart:32:40)
<asynchronous suspension>
#3      ChatScreenState._buildTextComposer.<anonymous closure> (/Users/developer/Projects/friendlychat-flutter-codelab/lib/main.dart:167:56)
<asynchronous suspension>
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:323:14)
#5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:375:30)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
#7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
#8      TapGestureRecognizer<…>
PlatformException(multiple_request, Cancelled by a second request, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:514:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:154:18)
<asynchronous suspension>
#2      ImagePicker.pickImage (package:image_picker/image_picker.dart:32:40)
<asynchronous suspension>
#3      ChatScreenState._buildTextComposer.<anonymous closure> (/Users/developer/Projects/friendlychat-flutter-codelab/lib/main.dart:167:56)
<asynchronous suspension>
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:323:14)
#5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:375:30)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
#7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
#8      TapGestureRecognizer<…>
PlatformException(multiple_request, Cancelled by a second request, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:514:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:154:18)
<asynchronous suspension>
#2      ImagePicker.pickImage (package:image_picker/image_picker.dart:32:40)
<asynchronous suspension>
#3      ChatScreenState._buildTextComposer.<anonymous closure> (/Users/developer/Projects/friendlychat-flutter-codelab/lib/main.dart:167:56)
<asynchronous suspension>
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:323:14)
#5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:375:30)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
#7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
#8      TapGestureRecognizer<…>
PlatformException(multiple_request, Cancelled by a second request, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:514:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:154:18)
<asynchronous suspension>
#2      ImagePicker.pickImage (package:image_picker/image_picker.dart:32:40)
<asynchronous suspension>
#3      ChatScreenState._buildTextComposer.<anonymous closure> (/Users/developer/Projects/friendlychat-flutter-codelab/lib/main.dart:167:56)
<asynchronous suspension>
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:323:14)
#5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:375:30)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
#7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
#8      TapGestureRecognizer<…>

## `flutter analyze`:
Analyzing /Users/developer/Projects/friendlychat-flutter-codelab...
No issues found!
Ran in 4.3s

## Flutter Doctor
[✓] Flutter (on Mac OS X 10.13.1 17B48, locale en-US, channel alpha)
    • Flutter at /Users/developer/flutter
    • Framework revision e8aa40eddd (4 weeks ago), 2017-10-17 15:42:40 -0700
    • Engine revision 7c4142808c
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /Users/developer/Library/Android/sdk
    • Platform android-26, build-tools 26.0.2
    • ANDROID_HOME = /Users/developer/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.1, Build version 9B55
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.6)
    • Flutter plugin version 19.1
    • Dart plugin version 172.4343.25

[✓] Connected devices
    • iPhone X • 746979BB-0CFC-4B1D-B09E-3BC82FC6756D • ios • iOS 11.1 (simulator)

**Comment by zoechi** [comment]
I think this was fixed in 0.1.4 https://github.com/flutter/plugins/blob/master/packages/image_picker/CHANGELOG.md#014

**Comment by baksoy** [comment]
Yes. Thanks for reminding.
