### ISSUE TITLE
Add a GitHub webhook for flutter/flutter repo to new github-label-notifier service

### ISSUE THREAD

**Issue by whesse** [flutter/flutter#130500]
The github-label-notifier is migrating from Cloud Functions to Cloud Run, and so the webhook that sends notifications of new issues and issue label events needs to be duplicated, to send to the new service as well.

I cannot see the webhooks, but it should send to the same place as the dart-lang/sdk webhook, and use the same secret to authenticate to the service.
Contact me to be authorized to access this secret.

The webhook should send to 
https://github-webhook-qvyo5rktwa-uc.a.run.app/githubWebhook

with content type application/json, ssh verification, the secret that you will get from me, and the events "issues" selected.
The hook should be made active.

You should already have an existing webhook with the same settings, going to the service at its old address
https://us-central1-dart-ci.cloudfunctions.net/githubWebhook

The new one should just duplicate it.

@keyonghan @CaseyHillers

**Comment by keyonghan** [comment]
> The github-label-notifier is migrating from Cloud Functions to Cloud Run, and so the webhook that sends notifications of new issues and issue label events needs to be duplicated, to send to the new service as well.

Do you have more context? Is there a hard deadline the old service will be deprecated? I can still get notifications as of now. 
This needs admin access, and @godofredoc is ooo. If this is urgent, we need help from, maybe @Hixie .

**Comment by whesse** [comment]
There is no hard deadline.  We can keep the old service running for flutter/flutter, and run the new one on dart/sdk.

I can't test the new service on flutter/flutter until the webhook is added.
We would like to turn the old service off, and delete its imlementation, but this is not urgent.  Priority should be decreased if you want.  But I would suggest asking @Hixie to do this, if possible.

New service is not even reviewed and landed yet: https://dart-review.googlesource.com/c/dart_ci/+/278961

**Comment by Hixie** [comment]
done
