### ISSUE TITLE
[process] Should label names be standardized?

### ISSUE THREAD

**Issue by itsjustkevin** [flutter/flutter#130503]
There seems to be multiple schemas for how we name labels within the Flutter organization. 

With the large rewrite of labels described in flutter.dev/go/triage-2023-rfc, there still seems to be a few label schemas that we are supporting. 

1. Hyphen separated labels (team-release)
2. Colon-space labels (f: material)
3. Spaced labels (permanently locked)

As new use cases appear which necessitate the creation of new labels, do we have guidance around the naming scheme?

CC: @Hixie

**Comment by Hixie** [comment]
guidance is at https://github.com/flutter/flutter/wiki/Issue-hygiene#labels
