### ISSUE TITLE
Regression in 99p raster times in tiles_scroll_perf on iOS

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#130594]
https://github.com/flutter/flutter/commit/a7a353ca2b9a02714ab8b592b86f5bd325f4b8b4

https://flutter-flutter-perf.skia.org/e/?begin=1689285778&end=1689317881&keys=X5d2af11e8f531e542f5cf0ab209f99bf&num_commits=50&request_type=1&xbaroffset=35735

cc @jonahwilliams @dnfield

**Comment by dnfield** [comment]
It was my commit - which was a revert which is going to get relanded.

**Comment by dnfield** [comment]
I'll close this - it should imrpove again when we reland a safer patch.
