### ISSUE TITLE
3.13 Beta does not support win7

### ISSUE THREAD

**Issue by shuax** [flutter/flutter#130554]
flutter_windows.dll depends `GetHostNameW `
`无法定位程序输入点 GetHostNameW 于动态链接库 WS2_32.dll 上。 `

3.12 Beta works fine

**Comment by darshankawar** [comment]
@shuax 
Can you provide / elaborate on the issue / error you are getting while trying to run on latest beta ?
Please provide complete error log if any so that we can properly address the issue.

**Comment by shuax** [comment]
![image](https://github.com/flutter/flutter/assets/6940583/b45dfe1e-9a79-4563-ac46-add18ae75077)
like this

**Comment by darshankawar** [comment]
See [this](https://www.htmlvalidator.com/CSS-HTML-Forum/viewtopic.php?t=3310) and check if it helps in your case or not.

**Comment by shuax** [comment]
It's caused by the engine, I can't modify it

**Comment by huycozy** [comment]
Are you using any 3rd plugin that loads that library? I see `GetHostNameW` function is only available in Windows 8 and above, see https://learn.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-gethostnamew

**Comment by shuax** [comment]
![image](https://github.com/flutter/flutter/assets/6940583/98fb25ee-8f3b-42e8-8c6f-105d91e510cc)

It is not caused by a third-party plugin, but the engine is referencing this function

**Comment by huycozy** [comment]
@shuax Unfortunately, I don't have Windows 7 so can't verify this issue. Are you seeing this issue on a newly created Flutter project? Does it also happen on the latest master channel? 

Please provide the complete output of `flutter run -v` and `flutter doctor -v`. Thank you!

**Comment by czw299** [comment]
> @shuax Unfortunately, I don't have Windows 7 so can't verify this issue. Are you seeing this issue on a newly created Flutter project? Does it also happen on the latest master channel?
> 
> Please provide the complete output of and . Thank you!`flutter run -v``flutter doctor -v`

I created a new project using the 3.13.0-0.3.pre SDK I just downloaded. As mentioned above, it does not work on Windows7.
![image](https://github.com/flutter/flutter/assets/48857658/cb82f7b5-834c-4150-b3d4-493efcd8c24e)
![image](https://github.com/flutter/flutter/assets/48857658/3cb9ee02-ae2e-4e5d-8baf-b9b61426550e)

**Comment by huycozy** [comment]
@czw299 Can you please check if it also happens on the latest master channel? 

Also, I notice the error comes when you open `Release` file (your screenshot). Does this issue only happen in release mode after building the app? Please verify this in debug mode as well. If it also appears, please provide the entire output of `flutter run -v`. Thank you!

**Comment by shuax** [comment]
The problem occurs in flutter_windows.dll, and this file is not compiled by the user, but provided by the flutter engine.

**Comment by shuax** [comment]
I found the reason, it's a change in dart. https://github.com/dart-lang/sdk/commit/7bdbc0560ed5cd0026bfc57a99583f7ba19a0245

**Comment by huycozy** [comment]
I see that commit is available on `3.1.0-262.3.beta` release which is your current Dart version.

**Comment by aam** [comment]
thanks for the report, https://dart-review.googlesource.com/c/sdk/+/320060 with proposed fix

**Comment by zanderso** [comment]
fyi @cbracken @HansMuller

**Comment by a-siva** [comment]
How come this bug which is apparently very critical to warrant a cherry pick not labeled with any kind of priority ?
It was totally missed in all the weekly triaging we do in the weeekly VM meetings for all P0, P1 issues.

**Comment by zanderso** [comment]
> How come this bug which is apparently very critical to warrant a cherry pick not labeled with any kind of priority ? It was totally missed in all the triaging we do in the weekly VM meetings for all P0, P1 issues.

It looks like there wasn't enough information for frontline triage to route the issue until @shuax found the commit this past Friday. Since the issue didn't get routed by frontline triage, it didn't show up on any subteam triage list.

**Comment by gspencergoog** [comment]
What is the status for this bug?  Do we still need a cherry pick for Flutter before we close this? (Desktop Triage)

Which versions should it be a cherrypick for?

cc @loic-sharma

**Comment by cbracken** [comment]
Looks like the Dart cherry-pick has landed, but we'll need a Dart SDK cherry-pick in to Flutter.

**Comment by zanderso** [comment]
The Dart CP made it to Flutter 3.13. I'll go ahead and close this. (@itsjustkevin can correct me and re-open this if needed).

**Comment by cbracken** [comment]
Thanks!
