### ISSUE TITLE
[Vscode Flutter Plugins] don't think `final` and `get` are equivalent

### ISSUE THREAD

**Issue by au-top** [flutter/flutter#130552]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create an abstract class
2. Abstract class has `abstract final GlobalKey widgetKey`
3. extends abstract class
4. use vscode flutter plugins quick fix code generate code `GlobalKey get widgetKey => throw  xxxx`

I don't think 'final' and 'get' are equivalent

The tool should generate a 'final' for '@override' instead of 'get'`

`get' is similar to 'function '

`abstract final 'is a variable in a block of memory space

### Expected results

generate `final GlobalKey widgetKey;`

### Actual results

 `GlobalKey get widgetKey => throw  xxxx`

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@au-top 
I think this need to be reported in dedicated repo: https://github.com/Dart-Code/Dart-Code/issues
Closing from here. If you get redirected here, please write in comments and I'll reopen it.
