### ISSUE TITLE
[google_maps_flutter_web] GoogleMap consumes gestures for all widgets on top of it. Gestures also affect the map.

### ISSUE THREAD

**Issue by penguisnt** [flutter/flutter#130597]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Using a Stack, put a Slider widget over GoogleMap using [google_maps_flutter_web](https://pub.dev/packages/google_maps_flutter_web). 

Drag the slider, observe that Google maps also shifts in the background. See attached video

I tried a lot of things like: AbsorbPointer, Listener, IgnorePointer, GestureDetector, but maybe I was using them incorrectly.

Please advise.

### Expected results

Widgets ontop of GoogleMap are not propagated to Google Map.

### Actual results

Google maps consumes the gestures, even when interacting with another widget.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

// stateful widget with a slider
class SliderDemo extends StatefulWidget {
  const SliderDemo({Key? key}) : super(key: key);

  @override
  State<SliderDemo> createState() => _SliderDemoState();
}

class _SliderDemoState extends State<SliderDemo> {
  double _currentSliderValue = 20;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Map Stack Demo',
      theme: ThemeData(useMaterial3: true),
      home: Stack(
        children: [
          const GoogleMap(
            mapType: MapType.none,
            initialCameraPosition: CameraPosition(
              target: LatLng(33.1627, -86.7816),
              zoom: 5.5,
            ),
          ),
          Center(
            child: Card(
              child: SizedBox(
                width: 200,
                height: 200,
                child: Slider(
                  value: _currentSliderValue,
                  min: 0,
                  max: 100,
                  divisions: 5,
                  label: _currentSliderValue.round().toString(),
                  onChanged: (double value) {
                    setState(
                      () {
                        _currentSliderValue = value;
                      },
                    );
                  },
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[screen-capture.webm](https://github.com/flutter/flutter/assets/117488089/501a6db7-6dd5-454a-b0f8-ff2892dc9abb)

</details>

### Logs

<details><summary>Logs</summary>

```console
None
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.3, on Microsoft Windows [Version 10.0.22621.1848], locale en-US)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[✓] Chrome - develop for the web
[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[!] Android Studio (version 2022.2)
    ✗ Unable to find bundled Java version.
[✓] IntelliJ IDEA Community Edition (version 2023.1)
[✓] VS Code (version 1.79.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 3 categories.
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @penguisnt 
It looks similar to https://github.com/flutter/flutter/issues/73830 for which the solution is https://github.com/flutter/flutter/issues/73830#issuecomment-760588189, so try the same which should resolve the issue.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.

**Comment by darshankawar** [comment]
Thanks for the report @penguisnt 
It looks similar to https://github.com/flutter/flutter/issues/73830 for which the solution is https://github.com/flutter/flutter/issues/73830#issuecomment-760588189, so try the same which should resolve the issue.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.

**Comment by penguisnt** [comment]
Thanks, that did seem to fix the issue. I had tried this before, but I made a wrong assumption. I thought that the PointerInterceptor would propagate clicks not handled by the flutter widgets, but it doesn't.

For others who might have the same issue: I had put my widgets over the GoogleMap using a Stack, but I wrapped the 'Align' widgets in the PointerInterceptor, which were technically full-width and full-height. That meant the map no longer moved with the map as intended, but also stopped the map from working all together (because the empty space (i.e. whole screen) technically had a PointerInterceptor over it)

So, you need to make sure to put the PointerInterceptor at a level that _only_ surrounds your smaller widgets
