### ISSUE TITLE
[tool_crash] StateError: Bad state: Future already completed

### ISSUE THREAD

**Issue by Hirenpar** [flutter/flutter#130575]
## Command
```
flutter --no-color attach --machine --device-id=RZ8MB0N9A9P lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: Future already completed
```
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:35:31)
#1      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:338:17)
<asynchronous suspension>
```
```
[!] Flutter (Channel stable, 3.7.12, on Microsoft Windows [Version 10.0.18362.113], locale en-IN)
    • Flutter version 3.7.12 on channel stable at C:\Users\PC\Downloads\flutter_windows_3.7.12-stable\flutter
    ! The flutter binary is not on your path. Consider adding C:\Users\PC\Downloads\flutter_windows_3.7.12-stable\flutter\bin to your path.
    ! The dart binary is not on your path. Consider adding C:\Users\PC\Downloads\flutter_windows_3.7.12-stable\flutter\bin to your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (3 months ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\PC\AppData\Local\Android\sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[✓] VS Code (version 1.80.0)
    • VS Code at C:\Users\PC\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • SM A307FN (mobile) • RZ8MB0N9A9P • android-arm64  • Android 11 (API 30)
    • Windows (desktop)  • windows     • windows-x64    • Microsoft Windows [Version 10.0.18362.113]
    • Chrome (web)       • chrome      • web-javascript • Google Chrome 114.0.5735.199
    • Edge (web)         • edge        • web-javascript • Microsoft Edge 114.0.1823.58

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.4+16
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 4b12645012342076800eb701bcdfe18f87da21cf
### Plugins
cloud_firestore-4.8.0
cloud_firestore_web-3.6.0
device_info_plus-9.0.1
file_selector_linux-0.9.1+3
file_selector_macos-0.9.2
file_selector_windows-0.9.2
firebase_auth-4.6.1
firebase_auth_web-5.5.1
firebase_core-2.14.0
firebase_core_web-2.6.0
firebase_crashlytics-3.3.1
firebase_dynamic_links-5.3.3
firebase_messaging-14.6.1
firebase_messaging_web-3.5.1
firebase_remote_config-4.2.1
firebase_remote_config_web-1.4.1
flutter_local_notifications-14.1.1
flutter_plugin_android_lifecycle-2.0.15
fluttertoast-8.2.1
google_mobile_ads-3.0.0
google_sign_in-6.1.0
google_sign_in_android-6.1.14
google_sign_in_ios-5.6.2
google_sign_in_web-0.12.0
image_cropper-4.0.1
image_cropper_for_web-2.0.0
image_gallery_saver-1.7.1
image_picker-0.8.9
image_picker_android-0.8.7+3
image_picker_for_web-2.2.0
image_picker_ios-0.8.8
image_picker_linux-0.2.1
image_picker_macos-0.2.1
image_picker_windows-0.2.1
in_app_purchase-3.1.5
in_app_purchase_android-0.2.5+4
in_app_purchase_storekit-0.3.6+3
in_app_review-2.0.6
in_app_update-4.0.1
package_info_plus-4.0.0
path_provider-2.0.15
path_provider_android-2.0.27
path_provider_foundation-2.2.3
path_provider_linux-2.1.10
path_provider_windows-2.1.6
permission_handler-10.2.0
permission_handler_android-10.2.1
permission_handler_apple-9.0.8
permission_handler_windows-0.1.2
share_plus-7.0.0
shared_preferences-2.1.1
shared_preferences_android-2.1.4
shared_preferences_foundation-2.2.2
shared_preferences_linux-2.2.0
shared_preferences_web-2.1.0
shared_preferences_windows-2.2.0
sign_in_with_apple-4.3.0
sign_in_with_apple_web-1.0.1
speech_to_text-6.1.1
speech_to_text_macos-1.0.2
sqflite-2.2.8+4
url_launcher-6.1.11
url_launcher_android-6.0.34
url_launcher_ios-6.1.4
url_launcher_linux-3.0.5
url_launcher_macos-3.0.5
url_launcher_web-2.0.16
url_launcher_windows-3.0.6
webview_flutter-4.2.0
webview_flutter_android-3.7.0
webview_flutter_wkwebview-3.4.3

**Comment by dam-ease** [comment]
Hi @Hirenpar. I see there's an open issue addressing the case you described. #77581
Please follow up on that issue, I'm closing the current one as a duplicate.
Thank you
