### ISSUE TITLE
linux-arm64-flutter-gtk.zip does not contain a license

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#130682]
http://storage.googleapis.com/flutter_infra_release/flutter/1a65d409c7a1438a34d21b60bf30a6fd5db59314/linux-arm64-profile/linux-arm64-flutter-gtk.zip doesn't contain a license file.

All of our distributed archives should contain license files. Source files should have the LICENSE file that applies to them (the one referenced in the header in the file), and binary files should have the license file that applies to any source files that were involved in the linking of the file.

**Comment by chinmaygarde** [comment]
`zip_bundle("flutter_gtk")` is probably missing the directives to copy the licenses.

**Comment by dnfield** [comment]
Doing a quick audit here, we have a number of zip bundles that do not have a license file. We're really not consistent about this.

**Comment by dnfield** [comment]
Argh, it looks like we don't copy the LICENSE file into _any_ of the zip bundles. We do provide a license readme in some cases where the blanket LICENSE file doesn't apply, but AFAICT we've been treating the top level LICENSE file distributed with the tool as covering the zips.
