### ISSUE TITLE
```flutter pub get``` should allow platform constraint in yaml

### ISSUE THREAD

**Issue by techwnn** [flutter/flutter#130693]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

When I run ```flutter pub get``` in my project, it hints me there is some conflict in two plugins for windows platform.

But my project is only for iOS and Android.

### Proposal

1. I think ```flutter pub get``` should allow me to config platforms in yaml
2. don't get unwanted platform implementations
3. don't check unrelated platform conflicts.

**Comment by techwnn** [comment]
I'm using:
```flutter  3.7.12```

I include in yaml with:
```
device_info_plus: 7.0.1
share_plus: 7.0.2
```

```flutter pub get``` error hints:
```
Because share_plus 7.0.2 depends on win32 >=4.0.0 <6.0.0 and device_info_plus >=7.0.0 <8.1.0 depends on win32 >=2.7.0 <4.0.0, share_plus 7.0.2 is incompatible with device_info_plus >=7.0.0 <8.1.0.
So, because flutter_app depends on both device_info_plus 7.0.1 and share_plus 7.0.2, version solving failed.
pub get failed
command: "/Users/qxy9763/Library/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --directory . get --example"
pub env: {
  "FLUTTER_ROOT": "/Users/qxy9763/Library/flutter",
  "PUB_ENVIRONMENT": "flutter_cli:get",
  "PUB_CACHE": "/Users/qxy9763/.pub-cache",
}
exit code: 1
```

**Comment by TahaTesser** [comment]
Hi @techwnn 
This seems to be related to the `pub`, please file an issue at https://github.com/dart-lang/pub repository.

**Comment by techwnn** [comment]
> Hi @techwnn This seems to be related to the `pub`, please file an issue at https://github.com/dart-lang/pub repository.
OK, thanks for your reminder.
