### ISSUE TITLE
Renaming dart files retains a copy of the old dart file

### ISSUE THREAD

**Issue by Cozmeh** [flutter/flutter#130675]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Not exactly sure how to reproduce it but, I found out about the issue later in the project development.
### context
So I got this warning "**the file name 'Example.dart' isn't a snake_case identifier**"
to keep everything clean I decided to change the file name, so I renamed it to '`example. dart`' but the file was still '`Example.dart`' so I renamed it again, and the changes got reflected.
But When I tried to change the constructor of a class that was being used in 2 different classes (dart files) the changes were only reflected in only one of the 2 classes 

### Expected results

Im not really sure what is the expected behaviour 

### Actual results

This is what I did :
 * Added one extra `required this.something` 
 * one file in which this was being used showed an error that the parameter is required 
 * but another file in which the same constructor was being used didn't show any error (which was odd)
 * After checking the code complete suggestions(ctrl+spacebar in vs code), I released that 2 constructors exist in the same file with the same name but different parameters and when I clrl+click the 2 different constructors it takes me to the same location and also the file name jumps from '`example.dart`' to '`Example.dart`' depending upon which constructor I ctrl+click 
 
I am not sure what is happening 
 

### Code sample

<details><summary>Code sample</summary>

```dart
// this was the one which was being used in 2 different classes ,file name-(participantsTile.dart)
class ParticipantsTile extends StatefulWidget {
  String participantID, takenTime, eventID;
  bool isPresent, isOpenForall, deleteBtn;
  ParticipantsTile({
    super.key,
    required this.participantID,
    required this.takenTime,
    required this.isPresent,
    required this.isOpenForall,
    required this.eventID,
    required this.deleteBtn,
  });

// the class in which no error reflected , file name-(scan.dart)
return ParticipantsTile(
  isOpenForall: widget.isOpenForall,
  isPresent: e['isPresent'],
  participantID: e.id,
  takenTime: itemTime,
  eventID: widget.eventID.toString()
);

// and the class in which the changed were reflected properly (showed and error), file name-(Participants.dart)
return ParticipantsTile(
  isOpenForall: widget.isOpenForall,
  isPresent: e['isPresent'],
  participantID: e.id,
  takenTime: itemTime,
  eventID: widget.eventID.toString(),
);

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.19045.3208], locale en-IN)
    • Flutter version 3.10.5 on channel stable at C:\Dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (5 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1) 
    • Android SDK at C:\Users\Cozmic\AppData\Local\Android\sdk
    • Platform android-33-ext4, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java       
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33530.505
    • Windows 10 SDK version 10.0.22000.0
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++"
      workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] VS Code (version 1.80.1)
    • VS Code at C:\Users\Cozmic\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.68.0

[√] Connected device (4 available)
    • SM E146B (mobile) • RZCW40TSXDK • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.19045.3208]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 114.0.5735.199
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 114.0.1823.79

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
@Cozmeh 
Since you are uncertain of the replicable / occurence of the issue, I suggest you to take some time and see if you are able to replicate it consistently or not. If yes, then you'll probably need to file this in flutter's vscode plugin github repo, as it could be related to it and not the framework itself. 
Closing for now based on above explaination. If you disagree, write in comments and I'll reopen it.

**Comment by Cozmeh** [comment]
okay, thanks for clarifying!
