### ISSUE TITLE
Request to add a mention of new Sync API to Platform Channels doc

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#13068]
We had someone evaluate Flutter and come to the conclusion that they couldn't do Sync Interop. Two reasons for this:

* Support landed this week, it's brand new :) https://github.com/flutter/engine/pull/4358
* it's not mentioned in our https://flutter.io/platform-channels/ doc

This is an issue to request that we at least mention this new capability, to increase its discoverability. We can, of course, add the note that we encourage people to use the async version whenever possible.

**Comment by sethladd** [comment]
cc @mit-mit

**Comment by Hixie** [comment]
Support didn't land, we decided against it.

**Comment by sethladd** [comment]
Apologies, I missed the revert. I'm curious if @takhion (our user originally requesting the capability) also saw the revert :)
