### ISSUE TITLE
Error when using Html inside a list

### ISSUE THREAD

**Issue by DiegoMazega** [flutter/flutter#130600]
error: "**The following assertion was thrown during performLayout():
Intrinsics are not available for PlaceholderAlignment.baseline, PlaceholderAlignment.aboveBaseline,
or PlaceholderAlignment.belowBaseline.**"

this error is happen on beta version, alpha is OK.

```flutter
Scaffold(
body: CustomScrollView(
        physics : const ClampingScrollPhysics(),
        shrinkWrap: true,
        slivers: <Widget>[
          SliverFillRemaining(
            hasScrollBody: false,
            child: Container(
          padding: const EdgeInsets.only(bottom: 20, left: 22, right: 22),
          child: Column(
            children: <Widget>[
              Container(
                  margin: const EdgeInsets.only(bottom: 10),
                  child: Html(data: ${HTML_DATA_HERE})),
            
            ],
          ),
        ),,
          )
        ],
      )),
```

full error :
Reloaded 1 of 3937 libraries in 1,390ms (compile: 85 ms, reload: 399 ms, reassemble: 882 ms).
flutter: -- REMOTE CONFIG EXCHANGE USERS -----------------------
flutter: Instance of 'RemoteConfigExchangeUsersAndBTGModel'
flutter: []
flutter: true
flutter: -------------------------------------------------------
Reloaded 1 of 3937 libraries in 1,309ms (compile: 113 ms, reload: 345 ms, reassemble: 790 ms).
flutter: -- REMOTE CONFIG EXCHANGE USERS -----------------------
flutter: Instance of 'RemoteConfigExchangeUsersAndBTGModel'
flutter: []
flutter: true
flutter: -------------------------------------------------------
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
Intrinsics are not available for PlaceholderAlignment.baseline, PlaceholderAlignment.aboveBaseline,
or PlaceholderAlignment.belowBaseline.
'package:flutter/src/rendering/paragraph.dart':
Failed assertion: line 499 pos 13: 'RenderObject.debugCheckingIntrinsics'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was:
  SliverFillRemaining

When the exception was thrown, this was the stack:
#2      RenderParagraph._canComputeIntrinsics (package:flutter/src/rendering/paragraph.dart:499:13)
#3      RenderParagraph._computeIntrinsicHeight (package:flutter/src/rendering/paragraph.dart:457:10)
#4      RenderParagraph.computeMaxIntrinsicHeight (package:flutter/src/rendering/paragraph.dart:472:12)
#5      RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1409:23)
#6      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#7      RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1407:57)
#8      RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1746:12)
#9      RenderPadding.computeMaxIntrinsicHeight (package:flutter/src/rendering/shifted_box.dart:202:21)
#10     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1409:23)
#11     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#12     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1407:57)
#13     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1746:12)
#14     RenderProxyBoxMixin.computeMaxIntrinsicHeight (package:flutter/src/rendering/proxy_box.dart:98:21)
#15     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1409:23)
#16     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#17     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1407:57)
#18     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1746:12)
#19     RenderCSSBox.computeMaxIntrinsicHeight.<anonymous closure> (package:flutter_html/src/css_box_widget.dart:462:48)
#20     RenderCSSBox.getIntrinsicDimension (package:flutter_html/src/css_box_widget.dart:434:52)
#21     RenderCSSBox.computeMaxIntrinsicHeight (package:flutter_html/src/css_box_widget.dart:461:12)
#22     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1409:23)
#23     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#24     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1407:57)
#25     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1746:12)
#26     RenderPadding.computeMaxIntrinsicHeight (package:flutter/src/rendering/shifted_box.dart:202:21)
#27     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1409:23)
#28     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#29     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1407:57)
#30     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1746:12)
#31     RenderFlex.computeMaxIntrinsicHeight.<anonymous closure> (package:flutter/src/rendering/flex.dart:615:60)
#32     RenderFlex._getIntrinsicSize (package:flutter/src/rendering/flex.dart:525:39)
#33     RenderFlex.computeMaxIntrinsicHeight (package:flutter/src/rendering/flex.dart:612:12)
#34     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1409:23)
#35     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#36     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1407:57)
#37     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1746:12)
#38     RenderPadding.computeMaxIntrinsicHeight (package:flutter/src/rendering/shifted_box.dart:202:21)
#39     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1409:23)
#40     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#41     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1407:57)
#42     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1746:12)
#43     RenderSliverFillRemaining.performLayout (package:flutter/src/rendering/sliver_fill.dart:148:32)
#44     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#45     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:534:13)
#46     RenderShrinkWrappingViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1882:12)
#47     RenderShrinkWrappingViewport.performLayout (package:flutter/src/rendering/viewport.dart:1833:20)
#48     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#49     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#50     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#51     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#52     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#53     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#54     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#55     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#56     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#57     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#58     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#59     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#60     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#61     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#62     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#63     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#64     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#65     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#66     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#67     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#68     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#69     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1056:7)
#70     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:235:7)
#71     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
#72     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#73     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#74     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#75     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#76     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#77     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#78     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1449:11)
#79     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#80     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#81     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#82     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#83     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#84     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#85     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#86     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#87     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#88     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#89     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#90     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
#91     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:580:43)
#92     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:607:12)
#93     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#94     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#95     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#96     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#97     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#98     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#99     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#100    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#101    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#102    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#103    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#104    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#105    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#106    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#107    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#108    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#109    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#110    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3749:14)
#111    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#112    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#113    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#114    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#115    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#116    _RenderTheaterMixin.performLayout (package:flutter/src/widgets/overlay.dart:832:15)
#117    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2234:7)
#118    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1016:18)
#119    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:492:19)
#120    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:905:13)
#121    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358:5)
#122    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284:15)
#123    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214:9)
#124    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1072:5)
#125    _invoke (dart:ui/hooks.dart:142:13)
#126    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359:5)
#127    _drawFrame (dart:ui/hooks.dart:112:31)
(elided 2 frames from class _AssertionError)

The following RenderObject was being processed when the exception was fired: RenderSliverFillRemaining#09dc3 relayoutBoundary=up8 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
  creator: _SliverFillRemainingWithoutScrollable ← SliverFillRemaining ← ShrinkWrappingViewport ←
    IgnorePointer-[GlobalKey#9273f] ← Semantics ← Listener ← _GestureSemantics ←
    RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#d25f8] ← Listener ← _ScrollableScope
    ← _ScrollSemantics-[GlobalKey#09bb5] ← NotificationListener<ScrollMetricsNotification> ← ⋯
  parentData: layoutOffset=None (can use size)
  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle,
    scrollOffset: 0.0, remainingPaintExtent: 591.0, crossAxisExtent: 375.0, crossAxisDirection:
    AxisDirection.right, viewportMainAxisExtent: 591.0, remainingCacheExtent: 841.0, cacheOrigin:
    -0.0)
  geometry: null
This RenderObject had the following descendants (showing up to depth 5):
    child: RenderPadding#ba038 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
      child: RenderFlex#b6450 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        child 1: RenderPadding#74615 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
          child: RenderCSSBox#30185 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
            child 1: RenderDecoratedBox#d969b NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: Null check operator used on a null value
Another exception was thrown: RenderBox was not laid out: RenderShrinkWrappingViewport#4c9ec relayoutBoundary=up7 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
Another exception was thrown: RenderBox was not laid out: RenderIgnorePointer#1fa1b relayoutBoundary=up6 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#71c9a relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
Another exception was thrown: RenderBox was not laid out: RenderPointerListener#49927 relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
Another exception was thrown: RenderBox was not laid out: RenderSemanticsGestureHandler#4fc34 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
Another exception was thrown: RenderBox was not laid out: RenderPointerListener#aef33 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
Another exception was thrown: RenderBox was not laid out: _RenderScrollSemantics#2b3b4 relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
Another exception was thrown: Intrinsics are not available for PlaceholderAlignment.baseline, PlaceholderAlignment.aboveBaseline, or PlaceholderAlignment.belowBaseline.
Another exception was thrown: Null check operator used on a null value
Another exception was thrown: RenderBox was not laid out: RenderShrinkWrappingViewport#4c9ec relayoutBoundary=up7 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
Another exception was thrown: RenderBox was not laid out: RenderIgnorePointer#1fa1b relayoutBoundary=up6 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#71c9a relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
Another exception was thrown: RenderBox was not laid out: RenderPointerListener#49927 relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
Another exception was thrown: RenderBox was not laid out: RenderSemanticsGestureHandler#4fc34 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
Another exception was thrown: RenderBox was not laid out: RenderPointerListener#aef33 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
Another exception was thrown: RenderBox was not laid out: _RenderScrollSemantics#2b3b4 relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
Another exception was thrown: RenderBox was not laid out: RenderShrinkWrappingViewport#4c9ec relayoutBoundary=up7 NEEDS-PAINT
Another exception was thrown: RenderBox was not laid out: RenderShrinkWrappingViewport#4c9ec relayoutBoundary=up7 NEEDS-PAINT

**Comment by huycozy** [comment]
Hi @DiegoMazega 
Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well. Thank you!
