### ISSUE TITLE
Add VirtualDisplay option for AndroidView.

### ISSUE THREAD

**Issue by XuanTung95** [flutter/flutter#130692]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

- I want to create a plugin that uses VirtualDisplay mode as default to show my platform view.
- Currently, Flutter doesn't have the option to use this mode. VirtualDisplay is a fallback mode when HCTL is not available. 
- I want more control over my plugin behavior by choosing the mode.

### Proposal

- Add options to prefer using Virtual Display over other modes

**Comment by stuartmorgan** [comment]
What's the use case here? The only reason VD still exists is for very specific edge cases; if there's another compelling reason to use it we need to know what that is.

**Comment by XuanTung95** [comment]
@stuartmorgan 

I don't know all the cases but I can imagine some cases related to bugs/limitations of HCTL like:
- SurfaceView is created during runtime.
- Bug related to TextureView
- HCTL has bug with native magnifier

VD mode uses other approaches so It has different pros and cons, if plugins do not meet its bugs, why don't let them use it.

**Comment by XuanTung95** [comment]
#112712

If you are done with the asking let's talk about why you don't think this is not necessary.

**Comment by stuartmorgan** [comment]
> #112712

Are you saying that bug doesn't affect VD? That seems surprising; if you've actually tested that and determined that it's not an issue for VD, please add that information to #112712. (If not, it wouldn't be a reason to select VD over TLHC.)

**Comment by stuartmorgan** [comment]
> let's talk about why you don't think this is not necessary.

I have explained why our default position is to not add it; the onus is on the proposal to justify that there is a compelling need that makes it necessary to add despite that. The three issues above are not currently sufficient justification, for the reasons I outlined above.

**Comment by XuanTung95** [comment]
I'm not looking to solve any issue that you asked me to provide.

> permanently maintaining lots of modes

Are 3 modes a lot?

> and having a complex API surface that makes plugin developers choose between a confusing array of options

Spending a few minutes to read the doc of a param won't hurt. The point is what it does, If dev can make use of it, it has a purpose. Chart libraries have hundreds of options, why dev doesn't complain to reduce the options?

> Our goal is to, as much as possible, simplify the platform view system.

I don't think all dev is that lazy and needs your goal

Anyway, I've explained my proposal. About the use case, let's just say I cannot provide a convincing one but thousands of plugins out there may use this option for their own purpose.
If you don't think my proposal is necessary, please close it.

**Comment by johnmccutchan** [comment]
Hi @XuanTung95 thanks for your request. Our goals for Android Platform Views is to reduce the API surface area but only when we can guarantee good behaviour of any android.view.View hierarchy. We would like to automatically switch to VirtualDisplay mode when necessary (by observing the view hierarchy changes) so that application authors don't need to worry about it.

**Comment by johnmccutchan** [comment]
FYI- I hope to have an update on this issue sometime in September.

**Comment by CarGuo** [comment]
In my opinion I would prefer to have a unified API and rendering logic, as the current issue is that different versions of the Flutter SDK may use different behaviors for the same API.


Since we cannot achieve unified rendering logic, it would be better to open it to developers for configuration. Currently, it is neither unified nor controllable, and it is difficult to expect results.

**Comment by johnmccutchan** [comment]
@CarGuo I am not convinced that we can't achieve a unified API and I hope to deliver one this year.

If we cannot achieve it or the amount of work required to achieve it is too high, I agree we should give more explicit controls to developers so they can decide between the implementations.

**Comment by reidbaker** [comment]
@johnmccutchan can this be closed now?

**Comment by johnmccutchan** [comment]
Current status:

- VirtualDisplay is only needed when/if a platform view has a SurfaceView embedded in it.
- VirtualDisplay has low performance and breaks input/a11y handling.
- Capturing VirtualDisplay output into a texture has been flagged as a security/privacy issue by the Android team and we will no longer be able to use this mechanism in the future.

Letting users explicitly pick a mode is problematic, if we had an API that said "Use VirtualDisplay" apps would break on newer versions of Android.

Closing this issue as we need to investigate an alternative to VirtualDisplay mode entirely.
