### ISSUE TITLE
[iOS] Bug when focusing TextField and pulling down iOS Control Center or notifications

### ISSUE THREAD

**Issue by b3nni97** [flutter/flutter#130641]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run the sample
2. Click on the text field and drag down the messages or the control center directly after that while the keyboard appears.
3. Observe that no keyboard appears, but a red box is visible.

Reproduced on an iPhone 14 Pro with iOS 16.3.1

### Expected results

The keyboard should be visible or the MediaQuery.viewInsets should be correctly updated.

### Actual results

3. Observe that no keyboard appears, but a red box is visible.

### Code sample

<details><summary>Code sample</summary>

```dart
runApp(
    MaterialApp(
      home: Scaffold(
        resizeToAvoidBottomInset: false,
        body: SafeArea(
          child: Stack(
            children: [
              Center(child: TextField()),
              Positioned(
                bottom: 0,
                left: 0,
                right: 0,
                child: Builder(builder: (context) {
                  return Container(
                    height: MediaQuery.viewInsetsOf(context).bottom,
                    color: Colors.red,
                  );
                }),
              )
            ],
          ),
        ),
      ),
    ),
  );
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/18357332/4d0e2dcd-3afc-4141-a57c-2283fb0af043

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Flutter (Channel master, 3.13.0-3.0.pre.69, on macOS 12.6 21G115 darwin-arm64, locale en-US)
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @b3nni97 


> Reproduced on an iPhone 14 Pro with iOS 16.3.1

Although I don't have the said device, but I tried on a lesser iOS simulator version on which the reported behavior didn't occur. After clearing the control center or notifications screen, the keyboard was intact in the app.

Can you also try on same iOS version's simulator to see if the behavior still persists or is it only specific to physical device ?

**Comment by b3nni97** [comment]
This bug also happens in native apps, so this is not a direct problem with Flutter.

Closed.
