### ISSUE TITLE
Downloading Gradle Wrapper Timout

### ISSUE THREAD

**Issue by sjx19900424** [flutter/flutter#13064]
C:\Users\Administrator>flutter doctor
Downloading Gradle Wrapper...

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Failed to send crash report due to a network error: SocketException: OS Error: 信号灯超时时间已到
, errno = 121, address = clients2.google.com, port = 51375
Crash report written to C:\Users\Administrator\flutter_17.log;
please let us know at https://github.com/flutter/flutter/issues.

What I can do to solve it

**Comment by maxatcn** [comment]
If you are from China,  you know the network to google.com is not working.  Plz try to find VPN or proxy so that you can get the network working.

**Comment by eseidelGoogle** [comment]
This sounds like https://github.com/flutter/flutter/issues/11681 which lists some possible workarounds.
