### ISSUE TITLE
[go_router] On auth token refresh, GoRouterState.extra comes as null

### ISSUE THREAD

**Issue by muezz** [flutter/flutter#130602]
### Is there an existing issue for this?

- [x] I have searched the [existing package issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Apackage)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### What package does this bug report belong to?

go_router

### What target platforms are you seeing this bug on?

iOS

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

[Lock File](https://gist.github.com/muezz/c078d3736fc5c17162baea53997eaf38)

</details>

### Steps to reproduce

1. Create a class that extends change notifier and use it as a listenable in your go_router instance.
2. Create a few routes and make sure that at least one of them needs some inputs or props when navigating to it.
3. Navigate to this route after starting the app.
4. Wait for your go_router instance to refresh which should be triggered by the change notifier due to some type of state change.

### Expected results

Yesterday I was on version `7.1.1` and everything worked fine. My auth provider and the redirect/refresh mechanism behaved correctly i.e. if the Auth state changed, the app would automatically navigate to the appropriate route.

### Actual results

Today, I upgraded to version `9.0.3` and when I run the app and wait for 3600 seconds (set in Supabase dashboard) for my auth token to refresh and my go_router instance to refresh consequently, I get the following error:
```console
_TypeError (type 'Null' is not a subtype of type '({bool? isUpdating, SearchedRecipe? searchedRecipe})' in type cast)
```
in the following piece of code
```dart
GoRoute(
        path: MyRoutes.recipeDetails.path,
        pageBuilder: (context, state) => CupertinoPage(
          child: RecipeDetailsScreen(
            props: state.extra as RecipeDetailsProps,
          ),
        ),
      ),
```
The above code is from where I am instantiating all of the routes. Also, for context, `RecipeDetailsProps` is a custom type for the record in the error above. This type is irrelevant here because the `GoRouterState.extra` is coming as null which shouldn't be the case. 

### Code sample

<details><summary>Code sample</summary>
I am working in a large code base and I am not sure what to provide here. If anything in particular is required, please let me know and I will provide it.
</details>

### Logs

<details><summary>Logs</summary>

```console
Restarted application in 667ms.
flutter: ***** Supabase init completed Instance of 'Supabase'
[GoRouter] Full paths for routes:
             => /landing
             => /login
             => /home
             => /add-food
             => /food-details
             => /create-food
             => /recipe-details
             => /create-recipe
[GoRouter] setting initial location /home
flutter: **** onAuthStateChange: AuthChangeEvent.signedIn
flutter: **** new token from supabase (removed for privacy reasons)
flutter: ***** SupabaseDeepLinkingMixin startAuthObserver
[GoRouter] pushing /add-food
[GoRouter] pushing /recipe-details
flutter: **** onAuthStateChange: AuthChangeEvent.tokenRefreshed
flutter: **** new token from supabase (removed for privacy reasons)
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following _TypeError was thrown building Builder:
type 'Null' is not a subtype of type '({bool? isUpdating, SearchedRecipe? searchedRecipe})' in type
cast

The relevant error-causing widget was:
  AnimatedSwitcher
  AnimatedSwitcher:file:///Users/abdulmuezz/Documents/Projects/iucalorie/lib/main.dart:206:26
When the exception was thrown, this was the stack:
#0      IucRouter._goRouter.<anonymous closure> (package:iucalorie/router/iuc_router.dart:168:32)
iuc_router.dart:168
#1      RouteBuilder._buildPageForGoRoute (package:go_router/src/builder.dart:363:45)
builder.dart:363
#2      RouteBuilder._buildRecursive (package:go_router/src/builder.dart:223:13)
builder.dart:223
#3      RouteBuilder._buildRecursive (package:go_router/src/builder.dart:231:9)
builder.dart:231
#4      RouteBuilder._buildRecursive (package:go_router/src/builder.dart:231:9)
builder.dart:231
#5      RouteBuilder._buildPages (package:go_router/src/builder.dart:162:7)
builder.dart:162
#6      RouteBuilder.tryBuild (package:go_router/src/builder.dart:135:9)
builder.dart:135
#7      RouteBuilder.build.<anonymous closure> (package:go_router/src/builder.dart:106:33)
builder.dart:106
#8      Builder.build (package:flutter/src/widgets/basic.dart:7531:48)
basic.dart:7531
#9      StatelessElement.build (package:flutter/src/widgets/framework.dart:5156:49)
framework.dart:5156
#10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5086:15)
framework.dart:5086
#11     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
framework.dart:4805
#12     StatelessElement.update (package:flutter/src/widgets/framework.dart:5162:5)
framework.dart:5162
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
framework.dart:3686
#14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
framework.dart:5111
#15     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
framework.dart:4805
#16     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
framework.dart:5417
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
framework.dart:3686
#18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
framework.dart:5111
#19     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
framework.dart:4805
#20     StatelessElement.update (package:flutter/src/widgets/framework.dart:5162:5)
framework.dart:5162
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
framework.dart:3686
#22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
framework.dart:5111
#23     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
framework.dart:4805
#24     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
framework.dart:5417
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
framework.dart:3686
#26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
framework.dart:5111
#27     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
framework.dart:4805
#28     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417:5)
framework.dart:5417
#29     Element.updateChild (package:flutter/src/widgets/framework.dart:3686:15)
framework.dart:3686
#30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111:16)
framework.dart:5111
#31     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
framework.dart:5251
#32     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
framework.dart:4805
#33     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2780:19)
framework.dart:2780
#34     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:903:21)
binding.dart:903
#35     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358:5)
binding.dart:358
#36     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284:15)
binding.dart:1284
#37     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214:9)
binding.dart:1214
#38     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1072:5)
binding.dart:1072
#39     _invoke (dart:ui/hooks.dart:142:13)
hooks.dart:142
#40     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359:5)
platform_dispatcher.dart:359
#41     _drawFrame (dart:ui/hooks.dart:112:31)
hooks.dart:112

════════════════════════════════════════════════════════════════════════════════════════════════════
[log] Error: Read failed
flutter: **** onAuthStateChange: AuthChangeEvent.tokenRefreshed
flutter: **** new token from supabase (removed for privacy reasons)
Another exception was thrown: type 'Null' is not a subtype of type '({bool? isUpdating, SearchedRecipe? searchedRecipe})' in type cast
Another exception was thrown: type 'Null' is not a subtype of type '({bool? isUpdating, SearchedRecipe? searchedRecipe})' in type cast
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4 22F66 darwin-arm64, locale en-PK)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.80.0)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @muezz 
Have you also looked at the recent [breaking changes](https://pub.dev/packages/go_router/changelog#900) along with migration guide in the package to see if that helps in your case or not ?

**Comment by muezz** [comment]
@darshankawar I did have a look and I did not find anything that seemed relevant to the error I am facing but I could very well be wrong.

Also, there were no errors in the code as well when I upgraded the package.

If you have a suspicion regarding any particular breaking change, let me know. I'll have a look at it again.

**Comment by darshankawar** [comment]
Thanks for the update. If you could provide us a minimal code sample that triggers the error, that'll help us to analyze it properly and make it actionable.

**Comment by muezz** [comment]
@darshankawar It took some time but I have been able to recreate this bug in [this repo](https://github.com/muezz/go_router_test.git).

Some important points:
- There is a login page, home page and a child page.
- Initial route is home page.
- When you first open the app, your auth state will be `loggedIn` which implies that your auth state was restored from a previous session or through some other method.
- Right then a timer starts for 30s. After this, the state changes to `loading` and then back to `loggedIn`. This implies that after 30 seconds, the server refreshed the user token. I am trying to recreate the same flow as Supabase where user auth token is refreshed after 3600 seconds.
- When this state changes, it triggers the refresh logic.
- To actually see the bug in action, restart the app, quickly navigate to the child page and then stay there until the auth state refreshes.

I hope the explanation helps. Let me know if you have any questions

**Comment by darshankawar** [comment]
Thanks for the update and taking time to provide the repo. Although it does have third party packages:

```
  flutter_hooks: ^0.18.6
  provider: ^6.0.5
```

We usually look for minimal code sample without third party package implementation so as to narrow down the error to go_router and it isn't occuring due to other packages. So if you could check the same just using go_router and see if the reported error still persists.

**Comment by muezz** [comment]
@darshankawar You can ignore the `flutter_hooks` package. It got left there by mistake. I am not using it anywhere. As for `provider`, it is sort of necessary for this use case. I cannot recreate this scenario otherwise (I think). 

Moreover, I do not think `provider` is the problem here because this bug only appears AFTER I upgrade the `go_router` package from `7.1.1` to `9.0.3`.

**Comment by darshankawar** [comment]
Thanks for the update. Using the repo and details provided [here](https://github.com/flutter/flutter/issues/130602#issuecomment-1641252393), it does throw the reported error.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.10.6, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.10.6 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (5 days ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.13.0-6.0.pre.30, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.13.0-6.0.pre.30 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 33d174d797 (4 hours ago), 2023-07-18 22:36:21 -0400
    • Engine revision 39d60be72f
    • Dart version 3.1.0 (build 3.1.0-324.0.dev)
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by muezz** [comment]
@darshankawar Any updates on this? This is one of the last few bugs that I have to fix before I can launch my app.

**Comment by JohnF17** [comment]
I fixed this issue by putting the data i receive from extra in to a variable within a stateful widget's state.

```dart
class _ChatPageState extends State<ChatPage> {
  late TextEditingController _textEditingController;

  @override
  void initState() {
    super.initState();
    _textEditingController = TextEditingController(text: widget.data);
  }
}
```
In this case I was passing in a string, i've also done this with other data types and it works well, The data is stored within the state's variables so it works like a charm.
Also make sure when you cast the value to your data type make it nullable, 
```dart
ChatPage(
     key: state.pageKey,
     data: (state.extra as String?),
),
```
although the state keeps your data within the state, `extra` will keep sending null.
Hope it helps 🙂

**Comment by JohnF17** [comment]
> I think this would work just fine but it seems like a work-around

@muezz, Yes indeed

> I hope the bug gets resolved permanently.

Well a [PR](https://github.com/flutter/packages/pull/4723) has been sent but has not been merged yet, till then this workaround might be best.

**Comment by liplum** [comment]
> Hello @muezz and @Andreigr0 , I fixed this issue by putting the data i receive from extra in to a variable within a stateful widget's state.
> 
> ```dart
> class _ChatPageState extends State<ChatPage> {
>   late TextEditingController _textEditingController;
> 
>   @override
>   void initState() {
>     super.initState();
>     _textEditingController = TextEditingController(text: widget.data);
>   }
> }
> ```
> 
> In this case I was passing in a string, i've also done this with other data types and it works well, The data is stored within the state's variables and doesn't get called again because its being initialied within the initState method so it won't reset to null and works like a charm. Also make sure when you cast the value to your data type make it nullable,
> 
> ```dart
> ChatPage(
>      key: state.pageKey,
>      data: (state.extra as String?),
> ),
> ```
> 
> although the state keeps your data within the state, `extra` will keep sending null. Hope it helps 🙂

It works. However, As far as I can see, now that the ChatPage is uncontrolled and loses the ability to rebuild if the arguments change.
So, I did a hack with path paramters.
- Using `id` or `key` -- "/product/:id" -- the data can be fetched from web or loaded from local storage in the `ProductPage`.
- Converting the argument to json or whatever can be converted to string -- "/details/:data" or "/details?data=$data" -- then the data can be converted back before passing it to the `DetailsPage`.

I hope this helps if the issue remains unsolved.

**Comment by JohnF17** [comment]
I ended up using [auto_route](https://pub.dev/packages/auto_route) package, don't get me wrong this package is great but the number of open issues to closed ones labelled `triaged-go_router` is unfair, **174 to 15** is just sad for this package, I mean I recently found a huge [bug](#134144) and reported it, mind you this is one of the main functionalities a routing package should do well and it got marked as `P2` for the root issue. 
And as for this issue a [PR]( https://github.com/flutter/packages/pull/4723) has been sent yet not merged. Its as if this package is abandoned but you'll see a minor update just a few days ago 🤨. 

Look i'm not being inconsiderate, I know we all have things to do and other issues have higher priorities than others and I also do understand we could help in some manner (i.e PRs) but c'mon **174 to 15**, do you see the concern so I decided to move on from `go_router` and use `auto_route` instead but regardless thanks for this package.

**Comment by patrikheinonen** [comment]
@JohnF17 I found more bugs myself as well. Ill test auto_route thanks 👍

**Comment by JohnF17** [comment]
Hey @muezz, the [PR](https://github.com/flutter/packages/pull/4723) has been merged and a new update has rolled out, [go_router: 11.0.0](https://pub.dev/packages/go_router/changelog), just letting you know👍.

**Comment by muezz** [comment]
I myself moved to `auto_route` for my current project and have been loving it so far. I prefer go_router's route guard mechanism but this bug was creating more problems in our project so T had no choice. I'll check out v11 in a future project.
