### ISSUE TITLE
FlutterBeep Package code is corrupt

### ISSUE THREAD

**Issue by Davidthai2** [flutter/flutter#130672]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

In the source code  class FlutterBeep statement is inside a method

### Expected results

FlutterBeep.beep() not error

### Actual results

FlutterBeep not resolved in my code

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```FlutterBeep.beep()

</details>


### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]
<img width="439" alt="FB" src="https://github.com/flutter/flutter/assets/31336257/cde33f9b-75f9-4122-a762-f74c145a6539">


</details>


### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```[flutter] flutter doctor -v
[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.22621.1992], locale en-US)
    • Flutter version 3.10.5 on channel stable at C:\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (5 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
    • Android SDK at C:\Users\dlord\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.0.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33205.214
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.80.1)
    • VS Code at C:\Users\dlord\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.44.0

[√] Connected device (1 available)
    • Windows (desktop) • windows • windows-x64 • Microsoft Windows [Version 10.0.22621.1992]

[√] Network resources
    • All expected network resources are available.

• No issues found!
exit code 0


</details>

**Comment by danagbemava-nc** [comment]
FlutterBeep is a third-party package. Any issues you face while using it should be reported on their repo. 

Closing from here as this is not a flutter issue. 

Thank you

**Comment by Davidthai2** [comment]
Thanks for your reply.
I am very much a beginner and have no idea how to contact the repo
Best wishes
David

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
07/18/23,
05:41:37 PM

**Comment by danagbemava-nc** [comment]
This is the repo for flutter beeb https://github.com/trietho/flutter_beep. You can file an issue there.  

However, I would caution against using the package since it has not been updated in 2 years and will likely be incompatible with never versions of flutter

**Comment by Davidthai2** [comment]
Hi
Thanks for your reply.
If they are not maintaining the package, there's probably no use in
contacting them.
Best wishes
David

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
07/21/23,
03:08:34 PM
