### ISSUE TITLE
[flutter_tools] triage backlog issues

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#130635]
To bring the tools team in alignment with the new triage process, we need to get through the backlog of untriaged team-tool issues.

You can use the check marks in this issue, or not. The acceptance criteria will ultimately be getting the following query to 0 open issues: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3Ateam-tool%2Cfyi-tool+-label%3Atriaged-tool+no%3Aassignee+-label%3A%22will+need+additional+triage%22+sort%3Aupdated-asc

The triage instructions are at: https://github.com/flutter/flutter/wiki/Triage#team-issue-triage-process.

<details>
<summary>@christopherfujino</summary>

- [x] #149921
- [ ] #149708
- [ ] #149419
- [ ] #148844
- [x] #148659
- [x] #148473
- [ ] #148332
- [x] #148044
- [x] #147327
- [ ] #146823
- [ ] #146545
- [x] #146130
- [ ] #145991
- [ ] #145772
- [ ] #145640
- [x] #145553
- [ ] #145031
- [ ] #144963
- [ ] #144656
- [ ] #144036
- [ ] #143504
- [ ] #143371
- [ ] #142784
- [ ] #142521
- [x] #141599
- [ ] #141349
- [ ] #141104
- [x] #140047
- [x] #139632
- [ ] #139298
- [ ] #138974
- [ ] #138417
- [x] #138144
- [x] #137990
- [x] #137894
- [x] #137640
- [x] #137184
- [x] #137162
- [x] #136931
- [x] #135985
- [x] #135534
- [x] #131646
- [x] #121565
- [x] #119552
- [x] #115642
- [x] #113739
- [x] #100751
- [x] #98140
- [x] #94548
- [x] #92818
- [x] #90280
- [x] #89166
- [x] #88090
- [x] #86742
- [x] #81051
- [x] #79320
- [x] #78110
- [x] #75611
- [x] #69216
- [x] #59902
- [x] #57497
- [x] #37827
</details>
<details>
<summary>@andrewkolos</summary>

- [x] #149859
- [ ] #149422
- [x] #149194
- [x] #148668
- [x] #148584
- [ ] #148461
- [x] #148157
- [x] #147974
- [x] #147288
- [ ] #146705
- [x] #146184
- [ ] #146009
- [x] #145781
- [x] #145701
- [ ] #145580
- [ ] #145252
- [ ] #145030
- [x] #144898
- [ ] #144287
- [x] #143788
- [ ] #143451
- [ ] #142861
- [ ] #142655
- [ ] #142494
- [ ] #141365
- [ ] #141180
- [ ] #140086
- [ ] #139750
- [ ] #139613
- [ ] #139212
- [ ] #138736
- [ ] #138354
- [ ] #138060
- [ ] #137988
- [ ] #137855
- [x] #137277
- [ ] #137176
- [ ] #137079
- [ ] #136830
- [ ] #135552
- [ ] #135222
- [ ] #130623
- [ ] #119618
- [ ] #117780
- [ ] #114538
- [ ] #101846
- [ ] #100254
- [ ] #97539
- [ ] #94340
- [ ] #92695
- [ ] #89317
- [ ] #88161
- [ ] #86883
- [ ] #84121
- [x] #80407
- [ ] #78261
- [x] #77127
- [ ] #71911
- [ ] #68983
- [ ] #58459
- [ ] #38935
</details>

**Comment by alan-m-thomas** [comment]
idk

**Comment by AlexV525** [comment]
I can also help solve some of them after a quick glance at the whole list, but it won't require an assignment 😄. I'll just go for specific issues.

**Comment by andrewkolos** [comment]
Closing as stale.
