### ISSUE TITLE
Unable to run flutter_gallery example app (fatal: remote error: Git repository not found)

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#13066]
When trying to run the flutter_gallery app I get the following error:

```text
Running "flutter packages get" in flutter_gallery...
Git error. Command: git clone --mirror https://flutter.googlesource.com/gallery-assets /Users/danny/.pub-cache/git/cache/gallery-assets-872fce92eb9f55133a9580149278163532d0d218
Cloning into bare repository '/Users/danny/.pub-cache/git/cache/gallery-assets-872fce92eb9f55133a9580149278163532d0d218'...
fatal: remote error: Git repository not found
```

There's a huge load of log info after that (looks like it tries it multiple times?) which I've trimmed in case it had anything sensitive, but I think the issue is related to the repo. I tried hitting https://flutter.googlesource.com/gallery-assets  in my browser and it just hangs for a while, then gives a 404.

**Comment by eseidelGoogle** [comment]
@sethladd or @HansMuller might know.

**Comment by DanTup** [comment]
Found where the address is coming from - it's the pubspec using it as a source:

https://github.com/flutter/flutter/blob/89405002bc2b642d9a0db20b8288294a4f293257/examples/flutter_gallery/pubspec.yaml#L12

```yaml
  flutter_gallery_assets:
    git:
      url: https://flutter.googlesource.com/gallery-assets
      ref: 6427f36af1bdb2fffaeda1c46d5e52d7b636c93d
```

I'm not sure if the pubspec is now bad or if that URL should work.

**Comment by DanTup** [comment]
That url seems to work now, so this is no longer a problem.
