### ISSUE TITLE
Auto warn in flutter doctor when CocoaPods spec repo is too old

### ISSUE THREAD

**Issue by xster** [flutter/flutter#13069]
Probably similar to how we do it on flutter itself based on date. 

Run `pod repo update` if git log on master spec repo is more than a month old

**Comment by mit-mit** [comment]
@xster what is the consequence if the spec repo being too old? How and where do we fail?

**Comment by xster** [comment]
It'll crash saying something like 
Want plugin X > 1.2.3 but 1.2.3 doesn't exist
or some such

**Comment by mit-mit** [comment]
Oh, that certainly not good. Tagging first-hour and m3.

**Comment by xster** [comment]
<early-alzheimer>Totally forgot I opened the same bug twice #12746 and already fixed it a while back</>
