### ISSUE TITLE
[flutter upgrade] reduce the dependencies and improve the package

### ISSUE THREAD

**Issue by LongXiangGuo** [flutter/flutter#130694]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

As shown in the figure, upgrading so many dependencies in the root package. When there is base package upgrade,It's needed to try the pub get and fix the package dependencies one by one, even some of the package are not used in current platform.

[third_party_dependencies.txt](https://github.com/flutter/flutter/files/12065802/third_party_dependencies.txt)

image is too big, you can rename the third_party_dependencies.txt to third_party_dependencies.dot and run dot -Tsvg -o third_party_dependencies.dot dot -Tsvg -o third_party_dependencies.svg generated it.

<img width="1200" alt="2023-07-17 11 14 26" src="https://github.com/flutter/flutter/assets/16632821/f5519570-19fd-4ecf-b85c-03fb289cb78b">

### Proposal

- Add `futter pub get --platforms`  command  to obtain dependencies from different platforms, reducing the number of dependencies, so that unused platforms should not broken currently used platforms.

- Add`flutter search {package} {package_version}` to query the dependencies of the specified library.

**Comment by stuartmorgan** [comment]
> * Add `futter pub get --platforms`  command  to obtain dependencies from different platforms,

The dependency graph doesn't have a concept of platforms, so there's nothing for that flag to do.

> * Add`flutter search {package} {package_version}` to query the dependencies of the specified library.

Since this isn't specific to Flutter, the right place for such a command would be `pub`; please file this request at https://github.com/dart-lang/pub/issues.

**Comment by LongXiangGuo** [comment]
Thank.
