### ISSUE TITLE
[Impeller] Goldens not rendering on gold but render locally.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#130633]
Goldens added in https://github.com/flutter/engine/pull/43695 are not rendering text in Skia gold but do render text locally.

**Comment by gaaclarke** [comment]
When I execute it locally, individually it renders correctly.
![impeller_Play_AiksTest_DrawScaledTextWithPerspectiveNoSaveLayer_Metal](https://github.com/flutter/flutter/assets/30870216/f3d5b3c0-cc86-4926-a428-eb846de58e35)

**Comment by chinmaygarde** [comment]
This looks fixed. Closing.

**Comment by gaaclarke** [comment]
@chinmaygarde It's rendering correctly locally, it still isn't showing up correctly on skia gold though.  I'm still investigating why.

**Comment by gaaclarke** [comment]
The criteria for closing this should be that the output in https://flutter-engine-gold.skia.org/search?corpus=flutter-engine&include_ignored=false&left_filter=name%3Dimpeller_Play_AiksTest_DrawScaledTextWithPerspectiveNoSaveLayer_Metal&max_rgba=0&min_rgba=0&negative=true&not_at_head=false&positive=true&reference_image_required=false&right_filter=&sort=descending&untriaged=true matches what we see locally.

**Comment by gaaclarke** [comment]
Okay, finally I executed all tests on a release build and this rendered correctly as golden output.  I'm not sure what is happening here.  I'm going to try tweaking the test and see if we can wipe out the golden history.  This should have a black background anyway.

**Comment by gaaclarke** [comment]
Here's an attempt to draw the background so we can see what golden skia sees: https://github.com/flutter/engine/pull/51333

**Comment by gaaclarke** [comment]
Changing the background image didn't seem to flush anything.  It really seems the rendering on CI is different.  I have no idea what's happening.  I also checked the [logs](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8753726933313007985/+/u/test:_Impeller-golden__dart_and_engine_tests_for_host_release/stdout) and it doesn't see to be printing out any error.  I'm not sure what's happening here.

**Comment by gaaclarke** [comment]
I attempting running the golden tests through `run_tests.py` to see if that was the x-factor.  The test still rendered correctly for me locally.

**Comment by gaaclarke** [comment]
I stepped through with a debugger to see if there was a part of the code where we are potentially silently failing on the CPU side, I didn't see anything on the platform thread.

The golden image tests are run in release mode and that means potentially impeller validation failures on the raster thread are silently ignored.  (for example: https://github.com/flutter/engine/blob/c076d21423ea0ad31ed8c1d1afc9e1049888a45d/impeller/entity/contents/text_contents.cc#L78)

We should probably run the impeller_golden_tests on debug engine builds to get validation errors.  We are independently looking into that for other reasons.

**Comment by gaaclarke** [comment]
fixed in https://github.com/flutter/engine/pull/51343 (cc @bdero @chinmaygarde )
