### ISSUE TITLE
can not create project with offline mode

### ISSUE THREAD

**Issue by Silentdoer** [flutter/flutter#130649]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Windows 10 machine is offline
the machine is first install flutter 3.10
then: flutter create demo01 --offline
can't create a project

flutter 3.3.7 works success

### Expected results

create a project, and can run success

### Actual results

can't run, and can't flutter pub get --offline

### Code sample

<details><summary>Code sample</summary>

```dart
none
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
pub.dart:447:7
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
throws in common.dart
```

</details>

**Comment by sujitbalasubramanian** [comment]
Hello @Silentdoer please share the log of the issue and try 
```sh
flutter create --offline demo01
```

**Comment by darshankawar** [comment]
@Silentdoer 
As mentioned above, try using the command as suggested (ex: `flutter create --offline testapp`) and see if it works. If not, provide the complete verbose log that shows any errors it might have received.  (`flutter create --offline testapp -v`)
