### ISSUE TITLE
Getting No Such Method Error while calling an API to display image

### ISSUE THREAD

**Issue by baqirhemani** [flutter/flutter#130686]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I am trying to call the api from coin gecko to display images of the crypto coin, current price, trend over the last 24 hours (through spark line chart) and the change in percentage in last 24 hours.

### Expected results

The result should look something like this

<img width="1223" alt="Screenshot 2023-07-17 at 1 02 30 AM" src="https://github.com/flutter/flutter/assets/32162679/e8568fd3-d25a-41b8-a731-82dbac87934b">

### Actual results

Here is the actual result

<img width="311" alt="Screenshot 2023-07-17 at 1 04 16 AM" src="https://github.com/flutter/flutter/assets/32162679/692ffbc0-6e70-4444-bb3c-f28f90abbfd2">

### Code sample

<details><summary>Code sample</summary>

```dart
Here is my API Function:

List? coinMarket = [];
  var coinMarketList;

  Future<List<CoinModel>?> getCoinMarket() async {
    const url =
        'https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=1&sparkline=true';

    setState(() {
      isRefreshing = true;
    });

    final response = await http.get(
      Uri.parse(url), headers: {
      "Content-Type" : "application/json",
      "Accept" : "application/json",
    },
    );

    setState(() {
      isRefreshing = false;
    });

    if (response.statusCode == 200) {
      var x =  response.body;
      coinMarketList = coinModelFromJson(x);
      setState(() {
        coinMarket = coinMarketList;
      });
    }
    else {
      print(response.statusCode);
    }
  }
  
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>
<img width="968" alt="Screenshot 2023-07-17 at 1 05 32 AM" src="https://github.com/flutter/flutter/assets/32162679/5ae20690-3bf5-493f-b6f2-168e6e8b0efb">
<img width="998" alt="Screenshot 2023-07-17 at 1 05 51 AM" src="https://github.com/flutter/flutter/assets/32162679/af4a0103-f803-4e4d-bd7c-e73d51f1a5ee">
<img width="507" alt="Screenshot 2023-07-17 at 1 06 05 AM" src="https://github.com/flutter/flutter/assets/32162679/0213a122-2592-4e72-ac0e-d74e51ecf4de">
<img width="923" alt="Screenshot 2023-07-17 at 1 06 33 AM" src="https://github.com/flutter/flutter/assets/32162679/36ac188f-2f06-4a9d-9a3e-fc97922c658a">

### Logs

<details><summary>Logs</summary>

```console
<img width="1144" alt="Screenshot 2023-07-17 at 1 09 53 AM" src="https://github.com/flutter/flutter/assets/32162679/0c6240d9-ef54-4cdc-bc27-08a16acb0126">

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>
<img width="1125" alt="Screenshot 2023-07-17 at 1 11 30 AM" src="https://github.com/flutter/flutter/assets/32162679/40834915-e038-4d8d-9c36-6dd521404198">

**Comment by darshankawar** [comment]
@baqirhemani 
Looking at the error, it most likely could be causing due to code implementation, so I suggest you to revisit how you are mapping the incoming data from the api. Also, these kind of issues / questions are better suited to be asked on support channels like StackOverflow.
Closing from here, as this doesn't look like a bug in framework but in code implementation. If you disagree, write in comments and I'll reopen it.
