### ISSUE TITLE
[google-sign-in-web] : Error: Dart library 'dart:html' is not available on this platform.

### ISSUE THREAD

**Issue by Simpler1** [flutter/flutter#130768]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

My app which uses "google sign in" as well as Firebase and which has been running fine for years on Android and web needed to be updated to the latest "google sign in" because authentication and authorization were separated recently.  After making the changes, and using the recommended `renderButton()`, now it will no longer build on Android.

### Expected results

App should build for both Android and web.
App should use google sign in for both authentication and authorization.
App should use Firebase for authorization.

### Actual results

After making changes to enable the flutter app to work with google sign in and firebase for web, now it won't build for Android.  This is the start of the error messages when building for Android.
```
Launching lib/main.dart on sdk gphone x86 in debug mode...
main.dart:1
: Error: Dart library 'dart:html' is not available on this platform.
google_sign_in_web.dart:6
import 'dart:html' as html;
       ^
Context: The unavailable library 'dart:html' is imported through these packages:

    package:flutter_shopping => package:google_sign_in_web => dart:html

    package:flutter_shopping => package:google_sign_in_web => package:flutter_web_plugins => dart:html
```

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:google_sign_in/google_sign_in.dart';
import 'package:google_sign_in_web/google_sign_in_web.dart' as web;
import 'package:google_sign_in_platform_interface/google_sign_in_platform_interface.dart';
...
GoogleSignInPlatform.instance as web.GoogleSignInPlugin).renderButton()
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.6, on Linux Mint 20.3 5.4.0-153-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.80.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @Simpler1, you will need to use conditional imports to get this working on non-web platforms. See the button example in the plugin example code for an example of how to use conditional imports. https://github.com/flutter/packages/blob/main/packages/google_sign_in/google_sign_in/example/lib/src/sign_in_button.dart

See usage of the button here https://github.com/flutter/packages/blob/d4d761b74c78be3d6030edbf4337520fcc5df87d/packages/google_sign_in/google_sign_in/example/lib/main.dart#L211 & import here https://github.com/flutter/packages/blob/d4d761b74c78be3d6030edbf4337520fcc5df87d/packages/google_sign_in/google_sign_in/example/lib/main.dart#L15C1-L16C1

**Comment by Simpler1** [comment]
@danagbemava-nc Thanks.  That worked.  

It's much more complicated now than it used to be.
