### ISSUE TITLE
[CP] Fix ConcurrentModificationError in DDS

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#130739]
### Issue Link

https://github.com/dart-lang/sdk/issues/52932

### Commit Hash

https://dart-review.googlesource.com/c/sdk/+/313782

### Target

beta

### PR Link

https://github.com/flutter/flutter/pull/130740

### Changelog Description

Before iterating over debug client breakpoints, copy the URIs to a new list because the handling within the loop is asynchronous, so other code paths could mutate the hash map storing them (leading to a ConcurrentModificationError).

### Impacted Users

Any Flutter developers doing debugging

### Impact Description

If a user adds/removes a breakpoint while the debugger code is sending the list of breakpoints to an isolate, their flutter tool may crash with a ConcurrentModificationError, and they will lose their entire debugger session (they will have to add their breakpoints from scratch once the tool restarts.

### Workaround

Only add/remove breakpoints before the app has started.

### Risk

low

### Test Coverage

yes

**Comment by CaseyHillers** [comment]
@bkonyi can you review this CP request? If it looks good to you, add the "cp: approved" label.

**Comment by bkonyi** [comment]
LGTM
