### ISSUE TITLE
How to debug dependencies versioning issues? Execution failed for task ':app:transformClassesWithDexForDebug'.

### ISSUE THREAD

**Issue by AdrienLemaire** [flutter/flutter#13079]
## Steps to Reproduce

Follow the codelab tutorial for flutter firebase.
Then try installing firebase_messaging at its latest version:

pubspec.yaml content:
```yml
dependencies:
  flutter:
    sdk: flutter
  image_picker: 0.1.1
  google_sign_in: 0.3.1
  firebase_analytics: 0.0.4
  firebase_auth: 0.2.0
  firebase_database: 0.0.12
  firebase_storage: 0.0.5
  firebase_messaging: 0.0.7
```

## Logs

```
$ flutter run --debug  
Running "flutter packages get" in grablunch...
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzben;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Gradle build failed: 1
```

## Flutter Doctor

```
[✓] Flutter (on Linux, locale en_US.UTF-8, channel alpha)
    • Flutter at /home/dori/Projects/personal/flutter/flutter
    • Framework revision e8aa40eddd (4 weeks ago), 2017-10-17 15:42:40 -0700
    • Engine revision 7c4142808c
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /opt/android-sdk
    • Platform android-26, build-tools 26.0.2
    • ANDROID_HOME = /opt/android-sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at /opt/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)
```

## Question

The Dex exception error is incomprehensible.  After figuring out that the issue arose when adding the new dependency, I blindly tried older versions of firebase_messaging until the version 0.0.4 stopped raising the error.
The error `Multiple dex files define Lcom/google/android/gms/internal/zzben` suggest that firebase_messaging in addition to another dependency define that file. Is there a way to track back what package it is ? In javascript, the lock file shows related dependencies... is there a way to show related dependencies in dart ? Are there good practices on how to upgrade packages ? (I was surprised that the codelab tutorial keep using seemingly old versions for the firebase packages).

Thank you for your help!

**Comment by Fandekasp** [comment]
Following this [stackoverflow thread](https://stackoverflow.com/questions/38202644/no-static-method-zzur-in-firebase-when-i-try-to-use-analytics-with-notificatio), it looks like we should be using the same versions across play services and firebase libraries, which makes sense. But the equivalent flutter libraries don't seem to respect this convention, and I do not know how to match a flutter plugin version to its related firebase/play-services version

**Comment by Hixie** [comment]
No idea what could be causing this, but I'm going to start by guessing it's Firebase-related.

cc @collinjackson

**Comment by kroikie** [comment]
@AdrienLemaire

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/938. Any further collaboration will be done there.

**Comment by BondarenkoStas** [comment]
I guess it's safe to close the issue (in flutterfire mirror) as resolved already. If you disagree, please comment or re-open it.
