### ISSUE TITLE
Gesture Detector on tap down local position dx and dy value are not same in all device

### ISSUE THREAD

**Issue by Mayank8290** [flutter/flutter#130709]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Add an image widget and put it under the GestureDetector widget
2. add onTapDown in GestureDetector and print the local position with details.localPosition
3. run the app on android and ios simulators.
4. tap down on the image, you will see the values of dx and dy are different on both devices.

### Expected results

The expected result should be both dx and dy should same for the image with fixed height and width.

### Actual results

localPosition.dx and localPosition.dy are different in every device , it should be same.

### Code sample

<details><summary>Code sample</summary>

GestureDetector(
         onTapDown: (details) {
        var position = localPosiiton;
        print(position);

     // this position should be the same in every device for the same point in the image.

      },
</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.11, on macOS 13.4.1 22F770820d darwin-arm64, locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.79.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.

</details>

**Comment by dam-ease** [comment]
Hi @Mayank8290. Thanks for filing this issue. I see you are on an older version of flutter, can you upgrade to the latest versions to confirm this issue still persists? If it does, Please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code

**Comment by moffatman** [comment]
How are you sure you tap the same point in the image?

**Comment by Mayank8290** [comment]
the number is written on the image, we have tapped on the same point of the image number 9 (top circle of 9), and we have run the app in the iphone14 Pro max simulator, iPhone SE simulator, and Android simulator at the same time, and tapped via the mouse pointer, found the different between the dx and dy localPoisiton for the same point.

**Comment by Mayank8290** [comment]
> How are you sure you tap the same point in the image?

Thanks for the reply @moffatman, really appreciated it.

the number is written on the image, we have tapped on the same point of the image number 9 (top circle of 9), and we have run the app in the iphone14 Pro max simulator, iPhone SE simulator, and Android simulator at the same time, and tapped via the mouse pointer, found the different between the dx and dy localPoisiton for the same point.

**Comment by Mayank8290** [comment]
one more thing I forgot to mention is, I have added a gesture detector in intractionViewer, seems like when we zoom the image dx and dy got changes and are not the same in every device.

**Comment by Mayank8290** [comment]
> Hi @Mayank8290. Thanks for filing this issue. I see you are on an older version of flutter, can you upgrade to the latest versions to confirm this issue still persists? If it does, Please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code

updated the flutter same issue 
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F770820d darwin-arm64, locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.79.2)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 category.

**Comment by Mayank8290** [comment]
> Thanks for the update @Mayank8290. Please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code to make this issue workable

import 'package:extended_image/extended_image.dart';
import 'package:flutter/material.dart';
import 'package:photo_view/photo_view.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  double imageX = 0.0;
  double imageY = 0.0;
  double imageZoom = 0.0;

  final viewTransformationController = TransformationController();

  @override
  void initState() {
    const zoomFactor = 4.0;
    const xTranslate = 550.0;
    const yTranslate = 1150.0;
    viewTransformationController.value.setEntry(0, 0, zoomFactor);
    viewTransformationController.value.setEntry(1, 1, zoomFactor);
    viewTransformationController.value.setEntry(2, 2, zoomFactor);
    // viewTransformationController.value.setEntry(0, 3, -xTranslate);
    // viewTransformationController.value.setEntry(1, 3, -yTranslate);
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: InteractiveViewer(
      transformationController: viewTransformationController,
      child: GestureDetector(
        onTapDown: (TapDownDetails details) {
          print(details.localPosition);
          print(details.localPosition.dx);
          print(details.localPosition.dy);
        },
        child: Container(
          height: 5055,
          width: 2880,
          color: Colors.lightBlueAccent,
          child: Image.network(
            'https://exposocial.s3.eu-west-1.amazonaws.com/event_map/event_map_1.png',
            height: 5055,
            width: 2880,
          ),
        ),
      ),
    ));
  }
}

**Comment by dam-ease** [comment]
Hi @Mayank8290. Thanks for your response. I'm getting very close values on the different devices, in which the little difference could be due to the fact that I might not be tapping at the exact point. 

iOS
```
flutter: Offset(71.1, 126.1)
flutter: 71.08333206176758
flutter: 126.08333206176758
``` 

Android
```
I/flutter ( 4214): Offset(70.5, 125.3)
I/flutter ( 4214): 70.54119318181819
I/flutter ( 4214): 125.26793323863636
``` 

Is this the same behavior you are experiencing or is there a huge difference in the values?

**Comment by Mayank8290** [comment]
> Hi @Mayank8290. Thanks for your response. I'm getting very close values on the different devices, in which the little difference could be due to the fact that I might not be tapping at the exact point.
> 
> iOS
> 
> ```
> flutter: Offset(71.1, 126.1)
> flutter: 71.08333206176758
> flutter: 126.08333206176758
> ```
> 
> Android
> 
> ```
> I/flutter ( 4214): Offset(70.5, 125.3)
> I/flutter ( 4214): 70.54119318181819
> I/flutter ( 4214): 125.26793323863636
> ```
> 
> Is this the same behavior you are experiencing or is there a huge difference in the values?

Nope, it's not the same behavior..
Android Pixel 2 api 30 simulator -> I/flutter ( 4578): Offset(33.2, 236.0)
iphone 14 Pro max simulator -> flutter: Offset(33.8, 354.8)

See the difference in dy , it's huge for the same point.

<img width="267" alt="Screenshot 2023-07-20 at 1 15 00 PM" src="https://github.com/flutter/flutter/assets/39935418/d5795140-618b-46f1-8628-7c3a36c56928">

I have clicked on middle of X in Exposoc Text.

**Comment by dam-ease** [comment]
Hi @Mayank8290. Thanks for your response. I'm trying to reproduce this and I think the difference in the values could be due to the fact that we can't exactly tap on the same point in both instances.

| Android | iOS |
|--------|--------|
| <video src="https://github.com/flutter/flutter/assets/53122008/d48f7f41-4f41-4f82-8c37-ee6df22666b4"> | <video src="https://github.com/flutter/flutter/assets/53122008/5b51008f-ea64-4036-aeb8-12828ead6c3f"> |

If you still have a different view, can you attach a screen record explaining further?

**Comment by Mayank8290** [comment]
> Hi @Mayank8290. Thanks for your response. I'm trying to reproduce this and I think the difference in the values could be due to the fact that we can't exactly tap on the same point in both instances.
> 
> Android	iOS
>  Screen.Recording.2023-07-20.at.13.26.18.mov 
> 
>  Screen.Recording.2023-07-20.at.13.27.26.mov 
> 
> If you still have a different view, can you attach a screen record explaining further?

Yes, I have a different view try to set const zoomFactor = 4.0; , the original image is not causing the issue but after adding zoomFactor, you will see the difference in values. how can i get the correct value with using zoom.

<img width="656" alt="Screenshot 2023-07-20 at 7 38 04 PM" src="https://github.com/flutter/flutter/assets/39935418/aecfc2a2-1cb5-42cd-8a0b-7df69af32a18">

**Comment by dam-ease** [comment]
Hi @Mayank8290. I'm unable to view the image without setting the `fit` property. So doing that with `zoomFactor = 4.0`. I still get close values. You might want to record your screen as mine so we can get a clearer view of the issue.

| iOS | Android |
|--------|--------|
| <video src="https://github.com/flutter/flutter/assets/53122008/ac428b27-1536-4861-b921-e35f8799e4ca"> | <video src="https://github.com/flutter/flutter/assets/53122008/1c23cfce-3964-4717-b850-57f1ffcd8b20"> |

**Comment by Mayank8290** [comment]
> Hi @Mayank8290. I'm unable to view the image without setting the `fit` property. So doing that with `zoomFactor = 4.0`. I still get close values. You might want to record your screen as mine so we can get a clearer view of the issue.
> 
> iOS	Android
>  Screen.Recording.2023-07-21.at.09.25.34.mov 
> 
>  Screen.Recording.2023-07-21.at.09.29.44.mov

This is the exact piece of code i am using.

`import 'package:extended_image/extended_image.dart';
import 'package:flutter/material.dart';
import 'package:photo_view/photo_view.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  double imageX = 0.0;
  double imageY = 0.0;
  double imageZoom = 0.0;

  final viewTransformationController = TransformationController();

  @override
  void initState() {
    const zoomFactor = 4.0;
    const xTranslate = 550.0;
    const yTranslate = 1150.0;
    viewTransformationController.value.setEntry(0, 0, zoomFactor);
    viewTransformationController.value.setEntry(1, 1, zoomFactor);
    viewTransformationController.value.setEntry(2, 2, zoomFactor);
    viewTransformationController.value.setEntry(0, 3, -xTranslate);
    viewTransformationController.value.setEntry(1, 3, -yTranslate);
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: InteractiveViewer(
      transformationController: viewTransformationController,
      child: GestureDetector(
        onTapDown: (TapDownDetails details) {
          print(details.localPosition);
          print(details.localPosition.dx);
          print(details.localPosition.dy);
        },
        child: Container(
          height: 5055,
          width: 2880,
          color: Colors.lightBlueAccent,
          child: Image.network(
            'https://exposocial.s3.eu-west-1.amazonaws.com/event_map/event_map_1.png',
            height: 5055,
            width: 2880,
            fit: BoxFit.contain,
          ),
        ),
      ),
    ));
  }
}
`
**Android**
https://github.com/flutter/flutter/assets/39935418/4309c532-70e3-4660-a945-b47ab7722350

**IOS**
https://github.com/flutter/flutter/assets/39935418/fea815cd-276f-4a21-873e-ba59847ba1b2

**Comment by moffatman** [comment]
It comes from a misunderstanding of `InteractiveViewer`. First, the widget is laid-out without any scaling. And it uses the incoming constraints. Those large `width` and `height` figures have no effet, since the `Container` and `Image` are limited to the size of `InteractiveViewer`'s parent (the phone screen size). Then afterwards, that layout is scaled.

Now the matter of different y-values for the same point on the image. The iPhone is taller than the Android. So in the initial layout, the image is smaller, and there is more "whitespace" above and below the image. You can be sure of this by looking at the app without any `scaleFactor`. The `localPosition` is relative to the `GestureDetector`, which is outside of this vertical padding. So localPosition on the GestureDetector is really equal to image tap position + image top padding. Note this padding is introduced by the `Image` itself, by fitting to external constraints and applying its `alignment` property (defaulting to `Alignment.center`).

To do what I think you want, you should set `constrained: false` on the `InteractiveViewer`, and use `alignment: Alignment.topLeft` on the `Image`.
