### ISSUE TITLE
This plugin saved my life: https://pub.dev/packages/flutter_exif_rotation

### ISSUE THREAD

**Issue by insane-03** [flutter/flutter#130791]
This plugin saved my life: https://pub.dev/packages/flutter_exif_rotation

Would be nice if this wouldn't be necessary. :(

_Originally posted by @SvenSchoene in https://github.com/flutter/flutter/issues/35334#issuecomment-508024213_

Using the "https://pub.dev/packages/flutter_exif_rotation" plugin, I had an issue where the picture size had increased.

**Comment by darshankawar** [comment]
@insane-03 
Please don't open issue using comments from other issue. If you are facing any issue or requesting a feature request, please use appropriate new issue template, fill out requested details so that we can properly address it.
Closing for now.
