### ISSUE TITLE
Potentially obsolete use of transparent rectangles to fix bounds issues

### ISSUE THREAD

**Issue by flar** [flutter/flutter#130737]
At one point there was an issue with Skia bounds of shadow operations and so the code was sprinkled with calls to draw a transparent rect of the proper bounds to work around the issue.

Now that we are using DisplayList internally instead of SkPictureRecorder, the bounds are correct without the workarounds (also, it is likely that Skia fixed that bug a long time ago and so it was already obsolete even before DisplayList). These code snippets should be removed.

One example: https://github.com/flutter/flutter/blob/0df4496cdb50c4b7d6c42d461c46b3f4c2029d95/packages/flutter/lib/src/rendering/proxy_box.dart#L2137

**Comment by goderbauer** [comment]
> the code was sprinkled with calls

The location you link to is the only one I can find where this work around still exists. Have you seen more?

**Comment by flar** [comment]
> > the code was sprinkled with calls
> 
> The location you link to is the only one I can find where this work around still exists. Have you seen more?

We already removed one of them earlier, so this one represents that sprinkling....

**Comment by flar** [comment]
Here was the previous instance (https://github.com/flutter/flutter/pull/127231). We didn't do a search at the time, we discovered just that one instance by noticing cullable ops being recorded into a DisplayList and fixed just that one case. More recent investigations uncovered the new case documented in this issue.

**Comment by flar** [comment]
I have a list of locations within the framework where I found rendering ops being performed with transparent colors, but they weren't as "deliberate" (nor as demonstrably obsolete) as these 2 cases so I haven't filed them. I was going to look into them further to see if they are due to rendering with default "transparent" widget properties, or due to developers handing us a transparent color and not checking it for transparency and then file them as appropriate, but perhaps I should just file them all and let the framework developers decide whether it was worth pruning them early.
