### ISSUE TITLE
Macros

### ISSUE THREAD

**Issue by Antoinegtir** [flutter/flutter#130722]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Issue title: Added macro support in Flutter

Description of the problem :
Currently, Flutter does not support macros, which limits flexibility and productivity for developers when working on large projects. Macros are powerful tools that automate repetitive tasks and reduce code duplication. Their absence in Flutter makes it difficult to implement certain design patterns and advanced techniques.

We will be offering to add macro support in Flutter, which will allow developers to enjoy the following benefits:

Reduced code duplication: Macros allow you to define reusable blocks of code, which avoids copying and pasting identical code in several places.
Increased productivity: Macros simplify the development process by automating tedious tasks and using the number of lines of code needed to accomplish a given task.
Improved flexibility: Macros allow defining custom functionality and syntactical shortcuts to meet the specific needs of a project or development team.
Easier Maintenance: Macros disable editing and updating code in one place, reducing the chance of errors when manually editing multiple files.
We believe that adding macro support in Flutter would be a significant improvement for the Flutter developer community. This will increase flexibility and productivity, while making it easier to maintain projects.

We therefore prefer the Flutter development team to consider this request and explore the possibility of implementing macro support in the framework. If necessary, we are ready to help in the development process and provide support for this feature.

Thank you very much for your attention. We look forward to seeing Flutter evaluate and continue building high-quality applications with this framework.

### Proposal

Issue title: Added macro support in Flutter

Description of the problem :
Currently, Flutter does not support macros, which limits flexibility and productivity for developers when working on large projects. Macros are powerful tools that automate repetitive tasks and reduce code duplication. Their absence in Flutter makes it difficult to implement certain design patterns and advanced techniques.

We will be offering to add macro support in Flutter, which will allow developers to enjoy the following benefits:

Reduced code duplication: Macros allow you to define reusable blocks of code, which avoids copying and pasting identical code in several places.
Increased productivity: Macros simplify the development process by automating tedious tasks and using the number of lines of code needed to accomplish a given task.
Improved flexibility: Macros allow defining custom functionality and syntactical shortcuts to meet the specific needs of a project or development team.
Easier Maintenance: Macros disable editing and updating code in one place, reducing the chance of errors when manually editing multiple files.
We believe that adding macro support in Flutter would be a significant improvement for the Flutter developer community. This will increase flexibility and productivity, while making it easier to maintain projects.

We therefore prefer the Flutter development team to consider this request and explore the possibility of implementing macro support in the framework. If necessary, we are ready to help in the development process and provide support for this feature.

Thank you very much for your attention. We look forward to seeing Flutter evaluate and continue building high-quality applications with this framework.

**Comment by darshankawar** [comment]
@Antoinegtir Thanks for the report.
Can you take a look at [this](https://github.com/dart-lang/language/blob/main/working/macros/feature-specification.md) and see if it resembles your proposal ?

**Comment by huycozy** [comment]
Thanks for your confirmation. I see this issue is mentioned at https://github.com/flutter/flutter/issues/63323#issuecomment-1407277518. It's an open issue with very detailed information and has lots of comments/upvotes.

So I will close this issue in favor of that one. Please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue.
