### ISSUE TITLE
After releasing the apk the package is not working properly

### ISSUE THREAD

**Issue by fractor16** [flutter/flutter#130706]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

If we are running the apk in emulator or device in debugging mode/developer mode  it working fine but when we are the release the apk using jenkins it is not working

### Expected results

Expected result is that it would be loading properly if i am open the razorpay method it will redirect to the site.

### Actual results

It do not load any page after running on the released apk.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by AkshayStackSum** [comment]
Please provide some code so i can help you.

**Comment by dam-ease** [comment]
Hi @fractor16. Please can you provide more information on this issue:
More specifically, please provide the information indicated below:

- A [complete and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of flutter doctor -v

Thank you!

**Comment by fractor16** [comment]
**Code:-**
import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter_form_builder/flutter_form_builder.dart';
import 'package:nslhub/common/constants.dart';
import 'package:nslhub/common/user_global.dart';
import 'package:nslhub/myTransaction/widgets/html_viewer.dart';
import 'package:nslhub/myTransaction/widgets/physical_layer.dart';
import 'package:webview_flutter/webview_flutter.dart';

class buildFormBuilderHtml extends StatefulWidget {
  final Map displayList;
  final BuildContext context;
  final dynamic fbKeyList;
  final Map physicalLayerFont;
  final Map cuFont;
  final bool isUrl;
  final String value;

  const buildFormBuilderHtml(
      {this.displayList, this.context, this.fbKeyList, this.physicalLayerFont, this.cuFont, this.isUrl, this.value});

  @override
  State<buildFormBuilderHtml> createState() => _buildFormBuilderHtmlState();
}

class _buildFormBuilderHtmlState extends State<buildFormBuilderHtml> {
  WebViewController webViewController = WebViewController();
  Set<Factory<OneSequenceGestureRecognizer>> gestureRecognizers;
  final ValueNotifier<bool> _isLoading = ValueNotifier<bool>(true);
  bool _pageLoaded = false;

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    var initialValue;

    if (widget.displayList['values']?.isNotEmpty == true) {
      if (widget.displayList['uiElement'] == StringConstants.uiElementTypeScormVideo || widget.isUrl == true) {
        var url = widget.value ?? widget.displayList['values'][0];
        initialValue =
            '<html><body><iframe style="height:100%; width:100%" src="$url" id="Iframe"></iframe><script>var frame = document.getElementById("Iframe");frame.onload = function (){ frame.style.height = frame.contentWindow.document.body.scrollHeight + "px";frame.style.width =frame.contentWindow.document.body.scrollWidth + "px";}</script></body></html>';
      } else {
        initialValue = widget.value ?? widget.displayList['values'][0] ?? '';
        if (!(initialValue.toString().startsWith('http') || initialValue.toString().startsWith('<!DOCTYPE html>'))) {
          initialValue = """<!DOCTYPE html>
        <html>
          <head><meta name="viewport" content="width=device-width, initial-scale=1.0"></head>
          <body style='"margin: 0; padding: 0;'>
            <div>
              $initialValue
            </div>
          </body>
        </html>""";
        }
      }

      Set<Factory<OneSequenceGestureRecognizer>> gestureRecognizers = {
        Factory<VerticalDragGestureRecognizer>(
          () => VerticalDragGestureRecognizer(),
        ), // or null
        Factory<HorizontalDragGestureRecognizer>(
          () => HorizontalDragGestureRecognizer(),
        ),
      };
      dynamic valueTransformer(value) {
        return initialValue;
      }

      WebViewController webViewController = WebViewController();

      webViewController
        ..loadRequest(Uri.dataFromString(initialValue, mimeType: 'text/html', encoding: Encoding.getByName('UTF-8')))
        ..setJavaScriptMode(JavaScriptMode.unrestricted)
        // ..setBackgroundColor(Colors.white)
        ..setNavigationDelegate(NavigationDelegate(
          onPageFinished: (String url) {
            if (!_pageLoaded) {
              _pageLoaded = true;
              _isLoading.value = false; // WebView has finished loading
            }
          },
          onNavigationRequest: (NavigationRequest request) async {
            String environment = userGlobal.environment.toLowerCase();
            if (request.url.contains(environment)) {
              return navigateToTransaction(request.url, context);
            }
            return NavigationDecision.navigate;
          },
        ));

      return Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          utils.AttributeName(widget.displayList),
          Padding(
            padding: const EdgeInsets.fromLTRB(0.0, SpaceConstants.widgetMargin12, 0.0, SpaceConstants.widgetMargin12),
            child: GestureDetector(
              onTap: () {
                Navigator.push(
                    context,
                    MaterialPageRoute(
                        builder: (context) => HTMLUIControl(
                              url: initialValue,
                            )));
              },
              child: Container(
                height: MediaQuery.of(context).size.height * 0.2,
                width: MediaQuery.of(context).size.width * 0.8,
                child: Stack(
                  children: [
                    Container(
                      margin: EdgeInsets.only(top: 7.0),
                      alignment: Alignment.center,
                      child: FormBuilderField(
                        name: widget.displayList['id'].toString(),
                        builder: (FormFieldState<String> field) {
                          return SizedBox(
                            height: MediaQuery.of(context).size.height * 0.2,
                            width: MediaQuery.of(context).size.width * 0.8,
                            child: Stack(children: [
                              WebViewWidget(
                                controller: webViewController,
                                gestureRecognizers: gestureRecognizers,
                              ),
                              ValueListenableBuilder<bool>(
                                valueListenable: _isLoading,
                                builder: (context, isLoading, child) {
                                  return isLoading
                                      ? const Center(
                                          child: CircularProgressIndicator(),
                                        )
                                      : const SizedBox.shrink();
                                },
                              ),
                            ]),
                          );
                        },
                      ),
                    ),
                    Align(
                      alignment: Alignment.topRight,
                      child: TextButton(
                          child: Row(
                            mainAxisAlignment: MainAxisAlignment.spaceAround,
                            children: [
                              Expanded(child: Text('')),
                              Icon(Icons.fullscreen, color: Color.fromARGB(255, 156, 156, 156))
                            ],
                          ),
                          onPressed: () {
                            Navigator.push(
                                context,
                                MaterialPageRoute(
                                    builder: (context) => HTMLUIControl(
                                          url: initialValue,
                                        )));
                          }),
                    )
                  ],
                ),
              ),
            ),
          ),
        ],
      );
    } else {
      return buildTileFormBuilderTextField(widget.displayList,
          physicalLayerFont: widget.physicalLayerFont, cuFont: widget.cuFont);
    }
  }
}

**Comment by fractor16** [comment]
![image](https://github.com/flutter/flutter/assets/74827495/98c00880-611f-4272-b72a-9da35abcdb8c)

**Comment by AkshayStackSum** [comment]
Can you elaborate your question i am not getting it.

**Comment by fractor16** [comment]
When i run my app in emulator or connecting my device through data cable the webview_flutter package is working fine 
but when i release the apk same for it , it not working properly

**Comment by dam-ease** [comment]
Hi @fractor16. Thanks for your response and patience. Please can you share your `flutter doctor -v` output as a comment and not a screenshot. Also, what version of the `webview_flutter` package are you currently using??

**Comment by AkshayStackSum** [comment]
> When i run my app in emulator or connecting my device through data cable the webview_flutter package is working fine but when i release the apk same for it , it not working properly

Can you please attach the whole code so i can debug better i can see there is 
**utils.AttributeName(widget.displayList),** so please add that as well or just copy paste whole class for better understanding.
