### ISSUE TITLE
ThemeData: Doc on `useMaterial3` wrongly says it defaults to `false`

### ISSUE THREAD

**Issue by chrisbobbe** [flutter/flutter#130761]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run the code sample, which renders a `Text` under a `ThemeData` that accepts `useMaterial3`'s default value. The text tells you what the ambient `useMaterial3` is.
2. See that it says "true".
3. Read [the doc on `ThemeData.useMaterial3`](https://api.flutter.dev/flutter/material/ThemeData/useMaterial3.html).

### Expected results

The doc should say that `useMaterial3` defaults to `true`, not `false`.

### Actual results

The doc says that `useMaterial3` defaults to `false`.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const ExampleApp());

class ExampleApp extends StatelessWidget {
  const ExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Theme(
        data: ThemeData(),
        child: Center(
          child: Builder(builder: (context) => Text(Theme.of(context).useMaterial3.toString())))));
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

(no errors expected or observed)

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel main, 3.13.0-3.0.pre.112, on macOS 13.4.1 22F82 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.80.1)
[✓] Connected device (3 available)
    ! Error: Chris’s Apple Watch needs to connect to determine its availability. Check the connection between the
      device and its companion iPhone, and the connection between the iPhone and Xcode. Both devices may also need to
      be restarted and unlocked. (code 1)
[✓] Network resources

• No issues found!
```

</details>

**Comment by chrisbobbe** [comment]
cc @HansMuller as the author of https://github.com/flutter/flutter/commit/157660afc, which changed the default. There's some related text in the doc that you might be the best person to update; otherwise I'd go ahead and send a PR directly. 🙂

**Comment by HansMuller** [comment]
Sorry, I should have updated the docs! I will land a fix ASAP. Thanks for pointing this out!
