### ISSUE TITLE
Proposal: `ListView` fade items that leave the viewport

### ISSUE THREAD

**Issue by FMorschel** [flutter/flutter#130797]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I have an UI with mainly these widgets:

```dart
CustomScrollView(
  physics: const AlwaysScrollableScrollPhysics(
    parent: BouncingScrollPhysics(),
  ),
  slivers: [
    SliverFillRemaining(
      hasScrollBody: true,
      child: ListView(
        children: [],
      ),
    ),
  ],
),
```

(on my actual UI, the Listview is wrapped in a `Column` and on top of it there is a "title".)

This is intended so that the list will be centred on the screen when it has few items and it will fill the screen when there are multiple items. 

I have 64 pixels of padding between the "title" and the actual list, and I believe that fading the list when it gets there would be a great effect.

### Proposal

I would like to propose a new "clipBehavior" of sorts, a `Fade` animation when scrolling outside the viewport. 

We could give it an extent or something like that for how long the fade animation should be applied.

**Comment by darshankawar** [comment]
Thanks for the report @FMorschel 
Have you checked if there's already a community package that offers this feature ?
For example: https://pub.dev/packages/fading_edge_scrollview

Also, see if [this](https://stackoverflow.com/questions/51066628/fading-edge-listview-flutter) helps to achieve your use case or not.

**Comment by FMorschel** [comment]
The StackOverflow answer is what I was looking for! Thank you!

PS: I know this is probably not the place to put this, but do you know if [this (a question I made on StackOverflow about scrolling and this widget layout)](https://stackoverflow.com/questions/76712640/flutter-controll-scrolling-priority) can be done with Flutter alone or do I need to use external packages? Or maybe you think I should create a new issue about it?

**Comment by darshankawar** [comment]
Thanks for the update and good to know the SO answer helped you to resolve. 

> if [this (a question I made on StackOverflow about scrolling and this widget layout)](https://stackoverflow.com/questions/76712640/flutter-controll-scrolling-priority) can be done with Flutter alone or do I need to use external packages? Or maybe you think I should create a new issue about it?

It seems there's an answer to it already using external package so if that helps you to achieve your use case, you should use the package because not every functionality and feature can be implemented in the framework itself. If you still think, you'll need more details about it, feel free to open a new issue.

Closing this one.
