### ISSUE TITLE
Children StatefulWidget(s) get recreated when switching back to the same tab the second time in TabBarView

### ISSUE THREAD

**Issue by iocat** [flutter/flutter#13080]
This seems to be a semantic issue? I tried to maintain state of a StatefulWidget in a TabBarView. When I view StatefulWidget in a tab, I changed the tab content, and therefore, I changed the state. Then, I switch to another tab. When I switch back to the tab with its state changed, the state is gone, and recreated. 

## Steps to Reproduce
Here's a simple program to reproduce the issue. I expect the state to remain when I move back to the same tab.

```dart
import 'package:flutter/material.dart';

void main() => runApp(new App());

class App extends StatefulWidget{
  @override
  AppState createState() => new AppState();

}

class AppState extends State<App>{

  final List<Widget> _tabs = [ new TabContent(), new Text("Other")];

  @override
  Widget build(BuildContext ctx){
    return new MaterialApp(home: new DefaultTabController(
        length: 2,
        child: new Scaffold(
            appBar: new AppBar(
              bottom: new TabBar(
                tabs: [new Tab(text: "Stateful"), new Tab(text: "Other",)],
              ),
            ),
            body: new TabBarView(
              children: _tabs,
            ))));
  }
}

class TabContent extends StatefulWidget{
  static int stateRecreationCounter = 0;
  @override
  TabContentState createState(){
    stateRecreationCounter ++;
    debugPrint("Create state $stateRecreationCounter times");
    return new TabContentState();
  }
}

class TabContentState extends State<TabContent>{
  @override
  Widget build(BuildContext ctx){
    return new Text("Create state x${TabContent.stateRecreationCounter} times");
  }
}

```

## Logs
```
I/flutter ( 3420): Create state 1 times
I/flutter ( 3420): Create state 2 times
I/flutter ( 3420): Create state 3 times
I/flutter ( 3420): Create state 4 times
I/flutter ( 3420): Create state 5 times
I/flutter ( 3420): Create state 6 times
I/flutter ( 3420): Create state 7 times
I/flutter ( 3420): Create state 8 times
I/flutter ( 3420): Create state 9 times
....
```

## Flutter Doctor
```
[✓] Flutter (on Mac OS X 10.13.1 17B48, locale en-US, channel unknown)
    • Flutter at /Users/felix/flutter
    • Framework revision 9a0d4cf75b (3 days ago), 2017-11-14 18:50:15 -0800
    • Engine revision 242ce44af5
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at /Users/felix/Library/Android/sdk
    • Platform android-27, build-tools 27.0.1
    • ANDROID_HOME = /Users/felix/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[-] iOS toolchain - develop for iOS devices (Xcode 9.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.1, Build version 9B55
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.5)
    • Flutter plugin version 18.4
    • Dart plugin version 172.4343.25

Error executing simctl: -6
dyld: Library not loaded: /Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator
  Referenced from: /Applications/Xcode.app/Contents/Developer/usr/bin/simctl
  Reason: image not found

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)
```

**Comment by franciscojunior** [comment]
Hi all!

Sorry for bothering you with this, but do you have any update on this problem?
I faced this problem recently and I as a workaround, I put my TextEditingController in the widget itself, instead of the state so I could keep the text fields state inside them. I know it is not the recommended procedure but I couldn't find a better way to handle it.
I'm new to Flutter, so it may have a much better way to handle this. Any advice is very welcome!

Thanks in advance.

**Comment by adriancmurray** [comment]
I think I am understanding everyone here, and the answer I've gotten is to wrap the tabviews in a stack offstage to keep them rendered. Now, I just have to figure out how to do exactly that...

**Comment by varundroid** [comment]
I can't believe this is an expected behavior. We definitely need a solution for this.

**Comment by zoechi** [comment]
@Hixie

**Comment by Hixie** [comment]
We intentionally unload tabs that aren't visible to save memory. But you can force them to stay around by using the KeepAlive machinery. See `AutomaticKeepAliveClientMixin` for the simplest way to do that. That should work with the `PageView` used with tabs; let me know if it doesn't.

**Comment by iocat** [comment]
@zoechi Hi, I saw the label "waiting for customer response," but I have no comment on this issue since I haven't used Flutter for a year now. Hope that somebody can elaborate on this issue and further start a discussion on how to resolve it. 

However, I strongly believe that the semantic of a Stateful widget should not be broken by a component because this introduces surprised behaviors that developers weren't expecting to get. 

Thanks!

**Comment by zoechi** [comment]
@iocat I wouldn't see this as surprising behavior. 
Any widget can be rebuilt at any time. That's stated explicitly in the `build()` docs.
If you need to keep state over the lifetime of widgets just keep it outside of widgets, like in Redux or Scoped Model, ...

**Comment by varundroid** [comment]
Thanks for your reply, I really appreciate it. But both Android and iOS
provides us this functionality out of the box so it's surprising for me not
to see this in built in the framework. Anyways I found a way around it for
the moment.

**Comment by nailgilaziev** [comment]
If my tabs have scrolls with some position I need extract this state outside of tabs?

**Comment by diegoveloper** [comment]
You can persist your tabs if you need.
https://medium.com/@diegoveloper/flutter-persistent-tab-bars-a26220d322bc

**Comment by Syphonjr** [comment]
@Hixie 
I tried AutomaticKeepAliveMixin, but whenever I switch from first to second tab, my first tab's inputs are unfocusable.

**Comment by zoechi** [comment]
@Syphonjr I'd suggest to ask on StackOverflow

**Comment by zoechi** [comment]
It doesn't look like there is anything actionable left in this issue.
