### ISSUE TITLE
flutter or atom-flutter package not found in Atom.

### ISSUE THREAD

**Issue by iPatel007** [flutter/flutter#13081]
@eseidelGoogle  

Actually I'm new for flutter!
Recently [downloaded **Atom** editor](https://atom.io/) and following [this tutorial for flutter app development and how to work with Atom editor.](https://flutter-io-staging-69a8a.firebaseapp.com/setup/#atom-editor)

When I reached at **2nd** step to install **flutter** package and try to search but **fluter / atom-flutte** package not found from **Install Packages**. I'm trying to install last 2 days but not get success. What flutter is not longer with Atom editor ? or I'm missing any step or going wrong ? Please guide me how can develop my first demo app by Atom editor?

**Note :** For **Dart** package installation is successfully done.

**Comment by sethladd** [comment]
Apologies, you somehow found an old version of the website.

Flutter now works well with Android Studio and VS Code. Atom is no longer actively supported. Please see https://flutter.io/ide-setup/ for how to get setup with Android Studio.

If you want to use VS Code, please see https://marketplace.visualstudio.com/items?itemName=DanTup.dart-code

**Comment by eseidelGoogle** [comment]
The Atom plugin is pretty old and unmaintained at this point.  I'd recommend using either IntelliJ:
https://flutter.io/ide-setup/
or Visual Studio Code:
https://marketplace.visualstudio.com/items?itemName=DanTup.dart-code
both of which have more active maintainers.

**Comment by iPatel007** [comment]
@eseidelGoogle and @sethladd  Thank you  for your support and cleared me now happy with **IntelliJ CE**.

**Comment by sandrobilbeisi** [comment]
IntelliJ is horrible : takes ages to start and crashes constantly ...

I really miss the flutter plugin for Atom

**Comment by iPatel007** [comment]
@sandrobilbeisi Actually go with VC Code it's easy to use and also lightweight 👍

**Comment by james-lawrence** [comment]
seriously android studio is terrible. I spend more time dealing with it breaking than writing actual code.
