### ISSUE TITLE
Painting Path.cubicTo() artifact

### ISSUE THREAD

**Issue by VolodymyrLykhonis** [flutter/flutter#13088]
## Steps to Reproduce

I am using CustomPainter to paint a graph. It does the job but sometimes (specific values?) it introduces artifact (see screenshot). It seems that if I use Path.cubicTo() with same x & y (basically lineTo(x,y)) on the last index values (last x & y) then artifact goes away, but the result is not what I am looking for.

Not sure if I am doing something wrong, or it may be some issue that needs to be address.

Much appreciated for any feedback! 

See artifact (darker, background like gradient on bottom of the path)

<img width="284" alt="screen shot 2017-11-19 at 10 28 11 am" src="https://user-images.githubusercontent.com/881338/32994013-fc454d18-cd15-11e7-9743-ac2d963f96cd.png">

```java
//index: Xs and Ys
//0: -57.3207602188823x303.42857142857144
//1: -3.5262540495904773x231.23538647047133
//2: 101.38419366645583x117.71082208108332
//3: 288.83907450036156x0.0
//4: 1231.6938216335097x303.42857142857144

final Path path = new Path();

final double startIntensity = 0.5;
final double endIntensity = 0.5;

double x = getX(dataSet[0]);
double y = getY(dataSet[0]);
double prevX = x;
double prevY = y;
double prevPrevX = x;

path.moveTo(x, y);

for (int i = 0; i < dataSet.length; i++) {
  x = getX(dataSet[i]);
  y = getY(dataSet[i]);

  double x1 = prevX + (x - prevX) * startIntensity;
  final double y1 = prevY;

  double x2 = prevX + (x - prevX) * endIntensity;
  final double y2 = y;

  if (y > prevY) {
    final double xx1 = prevX + (prevX - prevPrevX) * startIntensity;

    if (x1 > xx1) x1 = xx1;
    x2 = x;
  }

  path.cubicTo(x1, y1, x2, y2, x, y);

  prevPrevX = prevX;
  prevX = x;
  prevY = y;
}

return path
  ..lineTo(getX(dataSet[0]), getY(dataSet[0]))
  ..close();
```

## Logs

```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                0.9s
Resolving dependencies...                             1.0s
Running 'gradlew assembleDebug'...                    7.2s
Built build/app/outputs/apk/app-debug.apk (23.2MB).
Installing build/app/outputs/apk/app.apk...           1.9s
Syncing files to device Android SDK built for x86...      
D/        ( 6511): HostConnection::get() New Host Connection established 0xa6ca5d40, tid 6535
W/        ( 6511): Unrecognized GLES max version string in extensions: ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 
D/EGL_emulation( 6511): eglMakeCurrent: 0xa4016240: ver 2 0 (tinfo 0xa6c83820)
E/flutter ( 6511): [ERROR:flutter/shell/gpu/gpu_surface_gl.cc(189)] WARNING: Could not create offscreen surface. This device or emulator does not support color correct rendering. Fallbacks are in effect. Colors on this device will differ from those displayed on most other devices. This warning will only be logged once.
D/EGL_emulation( 6511): eglMakeCurrent: 0xa4016300: ver 2 0 (tinfo 0xa42fef80)
D/FA      ( 6511): Connected to remote service
V/FA      ( 6511): Processing queued up service tasks: 4

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:8102/
For a more detailed help message, press "h". To quit, press "q".
V/FA      ( 6511): Inactivity, disconnecting from the service
I/zygote  ( 6511): Do partial code cache collection, code=30KB, data=22KB
I/zygote  ( 6511): After code cache collection, code=30KB, data=22KB
I/zygote  ( 6511): Increasing code cache capacity to 128KB
```

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.13.1 17B48, locale en-US, channel alpha)
    • Flutter at /Users/Vladimir/Library/flutter
    • Framework revision e8aa40eddd (5 weeks ago), 2017-10-17 15:42:40 -0700
    • Engine revision 7c4142808c
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.0)
    • Android SDK at /Users/Vladimir/Library/Android/sdk
    • Platform android-27, build-tools 27.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.1, Build version 9B55
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.2.6)
    • Flutter plugin version 19.1
    • Dart plugin version 172.4343.25

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)
```

**Comment by eseidelGoogle** [comment]
One way to test might be to try with https://fiddle.skia.org/ . We mostly just expose the Skia apis directly.

**Comment by VolodymyrLykhonis** [comment]
Nice tool! Thanks. Will try and report back.

**Comment by VolodymyrLykhonis** [comment]
Tested with code below. It does look right (as expected). Not sure what if it actually means there is some issue in Flutter. I have used same values I get in the app code.

Options

Width: 1280
Height: 350

```
void draw(SkCanvas* canvas) {
SkPath pt;

double x0 = -57.3207602188823;
double y0 = 303.42857142857144;
double x1 = -3.5262540495904773;
double y1 = 231.23538647047133;
double x2 = 101.38419366645583;
double y2 = 117.71082208108332;
double x3 = 288.83907450036156;
double y3 = 0.0;
double x4 = 1231.6938216335097;
double y4 = 303.42857142857144;

pt.moveTo(x0, y0);
pt.cubicTo((x0 + x0) / 2, y0, (x0 + x0) / 2, y0, x0, y0);
pt.cubicTo((x0 + x1) / 2, y0, (x0 + x1) / 2, y1, x1, y1);
pt.cubicTo((x1 + x2) / 2, y1, (x1 + x2) / 2, y2, x2, y2);
pt.cubicTo((x2 + x3) / 2, y2, (x2 + x3) / 2, y3, x3, y3);
pt.cubicTo((x3 + x4) / 2, y3, (x3 + x4) / 2, y4, x4, y4);
pt.lineTo(x0, y0);
pt.close();

SkPaint p;
p.setColor(SK_ColorRED);
p.setAntiAlias(true);

canvas->drawPath(pt, p);
}
```

**Comment by eseidelGoogle** [comment]
https://fiddle.skia.org/c/c42a1c99b160305abf1ac699de40029c is a direct link to said fiddle.

**Comment by eseidelGoogle** [comment]
@VolodymyrLykhonis I'm not sure if your dart code with loop is producing the same drawing commands as you used in your fiddle.  You might try running the fiddle code in Flutter and seeing if that draws correctly.  If it doesn't, then we definitely have Flutter bug. :)

**Comment by VolodymyrLykhonis** [comment]
That was going to be my next step! I will follow up on this. Thank you @eseidel !

**Comment by Hixie** [comment]
We may have a Flutter bug either way (e.g. if we have a Skia bug :-) ).

**Comment by VolodymyrLykhonis** [comment]
Got the code running. Looks okay by itself, will validate other parameters, for now closing it.

```dart
void main() => runApp(new MyCustomPaint());

class MyCustomPaint extends StatelessWidget {
  final MyCustomPainter _painter = new MyCustomPainter();

  @override
  Widget build(BuildContext context) {
    return new CustomPaint(
      size: Size.infinite,
      painter: _painter,
    );
  }
}

class MyCustomPainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    double x0 = -57.3207602188823;
    double y0 = 303.42857142857144;
    double x1 = -3.5262540495904773;
    double y1 = 231.23538647047133;
    double x2 = 101.38419366645583;
    double y2 = 117.71082208108332;
    double x3 = 288.83907450036156;
    double y3 = 0.0;
    double x4 = 1231.6938216335097;
    double y4 = 303.42857142857144;

    Path pt = new Path();

    pt.moveTo(x0, y0);
    pt.cubicTo((x0 + x0) / 2, y0, (x0 + x0) / 2, y0, x0, y0);
    pt.cubicTo((x0 + x1) / 2, y0, (x0 + x1) / 2, y1, x1, y1);
    pt.cubicTo((x1 + x2) / 2, y1, (x1 + x2) / 2, y2, x2, y2);
    pt.cubicTo((x2 + x3) / 2, y2, (x2 + x3) / 2, y3, x3, y3);
    pt.cubicTo((x3 + x4) / 2, y3, (x3 + x4) / 2, y4, x4, y4);
    pt.lineTo(x0, y0);
    pt.close();

    Paint p = new Paint();
    p.color = Colors.red;

    canvas.drawPath(pt, p);
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) => false;
}
```

**Comment by VolodymyrLykhonis** [comment]
Here is updated data points. I was able to reproduce it.

```dart
void main() => runApp(new MyCustomPaint());

class MyCustomPaint extends StatelessWidget {
  final MyCustomPainter _painter = new MyCustomPainter();

  @override
  Widget build(BuildContext context) {
    return new CustomPaint(
      size: new Size(411.42857142857144, 329.42857142857144),
      painter: _painter,
    );
  }
}

class MyCustomPainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    Path path = new Path();
    path.moveTo(123.50931216161452, 303.42857142857144);
    path.cubicTo(123.50931216161452, 303.42857142857144, 123.50931216161452, 303.42857142857144,
        123.50931216161452, 303.42857142857144);
    path.cubicTo(163.9791580500681, 303.42857142857144, 163.9791580500681, 241.83474987766206,
        204.44900393852166, 241.83474987766206);
    path.cubicTo(
        290.6990449864386, 241.83474987766206, 290.6990449864386, 0.0, 376.9490860343555, 0.0);
    path.cubicTo(463.1991270822724, 0.0, 728.927470928722, 303.42857142857144, 728.927470928722,
        303.42857142857144);
    path.lineTo(123.50931216161452, 303.42857142857144);
    path.close();

    Paint paint = new Paint();
    paint.color = Colors.red;

    canvas.drawPath(path, paint);
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) => false;
}
```

**Comment by eseidelGoogle** [comment]
The question I then ask myself is does this set of points repro inside a fiddle.skia.org?  If it does, this is obviously a Skia bug (which we can raise with that team).

In any case, *thank you* for the report and all the debugging work you've done!

**Comment by VolodymyrLykhonis** [comment]
@eseidelGoogle it seems to be fine on [fiddle](https://fiddle.skia.org/c/fb154523a03b122b1fe845e606d63677). I may be doing something wrong with rendering, not sure.

If you have any ideas I will try it ASAP.

**Comment by eseidelGoogle** [comment]
@chinmaygarde might have some ideas.

**Comment by eseidelGoogle** [comment]
Cary pointed out "If I am reading it correctly, then there's one draw that generates two colors of red. That's nothing Skia will do even when it's buggy, as far as I know. It could be in the device driver, though."

The red in question appears to be fully opaque:
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/colors.dart#L398

**Comment by eseidelGoogle** [comment]
@VolodymyrLykhonis is your latest capture from an Android Emulator or device?  could you paste your updated `flutter doctor` output?

**Comment by VolodymyrLykhonis** [comment]
@eseidelGoogle Thank you for looking into this. Capture is from emulator, but I saw similar issue on PH1. I do not have access to my laptop at this moment, I will try to share doctor and a capture of the code above from PH1 and Nexus 5X (I may be able get Nexus 6P too).

**Comment by eseidelGoogle** [comment]
The last set of code did not reproduce for me in an iOS simulator:
![simulator screen shot nov 29 2017 2 24 37 pm](https://user-images.githubusercontent.com/11857803/33402341-1edab37e-d511-11e7-9212-a130f20cf8c2.png)

**Comment by VolodymyrLykhonis** [comment]
Checked on PH1, getting same as on emulator.

**Comment by eseidelGoogle** [comment]
Yes, this repros for me on the Android emulator:
![screenshot_1512262501](https://user-images.githubusercontent.com/11857803/33521245-9903963a-d781-11e7-8bd2-b63fc4d27988.png)

```
Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)
```

I have HAXM installed, but I haven't restarted yet so I suspect it's disabled.  Not sure that matters here.

Here is my surfaceflinger dump if that's helpful.  I suspect this is a Skia bug @brianosman https://gist.github.com/eseidelGoogle/d9c6ceb79d0960f6ed6de27302c9372f

**Comment by brianosman** [comment]
Thanks for the repro case - I've managed to repro this on a Nexus 6P as well, so I can try to narrow it down. I strongly suspect our tessellating path renderer - we recently saw a similar issue with that code.

**Comment by VolodymyrLykhonis** [comment]
Thank you for looking into this. Later today I will provide 3-4 points. Looks like it I can reproduce on 3 points only, and have another set of 3 points which doesn't show the issue. Let me know if this helps with debugging.

Thank you!

**Comment by brianosman** [comment]
FYI: Skia bug has been created: https://bugs.chromium.org/p/skia/issues/detail?id=7372

**Comment by brianosman** [comment]
This is fixed in Skia by https://skia-review.googlesource.com/c/skia/+/87341, which is not yet rolled into Flutter.

**Comment by VolodymyrLykhonis** [comment]
After recent pull, the issue seems to be gone!

Thank you for all efforts! Closing it.

**Comment by zhen1991** [comment]
Hi guys!
my question is also on a custom printer flutter!
i don't know where I can ask my question !
my question is about drawing an arrow inside a circle but I can only Draw the top of the arrow but not able to draw the bottom of the arrow my code is look this:





import 'package:flutter/material.dart';
import 'dart:math' as math;

void main() {
  runApp(new MaterialApp(home: new HomePage()));
}

class HomePage extends StatefulWidget {
  @override
  HomePageState createState() => new HomePageState();
}

class HomePageState extends State<HomePage> {

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
        body: new Stack(
            children: <Widget>[
              new Positioned(
                  bottom: 10.0,
                  left: 16.0,
                  right: 20.0,
                  top: 19.0,
                  child: new CustomPaint(
                    painter: new StockArrowPainter(),
                  )
              ),
            ]
        )
    );
  }
}

class StockArrowPainter extends CustomPainter {

  final Color color=Colors.red;

   final double percentChange= 90;

   @override
   void paint(Canvas canvas, Size size) {
    final Paint paint = Paint()..color = color;
    paint.strokeWidth = 3.0;
    paint.hashCode;
    const double padding = 5.0;
    assert(padding > paint.strokeWidth / 2.0); // make sure the circle remains inside the box
    final double r = (size.shortestSide - padding) / 2.0; // radius of the circle
    final double centerX = padding + r;
    final double centerY = padding + r;

    // Draw the arrow.
    const double w = 40.0;
    double h = 40.0;
    double arrowY;
    if (percentChange < 0.0) {
      h = -h;
      arrowY = centerX + 4.0;
    } else {
      arrowY = centerX - 1.0;
    }
    final Path path = Path();
    path.moveTo(centerX, arrowY - h); // top of the arrow
    path.lineTo(centerX + w, arrowY + h);
    path.lineTo(centerX - w, arrowY + h);
    path.close();
    paint.style = PaintingStyle.fill;
    canvas.drawPath(path, paint);



      path.moveTo(centerX, arrowY); // bottom of the arrow

      path.lineTo(centerX ,arrowY + h );
      path.lineTo(centerX , arrowY + h);
      path.close();
      paint.style = PaintingStyle.stroke;
      canvas.drawPath(path, paint);
    
    //canvas.drawLine( 400, 200, paint);
    // Draw a circle that circumscribes the arrow.
    paint.style = PaintingStyle.stroke;

    canvas.drawCircle(Offset(centerX, centerY), r, paint);

  }

  @override
  bool shouldRepaint(StockArrowPainter oldDelegate) {
    return oldDelegate.color != color
        || oldDelegate.percentChange != percentChange;
  }
}

class StockArrow extends StatelessWidget {
  const StockArrow({ Key key, this.percentChange }) : super(key: key);

  final double percentChange;

  int _colorIndexForPercentChange(double percentChange) {
    const double maxPercent = 10.0;
    final double normalizedPercentChange = math.min(percentChange.abs(), maxPercent) / maxPercent;
    return 100 + (normalizedPercentChange * 8.0).floor() * 100;
  }

  Color _colorForPercentChange(double percentChange) {
    if (percentChange > 0)
      return Colors.green[_colorIndexForPercentChange(percentChange)];
    return Colors.red[_colorIndexForPercentChange(percentChange)];
  }
  @override
  Widget build(BuildContext context) {
    return Container(
        width: 40.0,
        height: 40.0,
        margin: const EdgeInsets.symmetric(horizontal: 5.0),
        child: CustomPaint(
            painter: StockArrowPainter(
              // TODO(jackson): This should change colors with the theme

            )
        )
    );
  }
}
 
i will be grateful if someone can help me or give me some tips.
thnx;)

**Comment by zoechi** [comment]
@zhen1991 I'd suggest you ask on StackOverflow.
