### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by RothaSoeurn** [flutter/flutter#130845]
======== Exception caught by widgets library =======================================================
The following assertion was thrown building BlocBuilder<WishlistCubit, WishlistState>(dependencies: [_InheritedProviderScope<WishlistCubit?>], state: _BlocBuilderBaseState<WishlistCubit, WishlistState>#88fb7):
'package:flutter/src/widgets/scroll_view.dart': Failed assertion: line 116 pos 15: 'semanticChildCount == null || semanticChildCount >= 0': is not true.

**Comment by darshankawar** [comment]
@RothaSoeurn 
When opening an issue, please try to use new issue template and fill out requested details so that we'll have enough info to work with.
Closing for now, as no details are provided. Just posting error message isn't enough to properly address the issue.
