### ISSUE TITLE
[Impeller] Support Android Platform Views.

### ISSUE THREAD

**Issue by johnmccutchan** [flutter/flutter#130892]
Tracking issue for supporting Android Platform Views in Impeller.

Some tasks:

- [x] Introduce PlatformViewRenderTarget abstraction
- [x] Refactor code existing code and extract SurfaceTexturePlatformViewRenderTarget
- [x] Add an ImageReaderPlatformViewRenderTarget
- [x] Wire ImageReaderPlatformViewRenderTarget into GL texture
- [x] Wire ImageReaderPlatformViewRenderTarget into Vulkan texture

**Comment by chinmaygarde** [comment]
Should we file separate issues for the subtasks or is the umbrella bug enough for now?

**Comment by johnmccutchan** [comment]
I'm fine with the current umbrella bug. I'm making progress on items 3/4 and right now.
