### ISSUE TITLE
Dismal help for `flutter pub cache`

### ISSUE THREAD

**Issue by WorikQCI** [flutter/flutter#130848]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

`flutter help pub cache`

### Expected results

Something useful

### Actual results

```
% flutter help pub cache
Work with the Pub system cache.
This runs the "pub" tool in a Flutter context.

Global options:
-h, --help                  Print this usage information.
-v, --verbose               Noisy logging, including all shell commands executed.
                            If used with "--help", shows hidden options. If used with "flutter doctor", shows additional diagnostic information. (Use "-vv"
                            to force verbose logging in those cases.)
-d, --device-id             Target device id or name (prefixes allowed).
    --version               Reports the version of this tool.
    --suppress-analytics    Suppress analytics reporting for the current CLI invocation.
    --disable-telemetry     Disable telemetry reporting when this command runs.

Usage: flutter pub cache [<arguments...>]


Run "flutter help" to see global options.
```

### Code sample

a

### Screenshots or Video

a

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4 22F66 darwin-arm64, locale en-AU)
    • Flutter version 3.10.6 on channel stable at /Users/user/Documents/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (6 days ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.73.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • iPad (mobile)   • 00008103-000229CE1E31001E • ios            • iOS 16.5.1 20F75
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

**Comment by danagbemava-nc** [comment]
Hi @WorikQCI,

I believe if you want to view the help for the commands/subcommands you need to add the `--help` flag. So for instance, to get the help menu that you wanted, you would have to type 

`flutter pub cache --help`. 

Could you try that instead?

**Comment by WorikQCI** [comment]
Duh!
`flutter pub cache -h`

```
% flutter pub cache -h    
Work with the system cache.

Usage: dart pub cache [arguments...]
-h, --help    Print this usage information.

Available subcommands:
  add      Install a package.
  clean    Clears the global PUB_CACHE.
  repair   Reinstall cached packages.

Run "dart help" to see global options.
See https://dart.dev/tools/pub/cmd/pub-cache for detailed documentation.
```

Yes.
