### ISSUE TITLE
☂️ Update Flutter tooling to work with Xcode 15 / iOS 17

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#130819]
Umbrella issue to track progress in making Flutter compatible with Xcode 15 / iOS 17.

- [x] Use Xcode automation for debug and profile mode - https://github.com/flutter/flutter/pull/131865
- [x] Use devicectl for release mode - https://github.com/flutter/flutter/pull/131865
- [x] Use idevicesyslog to get logs - https://github.com/flutter/flutter/pull/131865
- [x] Throw error message for screenshot to normal Flutter users - https://github.com/flutter/flutter/pull/131865
- [ ] Use XCUIApplication to take screenshots for our CI

Original issue: https://github.com/flutter/flutter/issues/128531

**Comment by tologonkudaiberdiuulu** [comment]
I think it should be P0 issue. Because I'm not to able to build app

**Comment by jmagman** [comment]
@vashworth The high priority work here seems done.  Can you file a new issue for the remaining `XCUIApplication` screenshot work (probably a P2?), and we can close this umbrella.

**Comment by vashworth** [comment]
> @vashworth The high priority work here seems done. Can you file a new issue for the remaining `XCUIApplication` screenshot work (probably a P2?), and we can close this umbrella.

Good idea. Filed https://github.com/flutter/flutter/issues/143218.
