### ISSUE TITLE
Compiling Flutter Engine for iOS results the different binary size in release mode

### ISSUE THREAD

**Issue by 0xcj** [flutter/flutter#130851]
We recently encountered an issue when using version 3.7.12 and would like to seek your help.
We noticed Flutter 3.7 used some private APIs of Apple, which carries the risk of rejection. The specific issue link is: [https://github.com/flutter/flutter/issues/124008](https://github.com/flutter/flutter/issues/124008). To avoid this risk, we hope to fix this issue based on 3.7.12. We compiled the iOS Engine according to the official tutorial, but the generated binary (/artifacts/Flutter.xcframework/ios-arm64/Flutter.framework/Flutter) is 87KB smaller than the official version. The size of the binary we compiled locally is 9,107,128 bytes, while the official 3.7.12 engine size is 9,196,672 bytes.
 
Our operation steps are as follows:
 

1. Create an empty engine folder and a .gclient file with the following content:
```
solutions = [
  {
    "managed": False,
    "name": "src/flutter",
    "url": "[git@github.com](mailto:git@github.com):0xcj/engine.git@1a65d409c7a1438a34d21b60bf30a6fd5db59314",
    "custom_deps": {},
    "deps_file": "DEPS",
    "safesync_url": "",
  },
]
```

 
2. sync the code.
```gclient sync```
 
3. simulator-x64:
```./flutter/tools/gn --ios --runtime-mode debug --simulator --no-lto```
 
4. simulator-arm64:
```./flutter/tools/gn --ios --runtime-mode debug --simulator --simulator-cpu=arm64 --no-lto```
 
5. release:
```./flutter/tools/gn --ios --runtime-mode release```
 
I didn't use the --prebuilt-impellerc parameter. The tip for this parameter indicates I should not use it: “PREBUILT_IMPELLERC Absolute path to a prebuilt impellerc. Do not use this outside of CI or with impellerc from a different engine version”.
 
6. Compile:
```ninja -C out/ios_debug_sim && ninja -C out/ios_debug_sim_arm6 && ninja -C out/ios_release```
 
7. Generate framework:
 ```
  cd mypath/engine/src/flutter/sky/tools
 
  python3 create_full_ios_framework.py
 
  --dst /mypath/engine/src/out/ios/ios-release-framework
 
  --arm64-out-dir /mypath/engine/src/out/ios_release
 
  --simulator-x64-out-dir /mypath/engine/src/out/ios_debug_sim
 
  --simulator-arm64-out-dir /mypath/engine/src/out/ios_debug_sim_arm64
 
  --dsym —strip
```
 
Since the create_full_ios_framework.py script didn't strip symbols correctly, I used the code from this PR for this file: [https://github.com/flutter/engine/pull/41097](https://github.com/flutter/engine/pull/41097)
 
Our Xcode version is 14.2. The whole building process has no errors.
 
The above are the operations we performed. Looking forward to your reply. Please advise if we missed any critical configurations, or if there are more complete building workflows for the release environment engine for reference.
 
We would be extremely grateful if you could provide any help or suggestions to make the self-compiled engine consistent with the officially released binary. This is very important for our app release.

**Comment by darshankawar** [comment]
> We noticed Flutter 3.7 used some private APIs of Apple, which carries the risk of rejection. The specific issue link is: #124008. To avoid this risk, we hope to fix this issue based on 3.7.12.

@0xcj 
The linked issue was fixed just couple of months ago and must be on master version, but not in latest stable (3.10) yet.
I am not sure if the fix can be pushed to 3.7.12 release. Maybe you can try to use the commit in that version and see if it helps in your case, or else try running your scenario on latest master to see if it resolve your issue or not.

**Comment by 0xcj** [comment]
As you mentioned, we are trying to fix this issue based on version 3.7.12, and everything is going smoothly so far. However, we are uncertain if the commands and parameters being used by the build engine are correct for a production environment. It would be greatly appreciated if a tutorial could be provided for configuring the production build environment.

**Comment by darshankawar** [comment]
> However, we are uncertain if the commands and parameters being used by the build engine are correct for a production environment. It would be greatly appreciated if a tutorial could be provided for configuring the production build environment.

Can you elaborate on what exactly are you looking for in a tutorial and what uncertainties you think could occur ?

**Comment by 0xcj** [comment]
I am uncertain if the parameters I am using with gn/ninja are correct. I need to compile an engine in release mode.



1. Create an empty engine folder and a .gclient file with the following content:
```
solutions = [
  {
    "managed": False,
    "name": "src/flutter",
    "url": "git@github.com:0xcj/engine.git@1a65d409c7a1438a34d21b60bf30a6fd5db59314",
    "custom_deps": {},
    "deps_file": "DEPS",
    "safesync_url": "",
  },
]
```
 
2. sync the code.
```gclient sync```
 
3. simulator-x64:
```./flutter/tools/gn --ios --runtime-mode debug --simulator --no-lto```
 
4. simulator-arm64:
```./flutter/tools/gn --ios --runtime-mode debug --simulator --simulator-cpu=arm64 --no-lto```
 
5. release:
```./flutter/tools/gn --ios --runtime-mode release```
 
I didn't use the --prebuilt-impellerc parameter. The tip for this parameter indicates I should not use it: “PREBUILT_IMPELLERC Absolute path to a prebuilt impellerc. Do not use this outside of CI or with impellerc from a different engine version”.
 
6. Compile:
```ninja -C out/ios_debug_sim && ninja -C out/ios_debug_sim_arm6 && ninja -C out/ios_release```
 
7. Generate framework:
 ```
  cd mypath/engine/src/flutter/sky/tools
 
  python3 create_full_ios_framework.py
 
  --dst /mypath/engine/src/out/ios/ios-release-framework
 
  --arm64-out-dir /mypath/engine/src/out/ios_release
 
  --simulator-x64-out-dir /mypath/engine/src/out/ios_debug_sim
 
  --simulator-arm64-out-dir /mypath/engine/src/out/ios_debug_sim_arm64
 
  --dsym —strip
```

**Comment by huycozy** [comment]
The difference in binary size may be due to the parameters you are using. Per this note from [Compiling-the-engine](https://github.com/flutter/flutter/wiki/Compiling-the-engine) guideline:

>Remove --no-lto if you care about performance or binary size; unfortunately it results in a much slower build.

Perhaps `--no-lto` flag could make this difference. Please try removing it to see what changes.

**Comment by 0xcj** [comment]
I only used the --no-lto parameter in the --simulator mode, it will not affect the --release mode. I just want to know if the parameters I am using with gn/ninja are correct. I need to compile an engine in release mode."

**Comment by JamieWang1234** [comment]
We have also encountered the same problem, can the fix be pushed to the stable version?

**Comment by stuartmorgan** [comment]
> We compiled the iOS Engine according to the official tutorial, but the generated binary (/artifacts/Flutter.xcframework/ios-arm64/Flutter.framework/Flutter) is 87KB smaller than the official version. The size of the binary we compiled locally is 9,107,128 bytes, while the official 3.7.12 engine size is 9,196,672 bytes.

Those instructions are for building locally; they aren't intended to be a way to exactly replicate our production builds. All of our [recipes](https://cs.opensource.google/flutter/recipes) and bot runs are public if you want to attempt to exactly replicate everything about the environment (exact toolchain, source versions, compile options, packaging, etc.), but documenting all of that separately from the scripts themselves is out of scope (since it would almost certainly never actually stay exactly in sync with the scripts.)

> I just want to know if the parameters I am using with gn/ninja are correct.

"Correct" isn't really a well-defined concept here; if you are doing your own build, you can use whatever flags work for your use case. If you mean "identical to the official builds", referring to the build recipes is the best option.
