### ISSUE TITLE
Runner quit unexpectedly

### ISSUE THREAD

**Issue by Sanchit-Batra** [flutter/flutter#130877]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1.   Access the attached Github repo
2.  Fork it and run it on your computer

### Expected results

I expect the main.dart file to run and show to the app in the IOS simulator. 

### Actual results

As soon as I run the main.dart file. It does the process but after showing the below-given log it shows a big error message saying "Runner quit unexpectedly".  I have reinstalled Flutter as well as Android Studio but it's just not working. 

### Code sample

Please check the GitHub repository: https://github.com/Sanchit-Batra/World-Clock

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

</details>
<img width="998" alt="Screenshot 2023-07-19 at 5 13 00 PM" src="https://github.com/flutter/flutter/assets/97723736/d9f9eae5-8d43-400d-8fe5-2a153663701a">

### Logs

<details><summary>Logs</summary>

```console
Launching lib/main.dart on iPhone 14 Pro Max in debug mode...
Running Xcode build...
Xcode build done.                                           10.6s
[VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(35)] Using the Impeller rendering backend.
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4 22F66 darwin-arm64, locale
    en-US)
    • Flutter version 3.10.6 on channel stable at /Users/sanchitbatra/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (7 days ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/sanchitbatra/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.69.20230703

[✓] Connected device (2 available)
    • iPhone 14 Pro Max (mobile) • B99E9B8C-45F5-4B81-94D5-FE403B6CDCC0 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-arm64 • macOS 13.4 22F66 darwin-arm64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by stuartmorgan** [comment]
As it shows in the stack (in the future, please follow the instructions in the template and include text, not pictures of text, when filing issues), the crash is an exception from `GADApplicationVerifyPublisherInitializedCorrectly`, which is from `google_mobile_ads`. If you believe you have followed the setup instructions for that plugin correctly and it's still throwing an exception, you'll need to file an issue against that plugin.
