### ISSUE TITLE
 Text widget wraps words incorrectly when there is a "/' sign

### ISSUE THREAD

**Issue by orangebokov** [flutter/flutter#130856]
### Steps to reproduce

Create a text widget similar to this:
Text('Неправильно заданы имя / email / пароль.')

### Expected results

When reducing the screen size after wrapping text to another line, it should not jump back

### Actual results

Text jumps back and forth

### Code sample

Text('Неправильно заданы имя / email / пароль.')

### Screenshots or Video

https://github.com/flutter/flutter/assets/39646729/ce1e2181-28af-400a-95b5-e455a0bbe905

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.2 22D49 darwin-arm64, locale ru-RU)
    • Flutter version 3.10.5 on channel stable at /Users/user/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (5 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed
      instructions).

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.2 22D49 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.133

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by dam-ease** [comment]
Hi @orangebokov. Thanks for filing this issue. I guess the issue being referred to here is the jumping back and forth of the text when the screen size is being reduced which occurs only on desktop (macOS). Can you confirm I described your issue correctly?

| macOS | Web |
|--------|--------|
| <video src="https://github.com/flutter/flutter/assets/53122008/a9ced2f6-83e7-4444-824b-2289e97efed6"> | <video src="https://github.com/flutter/flutter/assets/53122008/a98be776-d673-4474-870e-29aa68476380"> |

**Comment by orangebokov** [comment]
@dam-ease 
Yes that's right

**Comment by gspencergoog** [comment]
@rusino Does this look like an `SkParagraph` issue with linebreaking? (Desktop Triage)

**Comment by Rusino** [comment]
Whatever SkParagraph does it does it equally to all platforms, iOS or Windows or anything else.
Line breaking algorithm works with the given font metrics the same way everywhere.
The text in a code sample is OK, I checked, no ZWSP symbols or anything else that could cause a problem.
What about the widget itself? In theory it could do something like that.
There is nothing much I can do without an example in dart reproducing the issue.
