### ISSUE TITLE
context.go(); Rebuilds the statefull widget.

### ISSUE THREAD

**Issue by UnreALi** [flutter/flutter#130827]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I am developing an application with bloc and go_router. I manage api calls and bloc events via routes. I just discovered it because my stafull widgets are creating unnecessary requests.
A context.go() called from a statefull widget; regenerates the redirected page.

### Expected results

The redirected page is not regenerated.

### Actual results

Unnecessary rebuild

### Code sample

<details><summary>Code sample</summary>

```dart
class MyTestWidget extends StatefulWidget {
  const MyTestWidget({super.key});
  final viewPage = AppPage.serviceList;
  @override
  State<MyTestWidget> createState() => _MyTestWidgetState();
}

class _MyTestWidgetState extends State<MyTestWidget> {
  var _viewPage;

  @override
  void initState() {
    // TODO: implement initState
    _viewPage = widget.viewPage;
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        (() {
          switch (_viewPage) {
            case AppPage.serviceList:
              print('do trigger bloc event');
              return Placeholder();
            default:
              return Placeholder();
          }
        })(),
        ElevatedButton(
          onPressed: () {
            // AppRouter.router.go(RouteNames.config);
            context.go(RouteNames.config);
          },
          child: const Text('ClickToMe'),
        ),
      ],
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
I/flutter (25140): do trigger bloc event
I/flutter (25140): go config page
I/flutter (25140): do trigger bloc event
```

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.4, on macOS 13.3.1 22E772610a darwin-x64, locale
    tr-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.77.3)
[✓] Connected device (2 available)
[✓] Network resources

**Comment by UnreALi** [comment]
I noticed that using Navigator on the instance `Navigator.push(
            //   context, ...)`  or accessing the go router through a static `AppRouter.router.go(RouteNames.config);`  does not trigger the rebuild. I still have the problem when I use static instance in my real application. I want to continue using go_router as I plan to deeplink the route I am trying to access.
Why might the statefull widget have such a behavior?

**Comment by huycozy** [comment]
Hi @UnreALi 
Which `go_router` version are you using currently? There is a release version ([9.0.0](https://pub.dev/packages/go_router/changelog#900)) that solved issue related to rebuild issue. If you are using a lower version, please try upgrading to that version or latest one and check if issue still persists or not. 

Otherwise, if you are on the latest version but still seeing this issue, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code, along with `Steps by steps` to reproduce the issue so that we may verify this properly. Thank you!

**Comment by lukaszciastko** [comment]
Hi. I am also seeing this issue. I am using go_router: ^9.0.0. The stateful Scaffold I'm using gets recreated only the first time a user navigates, but then it's being reused.
