### ISSUE TITLE
InteractiveViewer weird behavior on mobile web browser. 

### ISSUE THREAD

**Issue by smohser** [flutter/flutter#130809]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

```
1. create an interactive viewer, inside a fullscreen container : 
Container(
  width: screenWidth, height: screenHeight,
  child: InteraciveViewer(
      child: Stack(
          children: [
             //add a lot positioned children
             for(int i=0; i<1000; i++)
               Positioned(top: randomTop, left: randomLeft,
                    child: Container(width: 10, height, 10, shape: circle, color: colors.red, 
                                         child: Inkwell(
                                                onTap(){} //on tap here works perfectly until the bug happens and then it stops working
                                          )
                               ),
               )
          ]
      )
  )
)
```
2. run on a mobile browser
3. sometimes it runs perfectly, just refresh the browser a couple of times the bug (see 4) surely will pop up
4. try to pan and scale until interactiveViewer is stuck in a mode where any touch you do, even with one finger, causes it to scale just a little bit and behave weirdly, and also the children inside interactiveViewer stops responding to touch events

### Expected results

I expect interactiveViewer to scale on scale and pan on pan :) . if you runs on windows and scale with the mouse wheel and pan with the mouse, everything is perfect, i need the same bahavior on windows to be on mobile browser but with touch gestures instead of mouse gestures, 

### Actual results

described in steps to reproduce

### Code sample

described in steps to reproduce

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Flutter Doctor output

[√] Flutter (Channel stable, 3.10.2, on Microsoft Windows [Version 10.0.22621.1992], locale en-IL)
    • Flutter version 3.10.2 on channel stable at C:\Users\smohs\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (8 weeks ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\smohs\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32414.318
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.80.0)
    • VS Code at C:\Users\smohs\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1992]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 114.0.5735.199
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 114.0.1823.82

[√] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by darshankawar** [comment]
Thanks for the report @smohser 
Looking at the code sample you provided, you have `Stack` as a child of `InteractiveViewer` which in turn has `Positioned` as one of the children inside `Stack` . Basically, you are not using InteractiveViewer's properties such as `boundaryMargin` and others. Also you have set `InteractiveViewer` as a child of `Container` so probably not properly implementing the `InteractiveViewer`. See [this](https://api.flutter.dev/flutter/widgets/InteractiveViewer-class.html#widgets.InteractiveViewer.1) example and check if using it, you get same behavior or not.
If yes, please provide us complete runnable code sample that we can directly use to verify it properly.

**Comment by smohser** [comment]
Thanks for the quick response. I attached a complete example, I would like to remind you that the behavior is not consistent, and sometimes you need to refresh the browser and try again to hit the issue.
[interactive_viewer_issue.zip](https://github.com/flutter/flutter/files/12092973/interactive_viewer_issue.zip)

**Comment by smohser** [comment]
update: I corrected the code according to https://github.com/justinmc/flutter-go/blob/master/lib/main.dart and have not seen the issue again yet. It is a bit confusing that there is a very specific layout for interactiveViewer to work as expected. I guess you could close the issue and update the example. sorry for wasting your time:).

**Comment by huycozy** [comment]
Hi @smohser
Thanks for your response with sample code but I see it's still complicated with 3rd package usage (getx) along with others widgets like `AnimatedCrossFade`, `Transform`.

In order to make the issue reproducible and better investigated later, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party packages or complex code. Please complete the sample code you provided in the original comment. Thank you!

**Comment by smohser** [comment]
Hi, I update the code as you requested, still same issue:
1. removed 3rd party packges
2. removed animated crossfade and transform
3. all the code is in main.dart 90 lines of code i hope this helps :). model folder is not important i guess.

updated code :
[updated_code.zip](https://github.com/flutter/flutter/files/12104975/updated_code.zip)

**Comment by huycozy** [comment]
Thanks for your update with a more minimal sample code. I check this issue on mobile browser, and I notice the FPS drop as well. And I see there's an open issue addressing the case you described https://github.com/flutter/flutter/issues/60550.

Closing this issue in favor of that issue, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!

**Comment by smohser** [comment]
Hi,are you so sure it is the same issue :) ? I tried to create a lot less objects, like 50 really simple widgets inside interactive viewer, and still the same issue. anyway it looks like the other issue is gonna take a lot of years to fix, so best option is to stop using interactive viewer altogether :)

**Comment by smohser** [comment]
Hi, ok thanks for your time. Although I am not convinced it is the same issue, I am seeing this behavior also when the interactive viewer has very few children, like 10. and only on ios not android!
