### ISSUE TITLE
[engine][spell_check] iOS 17 shows native text editing UI

### ISSUE THREAD

**Issue by hellohuanlin** [flutter/flutter#130818]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Just an app with dummy text field. 
2. Type an incorrectly spelled word
3. Hit space, and then backspace (this is the tricky part)

Tried on iOS 17, but not sure if it's the same on iOS 16 

@camsim99 Likely we just need to disable the logic on framework side for iOS. 

### Expected results

There shouldn't be the android style prompt

### Actual results

The android style prompt appears at the top left corner of the screen

![Simulator Screenshot - iPhone 14 Pro Max - 2023-07-18 at 11 41 48](https://github.com/flutter/flutter/assets/41930132/3cb03137-88fd-4720-9a28-2ece635418f1)

### Code sample

NA

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Flutter Doctor output

[✓] Flutter (Channel main, 3.13.0-5.0.pre.50, on macOS 13.4.1 22F82 darwin-x64, locale en)
    • Flutter version 3.13.0-5.0.pre.50 on channel main at /Users/huanlin/Desktop/flutter/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision 94179a8e3f (2 hours ago), 2023-07-18 12:42:10 -0400
    • Engine revision c27658cc5a
    • Dart version 3.1.0 (build 3.1.0-323.0.dev)
    • DevTools version 2.25.0

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/huanlin/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio with Blaze.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.80.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version null

[✓] Connected device (4 available)
    • iPhone 14 Pro Max (mobile) • 51C118C7-8C4D-4D79-83DC-EFDD697A205D • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • iPhone 14 Pro (mobile)     • A78551E6-5D9B-4745-BA4C-BDCFAD4DDFE2 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 13.4.1 22F82
      darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome
      114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

**Comment by camsim99** [comment]
@hellohuanlin Did you reproduce this issue with a `TextField` or `CupertinoTextField`?

**Comment by hellohuanlin** [comment]
@camsim99 the example comes from https://github.com/flutter/flutter/blob/master/dev/integration_tests/ios_platform_view_tests/lib/main.dart#L161-L163

**Comment by camsim99** [comment]
Ah okay. The Android style is expected for `TextField`s but that position is not. cc @justinmc looks like a bug with the positioning of the Android style spell check suggestions toolbar on iOS.

**Comment by hellohuanlin** [comment]
Note that when I select a text in native iOS, a similar edit menu actually shows up. So we may still want this feature, but just after making the selection.

**Comment by hellohuanlin** [comment]
possibly related: https://github.com/flutter/flutter/issues/130170

**Comment by huycozy** [comment]
Reproduced this issue on iOS 17 on the latest Flutter stable and master channels with a minimal `TextField()` widget. It doesn't appear on iOS 16.

The issue still persists if I turn on or off `Predictive` in `Settings>General>Keyboard` (a case mentioned in the linked issue above https://github.com/flutter/flutter/issues/130170).

<details>
<summary>Demo video</summary>

https://github.com/flutter/flutter/assets/104349824/47d267dc-f45d-4132-bc6d-d8879bd4ad54

</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.10.6 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (5 hours ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.13.0-7.0.pre.57, on macOS 13.4.1 22F770820d darwin-x64, locale en-VN)
    • Flutter version 3.13.0-7.0.pre.57 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 83e5aca1c9 (88 minutes ago), 2023-07-20 21:26:17 -0400
    • Engine revision b5a6b1c9cb
    • Dart version 3.1.0 (build 3.1.0-332.0.dev)
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D                         • android-arm64  • Android 11 (API 30)
    • iPhone (mobile)  • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.7.2 19H218
    • macOS (desktop)  • macos                                    • darwin-x64     • macOS 13.4.1 22F770820d darwin-x64
    • Chrome (web)     • chrome                                   • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by camsim99** [comment]
> possibly related: https://github.com/flutter/flutter/issues/130170

Ah yes this doesn't look like the spell check toolbar we implemented, so this likely related to autocorrect.

**Comment by justinmc** [comment]
I also didn't see this on iOS 16.  I'll install 17 and try it there in a bit.

Some quick things I noticed:

  * From the screenshot it looks like the iOS-style spell check toolbar to me, not the Android one.  Though the arrow is strangely not visible.
  * By default, TextField should show the context menu UI of the current platform.  It shouldn't show any Android UI on iOS unless the developer has manually set that up via contextMenuBuilder or spellCheckConfiguration.
  * Spell check is disabled by default if I'm not mistaken ([iOS spell check default code](https://github.com/flutter/flutter/blob/0919fb86f1b61727ebcc39ff6ea4203cbfce0381/packages/flutter/lib/src/cupertino/text_field.dart#L893)).

<details>

<summary>Here's the app I'm using to test this just for completeness:</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: const Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextField(
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

**Comment by hellohuanlin** [comment]
You can also play around with my example, which is [https://github.com/flutter/flutter/blob/master/dev/integration_tests/ios_platform_view_tests](https://github.com/flutter/flutter/blob/master/dev/integration_tests/ios_platform_view_tests/lib/main.dart)

**Comment by justinmc** [comment]
Alright I was able to reproduce this on the iOS 17 simulator.  

<details>

<summary>Video of bug</summary>

https://github.com/flutter/flutter/assets/389558/07efc2c5-7cc2-4054-8a59-484de41e7c6a

</details>

  * The menu that appears at the top is the autocorrect menu drawn natively by iOS.
  * Notice also that the last character typed is highlighted.  Flutter is drawing this highlight because iOS 17 is sending showAutocorrectionPromptRect, but iOS 16 does not.

@LongCatIsLooong Do you know what's going on here having worked on autocorrect?  I guess iOS 17 has changed something about how it does autocorrect.  Playing around with the native text messaging app on iOS 17 I don't see all that much difference with iOS 16, though.  Maybe the autocorrect highlight is invisible?  Should we be displaying the autocorrect menu, but at the correct place and with the correctly-styled highlight?

**Comment by hellohuanlin** [comment]
> Notice also that the last character typed is highlighted. Flutter is drawing this highlight because iOS 17 is sending showAutocorrectionPromptRect, but iOS 16 does not.

@justinmc this is a known bug that I am fixing today. Will ping you in the PR.

**Comment by justinmc** [comment]
Oh nice, sounds good!  Maybe that will fix this issue too.

First of all I believe spell check is still disabled by default on iOS, so that menu shouldn't be showing at all.  Also there are subtle differences in the show/hide animation.  But I finally double checked by changing the string for "No replacements found", and it didn't affect the menu.

**Comment by hellohuanlin** [comment]
Related issue: https://github.com/flutter/flutter/issues/128406

**Comment by hellohuanlin** [comment]
Very possible duplicate of https://github.com/flutter/flutter/issues/130818. However, there are some UI differences (this issue shows the full auto correction bubble, while the other issue shows only portion of the auto correction bubble). So I will keep it open for now.
