### ISSUE TITLE
Please change link to docs

### ISSUE THREAD

**Issue by sfshaza2** [flutter/flutter#130805]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Please [update this link](https://github.com/flutter/flutter/blob/c8e42b47f5ea8b5ff7bf2f2b0a2a8e765f1aa51d/packages/flutter/lib/src/widgets/basic.dart#L5166-L5174)
to point to flutter.dev/unbounded-constraints.

Related PR:  https://github.com/flutter/website/pull/9062

### Expected results

Happy short link!

### Actual results

Current link is less informative.

### Code sample

n/a

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

n/a

**Comment by goderbauer** [comment]
> to point to flutter.dev/unbounded-constraints.

This link currently gives a 404 not found. Can you ping this issue when a new version of the website has been deployed where the link works? I don't want to update the link to something that points to nothing...

**Comment by parlough** [comment]
\@cc @khanhnwin When you get a chance, could you deploy the latest website-cms changes which has this redirect? Thanks!

**Comment by parlough** [comment]
Khanh has deployed the changes (thanks!) and https://flutter.dev/unbounded-constraints now works. We can more easily adjust its destination now if ever needed.
