### ISSUE TITLE
Gallery text gets messed up on one device

### ISSUE THREAD

**Issue by itsJoKr** [flutter/flutter#13087]
## Steps to Reproduce

Open Gallery app on my device. Go into animation. Poke around for 15 seconds and sometimes the letters get messed up. This only happens on my ZTE Blade A910, Android M. On Samsung J3 and Tab A works fine. Tested on few emulators, everything working fine.

![image](https://user-images.githubusercontent.com/11093480/33011376-1ef22de0-cdde-11e7-9f60-b04b76a5fccc.png)

![image](https://user-images.githubusercontent.com/11093480/33011390-2ae47c02-cdde-11e7-8af9-fc677212f99b.png)

It's not only the animations app, but it's easiest to reproduce for me.

![image](https://user-images.githubusercontent.com/11093480/33011403-35829a18-cdde-11e7-9eca-b581cd1cf86e.png)

The letters to "scramble" when the animation starts. The letters stay still when the animation ends (either messed up or normal state).

## Logs

Logs: https://hastebin.com/omadupuyec.scala

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.12.6 16G1036, locale en-US, channel master)
    • Flutter at /Users/jokr/Documents/flutter/flutter
    • Framework revision d5d2cdfeef (2 days ago), 2017-11-16 22:53:22 -0800
    • Engine revision 25912b8482
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at /Users/jokr/Library/Android/sdk
    • Platform android-27, build-tools 27.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.1, Build version 9B55
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.2.5)
    • Flutter plugin version 19.0
    • Dart plugin version 172.4343.25

[✓] Connected devices
    • ZTE BLADE A910               • 1245274                              • android-arm • Android 6.0 (API 23)
    • Android SDK built for x86 64 • emulator-5556                        • android-x64 • Android 6.0 (API 23) (emulator)
    • Android SDK built for x86    • emulator-5554                        • android-x86 • Android 8.0.0 (API 26) (emulator)
    • iPhone 8                     • AF78793F-1AF0-4B7E-9E22-3D65C7E559F8 • ios         • iOS 11.1 (simulator)

**Comment by oliverjanik** [comment]
I get forbidden on all of your links

**Comment by itsJoKr** [comment]
Thanks for the notice, I've updated my issue.

**Comment by eseidelGoogle** [comment]
I believe this was the Skia font handling regression (which also occurred on iOS) which @xster chased down last week?

**Comment by eseidelGoogle** [comment]
I believe this is https://github.com/flutter/flutter/issues/12934?

**Comment by eseidelGoogle** [comment]
I believe the fix for that landed, then was rolled out, and then landed again.  I'm not sure of the current status if it's in the tip-of-tree `master` or not.  You might try a `flutter upgrade`.

**Comment by xster** [comment]
Yes, it was #12934. You should be able to get your behaviour corrected if you update to head on master (e.g. run `flutter upgrade`).
