### ISSUE TITLE
Blank Screen is displayed after launching debug app of flutter with settings of appium

### ISSUE THREAD

**Issue by RYenike** [flutter/flutter#130980]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Blank Screen is displayed after launching debug app of flutter with settings of appium

Followed steps in below links

https://www.lambdatest.com/support/docs/testing-flutter-apps/

https://testingbot.com/support/mobile/flutter.html#start

### Expected results

Expect the debug app to launch successfully after the flutter settings done to apk file

### Actual results

Blank Screen is displayed after launching debug app of flutter with settings of appium

### Code sample

Please refer code in below links

https://www.lambdatest.com/support/docs/testing-flutter-apps/

https://testingbot.com/support/mobile/flutter.html#start

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by dam-ease** [comment]
Hi @RYenike. Thanks for filing this issue. I'm currently unable to reproduce this issue on the latest `master` and `stable` channels. I'm using the [Sample Flutter Demo App](https://github.com/testingbot/flutter-demo-app).
Can you provide more information into how you reproduce this issue. Also, kindly share the output of your `flutter doctor -v`

**Comment by RYenike** [comment]
Please find attached logs

<img width="1062" alt="Screenshot 2023-07-21 at 11 51 47 AM" src="https://github.com/flutter/flutter/assets/140067876/1425f866-e176-4982-a5fb-3350547df43c">
<img width="1062" alt="Screenshot 2023-07-21 at 11 52 16 AM" src="https://github.com/flutter/flutter/assets/140067876/56fc2c47-93e8-423a-98ae-73abc565fc70">

**Comment by RYenike** [comment]
Below is the output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.4.1 22F770820d darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.80.1)
[✓] VS Code (version 1.70.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
welcome@Welcomes-MacBook-Pro rfxcel-mobile-flutter % flutter doctor -v          
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.4.1 22F770820d darwin-x64, locale en-IN)
    • Flutter version 3.10.0 on channel stable at /Users/welcome/Downloads/Flutter sdks/flutter_3_10
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (2 months ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/welcome/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/welcome/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] VS Code (version 1.70.2)
    • VS Code at /Users/welcome/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)         • macos         • darwin-x64     • macOS 13.4.1 22F770820d darwin-x64
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!
