### ISSUE TITLE
Exception caught by rendering library ===================================================== The following assertion was thrown during performLayout(): RenderBox was not laid out: RenderShrinkWrappingViewport#4aefd relayoutBoundary=up13 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE 'package:flutter/src/rendering/box.dart': Failed assertion: line 1966 pos 12: 'hasSize'

### ISSUE THREAD

**Issue by negianoop2000** [flutter/flutter#130967]
Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

```
The relevant error-causing widget was: 
  ListView ListView:file:///D:/flutter%20projects/CredexConnect/lib/UI/SuperAdmin_ScreenUI.dart:797:27
When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:1966:12)
#3      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:123:21)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#5      RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#6      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#7      RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#8      RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#9      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#10     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#11     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#12     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#13     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#14     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#15     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#16     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#17     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#18     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#19     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#20     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#21     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#22     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#23     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#25     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:554:11)
#26     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#27     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#29     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#30     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#31     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:297:14)
#32     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#33     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#34     RenderStack.layoutPositionedChild (package:flutter/src/rendering/stack.dart:511:11)
#35     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:620:30)
#36     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#37     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#38     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:238:12)
#39     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#40     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#41     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#42     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1056:7)
#43     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:235:7)
#44     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
#45     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#46     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#47     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#48     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#49     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#50     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#51     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1449:11)
#52     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#53     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#54     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#55     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#56     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#57     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#58     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#59     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#60     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#61     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#62     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#63     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#64     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#65     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#66     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#67     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#68     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#69     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#70     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#71     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#72     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#73     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#74     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#75     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#76     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#77     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#78     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#79     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#80     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#81     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#82     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3751:13)
#83     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#84     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#85     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#86     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2234:7)
#87     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1016:18)
#88     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:492:19)
#89     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:905:13)
#90     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358:5)
#91     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284:15)
#92     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214:9)
#93     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:939:7)
#97     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
(elided 5 frames from class _AssertionError, class _Timer, and dart:async-patch)
The following RenderObject was being processed when the exception was fired: RenderIgnorePointer#d3672 relayoutBoundary=up12 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(0.0<=w<=Infinity, h=200.0)
...  size: MISSING
...  ignoring: false
...  ignoringSemantics: false
RenderObject: RenderIgnorePointer#d3672 relayoutBoundary=up12 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=Infinity, h=200.0)
  size: MISSING
  ignoring: false
  ignoringSemantics: false
...  child: RenderShrinkWrappingViewport#4aefd relayoutBoundary=up13 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    needs compositing
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(0.0<=w<=Infinity, h=200.0)
...    size: MISSING
...    axisDirection: down
...    crossAxisDirection: right
...    offset: ScrollPositionWithSingleContext#7fdfd(offset: 0.0, range: null..null, viewport: null, ScrollableState, AlwaysScrollableScrollPhysics -> ClampingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#375a7, ScrollDirection.idle)
...    child 0: RenderSliverPadding#92029 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: layoutOffset=None
...      constraints: MISSING
...      geometry: null
...      padding: EdgeInsets.zero
...      textDirection: ltr
...      child: RenderSliverList#21bc9 NEEDS-LAYOUT NEEDS-PAINT
...        parentData: paintOffset=Offset(0.0, 0.0)
...        constraints: MISSING
...        geometry: null
...        no children current live
====================================================================================================
```

**Comment by dam-ease** [comment]
Hi @negianoop2000. Please can you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code?
Thank you

**Comment by negianoop2000** [comment]
this problem is occuring when i am using a listview or any kinf of list widget inside positioned widget and the positioned widget is a children of stack

**Comment by negianoop2000** [comment]
Stack(
children[
Positioned(
child:ListView()
),
],
),

I don't have the code as i have deleted it but the error should occur if you use this code inside Scaffold

**Comment by negianoop2000** [comment]
@override
  Widget build(BuildContext context) {
       double screenWidth = MediaQuery.of(context).size.width;
       double screenHeight = MediaQuery.of(context).size.height;
    return WillPopScope(
      onWillPop: _onBackPressed,
      child: Scaffold(
        backgroundColor:  Colors.white,
        appBar: MyAppBar(
          appBar: AppBar(),
          context: context,
        ),
        body:
        isDesktop(context) ?
        Row(
          children: [
            Side_Bar(controller: _controller),
            Expanded(
              child: Container(
                padding: const EdgeInsets.all(20.0),
                child: Column(
                  children: <Widget>[
                    Container(
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(30.0),
                        gradient: const LinearGradient(
                          begin: Alignment.topLeft,
                          end: Alignment.bottomRight,
                          colors: [
                            Color(0xFF0E1C26),
                            Color(0xFF294861),
                          ],
                        ),
                      ),
                      child: Align(
                        alignment: Alignment.center,
                        child: Padding(
                          padding: EdgeInsets.all(10.0),
                          child: FittedBox(
                            fit: BoxFit.scaleDown,
                            child: Text(
                              'Hello, ${FirebaseAuth.instance.currentUser!.displayName}',
                              style: TextStyle(
                                fontSize: 20.0,
                                fontWeight: FontWeight.bold,
                                color: Colors.white,
                              ),
                            ),
                          ),
                        ),
                      ),
                    ),
                    SizedBox(height: 70.0),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: <Widget>[
                        Flexible(
                          flex: 1,
                          child: InkWell(
                            onTap: () {
                              Navigator.push(
                                context,
                                MaterialPageRoute(builder: (BuildContext) {
                                  return Tasks_UI();
                                }),
                              );
                            },
                            child: Container(
                              padding: EdgeInsets.all(8.0),
                              height: 150.0,
                              width: 150.0,
                              decoration: BoxDecoration(
                                borderRadius: BorderRadius.circular(30.0),
                                gradient: const LinearGradient(
                                  begin: Alignment.topRight,
                                  end: Alignment.bottomLeft,
                                  colors: [
                                    Color(0xFF471069),
                                    Color(0xFF30C5D2),
                                  ],
                                ),
                              ),
                              child: Column(
                                mainAxisAlignment: MainAxisAlignment.center,
                                children: <Widget>[
                                  Expanded(
                                    child: Lottie.asset(
                                      'assets/todo.json',
                                      fit: BoxFit.fill,
                                      alignment: Alignment.center,
                                    ),
                                  ),
                                  const Text(
                                    'Todo',
                                    style: TextStyle(
                                      fontSize: 25.0,
                                      fontWeight: FontWeight.bold,
                                      color: Colors.white,
                                    ),
                                    textAlign: TextAlign.center,
                                  ),
                                ],
                              ),
                            ),
                          ),
                        ),
                        const SizedBox(width: 30.0),
                        Flexible(
                          flex: 1,
                          child: InkWell(
                            onTap: () {
                              Navigator.push(
                                context,
                                MaterialPageRoute(
                                  builder: (BuildContext) {
                                    return Chatbot_screen();
                                  },
                                ),
                              );
                            },
                            child: Container(
                              padding: EdgeInsets.all(8.0),
                              height: 150.0,
                              width: 150.0,
                              decoration: BoxDecoration(
                                borderRadius: BorderRadius.circular(30.0),
                                gradient: const LinearGradient(
                                  begin: Alignment.topRight,
                                  end: Alignment.bottomLeft,
                                  colors: [
                                    Color(0xFFE4E5E6),
                                    Color(0xFF00416A),
                                  ],
                                ),
                              ),
                              child: Column(
                                mainAxisAlignment: MainAxisAlignment.center,
                                children: <Widget>[
                                  Expanded(
                                    child: Lottie.asset(
                                      'assets/ask me json.json',
                                      fit: BoxFit.fill,
                                    ),
                                  ),
                                  const Text(
                                    'Ask Me Anything',
                                    style: TextStyle(
                                      fontSize: 20.0,
                                      fontWeight: FontWeight.bold,
                                      color: Colors.white,
                                    ),
                                    textAlign: TextAlign.center,
                                  ),
                                ],
                              ),
                            ),
                          ),
                        )
                      ],
                    ),
                    const SizedBox(height: 60.0),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: <Widget>[
                        Flexible(
                          flex: 1,
                          child: InkWell(
                            onTap: () {
                              Navigator.push(
                                context,
                                MaterialPageRoute(
                                  builder: (BuildContext) {
                                    return Induction_Screen();
                                  },
                                ),
                              );
                            },
                            child: Container(
                              padding: EdgeInsets.all(8.0),
                              height: 150.0,
                              width: 150.0,
                              decoration: BoxDecoration(
                                borderRadius: BorderRadius.circular(30.0),
                                gradient: const LinearGradient(
                                  begin: Alignment.topRight,
                                  end: Alignment.bottomLeft,
                                  colors: [
                                    Color(0xFFBDC3C7),
                                    Color(0xFF1662D4),
                                  ],
                                ),
                              ),
                              child: Column(
                                mainAxisAlignment: MainAxisAlignment.center,
                                children: <Widget>[
                                  Expanded(
                                    child: Align(
                                      alignment: Alignment.center,
                                      child: Center(
                                        child: Lottie.asset(
                                          'assets/induction json.json',
                                          fit: BoxFit.fill,
                                          alignment: Alignment.center,
                                        ),
                                      ),
                                    ),
                                  ),
                                  const Text(
                                    'Induction',
                                    style: TextStyle(
                                      fontSize: 20.0,
                                      fontWeight: FontWeight.bold,
                                      color: Colors.white,
                                    ),
                                    textAlign: TextAlign.center,
                                  ),
                                ],
                              ),
                            ),
                          ),
                        ),
                        const SizedBox(width: 30.0),
                        Flexible(
                          flex: 1,
                          child: InkWell(
                            onTap: () {
                              Navigator.push(
                                context,
                                MaterialPageRoute(builder: (BuildContext) {
                                  return Pending_Request_List();
                                }),
                              );
                            },
                            child: Container(
                              padding: EdgeInsets.all(8.0),
                              height: 150.0,
                              width: 150.0,
                              decoration: BoxDecoration(
                                borderRadius: BorderRadius.circular(30.0),
                                gradient: const LinearGradient(
                                  begin: Alignment.topRight,
                                  end: Alignment.bottomLeft,
                                  colors: [
                                    Color(0xFFEAAFC8),
                                    Color(0xFF654EA3),
                                  ],
                                ),
                              ),
                              child: Column(
                                mainAxisAlignment: MainAxisAlignment.center,
                                children: <Widget>[
                                  Expanded(
                                    child: Padding(
                                      padding: const EdgeInsets.all(20.0),
                                      child: Lottie.asset(
                                        'assets/pending request json.json',
                                        height: 10,
                                        fit: BoxFit.fill,
                                        alignment: Alignment.center,
                                      ),
                                    ),
                                  ),
                                  const Text(
                                    'Pending Request',
                                    style: TextStyle(
                                      fontSize: 20.0,
                                      fontWeight: FontWeight.bold,
                                      color: Colors.white,
                                    ),
                                    textAlign: TextAlign.center,
                                  ),
                                ],
                              ),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
            ),
          ],
        ) :
        Stack(

        children: [
          Positioned(
            top: 0,
            left: 0,
            child: Padding(
              padding: const EdgeInsets.all(8.0),
              child: Text(
                'Hello!',
                style: TextStyle(
                  fontSize: 12,
                ),
              ),
            ),
          ),
          Positioned(
            top: 20,
            left: 0,
            child: Padding(
              padding: const EdgeInsets.all(8.0),
              child: Text(
                '${FirebaseAuth.instance.currentUser!.displayName}',
                style: TextStyle(
                  fontSize: 20,
                  fontWeight: FontWeight.bold,
                ),
              ),
            ),
          ),
          Positioned(
            top: 15,
            right: 0,
            child: Padding(
              padding: const EdgeInsets.all(8.0),
              child: Icon(
                Icons.notifications,
                color: Colors.black,
              ),
            ),
          ),
          Positioned(
            top: screenHeight / 7.5 -40,
            left: 0,
            right: 0,
            child:Padding(
              padding: const EdgeInsets.all(8.0),
              child: Container(
              height: screenWidth / 2,
              width: screenWidth - 50,
              decoration: BoxDecoration(
                color: Color(0xFF5f33e1),
                borderRadius: BorderRadius.circular(30.0),
              ),
              child: Stack(
                children: [
                  Positioned(
                    top: 0,
                    right: 0,
                    child: IconButton(
                      icon: Icon(Icons.more_horiz, color: Colors.white),
                      onPressed: () {
                        print("Icon Button clicked");
                      },
                    ),
                  ),
                  Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Padding(
                        padding: const EdgeInsets.all(10.0),
                        child: Text(
                          'Your Current Work Status !',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 18,
                          ),
                        ),
                      ),
                      SizedBox(height: 10),
                      ElevatedButton(
                        onPressed: () {
                          // Handle button press
                        },
                        style: ElevatedButton.styleFrom(
                          backgroundColor: Colors.white,
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(30),
                          ),
                        ),
                        child: Text(
                          'View All Tasks',
                          style: TextStyle(
                            color:  Color(0xFF5f33e1),
                            fontSize: 16,
                          ),
                        ),
                      ),
                    ],
                  ),
                Positioned(
                  top: 50,
                  right: 18,
                  child: Padding(
                    padding: const EdgeInsets.all(8.0),
                    child: new CircularPercentIndicator(
                      radius: 60.0,
                      lineWidth: 13.0,
                      animation: true,
                      percent: 0.8,

                      center: new Text(
                        "80.0%",
                        style:
                        new TextStyle(fontWeight: FontWeight.bold, fontSize: 20.0,
                        color: Colors.white),
                      ),

                      circularStrokeCap: CircularStrokeCap.round,
                      progressColor: Colors.white,
                    ),
                  ),
                ),],
              ),
          ),
            ),
          ),
          Positioned(
            top: screenHeight / 7.5 + 175 , // Adjust the vertical position as needed
            left: 0,
           // right: 0,
            child: Padding(
              padding: const EdgeInsets.all(8.0),
              child: Text(
                'In Progress',
                textAlign: TextAlign.center,
                style: TextStyle(
                  fontSize: 24,
                  fontWeight: FontWeight.bold,
                  color: Colors.black,
                ),
              ),
            ),
          ),
          Positioned(
              top: screenHeight/7.5 + 215,
              left: 0,
              right: 0,
              child: Padding(
                padding: const EdgeInsets.all(8.0),
                child: SingleChildScrollView(
                  scrollDirection: Axis.horizontal,
                  child:  FutureBuilder<List<Task>>(
                    future: fetchInProgressTasks(),
                    builder: (context, snapshot) {
                      if (snapshot.connectionState == ConnectionState.waiting) {
                        return Center(child: CircularProgressIndicator());
                      } else if (snapshot.hasError) {
                        return Center(child: Text('Error: ${snapshot.error}'));
                      } else {
                        return Container(
                          child: Wrap(
                            spacing: 8.0, // Adjust the spacing between containers
                            runSpacing: 8.0, // Adjust the run spacing between rows of containers
                            children: snapshot.data?.map((task) => _buildTaskContainer(task))?.toList() ?? [],
                          ),
                        );
                      }
                    },
                  ),
                ),
              ),
          ),
          Positioned(
            top: screenHeight/7.5 + 345,
            child: Padding(
              padding: const EdgeInsets.all(8.0),
              child: Text("Tasks Groups",
                textAlign: TextAlign.center,
                style: TextStyle(
                  fontSize: 24,
                  fontWeight: FontWeight.bold,
                  color: Colors.black,
                ),),
            ),
          ),
    

          Positioned(
            top: screenHeight / 7.5 + 378,
            child: Padding(
              padding: const EdgeInsets.all(8.0),
              child: FutureBuilder<List<Projects>>(
                future: fetchProjects(),
                builder: (context, snapshot) {
                  if (snapshot.connectionState == ConnectionState.waiting) {
                    // While waiting for data, display a loading indicator
                    return Center(
                      child: CircularProgressIndicator(),
                    );
                  } else if (snapshot.hasError) {
                    // If an error occurs, display an error message
                    return Center(
                      child: Text('Error fetching projects'),
                    );
                  } else {
                    // Display the projects using a Wrap
                    return Container(
                      height: 200,
                      child: ListView.builder(
                        itemCount: snapshot.data?.length ?? 0,
                        itemBuilder: (context, index) {
                          var project = snapshot.data![index];
                          return Card(
                            child: Padding(
                              padding: const EdgeInsets.all(8.0),
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Text(
                                    project.proj_name,
                                    style: TextStyle(
                                      fontWeight: FontWeight.bold,
                                      fontSize: 16,
                                    ),
                                  ),
                                  SizedBox(height: 8),
                                  Text(
                                    project.proj_desc,
                                    style: TextStyle(fontSize: 12),
                                  ),
                                  // You can add more information about the project here
                                ],
                              ),
                            ),
                          );
                        },
                      ),
                    );
                  }
                },
              ),
            ),
          ),




        ],
      ),
      ),
    );
  }
}




@dam-ease this is the exact code which is giving the error
