### ISSUE TITLE
* What went wrong: A problem occurred evaluating project ':tflite'. > No signature of method: build_11ndixxf2r45crtsznaj3tryh.android() is applicable for argument types: (build_11ndixxf2r45crtsznaj3tryh$_run_closure2) values: [build_11ndixxf2r45crtsznaj3tryh$_run_closure2@51adecfe]

### ISSUE THREAD

**Issue by TSxSAHIL** [flutter/flutter#130917]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

* What went wrong:
A problem occurred evaluating project ':tflite'.
> No signature of method: build_11ndixxf2r45crtsznaj3tryh.android() is applicable for argument types: (build_11ndixxf2r45crtsznaj3tryh$_run_closure2) values: [build_11ndixxf2r45crtsznaj3tryh$_run_closure2@51adecfe]

### Actual results

![Screenshot 2023-07-19 225514](https://github.com/flutter/flutter/assets/80686569/43a2a5ae-8f11-46ed-9a36-f6678cc4b568)

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by danagbemava-nc** [comment]
This is a gradle issue. You'll need to check your `android/app/build.gradle` for any typos. See https://stackoverflow.com/questions/67418660/no-signature-of-method-android-is-applicable-for-argument-types-exception-i for possible places to check. 

On another note, tflite has not been updated in 2 years and is likely out of date. If you are unable to fix this issue in your build.gradle, you'll either have to file an issue on their repo or switch to a different package for tensorflow. 

Closing from here as this is not a flutter issue. 

Thank you

**Comment by TSxSAHIL** [comment]
Have checked it and still nothing is resolved
