### ISSUE TITLE
Custom barrier color with showDatePicker, showTimePicker and showAboutDialog 

### ISSUE THREAD

**Issue by ronnnnn** [flutter/flutter#130971]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

`showDialog` can customize barrier color with `barrierColor` property. [^1]
However, `showDatePicker`, `showTimePicker` and `showAboutDialog` can't it, though they call `showDialog` internally.
To keep application wide unified looks, they should also provide `barrierColor` property.

[^1]: https://api.flutter.dev/flutter/material/showDialog.html

### Proposal

Add barrier configs to `showDatePicker`, `showTimePicker` and `showAboutDialog` like `showDialog`.

**Comment by ronnnnn** [comment]
I want to know why the barrier configs are not provided if it is intended.
I can't find any issues which describe it.

**Comment by loic-sharma** [comment]
https://github.com/flutter/flutter/pull/130484 had to be reverted by https://github.com/flutter/flutter/pull/131278 as it caused postsubmit test failures. /cc @ronnnnn

**Comment by ronnnnn** [comment]
@HansMuller @justinmc 

I pulled latest master changes and cherry-picked [9def8f6](https://github.com/flutter/flutter/commit/9def8f6bc56b4d32975c0a5a02526bfdce7d56b7).
I retried failed test as @loic-sharma mentioned and it passed right.

Any idea about it ?
