### ISSUE TITLE
[Flutter GPU] ☂️ MVP

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#130921]
This is an umbrella bug that links to all other issues required for a Flutter GPU MVP.

MVP means: With a _production_ Impeller backend enabled, users can...
* [ ] import from `package:flutter_gpu`, shipped as a built-in Flutter SDK package
* [ ] import shader bundles defined in `pubspec.yaml`
* [x] explicitly allocate textures (or other surface derivative, like swapchains)
* [x] import shader bundle assets and use them to form pipelines
* [x] schedule the execution of render passes against those texture(s)
* [x] instruct Flutter to composite those textures into the 2D Flutter scene

**Comment by jonahwilliams** [comment]
In this context, the MVP is essentially allowing us to ship impeller scene as a package - right? or was there a smaller MVP we were trying to hit?

**Comment by bdero** [comment]
It's implementing everything that would be necessary to rebuild the existing Impeller Scene render in Dart, yes.

**Comment by bdero** [comment]
That is the plan. See https://flutter.dev/go/impeller-dart for the full scope. :)

**Comment by chinmaygarde** [comment]
@bdero Now that we are tracking the MVP items on a dashboard with its own milestone. Should we close this umbrella tracking issue? We can also leave it be as a status update doc.

**Comment by bdero** [comment]
SGTM, let's close this out. Flutter GPU milestone is visible here: https://github.com/orgs/flutter/projects/134/views/1

**Comment by T-Davis** [comment]
@bdero, is that project meant to be private? I was going to have a look, but it's not viewable to me

**Comment by chinmaygarde** [comment]
Oh no. I set that up and didn't realize projects are private by default to Flutter Contributors now. Asking on discord to open it up.

**Comment by chinmaygarde** [comment]
All set. It should be visible now.

**Comment by T-Davis** [comment]
Woot! Thanks @chinmaygarde
