### ISSUE TITLE
Unable to use firebase_messaging

### ISSUE THREAD

**Issue by Fandekasp** [flutter/flutter#13093]
## Steps to Reproduce

In an existing project made from following the Codelabs "firebase for flutter" tutorial, I installed the firebase_messaging plugin and updated the config following [the readme documentation](https://github.com/flutter/plugins/tree/master/packages/firebase_messaging), then copied the [example/lib/main.dart file](https://github.com/flutter/plugins/blob/master/packages/firebase_messaging/example/lib/main.dart) in my project as `lib/messaging.dart` and ran flutter with that new target.
I then went to the firebase web console, and created a new notification targetting my device FCM token and specifying the key-value pair `click_action: FLUTTER_NOTIFICATION_CLICK`.
After sending the notification, my app crashed with the log reported below.

Note: Following [this issue](https://github.com/flutter/flutter/issues/13079), I'm using firebase_messaging 0.0.4

Another note: I've been unable to test firebase_messaging on an android studio simulator. After lot of debugging and googling, I tried installing the `Google Play Intel x86 atom system image` on several Android APIs, then creating google play services enabled AVDs (only the Nexus 5 and 5X with API25 for some reason), without success (running the app will raise `Please update your google play services`, services which I couldn't figure out how to update). Therefore, I've been testing on my real device since then (Zenfone 2, android 6.0.1, API 23).
Also, it became impossible to start the emulator from android studio, with error `Emulator: libGL error: unable to load driver: i965_dri.so`, so I've been running `/opt/android-sdk/tools/emulator -avd Nexus_5_API_25 -use-system-libs` instead.

## Logs

```
$ flutter run -d F5AZFG23U166 --target lib/messaging.dart    
Launching lib/messaging.dart on ASUS Z00AD in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Built build/app/outputs/apk/app-debug.apk (24.7MB).
Installing build/app/outputs/apk/app.apk...
Syncing files to device ASUS Z00AD...
I/flutter (14741): Push Messaging token: fDxqLr4UI-0:APA91bGla3tupTuzUYonSXOEA9HvPVceeNESkVXr523_7qACsr9w0HiGgleKU6yTJCCfciRq9tjE8Fo2OZKt206zakKRCQHMIYNzZDozjPTGj_j_Z3uAccRjC0eiRK9AcT6bNn4JwIjc

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on ASUS Z00AD is available at: http://127.0.0.1:8102/
For a more detailed help message, press "h". To quit, press "q".
W/IInputConnectionWrapper(14741): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(14741): endBatchEdit on inactive InputConnection
W/DynamiteModule(14741): Local module descriptor class for com.google.firebase.auth not found.
D/AndroidRuntime(14741): Shutting down VM
E/AndroidRuntime(14741): FATAL EXCEPTION: main
E/AndroidRuntime(14741): Process: com.dori.grablunch, PID: 14741
E/AndroidRuntime(14741): java.lang.NoSuchMethodError: No static method zzJU()Lcom/google/firebase/iid/zzq; in class Lcom/google/firebase/iid/zzq; or its super classes (declaration of 'com.google.firebase.iid.zzq' appears in /data/app/com.dori.grablunch-2/base.apk)
E/AndroidRuntime(14741):        at com.google.firebase.messaging.FirebaseMessagingService.zzn(Unknown Source)
E/AndroidRuntime(14741):        at com.google.firebase.iid.zzb.onStartCommand(Unknown Source)
E/AndroidRuntime(14741):        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3050)
E/AndroidRuntime(14741):        at android.app.ActivityThread.-wrap17(ActivityThread.java)
E/AndroidRuntime(14741):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1458)
E/AndroidRuntime(14741):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(14741):        at android.os.Looper.loop(Looper.java:148)
E/AndroidRuntime(14741):        at android.app.ActivityThread.main(ActivityThread.java:5480)
E/AndroidRuntime(14741):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14741):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E/AndroidRuntime(14741):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
I/Process (14741): Sending signal. PID: 14741 SIG: 9
Lost connection to device.
```

```
$ flutter analyze --watch 
Analyzing /home/dori/Projects/personal/flutter/grablunch...

0 issues found • analyzed 8 files, 0.96 seconds
```

## Flutter Doctor

```
$ flutter doctor
[✓] Flutter (on Linux, locale en_US.UTF-8, channel alpha)
    • Flutter at /home/dori/Projects/personal/flutter/flutter
    • Framework revision e8aa40eddd (5 weeks ago), 2017-10-17 15:42:40 -0700
    • Engine revision 7c4142808c
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /opt/android-sdk
    • Platform android-27, build-tools 26.0.2
    • ANDROID_HOME = /opt/android-sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at /opt/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Connected devices
    • ASUS Z00AD • F5AZFH24U167 • android-x86 • Android 6.0.1 (API 23)
```

**Comment by Fandekasp** [comment]
Following this [stackoverflow thread](https://stackoverflow.com/questions/38202644/no-static-method-zzur-in-firebase-when-i-try-to-use-analytics-with-notificatio), it looks like we should be using the same versions across play services and firebase libraries, which makes sense. But the equivalent flutter libraries don't seem to respect this convention, and I do not know how to match a flutter plugin version to its related firebase/play-services version

**Comment by bjornbjorn** [comment]
I think this is related to https://github.com/flutter/flutter/issues/12945 .. the versions used in the various packages have been updated there, but I'm still getting this SIGABRT Fatal error when running on Android.

**Comment by Hixie** [comment]
cc @collinjackson

**Comment by ffeu** [comment]
Is this still an issue? I've been using newer versions of `firebase_messaging` and didn't face any of these problems.

**Comment by zoechi** [comment]
@ffeu thanks! I also think this can be closed.

**Comment by kroikie** [comment]
@AdrienLemaire

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/937. Any further collaboration will be done there.
