### ISSUE TITLE
M3 Web spec is inconsistent about bottom-app-bar elevation

### ISSUE THREAD

**Issue by chrisbobbe** [flutter/flutter#130931]
This is a bug in the [Material 3 doc for bottom app bars](https://m3.material.io/components/bottom-app-bar/overview), so I'd appreciate a tip for a more direct way to reach its authors, if possible. But perhaps someone reading this can send it through a Google-internal channel if that's what needs to happen.

-----

The [spec](https://m3.material.io/components/bottom-app-bar/specs) gives `md.sys.elevation.level2` for the elevation.

But I see in [the "What's new" section of the "Overview" page](https://m3.material.io/components/bottom-app-bar/overview#adfd8035-0454-40e6-8ebb-1aee46d9f32a), in a caption (emphasis added):

> M3: Bottom app bar has new colors, a taller container, _no elevation_ or shadow, and contains the FAB.

So, should it have elevation or not? 🙂 For comparison, [top app bars](https://m3.material.io/components/top-app-bar/specs) are supposed to have no elevation except on scroll, in which case it's `md.sys.elevation.level2`.

Thanks for reading!

**Comment by dam-ease** [comment]
Hi @chrisbobbe. Thanks for filing this issue. I can see there is an elevation https://github.com/flutter/flutter/blob/a1b1386392267630b4dc813b1808af6247dc25f7/packages/flutter/lib/src/material/bottom_app_bar.dart#L302 but docs seems to state otherwise with 

> M3: Bottom app bar has new colors, a taller container, no elevation or shadow, and contains the FAB.

**Comment by HansMuller** [comment]
@chrisbobbe - marking this P3 not because it's unimportant, but because I think we've got it right. Of course I could be wrong ... @guidezpl - is 0.0 the correct default elevation for M3 AppBars, per the token database?

**Comment by gnprice** [comment]
(This issue is about BottomAppBar, not AppBar.)

I think the main question may actually be whether the token database is correct here. The database calls for an elevation, but the [M3 spec's text](https://m3.material.io/components/bottom-app-bar/overview) specifically says it differs from M2 in having no elevation for the bottom app bar.

**Comment by guidezpl** [comment]
I believe the token is correct and `M3: Bottom app bar has new colors, a taller container, no elevation or shadow, and contains the FAB.` should just read `no shadow`.
