### ISSUE TITLE
Create interactive tool to build the engine locally on MacOS

### ISSUE THREAD

**Issue by mossmana** [flutter/flutter#130945]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Building the engine locally for various platforms requires manually entering commands on a terminal per https://github.com/flutter/flutter/wiki/Compiling-the-engine, which can be error prone and time consuming.

### Proposal

We should provide a tool that can automate the local build process on MacOS as much as possible.

It should:

1. Be written in Dart
2. Read flags from the CI build configurations.
3. Provide an intuitive UI to interact with

### Next steps

Update the [wiki](https://github.com/flutter/flutter/wiki/Compiling-the-engine) to refer to this script

**Comment by reidbaker** [comment]
I talked to @mossmana and we should consider closing this bug and replacing it with https://github.com/flutter/flutter/issues/132807

**Comment by mossmana** [comment]
I will instead link this issue under the umbrella issue #132807 and perform the work suggested by @zanderso in https://github.com/flutter/engine/pull/43856#issuecomment-1685429753

**Comment by mossmana** [comment]
The work to read the configs from the build scripts is done as part of https://github.com/flutter/engine/pull/45390

**Comment by loic-sharma** [comment]
I created a rough prototype for a Dart tool: https://github.com/loic-sharma/crank

Examples:

```sh
# Build and test the engine
crank build
crank test

# Run a Flutter app using local engine build
crank run
```

The tool defaults to a `host_debug_unopt` build, but you can [customize builders](https://github.com/loic-sharma/crank#custom-builders) using JSON configs.
