### ISSUE TITLE
How to monitor a messed up view due to a exception like Object.noSuchMethod.

### ISSUE THREAD

**Issue by kangwang1988** [flutter/flutter#13094]
## Problem
Unable to catch exception in the outmost try/catch block, as a result, when the view is messed up in the end user(release mode), I will fail to monitor and fix it.
   ![Screenshot](https://github.com/FlutterRepo/exception_demo/raw/master/screenshot/IMG_1810.png)

## Steps to Reproduce
  Launch App, click the Increment Button in the bottom right. The view will be messed up due to a Object.noSuchMethod error.

## Source code (Example) for reproducing the problem.
    
   [Example code @github ](https://github.com/FlutterRepo/exception_demo)

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.13.1 17B48, locale en-CN, channel master)
    • Flutter at /Users/kylewong/Codes/Flutter/flutter
    • Framework revision 580281e520 (3 days ago), 2017-11-16 19:33:32 -0800
    • Engine revision 25912b8482
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at /Users/kylewong/Library/Android/sdk
    • Platform android-27, build-tools 27.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.1, Build version 9B55
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.6)
    • Flutter plugin version 19.1
    • Dart plugin version 172.4343.25

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554                            • android-x86 • Android 6.0 (API 23) (emulator)
    • KyleWong's iPhone         •***** • ios         • iOS 11.1.2

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by zoechi** [comment]
https://github.com/yjbanov/crashy/blob/master/lib/main.dart should provide the info you need

**Comment by kangwang1988** [comment]
@zoechi  Thx. Previously, I only used runApp:zoned, It seems not enough. With FlutterError&Isolate.addErrorListener used in this example, I successfully capture the `Flutter error`. As to the backend-service provided by sentry.io, we have our own infrastructure. Thank you again, I will close this issue.

**Comment by kangwang1988** [comment]
A combination of FlutterError.onError/Isolate.current.addErrorListener/runZoned:onError: helps me capture errors successfully.
