### ISSUE TITLE
Crash on Hot restart periodycally in flutter web

### ISSUE THREAD

**Issue by MacDeveloper1** [flutter/flutter#130972]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I it is not reproduceable because it is occurred from time to time. I setup my VS Code to hot restart when I save my code.

### Expected results

No errors

### Actual results

Reload already in progress, ignoring requestUnhandled exception:
Crash when compiling:
Null check operator used on a null value

#0      TypeBuilderComputer.visitTypeParameterType (package:front_end/src/fasta/kernel/type_builder_computer.dart:179:50)
#1      TypeParameterType.accept (package:kernel/ast.dart:13247:42)
#2      TypeBuilderComputer.visitInterfaceType.<anonymous closure> (package:front_end/src/fasta/kernel/type_builder_computer.dart:103:65)
#3      new _List.generate (dart:core-patch/array.dart:112:28)
#4      TypeBuilderComputer.visitInterfaceType (package:front_end/src/fasta/kernel/type_builder_computer.dart:102:23)
#5      InterfaceType.accept (package:kernel/ast.dart:12100:42)
#6      DillLoader.computeTypeBuilder (package:front_end/src/fasta/dill/dill_loader.dart:345:17)
#7      computeTypeBuilder (package:front_end/src/fasta/dill/dill_class_builder.dart:248:24)
#8      DillClassBuilder.supertypeBuilder (package:front_end/src/fasta/dill/dill_class_builder.dart:102:23)
#9      ClassHierarchyNodeBuilder.build (package:front_end/src/fasta/kernel/hierarchy/hierarchy_node.dart:42:57)
#10     ClassHierarchyBuilder.getNodeFromClassBuilder (package:front_end/src/fasta/kernel/hierarchy/hierarchy_builder.dart:58:10)
#11     ClassHierarchyBuilder.getNodeFromTypeBuilder (package:front_end/src/fasta/kernel/hierarchy/hierarchy_builder.dart:63:33)
#12     ClassHierarchyNodeBuilder.build (package:front_end/src/fasta/kernel/hierarchy/hierarchy_node.dart:42:21)
#13     ClassHierarchyBuilder.build (package:front_end/src/fasta/kernel/hierarchy/hierarchy_builder.dart:204:14)
#14     SourceLoader.buildClassHierarchy (package:front_end/src/fasta/source/source_loader.dart:2818:31)
#15     KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:477:14)
<asynchronous suspension>
#16     withCrashReporting (package:front_end/src/fasta/crash.dart:136:12)
<asynchronous suspension>
#17     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:408:33)
<asynchronous suspension>
#18     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:75:50)
<asynchronous suspension>
#19     FrontendCompiler.recompileDelta (package:frontend_server/frontend_server.dart:927:52)
<asynchronous suspension>
#20     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1374:11)
<asynchronous suspension>

the Dart compiler exited unexpectedly.
Exited (sigterm)

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
PS C:\data\flutter\cemacs> flutter -v doctor
[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.17763.4645], locale en-NL)
    • Flutter version 3.10.5 on channel stable at C:\Users\at\AppData\Local\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (5 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\at\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32407.343
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.80.1)
    • VS Code at C:\Users\at\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.68.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.17763.4645]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 114.0.5735.199

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by dam-ease** [comment]
Hi @MacDeveloper1. Thanks for filing this issue. 

> it is not reproduceable because it is occurred from time to time

According to this, can you share a code sample or anything that reproduces this error as I can't reproduce with a newly created flutter project. Also, this might be similar/related to https://github.com/flutter/flutter/issues/114672. Can you check this out?
