### ISSUE TITLE
FLUTTER DOCTOR UBUNTU(Zorin OS) Summary shows the Problem Dart Path: Consider adding to front of Path

### ISSUE THREAD

**Issue by kamranhccp** [flutter/flutter#130901]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

When running` kamranhccpszorin@kamranhccpszorin-Latitude-3300:~$ flutter doctor`

### Actual results

Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.10.5, on Zorin OS 16.2 5.15.0-76-generic, locale
    en_US.UTF-8)
    ! Warning: `dart` on your path resolves to /usr/bin/snap, which is not
      inside your current Flutter SDK checkout at
      /home/kamranhccpszorin/snap/flutter/common/flutter. Consider adding
      /home/kamranhccpszorin/snap/flutter/common/flutter/bin to the front of
      your path.
![Flutter Doctor Dart Problem in Ubuntu Zorin OS](https://github.com/flutter/flutter/assets/50527133/fff21699-ee5e-4cfe-a48c-f3aa55b01b08)

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by huycozy** [comment]
Hi @kamranhccp 
The warning message is quite clear. You should add the new dart/flutter path before the $PATH variable. Please check [this comment](https://github.com/flutter/flutter/issues/115651#issuecomment-1409619007) for more information. 

Closing the issue from here.

**Comment by kamranhccp** [comment]
> Hi @kamranhccp The warning message is quite clear. You should add the new dart/flutter path before the $PATH variable. Please check [this comment](https://github.com/flutter/flutter/issues/115651#issuecomment-1409619007) for more information.
> 
> Closing the issue from here.

I tried upgrading flutter using
`flutter upgrade --flutter
`
and it's been solved
