### ISSUE TITLE
Tell developers how to migrate their ThemeData & textTheme widgets over to Material3

### ISSUE THREAD

**Issue by leighajarett** [flutter/flutter#130949]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

There are several properties in ThemeData we don't recommend using when you switch over to Material3. As such, we should update the API docs to reflect this, and give examples to help people move over.  One important property to touch upon are the text styling properties. 

### Proposal

Modify the API docs to help developers move to Material 3

**Comment by TahaTesser** [comment]
TextTheme docs are up-to-date and deprecation message is shown when using unsupported text theme. Other unsupported theme data properties are deprecated/to be deprecated are tracked in  https://github.com/flutter/flutter/issues/130949
