### ISSUE TITLE
 Passing data with Navigator.pushReplacementNamed()  

### ISSUE THREAD

**Issue by sheikhasadmuneer** [flutter/flutter#13097]
Hello all ,

I know we can pass data via Navigator.push

i.e : 

```
Navigator.push(context, new MaterialPageRoute(
                              builder: (BuildContext context) => new SecondPage("some string"),
                            ));
```

I**s there a way to pass data when using**  **Navigator.pushReplacementNamed()**   ? 

Thanks,

**Comment by Alexays** [comment]
In these cases, just use `Navigator.pushReplacement`

**Comment by sheikhasadmuneer** [comment]
it worked , Thanks @Alexays

**Comment by Hixie** [comment]
You can also pass information in the name itself.
