### ISSUE TITLE
Error while updating

### ISSUE THREAD

**Issue by giovanni256** [flutter/flutter#130974]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Update all pubspec to latest version
2. Update Flutter to the latest stable version
3. Run in debug mode

### Expected results

App to work

### Actual results

App is not working, error here:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find any version that matches com.google.firebase:firebase-sessions:[15.0.0, 16.0.0).
     Versions that do not match: 1.0.0
     Required by:
         project :app > project :firebase_crashlytics > com.google.firebase:firebase-crashlytics:18.4.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s
```

I also tried to do `flutter clean` without positive result.

### Code sample

build.gradle

```
buildscript {
    ext.kotlin_version = '1.6.0'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.10'  // Google Services plugin
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.1'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

ext.kotlin_version = '1.6.0'

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

```

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Versione 10.0.22621.1848], locale it-IT)
    • Flutter version 3.10.6 on channel stable at C:\Users\Giovanni\Documents\flutter-v2.10.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (8 days ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\Giovanni\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.80.0)
    • VS Code at C:\Users\Giovanni\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.68.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Versione 10.0.22621.1848]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 114.0.5735.199
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 114.0.1823.67

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by dam-ease** [comment]
Hi @giovanni256. From the logs, 

> Could not find any version that matches com.google.firebase:firebase-sessions:[15.0.0, 16.0.0).
     Versions that do not match: 1.0.0
     Required by:
         project :app > project :firebase_crashlytics > com.google.firebase:firebase-crashlytics:18.4.0

There seems to be conflicting versions/versions that don't match, can you check this out in your pubspec or share your pubspec.yaml file

**Comment by VirusXMe** [comment]
Same error here, and it is very annoying because we were about to release a new version of our app, but suddenly we stopped because of this error!

**Comment by VirusXMe** [comment]
> Hi @giovanni256. From the logs,
> 
> > Could not find any version that matches com.google.firebase:firebase-sessions:[15.0.0, 16.0.0).
> > Versions that do not match: 1.0.0
> > Required by:
> > project :app > project :firebase_crashlytics > com.google.firebase:firebase-crashlytics:18.4.0
> 
> There seems to be conflicting versions/versions that don't match, can you check this out in your pubspec or share your pubspec.yaml file

```
firebase_analytics: ^10.4.4
firebase_crashlytics: ^3.3.4
firebase_core: ^2.15.0
cloud_firestore: ^4.8.3
firebase_storage: ^11.2.5
firebase_auth: ^4.7.1
cloud_functions: ^4.3.4
```

**Comment by VirusXMe** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the [existing issues](https://github.com/flutter/flutter/issues)
> * [x]  I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)
> 
> ### Steps to reproduce
> 1. Update all pubspec to latest version
> 2. Update Flutter to the latest stable version
> 3. Run in debug mode
> 
> ### Expected results
> App to work
> 
> ### Actual results
> App is not working, error here:
> 
> ```
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:mergeDebugAssets'.
> > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
>    > Could not find any version that matches com.google.firebase:firebase-sessions:[15.0.0, 16.0.0).
>      Versions that do not match: 1.0.0
>      Required by:
>          project :app > project :firebase_crashlytics > com.google.firebase:firebase-crashlytics:18.4.0
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 19s
> ```
> 
> I also tried to do `flutter clean` without positive result.
> 
> ### Code sample
> build.gradle
> 
> ```
> buildscript {
>     ext.kotlin_version = '1.6.0'
>     repositories {
>         google()
>         mavenCentral()
>     }
> 
>     dependencies {
>         classpath 'com.android.tools.build:gradle:4.2.2'
>         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
>         classpath 'com.google.gms:google-services:4.3.10'  // Google Services plugin
>         classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.1'
>     }
> }
> 
> allprojects {
>     repositories {
>         google()
>         mavenCentral()
>     }
> }
> 
> ext.kotlin_version = '1.6.0'
> 
> rootProject.buildDir = '../build'
> subprojects {
>     project.buildDir = "${rootProject.buildDir}/${project.name}"
> }
> subprojects {
>     project.evaluationDependsOn(':app')
> }
> 
> tasks.register("clean", Delete) {
>     delete rootProject.buildDir
> }
> ```
> 
> ### Screenshots or Video
> _No response_
> 
> ### Logs
> _No response_
> 
> ### Flutter Doctor output
> Doctor output

The only solution for now is to use older versions of Firebase packages.

1- Run "flutter clean" command
2- Run "pod cache clean --all" command
3- Run "flutter pub cache clean" command

(Delete also pubspec.lock and podfile.lock files)
Now use the Firebase packages you want with these versions in pubspec.yaml:
 
```
  firebase_analytics: 10.4.3
  firebase_crashlytics: 3.3.3
  firebase_core: 2.14.0
  cloud_firestore: 4.8.1
  firebase_storage: 11.2.3
  firebase_auth: 4.6.3
  cloud_functions: 4.3.3
```
Make sure to remove "^" before the package version number.

4- Run "flutter pub get" command
5- Run "cd ios" then "pod update" commands

Done.

**Comment by emreerkaslan** [comment]
I am having the same problem with these versions of the firebase libraries:

  #firebase
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.2
  firebase_storage: ^11.2.4
  firebase_messaging: ^14.6.4
  firebase_analytics: ^10.4.3
  firebase_crashlytics: ^3.3.4
  firebase_dynamic_links: ^5.0.15
  applovin_max: ^3.0.1

**Comment by VirusXMe** [comment]
> I am having the same problem with these versions of the firebase libraries:
> 
> #firebase firebase_auth: ^4.6.3 firebase_core: ^2.14.0 cloud_firestore: ^4.8.2 firebase_storage: ^11.2.4 firebase_messaging: ^14.6.4 firebase_analytics: ^10.4.3 firebase_crashlytics: ^3.3.4 firebase_dynamic_links: ^5.0.15

Please read this to fix your issues:
https://github.com/flutter/flutter/issues/130974#issuecomment-1644317645

**Comment by VirusXMe** [comment]
If you guys using onesignal try this also:
https://github.com/OneSignal/OneSignal-Gradle-Plugin

The gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.14.0 has been deprecated and removed in newer versions of onesignal

**Comment by emreerkaslan** [comment]
Definitely works but with the onesignal fix:

https://github.com/flutter/flutter/issues/130974#issuecomment-1645549417

**Comment by giovanni256** [comment]
> Definitely works but with the onesignal fix:
> 
> [#130974 (comment)](https://github.com/flutter/flutter/issues/130974#issuecomment-1645549417)



> If you guys using onesignal try this also: https://github.com/OneSignal/OneSignal-Gradle-Plugin
> 
> The gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.14.0 has been deprecated and removed in newer versions of onesignal

Not working for me

**Comment by emreerkaslan** [comment]
> > Definitely works but with the onesignal fix:
> > [#130974 (comment)](https://github.com/flutter/flutter/issues/130974#issuecomment-1645549417)
> 
> > If you guys using onesignal try this also: https://github.com/OneSignal/OneSignal-Gradle-Plugin
> > The gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.14.0 has been deprecated and removed in newer versions of onesignal
> 
> Not working for me

In my case, onesignal was effectively passive but I have basically removed it from gradle, kept NotificationService in ios project though. Do you want to share what goes wrong after removing onesignal and keeping old versions of firebase libraries or the error message?

**Comment by giovanni256** [comment]
> > > Definitely works but with the onesignal fix:
> > > [#130974 (comment)](https://github.com/flutter/flutter/issues/130974#issuecomment-1645549417)
> > 
> > 
> > > If you guys using onesignal try this also: https://github.com/OneSignal/OneSignal-Gradle-Plugin
> > > The gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.14.0 has been deprecated and removed in newer versions of onesignal
> > 
> > 
> > Not working for me
> 
> In my case, onesignal was effectively passive but I have basically removed it from gradle, kept NotificationService in ios project though. Do you want to share what goes wrong after removing onesignal and keeping old versions of firebase libraries or the error message?

Please, can you share your build.gradle files?

**Comment by giovanni256** [comment]
In my case the issue is not related to firebase, but instead to location and app_settings plugin.

Here you have the link to follow:
https://github.com/Lyokone/flutterlocation/issues/865
https://github.com/spencerccf/app_settings/issues/187

**Comment by VirusXMe** [comment]
> > > Definitely works but with the onesignal fix:
> > > [#130974 (comment)](https://github.com/flutter/flutter/issues/130974#issuecomment-1645549417)
> > 
> > 
> > > If you guys using onesignal try this also: https://github.com/OneSignal/OneSignal-Gradle-Plugin
> > > The gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.14.0 has been deprecated and removed in newer versions of onesignal
> > 
> > 
> > Not working for me
> 
> In my case, onesignal was effectively passive but I have basically removed it from gradle, kept NotificationService in ios project though. Do you want to share what goes wrong after removing onesignal and keeping old versions of firebase libraries or the error message?

Everything works as expected.
