### ISSUE TITLE
ExpansionTile doesn't update after more than two items added dynamically

### ISSUE THREAD

**Issue by bartwaggoner** [flutter/flutter#13092]
## Steps to Reproduce

Our app uses expansiontiles in a listview, where each expansiontile represents an employee, and the expansiontile children are 'invoices' for the employee.  After dynamically adding more than two children to the expansiontile the newly added items do not show up. If you click the up/dn arrow you only see the first 2 items only.  You have to force the list to rebuild by either reloading the route, or in our case you can also click on a new tab (we are using a tabbar where each tab contains a listview) then go back to the oringinal tab to see the added items - then they show up fine.

We will go through the process of building a single dart file to reproduce the issue, but for now we wanted to get this logged so that it can be looked at ASAP - we are hoping to release in January 2018.  It appears that the expansiontile is holding onto it's state and not updating itself (we of course call setState after adding new items).

## Logs

No obvious errors generated.

## Flutter Doctor

TBD: I am logging this from a different computer that the flutter environment, but it has been updated and checks out fine (built on MacOS but also exhibits same behavior on Linux developer's system).

**Comment by eseidelGoogle** [comment]
Would you be able to share some sample code?

Also @Hixie might know, he was recently in the expansion tile code.

**Comment by bartwaggoner** [comment]
I'll put something together ASAP - thanks for the response!

**Comment by leobispo** [comment]
@bartwaggoner 

I guess, if you are setting the ExpansionTile key then you have to refresh the key whenever you want to update the data inside the ExpansionTile, otherwise the object will not be reconstructed.

**Comment by bartwaggoner** [comment]
Yes, the problem seems to be with the list holding state. I was not setting a key in the list, so then I changed the code to create a new key for the list each time, as a test:

		Widget list = new ListView.builder(
			itemCount: len,
			itemBuilder: _listItemBuilder,
			key: new Key(new DateTime.now().toIso8601String()),
		);

This fixed the problem of the expansionTile item not updating, but now when I click the expansiontile it no longer expands because the state is recreated each time (I presume).  This key/state issue is probably what is biting me the most in moving to flutter from other systems, so I'll have to dive into this  more fully to understand it.  Any pointers on when/how to handle state/keys would be appreciated.

**Comment by Hixie** [comment]
You shouldn't normally need a key on the list. Just make sure you rebuild the ListView (by calling setState on the `State` whose `build()` calls `new ListView.builder`).

**Comment by bartwaggoner** [comment]
I was creating classes that extend StatefulWidget to render the rows in the expansion widget. Once I changed them to extend StatelessWidget it worked. They even update correctly when underlying values change, so apparently I did not need to make them stateful to begin with. Please consider this closed. Thankyou for the help.
