### ISSUE TITLE
Generic version of the ScaleTransition and RotationTransition

### ISSUE THREAD

**Issue by gmilou** [flutter/flutter#130946]
In: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/transitions.dart

ScaleTransition and RotationTransition  have duplicate code for the the alignment and filterQuality logic.
A more generic animation to Matrix Transition could both factor the duplicate code, and provide an easy way to make more Matrix based animations.

This is a proposal to make a new generic MatrixTransition class, with the common code, and make ScaleTransition and RotationTransition special cases of it.

**Comment by huycozy** [comment]
>A more generic animation to Matrix Transition could both factor the duplicate code, and provide an easy way to make more Matrix based animations.

Can you please be more specific? (Maybe use cases take advantage of this optimization)

**Comment by gmilou** [comment]
The ScaleTransition uses a matrix that scales along the X and Y axis.
The RotationTransition uses a matrix that rotates along the Z axis.
I can see use cases for an X axis only (or Y axis only) scale, or X and Y rotations, especially with skew effects added. The possible combinations are pretty large, and certainly not limited the two available today.

The alignment and filterQuality logic however is useful for all these cases, so anyone wanting to make a new type of Matrix based transition, and still use this logic, would have to copy/paste all that logic. This logic is already copy/pasted between the ScaleTransition and RotationTransition.

This is a proposal to factor the common portions into a common class leaving the (animation value => Matrix4) computation to a callback the caller can provide for any use-case they can imagine.

fwiw, I have a PR almost ready to submit (I'm still running tests). So this can be assigned to me.

**Comment by gmilou** [comment]
https://github.com/gmilou/flutter/commit/68fcdcfa9d08e4e0fb526cdba4cafd716574af93 actually completes this.

**Comment by goderbauer** [comment]
I believe this is mostly completed with #131084.
