### ISSUE TITLE
API docs don't list desktop and web platform under "Platform integrations"

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#130999]
Our API docs only document platform integrations for iOS and Android:

<img width="235" alt="Screenshot 2023-07-20 at 9 52 46 AM" src="https://github.com/flutter/flutter/assets/1227763/48bf1991-8017-4fa7-88a7-9ab07f638881">

What about all the other platforms we support now? All the desktop platforms and the web? Do they have platform integration docs that should be linked from here?

**Comment by yjbanov** [comment]
Soon `dart:ui_web` should show up in the docs, unless manual action is necessary to add new libraries. We should also add a link to https://docs.flutter.dev/platform-integration/web/initialization, which describes the JavaScript-side API for bootstrapping and configuring apps.

**Comment by gspencergoog** [comment]
@yjbanov The two existing sections are created by dummy Dart packages in the flutter/flutter `dev/docs` directory, so we probably need to somehow add one for ui_web if it isn't already discoverable via regular Dart packages.

**Comment by goderbauer** [comment]
dart:ui_web has an entry in the side menu, under the "DART" heading: https://master-api.flutter.dev/flutter/dart-ui_web/dart-ui_web-library.html

Is that the right place for it? Or should it be moved to "Platform Integrations" as well?
