### ISSUE TITLE
Consider adopting `process` and `platform` into the flutter/packages repository

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#130915]
Currently `process`, and its dependency `platform`, are hosted in individual google-org repositories, and published as "unverified uploader". The repos don't have any clear maintenance policy, contribution management, security stance, etc.

`process` is very heavily used in flutter/flutter; mostly tests, but also the tool. Given that, it seems like we should consider bringing them into flutter/packages so that they are managed, reviewed, published, etc. via our normal process. While they aren't Flutter-specific, flutter/packages seems like the natural place for them to live since we are maintaining them specifically for Flutter tooling. (We could move them into the google.dev publisher, but that only addresses the publisher permissions, not the maintenance aspects.)

[Edit: `process` is now google.dev rather than unverified]

**Comment by stuartmorgan** [comment]
Framework and tools folks, any thoughts on this? `flutter_tool` and a ton of `flutter/flutter` tests depend on these packages.

**Comment by christopherfujino** [comment]
This SGTM.

**Comment by goderbauer** [comment]
In the framework I only see two test using `package:platform` and none using `package:process`. The status-quo has not caused as any problems so far.

What problem are we solving by moving them? Who will own them once they are moved? The framework team currently doesn't have the resources for it and given that they appear to be hardly used wouldn't seem like the right owner...

**Comment by christopherfujino** [comment]
the tools team can "own" them, to the extent they are currently being owned :)

**Comment by goderbauer** [comment]
Just to clarify, you mean to move them to the `flutter/packages` repository, not the `packages` directory in the `flutter/flutter` repository? I may have misunderstood that when I first read the issue. I have no issues with that as long as they have a clear owner there.

**Comment by stuartmorgan** [comment]
> In the framework I only see two test using `package:platform` and none using `package:process`

I may well just not be understanding how to map to the new team labels; I saw that it was heavily used by `devicelab` foundations, and assumed that was relevant to the framework team.

> The status-quo has not caused as any problems so far.

I disagree, thus the existence of this issue :)

> What problem are we solving by moving them?

- It's caused it to be harder for me to get updates into it several times (as compared to if it lived with our other packages)
- The current situtaion violates guidance I'm trying to increasingly enforce in flutter/packages about how we manage dependencies there.
- We've had users file issues here to try to escalate attention to PRs in `process` that were stagnating because there's no mechanism in place to triage them.

> Who will own them once they are moved? The framework team currently doesn't have the resources for it and given that they appear to be hardly used wouldn't seem like the right owner

Formally, we'd either put someone's name on it who was quasi-owning it in the current location, or if none of those people want to be listed, I'd put me. I wouldn't expect the framework team to own it.

Informally, I would expect that the current situation of "anyone on the Flutter team who needs to change it owns making that change" to continue—but within a repo with clearly established structures and process, where everyone has permissions and updates are published automatically by anyone rather than manually by a small and hard-to-discover subset of the team, thus making that easier.

> Just to clarify, you mean to move them to the `flutter/packages` repository, not the `packages` directory in the `flutter/flutter` repository?

That's correct. Sorry, I forget that "flutter/packages" can be ambiguous as a name.
