### ISSUE TITLE
flaky bot applying old labels

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#130995]
For example on https://github.com/flutter/flutter/issues/130909, the bot applied `engine`, which is the old label, instead of `team-engine`, the new label.

cc @keyonghan @Hixie

**Comment by keyonghan** [comment]
I should have left the comment before the PR landed: https://github.com/flutter/cocoon/pull/2917#discussion_r1256461264

Assigning to myself to update these labels and add several missing ones, like `android`, `ios`, `infra`, `release`, etc.
