### ISSUE TITLE
Cant run local engine with error:  /../flutter/flutter/packages/flutter/lib/src/rendering/layer.dart:2308:38: Error: 'PhysicalShapeEngineLayer' isn't a type.

### ISSUE THREAD

**Issue by MikePendo** [flutter/flutter#131074]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I have followed the guides here:
[Engine dev environment](https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment)
[Compiling the engine](https://github.com/flutter/flutter/wiki/Compiling-the-engine#compiling-for-ios-from-macos)
[Debug The build](https://github.com/flutter/flutter/wiki/Debugging-the-engine#debugging-ios-builds-with-xcode)
I am on arm64 Mac.
After fetching the repos 
<img width="760" alt="Screenshot 2023-07-21 at 12 58 02" src="https://github.com/flutter/flutter/assets/56674958/b1c9bfbe-c919-47ea-ab71-de8b22a89d29">
**Q1:** Could u please explain why after fetching all the repos the flutter Engine (`src/flutter`) is on specific commit? (I would anticipate it following the master)
**Q2:** how the `src` repo related to  `src/flutter`? If I jump to to different branches in the `src/flutter` should I also do something in the `src` repo OR `gclient sync` would be enough? should the  `gclient sync` run from `src` repo or it doesn't matter.
I have did:
`./flutter/tools/gn --ios --simulator-cpu=arm64 --unoptimized`
`ninja -C out/ios_debug_unopt_arm64 && ninja -C out/host_debug_unopt`

My flutter version:
```
Flutter 3.10.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f468f3366c (9 days ago) • 2023-07-12 15:19:05 -0700
Engine • revision cdbeda788a
Tools • Dart 3.0.6 • DevTools 2.23.1
```
As far as I understand this is the flutter framework, whenever I build and use the engine I still use that precompiled framework 
**Q3:** please correct me if I am wrong about the above.

**Q4:** The framework might not work with every engine so `flutter/bin/internal/engine.version` that hash should be used to checkout on the engine OR how do I make sure which flutter framework support which engine?

I have the following use case: 
**Q5:** If I want to develop a plugin BUT during the development I would like to test in on the stable and master channels.
What the proper process you would recommend? check out the stable or the master in the framework get the engine version (via `engine.version`)and check that out and build? (I am still not sure what role plays the `src` repo, [buildroot](https://github.com/flutter/buildroot))

My issue is more about general knowledge, I will make the engine work but I would like to understand the underhood  so I could create a proper process in my company.

Thanks a lot for your help.

 

### Expected results

The app runs and compile with local engine

### Actual results

```
error: ../../../../flutter/flutter/packages/flutter/lib/src/rendering/layer.dart:2308:38: Error: 'PhysicalShapeEngineLayer' isn't a type.
        oldLayer: _engineLayer as ui.PhysicalShapeEngineLayer?,
                                     ^^^^^^^^^^^^^^^^^^^^^^^^
../../../../flutter/flutter/packages/flutter/lib/src/rendering/layer.dart:2302:29: Error: The method 'pushPhysicalShape' isn't defined for the class 'SceneBuilder'.
 - 'SceneBuilder' is from 'dart:ui'.
Try correcting the name to the name of an existing method, or defining a method named 'pushPhysicalShape'.
      engineLayer = builder.pushPhysicalShape(
                            ^^^^^^^^^^^^^^^^^
../../../../flutter/flutter/packages/flutter/lib/src/semantics/binding.dart:23:9: Error: The setter 'onSemanticsAction' isn't defined for the class 'PlatformDispatcher'.
 - 'PlatformDispatcher' is from 'dart:ui'.
Try correcting the name to the name of an existing setter, or defining a setter or field named 'onSemanticsAction'.
      ..onSemanticsAction = _handleSemanticsAction
        ^^^^^^^^^^^^^^^^^
../../../../flutter/flutter/packages/flutter/lib/src/semantics/semantics.dart:673:60: Error: Member not found: 'doNotUseWillBeDeletedWithoutWarningValuesAsList'.
      for (final SemanticsAction action in SemanticsAction.doNotUseWillBeDeletedWithoutWarningValuesAsList)
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../flutter/flutter/packages/flutter/lib/src/semantics/semantics.dart:685:54: Error: Member not found: 'doNotUseWillBeDeletedWithoutWarningValuesAsList'.
      for (final SemanticsFlag flag in SemanticsFlag.doNotUseWillBeDeletedWithoutWarningValuesAsList)
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../flutter/flutter/packages/flutter/lib/src/semantics/semantics.dart:2761:46: Error: Member not found: 'doNotUseWillBeDeletedWithoutWarningValuesAsList'.
    final List<String> flags = SemanticsFlag.doNotUseWillBeDeletedWithoutWarningValuesAsList.where((SemanticsFlag flag) => hasFlag(flag)).map((SemanticsFlag flag) => flag.toString().substring('SemanticsFlag.'.length)).toList();
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../flutter/flutter/packages/flutter/lib/src/widgets/text_selection.dart:3262:13: Error: The type 'AppLifecycleState' is not exhaustively matched by the switch cases since it doesn't match 'AppLifecycleState.hidden'.
 - 'AppLifecycleState' is from 'dart:ui'.
Try adding a default case or cases that match 'AppLifecycleState.hidden'.
    switch (state) {
            ^
../../../../flutter/flutter/packages/flutter/lib/src/scheduler/binding.dart:389:13: Error: The type 'AppLifecycleState' is not exhaustively matched by the switch cases since it doesn't match 'AppLifecycleState.hidden'.
 - 'AppLifecycleState' is from 'dart:ui'.
Try adding a default case or cases that match 'AppLifecycleState.hidden'.
    switch (state) {
            ^
Target debug_unpack_ios failed: Exception: No iOS frameworks found in /Users/michael.rozenblat/Desktop/flutter/engine/src/out/ios_debug_unopt_arm64/Flutter.xcframework
Target kernel_snapshot failed: Exception
Failed to package /Users/michael.rozenblat/Desktop/flutter_pendo/sample_apps/my_app/my_app.

```

### Code sample

there is no actual code sample 
`flutter create my_app`
and 
`flutter run --local-engine=$HOME/Desktop/flutter/engine/src/out/ios_debug_unopt_arm64`

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

`flutter doctor -v`
```
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F82 darwin-arm64, locale en-IL)
    • Flutter version 3.10.6 on channel stable at /Users/michael.rozenblat/Desktop/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (9 days ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/michael.rozenblat/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode-14.3.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • 178D5317-EE26-465D-811E-7ED06BC11E2B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.4.1 22F82 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 115.0.5790.102

[✓] Network resources
    • All expected network resources are available.
```

**Comment by MikePendo** [comment]
Hi @mraleph,
Maybe if you have a few spare minutes you could answer some of the question I had in the ticket. I can make the engine work but I would like to understand the underhood of the build process. I think my questions don't require really digging in to the issue
Thanks a lot

**Comment by MikePendo** [comment]
ok switching channel to master seems like run with local engine. (kinda anticipated). So probably the issue was caused by mismatching of flutter framework with the engine

**Comment by MikePendo** [comment]
So although it runs from command line it crashes if I get run via Xcode
<img width="1291" alt="Screenshot 2023-07-21 at 17 22 39" src="https://github.com/flutter/flutter/assets/56674958/cd9b983f-6667-4a78-ab21-99fc4376bd60">

**Comment by MikePendo** [comment]
so checking out  the 3.10.6 stable and building the engine withe from `engine.version ` checkout seems to work.
I guess there is some issue on the master

**Comment by huycozy** [comment]
Hi @MikePendo 
The goal of this Github repo is to improve flutter reporting bugs or feature requests.  Please see flutter's [community](https://flutter.dev/community) for resources and ask questions above.

 I'm not sure what is your current engine revision in the local engine repo (`src/flutter`). But taking a look at the error from the stack trace, it might be caused by it is missing https://github.com/flutter/engine/pull/42418. I see its commit is only available on some master versions, see https://github.com/flutter/engine/commit/81839ac81a644b58c598cbf3560eb9e76aafceeb. So I would suggest you fetch the latest engine version and retry. And when you check the engine build, please remember you set `--local-engine-src-path` param in the run command.

**Comment by MikePendo** [comment]
@huycozy 
Thanks, what do u mean some master versions? isn't it a single master.
in general the best approach to fetching the master would be:
To checkout master  channel and then use `engine.version` to check out the engine and build?
in that case what the `src` [buildroot](https://github.com/flutter/buildroot) responsible for? (I mean do we need to update it to something specific).

**Comment by huycozy** [comment]
>what do u mean some master versions? isn't it a single master.

You can click to "more" button to see all available versions contain that commit.
![Screenshot 2023-07-25 at 11 40 06](https://github.com/flutter/flutter/assets/104349824/3961f62e-bb87-4764-bdb7-63aaf6d1fc47)

>in that case what the src [buildroot](https://github.com/flutter/buildroot) responsible for?

It's build environment for the Flutter engine (as described in the repository's README file)

Could you confirm the issue has been solved on the latest master engine version? Please make sure you pull the latest changes from upstream:
```
git pull upstream main in src/flutter to update the Flutter Engine repo.
```
