### ISSUE TITLE
[CP] Allow OverlayPortal to be added/removed from the tree in a layout callback

### ISSUE THREAD

**Issue by LongCatIsLooong** [flutter/flutter#131002]
### Issue Link

https://github.com/flutter/flutter/issues/130668

### Commit Hash

bf4d659

### Target

beta

### PR Link

https://github.com/flutter/flutter/pull/130670

### Changelog Description

The application asserts when a `Tooltip` is opened/closed in a layout callback, typically in a `LayoutBuilder` or when scrolled away in a `ListView`.

### Impacted Users

Tooltip widget users, especially those use it in a ListView

### Impact Description

App asserts in debug mode

### Workaround

No easy workaround.

### Risk

low

### Test Coverage

yes

### Validation Steps

Either follow the steps provided in https://github.com/flutter/flutter/issues/130668, or run the test added in the fix: https://github.com/flutter/flutter/pull/130670/files#diff-d078821c55cd4390761f5928348ab73b271c76edb7c9a440af7edb08ad6896d7

**Comment by itsjustkevin** [comment]
@HansMuller could you take a look at this cherry-pick request and attach the cp: approved label if you support this cherry-pick?

**Comment by CaseyHillers** [comment]
Shipped in 3.13.0-0.4.pre beta
