### ISSUE TITLE
Only show linux desktop device if display server present

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#131016]
For certain workflows, such as in a cloud-based VM, the host environment may not even have a display server running. In these cases, we should not show "Linux (desktop)" as a connected device. Also, we don't need to show the desktop toolchain or check for IDEs.

**Comment by stuartmorgan** [comment]
> Also, we don't need to show the desktop toolchain

Why wouldn't we want to show the desktop toolchain in that scenario? You can build desktop apps without a display server.

It will make debugging setup issues with our own CI pretty difficult if the `flutter doctor` check we log at the beginning doesn't show the status of the tools we are going to be using.

**Comment by christopherfujino** [comment]
> > Also, we don't need to show the desktop toolchain
> 
> Why wouldn't we want to show the desktop toolchain in that scenario? You can build desktop apps without a display server.

This is true. Perhaps we should be explicit in these situations, that by installing those dependencies they can build linux desktop apps, but they still won't be able to run them without a display server?

> It will make debugging setup issues with our own CI pretty difficult if the `flutter doctor` check we log at the beginning doesn't show the status of the tools we are going to be using.

I think we can keep the behavior unchanged in verbose mode.

**Comment by stuartmorgan** [comment]
> Perhaps we should be explicit in these situations, that by installing those dependencies they can build linux desktop apps, but they still won't be able to run them without a display server?

Is this a common point of confusion? It seems odd to me to conditionalize that the toolchain section at all for desktop given that we don't conditionalize the Android or iOS toolchain sections based on the availability of a device.

**Comment by christopherfujino** [comment]
You changed my mind, I'm going to close this feature request.
