### ISSUE TITLE
ExpansionTile opened - initial state

### ISSUE THREAD

**Issue by leobispo** [flutter/flutter#13105]
Hi guys,

I am wondering why the ExpansionTile does not have an option to be opened at the initial state.

Is there any reason for that?

Would you accept a PR if I change the ExpansionTile to have a constructor argument to let the ExpansionTile be opened at the initial state?

**Comment by eseidelGoogle** [comment]
Sounds like a useful PR to me.  @HansMuller and @Hixie are the experts.

**Comment by Hixie** [comment]
We would definitely accept such a PR. It would be trivial; add a bool field (`initiallyExpanded` or some such, default false) to `ExpansionTile`, and in its state's `initState`, replace the fallback `false` with a reference to that field. The hardest part will be writing a test. :-)
