### ISSUE TITLE
Gradle OOM error across different platforms

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#131006]
For example: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8775032916537102849/+/u/run_test.dart_for_build_tests_shard_and_subshard_3_3/test_stdout

```
[        ] Execution failed for task ':app:packageDebug'.
[        ] > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
[        ]    > java.lang.OutOfMemoryError (no error message)
```

and

```
[        ] Caused by: java.lang.OutOfMemoryError: Java heap space
[        ] 	at java.base/java.io.ByteArrayOutputStream.<init>(ByteArrayOutputStream.java:81)
[        ] 	at com.android.zipflinger.NoCopyByteArrayOutputStream.<init>(NoCopyByteArrayOutputStream.java:27)
[        ] 	at com.android.zipflinger.Compressor.deflate(Compressor.java:35)
[        ] 	at com.android.zipflinger.BytesSource.build(BytesSource.java:89)
[        ] 	at com.android.zipflinger.BytesSource.<init>(BytesSource.java:50)
[        ] 	at com.android.zipflinger.Sources.from(Sources.java:40)
[        ] 	at com.android.zipflinger.Sources.from(Sources.java:32)
[        ] 	at com.android.builder.internal.packaging.ApkFlinger$writeFile$1.call(ApkFlinger.kt:198)
[        ] 	at com.android.builder.internal.packaging.ApkFlinger$writeFile$1.call(ApkFlinger.kt:195)
[        ] 	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428)
[        ] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[        ] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[        ] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[        ] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[        ] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

I have been seeing this intermittently all week.

**Comment by christopherfujino** [comment]
Earlier reported by cbracken July 11 in https://ci.chromium.org/p/flutter/builders/prod/Linux%20build_tests_3_3/1832?

**Comment by christopherfujino** [comment]
If I'm reading the top output correctly, it look like in https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8775032916537102849/+/u/OS_info/stdout

The bot had 30gb total, with only 3gb free before the test started.

**Comment by christopherfujino** [comment]
Although only 995MiB used? Not sure why free and used don't add up to total...

**Comment by keyonghan** [comment]
This ran on a VM. @reidbaker do you have any insight on this error?

**Comment by christopherfujino** [comment]
Flaky bot filed p0 because of this issue: https://github.com/flutter/flutter/issues/131322

**Comment by reidbaker** [comment]
[keyonghan](https://github.com/keyonghan) Do you have any idea what the heap space is on the machines? Could this be a legitimate OOM?

**Comment by keyonghan** [comment]
> [keyonghan](https://github.com/keyonghan) Do you have any idea what the heap space is on the machines? Could this be a legitimate OOM?

The issue happened across different platforms/testbeds, which sounds less likely a machine issue.

- https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20build_tests_3_3/8512/overview on a Linux VM, memory usage before running test: [`MiB Mem :  30073.3 total,   3000.9 free,    955.5 used,  26116.9 buff/cache`](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8775032916537102849/+/u/OS_info/stdout)
- https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20build_tests_1_4/11931/overview on a Mac arm bot, memory usage before running test: [`PhysMem: 3739M used (1450M wired), 12G unused.`](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8774937376017000001/+/u/OS_info/stdout)
- https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20build_tests_1_4/11954/overview on a Mac intel bot, memory usage before running test: [`PhysMem: 5180M used (2584M wired), 27G unused.`](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8774728186856664833/+/u/OS_info/stdout)

**Comment by eliasyishak** [comment]
Flakey bot also filed 2 more P0 issues:
- https://github.com/flutter/flutter/issues/131757
- https://github.com/flutter/flutter/issues/131754

**Comment by reidbaker** [comment]
Note from triage, On my plate for next week.

**Comment by reidbaker** [comment]
This is still on my radar. It is the next task after https://github.com/flutter/engine/pull/44724

**Comment by reidbaker** [comment]
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8772165294008113857/+/u/run_test.dart_for_build_tests_shard_and_subshard_3_3/test_stdout

**Comment by reidbaker** [comment]
Using 4g since that appears to be used in a few places in packages https://github.com/search?q=repo%3Aflutter%2Fpackages%20gradle.properties&type=code

**Comment by reidbaker** [comment]
If this issues shows up again when building flutter gallery we should reopen this issue. If it happens again for a different project we should open a new issue and reference this issue (and its solution).

**Comment by stuartmorgan** [comment]
> Using 4g since that appears to be used in a few places in packages https://github.com/search?q=repo%3Aflutter%2Fpackages%20gradle.properties&type=code even though build scan shows we only used 880Mib on my machine. https://scans.gradle.com/s/blb3dit4srnuu/performance/build

FWIW I believe I picked that number via the rigorous scientific process of "I really don't want to deal with this again in another year; what's a big number that should make it go away for the foreseeable number, but is well within the machines' capabilities?" 🙂
