### ISSUE TITLE
How to use StatefulNavigationShell outside of navigation bar GoRouter

### ISSUE THREAD

**Issue by GeorgePagounis** [flutter/flutter#131091]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Hello, I followed [https://codewithandrea.com/articles/flutter-bottom-navigation-bar-nested-routes-gorouter/](this) tutorial to achieve a stateful navigation with a bottom navigation bar using go router and riverpod. I now need to tap on a button inside the nested page and basically call the navigation bar onTap, which uses the StatefulNavigationShell to change route. Is it even possible to do this with this setup? And if so how?

### Expected results

I would expect to be able to somehow pass this StatefulNavigationShell variable from the router to the widget inside the branches list

### Actual results

I cannot seem to find a way to do this. Should I declare it as global and assign it  each time at this level?

```dart
 routes: <RouteBase>[
      StatefulShellRoute.indexedStack(
        builder: (BuildContext context, GoRouterState state,
            StatefulNavigationShell navigationShell) {
          //global navigation shell variable = navigationShell??
          return ScaffoldWithNavBar(navigationShell: navigationShell);
        },
```

### Code sample

<details><summary>Code sample</summary>

```dart
final navigationProvider = StateNotifierProvider.autoDispose
    .family<NavigationController, int, StatefulNavigationShell>(
  (ref, navigationShell) =>
      NavigationController(navigationShell: navigationShell),
);

class NavigationController extends StateNotifier<int> {
  NavigationController({required this.navigationShell}) : super(0) {
    state = navigationShell.currentIndex;
  }
  StatefulNavigationShell navigationShell;
  void onTap({
    required int value,
    required StatefulNavigationShell navigationShell,
  }) {
    state = value;
    navigationShell.goBranch(
      value,
      initialLocation: value == navigationShell.currentIndex,
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4 22F66 darwin-arm64, locale en-GR)
    • Flutter version 3.10.6 on channel stable at /Users/gogom/Flutter Apps/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (9 days ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/gogom/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • E05E459C-134F-4E5E-9F6B-2EC061AE4C1A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 114.0.5735.248

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by afriddev** [comment]
void _goOtherTab(BuildContext context, int index) {
    if (index == _currentIndex) return;
    GoRouter router = GoRouter.of(context);
    String location = tabs[index].initialLocation;

    setState(() {
      _currentIndex = index;
    });
    if (index == 3) {
      context.push('/login');
    } else {
      router.go(location);
    }
  }
}

**Comment by GeorgePagounis** [comment]
> void _goOtherTab(BuildContext context, int index) { if (index == _currentIndex) return; GoRouter router = GoRouter.of(context); String location = tabs[index].initialLocation;
> 
> ```
> setState(() {
>   _currentIndex = index;
> });
> if (index == 3) {
>   context.push('/login');
> } else {
>   router.go(location);
> }
> ```
> 
> } }

Hi @afriddev  could you elaborate a bit further, in your example you do not use the navigationShell anywhere, but you did help me , as I just did 
```dart
 GoRouter.of(context).go(PortfolioPage.routeLocation);
 ```
 
 Is there a better way, am I missing something or is it this simple?

**Comment by afriddev** [comment]
hey , by using index you can navigate

**Comment by GeorgePagounis** [comment]
Nevermind, thank you for the brainstorm!
