### ISSUE TITLE
App not running after downgrading to 3.7.12 from 3.10.6. 

### ISSUE THREAD

**Issue by fahad-whizpool** [flutter/flutter#131064]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Just run project even splash screen won't show up.

### Expected results

App Run successfully

### Actual results

I have downgraded to 3.7.12 from 3.10.6. because there were some random crashes in IOs for flutter. now i am facing this. 
 
FAILURE: Build failed with an exception.

* Where:
Script '/Users/mac/developer/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1157

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/mac/developer/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
Exception: Gradle task assembleDebug failed with exit code 1
Exited

### Code sample

<details><summary>Code sample</summary>

```dart
awesome_notifications: ^0.7.4
  api_cache_manager: ^1.0.1
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+3
  device_info_plus:
  dio: ^5.1.1
  flutter_screenutil:
  #Bug:Fl-577 temp changin file picker
  file_picker: 
  #  git:
  #     url: https://github.com/miguelpruivo/flutter_file_picker.git
  #     ref: c724ec05589c683cf0e2d8da4e231d6ff97b648f 
  flutter_svg:
  flutter_archive: ^5.0.0
  fluttertoast: ^8.2.1
  firebase_auth: ^4.6.1
  firebase_crashlytics: ^3.3.3
  firebase_core: ^2.13.0
  flutter_email_sender: ^5.2.0
  google_fonts: ^4.0.4
  google_mobile_ads: ^3.0.0
  get: ^4.6.5
  get_it: ^7.2.0
  intl: ^0.18.1
  in_app_review: ^2.0.6
  lottie: ^2.2.0
  mime: ^1.0.4
  media_store_plus: ^0.0.7
  open_file_plus: ^3.4.1
  pretty_dio_logger: ^1.3.1
  permission_handler: ^10.2.0
  path_provider: ^2.0.14
  path: 
  package_info_plus: ^4.0.1
  syncfusion_flutter_sliders: ^21.1.38
  scrollable_positioned_list: ^0.3.2
  share_plus: ^7.0.1
  stop_watch_timer: ^2.0.0
  video_player: ^2.5.1
  uuid: ^3.0.7
  notification_permissions: ^0.6.1
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel unknown, 3.7.12, on macOS 12.6 21G115 darwin-x64, locale en-GB)
    ! Flutter version 3.7.12 on channel unknown at /Users/mac/developer/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.75.1)
[✓] VS Code (version 1.67.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment]
Hi @fahad-whizpool 
Please provide the complete output of `flutter run -v` so we may verify this. Also, you are using many dependencies that could cause the issue, if the issue is related to a 3rd package/plugin, you should file an issue to it's developers.
