### ISSUE TITLE
[Impeller] Implement push constants for vulkan solid fill

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#131095]
Recently we moved over to varying variables since they are faster than the uniforms we were using for the `solid_fill.frag`.  Push constants should be faster still.

This requires:
1) switching the shader file
1) updating impellerc to generate the proper information in the generated header
1) adding a branch in solid_color_contents.cc to use push constants when necessary

It's uncertain what the actual different in performance will be but we have seen this be a significant const in certain apps so we believe it's worth pursuing.

Design doc: https://docs.google.com/document/d/1KqZD9oowLXGkqbRZWuhbbd3BOTAU5hyYn_gh7xvBvo0/edit

**Comment by gaaclarke** [comment]
https://github.com/flutter/engine/pull/43984 investigated this and measuring the results it didn't show a noticeable difference and getting it landed would require adding a fair bit of complexity to impeller.  Since we didn't see a big difference it didn't seem worthwhile.

See: https://github.com/flutter/engine/pull/43984#issuecomment-1652232023

**Comment by gaaclarke** [comment]
As an added note, the CVT counters in Streamline didn't appear to show any difference with https://github.com/flutter/engine/pull/43984.  (As measured by Jonah in the same setup he used when writing up his doc).

**Comment by chinmaygarde** [comment]
Oh, well. It was definitely worth a shot. Thanks for investigating.

**Comment by chinmaygarde** [comment]
Closing this as not planned after the findings of the investigation.
