### ISSUE TITLE
[CP] Fix assertion when a `WidgetSpan` is scaled by certain textScaleFactor values

### ISSUE THREAD

**Issue by LongCatIsLooong** [flutter/flutter#131004]
### Issue Link

https://github.com/flutter/flutter/issues/130588

### Commit Hash

0d1cc33

### Target

beta

### PR Link

https://github.com/flutter/flutter/pull/130648

### Changelog Description

Apps that use `WidgetSpan`s in text widgets may throw an assertion when the text scale factor is set to certain values.

### Impacted Users

WidgetSpan users

### Impact Description

Apps that use `WidgetSpan`s in text widgets may throw an assertion when the text scale factor is set to certain values, due to floating point precision.

### Workaround

No easy workaround available

### Risk

low

### Test Coverage

yes

### Validation Steps

Follow the repro steps in https://github.com/flutter/flutter/issues/130588, or run this test: https://github.com/flutter/flutter/pull/130648/files#diff-9fccc94ba0e90a5fb4c5b90761fe59995a5cf7bad0d580c6c2ff3cceafb495e5

**Comment by itsjustkevin** [comment]
Thanks again for the cherry-pick @LongCatIsLooong, it seems like there may have been an error in the changelog description, could you take a look?

@HansMuller could you take a look at this cherry-pick request and attach the cp: approved label if you support this cherry-pick?

**Comment by LongCatIsLooong** [comment]
Turns out I missed that in `computeDryLayout` and this commit needs to be added too: https://github.com/flutter/flutter/pull/131765. @XilaiZhang should I update the CP pull request to include that commit when it's merged, or that deserves its own CP request?

**Comment by XilaiZhang** [comment]
yeah it would need another cp request and cp approval. @itsjustkevin are we going to do another hotfix on 3.13.0 next week?

**Comment by tgucio** [comment]
#131765 is now merged.

**Comment by CaseyHillers** [comment]
Shipped in 3.13.0-0.4.pre beta
