### ISSUE TITLE
Rotation gesture

### ISSUE THREAD

**Issue by wmleler** [flutter/flutter#13103]
The current gesture detector has a scale gesture, but does not have the other common two-finger gesture, which is rotate. Since the two are closely related (both require two fingers, and need to calculate a center), would be nice if we either added rotate to the scale gesture, or had a similar gesture for rotate that shares some code.

**Comment by goderbauer** [comment]
Let's close this since it seems to be implemented by #17345. Anybody should feel free to file a new bug with more details if there are still missing bits.
