### ISSUE TITLE
[Impeller] Trim the thread-local command pools from time to time.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#131033]
Today, the individual command buffers are collected but the pools are never trimmed. This may cause use to hold onto more memory than necessary across an entire application run.

Issue raised as part of the comment chain in https://github.com/flutter/engine/pull/43867.

**Comment by jonahwilliams** [comment]
As of https://github.com/flutter/engine/pull/46166 we reset a rotation selection of cmd pools per frame.
