### ISSUE TITLE
[Impeller] Failure to render text glyph shadows.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#131012]
Noticed this at wonderous near ToT.

>  Break on 'ImpellerValidationBreak' to inspect point of failure: Could not find glyph position in the atlas with scale:

**Comment by huycozy** [comment]
When triaging issue https://github.com/flutter/flutter/issues/130613, the OP noticed the output log similar to the log above. I just leave my comment here if it's helpful for the investigation.

>  [VERBOSE-2:validation.cc(49)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not find glyph position in the atlas.

But it's only reproducible when using [fast_cached_network_image](https://pub.dev/packages/fast_cached_network_image) package (see https://github.com/flutter/flutter/issues/130613#issuecomment-1644045875). It causes the widget to be invisible when scrolling custom 3D Cube PageView in the carousel view. 

Checking [flutter-wonderous-app](https://github.com/gskinnerTeam/flutter-wonderous-app), I also notice that log from the output console on iOS platform.

Verifying this on the master channel.

<details>
<summary>flutter doctor -v (master)</summary>

```bash
[!] Flutter (Channel master, 3.13.0-7.0.pre.57, on macOS 13.4.1 22F770820d darwin-x64, locale en-VN)
    • Flutter version 3.13.0-7.0.pre.57 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 83e5aca1c9 (88 minutes ago), 2023-07-20 21:26:17 -0400
    • Engine revision b5a6b1c9cb
    • Dart version 3.1.0 (build 3.1.0-332.0.dev)
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D                         • android-arm64  • Android 11 (API 30)
    • iPhone (mobile)  • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.7.2 19H218
    • macOS (desktop)  • macos                                    • darwin-x64     • macOS 13.4.1 22F770820d darwin-x64
    • Chrome (web)     • chrome                                   • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by delfme** [comment]
Hello @jonahwilliams maybe this is interesting to you

https://github.com/flutter/flutter/issues/130613#issuecomment-1644045875

@huycozy pointed me here and it looks this might be the same issue. We closed 130613 coz I thought I had no time to create a sample but then I made one. 

As pointed out, `fast_cached_network_image ` also uses `hive` and `dio` internally, but we use those other plugins in our projects and have no issues with them.

**Comment by jonahwilliams** [comment]
@dnfield this is a regression from the glyph atlas changes. I'm not sure exactly why, but the compute scale for the text in the shadows is 1.0, which means its likely not computed the same as the traversal in entity pass.

**Comment by delfme** [comment]
Hello, just tested sample repo from 130613 after @bdero fix and that issue still persists.
https://github.com/flutter/flutter/issues/130613#issuecomment-1644045875
We will revert to 3.12.0 but are available to check things again at need.

**Comment by delfme** [comment]
Also noticed that after #43920 we no longer see the log: "[VERBOSE-2:validation.cc(49)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not find glyph position in the atlas."

We now see only the widgets getting unmounted.
I paste the sample link also here.
https://github.com/delfme/cube-sample
Can a plugin's bug force widgets to get unmounted after they have been rendered?

**Comment by delfme** [comment]
This might help narrow investigation, made time to test on more recent beta 3.13.0-0.2.pre (and 3.13.0-0.1.pre) and issue 130613 is not reproducible there.

@huycozy quick wrote this here but at this point I think the two issues might be unrelated, so please let me know if you want me to write only on
https://github.com/flutter/flutter/issues/130613

**Comment by bdero** [comment]
@delfme Although it looks like you were hit by the validation failure for some time, the current issue you're facing appears to be unique and not related to the validation failure. So keeping it to https://github.com/flutter/flutter/issues/130613 sounds like the right move. 👍
