### ISSUE TITLE
Navigator push method isn't marked async

### ISSUE THREAD

**Issue by mjohnsullivan** [flutter/flutter#13100]
When trying to get a value passed back from a popped route, the documentation gives an example using await, which doesn't work as the push() (and pushNamed) method isn't marked as async.

    bool value = await Navigator.of(context).push(new MaterialPageRoute<bool>(
    builder: (BuildContext context) {
        return new Center(
        child: new GestureDetector(
            child: new Text('OK'),
            onTap: () { Navigator.of(context).pop(true); }
        ),
        );
    }
    ));

Using the future directly with .then() works.

Should push and pushNamed be marked async, or the docs updated?

**Comment by Hixie** [comment]
You can use `await` without the method you are awaiting being marked `async`, so long as the method you are _in_ is marked `async`.

There's no difference between a method marked `async` and one not marked `async` from the perspective of the caller, all it does is change how the compiler compiles the code within the method.

**Comment by mjohnsullivan** [comment]
My bad for misunderstanding the await/async ordering. Working as intended:

    _navigateUsingConstructor() async {
      _value = await Navigator.of(context).push(
        new MaterialPageRoute(
          builder: (context) => new MyWidget(value: _value)
        )
      );
    }
