### ISSUE TITLE
Clean up xcodebuild's messy output

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#13104]
Our console output when running xCode builds is very noisy and hard to read. We heard very good things about https://github.com/supermarin/xcpretty from another team that runs xCode builds, so would be good to give that a try for Flutter.

**Comment by xster** [comment]
xcpretty doesn't have a brew formula which is unfortunate. We'd have to make it very optional since the user have to wrangle with ruby gems

**Comment by mit-mit** [comment]
Is there no way of bundling xcpretty into our SDK?

**Comment by xster** [comment]
There's actually something rather inconvenient with xcpretty
https://github.com/supermarin/xcpretty/issues/163

Since building the dart snapshot via script is one of the main components of the xcode build phases, having its output not show up is pretty inconvenient.

**Comment by xster** [comment]
For reference, I have a PR to use xcpretty (https://github.com/flutter/flutter/compare/master...xster:xcpretty?expand=1) but I think we shouldn't use it if it doesn't show any snapshotting output. 

Going to clean up the existing xcodebuild's stdout instead for now.

**Comment by xster** [comment]
With #14586, a failed build's output will be:
```
flutter build ios                                                                                                                                                                                                                 (02-09 00:54:37)
Building flutter tool...
Running "flutter packages get" in t72_base_ios_app...  0.5s
Building com.example.t72BaseIosApp for device (ios-release)...
Found saved certificate choice "iPhone Developer: Xiao Yu". To clear, use "flutter config".
Signing iOS app for device deployment using developer identity: "iPhone Developer: Xiao Yu"
Running Xcode clean...                                0.8s
Running Xcode build...                                5.4s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release ===
    Building AOT snapshot in release mode (ios-release)...
    Dart snapshot generator failed with exit code 254
    Error: 'file:///Users/xiao/Development/flutter-test/t72_base_ios_app/lib/main.dart': error: line 15 pos 19: semicolon expected
            })));wrong
                      ^
    Failed to build /Users/xiao/Development/flutter-test/t72_base_ios_app.
    Command /bin/sh failed with exit code 255
```

I think it's good enough.
