### ISSUE TITLE
Multi-view MVP has a fourth ghost view

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#131089]
When running any of the MVP demos (https://github.com/goderbauer/mvp) on macOS three windows are shown on screen. But `PlatformDispatcher.views` reports the existence of a forth ghost view.

It appears that the forth view is the implicit view, for which no backend surface (in form of a window) is provided.

When the implicit view is enabled, the demos should provide it with a window. When the implicit view is disabled, is should not appear in `PlatformDispatcher.views`.

**Comment by goderbauer** [comment]
@dkwingsmt I believe you mentioned you had a fix for this? @CoderDake ran into this problem when getting DevTools ready for multi view. The ghost view also shows up in DevTools and behaves in strange ways...

**Comment by dkwingsmt** [comment]
No, I don't have a fix for this yet. I'm not sure where it went wrong, but I think it's a macOS runner API issue, and we'll address it (and with a test) when we land it on stable.
