### ISSUE TITLE
Failed assertion: line 5235 pos 12: '_history.isNotEmpty': is not true.

### ISSUE THREAD

**Issue by maucoder-ingeint** [flutter/flutter#131086]
Got this message:

> 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 5235 pos 12: '_history.isNotEmpty': is not true.
> 
> Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
> In either case, please report this assertion by filing a bug on GitHub:

I was validating a list with the method "isNotEmpty" in another list with this:

```dart
(filesAttach.isNotEmpty
                  ? [
                      Container(
                        width: 30,
                        height: 30,
                        alignment: Alignment.topRight,
                        child: Container(
                          width: 15,
                          height: 15,
                          decoration: BoxDecoration(
                              shape: BoxShape.circle,
                              color: const Color(0xffc32c37),
                              border:
                                  Border.all(color: Colors.white, width: 1)),
                          child: Padding(
                            padding: const EdgeInsets.all(0.0),
                            child: Center(
                              child: Text(
                                filesAttach.length.toString(),
                                style: const TextStyle(fontSize: 10),
                              ),
                            ),
                          ),
                        ),
                      )
                    ]
                  : [])
```
I use parenthesis to append this element to another list when conditional is True, I don't know why it's happening this error.

**Comment by maucoder-ingeint** [comment]
Trying another ways, I discovered that when I use my item builder like this, the error doesn't happen:

```dart
itemBuilder: (BuildContext bc) {
        return [
          PopupMenuItem(
            onTap: () => openFileView(filesAttach),
            child: Text('file.attach'.tr()),
          )
        ];
      },
```

Calling the method openFileView like above example, I got the error,
but calling directly doesn't raises error messages:

```dart
// For some reason this works, but calls my method in the moment where I tap the PopupMenuButton, so it's not working for me
          PopupMenuItem(
            onTap: openFileView(filesAttach),
            child: Text('file.attach'.tr()),
          )
```

Sorry for my bad english, I hope it works

**Comment by afriddev** [comment]
Navigator.of(context).pushReplacement(MaterialPageRoute())

**Comment by huycozy** [comment]
Hi @maucoder-ingeint,
It seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any.
If you are proposing a change, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly.

Closing for now.

**Comment by maucoder-ingeint** [comment]
I think it was an flutter error for the log message, sorry for that and thanks for reply
