### ISSUE TITLE
Timeline: Frame.tdur value appears to be incorrect on iOS

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#13111]
On timeline data collected from iOS devices, I see a lot of `Frame` events with unreliable-looking `tdur` values. In a local run of `flutter_gallery_ios__transition_perf`, the `Frame.tdur` value is 0 microseconds for 75% of the events. This is in contrast to 0% of the equivalent events when run on an Android device.

Example event:
```json
{
  "name": "Frame",
  "cat": "Dart",
  "tid": 26627,
  "pid": 426,
  "ts": 14794467779,
  "tts": 339233,
  "ph": "X",
  "dur": 1450,
  "tdur": 0,
  "args": {
    "mode": "basic",
    "isolateNumber": "46788812"
  }
},
```

This value is computed in the VM's `OS::GetCurrentThreadCPUMicros()` in `runtime/vm/os_macos.cc`.

The place where we start the frame event in Flutter is `handleBeginFrame()` in `packages/flutter/lib/src/scheduler/binding.dart`.

Related: [Trace Event Format](https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview#heading=h.nso4gcezn7n1) documentation.

## Steps to Reproduce

Edit `examples/flutter_gallery/test_driver/transitions_perf_test.dart` to add the following line after the call to `summary.writeSummaryToFile` on line 210:
```
await summary.writeTimelineToFile('transitions_full', pretty: true);
```

Run the Gallery transitions benchmark:
```
cd dev/devicelab
dart bin/run.dart -t flutter_gallery_ios__transition_perf
```

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.13.1 17B48, locale en-AU, channel master)
    • Flutter at /Users/cbracken/src/flutter/flutter
    • Framework revision 86e23bdb64 (3 days ago), 2017-11-17 12:05:39 -0800
    • Engine revision 4733e33737
    • Tools Dart version 1.25.0-dev.11.0
```

**Comment by cbracken** [comment]
@rmacnak-google I marked you assigned but if you're unable to take a look please let me know.

**Comment by rmacnak-google** [comment]
In the Dart VM, on Mac and iOS this ultimately boils down to mach's thread_info. [Chromium](https://chromium.googlesource.com/chromium/src/base/+/master/time/time.h) uses this on Mac but disables asking about thread time altogether on iOS.

**Comment by cbracken** [comment]
In #13117 I'm migrating our benchmarks off thread duration onto cpu duration. Once that's in, I'd be in favour of eliminating the `tdur` report for iOS, and setting it to an obviously bad value like `-1` in `OS::GetCurrentThreadCPUMicros`.

**Comment by cbracken** [comment]
#13117 has now landed.

@rmacnak-google has landed a [Dart VM patch](https://dart-review.googlesource.com/c/22282/) to return `-1` from `GetCurrentThreadCPUMicros` on iOS.
