### ISSUE TITLE
[go_router] Seamless integration between nested GoRouter classes

### ISSUE THREAD

**Issue by vasilich6107** [flutter/flutter#131181]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Hi.

If you develop a big app sometimes you are splitting the app on separate features.
Separate feature require the isolated navigation.
At this point I came to nesting GoRouters.

Technically this is not an impossible to achieve but there are several things that are hard to address
- deeplink handling
- proper browser history stack maintanance + back and forward actions
- routing `app/featureA/*` to specific subfeature.

I tried to overcome those issues but the solution does not looks good and has a bunch of workarounds. 

### Proposal

Consider updating GoRouter functionality to have an ability of seamless integration between nested instances of `GoRouter`

**Comment by dam-ease** [comment]
Hi @vasilich6107. Thanks for this proposal. Can you explain more on what you mean by seamless integration between nested instances of GoRouter if possible with an example?
