### ISSUE TITLE
CMAKE_LIBRARY_OUTPUT_DIRECTORY | CMAKE_RUNTIME_OUTPUT_DIRECTORY support

### ISSUE THREAD

**Issue by kirill-21** [flutter/flutter#131163]
![image](https://github.com/flutter/flutter/assets/63228361/9431a9cb-da6a-40de-956a-49e6b25f8a86)

Can you add support for this CMake command so that all dlls from packages could be built into the separate folder?

Platform: Windows

**Comment by kirill-21** [comment]
So i did found that it can be done with this variable, however, now app can not find this dlls
![image](https://github.com/flutter/flutter/assets/63228361/73fd4350-9075-4bf9-8f45-21a10d1bbb92)

with this error
![image](https://github.com/flutter/flutter/assets/63228361/7281cf87-d242-4de5-90f3-388dfaec828d)

**Comment by stuartmorgan** [comment]
If you modify your build files to move files, you would need to also modify it to change the load paths.

Closing as this is out of scope; the Flutter template builds apps in a specific structure, and anyone who wants a different structure is welcome to modify their builds, but it's up to them to make complete/consistent modifications.

**Comment by kirill-21** [comment]
> If you modify your build files to move files, you would need to also modify it to change the load paths.
> 
> Closing as this is out of scope; the Flutter template builds apps in a specific structure, and anyone who wants a different structure is welcome to modify their builds, but it's up to them to make complete/consistent modifications.

Where do I do that? (Change the load path)

**Comment by stuartmorgan** [comment]
Help with CMake changes in your project is not in scope for Flutter's issue tracker. I would recommend checking general CMake resources/forums for information about how to manage library linking and loading.

**Comment by kirill-21** [comment]
If anybody is looking for the answer then here is a full example with media_kit plugin:

**1. Go to your project, open "Windows" folder and find CMakeLists.txt file.**
**2. Open this file and find these two lines:**
```CMake
set(INSTALL_BUNDLE_DATA_DIR "${CMAKE_INSTALL_PREFIX}/data")
set(INSTALL_BUNDLE_LIB_DIR "${CMAKE_INSTALL_PREFIX}")
```
and change them to this:
```CMake
set(INSTALL_BUNDLE_LIB_SUBDIR "media_kit") # Here you can choose any name for the folder where all dlls from this package will be located
set(INSTALL_BUNDLE_DATA_DIR "${CMAKE_INSTALL_PREFIX}/data")
set(INSTALL_BUNDLE_LIB_DIR "${CMAKE_INSTALL_PREFIX}/${INSTALL_BUNDLE_LIB_SUBDIR}")

# Delay main plugin dlls loading to avoid "The code execution cannot proceed because ...dll was not
# found" error
target_link_options(${BINARY_NAME} PRIVATE "/DELAYLOAD:screen_brightness_windows_plugin.dll")
target_link_options(${BINARY_NAME} PRIVATE "/DELAYLOAD:media_kit_libs_windows_video_plugin.dll")
target_link_options(${BINARY_NAME} PRIVATE "/DELAYLOAD:media_kit_video_plugin.dll")
```
**3. Find this two line of code in the same file:**
```CMake
install(FILES "${FLUTTER_LIBRARY}" DESTINATION "${INSTALL_BUNDLE_LIB_DIR}"
  COMPONENT Runtime)
```
and replace them with this:
```
install(FILES "${FLUTTER_LIBRARY}" DESTINATION "${CMAKE_INSTALL_PREFIX}"
  COMPONENT Runtime)
```
This code will make sure that flutter_windows.dll is located at the same folder where your main executable is being compiled
**4. Scroll down to the last line in this file and add there the following code:**
```CMake
# Copy main flutter dlls from [https://docs.flutter.dev/platform-integration/windows/building]
# to the same folder where app's executable is located. Remove dlls from their original source path
# after copying.
set(SOURCE_FILES
  "${CMAKE_CURRENT_BINARY_DIR}/runner/Release/${INSTALL_BUNDLE_LIB_SUBDIR}/msvcp140.dll"
  "${CMAKE_CURRENT_BINARY_DIR}/runner/Release/${INSTALL_BUNDLE_LIB_SUBDIR}/api-ms-win-crt-runtime-l1-1-0.dll"
  "${CMAKE_CURRENT_BINARY_DIR}/runner/Release/${INSTALL_BUNDLE_LIB_SUBDIR}/vcruntime140.dll"
  "${CMAKE_CURRENT_BINARY_DIR}/runner/Release/${INSTALL_BUNDLE_LIB_SUBDIR}/vcruntime140_1.dll"
)
install(CODE "
  execute_process(COMMAND ${CMAKE_COMMAND} -E copy ${SOURCE_FILES} ${CMAKE_CURRENT_BINARY_DIR}/runner/Release)
  file(REMOVE ${SOURCE_FILES})
")
```
**5. Navigate to Windows/runner/main.cpp and add this method below all includes**
```c++
// Tries to add provided path to the set of directories that are searched for a DLL
void _addFolderToLookable(std::wstring path) {
  // Construct the path to the binaries folder
  std::wstring dllDirectory = path + L"\\" + L"media_kit";

  // Try multiple WinAPI methods in case one won't work (due to old windows versions, etc.)
  AddDllDirectory(dllDirectory.c_str());
  SetDllDirectoryW(dllDirectory.c_str());
}
```
then add the following code to the beginning of wWinMain method:
```c++
  // Add path to [INSTALL_BUNDLE_LIB_SUBDIR] variable from CMake so that all /DELAYLOAD dlls
  // can be loaded
  WCHAR exePath[MAX_PATH];
  DWORD pathLength = GetModuleFileName(0, exePath, MAX_PATH);
  if (pathLength != 0 && !std::wstring(exePath).empty()) {
    // Extract the directory path from the executable path
    std::wstring exeDirectory = exePath;
    size_t lastSeparator = exeDirectory.find_last_of(L"\\/");
    exeDirectory = exeDirectory.substr(0, lastSeparator + 1);

    _addFolderToLookable(exeDirectory);
  } else {
    // Try one more way of retrieving current app's folder
    pathLength = GetCurrentDirectory(MAX_PATH, exePath);
    if (pathLength != 0) {
      std::wstring exeDirectory = exePath;
      if(!exeDirectory.empty()) _addFolderToLookable(exeDirectory);
    }
  }
```
Make sure #include <windows.h> and #include <psapi.h> are included at the top of the file.

Result: All default flutter dlls are located near the main executable and all plugin dlls can be found in media_kit directory. This methods supports all windows versions from 7 to 11.
![image](https://github.com/alexmercerind/media_kit/assets/63228361/b750e196-386e-4f32-a667-23aebf308498)
