### ISSUE TITLE
Change Android emulator instructions to use Flutter plugin workflow

### ISSUE THREAD

**Issue by LarkAscending** [flutter/flutter#13118]
From hackathon:
## Steps to Reproduce

Following instructions on https://flutter.io/setup/ under Android setup> Set up the Android emulator means 
1. Can’t start the avd manager from Android studio w/o creating a project - answering the zillion questions for the app creation wizard
1. So instead install the flutter plugin from the startup screen in studio, then create a new flutter app to start android studio
1. Then can get to avd, and no need to create flutter app from command line.

## Requested Fix

We should update the steps to install the Flutter plugin so new users don't have to create a dummy project in Android Studio in order to use the Emulator.
1. In Android Studio Welcome screen (which you only see if no projects exist), select **Configure>Plugins**. 
1.  **Browse repositories>Flutter plugin>Install**.
1. In Android Studio, Tools>Android>AVD Manager to set up a virtual device.

/cc @mit-mit

**Comment by mit-mit** [comment]
Don't we also need this step between 2 and 3? Isn't the AVD manager option only available if you have some project open?

2.5. Create a new Flutter project with **File > New Flutter Project**

**Comment by Hixie** [comment]
Closing as covered by https://github.com/flutter/flutter/issues/13379
