### ISSUE TITLE
[Impeller] fullscreen clips can de-opt clear color optimization.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#131100]
This is one of the causes of excessive overdraw on flutter/gallery. There are multiple full screen color draws which are expensive, but these don't always hit the clear color optimization as there is some clipping happening.

Additionally, unecessary clipping is more expensive on Android, so avoiding extra stencil operations might be good independently of the clear color optimization.

**Comment by afriddev** [comment]
Navigator.of(context).push(PageRouteBuilder(
    opaque: false,
    pageBuilder: (BuildContext context, _, __) {
        return YourFullScreenAlertDialog()
    }
));
