### ISSUE TITLE
Web Push support for Flutter apps, via Dart integration with service workers

### ISSUE THREAD

**Issue by lukehutch** [flutter/flutter#131144]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Right now Android apps really have to use Firebase Cloud Messaging (FCM) if they want to support push notifications.

There is one alternative, UnifiedPush, but you have to keep a persistent notification open in the notification bar if you don't want the user to miss push notifications (since only Google can push messages to Google Play Services, and 3rd party apps don't have the priority needed to listen always for notifications).

Flutter really needs to support an alternative to FCM and UnifiedPush.

One promising alternative is Web Push. This requires a Javascript service worker to be downloaded by, and registered in, the web browser on the device. I assume that Android Chrome runs these service workers as system services, so that they are never shut down, or so that they never miss events.

However, there seems to be no easy way for a Flutter app to start a Javascript service worker, or to have a JS service worker communicate push events back to the Flutter app. (If I'm wrong and this is already possible, it would be great if somebody could point me in the right direction, so that I could get this working.)

### Proposal

It would be great if the Flutter team could work with the Chrome team to expose service worker notifications to Flutter apps.

(My blue-skies goal is to add push notification capabilities to the Serverpod server and client, so that it's possible to push notifications to a Serverpod app without relying on a 3rd party service.)

**Comment by stuartmorgan** [comment]
> It would be great if the Flutter team could work with the Chrome team to expose service worker notifications to Flutter apps.

Whether an app is written in Flutter or not doesn't affect its ability to interact with other applications; if Chrome provides a way for external applications to register service workers on their behalf then Flutter apps could use it to, and if there's no such mechanism then Flutter apps won't be able to do it either.

You'd need to file a feature request with Chrome to expose service workers as a service for other applications for what you are describing to be possible. Closing as there is nothing Flutter-specific to track here.
