### ISSUE TITLE
Support for getting device screen size in inches

### ISSUE THREAD

**Issue by CoderUni** [flutter/flutter#131111]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I have a package called [responsive_sizer](https://pub.dev/packages/responsive_sizer) and I'm trying to calculate `dp` and `sp` according to the [Material Design specs](https://m2.material.io/design/layout/pixel-density.html#pixel-density-on-android). From what I understand, we need to divide the device's screen width in pixels by its screen width in inches to obtain its screen density. However, there doesn't seem to be a way to obtain the device's screen width in inches.

### Proposal

Hoping that the Flutter team could allow us to obtain a device's screen size in inches similar to how we could obtain the device pixel ratio by simply calling `View.of(context).devicePixelRatio`. Thanks for your hard work!

**Comment by hkarmoush** [comment]
Will it make sense to write this as an extension for the `MediaQuery`?

**Comment by CoderUni** [comment]
That works better. `MediaQuery` seems to be a better place for it.

**Comment by darshankawar** [comment]
@CoderUni 
Can you take a look at [this](https://pub.dev/packages/sized_context) community package and see if it helps to achieve your use case ?

**Comment by CoderUni** [comment]
> @CoderUni Can you take a look at [this](https://pub.dev/packages/sized_context) community package and see if it helps to achieve your use case ?

@crizant is right. It doesn't return the correct value because of the way it calculates the screen size in inches [here](https://github.com/gskinnerTeam/flutter-sized-context/blob/bd7ebd48dd548f0b1ccf27a3537a82d12d2fcdc5/lib/src/extensions.dart#L32).

**Comment by crizant-mpower** [comment]
> > @CoderUni Can you take a look at [this](https://pub.dev/packages/sized_context) community package and see if it helps to achieve your use case ?
> 
> @crizant is right. It doesn't return the correct value because of the way it calculates the screen size in inches [here](https://github.com/gskinnerTeam/flutter-sized-context/blob/bd7ebd48dd548f0b1ccf27a3537a82d12d2fcdc5/lib/src/extensions.dart#L32).

It even uses 96ppi when running the package on iOS Safari. LOL

**Comment by crizant** [comment]
> > @CoderUni Can you take a look at [this](https://pub.dev/packages/sized_context) community package and see if it helps to achieve your use case ?
> 
> @crizant is right. It doesn't return the correct value because of the way it calculates the screen size in inches [here](https://github.com/gskinnerTeam/flutter-sized-context/blob/bd7ebd48dd548f0b1ccf27a3537a82d12d2fcdc5/lib/src/extensions.dart#L32).

It even uses 96ppi when running the package on iOS Safari. LOL

**Comment by CoderUni** [comment]
yeah.

`just making github bot remove awaiting response tag`

**Comment by benthillerkus** [comment]
I've started building a [package](https://github.com/benthillerkus/millimeters) that allows you to retrieve the actual screen dimensions in millimeters. Doesn't support all platforms and edge cases yet, but depending on what you're trying to do it's already enough.

That being said, I don't think physical measurements make sense for calculating density, as they don't take distance to the screen into account.

**Comment by CoderUni** [comment]
@benthillerkus  Thanks for the suggestion. Hopefully, your package will support android and ios soon as well. Also, what do you mean by taking distance to the screen into account? Is this the distance from the user to the screen itself?

**Comment by darshankawar** [comment]
@CoderUni 
It looks like a package could address your proposal. Would https://github.com/flutter/flutter/issues/131111#issuecomment-1666947603 package suffice your use case once it supports mobile platform ?

Also, it probably may not be feasible to provide the screen size in mm or in inches out of the box.

**Comment by CoderUni** [comment]
@darshankawar It would. Just hoping they'd be able to support the mobile platform in the near future. Thanks.

**Comment by benthillerkus** [comment]
> @benthillerkus  Thanks for the suggestion. Hopefully, your package will support android and ios soon as well. Also, what do you mean by taking distance to the screen into account? Is this the distance from the user to the screen itself?

yes. there's no way to know that, but it matters immensely.


I'm currently working on Android support, but there are a bunch of edge cases (like folding screens, Android TV, vendor specific window management like tiling or overlays, that I wont be able to test, and where I don't have high hopes that it'll work properly.

**Comment by darshankawar** [comment]
Thanks for the updates. Given that a community package that would offer the functionality is in progress, I suggest to keep an eye on its progress, as I mentioned earlier, providing such feature in the framework out of the box may not be feasible, hence I'll close this issue and follow-up in community package's dedicated repo for further updates.
If anybody disagrees, write in comments and I'll reopen it.
