### ISSUE TITLE
getting error during sign_in 

### ISSUE THREAD

**Issue by ashish168** [flutter/flutter#131147]
![image](https://github.com/flutter/flutter/assets/11817011/a8db23b4-b1ee-4641-b1bf-9b7625a3ab51)

**Comment by FarisArmoush** [comment]
can you share the code?

**Comment by ashish168** [comment]
Hi ,

  Please find my git details , where i have uploaded my code

https://github.com/ashish168/step_02/tree/main

Thanks
Ashish Aggarwal
8587994099

**Comment by ashish168** [comment]
Hi ,

I have uploaded the project again on below link , after removing keys from
firebase_options.dart

https://github.com/ashish168/step_02/

Thanks
Ashish Aggarwal
8587994099

**Comment by thisisjaymehta** [comment]
This issue dont look like it belong here.

**Comment by ashish168** [comment]
fixed , need to flutter configure correctly
