### ISSUE TITLE
package `webview_flutter_web` is unusable

### ISSUE THREAD

**Issue by moluopro** [flutter/flutter#131177]
This package is completely unusable and unmaintained for a long time: `webview_flutter_web`.  
Hopefully someone will continue to maintain it and make sure it stays in use.

**Comment by huycozy** [comment]
Hi @moluopro 
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly (See appropriate template [here](https://github.com/flutter/flutter/issues/new/choose))

>This package is completely unusable

Please provide more information on this.

**Comment by moluopro** [comment]
and this: `https://www.apple.com`

**Comment by stuartmorgan** [comment]
Please file a new issue [using the template](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=9_first_party_packages.yml), providing all of the requested information; without those details there's no way for us to investigate.
