### ISSUE TITLE
Problem in listview.builder with multiple widgets

### ISSUE THREAD

**Issue by abdelrahman-abied** [flutter/flutter#131197]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I have a list of items and based on a condition it should be displayed in Widget1() or Widget2(). It works fine up to there, the problem is when I get to the bottom of the list and want to scroll slowly up, the items rebuild and it jumps up and down the list.

Using the itemExent does solve the problem, but it's not the ideal solution. I need dynamic items.

Note: Widgets do not have a default size.

### Expected results

don't rebuild listview if it contain shripwrap while scrolling list items

### Actual results

rebuild listview if it contain shripwrap while scrolling list items

### Code sample

<details><summary>Code sample</summary>

```dart
ListView.builder(
      controller: scrollController,
      cacheExtent: 10000,
      addAutomaticKeepAlives: true,
      dragStartBehavior: DragStartBehavior.start,
      physics: AlwaysScrollableScrollPhysics(),
      //itemExtent: 450.0,
      itemBuilder: (context, index) {
        if (index < list.length)
          return MultiBlocProvider(
              providers: [
                /// some mandatory providers
              ],
              child: some condition
                  ? Widget1()
                  : Widget2());

        return loading();
      },
      itemCount: list.length
    );
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F770820d darwin-arm64,
    locale en-EG)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.80.1)
[✓] Connected device (3 available)
[✓] Network resources

```

</details>

**Comment by abdelrahman-abied** [comment]
> Hi @abdelrahman-abied Your sample code is currently incomplete and uses providers so I'm not sure if the internal logic inside may affect the issue.
> 
> In order to address the issue properly, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so that we may verify this.
> 
> Also, it would be appreciated if you could provide a recorded video/gif for the actual result as well. Thanks!

```
the same issue exists in case i don't use any state management package shrink wrap not working if listview.builder contain condition statement to build it's widget
  return ListView.builder(
      itemCount: items.length,
      itemBuilder: (BuildContext context, int index) {
        final item = items[index];
          ListTile(
          title: Text(item.title),
          subtitle: Text(item.subtitle),
        ),
        if (index != items.length - 1) Divider(),
      },
    );
```

**Comment by huycozy** [comment]
Your sample code above still is incomplete. You should provide a complete sample code that is in a runnable `main.dart` file. 

You can try my below sample code which is working well from my side:

<details>
<summary>Complete sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp(home: MyApp()));
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ListView.builder(
          itemCount: 100,
          itemBuilder: (context, index) {
            if (index % 2 == 0) return const Divider();
            return ListTile(
              title: Container(
                margin: const EdgeInsets.symmetric(vertical: 8),
                padding: const EdgeInsets.symmetric(vertical: 16, horizontal: 8),
                child: Text('Hello $index'),
              ),
              leading: const Icon(Icons.ac_unit),
              onTap: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(builder: (context) => const SecondRoute()),
                );
              },
            );
          },
        ),
      ),
    );
  }
}

class SecondRoute extends StatelessWidget {
  const SecondRoute({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Second Route'),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            Navigator.pop(context);
          },
          child: const Text('Go back!'),
        ),
      ),
    );
  }
}

```
</details>

**Comment by abdelrahman-abied** [comment]
> Your sample code above still is incomplete. You should provide a complete sample code that is in a runnable `main.dart` file.
> 
> You can try my below sample code which is working well from my side:
> 
> Complete sample code

in your example  if add shrink wrap property to list view it will calculate the size of listview straight forward but in my list view every item has different height with the same divider in my case shrink wrap did't work

**Comment by huycozy** [comment]
Please provide a reproduction code sample so we may verify the issue properly (not complex production code or using 3rd plugins/packages)

**Comment by abdelrahman-abied** [comment]
now i am using listview and map list of widget to prevent rebuild of listview.builder with dynamic height size
