### ISSUE TITLE
Offer a flutter reconnect to resident runner option

### ISSUE THREAD

**Issue by xster** [flutter/flutter#13113]
When a flutter debug app is running, there are many ways of losing the service connection to the device such as closing the terminal, unplugging the wire, having the app be in the background for too long etc. 

Would be nice to have a `flutter reconnect` command that recreates a resident runner with the currently connected devices with debug apps.

**Comment by kangwang1988** [comment]
We're also continuously met the Observatory connection never became ready issue.Finally, it's found that's a timeout issue.i.e., when you flutter run command has run over 10min,but the web socket for observatory is still empty, an error will trigger. This can often occurs when your dependencies resolving or building take long.

This logic is in flutter's intellj plugin.Visit https://github.com/flutter/flutter-intellij/blob/master/third_party/intellij-plugins-dart/src/com/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcessZ.java#L203 for more.
Maybe a reconnect a method would help us deal with this problem.

**Comment by xster** [comment]
cc @devoncarew

**Comment by devoncarew** [comment]
@kangwang1988, I'll file an issue over at the inteliij plugin repo to track the timeout issues.

**Comment by xster** [comment]
This is done in https://github.com/flutter/flutter/pull/18677
