### ISSUE TITLE
Xcode installation is incomplete; a full installation is necessary for iOS and macOS development. ???  How to solve？

### ISSUE THREAD

**Issue by zhaohongbo910** [flutter/flutter#131155]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

 flutter doctor -v                                                                                                                                                                 ✔  

```
17:56:01  ▓▒░
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4 22F66 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.10.6 on channel stable at /Users/zhaohb/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (11 days ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2021.2.1)
    • Android Studio at /Applications/IntelliJ IDEA.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.4 22F66 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.

```

### Expected results

I'm going crazy, why does this fuck problem still exist, I can't tell if this problem is a flutter problem or a MacOS xcode problem, who can give me an answer? This problem last year feedback, upgrade the computer system, also upgrade the flutter version, still exists, then ask how to check through it, hey, really disappointed in this thing.  Is that the problem with your attitude to the problems in the user's environment?  Please also take a look at this with the MacOS xcode team,

my email:  buding98k@gmail.com   

### Actual results

I'm going crazy, why does this stupid problem still exist, I can't tell if this problem is a flutter problem or a MacOS xcode problem, who can give me an answer? This problem last year feedback, upgrade the computer system, also upgrade the flutter version, still exists, then ask how to check through it, hey, really disappointed in this thing.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Flutter Doctor output

 flutter doctor -v                                                                                                                                                                 ✔  17:56:01  ▓▒░
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4 22F66 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.10.6 on channel stable at /Users/zhaohb/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (11 days ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2021.2.1)
    • Android Studio at /Applications/IntelliJ IDEA.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.4 22F66 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.

**Comment by darshankawar** [comment]
> I'm going crazy, why does this fuck problem still exist,

@zhaohongbo910 First of all, please don't use such words and I recommend you to go through [code of conduct](https://github.com/flutter/.github/blob/main/CODE_OF_CONDUCT.md#code-of-conduct).

Coming to your issue, I think it is similar to the one you [filed](https://github.com/flutter/flutter/issues/125359) before which got closed due to inactivity wherein, we asked [this](https://github.com/flutter/flutter/issues/125359#issuecomment-1519560839) to confirm but didn't get any response from you, so please confirm if you followed the steps mentioned in the log to see if it helps to resolve the issue or not.

**Comment by peternann** [comment]
I must admit, this message confused me too as a new iOS/Flutter developer.

"Yes, yes I have fully installed XCode. I just did it..."

"Ohhhh, you mean the definition of 'fully installed' is to also run those 2 magic commands."

It might be clearer if the first line said "... Plus steps listed below" or something like that.
For me, running those 2 commands did indeed make Doctor happy.

But yeah most people will figure it out before coming and posting a ranty issue.  😳

**Comment by zhaohongbo910** [comment]
I have found the problem, ai, because I have installed a virtual machine, resulting in the configuration of the export SYSTEM_VERSION_COMPAT=1 in the.bashrc. Please set this to false to include such export SYSTEM_VERSION_COMPAT=0 、Thank you very much、Thank you very much、Thank you very much
