### ISSUE TITLE
[in_app_purchase] voidedpurchases does not return all refunded orders

### ISSUE THREAD

**Issue by vodemn** [flutter/flutter#131195]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I've implemented iap handling in my app following this tutorial https://codelabs.developers.google.com/codelabs/flutter-in-app-purchases. But it says nothing about getting notified about non-consumable items refunds (RTDN are not fired for such events). So I've did some investigating and seems that the only way to be notified about such refunds is by calling Voided Purchases API.

1. Buy non-consumable in-app product
2. Refund it via Google Play Console and don't forget to remove entitlement
3. Fetch `voidedpurchases`

### Expected results

The last refunded non-consumable order is present in the `voidedpurchases` list.

### Actual results

The last refunded non-consumable order is not present in the `voidedpurchases` list.

### Code sample

<details><summary>Code sample</summary>

```dart
  Future<void> fetchVoidedPurchases() async {
    final voidedPurchases = await androidPublisher.purchases.voidedpurchases.list(
      androidPackageId,
      type: 0,
      maxResults: 1000,
    );
    voidedPurchsesPaginationToken = voidedPurchases.tokenPagination?.nextPageToken;
    final items = voidedPurchases.voidedPurchases;
    if (items != null) {
      for (var item in items) {
        print("google_play_${item.orderId}");
      }
    }
    print('------');
  }
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.4 22F66 darwin-arm64, locale en-BY)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.80.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by vodemn** [comment]
@darshankawar 
I'm using `in_app_purchase: 3.1.5` and couldn't find such code:
```dart
final QueryPurchaseDetailsResponse responsePast = await InAppPurchaseConnection.instance.queryPastPurchases();
```
Seems like these classes are no longer present in the recent iap plugin version.
Users in the comments to that issue suggest using Voided Purchases API. And it is what I did for my app. And the issue here is that this API just doesn't work as expected.

**Comment by vodemn** [comment]
I found out, that order from March was actually refunded in the last 30 days, so it should be in the voided list. But still, why are more recent refunds not there?

**Comment by darshankawar** [comment]
Thanks for the update. I am keeping this issue open and labeling for team's attention and input on voidedpurchases api and whether this is an issue with the plugin or not.

**Comment by stuartmorgan** [comment]
@mvanbeusekom When you get a chance can you see if this is another case of the issue being in the underlying data?

**Comment by vodemn** [comment]
Also maybe you can point out who is responsible for this guide https://codelabs.developers.google.com/codelabs/flutter-in-app-purchases?
There is noting said about acknowledging the purchases, but in order for voidedPurchases API to work correctly it is a necessary step to acknowledge a purchase.

**Comment by vodemn** [comment]
> Regarding the acknowledging of purchases, this is mentioned in the code lab at the bottom of step "8) Make purchases" where at the bottom it explains:

There is a separate method in AndroidPublisherV3, that acknowledges the purchase. So as I understood it should be called on the b/e side even if `completePurchase` was called on f/e side.

**Comment by mvanbeusekom** [comment]
Hi @vodemn, 

Did acknowledging the purchases on the server side solve the issue of being notified on the client side? Do you happen the have any links or documentation pointing to how to handle the server side acknowledgement?

This would help out so I can update the necessary documentation.

**Comment by vodemn** [comment]
@mvanbeusekom 
I've contacted Google's support and this was a part of the response (apart from Removing entitlement):

> Furthermore, it's possible that the orders were automatically refunded by the system due to failure in acknowledging these purchases in your app within the given window (as indicated [here](https://developer.android.com/google/play/billing/integrate#non-consumable-products)). The Voided purchase API does not intend to pull the refunded orders that were not acknowledged since they are not requested by the user.

and

> Yes, acknowledging the purchases is done via the backend.


So these answers are probably not applicable to this package because they are backend-related. But I think it would be great to provide a guide or a link to guide on how to setup your backend. Because the current code labs tutorial lacks handling of non-consumable products.

**Comment by stuartmorgan** [comment]
Closing as expected behavior given the above. Please file a new issue about the request for codelab changes with details about what you'd want included there.
