### ISSUE TITLE
[go_router]After flutter web intervened in go_router, the package body of main.dart.js increased by 400k

### ISSUE THREAD

**Issue by zjrwdl** [flutter/flutter#131186]
Before import go_route :

<img width="478" alt="image" src="https://github.com/flutter/flutter/assets/6874049/79f21611-ce3b-4447-95d1-fd986d65a810">
<img width="1065" alt="image" src="https://github.com/flutter/flutter/assets/6874049/ff26fc9d-045a-442b-8da1-177a348a5751">

After import go_route :
<img width="718" alt="image" src="https://github.com/flutter/flutter/assets/6874049/f702f16e-7728-465d-9f34-7be6174fede6">

<img width="462" alt="image" src="https://github.com/flutter/flutter/assets/6874049/176b72da-0cfb-4c14-b37c-d9eafec2e121">
<img width="1083" alt="image" src="https://github.com/flutter/flutter/assets/6874049/2f915a3d-c92b-4431-9c3d-e16ff3cbdd2f">

I think the package body increment is a bit large.

**Comment by huycozy** [comment]
Thanks for the report, @zjrwdl 
This is a known issue at https://github.com/flutter/flutter/issues/99105. I will close this issue in favor of that issue, so please follow up on it for updates. Based on the recent [comment](https://github.com/flutter/flutter/issues/99105#issuecomment-1589706861), it would be appreciated if you could provide a reproduction case there. Thanks!
