### ISSUE TITLE
Flutter Desktop app's debug build without Dart VM running, cannot be invoked by Google Chrome extension's Native Messaging

### ISSUE THREAD

**Issue by hpelitebook745G2** [flutter/flutter#131149]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Let `app_exec_file_path` = `/Users/<user>/Desktop/desktop_app/build/macos/Build/Products/Debug/desktop_app.app/Contents/MacOS/desktop_app`

If I double click my Flutter Desktop app's Unix executable file in `app_exec_file_path`, this is the flow:
1. It opens a terminal and starts a Dart VM
2. The desktop app opens

**Approach 1:**
The problem is, if I use `app_exec_file_path` as `path` in the Native Messaging host file like so:
    
    {
      "name": "com.test.desktop_app",
      "description": "Open Desktop app",
      "path": "/Users/<user>/Desktop/desktop_app/build/macos/Build/Products/Debug/test_desktop.app/Contents/MacOS/desktop_app",
      "type": "stdio",
      "allowed_origins": ["chrome-extension://<extension_id>/"]
    }
  
what happens is the following flow:
1. I click open my extension and press the button
2. It will open the Flutter Desktop app briefly but then closes right away

One thing I think is the reason, the extension only opens the desktop app's executable file directly without a Dart VM running.
_See the 1st log below for the errors..._

**Approach 2:**
So what I did was, I created a combination of workarounds and use either shell script or executable file but basically its content is:
    
    #!/bin/bash
    osascript -e 'tell app "Terminal" to do script "/Users/<user>/Desktop/desktop_app/build/macos/Build/Products/Debug/test_desktop.app/Contents/MacOS/desktop_app"'
    
This file is called `open_app` and is a Unix executable file. Essentially, the 2nd line is a 1 liner command line that does the following in order:
1. Opens a terminal first (this will serve as the Dart VM)
2. Open the Flutter Desktop app's executable file (make it stay running together with the Dart VM)

Now, going back to the manifest.json, I replaced the path of `open_app` so Native Messaging would now invoke the script I just created to open Dart VM then the Desktop app (hoping it won't close right after).
_See the 2nd log below for the errors..._

### Expected results

I have a Chrome extension that uses [runtime.connectNative](https://developer.chrome.com/docs/extensions/reference/runtime/#method-connectNative) and [runtime.sendMessage](https://developer.chrome.com/docs/extensions/reference/runtime/#method-sendMessage) to communicate to my Flutter Desktop app that should listen to any message from the extension.

The expected flow:
1. I click open my extension and press the button
2. It will open the Flutter Desktop app and see the received message in my logs

### Actual results

Flutter Desktop app crashes or closes right away if its debug build - Unix executable file is invoked using Chrome Native Messaging.

### To summarize:
**Approach 1:**
When I used the _debug build's Unix executable file of my Flutter Desktop app_ as `path` value inside the Native Messaging host file, it opens the Desktop app briefly then closes right away because there's no Dart VM opened. 

**Approach 2:**
When I used the _shell script or executable file I created_ as `path` value inside the Native Messaging host file, it doesn't open the Desktop app at all.

From the 2nd log error message, it seems that Native Messaging **can only open binary** and not just any executable file.

Makes me wonder what is the standard way of communication between Chrome extension and Flutter Desktop apps, how do they send message to the app or even just invoke its method?

Any opinion would be greatly helpful.

### Code sample

<details><summary>Native Messaging host file</summary>

```dart
  {
    "name": "com.test.desktop_app",
    "description": "Open Test Desktop",
    "path": "/Users/<user>/Desktop/desktop_app/open_app",
    "type": "stdio",
    "allowed_origins": ["chrome-extension://<extension_id>/"]
  }

```

</details>

<details><summary>Chrome extension's popup.js</summary>

```dart
  let btn = document.getElementById("my_app");

  btn.addEventListener("click", () => {
    port = chrome.runtime.connectNative("com.test.desktop_app");
    console.log("Test Desktop clicked");
  });

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### 1st log:
Also, since I enabled logging using the command:
`/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --enable-logging --v=1`

I tailed the logs inside Library/Application Support/Google/Chrome/chrome_debug.log. 
<details><summary>Here are the errors I got:</summary>

```console
"Test Desktop clicked", source: chrome-extension://<extension_id>/popup.js (33)
Native Messaging host tried sending a message that is 1953852518 bytes long.
"Unchecked runtime.lastError: Error when communicating with the native messaging host.", source: chrome-extension://<extension_id>/popup.html (0)
"Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.", source:  (0)
```

</details>
Which means the connection is interrupted as the Desktop app has just closed.

### 2nd log:
<details><summary>Here's the new error if I click the button in my extension:</summary>

```console
    "Test Desktop clicked", source: chrome-extension://<extension_id>/popup.js (33)
    Found manifest, but not the binary for native messaging host com.<user>.desktop_app. Host path specified in the manifest: /Users/<user>/Desktop/desktop_app/open_app
    "Unchecked runtime.lastError: Specified native messaging host not found.", source: chrome-extension://<extension_id>/popup.html (0)
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F770820d darwin-arm64, locale en-SG)
    • Flutter version 3.10.6 on channel stable at /Users/<user>/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (10 days ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/<user>/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/<user>/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.4.1 22F770820d darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 115.0.5790.102

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment]
> the extension only opens the desktop app's executable file directly without a Dart VM running.
> [...]
> 1. Opens a terminal first (this will serve as the Dart VM)

It is not clear what this means; Flutter applications do not run in an external VM, nor is Terminal a Dart VM.

According to [Chrome documentation](https://developer.chrome.com/docs/extensions/mv3/nativeMessaging/#native-messaging-debugging) a messaging host cannot log anything to stdout that doesn't conform to the protocol, which means that debug Flutter application cannot possibly be a valid target, due to the logging that it does.

> Makes me wonder what is the standard way of communication between Chrome extension and Flutter Desktop apps

I would not expect a GUI application, Fluter or otherwise, to be the standard target for a Chrome extension. I would recommend a forum for Chrome extension development in general for advice on how to make a non-GUI binary that does IPC communication with a GUI application, as that wouldn't involved anything Flutter-specific.

Closing as this is not a Flutter bug.

**Comment by hpelitebook745G2** [comment]
<img width="749" alt="Screenshot 2023-07-24 at 11 21 04 AM" src="https://github.com/flutter/flutter/assets/27658429/52e4a61e-e3ac-41bb-a509-b1da9b475ec0">
<img width="682" alt="Screenshot 2023-07-24 at 11 22 42 AM" src="https://github.com/flutter/flutter/assets/27658429/80a56d6a-2665-4ace-98b0-46ebd52038f3">

> It is not clear what this means; Flutter applications do not run in an external VM, nor is Terminal a Dart VM.

The 1st screenshot is from DEBUG CONSOLE tab from VS Code, while the 2nd screenshot is the terminal that opened when double clicking the debug executable file. This is what I meant as the terminal that serves as Dart VM.

> I would not expect a GUI application, Fluter or otherwise, to be the standard target for a Chrome extension.

How about use cases where Flutter is used to create a Chrome extension and a Desktop app and these 2 apps communicate to each other. For example, to be able to use extension further, it should open the Desktop app when not opened and invoke its authentication functionality? I just think it might come up sooner than we thought as Flutter targets different platforms.

Thanks for the suggestion also, will open a forum at Chromium issue filing: https://bugs.chromium.org/p/chromium/issues/wizard

**Comment by stuartmorgan** [comment]
> This is what I meant as the terminal that serves as Dart VM.

The terminal is showing you the `stdout` from the application, including the logging from the application about where the debug VM service within the application is listening for connections. It is not a VM.

> How about use cases where Flutter is used to create a Chrome extension and a Desktop app and these 2 apps communicate to each other. For example, to be able to use extension further, it should open the Desktop app when not opened and invoke its authentication functionality?

I would expect that to be mediated by a non-UI binary that is specifically designed to conform to the requirements of the Chrome native messaging protocol, and which in turn communicates with the (in this case Flutter) GUI application through some mechanism other than `stdin`/`stdout`, as I described above.

> Thanks [stuartmorgan](https://github.com/stuartmorgan) for the suggestion also, will open a forum at Chromium issue filing: https://bugs.chromium.org/p/chromium/issues/wizard

I don't see any evidence of a Chromium bug here; my suggestion was to find a forum for asking questions about Chrome extension development to get advise about communicating with an application from an extension.
