### ISSUE TITLE
[CP] Avoid crash when backdrop filter is null for PlatformViews

### ISSUE THREAD

**Issue by iassal** [flutter/flutter#131228]
### Issue Link

https://github.com/flutter/flutter/issues/127095

### Commit Hash

01bb6af

### Target

stable

### PR Link

https://github.com/flutter/engine/pull/43982

### Changelog Description

Avoid crash when a null backdrop filter is applied to PlatformView

### Impacted Users

Flutter devs, end-customers

### Impact Description

App crash

### Workaround

No

### Risk

low

### Test Coverage

yes

### Validation Steps

Use the sample code in https://github.com/flutter/flutter/issues/127095#issuecomment-1592872318 to reproduce the crash and validate the fix.

**Comment by iassal** [comment]
@cyanglaz

**Comment by CaseyHillers** [comment]
Marking "cp: approved" on behalf of @cyanglaz as the PR was approved.

**Comment by iassal** [comment]
Any updates here?

**Comment by zanderso** [comment]
@CaseyHillers Can this be closed? It looks like it landed on the branch.

**Comment by blueeyestw** [comment]
3.10.7 doesn't exist on stable channel. Is this fix included in 3.13 ?

**Comment by artemsorochan** [comment]
> > Shipped in 3.10.7. To get it, you'll need to run `git fetch --tags && checkout 3.10.7` in your current flutter checkout.
> 
> 3.10.7 doesn't exist on stable channel. Is this fix included in 3.13 ?

@CaseyHillers we have the same question, we really need this fix. Thanks in advance!

**Comment by CaseyHillers** [comment]
> @CaseyHillers we have the same question, we really need this fix. Thanks in advance!

Yes, the fix is also on 3.13.

**Comment by sang-makebetter** [comment]
I still have the same crash after upgrading to 3.13 😢 
In my case, when I try to open a video dialog (openDialog with [Chewie](https://pub.dev/packages/chewie)), then the crash happens...

```
    thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)

 frame #0: 0x0000000105bb932c Flutter`flutter::IOSExternalViewEmbedder::CompositeEmbeddedView(long long) + 1828

Flutter`flutter::IOSExternalViewEmbedder::CompositeEmbeddedView:

-> 0x105bb932c <+1828>: ldr x8, [x0]

 0x105bb9330 <+1832>: ldr x8, [x8, #0x30]

 0x105bb9334 <+1836>: blr x8

 0x105bb9338 <+1840>: cbz x0, 0x105bb951c ; <+2324>

Target 0: (Runner) stopped.
```

**Comment by cyanglaz** [comment]
@sang-makebetter This is likely a different issue. Could you open a new issue tickets with details? Thank you!
