### ISSUE TITLE
☂️ Google Maps package improvements

### ISSUE THREAD

**Issue by leighajarett** [flutter/flutter#131284]
This umbrella issue is to track the individual features that are part of the ongoing work to improve the Flutter / Dart Google Maps offering:

- [x] https://github.com/flutter/flutter/issues/26863
- [x] https://github.com/flutter/flutter/issues/34657
- [x] https://github.com/flutter/flutter/issues/67631
- [ ] https://github.com/flutter/flutter/issues/78512
- [ ] Routes package

**Comment by stuartmorgan** [comment]
@mit-mit Is this still useful to track as an umbrella issue? Most of the work it was tracking is complete.

**Comment by mit-mit** [comment]
No, don't think this is needed anymore, closing

**Comment by stuartmorgan** [comment]
See https://github.com/flutter/flutter/issues/156608 for the latest version.
