### ISSUE TITLE
textCapitalization option for SearchBar

### ISSUE THREAD

**Issue by jamesncl** [flutter/flutter#131260]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Using the new material 3 [SearchBar](https://api.flutter.dev/flutter/material/SearchBar-class.html), it would be nice to be able to pass in the [TextCapitalization](https://api.flutter.dev/flutter/services/TextCapitalization.html) to use in the TextField.

For example, if I have a SearchBar where the user can search a list of things, **or create one if it doesn't exist in the list**, sometimes I want those new things to begin with a capital letter as default without the user having to manually use shift to capitalize the first letter. Currently this is not possible.

### Proposal

Currently this is what happens by default when you type into SearchBar without manually using shift to capitalize the first letter:

![image](https://github.com/flutter/flutter/assets/15979056/8c874858-69e6-444c-8a34-b4389332a02e)

To allow this to default to "New thing", it's a really easy addition: allow passing in a [TextCapitalization](https://api.flutter.dev/flutter/services/TextCapitalization.html) property:
```
SearchBar(
   hintText: "Search or create",
   onChanged: widget.onChanged,
   textCapitalization: TextCapitalization.sentences,
)
```
And apply this to [the TextField in SearchBar](https://github.com/flutter/flutter/blob/c8b9b15e4cd14de5ba46fafb476ac198da63fea5/packages/flutter/lib/src/material/search_anchor.dart#L1255):

```
                      TextField(
                        ...
                        // ADD THIS:
                        textCapitalization: widget.textCapitalization,
                      )
```

**Comment by HansMuller** [comment]
CC @QuncCccccc - this sounds like a reasonable proposal
