### ISSUE TITLE
Oversized ExpansionTile trailing arrow

### ISSUE THREAD

**Issue by TheNightmanCodeth** [flutter/flutter#13129]
## Steps to Reproduce

Create ExpansionTile ListView

## Logs

Nothing unusual in logs

## Flutter Doctor

[✓] Flutter (on Linux, locale en_US.UTF-8, channel alpha)
    • Flutter at /home/joe/Documents/Projects/flutter
    • Framework revision e8aa40eddd (5 weeks ago), 2017-10-17 15:42:40 -0700
    • Engine revision 7c4142808c
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at /home/joe/Android/Sdk
    • Platform android-27, build-tools 27.0.1
    • Java binary at: /home/joe/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at /home/joe/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Connected devices
    • SAMSUNG SM G920A • 04157df48188622a • android-arm • Android 7.0 (API 24)

Here's a screenshot:

![screenshot](https://user-images.githubusercontent.com/6336819/33096003-841f2858-ced3-11e7-85db-568c4321a979.png)

As you can see, the down arrow is far too large. Has anyone experienced anything like this before? I simply followed along with the ListView example in the examples

**Comment by Hixie** [comment]
Do you have the code that caused that? That's crazy!

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
