### ISSUE TITLE
Firebase Codelab: broken link to FirebaseAnimatedList

### ISSUE THREAD

**Issue by jfbibeau** [flutter/flutter#13120]
## Steps to Reproduce

* Navigate to the Firebase Codelab (https://codelabs.developers.google.com/codelabs/flutter-firebase/#8), specifically the `9. Enable data syncing` -> `Use an AnimatedList` section
* Click on the link to check out the FirebaseAnimatedList dart code in the sentence: "Start by replacing the ListView widget in the ChatScreenState class with a new `FirebaseAnimatedList` widget, as shown."
* Link broken!

Actual link:
https://github.com/flutter/firebase_database/blob/master/lib/ui/firebase_animated_list.dart

Should (probably) be:
https://github.com/flutter/plugins/blob/master/packages/firebase_database/lib/ui/firebase_animated_list.dart

**Comment by Hixie** [comment]
Looks like the codelab has changed a lot since then.
