### ISSUE TITLE
Image picker extended to videos in gallery or even files

### ISSUE THREAD

**Issue by abbadabbatech** [flutter/flutter#13124]
Was not sure where to put feature request for image_picker plugin.

Any chance to be able to select videos that are in the same gallery as images? Seems this would serve the same purpose in many scenarios.

Also a way to be able to go into documents and choose a file would be a great feature to have.

Thanks

**Comment by abbadabbatech** [comment]
Just wondered if there was a thought as to when someone might work on this, I have been trying some things for iOS and have the picking and camera option working, but can not get it to display back into the flutter app, so hoping this might have a schedule for features.

**Comment by Hixie** [comment]
This isn't on our current priority list, but we would accept patches if you are interested in trying to submit one.

**Comment by chazhenry** [comment]
Such a fundamental requirement. I was evaluating Flutter, but issues like these tell me it's not ready for prime time. You shouldn't have to lose a day or two to develop your own video picker.

**Comment by ride4sun** [comment]
Somebody mentioned to use the Android Media Picker for Android and the equivalent IOS (not sure what that is). Flutter could provide just a thin wrapper which shows the platforms implementation which is much better what is available in flutter and it stays up to date.

**Comment by AppleEducate** [comment]
This definitely needs to include videos. This is a common use case and when using the native cameras we should be able to specify video as an option. 

OR there needs to be a image_picker, video_picker and media_picker plugin for each use case.

Has anyone made a plugin yet that can handle video?

**Comment by abbadabbatech** [comment]
I have modified the current one to handle video for iOS and Java, picking and capture.

**Comment by AppleEducate** [comment]
@abbadabbatech I completed a pull request and merged to image_picker she support of picking and capturing videos. I did it for iOS and Android.

**Comment by abbadabbatech** [comment]
@AppleEducate I guess its not released yet, may look at using it once its released instead of the one I did.  Thanks

**Comment by AppleEducate** [comment]
@abbadabbatech I also did this plugin as well. 
https://github.com/AppleEducate/media_picker

**Comment by zoechi** [comment]
I'd prefer a list of media files with previews and hints if they are video, audio, or pictures (like in a file manager)
without the need to chose the media type in advance.

**Comment by satish754ss** [comment]
I want to save Imgapicker image in my folder,

**Comment by NightkingCH** [comment]
I'm currently developing an app where users can choose wheter they want to capture a new image / video or want to upload an existing media. It would be great if the user could choose any media within the gallery / picker. Like in this cordova plugin [https://github.com/apache/cordova-plugin-camera#cameramediatype--enum](url).

My quick look at the plugins source could would suggest to add a new delegate without a media filter as seen here :

[https://github.com/flutter/plugins/blob/2908b42a5c8c0ed1e0026e7a6a9989fc4acaacb1/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerDelegate.java#L260](url)

So that developers could call explicitly "pickImage", "pickVideo", "pickMedia".

**Comment by zoechi** [comment]
@NightkingCH did you check pub.dartlang.org? There might be plugin packages with these features.

**Comment by AppleEducate** [comment]
Use ImagePicker.pickVideo()

**Comment by Allan-Nava** [comment]
@AppleEducate Thank you!

**Comment by cyanglaz** [comment]
@abbadabbatech Is `ImagePicker.pickVideo` helpful to your issue?

**Comment by abbadabbatech** [comment]
It did finally do what was needed, there is still some weirdness with
aspect ratio, but I worked through that.

**Comment by cyanglaz** [comment]
@abbadabbatech Sounds good! Thank you. I am closing this issue.
