### ISSUE TITLE
Text with markups for easier styling

### ISSUE THREAD

**Issue by Fernandomr88** [flutter/flutter#131255]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Sometimes we're writing something like 

"This is the place where you can **change** your password. Etc etc etc etc" 

and all we want is to make one single word bold like the example. We can't do that today without changing our widget to TextSpan and creating a lot more code and stuff. 

### Proposal

So I would like to suggest a feature to make it easier to write text with different styles other than TextSpan.

My suggestion is that we can use the same markups we use here in git `"**text**"` `"_text_"` for bold/italic text.
so the previous example in flutter would be much easier to implement.

**Comment by moffatman** [comment]
Text markup is out of scope of flutter, there are a lot of great packages to handle it. And every solution will end with TextSpan usage, as it's the only way to have a paragraph of text where different parts have different styling.

**Comment by dam-ease** [comment]
Thanks for your input @moffatman. @Fernandomr88 As I suggested, you can make use of https://pub.dev/packages/flutter_markdown which is a first-party flutter package and per https://github.com/flutter/flutter/issues/131255#issuecomment-1650033295, Text markup is out of scope of flutter. Closing this issue based on these.
