### ISSUE TITLE
Scrollbar "current character" show

### ISSUE THREAD

**Issue by FMorschel** [flutter/flutter#131276]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

When #52207 is completed, `Scrollbar` would always know the right size of the scrolling content (except on infinite scroll, but that's another thing entirely, I believe).

Could then this be an entrance for an option to highlight the first character for the current first item on screen? Like when you scroll in [Google Contacts](https://contacts.google.com/) the first letter appears at the side of the Scrollbar to help the user in a big list to find something easier.

### Proposal

I propose an API where `Scrollbar` gives you the current `index` of the list so that we could return a character (or maybe a widget?) to show in a popup that follows the `Scrollbar` for helping users navigate big lists.

**Comment by darshankawar** [comment]
Thanks for the report @FMorschel 
Are you looking for a toast message or something similar that'll show current index or page out of total ? If so, have you already checked https://pub.dev/packages/scroll_to_index and possibly https://stackoverflow.com/a/63511502 to see if it helps in your case ?

**Comment by FMorschel** [comment]
Hi! Actually no, I was thinking more like this on the right that follows the trackbar:

https://github.com/flutter/flutter/assets/52160996/8bd80441-07c8-48c8-ae78-4c7f4c9b5469

**Comment by darshankawar** [comment]
Thanks for the update. Treating this as a potential proposal to add the requested feature for scrollbar api.

**Comment by darshankawar** [comment]
Revisiting this issue and I have feeling that there might be community package already which could be offering the feature, for example: check https://pub.dev/packages/azlistview and see if it helps to achieve your use case.

**Comment by FMorschel** [comment]
I'll try it out this weekend and relay my thoughts to you!

**Comment by Piinks** [comment]
This one may also provide the requested feature: https://pub.dev/packages/draggable_scrollbar

We're probably unlikely to implement this in the framework. The scrollbar does not know about the content of the scrolling widget, so the user would probably have to provide label information through a new API.

**Comment by FMorschel** [comment]
Thanks, Piinks! The [draggable_scrollbar](https://pub.dev/packages/draggable_scrollbar) is mostly what I was looking for! 

I see what you mean. Thanks for helping me anyway! We could then close this if you agree.

**Comment by Piinks** [comment]
>  We could then close this if you agree.

Thanks for the update @FMorschel. I will close this then.
