### ISSUE TITLE
[gen-l10n] use in a monorepo

### ISSUE THREAD

**Issue by felipeassis97** [flutter/flutter#131250]
I have a monorepo project with some packages:
**main_module, profile_module, card_module and design_system_module.**
I want to make each module have its own language files (.arb). I see it as a way to decouple the modules and make them more independent.
I didn't find anything in the documentation about it.
I found some approaches using adding a new package for the translations (translate_package), but I didn't really like the idea, because I would have to centralize all the texts of all the modules in one place.

This is my l10n.yaml file:

> arb-dir: lib/l10n
template-arb-file: app_es.arb
output-localization-file: app_localizations.dart
use-escaping: true
synthetic-package: false

This is my App widget:

>   Widget build(BuildContext context) {
    return MaterialApp.router(
      debugShowCheckedModeBanner: false,
      localizationsDelegates: const [
        AppLocalizations.delegate,
        CountryLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      supportedLocales: const [
        Locale('en'),
        Locale('es'),
      ],
      locale: const Locale('en'),
      theme: LightTheme.themeData,
      darkTheme: DarkTheme.themeData,
      themeMode: ThemeMode.light,
      routerConfig: _router,
    );
  }
  
  I'm trying to retrieve the texts from:
 > Text(AppLocalizations.of(context)!.helloWorld),
 
 Does anyone know how to resolve?

**Comment by dam-ease** [comment]
Hi @felipeassis97. Thanks for filing this issue. Can you provide more information on the issue you are facing with your current implementation (I assume you are having errors with the code implementation you have now and you'd like to resolve)? If yes, kindly provide all or some of the information indicated in the template so that we can address this issue properly.
More specifically, please provide the information indicated below:

- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of flutter doctor -v
- Reproduction steps

Thank you.

**Comment by felipeassis97** [comment]
**A completed and minimal reproducible code sample:** [https://github.com/felipeassis97/i18n-flutter/tree/monorepo](repositorie)

**The output of flutter doctor -v:**  

> [✓] Flutter (Channel stable, 3.10.5, on macOS 13.0.1 22A400 darwin-x64, locale en-BR)
    • Flutter version 3.10.5 on channel stable at /Users/felipe.assis/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (6 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

> [!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/felipe.assis/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

> [✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.12.1

> [✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

> [✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

> [✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

> [✓] Connected device (3 available)
    • iPhone 8 (mobile) • F4EFA3E9-92F8-4ABB-A81A-EFCFEBBDA4C7 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • macOS (desktop)   • macos                                • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)      • chrome                               • web-javascript • Google Chrome 115.0.5790.102

> [✓] Network resources
    • All expected network resources are available.

**Reproduction steps:**
Clone the repository at the link above and make the texts inserted in the .arb files of each of the modules available in the application.

In the current implementation, when running a flutter gen-l10n, it is generated only from the main module, as it only has the l10n.yaml file

If I add the file in other modules, it will be generated correctly, however when trying to retrieve a text from the context in other modules (as described in the documentation) in this format AppLocalizations.of(context)!.helloWorld, null is returned.
I identified that this happens because the localizationsDelegates imported in the MaterialApp is only from the main_module, so the context only offers it in the delegates class of the main_module.

I did other tests as well, like adding synthetic-package as false in the l10n.yaml file of the modules and manually importing the classes, which also didn't work

**Comment by maRci002** [comment]
Use the command line tool with the `--no-synthetic-package` flag so that the localization `.dart` files will be generated inside the modules. For example, here's how you might use command tool #123553
