### ISSUE TITLE
Support for Deferred Components on the desktop

### ISSUE THREAD

**Issue by arcticfox1919** [flutter/flutter#131202]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I'd like to see the [Deferred components](https://github.com/flutter/flutter/wiki/Deferred-Components) feature supported on the Flutter desktop as well.

### Proposal

I believe [Deferred components](https://github.com/flutter/flutter/wiki/Deferred-Components) is a very practical feature. Is there any consideration to extend this feature to desktop platforms? Unlike mobile platforms, desktop platforms have no restrictions on loading dynamic libraries. If we can implement Deferred components on desktop, it would enable hot updates and hot fixes for Flutter programs. By splitting and packaging a program into different dynamic libraries, issues could be resolved just by remotely replacing the relevant dynamic libraries.

![](https://raw.githubusercontent.com/flutter/engine/master/docs/deferred_components_architecture.svg)

**Comment by jonahwilliams** [comment]
Deferred components ***can not*** be used to implement code push like functionality. Deferred components are only a means of splitting up a single compilation into multiple artifacts. These pieces cannot be swapped out for different builds.

We have no current plants to offer code push functionality in the Flutter SDK.

**Comment by gspencergoog** [comment]
Even with deferred components on Android, we don't support what you're looking for.  In the page for Deferred Components it says:

> Though modules can be defer loaded, the entire application must be completely built and uploaded as a single Android App Bundle. Dispatching partial updates without re-uploading new Android App Bundles for the entire application is not supported.

So, even if we implemented it, I don't think it's what you're looking for.

Since things like requests for code push and hot updates are already captured in other issues, we're going to close this issue. (Desktop Triage)
