### ISSUE TITLE
`InAppPurchaseAndroidPlatformAddition` does not have the `launchPriceChangeConfirmationFlow` method as specified in the `README` of the package

### ISSUE THREAD

**Issue by OlegNezv** [flutter/flutter#131248]
### Is there an existing issue for this?

- [X] I have searched the [existing package issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Apackage)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### What package does this bug report belong to?

in_app_purchase

### What target platforms are you seeing this bug on?

Android

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
[Paste file content here]
```

</details>

### Steps to reproduce

I would like to implement the flow to handle subscription price changes on Android.

As specified in the [README](https://pub.dev/packages/in_app_purchase#confirming-subscription-price-changes) of the package we should use the `launchPriceChangeConfirmationFlow` method, but it's not defined in the `InAppPurchaseAndroidPlatformAddition` class

### Expected results

The documentation should probably be updated to describe how to handle the subscription price changes for Android

### Actual results

``

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Videos

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by dam-ease** [comment]
Hi @OlegNezv. Thanks for filing this issue. Can you explain further on what you mean by it's not defined in the InAppPurchaseAndroidPlatformAddition class. From the `InAppPurchaseAndroidPlatformAddition` class documentation, we have:

> /// Initiates a flow to confirm the change of price for an item subscribed by the user.
  ///
  /// When the price of a user subscribed item has changed, launch this flow to take users to
  /// a screen with price change information. User can confirm the new price or cancel the flow.
  ///
  /// The skuDetails needs to have already been fetched in a
  /// [InAppPurchaseAndroidPlatform.queryProductDetails] call.
  Future<BillingResultWrapper> launchPriceChangeConfirmationFlow(
      {required String sku}) {
    return _billingClient.launchPriceChangeConfirmationFlow(sku: sku);
  }

Can also confirm you are on the latest version of the `in_app_purchase` package: `in_app_purchase: ^3.1.7`?

**Comment by dam-ease** [comment]
Hi @OlegNezv. Thanks for your patience and for attaching this. I can see the issue you described now on my end. I'll label this as a proposal to change the documentation since a change has been made. Thank you!

**Comment by stuartmorgan** [comment]
@mvanbeusekom This looks like missed docs updates from the recent API migration.

**Comment by stuartmorgan** [comment]
Fixed in https://github.com/flutter/packages/pull/4643

**Comment by jbryanh** [comment]
Please update in changelog on flutter.dev on next release

**Comment by stuartmorgan** [comment]
> Maybe please update in changelog with more info regarding this on flutter.dev on next release

I'm not sure what page on flutter.dev you are referring to; please file a new issue with details if there are outdated pages on the Flutter website.

> I don't understand why such minimal information is always passed

I'm not sure what you are referring to when you say "always passed". The breaking change was described in the CHANGELOG when it was made, and the README update has details about the flow. If there's something that still hasn't been updated we'll need specific details.
