### ISSUE TITLE
A visual glitch appears when I use multiple instances of a CustomPaint

### ISSUE THREAD

**Issue by rxlabz** [flutter/flutter#13125]
I'm trying to "stress test" the rendering performance of a little "painted" animation. When I display only  a single instance of this animation, everything is fine, 

![www_rxlabz_com_labz_glitches_mov](https://user-images.githubusercontent.com/1397248/33068395-6fef154a-ceb1-11e7-9231-3ae0fea31a22.png)

but if I duplicate it, some visual glitches appear.

![www_rxlabz_com_labz_glitches_mov](https://user-images.githubusercontent.com/1397248/33068352-408c5b5a-ceb1-11e7-93b7-29ced84f5e85.png)

Here's a record showing the problem : http://www.rxlabz.com/labz/glitches.mov

Most of the time the glitch appears at the end of animation during the check mark drawing, but it changes sometimes 

![boite_de_reception__2 669 messages__814_non_lus_](https://user-images.githubusercontent.com/1397248/33068762-93177db8-ceb2-11e7-9006-4ab729ad7635.png)

video2 : http://www.rxlabz.com/labz/glitches_2.mov

Some more informations : 
- Everything is drawn with a drawPath instruction
- I use a stateful widget which uses an animation controller to know when to send the new drawing commands to it's CustomPaint child 
- this problem appears in release mode, on iOS and android
- sometimes, after few seconds everything is back to normal on each instance, sometimes not.

Any idea on how I can try to prevent/avoid this ?

## Flutter Doctor
```
[✓] Flutter (on Mac OS X 10.12.6 16G1036, locale fr-FR, channel master)
    • Flutter at /Users/rxlabz/dev/tools/flutter
    • Framework revision 928d2cc764 (3 days ago), 2017-11-17 15:45:27 -0800
    • Engine revision 4733e33737
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/rxlabz/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.0, Build version 9A235
    • ios-deploy 1.9.2
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.3 EAP)
    • Flutter plugin version 19.1
    • Dart plugin version 172.3317.48

[✓] Connected devices
    • A3 A40   • 622004271815                             • android-arm • Android 6.0 (API 23)
    • iPhone 8 • 3550BDC4-7E32-43DB-BBB3-3A8B4D7254D9     • ios         • iOS 11.0 (simulator)
```

**Comment by eseidelGoogle** [comment]
There was a bad regression in Skia for a couple days that could have been related.  Can you re-test on `master`?

**Comment by rxlabz** [comment]
I upgraded Flutter and tried both master and alpha channel, same symptoms :(

**Comment by sethladd** [comment]
Thanks for the feedback! Is there a way to share the code?

**Comment by rxlabz** [comment]
sure : https://github.com/rxlabz/glitch_report

**Comment by rxlabz** [comment]
@sethladd maybe it can help : I've just pushed a new version of the code ( same painting and symptoms, but this time with more [readable drawing commands](https://github.com/rxlabz/glitch_report/blob/master/lib/decoded_render.dart) )

**Comment by rxlabz** [comment]
I also notice that there is no glitch if draw only the border of the shapes ( PaintStyle.stroke ).

**Comment by rxlabz** [comment]
@eseidelGoogle @sethladd I have some doubts, and maybe you can help me to see clearer. This animation is generated from a plugin that I started for Adobe AnimateCC (aka FlashCC ). I was pretty excited cause that seemed a reasonable alternative to [Lottie](https://airbnb.design/lottie/) ( which I tried to port to Flutter but stopped cause it would be way too much work for me ) and thought about sharing it... But this glitch make me wonder if "frame-by-frame painted animations" are a good idea in Flutter ? from your perspective, from a performance angle, does it seems to you a "viable" => "sharable" way to animate UI elements ? ( on my iOS devices performances showed in the performance overlay are very good, on my old Android it's less impressive, but more than acceptable with a reasonable number of animated item ) 
Do you have any opinion/advice on this question?

**Comment by zoechi** [comment]
I can not reproduce in Android (can't currently build for iOS).

```
[✓] Flutter (Channel master, v1.1.5-pre.37, on Mac OS X 10.14.1 18B75, locale en-AT)
```
I assume this was fixed.
