### ISSUE TITLE
Google map circle is not a perfect circle

### ISSUE THREAD

**Issue by karthikk9828** [flutter/flutter#131330]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Use google_maps_flutter to render a google map with a circle in flutter web

### Expected results

A perfect circle should be rendered on the google map

### Actual results

Circle is not perfect

### Code sample

<details><summary>Code sample</summary>

```dart
class Map extends StatelessWidget {
  const Map({super.key});

  @override
  Widget build(BuildContext context) {
    return GoogleMap(
      circles: {
       const Circle(
          circleId:  CircleId('test'),
          center:  LatLng(23.77, 134.484),
          radius: 100,
          strokeWidth: 2,
        )
      },
      initialCameraPosition: const CameraPosition(
        target: LatLng(23.77, 134.484),
      ),
      zoomControlsEnabled: false,
      scrollGesturesEnabled: false,
      onMapCreated: (controller) {},
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

<img width="254" alt="image" src="https://github.com/flutter/flutter/assets/44114533/941c336e-f7e3-492b-903f-0bc9c685fd60">

</details>

### Logs

<details><summary>Logs</summary>

```console

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.4 22F66 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[!] Android Studio (version 2022.2)
    ✗ Unable to find bundled Java version.
[✓] IntelliJ IDEA Community Edition (version 2022.2.1)
[✓] VS Code (version 1.80.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

</details>

**Comment by stuartmorgan** [comment]
The circle is drawn by Google Maps; the plugin just passes it information like the center and radius. Issues with the actual rendering would need to be reported to Google Maps.
