### ISSUE TITLE
Error in Widgets codelab

### ISSUE THREAD

**Issue by Kaih1825** [flutter/flutter#131375]
There is an mistake in the document found at https://codelabs.developers.google.com/flutter-home-screen-widgets#3. As far as I know, the minimum update interval for android:updatePeriodMillis is 30 minutes, which is 1800000 ms. However, the document shows that it can be set to 1000 ms, which is 1 second, to facilitate testing.
 Thank you.
 (In the 'Update the Android code' section of the 'Update Home Screen widget configuration').

**Comment by danagbemava-nc** [comment]
Thanks for pointing this out, I see the same thing in the documentation. https://developer.android.com/develop/ui/views/appwidgets/advanced#periodic

cc @domesticmouse

**Comment by domesticmouse** [comment]
PTAL @ericwindmill

**Comment by Kaih1825** [comment]
Thank you for all your assistance.

**Comment by domesticmouse** [comment]
I believe this is now fixed
