### ISSUE TITLE
[Impeller] Faster DrawVertices/DrawAtlas via subpass elimination.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#131345]
## Background

Compared to the Skia backend, drawVertices and drawAtlas in Impeller are much slower. Generally the reason for this is that in cases where blending is required Impeller will blend using offscreen textures.

For example:

* drawVertices + per vertex colors + tiled image color source. We create an offscreen to draw the tiled image color source + vertex data, a second offscreen for the per vertex color + vertex data, and then blend them together into the parent pass.
* drawAtlas + per atlas color, same story.

These APIs aren't heavily used by applications, but are used by games and game-like apps, and by frameworks such as flame.

Historically we discussed subpass elimination for these APIs by proposing specific shaders for drawAtlas/drawVertices (see google only link go/impeller-draw-atlas-vertices ). This was discarded as creating too many shader variants, and so I implemented them with subpasses. Of course, this has lead to other visual fidelity bugs: 

* https://github.com/flutter/flutter/issues/121723
* https://github.com/flutter/flutter/issues/118914
* https://github.com/flutter/flutter/issues/119958

## Overview

We can modify the existing blend shaders in order to support blending with per-vertex colors rather than a uniform color value. This will have minor to little impact on rendering cost, but by allowing the vertex colors to vary then we can express all of drawAtlas/drawVertices blending with them.

These shaders include:
   * All advanced blend shaders (non framebuffer fetch)
   * porter-diff blend.

drawVertices + gradient blending will remain a slow case, as we would need to render the gradient to an offscreen in order to have a texture to sample. But texture sampling cases should work as is.

There was an open question as to whether we should attempt https://github.com/flutter/flutter/issues/116168 first and use different vertex layouts to make the encoding faster for the blend case versus the drawAtlas/drawVertices case. However since then we've learned a bit more about Vulkan specifically:

* PSO variants have much more overhead compared to metal, so changing layout isn't immediately a win
* Additional offscreen textures are much more expensive compared to upload time. So reducing the subpass count is more important than packing the bytes effectively.
* There are more caveats with shader performance on Vulkan. For example, loading uniform fragment data via vertex shader varyings may actually be faster in some cases, which is the opposite of what we expected.

Given these, I think we should proceed with modifying the blend shaders so that the blend color is specified per vertex.

**Comment by jonahwilliams** [comment]
The cost of drawVertices/drawAtlas today be demonstrated with a fairly simple benchmark application. I don't know if we should actually put this on CI though:


![image](https://github.com/flutter/flutter/assets/8975114/d6d25883-94cf-47e3-8061-02f0bae2cde5)


```dart
import 'dart:async';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

Future<ui.Image> loadImageFromAsset(String assetName) async {
  var buffer = await ImmutableBuffer.fromAsset(assetName);
  var codec = await ui.instantiateImageCodecFromBuffer(buffer);
  var frame = await codec.getNextFrame();
  return frame.image;
}

late ui.Image assetImage;

void main() async {
  assetImage = await loadImageFromAsset('assets/dash.jpg');
  runApp(MaterialApp(
    home: Scaffold(
      body: ListView(
        children: [
          for (var i = 0; i < 100; i++)
            CustomPaint(
              painter: FooPainter(),
              size: Size(400, 50),
            )
        ],
      )
    ),
  ));
}


class FooPainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    var vertices = ui.Vertices(
      VertexMode.triangles,
      [
        Offset.zero,
        Offset(0, 250),
        Offset(250, 0),
        Offset(0, 250),
        Offset(250, 0),
        Offset(250, 250)
      ],
      textureCoordinates: [
        Offset.zero,
        Offset(0, assetImage.height.toDouble()),
        Offset(assetImage.width.toDouble(), 0),
        Offset(0, assetImage.height.toDouble()),
        Offset(assetImage.width.toDouble(), 0),
        Offset(assetImage.width.toDouble(),  assetImage.height.toDouble())
      ],
      colors: [
        Colors.red,
        Colors.blue,
        Colors.green,
        Colors.red,
        Colors.blue,
        Colors.green,
      ].map((x) => x.withAlpha(100)).toList()
    );
    canvas.drawVertices(vertices, BlendMode.colorDodge, Paint()..shader = ImageShader(assetImage, TileMode.clamp, TileMode.clamp, Matrix4.identity().storage));
    canvas.translate(250, 0);
    canvas.drawVertices(vertices, BlendMode.colorDodge, Paint()..shader = ImageShader(assetImage, TileMode.clamp, TileMode.clamp, Matrix4.identity().storage));
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) {
    return true;
  }
}


```

**Comment by jonahwilliams** [comment]
Example project: https://github.com/jonahwilliams/draw_vertices_example

**Comment by jonahwilliams** [comment]
And a draw atlas example: 

https://screenshot.googleplex.com/72UMMKK6yGK2TLF

```dart
import 'dart:async';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

Future<ui.Image> loadImageFromAsset(String assetName) async {
  var buffer = await ImmutableBuffer.fromAsset(assetName);
  var codec = await ui.instantiateImageCodecFromBuffer(buffer);
  var frame = await codec.getNextFrame();
  return frame.image;
}

late ui.Image assetImage;

void main() async {
  assetImage = await loadImageFromAsset('assets/dash.jpg');
  runApp(MaterialApp(
    home: Scaffold(
      body: ListView(
        children: [
          for (var i = 0; i < 100; i++)
            CustomPaint(
              painter: FooPainter(),
              size: Size(400, 50),
            )
        ],
      )
    ),
  ));
}


class FooPainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    canvas.drawAtlas(assetImage, [
      RSTransform.fromComponents(rotation: 0, scale: 1, anchorX: 0, anchorY: 0, translateX: 0, translateY: 0),
      RSTransform.fromComponents(rotation: 0, scale: 1, anchorX: 0, anchorY: 0, translateX: 250, translateY: 0)
    ], [
      Rect.fromLTWH(0, 0, assetImage.width.toDouble(), assetImage.height.toDouble()),
      Rect.fromLTWH(0, 0, assetImage.width.toDouble(), assetImage.height.toDouble()),
    ], [
      Colors.red.withAlpha(100),
      Colors.blue.withAlpha(100),
    ], BlendMode.dstOver, null, Paint()..color = Colors.black.withAlpha(120));
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) {
    return true;
  }
}

```

**Comment by jonahwilliams** [comment]
One caveat is that the blend shaders and drawVertices/drawAtlas reverse src/dst for the color, making this a bit tricky.

**Comment by jonahwilliams** [comment]
Preliminary results from a drawAtlas update: https://flutter-flutter-perf.skia.org/e/?queries=sub_result%3D90th_percentile_frame_rasterizer_time_millis%26sub_result%3D99th_percentile_frame_rasterizer_time_millis%26sub_result%3Daverage_frame_rasterizer_time_millis%26sub_result%3Dworst_frame_rasterizer_time_millis%26test%3Ddraw_atlas_perf__timeline_summary%26test%3Ddraw_atlas_perf_ios__timeline_summary%26test%3Ddraw_atlas_perf_opengles__timeline_summary&selected=commit%3D36339%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DSM-G973U1%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253Daverage_frame_rasterizer_time_millis%252Ctest%253Ddraw_atlas_perf__timeline_summary%252C

**Comment by jonahwilliams** [comment]
Putting this on hold while I work on higher priority issues.

**Comment by JaffaKetchup** [comment]
> These APIs aren't heavily used by applications, but are used by games and game-like apps, and by frameworks such as flame.

We're planning to implement `drawVertices` into flutter_map to improve the speed of polygon rendering. There's a PR open for this at fleaflet/flutter_map#1800. 

---

I've done some testing on Flutter 3.19.0-0.1.pre, using a Redmi Note 10 Pro (with Vulkan). Ignore the top slider. The left switch controls whether `drawVertices` is used, and the right switch controls whether the outlines of the polygons are thick (more than a hairline). That isn't necessarily important here, but I've included it for completion and as a comparison.

### With Skia

307ms/53ms | 434ms/51ms | 342ms/40ms | 490ms/42ms 
:-------------------------:|:-------------------------:|:-------------------------:|:------------------:
![skia_perf_thin](https://github.com/flutter/flutter/assets/58115698/6185389a-5833-4d68-88bc-cd6ec3fe608d)  |  ![skia_perf_thick](https://github.com/flutter/flutter/assets/58115698/ebb75819-cb4b-4171-8257-3b9d3ccbb4ee) | ![skia_std_thin](https://github.com/flutter/flutter/assets/58115698/9e58fbb0-d86f-4530-8cf1-e5410e8b0784) | ![skia_std_thick](https://github.com/flutter/flutter/assets/58115698/a01b6c5d-afcb-466e-94d9-0c5a4737b476)

### With Impeller

105ms/59ms | 107ms/56ms | ⠀91ms/41ms | ⠀99ms/43ms  ⠀
:-------------------------:|:-------------------------:|:-------------------------:|:------------------:
![impeller_perf_thin](https://github.com/flutter/flutter/assets/58115698/8820b594-47e3-4b80-947b-277370b82547)  |  ![impeller_perf_thick](https://github.com/flutter/flutter/assets/58115698/26939ce5-7080-41e1-82f3-f033f6545a70) | ![impeller_std_thin](https://github.com/flutter/flutter/assets/58115698/aa543483-bec1-4d13-87af-ca07b160f4d9) | ![impeller_std_thick](https://github.com/flutter/flutter/assets/58115698/54867a09-447d-4eda-8005-ef418140cbf8)

### Conclusion

With Skia, enabling DV decreased the raster times by 10%, and decreased overall times by 6% (because the triangulation algorithm runs on the build thread) - on some other devices, such as my Windows machine with Gen 12 i7-12700H and RTX 3070, the improvement on the raster thread has been as high as 50%. However, with Impeller, enabling DV **increased** the raster time by 15%. Additionally, and maybe it's coincidence, but it also seemed to increase the build time.

**Comment by jonahwilliams** [comment]
Hey @JaffaKetchup , I'd love to dig into this a bit and profile this myself. Can I checkout the example at https://github.com/fleaflet/flutter_map/pull/1800/files and run it myself?

I would note that depending on what version of flutter you are on, the Impeller Vulkan backend is still lagging behind skia performance a bit.

**Comment by JaffaKetchup** [comment]
> Can I checkout the example at [fleaflet/flutter_map#1800 (files)](https://github.com/fleaflet/flutter_map/pull/1800/files) and run it myself?

Sure, you'll need to clone the entire repo though (the example depends on it). Then just head over to the Polygon Stress Test page. The slider at the top is for simplification, probably best to keep it 0, or constant. Also note that zooming will change the number of points (as simplification strength changes over different zoom levels), and so performance will also vary over zoom.

> Impeller Vulkan backend is still lagging behind skia performance a bit.

I thought Vulkan was the recommended backend? (Also, not 100% sure my device is Vulkan supported, but I'm pretty sure it is).

**Comment by jonahwilliams** [comment]
Impeller on Android is still in early preview.

**Comment by JaffaKetchup** [comment]
Yeah, I realised. Unfortunately I have no iOS device to test on.

**Comment by jonahwilliams** [comment]
Medium term, yes we definitely want it to be faster. The initial goal is visual fidelity and removal of shader compilation jank. Skia is quite a well written backend, so being faster than it is challenging, but I think we can do it 😄 .

I appreciate the example here, as these APIs aren't heavily used in the applicaitons we test on it can be hard to gauge how well they are working.

**Comment by JaffaKetchup** [comment]
It seems to already be faster, just not quiteee fast enough :D. Just for reference, the source GeoJson has about 138k points. Ideally we want it to render in 60fps, but there's not a whole lot more we can do after this, so really hoping Impeller picks up the rest! At the moment, it is pretty much 60fps on my computer, but nowhere near on a phone. Of course, I realise that that is quite a demand.
The reason I included the thick outlines was because I noticed Impeller seemed to handle that much better.

**Comment by jonahwilliams** [comment]
I took a profile on a Pixel 7 / Impeller/ near tip of tree. The vast, vast majority of the workload appears to be in construction of the outlines:

* StrokePathGeometry::GetPositionBuffer - path tessellation
* SimplifyOrDrawPath - converting Skia path to Impeller Path
* Dtors - destroying converted paths.

I don't think the performance difference is due to drawVertices, instead this is probably a good example of us needing to make stroked paths faster


![image](https://github.com/flutter/flutter/assets/8975114/0405e668-ec20-4847-8fdd-be44b822b38b)

**Comment by JaffaKetchup** [comment]
From my testing, Impeller was slower using `drawVertices`! Outlines are definitely the biggest factor when thick, but when hairline, they seem to be alright.
Out of interest, what's the device pixel ratio of your screen? If it's more than one, then the outline will never be hairline.

**Comment by jonahwilliams** [comment]
Oh I only mean from this profile, drawVertices isn't close to the largest contributor to CPU time. In aggregate, I agree it could make a difference, especially as I did not do a comparison to Skia.

This is on a Pixel which is 2.6.

**Comment by jonahwilliams** [comment]
Perhaps I am not using the right settings/branch? I checked out origin/polygon-draw-vertices

**Comment by JaffaKetchup** [comment]
That should be the correct one.
Maybe try removing the border altogether? Not the easiest to explain how to do that, but in the geojson loader, remove the ternary, and replace with 0.

**Comment by jonahwilliams** [comment]
I would recommend trying closer to tip of tree and seeing if these results reproduce in a profile build. I did some more profiling and in all cases I could find drawVertices takes up a miniscule % of overall CPU time. The biggest cost is polyline generation for strokes.

**Comment by jonahwilliams** [comment]
From looking at the profile, a lot of the overhead on both the Skia and Impeller side are the number of operations. You'll likely be able to improve performance just by batching up some of the calls to drawPath (i.e. use multi-contour paths) and drawVertices.

**Comment by jonahwilliams** [comment]
Using this:

```
diff --git a/lib/src/layer/polygon_layer/painter.dart b/lib/src/layer/polygon_layer/painter.dart
index 98ae24c..62f86cf 100644
--- a/lib/src/layer/polygon_layer/painter.dart
+++ b/lib/src/layer/polygon_layer/painter.dart
@@ -78,7 +78,7 @@ class _PolygonPainter extends CustomPainter {
 
       // Draw polygon outline
       if (polygon.borderStrokeWidth > 0) {
-        canvas.drawPath(borderPath, _getBorderPaint(polygon));
+       // canvas.drawPath(borderPath, _getBorderPaint(polygon));
       }
```

If I turn off outlines, I get 9ms frame times on a Pixel 7.

**Comment by JaffaKetchup** [comment]
Interesting. Ok, I'll test with the master channel (unless there's a way I can target the same commit as you were using?).

I wonder if some of the difference is due to the phones specs. Mines fairly budget, a Pixel 7 is a massive step up.

**Comment by jonahwilliams** [comment]
Generally things get faster proportionally though, I would be surprised if the stroke generation code got faster on a lower spec phone.

Something else to consider:
* These polygon strokes have round caps and joins, these are the most expensive. Changing to StrokeCap.square / StrokeJoin.miter will be slightly faster.
* You drawing 4204 individual paths. At that volume of draws, actually just allocation + deallocating the objects used to draw are taking up ~2/3 of frame time. If I remove the check for hash properties, frame time drops to 16ms raster / 11ms paint even in debug mode. Making more of an effort to batch individual paths will have more of an effect than anything else you can do.

**Comment by jonahwilliams** [comment]
You might need separate logic for batching the outlines vs fills, for example. The renderHashCode includes holePointsList / disableHolesBorder which don't seem to impact the outline?

**Comment by JaffaKetchup** [comment]
> especially as I did not do a comparison to Skia.

I would recommend doing this. My initial post was about how `drawVertices` is actually slower with Impeller (whereas it is faster with Skia), which fits the original purpose of this issue.
 
> Compared to the Skia backend, drawVertices and drawAtlas in Impeller are much slower.

I would say it is not 'much' slower - it is actually negatively impacting performance.

---

This is just a thought I had quickly, maybe it's worthless, I'm not an expert when it comes to this, but I noticed in #127273 you mention that you rely on libtess in more complex triangulation. We're using a [Dart port](https://github.com/JaffaKetchup/dart_earcut) of the [mapbox/earcut](https://github.com/mapbox/earcut) library. Whilst there are some bugs with the Earcut algortithm, there is an open fix available for one, and I think with some minor investment into the [C++ port](https://github.com/mapbox/earcut.hpp) (or creation of a new pure C one), Earcut could be a viable and faster alternative to trianugulation of simple/non-self-intersecting polygons than libtess. Mapbox added a performance comparison to their repo, although it does compare times presumably in JS: https://github.com/mapbox/earcut#why-another-triangulation-library. It is MUCH faster than libtess in all cases, but of course, isn't perfect. I just wondered whether other options had been explored.

---

We'll certainly look into more batching of outlines.

> (i.e. use multi-contour paths)

Can you explain a little more what you mean by "multi-contour paths"?

Also just wanted to say a huge thanks for being supportive here! It might be worth keeping an eye on how Impeller affects FM, as a couple of Impeller issues have been spotted through FM so far :)

**Comment by jonahwilliams** [comment]
FWIW there is no tessellation in the case of drawVertices, its just a memcpy. Though there has been some work on it in the last few months that is not on the current stable, mostly around batching up the allocations it makes to be more efficient. There is still more overhead we can remove, which is tracked here:  https://github.com/flutter/flutter/issues/142054

The slow path is on stroke tessellation. This doesn't need a general purpose segmentation algorithm, so we don't use libtess. it just needs more efficient allocation. If you break down the allocation time, something like 90% of the time is spent on generating the stroke joins and allocating the polyline. The polyline is generated by computing derivatives of the various cubic/quadradic curves and then inserting joins/caps.

![image](https://github.com/flutter/flutter/assets/8975114/d6caca75-b563-45d2-9826-35ad7e82fb1a)


Re: multi contour.

If you have two strokes with the same or similar properties and you don't care so much about the exact intersections, you can do them in the same path. Example:

```
var path1 = Path()
  ..lineTo(1, 2)
  ..lineTo(3, 4);
  
var path2 = Paint()
  ..lineTo(5, 6)
  ..lineTo(7, 8);
 
 canvas.drawPath(path1, Paint())
 canvas.drawPath(path2, Paint())
```

vs

```
var path = Path()
  ..lineTo(1, 2)
  ..lineTo(3, 4)
  ..close()
  ..lineTo(5, 6)
  ..lineTo(7, 8);
  
   canvas.drawPath(path, Paint())
```

This will look approximately the same, modulo cases where it overlaps with opactiy. but at 4200 paths vs a handful will be a massive performance difference

**Comment by JaffaKetchup** [comment]
I see, makes sense. At the moment, we're actually using `addPolygon` instead of `lineTo`. Is there a particular advantage to either one? `addPolygon` is an external method from what I can see, so that would suggest there's a specific implementation for it?

(
> FWIW there is no tessellation in the case of drawVertices

Yeah, I realised, that's what we're doing. I was just thinking generally.
)

**Comment by JaffaKetchup** [comment]
Got it. So we're drawing on every polygon, whereas we want to batch until afterward where possible (bearing in mind overlaps). (Probably should've realised that a while ago - wonder if there's a reason we didn't considering we've done a lot of batching anyway.) Thanks :)

(I also noticed that `drawVertices` doesn't seem to get anti-aliasing as a filled path does? I'm assuming that's intentional, but never noticed that before.)

**Comment by jonahwilliams** [comment]
drawVertices does not get anti aliasing in Skia. drawVertices will be anti-aliased in Impeller since we're relying on hardware MSAA.

**Comment by jonahwilliams** [comment]
Also the overlaps don't really matter if you're drawing a solid color and/or the overlaps are small and not visually significant. Computing potential overlaps isn't really worth it, but with that number of polygons I think it would be reasonable to prioritize performance over small visual differences.

**Comment by jonahwilliams** [comment]
Actually one caveat to MSAA on draw vertices is that is skipped in impeller for non-porterduff blend modes, but fixing this issue would fix that

**Comment by jonahwilliams** [comment]
there is always money in the banana stand

**Comment by JaffaKetchup** [comment]
That's a new one xD
