### ISSUE TITLE
[CP] [iOS] Only dispose view when it is removed from the composition order

### ISSUE THREAD

**Issue by iassal** [flutter/flutter#131331]
### Issue Link

https://github.com/flutter/flutter/issues/125223

### Commit Hash

d6bc5c5

### Target

stable

### PR Link

https://github.com/flutter/engine/pull/44035

### Changelog Description

[platform_view] [iOS] Only dispose view when it is removed from the composition order

### Impacted Users

Flutter devs, end-customers

### Impact Description

App crashes randomly when PlatformView is disposed while still in the composition order.

### Workaround

No

### Risk

low

### Test Coverage

yes

**Comment by iassal** [comment]
@cyanglaz

**Comment by iassal** [comment]
@CaseyHillers Is there any pending action from my side to include this in the next hotfix? Thanks!

**Comment by itsjustkevin** [comment]
> @CaseyHillers Is there any pending action from my side to include this in the next hotfix? Thanks!

Nope, your cherry-pick has boarded the release train.

**Comment by choim4389** [comment]
When will a hotfix addressing this issue be released?

**Comment by itsjustkevin** [comment]
> When will a hotfix addressing this issue be released?

It will be available with the next release.

**Comment by iassal** [comment]
Hello,

When can we expect the next release. I understand that there's a weekly hot-fix release as per https://github.com/flutter/flutter/wiki/Release-process#hot-fixing-releases

The reason I am pinging is that this is causing a high crash rate in our production app.

Thanks.

**Comment by cyanglaz** [comment]
@XilaiZhang Should we create a CP to beta instead?

**Comment by XilaiZhang** [comment]
yeah trying to focus on beta hotfix at the moment, would this need a cp to beta?

(will probably let someone else take over the stable hotfix)

**Comment by iassal** [comment]
Can we get an eta on the stable release? We have 8% crash rate in an app over 100k active users

**Comment by itsjustkevin** [comment]
This cherry-pick request has not been forgotten, we will continue working toward getting a new hotfix out.  Thank you for your patience.

**Comment by choim4389** [comment]
Our app have high crash rate(about 8%, over 50k active users) too, so I want this hotfix released as soon as possible.

**Comment by itsjustkevin** [comment]
While we wait on the next beta release, please try the beta channel.

**Comment by iassal** [comment]
Any updates here?

**Comment by zanderso** [comment]
@CaseyHillers Can this be closed? It looks like the linked PR landed on the branch?

**Comment by CaseyHillers** [comment]
> @CaseyHillers Can this be closed? It looks like the linked PR landed on the branch?

No, we never pushed the stable channel due to infra issues. We're waiting for the next stable for this to arrive.
