### ISSUE TITLE
SystemChrome.setPreferredOrientations works only after a short switchover

### ISSUE THREAD

**Issue by desmeit** [flutter/flutter#131396]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I added the following code to my main file:

```
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  // Portrait Modus
  await SystemChrome.setPreferredOrientations(
    [
      DeviceOrientation.portraitUp,
    ],
  );
```
The portrait mode only works after it has switched once. If I move from portrait to landscape it goes to landscape and jumps back briefly afterwards and then stays in portrait mode. it's the same on simulator or real device.
To recreate the behavior, I need to restart the app.

In Xcode I have this:

![Bildschirmfoto 2023-07-27 um 11 55 36](https://github.com/flutter/flutter/assets/9454529/647524f6-47a6-46d3-a20c-c88cf08d644f)

I cannot turn off the landscape modes because I want to allow landscape mode on individual pages.

https://github.com/flutter/flutter/assets/9454529/3d7b486b-04e2-413c-bb60-a4930d256d19

### Expected results

It should stay in portrait mode from the beginning.

### Actual results

The portrait mode only works after turning once.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.9, on macOS 12.6 21G115 darwin-arm64, locale de-DE)
    • Flutter version 3.7.9 on channel stable at /Users/XXX/development/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 62bd79521d (4 months ago), 2023-03-30 10:59:36 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/XXX/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/XXX/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/XXX/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (4 available)
    • SM J530F (mobile)      • 52034239f4dca4ed                     • android-arm    • Android 9 (API 28)
    • iPhone 14 Pro (mobile) • 2F34815C-796B-45FB-9FD8-FEE88312AF59 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 115.0.5790.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by dam-ease** [comment]
Hi @desmeit. Thanks for filing this issue. I am unable to reproduce this on the latest version of Flutter. It works fine without the switch over. I see you are on an older version of flutter. Can you upgrade to the latest versions to confirm this issue still persists?

**Comment by desmeit** [comment]
@dam-ease sorry, you are right. The issue is gone if I update to 3.10.6.
