### ISSUE TITLE
DropdownButton fills it's parent, but children don't expand

### ISSUE THREAD

**Issue by jpgilchrist** [flutter/flutter#13135]
I read an existing issue (#4949) where the developer wanted the opposite behavior. He wanted the the underline to shrink; where as I would like the contents of the result to expand and force the dropdown arrow button to the right. 

I was actually able to make it work by changing the underlying code to use a `ConstrainedBox` instead of a `SizedBox`. However, that does not work for all scenarios due to various flex restrictions. 

<img width="355" alt="image" src="https://user-images.githubusercontent.com/5065660/33101600-d8704c8a-cee6-11e7-830c-fd6c2172edb2.png">

I guess I'm asking if
1. this is possible today and there's something I'm missing; or
2. could an expand option be added to the DropdownButton and it would use something other than a `SizedBox` (`ConstrainedBox` is probably not right) in order to fill the remaining space?

**Update:** I used my brain a bit more and found a simpler solution to expand the `SizedBox`. Simply set it's width to `double.INFINITY` (taking some cues from `SizedBox.expand` constructor). I don't want to override this since it seems like that would be a lot of work, but if expand was passed into DropdownButton as:

```dart
new DropdownButton<String>(items: ..., value: ..., expand: true)
```

then the SizedBox could have a width of null or infinity based on the value of expand...

```dart
new SizedBox(
  height: widget.isDense ? _denseButtonHeight : null,
  width: widget.expand ? double.INFINITY : null,
  ...
)
```

## Steps to Reproduce

<img width="424" alt="image" src="https://user-images.githubusercontent.com/5065660/33101055-bcdeeb2c-cee4-11e7-8ba4-e6466cc9ac65.png">

```dart
new Container(
  child: new Row(
    children: <Widget>[
      new Expanded(
        child: new Container(
          child: new DropdownButton<String>(
              isDense: true,
              value: 'one',
              items: <DropdownMenuItem<String>>[
                new DropdownMenuItem(
                    child: new Container(
                      child: new Row(
                        mainAxisSize: MainAxisSize.max,
                        children: <Widget>[
                          new Text('one')
                        ],
                      ),
                    ),
                    value: 'one'),
                new DropdownMenuItem(child: new Text('two'), value: 'two'),
                new DropdownMenuItem(child: new Text('three'), value: 'three')
              ],
              onChanged: null),
        )
      )
    ],
  ),
)
```

## Logs

no useful `flutter run` logs

Analyzing /Users/jpgilchrist/Development/github/veoci-mobile...
  lint • Name non-constant identifiers using lowerCamelCase at lib/utils/veoci_api.dart:15:16 • non_constant_identifier_names
  hint • This method overrides a method annotated as @mustCallSuper in 'State', but does not invoke the overridden method at lib/components/my_rooms/my_rooms_component.dart:143:8 • must_call_super
  hint • Unused import at lib/components/private_chat/private_chat_component.dart:2:8 • unused_import
  hint • Unused import at lib/config/route_handlers.dart:3:8 • unused_import
4 issues found.
(Ran in 6.5s)

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.13.1 17B48, locale en-US, channel alpha)
    • Flutter at /Users/jpgilchrist/Development/github/flutter
    • Framework revision e8aa40eddd (5 weeks ago), 2017-10-17 15:42:40 -0700
    • Engine revision 7c4142808c
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at /Users/jpgilchrist/Library/Android/sdk
    • Platform android-27, build-tools 27.0.1
    • ANDROID_HOME = /Users/jpgilchrist/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.1, Build version 9B55
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.6)
    • Flutter plugin version 19.1
    • Dart plugin version 172.4343.25

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 8.1.0 (API 27) (emulator)
    • iPhone X                  • 44914EA5-A848-49F9-9A6D-E1E196D58E4A • ios         • iOS 11.1 (simulator)

**Comment by zoechi** [comment]
@HansMuller

**Comment by jpgilchrist** [comment]
@kinnariarastu I just stumbled into a work around. Just add a hint widget to the `DropdownButton`

```dart
DropdownButton<num>(
  value: state.value,
  hint: Text("Select"),
  items: <DropdownMenuItem<num>>[
    DropdownMenuItem<num>(
      child: Text("1"),
      value: 1,
    ),
    DropdownMenuItem<num>(
      child: Text("2"),
      value: 2,
    ),
    DropdownMenuItem<num>(
      child: Text("3"),
      value: 3,
    )
  ],
  onChanged: (num value) {
    state.didChange(value);
  });
```

**Comment by allandaleho** [comment]
I actually have a fix for it, i will try to fork and contribute. But basically if you look at DropdownButtonState, the IndexedStack should be wrapped in Expanded widget.

I will create a PR today, though I don't know how long will Flutter team approve my fix. If you guys need more info on how to do a temporary fix I can share them here.

**Comment by allandaleho** [comment]
Already made a PR!

**Comment by DhytoDev** [comment]
I have the same issues. So, I tried to make a custom dropdown. Actually this solution is the same as that written by Allandaleho above. Hopefully the following code can help you.

[](https://gist.github.com/DhytoDev/cdadf2e78bd694192c65b5634c2ad53e)

**Comment by TurkiWalid** [comment]
Try  
`isExpanded: true`

**Comment by ricardolopezmobiledev** [comment]
> Try
> `isExpanded: true`

works for me! thks!!!
