### ISSUE TITLE
Broken link on Codelab "Your first Flutter app"

### ISSUE THREAD

**Issue by Primer81** [flutter/flutter#131300]
# Preface

The codelab found here: https://codelabs.developers.google.com/codelabs/flutter-codelab-first#0 says to report issues to this repository according to the link in the bottom left:
![image](https://github.com/flutter/flutter/assets/12836905/6e786c7c-51cd-4636-882d-a6a08a937349)

Sorry if this seems out of place - let me know if there is someplace better to report this.

# Issue

The issue is simply that the link on the final step of the codelab for the "advanced version" of the app does not seem to be correct. I don't see any relevant code there.

Here is a screenshot with the broken link highlighted:
![image](https://github.com/flutter/flutter/assets/12836905/91a3b72a-7196-41d7-b8dc-287b5aac0034)

Here is the destination of that link: https://dartpad.dev/e7076b40fb17a0fa899f9f7a154a02e8

I know that the link is likely broken because, in the following, timestamped, video, it shows that it should directly link to all the "advanced" code: https://youtu.be/8sAyPDLorek?t=5355

Whereas I only see the following:
![image](https://github.com/flutter/flutter/assets/12836905/dab47169-9f68-4ae3-b8ce-7acd25cf30a4)

**Comment by danagbemava-nc** [comment]
cc @domesticmouse

**Comment by domesticmouse** [comment]
PTAL @filiph

**Comment by filiph** [comment]
Thanks! That URL (https://dartpad.dev/e7076b40fb17a0fa899f9f7a154a02e8) worked but I recently found out that it's safer to have https://dartpad.dev/?id=e7076b40fb17a0fa899f9f7a154a02e8. 

I have updated the codelab doc. @domesticmouse, I always forget: should I do anything else or will the codelab rebuild automatically? Also, was it wrong to use links such as `dartpad.dev/<somehash>`? I know this worked fine in the past, and now I worry I have other links elsewhere in that format.

**Comment by domesticmouse** [comment]
@johnpryan to answer the question on DartPad links.

As to publishing the updated codelab, I'll do it as soon as I've converted all your animated gifs to YouTube videos. Long story, don't ask.

**Comment by filiph** [comment]
> I'll do it as soon as I've converted all your animated gifs to YouTube videos. Long story, don't ask.

😳

**Comment by Primer81** [comment]
> Thanks! That URL (https://dartpad.dev/e7076b40fb17a0fa899f9f7a154a02e8) worked but I recently found out that it's safer to have https://dartpad.dev/?id=e7076b40fb17a0fa899f9f7a154a02e8.

The safer link seems to work for me! Thanks for sharing that one 😊

**Comment by pooransuthar** [comment]
> Thanks! That URL (https://dartpad.dev/e7076b40fb17a0fa899f9f7a154a02e8) worked but I recently found out that it's safer to have https://dartpad.dev/?id=e7076b40fb17a0fa899f9f7a154a02e8.
> 
> I have updated the codelab doc. @domesticmouse, I always forget: should I do anything else or will the codelab rebuild automatically? Also, was it wrong to use links such as `dartpad.dev/<somehash>`? I know this worked fine in the past, and now I worry I have other links elsewhere in that format.

Hey, thanks for this, worked for me!

**Comment by domesticmouse** [comment]
Fix in flight.

Googlers: cl/560902614

**Comment by domesticmouse** [comment]
Fix landed
