### ISSUE TITLE
Document direct CocoaPods in native code more

### ISSUE THREAD

**Issue by xster** [flutter/flutter#13130]
Currently, our optimized flow involves using cocoapods transiently by consuming entire plugins that includes dart and their corresponding native code. 

There will be edge cases where the user doesn't use any plugins and just writes custom native iOS code and just want to bring in another custom native iOS cocoapod dependency (unrelated to flutter). Document that in that case, they'd have to follow standard iOS development patterns and create a Podfile and run pod install manually.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2086](https://github.com/flutter/website/issues/2086) via [**ZenHub**](https://www.zenhub.com/)
