### ISSUE TITLE
TextFormField or TextField onchanged event not fired for specific scenario

### ISSUE THREAD

**Issue by selvam920** [flutter/flutter#131312]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. type some word like "test"
2. select all 
3. press backspace
4. check onchanged event 

### Expected results

should be fire onchage event

### Actual results

did not fire onchange event

### Code sample

TextField(
 onChanged: (str) {
}}

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Flutter 3.10.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f468f3366c (13 days ago) • 2023-07-12 15:19:05 -0700
Engine • revision cdbeda788a
Tools • Dart 3.0.6 • DevTools 2.23.1

**Comment by huycozy** [comment]
Can you please share the complete sample code? I checked this with below code but it works as expected. Verifying this on Android platform.

```console
I/flutter (13022): t
I/flutter (13022): te
I/flutter (13022): tes
I/flutter (13022): test
I/flutter (13022):
```

<details>
<summary>Complete sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: TextField(
            onChanged: (value) {
              print(value);
            },
          ),
        ),
      ),
    );
  }
}

```
</details>

Also, which platform are you seeing that issue?

**Comment by selvam920** [comment]
it' working as expected
