### ISSUE TITLE
Optimize "flutter update-packages"

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#1313]
Our builds take 8-10 mins now. 2 minutes of that is running pub via `./dev/update_packages.dart`:

```
Ran "pub get" 19 times in 125880 ms
```

We could optimize this by reading all the pubspecs for the examples and packages projects, unifying the info, writing out a synthetic pubspec in a temp dir, running pub on that, and then creating `pubspec.lock` and `.packages` files for each project. It would probably drop the time from ~125s to 10-15s. We might also need to create a `packages/` symlink dir in each project as some of our tooling depends on looking into `packages/ske_engine` and possibly other package dirs.

**Comment by abarth** [comment]
We should probably just switch to .packages files.  There's a bug on file for that.

**Comment by eseidelGoogle** [comment]
It's 10x faster when it's run with a warm pub cache.  But for whatever reason my attempts to get Travis to cache our pub cache have failed:
https://github.com/flutter/flutter/blob/master/.travis.yml

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/flutter/pull/922 was when I added these logs in my last attempt at optimizing this.

**Comment by a14n** [comment]
see also the discussion on #929

**Comment by eseidelGoogle** [comment]
update_packages.dart now accounts for 50% !!!?! of all time spent on our Mac builder:
https://build.chromium.org/p/client.flutter/stats/Mac
and 25% of time spent on our Linux builder:
https://build.chromium.org/p/client.flutter/stats/Linux

**Comment by Hixie** [comment]
@kevmoo Are you aware of this issue? Is there a better way for us to update 20+ packages at once?

**Comment by kevmoo** [comment]
> Are you aware of this issue?

Aware that it's good to cache pub-cache? Yes.

> Is there a better way for us to update 20+ packages at once?

I could imagine a script – I have some bits of something you could start with – ping me on gchat/hangouts

**Comment by Hixie** [comment]
@kevmoo and I talked about this. Conclusion: There's no supported way to do this for free, but we could fake it either by propagating the .lock files from the first package we update to the next, or by making a joint pubspec.yaml and running pub on that then back-propagating the data to all the actual packages manually.

Since this isn't a critical blocker for the team these days I'm just going to close it. We can fix it when someone gets annoyed enough with it...

**Comment by eseidelGoogle** [comment]
FWIW, my understanding from our travis output is that this step accounts for 2 minutes of our 5 minute total runtime on Travis and is our longest-single step:
https://travis-ci.org/flutter/flutter/jobs/258663743#L656

**Comment by Hixie** [comment]
It's a bit misleading. Our longest time on that PR is actually shard 2, the tests on linux, which takes 17 minutes, the breakdown of which is 7 minutes for flutter_tools test (some of which is itself spent doing `pub get`s), 2 minutes doing the ~1500 "flutter test" tests, and yeah, about 2 minutes spent doing `pub get` at the start (the other 6 minutes are spread around all the other testing we do).
