### ISSUE TITLE
Identify the best concurrency mode for our Datastore applications

### ISSUE THREAD

**Issue by ricardoamador** [flutter/flutter#131366]
We recently encountered an issue with the scheduler where tasks were not being updated correctly: https://github.com/flutter/flutter/issues/131192

Through this investigation it was found that we may not be using the correct concurrency mode for our needs when it comes to Datastore. We are currently using `Optimistic With Entity Groups` though we might be able to benefit from a switch to either 'Optimistic' or 'Pessimistic' since we do not fully log the Entity Group for a duration of time through the read and write of the entity. 

One of these methods may be better suited for us.

https://cloud.google.com/datastore/docs/concepts/transactions

Some good information provided by Travis Cheung:

```
The official "guidance" :
PESSIMISTIC is ideal for server-side applications where latency is minimal
OPTIMISTIC is ideal for clients where latency could be unpredictable, and may keep a "transaction" open for a
long time (and so this mode doesn't end up locking things up on the server side).  This is a more typical use
case for Firestore in Native mode, and rather rare for Firestore in Datastore mode
```

**Comment by keyonghan** [comment]
Closing as obsolete (being migrated to firestore).
