### ISSUE TITLE
please improve "context.push" function to change domain of url for next version

### ISSUE THREAD

**Issue by ItdaTeam** [flutter/flutter#131384]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

when I use context.push , It only changed url domain for go router 7.1.x subversion 

I hope to improment context.push function , next version.

### Proposal

Please improve the function below on "go router".

"context.push" Please make sure that url can be changed in the technique of stacking with push page stack.

Reason:
In the case of the web, it is common to copy the url domain and use it to various SNS, but I understand that it is not applied to the 10.x version.

Of course, I know that the function works in the 7.1.1 subversion, but I want to use the go router continuously in the future, and I think that function is really an essential function, so I decided that I can't use only the 7.1.1 version in the future

I would like to ask you to improve the function.

"context.push" is because I think it will give a lot of efficiency to develop pc view, mobile view web, etc. 

For this and that reason, when we improve the next version, we'll make a desperate context.push I hope the page URL will be changed in domain url within the context.push function.

p.s Thank you for providing such a good go router

**Comment by darshankawar** [comment]
@ItdaTeam 
Check [this](https://github.com/flutter/flutter/issues/131083) issue and underlying comments and see if it resembles your case and helps in your case or not.

**Comment by ItdaTeam** [comment]
thank you for your comment, 

first of all. I already send you why I need to improve context.push.. 

also , I checked what you mentioned , 

I need to have stack page and show the URL domain on the browser. 
( I do not delete stack page by replacement push. ) 

becuase , F5 refresh , copy the link url and send it to someone by sns and so on.. 

and when moved back page , many people , does not want to be refresh page  statarted top line . 

please improve for context.push function , 

1. stack page
2. show the url domain.

please..

**Comment by darshankawar** [comment]
@ItdaTeam 
The `context.push` feature, if I am not wrong, was removed in 8.0.0 plugin version as shown in the changelog here: https://pub.dev/packages/go_router/changelog#800

Can you elaborate more with an example (code snippet) as what limitation are you facing currently and what changes you would like to see along with how [this](https://github.com/flutter/flutter/issues/131083) issue is different from yours ?
