### ISSUE TITLE
Network Image exception

### ISSUE THREAD

**Issue by leobispo** [flutter/flutter#13147]
## Steps to Reproduce

Use the https://storage.cloud.google.com/notejuri/1467766052891918392/Person/17daa6bd-4dc0-4c5c-8529-595a60a495b3.png. It will throw the exception.
## Logs

E/flutter ( 4023): [ERROR:flutter/lib/ui/painting/codec.cc(78)] SkCodec::MakeFromData failed
I/flutter ( 4023): ══╡ EXCEPTION CAUGHT BY SERVICES ╞══════════════════════════════════════════════════════════════════
I/flutter ( 4023): The following _Exception was thrown resolving an image codec:
I/flutter ( 4023): Exception: operation failed
I/flutter ( 4023): 
I/flutter ( 4023): When the exception was thrown, this was the stack:
I/flutter ( 4023): #0      _futurize (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/painting.dart:2481)
I/flutter ( 4023): <asynchronous suspension>
I/flutter ( 4023): #1      instantiateImageCodec (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/painting.dart:920)
I/flutter ( 4023): #2      NetworkImage._loadAsync (package:flutter/src/services/image_provider.dart:445)
I/flutter ( 4023): <asynchronous suspension>
I/flutter ( 4023): #3      NetworkImage.load (package:flutter/src/services/image_provider.dart:422)
I/flutter ( 4023): #4      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/services/image_provider.dart:265)
I/flutter ( 4023): #5      ImageCache.putIfAbsent (package:flutter/src/services/image_cache.dart:82)
I/flutter ( 4023): #6      ImageProvider.resolve.<anonymous closure> (package:flutter/src/services/image_provider.dart:265)
I/flutter ( 4023): #7      SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:38)
I/flutter ( 4023): #8      ImageProvider.resolve (package:flutter/src/services/image_provider.dart:263)
I/flutter ( 4023): #9      DecorationImagePainter.paint (package:flutter/src/painting/images.dart:234)
I/flutter ( 4023): #10     _BoxDecorationPainter._paintBackgroundImage (package:flutter/src/painting/box_decoration.dart:384)
I/flutter ( 4023): #11     _BoxDecorationPainter.paint (package:flutter/src/painting/box_decoration.dart:402)
I/flutter ( 4023): #12     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:1578)
I/flutter ( 4023): #13     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:1996)
I/flutter ( 4023): #14     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:136)
I/flutter ( 4023): #15     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:124)
I/flutter ( 4023): #16     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:1996)
I/flutter ( 4023): #17     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:136)
I/flutter ( 4023): #18     RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2183)
I/flutter ( 4023): #19     RenderFlex.paint (package:flutter/src/rendering/flex.dart:931)
I/flutter ( 4023): #20     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:1996)
I/flutter ( 4023): #21     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:136)
I/flutter ( 4023): #22     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70)
I/flutter ( 4023): #23     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:1996)
I/flutter ( 4023): #24     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:136)
I/flutter ( 4023): #25     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:124)
I/flutter ( 4023): #26     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:1597)
I/flutter ( 4023): #27     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:1996)
I/flutter ( 4023): #28     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:136)
I/flutter ( 4023): #29     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:124)
I/flutter ( 4023): #30     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:1996)
I/flutter ( 4023): #31     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:136)
I/flutter ( 4023): #32     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:124)
I/flutter ( 4023): #33     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:1996)
I/flutter ( 4023): #34     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:136)
I/flutter ( 4023): #35     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:124)
I/flutter ( 4023): #36     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:1996)
I/flutter ( 4023): #37     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:116)
I/flutter ( 4023): #38     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:153)
I/flutter ( 4023): #39     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:134)
I/flutter ( 4023): #40     RenderSliverMultiBoxAdaptor.paint (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:541)
I/flutter ( 4023): #41     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:1996)
I/flutter ( 4023): #42     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:136)
I/flutter ( 4023): #43     RenderViewportBase._paintContents (package:flutter/src/rendering/viewport.dart:341)
I/flutter ( 4023): #44     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:313)
I/flutter ( 4023): #45     PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:330)
I/flutter ( 4023): #46     RenderViewportBase.paint (package:flutter/src/rendering/viewport.dart:332)
I/flutter ( 4023): #47     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:1996)
I/flutter ( 4023): #48     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:116)
I/flutter ( 4023): #49     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:784)
I/flutter ( 4023): #50     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:264)
I/flutter ( 4023): #51     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:628)
I/flutter ( 4023): #52     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:200)
I/flutter ( 4023): #53     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:713)
I/flutter ( 4023): #54     BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:649)
I/flutter ( 4023): #55     _invoke (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:101)
I/flutter ( 4023): #56     _drawFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:90)
I/flutter ( 4023): 
I/flutter ( 4023): Image provider:
I/flutter ( 4023): NetworkImage("https://storage.cloud.google.com/notejuri/1467766052891918392/Person/17daa6bd-4dc0-4c5c-8529-595a60a495b3.png",
I/flutter ( 4023): scale: 1.0)
I/flutter ( 4023): Image key:
I/flutter ( 4023): NetworkImage("https://storage.cloud.google.com/notejuri/1467766052891918392/Person/17daa6bd-4dc0-4c5c-8529-595a60a495b3.png",
I/flutter ( 4023): scale: 1.0)
I/flutter ( 4023): ════════════════════════════════════════════════════════════════════════════════════════════════════
## Flutter Doctor

Flutter • channel master • https://github.com/flutter/flutter.git
Framework • revision 8ba08718b6 (20 minutos atrás) • 2017-11-22 13:00:46 +0100
Engine • revision fbd384329b
Tools • Dart 1.25.0-dev.11.0

Running flutter doctor...
[✓] Flutter (on Linux, locale pt_BR.UTF-8, channel master)
    • Flutter at /home/bispo/workspace/flutter
    • Framework revision 8ba08718b6 (20 minutos atrás), 2017-11-22 13:00:46 +0100
    • Engine revision fbd384329b
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.3)
    • Android SDK at /home/bispo/Android/Sdk
    • Android NDK at /home/bispo/Android/Sdk/ndk-bundle
    • Compiler in Android NDK at /home/bispo/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc
    • Platform android-26, build-tools 26.0.3
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /usr/local/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 19.1
    • Dart plugin version 172.4343.25

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

**Comment by Alexays** [comment]
Your link is a redirection, this is probably the cause of the error.

**Comment by leobispo** [comment]
This is a google cloud storage bucket. IMO this should work out of box

**Comment by Alexays** [comment]
This is normal, your link requires google credentials, the link returns the 'google sign in' page, hence the error.

**Comment by leobispo** [comment]
You are right!

**Comment by Hixie** [comment]
cc @amirh Can we make the error message clearer here somehow?

**Comment by amirh** [comment]
In this case the HTTP request succeeded but it did not include a valid image.
The log currently includes: 
E/flutter ( 4023): [ERROR:flutter/lib/ui/painting/codec.cc(78)] SkCodec::MakeFromData failed

Actually MakeFromData's documentation says that it fails if we don't know how to decode the data, I'll update the error message to reflect that.
