### ISSUE TITLE
Get the property name as a string

### ISSUE THREAD

**Issue by NikosTsesmelis** [flutter/flutter#131463]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

```
class User {
  final String name;

  User({required this.name});

  User.fromJson(Map<String, String> json) {
    return User(
      name: json['name'],
    );
  }
}
```

### Proposal

Have a way to get the name of the class property for safe deserialization without the risk of typos etc.

```
class User {
  final String name;

  User({required this.name});

  User.fromJson(Map<String, String> json) {
    return User(
      name: json[name.getPropertyName()],
    );
  }
}
```

**Comment by danagbemava-nc** [comment]
Hi, this would need to be implemented in the dart sdk https://github.com/dart-lang/sdk/issues?q=is:issue+is:open+sort:updated-desc

Kindly file this issue on their repo. 

Closing from here. 

Thank you.
