### ISSUE TITLE
Add a test helper to simulate sending platform events to Flutter

### ISSUE THREAD

**Issue by wujek-srujek** [flutter/flutter#131404]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

My project is 'event-heavy' - we receive a lot of events from the platform side that we subscribe to in Flutter, so we use `EventChannel` extensively. We would also like to be able to test all of this. For `MethodChannel`, I can write a `testWidget` where I can successfully use https://api.flutter.dev/flutter/flutter_test/TestDefaultBinaryMessenger/setMockMethodCallHandler.html. I have been looking around but there seems to be no easy way to simulate an event from the platform in a test. The best I could come up with is the following snippet:

```dart
tester.binding.defaultBinaryMessenger.handlePlatformMessage(
  'myEventChannelName',
  myEncodedData,
  null,
);
```

The problem is that it relies on 2 implementation details of `EventChannel`:
1. It is backed by a `MethodChannel`.
2. The method channel uses exactly the same name.

Now, I don't know if there is any chance of this ever changing at this point, but it does require some knowledge of how `EventChannel` works under the hood.

### Proposal

I would like to have a function like `TestDefaultBinaryMessenger.sendPlatformEvent(EventChannel channel, ...)` or similar, that would abstract all `EventChannel` implementation details away from me. I actually did that by just creating an extension on `TestDefaultBinaryMessenger`, but maybe it would be worth putting something like this into the test framework?

Again, I have looked around and found nothing baked into the framework. If what I'm looking for does exist, my apologies, and please give me pointers where to look for it.

**Comment by danagbemava-nc** [comment]
Hi @wujek-srujek, can you take a look at https://github.com/flutter/flutter/issues/26528 to see if it is similar to your request? Also, does this comment help https://github.com/flutter/flutter/issues/26528#issuecomment-1489451078?

**Comment by wujek-srujek** [comment]
@danagbemava-nc I'm not sure, at first sight it looks like it allows to install a 'listener'; what I want is the inverse - I want to simulate a message from the platform, and I have my listeners react to it, and assert they are doing what I want. The package you mention might be doing that as well, I haven't looked in details. Actually, this comment https://github.com/flutter/flutter/issues/26528#issuecomment-512896634 is more or less what I'm doing, and I would be very happy with a helper (for my current use case).

**Comment by danagbemava-nc** [comment]
Hi @wujek-srujek, the author of the package filed a PR that does the same thing in the framework, it hasn't landed in stable yet so it was published as PR. This is the PR in question https://github.com/flutter/flutter/pull/123726, does it work for you?
