### ISSUE TITLE
Add Travis CI test for gen_snapshot

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#13140]
In recent weeks we've seen two different failures in which gen_snapshot failed to build a snapshot. e.g., due to the rename of `dart:vmservice_sky` to `dart:vmservice_io`.

While this certainly doesn't catch all gen_snapshot failure modes, we should add a Travis test step that builds a script snapshot and an AOT snapshot of hello world as a canary for easy-to-catch issues like these.

**Comment by iapicca** [comment]
Hi @cbracken  is this issue still meant to be open?

**Comment by jonahwilliams** [comment]
We don't use travis CI anymore ... hopefully we don't need this. Or we didn't, as its been 7 years.

**Comment by cbracken** [comment]
Even better, the fixture tests exercise gen_snapshot these days. https://github.com/flutter/engine/blob/3024ddd04bee612a154ef86f4c76d24ac2b13d93/testing/testing.gni#L222-L248
