### ISSUE TITLE
The cloud functions webhook for github-label-notifier may be deleted

### ISSUE THREAD

**Issue by whesse** [flutter/flutter#131473]
The github-label-notifier has been fully migrated to cloud run, and the legacy GitHub webhook in flutter/flutter may be deleted. This is the webhook with destination https://us-central1-dart-ci.cloudfunctions.net/githubWebhook, which is already inactive.

The active webhook with destination https://github-webhook-qvyo5rktwa-uc.a.run.app/githubWebhook should be left unchanged.

**Comment by Hixie** [comment]
done
