### ISSUE TITLE
Flutter app throws so many exceptions about concurrent modification during iteration of a GrowableList

### ISSUE THREAD

**Issue by kurtis92** [flutter/flutter#131415]
Since my team released our flutter app on the store, Crashlytics is noticing us so many exception about concurrent modification during iteration of a GrowableList (actually is the n.1 issue for number of occurrences).
Exception:
```
Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Concurrent modification during iteration: Instance(length:2) of '_GrowableList'.
       at ListIterator.moveNext(dart:_internal)
       at SchedulerBinding.handleDrawFrame(binding.dart:1213)
       at SchedulerBinding._handleDrawFrame(binding.dart:1072)
```
Actually it seems to be not a bug into our application, but rather a problem related to Flutter source code:
[binding.dart:1213](https://github.com/flutter/flutter/blob/f468f3366c26a5092eb964a230ce7892fda8f2f8/packages/flutter/lib/src/scheduler/binding.dart#L1213)

`flutter doctor -v` output:
```
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.2 22D49 darwin-arm64, locale it-IT)
    • Flutter version 3.10.6 on channel stable at /Users/user/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (2 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • ANDROID_HOME = /Users/user/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.75.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.2 22D49 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.248

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by darshankawar** [comment]
@kurtis92 

The error could be probably triggering based on your code implementation itself. See this similar SO link https://stackoverflow.com/questions/22409666/exception-concurrent-modification-during-iteration-instancelength17-of-gr

And response from flutter team member on one such similar issue: https://github.com/flutter/flutter/issues/49339#issuecomment-578662387

Also see https://stackoverflow.com/a/59877613



> Actually it seems to be not a bug into our application, but rather a problem related to Flutter source code:
> [binding.dart:1213](https://github.com/flutter/flutter/blob/f468f3366c26a5092eb964a230ce7892fda8f2f8/packages/flutter/lib/src/scheduler/binding.dart#L1213)

See https://github.com/flutter/flutter/issues/103516#issuecomment-1129406170 and check if it helps in your case or not.

**Comment by kurtis92** [comment]
@darshankawar 
Let's say the Exception comes from our code implementation, why is there no reference to anything related to our code base in the stacktrace?

**Comment by darshankawar** [comment]
@kurtis92 
The stacktrace shared in original description is the complete log you get or there's more ? If so, can you provide the entire log ?
Also, in order to properly address the issue and to deduce if the issue is in the framework or implementation, we would need a minimal reproducible code sample.

**Comment by kurtis92** [comment]
@darshankawar 
Everything we know about this Exception is in the stacktrace already shown in this issue, Crashlytics is not providing more informations about. Is there a way to retrieve more data from Crashlytics?
Also, since there is no reference to anything related to our code base in the stacktrace, I can't provide a code sample actually. As you can imagine, there are many lists in our app, we have already checked that we are not performing insert or delete operations during iteration of those lists.

**Comment by ryzr** [comment]
Also getting the same in Sentry since a recent release of Flutter, though a different Stacktrace. Hasn't been fatal, just very repetitive! I haven't figured out which Flutter version the issue started with (currently we're on 3.10.6), only that Dart was 3.0.6. First occurrence of the issue was July 19, shortly after release. Will share any other info I find!

```ConcurrentModificationError: Concurrent modification during iteration: Instance(length:14) of '_GrowableList'.
#0      ListIterator.moveNext (dart:_internal/iterable.dart:338)
#1      WidgetsBinding.handleAppLifecycleStateChanged (package:flutter/src/widgets/binding.dart:712)
#2      ServicesBinding._handleLifecycleMessage (package:flutter/src/services/binding.dart:261)
#3      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:212)
#4      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:479)
#5      _invoke2 (dart:ui/hooks.dart:174)
#6      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40)
#7      _Channel.push (dart:ui/channel_buffers.dart:130)
#8      ChannelBuffers.push (dart:ui/channel_buffers.dart:326)
#9      PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:686)
#10     _dispatchPlatformMessage (dart:ui/hooks.dart:86)```

**Comment by darshankawar** [comment]
@kurtis92 
Thanks for the feedback. As the error says `Concurrent modification during iteration: Instance(length:2) of '_GrowableList'.`, it probably indicates there's a simultaneous operation being performed along with modifying the list, so I suggest you to revisit your code implementation and see if there's any edge case you might be accidently performing while dealing with the list.

**Comment by kurtis92** [comment]
@darshankawar 
Thank you for your suggestion. However, as mentioned in this issue, the stacktrace clearly refers to a for loop in Flutter source code ([binding.dart:1213](https://github.com/flutter/flutter/blob/f468f3366c26a5092eb964a230ce7892fda8f2f8/packages/flutter/lib/src/scheduler/binding.dart#L1213)), there is no reference to our application code.

**Comment by darshankawar** [comment]
Thanks for the update. Keeping this issue open for team's input on this.

**Comment by mraleph** [comment]
@kurtis92 If you call `addPersistentFrameCallback` while looping over the list of persistent frame callbacks then you are going to get an exception like this. It will not point to the place where `addPersistentFrameCallback` is called, but to the place which iterates.

I have no idea if adding persistent frame callbacks while inside one is a supported use case or not. If it should be supported then iteration needs to be rewritten to use indexed loop. Maybe @dnfield knows?  

The issue reported by @ryzr is similar - there is a list of observers being iterated and we invoke `didChangeAppLifecycleState` on each observer. If this call tries to add or remove observers then you get an exception like that. If this needs to be a supported use case then something like `for (var observer in List<WidgetsBindingObserver>.of(...))` can be a work-around.

**Comment by dnfield** [comment]
In some places, we make a copy of the list to guard against this (we don't want to recursively fire callbacks added during iteration). We're not doing this consistently though.

@goderbauer WDYT? For example, compare 

https://github.com/flutter/flutter/blob/bd64bf5f923fa79635f2971531d9dfd717046963/packages/flutter/lib/src/widgets/binding.dart#L724 

And

https://github.com/flutter/flutter/blob/bd64bf5f923fa79635f2971531d9dfd717046963/packages/flutter/lib/src/widgets/binding.dart#L703

Or compare the persistent callbacks with the post frame callbacks here:

https://github.com/flutter/flutter/blob/bd64bf5f923fa79635f2971531d9dfd717046963/packages/flutter/lib/src/scheduler/binding.dart#L1230-L1241

We should fix these with a copy of the list. I think indexed iteration won't be safe in the case where something ends up removing itself from the list.
