### ISSUE TITLE
Devicelab mac-46 in try pool is down

### ISSUE THREAD

**Issue by ricardoamador** [flutter/flutter#131496]
flutter-devicelab-mac-46 is down and has last been seen 7w ago.

**Comment by kentnguyen99** [comment]
@ricardoamador I checked mac-46, it is up and it has been running for 50 days. Let me check around and I see anything wrong with machine.

flutter@flutter-devicelab-mac-46 ~ % uptime
10:14  up 50 days, 13:04, 2 users, load averages: 1.17 1.14 1.07

**Comment by ricardoamador** [comment]
Oh odd. It shows as down in the bot list:
![image](https://github.com/flutter/flutter/assets/32242716/16d0b501-88c8-4d67-ad47-2e48a4562fa7)

**Comment by ricardoamador** [comment]
Oh I wonder if it is not able to communicate with the swarming service.

**Comment by ricardoamador** [comment]
Yeah that looks like the issue. The bot is not authorized for the swarming handshake api. I remember this being an issue from a while back.

![image](https://github.com/flutter/flutter/assets/32242716/0959c629-3af1-49a2-b4c6-7c8d9a745231)

**Comment by kentnguyen99** [comment]
@ricardoamador Can you check machine mac-46 again?  It should be good now.
Machine mac-46 is back online and running fine now. It was bot check and want to upgrade "M2CRYPTO" from v0.36. to v038.0 and missing "swig" package.  I don't see mac-46 went dead from monitoring website https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=os&c=status&d=desc&f=pool%3Aluci.flutter.staging&s=status .  Can you add mac-46 to monitoring website?  Thanks.

**Comment by ricardoamador** [comment]
It is not in the staging pool. It is in the try pool. Shows as quarantined now with a different error:
![image](https://github.com/flutter/flutter/assets/32242716/5ae25e32-0bb1-40fa-8049-df13dca6e625)

**Comment by kentnguyen99** [comment]
Hi @keyonghan Can you take a look error for machine mac-46 that @ricardoamador is seeing on machine?  I'm not familiar the error, this is new to me. Thanks.

**Comment by ricardoamador** [comment]
Closing as this looks to be fixed now. I see the bot up in the try pool.
