### ISSUE TITLE
Address usability issues with the Flutter Wiki.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#131433]
The Flutter Wiki at https://github.com/flutter/flutter/wiki contains a lot more information than first meets the eye. Unfortunately, a lot (majority?) of the pages are not cross-referenced and there doesn't seem to be a structure to the organization of pages.

------------

<img width="1893" alt="Screenshot 2023-07-27 at 11 57 59 AM" src="https://github.com/flutter/flutter/assets/44085/bf7aa0a3-cd24-4907-b5cb-b9f7379d9acd">

------------

The only way to reach these pages is to notice a "Pages" menu above the side-bar and click it.

------------

<img width="1283" alt="Screenshot 2023-07-27 at 11 58 23 AM" src="https://github.com/flutter/flutter/assets/44085/8d883f3d-d0ad-4a7d-b901-1636ca477e41">

------------

This still only displays a tiny number of the pages in the Wiki.

------------

<img width="324" alt="Screenshot 2023-07-27 at 11 58 50 AM" src="https://github.com/flutter/flutter/assets/44085/711cadd0-4604-4a76-ae8e-5f230ed0bff7">

------------

Unless you are specifically looking for a page on the wiki, it is almost impossible to discover it either from the index or the sidebar.

Perhaps the wiki can be organized by team or subsystem with a prescribed structure and enforcing of cross-references of discoverability?

**Comment by chinmaygarde** [comment]
I used Obsidian. On corp. boxes, you can get a license at go/obsidian-md.

**Comment by Hixie** [comment]
There's some issues with the Obsidian analysis. For example, it lists both "Bad Builds" and "Bad-Builds", even though they're the same page.

I hacked up a custom version. Green means it's listed in the sidebar, red means nothing points to it, black is something points to it other than the sidebar. Light gray text means the file doesn't exist. That's expected for the style guide because I only scanned `.md` files and that's an AsciiDoc file.
![test](https://github.com/flutter/flutter/assets/551196/11f3e421-f861-45ca-9430-445c78a40cfc)

**Comment by Hixie** [comment]
This gives us the following list of pages that are orphans in the wiki today:

```
Adding-Flutter-to-Android.md
Binding-to-native-code-via-FFI.md
CI-Config-Migration-Guide.md
Code-generation-in-Flutter.md
Codelabs.md
Commits-Between-1.2.1-and-1.5.4.md
Creating-an-iOS-Bitcode-enabled-app.md
Debugging-issues-on-the-Web.md
Experimental-web-options.md
Experimental:-Adding-Flutter-to-Android.md
Experimenting-with-null-safety-in-Flutter.md
Flutter-CLI-crash-reporting.md
Flutter-FirebaseLab-Tests.md
Flutter-GPU.md
Flutter-Test-Fonts.md
Game-development-with-Flutter.md
How-Flutter-apps-are-compiled-with-Gradle-for-Android.md
Hybrid-Composition-iOS.md
IntelliJ---Flutter-Setup-Tips-and-Tricks.md
Life-of-a-Flutter-Frame.md
Migrating-Plugins-repository-PRs-to-Packages.md
Obfuscating-Dart-Code.md
PID-leak-in-iOS-development-workflow.md
PRs-addressed-between-1.5.4-and-1.7.8.md
PRs-merged-between-1.7.8-and-1.9.1.md
Package-migration-to-1.0.0.md
Reduce-shader-compilation-jank-using-SkSL-warm-up.md
Release-Notes---Changes-in-1.2.1.md
Release-Notes---Flutter-1.2.1.md
Release-Notes-Flutter-1.5.4.md
Release-Notes-Flutter-1.7.8.md
Release-Notes-Flutter-1.9.1.md
Release-versioning.md
Resolving-common-build-failures.md
Setting-up-MoltenVK-on-macOS-for-Impeller.md
State-of-Catalina-Support.md
Unexpected-Plugins-and-Packages-failures.md
Upgrading-Flutter-added-to-existing-iOS-Xcode-project.md
Upgrading-Flutter-projects-from-using-PlatformMessages-to-using-channels.md
Upgrading-Flutter-projects-to-Gradle-4.1-and-Android-Studio-Gradle-plugin-3.0.1.md
Upgrading-Flutter-projects-to-build-with-gradle.md
Upgrading-from-package:flutter_web-to-the-Flutter-SDK.md
Upgrading-pre-1.12-Android-projects.md
Waiting-for-tree-to-go-green-bot.md
Writing-Effective-Tests.md
code-signing-metadata.md
```

**Comment by Hixie** [comment]
Not sure what this is about: https://github.com/flutter/flutter/wiki/Flutter-migrate @stuartmorgan @reidbaker @christopherfujino any ideas?

**Comment by stuartmorgan** [comment]
It's about https://github.com/flutter/packages/tree/main/packages/flutter_migrate, which was mid-development when we lost the engineering resourcing for it.

**Comment by Hixie** [comment]
Ok I think the wiki now has no orphan nodes!
![](https://github.com/flutter/flutter/assets/551196/344a626a-9fda-4be1-9c76-2e884f920eec)

**Comment by Hixie** [comment]
https://github.com/flutter/cocoon/pull/2983 is the code I used to generate the graph, FWIW.
