### ISSUE TITLE
[google_sign_in_web] Chrome blocks One Tap UX and granular consent screen popup

### ISSUE THREAD

**Issue by Fiurgeist** [flutter/flutter#131420]
### Is there an existing issue for this?

- [X] I have searched the [existing package issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Apackage)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### What package does this bug report belong to?

google_sign_in

### What target platforms are you seeing this bug on?

Web

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
  google_sign_in:
    dependency: "direct main"
    description:
      name: google_sign_in
      sha256: aab6fdc41374014494f9e9026b9859e7309639d50a0bf4a2a412467a5ae4abc6
      url: "https://pub.dev"
    source: hosted
    version: "6.1.4"
  google_sign_in_android:
    dependency: transitive
    description:
      name: google_sign_in_android
      sha256: "2a8b90b766ce00b03e7543f4ffeec97b6eb51fb6c3f31ce2a364bd1f1b9dd7fc"
      url: "https://pub.dev"
    source: hosted
    version: "6.1.14"
  google_sign_in_ios:
    dependency: transitive
    description:
      name: google_sign_in_ios
      sha256: "6ec0e13a4c5c646471b9f6a25ceb3ae76d339889d4c0f79b729bf0714215a63e"
      url: "https://pub.dev"
    source: hosted
    version: "5.6.2"
  google_sign_in_platform_interface:
    dependency: "direct main"
    description:
      name: google_sign_in_platform_interface
      sha256: e69553c0fc6a76216e9d06a8c3767e291ad9be42171f879aab7ab708569d4393
      url: "https://pub.dev"
    source: hosted
    version: "2.4.1"
  google_sign_in_web:
    dependency: "direct main"
    description:
      name: google_sign_in_web
      sha256: "69b9ce0e760945ff52337921a8b5871592b74c92f85e7632293310701eea68cc"
      url: "https://pub.dev"
    source: hosted
    version: "0.12.0+2"
```

</details>

### Steps to reproduce

1. configure `Client ID -> Authorized JavaScript origins` as `https://sub.my.domain`
2. initialise GoogleSignIn with additional scopes (for the granular consent screen part)
3. use `signInSilently()` and `renderButton()` (see code sample)
4. build release: `flutter clean && flutter build web --release`
5. deploy to `https://sub.my.domain`
6. open `https://sub.my.domain` in Chrome (Version 114.0.5735.248 (Official Build) (arm64))

### Expected results

- Google One Tap UX shows up
- granular consent screen popup is not blocked

### Actual results

- Google One Tap UX does not show up in Chrome, because the browser blocks the gsi_client request `client:113 GET https://accounts.google.com/gsi/status?client_id=<client_id>&as=<as> net::ERR_BLOCKED_BY_CLIENT`
  - while in Firefox it is not blocked 

- When clicking the Sign-In button and choosing an account ("https://accounts.google.com/gsi/select..." popup)(or in Firefox after the One Tap UX does the sign-in "https://accounts.google.com/gsi/issue...") then the granular consent screen popup is blocked: `[GSI_LOGGER]: Failed to open popup window on url: https://accounts.google.com/o/oauth2/v2/auth?gsiwebsdk=3&client_id=<client_id>&scope=<scope>&redirect_uri=storagerelay%3A%2F%2Fhttps<...>&login_hint=<login_hint>&response_type=token&include_granted_scopes=true&enable_granular_consent=true. Maybe blocked by the browser?`
  - fyi: I also have another app written with React using the `@react-oauth/google` library and there the granular consent screen popup is not blocked

- fyi: running it on localhost (`flutter run -d chrome --web-port=8080`) nothing is blocked and all works just fine

### Code sample

<details><summary>Code sample</summary>

```dart
googleSignIn = GoogleSignIn(
  clientId: clientId,
  scopes: scopes,
);
....// App widget
  @override
  void initState() {
    super.initState();
    googleSignIn.onCurrentUserChanged.listen((GoogleSignInAccount? account) async {
      final bool isAuthorized = await googleSignIn.requestScopes(scopes);
      setState(() {
        _account = isAuthorized ? account : null;
      });
    });
    googleSignIn.signInSilently();
  }
...// Login Widget
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        ...
        body: Column(
          children: [
            ...
            Center(child: signInButton()),
          ],
        ));
  }
...
Widget signInButton() {
  return (GoogleSignInPlatform.instance as web.GoogleSignInPlugin).renderButton();
}
```

</details>

### Logs

<details><summary>Logs</summary>

Chrome blocks gsi_client request (while Firefox does not)
```console
client:45 [GSI_LOGGER]: Check credential status returns invalid response.
client:113 GET https://accounts.google.com/gsi/status?client_id=<client_id>&as=<as> net::ERR_BLOCKED_BY_CLIENT
```

both Chrome and Firefox block the granular consent screen (both in the One Tap UX flow and the renderButton flow)
```console
client:256 Cross-Origin-Opener-Policy policy would block the window.postMessage call.
client:45 [GSI_LOGGER]: Failed to open popup window on url: https://accounts.google.com/o/oauth2/v2/auth?gsiwebsdk=3&client_id=<client_id>&scope=<scope>&redirect_uri=storagerelay%3A%2F%2Fhttps<...>&login_hint=<login_hint>&response_type=token&include_granted_scopes=true&enable_granular_consent=true. Maybe blocked by the browser?
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.8, on macOS 12.2.1 21D62 darwin-arm64, locale en-DE)
    • Flutter version 3.7.8 on channel stable at /opt/homebrew/Caskroom/flutter/3.7.8/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 90c64ed42b (4 months ago), 2023-03-21 11:27:08 -0500
    • Engine revision 9aa7816315
    • Dart version 2.19.5
    • DevTools version 2.20.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.2.1 21D62 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.248

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by huycozy** [comment]
Hi @Fiurgeist 
I tried re-checking this but it works as expected on my side with [plugin sample code](https://github.com/flutter/packages/tree/main/packages/google_sign_in/google_sign_in/example).

<details>
<summary>Demo video</summary>

https://github.com/flutter/flutter/assets/104349824/22959b91-9d38-450d-ba32-c45bd6c83c06

</details>

There is only one difference that is I'm using the latest Chrome version `Version 115.0.5790.114 (Official Build) (x86_64)`. 

Also, are you using any adblock extension that may block the popup? Can you retry on Incognito mode?

**Comment by Fiurgeist** [comment]
hi, thx for the hint :)
I don't have an ad-blocker installed, next to some google extensions I actually have one extension installed and that is
`1Password – Password Manager`
and when I disable it, it all works... I don't even...
