### ISSUE TITLE
flutter/packages closed on scorecard failure

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#131403]
The scorecard analysis task is persistently failing ([example](https://github.com/flutter/packages/actions/runs/5675452050/job/15395239881)) on what looks like an attempt to prompt for permission to send data (which obviously never gets a response in CI). This is keeping the entire flutter/packages tree closed.

(/cc @tarrinneal who is the current gardener for flutter/packages)

**Comment by keyonghan** [comment]
Could you help take a look @drewroengoogle or @sealesj ?

**Comment by sealesj** [comment]
Yes, looking now

**Comment by tarrinneal** [comment]
Seems the latest roll may have fixed this issue

**Comment by parlough** [comment]
It started working on flutter/website again as well.

**Comment by sealesj** [comment]
Weird, seems like the error was on the scorecards side then. Previous successful scorecards scans show the same prompt for permission https://github.com/flutter/packages/actions/runs/5683761137/job/15404999752

**Comment by ricardoamador** [comment]
Is this still an issue?

**Comment by tarrinneal** [comment]
Seemed to be resolved for flutter/packages
