### ISSUE TITLE
Wrong analysis error appears in Flutter projects

### ISSUE THREAD

**Issue by rxlabz** [flutter/flutter#13146]
an analysis error appears if I use this code in a Flutter project :

```
class Lister {
  List<List<Function>> commands;

  void forAll() {
    commands.forEach((List<Function> cmds) => cmds.forEach((Function cmd) => cmd()));
  }
}
```
![animate_item2_dart_-_fluttie_-____dev_projects_fluttie_](https://user-images.githubusercontent.com/1397248/33126873-6b9ba398-cf86-11e7-991f-7a96bca8fa41.png)

The error disappears if I use `Function.apply(cmd,[])`

If I try it in a Non-Flutter Dart project, no error is shown => on dartPad  https://dartpad.dartlang.org/fd66465e52d0e582258f549f485d6195

## Logs
`flutter analyze` displays `error • 'c' isn't a function at lib/animate_item2.dart:83:37 • invocation_of_non_function`

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.12.6 16G1036, locale fr-FR, channel alpha)
    • Flutter at /Users/rxlabz/dev/tools/flutter
    • Framework revision e8aa40eddd (5 weeks ago), 2017-10-17 15:42:40 -0700
    • Engine revision 7c4142808c
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/rxlabz/Library/Android/sdk
    • Platform android-25, build-tools 25.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.0, Build version 9A235
    • ios-deploy 1.9.2
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.3 EAP)
    • Flutter plugin version 19.1
    • Dart plugin version 172.3317.48
```

**Comment by mit-mit** [comment]
cc @floitschG

**Comment by floitschG** [comment]
This warning is triggered by `enableStrictCallChecks: true` line in the analysis_options file.
(https://github.com/dart-lang/sdk/issues/21938)

I think the analyser is too aggressive and should allow calls to `Function`.

**Comment by rxlabz** [comment]
@floitschG FWIW I'm agree :) 
thanks for the explanation and the "linking" !

**Comment by mit-mit** [comment]
This is currently waiting on https://github.com/dart-lang/sdk/issues/31509

**Comment by Hixie** [comment]
This sounds like a Dart SDK bug. I recommend filing that in the dart-lang/sdk repo.
