### ISSUE TITLE
Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.

### ISSUE THREAD

**Issue by Sifatsb** [flutter/flutter#131498]
```
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
Running Gradle task 'assembleDebug'...
Exception: Flutter failed to run "/Users/noob/Documents/Flutter/OutSide Projects/Shakib/project-4/taki_booking_driver/android/gradlew -q -Ptarget-platform=android-arm64 -Ptarget=/Users/noob/Documents/Flutter/OutSide Projects/Shakib/project-4/taki_booking_driver/lib/main.dart -Pbase-application-name=android.app.Application -Pdart-defines=Zmx1dHRlci5pbnNwZWN0b3Iuc3RydWN0dXJlZEVycm9ycz10cnVl,RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ==,RkxVVFRFUl9XRUJfQ0FOVkFTS0lUX1VSTD1odHRwczovL3d3dy5nc3RhdGljLmNvbS9mbHV0dGVyLWNhbnZhc2tpdC9jZGJlZGE3ODhhMjkzZmEyOTY2NWRjM2ZhM2Q2ZTYzYmQyMjFjYjBkLw== -Pdart-obfuscation=false -Ptrack-widget-creation=true -Ptree-shake-icons=false -Pfilesystem-scheme=org-dartlang-root assembleDebug".
Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.
```

Is there any solution for this problem? I am using mac. My others projects are running well. I have tried stackoverflow and github solutions those are not working for me.

**Comment by iapicca** [comment]
I suspect this belongs on SO 
[The flutter tool cannot access the file or directory. Unable to grant read/write permissions for the current user](https://stackoverflow.com/questions/73639155/the-flutter-tool-cannot-access-the-file-or-directory-unable-to-grant-read-write)

**Comment by darshankawar** [comment]
@Sifatsb 
You have space in one of your folders `/OutSide Projects/`. 
Try to remove space and have it one name or put underscore and then run your scenario again to see if it still gives you same error or not.

Also, see if [this](https://github.com/flutter/flutter/issues/70216) is relatable to your case or not and check if [this](https://github.com/flutter/flutter/issues/70216#issuecomment-1304903704) helps to resolve your issue or not.

Closing for now in favor of the linked issue. If you disagree, write in comments and I'll reopen it.

**Comment by Sifatsb** [comment]
> 
@darshankawar I have tried to move on to another folder and there were no space but still get same error
