### ISSUE TITLE
Bump `compileSdkVersion`s in benchmarks and tests to the latest sdk version

### ISSUE THREAD

**Issue by gmackall** [flutter/flutter#131425]
Currently a number of the benchmarks and tests are using api 31 instead of 33 for target and compile sdk versions. We should change these to use 33 instead (or `flutter.compileSdkVersion`, where possible).

We should also add documentation that indicates that we always use the latest targetSdkVersion, as there are no binary side effects and it gives you the most recent versions of linters, etc.

Also potentially the latest compileSdkVersion, though there are side effects (unlike targetSdkVersion).

**Comment by gmackall** [comment]
An actionable piece of https://github.com/flutter/flutter/issues/102183

**Comment by gmackall** [comment]
cc @reidbaker Only piece left here is the documentation, do you have an opinion on if it should be in code (e.g. [here](https://github.com/flutter/flutter/blob/972d36c4efeee7e3bb16c050fd233389625a6470/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy#L53) and [here](https://github.com/flutter/flutter/blob/972d36c4efeee7e3bb16c050fd233389625a6470/packages/flutter_tools/lib/src/android/gradle_utils.dart#L43)), or in the team charter, or elsewhere?

**Comment by reidbaker** [comment]
I think in code is the right place. I do not think it should go in the charter. That is more about how we work and this is relevant for flutter contributors.
