### ISSUE TITLE
Find Required Reason API usage in 1P Flutter Plugins and create Privacy Manifest if applicable

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#131495]
Introduced in Xcode 15, Apple is now flagging specific APIs as needing a “Required Reason” to use. All usages of “Required Reason” APIs MUST be outlined in a Privacy manifest. A Privacy manifest is a document outlining how your app/SDK collects and uses a user’s data.

This is also time sensitive (https://developer.apple.com/news/?id=z6fu1dcu).

> Starting in fall 2023, when you upload a new app or app update to App Store Connect that uses an API (including from third-party SDKs) that requires a reason, you’ll receive a notice if you haven’t provided an approved reason in your app’s privacy manifest. And starting in spring 2024, in order to upload your new app or app update to App Store Connect, you’ll be required to include an approved reason in the app’s privacy manifest which accurately reflects how your app uses the API.

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api?language=objc
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests?language=objc
https://developer.apple.com/videos/play/wwdc2023/10060/

We'll probably want to also add testing to scan for Required Reason APIs, so they get caught when added.

We could also build tooling around this to try and warn plugin authors.

**Comment by stuartmorgan** [comment]
I've audited flutter/packages, and the only thing I found was `NSUserDefaults`.

That raises a very tricky question about how we want to handle this in the ecosystem:
- `shared_preferences` itself is just a wrapper around the API, it doesn't know how/why it's being used. So we can't do the manifest at that layer. (Technically currently there's only one possible reason that could be given, so we could, but I don't expect that to continue to be true.)
- If an app is just using `shared_preferences` themselves, the app developer can list the reason.
- But if a package the app is using (even transitively) is using `shared_preferences` for some package-internal state, then only the developer of *that package* knows how/why it's being used.

It seems like we'll either need to:
- leave this up to app developers to deal with (e.g., via finding the transitive usage and asking developers to list the reasons in their READMEs), which isn't going to be a good experience, or
- build a system for arbitrary pub packages to declare privacy manifests, and for the tool to bundle them all together.

**Comment by vashworth** [comment]
@stuartmorgan Looking at the documentation, it says `If you use the API in your third-party SDK’s code, then you need to report the API in your third-party SDK’s privacy manifest file`, which makes it sound like just having the code for it (even if you don't actually use it) may be enough to flag it.

So perhaps, even though `shared_preferences` is just wrapper, we should do the privacy manifest at the plugin layer.

**Comment by stuartmorgan** [comment]
> So perhaps, even though `shared_preferences` is just wrapper, we should do the privacy manifest at the plugin layer.

But we literally don't know at that layer what data is being stored is or how it's being used.

I've filed a request for a new reason describing the wrapping/delegation case. We'll see what Apple says about how to handle it.

**Comment by 781flyingdutchman** [comment]
As a plugin author, where/how do I declare the privacy manifest? A plugin isn't a typical iOS 3rd party SDK, so it isn't clear to me that the approach described [here](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests#4239187) works for a plugin.  I would like to add the manifest at the plugin level (different from userdefaults, I _do_ know why I use a file system API) so that the user of my plugin package doesn't have to do this. Any insights are appreciated!

**Comment by creativecreatorormaybenot** [comment]
So I just now received an email from someone at Apple inquiring that I would sync up a Flutter plugin I maintain to this new manifest (linking to https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests?language=objc).

Not sure how they even got hold of my contact. Any guidance as to how to proceed here?

**Comment by stuartmorgan** [comment]
@creativecreatorormaybenot Please see https://github.com/flutter/flutter/issues/131940 as referenced just above.

**Comment by omarzl** [comment]
Hello I created a [binary analyzer](https://github.com/omarzl/ios_17_required_reason_api_scanner/tree/binary_analyzer) and these are the "required reasons API" symbols found in Flutter xcframework binaries:

`Used symbols in binary ./Flutter.xcframework/ios-arm64_x86_64-simulator/Flutter.framework/Flutter: fstat, fstatfs, lstat, mach_absolute_time, NSURLContentModificationDateKey, stat, statfs, statvfs`

`Used symbols in binary ./Flutter.xcframework/ios-arm64/Flutter.framework/Flutter: fstat, fstatfs, lstat, mach_absolute_time, NSURLContentModificationDateKey, stat, statfs, statvfs`
