### ISSUE TITLE
[Impeller] Rect transformations should handle perspective

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#131445]
Our current rect bounds transformation routines work fine for affine transforms but are not quite right when perspective is involved. See SkMatrixPriv::MapRect for a working implementation.

**Comment by flar** [comment]
A second `TransformBounds` method is being added in https://github.com/flutter/engine/pull/51919 that does this extra clipping work. It is needed there to maintain compatible behavior for the engine code that is moving onto the Impeller geometry classes, but it was added as a separate method for now to avoid performance impact on the Impeller renderer. If we decide we want this behavior/protection all throughout Impeller then the methods can be merged. If we decide we only want it to be used in specific cases then this issue can be closed based on that PR.

**Comment by flar** [comment]
This was basically fixed in https://github.com/flutter/engine/pull/51919 with a new method.
