### ISSUE TITLE
Flutter app is crashing on windows on customers machines

### ISSUE THREAD

**Issue by ekuleshov** [flutter/flutter#131480]
### Steps to reproduce

The Flutter app built with Flutter 3.10.6, 3.10.5 or 3.10.1 for the Windows target is crashing at random places on some customer's machines. According to the crash dump the crash is happening somewhere in the `flutter_windows.dll`.

We were unable to reproduce issue in the dev environment (both debug and the same release app builds).

In any case we are looking for a guidance or tips how to get to the bottom of this.

### Expected results

No crash

### Actual results

Here is WinDbg output for a .dmp file from one of the crashes.

```
0:000> !analyze -v
*******************************************************************************
*                                                                             *
*                        Exception Analysis                                   *
*                                                                             *
*******************************************************************************


KEY_VALUES_STRING: 1

    Key  : AV.Dereference
    Value: NullPtr

    Key  : AV.Fault
    Value: Read

    Key  : Analysis.CPU.mSec
    Value: 1671

    Key  : Analysis.Elapsed.mSec
    Value: 2382

    Key  : Analysis.IO.Other.Mb
    Value: 0

    Key  : Analysis.IO.Read.Mb
    Value: 0

    Key  : Analysis.IO.Write.Mb
    Value: 0

    Key  : Analysis.Init.CPU.mSec
    Value: 312

    Key  : Analysis.Init.Elapsed.mSec
    Value: 106402

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 107

    Key  : Failure.Bucket
    Value: NULL_POINTER_READ_c0000005_flutter_windows.dll!Unknown

    Key  : Failure.Hash
    Value: {50c90234-ea28-50e4-5966-c3a5b7786078}

    Key  : Timeline.Process.Start.DeltaSec
    Value: 19

    Key  : WER.OS.Branch
    Value: vb_release

    Key  : WER.OS.Version
    Value: 10.0.19041.1

    Key  : WER.Process.Version
    Value: 10.0.19041.546


FILE_IN_CAB:  APP_CRASH.exe.15552.dmp

NTGLOBALFLAG:  0

PROCESS_BAM_CURRENT_THROTTLED: 0

PROCESS_BAM_PREVIOUS_THROTTLED: 0

APPLICATION_VERIFIER_FLAGS:  0

CONTEXT:  (.ecxr)
rax=00007ffd56831810 rbx=0000000000000000 rcx=0000000000000000
rdx=000000f605b7e990 rsi=000000f605b7e990 rdi=00000284fe6b04e0
rip=00007ffd5683181b rsp=000000f605b7e870 rbp=0000000000000000
 r8=000000000000000a  r9=0000028489dafb40 r10=0000028487292240
r11=000000f605b7e6a0 r12=000000000000000e r13=000000f605b7ea70
r14=0000000000000000 r15=0000000000000000
iopl=0         nv up ei pl nz na pe nc
cs=0033  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010202
flutter_windows+0x181b:
00007ffd`5683181b 488b01          mov     rax,qword ptr [rcx] ds:00000000`00000000=????????????????
Resetting default scope

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 00007ffd5683181b (flutter_windows+0x000000000000181b)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 0000000000000000
   Parameter[1]: 0000000000000000
Attempt to read from address 0000000000000000

PROCESS_NAME:  APP_CRASH.exe

READ_ADDRESS:  0000000000000000 

ERROR_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.

EXCEPTION_CODE_STR:  c0000005

EXCEPTION_PARAMETER1:  0000000000000000

EXCEPTION_PARAMETER2:  0000000000000000

IP_ON_HEAP:  ffffffff899af5e0
The fault address in not in any loaded module, please check your build's rebase
log at <releasedir>\bin\build_logs\timebuild\ntrebase.log for module which may
contain the address if it were loaded.

FRAME_ONE_INVALID: 1

STACK_TEXT:  
000000f6`05b7e870 ffffffff`899af5e0     : 000046f3`bfcc777c 000000f6`05b7e9d8 00000284`fe6b04e0 00000284`87410300 : flutter_windows+0x181b
000000f6`05b7e878 000046f3`bfcc777c     : 000000f6`05b7e9d8 00000284`fe6b04e0 00000284`87410300 00007ffd`56831681 : 0xffffffff`899af5e0
000000f6`05b7e880 000000f6`05b7e9d8     : 00000284`fe6b04e0 00000284`87410300 00007ffd`56831681 00000000`00000000 : 0x000046f3`bfcc777c
000000f6`05b7e888 00000284`fe6b04e0     : 00000284`87410300 00007ffd`56831681 00000000`00000000 00000000`0000000f : 0x000000f6`05b7e9d8
000000f6`05b7e890 00000284`87410300     : 00007ffd`56831681 00000000`00000000 00000000`0000000f 000000f6`05b7eb01 : 0x00000284`fe6b04e0
000000f6`05b7e898 00007ffd`56831681     : 00000000`00000000 00000000`0000000f 000000f6`05b7eb01 000000f6`00000000 : 0x00000284`87410300
000000f6`05b7e8a0 00000000`00000000     : 00000000`0000000f 000000f6`05b7eb01 000000f6`00000000 00000000`87528be0 : flutter_windows+0x1681


STACK_COMMAND:  ~0s; .ecxr ; kb

SYMBOL_NAME:  flutter_windows+181b

MODULE_NAME: flutter_windows

IMAGE_NAME:  flutter_windows.dll

FAILURE_BUCKET_ID:  NULL_POINTER_READ_c0000005_flutter_windows.dll!Unknown

OS_VERSION:  10.0.19041.1

BUILDLAB_STR:  vb_release

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

FAILURE_ID_HASH:  {50c90234-ea28-50e4-5966-c3a5b7786078}

Followup:     MachineOwner
---------

0:000> .ecxr
rax=00007ffd56831810 rbx=0000000000000000 rcx=0000000000000000
rdx=000000f605b7e990 rsi=000000f605b7e990 rdi=00000284fe6b04e0
rip=00007ffd5683181b rsp=000000f605b7e870 rbp=0000000000000000
 r8=000000000000000a  r9=0000028489dafb40 r10=0000028487292240
r11=000000f605b7e6a0 r12=000000000000000e r13=000000f605b7ea70
r14=0000000000000000 r15=0000000000000000
iopl=0         nv up ei pl nz na pe nc
cs=0033  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010202
flutter_windows+0x181b:
00007ffd`5683181b 488b01          mov     rax,qword ptr [rcx] ds:00000000`00000000=????????????????
0:000> .exr -1
ExceptionAddress: 00007ffd5683181b (flutter_windows+0x000000000000181b)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 0000000000000000
   Parameter[1]: 0000000000000000
Attempt to read from address 0000000000000000

```

### Code sample

We were unable to reproduce issue in a small isolated sample.

### Screenshots or Video

The app is simply crashes at somewhat arbitrary places on some customer's machines.

### Logs

There are no flutter logs available for these crashes of the released app.

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
>flutter doctor -v
[✓] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.22621.1992], locale en-CA)
    • Flutter version 3.10.6 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (2 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.6.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33829.357
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2023.1.2
    • Flutter plugin version 74.0.4
    • Dart plugin version 231.9161.14

[✓] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1992]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 114.0.1823.82

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

</details>

**Comment by huycozy** [comment]
Hi @ekuleshov 
Can you please collect affected Windows device info (OS version, percentage occurrence of the crash) and share it here?

**Comment by ekuleshov** [comment]
Here is the info I was able to collect from a customer machine.

Please let me know if you need any additional details

![image](https://github.com/flutter/flutter/assets/440954/b22c9508-4294-4765-aaa5-0acfa7a38add)

![image](https://github.com/flutter/flutter/assets/440954/7c0f4cdc-c4b3-4b40-ae5e-56423d33a477)

![image](https://github.com/flutter/flutter/assets/440954/c2d60ba2-42a7-4855-b4d9-555595ed0e32)

**Comment by huycozy** [comment]
Thanks, that may be helpful for further investigation.

**Comment by loic-sharma** [comment]
Hello, thank you for reporting this crash. Could you load Flutter's symbols to add additional debugging information to the crash? You should be able to find the symbols at `C:\flutter\bin\cache\artifacts\engine\windows-x64`. If needed, here are instructions on how to load symbols in WinDBG:

1. https://learn.microsoft.com/windows-hardware/drivers/debugger/setting-symbol-and-source-paths-in-windbg#symbol-path
2. https://learn.microsoft.com/windows-hardware/drivers/debugger/ld--load-symbols-

<details>
<summary>How to load Flutter's symbols in Visual Studio...</summary>

1. Find your **Flutter SDK path** using the terminal: `flutter doctor --verbose`.

   Let's say I have the following output:
   
   ```
   PS C:\> flutter doctor --verbose
   [✓] Flutter (Channel stable, 3.7.0, on Microsoft Windows [Version 10.0.22621.1105], locale en-US)
       • Flutter version 3.7.0 on channel stable at C:\Code\f\flutter
   ...
   ```

   My **Flutter SDK path** is `C:\Code\f\flutter`.

3. Add Flutter's symbols path to Visual Studio's options
    1. Open the Debugging options using `DEBUG` > `Options...`.
    2. Navigate to the `Symbols` pane and use the `+` button to add `<Flutter SDK path>/bin/cache/artifacts/engine/windows-x64`
   as a symbol location:

       ![Pasted image 20230126161935](https://user-images.githubusercontent.com/737941/214984655-353ba5d8-6ca5-4678-bc97-4932c4b3e63e.png)

    4. Close the `Options` window

3. Load Flutter's symbols in Visual Studio
    1. Open the `Modules` window using `DEBUG` > `Windows` > `Modules` (or `Ctrl+Alt+U`):

       ![Pasted image 20230126161915](https://user-images.githubusercontent.com/737941/214985815-ba128e85-b107-4fbf-ae58-7814b840bfaf.png)

    2. In the `Modules` window, right click the `flutter_windows.dll` item and select `Load Symbols`:

       ![Pasted image 20230126162141](https://user-images.githubusercontent.com/737941/214986218-4f53e12c-ccb6-4c8c-8419-ca8772a5e561.png)

    3. The engine's symbols should now be loaded:

       ![Pasted image 20230126162222](https://user-images.githubusercontent.com/737941/214986347-4bd31006-f960-4311-ad7e-9030b32067eb.png)

For more information, see the [How to debug the Flutter engine on Windows guide.](https://gist.github.com/loic-sharma/248f28b3ba4664dde08da68f46b312bd)

</details>

**Comment by ekuleshov** [comment]
> Hello, thank you for reporting this crash. Could you load Flutter's symbols to add additional debugging information to the crash? You should be able to find the symbols at `C:\flutter\bin\cache\artifacts\engine\windows-x64`. ...
> Alternatively, here's how to load Flutter's symbols in Visual Studio...

Thank you for these instructions.

The WinDbg says these symbols are invalid, but I was able to load them in VS and after clicking on "Debug with native only" action in the .dmp viewer I see this stack trace.

<img width="1348" alt="image" src="https://github.com/flutter/flutter/assets/440954/ba0dc83d-550e-45f2-a2cd-97f61efb25c2">

**Comment by ekuleshov** [comment]
@loic-sharma we were able to reproduce the same issue on more Windows 11 machines.

The app is built with Flutter 3.10.6 and when Windows built in `Narrator` is active the app is crashing at the same place as on the customer's machines. Also, it could be related that the customer's Windows machines may also have a touch screen HID device.

Below are the top two stack frames for the crash caught in the Visual Studio running Debug build of the app. It seems like `node_delegate`/`win_delegate` is null there.

![image](https://github.com/flutter/flutter/assets/440954/a9cdebbb-acf1-4292-9daf-3d40c34c0c78)

![image](https://github.com/flutter/flutter/assets/440954/97de6a6d-62ed-4bbb-bfb2-b7db62a8247c)

**Comment by ekuleshov** [comment]
With the Windows Narrator enabled the sample from a previously closed similar issue  
[127789](https://github.com/flutter/flutter/issues/127789#issuecomment-1584017540) is crashing running on Flutter 3.10.6

```
import 'dart:async';
import 'dart:math';

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final tc = TextEditingController(text: "old text");

  final fc = FocusNode();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        body: Center(
          child: Column(
            children: [
              TextField(
                controller: tc,
                focusNode: fc,
              ),
              TextButton(
                onPressed: () {
                  Timer.periodic(const Duration(seconds: 1), (timer){
                    fc.requestFocus();
                    var randomInt = Random().nextInt(1000);
                    tc.text = "new $randomInt text";
                  });
                },
                child: const Text("test"),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```
</details>

**Comment by loic-sharma** [comment]
@ekuleshov I could reproduce this crash on Flutter 3.10.6 but not on the latest stable version (3.13) or the latest master version. I suspect this may have been fixed by https://github.com/flutter/engine/pull/43281. Could you try [updating your Flutter SDK](https://docs.flutter.dev/release/upgrade) to the latest stable version and seeing if the bug still reproduces then?

**Comment by ekuleshov** [comment]
@loic-sharma I wonder if such severe issue affecting almost every text field in the app has been fixed 1.5 months ago, why it wasn't included into the hot fixe releases for 3.10 release?

**Comment by loic-sharma** [comment]
@ekuleshov That's a good question. I'll follow-up on why we didn't cherry-pick this back to the stable channel, it seems like we should have.

I'll close this as fixed, but let us know if you'd like to reopen this.

**Comment by ekuleshov** [comment]
So far we haven't seen any crashes with updated Flutter version. Thank you.

**Comment by superWendell** [comment]
As long as there is a touch screen on Windows and there is no external keyboard display soft keyboard setting, this problem will be encountered, and the software disk will repeatedly pop up. We hope that the official takes this issue seriously.
