### ISSUE TITLE
MaxColumnWidth and MinColumnWidth return different flex values

### ISSUE THREAD

**Issue by khwgit** [flutter/flutter#131467]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a `MaxColumnWidth` or `MinColumnWidth` with `a: FlexColumnWidth(1.0)` and `b: FixedColumnWidth(100)`
2. See the return of `.flex([])`

The `flex()` function of both `MaxColumnWidth` and `MinColumnWidth` will ignore `aFlex` when `bFlex` is `null`, which will cause unexpected results. For example, `MaxColumnWidth(a, b)` and `MaxColumnWidth(b, a)` have different outputs.

https://github.com/flutter/flutter/blob/0ff68b8c610d54dd88585d0f97531208988f80b3/packages/flutter/lib/src/rendering/table.dart#L263-L274

https://github.com/flutter/flutter/blob/0ff68b8c610d54dd88585d0f97531208988f80b3/packages/flutter/lib/src/rendering/table.dart#L316-L327

### Expected results

`1.0` as `a` is a `FlexColumnWIdth`

### Actual results

`null`

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/rendering.dart';

void main() {
  const width = MaxColumnWidth(
    FlexColumnWidth(1.0),
    FixedColumnWidth(100),
  );
  print('${width.flex([])}');
}
```

</details>

<details><summary>Flutter code sample</summary>

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [Table].

void main() => runApp(const TableExampleApp());

class TableExampleApp extends StatelessWidget {
  const TableExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('Table Sample')),
        body: const Column(children: [
          TableExample(
            width: MaxColumnWidth(
              FlexColumnWidth(),
              FixedColumnWidth(100),
            ),
          ),
          Divider(),
          TableExample(
            width: MaxColumnWidth(
              FixedColumnWidth(100),
              FlexColumnWidth(),
            ),
          ),
        ]),
      ),
    );
  }
}

class TableExample extends StatelessWidget {
  const TableExample({
    super.key,
    required this.width,
  });

  final TableColumnWidth width;

  @override
  Widget build(BuildContext context) {
    return Table(
      columnWidths: {
        0: width,
        1: const FixedColumnWidth(120),
      },
      children: [
        TableRow(children: [
          Container(
            height: 64,
            color: Colors.green,
          ),
          Container(
            height: 64,
            color: Colors.red,
          )
        ]),
      ],
    );
  }
}

```

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.2.1 22D68 darwin-arm64, locale en-HK)
    • Flutter version 3.10.6 on channel stable at /Users/xxx/Development/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (2 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by dam-ease** [comment]
Hi @khwgit. Thanks for filing this issue. This seems more of a proposal as from the codebase, this is the expected result, i.e. when `bFlex` is null, null should be returned. Can you describe your use case and why this returning null could be an issue?

**Comment by khwgit** [comment]
`aFlex` should be returned when `bFlex` is `null`, otherwise the results of
```
MaxColumnWidth(
  FlexColumnWidth(1.0),
  FixedColumnWidth(100),
)
```
and
```
MaxColumnWidth(
  FixedColumnWidth(100),
  FlexColumnWidth(1.0),
)
```
will be different. If it's an expected behaviour, I think we should document it.

**Comment by dam-ease** [comment]
Hi @khwgit. Thanks for responding. I can see from the documentation https://api.flutter.dev/flutter/rendering/MaxColumnWidth/flex.html:

```dart
if (bFlex == null) {
    return null;
  }
```

**Comment by khwgit** [comment]
Certainly you can see the code since the documentation is generated from source code.
My question is 

Should `MaxColumnWidth(FlexColumnWidth(1.0), FixedColumnWidth(100))` and `MaxColumnWidth(FixedColumnWidth(100), FlexColumnWidth(1.0))` behave differently?

For example, I don't think `math.max(10, 1)` and `math.max(1, 10)` should return different values, so I would expect `MaxColumnWidth(FlexColumnWidth(1.0), FixedColumnWidth(100))` and `MaxColumnWidth(FixedColumnWidth(100), FlexColumnWidth(1.0))` have the same behavior. However, the results are different.

Here's the video of the example code

https://github.com/flutter/flutter/assets/61644138/7dc4b881-f0ab-4a13-9475-31e6500225bf

**Comment by dam-ease** [comment]
Thanks for your patience and for providing more insights into the issue. This might be an issue considering they behave differently and return different values. Labelling for more insights.
Thank you!
