### ISSUE TITLE
[Impeller] Support Paint.enableDithering.

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#131450]
Parent issue: https://github.com/flutter/flutter/issues/118073.

Some notes:
- Look at [impeller/entity/shaders/linear_gradient_ssbo_fill.frag](https://github.com/flutter/engine/blob/main/impeller/entity/shaders/linear_gradient_ssbo_fill.frag)
- Look at [impeller/entity/contents/linear_gradient_contents.cc](https://github.com/flutter/engine/blob/main/impeller/entity/contents/linear_gradient_contents.cc)

Potential task items:
- [x] Consider making a standalone playground that shows the same dithering issue within Impeller
- [x] Get dithering working in the standalone playground
- [x] Get consensus we want this to work as implemented before continuing
- [x] Test `RadialGradient` for banding issues
- [x] Test `SweepGradient` for banding issues
- [x] Plumb `Paint.enableDithering` through to Impeller
- [x] ~Create a test that, with the Flutter framework + Impeller, supports dithering~ **Edit**: After talking to the engine team, we discovered that the place to do this (https://github.com/flutter/engine/blob/main/testing/dart/canvas_test.dart) relies on software rendering, and Impeller doesn't support it. For now, this will (like most of Impeller) be manual tested.

> Note that we also talked about the fact that `Paint.enableDithering` is an API anti-pattern, i.e. it would better to either (a) dither by default (as loosely proposed in https://github.com/flutter/flutter/issues/112498, see also @Hixie's comment on https://github.com/flutter/flutter/issues/44134#issuecomment-555781633, and the conversation on https://github.com/flutter/engine/pull/13868), or (b) perhaps better, make it a _local_ flag (i.e. a `bool` or `enum` on [`LinearGradient`](https://api.flutter.dev/flutter/painting/LinearGradient/LinearGradient.html) or similar.
> 
> For sake of scope, we'll continue to target the existing `Paint.enableDithering` in this issue, and explore refactors after.

/cc @jonahwilliams @gaaclarke to keep me honest that the above looks reasonable.

**Comment by jonahwilliams** [comment]
Some additional points:

* Make sure we measure the performance cost of dithering. I think it should be fine - but if we're going to make it the default we'll need to understand the relative costs.
* If we don't want to ship this in the engine for whatever reason, consider creating a package that implements dithered gradients (possible with the fragment program API).
* Look at Skia's dithered gradient implementation (usually easier by running in Xcode or RenderDoc (with GLES backend) and looking at the generated shader.

**Comment by matanlurey** [comment]
> * but if we're going to make it the default we'll need to understand the relative costs.

My understanding was we would still going to honor `Paint.enableDithering`, i.e. it would _not_ be the default. Right?

**Comment by jonahwilliams** [comment]
Correct

**Comment by jonahwilliams** [comment]
That is more a response to, if we were to remove the flag - would we add a flag to gradients or just turn it on by default.

**Comment by matanlurey** [comment]
Quick check-in:

I've created a standalone playground example that reproduces the issue outside of the Flutter framework:

```cc
namespace {
void CanRenderLinearGradientWithDithering(AiksTest* aiks_test,
                                          bool use_dithering) {
  Canvas canvas;
  Paint paint;
  canvas.Translate({100.0, 100.0, 0});

  // 0xffcccccc --> 0xff333333, taken from
  // https://github.com/flutter/flutter/issues/118073#issue-1521699748
  std::vector<Color> colors = {Color{0.8, 0.8, 0.8, 1.0},
                               Color{0.2, 0.2, 0.2, 1.0}};
  std::vector<Scalar> stops = {0.0, 1.0};

  paint.color_source = ColorSource::MakeLinearGradient(
      {0, 0}, {800, 500}, std::move(colors), std::move(stops),
      Entity::TileMode::kClamp, {});
  paint.dither = use_dithering;
  canvas.DrawRect({0, 0, 800, 500}, paint);
  ASSERT_TRUE(aiks_test->OpenPlaygroundHere(canvas.EndRecordingAsPicture()));
}
}  // namespace

TEST_P(AiksTest, CanRenderLinearGradientWithDitheringDisabled) {
  CanRenderLinearGradientWithDithering(this, false);
}
```

![Screenshot 2023-07-28 at 1 45 43 PM](https://github.com/flutter/flutter/assets/168174/ab97ebe0-bb16-451c-aa31-db95b46980a1)

The challenge is there is not a "standard" way to do dithering, and if we wanted to be as close as possible to how Skia does it (for compatibility and user-friendliness), Skia builds the shaders on the fly. One great suggestion from @jonahwilliams was opening up a demo in [RenderDoc](https://renderdoc.org/) and inspecting the generated shader, and seeing if there is anything we can glean from them in terms of how _our_ dithering/noise algorithm should/could work.

I'll try that next.

**Comment by dnfield** [comment]
I thought we were planning on removing this from the paint API?

**Comment by matanlurey** [comment]
@dnfield See https://github.com/flutter/flutter/issues/131450#issue-1825426647:

> Note that we also talked about the fact that `Paint.enableDithering` is an API anti-pattern, i.e. it would better to either (a) dither by default (as loosely proposed in https://github.com/flutter/flutter/issues/112498, see also @Hixie's comment on https://github.com/flutter/flutter/issues/44134#issuecomment-555781633, and the conversation on https://github.com/flutter/engine/pull/13868), or (b) perhaps better, make it a _local_ flag (i.e. a `bool` or `enum` on [`LinearGradient`](https://api.flutter.dev/flutter/painting/LinearGradient/LinearGradient.html) or similar.
> 
> For sake of scope, we'll continue to target the existing `Paint.enableDithering` in this issue, and explore refactors after.

That is yes, but unless we are doing that _today_, it probably makes sense to be compatible with the existing (Skia) backend, or at least not conflate the two issues (refactoring `Paint` versus supporting Dithering in Impeller).

**Comment by dnfield** [comment]
The original customer who asked for the flag decided not to use it, and we couldn't find usage of it in google3 or the ecosystem. But I see now the linked issue and it looks like we would want dithering at some point. Thanks!

**Comment by matanlurey** [comment]
I opened up the demo app created by @gaaclarke and walked through it in RenderDoc:

[Video.webm](https://github.com/flutter/flutter/assets/168174/ee6a8134-2a68-4f62-84bd-c26c5b3390ee)

It's unclear to me if there will be enough information to see exactly how Skia implements the gradient dithering, but in any case this was a useful exercise to get more comfortable with RenderDoc.

**Comment by jonahwilliams** [comment]
If you right click a pixel in the framebuffer and hit debug, that should take you to a shader debugger view of the linear gradient fragment.

**Comment by matanlurey** [comment]
> If you right click a pixel in the framebuffer and hit debug, that should take you to a shader debugger view of the linear gradient fragment.

Hmm, maybe I'm doing something wrong but "Debug Pixel" is greyed out when I try.

**Comment by matanlurey** [comment]
```glsl
#version 320 es

uniform highp vec2 u_skRTFlip;
precision mediump float;
precision mediump sampler2D;
out mediump vec4 sk_FragColor;
uniform mediump vec4 ustart_S1_c0_c0_c0;
uniform mediump vec4 uend_S1_c0_c0_c0;
uniform highp mat3 umatrix_S1_c0_c0_c1;
uniform mediump vec4 uleftBorderColor_S1_c0_c0;
uniform mediump vec4 urightBorderColor_S1_c0_c0;
uniform highp mat3 umatrix_S1_c1;
uniform mediump float urange_S1;
uniform sampler2D uTextureSampler_0_S1;
in mediump vec4 vcolor_S0;
in highp vec2 vTransformedCoords_6_S0;
void main() {
highp     vec4 sk_FragCoord = vec4(gl_FragCoord.x, u_skRTFlip.x + u_skRTFlip.y * gl_FragCoord.y, gl_FragCoord.z, gl_FragCoord.w);
    mediump vec4 outputColor_S0 = vcolor_S0;
    mediump vec4 _22_tmp_6_inColor = outputColor_S0;
    mediump vec4 _23_input = _22_tmp_6_inColor;
    highp vec2 _26_tmp_3_coords = vTransformedCoords_6_S0;
    mediump vec4 _27_t = vec4(_26_tmp_3_coords.x + 1e-05, 1.0, 0.0, 0.0);
    mediump vec4 _28_outColor;
    if (_27_t.x < 0.0) {
        _28_outColor = uleftBorderColor_S1_c0_c0;
    } else if (_27_t.x > 1.0) {
        _28_outColor = urightBorderColor_S1_c0_c0;
    } else {
        highp vec2 _30_tmp_1_coords = vec2(_27_t.x, 0.0);
        _28_outColor = mix(ustart_S1_c0_c0_c0, uend_S1_c0_c0_c0, _30_tmp_1_coords.x);
    }
    _23_input = _28_outColor;
    mediump vec4 _32_color = _23_input;
    mediump float _33_value = texture(uTextureSampler_0_S1, mat3x2(umatrix_S1_c1) * vec3(sk_FragCoord.xy, 1.0), -0.475).x - 0.5;
    mediump vec4 output_S1 = vec4(clamp(_32_color.xyz + _33_value * urange_S1, 0.0, _32_color.w), _32_color.w);
    {
        sk_FragColor = output_S1;
    }
}
```

**Comment by matanlurey** [comment]
For a first pass, something will live (unoptimized, uncached) in [`linear_gradient_contents.cc`](https://github.com/matanlurey/engine/blob/main/impeller/entity/contents/linear_gradient_contents.cc#L132).

**Comment by matanlurey** [comment]
I'm going to first try a different approach:

```glsl
// linear_gradient_ssbo_fill.frag

#include <impeller/dithering.glsl>

if (frag_info.dither) {
  frag_color = IPOrderedDither(frag_color, 8);
}
```

**Comment by matanlurey** [comment]
We agreed today to hold by the original `Paint.enableDithering` contract, at least for `LinearGradient`.

I'll be testing `RadialGradient` and `SweepGradient` for banding issues, applying dithering there (on flag). Once this is landed we'll start another conversation for API correctness (i.e. migrating away from `Paint.enableDithering` to something better).
