### ISSUE TITLE
InlineText's GestureDetector is always full-width

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#131435]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

  1. Create a TextSpan with a `recognizer` property, or use the app below.
  2. Run the app on a platform with a mouse.
  3. Hover over the space to the right of the TextSpan.

### Expected results

Only "example.com" is tappable, as in a typical link on the web, for example.  Here I've highlighted the area I expect to be tappable in blue (with an image editor, not with Flutter).

![Screenshot from 2023-07-27 12-59-33-small](https://github.com/flutter/flutter/assets/389558/c23515cb-f743-4864-96d2-7c7f76d4a2c0)

### Actual results

The entire width, highlighted in blue, is tappable.

![Screenshot from 2023-07-27 12-59-33](https://github.com/flutter/flutter/assets/389558/7da7c299-9a9b-4f70-8701-7c5634688ed3)

Related:
https://github.com/flutter/flutter/issues/27293
https://github.com/flutter/flutter/issues/13211
https://github.com/flutter/flutter/pull/125927

### Code sample

<details>

<summary>Example code</summary>

```dart
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            RichText(
              text: TextSpan(
                style: const TextStyle(
                  color: Colors.black,
                ),
                text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. ',
                children: [
                  TextSpan(
                    text: 'example.com',
                    style: const TextStyle(
                      color: Colors.blue,
                    ),
                    recognizer: TapGestureRecognizer()..onTap = () {},
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

</summary>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel master, 3.13.0-10.0.pre.49, on Debian GNU/Linux rodete 6.3.7-1rodete2-amd64, locale en_US.UTF-8)
    ! Upstream repository git@github.com:justinmc/flutter.git is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to git@github.com:justinmc/flutter.git to dismiss this error.
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.3)
[✓] Android Studio (version 2022.2)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 1 category.

```

</details>

**Comment by justinmc** [comment]
@LongCatIsLooong mentioned that there is a new Skia API that could affect this.  Seems to be related to the hit test method of the TextSpan.

**Comment by justinmc** [comment]
I should check if this issue is fixed after https://github.com/flutter/flutter/pull/131640 is merged.

**Comment by dutsky** [comment]
I have same issue and can't find any workarounds for it. I'm sorry, do you know any workarounds, maybe? Until fix will be released. Thanks!

**Comment by justinmc** [comment]
I verified that https://github.com/flutter/flutter/pull/131640 does fix this problem!  It was closed while waiting for a new Skia API, but the plan is to reopen it again after that.

**Comment by justinmc** [comment]
@dutsky You could patch that PR into a local copy of Flutter if you really need a fix now.  Otherwise I'm not aware of any workarounds.

**Comment by letungcntt** [comment]
@justinmc currently, my project used flutter 3.7 how to fix it. I don't update because lib has crash with 3.10 or 3.13

**Comment by justinmc** [comment]
@letungcntt How is this causing a crash?  Are you able to post a minimal reproduction example?

I don't think there is a workaround until https://github.com/flutter/flutter/pull/131640 is merged, see https://github.com/flutter/flutter/pull/131640#discussion_r1289374199.

CC @LongCatIsLooong
