### ISSUE TITLE
"Don't use 'BuildContext's across async gaps." when use "context.mounted"

### ISSUE THREAD

**Issue by SELiOTe** [flutter/flutter#131491]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

according to [use_build_context_synchronously](https://dart.dev/tools/linter-rules/use_build_context_synchronously) I add `context.mounted` before use `context`, but still got a warning

<img width="775" alt="2023-07-29 00 11 14" src="https://github.com/flutter/flutter/assets/26165897/22a6edc7-202c-47e3-a69d-b46d4b0d9b58">

but when I use `if (context.mounted) {`, there is no warning

<img width="634" alt="截屏2023-07-29 00 15 57" src="https://github.com/flutter/flutter/assets/26165897/71febcc2-229a-4d0c-808f-077bc2a92e64">

### Expected results

no warning

### Actual results

warning

### Code sample

<details><summary>Code sample</summary>

```dart
const String splashPage = "/";

class SplashPage extends StatelessWidget {
  const SplashPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    WidgetsBinding.instance.addPostFrameCallback((timeStamp) async {
      ScreenSize.init(context);
      await Db.init();
      var sysPref = await SysPrefProvider().select();
      if (!context.mounted) {
        return;
      }
      if (sysPref != null && sysPref.theme != null) {
        var themeProvider = Provider.of<ThemeProvider>(context);
        switch (sysPref.theme) {
          case dbThemeLight:
            themeProvider.themeMode = ThemeMode.light;
            break;
          case dbThemeDark:
            themeProvider.themeMode = ThemeMode.dark;
            break;
          default:
            themeProvider.themeMode = ThemeMode.system;
        }
      }
      if (sysPref == null || sysPref.token == null) {
        debugPrint("There is no sys pref info, will redirect to login");
        Navigator.of(context).pushNamedAndRemoveUntil(loginPage, (_) => false);
      } else {
        debugPrint("Find auth info, will redirect to home page");
        Api.token = sysPref.token!;
        Navigator.of(context).pushNamedAndRemoveUntil(homePage, (_) => false);
      }
    });
    return Container();
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.6, on macOS 12.6.2 21G320 darwin-arm64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.3)
[✓] Proxy Configuration
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @SELiOTe 
Since this is coming from dart-linter package, it seems related / similar to https://github.com/dart-lang/linter/issues/4007 which has been fixed recently so you can take a look at it and confirm. If you have any further issues, you may open the issue in dedicated repo.
Closing from here.
