### ISSUE TITLE
License duplicates

### ISSUE THREAD

**Issue by JFixby** [flutter/flutter#13144]
The ```AboutListTile``` class that provides list of all licenses used by an app contains a lot of duplicates.

The class is located here: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/about.dart

Please remove the duplicating entries.

**Comment by Hixie** [comment]
What are the duplicates?

**Comment by JFixby** [comment]
I'm sorry I just checked again and there are no duplicates.

Basically it looks like the same license is present multiple times, but in fact there are some minor differences making it technically different documents.
