### ISSUE TITLE
TextField style must be titleMedium and has no way be separated from that in theme configuration

### ISSUE THREAD

**Issue by MilesAdamson** [flutter/flutter#131424]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Use every text style input to input decoration. None effect the users input text. That comes from titleMedium only.

### Expected results

`style` of Textfield can be configured via theme without changing `titleMedium`

### Actual results

The only way to change `style` of Textfield user input text is to provide it in every single instance of `TextField`, or modify titleMedium

### Code sample

<details><summary>Code sample</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        textTheme: TextTheme(
          titleMedium: TextStyle(
            color: Colors.blue,
          ),
        ),
        inputDecorationTheme: const InputDecorationTheme(
          labelStyle: TextStyle(color: Colors.red),
          floatingLabelStyle: TextStyle(color: Colors.red),
          helperStyle: TextStyle(color: Colors.red),
          prefixStyle: TextStyle(color: Colors.red),
          counterStyle: TextStyle(color: Colors.red),
          suffixStyle: TextStyle(color: Colors.red),
          hintStyle: TextStyle(color: Colors.red),
          errorStyle: TextStyle(color: Colors.red),
        ),
      ),
      home: const Scaffold(
        body: Center(
          child: Padding(
            padding: EdgeInsets.all(32.0),
            child: TextField(
              decoration: InputDecoration(
                labelText: "label",
                counterText: "1/3",
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![Screenshot_20230727_111436.jpg](https://github.com/flutter/flutter/assets/29047682/18c5ca0e-4b44-4f38-8039-5778430f87b8)

</details>

**Comment by huycozy** [comment]
Thanks for the report! This is a known proposal being tracked at https://github.com/flutter/flutter/issues/118267. Closing this in favor of that issue, so please follow up on it for further updates. 

You can leave there your case above that will help keep the issue updated and more diverse in use cases. Thank you!
