### ISSUE TITLE
XCode 15 Beta 5 with Application Extension Fails to Compile

### ISSUE THREAD

**Issue by bobby-beckmann** [flutter/flutter#131586]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Start with default empty project
2. In X-Code, add in Blank Notification Service (Target-> + -> Notification Service)
3. Build

### Expected results

Running Flutter app

### Actual results

Error: Cycle inside Runner; building could produce unreliable results.\nCycle details:\n→ Target 'Runner': ExtractAppIntentsMetadata\n○ Target 'Runner' has copy command from...

Entire output log attached. 
[output.log](https://github.com/flutter/flutter/files/12210944/output.log)

### Code sample

None needed. Use default flutter code. Sample Repo here: https://github.com/bobby-beckmann/FlutterTest

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

[output.log](https://github.com/flutter/flutter/files/12210946/output.log)

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4 22F66 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.80.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by bobby-beckmann** [comment]
I confirmed that this works. Also, appears to work in XCode 14.

**Comment by huycozy** [comment]
Thanks for confirming. This seems to be XCode beta's issue so I'll close the issue as resolved.
