### ISSUE TITLE
[Proposal] Adding scene view to flutter 

### ISSUE THREAD

**Issue by EiTaNBaRiBoA** [flutter/flutter#131546]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I've been experimenting with 3D in Flutter, and I've previously used Unity3D for creating VR/AR Apps and Games. One of the major challenges with 3D or world design is accurately placing objects without having to wait for a hot reload or enlarging the codebase, particularly when it comes to colliders. VR/AR development becomes incredibly difficult when managing the XYZ coordinates and trying to visualize the position of all objects without altering the camera perspective in the code. This proves to be an extremely challenging task.

### Proposal

Hello, I'd like to propose a feature: the addition of a scene view similar to Unity/Godot. This would allow us to drag and move objects to different locations, enabling a more flexible and efficient design process for world-building and app development. It could significantly streamline the development of 3D games and XR apps.

**Key Benefits of an Editor Scene View:**
1. It simplifies the creation of VR/AR apps in a 3D environment.
2. When working with 2D games, there's no need for an additional third-party app to set up colliders or view your entire map. This is crucial for understanding your world spatially and for effective level design.

**Other Advantages of an Editor Scene View:**
1. Navigation: Scene view allows for easy navigation of your scene in 3D or 2D space. You can pan, zoom, and orbit around your scene from any perspective.
2. Selection & Manipulation: You can select game objects directly in the scene view and adjust their position, rotation, and scale using the transform tools.
3. Debugging: Scene view enables real-time inspection and manipulation of your game, which is particularly beneficial for debugging.
4. Component Visualization: Many components and systems provide visual feedback in the scene view, aiding in adjustments.
5. Prefab Editing: With the prefab mode, you can edit your prefabs directly in the scene view.
6. Gizmos and Icons: Scene view provides gizmos and icons to represent non-visible objects, simplifying their management.
7. Terrain Editing: Scene view includes a suite of terrain editing tools for 3D games, allowing direct terrain manipulation.

**Summary** 
An editor scene view could increase development speed and boost Flutter's popularity within the game dev and VR/AR communities.

**Comment by huycozy** [comment]
Hi @EiTaNBaRiBoA 
There is already a similar proposal for this (API level) https://github.com/flutter/flutter/issues/58145. If I understand correctly, the scene view you are suggesting, along with functionalities: prefab, terrains, camera, gizmos, etc should be closely related.

So I will close this issue in favor of #58145. Please leave there your comment with all information above that will help solidify the issue. Thank you!
