### ISSUE TITLE
Newly created targets fail to get scheduled

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#131501]
Two new targets were recently enabled via: https://github.com/flutter/flutter/pull/131441
<img width="82" alt="Screenshot 2023-07-28 at 11 26 33 AM" src="https://github.com/flutter/flutter/assets/54558023/fbdd135a-60a4-4a35-9292-864d6b1441ad">

7 more commits have been landed since then, but the oldest tasks are still hanging as `In Progress`, and newer ones stay `New`.

Possible culprit is the oldest tasks were scheduled before the roller rolling the new target configs to LUCI, and newer ones fail to get back filled due to existing `In Progress` tasks from the initial commit.

**Comment by ricardoamador** [comment]
cc @zanderso Here is one of the tracking issues you saw and reported here: https://github.com/flutter/flutter/issues/131894. The targets that were failing to get scheduled are due to the ci.yaml autoroller and whether commits were updated to TOT or not.

**Comment by ricardoamador** [comment]
Depends on https://github.com/flutter/flutter/issues/112127
and https://github.com/flutter/flutter/issues/127063

**Comment by yusuf-goog** [comment]
@ricardoamador are you working on this issue? Or do you need me to look at something?

**Comment by ricardoamador** [comment]
I am working on it. https://github.com/flutter/cocoon/pull/2981

**Comment by keyonghan** [comment]
Note from rotation: we want to skip backfilling for `docs` target.

**Comment by keyonghan** [comment]
https://github.com/flutter/flutter/issues/131501 to skip docs.

**Comment by ricardoamador** [comment]
@keyonghan you linked this issue to itself so I just need to know which docs tasks need to be skipped:

Linux docs_publish
Linux docs_test
Linux docs_deploy_beta
Linux docs_deploy_stable

All or a subset of these?

**Comment by keyonghan** [comment]
Sorry I meant this PR: https://github.com/flutter/flutter/pull/132510

**Comment by ricardoamador** [comment]
https://github.com/flutter/flutter/issues/112127 has had a fix applied.

**Comment by ricardoamador** [comment]
We will need to monitor the ci.yaml roller for the next couple of days.

**Comment by gaaclarke** [comment]
What is the guidance for people that run into this issue?  It seems there is a workaround that requires notifying the infra team.  Do you want us to just file issues to communicate this?

**Comment by ricardoamador** [comment]
Yes. Please open an issue on the ticket queue if you believe this to be happening.

**Comment by ricardoamador** [comment]
https://github.com/flutter/flutter/issues/134951
This was a result of extenuating circumstances but was related. In this case an outage and re-trigger caused the jobs to become stuck.
