### ISSUE TITLE
[image_picker] Please preserve original filename of picked photos/videos

### ISSUE THREAD

**Issue by lukehutch** [flutter/flutter#131513]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I need to get the age of a photo, and because of bug #131324, I can't get it from the EXIF data if the photo comes from Google Photos. The filename of a photo often contains the date, however (at least on Android).

Currently `image_picker` copies the picked image/video to a temporary file, with a new random filename. This loses date information.

### Proposal

Can you please keep the original filename of picked photos/videos, and just append a suffix after the basename and before the extension, if necessary to keep the filename unique?

**Comment by huycozy** [comment]
Thanks for the report! 

This is a known issue being tracked at https://github.com/flutter/flutter/issues/64685. Closing this issue as a duplicate, so please follow up on it for further updates.
