### ISSUE TITLE
Can't type into terminal after detaching from app after `flutter attach`

### ISSUE THREAD

**Issue by eliasyishak** [flutter/flutter#131511]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

This was found on the master channel

1. Create a new flutter app `flutter create my_test` and `cd` into directory
2. From the terminal, run `open ios/Runner.xcworkspace` (should open Xcode) per [instructions](https://docs.flutter.dev/deployment/ios#review-xcode-project-settings) – I ran my app in an iPhone 13 Pro simulator
4. After app is running on a simulator, open a new terminal window in the `my_test` directory and run `flutter attach` – if prompted with multiple devices, select your device; for me it automatically connected to the iPhone 13 Pro simulator since that was the only device
5. Confirm that you are attached by incrementing the counter app and hot restarting by pressing `R` in the terminal
6. Close out of the `flutter attach` session by either pressing `q` or `d` (detach)
7. Attempt to write in the terminal again to run any command

### Expected results

The text you are typing in step 7 should show up in the terminal UI

### Actual results

No text is appearing in the terminal...  opening a new terminal tab or new window resets the behavior and allows me to type

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
eliasyishak-macbookpro:issue_130623 eliasyishak$ flutter doctor -v
[!] Flutter (Channel master, 3.13.0-12.0.pre.6, on macOS 13.4.1 22F82 darwin-arm64, locale en)
    • Flutter version 3.13.0-12.0.pre.6 on channel master at /Users/eliasyishak/Desktop/flutter
    ! Upstream repository https://github.com/eliasyishak/flutter.git is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to https://github.com/eliasyishak/flutter.git to dismiss this error.
    • Framework revision e4ce8e0597 (7 hours ago), 2023-07-28 09:36:59 -0400
    • Engine revision e97014c710
    • Dart version 3.2.0 (build 3.2.0-11.0.dev)
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/eliasyishak/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.3)
    • IntelliJ at /Users/eliasyishak/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9161.38/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • iPhone 13 Pro (mobile) • 646FAB1E-3AA9-4962-B9D1-533B3F46D67F • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.4.1 22F82 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 115.0.5790.114

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by christopherfujino** [comment]
I fixed a similar bug. When we start up the hot_runner, we change the terminal input mode. There is certain logic to set this back BEFORE the tool exits and returns the user to the shell. I know we do this when the user hits `q` or the user sends a SIGINT signal to kill the process. I'm guessing we forgot to implement this for `d`?

**Comment by eliasyishak** [comment]
> I know we do this when the user hits `q`

Hmm exiting from `flutter attach` with `q` works for you? Both `q` and `d` result in this issue for me on my mac

**Comment by christopherfujino** [comment]
ok, i'm gonna investigate :)

**Comment by christopherfujino** [comment]
The fix I introduced for the `flutter run` flow was to introduce a `finally` block that always restored the terminal mode: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/run.dart#L771

I'll do similar for flutter attach
