### ISSUE TITLE
[camera] Is it possible to wait until the paused state to release camera resources, instead of the inactive state?

### ISSUE THREAD

**Issue by andynewman10** [flutter/flutter#131558]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a new Flutter project. I use Flutter 3.10.6 and VS Code ('Flutter: New Project' then 'Application' template)
2. Add `camera: ^0.10.5+2` and `camera_android_camerax: ^0.5.0+11` in the dependencies section of pubspec.yaml
3. Implement some basic camera functionality, in some basic page. Some simple camera preview will be sufficient.
4. Override didChangeAppLifecycleState as described in the official camera package documentation:
```dart
@override
void didChangeAppLifecycleState(AppLifecycleState state) {
  print(state); // for debugging
  final CameraController? cameraController = controller;

  // App state changed before we got the chance to initialize.
  if (cameraController == null || !cameraController.value.isInitialized) {
    return;
  }

  if (state == AppLifecycleState.inactive) {
    cameraController.dispose();
  } else if (state == AppLifecycleState.resumed) {
    _initializeCameraController(cameraController.description);
  }
}
```
5. Run application on Android, then on iOS.

### Expected results

As I understand in the documentation regarding [lifecycle managment](https://pub.dev/packages/camera#handling-lifecycle-states), camera resources are to be released when the page hosting the camera controller goes to the background, and the camera controller should be recreated then the page is resumed.

On Android 7.1.1 on my Sony Z5 Compact:

When you press the home button to place the application in the background, the following happens:

- the application goes to the `inactive` state
- the application goes to the `paused` state

When you bring back the application to the foreground, the following happens:

- the application goes to the `resumed` state

On iOS 16.4.1 on my iPhone 8:

When you press the home button to place the application in the background, the following happens:

- the application goes to the `inactive` state
- the application goes to the `paused` state

When you bring back the application to the foreground, the following happens:

- the application goes to the `inactive` state // note this difference here
- the application goes to the `resumed` state

The code proposed in the camera plugin page works fine because, even though it releases the camera controller when entering the inactive (not the paused) state, the following block of code:

```
  if (cameraController == null || !cameraController.value.isInitialized) {
    return;
  }
```
makes sure that, on iOS, things don't get released another time when the page goes back into the foreground and the controller is already disposed.

### Actual results

Wouldn't it be more simple to just release the camera controller when entering the `paused` state, instead of the `inactive` state? Is there any rationale behind the fact that the controller is released during the inactive state? Is this absolutely required to not wait the paused state to release it?

### Code sample

<details><summary>Code sample</summary>

```dart
@override
void didChangeAppLifecycleState(AppLifecycleState state) {
  print(state); // for debugging
  final CameraController? cameraController = controller;

  // App state changed before we got the chance to initialize.
  if (cameraController == null || !cameraController.value.isInitialized) {
    return;
  }

  if (state == AppLifecycleState.inactive) {
    cameraController.dispose();
  } else if (state == AppLifecycleState.resumed) {
    _initializeCameraController(cameraController.description);
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [version 10.0.22000.2176], locale fr-FR)
    • Flutter version 3.10.6 on channel stable at C:\Users\andy\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (2 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\andy\AppData\Local\Android\sdk
    • Platform android-33, build-tools 34.0.0
    • Java binary at: C:\Users\andy\Documents\Applications\android-studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.0.31919.166
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Users\andy\Documents\Applications\android-studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at C:\Users\andy\Documents\Applications\IntelliJ
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.80.2)
    • VS Code at C:\Users\andy\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.68.0

[√] Connected device (4 available)
    • E5823 (mobile)    • CB5A28LMYH • android-arm64  • Android 7.1.1 (API 25)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [version 10.0.22000.2176]
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 115.0.5790.110
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 115.0.1901.183

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @andynewman10, you are free to handle it however you want. 
The documentation was demonstrating an example of how to handle the lifecycle changes.

Do bear in mind that the camera is resource heavy so it's best to release the resource when it is not being used. See https://api.flutter.dev/flutter/dart-ui/AppLifecycleState.html, notice that for inactive, it states `Apps in this state should assume that they may be [paused](https://api.flutter.dev/flutter/dart-ui/AppLifecycleState.html) at any time.`. 

This means that there's a chance that it may not enter the `paused` when it goes into inactive.  For instance, if you just open the app switcher, the app goes into inactive, but it never goes into pause (at least not as immediately as it does when the app is put in the background), however, in that state, the camera is not really being used so there's no need to hold on to the resource. This isn't a scenario you're likely to meet in real-world usage of an app so you can probably ignore it, but it is best to not hold on to a resource no longer than it is required.

Does this answer your question?

**Comment by andynewman10** [comment]
Yes it does, many thanks for your reply and detailed explanation.

Just one final comment - I am free to do it however I want, but I have to free resources - it is mandatory, right? If I don't, as stated in the doc, I may experience https://github.com/flutter/flutter/issues/39109.

Unless I am mistaken, I understand that the camera's internal resources may be disposed when my app goes to the background because, for instance, the system decides to free some resources for another application to run. When my app is resumed, the exception mentionned in https://github.com/flutter/flutter/issues/39109 may happen because the camera's implementation does not automatically reallocates these disposed resources. To work around this issue, as stated in the documentation, I can free the resources as soon as I can (eg. during `inactive`), and reallocate them during `resumed`.

Thanks again for your explanations.
