### ISSUE TITLE
[CP] Revert removal of waitUntilScheduled in iOS impeller backend.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#131523]
### Issue Link

https://github.com/flutter/flutter/issues/131490

### Commit Hash

 df253d9 

### Target

stable

### PR Link

flutter-3.13-candidate.0

### Changelog Description

Impeller - Ensure that all metal command buffers have been scheduled before presenting on iOS

### Impacted Users

Impeller iOS users

### Impact Description

Some visual elements may not show up.

### Workaround

There is no work around.

### Risk

low

### Test Coverage

yes

### Validation Steps

Run the application linked in https://github.com/flutter/flutter/issues/131490

**Comment by jonahwilliams** [comment]
@chinmaygarde

**Comment by chinmaygarde** [comment]
lgtm

**Comment by jonahwilliams** [comment]
CP is https://github.com/flutter/engine/pull/44122

**Comment by jonahwilliams** [comment]
I made a mistake filling this CP request, I think it should be merge to beta (3.13) not the last stable.

**Comment by XilaiZhang** [comment]
> I made a mistake filling this CP request, I think it should be merge to beta (3.13) not the last stable.

very helpful information, thanks for clarifying Jonah!
