### ISSUE TITLE
Incorrect Description for FAB Example

### ISSUE THREAD

**Issue by zayKenyon** [flutter/flutter#131575]
### Document Link

https://api.flutter.dev/flutter/material/FloatingActionButton-class.html

### What problem are you solving?

Under the [FAB Class docs](https://api.flutter.dev/flutter/material/FloatingActionButton-class.html), the description for the first example describes the second example.

```diff
[line 55] /// This example shows how to display a [FloatingActionButton] in a
- [line 56] /// [Scaffold], with a pink [backgroundColor] and a thumbs up [Icon].
+ [line 56] /// [Scaffold], with a green [backgroundColor] and a navigation [Icon].
```

**Comment by dam-ease** [comment]
Hi @zayKenyon. Thanks for filing this. I can see this issue in the docs but this seems to have been fixed in the master API docs which has different examples. Closing this as fixed. 
Thank you!
