### ISSUE TITLE
Issue from website page 基础 Widgets  Why is it 404 every time I click

### ISSUE THREAD

**Issue by JuYiYang** [flutter/flutter#131536]
From URL: https://www.flutterchina.club/widgets/basics.md
Why is every widget document I click on a 404? That doesn't make sense.

**Comment by AmosHuKe** [comment]
这是中文站
https://flutter.cn/docs/ui/widgets

**Comment by JuYiYang** [comment]
ok thank you

 

> 
ok thank you~
