### ISSUE TITLE
measure the time from `flutter run` to first frame

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#13156]
We should add a benchmark that measures the time between the beginning of `flutter run` and the first frame rendered on the device. We should probably also measure the second iteration of the same sequence of commands to measure the same time but with warm cache (i.e. non-empty `build/` directory).

These metrics are important for developer experience.

**Comment by zanderso** [comment]
Does this benchmark exist? @jonahwilliams

**Comment by jonahwilliams** [comment]
We don't measure this through benchmarks, but it is measured via analytics - it is the value I asked about for the --fast-start features.

**Comment by yjbanov** [comment]
I guess that's good enough then.
