### ISSUE TITLE
[Impeller] Audit existing shaders to see if there are opportunities to avoid uniform computation.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#131518]
We patched the solid color, glyph atlas, and texture shaders in https://github.com/flutter/engine/pull/43838 to avoid uniform computation by using the varying unit for performance considerations. This issue just tracks if we there are remaining shaders we can patch to avoid uniform computation.

**Comment by chinmaygarde** [comment]
Just a followup from the Impeller weekly. I think @jonahwilliams has already patched the ones we know can avoid uniform computation. Is that right? We can close this issue if so.

**Comment by jonahwilliams** [comment]
Uniform computation includes reading data from a UBO, so there isn't much we can do to avoid this. For now lets close.

**Comment by chinmaygarde** [comment]
Sounds good. We can revive @gaaclarke s patch to use push constants at a later time if needed.
