### ISSUE TITLE
[Impeller] Wire up Android GPU usage tracking on CI.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#131526]
Today, we use the raster thread time to approximate how much work we may be doing on the GPU. But very often, this isn't a very useful approximation as the only way to know we are bottlenecked on the GPU is to notice the backpressure on the CPU and then go use vendor specific tools like ARM Streamline or Android GPU Inspector.

From the the weekly sync, some ways of address this discussed were:
* Wire up GPU performance counters capture from AGI.
* Wire up ARM Performance Advisor reports for common benchmarks like the "gallery transitions" or "complex layout".
  * This does require setting up orchestration between Flutter Tool and the ARM CLI for Performance Advisor. @gaaclarke suggested setting up a self driving test instead of making the two tools aware of one another.

There was a clear concensus on direction on how to set this up in CI. But a playbook on how to capture counters or get a Performance Advisor report locally should be a good first step.

**Comment by chinmaygarde** [comment]
cc @dnfield @gaaclarke @jonahwilliams @bdero based on discussion during the weekly. Just a stub for now but I'm going to try to setup and ARM Performance Advisor capture locally to see how it goes.

**Comment by jonahwilliams** [comment]
Fixed with https://github.com/flutter/flutter/issues/136493
