### ISSUE TITLE
[Impeller] Fix iOS/macOS presentation to avoid blocking on final cmd buffer schedule.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#131520]
### Background

In https://github.com/flutter/engine/pull/42160 I removed the final command buffer schedule as we observed no problems with this on common scenarios. Unfortunately @knopp discovered  that this isn't always valid. For now, lets revert to make sure things are still working. That said, there is definitely some room for improvement here:

### Overview

Impeller unconditionally sets [`presentsWithTransaction`](https://developer.apple.com/documentation/quartzcore/cametallayer/1478157-presentswithtransaction?language=objc) to true. From the documentation:

> Setting this value to YES makes the layer draw its contents synchronously, using whichever Core Animation transaction is current at the time you call the drawable’s [present](https://developer.apple.com/documentation/metal/mtldrawable/1470284-present?language=objc) method. To ensure that a transaction is available when you schedule the drawable to be presented, first commit the command buffer containing your Metal rendering commands. Then, call its [waitUntilScheduled](https://developer.apple.com/documentation/metal/mtlcommandbuffer/1443036-waituntilscheduled?language=objc) method to synchronously wait until the command queue schedules the command buffer to execute on the GPU. Finally, call the drawable’s present method.

Removing the [`waitUntilScheduled`] call appeared to work because the applications we tested on weren't under enough load. The application in https://github.com/flutter/flutter/issues/131490#issuecomment-1656196584 is much, much heavier.

### So what is happening?

Some of the UI isn't showing up, if I were to guess I would say that some % of the cmd buffers aren't scheduled and are simply getting dropped by CA. That would imply there are two ways to fix it:

1. Add back the waitUntilScheduled. This was reported to work and confirmed by me. Doing so follows the documention above as well.

2. Set presentsWithTransaction to `NO`. This is confirmed by me to work locally, though using a slightly different `[command_buffer presentDrawable:drawable_];` technique. 

We require presentsWithTransaction to be enabled when presenting with platform views in the scene. Previously we switched from conditionally presenting with transaction to unconditionally presenting in https://github.com/flutter/engine/pull/41501 . We can't opt out of this unless we fixed the issue.

**Comment by jonahwilliams** [comment]
If we could figure out how to toggle in and out of presentsWithTransaction correctly, then we could also conditionally waitUntilScheduled based on whether or not there was a transaction pending. That might be worthwhile but needs to be studied.

**Comment by knopp** [comment]
There is one more issue to tackle here. While disabling `presentWithTransaction` helps with the flicker (which does look lik  CA dropping command buffers), the application crashes when entering background while with the following assertion:
```
-[MTLDebugCommandBuffer dealloc]:136: failed assertion `MTLCommandBuffer is in an invalid status when being destroyed; is it being over-released?'
(lldb) 
```
This is reproducible with the example, flick to scroll and then immediately enter background.

**Comment by jonahwilliams** [comment]
Yeah, will look at that one on Monday. Its _probably_ just an over-release issue which shouldn't be too hard to track down...

**Comment by jonahwilliams** [comment]
@knopp do you mean that the application on ToT is currently failing with that assertion, or with presentsWithTransaction disabled is failing with that assertion?

**Comment by knopp** [comment]
The application is triggering the assertion with `presentsWithTransaction` disabled.

**Comment by jonahwilliams** [comment]
Marking this back to P3. Making this optional would require a lot more work in frame scheduling and there have been some reports that without the presentsWithTransaction, Flutter performs much worse on high frame rate devices.

**Comment by jonahwilliams** [comment]
We're no longer unconditionally presenting with a transaction, so this is potentially viable now. I'll investigate if this works with the example app provided with the original bug.
