### ISSUE TITLE
[Impeller] Improve performance of CA transaction synchronization when there are multiple layers.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#131577]
See also https://github.com/flutter/flutter/issues/131577 .

iOS/macOS Impeller backends currently rely on a CA transaction happening on the raster thread to correctly sychronize presentation. Because of this implicit synchronization, no layer can call presentDrawable until we're sure that all command buffers have been scheduled.

For the single layer case, this is easy to accomplish with a call to [waitUntilScheduled] on the last command buffer. When there are multiple layers, due to the presence of platform views, this is uneccessarily pessimistic:

1 . Because the layers are processed in order on the raster thread, the first layer's waitUntilScheduled will delay both the platform view workload and the second layers workload.
2. One of the layers is almost certainly completely empty, and there is no need to waitUntilScheduled at all.

Note that even on a phone that is under very mild load, waitUntilScheduled will take ~1ms as it requires CPU-GPU synchronization.

These facts lead to two obvious improvements that can be made here:
1. Avoid the waitUntilScheduled if no entities or commands were processed - that is, everything was culled out.
2. Harder: rather than blocking on waitUntilScheduled in submit, add a scheduledHandler to the final cmd buffer of each layer. Then block at the "end" of the frame. This requires some significant reworking of the Surface API, specifically present which would need to be broken into two methods.

**Comment by jonahwilliams** [comment]
Another small optimization: we could use an atomic and addScheduled callbacks to see if we've already scheduled the last real command buffer by the time we get to submit, then skip the whole thinig.

**Comment by knopp** [comment]
I don't think this can be done without splitting Present. It's all a bit messy on iOS. Much nicer on macOS where there is only one flow to present (regardless of number layers), and`waitUntilScheduled` is called independent of surfaces just once  right before presenting.

I would expect things to improve once migrated to embedder API, but that's probably too far off.

**Comment by jonahwilliams** [comment]
This is (basically) fixed now that we've split encode and present.
