### ISSUE TITLE
Flutter Running Library Custom

### ISSUE THREAD

**Issue by ac169** [flutter/flutter#131596]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

1. Does the Flutter runtime support the static compilation in the target application of the binary file, especially does the X86 platform support it?

2. Whether the Flutter runtime and its target application support, customize the operating library name, stored directory name, etc. After all, the directory structure, naming rules or developers' habits of each platform application are different. It's weird to get up! For example: flutter_windows.dll app.so on the Windows platform is not in line with habit

### Proposal

1. The Flutter Running Library supports static compilation in the target application binary file

2. Flutter Running Library and its genetic target application support, customized operating library name, storage directory name, etc.

**Comment by darshankawar** [comment]
@ac169 
Can you give us a practical use case that helps to properly understand the proposal you posted ?
