### ISSUE TITLE
ERROR: JAVA_HOME is set to an invalid directory

### ISSUE THREAD

**Issue by sumanta-ghosh** [flutter/flutter#13154]
JAVA_HOME is set properly but still, I face the issue that JAVA_HOME is setup invalid directory.
This is my PowerShell output:
![image](https://user-images.githubusercontent.com/2699051/33146522-7d77bb9c-cfea-11e7-9db9-4fa330f1db3d.png)

**Comment by Hixie** [comment]
Always look at the first error message, not the last. The first is about licenses.
Run `flutter doctor` for more details.

**Comment by yash365** [comment]
i changed the JAVA_HOME variable to value C:\Program Files\Android\Android Studio\jre in Environment Variables

**Comment by MichaelOttink** [comment]
> i changed the JAVA_HOME variable to value C:\Program Files\Android\Android Studio\jre in Environment Variables and it solve the above mentioned error

Yeah this worked for me! Thanks

**Comment by Adrian98do** [comment]
> i changed the JAVA_HOME variable to value C:\Program Files\Android\Android Studio\jre in Environment Variables and it solve the above mentioned error

This worked for me to, thanks!

**Comment by AleksandarSavic95** [comment]
If You are on Linux, just update Your `~/.bashrc` (or other shell config) file by adding this line at the end:
```
JAVA_HOME=/usr/local/android-studio/jre
```
**Note:** I installed Android studio by following the [official installation guide for Linux (link)](https://developer.android.com/studio/install#linux).


Then, run `flutter doctor --android-licenses` and press `y` to review the licences which are not accepted.
Press `y` for each of the licences. It will ask `Accept? (y/N):` at the end of the license file.
After You accept all unaccepted licences, You should see:
```
All SDK package licenses accepted
```

**Comment by BenjaminVanIseghem** [comment]
I have the same error but there is no JAVA_HOME variable in my System Environment Variables and when I try to set the variable using cmd, nothing happens.
Any thoughts where I can change this variable?

The issue started when I uninstalled android studio and reinstalled it at the default location. The JAVA_HOME variable still points to the old location

**Comment by nishant-kant-ojha** [comment]
> 
> 
> > i changed the JAVA_HOME variable to value C:\Program Files\Android\Android Studio\jre in Environment Variables and it solve the above mentioned error
> 
> Yeah this worked for me! Thanks



> 
> 
> i changed the JAVA_HOME variable to value C:\Program Files\Android\Android Studio\jre in Environment Variables and it solve the above mentioned error

thanx! this help me too

**Comment by kcbaruri** [comment]
My problem was resolved by setting JAVA_HOME variable to C:\Program Files\Android\Android Studio\jre
