### ISSUE TITLE
[Impeller] Relax restriction on render target textures being the exact same size as the render pass.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#131516]
This might allow us to achieve greater re-use of render target textures when accessing the textures from a persistent pool (tracked in https://github.com/flutter/flutter/issues/131515).

**Comment by chinmaygarde** [comment]
Followup from the Impeller weekly notes. @jonahwilliams mentioned that this doesn't work today but may be possible with little effort. For now, this is a lower priority task though.

**Comment by jonahwilliams** [comment]
I'm not sure if it works or not. I think for the most part we assume the size in the descriptor is the intended size. If the implementation of pooling uses new texture descriptors then fingers crossed it just might work.

**Comment by chinmaygarde** [comment]
I am pretty sure I've added a validation log for this. Perhaps overzealously.

**Comment by jonahwilliams** [comment]
I've looked into this more and I do not think there is a reasonable way to do this without aliasing memory. That has some additional caveats that I don't think will be worthwhile.
