### ISSUE TITLE
[Impeller] Grey scrim doesn't render in wonderous menu on beta 3.13

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#131576]
![flutter_01](https://github.com/flutter/flutter/assets/8975114/c246ea8d-aed5-4385-9d43-b3b40d9e5a1e)

This should be slightly grey, but as soon as the blur is added the grey disappears. If I had to guess, I would say this is the clear color optimization misfiring.

**Comment by jonahwilliams** [comment]
The scrim also doesn't render on the artifact discovery popup.

**Comment by jonahwilliams** [comment]
Disabling the clear color optimiation fixes this. FYI @gaaclarke

**Comment by gaaclarke** [comment]
I'm still looking into this, what I've seen so far isn't clear where the elimination of solid fills can cause this difference.  It isn't clear where the darkening of the pixels is happening.

## Texture Fill: Subpass

In the "Texture Fill: Subpass" with the clear color optimization we can see that the pixels are lighter than with the optimization off.  Presumably, the darker pixels is the correct rendering.

### with clear color optimization

<img width="1075" alt="Screenshot 2023-07-31 at 2 18 26 PM" src="https://github.com/flutter/flutter/assets/30870216/ec0ffceb-19bf-47ac-a90f-ba9087695dcb">


### without clear color optimization
<img width="837" alt="Screenshot 2023-07-31 at 2 14 13 PM" src="https://github.com/flutter/flutter/assets/30870216/074926a5-c052-46a5-9887-03f37b91139c">

## Subpass

If we look at the subpasses that proceed the texture fills, the output looks identical in both cases.  It is weird that there is a solid fill missing after the "Texture Fill".  The clear color optimization should only be stripping off solid fills from the beginning of a pass.

### with clear color optimization
<img width="815" alt="Screenshot 2023-07-31 at 2 19 05 PM" src="https://github.com/flutter/flutter/assets/30870216/1c57df4e-7c1e-4304-bc44-7b7d856e2b77">

### without clear color optimization
<img width="810" alt="Screenshot 2023-07-31 at 2 22 20 PM" src="https://github.com/flutter/flutter/assets/30870216/1a38f264-0e22-4aab-a325-2990e47c7b59">

**Comment by jonahwilliams** [comment]
Yes, the darker color is the correct one.

**Comment by gaaclarke** [comment]
The following patch fixes the bug:
```diff
--- a/impeller/entity/entity_pass.cc
+++ b/impeller/entity/entity_pass.cc
@@ -748,7 +748,7 @@ bool EntityPass::OnRender(
     render_element(backdrop_entity);
   }
 
-  bool is_collapsing_clear_colors = true;
+  bool is_collapsing_clear_colors = !backdrop_filter_proc_;
   for (const auto& element : elements_) {
     // Skip elements that are incorporated into the clear color.
     if (!collapsed_parent_pass) {
```

The reason is that the `render_element(backdrop_entity)` is happening before the rest of the rendering, so the optimizations thinks we have a clean canvas to use the clear color, but we don't.
