### ISSUE TITLE
[!] CDN: trunk Repo update failed - 62 error(s): CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/a/d/d/GoogleMaps/1.10.0/GoogleMaps.podspec.json Response: Timeout was reached CDN: trunk URL couldn't be downloaded: https:/

### ISSUE THREAD

**Issue by tebalink** [flutter/flutter#131660]
[!] CDN: trunk Repo update failed - 62 error(s):
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/a/d/d/GoogleMaps/1.10.0/GoogleMaps.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/a/d/d/GoogleMaps/1.10.1/GoogleMaps.podspec.json Response: SSL connect error
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/a/d/d/GoogleMaps/1.10.2/GoogleMaps.podspec.json Response: SSL connect error

**Comment by darshankawar** [comment]
@tebalink 
It looks like an issue with network connection or internet speed or maybe in cocoapods. See [this](https://github.com/CocoaPods/CocoaPods/issues/10356) similar issue and check if it helps in your case.

Closing from here, as this isn't a bug in flutter framework.
