### ISSUE TITLE
[Impeller] Wire up GL_EXT_debug_printf for printf from shaders in Vulkan.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#131621]
This is a validation layer that we setup already. I suspect it just needs to be wired up. This may come in handy for development workflows where RenderDoc cannot be used (for some reason).

The steps to wire [this up are documented in here](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/ffa36443492cb8597337f21638bfbb8f5582e610/docs/debug_printf.md).

**Comment by codeFaheem** [comment]
I am interested in making a contribution, but I am new to this. Could you guide me on where to get started in order to resolve this issue?

**Comment by chinmaygarde** [comment]
We haven't needed to resort to this and we generally use shader debugger directly. So I am closing this as obsolete.
