### ISSUE TITLE
Testing in VSCode attributes the failure to random tests and lines, if failure happened in tearDownAll defined in other library.

### ISSUE THREAD

**Issue by polina-c** [flutter/flutter#131681]
Instead, it should be somehow clear that failure happened in tearDownAll.

https://github.com/flutter/flutter/assets/12115586/f24726ba-2ecb-4611-ba5a-32f31d1f6dc9

**Comment by darshankawar** [comment]
Thanks for the report @polina-c 
Keeping this issue open based on the report and error received.

**Comment by DanTup** [comment]
This is likely related to https://github.com/dart-lang/test/issues/1851. Right now we only have the location of the test that failed, but really we want the location of where that failure happened.

**Comment by goderbauer** [comment]
Removed the framework labels since this doesn't seem related to the Flutter framework. 

@DanTup Should this be transferred to the VSCode Flutter Plugin tracker?

**Comment by DanTup** [comment]
I thought this was essentially https://github.com/dart-lang/test/issues/1851, but looking again, I think there's a Dart-Code bug here that was slightly masked by the line number of the `tearDownAll` method in file2 being a location in the test in file1. It seems we're actually recording `tearDownAll` as being in file1 (the test file), yet using the correct line/col.

I've opened https://github.com/Dart-Code/Dart-Code/issues/4681 for this - I _think_ it should be a simple fix. I'll close this one in favour of that.
