### ISSUE TITLE
[CP] Made the clear optimization handle backdrop filters.

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#131686]
### Issue Link

https://github.com/flutter/flutter/issues/131576

### Commit Hash

b3df4d767c9d92d969032fead7ff992392832bd4

### Target

beta

### PR Link

https://github.com/flutter/engine/pull/44222

### Changelog Description

Fixes missing solid fills that happen after backdrop filters.

### Impacted Users

iOS users

### Impact Description

This would result in the wrong rendering in some cases when a backdrop filter was used.

### Workaround

None.

### Risk

low

### Test Coverage

yes

### Validation Steps

Tested on wonderous app.

**Comment by CaseyHillers** [comment]
@jason-simmons can you review this CP request? If it looks good to you, add the "cp: approved" label.
