### ISSUE TITLE
Machine mac-11 is detecting external iPhone device due to device does not exist in the provisioning profile.

### ISSUE THREAD

**Issue by kentnguyen99** [flutter/flutter#131615]
Machine mac-11 is detecting external iPhone device due to device does not exist in the provisioning profile.
<img width="1565" alt="Screenshot 2023-07-31 at 10 04 41 AM" src="https://github.com/flutter/flutter/assets/120754754/aa0449de-ce1a-43fd-8f00-43c57888c95f">

**Comment by kentnguyen99** [comment]
Hi @yusuf-goog, Will you take a look machine mac-11? Machine is not detecting external iPhone device due to profile doesn't exist in the provisioning profile.

**Comment by yusuf-goog** [comment]
mac-11 is now up and running
