### ISSUE TITLE
`./ci/format.sh | patch -p0` no longer guaranteed to work

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#131683]
The output from `./ci/format.sh` is no longer guaranteed to work when piped to the patch function.  This broke in the last couple of months and had worked for years before.

## steps to reproduce

1) apply this patch:
```diff
diff --git a/shell/common/shell.h b/shell/common/shell.h
index 2368933223..2228c56238 100644
--- a/shell/common/shell.h
+++ b/shell/common/shell.h
@@ -217,7 +217,7 @@ class Shell final : public PlatformView::Delegate,
   //------------------------------------------------------------------------------
   /// @return     The settings used to launch this shell.
   ///
-  const Settings& GetSettings() const override;
+  const Settings&                                  GetSettings() const override;
 
   //------------------------------------------------------------------------------
   /// @brief      If callers wish to interact directly with any shell
```

2) run `./ci/format.sh | patch -p0`
3) Notice that execution of the patch is interrupted with the prompt "File to patch:" instead of executing cleanly

**Comment by stuartmorgan** [comment]
Shouldn't that be `-p1`?

**Comment by gaaclarke** [comment]
> Shouldn't that be -p1?

The script always used to suggest `-p0`.

Looks like this was an intended breaking change in order to unify the tooling for windows: https://github.com/flutter/engine/pull/36123

**Comment by gaaclarke** [comment]
To be clear, the correct way to do this now should be: `./ci/format.sh | git apply`
