### ISSUE TITLE
[Impeller] Batch TextFrames for multi-line text

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#131620]
Right now if you write multiple lines of text with the same font, they end up as 2 different draw calls.  It would be more efficient to draw those line in one draw call.

<img width="1720" alt="Screenshot 2023-07-31 at 10 58 52 AM" src="https://github.com/flutter/flutter/assets/30870216/500412c0-dbdf-4aad-bfa9-02fd939c2b9b">

**Comment by jonahwilliams** [comment]
1. Is batching actually going to improve GPU performance? Vulkan/Metal should easily be able to handle 1000s of commands. And even in complex cases we seem to top out in hundreds.

2. Is this going to help CPU time? If so, is this due to extra time we're spending constructing command objects or allocating that could be made more efficient instead?

**Comment by gaaclarke** [comment]
Yes, it should improve GPU performance.  How much is hard to say.  When making a game a big part of gpu performance is trying to get as many batched draw calls as possible.

I'm not sure if we are making a glyph atlas per frame or per TextFrame.  If are currently doing an atlas per TextFrame, it will be more efficient having a TextFrame for the whole batch since letters that appear in multiple lines wont' be represented more than once.  More efficient packing leads to better performance too.

CPU time, I would expect it to be roughly the same amount of work.

**Comment by gaaclarke** [comment]
I measured this by rendering the text "Lorem ipsum dolor" horizontally (one TextFrame) and vertically (17 TextFrames) and profiling the frame capture.  The one TextFrame performed about 17x faster as expected.

## horizontal

![Screenshot (3)](https://github.com/flutter/flutter/assets/30870216/ad05c554-7cb9-462a-b0c2-4c8cffd1a530)

## vertical

![Screenshot (4)](https://github.com/flutter/flutter/assets/30870216/4356491e-4878-4672-8c08-ed25f222aa61)

**Comment by gaaclarke** [comment]
Here is a frame rendered of the Flutter gallery too.  Notice that we are spending about 5x time on the GPU versus the CPU so optimizing the GPU work makes sense even if it takes a couple of more CPU cycles.

<img width="933" alt="Screenshot 2023-08-10 at 2 08 43 PM" src="https://github.com/flutter/flutter/assets/30870216/b4fcf998-2b25-4e8c-a02b-82f4adc190d1">

**Comment by gaaclarke** [comment]
Every call to render a TextFrame also is binding a new descriptor set.  The vertex buffers will bet different between them, but the texture (the glyph atlas) will be the same.  It may be faster to use `vkUpdateDescriptorSets` to bind the new vertex data instead of binding a whole new descriptor set?  The `PassBindingsCache` is able to cache many things but descriptor sets is one thing it doesn't do.

**Comment by gaaclarke** [comment]
I tried to expand the `PassBindingsCache` to encompass the descriptor sets too so we could avoid rebinding them between calls of TextFrame like we do for other bindings.  The problem is that between multi lines of text the `Binding::vertex_binding`'s `BufferView`s are not the same.  They are pointing to the same `Buffer`, but their ranges are different and ranges are incorporated in the descriptor set, so it can't reuse the previous binding.

It will take some reworking to make PassBindingCache work with this.  I'm not sure that effort would be better spent batching the TextFrames at the higher level instead of the PassBindingsCache level.  I suspect it is.  PassBindingsCache would only make sense to pursue if it was an easy fix.

**Comment by gaaclarke** [comment]
If we are drawing with the same buffer each time we could also look into dynamic uniform buffers (https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdBindDescriptorSets.html).  Since rendering with the same descriptor set modulo the offset is somewhat extraordinary, I think that refactor would probably not be worth the effort.

**Comment by jonahwilliams** [comment]
From what I've read, it's recommended that the resources used by your shaders are actually split into multiple descriptor sets based on usage. For example, in the first descriptor set place resources used by all shaders. Then in the second, more common resources, and finally shader specific resources.

I don't think this pattern is easily adoptable for our rendering setup given that most bindings are unique. We could cheat a little bit with the glyph atlas and bind it to its own descriptor set, I'm not sure how much that would actually buy us though.

If it's easier to batch text frames, and the logic to do isn't too cumbersome, that seems like it would be a better approach?

**Comment by gaaclarke** [comment]
> If it's easier to batch text frames, and the logic to do isn't too cumbersome, that seems like it would be a better approach?

Yea, that's what I'm thinking too.  I was just hoping maybe there was something we could do at the `PassBindingsCache` layer to get 90% of the benefit for 10% the effort.

**Comment by gaaclarke** [comment]
I have a draft that is starting to do the batching: https://github.com/flutter/engine/pull/44656

The approach I'm taking is to have the Canvas store a pointer to the last TextContents it added to the RenderPass.  If when adding a new TextFrame if it's being painted with the same color, just add it to the existing TextContents.

I didn't have a chance to finish the job since I was running into some weird behavior with `TextContents::SetOffset` where it seemed to work fine for small numbers, but not large numbers.

I was able to verify that Gallery will hit and benefit from this.

One choice we had to make was to do the batching in the Display List Dispatcher or in the Canvas.  I opted for the Canvas since that was what we did for the clear color optimization too and it's easier to test at that level.

**Comment by jonahwilliams** [comment]
The text color is already stored per vertex I think, so we could actually combine multiple contents with different colors as long as we adjusted the Text contents API. That said, you'll need to avoid combining text contents that sample from a different atlas (full color like emoji vs alpha bitmap)

**Comment by jonahwilliams** [comment]
We don't actually need a new descriptor set per command - we can split each cmd up into multiple descriptor sets like a described. There is support for a "dyamic offsets", so all uniform buffer bindings can be the same.

**Comment by gaaclarke** [comment]
I've implemented the batching but I couldn't get it to show positive results in our benchmarks.  The batching had little to no effect in https://github.com/flutter/engine/pull/44814.

I'm guessing the cpu work offset gpu savings.
