### ISSUE TITLE
Add more detailed logging to clang-tidy CI step

### ISSUE THREAD

**Issue by eyebrowsoffire** [flutter/flutter#131689]
The flutter engine's `clang-tidy` step has been timing out fairly consistently. Unfortunately, the log doesn't give us enough information to know which task is stalled. We probably need to add some more info to the logs to better understand this issue, including:

* Timestamps on each log statement to understand timing better
* Log statements about when a job starts or stops

**Comment by zanderso** [comment]
@jason-simmons Added more detailed logging, but I haven't been able to find any instances of a timeout since the clang roll here https://github.com/flutter/engine/commit/b6d4384a6a18e448870e292c6ebfb40146b77689.

**Comment by chinmaygarde** [comment]
Closing as fixed in https://github.com/flutter/engine/pull/44228 and Jason says a new clang-roll (that may be having some trouble sticking it landing) should help as well.
