### ISSUE TITLE
[huawei] Text Widget containing Chinese characters does not seem to be vertically centered

### ISSUE THREAD

**Issue by ChannelYu** [flutter/flutter#131653]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I am building a simple text label with a background color. On my Huawei phone(P30 Pro), the text is not vertically centered, and the top spacing is wider than the bottom spacing.

Additionally, I conducted the same test on XIAOMI Note3 and iPhone 12 Pro devices, and the results appear to be right.

I wonder if this could be related to the system's default font? 

### Expected results

text containing Chinese characters should be vertically centered on huawei phone.

### Actual results

top spacing is wider than the bottom spacing.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MaterialApp(home: MainContent()));

class MainContent extends StatefulWidget {
  const MainContent({super.key});

  @override
  State<MainContent> createState() => _MainContentState();
}

class _MainContentState extends State<MainContent> {
  var texts = ['ABCDFG', 'ABCDEF哈哈', '哈哈'];
  var selectedIdx = 0;

  @override
  Widget build(BuildContext context) => Scaffold(
    appBar: AppBar(title: const Text('haha')),
    floatingActionButton: FloatingActionButton(
      onPressed: onPressed,
      child: const Icon(Icons.refresh),
    ),
    body: Center(
      child: Container(
        color: Colors.blue,
        child: Text(
          texts[selectedIdx],
          style: const TextStyle(
            color: Colors.white,
            fontSize: 14,
          ),
        ),
      ),
    ),
  );

  void onPressed() async{
    setState(() => selectedIdx = (selectedIdx + 1) % 3);
  }
}
```

</details>

### Screenshots

<details>
<summary>huawei p30 pro screenshots</summary>

![Screenshot_20230801_152055_com example explore](https://github.com/flutter/flutter/assets/7424823/b55c94eb-b275-49bc-b873-60732b103b1f)

**device info**
version: Android SDK 29(Android 10)
model: VOG-AL10
width_px: 1080
height_px: 2340
dpi_x: 397.565002
dpi_y: 398.898988
</details>

<details>
<summary>xiaomi note 3 screenshots</summary>

![Screenshot_2023-08-01-15-14-06-877_com example explore](https://github.com/flutter/flutter/assets/7424823/832e22da-0bfd-4d4e-afb3-d3e261c056cb)

**device info**
version: Android SDK 28(Android 9)
model: Mi Note 3
width_px: 1080
height_px: 1920
dpi_x: 403.411011
dpi_y: 403.040985
</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.6, on macOS 12.6.6 21G646 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 3.10.6 on channel stable at
      /Users/sven/fvm/versions/3.10.6
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (3 周前), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/sven/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] Connected device (4 available)
    • VOG AL10 (mobile)          • APH0219919010188                     • android-arm64  • Android 10 (API 29)
    • iPhone 14 Pro Max (mobile) • AB670D8B-5C80-4CBB-BF5B-3B5CACD7D26E • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 12.6.6 21G646
      darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 115.0.5790.114

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by ChannelYu** [comment]
@huycozy
It works very well on the flutter master channel !!!
So, I am looking forward to the release of the main trunk code. thanks a lot.

**Comment by ChannelYu** [comment]
> @huycozy It works very well on the flutter master channel !!! So, I am looking forward to the release of the main trunk code. thanks a lot.
> 
> flutter --version Flutter 3.13.0-16.0.pre.18 • channel master • https://github.com/flutter/flutter.git Framework • revision [2c71881](https://github.com/flutter/flutter/commit/2c71881f505b0dc0997e959b3ac37664d221fad8) (2 hours before) • 2023-08-02 03:48:06 +0300 Engine • revision 9dae7b708b Tools • Dart 3.2.0 (build 3.2.0-22.0.dev) • DevTools 2.25.0
> 
> huawei p30 pro screenshost

This issue may be related to the `useMaterial3:` varible. on v3.10.6(stable) or v3.13.0(master), if i set `useMaterial3` to `false`, issue still exists.

<details><summary>code</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MaterialApp(home: MainContent()));

class MainContent extends StatefulWidget {
  const MainContent({super.key});

  @override
  State<MainContent> createState() => _MainContentState();
}

class _MainContentState extends State<MainContent> {
  var texts = ['ABCDFG', 'ABCDEF哈哈', '哈哈'];
  var selectedIdx = 0;

  @override
  Widget build(BuildContext context) => Theme(
    // set it to `true` works fine
    data: ThemeData(useMaterial3: false),
    child: Scaffold(
      appBar: AppBar(title: const Text('haha')),
      floatingActionButton: FloatingActionButton(
        onPressed: onPressed,
        child: const Icon(Icons.refresh),
      ),
      body: Center(
        child: Container(
          color: Colors.blue,
          child: Text(
            texts[selectedIdx],
            style: const TextStyle(
              color: Colors.white,
              fontSize: 14,
            ),
          ),
        ),
      ),
    ),
  );

  void onPressed() async{
    setState(() => selectedIdx = (selectedIdx + 1) % 3);
  }
}
```

</details>

Is it possible that this issue will be fixed in Material2, or do I need to upgrade my project to Material3?

**Comment by huycozy** [comment]
M3 will be enabled by default (already enabled on master channel), please see https://github.com/flutter/flutter/issues/127064. So I would recommend you start migrating your project to adapt to this change.
