### ISSUE TITLE
Issue: Cannot theme progress indicators, many properties missing

### ISSUE THREAD

**Issue by rydmike** [flutter/flutter#131690]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

## Steps to reproduce

The `ProgressIndicatorThemeData` is missing many key properties from `LinearProgressIndicator` and `CircularProgressIndicator` making it impossible to theme their styles.

### Expected results

Expect to be able to style the `LinearProgressIndicator` and `CircularProgressIndicator` with their `ProgressIndicatorThemeData` by also adding styles for properties:

- `borderRadius` The border radius of both the indicator and the linear track on a `LinearProgressIndicator`. https://github.com/flutter/flutter/blob/5d2c9d0933b9946d2eff8477edaceb9c91f61998/packages/flutter/lib/src/material/progress_indicator.dart#L291
- `strokeWidth`  The width of the line used to draw the circle on a `CircularProgressIndicator`. https://github.com/flutter/flutter/blob/5d2c9d0933b9946d2eff8477edaceb9c91f61998/packages/flutter/lib/src/material/progress_indicator.dart#L564
- `strokeAlign` The relative position of the stroke on a `CircularProgressIndicator`. https://github.com/flutter/flutter/blob/5d2c9d0933b9946d2eff8477edaceb9c91f61998/packages/flutter/lib/src/material/progress_indicator.dart#L565
- `strokeCap` The progress indicator's line ending on a `CircularProgressIndicator`. https://github.com/flutter/flutter/blob/5d2c9d0933b9946d2eff8477edaceb9c91f61998/packages/flutter/lib/src/material/progress_indicator.dart#L568

### Actual results

The newer `LinearProgressIndicator` and `CircularProgressIndicator` properties listed above that were added as enhancements, e.g. in [PR #122664](https://github.com/flutter/flutter/pull/122664) were forgotten or neglected to be added to `ProgressIndicatorThemeData` and are now missing, this is causing theming **issues**. 

The properties cannot be found in the latest version of `ProgressIndicatorThemeData`: 

https://github.com/flutter/flutter/blob/5d2c9d0933b9946d2eff8477edaceb9c91f61998/packages/flutter/lib/src/material/progress_indicator_theme.dart#L32

Therefore, we cannot theme the `LinearProgressIndicator` and `CircularProgressIndicator` to their desired style.

### Code sample

Code only via provided repo links showing the issue.

### Used Flutter version

Flutter version used to study the code and link to repo code samples:

Channel master, 3.13.0-15.0.pre.16

<details>
  <summary>Flutter doctor</summary>

```
flutter doctor -v
[✓] Flutter (Channel master, 3.13.0-15.0.pre.16, on macOS 13.4.1 22F770820d darwin-arm64,
    locale en-US)
    • Flutter version 3.13.0-15.0.pre.16 on channel master at
    • Framework revision fcd5a6c478 (3 hours ago), 2023-08-01 06:06:40 -0400
    • Engine revision 25b9d1088d
    • Dart version 3.2.0 (build 3.2.0-19.0.dev)
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is
      recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/rydmike/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Community Edition (version 2023.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 74.0.4
    • Dart plugin version 231.9161.14

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.4.1 22F770820d darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 115.0.5790.114

[✓] Network resources
    • All expected network resources are available.

```
</details>

**Comment by bernaferrari** [comment]
it is missing on purpose because both Circular and Linear progress indicator use the same theme, so we either add properties that doesn't make sense to the theme, or make two themes, but then need to make the usual deprecation process which is not worth it for such as small change.

**Comment by rydmike** [comment]
## Background and Rationale

Every little time a widget leaves out theme style properties that can be adjusted with widget style properties, but not with theme properties, we depreciate the usefulness of theming. It eventually results in that nobody will use theming because you cannot adjust all needed styles with them anyway. Thus devs may end up using only custom widget style wrappers instead. Which works if done right, but now devs on the project have to know to use those widget wrappers instead of just the theme styled vanilla SDK widgets, to get the intended style for the app.

There are already many widgets that have properties that can only be adjusted on widget level, but not on theme level. This is poor form already, let's not on purpose increase the gap. There are also a few rare cases where we can only change the widget style with themes, but not with widget properties. This is also not a good design. Let us aim to always keep parity between their styling capabilities.

### Use the same theme

As for this particular theme and the two widgets. Yes I agree it would be cleaner with two separate themes, on the other hand the two progress indicator variants could very well also share the same theme and the theme could well contain a few properties properties that are only used by each widget variant. There are already theme precedents in the SDK for this design, e.g. `ChipThemeData`.

In this case the theme property `borderRadius` would only be used by the `LinearProgressIndicator`. 

While `strokeWidth`,`strokeAlign` and `strokeCap` would only be used by the `CircularProgressIndicator`. 

There is no conflict between them and the fact that some theme properties only have any effect on one or the other progress indicator variant's style, is just a matter of theme property documentation. Sure separate themes would be nice, but I don’t see any major need to overcomplicate this issue.

## Related issue: Variant styles

This case is in fact much simpler than the ones where we have widget variant styles, that share the same theme and same properties, and setting the property on theme level destroys the variant styling by making all variant styles equal. See e.g. https://github.com/flutter/flutter/issues/123829, https://github.com/flutter/flutter/issues/118063 and https://github.com/flutter/flutter/issues/107946. 

This causes severe issues where we cannot use theming using the existing theme properties without destroying the difference between the variant styles. The defaults for these widgets can thus only be changed on widget property level. In fact styling them with themes is not really possible, which is very bad since the properties do exist, but we cannot use them for only a given widget variant. This issue comment https://github.com/flutter/flutter/issues/107946#issuecomment-1193422262 contains a discussion on a solution, but nothing has yet been done to move forward on it. 

However, this particular issue is not constrained by this complication. It is more like `Chips`, where some properties impact only certain variants. This case is, for now, even simpler, since there are only two variants, so it would not even be as complicated as the `Chip` theme.
