### ISSUE TITLE
Improper rendering of Asian language characters with Canvaskit

### ISSUE THREAD

**Issue by chathurach** [flutter/flutter#131794]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Use text widget with the phrase "අප්‍රිකා" or "ප්‍රීතිමත්" or "ශ්‍රී ලංකා".
2. build the web version using the canvaskit (flutter build web --release --web-renderer canvaskit)
3. host the app and go to the website on mobile Chrome (incorrect rendering) and desktop Chrome browser (correct rendering).

### Expected results

Asian language (Sinhala language) rendering is incorrect in the mobile version of the Chrome browser. But the desktop version shows the correct rendering.
Correct rendering should be "අප්‍රික/ප්‍රීතිමත්/ශ්‍රී ලංකා"

### Actual results

The mobile Chrome version rendering is incorrect with the canvaskit renderer. 
Incorrect rendering "අප්රිකා/ප්රීතිමත්/ශ්රී ලංකා"

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
correct and incorrect rendering
<summary>Screenshots </summary>

![africa](https://github.com/flutter/flutter/assets/10696314/e821c851-250d-437d-af9f-83e72bebcaf5)

![africa_phone_1](https://github.com/flutter/flutter/assets/10696314/2816448a-ae43-4574-a407-a7db8655b0b2)

![prithimath](https://github.com/flutter/flutter/assets/10696314/16c51212-9b1f-4f0d-847f-68b1f1ed39e0)

![prithimath_phone_1](https://github.com/flutter/flutter/assets/10696314/c4790ce9-16da-4240-b35d-238526f93534)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.10.0, on Microsoft Windows [Version 10.0.22621.1702], locale en-US)
    • Flutter version 3.10.0 on channel stable at C:\Android\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (3 months ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Android
    • Platform android-33, build-tools 30.0.3
    • ANDROID_HOME = C:\Android\
    • Java binary at: C:\Android\jdk-11.0.16.1\bin\java
    • Java version Java(TM) SE Runtime Environment 18.9 (build 11.0.16.1+1-LTS-1)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32210.238
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.80.2)
    • VS Code at C:\Users\ACER\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.68.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1702]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 115.0.5790.110
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 115.0.1901.183

[√] Network resources
    • All expected network resources are available.
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @chathurach, what device(s) are you seeing this bug on? 

I built a release version of the app and used python3 to run the app which was then exposed to my device using an ngrok tunnel and I see no differences between the text rendered on android and the text rendered on my PC browser. See the screenshot below. I also deployed the app to firebase hosting and I saw no differences. 

Can you upgrade to the latest version of flutter stable to see if you still face this issue? 

Please also provide the complete minimal reproducible code sample in case the upgrade doesn't fix the issue. 

![Screenshot 2023-08-03 at 07 34 22](https://github.com/flutter/flutter/assets/88313112/6fe1825b-1538-4545-9b7e-94355c5268bc)

<details>
<summary>sample used</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatefulWidget {
  const MyWidget({super.key});

  @override
  State<MyWidget> createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> {

  @override
  Widget build(BuildContext context) {
    return const DefaultTextStyle(
      style: TextStyle(fontSize: 36, color: Colors.black),
      child:  Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Text('අප්‍රිකා'),
          Text('ප්‍රීතිමත්'),
          Text('ශ්‍රී ලංකා'),
        ],
      ),
    );
  }
}

```
</details>

**Comment by chathurach** [comment]
Thank you @danagbemava-nc ,
I have updated to flutter 3.10.6 and it looks like it already has been fixed.
