### ISSUE TITLE
Inkwell two finger tap doesn't work 

### ISSUE THREAD

**Issue by Sesa1988** [flutter/flutter#131752]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Use Inkwell or GestureDetector above another widget with onTap events

I didn't test it alone but in this context it doesn't work. 
There where similar bugs months ago but they didn't fixed this issue.

### Expected results

onSecondaryTap works with two finger click on macOS (windows has probably the same issue).
Im not the latest Flutter version for both operating systems.

### Actual results

It does not get triggered.

### Code sample

<details><summary>Code sample</summary>

```dart
return GestureDetector(
      onSecondaryTap: () => _navigate(context),
      child: ListTile(
        enableFeedback: true,
        onTap: () => _navigate(context),
        onLongPress: () => _navigate(context),

return InkWell(
      onSecondaryTap: () => _navigate(context),
      child: ListTile(
        enableFeedback: true,
        onTap: () => _navigate(context),
        onLongPress: () => _navigate(context),
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

There is nothing to show

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output for windows</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.19045.3208], locale de-DE)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.2)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.80.2)
[√] Connected device (3 available)
[√] Network resources
```

</details>

**Comment by dam-ease** [comment]
Hi @Sesa1988 
This seems to be fixed as I cannot seem to reproduce this on the master channel. Please try switching to the master channel and check if it still persists on your end.

**Comment by tmpfs** [comment]
I can confirm that I am experiencing this as well, I was using `onSecondaryTap` in a GestureDetector for a context menu and it previously worked well on all three desktop platforms.

Now on Linux and MacOS it no longer works but continues to work as expected on Windows.

I am on the stable channel currently using:

```
Flutter 3.10.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f468f3366c (3 weeks ago) • 2023-07-12 15:19:05 -0700
Engine • revision cdbeda788a
Tools • Dart 3.0.6 • DevTools 2.23.1
```
