### ISSUE TITLE
InheritedElement.dispatchDidChangeDependencies behaves different to this document

### ISSUE THREAD

**Issue by kezhuw** [flutter/flutter#13176]
Document of `InheritedElement.dispatchDidChangeDependencies` says:

> Subclasses of [InheritedElement] might wish to call this function at other times if their inherited information changes outside of the build phase.

But there are assertions in `InheritedElement.dispatchDidChangeDependencies` and `Element.didChangeDependencies` to assert those method must be called in build scope.

Some historical PRs related to this issue:
1. #3580 introduces `InheritedElement.dispatchDidChangeDependencies` (named `dispatchDependenciesChanged` previously). Comment of that PR says:

> Some inherited widgets want to call this function direction, for example to
notify children when a mutable model object changes. Exposing this function to
subclasses of InheritedWidget is clear then forcing them to compute
updateShouldNotify for mutable model objects.

2. #6569 introduces `BuildContext.ancestorInheritedElementForWidgetOfExactType`. Dartdoc of this method says:

>   /// This method does not establish a relationship with the target in the way
  /// that [inheritFromWidgetOfExactType] does. It is normally used by such
  /// widgets to obtain their corresponding [InheritedElement] object so that they
  /// can call [InheritedElement.dispatchDidChangeDependencies] to actually
  /// notify the widgets that _did_ register such a relationship.

But comment of that PR mention nothing about this.

3. #12213 restricts `InheritedElement.dispatchDidChangeDependencies` and `Element.didChangeDependencies` to build scope. But neither dartdoc nor comment of PR mention this. 

There are some discussion in PR #12843 already, this issue is filed here to replace that PR.

**Comment by yjbanov** [comment]
I landed https://github.com/flutter/flutter/pull/13224. I think we should rephrase this issue in terms of a feature request that currently cannot be addressed by the framework and make changes to the framework to address it (and add proper tests).

**Comment by kezhuw** [comment]
Currently, I use Stream to detect changes in ancestor state and have no strong demand to extend usage of `InheritedWidget`. If I have new thought and good use case on `InheritedWidget`, I will open issue or pull request to discuss it.
