### ISSUE TITLE
Engine -> Framework roll is backed up

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#131772]
Starting with the roll here https://github.com/flutter/flutter/pull/131727

Rolls to the framework are failing on a crash detected in the FTL tests: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20firebase_release_smoke_test/57458/overview

```
More details are available at [ https://console.firebase.google.com/project/flutter-infra-staging/testlab/histories/bh.554c4369930daa2b/matrices/5941034075630413515 ].
┌─────────┬────────────────────────┬─────────────────────┐
│ OUTCOME │    TEST_AXIS_VALUE     │     TEST_DETAILS    │
├─────────┼────────────────────────┼─────────────────────┤
│ Failed  │ griffin-24-en-portrait │ Application crashed │
│ Failed  │ redfin-30-en-portrait  │ Application crashed │
└─────────┴────────────────────────┴─────────────────────┘
```

From the logs:
```
08-01 17:44:02.655: E/flutter(25134): [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1168)] Could not locate ImageTextureEntry class
08-01 17:44:02.655: F/flutter(25134): [FATAL:flutter/shell/platform/android/library_loader.cc(26)] Check failed: result. 
```

Suspecting: https://github.com/flutter/engine/pull/44087.

cc @eyebrowsoffire @johnmccutchan

**Comment by eyebrowsoffire** [comment]
Revert and manual roll has caught us up again. Closing.

**Comment by zanderso** [comment]
The re-land https://github.com/flutter/engine/pull/44278 is also hitting an issue in FTL: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20firebase_release_smoke_test/57519/overview

```
Abort message: 'art/runtime/thread.cc:1664] No pending exception expected: java.lang.NoSuchMethodError: no non-static method "Landroid/media/Image;.getHardwareBuffer()Landroid/hardware/HardwareBuffer;"'
```

**Comment by johnmccutchan** [comment]
https://github.com/flutter/engine/pull/44293

**Comment by chinmaygarde** [comment]
The roller is moving again 
<img width="749" alt="Screenshot 2023-08-07 at 10 32 21 AM" src="https://github.com/flutter/flutter/assets/44085/ef544775-3283-4165-bcd7-eb36b8a17b1a">
