### ISSUE TITLE
Windows_android flutter_gallery_win__compile execution time doubled over the past year

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#131702]
The execution time has increased from 850s (14min) to 1300s (21min) over the past year.
A recent build with 20 min: https://ci.chromium.org/ui/p/flutter/builders/prod/Windows_android%20flutter_gallery_win__compile/11251/overview
An old build (back to 04/2022) with 9.5 mins: https://ci.chromium.org/ui/p/flutter/builders/prod/Windows_android%20flutter_gallery_win__compile/3500/overview

![Screenshot 2023-08-01 at 12 13 13 PM](https://github.com/flutter/flutter/assets/54558023/5478a803-ef59-4dfe-96a7-e560ee0e8e2f)

@zanderso Could you help take a look?

**Comment by zanderso** [comment]
Previously the benchmark was running 3 `flutter build` commands. Now it is running 6 `flutter build` commands, so a ~doubling of runtime does not indicate a problem here.
