### ISSUE TITLE
Flavor-specific Assets

### ISSUE THREAD

**Issue by andrewkolos** [flutter/flutter#131728]
### Document Link

https://flutter.dev/go/flavor-specific-assets

### What problem are you solving?

[Flavor-specific assets (173 thumbs-up)](https://github.com/flutter/flutter/issues/21682)

Flutter app developers have no simple way to choose which assets are bundled with each flavor of their app. This results in either tedious steps in their release process or application bundles bloated with megabytes of unused assets when building specific flavors of their app.

Flutter should provide users the ability to associate assets with particular flavors. When building an app, Flutter will bundle only the assets associated with the build flavor(s).

**Comment by navaronbracke** [comment]
Related: https://github.com/flutter/flutter/issues/96514 (having the assets bundled per flavor would be a solution for that one)

**Comment by christopherfujino** [comment]
per discussion in discord, I'm gonna close this and add the link and design doc label to the linked issue.
