### ISSUE TITLE
[CP] [Impeller] Fix leak of wrapped TextureMTL objects in the Metal embedder API

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#131799]
### Issue Link

https://github.com/flutter/flutter/issues/131682

### Commit Hash

134c198eeb10f8c2ac2088bdc8058cdf2e963f2f

### Target

stable

### PR Link

https://github.com/flutter/engine/pull/44286

### Changelog Description

Fixes a memory leak in Impeller affecting macOS Metal embedders

### Impacted Users

Impeller users on macOS

### Impact Description

The app leaks memory when resizing the window

### Workaround

Disable Impeller

### Risk

low

### Test Coverage

yes

### Validation Steps

Resize the window and verify that memory usage is stable

**Comment by chinmaygarde** [comment]
lgtm

**Comment by CaseyHillers** [comment]
Shipped in 3.13.0-0.4.pre beta
