### ISSUE TITLE
How to debug flutter.framework in source mode? As flutter is open source, I think this can help us understand what's happening behind.

### ISSUE THREAD

**Issue by kangwang1988** [flutter/flutter#13174]
##  Problem

I have cloned dart-sdk,engine,flutter. However, when I want to debug the flutter.framework in source code to learn more, I failed. The framework has a lot of dependency, some of them is embedded while there are still some library not available like fxl. Any approches?

**Comment by kangwang1988** [comment]
@cbracken  @chinmaygarde  @xster

**Comment by Hixie** [comment]
Does this document help? https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md

**Comment by xster** [comment]
If you follow the guide at https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md, you should end up getting all the various dependencies (specifically the gclient sync part) needed to build a debuggable version of the engine. 

There are some tips on how to add breakpoints and use xcode to debug both native application code and engine code. 

Tentatively closing. Please let us know if there are parts of the doc that could be made clearer. Feel free to send us PRs to change the documentation as well if needed.
