### ISSUE TITLE
flutter packages get shouldn't retry for path dependencies

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#13178]
At some point we added retry logic for when `packages get` fails. That makes sense for network failures, but I'm not sure it makes sense for `path:` dependencies where the failure is typically due to a mistyped path:

```
---- End log transcript ----
pub get failed (69) -- attempting retry 3 in 4 seconds...
Could not find package firebase_auth at "../packages/firebase_auth".
```

**Comment by Hixie** [comment]
It only retries when pub returns 69, which I understand to be something that pub returns for network errors. We should make sure pub is consistent in reporting network errors (or other retryable errors) with one code and persistent errors with another.

**Comment by mit-mit** [comment]
@nex3 would it be possible for pub to use different error codes for these?

**Comment by nex3** [comment]
We could probably return error code 66 ("An input file did not exist or was unreadable") for path packages that don't exist. Can you file an issue against pub?

**Comment by mit-mit** [comment]
A fix was landed in pub. Waiting for a new Dart dev build we can roll.

**Comment by Hixie** [comment]
This has presumably landed by now?

**Comment by mit-mit** [comment]
Yes, this should be in SDK 2.0 dev 15 or later, and we are on 16 now.

**Comment by mit-mit** [comment]
cc @jcollins-g

**Comment by mit-mit** [comment]
This is now working after the roll to sdk dev.19!

```
>flutter packages get
Running "flutter packages get" in foobar...
Could not find package uurl_launcher at "c:/foobar/".
Depended on by:
- foobar
---- Log transcript ----
...
---- End log transcript ----
pub get failed (66)

>

```
