### ISSUE TITLE
[Flutter GPU] Make Dart source package developed in flutter/engine available through the flutter framework.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#131711]
Based on feedback from the Dart team, we've shifted dart:gpu from a `dart:` library into a regular source package that interacts with the engine via `dart:ffi`. While this seems to work great locally, it does leave an open question as to how we would distribute this package to developers.

We'd like to avoid developing this package in `flutter/flutter` and instead develop it in `flutter/engine` so that the Dart code is co-located with the native APIs it is binding to. However, we don't currently have a standard means of doing so. Some options we potentially have:

* The engine -> framework autoroller could be configured to copy the source code of flutter_gpu from a particular engine directory to a particular framework directory. This would ensure that the engine binary is always used with the correct flutter_gpu version. This would also make sure that the framework git repo wasn't left dirty.  Unfortunately, this would make the local engine development workflow harder, as we'd need to use dependency_overrides.

* The flutter tool could copy the flutter_gpu sources from some engine binary directory into an accessible source directory. This would require us to gitignore some folder in flutter/flutter or else we'd leave the git repo dirty. This may or may not work well with analysis, and may have implications for what source code is considered the source of truth. Similar issue as 1.

* The flutter SDK could include a package which essentially re-exports source code from a specified engine artifact directory using relative paths. This may only work with certain configurations of the SDK.

* The pub cmdline tool could be configured to look in a particular engine artifact directory, based on either heuristics or based on some configuration in the flutter/flutter repo. This would work similar to the `sdk: flutter` magic, which appends `/packages/<package-name>` to the flutter root known by pub.

FYI @Hixie @bdero @jonasfj

**Comment by dcharkes** [comment]
Are we planning on pinning this package to the engine version? If not we have to deal with version-skew between the symbols in native and the (generated?) FFI bindings in Dart code in the package.

**Comment by jonahwilliams** [comment]
> Are we planning on pinning this package to the engine version? If not we have to deal with version-skew between the symbols in native and the (generated?) FFI bindings in Dart code in the package.

It must be pinned to engine version, and needs to be distributed from flutter/engine or flutter/flutter. Publishing to pub is a non-starter.

**Comment by whesse** [comment]
The monorepo build of tip-of-tree framework, engine, and SDK uses only a modified engine DEPS to build engine, and the framework downloads these engine artifacts from cloud storage, the same way that released versions have framework download the engine.

So the second, third, and fourth options would be compatible with this, but not the first. I'm not clear on what the problems would be with the third option. What configurations would be incompatible with this?

The framework has no access to the engine source checkout when running tests and flutter builds with a monorepo build, only to the engine artifacts uploaded to the cloud.

**Comment by jonasfj** [comment]
> The pub cmdline tool could be configured to look in a particular engine artifact directory, based on either heuristics or based on some configuration in the flutter/flutter repo. This would work similar to the sdk: flutter magic, which appends /packages/<package-name> to the flutter root known by pub.

I assume you're talking about making a new sdk-package (`sdk: flutter`) which is not in `$FLUTTER_ROOT/packages/<package-name>`.

This is already possible, the logic is here:
https://github.com/dart-lang/pub/blob/master/lib/src/sdk/flutter.dart#L81-L94

It'd be easy to add another search folder, but honestly, I'd be inclined to suggest we just add a `$FLUTTER_ROOT/sdk-packages.yaml` file, like:
```yaml
sdk: flutter
packages:
- name: flutter
  path: packages/flutter
- name: sky_engine
  path: bin/cache/pkg/sky_engine
...
```

That way it would be very explicit whether a package is exposed from the Flutter SDK or not. And we wouldn't have a bunch of magic hardcoded paths in `pub`.

@sigurdm, thoughts?

----------------------------------

This all assumes you intended to introduce a new sdk-package.

**Comment by jonasfj** [comment]
Filed https://github.com/dart-lang/pub/issues/3980

**Comment by bdero** [comment]
Part of https://github.com/flutter/flutter/issues/130921

**Comment by sigurdm** [comment]
> I assume you're talking about making a new sdk-package (sdk: flutter) which is not in $FLUTTER_ROOT/packages/<package-name>.

We already include packages from `$FLUTTER_ROOT/bin/cache/pkg` which is currently just the `sky_engine` package. We could reuse that.

https://github.com/dart-lang/pub/blob/dce232ec195df802a730eb3a66163e28d2ec6444/lib/src/sdk/flutter.dart#L112

I believe sky_engine is coming from the engine already: https://github.com/flutter/engine/tree/f34c658b9600c380bc2608fa5622f3547fd05c1c/sky/packages/sky_engine

> It'd be easy to add another search folder, but honestly, I'd be inclined to suggest we just add a $FLUTTER_ROOT/sdk-packages.yaml file, like: [...]

I'm not opposed to it. I don't see a huge advantage to the current workings - so I don't know if it's worth making the change, but I think it would work fine, and be slightly less messy.
