### ISSUE TITLE
[google_maps_flutter] Remove old overrides in GoogleMapController.java

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#131791]
There are two sections of code in this file with the comment:
```
// TODO(mklim): Remove this empty override once https://github.com/flutter/flutter/issues/40126 is fixed in stable.
```

That issue was fixed in 2019, so we should be able to address the TODO now.

**Comment by mishapark** [comment]
I would like to take this one, if no one is working on it

**Comment by SirusCodes** [comment]
We can close this
