### ISSUE TITLE
[Feature Request] Flutter how to mimic typing text to any 3rd apps?

### ISSUE THREAD

**Issue by lucasjinreal** [flutter/flutter#131845]
I have posted this question to stackoverflow, but noone gives an answer.

This is not a problem to flutter, but a User request (feature).

Could flutter possible mimic typing text to any 3rd apps on desktop?

For example, just as am typing in github issue edit box in browser, can flutter able to input for me be implemented?  (sorry to be noisy to github issue, but really **got no clue** about how to implement, any suggestion would be very appreciated! Come up with this because ChatGPT becomes sooo useful wish flutter could help me typing automatically by request AI.

**Comment by stuartmorgan** [comment]
> This is not a problem to flutter, but a User request (feature).

Attempting to inject artificial events into other applications is not a use case that would be built into Flutter itself. To the extent that this is even possible, it would need to be built as a third-party plugin.

Closing as out of scope.

**Comment by lucasjinreal** [comment]
@stuartmorgan Understood that this is not flutter inside functions. As for the extensions, does there any community plugins I can reference?

**Comment by stuartmorgan** [comment]
For help finding community packages, consider one of the resources listed at https://flutter.dev/community#community-grid
