### ISSUE TITLE
[plugin] firebase version update

### ISSUE THREAD

**Issue by JFixby** [flutter/flutter#13184]
Appcompat version update required:

The latest version:
```
    compile 'com.google.firebase:firebase-core:11.6.0'
    compile 'com.google.firebase:firebase-messaging:11.6.0'
    compile 'com.google.firebase:firebase-crash:11.6.0'
```

Current (not functional): https://github.com/flutter/plugins/blob/master/packages/firebase_messaging/android/build.gradle#L32
```
        compile 'com.google.firebase:firebase-core:11.4.+'
        compile 'com.google.firebase:firebase-messaging:11.4.+'
```

**Comment by zoechi** [comment]
at least related to #12945 I guess

**Comment by Hixie** [comment]
cc @collinjackson

**Comment by kroikie** [comment]
@JFixby

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/934. Any further collaboration will be done there.
