### ISSUE TITLE
[Impeller] Re-enable the Scenario iOS UI golden tests.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#131888]
Today these use --enable-software-rendering, which is not supported in impeller, so they have not actually been testing impeller. I'm going to be disabling them as part of fixing https://github.com/flutter/flutter/issues/131887, but they should get re-enabled to get coverage. 

One thing that is not clear is how significant pixel differences will be if we enable impeller.

As part of re-enabling them, it may be worthwhile to see if we can upload the images to gold rather than doing the comparisons as part of the test harness.

**Comment by jmagman** [comment]
cc @jonahwilliams I was out when these scenario tests were turned off for impeller and didn't realize they weren't running, should we prioritize turning them back on since impeller is now the default on iOS?

**Comment by jonahwilliams** [comment]
Do the iOS machines support GPU passthrough or are they software only? IIRC we turned them off because Impeller doesn't support machines without metal.

**Comment by jmagman** [comment]
The lower end bot in the pool is [Macmini8,1 Core i7](https://everymac.com/systems/apple/mac_mini/specs/mac-mini-core-i7-3.2-late-2018-specs.html) with integrated Intel UHD Graphics 630. 

The higher end in the pool is [Macmini9,1](https://everymac.com/systems/apple/mac_mini/specs/mac-mini-m1-8-core-2020-specs.html) with an "integrated Apple GPU with 8-cores".

I'm not sure how to look up what supports GPU passthrough. They are both on the [Metal 3](https://support.apple.com/en-us/102894) list though since they run macOS Ventura or higher.

Might be easier to just flip it on and see what breaks, given https://github.com/flutter/flutter/issues/131887 would stop us from getting into a silly state.

**Comment by jonahwilliams** [comment]
We actually don't crash anymore, we just render nothing with a warning :)

**Comment by jmagman** [comment]
> just render nothing

Well hey, we'll still catch that, it won't match the screenshot! Great victory.

**Comment by jmagman** [comment]
1. I suspect the scenario tests are only being run with Skia (twice).
```
Running simulator tests with Impeller
...
2024-09-06 13:38:07.692810-0700 Scenarios[73857:470266] [IMPORTANT:flutter/shell/common/shell.cc(456)] [Action Required] The application opted out of Impeller by either using the --no-enable-impeller flag or FLTEnableImpeller=false plist flag. This option is going to go away in an upcoming Flutter release. Remove the explicit opt-out. If you need to opt-out, report a bug describing the issue.
```
https://github.com/flutter/engine/pull/55012#issuecomment-2334801029
I don't see the `INFOPLIST_FILE="Scenarios/Info_Impeller.plist"` being passed into the xcodebuild any more.  Not sure exactly why, I suspect some shell script whitespace though.

2. This logging logic is incorrect, `FLTEnableImpeller` is set in the app, not the UI test, so the bundle should be "dev.flutter.Scenarios".
https://github.com/flutter/engine/blob/397987aedeb4ed41ec945fcbe9d347e579513bf4/testing/scenario_app/ios/Scenarios/ScenariosUITests/GoldenTestManager.m#L84-L90

Therefore there's a bug on the side that tries to set Impeller and a bug on the side that checks the images, and would have caught it.

I can fix the bugs, or @jonahwilliams @zanderso is it time to turn off the Skia scenario tests? Or are those still valuable?

**Comment by zanderso** [comment]
> I can fix the bugs, or @jonahwilliams @zanderso is it time to turn off the Skia scenario tests? Or are those still valuable?

Depending on how much trouble it is, we should probably keep the Skia variants until early next month. If keeping the Skia variants is time consuming or troublesome, then removing them earlier is fine with me, but @jonahwilliams should confirm.
