### ISSUE TITLE
Monitor dart-internal queue times

### ISSUE THREAD

**Issue by drewroengoogle** [flutter/flutter#131871]
With the removal of greedy batching from the dart-internal configs, we want to be sure that our queue times are not significantly affected by this change. This bug is for tracking this so we make sure to keep an eye on it.

**Comment by yusuf-goog** [comment]
is this ready to close?

**Comment by drewroengoogle** [comment]
We haven't noticed any issues with dart-internal builds, so I am okay with closing this.
