### ISSUE TITLE
[CP] [ios][autocorrection]disable auto-correction highlight in iOS 17 #44176

### ISSUE THREAD

**Issue by hellohuanlin** [flutter/flutter#131890]
### Issue Link

https://github.com/flutter/flutter/issues/128406

### Commit Hash

42b4cfd

### Target

beta

### PR Link

https://github.com/flutter/engine/pull/44354

### Changelog Description

Disables the "auto-correction highlight" feature in iOS 17. 

### Impacted Users

all end-customers

### Impact Description

This PR fixes a bug where the last char is selected on every key stroke ([video](https://github.com/flutter/flutter/issues/128406#issuecomment-1585708637)). This can be a deal breaker for iOS developers to use Flutter. 

### Workaround

NA

### Risk

high

### Test Coverage

yes

### Validation Steps

Create a dummy Flutter app with an EditableText widget, and type. You will see it's been fixed. 

You can also try the test app under `/flutter/dev/integration_tests/ios_platform_view_tests` in framework repo

**Comment by CaseyHillers** [comment]
@stuartmorgan can you review this CP request? If it looks good to you, add the "cp: approved" label.

**Comment by stuartmorgan** [comment]
LGTM and approved.
