### ISSUE TITLE
Meta: Keep branches on flutter/flutter pruned?

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#13186]
## Steps to Reproduce

Run the `flutter upgrade` tool or view https://github.com/flutter/flutter/branches.

<img width="984" alt="screen shot 2017-11-23 at 12 47 55 pm" src="https://user-images.githubusercontent.com/168174/33188182-91473e2e-d04c-11e7-8f30-567a1ee58dd4.png">

<img width="319" alt="screen shot 2017-11-23 at 12 52 01 pm" src="https://user-images.githubusercontent.com/168174/33188232-268c4894-d04d-11e7-83d4-accd308f8288.png">

Here is what I got when running `flutter upgrade` on a machine with a 30-day old SDK:

```
Upgrading Flutter from /Users/matan/git/flutter...
From github.com:flutter/flutter
   e20bff4d7..167382480  master                  -> origin/master
 * [new branch]          address_analysis_issues -> origin/address_analysis_issues
   4424892c7..e8aa40edd  alpha                   -> origin/alpha
 * [new branch]          inspector_service_review -> origin/inspector_service_review
 * [new branch]          mit-mit-analysis        -> origin/mit-mit-analysis
 * [new branch]          mit-mit-rolldart        -> origin/mit-mit-rolldart
 * [new branch]          public_docs             -> origin/public_docs
 * [new branch]          revert-12629-roll       -> origin/revert-12629-roll
 * [new branch]          revert-13143-roll_engine -> origin/revert-13143-roll_engine
 * [new branch]          tweak_create_template   -> origin/tweak_create_template
 * [new branch]          update_reload_message   -> origin/update_reload_message
 * [new branch]          update_template_iml     -> origin/update_template_iml
 + 802be8253...c9ea69f50 video                   -> origin/video  (forced update)
 * [new tag]             0.0.17                  -> 0.0.17
```

-----

It would be nice to keep this to just tagged releases and the explicit `alpha`/`master` channel. I see that a lot of contributors with write permissions are creating branches directly here instead of creating a fork first, which would avoid this problem entirely of having lots of stale branches.

**Comment by eseidelGoogle** [comment]
We have historically.  Looks like we need a new round of pruning.  https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md talks about using your clone as origin I think.  FYI @Hixie @mit-mit

**Comment by Hixie** [comment]
There shouldn't be any branches normally other than alpha and master (and hackathon). I just deleted a bunch of them, but there looks like there were some new ones created by @devoncarew and @mit-mit recently, and some by @jacob314 a few months ago, that I am not sure are safe to delete.

The only ones I would expect to see normally are reverts created by GitHub's revert tool.

**Comment by mit-mit** [comment]
I believe the active branches you see are the result of creating pull requests from the GitHub web UI. It would be sad if that was no longer allowed.

What problem do the branches create?

**Comment by matanlurey** [comment]
You can definitely still create pulls from the GitHub UI just staged in your fork and not upstream. Anyone that doesn't have write access (read: everyone but your team) would have to do this anyway.

**Comment by mit-mit** [comment]
Yes, you can, but keeping a fork up-to-date from the web UI is quite painful: https://github.com/isaacs/github/issues/121

That being said, if these branches are causing issues I guess that's the way to go...

**Comment by Hixie** [comment]
I think it's fine to just clean up the branches occasionally.
