### ISSUE TITLE
[plugin] firebase_messaging onMessage/onLaunch/onResume not working

### ISSUE THREAD

**Issue by JFixby** [flutter/flutter#13181]
Project: https://github.com/flutter/plugins/tree/master/packages/firebase_messaging/example

This is the code from the example:
```Dart
@override
  void initState() {
    super.initState();
    _firebaseMessaging.configure(
      onMessage: (Map<String, dynamic> message) {
        print("log: onMessage: $message");
        _showItemDialog(message);
      },
      onLaunch: (Map<String, dynamic> message) {
        print("log: onLaunch: $message");
        _navigateToItemDetail(message);
      },
      onResume: (Map<String, dynamic> message) {
        print("log: onResume: $message");
        _navigateToItemDetail(message);
      },
    );
    _firebaseMessaging.requestNotificationPermissions(
        const IosNotificationSettings(sound: true, badge: true, alert: true));
    _firebaseMessaging.onIosSettingsRegistered
        .listen((IosNotificationSettings settings) {
      print("log: Settings registered: $settings");
    });
    _firebaseMessaging.getToken().then((String token) {
      assert(token != null);
      setState(() {
        _homeScreenText = "Push Messaging token: $token";
      });
      print(_homeScreenText);
    });
  }
```
 
The onMessage/onLaunch/onResume-listeners are set but never get called.

**Comment by Hixie** [comment]
cc @collinjackson

**Comment by zoechi** [comment]
Perhaps https://github.com/flutter/plugins/blob/master/packages/firebase_messaging/example/android/app/src/main/AndroidManifest.xml#L18 or `data: { click_action: 'FLUTTER_NOTIFICATION_CLICK', ...` in the message is missing?

**Comment by zoechi** [comment]
#23293, #23148 might be related

**Comment by zoechi** [comment]
See also https://github.com/flutter/flutter/issues/18425#issuecomment-400111877

**Comment by phuongdanh** [comment]
I think it helps
https://github.com/flutter/flutter/issues/18425#issuecomment-457129809

**Comment by ozenati** [comment]
@JFixby did you resolve your issue?

**Comment by JFixby** [comment]
@ozenati Sort of.
I quit the job.

**Comment by kroikie** [comment]
@JFixby

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/935. Any further collaboration will be done there.
