### ISSUE TITLE
[image_picker] image_picker: ^1.0.1 image rotation issue 

### ISSUE THREAD

**Issue by CuongNV12** [flutter/flutter#131831]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce
Pick up photos and see the cache results.

The preview is displayed correctly, but the image in memory has been rotated with ```image_picker: ^1.0.1```
(the same problem occurs in both ```Android``` and ```IOS```)
This happens with a few pictures.

### Expected results

Keep the correct orientation of the image.
I use this image to push to the server, so the original orientation of the image should be correct.

### Actual results

The image was automatically rotated

### Code sample

<details><summary>Code sample</summary>

```dart
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  XFile? _xFile;

  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            if (_xFile != null) Image.file(File(_xFile?.path ?? '')),
            TextButton(
              onPressed: () async {
                final image =
                    await ImagePicker().pickImage(source: ImageSource.gallery);
                if (image != null) {
                  setState(() {
                    _xFile = image;
                  });
                }
              },
              child: const Text('Pick Image'),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/53120409/306399d8-97b0-4d71-8930-296649341ba8

[The image has an error]
![bo-suu-tap-hinh-anh-ngoi-nha-dep-nhat-viet-nam-6 (1)](https://github.com/flutter/flutter/assets/53120409/dda26e7f-6325-4d85-a484-bde65f6b8a70)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4 22F66 darwin-arm64, locale en-VN)
    • Flutter version 3.10.5 on channel stable at /Users/cuong.nv2/fvm/versions/3.10.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (7 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/cuong.nv2/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Connected device (5 available)
    • SM A536E (mobile)           • R5CT43S52SD                          • android-arm64  • Android 12 (API 31)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 13 (API 33) (emulator)
    • iPhone Xʀ (mobile)          • 94A1EBEC-51FB-4B71-8ED6-C876D62CFE30 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 115.0.5790.114

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by dam-ease** [comment]
Hi @CuongNV12. Thanks for filing this issue, I can't seem to reproduce this issue on the latest `stable` channel. Can you upgrade to the latest version to confirm if this issue still persists?

**Comment by maRci002** [comment]
The image may contain EXIF data, which records the image's orientation. While some software, like Android Studio's Device File Explorer, may not respect this EXIF orientation, Flutter correctly rotates the image in the same way that Android's file picker does.

You can use the https://pub.dev/packages/exif package to confirm whether the image is originally in landscape mode, even though the EXIF data may rotate it.

**Comment by CuongNV12** [comment]
> Hi @CuongNV12. Thanks for filing this issue, I can't seem to reproduce this issue on the latest `stable` channel. Can you upgrade to the latest version to confirm if this issue still persists?

I've used flutter sdk `3.10.6` in stable channel and image_picker: ^1.0.1 but the problem still occurs.

You can use below image to reproduce this issue.
https://user-images.githubusercontent.com/53120409/258004351-dda26e7f-6325-4d85-a484-bde65f6b8a70.jpg


<details><summary>Doctor output</summary>
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4 22F66 darwin-arm64, locale en-VN)
    • Flutter version 3.10.6 on channel stable at /Users/cuong.nv2/fvm/versions/3.10.6
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (3 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/cuong.nv2/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 13 (API 33) (emulator)
    • iPhone Xʀ (mobile)          • 94A1EBEC-51FB-4B71-8ED6-C876D62CFE30 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 115.0.5790.170

[✓] Network resources
    • All expected network resources are available.

• No issues found!
</details>

**Comment by CuongNV12** [comment]
> The image may contain EXIF data, which records the image's orientation. While some software, like Android Studio's Device File Explorer, may not respect this EXIF orientation, Flutter correctly rotates the image in the same way that Android's file picker does.
> 
> You can use the https://pub.dev/packages/exif package to confirm whether the image is originally in landscape mode, even though the EXIF data may rotate it.

![image](https://github.com/flutter/flutter/assets/53120409/5732b4dc-9db0-45bb-82ea-4d8924985af5)

This is EXIF data. 

>While some software, like Android Studio's Device File Explorer, may not respect this EXIF orientation
>
It doesn't seem to be the fault of `Android Studio Device File Explorer`. because i used this file to send to the server, after getting the image url and displaying, the image still shows like `Android Studio Device File Explorer` does.

**Comment by dam-ease** [comment]
Hi @CuongNV12. Thanks for the detailed explanation. Using the image you shared, I can see from the EXIF data that it's rotated 90.
```
{Image ImageWidth: 600, Image ImageLength: 398, Image ExifOffset: 62, Image Orientation: Rotated 90 CCW, EXIF LightSource: Unknown}
``` 
Checking the downloaded file from the device, I see the correct image but viewing the Downloads folder via `Android Studio Device File Explorer`, I see the image rotated, hence this might stand.

> While some software, like Android Studio's Device File Explorer, may not respect this EXIF orientation

<img width="947" alt="Screenshot 2023-08-04 at 10 20 46" src="https://github.com/flutter/flutter/assets/53122008/2a8cbc6c-bf0d-41d7-8ac0-b8b2da837341">

**Comment by CuongNV12** [comment]
It seems to be a display error of `Android Studio Device File Explorer`, and our `fie uploader`.

Thank you for supporting me!
