### ISSUE TITLE
Incomplete doc for RasterStatus::kSkipAndRetry

### ISSUE THREAD

**Issue by dkwingsmt** [flutter/flutter#131814]
[The doc for `RasterStatus::kSkipAndRetry`](https://github.com/flutter/engine/blob/6a2afca228ba18a0ffd20657c5f72e9115346ae8/flow/compositor_context.h#L43) seems incomplete.

```
  // Frame is dropped and a new frame with the same layer tree is
  // attempted.
  //
  // This is currently used to wait for the thread merger to merge
  // the raster and platform threads.
  //
  // Since the thread merger may be disabled,
  kSkipAndRetry,
```

And it has been like this since [it was added](https://github.com/flutter/engine/pull/21059/files#diff-67baf63d33b9c545c24810d32e0e68fb29079b36d00e6d909043471136d431b8R41).

**Comment by dkwingsmt** [comment]
Also, the doc for `kEnqueuePipeline` has an extra `"`.

**Comment by yatendra2001** [comment]
I would like to take this one if no one's working on it.

**Comment by dkwingsmt** [comment]
> I would like to take this one if no one's working on it.

That would be really helpful!

**Comment by yatendra2001** [comment]
Awesome then could you assign this to me??

**Comment by SakshamSahu** [comment]
I would like to work on this issue. can you assign this to me?

**Comment by dkwingsmt** [comment]
Hi, feel free to submit a PR. The assignment doesn't mean much.

**Comment by SakshamSahu** [comment]
I have sent the PR

**Comment by yatendra2001** [comment]
Hi @dkwingsmt ,

I've addressed the incomplete documentation for RasterStatus::kSkipAndRetry in compositor_context.h.

In the PR, I've clarified the behavior when the thread merger is disabled and provided insights into potential performance implications when threads aren't merged. This addition offers a clearer understanding of the enum value's purpose and behavior.

Please review the PR when you have a moment. Thanks!

**Comment by yatendra2001** [comment]
hey @dkwingsmt , any update??

**Comment by dkwingsmt** [comment]
Fixed by https://github.com/flutter/engine/pull/44880.
