### ISSUE TITLE
Hot reload: "Some program elements" is confusing

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#13188]
Similar to https://github.com/flutter/flutter/issues/13187.

See logs below for an example of what I'm talking about in particular.

* [ ] Some "reloaded elements" appear more than once (same line number too)
* [ ] If elements are not in use I still get a warning to "restart the app" (it won't do anything)

**EDIT**: A second reload doesn't trigger this confusing message, I just get:

> Reloaded 2 of 466 libraries in 348ms.

## Steps to Reproduce

* `flutter create example`
* `cd example`
* Use an IDE that triggers auto-reload, and run the application (similar to `flutter run`)
* Add a file - i.e. `lib/src/file.dart`, with some fields/classes.
* Add an import (unused) to `lib/main.dart` to `lib/src/file.dart`

## Logs

> Reloaded 2 of 466 libraries in 433ms.
>
> Some program elements were changed during reload but did not run when the view was reassembled; you may need to restart the app for the changes to have an effect.
>
> • Food (lib/src/data.dart:6)
> • starchesRanked (lib/src/data.dart:33)
> • starchesRanked (lib/src/data.dart:33)

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-US, channel master)
    • Flutter at /Users/matan/git/flutter
    • Framework revision 167382480a (12 hours ago), 2017-11-23 10:24:16 +0100
    • Engine revision 93b2179597
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/matan/Library/Android/sdk
    • Unable to locate Android NDK.

    • Unable to locate compiler in Android NDK.

    • Platform android-25, build-tools 25.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b05)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.1, Build version 9B55
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 2.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b05)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.5)
    • Flutter plugin version 17.0
    • Dart plugin version 172.4343.25

[✓] Connected devices
    • iPhone SE • 9F33391B-D2D7-4E44-95C4-9A912FDCD824 • ios • iOS 11.1 (simulator)
```

**Comment by Hixie** [comment]
I believe we've removed this for now.
