### ISSUE TITLE
[iOS] Instead of Keyboard white space is shown when app is taken to background and then to foreground

### ISSUE THREAD

**Issue by prateekrk** [flutter/flutter#131840]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Have a TextField  widget with autofocus as true
2. Open another app for ex. notepad and start editing, so that keyboard appears
3. now start switching between flutter and notepad.

### Expected results

Keyboard should appear as its intended to, no white space should be shown instead of keyboard

### Actual results

When app is taken from background to foreground and when TextField is focused, instead of showing keyboard white space is shown.

### Code sample

<details>
<summary>code sample</summary>

```dart
// Note: to reproduce the issue easily i have added unfocus code when app moves to background.
void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> with WidgetsBindingObserver {
  @override
  void initState() {
    WidgetsBinding.instance.addObserver(this);
    // TODO: implement initState
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        backgroundColor: Colors.white,
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: Center(
            child: Container(
          padding: const EdgeInsets.all(10),
          child: TextField(
            autofocus: true,
            textInputAction: TextInputAction.search,
            onSubmitted: (value) => {print(value)},
          ),
        )));
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    switch (state) {
      case AppLifecycleState.paused:
      case AppLifecycleState.inactive:
      case AppLifecycleState.detached:
        if (mounted) {
          FocusScope.of(context).unfocus();
        }
        break;
      case AppLifecycleState.resumed:
        break;
      default:
        break;
    }
    super.didChangeAppLifecycleState(state);
  }
}
```
</details>

### Screenshots or Video

https://github.com/flutter/flutter/assets/35128534/da1b9e38-d942-4001-aa71-8f2554179a92

### Flutter Doctor output

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.3.10, on macOS 12.6 21G115 darwin-arm, locale
    en-IN)
    • Flutter version 3.3.10 on channel stable at
      /Users/kovallip/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (8 months ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/kovallip/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.4)
    • IntelliJ at /Users/kovallip/Applications/JetBrains Toolbox/IntelliJ IDEA
      Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.4)
    • IntelliJ at /Users/kovallip/Library/Application
      Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9225.16/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.3)
    • IntelliJ at /Users/kovallip/Library/Application
      Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9161.38/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.80.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • Prateek Koval li’s iPod (mobile) •
      d2a65f89a60a14829e79399fae6cb7250b82a27a • ios            • iOS 15.5 19F77
    • macOS (desktop)                  • macos
      • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)                     • chrome
      • web-javascript • Google Chrome 115.0.5790.170

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

**Comment by danagbemava-nc** [comment]
Hi @prateekrk, you are using an older version of the flutter framework. Kindly upgrade to the latest version of flutter stable (3.10.6) to see if you still experience this issue. 

If you do, please provide the updated output of `flutter doctor -v`. 

Thank you

**Comment by prateekrk** [comment]
I am able to reproduce this issue, it's reproducible consistently but not all the time. It does look ugly when our product's end user is stuck on the resized screen and sticky white space instead of the keyboard.
<details>
<summary>flutter doctor -v</summary>
[✓] Flutter (Channel stable, 3.10.6, on macOS 12.6 21G115 darwin-arm64, locale en-IN)
    • Flutter version 3.10.6 on channel stable at /Users/kovallip/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (3 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/kovallip/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.4)
    • IntelliJ at /Users/kovallip/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.4)
    • IntelliJ at /Users/kovallip/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9225.16/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.3)
    • IntelliJ at /Users/kovallip/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9161.38/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.80.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (4 available)
    • Android SDK built for arm64 (mobile) • emulator-5554                            • android-arm64  • Android 10 (API 29) (emulator)
    • Prateek Koval li’s iPod (mobile)     • d2a65f89a60a14829e79399fae6cb7250b82a27a • ios            • iOS 15.5 19F77
    • macOS (desktop)                      • macos                                    • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)                         • chrome                                   • web-javascript • Google Chrome 115.0.5790.170
    ! Error: Prateek Koval li’s iPod is busy: Waiting to connect and unlock the device. Xcode will continue when Prateek Koval li’s iPod is finished. (code -10)

[✓] Network resources
    • All expected network resources are available.
</details>

**Comment by prateekrk** [comment]
Yes, to reproduce I am doing that. Even if i don't do any focus-related stuff this issue is happening. Currently, I am using ipod.
I have attached the compressed video
[flutter keyboard issue 2.mp4.zip](https://github.com/flutter/flutter/files/12259959/flutter.keyboard.issue.2.mp4.zip)

**Comment by prateekrk** [comment]
1. Yes, To reproduce the issue I am doing that. Even if I don't do any unfocus and refocus-related stuff this issue is seen.
2. I am using iPOD 7th generation, iOS 15.5.

**Comment by danagbemava-nc** [comment]
Hi @prateekrk, I can't seem to reproduce this on my iPhone XS. The keyboard showed up for in every test I conducted. Can you try on the `master` channel to see if you still face this issue? 

You can use the master channel by running 

```
flutter channel master
flutter upgrade --force
```

**Comment by danagbemava-nc** [comment]
You can also try out the beta channel to see if it has been fixed there. Do let us know of the results after you have done some more testing. 

Thank you
