### ISSUE TITLE
Adapt "Dump frame raster stats for the current frame" of CLI to multi-view

### ISSUE THREAD

**Issue by dkwingsmt** [flutter/flutter#131892]
Currently the "Dump frame raster stats for the current frame" function of CLI (shortcut `J`), which calls `Shell::OnServiceProtocolRenderFrameWithRasterStats`, assumes that Flutter has a single view. The returned message contains:
* A snapshot of the last layer tree (got from `Rasterizer::DrawLastLayerTree`).
* The size of the last layer tree as `frame_width` and `frame_height`.

The file format does not seem compatible to multi-view. As I'm working on multi-view, I'm planning to keep the current behavior of targeting the implicit view (view 0) for now, but we'll need to make it somehow contain all views.

**Comment by christopherfujino** [comment]
From tool bug triage assigning p2, feel free to modify if priorities are different.

**Comment by jonahwilliams** [comment]
Closing as obsolete, we're removing the raster stats feature
