### ISSUE TITLE
Main branch documentation sometimes is updated to an older version

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#131832]
For example, right now master-api.flutter.dev is the documentation for 6cf50ef942, which is from 14h old at this point, while a few hours ago it was for 47b188e, which is 9h old at this point. I'm guessing we run the tests out of order but the documentation shard just unconditionally uploads to the server and overwrites whatever is there, even if it's newer?

cc @gspencergoog

**Comment by keyonghan** [comment]
This should be fixed with https://github.com/flutter/flutter/pull/132510
