### ISSUE TITLE
ShowBottomSheet show/hide by keyboard in Flutter (version 3.7.12 is show on keyboard, version >3.10.0 is behide by keyboard)

### ISSUE THREAD

**Issue by kylequang** [flutter/flutter#131909]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

showbottomsheet in flutter

### Expected results

showbottomsheet show above keyboard

### Actual results

version 3.7.12 It worked
version >3.10.0 showbottomsheet is behide the keyboard

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:auto_route/auto_route.dart';
import 'package:flutter/material.dart';


class DemoBottomSheetScreen extends StatelessWidget {
  const DemoBottomSheetScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: const NewWidget(),
    );
  }
}

class NewWidget extends StatelessWidget {
  const NewWidget({
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        const Text('Version 3.10.0'),
        ElevatedButton(
          child: const Text('showBottomSheet'),
          onPressed: () {
            showBottomSheet(
              context: context,
              builder: (BuildContext context) {
                return Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    const TextField(
                      decoration: InputDecoration(labelText: 'Enter'),
                    ),
                    const SizedBox(height: 16),
                    ElevatedButton(
                      onPressed: () {
                        Navigator.of(context).pop();
                      },
                      child: const Text('Close'),
                    ),
                  ],
                );
              },
            );
          },
        )
      ],
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

https://github.com/flutter/flutter/assets/67398186/94e23c69-31c2-45b1-ae79-423ad12a2bde

https://github.com/flutter/flutter/assets/67398186/10e7721b-4bf8-402c-8ea3-4fe09d2a3b89

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]

```
![Screenshot 2023-08-04 112443](https://github.com/flutter/flutter/assets/67398186/57a47527-e6fe-4fe2-b139-2f0ca01d1c47)

</details>

**Comment by 78sarmad** [comment]
It's working on Flutter 3.10.5. Try upgrading to latest Flutter version: `flutter upgrade`

<details>
  <summary>Screenshot</summary>
  
![Screenshot_1691129556](https://github.com/flutter/flutter/assets/67017318/bc1b721b-6964-41ae-b344-3a2c61b9f877)
</details>

**Comment by dam-ease** [comment]
Hi @kylequang. Thanks for filing this issue. This seems to have been fixed in newer versions of flutter, I can see it works fine on `3.10.6`. Kindly upgrade to the latest version of flutter to see this. Thank you.
Closing this as fixed, if you disagree, kindly comment and I'd reopen this.
