### ISSUE TITLE
Android predictive back route transitions

### ISSUE THREAD

**Issue by justinmc** [flutter/flutter#131961]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Flutter recently added support for Android's [predictive back](https://developer.android.com/about/versions/13/features/predictive-back-gesture) feature (https://github.com/flutter/flutter/issues/109513) in https://github.com/flutter/flutter/pull/120385 and https://github.com/flutter/engine/pull/39208.  However, that only works when exiting a Flutter app, and not between routes within a Flutter app.

### Proposal

Flutter should support route transitions that allow the user to peek behind the current route while performing a back gesture and cancel the route pop if desired.

This can't be done entirely in the framework if we want to show Android's back arrow too.  Flutter can't draw the back arrow with 100% accuracy because it is customizable by the system color theme, and the colors used for the arrow are not currently exposed via API.

We should be able to use the [onBackAnimationCallback](https://developer.android.com/reference/kotlin/android/window/OnBackAnimationCallback) API to get information about the back gesture as it happens and update the route transition animation.

<img width="156" alt="Screenshot 2023-08-04 at 2 52 57 PM" src="https://github.com/flutter/flutter/assets/389558/0812478b-abf7-475e-9dd7-03f4cdbcdfb7">

### Requirements

  1. Route transitions should look like the [spec](https://github.com/flutter/flutter/issues/131961#issuecomment-1865076080) (see video below).
  2. Canceling the gesture and committing the gesture should both work.
  3. The native back button should be shown during the gesture.
  4. The route transition should integrate well with Flutter's [existing route transition infrastructure](https://docs.flutter.dev/cookbook/animation/page-route-animation).
  5. Should be the default behavior for Android apps that enable predictive back? But should not interfere with other platforms and older versions of Android where the engine API isn't supported.
  6. Stretch goal: if possible, vertically dragging during the gesture should wiggle the animation vertically as it seems to do on native. This seems to require having Flutter track the gesture as well as native.

<details>

<summary>Spec animation</summary>

https://github.com/flutter/flutter/assets/389558/aabf4140-79a7-4826-9d61-d1bbc8a1ec53

</details>

**Comment by gmackall** [comment]
Note from android triage: Hey @justinmc, we believe you meant to assign this to yourself. If this is work that should be assigned to someone else, or the android team, feel free to un-assign and let us know!

**Comment by HansMuller** [comment]
Labeling this P3 only because we're not planning to address it in the near term. It's a good feature and we should provide it eventually.

**Comment by maRci002** [comment]
I've completed the implementation on the engine side flutter/engine#49093 and would greatly appreciate any feedback or review. Additionally, if needed, I'm ready and eager to work on the framework side as well.
