### ISSUE TITLE
[camera] iOS crash under AVCapturePhotoOutput capturePhotoWithSettings:delegate:] No active and enabled video connection

### ISSUE THREAD

**Issue by programer001** [flutter/flutter#131916]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I'm unable to force the crash on my device but I can see quite of lot of crashes occuring on iOS devices 
crash at -[FLTCam captureToFile:] (FLTCam.m:292)

Really hope someone can make some sense out of this..

### Expected results

use camera

### Actual results

crash

### Code sample

camera: ^0.9.8+1

show my code

enum TakePhotoStatus {
  /// 准备中
  preparing,

  /// 拍摄中
  taking,

  /// 待确认
  confirm,

  /// 已完成
  done
}

class FDCCustomCamera extends StatefulWidget {
  static const String saveDir = "tempImage";

  final double? aspectRatio;
  final double? pixelRatio;

  const FDCCustomCamera({Key? key, this.aspectRatio, this.pixelRatio})
      : super(key: key);

  @override
  State<FDCCustomCamera> createState() => _FDCCustomCameraState();
}

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.10.3, on macOS 13.4.1 22F770820d darwin-x64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.80.2)
[✓] Connected device (3 available)
[✓] Network resources

**Comment by dam-ease** [comment]
Hi @programer001. Thanks for filing this issue. Can you upgrade to the latest flutter version to confirm this issue still persists? If it does, kindly share a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code and also your full output on `flutter run -v`
Thank you
