### ISSUE TITLE
`gclient sync` failed to resolve dart-sdk 

### ISSUE THREAD

**Issue by eladmaimoni** [flutter/flutter#131980]
I'm attempting to compile a compatible version of the engine for my windows x64 machine.

After setting up the the engine development environment, I get the following when trying to run 'gclient sync':

```
PS C:\libs\engine> gclient sync --revision=src/flutter@cdbeda788a293fa29665dc3fa3d6e63bd221cb0d
Updating depot_tools...
1>________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress git@github.com:eladmaimoni/engine.git C:\libs\engine\src\_gclient_flutter_13uuz58b' in 'C:\libs\engine'
1>Cloning into 'C:\libs\engine\src\_gclient_flutter_13uuz58b'...
1>remote: Enumerating objects: 347735, done.
1>remote: Counting objects: 100% (351/351), done.
1>remote: Compressing objects: 100% (169/169), done.
1>remote: Total 347735 (delta 235), reused 252 (delta 182), pack-reused 347384
1>Receiving objects: 100% (347735/347735), 437.13 MiB | 11.84 MiB/s, done.
1>Resolving deltas: 100% (260308/260308), done.
Syncing projects: 100% (132/132), done.

________ running 'cipd ensure -log-level error -root C:\libs\engine -ensure-file C:\Users\mrmai\AppData\Local\Temp\tmpgtq5bxud.ensure' in '.'
Errors:
  failed to resolve flutter/dart-sdk/windows-arm64@git_revision:8d5b878d0a8a06326227cde88221eea7e15ee0c4 (line 8): no such tag
Error: Command 'cipd ensure -log-level error -root C:\\libs\\engine -ensure-file C:\\Users\\mrmai\\AppData\\Local\\Temp\\tmpgtq5bxud.ensure' returned non-zero exit status 1
Errors:
  failed to resolve flutter/dart-sdk/windows-arm64@git_revision:8d5b878d0a8a06326227cde88221eea7e15ee0c4 (line 8): no such tag
```

This seems similar to the issue here:

[dart roller failing to load windows artifacts](https://github.com/flutter/flutter/issues/115666)

I have no idea what is the dart roller, I'm just trying to build the engine. 

For reference, here is my `.gclient` file:

```
solutions = [
  {
    "managed": False,
    "name": "src/flutter",
    "url": "git@github.com:eladmaimoni/engine.git",
    "custom_deps": {},
    "deps_file": "DEPS",
    "safesync_url": "",
  },
]
```

**Comment by pieter-scholtz** [comment]
Have you tried an earlier revision ? such as 45f6e009110df4f34ec2cf99f63cf73b71b7a420

**Comment by eladmaimoni** [comment]
@pieter-scholtz I tried multiple revisions, I am currently working with f973fb4636d3719086474df35a261f9ce42bd311 (master branch) and it is working ok with my embedder as long as I don't update the flutter VS extension to the most recent version (then hot reload breaks, so much fun).

So I guess it can work with a few revisions. I am going to stick to this revision for now. just wish the whole embedder workflow would be more robust. it seems very fragile to try and match SDK + engine + vs extension.

**Comment by huycozy** [comment]
@eladmaimoni Given your last message, I feel safe to close this issue. In case you still have this issue on main/master branch, please write in the comments and I will re-open the issue. Thanks!
