### ISSUE TITLE
[Impeller] Auto-promote some uniform data to use push constants instead on Vulkan.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#131957]
Some amount of uniform data (something like ~128 bytes) can be promoted to use push constants for performance. This can be done transparently by ImpellerC. Today, most (if not all) of Impellers shaders contain uniforms that fit within the available range. We should investigate auto-promotion in the compiler and patch the reflector to generate the right metadata.

So far, we haven't come across instances where this has been the bottleneck. Though we have certainly [investigated using push-constants in specific cases](https://github.com/flutter/flutter/issues/131095).

Right now, this is low priority since this isn't a bottneck we've observed. But it may be a future improvement that'd be nice to have.

**Comment by chinmaygarde** [comment]
cc @gaaclarke @jonahwilliams

**Comment by jonahwilliams** [comment]
@gaaclarke investigated this a while back and found no performance difference. Given that we'd have to do binding differently for Vulkan if we used push constants (due to size limits) it seems like it would be more trouble than its worth.

**Comment by gaaclarke** [comment]
For reference: https://github.com/flutter/engine/pull/43984
