### ISSUE TITLE
Can `flutter_tools` terse-ify stack traces on failures?

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#13191]
The [`stack_trace`](https://pub.dartlang.org/packages/stack_trace) package has an option to remove/fold repetitive Dart SDK frames, which on the stack trace like listed on #13190, would make much more understandable. This looks like a big scary system crash when in reality it was just an NPE in the tooling, for example.

## Steps to Reproduce

See https://github.com/flutter/flutter/issues/13190.

**Comment by Hixie** [comment]
See also #4021.

I'd rather we avoided stack_trace. It generates stack traces that are less readable overall than the VM's default stack traces (because of doing weird things to the paths, etc). This messes with tooling that tries to process the stacks, for example.

**Comment by matanlurey** [comment]
It's not required to use stack_trace to rewrite - it has some decent folding infrastructure that is completely separate from how the traces are parsed and displayed for example.

**Comment by zoechi** [comment]
What about creating issues to get bad behavior fixed?

**Comment by Hixie** [comment]
Closing in favour of #4021 which will cover this.
