### ISSUE TITLE
[go_router] top level `routeMatchRedirect`

### ISSUE THREAD

**Issue by vasilich6107** [flutter/flutter#131919]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

There is case when the app should support routes from existing web site. The routing on the website could be wired.
Let's imagine that we have 2 routes on the web
`/id/reset/123454` and `/en/id/reset/123454` which both should be redirected to `/signin/password-reset`

It would be nice to have top level `routeMatchRedirect` stack. With objects `MatchRedirect(path, redirectFn)`.

Currently this could be achieved by placing some dummy `GoRoute` here and there with `redirect` function.
OR
Utilising `patternToRegExp` and `extractPathParameters` to make some matching magic.

On the other hand - the top level route match redirection stack could help to gather all such kind of redirects in one place.

### Proposal

It would be nice to have top level `routeMatchRedirect` stack. With objects `MatchRedirect(path, redirectFn)`.

**Comment by chunhtai** [comment]
I am not sure what's the ask. Can this be achieve with top level redirect? `GoRouter(redirect: ...)`
