### ISSUE TITLE
PersistentTabView Error

### ISSUE THREAD

**Issue by MosabShabat** [flutter/flutter#131949]
import 'package:persistent_bottom_nav_bar/persistent_tab_view.dart';
import '../../../common/widgets/exit_dialog.dart';
import '../../../constant/const.dart';
import '../../home_page/screens/home_page_screen.dart';
import '../controller/home_controller.dart';

class HomeScreen extends StatefulWidget {
  int page;
  HomeScreen({this.page = 0});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  var controller = Get.find<HomeController>();
  final persistentTabController = PersistentTabController(initialIndex: 0);

  List<PersistentBottomNavBarItem> navbarItems() {
    return [
      PersistentBottomNavBarItem(
        inactiveIcon: SvgPicture.asset(
          HomeLightIcon,
          width: 70,
          height: 70,
        ),
        icon: SvgPicture.asset(
          HomeBoldIcon,
          width: 70,
          height: 70,
        ),
        title: '',
        textStyle: TextStyle(fontFamily: Black),
        activeColorPrimary: mainColor,
        inactiveColorPrimary: Colors.grey,
      ),
      PersistentBottomNavBarItem(
        inactiveIcon: SvgPicture.asset(
          personLightIcon,
          width: 70,
          height: 70,
        ),
        icon: SvgPicture.asset(
          PersonBoldIcon,
          width: 70,
          height: 70,
        ),
        title: '',
        textStyle: TextStyle(fontFamily: Black),
        activeColorPrimary: mainColor,
        inactiveColorPrimary: Colors.grey,
      ),
      PersistentBottomNavBarItem(
        inactiveIcon: SvgPicture.asset(
          OpportunityUnSelectedIcon,
          width: 70,
          height: 70,
        ),
        icon: SvgPicture.asset(
          OpportunityIcon,
          width: 70,
          height: 70,
        ),
        title: '',
        textStyle: TextStyle(fontFamily: Black),
        activeColorPrimary: mainColor,
        inactiveColorPrimary: Colors.grey,
      ),
      PersistentBottomNavBarItem(
        inactiveIcon: SvgPicture.asset(
          LightLocationIcon,
        ),
        icon: SvgPicture.asset(
          BoldLocationIcon,
        ),
        title: '',
        textStyle: TextStyle(fontFamily: Black),
        activeColorPrimary: mainColor,
        inactiveColorPrimary: Colors.grey,
      ),
      PersistentBottomNavBarItem(
        inactiveIcon: SvgPicture.asset(
          LightMapIcon,
          width: 70,
          height: 70,
        ),
        icon: SvgPicture.asset(
          BoldMapIcon,
          width: 70,
          height: 70,
        ),
        title: '',
        textStyle: TextStyle(fontFamily: Black),
        activeColorPrimary: mainColor,
        inactiveColorPrimary: Colors.grey,
      ),
    ];
  }

  List<Widget> navBodies() {
    return [
      // HomePage(page: 0),
      Icon(Icons.person),
      Icon(Icons.person),
      Icon(Icons.shop),
      Center(
        child: Icon(Icons.map),
      ),
      Icon(Icons.location_on_outlined),
    ];
  }

  @override
  Widget build(BuildContext context) {
    return
        //  RefreshIndicator(
        //   onRefresh: _refreshData,
        //   child: WillPopScope(
        //     onWillPop: () async {
        //       showDialog(
        //         barrierDismissible: false,
        //         context: context,
        //         builder: (context) => exitDialog(),
        //       );
        //       return false;
        //     },
        //     child:
        PersistentTabView(
      context,
      navBarHeight: context.screenHeight / 12,
      controller: persistentTabController,
      screens: navBodies(),
      items: navbarItems(),
      backgroundColor: Colors.white,
      decoration: NavBarDecoration(
        borderRadius: BorderRadius.circular(1),
        colorBehindNavBar: whiteColor,
      ),
      navBarStyle: NavBarStyle.style15,
    );
    //   ),
    // );
  }
}
...this code give me this error >>>  
════════ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/box.dart': Failed assertion: line 325 pos 12: 'width > 0.0': is not true.
box.dart:325
2

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was
PersistentTabView
home_screen.dart:128
When the exception was thrown, this was the stack
=====================
so how fix it

**Comment by huycozy** [comment]
Hi @MosabShabat 
The issue seems to be related to a 3rd party package rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/BilalShahid13/PersistentBottomNavBar/issues) for better support there.

Closing, as this isn't an issue with Flutter itself.
