### ISSUE TITLE
Plugin: Dialer / Call action

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#132]
<a href="https://github.com/sethladd"><img src="https://avatars.githubusercontent.com/u/5479?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sethladd](https://github.com/sethladd)**
_Friday Aug 21, 2015 at 14:52 GMT_
_Originally opened as https://github.com/flutter/engine/issues/735_

---

Thanks!

**Comment by mit-mit** [comment]
Closing; this is now supported by passing a `tel:<phone no>` URL to the url_launcher plugin:
https://pub.dartlang.org/packages/url_launcher
