### ISSUE TITLE
[CP] Constrain _RenderScaledInlineWidget child size in computeDryLayout

### ISSUE THREAD

**Issue by LongCatIsLooong** [flutter/flutter#132095]
### Issue Link

https://github.com/flutter/flutter/issues/130588

### Commit Hash

55044a6

### Target

beta

### PR Link

https://github.com/flutter/flutter/pull/132096/

### Changelog Description

Address the issue that the previous CP didn't fully resolve: https://github.com/flutter/flutter/pull/131289

### Impacted Users

 `WidgetSpan` users

### Impact Description

Apps that use `WidgetSpans` in text widgets may throw an assertion when the text scale factor is set to certain values, due to floating point precision.

### Workaround

not available

### Risk

low

### Test Coverage

yes

### Validation Steps

Follow the repro steps in https://github.com/flutter/flutter/issues/130588

**Comment by CaseyHillers** [comment]
@chunhtai  can you review this CP request? If it looks good to you, add the "cp: approved" label.

**Comment by chunhtai** [comment]
change seems low risk, approved

**Comment by CaseyHillers** [comment]
Shipped in 3.13.0-0.4.pre beta
