### ISSUE TITLE
dart analyze/flutter_lints: Allow negated checking with early return for BuildContext.mounted

### ISSUE THREAD

**Issue by wesleym** [flutter/flutter#132018]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I would like to be able to check whether a BuildContext is mounted in an async function and to return early if the context is not mounted.

Here's an example of the code I want to write:

```
void _onShowButtonPressed(BuildContext context) async {
  // Simulates an asynchronous operation, like a network call.
  await Future.value();

  // Lint annotates the following line with `use_build_context_synchronously`.
  if (!context.mounted) return;
  showDialog(
    context: context,
    builder: (context) => const SimpleDialog(),
  );
}
```

I can do this, but `dart analyze` reports a finding:

```
% dart analyze
Analyzing mounteddemo...               2.1s

   info • lib/main.dart:32:10 • Don't use 'BuildContext's across async gaps. Try rewriting the code to not reference the
          'BuildContext'. • use_build_context_synchronously

1 issue found.
```

See the test case project: https://github.com/wesleym/mounteddemo.

### Proposal

Today, writing this code does not result in any `dart analyze` findings:

```
// Simulates another asynchronous operation.
await Future.value();

// No lint error is added on the following line.
if (context.mounted) {
  showDialog(
    context: context,
    builder: (context) => const SimpleDialog(),
  );
}
```

It would be nice if an early return of the form `if (!context.mounted) return` would allow use of the context without checking `mounted` again until the next awaited operation.

Alternatively, it would be nice if the line `if (!context.mounted) return` was not itself causing an analysis finding. It makes no sense to wrap that line in a check for whether the context is mounted.

**Comment by wesleym** [comment]
```
% flutter doctor -v
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F770820d darwin-arm64, locale en-CA)
    • Flutter version 3.10.6 on channel stable at /Users/wesley/usr/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (4 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/wesley/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.81.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (4 available)
    • Pixel 4a (mobile)        • adb-08041JEC201688-sXAWJ8._adb-tls-connect._tcp. • android-arm64  • Android 13 (API 33)
    • Wesley’s iPhone (mobile) • 00008030-000D78993C63802E                        • ios            • iOS 16.5.1 20F75
    • macOS (desktop)          • macos                                            • darwin-arm64   • macOS 13.4.1 22F770820d
      darwin-arm64
    • Chrome (web)             • chrome                                           • web-javascript • Google Chrome 115.0.5790.114

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by AsmaAlshameri** [comment]
PS C:\Users\Elite\StudioProjects\occasions_app> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.2, on Microsoft Windows [Version 10.0.17134.1], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.0)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[√] Android Studio (version 2022.2)
[√] VS Code (version 1.81.0)
[☠] Connected device (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Unable to run "adb", check your Android SDK installation and ANDROID_SDK_ROOT environment variable: C:\Users\Elite\AppData\Local\Android\Sdk\platform-tools\adb.exe
[√] Network resources

! Doctor found issues in 2 categories.

**Comment by huycozy** [comment]
Closing the issue as it's Dart linter's issue. Please see https://github.com/dart-lang/linter/issues/4007 which has been fixed recently.
