### ISSUE TITLE
Android - BasicMessageChannel.resizeChannelBuffer should use a non deprecated format and be more efficient

### ISSUE THREAD

**Issue by bleroux** [flutter/flutter#132048]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

https://github.com/flutter/engine/pull/41982 fixes `BasicMessageChannel.resizeChannelBuffer` which was broken.
The fix was based on the existing implementation which relies on a deprecated format (see https://github.com/flutter/engine/pull/41982#issuecomment-1657305288).

### Proposal

Replace `BasicMessageChannel.resizeChannelBuffer` implementation to rely on the expected and more efficient format.

While doing so, consider providing a similar helper for the `overflow` control message, see https://github.com/flutter/engine/blob/5b47c05770609a6f10d84e624c43c94bc7b4de4d/lib/ui/channel_buffers.dart#L447-L458

**Comment by reidbaker** [comment]
What is the tangible benefit we get from having an optimized resizeChannelBuffer? Can you walk me through a use case?

**Comment by bleroux** [comment]
I should have not emphasized the optimisation in the issue title, sorry for the confusion.

The performance gain will be very small. 

As pointed out in this comment, https://github.com/flutter/engine/pull/41982#issuecomment-1657305288, the main motivation for this PRs is to replace the format used for the 'resize' command with the expected one. The previous implementation relied on the deprecated format, see https://github.com/flutter/engine/blob/5b47c05770609a6f10d84e624c43c94bc7b4de4d/lib/ui/channel_buffers.dart#L440-L446.

Another motivation is to provide a similar implementation for the 'overflow' command.
