### ISSUE TITLE
App bar snaps demo misbehaving

### ISSUE THREAD

**Issue by xster** [flutter/flutter#13202]
In the gallery's contacts app, the overflow menu has options to toggle the app bar sliver behavior. The snapping option seems to have some strange behaviors. Sometimes, sliding halfway up doesn't trigger any snapping, then snapping happened in unexpected sudden ways at other times.

**Comment by Hixie** [comment]
If you can be more specific (e.g. a unit test :-) ) then maybe @HansMuller can take a look...

**Comment by HansMuller** [comment]
@xster just showed me the issue

The animation demo doesn't seem to exhibit these problems however it sets `CustomScrollView.physics` to an instance of a private scroll physics class that deals with snapping.

**Comment by Hixie** [comment]
@TahaTesser not sure how to triage this further, can you elaborate on what you need?

**Comment by Hixie** [comment]
@goderbauer figured out this is one of the gallery bugs.

**Comment by Hixie** [comment]
Leaving open because this is probably a bug in the component itself.

**Comment by pedromassangocode** [comment]
I wonder if we should update the title to better describe where the actual issue is.

**Comment by guidezpl** [comment]
Closing as N/A to https://github.com/flutter/gallery
