### ISSUE TITLE
BottomSheet should be useable to show on top of the screen

### ISSUE THREAD

**Issue by ride4sun** [flutter/flutter#13205]
## Steps to Reproduce
![1511588247073](https://user-images.githubusercontent.com/7740651/33251992-1141d102-d2f0-11e7-9783-9160f9e60d05.jpg)

I would like to show this kind of context menu on top of the screen. After trying out Scaffold/AppBar (didnt work because I didnt get the background transparent) and Dialog I ended up using the BottomSheet.
That works well but unfortunately, like the name indicates the context menu shows on the bottom.
Well it would be great if the BottomSheet could loose the Bottom and be just a `Sheet` and has some alignment parameter for top/bottom and be usable more generically. It seems like the change of the source should be small. And yes I could just do it but it seems like a very common Android use-case.

Also the ButtonSheet is currently showing a transparent overlay which cannot be changed and avoids any input in that area, besides dismissing the sheet itself. If the user wants to select multiple objects this would not be usable (see the pictures above where the user can select multiple objects to share)
`
[√] Flutter (on Microsoft Windows [Version 10.0.16299.64], locale en-US, channel alpha)
    • Flutter at c:\sdks\flutter
    • Framework revision e8aa40eddd (6 weeks ago), 2017-10-17 15:42:40 -0700
    • Engine revision 7c4142808c
    • Tools Dart version 1.25.0-dev.11.0

[√] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at C:\Users\ride4\AppData\Local\Android\sdk
    • Platform android-27, build-tools 27.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 19.1
    • Dart plugin version 172.4343.25

[√] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)
`

**Comment by Hixie** [comment]
I don't understand the effect you would like. Can you show some screenshots of what you mean and what you want/don't want? Also maybe why AppBar or Scaffold didn't work?

**Comment by zoechi** [comment]
It's about showing BottomSheet at the top, like this part in the screenshot above

![image](https://user-images.githubusercontent.com/405837/40562674-4d594346-6062-11e8-813d-26d8a1c21fe2.png)

**Comment by Hixie** [comment]
What's the difference between that and an AppBar?

**Comment by hillelcoren** [comment]
This would actually be useful in the app we're working on. 

We have a popup button at the top of the screen which triggers the bottom sheet to appear. Since the buttons are at the top it would be better if the 'bottom screen' was a 'top screen' which dropped down from the top.

![capture](https://user-images.githubusercontent.com/4629496/40716083-a5cf4630-63bc-11e8-93af-17973f7752cf.PNG)

**Comment by Hixie** [comment]
cc @willlarche to ask material if this widget idea is one they want to support.

If this idea becomes an official material widget, it makes sense for us to implement it. otherwise, probably best for this to be done as a separate package.

**Comment by willlarche** [comment]
Thanks for the designs! It's a cool idea. It's not a way we currently recommend using the bottom sheet so we wouldn't consider adding it as official functionality. But I think you have some options for a user experience that accomplishes your needs! Take a look at the following components:

- [Banner](https://material.io/design/components/banners.html)
- [Dropdown menu](https://material.io/design/components/menus.html#dropdown-menu)  (Not recommended for iOS)
- [Bottom app bar](https://material.io/design/components/app-bars-bottom.html)

Another possibility is just having the state of the actions in the app bar change when the user hits an action. But I don't think you'll be able to do as many as I see in your screenshot.

@hillelcoren , bottom app bar might work particularly well for you. By moving all the interaction to the bottom of the screen, the bottom sheet will appear in the same region as the action that triggered it. The user will not have to move their hand to use it, just their thumb.

**Comment by ColquePaxi** [comment]
Hi @ride4sun , I also looking for the CAB (Context Action Bar) in Flutter without success. If I find it, will post here, ok?

**Comment by ColquePaxi** [comment]
Hey @ride4sun , I loved your WhatsApp interface in Flutter!!!!! Using redux to me is awesome!!!! Do you have open code for this project in github to inspire newbie like me?

**Comment by ride4sun** [comment]
Thx, that would be great.

**Comment by De-Morgan** [comment]
You can use this workaround [package](https://pub.dev/packages/contextualactionbar) for now.

**Comment by De-Morgan** [comment]
Hello @ColquePaxi, here is a workaround [package](https://pub.dev/packages/contextualactionbar) for CAB
