### ISSUE TITLE
flutter test command timeout after 3.10

### ISSUE THREAD

**Issue by shinayser** [flutter/flutter#132084]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

We use fastlane to execute our end-to-end test codes on our CI/CD pipelines.

We have an issue on our side, that we need to retry once every time we build for iOS, but that is not the issue I am trying to report here.

The problem is that after upgrading to flutter 3.10, Fastlane seems to not detect that the command `flutter test` had stopped, which is causing the pipeline to get stuck for 12 minutes before Fastlane decides to continue (and perform the scriped retry).

```
[14:41:12]: ▸ 02:34 +0: loading /Users/ec2-user/builds/sWhe5qeA/0/ifood/enterprise/app-customer-benefits/ifoodoffice-benefits-flutter/benefits_app/integration_test/e2e_test/e2e_test.dart
[14:41:12]: ▸ Xcode build done.                                           132.7s
[14:41:12]: ▸ Failed to build iOS app
[14:41:12]: ▸ Swift Compiler Error (Xcode): No such module 'IncogniaBR'
[14:41:12]: ▸ /Users/ec2-user/builds/sWhe5qeA/0/ifood/enterprise/app-customer-benefits/ifoodoffice-benefits-flutter/benefits_app/ios/Runner/AppDelegate.swift:5:7
[14:41:12]: ▸ Could not build the application for the simulator.
[14:41:12]: ▸ 02:34 +0 -1: loading /Users/ec2-user/builds/sWhe5qeA/0/ifood/enterprise/app-customer-benefits/ifoodoffice-benefits-flutter/benefits_app/integration_test/e2e_test/e2e_test.dart [E]
[14:41:12]: ▸ TestDeviceException(Unable to start the app on the device.)
[14:41:12]: ▸ package:flutter_tools/src/test/integration_test_device.dart 63:7  IntegrationTestTestDevice.start
[14:50:38]: ▸ TimeoutException after 0:12:00.000000: Test timed out after 12 minutes.
```

So, my question is: what could have changed on the `flutter test` command that it is not launching exceptions anymore for Fastlane to catch?

### Expected results

flutter test should launch an exception

### Actual results

After 3.10, it seems to not be launching anymore.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.10.5, on Microsoft Windows [versÆo 10.0.22621.1992], locale pt-BR)
    ! Warning: `flutter` on your path resolves to C:\Users\shina\fvm\versions\3.10.5\bin\flutter, which is not inside your current Flutter SDK checkout at C:\Users\shina\fvm\default. Consider adding C:\Users\shina\fvm\default\bin
      to the front of your path.
    ! Warning: `dart` on your path resolves to C:\Users\shina\fvm\versions\3.10.5\bin\dart, which is not inside your current Flutter SDK checkout at C:\Users\shina\fvm\default. Consider adding C:\Users\shina\fvm\default\bin to
      the front of your path.
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Community Edition (version 2022.2)
[✓] IntelliJ IDEA Community Edition (version 2023.1)
[✓] VS Code (version 1.80.2)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 2 categories.

**Comment by shinayser** [comment]
I think the most weird question here is: why flutter test kept running even if Xcode build failed?

```Failed to build iOS app```

**Comment by huycozy** [comment]
Hi @shinayser 
Are you using flavor for your test? If it is, there is a known issue: https://github.com/flutter/flutter/issues/129338 (you can check a workaround at https://github.com/flutter/flutter/issues/129338#issuecomment-1613907710 if it can help). Otherwise, can you share a minimal sample code to reproduce this issue locally if any?

**Comment by shinayser** [comment]
Hey @huycozy we are using no flavors. That is the command we are running:

`flutter test -d #{device_name} integration_test/e2e_test/e2e_test.dart`

Yesterday we were able to fix our pipeline by running a `pod install` before the tests running, but this change was necessary only after 3.10 while in 3.8 it worked flawlessly.

**Comment by huycozy** [comment]
So, does it mean you can reproduce this locally? Could you please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so that we may verify this?
