### ISSUE TITLE
Add Minimum SDK Version Option to CLI `flutter create` command

### ISSUE THREAD

**Issue by progressive-galib** [flutter/flutter#132081]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

# Description
Currently, when creating a new Flutter project using the Flutter CLI, there is no option available to set the minimum SDK version directly during the project creation process. This feature request suggests adding an option to specify the minimum SDK version as a part of the project creation command.

i can assign myself on this and submit a pull request if newcomer my contributions are welcome

# Proposed Solution
Introduce a new flag or parameter in the `flutter create` command that allows developers to specify the desired minimum SDK version for the newly created project. For example:

``flutter create --min-sdk-version <sdk_version> my_project``

**Comment by christopherfujino** [comment]
@progressive-galib Is there a situation where it would not feasible to manually update the pubspec.yaml after creating? I'm inclined to close this as won't fix, as I'm not convinced the maintenance overhead is worth the added benefit, but I'm open to being convinced.
