### ISSUE TITLE
Failed assertion: line 739 pos 12: '_hold == null': is not true.

### ISSUE THREAD

**Issue by TienLen2808** [flutter/flutter#132067]
i am use the code :
bool isAutoScrolling = false; 

        _listViewProposeScrollController.position.isScrollingNotifier.addListener(() async {
          if (!_listViewProposeScrollController.position.isScrollingNotifier.value && !isAutoScrolling) {
            isAutoScrolling = true; // Bắt đầu cuộn tự động

            if (position > 12 && position < 24 ) {
              await _listViewProposeScrollController.animateTo(80,
                  duration: const Duration(milliseconds: 500),
                  curve: Curves.ease).whenComplete(() {
                isAutoScrolling = false; // Kết thúc cuộn tự động
              });
            }
            else if (position > 0 && position <= 12) {
              await _listViewProposeScrollController.animateTo(0,
                  duration: const Duration(milliseconds: 500),
                  curve: Curves.ease).whenComplete(() {
                isAutoScrolling = false; 
              });
            }
          }
        });
      });
error: if animateTo activity ,  user change screen

**Comment by darshankawar** [comment]
@TienLen2808 
Can you provide a [complete runnable but minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that throws the reported error along with `flutter doctor -v` ?
