### ISSUE TITLE
Wrong digits format shows in timepicker widget

### ISSUE THREAD

**Issue by m8811163008** [flutter/flutter#132032]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Add supported locate to `fa` in `MaterialApp` widget
```dart
...
              localizationsDelegates: const [
                GlobalCupertinoLocalizations.delegate,
                GlobalMaterialLocalizations.delegate,
                GlobalWidgetsLocalizations.delegate,
                ComponentLibraryLocalizations.delegate,
              ],
              supportedLocales: const [
                Locale("fa", "IR"),
              ],
              locale: const Locale("fa", "IR"),
...
```
then call the show `showTimePicker`.
It show the English number in `TimePickerEntryMode.dial` mode:

![flutter_01](https://github.com/flutter/flutter/assets/20933055/c8419a46-c278-4058-a445-075ccc6e4d3e)
This screen shot shows the widget shows 0 with farsi font and other numbers with English fonts.

Another problem is related with `TimePickerEntryMode.input ` mode:
It shows error message with correct digits in supported language and to confirm the dialog we should type English digits.
![flutter_02](https://github.com/flutter/flutter/assets/20933055/235371f7-0671-4e3d-b5f9-0912cbcc695f)
.This screen shot shows widget when you enter `input` mode.

When you confirm the time it shows wrong textfield error.
![flutter_03](https://github.com/flutter/flutter/assets/20933055/868e1995-1c0a-47a5-bcb8-4aa821515eef)
This screen shot shows widget with wrong error despite the input is correct.

### Expected results

1. Expect to show the correct digits in `fa` but here the digits are in English format 
2. Expect to confirm the selected time but shows the error message in `input` mode

### Actual results

1. Shows the wrong number format when selecting hour in dialog mode
2. Show the error message when the digits are in `fa` when time picker is in `input` mode

### Code sample

<details><summary>Code sample</summary>

```dart
...
              localizationsDelegates: const [
                GlobalCupertinoLocalizations.delegate,
                GlobalMaterialLocalizations.delegate,
                GlobalWidgetsLocalizations.delegate,
                ComponentLibraryLocalizations.delegate,
              ],
              supportedLocales: const [
                Locale("fa", "IR"),
              ],
              locale: const Locale("fa", "IR"),
...
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]
![flutter_01](https://github.com/flutter/flutter/assets/20933055/8236277e-f4ee-4a45-b92d-c5a520eb3c3b)
![flutter_02](https://github.com/flu
![flutter_03](https://github.com/flutter/flutter/assets/20933055/640b073d-3adc-47d5-8a55-db914c54df76)
tter/flutter/assets/20933055/d99973ab-ca3f-41c7-ba57-f3ad1fc1e6e0)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.10.5, on macOS 13.0 22A380 darwin-x64, locale en-US)
    • Flutter version 3.10.5 on channel stable at /Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (8 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/viraminer/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] VS Code (version 1.79.2)
    • VS Code at /Users/viraminer/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • ViraMiner’s iPhone (mobile) • 00008030-0018391622FA802E • ios            • iOS 16.5.1 20F75
    • macOS (desktop)             • macos                     • darwin-x64     • macOS 13.0 22A380 darwin-x64
    • Chrome (web)                • chrome                    • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by m8811163008** [comment]
Hi @dam-ease , I can confirm the issue is similar to [#85527](https://github.com/flutter/flutter/issues/85527) and it is still shows English digits at `TimePickerEntryMode.dial` mode

**Comment by m8811163008** [comment]
I had the same issue with you sample code on my iOS device, here is the screen shots but with Material2 the digits issue which was showing the English number has resolved but still show the error message in `input` mode.
<details>
<summary>screen shots of Material3</summary>
![flutter_01](https://github.com/flutter/flutter/assets/20933055/40a7064b-1eec-4339-baf9-b4d372243fb9)
![flutter_02](https://github.com/flutter/flutter/assets/20933055/a5d786b8-fde4-47bf-a3d1-ab838f56340b)

</details>
<details>
<summary> screen shots of Material2</summary>

![flutter_03](https://github.com/flutter/flutter/assets/20933055/3731e02c-f03d-4504-8a61-1f211ae52769)
![flutter_04](https://github.com/flutter/flutter/assets/20933055/43ce71f9-1719-4429-b925-1df811f52aee)

</details>

**Comment by dam-ease** [comment]
Hi @m8811163008. Thanks for these. Please can you file a separate issue for that of the regression as described here https://github.com/flutter/flutter/issues/132032#issuecomment-1669063690 so it's easier to track? For the issue with error being thrown when inputting correct time which is similar to an already open issue https://github.com/flutter/flutter/issues/85527, I'd be closing this in favour of the already open one, kindly comment on the issue, upvote for attention and follow up on it for updates. If you disagree with these, kindly comment and I'd reopen this
