### ISSUE TITLE
[video_player] Does the video_player have record video and/or take snapshot feature of any video player?

### ISSUE THREAD

**Issue by izzabellerina** [flutter/flutter#132011]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Do you have a feature like recording video and taking a snapshot of any video player? If not, do you have any suggestions on how to do that? So, thank you in advance.

### Proposal

-

**Comment by stuartmorgan** [comment]
`video_player` is for playback, not recording. Closing as out of scope.
