### ISSUE TITLE
[Impeller] Investigate "DlCanvas implementation wrapping Aiks canvas" 90th percentile increase

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#132071]
https://github.com/flutter/engine/pull/44248 seems to have improved the average rasterizer time for the backdrop filter benchmark, but potentially raised the floor on the gallery 90th percentile test (albeit the attribution is tenuous).  Can we double check the implementation to make sure there isn't something we missed that might negatively effect the 90th percentile 

## backdrop filter average raster time benchmark drop

<img width="1432" alt="Screenshot 2023-08-07 at 10 39 39 AM" src="https://github.com/flutter/flutter/assets/30870216/3fda00e7-41a3-4aee-967a-268f20e2a849">

## gallery 90th percentile increase
(notice that the floor never reaches 10ms around the time that PR landed)
<img width="1713" alt="Screenshot 2023-08-07 at 10 11 58 AM" src="https://github.com/flutter/flutter/assets/30870216/e345a034-1e47-44c7-aac7-2e461d0a3297">

cc @dnfield

**Comment by gaaclarke** [comment]
I think it's easiest if @dnfield just gives it a look to see if there is some easy tweak we could make.  He won't be available for a while though.

**Comment by jonahwilliams** [comment]
Here are some CPU usage numbers from the iOS:

https://flutter-flutter-perf.skia.org/e/?formulas=filter(%22sub_result%3Daverage_cpu_usage%22)&selected=commit%3D36135%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253Daverage_cpu_usage%252Ctest%253Ddraw_points_perf_ios__timeline_summary%252C

drawPoints dropped by 50%, a few regressed, a few improved. I think we should track down the regressions.

**Comment by jason-simmons** [comment]
Some other benchmarks regressed noticeably in that engine roll.

For example, this query shows `post_backdrop_filter_perf_ios__timeline_summary`/`average_cpu_usage` up by 25% and `backdrop_filter_perf_ios__timeline_summary`/`average_gpu_usage` up by 40%:

https://flutter-flutter-perf.skia.org/e/?begin=1688572077&end=1691427625&keys=X8a443eafed2166315999f8d7eb6fd852&requestType=0&selected=commit%3D36136%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253Daverage_cpu_usage%252Ctest%253Dpost_backdrop_filter_perf_ios__timeline_summary%252C&xbaroffset=36136

**Comment by gaaclarke** [comment]
@zanderso @chinmaygarde what do you want to do about that PR?  Looks like its benefits are complicated and I looked at the PR and it still had some unanswered comments on it.  Dan isn't going to be available for a minute to investigate.

**Comment by zanderso** [comment]
Let's revert. @dnfield can re-land next week after investigating the regressions noted here.

**Comment by chinmaygarde** [comment]
The revert has landed and I have filed an issue tracking re-landing with references https://github.com/flutter/flutter/issues/132416. Closing this.
