### ISSUE TITLE
Impeller iOS - ImageFilter.blur causes "Grain/Pixilated" blur effect on a physical iOS device that is of model iPhone 13 Pro or later.

### ISSUE THREAD

**Issue by ehw-dawn** [flutter/flutter#132045]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Make sure to use latest version of Flutter and have Impeller engine enabled.
2. Run code sample on physical iOS device that is a iPhone 13 Pro or later version.

### Expected results

What is expected to render - and what renders when running on a physical iOS device that is of a model earlier than iPhone 13 Pro. 

The expected output is also rendered correctly on any physical iOS device when the Impeller engine is disabled.

See image marked with [1] in Screenshots or Video section.

### Actual results

What is rendered when running on a physical iOS device that is of model iPhone 13 Pro or later.

See image marked with [2] in Screenshots or Video section.

### Code sample

<details><summary>Code sample</summary>

```dart

import 'dart:ui';

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const Body(),
    );
  }
}

class Body extends StatelessWidget {
  final blur = 10.0;
  const Body({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Impeller Blur Example'),
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
      ),
      body: ImageFiltered(
        imageFilter: ImageFilter.blur(
          sigmaX: blur,
          sigmaY: blur,
          tileMode: TileMode.decal,
        ),
        child: Image.network('https://upload.wikimedia.org/wikipedia/commons/4/4f/Dash%2C_the_mascot_of_the_Dart_programming_language.png')
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

| Expected | Actual |
| -- | -- |
| <img src="https://github.com/flutter/flutter/assets/112851402/b46d399d-1665-4810-a812-a7635528e44f" /> | <img src="https://github.com/flutter/flutter/assets/112851402/9633c40d-516b-4d1c-a09a-d541aa26c6ae" /> |

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.10.5, on macOS 13.5 22G74 darwin-arm64, locale en-DK)
    • Flutter version 3.10.5 on channel stable at /Users/a/b/c
    • Upstream repository ssh://git@github.com/flutter/flutter.git
    • FLUTTER_GIT_URL = ssh://git@github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (8 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/a/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
       • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.80.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] VS Code (version 1.74.2)
    • VS Code at /Users/a/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)

[✓] Network resources
    • All expected network resources are available.


```

</details>

**Comment by ehw-dawn** [comment]
Hi @danagbemava-nc, I checked on the master channel and iPhone 13 Pro, and the issues is no longer present. 

Would you perhaps know when the fix on the master channel is scheduled to be pushed to the stable channel?

**Comment by danagbemava-nc** [comment]
Hi @ehw-dawn, thanks for checking. Unfortunately, I cannot say when it will be available on the stable channel. You could check on the beta channel as well to see if it has been fixed there. If it has been fixed there, then there's a high probability that it will be in the next stable channel. 

Per our triage policy, I'll be closing this since it has been fixed on the master channel.

Thank you
