### ISSUE TITLE
Support for animated SVG 

### ISSUE THREAD

**Issue by dharanidharandharmasivam** [flutter/flutter#132029]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I tried to use animated svg in my mobile application, but currently, this is not supported with Flutter. So I tried other packages on Pub, the most commonly used package is [flutter_svg](https://pub.dev/packages/flutter_svg), but with this also I can't use my svg image, since is already an animated svg image. 

### Proposal

My requirement is to use the animated SVG image in my Flutter application, don't want to animate the SVG image in my application or use another package on pub. So, if you provide support to use animated SVG images either in Flutter or any other packages on pub would be much better. Kindly help me out with this scenario. I have attached simple animated SVG image below.

![animated_svg (1)](https://github.com/flutter/flutter/assets/19346074/1c86ccf1-faf2-4f80-88c2-3099d7006993)

**Comment by dam-ease** [comment]
Hi @dharanidharandharmasivam. Thanks for proposing this. Are there specific issues you are encountering with these other packages on pub that suit this use case?
You might want to try out https://pub.dev/packages/rive or https://pub.dev/packages/lottie

**Comment by dharanidharandharmasivam** [comment]
Hi @dam-ease ,
Thanks for the suggestions. While using the animated SVG images in **flutter_svg** package faced some exceptions. Currently using 3.7.12 version, I ensured with the latest Flutter package, in that too facing exception. I suspect this is due to the package that doesn't support animated SVG and supports static SVG images.

Here is the code which I have used

```
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';

void main() {
  runApp((ExampleApp()));
}

class ExampleApp extends StatelessWidget {
  ExampleApp({key});

  @override
  Widget build(BuildContext context) => MaterialApp(
        home: SvgPicture.asset('assets/animated_svg.svg'),
      );
}
```

And I am unable to use Rive & Lottie, since my input will be animated svg, if needs to use Rive & Lottie, format conversion needs to be carried riv & json respectively, can't use my animated svg with these packages. Please let me know if you any other information.

**Comment by dam-ease** [comment]
Hi @dharanidharandharmasivam. Thanks for your response. As regards supporting showing animations in SVG format using the `flutter_svg` package, there are some issues filed in the repo regarding that and per this https://github.com/dnfield/flutter_svg/issues/772#issuecomment-1242169457, has been closed. Converting to other file formats, do you experience any issues?
