### ISSUE TITLE
[camera_avfoundation] Occasional crash when recording with camera

### ISSUE THREAD

**Issue by misos1** [flutter/flutter#132073]
### Is there an existing issue for this?

- [x] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run test code in debug mode
2. It will show some message and then exits, continue to step 1 until crash happens ("Lost connection to device." is ok)

Alternatively run this in terminal, it will stop when crash happens:

```
while flutter run -d your_device_id_or_name --no-build; do; done
```

It may occasionally stop without triggering a crash with `Error launching application on ....` or iphone may lock screen so it would be optimal to adjust auto-lock timeout.

Reproduction of https://github.com/flutter/flutter/issues/69874.

Unfortunately this is really hard to reproduce. It may be easier on older devices like iphone 7 plus. It usually takes up to 10 runs to reproduce on my device but on newer and faster devices it could take much much more. I was not able to reproduce it by using hot restart.

Unfortunately it seems `--no-build` has no effect so it can take a really long time to trigger this.

As that error message says `appendPixelBuffer` should not be called when `readyForMoreMediaData` is false so it should first check `readyForMoreMediaData` and only when it is true call `appendPixelBuffer` similarly as is done with `appendSampleBuffer`. `appendPixelBuffer` probably directly calls `appendSampleBuffer` and will not do this for you. Also I do not see any reason why `AVAssetWriterInputPixelBufferAdaptor` is used there at all. I only ever used it when I appended samples which I rendered myself. It provides `pixelBufferPool` which can be used with `CVPixelBufferPoolCreatePixelBuffer`. It just provides a pool of pixel buffers into which you can render and pass to `appendPixelBuffer`. Here in `FLTCam` every sample buffer you get in `captureOutput` is already provided to you so there is no use for pool provided by `AVAssetWriterInputPixelBufferAdaptor` and no benefit for using it and you could just simply use `appendSampleBuffer` as well.

When I add some logging before `appendPixelBuffer`:
```
NSLog(@"%i %li %li %li", _videoWriterInput.readyForMoreMediaData, nextSampleTime.value, nextSampleTime.timescale, nextSampleTime.epoch);
```
```
1 82972987238333 1000000000 0
1 82973720556125 1000000000 0
0 82973753888833 1000000000 0
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '*** -[AVAssetWriterInputPixelBufferAdaptor appendPixelBuffer:withPresentationTime:] A pixel buffer cannot be appended when readyForMoreMediaData is NO.'
```

And with this it no longer happens (still no crash even after more than 100 runs):
```
      if(_videoWriterInput.readyForMoreMediaData) {
        [_videoAdaptor appendPixelBuffer:nextBuffer withPresentationTime:nextSampleTime];
      }
```

### Expected results

No crash.

### Actual results

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '*** -[AVAssetWriterInputPixelBufferAdaptor appendPixelBuffer:withPresentationTime:] A pixel buffer cannot be appended when readyForMoreMediaData is NO.'
libc++abi: terminating with uncaught exception of type NSException
* thread #6, queue = 'io.flutter.camera.captureSessionQueue', stop reason = signal SIGABRT
```

### Code sample

<details><summary>Code sample</summary>

```dart
import "dart:io";
import "package:flutter/material.dart";
import "package:camera/camera.dart";

void main() {
	runApp(const MyApp());
}

class MyApp extends StatelessWidget {
	const MyApp({super.key});
	@override Widget build(BuildContext context) => const MaterialApp(home: MyHomePage());
}

class MyHomePage extends StatefulWidget {
	const MyHomePage({super.key});
	@override State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
	bool loading = true;
	String where = "";
	late CameraController camera_cont;

	@override void dispose() {
		camera_cont.dispose();
		super.dispose();
	}

	@override void initState() {
		super.initState();
		init_camera();
	}

	init_camera() async {
		final cameras = await availableCameras();
		camera_cont = CameraController(cameras.firstWhere((camera) => camera.lensDirection == CameraLensDirection.back), ResolutionPreset.ultraHigh);
		await camera_cont.initialize();
		await camera_cont.startVideoRecording();
		setState(() => loading = false);
		await Future.delayed(const Duration(milliseconds: 100));
		final file = await camera_cont.stopVideoRecording();
		await File(file.path).delete();
		setState(() => where = "Sorry, nothing this time, please try again");
		await Future.delayed(const Duration(milliseconds: 3000));
		exit(0);
	}

	@override Widget build(BuildContext context)
	{
		if(loading)return const Center(child: CircularProgressIndicator());
		else return Stack(
			alignment: Alignment.center,
			children: [
				CameraPreview(camera_cont),
				Text(where, textAlign: TextAlign.center),
			],
		);
	}
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.5 22G74 darwin-x64)
```

</details>

**Comment by danagbemava-nc** [comment]
I attempted to reproduce this on my iPhone XS but I did more than 10 re-runs and I couldn't seem to reproduce the issue. I always got `Lost connection to device`, logs shared below. 

Labeling for further investigation

<details>
<summary>logs</summary>

```
Launching lib/main.dart on Nexus in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: X8NNQ9CYL2
Xcode build done.                                           43.0s
(lldb) 2023-08-08 10:26:12.528172+0000 Runner[627:30869] [VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(37)] Using the Impeller rendering backend.
Warning: Unable to create restoration in progress marker file
fopen failed for data file: errno = 2 (No such file or directory)
Errors found! Invalidating cache...
The selected imageFormatGroup is not supported by iOS. Defaulting to brga8888
[client] No error handler for XPC error: Connection invalid
Lost connection to device.

Exited.
```
</details>

**Comment by ob-juliandixon** [comment]
So if I am reading this correctly, it sounds like the fix is to add this to FLTCam.m?

```
if(_videoWriterInput.readyForMoreMediaData) {
        [_videoAdaptor appendPixelBuffer:nextBuffer withPresentationTime:nextSampleTime];
}
```

I've got a similar issue with one of my applications that centers around recording video. I will try and use a custom fork with this change in my project and see if that alleviates the problem

**Comment by bgenidy** [comment]
+1 on this bug. I have an Iphone 13 Pro running iOS Version 17.2.1 and I pretty much can't get more than 3-5 seconds into a recording before it crashes the entire app when running in debug (can consistently repro).

When using release mode it seems to be working fine, so I think there is something with the way the debugger and the camera play together that is causing this problem.

**Comment by bgenidy** [comment]
@ob-juliandixon is the fix you have above working? and any reason why your going the fork route instead of creating a PR against the main repo?

**Comment by misos1** [comment]
@bgenidy
> When using release mode it seems to be working fine, so I think there is something with the way the debugger and the camera play together that is causing this problem.

It is probably because in debug almost everything is slower so it has a harder time to append pixel buffers and there is a higher chance it will be not ready. I would not assume that it is working correctly in release, there is just much lower chance for it to happen.

> is the fix you have above working? and any reason why your going the fork route instead of creating a PR against the main repo?

It is much less work (btw I am planning to do PR).

**Comment by hellohuanlin** [comment]
Possible related to https://github.com/flutter/flutter/issues/69874
