### ISSUE TITLE
`Platform.environment` is an unmodifiable map

### ISSUE THREAD

**Issue by WorikQCI** [flutter/flutter#132088]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

* Dart code that depends on, say,  `bool.hasEnvironment("QQQ")` in production
* It cannot be tested because `Platform.environment['QQQ'] = 1; // or whatever value` throws an exception

### Expected results

Set environment variables at test time

### Actual results

Exception is thrown

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:test/scaffolding.dart';
void main() async {
  test("Cannot set environment in a test", () async {
    Platform.environment['QQQ'] = 'foo';

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by stuartmorgan** [comment]
Please file issues with Dart SDK libraries against the Dart project, rather than Flutter.

(In this case, it would likely be closed there as well however, as that's [explicitly documented](https://api.dart.dev/stable/3.0.7/dart-io/Platform/environment.html) behavior.)
