### ISSUE TITLE
[framework/tool/dart] clean up single widget reload functionality.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#132157]
The single widget reload functionality was an experimental feature that was conditionally enabled to prototype faster hot reloads. Experimental data from beta branches/g3 showed no improvement/regression in performance for the change, so it was never rolled out. Nevertheless, there are still a few pieces of code that need to be cleaned up.

- [ ] remove the [Widgetcache](https://github.com/dart-lang/sdk/blob/585c34b4d1d34eecc3d6bdbe1983f5c1ef8ceace/pkg/front_end/lib/widget_cache.dart#L11
) and associated cmd line flags from the front_end and frontend_server packages: 
- [x] Remove the [DebugReassembleConfig](https://github.com/flutter/flutter/blob/e2badf38570db7ee6526b778549d300b7d1c9ba5/packages/flutter/lib/src/foundation/binding.dart#L997) class from the framework
- [x] Remove the [singleWidgetReload](https://github.com/flutter/flutter/blob/e2badf38570db7ee6526b778549d300b7d1c9ba5/packages/flutter_tools/lib/src/features.dart#L144) feature flag and associated code from the flutter tool.

The only caveat is that the dart SDK should be updated last.

**Comment by Hixie** [comment]
Dart side: https://dart-review.googlesource.com/c/sdk/+/319871
