### ISSUE TITLE
SemanticsAction Handler provided to addAction does not get invoked

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#13219]
See https://github.com/flutter/flutter/pull/13152#discussion_r152700737

/cc @yjbanov

**Comment by goderbauer** [comment]
Actually, this is a bug/feature in how Android prior to Oreo handles the "tap" accessibility event and it has caused confusion before (e.g. https://github.com/flutter/flutter/issues/1715#issuecomment-311199707). Here is what is happening:

On Android prior to Oreo TalkBack doesn't dispatch the double tap as a [`AccessibilityAction.ACTION_CLICK`](https://developer.android.com/reference/android/view/accessibility/AccessibilityNodeInfo.AccessibilityAction.html#ACTION_CLICK) to the currently focused accessibility element, as one would expect. Instead, it generates pointer down and up events and dispatches them to whatever is at the center of the currently focused accessibility element. The action is therefore handled by the gesture detector responsible for that area and not by the `SemanticsAction` handler provided to `addAction`. 

Starting with Android Oreo (and on all versions of iOS) the tap event is correctly dispatched to the SemanticsAction handler as expected.

As discussed in https://github.com/flutter/flutter/issues/1715#issuecomment-311806274 there is no good way to "fix" the broken behavior in Android prior to Oreo.

**Comment by Hixie** [comment]
Can we make sure the API docs document this in detail?
