### ISSUE TITLE
Rendering bug on Android material 

### ISSUE THREAD

**Issue by KevinTheGray** [flutter/flutter#13216]
Getting very odd rendering behavior on some mix of material components, though not really sure what's causing it.  I've seen it mainly on older devices, one specifically is a Samsung S6 running Android 5.0.1

I've listed the steps to reproduce, and have noticed that if I remove the border radius from the material, it seems to fix it, but not always.

## Steps to Reproduce
- Start a new flutter project and use this code
```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Android Bug',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'Android Bug'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: new Container(
        height: 250.0,
        child: new Padding(
          padding: new EdgeInsets.all(10.0),
          child: new Material(
            borderRadius: new BorderRadius.all(
              new Radius.circular(4.0),
            ),
            elevation: 1.0,
            color: Colors.white,
            child: new Column(
              children: <Widget>[
                new Expanded(
                  child: new Text(
                    "Lorem ipsum dolor sit amet, consectetur adipiscing "
                        "elit, sed do eiusmod tempor incididunt ut labore "
                        "et dolore magna aliqua. Ut enim ad minim veniam, "
                        "quis nostrud exercitation ullamco laboris nisi "
                        "ut aliquip ex ea commodo consequat.",
                  ),
                ),
                new MaterialButton(
                  color: Colors.blue,
                  child: new Text("Press Me"),
                  onPressed: () {},
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```
- Run it on an Android device, the older the better

## Flutter Doctor
[✓] Flutter (on Mac OS X 10.12.6 16G1036, locale en-US, channel master)
    • Flutter at /Users/KG/Developer/Flutter/flutter
    • Framework revision ea34bb5c29 (8 days ago), 2017-11-20 03:31:44 -0500
    • Engine revision 4733e33737
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.0)
    • Android SDK at /Users/KG/Library/Android/sdk
    • Platform android-27, build-tools 27.0.0
    • ANDROID_HOME = /Users/KG/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.1, Build version 9B55
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio 3.0RC2.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.2.6)
    • Flutter plugin version 19.1
    • Dart plugin version 172.4343.25

[✓] Connected devices
    • SCH I545              • 5f0daba2                                 • android-arm • Android 5.0.1 (API 21)

![image](https://user-images.githubusercontent.com/9346834/33291164-ebd41ab2-d392-11e7-85e1-0967fcbd9c18.png)

**Comment by KevinTheGray** [comment]
Also seen consistently on a Motorola XT1032 running Android 5.1

**Comment by eseidelGoogle** [comment]
@xster @chinmaygarde could this be the skia rendering issue we had with font textures showing up in a different way?

**Comment by eseidelGoogle** [comment]
Nevermind, probably not since this appears to be a consistent rendering error, not a flake?

**Comment by KevinTheGray** [comment]
it will consistently happen, but it seems to consistently render differently per device.  For example, the above image is of the Samsung.  It always renders like that.  I'll a shot of the Motorola, which always renders like that.  There should be text above the button

![image](https://user-images.githubusercontent.com/9346834/33292021-c85723b0-d395-11e7-9829-60dedeb16dca.png)

**Comment by xster** [comment]
Looking at it now. Just pure guessing, I'm suspecting that some OEMs are reporting system insets differently.

**Comment by xster** [comment]
To make sure I understand the issue correctly, is it correct that the problems are:
1- the button in the first screenshot should be fully visible and isn't; and
2- the text is missing?

**Comment by xster** [comment]
Repro'ed on a Moto E

**Comment by xster** [comment]
This is pretty strange

![flutter_01](https://user-images.githubusercontent.com/156888/33919975-4ae2a332-df70-11e7-862e-01a696b36f20.png)

Also taking a screenshot with the resident runner makes it work. Most likely an engine problem.

**Comment by xster** [comment]
Some more observations:
Avoiding the combination of PhysicalModel (from Material) and ClipRRect (from border radius) works. 

Larger parent box has less issues than smaller boxes. 

It's possible to create a clipping 'band' both on top and at the bottom depending on the position.

**Comment by xster** [comment]
https://bugs.chromium.org/p/skia/issues/detail?id=7410

**Comment by brianosman** [comment]
I think I have a fix for this, currently testing within Skia. @KevinTheGray, are you sure that was an S6, and not an S4? Your `flutter doctor` output includes this:

• SCH I545 • 5f0daba2 • android-arm • Android 5.0.1 (API 21)

... which looks like an S4. That would also be in-line with all the other devices where this bug has been seen - it appears to only affect Adreno 3xx series GPUs.

**Comment by KevinTheGray** [comment]
@brianosman you're correct, it was an S4.  Sorry about that.  Glad to know you'll have a fix coming :+1:

**Comment by chinmaygarde** [comment]
This has been fixed.
