### ISSUE TITLE
PageView initialPage not work at hybrid app in release mode

### ISSUE THREAD

**Issue by CliffVardant** [flutter/flutter#132117]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1.Embed a flutter module in a native app
2.Specify an entry point
3.Set initialPage for PageView
4.Open flutter page from native 

### Expected results

When I open the page, pageView can init  and scroll to the page i want.

### Actual results

The first time to open flutter page, initialPage works fine. 
Then the second and after times to open flutter page, whatever the initialPage set, page always 0 (only in release mode).
It seens

### Code sample

```dart
PageController? _pageController;
  TabController? _tabController;
  var titleArr = ['Page 1'.tr, 'Page 2'.tr];

  @override
  void initState() {
    super.initState();
    _tabController = TabController(
        length: titleArr.length, vsync: this, initialIndex: widget.defaultPage);
    _pageController = PageController(initialPage: widget.defaultPage, keepPage: false);
  }


Widget createContainerView() {
    double? page;
    if (_pageController!.hasClients) {
      page = _pageController!.page;
    }
    print(
        "_PageState page: $page, initialPage: ${_pageController!.initialPage}, initialScrollOffset: ${_pageController!.initialScrollOffset}");
    return Container(
        child: Column(
          children: [
            Align(
              alignment: Alignment.centerLeft,
              child: SizedBox(
                height: 38,
                child: TabBar(
                    controller: _tabController,
                    physics: const BouncingScrollPhysics(),
                    labelStyle: TextStyle(),
                    unselectedLabelStyle: TextStyle( ),
                    isScrollable: true,
                    onTap: _onTabbarChange,
                    tabs: titleArr.map((e) => Tab(text: e)).toList()),
              ),
            ),
            Expanded(
                child: PageView(
              physics: const NeverScrollableScrollPhysics(),
              controller: _pageController,
              onPageChanged: _onPageViewChange,
              children: [
                Container(color: Colors.blue,),
                Container(color: Colors.green,),
              ],
            )),
          ],
        ));
  }
``` 

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

The first time open flutter page:

```
2023-08-08 16:54:44.001828+0800 TradeBook[1017:285744] flutter: Entrypoint args-page: 1
2023-08-08 16:54:44.010732+0800 TradeBook[1017:285744] flutter: _PageState page: null, initialPage: 1, initialScrollOffset: 0.0
2023-08-08 16:54:44.092700+0800 TradeBook[1017:285744] flutter: PageView (get page) pixels: 375.0, minScrollExtent: 0.0, maxScrollExtent: 375.0
2023-08-08 16:54:44.092799+0800 TradeBook[1017:285744] flutter: PageView (getPageFromPixels) pixels: 375.0, _initialPageOffset: 0.0, actual: 1.0, round: 1.0
2023-08-08 16:54:44.092857+0800 TradeBook[1017:285744] flutter: _PageState page: 1.0, initialPage: 1, initialScrollOffset: 0.0
FlutterBaseViewController has dealloc
``` 

The other:

```
2023-08-08 16:54:50.801195+0800 TradeBook[1017:285779] flutter: Entrypoint args-page: 1
2023-08-08 16:54:50.804437+0800 TradeBook[1017:285779] flutter: _PageState page: null, initialPage: 1, initialScrollOffset: 0.0
2023-08-08 16:54:50.860858+0800 TradeBook[1017:285779] flutter: PageView (get page) pixels: 0.0, minScrollExtent: 0.0, maxScrollExtent: 375.0
2023-08-08 16:54:50.860954+0800 TradeBook[1017:285779] flutter: PageView (getPageFromPixels) pixels: 0.0, _initialPageOffset: 0.0, actual: 0.0, round: 0.0
2023-08-08 16:54:50.860996+0800 TradeBook[1017:285779] flutter: _PageState page: 0.0, initialPage: 1, initialScrollOffset: 0.0
``` 

### Flutter Doctor output

```
youngfung@YoungdeMac-mini Flutter_Module$ flutter doctor -v
[✓] Flutter (Channel stable, 3.0.5, on macOS 13.4.1 22F82 darwin-arm, locale zh-Hans-CN)
    • Flutter version 3.0.5 at /Users/youngfung/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (1 year, 1 month ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/youngfung/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_371-b11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.81.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • iPhone (3) (mobile) • 59a58859a7c82be2c689140e86e7ab7dff2b085e • ios            • iOS 14.4.2 18D70
    • macOS (desktop)     • macos                                    • darwin-arm64   • macOS 13.4.1 22F82
      darwin-arm
    • Chrome (web)        • chrome                                   • web-javascript • Google Chrome 107.0.5304.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

**Comment by CliffVardant** [comment]
> Hi @CliffVardant. Thanks for filing this issue. Can't seem to reproduce this with the sample project I'm testing with, can you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code (could be a sample/simple github repo sample). Thank you!

Unfortunately, similar project configuration is not possible in demo, and in demo's  release mode, where the FlutterModule runs alone, everything works fine.
But in a real project, after navigating in and out of the Flutter page multiple times, the property pixels inside the PageView will be 0.

**Comment by dam-ease** [comment]
Hi @CliffVardant. Thanks for your response. For this issue to be workable we would need a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the issue. By real project, do you mean it doesn't reproduce with smaller samples without complex production codes?
Also, I see you are on an older version of flutter, can you upgrade to the latest flutter versions to confirm this issue persists, if possible, the latest `master` channel.

**Comment by CliffVardant** [comment]
> Hi @CliffVardant. Thanks for your response. For this issue to be workable we would need a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the issue. By real project, do you mean it doesn't reproduce with smaller samples without complex production codes? Also, I see you are on an older version of flutter, can you upgrade to the latest flutter versions to confirm this issue persists, if possible, the latest `master` channel.

I created a new project to reproduce the problem, but nothing gone wrong😥.  The problem only appears in the real project. Because of minimum iOS 10 support is required, so v3.0.5 is the maximum version I can choose.

**Comment by dam-ease** [comment]
Thanks for your response. We'd need to either be able to reproduce this issue on a simple minimal project on the latest versions of flutter for it to be workable. Please provide more information on this

**Comment by CliffVardant** [comment]
After I import "flutter_screenutil" , the problem seen solved.  It seems to be a problem with the engine and the timing of page initialization.
