### ISSUE TITLE
[SelectionArea] Selection sometimes picks up empty text

### ISSUE THREAD

**Issue by mrchenmo** [flutter/flutter#132188]
<details>
<summary>flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [版本 10.0.22000.2176], locale zh-CN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio 生成工具 2022 17.6.2)
[√] Android Studio (version 2020.3)
[√] Android Studio (version 2021.3)
[√] Connected device (4 available)
[!] Network resources
```
</details>

```
======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/selectable_region.dart': Failed assertion: line 624 pos 12: '_selectionDelegate.value.endSelectionPoint != null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      SelectableRegionState._handleSelectionEndHandleDragStart (package:flutter/src/widgets/selectable_region.dart:624:12)
#3      SelectionOverlay._handleEndHandleDragStart (package:flutter/src/widgets/text_selection.dart:1141:27)
#4      DragGestureRecognizer._checkStart.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:497:53)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275:24)
#6      DragGestureRecognizer._checkStart (package:flutter/src/gestures/monodrag.dart:497:7)
#7      DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:420:7)
#8      GestureArenaManager._resolveByDefault (package:flutter/src/gestures/arena.dart:268:25)
#9      GestureArenaManager._tryToResolveArena.<anonymous closure> (package:flutter/src/gestures/arena.dart:248:31)
(elided 4 frames from class _AssertionError and dart:async)
Handler: "onStart"
Recognizer: PanGestureRecognizer#2d4ef
  debugOwner: _SelectionHandleOverlayState#9619d(ticker inactive)
  start behavior: start
====================================================================================================
```

Long press the text on the mobile phone and the selection cursor will appear, and there will be no text selected, and the above error will appear.

https://github.com/flutter/flutter/assets/18020929/0e1bb673-e58f-4257-b03c-35b8c681c01f

**Comment by danagbemava-nc** [comment]
Hi @mrchenmo, a similar issue was reported in https://github.com/flutter/flutter/issues/126652. Can you check on the master channel to see if you still experience this issue? Although the issue mentions Chinese text, the fix didn't seem to do anything chinese specific. If you still face this issue on the master channel, kindly provide the version of the master channel that you tested on. 

Thank you

**Comment by mrchenmo** [comment]
> Hi @mrchenmo, a similar issue was reported in #126652. Can you check on the master channel to see if you still experience this issue? Although the issue mentions Chinese text, the fix didn't seem to do anything chinese specific. If you still face this issue on the master channel, kindly provide the version of the master channel that you tested on.
> 
> Thank you

Chinese is more prone to this problem, I will test in the master channel, whether this problem is fixed, this problem can still be reproduced in the stable channel 3.10.6

**Comment by danagbemava-nc** [comment]
Kindly update us with the result of what happens when you test on the master channel. 

Thank you

**Comment by mrchenmo** [comment]
<details>
<summary>flutter doctor</summary>
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 3.14.0-2.0.pre.20, on Microsoft Windows [版本 10.0.22000.2176], locale zh-CN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio 生成工具 2022 17.6.2)
[√] Android Studio (version 2020.3)
[√] Android Studio (version 2021.3)
[√] Connected device (4 available)
[!] Network resources
    X An HTTP error occurred while checking "https://github.com/": 信号灯超时时间已到


! Doctor found issues in 1 category.
</details>

**Comment by mrchenmo** [comment]
<details>
<summary>flutter doctor</summary>
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 3.14.0-2.0.pre.20, on Microsoft Windows [版本 10.0.22000.2176], locale zh-CN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio 生成工具 2022 17.6.2)
[√] Android Studio (version 2020.3)
[√] Android Studio (version 2021.3)
[√] Connected device (4 available)
[!] Network resources
    X An HTTP error occurred while checking "https://github.com/": 信号灯超时时间已到


! Doctor found issues in 1 category.
</details>

**Comment by mrchenmo** [comment]
<details>
<summary>flutter doctor</summary>
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 3.14.0-2.0.pre.20, on Microsoft Windows [版本 10.0.22000.2176], locale zh-CN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio 生成工具 2022 17.6.2)
[√] Android Studio (version 2020.3)
[√] Android Studio (version 2021.3)
[√] Connected device (4 available)
[!] Network resources
    X An HTTP error occurred while checking "https://github.com/": 信号灯超时时间已到


! Doctor found issues in 1 category.
</details>
there will still be problems

https://github.com/flutter/flutter/assets/18020929/603f9cc7-9b36-4ac2-bf18-4fe96f4c9b68

**Comment by danagbemava-nc** [comment]
Hi @mrchenmo, please share the repro sample you used in the recording above. 

Thank you

**Comment by mrchenmo** [comment]
`void main() {
  runApp(
    MaterialApp(
      title: 'Demo',
      home: TestPage(),
    ),
  );
}

class TestPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('RPCWidget'),
      ),
      body: Center(
        child: Column(
          children: [
            const SizedBox(height: 16.0),
            const Expanded(
              child: Column(
                children: [
                  Padding(
                    padding: EdgeInsets.only(left: 16.0, right: 16.0),
                    child: SelectionArea(
                      child: Text(
                          '银行是否不再需要一致性？如果你不在“同一页”上，该技术通过在不同的服务器之间传输事务上下文来工作。因此，一台服务器上的提交是一个多阶段过程，几乎可以保证所有服务器都成功或作为一个服务器回滚。这是相当惊人的，实际上效果相当好（显然有一些警告）。令人惊讶的是，这是通过方法调用实现的。你不需要做任何事，即使在完全不同的服务器上调用远程方法，它也能好好工作。'),
                    ),
                  ),
                  SizedBox(height: 16.0),
                ],
              ),
            ),
            Column(
              children: [
                GestureDetector(
                  onTap: () async {},
                  child: const Text('send tra', style: TextStyle(fontSize: 18.0)),
                ),
                const SizedBox(height: 16.0),
                GestureDetector(
                  onTap: () async {},
                  child: const Text('get balance', style: TextStyle(fontSize: 18.0)),
                )
              ],
            ),
            const SizedBox(height: 56.0),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () async {},
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}`

**Comment by danagbemava-nc** [comment]
Hi @mrchenmo, I can't seem to reproduce this on my android device. Please provide the full logs of `flutter run -v` that captures the error when you reproduce on the `master channel` so that we can take this forward. The output may be huge, so kindly put it into a .txt file and attach it here. 

Thank you

**Comment by mrchenmo** [comment]
<details>
<summary>flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 3.14.0-3.0.pre.3, on Microsoft Windows [版本 10.0.22000.2295], locale zh-CN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio 生成工具 2022 17.6.2)
[√] Android Studio (version 2020.3)
[√] Android Studio (version 2021.3)
[√] Connected device (4 available)
[√] Network resources

• No issues found!

```
</details>

[rpc_log.txt](https://github.com/flutter/flutter/files/12333302/rpc_log.txt)

**Comment by mrchenmo** [comment]
<details>
<summary>flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 3.14.0-3.0.pre.58, on Microsoft Windows [版本 10.0.22000.2295], locale zh-CN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio 生成工具 2022 17.6.2)
[√] Android Studio (version 2020.3)
[√] Android Studio (version 2021.3)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
```
</details>

[rpc_log.txt](https://github.com/flutter/flutter/files/12333555/rpc_log.txt)

long press at any position only selects the text once, and the rest are selected blank

**Comment by danagbemava-nc** [comment]
Hi @mrchenmo, I do not see the error in your logs, are you still getting the error?

**Comment by mrchenmo** [comment]
Yes, there is no error, but the text is not selected, and there is a high probability that the selection will be empty. does this need to be fixed? sir,the new beta version has fixed the error, but long press still selects empty.

**Comment by mrchenmo** [comment]
this is my mistake sir, I mainly want to feedback the phenomenon that long press will select empty

**Comment by danagbemava-nc** [comment]
Thanks for the clarification. However, I can't seem to reproduce this on my pixel 7 with the code sample in https://github.com/flutter/flutter/issues/132188#issuecomment-1674333178 on the latest master channel. Can you do an upgrade and check again? 

Also, is this only the MEIZU device?

**Comment by mrchenmo** [comment]
<details>
<summary>flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.0, on Microsoft Windows [版本 10.0.22000.2295], locale zh-CN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio 生成工具 2022 17.6.2)
[√] Android Studio (version 2020.3)
[√] Android Studio (version 2021.3)
[√] Connected device (4 available)
[!] Network resources             
    X An HTTP error occurred while checking "https://github.com/": 信号灯超时时间已到


! Doctor found issues in 1 category.

```
</details>

I tested Meizu and Huawei devices, and on the latest version 3.13.0, long press to select empty text still appears

**Comment by danagbemava-nc** [comment]
Thanks, @mrchenmo, one final ask, do you experience this issue on iOS as well or is it just android? Are any other platforms affected?

**Comment by mrchenmo** [comment]
I have only tested on Android devices, I am asking my colleagues to help me test on iOS

**Comment by danagbemava-nc** [comment]
Please share your colleague's findings when you get them, for now, I'll be labeling this so that it can be investigated. 

I could not reproduce this on my Pixel 7 but I think this may not be a platform or device-specific issue. It may require other steps to reproduce. The code sample can be found in https://github.com/flutter/flutter/issues/132188#issuecomment-1674333178

Labeling based on the report shared above. OP tested on master before the new stable was released, which likely means it has not been fixed in the latest stable/master release. Flutter doctor from op can be found in https://github.com/flutter/flutter/issues/132188#issuecomment-1672738803

**Comment by Renzo-Olivares** [comment]
cc @Renzo-Olivares from triage, will try to reproduce.

**Comment by mrchenmo** [comment]
The correct `LongPressStartDetails `is obtained in the `_handleTouchLongPressStart `method, and the globalPosition Offset contains the normal dx and dy. It seems that the selected text is not displayed correctly in the `_selectWordAt `method. I am not sure whether it is because the `handleSelectWord `method has not been processed correctly.

**Comment by Renzo-Olivares** [comment]
@mrchenmo are you running on the latest flutter master? I ask because this PR https://github.com/flutter/flutter/pull/132518 may have changed/fixed the behavior, it was merged last week. Can you try and see if this fixed the issue?

**Comment by mrchenmo** [comment]
I think https://github.com/flutter/flutter/issues/104603#issuecomment-1164421064
The description of this problem is very suitable for my current problem, I will test it in the main channel, thanks, sir

**Comment by mrchenmo** [comment]
sir, this bug has been fixed in the latest master channel, I will close this issue, thx sir
