### ISSUE TITLE
reimage mac-38

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#132158]
@kentnguyen99 the mac-38 machines seems to be in a bad state. Can you please completely wipe and re-setup the host.

**Comment by kentnguyen99** [comment]
Hi @yusuf-goog,  Machine mac-38 has been wiped out clean and re-installed OS.  The mac-38 is back online and ready for service.

**Comment by kentnguyen99** [comment]
Re-imaging mac-38 has been completed. Machine mac-38 is back online and running.
