### ISSUE TITLE
Widget change it's color when snap is builded in linux app

### ISSUE THREAD

**Issue by PrashantSaxena07** [flutter/flutter#132118]
![image](https://github.com/flutter/flutter/assets/55252616/fb8acabf-2520-4e04-aef7-4af185de2758)

`  Widget createDateInput(String hintText, TextEditingController controller) {
    return Container(
        height: 35,
        width: MediaQuery.of(context).size.width/4.75,
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(12.0),
        ),
        child: TextFormField(
            style: TextStyle(fontSize: 12),

            controller: controller,
            cursorHeight: 17,
            cursorColor: ColorsFile.primaryColor2.withOpacity(0.6),
            decoration: InputDecoration(
                focusedBorder: UnderlineInputBorder(
                  // borderRadius: BorderRadius.circular(0),
                  borderSide: BorderSide(
                      color: ColorsFile.primaryColor2.withOpacity(0.6),
                      width: PixelService.instance.getPixelSize(2)),
                ),
                contentPadding: EdgeInsets.fromLTRB(
                    PixelService.instance.getPixelSize(12),
                    PixelService.instance.getPixelSize(0),
                    PixelService.instance.getPixelSize(20),
                    PixelService.instance.getPixelSize(15)),
                border: const UnderlineInputBorder(
                    borderSide: BorderSide(
                      color: ColorsFile.primaryColor2,
                    )),
                labelText: hintText,

                labelStyle: new TextStyle(
                    color: ColorsFile.textcolor.withOpacity(0.7), fontWeight: FontWeight.w400, fontSize: 13),
              suffixIcon: IconButton(
                splashRadius: 1,
                    icon: const Icon(Icons.calendar_month_outlined, size: 13,),
                    onPressed: () {
                      if (controller == startDateController) {
                        _selectDateStart(context, startDateController);
                      } else if (controller == endDateController) {
                        _selectDateStart(context, endDateController);
                      }
                    }))));
  }
`
as you can see in left image its from running code... it's in correct format but after building its snap file it changes it's widget's properties mainly color and pading.

> flutter doctor -v
`[✓] Flutter (Channel stable, 3.10.6, on Ubuntu 23.04 6.2.0-26-generic, locale en_US.UTF-8)
    • Flutter version 3.10.6 on channel stable at /home/prashant-saxena/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (4 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /home/prashant-saxena/Android/Sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2022.3)
    • Android Studio at /opt/android-studio-2022.3.1/android-studio
    • Flutter plugin version 75.1.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.68.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 23.04 6.2.0-26-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 115.0.5790.110

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
`

**Comment by dam-ease** [comment]
Hi @PrashantSaxena07  
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly.
More specifically, please provide the information indicated below:

- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of flutter doctor -v
- Reproduction steps

Once you update the issue with more information, please write in the comments for further discussion. Thanks!
