### ISSUE TITLE
ERR_CONTENT_LENGTH_MISMATCH

### ISSUE THREAD

**Issue by tauqeerkhattak** [flutter/flutter#132114]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a new Flutter project.
2. Run the command `flutter build web`
3. Serve the app on localhost using `python -m http.server 8080` or deploy on any server.
4. Open the deployed app on Android Emulator Chrome browser or iPhone Safari Browser.

### Expected results

The App opens normally on Android Emulator chrome browser or iPhone Safari browser.

### Actual results

This error is thrown in web console when viewed through chrome DevTools.

http://10.0.2.2:8080/flutter.js net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)

### Code sample

Public Repo: https://github.com/tauqeerkhattak/flutter_test.git

### Logs

<details><summary>Logs</summary>

```console
10.0.2.2/:40     GET http://10.0.2.2:8080/flutter.js net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)
(index):46 Uncaught ReferenceError: _flutter is not defined
    at (index):46:7
(anonymous) @ (index):46
load (async)
(anonymous) @ (index):44

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.22000.2245], locale en-US)
    • Flutter version 3.10.5 on channel stable at D:\flutters\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (8 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\rk\AppData\Local\Android\Sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32328.378
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.81.0)
    • VS Code at C:\Users\rk\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.50.0

[√] Connected device (4 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.2245]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 115.0.5790.171
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 115.0.1901.188

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by opxdelwin** [comment]
The `_flutter is not defined` error usually happens due to hosting issues, still you can try these out.

- delete your `pubspec.lock` file
- `flutter clean`
- `flutter pub cache repair`
- `flutter pub upgrade`

To build for deployment, use `flutter build web` and you can find the files at `build/web`
Try deploying contents of `build/web` folder manually if you can, else ill suggest to use `Firebase Hosting` to test out if it works.

**Comment by tauqeerkhattak** [comment]
Okay, let me try the steps you've mentioned.

Thanks for replying!

**Comment by tauqeerkhattak** [comment]
@opxdelwin I've tried all the steps mentioned, the app runs on Desktop browsers, but it only shows blank screen on Safari browsers on iPhone.

**Comment by opxdelwin** [comment]
What URL did you use on search field for emulated devices

**Comment by tauqeerkhattak** [comment]
Localhost for Android emulator is I think http://10.0.2.2:8000/

**Comment by opxdelwin** [comment]
Can reproduce, no solutions so far

**Comment by huycozy** [comment]
@tauqeerkhattak Is `10.0.2.2` your host machine local IP? I still can host the built web normally and open it on Android/iOS browser. You should try open the web in host machine firstly to make sure it works.

**Comment by opxdelwin** [comment]
So you cannot use firebase hosted website on your ios (do mention emulator or real)?

**Comment by tauqeerkhattak** [comment]
I tried on localhost (10.0.2.2:8000) as well as Firebase hosting. Both shows the same error on iOS Safari Browser! Note that the issue does not occur now on Android Emulator.

**Comment by huycozy** [comment]
@tauqeerkhattak I think the problem is using that IP address since it's an alias to your host loopback interface. You can try using real IP of your machine in local network instead (192.168.x.x for eg).

>I tried on localhost (10.0.2.2:8000) as well as Firebase hosting

Can you share the deployed site here?

**Comment by tauqeerkhattak** [comment]
@huycozy It is resolved now, it was due to not correctly deployed to Firebase Hosting, thank you for your time!
