### ISSUE TITLE
add a --start-paused option to `flutter start`

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#1321]
`flutter start` should support a `--start-paused` option. This would pass through to the VM's `--pause_isolates_on_start` option and would be used to have isolates start in a paused state to allow a debugger to connect before they run.

**Comment by sethladd** [comment]
I think we're going to get this very soon, yes?

**Comment by devoncarew** [comment]
It's in the CLI tool, and being passed into both the android and ios clients. John is working on a change so that the embedder respects the flag.

**Comment by yjbanov** [comment]
+1. Flutter driver needs this too.

**Comment by devoncarew** [comment]
This is working and verified w/ `flutter start` and android. There's a more specific bug for issues on the ios simulator. Closing this out -
