### ISSUE TITLE
ConstrainedBox with multi-line text always grows to max width

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#13211]
If you embed Text inside a `ConstrainedBox` and the text is longer than the max constrained width then the `ConstrainedBox` will always grow to be the maximum width. What _probably_ should happen is that the `ConstrainedBox` should only grow to match the maximum extent of the contents instead.

See below:
![capture](https://user-images.githubusercontent.com/37941/33281809-58ec5228-d35b-11e7-8d26-b01c8d5ce306.PNG)

**Comment by Hixie** [comment]
It's the Text that's expanding. It tries to lay out the first line, grows as much as it can to accomodate the line, then when it runs out of room, wraps. But at that point it's already reached the maximum width.

We could provide a feature that lets it then shrink to the longest line, I suppose.

**Comment by lukef** [comment]
I would think that what I was describing is the "default" behaviour as it is `maxWidth` and not simply `width`. I suspect most people's expectation is that the box only grows to fit the contents. I definitely understand why it is happening, but it seems broken.

**Comment by lukef** [comment]
Also, if you have any suggestions as to how to do it with a custom widget i'd appreciate it seeing as it is flagged "future".

**Comment by Hixie** [comment]
As a workaround you could put a hardcoded newline in the string, or implement the wrapping and background manually using a CustomPainter and TextPainters. I agree it's not ideal though.

**Comment by sroddy** [comment]
Related https://github.com/flutter/flutter/issues/15300

**Comment by Agraphie** [comment]
Are there any news on this? This seems rather important, i.e. when someone wants to build a chat. Or overlay a label on a picture or video.

**Comment by GaryQian** [comment]
https://github.com/flutter/flutter/issues/25287 proposes new line wrapping options that would resolve this if implemented.

**Comment by markusaksli-nc** [comment]
Reproducible on the latest master `1.22.0-10.0.pre.450`.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.22.0-10.0.pre.450, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.22.0-10.0.pre.450 at C:\Development\flutter_master
    • Framework revision 9d41ddcbac (73 minutes ago), 2020-10-01 08:01:58 +0200
    • Engine revision 612acf349e
    • Dart version 2.11.0 (build 2.11.0-180.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (6 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.508]
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 85.0.4183.121
    • Edge (web)                  • edge               • web-javascript • Microsoft Edge 85.0.564.51

• No issues found!
```
</details>
<details>
 <summary>Minimal reproducible code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  var text = '';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Sample',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Sample'),
        ),
        body: Center(
          child: Container(
            color: Colors.grey,
            child: ConstrainedBox(
              constraints: BoxConstraints(maxWidth: 250),
              child: Text(
                text,
                style: TextStyle(fontSize: 40),
              ),
            ),
          ),
        ),
        bottomNavigationBar: Container(
          color: Colors.red,
          height: 40,
          child: Card(
            child: TextField(
              onChanged: (newText) => setState(() => text = newText),
            ),
          ),
        ),
      ),
    );
  }
}
```
</details>

**Comment by theSharpestTool** [comment]
I've faced with this issue too, the solution that works for me is to set `textWidthBasis: TextWidthBasis.longestLine` in `Text`

**Comment by FaFre** [comment]
The solution of @theSharpestTool also solved my problem

**Comment by lukas-pierce** [comment]
> I've faced with this issue too, the solution that works for me is to set `textWidthBasis: TextWidthBasis.longestLine` in `Text`

Thanks a lot
