### ISSUE TITLE
[webview_flutter] Unable to focus on text input in webview 

### ISSUE THREAD

**Issue by fondoger** [flutter/flutter#132143]
### Is there an existing issue for this?

- [X] I have searched the [existing package issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Apackage)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### What package does this bug report belong to?

webview_flutter

### What target platforms are you seeing this bug on?

Android

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
No provided. Please see the screenshot.
```

</details>

### Steps to reproduce

Steps to reproduce issue:
* Upgrade `webview_flutter_android` to **3.9.2**

**Important**: I can only reproduce the issue on Android device in Release mode. I tested debug mode, the issue does not show. I think the showing of keyboard somehow caused the flutter app to re-render the webview.

Steps I used to fix the bug: 
* Downgrade `webview_flutter_android` to **3.8.2**

I believe the bug was introduced two weeks ago in this PR: https://github.com/flutter/packages/pull/4533
<img width="797" alt="image" src="https://github.com/flutter/flutter/assets/22270677/1ee465c4-c71b-4856-affa-b0f137b0ea86">

Please revert that PR until some one come up with a better solution.

### Expected results

**Expected Behavior**: When I tap to focus on a `<input>` element in webview, the soft keyboard shows and I can type normally.

https://github.com/flutter/flutter/assets/22270677/4efac599-71fd-4cbb-98b3-76d5a9c7c6d0

### Actual results

**Wrong behavior**: When I tap to focus on a `<input>` element in webview, the page flashes with white screen, and automatically loose focus. The soft keyboard cannot open and I cannot type.

https://github.com/flutter/flutter/assets/22270677/3e151fdc-0e89-4215-a992-35a7792ddc51

### Code sample

<details><summary>Code sample</summary>

```dart
No provided. Please see the videos I uploaded.
```

</details>

### Screenshots or Videos

<details>
<summary>Screenshots / Video demonstration</summary>

**Expected Behavior**: When I tap to focus on a `<input>` element in webview, the soft keyboard shows and I can type normally.

https://github.com/flutter/flutter/assets/22270677/4efac599-71fd-4cbb-98b3-76d5a9c7c6d0

**Wrong behavior**: When I tap to focus on a `<input>` element in webview, the page flashes with white screen, and automatically loose focus. The soft keyboard cannot open and I cannot type.

https://github.com/flutter/flutter/assets/22270677/45441ca2-958b-49a2-bb32-ffa7bcc4c47e

</details>

### Logs

<details><summary>Logs</summary>

```console
No related logs.
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F770820d darwin-x64, locale en-CN)
    • Flutter version 3.10.6 on channel stable at /Users/fondoger/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (4 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/fondoger/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.80.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)            
    • V2055A (mobile) • 192.168.0.100:42651 • android-arm64  • Android 12 (API 31)
    • macOS (desktop) • macos               • darwin-x64     • macOS 13.4.1 22F770820d darwin-x64
    • Chrome (web)    • chrome              • web-javascript • Google Chrome 115.0.5790.170

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @fondoger 
I tried the plugin example and ran in release mode but was able to input and type in properly and it also showed up the keyboard properly as below:

<img width="222" alt="Screenshot 2023-08-09 at 1 27 04 PM" src="https://github.com/flutter/flutter/assets/67046386/91c970c7-f575-4eb0-8c71-7738b313de59">

I used latest plugin versions.  If above doesn't represent your case, can you provide us a minimal code sample so that we can make the issue actionable ?

**Comment by JDongKhan** [comment]
Help, the same issue was found in version  ```webview_flutter: ^4.2.2```

**Comment by JDongKhan** [comment]
```webview_flutter_android: 3.8.2``` is work for me.

It seems to have occurred during the first installation.

**Comment by JDongKhan** [comment]
1、install and open
https://github.com/flutter/flutter/assets/4929805/6e7a4749-a44d-4795-8edf-87cd3670ef67

2、kill app and then open app
https://github.com/flutter/flutter/assets/4929805/51988a7c-fe98-445e-b6c2-267ea8808980

**Comment by darshankawar** [comment]
I tried by using `<input type="text">` in plugin example, ran in release mode in which the keyboard opened properly:

<img width="274" alt="Screenshot 2023-08-09 at 6 14 39 PM" src="https://github.com/flutter/flutter/assets/67046386/b4a62603-da07-4462-b7e1-a87a6c35bfc0">
