### ISSUE TITLE
error on accept the license 

### ISSUE THREAD

**Issue by hostworldly** [flutter/flutter#132142]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

flutter doctor --android-licenses

### Actual results

C:\Users\noori>flutter doctor --android-licenses
Error: LinkageError occurred while loading main class com.android.sdklib.tool.sdkmanager.SdkManagerCli
        java.lang.UnsupportedClassVersionError: com/android/sdklib/tool/sdkmanager/SdkManagerCli has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
Android sdkmanager tool was found, but failed to run
(C:\Users\noori\AppData\Local\Android\Sdk\cmdline-tools\latest\bin\sdkmanager.bat): "exited code 1".
Try re-installing or updating your Android SDK,
visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by hostworldly** [comment]
i'm using java 11 version and android SDK is also latest version

**Comment by ilovelinux** [comment]
It looks like you have a different Java Runtime version than the one SdkManager has been built against. Did you try re-installing or updating your Android SDK?

**Comment by hostworldly** [comment]
you're right thank you for help me Java Runtime version it is too old 

it is resolved now
