### ISSUE TITLE
Expose low-level back navigation event broadcast, maybe via `SystemNavigator`

### ISSUE THREAD

**Issue by gintominto5329** [flutter/flutter#132221]
hello,

I want to create a custom, `Navigator`(and `NavigatorState`) equivalent, in-dependent of the former.

---

Equivalents which are already mimicked, using my custom stack data-struct; supporting pages, bottom sheets, alerts, bottom toasts:
- `push`
- `push_replace`

Not completed, yet:
- `pop`
- `pop_until`

---

We know, that Android, and Iphones support the following options for back navigation (pop):
```
           Android   Iphone
Top bar       Y        Y
Gesture       Y        Y
Button        Y        -

```

Among these, tab-bar is in-app, so I can directly listen to its press, but:

### How to listen for back gesture (swipe from screen's left/right edge), and back button press actions.

Also, are these sensed directly by flutter, or the OS sends some event to the framework?

---

I checked out [`Future<bool> WidgetsBindingObserver.didPopRoute`](https://master-api.flutter.dev/flutter/widgets/WidgetsBindingObserver/didPopRoute.html): "Called when the system tells the app to pop the current route. For example, on Android, this is called when the user presses the back button."

### Proposal

Expose a low-level function like `static Stream<BackNavigationEvent> system_back_navigation_events_broadcast()` via `SystemNavigator`.

If this is not possible, then how does `Navigator` class gets to know, when the user press the system back button on android, and swipe from right edge, on Ios.

thanks

**Comment by darshankawar** [comment]
@gintominto5329 
Can you take a look at [this](https://github.com/flutter/flutter/issues/11490) issue and check if it resembles your case or not ?

**Comment by gintominto5329** [comment]
Sorry, I do not think that, that issue resembles my case, 
  except a single, un-replied comment, which clearly states my issue:

> Developers sometimes need to handle the system back themselves

> For example, when catching the system back gesture in order to show a confirmation dialog before going back. In that case, the developer has to know where the route is in the stack and then use either `Navigator.maybePop` or `SystemNavigator.pop`.

_Originally posted by @justinmc in https://github.com/flutter/flutter/issues/11490#issuecomment-1629389053_

**Comment by goderbauer** [comment]
> I checked out [Future<bool> WidgetsBindingObserver.didPopRoute](https://master-api.flutter.dev/flutter/widgets/WidgetsBindingObserver/didPopRoute.html): "Called when the system tells the app to pop the current route. For example, on Android, this is called when the user presses the back button."

This is the way to do it. Did you run into any problems with this?

**Comment by gintominto5329** [comment]
hi,

To use [`Future<bool> WidgetsBindingObserver.didPopRoute`](https://master-api.flutter.dev/flutter/widgets/WidgetsBindingObserver/didPopRoute.html), the widget's class need to extend `WidgetsBindingObserver`, which i cannot do

I needed an `add_listener`(or `listen`) type interface.

I found `SystemChannels.navigation.setMethodCallHandler(Future Function(MethodCall) call)`, does this disturb anything(other than `Navigator`), because I do not use flutter's navigator, or any of the navigation packages on pub_dev.

thanks

**Comment by goderbauer** [comment]
> To use [Future<bool> WidgetsBindingObserver.didPopRoute](https://master-api.flutter.dev/flutter/widgets/WidgetsBindingObserver/didPopRoute.html), the widget's class need to extend WidgetsBindingObserver, which i cannot do

You can also implement it or mix it in. That works for any class really, it doesn't have to be a widget. Why can you not do that?

**Comment by gintominto5329** [comment]
hi,

the `Navigator`-equivalent is quite-ready, but facing a problem.
I cannot ask stack-overflow, because SO's flutter community, do not have much knowledge of flutter-**engine**, just layouts, etc.

Could you help me?

The `Navigator`-equivalent's rough design is
```dart
/// Note: pseudo-code

Stack_data_struct<Widget> navigation_history; // `NavigatorEquivalent` listens for changes and re-builds on push/pop

WidgetsApp(
  initial_page: NavigatorEquivalent( // state-ful
    initState: () => navigation_history.add_listener(re_build /*setState*/);
    build: (context) => navigation_history.top/* top of stack, hence the latest page */;
  ),
);

void navigate__push(Widget page) => navigation_history.push(page);
```

The problem is, that the `Widget page`, which gets passed to `navigate__push`, gets un-mounted from the tree, hence the `page`'s `initState` gets called again, when `navigate__pop` is called; something like `KeepAlive` is needed.

I tried using the `Stack` widget with `Offstage`, but no progress.

May I ask, how can MaterialPageRoute`'s `maintainState` be applicable here?

thanks
