### ISSUE TITLE
storage.flutter-io.cn%0D is not a valid link-local address but contains %. Scope id should be used as part of link-local address. (at character 22)

### ISSUE THREAD

**Issue by guojunlong** [flutter/flutter#132200]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

My computer is Apple M2(Ventura 13.3 (22E252))

Create a flutter project and run it with an error

### Actual results

The program crashed

### Logs

<details>
<summary>Logs</summary>

```console


. Make sure you trust this source!
Downloading an artifact that may not be reachable in some environments (e.g. firewalled environments): https://storage.flutter-io.cn%0D/flutter_infra_release/flutter/cdbeda788a293fa29665dc3fa3d6e63bd221cb0d/ios/artifacts.zip
This should not have happened. This is likely a Flutter SDK bug. Please file an issue at https://github.com/flutter/flutter/issues/new?template=1_activation.yml
Downloading an artifact that may not be reachable in some environments (e.g. firewalled environments): https://storage.flutter-io.cn%0D/flutter_infra_release/flutter/cdbeda788a293fa29665dc3fa3d6e63bd221cb0d/ios/artifacts.zip
This should not have happened. This is likely a Flutter SDK bug. Please file an issue at https://github.com/flutter/flutter/issues/new?template=1_activation.yml
Downloading ios tools...
Downloading ios tools...
Failed to download https://storage.flutter-io.cn%0D/flutter_infra_release/flutter/cdbeda788a293fa29665dc3fa3d6e63bd221cb0d/ios/artifacts.zip. Ensure you have network connectivity and then try again.
FormatException: storage.flutter-io.cn%0D is not a valid link-local address but contains %. Scope id should be used as part of link-local address. (at character 22)
storage.flutter-io.cn%0D
                     ^



```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

s-MacBook-Pro ~ %  flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.3 22E252 darwin-arm64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by huycozy** [comment]
Please follow [Configuring Flutter to use a mirror site](https://docs.flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site) and retry. Make sure there is no redundant space in the values.

**Comment by guojunlong** [comment]
I searched for the file 'storage. flutter-io.cn' on my computer and found one in the  flutter/bin/cache/downloads  path" storage.flutter-io.cn@per@0D" file, I'm not sure if it's an error, so I deleted the  flutter  file and followed the instructions to perform the operation:

`export PUB_HOSTED_URL=https://pub.flutter-io.cn
export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
git clone -b dev https://github.com/flutter/flutter.git
export PATH="$PWD/flutter/bin:$PATH"
cd ./flutter
flutter doctor
`
I'm sure there's no redundant space this time;

But when I ran the project again, Android Studio reported the same error



"
. Make sure you trust this source!
Downloading an artifact that may not be reachable in some environments (e.g. firewalled environments): https://storage.flutter-io.cn%0D/flutter_infra_release/flutter/3950c6140a3f1cb295364b0446627bd3a1736915/ios/artifacts.zip
This should not have happened. This is likely a Flutter SDK bug. Please file an issue at https://github.com/flutter/flutter/issues/new?template=1_activation.md
Downloading an artifact that may not be reachable in some environments (e.g. firewalled environments): https://storage.flutter-io.cn%0D/flutter_infra_release/flutter/3950c6140a3f1cb295364b0446627bd3a1736915/ios/artifacts.zip
This should not have happened. This is likely a Flutter SDK bug. Please file an issue at https://github.com/flutter/flutter/issues/new?template=1_activation.md
Downloading ios tools...
Downloading ios tools...
Failed to download https://storage.flutter-io.cn%0D/flutter_infra_release/flutter/3950c6140a3f1cb295364b0446627bd3a1736915/ios/artifacts.zip. Ensure you have network connectivity and then try again.
FormatException: storage.flutter-io.cn%0D is not a valid link-local address but contains %. Scope id should be used as part of link-local address. (at character 22)
storage.flutter-io.cn%0D
"

**Comment by huycozy** [comment]
Please share the output of `flutter doctor -v` (with verbose).

Also, can you try putting all `export` commands to `.zshrc` file (I see you are using macOS) in home directory and then retry running? (please remember to execute `source .zshrc` to make sure new aliases are loaded)

**Comment by guojunlong** [comment]
1. This is the whole process of my operation:

Last login: Thu Aug 10 11:55:09 on ttys002
s-MacBook-Pro ~ % source .zshrc
s-MacBook-Pro ~ % git clone -b dev https://github.com/flutter/flutter.git
Cloning into 'flutter'...
remote: Enumerating objects: 462259, done.
remote: Counting objects: 100% (1186/1186), done.
remote: Compressing objects: 100% (661/661), done.
remote: Total 462259 (delta 721), reused 813 (delta 497), pack-reused 461073
Receiving objects: 100% (462259/462259), 262.42 MiB | 1.99 MiB/s, done.
Resolving deltas: 100% (354352/354352), done.
s-MacBook-Pro ~ % flutter doctor
Downloading Darwin arm64 Dart SDK from Flutter engine 3950c6140a3f1cb295364b0446627bd3a1736915...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  187M  100  187M    0     0  1477k      0  0:02:09  0:02:09 --:--:--  907k
Building flutter tool...
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure
you trust this source!
Downloading Material fonts...                                      825ms
Downloading Gradle Wrapper...                                       23ms
Downloading package sky_engine...                                  405ms
Downloading flutter_patched_sdk tools...                         1,176ms
Downloading flutter_patched_sdk_product tools...                 1,127ms
Downloading darwin-x64 tools...                                    29.5s
Downloading libimobiledevice...                                    156ms
Downloading usbmuxd...                                              65ms
Downloading libplist...                                             52ms
Downloading openssl...                                           1,144ms
Downloading ios-deploy...                                           71ms
Downloading darwin-x64/font-subset tools...                      1,130ms
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 3.4.0-17.2.pre, on macOS 13.3 22E252 darwin-arm,
    locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
s-MacBook-Pro ~ % 



2. flutter doctor -v

Last login: Thu Aug 10 12:09:54 on ttys000
s-MacBook-Pro ~ % flutter doctor -v
[✓] Flutter (Channel dev, 3.4.0-17.2.pre, on macOS 13.3 22E252 darwin-arm,
    locale zh-Hans-CN)
    • Flutter version 3.4.0-17.2.pre on channel dev at /Users/baipeng/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d6260f127f (11 months ago), 2022-09-21 13:33:49 -0500
    • Engine revision 3950c6140a
    • Dart version 2.19.0 (build 2.19.0-146.2.beta)
    • DevTools version 2.16.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/baipeng/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • B1F3FB87-4416-41BC-ADCF-86DE37BE84A5 • iOS
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)        • macOS                                •
      darwin-arm64   • macOS 13.3 22E252 darwin-arm
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 115.0.5790.170

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!




3. This is all the information in my ".zshrc" file

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
export PATH="/opt/homebrew/opt/ruby@3.0/bin:$PATH"
export PATH="$PATH:/Users/baipeng/flutter/bin"
source /opt/homebrew/opt/chruby/share/chruby/chruby.sh
source /opt/homebrew/opt/chruby/share/chruby/auto.sh
chruby ruby-3.2.2
___MY_VMOPTIONS_SHELL_FILE="${HOME}/.jetbrains.vmoptions.sh"; if [ -f "${___MY_VMOPTIONS_SHELL_FILE}" ]; then . "${___MY_VMOPTIONS_SHELL_FILE}"; fi


export PUB_HOSTED_URL=https://pub.flutter-io.cn
export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
export PATH="$PWD/flutter/bin:$PATH"


4. Then I created a new flutter project in Android Studio and ran it directly, and the result was still this error.

. Make sure you trust this source!
Downloading an artifact that may not be reachable in some environments (e.g. firewalled environments): https://storage.flutter-io.cn%0D/flutter_infra_release/flutter/3950c6140a3f1cb295364b0446627bd3a1736915/flutter-web-sdk-darwin-x64.zip
This should not have happened. This is likely a Flutter SDK bug. Please file an issue at https://github.com/flutter/flutter/issues/new?template=1_activation.md
Downloading an artifact that may not be reachable in some environments (e.g. firewalled environments): https://storage.flutter-io.cn%0D/flutter_infra_release/flutter/3950c6140a3f1cb295364b0446627bd3a1736915/flutter-web-sdk-darwin-x64.zip
This should not have happened. This is likely a Flutter SDK bug. Please file an issue at https://github.com/flutter/flutter/issues/new?template=1_activation.md
Downloading Web SDK...
Downloading Web SDK...
Failed to download https://storage.flutter-io.cn%0D/flutter_infra_release/flutter/3950c6140a3f1cb295364b0446627bd3a1736915/flutter-web-sdk-darwin-x64.zip. Ensure you have network connectivity and then try again.
FormatException: storage.flutter-io.cn%0D is not a valid link-local address but contains %. Scope id should be used as part of link-local address. (at character 22)
storage.flutter-io.cn%0D
                     ^

**Comment by huycozy** [comment]
Thanks for the detailed info. I forgot to mention that `dev` channel is obsoleted. Currently, there are 3 channels: stable, beta, and master. See [Switching Flutter channels](https://docs.flutter.dev/release/upgrade#switching-flutter-channels).


Can you please try using another network if any? Also, does the issue persist if running from Terminal instead of Android Studio IDE? Providing the entire output of `flutter run -v` could be also helpful. Thanks!

**Comment by guojunlong** [comment]
Thanks for your help. I switched to the stable channel and now I can run the project normally on Android studio.
