### ISSUE TITLE
Label not vertical aligned in TextFormField

### ISSUE THREAD

**Issue by anas-iqbal** [flutter/flutter#132208]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Just use a TextFormField and apply an outline border in the decoration. You will start noticing that the placeholder isn't vertically aligned in the center, and there is a bit more space below the hint text.

### Expected results

I have't use any paddings or anything so it should be aligned center vertically, even I tried using multiple props to center align e.g textbaseline and center align but didn't work.

### Actual results

The placeholder is not vertically centered.

### Code sample

<details><summary>This is just simple code I am using to render textformfield</summary>

```dart
         TextFormField(
            style: const TextStyle(color: PaletteColor.raisingBlack),
            decoration: InputDecoration(
                labelText: widget.placeholder,
                labelStyle: const TextStyle(color: PaletteColor.darkGray, fontWeight: FontWeight.w400, fontSize: 16),
                focusedBorder: OutlineInputBorder(
                  borderSide: const BorderSide(color: Colors.black, width: 2),
                  borderRadius: BorderRadius.circular(8.0),
                ),
                enabledBorder: OutlineInputBorder(
                  borderSide: const BorderSide(color: Colors.black, width: 2),
                  borderRadius: BorderRadius.circular(8.0),
                ),
                errorBorder: OutlineInputBorder(
                  borderSide: const BorderSide(color: Colors.black, width: 2),
                  borderRadius: BorderRadius.circular(8.0),
                ),
                disabledBorder: OutlineInputBorder(
                  borderSide: const BorderSide(color: PaletteColor.lightGray, width: 2),
                  borderRadius: BorderRadius.circular(8.0),
                ),
                focusedErrorBorder: OutlineInputBorder(
                  borderSide: const BorderSide(color: Colors.black, width: 2),
                  borderRadius: BorderRadius.circular(8.0),
                ),
                errorStyle: const TextStyle(color: PaletteColor.spanishGray)),
          ),
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>
<img width="328" alt="Screenshot 2023-08-09 at 2 29 09 PM" src="https://github.com/flutter/flutter/assets/19326974/71e115da-f2ad-4dbc-abdb-dd0d2eb2c5cd">

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.0.1 22A400 darwin-arm64, locale en-AE)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.76.0)```

</details>

**Comment by dam-ease** [comment]
Hi @anas-iqbal. Thanks for filing this issue. I can see little spacing below the label text which seems to almost not be noticeable so this might be expected. You might want to control this using `contentPadding` to get it well aligned to suit your case. Kindly let me know if this suits your use case
