### ISSUE TITLE
Upgrade Phase 1 for iOS 17 (~25%)

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#132252]
Blocked by: 
- [x] https://github.com/flutter/flutter/issues/141383 - workaround added

Try pool:

x86 - Upgrade 1 device (1 / 3)
- [x] Upgrade device on https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-1

arm64 - Upgrade 1 device (1 / 3)
- [x] Upgrade device on https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-38

Prod pool:

x86 - Upgrade 1 device (3 / 12) - only do one per day (so spread over 3 days time)
- [x] Upgrade device on https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-2
- [x] Upgrade device on https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-3
- [x] Upgrade device on https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-6

arm64  - Move 1 device (1 / 5)
- [x] Move bot https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-40 from staging pool to prod pool

----

Steps after upgraded to iOS 17 on iPhone devices.

* Open Xcode 15 from /opt/flutter/xcode/15a240d/XCode.app
* In the top bar, open Window > Device and Simulators
* The window that opens should show the connected device
* Accept the Trust dialog on the iPhone device
  * If you get the dialog on the device twice, you may need to accept it once, disconnect, reconnect, and accept again.
* Wait for the yellow bar at the top of the Device and Simulators window to go away - It should take a minute or so to Copy cache symbols

**Comment by keyonghan** [comment]
This is not a ticket queue bug. Routing to devicelab.

**Comment by ricardoamador** [comment]
@yusuf-goog @kentnguyen99 feel free to reprioritize this.

**Comment by yusuf-goog** [comment]
CL to move mac-40 from `staging` to `prod`: https://chrome-internal-review.googlesource.com/c/infradata/config/+/6934900

**Comment by yusuf-goog** [comment]
all listed devices have been upgraded.

**Comment by vashworth** [comment]
Everything is looking good. Closing.
