### ISSUE TITLE
Flutter tool should require "--local-engine-host" when "--local-engine" is set

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#132245]
**Status**: WIP. There are enough PRs out right now where I'm focusing on getting them landed/sticking before moving forward.

---

This is a follow-up to https://github.com/flutter/flutter/pull/132180#discussion_r1289011670.

As of https://github.com/flutter/flutter/pull/132180, `--local-engine-host` is _optional_, and if omitted, [falls back to trying to derive the host](https://github.com/flutter/flutter/blob/88ed9bd9d2017be2f1a42711382d8ba974989eb6/packages/flutter_tools/lib/src/runner/local_engine.dart#L161).

We'd like to make this explicit instead, so:

- [x] Announce the changes to the flutter tool to appropriate channels and wait a reasonable duration for feedback
- [x] Update the [`devicelab`](https://github.com/flutter/flutter/tree/1e35d3a6b702b9c804edc01fc4992567f7847f73/dev/devicelab).
    - PR: https://github.com/flutter/flutter/pull/132342
- [x] Update the [`glfw` examples](https://github.com/flutter/engine/blob/0795adf91db57fba52102b33b06f8de17479bc14/examples/glfw/run.sh#L31) and related examples in `examples/*gl*/**`.
    - PR: https://github.com/flutter/engine/pull/44610
- [x] Update the [`tool_backend.dart`](https://github.com/flutter/flutter/blob/1e35d3a6b702b9c804edc01fc4992567f7847f73/packages/flutter_tools/bin/tool_backend.dart#L49) and related scripts in `flutter_tools/bin/*`.
    - PR: https://github.com/flutter/flutter/pull/132336
- [x] Update [`flutter.groovy`](https://github.com/flutter/flutter/blob/1e35d3a6b702b9c804edc01fc4992567f7847f73/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy#L1314) and related.
    - PR: https://github.com/flutter/flutter/pull/132346
- [x] Update the [`dart_roll_helper.py`](https://github.com/flutter/buildroot/blob/a067408d923ccf80742571bb7a71705499f5779e/tools/dart/dart_roll_helper.py#L164).
    - PR: https://github.com/flutter/buildroot/pull/751
- [x] Update the web engine [`web_ui/dev/build.dart`](https://github.com/flutter/engine/blob/0795adf91db57fba52102b33b06f8de17479bc14/lib/web_ui/dev/build.dart#L36) and related files in `web_ui/dev/*`.
    - PR: https://github.com/flutter/engine/pull/44613
- ~Update [`flutter_gbd`](https://github.com/flutter/engine/blob/0795adf91db57fba52102b33b06f8de17479bc14/sky/tools/flutter_gdb#L99).~
    - Doesn't appear to need any changes, uses the device engine only.
- [x] Update [`dev/bots/test.dart`](https://github.com/flutter/flutter/blob/1e35d3a6b702b9c804edc01fc4992567f7847f73/dev/bots/test.dart#L209).
    - PR: https://github.com/flutter/flutter/pull/132354
- [x] Update [`build_linux.dart`](https://github.com/flutter/flutter/blob/1e35d3a6b702b9c804edc01fc4992567f7847f73/packages/flutter_tools/lib/src/linux/build_linux.dart#L61).
    - PR: https://github.com/flutter/flutter/pull/132579
- [x] Update [`xcode_build_settings.dart`](https://github.com/flutter/flutter/blob/1e35d3a6b702b9c804edc01fc4992567f7847f73/packages/flutter_tools/lib/src/ios/xcode_build_settings.dart#L188).
    - PR: https://github.com/flutter/flutter/pull/132579
- [x] Update [`build_windows.dart`](https://github.com/flutter/flutter/blob/1e35d3a6b702b9c804edc01fc4992567f7847f73/packages/flutter_tools/lib/src/windows/build_windows.dart#L252).
    - PR: https://github.com/flutter/flutter/pull/132579
- [x] Try a CI run where `--local-engine-host` is required, and fix CI bots, tests, and bash scripts that aren't using it
    - PR: https://github.com/flutter/flutter/pull/132707
- [x] Replace the warning message with `throwToolExit` and delete `_getHostEngineBasename` and friends

**Comment by matanlurey** [comment]
@christopherfujino Two quick questions:

1. Where, if anywhere, should we announce this change? I don't think it's important enough to be an "announcement", so maybe just `#hackers-engine` and `#hackers-tool` (and respective internal-only chat groups)? This is mostly just to make sure we get feedback if we're missing some nuance.
2. If I wanted to test "what if this was required", is the best way to make it a `throwToolExit` and create a draft PR?

**Comment by christopherfujino** [comment]
1. notifying those discord channels SGTM, I'd just add that you should update: https://github.com/flutter/flutter/wiki/The-flutter-tool#using-a-locally-built-engine-with-the-flutter-tool. That's where I point people when they ask how to do it.
2. That would test *most* of the framework tests (most devicelab tests don't run pre-submit, but I doubt any of them are using a local engine). @godofredoc do you know if there are any existing engine tests that use `flutter --local-engine`? Also, per https://github.com/flutter/flutter/pull/132180#discussion_r1289084382, it sounds like we may break golem?

**Comment by matanlurey** [comment]
@christopherfujino:

> 1. I'd just add that you should update: https://github.com/flutter/flutter/wiki/The-flutter-tool#using-a-locally-built-engine-with-the-flutter-tool

Want to informally review this delta before I apply it?
https://gist.github.com/matanlurey/ddb5e16e349c5bbdd0c1e036f189aed4

> 2. It sounds like we may break golem?

I'll follow-up with Bill's team and make sure they have ample time (or can show me where to make changes).

**Comment by matanlurey** [comment]
For posterity, we communicated the tooling changes via Discord:

![Screenshot 2023-08-10 at 12 36 10 PM](https://github.com/flutter/flutter/assets/168174/e523b18d-6533-43ff-ae29-0adbfcdf3207)

**Comment by christopherfujino** [comment]
> @christopherfujino:
> 
> > 1. I'd just add that you should update: https://github.com/flutter/flutter/wiki/The-flutter-tool#using-a-locally-built-engine-with-the-flutter-tool
> 
> Want to informally review this delta before I apply it? https://gist.github.com/matanlurey/ddb5e16e349c5bbdd0c1e036f189aed4
> 
> > 2. It sounds like we may break golem?
> 
> I'll follow-up with Bill's team and make sure they have ample time (or can show me where to make changes).

wiki diff LGTM

**Comment by matanlurey** [comment]
Wiki Updated:

https://github.com/flutter/flutter/wiki/_compare/30d1d87106d8ba04465e0f3432bb088a7636a3b3

**Comment by matanlurey** [comment]
Update: Making progress on dependent PRs (see above).

**Comment by whesse** [comment]
Golem is now using the --local-engine-host option everywhere. The only other thing in Dart that needs changing is the monorepo local usage instructions, but that is not blocking the change to mandatory option from landing.

**Comment by matanlurey** [comment]
> Do the instructions on https://github.com/flutter/flutter/wiki/Compiling-the-engine need to change

I don't think anything _needs_ to change. The instructions (and this issue) refer to how to specify what host platform to use when using the `flutter` tool. There are [some additional instructions here](https://github.com/flutter/flutter/wiki/Debugging-the-engine#using-the-flutter-tool) more specific to that workflow.

An occasional engine developer probably doesn't need to be concerned, AFAICT most of the engine team uses Rosetta (emulated `host_debug_unopt` on Mac) either on accident or on purpose; this change is to make it easier (well, possible) to use `host_debug_unopt_arm64` - and future platforms we don't even know about yet.

... so I guess that's a long-winded way of saying "no, they don't [strictly] need to change".

**Comment by mossmana** [comment]
If that is the case, then won't the majority of hosts used by the `flutter` tool still be `host_debug_unopt`, since that is what is being built? So it seems making `--local-engine-host` required will add additional overhead to the majority of developers who are using a local engine. Would it make sense to hold off on this requirement until the usage crosses a certain threshold to benefit the majority rather than inconvenience them?

**Comment by matanlurey** [comment]
> If that is the case, then won't the majority of hosts used by the `flutter` tool still be `host_debug_unopt`

Likely, until we make `--local-engine-host` mandatory, in which case it will be whatever developers specify.

> My preference at this time would be to keep the `--local-engine-host` optional

Thanks for the feedback. The overwhelming opinion so far has been either neutral or supportive of making it explicit:

- [Original issue on GitHub](https://github.com/flutter/flutter/issues/132162)
- Announcements on Discord: [1](https://discord.com/channels/608014603317936148/608022056616853515/1139280888069357658), [2](https://discord.com/channels/608014603317936148/608021010377080866/1139280978506948652)
- Thread [discussing the issue on Discord](https://discord.com/channels/608014603317936148/1139280978506948652/1141049848343314495)

The main rationale is the heuristics have always been faulty, and are NP-hard to get correct automatically. There is a constant trade-off between correct behavior and intuitive defaults. Given that we don't have a ton of casual engine contributors (as you've mentioned yourself in some tooling you were working on), we've decided to focus on making the platform explicit (versus inferred incorrectly).

As an added bonus it's future proof - any future platform will work out of the box.

**Comment by matanlurey** [comment]
Certainly it's [easy to update the Wiki](https://github.com/flutter/flutter/wiki/Compiling-the-engine/_compare/835dff1eb8acfdad18ac964e48c7e2733709071c), if that's the primary concern.

Does https://github.com/flutter/flutter/wiki/Compiling-the-engine look sufficient now?

**Comment by mossmana** [comment]
> Does https://github.com/flutter/flutter/wiki/Compiling-the-engine look sufficient now?

Looks like the edit was only made for Android. Do the same changes need to be made for the other platforms? (I still honestly don't know when you'd need to use another host.) Otherwise, LGTM. Thanks!

**Comment by matanlurey** [comment]
To be honest I don't know what the right tradeoff is around duplicated content. I find the Wiki nearly impossible to use.

I've added you to a private (internal) doc where @chinmaygarde is discussing another documentation approach (specific to Impeller, but could potentially be expanded to the engine repo at large).

**Comment by matanlurey** [comment]
Looking good so far. Will try finalizing this next week after it has baked a bit.
