### ISSUE TITLE
Clean up commands for analytics opt out

### ISSUE THREAD

**Issue by eliasyishak** [flutter/flutter#132258]
Currently we have two different flags that can be used for disabling analytics collection for the flutter tool. And this is because we currently have two different analytics systems within the flutter tool as we are incrementally migrating to [`package:unified_analytics`](https://pub.dev/packages/unified_analytics)

**Note: although there are two commands for disabling analytics, they both did the same thing by opting out of the legacy analytics system and from the new `package:unified_analytics` system.**

The legacy analytics system from `package:usage` used the following commands to enable and disable analytics

```terminal
flutter config --no-analytics // to disable

flutter config --analytics // to enable
```

While `package:unified_analytics` used the following flutter commands to achieve the same results
```terminal
flutter --disable-telemetry // to disable

flutter --enable-telemetry // to enable
```

This issue proposes we remove the `flutter --disable-telemetry` and `flutter --enable-telemetry` commands in favor of a new command below

```terminal
flutter --disable-analytics // to disable

flutter --enable-analytics // to enable
```

Those commands are the same as `dart --enable-analytics` and `dart --disable-analytics` and result in less confusion.

## Preventing Breaking Changes

The `flutter --disable-telemetry` and `flutter --enable-telemetry` are only 2 months old so likely won't break too many clients. However, `flutter config --no-analytics` and `flutter config --analytics` will likely break several clients so to prevent this, we will alias the following below.

So running:
`flutter --disable-analytics` will be an alias for `flutter config --no-analytics`
`flutter --enable-analytics` will be an alias for `flutter config --analytics`

**Comment by Hixie** [comment]
Oh I didn't realize we had _three_ sets of options, oops! :-)
