### ISSUE TITLE
New flaky leaks reported after leak_tracker update

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#132222]
The updates here https://github.com/flutter/flutter/pull/131998 have left some flaky failures on the framework tree, closing it. For example: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20framework_tests_libraries/12640/overview

**Comment by zanderso** [comment]
cc @polina-c

**Comment by polina-c** [comment]
thx

**Comment by polina-c** [comment]
The issue was fixed and leak_tracker is upgraded now. Closing.
