### ISSUE TITLE
[file_selector] `openFile` and `openFiles` without `acceptedTypeGroups` don't allow selecting files on iOS

### ISSUE THREAD

**Issue by mgenware** [flutter/flutter#132211]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I use file_selector's `openFile()` and `openFiles()` to pick up files. They work fine on Windows and Android. But on iOS, it shows a popup that no files can be selected:

![image](https://github.com/flutter/flutter/assets/11565096/4e245947-4f82-4ebf-9281-35a60dfc2945)

Turns out you need to pass a `public.item` type identifier as `acceptedTypeGroups`: 
```dart
[
  const XTypeGroup(uniformTypeIdentifiers: ['public.item'])
]
```

### Proposal

It makes no sense to open a file selector that cannot pick up any files. The `public.item` type identifier on iOS should be default if `acceptedTypeGroups` is empty. This makes sure that the same function call results in the same behavior on different platforms.

**Comment by stuartmorgan** [comment]
Retitling to describe the bug, rather than a specific proposed solution.

> The `public.item` type identifier on iOS should be default if `acceptedTypeGroups` is empty.

`public.item` includes directories, so would not be correct here. I believe `public.data` is the root type that would cover all actual files.
