### ISSUE TITLE
Error messages sent to LUCI are over-escaped

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#132276]
This should fix the problem (untested):

```patch
diff --git a/recipe_modules/test_utils/api.py b/recipe_modules/test_utils/api.py
index 90758791..3b309900 100644
--- a/recipe_modules/test_utils/api.py
+++ b/recipe_modules/test_utils/api.py
@@ -66,6 +66,12 @@ IDENTIFIER_NAME_MAP = {
 # Regexp for windows os version number
 _WINDOWS_OS_RE = r'\[version (\d+\.\d+)\.(\d+(?:\.\d+|))\]'
 
+# Same as StepFailure except that the message is assumed to be
+# already formatted. (StepFailure assumes that the message needs
+# to be further escaped.)
+class PrettyFailure(StepFailure):
+  def reason_message(self):
+    return '{}\nStep failed'.format(name)
 
 class TestUtilsApi(recipe_api.RecipeApi):
   """Utilities to run flutter tests."""
@@ -138,7 +144,7 @@ class TestUtilsApi(recipe_api.RecipeApi):
       stdout = self._truncateString(result.stdout)
       # Truncate stderr
       stderr = self._truncateString(result.stderr)
-      raise self.m.step.StepFailure(
+      raise PrettyFailure(
           '\n\n```%s```\n' % (stdout or stderr),
           result=result,
       )

```

**Comment by ricardoamador** [comment]
@Hixie Can you please provide an example of the output we are looking to fix?

**Comment by Hixie** [comment]
More or less any time a step fails, for example, some random failures in various shards from our dashboard in recent hours:

![2023-08-11-141344_1078x1000_scrot](https://github.com/flutter/flutter/assets/551196/5d6171a8-f798-446b-92dd-de23a9b77e93)
![2023-08-11-141340_1168x835_scrot](https://github.com/flutter/flutter/assets/551196/3a2c176c-b029-459c-865f-320ee52b6836)
![2023-08-11-141336_1136x981_scrot](https://github.com/flutter/flutter/assets/551196/a0ddebdb-1027-4567-8753-3f1e3d7e3ff9)
![2023-08-11-141332_1187x890_scrot](https://github.com/flutter/flutter/assets/551196/16466cb7-246b-48d6-af3b-69ece13639ac)
![2023-08-11-141328_1170x1085_scrot](https://github.com/flutter/flutter/assets/551196/f7bc2b58-243b-494b-9deb-fbaa8499cd4a)
![2023-08-11-141322_1123x1050_scrot](https://github.com/flutter/flutter/assets/551196/b5773c47-3a56-4585-81c5-2fcba8b51010)

**Comment by ricardoamador** [comment]
Thanks. I'll take a look today.

**Comment by ricardoamador** [comment]
This is fixed.

**Comment by Hixie** [comment]
see also https://flutter-review.googlesource.com/c/recipes/+/50080

**Comment by ricardoamador** [comment]
Thanks Ian! 
Also see: https://flutter-review.googlesource.com/c/recipes/+/49420
