### ISSUE TITLE
The recipes repo has no contributing instructions

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#132277]
It's not clear to me how a non-Googler can contribute to the [recipes repo](https://flutter.googlesource.com/recipes).

We should move this to GitHub like all our other repositories, and document clear contributing instructions.

**Comment by Hixie** [comment]
If you can point me to the contributing instructions for checking out the repo, creating a PR, and uploading it, I'll try it out and report back!

**Comment by godofredoc** [comment]
CL adding instructions: https://flutter-review.googlesource.com/c/recipes/+/49780
