### ISSUE TITLE
Android: Dead keys are not producing accented characters 

### ISSUE THREAD

**Issue by Dakkaron** [flutter/flutter#132297]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

This issue is identical to https://github.com/flutter/flutter/issues/86179, just on Android.

To reproduce:

1. Connect a physical keyboard to your Android device
2. Open any flutter app with text input
3. Try to use dead keys to compose characters

### Expected results

¨ + a should result in "ä"

### Actual results

¨ + a results in "¨a"

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData( primarySwatch: Colors.blue),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextFormField(),
            const TextField(),
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![Screenshot_20230810-130508~2](https://github.com/flutter/flutter/assets/6311558/630d6e3c-d911-4080-a09d-8d083821b211)

</details>

### Logs

<details><summary>Logs</summary>

```console

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
This is a known issue being tracked at https://github.com/flutter/flutter/issues/59541. Closing this issue as a duplicate, so please follow up on it for further updates.
