### ISSUE TITLE
[CP] Print pretty error when xcodebuild fails due to missing simulator

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#132265]
### Issue Link

https://github.com/flutter/flutter/issues/129558

### Commit Hash

2892b57

### Target

beta

### PR Link

https://github.com/flutter/flutter/pull/132235

### Changelog Description

Prints an easy to understand message when there is an error due to iOS 17 simulator runtime not being installed with Xcode 15.

### Impacted Users

All iOS Flutter developers using Xcode 15

### Impact Description

iOS Flutter developers using Xcode 15 who haven't downloaded the iOS 17 simulator will run into an error and won't be able to run Flutter. This PR does not fix that, but parses the error and prints a "prettier" message with clear instructions on how to fix.

### Workaround

Manually read and understand xcodebuild error, for reference, the xcodebuild error looks like:
```
Ineligible destinations for the "Runner" scheme:
		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device, error:iOS 17.0
		is not installed. To use with Xcode, first download and install the platform }
```
But you usually have to scroll up to find it.

### Risk

low

### Test Coverage

yes

### Validation Steps

1. Download Xcode 15, but don't download iOS 17 simulator.
2. Run `flutter run` on an iOS device/simulator
3. Should expect to see a "pretty" message that instructs how to fix the error

**Comment by CaseyHillers** [comment]
@christopherfujino can you review this CP request? If it looks good to you, add the "cp: approved" label.
