### ISSUE TITLE
Consider making `TabAlignment.start` the default tab alignment

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#132259]
After upgrading to the latest Flutter, I noticed all our tab bars in DevTools have this blank offset.

![Screenshot 2023-08-09 at 1 47 04 PM](https://github.com/flutter/flutter/assets/43759233/3100e994-4a5d-4df7-b96e-d2cd14c0b1c1)

I was able to resolve this by setting the `tabAlignment` property on the top level app theme, but this made me wonder why
`TabAlignment.startOffset` is the default? I suspect this will break many displays for apps where the `TabBarTheme.tabAlignment` property is not manually set to `start`.

**Comment by TahaTesser** [comment]
Please see https://docs.flutter.dev/release/breaking-changes/tab-alignment

This was done to match the Material specs for the scrollable `TabBar` and it can be changed to `start` with the new `tabAlignment` parameter.

### Material 2
![Screenshot 2023-08-10 at 11 48 05](https://github.com/flutter/flutter/assets/48603081/bde76f37-4942-4920-b04d-52b33e4f02f9)



### Material 3 
![Screenshot 2023-08-10 at 11 47 22](https://github.com/flutter/flutter/assets/48603081/1f9ed9b4-1d1d-4c15-abe5-f503d5652302)


cc: @Piinks

**Comment by Piinks** [comment]
(Triage) Since we default to the Material spec, have a migration guide, and backwards compatibility, I am going to close this. Thanks!
