### ISSUE TITLE
Need a sample to demonstrate how to use the Animation APIs

### ISSUE THREAD

**Issue by qchong** [flutter/flutter#1322]
Can we have a sample that shows how animations work? The sample should include code showing how to create an `Animation` and how to attach it to a widget via an `AnimationListener`.

**Comment by sethladd** [comment]
I think @HansMuller is working on a demo that highlights a lot of animations.

**Comment by HansMuller** [comment]
In addition to the demo I've been working on, I think a set of simple examples are in order.  I'd like to take a crack at those as well.

**Comment by nelsonkam** [comment]
@HansMiller Is there any link to a draft ?

**Comment by nelsonkam** [comment]
@HansMuller Is there any link to a draft ?

**Comment by Hixie** [comment]
We have many demos of animations now, and a whole guide: https://flutter.io/animations/
