### ISSUE TITLE
☂️ Upgrade CI to Xcode 15 and iOS 17 simulator

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#132237]
When Xcode 15 and iOS 17 release (probably September), we'll want to upgrade CI to use it.

## Infra
- [x] Xcode 15 requires macOS 13: https://github.com/flutter/flutter/issues/133207

### Issues
- [x] https://github.com/flutter/flutter/issues/133461
- [x] https://github.com/flutter/flutter/issues/133458
- [x] https://github.com/flutter/flutter/issues/139693

## Framework
- [x] https://github.com/flutter/flutter/pull/141706

### Issues
- [x] https://github.com/flutter/flutter/issues/132755
- [x] https://github.com/flutter/flutter/issues/132975
- [x] https://github.com/flutter/flutter/issues/132980
- [x] https://github.com/flutter/flutter/issues/132990
- [x] https://github.com/flutter/flutter/issues/133061
- [x] https://github.com/flutter/flutter/issues/139917

## Packages
- [x] https://github.com/flutter/packages/pull/5914

### Issues
- [x] https://github.com/flutter/flutter/issues/132975
- [x] https://github.com/flutter/flutter/issues/133061
- [x] https://github.com/flutter/flutter/issues/136737
- [x] https://github.com/flutter/flutter/issues/136747
- [x] https://github.com/flutter/flutter/issues/136827

## Engine
- [x] https://github.com/flutter/engine/pull/49833

### Issues
- [x] https://github.com/flutter/flutter/issues/128958
- [x] https://github.com/flutter/flutter/issues/133776
- [x] https://github.com/flutter/flutter/issues/133783
- [x] https://github.com/flutter/flutter/issues/134079
- [x] https://github.com/flutter/flutter/issues/140181

**Comment by tologonkudaiberdiuulu** [comment]
@vashworth ios and xcode released. And there's no podfile(or moved somewhere, I couldn't find). Old apps not working with xcode 15 stable release. Please fix it ASAP

**Comment by vashworth** [comment]
> @vashworth ios and xcode released. And there's no podfile(or moved somewhere, I couldn't find). Some old apps not working with xcode 15 stable release. Please fix it ASAP

@tologonkudaiberdiuulu Can you file a new issue at https://github.com/flutter/flutter/issues/new/choose with a description of any errors you're seeing and and include reproducible steps?

**Comment by vashworth** [comment]
All repos have been updated.
