### ISSUE TITLE
People are confused when they search and find a webpage hosted on a staging server

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#13227]
When PRs are submitted to Flutter's website, they often trigger a "staging server" to deploy the PR. Sometimes, search engines find these staging servers and return those results to users. This confuses the user, as they think they are looking at canonical docs but instead are looking at staging/test docs.

Strawman proposal:

* add robots.txt to every staging server (any server that is NOT flutter.io)
* add some JS that detects the user is NOT looking at flutter.io and puts up a banner of some sort

**Comment by sethladd** [comment]
cc @mjohnsullivan @filiph

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1827](https://github.com/flutter/website/issues/1827) via [**ZenHub**](https://www.zenhub.com/)
