### ISSUE TITLE
[CP] Check for iOS simulator runtime in flutter doctor for Xcode 15

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#132256]
### Issue Link

https://github.com/flutter/flutter/issues/129558

### Commit Hash

b39604e

### Target

beta

### PR Link

https://github.com/flutter/flutter/pull/132230

### Changelog Description

Warns users via `flutter doctor` when using Xcode 15 and the iOS 17 simulator runtime is not installed.

### Impacted Users

All iOS Flutter developers using Xcode 15

### Impact Description

iOS Flutter developers using Xcode 15 who haven't downloaded the iOS 17 simulator will run into an error and won't be able to run Flutter. This PR does not fix that, but adds a warning to `flutter doctor` to help instruct users how to fix the problem.

### Workaround

NA

### Risk

medium

### Test Coverage

yes

### Validation Steps

1. Download Xcode 15, but don't download iOS 17 simulator.
2. Run `flutter doctor`
3. Should expect to see a warning about missing simulator
4. Download and install iOS 17 simulator
5. Run `flutter doctor`
6. Should not see warning

**Comment by CaseyHillers** [comment]
@christopherfujino can you review this CP request? If it looks good to you, add the "cp: approved" label.
