### ISSUE TITLE
[Autocomplete] Alignment & Size constraints of Overlay are off

### ISSUE THREAD

**Issue by sabin26** [flutter/flutter#132220]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run the code sample
2. Bring the overlay by typing something into the `Autocomplete` widget.

### Expected results

The overlay should be properly aligned and sized.

### Actual results

The overlay is not properly aligned nor sized.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        body: Center(
          child: FractionallySizedBox(
            widthFactor: 0.8,
            heightFactor: 0.5,
            child: Dialog(
              child: Padding(
                padding: const EdgeInsets.all(8.0),
                child: Autocomplete(
                  optionsBuilder: (TextEditingValue textEditingValue) {
                    if (textEditingValue.text == '') {
                      return const Iterable<String>.empty();
                    }
                    return kOptions.where((String option) {
                      return option.contains(textEditingValue.text.toLowerCase());
                    });
                  },
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

const List<String> kOptions = <String>[
  'aardvark',
  'bobcat',
  'chameleon',
];
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![autocomplete_bug](https://github.com/flutter/flutter/assets/61322712/24ee4168-a286-48a3-9a66-da965e6ece39)

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 3.13.0-0.3.pre, on Microsoft Windows [Version 10.0.19045.3208], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.3)
[√] Android Studio (version 2022.2)
[√] VS Code (version 1.81.0)
[√] Connected device (3 available)
[√] Network resources

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@sabin26 
I think you are hitting https://github.com/flutter/flutter/issues/78746, so please follow-up in it for further updates.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.
