### ISSUE TITLE
[CP] Update material translations

### ISSUE THREAD

**Issue by itsjustkevin** [flutter/flutter#132316]
### Issue Link

https://github.com/flutter/flutter/issues/130874

### Commit Hash

f4c25bb

### Target

beta

### PR Link

https://github.com/flutter/flutter/pull/132315

### Changelog Description

Updates translation list for all supported languages.

### Impacted Users

Flutter devs

### Impact Description

Users will not have updated translation files, impacting customers who rely on these translations. 

### Workaround

N/A

### Risk

medium

### Test Coverage

yes

### Validation Steps

N/A

**Comment by itsjustkevin** [comment]
@HansMuller @justinmc could you take a look at this cherry-pick and request?

**Comment by justinmc** [comment]
:+1:
