### ISSUE TITLE
When iOS starts, the image cannot be loaded, whether it is a local image or a network image

### ISSUE THREAD

**Issue by WuChuanRong** [flutter/flutter#132369]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

iPhone 14 Pro
version: 16.5.1

iPhone 12 mini
version: 16.5.1

iPhone 14 Pro Max 
version: 17.0

At present, these models of mobile phones will occasionally load abnormal pictures when opening the App

### Expected results

The pink boxes are all Image，Restarting the App is normal again, but this happens occasionally

### Actual results

iOS image loading exception

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![1691730500777](https://github.com/flutter/flutter/assets/33706740/0ce76d0a-60bc-4244-9132-62de1ecaa09c)
![WechatIMG79](https://github.com/flutter/flutter/assets/33706740/fe46f7e3-5627-47d1-bb43-0eb74495bc43)
![WechatIMG80](https://github.com/flutter/flutter/assets/33706740/9daaa643-4527-4f95-9801-9a91c5b28e21)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

[✓] Flutter (Channel stable, 3.10.0, on macOS 13.3.1 22E772610a darwin-arm64 (Rosetta), locale zh-Hans-HK)
    • Flutter version 3.10.0 on channel stable at /Users/szteam/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (3 months ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/szteam/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/szteam/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Connected device (3 available)
    • iPhone Xs (mobile) • 00008020-000909663C62002E • ios            • iOS 16.3.1 20D67
    • macOS (desktop)    • macos                     • darwin-arm64   • macOS 13.3.1 22E772610a
      darwin-arm64 (Rosetta)
    • Chrome (web)       • chrome                    • web-javascript • Google Chrome 112.0.5615.49

[✓] Network resources
    • All expected network resources are available.

</details>

**Comment by WuChuanRong** [comment]
@darshankawar

**Comment by danagbemava-nc** [comment]
Hi @WuChuanRong, a similar issue was reported in https://github.com/flutter/flutter/issues/126878 which has since been fixed and is available on the latest version of flutter stable, can you upgrade to the latest version of flutter stable (3.10.6) to see if you still face this issue?

**Comment by WuChuanRong** [comment]
Thank you very much, I will try to update to the latest version.
