### ISSUE TITLE
Invalid path in Home Screen Widgets tutorial

### ISSUE THREAD

**Issue by kakopappa** [flutter/flutter#132382]
In https://codelabs.developers.google.com/flutter-home-screen-widgets#1

![image](https://github.com/flutter/flutter/assets/7474406/cb71527a-f346-41e5-bd0e-d61ad9a51f6a)

Open the flutter-codelabs/homescreen-widgets/step_03 directory into your preferred IDE.

Should be

flutter-codelabs/homescreen_codelab/step_03

Happy to send a PR if tutorials are open source.

**Comment by dam-ease** [comment]
Hi @kakopappa. Thanks for pointing this out. I see the same in the documentation. 

cc: @domesticmouse

**Comment by domesticmouse** [comment]
PTAL @ericwindmill

**Comment by felipecastrosales** [comment]
Hey, I would open an isue about this documentation too. 

I found more problems: 

![image](https://github.com/flutter/flutter/assets/59374587/e44de04a-879a-4485-a5d6-6ec2621f8d21)

1. The link on `lib/news_data.dart` should be [this](https://github.com/flutter/codelabs/blob/main/homescreen_codelab/step_03/lib/news_data.dart) instead [of](https://github.com/flutter/codelabs/blob/homescreen_widgets/homescreen_codelab/step_03/lib/news_data.dart#LL1C1-L13C2), and this is applied to other several mentions to files.
2. The class snippet has missing `}` for close the class scope and is missing the `const` in the constructor. 
3. In `floatingActionButton` has unnecessary `async` keyword usage.

![image](https://github.com/flutter/flutter/assets/59374587/08817a55-661a-4b74-89c8-632aed7c1bec)

**Comment by felipecastrosales** [comment]
I see this should be open-source. We could have already opened a PR resolving this (now!).

**Comment by felipecastrosales** [comment]
Another typo:

![image](https://github.com/flutter/flutter/assets/59374587/4bc05002-e3c6-4d48-90a6-d59f441c4970)

**Comment by felipecastrosales** [comment]
In addiction, this parameter doesn't exist in repository: 

![image](https://github.com/flutter/flutter/assets/59374587/50fb6f15-6e76-40fc-9ae8-717027c19ff1)

I have a lot problems with this tutorial and I didn't get where I wanted. 

It seems to me that there are a few details missing in the writing and operation of it. For me, none of the applications worked as expected (Android and iOS) even though I carefully followed the recommended steps.

**Comment by ericwindmill** [comment]
Thank you @felipecastrosales, all issues have been addressed and changes are in-flight.

**Comment by domesticmouse** [comment]
I believe this is now fixed
