### ISSUE TITLE
Firefox browser is getting crash using flutter integration test for web automation

### ISSUE THREAD

**Issue by sawanS** [flutter/flutter#132329]
### Page URL

NA

### Describe the problem

When I am trying to run web automation test using .sh file for all 3 browser i.e chrome, safari and firefox then firefox is keep crashing after performing certain steps. Firefox is shutting down according to logs and after crashing firefox it takes almost 20 min to failed the test saying "**Flutter has exited unexpectedly.** However, same script is working completely fine with safari and chrome browser. Just wanted to understand the reason for failure and would like to hear solution from community. Any help would be highly appreciated. Thanks!

### Expected fix

Firefox crashing should be fixed while running web automation test.

**Comment by darshankawar** [comment]
@sawanS Thanks for the report.
Can you provide us a minimal reproducible code sample that shows the error reported ? 
If you try to run it individually / manually in firefox (without sh file trigger), does it still throw the error and crash ?

Also provide us the complete crash log so that we can take a look at what's going on.

**Comment by sawanS** [comment]
@darshankawar Yes it is crashing even if we are running individual test.


Steps for individual runs:

1. initiating geckodriver instances using geckodriver --port=4444
2. Calling test using below command for firefox:

flutter drive --driver=integration_test/website_Automation/ITDriver_test.dart --target=integration_test/website_Automation/testScripts/$testScriptName.dart -d web-server --browser-name=firefox --flavor $env --dart-define=environment=$env --dart-define=listenForOtp=false --no-sound-null-safety --no-headless

Result:
1. launch the browser
2. login into the app
4. perform certain steps and then It's crashing




Steps though .sh file:



env=$1
./configure-web.sh $env
echo "***** Environment from pipeline stage: $(echo $env | tr '[:lower:]' '[:upper:]') environment *****"
"$@"

flutter clean
flutter pub get
STATUS=0


echo "Initialising firefox driver"
geckodriver --port=4444 --log error >/dev/null & _pid=$!
echo "$_pid"

run_test () {
  echo "=============================== Starting new test script execution ==============================="
  arg1=$1
  testScriptName="$arg1"

  if
flutter drive --driver=integration_test/website_Automation/ITDriver_test.dart --target=integration_test/website_Automation/testScripts/$testScriptName.dart -d web-server --browser-name=firefox --flavor $env --dart-define=environment=$env --dart-define=listenForOtp=false --no-sound-null-safety --no-headless


  then
    echo "********** ✅ Test Passed. ⏹️ Stopping screen recording **********"
    sleep 5
#    pkill -f screenrecord
#    sleep 5
#    pkill -f screenrecord
    passed_test_scripts_array[$passed_test_scripts_count]=$testScriptName".dart"
    let passed_test_scripts_count+=1
    echo "Passed count : "$passed_test_scripts_count
    #flutter test passed. Waiting for 10 sec for video processing to complete before pulling the video to local system
    sleep 10
#    pull_video $testScriptName
  else
    echo "********** ❌ Test Failed. ⏹️ Stopping screen recording **********"
    sleep 5

    STATUS=1
    echo $STATUS
    failed_test_scripts_array[$failed_test_scripts_count]=$testScriptName".dart"
    let failed_test_scripts_count+=1
    echo "Failed count : "$failed_test_scripts_count
    #flutter test failed. Waiting for 10 sec for video processing to complete before pulling the video to local system
    sleep 10
  fi
}

if [ "$env" != "cug" ]
  then
     

    run_test testscriptname.test
    
  else
    run_test demo_web_test
fi



# Delete individual tests recording folder

rm -r testScriptname_test

echo "Closing firefox driver"
echo "$_pid"
kill -9 "$_pid"




**I have mentioned both ways to triggers test in firefox but it is keep crashing irrespective of way we trigger the test**

**Comment by sawanS** [comment]
@darshankawar  - please find the logs below.

[
[Geckodriver log.txt](https://github.com/flutter/flutter/files/12319150/Geckodriver.log.txt)
](url)

**Comment by darshankawar** [comment]
It seems it could be related to geckodriver + firefox. I see that you have already filed an issue in dedicated repo: https://github.com/mozilla/geckodriver/issues/2124 so I suggest you to follow-up in it and check what that team says about the crash. If they direct you to here, write in comments and we'll take it up further.
