### ISSUE TITLE
assets-for-api-docs repo can't run presubmits anymore.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#132355]
The assets-for-api-docs repo can't run presubmits anymore. It seems to have a problem authenticating with Cirrus.

See here for an example failure:
https://github.com/flutter/assets-for-api-docs/pull/221/checks?check_run_id=15803091607

This links to the Cirrus run:
https://cirrus-ci.com/task/5763072120324096

Which has the error:
```
Failed to stop: Error getting access token for service account: 400 Bad Request POST https://oauth2.googleapis.com/token {"error":"invalid_grant","error_description":"Invalid JWT Signature."}, iss: cirrus-ci@flutter-cirrus.iam.gserviceaccount.com
```

**Comment by keyonghan** [comment]
This is due to key expiration. Fix: https://github.com/flutter/assets-for-api-docs/pull/222
