### ISSUE TITLE
Instructions for creating a pub package mirror like China has.

### ISSUE THREAD

**Issue by harri-pasanen** [flutter/flutter#132393]
Hi,

In corporate environments with limited internet access the development experience is currently worse than in China.

It would be useful to have documented way to create required mirrors, equivalent to:

export PUB_HOSTED_URL=https://pub.flutter-io.cn
export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn

I'm sure many corporate users would be happy to use a similar method, as well as those of use who often work from locations with bad internet connectivity, but where on can easily carry a portable hard drive to to update the mirror.

**Comment by huycozy** [comment]
Hi @harri-pasanen 
It seems your request is best suited for [pub-dev](https://github.com/dart-lang/pub-dev) and [pub](https://github.com/dart-lang/pub) repositories, so please ask the same there or check below similar issues:

- https://github.com/dart-lang/pub-dev/issues/4665
- https://github.com/dart-lang/pub-dev/issues/4671 (there are some options but I'm not sure which one is suitable for your case)
- https://github.com/dart-lang/pub/issues/2993
