### ISSUE TITLE
Mention initState() in "Using Hot Reload" page

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter#13235]
The discussion of hot reload at  [](https://flutter.io/hot-reload/) is good but I have one suggestion to consider. For a new user like myself, it is not obvious when `initState()` is called. It might be worth mentioning that changes to an implementation of State.initState() will not be apparent after hot reload.

**Comment by sethladd** [comment]
Thanks for the feedback!

This may be related to https://github.com/flutter/flutter/issues/11431 and perhaps related to https://github.com/flutter/flutter/issues/7047

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1991](https://github.com/flutter/website/issues/1991) via [**ZenHub**](https://www.zenhub.com/)
