### ISSUE TITLE
Make it possible to configure textCapitalization for SearchAnchor

### ISSUE THREAD

**Issue by PerLycke** [flutter/flutter#132301]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Our company have an app where you search for license plates. License plates are always constructed with capital letters. It would be user friendly to be able to configure the platform keyboard to select uppercase only by being able to set textCapitalization for the SearchAnchor.

I don't think it's a super wild idea to consider other cases where you want to configure textCapitalization for SearchAnchor, thus I hope this is a valid request.

### Proposal

Make it possible to configure textCapitalization for SearchAnchor.

**Comment by dam-ease** [comment]
Hi @PerLycke. Thanks for proposing this. This seems to have been implemented on the latest `master` with https://github.com/flutter/flutter/pull/131459
You can check though the master [docs](https://master-api.flutter.dev/flutter/material/SearchAnchor-class.html) and also by switching to the latest master channel.

Closing this as it has been implemented in newer versions. Thank you!
