### ISSUE TITLE
flutter_widget_from_html_core >=0.9.0 which requires Flutter SDK version >=3.3.0, version solving failed.

### ISSUE THREAD

**Issue by brayuko** [flutter/flutter#132394]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

good afternoon! Can someone help me? I'm having difficulty generating the application with flutter, this error appears: Because efood_multivendor depends on flutter_widget_from_html_core >=0.9.0 which requires Flutter SDK version >=3.3.0, version solving failed.

flutter version for this project is 3.0.1 and gradle 6.3

### Expected results

normally generates no errors, I'm starting now and I'm having some difficulties

### Actual results

PS C:\Users\corel\Desktop\App\STACKFOOD_CLIENTE_USUARIO_6.2.0> flutter pub get
The current Flutter SDK version is 3.0.1.

Because efood_multivendor depends on flutter_widget_from_html_core >=0.9.0 which requires Flutter SDK version >=3.3.0, version solving failed.      
Running "flutter pub get" in STACKFOOD_CLIENTE_USUARIO_6.2.0...             
pub get failed (1; Because efood_multivendor depends on flutter_widget_from_html_core >=0.9.0 which requires Flutter SDK version >=3.3.0, version
solving failed.)
PS C:\Users\corel\D

### Code sample

PS C:\Users\corel\Desktop\App\STACKFOOD_CLIENTE_USUARIO_6.2.0> flutter create bug 
Creating project bug...
Running "flutter pub get" in bug...                                 5,8s
Wrote 127 files.
In order to run your application, type:

  $ cd bug
  $ flutter run

Your application code is in bug\lib\main.dart.

PS C:\Users\corel\Desktop\App\STACKFOOD_CLIENTE_USUARIO_6.2.0> cd bug
PS C:\Users\corel\Desktop\App\STACKFOOD_CLIENTE_USUARIO_6.2.0\bug> flutter run
Multiple devices found:
Windows (desktop) • windows • windows-x64    • Microsoft Windows [versÆo 10.0.19045.3208]
Chrome (web)      • chrome  • web-javascript • Google Chrome 115.0.5790.171
Edge (web)        • edge    • web-javascript • Microsoft Edge 115.0.1901.200
[1]: Windows (windows)
[2]: Chrome (chrome)
[3]: Edge (edge)

### Screenshots or Video

┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [versÆo 10.0.19045.3208], locale pt-BR)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.6.5)
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.80.1)
[√] Connected device (3 available)
[√] HTTP Host Availability
• No issues found!

![image](https://github.com/flutter/flutter/assets/100873696/cc4c336f-d473-4824-9b08-5ca7e0dbbb69)

### Logs

[log.txt](https://github.com/flutter/flutter/files/12323147/log.txt)

### Flutter Doctor output

[log.txt](https://github.com/flutter/flutter/files/12323199/log.txt)

**Comment by huycozy** [comment]
Hi @brayuko 
The error message is quite clear. You should use a higher Flutter version (>=3.3.0) or a lower package version (<0.9.0), see that package changelog [here](https://pub.dev/packages/flutter_widget_from_html_core/changelog#090).

Closing the issue as it's not a Flutter framework bug.

**Comment by brayuko** [comment]
oops, cool, I'm newbie, how do I change to a lower version of the package (<0.9.0)?

**Comment by huycozy** [comment]
You should use a concrete version number, like this: `flutter_widget_from_html_core: 0.8.5+3` (without caret). FYI: https://dart.dev/tools/pub/dependencies#caret-syntax.

Please remember to clean pub since it cached a higher version already. For further questions, please ask on support channels like StackOverflow for solutions if any.
