### ISSUE TITLE
I typed flutter run in terminal, but there's a error

### ISSUE THREAD

**Issue by 1027jason** [flutter/flutter#132300]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

flutter run

### Actual results

PS C:\Windows\System32\toonflix> flutter run
Launching lib\main.dart on SM T875N in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     C:\Windows\System32\toonflix\build\app\intermediates\packaged_manifests\debug\AndroidManifest.xml: error: failed to load XML file: �??��?�� ?��?��?�� 찾을 ?�� ?��?��?��?��. (2).

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 14s
Running Gradle task 'assembleDebug'...                             77.3s
Exception: Gradle task assembleDebug failed with exit code 1
PS C:\Windows\System32\toonflix> 

### Logs

maybe,it doen't matter

### Flutter Doctor output

maybe,it doen't matter>

**Comment by danagbemava-nc** [comment]
Hi @1027jason, it seems like you're running your app in a directory that requires elevated access can you move the app to a folder that doesn't require elevated access like your desktop to see if you still have this issue? 

Please provide the output of `flutter doctor -v` in case you still face the issue after moving the project folder to one that doesn't require elevated access.
