### ISSUE TITLE
[go_router] Unable to navigate across path branches with retained history.

### ISSUE THREAD

**Issue by tjarvstrand** [flutter/flutter#132387]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I'm building an event app. On the page for an event inside the app, there's a list of users you can tap, to see their profile. You can the continue from there to that user's events, or their friends' profiles etc.

Suppose I have a route list looking something like this:
```
List<GoRoute> routes_ = [
  GoRoute(
    path: '/events/:id',
    builder: (context, _) => TextButton(child: const Text('Go'), onPressed: () => context.go('/users/myUser')),
  ),
  GoRoute(
    path: '/users/:username',
    builder: (_, state) => Text(state.pathParameters['username'] as String),
  ),
];
```

Using go_router, I'm unable to navigate from `/events/myEvent` to `/users/myUser` and then be able to go back again, without keeping track of the (potentially deeply nested) history myself. 

On web, the browser back button works, but on mobile there's no way at all to come back to the original event page.

### Proposal

Please add a way to store history across different path branches.

**Comment by dam-ease** [comment]
Hi @tjarvstrand. Thanks for proposing this. This seems to be similar to https://github.com/flutter/flutter/issues/115353. Can you confirm it is??

**Comment by tjarvstrand** [comment]
Ah, yes, that is quite similar! I wasn't sure what to look for among all the issues so I must have missed it. I'll close this. Sorry for the noise!
