### ISSUE TITLE
go_router version bump needs to be reflected in codelab content

### ISSUE THREAD

**Issue by Nursen** [flutter/flutter#132465]
In the [firebase get to know flutter codelab](https://firebase.google.com/codelabs/firebase-get-to-know-flutter#4)

Line 71 of main.dart in step_05 (and subsequent steps) should be updated from

final arguments = state.queryParameters;

to 

final arguments = state.uri.queryParameters;

to reflect the [update](https://github.com/flutter/codelabs/commit/f02b4427b8f9cec317693a582a38299dc57e1e55) in go_router version. 

Apologies if there's a better place to report this issue, this is the destination provided for reporting errors via the "report a mistake" link in the lower left of the codelab

**Comment by opxdelwin** [comment]
I checked with `codelabs` official repository for the mentioned changes. They have updated the code, but the website is yet to be re-deployed with new changes.  

See also: [latest code](https://github.com/flutter/codelabs/blob/main/firebase-get-to-know-flutter/step_05/lib/main.dart)  and [Pull request](https://github.com/flutter/codelabs/pull/1791)
Expect soon. Feel free to close this issue...

**Comment by dam-ease** [comment]
Hi @Nursen. Thanks for filing this. Also, thanks for your input @opxdelwin. Per this PR https://github.com/flutter/codelabs/pull/1791, I see this has been fixed and should be released soon. Thank you!

**Comment by Nursen** [comment]
Thank you @opxdelwin and @dam-ease. If I run into anything else I'll know where to file it for more specificity.
