### ISSUE TITLE
Progress bar on video in gallery doesn't scrub

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#13243]
When I tap the video in the gallery, I see a dedicated screen for the video. A progress bar appears.

I can't seem to be able to scrub the video forward and back smoothly with the progress bar.

Also, when I tap the progress bar, the video doesn't seem to jump to my tap location.

**Comment by sethladd** [comment]
cc @mit-mit @sigurdm Not sure if there's another label for this, so I created "video". Feel free to delete that label and use another one.

**Comment by sigurdm** [comment]
I'll take a shot at implementing scrubbing. I think it is mainly a question of listening to drag events.

The android media player does not jump very exactly to the given location.
That shows up very clearly when the video is short. Not sure exactly how to solve that.

**Comment by sigurdm** [comment]
Scrubbing was done by https://github.com/sigurdm/plugins/pull/4

**Comment by sethladd** [comment]
Thanks for the update!

Can a developer choose to use another video player? I recall someone mentioning there are better video players, perhaps with better scrubbing?

**Comment by sigurdm** [comment]
Not without reimplementing the platform side of the plugin for said player.
