### ISSUE TITLE
Provide a way to preload color emoji on web

### ISSUE THREAD

**Issue by crizant** [flutter/flutter#132425]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

On web, we can add `useColorEmoji: true` to use Noto Color emoji.
But before it gets loaded, all emojis are displayed as a block with a question mark in it.
I tried something like this in my loading screen before rendering any emojis:
```
await GoogleFonts.pendingFonts([
    GoogleFonts.notoColorEmoji(),
])
```
Which does nothing except make the loading time of my app 10s longer.

### Proposal

Can we have something like `WebColorEmoji.precache()` to let us load the NotoColorEmoji font before we actually render it?

**Comment by darshankawar** [comment]
Thanks for the report @crizant 
Can you take a look at [this](https://github.com/flutter/flutter/issues/101171) issue and check if it resembles your case or not ?

**Comment by crizant** [comment]
> Thanks for the report @crizant Can you take a look at [this](https://github.com/flutter/flutter/issues/101171) issue and check if it resembles your case or not ?

No. They are totally different.

**Comment by ditman** [comment]
I think this is a duplicate/similar to:

* https://github.com/flutter/flutter/issues/78422
