### ISSUE TITLE
FlutterEngineSendKeyEvent only sends message to the flutter/keydata channel after a flutter/keyevent message 

### ISSUE THREAD

**Issue by eladmaimoni** [flutter/flutter#132433]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

In the `embedder.h` documentation, It is said the the proper way to send the engine / framework with keyboard events is via the `FlutterEngineSendKeyEvent` function.

When sending keyboard events via this function, I can see that it internally sends a platform message to the "flutter/keydata" channel containing the data.

On the framework side, I can see ui.KeyData is received by the KeyEventManager. however, it seems that the manager only trigger keyboard events if a RawKeyEvent is recieved also. Or at least this is what one would think. Anyway, It is not properly documented in the `embedder.h` api what is the proper way to trigger keyboard events on the framework side, or that simply `FlutterEngineSendKeyEvent` has a bug. as by itself it does not trigger keyboard event like its documentation implies.

So please, either clarify the documentation or make sure `FlutterEngineSendKeyEvent` does the right thing.

### Expected results

`FlutterEngineSendKeyEvent` will trigger keyboard events on the framework side.

### Actual results

On the Framework side, `ui.KeyData` objects are buffered, `KeyEventManager` never triggers keyboard events.

### Code sample

```
FlutterKeyEvent keyEvent {
            .struct_size = sizeof(FlutterKeyEvent),
            .timestamp = static_cast<double>(CurrentTimeMicroseconds()),
            .type = FlutterKeyEventType::kFlutterKeyEventTypeDown,
            .physical = SDL_TO_PHYSICAL_MAP.at(scancode),
            .logical = SDL_TO_LOGICAL_MAP.at(key),
            .character = key_name,
 };

FLUTTER_CHECK(_engine.SendKeyEvent(_flutterEngine, &keyEvent , KeyboardFlutter, nullptr));
```

### Flutter Doctor output

[!] Flutter (Channel [user-branch], 3.12.0-11.0.pre.11, on Microsoft Windows [Version 10.0.22621.2134], locale en-US)
    ! Flutter version 3.12.0-11.0.pre.11 on channel [user-branch] at C:\libs\flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at
      https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision 176f7e6382 (7 weeks ago), 2023-06-25 00:00:25 -0400
    • Engine revision 100f6fc854
    • Dart version 3.1.0 (build 3.1.0-246.0.dev)
    • DevTools version 2.24.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33829.357
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.81.1)
    • VS Code at C:\Users\mrmai\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.2134]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 115.0.1901.200

[✓] Network resources
    • All expected network resources are available.

**Comment by eladmaimoni** [comment]
after investigating this further, it seems all the embedders I have seen use the flutter/keyevent channel only. also, flutter contains translation layers specific to glfw and GTK toolkits in the linux releted keyboard handling code inside the framework. 

In my case, I use SDL for windowing and it seems there is not even some sort of undocumented support for that. 

So what exactly does the flutter team expect the embedders to do in order to get cross platform key handling working?

maybe @stuartmorgan could comment? seems like there have been some [suggestions](https://docs.google.com/document/u/0/d/1FDuxxEh810XpY561SgeiyUR0gU2eVz5kRpCFI55ibec/mobilebasic?pli=1) related to this.

**Comment by eladmaimoni** [comment]
@darshankawar yes I have looked at this issue and many related issues.

The thing is, it is unclear what is expected from embedders regarding keyboard and text input. 

- Do they need to send platform messager?
- Do they need to use the embedder API? maybe both? at what sequence?
- What part does the flutter/textinput plays on that regard? what is the minimun the embedder needs to do with regards to it?

I think that it should be enough for the embedder to call `FlutterEngineSendKeyEvent` so that text input will work. and if it is not enough, it should be explained / documented what is missing.
`FlutterEngineSendKeyEvent` simply returns success, but figuring out what is missing in order to make simple text input widgets work is really painful.

**Comment by stuartmorgan** [comment]
> maybe @stuartmorgan could comment?

I'm not sure why I was pinged for comment here; I didn't write the key event system or the linked design document, and I don't own embedder.h

**Comment by eladmaimoni** [comment]
my bad, sorry. I guessed I confused you with other issues. 
I think I meant @gspencergoog

**Comment by dkwingsmt** [comment]
Yes, this is an intended behavior, and I'm sorry that it has caused such confusion. It serves as compatibility design before `flutter/keyevent` is removed from Flutter, which I've never had time to finish. I'll add this clarification to embedder.h.

**Comment by eladmaimoni** [comment]
Thanks for the clarification @dkwingsmt. This will be a welcome fix.

**Comment by dkwingsmt** [comment]
I've created https://github.com/flutter/flutter/pull/132533 by adding some docs to `KeyEventManager`. I'm not sure if explaining this to `FlutterEngineSendKeyEvent` is a better option, because this protocol doesn't apply to code under `PlatformDispatcher.onKeyData`, but only `KeyEventManager` and everything relies on it. Let me know what you think.

**Comment by eladmaimoni** [comment]
@dkwingsmt thanks. It makes thing slightly clearer. though I still don't fully understand why in the newer mode we need to wait for the legacy `flutter/keyevent` in order to raise events. wouldn't it be better to simply ignore them and raise an event anyway?

Unless embedders stumble across `KeyEventManager` docs,  they might still be led to believe that  calling `FlutterEngineSendKeyEvent` is enough

Thanks!

**Comment by dkwingsmt** [comment]
@eladmaimoni I agree that it's an unintuitive way to design a protocol, and it's not the most obvious place to explain it. The reason why the two message channels are entangled like this is, first, to ensure compatibility, so that platforms that don't support `flutter/keydata` can also generate `KeyEvent`s. Of course, we could've designed the compatibility protocol in a better way. But also even if we did, embedder implementations will still have to implement `flutter/keyevent` instead of just calling `FlutterEngineSendKeyEvent`s, because many legacy apps are still using `RawEvent` or `onKey`.

Again, it's unfortunate that I've never had the bandwidth to remove `RawKeyboard` as I planned. When we do, this will be much simpler.
