### ISSUE TITLE
[Impeller] Re-land "DlCanvas implementation wrapping Aiks canvas"

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#132416]
The original patch (https://github.com/flutter/engine/pull/44248 by @dnfield) was reverted (https://github.com/flutter/engine/pull/44466 by @jason-simmons) following odd benchmark behavior (https://github.com/flutter/flutter/issues/132071 by @gaaclarke).

@gaaclarke also reported observing rendering artifacts in Wondrous and @flar also left some comments after the patch landed.

This issue tracks relanding the patch after issues have been sorted out.

**Comment by chinmaygarde** [comment]
@gaaclarke If you remember, can you detail the rendering artifacts you noticed?

**Comment by gaaclarke** [comment]
> @gaaclarke If you remember, can you detail the rendering artifacts you noticed?

I don't remember what they looked like but if you run Wonderous, errors will be printed out on the terminal.

**Comment by jonahwilliams** [comment]
The draw points macrobenchmark failed to render also

**Comment by dnfield** [comment]
I've fixed the rendering failures (one of them was fixed by @bdero in https://github.com/flutter/engine/pull/44835, one of them was a bug in new code being added that resulted in me filing https://github.com/flutter/flutter/issues/132770).

I've re-run old gallery transitions perf and still see very promising numbers. But now I want to understand why I didn't get those numbers in the devicelab, and how/whether to better integrate with @flar 's patch to separate out DlCanvasToReceiver.

**Comment by dnfield** [comment]
Ok, I see regressions now in some other benchmarks that I'll look into.

**Comment by dnfield** [comment]
This failed some platform view tests eventually, got reveted again.

**Comment by flar** [comment]
Sigh. Github re-closing issues when someone forks a repo with an obsolete fix... :(

**Comment by bdero** [comment]
Yeah this keeps happening with my PRs too: I place action keywords in most of my PRs, and wind up needing to forego autosubmit to manually remove action keywords from commit messages copied from the PR. :/

Perhaps we should have the autosubmit bot strip [link lines](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) when copying PR descriptions to commit messages... if there's no way to turn off issue linking for commit messages while keeping it on for PRs.
