### ISSUE TITLE
Infinite and grey widget on some devices

### ISSUE THREAD

**Issue by Asmitta-01** [flutter/flutter#132462]
I have made an application with flutter, the release apk works fine on my phone. I also installed it on my sister's phone and it works fine but on the customer's phone the second page(showing the login form) display an infinite grey widget (keep scrolling and it doesn't finish). The code of this page(view) can be found [here](https://gist.github.com/Asmitta-01/b9df9d8d57ac4b3f260aa3ceb3a96203).

My phone is a Tecno and my sister has an Infinx, the customer has a Redmi.
This is how it looks on our phone: [image1](https://imgbb.com/MGfhNxw), and on the customer's phone: [image2](https://imgbb.com/W6n0X11).

> 5.  Open Flutter DevTools and save a timeline trace of the performance issue
>      so we know which functions might be causing it. See "How to Collect
>      and Read Timeline Traces" on this blog post:
>        https://medium.com/flutter/profiling-flutter-applications-using-the-timeline-a1a434964af3#a499
>      Make sure the performance overlay is turned OFF when recording the
>      trace as that may affect the performance of the profile run.
>      (Pressing ‘P’ on the command line toggles the overlay.)
> 
The bug is on the release apk and i can not ask ts. the customer's phone to work with it or do tests.

Edit: I sent the APK to friends and the render is as same as the customer's view, they have a Xiaomi and a Huawei.

**Target Platform:** Android
**Devices:** Redmi, Xiaomi, Huawei

**Comment by danagbemava-nc** [comment]
Hi @Asmitta-01, you are using a third-party package in your sample code. Please provide a complete minimal sample without any third-party packages so that we can investigate this. 

Also, if you're not using a service like Sentry or Crashlytics, I would advise that you integrate it into your project so that can you track the errors in production. This would help you to discover the source of issues such as this. 

Please also provide the output of `flutter doctor -v`.

Thank you

**Comment by Asmitta-01** [comment]
@danagbemava-nc  Thanks for the reply.

>you are using a third-party package in your sample code. Please provide a complete minimal sample without any third-party packages so that we can investigate this.
I don't understand this please, are you talking about **flutx** ? All my project depends on it, if i remove it the expected behavior might not be the same.
>Please also provide the output of `flutter doctor -v`.
```bash
PS C:\Users\Asmitta\StudioProjects\demo_tdgacademy> flutter doctor -v
[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [version 10.0.19045.3324], locale fr-FR)
    • Flutter version 3.10.6 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (5 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\Asmitta\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.81.1)
    • VS Code at C:\Users\Asmitta\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.70.0

[√] Connected device (3 available)
    • TECNO KG5k (mobile) • 078163722C000563 • android-arm64  • Android 11 (API 30)
    • Windows (desktop)   • windows          • windows-x64    • Microsoft Windows [version 10.0.19045.3324]
    • Edge (web)          • edge             • web-javascript • Microsoft Edge 115.0.1901.203

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

I've installed sentry and i will start debugs, i will have to wait for my friend's responses(since on my phone the app works well).

**Comment by danagbemava-nc** [comment]
> I don't understand this please, are you talking about flutx ? All my project depends on it, if i remove it the expected behavior might not be the same.

We do not expect your minimal sample to be your actual app. So you can try with a smaller code sample on one of the devices that it reproduces on(if you can get your hands on it) then try removing the flutx package to see if you still get the issue. If the issue does not occur without the flutx library, then you may need to report it on their eind. If it does occur then it is a framework issue. 

> I've installed sentry and i will start debugs, i will have to wait for my friend's responses(since on my phone the app works well).

Please keep us updated

**Comment by Asmitta-01** [comment]
I modified my main function to this:
```dart
// main.dart
Future<void> main() async {
  //You will need to initialize AppThemeNotifier class for theme changes.
  WidgetsFlutterBinding.ensureInitialized();

  AppTheme.init();

  await SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);
  await SentryFlutter.init(
    (options) {
      options.dsn =
          'https://*****.ingest.sentry.io/45***';
      // Set tracesSampleRate to 1.0 to capture 100% of transactions for performance monitoring.
      // We recommend adjusting this value in production.
      options.tracesSampleRate = 1.0;
    },
    appRunner: () => runApp(ChangeNotifierProvider<AppNotifier>(
      create: (context) => AppNotifier(),
      child: const MyApp(),
    )),
  );
}
```
And i receive nothing in my sentry issues. So th grey widget is not an error ? Or i missed something during the configuration of sentry?

**Comment by Asmitta-01** [comment]
Update
I launch the app on the web, it is not the destination but i wanted to test it.. And i got a sentry issue:
```
No MaterialLocalizations found.
TextField widgets require MaterialLocalizations to be provided by a Localizations widget ancestor.
The material library uses Localizations to generate messages, labels, and abbreviations.
To introduce a MaterialLocalizations, either use a MaterialApp at the root of your application to include them automatically, or add a Localization widget with a MaterialLocalizations delegate.
The specific widget that could not find a MaterialLocalizations ancestor was:
  TextField
The ancestors of this widget were:
  UnmanagedRestorationScope
  TextFormField
  ...
```
I think i've found the problem, and because of this error the page is similar to the page of my friends(https://ibb.co/rFWR9HS). The stack trace is very long, it is why it seems infinite on mobile (smaller screen).
I'll try to resolve it.

**Comment by Asmitta-01** [comment]
Latest update:  I remove the part of the code including `localizations`. The app is in 'fr', i will read more the [block about it](https://docs.flutter.dev/ui/accessibility-and-localization/internationalization).

Thanks for your availability, and the tip with Sentry,it is very useful)
