### ISSUE TITLE
%5Btool_crash%5D _Exception

### ISSUE THREAD

**Issue by NitinSharmaIkokas** [flutter/flutter#132451]
%23%23 Command%0A%60%60%60%0Aflutter analyze%0A%60%60%60%0A%0A%23%23 Steps to Reproduce%0A1. ...%0A2. ...%0A3. ...%0A%0A%23%23 Logs%0A_Exception%0A%60%60%60%0A%0A%60%60%60%0A%60%60%60%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m Flutter %28Channel stable%2C 3.10.6%2C on macOS 12.6.8 21G725 darwin-x64%2C locale en-IN%29%0A    %1B%5B32m%E2%80%A2%1B%5B39m Flutter version 3.10.6 on channel stable at %2FUsers%2Fikokas%2FDocuments%2Fikokasprojects%2Fsdk%2Fflutter%0A    %1B%5B32m%E2%80%A2%1B%5B39m Upstream repository https%3A%2F%2Fgithub.com%2Fflutter%2Fflutter.git%0A    %1B%5B32m%E2%80%A2%1B%5B39m Framework revision f468f3366c %284 weeks ago%29%2C 2023-07-12 15%3A19%3A05 -0700%0A    %1B%5B32m%E2%80%A2%1B%5B39m Engine revision cdbeda788a%0A    %1B%5B32m%E2%80%A2%1B%5B39m Dart version 3.0.6%0A    %1B%5B32m%E2%80%A2%1B%5B39m DevTools version 2.23.1%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m Android toolchain - develop for Android devices %28Android SDK version 34.0.0-rc3%29%0A    %1B%5B32m%E2%80%A2%1B%5B39m Android SDK at %2FUsers%2Fikokas%2FLibrary%2FAndroid%2Fsdk%0A    %1B%5B32m%E2%80%A2%1B%5B39m Platform android-34%2C build-tools 34.0.0-rc3%0A    %1B%5B32m%E2%80%A2%1B%5B39m Java binary at%3A %2FApplications%2FAndroid Studio.app%2FContents%2Fjbr%2FContents%2FHome%2Fbin%2Fjava%0A    %1B%5B32m%E2%80%A2%1B%5B39m Java version OpenJDK Runtime Environment %28build 17.0.6%2B0-17.0.6b829.9-10027231%29%0A    %1B%5B32m%E2%80%A2%1B%5B39m All Android licenses accepted.%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m Xcode - develop for iOS and macOS %28Xcode 14.2%29%0A    %1B%5B32m%E2%80%A2%1B%5B39m Xcode at %2FApplications%2FXcode.app%2FContents%2FDeveloper%0A    %1B%5B32m%E2%80%A2%1B%5B39m Build 14C18%0A    %1B%5B32m%E2%80%A2%1B%5B39m CocoaPods version 1.12.1%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m Chrome - develop for the web%0A    %1B%5B32m%E2%80%A2%1B%5B39m Chrome at %2FApplications%2FGoogle Chrome.app%2FContents%2FMacOS%2FGoogle Chrome%0A%0A%1B%5B32m%5B%E2%9C%93%5D%1B%5B39m Android Studio %28version 2022.3%29%0A    %1B%5B32m%E2%80%A2%1B%5B39m Android Studio at %2FApplications%2FAndroid Studio.app%2FContents%0A    %1B%5B32m%E2%80%A2%1B%5B39m Flutter plugin can be installed from%3A%0A      %F

**Comment by huycozy** [comment]
Hi @NitinSharmaIkokas 
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly (See bug report template [here](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml))

Closing this issue. Once you updated the issue with more information, please write in the comments and I will re-open this for further discussion.
