### ISSUE TITLE
defaultRowDecoration parameter of RenderTable is unused

### ISSUE THREAD

**Issue by a14n** [flutter/flutter#13249]
https://github.com/flutter/flutter/blob/b61cbc735e2c50b8c44169e823ba114080e61573/packages/flutter/lib/src/rendering/table.dart#L366

Should it be removed or should the class be updated to use it ?

**Comment by Hixie** [comment]
In principle we should use it, but we can remove it in the meantime.

**Comment by goderbauer** [comment]
Looks like this got removed.
