### ISSUE TITLE
OpenCV for Dart

### ISSUE THREAD

**Issue by SpirikleOfficial** [flutter/flutter#132484]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

OpenCV is vital for image/video processing, computer vision research, real-time applications, and machine learning integration. Its open-source nature, cross-platform compatibility, and extensive tools empower developers and researchers, driving innovations in robotics, healthcare, AR/VR, and more. However, as Flutter and Dart are also great tools, their absence for any integration with OpenCV has greatly inhibited their impact in said areas.

### Proposal

Having Dart code has it's benefits, like calling isolates, which can become cumbersome if one went for the native approach. For parallel processing one cannot expect to run native code in isolates (as native itself reverts back to main thread), due to which OpenCV integrations have not been fruitful. 
Creating an OpenCV library in Dart is crucial to bridge the gap in computer vision capabilities for Dart developers. By enabling OpenCV functionalities directly in Dart, developers can efficiently process images and videos, conduct research, and integrate machine learning.
Hoping for Flutter team to support my proposal.

**Comment by darshankawar** [comment]
@SpirikleOfficial 
Have you already looked in [pub.dev](https://pub.dev/) to check if there's community package that offers the feature ? 
See https://pub.dev/packages/opencv_4 and check if it serves your purpose or not.

Also, since this feature request seems to be related to Dart itself, so correct repo to file an issue for it is https://github.com/dart-lang/sdk/issues

Closing from here.

**Comment by SpirikleOfficial** [comment]
> @SpirikleOfficial 
> Have you already looked in [pub.dev](https://pub.dev/) to check if there's community package that offers the feature ? 
> See https://pub.dev/packages/opencv_4 and check if it serves your purpose or not.
> 
> Also, since this feature request seems to be related to Dart itself, so correct repo to file an issue for it is https://github.com/dart-lang/sdk/issues
> 
> Closing from here.
> 

I thought flutter team could make a first party package for OpenCV. OpenCV is widely used by developers and If I thought that flutter would have support for this, so it could be many developers. That's why I asked for this.
