### ISSUE TITLE
Progress bar on video doesn't seem to be material styled

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#13245]
The progress bar on the video player doesn't seem to match familiar styling from the Material spec or the YouTube player.

An example of a linear progress bar: https://material.io/guidelines/components/progress-activity.html#progress-activity-types-of-indicators

The youtube progress bar has a thinner line, a dot that disappears, and a gray line to indicate buffering. The dot is red, like the line, and the dot is bigger than the line. The dot disappears after the view resumes playing.

**Comment by sethladd** [comment]
cc @mit-mit @sigurdm

**Comment by sigurdm** [comment]
The progress bar is now material styled (using a LinearProgressIndicator) and we have community-contributed https://pub.dartlang.org/packages/chewie for extra goodness!
