### ISSUE TITLE
API documentation doesn't explain what a "floating cursor" is

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#132411]
There are many places in our API docs that refer to the "floating cursor". For example:

* `FloatingCursorDragState`
* `RenderEditable.floatingCursorAddedMargin`
* `RawFloatingCursorPoint`
* `RenderEditable.setFloatingCursor`
* `TextInputClient.updateFloatingCursor`
* `EditableText.backgroundCursorColor`

For developers who are not familiar with iOS (and maybe even for many who are), it is not at all clear what a "floating cursor" is.

We should pick one of these places to define in detail (with assets-for-api-docs-generated screenshots) what a "floating cursor" is, and then have all the places that mention it point to that place in the docs for an explanation.

**Comment by goderbauer** [comment]
cc @justinmc @Renzo-Olivares

**Comment by justinmc** [comment]
I'm back from leave and attempting to get final review for my PR that will close this (https://github.com/flutter/flutter/pull/133002).
