### ISSUE TITLE
upgrade single devicelab mac-45 host to macOS 13.5

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#132410]
@kentnguyen99 please upgrade devicelab host https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-45 to latest macOS version, which I believe should be macOS 13.5.

**Comment by yusuf-goog** [comment]
@kentnguyen99 please quarantine the bot manually before performing the upgrade.

**Comment by yusuf-goog** [comment]
\cc @vashworth

**Comment by kentnguyen99** [comment]
Upgrading Mac OS v13.5 on machine mac-45 has been completed.

flutter-devicelab-mac-45:~ swarming$ sw_vers
ProductName:		macOS
ProductVersion:		13.5
BuildVersion:		22G74
