### ISSUE TITLE
`[video_player]` web support

### ISSUE THREAD

**Issue by fishsticks89** [flutter/flutter#132443]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I get an `XFile` video from the `camera` package and I'd like to show it to my user before they upload it. Right now the only way is to turn it into a regular `File`, which you cannot do on the web.

### Proposal

A `VideoPlayerController.xFile` function

**Comment by maRci002** [comment]
Try this:

```dart
import 'dart:io';

import 'package:cross_file/cross_file.dart';
import 'package:video_player/video_player.dart';

final XFile pickedVideo = ...;
final VideoPlayerController controller;

if (kIsWeb) {
  controller = VideoPlayerController.networkUrl(Uri.parse(pickedVideo.path));
} else {
  controller = VideoPlayerController.file(File(pickedVideo.path));
}
```

**Comment by fishsticks89** [comment]
It works! 
It doesn't work for me on safari though

**Comment by fishsticks89** [comment]
[I think this answers the question](https://github.com/flutter/flutter/issues/119336)
