### ISSUE TITLE
[iOS] First day of week from MaterialLocalizations does not take region settings into account

### ISSUE THREAD

**Issue by navaronbracke** [flutter/flutter#132438]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. `flutter create locale_region_bug`
2. Replace `main.dart` with the code sample and add `flutter_localizations` as a dependency for the delegates
3. `open -a Simulator`
4. In the Simulator, set the language to `English (US)` and the region to some region that uses a different value for the `First Day Of The Week`
5. `flutter run` the app on the Simulator

Side note: While creating a code sample, I also noticed that the documentation for `MaterialApp/CupertinoApp.supportedLocales` is missing a `be` in the phrase `This list must not null. Its default value is just [const Locale('en', 'US')].`

### Expected results

The `first day of the week` is taken from the Region information (as seen in the Simulator settings, and in the Calendar app)

### Actual results

The `first day of the week` is taken from the language and not from the region settings. 

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Locale Region Sample',
      theme: ThemeData(
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
      localizationsDelegates: const <LocalizationsDelegate<dynamic>>[
        GlobalMaterialLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      supportedLocales: const [Locale('en', 'US'), Locale('nl', 'BE')],
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    final MaterialLocalizations localizations = MaterialLocalizations.of(context);

    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Text(localizations.narrowWeekdays[localizations.firstDayOfWeekIndex]),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

Region settings in the Simulator 
![Simulator Screenshot - iPhone 14 Pro - 2023-08-12 at 14 31 50](https://github.com/flutter/flutter/assets/23480364/b1d954d3-92a5-4137-bc65-71177cf3b343)

Actual `first day of week` in the application 
![Simulator Screenshot - iPhone 14 Pro - 2023-08-12 at 14 31 59](https://github.com/flutter/flutter/assets/23480364/4c825be3-fda3-4ce7-bf16-c2dfa085a499)

</details>

### Logs

<details><summary>Logs</summary>

```console
N/A
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.2.1 22D68 darwin-x64, locale
    en-BE)
    • Flutter version 3.10.6 on channel stable at
      /Users/navaronbracke/Documents/flutter
    • Upstream repository git@github.com:navaronbracke/flutter.git
    • FLUTTER_GIT_URL = git@github.com:navaronbracke/flutter.git
    • Framework revision f468f3366c (4 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/navaronbracke/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/navaronbracke/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • 221E1600-48E8-4744-8BDA-23CC9920211D • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • macOS 13.2.1 22D68 darwin-x64
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 115.0.5790.170

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by navaronbracke** [comment]
I think that the actual problem here is a bit bigger than just the first day of the week. The entire region settings should be kept separate from the locale.

**Comment by huycozy** [comment]
Thanks for filing the issue, @navaronbracke 
But this issue doesn't seem to be iOS specific (platform) issue but a framework issue. I see there's an open issue addressing the case you described https://github.com/flutter/flutter/issues/122274.

Closing this issue as a duplicate, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
