### ISSUE TITLE
Framework crashes on Android only 

### ISSUE THREAD

**Issue by rehamalraee24** [flutter/flutter#132552]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Hello Everyone,
I could not find clear steps, these crashes are shown only for android 
<img width="1273" alt="image" src="https://github.com/flutter/flutter/assets/91408637/2d2bddcb-0b1f-4e33-8ae2-f5376c1b7822">
are 

### Expected results

I expected them to do not appear since they are not on IOS

### Actual results

Android crashes by Flutter are being increased 

### Code sample

<details><summary>Code sample</summary>

```dart
////
```

</details>

### Screenshots or Video

<details>
<img width="1273" alt="image" src="https://github.com/flutter/flutter/assets/91408637/d6bba50d-8557-4f9c-ad1b-1d64787e8863">

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.1, on macOS 13.3.1 22E261 darwin-x64, locale en-JO)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by dam-ease** [comment]
Hi @rehamalraee24. Thanks for filing this. Can we get more information about this? More specifically:

- Can we get the full crash logs??
- Does this happen when you run the app locally? If yes, can you upgrade to a newer version to confirm issue still persists?
- Are there specific devices in which crash occurs?

Also, this might be similar to https://github.com/flutter/flutter/issues/83596.
