### ISSUE TITLE
Automate some of the redundant processes

### ISSUE THREAD

**Issue by windmillcode0** [flutter/flutter#132568]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Save developer times updating const and shortens application code by a factor of how many class instances need disposing in a stateful widget

### Proposal

So there are plenty of prefer const constructors,  and const for immutable properties, since the devtools know when a value should be const, cant we have a tool  that takes action and autolintfixes your whole app?

In addition I see for controllers we always have to init and dispose of them can we make an optional widget where it uses recursive and other DSA techiniques to dispose of every item that is supposed to be disposed of, mabye passes a list of flutter widget classes and the algorithims goes and collects all of the instances and disposes of it

**Comment by darshankawar** [comment]
Thanks for the report @windmillcode0 
I think this proposal probably belongs to dart-lang repo, so you may need to file it in https://github.com/Dart-Code/Dart-Code/issues or https://github.com/dart-lang/sdk/issues

Also, have you already looked at `dart fix` command and check if it helps to resolve your use case ?  https://dart.dev/tools/dart-fix

Something like `flutter channel master && flutter upgrade && dart fix --apply` you can check and see if it helps or not.

Closing from here, as the proposal doesn't seem to belong in flutter repo. If you disagree, write in comments and I'll reopen it.

**Comment by windmillcode0** [comment]
What about applying the facade pattern for covering up abstractions of classes such as controllers, is redundant to class class.dispose on every controller, also to
