### ISSUE TITLE
Grant dart-internal-sdk write access to cipd flutter/dart-sdk

### ISSUE THREAD

**Issue by sortie** [flutter/flutter#132565]
I'm changing the service account uploading the https://chrome-infra-packages.appspot.com/p/flutter/dart-sdk packages. Can you grant `dart-internal-sdk@dart-ci-internal.iam.gserviceaccount.com` write access to the flutter/dart-sdk cipd prefix?

**Comment by godofredoc** [comment]
This requires adding the service account to `project-flutter-cipd-writers` in the luci configs
