### ISSUE TITLE
Recipes bundler failing consistently

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#132521]
The recipes bundler is failing consistently because of:

```
failed                                      {"error":"bug: refs/heads/fuchsia_* doesn't resolve to a valid CIPD ref name"}
```

Links to failing builds:

https://luci-milo.appspot.com/ui/p/flutter/builders/prod/recipes-bundler

**Comment by sealesj** [comment]
Looking into this

**Comment by sealesj** [comment]
As Casey mentioned over chat, it seems like the regex here https://source.chromium.org/chromium/infra/infra/+/main:go/src/go.chromium.org/luci/cipd/common/common.go;l=45;bpv=1 is failing when `fuchsia_*` is passed

**Comment by sealesj** [comment]
Reaching out to LUCI team for help

**Comment by sealesj** [comment]
It looks like there is a mixed-case issue which is not supported by the regex. There exists both `refs/heads/fuchsia_R53` and `refs/heads/fuchsia_r53`, so the uppercase branch will be deleted which should resolve this issue
