### ISSUE TITLE
Provide a convenient canonical network image in listview preload mechanism

### ISSUE THREAD

**Issue by xster** [flutter/flutter#13258]
Items with network images in a ListView or GridView is a super common app pattern that should be easy to look good. Make it easy to have pre-loaded images scroll in.

**Comment by goderbauer** [comment]
We recently added `cacheExtent` [1], which should work great for this use case. I am tentatively closing this. Please feel free to reopen or file a new issue if this is not sufficient.

[1] https://master-docs.flutter.io/flutter/widgets/ScrollView/cacheExtent.html
