### ISSUE TITLE
Recipes formating message from tricium is incorrect

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#132537]
https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/tricium/tricium.py

```
File not formatted properly.
Run the following to format:
fx format-code --files=recipe_modules/os_utils/api.py
```

Flutter is using fuchsia's tricium_analyze recipe modules to analyze CLs. We should update the message to use `yapf` instead.

**Comment by godofredoc** [comment]
Fixed with https://flutter-review.googlesource.com/c/recipes/+/50240
