### ISSUE TITLE
Regressions in hot reload time

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#132574]
On the commit here https://github.com/flutter/flutter/commit/a2e2574941982e3de3eb746f0a00ca90f6d28f04, SkiaPerf is reporting 10-20% regressions in hot reload time:

https://flutter-flutter-perf.skia.org/e/?begin=1691700785&end=1691719955&keys=X2a4a30b97ed341e63b68ee9907a57f2a&num_commits=50&request_type=1&xbaroffset=36249

Was this benchmark accidentally using the optimization that was removed?

cc @Hixie @jonahwilliams

**Comment by Hixie** [comment]
Woah, that's unexpected. I thought that code was dead. Maybe my removal introduced a bug?

**Comment by Hixie** [comment]
Let's revert that PR and see if it brings it back.

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/pull/132578 is the revert PR; I'm in meetings all day but please feel free to land if you see the tests go green and so on.

**Comment by jonahwilliams** [comment]
If this was only enabled in master channel then removing is still the correct decision. While the feature benchmarked well, analytics based studies showed it performing the same or worse. So really, this is re-aligning our benchmarks with reality.

**Comment by Hixie** [comment]
Roger. I've closed the revert. Let's rebaseline with the new values.
