### ISSUE TITLE
[Engine] Audit `clang_tidy --enable-check-profile` and see what is expensive

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#132687]
See https://github.com/flutter/engine/pull/44773.

**Comment by matanlurey** [comment]
Fwiw locally it took 90 minutes, even without profiling enabled, to lint all files.

**Comment by matanlurey** [comment]
@zanderso https://discourse.llvm.org/t/rfc-exclude-issues-from-system-headers-as-early-as-posible/68483, https://www.reddit.com/r/cpp_questions/comments/10jx0uc/clang_tidy_is_very_slow_when_using_headers_like/ is almost certainly the problem (early results I'm looking at mirror the problems in this RFC) - basically every "lint" checks 100s of files (system headers) indirectly. This becomes obvious with the use of `--enable-check-profile`.

For example, [`clip_rect_layer.cc`](https://github.com/flutter/engine/blob/main/flow/layers/clip_rect_layer.cc), which appears tiny, takes 95s to analyze, of which 55s is attributed to `performance-unnecessary-value-param`, and still a significant amount to `readability-identifier-naming`. See (my local) results below:

```txt
Results of --enable-check-profile for clang-tidy on /Users/matanl/Developer/engine/src/flutter/flow/layers/clip_rect_layer.cc:
===-------------------------------------------------------------------------===
                          clang-tidy checks profiling
===-------------------------------------------------------------------------===
  Total Execution Time: 95.5014 seconds (144.6501 wall clock)

   ---User Time---   --System Time--   --User+System--   ---Wall Time---  ---Instr---  --- Name ---
  55.4190 ( 75.5%)  10.3086 ( 46.7%)  65.7275 ( 68.8%)  95.1104 ( 65.8%)  398798717324  performance-unnecessary-value-param
   3.5988 (  4.9%)   3.8070 ( 17.3%)   7.4058 (  7.8%)  15.1150 ( 10.4%)  33872960742  google-runtime-int
   4.8368 (  6.6%)   2.4138 ( 10.9%)   7.2506 (  7.6%)  11.0247 (  7.6%)  50217982966  readability-identifier-naming
   2.8535 (  3.9%)   1.8428 (  8.4%)   4.6963 (  4.9%)   6.7398 (  4.7%)  35174314910  google-upgrade-googletest-case
   2.5471 (  3.5%)   0.7834 (  3.6%)   3.3305 (  3.5%)   5.0725 (  3.5%)  20175681860  bugprone-use-after-move
   0.8434 (  1.1%)   0.5846 (  2.7%)   1.4281 (  1.5%)   2.1370 (  1.5%)  9763324981  bugprone-unchecked-optional-access
   0.7978 (  1.1%)   0.5746 (  2.6%)   1.3724 (  1.4%)   2.0961 (  1.4%)  9267646436  performance-move-const-arg
   0.7379 (  1.0%)   0.5695 (  2.6%)   1.3074 (  1.4%)   1.9333 (  1.3%)  9457750409  google-global-names-in-headers
   0.3576 (  0.5%)   0.3262 (  1.5%)   0.6838 (  0.7%)   1.4836 (  1.0%)  2296854262  google-build-explicit-make-pair
   0.4622 (  0.6%)   0.2441 (  1.1%)   0.7063 (  0.7%)   1.2659 (  0.9%)  3130561220  darwin-dispatch-once-nonstatic
   0.3949 (  0.5%)   0.2410 (  1.1%)   0.6359 (  0.7%)   1.0664 (  0.7%)  3096766672  google-readability-function-size
   0.1776 (  0.2%)   0.1371 (  0.6%)   0.3147 (  0.3%)   0.5139 (  0.4%)  1943640141  google-runtime-operator
   0.1693 (  0.2%)   0.0976 (  0.4%)   0.2669 (  0.3%)   0.4590 (  0.3%)  1189791353  google-explicit-constructor
   0.0666 (  0.1%)   0.0437 (  0.2%)   0.1102 (  0.1%)   0.1935 (  0.1%)  731638446  darwin-avoid-spinlock
   0.0833 (  0.1%)   0.0187 (  0.1%)   0.1020 (  0.1%)   0.1798 (  0.1%)  508913701  google-readability-braces-around-statements
   0.0534 (  0.1%)   0.0308 (  0.1%)   0.0841 (  0.1%)   0.1484 (  0.1%)  435034115  google-readability-namespace-comments
   0.0433 (  0.1%)   0.0333 (  0.2%)   0.0765 (  0.1%)   0.1083 (  0.1%)  519433560  modernize-use-default-member-init
   0.0013 (  0.0%)   0.0009 (  0.0%)   0.0022 (  0.0%)   0.0025 (  0.0%)   12347382  google-build-namespaces
  73.4436 (100.0%)  22.0578 (100.0%)  95.5014 (100.0%)  144.6501 (100.0%)  580593360480  Total

3389 warnings generated.
Suppressed 3398 warnings (3389 in non-user code, 9 NOLINT).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
```

I'm not sure if we're already only [linting changed files](https://github.com/CleverRaven/Cataclysm-DDA/blob/81adbbdeed7ee4df64f2f0b4aacafad376a2ef8a/.github/workflows/clang-tidy.yml#L85-L102), but that might be an easy one to start with - and then look into disabling or parallelizing particularly expensive checks.

**Comment by zanderso** [comment]
@gaaclarke it looks like `performance-unnecessary-value-param` added in https://github.com/flutter/engine/pull/36221 is up to more than half of the clang-tidy time, at least for that one file. What is your sense for how well that check is pulling its weight? Did we book any perf gains on fixing the lints?

**Comment by matanlurey** [comment]
I ran `--enable-check-profile` (i.e. with `--lint-all`): [clang_tidy_enable_check_profile_lint_all.txt](https://github.com/flutter/flutter/files/12364774/clang_tidy_3.txt).

`performance-unnecessary-value-param` is the long-tail on nearly every invocation, nothing else really stands out. Maybe there is a way to improve it (I couldn't personally find anything), or we could move that check specifically to a parallel build (I don't know if we have the concept of a post-submit-only check, but that's another candidate).

**Comment by chinmaygarde** [comment]
Triage: There is some consensus that `performance-unnecessary-value-param` is generally the most important the check performed by clang-tidy and provide a different .clang-tidy file the pre-push hook that doesn't have this check.

**Comment by matanlurey** [comment]
I am happy to take this action.
