### ISSUE TITLE
devicelab: add pixel7 to linux-37..46

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#132670]

**Comment by yusuf-goog** [comment]
cc @zanderso

**Comment by yusuf-goog** [comment]
@kentnguyen99 I have ordered USB A to C cables for the new devices.

**Comment by kentnguyen99** [comment]
Setup and connecting 10 Pixel 7 phones onto Linux machine hostname=linux-37..46 have been completed. All phones are online and running.
