### ISSUE TITLE
Failed assertion: line 5334 pos 14: '_dependents.isEmpty': is not true

### ISSUE THREAD

**Issue by saga009** [flutter/flutter#132637]
Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
I don't know how to fix this issu please help me

**Comment by dam-ease** [comment]
Hi @saga009. Kindly provide more details on how to reproduce this.
More specifically, please provide the information indicated below:

- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of flutter doctor -v
- Reproduction steps

Thank you!
