### ISSUE TITLE
Flutter (Channel beta, 3.13.0-0.4.pre) hangs when backgrounding app and locking phone, then coming back.

### ISSUE THREAD

**Issue by notandyvee** [flutter/flutter#132666]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Whenever I go a few screens into my app, background the app, lock the device, and come back, there is a high chance the app hangs.

Unfortunately I cannot reproduce on a sample app. So some part of this might be my app or a library. But I provide a screenshot below.

It should also be noted I tested 3.10. Doesn't happen there. So it was a change between 3.10 and 3.13 beta.

### Expected results

No hang.

### Actual results

The app hangs. No error. Nothing I can actionably do at the moment.

### Code sample

<details><summary>Code sample</summary>

N/A

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

<img width="421" alt="Screenshot 2023-08-16 at 12 46 01 PM" src="https://github.com/flutter/flutter/assets/1571223/cc6fa08c-aed9-48dd-89e9-1fe759cbc7eb">

When running the app on xcode, I can pause to see the threads. The problem is a lot of it is machine codes. It's hard to decipher anything.

</details>

### Logs

<details><summary>Logs</summary>

No logs, which is the problem. Just a hang.

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 3.13.0-0.4.pre, on macOS 13.4.1 22F770820d darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
    Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.81.1)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @notandyvee 
In order to properly address the issue, we would need some kind of reproducible code that we can use and to make the issue  actionable. If the code involves any plugins or packages or any assets, you may create a repo and share the link here so that we can clone it and try to replicate. 

Also, since stable is also now 3.13, can you try to run your scenario on it and check if the behavior still persists or not ?

**Comment by notandyvee** [comment]
I would love to give you some reproducible steps. The issue is it hangs and gives me no errors. It will take a while to walk through my app and find the issue. I've honestly been extremely disappointed with the support here. This is the second time I've had to stop focusing on my business to figure out performance issues (on the framework side). And now a bug that literally doesn't produce any errors will require a significant amount of the little time I already have to help you... help me.

**Comment by darshankawar** [comment]
Thanks for the feedback @notandyvee 


> Things appear to work fine in 13.10. I will confirm this. But if this is the case, something on flutter engine has changed.

There must have been lot of updates going from 3.10 to 3.13, so it'll be tough to pinpoint / identify which change might be affecting the behavior you are seeing. Hence, a reproducible code sample or a repo would be extremely help to analyze this issue better.



> The issue is it hangs and gives me no errors.

Can you try to run in verbose mode (ex: flutter run -v) and see if it gives any meaningful log or error that might be helpful for us ?

> Whenever I go a few screens into my app, background the app, lock the device, and come back, there is a high chance the app hangs.

Can you provide what device and OS version are you seeing this behavior on ? Are you seeing the hang in debug mode or in profile / release mode ? 
Does the app contain and render heavy images while navigating ? Or if you could elaborate on what kind of widgets or features are in the app (bare minimum) that would possibly help us to debug further.

**Comment by notandyvee** [comment]
> Can you try to run in verbose mode (ex: flutter run -v) and see if it gives any meaningful log or error that might be helpful for us ?

Yes. I ran it with `--verbose`. No error. In debug mode it hangs. In release mode I believe iOS crashes as it hangs for too long. The screenshot I provide shows what I mean. The main thread is stuck.

> Can you provide what device and OS version are you seeing this behavior on 

iPhone 14 Pro Max. iOS 16.6.

> Does the app contain and render heavy images while navigating ? Or if you could elaborate on what kind of widgets or features are in the app (bare minimum) that would possibly help us to debug further.

I don't want to waste too much of your time as I understand it's improbable to fix a bug you cannot reproduce. I understand that. I'm just expressing my frustration.

But to directly answer your question. On iOS I use the cupertino scaffold. I believe this is where the issue is. I just don't understand why. No heavy images. Just `ChangeNotifier`s and firebase (firestore) streams. I'm making assumptions here. I'll try to find the cause in the next few weeks if I can. So leave the waiting for customer response label.

**Comment by notandyvee** [comment]
Great news. I was able to drill down the exact issue. And then create a reproducible sample. Attaching the `main.dart` file below. I'll outline exactly how to reproduce as it's not 100%. But it mirrors the issue I am experiencing in a minimal example.

The sample is using Cupertino widgets. It's not the exact issue. But pointing it out if it matters. I didn't test Android yet. But I imagine if it's actually an issue with a core widget, it will fix it in Material as well.

The actual issue seems to come from using `CustomScrollView`, a `SliverList`, and in my case, 2 `SliverToBoxAdapter`s. For some reason the key is having that on a second screen you navigate too. I don't understand why. I can consistently reproduce on a second screen.

### Pre-req

* iPhone 14 Pro Max (**Physical device**)
* iOS 16.6
* Flutter 3.13 stable.

### Steps

1. Load the app
2. Click the button to "Open new screen".
3. When on the second screen background the app and lock the device.
4. Wait 5-10 seconds. Or longer.
5. Unlock the device and go back to the app and attempt to scroll.
6. If it doesn't hang, try steps 3-5 again. Eventually it will happen.

A caveat is reproducing isn't 100%. I find installing the app in release allows you to reproduce it better. You don't necessarily have to sleep the device. Going background and back into the app will also work. Just takes longer I think. Attaching a video of me doing it. I built it in release and in the end it crashes. No error FYI. It simply hangs.

In practice while dogfooding my app with testflight the app just fails all the time. I'll background it and when opening my device I get the dialog that my app crashed. It happened extremely frequently and as far as I can tell, on that screen. This bug prevents me from updating to 3.13. Which is required to solve the jank introduced on iOS 16.6.



[main.dart.zip](https://github.com/flutter/flutter/files/12386452/main.dart.zip)


https://github.com/flutter/flutter/assets/1571223/64378485-3283-4990-82e1-71af39f3c4e9

**Comment by notandyvee** [comment]
Just noticed you are no longer assigned @darshankawar . See my comment above with everything you will hopefully need to reproduce.

**Comment by luckysmg** [comment]
@jonahwilliams here is engine stack.

<img src="https://github.com/flutter/flutter/assets/49340347/4f963992-4842-4e3d-a554-94c3048ec760" width= 700/>

**Comment by notandyvee** [comment]
> Scrolling/Slivers are part of the framework and not a part of the engine. If you have any native stack traces we'll be happy to take a look of course

@jonahwilliams believe me, if the framework spit out any error I would gladly give it. Which is where the frustration is. 

But maybe I am misunderstanding. Did I submit the issue on the wrong repo? Either way I submitted a simple example that's clearly pointing to a bug on the framework/engine. And may I add, makes apps essentially unusable. Any help to drill down the exact cause and get the fix to the right team would be greatly appreciated.

**Comment by jonahwilliams** [comment]
> @jonahwilliams here is engine stack（Tested on engine main branch）.
> 
> <img alt="" width="700/" src="https://user-images.githubusercontent.com/49340347/261827854-4f963992-4842-4e3d-a554-94c3048ec760.jpg">

``

What is the actual error there? Is it something about cmd buffer execution or is it just an abort?

**Comment by luckysmg** [comment]
> 
> 
> 
> 
> > @jonahwilliams here is engine stack（Tested on engine main branch）.
> 
> > 
> 
> > <img alt="" width="700/" src="https://user-images.githubusercontent.com/49340347/261827854-4f963992-4842-4e3d-a554-94c3048ec760.jpg">
> 
> 
> 
> ``
> 
> 
> 
> What is the actual error there? Is it something about cmd buffer execution or is it just an abort?

Seems like dead lock...The app freeze...

**Comment by johannesvuorinen** [comment]
We have similar problem with Flutter 3.13 in iOS (everything was working fine with 3.10). I noticed that when the hanging happens AppLifecycleState "paused" has not been fired when going to background (only the "inactive" state is fired). Then, when going back to foreground, everything is stuck and eventually the app autocloses itself.

**Comment by stuartmorgan** [comment]
> What is the actual error there?

It looks like the platform thread is stuck on an engine lock, which will cause the watchdog to kill the app.

**Comment by jonahwilliams** [comment]
The thread 1 block on the sync switch? If so that means we're blocking trying to tell the renderer that we're about to go to the background. Maybe something else is holding onto the sync switch lock incorrectly.

**Comment by stuartmorgan** [comment]
> Maybe something else is holding onto the sync switch lock incorrectly.

That's my guess from the stack as well (assuming this is a steady-state trace, not a breakpoint, which is what it sounded like; @luckysmg please let us know if I'm incorrect on that).

**Comment by jonahwilliams** [comment]
@luckysmg if you've got any easy repro, could try out https://github.com/flutter/engine/pull/44885 ?

**Comment by luckysmg** [comment]
@jonahwilliams  I tried the patch on that PR, and it seems works. ^_^

**Comment by luckysmg** [comment]
> if you've got any easy repro

%100 repro on my iPhone13Pro iOS16.6.
Scroll a ListView ,  and switch to app to background without waiting the scrolling animation stop, and back, will repro this. If current app has no animation, and switch to background and back, it seems ok.

**Comment by jonahwilliams** [comment]
Excellent! I will get started on the hotfix tomorrow.

**Comment by chinmaygarde** [comment]
This has been fixed and https://github.com/flutter/flutter/issues/132982 was added to the CP queue just now.

**Comment by DFelten** [comment]
Thanks for the fix! Is the fix also part of the new Flutter version 3.13.1 or did it not make it? At least the changelog doesn't look like it.

**Comment by David-Mou** [comment]
> does it fixed in 3.13.1 stable?

No. You can see the release notes of each patch version [here](https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel)

**Comment by jonahwilliams** [comment]
Yes it is: https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel#3131-august-23-2023

**Comment by escamoteur** [comment]
awesome, we just ran into this too, hope the fix will solve it for our users
