### ISSUE TITLE
[infra] Skia Gold is frequently flaky

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#132656]
Filing this issue to consolidate all the individual issues auto-filed by the flake detection bot that are caused by this one Skia Gold issue.

We frequently get intermittent test failures with errors that look like this:

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: one widget whose rasterized image matches golden image "material.border_paint_above.png"
  Actual: _KeyFinder:<exactly one widget with key [#103dd] (ignoring offstage widgets):
RepaintBoundary-[#103dd](renderObject: RenderRepaintBoundary#be5c3 relayoutBoundary=up1)>
   Which: SkiaException: Skia Gold received an unapproved image in post-submit
          testing. Golden file images in flutter/flutter are triaged
          in pre-submit during code review for the given PR.

          Visit https://flutter-gold.skia.org/ to view and approve
          the image(s), or revert the associated change. For more
          information, visit the wiki:
          https://github.com/flutter/flutter/wiki/Writing-a-golden-file-test-for-package:flutter

          Debug information for Gold --------------------------------
          stdout:
          stderr: Error running command: ''computing grouping for test
"material.material.border_paint_above": grouping params for corpus "flutter" are unknown; known
grouping params: map[]. At goldclient.go:418 goldclient.go:320 goldclient.go:280 cmd_imgtest.go:363
cmd_imgtest.go:294 command.go:860 command.go:974 command.go:902 command.go:895 main.go:54
proc.go:250 asm_amd64.s:1598''


          result-state.json: No result file found.

When the exception was thrown, this was the stack:
../dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49  throw_
../packages/matcher/src/expect/prints_matcher.dart.js 434:22                     fail
../packages/matcher/src/expect/prints_matcher.dart.js 411:18                     <fn>
../packages/stack_trace/src/stack_zone_specification.dart.js 185:98              <fn>
../packages/stack_trace/src/stack_zone_specification.dart.js 237:16              [_run]
../packages/stack_trace/src/stack_zone_specification.dart.js 185:80              <fn>
../dart-sdk/lib/async/zone.dart 1407:47                                          _rootRunUnary
../dart-sdk/lib/async/zone.dart 1308:19                                          runUnary
../dart-sdk/lib/async/future_impl.dart 159:18                                    handleValue
../dart-sdk/lib/async/future_impl.dart 843:44                                    handleValueCallback
../dart-sdk/lib/async/future_impl.dart 872:13                                    _propagateToListeners
../dart-sdk/lib/async/future_impl.dart 644:5                                     [_completeWithValue]
../dart-sdk/lib/async/future_impl.dart 718:7                                     callback
../dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
../dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
../dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:15           <fn>

The test description was:
  border is painted above child by default
════════════════════════════════════════════════════════════════════════════════════════════════════
```

Opening https://flutter-gold.skia.org/ shows "No untriaged digests for corpus flutter".

Sample build logs:

- https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_tests_0/12222/overview
- https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_tests_0/12221/overview
- https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_tests_1/12219/overview

I'm not sure what to do about these. They go away on their own, but they trigger the bot to file P0s, which is also why I made this issue a P0 too.

**Comment by godofredoc** [comment]
@keyonghan do you know why the bugs are opened as P0

@Piinks can you please help us triage the issue?

**Comment by Piinks** [comment]
FWIW I don't think all of the flakes reported on the web shards last week are attributed to Gold. I was the gardener last week, and many of them were timeouts instead of Gold issues.

As far as the groupings issue with Gold, that is being tracked in https://g-issues.skia.org/issues/40045532 cc @kjlubick

**Comment by yjbanov** [comment]
The timeout issue is tracked in https://github.com/flutter/flutter/issues/132654. It looks unrelated to this issue.

**Comment by yjbanov** [comment]
This happened again today: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_canvaskit_tests_3/10032/overview.

Since the flaky bot files issues under P0 ([example](https://github.com/flutter/flutter/issues/133650)), I'm raising this to P0 too. It doesn't make sense to dedupe P0 issues into P2. That artificially reduces the priority.

**Comment by godofredoc** [comment]
Who should be the assignee for this?

**Comment by kjlubick** [comment]
> This was reported again today: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_canvaskit_tests_3/10032/overview.
> 

Are we sure that was a problem with the gold server? I don't see `goldctl` show up in the logs of that at all

**Comment by keyonghan** [comment]
Redirecting back to web for the commented question.

**Comment by yjbanov** [comment]
@Piinks can comment on how error messages propagate from `goldctl` to the test, but here's the message that points at Skia Gold:

```
Skia Gold received an unapproved image in post-submit
          testing. Golden file images in flutter/flutter are triaged
          in pre-submit during code review for the given PR.

          Visit https://flutter-gold.skia.org/ to view and approve
          the image(s), or revert the associated change. For more
          information, visit the wiki:
          https://github.com/flutter/flutter/wiki/Writing-a-golden-file-test-for-package:flutter

          Debug information for Gold --------------------------------
          stdout: Given image with hash a5e59a594e5e49b1a9c938ecd08704d5 for test
widgets.inconsequential_golden_file
          Untriaged or negative image:
https://flutter-gold.skia.org/detail?grouping=name%3Dwidgets.inconsequential_golden_file%26source_type%3Dflutter&digest=a5e59a594e5e49b1a9c938ecd08704d5
          stderr: Test: widgets.inconsequential_golden_file FAIL
          result-state.json: No result file found.
```

Importantly, if you follow the [triage link](https://flutter-gold.skia.org/detail?grouping=name%3Dwidgets.inconsequential_golden_file%26source_type%3Dflutter&digest=a5e59a594e5e49b1a9c938ecd08704d5) you will find that the image was triaged by @Piinks 94 weeks ago:

<img width="191" alt="Screenshot 2023-08-31 at 1 43 54 PM" src="https://github.com/flutter/flutter/assets/211513/5ddc3caa-df22-492e-b161-c6e07d164d48">

So I'm not sure why the image was rejected.

**Comment by Piinks** [comment]
@yjbanov that error message does not match the error message from the OP. This looks like a separate issue, or may be a case of it working as intended. Looks like one version of that test image changed recently:

https://flutter-gold.skia.org/search?corpus=flutter&include_ignored=false&left_filter=name%3Dwidgets.inconsequential_golden_file&max_rgba=0&min_rgba=0&negative=true&not_at_head=false&positive=true&reference_image_required=false&right_filter=&sort=descending&untriaged=true

**Comment by yjbanov** [comment]
Ah, it is a different error message indeed! Would you prefer a separate issue?

As for the image changing, the images listed at the link you posted are 151w, 6w, and 94w old. But the Skia Gold failure is from Aug 28 (which is 4 days ago as of this writing), so I would still expect it to pass. But more specifically, the error message points to golden a5e59a594e5e49b1a9c938ecd08704d5, which is triaged as positive 94w ago, and it's seemingly the only image that the CanvasKit renderer ever produced.

**Comment by yjbanov** [comment]
From a Discord discussion: there was a temporary outage due to backend issues in August that roughly coincided with this spike of Gold errors. While we don't have proof, it's reasonable assume that the outage was the culprit. So I'm closing this. I might reopen if the flaky bot start filing new issues that look identical to this one.
