### ISSUE TITLE
Web tests flaky due to Chromium process failing to shutdown

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#132654]
Consolidating all issues auto-filed by the flake detector into this one. As of this writing, this issue is mostly tracking https://github.com/dart-lang/test/issues/1104 as the suspected culprit.

In short, the issue seems to be that the test runner first "loads" the test, then "runs" the test. However, the timeout clock starts when it loads the test. Since the concurrency level is limited (and because Flutter takes screenshots, has to be set to 1), by the time it's the test's turn to run it's well into the 12-minute timeout limit, so it times out. The fix should be to only start the clock when the test starts running. The correct thing to do would be to count the time between "load" and "run" as zero. More details in the Dart issue.

Relevant Google-internal issue: b/294950828

**Comment by yjbanov** [comment]
Update: [1.24.5](https://pub.dev/packages/test/versions/1.24.5) includes an improvement we should try. This requires a package roll in the flutter/flutter repo. I'll do it when I get the chance, unless someone else beats me to it.

**Comment by yjbanov** [comment]
Update: the Flutter repo has rolled to 1.24.6. Now just waiting for the next repro to see if the error messages improved.

**Comment by yjbanov** [comment]
Here's a fresh repro. I don't see anything new in the logs: https://github.com/flutter/flutter/issues/133130

**Comment by yjbanov** [comment]
No progress yet. I [asked](https://github.com/dart-lang/test/issues/1104#issuecomment-1698234036) if there's any useful data from Forge (internal CI system) that we can piggyback on.

**Comment by yjbanov** [comment]
Some new observations: there are strong signals that Chromium freezes when these flakes happen. So it's not test runtime being misattributed (or it could be both; hard to say). As of right now we're looking for a concrete signal about the browser freezing so the test can be retried (we don't want to always retry as that would allow other source of flakiness to creep in over time).

**Comment by yjbanov** [comment]
No new reports of this kind of timeout have been filed. Interestingly, the reports stopped coming almost simultaneously with the Skia Gold issue (2 weeks ago). I wonder if Chrome was observed to be "stuck" was actually Skia Gold not responding to HTTP requests.

@Piinks At what point does a test talk to Skia Gold? Do we first run all tests and then submit goldens? Or do we talk to Gold and expect a response while tests are running?

**Comment by Piinks** [comment]
> Do we first run all tests and then submit goldens? Or do we talk to Gold and expect a response while tests are running? 

The later. Since tests are sharded out and run in parallel, we have to check with Gold for each one individually.

**Comment by zanderso** [comment]
There was an instance earlier today on the engine tree? Maybe this isn't the same thing? https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Production%20Engine%20Drone/356627/overview

**Comment by zanderso** [comment]
Another from this morning: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Production%20Engine%20Drone/358592/overview

**Comment by yjbanov** [comment]
Thanks, @zanderso! We were just wondering the other day why we don't see this on the engine side, but looks like we do!

**Comment by eyebrowsoffire** [comment]
Actually both of those examples are still framework unit tests, and they are using the framework's unit test harness. We do have a CI step that runs the framework tests in presubmit on engine PRs. So the observation still stands: the web engine unit test harness doesn't see these timeouts.

**Comment by yjbanov** [comment]
Ah, I missed that. Good catch!

**Comment by yjbanov** [comment]
Just deduped 2 more reports of flakiness due to timeouts.

**Comment by yjbanov** [comment]
@eyebrowsoffire helped me spot another pattern. It looks like we're starting a new instance of Chrome for each `_test.dart` file. Notice that every successful test starts with "Using Chromium" printed immediately after the first "loading" message, e.g.:

```
06:01 +658 ~14: loading /b/s/w/ir/x/w/flutter/packages/flutter/test/widgets/overscroll_indicator_test.dart                                                                                             [+5569 ms] Serving tests at http://localhost:36575/static/index.html?managerUrl=ws%3A%2F%2Flocalhost%3A36575%2F48&debug=false
[  +35 ms] Using Chromium 115.0.5790.0 

[ +113 ms] [CHROME]: 
[        ] [CHROME]: DevTools listening on ws://127.0.0.1:36715/devtools/browser/06050489-9738-4ce6-a888-3fa54a53c90c
```

However, I just clicked through 10 random timeouts, and in each one of them the failing test never prints "Using Chromium" and simply prints the "loading" message repeatedly, e.g.:

```
06:09 +674 ~14: loading /b/s/w/ir/x/w/flutter/packages/flutter/test/rendering/debug_test.dart                                                                                                          
06:10 +674 ~14: loading /b/s/w/ir/x/w/flutter/packages/flutter/test/rendering/debug_test.dart                                                                                                          
06:11 +674 ~14: loading /b/s/w/ir/x/w/flutter/packages/flutter/test/rendering/debug_test.dart                                                                                                          
06:12 +674 ~14: loading /b/s/w/ir/x/w/flutter/packages/flutter/test/rendering/debug_test.dart                                                                                                          
06:13 +674 ~14: loading /b/s/w/ir/x/w/flutter/packages/flutter/test/rendering/debug_test.dart                                                                                                          
06:14 +674 ~14: loading /b/s/w/ir/x/w/flutter/packages/flutter/test/rendering/debug_test.dart                                                                                                          
06:15 +674 ~14: loading /b/s/w/ir/x/w/flutter/packages/flutter/test/rendering/debug_test.dart                                                                                                          
06:16 +674 ~14: loading /b/s/w/ir/x/w/flutter/packages/flutter/test/rendering/debug_test.dart
```

The "Using Chromium" message is printed by [this line](https://github.com/flutter/flutter/blob/65693955343d710a03f52f0ee5c9fceb69bc7ea5/packages/flutter_tools/lib/src/web/chrome.dart#L179) in the code. If I'm reading this correctly, then we're getting stuck at the `chrome --version` command.

I'm going to add more output to Chrome launcher in `--verbose` mode.

**Comment by yjbanov** [comment]
The new logging code has landed, and here's a new piece of info from a recent flake:

```
07:48 +1367 ~210: loading /b/s/w/ir/x/w/flutter/packages/flutter/test/widgets/inherited_model_test.dart                                                                                                [+3213 ms] Serving tests at http://localhost:42693/static/index.html?managerUrl=ws%3A%2F%2Flocalhost%3A42693%2F57&debug=false
[        ] Launching Chromium (url = http://localhost:42693/static/index.html?managerUrl=ws%3A%2F%2Flocalhost%3A42693%2F57&debug=false, headless = true, skipCheck = false, debugPort = null)
[        ] Will use Chromium executable at /b/s/w/ir/cache/chrome/chrome/chrome
[  +39 ms] Using Chromium 117.0.5938.0 

[ +106 ms] [CHROME]: 
[        ] [CHROME]: DevTools listening on ws://127.0.0.1:38939/devtools/browser/debaa994-28c7-4881-8cb0-a23345b6f873

07:49 +1367 ~210: loading /b/s/w/ir/x/w/flutter/packages/flutter/test/widgets/inherited_model_test.dart
07:50 +1367 ~210: loading /b/s/w/ir/x/w/flutter/packages/flutter/test/widgets/inherited_model_test.dart
07:50 +1367 ~210: test/widgets/inherited_model_test.dart: InheritedModel basics
07:51 +1367 ~210: test/widgets/inherited_model_test.dart: InheritedModel basics
07:51 +1368 ~210: test/widgets/inherited_model_test.dart: InheritedModel basics
07:51 +1368 ~210: test/widgets/inherited_model_test.dart: Looking up an non existent InheritedModel ancestor returns null
07:51 +1369 ~210: test/widgets/inherited_model_test.dart: Looking up an non existent InheritedModel ancestor returns null
07:51 +1369 ~210: test/widgets/inherited_model_test.dart: Inner InheritedModel shadows the outer one
07:52 +1369 ~210: test/widgets/inherited_model_test.dart: Inner InheritedModel shadows the outer one
07:52 +1370 ~210: test/widgets/inherited_model_test.dart: Inner InheritedModel shadows the outer one
07:52 +1370 ~210: test/widgets/inherited_model_test.dart: InheritedModel inner models supported aspect change
07:52 +1371 ~210: test/widgets/inherited_model_test.dart: InheritedModel inner models supported aspect change
07:52 +1371 ~210: loading /b/s/w/ir/x/w/flutter/packages/flutter/test/cupertino/scrollbar_paint_test.dart
07:53 +1371 ~210: loading /b/s/w/ir/x/w/flutter/packages/flutter/test/cupertino/scrollbar_paint_test.dart
07:54 +1371 ~210: loading /b/s/w/ir/x/w/flutter/packages/flutter/test/cupertino/scrollbar_paint_test.dart
...
19:52 +1371 ~210 -1: loading /b/s/w/ir/x/w/flutter/packages/flutter/test/cupertino/scrollbar_paint_test.dart [E]
  TimeoutException after 0:12:00.000000: Test timed out after 12 minutes.
```

([source](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8769309700718622289/+/u/run_test.dart_for_web_tests_shard_and_subshard_1/test_stdout))

When `scrollbar_paint_test.dart` starts loading we never print the "Launching Chromium" message. It's as if we're not even trying to launch the browser. My current hypothesis is that we are blocking on trying to acquire the `_suiteLock`.

**Comment by yjbanov** [comment]
Found the issue! 🤞 

The culprit is on this line:

https://github.com/flutter/flutter/blob/80fb7bd2060132af51b7191d808b9fbbd6e3ab7c/packages/flutter_tools/lib/src/web/chrome.dart#L490

`_process.kill()` sends a `SIGTERM`, which is a soft request for the process to shut down. Once every few tens of thousand times, the Chromium process refuses to exit, which blocks the following line in the test harness:

https://github.com/flutter/flutter/blob/80fb7bd2060132af51b7191d808b9fbbd6e3ab7c/packages/flutter_tools/lib/src/test/flutter_web_platform.dart#L462

That line executes after the test reported back to `package:test` that it has finished running, which causes the test runner to being loading the next test. However, the `lockResource` is only released after a successful shutdown of the browser. Since the browser is not shutting down the lock is never released. This means the next test is stuck waiting for the lock here:

https://github.com/flutter/flutter/blob/80fb7bd2060132af51b7191d808b9fbbd6e3ab7c/packages/flutter_tools/lib/src/test/flutter_web_platform.dart#L444

Since at this point the test runner already started the clock for the next test, it complains that the latter timed out. However, in reality it's the previous test failing to clean up after itself (failing to shutdown Chromium).

I'm going to try the following solution:

* Send `SIGTERM` and wait up to 5 seconds, if the process exited, great! Return from the function.
* If the process has not exited, then send a `SIGKILL`, which is a much firmer way to exit a process. Same as before, wait up to 5 seconds, if the process exited, great! Return from the function.
* If it still hasn't exited then give up trying to exit Chromium, just print a warning to the console and return from the function.

Since we cannot make any guarantees about Chromium (like any other external piece of code), it's probably reasonable to go for a "best effort" approach.

**Comment by yjbanov** [comment]
Confirmed the strategy works. Here's an example of SIGTERM failing, falling back to SIGKILL, unblocking the next test:

```
[+5000 ms] Failed to exit Chromium (pid: 117964) using SIGTERM. Will try sending SIGKILL instead.
02:13 +242 ~22: loading /b/s/w/ir/x/w/flutter/packages/flutter/test/semantics/custom_semantics_action_test.dart                                                                                        [  +22 ms] Test suite test/widgets/gesture_detector_test.dart finished.
[        ] Serving tests at http://localhost:42197/static/index.html?managerUrl=ws%3A%2F%2Flocalhost%3A42197%2F20&debug=false
[        ] Launching Chromium (url = http://localhost:42197/static/index.html?managerUrl=ws%3A%2F%2Flocalhost%3A42197%2F20&debug=false, headless = true, skipCheck = false, debugPort = null)
[        ] Will use Chromium executable at /b/s/w/ir/cache/chrome/chrome/chrome
[  +50 ms] Using Chromium 117.0.5938.0 

[ +119 ms] [CHROME]: 
[        ] [CHROME]: DevTools listening on ws://127.0.0.1:46003/devtools/browser/27167a0b-6780-418e-9c5d-6edc760f0db6
[ +162 ms] Running test suite test/semantics/custom_semantics_action_test.dart.

02:14 +242 ~22: loading /b/s/w/ir/x/w/flutter/packages/flutter/test/semantics/custom_semantics_action_test.dart
```

I'll prepare a PR with the fix.
