### ISSUE TITLE
Text selection does not work

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#13263]
Text selection on Flutter apps installed on ChromeOS does not work with mouse or with keyboard. The ctrl + shift modifiers do nothing and the mouse pointer does not switch to caret indicator when hovering over a text field.

**Comment by mehmetf** [comment]
@eseidel 

Let's set appropriate milestone for this so we can deliver it by August 15, 2018. This is a hard deadline. If we don't meet this, Flutter apps published in Google will be banned on tablets (not just Chromebooks).

**Comment by tvolkert** [comment]
Closing this as a dup of https://github.com/flutter/flutter/issues/15758 and https://github.com/flutter/flutter/issues/15754 (broken out between mouse and physical keyboard)
