### ISSUE TITLE
Scrolling causes the next mouse down event to be long press

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#13262]
After scrolling is done, putting my finger on the touchpad registers as a long press. The inkwell is activated but it does not actually drill into the item.

This also triggers odd behavior on TabBar. If I scroll horizontally, I can "activate" each tab and leave it in active mode.

![image](https://user-images.githubusercontent.com/6687929/33414948-98655a00-d548-11e7-829c-c1c90e2dc4d5.png)

**Comment by mehmetf** [comment]
@eseidel  Let's set appropriate milestone for this so we can deliver it by August 15, 2018.

**Comment by gedw99** [comment]
Any chance that this can be fixed earlier ? I am using flutter for a medical app and it's an easy fix but very jarring for users.

**Comment by jslavitz** [comment]
@mehmetf Do you have test code that reproduces this issue? Doesn't seem like it's the case in the flutter gallery as far as I can tell.

**Comment by mehmetf** [comment]
It is possible that this has been fixed since then. If you can't reproduce it, then feel free to close. This should be easy to reproduce. Just scroll with the touchpad of the chromebook and click any button or tab.

**Comment by zoechi** [comment]
Sounds like this issue can be closed.
