### ISSUE TITLE
Flutter web Stream is null while creating bytestream

### ISSUE THREAD

**Issue by UnStunned** [flutter/flutter#132632]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Select a file using file picker package in flutter web.
2. Since path is not supported on web, send bytes to the upload document API.
3. The upload document API allows customization of headers, body, data. 
4. The upload document API calls the function that makes a multipart request to the server with supplied paramaters.
5. Data consists of Bytes / Native UInt8List, a multipart request is made by adding a multipart file in the body. MultipartFile.fromBytes is called. 
6. fromBytes method internally creates a stream from bytes. 
7. This stream should be non null. However, I am getting a null stream probably because Stream.fromBytes is defined in dart:io which is not supported in flutter web. 
8. Since stream is null, the request does not send the file. It results in a bad request and is rejected by the server.

### Expected results

Non empty Stream

### Actual results

Null Stream

### Code sample

```
Future<dynamic> postNew2(
      File? file, Uint8List? bytes, String path, Map<String, dynamic>? body,
      [Map<String, String>? headers = defaultHeaders]) async {
    var request = http.MultipartRequest(
        "POST",
        Uri.parse(URL);

    if (kIsWeb) {
      request.files.add(MultipartFile.fromBytes('document', bytes!));
    } else {
      request.files.add(
          http.MultipartFile.fromBytes('document', file!.readAsBytesSync()));
    }

    request.headers.addAll(headers!);

    await request.send().then((response) async {
      print(response.statusCode);
      print(await response.stream.bytesToString());
      if (response.statusCode == 200 || response.statusCode == 201) {
        print("Uploaded!");
      }
    });
```

### Screenshots or Video

![44fe5a0d-b82f-434c-b7f5-a779f1a42787](https://github.com/flutter/flutter/assets/62642722/db622fbc-2b3c-4bf8-8c66-a27fe94cfc8e)

![0a7a9f76-4ffb-4dc6-974c-d238026d3a16](https://github.com/flutter/flutter/assets/62642722/9cc51b0f-a9ec-42e4-9abb-f2b43387bf8d)

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.10.4, on Microsoft Windows [Version 10.0.19045.3208], locale en-IN)
    • Flutter version 3.10.4 on channel stable at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 682aa387cf (2 months ago), 2023-06-05 18:04:56 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

 

[√] Windows Version (Installed version of Windows is version 10 or higher)


[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\sumukh.kulkarni\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: D:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

 

[√] Chrome - develop for the web
    • Chrome at C:\Users\sumukh.kulkarni\AppData\Local\Google\Chrome\Application\chrome.exe


[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.6.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33815.320
    • Windows 10 SDK version 10.0.22000.0


[√] Android Studio (version 2021.2)
    • Android Studio at D:\Android\Android Studio
    • Flutter plugin can be installed from:
https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)


[√] VS Code (version 1.80.0)
    • VS Code at C:\Users\sumukh.kulkarni\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.69.20230703


[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.3208]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 115.0.5790.171
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 114.0.1823.82


[!] Network resources
    X A network error occurred while checking "[https://cocoapods.org/":](https://cocoapods.org/%22:) The semaphore timeout period has expired.


    X A network error occurred while checking "[https://github.com/":](https://github.com/%22:) The semaphore timeout period has expired.
```

</details>

**Comment by dam-ease** [comment]
Hi @UnStunned. Thanks for filing this. Please can you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code?
Thank you

**Comment by UnStunned** [comment]
@dam-ease Thank you for the prompt response, I have edited extra information off the issue. There are no third party plugins or complex production code. Please look into the matter.

**Comment by dam-ease** [comment]
Hi @UnStunned. Thanks for your response. The attached code isn't a minimal complete reproducible code sample and I seem to not fully understand this issue. Can you provide more information on this? More specifically:

- Does this issue after making the API call?
- Is it with the `Uint8List? bytes` you are passing to the API call? If yes, can you share a code sample of how you obtain this?
- Also, you can click the link, [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), to get an idea of what a minimal complete reproducible code sample is and share one

Thank you!
