### ISSUE TITLE
Some webps do not work

### ISSUE THREAD

**Issue by Gi-lo** [flutter/flutter#132645]
### Steps to reproduce

1. Create an Image widget.
2. Assign [this](https://img.how.fm/v1?url=https%3A%2F%2Fstorage.googleapis.com%2Fhow-fm-production-eu.appspot.com%2Facademy.martin%2Fcapture-202381017291mp4_c8db766a-94ee-4c30-b87e-7b612466edd0.mp4.webp%3FGoogleAccessId%3Dhow-fm-production-eu%2540appspot.gserviceaccount.com%26Expires%3D32535129600%26Signature%3DXDqsk3SPOUGR25JkphPypLIXCfUF92AnpuXtC9WNPT9DaezQ2vVV87ytTAFEnNgK5C4MGxv%252BHrqGR1EtIDvDm%252FiIePoGBfHpFqKqBU6V5ZI%252B0YR7BAL9wThGF0f%252BXHErbpXcsXlG686rHQDA0DWFkckpy9RP0D1%252FipaEXWBdj5E6DuYqQrHzA%252BNvwOLnhtER%252FkEJoB%252Bv0SiagIwDni9sPg6MshzXO5DZvYiNXE9u2JrBDpmlr1Kr%252BArEaO9AyIRw1CAXbk2wOuuPd7c5d2%252FbxEDbvR9%252FDkhG7JGm2T6hUZiV8LClNlk18HPxcgWO4TK9vRuGuEyOg3TW3arE%252FeInnA%253D%253D&n=-1&w=600&h=600&output=webp&il) `webp` to be displayed.

### Expected results

I see the `webp` in the App.

### Actual results

I don't see the `webp` and an error is logged.

**NOTES:**

* Chrome/Firefox/Safari are able to show the `webp`.
* A Flutter App on iOS, Android, Simulator and Emulator can not show the `webp`.
* `webpinfo` states no error detected for the given `webp`.

### Code sample

<details><summary>Code</summary>

`Image.network("https://rb.gy/frpmj");`

</details>

### Logs

<details><summary>Logs</summary>

```console
E/flutter ( 4403): [ERROR:flutter/lib/ui/painting/multi_frame_codec.cc(130)] Could not getPixels for frame 1

══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following _Exception was thrown resolving an image frame:
Exception: Codec failed to produce an image, possibly due to invalid image data.

When the exception was thrown, this was the stack
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.0, on macOS 12.2 21D49 darwin-arm64 (Rosetta), locale de-DE)
    • Flutter version 3.7.0 on channel stable at /Users/gilo/fvm/versions/3.0.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (7 months ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/gilo/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/gilo/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/gilo/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_265-b01)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 12A7403
    ✗ Flutter requires Xcode 13 or higher.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.12.1

[!] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[!] Android Studio
    • Android Studio at /Users/gilo/Library/Android/sdk/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Android Studio not found at /Users/gilo/Library/Android/sdk/Contents
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (1 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64 • Android 14 (API 34) (emulator)

[✓] HTTP Host Availability
    • All required HTTP hosts are available```

</details>

**Comment by Gi-lo** [comment]
@darshankawar I am pretty sure I did test it it but will verify tmr and let you know. As far as I understood the issues you linked only refer to iOS Simulator Builds. My problem exists on any mobile device.

**Comment by Gi-lo** [comment]
@darshankawar 

I tried it on:
> [✓] Flutter (Channel master, 3.14.0-6.0.pre.27, on macOS 12.2 21D49 darwin-arm64, locale de-DE)

I get the same error just without any stack trace attached.
> E/flutter ( 4261): [ERROR:flutter/lib/ui/painting/multi_frame_codec.cc(110)] Could not getPixels for frame 1

**Comment by darshankawar** [comment]
Thanks for the update @Gi-lo 
I was also able to replicate the reported behavior on mobile platform (android emulator, iOS simulator and device) along with on desktop in which it throws below error:

```
E/flutter ( 6603): [ERROR:flutter/lib/ui/painting/multi_frame_codec.cc(110)] Could not getPixels for frame 2

======== Exception caught by image resource service ================================================
The following _Exception was thrown resolving an image frame:
Exception: Could not getPixels for frame 2

When the exception was thrown, this was the stack: 
Image provider: AssetImage(bundle: null, name: "assets/test.webp")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#a4171(), name: "assets/test.webp", scale: 1.0)
====================================================================================================
```
And

`2023-08-18 11:28:18.872357+0530 Runner[5575:387261] [VERBOSE-2:multi_frame_codec.cc(110)] Could not getPixels for frame 1`

However, on web, it loads the image properly as below:

<img width="354" alt="Screenshot 2023-08-18 at 11 19 24 AM" src="https://github.com/flutter/flutter/assets/67046386/eb09336e-12d1-4649-b089-b0e99ea4416d">

<details>
<summary> runnable code sample </summary>

```

import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    var title = 'Web Images';

    return MaterialApp(
      title: title,
      home: Scaffold(
        appBar: AppBar(
          title: Text(title),
        ),
        body: Image.asset("assets/image.webp"),
      ),
    );
  }
}

```

</details>

Wherein, the webp images were used as mentioned in this issue's original description as well as in original issue's [description](https://github.com/flutter/flutter/issues/85831#issue-936228026).


I will go ahead and update https://github.com/flutter/flutter/issues/85831 to reflect that the issue only doesn't occur on desktop but no mobile platforms as well. I suggest you to follow-up in that issue for further updates and will close this in favor of the linked issue. If you disagree, write in comments and I'll reopen it.
