### ISSUE TITLE
Simple repro case for iOS 16.6 regression

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#132683]
For reporting https://github.com/flutter/flutter/issues/131319 to Apple as a parallel track to getting our own fix out, we need a reduced test case. This could be a minimal Flutter app, but if we can point to an existing, published third-party app, with specific repro steps for it, that might be easier since it would require much less Flutter-specific setup for someone to reproduce.

**Comment by stuartmorgan** [comment]
@luckysmg I noticed you added a customer label to that issue; do you have simple repro steps using a published application by any chance?

**Comment by luckysmg** [comment]
Our published app xianyu（闲鱼）has fixed this by setting `CAMetalLayer.presentsWithTransacation = YES` in our flutter engine to avoid this junk on iOS16.6, also, we need to force `UIView` and `CALayer` 's `layout` method on main thread to avoid this [crash](https://github.com/flutter/flutter/issues/131319#issuecomment-1668825204)

I don't know how to download old version of xianyu on app store....If you can download old version of xianyu, maybe `7.11.80` or `7.11.70` version,  plz follow this steps:

1. Open the app, enter the home page, you will see a waterfall view in home page with goods items.
2. Click any goods item to enter the detail page(this page is flutter) 
3. Scroll the page, you will see lag and junk on iOS16.6 **(Also you need to use a high refresh rate device like iPhone13Pro or iPhone14Pro)**

**Comment by zanderso** [comment]
@stuartmorgan I believe that @chinmaygarde saw this issue with a couple of the published 3p apps he had installed on his phone. Instead of calling them out publicly, maybe you can ask him the names of those apps over chat.

**Comment by zanderso** [comment]
I believe we also repro'd the issue with the Wonderous app, but @chinmaygarde and @dnfield should confirm.

**Comment by dnfield** [comment]
Yes, one screen on Wonderous in particular reproduced this well.

I think Chinmay's goal here though is to write a more barebones Metal app that shows this regression.

**Comment by chinmaygarde** [comment]
[go/flutter-ios-16.6-retrospective](http://go/flutter-ios-16.6-retrospective) contains some more examples but that is yet to be publicly available. You'll have to download the videos locally and view them in QuickTime to tell the really bad jank. Its a 120 Hz screen captured in slo-mo and displayed using drive that does all sorts tricks to display it smoothly on a 60Hz screen.

The screen where the jank is most apparently in Wondrous (other than the apps we know about on the store) is this one:

<img width="502" alt="Screenshot 2023-08-22 at 1 12 42 PM" src="https://github.com/flutter/flutter/assets/44085/06203260-477c-4dbb-a919-a44ca7bbe8bc">

Zach, Jonah, and I were able to reproduce it on the iPhone 14 (non-pro) but not the high refresh rate iPads.

**Comment by stuartmorgan** [comment]
> [go/flutter-ios-16.6-retrospective](http://go/flutter-ios-16.6-retrospective) contains some more examples but that is yet to be publicly available. You'll have to download the videos locally and view them in QuickTime to tell the really bad jank.

The video is an "actual results"; could you turn the steps used to create that video into something suitable to be pasted into the "steps to reproduce" section of a bug report? The purpose here is to file a report with Apple, which means we need clear repro steps that someone who is not a Flutter engineer can follow.

**Comment by chinmaygarde** [comment]
Right. I was responding to:

> If someone can send me detailed instructions to reproduce **with Wonderous** I can start by filing with that,

I'll take a stab at creating a reduced test case but we don't fully understand the behavior yet. So it might take a while.

**Comment by stuartmorgan** [comment]
I'm not talking about a reduced test case at this point, I'm asking for steps to reproduce what is shown in that video. I.e.,

1. Download Wonderous from insert-link-here
2. Launch the app
3. Tap on ???
4. Scroll?

I'm looking for detailed steps that an engineer at Apple could follow to see the difference themselves in different OS versions, and, e.g., run under OS tracing on their end to see what's happening.

**Comment by jonahwilliams** [comment]
We ultimately worked around the issue by switching from CAMEtalLayer to our own layer type written by @knopp
