### ISSUE TITLE
Add a warning dialogue box when you are merging a PR and all checks haven't passed

### ISSUE THREAD

**Issue by johnmccutchan** [flutter/flutter#132602]
It is possible to submit a PR while checks are running (or have already failed). Would be a nicer experience to warn the developer before breaking the tree.

**Comment by godofredoc** [comment]
I'm afraid this is not feasible as this is the github ui and we don't have control over it.

In the chat thread it was mentioned that github has support for blocking merges based on predefined checks. Even when this functionality exists is not scalable for the flutter use case as it will require one of the 3 org admins to manually update branch protection rules when new tests are added or old ones are removed.

The proposal here is to use the autosubmit label the provides the feedback required as comments.

**Comment by ricardoamador** [comment]
Closing this issue as this will not be delivered. The solution would be to enforce autosubmit bot and remove the ability to merge manually. 
@godofredoc fyi
