### ISSUE TITLE
Create `dart.flutterSdkPathFromEnVar` and `dart.sdkPathFromEnVar` settings

### ISSUE THREAD

**Issue by manuel-plavsic** [flutter/flutter#132668]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

## Nix/NixOS and flutter

Currently, Flutter support is a bit weak on Nix/NixOS land.

I can get Flutter to build and run, targeting both Linux and Android. However, the Flutter/Dart extension/language server picks a wrong Flutter SDK path and also a wrong Dart SDK path. This make it impossible to use the GUI of VSCode; instead, I can only use the integrated terminal.

What is weird, is that the following environment variables are available after entering `nix develop`:
-  `$PATH`
  `/nix/store/j1q06cyrmmlwr3kkbqlwd06z03zchh8b-patchelf-0.15.0/bin /nix/store/ygi2qf01dyx5015lqlqshrdh9gqijkxa-gcc-wrapper-12.3.0/bin /nix/store/yxpdhv0vv17gkg0xxsliimals3ldvbq3-gcc-12.3.0/bin /nix/store/zz9xg4dp3miyv5w6ss9a1ww622rf73hf-glibc-2.37-8-bin/bin /nix/store/8fdd0nqajq5sk1m6p4qnn0z0j9d7n3q5-coreutils-9.3/bin /nix/store/h43yhgahcwif4vnlz3909wpchg1k8zml-binutils-wrapper-2.40/bin /nix/store/fm1xq4f3g48k1mmwl6qg9jc3ipgfsk1x-binutils-2.40/bin /nix/store/rxbqb5y3ia3kpq9apcky47mlbxz16hrq-bash-interactive-5.2-p15/bin /nix/store/rjgiliqa5a9bv2xqx6nri2frd02nyx6n-androidsdk/bin /nix/store/0f087v5zrnvj4ickd01qpxlk47a81jpw-flutter-wrapped-sdk-links/bin /nix/store/fapf7lyx2ni8yysf6sjk6cy2rkwy7yjl-gradle-8.2.1/bin /nix/store/jrqnp10937px3llfwpagmklrivjhk0r8-openjdk-11.0.19+7/bin /nix/store/hq4wcmxsvz3jhn6hglxbm5fd96p8wnqg-sqlite-3.42.0-bin/bin /nix/store/8fdd0nqajq5sk1m6p4qnn0z0j9d7n3q5-coreutils-9.3/bin /nix/store/jids6qqs36p4ds9ghpkcw57kbhp8lbq2-findutils-4.9.0/bin /nix/store/q0gfc489hnjjg52p7aggbb6q18kfwd20-diffutils-3.10/bin /nix/store/zl7fpambb4db6by8mhl9xcmr6n1pp98c-gnused-4.9/bin /nix/store/2hz0i9y0xck9y4pq1rabi0cwk4kylgrw-gnugrep-3.11/bin /nix/store/3mpa96b8hi3gfx17099xwgfnp6kbz4ga-gawk-5.2.2/bin /nix/store/lwncj07g77z30hb8g3s3vkr3pcs52p1r-gnutar-1.35/bin /nix/store/zz9xsi57f49vcxy7ndq5gqkazdd1h5q4-gzip-1.12/bin /nix/store/rmq1rwjfgl1vm1v7v9axzr6n3jh8kjvn-bzip2-1.0.8-bin/bin /nix/store/28p2r7a9nnzl24w3yhbakz69i0sl24wl-gnumake-4.4.1/bin /nix/store/ir0j7zqlw9dc49grmwplppc7gh0s40yf-bash-5.2-p15/bin /nix/store/5jnldfvr9p9hh7m4fky7359m9m8yqsb4-patch-2.7.6/bin /nix/store/75rkp4a0dh6qnad033l1q75sv51awydd-xz-5.4.3-bin/bin /nix/store/m2wp56nf47ipyhqw4yicyglijw3mjwp1-file-5.44/bin /nix/store/1vjlw2piyxqwgn630vl8a6bn8ah677gw-glib-2.76.4-bin/bin /run/wrappers/bin /home/username/.nix-profile/bin /etc/profiles/per-user/username/bin /nix/var/nix/profiles/default/bin /run/current-system/sw/bin`
- `$FLUTTER_ROOT` 
  /nix/store/0f087v5zrnvj4ickd01qpxlk47a81jpw-flutter-wrapped-sdk-links
- `$DART_ROOT`
  /nix/store/0f087v5zrnvj4ickd01qpxlk47a81jpw-flutter-wrapped-sdk-links/bin/cache/dart-sdk

## Problem

The Dart and Flutter extensions somehow insist on choosing the `/nix/store/8gcy7hn3f8qi01zaiaf2q2a5md9k47h8-flutter-3.10.5-unwrapped` SDK over the other one in `$FLUTTER_ROOT`. The only way I could force the SDK was to apply the following to my `settings.json`:

```json
    "dart.flutterSdkPath": "/nix/store/0f087v5zrnvj4ickd01qpxlk47a81jpw-flutter-wrapped-sdk-links",
    "dart.sdkPath": "/nix/store/0f087v5zrnvj4ickd01qpxlk47a81jpw-flutter-wrapped-sdk-links/bin/cache/dart-sdk",
```

To avoid having to keep track of the version, I tried replacing with the following:

```json
    "dart.flutterSdkPath": "${env:FLUTTER_ROOT}",
    "dart.sdkPath": "${env:FLUTTER_ROOT}/bin/cache/dart-sdk",
```

however, environment variables are not supported at the moment.

### Proposal

I propose adding settings `dart.flutterSdkPathFromEnVar` and `dart.sdkPathFromEnVar` which default to `false`. 

If `dart.flutterSdkPathFromEnVar` is set to true, it will try to set the Flutter SDK path to the one defined in `FLUTTER_ROOT`. The Dart SDK path will be set to `${env:FLUTTER_ROOT}/bin/cache/dart-sdk`.

If `dart.sdkPathFromEnVar` is set to true, it will set the Dart SDK path to `DART_ROOT`, independently from the Flutter SDK.

**Comment by christopherfujino** [comment]
@manuel-plavsic this sounds like a feature request on the VSCode extension Dart-Code: https://github.com/Dart-Code/Dart-Code/issues. Is this correct?
