### ISSUE TITLE
Don't run clang_tidy for ~25 minutes if no C/C++ code has been changed

### ISSUE THREAD

**Issue by johnmccutchan** [flutter/flutter#132605]
Some example commits that triggered Clang tidy to run for ~25 minutes:

https://flutter.googlesource.com/mirrors/engine/+/1d63eece6c37aa467b1d4e1e1d564c9e84411417
https://flutter.googlesource.com/mirrors/engine/+/785b24900a360ed872d1f779a65d6c062ce69448

**Comment by godofredoc** [comment]
The current clang tidy always build two variants of the engine: `android_debug_arm64` and `host_debug` and runs https://cs.opensource.google/flutter/engine/+/master:ci/lint.sh?q=ci%2Flint.sh&ss=flutter on the output of the builds using multiple shards. This is the reason they take a similar execution time independently of the files being touched.

If I understand correctly the proposal is to use gn/ninja to detect the impacted targets, run those targets and run clang tidy in their outputs. Is this correct?

**Comment by johnmccutchan** [comment]
My proposal is this:

If no C/C++ code has been changed in a PR than we know that clang-tidy can't find any new lints (as no relevant code was modified) and we shouldn't run it at all.

**Comment by johnmccutchan** [comment]
A concrete example:

If I land a PR that only touches *.md and *.dart files then running clang_tidy is unnecessary.

**Comment by matanlurey** [comment]
Also if I land a PR that only touches `a.cc`, why do I need to lint `b.cc` (unless some of the clang tidy lints are impacted by dependent changes?)

**Comment by godofredoc** [comment]
@johnmccutchan your proposal can be implemented with a run_if in .ci.yaml similar to https://cs.opensource.google/flutter/engine/+/main:.ci.yaml;l=362

**Comment by zanderso** [comment]
https://github.com/flutter/engine/pull/44759 <- Adds runIf to linux_clang_tidy. We have it already on mac_clang_tidy. I'm not sure why the Linux one is missing it.

**Comment by godofredoc** [comment]
Thanks @zanderso, do you remember the reason for not using gn/ninja for test filtering? I remember an old conversation about this, maybe @dnfield remembers some of the details.

**Comment by dnfield** [comment]
I think it's just slow period.

**Comment by matanlurey** [comment]
> I think it's just slow period.

Interesting. Since I'm curious now and working a half day (dentist stuff) I might take a look today and see if anything stands out.

**Comment by zanderso** [comment]
The `runIf` added in https://github.com/flutter/engine/pull/44759, appears not to be working as expected sometimes?

It correctly skipped the clang_tidy checks on https://github.com/flutter/engine/pull/44834.

@matanlurey could you link the instances you saw where it wasn't working correctly?

**Comment by matanlurey** [comment]
> @matanlurey could you link the instances you saw where it wasn't working correctly?

I think we were mistaken or looking at older commits - newer commits seem to work as expected, for example:

https://github.com/flutter/engine/pull/44830/checks

**Comment by chinmaygarde** [comment]
I see https://github.com/flutter/engine/pull/44759 which ostensibly fixes this. Please re-open if I'm mistaken.
