### ISSUE TITLE
FirebaseUI Auth packages for flutter

### ISSUE THREAD

**Issue by pranjalcna** [flutter/flutter#132658]
step 5 says "For Android native, iOS native, and Web, there are prebuilt FirebaseUI Auth packages, but you need to build this capability for Flutter.". 

then the lab uses the FirebaseUI auth package.

![image](https://github.com/flutter/flutter/assets/72935229/e0aba5ae-6447-4a1c-99c3-430a19bd026f)

**Comment by huycozy** [comment]
Hi @pranjalcna 
Can you please be more specific on the issue? What is the inaccurate statement and proposal for the correction?

**Comment by pranjalcna** [comment]
Sorry, the flutter package firebase_ui_auth is now available (https://pub.dev/packages/firebase_ui_auth) and the code lab actually uses it (see step 5: https://firebase.google.com/codelabs/firebase-get-to-know-flutter#4). Therefore, the statement "but you need to build this capability for Flutter" at the beginning of step 5 seems incorrect.

It confused me as I am new to this flutter stuff.

**Comment by huycozy** [comment]
Thanks for the response. Maybe it needs to be updated so as not to cause confusion. 

/cc @domesticmouse

**Comment by domesticmouse** [comment]
PTAL @ericwindmill

**Comment by ericwindmill** [comment]
A fix for the text is in flight via CL 572560350, and the source code via https://github.com/flutter/codelabs/pull/1925
