### ISSUE TITLE
Video player demo in Gallery doesn't test for network connectivity

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#13266]
The demo of video being landed in the Gallery (https://github.com/flutter/flutter/pull/13195), plays back videos from the network. If you run it and don't have a networking connection, nothing happens. It would be better if it checked for a connection, and somehow prompted that video requires one such.

**Comment by mit-mit** [comment]
cc @sigurdm

**Comment by mit-mit** [comment]
I think https://pub.dartlang.org/experimental/packages/connectivity can be used for this

**Comment by sethladd** [comment]
Good idea!

**Comment by sigurdm** [comment]
Done in https://github.com/flutter/flutter/pull/13195
