### ISSUE TITLE
Corporate mirrors or hermetic builds

### ISSUE THREAD

**Issue by oravecz** [flutter/flutter#132614]
I’m inside a corporate firewall and trying to package Flutter up in a hermetic bundle for distribution across Linux, MacOS and Windows. I have two ways to accomplish this task.

1. Bypass my network proxy to create a custom package on several different platforms in order to download a Flutter package and run `flutter precache`. Zip it up and distribute, or
2. Use an internal mirror of the servers Flutter uses for all of its install dependencies, and allow the first execution of Flutter to install its dependencies.

I would like to go with the mirror option, and there is a precedent of the China mirror, but I’m not finding any details on how someone else might set up something similar. Is it allowed?

**Comment by jonahwilliams** [comment]
Flutter is a permissively licensed open source library. You can generally do whatever you want with it, download artifacts or store them wherever. Note that the China mirror is not maintained by the Flutter team, and we do not maintain mirrors of the engine artifacts ourselves.

**Comment by oravecz** [comment]
I cannot mirror without cooperation. The file structure of storage.googleapis.com isn’t discoverable, nor is it easily discoverable to determine which files flutter will download upon executing `flutter precache` across all OS/arch options. 

I’m not sure why the issue was closed with such fervor, but I appreciate the timely response. Is there a better channel for this discussion?
