### ISSUE TITLE
follow write protection setup steps on mac-6

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#132700]
On mac-6:
```
% csrutil status
System Integrity Protection status: enabled.
```

we need to make sure that all the mac hosts have this disabled. Please run the steps at: go/flutter-salt#disable-readonly-filesystem

**Comment by yusuf-goog** [comment]
blocking https://github.com/flutter/flutter/issues/132674

**Comment by yusuf-goog** [comment]
@kentnguyen99 running `csrutil status` should confirm when it is correctly disabled.

**Comment by kentnguyen99** [comment]
csrutil has been disabled on mac-6, work is done.
