### ISSUE TITLE
FileSystemEvent error

### ISSUE THREAD

**Issue by asemanTest** [flutter/flutter#132737]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

dart run build_runner build --delete-conflicting-outputs

### Expected results

successfull operation

### Actual results

Building package executable... (7.8s)
Failed to build build_runner:build_runner:
/C:/Users/alireza/AppData/Local/Pub/Cache/hosted/pub.dev/watcher-1.0.2/lib/src/constructable_file_system_event.dart:7:57: Error: The cl
ass 'FileSystemEvent' can't be extended, implemented, or mixed in outside of its library because it's a sealed class.
abstract class _ConstructableFileSystemEvent implements FileSystemEvent {
                                                        ^
Failed to build build_runner:build_runner:
/C:/Users/alireza/AppData/Local/Pub/Cache/hosted/pub.dev/watcher-1.0.2/lib/src/constructable_file_system_event.dart:7:57: Error: The cl
ass 'FileSystemEvent' can't be extended, implemented, or mixed in outside of its library because it's a sealed class.
abstract class _ConstructableFileSystemEvent implements FileSystemEvent {
                                                        ^

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
The file that is throwing the error has been removed from the watcher library. You should probably clean your flutter cache and run flutter pub get again to see if you still face this issue. If you still face this issue, file an issue on the build_runner repo as it is not maintained on this repo. Please also make sure you're using the latest version of flutter(3.13.0). 

Closing from here as this is not a flutter issue. 

Thank you
