### ISSUE TITLE
[tool_crash] FileSystemException: C

### ISSUE THREAD

**Issue by Dakyung2** [flutter/flutter#132771]
Flutter- Errno=1, Cannot create link, path

Hi! would appreciate anyone's help!

The Problem:  I keep facing the same error below-

```
Oops; flutter has exited unexpectedly: "FileSystemException: Cannot create link, path =
'D:\FlutterProjects\projects\trywithkoko_expense2\windows\flutter\ephemeral\.plugin_symlinks\
firebase_core' (OS Error: 잘못된 기능입니다.
, errno = 1)".
A crash report has been written to
D:\FlutterProjects\projects\trywithkoko_expense2\flutter_03.log.
```

Solutions I've tried:
1. checking the plugin_symlink  file:
I checked that the file exists, and it was empty
2. Trying other terminals:
Tried Firebase CLI, and command line. Did not work for both

Additional info
- flutterfire confige had error with Firebase CLI but worked with command line
- I am not using the C: drive for this project

Cannot move on to next step due to this problem. Would appreciate your solutions! Thansk:)

**Comment by darshankawar** [comment]
@Dakyung2 
Can you provide the the log file generated ?

`trywithkoko_expense2\flutter_03.log`
