### ISSUE TITLE
Since updating to Flutter 3.13 I cant build in release or profile for SKSL generation, debug works though.

### ISSUE THREAD

**Issue by cfsbhawkins** [flutter/flutter#132789]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I can launch to a simulator using the play button in Android Studio, but when I try and run profile on a physical device or build a release version gradle hangs up and must be killed off to quit at this command:
```console
[        ] [  +25 ms] /Users/bhawkins/FlutterSDK/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /Users/bhawkins/FlutterSDK/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.snapshot --sdk-root /Users/bhawkins/FlutterSDK/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/
--target=flutter --no-print-incremental-dependencies -DFLUTTER_WEB_AUTO_DETECT=true -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/1ac611c64eadbd93c5f5aba5494b8fc3b35ee952/ -Ddart.vm.profile=true -Ddart.vm.product=false --track-widget-creation --aot --tfa --target-os android --packages
/Users/bhawkins/Flutter Apps/core_flutter/.dart_tool/package_config.json --output-dill /Users/bhawkins/Flutter Apps/core_flutter/.dart_tool/flutter_build/41fa453189e9c13adc6ad3189ce789d4/app.dill --depfile /Users/bhawkins/Flutter
Apps/core_flutter/.dart_tool/flutter_build/41fa453189e9c13adc6ad3189ce789d4/kernel_snapshot.d --source file:///Users/bhawkins/Flutter%20Apps/core_flutter/.dart_tool/flutter_build/dart_plugin_registrant.dart --source package:flutter/src/dart_plugin_registrant.dart
-Dflutter.dart_plugin_registrant=file:///Users/bhawkins/Flutter%20Apps/core_flutter/.dart_tool/flutter_build/dart_plugin_registrant.dart --verbosity=error package:core_flutter/main-prod.dart
```
All these commands worked in 3.10.6 and are now failing on all of our devs computers. I have gone through created a new flutter project, merged in the gradle changes for 3.13 and that did not help either.

### Actual results

Should launch app in profile mode and allow me to generate a SKSL on an android device.

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.13.0, on macOS 13.5 22G74 darwin-x64, locale en-US)
    • Flutter version 3.13.0 on channel stable at /Users/bhawkins/FlutterSDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (2 days ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/bhawkins/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.81.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.5 22G74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.96

[✓] Network resources                
    • All expected network resources are available.

• No issues found!


```

</details>

**Comment by huycozy** [comment]
>merged in the gradle changes for 3.13

Hi @cfsbhawkins, could you please share these changes?

I check this on stable 3.10.3 as well and see it can generate SkSL as expected:

```console
➜  reproduce_issues_2 flutter run --profile --cache-sksl
Launching lib/main.dart on RMX2001 in profile mode...
Running Gradle task 'assembleProfile'...                           57.6s
✓  Built build/app/outputs/flutter-apk/app-profile.apk (32.0MB).
Installing build/app/outputs/flutter-apk/app-profile.apk...         3.3s

Flutter run key commands.
h List all available interactive commands.
c Clear the screen
q Quit (terminate the application on the device).
A Dart VM Service on RMX2001 is available at: http://127.0.0.1:60645/IGKWO-4j0eg=/
I/eproduce_issue(19698): ProcessProfilingInfo new_methods=1424 is saved saved_to_disk=1 resolve_classes_delay=5000
The Flutter DevTools debugger and profiler on RMX2001 is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:60645/IGKWO-4j0eg=/
D/ProfileInstaller(19698): Installing profile for com.example.reproduce_issues

Wrote SkSL data to /Users/huynq/Documents/NEVERCODE.IO/RepoduceProjects/reproduce_issues_2/flutter_02.sksl.json.

```

Could you also share the entire `run command` and `output`? Which Android device (OS, model) are you seeing this issue?

**Comment by cfsbhawkins** [comment]
I will get the diffs together but it didnt work with original gradle files either, but I am seeing this in the android studio messages now and its new. Even before I build just opening the app and the step before it shows is it generating intl files. Wonder if this is what is crashing and causing the production builds to fail.

/Users/bhawkins/FlutterSDK/flutter/bin/flutter --no-color pub global run intl_utils:generate
Failed to build intl_utils:generate:
../../.pub-cache/hosted/pub.dev/watcher-1.0.2/lib/src/constructable_file_system_event.dart:7:57: Error: The class 'FileSystemEvent' can't be extended, implemented, or mixed in outside of its library because it's a sealed class.
abstract class _ConstructableFileSystemEvent implements FileSystemEvent {
                                                        ^
Process finished with exit code 1

**Comment by iamiota** [comment]
> I will get the diffs together but it didnt work with original gradle files either, but I am seeing this in the android studio messages now and its new. Even before I build just opening the app and the step before it shows is it generating intl files. Wonder if this is what is crashing and causing the production builds to fail.
> 
> /Users/bhawkins/FlutterSDK/flutter/bin/flutter --no-color pub global run intl_utils:generate Failed to build intl_utils:generate: ../../.pub-cache/hosted/pub.dev/watcher-1.0.2/lib/src/constructable_file_system_event.dart:7:57: Error: The class 'FileSystemEvent' can't be extended, implemented, or mixed in outside of its library because it's a sealed class. abstract class _ConstructableFileSystemEvent implements FileSystemEvent { ^ Process finished with exit code 1
> 
> Reverting back to 3.10.6 that error goes away. Maybe something in the intl package is causing it to break, I have latest 0.18.1 per my pubspec.lock

I had the same problem after upgrading to `3.10.6`.

**Comment by cfsbhawkins** [comment]
Maybe Android Studio plugin needs to be updated with the latest version?

**Comment by huycozy** [comment]
@cfsbhawkins For your new error, looks like `dart pub upgrade` can solve it, see https://github.com/dart-lang/sdk/issues/52570#issuecomment-1570610278. Please try it. 

Once it's solved and the origin issue still persists, please provide entire output of run commands and the output in verbose as I mentioned above so we have more information to verify this. 

Please also confirm if the issue appears on a newly created project or a specific configuration project as well. If it's on 2nd case, please provide a minimal sample code. Thank you!

**Comment by cfsbhawkins** [comment]
OK I have reverted my Gradle changes back to how they were, that way I can narrow this down to something I know that works in 3.10.6 and not in 3.13.0.  I have attached the verbose output from the flutter run command that does a release mode version of the app. 

I can confirm that both just trying to run the app in release mode and generating a SKSL file will both lock up at the same step and never get past it. It does not install the app or launch it. 

I also tested and I can launch into release mode on iOS so issue appears to be with Android and Gradle.

Please see the attached text file output of running a release mode version of the app, my next step will be to try and upgrade to Gradle 8 / Android SDK 34 (Currently on Gradle 7.6.1 / Android SDK 33)

[prod_output.txt](https://github.com/flutter/flutter/files/12412275/prod_output.txt)

**Comment by cfsbhawkins** [comment]
I will say I just tried the beta channel with 3.14 and it does appear to get further past that command above that it hangs on. It now blows up with an issue with a third party lib as they don't support 3.14 yet. Not sure if that helps at all.

**Comment by huycozy** [comment]
```
[        ] [  +18 ms] /Users/bhawkins/FlutterSDK/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /Users/bhawkins/FlutterSDK/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.snapshot --sdk-root /Users/bhawkins/FlutterSDK/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk_product/ --target=flutter --no-print-incremental-dependencies -DFLUTTER_WEB_AUTO_DETECT=true -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/1ac611c64eadbd93c5f5aba5494b8fc3b35ee952/ -Ddart.vm.profile=false -Ddart.vm.product=true --aot --tfa --target-os android --packages /Users/bhawkins/Flutter Apps/core_flutter/.dart_tool/package_config.json --output-dill /Users/bhawkins/Flutter Apps/core_flutter/.dart_tool/flutter_build/21435e7fe3b50aa0531f90b7aaa998c0/app.dill --depfile /Users/bhawkins/Flutter Apps/core_flutter/.dart_tool/flutter_build/21435e7fe3b50aa0531f90b7aaa998c0/kernel_snapshot.d --source file:///Users/bhawkins/Flutter%20Apps/core_flutter/.dart_tool/flutter_build/dart_plugin_registrant.dart --source package:flutter/src/dart_plugin_registrant.dart -Dflutter.dart_plugin_registrant=file:///Users/bhawkins/Flutter%20Apps/core_flutter/.dart_tool/flutter_build/dart_plugin_registrant.dart --verbosity=error package:core_flutter/main-prod.dart

```

Could you share the entire command you ran? It is hung up on this last line log on the file output above, right?

Checking the given log above, it seems you are having flavor configuration on it, doesn't it? (not sure if this is also related but it could be). I would suggest you narrow down the issue more by minimizing the project until seeing a pattern for this. 

I tried this again on a minimal sample code with targetSdkVersion 33 and 34, along with AGP `8.0.2` and gradle `gradle-8.1.1-all.zip`, it still can write SkSL data well in profile mode with command. I'm on Flutter stable 3.13.0.

```
flutter run --profile --cache-sksl
```

**Comment by cfsbhawkins** [comment]
Yes thats the line it hangs on, since it appears anytime a --release  SKSL or just trying to push a release build onto a device is ran the output came from the following command: 

`flutter run -v --release --flavor prod -t lib/main-prod.dart`

Yes there is a flavor here, we used to have 3 different build pipelines for dev/uat/prod but its been recently reduced to just dev and prod, since app feature "licensing" is now controlled server side and our testers can turn them on now without needing a dev to do it on the backend.

I could probably look at dropping the flavors now, and revert to the kDebugMode where needed.

**Comment by cfsbhawkins** [comment]
I have tried 3.13.1 and dropped flavors still hangs at the same point. One thing I have noticed is that the URL specified here in that command is returning a 404.

-DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/b20183e04096094bcc37d9cde2a4b96f5cc684cf/ 

What is this url? Could this be causing flutter to stop compiling?

**Comment by huycozy** [comment]
>since it appears anytime a --release SKSL

Thanks for your update but I don't think SKSL shaders file can be generated in release mode. Per [How to use SkSL warmup](https://docs.flutter.dev/perf/shader#how-to-use-sksl-warmup), it seems to work in profile mode. I tried with release mode and also see it can not be generated as well.

>push a release build onto a device is ran the output came from the following command:

I also checked this with [flavors](https://github.com/flutter/flutter/tree/master/dev/integration_tests/flavors) project here but it works as expected without hanging the process. The flavor sample is also able to work in profile mode and can generate SkSL normally. 

It looks like flavor is not the cause. Could you retry on a newly created Flutter project?

**Comment by cfsbhawkins** [comment]
Going to kick off another build after work tonight and just let it sit and export all of its logs, but it does appear that it eventually completes and generates a build for release or profiling but were talking 30-45 minutes where it appears hung. I will kick one off that logs everything to a file again to see if we can find out where the slowdown is at.

**Comment by NSLogZfRee** [comment]
same issue  flutter 3.10.0

**Comment by barilki** [comment]
same issue flutter 3.13.2

**Comment by huycozy** [comment]
@NSLogZfRee @barilki Could you please provide a minimal reproduction (sample code, steps) for this?

**Comment by NSLogZfRee** [comment]
> @NSLogZfRee @barilki Could you please provide a minimal reproduction (sample code, steps) for this?

ide: android studio
plugins: Flutter Intl (i10n)
multiple .arb
