### ISSUE TITLE
Tell Flutter tool that Impeller is enabled by default

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#132712]
Flags like `--enable-impeller` can be specified to the tool to selectively enable or disable features. But it is unclear if the tool can tell if that same flag is specified using the applications `Info.plist` or `AndroidManifest.xml` files. Are flag opt-in/out rates accurate?

**Comment by chinmaygarde** [comment]
This was brought up during the Impeller weekly in relation to the confidence in reporting from the tool. This isn't a super high priority action item.

cc @gaaclarke @zanderso

**Comment by matanlurey** [comment]
Do we have a pulse for how often the application flags are used generally?

**Comment by chinmaygarde** [comment]
I think we can tell the usage based on what specified on the command line. But not sure how. @zanderso will know.

**Comment by zanderso** [comment]
Gathered for iOS here: https://github.com/flutter/flutter/pull/135193

Not yet implemented on the Android side.

**Comment by matanlurey** [comment]
I have some time in between larger changes going through review, so I'll take a pass at this.

**Comment by matanlurey** [comment]
@chinmaygarde This is now done. The last and final step, only to be done when we enable the flag by default, is here:

https://github.com/flutter/flutter/blob/a6a8caaa7338daad7fed228847a9a75dc42091fe/packages/flutter_tools/lib/src/project.dart#L885-L886

Assigning to you as a holder.

**Comment by zanderso** [comment]
FYI https://github.com/flutter/engine/pull/54156
