### ISSUE TITLE
[Impeller] Document the logic for determining when Android uses Vulkan and when it falls back to OpenGL ES.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#132716]
Impeller will support both OpenGL ES and Vulkan on Android. The preference will be for Vulkan but there will be a fallback to OpenGL ES on devices that either don't support Vulkan or don't have the necessary extensions to support common plugins.

This issue tracks documenting the logic.

**Comment by chinmaygarde** [comment]
Per @johnmccutchan, Android Vulkan Platform Views will require API >= 29.

**Comment by johnmccutchan** [comment]
I can document this but where should I put it?

**Comment by chinmaygarde** [comment]
We can just put these in the `//flutter/impeller/docs` folder I suppose.
