### ISSUE TITLE
Foreach usage in visitChildren in sliver

### ISSUE THREAD

**Issue by hawkkiller** [flutter/flutter#132743]
I see that SliverMultiBoxAdapterElement uses forEach. Wouldn't it be better to replace it with plain `for`?

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/sliver.dart#L1051-L1057

**Comment by huycozy** [comment]
Hi @hawkkiller 
This looks like a proposal but can you share a bit about the advantages of this change? Is there any issue with the current `forEach`?

**Comment by hawkkiller** [comment]
Hi! I believe it is better code style as each callback called in forEach is scheduled to the new frame.

**Comment by goderbauer** [comment]
This usage of foreach seems fine since its passed an existing function. If it were a newly defined closure it would be a different story.

**Comment by hawkkiller** [comment]
@goderbauer could you please provide more information or direct me to relevant documentation?
