### ISSUE TITLE
[Impeller] Determine the Android version floor for expecting VK_SUBOPTIMAL_KHR on present from the swapchain.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#132708]
In https://github.com/flutter/engine/pull/44361, rotation checks during present were replaced with polling. This gives us consistent behavior across all Android versions but at the cost of a minor performance penalty.

If a version floor is determined, we can forego the performance penalty on devices that support giving the caller the indication on present that the swapchain is suboptimal.

**Comment by chinmaygarde** [comment]
Followup from the Impeller weekly discussion. cc @jonahwilliams  @matanlurey

**Comment by matanlurey** [comment]
As I remember it it's not something that could be reliably determined. For example some Samsung devices @jonahwilliams gave me _technically_ should implement `VK_SUBOPTIMAL_KHR`, but don't. We'd either have to go with a dynamic strategy, or, if you mean finding an _even higher_ Android version floor that looks consistent - perhaps :)

**Comment by jonahwilliams** [comment]
I think this issue involves following up with the Android team to confirm that their vulkan documentation is correct and/or experiment with a very high min API level.

**Comment by jonahwilliams** [comment]
xref: https://developer.android.com/games/optimize/vulkan-prerotation
