### ISSUE TITLE
`flutter_packaging_test`s failing with `gsutil.py` permissions error

### ISSUE THREAD

**Issue by yaakovschectman** [flutter/flutter#132796]
In the build dashboard, the `Mac/Mac_arm64 flutter_packaging_test`s are failing, reporting:
```
Running "gsutil.py -- cp gs://flutter_infra_release/releases/releases_macos.json /Volumes/Work/s/w/ir/x/w/archive/releases_macos.json" in /Volumes/Work/s/w/ir/x/w.
Error: Running "gsutil.py -- cp gs://flutter_infra_release/releases/releases_macos.json /Volumes/Work/s/w/ir/x/w/archive/releases_macos.json" in /Volumes/Work/s/w/ir/x/w failed with:
ProcessException: Found candidates, but lacked sufficient permissions to execute "gsutil.py".
```
E.g. for Mac_arm64: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_arm64%20flutter_packaging_test/2417/overview

None of the affected commits look to be of any relevance. The build tree is closed, and there is no obvious commit to revert to reopen it.

**Comment by sealesj** [comment]
Resolved with change to re-enable gsutil as executable
