### ISSUE TITLE
Rename the Runner to MyCustomRunner, but the generated GeneratedPluginRegistrant file is still in the Runner folder

### ISSUE THREAD

**Issue by kjxbyz** [flutter/flutter#132724]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Rename Runner Xcode project and workspace
2. Rename Runner Target 

### Expected results

Rename the `Runner` to `MyCustomRunner`, but the generated `GeneratedPluginRegistrant` file should be in the `MyCustomRunner` folder

### Actual results

Rename the `Runner` to `MyCustomRunner`, but the generated `GeneratedPluginRegistrant` file is still in the `Runner` folder

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.5 22G74 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.13.0 on channel stable at /Users/ying/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (25 小时前), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/ying/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/ying/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 75.1.4
    • Dart plugin version 232.8660.129

[✓] VS Code (version 1.81.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (5 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554                        • android-x64    • Android 13 (API 33)
      (emulator)
    • Kimmy's iPhone (mobile)      • 00008020-000A1D110A32002E            • ios            • iOS 16.6 20G75
    • iPhone 14 Pro Max (mobile)   • 66C1C365-BE63-4FCB-8D43-00622E87B9FE • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)              • macos                                • darwin-x64     • macOS 13.5 22G74
      darwin-x64
    • Chrome (web)                 • chrome                               • web-javascript • Google Chrome
      116.0.5845.96

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by dam-ease** [comment]
Hi @kjxbyz. Thanks for filing this. How are you renaming this? This might be similar to https://github.com/flutter/flutter/issues/9767, can you check if this https://github.com/flutter/flutter/issues/9767#issuecomment-1533771721 helps in your case?

**Comment by kjxbyz** [comment]
Is it possible to only rename the name of the Xcode project and workspace, but not the name of the target?

![20230817-171236](https://github.com/flutter/flutter/assets/47768002/65b22e8f-9ed2-4bd9-957b-c67711d9e803)

**Comment by dam-ease** [comment]
Hi @kjxbyz. You might wan to check this https://stackoverflow.com/questions/33370175/how-do-i-completely-rename-an-xcode-project-i-e-inclusive-of-folders out for more details on your question.

**Comment by kjxbyz** [comment]
@dam-ease I know the reason. In the left arrow part of the picture, the `Runner` cannot be renamed to `MyCustomRunner`.

**Comment by dam-ease** [comment]
Hi @kjxbyz. Is there a reason you'd like to rename this?

**Comment by kjxbyz** [comment]
@dam-ease The name of this folder wants to be consistent with the name of project/target.
