### ISSUE TITLE
Ignore --device-user option on platforms different than Android

### ISSUE THREAD

**Issue by manuel-plavsic** [flutter/flutter#132761]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

When calling `flutter run` and selecting an Android device, an APK is generated and installed globally, to all users of the Android device (even if there is only one user).

However, I don't only use `flutter run`. Sometimes I wanna install the same app from the Play Store. So what I do is I delete the app from the launcher and I open the Play Store. However, when I try to install the app I get the following warning: "Can't install $appName. Try again, and if it does not work, see common ways to fix the problem.". 

The problem is that when I want to delete the app, it is not enough to simply delete the app from the launcher: I need to go into the settings, then select Apps and remove the app by choosing "delete for all users". Which is a very annoying process.

## Existing Fix

There would already be a fix to this, which is using `--device-user`. If I uninstall an app installed with this option, it will not give me the problem I mentioned above.

However, if I run the app targeting another platform (e.g. Linux), it will not let me do it. It will say "--device-user is only supported for Android. At least one Android device is required.". Therefore, it is not safe to add this setting to `setting.json`.

## launch.json

Different `launch.json` configurations (this, targeting Android separately) could be used to improve IDE support and automating the process. However, this approach is requires to write configurations. And before running the app, the right configuration has to be manually selected (android and other platforms). Also, a `launch.json` has to be present in every Flutter project.

### Proposal

I propose letting the app run even if the targeted device's OS is not Android. A warning should still be shown, e.g. "--device-user is only supported for Android. Ignoring option due to different platform.".

This way I can define  `"dart.flutterRunAdditionalArgs": ["--device-user=0"]` in my VSCode profile's `settings.json` and it will work across all my projects.

**Comment by christopherfujino** [comment]
> Different launch.json configurations (this, targeting Android separately) could be used to improve IDE support and automating the process. However, this approach is requires to write configurations. And before running the app, the right configuration has to be manually selected (android and other platforms). Also, a launch.json has to be present in every Flutter project.

Forgive me, I don't use VS Code, so I'm not familiar with its configuration. However, when it comes to writing new configurations, this would consist of copy pasting a few lines of JSON, and adding a single new field, correct? And in terms of manually selecting, is the configuration drop-down right next to the run and debug button?

![Screenshot from 2023-08-21 12-12-25](https://github.com/flutter/flutter/assets/7856010/8cbf90bf-cab0-45c9-97ce-5e421b55f0ee)

**Comment by manuel-plavsic** [comment]
> > Different launch.json configurations (this, targeting Android separately) could be used to improve IDE support and automating the process. However, this approach is requires to write configurations. And before running the app, the right configuration has to be manually selected (android and other platforms). Also, a launch.json has to be present in every Flutter project.
> 
> Forgive me, I don't use VS Code, so I'm not familiar with its configuration. However, when it comes to writing new configurations, this would consist of copy pasting a few lines of JSON, and adding a single new field, correct? And in terms of manually selecting, is the configuration drop-down right next to the run and debug button?
> 
> ![Screenshot from 2023-08-21 12-12-25](https://user-images.githubusercontent.com/7856010/262130648-8cbf90bf-cab0-45c9-97ce-5e421b55f0ee.png)

Excuse me for the late reply. Yes, both your assumptions are correct. Do you think this is something that could be implemented?

**Comment by christopherfujino** [comment]
> > > Different launch.json configurations (this, targeting Android separately) could be used to improve IDE support and automating the process. However, this approach is requires to write configurations. And before running the app, the right configuration has to be manually selected (android and other platforms). Also, a launch.json has to be present in every Flutter project.
> > 
> > 
> > Forgive me, I don't use VS Code, so I'm not familiar with its configuration. However, when it comes to writing new configurations, this would consist of copy pasting a few lines of JSON, and adding a single new field, correct? And in terms of manually selecting, is the configuration drop-down right next to the run and debug button?
> > ![Screenshot from 2023-08-21 12-12-25](https://user-images.githubusercontent.com/7856010/262130648-8cbf90bf-cab0-45c9-97ce-5e421b55f0ee.png)
> 
> Excuse me for the late reply. Yes, both your assumptions are correct. Do you think this is something that could be implemented?

I'm sorry, but I don't think making this no-op on platforms where it does nothing is the right solution. I would recommend writing custom launch.json configs.
