### ISSUE TITLE
Allow disabling the overlay spinner for RefreshIndicator

### ISSUE THREAD

**Issue by stellaseah** [flutter/flutter#132775]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case
Internal: b/296423601

Currently, the RefreshIndicator comes with a loading spinner icon on user refresh, which might not align to our product's specs for loading a page. E.g. we might want to show a horizontal loading bar or ghost loading. 

### Proposal

Could we expose a way to omit showing the loading spinner?

Image currently shows the circular loading spinner (from RefreshIndicator) and the horizontal loading bar (our own loading widget).

![image](https://github.com/flutter/flutter/assets/142530802/0756e47a-d292-4487-8e4a-0031d10f2120)

**Comment by opxdelwin** [comment]
So you'd just want an option to disable it, or provide an alternative `Widget` as well?

**Comment by stellaseah** [comment]
I think disabling it would be sufficient.

AFAIK, this widget is gm3 compliant, so I don’t think we should show an
alternative widget should we decide to use a loading spinner.

**Comment by opxdelwin** [comment]
@danagbemava-nc @HansMuller so we move forward with an optional parameter to disable spinner?

**Comment by HansMuller** [comment]
An alternative that's worth exploring would be to add a callback like:
```
Widget buildSpinner(BuildContext context, Animation<double> animation)
```
To simplify the case we've been talking about here we could provide a static const value like
```
RefreshIndicator.noSpinner
```
Which would have the same effect as the flag we're talking about.

**Comment by opxdelwin** [comment]
So more like `RefreshIndicator.noSpinner` that'd carry out the functions of `RefreshIndicator()` but without the spinner in stage I (just the spinner icon) and stage II (the loading phase of the spinner)

**Comment by stellaseah** [comment]
We have no strong opinions about the implementation (a buildSpinner callback could be more versatile if there is a use case where we need our own spinner).

**Comment by opxdelwin** [comment]
Disabling the spinner would result in lack of visual clarity in current event status, i.e (`drag`, `armed`, `refresh`, `cancelled` etc).  
Should we consider adding callback function which provides current status?

This is as `onRefresh` is only triggered when pull is successful, i.e `refresh`, but lack of control over other state would result in lack of control over UI by devs.

**Comment by opxdelwin** [comment]
awaiting review for pull, @danagbemava-nc
