### ISSUE TITLE
`TimePickerThemeData` action buttons styles aren't working

### ISSUE THREAD

**Issue by kostvick** [flutter/flutter#132760]
### Steps to reproduce

1. Create custom ThemeData with useMaterial3: true,
2. Provide timePickerTheme, changing confirmButtonStyle or\and cancelButtonStyle
3. Provide created theme to the app and put TimePickerDialog in Scaffold.body

There was an issue #94927 however it was closed long time ago. The answer @TahaTesser gave, didn't help, as it changed the ButtonStyles for both - confirmButton and cancelButton. I think that those props must be removed (if they truly doesn't work) or if there is a solution to this it must be somewhere in docs

### Expected results

The confirmButtonStyle and cancelButtonStyle of TimePickerThemeData should have been changed

### Actual results

Nothing has changed. I think if those properties are in TimerPickerThemeData and we can provide our ButtonStyles to it, it should change.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

const Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark(useMaterial3: true).copyWith(
        scaffoldBackgroundColor: darkBlue,
        timePickerTheme: TimePickerThemeData(
          backgroundColor: Colors.blue,
          confirmButtonStyle: ButtonStyle(
            backgroundColor:
                MaterialStateColor.resolveWith((states) => Colors.grey),
            foregroundColor:
                MaterialStateColor.resolveWith((states) => Colors.red),
          ),
        ),
      ),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: TimePickerDialog(
            initialTime: TimeOfDay.fromDateTime(
              DateTime.now(),
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/flutter/flutter/assets/78662639/9d9cf7ef-40d9-4084-b13e-6a7b98093655)

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.5 22G74 darwin-x64, locale en-UA)
    • Flutter version 3.10.6 on channel stable at /Users/me/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (5 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/me/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/me/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • 48896B42-4960-4EB8-9A92-B04AB52D8E18 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 13.5 22G74 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 115.0.5790.170

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
The solution provided in https://github.com/flutter/flutter/issues/94927 allows you to customize both action buttons but you're right `TimePickerThemeData.confirmButtonStyle` & `TimePickerThemeData.cancelButtonStyle` properties aren't working as expected.

**Comment by LinetTheFox** [comment]
Facing same issue, and setting `textButtonTheme` is not enough because for my usecase these buttons should be different.

> ...or if there is a solution to this it must be somewhere in docs

I don't think there should be one - these parameters are already exposed as parameters in `TimePickerThemeData`, so you'd expect they would be prioritized over any other theme props 🤔
