### ISSUE TITLE
scaffoldKey.currentState.showBottomSheet  quite different from  showModalBottomSheet

### ISSUE THREAD

**Issue by ride4sun** [flutter/flutter#13279]
I have a hard time understanding why the API is not more symmetrical and easier to use  for showing a 
Modal or not Modal Bottom sheet. I like the straight forward approach under 2. for the Modal Bottom sheet. Why is there not a same for the non Modal? 

1.
```
      new InkWell(
            onLongPress: () {
                HomeScreen.scaffoldKey.currentState.showBottomSheet<Null>(
                  (context) => createBottomSheet(context, appController));
            },
```

2.
```
      new InkWell(
            onLongPress: () {
              showModalBottomSheet<Null>(
                  context: context,
                  builder: (context) =>
                      createBottomSheet(context, appController));
            },
```

[√] Flutter (on Microsoft Windows [Version 10.0.16299.64], locale en-US, channel alpha)
    • Flutter at c:\sdks\flutter
    • Framework revision e8aa40eddd (6 weeks ago), 2017-10-17 15:42:40 -0700
    • Engine revision 7c4142808c
    • Tools Dart version 1.25.0-dev.11.0

[√] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at C:\Users\ride4\AppData\Local\Android\sdk
    • Platform android-27, build-tools 27.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 19.1
    • Dart plugin version 172.4343.25

[√] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

**Comment by Hixie** [comment]
Good point.
