### ISSUE TITLE
[Impeller] Link 99th and worst frame time benchmarks on the document containing important Impeller benchmarks.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#132715]
Some important benchmarks the team tracks [are documented here](https://github.com/flutter/engine/blob/533670269c99a8f552edb1e5bf5a17b706e54e5b/impeller/docs/benchmarks.md). However, this is currently missing the 99th and worst frame time benchmarks. These are important as they capture the jank due to shader compilation. References to these benchmarks must be added to the page.

**Comment by chinmaygarde** [comment]
cc @gaaclarke

**Comment by jonahwilliams** [comment]
I followed the link and several of the bencharmks due include 99% and worst frame time. If there are specific ones that should be added, just make the change?
