### ISSUE TITLE
[CP] Fix Windows powershell script not being able to update Dart SDK

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#132718]
### Issue Link

https://github.com/flutter/flutter/issues/132592

### Commit Hash

[7ee864e](https://github.com/flutter/flutter/commit/7ee864ee37395f7ef13632cbc9663e24fcad248c)

### Target

beta (3.14)

### PR Link

https://github.com/flutter/flutter/pull/132762

### Changelog Description

Ensure the existing //flutter/bin/cache/LICENSE.dart_sdk_archive.md is moved before unzipping a new Dart SDK, preventing the powershell script from hanging.

### Impacted Users

Windows developers

### Impact Description

Once users get on an affected version, their NEXT `flutter upgrade` will leave them in a bad state where they can't extract the new Dart SDK. Re-running the tool will not help, as the batch entrypoint will still detect the Dart SDK is not present, and then run the powershell script to download and unzip the Dart SDK.

### Workaround

The workaround would be to run `flutter upgrade` until it hangs, kill the process, delete //flutter/bin/cache/LICENSE.dart_sdk_archive.md, and then re-run to complete extracting the zip and building the tool.

### Risk

medium

### Test Coverage

yes

**Comment by christopherfujino** [comment]
https://github.com/flutter/flutter/pull/132669 is currently going through code review, I will ensure it is merged and open a CP PR in the morning.

**Comment by christopherfujino** [comment]
upstream PR merged, CP PR forthcoming...

**Comment by loic-sharma** [comment]
CP PR: https://github.com/flutter/flutter/pull/132762

**Comment by christopherfujino** [comment]
@zanderso can you review, and if approving, add `cp: approved` label?

**Comment by zanderso** [comment]
lgtm
