### ISSUE TITLE
Flutter 3.10.6 ios crashes  

### ISSUE THREAD

**Issue by Zia9335** [flutter/flutter#132786]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

flutter run

### Expected results

App should be run on ios

### Actual results

App is not opening android its fine

### Code sample

<details><summary>Code sample</summary>

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CADisableMinimumFrameDurationOnPhone</key>
	<true/>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleDisplayName</key>
	<string>Anadolu Digital</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>Anadolu Digital</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSMicrophoneUsageDescription</key>
	<string>Need microphone access for uploading audio</string>
	<key>UIApplicationSupportsIndirectInputEvents</key>
	<true/>
	<key>UIBackgroundModes</key>
	<array>
		<string>fetch</string>
		<string>remote-notification</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>FLTEnableImpeller</key>
    <false />
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
</dict>
</plist>

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>
   -------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: BECF7D2A-6A23-419A-98C8-39FB584B3334
CrashReporter Key:   E30DE822-EC80-6317-2C69-AB36940ACF8A
Hardware Model:      MacBookPro14,3
Process:             Runner [20809]
Path:                /Users/USER/Library/Developer/CoreSimulator/Devices/B06C5B84-8F99-4A62-988D-C5C08DD78093/data/Containers/Bundle/Application/7585FDE6-462B-4C7F-A466-AB1317DAAB34/Runner.app/Runner
Identifier:          com.dbug.minitv.liveTvMini
Version:             1.0.4 (8)
Code Type:           X86-64 (Native)
Role:                Foreground
Parent Process:      launchd_sim [15100]
Coalition:           com.apple.CoreSimulator.SimDevice.B06C5B84-8F99-4A62-988D-C5C08DD78093 [6068]
Responsible Process: SimulatorTrampoline [1720]

Date/Time:           2023-08-17 23:42:29.2001 +0500
Launch Time:         2023-08-17 23:42:27.9198 +0500
OS Version:          macOS 13.5 (22G74)
Release Type:        User
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Termination Reason: SIGNAL 6 Abort trap: 6
Terminating Process: Runner [20809]

Triggered by Thread:  6

Last Exception Backtrace:
0   CoreFoundation                	    0x7ff80045477b __exceptionPreprocess + 226
1   libobjc.A.dylib               	    0x7ff80004db73 objc_exception_throw + 48
2   CoreFoundation                	    0x7ff8004543fd -[NSException init] + 0
3   Runner                        	       0x107202d8c GADApplicationVerifyPublisherInitializedCorrectly + 380
4   Runner                        	       0x107202f42 0x106f36000 + 2936642
5   libdispatch.dylib             	    0x7ff80013be40 _dispatch_call_block_and_release + 12
6   libdispatch.dylib             	    0x7ff80013d0d9 _dispatch_client_callout + 8
7   libdispatch.dylib             	    0x7ff80014002c _dispatch_queue_override_invoke + 1276
8   libdispatch.dylib             	    0x7ff800150717 _dispatch_root_queue_drain + 414
9   libdispatch.dylib             	    0x7ff80015124d _dispatch_worker_thread2 + 251
10  libsystem_pthread.dylib       	    0x7ff837749c0f _pthread_wqthread + 257
11  libsystem_pthread.dylib       	    0x7ff837748bbf start_wqthread + 15

Thread 0::  Dispatch queue: com.apple.main-thread

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>
mac@MACs-MacBook-Pro ~ % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.5 22G74 darwin-x64, locale
    en-PK)
[✓] Android toolchain - develop for Android devices (Android SDK version
    34.0.0-rc2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.81.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

</details>

**Comment by stuartmorgan** [comment]
> 0 CoreFoundation 0x7ff80045477b __exceptionPreprocess + 226
> 1 libobjc.A.dylib 0x7ff80004db73 objc_exception_throw + 48
> 2 CoreFoundation 0x7ff8004543fd -[NSException init] + 0
> 3 Runner 0x107202d8c GADApplicationVerifyPublisherInitializedCorrectly + 380

This is an exception being thrown by an SDK you are using (apparently indicating that you haven't done some required application setup, based on the symbol name); it's not coming from Flutter. You'll need to contact the developers of that SDK for help.

**Comment by stuartmorgan** [comment]
(See also https://github.com/flutter/flutter/issues/130877)
