### ISSUE TITLE
Migrating Engine targets from Goma to Reclient

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#132701]
This tracks the status of Goma to Reclient migration.

Context: Goma will be deprecated EOY, and we need to switch over to Reclient.

Action items:

- [x] Setup rbe projects/instances/workers/servers via terraform - Done by @yusuf-goog 
- [x] Create rbe recipes modules to support `reclient` context replacing `goma` context, https://flutter-review.googlesource.com/c/recipes/+/49541, https://flutter-review.googlesource.com/c/infra/+/50860
- [x] Update `gn` related configs to point to the new wrapper instead of `gomacc`, https://github.com/flutter/engine/pull/45271, https://github.com/flutter/buildroot/pull/757, https://github.com/flutter/buildroot/pull/758
- [x] Migrate Engine targets

**Comment by keyonghan** [comment]
https://github.com/flutter/engine/pull/46272 to restore targets that affect framework, waiting for 3.16 branch.

**Comment by philwo** [comment]
Hi folks, could you please share an update on the current progress of migrating from Goma to RBE? How much is still left to do?

**Comment by keyonghan** [comment]
Flutter team is still working on the migration, but we have a couple of blockers from our side. https://github.com/flutter/flutter/issues/136570 is one example.

Also we need to collect some baseline data before moving forward. Still targeting in Q4, but we cannot guarantee.

**Comment by philwo** [comment]
Thank you, that's very helpful!

**Comment by atetubou** [comment]
Hi, what is the current status of this issue? Did you stop using goma?

**Comment by zanderso** [comment]
We're still using goma in the build that @keyonghan mentions, and migrating from goma to reclient for local developer workflows is blocked on a small amount of documentation and tooling work. I suspect that there are still a few weeks of calendar time remaining before we can start deleting goma support from the tree.

I would also really like to move our clang-tidy usage to reclient, but that is blocked on b/326591374 and any issues that it is potentially masking.

**Comment by atetubou** [comment]
Hi, what is the current progress of goma deprecation in flutter? Can we assume you finished migration to reclient and shutted down your own goma instances?

**Comment by atetubou** [comment]
@zanderso ping?
