### ISSUE TITLE
Timezone reported as UTC even though it is GMT+02:00

### ISSUE THREAD

**Issue by andynewman10** [flutter/flutter#132790]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a Flutter application on a Sony Z5 Compact (E5823) device (this device was freshly reinstalled through a factory reset a few days ago. The device uses Android 7.1.1, is in pristine condition, and has no other app installed).
2. Double-check the time settings and the time zone and make sure they are correct.
3. Add the following code:
```
DateTime dateTime = DateTime.now();
```
4. Run the code and inspect the value of `dateTime`, either by printing it or using the debugger (I use VS code).

### Expected results

In Paris, France, `dateTime.toString()` should be equal to
```
DateTime (2023-08-17 21:23:23.241901)
```
and the time zone should be:
```
timeZoneName: "CEST"
timeZoneOffset: Duration (2:00:...)
```
In other words, the time should be `21:23` in the `CEST` timezone.

### Actual results

`dateTime.toString()` is
```
DateTime (2023-08-17 19:23:23.241901)
```
and the timezone reported is:
```
timeZoneName: "GMT"
timeZoneOffset: Duration (0:00:...)
```
In other words, the time is correct (in its reported timezone: it really is `19:23` in `UTC/GMT` timezone), but the timezone is not correct.

The same program runs fine (no timezone error) on

- an iPhone 8 with iOS 16.6
- a Samsung S5 Mini (SM-G800F) with Android 6.0.1

### Comparison with a native Android implementation

1. Create a native Android application in Android Studio, use the "Basic Activity" template
2. Add the following code:

```
                SimpleDateFormat timezoneOffsetFormatter = new SimpleDateFormat("ZZZZZ");
                String timezoneNotation = timezoneOffsetFormatter.format(new Date()); // "+02:00"
                String timezoneLocation = TimeZone.getDefault().getID(); // "Europe/Paris"
                String tzString = timezoneNotation + "," + timezoneLocation;
```
3. Run the application on the same device (Sony Xperia Z5 Compact with Android 7.1.1).

Look at the `tzString` value. This value is `+02:00,Europe/Paris`.

### Code sample

<details><summary>Code sample</summary>

```dart
DateTime dateTime = DateTime.now();
```
</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [version 10.0.22000.2295], locale fr-FR)
    • Flutter version 3.10.6 on channel stable at C:\Users\fred\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (5 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\fred\AppData\Local\Android\sdk
    • Platform android-33, build-tools 34.0.0
    • Java binary at: C:\Users\fred\Documents\Applications\android-studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.0.31919.166
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Users\fred\Documents\Applications\android-studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at C:\Users\fred\Documents\Applications\IntelliJ
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.81.1)
    • VS Code at C:\Users\fred\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.70.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [version 10.0.22000.2295]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 115.0.5790.171
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 115.0.1901.203

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@andynewman10 
Since `DateTime` [method](https://api.dart.dev/stable/1.10.1/dart-core/DateTime-class.html) comes from Dart and the behavior reported looks to be dart specific, so I suggest you to file this issue in dedicated repo: https://github.com/dart-lang/sdk/issues
Closing from here. If you disagree, write in comments and I'll reopen it.

**Comment by andynewman10** [comment]
Thanks for your reply - sure, I will post a new bug at that location. The bug actually repros in an emulator, which will be handy (I updated the bug report at the top just in case).
