### ISSUE TITLE
`Windows plugin_test_windows` build infra fails with no steps

### ISSUE THREAD

**Issue by yaakovschectman** [flutter/flutter#132844]
As of the most recent engine roll, seemingly unrelated to the roll itself, the title test fails the build tree. The build log shows `Build infra failed.` with no further details, and `No steps.` under `STEPS & LOGS`.  
Failure: https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20plugin_test_windows/3078/overview

**Comment by keyonghan** [comment]
This is due to [LUCI logdog outage](https://groups.google.com/a/google.com/g/luci-outages/c/-AiKoWIihvg/m/7tNc0VMxGAAJ?utm_medium=email&utm_source=footer&pli=1), which has been recovered.
