### ISSUE TITLE
Ability to customize arrow icon in SubmenuButton

### ISSUE THREAD

**Issue by kamilkarp** [flutter/flutter#132898]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Currently, there's no easy way to override default arrow icon in `SubmenuButton`. The `leadingIcon` and `trailingIcon` are custom widgets that can be added before and after content of this button, but the arrow icon will always be there.

<img width="210" alt="image" src="https://github.com/flutter/flutter/assets/22731536/6fa9130a-eb3e-47e8-83fe-b1dc89a1237e">

<img width="265" alt="image" src="https://github.com/flutter/flutter/assets/22731536/2cfeec87-80e6-4b0a-bde4-1d927b1b94f7">

In `menu_anchor.dart` we can see that this arrow icon will be always be visible if the orientation is vertical(`showDecoration` and `hasSubmenu` will be `true`)
```
        if (showDecoration && hasSubmenu)
          Padding(
            padding: EdgeInsetsDirectional.only(start: horizontalPadding),
            child: const Icon(
              Icons.arrow_right, // Automatically switches with text direction.
              size: _kDefaultSubmenuIconSize,
            ),
          ),
```

As a workaround I had to wrap SubmenuButton in Stack, pass `SubmenuButton.styleFrom(iconColor: Colors.transparent)` to SubmenuButton's style and position my own icon in place of the arrow icon.

### Proposal

It would be really nice to have a way of customising this arrow icon. My proposition is to have an optional builder in SubmenuButton.

`preferredSize` would be the `_kDefaultSubmenuIconSize` to know the size of the default icon.
`preferredColor` would be added for convienience and will indicate the color that the default arrow icon would have(from theme data)

To determine other things like directionality we could get it through context

```dart
SubmenuButton(
  customArrowIconBuilder: (BuildContext context, double preferredSize, Color preferredColor) {
      return MyCustomArrowIcon(preferredSize, preferredColor);
  },
   ...
)
```

**Comment by goderbauer** [comment]
There is a partial patch in https://github.com/flutter/flutter/pull/132899 that somebody could take over to implement this.

**Comment by piedcipher** [comment]
I would like to take this up!

**Comment by aike1202** [comment]
any update
