### ISSUE TITLE
Option --preview-dart-2 is not passed from 'flutter run --profile' to 'flutter build aot' (when building for iOS)

### ISSUE THREAD

**Issue by alexmarkov** [flutter/flutter#13283]
## Steps to Reproduce

Run app on Mac with iOS device using

```
flutter run -v --profile --preview-dart-2
```

In the output there is a 'flutter build aot' command like

```
flutter --suppress-analytics build aot --output-dir=build/aot --target-platform=ios --target=/Users/mac4/.cocoon/flutter/dev/benchmarks/microbenchmarks/lib/stocks/layout_bench.dart --profile
```

You can see that it doesn't have --preview-dart-2 option.

**Comment by alexmarkov** [comment]
/cc @yjbanov 

I think this is the reason why microbenchmarks do not fail in --preview-dart-2 mode on iOS while failing on android.

**Comment by aam** [comment]
https://github.com/flutter/flutter/pull/13285 with the fix

**Comment by aam** [comment]
FWIW, I still see microbenchmark failure locally even with the fix that passes `--preview-dart-2` to build flx:
```
[microbenchmarks_ios] [STDOUT] Executing: $FH/flutter/dev/devicelab/../../bin/flutter run -v --profile -d bad2cf647626bc00d1864fb5202d98910167229a --preview-dart-2 lib/stocks/layout_bench.dart
...
[microbenchmarks_ios] [STDOUT]            ♦ $FH/flutter/bin/flutter --suppress-analytics build aot --output-dir=build/aot --target-platform=ios --target=$FH/flutter/dev/benchmarks/microbenchmarks/lib/stocks/layout_bench.dart --profile --preview-dart-2
...
[microbenchmarks_ios] [STDOUT]            Building AOT snapshot in profile mode (ios-profile)...
[microbenchmarks_ios] [STDOUT]            Dart snapshot generator failed with exit code 253
```

**Comment by alexmarkov** [comment]
That's the expected behavior. Microbenchmarks should fail for now due to outdated quiver package (kernel front-end reports errors on the old version of that package).

The microbenchmarks were passing on iOS by mistake because they were not testing --preview-dart-2 and now as you fixed this they will start failing :)

**Comment by aam** [comment]
https://github.com/flutter/flutter/pull/13285 landed
