### ISSUE TITLE
[go_router] async redirect routes cause flickering dark screen between transition

### ISSUE THREAD

**Issue by agufagit** [flutter/flutter#132885]
### Is there an existing issue for this?

- [X] I have searched the [existing package issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Apackage)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### What package does this bug report belong to?

go_router

### What target platforms are you seeing this bug on?

Android

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>
```lock
go_router:
    dependency: "direct main"
    description:
      name: go_router
      sha256: "2aa884667eeda3a1c461f31e72af1f77984ab0f29450d8fb12ec1f7bc53eea14"
      url: "https://pub.dev"
    source: hosted
    version: "10.1.0"
```
</details>

### Steps to reproduce

1. make GoRoute redirect function async

### Expected results

no flicker dark screen between transition

### Actual results

flicker dark screen between transition

### Code sample

<details><summary>Code sample</summary>

```dart
GoRoute(
        name: "profiles",
        path: '/profile',
        parentNavigatorKey: rootNavigatorKey,
        builder: (context, state) => const ProfilesScreen(),
        redirect: (BuildContext context, GoRouterState state) async {
          return null;
        },
)
```

</details>

### Screenshots or Videos

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @agufagit 
The flickering dark screen may not be specific to go_router package, as there's a similar issue open https://github.com/flutter/flutter/issues/116127 that you can check and confirm if it resembles your case or not.

**Comment by agufagit** [comment]
not sure if it's the same problem, when I remove async, it works, dark screen disappears, but when I add async, dark screen appears.

not a deal breaker for me, I ended up placing redirect code somewhere else

**Comment by darshankawar** [comment]
@agufagit 
I am unable to replicate it properly using the code snippet you provided and using it in the package's [example](https://pub.dev/packages/go_router/example). Can you provide a runnable code ?

**Comment by agufagit** [comment]
that's the exact code, I just add `async` without any logic, and it flickers dark screen, I guess it's just my system then, I'll close this issue

Thank you for your time.
