### ISSUE TITLE
Uneven blurring on Cupertino nav and tab bar

### ISSUE THREAD

**Issue by xster** [flutter/flutter#13280]
Seems like the image blur filter from skia is blurring from contents around it and at the edge of the screen, the blurring effect is reduced since there's no content outside the screen edge.

It ends up creating a gradient effect where the inner side of the bar is properly blurred and the outer side of the bar is less blurred.

**Comment by sethladd** [comment]
Good catch.

**Comment by xster** [comment]
https://bugs.chromium.org/p/skia/issues/detail?id=7411

**Comment by xster** [comment]
As per @brianosman,  we can try other [TileMode](https://cs.chromium.org/chromium/src/third_party/skia/include/effects/SkBlurImageFilter.h?q=skblurimage+file:%5Esrc/third_party/skia/+package:%5Echromium$&l=27) in https://github.com/flutter/engine/blob/08961f8ec5d3ee9ecc55bf4e9474ea37b0480c2b/lib/ui/painting/image_filter.cc#L53

**Comment by xster** [comment]
@brianosman, I tried the other flags though I seem to be getting identical outputs

Clamp:
![clamp](https://user-images.githubusercontent.com/156888/34590273-9ad5d452-f16a-11e7-98be-0821726722b5.png)

Clamp to black:
![clamp_to_black](https://user-images.githubusercontent.com/156888/34590279-9d90e22c-f16a-11e7-8967-bc8cd9d3c824.png)

Repeat:
![repeat](https://user-images.githubusercontent.com/156888/34590280-9fd1c344-f16a-11e7-9411-505a5a870af2.png)

**Comment by brianosman** [comment]
I'm WFH today, so I can't easily repro this. It may depend on the exact composition of skia calls. Can you record an SKP from running your sample (flutter screenshot --skia=<port number>), and send/attach it? That will let us see exactly how the image filter is being applied.

**Comment by xster** [comment]
TIL about screenshot skia

Attached
[flutter_01.skp.zip](https://github.com/flutter/flutter/files/1608131/flutter_01.skp.zip)

**Comment by brianosman** [comment]
@xster  Ah, just saw that you attached an SKP. Cool. I just tried using kClamp locally, and it seems to have had the intended effect:

![flutter_01](https://user-images.githubusercontent.com/18424222/34893902-40541626-f7ad-11e7-8d48-60ab5d36026b.png)

**Comment by xster** [comment]
Tested, confirm this works!

**Comment by Chimba123** [comment]
If I am not mistaken I think this problem is back
check link below 

https://github.com/flutter/flutter/issues/58835
