### ISSUE TITLE
Sensitive object redaction

### ISSUE THREAD

**Issue by hanskokx** [flutter/flutter#132822]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Users often enter PII and sensitive information, such as passwords, social security numbers, and the like.

### Proposal

I propose a decorator that can be applied to sensitive objects that prevent them from being logged in any form.

**Comment by dam-ease** [comment]
Hi @hanskokx. Thanks for proposing this. Please can you provide more details on this, preferably examples or do you mean decorator in terms of `obscure` as in password fields?

**Comment by hanskokx** [comment]
Currently, this is what you see:
```dart
class Credentials {
  final String username;
  final String password;

  Credentials({
    required this.username,
    required this.password,
  });

  Map<String, String> toJson() => {'username': username, 'password': password};

  @override
  String toString() => toJson().toString();
}

final Credentials myCredentials = Credentials(
  username: "hans",
  password: "password",
);

print(myCredentials);
```

`I/flutter (10392): {username: hans, password: password}`

What I'm proposing is adding a new decorator or keyword, like this:

```dart
class Credentials {
  final String username;
  final String password;

  Credentials({
    required this.username,
    sensitive required this.password,
  });
...
```
So, at a _system level_ when you try to log/print the parameter, you'd see something like this:

`I/flutter (10392): {username: hans, password: <SENSITIVE>}`

**Comment by dam-ease** [comment]
Hi @hanskokx. I think this feature request seems to be related to Dart itself, so the correct repo to file an issue for it is https://github.com/dart-lang/sdk/issues

I'd be closing this from here.
Thank you!
