### ISSUE TITLE
[Tools] Adding navigation attribute by default in the AndroidManifest.xml 

### ISSUE THREAD

**Issue by hioshih** [flutter/flutter#132897]
I just wanted to share that I found a solution for issue #86456:

https://stackoverflow.com/questions/31032042/android-get-restarted-once-it-is-connected-or-disconnected-to-bluetooth-device

Basically, most flutter apps right now are restarted if you connect a Logitech MX Keys BT keyboard on an android device.

It is easily solved by adding the "navigation" option by default in the AndroidManifest.xml:
android:configChanges="keyboard|keyboardHidden|navigation"

It would be nice if this were to be changed by default on flutter framework when creating a new projects or adding android platform support (flutter create --platform android).

But I don't know how to make that suggestion, so if someone could kindly make that pull request, it would be appreciated.

> Without additional information, we are unfortunately not sure how to resolve this issue. 
> We are therefore reluctantly going to close this bug for now. 
> Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
> Thanks for your contribution.
> 
> Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
> All system setups can be slightly different, so it's always better to open new issues and reference related issues.
> 
> _Originally posted by @TahaTesser in https://github.com/flutter/flutter/issues/86456#issuecomment-900299468_
>

**Comment by huycozy** [comment]
Thanks for filing the issue, @hioshih 
I can see this issue on both Flutter and Android native project. Adding  `navigation` indeed can make this work. 

But I can't observe any crash when connecting/disconnecting Bluetooth. The actual result is the app will be restarted only. If you see the crash, can you please provide the complete stack trace here? (flutter run -v)

**Comment by hioshih** [comment]
> 

You are right, it doesn't "crash".  It just restart, but makes you lose any non persistent state that the app had, as if the app were closed abruptly and opened again.

**Comment by huycozy** [comment]
Thanks for confirming this. Labeling the issue as a proposal for `adding the "navigation" option by default in the AndroidManifest.xml`.

**Comment by gmackall** [comment]
@hioshih Thanks for filing this issue! To anyone else finding this issue because you are seeing your app restart on bluetooth keyboard connect/disconnect, adding the above events is a reasonable change (especially if you are a pure flutter app without platform views).

We don't think this should be default for all flutter apps, because of the complexity that this causes with platform views and how they might interact with a keyboard that is dynamically added or dropped.

**Comment by hioshih** [comment]
@gmackall Thanks for your feedback on this.

I'm not sure what you meant by "other platform views", as it is specific for android and documentation itself says it is not a common occurrence, so I thought it wouldn't be any harm to support it rather than ignore it. 

But well, I'm no expert on this so I will take your word on it. 

Just in case may be of any help, here is the reference on android docs about navigation:

> ["navigation" | TA change to the navigation type (trackball or D-pad). Normally, this does not happen.](https://developer.android.com/guide/topics/manifest/activity-element#config)

**Comment by gmackall** [comment]
> @gmackall Thanks for your feedback on this.
> 
> I'm not sure what you meant by "platform views" (no ui maybe?), as it is specific for android and documentation itself says it is not a common occurrence, so I thought it wouldn't be any harm to support it rather than ignore it.
> 
> But well, I'm no expert on this so I will take your word on it.
> 
> Just in case it may be of any help, here is the reference on android docs about navigation:
> 
> > ["navigation" | TA change to the navigation type (trackball or D-pad). Normally, this does not happen.](https://developer.android.com/guide/topics/manifest/activity-element#config)

"Platform views" refers to ways by which Flutter developers can visually embed an actual Android view within their Flutter UI. There is some more description here https://github.com/flutter/flutter/wiki/Android-Platform-Views. Let me know if you have any other questions!
