### ISSUE TITLE
[CP] Space character should be optional when tree shaking fonts

### ISSUE THREAD

**Issue by eyebrowsoffire** [flutter/flutter#132883]
### Issue Link

https://github.com/flutter/flutter/issues/132711

### Commit Hash

6f227c0

### Target

stable

### PR Link

https://github.com/flutter/flutter/pull/132882

### Changelog Description

Fixes an issue with tree shaking fonts that do not contain a space glyph.

### Impacted Users

Flutter Web apps that have custom fonts that do not contain a space glyph

### Impact Description

The flutter tool fails out with an error when attempting to compile an app that uses a custom icon font that does not contain a space.

### Workaround

The user can pass --no-tree-shake-icons to prevent icon tree shaking, which will allow the flutter tool to complete the build process. However, it skips icon tree shaking, which bloats the payload size of their font files.

### Risk

low

### Test Coverage

yes

### Validation Steps

Unit tests verify that the tool is feeding the proper into the font subset tool. Also, verified that the repository provided in https://github.com/flutter/flutter/issues/132711 can now build for web without issue.

**Comment by zanderso** [comment]
CP LGTM. The linked PR depends on the Engine CP https://github.com/flutter/engine/pull/44869 landing first.

**Comment by itsjustkevin** [comment]
Looks like https://github.com/flutter/engine/pull/44869 is just waiting on a review.  Will merge once it is reviewed as all tests are already passing.
