### ISSUE TITLE
[Windows] Investigate adding a build error if using APIs not available on Windows 7

### ISSUE THREAD

**Issue by loic-sharma** [flutter/flutter#132862]
## Background

Dart and Flutter offer best effort support for Windows 7. Thus, Dart and Flutter must not directly link against Windows APIs that aren't available on Windows 7. Doing so would cause a Flutter app to crash immediately on startup. For example, see: https://github.com/flutter/flutter/issues/130554

As a workaround, Dart and Flutter can use dynamic loading with fallback logic.

## Prevention

Ideally we could catch usages of Windows APIs not available on Windows 7 at build time. Investigate:

1. https://stackoverflow.com/questions/10112051/c-compile-time-macros-to-detect-windows-os
2. https://learn.microsoft.com/en-us/windows/win32/winprog/using-the-windows-headers?redirectedfrom=MSDN#setting_winver_or__win32_winnt
3. https://learn.microsoft.com/en-us/cpp/porting/modifying-winver-and-win32-winnt?view=msvc-170

**Comment by FusoraTech** [comment]
When platform views arrive, all pre Windows 10 will be doomed, because WinUI 3+ are Win 10+ only. Unless Flutter go distances trying to mimic lots of native controls with internal alternatives until finally any pre Windows 10 are finally considered unsupported for Flutter.
