### ISSUE TITLE
check on ios device attached to mac-45

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#132872]
@kentnguyen99 please check the iphone connected to mac-45 its showing as not connected https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-45

We had upgraded mac-45 to macOS 13 recently. Maybe the iphone need to accept the auth dialog?

**Comment by yusuf-goog** [comment]
cc @vashworth

**Comment by kentnguyen99** [comment]
@yusuf-goog  iPhone is up and running fine now. I power recycled the iPhone, it was hung or something.

**Comment by vashworth** [comment]
I confirmed it's working. Closing this. Thanks!
