### ISSUE TITLE
`runIf` clauses in .ci.yaml don't actually do anything

### ISSUE THREAD

**Issue by eyebrowsoffire** [flutter/flutter#132858]
The `runIf` clauses specified in the `.ci.yaml` file (at least in the engine) don't seem to actually prevent CI steps from running on PRs that don't touch the files specified in `runIf`. In my experience, this appears to be universally true with both the engine and framework repos, but here is one concrete example:

The Linux linux_clang_tidy step is specified in the .ci.yaml file here: https://github.com/flutter/engine/blame/3cdb07cacc543bfda642c775025a8eba08a186cd/.ci.yaml#L211C6-L211C6

The `runIf` criteria for this step is specified as follows:
```
    runIf:
      - DEPS
      - .ci.yaml
      - tools/clang_tidy/**
      - ci/builders/**
      - ci/clang_tidy.sh
      - "**.h"
      - "**.c"
      - "**.cc"
      - "**.fbs"
      - "**.frag"
      - "**.vert"
```

Here is an example of a simple web engine PR that only touches two dart files in the `flutter/lib/web_ui` hierarchy https://github.com/flutter/engine/pull/44693. Neither of these files meets the `runIf` criteria. Despite that, the `Linux linux_clang_tidy` CI step definitely ran for this PR (https://github.com/flutter/engine/pull/44693/checks?check_run_id=15886836112).

Reading through cocoon's code, I notice that there is a recovery path that adds all targets regardless of the `runIf` clause if the diff could not be successfully fetched from github: https://github.com/flutter/cocoon/blob/6f5a331f23fee53f4cf93fb50ef72f6c80b5a0d5/app_dart/lib/src/service/scheduler.dart#L414C7-L414C7

If this is actually the issue, warnings would appear in the cocoon logs. However, I don't know where the cocoon logs go or how to check them.

**Comment by matanlurey** [comment]
I believe that was _our_ mistake. @zanderso only added the `runIf` 2 days ago (https://github.com/flutter/engine/commit/dbfe71c898b6761af897574c297ce89623ce0d8c) but the commit is from 4 days ago.

**Comment by godofredoc** [comment]
Thanks @matanlurey for the context. @eyebrowsoffire can you please rebase and retry?

**Comment by eyebrowsoffire** [comment]
I see. Seems that more recent web PRs are skipping clang-tidy, as intended. Closing!
