### ISSUE TITLE
[BUG][Flutter 3.13.0]Unable to push app to testflight

### ISSUE THREAD

**Issue by bibash28** [flutter/flutter#132842]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Try to push app to testflight

### Expected results

Ready to submit

### Actual results

Blank
![image](https://github.com/flutter/flutter/assets/18188709/21b074db-993d-49e1-8707-2382892b6aa7)

**Comment by rushabhshah065** [comment]
@bibash28 Please add more details here. What steps you followed, what errors you are receiving, and what logs of the errors?

**Comment by dam-ease** [comment]
Hi @bibash28. If you had a successful upload to the store and just want to view this on the app store site, you might have to wait for a while to be able to see this. I'm guessing you should be able to view it now. If at all you can't by now, you might want to share the logs of the errors you received.
Closing this as this doesn't seem to be an issue with Flutter itself, if you disagree, kindly comment and I'd reopen this.
Thank you!
