### ISSUE TITLE
TextField selection truncated in Chinese

### ISSUE THREAD

**Issue by Kigoal** [flutter/flutter#132819]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

main.dart

```dart
MaterialApp.(
  localizationsDelegates: const <LocalizationsDelegate<Object>>[
    GlobalWidgetsLocalizations.delegate,
    GlobalMaterialLocalizations.delegate,
    GlobalCupertinoLocalizations.delegate,
  ],
  localeResolutionCallback: (locale, supportedLocales) => locale,
)
```

pubspec.yaml
``` yaml
environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
```

### Expected results

display Chinese normally under `Pixel 7 API 34`

![image](https://github.com/flutter/flutter/assets/21240282/b6e42a55-1306-4028-8602-9678d154f955)

### Actual results

cannot display Chinese normally under `Iphone14 Pro Max` `iOS 16.6`

![fe8ffefd-1adc-4f39-9689-b88edcc0332b](https://github.com/flutter/flutter/assets/21240282/578a9c84-5170-484b-b4d0-7101dd9178c1)

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.13.0, on Microsoft Windows [版本 10.0.22621.2134], locale zh-CN)
    • Flutter version 3.13.0 on channel stable at C:\Apps\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (2 days ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\95646\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Apps\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.5)
    • Visual Studio at C:\Apps\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33829.357
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Apps\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] Connected device (4 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • sdk gphone64 x86 64 (mobile) • emulator-5556 • android-x64    • Android 14 (API 34) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [版本 10.0.22621.2134]
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 115.0.1901.203
```

</details>

**Comment by kennyfully88** [comment]
@Kigoal ,  Take a look at issue  #132818 . It may be related because the user that has this issues is also on a Chinese locale `zh-CN`

**Comment by Kigoal** [comment]
> @Kigoal , Take a look at issue #132818 . It may be related because the user that has this issues is also on a Chinese locale `zh-CN`

not the same question

**Comment by Kigoal** [comment]
@kennyfully88  has a new question, the virtual keyboard flashes when you press and swipe


https://github.com/flutter/flutter/assets/21240282/7cd7ea10-b9c5-4cfb-a919-62c496aefae7

**Comment by dam-ease** [comment]
Hi @Kigoal. Thanks for filing this issue. This seems to be similar/related to https://github.com/flutter/flutter/issues/69847. Can you check this out? If not, kindly provide more information on this issue. More specifically, a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example).
Thank you!

**Comment by hukusuke1007** [comment]
The same goes for Japanese.
<img src="https://github.com/flutter/flutter/assets/29278033/7bacf27c-dd70-4c67-89c4-8cdc0262ed02" width="50%" />

**Comment by Kigoal** [comment]
> Hi @Kigoal. Thanks for filing this issue. This seems to be similar/related to #69847. Can you check this out? If not, kindly provide more information on this issue. More specifically, a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example).
> Thank you!


@dam-ease this is a new project

```dart
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
      localizationsDelegates: const <LocalizationsDelegate<Object>>[
        GlobalWidgetsLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      localeResolutionCallback: (locale, supportedLocales) => locale,
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(title),
      ),
      body: const Center(
        child: TextField(),
      ),
    );
  }
}

```

```yaml
name: flutter_application_2
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
```

<img width="435" alt="image" src="https://github.com/flutter/flutter/assets/21240282/a05fa15c-f208-4609-9c7d-9b730a5854d6">

<img width="435" alt="image" src="https://github.com/flutter/flutter/assets/21240282/04021b7c-1e08-47e3-b077-8901bf30c443">

**Comment by dam-ease** [comment]
Hi @Kigoal. Thanks for responding. From my understanding of this, it seems this issue is similar to  https://github.com/flutter/flutter/issues/69847. Can you check this out and if possible explain the difference?
Thank you!

**Comment by tgucio** [comment]
This appears to be a more generic problem with text being clipped with all fonts, including Latin while inside a `CupertinoTextSelectionToolbar`.

I've created https://github.com/flutter/flutter/issues/133140 with minimum repro.
