### ISSUE TITLE
[Impeller] Move secondary build configuration from the buildroot to the engine. 

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#132981]
See also https://github.com/flutter/buildroot/pull/754#discussion_r1300422285.

Can we add a tertiary build tree that GN can use to resolve rules/targets for third_party dependencies, and then move our third_party rules into the engine repository? Ideally, rules would still be resolvable in the same way they are in the `secondary` buildroot directory.

**Comment by chinmaygarde** [comment]
Closing due to https://github.com/flutter/buildroot/pull/754#issuecomment-1687088889
