### ISSUE TITLE
Flutter web, get generated elements from the DOM

### ISSUE THREAD

**Issue by leisnielcp-ks** [flutter/flutter#132904]
I am trying to retrieve input elements from the DOM in a Flutter Web app, but so far I have not been successful, and I'm not even sure if it can be achieved.

For example:

```
TextField(
  key: const Key('referenceNumber'),
  decoration: const InputDecoration(
    border: OutlineInputBorder(),
    labelText: 'Reference Number',
  ),
  onChanged: (text) {
    setState(() {
      referenceNumber = text;
    });
  },
),
```

Does Flutter generate an <input> element for this TextField widget?

In my Flutter-generated web app, I need to integrate a JavaScript library that requires the ability to identify the generated DOM elements.

**Comment by darshankawar** [comment]
@leisnielcp-ks 
When you say `retrieve input elements from the DOM`, are you looking to find some element via id which is assigned to a widget like TextField ?

**Comment by darshankawar** [comment]
Your case is probably same as https://github.com/flutter/flutter/issues/95624 for which the feedback was https://github.com/flutter/flutter/issues/95624#issuecomment-1006873329, that you can check and see if it helps to answer your question or not. For now based on it, I'll close it. If you disagree or think I misinterpreted the issue, write in comments and I'll reopen it.
