### ISSUE TITLE
[Impeller] Flutter 3.13.0 regression of box shadow from container with partial border radius drawn over scrollable

### ISSUE THREAD

**Issue by fangjue** [flutter/flutter#132936]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a Container with **box shadow** and bottom left border radius (actually any **partial border radius** reproduces the bug) at the top. Place a ListView below it with some simple text items. See sample code for details.

2. Run on iOS with impeller enabled and disabled and compare results.

```
flutter run --enable-impeller
flutter run --no-enable-impeller
```

3.  Scroll the list and observe the extra white background on the text 'item x' of the list when Impeller is used.

This bug does not reproduce on Flutter 3.10.6 on the same device. Also it does not reproduce on Android with Flutter 3.13.0 with the flag `--enable-impeller`. The border radius on the box shadowed container must be partial to reproduce the bug.

### Expected results

No extra white box should be drawn over the box shadow while scrolling the list.

### Actual results

Extra white box is drawn over the box shadow after the list is scrolled. If scrolled up for the first time, the extra white blinks.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Box shadow with impeller bug',
      home: Scaffold(
        appBar: PreferredSize(preferredSize: const Size.fromHeight(60), child: Container(
          decoration: const BoxDecoration(
            color: Colors.white, // Background color can be removed and this bug still reproduces.
            borderRadius: BorderRadius.only(bottomLeft: Radius.circular(30)), // BorderRadius.circular(30) does not reproduce the bug.
            boxShadow: [BoxShadow(color: Colors.black,blurRadius: 120)],
          ),
        )),
        body: ListView.builder(
          physics: const BouncingScrollPhysics(),
          itemBuilder: (context, index) => index < 100 ? Padding(padding: const EdgeInsets.all(16), child: Center(child: Text('item $index'))) : null
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/flutter/flutter/assets/4703033/7dbcb044-c5be-426a-8987-6917270b5bd5)

https://github.com/flutter/flutter/assets/4703033/7e63e979-aef3-4a9f-ac06-f98e419545e3

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.0, on macOS 12.6.1 21G217 darwin-x64, locale en-US)
    • Flutter version 3.13.0 on channel stable at /Users/jipeng/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (5 days ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/xxx/Library/Android/sdk/
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = /Users/xxx/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (3 available)
    • xxx (mobile) • xxx-xxx • ios            • iOS 15.6.1 19G82
    • macOS (desktop)     • macos                     • darwin-x64     • macOS 12.6.1 21G217 darwin-x64
    • Chrome (web)        • chrome                    • web-javascript • Google Chrome 116.0.5845.96

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by chinmaygarde** [comment]
cc @jonahwilliams

**Comment by fangjue** [comment]
I did a bisect between `$(git merge-base master 3.13.0)` and `$(git merge-base master 3.10.0)` ( e749db6f915c341d15b9cb81dc19bdc9e791c72f..bff6b93683de8be01d53a39b6183f230518541ac ), and reproduced the bug starting from e2ae260b429b91b496a1ae56432fa1801bcaa541. This is a Flutter Engine roll and the corresponding engine commit is flutter/engine@0c41b02cd5a641e42328403ed5a6e183c473c827.

**Comment by jonahwilliams** [comment]
The bounds computation in AIKS canvas is correct, and there is no incorrect culling before that point:

[VERBOSE-2:canvas.cc(167)] Draw Path Bounds: ((-1227, -1098), (2610, 1761))

So possibly something is going wrong with the coverage hint computation.

**Comment by jonahwilliams** [comment]
It looks like we clamp the X,Y of the coverage hint, and the resulting transform puts the RRect blur offscreen:

2:canvas.cc(167)] Draw Path Bounds: ((-1227, -1080), (2610, 1761))
[VERBOSE-2:gaussian_blur_filter_contents.cc(94)] Coverage hint: ((0, 0), (156, 2083))
[VERBOSE-2:gaussian_blur_filter_contents.cc(121)] ((0, 0), (156, 2083))

**Comment by jonahwilliams** [comment]
Seems like this isn't the issue after all, we're not actually clipping out the filter where I thought we were.

**Comment by jonahwilliams** [comment]
I think this is actually a clipping issue!

**Comment by jonahwilliams** [comment]
This works correctly when the border radius is uniform and/or there is no border radius as we're able to use the analytical solution and that is positioned correctly.

**Comment by jonahwilliams** [comment]
Okay, the _actual_ problem seems to be that we compute the coverage incorrectly, and as a result either cull or render incorrectly:


[VERBOSE-2:gaussian_blur_filter_contents.cc(363)] CHECK FILTER COVERAGE: ((-507, -409), (1170, 321))
[VERBOSE-2:gaussian_blur_filter_contents.cc(372)] Computed result: ((-867, -409), (1890, 321))

In this case we seem to either create a height that evaluates to 0 or is otherwise very small.

**Comment by jonahwilliams** [comment]
Here is an impeller playground that demontrates the issue:

```
TEST_P(AiksTest, BlurFilterWithNonZeroOriginRendersCorrectly) {
  Canvas canvas;
  //canvas.Translate({0, -400, 0});
  Paint paint;
  paint.mask_blur_descriptor = Paint::MaskBlurDescriptor{
      .style = FilterContents::BlurStyle::kNormal,
      .sigma = Radius{120},
  };
  paint.color = Color::Red();
  PathBuilder builder{};
  builder.AddRect(Rect::MakeLTRB(0, 0, 800, 800));
  canvas.DrawPath(builder.TakePath(), paint);

  ASSERT_TRUE(OpenPlaygroundHere(canvas.EndRecordingAsPicture()));
}
```

**Comment by BenjiFarquhar** [comment]
I have a few occurrences of this bug. It is nothing to do with uniformity for me. Any border radius will reproduce. 


https://github.com/flutter/flutter/assets/26356162/9c401ff5-3c8e-4006-8012-ca763bd70f07

There is the obvious top nav bar shadow. Then also take note of the scroll view card items, as they get near the top, the bottom shadow disappears. 

Then I have another page where the top nav bar doesn't have shadow on top of a google map:

<img width="1001" alt="Screenshot 2023-08-23 at 3 49 56 PM" src="https://github.com/flutter/flutter/assets/26356162/4711e5f3-a52e-420c-bb4b-dc64232939bd">

Only happens on Flutter 3.13, on iOS.

**Comment by chinmaygarde** [comment]
We discussed this in the Impeller sync today and decided to elevate priority. @bdero said he would take a closer look later today.

**Comment by bdero** [comment]
Will have a patch out for this today. There turned out to be a few overlapping problems here:
* The mask blur can get double-applied in some circumstances.
* One of the new coverage optimizations is interacting poorly with dirty regions. In the Gaussian Blur this optimization wasn't incorporating the full transform of the blur radius, causing the included blur region to wind up being too small on high DPI devices. I believe this is also the cause of the other issues we've seen come in. Going to cross reference.
* There's a texture coordinate mapping issue.

This is how it looks with 2 out of the 3 problems fixed:
![image](https://github.com/flutter/flutter/assets/919017/7e5c9c17-c9de-4dd9-bf91-4d6d7b990082)

Once problem 3 (the texture coordinate mapping issue) is fixed, there will be no visible banding. We can easily prevent issues like this from reoccurring by tracking a couple of new mask blur goldens.

**Comment by ldasilva-net** [comment]
This issue can be affect v3.10.7 too?
