### ISSUE TITLE
`TextField onSubmitted` not called when embeded inside an `AlertDialog`

### ISSUE THREAD

**Issue by mgenware** [flutter/flutter#132900]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Clone this fresh repo (created `flutter create` on 3.13 stable)
2. Click the '+', which shows a dialog with a `TextField`
3. Enter something and hit Enter key

### Expected results

`TextField.onSubmitted` should be called and the dialog should be dismissed

### Actual results

`TextField.onSubmitted` is not called

### Code sample

<details><summary>Code sample</summary>

https://github.com/mgenware/flutter-alert-text-submit-issue/blob/main/lib/text_field_alert.dart

The `TextField` is inside an `AlertDialog` along with a `StatefulBuilder` to manage state.

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/flutter/flutter/assets/11565096/72477e89-094b-4d96-bc67-d70801676d49)

Nothing happened when enter is hit.

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.0, on Microsoft Windows [Version 10.0.22621.2134], locale en-US)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.1)
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.81.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by SakshamSahu** [comment]
The onSubmitted callback should be assigned a function that is invoked when the user submits the text field, but in your code, you're passing a reference to the onOK function without calling it.

**Comment by hassanbileh** [comment]
You already have been given the solution, but to be specific replace this "onSubmitted: (value) => onOK" to "onSubmitted: (value) => onOK()".
