### ISSUE TITLE
flutter build failed with library in wrong format

### ISSUE THREAD

**Issue by jidezhanghh** [flutter/flutter#132926]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. On an Debian11(arm64) machine，install flutter through snap(because flutter_linux_3.13.0-stable.tar.xz only works on x86_64);
2. Go to project's source dir, run command: flutter build some_dir --debug -v，but build failed;
3. Try step 2 on another Debian11 machine(x86_64, with flutter installed through flutter_linux_3.13.0-stable.tar.xz)，everything is fine;

### Actual results

build failed, below is partial error log:
...
[   +1 ms] /snap/flutter/current/usr/bin/ld: pdfium-src/lib/libpdfium.so: error adding symbols: file in wrong format
[   +1 ms] clang: error: linker command failed with exit code 1 (use -v to see invocation)
...

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->
[   +1 ms] /snap/flutter/current/usr/bin/ld: pdfium-src/lib/libpdfium.so: error adding symbols: file in wrong format
[   +1 ms] clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.14.0-8.0.pre.3, on BrilliaOS 5.10.179.ft, locale zh_CN.UTF-8)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] Connected device (1 available)
[!] Network resources                               
    ✗ A cryptographic error occurred while checking "https://pub.dev/": Connection terminated during handshake
      You may be experiencing a man-in-the-middle attack, your network may be compromised, or you may have malware installed on your computer.
    ✗ A network error occurred while checking "https://maven.google.com/": Connection timed out

! Doctor found issues in 4 categories.
```

</details>

**Comment by huycozy** [comment]
Hi @jidezhanghh 
Does that mean the issue only appears on your arm64 machine with snap (it works as expected when installing Flutter manually)? And please provide the entire output of `flutter run -v` which contains crash stack trace as well. Thanks!

**Comment by jidezhanghh** [comment]
Hi @huycozy 
Thank you for your reply!
 I found that in an arm64 debian11 machine, even I build it with "fultter build linux --target-platform linux_arm64", the architecture of the download pdfium is still x64, I've tried both snap and "git clone" version(in stable branch), both failed with the same error. 

And I also found that the file "$HOME/.pub-cache/hosted/pub.dev/printing-5.11.0/linux/CMakeLists.txt" has wrong contents at line 20: set(PDFIUM_ARCH "x64" CACHE STRING "Architecture of pdfium used"), I changed it to: set(PDFIUM_ARCH "arm64" CACHE STRING "Architecture of pdfium used"), and remove build directory, then relaunch "fultter build linux --target-platform linux_arm64", it works! So I think the key point is why pdfium still x64(even arm64 is given)?

**Comment by huycozy** [comment]
Hi @jidezhanghh 
The issue seems to belong to 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/DavBfr/dart_pdf/issues) for better support there. Looks like the same issue here: https://github.com/DavBfr/dart_pdf/issues/1448, you can find there solutions if any.

Closing, as this isn't an issue with Flutter itself.
