### ISSUE TITLE
ImmediateMultiDragGestureRecognizer seems to use globalLocation only

### ISSUE THREAD

**Issue by VladimirDemirev** [flutter/flutter#132974]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Any use of ImmediateMultiDragGestureRecognizer where event handlers receive DragUpdateDetails. See the code example.

### Expected results

I would expect the 'details' variable (DragUpdateDetails) to have both localPostion and globalPostion populated correctly, instead - they both contain the same value which is globalPostion.

### Actual results

Both properties localPosition and globalPosition of 'details' have the same value, which corresponds to globalPosition.
This happens for any widget.

### Code sample

<details><summary>Code sample</summary>

```dart
ImmediateMultiDragGestureRecognizer: GestureRecognizerFactoryWithHandlers<ImmediateMultiDragGestureRecognizer>(
          () => ImmediateMultiDragGestureRecognizer(),
          (ImmediateMultiDragGestureRecognizer instance) {
            instance.onStart = (Offset offset) {
              final touch = Touch(
                offset,
                (details) => _update(details),
                (details) => _end(details),
              );
              
              return touch;
            };
          },
        )
```

</details>

### Screenshots or Video

the issue reported in 2018 at StackOverflow:

https://stackoverflow.com/questions/60117082/how-do-i-get-offset-from-the-correct-context-when-logging-touches-with-immediate/76947542

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by dam-ease** [comment]
Hi @VladimirDemirev. Thanks for filing this. I see there is a currently open issue describing this case https://github.com/flutter/flutter/issues/117146. Kindly comment, upvote and follow up on this issue for updates. Closing this in favour of the already open issue, if you disagree please comment and I'd reopen this.
