### ISSUE TITLE
Compiled with incompatible version of Kotlin

### ISSUE THREAD

**Issue by remsysinc** [flutter/flutter#132902]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Create new project with latest Flutter/Dart.  Add these plugins in pubspec.yaml and then build a project:

  device_info_plus: ^9.0.3
  package_info_plus: ^4.1.0
  url_launcher: ^6.1.12

### Expected results

APK build without error using command prompt and updated Kotlin.

### Actual results

Errors received during build command ("flutter build apk").  The APK does get built in the end, but these errors appeared after a "flutter upgrade" in the last week or so.  The following errors are from my experience and another independent user and his setup attempting to assist.  Hence, this is not just a local issue to me.

However, one thing to note... this error happens using the build in the command prompt (Windows 10).  When using Android Studio's "build" option AND having its settings for "kotlin compiler" set to "bundled (1.8.0-release-345)", the APK gets built without error.  Using AS Giraffe (Build #AI-223.8836.35.2231.10406996, built on June 29, 2023).

Errors on my computer ("myProject") and then "anotherUser":

e: C:/myProject/build/package_info_plus/.transforms/abc47a3830e3f326f11c2f9f898fde9f/transformed/out/jars/classes.jar!/META-INF/package_info_plus_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.

e: /anotherUser/.gradle/caches/transforms-3/9c9ab1a476c120097a79d748cec7161f/transformed/core-1.10.1/jars/classes.jar!/META-INF/core_release.kotlin_
module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: /anotherUser/.gradle/caches/modules-2/files-2.1/androidx.annotation/annotation-jvm/1.6.0/a7257339a052df0f91433cf9651231bbb802b502/annotation-jvm-
1.6.0.jar!/META-INF/annotation.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8
.0, expected version is 1.6.0.
e: /anotherUser/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.8.22/636bf8b320e7627482771bbac9ed7246773c02bd/kotlin-stdlib-
1.8.22.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metada
ta is 1.8.0, expected version is 1.6.0.
e: /anotherUser/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.8.22/636bf8b320e7627482771bbac9ed7246773c02bd/kotlin-stdlib-
1.8.22.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is
 1.8.0, expected version is 1.6.0.
e: /anotherUser/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.8.22/636bf8b320e7627482771bbac9ed7246773c02bd/kotlin-stdlib-
1.8.22.jar!/META-INF/kotlin-stdlib-jdk8.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metada
ta is 1.8.0, expected version is 1.6.0.
e: /anotherUser/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.8.22/1a8e3601703ae14bb58757ea6b2d8e8e5935a586/kotlin-
stdlib-common-1.8.22.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary versi
on of its metadata is 1.8.0, expected version is 1.6.0.

### Code sample

<details><summary>Code sample</summary>

```dart
  device_info_plus: ^9.0.3
  package_info_plus: ^4.1.0
  url_launcher: ^6.1.12
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

[log.txt](https://github.com/flutter/flutter/files/12386656/log.txt)

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
C:\temp>flutter doctor -v
[√] Flutter (Channel stable, 3.13.0, on Microsoft Windows [Version 10.0.19045.3324], locale en-US)
    • Flutter version 3.13.0 on channel stable at C:\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (4 days ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Mark\AppData\Local\Android\sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Visual Studio - develop Windows apps (Visual Studio Enterprise 2019 16.11.29)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    • Visual Studio Enterprise 2019 version 16.11.33927.289
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.81.1)
    • VS Code at C:\Users\Mark\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.0

[√] Connected device (1 available)
    • Windows (desktop) • windows • windows-x64 • Microsoft Windows [Version 10.0.19045.3324]

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by remsysinc** [comment]
SOLVED!!!  The solution at https://stackoverflow.com/a/72984766/1814785 took care of this.  It had nothing to do with the gradle setting after all.

**Comment by danagbemava-nc** [comment]
Closing this since the issue has been resolved on your end
