### ISSUE TITLE
when using material 3 with NestedScrollView the app stops

### ISSUE THREAD

**Issue by ANGEEEL7U7** [flutter/flutter#132909]
When using NestedScrollView with `Material 3`, the application crashes. I tried using `WidgetsBinding.instance!.addPostFrameCallback` and didn't get any results. I'm attempting to have the native scroll of Android 12 and use this widget for the app bar, but I've been without finding a solution for 4 days.

VIDEO

https://github.com/flutter/flutter/assets/82860569/cd15bed2-10fc-4582-83ac-ceac2642e591

CODE
![code](https://github.com/flutter/flutter/assets/82860569/2b4f1115-6e02-49ff-93e8-0b355c3668cf)

ERROR
![exception](https://github.com/flutter/flutter/assets/82860569/cf5aa5ad-e4f7-47a1-9d52-0d0016411d94)

FLUTTER DOCTOR -V
![flutter_doctor](https://github.com/flutter/flutter/assets/82860569/23b69de9-7e7e-4982-bee7-391fd17e1699)

**Comment by hagen00** [comment]
I'm experiencing the same problem on `3.13.0`. 

NestedScrollView with  headerSliverBuilder no longer scroll. This happens on an actual device and emulator. Downgrading to `3.10.6` fixes the problem.

**Comment by dam-ease** [comment]
Hi @ANGEEEL7U7. Thanks for filing this issue. I am able to reproduce this issue but there is a currently open issue describing this case. I'd be closing this in favor of https://github.com/flutter/flutter/issues/104798, kindly upvote, comment and follow up on this issue for updates. If you disagree, please comment and I'd reopen this.
Also, kindly refrain from posting pictures/screenshots if not necessary, copy and paste code samples and output of `flutter doctor -v`.
Thank you!
