### ISSUE TITLE
Share my VSCode extension  that can debug flutter engine in Andrroid Application

### ISSUE THREAD

**Issue by xiaoxiaowesley** [flutter/flutter#132929]
For a long time, the Flutter engine has been troublesome for debugging Android applications. 
So I wrote a vscode debugging extension myself, and I shared it hoping to help facilitate the debugging of Android applications.

 If possible, I would be happy to put it in the official debugging documentation and make it available to more people.

Here is my vscode estension : 

https://marketplace.visualstudio.com/items?itemName=seanxiaoxiang.android-flutter-engine-debugger

**Comment by dam-ease** [comment]
Hi @xiaoxiaowesley. Thanks for filing this. The VSCode plugin for flutter has a dedicated repo: https://github.com/Dart-Code/Flutter so I think you should file this issue [here](https://github.com/Dart-Code/Dart-Code/issues) for more insights.
I'd be closing this from here.

**Comment by xiaoxiaowesley** [comment]
> Hi @xiaoxiaowesley. Thanks for filing this. The VSCode plugin for Flutter has a dedicated repo: https://github.com/Dart-Code/Flutter so I think you should file this issue [here](https://github.com/Dart-Code/Dart-Code/issues) for more insights. I'd be closing this from here.

Hi, maybe there's something I didn't make clear here. Of course, I know that vscode has a flutter plugin, which is a plugin for developing flutter applications using dart. 

But my plugin did another thing which is used to debug the C++ code of Android debugging flutter engine. 
As far as I know, there is no better tool for debugging flutter engine c++ side code. In the official[ wiki documentation](https://github.com/flutter/flutter/wiki/Debugging-the-engine), the section of how to debug android applications is very simple.
