### ISSUE TITLE
router.routeInformationProvider.value.location does not update

### ISSUE THREAD

**Issue by turbobuilt** [flutter/flutter#132930]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

You make a simple go router.  Then you push some pages.  Then you try to get the current page when you are listening for IAP updates (because it has to be in a different listener).  Then you try to get the current page and it won't let you. It just says the first page and it's not reflective of the actual page.

final router = GoRouter(
  initialLocation: "/login",
  routes: [
    GoRoute(...

>> router.routeInformationProvider.value.location

This always just says "/login" for me no matter what page I'm on.

Thanks for the hard work you guys are amazing! (and girls)

### Expected results

Should tell you the actual path!

### Actual results

Just says the first (default) location

### Code sample

<details><summary>Code sample</summary>

```dart
router.routeInformationProvider.value.location
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
✓] Flutter (Channel stable, 3.10.6, on macOS 13.3 22E252 darwin-arm64, locale en-US)
    • Flutter version 3.10.6 on channel stable at /Users/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (6 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/dev/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (4 available)
    • iPhone (4) (mobile)        • 00008030-00051580222B802E            • ios            • iOS 16.5.1 20F75
    • iPhone 14 Pro Max (mobile) • 6A6A7235-32BA-4D4C-BDBB-6192F71E0FFC • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.3 22E252 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 115.0.5790.170

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by dam-ease** [comment]
Hi @turbobuilt. Thanks for filing this. Please can you provide us with a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code?

**Comment by turbobuilt** [comment]
Of course. Thank you so much for taking me seriously, I find it's kind of
hard to get started with new frameworks, but I always like to file bug
reports because I feel like it will help other noobs like me.
