### ISSUE TITLE
Requesting access to Android's "Send Feedback" API

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#133]
<a href="https://github.com/sethladd"><img src="https://avatars.githubusercontent.com/u/5479?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sethladd](https://github.com/sethladd)**
_Friday Aug 21, 2015 at 14:53 GMT_
_Originally opened as https://github.com/flutter/engine/issues/736_

---

The standard Feedback API from the Play services.

**Comment by eseidelGoogle** [comment]
I thought we had a separate bug about Google Feedback API, but I guess not.  Several of our customers have asked for this.

**Comment by eseidelGoogle** [comment]
customer: fast has successfully done this via the hello_services model, but we don't yet have a public example of this.

**Comment by Hixie** [comment]
@sethladd Please reopen if you think we should still track this.
