### ISSUE TITLE
when app is in background particular screen is not opening without context

### ISSUE THREAD

**Issue by navaghandabhi** [flutter/flutter#133040]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

void notificationTapBackground(NotificationResponse notificationResponse) async {
try {
WidgetsFlutterBinding.ensureInitialized();
await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
Map payload = json.decode(notificationResponse.payload!);
// ignore: avoid_print
print('notification(${notificationResponse.id}) action tapped: '
'${notificationResponse.actionId} with'
' payload: ${json.decode(notificationResponse.payload ?? "")}');
if (notificationResponse.actionId == 'Accept') {
log("Call Accepted");

///tryed [not working currentState getting null ]
// navigatorKey.currentState!.pushNamed(Routes.CALL_PICKUP_SCREEN,arguments: {"userData": payload["userData"], "callId": payload["callId"]});

///tryed [not working without context]
// Navigator.of(context).pushNamed(Routes.CALL_PICKUP_SCREEN,arguments: {"userData":
payload["userData"), "callId": payload["callId"]});

///tryed [not working]
// navigatorKey.currentState?.pushNamed(Routes.CALL_PICKUP_SCREEN, arguments: {"userData": payload["userData"], "callId": payload["callId"]});
} else if (notificationResponse.actionId == 'Reject') {
log("Call Rejected");

  FlutterLocalNotificationsPlugin().cancel(1); // Dismiss the notification
} else {
  ///other action
}
} catch (error) {
log("error on notification tap in background : $error");
}
}

also tried getx
// Get.to(() => AudioCallView(), arguments: {"userData": json.decode(remoteMessage.data["userData"]), "callId": remoteMessage.data["callId"]});

also tried method channel
await const MethodChannel('android_channel').invokeMethod("openCallPickUpScreen", {'userData': userData.toMap(), 'callId': callId});

how to resolve this and open perticular screen from background on click to notification button

### Proposal

i want to show call pickup screen when app is in background and notification renders

**Comment by dam-ease** [comment]
Hi @navaghandabhi. Thanks for filing this. When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly.
More specifically, please provide the information indicated below:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of flutter doctor -v
- Reproduction steps
Thank you!

**Comment by navaghandabhi** [comment]
void notificationTapBackground(NotificationResponse notificationResponse) async {
  try {
    WidgetsFlutterBinding.ensureInitialized();
    await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
    Map payload = json.decode(notificationResponse.payload!);
    // ignore: avoid_print
    print('notification(${notificationResponse.id}) action tapped: ${notificationResponse.actionId} with payload: ${json.decode(notificationResponse.payload ?? "")}');
    if (notificationResponse.actionId == 'Accept') {
      log("Call Accepted");
      // globalCallId = payload["callId"];
      // globalUserData = UserData.fromJson(json.decode(payload["userData"]));
      navigatorKey.currentState!.pushNamed(Routes.CALL_PICKUP_SCREEN, arguments: {"userData": UserData.fromJson(payload["userData"]), "callId": payload["callId"], "isPickup": false, "isFromCall": true, "isStartCall": true});
      // openActivityOnNotificationClick(UserData.fromJson(json.decode(payload["userData"])),payload["callId"]);
      // Navigator.of(context).pushNamed(Routes.CALL_PICKUP_SCREEN,arguments: {"userData": UserData.fromJson(payload["userData"]), "callId": payload["callId"], "isPickup": false, "isFromCall": true, "isStartCall": true});
      // navigatorKey.currentState?.pushNamed(Routes.CALL_PICKUP_SCREEN, arguments: {"userData": UserData.fromJson(payload["userData"]), "callId": payload["callId"], "isPickup": false, "isFromCall": true, "isStartCall": true});
      // Get.off(() => AudioCallView(callId: payload["callId"], userData: UserData.fromJson(payload["userData"]), isPickup: true, isStartCall: false, isFromCall: true));
    } else if (notificationResponse.actionId == 'Reject') {
      log("Call Rejected");
      FirebaseDatabase.instance.ref("CallHistory").child(payload["callId"]).update({"endAt": DateTime.now().toString(), "status": "Rejected"});
      FlutterLocalNotificationsPlugin().cancel(1); // Dismiss the notification
    } else {
      ///other action onn notification
    }
  } catch (error) {
    log("error on notification tap in background : $error");
  }
}

**Comment by navaghandabhi** [comment]
this is my code when user click on notification all things working but navigation to AudioCallView [ call pickup screen ]not working  when app is in background

**Comment by navaghandabhi** [comment]
hello @dam-ease Thanks for your response. i alrady commented there [issue link](https://github.com/MaikuB/flutter_local_notifications/issues/2075) but no response...
if you have any other solution using native code or any other resource for
how to opening  particular screen when app is in background at notification time
