### ISSUE TITLE
[go_router] GoRouterState doesn't carry data when the app is opened using deep link in Android

### ISSUE THREAD

**Issue by iLoveDocs** [flutter/flutter#133047]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Set up a deep link by following the instructions provided in this [Flutter documentation](https://docs.flutter.dev/cookbook/navigation/set-up-app-links).
2. Launch the application on an Android emulator (or physical device). 
3. Terminate the application (by pressing the stop button)
4. Execute the following command:
```
 adb shell 'am start -a android.intent.action.VIEW \
    -c android.intent.category.BROWSABLE \
    -d "http://example.com/details"' \
    com.example.foo
```

### Expected results

The console should print

```
matchedLocation = /details
```

### Actual results

The console prints

```
matchedLocation = /
```

### Minimum reproducible code:

```dart
void main() {
  final router = GoRouter(
    routes: [
      GoRoute(
        path: '/',
        builder: (_, __) => Scaffold(
          appBar: AppBar(title: const Text('Home Screen')),
        ),
        routes: [
          GoRoute(
            path: 'details',
            builder: (_, __) => Scaffold(
              appBar: AppBar(title: const Text('Details Screen')),
            ),
          ),
        ],
      ),
    ],
    redirect: (context, state) {
      print('matchedLocation = ${state.matchedLocation}');
      return null;
    },
  );

  runApp(MaterialApp.router(routerConfig: router));
}
```

### Version: 

```yaml
go_router: ^10.1.0
```

### More info:
**iOS Devices**: The app functions correctly in all scenarios, regardless of whether it is terminated or running (either in the background or foreground).
**Android Devices**: The app operates seamlessly when it's active (in either the background or foreground). However, issues arise when the app is in a terminated state.

I discovered that [related issues](https://github.com/flutter/flutter/issues/100624) have been addressed, but I'm unclear on the resolution.

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.8.0-13.0.pre.79, on macOS 13.3.1 22E261 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Community Edition (version 2022.3)
[✓] VS Code (version 1.80.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by dam-ease** [comment]
Hi @iLoveDocs. Thanks for filing this. From the closed issue you referenced, it seems to have been fixed with https://github.com/flutter/engine/commit/be57de6decff4ddaf6abbb318b1093620b417ee1. Can you upgrade to the latest master to confirm this?

**Comment by iLoveDocs** [comment]
@dam-ease, indeed, that solution worked. I apologize for my lack of familiarity with GitHub, which made it difficult for me to identify the branch where this issue was resolved. I mistakenly assumed that it was related to the `go_router` package.
