### ISSUE TITLE
High volume crash in url_launcher package: "Attempted to call Window.open with a null window."

### ISSUE THREAD

**Issue by jacobsimionato** [flutter/flutter#133023]
Copied from Google bug b/290500892

We're seeing a high volume crash in a google app that is occurring within the [url_launcher](https://github.com/flutter/packages/tree/main/packages/url_launcher/url_launcher
) package:
```
Translated error message:
   Attempted to call Window.open with a null window.
Deobfuscated stack trace:
  [Mapped Dart].wrapException(sdk/lib/_internal/js_runtime/lib/js_helper.dart:1195)
  [Mapped Dart].throwExpression(sdk/lib/_internal/js_runtime/lib/js_helper.dart:1235)
  [Mapped Dart].open(sdk/lib/html/dart2js/html_dart2js.dart:32167)
  [Mapped Dart].openNewWindow(url_launcher/web/lib/url_launcher_web.dart:67)
  [Mapped Dart].UrlLauncherPlugin.launch(url_launcher/web/lib/url_launcher_web.dart:87)
  [Mapped Dart].launchUrlString(dart/url_launcher/lib/src/url_launcher_string.dart:41)
  [Mapped Dart]._wrapJsFunctionForAsync(sdk/lib/_internal/js_runtime/lib/async_patch.dart:307)
  [Mapped Dart]._wrapJsFunctionForAsync.<anonymous>(sdk/lib/_internal/js_runtime/lib/async_patch.dart:332)
  [Mapped Dart]._asyncStartSync(sdk/lib/_internal/js_runtime/lib/async_patch.dart:237)
  [Mapped Dart].launchUrlString(dart/url_launcher/lib/src/url_launcher_string.dart:29)
  [Mapped Dart].launchUrl(dart/url_launcher/lib/src/url_launcher_uri.dart:58)
```

We don't have a repro, but this is affecting users over 1000 times per day, so we'd love any help or advice on the topic.

It's unclear why window could be null or what the right way of handling that is. If this is expected to happen in some circumstances, perhaps it could be caught in url_launcher_web?

**Comment by yjbanov** [comment]
In dart2js the code that calls `window.open` is here: https://cs.opensource.google/dart/sdk/+/master:sdk/lib/html/dart2js/html_dart2js.dart;l=32148-32166;drc=a0d8796c9441024640c6f81ffbf466cd3555627a

It chooses between `_open2` and `_open3`, but in both cases the receiver is `this`. In Dart `this` is guaranteed to never be null. In JS it can be null in some situations. Since the code is right on the JS-interop boundary I wonder if there's some violation of soundness or a compiler bug that lead to `this` becoming null. Adding `dependency: dart` for assistance.

**Comment by yjbanov** [comment]
Here's a recent change that looks related: https://cs.opensource.google/dart/sdk/+/b859e0090801eaa6e4934feba6a55ca4140a8101

**Comment by yjbanov** [comment]
Also, `window.open` does not guarantee a non-null return value: https://stackoverflow.com/questions/18401331/window-open-returns-null-and-fails-in-inline-script-but-works-from-console. So there seems to be an issue in the `dart:html` API.

**Comment by nshahan** [comment]
cc @srujzs 

Your change was already flagged and I just want to also highlight this related issue that is still open.
https://github.com/dart-lang/sdk/issues/52685

**Comment by srujzs** [comment]
I think this was discussed in an internal bug/discussion and was resolved. There was a change to the `dart:html` API to make inevitable JS errors materialize as Dart errors instead. Feel free to reopen if there needs to be more discussion or if I missed anything.
