### ISSUE TITLE
[devicelab/infra] update cocoapods on devicelab machines to 1.13.0

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#133096]
See https://github.com/flutter/flutter/commit/5e9e959d570c2924430d9d9c12b27742a44af3eb

flutter/gallery (and potentially other repos?) are now using cocoapods 1.12. Running with outdated cocoapods is causing errors as 1.11 does not seem forward compatible with them. Updating to 1.12 should be safe?

**Comment by drewroengoogle** [comment]
@yusuf-goog Are you the right person to assign this to? What exactly is needed to update cocoapods on devicelab machines?

**Comment by yusuf-goog** [comment]
@jonahwilliams does this update need to be made only on the devicelab macs, or our "VM" fleet as well?

**Comment by jonahwilliams** [comment]
To unblock this particular test, only the devicelab macs need to be updated.

**Comment by vashworth** [comment]
Yes, so there was this issue: https://github.com/flutter/flutter/issues/122057

It sounded like the fix was going to be a new ruby/gems CIPD package

**Comment by yusuf-goog** [comment]
referencing go/flutter-ruby

@XilaiZhang do you have instructions for : go/flutter-ruby#step-eight-codesigning

**Comment by XilaiZhang** [comment]
> referencing go/flutter-ruby
> 
> @XilaiZhang do you have instructions for : go/flutter-ruby#step-eight-codesigning

umm good point, after integrating codesigning tool to dart internal, i don't think we have a tool to sign a customized bundle anymore.

**Comment by godofredoc** [comment]
We don't need a tool, just a couple of commands and the proper certificates.  @XilaiZhang can you please share the command the tool executes?

Please also note that if updating cocoapods and the ruby bundles you'll need to create packages for x64 and arm64 and validate with all the tests before updating the references to the cipd packages in .ci.yaml

**Comment by drewroengoogle** [comment]
Removing from ticket queue as this is not actively causing a breakage, but marking P1

**Comment by vashworth** [comment]
Umbrella bug for updating the ruby self contained package: https://github.com/flutter/flutter/issues/136377

**Comment by godofredoc** [comment]
This is complete now.
