### ISSUE TITLE
<flutter web> (iOS 15.6)     Use ui.platformViewRegistry.registerViewFactory to access iframe, enter the secondary page and cannot return to the previous level

### ISSUE THREAD

**Issue by iamzhibo** [flutter/flutter#133019]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Use an iframe to load the url. Enter iframe, exit iframe. In the iframe again, enter the secondary page. Secondary page click returns invalid.

### Expected results

The secondary page clicks to return to invalid

### Actual results

can return to the previous level

### Code sample

ui.platformViewRegistry.registerViewFactory(
        _localVideoPlayerId,
        (int viewId) => IFrameElement()
          ..allowFullscreen = true
          ..height = '100%'
          ..src = 'url'
          ..style.border = 'none');

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by iamzhibo** [comment]
flutter code
<img width="730" alt="截屏2023-08-22 上午11 09 16" src="https://github.com/flutter/flutter/assets/118972991/b9a44af3-98ee-4a74-9d95-c9dc24909886">


h5 code index.html
<img width="1164" alt="截屏2023-08-22 上午11 03 36" src="https://github.com/flutter/flutter/assets/118972991/51153edd-7941-43b6-a362-67dc07706e27">
index1.html
<img width="1136" alt="截屏2023-08-22 上午11 07 39" src="https://github.com/flutter/flutter/assets/118972991/beda2597-bc03-4116-9577-d18e7a907f87">

**Comment by iamzhibo** [comment]
Actual results

https://github.com/flutter/flutter/assets/118972991/a12d213a-b5e4-40f7-a44d-b2a69d818aba

**Comment by iamzhibo** [comment]
flutter

**Comment by iamzhibo** [comment]
flutter code：
  Widget build(BuildContext context) {
    ui.platformViewRegistry.registerViewFactory(
       'iframe',
        (int viewId) => IFrameElement()
          ..allowFullscreen = true
          ..height = '100%'
          ..src = 'h5url'
          ..style.border = 'none');
    // ui.platformViewRegistry.registerViewFactory(_localVideoPlayerId, (int viewId) {
    //   return H5PlayerElement().create();
    // });
    return Scaffold(
        appBar: AppBar(
          title: const Text('WebViewX Page'),
        ),
        body: Center(
          child: Container(
            color: Colors.red,
            // padding: const EdgeInsets.only(left: 16, right: 16),
            height: 500,
            child: HtmlElementView(viewType:'iframe'),
          ),
        ));
  }

h5 index.html ：

<body>
  <div class="liveH5-page">
    <a href="./index1.html">进入二级页A</a>

    <br>
    <br>
    <a href="./index2.html">进入二级页B</a>
  </div>
</body>

secondary page ：

<body>
  <div class="liveH5-page">
    <div onclick="goback()">返回上一级</div>
  </div>
</body>
<script>
  function goback(){
    history.go(-1)
  }
</script>

**Comment by huycozy** [comment]
Could you share the entire sample code in a zip file or GitHub repository? It will be easier for us to replicate this issue by just downloading/cloning it and make sure the code is consistent.

**Comment by huycozy** [comment]
Thanks for that but your sample code is still not complete as it has undefined classes and single `html` files. I'm not sure how it can be embedded into Flutter so please provide an entire sample code that is runnable along with detailed steps to reproduce the issue.

**Comment by iamzhibo** [comment]
Deploy html online and embed url address

**Comment by huycozy** [comment]
Without detailed information, I'm unfortunately not sure how to resolve this issue. Please try to provide all information indicated [above](https://github.com/flutter/flutter/issues/133019#issuecomment-1687859261) so that we can verify this issue properly.

**Comment by iamzhibo** [comment]
Deploy an h5 service. For example, 192.168.31:8080. Import this url with iframe

**Comment by huycozy** [comment]
I can manage to run it now with the updated sample code below. 

### Reproduction steps
1. Deploy the HTML web at `html.zip` below. You will have a local site, for eg: `192.168.1.2:8001`

2. Open `repro_web_133019.zip` below, then update `src` in `main.dart` to the 1st site above:

```dart
  uiWeb.platformViewRegistry.registerViewFactory(
      _localVideoPlayerId,
      (int viewId) => IFrameElement()
        ..allowFullscreen = true
        ..height = '100%'
        ..src = 'http://192.168.1.2:8001'
        ..style.border = 'none');
```

Then deploy Flutter web to a site, for eg: `192.168.1.2:8002`. 

3. Open Flutter site (`192.168.1.2:8002`) on Safari browser on iPhone. 

4. Navigate to the 2nd page by FAB button > Tap on one of two items there (A or B). Once you are on page A/B (corresponding to `index1.html`/`index2.html`), tap on the text to get back > Back to the 1st page by AppBar back button.

5. Repeat step 4 and notice you can not back to `index.html` page from page A/B (`index1.html`/`index2.html`) in second time test.

### Actual result

- Can not back to `index.html` page from page A/B (`index1.html`/`index2.html`) in second time test. But if I press twice on the text, it will navigate to the 1st page in Flutter app. (let's watch video below for details)

- The issue is only reproducible on `iOS 15.7.2` but works as expected on `iOS 16.4`. And it doesn't happen on Android browser.

- Observing Safari console log, I notice below error log


<details>
<summary>Error log from Safari</summary>

```console
[Error] TypeError: null is not an object (evaluating 's.toString')
	vv (main.dart.js:24377)
	(anonymous function) (main.dart.js:4388)
	$1 (main.dart.js:34332)
	afA (main.dart.js:4190)
	aij (main.dart.js:7323)
	(anonymous function) (main.dart.js:7319)
```
</details>

<details>
<summary>Demo video</summary>

https://github.com/flutter/flutter/assets/104349824/e3de296b-6063-470e-b761-bcaa6b69a383

</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.13.1, on macOS 13.5 22G74 darwin-x64, locale en-VN)
    • Flutter version 3.13.1 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e1e47221e8 (23 hours ago), 2023-08-22 21:43:18 -0700
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • iPhone (mobile) • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.7.2 19H218
    • macOS (desktop) • macos                                    • darwin-x64     • macOS 13.5 22G74 darwin-x64
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 116.0.5845.96

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.14.0-9.0.pre.86, on macOS 13.5 22G74 darwin-x64, locale en-VN)
    • Flutter version 3.14.0-9.0.pre.86 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 22a61b947f (4 minutes ago), 2023-08-24 21:26:56 -0700
    • Engine revision 1382d6d794
    • Dart version 3.2.0 (build 3.2.0-97.0.dev)
    • DevTools version 2.26.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.5 22G74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.110

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

[html.zip](https://github.com/flutter/flutter/files/12436150/html.zip)
[repro_web_133019.zip](https://github.com/flutter/flutter/files/12436151/repro_web_133019.zip)

**Comment by iamzhibo** [comment]
Flutter (Channel stable, 3.7.12, on Mac OS X 10.15.7 19H2 darwin-x64, locale zh-Hans-US)
    • Flutter version 3.7.12 on channel stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (4 个月前), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[!] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 12A7403
    ✗ Flutter requires Xcode 13 or higher.
      Download the latest version or update via the Mac App Store.
    ! CocoaPods 1.10.1 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 201.9380

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.3)
    • IntelliJ at /Downloads/Enigma/IntelliJ IDEA/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 201.9380

[✓] VS Code (version 1.81.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

**Comment by iamzhibo** [comment]
Can you fix this problem?
