### ISSUE TITLE
[CP] SliverMainAxisGroup overflow fix

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#133058]
### Issue Link

https://github.com/flutter/flutter/issues/132788

### Commit Hash

a5b06f1

### Target

stable

### PR Link

https://github.com/flutter/flutter/pull/133057

### Changelog Description

This fixes a visual overflow caused by SliverMainAxisGroup due to the clip behavior of the viewport not being applied in some cases.

### Impacted Users

Everyone using SliverMainAxisGroup

### Impact Description

https://github.com/flutter/flutter/assets/906564/1ea4b59a-32a9-4515-a6b3-9adc75970f03

This issue caused the content of the ScrollView to overflow outside of the bounds of the viewport.

### Workaround

Yes, placing a clip around the CustomScrollView is a workaround.

### Risk

low

### Test Coverage

yes

### Validation Steps

1. Run this code
2. Observe no overflowing content outside of the blue border.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Material(
        color: Colors.red,
        child: Padding(
          padding: const EdgeInsets.symmetric(vertical: 128.0),
          child: DecoratedBox(
            position: DecorationPosition.foreground,
            decoration: BoxDecoration(
              border: Border.all(color: Colors.blue, width: 3.0),
            ),
            child: CustomScrollView(
              clipBehavior: Clip.hardEdge, // default value
              slivers: [
                SliverMainAxisGroup(
                  slivers: [
                    const SliverToBoxAdapter(
                      child: Material(
                        child: Padding(
                          padding: EdgeInsets.symmetric(vertical: 8.0, horizontal: 16.0),
                          child: Text('Heading'),
                        ),
                      ),
                    ),
                    SliverList.builder(
                      itemBuilder: (BuildContext context, int index) {
                        return Material(
                          child: ListTile(
                            title: Text('Item #$index'),
                          ),
                        );
                      },
                    ),
                  ],
                ),
              ],
            ),
          ),
        ),
      ),
    ),
  );
}
```

**Comment by CaseyHillers** [comment]
@HansMuller can you review this CP request? If it looks good to you, add the "cp: approved" label.
