### ISSUE TITLE
Building for the Web.  Not loading PNG assets

### ISSUE THREAD

**Issue by WorikQCI** [flutter/flutter#133008]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

The project I am working on has several PNG assets, but none of them are displaying when the code is built for, and deployed on, the Web.

On examination of the browser Network Tab, one of the assets is being loaded.  (It is one we are not using yet).  None of the others are.

I only see this problem running on a cloud server which loads the flutter web app via an iframe created in JavaScript.  Loading it on a local server has no problems.

The local server is served using: `http://localhost:8080/my_app/` and loads an index.html that has an iframe with the web app in it.

On the server that does not work (I am not in complete control of this server as will become apparent below):

* It is HTTPS
* It is using a self signed certificate that has a host definition that does not match the server URL
* There is some sort of authentication (username/password)
* The loading is done via JavaScript

```
    this.iframe = document.createElement("iframe");
    this.iframe.setAttribute('src', '/<path>/index.html');
    this.container.appendChild(this.iframe);
```

If it were not for the fact that one of the assets is loading, I would not be bothering you good people with an issue.  The asset that does load is defined differently from the ones that do not:

* Given two assets, one "foo.png" and another :bar.png".  
* "foo.png" loads (HTTP status 200 in network tab)
* "bar.png" does not appear in the network tab
* In code "foo.png" is used thusly:
```
  static loadAssets() async {
    QCIConstants.fooImage = await getUiImage('lib/assets/foo.png');
  }
```
* "bar.png" like this:
`const AssetImage('lib/assets/bar.png'),`

Is this expected behaviour?

Is it worth building a small example App (free from IP issues) that demonstrates this?

Some more details:
* The Pubspec,yml looks correct to me.  The assets are specified relative to the Pubspec.yml file
* All our fonts are loading correctly
`textStyle = const TextStyle(fontSize: 36, fontWeight: FontWeight.bold, fontFamily: "opensans");`
```
  fonts:
    - family: opensans-bold
      fonts:
        - asset: lib/fonts/opensans-bold.ttf
```

### Expected results

Described above

### Actual results

Described above

### Code sample

<details><summary>Code sample</summary>

```dart
Above
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
% flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.4 22F66 darwin-arm64, locale en-AU)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.81.0)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 2 categories.

```

</details>

**Comment by WorikQCI** [comment]
Ooops.

I am not the autthor of the UI code in our system and it shows!

Th efunction `getUIImage(..)` is ne of ours and is:

```
Future<ui.Image?> getUiImage(
    String assetPath) async {
  try {
    /// load the asset from the rootBundle (AssetBundle)
    final ByteData assetImageByteData = await rootBundle.load(assetPath);
    final codec = await ui.instantiateImageCodec(
        assetImageByteData.buffer.asUint8List());
    ui.Image image = (await codec.getNextFrame()).image;

    return image;
  } catch (e) {
    throw somerror
  }
}
```

**Comment by WorikQCI** [comment]
Some more information:

Examining the console logs more carefully I see this error.  Apart from the loading of assets the Flutter application is performing normally:

```
Exception while loading service worker: DOMException: Failed to register a ServiceWorker for scope ('https://<path to app>/') with script ('https://<path to app>/flutter_service_worker.js?v=2137097228'): An SSL certificate error occurred when fetching the script
```

**Comment by dam-ease** [comment]
Hi @WorikQCI. Thanks for filing this issue. Yes. please can you create a small example app that has a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code?

**Comment by WorikQCI** [comment]
Thank you for your attention

I have not got the chance right now.  Others in the company think they have different solutions.  If I get the chance to work on this some more I will create a small app to demonstrate this problem.

**Comment by WorikQCI** [comment]
Sorry.  I have not had  the time to address this.  I will ensure I have an example if I raise this again.

**Comment by WorikQCI** [comment]
CLosing as I cannot provide the information.
