### ISSUE TITLE
firebase-get-to-know-flutter#8: Code is still using undefined ApplicationLoginState

### ISSUE THREAD

**Issue by natrok** [flutter/flutter#133082]
In the step 2 of step 10 there is an enum that was not created in the tutorial: 

ApplicationLoginState
_loginState = ApplicationLoginState.loggedOut; 

 had to look at the source code to figure out what was wrong, but it's not always trivial.

https://firebase.google.com/codelabs/firebase-get-to-know-flutter?hl=es-419#8

**Comment by huycozy** [comment]
Thanks for the report. Compared to [sample code](https://github.com/flutter/codelabs/blob/6f330ceb6b1cd16b4f392aaf92eefe0722a21e8c/firebase-get-to-know-flutter/step_09/lib/app_state.dart#L99C8-L101) in GitHub repository, looks like it is changed to use a bool variable (`_loggedIn`) instead:

```dart
... 
 _loggedIn = true;
  _emailVerified = user.emailVerified;
  _guestBookSubscription = FirebaseFirestore.instance
...
```

/cc @domesticmouse

**Comment by domesticmouse** [comment]
I believe this is now fixed.
