### ISSUE TITLE
Tool should check if the android sdkmanager is in the path

### ISSUE THREAD

**Issue by bramp** [flutter/flutter#133063]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

On my mac, I installed Android's sdkmanager via a [Homebrew cask](https://formulae.brew.sh/cask/android-commandlinetools) (which is my preferred way to keep my software up to date). However, Flutter seems to assume the sdkmanager is in a specific Android SDK directory, and does not search the path for the binary.

1. Buy a Mac
2. Install sdkmanager with:
   `brew install --cask android-commandlinetools`
3. Run:

```
$ flutter doctor
 Doctor summary (to see all details, run flutter doctor -v):
 [✓] Flutter (Channel stable, 3.13.0, on macOS 13.5 22G74 darwin-arm64, locale en-GB)
 [!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
     ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

$ flutter doctor --android-licenses
 Android sdkmanager not found. Update to the latest Android SDK and ensure that the cmdline-tools are installed to resolve this.
```

You get the error `Android sdkmanager not found.`. However:

```
$ which sdkmanager
/opt/homebrew/bin/sdkmanager

$ sdkmanager --version
11.0
```

### Actual results

Flutter does not find `sdkmanager` on the path, instead reading [android_workflow.dart#L422-L428](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_workflow.dart#L422-L428) it seems to assume its within the the Android SDK directory.

I did fix this, by opening Android Studio, and installing "Android SDK Command-line tools" there.

**Since https://developer.android.com/tools does provide the tools as separate downloads (which is what homebrew seems to be using), should this configuration work?**

### Logs

See above

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

After I fixed the issue:

```console

❯ flutter doctor -v
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.5 22G74 darwin-arm64, locale en-GB)
    • Flutter version 3.13.0 on channel stable at /opt/homebrew/Caskroom/flutter/3.10.6/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (7 days ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/bramp/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 14 (API 34) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.5 22G74 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 116.0.5845.96

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @bramp, you can manually set the directory for the android SDK for the flutter tool. See https://stackoverflow.com/a/52926825. 

Did you run into any issues using the command in the answer linked above?

**Comment by bramp** [comment]
Flutter finds the Android SDK fine, I'm just pointing out, that I don't have command line tools installed there, instead they are being managed by homebrew that places them in a different directory.

```
$ flutter doctor
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/bramp/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.
```

```
$ which sdkmanager
/opt/homebrew/bin/sdkmanager

$ readlink /opt/homebrew/bin/sdkmanager
/opt/homebrew/share/android-commandlinetools/cmdline-tools/latest/bin/sdkmanager
```

So really I need two paths, one path for Android SDK, and one path for cmdline-tools.  Maybe there is no good reason to have them in two different places, other than they can be downloaded/installed independently, so I think it's a assumption that they co-exist.

**Comment by danagbemava-nc** [comment]
Yes, I believe the tool assumes they co-exist because that is the default. When setting up Flutter, most people leave that to Android Studio to manage. 

If I am understanding you correctly, do you want flutter to check if the command-line tools are in the PATH or maybe set via environment variables?

**Comment by bramp** [comment]
Yes I was looking for one of two outcomes.

1) Tell me that my setup is unsupported
Or
2) Change the flutter tools to find sdkmanager in the path (in addition to in the SDK).

Btw, when I recently installed Android Studio it did not come with sdkmanager by default, until I ticked the 'Android SDK Command-line tools' box to download. However I encountered the "Android sdkmanager not found" error, so I googled "Homebrew sdkmanager" and that led me to installing https://formulae.brew.sh/cask/android-commandlinetools.

So maybe a 3rd option

3) Update the error to point folks to the Android Studio way to install sdkmanager

**Comment by danagbemava-nc** [comment]
Thanks for the info. 
Possibly related https://github.com/flutter/flutter/issues/116434

**Comment by camsim99** [comment]
@christopherfujino Just FYI, you may want to close this as a won't fix.

**Comment by christopherfujino** [comment]
> 1. Tell me that my setup is unsupported

I would say your setup is unsupported :). We "officially" require Android Studio, and for you to install the Android SDK and command line tools via Android Studio. Not because this is the only way building flutter apps for android work, but because it simplifies the already complicated matrix of finding and using all these tools, and ensuring they are all of compatible versions.

If you **know what you are doing**, I have no personal issue with your workflow, but I don't think we should go out of our way to ensure the helper `flutter doctor --android-licenses` supports this workflow. It's basically a helper for users who don't know what `sdkmanager` is run `sdkmanager --licenses`: https://github.com/christopherfujino/flutter/blob/fix-version-format-exception/packages/flutter_tools/lib/src/android/android_workflow.dart#L374. You can run this manually from the terminal and hack away.

**Comment by bramp** [comment]
Ok thanks for your update. Unsupported sounds good.
