### ISSUE TITLE
Video example in gallery shows black square while loading, unclear what is happening

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#13304]
In the video example of the gallery, we see two black squares while video is loading, for approx 2 seconds. This can be confusing, as it's not clear what is happening while the video is being loaded/buffered.

Strawman proposal: show a spinner in the video player to indicate the video is loading/buffering.

**Comment by sethladd** [comment]
cc @sigurdm @mit-mit

**Comment by mit-mit** [comment]
For inspiration: https://material.io/guidelines/components/progress-activity.html#progress-activity-types-of-indicators

"Circular indeterminate" might work well
