### ISSUE TITLE
Desktop multi-window support

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#133079]
### Document Link

https://flutter.dev/go/desktop-multi-window-support

### What problem are you solving?

In order to implement many desirable features on desktop platforms, it is necessary to be able to open and manage multiple window contexts. This document describes the API and mechanisms for that.

**Comment by gspencergoog** [comment]
This design doc is now out of date: the described changes were made a long time ago, and have been superseded by updated designs and implementations.
