### ISSUE TITLE
Flutter has stopped working after upgrade

### ISSUE THREAD

**Issue by ashtouch007** [flutter/flutter#13306]
I tried to show a link in a new app by following the simple instructions here -
[https://flutter.io/using-packages/#url-example](https://flutter.io/using-packages/#url-example)

After replacing the code in pubspec.yaml as instructed and clicking on "Packages get" on InelliJ, I got this error message:

```console
Error on line 4, column 14 of pubspec.yaml: Mapping values are not allowed here. Did you miss a colon earlier?
```
I tried adjusting the indentation but nothing helped.

I then clicked "Packages upgrade" and eventually "Flutter upgrade", and things got even worse.
Projects that used to work didn't run anymore and even trying to compile a completely new project ended up with error messages.
I than deleted the cache dir as was suggested somewhere and ended up where I am now.

Running Flutter doctor now I get these error messages:

```console
    • Unable to locate Android NDK.
      
    • Unable to locate compiler in Android NDK.
```

**Comment by ashtouch007** [comment]
And when I try to run a completely new project this is what I get:

`Launching lib\main.dart on SM G930F in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Failed to run the Flutter compiler. Exit code: -1073741795

FAILURE: Build failed with an exception.

* Where:
Script 'C:\git\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 361

* What went wrong:
Execution failed for task ':app:flutterDependenciesDebug'.
> Process 'command 'C:\git\flutter\bin\flutter.bat'' finished with non-zero exit value -1073741795

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Finished with error: Gradle build failed: 1
`

**Comment by eseidelGoogle** [comment]
FYI @goderbauer @bkonyi

**Comment by ride4sun** [comment]
I did see that as well:
    • Unable to locate Android NDK.
    • Unable to locate compiler in Android NDK.

I also get errors when I try to run the stock example under flutter. All tools are updated.
I was able to create  and run a brand new app under Android Studio. 

I am not sure its related but this is the error I get when I get packaged in the stock example:
C:\sdks\flutter\bin\flutter.bat --no-color packages get
Running "flutter packages get" in stocks...
Incompatible version constraints on quiver:
- flutter_test 0.0.16 depends on version 0.26.0
- stocks depends on version 0.26.2
---- Log transcript ----
FINE: Pub 1.25.0-dev.11.0
IO  : Spawning "cmd /c ver" in C:\Projects\flutter\examples\stocks\.
IO  : Finished ver. Exit code 0.
    | stdout:
    | | 
    | | Microsoft Windows [Version 10.0.16299.98]
    | Nothing output on stderr.
MSG : Resolving dependencies...
SLVR: Solving dependencies: 
....
....
....



Flutter Version:
C:\Users\ride4\AndroidStudioProjects\flutter_app2>flutter doctor
[√] Flutter (on Microsoft Windows [Version 10.0.16299.98], locale en-US, channel alpha)
    • Flutter at c:\sdks\flutter
    • Framework revision d957c8f040 (3 days ago), 2017-11-30 13:29:59 -0800
    • Engine revision 77d8acb9be
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-dev.9.0

[√] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at C:\Users\ride4\AppData\Local\Android\sdk
    • Unable to locate Android NDK.

    • Unable to locate compiler in Android NDK.

    • Platform android-27, build-tools 27.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 19.1
    • Dart plugin version 172.4343.25

[√] Connected devices
    • None

**Comment by goderbauer** [comment]
You can ignore the following two lines in `flutter doctor`

```
• Unable to locate Android NDK.
• Unable to locate compiler in Android NDK.
```

Android NDK is not required to run flutter apps, and we are working on making that clear in `flutter doctor` (see https://github.com/flutter/flutter/pull/12788#pullrequestreview-80320467, @mkustermann).

**Comment by goderbauer** [comment]
@ashtouch007 `flutter run` works for me on an app I just created with `flutter create`. There is probably something else misconfigured on your system. Can you post the full output of `flutter doctor`? It would also be hellpful if you post the full content of the `pubspec.yaml` that didn't work for you when you added the `url_launcher` plugin.

**Comment by goderbauer** [comment]
@ride4sun are you sure you are on the latest alpha? In the source stocks depends on quiver 0.26.0 (https://github.com/flutter/flutter/blob/alpha/examples/stocks/pubspec.yaml#L45) just like flutter_test does (https://github.com/flutter/flutter/blob/alpha/packages/flutter_test/pubspec.yaml#L12). There shouldn't be a version conflict and on my system it works. You can try deleting the `.packages` file and it should get re-generated the next time you run the stocks app.

If the problem continues to exist: Please file a new bug because I think this is unrelated to the issue discussed here.

**Comment by ashtouch007** [comment]
@goderbauer 
 full output of flutter doctor:
'C:\git\flutter\bin\flutter.bat --no-color doctor
[√] Flutter (on Microsoft Windows [Version 6.3.9600], locale he-IL, channel alpha)
    • Flutter at C:\git\flutter
    • Framework revision d957c8f040 (4 days ago), 2017-11-30 13:29:59 -0800
    • Engine revision 77d8acb9be
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-dev.9.0

[√] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at C:\Users\amitsh\AppData\Local\Android\sdk
    • Unable to locate Android NDK.
      
    • Unable to locate compiler in Android NDK.
      
    • Platform android-27, build-tools 27.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 19.1
    • Dart plugin version 172.4343.25

[√] Connected devices
    • SM G930F • ce01171128360c1a02 • android-arm • Android 7.0 (API 24)

Process finished with exit code 0'

Full content of the pubspec.yaml that didn't work when I added the url_launcher plugin:

'name: launchdemo
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
'

And when running I get (as with every app I run, even a new one):

'Launching lib\main.dart on SM G930F in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Failed to run the Flutter compiler. Exit code: -1073741795

FAILURE: Build failed with an exception.

* Where:
Script 'C:\git\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 361

* What went wrong:
Execution failed for task ':app:flutterDependenciesDebug'.
> Process 'command 'C:\git\flutter\bin\flutter.bat'' finished with non-zero exit value -1073741795

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Finished with error: Gradle build failed: 1
'

I've only been running things from the IDE. Not sure where to run commands from.
I'll get into it tomorrow if necessary.
Thanks

**Comment by goderbauer** [comment]
You should probably update to the latest url_launcher plugin (version 1.0.3, see https://pub.dartlang.org/packages/url_launcher#pub-pkg-tab-installing). I am not sure how well the old version you specified in your `pubspec.yaml` is working with the latest flutter version.

To run with `-v`: Open PowerShell and cd into the directory of your app. Then run `C:\git\flutter\bin\flutter.bat run -v` in there.

**Comment by ashtouch007** [comment]
OK, managed to create a new project with 'flutter create'.
When I run it I get a VERY long output, some of it already out of the shell window and can't be copied.
Here's the last part, which shows problems:

'[  +66 ms] Building APK
[ +361 ms] Running 'gradlew assembleDebug'...
[   +5 ms] [android\] C:\Users\amitsh\IdeaProjects\newproject\android\gradlew.ba
t -Ptarget=C:\Users\amitsh\IdeaProjects\newproject\lib/main.dart assembleDebug
[+3406 ms] NDK is missing a "platforms" directory.
[ +113 ms] If you are using NDK, verify the ndk.dir is set to a valid NDK direct
ory.  It is currently set to C:\Users\amitsh\AppData\Local\Android\sdk\ndk-bundl
e.
[   +5 ms] If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOM
E or local.properties to remove this warning.
[ +428 ms] Incremental java compilation is an incubating feature.
[+4572 ms] :app:flutterBuildX86Jar
[  +17 ms] :app:preBuild UP-TO-DATE
[   +3 ms] :app:preDebugBuild UP-TO-DATE
[   +5 ms] :app:checkDebugManifest
[   +6 ms] :app:prepareDebugDependencies
[  +42 ms] :app:compileDebugAidl
[  +37 ms] :app:compileDebugRenderscript
[ +121 ms] :app:generateDebugBuildConfig
[+2094 ms] Failed to run the Flutter compiler. Exit code: -1073741795
[  +39 ms] :app:flutterDependenciesDebug FAILED
[  +33 ms] FAILURE: Build failed with an exception.
[  +47 ms] * Where:
[   +1 ms] Script 'C:\git\flutter\packages\flutter_tools\gradle\flutter.gradle'
line: 361
[   +2 ms] * What went wrong:
[   +1 ms] Execution failed for task ':app:flutterDependenciesDebug'.
[   +1 ms] > Process 'command 'C:\git\flutter\bin\flutter.bat'' finished with no
n-zero exit value -1073741795
[   +2 ms] * Try:
[   +1 ms] Run with --stacktrace option to get the stack trace. Run with --info
or --debug option to get more log output.
[   +2 ms] BUILD FAILED
[   +1 ms] Total time: 10.66 secs
[ +757 ms] "flutter run" took 35,929ms.
Gradle build failed: 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:314
)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:238)
<asynchronous suspension>
#3      buildApk (package:flutter_tools/src/android/apk.dart:36)
<asynchronous suspension>
#4      AndroidDevice.startApp (package:flutter_tools/src/android/android_device
.dart:360)
<asynchronous suspension>
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:267
)
<asynchronous suspension>
#6      HotRunner.run (package:flutter_tools/src/run_hot.dart:215)
<asynchronous suspension>
#7      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:335)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/fl
utter_command.dart:256)
<asynchronous suspension>
#9      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dar
t:196)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutte
r_command_runner.dart:279)
<asynchronous suspension>
#12     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:
109)
#13     new Future.sync (dart:async/future.dart:222)
#14     CommandRunner.run (package:args/command_runner.dart:109)
#15     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_comma
nd_runner.dart:162)
#16     run.<anonymous closure> (package:flutter_tools/runner.dart:89)
<asynchronous suspension>
#17     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#18     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base
/context.dart:66)
#19     _rootRun (dart:async/zone.dart:1120)
#20     _CustomZone.run (dart:async/zone.dart:1001)
#21     runZoned (dart:async/zone.dart:1467)
#22     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#23     run (package:flutter_tools/runner.dart:60)
<asynchronous suspension>
#24     main (package:flutter_tools/executable.dart:43)
<asynchronous suspension>
#25     main (file:///C:/git/flutter/packages/flutter_tools/bin/flutter_tools.da
rt:16)
#26     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart
:263)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dar
t:151)


[ +322 ms] ensureAnalyticsSent: 260ms
[   +6 ms] exiting with code 1'

**Comment by mit-mit** [comment]
@ashtouch007 just to narrow things down: Can you create a (regular) Android project in Android Studio, and run that on the emulator without problems?

**Comment by Hixie** [comment]
We don't have sufficient context to resolve this issue. Since there hasn't been an update in several months, I'm going to close it. Please don't hesitate to file a new bug if you are still seeing this.
