### ISSUE TITLE
[Impeller] Inline binding maps in command object (cmd.h)

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#133199]
Originally the bindings object in command.h created 5 std::unordered_map for the vertex and 5 for the fragment stage. The deallocation of these maps adds measurable overhead to render pass encoding. In https://github.com/flutter/engine/pull/44990 and https://github.com/flutter/engine/pull/45021 I reduced the number of maps from 5 to 2. But since most cmds will 0-1 bound items, we can be more efficient if we slightly inline the map: that is have a slot on the binding object for id 0, and the a ptr to a map that we lazily create if we need more

**Comment by jonahwilliams** [comment]
It looks like the only shaders we have that use more than the default bindings are SSBO gradients and some filter types that take two texture bindings. So updating commands to have special slots for binding 0 buffer, binding 0 texture, and vertex bindings seems like a free win.

**Comment by chinmaygarde** [comment]
Presumably, https://github.com/flutter/engine/pull/45040 fixes this but perhaps only partially?

**Comment by jonahwilliams** [comment]
We've fixed this for Vulkan/Metal. For GLES, we need to track less data and update our API: https://github.com/flutter/flutter/issues/142165
