### ISSUE TITLE
Flutter/Android: how to remove darkening layer in darkmode on Android (Xiaomi) during Splash Screen?

### ISSUE THREAD

**Issue by K1yoshiSho** [flutter/flutter#133132]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I used:

    android:theme="@style/LaunchTheme"

and style in values-night:

    <?xml version="1.0" encoding="utf-8"?>
    <resources>
        
        <style name="LaunchTheme" parent="@android:style/Theme.Black.NoTitleBar">
            
            <item name="android:windowBackground">@drawable/launch_background</item>
            <item name="android:forceDarkAllowed">false</item>
            <item name="android:windowFullscreen">true</item>
            <item name="android:windowDrawsSystemBarBackgrounds">true</item>
            <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>
        </style>
        
        <style name="NormalTheme" parent="@android:style/Theme.Black.NoTitleBar">
            <item name="android:windowBackground">#ffffff</item>
        </style>
    </resources>

What i want:

[![enter image description here][1]][1]

And in my case:

[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/cXqMt.jpg
  [2]: https://i.stack.imgur.com/l6OAY.jpg

I check some apps and some have a dark layer and some don't. So there are workarounds. If anyone knows, can you share? I use #ffffff color because when i put this one:

    <item name="android:windowBackground">?android:colorBackground</item>

It is a dark color and as a result, just a black screen is shown there.

### Expected results

Normal splash screen

### Actual results

Splash screen with dark layer when i put white color in windowsBackground item and black color in default.

### Code sample

<details><summary>Code sample</summary>

```dart
Not dart code
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

Pinned.

</details>

### Logs

<details><summary>Logs</summary>

```console
No logs
```

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.5.1 22G90 darwin-arm64, locale ru-KZ)
    • Flutter version 3.13.0 on channel stable at /Users/yelamanyelmuratov/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (7 days ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/yelamanyelmuratov/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 14 (API 34) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.5.1 22G90 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 116.0.5845.96

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by K1yoshiSho** [comment]
Removing NormalTheme not work, and i used SplashTheme too, is the same thing. Not work.

**Comment by darshankawar** [comment]
@K1yoshiSho 
I think your question is better suited for support channels like StackOverflow, where you can get a solution on the case you described.
If you think this is a bug in the framework, please provide all relevant details like reproducible code sample along with flutter doctor -v so that we can properly address the issue, as the repo is to track bugs and feature requests.
Closing from here, as this is more of a `how to` question. If you disagree, write in comments and I'll reopen it.
