### ISSUE TITLE
Revert follow-up for "Enable clang-tidy for pre-push (opt-out), exclude performance-unnecessary-value-param"

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#133190]
Follow-up/context bug for https://github.com/flutter/engine/pull/45020.

We reverted it because it seemed to be triggering some build failures on https://github.com/flutter/engine/pull/43764. (Failed build: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Engine%20Drone/1263361/overview)

CC @matanlurey

**Comment by matanlurey** [comment]
I am going to close this as not necessary.
