### ISSUE TITLE
Dart to Engine roller is paused

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#133152]
The most recent roll was reverted in https://github.com/flutter/engine/pull/44989 due to many new analyzer lints that were surfaced in the attempt to roll to the framework: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20analyze/62841/overview.

These are apparently due to https://dart.googlesource.com/sdk.git/+/8c2f088481e90949dc04f532af8600b23138ff63

cc @kallentu

**Comment by kallentu** [comment]
Fixed with https://github.com/dart-lang/sdk/commit/b3c433c7614e39d0dedcab2ef130bf6d0e291390.

**Comment by zanderso** [comment]
The roll to the framework failed again after including this fix: https://github.com/flutter/flutter/pull/133261

**Comment by a-siva** [comment]
A manual roll of Dart into Flutter engine with the analyzer fix was done here https://github.com/flutter/engine/pull/45165
 and this version of the engine roll into Flutter framework here https://github.com/flutter/flutter/pull/133444.

Closing issue as fixed.
