### ISSUE TITLE
flutter go_router and riverpod Get parameters send to Controller

### ISSUE THREAD

**Issue by WyntersN** [flutter/flutter#133160]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

flutter_riverpod: ^2.3.7
go_router: ^10.1.0
flutter 3.13.0

ControllerCode:
```
  final ControllerProvider =
        StateNotifierProvider.autoDispose<Controller, State>((ref) => Controller());
    class State {}
    class Controller extends StateNotifier<State> {
      Controller() : super(State()) {
        //How should I obtain it correctly arguments ???
        if (arguments != null) {
          state.textEditingController.text = Get.arguments;
          getData(page: 1, keyword: Get.arguments);
        } else {
          getData(page: 1);
        }
      }
    }
```

pageCode:

```
  class Page extends ConsumerStatefulWidget {
        const Page({super.key});

        @override
        _State createState() => _State();
      }

      class _State extends ConsumerState<Page> {
        late State state;
        late Controller controller;

        @override
        Widget build(BuildContext context) {
          final routeState = GoRouterState.of(context);
          if (routeState.uri.queryParameters["arguments"] != null) {
            routeState.uri.queryParameters["arguments"]!;
            //print username01
          }

          state = ref.watch(ControllerProvider);
          controller = ref.watch(ControllerProvider.notifier);
          return Container();
        }
      }
```

### Actual results

How should I obtain it correctly arguments to Controller(arguments)  ?

ControllerProvider Can be obtained GoRouterState.of(context) to Controller?

Controller get GoRouterState.of(context).uri.queryParameters

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by ASISBusiness** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
> - [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)
> 
> ### Steps to reproduce
> 
> flutter_riverpod: ^2.3.7
> 
> go_router: ^10.1.0
> 
> flutter 3.13.0
> 
> 
> 
> ControllerCode:
> 
> ```
> 
>   final ControllerProvider =
> 
>         StateNotifierProvider.autoDispose<Controller, State>((ref) => Controller());
> 
>     class State {}
> 
>     class Controller extends StateNotifier<State> {
> 
>       Controller() : super(State()) {
> 
>         //How should I obtain it correctly arguments ???
> 
>         if (arguments != null) {
> 
>           state.textEditingController.text = Get.arguments;
> 
>           getData(page: 1, keyword: Get.arguments);
> 
>         } else {
> 
>           getData(page: 1);
> 
>         }
> 
>       }
> 
>     }
> 
> ```
> 
> 
> 
> pageCode:
> 
> 
> 
> ```
> 
>   class Page extends ConsumerStatefulWidget {
> 
>         const Page({super.key});
> 
> 
> 
>         @override
> 
>         _State createState() => _State();
> 
>       }
> 
> 
> 
>       class _State extends ConsumerState<Page> {
> 
>         late State state;
> 
>         late Controller controller;
> 
> 
> 
>         @override
> 
>         Widget build(BuildContext context) {
> 
>           final routeState = GoRouterState.of(context);
> 
>           if (routeState.uri.queryParameters["arguments"] != null) {
> 
>             routeState.uri.queryParameters["arguments"]!;
> 
>             //print username01
> 
>           }
> 
> 
> 
>           state = ref.watch(ControllerProvider);
> 
>           controller = ref.watch(ControllerProvider.notifier);
> 
>           return Container();
> 
>         }
> 
>       }
> 
> ```
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ### Actual results
> 
> How should I obtain it correctly arguments to Controller(arguments)  ?
> 
> 
> 
> ControllerProvider Can be obtained GoRouterState.of(context) to Controller?
> 
> 
> 
> Controller get GoRouterState.of(context).uri.queryParameters
> 
> ### Logs
> 
> <details>
> 
> <summary>Logs</summary>
> 
> 
> 
> ```console
> 
> 
> 
> 
> 
> 
> 
> ```
> 
> 
> 
> </details>
> 
> 
> 
> ### Flutter Doctor output
> 
> <details>
> 
> <summary>Doctor output</summary>
> 
> 
> 
> ```console
> 
> 
> 
> 
> 
> 
> 
> ```
> 
> 
> 
> </details>
> 
>

**Comment by WyntersN** [comment]
？？？？？？？？？？？？？？？？？

**Comment by WyntersN** [comment]
go_router.pushNamed("/home",extra:"hello word");

Controller How to get go_router extra，Currently, I am using global variables get extra

**Comment by WyntersN** [comment]
https://github.com/flutter/flutter/assets/27792650/364bc7f3-1e29-46a7-ac02-dddef926a435


IOS WEB  go_route back.

**Comment by darshankawar** [comment]
@WyntersN 
Can you try by creating a data class to be used for passing object into extra and see if it helps in your case or not ?

**Comment by WyntersN** [comment]
extra，I have already resolved it,I used global var。
Now there is a new problem，WEB go_route gesture back, there are some issues,Can you take a look at the recorded video

**Comment by darshankawar** [comment]
> Now there is a new problem，WEB go_route gesture back, there are some issues,Can you take a look at the recorded video

This seems to be a new issue separate from the one you reported in this one. Since your original issue seems to be resolved per your above comment, I'll go ahead and close this issue. Please file a new issue with all relevant details so as to get proper action on it instead of clubbing both issues in single one.
