### ISSUE TITLE
[Impeller] Enable validations for 32 bit builds.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#133167]
Apparently Vulkan _can_ run on a 32 bit user space.

We should enable validation layers for 32 bit builds, currently we assert the CPU is arm64.

**Comment by chinmaygarde** [comment]
I thought we built our own validation layers instead of using prepackaged ones like we used to. Shouldn't this have been taken care of by the usual engine build rules? cc @gaaclarke

**Comment by dnfield** [comment]
There's currently an assert that validations are only enabled if the target_cpu == "arm64".

There are also issues where the VVL headers error if you're on too low of an API level, which we are by default for 32 bit builds.

**Comment by dnfield** [comment]
I have a local patch that makes this work by manually updating the Android API version

**Comment by chinmaygarde** [comment]
@dnfield Is there another issue tracking updating on NDK version? Or is that a non-starter?

**Comment by jonahwilliams** [comment]
I don't think this is going to be important to do. The validation layers are the same on all devices and 32 bit builds are an ever shrinking % of Android
