### ISSUE TITLE
new builds not running in luci till restart

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#133161]
The tests @zanderso switched from s10 to pixel 7 are not starting https://ci.chromium.org/ui/p/flutter/builders/luci.flutter.staging/Linux_pixel_7pro%20animated_advanced_blend_perf__timeline_summary

**Comment by yusuf-goog** [comment]
cc @ricardoamador

**Comment by yusuf-goog** [comment]
There is some issue with new tests and running them before they appear in LUCI.

I just kicked off reruns and they are now starting to pass.

**Comment by yusuf-goog** [comment]
This behavior also seen with some tests @vashworth just reintroduced. They never ran till I kicked off a rerun.

**Comment by yusuf-goog** [comment]
Making this bug be about tracking down root cause.

**Comment by yusuf-goog** [comment]
FYI, workaround seems to be kicking off a rerun. Although, the rerun might need to be delay till luci build info propagates (not sure).

**Comment by yusuf-goog** [comment]
Mac_ios integration_ui_ios_driver_xcode_debug, Mac_ios flutter_gallery_ios__start_up_xcode_debug were the tests @vashworth reintroduced.

**Comment by vashworth** [comment]
For my use case, I added two tests `Mac_ios integration_ui_ios_driver_xcode_debug` and `Mac_ios flutter_gallery_ios__start_up_xcode_debug`.

I originally added them in https://github.com/flutter/flutter/pull/131865 (Aug 9) and they started fine. I later removed them in https://github.com/flutter/flutter/pull/132398 (Aug 11). And I recently re-added them in https://github.com/flutter/flutter/pull/132523 (Aug 22)

**Comment by yusuf-goog** [comment]
FYI, once the first build runs (after kicking off rerun) subsequent ones run fine.

**Comment by ricardoamador** [comment]
I believe this to be this issue: https://github.com/flutter/flutter/issues/131501.

The next step in that is to just rebase to TOT.
