### ISSUE TITLE
Execution Failed for Task ':qr_code_scanner:parseDebugLocalResources' When Running on Different Machine

### ISSUE THREAD

**Issue by MISHRA-TUSHAR** [flutter/flutter#133121]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Clone the project on a new machine.
Run flutter pub get.
Execute flutter run.

I'm currently working on a Flutter project that utilizes the qr_code_scanner package. The application runs perfectly fine on my primary machine, but when I try to run the same codebase on a different machine, I'm encountering an error

Here's what I've tried so far to address the issue:

Cleaned the Project: Ran flutter clean, followed by flutter pub get and flutter run.
Ensured SDK Consistency: Made sure both machines have the same Flutter and Dart SDK versions.
Checked AndroidX Compatibility: Verified that the project is AndroidX compatible.
Updated the qr_code_scanner Package: Ensured I'm using the latest version.
Verified Resource Integrity: Ensured all required resources are correctly placed and accessible.
Despite these efforts, the error persists. I'm wondering if anyone else has faced a similar issue and might have insights or suggestions on how to resolve it. I'd appreciate any guidance the community can provide.

### Actual results

When attempting to run the application, the build process halts and throws the following error:

**Execution failed for task ':qr_code_scanner:parseDebugLocalResources'.**

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by darshankawar** [comment]
@MISHRA-TUSHAR 
qr_code_scanner is a community package, so if there's any issues with it, you'll need to report it in dedicated repo or ask this issue in support channels like Stackoverflow.
Closing from here, as this isn't related to bug in flutter framework.
