### ISSUE TITLE
[Impeller] PaintingStyle.stroke for Text: Rendered text has an offset

### ISSUE THREAD

**Issue by LeoSandbox** [flutter/flutter#133157]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Hi, I am following up on #126010 and [#41735](https://github.com/flutter/engine/pull/41735) closed last month.

I am using `3.14.0-0.1.pre` on `beta` channel and I can clearly see that outline of text is now supported on Impeller iOS using foreground in TextStyle as per [doc](https://api.flutter.dev/flutter/painting/TextStyle-class.html#painting.TextStyle.6). 

However this fix introduced an offset issue on the rendered text with foreground stroke painter with both the default Flutter font (small offset) and other Google Fonts (large offset). See code example, screenshots and details below.

### Expected results

This issue makes text outline impossible to use with foreground method as the goal of the outline is to be positioned exactly below the text without outline in the Stack - otherwise it is a shadow. The [shadow method](https://stackoverflow.com/questions/52146269/how-to-decorate-text-stroke-in-flutter) workaround still works but visually not great compared to a real outline stroke.

### Actual results

Texts with strokes on iOS using Impeller have now an offset that can range from a few pixel if using the default Flutter font to a significant amount when using any other fonts (see Google Font [Mulish](https://fonts.google.com/specimen/Mulish) in screenshots)

### Code sample

```
import 'package:flutter/material.dart';

class TestTextOutline extends StatelessWidget {
  const TestTextOutline({super.key});

  @override
  Widget build(BuildContext context) => Material(
        color: Colors.blue,
        child: Center(
          child: Stack(
            children: [
              Text(
                "1,250 / 35,000",
                style: TextStyle(
                    fontSize: 30,
                    fontWeight: FontWeight.w700,
                    fontFamily: 'Mulish',
                    foreground: Paint()
                      ..style = PaintingStyle.stroke
                      ..strokeWidth = 1
                      ..color = Colors.black),
              ),
              const Text(
                "1,250 / 35,000",
                style: TextStyle(
                  color: Colors.white,
                  fontSize: 30,
                  fontWeight: FontWeight.w700,
                  fontFamily: 'Mulish',
                ),
              ),
            ],
          ),
        ),
      );
}
```

### Screenshots or Video

**Using the sample code with Mulish Google Font (this applies to other Google Fonts I tested)**

<img width="564" alt="textoutline-mulish" src="https://github.com/flutter/flutter/assets/132463706/ecbdf40b-0e64-4dde-a2d2-5d56592dd700">

**Using the default font (i.e. removing fontFamily)**

<img width="564" alt="textoutline-default" src="https://github.com/flutter/flutter/assets/132463706/26259c4d-6cc7-4d97-bd14-1905166d4398">

**Using the default font and zooming in so you can see the offset**

<img width="1163" alt="textoutline-default-zoom" src="https://github.com/flutter/flutter/assets/132463706/7fc9f69d-c92c-4bf6-b830-4c552708c1d7">

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel beta, 3.14.0-0.1.pre, on macOS 13.2.1 22D68 darwin-arm64, locale en-CA)
    • Flutter version 3.14.0-0.1.pre on channel beta at /Users/xxxxxxxxxxxxx/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 120d54d33a (6 days ago), 2023-08-17 14:10:34 -0500
    • Engine revision f613b67824
    • Dart version 3.2.0 (build 3.2.0-42.1.beta)
    • DevTools version 2.26.1

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.0

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (2 available)
    • iPhone (mobile) • 00008020-xxxxxxxxxxxxx • ios          • iOS 16.4.1 20E252
    • macOS (desktop) • macos                     • darwin-arm64 • macOS 13.2.1 22D68 darwin-arm64

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report. Seeing the same behavior as reported on latest master and beta versions.

<details>
<summary> master flutter doctor -v </summary>

```

[!] Flutter (Channel master, 3.14.0-8.0.pre.21, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.14.0-8.0.pre.21 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c328d03928 (2 hours ago), 2023-08-20 23:21:32 -0400
    • Engine revision e7d7451117
    • Dart version 3.2.0 (build 3.2.0-90.0.dev)
    • DevTools version 2.26.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by UlasAkgun** [comment]
+1 to this please

**Comment by LeoSandbox** [comment]
@UlasAkgun Just put a 👍 to my original post above. Issues are ranked by count of 👍. Thanks!

**Comment by jonahwilliams** [comment]
FYI @matanlurey

**Comment by matanlurey** [comment]
> I suspect I've done my math wrong on the transform.

Maybe :)

I made a little demo within the engine to validate, similar to the framework code above:

![Screenshot 2023-08-25 at 6 46 20 PM](https://github.com/flutter/flutter/assets/168174/c4740604-b4bd-4371-9ddd-164a4f314bca)

Debugging the state a bit, here is what I found:

```cc
# [stroked] x=250 y=250
# bounds: x=1.5625, y=-37.5, w=137.305, h=39.0625
canvas_.Translate({x + bounds->origin.x, y + bounds->origin.y, 0.0});

# [filled] x=250 y=250
```

Will continue to poke :)

**Comment by matanlurey** [comment]
Interesting discovery time!

In Skia's [`ParagraphImpl.cc`, they perform a transform](https://github.com/google/skia/blob/26c9cb69e1211bb47dc3a03af69d7d0796557253/modules/skparagraph/src/ParagraphImpl.cpp#L1406-L1409):

```cc
SkMatrix tmp(mx);
tmp.postTranslate(rec->fPos->fX - rec->fOffset.fX, rec->fPos->fY - rec->fOffset.fY);
rec->fDst->addPath(*src, tmp);
```

If comment out the `postTranslate`, I get the following output with an identity transform in `dl_dispatcher.cc`:

```diff
- canvas_.Translate({x + bounds->origin.x, y + bounds->origin.y, 0.0});
+ canvas_.Translate({x, y, 0.0});
```

...  you'll notice the first letter is offset correctly (unfortunately every subsequent letter is now on top of the first):

<img width="251" alt="Screenshot 2023-08-26 at 11 18 38 AM" src="https://github.com/flutter/flutter/assets/168174/6add58ba-ab5a-4830-9176-bf0bd55c8a71">

I'm not saying the Skia code is wrong (though, maybe?), but it could be a hint to how the offset is occurring.

**Comment by matanlurey** [comment]
Looks like I got it, I'll prepare a patch:

```diff
-    auto bounds = text_frame.GetBounds();
-    if (!bounds.has_value()) {
-      return;
-    }
+    auto& bounds = blob->bounds();
     canvas_.Save();
-    canvas_.Translate({x + bounds->origin.x, y + bounds->origin.y, 0.0});
+    canvas_.Translate({x + bounds.left(), y + bounds.top(), 0.0});
```

<img width="370" alt="Screenshot 2023-08-26 at 11 37 03 AM" src="https://github.com/flutter/flutter/assets/168174/4ebaec8a-651d-4381-b642-1ad7f2f4d5ad">

That was the offset provided in the Skia implementation:

```cc
struct Rec { SkPath* fDst; SkPoint fOffset; const SkPoint* fPos; } rec =
  {&path, {textBlob->bounds().left(), textBlob->bounds().top()},
  iter.points()};
```

**Comment by LeoSandbox** [comment]
Wow awesome!! 🥳 I wasn't expecting such a super fast resolution.

Quick question - did you try with couple of variations to see if the outline still holds?
Example of variations: google fonts such as Mulish, Noto Sans Japanese, Noto Sans Arabic, Baloo2 Reenie Beanie (trying to cater for different alphabet and manuscript font), boldness like FontWeight changes, styles FontStyle bold/italic, changing height and letterspacing. Just my 2 cents, maybe the fix is universal for sure in independent from all these variations.

**Comment by pinktoadette** [comment]
> Wow awesome!! 🥳 I wasn't expecting such a super fast resolution.
> 
> Quick question - did you try with couple of variations to see if the outline still holds? Example of variations: google fonts such as Mulish, Noto Sans Japanese, Noto Sans Arabic, Baloo2 Reenie Beanie (trying to cater for different alphabet and manuscript font), boldness like FontWeight changes, styles FontStyle bold/italic, changing height and letterspacing. Just my 2 cents, maybe the fix is universal for sure - independent from all these variations.

Me too! I have similar challenges with all eastern languages.
