### ISSUE TITLE
[Impeller] Scene is unconditionally selecting kD32SfloatS8UInt for a depth attachment

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#133194]
The device may not support this, which will result in errors. There needs to be some caps based selection here.

https://github.com/flutter/engine/blob/bc28b6792248d5b8b5c2a4d52dc30a2fcda7aaa0/impeller/scene/scene_context.cc#L21-L27

**Comment by dnfield** [comment]
@bdero fyi

**Comment by bdero** [comment]
Impeller Scene is an absolute bare minimum 3D renderer. If we can't keep an easy path open for building its pipelines on CI, then Impeller's HAL is unsuitable for 3D.

This format is required for iPhones. We're missing a good validation and querying story for available formats at the moment. I think we'll eventually need to add these. 

However, I believe it will always be the case that a depth+stencil format is available, and so in this case it may be useful to sidestep the problem by adding a `GetDefaultDepthStencilFormat()` in the capabilities alongside `GetDefaultStencilFormat()`. Where `GetDefaultStencilFormat()` biases towards selecting a stencil-only format, and the other guarantees that a depth segment is included.

**Comment by chinmaygarde** [comment]
Isn't that just a typo? Why isn't D24S8 suitable?

**Comment by dnfield** [comment]
> Isn't that just a typo? Why isn't D24S8 suitable?

It's not available on iOS.

iOS will always have D32S8 and never have D24S8.

Vulkan might have one or the other.

**Comment by chinmaygarde** [comment]
We have a `Capabilities::GetDefaultColorFormat` and `Capabilities::GetDefaultStencilFormat`. The latter doesn't care about depth. We should have a `Capabilities::GetDefaultDepthStencilFormat` too for this use case.

**Comment by bdero** [comment]
Yes, that's what [I recommended](https://github.com/flutter/flutter/issues/133194#issuecomment-1690824946). 😆

**Comment by chinmaygarde** [comment]
derp

**Comment by bdero** [comment]
I added an issue about the more general problem of determining which formats are supported here: https://github.com/flutter/flutter/issues/133496
