### ISSUE TITLE
Overflow issue found in RadioListTile sample code

### ISSUE THREAD

**Issue by YumNumm** [flutter/flutter#133142]
## Steps to reproduce
1. open [`RadioListTile<T> class Example3`](https://api.flutter.dev/flutter/material/RadioListTile-class.html#material.RadioListTile.3) 
2. make the window smaller
3. then, you will found `Scaffold()` is overflowed

## Expected results
This RadioListTile array would be scrollable

## Actual results
It overflows because it can't be scrolled.

## Screenshot

<details>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/flutter/flutter/assets/73390859/412df754-56bf-4c30-85d6-956497fea918)

</details>

**Comment by TahaTesser** [comment]
Hi @YumNumm 

> make the window smaller


This could happen with any column of widgets in the API docs if you size the window. Not just the `RadioListTile` sample.

 I'm not sure it is necessary to add `SingleChildScrollView` to a bunch of code samples as it is recommended to have `SingleChildScrollView` all the time for performance reasons.

This default Dartpad window size doesn't throw an overflow error.
![Screenshot 2023-08-23 at 16 40 34](https://github.com/flutter/flutter/assets/48603081/7de01487-9524-4986-8bfc-bfab54e1b0ba)


cc: @gspencergoog  

WDYT?

**Comment by gspencergoog** [comment]
I don't really want to add `SingleChildScrollView` to most examples: it clutters up the example with context that can confuse new users. Also, it can make the content of the window appear clipped instead of wrapping.

**Comment by YumNumm** [comment]
Thanks @TahaTesser & @gspencergoog !!
Indeed, what you say is right. 
This colud be over-implemented and poor performance&UX.
I'm going to close this PR and related issue. Is it okay?
