### ISSUE TITLE
[Impeller] Raster thread can take up to 1ms to wake up.

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#133166]
Profile from the [new gallery driver test](https://ui.perfetto.dev/#!/?s=432a33d9b53a70a73817c7332d75695c5542feb55bede716847cb0225efc2127):

<img width="332" alt="Screenshot 2023-08-23 at 10 05 49 AM" src="https://github.com/flutter/flutter/assets/30870216/ccd3630f-944b-4a56-94d6-cd4c3ed6cbeb">

Potential fixes could be to reduce the number of threads the engine is using or change thread priorities.  Jonah isn't confident that there is much to be gained by adjusting the thread priorities since the raster thread should be maxed out and adjusting io threads to be lower has caused problems in the past.

engine version: eda01661c621d364c8619e50ce126f59b69ad825

**Comment by jonahwilliams** [comment]
Specifically when we had the IO thread at lower priority I believe there were numerous priority inversion issues, but I didn't actually work on that part.

The biggest reason we need so many threads is that we don't have a way to do per-task prioritization, so in order to prevent (for example) PSO construction from getting stuck behind image decoding we need different thread pools.

**Comment by gaaclarke** [comment]
According to the profile, the 2 mid cores are actually available for that whole 1 ms too.  I'm not sure what the delay is.

<img width="340" alt="Screenshot 2023-08-23 at 10 39 30 AM" src="https://github.com/flutter/flutter/assets/30870216/e58c47fa-6225-44de-bd3e-e4e24297eddf">

**Comment by chinmaygarde** [comment]
Not sure there is anything actionable here. The raster thread is already at elevated priority. We should reduce the number of threads but it is not clear if that would help in this case.

**Comment by gaaclarke** [comment]
@chinmaygarde I don't know that it's helpful to close this since it is still an issue.  We don't typically close verified issues we don't know how to address.

When analyzing the thread state statistics for the new gallery driver test it was found that 916ms / 14,332 ms (6%) of the raster thread is spent in "Runnable".  If there was a theoretical fix for that, it would be an improvement on the scale we've been considering for other PRs.
