### ISSUE TITLE
[tool_crash] ProcessException: Operation not permitted Command: /Users/user/apps/android/gradlew, OS error code: 1

### ISSUE THREAD

**Issue by muchlisre** [flutter/flutter#133148]
## Command
```
flutter --no-color build apk
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Operation not permitted Command: /Users/user/apps/ 2/android/gradlew, OS error code: 1
```

```
```
[✓] Flutter (Channel stable, 1.22.6, on macOS 13.5 22G74 darwin-arm, locale en-ID)
    • Flutter version 1.22.6 at /Users/xx/fvm/versions/1.22.6
    • Framework revision 9b2d32b605 (2 years, 7 months ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/xx/Library/Android/sdk
    • Java binary at: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_371-b11)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    • CocoaPods version 1.12.1

[!] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[!] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Redmi Note 8 Pro (mobile) • r8yh596dhmr4ztbu • android-arm64 • Android 11 (API 30)

! Doctor found issues in 4 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 2.0.3+16
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 2ae34518b87dd891355ed6c6ea8cb68c4d52bb9d
### Plugins
flutter_map_arcgis-1ed33275d4ee08de57fe610499b6a87dc628b845
flutter_plugin_pdf_viewer-85e5b127b7fa8a3b4d5b77b7484efcaa6d99c90a
connectivity-2.0.2
connectivity_for_web-0.3.1+4
connectivity_macos-0.1.0+7
file_picker-2.1.7
firebase_core-0.5.3
firebase_core_web-0.2.1+1
firebase_messaging-7.0.3
flutter_keyboard_visibility-4.0.6
flutter_keyboard_visibility_web-1.0.1
flutter_native_image-0.0.5+3
flutter_native_timezone-1.0.4
flutter_plugin_android_lifecycle-1.0.11
gallery_saver-2.0.3
geocoding-1.0.5
geolocator-6.2.1
geolocator_web-1.0.1
image_picker-0.6.7+22
image_picker_for_web-0.1.0+2
package_info-0.4.3+4
path_provider-1.6.28
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+8
path_provider_windows-0.0.4+3
phone_number-0.6.3
search_choices-1.0.17
share_plus-1.2.0
share_plus_web-0.1.0
shared_preferences-0.5.12+4
shared_preferences_linux-0.0.2+4
shared_preferences_macos-0.0.1+11
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.2+3
sqflite-1.3.2+4
url_launcher-5.7.10
url_launcher_linux-0.0.1+4
url_launcher_macos-0.0.1+9
url_launcher_web-0.1.5+3
url_launcher_windows-0.0.1+3
webview_flutter-0.3.24

**Comment by dam-ease** [comment]
Hi @muchlisre , you are on an older version of flutter. Kindly upgrade to the latest version of flutter. This issue was reported in https://github.com/flutter/flutter/issues/50880 and has since been fixed.

Closing this as it has already been fixed.

If you still experience this issue after upgrading to the latest version of flutter, kindly leave a report below.

Thank you
