### ISSUE TITLE
[Impeller] Scene is getting compiled into binary even if IMPELLER_ENABLE_3D is false.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#133193]
We should not do this for now, only add it in if the define is set.

@bdero fyi

**Comment by bdero** [comment]
Can you please paste the validation log you are getting? SceneContext uploads a texture on construction, but it doesn't render anything. It sounds to me like there might be a bug in the Vulkan backend.

**Comment by bdero** [comment]
Ah, I see it's the pipeline formation as you pointed out here: https://github.com/flutter/flutter/issues/133194
