### ISSUE TITLE
go_router package: GoRouterState extra object not updated when using .push 

### ISSUE THREAD

**Issue by mihaieremia** [flutter/flutter#133218]
Hey guys,

I have a function that checks the extra object from each page inside of my nav bar, I want to check if I need to hide the nav bar or not on some pages.

```
bool isNoNavBarRoute(BuildContext context) {
  final extra = GoRouterState.of(context).extra as Map?;

  if (extra?['hasNav'] == false) {
    return true;
  }
  return false;
}

Object hasNoNav = {
  'hasNav': false,
};
```

While implementing and testing I realised that navigating like this will not update my GoRouterState extra object:
```
 context.push(SendNftPage.getPath(address), extra: hasNoNav);
```
But when I use .replace or .go will work:
```
 context.go(SendNftPage.getPath(address), extra: hasNoNav);
```

Might be this a bug or is by design ?

**Comment by darshankawar** [comment]
@mihaieremia 
Can you take a look at [this](https://github.com/flutter/flutter/issues/125752) issue and check if it helps to answer your case or not ?

**Comment by mihaieremia** [comment]
> @mihaieremia Can you take a look at [this](https://github.com/flutter/flutter/issues/125752) issue and check if it helps to answer your case or not ?

Yes I have exactly the same problem, then this issue can be market as duplicate and we can focus on that one.

**Comment by darshankawar** [comment]
Good to know. Closing this as a duplicate.

**Comment by darshankawar** [comment]
Good to know. Closing this as a duplicate.
