### ISSUE TITLE
[Impeller] Page route transition just doesn't work

### ISSUE THREAD

**Issue by victor-tinoco** [flutter/flutter#133265]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

You can create a simple app with a single page that will navigate to another route by extending on `PageRoute` and adding a transition, like the `FadeTransition`. 

Use [this example](https://dartpad.dev/?id=cbac6a3b769ed35d10eddf14235ad925) on dartpad.

The animation just doesn't work. I debugged for a couple of hours until having the idea to just disable the impeller, and damn, it worked. The issue was found on iOS, not sure about Android since it doesn't have the impeller enabled by default.

### Expected results

The transition should animate as expected, in the example mentioned above, performing a fade transition.

See the recording with the impeller disabled:

https://github.com/flutter/flutter/assets/49794086/74217a16-5ec8-4d68-b86d-44b0ed124c36

### Actual results

It just does not animate the transition.

See the recording with the impeller enabled (please see the very final pixel of this recording, I've cut too early, but as you can see it just does not animate and then jumps to the yellow route).

https://github.com/flutter/flutter/assets/49794086/1f61628f-1da7-457b-b011-3e4d204c8be8

### Code sample

See this [code example](https://dartpad.dev/?id=cbac6a3b769ed35d10eddf14235ad925) over dartpad.

### Flutter Doctor output

<details>
<summary>Output</summary>

```sh
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.1, on macOS 13.3.1 22E772610a darwin-arm64, locale en-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.81.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```
</details>

**Comment by feinstein** [comment]
@huycozy don't know why this issue wasn't labeled, I think it would be good to label it as `e: Impeller`.

**Comment by darshankawar** [comment]
Thanks for the report @victor-tinoco 
Although I see the same behavior as reported using impeller on latest stable version, but it seems to be fixed and working as expected on latest master. See below video in which the page route transition happens smoothly as expected:


https://github.com/flutter/flutter/assets/67046386/f08440c9-d289-4609-b273-f9a601db792f

`Channel master, 3.14.0-9.0.pre.88`

Since it is fixed on latest master, I'll go ahead and close this as working as expected. If you disagree, write in comments and I'll reopen it.

**Comment by victor-tinoco** [comment]
Thanks for the heads up @darshankawar!

Just tested and confirmed it here, it seems to be working as expected at the `master` channel.
