### ISSUE TITLE
Tab is hardcoding the height of the icons and the text 

### ISSUE THREAD

**Issue by ride4sun** [flutter/flutter#13322]
The height of the Tabs get hardcoded in the Tab Widget. I would like to use custom images instead of the icons and they are a bit bigger. Unfortunately the the widgets shows the clipping text when the Images gets applied because of the hardcoded height values (see below). I would suggest to set these values in the ctor as default values to give the user a option to change them. Also a enum in ctor would be great which has two values (manual, autosize). Autosize would size based on the content and manual sizing would size use the default or passed in ctor values. These changes could be compatible with the current API.

Hardcoded heights now tabs.dart 
https://github.com/flutter/flutter/blob/e6ed069b326ab42b31c316b594277566d05b7bbc/packages/flutter/lib/src/material/tabs.dart#L93-L99

```
[√] Flutter (on Microsoft Windows [Version 10.0.16299.98], locale en-US, channel alpha)
    • Flutter at c:\sdks\flutter
    • Framework revision d957c8f040 (2 days ago), 2017-11-30 13:29:59 -0800
    • Engine revision 77d8acb9be
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-dev.9.0

[√] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at C:\Users\ride4\AppData\Local\Android\sdk
    • Unable to locate Android NDK.

    • Unable to locate compiler in Android NDK.

    • Platform android-27, build-tools 27.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 19.1
    • Dart plugin version 172.4343.25

[√] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)
```

**Comment by Hixie** [comment]
cc @HansMuller

**Comment by Hanggi** [comment]
Me too, I need set the height of Tab.

**Comment by matthewlloyd** [comment]
Me too. I also needed to customize the text size and color for both active and inactive tabs, in addition to the icon styles for both, and I wanted to customize the background too to make it a linear gradient. I ended up copying the contents of tabs.dart into my project, renaming the classes, and implementing what I needed on my own. It would have been nice to be able to just use the provided widgets.

**Comment by lifetin** [comment]
这个不能定死啊.不知道开发人员在搞什么,把高宽定死了. 都一年多了什么时候更新呀?

**Comment by theochampion** [comment]
Any update on this? Would be great to be able to set tab height

**Comment by sooxt98** [comment]
3 years later.... im on the same boat now

**Comment by Zigotote** [comment]
Same issue here. Because tab size is fixed, text is cut if it is too large, like in the screenshot where text scale is set to 300%
![image](https://github.com/flutter/flutter/assets/34279302/c707ccab-69b6-472c-aee8-5bb2168cd432)

**Comment by TahaTesser** [comment]
@Zigotote 
Filed a fix https://github.com/flutter/flutter/pull/147232
