### ISSUE TITLE
[Impeller] Flutter Gallery DlDispatch is mostly text conversions

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#133204]
![image](https://github.com/flutter/flutter/assets/8975114/afb656b1-a882-4313-91ca-8f8a131b3ed3)

Because we completely redispatch every part of every frame, we are reconverting all text blobs every single frame - and doing a ton of extra work. FYI @dnfield

**Comment by chinmaygarde** [comment]
This will be addressed by @dnfield s [patch](https://github.com/flutter/engine/pull/44248) that got reverted due to some platform views stuff.

**Comment by jonahwilliams** [comment]
That patch will move those conversions to the UI thread, but we still need to make this faster.

**Comment by jonahwilliams** [comment]
Fixed via https://github.com/flutter/engine/pull/45418

**Comment by chinmaygarde** [comment]
@dnfield is working on re-landing the patch.

**Comment by jonahwilliams** [comment]
Will be relanded via https://github.com/flutter/engine/pull/46115
