### ISSUE TITLE
Test fails based on time taken rather than testing the actual condition

### ISSUE THREAD

**Issue by flar** [flutter/flutter#133215]
In this PR: https://github.com/flutter/flutter/pull/132239

A test was added that looks for output that it expects to have "0ms" as the run time. That is not a reliable condition on test hosts and presumably doesn't actually test that the behavior was actually disabled, just that it doesn't take "much" time.

A failure on this test can derail an engine roll as seen here: https://cirrus-ci.com/task/5417897460236288?logs=main#L1130

**Comment by flar** [comment]
@Hixie

**Comment by Hixie** [comment]
hm yeah, i suppose that could go wrong huh
