### ISSUE TITLE
[Impeller] Reduce hashing and std::shared_ptr operations during text workloads.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#133201]
Each FontGlyphPair that we render will be hashed twice, once to deduplicate and collect all glyphs for a frame, and another time in the text contents. The hash computation itself is adding up. Additionall, the Typeface shared_ptr has a lot of ops on it too. We should find a way to reduce the amount of hashing.

![image](https://github.com/flutter/flutter/assets/8975114/3c1cdae3-87cc-4d5d-a069-f5744ee125e7)

**Comment by gaaclarke** [comment]
I have an issue related to this: https://github.com/flutter/flutter/issues/132164 (`[Impeller] Unify instances of Font in impeller::GlyphAtlas`).

If we unify the instances of Font's we won't be copying all those shared_ptr to typefaces.

**Comment by jason-simmons** [comment]
I'm looking into an approach involving splitting the `Font` out of the `FontGlyphPair` key and storing a separate map of glyph positions for each `Font`.

**Comment by chinmaygarde** [comment]
Can we close this after @jason-simmons patch https://github.com/flutter/engine/pull/45191#issuecomment-1696569467?

**Comment by jonahwilliams** [comment]
Yes, this is much improved now. TBD, find a way better way that doesn't involve hashing at all
