### ISSUE TITLE
Firebase plugins have conflicting dependencies.

### ISSUE THREAD

**Issue by jifalops** [flutter/flutter#13324]
Using the newest versions of the firebase plugins (as of Dec 4 2017) causes APK build to fail.

## Steps to Reproduce
1. `flutter create` a new app.
2. Add Firebase dependencies to pubspec.yaml: 
    ```
    firebase_analytics: ^0.1.1
    firebase_auth: ^0.3.1
    cloud_firestore: ^0.1.0
    firebase_database: ^0.1.4
    firebase_storage: ^0.0.7
    ```
3. `flutter build apk`

## Logs

```
Execution failed for task ':app:transformClassesWithDexForRelease'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/common/internal/zzbb;
```

## Flutter Doctor

[✓] Flutter (on Linux, locale en_US.UTF-8, channel alpha)
    • Flutter at /home/jake/flutter
    • Framework revision d957c8f040 (4 days ago), 2017-11-30 13:29:59 -0800
    • Engine revision 77d8acb9be
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-dev.9.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /home/jake/Android/Sdk
    • Unable to locate Android NDK.

    • Unable to locate compiler in Android NDK.

    • Platform android-26, build-tools 26.0.2
    • Java binary at: /home/jake/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at /home/jake/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Connected devices
    • Nexus 5X • 008c24c97a9490d0 • android-arm • Android 8.0.0 (API 26)

**Comment by Skylled** [comment]
This is due to differences in dependencies. This should be fixed by updating to `firebase_database: 0.1.4` or greater.

**Comment by jifalops** [comment]
@Skylled `firebase_database: ^0.1.4` has the same issue when combined with `firebase_storage: 0.0.7` (newest of both versions). However `firebase_storage: 0.0.6` is compatible. Should I open a new issue?

**Comment by Skylled** [comment]
You could probably just rename and reopen this one, to keep context.

All of the Firebase plugins should use the same versions of dependencies. (But currently that isn't the case.) I'll have a look at this specific case in a bit.

**Comment by jifalops** [comment]
Okay it goes deeper because storage 006 and 005 are having another firebase dep problem. I'll keep juggling the versions for a bit to see if they'll build. Are the Firebase plugins close to having the same gms and other dependencies?

**Comment by Skylled** [comment]
The plugins have all been updated to use 11.4.0+ on the repo, but those updates haven't been pushed to pub yet. Last I saw, @collinjackson said he was going to take care of that.

In the short term, you could clone the flutter/plugins repo and specify the path like so:

```
dependencies:
  flutter:
    sdk: flutter
  cloud_firebase:
    path: ../plugins/packages/cloud_firebase
  firebase_database:
    path: ../plugins/packages/firebase_database
```

and so on, as needed.

**Comment by mit-mit** [comment]
I believe this is being tracked -- and is in progress of being resolved -- as https://github.com/flutter/flutter/issues/12945 ?

**Comment by artAst** [comment]
I am experiencing the same issue here. Why is this happening? I am using the same plugin versions. Are there changes on the firebase plugins that we are using? because I am using the same plugin since and experienced the error. Supposedly the new changes must be on the new versions of the plugins right? not on existing ones

**Comment by mit-mit** [comment]
Closing this as #12945 was resolved. If anyone is still seeing issues please open a new issue with detailed repro steps.
