### ISSUE TITLE
Flutter Module not access internet with release mode

### ISSUE THREAD

**Issue by ltsolutionviet** [flutter/flutter#133245]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. I have a native android app
2. I create flutter module
3. Setup run debug mode it working normal
4. Release mode flutter module not access internet.
5. Permission INTERNET added in android manifest because feature of native android still working.

### Expected results

Flutter module access the internet with release mode

### Actual results

Flutter module can't access the internet with release mode

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![Screenshot 2023-08-24 at 16 35 47](https://github.com/flutter/flutter/assets/49478344/2b3f980b-9116-4e1d-bae1-64cd10442ffe)

</details>

### Logs

<details><summary>Logs</summary>

```console
 [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
                                                              #0      PathProviderApi.getTemporaryPath (package:path_provider_android/messages.g.dart:44)
                                                              <asynchronous suspension>
                                                              #1      getTemporaryDirectory (package:path_provider/path_provider.dart:55)
                                                              <asynchronous suspension>
                                                              #2      IOFileSystem.createDirectory (package:flutter_cache_manager/src/storage/file_system/file_system_io.dart:14)
                                                              <asynchronous suspension>
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.0 22A380 darwin-x64, locale en-VN)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.80.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

```

</details>

**Comment by dam-ease** [comment]
Hi @ltsolutionviet. Thanks for filing this. Can you confirm you're granting internet permission in your main `AndroidManifest.xml`? If yes, can you please share a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code (could be a simple repo)?

**Comment by ltsolutionviet** [comment]
@dam-ease  Yes, i have been add internet permission. I will upload minimal code sample .

**Comment by ltsolutionviet** [comment]
I thinks it conflict with my project, because i clone to minimal sample, it working normal. 
I will check my project.

**Comment by ltsolutionviet** [comment]
@dam-ease  After checking i got a problem,
![Screenshot 2023-08-25 at 14 22 35](https://github.com/flutter/flutter/assets/49478344/03f9bd24-0b10-4d47-bf36-5e081868d240)
After build aar module.
releaseImplementation 'com.module.flutter_module:flutter_release:1.0'  can't connect the internet.
but 
releaseImplementation 'com.module.flutter_module:flutter_debug:1.0' connect internet normal
I don't know exactly problem, but i think it is mistake of
   profile {
            initWith debug
        }
This config what is it?. Should i need config for mode release.

**Comment by ltsolutionviet** [comment]
![Screenshot 2023-08-25 at 14 48 37](https://github.com/flutter/flutter/assets/49478344/b8f83a5d-e02b-4411-a98c-232424c83018)

**Comment by dam-ease** [comment]
Hi @ltsolutionviet. Not to sure I can point out where this might be wrong or right, but based on this log 
> releaseImplementation 'com.module.flutter_module:flutter_debug:1.0' connect internet normal
Can you check out https://github.com/flutter/flutter/issues/95515 if it helps in your case?

**Comment by ltsolutionviet** [comment]
> 
It not help, because i completed integrate flutter plugin to android project. Only facing problem connect internet with release mode.

**Comment by dam-ease** [comment]
> I thinks it conflict with my project, because i clone to minimal sample, it working normal.
I will check my project.

Can you share the minimal sample with steps we can use to reproduce?

**Comment by ltsolutionviet** [comment]
[TestFlutterModule.zip](https://github.com/flutter/flutter/files/12438195/TestFlutterModule.zip)
@dam-ease 
Here is minimal sample:
Step run:
1. Open with android studio
2. cd flutter_module
3. flutter pub get
4. flutter build aar
5.  run debug app  -> working normal
6. build release with key -> not work

**Comment by ltsolutionviet** [comment]
> > I thinks it conflict with my project, because i clone to minimal sample, it working normal.
> > I will check my project.
> 
> Can you share the minimal sample with steps we can use to reproduce?

Can you help me check sample code above

**Comment by dam-ease** [comment]
Hi @ltsolutionviet. Thanks for your response and patience, I am checking this and can't seem to point out the issue as it seems to not be an issue with flutter itself. Does it give any error that we can take a look at? Can you run flutter run --release -v and see if it shows any error in the log and provide the same here?

**Comment by ltsolutionviet** [comment]
@dam-ease Don't have any error in log with comment flutter run --release -v, but the problem occurs when the build release and install the apk file, when entering the application the image is not loaded.

**Comment by ltsolutionviet** [comment]
`[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
                                                              #0      WebViewHostApi.create (package:webview_flutter_android/src/android_webview.pigeon.dart:289)
                                                              <asynchronous suspension>
15:13:20.196                                               E  [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
                                                              #0      WebSettingsHostApi.create (package:webview_flutter_android/src/android_webview.pigeon.dart:1013)
                                                              <asynchronous suspension>
15:13:20.196                                               E  [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
                                                              #0      WebSettingsHostApi.setDomStorageEnabled (package:webview_flutter_android/src/android_webview.pigeon.dart:1061)
                                                              <asynchronous suspension>
15:13:20.197                                               E  [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
                                                              #0      WebSettingsHostApi.setJavaScriptCanOpenWindowsAutomatically (package:webview_flutter_android/src/android_webview.pigeon.dart:1087)
                                                              <asynchronous suspension>
15:13:20.199                                               E  [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
                                                              #0      WebSettingsHostApi.setSupportMultipleWindows (package:webview_flutter_android/src/android_webview.pigeon.dart:1113)
                                                              <asynchronous suspension>
15:13:20.200                                               E  [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
                                                              #0      WebSettingsHostApi.setLoadWithOverviewMode (package:webview_flutter_android/src/android_webview.pigeon.dart:1239)
                                                              <asynchronous suspension>
15:13:20.200                                               E  [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
                                                              #0      WebSettingsHostApi.setUseWideViewPort (package:webview_flutter_android/src/android_webview.pigeon.dart:1263)`

@dam-ease  This is error after i run apk with release mode. It is problem with the internet, beside i use package https://pub.dev/packages/connectivity_plus it can't detect status, but debug working normal

**Comment by ltsolutionviet** [comment]
> 
Problem at Step 6
**build release with key store** 
We got apk, and it can't access internet.

**Comment by dam-ease** [comment]
Hi @ltsolutionviet. Thanks for your response. Checking on my end, can you try creating a new project without adding `<uses-permission android:name="android.permission.INTERNET"/>` to flutter_module's main AndroidManifest.xml. Also, See similar issues reported there and see if it helps to resolve them. This looks like a config / setting issue rather than a framework bug. 
https://stackoverflow.com/questions/67090107/flutter-release-apk-cannot-connect-the-internet-on-android-11-0-mobile-device-b
https://www.flutterclutter.dev/flutter/troubleshooting/no-internet-connection-in-release-build/2020/93/
https://stackoverflow.com/questions/61809033/flutter-app-doesnt-connect-to-internet-after-realse

**Comment by ltsolutionviet** [comment]
Finally i have found problem.
Release mode use
`minifyEnabled true`
It is reason flutter module can't connect the internet.
Solution
update proguard file
`-keep class com.module.flutter_module.**{ *; }
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-keep class io.flutter.embedding.**  { *; }
-dontwarn io.flutter.embedding.**`
