### ISSUE TITLE
links broken on flutter webpage https://github.com/flutter/flutter/wiki/Creating-Responsive-Apps

### ISSUE THREAD

**Issue by ride4sun** [flutter/flutter#13323]
There are quite a few broken links:
https://github.com/flutter/flutter/wiki/Creating-Responsive-Apps

**Comment by sethladd** [comment]
Thanks for the report!

**Comment by sethladd** [comment]
cc @mjohnsullivan

**Comment by mjohnsullivan** [comment]
Links have been updated and should now resolve correctly.
