### ISSUE TITLE
Engine artifacts are not being uploaded

### ISSUE THREAD

**Issue by Jasguerrero** [flutter/flutter#133206]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

On my 1p CP https://github.com/flutter/flutter/pull/133202 all the builds for Linux and Mac are failing due to not finding the engine artifacts although they were all build on https://flutter-dashboard.appspot.com/#/build?repo=engine&branch=flutter-3.14-candidate.7

**Comment by drewroengoogle** [comment]
I think this is due to a recent change on my end with BCID validation. Reverting the change here: https://flutter-review.googlesource.com/c/recipes/+/50101

**Comment by drewroengoogle** [comment]
I will cherrypick this revert into the candidate branch as well

**Comment by Jasguerrero** [comment]
Engine artifacts are uploaded after revert
