### ISSUE TITLE
Enable autosubmit for assets-for-api-docs repo

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#133274]
[assets-for-api-docs](https://github.com/flutter/assets-for-api-docs) does not have autosubmit enabled.

**Comment by godofredoc** [comment]
@ricardoamador FYI

**Comment by ricardoamador** [comment]
On it!

**Comment by godofredoc** [comment]
Awesome, thank you!

**Comment by ricardoamador** [comment]
Okay I added it but it looks like it sent a request. Are you able to accept it?

**Comment by godofredoc** [comment]
Accepted the request!

**Comment by ricardoamador** [comment]
Okay I see an autoroll open with the autosubmit label added to it. Is the bot added as a pusher? That would be the only other thing I believe.

**Comment by ricardoamador** [comment]
Oh wait nevermind. Wrong repo. We just need a pull request now.

**Comment by godofredoc** [comment]
@ricardoamador is branch protection what we are missing for this bug?

**Comment by ricardoamador** [comment]
I don't know for sure as it looks like no one is using the 'autosubmit' label. I just asked on the newest open pull request so we shall see what happens.

**Comment by ricardoamador** [comment]
Still waiting for someone to add the 'autosubmit' label here: https://github.com/flutter/assets-for-api-docs/pull/226

**Comment by keyonghan** [comment]
Autosubmit bot has been used in the repo. Marking as closed.
