### ISSUE TITLE
[Impeller] Have a rough concept of a frame interval.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#133213]
Impeller doesn't have the concept of a frame. However, a rough idea of a single frame interval elapsing would be useful in making decisions around resource pooling and reuse.

Today, such a thing already exists somewhat in the Vulkan backend. Since the context owns a swapchain, [everytime a swapchain image requested, we equate that event to the previous frame interval elapsing](https://github.com/flutter/engine/blob/c380d1a6904deb4a7bc5234141dcdfdcf5029345/impeller/renderer/backend/vulkan/surface_context_vk.cc#L69).

We can generalize this concept to all backends and make some pooling be part of the HAL in an backend agnostic manner.

**Comment by chinmaygarde** [comment]
cc @bdero @jonahwilliams

**Comment by jonahwilliams** [comment]
We have a rough concept of a frame interval now.
