### ISSUE TITLE
Scrollable widgets should have parameter to allow/disallow multiple finger scrolling.

### ISSUE THREAD

**Issue by qiqetes** [flutter/flutter#133247]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

When implementing InteractiveViewer inside of Scrollable widget, most of the time, the onScale gesture is not detected because the Drag gesture is detected by the Scrollable widget.

The biggest problem is when you try to pinch (onScale) in the direction of the scroll. The timing between your two fingers has to be perfect (since in the emulator works all the time, simultaneous touches), but in real device, with human interaction, the result is that the onScale is almost never triggered.

### Proposal

Allow a parameter to disallow the two finger scrolling in Scrollable Widgets (i.e: SingleChildScroll, ListView...).

**Comment by Piinks** [comment]
Can you provide a code sample illustrating the issue?
