### ISSUE TITLE
[Impeller] Create a native Android app that with effects identical to that of a Flutter app for comparison.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#133209]
Today, we are comparing the performance of Impeller with the legacy backend.

However, there is no application for us to test how something that uses identical effects and features but using native Android frameworks performs.

**Comment by jonahwilliams** [comment]
I don't think we're ever going to do this so I'm closing the issue. its not clear how useful it would be in our exploration of Impeller performance; we should start with a comparison to Skia Flutter applications and go from there.
