### ISSUE TITLE
[Web] TextField and TextFormField don't show text while in edit mode in MS Edge on Windows 10

### ISSUE THREAD

**Issue by tporcham** [flutter/flutter#133232]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Open https://dartpad.dev/?id=387be773179a32f3698dcbd982e1bda7 and run the sample.
Try to enter some text in the text field.

This issue was created on request of the DartPad support team, see also https://github.com/dart-lang/dart-pad/issues/2626

Browser and OS version:
Browser:
MS Edge

Version:
Microsoft Edge | 115.0.1901.203 (Offizielles Build) (64-Bit)
Revision | a5a2b1779bcfe71f081bc9104cca968d420a89ac
Chromium-Version | 115.0.5790.171
Operating System| Windows 10 Version 22H2 (Build 19045.3208)
JavaScript | V8 11.5.17.12

Are you using any extensions/plugins that affect website behavior
No.

Are there any warnings or errors in your browser's JavaScript console?
General warnings about usage of deprecated functions are shown.

Machine
Operating system:
Windows

Version:
10

DartPad shown Based on Flutter 3.13.0 Dart SDK 3.1.0

The issue also appears on https://flutter.github.io/samples/web/material_3_demo/ with Edge on Windows. The fields in the text inpts section don't work as expected.
![image](https://github.com/flutter/flutter/assets/8996358/cd1018c7-ed93-4b20-98cf-f5e1d160dfe1)

### Expected results

Text field works as normal and the entered text is shown

### Actual results

While entering the text one cannot see what was entered.

### Code sample

<details><summary>Code sample</summary>

see https://dartpad.dev/?id=387be773179a32f3698dcbd982e1bda7
```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [TextField].

void main() => runApp(const TextFieldExampleApp());

class TextFieldExampleApp extends StatelessWidget {
  const TextFieldExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: TextFieldExample(),
    );
  }
}

class TextFieldExample extends StatefulWidget {
  const TextFieldExample({super.key});

  @override
  State<TextFieldExample> createState() => _TextFieldExampleState();
}

class _TextFieldExampleState extends State<TextFieldExample> {
  late TextEditingController _controller;

  @override
  void initState() {
    super.initState();
    _controller = TextEditingController();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.grey,
      body: Center(
        child: TextField(
          controller: _controller,
          onSubmitted: (String value) async {
            await showDialog<void>(
              context: context,
              builder: (BuildContext context) {
                return AlertDialog(
                  title: const Text('Thanks!'),
                  content: Text(
                      'You typed "$value", which has length ${value.characters.length}.'),
                  actions: <Widget>[
                    TextButton(
                      onPressed: () {
                        Navigator.pop(context);
                      },
                      child: const Text('OK'),
                    ),
                  ],
                );
              },
            );
          },
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

<video src="https://github.com/flutter/flutter/assets/8996358/595febdd-9c45-4e1c-bfb4-504fa7c6e11e">

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
In DartPad there is no Flutter Doctor I guess.
```

</details>

**Comment by tporcham** [comment]
The issue does not appear when I use FireFox, it can only be reproduced in MS Edge.

**Comment by dam-ease** [comment]
Hi @tporcham. Thanks for filing this issue. This doesn't seem to reproduce on an Edge browser on Macbook, I see it might be peculiar to Windows 10 from your description though. Please can you try running the code sample in IDE and on the Edge browser to see if this issue reproduces?

**Comment by itsgits01** [comment]
Hey @tporcham , I have identified that a particular issue doesn't reproduce on the Edge browser on Windows 11. The issue seems to be with Windows 10.

**Comment by tporcham** [comment]
> 

Sorry I don't have the IDE installed and cannot install it currently - I was just using DartPad

**Comment by tporcham** [comment]
> Hey @tporcham , I have identified that a particular issue doesn't reproduce on the Edge browser on Windows 11. The issue seems to be with Windows 10.

Yes can be an issue with the Edge browser in the specified version on Windows 10 only.

**Comment by dam-ease** [comment]
Hi @tporcham. Thanks for your response. We can't seem to reproduce this on our end as it seems to work fine (testing on the latest version of the Edge browser Version 116.0.1938.54 (Official build) (64-bit) on Windows 10). Can you check/confirm with the latest version of the Edge browser? 

> Sorry I don't have the IDE installed and cannot install it currently - I was just using DartPad

Also, per this, please try running this from Command Prompt to see if the issue reproduces.

Thank you!

**Comment by tporcham** [comment]
Hi guys,

I think you can just close this issue.
I found out the issue does not appear when I disable the browser extensions.
I only have one browser extension called "Netwrix Password Secure". Somehow this extension breaks the flutter text fields. It seems the extension tries to grab values from fields on a page by changing the source (adding additional input fields (?))- this might cause the issue. 

Anyway, thanks for your support - please close the issue.
