### ISSUE TITLE
Regression: `ExpansionPanelList`'s `expansionCallback` reports the wrong `expanded` state

### ISSUE THREAD

**Issue by Zazo032** [flutter/flutter#133242]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Go to https://api.flutter.dev/flutter/material/ExpansionPanelList-class.html
2. Inside `expansionCallback`, before `setState`, add this:
```dart
print('current state ($index): $isExpanded');
```
3. Check that, when trying to open a closed `ExpansionPanelList`, the reported `expanded` value is `true` instead of `false`

### Expected results

The `expanded` value should be `false` when the `ExpansionPanelList` is closed.
The `ExpansionPanelList` should open after tapping it.

### Actual results

The `expanded` value is `true` when the `ExpansionPanelList` is closed.
The `ExpansionPanelList` doesn't open after tapping it.

### Code sample

https://api.flutter.dev/flutter/material/ExpansionPanelList-class.html#material.ExpansionPanelList.1

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.1, on Microsoft Windows [Versi¢n 10.0.22621.2215], locale es-ES)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2022.3)
[√] Connected device (3 available)
[√] Network resources

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Thanks for the report but this's fixed by https://github.com/flutter/flutter/pull/132837 and it's available on master. You can also check it here on [master API docs](https://master-api.flutter.dev/flutter/material/ExpansionPanelList-class.html).

Closing as fixed.
