### ISSUE TITLE
[CP] 3.13: [Impeller] Apply color blends on the CPU; fix mask blurs and the Gaussian blur coverage hint.

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#133360]
### Issue Link

https://github.com/flutter/flutter/issues/132936

### Commit Hash

https://github.com/flutter/engine/commit/53595c937df156b932850807869f539c15042919

### Target

stable

### PR Link

https://github.com/flutter/engine/pull/45130

### Changelog Description

This is a combined cherry-pick of two dependent commits: https://github.com/flutter/engine/commit/81d5adb28840dd5a71a2b717ab23c1be6593689d and https://github.com/flutter/engine/commit/53595c937df156b932850807869f539c15042919.

The first commit enables applying color filters on the CPU, and the second commit fixes issues in the generic mask blurring path as well as geometry coordinate mapping problems in the Gaussian blur.

Medium risk due to large cherry-pick and the fact that this is a forward fix. This problem is difficult to fix without a series of risky reverts, and so this is a forward fix.

### Impacted Users

This issue affects Impeller users on iOS.

### Impact Description

This fixes a variety of rendering problems with Impeller shadows which are exacerbated by the presence of dirty regions. When elements are moving over the top of a non-animated shadow, the shadow may sometimes render as faded or become invisible. 

### Workaround

There are no simple workaround for this issue.

### Risk

medium

### Test Coverage

yes

### Validation Steps

To test, run the example Flutter app in https://github.com/flutter/flutter/issues/132936 and verify that the blur does not cut out while scrolling.
Alternatively, run the `AiksTest.ClippedBlurFilterRendersCorrectly` playground golden and verify that the blur does not dim out as it approaches the top edge of the screen.

**Comment by zanderso** [comment]
This is a bit hefty for a stable CP. Maybe the right place to CP this is the 3.14 beta? @CaseyHillers @itsjustkevin is 3.14 still accepting CPs?

**Comment by itsjustkevin** [comment]
Would love to get this into 3.14 @zanderso.  @bdero if you still desire the cherry-pick could you push to the 3.14 branch instead?

**Comment by bdero** [comment]
I created a new CP request for 3.14 which is simpler because we don't have to pull in multiple commits: https://github.com/flutter/flutter/issues/133511

Closing these one out rather than repurposing it (just in case we need to change our mind about 3.13 -- this issue is teetering on severe IMO).
