### ISSUE TITLE
display information message that video demo isn't supported on the iOS Simulator

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#13332]
The video demo isn't supported on the iOS Simulator (as it doesn't support video playback). Rather than just displaying two empty video cards, we should just show a centered information piece of text with something like 'This demo isn't supported on the iOS Simulator'.

You can ask if the app is on a an iOS simulator with `Platform.isIOS` and [isPhysicalDevice](https://www.dartdocs.org/documentation/device_info/0.0.5/device_info/IosDeviceInfo/isPhysicalDevice.html) from the `device_info` package.

**Comment by sigurdm** [comment]
This has been done some time ago
