### ISSUE TITLE
UnsupportedError RenderSliverFixedExtentBoxAdaptor.getMinChildIndexForScrollOffset

### ISSUE THREAD

**Issue by Reketaka** [flutter/flutter#133322]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Sorry but it's report full duplicate https://github.com/flutter/flutter/issues/107893

I have same error on firebase crashlogs on same devices

But for a long time don't have a fixed result

**Comment by dam-ease** [comment]
Hi @Reketaka. Thanks for filing this. Please can you provide more information on this? More specifically, please provide the information indicated below:

- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of flutter doctor -v
- Reproduction steps

**Comment by Reketaka** [comment]
> Hi @Reketaka. Thanks for filing this. Please can you provide more information on this? More specifically, please provide the information indicated below:
> 
>     * A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
> 
>     * The output of flutter doctor -v
> 
>     * Reproduction steps

I can't write Reproduction steps

**Comment by Reketaka** [comment]
> Hi @Reketaka. Thanks for filing this. Please can you provide more information on this? More specifically, please provide the information indicated below:
> 
>     * A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
> 
>     * The output of flutter doctor -v
> 
>     * Reproduction steps

[✓] Flutter (Channel stable, 3.13.0, on Ubuntu 21.10 5.13.0-52-generic, locale ru_RU.UTF-8)
    • Flutter version 3.13.0 on channel stable at /home/fvm/versions/3.13.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (10 дней назад), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/Android/Sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /home/android-studio-2021.3.1.17-linux/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /home/android-studio-2021.3.1.17-linux/android-studio
    • Flutter plugin version 71.0.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2021.2)
    • Android Studio at /opt/android-studio-2021.2.1/android-studio
    • Flutter plugin version 71.2.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 21.10 5.13.0-52-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 97.0.4692.71

[✓] Network resources
    • All expected network resources are available.

**Comment by Reketaka** [comment]
> * A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

write code sample later
