### ISSUE TITLE
[Impeller] TextFrame::getBounds() is wrong and/or slow

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#133388]
@jonahwilliams in https://github.com/flutter/engine/pull/45148#pullrequestreview-1597023589:

> If our text frame bounds computation is wrong, that is going to bubble up to more places too.
Can we either 1) make impeller::TextFrame use the bounds data from the SkTextFrame 2) fix the impeller::TextFrame computation?
>
> Actually in general TextFrame::GetBounds is super hot, so we might want to take the SkiaBounds in the constructor and use them cached, see https://github.com/flutter/engine/pull/45131#discussion_r1306202240

**Comment by jonahwilliams** [comment]
I have a patch for this one, its been on my least of cleanups since its a hot function in DL dispatching anyway.
