### ISSUE TITLE
flutter textfield words candidate always jump, microsoft pinyin IME,

### ISSUE THREAD

**Issue by red-co** [flutter/flutter#133395]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create an empty project with a text field
2. set initial value to textfied,

use step 1,2 or run this code sample
4.Change input to IME language (e.g. Chinese)
5.select a position to type and observe the issue

### Expected results

https://github.com/flutter/flutter/assets/75922982/09fa2320-00d6-4b9b-855b-5849cc0e106a

### Actual results

https://github.com/flutter/flutter/assets/75922982/ea287a95-9f3f-4782-ad4c-a0ed7ea39f5d

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Counter',
      home: Scaffold(body: InputPage()),
    );
  }
}

final text =
    "flutter wikipedia zh\",\"Flutter是由Google创建的开源UI软件开发工具包。它用于从单个代码库为任何Web浏览器开发跨平台应用程序，[4] Fuchsia，Android，iOS，Linux，macOS和Windows。[5]2015年首次描述，[6][7]Flutter于2017年5月发布。[1]";

class InputPage extends StatefulWidget {
  const InputPage({super.key});

  @override
  State<InputPage> createState() => _InputPageState();
}

class _InputPageState extends State<InputPage> {
  final _textcontroller = TextEditingController(text: text);
  @override
  Widget build(BuildContext context) {
    return Center(
      child: TextField(
        controller: _textcontroller,
        maxLines: null,
        textInputAction: TextInputAction.newline,
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [版本 10.0.22621.2134], locale zh-CN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.7.0)
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.81.1)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by red-co** [comment]
Hello, By reading the source code, I actually fixed this problem in flutter/sec/widget/editable_text.dart,

**Comment by red-co** [comment]
this is code
```dart
  void _updateComposingRectIfNeeded() {
    final TextRange composingRange = _value.composing;
    assert(mounted);
    Rect? composingRect =
        renderEditable.getRectForComposingRange(composingRange);
    // Send the caret location instead if there's no marked text yet.
    if (composingRect == null) {
      assert(!composingRange.isValid || composingRange.isCollapsed);

// ------
      final TextSelection? selection = renderEditable.selection;
      if (selection == null || !selection.isValid || !selection.isCollapsed) {
        return;
      }
// ----

      final int offset =
          composingRange.isValid ? composingRange.start : selection.baseOffset;
      composingRect =
          renderEditable.getLocalRectForCaret(TextPosition(offset: offset));
    }
    _textInputConnection!.setComposingRect(composingRect);
  }
```
i replace start:0 to renderEditable.selection,

**Comment by red-co** [comment]
Can someone help me PR it? I don't know how to submit this patch to flutter,

**Comment by huycozy** [comment]
Hi @red-co 
I tested this several times and noticed the behavior is similar to a known issue at https://github.com/flutter/flutter/issues/128323 (see https://github.com/flutter/flutter/issues/128323#issuecomment-1583128638). So I will close this issue to centralize on that one. 

For the fix/PR, feel free to do that. For more details, please see [Developing for Flutter](https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md#developing-for-flutter). Thank you for your contribution.
