### ISSUE TITLE
Screen orientation change cause initial route call

### ISSUE THREAD

**Issue by razer-santhosh** [flutter/flutter#133379]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I'm using 
MaterialApp.router(
                routeInformationProvider: routesData().routeInformationProvider,
                routeInformationParser: routesData().routeInformationParser,
                routerDelegate: routesData().routerDelegate,
)

and for routes data I'm using 

routesData() {
  final GoRouter router = GoRouter(
    routes: <GoRoute>[
      GoRoute(
        path: '/',
        name: '/',
        redirect: (context, state) {
          return token != null
              ? baseSideMenu.isNotEmpty
                  ? baseSideMenu[0].route
                  : "/dashboard"
              : '/login';
        },
      ),])
}

### Expected results

when I change orientation in any page, I want that page to be in desired orientation

### Actual results

whenever I try to change orientation, It call the routes initial route '/', resulting in return to dashboard page

### Code sample

I'm using 
MaterialApp.router(
                routeInformationProvider: routesData().routeInformationProvider,
                routeInformationParser: routesData().routeInformationParser,
                routerDelegate: routesData().routerDelegate,
)

and for routes data I'm using 

routesData() {
  final GoRouter router = GoRouter(
    routes: <GoRoute>[
      GoRoute(
        path: '/',
        name: '/',
        redirect: (context, state) {
          return token != null
              ? baseSideMenu.isNotEmpty
                  ? baseSideMenu[0].route
                  : "/dashboard"
              : '/login';
        },
      ),])
}

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

[√] Flutter (Channel stable, 3.13.0, on Microsoft Windows [Version 10.0.22621.2134], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[!] Android Studio (version 2021.3)
    X Unable to determine bundled Java version.
[√] Android Studio (version 2022.2)
[√] VS Code (version 1.72.1)
[√] Connected device (4 available)
[√] Network resources

**Comment by opxdelwin** [comment]
@razer-santhosh Thanks for filing this issue, for better formatting, enclose your code within (```) on both ends, and attach a `minimal reproduceable code` for testing.

**Comment by razer-santhosh** [comment]
> @razer-santhosh Thanks for filing this issue, for better formatting, enclose your code within (```) on both ends, and attach a `minimal reproduceable code` for testing.
this is the code I'm using in main.dart
```MaterialApp.router(
                routeInformationProvider: routesData().routeInformationProvider,
                routeInformationParser: routesData().routeInformationParser,
                routerDelegate: routesData().routerDelegate,
                title: appTitle,
                locale: _locale,
                supportedLocales: const [
                  Locale("en", "US"),
                  Locale("ta", "IN")
                ],
                localizationsDelegates: const [
                  ApplicationLocalizations.delegate,
                  GlobalMaterialLocalizations.delegate,
                  GlobalWidgetsLocalizations.delegate,
                  GlobalCupertinoLocalizations.delegate,
                ],
                localeResolutionCallback: (locale, supportedLocales) {
                  for (var supportedLocale in supportedLocales) {
                    if (supportedLocale.languageCode == locale!.languageCode &&
                        supportedLocale.countryCode == locale.countryCode) {
                      return supportedLocale;
                    }
                  }
                  return supportedLocales.first;
                },
                debugShowCheckedModeBanner: false,
                theme: MyTheme.appStatusBarColor);```

this is the routes data

```routesData() {
  final GoRouter router = GoRouter(
    routes: <GoRoute>[
      GoRoute(
        path: '/',
        name: '/',
        redirect: (context, state) {
          return token != null
              ? dashboard_available == 1
                  ? '/reports'
                  : '/reports'
              : '/login';
        },
      ),
      GoRoute(
        path: '/reports',
        name: '/reports',
        pageBuilder: (BuildContext context, GoRouterState state) {
          final isOnline = Provider.of<ConnectivityProvider>(context).isOnline;
          final isUpdateAvailable =
              Provider.of<AppUpgradeProvider>(context).isUpdateAvailable;
          bottomIndex = dashboard_available == 1 ? 1 : 0;
          var child = (isOnline != null && !isOnline)
              ? const NoInternet()
              : (isUpdateAvailable)
                  ? const AppUpdate()
                  : const Report();
          return customTransitionPage(state.pageKey, child);
        },
      )]);
return router;```

after, I pushed some pages, when user click on full screen icon, I'm changing screen orientation to landscape, then it calling the routes data function, resulting in dashboard page pushed to the route

**Comment by huycozy** [comment]
@razer-santhosh I checked this with below minimal sample code with 2 pages but can't reproduce the issue. The steps I tried are:

1. Open app
2. Navigate to 2nd page. Rotate the device screen to landscape

Result: The 2nd page stays without being returned to page 1 automatically.

<details>
<summary>Minimal sample code</summary>

```dart
// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

/// This sample app shows an app with two screens.
///
/// The first route '/' is mapped to [HomeScreen], and the second route
/// '/details' is mapped to [DetailsScreen].
///
/// The buttons use context.go() to navigate to each destination. On mobile
/// devices, each destination is deep-linkable and on the web, can be navigated
/// to using the address bar.
void main() => runApp(const MyApp());

/// The route configuration.
final GoRouter _router = GoRouter(
  routes: <RouteBase>[
    GoRoute(
      path: '/',
      builder: (BuildContext context, GoRouterState state) {
        return const HomeScreen();
      },
      routes: <RouteBase>[
        GoRoute(
          path: 'details',
          builder: (BuildContext context, GoRouterState state) {
            return const DetailsScreen();
          },
        ),
      ],
    ),
  ],
);

/// The main app.
class MyApp extends StatelessWidget {
  /// Constructs a [MyApp]
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerConfig: _router,
    );
  }
}

/// The home screen
class HomeScreen extends StatelessWidget {
  /// Constructs a [HomeScreen]
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Home Screen')),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            ElevatedButton(
              onPressed: () => context.go('/details'),
              child: const Text('Go to the Details screen'),
            ),
          ],
        ),
      ),
    );
  }
}

/// The details screen
class DetailsScreen extends StatelessWidget {
  /// Constructs a [DetailsScreen]
  const DetailsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Details Screen')),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <ElevatedButton>[
            ElevatedButton(
              onPressed: () => context.go('/'),
              child: const Text('Go back to the Home screen'),
            ),
          ],
        ),
      ),
    );
  }
}

```
</details>

In order to address the issue properly, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so that we may verify this.
