### ISSUE TITLE
Cocoon backend not deploying due to SLSA validation

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#133376]
This is because the SLSA provenance validation has been failing.

**Comment by godofredoc** [comment]
Making this issue a P1

**Comment by godofredoc** [comment]
Moving to P2 as the issue has been mitigated.

**Comment by ricardoamador** [comment]
Is this mitigated based on the change you made but still with the outstanding bug to slsa-verifier?

**Comment by ricardoamador** [comment]
Awesome! Thanks for confirming.

**Comment by drewroengoogle** [comment]
This is continuing to occasionally fail - https://github.com/flutter/cocoon/pull/3032 was an attempt to resolve, but now running into issues actually installing slsa-verifier, so I am going to follow their readme to rebuild the slsa-verifier tooling folder based on the latest version.
