### ISSUE TITLE
iOS tests not all running

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#133301]
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Production%20Engine%20Drone/130722/overview

From

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20mac_unopt/2715/overview

This should be running
```
    "tests": [
      {
        "language": "python3",
        "name": "Tests for ios_debug_sim",
        "parameters": [
          "--variant",
          "ios_debug_sim",
          "--type",
          "objc",
          "--engine-capture-core-dump",
          "--ios-variant",
          "ios_debug_sim"
        ],
        "script": "flutter/testing/run_tests.py"
      },
      {
        "name": "Scenario App Integration Tests",
        "parameters": [
          "ios_debug_sim"
        ],
        "script": "flutter/testing/scenario_app/run_ios_tests.sh"
      }
```

but is instead doing nothing.

Suspecting this is somehow due to https://github.com/flutter/engine/pull/44836 and https://github.com/flutter/engine/pull/44920

**Comment by drewroengoogle** [comment]
Just catching up now. It seems that the latest mac_unopt build ran the Scenario App Integration Tests. Did https://github.com/flutter/engine/pull/45097 resolve the issue?

**Comment by godofredoc** [comment]
This is fixed by https://github.com/flutter/engine/pull/45097
