### ISSUE TITLE
Deprecate old accept callbacks in DragTarget

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#133347]
Follow up to https://github.com/flutter/flutter/pull/131545

We discussed in the issue, the older callbacks (onAccept, onWillAccept), should be deprecated in favor of the new onAcceptWithDetails and onWillAcceptWithDetails.
These should include dart fixes as well to aid in migration.

cc @chinmoy12c who expressed interest in working on this

**Comment by chinmoy12c** [comment]
> Follow up to #131545
> 
> We discussed in the issue, the older callbacks (onAccept, onWillAccept), should be deprecated in favor of the new onAcceptWithDetails and onWillAcceptWithDetails. These should include dart fixes as well to aid in migration.
> 
> cc @chinmoy12c who expressed interest in working on this

Hey, @Piinks could you point me to a reference PR/documentation that elaborates the process of deprecation and how to create a dart fix?

**Comment by Piinks** [comment]
Sure thing! 

The deprecation policy is here: https://github.com/flutter/flutter/wiki/Tree-hygiene#deprecations
All of the details for writing dart fixes are here: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

A rename is likely the type of fix this will need, there are a lot of examples under fix_data: https://github.com/flutter/flutter/tree/master/packages/flutter/lib/fix_data

Here is an example of a deprecation being add with a fix: https://github.com/flutter/flutter/pull/96174

Let me know how this goes, happy to review and advise. Thanks for continuing to contribute!
