### ISSUE TITLE
It doesn't save data when app background

### ISSUE THREAD

**Issue by Demirzekk** [flutter/flutter#133315]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

SharedPreferences doesn't work when app background. it doesn't work on both Android and IOS. If app totally close or when opened, it work. I need to save notification data when app resumed. 

### Expected results

SharedPreferences should be able to save any LifeCyleState

### Actual results

it only works totally closed or open 

### Code sample

// this code works everytime. But SharedPreferences code not work when app resume in background
@pragma('vm:entry-point')
  static saveNotification(RemoteMessage message) async {
    var prefs = await SharedPreferences.getInstance();
    List<String> messageList = prefs.getStringList("notification_list") ?? [];
    messageList.insert(0, jsonEncode(message.toMap()));
    prefs.setStringList("notification_list", messageList);
    log("Notification:" + message.toString());
  }

### Screenshots or Video

 
<img width="1057" alt="Ekran Resmi 2023-08-25 11 56 37" src="https://github.com/flutter/flutter/assets/30274717/b0d6306b-9d48-4095-a779-0837a8a85605">

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.4.1 22F770820d darwin-arm64, locale tr-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.81.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

**Comment by dam-ease** [comment]
Hi @Demirzekk. Thanks for filing this. Can you try this https://github.com/flutter/flutter/issues/60892#issuecomment-654129519 if it works in your use case?

**Comment by Demirzekk** [comment]
Hi @dam-ease, firstly thank you for your interest. unfortunately its not work. its Already IOS has same problem.

**Comment by stuartmorgan** [comment]
Please provide a reproducible test case, and a clear description of the problem. You've only shown partial code, and a screenshot (please don't use screenshots of text, as requested in the issue template) of a log that doesn't appear to show any problems. It's not at all clear what "doesn't work" actually means, specifically, in this report.
