### ISSUE TITLE
[Engine] Not sure how to update goldens in `platform/embedder/fixtures`

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#133375]
In https://github.com/flutter/engine/pull/44705, a number of tests fail because the outputted gradient golden files, such as [`gradient_xform.png`](https://github.com/flutter/engine/blob/f1464b49c4fff8b2a72ed978fbb3198e3f0db176/shell/platform/embedder/fixtures/gradient_xform.png) are now dithered, so exact pixel tests fail.

I would update them, but I couldn't find instructions how to either within the code or the Wiki.

**Comment by chinmaygarde** [comment]
When the failure occurs, the error message will generate the actual image as well as the expectation in the out directory and dump the paths to those files. You need to copy those files to the fixtures location. Its not great and maybe we should we the gold instance we have since wired up.

**Comment by matanlurey** [comment]
One of the tough parts is it looks like some of the tests only run on Linux:

> ../../flutter/shell/platform/embedder/tests/embedder_unittests.cc:1332: Skipped
> Skipping golden tests on non-Linux OSes

**Comment by matanlurey** [comment]
Is there a way to download the artifacts/build from LUCI?
