### ISSUE TITLE
[Impeller] Improve `AiksLayer::IsReplacing`

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#133361]
We should do the following:

- [ ] Collect statistics similar to `DisplayListLayer`
- [ ] Do a deeper comparison of the `EntityPass` if the pointers do not actually match, at least to a certain point - for example, DisplayListLayer will compare DLs of up to 10kb. `EntityPass` is potentially more expensive to compare right now though.

**Comment by jonahwilliams** [comment]
We decided not to proceed with the AiksLayer approach. Closing for now.
