### ISSUE TITLE
Cupertino Icons Paw icon should not be filled

### ISSUE THREAD

**Issue by khatruong2009** [flutter/flutter#133382]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. import 'package:flutter/cupertino.dart'
2. use CupertinoIcons.paw. 
3. use CupertinoIcons.paw_solid

### Expected results

The two icons should be different. The CupertinoIcons.paw should be an outline not filled in. 

### Actual results

The two icons are exactly the same. They are both filled in versions of the paw icon.

### Code sample

<details><summary>Code sample</summary>

```dart
'Pets': CupertinoIcons.paw
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

<img width="358" alt="Screenshot 2023-08-25 at 11 44 42 PM" src="https://github.com/flutter/flutter/assets/64438356/2df330b1-e5f6-4403-a9d5-c95ecec3c062">

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.1, on macOS 13.5.1 22G90 darwin-arm64,
    locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version
    34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.81.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@khatruong2009 Let's track this issue in https://github.com/flutter/flutter/issues/82634 which is an umbrella issue to add any missing and incorrectly rendered icons.

You can share your findings in that issue for better tracking.
