### ISSUE TITLE
when using open Container the screen is built twice (animations package)

### ISSUE THREAD

**Issue by ANGEEEL7U7** [flutter/flutter#133399]
Good evening, does anyone who has already used the open container of the animations package know why my screen is built twice?

CODE
![code](https://github.com/flutter/flutter/assets/82860569/2347d757-6ee4-463c-ab62-aa5a0e9e1829)

PRINT
![Captura de pantalla de 2023-08-26 20-28-48](https://github.com/flutter/flutter/assets/82860569/eb25e84b-ccee-47f7-99f3-cf77c15d7328)

VIDEO

https://github.com/flutter/flutter/assets/82860569/22835112-4408-480f-b2ae-8892ad5c1b16

**Comment by darshankawar** [comment]
@ANGEEEL7U7 
Please don't post screenshots of the code as they are not useful for us to copy and then run to verify.
Please provide[ complete runnable code sample](https://stackoverflow.com/help/minimal-reproducible-example) without any third party package implementation in formatted text that we can directly copy paste and run. Also provide `flutter doctor -v` on which you are seeing the reported behavior.
