### ISSUE TITLE
Regarding In App Purchase.. How can I use AppStoreServerAPI with transactionId

### ISSUE THREAD

**Issue by YoungrakSon** [flutter/flutter#133430]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

https://developer.apple.com/documentation/storekit/in-app_purchase/original_api_for_in-app_purchase/validating_receipts_with_the_app_store

verifyReceipt endpoint is deprecated.. and Apple wants us to use AppStoreServerAPI with transactionId instead of verifyReceipt. 

but it looks like purchaseDetails.verificationData.serverVerificationData doesn't contain the transactionId data.. 

How can I get the transactionId value to use the AppStoreServerAPI to verify purchase is authentic? or is it yet not available in flutter in app purchase package? 

### Proposal

I want to use AppStoreServerAPI with transactionId..

**Comment by YoungrakSon** [comment]
I found 

https://github.com/apple/app-store-server-library-node 

if you send request to AppStoreServerAPI using that node package 

you can just get transactionId by receipt 


or 

purchaseId property of purchaseDetails is equivalent to the transactionId 

I checked it

**Comment by darshankawar** [comment]
> you can just get transactionId by receipt
> 
> or
> 
> purchaseId property of purchaseDetails is equivalent to the transactionId

@YoungrakSon 
Does this mean you can use `purchaseId` instead of `transactionId` that can be used with `AppStoreServerAPI` ?

**Comment by YoungrakSon** [comment]
> > you can just get transactionId by receipt
> > or
> > purchaseId property of purchaseDetails is equivalent to the transactionId
> 
> @YoungrakSon Does this mean you can use `purchaseId` instead of `transactionId` that can be used with `AppStoreServerAPI` ?

Yes 
Just use purchaseId to query AppStoreServerAPI

**Comment by darshankawar** [comment]
Does that mean the issue you raised is solvable currently and works already ?
