### ISSUE TITLE
[Proposal] Show error before runtime when using color param AND decoration param at the same time

### ISSUE THREAD

**Issue by Fernandomr88** [flutter/flutter#133456]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Whenever you're implementing a `Container` for example and you use both `color` and `decoration` at the same time, there's no error shown but an exception is thrown only when the widget is built in runtime, not even on compilation.
Code example:
```dart
Container(
  height: 150,
  width: 150,
  color: Colors.white, ///<- color
  decoration: BoxDecoration(borderRadius: BorderRadius.circular(100), color: Colors.white), //<- color again
  child: Image.asset(
    'assets/img/X.gif',
    height: 100,
  ),
));
```

![image](https://github.com/flutter/flutter/assets/14304128/deefa638-e3f5-4a77-9428-f3fe2538a7be)

### Proposal

My proposal is that the error is shown on "coding time", just as any errors that are shown such as this one for example:

![image](https://github.com/flutter/flutter/assets/14304128/92869f1b-9f26-4586-81ab-a752123de301)

**Comment by darshankawar** [comment]
Thanks for the report @Fernandomr88 
The example you gave in proposal section actually depicts a type check error and are most commonly thrown during coding time rather than runtime through Dart. You may read about the common type check problems here: https://dart.dev/guides/language/sound-problems

The one you highlighted related to Container is actually a code implementation issue which has been documented for reference:

```
/// The `color` and `decoration` arguments cannot both be supplied, since
  /// it would potentially result in the decoration drawing over the background
  /// color. To supply a decoration with a color, use `decoration:
  /// BoxDecoration(color: color)`.
```

I am not sure if the tool / framework will be able to identify whether `color` and `decoration` properties are being used during coding time.

**Comment by Fernandomr88** [comment]
I see, can at least it be detected during compile time or even by linter?

This could prevent some issues during production time, since that problem is only detected when that widget is rendered

**Comment by darshankawar** [comment]
I think there's no way to ensure that an assert is run at compile time. I see [this](https://github.com/flutter/flutter/issues/94416) similar issue you can check for reference which probably talks about same case as yours but just for another widget.

**Comment by Fernandomr88** [comment]
> I think there's no way to ensure that an assert is run at compile time. I see [this](https://github.com/flutter/flutter/issues/94416) similar issue you can check for reference which probably talks about same case as yours but just for another widget.

How about at flutter linter? 🤔 My point is that this could prevent problems, exceptions and crashes at runtime

**Comment by darshankawar** [comment]
> How about at flutter linter?

You may file a proposal for that package https://pub.dev/packages/flutter_lints. Although it'll be in same repo as this, but just using the package template.

**Comment by Fernandomr88** [comment]
done
