### ISSUE TITLE
[local_auth] Extra step after biometric auth success

### ISSUE THREAD

**Issue by fauzipadlaw** [flutter/flutter#133427]
### Is there an existing issue for this?

- [X] I have searched the [existing package issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Apackage)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### What package does this bug report belong to?

local_auth

### What target platforms are you seeing this bug on?

Android

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
local_auth:
    dependency: "direct main"
    description:
      name: local_auth
      sha256: "0cf238be2bfa51a6c9e7e9cfc11c05ea39f2a3a4d3e5bb255d0ebc917da24401"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.6"
  local_auth_android:
    dependency: transitive
    description:
      name: local_auth_android
      sha256: "36a78898198386d36d4e152b8cb46059b18f0e2017f813a0e833e216199f8950"
      url: "https://pub.dev"
    source: hosted
    version: "1.0.32"
  local_auth_ios:
    dependency: transitive
    description:
      name: local_auth_ios
      sha256: edc2977c5145492f3451db9507a2f2f284ee4f408950b3e16670838726761940
      url: "https://pub.dev"
    source: hosted
    version: "1.1.3"
  local_auth_platform_interface:
    dependency: transitive
    description:
      name: local_auth_platform_interface
      sha256: "9e160d59ef0743e35f1b50f4fb84dc64f55676b1b8071e319ef35e7f3bc13367"
      url: "https://pub.dev"
    source: hosted
    version: "1.0.7"
  local_auth_windows:
    dependency: transitive
    description:
      name: local_auth_windows
      sha256: "5af808e108c445d0cf702a8c5f8242f1363b7970320334f82e6e1e8ad0b0d7d4"
      url: "https://pub.dev"
    source: hosted
    version: "1.0.9"
```

</details>

### Steps to reproduce

1. Show dialog biometric auth, in this case is face recognition android
2. Auth success, there is this dialog "Face recognition successful. Please continue."

### Expected results

There is no dialog "Face recognition successful. Please continue." after auth success. It will redirect directly to app and return the auth value, which is true if it's successful.

### Actual results

after face recognition success, there is this dialog "Face recognition successful. Please continue." and I have to tap "Continue" to conitnue. User said it only happens on my app, it does not happen on other app using biometric face recognition. The device is Oppo FInd X2.

### Code sample

<details><summary>Code sample</summary>

```dart
await auth.authenticate(
        localizedReason: 'Pindai Biometrik untuk Keamanan',
        authMessages: [
          AndroidAuthMessages(
            signInTitle: 'Verifikasi Biometrik',
            cancelButton: (set || noBack) ? 'Batalkan' : 'Gunakan PIN',
            biometricHint: '',
          ),
        ],
        options: const AuthenticationOptions(
          useErrorDialogs: true,
          stickyAuth: true,
          biometricOnly: true,
        ),
      );
```

</details>

### Screenshots or Videos

<details>
<summary>Screenshots / Video demonstration</summary>

<img width="554" alt="Screenshot 2023-08-28 at 11 38 57 AM" src="https://github.com/flutter/flutter/assets/15975922/4965d202-c2db-47f2-b77b-0e434614c5fc">

</details>

### Logs

<details><summary>Logs</summary>

```console
No logs, it happens on production
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel unknown, 2.0.6, on macOS 13.2 22D49 darwin-arm, locale en)
    • Flutter version 2.0.6 at /Users/efzet/SDKs/flutold
    • Framework revision 1d9032c7e1 (2 years, 4 months ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/efzet/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/efzet/Library/Android/sdk
    • Java binary at: /Users/efzet/.sdkman/candidates/java/current/bin/java
    • Java version OpenJDK Runtime Environment Zulu15.28+13-CA (build 15.0.1+8)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 14.2, Build version 14C18
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[!] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 71.2.2
    • Dart plugin version 212.5744

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Brave Browser 116.1.57.53

! Doctor found issues in 1 category.
```

</details>

**Comment by dam-ease** [comment]
Hi @fauzipadlaw. Thanks for filing this issue. I see you are on an older version of flutter. Please can you upgrade to the latest versions of flutter and the package and help provide some more information on this:

- Does this issue only reproduce on a specific physical device in production as you described i.e can you try on an Android emulator/ physical device in debug mode to verify if this issue reproduces?
- If it does reproduce, kindly share with us a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code.

Thank you

**Comment by fauzipadlaw** [comment]
Sorry that is wrong flutter doctor output. this is the correct one

```
!] Flutter (Channel stable, 3.10.6, on macOS 13.2 22D49 darwin-arm64, locale en)
    • Flutter version 3.10.6 on channel stable at /Users/efzet/fvm/versions/3.10.6
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (7 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/efzet/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/efzet/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 71.2.2
    • Dart plugin version 212.5744

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Brave Browser 116.1.57.53

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

**Comment by fauzipadlaw** [comment]
Q: Does this issue only reproduce on a specific physical device in production as you described i.e can you try on an Android emulator/ physical device in debug mode to verify if this issue reproduces?
A: Yes

**Comment by fauzipadlaw** [comment]
```
final LocalAuthentication auth = LocalAuthentication();
bool authenticated = await auth.authenticate(
        localizedReason: 'Pindai Biometrik untuk Keamanan',
        authMessages: [
          AndroidAuthMessages(
            signInTitle: 'Verifikasi Biometrik',
            cancelButton: (set || noBack) ? 'Batalkan' : 'Gunakan PIN',
            biometricHint: '',
          ),
        ],
        options: const AuthenticationOptions(
          useErrorDialogs: true,
          stickyAuth: true,
          biometricOnly: true,
        ),
      );

if(authenticated) {
// continue doing something
}
```

**Comment by stuartmorgan** [comment]
This system-provided UI likely corresponds to [`setConfirmationRequired`](https://developer.android.com/reference/androidx/biometric/BiometricPrompt.PromptInfo.Builder#setConfirmationRequired(boolean)); have you tried setting `sensitiveTransaction` to `false` in `AuthenticationOptions`?

**Comment by fauzipadlaw** [comment]
Thanks @stuartmorgan, I will try to set `sensitiveTransaction` false and will follow up with the user if the issue is solved. I will update in this thread by tomorrow.

**Comment by fauzipadlaw** [comment]
Hi @stuartmorgan, I tried setting `sensitiveTransaction` to false and publish it. User still facing the same issue. It does not solve issue.

**Comment by danagbemava-nc** [comment]
Labeling this for further investigation as this appears to be a device-specific issue. My device is only set up to verify using the fingerprint in apps so I couldn't test facial recognition with it. OP also reports that so far the report is only from an Oppo Find X2.

**Comment by stuartmorgan** [comment]
Unfortunately, per the docs for that method:
>> Also note that, as it is merely a hint, this option may be ignored by the system. For example, the system may choose to instead always require confirmation if the user has disabled passive authentication for their device in Settings.

If the system is choosing to ignore that option, there's not really anything the plugin can do; I would encourage you to provide feedback to the device developer if you don't want that UX.

> User said it only happens on my app, it does not happen on other app using biometric face recognition.

Other apps may be using older APIs for biometrics, or they may be implementing their own biometrics auth flow from scratch; neither is something we would do in `local_auth`. I'll leave a final decision to the Android triage, but my suggestion is that we close this as infeasible.
