### ISSUE TITLE
SharedPreferences are not persisted when changing organization on App Store

### ISSUE THREAD

**Issue by gilamarko** [flutter/flutter#133448]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

We have an app deployed on App Store where we store an ID which is Unique per installation via shared_preferences. 
For some reasons we changed the organization on the App Store and released a new version with some changes.
Since our data controlling if the app was a new installation were lost, the app acted like a new installation and then it is another story.

I'm using `shared_preferences: ^2.1.0`

### Expected results

shared_preferences should be kept stored even after organization changes.

### Actual results

shared_preferences were not kept stored even after organization changes.

### Code sample

<details><summary>Code sample</summary>

```dart
  Future<void> cleanAppStart() async {
    final prefs = await SharedPreferences.getInstance();
    if (prefs.getBool('first_run') ?? true) {
      await sl<FlutterSecureStorage>().deleteAll();
      await prefs.setBool('first_run', false);
    }
  }
```

</details>
As it can be seen based on a key-value pair stored on shared_preferences we do some actions, since the value was not present after the organization change we had some unwanted behaviour

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.22621.2134], locale en-US)
    • Flutter version 3.10.5 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (3 months ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\markogila\AppData\Local\Android\sdk
    • Platform android-33-ext4, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33424.131
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] IntelliJ IDEA Ultimate Edition (version 2022.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2022.2.4
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.79.0)
    • VS Code at C:\Users\markogila\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)          • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.2134]
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 116.0.5845.111
    • Edge (web)                 • edge          • web-javascript • Microsoft Edge 116.0.1938.62

[√] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by stuartmorgan** [comment]
> shared_preferences should be kept stored even after organization changes.

`sharde_preferences` on iOS does not manage the storage itself, it's just a wrapper around the OS-provided `NSUserDefaults` system. If changing your app's organization unexpectedly removed your ability to access existing values in `NSUserDefaults`, you would need to report that to Apple.
