### ISSUE TITLE
Fonts in CupertinoTheme do not inherit settings

### ISSUE THREAD

**Issue by KostyaLocal** [flutter/flutter#133423]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Setup new flutter project ios+android
2. Download any non-variable-height font, for example, Quicksand-Medium.ttf to folder "fonts"
[Quicksand-Medium.zip](https://github.com/flutter/flutter/files/12449405/Quicksand-Medium.zip) from Google Fonts
3. Register font in pubspec.yaml section "flutter":
```
  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Medium.ttf
```
4. Use CupertinoApp and add this font on CupertinoThemeData textStyle without specifying the size and weight:
```
CupertinoApp(
      theme: CupertinoThemeData(
        textTheme: CupertinoTextThemeData(
            textStyle: TextStyle(fontFamily: 'Quicksand')),
      ),
```
5. Try to adjust size (or weight) in widget build function:
`var style = CupertinoTheme.of(context).textTheme.textStyle.apply(fontSizeDelta: 1);`

### Expected results

Text-style with adjusted size (or weight)

### Actual results

A variable of type TextStyle does not inherit font size and weight. 
An exception is thrown when apply function is called:
> 'package:flutter/src/painting/text_style.dart': Failed assertion: line 968 pos 12: 'fontSize != null || (fontSizeFactor == 1.0 && fontSizeDelta == 0.0)': is not true.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const CupertinoApp(
      theme: CupertinoThemeData(
        textTheme: CupertinoTextThemeData(textStyle: TextStyle(fontFamily: 'Quicksand')),
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    var style = CupertinoTheme.of(context).textTheme.textStyle.apply(fontSizeDelta: 1);
    return SafeArea(child: Text("This is Text", style: style));
  }
}
```
</details>

[pubspec.zip](https://github.com/flutter/flutter/files/12449485/pubspec.zip)

### Screenshots or Video

None

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.13.1, on Microsoft Windows [Version 10.0.19044.3324], locale ru-RU)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.2)
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.79.0)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
```

</details>

**Comment by dam-ease** [comment]
Hi @KostyaLocal. Thanks for filing this issue. I am able to reproduce this but can you try with this to see if it suits your use-case?

<details><summary>Code Sample</summary>
<p>

```dart
import 'package:flutter/cupertino.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const CupertinoApp(
      theme: CupertinoThemeData(
        textTheme: CupertinoTextThemeData(
            textStyle:
                TextStyle(fontFamily: 'Quicksand', color: Color(0xFFFF0000))),
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    var style =
        CupertinoTheme.of(context).textTheme.textStyle.copyWith(fontSize: 10);
    return SafeArea(
        child: Text(
      "This is Text",
      style: style,
    ));
  }
}

``` 

</p>
</details>

**Comment by KostyaLocal** [comment]
@dam-ease Yes, this workaround works great, thanks!
