### ISSUE TITLE
Firesstore_Cloud setData crash on Android

### ISSUE THREAD

**Issue by Arno-Z** [flutter/flutter#13341]
Hi,

I am building an app to work with Google Cloud Firestore, which (as this SDK is very young) i have run into a number of issues which seem to come down to the SDK not being finished. That's what you get for running Alpha isn't it? ;) During this exercise i have found the field types are limited to string fields only, field nesting is also not allowed.

Limiting to this rules i have build something which runs fine on iOS but does not on Android. It crashes on a call in one of the provided flutter Dart files: document_reference.dart. On lines 20-30 it states:

 ```dart
Future<Null> setData(Map<String, dynamic> data) {
    return Firestore.channel.invokeMethod(
      'DocumentReference#setData',
      <String, dynamic>{'path': path, 'data': data},
    );
  }
```

Which leads to platformchannel.dart:
 ```dart
 Future<dynamic> invokeMethod(String method, [dynamic arguments]) async {
    assert(method != null);
    final dynamic result = await BinaryMessages.send(
      name,
      codec.encodeMethodCall(new MethodCall(method, arguments)),
    );
    if (result == null)
      throw new MissingPluginException('No implementation found for method $method on channel $name');
    return codec.decodeEnvelope(result);
  }
```

The invokeMethod will (i assume) pass it on to the Android native classes. Which comes back with _java.lang.NoSuchMethodError_ and causes the Android App to crash.

I am logged in with a Google Account and the security settings seem to be passed on to the Firestore plugin (see log). Running in iOS it runs ok and is satisfies the Firestore security rules.

My Questions:

- Am i in error, or is this a bug in the alpha sdk?
- Is there a feature missing/incorrectly mapped?
- Why does it crash, instead of boiling up an error?
- Am i correct Firestore functionality is currently limited to String fields?

Thanks for all your great effort!

Arno

**## My DART Code (cutout)**
 ```dart
//Create the basic Document
      Map <String, String> _document = {
        'uid': _currentUser.uid,
        'Value':'012345678',
      };

      Firestore.instance
          .collection('/Documents/$Revision/' + _currentUser.uid)
          .document()
          .setData(_document);
    } catch (error) {
      print ('Firesstore insert Error:' + error.toString());
    }
```

**pubspec.yaml**
```yaml
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: 0.1.0
  cupertino_icons: ^0.1.0
  firebase_auth: 0.3.1
  google_sign_in: 1.0.1
```

**## Logs**
```console
I/flutter (19194): Firestore __addDocument for 4EUIfIeWeyVOH0Rkvz1k3mmTSCn2
I/flutter (19194): Firestore insert document for 4EUIfIeWeyVOH0Rkvz1k3mmTSCn2
I/flutter (19194): [INFO:platform_view_android_jni.cc(29)] java.lang.NoSuchMethodError: No static method zzb(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzbp; or its super classes (declaration of 'com.google.android.gms.common.internal.zzbp' appears in /data/app/tld.domain.app-1/base.apk)
I/flutter (19194): 	at com.google.firebase.firestore.FirebaseFirestore.zze(Unknown Source)
I/flutter (19194): 	at com.google.firebase.firestore.FirebaseFirestore.getInstance(Unknown Source)
I/flutter (19194): 	at io.flutter.plugins.firebase.cloud_firestore.CloudFirestorePlugin.getDocumentReference(CloudFirestorePlugin.java:56)
I/flutter (19194): 	at io.flutter.plugins.firebase.cloud_firestore.CloudFirestorePlugin.onMethodCall(CloudFirestorePlugin.java:203)
I/flutter (19194): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
I/flutter (19194): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:122)
I/flutter (19194): 	at android.os.MessageQueue.nativePollOnce(Native Method)
I/flutter (19194): 	at android.os.MessageQueue.next(MessageQueue.java:323)
I/flutter (19194): 	at android.os.Looper.loop(Looper.java:136)
I/flutter (19194): 	at android.app.ActivityThread.main(ActivityThread.java:6077)
I/flutter (19194): 	at java.lang.reflect.Method.invoke(Native Method)
I/flutter (19194): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
I/flutter (19194): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
I/flutter (19194): 
F/flutter (19194): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(51)] Check failed: CheckException(env). 
F/libc    (19194): Fatal signal 6 (SIGABRT), code -6 in tid 19194
Run your application with `flutter run` and attach all the log output.
```

**## flutter analyze**
Run `flutter analyze` and attach any output of that command also.
macbook-arno:waarneem_planner arno$ flutter analyze
Analyzing /Users/arno/AndroidStudioProjects/xxxxxxxxxx...
No issues found!
Ran in 5.8s

**## Flutter Doctor**

[✓] Flutter (on Mac OS X 10.13.1 17B1003, locale en-NL, channel alpha)
    • Flutter at /Users/arno/flutter
    • Framework revision d957c8f040 (4 days ago), 2017-11-30 13:29:59 -0800
    • Engine revision 77d8acb9be
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-dev.9.0

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at /Users/arno/Library/Android/sdk
    • Android NDK at /Users/arno/Library/Android/sdk/ndk-bundle
    • Unable to locate compiler in Android NDK.
    • Platform android-27, build-tools 27.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.1, Build version 9B55
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0.beta.2

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 7.0 (API 24) (emulator)
    • iPhone X                  • 9DE45820-B145-491C-8A25-71599CBD8386 • ios         • iOS 11.1 (simulator)

**Comment by eseidelGoogle** [comment]
@collinjackson @kroikie

**Comment by Skylled** [comment]
This is an issue with the firebase_auth package on pub using a different version of GMS. Until it has been updated there, you can clone the repo and use a local version, as described [here](https://github.com/flutter/flutter/issues/13324#issuecomment-349070493).

**Comment by mit-mit** [comment]
This is being tracked and resolved as part of https://github.com/flutter/flutter/issues/12945

**Comment by varundroid** [comment]
I am still having this issue. Plugin versions that I am using: 

`cloud_firestore: "^0.7.3"`
`firebase_auth: "^0.5.11"`

Exception:
`[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
MissingPluginException(No implementation found for method DocumentReference#setData on channel plugins.flutter.io/cloud_firestore)

**Comment by kroikie** [comment]
@Arno-Z

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/930. Any further collaboration will be done there.
