### ISSUE TITLE
Installing Xcode 15 on CI bot hangs and times out

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#133461]
We had a couple of bots upgraded to macOS 13 so we could test Xcode 15 on them - [one devicelab bot](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-45) and [one chromium bot](https://chromium-swarm.appspot.com/bot?id=mac-346-g140).

When installing Xcode on the chromium bot, it gives this error and then hangs and eventually times out:
```
[I 2023-08-24 13:49:59] About to install Xcode 15a5219j in /Volumes/Work/s/w/ir/cache/osx_sdk/xcode_15a5219j/XCode.app for ios
[W 2023-08-24 13:49:59] Checking if the host is on MacOS13 or later
[W 2023-08-24 13:49:59] Checking if Xcode should be re-installed
[W 2023-08-24 13:49:59] CFBundleVersion 22004 matches between local and cipd, Xcode should not be re-installed
[W 2023-08-24 13:49:59] Removing the hidden cipd files if exists to be compliant with MacOS13+ codesign check...
[E 2023-08-24 13:49:59] original error: open /Library/Preferences/com.apple.dt.Xcode.plist: no such file or directory

goroutine 1:
#0 mac_toolchain/plist.go:111 - main.getXcodeAcceptedLicense()
  reason: failed to open /Library/Preferences/com.apple.dt.Xcode.plist

#1 mac_toolchain/install.go:139 - main.needToAcceptLicense()
#2 mac_toolchain/install.go:597 - main.installXcode()
#3 mac_toolchain/main.go:202 - main.(*installRun).Run()
#4 github.com/maruel/subcommands@v1.1.1/subcommands.go:395 - subcommands.Run()
#5 mac_toolchain/main.go:664 - main.main()
#6 runtime/proc.go:267 - runtime.main()
#7 runtime/asm_arm64.s:1197 - runtime.goexit()
```
https://chromium-swarm.appspot.com/task?id=64416e59b9dee710

I don't think that's the real issue, though. I looked at the mac_toolchain code and getting that error shouldn't be fatal, it should continue on to try and accept the license. However, mac_toolchain doesn't provide enough logs to figure out where it's getting stuck.
https://chromium.googlesource.com/infra/infra/+/refs/heads/main/go/src/infra/cmd/mac_toolchain/install.go#142

Just a guess, but perhaps it's getting stuck [waiting for the license to be accepted](https://chromium.googlesource.com/infra/infra/+/refs/heads/main/go/src/infra/cmd/mac_toolchain/install.go#190) because it's using `sudo` and waiting for a password to be inputted?

Also, the flutter devicelab bot works fine and had no issues installing Xcode 15.

**Comment by keyonghan** [comment]
We may need to reach out to toolchain or the chromium lab team to see what's going on. Another thing to check is the `mac_toolchain` version.

**Comment by vashworth** [comment]
Looks like the issue is due to our Xcode package in CIPD. Apparently in macOS 13.5.1, you can't alter the Xcode package, otherwise it becomes "damaged". I cleared the cache and tried with a non-altered Xcode and was able to get it to work. Closing.
