### ISSUE TITLE
[Android] TextField loses focus when using physical keyboard

### ISSUE THREAD

**Issue by sstasi95** [flutter/flutter#133450]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Connect a physical keyboard
2. Switch on 'Show virtual keyboard while physical keyboard is active' setting
3. Tap the text field to focus it
4. Type a character

### Expected results

Virtual keyboard should close, but text field should keep the focus and it should be possible to type from the physical keyboard. This is Google Play and Settings app behaviour.

### Actual results

Virtual keyboard closes, but text field loses focus and there is no way to type text into it.

Tested on a Samsung Galaxy A13 (SM-A137F) and on a Samsung Galaxy Tab S6 Lite (SM-P610), both with Android 13.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              TextField(),
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.13.1, on macOS 13.5 22G74 darwin-arm64, locale en-IT)
    • Flutter version 3.13.1 on channel stable at /Users/Simone/dev/flutter
    ! Warning: `flutter` on your path resolves to /Users/simone/dev/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/Simone/dev/flutter. Consider adding /Users/Simone/dev/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/simone/dev/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/Simone/dev/flutter. Consider adding /Users/Simone/dev/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e1e47221e8 (5 days ago), 2023-08-22 21:43:18 -0700
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/simone/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (2 available)
    • SM A137F (mobile) • R58TB1MBLTJ • android-arm    • Android 13 (API 33)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by huycozy** [comment]
Hi @sstasi95 
I'm checking this issue with my Bluetooth keyboard connecting to `Realme 6, Android 11` and see it works as expected. The virtual keyboard stays and can enter TextField with either virtual keyboard or physical keyboard. The same result is on another app (Play Store app's search field) and I think the virtual keyboard should be opened as the desired result.

<details>
<summary>Demo</summary>

https://github.com/flutter/flutter/assets/104349824/d364f4ec-f9de-4f18-9377-74aab5cf352e
</details>

I wonder if this issue is Samsung specific issue or not. Can you check it on another device if any? It would be appreciated if you could provide a recorded video for the issue. Thank you!

**Comment by sstasi95** [comment]
Hi @huycozy, thanks for the response.

I think I found the issue, it's the Samsung default keyboard. I tested it on other devices of different brands and it works everywhere, but all these devices have GBoard keyboard installed. So I tried to install GBoard on the Samsungs and the issue disappears.

I think we can close this, thanks for the help!
