### ISSUE TITLE
When there are multiple Expanded in the row, if one has enough space, the other can occupy it. Like the flex layout of the web.

### ISSUE THREAD

**Issue by zhou26192619** [flutter/flutter#133438]
When there are multiple Expanded in the row, if one has enough space, the other can occupy it. Like the flex layout of the web.

In the picture, the content of text is uncertain, and a text can be displayed completely with just a little more space. The flex layout on the web is completely fine and easy to implement.

## Details

**Target Platform: android**
**Target OS version/browser: 33**
**Devices: Pixel_3a_API_34_extension_level_7_arm64-v8a**

## Logs

```dart
Row(
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.circular(1000),
                      child: Image.network(
                        'https://cdn.pixabay.com/photo/2023/08/05/23/40/bird-8171927_640.jpg',
                        fit: BoxFit.fill,
                        height: 30,
                        width: 30,
                      ),
                    ),
                    Expanded(
                      child: Container(
                        margin: const EdgeInsets.fromLTRB(10, 0, 10, 0),
                        child: Text(
                          'aaaaaaa',
                          overflow: TextOverflow.ellipsis,
                          style: const TextStyle(fontSize: 16, color: Colors.black),
                        ),
                      ),
                    ),
                    Image.network(
                      'https://cdn.pixabay.com/photo/2023/08/05/23/40/bird-8171927_640.jpg',
                      fit: BoxFit.fill,
                      height: 20,
                      width: 20,
                    ),
                    Container(
                      child: Text('回复'),
                      margin: EdgeInsets.fromLTRB(10, 0, 10, 0),
                    ),
                    Expanded(
                      child: Container(
                        margin: const EdgeInsets.fromLTRB(0, 0, 10, 0),
                        child: Text(
                          'c',
                          overflow: TextOverflow.ellipsis,
                        ),
                      ),
                    ),
                    Text('2022-02-22')
                  ],
                ),
```

![20230828154341](https://github.com/flutter/flutter/assets/4471261/6ab031d6-b986-4255-a387-2e5aa7fe5072)

**Comment by huycozy** [comment]
Hi @zhou26192619 
This issue isn't a performance issue and also quite not clear about the expected result. Please update the issue or open a new issue (and close this respectively) corresponding to [Bug issue template](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml) so that we may verify the issue properly. Thank you!

**Comment by zhou26192619** [comment]
> Hi @zhou26192619 This issue isn't a performance issue and also quite not clear about the expected result. Please update the issue or open a new issue (and close this respectively) corresponding to [Bug issue template](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml) so that we may verify the issue properly. Thank you!

Thank yout, I put it to Bug issue.
