### ISSUE TITLE
Various framework tests are failing in CI

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#133486]
[Linux framework_tests_libraries](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20framework_tests_libraries/12989/overview), [Mac framework_tests_widgets](https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20framework_tests_widgets/12741/overview), [Linux framework_tests_widgets](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20framework_tests_widgets/12863/overview) are failing flakily in CI

It fails on different tests in each.
This appears to have started happening at same time as https://github.com/flutter/flutter/issues/133483

**Comment by godofredoc** [comment]
The error in widgets seems to be related to golden differences:

```
Debug information for Gold --------------------------------
stdout: Given image with hash 62f1bf7417dacf2636ced736d822d26c for test widgets.invert_colors_test.0
Untriaged or negative image:
https://flutter-gold.skia.org/detail?grouping=name%3Dwidgets.invert_colors_test.0%26source_type%3Dflutter&digest=62f1bf7417dacf2636ced736d822d26c


stderr: Test: widgets.invert_colors_test.0 FAIL


result-state.json: No result file found.

When the exception was thrown, this was the stack:
#0      SkiaGoldClient.imgtestAdd (package:flutter_goldens_client/skia_client.dart:243:7)
<asynchronous suspension>
#1      MatchesGoldenFile.matchAsync.<anonymous closure> (package:flutter_test/src/_matchers_io.dart:118:32)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from dart:async)

The exception was caught asynchronously.
```

**Comment by godofredoc** [comment]
The golden has been accepted and I now see the tests passing. Should we close this bug?

**Comment by vashworth** [comment]
> The golden has been accepted and I now see the tests passing. Should we close this bug?

I see that too. Closing.
