### ISSUE TITLE
Issues automating end to end tests for Flutter Web apps

### ISSUE THREAD

**Issue by pandoras-toolbox** [flutter/flutter#133451]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I tried to use the official Flutter "integration_test" package to automate end to end tests for Flutter **_web_** apps.

Unfortunately it turned out to be very immature and that it has a lot of limitations when compared to Selenium. 

But Selenium cannot be used to automate Flutter web apps because the widgets are kinda painted and thus they cannot be located with CSS selectors, and it is not possible to interact with them in the standard HTML way.

The problems of that official test package are the reason why [Patrol](https://www.droidcon.com/2023/08/07/reimagining-flutter-ui-tests-with-patrol/) was developed. But that 3rd party tool works only for Flutter mobile apps. It is not made to automate tests for Flutter web apps.

My idea is to create a bridge to make it possible to use Selenium for Flutter web apps. I seen that the tests are included the browser's sources and that they are in JavaScript, also the Flutter API. But I do not know what statment(s) I need to execute in order to find widgets using the Flutter finder API and what statement(s) I need to execute to interact with a found widget.

I am a tester and automater, not a JavaScript pro or a Flutter expert.

My questions are this:

1. Am I totally wrong that the "integration_ test" package is horrible for professional use?
2. What do you think about my idea to build a bridge from Selenium to Flutter web apps, and can you help me to achieve it?
3. What do you suggest how I should proceed to automate tests for Flutter web apps professionally?

### Actual results

Here are some of the problems with Flutter's "integration_test" package:

- slow and unnecessary builds
- no isolation between tests
- no sharding of tests
- no test durations
- not compatible with device farms and native tooling
- test code is too verbose
- no black box approach possible, which some people prefer

There are more problems, for example the tests cannot be started from IDE and thus not easily debugged, after taking a screenshot the page doesn't refresh and it is impossible to automate a test scenario which stretches across both Flutter web apps and non-Flutter web apps.

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```
[✓] Flutter (Channel stable, 3.10.6, on Fedora Linux 38 (Workstation Edition) 6.4.11-200.fc38.x86_64, locale en_US.UTF-8)
    • Flutter version 3.10.6 on channel stable at /home/mario/flutter_linux_3.10.6-stable/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (7 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/mario/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /home/mario/Android/Sdk
    • Java binary at: /home/mario/.sdkman/candidates/java/current/bin/java
    • Java version OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
    ✗ CMake is required for Linux development.
      It is likely available from your distribution (e.g.: apt install cmake), or can be downloaded from https://cmake.org/download/
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from
      https://github.com/ninja-build/ninja/releases
    • pkg-config version 1.8.0
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)

[!] Android Studio (version 2023.1)
    • Android Studio at /home/mario/android-studio-2023.1.1.11-linux/android-studio
    • Flutter plugin version 74.0.4
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at /home/mario/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9161.38
    • Flutter plugin version 75.1.3
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
    • IntelliJ at /home/mario/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/232.8660.185
    • Flutter plugin version 75.1.4
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.81.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.70.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Fedora Linux 38 (Workstation Edition) 6.4.11-200.fc38.x86_64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.110

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```
</details>

**Comment by huycozy** [comment]
Hi @pandoras-toolbox 
Thanks for filling the issue but the issue seems to raise issues more generally than bug reporting or suggesting specific new changes/features for integration test on Web.

The issue should be more detailed with each case to be actionable. For instance, some of the following issues might be similar to what you are experiencing:

- https://github.com/flutter/flutter/issues/86295
- https://github.com/flutter/flutter/issues/117955

You can take a look at [integration_test issue filter](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3A%22f%3A+integration_test%22+label%3Aplatform-web) and see if there is any similar issue you are also experiencing on. If your issue has not existed yet, please file a new one for that. When opening a new issue, please try to clarify all information in the issue template so that we may verify it properly. 

Please also see flutter's [community](https://flutter.dev/community) for resources and ask questions like this as well. 

With the information given above, I will close this issue from here. Thank you!

**Comment by pandoras-toolbox** [comment]
Thank you, but I am afraid that leads nowhere. My issue is to question the maturity and quality of the integration_test package as a whole, which is the biggest problem no one talks about here.

I tried to ask such a question in the Slack Flutter community, there was no answer at all.

And when I reported a particular issue in detail here someone from Flutter developers could reproduce it and then nothing happened, like with so many issues here, for years even.

Sorry, but I am very disappointed about Flutter from a test automation perspective.

**Comment by bartekpacia** [comment]
> My issue is to question the maturity and quality of the integration_test package as a whole, which is the biggest problem no one talks about here.

I agree with you very much. I agree that `integration_test` can't be considered production ready.

> Sorry, but I am very disappointed about Flutter from a test automation perspective.

We are too, that's how Patrol was [born](https://patrol.leancode.co/) actually.

I can say that Web is on our radar, but it won't happen anytime soon. Meanwhile we'd be happy to hear what use cases you have in mind in https://github.com/leancodepl/patrol/discussions/1489.
