### ISSUE TITLE
[image_picker] Need help with "pickMultiImage()"

### ISSUE THREAD

**Issue by Caio-Caetano** [flutter/flutter#133459]
Hello,

I searched for, but I didn't find.
There's a way to set limit for this Function?

Like: `final List<XFile> pickedFileList = await _picker.pickMultiImage(max: 5);`

If not, how can I do this?

Version: ` image_picker: ^1.0.2`

**Comment by stuartmorgan** [comment]
Duplicate of https://github.com/flutter/flutter/issues/85772
