### ISSUE TITLE
Migrate `#pragma once` to `#ifndef *_H_` guards and catch backslides

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#133415]
We use `#pragma once` [~350 times](https://github.com/search?q=repo%3Aflutter%2Fengine+%22%23pragma+once%22&type=code).

Mostly in [`impeller/`](https://github.com/search?q=repo%3Aflutter%2Fengine+%22%23pragma+once%22+path%3A%2F%5Eimpeller%5C%2F%2F&type=code), 316 files, but also in [`lib/`](https://github.com/search?q=repo%3Aflutter%2Fengine+%22%23pragma+once%22+path%3A%2Flib%5C%2F%2F&type=code), 9 files, [`web_ui/`](https://github.com/search?q=repo%3Aflutter%2Fengine+%22%23pragma+once%22+path%3A%2Fweb_ui%5C%2F%2F&type=code), 4 files, and [`shell/`](https://github.com/search?q=repo%3Aflutter%2Fengine+%22%23pragma+once%22+path%3A%2Fshell%5C%2F%2F&type=code), 10 files (including Fuchsia, Android) and more.

Unless there is a good reason we're only _sometimes_ using it, I'd propose to replace the remainder of the guards ([604 files](https://github.com/search?q=repo%3Aflutter%2Fengine+%2F%23ifndef+.*_H%2F&type=code)), and ban it's recurrence.

_Or_, as @stuartmorgan brings up below, the opposite. There is a check to help enforce that:

[`llvm-header-guard`](https://clang.llvm.org/extra/clang-tidy/checks/llvm/header-guard.html)

**Comment by stuartmorgan** [comment]
`pragma once` is non-standard, and isn't completely reliable. The Google C++ style guide, which we say we follow, [requires the use of explicit guards](https://google.github.io/styleguide/cppguide.html#The__define_Guard), so we should actually do the opposite: replace all use of `pragma` so that we are following the style guide.

**Comment by matanlurey** [comment]
Thanks Stuart!

Renamed the title to discuss.

**Comment by stuartmorgan** [comment]
What would be the argument for Flutter not following the style guide?

**Comment by matanlurey** [comment]
No idea, this bug is to discover if there is one.

**Comment by stuartmorgan** [comment]
> It's very easy to get the header guards wrong and not notice it and get weird build failures (because you copy and pasted from another file, because you and your reviewers missed that the `#ifndef` has a typo that causes this, etc).

Presumably the `clang-tidy` check referenced above eliminates that?

> `#pragma once` is supported well by all the toolchains we actually use or support for building the engine.

I wouldn't think that "well supported" would eliminate the subtle failure cases inherent to `pragma once` itself though. And unlike the failure modes you described, those can't be trivially detected by tooling.

**Comment by matanlurey** [comment]
We chatted about this offline a bit in the elevator with @dnfield.

Even though we prefer the `#pragma once` style, it doesn't seem worth the effort to change the existing files and then write custom tooling to enforce it, when existing tools (i.e. `clang_tidy`) support the `#ifndef` method with [`llvm-header-guard`](https://clang.llvm.org/extra/clang-tidy/checks/llvm/header-guard.html).

I'm going to attempt change existing code and enforce the lint.

**Comment by stuartmorgan** [comment]
> Even though we prefer the `#pragma once` style, it doesn't seem worth the effort to change

Putting on my emeritus C++ readability hat: leaving aside tooling, an argument for deviating from the style guide should always be "our project is fundamentally different from other projects in an inherent way that makes the rationale for the style guide rule inapplicable (or at least very differently)", and not "those of us who happen to be on this team at the moment prefer a different style", because otherwise the entire point of the style guide is undermined.

**Comment by dnfield** [comment]
> > Even though we prefer the `#pragma once` style, it doesn't seem worth the effort to change
> 
> Putting on my emeritus C++ readability hat: leaving aside tooling, an argument for deviating from the style guide should always be "our project is fundamentally different from other projects in an inherent way that makes the rationale for the style guide rule inapplicable (or at least very differently)", and not "those of us who happen to be on this team at the moment prefer a different style", because otherwise the entire point of the style guide is undermined.

The fundamental difference we have is that we're pretty limited in terms of toolchains and platforms we support: it's basically Clang that we ship with the project and a _little bit of MSVC/VisualStudio_ thrown in on Windows.

**Comment by stuartmorgan** [comment]
I'm skeptical that using clang makes us immune to the same-file-but-different-paths pitfalls that can cause very hard-to-understand problems with `pragma once`.

**Comment by dnfield** [comment]
Alright, and I suspect we're susceptible there in terms of how we do includes alternatively using styles like `flutter/impeller/foo/bar.h` and `impeller/foo/bar.h` or `third_party/skia/include/core/SkFoo.h`/`include/core/SkFoo.h`, and probably with the way some of the vulkan dependencies are handled...

**Comment by matanlurey** [comment]
Going to start sending out changes to move us to the header-guard style consistently, then we can enable the lint to avoid backsliding.

**Comment by matanlurey** [comment]
Caveat: It looks like `llvm-header-guard` is specifically written to work well in LLVM's own codebase, and has no configuration options. What that means in practice is that it expects all header files to live under an `include/` directory (ours does not) and butchers our existing guards.

Here is an example of `assets/asset_manager.h` with `--fix` applied.

```diff
-#ifndef FLUTTER_ASSETS_ASSET_MANAGER_H_
+#ifndef USERS_MATANL_DEVELOPER_ENGINE_SRC_OUT_HOST_DEBUG_UNOPT_ARM64_______FLUTTER_ASSETS_ASSET_MANAGER_HRC_OUT_HOUSERS_MATANL_DEVELOPER_ENGINE_SRC_OUT_HOST_DEBUG_UNOPT_ARM64_______FLUTTER_ASSETS_ASSET_MANAGER_HTER_ASSETS_ASSET_MANAGER_H
```

So uh, that won't work.

We could write some custom tooling to check this, for example, similar to [`tools/api_check`](https://github.com/flutter/engine/tree/main/tools/api_check). I'll probably go down that route instead given this is very simple and does not change often (ever).

**Comment by matanlurey** [comment]
Not enforced yet. Next PR.
