### ISSUE TITLE
[Engine] Consider enabling clang-tidy: `misc-include-cleaner`

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#133417]
`clangd` has a "preview mode" for a [feature called "Include Cleaner"](https://clangd.llvm.org/design/include-cleaner):

> Manually managing includes in a C++ translation unit, especially in the face of transitive inclusions, requires a lot of effort. Include Cleaner aims to provide diagnostics to keep includes in an [IWYU](https://include-what-you-use.org/)-clean state.
>
> ```cc
> // main.cpp
> 
> #include "foo.h"
> #include "bar.h" // <- Will be marked as unused and suggested to be removed.
> 
> int main() {
>   Foo f;
> }
> ```

It can be enabled with a `.clangd` file at the root:

```
# .clangd
Diagnostics:
  UnusedIncludes: Strict
  MissingIncludes: Strict
```

To run these on CI, we can include the Clang Tidy check `misc-include-cleaner`:

https://clang.llvm.org/extra/clang-tidy/checks/misc/include-cleaner.html

Here are some files I spot-checked in the engine repo:

![Screenshot 2023-08-27 at 2 58 18 PM](https://github.com/flutter/flutter/assets/168174/451fe8ea-8da5-4225-b149-d86c9d9964a4)

![Screenshot 2023-08-27 at 2 56 18 PM](https://github.com/flutter/flutter/assets/168174/3a453a3d-81e6-4c8d-bc71-f19d871f4c93)

![Screenshot 2023-08-27 at 2 57 00 PM](https://github.com/flutter/flutter/assets/168174/3a71f07a-af0c-4c6e-b807-9a031cacdab6)

![Screenshot 2023-08-27 at 2 57 45 PM](https://github.com/flutter/flutter/assets/168174/53a90ef0-955b-4d39-875e-adfb7dc08915)

And here is an example of running `clang-tidy --fix` on `dl_unittests.cc`:

```diff
impeller/display_list/dl_unittests.cc
@@ -3,10 +3,18 @@
 // found in the LICENSE file.
 
 #include <array>
+#include <cassert>
 #include <cmath>
+#include <cstddef>
+#include <cstdint>
 #include <memory>
+#include <optional>
+#include <tuple>
 #include <vector>
 
+#include "display_list/dl_canvas.h"
+#include "display_list/dl_sampling_options.h"
+#include "display_list/dl_vertices.h"
 #include "flutter/display_list/display_list_builder.h"
 #include "flutter/display_list/dl_blend_mode.h"
 #include "flutter/display_list/dl_color.h"
@@ -16,24 +24,33 @@
 #include "flutter/display_list/effects/dl_color_source.h"
 #include "flutter/display_list/effects/dl_image_filter.h"
 #include "flutter/display_list/effects/dl_mask_filter.h"
-#include "flutter/testing/testing.h"
+#include "gtest/gtest-param-test.h"
 #include "gtest/gtest.h"
 #include "impeller/display_list/dl_dispatcher.h"
 #include "impeller/display_list/dl_image_impeller.h"
 #include "impeller/display_list/dl_playground.h"
 #include "impeller/entity/contents/solid_color_contents.h"
 #include "impeller/entity/contents/solid_rrect_blur_contents.h"
+#include "impeller/entity/entity.h"
+#include "impeller/geometry/color.h"
 #include "impeller/geometry/constants.h"
 #include "impeller/geometry/point.h"
+#include "impeller/geometry/rect.h"
 #include "impeller/geometry/scalar.h"
+#include "impeller/playground/playground_test.h"
 #include "impeller/playground/widgets.h"
-#include "impeller/scene/node.h"
+#include "include/core/SkPath.h"
+#include "include/core/SkPath.h"
+#include "include/core/SkPathTypes.h"
+#include "include/core/SkPoint.h"
+#include "include/core/SkRect.h"
+#include "include/core/SkScalar.h"
+#include "include/core/SkTextBlob.h"
 #include "third_party/imgui/imgui.h"
-#include "third_party/skia/include/core/SkBlurTypes.h"
-#include "third_party/skia/include/core/SkClipOp.h"
 #include "third_party/skia/include/core/SkPathBuilder.h"
 #include "third_party/skia/include/core/SkRRect.h"
```

**Comment by matanlurey** [comment]
Oh, this _might_ address https://github.com/flutter/flutter/issues/126889 @gaaclarke?

**Comment by gaaclarke** [comment]
Ooo cool, looks promising.  "IWYU" sounds right.  The sample output sounds right too.  Nice find.

**Comment by matanlurey** [comment]
Self-assigning to try landing this (I won't do it in an atomic CL).

**Comment by dnfield** [comment]
I took a look at this a bit and am finding that there are two themes right now making it hard:

- Use of `FML_USED_ON_EMBEDDER` confuses the plugin, because it will try to put headers above that define and then they don't work because the define guard is missing. If we can avoid this pattern we probably should, see https://google.github.io/styleguide/cppguide.html#Self_contained_Headers which says "Users and refactoring tools should not have to adhere to special conditions to include the header."
- Use of forward declares in Impeller in particular leads to confusion in the plugin. We could probably support this with lots of pragmas around what to keep/forward declare/not forward declare, but we should also just avoid forward declaring as much as we are. See https://google.github.io/styleguide/cppguide.html#Forward_Declarations which says "Avoid forward declarations where possible."

**Comment by matanlurey** [comment]
> * Use of `FML_USED_ON_EMBEDDER` confuses the plugin, because it will try to put headers above that define and then they don't work because the define guard is missing. If we can avoid this pattern we probably should, see https://google.github.io/styleguide/cppguide.html#Self_contained_Headers which says "Users and refactoring tools should not have to adhere to special conditions to include the header."

@dnfield I wonder if this is "fixed" with the new header guard enforcement?

**Comment by matanlurey** [comment]
@dnfield I am assigning this to you if you were still hacking on it in the background, otherwise feel free to unassign.
