### ISSUE TITLE
showModalBottomSheet creates ModalBottomSheetRoute that is never disposed.

### ISSUE THREAD

**Issue by polina-c** [flutter/flutter#133594]
PR: https://github.com/flutter/flutter/pull/133595

Steps to repro:
1. Remove notDisposedAllowList added by the PR
2. Run the updated test library with 'flutter run <path to the library>'
3. Observe the test failure

https://github.com/flutter/flutter/blob/4022864c659ff2f0691aff4efce7be43a3ce757c/packages/flutter/lib/src/material/bottom_sheet.dart#L1221

**Comment by polina-c** [comment]
For some reason it does not happen in the test, marked by this PR: https://github.com/flutter/flutter/pull/133595
Is it issue of test or something is missing in the flutter framework code?

**Comment by chunhtai** [comment]
interesting, I think we will need to investigate further.

**Comment by chunhtai** [comment]
@hangyujin can you take a look at this bug?
