### ISSUE TITLE
[Web][html] Encountering issues with jittery transitions and experiencing unusual behavior.

### ISSUE THREAD

**Issue by FarhanAli-98** [flutter/flutter#133543]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

When running our app with the `-web-renderer html` render, we observed jittery effects during execution.

### Expected results

While utilizing the `-web-renderer html` render, we encountered certain jittery transition problems. These issues were critical as they disrupted UI adjustments and led to some inexplicable behaviors. 

### Actual results

While using the `--web-renderer canvaskit`, the bundle size increased by 1.50MB, and the time increased by 1.02 seconds. that's why we need to reduce time and size in initial loading.

### Code sample

<details><summary>Code sample</summary>

```dart
<body>
  <script>
    let useHtml = true;

    window.addEventListener('load', function(ev) {
    _flutter.loader.loadEntrypoint({
      serviceWorker: {
        serviceWorkerVersion: serviceWorkerVersion,
      },
      onEntrypointLoaded: function(engineInitializer) {
        let config = {
          renderer: useHtml ? "html" : "canvaskit",
        };
        engineInitializer.initializeEngine(config).then(function(appRunner) {
          appRunner.runApp();
        });
      }
    });
  });
  </script>
</body>

```

</details>

### Screenshots or Video

https://github.com/flutter/flutter/assets/50108735/f53ed788-d474-4ce0-87c3-44cf72cbcd7e

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.10.5, on macOS 13.4 22F66 darwin-x64, locale en-GB)
    • Flutter version 3.10.5 on channel stable at /Users/pro/Documents/previous_flutter/flutter3.10.5
    ! Warning: `dart` on your path resolves to /usr/local/Cellar/dart/3.0.4/libexec/bin/dart, which is not inside your current Flutter SDK checkout at
      /Users/pro/Documents/previous_flutter/flutter3.10.5. Consider adding /Users/pro/Documents/previous_flutter/flutter3.10.5/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (3 months ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/pro/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] VS Code (version 1.79.0)
    • VS Code at /Users/pro/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.4 22F66 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.110

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by FarhanAli-98** [comment]
Requesting your attention to address this critical Issue.
@darshankawar @yjbanov @huycozy @tneotia @erickok

**Comment by danagbemava-nc** [comment]
Hi @FarhanAli-98, please provide a complete minimal reproducible code sample (preferably without any third-party packages) so that we can investigate this issue. 

I noticed you're using an older version of the flutter. Can you upgrade to the latest version of flutter stable to see if you still experience this issue?

Lastly, please do not ping random people on issues, we have a triage process and all issues will be triaged per the process. 

Thank you

**Comment by FarhanAli-98** [comment]
Hello @danagbemava-nc, I have tried using the latest version (3.13.1), but the issue remains the same. Could you please @adnan-nazir to create an example project for me?

**Comment by FarhanAli-98** [comment]
@danagbemava-nc 
Hello, I have created an example for you. You can follow the steps demonstrated in the video to reproduce this issue. The example includes only three images, but if the UI is more complex, the issue will persist consistently.
GitHub project link: [Flutter jittery](https://github.com/FarhanAli-98/flutter_jittery.git)

https://github.com/flutter/flutter/assets/50108735/054a6af0-01c4-4e33-ad18-1f40b02f95b5

**Comment by danagbemava-nc** [comment]
Hi @FarhanAli-98, thanks for the update. 
A few questions

- Does this only happen when the pages you're transitioning between have images?
- Does this happen in release/profile mode as well? or only debug mode?

**Comment by FarhanAli-98** [comment]
Hi @danagbemava-nc,

I have tried debugging, release, and profile modes, but the issue still persists. It mostly happens when transitioning between pages that contain images and dynamic content.

**Comment by adnan-nazir** [comment]
> * Does this only happen when the pages you're transitioning between have images?

Actually its
![Screenshot_20230831_120625](https://github.com/flutter/flutter/assets/107183643/b96af3c7-764b-4ad9-bc12-23f8b3f0b062) the only screen inside the App. For other case let us check its occurring there or not.

> * Does this happen in release/profile mode as well? or only debug mode?

Yes its produce able in all(debug, profile release) modes.

**Comment by adnan-nazir** [comment]
> * Does this only happen when the pages you're transitioning between have images?

Actually its
![Screenshot_20230831_120625](https://github.com/flutter/flutter/assets/107183643/b96af3c7-764b-4ad9-bc12-23f8b3f0b062) the only screen inside the App. For other case let us check its occurring there or not.

> * Does this happen in release/profile mode as well? or only debug mode?

Yes its produce able in all(debug, profile release) modes.

**Comment by adnan-nazir** [comment]
@danagbemava-nc I just tried without images I am still facing the same issue. It's not image-specific.

**Comment by danagbemava-nc** [comment]
Hi, I can't seem to reproduce with the image sample code, am I doing this correctly? See the recording below

@adnan-nazir, can you provide the code sample without the images? 

https://github.com/flutter/flutter/assets/88313112/c41a5118-9aee-4169-8313-7567f2426646

**Comment by FarhanAli-98** [comment]
Hi @danagbemava-nc , thanks for the update.
A few questions

- Have you run sample project with html render `flutter run --web-renderer html`?
- Occasionally, when attempting to reproduce the issue, it takes roughly one minute. Consequently, a few machines reproduce this issue in a relatively minor manner. 
- In the provided video, you can observe these jittery effects occurring on pages without images.

https://github.com/flutter/flutter/assets/50108735/8d7fc6c5-d91b-4c0a-b7cd-adb3e7237130


-

**Comment by danagbemava-nc** [comment]
Hi @FarhanAli-98, I tested with the html renderer. 

What device does this issue reproduce easily on?

**Comment by FarhanAli-98** [comment]
Hello @danagbemava-nc,
I am using a MacBook Pro from 2018. Let me create a new example for you that will enable you to reproduce the issue quickly.

**Comment by FarhanAli-98** [comment]
@danagbemava-nc 
I've also hosted this identical example on Firebase, and you can observe that the issues still persist. Here's the link to this website example: https://jittery-d16e2.web.app/#/

**Comment by danagbemava-nc** [comment]
Hi @FarhanAli-98, oddly enough, I still cannot reproduce with the version of the app that is deployed. 

Can you do some performance monitoring through your browser devtools to see if there are any noticeable frame losses? Can you also check in an incognito window to see if this persists?

**Comment by FarhanAli-98** [comment]
Hi @danagbemava-nc 
It's surprising to me that you are not able to reproduce this issue from my deployment.Here are the results of my testing:

Windows:
- I conducted tests on Windows, and the issue couldn't be reproduced.
Macbook:

- The issue was reproducible only on Chrome and Brave browsers, even in incognito mode. but when we open Chrome inspect then the not replicate.
- However, when using Safari, the issue couldn't be reproduced.
It's pretty hard to reproduce the issue on current hosting environment currently we are using only single screen the issues visibility less. but if we have multiple screens then we observed lots of jittery effects.
[Please check this video](https://www.loom.com/share/c5b5f3b054214cb5af735ba3ea49801e?sid=aff0626c-5876-4c6c-a860-17f39f92aa8a)

**Comment by danagbemava-nc** [comment]
Thanks for the update. @FarhanAli-98, it is rather strange, I asked one of my colleagues to look into it and he could also not reproduce. Would it be possible to provide a slightly more complex example so that we can check to see if we can reproduce this? 

Can you also run the sample code on the `master` channel to see if the bug still reproduces there?

**Comment by FarhanAli-98** [comment]
Hello @danagbemava-nc, I have a few brief inquiries:

1. Could you specify the MacBook model you're currently utilizing?
2. The majority of issues seem to be arising on macOS Ventura, particularly with Brave and Chrome, and less possibility in macOS monterey.
3. Please access this link: https://dev.bespoke.ly/panda/shop and repeatedly attempt to open the first product. Confirm if the issue occurs for you as demonstrated in the video. I've tested this on various MacBooks; Most were able to replicate the problem, while others were not.

https://github.com/flutter/flutter/assets/50108735/f3c2dc1c-020a-4275-8b90-4a17380af22f

**Comment by FarhanAli-98** [comment]
@danagbemava-nc, I've switched to the `flutter channel master` and the `Flutter SDK version is 3.14.0`, yet the problem persists.

**Comment by danagbemava-nc** [comment]
Hi @FarhanAli-98, I am using an M1 Macbook Pro 13" running macOS ventura (13.4.1). I am using Arc which is Chromium-based, I also checked with chrome but I can't seem to reproduce it as well. 

Nonetheless, this is an issue that needs to be investigated. @FarhanAli-98, just to confirm, you do not have this issue with Canvaskit, correct? 

<details>
<summary>recording</summary>

https://github.com/flutter/flutter/assets/88313112/43e9d1ec-29b8-46b9-a81c-9a68dd36b023
</details>

**Comment by FarhanAli-98** [comment]
Hi @danagbemava-nc,
I want to express my gratitude for your efforts. If it's possible, could you kindly attempt these steps on a macOS system running an Intel-based chip, such as any MacBook from the 15th to the 20th generation? This issue appears to be more prevalent in these specific generations of MacBooks.

>  @FarhanAli-98, just to confirm, you do not have this issue with Canvaskit, correct?

Yes, when I use Canvaskit, the problem no longer occurs. However, it does lead to increased initial loading times and a larger build size, which directly impacts the app's performance.

> Also, was there a particular version of flutter you started to notice this behaviour?

I've tested this behaviour across Flutter versions ranging from `Flutter SDK 3.3.10 to 3.14.0`, using the `--web-renderer html` Engine, and the issue persists.

**Comment by FarhanAli-98** [comment]
Finding:
I am presently using Chrome version `Version 116.0.5845.187 (Official Build) (x86_64)`, and I can confirm that the problem can be replicated.

However, when I roll back my Chrome to `Version 80.0.3987.149 (Official Build) (64-bit)`, I no longer experience the jittery effects. Therefore, I can conclude that it is functioning flawlessly on the previous version, while the issue persists on the most recent version.
Comparing your Chrome version with mine and giving it a try is a straightforward task for me.

**Comment by danagbemava-nc** [comment]
Thanks for the update @FarhanAli-98. I am also using `Google Chrome 116.0.5845.187`. The interesting thing was my colleague did test on an intel mac. 

Nonetheless, based on your findings and the recordings above, I will label this issue for further investigation from the web team.

Thanks for your patience. 

---
### Triage report
- This issue is only with the HTML renderer
- This issue is only on chrome (chromium-based) browsers https://github.com/flutter/flutter/issues/133543#issuecomment-1711539066
- It seems to reproduce on certain versions of chrome https://github.com/flutter/flutter/issues/133543#issuecomment-1715525419
- It does not reproduce on some devices or reproduce consistently on all devices. 

Labeling for further investigation

**Comment by FarhanAli-98** [comment]
Hello 
@danagbemava-nc 
Is there any new information regarding the problem with jittery transitions? It would be highly appreciated if a solution could be identified.

**Comment by yjbanov** [comment]
I ran the app using `flutter run -d chrome --web-renderer=html --release` but I'm unable to reproduce the issue. The only way I can see glitches that look similar to the reported ones is when I have Chrome DevTools open and check the "Disable cache" checkbox in the Network tab, which is expected in the HTML renderer.

Do you have DevTools open by any chance
