### ISSUE TITLE
Entering Flag Emoji places cursor at the beginning of text field

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#13357]
Entering a Flag emoji into a text field moves the blinking cursor at the beginning of the text field.

Letters entered after the flag will appear at the right place (after the flag) and the cursor then jumps back to the correct location.

I saw this on Android.

**Comment by zoechi** [comment]
I can not reproduce and assume this is fixed.
```
[✓] Flutter (Channel master, v1.2.2-pre.21, on Mac OS X 10.14.3 18D42, locale en-AT)
```
