### ISSUE TITLE
When there are multiple Expanded in the row, if one has enough space, the other can occupy it. Like the flex layout of the web.

### ISSUE THREAD

**Issue by zhou26192619** [flutter/flutter#133521]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

When there are multiple Expanded in the row, if one has enough space, the other can occupy it. Like the flex layout of the web.

In the picture, the content of text is uncertain, and a text can be displayed completely with just a little more space. The flex layout on the web is completely fine and easy to implement.

### Expected results

```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .color1 {
            background: #ff0000;
        }

        .color2 {
            background: #00ff00;
        }

        .color3 {
            background: #0000ff;
        }

        .color4 {
            background: #ff00ff;
        }

        .block {
            height: 100px;
            width: 100px;
        }

        .grow {
            flex-grow: 1;
        }
    </style>
</head>

<body>
    <div style="display: flex;">
        <div class="color1 block"></div>
        <div class="color2 grow">aaaaaaaa</div>
        <div class="color3 grow">ccc</div>
        <div class="color4 block"></div>
    </div>
</body>

</html>
```

![20230829084824](https://github.com/flutter/flutter/assets/4471261/ad04d477-9f6c-44d6-8ef6-101382969b56)

### Actual results

![20230828154341](https://github.com/flutter/flutter/assets/4471261/6ab031d6-b986-4255-a387-2e5aa7fe5072)

### Code sample

<details><summary>Code sample</summary>

```dart
Row(
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.circular(1000),
                      child: Image.network(
                        'https://cdn.pixabay.com/photo/2023/08/05/23/40/bird-8171927_640.jpg',
                        fit: BoxFit.fill,
                        height: 30,
                        width: 30,
                      ),
                    ),
                    Expanded(
                      child: Container(
                        margin: const EdgeInsets.fromLTRB(10, 0, 10, 0),
                        child: Text(
                          'aaaaaaa',
                          overflow: TextOverflow.ellipsis,
                          style: const TextStyle(fontSize: 16, color: Colors.black),
                        ),
                      ),
                    ),
                    Image.network(
                      'https://cdn.pixabay.com/photo/2023/08/05/23/40/bird-8171927_640.jpg',
                      fit: BoxFit.fill,
                      height: 20,
                      width: 20,
                    ),
                    Container(
                      child: Text('回复'),
                      margin: EdgeInsets.fromLTRB(10, 0, 10, 0),
                    ),
                    Expanded(
                      child: Container(
                        margin: const EdgeInsets.fromLTRB(0, 0, 10, 0),
                        child: Text(
                          'c',
                          overflow: TextOverflow.ellipsis,
                        ),
                      ),
                    ),
                    Text('2022-02-22')
                  ],
                ),
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.10.6, on macOS 13.3 22E252 darwin-arm64, locale
    zh-Hans-CN)
    • Flutter version 3.10.6 on channel stable at
      /Users/wanzhong/AndroidStudioProjects/flutter
    ! Warning: `dart` on your path resolves to
      /opt/homebrew/Cellar/dart/3.0.5/libexec/bin/dart, which is not inside your
      current Flutter SDK checkout at
      /Users/wanzhong/AndroidStudioProjects/flutter. Consider adding
      /Users/wanzhong/AndroidStudioProjects/flutter/bin to the front of your
      path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (7 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/wanzhong/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] VS Code (version 1.79.2)
    • VS Code at /Users/wanzhong/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Face RK3399 (mobile) • AE64DQC06G • android-arm64  • Android 7.1.2 (API
      25)
    • macOS (desktop)      • macos      • darwin-arm64   • macOS 13.3 22E252
      darwin-arm64
    • Chrome (web)         • chrome     • web-javascript • Google Chrome
      116.0.5845.110
```

</details>

**Comment by huycozy** [comment]
Hi @zhou26192619 
Thanks for filing the issue. I ran your HTML page and compared it with Flutter Web but I see they look similar in flex layout.  Or maybe the sample code doesn't describe the issue clearly?

| html | flutter |
| --------------- | --------------- |
<img width="400" src="https://github.com/flutter/flutter/assets/104349824/570095ad-e0be-4ae1-8621-d100dba0f266"> | <img width="400" src="https://github.com/flutter/flutter/assets/104349824/506c724e-1588-4575-8cf6-d97d1f462631">

**Comment by zhou26192619** [comment]
> Hi @zhou26192619 Thanks for filing the issue. I ran your HTML page and compared it with Flutter Web but I see they look similar in flex layout. Or maybe the sample code doesn't describe the issue clearly?
> 
> html	flutter
> <img alt="" width="400" src="https://user-images.githubusercontent.com/104349824/263941542-570095ad-e0be-4ae1-8621-d100dba0f266.png">	<img alt="" width="400" src="https://user-images.githubusercontent.com/104349824/263941571-506c724e-1588-4575-8cf6-d97d1f462631.png">

Actual results is a screenshot of Android. When text a is very long, ellipses will be displayed directly, instead of occupying the space of text c first, and only displaying ellipses when it is not enough.

On the web side, when there is not enough space in text a, it will occupy the area of text c, while on the Android side, it will not. Both have fixed widths. Can Android and web effects be unified.

**Comment by huycozy** [comment]
I see it now. But you can solve it by following code:

<details>
<summary>Complete sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyWidget(),
    ),
  );
}

class MyWidget extends StatefulWidget {
  const MyWidget({super.key});

  @override
  State<MyWidget> createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Row(
          children: [
            ClipRRect(
              borderRadius: BorderRadius.circular(1000),
              child: Image.network(
                'https://cdn.pixabay.com/photo/2023/08/05/23/40/bird-8171927_640.jpg',
                fit: BoxFit.fill,
                height: 30,
                width: 30,
              ),
            ),
            IntrinsicWidth(
              child: Container(
                margin: const EdgeInsets.fromLTRB(10, 0, 10, 0),
                child: const Text(
                  'aaaaaaaaaaaaaaaaaaaa',
                  overflow: TextOverflow.ellipsis,
                  style: TextStyle(fontSize: 16, color: Colors.black),
                ),
              ),
            ),
            Image.network(
              'https://cdn.pixabay.com/photo/2023/08/05/23/40/bird-8171927_640.jpg',
              fit: BoxFit.fill,
              height: 20,
              width: 20,
            ),
            Container(
              margin: const EdgeInsets.fromLTRB(10, 0, 10, 0),
              child: const Text('回复'),
            ),
            Expanded(
              child: Container(
                margin: const EdgeInsets.fromLTRB(0, 0, 10, 0),
                child: const Text(
                  'c',
                  overflow: TextOverflow.ellipsis,
                ),
              ),
            ),
            const Flexible(
              child: Text(
                '2022-02-22',
                overflow: TextOverflow.ellipsis,
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```
</details>

In this updated sample code, I used `IntrinsicWidth` for the first Expanded item. Also, need to wrap the latest item with `Flexible` to prevent the overflow layout issue. 

![Screenshot 2023-08-29 at 17 46 18](https://github.com/flutter/flutter/assets/104349824/69a47f75-222e-4bc5-9347-9b169972f99e)

The main idea from https://github.com/flutter/flutter/issues/46803#issuecomment-821804152. That issue is not exactly the same but a similar case for the minimum height of child inside a flex. You can also follow up on it for updates. 

I will close this issue as solved. If you disagree, please write in the comments with more information.

**Comment by zhou26192619** [comment]
> I see it now. But you can solve it by following code:
> 
> Complete sample code
> In this updated sample code, I used `IntrinsicWidth` for the first Expanded item. Also, need to wrap the latest item with `Flexible` to prevent the overflow layout issue.
> 
> ![Screenshot 2023-08-29 at 17 46 18](https://user-images.githubusercontent.com/104349824/263994297-69a47f75-222e-4bc5-9347-9b169972f99e.png)
> 
> The main idea from [#46803 (comment)](https://github.com/flutter/flutter/issues/46803#issuecomment-821804152). That issue is not exactly the same but a similar case for the minimum height of child inside a flex. You can also follow up on it for updates.
> 
> I will close this issue as solved. If you disagree, please write in the comments with more information.

Thank you for your sample. But my business is for user a to reply to user c's posts. The length of user names for both a and c is variable, while others need to be fully displayed, which may not be suitable for this use case. But thank you very much and we look forward to future solutions.
