### ISSUE TITLE
Can't reach the credential uid while sending the data to firestore database.

### ISSUE THREAD

**Issue by MUGDAD-78** [flutter/flutter#133541]
I have two pages and I want the user to enter his email and password and then move to the other page as the pictures.
<img width="161" alt="Screenshot 2023-08-29 140542" src="https://github.com/flutter/flutter/assets/129184865/a3b8c798-2be2-4511-911e-20bb35948ba6">
<img width="193" alt="Screenshot 2023-08-29 140606" src="https://github.com/flutter/flutter/assets/129184865/e57a9f29-1d53-449a-8ef3-4e436518c716">
 
The issue is that I want to name the database document by user uid but I can't reach the local var which is credential var so as to get the user uid property. 

There the codes 

this function is on the register page which is the first page.
```
Register() async {
    setState(() {
      isLoading = false;
    });
    try {
      final credential =
          await FirebaseAuth.instance.createUserWithEmailAndPassword(
        email: emailController.text,
        password: passwordController.text,
      );
    } on FirebaseAuthException catch (e) {
      if (e.code == 'weak-password') {
        showSnackBar(context, 'The password provided is too weak.');
      } else if (e.code == 'email-already-in-use') {
        showSnackBar(context, 'The account already exists for that email.');
      }
    } catch (e) {
      showSnackBar(context, e.toString());
    }

    isLoading = true;
  }
```
this function in the complete profile page which is the next page I want the user to move on.

```
sendDataToFirestore() {
    try {
      CollectionReference users = FirebaseFirestore.instance.collection('User');
      UserData userData = UserData(
          firstname: firstNameController.text,
          lastname: lastNameController.text,
          phonenumber: phoneNumberController.text,
          address: addressController.text);
      users
          .doc('ABBBBBB')            // here I want to put the user uid.
          .set(
            userData.convert2Map(),
          )
          .then((value) => print('user Added'))
          .catchError((error) => print("Failed to merge data: $error"));
    } catch (e) {
      print(e.toString());
    }
  }
```

I want to get the user ID from the first code but the issue is that it's a local var, can anyone tell me how to get the user ID or if I need to make changes in any code?

**Comment by opxdelwin** [comment]
you can get uid of active user by `FirebaseAuth.instance.currentUser?.uid`.

**Comment by darshankawar** [comment]
@MUGDAD-78 
Your issue is better suited for support channels like StackOverflow.
Closing from here, as this isn't related to the bug tracking and feature requests for this repo.
