### ISSUE TITLE
[CP] 3.14: [Impeller] Apply color blends on the CPU; fix mask blurs and the Gaussian blur coverage hint.

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#133511]
### Issue Link

https://github.com/flutter/flutter/issues/132936

### Commit Hash

https://github.com/flutter/engine/commit/53595c937df156b932850807869f539c15042919

### Target

beta

### PR Link

https://github.com/flutter/engine/pull/45193

### Changelog Description

Fixes issues in the generic mask blurring path as well as geometry coordinate mapping problems in the Gaussian blur.

### Impacted Users

This issue affects Impeller users.

### Impact Description

This fixes a variety of rendering problems with Impeller shadows which are exacerbated by the presence of dirty regions. When elements are moving over the top of a non-animated shadow, the shadow may sometimes render as faded or become invisible. 

### Workaround

There are no simple workaround for this issue.

### Risk

medium

### Test Coverage

yes

### Validation Steps

To test, run the example Flutter app in https://github.com/flutter/flutter/issues/132936 and verify that the blur does not cut out while scrolling.
Alternatively, run the `AiksTest.ClippedBlurFilterRendersCorrectly` playground golden and verify that the blur does not dim out as it approaches the top edge of the screen.

**Comment by itsjustkevin** [comment]
@zanderso could you review this cherry-pick?

**Comment by zanderso** [comment]
cp lgtm

**Comment by bdero** [comment]
Should we close this as complete, or are there more steps from here?

**Comment by itsjustkevin** [comment]
@bdero the release engineer will close this PR when it is released.
