### ISSUE TITLE
[flutter_tools] ProcessException trying to call git

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#133585]
On stable/3.13.1

```
ProcessPackageException: ProcessException: Failed to find "git" in the search path.  Command: git
at LocalProcessManager.runSync(local_process_manager.dart:118)
at ErrorHandlingProcessManager.runSync.<anonymous closure>(error_handling_io.dart:714)
at _runSync(error_handling_io.dart:590)
at ErrorHandlingProcessManager.runSync(error_handling_io.dart:713)
at _runSync(version.dart:835)
at _gitCommitDate(version.dart:434)
at FlutterVersion.checkFlutterVersionFreshness(version.dart:279)
at FlutterCommandRunner.runCommand.<anonymous closure>(flutter_command_runner.dart:311)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at FlutterCommandRunner.runCommand(flutter_command_runner.dart:285)
at <asynchronous gap>(async)
at run.<anonymous closure>.<anonymous closure>(runner.dart:115)
at <asynchronous gap>(async)
at AppContext.run.<anonymous closure>(context.dart:150)
at <asynchronous gap>(async)
at main(executable.dart:90)
at <asynchronous gap>(async)
```

**Comment by andrewkolos** [comment]
Discussed with @christopherfujino. I see two ways to resolve this issue:

1. Early on in the tools execution, make a call to [`canRun`](https://api.flutter.dev/flutter/package-process_process/ProcessManager/canRun.html) to make sure `git` is available. If it isn't, tool exit with a useful message. The downside is that this has a non-zero performance penalty. On my windows desktop machine at home, a trivial benchmark estimates that this will take 3-4ms (compiled exe).
2. Make sure all invocations of `git` (at least those in version.dart) are routed through some abstraction (a simple function will do) that catches `ProcessException`s and tool exits with a friendly message. This avoids the performance penalty, but adds another layer of indirection to any code path that depends on git.

Regardless of all this, this isn't a top crasher; and the existing error message (as noisy it may be) should be sufficient for most users to realize that they need `git`. I'm lowering the priority to P2.

**Comment by andrewkolos** [comment]
Another option is to catch this exception at-or-near the top level of the tool code (such as in [`handleToolError`](https://github.com/flutter/flutter/blob/48187028c11ca8ca10e0179705d25553e1fe2c14/packages/flutter_tools/lib/runner.dart#L147)). We could catch `ProcessException`, grep its message string, and (if there's a match) exit without generating a crash report.

**Comment by andrewkolos** [comment]
Putting this off because I don't see a clear best solution.

**Comment by andrewkolos** [comment]
> Another option is to catch this exception at-or-near the top level of the tool code (such as in [`handleToolError`](https://github.com/flutter/flutter/blob/48187028c11ca8ca10e0179705d25553e1fe2c14/packages/flutter_tools/lib/runner.dart#L147)). We could catch `ProcessException`, grep its message string, and (if there's a match) exit without generating a crash report.

I think this is a good approach, but the problem relying on the error messages from the OS is that they are localized, so the messages might differ between languages. However, matching on `ProcessException` and `'git'` might be sufficient.

**Comment by bkonyi** [comment]
This still seems to be an issue.

**Comment by bkonyi** [comment]
I looked through the crash samples and they're all from Windows users.

**Comment by andrewkolos** [comment]
> This still seems to be an issue.

https://github.com/flutter/flutter/pull/154445 won't be in user's hands until 3.27. Are you still seeing this in beta?

**Comment by bkonyi** [comment]
Ugh, I was looking at the wrong page of crash reports 🤦‍♂️ there's nothing on the beta channel that I can see. Sorry about that.
