### ISSUE TITLE
build web and run web --release not working, it's building an older version of the app 

### ISSUE THREAD

**Issue by rmcassio** [flutter/flutter#133599]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

The 2 commands are not working properly, tried to delete the build folder and flutter clean but it's not working. When I run the command on flutter run without the argument --release it works. 

### Expected results

It has to build the newer version of the app.

### Actual results

It's building an older version.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @rmcassio, what version of flutter are you using? Does this happen with every app? Can you provide a recording of the issue? Can you also provide some steps to reproduce? 

Thank you

**Comment by rmcassio** [comment]
Hi @danagbemava-nc , thanks for replying!! I figured it out, it was the web folder, I deleted the flutter_service_worker.js, main.dart.js and flutter.js and it worked. I compiled in debug mode and after that it was compiling ok!!

**Comment by danagbemava-nc** [comment]
Hi @rmcassio, did you make any changes to those files? Do you happen to know when it started behaving this way and what you were doing at the time that led to this?

**Comment by lyf571321556** [comment]
same issue on v3.13.1

**Comment by lyf571321556** [comment]
> same issue on v3.13.1,When one builds a Flutter web app with 'flutter build web --release/--profile --web-renderer html',then the app does not load (blank screen),run the command without the argument --release or --profile web app works.

i found that plugin modular led to this issue, [https://github.com/Flutterando/modular/issues/890](url)

**Comment by rmcassio** [comment]
hello @danagbemava-nc, no I didn't change those files, I noticed it start behaving this way after I upgraded to 3.13.1. It's strange that after I deleted those files in the web folder it worked. And same as @lyf571321556 --release or --profile had the same behavior.

**Comment by danagbemava-nc** [comment]
> It's strange that after I deleted those files in the web folder it worked

Hi @rmcassio, this was in the build/web directory, correct? 

We will need a minimal reproducible code sample preferably without any third-party packages so that we can get to the root of this issue.
