### ISSUE TITLE
InitialScrollOffset based on MediaQueryData fails in release mode

### ISSUE THREAD

**Issue by xqwzts** [flutter/flutter#13350]
I'm initializing the `initialScrollOffset` of my GridView's ScrollController using MediaQueryData, this seems to be working fine, but when I build my app in release mode [`flutter build apk` or `flutter run --release`] it has no effect, and the GridView loads at an initial offset of 0.

This has no effect in release mode, works fine in debug:
```dart
@override
  void didChangeDependencies() {
    super.didChangeDependencies();

    initialPosition = 50 * MediaQuery.of(context).size.width / 7;

    _gridController = new ScrollController(
      initialScrollOffset: initialPosition,
    );
```

This works in both release and debug:
```dart
@override
  void didChangeDependencies() {
    super.didChangeDependencies();

    initialPosition = 2470.0;

    _gridController = new ScrollController(
      initialScrollOffset: initialPosition,
    );
```

I'm calculating my offset based on the window width because this is a GridView with `SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: 7)` so the size of an individual item is 
`MediaQuery.of(context).size.width / 7`. Is there a cleaner way of getting item extents from a grid view and using them in the initialScrollOffset?

## Logs

No issues found in flutter analyze and nothing special logged during the debug run.

## Flutter Doctor
Running flutter doctor...
[✓] Flutter (on Linux, locale en_US.UTF-8, channel alpha)
    • Flutter at /home/vic/devel/flutter
    • Framework revision e8aa40eddd (7 weeks ago), 2017-11-30 13:29:59 -0800
    • Engine revision 77d8acb9be
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /home/vic/Android/Sdk
    • Platform android-26, build-tools 26.0.1
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at /usr/local/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 19.1
    • Dart plugin version 172.4343.25

[✓] Connected devices
    • MI 5 • 0123456789ABCDEF • android-arm • Android 7.1.1 (API 25)

**Comment by xqwzts** [comment]
[This](https://github.com/flutter/flutter/issues/11697#issuecomment-323568560) explains the different behavior in release vs debug.

So it seems when the controller is initialized MediaQuery.of returns 0 for the size. Widgets depending on it will rebuild, but since the gridview has already been built with an initialScrollOffset of 0, it won't change. 

Resolved by manually animating to the new position in `didChangeDependencies`.

**Comment by Hixie** [comment]
Yeah, in release builds we build the app so fast we don't have the size by the time we are building the first frame. :-(
