### ISSUE TITLE
Release mode behaves differently when Expanded widget is set as parent data 

### ISSUE THREAD

**Issue by sohitEngg** [flutter/flutter#133551]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I have a ListView which I need to use in a column to show a bar above the ListView and there are list items. 

In one of the ListItem I used Expanded as the parent of ListView but this seems to be an issue because of incorrect use of ParentData.

But surprisingly it is working fine in the DEBUG mode however when we test release mode it shows error and prevents UI rendering. 

Issues like this cause lots of troubleshooting and surprises, I think release and debug mode should point to same set of rules irrespective of the case.

### Expected results

I think release and debug mode should point to same set of rules irrespective of the code principals.

### Actual results

Release build behaves differently 

### Code sample

`Column -> Expanded -> ListView -> Item -> Expanded -> ClipRect`

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F770820d darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.81.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

**Comment by danagbemava-nc** [comment]
Hi @sohitEngg, this is a known issue that is being tracked in https://github.com/flutter/flutter/issues/108186. 

Kindly subscribe to the original issue for updates. 

Closing from here as duplicate. 

Thank you
