### ISSUE TITLE
Update Cocoapods version in CI after DT_TOOLCHAIN_DIR fix is in an official release

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#133584]
An [error](https://github.com/flutter/flutter/issues/132755) was introduced to Cocoapods with Xcode 15, which causes macOS builds to fail. 
```
error: DT_TOOLCHAIN_DIR cannot be used to evaluate LD_RUNPATH_SEARCH_PATHS, use TOOLCHAIN_DIR instead (in target 'Pods-Runner' from project 'Pods')
```
The issue was fixed upstream in Cocoapods (https://github.com/CocoaPods/CocoaPods/pull/12009), but the fix is not in an official release yet.

We added a workaround to Flutter in https://github.com/flutter/flutter/issues/132755, but we had to [ignore some errors in tests](https://github.com/flutter/flutter/pull/133588) due to this.

This is the tracking issue to upgrade Cocoapods in CI once https://github.com/CocoaPods/CocoaPods/pull/12009 is in an official release.

**Comment by cbracken** [comment]
This looks like a likely dupe of https://github.com/flutter/flutter/issues/131527.

**Comment by ManuelRauber** [comment]
Hi @vashworth :) 

According to the CocoaPods releases the mentioned PR (https://github.com/CocoaPods/CocoaPods/pull/12009) is now official in 1.13.0: https://github.com/CocoaPods/CocoaPods/releases/tag/1.13.0

**Comment by cbracken** [comment]
I've sent a patch to bump the recommended version in https://github.com/flutter/flutter/pull/135447

**Comment by godofredoc** [comment]
Umbrella bug for updating the ruby self contained package: https://github.com/flutter/flutter/issues/136377

**Comment by stuartmorgan** [comment]
@godofredoc I can see there's active work happening on blocking work; do you have an ETA for Cocoapods itself being updated? I'm trying to evaluate whether to invest time in a flutter/packages workaround for the old version (https://github.com/flutter/flutter/issues/136737) or if it's become moot shortly due to having 1.13 on the bots.

**Comment by godofredoc** [comment]
@cbracken can you please validate this has been fixed with the new ruby dep?

**Comment by godofredoc** [comment]
Removing myself from this bug, everything has landed and only the confirmation is missing. @vashworth FYI

**Comment by vashworth** [comment]
Verified fixed in https://github.com/flutter/flutter/pull/140395.
