### ISSUE TITLE
controller!.stopVideoRecording() returning a jpg, not mp4

### ISSUE THREAD

**Issue by cmptscpeacock** [flutter/flutter#133540]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Flutter 3.10.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f468f3366c (7 weeks ago) • 2023-07-12 15:19:05 -0700
Engine • revision cdbeda788a
Tools • Dart 3.0.6 • DevTools 2.23.1

Package
camera: ^0.10.5+3

Using the camera package, I've noticed if I call **await cameraController!.takePicture()** whilst **await cameraController!.startVideoRecording()** is running, when I call **XFile file = await controller!.stopVideoRecording();** it returns the .jpg file that the takePicture() created.

I'm testing a motion detection operation by creating one image using takePicture() and then a second image using takePicture() and comparing the two (this works, and I can report motion detection based on the file differences). This motion detection (using takePicture() ) can also run while a video recording is running, but means when I call stopVideoRecording() it uses the last .jpg that was created by the takePicture().

I am not sure if this is by design, or a bug, but the camera package seems to return a jpg and not mp4 when calling stopVideoRecording()

### Expected results

stopVideoRecording() should return a .mp4 file even if takePicture() has been used during a recording

### Actual results

Instead of a mp4 being returned with stopVideoRecording() it returns a jpg from the takePicture()
```
XFile
_bytes:
null
_file:
_File (File: '/data/user/0/com.example.app1/cache/CAP7585786840083562893.jpg')
_lastModified:
null
_length:
null
_mimeType:
null
hashCode:
663534142
mimeType:
null
name:
"CAP7585786840083562893.jpg"
path:
"/data/user/0/com.example.app1/cache/CAP7585786840083562893.jpg"
runtimeType:
Type (XFile)
```

### Code sample

Here is the code to start a video recording

  ```
Future<void> startVideoRecording() async {
    final CameraController? cameraController = controller;

    try {
      await cameraController!.startVideoRecording();

    } on CameraException catch (e) {
      print('Error starting to record video: $e');
    }
  }
```

Here is the code to stop the video recording

```
  Future<XFile?> stopVideoRecording() async {
    if (!controller!.value.isRecordingVideo) {

    try {
      XFile file = await controller!.stopVideoRecording();
      return file;
    } on CameraException catch (e) {
      print('Error stopping video recording: $e');
      return null;
    }
  }``
```

Here is the code that takes two images to compare to each other (using another method not shown here)

```
Future<void> takeImagesToCompare() async {

    XFile file1 = await controller!.takePicture();

    XFile file2 = await controller!.takePicture();
  
  }
```

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

I only use Edge, so Chrome error below:

[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.19045.3324], locale en-GB)
    • Flutter version 3.10.6 on channel stable at C:\software\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (7 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\ChrisPeacock\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop for Windows (Visual Studio Professional 2022 17.4.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
    • Visual Studio Professional 2022 version 17.4.33122.133
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.81.1)
    • VS Code at C:\Users\ChrisPeacock\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.70.0

[√] Connected device (3 available)
    • SM G950F (mobile) • ce0718276937941201 • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.19045.3324]
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 116.0.1938.62
    ! Device emulator-5562 is offline.

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

**Comment by darshankawar** [comment]
Thanks for the report @cmptscpeacock 
Can you take a look at this method provided by the camera package and see if it helps in your case ?

https://pub.dev/documentation/camera/latest/camera/ImageFormat-class.html

Maybe an implementation like below and check if you could pass the desired extension ?

`final CameraImageFormat imageFormat = CameraImageFormat(ImageFormatGroup.jpeg`

**Comment by cmptscpeacock** [comment]
Additionally, I did get this response from Bard (using Bard tentatively for now, so the response could be wrong):

The ImageFormatGroup class is used to specify the image format for the camera. It does not have any effect on the video recording.

The stopVideoRecording() method will always use the last frame that was captured by the camera, regardless of the image format that was used to capture the frame.

To prevent the stopVideoRecording() method from using the jpg saved by takePicture(), you can either:

Do not call takePicture() while the camera is recording a video.
Call stopVideoRecording() before calling takePicture().

So, I think I need to find a way to get the mp4 that was created as takePicture() is being used and affecting stopVideoRecording()

**Comment by darshankawar** [comment]
Thanks for the feedback and going by above comment, I think it could be related to the way `takePicture()` and `stopVideoRecording()` methods used in sync. Maybe if there's a way for you to check on native camera app as well and see how it behaves in similar case would be helpful to know if this is specific to Flutter or not.

**Comment by cmptscpeacock** [comment]
@darshankawar 

My workaround was the find the latest .mp4 file in the temporary directory and return that to an xfile I needed. It works.

However, the use of takePicture to constantly take a picture for the purpose of motion detection is not a good method. The camera constantly hangs whilst it runs.

Using a screenshot package wouldn't work either as the screenshot vs what the camera sees are two different images with what I'm doing with overlays, etc.

**Comment by cmptscpeacock** [comment]
Also, I have tried a few ways with the native camera package but always some issue with it. takePicture causes the app to hang until it's finished. You can edit the camera.java file, which makes it instant. However, when used with startVideoRecording / stopVideoRecording the app hangs every half second or so. I can't use startImageStream with startVideoRecording as it needs exclusive access to the camera, so constantly having issues with the camera package with what I want to do.

**Comment by darshankawar** [comment]
Ok, thanks for doing the analysis. Can you provide us a runnable code sample that we can directly copy paste and run to verify this further ?

**Comment by cmptscpeacock** [comment]
@darshankawar Just add a takePicture before the stopViceoRecording():

```
Future<XFile?> stopVideoRecording() async {
    if (!controller!.value.isRecordingVideo) {

await controller!.takePicture();

    try {
      XFile file = await controller!.stopVideoRecording();
      return file;
    } on CameraException catch (e) {
      print('Error stopping video recording: $e');
      return null;
    }
```

**Comment by darshankawar** [comment]
Thanks for the update. I used the code snippet above and used in the camera package example, ran on iOS device using latest master version of the framework. Recorded and stopped video which then shows a snackbar with path where the video is stored. It saves it in .mp4 format, as shown in below video:


https://github.com/flutter/flutter/assets/67046386/a035f2eb-6a3f-44d1-8c81-b44aa8234e93

Updated code snippet:

```
Future<XFile?> stopVideoRecording() async {
    final CameraController? cameraController = controller;

    if (cameraController == null || !cameraController.value.isRecordingVideo) {
      await controller!.takePicture();
      return null;
    }

    try {
      return cameraController.stopVideoRecording();
    } on CameraException catch (e) {
      _showCameraException(e);
      return null;
    }
  }
```

**Comment by cmptscpeacock** [comment]
may be an issue with android then as that's what I'm using

**Comment by darshankawar** [comment]
> may be an issue with android then as that's what I'm using

Also tried the same plugin code on Pixel 6 emulator (since I don't have a physical device to verify), but after stopping the recording, it does saved it in .mp4 format, as shown in below video:


https://github.com/flutter/flutter/assets/67046386/a1d9cb0c-87e0-4b0a-9105-285dc9f5409c
