### ISSUE TITLE
video_player package error 

### ISSUE THREAD

**Issue by stemuk** [flutter/flutter#13351]
I get an error after testing the [video_player package](https://pub.dartlang.org/packages/video_player) (version 0.0.6), where the error message is shown in the area where the Video was supposed to play.

![screenshot from 2017-12-05 16-05-59](https://user-images.githubusercontent.com/17005007/33613963-4e74f8b4-d9d6-11e7-9da5-628f064dc208.png)

I used the example from the pub.dartlang.org page, but I wasn't able to get the implementation of  video_player working as intended. My code is [here](https://www.pastiebin.com/5a26b6f7ce0d8), but since I used the example I would expect the error to be caused by the video_player package. Could someone take a quick look?

**Comment by sigurdm** [comment]
The video player depends on new features from the engine.
Try a 'flutter upgrade'

**Comment by sigurdm** [comment]
If it still does not work, can you post the output of 'flutter doctor' and the logging output from flutter?

**Comment by stemuk** [comment]
Thanks, it was indeed the flutter version :+1:
