### ISSUE TITLE
Incomplete list of release candidate branches in the dashboard.

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#133622]
The list of branches in the dashboard have different problems:

* List of branches is incomplete.
* Some revert branches are showing up
* Master or main branch is not listed.

![image](https://github.com/flutter/flutter/assets/54371434/e13505c1-8dfd-427c-8076-d42791ef5eb6)

**Comment by godofredoc** [comment]
@XilaiZhang what is the context for trying to get branches from both data store and github?

**Comment by godofredoc** [comment]
Link to file: https://cs.opensource.google/flutter/cocoon/+/main:app_dart/lib/src/request_handlers/get_branches.dart;bpv=1

**Comment by godofredoc** [comment]
What was the issue https://github.com/flutter/cocoon/pull/2924 was trying to fix?

**Comment by XilaiZhang** [comment]
right theoretically from datastore it is supposed to get branches with recent activities, and from github it is supposed to get release branches (beta, stable, dev). umm and yeah looking at the dashboard they do not show up, I wonder if these branches exist in database at all. 

umm I can probably look at this later, need to work on rolls and cl/560915610 tonight

**Comment by godofredoc** [comment]
beta, stable and dev only exist for flutter/flutter

**Comment by XilaiZhang** [comment]
right yeah theoretically it retrieves beta branch from reading the file https://github.com/flutter/flutter/blob/beta/bin/internal/release-candidate-branch.version, and retrieves the stable branch name from reading the file https://github.com/flutter/flutter/blob/stable/bin/internal/release-candidate-branch.version. But something must have went wrong somewhere.

**Comment by godofredoc** [comment]
@drewroengoogle are we ingesting beta | stable branches data?

**Comment by godofredoc** [comment]
I see multiple areas of opportunity:

* The get_branches is extremely slow 2+ seconds, the results can be cached to avoid hitting the APIs every time we call the endpoint.
* The current implementation may eventually work, as the Branch entity is populated (~3Months)
* Beta, master, stable, etc should be already present but they are not.

Proposal: 

1. - Get the branches directly from Checklist entity with a query similar to:

```
select Branch from CheckList where FlutterRepoPath = 'xyz' and created_timestamp < 3months
group by branch
order by branch
```

2.- Cache the query result for 1+ minutes to avoid hitting the datastore too frequently.

3.- Remove Branch entity.
4.- Start ingesting beta, stable results
5.- Remove the calls to the github service.

Note: This will require new indexes to be created.

**Comment by drewroengoogle** [comment]
> @drewroengoogle are we ingesting beta | stable branches data?

We currently do not have any tasks associated with beta/stable, but we could potentially do that with dart-internal results, if that's what you're asking. I can make a new issue to track that if you think that's the correct thing to do

**Comment by godofredoc** [comment]
Yes please, we would like flutter dashboard to show the same content as here: https://luci-milo.appspot.com/p/dart-internal/g/flutter_packaging/console for beta and stable.
