### ISSUE TITLE
[CP] handle exceptions raised while searching for configured android studio

### ISSUE THREAD

**Issue by andrewkolos** [flutter/flutter#133603]
### Issue Link

https://github.com/flutter/flutter/issues/133055

### Commit Hash

e1967ec

### Target

stable

### PR Link

https://github.com/flutter/flutter/pull/133602

### Changelog Description

Handles tool crashes from `FileSystemException` being thrown by `flutter doctor` when `flutter config --android-studio-dir` is set to an invalid file path (e.g. `"C:\my\path\has\quotes\in\it"`). Users instead get an informative message.

### Impacted Users

all Flutter devs

### Impact Description

`flutter doctor` crashes when users manually set their Android Studio location to a malformed path `flutter config --android-studio-dir`. This may be especially confusing for users who set their config dir far in the past and have just recently ran `flutter doctor` and encountered this crash.

### Workaround

The user can inspect the crash message and eventually deduce that the path they have configured is incorrect. They can then unset or update it. For example, `flutter config --android-studio-dir="fixed/path/here"`.

### Risk

low

### Test Coverage

yes

**Comment by itsjustkevin** [comment]
@christopherfujino could you take a look at this cherry-pick?

**Comment by XilaiZhang** [comment]
umm looks like this issue doesn't have the cp:apporved label and the tests are failing in the CP PR. Will drop this one for this week's release

**Comment by XilaiZhang** [comment]
looks like we should cp https://github.com/flutter/flutter/pull/133575 to release branches, will do this now

**Comment by christopherfujino** [comment]
> looks like we should cp #133575 to release branches, will do this now

thanks!
