### ISSUE TITLE
[engine] There are at least 5+ implementations of Paint, which is ... pain-t-ful

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#133698]
![ba-dum-tsss-drum](https://github.com/flutter/flutter/assets/168174/bd02f45c-6100-410a-8f2d-ce308a869fb7)

In https://github.com/flutter/engine/pull/44705, I'm flipping the default of `Paint.enableDithering`:

```diff
-static bool enableDithering = false;
+static bool enableDithering = true;
```

I'm getting held up though, because it turns out that there are really at least 5 implementations of `Paint`:

1. [`lib/ui/painting.dart`](https://github.com/flutter/engine/blob/5478052c2a54096384ad30897e05c993091da9e4/lib/ui/painting.dart#L1091)
1. [`lib/web_ui/lib/painting.dart`](https://github.com/flutter/engine/blob/591bf9f64bc69a5fab6efea3d88937b8a17c4a9f/lib/web_ui/lib/painting.dart#L218)
1. [`lib/web_ui/lib/src/engine/canvaskit/painting.dart`](https://github.com/flutter/engine/blob/7ffaec668db9dff1d9c5ebc166d7113d93b1b3d2/lib/web_ui/lib/src/engine/canvaskit/painting.dart#L24)
1. [`lib/web_ui/lib/sc/engine/html/painting.dart`](https://github.com/flutter/engine/blob/59a5563eacbf9d49effd4aa5d43996a41babd09f/lib/web_ui/lib/src/engine/html/painting.dart#L11)
1. [`lib/web_ui/lib/src/engine/skwasm/skwasm_impl/paint.dart`](https://github.com/flutter/engine/blob/f63fcf5a274ebb3761347ed73fbec00871cc7295/lib/web_ui/lib/src/engine/skwasm/skwasm_impl/paint.dart#L11)

For example, this is causing failures in the framework's [`flutter/test/painting/text_style_test.dart`](https://github.com/flutter/flutter/blob/1e770c3808e7a74fbef17a68f3dbd515f1d3c2a2/packages/flutter/test/painting/text_style_test.dart#L462):

```txt
03:18 +470 ~10 -1: test/painting/text_style_test.dart: backgroundColor [E]                                                                                                                             
  Expected: contains 'background: Paint(Color(0xff00ff00); dither: true)'
    Actual: 'TextStyle(color: unspecified, decoration: unspecified, decorationColor: unspecified, decorationStyle: unspecified, decorationThickness: unspecified, fontWeight: unspecified, fontStyle: unspecified, textBaseline: unspecified, fontFamily: unspecified, fontFamilyFallback: unspecified, fontSize: unspecified, letterSpacing: unspecified, wordSpacing: unspecified, height: unspecified, locale: unspecified, background: Paint(Color(0xff00ff00)), foreground: unspecified, shadows: unspecified, fontFeatures: unspecified, fontVariations: unspecified)'
     Which: does not contain 'background: Paint(Color(0xff00ff00); dither: true)'
  
  ../dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49      throw_
```

I'm going to work around this (as I don't think this is a terribly effective test) with a `if (kIsWeb)`, but we should figure out what the story is supposed to be here. If `Paint` shouldn't have any user-visible `toString()`, then let's remove it (and the tests that rely on it).

If it should, the implementations should agree - I shouldn't have to update 5 implementations IMO.

**Comment by eyebrowsoffire** [comment]
We should probably not be using `toString` as our way of checking the state of a `TextStyle` in the framework. The test that broke does not appear to do anything except actually test the functionality of `TextStyle.toString` or `Paint.toString`, which is not the framework's responsibility.

**Comment by yjbanov** [comment]
`lib/web_ui/lib/painting.dart` is not an implementation. It is the interface that all other web implementations implement.

**Comment by yjbanov** [comment]
It's unclear what we want to do about it. Long-term we will do our best to reduce the number of renderers on the web, that should help, but this issue does not help us get there. We can also stop using toString in tests (and probably also `runtimeType`, which is a leaky abstraction in Dart).

If there are no concrete steps we can take, I suggest we close this issue.
