### ISSUE TITLE
GestureDetector blocking when inside a Stack

### ISSUE THREAD

**Issue by eladmaimoni** [flutter/flutter#133673]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

This is a duplicate of a duplicate of a duplicate:

https://github.com/flutter/flutter/issues/32492

yet this is not a duplicate since it is still an issue.

GestureDestector is blocking detection on any widget that are behind it on a Stack, even when behavior: HitTestBehavior.translucent is set!

This is really problematic, mostly when you want to use a GestreDetector to figure out when a user taps outside a specific widget.

### Expected results

When GestureDetector behavior is set to transluscent, elements behind it on the Stack will receive events.

### Actual results

when GestureDetector behavior is set to transluscent, elements behind it does not receive events.

### Code sample
```
class RandomTest extends StatelessWidget {
 
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Stack(
          children: <Widget>[
            Positioned.fill(
              child: RaisedButton(
                child: Text("THIS CAN'T BE CLICKED"),
                onPressed: () {
                  print("The button got clicked");
                },
              ),
            ),
            Positioned.fill(
              child: GestureDetector(
                behavior: HitTestBehavior.translucent,
                onTap: () {
                  print("The GestureDetector got clicked");
                },
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```
### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.12.0-11.0.pre.11, on Microsoft Windows [Version 10.0.19045.3324], locale en-IL)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.2)
[!] Android Studio (not installed)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 3 categories.

**Comment by darshankawar** [comment]
Thanks for the report @eladmaimoni 
I verified the code sample on Pixel 6 emulator using latest master version and it works as expected. The print statement is triggered in the console as expected, as shown below:


https://github.com/flutter/flutter/assets/67046386/74dc46b4-4cb5-4828-b951-4672b44c969f

I verified on `Channel master, 3.14.0-13.0.pre.27`. 
You seem to be on older version of the master. Please upgrade to see it working properly.

Closing, as this works as expected. If you disagree, write in comments and I'll reopen it.
