### ISSUE TITLE
Platform.localeName always returns 'en_US'

### ISSUE THREAD

**Issue by zzzev** [flutter/flutter#13363]
## Steps to Reproduce

1. Start an android emulator
2. Change the locale (Settings > Languages & input > Languages, then either add a non-english one or sort a non-English one to the top of the list).
3. Start a flutter app that includes the line `print(Platform.localeName);`, note that the output is always 'en_US'

## Expected behavior
`Platform.localeName` should return the locale string that is associated with the language at the top of the list in the settings app.

A `MaterialApp`'s `localizationsDelegate` does (eventually) load the correct locale, so it is available there, but there shouldn't be a discrepancy between the values (even at this later point, where the `localizationsDelegate` is passed the correct locale, `Platform.localeName` still returns 'en_US').

**Comment by eseidelGoogle** [comment]
Is this a Dart library bug then?

**Comment by zzzev** [comment]
Sorry, you're right that's probably the right place; I'll close this in favor of this existing issue which is related: https://github.com/dart-lang/sdk/issues/29211

**Comment by Hixie** [comment]
Flutter uses `window.locale` and `window.onLocaleChanged` (from `dart:ui`).
We'll eventually be adding `window.locales` as well (to get the user's whole list).
I guess it would make sense to have `Platform.localeName` match `window.locale`'s `toString()` output. Does Dart allow us to configure that from the engine?

**Comment by eseidelGoogle** [comment]
@zanderso might know.

**Comment by zanderso** [comment]
There is currently no callback that the engine can set up to control the result of `Platform.localeName`, but it shouldn't be too much work to add one.  I'll updated https://github.com/dart-lang/sdk/issues/29211 and use it to track.

**Comment by zanderso** [comment]
The above fix should be live.
