### ISSUE TITLE
SocketException: Failed host lookup: 'mydomain.com' (OS Error: No address associated with hostname, errno = 7)

### ISSUE THREAD

**Issue by xOldeVx** [flutter/flutter#133686]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I'm using `http` library, after upgrade to Flutter 3.13.1 i'm getting exception `SocketException: Failed host lookup: 'mydomain.com' (OS Error: No address associated with hostname, errno = 7)`.

I searched a lot about this bug, all of the solutions doesn't work, like add Internet permission to Manifest, or disable the "Break on all exceptions" from the debugger etc.. it's still throw the error.

At the bottom line i didn't find a solution to this exception (which is really disturbing!), and nothing changed in my code except from the fact that I upgraded to Flutter 3.

### Expected results

Not exception

### Actual results

SocketException

### Code sample

<details><summary>Code sample</summary>

```dart
    final http.Response result = await http.get("https://......");
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.13.1, on macOS 13.3.1 22E772610a darwin-arm64
    (Rosetta), locale en-IL)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.81.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@xOldeVx 
You are most probably hitting https://github.com/dart-lang/sdk/issues/53331 and related https://github.com/dart-lang/sdk/issues/53334 so please follow-up in the linked issues / repos for further resolution.
Closing from here, as this isn't a bug in flutter sdk.
