### ISSUE TITLE
`TextWidthBasis.longestLine` prevents text from unwrapping when width constraints increase

### ISSUE THREAD

**Issue by necropolina** [flutter/flutter#133687]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Providing `textWidthBasis: TextWidthBasis.longestLine` to a `Text` widget ensures that the widget's width will fit the width of its text when the text is wrapped, rather than filling leftover width in the parent. However, if the inherited width constraint increases (eg, if its parent's width increases), `TextWidthBasis.longestLine` prevents the text from unwrapping even though the text no longer exceeds its width constraint.

This can be especially noticeable for mobile device when switching the device orientation from portrait to landscape. Text that needed to wrap in portrait mode remains wrapped in landscape even with significantly more available width and significantly less available height.

### Proposal

If this is an unintended consequence of `TextWidthBasis.longestLine`, then maybe it requires a bugfix. Otherwise, it would be great if we had a third option - something like `TextWidthBasis.expandingLongestLine` - that constraints the width of the `Text` widget to the longest line but still determines line wrapping from the width constraint inherited by the parent.

**Comment by danagbemava-nc** [comment]
Hi @necropolina, can you provide a complete minimal reproducible code sample that reproduces the issue you're experiencing? Please also provide the version of flutter that you experience this issue with. If you could share any screenshots/videos, that would also be appreciated. 

Thank you
