### ISSUE TITLE
Let PageView have a non-gesture-swipable toggle

### ISSUE THREAD

**Issue by xster** [flutter/flutter#13369]

**Comment by yohom** [comment]
I need this feature. Is there any update? @xster

**Comment by yohom** [comment]
I use `NeverScrollableScrollPhysics` reached this effect.

**Comment by iapicca** [comment]
Hi @xster  is this issue still meant to be open?

**Comment by xster** [comment]
Yes, this should be still valid.

**Comment by goderbauer** [comment]
@Piinks

**Comment by Piinks** [comment]
De-duping this with https://github.com/flutter/flutter/issues/65520 as it describes some specific use cases and has another workaround. NeverScrollableScrollPhysics is how I would approach this though as mentioned here: https://github.com/flutter/flutter/issues/13369#issuecomment-409794645
