### ISSUE TITLE
Engine->Flutter autoroller blocked after dart roll

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#133677]
First example of roll failure: https://github.com/flutter/flutter/pull/133624
dart roll: https://github.com/flutter/engine/pull/45262
dart commits in roll: https://dart.googlesource.com/sdk.git/+log/0cea73a8d3c3..96d3a79547fc

I looked through the commit messages and nothing immediately jumped out at me.

## error log
```
11:14 +4: test/integration.shard/break_on_framework_exceptions_test.dart: breaks when platform message callback throws                                                                                 
11:14 +4 -1: test/integration.shard/break_on_framework_exceptions_test.dart: breaks when platform message callback throws [E]                                                                          
  Timed out waiting for VM service pause debug event
  package:matcher                                                        fail
  test/integration.shard/break_on_framework_exceptions_test.dart 623:11  _timeoutAfter.<fn>
  
55s            Spawning flutter [test, --disable-service-auth-codes, --machine, --start-paused, test/test.dart] in /Volumes/Work/s/w/ir/x/t/flutter_break_on_framework_exceptions.dl81v8

56s <=stdout=  {"protocolVersion":"0.1.1","runnerVersion":null,"pid":92785,"type":"start","time":0}

<=stdout=  {"suite":{"id":0,"platform":"vm","path":"/Volumes/Work/s/w/ir/x/t/flutter_break_on_framework_exceptions.dl81v8/test/test.dart"},"type":"suite","time":0}

<=stdout=  {"test":{"id":1,"name":"loading /Volumes/Work/s/w/ir/x/t/flutter_break_on_framework_exceptions.dl81v8/test/test.dart","suiteID":0,"groupIDs":[],"metadata":{"skip":false,"skipReason":null},"line":null,"column":null,"url":null},"type":"testStart","time":1}

66s <=stdout=

<=stdout=  [{"event":"test.startedProcess","params":{"vmServiceUri":"[http://127.0.0.1:52961/","observatoryUri":"http://127.0.0.1:52961](http://127.0.0.1:52961/%22,%22observatoryUri%22:%22http://127.0.0.1:52961)/"}}]

OK (test.startedProcess event)
```

**Comment by whesse** [comment]
That commit is a fix for https://github.com/dart-lang/sdk/issues/53334 which is copied from Flutter https://github.com/flutter/flutter/issues/129121. https://github.com/dart-lang/sdk/issues/47985 may also be related.

**Comment by mraleph** [comment]
I would think that the test is wrong somewhere - it expects this exception to be unhandled but somewhere in the chain of futures there is a future with `onError` attached to it, which was previously invisible to the debugger, but now is visible.

**Comment by gaaclarke** [comment]
attn @goderbauer who is the author of the test ( https://github.com/flutter/flutter/blame/main/packages/flutter_tools/test/integration.shard/break_on_framework_exceptions_test.dart#L123 )

@goderbauer, it appears the test is asserting that platform channel handlers that throw cause the debugger to pause, but that is no longer happening because the behavior of the debugger has been changed in a way that is more correct.  Specifically, it was reporting exception as "uncaught" erroneously when an `Future.then(onError:)` was specified.

Our options are:
1) Hunt down and remove the `onError` that is catching the exception being thrown in the channel handler.  This will cause the debugger to pause again, but potentially the error that happens will be less informative / less helpful when the debugger is not attached.  This could turn a warning message to a crash, no?
1) Delete the test, removing our assertion that this causes the debugger to pause.  I imagine there is a workaround for users, they can manually add a breakpoint or add a breakpoint on `throw`?

**Comment by mraleph** [comment]
On the second thought it *might* be a bug in the change as well. I did not account for Zones. I can check a bit later today or you should feel free to revert.

**Comment by a-siva** [comment]
revert of above CL has landed, closing issue.
