### ISSUE TITLE
'pub run' with flutter tool requires redundant 'pub' on the command line

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#13360]
@franzsilva wrote a cool tool for managing launcher icons, and packaged it as a pub package. Apparently, using the flutter tool, a user can't run the script without typing "pub" twice.

For example: `flutter pub pub run flutter_launcher_icons:main`

We're wondering if the following could work instead: `flutter pub run flutter_launcher_icons:main`

Comment: https://github.com/franzsilva/flutter_launcher_icons/issues/4#issuecomment-349454015

**Comment by sethladd** [comment]
cc @mit-mit @devoncarew

**Comment by Hixie** [comment]
It's actually `flutter packages pub run flutter_launcher_icons:main`.

What's going on is that `flutter packages` sets the environment for pub, then there's a bunch of commands that `flutter packages` supports (see `flutter packages --help`). One of those is `pub`; what that does is call through to pub and hand it the rest of the command line. The other commands are shortcuts to common things you do with `pub`, though they don't support all the features of `pub`. Namely, `get` and `upgrade` run `pub get` and `pub upgrade`, and `test` runs `pub run test`.

**Comment by mit-mit** [comment]
We are starting to see a few of these. I think we should reconsider this more globally as originally suggested in https://github.com/flutter/flutter/issues/9799

**Comment by sethladd** [comment]
We want to give our developers a way to extend their workflow with scripts distributed as pub packages. Then, we want to give them a clear way to run those scripts. So, +1 to making it a bit more discoverable and terse to run a workflow script :)

Thanks!

**Comment by MarkOSullivan94** [comment]
@sethladd any update on this?

**Comment by mit-mit** [comment]
No  updates, sorry. For now, please use `flutter packages pub run <dart file>`

**Comment by matanlurey** [comment]
On the mailing list I suggested `flutter script` as a shorthand:

`flutter script <pub package or command-line file.dart>`

```bash
$ flutter script some_package
$ flutter script some_package:some_executable
$ flutter script tool/some_dart_file.dart
```

We could combine this with `build_runner`'s support for code generation quite easily:

https://github.com/dart-lang/build/issues/733

**Comment by mit-mit** [comment]
@matanlurey how would we determine if we should run the argument with the dart vm or through `pub run`? If there is a `pubspec.yaml` in the same dir or in the parent dir, then use `pub run` otherwise use the vm?

**Comment by matanlurey** [comment]
@mit-mit:

> How would we determine if we should run the argument with the dart vm or through pub run? 

One option would be, if the argument represents a path on disk (i.e. `tool/file.dart`), or you could even say, ends in the string `'.dart'`, use the Dart VM, otherwise use `pub run`. It's probably safe to _always_ use `pub run`, though, because I think it works anyway.

**Comment by sethladd** [comment]
Curious, why would we *need* to use `pub run` ? What does that buy us, over the CLI engine?

**Comment by matanlurey** [comment]
@sethladd: You don't need to, it just allows packages to define shortcuts like `pub run test`

Imagine:

`flutter script optimize-pngs` versus
`flutter script flutter_image_optimizer:optimize-pngs` versus
`flutter script /some/cache/dir/packages/flutter_image_optimizer/bin/optimize_pngs.dart`

**Comment by MarkOSullivan94** [comment]
@mit-mit just looking at the merged PR does this mean that the following will now work 

`flutter packages run flutter_launcher_icons:main`

**Comment by mit-mit** [comment]
It should; please give it a try, and let us know if not. Generally any `pub x` command should now be available as `flutter pub x`
