### ISSUE TITLE
ImpellerValidationBreak

### ISSUE THREAD

**Issue by vfthome** [flutter/flutter#133725]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create custom icon from svg on FlutterIcon website.
2. Import TTF and assets, also the dart custom font class for accessing the icons.
3. Use a FittedBox with child Icon and set Fit parameter to BoxFit.fill
4. Boom, impeller error. Didn't got it with default flutter Icons class tho.

### Expected results

Load login screen normally and display svg.
The svg would be distorted but 

### Actual results

The screen didn't loaded, after using navigator.pushReplacementNamed('/login');

The error was given when I tried to use an SVG imported into flutter as an custom font TTF.
I converted the SVG to an Icon with Flutter Icon website.
Imported it into flutter, tried to used it and got the error.

The error probably is related to BoxFit.fill on Fit parameter of Flutter FittedBox widget.
Just wanted to share because could have something useful because I got an impeller error, not usual framework related errors..

### Code sample

<details><summary>Code sample</summary>

```dart

Stack(
      children: [
        Align(
          alignment: Alignment(0, 0),
          child: Container(
            color: Colors.white10,
            width: 493.91,
            height: 40.81,
            child: const FittedBox(
              fit: BoxFit.fill,
              child: Icon(
                NavalcareConnectIcons.waves_triple,
                color: corNiloBragaIconeAtivo,
              ),
            ),
          ),
        ),
      ],
    );

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

<img width="1271" alt="image" src="https://github.com/flutter/flutter/assets/103903008/221c9481-929f-4afa-bfdb-c4005bbfbb8d">

</details>

### Logs

<details><summary>Logs</summary>

```console

Reloaded 9 of 1820 libraries in 627ms (compile: 38 ms, reload: 92 ms, reassemble: 479 ms).
[VERBOSE-2:validation.cc(49)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not create valid atlas.
[VERBOSE-2:validation.cc(49)] Break on 'ImpellerValidationBreak' to inspect point of failure: Cannot render glyphs without prepared atlas.
[VERBOSE-2:validation.cc(49)] Break on 'ImpellerValidationBreak' to inspect point of failure: Failed to render entity.

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console

flutter doctor -v

[✓] Flutter (Channel stable, 3.13.1, on macOS 13.5.1 22G90 darwin-arm64, locale pt-BR)
    • Flutter version 3.13.1 on channel stable at /Users/vfthome/Documents/Desenvolvimento/Frameworks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e1e47221e8 (8 days ago), 2023-08-22 21:43:18 -0700
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/vfthome/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • iPhone 13 mini (mobile) • AA0C559A-CB0A-4415-B00B-F271BA3D1F70 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0
      (simulator)
    • macOS (desktop)         • macos                                • darwin-arm64   • macOS 13.5.1 22G90 darwin-arm64
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 115.0.5790.170

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @vfthome 
Can you provide us the custom font that we can directly use ?
Also, an issue related to `ImpellerValidationBreak` was fixed recently 
https://github.com/flutter/flutter/issues/131012
Can you try switching to latest master and run your scenario again to check if the error still persists or not ?

`flutter channel master`
`flutter upgrade --force`

**Comment by vfthome** [comment]
Yes, sorry for the delay in my answer.
https://drive.google.com/drive/folders/1zIvHVkCMt1vs2NNegDnq0WXuk1AEutbF?usp=share_link

**Comment by vfthome** [comment]
This is my first time filling an issue as well! =)

Actually found another bug with CustomScrollView and SliverGrid with Fitted Box widget wrapping a Text. Very weird one as well, the app does not gives a RED screen but the layout glitches and when I use String interpolation with the text like '$parameter ' the glitch simply does not happen.

**Comment by vfthome** [comment]
FittedBox + CustomScrollView #134704

**Comment by huycozy** [comment]
@vfthome Could you confirm this issue has been fixed on the latest master channel as Darshan mentioned above? If not so, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. 

If your new issue https://github.com/flutter/flutter/issues/134704 is a similar one, feel free to close this and follow up on that issue for updates. Thanks!
