### ISSUE TITLE
FloatingActionButtonVisibilityValue not change when showBottomSheet Calling

### ISSUE THREAD

**Issue by allou-deyforyou** [flutter/flutter#133723]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. use showBottomSheet and DraggableScrollableSheet
2. set FloatingActionButton in Scaffold

### Expected results

- When using showBottomSheet and DraggableScrollableSheet, FloatingActionButton Visibility change. 

### Actual results

Currently FloatingActionButton Visibility not change and BodyScrim not also change.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: true),
      home: const ExampleScreen(),
    );
  }
}

class ExampleScreen extends StatefulWidget {
  const ExampleScreen({super.key});

  @override
  State<ExampleScreen> createState() => _ExampleScreenState();
}

class _ExampleScreenState extends State<ExampleScreen> {
  final _scaffolKey = GlobalKey<ScaffoldState>();

  void _showHomeDraggableScrollableSheet() {
    _scaffolKey.currentState!.showBottomSheet(
      clipBehavior: Clip.antiAlias,
      (context) {
        return DraggableScrollableSheet(
          snap: true,
          expand: false,
          minChildSize: 0.0,
          maxChildSize: 0.9,
          initialChildSize: 0.9,
          snapSizes: const [0.0, 0.9],
          builder: (context, scrollController) {
            return Scaffold(
              body: CustomScrollView(
                controller: scrollController,
              ),
            );
          },
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      key: _scaffolKey,
      appBar: AppBar(title: const Text("Example")),
      floatingActionButton: FloatingActionButton(
        onPressed: _showHomeDraggableScrollableSheet,
        child: const Text("Open"),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
octor summary (to see all details, run
flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.2, on
    macOS 13.5.1 22G90 darwin-x64,
    locale fr-CI)
[✓] Android toolchain - develop for
    Android devices (Android SDK
    version 33.0.2)
[✓] Xcode - develop for iOS and macOS
    (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.81.1)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @allou-deyforyou, the code sample that you have provided is not complete. Please provide a complete minimal reproducible code sample along with detailed steps to reproduce so that we can investigate this issue. Please also provide any screenshots/recordings that capture the issue. 

Thank youj

**Comment by allou-deyforyou** [comment]
Hi @danagbemava-nc, I just modified the code. You can try.

Thank you

**Comment by danagbemava-nc** [comment]
Hi, @allou-deyforyou, your description of the issue is quite vague. Please provide a detailed description of the issue. Screenshots/recordings will help in this case. 

If you could also share anything that supports your expected case, that would be helpful. 

Thank you
