### ISSUE TITLE
I really want to konw   ,flutter will have about dynamic update mechanism later?  Just like React-Native use to download jsbundle similar patch package to dynamically update the app and do not send a new version？   

### ISSUE THREAD

**Issue by glndex** [flutter/flutter#13378]
## Steps to Reproduce

Please tell us what you were doing and what went wrong. If you are running flutter tools from the command line, please try adding the `-v` or `--verbose` option to gather more information.

If the problem is with your application's rendering, please attach a screenshot and any relevant source code.
If you are getting an exception in the logs, and your code is implicated in the first few frames, then please include the source code for the functions involved.

## Logs

Run your application with `flutter run` and attach all the log output.

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor

Paste the output of running `flutter doctor` here.

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by itsJoKr** [comment]
AFAIK you can use "hot reload" to quickly push changes in your app only in development. The production version works very differently (Ahead-Of-Time compiling).

**Comment by mit-mit** [comment]
@glndex can you clarify, please: Are you asking a question, or raising a feature request. If the latter, can you please update the description with some details about the request (use cases for it, how you would use it, importance, etc.)?

**Comment by eseidelGoogle** [comment]
Tracking as https://github.com/flutter/flutter/issues/14330
