### ISSUE TITLE
Android Studio is found twice because of a symlink that is not detected as such

### ISSUE THREAD

**Issue by mfonville** [flutter/flutter#133758]
I have a popular deb-package for Android Studio on Ubuntu : https://launchpad.net/~maarten-fonville/+archive/ubuntu/android-studio

To allow user to install both development and stable versions next to each other on the same system, and to prevent possible installation files issues/clashes when upgrading to a newer version, a major version is put in each own directory, e.g.: `/opt/android-studio-2022.3.1/android-studio`
and for the then current stable android studio version, a symlink is made from `/opt/android-studio` to such subdirectory.

Because of this set-up, flutter erroneously does find two installs of Android Studio:
```
[✓] Android Studio (version 2022.3)
    • Android Studio at /opt/android-studio-2022.3.1/android-studio
    • Flutter plugin version 75.1.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[!] Android Studio (version unknown)
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
```

This is because `/opt/android-studio` is assumed to be one of the default paths (https://github.com/flutter/flutter/blob/5e16d2ca757fe26c4b728782cec23ec9b17394b3/packages/flutter_tools/lib/src/android/android_studio.dart#L479 ) but it only checks if it is a directory, but it doesn't check if it is a symlink.

An easy solution would be to add in this method a check that only compares the specified path, but also compares the absolute path to detect potential double entries:
https://github.com/flutter/flutter/blob/9e9aa810bec31cc7a0cded6ad014e85a99543405/packages/flutter_tools/lib/src/android/android_studio.dart#L367

**Comment by darshankawar** [comment]
Thanks for the report. This looks similar to https://github.com/flutter/flutter/issues/56995, so please follow-up in it for further updates.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.

**Comment by mfonville** [comment]
Hi, thank you for checking with the possible duplicate.
The other issue was really an (old) bug and Windows-related. And very probably already solved actually.
My issue is Linux-specific and more of a suggested enhancement. 

I would make a PR, but I haven't every done development in Dart myself, so that is why I thought it would be best to just point to the line where I think the logic could be enhanced. The only thing that woud be necessary is to also check absolute paths, to catch (symlinked) duplicate locations when filtering.

**Comment by darshankawar** [comment]
Thanks for the feedback. Reopening.

**Comment by darshankawar** [comment]
Most probably [this](https://github.com/flutter/flutter/issues/17746) issue then ? @mfonville

**Comment by mfonville** [comment]
Yes, that issue describes the same problem :-)

**Comment by darshankawar** [comment]
Closing as duplicate.
