### ISSUE TITLE
DynamicLibrary.open() fails to find/load system native dependencies of a FFI library 

### ISSUE THREAD

**Issue by kubaraczkowski** [flutter/flutter#133768]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

We build an Android app that includes: a component in Go (via the `CGO_ENABLED=1 go build -buildmode=c-shared`), which on itself includes a shared C library that depends on libOpenCL.so - we get into troubles.

our go library has the following dependencies:
- libopencv_flann.so - opencv
- libopencv_features2d.so - opencv
- liblog.so - standard go dependency
- libdpapi_identity.so - ours library, depending on libOpenCL, etc
- libdl.so - standard
- libc.so - standard

We copied all the necessary libraries such that they get deployed to $APP/lib/arm64 directory

### Expected results

When running `DynamicLibrary.open("libgrpcevk.so")` it should load our Go library including the system (native) dependencies.

### Actual results

At runtime we fail at `DynamicLibrary.open()` which fails to locate any system native libraries. 
Really, any system native libraries... It didn't find either `libcutils.so` or `libvndksupport.so`, even `libc.so`.

```
final DynamicLibrary _dep = DynamicLibrary.open("libvndksupport.so");
final DynamicLibrary _dep2 = DynamicLibrary.open("libcutils.so");
final DynamicLibrary _dep3 = DynamicLibrary.open("libOpenCL.so");

final DynamicLibrary DynamicLibrary.open("libgrpcevk.so") 
DynamicLibrary.process();
```

```
ArgumentError (Invalid argument(s): Failed to load dynamic library 'libgrpcevk.so': 
dlopen failed: library "libOpenCL.so" not found: needed by 
/data/app/~~x2VJ3eZtxnvo3raiNH2BDw==/com.example.evk34_liveview-IFOoSCI2JkMN-NcYx2cnZg==/lib/arm64/libdpapi_identity.so 
in namespace classloader-namespace)
```

Interestingly, in the example above, the direct loads of e.g. `DynamicLibrary.open("libcutils.so")` etc passes OK, but fails if it's a dependency of "our library".

We tried copying all of the system dependencies into the app, this goes further, but then any calls to the OpenCL fail with a SIGTRAP on `__loader_dlopen` of `ld-android.so`, perhaps because it's all simply in a wrong place?

We also tried the Go library without the second dependency (breaking the OpenCL dependency) - that works perfectly fine. 

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/flutter/flutter/assets/554652/9428c688-98f9-4782-ab2c-ae2546192d45)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.1, on Ubuntu 22.04.3 LTS 5.19.0-50-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 2 categories.```

</details>

**Comment by darshankawar** [comment]
Thanks for the report. I don't have much insights on the reported behavior, so keeping this issue open and labeling for team's input / attention.

**Comment by dcharkes** [comment]
Lets try to dissect the problem. Does the fact that Go is used influence this? e.g. if you write a small C library that uses the dynamic linker to access the same libraries, does that work? E.g. is it Go dynamic linking or C dynamic linking that is the issue here?

> Interestingly, in the example above, the direct loads of e.g. `DynamicLibrary.open("libcutils.so")` etc passes OK, but fails if it's a dependency of "our library".

The dynamic loader of C/C++ uses a different lookup path than the Dart VM when looking up libraries. As a workaround you can `DynamicLibrary.open` the dependencies first, then the C dynamic linker will use the already opened dynamic libraries.

The better solution would probably be play around with `-rpath` or `--library-path` and other related dynamic loading configuration flags/options. This will likely require quite some digging. You can start exploring with `objdump` and `readelf` to see what the rpath/runpath is.

> We tried copying all of the system dependencies into the app, this goes further, but then any calls to the OpenCL fail with a SIGTRAP on `__loader_dlopen` of `ld-android.so`, perhaps because it's all simply in a wrong place?

This sounds a bit like a smell, those libraries should be on an Android phone already right?

If you're copying you get all kinds of questions such as: Did you make sure to then also copy the dependencies of those dependencies? What are the versions of those libraries? Are these versions compatible with what is already on the phone?

Probably step 1 is to make the problem smaller: Only use C, have dynamic libraries have dependencies that are being loaded by the dynamic linker at runtime, and don't use the `DynamicLibrary.open` pre-loading of dependencies. If that doesn't work investigate the loading path, run path, of these libraries.

**Comment by kubaraczkowski** [comment]
Thanks for your help @dcharkes.

Indeed, what we did is narrow down the problem as much as possible, just like you suggested. We tried all the steps you proposed, including hardcoding `rpath` to no avail.

In the end we got to a very simple problem, most probably linked to `libOpenCL.so` or other libs located in `/vendor/lib64`. 
We tried simply loading this library straight from Dart and calling the simplest function possible (`clGetPlatformIDs()`). Even that failed :/ 

- trying to load `DynamicLibrary.open("libOpenCL.so")` passes, but any function call fails saying the lib cannot be found
- trying to manually spec the library path `DynamicLibrary.open("/vendor/lib64/libOpenCL.so")` fails immediately saying that 

```
ArgumentError (Invalid argument(s): Failed to load dynamic library '/vendor/lib64/libOpenCL. so':
 dlopen fatled: library "/vendor/lib64/libOpen(L.so" needed or dlopened by "/data/app/~~W16ZnvPLawQjH6P2_fr500--/com.example.evk34_liveview-XAGhamCbdlnai7daGcDpbA=-/lib/arm64/libflutter.so"
 is not accessible for the namespace "classloader-namespace")
```

Googling around it seems like a potential permission problem, something perhaps with "public libraries" (see [stackoverflow](https://stackoverflow.com/questions/59608865/library-is-not-accessible-for-the-namespace-classloader-namespace) ), however `libOpenCL.so` is marked as public in `/vendor` ... 

At the same time, OpenCL-Z [googleplay](https://play.google.com/store/apps/details?id=com.robertwgh.opencl_z_android&hl=en_US) succeeds in reporting the GPU parameters and performance numbrers, which suggests there is at least a way around any permission issue.

At the same time we've verified that running any 'our' libs, shipped together with the app, works as expected. Also e.g. calling functions from `/system/libGLESv3.so` goes through. 

Any pointers appreciated!

**Comment by dcharkes** [comment]
> * trying to load `DynamicLibrary.open("libOpenCL.so")` passes, but any function call fails saying the lib cannot be found

That's quite weird. `DynamicLibrary.open` does a `dlopen` on Android. How can it fail on a `dlsym` (the `lookup` in Dart) with that a library is not found. What error message does it give?

> Googling around it seems like a potential permission problem, something perhaps with "public libraries" (see [stackoverflow](https://stackoverflow.com/questions/59608865/library-is-not-accessible-for-the-namespace-classloader-namespace) ), however libOpenCL.so is marked as public in /vendor ...

Unfortunately, I'm not an expert on this. Maybe someone from the Flutter Android team is more knowledgable on using system libraries. cc @mossmana @gmackall

**Comment by dcharkes** [comment]
> If you're copying you get all kinds of questions such as: Did you make sure to then also copy the dependencies of those dependencies? What are the versions of those libraries? Are these versions compatible with what is already on the phone?

Maybe copying would be the right thing, because there's no guarantee of version compatibility between your C code and the version of the system libraries on the phone. If you include all dependencies transitively, at least the versioning should work out.

**Comment by gaaclarke** [comment]
I have more experience with mach-o operating systems but in the past when I ran into this it was one of these problems:
1) The dynamic library is not the architecture of the target platform -- You can verify that with the `file` command in linux.  This is probably not the case if you can load them individually.
1) The transitive dependencies are not in a location that dyld can locate -- Where dyld looks for those dependencies is dictated by environment variables (like `LD_LIBRARY_PATH`) and the elf file itself.  You can see the transitive dependencies by the using the `ldd` command on the dynamic library.  Looks like they can be edited with `patchelf` if they are not correct.  I'd make sure they are all relative.

> Googling around it seems like a potential permission problem, something perhaps with "public libraries"

Are you talking about the visibility of the symbols you are trying to load?  You can verify that with the `nm` command.

**Comment by kubaraczkowski** [comment]
Hi @gaaclarke, thanks for helping out.
The trouble is that on the "linux level" everything works just fine - ldd, `LD_LIBRARY_PATH` and all is working as expected. I can run a binary version of the main go program no problem. On the "android app level", however, nope!

However, after working on minimal examples today, there was a breakthrough. It's hard to believe, so I need to retest and document properly, but here's the spoiler. The test is running the simple 'counter example' flutter app with added a simple `libOpenCL.so` call.

- compilation on MacOS - no problem! everything works as expected
- compilation on Linux via docker (https://hub.docker.com/r/instrumentisto/flutter) - can't find the libs no matter what

The version of Flutter SDK (3.13.2) and Android SDK (tried build tools 34.0.x and 33.0.x), are the same, code is the same, `flutter doctor -v` is almost the same in both cases except the compiler itself (Xcode's clang vs. Ubuntu clang).

I'll publish the MWE tomorrow to help find that difference...

**Comment by camsim99** [comment]
cc @reidbaker to be subscribed

**Comment by chinmaygarde** [comment]
The engine just delegates to dlopen and I am not sure what else if the system cannot find the library (due to permissions or otherwise). Keeping this open for a bit for an update but will close if there isn't anything actionable.

**Comment by kubaraczkowski** [comment]
Thanks, sorry for the delay I’ll try to finish the example tomorrow

**Comment by kubaraczkowski** [comment]
OK, it seems we've been chasing ghost.
I made minimal working example, it didn't reproduce the error, we rebuilt everything from scratch - no errors :/

Please close this issue, and great thanks to all for support!
