### ISSUE TITLE
[flutter_tools] `list` subcommand

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter#133732]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

As previously discussed in https://github.com/flutter/flutter/issues/81831, we might consider a cleaner command design for the `config` tool.

### Proposal

- Use the `list` command to display configured settings.
- Still displays usage when `flutter config` only.

**Comment by christopherfujino** [comment]
Sounds good to me

**Comment by AlexV525** [comment]
Sub-command has design incompatibility which is intended, so the proposal will be revert to #81831.
