### ISSUE TITLE
[flutter_lints] Proposal - Show error before runtime when using color param AND decoration param at the same time

### ISSUE THREAD

**Issue by Fernandomr88** [flutter/flutter#133760]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Coming from https://github.com/flutter/flutter/issues/133456

Whenever you're implementing a `Container` for example and you use both `color` and `decoration` at the same time, there's no error shown but an exception is thrown only when the widget is built in runtime, not even on compilation.
Code example:
```dart
Container(
  height: 150,
  width: 150,
  color: Colors.white, ///<- color
  decoration: BoxDecoration(borderRadius: BorderRadius.circular(100), color: Colors.white), //<- color again
  child: Image.asset(
    'assets/img/X.gif',
    height: 100,
  ),
));
```

![image](https://github.com/flutter/flutter/assets/14304128/deefa638-e3f5-4a77-9428-f3fe2538a7be)

### Proposal

My proposal is that the error is shown on "coding time" rather than on runtime, just as any errors that are shown whenever Linter detects an issue or suggestion.

**Comment by stuartmorgan** [comment]
Please file requests for new lints at https://github.com/dart-lang/linter/issues

`flutter_lints` is just a utility to easily enable a specific set of existing lints, not an actual linter.

**Comment by Fernandomr88** [comment]
> https://github.com/dart-lang/linter/issues

my suggestion is not specific to dart but to a flutter widget, does it make sense to be at dart-lang?
