### ISSUE TITLE
Flutter Inspector doesn't open selected widget inside Text Editor

### ISSUE THREAD

**Issue by davor-layer-four** [flutter/flutter#133756]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

On latest Flutter version, when a project is opened inside Android Studio and Flutter Inspector is open, selecting a widget with the inspector doesn't open the Dart file inside the Text Editor where the widget is written. It just shows the selected widget inside the Widget Tree Hierarchy. 

Flutter - channel stable - 3.13.2
Android Studio Giraffe | 2022.3.1 Patch 1
Build #AI-223.8836.35.2231.10671973, built on August 17, 2023

### Expected results

Dart file containing the widget is open inside the text editor.

### Actual results

Nothing happens, the widget is selected inside the widget tree.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by dam-ease** [comment]
Hi @davor-layer-four. This doesn't seem like a flutter issue, issues with the flutter intellij plugin should be reported on their dedicated repo over on https://github.com/flutter/flutter-intellij.

Closing from here as the intellij plugin has its own repo.

Thank you
