### ISSUE TITLE
Builds running on dart-internal should have a longer timeout

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#133785]
Builds running on dart-internal should have a longer timeout. There is enough capacity to build a few commits concurrently but in cases where we have several commits or capacity is running low builds are timing out.

**Comment by XilaiZhang** [comment]
note: time out refers to queue time out

**Comment by godofredoc** [comment]
Fix: https://flutter-review.googlesource.com/c/recipes/+/50680
