### ISSUE TITLE
flutter upgrade gives unknown flutter tag and abandons even though reports stable channel

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/flutter#133764]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

neil.warner@NA-081MD6TMBP resident-app % flutter channel
Flutter channels:
  master (latest development branch, for contributors)
  main (latest development branch, follows master channel)
  beta (updated monthly, recommended for experienced users)
* stable (updated quarterly, for new users and for production app releases)
neil.warner@NA-081MD6TMBP resident-app % flutter channel stable
Switching to flutter channel 'stable'...

Upgrading engine...
Successfully switched to flutter channel 'stable'.
To ensure that you're on the latest build from this channel, run 'flutter upgrade'
neil.warner@NA-081MD6TMBP resident-app % flutter upgrade
Unknown flutter tag. Abandoning upgrade to avoid destroying local changes. It is recommended to use git directly if not working on an official channel.

### Expected results

Succesful upgrade since the star showed me on stable and there's a new stable. (flutter upgrade worked for 3.13 earlier this month)

### Actual results

Unknown flutter tag. Abandoning upgrade to avoid destroying local changes. It is recommended to use git directly if not working on an official channel.

### Code sample

na

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
neil.warner@NA-081MD6TMBP resident-app % flutter upgrade
Unknown flutter tag. Abandoning upgrade to avoid destroying local changes. It is recommended to use git directly if not working on an official channel.
neil.warner@NA-081MD6TMBP resident-app % 
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
neil.warner@NA-081MD6TMBP resident-app % flutter doctor -v
[✓] Flutter (Channel stable, 3.13.1, on macOS 13.5 22G74 darwin-x64, locale en-US)
    • Flutter version 3.13.1 on channel stable at /Users/neil.warner/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e1e47221e8 (8 days ago), 2023-08-22 21:43:18 -0700
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/neil.warner/Library/Android/sdk
    • Platform android-33, build-tools 34.0.0
    • Java binary at: /usr/local/opt/openjdk@11/bin/java
    • Java version OpenJDK Runtime Environment Homebrew (build 11.0.15+0)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.79.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • 44BB58CD-A324-4358-B700-015DC6313498 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 13.5 22G74 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 116.0.5845.140

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by dam-ease** [comment]
Hi @neiljaywarner. Thanks for filing this issue, there is a currently open issue describing this case https://github.com/flutter/flutter/issues/133441.
Closing this as a duplicate.
Thank you!
