### ISSUE TITLE
Multiple ScenariosUITests in engine fail with Xcode 15 in CI

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#133783]
Multiple ScenariosUITests fail when testing for `ios_debug_sim_arm64_extension_safe` with Xcode 15 in CI. Seems to happen consistently.

```
Failing tests:
	-[PlatformViewMutationClipRectTests testPlatformView]
	-[PlatformViewMutationClipRRectWithTransformTests testPlatformView]
	-[BogusFontTextTest testFontRenderingWhenSuppliedWithBogusFont]
	-[PlatformViewUITests testPlatformView]
	-[PlatformViewMutationClipRectAfterMovedTests testPlatformView]
	-[PlatformViewMutationLargeClipRRectTests testPlatformView]
	-[MultiplePlatformViewsBackgroundForegroundTest testPlatformView]
	-[TwoPlatformViewsWithOtherBackDropFilterTests testPlatformView]
	-[PlatformViewRotation testPlatformView]
	-[SpawnEngineTest testSpawnEngineWorks]
	-[PlatformViewMutationClipPathWithTransformTests testPlatformView]
	-[PlatformViewWithOtherBackdropFilterTests testPlatformView]
	-[PlatformViewMutationClipRectWithTransformTests testPlatformView]
	-[PlatformViewMutationOpacityTests testPlatformView]
	-[LocalizationInitializationTest testNoLocalePrepend]
	-[PlatformViewMutationClipPathTests testPlatformView]
	-[PlatformViewMutationLargeClipRRectWithTransformTests testPlatformView]
	-[TwoPlatformViewClipRRectTests testPlatformView]
	-[NonFullScreenFlutterViewPlatformViewUITests testPlatformView]
	-[PlatformViewWithNegativeOtherBackDropFilterTests testPlatformView]
	-[MultiplePlatformViewsTest testPlatformView]
	-[PlatformViewMutationTransformTests testPlatformView]
	-[TwoPlatformViewClipPathTests testPlatformView]
	-[TwoPlatformViewClipRectTests testPlatformView]
	-[PlatformViewMutationClipRRectTests testPlatformView]
```
https://chromium-swarm.appspot.com/task?id=6461768488479410
https://chromium-swarm.appspot.com/task?id=646528f8d744d410

Almost all of the tests error with 
```
GoldenTestManager.m:79: error: ... -[UIImage internalImage]: unrecognized selector sent to instance
```

expect for `-[LocalizationInitializationTest testNoLocalePrepend]` has this error
```
LocalizationInitializationTest.m:33: error: -[LocalizationInitializationTest testNoLocalePrepend] : (([textInputSemanticsObject waitForExistenceWithTimeout:timeout]) is true) failed
 ```

**Comment by cyanglaz** [comment]
Does it happen for ios_debug_sim_arm64?

**Comment by vashworth** [comment]
Unsure, it doesn't seem like the `ios_debug_sim_arm64` runs the same tests, here's an example of `Linux mac_unopt ios_debug_sim_arm64`: https://chromium-swarm.appspot.com/task?id=646528534341a410

**Comment by cyanglaz** [comment]
Ah It stopped at unit test so the scenario test has started yet for `ios_debug_sim_arm64`. I bet both targets will fail on the scenario tests.

**Comment by cyanglaz** [comment]
I'm unable to repro the golden test errors but was able to repro this one: 
`-[LocalizationInitializationTest testNoLocalePrepend]`

**Comment by cyanglaz** [comment]
Oh was the simulator changed to use iOS 17 in the scenario tests?
We need to use the same version of simulators or scenario tests won't pass. 

Although using the wrong simulator version should not produce the exact error in this issue. 

@vashworth to make the tests pass, we should keep the version to iOS 16.2 for scenario tests. We should then try to update the simulator to iOS 17 later (possibly around the time we bump to a stable XCode 15 version)

**Comment by cyanglaz** [comment]
And yes, I can reproduce the same crash `[UIImage internalImage]: unrecognized selector sent to instance` with iOS 17 simulators.

**Comment by cyanglaz** [comment]
The issue is that we are sending a UIImage type as parameter to `XCTAttachment attachmentWithScreenshot:`, which takes a `XCUIScreenshot` as parameter, this is not supposed to pass in old iOS versions. I'm not sure why it worked before but the fix is straightforward. I'm adding the fix to the https://github.com/flutter/engine/pull/45391
