### ISSUE TITLE
flutter build web assets missing

### ISSUE THREAD

**Issue by ntatko** [flutter/flutter#133896]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a flutter app 
```bash
flutter create my_app
cd my_app
```
2. Create assets directory and add image
```bash
mkdir assets
cd assets
wget --output-document=flutter-logo.png https://storage.googleapis.com/cms-storage-bucket/c823e53b3a1a7b0d36a9.png
```
3. Add asset to pubspec
```bash
cd ..
echo 'assets:\n    - assets/' >> ./pubspec.yaml
flutter pub get # I don't image this is necessary, but I always run this when pubspec changes
```
4. Use the asset in the project
```dart
Image(image: AssetImage('flutter-logo.png'))
```
5. Run the project in web mode. Note that the image will show up.
```bash 
flutter run -d chrome
```
6. Build the project for web
```bash
flutter build web
```
7. Serve the bundle. For local demo, we'll be using the `serve` npm package.
```bash
npm i -g serve # skip if installed
cd build/web
npx serve
```
8. Note that the image will not show up.

If you want all those steps in one file - here you go
```bash
flutter create my_app
cd my_app
mkdir assets
cd assets
wget --output-document=flutter-logo.png https://storage.googleapis.com/cms-storage-bucket/c823e53b3a1a7b0d36a9.png
cd ..
echo 'assets:\n    - assets/' >> ./pubspec.yaml
flutter pub get
string=$(cat << EOF

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Noah\'s thorough PR Demo',
      home: const Image(image: AssetImage('flutter-logo.png')),
    );
  }
}

EOF
)
echo $string  > ./lib/main.dart
flutter run -d chrome
```

Then, once you've seen it running there:

```bash
flutter build web
npm i -g serve
cd build/web
open http://localhost:3000
npx serve
```

### Expected results

I expect that the outputs of `flutter build web` to match `flutter run`, especially in the handling of assets.

### Actual results

Behavior has differed for me. 

In the case of this example, the asset `flutter-logo.png` isn't in the output `build/web` directory.  It's available in the `./assets` folder, but nowhere inside `build/web/`
<img width="360" alt="Screenshot 2023-09-01 at 19 38 45" src="https://github.com/flutter/flutter/assets/37306038/e51eb739-ecaf-45a1-87ac-6872c603f138">

### Code sample

<details><summary>Code sample</summary>

See the steps to reproduce in order to see the full error.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Noah\'s thorough PR Demo',
      home: const Image(image: AssetImage('flutter-logo.png')), // This asset is visible while `flutter run`, but not while `flutter build web`
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

Running locally `flutter run` on chrome

<img width="1041" alt="Screenshot 2023-09-01 at 19 35 22" src="https://github.com/flutter/flutter/assets/37306038/a6d5dc8f-bf73-467f-bf03-cc5faeac0aea">

Console error in chrome for the built version

<img width="619" alt="Screenshot 2023-09-01 at 19 38 11" src="https://github.com/flutter/flutter/assets/37306038/3ac3e6eb-4205-4af9-8967-126952354df8">

The file is present in the `assets` folder, but not in the build:

<img width="360" alt="Screenshot 2023-09-01 at 19 38 45" src="https://github.com/flutter/flutter/assets/37306038/9b0ada62-2a62-4564-ada3-dee28a7f17d6">

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.2, on macOS 13.0 22A380 darwin-x64, locale en-US)
    • Flutter version 3.13.2 on channel stable at /Users/noahtatko/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (9 days ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/noahtatko/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.76.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0 22A380 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.140

[✓] Network resources
    • All expected network resources are available.

• No issues found!```

</details>

Edit - for thoroughness, I was checking spacing, and verifying that both absolute references and folder-based references to the asset in `pubspec.yaml` also failed.

**Comment by danagbemava-nc** [comment]
Hi @ntatko, I think this might be a duplicate of https://github.com/flutter/flutter/issues/86833. 

Can you take a look at the issue linked above to see if it is similar to your case? 

Thank you

**Comment by ntatko** [comment]
You're right, it does look like a duplicate.
