### ISSUE TITLE
flutter doctor, Windows Version (Unable to determine Windows version (command `ver` returned Windows))

### ISSUE THREAD

**Issue by LeeHaeHyun** [flutter/flutter#133835]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

```
[!] Flutter (Channel stable, 3.13.2, on Windows, locale ko-KR)
    ! Warning: `flutter` on your path resolves to C:\Users\study02\flutter, which is not inside your current Flutter SDK
      checkout at C:\Dev\flutter. Consider adding C:\Dev\flutter\bin to the front of your path.
[X] Windows Version (Unable to determine Windows version (command `ver` returned Windows))
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    X Could not determine java version
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.3)
[!] Android Studio (version unknown)
    X Unable to determine Android Studio version.
    X android-studio-dir = C:\Dev\flutter
    X Unable to find bundled Java version.
[√] Connected device (3 available)
[√] Network resources
``` 

### Expected results

--android-licenses
It's not possible. 

### Actual results

--android-licenses
It's not possible. 

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by LeeHaeHyun** [comment]
Microsoft Windows [Version 10.0.19045.3393]
(c) Microsoft Corporation. All rights reserved.

C:\Users\study02>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.13.2, on Windows, locale ko-KR)
    ! Warning: `flutter` on your path resolves to C:\Users\study02\flutter, which is not inside your current Flutter SDK
      checkout at C:\Dev\flutter. Consider adding C:\Dev\flutter\bin to the front of your path.
[X] Windows Version (Unable to determine Windows version (command `ver` returned Windows))
[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.3)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 4 categories.

C:\Users\study02>flutter config --android-studio-dir="C:\Dev\Android Studio"
Setting "android-studio-dir" value to "C:\Dev\Android Studio".

You may need to restart any open editors for them to read new settings.

C:\Users\study02>flutter doctor --android-licenses
Unable to locate Android SDK.

C:\Users\study02>flutter config --android-sdk "C:\Users\study02\AppData\Local\Android\Sdk"
Setting "android-sdk" value to "C:\Users\study02\AppData\Local\Android\Sdk".

You may need to restart any open editors for them to read new settings.

C:\Users\study02>flutter doctor --android-licenses

C:\Users\study02>flutter doctor --android-licenses

C:\Users\study02>flutter doctor --android-licenses

C:\Users\study02>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.13.2, on Windows, locale ko-KR)
    ! Warning: `flutter` on your path resolves to C:\Users\study02\flutter, which is not inside your current Flutter SDK
      checkout at C:\Dev\flutter. Consider adding C:\Dev\flutter\bin to the front of your path.
[X] Windows Version (Unable to determine Windows version (command `ver` returned Windows))
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.3)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 4 categories.

C:\Users\study02> flutter doctor --android-licenses

C:\Users\study02> flutter doctor --android-licenses

C:\Users\study02> flutter doctor --android-licenses

C:\Users\study02>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.13.2, on Windows, locale ko-KR)
    ! Warning: `flutter` on your path resolves to C:\Users\study02\flutter, which is not inside your current Flutter SDK
      checkout at C:\Dev\flutter. Consider adding C:\Dev\flutter\bin to the front of your path.
[X] Windows Version (Unable to determine Windows version (command `ver` returned Windows))
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.3)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 4 categories.

C:\Users\study02>flutter doctor -v
[!] Flutter (Channel stable, 3.13.2, on Windows, locale ko-KR)
    • Flutter version 3.13.2 on channel stable at C:\Dev\flutter
    ! Warning: `flutter` on your path resolves to C:\Users\study02\flutter, which is not inside your current Flutter SDK
      checkout at C:\Dev\flutter. Consider adding C:\Dev\flutter\bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (8 days ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[X] Windows Version (Unable to determine Windows version (command `ver` returned Windows))

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\study02\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Dev\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Dev\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Dev\Android Studio
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Windows
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 116.0.5845.112
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 115.0.1901.183

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 4 categories.

C:\Users\study02>flutter config --android-studio-dir=C:\Dev\flutter
Setting "android-studio-dir" value to "C:\Dev\flutter".

You may need to restart any open editors for them to read new settings.

C:\Users\study02>flutter doctor -v
Could not parse java version from:
openjdk 17 2021-09-14
OpenJDK Runtime Environment (build 17+35-2724)
OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)

If there is a version please look for an existing bug https://github.com/flutter/flutter/issues/ and if one does not
exist file a new issue.
[!] Flutter (Channel stable, 3.13.2, on Windows, locale ko-KR)
    • Flutter version 3.13.2 on channel stable at C:\Dev\flutter
    ! Warning: `flutter` on your path resolves to C:\Users\study02\flutter, which is not inside your current Flutter SDK
      checkout at C:\Dev\flutter. Consider adding C:\Dev\flutter\bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (8 days ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[X] Windows Version (Unable to determine Windows version (command `ver` returned Windows))

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\study02\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Dev\jdk-17\bin\java
    X Could not determine java version
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Dev\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[!] Android Studio (version unknown)
    • Android Studio at C:\Dev\flutter
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to determine Android Studio version.
    X android-studio-dir = C:\Dev\flutter
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.
    • Consider removing your android-studio-dir setting by running:
      flutter config --android-studio-dir=

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Windows
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 116.0.5845.112
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 115.0.1901.183

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 5 categories.

C:\Users\study02>flutter config --android-sdk C:\Dev\Android Studio
error: flutter config: Too many arguments.

If a value has a space in it, enclose in quotes on the command line
to make a single argument.  For example:
    flutter config --android-studio-dir "/opt/Android Studio"

C:\Users\study02> flutter doctor --android-licenses

C:\Users\study02>java -version
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment (build 17+35-2724)
OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)

C:\Users\study02>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
Could not parse java version from:
openjdk 17 2021-09-14
OpenJDK Runtime Environment (build 17+35-2724)
OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)

If there is a version please look for an existing bug https://github.com/flutter/flutter/issues/ and if one does not
exist file a new issue.
[!] Flutter (Channel stable, 3.13.2, on Windows, locale ko-KR)
    ! Warning: `flutter` on your path resolves to C:\Users\study02\flutter, which is not inside your current Flutter SDK
      checkout at C:\Dev\flutter. Consider adding C:\Dev\flutter\bin to the front of your path.
[X] Windows Version (Unable to determine Windows version (command `ver` returned Windows))
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    X Could not determine java version
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.3)
[!] Android Studio (version unknown)
    X Unable to determine Android Studio version.
    X android-studio-dir = C:\Dev\flutter
    X Unable to find bundled Java version.
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 5 categories.

**Comment by dam-ease** [comment]
Hi @LeeHaeHyun. Thanks for filing this. Can you follow the steps highlighted in https://docs.flutter.dev/get-started/install/windows to resolve other doctor issues so, we could focus on the issue title? When done, Can you also please provide the logs to `flutter doctor -vv`

**Comment by LeeHaeHyun** [comment]
C:\Users\study02>flutter doctor -v
Could not parse java version from:
openjdk 17 2021-09-14
OpenJDK Runtime Environment (build 17+35-2724)
OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)

If there is a version please look for an existing bug https://github.com/flutter/flutter/issues/ and if one does not
exist file a new issue.
[!] Flutter (Channel stable, 3.13.2, on Windows, locale ko-KR)
    • Flutter version 3.13.2 on channel stable at C:\Dev\flutter
    ! Warning: `flutter` on your path resolves to C:\Users\study02\flutter, which is not inside your current Flutter SDK
      checkout at C:\Dev\flutter. Consider adding C:\Dev\flutter\bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (11 days ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[X] Windows Version (Unable to determine Windows version (command `ver` returned Windows))

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\study02\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: C:\Dev\jdk-17\bin\java
    X Could not determine java version
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Dev\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[!] Android Studio (version unknown)
    • Android Studio at C:\Dev\flutter
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to determine Android Studio version.
    X android-studio-dir = C:\Dev\flutter
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.
    • Consider removing your android-studio-dir setting by running:
      flutter config --android-studio-dir=

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Windows
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 116.0.5845.141
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 115.0.1901.183

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 5 categories.




-----Original Message-----
