### ISSUE TITLE
libtxt: Emoji sequences don't render correctly

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#13386]
![screenshot_20171206-113017](https://user-images.githubusercontent.com/551196/33681623-f5681450-da79-11e7-9106-d8fe572deaa6.png)

cc @jason-simmons

**Comment by rlee1990** [comment]
I have the same issue when viewing on ios

**Comment by GaryQian** [comment]
This should no longer happen on Android, and we are aware of the problem on iOS.

**Comment by rlee1990** [comment]
@GaryQian any update on a fix in IOS?

**Comment by GaryQian** [comment]
This looks to be resolved on iOS now.
