### ISSUE TITLE
[google_maps_flutter] Cannot run on iOS simulator

### ISSUE THREAD

**Issue by Rexios80** [flutter/flutter#133866]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Attempt to run an app using the google_maps_flutter plugin on an iOS simulator

### Expected results

It runs

### Actual results

It doesn't run

It used to run on simulators. Not sure if it was an Xcode, macOS, iOS, etc update that broke it, but it doesn't work anymore.

Xcode can run it on a simulator but it has a huge popup about needing to run it with rosetta. I guess Flutter can't handle doing that itself? Either way this is probably a config issue with the google maps plugin.

### Code sample

Unnecessary. The plugin itself doesn't build.

### Logs

[logs](https://github.com/flutter/flutter/files/12499280/output.txt)

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.2, on macOS 13.5.1 22G90 darwin-arm64, locale en-US)
    • Flutter version 3.13.2 on channel stable at /Users/rexios/fvm/versions/3.13.2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (8 days ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
    • Android SDK at /Users/rexios/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0-rc3
    • Java binary at: /Applications/Android Studio Preview.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version unknown)
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (4 available)
    • Aaron’s iPhone (mobile)    • 00008120-001C0CA201DB401E            • ios            • iOS 16.6 20G75
    • iPhone 14 Pro Max (mobile) • FF9097BB-27DB-4F50-A9AC-DA77CA19DB71 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.5.1 22G90 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 116.0.5845.110
    ! Error: Aaron’s iPhone is busy: Waiting to connect and unlock the device. Xcode will continue when Aaron’s iPhone is finished. (code -10)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by stuartmorgan** [comment]
> ```
> warning: ignoring file [...]/build/ios/Debug-development-iphonesimulator/google_maps_flutter_ios/google_maps_flutter_ios.framework/google_maps_flutter_ios,
> building for iOS Simulator-arm64 but attempting to link with file built for iOS Simulator-x86_64
> ```

Are you doing something in this app that would force an ARM simulator? Apps that use `google_maps_flutter` should be running under the Rosetta simulator.

> Either way this is probably a config issue with the google maps plugin.

The requirement to use Rosetta is discussed in https://github.com/flutter/flutter/issues/94491

**Comment by Rexios80** [comment]
What would force the app to use an ARM simulator?
Xcode seems to run the app in the rosetta simulator fine (with an initial information popup), but the flutter tool itself doesn't do that for some reason.

We've been running this app in the simulator since we started using the google maps plugin and only just now started having the issue. The issue came up without updating the google maps plugin, so it must be something external that broke it but I'm not sure what it would be.

**Comment by Rexios80** [comment]
I think I fixed it with the following pieced together from the issue you linked:

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # We already had this
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      # I added this
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = ''
    end
  end
end
```

Not sure why it suddenly broke but thanks for the insight

**Comment by Rexios80** [comment]
The exception I was getting is:

```console
Error (Xcode): Undefined symbol: _OBJC_CLASS_$_FLTGoogleMapsPlugin
```

So this issue is searchable in the future
