### ISSUE TITLE
[webview_flutter] Can't copy text via Javascript navigator.clipboard.writeText

### ISSUE THREAD

**Issue by MobIS1User** [flutter/flutter#133817]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

See this issue: https://github.com/flutter/flutter/issues/111388

### Expected results

see this issue: https://github.com/flutter/flutter/issues/111388

### Actual results

see  this issue: https://github.com/flutter/flutter/issues/111388

### Code sample

see this issue: https://github.com/flutter/flutter/issues/111388

### Logs

I/chromium(29007): [INFO:CONSOLE(0)] "Uncaught (in promise) NotAllowedError: Write permission denied.", source: https://www.hunterindustries.com/irrigation-product/rotors/pgj (0)
I/chromium(29007): [INFO:CONSOLE(0)] "Uncaught (in promise) NotAllowedError: Write permission denied.", source: https://www.hunterindustries.com/irrigation-product/rotors/pgj (0)
I/chromium(29007): [INFO:CONSOLE(0)] "Uncaught (in promise) NotAllowedError: Write permission denied.", source: https://www.hunterindustries.com/irrigation-product/rotors/pgj (0)

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.2, on Microsoft Windows [Version 10.0.19045.3324], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)                        
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)                  
[√] Chrome - develop for the web                                                
[√] Visual Studio - develop Windows apps (Visual Studio Enterprise 2022 17.6.4) 
[√] Android Studio (version 2022.3)                                             
[√] VS Code, 64-bit edition (version 1.79.2)                                    
[√] Connected device (4 available)                                              
[√] Network resources                                                           

• No issues found!

**Comment by MobIS1User** [comment]
We are resurrecting this issue since we are experiencing it now too when our users go to:
https://www.hunterindustries.com/irrigation-product/rotors/pgj
In our flutter web view on an android device and tap the link in the attached screenshot
![copyLinkIssueFLutterWebView](https://github.com/flutter/flutter/assets/137835973/24a2001e-7c7f-4926-a457-61642382f4e7)

**Comment by MobIS1User** [comment]
did @Aulig ever find a fix for this?

**Comment by MobIS1User** [comment]
Can @stuartmorgan give us a code example for the solution he was talking about?

**Comment by MobIS1User** [comment]
Right now everything we read online and that AI generates for us does not work or is editing Java code, which does not seems like a good solution in a Flutter app.

**Comment by MobIS1User** [comment]
Even if the bug is in android code, this propagates an causes a bug for flutter users.
What can we do to resolve this bug? Nothing?

**Comment by stuartmorgan** [comment]
> We are resurrecting this issue since we are experiencing it now

Please don't deliberately file duplicates of issues that have been closed as unfixable just because you are also experiencing them; that's not a change in circumstances for the issue.

> did @Aulig ever find a fix for this?
> Can @stuartmorgan give us a code example for the solution he was talking about?

The issue tracker is for tracking issues and feature requests; consider one of the resources at https://flutter.dev/community#community-grid for cases where you just want to ask for help with your own project's code.

> What can we do to resolve this bug?

The workaround that I described in the referenced bug continues to be an option.

**Comment by MobIS1User** [comment]
Thanks so much for your time and help @stuartmorgan!

Instead of building our own webview with different behaviors 😅, we plan on trying the workaround you mentioned in the other issue: "add it in your own code by setting up a JavaScript channel for the webview, and implementing it via Flutter's Clipboard class."

We are unsure of how to do that, so we asked AI to generate an example and it looks like:

`import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';
import 'package:flutter/services.dart';

class WebViewExample extends StatefulWidget {
  @override
  _WebViewExampleState createState() => _WebViewExampleState();
}

class _WebViewExampleState extends State<WebViewExample> {
  WebViewController _controller;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Flutter WebView example'),
      ),
      body: WebView(
        initialUrl: 'https://flutter.dev',
        javascriptMode: JavascriptMode.unrestricted,
        onWebViewCreated: (WebViewController webViewController) {
          _controller = webViewController;
          _controller.evaluateJavascript("window.addEventListener('flutterInAppWebViewPlatformReady', function(event) {window.flutter_inappwebview.callHandler('test', 'Text to copy').then(function(result) {console.log(result);});});");
        },
        javascriptChannels: <JavascriptChannel>[
          JavascriptChannel(
              name: 'Clipboard',
              onMessageReceived: (JavascriptMessage message) {
                Clipboard.setData(ClipboardData(text: message.message));
              }),
        ].toSet(),
      ),
    );
  }
}`

Is this what you had in mind? Anything else we are missing? 

We do plan to go the flutter stackoverflow, etc. route you mentioned, but are asking here first just in case the flutter dev team who has a great grasp of the context on this bug, wants to weigh in first with specifics (e.g., code example). Any help would be greatly appreciated. Thanks again!

**Comment by MobIS1User** [comment]
As requested, we have posted in stackoverflow here: https://stackoverflow.com/questions/77026101/webview-flutter-cant-copy-text-via-javascript-navigator-clipboard-writetext

**Comment by stuartmorgan** [comment]
> (e.g., code example)

The `webview_flutter` plugin already has a code example that demonstrates correct use of JavaScript channels (which is the only part of what you are trying to accomplish that is specific to the plugin).

**Comment by MobIS1User** [comment]
> > (e.g., code example)
> 
> The `webview_flutter` plugin already has a code example that demonstrates correct use of JavaScript channels (which is the only part of what you are trying to accomplish that is specific to the plugin).

@stuartmorgan, Thanks for the guidance!

We found this:
https://pub.dev/documentation/webview_flutter/latest/webview_flutter/WebViewController/addJavaScriptChannel.html

So that code example takes care of the "addJavaScriptChannel" (lets call that step 1) part of your suggested solution: 
"add it in your own code by setting up a JavaScript channel for the webview, and implementing it via Flutter's Clipboard class."

Step 2 would seem to be to call the "setData(ClipboardData data)" method from the Clipboard class (https://api.flutter.dev/flutter/services/Clipboard-class.html).
We would call set data every time a JavaScriptMessage is published to our created javascript channel.

However, we are unsure of what to do for step number 3:
Publish the text to copy to the created javascript channel (step 1) every time a user clicks a button that performs a "copy clipboard" action in the flutter webview. 
Do you have a code example of how to do this? We have tried several things but are failing to find something that works. 

Thanks again!

**Comment by MobIS1User** [comment]
FYI: After many more experiments, we have made progress on step 3 (currently trying to remember how to write js now to listen for the copy event 😅)  but would still love your code example if you got one. Thanks!

**Comment by stuartmorgan** [comment]
Please see my comment above:

> The issue tracker is for tracking issues and feature requests; consider one of the resources at https://flutter.dev/community#community-grid for cases where you just want to ask for help with your own project's code.
