### ISSUE TITLE
Create redirect from master-api.flutter.dev to main-api.flutter.dev

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#133877]
## Description

Eventually, we'd like to move to using the "main" channel instead of the "master" channel, to be sensitive to the connotations that "master" has.

To that end, we should move the existing `master-api.flutter.dev` site to be `main-api.flutter.dev`, and create a permanent redirect from `master-api.flutter.dev` to `main-api.flutter.dev`. As an alternative, we could just create a `main-api.flutter.dev` redirect and point it to the existing site, but the problem with that is that it continues to propagate the "master" name in new URLs that are used to link to the site, since after redirect it ends up on the master site, not the main site.

I'm not sure exactly what is involved in this reconfiguration, but I assume it has something to do with the Firebase configuration.  One complication will be to make sure that the API docs continue to be published to the renamed Firebase project, and to maintain whatever website version history we want to preserve (not much, I think, maybe the last 5 versions).

cc @godofredoc

**Comment by yusuf-goog** [comment]
@gspencergoog I don't think we manage the links, potentially a someone in the devrel team? @craiglabenz ?

**Comment by gspencergoog** [comment]
Well, it's not really the links themselves.  This has to do with configuring the publishing step to a renamed/new Firebase project, and the hostname of the hosted firebase project (which could also be configured to do the redirects, I think).

The main point is that we want to move the site to the new hostname and provide redirects from the old site. There are probably configuration changes that we could make to the Firebase project that would do this without a lot of churn or work, but I'm not sure what those would be.

**Comment by yusuf-goog** [comment]
@godofredoc do we manage the firebase project, or is someone else the best contact for this?

**Comment by yusuf-goog** [comment]
I do not have the required permissions, @godofredoc is there docs on the needed permissions?

**Comment by parlough** [comment]
\cc @domesticmouse @RedBrogdon Do either of you have access to the relevant DNS configuration and Firebase projects? Perhaps you can help with this.

**Comment by domesticmouse** [comment]
This isn't something that can be done with DNS, but it can be handled by introducing a new bouncer AppEngine service that responds with a 301 Permanent Redirect. 

Context: https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections

**Comment by gspencergoog** [comment]
Who actually owns the Firebase project for the API docs and has the relevant permissions to modify it, and create new ones?

**Comment by gspencergoog** [comment]
@christopherfujino do you know?

**Comment by christopherfujino** [comment]
@parlough or @sfshaza2 would either of you know?

**Comment by domesticmouse** [comment]
My understanding is that both @RedBrogdon and @johnpryan have access to this project.

**Comment by parlough** [comment]
@domesticmouse said:

> This isn't something that can be done with DNS, but it can be handled by introducing a new bouncer AppEngine service that responds with a 301 Permanent Redirect.
> 
> Context: https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections

That's definitely an option for setting up the redirect, especially if its desired to reuse the same Firebase project :)

I was more checking to see who has access to the `master-docs-flutter-dev` Firebase project and could also setup the new `main-api.flutter.dev` subdomain.

**Comment by parlough** [comment]
> The main point is that we want to move the site to the new hostname and provide redirects from the old site. There are probably configuration changes that we could make to the Firebase project that would do this without a lot of churn or work, but I'm not sure what those would be.

If it's fine/desired to reuse the existing `master-docs-flutter-dev` Firebase project, I imagine not a lot of work will be needed:

1. (Optional) To avoid downtime: Set up some mechanism to temporarily (302) redirect `master-api.flutter.dev` requests to `master-docs-flutter-dev.web.app`.
2. Adjust the `master-docs-flutter-dev` hosting configuration to instead use a new `main-api.flutter.dev` subdomain
3. Change the mechanism from step 1 to instead permanently (301) redirect `master-api.flutter.dev` requests to `main-api.flutter.dev`
<br>

If it's desired to use a new `main-docs-flutter-dev` Firebase project, I guess there's a few extra steps:

1. Create a new `main-docs-flutter-dev` Firebase project with hosting setup.
2. Configure the `main-docs-flutter-dev` project to use a new `main-api.flutter.dev` subdomain.
3. I'm not sure what the setup is now, but either configure the service account/token that `flutter/flutter` already uses to have access to the new project or set up the new service account or token.
4. Update flutter/flutter's CI to instead upload to `main-docs-flutter-dev`: https://github.com/flutter/flutter/blob/8ca7d7d1362c1503c77585fff52415ac4295e415/.ci.yaml#L384
5. Setup a mechanism to redirect requests to `master-api.flutter.dev` to `main-api.flutter.dev`. An easy choice would be to push a new `firebase.json` to the old `master-docs-flutter-dev` project to (301) redirect all requests to `main-api.flutter.dev`. Or setup redirection with something external like an AppEngine bouncer service like Brett mentioned.

**Comment by gspencergoog** [comment]
It think it is desirable to rename the project too.  We could still leave the old `master-docs-flutter-dev` project as an empty project with a redirect, but I think that if we don't have it publish to `main-docs-flutter-dev`, then it will just be confusing for future maintainers (and tech debt).

**Comment by godofredoc** [comment]
This may also require some updates in the internal redirections. I'll take a look and try to fix by the end of next week.

**Comment by godofredoc** [comment]
Took a look, this will be landed in two steps:

* Adding two custom domains to master-docs-flutter-dev: main-api.flutter.dev and main-docs.flutter.dev
* Add CNAMES to point those two subdomains

**Comment by godofredoc** [comment]
Because of restrictions in the naming conventions the new project will be called `main-docs-flutter-dev`

**Comment by parlough** [comment]
Thanks for working on this @godofredoc! For those following, https://main-api.flutter.dev/ is now live and being updated with changes.

However, should we reopen this issue until `master-api.flutter.dev` redirects to `main-api.flutter.dev`?

**Comment by gspencergoog** [comment]
Yes, let's keep it open for that part.

**Comment by godofredoc** [comment]
Should we change the `master-api.flutter.dev` the references instead?

**Comment by parlough** [comment]
I do think the references should be updated where possible, but there are likely many `master-api.flutter.dev` links around the internet that may not get updated and many users may type it out of familiarity, but it won't be clear to them they are seeing outdated content.

**Comment by gspencergoog** [comment]
> ...  it won't be clear to them they are seeing outdated content.

Actually, since this is a redirect to the main-api site, the content should be up to date, just the link will be out of date.

**Comment by parlough** [comment]
Oops, sorry for misspeaking, I meant without the redirect it won't be clear the content is out of date :)

**Comment by gspencergoog** [comment]
Yeah, once we have the redirect from master to main, we can actually remove the old master site entirely.

**Comment by godofredoc** [comment]
The redirects are ready please feel free to close the issue when validated.

**Comment by gspencergoog** [comment]
When I go to https://master-api.flutter.dev, (or a specific page like https://master-api.flutter.dev/flutter/animation/Curve-class.html) I still end up with a URL that starts with `master-api.flutter.dev`.  With the redirect, I was expecting to see it switch to `main-api.flutter.dev`. Would that be easy to do? It would help with the migration of external links, since as it is now, copying the link will perpetuate the "master-api" links.

**Comment by godofredoc** [comment]
@gspencergoog can you please give it another try. I fixed one of the redirects.

**Comment by TahaTesser** [comment]
Just noticed all the Dartpad examples aren't loading in the redirected page to https://main-api.flutter.dev/
I was about to report it but looks like @parlough is fixing it in https://github.com/dart-lang/dart-pad/pull/2714

**Comment by gspencergoog** [comment]
Yes, the redirect works for me now.

**Comment by parlough** [comment]
The main API docs are now hosted at `main-api.flutter.dev` under the new `main-docs-flutter-prod` Firebase/GCP project, and `master-api.flutter.dev` now successfully redirects all links while preserving paths to there. 

https://github.com/dart-lang/dart-pad/pull/2714 has also landed and been deployed, fixing embedded sample DartPads.

So I'm going to close this issue as fixed. Thank you all for helping getting this work landed, especially @godofredoc!
