### ISSUE TITLE
[CP] [web] Migrate web-only initialization APIs (#129856)

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#133892]
### Issue Link

https://github.com/flutter/flutter/issues/133069

### Commit Hash

87d5214

### Target

stable

### PR Link

https://github.com/flutter/flutter/pull/133891

### Changelog Description

We deprecated some APIs in the web engine that were used in the framework. The engine changes made it to `stable`, but the framework changes didn't, so users are now seeing warnings in the console that they can't act upon. This PR cherry-picks the framework changes into stable.

### Impacted Users

Flutter web users

### Impact Description

Warnings in the JS console.

### Workaround

No, the warnings are caused by [a "glue" file](https://github.com/flutter/flutter/blob/b1f691c9fc93f8a28c2c7edfd7b9fb3bdb98f851/packages/flutter_tools/lib/src/web/file_generators/main_dart.dart#L8) that the `flutter_tools` creates to put together a flutter web app with the engine code.

### Risk

low

### Test Coverage

yes

### Validation Steps

1. Create a new flutter app
2. Run `flutter run -d chrome`
3. Observe the JS console

In current `stable`, there are always 2 warnings printed to the console:

```
The webOnlyWarmupEngine API is deprecated and will be removed in a future release.
Please use `bootstrapEngine` from `dart:ui_web` instead.
The debugEmulateFlutterTesterEnvironment getter is deprecated and will be removed
in a future release.
Please use `debugEmulateFlutterTesterEnvironment` from `dart:ui_web` instead.
```

After the cherry-pick, those two warnings should be gone.

**Comment by itsjustkevin** [comment]
@ditman  Friendly ping on this cherry-pick.

**Comment by itsjustkevin** [comment]
Reviewed by @yjbanov on the PR.
