### ISSUE TITLE
Image.network "No address associated with hostname"

### ISSUE THREAD

**Issue by theSonGoku1991** [flutter/flutter#133854]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. I have been developing my app almost daily the last few weeks until I had a short break for a few days. Coming back, I noticed there is a new flutter version which I immediately upgraded too. From now on, I notice that none of my Image.network calls resolves images from the internet anymore.

In order to solve this problem, I tried
- adding ```<uses-permission android:name="android.permission.INTERNET"/>``` and ```<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />``` to all AndroidManifest.xml files
- checking the connection status of my emulator (since I did not chage anything, I did not expect to find a reason, I still disconnected and reconnected the wifi of the emulator as well as the overall connection several times)
- checking weather or not I can access regular websites via google chrome in the emulator (if that did not work, it would clearly be a connection problem), which works
- checked weather there is a connection via ```InternetAddress.lookup('google.de')``` (which also works)
- switching to an older flutter version
- switching to another flutter channel (which is kind of the same I guess?)

Unfortunaly, nothing worked.

Since I was working heavily on one custom widget on my apps front page the entire time, I gave it a try and checked out some other widgets further down in my app which also work with Image.network. Same result.

### Expected results

I expect Image.network to be able to find and show the network image I am refering to (as it just did a few days before).

### Actual results

See "Steps to reproduce"

### Code sample

The height, width and they key have NOT been set before. I only placed these attributes because I thought something might have changed which may result in having to set the height and width for the image in the widget itself instead of the surrounding Container widget.

```
Image.network(globals.wochenplanTag[3][0]["img"],
                                        height: 200,
                                        width: 200,
                                        key: Key("test")
                                        )
```

### Flutter Doctor output

PS D:\Coding\nutritious> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.2, on Microsoft Windows [Version 10.0.19045.3324], locale de-DE)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.2)
[√] Connected device (4 available)
[√] Network resources

! Doctor found issues in 1 category.

**Comment by darshankawar** [comment]
Thanks for the report @theSonGoku1991 
Can you take a look at these issues and see if you are hitting the same ?

https://github.com/dart-lang/sdk/issues/53331 and related https://github.com/dart-lang/sdk/issues/53334

**Comment by theSonGoku1991** [comment]
Hi @darshankawar,

yes, seems to be the very same error message, just a different way the error messages comes up. Them mentioning that this problem just recently came up is the very same thing I experience.

**Comment by MikeAngelE** [comment]
Hello, 

I am experiencing the same exact issue. I read dart-lang/sdk#53331 and the 46ac1f commit which would be the solution to my problem. My question is, how to I pull/download/update flutter to that commit? I'm newer to coding so I apologize for the simple question. 

Thank you.

**Comment by MikeAngelE** [comment]
> Hi @darshankawar,
> 
> yes, seems to be the very same error message, just a different way the error messages comes up. Them mentioning that this problem just recently came up is the very same thing I experience.

@darshankawar, how do we update flutter to the 46ac1f commit which resolves this problem? I very recently tried flutter upgrade --force on the stable channel which updated flutter to 3.13.2 from 3.13.1 but still experiencing the same issue

**Comment by darshankawar** [comment]
> how do we update flutter to the 46ac1f commit which resolves this problem?

See if [this](https://github.com/flutter/flutter/wiki/Where%27s-my-commit%3F) helps.




> yes, seems to be the very same error message, just a different way the error messages comes up. Them mentioning that this problem just recently came up is the very same thing I experience.

This probably belongs to dart-lang and not in Flutter repo, so I'll close this in favor of https://github.com/dart-lang/sdk/issues/53331 and https://github.com/dart-lang/sdk/issues/53334. If anybody disagree, write in comments and I'll reopen it.
