### ISSUE TITLE
[iOS] Image picker's `pickVideo` with `ImageSource.gallery` crashes on flutter 3.13. 

### ISSUE THREAD

**Issue by mattermoran** [flutter/flutter#133847]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

This template does not have a place to put some description so I'll do it here instead. 

Since updating to stable 3.13 we started getting reports of people not being able to upload videos because the app would crash. It only started happening in version 3.13. 
Tried downgrading to 3.10.6 and there's no issue there. 
Running 3.13 with `--no-enable-impeller` works fine and app does not crash so it seems to be related to impeller. 
Tried latest master `3.14.0-13.0.pre.71` and no crash either. Meaning it was probably fixed in 3.14 and I think it should be cherry picked into stable as it's pretty important. 

1. Setup image picker package
2. Call `ImagePicker().pickVideo(source: ImageSource.gallery)`

### Expected results

Video picker is shown

### Actual results

App crashes

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('Image picker crash')),
        body: Center(
          child: TextButton(
            child: const Text('Open picker'),
            onPressed: () {
              ImagePicker().pickVideo(source: ImageSource.gallery);
            },
          ),
        ),
      ),
    );
  }
}
```

</details>

### Logs

<details><summary>Logs</summary>

```console
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread.'
*** First throw call stack:
(0x1a3dd05e0 0x19c12bc00 0x1c3ff07ac 0x1c3ff6bc0 0x1c3ff68d4 0x1c3ff6660 0x1a5f293f0 0x1a5f27b40 0x1a5340924 0x1a53404ac 0x1a53469e8 0x1a533fcd8 0x1a533f980 0x1a3d191dc 0x1a3d17be4 0x1a3d17300 0x1a3d16e18 0x104394134 0x104392cd8 0x20bc124d4 0x20bc11a10)
libc++abi: terminating due to uncaught exception of type NSException
Unsupported layout off the main thread for UITextEffectsWindow with no associated or ancestor view controller
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.2, on macOS 14.0 23A5328b darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[!] Android Studio (version unknown)
    ✗ Unable to determine Android Studio version.
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.81.1)
[✓] VS Code (version 1.82.0-insider)
[✓] Connected device (3 available)
[✓] Network resources
```

</details>

**Comment by dam-ease** [comment]
Hi @mattermoran. Thanks for filing this. This has been fixed on the master channel, you can follow up on the replies here https://github.com/flutter/flutter/issues/133147#issuecomment-1699539686 for updates.
Closing this as fixed. Thank you!

**Comment by mattermoran** [comment]
Ah I must be pretty bad at searching existing issues, sorry and cheers!
