### ISSUE TITLE
Allow building and running a Windows app from WSL

### ISSUE THREAD

**Issue by trayanr** [flutter/flutter#133848]
*Cross-reference: https://github.com/flutter/flutter/issues/93164 requests the opposite direction.*

### Use case

The use case is running `flutter run -d windows` from wsl. And seeing all connected devices connected to windows from the wsl binary.  This will allow quick checking for cross-compilation. This will also allow having your dev environment in linux, without duplicating it in windows. The current flow for developing might look like rsync-ing the content to windows then running `flutter run`.

### Proposal

I suggest having some sort of a communication between a windows installed sdk and wsl sdk. This should allow having access to all already configured devices on windows.
Example my windows flutter sdk has 3 devices: `windows`, `chrome`, `edge`. The wsl sdk has only `linux`.
This should also allow to have the android sdk on the windows host directly. (If I am not mistaken flutter doesn't have docs on wsl android development, most tutorials run the android emulator from wsl, although connection to an adb socket is also possible, either way having access to the windows sdk should make it easier to connect and also connect to plugged device to windows, like a physical phone/watch so on.)

I wonder if this could also allow (in the future) some sort of wireless connection to a macos flutter sdk and having this possibility to at least run test from a machine that is not a mac. Or maybe even capturing the rendered window of the mac machine. This could allow maybe a team of developers to still use their preferred dev environments and only have a single apple machine that they can connect to, lowering the upfront cost for apple development.

**Comment by stuartmorgan** [comment]
> The use case is running `flutter run -d windows` from wsl. And seeing all connected devices connected to windows from the wsl binary. This will allow quick checking for cross-compilation.

As discussed in https://github.com/flutter/flutter/issues/93164 (which is requesting the reverse direction), Flutter doesn't have cross-compilation support. This issue is passed as a request to be able to see the Windows device, but without solving the much more involved issue of actually doing cross-compilation the devices won't be useful.

**Comment by trayanr** [comment]
Thanks for pointing the issue out, I hadn't seen it. I can imagine that cross-copilation would be time-consuming. That is why I am suggesting still compiling on the host, but having "just" communication between the two SDK's. This should be needing less resources to implement(, compared to cross-compilation), but still get the job done of running on another device other the main one.
Like having on windows `flutter run --server localhost:12345`
and on wsl having `flutter connect localhost:12345` and then having the ability to do `flutter run -d windows` or vice versa.
Cross-compilation would be indeed good to have but if there are no plans in the conceivable future, having the communication pathway to use different compilation targets would achieve at least part of it and circumvent cross-comp for the near future.

**Comment by stuartmorgan** [comment]
Can you elaborate on what this means:

> This will also allow having your dev environment in linux, without duplicating it in windows.

if you aren't envisioning cross-compilation? If you are just proposing driving the build in Windows from Linux, you still a copy of both the Flutter SDK and the project being built in the Windows environment.

**Comment by loic-sharma** [comment]
Hello, have you considered using these options?

1. [Windows Terminal](https://apps.microsoft.com/store/detail/windows-terminal/9N0DX20HK701) - This lets you open a tab for Windows PowerShell and a tab for WSL's Linux VM. You can run `flutter run -d windows` from PowerShell and `flutter run -d linux` from WSL's Linux VM.
2. [Visual Studio Code's remote development](https://code.visualstudio.com/docs/remote/remote-overview)? VS Code can launch your Linux app using remote development.

From my experience, these work quite well!

> The more I think about it the more complex the problem becomes.

I agree this solution would be complex to implement and maintain. It's not clear to me that the implementation complexity is warranted given these alternatives exist. I'll close this off for now, but please let us know if you have feedback! (Desktop triage)
