### ISSUE TITLE
[CP] Fix flutter upgrade failing with "Unknown Flutter tag" on beta 3.14

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#133822]
### Issue Link

https://github.com/flutter/flutter/issues/133441

### Commit Hash

https://github.com/flutter/flutter/commit/33210218ba4968f6a0c118239abdcd933049bb59

### Target

beta

### PR Link

https://github.com/flutter/flutter/pull/133821

### Changelog Description

This fixes a regression to `flutter upgrade` that would result in an error stating "Unknown Flutter tag" unless either the user's current working directory or they run with the `--force` flag.

### Impacted Users

All Flutter developers upgrading their SDK via `flutter upgrade`.

### Impact Description

Users issuing `flutter upgrade` on any affected release will get an error.

### Workaround

Use `flutter upgrade --force` or change your working directory to your Flutter SDK checkout before running `flutter upgrade`.

### Risk

medium

### Test Coverage

yes

### Validation Steps

once this fix is on beta:

1. commit an empty commit `git commit --allow-empty -m 'empty commit'`
2. reset to the previous commit `git reset --hard HEAD~1`
3. change to a directory NOT within the Flutter SDK `cd $HOME`
4. run `flutter upgrade`. This should succeed if the fix works.

**Comment by christopherfujino** [comment]
@zanderso one more please

**Comment by zanderso** [comment]
cp lgtm
