### ISSUE TITLE
[Proposal] [Documentation] Provide better docs about setting up background processes

### ISSUE THREAD

**Issue by navaronbracke** [flutter/flutter#133855]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Developers wanting to learn how to run Dart code in the background have some resources to look into.

However, the bits and pieces required to get things working, require some research from their end and might not always be easy to understand.

For example we have https://docs.flutter.dev/packages-and-plugins/background-processes but this does not go into detail itself. It is also specifically for plugins, which makes it less discoverable?

It does link to a Medium article, though. (which then has a link to a working example)

In that sample you can eventually figure out how things work, but it requires some reading :)

### Proposal

Explain in more detail how to set up a background process using a Dart entrypoint / separate Flutter Engine.

I could see a codelab as a good option, since you need to do quite a few things:

1) Create a callback handle in Dart (top-level or static method)
    - important is the `@vm:entry-point`
2) Save the callback handle (i.e. using shared preferences), for using it later
    - this involves calling a regular MethodChannel method, which just saves the handle on the native side
    - usually this is done in `void main() {}`
3) On the native side, retrieve the callback handle when needed (i.e. in a service that is started in the background)
4) Use the callback handle to start a new FlutterEngine, that executes the Dart entrypoint that was created in step 1
    - Do not forget to clean up the FlutterEngine
    
Essentially, we should get the GeoFencing sample, but trimmed down to the bare necessities that just explain _how_ the system works. If this could be achieved without explicitly setting up a Flutter plugin, that would be even better (since this avoids a little bit of the overhead)

**Comment by danagbemava-nc** [comment]
Hi @navaronbracke, this belongs on the website repo. It seems like there's already an existing issue requesting that the content be updated. You can find it here https://github.com/flutter/website/issues/1986. 

Please feel free to share your thoughts in the issue linked above. 

I'll be closing this from here as a duplicate. 

PS: These types of documentation requests should go to the website repo.

**Comment by navaronbracke** [comment]
Yes, I realized a bit too late that this belongs on the website 🙈 

I added my remarks in the thread
