### ISSUE TITLE
[CP][ios]fix text input system highlight in iOS 17 Beta 7

### ISSUE THREAD

**Issue by hellohuanlin** [flutter/flutter#133890]
### Issue Link

flutter/flutter#131622

### Commit Hash

40fb92c1513f6cb512d31c043acc2e12a1bdeb12

### Target

stable

### PR Link

https://github.com/flutter/engine/pull/45398

### Changelog Description

Fix text input system highlight in iOS 17 Beta 7. This is due to a change in Beta 7. 

### Impacted Users

All iOS 17 users who uses text fields.

### Impact Description

The auto correction system highlight is displayed incorrectly, which happens to all text fields for all iOS 17 users

### Workaround

NA

### Risk

low

### Test Coverage

yes

### Validation Steps

- Create a dummy flutter project with an Editable text (or just use flutter/dev/integration_tests/ios_platform_view_tests project)
- Write a word with typo
- Observe the correct highlight.

**Comment by itsjustkevin** [comment]
@vashworth could you take a look at this cherry-pick?

**Comment by vashworth** [comment]
> @vashworth could you take a look at this cherry-pick?

@stuartmorgan has given LGTM

**Comment by hellohuanlin** [comment]
@itsjustkevin @CaseyHillers kind reminder since iOS 17 release is happening soon, and I will have another CP coming up after this one. This has very very low risk of breaking existing projects, since we guard it with iOS 17 checks which is not released yet.
