### ISSUE TITLE
[Impeller] Determine correct behavior of bounds hint in EntityPass::Clone.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#133876]
Follow up from https://github.com/flutter/engine/pull/45313 

Just copying the data over appeared to break the wonderous application, it might need to be transformed first.

**Comment by bdero** [comment]
By adjusting the subpass transforms during DrawPicture, we actually already handle this. However, there are indeed problems lurking with savelayer bounds param... MatrixFilters are supposed to affect the bounds hint, which we definitely aren't doing right now: https://github.com/flutter/flutter/issues/126388

**Comment by chinmaygarde** [comment]
Triage: Brandon doesn't think this is a problem and we are tracking the underlying issue in [other bugs](https://github.com/flutter/flutter/issues/126388).
