### ISSUE TITLE
[CP] Fix flutter upgrade failing with "Unknown Flutter tag" on stable 3.13

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#133819]
### Issue Link

https://github.com/flutter/flutter/issues/133441

### Commit Hash

https://github.com/flutter/flutter/commit/33210218ba4968f6a0c118239abdcd933049bb59

### Target

stable

### PR Link

https://github.com/flutter/flutter/pull/133818

### Changelog Description

This fixes a regression to `flutter upgrade` that would result in an error stating "Unknown Flutter tag" unless either the user's current working directory or they run with the `--force` flag.

### Impacted Users

All Flutter developers upgrading their SDK via `flutter upgrade`.

### Impact Description

Users issuing `flutter upgrade` on any 3.13 (3.14 releases are also affected, but will be hotfixed independently) release between beta `3.13.0-0.1.pre` and stable `3.13.2` (hopefully this hotfix will make it into `3.13.3`) will get an error.

### Workaround

Use `flutter upgrade --force` or change your working directory to your Flutter SDK checkout before running `flutter upgrade`.

### Risk

medium

### Test Coverage

yes

### Validation Steps

once this fix is on stable:

1. commit an empty commit `git commit --allow-empty -m 'empty commit'`
2. reset to the previous commit `git reset --hard HEAD~1`
3. change to a directory NOT within the Flutter SDK `cd $HOME`
4. run `flutter upgrade`. This should succeed if the fix works.

**Comment by christopherfujino** [comment]
@zanderso can you review?

**Comment by zanderso** [comment]
cp lgtm
