### ISSUE TITLE
Proposal to add `NavigationMessesenger` that finds current `NavigationState` so that modals could be accessed using only `NavigationState`, without `BuildContext`

### ISSUE THREAD

**Issue by lukehutch** [flutter/flutter#133902]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

To open a full-screen modal in Flutter, you need to do something like:

```dart
Navigator.of(context).push(
    PageRouteBuilder( ... )
);
```

to open a bottom sheet, you need to do

```dart
showModalBottomSheet(
    context: context,
    ...
);
```

Both of these require a `BuildContext`. Similarly, closing these requires a `BuildContext`:

```dart
Navigator.of(context).pop();
```

However, these methods cannot be called from `build()`. They have to be called after the build has finished.

Most of the time, these methods are called in an `onTapped` handler or other event handler. That is fine, if the handler method is non-`async`, because then you can access the associated widget's `BuildContext` when defining the handler.

However, if the handler is `async`, then you get a linter warning that you should not use `BuildContext` across an async gap.

If you use `async` callbacks for event handlers, suddenly there is no way to get the `BuildContext` to open modals.

I tried adding a `scaffoldMessengerKey` to my `MaterialApp`, then fetched `scaffoldMessengerKey.currentState`, but got this error:

```
Navigator operation requested with a context that does not include a Navigator.
```

I don't see any way to get a global context, or a global `NavigationState`, that will work in all situations across an `async` gap.

### Proposal

There needs to be a way to open modal dialogs, even across an `async` gap.

**Comment by SanketRSalve** [comment]
You can try using Builder class which takes context.

**Comment by lukehutch** [comment]
@SanketRSalve You can't use `Builder` inside an `onClicked` handler, because it is not a `build` method.

**Comment by SanketRSalve** [comment]
> @SanketRSalve You can't use `Builder` inside an `onTapped` handler, because it is not a `build` method.

Have you tried GlobalKey? I think it will solve your problem -
https://api.flutter.dev/flutter/widgets/GlobalKey-class.html

**Comment by lukehutch** [comment]
Yes, as I mentioned I tried adding a `scaffoldMessengerKey` (which is a `GlobalKey<ScaffoldMessengerState>`) to my `MaterialApp`. But the `BuildContext` of that key does not have a `Navigator`, hence the error that I reported.

You can`t assume a `BuildContext` ever persistently exists, as far as I understand it, so unless there is some `Element` at the root of the build tree that never goes away, I don't see how I can get a reliable `BuildContext` in a `GlobalKey`.

What I would like to see is something like `ScaffoldMessenger` that can fetch a `Navigator` for the current `Scaffold`. And then each of the methods of opening a new modal should require only a `NavigationState`, not a `BuildContext`.

**Comment by lukehutch** [comment]
OK if I add a `GlobalKey<ScaffoldState>` to every single `Scaffold` in my app, _and_ as long as there is only ever one `Scaffold` in the build tree at any given time (because the key can't be reused), then I can in fact get a `NavigatorState` from this key. However, this does not at all feel robust (and I think this may have life cycle issues, where the `GlobalKey.currentState` could go away at any time).

**Comment by SanketRSalve** [comment]
> OK if I add a `GlobalKey<ScaffoldState>` to every single `Scaffold` in my app, _and_ as long as there is only ever one `Scaffold` in the build tree at any given time (because the key can't be reused), then I can in fact get a `NavigatorState` from this key. However, this does not feel robust (I think this may have lifecycle issues, where the `GlobalKey.currentState` could go away at any time).

Creating a service class for navigation or using state management won't this be a good idea. I'm don't have much experience in flutter so correct me if I'm wrong.

**Comment by darshankawar** [comment]
> I tried adding a `scaffoldMessengerKey` to my `MaterialApp`, then fetched `scaffoldMessengerKey.currentState`, but got this error:
> 
> ```
> Navigator operation requested with a context that does not include a Navigator.
> ```

@lukehutch Can you take a look at [this](https://stackoverflow.com/a/51292613) and see if it helps as far as the error is concerned ?

**Comment by lukehutch** [comment]
@darshankawar Thanks, I saw that SO answer previously, but it does not solve the issue in this case.

Here is the problem again, more succinctly:

1. Opening full-screen modals and/or bottom sheets (collectively, "modals") requires a `BuildContext`.
2. You're not supposed to open modals from a `build` method, because `build` methods should not modify state, including navigation state. However, *`BuildContext` is technically only available while a `build` method is running*.
3. Typically modals are only opened in event handlers, such as `onTapped`, *and they use a variable capture of the `BuildContext` of the `Widget` in which the handler is defined*, which is passed to the code that opens the modal.
5. However, the situation is significantly worse when the handler is `async`, *because `BuildContext` cannot be used across an `async` gap. The `BuildContext` lifecycle is not guaranteed to be valid when the handler is run. The `BuildContext` may not even be mounted when the handler is run, for example.
6. Many handlers *have* to be defined as `async` just to get their job done (e.g. tapping a button may download a file from a server, and then open a modal to edit the file).
7. There is no way to reliably get a `NavigationState` reference if there is no `BuildContext`, although a `NavigationState` can be captured after calling `Navigator.of(context)` in the `build` method. However that does not solve the problem for all modals, because some modal types require a `BuildContext`, not a `Navigator`, to open.
8. If you know you have a parent `Scaffold` in the widget tree, you can probably get a `BuildContext` and/or a `NavigationState` using a `GlobalKey<ScaffoldState>` and then getting the `currentContext` from that key. However I don't know if the `BuildContext` of a `Scaffold` is always available (probably not, I'm sure it could be unmounted). So this is not reliable.

There just doesn't seem to be a clear, reliable way to do this.

1. There should be a global `NavigationState` reference that you can get, easily.
2. Modals should be openable using only this `NavigationState`, without a `BulidContext`.

**Comment by darshankawar** [comment]
Thanks for the detailed follow-through. Retitling to reflect the updated proposal.

**Comment by abichinger** [comment]
@lukehutch Have you tried setting `navigatorKey` in `MaterialApp`? Here is an [example](https://stackoverflow.com/a/59771354/3140799)

This should allow you to have multiple Scaffolds.

**Comment by lukehutch** [comment]
> @lukehutch Have you tried setting `navigatorKey` in `MaterialApp`? Here is an [example](https://stackoverflow.com/a/59771354/3140799)
> 
> This should allow you to have multiple Scaffolds.

Thanks for the pointer... I didn't know about that... I am using the `MaterialApp.router`constructor, and it doesn't have that parameter.

**Comment by lukehutch** [comment]
OK, so I assume because of this that if you're doing routing with a custom router, then you have to navigate through that router instance, you can't use `navigationKey`? I'll close this since it seems in the more common case, this is a solved problem already. Thanks!
