### ISSUE TITLE
Failed host lookup on debug mode

### ISSUE THREAD

**Issue by iamalper** [flutter/flutter#133993]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [x] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Add `http` to dependencies
2. Make an GET request to `https://servis.mgm.gov.tr` on debug mode

### Expected results

Shouldn't throw `OSError: Failed to host lookup`.
When i made same request with Curl, it responses `500 Unauthorized` which is the expected result.

### Actual results

If running on debug mode, it throws `Failed host lookup: 'servis.mgm.gov.tr'`
If release or tests, doesn't throw and successfully gets response.
This error not happens when request made to `www.mgm.gov.tr`.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:http/http.dart' as http;
final url = Uri.https("servis.mgm.gov.tr", "web/meteoalarm/today");
final response = await http.get(url);
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
_NativeSocket.lookup.<anonymous closure> (dart:io-patch/socket_patch.dart:520)
<asynchronous gap> (Unknown Source:0)
_NativeSocket.staggeredLookup.<anonymous closure>.lookupAddresses.<anonymous closure> (dart:io-patch/socket_patch.dart:0)
<asynchronous gap> (Unknown Source:0)
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.2, on Ubuntu 22.04.3 LTS 6.2.0-31-generic, locale tr_TR.UTF-8)
    • Flutter version 3.13.2 on channel stable at /home/alper/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (11 gün önce), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /mnt/hdd-1/android-sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /mnt/hdd-1/android-sdk
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.20.1+1-post-Ubuntu-0ubuntu122.04)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Ubuntu 22.04.3 LTS 6.2.0-31-generic

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
exit code 0
```

</details>

**Comment by KostyaLocal** [comment]
Same error on release build on android device. 

Client exception with SocketException: Failed host lookup

Doctor output:
[√] Flutter (Channel master, 3.14.0-14.0.pre.92, on Microsoft Windows [Version 10.0.19044.3324], locale ru-RU)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.2)
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.81.1)
[√] Connected device (4 available)
[√] Network resources

Guys, how long can you torture us with this error?

**Comment by KostyaLocal** [comment]
@iamalper workaround for you: add ipv6 record for servis.mgm.gov.tr , if you can

**Comment by iamalper** [comment]
> @iamalper workaround for you: add ipv6 dns record for servis.mgm.gov.tr , if you have access to the DNS zone

Thanks but i don't have access, it's a public api

**Comment by huycozy** [comment]
Hi @iamalper 
Which platform and IDE are you seeing this issue on? Based on the above comments, it seems to be similar to an issue filed recently https://github.com/flutter/flutter/issues/132912, please take a look at https://github.com/flutter/flutter/issues/132912#issuecomment-1691046212 and confirm if your case is the same. If it is, please do as the suggestion there. Thanks!

**Comment by iamalper** [comment]
> Hi @iamalper Which platform and IDE are you seeing this issue on? Based on the above comments, it seems to be similar to an issue filed recently #132912, please take a look at [#132912 (comment)](https://github.com/flutter/flutter/issues/132912#issuecomment-1691046212) and confirm if your case is the same. If it is, please do as the suggestion there. Thanks!

Issue happens on VsCodium in Xubuntu 22.04 host with latest Dart and Flutter extensions. 
I confirm #132912 is same.
Also i see this is a Dart specific issue and there was opened an issue with same case dart-lang/sdk#53334
