### ISSUE TITLE
[go_router] deeplink FormatException: Illegal scheme character

### ISSUE THREAD

**Issue by andredealmei** [flutter/flutter#133950]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

open a deep link like this with app closed: lets_eat_dash://compraqui.app/panel/orders/

### Expected results

navigate to /panel/orders

### Actual results

FormatException: FormatException: Illegal scheme character (at character 5)
lets_eat_dash://compraqui.app/panel/orders/69428033-34ff-456b-8eaf-f3b94ab0...
    ^
  File "uri.dart", line 1738, col 5, in _Uri._fail
  File "uri.dart", line 2280, col 9, in _Uri._makeScheme
  File "uri.dart", line 1600, col 18, in new _Uri.notSimple
  File "uri.dart", line 1138, col 17, in Uri.parse
  File "path_utils.dart", line 123, col 22, in canonicalUri

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.1, on Microsoft Windows [versÆo 10.0.22621.2134], locale pt-BR)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.4)
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.81.1)
[√] VS Code (version 1.82.0-insider)
[√] Connected device (4 available)
[√] Network resources
</details>

**Comment by danagbemava-nc** [comment]
Hi @andredealmei, the deep link you have provided is not a valid URI. If you pass it through a URI validator you'll see that the deep link fails. underscores are not allowed in the scheme of a URI. You can use dashes, but not underscores. 

Closing as this is an issue with your URI. 

Thank you
