### ISSUE TITLE
Engine failing to roll to framework on new analyzer lint.

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#133922]
Starting with the roll attempt at https://github.com/flutter/flutter/pull/133916

https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20analyze/63719/overview

```
Command: bin/flutter analyze --flutter-repo
Command exited with exit code 1 but expected zero exit code.
Working directory: /b/s/w/ir/x/w/Á flutter sdk/.
stdout and stderr output:
Analyzing Á flutter sdk...                                      

   info • Unnecessary constructor invocation • packages/flutter/lib/src/widgets/framework.dart:3113:75 • prefer_collection_literals
```

That message is for this line: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/framework.dart#L3113

Scanning the commits, this one looks interesting:

https://dart.googlesource.com/sdk.git/+/cd8a3370e7d854ded526329178eb8c046917ddf7

That rolled into the engine at https://github.com/flutter/engine/pull/45412

@srawlins

**Comment by srawlins** [comment]
Sorry about that, @zanderso ; thanks for looking into the fix!
