### ISSUE TITLE
Device Back Button Closes Application Instead of Menu/Dialog/Page

### ISSUE THREAD

**Issue by tomshane** [flutter/flutter#133976]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

When I open a menu or a dialog and press Back button on a device/emulator (Android) the whole application is closed instead of just menu or dialog. The behavior is same even for "pushed" pages. When using Navigator.pop(), everything works.

Recently everything worked as expected, I just noticed this after upgrade (flutter, packages).

### Expected results

Menu and dialogs should close.

### Actual results

The whole application is closed.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.13.2, on Microsoft Windows [Version 10.0.22621.2134], locale cs-CZ)
    • Flutter version 3.13.2 on channel stable at C:\Utilities\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (11 days ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\Tom Shane\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code, 64-bit edition (version 1.81.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.70.0

[√] Connected device (1 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64 • Android 13 (API 33) (emulator)

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by tomshane** [comment]
Solved by setting "enableOnBackInvokedCallback" from "true" to "false".

**Comment by dam-ease** [comment]
Hi @tomshane. Thanks for filing this and for the update as well. Closing this as solved. Thank you!

**Comment by fabriquetonvoyage** [comment]
Thanks !!
I was going crazy with this new behavior!! Do you know what has changed in last Flutter version ?
