### ISSUE TITLE
Huge performance issue when using `PageView` with blur in each page

### ISSUE THREAD

**Issue by mattermoran** [flutter/flutter#133910]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I was going to check if impeller have fixed in issue I file a while ago https://github.com/flutter/flutter/issues/89585 and apparently it just got a lot worse as it seems impeller made it very stuttery. 

1. Create a page view widget
2. Add children with `BackdropFilter(filter: ImageFilter.blur(sigmaX: 20, sigmaY: 20), child: ...)`
3. Swipe around

### Expected results

Pages change smoothly

### Actual results

Very stuttery

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'dart:ui';

void main() {
 runApp(App());
}

class App extends StatelessWidget {
 @override
 Widget build(BuildContext context) {
   return MaterialApp(
     home: Scaffold(
       backgroundColor: Colors.black,
       body: PageView.builder(
         itemBuilder: (context, index) {
           return Stack(
             children: [
               Container(color: Colors.white),
               Positioned(
                 child: Container(
                   clipBehavior: Clip.hardEdge,
                   decoration: BoxDecoration(),
                   child: BackdropFilter(
                     filter: ImageFilter.blur(
                       sigmaX: 20,
                       sigmaY: 20,
                     ),
                     child: Center(
                       child: Text(
                         'Page #${index + 1}',
                         style: TextStyle(
                           fontWeight: FontWeight.bold,
                           fontSize: 32,
                         ),
                       ),
                     ),
                   ),
                 ),
               ),
             ],
           );
         },
       ),
     ),
   );
 }
}
```

</details>

### Screenshots or Video

<details>
<summary>Video with impeller</summary>

https://github.com/flutter/flutter/assets/29712386/747643b0-4c0d-432f-87a8-fe68e2df01e9

</details>

<details>
<summary>Video without impeller (--no-enable-impeller)</summary>

https://github.com/flutter/flutter/assets/29712386/2d45d1a6-7fe8-404e-a5a7-4e346ad46425

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.2, on macOS 14.0 23A5337a darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[!] Android Studio (version unknown)
    ✗ Unable to determine Android Studio version.
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.81.1)
[✓] VS Code (version 1.82.0-insider)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by mattermoran** [comment]
@darshankawar the difference is that I apply blur to each child and that issue has it outside but I'd say it's most likely same issue.

**Comment by darshankawar** [comment]
Thanks for the feedback @mattermoran 
I do believe the root-cause is same as the linked issue and once that is fixed, you may run your scenario on latest master to confirm whether the issue persists or not. You may subscribe to the linked issue to get updates on it. I'll close this in favor of the linked issue. If you disagree, write in comments and I'll reopen it.
