### ISSUE TITLE
When multi-line TextField enters Chinese in Web, the position of the candidate word box is incorrect

### ISSUE THREAD

**Issue by xia-weiyang** [flutter/flutter#133900]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create an empty project with a text field and run by web.
2. Enter multi-line text in Chinese.
3. When there are enough rows and observe the issue.

### Expected results

https://github.com/flutter/flutter/assets/11485324/966fddc1-0137-4ce7-8817-d196734a1547

Candidate boxes can follow the cursor no matter how many lines of text

### Actual results

https://github.com/flutter/flutter/assets/11485324/b6d6dba1-42fe-4662-9836-26bcd3fbaa32

Candidate boxes can no longer follow the cursor in the second line

### Code sample

<details><summary>Code sample</summary>

```dart
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: const Center(
        child: TextField(
          maxLines: null,
        ),
      ),
    );
  }
```

</details>

### Screenshots or Video

see Actual results

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

[✓] Flutter (Channel stable, 3.13.2, on macOS 13.4.1 22F770820d darwin-arm64,
    locale zh-Hans-CN)
    • Flutter version 3.13.2 on channel stable at /Users/xia/Work/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (9 days ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version
    33.0.0-rc4)
    • Android SDK at /Users/xia/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 72.1.4
    • Dart plugin version 223.7571.203

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.4.1 22F770820d
      darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.140

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
</details>

**Comment by darshankawar** [comment]
Thanks for the report @xia-weiyang 
I tried following the replicating the reported behavior, but I wasn't able to see the behavior.
Also, I completely didn't understand what exactly the issue here is because I couldn't find any difference between the videos you shared. 
Can you elaborate more on the actual vs expected behavior ?

**Comment by xia-weiyang** [comment]
@darshankawar Thanks for your reply.

The position of the candidate box should be from here, because the position of the cursor is here.

![image](https://github.com/flutter/flutter/assets/11485324/bbd2c7ac-455a-469d-a7e1-f05ae388a489)

The correct position should be as shown in the picture below, and the candidate box is displayed from the bottom of the cursor.

![image](https://github.com/flutter/flutter/assets/11485324/ec571810-e7d6-416c-9da9-2482cdc086a9)

**Comment by darshankawar** [comment]
Thanks for the explanation @xia-weiyang 
I tried the same scenario using latest stable and found that the cursor position seems to be correct I guess ? Please see below video:


https://github.com/flutter/flutter/assets/67046386/2c06607b-1f78-45d0-b0ea-f55e742e4e4a

I used simplified chinese input, running on macOS.

**Comment by xia-weiyang** [comment]
@darshankawar What is your flutter version ? My version is 3.13.2.
I watched your video carefully, there are some deviations, but not as serious as mine

**Comment by huycozy** [comment]
@xia-weiyang I checked this on stable 3.13.2 and master channels but also can't see the issue as in your demo above. 

https://github.com/flutter/flutter/assets/104349824/57c89d46-80c1-41c5-849f-098868066c24

Maybe there are some specific steps to reproduce the issue?

Also, this seems to have the same cause with https://github.com/flutter/flutter/issues/128323; reposition issue, please see https://github.com/flutter/flutter/issues/128323#issuecomment-1583128638.
