### ISSUE TITLE
Flutter is not tested with ARC and Chromebooks in our test matrix

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#13394]
Tracking issue for Flutter testing matrix for ARC/Chromebook support.

**Comment by jonahwilliams** [comment]
FYI @godofredoc @digiter, it would be nice to get some pixelbooks for the devicelab since we've recently expanded capacity.

**Comment by godofredoc** [comment]
@jonahwilliams do we need the screen of the pixelbooks or chromebits are enough?

**Comment by jonahwilliams** [comment]
any chromebook is fine, ideally x86_64 ABI so we get more coverage there
