### ISSUE TITLE
[Android] Add callback for external view synchronization

### ISSUE THREAD

**Issue by XuanTung95** [flutter/flutter#133990]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I've created a plugin for managing external Android views related to https://github.com/flutter/flutter/issues/128198
But it is missing the position synchronization feature. When the external view is moving, its position does not match the frame produced by Flutter.

I was able to implement the synchronization feature but it required exposing some callback from the flutter engine.
This ticket is for merging these changes into Flutter.

### Proposal

The mechanism:
1. At the end of the compositing phase, after updating the view position and before rasterization, send the new position and the timestamp (framework build end time) to the native plugin.
2. At the start of rasterization, send the engine build end time and the current timestamp to the native plugin. (requires adding a new callback into the engine)
3. Using `FlutterImageView `to render the UI. It provides `Image `from `ImageReader`.
4. The `Image `provides `getTimestamp()` which is the nano time when the image is created. Use it to find the rasterization start time -> find the engine build end time -> find the framework build end time -> find the corresponding position. Update the corresponding position and draw the `Image`. (requires adding callback and modifying `FlutterImageView`)

Detail modification:

Engine (PR https://github.com/flutter/engine/pull/45430):
 - Add `FlutterEngine.addOnFrameTimeListener()`, when rasterization starts, it fires the callback that provides buildStartTime, buildEndTime, raster nanoTime for the plugin.
 - Add `FlutterImageView.addOnImageAvailableListener` which exposes `ImageReader.OnImageAvailableListener` callback.
 - FlutterImageView delays the `Image.close()` call until the Image is drawn on screen. Because in practice, calling `Image.close()` too soon will cause miss synchronization event if the `Image` and its position are correct. 
 The image is closed at the `Choreographer.FrameCallback` after the nearest `View.onDraw`. 
 Detail: `ImageReader.acquireLatestImage()` -> first `Choreographer.FrameCallback` -> `View.onDraw()` ->  second `Choreographer.FrameCallback` (Image is closed here).
 - Expose the `FlutterImageView.getPendingImage()`

Result

After:

https://github.com/flutter/flutter/assets/26743089/28fb756d-656b-4d15-a17c-30a8b1f52f82

Before:

https://github.com/flutter/flutter/assets/26743089/49384ba8-9da7-4430-a0eb-4a34317ea252

**Comment by camsim99** [comment]
cc @johnmccutchan to take a look at the changes

**Comment by XuanTung95** [comment]
I managed to distribute a custom engine for my plugin.
It's no longer necessary to merge this into Flutter.
