### ISSUE TITLE
FAQ: document flutter's fixed memory cost

### ISSUE THREAD

**Issue by xster** [flutter/flutter#13393]
https://flutter.io/faq/#how-big-is-the-flutter-engine should include a blank run memory cost too

**Comment by sethladd** [comment]
Can someone can suggest a way to do this, which is easily repeatable?

**Comment by xster** [comment]
If easy were a relative term, I'll run through it once to test. 
My methodology will basically be flutter create, delete everything in pubspec, delete everything in main.dart and run it in xcode and android studio. Use native instrumentation tools to measure memory.

**Comment by xster** [comment]
Also caveat: Android was tested on a Nexus 5X. Each Android OEM OS can choose an arbitrary number as an opener for initial heap allocation as far as I remember based on that device's RAM size.

**Comment by Hixie** [comment]
Probably worth including a `MaterialApp` and a call to `runApp` in these calculations, because we position the framework as a big part of the offering and the framework is bound to use up a lot of RAM too.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2085](https://github.com/flutter/website/issues/2085) via [**ZenHub**](https://www.zenhub.com/)
