### ISSUE TITLE
[Video_player_Web] if crossOriginIsolated=true video is not display

### ISSUE THREAD

**Issue by Nimo11** [flutter/flutter#133901]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

When crossOriginIsolated is set to true

if hosting server have this header 
`Cross-Origin-Opener-Policy:same-origin
Cross-Origin-Embedder-Policy:require-corp`

 loading video from another domain is prohibited if this domain doesn't return Cross-Origin-Resource-Policy header by the browser if this domain doesn't return Cross-Origin-Resource-Policy header

### Expected results

Load and display video

adding to video html tag the property crossOrigin = "anonymous" solve the problem

```
final VideoElement videoElement = VideoElement()
      ..id = 'videoElement-$textureId'
      ..src = uri
      ..crossOrigin = "anonymous"
      ..style.border = 'none'
      ..style.height = '100%'
      ..style.width = '100%';
```Video not loaded

### Actual results

Video not loaded

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```
controller = VideoPlayerController.networkUrl(Uri.parse(path));
...
</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>
![Capture3](https://github.com/flutter/flutter/assets/60822263/f3c5bf27-d99c-4340-8231-dabf145828e3)

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

[√] Flutter (Channel stable, 3.13.2, on Microsoft Windows [version 10.0.19045.3324], locale fr-FR)
    • Flutter version 3.13.2 on channel stable at c:\src\flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision ff5b5b5fa6 (9 days ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at D:\Users\info\Android\SDK
    • Platform android-33, build-tools 33.0.0
    • ANDROID_SDK_ROOT = D:\Users\info\Android\SDK
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33205.214
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.81.1)
    • VS Code at C:\Users\info\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.70.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [version 10.0.19045.3324]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 116.0.5845.141
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 116.0.1938.62

[√] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by darshankawar** [comment]
Thanks for the report @Nimo11 
It seems `crossOriginIsolated=true` is not yet supported on web yet. See [this](https://github.com/flutter/flutter/issues/127902) issue for further reference. 
Since it is not supported, that might be the reason as why you are seeing the reported behavior. Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.

**Comment by Nimo11** [comment]
Hello, thank you for your responsiveness. Flutter web works in this mode but in the case where the headers are not provided by the server as is the case with firebase storage for example the possibility of adding the crossorgin=anonymous tag allows to circumvent the problem for the video . Images works as detailed here
[Stackoverflow](https://stackoverflow.com/questions/69197475/firebase-auth-breaks-with-cross-origin-isolation-i-e-when-using-cross-origin-r)

So adding this property may be optionaly would be very intresting.
