### ISSUE TITLE
Loading more emojis will keep flashing, which is why?

### ISSUE THREAD

**Issue by wuwenwei5566** [flutter/flutter#133907]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Display emojis using the Text component

### Expected results

Normal display

### Actual results

emoji flash

### Code sample

```
CustomScrollView（物理学：const BouncingScrollPhysics（父：AlwaysScrollableScrollPhysics（），条片：[如果（objcetMgr.emojiMgr.useEmojiList.isNotEmpty）SliverToBox适配器（孩子：填充（填充：EdgeInsets.fromLTRB（CommonW.wd（32），CommonW.wd（32），CommonW.wd（32），CommonW.wd（32）），孩子：CommonText（'最近使用',颜色：ThemeColor.textColor45（上下文），字体：Commonfont.sp（26），），），），如果（objcetMgr.emojiMgr.useEmojiList.isNotEmpty）SliverGrid.builder（addAutomaticKeepAlives：false，项目计数：objcetMgr.emojiMgr.useEmojiList.length，gridDelegate：SliverGridDelegateWithFixedCrossAxisCount（儿童方面比率：1，交叉轴计数：8，mainAxisSpacing：CommonW.wd（24），跨轴间距：CommonW.wd（26），），itemBuilder：（上下文，索引）{返回createItem（objcetMgr.emojiMgr.useEmojiList[index]）；}，），SliverToBox适配器（孩子：填充（填充：EdgeInsets.fromLTRB（CommonW.wd（32），CommonW.wd（32），CommonW.wd（40），CommonW.wd（32）），孩子：CommonText（'所有表情',颜色：ThemeColor.textColor45（上下文），字体：Commonfont.sp（26），），），），SliverGrid.builder（addAutomaticKeepAlives：false，itemCount：_emojiList.length，gridDelegate：SliverGridDelegateWithFixedCrossAxisCount（儿童方面比率：1，交叉轴计数：8，mainAxisSpacing：CommonW.wd（24），跨轴间距：CommonW.wd（26），），itemBuilder：（上下文，索引）{返回createItem(_emojiList[index]);}，），SliverToBox适配器（儿童：尺寸箱（高度：widget.bottom ??CommonW.wd(80) + objcetMgr.navigatorMgr.SAFE_BOTTOM，）），]，）；


Widget createItem(EmojiModel data) {
    return GestureDetector(
      onTap: () => _onItemChoose(data),
      child: Container(
        width: double.infinity,
        height: double.infinity,
        color: Colors.transparent,
        alignment: Alignment.center,
        child: CommonText(
          data.code,
          font: Platform.isAndroid ? Commonfont.sp(48) : Commonfont.sp(52),
        ),
      ),
    );
  }

```

### Screenshots or Video

Uploading RPReplay_Final16935690

https://github.com/flutter/flutter/assets/52393077/8890ec48-bc94-4a05-91c2-0f54cd25eda0

76.mov…

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

[!] Flutter (Channel [user-branch], 3.13.2, on macOS 13.5.1 22G90 darwin-arm64, locale zh-Hans-CN)
    ! Flutter version 3.13.2 on channel [user-branch] at /Users/wuwenwei/development/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at
      https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision ff5b5b5fa6 (9 days ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git"
      directly to perform update checks and upgrades.

**Comment by darshankawar** [comment]
Thanks for the report @wuwenwei5566 
Can you provide us a [complete runnable but minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can directly copy paste and run to verify the reported behavior ?
Please don't include any third party package code in it and use English language in your code so that it is easily readable.
