### ISSUE TITLE
Flutter downloadable archives don't allow 'flutter create' to run without a network.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#13403]
For some reason, when we have a populated .pub-cache in the flutter root, and try and run `flutter create` to create a new project, flutter still tries to go to the internet to `pub get` something.

It's probably just a mismatch in versions between the repo and the template pubspec, or maybe there are additional requirements.

The downloadable archives are meant to allow someone to explore Flutter without an internet connection, so it would be nice to avoid this, at least for a trivial "hello world" project.

**Comment by mit-mit** [comment]
@jakobr-google and I discussed a bit, and we speculate the the networking connection is for pub to resolve the dependencies in `pubspec.yaml` to 1) get the latest versions of those, and 2) download to cache any that may not be there already. A few options for resolving this:

Checkin `pubspec.lock` to our template (and remove it from `.gitignore`). This is actually the pub guideline. The downside to this would be that we have to maintain pubspec.lock and actually it's dependencies on some regular basis.

Make sure that what we need for a new app is in the cache, and invoke pub offline:
https://www.dartlang.org/tools/pub/cmd/pub-get#getting-while-offline

**Comment by gspencergoog** [comment]
My latest packaging script now deals with this by building each type of `flutter create` project types to warm the pub cache with any needed dependencies.
