### ISSUE TITLE
Flutter Web release build including debug VM

### ISSUE THREAD

**Issue by anon-is-anonymus** [flutter/flutter#134021]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [x] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Compile flutter as a release build for web
2. Run using node.js, served through Koa
3. Inspect the console

### Expected results

Console printout should only show one printout from main.dart.js

_This screenshot is from the debug build_
![image](https://github.com/flutter/flutter/assets/68243858/5e959287-66a7-4591-9cd9-46f6fc2031dc)

### Actual results

Console printout shows both a printout from main.dart.js as well as VM main.dart.js

![image](https://github.com/flutter/flutter/assets/68243858/04988fbb-62f7-4672-b1c9-9653ca701f71)

### Code sample

<details><summary>Code sample</summary>

```dart
Stream<Future<(StatusEnums, String)>> statusStream =
      Stream<Future<(StatusEnums, String)>>.periodic(
          const Duration(milliseconds: 750), (i) async {
    print("Compute $i occured at ${DateTime.now().millisecondsSinceEpoch}");
    try {
      var (newStatus, msg) =
          await _StateComp().timeout(const Duration(seconds: 1));
      oldStatus = newStatus;
      return (newStatus, msg);
    } catch (e) {
      return (StatusEnums.Failed, "Could not get status");
    }
  }).asBroadcastStream(
    onCancel: (subscription) => subscription.cancel(),
  );
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.6, on Ubuntu 20.04.5 LTS 5.15.0-82-generic, locale en_US.UTF-8)
    • Flutter version 3.10.6 on channel stable at /home/dc/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (8 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
    • cmake version 3.24.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.5 LTS 5.15.0-82-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

</details>

**Comment by dam-ease** [comment]
Hi @anon-is-anonymus. Thanks for filing this. I'm trying to reproduce this with the code sample provided but can't seem to, please can you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code?
Also, I see you are on an older version of flutter, can you upgrade to the latest versions to confirm this issue still persists?
