### ISSUE TITLE
Go Router extra in context.push is looking for toJson function

### ISSUE THREAD

**Issue by joseianpatrick** [flutter/flutter#134017]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Add custom extra

![Screenshot 2023-09-05 at 2 12 36 PM](https://github.com/flutter/flutter/assets/79951156/eafed341-47c2-48ea-81dc-60426bea36e1)
2. Try to push the new screen and add extra

![Screenshot 2023-09-05 at 2 12 47 PM](https://github.com/flutter/flutter/assets/79951156/b87a290a-3a95-45b5-b92c-7d78af019106)
Like this

![Screenshot 2023-09-05 at 2 14 30 PM](https://github.com/flutter/flutter/assets/79951156/8183ad58-ed2f-41c8-a41c-edaa6f69da63)

3. Check error

![Screenshot 2023-09-05 at 2 14 15 PM](https://github.com/flutter/flutter/assets/79951156/ad32bd73-2ae6-4efd-9b83-0f7cddc495cb)

### Expected results

It should normally push the extra in new screen

### Actual results

It shows an error looking for toJson method

![Screenshot 2023-09-05 at 2 15 00 PM](https://github.com/flutter/flutter/assets/79951156/376cd620-41a6-4b48-a07b-562149c99ef0)

### Code sample

<details><summary>Code sample</summary>

```

Future<T?> navPush<T>(
  BuildContext context,
  String name, {
  bool shouldPop = false,
  Object? extra,
}) async {
  if (shouldPop) {
    context.go('/');
  }
  if (extra != null) {
    return context.pushNamed(name, extra: extra);
  }
  context.goNamed(name, extra: extra);

  return null;
}

  navPush(
      context,
      'designList',
      extra: DesignListArguments(
        dpkId: dpk.id,
        isGrid: isGrid,
        designsFilterStore: designsFilterStore,
      ),
    );
        
```        
        
</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>
I don't use android studio. does not affect my flutter development.

![Screenshot 2023-09-05 at 2 17 28 PM](https://github.com/flutter/flutter/assets/79951156/8d61dd2d-f41e-4f9b-9573-591b0fad90b5)

</details>

**Comment by darshankawar** [comment]
@joseianpatrick 
Please don't post screenshots of the code, as it is not helpful to use. Please provide [complete runnable reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without any third party package implementation in properly formatted text, that shows the reported error.
