### ISSUE TITLE
Failed host lookup on android device in release mode

### ISSUE THREAD

**Issue by KostyaLocal** [flutter/flutter#134030]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Add http to dependencies
 2. Make an GET request to any host
3. Run "flutter build apk"
4. Copy apk on android device and run

### Expected results

Successful request

### Actual results

ClientException with SocketException: Failed host lookup

### Code sample

<details><summary>Code sample</summary>

```dart
main() async {
var client = HttpClient();
try {
var response = await _client.get("https://flutter.dev");
}
catch (e) {
 log(e.toString());
}


```

</details>

### Screenshots or Video

![photo_2023-09-05_13-38-01](https://github.com/flutter/flutter/assets/39090525/66e5371c-5626-41a5-91fa-4ca71d1f6d92)

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.13.2, on Microsoft Windows [Version 10.0.19044.3324], locale ru-RU)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.2)
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.81.1)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
```

</details>

**Comment by KostyaLocal** [comment]
Is there any way to completely disable ipV6 support in flutter/dart?

**Comment by dam-ease** [comment]
Hi @KostyaLocal. Thanks for filing this. Can you confirm you have internet permission enabled in your main `AndroidManifest.xml`? Kindly confirm you have
```
<uses-permission android:name="android.permission.INTERNET"/>
``` 
added to your `android/app/src/main/AndroidManifest.xml`

If yes, can you run flutter run --release -v and see if it shows any error in the log and provide the same here?

**Comment by KostyaLocal** [comment]
> Hi @KostyaLocal. Thanks for filing this. Can you confirm you have internet permission enabled in your main `AndroidManifest.xml`? Kindly confirm you have
> 
Yes, thank you, that was the point. I forgot to specify permission in the manifest.xml.
