### ISSUE TITLE
Consider adding a `--no-retry` flag to the devicelab `test` runner command 

### ISSUE THREAD

**Issue by andrewkolos** [flutter/flutter#134070]
Per [dev/devicelab/README.md](https://github.com/flutter/flutter/blob/a7997f606e32bc7e54778df50e003f975b85a536/dev/devicelab/README.md#L63), you can run device lab tests locally using `dev/devicelab/bin/test_runner.dart test -t {NAME_OR_PATH_OF_TEST}`.

Failed tests retry up to two times, for a total of three runs. When I'm modifying a devicelab test and debugging locally, I am usually only interested in running the test once, as failures are more likely to be caused by a change I made rather than a flake.

I'd like to add an option or flag to the `test` command to prevent retries. This would save me dev time and reduce the amount of output I need to sift through when running a devicelab test locally.

**Comment by christopherfujino** [comment]
what's the difference between `dev/devicelab/bin/test_runner.dart` and `dev/devicelab/bin/run.dart`? I always use the latter.

**Comment by andrewkolos** [comment]
> what's the difference between `dev/devicelab/bin/test_runner.dart` and `dev/devicelab/bin/run.dart`? I always use the latter.

Great question. Upon a cursory glance, they both seem to lead to a [`runTasks` call](https://github.com/flutter/flutter/blob/a7997f606e32bc7e54778df50e003f975b85a536/dev/devicelab/lib/framework/runner.dart#L27). While looking for when `test_runner` was introduced, I found [this comment from @CaseyHillers in late 2020](https://github.com/flutter/flutter/pull/72765/files#r547474515):

> I created a separate bin/test_runner.dart to reduce the complexity of the migration, and only added upload-metrics for now. Once we have migrated off of Cocoon agents, we can remove the global args code in bin/run.dart.

I'll have to reach out to Casey, and see if he knows more before I go spelunking. There's some tech debt here, I'm sure.

Anyway, even though `run.dart` has an `--exit` flag that provides the functionality I described in this issue, it doesn't seem to work--[it's not wired up in `runTasks`](https://github.com/flutter/flutter/blob/a7997f606e32bc7e54778df50e003f975b85a536/dev/devicelab/lib/framework/runner.dart#L68).
