### ISSUE TITLE
[Go Router Package] - Passing data as Map<String, dynamic> with query params issue

### ISSUE THREAD

**Issue by abualhamd** [flutter/flutter#134038]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I am using Go Router version 10.1.2, and I pass the data as a Map<String, dynamic> with query params, and when I try to fetch/get the data in the GoRoute Builder using state.uri.queryParameters I got the below error:
"type 'double' is not a subtype of type 'Iterable<dynamic>'"

### Expected results

Map<String, dynamic> 

### Actual results

"type 'double' is not a subtype of type 'Iterable<dynamic>'"

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @abualhamd,

Please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with steps to reproduce so that we can investigate this issue. 

Thank you
