### ISSUE TITLE
[Devicelab] Add Windows Arm64 machines to the non-staging pool

### ISSUE THREAD

**Issue by loic-sharma** [flutter/flutter#134083]
### Is there an existing issue for this?

- [X] I have searched the [existing infra issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-infra)

### Type of Request

feature request

### Infrastructure Environment

Devicelab

### What is happening?

Currently all Windows Arm64 Devicelab machines are in the staging pool. This prevents us from promoting Windows Arm64 Devicelab tests out of `bringup: true`.

**Comment by yusuf-goog** [comment]
We can move some machines over to prod. We would need to determine the right sizing between to have between the pools since we have limited capacity. Do you have recommendations on expected load for each pool?

**Comment by loic-sharma** [comment]
@yusuf-goog I would expect that Windows Arm64's load would be similar to the Windows x64 loads as we plan to run the same tests.

**Comment by keyonghan** [comment]
Is there any blockers here? These targets need to be enabled in prod if not flaky:
<img width="504" alt="Screenshot 2023-10-23 at 3 04 32 PM" src="https://github.com/flutter/flutter/assets/54558023/23ae49e9-de47-483c-a1b6-e2a6a3c7ae3e">

**Comment by keyonghan** [comment]
This is being blocked on https://github.com/flutter/flutter/issues/137104

**Comment by yusuf-goog** [comment]
https://github.com/flutter/flutter/issues/137104 does not seem to be an issue anymore. We can go ahead with the migration to prod pool

**Comment by keyonghan** [comment]
There are 58 (42 in framework, 5 in engine, 11 in packages) windows x64 targets running in post-submit and we have 60 x64 Windows VMs in prod pool.

IIRC, the arm64 bots are only available in devicelab, and are not supported as of now in GCP as VMs. This will limit the capacity. We have only 10 arm64 testbeds in staging.

@loic-sharma By `I would expect that Windows Arm64's load would be similar to the Windows x64 loads as we plan to run the same tests.`, do you mean all those host only tests? I am afraid we will not be able to cover all in short term. 

To unblock, I am proposing we enable 8 arm64 bots in prod to start validating in prod CI: https://chrome-internal-review.googlesource.com/c/infradata/config/+/6594395

**Comment by keyonghan** [comment]
This is done. https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=os&c=status&d=asc&f=os%3AWindows&f=cpu%3Aarm&f=pool%3Aluci.flutter.prod&k=pool&s=id

**Comment by stuartmorgan** [comment]
Did this regress? We noticed that the ARM flutter/plugins tests (which are still in bringup referencing this issue, which seems like a mistake?) are purple since yesterday, saying "Task did not start, no resource"

https://ci.chromium.org/ui/p/flutter/builders/staging/Windows_arm64%20windows-build_all_packages%20stable/516/overview

**Comment by keyonghan** [comment]
> Did this regress? We noticed that the ARM flutter/plugins tests (which are still in bringup referencing this issue, which seems like a mistake?) are purple since yesterday, saying "Task did not start, no resource"
> 
> https://ci.chromium.org/ui/p/flutter/builders/staging/Windows_arm64%20windows-build_all_packages%20stable/516/overview

DeviceLab move is WIP. There may be some capacity fluctuation. Seems now they have recovered.

**Comment by yusuf-goog** [comment]
This is again a balancing problem. https://ci.chromium.org/ui/p/flutter/builders/staging/Windows_arm64%20windows-build_all_packages%20stable/516/overview shows there is only 1 bot in staging that satisfies this.

The other bots were moved over to try or prod pool.
