### ISSUE TITLE
App functionality not working in background in ios

### ISSUE THREAD

**Issue by saifr383** [flutter/flutter#134003]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I want to run a code after 1 min when app is in background in ios for this i am running a timer but the timer stop working after 30 seconds when app goes to background in ios this functionality is working fine in android

### Actual results

the timer should continue to work after 30 seconds

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console



```

</details>

**Comment by stuartmorgan** [comment]
iOS suspends background processes; this is a fundamental system behavior, and is not specific to Flutter. See also discussion in https://github.com/flutter/flutter/issues/3671

Closing as this is not a Flutter bug.
