### ISSUE TITLE
`flutter ios --init` should use the project name from `flutter.yaml`

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#1340]
Right now the iOS project has "FlutterApplication" all over it.  The name of the .xcproj, the directory for resources, the target name, etc.  This doesn't follow the typical pattern of iOS projects (ones generated from XCode templates) of using the project name in all those spots.

This is non-critical, but eventually nice to have.

**Comment by chinmaygarde** [comment]
We now put all the user configurable stuff outside the Xcode project and launch via the command line tools.
