### ISSUE TITLE
Support reading text word by word, character by character, line by line, etc. on Android

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#13406]

**Comment by jonahwilliams** [comment]
It looks like this isn't supported on iOS?  Regardless, it looks like this would involve renaming the kMoveCursorForward/BackwardByCharacter commands to the android equivalents, and then encoding the granularity and extend selector into the argument.

**Comment by goderbauer** [comment]
Another idea Hixie and I had back when I added initial support for this was to just have separate actions for all the granularities.

**Comment by gmoraja** [comment]
@gspencergoog we're dealing with this issue in our app, any chance it can be prioritized?

TalkBack can switch between default, controls, links, and headings. We need to add characters and words.

**Comment by xster** [comment]
@goderbauer is this an Android specific embedding feature request from customer soldier?

**Comment by goderbauer** [comment]
We will have to figure out what information the accessibility bridge needs to provide to Android to enable this feature. It's possible that this will also require changes to the framework to provide that information to the bridge.

**Comment by jonahwilliams** [comment]
We already support moving by word and by character:

https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/view/AccessibilityBridge.java#L558

We could support by line easy enough by declaring that as splitting on `\n`.

**Comment by jonahwilliams** [comment]
See also: https://github.com/flutter/flutter/blob/210f4d83136a2eae773bda471db90ac27676f662/packages/flutter/lib/src/semantics/semantics.dart#L3107


And

https://github.com/flutter/flutter/blob/4af5fe2c370df36e5640c79d4080981879d0de69/packages/flutter/lib/src/rendering/editable.dart#L1265

**Comment by goderbauer** [comment]
> We already support moving by word and by character:

That's for _moving_ the cursor in a textfield. I believe this bug is about making TalkBack _read out_ any label word by word, character by character, etc.

**Comment by goderbauer** [comment]
Maybe I am wrong.

@gmoraja are you asking for support to move the cursor in a textfield by these granularities? Or for support to read out any kind of labels by these granularities?

**Comment by jonahwilliams** [comment]
Oh, I see sorry. I thought we already do that? Let me check

**Comment by jonahwilliams** [comment]
I guess not, I don't see any options in the LCM

**Comment by jonahwilliams** [comment]
It looks like we need to set https://developer.android.com/reference/android/view/accessibility/AccessibilityNodeInfo#MOVEMENT_GRANULARITY_WORD

If I'm understanding https://github.com/google/talkback/blob/9b1d5132b074174d02886faccf731e814d69363c/utils/src/main/java/input/CursorGranularity.java , its not just for text field movement.

**Comment by gmoraja** [comment]
@goderbauer we need it for any kind of label. We're able to do it in the text fields already.

**Comment by vick08** [comment]
@goderbauer I believe this issue was copied over from my original feature request in the repo now deprecated.
As mentioned above, Flutter for Android supports movement granularity inside edit fields only. We need to also support setMovementGranularity API for all UI elements. This does mean setting the granularity bits for the AccessibilityNodeInfos for those elements.
