### ISSUE TITLE
Huawei mate 60 pro released, will the framework adapt to the latest HarmonyOS NEXT?

### ISSUE THREAD

**Issue by sawwas** [flutter/flutter#134097]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

none

### Proposal

none。

**Comment by sawwas** [comment]
Huawei mate 60 pro released, Qualcomm announced the start of support for HarmonyOS, will the framework adapt to the latest HarmonyOS NEXT?

**Comment by yang-lile** [comment]
no, unnecessary.

**Comment by huycozy** [comment]
@sawwas [HarmonyOS isn't one of Flutter's supported platforms](https://github.com/flutter/flutter/issues/38437). If there are any issues with Android apps (native apps or apps built with Flutter), you should report them to the HarmonyOS developers for better support. Closing the issue.
