### ISSUE TITLE
Fuchsia SDK to Engine roll failing on license check

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#134042]
The last successful roll was a week ago in https://github.com/flutter/engine/pull/45216

The roller failed to create a CL with:
failed pre-upload step: Error when running dart license script: Command exited with exit status 1: /data/src/third_party/dart/tools/sdks/dart-sdk/bin/dart --interpret_irregexp lib/main.dart --src ../../.. --out /data/src/out/licenses --golden /data/src/flutter/ci/licenses_golden. At deps_local.go:174 git_common.go:160 git_checkout.go:77 autoroller.go:488 autoroller.go:444 state_machine.go:291 state_machine.go:53 state_machine.go:168 state_machine.go:914 state_machine.go:927 state_machine.go:933 autoroller.go:780 autoroller.go:338 util.go:383 cleanup.go:57 asm_amd64.s:1594

cc @arbreng

**Comment by jason-simmons** [comment]
Tried the roll locally and got this error:
```
Finding files...
../../../fuchsia/sdk/linux/packages/blobs/00299e332421e39f2a539e13dd9f47cd3cc3db669e5516d82b095d44859fc35f

failure: failed to handle ../../../fuchsia/sdk/linux/packages/blobs/00299e332421e39f2a539e13dd9f47cd3cc3db669e5516d82b095d44859fc35f
non-UTF8 data in ../../../fuchsia/sdk/linux/packages/blobs/00299e332421e39f2a539e13dd9f47cd3cc3db669e5516d82b095d44859fc35f
Original stack:
#0      _RepositorySourceFile._readFile (package:licenses/main.dart:79:7)
#1      new _RepositorySourceFile (package:licenses/main.dart:68:75)
#2      _RepositoryDirectory.createFile (package:licenses/main.dart:1061:14)
#3      _RepositoryDirectory.crawl (package:licenses/main.dart:966:43)
...
```

The latest `fuchsia/sdk/core/linux-amd64` CIPD package archive contains a set of `packages/blobs` files that were not there in previous archives.  The license script could exclude that path from the crawl.  Or possibly Fuchsia should regenerate the SDK if these files are not there intentionally.

**Comment by chinmaygarde** [comment]
This is being tracked by the Fuchsia team in https://b.corp.google.com/issues/299137892. There is nothing for us to do here but wait.

**Comment by cligh** [comment]
There is confirmation in b/299137892 that the new files are expected. Could we update the license script to exclude this path?

**Comment by zanderso** [comment]
Fixed by https://github.com/flutter/engine/pull/45498
