### ISSUE TITLE
Platform views not blurring properly with BackdropFilter on iOS

### ISSUE THREAD

**Issue by Reprevise** [flutter/flutter#134059]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Clone this repository https://github.com/Reprevise/flutter_ios_platform_view_blur_issue
2. Run the app
3. Tap on the "Open BackdropFilter dialog" button
4. See "Screenshots" section below

### Expected results

The blur should cover the platform view properly.

### Actual results

Not sure how to describe it, the platform view is being blurred, but it's almost like its separate? It also has a "glow" effect on top and below it, and it's much darker than the rest of the view.

### Code sample

GitHub repository: https://github.com/Reprevise/flutter_ios_platform_view_blur_issue

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![Simulator Screenshot - iPhone 14 Pro - 2023-09-05 at 14 04 53](https://github.com/flutter/flutter/assets/25782944/25cb6af6-7f33-4920-b8e7-a8bcd5a5d261)

</details>

### Logs

N/A

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.2, on macOS 13.5 22G74 darwin-arm64 (Rosetta), locale en-US)
    • Flutter version 3.13.2 on channel stable at /Users/ben/.puro/envs/stable/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (12 days ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (2 available)
    • iPhone 14 Pro (mobile) • 183E6448-C427-44C0-82B2-34EFB343B5A0 • ios          • com.apple.CoreSimulator.SimRuntime.iOS-16-4
      (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64 • macOS 13.5 22G74 darwin-arm64 (Rosetta)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

</details>

**Comment by huycozy** [comment]
Thanks for filing the issue. 
I see there's an open issue addressing the case you described https://github.com/flutter/flutter/issues/120028.

Closing this issue as a duplicate, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
