### ISSUE TITLE
Introduce multi-view runner APIs to desktop platforms

### ISSUE THREAD

**Issue by loic-sharma** [flutter/flutter#134152]
### Document Link

https://flutter.dev/go/desktop-multi-view-runner-apis

### What problem are you solving?

Currently, Flutter apps can only have a single view, and therefore, a single window. The Flutter framework recently added support for rendering into multiple views (see https://flutter.dev/go/multiple-views).

Although the Flutter framework can render into views, it cannot create views. Views are platform-specific concepts that are created and managed by each platform’s embedder. This design proposes new APIs to enable the native entrypoint and plugins to create multiple views.

This enables app developers to create multi-window apps by creating a native plugin.

This is also useful for add-to-app scenarios. Imagine a native Windows app would like to migrate to Flutter incrementally. This app might want to migrate both its sidebar and its profile screen to Flutter as two separate views. Today, this requires creating two Flutter engines with two separate widget trees, which makes sharing Flutter app state difficult.

This design does not introduce APIs to create/manage windows. This is out-of-scope for this document and will be covered in a subsequent design.

**Comment by darshankawar** [comment]
Adding `will need additional triage` label to direct this to correct team owner.
