### ISSUE TITLE
[Windows Arm64] Execution policies disallow running Powershell scripts

### ISSUE THREAD

**Issue by loic-sharma** [flutter/flutter#134182]
### Is there an existing issue for this?

- [X] I have searched the [existing infra issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-infra)

### Type of Request

bug

### Infrastructure Environment

LUCI Devicelab

### What is happening?

Please update Windows Arm64 machines to allow running PowerShell scripts from the internet. For example:

```
Set-ExecutionPolicy Unrestricted
```

For background, I'm updating Windows Devicelab tests to run on Arm64 machines. However, these Arm64 machines are failing to install Visual Studio due to the following error:

```
 c:\opt\s\w\ir\cache\vsbuild\install.ps1 : File C:\opt\s\w\ir\cache\vsbuild\install.ps1 cannot be loaded because 
 running scripts is disabled on this system. For more information, see about_Execution_Policies at 
 https:/go.microsoft.com/fwlink/?LinkID=135170.
 At line:1 char:1
 + c:\opt\s\w\ir\cache\vsbuild\install.ps1
 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     + CategoryInfo          : SecurityError: (:) [], PSSecurityException
     + FullyQualifiedErrorId : UnauthorizedAccess
```

Example failure: https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/loicsharma_google.com/d96efacb0ccd274798d5c18c9822903543bb1513d620ba9e50240e3ee2375905/+/build.proto?server=chromium-swarm.appspot.com

### Steps to reproduce

Use `led` to run the `luci.flutter.staging:Windows_arm64 hello_world_win_desktop__compile` builder. It will fail to install Visual Studio.

### Expected results

The Windows Arm64 machines should be able to run PowerShell scripts to install Visual Studio

**Comment by yusuf-goog** [comment]
applied `Set-ExecutionPolicy Unrestricted` to win-7..16.
