### ISSUE TITLE
Users wish to provide their own caching strategies for images

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#13419]
We have an advanced user that cares deeply about memory usage. They would like to experiment with different caching strategies for images.

For example, they would like to experiment with both FIFO and LRU strategies.

Is there a way for them to plug in their own cache strategy for images?

**Comment by sethladd** [comment]
cc @mjohnsullivan

**Comment by Hixie** [comment]
Fixed.

**Comment by Hixie** [comment]
(Fixed in https://github.com/flutter/flutter/pull/13409)

**Comment by sethladd** [comment]
Thanks for the head's up!

I found the ImageCache interface (https://docs.flutter.io/flutter/services/ImageCache-class.html)

I see that a developer can override `createImageCache`, but it wasn't immediately clear where I might want to do that. Any hints for people following along? :)

**Comment by Hixie** [comment]
They should create their own binding, probably by extending WidgetsFlutterBinding, and override the createImageCache method. Then, call the constructor for that binding class before calling `runApp`.

**Comment by sethladd** [comment]
Thank you! Very helpful.

**Comment by hasonguo** [comment]
@sethladd Do you have implement disk cache for flutter：DiskLruCache.If you had implemented DiskLruCache . I wish you can share it.Thanks
