### ISSUE TITLE
[Impeller] Add devicelab test to verify validation layers in debug builds

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#134175]
There is a print statement when the app loads that will say if vulkan is being used with validation layers.  We just need to check for that.

This can be doubled with a check that maybe runs the gallery and checks for validation layer errors.

**Comment by chinmaygarde** [comment]
Is this fixed by https://github.com/flutter/engine/pull/45682?

**Comment by gaaclarke** [comment]
> Is this fixed by [flutter/engine#45682](https://github.com/flutter/engine/pull/45682)?

Nope, this was blocked on that being fixed.  There will be a change to the flutter/flutter repo for this test.
