### ISSUE TITLE
[webview_flutter] [Android] After enabling VPN, other apps in mobile phone will use VPN, but webview version uses mobile phone's original network, what's the reason? How to solve?

### ISSUE THREAD

**Issue by scuti-haidv** [flutter/flutter#134124]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

import webview_flutter. Use flutter_vpn connect VPN.
After enabling VPN, open webview in app.

### Expected results

Webview will use VPN.

### Actual results

After enabling VPN, other apps in mobile phone will use VPN, but webview version uses mobile phone's original network, what's the reason?

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Hi @scuti-haidv 
Can you check if the issue also occurs by using 3rd VPN app and webview plugin only? (without using `flutter_vpn` plugin). If the issue still persists in that case, does the issue occur with native webview as well? (you can use this [Android webview native](https://github.com/huycozy/Android-Native-Webview) repo)

**Comment by scuti-haidv** [comment]
hi @huycozy 
I tried calling webview from native android. Even creating a child app within that app, the problem is still not resolved.

**Comment by scuti-haidv** [comment]
It's same to this issue [https://github.com/X-dea/flutter_vpn/issues/121]

**Comment by huycozy** [comment]
>Even creating a child app within that app

Can you be more specific on this? Do you mean Flutter module on Android native project?

>It's same to this issue [https://github.com/https://github.com/X-dea/flutter_vpn/issues/121]

If the issue is only reproducible when using `flutter_vpn` and not with other 3rd VPN apps, it is most likely a plugin issue rather than Flutter itself. So please follow up on that issue for further updates.

**Comment by scuti-haidv** [comment]
The situation is like this, I use webview_flutter to develop a browser, and then integrate flutter_vpn.

After turning on flutter_vpn connectIkev2EAP connection is successful, other software in the mobile phone use vpn and can access private.

However, the APP developed by myself still uses the original network of the mobile phone and cannot access Google. How can the software developed by myself also use VPN to access private

**Comment by huycozy** [comment]
Thanks for your response. But we need to verify if this issue is caused by `flutter_vpn` or not. The goal of this Github repo is to improve Flutter framework reporting bugs or feature requests. If the issue belongs to `flutter_vpn`, you should ask for support from its developers. 

So I would recommend you check if [webview_flutter](https://pub.dev/packages/webview_flutter) package is able to work with other 3rd VPN apps (by enabling VPN and accessing webview). If it does, perhaps this issue belongs to `flutter_vpn`.
