### ISSUE TITLE
Why can't I set the background color and margin of SliverGrid?

### ISSUE THREAD

**Issue by giantss** [flutter/flutter#134122]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

When I used `CustomScrollView`  `SliverGrid`, I found that the background color and margins could not be set separately for SliverGrid. I think this is a very common function, and I found that many developers have encountered similar problems. May I ask if the official plans to add relevant attributes?

### Proposal

<img width="669" alt="image" src="https://github.com/flutter/flutter/assets/13778798/37065bc0-bfd0-44ec-8c1e-f9b4eb49c4d6">

I have used CustomScrollView to realize almost all the effects in the picture above, but SliverGrid cannot set the background color and margins. I have tried various methods and finally failed to achieve it, so I had to give up this component in the end.

**Comment by farhanfadila1717** [comment]
@giantss for add margin you can wrap SliverGrid with SliverPadding. 

```dart
SliverPadding(
  padding: EdgeInsets.all(20),
  sliver: SliverGrid()
)
```

**Comment by giantss** [comment]
Thanks  @farhanfadila1717.
