### ISSUE TITLE
error while running flutter project on windows device 

### ISSUE THREAD

**Issue by muhammadmnyer** [flutter/flutter#134131]
i'm using flutter version 3.13.2 and dart version 3.1.0 with android studio giraffe , when i tried to run my flutter project on windows i got the folowing error :

`Launching lib\main.dart on Windows in debug mode...
Building Windows application...
CMake Error at flutter/ephemeral/.plugin_symlinks/printing/windows/CMakeLists.txt:15 (cmake_minimum_required):
  CMake 3.15 or higher is required.  You are running version
  3.14.19050301-MSVC_2
Exception: Unable to generate build files`

what i tried is to check the Cmake box in the sdk tools and to download the Cmake and adding it to the system enviroment path and the both ways did not work, then i tried to create a new flutter project to determine if the problem is specific to my existing project or a general issue with flutter and what i got is :

`C:\Users\hazem\StudioProjects\windows_testing\windows\runner\utils.cpp(54,43): error C2220:  warning treated as error - no 'object' file generated [C:\Users\hazem\StudioProjects\windows_testing\build\windows\runner\windows_testing.vcxproj]
C:\Users\hazem\StudioProjects\windows_testing\windows\runner\utils.cpp(54,43): warning C4018:  '>': signed/unsigned mismatch [C:\Users\hazem\StudioProjects\windows_testing\build\windows\runner\windows_testing.vcxproj]
Exception: Build process failed.`

any ideas how can i solve this problem ?
thanks for helping ..

**Comment by stuartmorgan** [comment]
The error is coming from the third-party `printing` package; you will need to contact its developers. They have chosen to require a higher version of CMake than Flutter does, which we [explicitly recommend against](https://github.com/flutter/flutter/blob/03fcfbef211c84b9d1050b1f67946be5ed6ffc0c/packages/flutter_tools/templates/plugin/windows.tmpl/CMakeLists.txt.tmpl#L1-L5).

**Comment by Saransh1650** [comment]
If you are using firebase in your project, try using it with android or ios emulator

**Comment by muhammadmnyer** [comment]
> If you are using firebase in your project, try using it with android or ios emulator

No I'm not using firebase , and the project is for windows not android or ios
