### ISSUE TITLE
New person perspective: Documentation is worded very confusingly. Examples given.

### ISSUE THREAD

**Issue by ScottS2017** [flutter/flutter#13412]
Hello,

I'm loving all the great work so far and can see how I'll be productive with this is no time! There is only one hitch. Whenever I use Cntl+Click to look at the documentation, I leave the app.dart file more confused than when I started. Here is why:

In short, the documentation appears to have many lines that are sentence fragments, rather than complete sentences. To someone who doesn't already know the context, who doesn't know what is being referred to, this is extremely confusing. Here are a few examples from the app.dart file:

Line 35:
/// An application that uses material design.

What about it? I don't know. Is there more to this sentence that would help me understand? What if we look at it and the next few lines as a set?

/// An application that uses material design.
///
/// A convenience widget that wraps a number of widgets that are commonly
/// required for material design applications. It builds upon a [WidgetsApp] by
/// adding material-design specific functionality, such as [AnimatedTheme] and
/// [GridPaper].

(EDIT: Is the first line a title?? If so, a colon would have made that clear. As it is, a period leaves the reader confused.)

So:
- *"An application that uses material design."* : This is the sentence fragment from line 35.
- *"A convenience widget that wraps a number of widgets that are commonly required for material design applications."* ... is what? I'm not sure. This is another sentence fragment that is an incomplete thought, or idea.
- *"It builds upon a [WidgetsApp] by adding material-design specific functionality, such as [AnimatedTheme] and [GridPaper]."* : This is more understandable. I can understand what it builds on and what specific functionality it adds... but I still have no idea what "it" is referring to.

If I make an assumption and join the first two then it seems to make sense:

*"An application that uses material design"* (is) *"A convenience widget that wraps a number of widgets that are commonly required for material design applications."*

However, I'm not comfortable about making assumptions about something I don't understand, and I'm reading the docs in the first place because I don't understand. Also, as Spock would say: "Logic would indicate that the two may not be joined as if they were a single sentence because the two fragments are separated by more than simply a period. They are, in fact, also separated by an empty line, as if they were completely different paragraphs."

Suggestion: Please write only in complete ideas or thoughts. If you were expecting me to say sentences then I understand why but the real point here has nothing at all to do with grammar. It has to do with the fact that a person reading these docs today can easily be left feeling as if they're reading a bunch of half-finished thoughts or ideas that don't make any sense... and this has been my personal experience. This is why I'm taking the time to report this as an issue.

Because to those of us who are trying to learn Flutter, who are trying to understand how all these pieces fit together, it's a monumental issue. Being able to understand the docs is what enables us to use Flutter at all; and not being able to understand them is what keeps us from being able to use it.

Thanks for taking the time to read this and thanks for all the great work! I'm loving what I can understand so far and I'm excited about learning and being able to do more!

Scott Stoll

**Comment by sethladd** [comment]
Thanks for the feedback! When you say "Whenever I use Cntl+Click to look at the documentation" I assume you mean, "with IntelliJ or Android Studio" ?

When you Cntl+Click, can you provide a screenshot with what you see? I'm curious if only the first line of the API docs are displayed.

Thank you for the additional screenshot.

**Comment by ScottS2017** [comment]
Sorry for the delay in response, I didn't see that you had replied.

I'm using IntlliJ. A screenshot of what I see in the tutorial might help but one of my screen won't, but I can tell you exactly what is happening. If I go to any number of key terms and CNTL+Right click, IntelliJ opens a new file in a new tab and places the carrot (cursor) in that term's definition. For Example: 

CNTL+Click on crossAxisAlignment opens the file basic.dart and places the carrot on line # 3569.
CNTL+Click on StatelessWidget opens framework.dart and places the carrot on line #600
CNTL+Click on controller opens text_field.dart and places the carrot on line #123 

In the tutorial I'm watching, the presenter says that he is using control click on a Mac to get IntelliJ to show a drop down list of possible choices. I'm enclosing a screenshot of what he's seeing. I can't seem to find a way to make my configuration do this, and it would be extremely helpful. I'm on Linux. Here is the screenshot of the choices he's getting, supposedly when he uses CNTL+Click on a Mac:

![flutterissuescreenshot](https://user-images.githubusercontent.com/32370328/33799243-e16a6f10-dcf5-11e7-81f1-309f0ec4bd5b.png)

**Comment by ScottS2017** [comment]
Also, some other unexpected behavior from IntelliJ is this:

```body: new Container(
        child: new Center(
          child: new Column(
            children: <Widget>[
              new Text("Placeholder Text") //Missed a comma here, all code below this is gray "dead code"
              new RaisedButton(child: new Text("Press me!"))
            ],
          ),
        ),
      ),```

When we miss a ; ] } or ) we get told that, but if we miss a , in a list like this, it just kills all the code below it. One would expect to get a reminder to add a comma, just like all the other punctuation.

**Comment by sethladd** [comment]
Hi @ScottS2017 , could you help us by opening a new issue for the behavior when missing a ; ] } ?

Thank you!

**Comment by ScottS2017** [comment]
Done, thanks Seth.

**Comment by stevenroose** [comment]
I don't think the mentioned wording is confusing.

**Comment by zoechi** [comment]
https://www.dartlang.org/guides/language/effective-dart/documentation#do-make-the-first-sentence-a-standalone-paragraph should explain why the first sentence looks like it does.

**Comment by Hixie** [comment]
@ScottS2017 Does it make more sense in the context of the API docs at https://docs.flutter.io/ ?

**Comment by ScottS2017** [comment]
That's much more clear, yes.

Sorry for the delay, I've been crazy busy with everything from dealing with a wrist injury to my gf's cousin competing in the Olympics (yea, it's been tense around here).

I realized what the issue is. Basically, the comments don't have a header telling you where a new section begins. If you're familiar with that setup then you don't know why others have an issue but to others it looks like you changed chapters in mid-paragraph and didn't bother to tell the reader.

The issue I was having was that I'd keep reading from the comments about one class right into the next and not realize things had changed because she ended up finishing 13th in the qualifiers and I forgot to get sausage at the store so it makes it really hard to figure out what's going on since the docs are supposed to be explaining this stuff to people who aren't familiar with it.

Kind of like that.

**Comment by Hixie** [comment]
Ah, yeah. That makes sense.

I'm not sure there's really much we can do about it... it's pretty standard practice to have documentation start with a noun phrase (not a complete sentence), describing the member being documented. And since the documentation in Dart comes before the member being documented, you sort of have to read the Dart code first then jump back up to read the documentation.

You can basically assume that every sentence fragment starts with "The member below is...". If we actually added that text everywhere it would become very hard to read the documentation since everything would start with "The member below is", which would be dizzying.

I recommend reading the docs at docs.flutter.io instead of in the IDE, if that is easier to understand.

I'm going to close this bug because I don't really see what we can do it improve matters, but if you have any ideas please don't hesitate to file a new bug for and we will definitely consider them!
