### ISSUE TITLE
How do I build a final ipa from `flutter ios --init`?

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#1341]
It does not seem to be documented at:
https://github.com/flutter/engine/wiki/Flutter-Apps-on-iOS
(which probably should move to flutter/flutter at this point).

All I can seem to do is build a Runner.app, which doesn't have my correct icon, etc.

Presumably there are multiple targets in this XCode proj I can select, one of which produces my proper .ipa?  I'm not familiar enough with this modern XCode to tell.

@chinmaygarde

**Comment by chinmaygarde** [comment]
For final deployment to the App Store, you would have to open Xcode then `Product -> Archive`. I will document this.

**Comment by eseidelGoogle** [comment]
Archive is blurred out for the Application Scheme/Target in the ios --init
project I just generated.

**Comment by chinmaygarde** [comment]
`Archive` is only selectable if you target an actual device or a generic device target. https://monosnap.com/file/VnnXMjwmQYP64bzJ8Pf4SmNf4ZVGDO

**Comment by eseidelGoogle** [comment]
I see.  So maybe Runner.app is my actual app (not the universal runner, etc.) and what I'm really asking for is #1340?  Because then I would see MaterialGallery.app instead of Runner.app?

**Comment by chinmaygarde** [comment]
Yeah, https://github.com/flutter/flutter/issues/1340 seems about right. Should I close this ticket?

**Comment by sethladd** [comment]
Opened a doc request here: https://github.com/flutter/website/issues/151
