### ISSUE TITLE
Unexpected TextSpan.recognizer behaviour

### ISSUE THREAD

**Issue by Waqar144** [flutter/flutter#134141]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

In my app I am trying to install TextSpan with onTap gesture on each word in the text. To do so I split the words by a special character and then pass the wordIndex to the callback so that I know which word was tapped. However, when I tap the word I get the same index every time.

Sample Code:

```dart
class _MyHomePageState extends State<MyHomePage> {
  void myOnTap(int word) {
    print("Tapped word: $word");
  }

  List<TextSpan> getSpans() {
    String line = "This is a line";
    List<String> words = line.split(' ');
    List<TextSpan> spans = [];
    int index = 0;
    for (final w in words) {
      spans.add(
        TextSpan(
          text: w,
          recognizer: TapGestureRecognizer()
            ..onTap = () {
              myOnTap(index);
            },
        ),
      );
      spans.add(const TextSpan(text: ' '));
      index = index + 1;
    }
    return spans;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text.rich(
              TextSpan(children: getSpans()),
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
    );
  }
}
```

### Expected results

When the above sample code is run, I expect that when I tap a word I get the index for that word. Instead I get `4` every time as if the index was stored by reference. The current work around I have is to do something like:

``` dart
      for (final w in words) {
        int index = words.indexOf(w);
        // add span
      }
```
If I do the above, I get the correct index every time.

### Actual results

I get `4` instead of the correct index

### Code sample

<details><summary>Code sample</summary>

```dart
class _MyHomePageState extends State<MyHomePage> {
  void myOnTap(int word) {
    print("Tapped word: $word");
  }

  List<TextSpan> getSpans() {
    String line = "This is a line";
    List<String> words = line.split(' ');
    List<TextSpan> spans = [];
    int index = 0;
    for (final w in words) {
      spans.add(
        TextSpan(
          text: w,
          recognizer: TapGestureRecognizer()
            ..onTap = () {
              myOnTap(index);
            },
        ),
      );
      spans.add(const TextSpan(text: ' '));
      index = index + 1;
    }
    return spans;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text.rich(
              TextSpan(children: getSpans()),
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.13.1, on Manjaro Linux 6.1.49-1-MANJARO, locale en_US.UTF-8)
    • Flutter version 3.13.1 on channel stable at /home/waqar/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e1e47221e8 (2 weeks ago), 2023-08-22 21:43:18 -0700
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/waqar/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /home/waqar/Downloads/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 15.0.3 (https://github.com/llvm/llvm-project.git 4a2c05b05ed07f1f620e94f6524a8b4b2760a0b1)
    • cmake version 3.27.4
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[✓] Android Studio (version 2022.2)
    • Android Studio at /home/waqar/Downloads/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Manjaro Linux 6.1.49-1-MANJARO

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

**Comment by Karthikeyanarla** [comment]
@Waqar144, are you expecting to run the getSpan() function every time you click the text?

I am asking for the following reasons.

The function only runs (single time) when the MyHomePage widget initializes, i.e., before the MyHomePage screen appears on the screen. 

`for (final w in words) {
  '''' ''''
}`
It is executed before the widget renders.
Therefore, after the screen renders 

`TextSpan(children: getSpans())` is equal
`TextSpan(children: [Widget1, Widget2, Widget3, ... WidgetN])`
n is the length of the word. So, the **index** value = N(4)
So, 
Widget contains the second index value = 4
I hope you understand.

**Comment by Karthikeyanarla** [comment]
> @Waqar144, are you expecting to run the getSpan() function every time you click the text?
> 
> I am asking for the following reasons.
> 
> The function only runs (single time) when the MyHomePage widget initializes, i.e., before the MyHomePage screen appears on the screen.
> 
> `for (final w in words) { '''' '''' }` It is executed before the widget renders. Therefore, after the screen renders
> 
> `TextSpan(children: getSpans())` is equal `TextSpan(children: [Widget1, Widget2, Widget3, ... WidgetN])` n is the length of the word. So, the **index** value = N(4) So, Widget contains the second index value = 4 I hope you understand.



Overall, I want to convey. It is the way the dart/flutter screen rendering works. You can change the TextSpan widget to an elevated button or something. You can see the same situation.

**Comment by Waqar144** [comment]
> @Waqar144, are you expecting to run the getSpan() function every time you click the text?

No.

I expect that the index value is what I stored i.e., `[0] = This,  [1] = is,  [2] = a, [3] = line`

**Comment by Waqar144** [comment]
> Overall, I want to convey. It is the way the dart/flutter screen rendering works. You can change the TextSpan widget to an elevated button or something. You can see the same situation.

I think you didn't understand the issue at all.

The issue isn't with rendering. The issue is that when I tap the text, I expect the right index in the callback. Currently, no matter which word I tap, I get `index == 4` printed in the handler.

**Comment by Karthikeyanarla** [comment]
Sir, it won't work in that way. if you want to bind the index to the word, try something different. 

It is the screen render flow of Dart/Flutter Framework. 
Write a print (print(index)) statement in the for loop. 
to see the value of the index exactly after running the code. You can see 1,2,3,4 prints on the screen. Indicating the text span widgets are built.
Now, the index = 4. It would be always 4. 
As there is no binding relation between the index and the word.
 Hope this can clear you.
 
 You can check with ElevatedButton, TextButton, or anything else instead of textspan.

**Comment by Waqar144** [comment]
> As there is no binding relation between the index and the word.

Why does that matter? I am just using the index in the `onTap` callback. What does that have to do anything with render flow? It does work if I get the index with `index = words.indexof(currentWord)` after all.

**Comment by Karthikeyanarla** [comment]
`index = words.indexof(currentWord)` is in the local scope for the onTap function.
That means you are creating a new variable, which means you are allocating a new memory location every time the loop executes.
Dart is a lexical compiler, meaning a function's variable binds to the nearest name/variable.

While the thing you are thinking unexpected behavior is due to
`index` being global for the onTap function (at least for this function).
Therefore, the same variable or memory location is used for every onTap callback function.

It's not an issue. It is how a lexical compiler works. Dart is a lexical compiler.

**Comment by Waqar144** [comment]
I believe it's called 'reference semantics'. I was under the impression that ints were value types.
