### ISSUE TITLE
TabBarView to take a IndexedWidgetBuilder, as alternative to list of children

### ISSUE THREAD

**Issue by j4k0bk** [flutter/flutter#13416]
I want to make an "infinite" TabBarView, but it is impossible with the children attribute (setting childCount unrealistic high could simulate this).

A solution could be to have TabBarView take an IndexedWidgetBuilder as argument as an alternative to the children attribute, and build children when needed.

**Comment by Hixie** [comment]
This is probably a use case that is contrary to the material design guidelines, so it's not something I would expect Flutter to support in the near term (if ever).

However, you can totally implement that in your app if you want. I would recommend starting by cloning the tabs.dart file into your project, so that you can adjust the relevant classes as you desire.

**Comment by Hixie** [comment]
(Specifically, the material UI guidelines encourage as few tabs as possible.)

**Comment by j4k0bk** [comment]
A use case for this could be a calendar view, where the user swipes back and forth between weeks/months/years. Or any use case basically where the content is dynamically generated would need an indexed build callback.

Btw. this has nothing to do with tabs - i am only refering to the TabBarView which, according to Flutters own docs, is only "Typically used in conjunction with a TabBar."

**Comment by j4k0bk** [comment]
My current hack to achieve this is to extend ListBase and override the [] operator, and within it call an IndexedWidgetBuilder.

**Comment by Kripner** [comment]
@j4k0bk Neat. I've tried implementing it and it doesn't seem to work. Could you please share your code?

**Comment by Kripner** [comment]
My best solution involves picking some large number and passing it to the tab controller & tab bar view. Does your solution avoid that?

**Comment by Hixie** [comment]
I'm going to close this based on my comments above.
