### ISSUE TITLE
Can not run windows desktop release in other directory.

### ISSUE THREAD

**Issue by ysdxz207** [flutter/flutter#134105]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1、create a windows desktop app
2、run flutter build windows command.
3、run build\windows\runner\Release\myapp.exe，it work well
![image](https://github.com/flutter/flutter/assets/4596561/ccc458dd-5f54-4e65-a76d-495f7af0f217)

4、copy Release folder to d:\Release，run d:\Release\myapp.exe,it can not working,It seems like not loading ***_plugin.dll
![image](https://github.com/flutter/flutter/assets/4596561/651f6e03-96ae-4451-9a16-12b2c1d0d0e3)

5、I tried copy all the project, only keep .dart_tool/package_config.json and build folder,it work well,when I delete package_config.json file,it not working.

myporoject
       -.dart_tool
              -package_config.json
       -build
             -windows
                  -runner
                       Release

![image](https://github.com/flutter/flutter/assets/4596561/67c9ccf0-a686-41b2-9804-297f2bdefbc3)

### Actual results

can not run my app Release in other place

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by ysdxz207** [comment]
@huycozy 
`not working`:  it seems like all the plugins not working, can not load data from sqlite,hot key not working,tray manager can not show a tray icon...

![image](https://github.com/flutter/flutter/assets/4596561/cb3817cb-8096-4bee-b697-c4dd91ab3805)

```
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[√] Flutter (Channel stable, 3.13.2, on Microsoft Windows [版本 10.0.22621.2134], locale zh-CN)
    • Flutter version 3.13.2 on channel stable at C:\env\flutter_windows_v1.12.13+hotfix.9-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (13 days ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\hupubao\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33815.320
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2023.2)
    • IntelliJ at C:\Users\hupubao\AppData\Local\Programs\IntelliJ IDEA Ultimate
    • Flutter plugin version 75.1.4
    • Dart plugin version 232.9559.10

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.22621.2134]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 116.0.5845.141
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 115.0.1901.203

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

**Comment by huycozy** [comment]
I checked this issue on a minimal Flutter sample code but can't reproduce it. I copied `Release` folder to another location and can run the exe file normally. 

I think this could be caused by using some plugins above. You should narrow down the issue by removing the usage of 3rd party plugins/packages one by one, unrelated/unaffected pages, and isolating the issue until find the causing plugin. 

Since you mentioned `sqlite`, please take a look at this issue https://github.com/flutter/flutter/issues/62020 and find any hints there. Furthermore, it could be a plugin's issue.

**Comment by ysdxz207** [comment]
Thank you very much,I will check this.
