### ISSUE TITLE
TabBar widget's divider error

### ISSUE THREAD

**Issue by Sarzn** [flutter/flutter#134189]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

In the paint function of _IndicatorPainter class, there is a judgment on whether there is a divider：

```dart
 if (showDivider && dividerHeight! > 0) {
      final Paint dividerPaint = Paint()
        ..color = dividerColor!
        ..strokeWidth = dividerHeight!;
      final Offset dividerP1 =
          Offset(0, size.height - (dividerPaint.strokeWidth / 2));
      final Offset dividerP2 =
          Offset(size.width, size.height - (dividerPaint.strokeWidth / 2));
      canvas.drawLine(dividerP1, dividerP2, dividerPaint);
    }
```    

Based on this judgment, if the theme.useMaterial3 is true and widget.isScrollable is false, there will be no divider.
But, in build function of _TabBarState, there is another _DividerPainter:
   
```dart
 tabBar = CustomPaint(
          painter: _DividerPainter(
            dividerColor: widget.dividerColor ??
                tabBarTheme.dividerColor ??
                _defaults.dividerColor!,
            dividerHeight: widget.dividerHeight ??
                tabBarTheme.dividerHeight ??
                _defaults.dividerHeight!,
          ),
          child: Align(
            heightFactor: 1.0,
            alignment: effectiveAlignment,
            child: tabBar,
          ),
        );
``` 

Is this correct? Do these two places duplicate the handling of divider?

### Expected results

To hide the divider, it is necessary to set widget.dividerHeight to 0

### Actual results

To hide the divider, it is necessary to set widget.dividerHeight to 0

### Code sample

          TabBar(
            indicatorColor: Colors.lightBlue,
            indicatorSize: TabBarIndicatorSize.label,
            indicatorWeight: 5,
            indicatorPadding: const EdgeInsets.only(bottom: 8),
            isScrollable: true,
            tabAlignment: TabAlignment.start,
            dividerHeight: 0,    // This line of work is mandatory
            controller: _controller,
            tabs: [
              Tab(
                icon: Icon(
                  Icons.flight,
                  color: _selectedIndex == 0 ? Colors.lightBlue : null,
                ),
              ),
              Tab(
                icon: Icon(
                  Icons.directions_transit,
                  color: _selectedIndex == 1 ? Colors.lightBlue : null,
                ),
              ),
              Tab(
                icon: Icon(
                  Icons.directions_car,
                  color: _selectedIndex == 2 ? Colors.lightBlue : null,
                ),
              ),
            ],
          ),

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by dam-ease** [comment]
Hi @Sarzn. Not sure I fully understand this. Are you currently experiencing an issue hiding the divider?
