### ISSUE TITLE
Engine to framework rolls failing on .ci.yaml validation

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#134261]
### Is there an existing issue for this?

- [X] I have searched the [existing infra issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-infra)

### Type of Request

bug

### Infrastructure Environment

GitHub

### What is happening?

The last two engine rolls have failed (or are failing) on ci.yaml validation:

https://github.com/flutter/flutter/pull/134257
https://github.com/flutter/flutter/pull/134259

### Steps to reproduce

Step 1:
Step 2:
..
Step n:

### Expected results

I expect to see X when Y is finished.

**Comment by zanderso** [comment]
Looks like the next roll might be succeeding? https://github.com/flutter/flutter/pull/134260

**Comment by yusuf-goog** [comment]
closing for now since its resolved. reopen if needed
