### ISSUE TITLE
Missing listeners (eg. onSubmitted) for SearchController view's input text

### ISSUE THREAD

**Issue by mstagitis** [flutter/flutter#134211]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I am adding a SearchAnchor/SearchBar to my Flutter app and noticed that there is no available way to detect when a user has submitted a query (_onSubmitted_) from the associated SearchController's view.

I am able to provide an _onSubmitted_ listener for the SearchBar itself [(thanks to this change)](https://github.com/flutter/flutter/pull/127845) which is useful for detecting when a user submits a query from within the SearchBar itself. However, when the SearchController's view is open I have no way of passing this same listener in to listen to the input used in the view.

It appears that the only way to detect a new query from within the SearchController's view is to add a button and force the user to explicitly click it (rather than using the 'Done' key on the keyboard).

Here is a minimal snippet:

```
  final SearchController _controller = SearchController();

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SearchAnchor(
        searchController: _controller,
        builder: (BuildContext context, SearchController controller) {
          return SearchBar(
            controller: controller,
            leading: const Icon(Icons.search),
            onTap: () {
              _controller.openView();
            },
            onChanged: (_) {
              _controller.openView();
            },
            onSubmitted: (value) {
              // This only listens to the search bar, NOT the input in the controller's view!
            },
          );
        },
        suggestionsBuilder:
            (BuildContext context, SearchController controller) {
          return [];
        });
  }
```

--------------------------

`flutter doctor -v` output:

```
[✓] Flutter (Channel stable, 3.13.2, on macOS 13.1 22C65 darwin-arm64, locale en-US)
    • Flutter version 3.13.2 on channel stable at /opt/homebrew/Caskroom/flutter/2.0.1/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (2 weeks ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc1)
    • Android SDK at /Users/mstagitis/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0-rc1
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.179

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

### Proposal

I propose that the SearchController's API be extended to allow an _onCompleted_ listener (and maybe others like _onChanged_?) to be passed in through to it's child text field. I don't see any reason that the contained text field's API should be hidden from users of the SearchController view.

**Comment by dam-ease** [comment]
Hi @mstagitis. Thanks for proposing this. Noticed your proposal seems quite similar to https://github.com/flutter/flutter/issues/132915, can you check this out?

**Comment by mstagitis** [comment]
@dam-ease - Thanks for the response! I read through that issue and I believe we are pointing out the same gap.

I think the existing widgets are working as intended, but SearchController is missing some crucial functionality. Please advise on how best to push this feature request forward! Thank you! 😄
