### ISSUE TITLE
Remove mac-328-g140 from service

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#134226]
### Is there an existing issue for this?

- [X] I have searched the [existing infra issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-infra)

### Type of Request

infra task

### Infrastructure Environment

LUCI, Github, Cocoon scheduler, Autosubmit, etc...

### What is happening?

Remove https://chromium-swarm.appspot.com/bot?id=mac-328-g140 from service, since it seems to be causing a lot of errors.

Reference:
https://github.com/flutter/flutter/issues/134222

\cc @reidbaker @zanderso

**Comment by zanderso** [comment]
Thanks. Confidence that this is the only machine with this issue is somewhat low, though.
