### ISSUE TITLE
Hi @arpit-it

### ISSUE THREAD

**Issue by Dhirenvinay** [flutter/flutter#134289]
Still showring the error       
C:\flutter_windows_3.3.3-stable\flutter\bin\flutter.bat --no-color pub get

  ╔════════════════════════════════════════════════════════════════════════════╗
  ║                 Welcome to Flutter! - https://flutter.dev                  ║
  ║                                                                            ║
  ║ The Flutter tool uses Google Analytics to anonymously report feature usage ║
  ║ statistics and basic crash reports. This data is used to help improve      ║
  ║ Flutter tools over time.                                                   ║
  ║                                                                            ║
  ║ Flutter tool analytics are not sent on the very first run. To disable      ║
  ║ reporting, type 'flutter config --no-analytics'. To display the current    ║
  ║ setting, type 'flutter config'. If you opt out of analytics, an opt-out    ║
  ║ event will be sent, and then no further information will be sent by the    ║
  ║ Flutter tool.                                                              ║
  ║                                                                            ║
  ║ By downloading the Flutter SDK, you agree to the Google Terms of Service.  ║
  ║ Note: The Google Privacy Policy describes how data is handled in this      ║
  ║ service.                                                                   ║
  ║                                                                            ║
  ║ Moreover, Flutter includes the Dart SDK, which may send usage metrics and  ║
  ║ crash reports to Google.                                                   ║
  ║                                                                            ║
  ║ Read about data we send with crash reports:                                ║
  ║ https://flutter.dev/docs/reference/crash-reporting                         ║
  ║                                                                            ║
  ║ See Google's privacy policy:                                               ║
  ║ https://policies.google.com/privacy                                        ║
  ╚════════════════════════════════════════════════════════════════════════════╝

Running "flutter pub get" in learn_dart...                      
The current Dart SDK version is 2.18.2.

Because learn_dart requires SDK version >=3.0.6 <4.0.0, version solving failed.
pub get failed (1; Because learn_dart requires SDK version >=3.0.6 <4.0.0, version solving failed.)
Process finished with exit code 1

   Hi @arpit-it 
as you can see from your` flutter doctor -v`
the dart version of `flutter channel stable` is `2.5.0`;

even in the channel dev the dart version in `2.7.0-dev.2.1.` which is < than `2.7.0`.

If you need the latest version of Dart  you may want to run
`
 flutter channel master
`
`
 flutter upgrade
`
Does this solution solve the issue?
thank you

_Originally posted by @iapicca in https://github.com/flutter/flutter/issues/46413#issuecomment-563199351_

**Comment by stuartmorgan** [comment]
> The current Dart SDK version is 2.18.2.
> 
> Because learn_dart requires SDK version >=3.0.6 <4.0.0, version solving failed.

As indicated in the error message, you need a newer version of Flutter/Dart to run the project you are trying to run.

Closing as expected behavior.
