### ISSUE TITLE
 Will flutter support functions similar to aspectJ in Java to implement AOP?

### ISSUE THREAD

**Issue by 34sir** [flutter/flutter#134282]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I now need to implement a non-intrusive buried point system, so I need dart to support AOP

### Proposal

I need flutter support functions similar to aspectJ in Java to implement AOP

**Comment by danagbemava-nc** [comment]
There was some discussion around this in https://github.com/flutter/flutter/issues/36738. 

But it seems like some work will have to be done in dart itself. You should probably file an issue on the dart-sdk repo. 

Closing from here. 

Thank you
