### ISSUE TITLE
"Debugging with Flutter" doesn't mention how to use Observatory with IDE

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#13425]
We did a search for "observatory intellij flutter" and https://flutter.io/debugging/#dart-observatory-statement-level-single-stepping-debugger-and-profiler was the first result.

We wonder if we can link over to how to Observatory w/ IDE, from the main Debugging docs.

Thanks!

**Comment by sethladd** [comment]
cc @mit-mit

**Comment by zoechi** [comment]
Please don't forget to mention debugging tests.
Just 2h ago on Gitter

> Oh perfect
> `--start-paused` is the one

**Comment by mit-mit** [comment]
In what context did this come up, i.e. to solve which debugging problem? I doubt that the majority of our developers are going to see much value from this for regular debugging. For that we recommend using the built-in debugging in our IDEs.

cc @devoncarew

**Comment by zoechi** [comment]
It was about VSCode. I don't know if VSCode provides some debugger integration.

**Comment by mit-mit** [comment]
If you want classic step-based debugging, I would much recommend IntelliJ IDEA with flutter plugin over observatory.

**Comment by zoechi** [comment]
Sure, but some are purists and don't want to download full IDEs just to try a new framework.
I don't care for myself, but I was involved in that discussion and thought it might be a good idea to mention it that no IDE is necessary.

**Comment by DanTup** [comment]
> It was about VSCode. I don't know if VSCode provides some debugger integration.

It absolutely does! :) You just open a Flutter project and hit `F5` or choose to run from the Debug sidebar. All of the usual things should work (breakpoints, watch window, expression evaluation in debug console, evaluations on hovers, stack traces).

I've seen a lot of youtube videos of people using Dart Code and then running flutter from the terminal and missing out on all the debugger stuff (and hot-reload-on-save, etc.) so if you see anyone having troubles with it please feel free to have them ping me or jump in Dart Code Gitter.

One of the things that might be confusing this is that if the flutter projects is in a sub-folder it doesn't work properly. I was hoping people would use Code's multi-root support but I've been convinced that it doesn't work great in all situations, so I'm planning on revisiting this (hopefully for vNext in a few weeks).

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1989](https://github.com/flutter/website/issues/1989) via [**ZenHub**](https://www.zenhub.com/)
