### ISSUE TITLE
Application developed using Flutter  display garbled Chinese fonts on linux arm64 architecture

### ISSUE THREAD

**Issue by wuzhaohui100** [flutter/flutter#134287]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

linux  arm64 architecture

git clone https://github.com/flutter/gallery.git

cd gallery
flutter pub get
flutter run -d linux
![image](https://github.com/flutter/flutter/assets/108720447/06b02a48-b7ac-488c-8a5e-abd5928a592b)

### Expected results

![image](https://github.com/flutter/flutter/assets/108720447/70e917ed-108e-492f-98d5-802110446922)

### Actual results

![image](https://github.com/flutter/flutter/assets/108720447/6cc9bf0e-1933-43d1-bd72-fdceaf28b5d1)

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by wuzhaohui100** [comment]
> 你好@wuzhaohui100 据我所知，这个问题最适合画廊团队。[请在专用存储库](https://github.com/flutter/gallery/issues)中打开该问题。
> 
> 结束，因为这不是 Flutter 框架本身的问题。如果您不同意，请提供[完整且最小的可重现代码示例](https://stackoverflow.com/help/minimal-reproducible-example)，我将重新打开该示例进行调查。谢谢你！

I don’t think it’s a problem with the application itself, because I have compiled many applications developed by flutter, and the Chinese characters are all displayed as garbled characters on the arm64 platform.
For example：
https://github.com/localsend/localsend/issues/101

**Comment by huycozy** [comment]
Re-opening the issue for further discussion. Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Also, please provide the output of `flutter doctor -v` as well.

Also, when you said "garbled Chinese fonts", do you mean the characters are square? (If so, this looks similar to https://github.com/flutter/gallery/issues/540)
![image](https://github.com/flutter/flutter/assets/104349824/58eed9c7-b4d6-4674-bcfa-943545bb5e8d)

**Comment by wuzhaohui100** [comment]
> 重新打开该问题以进行进一步讨论。请提供[完整且最小的可重现代码示例](https://stackoverflow.com/help/minimal-reproducible-example)，其中不包含第 3 方插件或复杂的生产代码。另外，请提供输出`flutter doctor -v`。
> 
> 另外，你说的“中文字体乱码”是指汉字是方形的吗？（如果是这样，这看起来类似于[flutter/gallery#540](https://github.com/flutter/gallery/issues/540)） ![图像](https://user-images.githubusercontent.com/104349824/267214978-58eed9c7-b4d6-4674-bcfa-943545bb5e8d.png)

yes that's it
![image](https://github.com/flutter/flutter/assets/108720447/0a7a1758-ea71-4d81-b549-55929a33c5b9)

**Comment by wuzhaohui100** [comment]
> 重新打开该问题以进行进一步讨论。请提供[完整且最小的可重现代码示例](https://stackoverflow.com/help/minimal-reproducible-example)，其中不包含第 3 方插件或复杂的生产代码。另外，请提供输出`flutter doctor -v`。
> 
> 另外，你说的“中文字体乱码”是指汉字是方形的吗？（如果是这样，这看起来类似于[flutter/gallery#540](https://github.com/flutter/gallery/issues/540)） ![图像](https://user-images.githubusercontent.com/104349824/267214978-58eed9c7-b4d6-4674-bcfa-943545bb5e8d.png)

This is the simplest demo:
[flutter_demo.tar.gz](https://github.com/flutter/flutter/files/12592250/flutter_demo.tar.gz)

The demo generation process is as follows：
flutter create flutter_demo
cd flutter_demo
Modify lib/main.dart file，Modify line 109
flutter run -d linux

The effect is as follows：
x86_64
$ flutter doctor -v
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[✓] Flutter (Channel beta, 3.14.0-0.2.pre, on Kylin V10 SP1 5.4.18-85-generic, locale zh_CN.UTF-8)
    • Flutter version 3.14.0-0.2.pre on channel beta at /home/wzh/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 123453dc41 (12 天前), 2023-08-31 13:50:44 -0700
    • Engine revision b93c76ab94
    • Dart version 3.2.0 (build 3.2.0-42.2.beta)
    • DevTools version 2.26.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✗] Android toolchain - develop for Android devices
    • Android SDK at /usr/lib/android-sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4kylin1
    • cmake version 3.24.1
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed
      instructions).

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Kylin V10 SP1 5.4.18-85-generic

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 4 categories.

![image](https://github.com/flutter/flutter/assets/108720447/89869877-4838-4f5e-ac1d-c92614886e54)

arm64
$ flutter doctor -v
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[✓] Flutter (Channel beta, 3.14.0-0.2.pre, on Kylin V10 SP1 5.4.18-53-generic, locale zh_CN.UTF-8)
    • Flutter version 3.14.0-0.2.pre on channel beta at /home/wzh/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 123453dc41 (12 天前), 2023-08-31 13:50:44 -0700
    • Engine revision b93c76ab94
    • Dart version 3.2.0 (build 3.2.0-42.2.beta)
    • DevTools version 2.26.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • Kylin clang version 13.0.1-7~20.04.sav0kylin2
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed
      instructions).

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-arm64 • Kylin V10 SP1 5.4.18-53-generic

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 4 categories.
![image](https://github.com/flutter/flutter/assets/108720447/a410e3ed-8970-4e55-ae92-6a7a32281adb)

**Comment by huycozy** [comment]
Thanks for your update. This looks similar to https://github.com/flutter/flutter/issues/90951; although the OP on that issue uses x64 machine. Can you check the workaround at https://github.com/flutter/flutter/issues/90951#issuecomment-931551300 if it can help?

**Comment by wuzhaohui100** [comment]
> 感谢您的更新。这看起来类似于#90951；尽管该问题上的OP使用x64机器。[您可以查看#90951（评论）](https://github.com/flutter/flutter/issues/90951#issuecomment-931551300)中的解决方法是否有帮助？
First，add the following code in pubspec.yaml
  fonts:
    - family: NotoSansCJKsc
      fonts:
        - asset: fonts/NotoSansCJK-Regular.ttc

Then，add the following code in lib/main.dart.
              style: TextStyle(fontFamily: 'NotoSansCJKsc'),

**Comment by huycozy** [comment]
Thanks for your update. I think it's indeed the same cause with https://github.com/flutter/flutter/issues/90951, so I will close this issue in favor of that issue. Please follow up on it for further updates.
