### ISSUE TITLE
Execution failed for task ':gradle:compileGroovy'. > Could not resolve all files for configuration ':gradle:detachedConfiguration1

### ISSUE THREAD

**Issue by alisiam1625** [flutter/flutter#134241]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

```console
Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gradle:compileGroovy'.
> Could not resolve all files for configuration ':gradle:detachedConfiguration1'.
   > Could not find org.codehaus.groovy:groovy:?.?.??.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/codehaus/groovy/groovy/?.?.??/groovy-?.?.??.pom
       - https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy/?.?.??/groovy-?.?.??.pom
     Required by:
         project :gradle
   > Could not find org.codehaus.groovy:groovy-ant:?.?.??.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/codehaus/groovy/groovy-ant/?.?.??/groovy-ant-?.?.??.pom
       - https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-ant/?.?.??/groovy-ant-?.?.??.pom
     Required by:
         project :gradle
   > Could not find org.codehaus.groovy:groovy-astbuilder:?.?.??.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/codehaus/groovy/groovy-astbuilder/?.?.??/groovy-astbuilder-?.?.??.pom
       - https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-astbuilder/?.?.??/groovy-astbuilder-?.?.??.pom
     Required by:
         project :gradle
   > Could not find org.codehaus.groovy:groovy-console:?.?.??.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/codehaus/groovy/groovy-console/?.?.??/groovy-console-?.?.??.pom
       - https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-console/?.?.??/groovy-console-?.?.??.pom
     Required by:
         project :gradle
   > Could not find org.codehaus.groovy:groovy-datetime:?.?.??.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/codehaus/groovy/groovy-datetime/?.?.??/groovy-datetime-?.?.??.pom
       - https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-datetime/?.?.??/groovy-datetime-?.?.??.pom
     Required by:
         project :gradle
   > Could not find org.codehaus.groovy:groovy-dateutil:?.?.??.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/codehaus/groovy/groovy-dateutil/?.?.??/groovy-dateutil-?.?.??.pom
       - https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-dateutil/?.?.??/groovy-dateutil-?.?.??.pom
     Required by:
         project :gradle
   > Could not find org.codehaus.groovy:groovy-nio:?.?.??.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/codehaus/groovy/groovy-nio/?.?.??/groovy-nio-?.?.??.pom
       - https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-nio/?.?.??/groovy-nio-?.?.??.pom
     Required by:
         project :gradle
   > Could not find org.codehaus.groovy:groovy-sql:?.?.??.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/codehaus/groovy/groovy-sql/?.?.??/groovy-sql-?.?.??.pom
       - https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-sql/?.?.??/groovy-sql-?.?.??.pom
     Required by:
         project :gradle
   > Could not find org.codehaus.groovy:groovy-test:?.?.??.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/codehaus/groovy/groovy-test/?.?.??/groovy-test-?.?.??.pom
       - https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-test/?.?.??/groovy-test-?.?.??.pom
     Required by:
         project :gradle
   > Could not find org.codehaus.groovy:groovy-templates:?.?.??.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/codehaus/groovy/groovy-templates/?.?.??/groovy-templates-?.?.??.pom
       - https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-templates/?.?.??/groovy-templates-?.?.??.pom
     Required by:
         project :gradle
   > Could not find org.codehaus.groovy:groovy-json:?.?.??.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/codehaus/groovy/groovy-json/?.?.??/groovy-json-?.?.??.pom
       - https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-json/?.?.??/groovy-json-?.?.??.pom
     Required by:
         project :gradle
   > Could not find org.codehaus.groovy:groovy-xml:?.?.??.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/codehaus/groovy/groovy-xml/?.?.??/groovy-xml-?.?.??.pom
       - https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-xml/?.?.??/groovy-xml-?.?.??.pom
     Required by:
         project :gradle
   > Could not find org.codehaus.groovy:groovy-groovydoc:?.?.??.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/codehaus/groovy/groovy-groovydoc/?.?.??/groovy-groovydoc-?.?.??.pom
       - https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-groovydoc/?.?.??/groovy-groovydoc-?.?.??.pom
     Required by:
         project :gradle

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

### Expected results

Filter problem

### Actual results

Filter problem

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Hi @alisiam1625 
This seems to be an issue with Gradle rather than Flutter itself. Can you share these file contents?

- /android/build.gradle
- /android/gradle/wrapper/gradle-wrapper.properties
- /android/app/build.gradle

**Comment by alisiam1625** [comment]
buildscript {
    ext.kotlin_version = '1.7.10'
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
-----------------------------------------------
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-all.zip
-----------------------------------
plugins {
    id "com.android.application"
    id "kotlin-android"
    id "dev.flutter.flutter-gradle-plugin"
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

android {
    namespace "com.example.flutter_application_151"
    compileSdkVersion flutter.compileSdkVersion
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.flutter_application_151"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
        minSdkVersion flutter.minSdkVersion
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
  
}

**Comment by alisiam1625** [comment]
buildscript {
    ext.kotlin_version = '1.7.10'
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

**Comment by alisiam1625** [comment]
buildscript {
    ext.kotlin_version = '1.7.10'
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

**Comment by alisiam1625** [comment]
plugins {
    id "com.android.application"
    id "kotlin-android"
    id "dev.flutter.flutter-gradle-plugin"
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

android {
    namespace "com.example.flutter_application_151"
    compileSdkVersion flutter.compileSdkVersion
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.flutter_application_151"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
        minSdkVersion flutter.minSdkVersion
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
  
}

**Comment by alisiam1625** [comment]
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-all.zip

**Comment by Shreyans13** [comment]
If I am updating my `gradle-wrapper.properties` at `android/gradle/wrapper/gradle-wrapper.properties`
to `gradle-7.8.2-all.zip`
`distributionUrl=https\://services.gradle.org/distributions/gradle-7.8.2-all.zip`. It seems to compile and run in emulator but release apk fails to install in my phone 

P.S. - its a default project generated by flutter (Counter application)

```
javac --version 
javac 20.0.2
```

```
flutter --version 
Flutter 3.13.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ff5b5b5fa6 (2 weeks ago) • 2023-08-24 08:12:28 -0500
Engine • revision b20183e040
Tools • Dart 3.1.0 • DevTools 2.25.0
```

**Comment by TOKA-ALsabbagh** [comment]
I am facing the same problem how did you solve it ?

**Comment by r6mez** [comment]
same problem Here.

**Comment by ihebm22** [comment]
same :(

**Comment by mahmodalali2003ali** [comment]
كيف يممكننا حل هذه المشكلة

**Comment by Sarah11abd6** [comment]
@alisiam1625 
@Shreyans13 
@r6mez 
@huycozy 
@ihebm22 
@TOKA-ALsabbagh
@mahmodalali2003ali 

 I fix it by change my windows display language from arabic to english . 
fter that restart your system and run the project again.
I hope this fix your problem.

**Comment by Eng-Mushtaq** [comment]
@alisiam1625
@Shreyans13
@r6mez
@huycozy
@ihebm22
@TOKA-ALsabbagh
@mahmodalali2003ali

I fix it by change my windows display language from arabic to english .
fter that restart your system and run the project again.
I hope this fix your problem.

**Comment by Eng-Mushtaq** [comment]
> كيف يممكننا حل هذه المشكلة

I fix it by change my windows display language from arabic to english .
fter that restart your system and run the project again.
I hope this fix your problem.

**Comment by Eng-Mushtaq** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the [existing issues](https://github.com/flutter/flutter/issues)
> * [x]  I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)
> 
> ### Steps to reproduce
> ```
> Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':gradle:compileGroovy'.
> > Could not resolve all files for configuration ':gradle:detachedConfiguration1'.
>    > Could not find org.codehaus.groovy:groovy:?.?.??.
>      Searched in the following locations:
>        - https://dl.google.com/dl/android/maven2/org/codehaus/groovy/groovy/?.?.??/groovy-?.?.??.pom
>        - https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy/?.?.??/groovy-?.?.??.pom
>      Required by:
>          project :gradle
>    > Could not find org.codehaus.groovy:groovy-ant:?.?.??.
>      Searched in the following locations:
>        - https://dl.google.com/dl/android/maven2/org/codehaus/groovy/groovy-ant/?.?.??/groovy-ant-?.?.??.pom
>        - https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-ant/?.?.??/groovy-ant-?.?.??.pom
>      Required by:
>          project :gradle
>    > Could not find org.codehaus.groovy:groovy-astbuilder:?.?.??.
>      Searched in the following locations:
>        - https://dl.google.com/dl/android/maven2/org/codehaus/groovy/groovy-astbuilder/?.?.??/groovy-astbuilder-?.?.??.pom
>        - https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-astbuilder/?.?.??/groovy-astbuilder-?.?.??.pom
>      Required by:
>          project :gradle
>    > Could not find org.codehaus.groovy:groovy-console:?.?.??.
>      Searched in the following locations:
>        - https://dl.google.com/dl/android/maven2/org/codehaus/groovy/groovy-console/?.?.??/groovy-console-?.?.??.pom
>        - https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-console/?.?.??/groovy-console-?.?.??.pom
>      Required by:
>          project :gradle
>    > Could not find org.codehaus.groovy:groovy-datetime:?.?.??.
>      Searched in the following locations:
>        - https://dl.google.com/dl/android/maven2/org/codehaus/groovy/groovy-datetime/?.?.??/groovy-datetime-?.?.??.pom
>        - https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-datetime/?.?.??/groovy-datetime-?.?.??.pom
>      Required by:
>          project :gradle
>    > Could not find org.codehaus.groovy:groovy-dateutil:?.?.??.
>      Searched in the following locations:
>        - https://dl.google.com/dl/android/maven2/org/codehaus/groovy/groovy-dateutil/?.?.??/groovy-dateutil-?.?.??.pom
>        - https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-dateutil/?.?.??/groovy-dateutil-?.?.??.pom
>      Required by:
>          project :gradle
>    > Could not find org.codehaus.groovy:groovy-nio:?.?.??.
>      Searched in the following locations:
>        - https://dl.google.com/dl/android/maven2/org/codehaus/groovy/groovy-nio/?.?.??/groovy-nio-?.?.??.pom
>        - https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-nio/?.?.??/groovy-nio-?.?.??.pom
>      Required by:
>          project :gradle
>    > Could not find org.codehaus.groovy:groovy-sql:?.?.??.
>      Searched in the following locations:
>        - https://dl.google.com/dl/android/maven2/org/codehaus/groovy/groovy-sql/?.?.??/groovy-sql-?.?.??.pom
>        - https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-sql/?.?.??/groovy-sql-?.?.??.pom
>      Required by:
>          project :gradle
>    > Could not find org.codehaus.groovy:groovy-test:?.?.??.
>      Searched in the following locations:
>        - https://dl.google.com/dl/android/maven2/org/codehaus/groovy/groovy-test/?.?.??/groovy-test-?.?.??.pom
>        - https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-test/?.?.??/groovy-test-?.?.??.pom
>      Required by:
>          project :gradle
>    > Could not find org.codehaus.groovy:groovy-templates:?.?.??.
>      Searched in the following locations:
>        - https://dl.google.com/dl/android/maven2/org/codehaus/groovy/groovy-templates/?.?.??/groovy-templates-?.?.??.pom
>        - https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-templates/?.?.??/groovy-templates-?.?.??.pom
>      Required by:
>          project :gradle
>    > Could not find org.codehaus.groovy:groovy-json:?.?.??.
>      Searched in the following locations:
>        - https://dl.google.com/dl/android/maven2/org/codehaus/groovy/groovy-json/?.?.??/groovy-json-?.?.??.pom
>        - https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-json/?.?.??/groovy-json-?.?.??.pom
>      Required by:
>          project :gradle
>    > Could not find org.codehaus.groovy:groovy-xml:?.?.??.
>      Searched in the following locations:
>        - https://dl.google.com/dl/android/maven2/org/codehaus/groovy/groovy-xml/?.?.??/groovy-xml-?.?.??.pom
>        - https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-xml/?.?.??/groovy-xml-?.?.??.pom
>      Required by:
>          project :gradle
>    > Could not find org.codehaus.groovy:groovy-groovydoc:?.?.??.
>      Searched in the following locations:
>        - https://dl.google.com/dl/android/maven2/org/codehaus/groovy/groovy-groovydoc/?.?.??/groovy-groovydoc-?.?.??.pom
>        - https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-groovydoc/?.?.??/groovy-groovydoc-?.?.??.pom
>      Required by:
>          project :gradle
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 14s
> Exception: Gradle task assembleDebug failed with exit code 1
> Exited (sigterm)
> ```
> 
> ### Expected results
> Filter problem
> 
> ### Actual results
> Filter problem
> 
> ### Code sample
> Code sample
> ### Screenshots or Video
> Screenshots / Video demonstration
> ### Logs
> Logs
> ### Flutter Doctor output
> Doctor output

I fix it by change my windows display language from arabic to english .
fter that restart your system and run the project again.
I hope this fix your problem.

**Comment by huycozy** [comment]
For anyone facing this issue: If you have the same case as @Eng-Mushtaq mentioned, please try his solution to see if it can help. 

If the issue still persists, please help to file a new issue with all information indicated in the issue template. (as I'm not sure if he's already solved this issue or not)

**Comment by Shreyans13** [comment]
You could try re-setting up your Java in android studio settings. in my case, Studios java version was not matching therefore it was giving issues. 
`distributionUrl=https\://services.gradle.org/distributions/gradle-7.8.2-all.zip`

This was compatible with java version setup in my android studio therefore it was working. App not getting installed was a different issue altogether. 

Hope this helps

**Comment by Shreyans13** [comment]
@Eng-Mushtaq windows display language should not pose an issue I was getting this issue in Mac with English language. Both thing looks unconnected, not sure how it might have fixed this issue. Are you getting this issue again if you change the language back to Arabic
I believe it got solved because of restarting android studio. Also, Did you invalidate your cache and restart ?

**Comment by Shreyans13** [comment]
@huycozy Lets see if this fixes the issue for others  or we can raise a new issue with all information indicated in the issue template

**Comment by r6mez** [comment]
@huycozy @Eng-Mushtaq @alisiam1625 @huycozy 
That is so strange, changing the display language does end the problem.
I tried changing the language from Arabic to English, and after that, I opened VScode and a message appeared "Lunching Gradle",
Then I tried running the app on the emulator and it worked.
when I switched the language back to Arabic the problem appeared again.

I think while building the app something tries to access the gradle files with a specific path that changes relatively to the language.
maybe this is wrong but I see no other relation between the system language and the missing gradle files.

**Comment by huycozy** [comment]
@r6mez Can you also check this with Android native project? If it's only reproducible with Flutter, please help to file a new issue for this.

**Comment by abutlb** [comment]
i had the same issue and solved by making my windows english as @Eng-Mushtaq  said 
turned it back to arabic and the issue is back with it 

temporary sulotion for me ...i made a new english windows user and use it for cases like this

**Comment by shimy2023** [comment]
> > كيف يممكننا حل هذه المشكلة
> 
> I fix it by change my windows display language from arabic to english . ater that restart your system and run the project again. I hope this fix your problem.

thank you it's work with me

**Comment by shimy2023** [comment]
> > كيف يممكننا حل هذه المشكلة
> 
> I fix it by change my windows display language from arabic to english . ater that restart your system and run the project again. I hope this fix your problem.

Thank you it's work with me
