### ISSUE TITLE
How to add navigatorObservers on MaterialApp.router

### ISSUE THREAD

**Issue by MikePendo** [flutter/flutter#134239]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I would like to add Naviagator Observers to `MaterialApp.router` in case I dont use the GoRouter Package.
The most closest issue I have found:
[https://github.com/flutter/flutter/issues/109861](https://github.com/flutter/flutter/issues/109861)
But in that case it was resolved with GoRouter Package.
Maybe there is a way to access the Navigator directly and add the observers.
Or somehow to use `RouterDelegate` and add a configuration there? (Can somebody suggest a work around for that case )
If the `RouterDelegate` has Navigator we can add observers there

### Proposal

A more convenience way to add Navigator observers to MaterialApp.router

**Comment by chunhtai** [comment]
If you implement your own routerdelegate. Somewhere in the RouterDelegate.build method should build a navigator. You can plug in the navigator observe in there.

I doesn't make sense to have navigator observers in MaterialApp.router since it doesn't create a navigator in the MaterialApp.
