### ISSUE TITLE
Error while installing flutterfire cli via terminal 

### ISSUE THREAD

**Issue by Sri-Geyan** [flutter/flutter#134371]
After installing 624 packages by running (npm install -g firebase-tools),I was not able to run (dart pub global activate flutterfire_cli) 
![Screenshot (5)](https://github.com/flutter/flutter/assets/73470830/5fcc803d-fc84-4dca-98d2-e80e8de2b76d)
I have tried changing from sdk: '>=2.10.0 <3.0.0' to sdk: '>=2.17.3 <3.0.0' in pubspec.yaml,updated dart to the latest stable release and add the flutter path in system variable environment but still the above mentioned error code occurs,It would be helpful if someone assists me on rectifying this error and on installing flutterfire cli

**Comment by N-Saipraveen** [comment]
Ask the question in slack you will get a faster response
@Sri-Geyan

**Comment by Sri-Geyan** [comment]
> Ask the question in slack you will get a faster response @Sri-Geyan

May I know what is slack

**Comment by N-Saipraveen** [comment]
https://fluttercommunity.slack.com/join/shared_invite/zt-21zu3gdhi-4pOnVyFIXWCHyZ~rFet_gA#/shared-invite/email

**Comment by N-Saipraveen** [comment]
Join it and ask there

**Comment by stuartmorgan** [comment]
The version of Dart you are using from Flutter 2.0, which is several years old. If you need help updating Flutter, or making sure the correct version of `flutter` and `dart` are in your path, consider one of the resources listed at https://flutter.dev/community#community-grid

Closing as this is not a Flutter bug.
