### ISSUE TITLE
MenuAnchor crashes when a child has tooltip and is hover

### ISSUE THREAD

**Issue by BananaMasterz** [flutter/flutter#134390]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Simply run the following code, click the bell icon and hover the item. Haven't tried on mobile this was tested on windows desktop.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: Center(
          child: MenuAnchor(
            builder: (BuildContext context, MenuController controller, Widget? child) {
              return IconButton(
                onPressed: () {
                  if (controller.isOpen) {
                    controller.close();
                  } else {
                    controller.open();
                  }
                },
                icon: const Icon(Icons.notifications),
              );
            },
            menuChildren: [
              Tooltip(
                message: 'some tip',
                child: Padding(
                  padding: const EdgeInsets.all(16.0),
                  child: Text('hover me'),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.13.0, on Microsoft Windows [Version 10.0.22000.2360], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.4)
[√] Android Studio (version 2022.3)
[√] Connected device (3 available)
[√] Network resources
```

</details>

**Comment by darshankawar** [comment]
@BananaMasterz 
There's a similar issue reported describing your case https://github.com/flutter/flutter/issues/133545 which is caused as mentioned [here](https://github.com/flutter/flutter/issues/133545#issuecomment-1699806041). 
I suggest you subscribe to that issue so that once it is fixed, you can re-run your scenario on latest master and confirm if it works for your case or not.
For now, I'll close as duplicate. If you disagree, write in comments and I'll reopen it.
