### ISSUE TITLE
flutter_ffmpeg  executeAsyncWithArguments callback not being executed

### ISSUE THREAD

**Issue by cooldadabs** [flutter/flutter#134374]
Hello, I've been stuck for a while now in the app I am working on. I am using ffmpeg executeAsyncWithArguments to overlay a single image into a video from start to end, the filterParams I used do work as you can see in the logs. However, it seems to me that the execution of the command is stuck after the overlaying process, sort of hanging and no logs is happening there after. Btw I used the sample code in pub.dev documentation and non of the print statement is being printed. Can anyone shed light on this? Will really appreciate your help, same with the code, I am stuck on how to proceed. 

`final FlutterFFmpeg _flutterFFmpeg = FlutterFFmpeg();
  _flutterFFmpeg.executeAsyncWithArguments(filterParams, (CompletedFFmpegExecution execution) {
  print("executionID: ${execution.executionId} exited with rc ${execution.returnCode}");
  }).then((executionId) => print("Async FFmpeg process started with executionId $executionId."));`

Logs:
`I/flutter (29780): Async FFmpeg process started with executionId 3001.
I/mobile-ffmpeg(29780): Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/data/user/0/com.example.app/cache/video_clip_1.mp4':
I/mobile-ffmpeg(29780):   Metadata:
I/mobile-ffmpeg(29780):     major_brand     : 
I/mobile-ffmpeg(29780): isom
I/mobile-ffmpeg(29780): 
I/mobile-ffmpeg(29780):     minor_version   : 
I/mobile-ffmpeg(29780): 512
I/mobile-ffmpeg(29780): 
I/mobile-ffmpeg(29780):     compatible_brands: 
I/mobile-ffmpeg(29780): isomo2avc1mp41
I/mobile-ffmpeg(29780): 
I/mobile-ffmpeg(29780):     encoder         : 
I/mobile-ffmpeg(29780): Lavf58.48.100
I/mobile-ffmpeg(29780): 
I/mobile-ffmpeg(29780):   Duration: 
I/mobile-ffmpeg(29780): 00:00:04.65
I/mobile-ffmpeg(29780): , start: 
I/mobile-ffmpeg(29780): 0.000000
I/mobile-ffmpeg(29780): , bitrate: 
I/mobile-ffmpeg(29780): 19513 kb/s
I/mobile-ffmpeg(29780): 
I/mobile-ffmpeg(29780):     Stream #0:0
I/mobile-ffmpeg(29780): (eng)
I/mobile-ffmpeg(29780): : Video: h264 (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080, 19844 kb/s
I/mobile-ffmpeg(29780): , 
I/mobile-ffmpeg(29780): 29.61 fps, 
I/mobile-ffmpeg(29780): 29.61 tbr, 
I/mobile-ffmpeg(29780): 90k tbn, 
I/mobile-ffmpeg(29780): 180k tbc
I/mobile-ffmpeg(29780):  (default)
I/mobile-ffmpeg(29780): 
I/mobile-ffmpeg(29780):     Metadata:
I/mobile-ffmpeg(29780):       handler_name    : 
I/mobile-ffmpeg(29780): VideoHandle
I/mobile-ffmpeg(29780): 
I/mobile-ffmpeg(29780):     Stream #0:1
I/mobile-ffmpeg(29780): (eng)
I/mobile-ffmpeg(29780): : Audio: aac (mp4a / 0x6134706D), 48000 Hz, mono, fltp, 192 kb/s
I/mobile-ffmpeg(29780):  (default)
I/mobile-ffmpeg(29780): 
I/mobile-ffmpeg(29780):     Metadata:
I/mobile-ffmpeg(29780):       handler_name    : 
I/mobile-ffmpeg(29780): SoundHandle
I/mobile-ffmpeg(29780): 
I/mobile-ffmpeg(29780): Input #1, png_pipe, from '/data/user/0/com.example.app/cache/image.png':
I/mobile-ffmpeg(29780):   Duration: 
I/mobile-ffmpeg(29780): N/A
I/mobile-ffmpeg(29780): , bitrate: 
I/mobile-ffmpeg(29780): N/A
I/mobile-ffmpeg(29780): 
I/mobile-ffmpeg(29780):     Stream #1:0
I/mobile-ffmpeg(29780): : Video: png, rgba(pc), 699x393
I/mobile-ffmpeg(29780): , 
I/mobile-ffmpeg(29780): 25 tbr, 
I/mobile-ffmpeg(29780): 25 tbn, 
I/mobile-ffmpeg(29780): 25 tbc
I/mobile-ffmpeg(29780): 
I/mobile-ffmpeg(29780): Stream mapping:
I/mobile-ffmpeg(29780):   Stream #0:0 (h264) -> split
I/mobile-ffmpeg(29780): 
I/mobile-ffmpeg(29780):   Stream #1:0 (png) -> scale
I/mobile-ffmpeg(29780): 
I/mobile-ffmpeg(29780):   vstack
I/mobile-ffmpeg(29780):  -> Stream #0:0 (mpeg4)
I/mobile-ffmpeg(29780): Press [q] to stop, [?] for help
I/mobile-ffmpeg(29780): frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
W/mobile-ffmpeg(29780): [graph 0 input from stream 0:0 @ 0xb400007208109040] sws_param option is deprecated and ignored
W/mobile-ffmpeg(29780): [graph 0 input from stream 1:0 @ 0xb400007208109100] sws_param option is deprecated and ignored
I/mobile-ffmpeg(29780): Output #0, mp4, to '/data/user/0/com.example.app/cache/video_1.mp4':
I/mobile-ffmpeg(29780):   Metadata:
I/mobile-ffmpeg(29780):     major_brand     : 
I/mobile-ffmpeg(29780): isom
I/mobile-ffmpeg(29780): 
I/mobile-ffmpeg(29780):     minor_version   : 
I/mobile-ffmpeg(29780): 512
I/mobile-ffmpeg(29780): 
I/mobile-ffmpeg(29780):     compatible_brands: 
I/mobile-ffmpeg(29780): isomo2avc1mp41
I/mobile-ffmpeg(29780): 
I/mobile-ffmpeg(29780):     encoder         : 
I/mobile-ffmpeg(29780): Lavf58.48.100
I/mobile-ffmpeg(29780): 
I/mobile-ffmpeg(29780):     Stream #0:0
I/mobile-ffmpeg(29780): : Video: mpeg4 (mp4v / 0x7634706D), yuv420p, 1920x1080, q=2-31, 200 kb/s
I/mobile-ffmpeg(29780): , 
I/mobile-ffmpeg(29780): 29.61 fps, 
I/mobile-ffmpeg(29780): 18k tbn, 
I/mobile-ffmpeg(29780): 29.61 tbc
I/mobile-ffmpeg(29780):  (default)
I/mobile-ffmpeg(29780): 
I/mobile-ffmpeg(29780):     Metadata:
I/mobile-ffmpeg(29780):       encoder         : 
I/mobile-ffmpeg(29780): Lavc58.96.100 mpeg4
I/mobile-ffmpeg(29780): 
I/mobile-ffmpeg(29780):     Side data:
I/mobile-ffmpeg(29780):       
I/mobile-ffmpeg(29780): cpb: 
I/mobile-ffmpeg(29780): bitrate max/min/avg: 0/0/200000 buffer size: 0 
I/mobile-ffmpeg(29780): vbv_delay: N/A
I/mobile-ffmpeg(29780): 
W/System  (29780): A resource failed to call release. 
W/System  (29780): A resource failed to call release. 
I/mali_config(29780): @get_buffer_dataspace_setting: update dataspace (0x10010000 -> 0x08020000)
I/mobile-ffmpeg(29780): frame=   11 fps=0.0 q=21.3 size=     256kB time=00:00:00.33 bitrate=6208.7kbits/s dup=1 drop=0 speed=0.558x    
I/mobile-ffmpeg(29780): frame=   28 fps= 25 q=31.0 size=     256kB time=00:00:00.91 bitrate=2299.8kbits/s dup=1 drop=0 speed=0.822x    
I/mobile-ffmpeg(29780): frame=   45 fps= 28 q=31.0 size=     256kB time=00:00:01.48 bitrate=1411.2kbits/s dup=1 drop=0 speed=0.913x    
I/mobile-ffmpeg(29780): frame=   62 fps= 29 q=31.0 size=     512kB time=00:00:02.06 bitrate=2035.7kbits/s dup=1 drop=0 speed=0.964x    
I/mobile-ffmpeg(29780): frame=   79 fps= 30 q=31.0 size=     768kB time=00:00:02.63 bitrate=2388.0kbits/s dup=1 drop=0 speed=0.99x    
I/mobile-ffmpeg(29780): frame=   95 fps= 30 q=31.0 size=     768kB time=00:00:03.17 bitrate=1981.6kbits/s dup=1 drop=0 speed=   1x    
I/mobile-ffmpeg(29780): frame=  112 fps= 30 q=31.0 size=    1024kB time=00:00:03.74 bitrate=2237.4kbits/s dup=1 drop=0 speed=1.02x    
I/mobile-ffmpeg(29780): frame=  129 fps= 31 q=31.0 size=    1024kB time=00:00:04.32 bitrate=1940.3kbits/s dup=1 drop=0 speed=1.03x    
I/mobile-ffmpeg(29780): frame=  135 fps= 31 q=31.0 Lsize=    1294kB time=00:00:04.52 bitrate=2341.8kbits/s dup=1 drop=0 speed=1.03x    
I/mobile-ffmpeg(29780): video:1292kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 
I/mobile-ffmpeg(29780): 0.110388%
I/mobile-ffmpeg(29780): `

**Comment by stuartmorgan** [comment]
Issues with third-party packages need to be reported to the package's developers.

Closing as this is not an issue with Flutter itself.
