### ISSUE TITLE
Font rendering has issues on Pixel 7 

### ISSUE THREAD

**Issue by lukehutch** [flutter/flutter#134335]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Flutter font rendering on Pixel 7 has both fill and stroke issues:

Rendering on Pixel 7 (Android 13):

![Screenshot_20230909-013104](https://github.com/flutter/flutter/assets/811305/7aef4649-ffed-46b8-a75d-fb7ebb2253fd)

(Note the weird fill issue)

![Screenshot_20230909-012638](https://github.com/flutter/flutter/assets/811305/f788eef4-61a6-4941-a323-61a5787ff2b4)

(Note the very thick curly stems -- it's like the font has a nonzero stroke width, which I didn't request when I rendered the font, I just used the default `TextStyle` except for setting the size.)

Rendering on Android emulator (API level 33), with the same exact code:

![image](https://github.com/flutter/flutter/assets/811305/b06ae11f-6f4a-402a-91f7-1a0f5a3e2d04)

(Fill is fixed)

![image](https://github.com/flutter/flutter/assets/811305/10d5487c-524c-4abe-b076-7ed7d31f20c3)

(Font does not have a stroke)

Rendering in desktop Chrome on Linux (to show the fonts don't have issues there):

![image](https://github.com/flutter/flutter/assets/811305/73207132-9b7d-45e4-9f96-3b52d275292c)

![image](https://github.com/flutter/flutter/assets/811305/9eb7c788-e662-4563-a984-bb5ca1fe99c0)

(Rendering quality is overall better on desktop Chrome than on the emulator, but that may be due to the emulator scaling the screen image to something that is not 1:1)

### Expected results

Font rendering should be the same on all platforms, since they all use Skia

### Actual results

Font rendering is different on all 3 platforms, but the serious problems are only on Pixel 7

### Code sample

N/A

### Screenshots or Video

N/A

### Logs

N/A

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.13.2, on Fedora Linux 38 (Workstation Edition) 6.4.12-200.fc38.x86_64, locale en_US.utf8)
    • Flutter version 3.13.2 on channel stable at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (2 weeks ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/luke/Android/Sdk
    • Platform android-UpsideDownCake, build-tools 33.0.1
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 16.0.6 (Fedora 16.0.6-2.fc38)
    • cmake version 3.27.3
    • ninja version 1.11.1
    • pkg-config version 1.8.0

[✓] Android Studio (version 2022.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 73.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Linux (desktop)            • linux         • linux-x64      • Fedora Linux 38 (Workstation Edition) 6.4.12-200.fc38.x86_64
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 116.0.5845.110

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by lukehutch** [comment]
Setting the `foreground: Paint()..style = PaintingStyle.fill` or `foreground: Paint()..strokeWidth = 0` doesn't fix the problem on Pixel 7.

**Comment by lukehutch** [comment]
I can get the emulator to replicate the font stroke issue with the Mystery Quest font, by setting `fontWeight: FontWeight.w600` or above. Basically the `FontWeight.bold` weight is being used for this font on Pixel 7, but not on the emulator. However, setting `fontWeight:FontWeight.w100` on the Pixel 7 does not remove the bolding.

**Comment by danagbemava-nc** [comment]
Hi @lukehutch, thanks for filing this issue. 

Please provide a complete minimal reproducible code sample so that we can investigate this. Does this also happen when you run on linux desktop itself (not chrome)?

**Comment by lukehutch** [comment]
@danagbemava-nc Here is the source code for a minimal reproducer:

```dart
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        home: Scaffold(
          body: Center(
            child: SafeArea(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Text(
                    'Here I come, ready or not',
                    style: GoogleFonts.bellefair(
                      fontSize: 35,
                    ),
                  ),
                  Text(
                    'Here I come, ready or not',
                    style: GoogleFonts.bellefair(
                      fontSize: 35,
                      fontWeight: FontWeight.normal,
                    ),
                  ),
                  Text(
                    'Here I come, ready or not',
                    style: GoogleFonts.bellefair(
                      fontSize: 35,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  const SizedBox(height: 50),
                  Text(
                    'Here I come, ready or not',
                    style: GoogleFonts.mysteryQuest(
                      fontSize: 32,
                    ),
                  ),
                  Text(
                    'Here I come, ready or not',
                    style: GoogleFonts.mysteryQuest(
                      fontSize: 32,
                      fontWeight: FontWeight.normal,
                    ),
                  ),
                  Text(
                    'Here I come, ready or not',
                    style: GoogleFonts.mysteryQuest(
                      fontSize: 32,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ],
              ),
            ),
          ),
        ));
  }
}
```

Android emulator screenshot:

![image](https://github.com/flutter/flutter/assets/811305/94b65443-c879-4c91-89c6-fbc3aadcfba3)

Pixel 7 Pro screenshot:

![Screenshot_20230914-144651](https://github.com/flutter/flutter/assets/811305/92b91b12-b946-4d96-8a15-b1404132cdb5)

I can't run this on Linux, because of https://github.com/flutter/flutter/issues/134771 . However, here is the screenshot if running on Chrome:

![image](https://github.com/flutter/flutter/assets/811305/b890d079-069d-45ce-8b8c-d71bdfa81242)

So actually Chrome exhibits the same rendering issues as the Android emulator, for both fonts.

The fundamental issue on Pixel 7 Pro is that these fonts are displayed as **bold weight by default**. And the font renderer has problems displaying these fonts in bold (they do not have a bold weight, so the stroke width is just set to something greater than zero). 

The other issue appears to be with the Skia font renderer, for the Bellefair font, when this font is displayed in bold weight, but that is probably a separate bug that could be filed against Skia, I assume?

**Comment by lukehutch** [comment]
There seems to be no way to fix the automatic bolding of all fonts on Pixel 7, e.g. setting `fontVariations: [FontVariation('wght', 50)]`, and could not switch off the bolding.

**Comment by danagbemava-nc** [comment]
Hi @lukehutch, I'm curious, do you happen to have bold font turned on in your font settings on the Pixel 7 pro? On my pixel 7, I do not have it turned on and this is what I see when I run the code sample, I see the same issue as your android emulator & chrome screenshot. (I reduced the width of the image so it doesn't take up too much space in the thread)

<img src="https://github.com/flutter/flutter/assets/88313112/47ef79a7-0981-45c1-8503-3a1c5cf29898" width="300"/>

**Comment by lukehutch** [comment]
@danagbemava-nc Argh, I do. I didn't even know that setting existed, and I have no idea how it got switched on. Thanks!

There's still an issue with the Bellefair font rendering, but I assume that has to be fixed in Skia, so I filed a bug there.
