### ISSUE TITLE
Http post not sending body on iOS

### ISSUE THREAD

**Issue by tejainece** [flutter/flutter#1343]
```dart  
Map lMap = {"Foo1": "Bar1", "Foo2": "Bar2"};
String lData = JSON.encode(lMap);  

Map lHeaders = {"Content-type": "application/json", "Accept": "application/json"};

http.Response lResp = await http.post(lUrl, body: lData, headers: lHeaders);
```

The body is empty.

PS: Also missing the cozy network tab in DevTools in chromium.

**Comment by tejainece** [comment]
Can I get an ETA on this?

**Comment by eseidelGoogle** [comment]
Attempting to repro now.

**Comment by eseidelGoogle** [comment]
Current attempt: https://github.com/eseidelGoogle/repro_flutter_1343

**Comment by eseidelGoogle** [comment]
Android is complaining with
```android: I/flutter : NetworkService unavailable MojoInternalError: Failed to register the MojoHandle.```
I'm not sure what that means yet.  @collinjackson @mpcomplete

**Comment by eseidelGoogle** [comment]
So I'm not yet able to get as far as @tejainece did.  I wonder if there is a regression on master.

**Comment by eseidelGoogle** [comment]
OK.  I have it working on Android.  Checking iOS.  Ran into https://github.com/flutter/flutter/issues/1345 (our iOS workflow still needs a ton of work).

**Comment by eseidelGoogle** [comment]
OK.  I've confirmed this bug on iOS.  See https://github.com/eseidelGoogle/repro_flutter_1343/blob/master/README.md

**Comment by eseidelGoogle** [comment]
Yup.  It appears the iOS code doesn't use the body parameter at all. :/

https://github.com/flutter/engine/blob/master/sky/services/ns_net/url_loader_impl.mm

So the real bug here is that we don't have any testing of our `http` library.  The dart http library appears to have tests, maybe we can just run them:
https://github.com/dart-lang/http

**Comment by eseidelGoogle** [comment]
@chinmaygarde has offered to write the missing body code.  I expect we'll have this fixed today.

**Comment by eseidelGoogle** [comment]
The android version only supports a single part body.  We can do the same on iOS:
https://github.com/flutter/engine/blob/master/sky/services/oknet/src/org/domokit/oknet/UrlLoaderImpl.java#L161

**Comment by eseidelGoogle** [comment]
I think Android is also hard-coding the content type which is wrong:
https://github.com/flutter/engine/blob/master/sky/services/oknet/src/org/domokit/oknet/UrlLoaderImpl.java#L189

**Comment by eseidelGoogle** [comment]
I'm not sure this can be closed yet.  There is still an issue of android hard-coding the content type which is causing android to post with 'form=' instead of 'data=' in this example.  At least that's my understanding.  Can you confirm @tejainece?

**Comment by tejainece** [comment]
I am sorry. I am in a training, so don't have access to my Linux and mac machines. Will test it as soon as i get back home on Thursday.

Thanks for quick response.

**Comment by tejainece** [comment]
It doesn't work yet. It still sends empty body.

Maybe I don't have the recent version. I did ```flutter upgrade```. How do I verify it?

**Comment by chinmaygarde** [comment]
I am not able to reproduce this. Can you try removing the `ios/` directory and try `flutter ios --init` again (after the `flutter upgrade` that you have already done.)

**Comment by tejainece** [comment]
I am testing it on Android, not ios.

**Comment by tejainece** [comment]
Working on Android now. Thanks :)

**Comment by sethladd** [comment]
Cool, thanks for testing!

**Comment by bennybat50** [comment]
final Map<String,dynamic>userData={
      'firstname': _firstNameField,
      'lastname': _lastNameField,
      'display_name': _userNameField,
      'email': _emailField,
      'password': _passwordField
    };

    final response = await http.post(url, body:json.encode(userData) );

I tried sending a post request but its sending an empty body to the server how do i resolve this

**Comment by eseidelGoogle** [comment]
@bennybat50 would you be willing to open a new bug with more info (e.g. your `flutter version` information, etc?) . Thanks!
