### ISSUE TITLE
I'm having issues installing flutter in order to get to wo

### ISSUE THREAD

**Issue by foyem** [flutter/flutter#134334]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

When I ran flutter --version on my PC is shows that it is installed. And when I ran flutter doctor, I received 
flutter doctor shows that my machine could not parse java version - it was unable not determine java version
It also throws adb error

### Actual results

C:\Users\Admin>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
Could not parse java version from:

If there is a version please look for an existing bug https://github.com/flutter/flutter/issues/ and if one does not
exist file a new issue.
[√] Flutter (Channel stable, 3.13.3, on Microsoft Windows [Version 10.0.22000.2295], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    X Could not determine java version
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.1.1)
[√] Android Studio (version 4.1)
[√] VS Code (version 1.81.1)
[☠] Connected device (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Unable to run "adb", check your Android SDK installation and ANDROID_SDK_ROOT environment variable:
      C:\Users\Admin\AppData\Local\Android\Sdk\platform-tools\adb.exe
[√] Network resources

! Doctor found issues in 2 categories.

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

C:\Users\Admin>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
Could not parse java version from:

If there is a version please look for an existing bug https://github.com/flutter/flutter/issues/ and if one does not
exist file a new issue.
[√] Flutter (Channel stable, 3.13.3, on Microsoft Windows [Version 10.0.22000.2295], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    X Could not determine java version
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.1.1)
[√] Android Studio (version 4.1)
[√] VS Code (version 1.81.1)
[☠] Connected device (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Unable to run "adb", check your Android SDK installation and ANDROID_SDK_ROOT environment variable:
      C:\Users\Admin\AppData\Local\Android\Sdk\platform-tools\adb.exe
[√] Network resources

! Doctor found issues in 2 categories.

```

</details>

**Comment by huycozy** [comment]
This may be similar to https://github.com/flutter/flutter/issues/134333. Can you please share the output of `java -version` from the command prompt?
