### ISSUE TITLE
Incorrect labelling for Cloud Firestore

### ISSUE THREAD

**Issue by deefstes** [flutter/flutter#134338]
Very minor nitpick but the menu option reads "Firestore Database", not "Cloud Firestore" as per the "Enable Firestore" step in the [Codelab](https://firebase.google.com/codelabs/firebase-get-to-know-flutter#2).
![image](https://github.com/flutter/flutter/assets/20295990/50edc184-ddd0-4b37-988c-c26ed3f8483e)

**Comment by Karthikeyanarla** [comment]
@deefstes 
Thanks for reporting.
I have raised the PR for the changes.
