### ISSUE TITLE
My app unexpectedly closes when I perform a fast scroll (sliver list)

### ISSUE THREAD

**Issue by ANGEEEL7U7** [flutter/flutter#134352]
I'm using CustomScrollView to fetch a list of services from an API. When I run the app in debug mode, it doesn't crash when I perform a fast scroll. However, when I run it in release mode, the app closes. I tried using Sentry, but it doesn't capture the error. I also attempted to update my Flutter version, but I was unsuccessful. I've been dealing with this issue for about a week now. What am I doing wrong, or what can I do? (I can't show much code as this is a company project).

CODE
[dashboard.txt](https://github.com/flutter/flutter/files/12566049/dashboard.txt)
video 

https://github.com/flutter/flutter/assets/82860569/96f21e21-8fcb-42e2-8d47-2e02036fe979

**Comment by Karthikeyanarla** [comment]
@ANGEEEL7U7 
please check your output screen while you do same in the debug mode. Because, in debug mostly app don't crashes. 
Mostly you will find some kind of error.

**Comment by ANGEEEL7U7** [comment]
in debug mode it doesn't show me any errors in profile mode it shows me this


`F/libc    (20583): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 20610 (1.ui), pid 20583 (es.instaladores)
Process name is com.instaladores.instaladores, not key_process
keyProcess: 0
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'OPPO/CPH2205/OP4F43L1:13/TP1A.220905.001/R.11c8aef-aa7:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2023-09-09 12:42:12.684725859-0600
Process uptime: 57s
Cmdline: com.instaladores.instaladores
pid: 20583, tid: 20610, name: 1.ui  >>> com.instaladores.instaladores <<<
uid: 10385
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0000000000000000
Cause: null pointer dereference
    x0  0000000000000000  x1  b4000078ee86d0f0  x2  b4000078ee82dc88  x3  b4000078ee82dc90
    x4  b400007865b26378  x5  b4000078ef24b1f8  x6  0000000000000000  x7  0000000000000010
    x8  000000009a0ee4aa  x9  000000007fc00000  x10 0000000000000000  x11 000000007f800000
    x12 0000007887364600  x13 0074006f00630000  x14 0000000035333534  x15 0000000000000010
    x16 00000079a39e08f0  x17 00000079a39d1610  x18 00000078802e2000  x19 0000000000000081
    x20 b4000078ee856e00  x21 b4000078ef23b900  x22 b4000078ee856e60  x23 b4000078ee856ea8
    x24 b4000078ee856eb8  x25 b4000078ef3f8300  x26 0000000000000100  x27 b4000078ef312808
    x28 b4000078ee872c80  x29 0000000000000000
    lr  000000788275f06c  sp  0000007880ba9a70  pc  000000788275f074  pst 0000000020000000
backtrace:
      #00 pc 0000000000aa5074  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libflutter.so (BuildId: 5bc4e54a3f62f367e052915542b94e737c0c4391)
      #01 pc 00000000003ad908  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #02 pc 00000000003ad7b0  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #03 pc 00000000003ad6b4  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #04 pc 00000000003b6e44  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #05 pc 00000000003c0d8c  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #06 pc 00000000003d59a4  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #07 pc 0000000000589630  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #08 pc 00000000006396cc  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #09 pc 0000000000638f1c  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #10 pc 0000000000584730  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #11 pc 00000000006396cc  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #12 pc 0000000000638f1c  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #13 pc 0000000000585690  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #14 pc 00000000006396cc  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #15 pc 0000000000638f1c  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #16 pc 0000000000585128  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #17 pc 00000000006396cc  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #18 pc 0000000000638f1c  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #19 pc 0000000000585690  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #20 pc 00000000006396cc  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #21 pc 0000000000638f1c  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #22 pc 0000000000585690  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #23 pc 00000000006396cc  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #24 pc 0000000000638f1c  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #25 pc 0000000000501590  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #26 pc 000000000058de44  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #27 pc 000000000058d3d8  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #28 pc 00000000006396cc  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #29 pc 0000000000410f40  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #30 pc 0000000000410ae4  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #31 pc 000000000058a7f8  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #32 pc 00000000003d3fb0  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #33 pc 00000000003d3e4c  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #34 pc 00000000004a7ff0  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #35 pc 00000000004a7e6c  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #36 pc 00000000004a780c  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #37 pc 00000000004a77d4  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #38 pc 0000000000382b2c  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #39 pc 0000000000382a34  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #40 pc 00000000003826dc  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #41 pc 0000000000382594  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #42 pc 0000000000379d00  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #43 pc 00000000004eeb54  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #44 pc 00000000004f03d4  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #45 pc 00000000004f0404  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #46 pc 0000000000354cf8  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libapp.so (BuildId: f2be611d47fc56cdca2cb5554b4c922e)
      #47 pc 0000000000b517a8  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libflutter.so (BuildId: 5bc4e54a3f62f367e052915542b94e737c0c4391)
      #48 pc 0000000000cff628  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libflutter.so (BuildId: 5bc4e54a3f62f367e052915542b94e737c0c4391)
      #49 pc 0000000000a4e8a0  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libflutter.so (BuildId: 5bc4e54a3f62f367e052915542b94e737c0c4391)
      #50 pc 0000000000a40830  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libflutter.so (BuildId: 5bc4e54a3f62f367e052915542b94e737c0c4391)
      #51 pc 0000000000a56a48  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libflutter.so (BuildId: 5bc4e54a3f62f367e052915542b94e737c0c4391)
      #52 pc 000000000077aee8  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libflutter.so (BuildId: 5bc4e54a3f62f367e052915542b94e737c0c4391)
      #53 pc 000000000077e56c  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libflutter.so (BuildId: 5bc4e54a3f62f367e052915542b94e737c0c4391)
      #54 pc 000000000001836c  /system/lib64/libutils.so (android::Looper::pollInner(int)+1068) (BuildId: 6038dbf95f76d91eaf842148f10f89ea)
      #55 pc 0000000000017ee0  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+112) (BuildId: 6038dbf95f76d91eaf842148f10f89ea)
      #56 pc 00000000000185e4  /system/lib64/libandroid.so (ALooper_pollOnce+100) (BuildId: aa21a30a4bdc2f831ddbb8e9341e722b)
      #57 pc 000000000077e678  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libflutter.so (BuildId: 5bc4e54a3f62f367e052915542b94e737c0c4391)
      #58 pc 000000000077cb30  /data/app/~~uId7ScCJCvpGk6kcaNRcBQ==/com.instaladores.instaladores-9Fyj2QBJb4cjmrmVAx_EFg==/lib/arm64/libflutter.so (BuildId: 5bc4e54a3f62f367e052915542b94e737c0c4391)
      #59 pc 00000000000eb720  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+208) (BuildId: cd953571180b7f5f8ae5570dad29595f)
      #60 pc 000000000007e2d0  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: cd953571180b7f5f8ae5570dad29595f)`

**Comment by Karthikeyanarla** [comment]
@ANGEEEL7U7 
Please give a reproducible code. There are some classes not available in the given dashboard.txt

**Comment by darshankawar** [comment]
@ANGEEEL7U7 
As requested above and to properly address the issue, please provide [runnable but complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without any third party package implementation.
