### ISSUE TITLE
Regression in 3.13.3: Lagging in iOS 16.6 iPhone high frame rates devices

### ISSUE THREAD

**Issue by b-ray** [flutter/flutter#134309]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

- Run the sample code on an iOS 16.6+ Device with support for a high frame rate (13 Pro/Pro Max, 14 Pro/Pro Max, ...).
- Scroll the list.

Flutter 3.13.2 does not have this problem. I am only seeing this when I updated to Flutter 3.13.3 today.
Appears to be a regression of issue: https://github.com/flutter/flutter/issues/131319

### Expected results

Scrolling should be smooth and should not lag/stutter.

### Actual results

Scrolling lags (stutters).

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp(
    items: List<String>.generate(10000, (i) => 'Item $i'),
  ));
}

class MyApp extends StatelessWidget {
  final List<String> items;

  const MyApp({super.key, required this.items});

  @override
  Widget build(BuildContext context) {
    const title = 'Long List';

    return MaterialApp(
      title: title,
      home: Scaffold(
        appBar: AppBar(
          title: const Text(title),
        ),
        body: ListView.builder(
          // Add a key to the ListView. This makes it possible to
          // find the list and scroll through it in the tests.
          key: const Key('long_list'),
          itemCount: items.length,
          itemBuilder: (context, index) {
            return ListTile(
              title: Text(
                items[index],
                // Add a key to the Text widget for each item. This makes
                // it possible to look for a particular item in the list
                // and verify that the text is correct
                key: Key('item_${index}_text'),
              ),
            );
          },
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

Performance Debug Tool Flutter 3.13.2 (profile mode)
<img width="857" alt="Screenshot 2023-09-08 at 18 21 46" src="https://github.com/flutter/flutter/assets/1121929/4b96ba2e-3dc9-4212-9aa6-d4b37915d499">
Performance Debug Tool Flutter 3.13.3 (profile mode)
<img width="860" alt="Screenshot 2023-09-08 at 18 20 08" src="https://github.com/flutter/flutter/assets/1121929/ffd52cdc-14b5-4164-b18c-cceb1baf0448">

Video 3.13.2

https://github.com/flutter/flutter/assets/1121929/5f8316c5-a507-43a7-91c2-037ba254ea08

Video 3.13.3

https://github.com/flutter/flutter/assets/1121929/916ffbc5-75e1-47d1-bf3e-c0c8abd8c1f7

</details>

### Logs

<details><summary>No Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.3, on macOS 13.5.2 22G91 darwin-arm64, locale en-AT)
    • Flutter version 3.13.3 on channel stable at /Users/stpu/fvm/versions/3.13.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2524052335 (2 days ago), 2023-09-06 14:32:31 -0700
    • Engine revision b8d35810e9
    • Dart version 3.1.1
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/stpu/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/stpu/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode-14.3.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.82.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (3 available)
    • Stefans iPhone 14 Pro (mobile) • 00008120-000C611822EB401E            • ios          • iOS 16.6.1 20G81
    • iPhone 11 Pro (mobile)         • 8502B9A2-1553-4219-93B0-21E155C971E7 • ios          • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)                • macos                                • darwin-arm64 • macOS 13.5.2 22G91 darwin-arm64
    ! Error: (null) needs to connect to determine its availability. Check the connection between the device and its companion iPhone, and the connection between the iPhone and Xcode. Both devices may also need to be restarted and unlocked. (code 1)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by navaronbracke** [comment]
This is intentional, as the original fix for the issue had to be reverted due to https://github.com/flutter/flutter/issues/133147

See the comment in https://github.com/flutter/engine/pull/45182/files

**Comment by dam-ease** [comment]
Hi @b-ray. Thanks for filing this. The fix for the original [issue](https://github.com/flutter/flutter/issues/131319) was cherry-picked in `3.10.7` version as mentioned in the last comments of that issue. Kindly check out [this](https://github.com/flutter/flutter/issues/131319#issuecomment-1683070516) comment and [this](https://github.com/flutter/flutter/issues/131319#issuecomment-1686877394). 
Thank you!

**Comment by b-ray** [comment]
Thanks very much @navaronbracke , I was not aware of that, thanks for clearing that up!

@dam-ease I just want to raise again that this is still a (known) problem in the latest Flutter Version `3.13.3`, so I would personally find it clearer to keep this ticket open until it is fixed in a new Flutter release.

**Comment by moffatman** [comment]
Yes, this ticket is improperly closed, the old branch `3.10.x` has not been cherry-picked with https://github.com/flutter/engine/pull/45182 which fixes a crash but reintroduces the lag. `master` branch including `3.13.x` will have this behaviour again.

See https://github.com/flutter/flutter/issues/134242

**Comment by dam-ease** [comment]
Hi @b-ray. Thanks for your response and pointing this out. Thanks @moffatman for your input. I'd keep open and label this appropriately.

**Comment by sz7i** [comment]
> The original fix for the issue had to be reverted due to #133147
> 
> See the comment in https://github.com/flutter/engine/pull/45182/files
> 
> A different fix is planned, though.

The reverted fix was very critical for us and our app didn't use the image picker to pick videos. I do understand that fixing a crash is more important than fixing performance issues. But I would wish that such reverts are announced in the release notes. What I read in the announcement for 3.13.3 (https://groups.google.com/g/flutter-announce/c/ryFiSPpOkUg) is only "fixes image-picker crashes on iOS". It would save us few hours of work if the release announcement would be more transparent.

But anyway thank you for your great work!

**Comment by bdero** [comment]
Triage: This is due to known slow tessellation performance in Impeller. We've revived the stencil-then-cover discussion with new ideas for improving our slow tessellation cases: https://github.com/flutter/flutter/issues/123671

**Comment by m-j-g** [comment]
I'm trying to follow the conversation here.  As far as I can tell it's best to stay on 13.2 if your app is in production, as the performance on iPhone Pro devices isn't acceptable for production apps.  Is this the recommended solution that apps in production are following. I haven't seen any updates here in weeks so I feel like I'm missing something.

**Comment by sz7i** [comment]
Could someone please shed some light on the current status of this issue? Is something still planned to be improved with it? 

I'm not sure when I should upgrade flutter to the version >3.13.2. I've read somewhere that scroll lagging is related to iOS version 16 and it should get better with iOS 17. But statistically more than 50% of my app users still use iOS 16. I would appreciate any advice in this regard.
