### ISSUE TITLE
[Web] Disable context menu for `TextInputConnection`'s hidden input

### ISSUE THREAD

**Issue by angelosilvestre** [flutter/flutter#134359]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

In super_editor, we want the ability to disable the browser context menu/selection toolbar so we can draw our own toolbar.

Currently, there is `BrowserContextMenu.disableContextMenu();` to disable the context menu for the whole application. This is not ideal as apps might want the browser to appear in other places.

### Proposal

Add a property to `TextInputConfiguration` to configure whether or not the browser context menu should be disabled.

**Comment by Renzo-Olivares** [comment]
Hi @angelosilvestre thanks for reporting this issue. So from my understanding the use-case you are trying to achieve is disabling the context menu for a specific input field. If that's the case this might not be possible. This was discussed in the original engine pr [here](https://github.com/flutter/engine/pull/38682) and a way to accomplish this behavior with the existing API is [here](https://github.com/flutter/engine/pull/38682#issuecomment-1376212595). Let me know if this is what you wanted to accomplish. 

```dart
onSecondaryTapDown: (TapDownDetails details) {
  await BrowserContextMenu.disableContextMenu();
  await Future.delayed(const Duration(seconds: 0));
  BrowserContextMenu.enableContextMenu();
}
```

**Comment by angelosilvestre** [comment]
Hi @Renzo-Olivares. Thanks for the answer. And for the mobile text selection toolbar, is it possible to prevent the browser from showing it?

**Comment by Renzo-Olivares** [comment]
@angelosilvestre i'll follow up regarding that use-case on https://github.com/flutter/flutter/issues/134358
