### ISSUE TITLE
Regression: iOS touch to scroll-to-top has stopped working

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#13439]
## Steps to Reproduce

1. Run the Flutter gallery on an iOS device.
2. Scroll down in some page
3. Tap the status bar

## Expected behavior

The scrollable region should scroll to the top.

## Actual behavior

Nothing happens.

**Comment by tvolkert** [comment]
@cbracken @xster

**Comment by cbracken** [comment]
Did some testing and appears to be iOS 11-specific. Status bar taps still behave well on iOS 10.3. The way we compute the status bar frame has changed in iOS 11, with the introduction of safe area insets, so I expect that's likely the issue.

**Comment by cbracken** [comment]
Did a bit more testing on iOS 11 and it looks like this is specific to the iPhone X. There's a check we do that relies on a hardcoded status bar height. The iPhone X has a slightly taller status bar by default. Fortunately iPhone Xs all run iOS 11, so I expect we can do a quick runtime check for iOS 11 and go against the top safe area inset.
