### ISSUE TITLE
Proposal to introduce Adaptive action button widget for adaptive action dialog.

### ISSUE THREAD

**Issue by aliasgar4558** [flutter/flutter#134347]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

In last flutter release - we got adaptive alert dialog but it seems we don't have adaptive action buttons for it.

### Proposal

It would be great if we can have adaptive alert action button widget that will show `TextButton` on Android,Linux Fuchsia & Windows platform and `CupertinoDialogAction` on IOS & macOS platforms.

**Comment by aliasgar4558** [comment]
Raised PR https://github.com/flutter/flutter/pull/134348 - for addressing the issue.

**Comment by darshankawar** [comment]
@aliasgar4558 
Can you take a look at [this](https://pub.dev/packages/adaptive_dialog) community package and check if it serves your proposal ?

**Comment by aliasgar4558** [comment]
@darshankawar : Sure - I looked into the same, but I feel this use case is quite normal that many other users might also face it, and going for 3rd party for this important to have feature is what I am concerned to. However, I have raised a PR which satisfies the requirement of having adaptive action in the material itself. So would you mind please have a look into it and suggest if anything which can be improved.

**Comment by darshankawar** [comment]
Thanks for the feedback.

**Comment by MitchellGoodwin** [comment]
When I was making the adaptive dialog, I did not make an adaptive action intentionally as I was unsure if it was needed. Cupertino is the only design language that has a specific action widget, Material does not have any opinion on what kind of widget is used for it's actions, and Cupertino can use other widgets as well. So to make an adaptive action widget you have two choices:

1. Make a simple adaptive action widget that uses either `CupertinoDialogAction` or some kind of Material button depending on platform. If that's what the developer needs, then writing one themselves is fairly simple as it's basically just a switch statement. In which case they could write it once and use throughout their app. If they need something more complicated, then they are stuck making their own implementation regardless.

2. Make a complicated adaptive action widget that covers as many cases as possible. This would be difficult to design, and likely expensive to maintain for what it is. We would probably have to keep up with multiple issues accounting for edge cases we didn't think of, and the end result would probably some version of having the developer provide a builder method, which would be not that different from them making their own implementation from scratch.

So my opinion is to just leave the example in the documentation that shows how to make a basic adaptive action widget and let the developer build off of that. I think making an official widget would end up being limited or clunky and we try not to bloat the widget catalog with widgets that are fairly simple to implement. I'm open to discussion, however.

**Comment by aliasgar4558** [comment]
Hey @MitchellGoodwin : You are right but what I think is - this is very common problem that will be faced by the developers which is going to use adaptive alerts in their softwares. 

Also, I understand it will be a simple widget that will be disclosed in the sdk, but I think its a very common use case to have it - and if user wants their own action (customised one) then they are free to have that, because we are not imposing the "New widget" mandatorily to be used in actions. 

So, if we have this, major community developers can utilise this one because majority of people only require basic widgets - so introducing software specific widget or going on to some 3rd party package for this simple use case, I felt not very encouraging for all developers.

Happy to hear from you !!  👍

**Comment by MitchellGoodwin** [comment]
Closing as not planned according to reasons above.
