### ISSUE TITLE
Obj-c test Deallocated failing in Xcode Beta 8

### ISSUE THREAD

**Issue by DiegoGW** [flutter/flutter#134388]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Install XCode beta 8 and iOS 17.0 Simulator

1. Compiling the Engine https://github.com/flutter/flutter/wiki/Compiling-the-engine#compiling-for-ios-from-macos for simulator arm-64

2. Testing the engine, don't forget to add the ios variant flag for arm-64 mac simulator:
https://github.com/flutter/flutter/wiki/Testing-the-engine#objective-c---ios-embedding 

3. Run obj-c test: 

from terminal:

run command using the script `run_test.py`: 
```
testing/run_tests.py --type=objc
```
Here the output will be:

Failing tests:
	-[FlutterEngineTest testDeallocated]
	-[FlutterTextInputPluginTest testInteractiveKeyboardDidResignFirstResponderDelegateisCalledAfterDismissedKeyboard]

Also check testing the individual test with `xcodebuild` using:
```
# replace simulator_id
xcodebuild test -workspace project.xcworkspace -scheme IosUnitTests \
-destination 'platform=iOS Simulator,id=$simulator_id' \
-only-testing:IosUnitTestsTests/FlutterEngineTest &> ~/Desktop/objc_results/flutter_engine_test.txt
```

from xcode using the test navigator:

![screen2](https://github.com/flutter/flutter/assets/11681325/b0ebee8a-5351-4320-834e-31344715b8c0)
![screen3](https://github.com/flutter/flutter/assets/11681325/4cc3668c-9e10-4390-bfc7-0eb992a0e21f)

### Expected results

Test success

### Actual results

Failing tests:
	-[FlutterEngineTest testDeallocated]

### Code sample

<details><summary>Code sample</summary>

```
N/A
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![screen1](https://github.com/flutter/flutter/assets/11681325/65066a4a-7250-426a-899f-d79aee9db92b)

</details>

### Logs

<details><summary>Logs</summary>

```console
Failing tests:
	-[FlutterEngineTest testDeallocated]
	-[FlutterTextInputPluginTest testInteractiveKeyboardDidResignFirstResponderDelegateisCalledAfterDismissedKeyboard]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.3, on macOS 13.5 22G74 darwin-arm64, locale en-US)
    • Flutter version 3.13.3 on channel stable at /Users/diegogawenda/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2524052335 (2 days ago), 2023-09-06 14:32:31 -0700
    • Engine revision b8d35810e9
    • Dart version 3.1.1
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/diegogawenda/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/diegogawenda/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/diegogawenda/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Build 15A5229m
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.5 22G74 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.140

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by vashworth** [comment]
The `testInteractiveKeyboardDidResignFirstResponderDelegateisCalledAfterDismissedKeyboard` test is fixed as of https://github.com/flutter/flutter/issues/133776. We should investigate why `testDeallocated` does not pass locally
