### ISSUE TITLE
Latest version (3.13.3) not detecting Git PATH even though I already reinstall and set PATH again.

### ISSUE THREAD

**Issue by jamesdev23** [flutter/flutter#134382]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Download and install Flutter SDK 3.13.3 on Windows 10.
2. Install the latest version of Git (v.2.42.0).
3. Run flutter doctor. It says it doesn't detect git path.

### Expected results

*detects git path*

### Actual results

Unable to detect git path

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Please check this https://github.com/flutter/flutter/issues/123995#issuecomment-1494518327 to see if given solution there can help you solve this issue.

**Comment by jamesdev23** [comment]
> Please check this [#123995 (comment)](https://github.com/flutter/flutter/issues/123995#issuecomment-1494518327) to see if given solution there can help you solve this issue.

The linked comment solves the issue. Thanks.
