### ISSUE TITLE
Screenshots grabbed with driver tests have 'slow mode' banner

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#13448]
If you grab a screenshot with `driver.screenshot()` it has the slow mode banner. It's not clear how to remove this.

**Comment by sethladd** [comment]
cc @Hixie I think I heard of a way to turn off the banner programmatically? Is there a service protocol extension for this?

**Comment by Hixie** [comment]
Check the flutter_tools code, its screenshot logic shows how to temporarily turn off the banner.

**Comment by mit-mit** [comment]
Actually, since flutter driver tests support a custom main, it's pretty easy to just pass in a flag to disable this when the app is instantiated:

```dart
Widget build(BuildContext context) {
   return new MaterialApp(
      home: new MyAppHome(title: 'My App'),
      debugShowCheckedModeBanner: showSlowBanner,
    );
}```

**Comment by nosmirck** [comment]
@mit-mit Hello, I've been looking on how to grab the screenshots taken with the driver, I found you opened an issue to add an example for this here, but still no one has provided an example.

In this issue I see that you managed to do it. would you mind sharing how you got the screenshot saved?

Thanks!

**Comment by mit-mit** [comment]
Yup, see https://github.com/mit-mit/flutter_testing/blob/master/test_driver/tabs.dart !

**Comment by mmcc007** [comment]
The slow mode banner can also be turn-off, without modifying the app, using:
```
  WidgetsApp.debugAllowBannerOverride = false; // remove debug banner
```
in the flutter driver's test_driver/main.dart

See https://github.com/mmcc007/screenshots/blob/master/example/test_driver/main.dart for a working example.

**Comment by bkonyi** [comment]
There's nothing really actionable here since there's already ways to programmatically turn the debug banner off.
