### ISSUE TITLE
[web] Remove `FlutterViewEmbedder`

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#134443]
As part of preparing Flutter Web for a multi-view world, we need to disentangle and de-singletonize several classes, one of which is [`FlutterViewEmbedder`](https://github.com/flutter/engine/blob/e42fd367adcbe16484743e3e5e2a4afe90655eb1/lib/web_ui/lib/src/engine/embedder.dart#L41-L41).

As mentioned in https://github.com/flutter/flutter/issues/118481, each view should know how to embed and handle itself (with the help of helper classes e.g. `MouseCursor`, `ContextMenu`, `Display`, `ScreenOrientation`, etc)

**Comment by albertoazinar** [comment]
Hello @mdebbar 
Can I try this one?
