### ISSUE TITLE
Flutter engine should use CPU affinity on Android for better performance

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#134452]
Even on simple apps on Android (like the inappropriately named complex_layout), we seem to occassionally drop frames on the UI thread every so often (Impeller or Skia). 

At first I thought it might be a GC or something like that, but looking at perfetto traces I can see that some times the UI thread ends up running on the slow cores of the Pixel 6 Pro 2.80 GHz -> 1.80 GHz . For the scrolling apps that seems to be OK sometimes, unless perhaps some new item needs to be laid out and rendered and then we end up dropping the frame.

### Perfetto Trace

![image (1)](https://github.com/flutter/flutter/assets/8975114/ac529939-64ee-4438-8e54-e501d4a35091)

### Release Mode Performance Overlay

<img src="https://github.com/flutter/flutter/assets/8975114/d2ba8201-a9ab-42c8-a4c5-66091c0744f5" width=400>

The Pixel 6 Pro that I'm using, and many other Android devices use the Arm Big.LITTLE CPU architecture: About half of the cores are "efficiency" cores and are significantly slower ~50% than the other half of the "performance" cores. While the Flutter engine does set priorities of its worker threads to appropriate levels, this does not seem sufficient to ensure that UI/raster workloads are only run on the performance cores.

Furhtermore, the engine uses the concurrency level in many places (IO/Raster worker count) where it would be more appropriate to use the number of fast/slow cores - or about half the concurrency level. This may ultimately be the cause of issues like https://github.com/flutter/flutter/issues/132690 and https://github.com/flutter/flutter/issues/129392 , but this needs more investigation.

### CPU/Thread Affinity Masking

We can force the UI/Raster threads to only run on certain CPUs via 

in android_shell_holder.cc

```c++
      cpu_set_t set;
      CPU_ZERO(&set);
      CPU_SET(6, &set);
      CPU_SET(7, &set);
      if (sched_setaffinity(gettid(), sizeof(set), &set) != 0) {
        FML_LOG(ERROR) << "Failed to set affinity";
      }
 ```
 
 This takes advantage of the fact that I can 1) get the CPU count from sched_getaffinity and 2) am making an assumption that the large CPU indexes are the faster cores. The result of making this change to both Raster/UI threads is that the max UI thread time reported on complex_layout app is about 1/3rd what it used to be:

<img src="https://github.com/flutter/flutter/assets/8975114/2530f2b2-5288-437a-839a-fbfbcbd8d7e4" width=400>

**Comment by jonahwilliams** [comment]
The Dart VM is already parsing cpuinfo here: https://github.com/dart-lang/sdk/blob/main/runtime/vm/proccpuinfo.cc

Maybe we can use this to pull out CPU frequency and select the high frequency cores?

**Comment by jonahwilliams** [comment]
I looked into the image decoding issue and found that the I/O tasks are often running on the fast cores. This might be due to the fact that we schedule 8 concurrent, where there are only 4 slow cores, and then never set thread affinity for them.

![image](https://github.com/flutter/flutter/assets/8975114/715982dd-92c5-4fd2-aeda-681dc280049e)

**Comment by jonahwilliams** [comment]
https://screenshot.googleplex.com/4FHurYtKmyrWB57

**Comment by zanderso** [comment]
```
1|cheetah:/ $ cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq
1803000
cheetah:/ $ cat /sys/devices/system/cpu/cpu1/cpufreq/cpuinfo_max_freq
1803000
cheetah:/ $ cat /sys/devices/system/cpu/cpu2/cpufreq/cpuinfo_max_freq
1803000
cheetah:/ $ cat /sys/devices/system/cpu/cpu3/cpufreq/cpuinfo_max_freq
1803000
cheetah:/ $ cat /sys/devices/system/cpu/cpu4/cpufreq/cpuinfo_max_freq
2348000
cheetah:/ $ cat /sys/devices/system/cpu/cpu5/cpufreq/cpuinfo_max_freq
2348000
cheetah:/ $ cat /sys/devices/system/cpu/cpu6/cpufreq/cpuinfo_max_freq
2850000
cheetah:/ $ cat /sys/devices/system/cpu/cpu7/cpufreq/cpuinfo_max_freq
2850000
```

**Comment by jonahwilliams** [comment]
Oooooooh

**Comment by jonahwilliams** [comment]
This has landed an led to substantial 90, 99, and worst frame time improvements across the board:

https://flutter-flutter-perf.skia.org/e/?keys=Xd5c51a50276b0fa3f7e3cc3a8df4333a&selected=commit%3D36921%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DPixel_7_Pro%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253Daverage_frame_build_time_millis%252Ctest%253Dimagefiltered_transform_animation_perf__timeline_summary%252C&xbaroffset=36927

**Comment by jonahwilliams** [comment]
Reopening as there is p
