### ISSUE TITLE
 I want to import external calendar using url in flutter. Do we have any package to support this url calendar import feature? 

### ISSUE THREAD

**Issue by selvaonline** [flutter/flutter#134464]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

 I want to import external calendar using url in flutter. Do we have any package to support this url calendar import feature? 

### Proposal

 I want to import external calendar using url in flutter. Do we have any package to support this url calendar import feature?

**Comment by stuartmorgan** [comment]
Please see https://flutter.dev/community#community-grid for other resources that can be used for Q&A.

Closing as this is not an issue for Flutter itself.
