### ISSUE TITLE
[release] engine release builder only starts after previous build finishes 

### ISSUE THREAD

**Issue by XilaiZhang** [flutter/flutter#134499]
on dashboard, the empty build block of the not started build, corresponds to the yellow running block on an existing build

![Screenshot 2023-09-11 at 5 42 15 PM](https://github.com/flutter/flutter/assets/38773539/1f3b07ea-f9c1-4bd4-85a9-c03e91f62ea4)
![Screenshot 2023-09-11 at 5 42 05 PM](https://github.com/flutter/flutter/assets/38773539/18aa9b83-1c96-48bd-b73c-ccc00b118e82)

And on luci milo dashboard, the start time of the not started build, corresponds to the finish time of the previously existing build
![Screenshot 2023-09-11 at 5 56 02 PM](https://github.com/flutter/flutter/assets/38773539/75f022e1-d76e-4d59-a0c4-f74819011ced)
![Screenshot 2023-09-11 at 5 55 54 PM](https://github.com/flutter/flutter/assets/38773539/0713bbd0-2ccd-498e-b73a-a73351574703)

**Comment by XilaiZhang** [comment]
@drewroengoogle from triage: I think this is fixed by Drew?

**Comment by drewroengoogle** [comment]
We have increased the concurrency to 2 for engine release branch candidates, so 2 builds per platform can run at once. This is different from how tasks in the flutter pool are run, so if there are a ton of cherry picks at once, you may still run into blank tiles until they are picked up, but that is a consequence of using the internal scheduling mechanism. I can close this though
