### ISSUE TITLE
☂️ Flutter + Dart unified telemetry

### ISSUE THREAD

**Issue by leighajarett** [flutter/flutter#134442]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Flutter and Dart have various tools -- the Dart command line tool, the Flutter command line tool, IDE plugins and DevTools. Previously, each tool had its own Google Analytics process with its own Client ID. With the new unified analytics project, all tools report data into a unified Google Analytics account. 

# How does it work?
Events and user properties are collected using the [unified_analytics package](https://github.com/dart-lang/tools/tree/main/pkgs/unified_analytics). This provides a common interface for the various tools to send events to a single Google Analytics account

# How are new events added?
Individual teams will be responsible for adding new event names, event keys and user property keys as necessary to the unified_analytics package. The event value will be set in the corresponding Flutter, Dart or tools code based on some action.

### Proposal

# What needs to be done?
| Category | Issue    | Estimated Completion |
| ------- | -------- | ------- |
| Initial Setup | <ul><li>[x] Create a unified GA account</li></ul>  | June, 2023   |
| Initial Setup | <ul><li>[x] Create a unified_analytics package</li></ul>  | June, 2023   |
| Make package usable | <ul><li>[x] Create a package usage guide</li></ul>  | June, 2023   |
| Make package usable |  <ul><li>[x] https://github.com/dart-lang/tools/issues/137</li></ul> | September, 2023   |
| Make package usable |  <ul><li>[x] https://github.com/dart-lang/tools/issues/158</li></ul> | September, 2023   |
| Make package usable |  <ul><li>[x] https://github.com/dart-lang/tools/issues/159</li></ul> | September, 2023   |
| Migrating events | <ul><li> [x] Migrate all events for the **Flutter tool**: https://github.com/flutter/flutter/issues/128251</li></ul>| March, 2024    |
| Migrating events | <ul><li>[x]  Migrate all events for the **Dart Tool**: https://dart-review.googlesource.com/c/sdk/+/338700, TBD for `pub` </li></ul>| March, 2024    |
| Migrating events | <ul><li>[x]  Migrate all events for **DevTools** </li></ul>| March, 2024    |
| Migrating events | <ul><li>[x]  Migrate all events for **VSCode Plugin** (analyzer only) </li></ul>| March, 2024  |

**Comment by huycozy** [comment]
As far as I understand, this requires the participation of many teams. From the perspective of primary triage, it's not able to apply many `team-*` labels for this. Adding `will need additional triage` label for other's input.

**Comment by mit-mit** [comment]
Perhaps we should file detail issues for each of the rows in the table, in the issue trackers for each of those?

**Comment by Hixie** [comment]
(Since this is assigned I'm going to remove the `will need additional triage` label.)

**Comment by mit-mit** [comment]
@bkonyi do you have spec'ed out what we're doing for the `dart` CLI? And what is the status of that migration? Is there a tracking issue?

**Comment by bkonyi** [comment]
> @bkonyi do you have spec'ed out what we're doing for the `dart` CLI? And what is the status of that migration? Is there a tracking issue?

This landed in November in [this CL](https://dart-review.googlesource.com/c/sdk/+/338700).

There isn't anything spec'ed out, but we're basically just sending the command invoked and the set of enabled experiments. Pub sends some additional events (I think related to `pub get`?).

**Comment by mit-mit** [comment]
cc @jacob314 can you help with status on DevTools, and the AS + Code plugins?

**Comment by jacob314** [comment]
The VSCode plugin should not be on the list. The only analytics Google tracks from it are ones sent through the Dart analysis server that is already on unified analytics. @eliasyishak is in progress on migrating DevTools.

**Comment by mit-mit** [comment]
Thanks @jacob314, removed VSCode. Same for the JetBrains plugin?

**Comment by mit-mit** [comment]
Marking DevTools done; not all data points have been migrated, but the core is there and the overall mechanism is ready.
