### ISSUE TITLE
[image_picker] example folder include in project

### ISSUE THREAD

**Issue by guyluz11** [flutter/flutter#134414]
Example folder is getting included in projects when downloading the package from pub.dev
This disrupts the development process while searching for files/widgets I am getting this `image_picker` results as well 

As written here https://github.com/dart-lang/pub-dev/issues/5862 you need to manually add `example` folder to `.pubignore`

![image](https://github.com/flutter/flutter/assets/9304740/fe60cb3f-4630-45b2-add6-928591d560bb)

**Comment by stuartmorgan** [comment]
https://github.com/flutter/flutter/issues/134413
