### ISSUE TITLE
[Impeller] flutter debug runs falling back to opengl

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#134460]
```
flutter run --enable-impeller
...
E/flutter ( 7021): [ERROR:flutter/shell/platform/android/android_context_vulkan_impeller.cc(42)] Using the Impeller rendering backend (Vulkan with Validation Layers).
E/flutter ( 7021): [ERROR:flutter/impeller/base/validation.cc(49)] Break on 'ImpellerValidationBreak' to inspect point of failure: Requested validations but the validation layer was not found.
E/flutter ( 7021): [ERROR:flutter/impeller/base/validation.cc(49)] Break on 'ImpellerValidationBreak' to inspect point of failure: Requested validations but could not find the VK_EXT_debug_utils extension.
E/flutter ( 7021): [ERROR:flutter/impeller/base/validation.cc(49)] Break on 'ImpellerValidationBreak' to inspect point of failure: Device has insufficient capabilities.
E/flutter ( 7021): [ERROR:flutter/shell/platform/android/android_context_gl_impeller.cc(80)] Using the Impeller rendering backend (OpenGLES).
Syncing files to device Pixel 4a...                                 18ms
```

This is happening because the validations are not correctly loading.  They worked with locally built but something is happening with `flutter/flutter` archives.

## doctor

[✓] Flutter (Channel main, 3.14.0-14.0.pre.222, on macOS 13.5.2 22G91 darwin-arm64, locale en)
    • Flutter version 3.14.0-14.0.pre.222 on channel main at /Users/aaclarke/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e7058f568f (15 minutes ago), 2023-09-11 22:46:04 +0200
    • Engine revision 0774ddcda9
    • Dart version 3.2.0 (build 3.2.0-134.0.dev)
    • DevTools version 2.27.0

**Comment by gaaclarke** [comment]
The validations are missing from `flutter/bin/cache/artifacts/engine/android-arm64/flutter.jar`

```
$ find lib
lib
lib/arm64-v8a
lib/arm64-v8a/libflutter.so
```

**Comment by gaaclarke** [comment]
I also verified that local engines have the necessary file structure:
```
$ find lib/
lib/
lib//arm64-v8a
lib//arm64-v8a/libflutter.so
lib//arm64-v8a/libVkLayer_khronos_validation.so
lib//arm64-v8a/libc++_shared.so
```

**Comment by jonahwilliams** [comment]
Are we missing some updates in flutter.gradle/flutter.groovy?

**Comment by gaaclarke** [comment]
> Are we missing some updates in flutter.gradle/flutter.groovy?

@jonahwilliams I'm not sure what that file is.  If it is building apps when you execute `flutter run` I don't think that is the problem because the actual `flutter/bin/cache/artifacts/engine/android-arm64/flutter.jar` file is wrong on disk.  It seems like the bot that archives these files is modifying the jar file or using some odd build path not used locally.

**Comment by jonahwilliams** [comment]
I don't think that jar file is used though, I believe we upload _something_ to maven central and then the tool downloads this?

**Comment by gaaclarke** [comment]
> 
I don't think that jar file is used though, I believe we upload something to maven central and then the tool downloads this?

Hmm, hopefully if I fix that artifact it also fixes the maven copy.

It looks like we are uploading something in the bots like here: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Production%20Engine%20Drone/354235/overview

```
27. gsutil Upload /b/s/w/ir/cache/builder/src/out/android_debug_arm64/zip_archives/download.flutter.io/io/flutter/arm64_v8a_debug/1.0.0-fe5fa056a54043b08df27f4a0028da21a4df4687/arm64_v8a_debug-1.0.0-fe5fa056a54043b08df27f4a0028da21a4df4687.jar to gs://download.flutter.io/io/flutter/arm64_v8a_debug/1.0.0-fe5fa056a54043b08df27f4a0028da21a4df4687/arm64_v8a_debug-1.0.0-fe5fa056a54043b08df27f4a0028da21a4df4687.jar
```

That build appears to be compiling context_vk.cc but nothing from `//third_party/vulkan-deps/vulkan-validation-layers`.  I'll see if getting it showing up there will fix it.

**Comment by gaaclarke** [comment]
If that is in fact the source of all the archives what is suspicious is that context_vk.cc is getting compiled, but `--enable-impeller-vulkan` is not being specified.
