### ISSUE TITLE
[Impeller] Android Preview

### ISSUE THREAD

**Issue by mariamhas** [flutter/flutter#134449]
The Android migration to Impeller will be similar to that on iOS. Flutter has been OpenGL ES only on Android since the beginning. With Impeller, Flutter will use Vulkan for the first time. [Productionizing the Vulkan backend with OpenGL ES fallback](https://github.com/orgs/flutter/projects/21/views/11).

**Comment by zanderso** [comment]
The work that was prerequisite for the preview has been completed, so I'll go ahead and close this.
