### ISSUE TITLE
Building with "--source-maps" uses the wrong URL

### ISSUE THREAD

**Issue by WorikQCI** [flutter/flutter#134498]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

* Build a flutter web app with "--source-maps" argument to generate a main.dart.js.map
* When app loaded into a web page use devtools (I was using Chrome) to find the source
* The source files are all listed
* Click on one
* Get error: "Could not load content for https://&lt;My URL&gt;/lib/src/...."

This will not effect everybody.

My `--base-href` is:  "/develop/&lt;my name&gt;/".  So would expect (hope) that the paths to the source files in the "main.dart.js.map" would be " https://&lt;My URL&gt;/develop/lib/src/....".  

I tried some naive editing of main.dart.js.map, but all I could do was make the files disappear from the "Page" view in Chrome Devtools 

### Expected results

I have not used this before.

I was hoping that I could use this do debug my web app in situ

### Actual results

See above

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
% flutter doctor -v
[✓] Flutter (Channel stable, 3.13.2, on macOS 13.4 22F66 darwin-arm64, locale en-AU)
    • Flutter version 3.13.2 on channel stable at /Users/user/Documents/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (3 weeks ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.81.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.198
    ! Error: iPad has recently restarted. Xcode will continue when iPad is unlocked. (code -14)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @WorikQCI 
I tried following the steps you mentioned, generated `main.dart.js.map` file too using `--source-maps` command.
Then ran sample web app and opened the devtools link in chrome, but then I am unsure how to proceed further in order to see all the source files and click on them.
Can you elaborate on it ?

**Comment by WorikQCI** [comment]
I am unfamiliar with what should be happening, so this is the blind leading.... somebody

The link to my webapp is (like) "https://foo.com/develop"

The DocumentRoot is a directory like... "c:\some\root\inetpub\" (Yes, on Windows.  An Azure instance.)

I build with "--hrefs" as "/develop/my_app_name"

The app is in: "c:\some\root\inetpub\develop\my_app_name"

When I run it and I look at the "Page" tab of Chrome Dev Tools I can see a source tree that matches my source tree on my build environment, all the dart files.  When I click on one I get a tab opened, with the file name ("some_such.dart") as the tab name and an error along the top (not a error dialogue or very prominent) "Could not load content for https://foo.com/lib/src/path/to/some_such.dart"

I have used `tar` to move all the "*.dart" files in my  my `lib/` tree to: "c:\some\root\inetpub\develop\lib\...*

Is that clear?

**Comment by WorikQCI** [comment]
I have another detail that may explain it

The Web App in question is launched inside an iframe 

It is set up by another Web App written in Javascript

```javascript
this.iframe = document.createElement("iframe");
this.iframe.setAttribute('src', '/develop/my_app_name/index.html');
this.iframe.setAttribute('id', 'my_app_name');

// TODO:  Size the iframe properly
this.iframe.style.width = '100%';
this.iframe.style.height = '100%';
this.my_app_container.appendChild(this.iframe);
this.target.appendChild(this.my_app_container);
```

Where `/develop/my_app_name/index.html` is the local part of the URL to the `index.html`

**Comment by WorikQCI** [comment]
I have been digging further

I have it working in a separate instance, on a local server

I believe that what I need to do is configure my webserver better.  

I would like it to look for source in either the same place as `--base-href` or some other way of configuring it, but that is a "feature request" not a bug.

Thank you for your attention, and I am sorry that I wasted some of your time
