### ISSUE TITLE
TextFormField - when validation fails, cursor color is assigned to be the same as the error text color

### ISSUE THREAD

**Issue by lirantzairi** [flutter/flutter#134451]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run the code sample
2. Tap on the text field to set the focus to it
3. The cursor color is green as expected
4. Write something, no matter what, so the "Invalid" error text will appear in red under the text field

### Expected results

The cursor color should stay green.

### Actual results

The cursor color turns red like the error text color.
If this is intended, then the documentation of `TextFormField` should be updated, although I don't see the point in keeping this behavior.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Form(
          autovalidateMode: AutovalidateMode.always,
          child: Center(
            child: Padding(
              padding: const EdgeInsets.all(20),
              child: TextFormField(
                cursorColor: Colors.green,
                validator: (value) {
                  if (value?.isNotEmpty == true) return 'Invalid';
                  return null;
                },
              ),
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel unknown, 3.10.5, on macOS 13.3 22E252 darwin-arm64, locale en-IL)
    ! Flutter version 3.10.5 on channel unknown at /Users/liran/code/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    • Framework revision 796c8ef792 (3 months ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/liran/Library/Android/sdk
    • Platform android-34, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554             • android-arm64  • Android 14 (API 34) (emulator)
    • Liran's iPhone (mobile)     • 00008101-000265A20C84001E • ios            • iOS 16.6 20G75
    • macOS (desktop)             • macos                     • darwin-arm64   • macOS 13.3 22E252 darwin-arm64
    • Chrome (web)                • chrome                    • web-javascript • Google Chrome 116.0.5845.179

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @lirantzairi 

> The cursor color should stay green.

This was changed as part of https://github.com/flutter/flutter/pull/119225 that you can go through for reference.
Hence you are seeing cursor color to be red.
I'll close this as WAI and also as part of the link. If you disagree, write in comments and I'll reopen it.

**Comment by lirantzairi** [comment]
Thanks @darshankawar for your quick response. I looked at https://github.com/flutter/flutter/pull/119225 and https://github.com/flutter/flutter/issues/113750 and on the relevant Material design specs:
* https://m2.material.io/components/text-fields#filled-text-field
* https://m3.material.io/components/text-fields/specs

Can you please refer me to where they specify that the cursor color **has to be** the same color as the error text? I did see the images in https://github.com/flutter/flutter/issues/113750, but:
1. They don't indicate that it's mandatory, to me they look more like examples.
2. If we did consider them as indications then the border color should also be the same color as the error text but in practice we're able to change them in Flutter using 
```
focusedErrorBorder: UnderlineInputBorder(
  borderSide: BorderSide(
    color: Colors.green,
  ),
),
```
