### ISSUE TITLE
[RefreshProgressIndicator] More configurable fields

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter#134494]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Currently, `margin`, `elevation`, and `padding` inside the indicator are hard-coded, which does not allow for modification.

https://github.com/flutter/flutter/blob/a9fac73361d3a86fa9dc7921e773f1aa0d0cae71/packages/flutter/lib/src/material/progress_indicator.dart#L976
https://github.com/flutter/flutter/blob/a9fac73361d3a86fa9dc7921e773f1aa0d0cae71/packages/flutter/lib/src/material/progress_indicator.dart#L980
https://github.com/flutter/flutter/blob/a9fac73361d3a86fa9dc7921e773f1aa0d0cae71/packages/flutter/lib/src/material/progress_indicator.dart#L982

### Proposal

These fields should be considered exposed to the constructor or the theme data.

**Comment by AlexV525** [comment]
cc @TahaTesser for your opinion.

**Comment by HansMuller** [comment]
Sounds reasonable. We'd welcome a PR.

**Comment by salmanulfarisi** [comment]
will like to work on it

**Comment by salmanulfarisi** [comment]
Have a doubt for whether these parameters should be added in constructor or theme data of progress indicator 
@HansMuller

**Comment by TahaTesser** [comment]
@AlexV525 
Thanks for the PR! l'll review it soon
