### ISSUE TITLE
Unclear how to handle conditional UI, when resolving the condition is async

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#13445]
Occasionally apps need to render different UI depending on some condition that is resolved asynchronously, for example:

* Dependent on device vs. emulator: The `device_info` package has an `isEmulator` API, but this is async

* Dependent on login state: The `firebase_auth` package handles login, but asking if the user is logged in or not is async

It would be great if flutter.io has documentation for how to generally render UI that is conditional on async state.

**Comment by goderbauer** [comment]
The cookbook would be a great place to add this (https://flutter.io/docs/cookbook).

Should this be moved to the website repo?

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2133](https://github.com/flutter/website/issues/2133) via [**ZenHub**](https://www.zenhub.com/)
