### ISSUE TITLE
[go_router] access matched location with the actual path parameter

### ISSUE THREAD

**Issue by momrak** [flutter/flutter#134402]
### Use case

In this route the `matchedLocation` will return `album/:albumId`. Is there a builtin way of getting the route prefix and the actual value of the path param? If the album id is `3` I want to get `album/3`. Does this exist? 
```
              GoRoute(
                path: 'album/:albumId',
                builder: (BuildContext context, GoRouterState state) {
                  print(state.matchedLocation);
                  return AlbumScreen(
                    albumId: state.pathParameters['albumId'],
                  );
                },
                )
```

### Proposal

I want to be able to get the matched location with the actual value of the path param.

**Comment by darshankawar** [comment]
@momrak 
Can you check [this](https://github.com/flutter/flutter/issues/107240) issue and see if it helps in your case or not ?

**Comment by darshankawar** [comment]
Thanks for the feedback.

**Comment by chunhtai** [comment]
There is a private method you can copy over to your code base as a workaround

https://github.com/flutter/packages/blob/adf7adf983fc8a56adeaf2b84e580698acdb9638/packages/go_router/lib/src/path_utils.dart#L73

If we were to do this, I think it will be to open up this file in go_router

**Comment by momrak** [comment]
Nice, thank you 👍

**Comment by usamaidrsk** [comment]
I think there is an issue as @momrak  mentioned to be addressed
https://github.com/flutter/flutter/issues/134402#issue-1889775023
               
The `albumId` param value is not the value returned but rather the parameter name  `:albumId ` when trying to access it by  `state.pathParameters['albumId'] `

**Comment by iharoonamjad** [comment]
> I think there is an issue as @momrak mentioned to be addressed [#134402 (comment)](https://github.com/flutter/flutter/issues/134402#issue-1889775023)
> 
> The `albumId` param value is not returned but rather the parameter name `:albumId ` when trying to access it by `state.pathParameters['albumId'] `

Same Issue at my side,
**Caller Side:**
`GoRouter.of(context).goNamed(
                                Pages().manageCourses.name,
                                extra: course,
                                pathParameters: {"courseId": course.ref.id});`
                                
Reciever Side:
![image](https://github.com/flutter/flutter/assets/135381966/96cd9458-8f08-41b9-96c0-43c995be9b24)

**Comment by chunhtai** [comment]
oops this looks worse than i thought thanks for pointing out

**Comment by chunhtai** [comment]
I can't reproduce the issue this is the code I am using

<details>

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

/// This sample app demonstrates how to use GoRoute.onExit.
void main() => runApp(const MyApp());

/// The route configuration.
final GoRouter _router = GoRouter(
  routes: <RouteBase>[
    GoRoute(
      path: '/',
      builder: (BuildContext context, GoRouterState state) {
        return const HomeScreen();
      },
      routes: <RouteBase>[
        GoRoute(
          path: 'album/:albumId',
          builder: (BuildContext context, GoRouterState state) {
            print(state.matchedLocation);
            print("state.pathParameters['albumId'] is ${state.pathParameters['albumId']}");
            print("state.pathParameters['albumId'] from context is ${GoRouterState.of(context).pathParameters['albumId']}");
            return Text(state.pathParameters['albumId'] ?? " null");
          },
        )
      ],
    ),
  ],
);

/// The main app.
class MyApp extends StatelessWidget {
  /// Constructs a [MyApp]
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerConfig: _router,
    );
  }
}

/// The home screen
class HomeScreen extends StatelessWidget {
  /// Constructs a [HomeScreen]
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Home Screen')),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            ElevatedButton(
              onPressed: () => context.go('/album/123'),
              child: const Text('Go to the Details screen'),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

**Comment by iharoonamjad** [comment]
Can You also try with Shell Routes. ? I am experiencing issue for routes in shellRoutes.

**Comment by chunhtai** [comment]
@iharoonamjad Can you provide a repro?

**Comment by iharoonamjad** [comment]
I am also unable to reproduce, could be problem within my code.
Will share solution for my issue if caught.

**Comment by usamaidrsk** [comment]
> I can't reproduce the issue this is the code I am using
> 
> ```dart
> import 'package:flutter/material.dart';
> import 'package:go_router/go_router.dart';
> 
> /// This sample app demonstrates how to use GoRoute.onExit.
> void main() => runApp(const MyApp());
> 
> /// The route configuration.
> final GoRouter _router = GoRouter(
>   routes: <RouteBase>[
>     GoRoute(
>       path: '/',
>       builder: (BuildContext context, GoRouterState state) {
>         return const HomeScreen();
>       },
>       routes: <RouteBase>[
>         GoRoute(
>           path: 'album/:albumId',
>           builder: (BuildContext context, GoRouterState state) {
>             print(state.matchedLocation);
>             print("state.pathParameters['albumId'] is ${state.pathParameters['albumId']}");
>             print("state.pathParameters['albumId'] from context is ${GoRouterState.of(context).pathParameters['albumId']}");
>             return Text(state.pathParameters['albumId'] ?? " null");
>           },
>         )
>       ],
>     ),
>   ],
> );
> 
> /// The main app.
> class MyApp extends StatelessWidget {
>   /// Constructs a [MyApp]
>   const MyApp({super.key});
> 
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp.router(
>       routerConfig: _router,
>     );
>   }
> }
> 
> /// The home screen
> class HomeScreen extends StatelessWidget {
>   /// Constructs a [HomeScreen]
>   const HomeScreen({super.key});
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(title: const Text('Home Screen')),
>       body: Center(
>         child: Column(
>           mainAxisAlignment: MainAxisAlignment.center,
>           children: <Widget>[
>             ElevatedButton(
>               onPressed: () => context.go('/album/123'),
>               child: const Text('Go to the Details screen'),
>             ),
>           ],
>         ),
>       ),
>     );
>   }
> }
> ```

@chunhtai would try and test this `album/:albumId` as a subroute of `/`.

**Comment by chunhtai** [comment]
> would you try and test this album/:albumId as a subroute of /.

Isn't this what the code does already?
