### ISSUE TITLE
[two_dimensional_scrollables] - TableView is missing padding attribute

### ISSUE THREAD

**Issue by Quijx** [flutter/flutter#134453]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I have a `TableView` in a screen with an app bar that does not have a straight edge. Wrapping the `TableView` with a padding widget causes artifacts with the scroll glow.

![Screenshot_20230911-203251](https://github.com/flutter/flutter/assets/48153628/22dde1ae-69fa-4df2-867d-25961c847536)

### Proposal

`TableView` from the two_dimensional_scrollables package should have a `padding` attribute like any other scrollable widget that allows to add padding around the content without shrinking the scrollable area.

@Piinks

**Comment by Piinks** [comment]
Thanks @Quijx. For now you could wrap Padding around the individual children returned by the TableView cellBuilder.

This would likely be something we implement in TableSpan, which configures individual rows and columns, rather than directly on TableView.

**Comment by Piinks** [comment]
And this one is queued up in https://github.com/flutter/packages/pull/5039 :)
