### ISSUE TITLE
[Impeller] Tessellation overhead causes regression on some animations.

### ISSUE THREAD

**Issue by HayesGordon** [flutter/flutter#134432]
## Details

Hi there! Running into a severe performance regression with Impeller when running a [Rive](https://rive.app) animation.

This was first reported by a customer who did not experience any issues using the Rive Editor (built with Skia) but then ran into issues when building to device (Impeller).

I've created a reproducible example at [this repository](https://github.com/HayesGordon/impeller_performance_regression_sample).

This is the complete animation, and I'm not sure what exactly is causing the issues. Could be something with paths/painting.

Video demonstrating the performance on macOS Impeller (profile build) on Master Flutter channel:

https://github.com/flutter/flutter/assets/13705472/90e295d2-7f11-4fad-b22b-8ef71db812c5

Video demonstrating the performance on iOS Impeller (debug build, simulator) on Master Flutter channel:

https://github.com/flutter/flutter/assets/13705472/4396353a-a8a3-4e29-bb9d-248a3e5cbc18

A **Skia build** runs at about **9ms** (macOS, profile) and **16ms** (iOS debug on simulator) per frame on the raster thread. In the above videos Impeller is pushing 60ms.

This appears to have been introduced recently - Impeller for macOS with **version 3.10.6**, for example, **did not** have this issue. However, v3.10.6 for iOS (simulator and physical device) **does** have the performance issue. 

I've only ran tests for iOS and macOS.

Flutter doctor:
```bash
[✓] Flutter (Channel master, 3.14.0-14.0.pre.215, on macOS 13.5.1 22G90
    darwin-arm64, locale en-NL)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.82.0)
[✓] Connected device (3 available)
[✓] Network resources
```

**Comment by darshankawar** [comment]
Thanks for the detailed report.
I do see the reported performance rendering issue using latest master and stable upon running on iOS simulator with and without impeller.

To confirm whether this is a regression or not, I'll let the engine team take a look.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.13.2, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.13.2 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (7 days ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.14.0-14.0.pre.212, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.14.0-14.0.pre.212 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffe1ebd207 (67 minutes ago), 2023-09-11 03:46:15 -0400
    • Engine revision 1aa11b6448
    • Dart version 3.2.0 (build 3.2.0-134.0.dev)
    • DevTools version 2.27.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by gaaclarke** [comment]
I ran this through the profiler and it seems to be cpu bound on `impeller::FillPathGeometry::GetPositionBuffer` (70% of the raster thread)

<img width="1026" alt="Screenshot 2023-09-15 at 1 42 43 PM" src="https://github.com/flutter/flutter/assets/30870216/8c85cf03-eca0-406e-aae0-3e6704bd3722">


The "Metal resource events" seems to be reporting a lot of time in `AllocatorMTL::OnCreateBuffer` too.  I'm less certain with this problem to know if that is in fact what it is saying.  But if the problem is in the tessellation I would expect the results are potentially being uploaded in a buffer.


<img width="892" alt="Screenshot 2023-09-15 at 1 46 02 PM" src="https://github.com/flutter/flutter/assets/30870216/44dff0af-c9c1-48e6-bbb8-5a8911984e02">

@dnfield and @jonahwilliams will have a better idea about what changed with respect to the tessellation.  In the meantime, I'll poke around.

[ios_profile.trace.zip](https://github.com/flutter/flutter/files/12623638/ios_profile.trace.zip)

**Comment by jonahwilliams** [comment]
Nothing has actually changed about this code as far as I know, in general tessellation is really expensive and we don't handle that well currently. I'm not sure if we actually supported impeller on macos on 3.10, so I'm unsure if this is actually a regression

**Comment by gaaclarke** [comment]
I ran the sample code in 3.10.6 and it exhibits the same performance.  I'm inclined to believe too that this is not a regression.

**Comment by HayesGordon** [comment]
🤷 I attached a video showing what it does my side. With `--enable-impeller` and without and as you can see the perf is the same. So granted it could be that impeller was not available on macOS for that version (but @gaaclarke reports seeing the performance issue on that version, so maybe it's something else).

https://github.com/flutter/flutter/assets/13705472/675f1bf9-aaa2-4eab-b196-2942e733ee22

For clarity we us this (redacted) script to pin the version of Flutter we use across team members, where `TAG` is set to the version:
```sh
for i in $(seq 1 $iterations)
do
    # update the local repository with new info from github
    if git fetch --depth 1 origin tag "$TAG"; then
        # set the correct tag
        git checkout tags/"$TAG"
    elif git checkout "$TAG"; then
        # see if it's a commit sha
        echo checked out "$TAG"
    else
        # tag doesn't exist, it's probably a channel
        flutter channel "$TAG"
    fi
    result=$?
    if [[ $result -eq 0 ]]
    then
        # trigger Flutter to sort itself out
        "$FLUTTER_ROOT"/bin/flutter doctor
        echo "Flutter set to $(git describe --tags)"
        break   
    else
        echo "Local repo could not be updated"
        sleep 1
    fi
done
```

**Comment by bdero** [comment]
Triage: This is due to known slow tessellation performance in Impeller. We've revived the stencil-then-cover discussion with new ideas for improving our slow tessellation cases: https://github.com/flutter/flutter/issues/123671

**Comment by gaaclarke** [comment]
As a tiny performance experiment I moved our libTess2 calls from using malloc to using a linear memory pool.  It increased the tessellation performance 7% (109µs vs 117µs) but doesn't handle the overflow case (not a problem with a 1MB buffer) or realloc (which isn't ever used by libtess2 in my benchmarks).  It's not huge but might be a nice stop gap while we investigate larger fixes.

benchmark:
<details>

```c++
TEST(TessellatorTest, Benchmark) {
  PathBuilder builder;
  for (int i = 0; i < 1000; i++) {
    auto coord = i * 1.0f;
    builder.AddLine({coord, coord}, {coord + 1, coord + 1});
  }
  auto polyline = builder.TakePath().CreatePolyline(1.0f);
  auto start = std::chrono::high_resolution_clock::now();
  int count = 100;
  for (int i = 0; i < count; ++i) {
    Tessellator t;
    Tessellator::Result result = t.Tessellate(
        FillType::kPositive, polyline,
        [](const float* vertices, size_t vertices_size, const uint16_t* indices,
          size_t indices_size) { return true; });
    ASSERT_EQ(result, Tessellator::Result::kSuccess);
  }
  auto end = std::chrono::high_resolution_clock::now();
  auto elapsed = std::chrono::duration_cast<std::chrono::microseconds>(end - start);
  printf("time: %f us\n", elapsed.count() / static_cast<double>(count));
}
```

</details>

**Comment by jonahwilliams** [comment]
I'm lowering the priority of this to P2 because its behind our immediate fidelity/correctness concerns, and requires some long term investment into alternative rendering techniques.

**Comment by jonahwilliams** [comment]
Another tessellation issue: https://github.com/flutter/flutter/issues/135458

There is also example code in that bug, but I'm merging into this one since it will be easier to track.

**Comment by jonahwilliams** [comment]
Checking in after the StC/depth buffer clipping patch on an iPhone

Before: ~70ms raster times
After: ~40ms raster times.

Hey that is progress. Much of the remaining overhead is in polyline generation, which we've sort of known is inefficent but wasn't important as long as we had to deal with tessellation.

![image](https://github.com/flutter/flutter/assets/8975114/ea7d36c7-7cd4-4493-86d4-056563db9ea9)

Interestingly if I run with instruments attached we get ~8ms raster times. I suspect that for some reason (potentially thermal throttling?) we're getting kicked onto the slow core. So despite tessellation being most of the CPU time, we haven't actually improved it as much as we could have. Need to double check if we have the correct affinity settings.

**Comment by jonahwilliams** [comment]
Actually if i launch it in release mode then raster times are ~8ms 😵‍💫

**Comment by bdero** [comment]
StC reduced raster time for this scene by 76%, which brings us down to ~2x Skia's raster time (down from ~8.5x).

## [iPhone 12 mini (PROFILE)](https://github.com/flutter/flutter/issues/143077#issuecomment-2032884280)

### Skia (with raster cache)
5.1 ms/frame

https://github.com/flutter/flutter/assets/919017/e9be30bf-d86d-49b8-8cc2-56b1a49d2fb9

### Impeller (before StC)
43.7 ms/frame

https://github.com/flutter/flutter/assets/919017/10a01a5e-c456-4ca0-b951-2b38187ae815

### Impeller (after StC)
10.6 ms/frame

https://github.com/flutter/flutter/assets/919017/68e417ed-f12e-40a7-ba05-2ef6c6f9dd21

**Comment by bdero** [comment]
This is in 3.22 along with many other minor speedups since this bug was filed. Going to call this resolved, although we have more ideas for speeding up paths and reducing per-draw call overhead in the future.

**Comment by IchordeDionysos** [comment]
Thanks @bdero 😍💪
