### ISSUE TITLE
DateTime.parse('') return a utc datetime

### ISSUE THREAD

**Issue by lsaudon** [flutter/flutter#134425]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

```DateTime.parse('2023-09-11T14:46:10+02:00')``` return a local DateTime

### Expected results

```
false
false
```

### Actual results

```
true
false
```

### Code sample

<details><summary>Code sample</summary>

```dart
void main() {
  print(DateTime.parse('2023-09-11T14:46:10+02:00').isUtc);
  print(DateTime.now().isUtc);
}
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @lsaudon, the DateTime class is from the dart SDK itself and should be reported on their repo. 

Closing from here. 

Thank you
