### ISSUE TITLE
[file_selector] example folder include in project 

### ISSUE THREAD

**Issue by guyluz11** [flutter/flutter#134413]
Example folder is getting included in projects when downloading the package from pub.dev
This disrupts the development process while searching for files/widgets I am getting this `file_selector` results as well 

As written here https://github.com/dart-lang/pub-dev/issues/5862 you need to manually add `example` folder to `.pubignore`

![image](https://github.com/flutter/flutter/assets/9304740/114cf6f8-8773-4dc1-b40a-b960ccd36fe9)

![image](https://github.com/flutter/flutter/assets/9304740/4100ffec-83c3-4788-8afb-eebf1f748402)

**Comment by stuartmorgan** [comment]
> As written here [dart-lang/pub-dev#5862](https://github.com/dart-lang/pub-dev/issues/5862) you need to manually add `example` folder to `.pubignore`

We will not be making this change to our projects, as it would break https://pub.dev/packages/file_selector/example
