### ISSUE TITLE
Provide Midi Support

### ISSUE THREAD

**Issue by raygray** [flutter/flutter#13443]
It would be great to have midi playing support.

**Comment by sethladd** [comment]
Thanks for reaching out! We have a plugin infrastructure which should allow someone to create a plugin to expose Midi up into Flutter. Here are the plugin docs: https://flutter.io/platform-channels/

We don't have plans to write this plugin, but we encourage the community to do it. And, if there are issues with the plugin APIs that make it difficult or impossible, please definitely let us know!

I'll close this issue for now, but we hope to see a Midi plugin!
