### ISSUE TITLE
Android emulator tests have regressed to running on api 31

### ISSUE THREAD

**Issue by gmackall** [flutter/flutter#134588]
In the past, these tests respected the `android_virtual_device` dependency. Here is a PR https://github.com/flutter/flutter/pull/127689 and corresponding run of one of the tests that changed https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20android%20views/27706/overview.

As you can see, the change to the dependency worked and the test started an api 33 emulator. 

Here is a run of the same test from a recent PR: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20android%20views/34883/overview.

The test instead starts an api 31 emulator, despite the dependency still existing (although it was bumped to version 34 recently).

**Comment by gmackall** [comment]
Notably, this regression happened between these two runs
https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20android%20views/28602/overview
https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20android%20views/28603/overview
Meaning it happened between 16:35 and 17:34 PDT.

**Comment by ricardoamador** [comment]
I have time to look at this now. Did it ever run a test with api 34?

**Comment by ricardoamador** [comment]
Okay @gmackall nvm, I see the issue. It would have never run with 34. Somehow the dependencies key for the virtual device version was redefined and was no longer getting picked up. The default version is 31 which is why it was using that. Still not sure how 33 was being found though.

**Comment by gmackall** [comment]
> Okay @gmackall nvm, I see the issue. It would have never run with 34. Somehow the dependencies key for the virtual device version was redefined and was no longer getting picked up. The default version is 31 which is why it was using that. Still not sure how 33 was being found though.

Did the re-definition happen around the time from my earlier comment? If so, then I think the change to 33 would have landed slightly before that happened.

And yes, it never ran with 34. Just 33 briefly, though we didn't notice this until recently

**Comment by ricardoamador** [comment]
Cool. yeah there are two very subtle bugs depending on which test runs. I am going to put in a fix shortly and then need to clean this up.

**Comment by gmackall** [comment]
Also, because they were never running on 34 there is a chance some tests start to fail when the recipes get fixed. If that happens we can downgrade to 33 for now

**Comment by ricardoamador** [comment]
The two tests in the framework ci.yaml that use emulators both passed with version 34.

**Comment by ricardoamador** [comment]
Okay a fix has been merged in: https://flutter-review.googlesource.com/c/recipes/+/51120

**Comment by ricardoamador** [comment]
Okay closing as fixed as the new changes have been picked up and the version 34 api is being used.
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20android%20views/9686/overview.
If this happens again please feel free to reopen this issue.

**Comment by gmackall** [comment]
Thanks!
