### ISSUE TITLE
Entering fullscreen cause canvas to have an incorrect size until you tap anywhere

### ISSUE THREAD

**Issue by Gieted** [flutter/flutter#134563]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

In Flutter Web on a mobile device:
1. Create an app which has a button that enables fullscreen and changes orientation:
```dart
Future<void> enterFullscreen({bool lockOrientation = true}) async {
  await document.documentElement!.requestFullscreen({'navigationUI': 'hide'});
  if (!lockOrientation) return;
  await window.screen?.orientation
      ?.lock('landscape')
      .catchError((_) => {}, test: (e) => e is DomException && e.name == 'NotSupportedError');
}

Future<void> exitFullscreen() async {
  document.exitFullscreen();
  window.screen?.orientation?.unlock();
}
```
2. This happens only 50% of times when you fullscreen, so tap the button repeatedly.
3. Eventually you will see canvas having too much height and therefore the bottom of your application will be out of bounds of the screen.
4. This effect disappear only if you exit fullscreen or tap anywhere in the app

### Expected results

The height of canvas should match the height of the screen

### Actual results

The height of canvas is chosen incorrectly, and it's bigger that the height of the screen

### Screenshots or Video

https://github.com/flutter/flutter/assets/35242233/ee76892f-e1d3-41c4-bac1-90866d0dfbcf

In this video, I'm using a keyboard shortcut to enter and exit full screen fast. You can see the bottom of my application is clipped until I tap the screen

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.3, on Microsoft Windows [Version 10.0.22621.2134], locale pl-PL)
    • Flutter version 3.13.3 on channel stable at C:\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2524052335 (6 days ago), 2023-09-06 14:32:31 -0700
    • Engine revision b8d35810e9
    • Dart version 3.1.1
    • DevTools version 2.25.0

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Gieted\AppData\Local\Android\sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\Chromium\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33205.214
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
    • IntelliJ at C:\Users\Gieted\AppData\Local\Programs\IntelliJ IDEA Ultimate
    • Flutter plugin version 75.1.4
    • Dart plugin version 232.9559.10

[✓] Connected device (4 available)
    • Pixel 6 (mobile)  • 18271FDF600AFG • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows        • windows-x64    • Microsoft Windows [Version 10.0.22621.2134]
    • Chrome (web)      • chrome         • web-javascript • unknown
    • Edge (web)        • edge           • web-javascript • Microsoft Edge 116.0.1938.62

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by Gieted** [comment]
Here you can see canvas height not changing until I tap the screen:


https://github.com/flutter/flutter/assets/35242233/4c4c5771-d375-49a3-8fe6-eca26df1e241

**Comment by huycozy** [comment]
Hi @Gieted 
Looks like it's not easy to detect the issue with video player inside. Can you please share a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) with static content instead?

**Comment by Gieted** [comment]
@huycozy Upon closer inspection, this is a bug in Google Chrome rather than Flutter, because even CSS calculated values are incorrect until you tap the screen.

However, I've noticed that adding a brief delay between enterFullscreen() and orientation.lock() makes this issue far less likely to occur.

e.g.
```dart
Future<void> enterFullscreen({bool lockOrientation = true}) async {
  await document.documentElement!.requestFullscreen({'navigationUI': 'hide'});
  if (!lockOrientation) return;

  await Future.delayed(const Duration(milliseconds: 10)); // it's needed to fix Chrome bug
  await window.screen?.orientation
      ?.lock('landscape')
      .catchError((_) => {}, test: (e) => e is DomException && e.name == 'NotSupportedError');
}
```

------------------------
I doubt there is anything you can do with this issue on your site.
