### ISSUE TITLE
[Skwasm] Remove dependency on `WebAssembly.Function`

### ISSUE THREAD

**Issue by eyebrowsoffire** [flutter/flutter#134556]
Skwasm uses `WebAssembly.Function` in order to export a callback to the skwasm module. This is unfortunate for several reasons:
* This creates a needless Wasm Function -> JS Function -> Wasm Function layering that is probably slow
* It creates a dependency on the type reflection proposal, which we'd like to avoid.
The main reason I can't just export the callback directly is because we need access to the Wasm types in `dart:_wasm` in order to declare the proper signatures and also create a wasm function reference out of a dart function. I'll need to look into how we can give the flutter engine specifically access to the `dart:_wasm` library.

**Comment by mkustermann** [comment]
> I'll need to look into how we can give the flutter engine specifically access to the dart:_wasm library.

Something like [cl/325620](https://dart-review.googlesource.com/c/sdk/+/325620) should be sufficient to allow this.
