### ISSUE TITLE
[Regression] Material leading button scrolls in slivers

### ISSUE THREAD

**Issue by xster** [flutter/flutter#13458]
https://streamable.com/mri1t

Tentatively marking as today. It looks visually pretty jarring.

**Comment by xster** [comment]
Actually it's only on iPhone X as far as I can tell. Reducing priority.

**Comment by xster** [comment]
Bisected to #13442 cc @cbracken

**Comment by cbracken** [comment]
I've got AppBar patches locally; they just need tests. Will verify that they resolve this.
