### ISSUE TITLE
Switch from services.createHttpClient to dart:io.createHttpClient and use dart:io's HttpClient

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#13456]
In an effort to minimize dependencies, we seek to use dart:io's HTTP client instead of the http package

We found that the http package was uses in assets and images (and numerous tests).

For testing/mocking, we can use this injection point: https://docs.flutter.io/flutter/dart-io/HttpOverrides/createHttpClient.html

**Comment by sethladd** [comment]
cc @Hixie

**Comment by sethladd** [comment]
Also, there's HttpOverrides.global (which I think is new since this was filed)

https://github.com/dart-lang/sdk/blob/master/sdk/lib/_http/overrides.dart#L44

**Comment by jonahwilliams** [comment]
Porting the existing framework code to use dart:io has been fairly trivial.  However, I noticed that we specifically provide a `MockClient` from  `package:http/testing.dart` in flutter_test.  Specifically, these lines:

```dart
  @override
  void initInstances() {
    timeDilation = 1.0; // just in case the developer has artificially changed it for development
    HttpOverrides.runZoned(() {}, createHttpClient: (SecurityContext c) {
      return new MockClient((http.BaseRequest request) {
        return new Future<http.Response>.value(
            new http.Response('Mocked: Unavailable.', 404, request: request)
        );
      });
    });
    _testTextInput = new TestTextInput()..register();
    super.initInstances();
  }
```

Would it be appropriate to just replace this with some mockito mocks, or do we need to ship testing versions of `HttpClient` & friends (`HttpClientRequest`, `HttpClientResponse`, `HttpHeaders`, ...).

CC @Hixie

**Comment by jonahwilliams** [comment]
Actually ... does this line _do_ anything?

**Comment by jonahwilliams** [comment]
Okay, I guess I could amend my question to be "Why is this here"

**Comment by jonahwilliams** [comment]
Okay, i am crazy. I added the zoned line.

**Comment by jonahwilliams** [comment]
Spoke offline with @yjbanov about this.

Right now flutter_test overrides the HttpClient for testing, possibly just for network images and related.  `HttpOverrides` from `dart:io` allows overriding the HttpClient using zones.  This may or may not play nicely with flutter_test.  Certainly I don't every single test case to require an `HttpOverride.runZoned` call.

**Comment by zanderso** [comment]
Does `HttpOverrides.global` help? https://api.dartlang.org/dev/2.0.0-dev.35.0/dart-io/HttpOverrides/global.html

**Comment by jonahwilliams** [comment]
@zanderso Yup, that is they key
