### ISSUE TITLE
Need Cupertino Translations

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#13452]
Currently, we only have infrastructure to provide internationalized strings for things in the Material layer. We need to extend that infrastructure to also allow internationalized strings in the Cupertino layer.

This will be required to fix https://github.com/flutter/flutter/issues/13451 as one of the ModalRoutes lives in the Cupertino layer and will have to be translated there.

/cc @HansMuller

**Comment by szotp** [comment]
Uh... is milestone name correct, 2019?

**Comment by xster** [comment]
Oops, wrong date

**Comment by chunlea** [comment]
Before this issue fixed, we can follow https://github.com/flutter/flutter/issues/22624#issuecomment-445524102  use 

```dart
ThemeData(platform: TargetPlatform.android)
```

to fix this.

It will force flutter to use the Android style text copy menu on iOS.

Looks like this in Chinese: 

<img width="250" alt="screenshot 2018-12-10 at 7 37 18 pm" src="https://user-images.githubusercontent.com/1522415/49730350-0e0eda00-fcb3-11e8-98af-4699373ff137.png">

**Comment by xster** [comment]
This is being worked on at this moment. If you found this bug via a cut/copy/paste crash bug, you can currently resolve this in your app by adding more `localizationsDelegates` to your Material or CupertinoApp for your supported locals. 

In those delegates, point each required local to a `CupertinoLocalizations` subclass that provides the needed strings.

**Comment by HerrNiklasRaab** [comment]
@xster Thanks for the help, can you provide use a litte example, because I am not 100% in what you mean?

**Comment by yy1300326388** [comment]
@HerrNiklasRaab  
look here
https://github.com/CaiJingLong/localization_error_example/blob/master/lib/chinese_localization.dart

**Comment by Panthro** [comment]
A quick and dirty hack if you are ok with the english literals to be shown, create a delegate that will load the english text and add to your Material/Cupertino app

```
class CupertinoEnDefaultLocalizationsDelegate extends LocalizationsDelegate<CupertinoLocalizations> {
  const CupertinoEnDefaultLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => true;

  @override
  Future<CupertinoLocalizations> load(Locale locale) =>
      DefaultCupertinoLocalizations.load(Locale('en'));

  @override
  bool shouldReload(CupertinoEnDefaultLocalizationsDelegate old) => false;

  @override
  String toString() => 'DefaultCupertinoLocalizations.delegate(en_US)';
}
```

**Comment by b4rtaz** [comment]
I needed a solution for multi languages app. So, I made below solution. It supports partly two languages.

```dart
import 'package:flutter/foundation.dart' show SynchronousFuture;
import 'package:flutter/cupertino.dart';

class CupertinoLocalizationsDelegate extends LocalizationsDelegate<CupertinoLocalizations> {
  const CupertinoLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'pl'].contains(locale.languageCode);

  @override
  Future<CupertinoLocalizations> load(Locale locale) {
    return SynchronousFuture<_DefaultCupertinoLocalizations>(
      _DefaultCupertinoLocalizations(locale.languageCode)
    );
  }

  @override
  bool shouldReload(CupertinoLocalizationsDelegate old) => false;
}

class _DefaultCupertinoLocalizations extends CupertinoLocalizations {
  final _en = DefaultCupertinoLocalizations();
  final String _languageCode;

  static Map<String, Map<String, String>> _dict = {
    'en': {
      'alert': 'Alert',
      'copy': 'Copy',
      'paste': 'Paste',
      'cut': 'Cut',
      'selectAll': 'Select all'
    },
    'pl': {
      'alert': 'Komunikat',
      'copy': 'Kopiuj',
      'paste': 'Wklej',
      'cut': 'Wytnij',
      'selectAll': 'Zaznacz wszystko'
    }
  };

  _DefaultCupertinoLocalizations(this._languageCode):
    assert(_languageCode != null);

  @override
  String get alertDialogLabel => _get('alert');

  @override
  String get anteMeridiemAbbreviation => _en.anteMeridiemAbbreviation;

  @override
  String get postMeridiemAbbreviation => _en.postMeridiemAbbreviation;

  @override
  String get copyButtonLabel => _get('copy');

  @override
  String get cutButtonLabel => _get('cut');

  @override
  String get pasteButtonLabel => _get('paste');

  @override
  String get selectAllButtonLabel => _get('selectAll');

  @override
  DatePickerDateOrder get datePickerDateOrder => _en.datePickerDateOrder;

  @override
  DatePickerDateTimeOrder get datePickerDateTimeOrder => _en.datePickerDateTimeOrder;

  @override
  String datePickerDayOfMonth(int dayIndex) => _en.datePickerDayOfMonth(dayIndex);

  @override
  String datePickerHour(int hour) => _en.datePickerHour(hour);

  @override
  String datePickerHourSemanticsLabel(int hour) => _en.datePickerHourSemanticsLabel(hour);

  @override
  String datePickerMediumDate(DateTime date) => _en.datePickerMediumDate(date);

  @override
  String datePickerMinute(int minute) => _en.datePickerMinute(minute);

  @override
  String datePickerMinuteSemanticsLabel(int minute) => _en.datePickerMinuteSemanticsLabel(minute);

  @override
  String datePickerMonth(int monthIndex) => _en.datePickerMonth(monthIndex);

  @override
  String datePickerYear(int yearIndex) => _en.datePickerYear(yearIndex);

  @override
  String timerPickerHour(int hour) => _en.timerPickerHour(hour);

  @override
  String timerPickerHourLabel(int hour) => _en.timerPickerHourLabel(hour);

  @override
  String timerPickerMinute(int minute) => _en.timerPickerMinute(minute);

  @override
  String timerPickerMinuteLabel(int minute) => _en.timerPickerMinuteLabel(minute);

  @override
  String timerPickerSecond(int second) => _en.timerPickerSecond(second);

  @override
  String timerPickerSecondLabel(int second) => _en.timerPickerSecondLabel(second);

  String _get(String key) {
    return _dict[_languageCode][key];
  }
}
```

**Comment by Panthro** [comment]
careful it will crash with Copy and Paste on iOS users if you don't provide
(or show english values)


*Rafael Roman*

**Comment by jaumard** [comment]
I extends `DefaultCupertinoLocalizations` so by default it shows English values, should be good :)

**Comment by xqwzts** [comment]
@xster I think that's the wrong label, wouldn't this be under `severe: crash` [as opposed to `severe: new feature`]?

**Comment by xster** [comment]
This is still slated for being brought into master in February. Updating the milestone. 

@xqwzts, in general, if you add [supportedLocales](https://docs.flutter.io/flutter/widgets/WidgetsApp/supportedLocales.html) for your app, you need to provide a LocalizationsDelegate that supports those locales. This is for bundling a partial set that supports Cupertino widgets.

**Comment by kyleodev** [comment]
I can assure you that `CupertinoDatePicker` seems to struggle when it comes to another language.

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following NoSuchMethodError was thrown building MediaQuery(MediaQueryData(size: Size(375.0,
flutter: 667.0), devicePixelRatio: 2.0, textScaleFactor: 1.0, platformBrightness: Brightness.light, padding:
flutter: EdgeInsets(0.0, 20.0, 0.0, 0.0), viewInsets: EdgeInsets.zero, alwaysUse24HourFormat: true,
flutter: accessibleNavigation: falsedisableAnimations: falseinvertColors: falseboldText: false)):
```

**Comment by xster** [comment]
2 more steps:

- [ ] tests
- [ ] update https://flutter.dev/docs/development/accessibility-and-localization/internationalization

**Comment by marwanyousry** [comment]
BUG ( AR Locale) Arabic TextField long press copy-paste: 'pasteButtonLabel' was called on null

      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        _specificLocalizationDelegate
      ],
      
      supportedLocales: [Locale('en'), Locale('ar')],

**Comment by xster** [comment]
Some updates:

The manually translated french localization is in [flutter_localizations](https://github.com/flutter/flutter/blob/5b2281e747b4b9291bb211ce4282e8f8875cdf23/packages/flutter_localizations/lib/src/l10n/generated_cupertino_localizations.dart#L211)

All the other locales currently supported by Material are internally translated (via something like the Google Play Console's app translation service). Generating the rest of the dart GlobalCupertinoLocalizations class instances in flutter_localizations is still pending one last string that needs translation.

**Comment by lgfranco** [comment]
I sent the Portuguese translations to flutter_localizations

**Comment by xster** [comment]
For folks with corresponding language skills, could you help check the translated strings in the various cupertino_*.arb files in https://github.com/flutter/flutter/pull/31644?

**Comment by lgfranco** [comment]
> For folks with corresponding language skills, could you help check the translated strings in the various cupertino_*.arb files in #31644?
> 
> Specifically, our translators may have translated some strings generically but we should match whatever iOS shows in their corresponding UIs.

In fact the translations are generic and not corresponding to the iOS.
The Portuguese ones (my native language) was sent by me in #32049 
 You can use my arbs they were double checked!
(the select all string has a case difference in pt and pt_PT, the seconds abbreviation is misspelled in pt on iOS, I know it's incorrect, but the iOS use 'seg' instead 's' in pt and the correct form in pt_PT)

**Comment by xster** [comment]
Thanks for your suggestions

**Comment by AlexVincent525** [comment]
As I running flutter 1.5.7 on iOS 11.2.5, this issue appears again with pasteButtonLabel call on null, and iOS version greater than 12 has no problem with this.
So maybe test on older iOS firmware version?
Locale is default.

**Comment by aBuder** [comment]
Is there an update or fix available? 
I found an workaround, I deactivated the paste button with following code on TextField and TextFormField

```datrt
enableInteractiveSelection: false,
```

**Comment by AlexVincent525** [comment]
> Is there an update or fix available?
> I found an workaround, I deactivated the paste button with following code on TextField and TextFormField
> 
> ```
> enableInteractiveSelection: false,
> ```

The paste button is required in most case, this doesn't seems to be a good workaround my friend.

**Comment by aBuder** [comment]
when would be an bugfix available?

**Comment by xster** [comment]
I had to revert #31644 unfortunately because some of the strings weren't right.

**Comment by Nazacheres** [comment]
Hey, any progress on that one? It basically makes half of the flutter is not usable at all, while google just keeps talking on stage how good it is. :( IT should be a TOP priority, no?

**Comment by vargavince91** [comment]
There is a pending PR that adds Cupertino translations.

https://github.com/flutter/flutter/pull/32513

**Comment by elo5** [comment]
https://www.kikt.top/posts/flutter/framework/cupertino-paste-tooltip/

I fixed mine by following this

**Comment by pakyo-pan** [comment]
Waiting for the flutter team to fix this problem as soon as possible

**Comment by tvqphong001** [comment]
So many problem in keyborad IOS, Android it OK

**Comment by aBuder** [comment]
Is there an workaround possible

**Comment by hpoul** [comment]
@aBuder might sound stupid, but did you add `GlobalCupertinoLocalizations.delegate` to the `localizationsDelegates`? This solved the problems for me on dev channel. (It took me quite some time to figure that out, since it's missing from the https://flutter.dev/docs/development/accessibility-and-localization/internationalization example

**Comment by andersonmendesdev** [comment]
My CupertinoTimerPicker still gets error when using locale ('pt') and Cupertino delegate. If someone needs the complete mistake just say that post everything.

The following assertion was thrown building CupertinoTimerPicker(dirty, dependencies:
flutter: [_LocalizationsScope-[GlobalKey#e9e55], Directionality], state: _CupertinoTimerPickerState#b4279):
flutter: A non-null String must be provided to a Text widget.
flutter: 'package:flutter/src/widgets/text.dart': Failed assertion: line 241 pos 10: 'data != null'

**Comment by lgfranco** [comment]
You probably forgot to add the delegates:

```
    CupertinoApp(
      localizationsDelegates: [
        GlobalCupertinoLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalMaterialLocalizations.delegate
      ],
      //...
    );
```
OR
```
    MaterialApp(
      localizationsDelegates: [
        GlobalCupertinoLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalMaterialLocalizations.delegate
      ],
      //...
    );
```

**Comment by andersonmendesdev** [comment]
Unfortunately I have it added.

**Comment by uiboy** [comment]
Its weird, I have the `GlobalCupertinoLocalizations.delegate,` added, but in a `TextFormField` the copy and paste buttons do not show up until there is at least one letter typed. The `enableInteractiveSelection` is also set to the default true. 🤔

**Comment by riamehdi** [comment]
> https://www.kikt.top/posts/flutter/framework/cupertino-paste-tooltip/
> 
> I fixed mine by following this

For me work fine, i make same code lake explain in link, juste ajuste for French _context_

**Comment by reasje** [comment]
Wrap the widget with MetrialApp widget to use the default localization .
This way the time picker will have English localization .
But the problem is not solved waiting for the solution ...
