### ISSUE TITLE
Flutter pub get error 

### ISSUE THREAD

**Issue by Ezeani129** [flutter/flutter#134598]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I have tried to check all tutorial possible on YouTube but I keep seeing the process of creating a env variable for it which I have do but the error still happens anytime I try to create a new flutter project and all other requirements have been resolved 

### Expected results

If there's any other way to get pub get to start working 🙏🏾🙏🏾

### Actual results

I would be able to carry out my tasks completely 

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by stuartmorgan** [comment]
If you would like to report an issue, please file a new issue and fill out all of the information requested in the template; we need all of that information in order to investigate.

Closing as there is nothing actionable here, given the lack of steps and error details.
