### ISSUE TITLE
[Impeller] PaintingStyle.stroke is unimplemented for Text.

### ISSUE THREAD

**Issue by Cteq3132** [flutter/flutter#134525]
#126010 has being mark as resolved but the Engine roll implementing the fix has still not landed on stable => [flutter/flutter@ 47ba59c](https://github.com/flutter/flutter/commit/47ba59c762919d66811b72acab9732d6aa2a93c9). 

Do you have more informations about when this commit will be cherry picked on stable?

**Comment by jonahwilliams** [comment]
When the next stable is ready in another month or so
