### ISSUE TITLE
Update CupertinoActionSheet design

### ISSUE THREAD

**Issue by Anishishi** [flutter/flutter#134539]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Overview

The current implementation of CupertionActionSheet differs a little bit from the design referenced in the HIG, [Apple Design Resource](https://www.figma.com/community/file/1248375255495415511).

According to my observation, this is because the thickness of the border line separating the actionSheetItem, the fontSize for the title and description, and the spacing for the title and description sections are different.

So, I would like to update the implementation to follow the current HIG.

### Current Implementation (Colors vary due to M3 but do not care.)
<img src="https://github.com/flutter/flutter/assets/40790076/c85ef420-0cd9-4b27-a8c4-0fb10bb10eca" width=200>

### Proposal, the HIG based design)

<img src="https://github.com/flutter/flutter/assets/40790076/ed5fd344-072e-4d78-972c-78b0a0be367b" width=200>

**Comment by anishi-pfr** [comment]
this issue has been fixed by #134345.

**Comment by Anishishi** [comment]
#134345 is already merged into main branch. so, this issue is resolved.
