### ISSUE TITLE
Following Mac machines lost external connection iPhone devices.

### ISSUE THREAD

**Issue by kentnguyen99** [flutter/flutter#134579]
### Is there an existing issue for this?

- [X] I have searched the [existing infra issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-infra)

### Type of Request

infra task

### Infrastructure Environment

LUCI, Github, Cocoon scheduler, Autosubmit, etc...

### What is happening?

Following Mac machines lost external connection iPhone devices.
<img width="1482" alt="Screenshot 2023-09-12 at 1 25 55 PM" src="https://github.com/flutter/flutter/assets/120754754/0a162549-389a-418c-b91d-9dcd7a6e91d6">

### Steps to reproduce

Step 1:
Step 2:
..
Step n:

### Expected results

I expect to see X when Y is finished.

**Comment by we-prajapati-c001** [comment]
same happens for us

**Comment by kentnguyen99** [comment]
All external connections have been restored by restarting all iPhone devices.

**Comment by we-prajapati-c001** [comment]
Didn't work for us
