### ISSUE TITLE
onChanged event in TextField behaves inconsistently with Korean input on iOS 

### ISSUE THREAD

**Issue by kyle-seongwoo-jun** [flutter/flutter#134507]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Clone the repository from https://github.com/kyle-seongwoo-jun/flutter_korean_ime_issue.
2. Build and run the project on iOS.
3. Type any Korean word into the TextField (e.g., `안녕하세요`).

When typing Korean characters in a `TextField` on iOS, the `onChanged` event gets called in an inconsistent manner as compared to other platforms (Android and macOS). This might be related to how the IME handles Korean input. 

Korean characters are typically composed of 2-3 individual letters (자소 or jaso). For instance, the character "안" is formed by typing ㅇ + ㅏ + ㄴ. 

### Expected results

While typing "안녕하세요" (which translates to "hi"), the expected `onChanged` sequence should be:

1. ㅇ
2. 아
3. 안
4. 안ㄴ
5. 안녀
6. 안녕
7. 안녕ㅎ
8. 안녕하
9. 안녕핫
10. 안녕하세
11. 안녕하셍
12. 안녕하세요

### Actual results

| Actual Sequence | Key Press Sequence | Value Passed to `onChanged` |
|-----------------|--------------------|----------------------------|
| 1               | 1                  | ㅇ                          |
| 2               | 2                  | (empty string)              |
| 3               | 2                  | 아                          |
| 4               | 3                  | (empty string)              |
| 5               | 3                  | 안                          |
| 6               | 4                  | 안ㄴ                        |
| 7               | 5                  | (empty string)              |
| 8               | 5                  | 안                          |
| 9               | 5                  | 안녀                        |
| 10              | 6                  | (empty string)              |
| 11              | 6                  | 안                          |
| 12              | 6                  | 안녕                        |
| 13              | 7                  | 안녕ㅎ                      |
| 14              | 8                  | (empty string)              |
| 15              | 8                  | 안                          |
| 16              | 8                  | 안녕                        |
| 17              | 8                  | 안녕하                      |
| 18              | 9                  | (empty string)              |
| 19              | 9                  | 안                          |
| 20              | 9                  | 안녕                        |
| 21              | 9                  | 안녕핫                      |
| 22              | 10                 | (empty string)              |
| 23              | 10                 | 안                          |
| 24              | 10                 | 안녕                        |
| 25              | 10                 | 안녕하                      |
| 26              | 11                 | 안녕                        |
| 27              | 11                 | 안녕하                      |
| 28              | 11                 | 안녕하셍                    |
| 29              | 12                 | 안녕                        |
| 30              | 12                 | 안녕하                      |
| 31              | 12                 | 안녕하세요                  |

### Code sample

<details><summary>Code sample</summary>

https://github.com/kyle-seongwoo-jun/flutter_korean_ime_issue

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

**Android behavior (working as expected)**

https://github.com/flutter/flutter/assets/16515307/1627dab1-20f2-42f0-9db2-dbf2f3f51a07

**iOS behavior (with issue)**

https://github.com/flutter/flutter/assets/16515307/0ebdbbc6-5906-4e8e-896f-ea481ba9f086

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.3, on macOS 13.5 22G74 darwin-arm64, locale en-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Android Studio (version 2022.3)
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.81.1)
[✓] VS Code (version 1.82.0-insider)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by kyle-seongwoo-jun** [comment]
It may related to #50163

**Comment by dam-ease** [comment]
Hi @kyle-seongwoo-jun. Thanks for filing this. I see there's an open issue addressing the case you described https://github.com/flutter/flutter/issues/50163.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
