### ISSUE TITLE
error: package app.rive.rive does not exist       flutterEngine.getPlugins().add(new app.rive.rive.RivePlugin());                                                       ^

### ISSUE THREAD

**Issue by ArslanAsghar123** [flutter/flutter#134541]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I upgraded to the latest version of flutter and ran pub run outdated and upgrade my packages. 

i got this error everytime i run the app

error: package app.rive.rive does not exist
      flutterEngine.getPlugins().add(new app.rive.rive.RivePlugin());
                                                      ^

### Expected results

the app should be able to run

### Actual results

error: package app.rive.rive does not exist
      flutterEngine.getPlugins().add(new app.rive.rive.RivePlugin());
                                                      ^

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

<img width="803" alt="Screenshot 2023-09-12 at 8 04 19 PM" src="https://github.com/flutter/flutter/assets/56467320/8e347153-311b-4d25-95f6-7dde27366ac6">

</details>

### Logs

<details><summary>Logs</summary>

```console
/Users/asghaars/Trapeze projects/TrapezeCrewApp/crewapp/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:74: error: package app.rive.rive does not exist
      flutterEngine.getPlugins().add(new app.rive.rive.RivePlugin());
                                                      ^
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 28s
Exception: Gradle task assembleDebug failed with exit code 1
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.3, on macOS 13.0 22A380 darwin-arm64, locale en-PK)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2022.1.4)
[✓] VS Code (version 1.78.0)
```

</details>

**Comment by darshankawar** [comment]
@ArslanAsghar123 
Maybe this is related to rive plugin itself ? Check this issue in rive's dedicated repo: https://github.com/rive-app/rive-flutter/issues/286

**Comment by ArslanAsghar123** [comment]
@darshankawar i am not using rive pckg but i am using awesome_dialog pckg that user rive

**Comment by huycozy** [comment]
Hi @ArslanAsghar123 
This looks like a package issue rather than Flutter framework itself. I would recommend you leave a comment at https://github.com/rive-app/rive-flutter/issues/286 that will help package's author to investigate the issue. 

Once it's identified as a Flutter framework issue, please write in comments here and I will reopen this for investigation. Thank you!
