### ISSUE TITLE
Text widgets are lacking a way to automatically adjust their font size 

### ISSUE THREAD

**Issue by sroddy** [flutter/flutter#13455]
It would be very useful to have a feature similar to iOS's `adjustsFontSizeToFitWidth` in the Texts widgets.

https://developer.apple.com/documentation/uikit/uilabel/1620546-adjustsfontsizetofitwidth

**Comment by Hixie** [comment]
If I understand what you're asking for, you can do it by putting the text in a SizedBox with the desired width, and putting the SizedBox in a FittedBox.

**Comment by sroddy** [comment]
I'm not sure we are talking about the same thing.
The purpose of this attribute is to automatically reduce the font size of a label if the text doesn't fit, until a given minimum font size is reached.
This can help in various use cases, for example to avoid a text to overflow a given size while making sure that it is displayed entirely, or to automatically fill in a nice way a given space with a text variable in length

**Comment by Hixie** [comment]
Ah, I see. That's a little different. For that you probably want just a Text inside a FittedBox, using fit.scaleDown.

**Comment by sroddy** [comment]
That would probably do the trick, thanks!

**Comment by maryx** [comment]
Note: The above recommendation does work, but the text has to be in 1 line. It's not able to resize multiple lines of text in a given area. 

Wrapping the FittedBox in a SizedBox resolves this, but the SizedBox is a constant size, and doesn't shrink if the text is super short, so you may have extra space underneath the SizedBox.

**Comment by zoechi** [comment]
@maryx please consider creating a new issue. I wouldn't expect comments on closed issues to be monitored. You can link to this issue for context.

**Comment by maryx** [comment]
I wasn't sure if this is considered a bug - I was just leaving a note so that future people who find the issue through search would know.

**Comment by zoechi** [comment]
@maryx I'd say it's a potentional bug ;-)

**Comment by Nik99** [comment]
What about Tab text ?

```
tabs: <Widget>[
                Tab(text: "x"),
                Tab(text: "y"),
                Tab(text: "z"),
                Tab(text: "t")
              ],
```

It should auto resize based upon the screen size if i do not specify labelStyle and unselectedLabelStyle
