### ISSUE TITLE
Separate out generic application wiring from MaterialApp

### ISSUE THREAD

**Issue by krisgiesing** [flutter/flutter#1346]
Create another class, like App or BasicApp, that does things like wire up locale and media query information, but does not assume any particular UI layout the way MaterialApp does.

MaterialApp could then either inherit from this class, or hold one in a member variable, depending on which seems cleaner.

**Comment by krisgiesing** [comment]
Related to #1129

**Comment by abarth** [comment]
I wonder if it should wire up a Navigator...

**Comment by krisgiesing** [comment]
I don't have a strong opinion, but maybe leave it out for now? We can push navigator support down more easily than trying to pull it up later (since pulling it up would be an API removal).

**Comment by abarth** [comment]
Makes sense.

**Comment by Hixie** [comment]
cc @jimbeveridge - are you saying this would be really good asap?

**Comment by jimbeveridge** [comment]
I've manually extracted the bits in SysUI, but it would certainly be cleaner if it were properly factored and reusable. It doesn't need to be done before the Hackathon, if that helps.

**Comment by Hixie** [comment]
Which parts did you use in your extracted version? Or maybe more importantly, which parts did you leave out?

**Comment by jimbeveridge** [comment]
I needed the ability to detect rotation and have my build function called
after rotation. I included the locale code, but we don't use it at the
moment.




Jim Beveridge

**Comment by Hixie** [comment]
So no navigator or overlay?

**Comment by jimbeveridge** [comment]
We use both Navigator and the overlay, but I didn't touch those classes in our code when I pulled out the bits from MaterialApp.

**Comment by Hixie** [comment]
so it should probably include everything except the theme and the material grid. k.
