### ISSUE TITLE
[Impeller] Attempt enabling validations by default in all debug Vulkan builds.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#134679]
Today, validations need to be enabled explicitly via flags. This was because locating the validation layers was platform specific and asking for validations and not finding the layers was a fatal error.

We are now packaging our own validation layers and also not failing Vulkan context creation when the layer could not be found.

Impeller should attempt loading validations in debug runtime modes by default now.

**Comment by matanlurey** [comment]
I don't see it?

In @gaaclarke's https://github.com/flutter/engine/pull/45682, we appear to enable for ARM64 builds only. Is that "all debug Vulkan builds", or am I missing something?

**Comment by gaaclarke** [comment]
@matanlurey this was discussed in the PR review that arm64 is sufficient.  I believe it captures 93% of android phones.  I don't think we could get arm32 working, but we could get x64 if we wanted.  I think that's what you were running into the other day.  I'd file that as a separate issue considering it has a different priority.

**Comment by matanlurey** [comment]
Gotcha, then let's close this, thanks for clarifying!
