### ISSUE TITLE
[local_auth] Crash on iOS 16.6 

### ISSUE THREAD

**Issue by maerlynflagg** [flutter/flutter#134619]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Open App and use Fingerprint to login
2. go to a order use the take photo function of the 'image_picker' package
3. after photo is taken, App crashed.

looks like the issue described there: https://stackoverflow.com/questions/76901107/ios-only-app-crashes-coming-from-background

If I deactivate the use of TouchID in the app, the error goes away. As soon as I reactivate it, the problem is back.

```
flutter 3.13.3
local_auth: ^2.1.7
image_picker: ^1.0.4
```

### Expected results

The app should no longer crash.

### Actual results

The app crashes and restarts itself as soon as the app comes out of the background after taking a photo. This prevents users from working effectively.

### Logs

<details><summary>Log entry, when it is crashing</summary>

```
PlatformException(NotAvailable, Authentication aborted., com.apple.LocalAuthentication, null)
```

</details>

**Comment by dam-ease** [comment]
Hi @maerlynflagg  
Please can you provide:

- a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code.
- information on the device this crash occurs on
- full output of your `flutter run -v`
-  and also the output of your `flutter doctor -v?`

Thank you!

**Comment by maerlynflagg** [comment]
I can already provide the first further information.

### flutter doctor & devices

<details><summary>flutter doctor -v for the iOS Build</summary>

```
flutter doctor -v
[✓] Flutter (Channel stable, 3.13.3, on macOS 13.5.2 22G91 darwin-x64, locale de-DE)
    • Flutter version 3.13.3 on channel stable at /Users/myuser/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2524052335 (vor 7 Tagen), 2023-09-06 14:32:31 -0700
    • Engine revision b8d35810e9
    • Dart version 3.1.1
    • DevTools version 2.25.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.82.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (2 available)
    • iPad (8th generation) (mobile) • 3643B74D-8A04-44D1-B26A-F45C440CFEF2 • ios        • com.apple.CoreSimulator.SimRuntime.iOS-16-4
      (simulator)
    • macOS (desktop)                • macos                                • darwin-x64 • macOS 13.5.2 22G91 darwin-x64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.

```

</details>

I only know a few devices because I only know the ones where users have registered. Users of these devices have described the same problem in the same place - a crash.

<details><summary>example devices</summary>

```
iPad Pro, 10.5 inch , iOS 16.5.1

iPad  8. Gen, iOS 16.6

iPad Pro (iPad8,3) , iOS 16.6

iPad Air , 3. Gen , iOS 16.6

iPad 7. Gen, iOS 16.6

Samsung Galaxy Tab S7

```

</details>

**Comment by dam-ease** [comment]
Hi @maerlynflagg. Thanks for your response and for providing more info on this. From the devices provided, I see this is not peculiar to iOS devices only. Can you reproduce this on your devices with two simple screens, one to authenticate and then route to a new screen and the other to pick an image using image_picker to see if this reproduces?

**Comment by maerlynflagg** [comment]
Yes, an Android is included, although I don't know if it's really the same error there. This was the only user report from an Android user. All other reports were from iOS users.

Today I would like to try to create a small example where the problem can be reproduced.

**Comment by maerlynflagg** [comment]
Sorry, but I couldn't provide a simple application to recreate it.

But while troubleshooting I noticed something that only occurs on iOS and that is the cause of all the errors.

Steps:
1. Open the app and log in with TouchID 
```
          final bool _succ = await _auth.authenticate(
            localizedReason: HelperManager.resources.passcodeDefaultMessage,
            options: const AuthenticationOptions(
              biometricOnly: true,
              stickyAuth: true,
            ),
            authMessages:  <AuthMessages>[
              AndroidAuthMessages(
                cancelButton: HelperManager.resources.buttonCancel,
                goToSettingsButton: HelperManager.resources.buttonGoToSettings,
                goToSettingsDescription: HelperManager.resources.buttonGoToDescription,
                biometricHint: HelperManager.resources.fingerprintHint,
                biometricNotRecognized: HelperManager.resources.fingerprintNotRecognized,
                biometricRequiredTitle: HelperManager.resources.fingerprintRequiredTitle,
                biometricSuccess: HelperManager.resources.fingerprintSuccess,
                signInTitle: HelperManager.resources.fingerprintSignInTitle,
              ),
              IOSAuthMessages(
                cancelButton: HelperManager.resources.buttonCancel,
                goToSettingsButton: HelperManager.resources.buttonGoToSettings,
                goToSettingsDescription: HelperManager.resources.buttonGoToDescription,
                lockOut: HelperManager.resources.lockOut,
              ),
            ],
          );

          if (_succ) {
            Navigator.of(context).pushReplacementNamed(AdvicesPage.routeName)
          }
```
2. Open an order from the order list to see the order details
`Navigator.of(context).pushNamed(AdviceDetailsPage.routeName)`
3. Open edit mode
 `Navigator.of(context).pushNamed(AdviceEditPage.routeName);`
4. A photo is renamed and the Flutter dialog causes the "dispose" to be called from the order details page only on iOS. This resets an internal flag.

```
final GlobalKey<NavigatorState> globalNavigatorKey = GlobalKey<NavigatorState>();

      showDialog(
        context: globalNavigatorKey.currentContext!,
        barrierDismissible: waiter.dismissable,
        builder: (context) {
          waiterDialog = Waiter(message: waiter.message);
          return waiterDialog!;
        },
      )
```

8. A photo is now taken with the "imager_picker" and  the "didChangeAppLifecycleState" is called from the order list. Because the flag was incorrectly reset, the function that calls TouchID is now called here.
9. The following is the "local_auth" error: `PlatformException(NotAvailable, Authentication aborted., com.apple.LocalAuthentication, null)`
But TouchID is available and has not been canceled by the user.
Sometimes the app crashes so much that a restart is necessary.

So the root cause is that the "dispose" is called in iOS and not on Android as soon as the "showDialog" is called.

So the platform error is a kind of follow-on error.

I have adjusted the "dispose" function so that the error chain no longer occurs. That's why the platform error no longer occurs.
Nevertheless, thank you for the support.

If the platform error is no longer relevant, the issue can be closed.
