### ISSUE TITLE
[Impeller] Audit/remove/merge `host_debug_impeller_vulkan` CI configuration.

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#134675]
There is a nebulously named [`host_debug_impeller_vulkan` configuration](https://github.com/flutter/engine/blob/b71b366e3de3be6720b193086271a3934ead3901/ci/builders/linux_host_engine.json#L36-L44) for Engine CI:

```json
"gn": [
    "--runtime-mode",
    "debug",
    "--unoptimized",
    "--prebuilt-dart-sdk",
    "--target-dir",
    "host_debug_impeller_vulkan"
 ],
"name": "host_debug_impeller_vulkan",
```

It appears to have been added in https://github.com/flutter/engine/commit/40019b79d4f84bbadc7412b76b6a4daf88295c8c, and _used_ to contain additional flags, such as `"--enable-impeller-vulkan"` and `"--engine-capture-core-dump"`, which are no longer used in today's configuration (IIRC `--enable-impeller-vulkan` is _enabled_ by default outside of iOS/MacOS hosts?)

@zanderso also mentioned on chat:

> The other `host_debug_unopt` build builds to run with asan and lsan: https://github.com/flutter/engine/blob/main/ci/builders/linux_unopt.json#L14. My guess is that when the tests under `host_debug_impeller_vulkan` were added, they required some other different flags that have since been removed, or that they didn't pass under asan and lsan.

We should really be running our Impeller/Vulkan tests with ASAN/LSAN, and have 1 less configuration.

**Comment by chinmaygarde** [comment]
Our understanding was that this was only necessary when the host didn't support Impeller everywhere. This is perhaps obsolete. Kill it and see what breaks?

**Comment by matanlurey** [comment]
Will give it a shot.

**Comment by matanlurey** [comment]
Ok, this is not a safe change - for example this is the only build configuration that caught https://github.com/flutter/flutter/issues/134982.

Taking a look closer, this is the only configuration that runs x-server on Linux:

```py
# Use this type to exclusively run impeller vulkan tests.
if 'impeller-vulkan' in types:
  build_name = args.variant
  try:
    xvfb.start_virtual_x(build_name, build_dir)
    run_engine_executable(
        build_dir,
        'impeller_unittests',
        engine_filter,
        shuffle_flags + ['--gtest_filter=-'
                          '*/OpenGLES:'],
        coverage=args.coverage
    )
  finally:
    xvfb.stop_virtual_x(build_name)
```

We should probably keep this configuration, IMO. It is not being covered elsewhere on Linux.

@chinmaygarde If you agree ^, please let me know (or close this issue).

**Comment by zanderso** [comment]
The idea would be to eliminate the build from `linux_host_engine.json`, and retain the test coverage by adding `impeller-vulkan` to the list here: https://github.com/flutter/engine/blob/main/ci/builders/linux_unopt.json#L45. That is, add `impeller-vulkan` to the list of tests to run after the `host_debug_unopt` build in `linux_unopt.json`.

**Comment by matanlurey** [comment]
I don't see myself looking into this anytime soon.

**Comment by zanderso** [comment]
Following https://github.com/flutter/engine/pull/50555, the remaining task is to shift running the `impeller` tests of `run_tests.py` to an `--unopt` build in `linux_unopt.json`, and to remove the `host_debug_impeller_vulkan` build from `linux_host_engine.json`.

**Comment by zanderso** [comment]
Judging from the json files, it looks like this is done.
