### ISSUE TITLE
type 'Null' is not a subtype of type 'String'

### ISSUE THREAD

**Issue by jeremielodi** [flutter/flutter#134601]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I suggest to have the file name and the line where is error occured. It's very complicated to know directly where to fixe the type when you face this error.

### Proposal

-

**Comment by danagbemava-nc** [comment]
This is not a flutter issue. This will have to be done in dart. 

Kindly file an issue on the dart repo instead. 

Closing from here. 

Thank you
