### ISSUE TITLE
Replace `flutter run` tooling for iOS

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#134672]
In https://github.com/flutter/flutter/pull/131865 we had to replace the previous `ios-deploy`-based code path for `flutter run` with Xcode automation, since `ios-deploy` doesn't work with (physical) iOS 17 devices, and we didn't have a better replacement. Once the new communication protocol for device communication has been reverse engineered (as was done originally for earlier versions for `ios-deploy`) we should restore a codepath that doesn't require the unfortunate UX (and increased fragility since it's automating UI) that we are currently having to use. That will likely require us building and bundling a new tool that's downloaded by `flutter`.

**Comment by stuartmorgan** [comment]
(/cc @vashworth FYI. Filing for tracking since we'll likely see issues that are going to depend back to this.)

**Comment by bartekpacia** [comment]
> since ios-deploy doesn't work with (physical) iOS 17 devices, and we didn't have a better replacement

Did you check [go-ios](https://github.com/danielpaulus/go-ios)? I mentioned it to the team [here, some time ago](https://github.com/flutter/flutter/pull/127875#issuecomment-1569697472).

**Comment by vashworth** [comment]
@stuartmorgan I had already filed a bug for this: https://github.com/flutter/flutter/issues/133465

Feel free to close whichever.

**Comment by stuartmorgan** [comment]
🤦🏻 I'm not sure how I had it in my head that we hadn't filed something yet. Closing as a duplicate.
