### ISSUE TITLE
Vscode exception in http requests on Android

### ISSUE THREAD

**Issue by vitoramaral10** [flutter/flutter#134653]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a project to make an http request
2. Run with debug mode active in vscode (F5)

### Expected results

Code successfully executed

### Actual results

![erro](https://github.com/flutter/flutter/assets/7594095/de27f55b-5664-4805-9dcd-8fc96bf125fc)

It causes the error in the debug, but the request is completed and I can retrieve the body 

### Code sample

I'm not creating a code example, because any http request causes an exception in Android.

I've already set the internet permission in AndroidManifest.xml

### Logs

This exception does not generate a log in the terminal, it is only reported in the vscode debug tool

### Flutter Doctor output

[√] Flutter (Channel stable, 3.13.3, on Microsoft Windows [versÆo 10.0.19044.3086], locale pt-BR)
    • Flutter version 3.13.3 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2524052335 (7 days ago), 2023-09-06 14:32:31 -0700
    • Engine revision b8d35810e9
    • Dart version 3.1.1
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\vitor.melo\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.82.0)
    • VS Code at C:\Users\vitor.melo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.72.0

[√] Connected device (3 available)
    • 22041219NY (mobile) • fyx4z9eeqs65fmtw • android-arm64  • Android 13 (API 33)
    • Chrome (web)        • chrome           • web-javascript • Google Chrome 116.0.5845.180
    • Edge (web)          • edge             • web-javascript • Microsoft Edge 116.0.1938.76
    ! Device emulator-5554 is offline.

[√] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by dam-ease** [comment]
Hi @vitoramaral10. Thanks for filing this. This seems similar to https://github.com/flutter/flutter/issues/126650 which has been closed as fixed and I think the fix is on the master channel. Also kindly check this for more insights into a workaround https://github.com/flutter/flutter/issues/126650#issuecomment-1576503525.
It was also being tracked here: https://github.com/dart-lang/sdk/issues/53334
I'd be closing this as it seems a fix is currently on its way, If you disagree, kindly comment and I'll reopen this.
Thank you.

**Comment by dam-ease** [comment]
Hi @vitoramaral10. I see the bug was later reopened and tracked in the Dartlang repo. Are you able to check this fix on the latest `master` channel?

**Comment by vitoramaral10** [comment]
This bug is fixed in 3.13.4 version, thanks!

**Comment by vitoramaral10** [comment]
Hello, the bug has returned in version 3.13.6, please be careful with releases so as not to keep bringing back bugs that have already been fixed.
