### ISSUE TITLE
[Impeller] `LayerTree::Preroll` and `::Paint` use different criteria for `impeller_enabled` flag.

### ISSUE THREAD

**Issue by flar** [flutter/flutter#134689]
See https://github.com/flutter/engine/blob/cd90cc8469fbc789e0b44adc79f330f8d4d2744c/flow/layers/layer_tree.cc#L63
and https://github.com/flutter/engine/blob/cd90cc8469fbc789e0b44adc79f330f8d4d2744c/flow/layers/layer_tree.cc#L143

The flag was introduced in https://github.com/flutter/engine/pull/43759

I believe they should both use `!!frame.aiks_context()` as a criteria, but Preroll is using `!frame.gr_context()`.

For now it could lead to inconsistent behavior between the two methods, but this led to a crash (see b/298583505) in the ["lazy RasterCache" PR](https://github.com/flutter/engine/pull/45211) where Preroll assumed that the RCI could be left lazily null and the Paint method got different answers and dereferenced it.

The inconsistency in the initialization of the flag fixes the crash on its own and it should be fixed in any case as it can lead to inconsistent behavior, but the PR could also be written more defensively in case another logic issue creates an unexpected lazy allocation.

**Comment by jonahwilliams** [comment]
Fixed via revert in https://github.com/flutter/engine/pull/46113
