### ISSUE TITLE
Flutter build_deps scripts not compatible with glinux (rodete)

### ISSUE THREAD

**Issue by crelier** [flutter/flutter#13460]
## Steps to Reproduce

Per instructions in https://github.com/flutter/engine/blob/master/CONTRIBUTING.md, try to run these scripts on a glinux workstation (fresh install of rodete, not in-place upgrade of goobuntu, in case that matters):
sudo ./build/install-build-deps-android.sh
sudo ./build/install-build-deps.sh

The second script is called by the first one.
The second one needs to be patched to understand "rodete" like this
debian_codenames="(stretch|rodete)"
and you still need to adjust the list of packages (e.g. "libpng12-0 " must be removed).
Then, the first script cannot install the openjdk:

> Package openjdk-7-jre is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> E: Package 'openjdk-7-jre' has no installation candidate
> 

The next issue may be a consequence of the above:

> + cd /usr/local/google/home/regis/flutter/examples/flutter_gallery
> + flutter run --release --local-engine=android_release --local-engine-src-path=/usr/local/google/home/regis/flutter/engine/src
> Initializing gradle...                                0.9s
> Resolving dependencies...                                /
> 
> * Error running Gradle:
> Unable to download needed Android SDK components, as the following licenses have not been accepted:
> Android SDK Build-Tools 25.0.3, Android SDK Platform 25
> 
> To resolve this, please run the following command in a Terminal:
> flutter doctor --android-licenses
> 

Executing "flutter doctor" does not complain, see output below, but "flutter doctor --android-licenses" as suggested by the error above results in a crash:

> flutter doctor --android-licenses
> 
> Oops; flutter has exited unexpectedly.
> Sending crash report to Google.
> Crash report sent (report ID: ed723858534243a6)
> Crash report written to /usr/local/google/home/regis/flutter/engine/src/flutter_04.log;
> please let us know at https://github.com/flutter/flutter/issues.
> 

The log is pasted below:
## Logs

> Flutter crash report; please file at https://github.com/flutter/flutter/issues.
> 
> ## command
> 
> flutter doctor --android-licenses
> 
> ## exception
> 
> ArgumentError: Invalid argument(s): Cannot find executable for /usr/local/google/home/regis/flutter/engine/src/third_party/android_tools/sdk/tools/bin/sdkmanager.
> 
> ```
> #0      _getExecutable (package:process/src/interface/local_process_manager.dart:113)
> #1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:41)
> #2      runCommand (package:flutter_tools/src/base/process.dart:108)
> #3      AndroidWorkflow.runLicenseManager (package:flutter_tools/src/android/android_workflow.dart:193)
> <asynchronous suspension>
> #4      Doctor.diagnose (package:flutter_tools/src/doctor.dart:101)
> <asynchronous suspension>
> #5      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:27)
> <asynchronous suspension>
> #6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:256)
> <asynchronous suspension>
> #7      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:196)
> <asynchronous suspension>
> #8      CommandRunner.runCommand (package:args/command_runner.dart:194)
> <asynchronous suspension>
> #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:279)
> <asynchronous suspension>
> #10     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
> #11     new Future.sync (dart:async/future.dart:222)
> #12     CommandRunner.run (package:args/command_runner.dart:109)
> #13     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:162)
> #14     run.<anonymous closure> (package:flutter_tools/runner.dart:89)
> <asynchronous suspension>
> #15     AppContext._run (package:flutter_tools/src/base/context.dart:76)
> <asynchronous suspension>
> #16     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
> #17     _rootRun (dart:async/zone.dart:1120)
> #18     _CustomZone.run (dart:async/zone.dart:1001)
> #19     runZoned (dart:async/zone.dart:1467)
> #20     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
> #21     run (package:flutter_tools/runner.dart:60)
> <asynchronous suspension>
> #22     main (package:flutter_tools/executable.dart:43)
> <asynchronous suspension>
> #23     main (file:///usr/local/google/home/regis/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
> #24     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
> #25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
> ```
> 
> ## flutter doctor
> 
> ```
> [✓] Flutter (on Linux, locale en_US.UTF-8, channel master)
>     • Flutter at /usr/local/google/home/regis/flutter
>     • Framework revision 3979dafaed (22 hours ago), 2017-12-07 15:34:42 -0800
>     • Engine revision f888186e50
>     • Tools Dart version 1.25.0-dev.11.0
>     • Engine Dart version 2.0.0-edge.e7b7b68ef6e7b1e5df379b628134764c489901dc
> 
> [✓] Android toolchain - develop for Android devices (Android SDK 22.0.1)
>     • Android SDK at /usr/local/google/home/regis/flutter/engine/src/third_party/android_tools/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-22, build-tools 22.0.1
>     • Java binary at: /usr/local/buildtools/java/jdk/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_112-google-v7-177054630-176677371)
> 
> [✗] Android Studio (not installed)
>     • Android Studio not found; download from https://developer.android.com/studio/index.html
>       (or visit https://flutter.io/setup/#android-setup for detailed instructions).
> 
> [✓] Connected devices
>     • Nexus 4 • 04ea030e56956826 • android-arm • Android 5.1.1 (API 22)
> 
> ```
> 
>

**Comment by crelier** [comment]
The doctor prescribed Android Studio, which I installed.

At least, "flutter doctor --android-licenses" is succeeding, but "flutter run ..." still complains that I need to run "flutter doctor --android-licenses", which I just did.

> regis@belenos:~/flutter/engine/src$ flutter doctor
> [✓] Flutter (on Linux, locale en_US.UTF-8, channel master)
>     • Flutter at /usr/local/google/home/regis/flutter
>     • Framework revision 3979dafaed (22 hours ago), 2017-12-07 15:34:42 -0800
>     • Engine revision f888186e50
>     • Tools Dart version 1.25.0-dev.11.0
>     • Engine Dart version 2.0.0-edge.e7b7b68ef6e7b1e5df379b628134764c489901dc
> [✓] Android toolchain - develop for Android devices (Android SDK 27.0.2)
>     • Android SDK at /usr/local/google/home/regis/Android/Sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-27, build-tools 27.0.2
>     • Java binary at: /usr/local/google/home/regis/android-studio/jre/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
> [✓] Android Studio (version 3.0)
>     • Android Studio at /usr/local/google/home/regis/android-studio
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
> [✓] Connected devices
>     • Nexus 4 • 04ea030e56956826 • android-arm • Android 5.1.1 (API 22)
> regis@belenos:~/flutter/engine/src$ flutter doctor --android-licenses
> Warning: File /usr/local/google/home/regis/.android/repositories.cfg could not be loaded.
> All SDK package licenses accepted.======] 100% Computing updates...             
> regis@belenos:~/flutter/engine/src$ test_flutter.sh 
> + cd /usr/local/google/home/regis/flutter/examples/flutter_gallery
> + flutter run --release --local-engine=android_release --local-engine-src-path=/usr/local/google/home/regis/flutter/engine/src
> Initializing gradle...                                0.8s
> Resolving dependencies...                                -
> * Error running Gradle:
> Unable to download needed Android SDK components, as the following licenses have not been accepted:
> Android SDK Build-Tools 25.0.3, Android SDK Platform 25
> To resolve this, please run the following command in a Terminal:
> flutter doctor --android-licenses
> 
>

**Comment by crelier** [comment]
Apparently, openjdk-8-jre and openjdk-8-jdk are already installed on rodete. So the script install-build-deps-android.sh should handle $lsb_release == "rodete" exactly as $lsb_release == "xenial".

**Comment by a-siva** [comment]
cc @jakobr-google @tvolkert @cbracken

**Comment by chinmaygarde** [comment]
I think we should go ahead and add that conditional check to the `install-build-deps-android.sh` script. @a-siva mentioned that this only happens for users that are using a fresh Rodete image (instead of performing an in-place update).

**Comment by crelier** [comment]
@chinmaygarde, I do not have access to flutter buildroot. I have tested the patches below and they work on my rodete workstation, which was a fresh install.
Would you mind taking care of the actual pull request to flutter buildroot? Thanks.
```
diff --git a/build/install-build-deps-android.sh b/build/install-build-deps-android.sh
index 7b3d167..cde747c 100755
--- a/build/install-build-deps-android.sh
+++ b/build/install-build-deps-android.sh
@@ -56,7 +56,7 @@ else
   sudo apt-get -y install libncurses5:i386 libstdc++6:i386 zlib1g:i386
 fi
 
-if [[ $lsb_release == "xenial" ]]; then
+if [[ $lsb_release == "xenial" || $lsb_release == "rodete" ]]; then
   sudo apt-get -y install openjdk-8-jre openjdk-8-jdk
   sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
   sudo apt-get -y install ant
diff --git a/build/install-build-deps.sh b/build/install-build-deps.sh
index a40a4a6..932772d 100755
--- a/build/install-build-deps.sh
+++ b/build/install-build-deps.sh
@@ -66,7 +66,7 @@ fi
 distro=$(lsb_release --id --short)
 codename=$(lsb_release --codename --short)
 ubuntu_codenames="(precise|trusty|utopic|vivid|xenial)"
-debian_codenames="(stretch)"
+debian_codenames="(stretch|rodete)"
 if [ 0 -eq "${do_unsupported-0}" ] && [ 0 -eq "${do_quick_check-0}" ] ; then
   if [[ ! $codename =~ $ubuntu_codenames && ! $codename =~ $debian_codenames ]]; then
     echo "ERROR: Only Ubuntu 12.04 (precise), 14.04 (trusty), " \
@@ -105,7 +105,7 @@ dev_list="bison cdbs curl dpkg-dev elfutils devscripts fakeroot
 lib_list="libatk1.0-0 libc6 libasound2 libcairo2 libcap2 libcups2 libexpat1
           libexif12 libfontconfig1 libfreetype6 libglib2.0-0 libgnome-keyring0
           libgtk2.0-0 libpam0g libpango1.0-0 libpci3 libpcre3 libpixman-1-0
-          libpng12-0 libspeechd2 libstdc++6 libsqlite3-0 libx11-6
+          libspeechd2 libstdc++6 libsqlite3-0 libx11-6
           libxau6 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxdmcp6
           libxext6 libxfixes3 libxi6 libxinerama1 libxrandr2 libxrender1
           libxtst6 zlib1g"
@@ -184,7 +184,11 @@ if package_exists libbrlapi0.6; then
 else
   dev_list="${dev_list} libbrlapi0.5"
 fi
-
+if package_exists libpng16-16; then
+  lib_list="$lib_list libpng16-16"
+else
+  lib_list="$lib_list libpng12-0"
+fi
 
 # Some packages are only needed if the distribution actually supports
 # installing them.
```

**Comment by mit-mit** [comment]
Removing 'first hour' label; that is meant for issues that new Flutter developers experience in their first few hours of using Flutter.

**Comment by gspencergoog** [comment]
I tried this patch out on my newly updated Rodete system, and I had to add Rodete as an additionally allowed codename.

Here's my patch (which includes the above patches): [patch.txt](https://github.com/flutter/flutter/files/1637368/patch.txt)

It runs, but if you answer "Y" to the question about installing symbols, it fails: [Symbols_fail.log](https://github.com/flutter/flutter/files/1637370/Symbols_fail.log)

I'm still unable to compile the engine after that, but that's a separate issue, I think.

**Comment by tvolkert** [comment]
Was this fixed by https://github.com/flutter/buildroot/commit/c947b7aa6a57d3c427d63692e530f23b1f77d81e?

**Comment by gspencergoog** [comment]
Yes
