### ISSUE TITLE
[flutter_test] setUpAll should not call the same function twice

### ISSUE THREAD

**Issue by lesnitsky** [flutter/flutter#134658]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

`setUpAll` calls the same function for every `setUpAll` call.

### Proposal

it's common to have multiple entry points to be able to debug only a subset of tests in large projects. That's why `setUpAll` should be called in several places.

GIven the following structure:

```
integration_test
  package_a/package_a_test.dart
  package_b/package_b_test.dart
  all_test.dart
```

`all_test.dart`

```dart
import './package_a/package_a.dart' as package_a_e2e;
import './package_b/package_b.dart' as package_b_e2e;

void main() {
  setUpAll(prepare):

  package_a_e2e.main();
  package_b_e2e.main();
}
```

is a CI entry point, but you will likely debug `package_a/package_a.dart` directly on your local setup, so `setUpAll(prepare);` should be called there as well.

My proposal is to have `setUpAll` memorize already-called functions and call them only once.

**Comment by huycozy** [comment]
Thanks for the report, @lesnitsky 
Could you please provide the complete sample code above here? And please share the steps to reproduce the issue you are seeing as well. Thanks!
