### ISSUE TITLE
Enabling pixel tests in prod

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#134698]
More than 20 pixel tasks have been running in the staging pool
<img width="833" alt="Screenshot 2023-09-13 at 3 42 49 PM" src="https://github.com/flutter/flutter/assets/54558023/4a5d7ac9-257a-46cf-a35f-a368ed65e321">

, and some of them have been passing consistently and are being promoted to prod:
https://github.com/flutter/flutter/pulls?q=is%3Aopen+is%3Apr+author%3Afluttergithubbot+pixel

However, we do not seem to have any testbeds available in the prod pool.
/cc @yusuf-goog @zanderso What is our plan for these targets and the corresponding testbeds?

**Comment by zanderso** [comment]
IIUC, we need to have some pixel devices moved to the prod pool. I have more sitting next to me whenever the lab is ready for that =)

**Comment by yusuf-goog** [comment]
We are waiting on the go ahead to add them to prod.

**Comment by yusuf-goog** [comment]
Looks like initial tests are successful. 

We can start the roll out. There are a few questions to answer:
* do we want to swap out all the existing moto G4 with the Pixels?
* Are there anything to think about regarding our performance testing to make sure we get metrics moved over nicely.
* I will double check ci.yaml to ensure that builds will roll over to the Pixels correctly when they are added.

**Comment by yusuf-goog** [comment]
I am handing over 19 Pixels to @kentnguyen99 to prepare them for use.

**Comment by yusuf-goog** [comment]
@zanderso 2 pixels are in prod (linux-19,20). And others will come in late next week, we are waiting on delivery of some equipment.

We can move one or two builders over to prod to run on these new devices and let them bake.

**Comment by yusuf-goog** [comment]
linux-41..49 moved to prod, and linux-26 moved to try pools.

**Comment by yusuf-goog** [comment]
All pixels have been moved to the relevant pools.

**Comment by yusuf-goog** [comment]
Pixel 7 Pro bot distribution:
Prod: 18
Staging: 9 (linux) + 1 (mac)
Try: 2

**Comment by keyonghan** [comment]
Following up on this bug, seems we still have 14 pixel targets running in staging. Is this expected or shall we move them to prod as well?
<img width="506" alt="Screenshot 2023-10-23 at 2 59 09 PM" src="https://github.com/flutter/flutter/assets/54558023/b93750a3-36b5-4deb-9ba7-52d825e27650">

**Comment by zanderso** [comment]
The Impeller on Android tests should stay in staging.
