### ISSUE TITLE
3.13.3 released artifacts changed

### ISSUE THREAD

**Issue by StephenWithPH** [flutter/flutter#134690]
### Is there an existing issue for this?

- [X] I have searched the [existing infra issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-infra)

### Type of Request

bug

### Infrastructure Environment

LUCI, Github, Cocoon scheduler, Autosubmit, etc...

### What is happening?

In the last ~60 minutes, a new, duplicated set of `3.13.3` release artifacts appeared:

<img width="1286" alt="Screenshot 2023-09-13 at 2 34 33 PM" src="https://github.com/flutter/flutter/assets/2990492/6741842d-2106-42c7-8147-9e4a027c9650">

The json (truncated below) also has two results:

```json
{
  "base_url": "https://storage.googleapis.com/flutter_infra_release/releases",
  "current_release": {
    "beta": "123453dc41ef48e717939dd3c012db6a23138895",
    "dev": "13a2fb10b838971ce211230f8ffdd094c14af02c",
    "stable": "367f9ea16bfae1ca451b9cc27c1366870b187ae2"
  },
  "releases": [
    {
      "hash": "367f9ea16bfae1ca451b9cc27c1366870b187ae2",
      "channel": "stable",
      "version": "3.13.4",
      "dart_sdk_version": "3.1.2",
      "dart_sdk_arch": "x64",
      "release_date": "2023-09-13T20:12:13.313067Z",
      "archive": "stable/linux/flutter_linux_3.13.4-stable.tar.xz",
      "sha256": "d9bbfbfb6fe3c72a29c1040235126edd0cd461e4e18556335fd1cf217c2e1473"
    },
    {
      "hash": "b0daa737b75b007b4777e5cc2bd42b1b18a6fd4f",
      "channel": "stable",
      "version": "3.13.3",
      "dart_sdk_version": "3.1.1",
      "dart_sdk_arch": "x64",
      "release_date": "2023-09-13T19:53:41.927127Z",
      "archive": "stable/linux/flutter_linux_3.13.3-stable.tar.xz",
      "sha256": "4fc057286135d4b7559db7d735a235753e273f284219b2e9d2f77aa455dd923e"
    },
    {
      "hash": "2524052335ec76bb03e04ede244b071f1b86d190",
      "channel": "stable",
      "version": "3.13.3",
      "dart_sdk_version": "3.1.1",
      "dart_sdk_arch": "x64",
      "release_date": "2023-09-07T17:19:53.810487Z",
      "archive": "stable/linux/flutter_linux_3.13.3-stable.tar.xz",
      "sha256": "c53c8aeff17d13c4c0b47bff2c54a293e48286e03dd089f37d561737e41a8c2c"
    }
  ]
}
```

It appears that the newer of the two `3.13.3` artifacts overwrote the old one.

I noticed this because the (original) checksum for `3.13.3` no longer matches the downloaded file.

**Comment by XilaiZhang** [comment]
from triage: @drewroengoogle @godofredoc has this been fixed now? thank you!

**Comment by XilaiZhang** [comment]
From triage: synced with Drew and will close this in favor of the post mortem
