### ISSUE TITLE
Google testing failure missing triage info

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#134668]
Example RP: https://github.com/flutter/flutter/pull/134637

<img width="1048" alt="Screenshot 2023-09-13 at 9 16 08 AM" src="https://github.com/flutter/flutter/assets/54558023/800a09c1-f33c-4b63-b1f5-8cd1b198815c">

By clicking `details`, here is the check run page:
https://github.com/flutter/flutter/pull/134637/checks?check_run_id=16761209576

The [View more details on Flutter Roll on Borg](https://github.com/flutter/flutter/wiki/Understanding-Google-Testing#my-cl-reached-max-number-of-retry-why-and-how-do-i-resolve-this) however directs to the wiki page as well. 

Not sure how to debug this failure.

**Comment by keyonghan** [comment]
@XilaiZhang Could you help take a look?

**Comment by ricardoamador** [comment]
https://github.com/flutter/flutter/wiki/Understanding-Google-Testing#my-cl-reached-max-number-of-retry-why-and-how-do-i-resolve-this

This is concerning as the only solution offered is to ask a Googler to investigate or follow the solutions below:  
1. rebase and ignore google testing which it looks like you cannot or 
2. wait for commits to catch up and hope the conflict is resolved then resubmit or 
3. manually override if you are a Googler, which you can no longer do.

Can we revert this functionality at this time?

**Comment by ricardoamador** [comment]
Some more examples of this: 
https://github.com/flutter/flutter/pull/134629
https://github.com/flutter/flutter/pull/134628
https://github.com/flutter/flutter/pull/134607

**Comment by keyonghan** [comment]
Marking as P1 considering high impact but there is a workaround to reset the test status considering this is a false alarm.

**Comment by XilaiZhang** [comment]
sent cl/565087659 for review and put more context in https://github.com/flutter/flutter/pull/134637#issuecomment-1718048841

**Comment by vashworth** [comment]
I have a couple PRs (https://github.com/flutter/flutter/pull/134493, https://github.com/flutter/flutter/pull/134542) that are having this issue to. Will overriding the status even work if FroB says it's "Deleted" and there's no CL?

**Comment by XilaiZhang** [comment]
yes it would work even if its deleted and theres no cl

**Comment by XilaiZhang** [comment]
umm i tried the same with autosubmit but for some reasons autosubmit merged it. Would be great if you could file a bug and document what happened. thank you!

**Comment by ricardoamador** [comment]
Latency in reporting the status?

**Comment by christopherfujino** [comment]
> Latency in reporting the status?

It went from red -> green -> red again? and persisted red, until Xilai overrode it a second time from FRoB.

**Comment by ricardoamador** [comment]
> > Latency in reporting the status?
> 
> It went from red -> green -> red again? and persisted red, until Xilai overrode it a second time from FRoB.

I did not know that.

**Comment by christopherfujino** [comment]
This happened again on https://github.com/flutter/flutter/pull/134590 cc @XilaiZhang

**Comment by christopherfujino** [comment]
I will file a separate issue for this

**Comment by ricardoamador** [comment]
Isn't that part of this issue? Also what is the work around here then? Do you need to go on Frob and toggle the status to land the PR? I am assuming you do not since you can squash and merge in flutter.

**Comment by christopherfujino** [comment]
> Isn't that part of this issue? Also what is the work around here then?

If you're referring to https://github.com/flutter/flutter/issues/134684, it is not obvious to me that it is the same issue as this one. I will defer to you however if you think it is the same issue.

**Comment by ricardoamador** [comment]
@christopherfujino no I am fine with this, I thought the actual issue was the one you pointed out. My mistake I thought there were two issues beyond the missing triage info. Please keep it open.

**Comment by drewroengoogle** [comment]
Hi @XilaiZhang, any updates on this? Just caught up on the thread

**Comment by XilaiZhang** [comment]
Yeah i sent updates in the PSA on Saturday

**Comment by drewroengoogle** [comment]
Gotcha. Thanks! I will close this, but feel free to reopen if necessary.
