### ISSUE TITLE
Flutter API style guide doesn't have opinion about how to indicate deprecated

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#13463]
I'd like to indicate to developers that they should prefer dart:io's createHttpClient instead of services.dart's createHttpClient.

I checked https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo to see if we have a style/opinion on documenting deprecation. I didn't find it, though I could have missed it.

Specific questions:

* do I literally use `@deprecated` ?
* If not, do we have a preference for using the word "deprecated"

**Comment by sethladd** [comment]
cc @Hixie

**Comment by Hixie** [comment]
See https://flutter.io/design-principles/#handling-breaking-changes

**Comment by Hixie** [comment]
But yes, @deprecated is the way we would do it. Except that if you do that, it'll make the build red because we use it and @deprecated means we shouldn't use it. :-)

**Comment by sethladd** [comment]
Hence my question :)

**Comment by sethladd** [comment]
In the meantime, I've added https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#clearly-mark-deprecated-apis to the Wiki. Of course, feel free to update.

**Comment by Hixie** [comment]
looks good
