### ISSUE TITLE
Vulkan unit tests log spam `error: XDG_RUNTIME_DIR not set`

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#134677]
[Example run](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8770053821110000177/+/u/test:_Host_Tests_for_host_debug_impeller_vulkan/stdout):

```txt
[----------] 126 tests from Play/EntityTest
[ RUN      ] Play/EntityTest.ThreeStrokesInOnePath/Metal
../../flutter/impeller/playground/playground_test.cc:20: Skipped
Playground doesn't support this backend type.
[  SKIPPED ] Play/EntityTest.ThreeStrokesInOnePath/Metal (62 ms)
[ RUN      ] Play/EntityTest.CanCreateEntity/Vulkan
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
[       OK ] Play/EntityTest.CanCreateEntity/Vulkan (351 ms)
[ RUN      ] Play/EntityTest.ColorMatrixFilterEditable/Metal
../../flutter/impeller/playground/playground_test.cc:20: Skipped
Playground doesn't support this backend type.
[  SKIPPED ] Play/EntityTest.ColorMatrixFilterEditable/Metal (0 ms)
[ RUN      ] Play/EntityTest.ColorFilterWithForegroundColorClearBlend/Vulkan
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
[       OK ] Play/EntityTest.ColorFilterWithForegroundColorClearBlend/Vulkan (378 ms)
[ RUN      ] Play/EntityTest.TriangleInsideASquare/Vulkan
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
```

I am guessing this is fine (or maybe it's a sign of misconfiguration). I don't know a ton unfortunately.

Here is what I looked up potentially related on the web:

- https://github.com/search?q=+%22XDG_RUNTIME_DIR+not+set+in+the+environment%22&type=code
- https://www.reddit.com/r/swaywm/comments/133cgi5/issue_xdg_runtime_dir_is_not_set_in_the/

It would be nice to fix this because for someone who isn't intimately familiar with what errors are "expected" in CI logs, this was a false flag when I was just starting.

**Comment by chinmaygarde** [comment]
This may be an artifact of WSI integration with GLFW. Definitely not a log we control.

**Comment by chinmaygarde** [comment]
Since this isn't a log we emit, not sure what we can do about this. Closing this can cant-fix.
