### ISSUE TITLE
[two_dimensional_scrollview] The default scroll experience is different from one dimensional scrollview

### ISSUE THREAD

**Issue by ZhiwenLuoAllIn** [flutter/flutter#134702]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Hello, all:

Recently I'm trying to implement the two-dimensional scrolling experience by using the sample code from [**Here**](https://dartpad.dev/?id=4424936c57ed13093eb389123383e894).

And I found that the scrolling experience is kind of different from one-dimensional scrolling.

Here is a video. Seems during scrolling the user's gesture is ignored. I'm not sure is it by design or it might have attribute somewhere I can override this behavior. 

https://github.com/flutter/flutter/assets/107196519/2c57de1a-d0be-47e7-987e-acfb89aeeca9

#### Environment
```
Flutter 3.13.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2524052335 (7 days ago) • 2023-09-06 14:32:31 -0700
Engine • revision b8d35810e9
Tools • Dart 3.1.1 • DevTools 2.25.0
```

### Proposal

What I'm expected is that it can accelerate the speed during scrolling just like the one-dimensional scrollview.

**Comment by danagbemava-nc** [comment]
Hi @ZhiwenLuoAllIn. this is a known issue and is being tracked in https://github.com/flutter/flutter/issues/133529. 

Kindly follow up in the original issue for updates. 

Closing from here as duplicate. 

Thank you
