### ISSUE TITLE
IOS App crash when picking image/video on latest IOS version 16.6.1

### ISSUE THREAD

**Issue by ashanftw** [flutter/flutter#134753]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

works perfectly on previous ios version but in latest 16.6.1 as soon as i call below methods app automatically crashed and closed by itself

final XFile? photo = await _picker.pickImage();
final XFile? video = await _picker.pickVideo();

### Expected results

should open gallery/camera based on the source

### Actual results

IOS App crashing immidiately

### Code sample

final XFile? photo = await _picker.pickImage();
final XFile? video = await _picker.pickVideo();

### Logs

<details><summary>Logs</summary>

```console
No logs
```

</details>

### Flutter Doctor output

[√] Flutter (Channel stable, 3.13.2, on Microsoft Windows [Version 10.0.22621.755], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Android Studio (version 2022.1)
[√] Connected device (1 available)
[√] Network resources

**Comment by Karthikeyanarla** [comment]
@ashanftw,
please provide with some reproducible code.
It would be easier to check up with the issue

**Comment by ashanftw** [comment]
> @ashanftw, please provide with some reproducible code. It would be easier to check up with the issue

Hi @Karthikeyanarla ,
IOS 16.6.1 App crash when i try to pick image using any of the below methods in image_picker. 

final XFile? image = await picker.pickImage(source: ImageSource.gallery);
final XFile? photo = await picker.pickImage(source: ImageSource.camera);

final XFile? video= await picker.pickVideo(source: ImageSource.gallery);
final XFile? video= await picker.pickVideo(source: ImageSource.camera);

**Comment by danagbemava-nc** [comment]
Hi @ashanftw, can you share the crash log that you get? Can you also upgrade the stable 3.13.4 to see if you staill face this issue? I just run the image_picker sample code on iOS 16.6.1 and I could not reproduce a crash.

**Comment by ashanftw** [comment]
> Hi @ashanftw, can you share the crash log that you get? Can you also upgrade the stable 3.13.4 to see if you still face this issue? I just run the image_picker sample code on iOS 16.6.1 and I could not reproduce a crash.

Ill try this and see. but i disable impeller in ios permission and the issue went away. Anyways thanks for your support
<key>FLTEnableImpeller</key>
<false />

**Comment by ashanftw** [comment]
close the issue since i was able to solve this.
