### ISSUE TITLE
PathProvider should provide a way to access the Library directory

### ISSUE THREAD

**Issue by sroddy** [flutter/flutter#13474]
Currently under iOS PathProvider `getApplicationDocumentsDirectory` method returns the Documents directory.

It should be noted that this is NOT (or at least SHOULD NOT be) the standard path where an iOS app stores its data!

From https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html

> Use this directory (Documents directory - ed.) to store user-generated content. The contents of this directory can be made available to the user through file sharing; therefore, this directory should only contain files that you may wish to expose to the user.

> Use the Library subdirectories for any files you don’t want exposed to the user. Your app should not use these directories for user data files.

Content in both directories is automatically backed up by iCloud.

BTW, It's currently very easy to access this directory (documents + '../Library') but the workaround is system-specific and not really future-proof.

As Android doesn't differentiate between the two, I think we can safely add a `getApplicationLibraryDirectory` that returns the AppData dir (the same as `getApplicationDocumentsDirectory`) under Android and the Library dir under iOS.
Maybe this is not ideal, but at least won't break BC.

I can provide a PR if the maintainer likes this approach.

**Comment by sroddy** [comment]
The more I think about this, the more I think that the current API design of this plugin is a bit off.
The main issue is that actually the iOS Documents directory is much closer to the Android External Storage directory than the AppData directory, while the AppData directory is closer to the Library (or even the `Library/Application Support`) directory.

I think that this plugin should actually have three cross-platform methods:
- `getApplicationLibraryDirectory` which maps to `NSLibraryDirectory` (or maybe `NSApplicationSupportDirectory` which is even more standard) on iOS and `AppData` on Android
- `getApplicationDocumentsDirectory`: which maps to `NSDocumentDirectory` on iOS and the External storage path on Android.
- the `getTemporaryDirectory` which should be ok as it is now (although there are some subtle differences between Caches and tmp under iOS).

On top of these methods the plugin can provide platform-specific methods (e.g. android appdata and external storage, direct access to iOS `NSSearchPathForDirectoriesInDomains`, etc.).

Unfortunately this approach would completely destroy BC, unless we introduce these methods with brand new names (e.g. `getLibraryDirectory`, `getDocumentsDirectory`, etc.) and put the old ones as deprecated.

**Comment by thosakwe** [comment]
I just want to mention, `path_provider` doesn't seem to work on iOS 11.2.

**Comment by bsjosten** [comment]
I agree with sroddy that we need a getApplicationLibraryDirectory method. Also needed is a way to set files to not be backed up, for application files that can easily be recreated/downloaded.

Any action on this issue?

**Comment by iNima** [comment]
Any new update on this issue?

**Comment by collinjackson** [comment]
I agree there should be some way to get the something like the NSApplicationSupportDirectory on iOS. Please see https://github.com/flutter/plugins/pull/1566.

Having `getApplicationDocumentsDirectory` give external storage by default seems like it might not be a great experience since sometimes external storage isn't available (including on simulators). Can developers try external storage and fall back on the documents directory if it can't be written?
