### ISSUE TITLE
Uninstall/cleanup apps in android devices after task finishes

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#134782]
Android devices occasionally hit issues like insufficient storage, and we need to auto cleanup after task finishes to avoid:
go/flutter-luci-playbook#android-install-failed-insufficient-storage

The logic has been there for iOS devices, and we should do the same for android devices.

1) add logic to device doctor
2) enable `recovery` action in bot config.

**Comment by godofredoc** [comment]
@yusuf-goog is this something you can help us with?  full device storage is causing a lot of flakiness

**Comment by yusuf-goog** [comment]
Is this something we want to only do when the device hits a bad state, or do we want to cleanup after each run?

**Comment by keyonghan** [comment]
We want to clean up whenever a task fails: https://chrome-internal.googlesource.com/infradata/config/+/refs/heads/main/configs/chromium-swarm/scripts/flutter_android_staging.py#191

**Comment by keyonghan** [comment]
This has been implemented.
