### ISSUE TITLE
Mocking `vk::[Unique]Fence` for tests.

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#134785]
In https://github.com/flutter/flutter/issues/134751, I'm going to be tweaking a refactoring [`FenceWaiterVK`](https://github.com/flutter/engine/blob/f5f1a96017b9bfba7b0f1c262452ae95d48d5ce0/impeller/renderer/backend/vulkan/fence_waiter_vk.cc), which is algorithmically complex, and uses a lot of code susceptible to race conditions or edge cases, which is a perfect candidate for some unit testing.

Imagine this test case, which catches that terminating the fence waiter still waits for outstanding fences:

```cc
// This is an *imagined* test, and does not actually exist, and might have slight logical errors.

TEST(FenceWaiterVKTest, WhenTerminatedStillWaitsOnFences) {
  auto waiter = context->GetFenceWaiter();
  auto fence = FakeFence();
  auto signal = fml::ResetSignal();

  waiter.AddFence(fence, [&signal]() { signal.Notify(); });
  waiter.Terminate();
  fence.MarkSignalDone();

  signal.Wait();
}
```

---

We use `vk::UniqueFence`, which is a unique-pointer-like object provided by Vulkan (called ["Smart Handles"](https://www.reddit.com/r/vulkan/comments/f74crh/managing_vulkan_handles_and_their_lifespan_in_c/)):

[`swapchain_impl_vk.cc`](https://github.com/flutter/engine/blob/f5f1a96017b9bfba7b0f1c262452ae95d48d5ce0/impeller/renderer/backend/vulkan/command_encoder_vk.cc#L188):
```cc
    auto acquire_res = device.createFenceUnique(
        vk::FenceCreateInfo{vk::FenceCreateFlagBits::eSignaled});
```

[`command_encoder_vk.cc`](https://github.com/flutter/engine/blob/f5f1a96017b9bfba7b0f1c262452ae95d48d5ce0/impeller/renderer/backend/vulkan/command_encoder_vk.cc#L188):
```cc
  auto [fence_result, fence] = strong_device->GetDevice().createFenceUnique({});
```

These smart handles, AFAICT, essentially work like `std::unique_ptr`, calling `vkDestroyFence` in the destructor. However, that also means they have lifecycle requirements that are non-trivial to emulate in a unit test (I fiddled a bit and realized that they assert that you aren't creating an invalid struct).

I can see a few options:

1. Do nothing, do not add unit testing.

    I think this is a non-starter to be able to algorithmically check this stuff.

2. Remove our uses of `device.createFenceUnique` and replace with our own `FenceVK` objects that do the same thing.

    Alternatively, wrap `UniqueFence` in `FenceVK` objects and have our APIs take the wrapped object.

3. Use a template for `FenceWaiterVK`, and, in narrow unit tests, use a different self-authored type:

    ```h
    template <class FenceType>
    class FenceWaiterVK {
      void Add(T fence, fml::closure callback);
    }
    ```

    In production, it would be `FenceWaiterVK<vk::UniqueFence>`, and in tests, `FenceWaiterVK<MockFence>`.

4. Create a base or composition class, `FenceWaiter`, that algorithmically implements fence waiting.

    It would not depend on Vulkan, and be unit tested, and then `FenceWaiterVK` would implement itself with it.

**Comment by matanlurey** [comment]
I should add that my preference is narrowly (4), but I defer to the experts!

**Comment by gaaclarke** [comment]
I was thinking we could do something like this.
```c++
TEST(FenceWaiterVKTest, WhenTerminatedStillWaitsOnFences) {  
  auto fence = FakeFence();
  auto context = MockVulkanContextBuilder().InjectFences({fence}).Build();
  auto waiter = context->GetFenceWaiter();
  auto signal = fml::ResetSignal();

  waiter.AddFence(fence, [&signal]() { signal.Notify(); });
  waiter.Terminate();
  fence.MarkSignalDone();

  signal.Wait();
}
```

If the problem is with `vkDestroyFence` we can make that do whatever we want or have our `FakeFence` has some residual shared_ptr we still can access.  Is there a reason we can't do this?

**Comment by matanlurey** [comment]
> Is there a reason we can't do this?

Yes, because our API calls `vkCreateUniqueFence`, and we can't override / provide a mock object.

Your idea would work if we converted calls from `vkCreateUniqueFence` to `vkCreateFence`, but this is less of a "how do we setup the mock context" and more "how do we reference fences in Impeller" (see the example snippets above for what happens in a real app).

**Comment by gaaclarke** [comment]
> Yes, because our API calls vkCreateUniqueFence, and we can't override / provide a mock object.

`vkCreateUniqueFence` is just a raii c++ wrapper around vkFence creation and destruction (which call vkCreateFence and vkDestroyFence).

vkFence is an opaque pointer, it is never accessed or used by flutter or the c++ wrapper.  It can be replaced with a mock safely.  We control all the endpoints that actually create it, use it, and destroy it.

**Comment by matanlurey** [comment]
Either you're missing something or I am :)

> vkFence is an opaque pointer, it is never accessed or used by flutter or the c++ wrapper. It can be replaced with a mock safely. We control all the endpoints that actually create it, use it, and destroy it.

Yes, I totally get that. My point is our API calls `vkCreateUniqueFence`, _not_ `vkCreateFence`, and the RAII wrapper performs assertions to make sure the `vkFence` is a real fence.

**Comment by gaaclarke** [comment]
Yep, this is confusing stuff, happy to jump on a call if this doesn't clear it up.

There is no thing as `vkCreateUniqueFence`, that is just a c++ wrapper that calls the c api (vkCreateFence).  There is no such thing as a "real fence", a vkFence is whatever a driver decides it is.  Or in our case what our mock driver decides.

**Comment by matanlurey** [comment]
Let's do it!

**Comment by matanlurey** [comment]
Ok sorry for the confusion folks, @gaaclarke was _very_ right and this works out of the box. Closing as resolved!
