### ISSUE TITLE
Upgrade one chromium x86 bot to macOS 13.5+ from try pool

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#134742]
### Is there an existing issue for this?

- [X] I have searched the [existing infra issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-infra)

### Type of Request

infra task

### Infrastructure Environment

Devicelab

### What is happening?

Upgrade one chromium x86 bot to macOS 13.5+ from try pool

**Comment by yusuf-goog** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1484699 opened to upgrade.

**Comment by yusuf-goog** [comment]
https://chromium-swarm.appspot.com/bot?id=mac-47-g572 is at 13.5.2
