### ISSUE TITLE
[CP] Fix permissions on macos artifacts

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#134765]
### Issue Link

https://github.com/flutter/flutter/issues/132725

### Commit Hash

0cf5971438b45d8054a6d6fe14f9547abed39747

### Target

beta

### PR Link

https://github.com/flutter/engine/pull/45900

### Changelog Description

Fixes FlutterMacOS.framework file permissions that were set to readable by owner only.

### Impacted Users

Mac/iOS users publishing apps to app store

### Impact Description

FlutterMacOS.framework.zip included files that were readable/executable only by owner and was causing issues when publishing to the app store.

### Workaround

N/A

### Risk

low

### Test Coverage

yes

### Validation Steps

Automated and manual tests have been executed to ensure the fix is working propertly.

**Comment by godofredoc** [comment]
@gspencergoog this is the CP request for beta.

**Comment by gspencergoog** [comment]
![32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d](https://user-images.githubusercontent.com/8867023/37737237-66e9c9dc-2d10-11e8-8797-13a405eace49.png)

I think this is low risk, and fixes a critical issue that prevents some people from publishing to the app store.
