### ISSUE TITLE
Updating flutter tool

### ISSUE THREAD

**Issue by azerturk** [flutter/flutter#13479]
windows 10
flutter doctor
after "Updating flutter tool..."
gives error ".pub-cache was unexpected at this time."
I delete cache folder and disable firewall
run it again same result.

**Comment by azerturk** [comment]
when i install first time i run git clone from cmd at windows/system32 then i can't find flutter folder. After i run git clone from cmd at program files/git folder. It's not related with issue i thing. But i scan computer i'cant find flutter folder related with first install. But in git folder it's there after second install.

**Comment by azerturk** [comment]
It's related with windows maybe. I try flutter doctor at C:\ the error is gone.

**Comment by yassinereptor** [comment]
Just delete the cache folder in "flutter\bin" and try again flutter doctor the error is gone
