### ISSUE TITLE
The tree is closed on an infra issue

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#134727]
### Is there an existing issue for this?

- [X] I have searched the [existing infra issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-infra)

### Type of Request

bug

### Infrastructure Environment

No idea

### What is happening?

Please be descriptive.
<img width="1459" alt="Screenshot 2023-09-14 at 6 22 47 AM" src="https://github.com/flutter/flutter/assets/6343103/3cd0cf0b-bbb5-4e02-9320-77f7927cfe6d">

Every job has `failed to create a swarming task: context deadline exceeded`

### Expected results

The tree is open.

**Comment by zanderso** [comment]
cc @keyonghan the infra gardener

**Comment by keyonghan** [comment]
It's a LUCI outage happened midnight of 09/14/2023 due to some datastore errors. The service should be up and running again.

**Comment by keyonghan** [comment]
For context: https://crbug.com/1482657
