### ISSUE TITLE
Upgrade fleet to macOS 13

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#134737]
### Is there an existing issue for this?

- [X] I have searched the [existing infra issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-infra)

### Type of Request

infra task

### Infrastructure Environment

Devicelab

### What is happening?

Prerequisites: 
- [x] https://github.com/flutter/flutter/issues/134736

## Upgrade Phase 1 - Upgrade so 25% of bots are on macOS 13
Staging Pool
- [x] [[staging pool] x86 chromium bots](https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=os&c=status&d=asc&f=device_os%3Anone&f=pool%3Aluci.flutter.staging&f=cpu%3Ax86&f=os%3AMac&k=os&s=id)  - Upgrade 2 bots to macOS 13 (2 / 5)
- [x] [[staging pool] arm64 chromium bots](https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=os&c=status&d=asc&f=device_os%3Anone&f=pool%3Aluci.flutter.staging&f=cpu%3Aarm&f=os%3AMac&k=os&s=id)  - Upgrade 2 bots to macOS 13 (2 / 6)
- [x] [[staging pool] x86 iOS devicelab bots](https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=device_os&c=os&c=status&d=asc&f=device_os%3AiOS&f=pool%3Aluci.flutter.staging&f=cpu%3Ax86&f=os%3AMac&k=os&s=id)  - Upgrade 1 bots to macOS 13 (1 / 3)
- [x] [[staging pool] arm64 iOS devicelab bots](https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=device_os&c=os&c=status&d=asc&f=device_os%3AiOS&f=pool%3Aluci.flutter.staging&f=cpu%3Aarm&f=os%3AMac&k=os&s=id)  - Upgrade 1 bots to macOS 13 (2 / 5)
  * 1 is already upgraded so a total of 2
- [x] [[staging pool] x86 msm8952 devicelab bots](https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=device_os&c=device_type&c=os&c=status&d=asc&f=pool%3Aluci.flutter.staging&f=cpu%3Ax86&f=os%3AMac&f=device_type%3Amsm8952&k=device_type&s=id) - No upgrade (0 / 1)
  * There are no staging tests that use msm8952 devices, so we want to keep these on macOS 12 in case we need to move it into the try pool, which only has one.
- [x] [[staging pool] arm64 msm8952 devicelab bots](https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=device_os&c=device_type&c=os&c=status&d=asc&f=pool%3Aluci.flutter.staging&f=cpu%3Aarm64&f=os%3AMac&f=device_type%3Amsm8952&k=device_type&s=id) - Upgrade 1 bots to macOS 13 (1 / 3)

Try Pool
- [x] [[try pool] x86 chromium bots](https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=os&c=status&d=asc&f=device_os%3Anone&f=pool%3Aluci.flutter.try&f=cpu%3Ax86&f=os%3AMac&k=os&s=id) - Upgrade 14 bots to macOS 13 (16 / 63)
  * 2 are already upgraded so a total of 16
- [x] [[try pool] arm64 chromium bots](https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=os&c=status&d=asc&f=device_os%3Anone&f=pool%3Aluci.flutter.try&f=cpu%3Aarm&f=os%3AMac&k=os&s=id) - Upgrade 17 bots to macOS 13 (18 / 71)
  * 1 is already upgraded so a total of 18
- [x] [[try pool] x86 iOS devicelab bots](https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=device_os&c=os&c=status&d=asc&f=device_os%3AiOS&f=pool%3Aluci.flutter.try&f=cpu%3Ax86&f=os%3AMac&k=os&s=id) - Upgrade 1 bots to macOS 13 (1 / 3)
- [x] [[try pool] arm64 iOS devicelab bots](https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=device_os&c=os&c=status&d=asc&f=device_os%3AiOS&f=pool%3Aluci.flutter.try&f=cpu%3Aarm&f=os%3AMac&k=os&s=id) - Upgrade 1 bots to macOS 13 (1 / 3)
- [x] [[try pool] x86 msm8952 devicelab bots ](https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=device_os&c=device_type&c=os&c=status&d=asc&f=pool%3Aluci.flutter.try&f=cpu%3Ax86&f=os%3AMac&f=device_type%3Amsm8952&k=device_type&s=id)- No upgrade (0 / 1)
- [x] [[try pool] arm64 msm8952 devicelab bots](https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=device_os&c=device_type&c=os&c=status&d=asc&f=pool%3Aluci.flutter.try&f=cpu%3Aarm64&f=os%3AMac&f=device_type%3Amsm8952&k=device_type&s=id) - No bots

Prod Pool
- [x] [[prod pool] x86 chromium bots](https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=os&c=status&d=asc&f=device_os%3Anone&f=pool%3Aluci.flutter.prod&f=cpu%3Ax86&f=os%3AMac&k=os&s=id) - Upgrade 10 bots to macOS 13 (10 / 40)
- [x] [[prod pool] arm64 chromium bots](https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=os&c=status&d=asc&f=device_os%3Anone&f=pool%3Aluci.flutter.prod&f=cpu%3Aarm&f=os%3AMac&k=os&s=id) - Upgrade 8 bots to macOS 13 (8 / 31)
- [x] [[prod pool] x86 iOS devicelab bots](https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=device_os&c=os&c=status&d=asc&f=device_os%3AiOS&f=pool%3Aluci.flutter.prod&f=cpu%3Ax86&f=os%3AMac&k=os&s=id) - Upgrade 3 bots to macOS 13 (3 / 12)
- [x] [[prod pool] arm64 iOS devicelab bots](https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=device_os&c=os&c=status&d=asc&f=device_os%3AiOS&f=pool%3Aluci.flutter.prod&f=cpu%3Aarm&f=os%3AMac&k=os&s=id) - Upgrade 1 bots to macOS 13 (1 / 4)
- [x] [[prod pool] x86 msm8952 devicelab bots](https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=device_os&c=device_type&c=os&c=status&d=asc&f=pool%3Aluci.flutter.prod&f=cpu%3Ax86&f=os%3AMac&f=device_type%3Amsm8952&k=device_type&s=id) - Upgrade 1 bots to macOS 13 (1 / 4)
- [x] [[prod pool] arm64 msm8952 devicelab bots](https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=device_os&c=device_type&c=os&c=status&d=asc&f=pool%3Aluci.flutter.prod&f=cpu%3Aarm64&f=os%3AMac&f=device_type%3Amsm8952&k=device_type&s=id) - Upgrade 1 bots to macOS 13 (1 / 2)

## Upgrade Phase 2 - Upgrade so 50% of bots are on macOS 13
Staging Pool
- [x] [staging pool] x86 chromium bots  - Upgrade 1 bots to macOS 13 (3 / 5)
- [x] [staging pool] arm64 chromium bots  - Upgrade 8 bots to macOS 13 (10 / 19)
- [x] [staging pool] x86 iOS devicelab bots  - Upgrade 1 bots to macOS 13 (2 / 3)
- [x] [staging pool] arm64 iOS devicelab bots  - Upgrade 1 bots to macOS 13 (3 / 5)
- [ ] [staging pool] x86 msm8952 devicelab bots - Upgrade all to macOS 13 (1 / 1)
- [x] [staging pool] arm64 msm8952 devicelab bots - Upgrade 1 bots to macOS 13 (2 / 3)
- [x] [staging pool] x86 Pixel 7 Pro devicelab bots - Upgrade all to macOS 13 (1 / 1)

Try Pool
- [x] [try pool] x86 chromium bots - Upgrade 15 bots to macOS 13 (31 / 63)
- [x] [try pool] arm64 chromium bots - Upgrade 50 bots to macOS 13 (68 / 137) 
  * Only 49 bot upgraded but close enough - so total of (67 / 137)
- [x] [try pool] x86 iOS devicelab bots - Upgrade 1 bots to macOS 13 (2 / 3)
- [x] [try pool] arm64 iOS devicelab bots - Upgrade 1 bots to macOS 13 (2 / 3)
- [x] [try pool] x86 msm8952 devicelab bots - No upgrade (0 / 1)
- [x] [try pool] arm msm8952 devicelab bots - No bots
- [x] [try pool] x86 Pixel 7 Pro devicelab bots - Upgrade all to macOS 13 (1 / 1)

Prod Pool
- [x] [prod pool] x86 chromium bots - Upgrade 10 bots to macOS 13 (20 / 40)
- [x] [prod pool] arm64 chromium bots - Upgrade 24 bots to macOS 13 (32 / 64)
- [x] [prod pool] x86 iOS devicelab bots - Upgrade 3 bots to macOS 13 (6 / 12)
- [x] [prod pool] arm64 iOS devicelab bots - Upgrade 1 bots to macOS 13 (2 / 4)
- [x] [prod pool] x86 msm8952 devicelab bots - Upgrade 1 bots to macOS 13 (2 / 4)
- [x] [prod pool] arm64 msm8952 devicelab bots - No upgrade (1 / 2)

## Upgrade Phase 3 - Upgrade until bare minimum of bots remain
Staging Pool
- [x] [staging pool] Upgrade all to macOS 13 except 1 arm64 msm8952 devicelab bot

Try Pool
- [x] [try pool] x86 chromium bots - Keep 15 bots on macOS 12 and upgrade the rest to macOS 13 (48 / 63)
- [x] [try pool] arm64 chromium bots - Keep 15 bots on macOS 12 and upgrade the rest to macOS 13 (122 / 137)
- [x] [try pool] devicelab bots - No upgrade

Prod Pool
- [x] [prod pool] x86 chromium bots - Keep 15 bots on macOS 12 and upgrade the rest to macOS 13 (25 / 40)
- [x] [prod pool] arm64 chromium bots - Keep 15 bots on macOS 12 and upgrade the rest to macOS 13 (49 / 64)
- [x] [prod pool] x86 iOS devicelab bots - Keep 2 bots on macOS 12 and upgrade the rest to macOS 13 (10 / 12)
- [x] [prod pool] arm64 iOS devicelab bots -  No upgrade (2 / 4)
- [x] [prod pool] x86 msm8952 devicelab bots - No upgrade (2 / 4)
- [x] [prod pool] arm64 msm8952 devicelab bots - No upgrade (1 / 2)

## Upgrade Phase 4 - Upgrade all remaining bots to macOS 13
- [x] Upgrade all remaining devicelab bots to macOS 13
- [ ] Upgrade all remaining chromium bots to macOS 13

Note:
* When upgrading to macOS 13, the Xcode cache needs to be cleared (ask @vashworth if you need instructions on how to do this).
* When upgrading devicelab, ensure there is a `/opt/flutter/xcode` directory with the owner of `swarming`: https://github.com/flutter/flutter/issues/137342
* https://github.com/flutter/flutter/issues/137345

**Comment by yusuf-goog** [comment]
This is the list of bots (~25%) of existing mac fleet that we are upgrading to macOS 13.x:

### Staging pool
####  chromium (x86)
mac-45-g572
mac-46-g572
#### chromium (arm)
mac-340-g140
mac-341-g140
#### devicelab (arm - moto G4)
flutter-devicelab-mac-33
flutter-devicelab-mac-34 (already upgraded)
#### devicelab (arm - no device)
flutter-devicelab-mac-11 (already upgraded)

### Try pool
#### chromium (x86)
build847-m9
build848-m9
build849-m9
build850-m9
build851-m9
build852-m9
build853-m9
build854-m9
build855-m9
build856-m9
build857-m9
build858-m9
mac-47-g572 (already upgraded)
mac-47-h526 (already upgraded)
#### chromium (arm)
mac-293-g140
mac-294-g140
mac-295-g140
mac-296-g140
mac-297-g140
mac-298-g140
mac-299-g140
mac-300-g140
mac-301-g140
mac-302-g140
mac-303-g140
mac-304-g140
mac-305-g140
mac-306-g140
mac-307-g140
mac-308-g140
mac-309-g140
mac-310-g140
mac-311-g140
mac-312-g140
mac-313-g140
#### devicelab (arm - no device)
flutter-devicelab-mac-45 (already upgraded)
#### devicelab (x86 - no device)
flutter-devicelab-mac-1
flutter-devicelab-mac-12

### Prod pool
#### chromium (x86)
build797-m9
build798-m9
build799-m9
build800-m9
build801-m9
build802-m9
build803-m9
build804-m9
build805-m9
build806-m9
#### chromium (arm)
mac-476-g140
mac-477-g140
mac-478-g140
mac-479-g140
mac-480-g140
mac-481-g140
mac-482-g140
mac-483-g140
#### devicelab (x86 - no device)
flutter-devicelab-mac-2
flutter-devicelab-mac-3
flutter-devicelab-mac-6
flutter-devicelab-mac-7
#### devicelab (arm - no device)
flutter-devicelab-mac-43
flutter-devicelab-mac-44

**Comment by vashworth** [comment]
@yusuf-goog, @kentnguyen99 As you guys upgrade to macOS 13, please ensure you do the following:
* After upgrading to macOS 13, the Xcode cache needs to be cleared (ask @vashworth if you need instructions on how to do this).
* When upgrading devicelab, ensure there is a /opt/flutter/xcode directory with the owner of swarming: https://github.com/flutter/flutter/issues/137342
* https://github.com/flutter/flutter/issues/137345

**Comment by yusuf-goog** [comment]
Opened https://github.com/flutter/flutter/issues/138011 for devicelab machines

**Comment by yusuf-goog** [comment]
Opened https://bugs.chromium.org/p/chromium/issues/detail?id=1500330 for chromium bots

**Comment by yusuf-goog** [comment]
Filed chromium ticket: https://bugs.chromium.org/p/chromium/issues/detail?id=1508144

**Comment by yusuf-goog** [comment]
b/315201468 for missed bots in staging/try

**Comment by yusuf-goog** [comment]
Beginning phase3 upgrades

**Comment by yusuf-goog** [comment]
Request for chromium bots are at : b/319141626

**Comment by yusuf-goog** [comment]
b/326078082 to track macOS 13 upgrade of remaining chromium bots for `prod` and `try` pools.

**Comment by vashworth** [comment]
All bots are now macOS 13. Woohoo! 🎊
