### ISSUE TITLE
[Impeller] `AiksInspector` leaks allocated textures.

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#134748]
The fix:

```diff
// aiks_playground_inspector.cc

+ void AiksInspector::HackResetDueToTextureLeaks() {
+   last_picture_.reset();
+ }
```

```diff
// aiks_playground.cc

+ void AiksPlayground::TearDown() {
+   inspector_.HackResetDueToTextureLeaks();
+   PlaygroundTest::TearDown();
+ }
```

---

@jonahwilliams commentary:

> I don't think this code is running in the right order. It might be torn down after we run shutdown of the context
>
> because the dtors are running after shutdown
>
> but shutdown is what tries to flush the fence waiter/resource manager

I want to fix this, but after some more pressing issues.

**Comment by chinmaygarde** [comment]
The hack seems reasonable?

**Comment by matanlurey** [comment]
I mean it's reasonable in that it works, but our layers are getting unmanageable IMO, we should not require arbitrary shared_ptr and resource resets in particular orders, or should design the APIs to be less brittle.

**Comment by jonahwilliams** [comment]
We're always going to need resource resets in a particular order.

**Comment by matanlurey** [comment]
The fact we don't know that order seems like a problem/smell though (and that it's possible to add _new_ things, like the Inspector, that further complicate this!)

**Comment by gaaclarke** [comment]
Reopened since the removal of AiksInspector was reverted in https://github.com/flutter/engine/pull/52680.
