### ISSUE TITLE
Ignore default Cmd-z (Ctrl-z) behavior on TextField

### ISSUE THREAD

**Issue by Dall127** [flutter/flutter#134706]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I would like to be able to implement custom undo behavior (which I successfully have) but I am unable to block the default behavior of using Cmd-z. 
I am working on a multi-chapter text editor, so I need to be able to rely on state's of text that lie outside of my textfield's knowledge (i.e. I switched chapters). 
### Proposal

Have a field like so on a text-editable widget to be able to implement customBehavior 
```
 RawKeyboardListener(
    focusNode: FocusNode(),
    onKey: (RawKeyEvent value) {
        // custom behavior here
    }
    child: TextField( 
        useKeyboardShortcuts: false,
        ... 
    )
)
```

**Comment by huycozy** [comment]
There is a more general issue for both undo and redo here: https://github.com/flutter/flutter/issues/98280. So I will close this issue in favor of that one. Please follow up on it for updates.
