### ISSUE TITLE
XCode15 got fatal error: 'FlutterMacOS/FlutterMacOS.h' file not found #import <FlutterMacOS/FlutterMacOS.h>

### ISSUE THREAD

**Issue by lucasjinreal** [flutter/flutter#134855]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

fatal error: 'FlutterMacOS/FlutterMacOS.h' file not found
#import <FlutterMacOS/FlutterMacOS.h>

Flutter is already up to date on channel stable
Flutter 3.13.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 367f9ea16b (3 天前) • 2023-09-12 23:27:53 -0500
Engine • revision 9064459a8b
Tools • Dart 3.1.2 • DevTools 2.25.0

### Expected results

Flutter is already up to date on channel stable
Flutter 3.13.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 367f9ea16b (3 天前) • 2023-09-12 23:27:53 -0500
Engine • revision 9064459a8b
Tools • Dart 3.1.2 • DevTools 2.25.0

### Actual results

Flutter is already up to date on channel stable
Flutter 3.13.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 367f9ea16b (3 天前) • 2023-09-12 23:27:53 -0500
Engine • revision 9064459a8b
Tools • Dart 3.1.2 • DevTools 2.25.0

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>
Flutter is already up to date on channel stable
Flutter 3.13.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 367f9ea16b (3 天前) • 2023-09-12 23:27:53 -0500
Engine • revision 9064459a8b
Tools • Dart 3.1.2 • DevTools 2.25.0

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>
Flutter is already up to date on channel stable
Flutter 3.13.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 367f9ea16b (3 天前) • 2023-09-12 23:27:53 -0500
Engine • revision 9064459a8b
Tools • Dart 3.1.2 • DevTools 2.25.0

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>
Flutter is already up to date on channel stable
Flutter 3.13.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 367f9ea16b (3 天前) • 2023-09-12 23:27:53 -0500
Engine • revision 9064459a8b
Tools • Dart 3.1.2 • DevTools 2.25.0

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste youFlutter is already up to date on channel stable
Flutter 3.13.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 367f9ea16b (3 天前) • 2023-09-12 23:27:53 -0500
Engine • revision 9064459a8b
Tools • Dart 3.1.2 • DevTools 2.25.0r output here]
```

</details>

**Comment by huycozy** [comment]
Hi @lucasjinreal 
When opening an issue, please fill appropriate information in the issue template so that we may verify the issue properly. More specifically, please provide the information indicated below:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- Reproduction steps
- The entire output stack trace (flutter run -v)

**Comment by filiphosko** [comment]
Having the same issue, tried creating a fresh new project, purging Pods, nothing helped.
