### ISSUE TITLE
Android app not building

### ISSUE THREAD

**Issue by gintominto5329** [flutter/flutter#134893]
hi,

My system's android-setup side of flutter is completely messed-up.

Note: Debian(Linux-based) builds are working great, everything else is good, and working, except android.

How may i solve it?

Process(I followed) to get to this situation (please read carefully):
- Install Debian, then `git clone` flutter-master, then `flutter doctor`.
- Create a debian-supported flutter project, and run it; app builds, and works great.
- Ensure android-studio is not installed.
- Install `cmdline-tools;latest`, from [developer.android.com/cmdline-tools](http://developer.android.com/studio#command-line-tools-only).
- Using `cmdline-tools/bin/sdkmanager`, install `build-tools;34.0.0`, and `platform-tools`.
- Using `platform-tools/bin/adb`, (wirelessly) pair and connect to my physical, motorola branded, android-11 based, phone; through internet connected WiFi.
- Create an android-supported flutter project, and run, it.
- Android device is detected correctly, hence building starts, and user is waiting for gradle assemble.
- Encounter the error, Problem installing some packages, Android licenses not accepted, so exec `cmdline-tools/bin/sdkmanager --licenses`,
- Run again, still has some problem, so restart the computer.
- Connect the previously paired, android phone.
- Encounter the error, Current platform not supported; then exec `flutter devices`, and find that device is not being detected by flutter tool, but phone is showing the connection notification. Exec `platform-tools/adb kill-server`, then connect again, but still, same problem, so restart the computer, again.
- Search Google, and decide to exec `export ANDROID_HOME="~/bin/android/sdk`, and `echo` to `.bashrc`, all above mentioned cli tools are installed in this directory.
- Exec `flutter doctor -vv`, and encounter the error, saying, sdk path is set, but no SDK found.
- Curse the docs a bit, and decide to install android-studio, then setup; still no progress.
- Exec `flutter config --android-studio-dir=~/bin/android/studio`, and `export JAVA_HOME=~/bin/android/studio/jbr`(also `echo` to bash-rc).
- Now encounter the error, "Could not find the Android Studio installation at the manually configured path "~/bin/android/studio"".
- Then curse the docs, a bit more, then write this issue, then submit.

Note:  debian apps are still building, and working great, just android apps are not

thanking you

**Comment by NobodyForNothing** [comment]
Setting up Android builds is a little bit tricky 😉.

For setting up Android builds, please refer to the procedure presented in [the docs](https://docs.flutter.dev/get-started/install/linux#android-setup). I recommend you uninstall the Android toolchain as well as Android Studio and verify that you install them in the correct location.
Also, try to do one step at a time: you don't need to connect your phone when you can't even build the app.

In case you still encounter issues with your build, please provide the following information:
- how you installed your setup (e.g. did you use Snap, install the files manually, use an installer)
- links to your information sources
- the concrete flutter doctor output

**Comment by huycozy** [comment]
@gintominto5329 When opening an issue, please try to provide all information indicated in the issue template so that we can address this issue properly (See the bug template [here](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml)). The necessary information to debug this issue has been mentioned above by @NobodyForNothing.
