### ISSUE TITLE
Weird behavior of nested decorations combined with dragging and opacity layer

### ISSUE THREAD

**Issue by eli1stark** [flutter/flutter#134891]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Paste code sample
2. Run app
3. Drag container, you should notice weird flickering.

The issue is reproducible with Impeller ON and OFF. I provided simple example but in my complex widgets I noticed that with Impeller ON, flickering becomes more apparent, in the specific example I provided Impeller doesn't seem to enhance buggy feel. 

### Expected results

1. Parent's background shouldn't be visible on the corners (Black color).
2. Flickering of parent's background color (Black color) should not happen.
3. When I nest containers I expect child's color (White color) to occupy all space and cover 100% of available space of the parent, black color should not be visible at all.

### Actual results

1. Black color is visible.
2. Black color is flickering when dragged.
3. Child does not fill 100% of its parent with color.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp(home: PhysicsCardDragDemo()));
}

class PhysicsCardDragDemo extends StatefulWidget {
  const PhysicsCardDragDemo({super.key});

  @override
  State<PhysicsCardDragDemo> createState() => _PhysicsCardDragDemoState();
}

class _PhysicsCardDragDemoState extends State<PhysicsCardDragDemo> {
  Alignment dragAlignment = const Alignment(0, 0);

  @override
  Widget build(BuildContext context) {
    final size = MediaQuery.sizeOf(context);

    return Scaffold(
      body: GestureDetector(
        onPanUpdate: (details) async {
          setState(() {
            dragAlignment += Alignment(
              details.delta.dx / (size.width / 2),
              details.delta.dy / (size.height / 2),
            );
          });
        },
        child: Align(
          alignment: dragAlignment,
          child: Container(
            height: 200,
            width: 200,
            decoration: BoxDecoration(
              color: Colors.black,
              borderRadius: BorderRadius.circular(24),
            ),
            child: Opacity(
              opacity: 0.99,
              child: DecoratedBox(
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(24),
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/57593530/7f8d3dbd-3dd4-4e66-97a7-e63386c9e219

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.4, on macOS 13.3.1 22E772610a darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.81.1)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @eli1stark 
There is a known issue with a similar case https://github.com/flutter/flutter/issues/132911 but it's indeed  https://github.com/flutter/flutter/issues/14288. Please follow up on #14288 for updates. You can leave your comment about dragging behavior and react an upvote to the original comment will help to raise the issue. Thank you!
