### ISSUE TITLE
gradle fails build with confusing error

### ISSUE THREAD

**Issue by droundy** [flutter/flutter#13483]
## Steps to Reproduce

    git clone git://github.com/droundy/student-pairs
    cd student-pairs
    (add a key.properties here)
    flutter build apk

## Logs

```
$ flutter build apk
Initializing gradle...                                0.5s
Resolving dependencies...                             0.9s
Running 'gradlew assembleRelease'...                      

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForRelease'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzdto;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Gradle build failed: 1
```
```
$ flutter analyze
Analyzing /home/droundy/src/test-student-pairs...
No issues found!
Ran in 4.9s
```

## Flutter Doctor

```
$ flutter doctor
[✓] Flutter (on Linux, locale en_US.UTF-8, channel master)
    • Flutter at /home/droundy/src/flutter
    • Framework revision 0c09179b65 (32 hours ago), 2017-12-09 22:04:06 -0800
    • Engine revision edb0201fa2
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.a38ac7cf127f4611c873c2f2d523c06ce06b1342

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /home/droundy/src/android-sdk-linux
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-26, build-tools 25.0.3
    • ANDROID_HOME = /home/droundy/src/android-sdk-linux
    • Java binary at: /home/droundy/src/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_76-release-b03)

[✓] Android Studio (version 2.2)
    • Android Studio at /home/droundy/src/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_76-release-b03)

[-] Connected devices
    • None
```
Paste the output of running `flutter doctor` here.

**Comment by droundy** [comment]
On another project, I can reproduce this problem by making the following edit to pubspec.yaml:

```
$ git diff
diff --git a/pubspec.yaml b/pubspec.yaml
index 0ea30aa..d7babda 100644
--- a/pubspec.yaml
+++ b/pubspec.yaml
@@ -6,9 +6,9 @@ dependencies:
     sdk: flutter
   share: "^0.2.1"
   path_provider: "^0.2.1+1"
-  google_sign_in: "^0.3.1"
-  firebase_auth: "^0.2.3"
-  firebase_database: "^0.1.0"
+  google_sign_in: "^1.0.1"
+  firebase_auth: "^0.3.1"
+  firebase_database: "^0.1.4"
   flutter_color_picker: "^0.0.1"
```

Presumably this means there is a version mismatch somewhere in these packages.  Any suggestions how to figure out a consistent and up-to-date set of imports?

**Comment by okaybroda** [comment]
I'm having similar issue.

My deps:
```
  firebase_auth: ^0.3.1
  google_sign_in: ^0.3.1
  firebase_analytics: ^0.1.1
  firebase_database: ^0.1.4
  firebase_storage: ^0.0.7
```

**Comment by Arno-Z** [comment]
Isn't that this issue: https://github.com/flutter/flutter/issues/13324#issuecomment-349070493

**Comment by mit-mit** [comment]
Yes, this is believed to be the same as https://github.com/flutter/flutter/issues/13324, so closing for now.

**Comment by bhaskarpait84** [comment]
DELL@DESKTOP-KB3FP1J MINGW64 ~/Desktop/helloflutter/myapp
$ flutter run
Launching lib/main.dart on Redmi 5 in debug mode...
Initializing gradle...                                       3.6s
Resolving dependencies...
* Error running Gradle:
Exit code 1 from: C:\Users\DELL\Desktop\helloflutter\myapp\android\gradlew.bat app:properties:
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details
of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\DELL\Desktop\helloflutter\myapp\android\app\build.gradle' line: 25

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not resolve all files for configuration 'classpath'.
   > Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.1.2).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/lint/lint-gradle-api/26.1.2/lint-gradle-api-26.1.2.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s


Please review your Gradle project setup in the android/ folder.

**Comment by zoechi** [comment]
@bhaskarpait84 I assume you found https://stackoverflow.com/questions/52945041/couldnt-locate-lint-gradle-api-26-1-2-jar-for-flutter-project (or other places with solutions) already.
