### ISSUE TITLE
[video_player] Adds `loop`, `volume` and `playAfterInitialized` parameters to VideoPlayerController constructors

### ISSUE THREAD

**Issue by vanvixi** [flutter/flutter#134894]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Iam currently developing a video playback application similar to TikTok. During the development process, I need to prepare the next video and configure necessary options such as "loop, volume, playAfterInitialized" in advance. The changes in this pull request (PR) make my application faster, and I believe those who are working on a video application like TikTok will also need these options in the constructor.

### Proposal

Adds `loop`, `volume` and `playAfterInitialized` parameters to VideoPlayerController constructors

**Comment by vanvixi** [comment]
@stuartmorgan 
Check this issue please

**Comment by stuartmorgan** [comment]
> The changes in this pull request (PR) make my application faster

How would adding constructor arguments that will be applied asynchronously later regardless make an application faster? Please provide performance traces demonstrating a difference, since I don't see how that would be possible.
