### ISSUE TITLE
Condition variables should support thread static analysis

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#134843]
In https://github.com/flutter/engine/pull/45870/files/d9735741e0980df0020e23f48a5cff904b923970#r1327787268:

> @chinmaygarde:
>
> The locking without static analysis makes me nervous. I suspect we didn't use the `IPLR_GUARDED_BY` and friends because we don't have static thread safety analysis around condition variable. This should be easy enough to add support for. Can we file a followup bug for it?

So, this is that bug!

I also mentioned I'd personally prefer to just use `absl` if possible (https://github.com/flutter/flutter/issues/134741), but that's not necessarily a blocker.

**Comment by chinmaygarde** [comment]
I couldn't find this in `absl`? Am I missing something?

**Comment by matanlurey** [comment]
> I couldn't find this in `absl`? Am I missing something?

https://abseil.io/docs/cpp/guides/synchronization ?

**Comment by chinmaygarde** [comment]
I saw that and there is Mutex and Lock, but what about condition variable? Specifically, the wait with a predicate? What would I use in absl to support this ask.
