### ISSUE TITLE
[impeller][android] janky animation

### ISSUE THREAD

**Issue by delfme** [flutter/flutter#134841]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Hello,
Just tested Impeller on android with Flutter version 3.13.0-0.2.pre.

I know it is still under development but wanted to ask if this janky animation with images is normal at the moment. 

https://github.com/flutter/flutter/assets/53510751/3bf96a33-1ca1-4b46-b6f4-9e6e26ae7e1a

Same code is smooth on Impeller iOS.

https://github.com/flutter/flutter/assets/53510751/1f262db7-b43e-4750-8847-87a52189fc11

### Expected results

Smooth transition.

### Actual results

Janky transition.

### Code sample

Code is closed but will try to make a sample repo if you guys think that the issue should not occur with current stage of Impeller for android roadmap. I think similar effect can be found inside wonderous app and you’d save my time if you’d already have a sample code to check the issue with.

I could also test with latest master if you guys want me to try that as well.

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Flutter (Channel [user-branch], 3.13.0-0.2.pre, on macOS 12.6.5 21G531 darwin-arm64, locale en-IT)
    ! Flutter version 3.13.0-0.2.pre on channel [user-branch] at /Users/delf/Development/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] Connected device (3 available)
[✓] Network resources

**Comment by jonahwilliams** [comment]
> Code is closed but will try to make a sample repo if you guys think that the issue should not occur with current stage of Impeller for android roadmap. I think similar effect can be found inside wonderous app and you’d save my time if you’d already have a sample code to check the issue with.

Hi @delfme , the purpose of filling a bug report on a performance issue is to create a concrete repro case that we can examine. If you're not willing to share any code/profiles or any data at all about the problem you're having, there is zero information we can provide. no one is going to attempt to guess based on your video. 

In the future, please do not file bugs like this. Either provide sufficient details that allow an issue to reproduced or investigate on your own.

**Comment by delfme** [comment]
@jonahwilliams My bad. Will create a compliant PR for this. Was out travelling and thought that you guys might already have a repro case for this very issue. Sorry.
