### ISSUE TITLE
The Image widget has a bug; it's not possible to retrieve the width and height of an Image loaded from assets.

### ISSUE THREAD

**Issue by Silentdoer** [flutter/flutter#134873]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

aaa.png is a 32*16 picture.

```dart
var img = Image.asset("assets/images/aaa.png", scale: 1,);
    print("img:${img.width}---${img.height}");
```

### Expected results

prints: img:32---16

### Actual results

img:null---null

### Code sample

<details><summary>Code sample</summary>

```dart
var img = Image.asset("assets/images/aaa.png", scale: 1,);
    print("img:${img.width}---${img.height}");
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.3, on Arch Linux 6.1.52-1-lts, locale zh_CN.UTF-8)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
[!] Proxy Configuration
    ! NO_PROXY is not set
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 3 categories.

**Comment by dam-ease** [comment]
Hi @Silentdoer. Thanks for filing this. Calling `img.width` or `img.height` gets the height or width specified in `Image.asset` and not the actual image height and width. To get the actual height and width of the image, see this [Thread](https://stackoverflow.com/questions/44665955/how-do-i-determine-the-width-and-height-of-an-image-in-flutter) for more info.
Closing this as this seems to be working as expected, if you disagree, kindly comment and I'd reopen this.
Thank you
