### ISSUE TITLE
[Impeller] MacOS+SwiftShader doesn't render.

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#134852]
In order to get _some_ Vulkan validation checking on CI, we'll need to use Swift Shader (Software Rendering). However, as of HEAD (https://github.com/flutter/engine/commit/d0ff708bdf17d0f4758a2acf616f6308af77a8c3 at time of writing), there are two problems with Vulkan+Swift Shader on MacOS hosts (which I can also reproduce locally):

1. Asynchronous presentation causes a timeout
2. Even with synchronous presentation, the image is blank

There is a some more information here: 
- https://github.com/flutter/flutter/issues/133506#issuecomment-1722098909
- https://github.com/flutter/flutter/issues/126022#issuecomment-1541039713

It's likely the issues are same (nothing is being drawn).

---

To reproduce (remember, MacOS host - and I only tried ARM64):

```shell
# Assuming you're in $ENGINE/src/flutter

# GN
./tools/gn \
  --unopt \
  --mac-cpu arm64 \
  --enable-vulkan-validation-layers \
  --enable-impeller-vulkan \
  --target-dir=host_debug_impeller_vulkan \
  --no-stripped

# Ninja
ninja -j1000 -C ../out/host_debug_impeller_vulkan impeller_unittests

# Make sure this path is right, if not you'll silently use MoltenVK, which works fine.
ls ../out/host_debug_impeller_vulkan/vk_swiftshader_icd.json

# Run, providing Swift Shader, and enabling validation.
VK_ICD_FILENAMES=../out/host_debug_impeller_vulkan/vk_swiftshader_icd.json \
  ../out/host_debug_impeller_vulkan/impeller_unittests \
  --gtest_filter="Play/AiksTest.*/Vulkan" \
  --playground_timeout_ms=1000 \
  --enable_vulkan_validation
```

---

I'm filing this issue so we can at least get validation coverage (https://github.com/flutter/engine/pull/45918).

**Comment by gaaclarke** [comment]
MacOS+SwiftShader does work for at least the golden tests.  The big gap was making sure the interactive tools don't break since chinmay was relying on them to iterate quickly.  I was going to suggest maybe we just look at making the the interactive tests use moltenvk since that's how people are using them anyway.  I'm not sure if that is possible though on CI.

**Comment by matanlurey** [comment]
Maybe they have GPUs? Do any modern Mac hosts, even on CI, not?

**Comment by gaaclarke** [comment]
> Maybe they have GPUs? Do any modern Mac hosts, even on CI, not?

Yea they have to, especially if they are arm64 since it's physically attached to the cpu.  I think the setup and licensing of moltenvk are more of blockers.

**Comment by matanlurey** [comment]
@zanderso I'm re-assigning this to you just to figure out if there are issues with installing MoltenVK on CI. Please re-assign back, and @gaaclarke and I can take over setup/switching over, if necessary.

@gaaclarke If SwiftShader software rendering doesn't work, and won't, should be just error out/fail instead of doing nothing?

**Comment by gaaclarke** [comment]
> @gaaclarke If SwiftShader software rendering doesn't work, and won't, should be just error out/fail instead of doing nothing?

Swiftshader does work with the golden image tests.  Sorry, what I meant is that I ran into that problem and I fixed it.  That's why the golden image tests work today.

**Comment by matanlurey** [comment]
Got it, thanks for clarifying!

**Comment by zanderso** [comment]
For CI (and locally as well), we can put the releases like https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.2.5 in CIPD, and pull them with the DEPS file under e.g. `flutter/prebuilts`.

**Comment by littleGnAl** [comment]
I ran into this issue when I tried to run our screenshot test in the iOS simulator with the 3.16.x. 

Here's the failed job link
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/actions/runs/7016067696/job/19089615557?pr=1451

**Comment by jonahwilliams** [comment]
This works now, but you have to run with the cwd as the build output directory so we can find the swiftshader binary.
