### ISSUE TITLE
Linker warnings in the mac host engine build

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#134857]
```
[1371/3284] LINK ./gen_snapshot
ld64.lld: warning: cannot export hidden symbol Dart_LookupLibrary
>>> defined in obj/third_party/dart/runtime/libdart_precompiler.a(libdart_precompiler.dart_api_impl.o)
....
```

The convention for ninja builds is that a successful build produces no output. There should only be output when something goes wrong.

Related to https://dart.googlesource.com/sdk/+/b8ee3a999676b0e502c0a2a9cba9730374d9bf83

cc @rmacnak-google @jason-simmons

**Comment by chinmaygarde** [comment]
Why aren't `lld` warnings errors? Perhaps we should separately track enabling these so that rolls fail?

**Comment by zanderso** [comment]
We may be missing `-Wl,--fatal-warnings`.

**Comment by chinmaygarde** [comment]
From Dart VM Sync: @rmacnak-google believes this needs the rules to be patched such that the visibility for each TU is specified. But there may also be a separate investigation about why the standalone VM needs this symbol exposed as well.

**Comment by zanderso** [comment]
Following https://github.com/dart-lang/sdk/commit/2a30837626398ba3baa5f8d7d8ed9837b4a62f44, I'm not seeing the warnings anymore. Thanks @rmacnak-google!
