### ISSUE TITLE
Google Sign In Not Working With Huawei Packages

### ISSUE THREAD

**Issue by SerDariss** [flutter/flutter#134901]
### Is there an existing issue for this?

- [X] I have searched the [existing package issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Apackage)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### What package does this bug report belong to?

google_sign_in

### What target platforms are you seeing this bug on?

Android

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.yaml</summary>

```lock
google_mobile_ads: ^3.0.0
google_sign_in: ^6.1.1
google_sign_in_dartio: ^0.2.2+1
googleapis: ^10.1.0
huawei_iap: ^6.10.0+300
google_huawei_availability: ^1.4.0
```

</details>

<details><summary>build gradle</summary>

```lock
buildscript {
    ext.kotlin_version = '1.9.0'
    repositories {
        google()
        mavenCentral()
        maven { url 'https://developer.huawei.com/repo/' }   
    }

dependencies {
        classpath 'com.android.tools.build:gradle:7.3.0'
        classpath 'com.google.gms:google-services:4.3.15'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.huawei.agconnect:agcp:1.5.2.300'
    }

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {url 'https://developer.huawei.com/repo/'}
    }
}
```

</details>

<details><summary>app level build gradle</summary>

```lock
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'com.google.gms.google-services'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
apply plugin: 'com.huawei.agconnect'

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.android.support:multidex:1.0.3'
    implementation platform('com.google.firebase:firebase-bom:31.3.0')
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.android.gms:play-services-ads:22.0.0'
    implementation 'com.android.billingclient:billing:4.0.0'
    implementation 'androidx.window:window:1.0.0'
    implementation 'androidx.window:window-java:1.0.0'
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5'
}
```

</details>

<details><summary>android manifest.xml</summary>

```lock
<meta-data android:name="com.huawei.hms.client.appid" android:value="appid=xxxxxxxxx"/>
<meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="ca-app-pub-xxxxxxxxxxxxxx~xxxxxxx"/>
<meta-data android:name="com.google.firebase.messaging.default_notification_channel_id" android:value="xxxxxxxxxxxxxxl:string/default_notification_channel_id"/>
```

</details>

### Steps to reproduce

1. I try to log in to my app with google sign in. (Huawei packages are also active)
2. It doesn't work and I get the same error over and over again.
The error:  PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)

The issue disappears as soon as I deactivate everything Huawei related. However, I need both of them (Google & Huawei) working at the same time.

### Expected results

I expect Google Sign In to work while I also have the Huawei packages activated.

### Actual results

Google Sign In doesn't work when I have Huawei packages activated in my application.

### Code sample

The method I use for my google sign in:

```dart
static final googleSignInInstance = GoogleSignIn(
    serverClientId:
        'xxxxxxxx', 
  );

  Future signInWithGoogle() async {
    final gUser = googleSignInInstance.currentUser ?? await googleSignInInstance.signIn();
    if (gUser != null) {
      final gAuthEmail = gUser.email;
      final token = (await gUser.authentication).accessToken;
      var response = await post('xxxxxx', {
        "EMAIL_ADDRESS": gAuthEmail,
        "TOKEN": token,
      });
      if (!response.success) throw response.message;
      return AppData.userDetail.value = {...response.data};
    }
    throw 'GoogleSignInFailed';
  }
```

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

<img width="900" src="https://github.com/flutter/flutter/assets/89767593/232b3bf6-0a49-4757-9d19-23110ac31383">

</details>

**Comment by huycozy** [comment]
Hi @SerDariss 
I tried adding those Huawei packages and running Google SignIn example but can't reproduce the issue. I still can login normally.

I wonder if this is an issue with Huawei packages? Can you share a complete and minimal sample project? And please share the entire output of `flutter run -v` as well. Thanks!
