### ISSUE TITLE
Restart the ANGLE roller with fixes for window resizing on Windows.

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#134981]
We encountered issues with window resizing on Windows with the ANGLE roll and needed to revert/pause it: https://github.com/flutter/flutter/issues/134262

This issue is to track getting the ANGLE roller restarted once the Windows-related issues are addressed.

**Comment by loic-sharma** [comment]
Window resize bug was fixed by https://github.com/flutter/engine/pull/46172. I restarted the ANGLE autoroller, I will close this once the autoroll lands.

**Comment by loic-sharma** [comment]
ANGLE autoroller was restarted. ANGLE autoroll is now failing as `vulkan-deps` is out-of-date. Closing this as the Windows resize issue is no longer blocking the ANGLE autoroll.
