### ISSUE TITLE
Update screenshots on homepage with new iOS demo

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#13494]
There's a very cool Cupertino Navigation demo in the gallery. We'd like to show it on flutter.io homepage.

**Comment by zoechi** [comment]
Is this covered by 

![image](https://user-images.githubusercontent.com/405837/49376739-95cf7400-f708-11e8-9cad-e91f25bbc1dd.png)

?

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2062](https://github.com/flutter/website/issues/2062) via [**ZenHub**](https://www.zenhub.com/)
