### ISSUE TITLE
Implement a "testing" channel to the engine.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#13491]
In order to easily write tests that test our framework interfaces with the engine over the various channels, we need to have a way to inject messages in the engine from the framework side.

This would be a channel that would be compiled out on the engine side in release builds, but would respond to messages in a debug build.

The idea is that from the framework you would send a message to the engine to simulate a call from the engine to the framework.

The testing channel would take a destination channel and a payload and deliver the payload to the framework side as if it had been generated by the engine directly.

The reason this should be on the engine side is so that we don't have active APIs in the framework side that can be used in a release build, and need to be supported.

An example of such a use case is to write a test that will change the textScaleFactor as if it had come from the user changing the system settings.

**Comment by gspencergoog** [comment]
@goderbauer

**Comment by goderbauer** [comment]
This would also make testing of https://github.com/flutter/flutter/pull/13490 easier/possible.

**Comment by jonahwilliams** [comment]
Given that we didn't build this anytime in the last seven years I'm going to say it wasn't important
