### ISSUE TITLE
Flutter Plugin and Package editing  Option

### ISSUE THREAD

**Issue by ZahidUrRehman13** [flutter/flutter#134932]
As per my expereince with the flutter, a lot of packages and plugins can edit by any developer  from his side. 
If we think about it, it may cause security issues for  flutter app, Please help me i have changed so many packages and plugin from my side, is it ok or not

**Comment by stuartmorgan** [comment]
For general questions or discussion, consider one of the options at https://flutter.dev/community#community-grid.

Closing as this is not an issue or feature request.
