### ISSUE TITLE
Picture.toImage must return a GPU resident image.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#13498]
Currently, the synchronous call to [materialize the image from a picture](https://docs.flutter.io/flutter/dart-ui/Picture/toImage.html) obtained from a picture recorder returns an image whose data is resident on the host. This is the only way it can work right now because the UI task runner does not have access to the GPU context. While such images work well for callers that attempt to manipulate the bytes of the image, rendering multiple frames with such images causes a per frame texture upload. This kills performance. Images obtained via an IO thread hop perform the texture upload and get rid of the host side allocation before returning a reference to the GPU image to the Dart wrapper of the image. Hence, such images are fast to render to per frame.

We should make the call to `Picture.toImage` return a future to the image so that we can perform the same thread hop and return a handle to a GPU resident image.

**Comment by chinmaygarde** [comment]
Reported by @sroddy on Gitter. @Hixie suggested the call to `toImage()` return a future to the image.

**Comment by chinmaygarde** [comment]
The discussion for this change was made on the PR that introduced the `Picture.toImage` in the first place. Linking it here for reference: https://github.com/flutter/engine/pull/3657#issuecomment-350902455

**Comment by sroddy** [comment]
@chinmaygarde do you happen to have an ETA for this? It's probably the only real thing it's preventing us to release now...

**Comment by chinmaygarde** [comment]
Update: I was working on this today. I have implemented the async variant and am working around a few edge cases. Will post an update as soon as the patch is ready.

**Comment by sroddy** [comment]
hi @chinmaygarde, do you have any update? thanks

**Comment by iapicca** [comment]
Hi @chinmaygarde is this issue still meant to be open?

**Comment by chinmaygarde** [comment]
Yes. The current image returned is still a raster image which may be unnecessarily expensive if the caller intent is to immediately display it without modification.

**Comment by dnfield** [comment]
@chinmaygarde is this fixed now that we use a pbuffer surface when the on screen surface is not available? The only time we're drawing to a raster surface now is if the GPU is not available, e.g. if we're in the background on iOS.

**Comment by dnfield** [comment]
Ahh I think I see from the linked discussion that we really need to make this a cross context image to fully resolve this issue. Ok.

**Comment by dnfield** [comment]
Failure modes this would have to address (posting here too incase we try to do this without having a synchronous method)

- There is no context available when you request the GPU image, so we can't make one. Do we just try again when one is available? 
- The context goes away after you make the GPU image, taking the texture with it. What do we do? Do a host transfer and re-upload for you?
- The image is too big to fit into GPU memory (do we try to tile it for you, or just fail and make you do it?)
- You have simply run out of memory.

**Comment by fzyzcjy** [comment]
Hi, https://api.flutter.dev/flutter/dart-ui/Picture/toImage.html returns `Future<Image>`, while it says "the image is returned synchronously"... So maybe the doc needs an update?

> Although the image is returned synchronously, the picture is actually rasterized the first time the image is drawn and then cached.

More importantly, is it still true? Or is "the picture is actually rasterized the first time the image is drawn and then cached" already outdated?

**Comment by fzyzcjy** [comment]
Oh I see https://github.com/flutter/flutter/issues/77289
