### ISSUE TITLE
XCTests and XCUITests failing on webview_flutter_wkwebview package iOS 17 XCode RC1

### ISSUE THREAD

**Issue by rzambroni** [flutter/flutter#134972]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Install XCode RC1 and iOS 17.0 Simulator

git clone [GitHub - flutter/packages: A collection of useful packages maintained by the Flutter team](https://github.com/flutter/packages.git) 

cd packages

cd web_view_flutter/webview_flutter_wkwebview/example/ios

flutter pub get

pod install

Run the test using command (Replace $simulator_id):

```shell 

xcodebuild test -workspace Runner.xcworkspace -scheme Runner \

-destination 'platform=iOS Simulator,id=$simulator_id' > logs.txt

```

9- Alternatively, you can run test inside Xcode in the Test Navigator

### Expected results

Running all tests should succeed 

### Actual results

![image](https://github.com/flutter/flutter/assets/54465214/c78fa9e8-de18-4553-a58a-8e279043b67e)

[Screenshot 1]: Xcode test navigator showing failing test: testLoadRequestWithInvalidUrl

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
error: -[FWFWebViewHostApiTests testLoadRequestWithInvalidUrl] : loadRequest:<OCMAnyConstraint: 0x600000b41910>: explicitly disallowed method invoked: loadRequest:<NSMutableURLRequest: 0x600000b476e0> { URL: %25invalidUrl%25 } (NSInternalInconsistencyException)

Test Case '-[FWFWebViewHostApiTests testLoadRequestWithInvalidUrl]' failed (0.049 seconds).

Test Suite 'FWFWebViewHostApiTests' failed at 2023-09-18 16:07:37.317.

Executed 1 test, with 1 failure (1 unexpected) in 0.049 (0.050) seconds

Test Suite 'RunnerTests.xctest' failed at 2023-09-18 16:07:37.318.

Executed 1 test, with 1 failure (1 unexpected) in 0.049 (0.051) seconds

Test Suite 'Selected tests' failed at 2023-09-18 16:07:37.318.

Executed 1 test, with 1 failure (1 unexpected) in 0.049 (0.053) seconds

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.14.0-14.0.pre.333, on macOS 13.5.2 22G91 darwin-x64, locale en-UY)

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)

[✓] Chrome - develop for the web

[✓] VS Code (version 1.82.2)

[✓] Connected device (3 available)

[✓] Network resources
```

</details>

**Comment by stuartmorgan** [comment]
This will be the same problem as described [here](https://github.com/flutter/flutter/issues/134971#issuecomment-1726404090), so I'll fix it at the same time.

**Comment by rzambroni** [comment]
Hi @stuartmorgan, thanks for the answer. FYI there is a third XCTest-XCUITest issue we reported that might be caused by the same problem you described. [Here](https://github.com/flutter/flutter/issues/134973) it is in case you want to take a look. 
Thanks.
