### ISSUE TITLE
XCTests and XCUITests failing on url_launcher package iOS 17 XCode RC1

### ISSUE THREAD

**Issue by rzambroni** [flutter/flutter#134971]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Steps to reproduce

Install XCode RC1 and iOS 17.0 Simulator

git clone  

cd packages

cd url_launcher/url_launcher_ios/example/ios

flutter pub get

pod install

Run the test using command (Replace $simulator_id):

```shell 

xcodebuild test -workspace Runner.xcworkspace -scheme Runner \

-destination 'platform=iOS Simulator,id=$simulator_id' > logs.txt

```

9- Alternatively, you can run test inside Xcode in the Test Navigator

### Expected results

Expected results

Running all tests should succeed

### Actual results

Actual results

![image](https://github.com/flutter/flutter/assets/54465214/9d344f67-5d25-4997-8749-cd8dd34e46a2)

[Screenshot 1]: Xcode test navigator showing failing tests.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
Test Case '-[RunnerUITests.URLLauncherUITests testLaunch]' failed (42.205 seconds).

Test Suite 'URLLauncherUITests' failed at 2023-09-18 15:33:34.376.

Executed 1 test, with 1 failure (0 unexpected) in 42.205 (42.207) seconds

Test Suite 'RunnerUITests.xctest' failed at 2023-09-18 15:33:34.377.

Executed 1 test, with 1 failure (0 unexpected) in 42.205 (42.209) seconds

Test Suite 'Selected tests' failed at 2023-09-18 15:33:34.378.

Executed 1 test, with 1 failure (0 unexpected) in 42.205 (42.215) seconds
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.14.0-14.0.pre.333, on macOS 13.5.2 22G91 darwin-x64, locale en-UY)

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)

[✓] Chrome - develop for the web

[✓] VS Code (version 1.82.2)

[✓] Connected device (3 available)

[✓] Network resources
```

</details>

**Comment by stuartmorgan** [comment]
The XCTests are no longer valid due to an NSURL behavioral change:
>> For apps linked on or after iOS 17 and aligned OS versions, [NSURL](https://developer.apple.com/documentation/foundation/nsurl) parsing has updated from the obsolete RFC 1738/1808 parsing to the same [RFC 3986](https://www.ietf.org/rfc/rfc3986.txt) parsing as [NSURLComponents](https://developer.apple.com/documentation/foundation/nsurlcomponents). This unifies the parsing behaviors of the NSURL and NSURLComponents APIs. Now, NSURL automatically percent- and IDNA-encodes invalid characters to help create a valid URL.

We'll need to see if we can find a different way to create invalid URLs, or we'll have to relax the test expectations (and lose some edge case coverage).

The XCUITest seems to be tapping `Done` without effect, causing the test to get stuck. That seems like it may be an XCUITest bug, but I'll have to investigate further.
