### ISSUE TITLE
Fuchsia Linux SDK roller failing on FEMU build due to `aemu_internal` missing.

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#134987]
The Fuchsia Linux SDK roller started failing on Saturday (https://github.com/flutter/engine/pull/45927):

```
Sep 16 09:41:04.001 [10968001005931356169] WARN ffx_emulator_engines::qemu_based::modules: failed to get host tool aemu_internal from manifest. Trying local SDK dir: Tool 'aemu_internal' not found in SDK dir
Sep 16 09:41:04.001 [10968001005931356169] INFO ffx_command::metrics: Command finished. success: false, command time: 0.07223062, analytics disabled
BUG: An internal command error occurred.
Error: Error creating new engine
    1.  Error creating new engine
    2.  Failed to load the emulator binary path for femu
    3.  Giving up finding emulator binary. Tried "/b/s/w/ir/cache/builder/src/fuchsia/sdk/linux/tools/x64/aemu_internal"
More information may be available in ffx host logs in directory:
    /b/s/w/ir/x/w/recipe_cleanup/ffx_isolate_files9orat1v6/cache/logs
```

**Comment by bdero** [comment]
This error string is coming from the ffx binary -- the `aemu_internal` string also seems to be originating from that binary. Perhaps the SDK is no longer being packaged correctly?

**Comment by bdero** [comment]
This is starting to look a lot less like a packaging problem.

* Checked the known working distro (ZhY53WD7bFJSA3xoOchmSzb5zambmf3zOGFuK0GVv_YC) and the known broken distro (UGCAI0tQssJWw5NCx2yGwLgr8gGK1Ws6_C7kb6fzzBIC), and `aemu_internal` is present in both versions.
* I recursively diffed the filenames under `aemu_internal` between both versions and the file tree structure is identical.
* The shasum of `ffx` between the two versions are different.

**Comment by zanderso** [comment]
There was a successful roll here https://github.com/flutter/engine/pull/46082. Closing as presumed fixed.
