### ISSUE TITLE
Reconsider - layout related FlutterErrors do net get reported in release mode

### ISSUE THREAD

**Issue by petrnymsa** [flutter/flutter#134939]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Following up for older reported issue #72598 . 

We have use cases where testers are reporting sometimes hard reporducible issues within UI layer. Reporting layout issue into Flutter.onError would help us, as we are reporting every unhandled issues into logger services such as Bugender/Sentry. 

Could it be reconsidered to include these errors in release?

### Proposal

Find a way how to include layout error in logs when app is built in release mode

**Comment by darshankawar** [comment]
@petrnymsa 
Can you take a look at below issues and underlying comments and check if they help in your case or not ?

https://github.com/flutter/flutter/issues/134094



https://github.com/flutter/flutter/issues/8338

https://github.com/flutter/flutter/issues/78503#issuecomment-802254913

**Comment by petrnymsa** [comment]
@darshankawar I think #134094 describes similar issue - there is no way to get logs / capture layout rendering related errors in release.

**Comment by darshankawar** [comment]
Good to know. I suggest you to follow-up in that issue for further updates. Closing this in favor of it. If you disagree, write in comments and I'll reopen it.
