### ISSUE TITLE
[ios]: `fillColor` for `Checkbox.adaptive` is ignored

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#134917]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

The `Checkbox.adaptive` docs say:

> /// If a [CupertinoCheckbox] is created, the following parameters are ignored:
  /// [mouseCursor], [hoverColor], [overlayColor], [splashRadius],
  /// [materialTapTargetSize], [visualDensity], [isError]. However, [shape] and
  /// [side] will still affect the [CupertinoCheckbox] and should be handled if
  /// native fidelity is important.

But I created one with `fillColor: MaterialStateProperty.all(Theme.of(context).colorScheme.primary),` and `fillColor` is also being ignored when running on iOS.

### Expected results

Either the `fillColor`should work on iOS (desirable) or the docs should expose this limitation.

### Actual results

`fillColor` is being ignored by `CupertinoCheckbox`.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel unknown, 3.10.7, on macOS 13.4.1 22F770820d darwin-arm64, locale en-AU)
    ! Flutter version 3.10.7 on channel unknown at /opt/homebrew/Caskroom/flutter/3.10.6/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.81.1)
[✓] Connected device (4 available)
[✓] Network resources
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report. Using below code sample, Android and iOS behavior is captured:

<details>
<summary> runnable code sample </summary>

```

import 'package:flutter/material.dart';

/// Flutter code sample for [Checkbox].

void main() => runApp(const CheckboxExampleApp());

class CheckboxExampleApp extends StatelessWidget {
  const CheckboxExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('Checkbox Sample')),
        body: const Center(
          child: CheckboxExample(),
        ),
      ),
    );
  }
}

class CheckboxExample extends StatefulWidget {
  const CheckboxExample({super.key});

  @override
  State<CheckboxExample> createState() => _CheckboxExampleState();
}

class _CheckboxExampleState extends State<CheckboxExample> {
  bool isChecked = false;

  @override
  Widget build(BuildContext context) {
    Color getColor(Set<MaterialState> states) {
      const Set<MaterialState> interactiveStates = <MaterialState>{
        MaterialState.pressed,
        MaterialState.hovered,
        MaterialState.focused,
      };
      if (states.any(interactiveStates.contains)) {
        return Colors.blue;
      }
      return Colors.red;
    }

    return Checkbox.adaptive(
      checkColor: Colors.white,
      fillColor: MaterialStateProperty.all(Theme.of(context).colorScheme.primary),
      value: isChecked,
      onChanged: (bool? value) {
        setState(() {
          isChecked = value!;
        });
      },
    );
  }
}

```

</details>


https://github.com/flutter/flutter/assets/67046386/9bb44dc8-547c-4266-8643-06bec041dbdc


https://github.com/flutter/flutter/assets/67046386/f9512331-e500-4942-86a4-ba5ca837b8d1

**Comment by HansMuller** [comment]
The problem you're referring to exists with the all of the components that "adapt" to iOS by delegating to a Cupertino component.  We're about to resume work on https://github.com/flutter/flutter/pull/130425 which should establish a pattern for Material components that can be configured with iOS defaults (using an `adaptive` factory) and do so without delegating to a different toolkit or ignoring any properties.

CC @QuncCccccc @MitchellGoodwin

**Comment by feinstein** [comment]
That's great to hear, thanks a lot @HansMuller!

**Comment by Piinks** [comment]
Looks like this was resolved by the updates in https://github.com/flutter/flutter/pull/125643 👍
