### ISSUE TITLE
Flutter web operation error

### ISSUE THREAD

**Issue by cyb9701** [flutter/flutter#134924]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

The Flutter app is showing a web view.
The web view contains a web page created with the Flutter web project.

### Expected results

When a web page created with Flutter is displayed in a web view, it operates abnormally in certain actions.

### Actual results

When showing a web view created with Flutter web, if you take a close action with an iOS swipe and then return, the web page behaves strangely.

The first webview (Google) works normally, but
The second web view (Flutter web project) works abnormally.
These errors only occur on web pages created with Flutter web.

### Code sample

<details><summary>Code sample</summary>

This is general and simple flutter code.

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/59527787/add89038-574c-49e2-adfe-944b51cef1f0

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.5.2 22G91 darwin-arm64, locale
    ko-KR)
    • Flutter version 3.10.6 on channel stable at /Users/cyb/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (10 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/cyb/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/cyb/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/cyb/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Community Edition (version 2023.2.2)
    • IntelliJ at /Users/cyb/Applications/IntelliJ IDEA Community Edition.app
    • Flutter plugin version 75.1.4
    • Dart plugin version 232.9559.10

[✓] Connected device (2 available)
    • iPhone 13 mini (mobile) • 386704A8-0B1C-40D4-9A8C-18BCB03FD387 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 116.0.5845.187

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by darshankawar** [comment]
@cyb9701 Thanks for the report.
Can you provide a runnable minimal reproducible code sample that we can use that shows the reported behavior ?
