### ISSUE TITLE
[Flake] [Impeller] `CommandPoolRecyclerVKTest.GetsACommandPoolPerThread` is flaky.

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#134982]
This test closed the engine tree twice today:

- https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20linux_host_engine/6493/overview
- https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20linux_host_engine/6501/overview

FYI @matanlurey

**Comment by matanlurey** [comment]
Thanks! Taking a look now.
 
@bdero: I'm a bit curious why this only occurs (or happened to occur) on `host_debug_impeller_vulkan`, which I'm nuking in https://github.com/flutter/engine/pull/45999. Does that mean that certain tests are only run on that configuration (if so, I should close https://github.com/flutter/engine/pull/45999), or that `host_debug_impeller_vulkan`'s configuration is linked to the problem.

**Comment by bdero** [comment]
Yeah that's a good question, not sure yet.

**Comment by bdero** [comment]
host_debug_impeller_vulkan is the only step running this tests in linux_host_engine, at least.
