### ISSUE TITLE
Pinch zooming not working with interactive viewer

### ISSUE THREAD

**Issue by dharanidharandharmasivam** [flutter/flutter#134948]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Run the below sample

### Expected results

Pinch zooming functionality and vertical scrolling need to work on mobile devices while having ListView as a child for the InteractiveViewer. 

### Actual results

Only vertical scrolling works and pinch zooming not working.

### Code sample

<details><summary>Code sample</summary>

```dart
class ExamplePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Pinch-zoom test'),
      ),
      body: ListView.builder(
          itemBuilder: (context, index) {
            return Image.network('https://placekitten.com/640/360');
          },
          itemCount: 100),
    );
  }
}
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.13.2, on Microsoft Windows [Version 10.0.19044.3448], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.2)
[√] VS Code (version 1.81.1)
[√] Connected device (4 available)
[√] Network resources
```

</details>

**Comment by huycozy** [comment]
Hi @dharanidharandharmasivam 
I checked this issue with a complete sample code below. I still can pinch to zoom and scroll the list but it's not 100% working. I see there is a known issue for this behavior, please see if it's similar: https://github.com/flutter/flutter/issues/65006.

<details>
<summary>Complete sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const ExamplePage(),
    ),
  );
}

class ExamplePage extends StatelessWidget {
  const ExamplePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Pinch-zoom test'),
      ),
      body: InteractiveViewer(
        child: ListView.builder(
            itemBuilder: (context, index) {
              return Image.network('https://placekitten.com/640/360');
            },
            itemCount: 100),
      ),
    );
  }
}

```
</details>

**Comment by dharanidharandharmasivam** [comment]
@huycozy , yes you are right it is the same, in most cases pinch zoom not working and in my case, I can't use the column widget, so is there any workaround until we get a fix for this?

**Comment by dharanidharandharmasivam** [comment]
@huycozy , and while using ListView, I can make use of Fling, but with the column widget it's not. So I need to use the ListView widget, if there is any alternative, kindly provide your suggestion.

**Comment by huycozy** [comment]
I also tried this with widgets in a Column instead and noticed it's hard to pinch zoom as you see. But it's still the same issue with https://github.com/flutter/flutter/issues/65006 I think. I would recommend you leave a comment there about this case and react an upvote to the original comment that will help to raise the issue.

Closing this issue in favor of #65006. Please follow up on it for updates. Thanks!
