### ISSUE TITLE
_RouterState<T> does not call dispose on delegate or info provider

### ISSUE THREAD

**Issue by shovelmn12** [flutter/flutter#135005]
https://github.com/flutter/flutter/blob/367f9ea16bfae1ca451b9cc27c1366870b187ae2/packages/flutter/lib/src/widgets/router.dart#L731

As you can see in the code `RouterDelegate<T>.dispose()` and `RouteInformationProvider.dispose()` are not called:

```dart
  @override
  void dispose() {
    widget.routeInformationProvider?.removeListener(_handleRouteInformationProviderNotification);
    widget.backButtonDispatcher?.removeCallback(_handleBackButtonDispatcherNotification);
    widget.routerDelegate.removeListener(_handleRouterDelegateNotification);
    _currentRouterTransaction = null;
    super.dispose();
  }
```

**Comment by dam-ease** [comment]
Hi @shovelmn12 
I see there's an open issue addressing the case you described https://github.com/flutter/flutter/issues/134205.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you.
