### ISSUE TITLE
Include range of Xcode versions supported by Flutter as in Supported Platforms

### ISSUE THREAD

**Issue by bartekpacia** [flutter/flutter#135011]
I tried googling and searching but couldn't find it within 2 minutes. The [getting started](https://docs.flutter.dev/get-started/install/macos) guide recommends 14 but it doesn't sound too authoritative about it.

I'd like to have something like this: https://docs.flutter.dev/reference/supported-platforms

A mapping like: stable Flutter version -> supported Xcode version range

**Comment by stuartmorgan** [comment]
> The [getting started](https://docs.flutter.dev/get-started/install/macos) guide recommends 14 but it doesn't sound too authoritative about it.

Where are you seeing that recommendation? The docs I see there say:

>> Install the latest stable version of Xcode

**Comment by stuartmorgan** [comment]
> I'd like to have something like this: https://docs.flutter.dev/reference/supported-platforms

There's an important difference here in that Flutter developers control their own environment, but don't control the OS used by customers. Supporting older OS versions for deployment has much higher value than supporting old toolchains for developers.

**Comment by bartekpacia** [comment]
> Supporting older OS versions for deployment has much higher value than supporting old toolchains for developers.

Yeah I totally get it. Just having that written down somewhere would be nice tho :)

**Comment by stuartmorgan** [comment]
> Just having that written down somewhere would be nice

What is the problem you are trying to solve? `flutter doctor` already does enforcement of minimum versions, and the getting started docs recommend using the latest stable version (which seems like the right recommendation in that context.)

What is the use case for permanently maintaining more documentation (which would need to be updated on every stable release) with the exact range?

**Comment by bartekpacia** [comment]
> What is the problem you are trying to solve?

When new Xcode came out, I was unsure if "latest stable" applies to 14 or 15.

Not gonna push on that, I understand not the desire to not maintain documentation. Latest stable is good. Thanks for answering.
