### ISSUE TITLE
Issue with Flutter Widget Test Rendering Multiple Widgets.

### ISSUE THREAD

**Issue by Girisankar1** [flutter/flutter#135000]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a new Flutter widget test case.
2. Write a test case that renders multiple widgets.
3. Run the test case using the `flutter test`.

### Expected results

Render all widgets same time

### Actual results

First widgets on rendering, other widgets are not rendered properly.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Movable Icon on Image'),
        ),
        body: const Center(
          child: ImageWithMovableIcon(),
        ),
      ),
    );
  }
}

class ImageWithMovableIcon extends StatefulWidget {
  const ImageWithMovableIcon({super.key});

  @override
// ignore: library_private_types_in_public_api
  _ImageWithMovableIconState createState() => _ImageWithMovableIconState();
}

class _ImageWithMovableIconState extends State {
  Offset _iconPosition = const Offset(100, 100); // Initial position of the icon

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        Image.asset(
            'assets/Invoice.jpg'), // Replace 'your_image.png' with your image file path
        Positioned(
          left: _iconPosition.dx,
          top: _iconPosition.dy,
          child: Draggable(
            feedback: const Icon(
              Icons.star,
              size: 48.0,
              color: Colors.yellow,
            ),
            onDraggableCanceled: (_, __) {},
            onDragEnd: (details) {
              setState(() {
                _iconPosition = details.offset;
              });
            },
            child: const Icon(
              Icons.star,
              size: 48.0,
              color: Colors.yellow,
            ),
          ),
        ),
      ],
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by dam-ease** [comment]
Hi @Girisankar1. Thanks for filing this. Can you please provide the content of your `test/widget_test.dart` as well?
Thank you

**Comment by Girisankar1** [comment]
testWidgets(
    'should properly mock Image.network and not crash',
    (WidgetTester tester) async {
      
      await mockNetworkImages(() async => tester.pumpWidget(const ImageWithMovableIcon()));

    expect(find.text('0'), findsOneWidget);
    },

**Comment by huycozy** [comment]
@Girisankar1 The `mockNetworkImages` function is not found on your sample test. Please provide the complete sample test.

Also, regarding the sample code above, when I tried it with a small image, the upper widget on the Stack did not appear. It's caused by your `_iconPosition` distance being too wide. You can try setting size of Image (which is the underlying widget on Stack) to bigger (200x200 for eg) or decreasing `_iconPosition` distance to make sure all widgets are displaying when running the app.
