### ISSUE TITLE
NavigationBar has redundant bottom padding when not being laid out at the bottom as usual

### ISSUE THREAD

**Issue by smtp10185** [flutter/flutter#135030]
### Update ###

a simple PR: 
https://github.com/flutter/flutter/pull/135129

### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Initialize a navigation bar that's not at the bottom of the screen.

### Expected results

Due to 
1. https://github.com/flutter/flutter/issues/88888#issuecomment-905800876
2. https://m3.material.io/components/navigation-bar/overview

We should get a navigation bar without bottom padding.

### Actual results

Get a navigation bar with bottom padding, causing a layout issue.

### Code sample

<details><summary>Code sample</summary>

```dart
class Example extends StatelessWidget {
  const Example({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          elevation: 2,
          title: const Text("Title"),
        ),
        body: Column(children: <Widget>[
          NavigationBar(
            elevation: 2,
            onDestinationSelected: (int index) {},
            selectedIndex: 0,
            destinations: const <Widget>[
              NavigationDestination(
                selectedIcon: Icon(Icons.library_books),
                icon: Icon(Icons.library_books_outlined),
                label: 'A',
              ),
              NavigationDestination(
                selectedIcon: Icon(Icons.piano),
                icon: Icon(Icons.piano_outlined),
                label: 'B',
              ),
            ],
          ),
          Expanded(child: Container(color: Colors.red))
        ]));
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/flutter/flutter/assets/76031581/b8837618-ed21-4b29-a54b-c74d97c3e070)

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel master, 3.14.0-14.0.pre.358, on macOS 13.4 22F66 darwin-arm64, locale en-TW)
    • Flutter version 3.14.0-14.0.pre.358 on channel master at /Users/[username]/GitHub/flutter
    ! Upstream repository https://github.com/[username]/flutter.git is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to https://github.com/[username]/flutter.git to dismiss this error.
    • Framework revision 8936504163 (10 hours ago), 2023-09-19 02:10:24 -0400
    • Engine revision 589bde9a95
    • Dart version 3.2.0 (build 3.2.0-174.0.dev)
    • DevTools version 2.28.0-dev.8
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and
      upgrades.

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • iPhone 14 (mobile) • 031EAC49-60E0-4D56-BA84-71FC5AE470FA • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 116.0.5845.187

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

</details>

**Comment by smtp10185** [comment]
I believe the simplest solution is to provide a parameter for the Navigation Bar to remove the SafeArea, ensuring that the existing code remains error-free. However, to adhere to best practices, the SafeArea logic of the NavigationBar should be moved and implemented within the bottomNavigationBar section of the Scaffold.

**Comment by huycozy** [comment]
I checked this on Android/iOS and see it has the same padding when the NavigationBar on top or bottom:

<details>
<summary>Demo (Android)</summary>

| top | bot |
| --------------- | --------------- |
<img width="400" src="https://github.com/flutter/flutter/assets/104349824/3a27f4b1-bb13-4991-aca0-6029bec4e0b3"> | <img width="400" src="https://github.com/flutter/flutter/assets/104349824/e9863efb-f43b-42b3-af9e-80bbb8a25eeb">

</details>

Your demo image above does not correspond to the sample code, please provide the sample code that presents the issue. Thanks!

**Comment by smtp10185** [comment]
Here's the new complete code: 
```
class Example extends StatelessWidget {
  const Example({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          elevation: 2,
          title: const Text("Title"),
        ),
        body: Column(children: <Widget>[
          NavigationBar(
            useSafeArea: false  // check this
            elevation: 2,
            onDestinationSelected: (int index) {},
            selectedIndex: 0,
            destinations: const <Widget>[
              NavigationDestination(
                selectedIcon: Icon(Icons.library_books),
                icon: Icon(Icons.library_books_outlined),
                label: 'A',
              ),
              NavigationDestination(
                selectedIcon: Icon(Icons.piano),
                icon: Icon(Icons.piano_outlined),
                label: 'B',
              ),
            ],
          ),
          Expanded(child: Container(color: Colors.red))
        ]));
  }
}

void main() {
  runApp(const Example());
}
```

Here's the image: 
![Simulator Screenshot - iPhone 14 - 2023-09-20 at 19 09 41](https://github.com/flutter/flutter/assets/76031581/7e42ed81-49ab-464f-8486-84483d1a07f3)


The main issue is caused by SafeArea.
So, perhaps some models might not be affected.
I've made a simple PR, please take another look~"

**Comment by huycozy** [comment]
I checked this issue again on iPhone 14 Pro, iOS 16.4, and can see the issue now.

| NavigationBar on top | NavigationBar on bottom |
| --------------- | --------------- |
<img width="400" src="https://github.com/flutter/flutter/assets/104349824/9a6a18f6-90d2-4c8c-86f7-b853428430e3"> | <img width="400" src="https://github.com/flutter/flutter/assets/104349824/b256915f-121a-4646-b5d4-3e1c323394e1">

Debugging this on Widget inspector and see NavigationBar has bottom padding(34.0):

![Screenshot 2023-09-21 at 11 20 26](https://github.com/flutter/flutter/assets/104349824/0c793c20-c40d-41a7-846d-50287c7de217)

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.13.4, on macOS 13.5 22G74 darwin-x64, locale en-VN)
    • Flutter version 3.13.4 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 367f9ea16b (31 hours ago), 2023-09-12 23:27:53 -0500
    • Engine revision 9064459a8b
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode15RC.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.82.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (5 available)
    • RMX2001 (mobile)       • EUYTFEUSQSRGDA6D                         • android-arm64  • Android 11 (API 30)
    • iPhone (mobile)        • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.7.2 19H218
    • iPhone 14 Pro (mobile) • 3BD60F46-FB95-41A0-A179-8AA3F637DA4E     • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)        • macos                                    • darwin-x64     • macOS 13.5 22G74 darwin-x64
    • Chrome (web)           • chrome                                   • web-javascript • Google Chrome 117.0.5938.62

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.14.0-14.0.pre.407, on macOS 13.5 22G74 darwin-x64, locale en-VN)
    • Flutter version 3.14.0-14.0.pre.407 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c416aa4735 (20 minutes ago), 2023-09-20 23:09:24 -0400
    • Engine revision 76e5e35ab3
    • Dart version 3.2.0 (build 3.2.0-185.0.dev)
    • DevTools version 2.28.0-dev.12
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 13.5 22G74 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 117.0.5938.62

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by QuncCccccc** [comment]
Hi! Thanks a lot for filing this issue and creating the PR! Just wonder why don't we use `TabBar` on top instead of using `NavigationBar`? Based on the Material Design 3, the `NavigationBar` is the new name for bottom navigation and should be positioned [at the bottom of the screen](https://m3.material.io/components/navigation-bar/guidelines#:~:text=The%20nav%20bar%20is%20positioned%20at%20the%20bottom%20of%20screens%20for%20convenient%20access.).

**Comment by smtp10185** [comment]
> Hi! Thanks a lot for filing this issue and creating the PR! Just wonder why don't we use `TabBar` on top instead of using `NavigationBar`? Based on the Material Design 3, the `NavigationBar` is the new name for bottom navigation and should be positioned [at the bottom of the screen](https://m3.material.io/components/navigation-bar/guidelines#:~:text=The%20nav%20bar%20is%20positioned%20at%20the%20bottom%20of%20screens%20for%20convenient%20access.).

You are correct. Indeed, in the material3 website documentation, there is a description suggesting that the NavigationBar should be placed at the bottom. However, after the renaming, perhaps we can consider using it for different components.

Furthermore, according to the TabBar standard within material3, it implies horizontal scrolling (https://m3.material.io/components/tabs/overview - Tabs can horizontally scroll). In the implementation of certain components, Navigation and Tabs provide users with entirely different experiences - one involves scrollable behavior, while the other entails completely different page transitions.

In a business logic we previously implemented, because the pages that need to be switched are within the same logical context, the sliding behavior of the TabBar can lead to incorrect behavior hints. Therefore, I hope that in the implementation, we can have a NavigationBar for complete page transitions that doesn't have to be positioned at the bottom.

If Flutter's implementation needs to strictly adhere to the guidelines, then it's true that we should reconsider this aspect. However, it seems that some discrepancies in the documentation have arisen due to the renaming process.

**Comment by smtp10185** [comment]
> Hi! Thanks a lot for filing this issue and creating the PR! Just wonder why don't we use `TabBar` on top instead of using `NavigationBar`? Based on the Material Design 3, the `NavigationBar` is the new name for bottom navigation and should be positioned [at the bottom of the screen](https://m3.material.io/components/navigation-bar/guidelines#:~:text=The%20nav%20bar%20is%20positioned%20at%20the%20bottom%20of%20screens%20for%20convenient%20access.).

I'm sorry, the AI-refined text may sound a bit verbose.
If you assess that this issue doesn't affect the majority of users, I will close the issue.
