### ISSUE TITLE
[Impeller] screen flashes dark color when applying menu blur

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#135053]
![image](https://github.com/flutter/flutter/assets/8975114/c0f429b7-4df2-4894-b546-3d7ab4570e2a)

Having trouble capturing a video right now, but clicking this menu and the screen will flash a dark color for a second. Reminds me of issues with the previous clear color optimization.

**Comment by bdero** [comment]
https://github.com/flutter/flutter/assets/919017/b3d1e7a0-4ea1-4c82-988b-f7a2252370a1

**Comment by jonahwilliams** [comment]
Closing as this is fixed!
