### ISSUE TITLE
Problem when embedding a Flutter app into Rails html

### ISSUE THREAD

**Issue by Hau-tt** [flutter/flutter#135016]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

First of all, my goal is to display a specific link of my flutter web app with flutter.js and the hostElement engine initialization parameter. Link to [document](https://docs.flutter.dev/deployment/web#choosing-a-web-renderer)

I did try this approaching https://github.com/flutter/flutter/issues/125330#issuecomment-1520946370. But it doesn't work either.

**Note**:
Domain server Flutter apps are different from Rails web.

### Expected results

Fully load an page with embeded Flutter

### Actual results

Return a blank page with some errors related with History, which I'm not sure if it is the cause
`SecurityError: Failed to execute 'replaceState' on 'History': A history state object with URL 'https://example.com/demo' cannot be created in a document with origin 'http://localhost:3000' and URL 'http://localhost:3000/demo'
`
### Code sample

```
<!DOCTYPE html>
<html>
  <head>
    <%= display_meta_tags %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <base href="https://example.com/">
    <script src="flutter.js" defer></script>
  </head>

  <body>
    <script>
      window.addEventListener('load', function (ev) {
        // Download main.dart.js
        _flutter.loader.loadEntrypoint({
          onEntrypointLoaded: async function(engineInitializer) {
            // Initialize the Flutter engine
            let appRunner = await engineInitializer.initializeEngine();
            // Run the app
            await appRunner.runApp();
          }
        });
      });
    </script>
  </body>
</html>
```

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/flutter/flutter/assets/81552435/94b07155-e78d-4df0-9a1f-a8d78bdcdbcb)
![image](https://github.com/flutter/flutter/assets/81552435/e17a41ae-a948-411d-bfa7-2a889bb432e3)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.3 22E252 darwin-x64, locale en-US)
    • Flutter version 3.10.5 on channel stable at /Users/sid/Desktop/FLUTTER/SDKs/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (3 months ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/sid/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      :hammer: https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      :hammer: https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
[✓] VS Code (version 1.82.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0
[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.3 22E252 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 117.0.5938.88
[✓] Network resources
    • All expected network resources are available.
• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @Hau-tt 
I see you are using `<base href="https://example.com/">` instead of `<base href="$FLUTTER_BASE_HREF">` by default. Is there any specific reason related to this? Does the issue happen with the default base href?

Also, the code sample doesn't seem to be integrated with the embedding element yet.

**Comment by Hau-tt** [comment]
> Hi @Hau-tt I see you are using `<base href="https://example.com/">` instead of `<base href="$FLUTTER_BASE_HREF">` by default. Is there any specific reason related to this? Does the issue happen with the default base href?
> 
> Also, the code sample doesn't seem to be integrated with the embedding element yet.

I believe that the base url should point to the host containing the main.dart.js and other files. Also the server host Flutter apps are different from Rails web. I did tried using `<base href="$FLUTTER_BASE_HREF">` too but it won't work either, now it throw `Uncaught ReferenceError: _flutter is not defined`.

> Also, the code sample doesn't seem to be integrated with the embedding element yet.

Is it  `hostElement`? If so I tried it and it didn't work either

**Comment by huycozy** [comment]
Could you please share a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) with detailed steps to reproduce this (unfortunately, I'm not familiar with Rails)

**Comment by Hau-tt** [comment]
```
<!DOCTYPE html>
<html>
  <head>
    <base href="https://s3.us-west-2.amazonaws.com/dev.bespoke.ly/">
    <script src="https://s3.us-west-2.amazonaws.com/dev.bespoke.ly/flutter.js" defer></script>
  </head>

  <body>
    <script>
      window.addEventListener('load', function (ev) {
        // Download main.dart.js
        _flutter.loader.loadEntrypoint({
          onEntrypointLoaded: async function(engineInitializer) {
            // Initialize the Flutter engine
            let appRunner = await engineInitializer.initializeEngine();
            // Run the app
            await appRunner.runApp();
          }
        });
      });
    </script>
  </body>
</html>
```
Here's my example code, showing how I'm implementing the embed feature right now. It behaviour exactly the same on my rails

**Comment by Hau-tt** [comment]
> Could you please share a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) with detailed steps to reproduce this (unfortunately, I'm not familiar with Rails)

```
<!DOCTYPE html>
<html>
  <head>
    <base href="https://s3.us-west-2.amazonaws.com/dev.bespoke.ly/">
    <script src="https://s3.us-west-2.amazonaws.com/dev.bespoke.ly/flutter.js" defer></script>
  </head>

  <body>
    <script>
      window.addEventListener('load', function (ev) {
        // Download main.dart.js
        _flutter.loader.loadEntrypoint({
          onEntrypointLoaded: async function(engineInitializer) {
            // Initialize the Flutter engine
            let appRunner = await engineInitializer.initializeEngine();
            // Run the app
            await appRunner.runApp();
          }
        });
      });
    </script>
  </body>
</html>
```
@huycozy Here's my example code, showing how I'm implementing the embed feature right now. It behaviour exactly the same on my rails

**Comment by huycozy** [comment]
Hi, Thanks for your update but I'm still not clear on the steps to reproduce this issue. It would be appreciated if you could share it step-by-step on both Flutter and Rails sample that will help domain team can capture the issue better. 

Regarding the error message, it looks like an issue with path/route from Rails app, please check [this](https://github.com/angular/angular/issues/49610) if it helps.

**Comment by Hau-tt** [comment]
Thanks. Here is the background, I've a Flutter app that already host in this domain [https://dev.bespoke.ly](https://dev.bespoke.ly/). And now I just want to embed it in my blank Rails webpage on localhost. Do you have any suggests to make this work

**Comment by huycozy** [comment]
If so, simply put your Flutter web app inside an iframe like this:

```html
<!DOCTYPE html>
<html>
<head>
</head>
<body>
    <h1>HTML element</h1>
    <iframe src="https://dev.bespoke.ly" width="100%" height="500px"></iframe>
    <h1>HTML element</h1>
</body>
</html>
```
### Demo

<img width="400" src="https://github.com/flutter/flutter/assets/104349824/19d5dc1b-08ae-412f-a8c0-08855c36f60c">

**Comment by echo718** [comment]
> _flutter

how to pass token using iframe?
