### ISSUE TITLE
[Impeller] Rasterizer::ScreenshotLayerTreeAsImage uses Skia rendering when running with Impeller.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#135052]
Only part of the screen seems to be captured on Wonderous. On iOS 17 the native screenshot tool is broken so we're falling back to rasterizer screenshots. These aren't setting up an aiks context, so its rendering skia but no images.

Expected:

![flutter_01](https://github.com/flutter/flutter/assets/8975114/6ecdeacc-17b4-4782-ac2f-91bcc78fb68f)

Actual:

![flutter_02](https://github.com/flutter/flutter/assets/8975114/2e68cc30-9f49-4696-8730-f2a661c3b01b)

**Comment by jason-simmons** [comment]
How are you obtaining the screenshots?

I noticed that if I use `flutter screenshot --type=rasterizer`, then any images drawn in the scene will not be captured in the screenshot.

`Rasterizer::ScreenshotLayerTreeAsImage` is not setting up an `AiksContext`.  So `CompositorContext::ScopedFrame::Raster` is actually going through the Skia painting code path instead of using Impeller.

**Comment by jonahwilliams** [comment]
This is using the `s` button in the flutter tool, I'm not actually sure what that is using but I thought it was using some cmdline flutter utility.

**Comment by jonahwilliams** [comment]
Oh, maybe on iOS17 the cmd line tool for screenshots isn't working so we're falling back to the rasterizer screenshot? @christopherfujino does this sound right?

**Comment by christopherfujino** [comment]
Hmm, I'm actually surprised we got a screenshot at all, I thought this was completely broken per: https://github.com/flutter/flutter/issues/128598. Was this with a physical phone?

cc @vashworth

**Comment by jonahwilliams** [comment]
Yes!

**Comment by jonahwilliams** [comment]
Ahh:

>   /// If the device type does not support a "native" screenshot, then this
  /// will fallback to a rasterizer screenshot from the engine. This has the
  /// downside of being unable to display the contents of platform views.
  
  resident_runner L974

**Comment by jonahwilliams** [comment]
So we either need to fix Rasterizer::ScreenshotLayerTreeAsImage to use impeller correctly, or disable this functionality when using impeller entirely. Probably no action needed on tools side.
