### ISSUE TITLE
SplayTreeMap omitting nodes with matching key/value pairs?

### ISSUE THREAD

**Issue by CharlesCleveJr** [flutter/flutter#13504]
When using a SplayTreeMap to map key/value pairs of a Firebase node, I've found that nodes with matching key/value pairs only return 1 node and omit all others.  Here is the code I'm using...

[DartPad Example](https://dartpad.dartlang.org/48149723e4bc4503a886becf130e1e03)

`final sorted = new SplayTreeMap<String,dynamic>.from(map, (a, b) => map[b]['rank'].compareTo(map[a]['rank']));`

Here are examples of the nodes I'm returning...

```
var map = {
  "Vid2": {
    "imageString": "https://i.ytimg.com/vi/Amq-qlqbjYA/mqdefault.jpg",
    "title": "BLACKPINK - '마지막처럼 (AS IF IT'S YOUR LAST)' M/V",
    "rank": "2",
    "videoID": "Amq-qlqbjYA"
  },
  "Vid10": {
    "imageString": "https://i.ytimg.com/vi/KSH-FVVtTf0/mqdefault.jpg",
    "title": "EXO 엑소 'Monster' MV",
    "rank": "2",
    "videoID": "KSH-FVVtTf0"
  },
  "Vid6": {
    "imageString": "https://i.ytimg.com/vi/BVwAVbKYYeM/mqdefault.jpg",
    "title": "[MV] BTS(방탄소년단) _ DOPE(쩔어)",
    "rank": "2",
    "videoID": "BVwAVbKYYeM"
  }}
```

Is this an issue or am I using the wrong properties???

**Comment by zoechi** [comment]
As far as I know this is the intended behavior of `SplayTreeMap`
https://stackoverflow.com/questions/47664718/how-to-use-a-splaytreemap-on-firebase-snapshot-dictionary-in-dart-flutter/47669085#47669085

**Comment by Hixie** [comment]
This sounds like a Dart SDK issue. If you still believe this should be changed, please file it at dart-lang/sdk. Thanks.
