### ISSUE TITLE
[image_picker] select non image files crash

### ISSUE THREAD

**Issue by FrankyLee-dev** [flutter/flutter#135008]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Use the ```pickImage``` method to open gallery and select non image files
```
          file = await _picker.pickImage(
            source: ImageSource.gallery,
            imageQuality: 70,
          );

```
2. Crash Log:
```
E/BitmapFactory(21466): Unable to decode stream: java.lang.NullPointerException
E/AndroidRuntime(21466): FATAL EXCEPTION: pool-1-thread-1
E/AndroidRuntime(21466): Process: com.zhichan.bbcamera, PID: 21466
E/AndroidRuntime(21466): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
E/AndroidRuntime(21466): 	at io.flutter.plugins.imagepicker.ImageResizer.resizeImageIfNeeded(ImageResizer.java:46)
E/AndroidRuntime(21466): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.getResizedImagePath(ImagePickerDelegate.java:765)
E/AndroidRuntime(21466): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleImageResult(ImagePickerDelegate.java:753)
E/AndroidRuntime(21466): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:634)
E/AndroidRuntime(21466): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.lambda$onActivityResult$0$io-flutter-plugins-imagepicker-ImagePickerDelegate(ImagePickerDelegate.java:605)
E/AndroidRuntime(21466): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate$$ExternalSyntheticLambda0.run(Unknown Source:6)
E/AndroidRuntime(21466): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(21466): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(21466): 	at java.lang.Thread.run(Thread.java:919)
Lost connection to device.

```
3. Working normally without setting the ```imageQuality``` parameter

### Expected results

Can there be optional settings when opening the gallery selection, only the selection of images.

### Actual results

Open the gallery selection, but you can still select the file manager to select other files

### Code sample

<details><summary>Code sample</summary>

```dart
final ImagePicker _picker = ImagePicker();
XFile? file = await _picker.pickImage(
            source: ImageSource.gallery,
            imageQuality: 70,
          );
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/17977044/ed0321c1-b77a-489b-9199-e484c03e4028

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
E/BitmapFactory(21466): Unable to decode stream: java.lang.NullPointerException
E/AndroidRuntime(21466): FATAL EXCEPTION: pool-1-thread-1
E/AndroidRuntime(21466): Process: com.zhichan.bbcamera, PID: 21466
E/AndroidRuntime(21466): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
E/AndroidRuntime(21466): 	at io.flutter.plugins.imagepicker.ImageResizer.resizeImageIfNeeded(ImageResizer.java:46)
E/AndroidRuntime(21466): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.getResizedImagePath(ImagePickerDelegate.java:765)
E/AndroidRuntime(21466): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleImageResult(ImagePickerDelegate.java:753)
E/AndroidRuntime(21466): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:634)
E/AndroidRuntime(21466): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.lambda$onActivityResult$0$io-flutter-plugins-imagepicker-ImagePickerDelegate(ImagePickerDelegate.java:605)
E/AndroidRuntime(21466): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate$$ExternalSyntheticLambda0.run(Unknown Source:6)
E/AndroidRuntime(21466): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(21466): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(21466): 	at java.lang.Thread.run(Thread.java:919)
Lost connection to device.
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.3, on macOS 13.4 22F66 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 14.2)
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.82.0)
[✓] Connected device (3 available)
```

</details>

**Comment by dam-ease** [comment]
Hi @FrankyLee-dev. Thanks for filing this issue. I can't seem to pick a non-image when setting Image source as `ImageSource.gallery`. Are you using the latest version of the `image_picker` package and the latest version of flutter? Can you test with the sample code on the `image_picker` package [code](https://pub.dev/packages/image_picker/example) to see if the issue persists?

**Comment by stuartmorgan** [comment]
We should make sure a null path can't get that far into the code, with checks earlier in the process.

**Comment by stuartmorgan** [comment]
> I can't seem to pick a non-image when setting Image source as `ImageSource.gallery`.

This is going to be a function of the intent handler for image picking being used on the device.


> ### Expected results
> Can there be optional settings when opening the gallery selection, only the selection of images.
> 
> ### Actual results
> Open the gallery selection, but you can still select the file manager to select other files

@FrankyLee-dev You should report an issue to the developer of the image picker application that you are using to handle image selection intents. The intent we using is, explicitly, for selecting images, so the fact that your handler is allowing you to pick arbitrary files is a bug in that software, and is beyond the control of the plugin.

**Comment by FrankyLee-dev** [comment]
> Hi @FrankyLee-dev. Thanks for filing this issue. I can't seem to pick a non-image when setting Image source as `ImageSource.gallery`. Are you using the latest version of the `image_picker` package and the latest version of flutter? Can you test with the sample code on the `image_picker` package [code](https://pub.dev/packages/image_picker/example) to see if the issue persists?

Hi, @dam-ease @stuartmorgan  I use the following code to open the image selector `android 10`
```
final ImagePicker _picker = ImagePicker();
XFile? file = await _picker.pickImage(
     source: ImageSource.gallery,
     imageQuality: 70,
);
```
screenshot：
![002_mosaic](https://github.com/flutter/flutter/assets/17977044/5eeaf427-0c09-49fd-8898-479b4366bb93)


I can select non-image in ```File Manager```

I may need to try multiple Android versions

flutter version: Channel stable, 3.13.3
image_picker version: ^1.0.4

**Comment by gmackall** [comment]
> We should make sure a null path can't get that far into the code, with checks earlier in the process.

It should be easy to add that logic to https://github.com/flutter/packages/pull/5009, I can make that change.

**Comment by stepanov-standy** [comment]
Hi Team, any updates on the fix? I observe ~1000 crashes during last 3 months in production. I agree that it is not fully on the side of image_picker library, but if it is possible to avoid NPE and protect users from selecting wrong types of files, it is great.

**Comment by stepanov-standy** [comment]
Hi Team and @gmackall May I know when do you plan to merge the fix to handle null path case gracefully? I have that problem on both platforms iOS and Android and would like to provide better user experience even for such non intended use case.
