### ISSUE TITLE
tag 3.13.4 gclient sync failed to resolve dart-sdk for windows x86

### ISSUE THREAD

**Issue by leannlc** [flutter/flutter#135001]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. I'm attempting to compile a compatible version of the engine for my windows x64 machine.
After setting up the the engine development environment, I get the following when trying to run 'gclient sync':
2. my .gclient
```
solutions = [
  {
    "managed": False,
    "name": "src/flutter",
    "url": "git@github.com:flutter/engine.git@9064459a8b0dcd32877107f6002cc429a71659d1",
    "custom_deps": {},
    "deps_file": "DEPS",
    "safesync_url": "",
    "custom_vars" : { 
      "download_android_deps" : False,
    },
  },
]
```
4. gclient sync
output:
```console
Updating depot_tools...
Syncing projects: 100% (134/134), done.

________ running 'cipd ensure -log-level error -root C:\Users\banma-1179\Work\flutter3\flutter_3_13_4\engine -ensure-file C:\Users\BANMA-~1\AppData\Local\Temp\tmp60albkvj.ensure' in '.'
Errors:
  failed to resolve flutter/dart-sdk/windows-arm64@git_revision:9bf2f88a8ba82fcfdc5960ac9c92e0e03fc0acef (line 5): no such tag
Error: Command 'cipd ensure -log-level error -root C:\\Users\\banma-1179\\Work\\flutter3\\flutter_3_13_4\\engine -ensure-file C:\\Users\\BANMA-~1\\AppData\\Local\\Temp\\tmp60albkvj.ensure' returned non-zero exit status 1
Errors:
  failed to resolve flutter/dart-sdk/windows-arm64@git_revision:9bf2f88a8ba82fcfdc5960ac9c92e0e03fc0acef (line 5): no such tag
```
5.actually my windows is x64, windows-arm64 is not needed, how can I resovle this problem

### Expected results

gclient sync success

### Actual results
```console
glient sync failed to resovle  flutter/dart-sdk/windows-arm64@git_revision:9bf2f88a8ba82fcfdc5960ac9c92e0e03fc0acef (line 5): no such tag
```
### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by leannlc** [comment]
I find window-amd64 version of dart version 3.12 in cipd https://chrome-infra-packages.appspot.com/p/dart/dart-sdk/windows-amd64/+/git_revision:9bf2f88a8ba82fcfdc5960ac9c92e0e03fc0acef
But I can't find window-arm64 corresponding version in cipd
And my machine is windowx64, dart-sdk of window-arm64 is not needed for my machine
so why gclient sync failed

**Comment by huycozy** [comment]
There is a similar issue at https://github.com/flutter/flutter/issues/131980 and the OP can solve it by using master revision. Please also try to see if it's applied to you.

**Comment by leannlc** [comment]
> There is a similar issue at #131980 and the OP can solve it by using master revision. Please also try to see if it's applied to you.

I had saw this issue at #131980 , but want to use tag version, like 3.13.4 or 3.13.3 and so on, I think it's more stable
