### ISSUE TITLE
[webview_flutter_wkwebview] 'Flutter/Flutter.h' file not found Xcode 15

### ISSUE THREAD

**Issue by Auramel** [flutter/flutter#135099]
I'm upgraded on Xcode 15 and has this problem on build
![image](https://github.com/flutter/flutter/assets/5775873/1c061865-7495-4990-b411-98ab84b6da84)

I update Podfile before because I have error on build 
`DT_TOOLCHAIN_DIR cannot be used to evaluate LIBRARY_SEARCH_PATHS, use TOOLCHAIN_DIR instead`

<details>
<summary>Podfile</summary>
<pre>
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.base_configuration_reference
        xcconfig_path = config.base_configuration_reference.real_path
        xcconfig = File.read(xcconfig_path)
        xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
        File.open(xcconfig_path, "w") { |file| file << xcconfig_mod } 
      end
    end
  end
end
</pre>
</details>

I make flutter **flutter pub get** and **flutter pub upgrade**
I use mac os on m1, Ventura 13.5.2

<details>
<summary>flutter doctor -v</summary>
<pre>
[✓] Flutter (Channel stable, 3.13.4, on macOS 13.5.2 22G91 darwin-arm64, locale
    ru-RU)
    • Flutter version 3.13.4 on channel stable at
      /opt/homebrew/Caskroom/flutter/3.10.3/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 367f9ea16b (7 дней назад), 2023-09-12 23:27:53 -0500
    • Engine revision 9064459a8b
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (3 available)
    • iPhone 15 Pro (mobile) • F2DFADF7-4A62-4EA8-8293-85735B8CABBB • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.5.2 22G91 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 116.0.5845.187

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
</pre>
</details>

**Comment by dam-ease** [comment]
Hi @Auramel. Thanks for filing this. Can you try out the suggested solution in this [thread](https://stackoverflow.com/a/64993852) to see if it works in your case?

**Comment by Auramel** [comment]
@dam-ease Hello. Yes, I did it. It is not solved my problem. I found [this](https://stackoverflow.com/questions/71724105/how-do-i-resolve-lexical-or-preprocessor-issue-xcode-flutter-flutter-h-fil) thread and it not help me too.

**Comment by Auramel** [comment]
I have same problem with url_laucnher package. After **flutter pub upgrade** it disappeared

**Comment by Auramel** [comment]
I think the problem is in my Podfile. [Here](https://github.com/CocoaPods/CocoaPods/pull/12009) guy has same problem

**Comment by chanjungkim** [comment]
I did all the things on the internet and nothing worked!

Please don't update to xcode 15.  That's terrible.

**Comment by Auramel** [comment]
@chanjungkim I'm downgraded to **Xcode 14.3.1**, then delete:
- ios/Pods
- ios/Podfile.lock
- ios/.symlinks
- pubspec.lock
Remove all Xcode files from my computer (Caches, Virtual devices and other)
run
- flutter clean
- flutter pub get
- flutter pub upgrade
and it worked.

**Comment by stoppimyse** [comment]
hi, i receive this error, xcode15 ios 17

`#import <Flutter/Flutter.h>
#import <Foundation/Foundation.h>
#import <WebKit/WebKit.h>

NS_ASSUME_NONNULL_BEGIN

/**
 * App and package facing native API provided by the `webview_flutter_wkwebview` plugin.
 *
 * This class follows the convention of breaking changes of the Dart API, which means that any
 * changes to the class that are not backwards compatible will only be made with a major version
 * change of the plugin. Native code other than this external API does not follow breaking change
 * conventions, so app or plugin clients should not use any other native APIs.
 */
@interface FWFWebViewFlutterWKWebViewExternalAPI : NSObject
/**
 * Retrieves the `WKWebView` that is associated with `identifier`.
 *
 * See the Dart method `WebKitWebViewController.webViewIdentifier` to get the identifier of an
 * underlying `WKWebView`.
 *
 * @param identifier The associated identifier of the `WebView`.
 * @param registry The plugin registry the `FLTWebViewFlutterPlugin` should belong to. If
 *        the registry doesn't contain an attached instance of `FLTWebViewFlutterPlugin`,
 *        this method returns nil.
 * @return The `WKWebView` associated with `identifier` or nil if a `WKWebView` instance associated
 * with `identifier` could not be found.
 */
+ (nullable WKWebView *)webViewForIdentifier:(long)identifier
                          withPluginRegistry:(id<FlutterPluginRegistry>)registry;
@end

NS_ASSUME_NONNULL_END`

**Comment by huycozy** [comment]
I also use `XCode 15 Build 15A240d` and run below sample code on iPhone 14 Pro, iOS 17.0 but can't reproduce this issue.

<details>
<summary>Minimal sample code</summary>

```dart
// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// ignore_for_file: public_member_api_docs

import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(const MaterialApp(home: WebViewExample()));

class WebViewExample extends StatefulWidget {
  const WebViewExample({super.key});

  @override
  State<WebViewExample> createState() => _WebViewExampleState();
}

class _WebViewExampleState extends State<WebViewExample> {
  late final WebViewController controller;

  @override
  void initState() {
    super.initState();

    // #docregion webview_controller
    controller = WebViewController()
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setBackgroundColor(const Color(0x00000000))
      ..setNavigationDelegate(
        NavigationDelegate(
          onProgress: (int progress) {
            // Update loading bar.
          },
          onPageStarted: (String url) {},
          onPageFinished: (String url) {},
          onWebResourceError: (WebResourceError error) {},
          onNavigationRequest: (NavigationRequest request) {
            if (request.url.startsWith('https://www.youtube.com/')) {
              return NavigationDecision.prevent;
            }
            return NavigationDecision.navigate;
          },
        ),
      )
      ..loadRequest(Uri.parse('https://google.com/'));
    // #enddocregion webview_controller
  }

  // #docregion webview_widget
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Flutter Simple Example')),
      body: WebViewWidget(controller: controller),
    );
  }
// #enddocregion webview_widget
}
```
</details>

Can you try running this sample on new project or [plugin example](https://github.com/flutter/packages/tree/main/packages/webview_flutter/webview_flutter/example) to see if you can replicate the issue?

**Comment by stoppimyse** [comment]
@Auramel have you resolve?

**Comment by stoppimyse** [comment]
@huycozy hi, for firebase we have chenge the podfile for the bug  DT_TOOLCHAIN_DIR cannot be used to evaluate LIBRARY_SEARCH_PATHS, use TOOLCHAIN_DIR instead. I think the problem is here, can you try to add firebase and change the podfile.

**Comment by Auramel** [comment]
@stoppimyse no, I delete Xcode 15 and install Xcode 14.3.1

**Comment by stoppimyse** [comment]
i've resolve usinng this podfile configuration

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    # shim for CocoaPods issue, should remove when 1.13.0 is released
    # more info: https://github.com/CocoaPods/CocoaPods/issues/12012#issuecomment-1659803356
    target.build_configurations.each do |config|
      xcconfig_path = config.base_configuration_reference.real_path
      xcconfig = File.read(xcconfig_path)
      xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
      File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
    end
  end
end
```

**Comment by Auramel** [comment]
@huycozy yes, I create new project and it running on Xcode 15. But! I replaced my ios folder from new flutter project and it not working.

**Comment by huycozy** [comment]
@Auramel I can reproduce this issue with your initial Podfile configuration but I notice it's missing `flutter_additional_ios_build_settings(target)` when comparing it with @stoppimyse's comment above. And it indeed works after I added the line back (it's the default when creating a project). Can you try adding it back and confirm?

Also, regarding https://github.com/flutter/flutter/issues/135099#issuecomment-1729214830, there is a related topic at flutterfire repository: https://github.com/firebase/flutterfire/issues/11614. It's cocoapods issue and looks like you are attempting to solve it with [workaround](https://github.com/CocoaPods/CocoaPods/issues/12012#issuecomment-1659803356), right?

@Auramel @chanjungkim Please try the [podfile configuration above](https://github.com/flutter/flutter/issues/135099#issuecomment-1729362879) and confirm this.

**Comment by TiluWeb** [comment]
> i've resolve usinng this podfile configuration
> 
> ```
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     flutter_additional_ios_build_settings(target)
> 
>     # shim for CocoaPods issue, should remove when 1.13.0 is released
>     # more info: https://github.com/CocoaPods/CocoaPods/issues/12012#issuecomment-1659803356
>     target.build_configurations.each do |config|
>       xcconfig_path = config.base_configuration_reference.real_path
>       xcconfig = File.read(xcconfig_path)
>       xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
>       File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
>     end
>   end
> end
> ```

With this, I got : 
Error (Xcode): SDK does not contain 'libarclite' at the path '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphonesimulator.a'; try increasing the minimum deployment target

**Comment by Auramel** [comment]
> @Auramel I can reproduce this issue with your initial Podfile configuration but I notice it's missing `flutter_additional_ios_build_settings(target)` when comparing it with @stoppimyse's comment above. And it indeed works after I added the line back (it's the default when creating a project). Can you try adding it back and confirm?
> 
> Also, regarding [#135099 (comment)](https://github.com/flutter/flutter/issues/135099#issuecomment-1729214830), there is a related topic at flutterfire repository: [firebase/flutterfire#11614](https://github.com/firebase/flutterfire/issues/11614). It's cocoapods issue and looks like you are attempting to solve it with [workaround](https://github.com/CocoaPods/CocoaPods/issues/12012#issuecomment-1659803356), right?
> 
> @Auramel @chanjungkim Please try the [podfile configuration above](https://github.com/flutter/flutter/issues/135099#issuecomment-1729362879) and confirm this.

My Podfile configuration I found in Google. Ok, I will try. I deleted Xcode 15, I'll have to download it again.

**Comment by stuartmorgan** [comment]
Flutter should inject a workaround for the `DT_TOOLCHAIN_DIR` issue the first time you run, so manually changing your Podfile to do that should not be necessary unless you already had a custom Podfile.

**Comment by Auramel** [comment]
![image](https://github.com/flutter/flutter/assets/5775873/9ee1e845-4382-4ec5-abb7-9ed785ead949)

**Comment by stuartmorgan** [comment]
@Auramel Please do not post pictures of text; they are much harder to read, and they aren't searchable.

It's also not clear to me how that is related to this issue. It's not the same error, and it's not even from a Flutter-team-provided plugin. Does this mean you no longer have an issue with `webkit_flutter`?

**Comment by MasonKomo** [comment]
> > i've resolve usinng this podfile configuration
> > ```
> > post_install do |installer|
> >   installer.pods_project.targets.each do |target|
> >     flutter_additional_ios_build_settings(target)
> > 
> >     # shim for CocoaPods issue, should remove when 1.13.0 is released
> >     # more info: https://github.com/CocoaPods/CocoaPods/issues/12012#issuecomment-1659803356
> >     target.build_configurations.each do |config|
> >       xcconfig_path = config.base_configuration_reference.real_path
> >       xcconfig = File.read(xcconfig_path)
> >       xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
> >       File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
> >     end
> >   end
> > end
> > ```
> 
> With this, I got : Error (Xcode): SDK does not contain 'libarclite' at the path '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphonesimulator.a'; try increasing the minimum deployment target

were you able to resolve this? I updated my podfile and am getting the same error that you mentioned.

**Comment by Mortando** [comment]
Issue is still open.

Upgraded Cocoapods to v1.13.0 and the fix mentioned above is not needed anymore.

Then with pod install there is the error 'Flutter/Flutter.h' file not found on all pods.

Below is Podfile:

`# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  #target 'RunnerTests' do
  #  inherit! :search_paths
  #end
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
         end
    end
  end
end
`

**Comment by TiluWeb** [comment]
Solution:
Delete Xcode 15.
Download Xcode 14.3 : https://developer.apple.com/download/all/?q=Xcode%2014 & its command tools.

**Comment by eyesoffish** [comment]
我调整build phases 配置顺序解决了“'Flutter/Flutter.h' file not found”<img width="858" alt="image" src="https://github.com/flutter/flutter/assets/18106623/ef1cd83e-65fa-4e26-a740-a901595ebf88">

调整后：
```
buildPhases = (
		87B419743B513AB9E3637B1D /* [CP] Check Pods Manifest.lock */,
		9740EEB61CF901F6004384FC /* Run Script */,
		97C146EA1CF9000F007C117D /* Sources */,
		97C146EB1CF9000F007C117D /* Frameworks */,
		97C146EC1CF9000F007C117D /* Resources */,
		9705A1C41CF9048500538489 /* Embed Frameworks */,
		E583813125B0628A003E7508 /* Embed Watch Content */,
		35565F8214D07D71E5076AFE /* [CP] Embed Pods Frameworks */,
		89FFCF69F1320183F0FA1830 /* [CP] Copy Pods Resources */,
		3B06AD1E1E4923F5004D2608 /* Thin Binary */,
	);
```
