### ISSUE TITLE
`SizedBox` with zero size throws `Failed assertion: ... 'width > 0.0': is not true`, Proposal to improve error message if `SizedBox` has zero size

### ISSUE THREAD

**Issue by bramp** [flutter/flutter#135082]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Write the following
  ```dart
    const Row(
        children: [
          FittedBox(
            child: SizedBox(
              height: 0,
              width: 0,
            ),
          ),
        ],
      ),
```

2. Run

### Expected results

Nothing to be displayed as the widget is effectively zero sized.

### Actual results

```
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/box.dart': Failed assertion: line 320 pos 12: 'width > 0.0': is not true.
box.dart:320

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml
```

If I change the SizedBox to have a non-zero size, or take the FittedBox out of the Row, then the assertion goes away. I'm only filing this to improve the error message / handling of zero width elements.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const Row(
        children: [
          FittedBox(
            child: SizedBox(
              height: 0,
              width: 0,
            ),
          ),
        ],
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
❯ flutter doctor -v
[✓] Flutter (Channel stable, 3.13.4, on macOS 13.5.2 22G91 darwin-arm64, locale en-GB)
    • Flutter version 3.13.4 on channel stable at /opt/homebrew/Caskroom/flutter/3.13.2/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 367f9ea16b (7 days ago), 2023-09-12 23:27:53 -0500
    • Engine revision 9064459a8b
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/bramp/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.73.20230904

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 14 (API 34) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.5.2 22G91 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 116.0.5845.187

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report. The error occurs due to the fact that the `width` and `height` values are 0. If we provide non-zero values, then the error goes away.

The use case is if we provide 0 values then it throws: `Failed assertion: line 320 pos 12: 'width > 0.0': is not true.` as expected, but OP is proposing to have an improved error message.

Treating the issue as applicable and labeling for team's attention.

**Comment by saifr383** [comment]
@darshankawar  i am new to contribution can i do this change?

**Comment by AbhishekDoshi26** [comment]
@darshankawar based on my initial research, this issue is not of SizedBox. This issue only happens when the SizedBox is wrapped with FittedBox.

FittedBox is a widget that tries to size and position its child within the available space while maintaining the child's aspect ratio (kind of similar to ConstrainedBox). When you set the width and height of the SizedBox child to zero, you are essentially telling Flutter to render a child with zero dimensions, which is causing the error.

We need to change the assert message which is present [here](https://github.com/flutter/flutter/blob/74c6693170e184807428683ebcb893b1717d2ecf/packages/flutter/lib/src/rendering/box.dart#L320).

**Comment by rekire** [comment]
@AbhishekDoshi26 this is just the case when the view is in a `Row` widget, when it is in a `Column` like in my linked ticket above it should be [the line](https://github.com/flutter/flutter/blob/74c6693170e184807428683ebcb893b1717d2ecf/packages/flutter/lib/src/rendering/box.dart#L321) below.

I could also imagine the case that it is in a `Stack` where both constrains could be broken and it should be fine.

**Comment by Passer-by** [comment]
```
@override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        child: FittedBox(
          child:Text(''),
        ),
      ),
    );
  }
```
The same issue persists in this code.

**Comment by PurplePolyhedron** [comment]
To improve the error message, would it be the correct for a `FittedBox` to throw if the child has a size of zero？
Currently if the constraints of `FittedBox` is tight, and `fit` is not `BoxFit.scaleDown`, there is no error for having a child of size 0. In this case throwing would be a breaking change.

Or should `FittedBox` be skipping child of size 0 and not throw an error?
