### ISSUE TITLE
[Impeller] Vulkan Validation errors present due to Swapchain

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#135086]
@bdero reported p90 raster time [went up ~40%](https://flutter-flutter-perf.skia.org/e/?keys=X6e24ec889a2e7028e3ad6707748dc5b2&selected=commit%3D36896%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DPixel_7_Pro%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253D90th_percentile_frame_rasterizer_time_millis%252Ctest%253Danimated_advanced_blend_perf__timeline_summary%252C&xbaroffset=36896) for `animated_advanced_blend_perf__timeline_summary`:

> Roll: https://github.com/flutter/engine/compare/490925676b91...8c2203bb6c3b
>
> The only item of interest I see is https://github.com/flutter/engine/pull/45654? FYI @matanlurey

@jonahwilliams and I looked at this using a Pixel 7/Pixel Fold with similar performance specs, and we were able to confirm that there was a drop in performance - not expected however. Jonah also immediately pointed out some possible root causes:

> This benchmark is definitely stressing the phone, it would be interesting to see what the profile of this shows? Is the resetting happening on the wrong thread, or are we resetting too often, or is it a threading issue?
>
> Something unique about this app is that the frames are really expensive, so the fence waiter will fire much much later than you might expect

We were able to debunk that we're needlessly creating too _many_ command pools:

```diff
auto [result, pool] = device.createCommandPoolUnique(info);
if (result != vk::Result::eSuccess) {
  return std::nullopt;
}
+FML_LOG(ERROR) << "Creating new command pool";
```

And was able to confirm the errors are because of resetting on a background thread:

```cc
static bool kResetOnBackgroundThread = false;

...

auto reset_pool = BackgroundCommandPoolVK(
    std::move(pool_), std::move(collected_buffers_), recycler);
if (kResetOnBackgroundThread) {
  UniqueResourceVKT<BackgroundCommandPoolVK> pool(
      context->GetResourceManager(), std::move(reset_pool));
}
```

After using the "Draw Vertices" benchmark, we now suspect it's due to driver/validation errors:

```txt
E/flutter (13448): --- Vulkan Debug Report  ----------------------------------------
E/flutter (13448): |                Severity: Error
E/flutter (13448): |                    Type: { Validation }
E/flutter (13448): |                 ID Name: UNASSIGNED-Threading-MultipleThreads
E/flutter (13448): |               ID Number: 337425955
E/flutter (13448): |       Queue Breadcrumbs: [NONE]
E/flutter (13448): |  CMD Buffer Breadcrumbs: [NONE]
E/flutter (13448): |         Related Objects: CommandPool [405719790649713] [UNNAMED]
E/flutter (13448): |                 Trigger: Validation Error: [ UNASSIGNED-Threading-MultipleThreads ] Object 0: handle = 0x1710000000171, type = VK_OBJECT_TYPE_COMMAND_POOL; | MessageID = 0x141cb623 | THREADING ERROR : vkAllocateCommandBuffers(): object of type VkCommandPool is simultaneously used in thread 520790568112 and thread 521429589168
E/flutter (13448): -----------------------------------------------------------------
```

The root cause appears to be the [final command buffer we create for a frame](https://github.com/flutter/engine/blob/5a924a9017d764bc5c08d21a76f6ab52bba3a6f1/impeller/renderer/backend/vulkan/swapchain_impl_vk.cc#L432-L434), which is _untracked_ (in other words, the Swapchain-created buffer calls submit directly, so the tracked objects are just dropped at the end of the method.

**Comment by matanlurey** [comment]
Last update for tonight. @jonahwilliams had a proposed patch:

```patch
diff --git a/impeller/renderer/backend/vulkan/surface_context_vk.cc b/impeller/renderer/backend/vulkan/surface_context_vk.cc
index 2e20d2af5c..88150f5ba7 100644
--- a/impeller/renderer/backend/vulkan/surface_context_vk.cc
+++ b/impeller/renderer/backend/vulkan/surface_context_vk.cc
@@ -80,7 +80,6 @@ std::unique_ptr<Surface> SurfaceContextVK::AcquireNextSurface() {
   if (auto allocator = parent_->GetResourceAllocator()) {
     allocator->DidAcquireSurfaceFrame();
   }
-  parent_->GetCommandPoolRecycler()->Dispose();
   return surface;
 }
 
diff --git a/impeller/renderer/backend/vulkan/swapchain_impl_vk.cc b/impeller/renderer/backend/vulkan/swapchain_impl_vk.cc
index d9146d9056..7ccabc5872 100644
--- a/impeller/renderer/backend/vulkan/swapchain_impl_vk.cc
+++ b/impeller/renderer/backend/vulkan/swapchain_impl_vk.cc
@@ -9,6 +9,7 @@
 #include "impeller/renderer/backend/vulkan/context_vk.h"
 #include "impeller/renderer/backend/vulkan/formats_vk.h"
 #include "impeller/renderer/backend/vulkan/surface_vk.h"
+#include "impeller/renderer/backend/vulkan/fence_waiter_vk.h"
 #include "impeller/renderer/backend/vulkan/swapchain_image_vk.h"
 #include "vulkan/vulkan_structs.hpp"
 
@@ -428,6 +429,8 @@ bool SwapchainImplVK::Present(const std::shared_ptr<SwapchainImageVK>& image,
   if (!sync->final_cmd_buffer) {
     return false;
   }
+  // Increment the frame before creating the next buffer, at is it untracked.
+  context.GetCommandPoolRecycler()->Dispose();
 
   auto vk_final_cmd_buffer = CommandBufferVK::Cast(*sync->final_cmd_buffer)
                                  .GetEncoder()
~
```

It did drastically reduce the amount of validation errors, and is possibly worth landing as-is.

That being said, I continue to see some errors, typically after backing out of a benchmark app.

Sometimes there is also a hard crash in the validation layers:

```txt
Abort message: '../../third_party/vulkan-deps/vulkan-validation-layers/src/layers/state_tracker/image_state.cpp:576: void SWAPCHAIN_NODE::PresentImage(uint32_t, uint64_t): assertion "acquired_images > 0"
```

We did also consider using a _second_ fence for the last frame. @jonahwilliams:

> I think two fences might be the most straightforward, assuming that we can attach more than one fence to a cmd buffer submission
>
> We could also create a dummy empty cmd buffer and submit it and just capture both cmd buffers

**Comment by jonahwilliams** [comment]
I wonder if we could actually hold the tracked objects in the same swapchain structure, and then release it when we block on the fence to acquire the swapchain.

**Comment by jonahwilliams** [comment]
Landed a work around and this no longer seems to happen for me, though it may be a lurking issue still.

**Comment by jonahwilliams** [comment]
Actually this is still happening :(

**Comment by matanlurey** [comment]
On every frame or on back button (I was seeing the latter)?

**Comment by jonahwilliams** [comment]
forward/back, less frequently on animated advanced blend. vertices seems fixed

**Comment by matanlurey** [comment]
Cool. I'm free all day in the afternoon - open to pair or I can try to track down other root causes with some print debugging
