### ISSUE TITLE
PageView API doc sample fails on Desktop and Web

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#135188]
The [PageView API doc sample](https://api.flutter.dev/flutter/widgets/PageView-class.html) fails - doesn't respond to the mouse -  on Desktop and Web but not on the iPhone emulator.  I've only tested on macOS.

**Comment by bleroux** [comment]
As someone who often run Flutter apps on desktop, I'm used to make the required change which is to configure `MaterialApp.scrollBehavior` :

<details><summary>Updated doc sample with scrollBehavior</summary>

```dart
import 'dart:ui';

import 'package:flutter/material.dart';

/// Flutter code sample for [PageView].

void main() => runApp(const PageViewExampleApp());

class PageViewExampleApp extends StatelessWidget {
  const PageViewExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      // Custom scroll behavior to activate drag gestures on Desktop and Web.
      // See https://docs.flutter.dev/release/breaking-changes/default-scroll-behavior-drag
      scrollBehavior: MyCustomScrollBehavior(),
      home: Scaffold(
        appBar: AppBar(title: const Text('PageView Sample')),
        body: const PageViewExample(),
      ),
    );
  }
}

class MyCustomScrollBehavior extends MaterialScrollBehavior {
  @override
  Set<PointerDeviceKind> get dragDevices => {
    PointerDeviceKind.touch,
    PointerDeviceKind.mouse,
  };
}

class PageViewExample extends StatelessWidget {
  const PageViewExample({super.key});

  @override
  Widget build(BuildContext context) {
    final PageController controller = PageController();
    return PageView(
      /// [PageView.scrollDirection] defaults to [Axis.horizontal].
      /// Use [Axis.vertical] to scroll vertically.
      controller: controller,
      children: const <Widget>[
        Center(
          child: Text('First Page'),
        ),
        Center(
          child: Text('Second Page'),
        ),
        Center(
          child: Text('Third Page'),
        ),
      ],
    );
  }
}

```

</details> 

This is related to a change, https://github.com/flutter/flutter/pull/81569, introduced in Flutter 2.5, and documented in https://docs.flutter.dev/release/breaking-changes/default-scroll-behavior-drag.

I'm not sure how we can proceed to update the doc samples. Maybe we should try to spot which code samples are impacted and make changes similar to the updated code sample I pasted above.

**Comment by HansMuller** [comment]
CC @jonahwilliams @Piinks 

@bleroux - thanks for the explanation!

I assume that the default behavior that #81569 was trying to overcome was desktop scrolling a typical ListView with scrollbars, but not the horizontal scrolling in a (no scrollbars) PageView. We should modify our examples (and test them) so that they work as expected in DartPad. I think it would be better to apply the custom scroll behavior to the PageView itself:

```dart
import 'dart:ui';

class MyCustomScrollBehavior extends MaterialScrollBehavior {
  @override
  Set<PointerDeviceKind> get dragDevices => {
    PointerDeviceKind.touch,
    PointerDeviceKind.mouse,
  };
}

PageView(
  // Custom scroll behavior to activate drag gestures on Desktop and Web.
  // See https://docs.flutter.dev/release/breaking-changes/default-scroll-behavior-drag
  scrollBehavior: MyCustomScrollBehavior(),
  ...
)
```

However maybe we should provide a `MaterialScrollBehavior.mouseIsTouch` constant (maybe with a better name). What do you-all think?

Note also: TabBar, which is based on PageView has the same problem although - IMHO - desktop users are unlikely to find the DartPad TabBar example confusing since you can mouse on the tabs. For the sake of consistency perhaps TabBar should get a scrollBehavior parameter  though.

**Comment by Piinks** [comment]
I don't think we should make the samples enable mouse dragging. They should demonstrate best practices and real use cases. On desktop in this case, it is typical for either left/right arrow buttons on the sides of the PageView to change the page, or indicator dots at the bottom of the PageView to indicate and navigate to other pages.

There was a recent PR that tried to add mouse dragging like this in favor and it was rejected for these reasons.

Maybe we should add these navigation options to the PageView so they are readily available on desktop?

**Comment by HansMuller** [comment]
Adding forward/backward buttons would make sense for the DartPad TabBar sample; SGTM

**Comment by HansMuller** [comment]
The RefreshIndicator examples have a similar problem, see https://github.com/flutter/flutter/issues/135510

**Comment by huycozy** [comment]
I'm happy to work on this, may I take it? I built a demo based on the ideas above. The updated sample is quite simple integrating [TabPageSelector](https://api.flutter.dev/flutter/material/TabPageSelector-class.html) as an indicator for PageView along with forward/backward buttons.

On mobile platforms, let's keep it as is (no indicator). Let me know if you find this demo appropriate.

Demo with mouse clicks on buttons and trackpad gestures (swipe left/right):

https://github.com/flutter/flutter/assets/104349824/0f9c60bd-8b18-404e-b5b6-1d594604de31

**Comment by HansMuller** [comment]
That looks like a much better version of the demo for users burdened with a mouse :-).  I hope you'll contribute a PR!

**Comment by huycozy** [comment]
Thank @bleroux for assigning this to me :)

@HansMuller I just pushed a PR, could you please take a look?
