### ISSUE TITLE
Tooltips cover the page on the codelab

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#13513]
When visiting https://codelabs.developers.google.com/codelabs/flutter/#0, if you put your mouse cursor ANYWHERE, it pops up a tooltip. The tooltip should be confined to the title, not the entire page.

It makes it hard to read the document because it gets in the way no matter where you put your cursor.

**Comment by gspencergoog** [comment]
FYI, this was on Chrome Linux: Version 63.0.3239.84 (Official Build) (64-bit)

**Comment by Sfshaza** [comment]
I see what you mean, @gspencergoog. I created an [internal bug](https://buganizer.corp.google.com/issues/111745213) against the codelabs plugin.

Closing.
