### ISSUE TITLE
[go_router]Possible bug in how to implement screen a -> screen b -> screen c .

### ISSUE THREAD

**Issue by patrikheinonen** [flutter/flutter#135135]
### Is there an existing issue for this?

- [X] I have searched the [existing package issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Apackage)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### What package does this bug report belong to?

go_router

### What target platforms are you seeing this bug on?

Web

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
[Paste file content here]
```

</details>

### Steps to reproduce

/ -> Navigate to login -> navigate to otp -> try to navigate all the way back to / with browser back button.

### Expected results

Back button of broswer should be working correctly.

See video.

### Actual results

Back button of broswer is not working.

See video

### Code sample

<details><summary>Code sample</summary>

https://pastebin.com/rFv6A71H

</details>

### Screenshots or Videos

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

https://github.com/flutter/flutter/assets/36403567/e006a518-f4d5-447b-826f-b5915403f143

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by patrikheinonen** [comment]
If anyone has any idea how to implement this flow in such a way that it works in both mobile and web that would be very much appreciated. Curently it only works correctly on mobile.

**Comment by darshankawar** [comment]
@patrikheinonen 
The pastebin link you provided isn't opening for me.

Also, take a look at [this](https://github.com/flutter/flutter/issues/116440) issue with underlying comments and see if it helps in your case or not.

**Comment by darshankawar** [comment]
Thanks for the update @patrikheinonen 
I am wondering how is this different from the one you filed https://github.com/flutter/flutter/issues/135018 which also seems to work without using queryParams, so most likely the root-cause seems to be the same.
