### ISSUE TITLE
sky_snapshot should probably be updated to also support the .packages file

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#1351]
sky_snapshot currently takes a `--package-root`; it should probably also support `.packages` files. The VM uses the `--packages` flag for this.

```
--packages=<path>
  Where to find a package spec file.
```

**Comment by abarth** [comment]
Yes.  I wonder if we should replace `sky_snapshot` with `gen_snapshot`.  That binary already supports `.packages` files.

**Comment by Hixie** [comment]
See also #60.

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/engine/search?utf8=%E2%9C%93&q=CanonicalizePackageURL&type=Code
should find the relevant functions needing modification.

**Comment by abarth** [comment]
Fixed.  We now use `.packages`
