### ISSUE TITLE
Add `abiFilters` to android gradle templates to prevent serving on x86 devices

### ISSUE THREAD

**Issue by gmackall** [flutter/flutter#135173]
Original comment by @chinmaygarde 

>There are no x86 AOT builds supported by Flutter. To disable the application being served on devices those device, the abiFilters directive must be used to only specify the variants Flutter supports. 

We should look in to adding such a validation check ~to the Flutter tools.~

Context: https://github.com/flutter/flutter/issues/83596#issuecomment-852526806

Edited based on comment from @christopherfujino, this should actually be done by adding `abiFilters` to our gradle templates: https://developer.android.com/ndk/guides/abis#gc

**Comment by christopherfujino** [comment]
@gmackall abiFilters is a gradle property, right?

https://developer.android.com/ndk/guides/abis#gc

I'm guessing we would add this to our templates?

**Comment by gmackall** [comment]
> @gmackall abiFilters is a gradle property, right?
> 
> https://developer.android.com/ndk/guides/abis#gc
> 
> I'm guessing we would add this to our templates?

I was not aware that it was a gradle property when I made the issue, but that looks correct to me! I'll edit to reflect that. Also sorry, should have added team-android regardless!

**Comment by christopherfujino** [comment]
> > @gmackall abiFilters is a gradle property, right?
> > https://developer.android.com/ndk/guides/abis#gc
> > I'm guessing we would add this to our templates?
> 
> I was not aware that it was a gradle property when I made the issue, but that looks correct to me! I'll edit to reflect that. Also sorry, should have added team-android regardless!

It's all good. We now have equal knowledge about abiFilters :)

**Comment by gmackall** [comment]
It looks like the tool is actually already doing this? 
https://cs.opensource.google/flutter/flutter/+/master:packages/flutter_tools/lib/src/commands/build_appbundle.dart?q=appbundle&ss=flutter
I tried uploading the counter app to the play store, and in the play console app bundle explorer it shows:
```
Native platforms    arm64-v8a, armeabi-v7a, x86_64
```
Which makes me think that there is something more going on in https://github.com/flutter/flutter/issues/83596 than just people mistakenly building for x86

**Comment by gmackall** [comment]
Unclear why all the filepaths would include x86 though
