### ISSUE TITLE
[flutter_tooling] Refactor `EdgeInsets.all()` & `EdgeInsets.symmetric()` to `EdgeInsets.only()` & `EdgeInsets.symmetric()`

### ISSUE THREAD

**Issue by dickermoshe** [flutter/flutter#135156]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

While programming it is very common that users will create a padding in all direction, and then later decide that in one direction it should be different. You then need to manually change `all` to `only` and manually fill in `top`, `bottom`, `left`, `right`.
The refactor tooling that adds a padding automatically uses `EdgeInsets.all()` by default, so this is very common.

https://github.com/flutter/flutter/assets/75931499/00cf5c2e-6e99-4c43-870b-ea40bcc71f41

### Proposal

A refactor option built into the flutter tooling that would provide the options to refactor:

- EdgeInsets.all()

to

- EdgeInsets.only()
- EdgeInsets.symmetric()

&

- EdgeInsets.symmetric()

to

- EdgeInsets.only()

**Comment by darshankawar** [comment]
Thanks for the report @dickermoshe 
If I understand correctly, you are trying to propose options to refactor for the IDE plugin right that currently gives you the options to add widgets as you showed in the video ?

**Comment by dickermoshe** [comment]
@darshankawar 
Yes. Something like this
![Screensho 115529 (0-00-00-00)](https://github.com/flutter/flutter/assets/75931499/50ea6e60-406f-42f7-a1f8-dab9504ef52d)

**Comment by darshankawar** [comment]
This I think would probably need to be filed in https://github.com/flutter/flutter-intellij/issues
Closing from here.
