### ISSUE TITLE
[camera] Crash on launch on iOS: `Symbol not found: _OBJC_CLASS_$_NSError`

### ISSUE THREAD

**Issue by zanohikaru7** [flutter/flutter#135195]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

My XCode updated to the latest version for iOS 17 SDK, and then suddenly my app crashed upon opening

This app/library was working before the update of XCode and iOS 17 here are the error logs:

```
Launching lib/main_staging.dart on Psalm’s iPhone in debug mode...
main_staging.dart:1
Automatically signing iOS for device deployment using specified development team in Xcode project: U5CD6V7ZFZ
Upgrading Pods-Runner.profile.xcconfig
Upgrading Pods-Runner.debug.xcconfig
Xcode build done.                                           19.3s
(lldb) dyld[871]: Symbol not found: _OBJC_CLASS_$_NSError
  Referenced from: <5FAED927-C1FA-31BF-A4D3-B57AC2CE16B2> /private/var/containers/Bundle/Application/7E5E166F-A777-4BEE-B2C8-6032A33F0D4E/Runner.app/Runner
  Expected in:     <AAB63F35-5584-3755-89EC-E23FA0040514> /private/var/containers/Bundle/Application/7E5E166F-A777-4BEE-B2C8-6032A33F0D4E/Runner.app/Frameworks/camera_avfoundation.framework/camera_avfoundation
* thread #1, stop reason = signal SIGABRT
    frame #0: 0x00000001da393fcc dyld`__abort_with_payload + 8
dyld`:
->  0x1da393fcc <+8>:  b.lo   0x1da393fec               ; <+40>
    0x1da393fd0 <+12>: pacibsp
    0x1da393fd4 <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1da393fd8 <+20>: mov    x29, sp
Target 0: (Runner) stopped.
Error launching application on Psalm’s iPhone.
Exited
```

### Expected results

Expecting to work after the updates from XCode

### Actual results

The App is crashing and referring to the camera_avfoundation library which is used as a dependency in this library

### Code sample

<details><summary>Code sample</summary>

```dart
availableCameras().then((cameras) {
      _cameraController = CameraController(cameras.first, ResolutionPreset.max);

      _cameraController.initialize().then((_) {
        if (!mounted) {
          return;
        }

        setState(() {
          _isInitialized = true;
        });
      });
    }).catchError((Object e) {
      if (e is CameraException) {
        switch (e.code) {
          case 'CameraAccessDenied':
            // Handle access errors here.
            break;
          default:
            // Handle other errors here.
            break;
        }
      }
    });
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/flutter/flutter/assets/30557803/44d12ef2-9bbd-498f-bf67-9d53b4a72aa4)

</details>

### Logs

<details><summary>Logs</summary>

```console
Launching lib/main_staging.dart on Psalm’s iPhone in debug mode...
main_staging.dart:1
Automatically signing iOS for device deployment using specified development team in Xcode project: U5CD6V7ZFZ
Upgrading Pods-Runner.release.xcconfig
Upgrading Pods-Runner.profile.xcconfig
Upgrading Pods-Runner.debug.xcconfig
Xcode build done.                                           19.3s
(lldb) dyld[871]: Symbol not found: _OBJC_CLASS_$_NSError
  Referenced from: <5FAED927-C1FA-31BF-A4D3-B57AC2CE16B2> /private/var/containers/Bundle/Application/7E5E166F-A777-4BEE-B2C8-6032A33F0D4E/Runner.app/Runner
  Expected in:     <AAB63F35-5584-3755-89EC-E23FA0040514> /private/var/containers/Bundle/Application/7E5E166F-A777-4BEE-B2C8-6032A33F0D4E/Runner.app/Frameworks/camera_avfoundation.framework/camera_avfoundation
* thread #1, stop reason = signal SIGABRT
    frame #0: 0x00000001da393fcc dyld`__abort_with_payload + 8
dyld`:
->  0x1da393fcc <+8>:  b.lo   0x1da393fec               ; <+40>
    0x1da393fd0 <+12>: pacibsp
    0x1da393fd4 <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1da393fd8 <+20>: mov    x29, sp
Target 0: (Runner) stopped.
Error launching application on Psalm’s iPhone.
Exited
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.4, on macOS 13.5.2 22G91 darwin-arm64, locale en-PH)
    • Flutter version 3.13.4 on channel stable at /Users/psalmlimpin/Documents/Projects/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 367f9ea16b (8 days ago), 2023-09-12 23:27:53 -0500
    • Engine revision 9064459a8b
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/psalmlimpin/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.12.1

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (2 available)
    • Psalm’s iPhone (mobile) • 00008120-000C24A62107C01E • ios          • iOS 16.6.1 20G81
    • macOS (desktop)         • macos                     • darwin-arm64 • macOS 13.5.2 22G91 darwin-arm64

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by danagbemava-nc** [comment]
Hi @zanohikaru7, I just ran the camera sample app a few times on iOS 17, and in all cases, the app run just fine. 

Can you try with a new project to see if reproduces there as well?

**Comment by zanohikaru7** [comment]
> Hi @zanohikaru7, I just ran the camera sample app a few times on iOS 17, and in all cases, the app ran just fine.
> 
> Can you try with a new project to see if reproduces there as well?

Hello Thanks for replying, I already tried the library in the newly created Flutter project, and it's working:

But in my existing project, I tried to remove the library from it and it's working, but when I turn it back the issue occurs again

In an Android phone, there's no problem, the camera is working fine

**Comment by zanohikaru7** [comment]
I also try to down all the pages using the Camera Library, but still, it's not working, so it's not a code level.

But when I tried to uninstall the library, the app was working.

So my suspect here is there's a conflict with the other libraries I'm using. Here are the libraries I'm using:


  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.17
  go_router: ^6.0.3
  flutter_riverpod: ^2.1.3
  riverpod: ^2.1.3
  riverpod_annotation: ^1.1.1
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  rxdart: ^0.27.7
  #camera: ^0.10.5+4
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  custom_qr_generator: ^0.1.2
  google_fonts: ^4.0.3
  flutter_svg: ^1.1.6
  shimmer: ^2.0.0
  intl: ^0.17.0
  otp_text_field: ^1.1.3
  device_info_plus: ^8.0.0
  package_info_plus: ^4.0.1
  image: ^3.3.0
  signature: ^5.3.0
  barcode: ^2.2.3
  path_provider: ^2.0.12
  google_maps_flutter: ^2.2.8
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  flutter_polyline_points: ^1.0.0
  flutter_dotenv: ^5.0.2
  permission_handler: ^10.2.0
  webview_flutter: ^3.0.1
  dropdown_search: ^5.0.6

**Comment by lfarmer** [comment]
I'm experiencing issues with iOS 17 also,  Could be mistaken but seems camera_avfoundation `platform = :ios, '11.0'` which is no longer supported within Xcode 15 - https://developer.apple.com/support/xcode/

**Comment by zanohikaru7** [comment]
> I'm experiencing issues with iOS 17 also, Could be mistaken but seems camera_avfoundation `platform = :ios, '11.0'` which is no longer supported within Xcode 15 - https://developer.apple.com/support/xcode/

what did you do to make it work? or should we wait for the author to the library?

**Comment by lfarmer** [comment]
Haven't been able to yet,  my search for the solution led me here :)

**Comment by zanohikaru7** [comment]
Thanks bro, hope this will be solved in the next release, it's too tiring to switch to another library. I have a lot of features depending on this library.

**Comment by danagbemava-nc** [comment]
Hi @zanohikaru7, can you share your `Podfile` & `Podfile.lock`?

**Comment by zanohikaru7** [comment]
Here:

# Uncomment this line to define a global platform for your project
# platform :ios, '11.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

**Comment by zanohikaru7** [comment]
> Hi @zanohikaru7, can you share your `Podfile` & `Podfile.lock`?

```
# Uncomment this line to define a global platform for your project
# platform :ios, '11.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```

**Comment by zanohikaru7** [comment]
PODS:
  - device_info_plus (0.0.1):
    - Flutter
  - Flutter (1.0.0)
  - geocoding_ios (1.0.5):
    - Flutter
  - geolocator_apple (1.2.0):
    - Flutter
  - google_maps_flutter_ios (0.0.1):
    - Flutter
    - GoogleMaps
  - GoogleMaps (5.2.0):
    - GoogleMaps/Maps (= 5.2.0)
  - GoogleMaps/Base (5.2.0)
  - GoogleMaps/Maps (5.2.0):
    - GoogleMaps/Base
  - image_picker_ios (0.0.1):
    - Flutter
  - MTBBarcodeScanner (5.0.11)
  - package_info_plus (0.4.5):
    - Flutter
  - path_provider_foundation (0.0.1):
    - Flutter
    - FlutterMacOS
  - permission_handler_apple (9.1.1):
    - Flutter
  - qr_code_scanner (0.2.0):
    - Flutter
    - MTBBarcodeScanner
  - shared_preferences_foundation (0.0.1):
    - Flutter
    - FlutterMacOS
  - webview_flutter_wkwebview (0.0.1):
    - Flutter

DEPENDENCIES:
  - device_info_plus (from `.symlinks/plugins/device_info_plus/ios`)
  - Flutter (from `Flutter`)
  - geocoding_ios (from `.symlinks/plugins/geocoding_ios/ios`)
  - geolocator_apple (from `.symlinks/plugins/geolocator_apple/ios`)
  - google_maps_flutter_ios (from `.symlinks/plugins/google_maps_flutter_ios/ios`)
  - image_picker_ios (from `.symlinks/plugins/image_picker_ios/ios`)
  - package_info_plus (from `.symlinks/plugins/package_info_plus/ios`)
  - path_provider_foundation (from `.symlinks/plugins/path_provider_foundation/darwin`)
  - permission_handler_apple (from `.symlinks/plugins/permission_handler_apple/ios`)
  - qr_code_scanner (from `.symlinks/plugins/qr_code_scanner/ios`)
  - shared_preferences_foundation (from `.symlinks/plugins/shared_preferences_foundation/darwin`)
  - webview_flutter_wkwebview (from `.symlinks/plugins/webview_flutter_wkwebview/ios`)

SPEC REPOS:
  trunk:
    - GoogleMaps
    - MTBBarcodeScanner

EXTERNAL SOURCES:
  device_info_plus:
    :path: ".symlinks/plugins/device_info_plus/ios"
  Flutter:
    :path: Flutter
  geocoding_ios:
    :path: ".symlinks/plugins/geocoding_ios/ios"
  geolocator_apple:
    :path: ".symlinks/plugins/geolocator_apple/ios"
  google_maps_flutter_ios:
    :path: ".symlinks/plugins/google_maps_flutter_ios/ios"
  image_picker_ios:
    :path: ".symlinks/plugins/image_picker_ios/ios"
  package_info_plus:
    :path: ".symlinks/plugins/package_info_plus/ios"
  path_provider_foundation:
    :path: ".symlinks/plugins/path_provider_foundation/darwin"
  permission_handler_apple:
    :path: ".symlinks/plugins/permission_handler_apple/ios"
  qr_code_scanner:
    :path: ".symlinks/plugins/qr_code_scanner/ios"
  shared_preferences_foundation:
    :path: ".symlinks/plugins/shared_preferences_foundation/darwin"
  webview_flutter_wkwebview:
    :path: ".symlinks/plugins/webview_flutter_wkwebview/ios"

SPEC CHECKSUMS:
  device_info_plus: e5c5da33f982a436e103237c0c85f9031142abed
  Flutter: f04841e97a9d0b0a8025694d0796dd46242b2854
  geocoding_ios: a389ea40f6f548de6e63006a2e31bf66ff80769a
  geolocator_apple: cc556e6844d508c95df1e87e3ea6fa4e58c50401
  google_maps_flutter_ios: 66201f392bf62d500f07670a30488a247b9bb5b9
  GoogleMaps: 025272d5876d3b32604e5c080dc25eaf68764693
  image_picker_ios: 4a8aadfbb6dc30ad5141a2ce3832af9214a705b5
  MTBBarcodeScanner: f453b33c4b7dfe545d8c6484ed744d55671788cb
  package_info_plus: fd030dabf36271f146f1f3beacd48f564b0f17f7
  path_provider_foundation: 37748e03f12783f9de2cb2c4eadfaa25fe6d4852
  permission_handler_apple: e76247795d700c14ea09e3a2d8855d41ee80a2e6
  qr_code_scanner: bb67d64904c3b9658ada8c402e8b4d406d5d796e
  shared_preferences_foundation: 297b3ebca31b34ec92be11acd7fb0ba932c822ca
  webview_flutter_wkwebview: b7e70ef1ddded7e69c796c7390ee74180182971f

PODFILE CHECKSUM: ef19549a9bc3046e7bb7d2fab4d021637c0c58a3

COCOAPODS: 1.12.1

**Comment by danagbemava-nc** [comment]
Hi @lfarmer, thanks for the details. Please provide the full output of `flutter run -v`. The output may be huge so kindly put it into a .txt/.log file and attach it here. 

Thank you

**Comment by lfarmer** [comment]
Hi @danagbemava-nc ,  Have just started my Mac back up and it seems that Apple has updated something as was asked to allow Xcode update to run on start up.   

After doing this and building the app again the issue has disappeared??

**Comment by aithrajbouty** [comment]
hello, I'm currently experiencing the same issue on my flutter project. Weird thing is everything works fine with my other project that has camera plugin. I am getting the same error when running my app in real device and iOS simulators (can run on android).

**Comment by caseymdk** [comment]
Just adding I'm seeing the same issue on my app, iOS 17.0, getting immediate crash and:

```
dyld[554]: Symbol not found: _OBJC_CLASS_$_NSError
  Referenced from: <48CE0BEE-56D1-3DD7-9B8D-CA9504B772A4> /private/var/containers/Bundle/Application/E6C8F1A7-0798-4779-ABC4-E352D52B6A92/Runner.app/Runner
  Expected in:     <FEDD546D-EE5F-3DCE-A146-4EC2A3317776> /private/var/containers/Bundle/Application/E6C8F1A7-0798-4779-ABC4-E352D52B6A92/Runner.app/Frameworks/camera_avfoundation.framework/camera_avfoundation
```

Haven't seemed to get any xcode update that's fixed it yet. Removing the camera plugin and the issue goes away.

camera 0.10.5+4
iPhone 12 Mini 17.0
Flutter 3.13.5
camera_avfoundation 0.9.13+5

**Comment by zanohikaru7** [comment]
> That is interesting. @zanohikaru7, did you also get a notice like [#135195 (comment)](https://github.com/flutter/flutter/issues/135195#issuecomment-1733143126)?
> 
> Can you also share the information requested in [#135195 (comment)](https://github.com/flutter/flutter/issues/135195#issuecomment-1732998651)?

Hello, I don't try to use my Mac Backup

But I tried to put all the Libraries used in my current project in the new project you said, then the issue occurred, then I debugged it by removing the libraries one by one to know which library causing the error, and then I found out that the issue occurs when combining with **google_maps_flutter**

I tried to update it to latest version ** google_maps_flutter: ^2.5.0 ** but still doesn't work on both **Newly Created Project** and my **Existing Project**

**Comment by caseymdk** [comment]
@zanohikaru7 I'm seeing the same, app boots alright if I remove my google_maps_flutter package. Putting it back in breaks things.

**Comment by danagbemava-nc** [comment]
Can anyone facing the issue please provide a complete minimal reproducible code sample (preferably in a repo that we can clone) so that we can investigate this issue? 

Thank you

**Comment by caseymdk** [comment]
@danagbemava-nc I put some here, it's just the `flutter create` code with google_maps_flutter and camera added into pubspec.yaml. https://github.com/caseymdk/flutter_camera_crash

I get a crash on app start after setting developer certificates and running `flutter run`. Please let me know if you're able to reproduce.

It's worth noting that adding google_maps_flutter as a dependency to https://github.com/flutter/plugins/tree/main/packages/camera/camera/example does **NOT** cause a crash for me.

Thank you!

macOS Ventura 13.6, Xcode 15.0
iPhone 12 Mini - iOS 17.0.2
Flutter 3.13.5

**Comment by quiless** [comment]
Hello! I get the same issue!

doctor -v 

    • Flutter version 3.13.6
    • Dart version 3.1.3
    • DevTools version 2.25.0
    • Xcode - develop for iOS and macOS (Xcode 15.0)
    • CocoaPods version 1.13.0
    • Flutter extension version 3.72.0
    • Device - Quiless (mobile) • iOS -  iOS 16.7 20H19  

I tried to build on device (Quiless) and simulator. 

(lldb) dyld[2505]: Symbol not found: _OBJC_CLASS_$_NSError
Referenced from: <A5537F53-A45C-313B-9B8E-08B049E9AB7B>
/private/var/containers/Bundle/Application/93AB90CD-500C-4F88-89DC-78F63CC8DED8/Runner.app/Runner
Expected in:     <55B618E0-1A0D-3E4E-9BCC-81FC1AB61A7D>
/private/var/containers/Bundle/Application/93AB90CD-500C-4F88-89DC-78F63CC8DED8/Runner.app/Frameworks/camera_avfoundation.framework/camera_a
vfoundation

**Comment by danagbemava-nc** [comment]
@caseymdk, thanks for the repro.

Reproducible using the code sample provided in https://github.com/flutter/flutter/issues/135195#issuecomment-1738646993. 

I initially could not reproduce the issue with just the `camera` dependencies. And with the sample provided by @caseymdk, after removing the `google_maps_flutter` plugin and running `flutter clean & flutter pub get`, the app builds just fine. It seems like the `google_maps_flutter` plugin (& other plugins) may be triggering this error. After adding the `google_maps_flutter` plugin back into the app, the app failed to build again. 

Labeling for further investigation

```
dyld[9069]: Symbol not found: _OBJC_CLASS_$_NSError
  Referenced from: <1CB429BC-C3C7-3DD8-A653-1C2846A72F1C> /private/var/containers/Bundle/Application/1F2F8F2E-C1EF-4289-B262-1400097B9683/Runner.app/Runner
  Expected in:     <27C62497-EEFA-3230-A726-3594BEC264D3> /private/var/containers/Bundle/Application/1F2F8F2E-C1EF-4289-B262-1400097B9683/Runner.app/Frameworks/camera_avfoundation.framework/camera_avfoundation
```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.13.6, on macOS 14.0 23A344 darwin-arm64, locale en-GB)
    • Flutter version 3.13.6 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (2 days ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-15.0.0-Release.Candidate.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.2)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 75.1.4
    • Dart plugin version 232.9559.10

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (4 available)
    • Nexus (mobile)       • 00008020-001875E83A38002E • ios            • iOS 17.0.1 21A340
    • Dean’s iPad (mobile) • 00008103-000825C811E3401E • ios            • iOS 17.0.1 21A340
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 117.0.5938.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```
[!] Flutter (Channel master, 3.15.0-11.0.pre.44, on macOS 14.0 23A344 darwin-arm64, locale en-GB)
    • Flutter version 3.15.0-11.0.pre.44 on channel master at /Users/nexus/dev/sdks/flutters
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 938bb217fb (3 hours ago), 2023-09-28 21:11:31 -0700
    • Engine revision 2052515c44
    • Dart version 3.2.0 (build 3.2.0-210.0.dev)
    • DevTools version 2.28.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-15.0.0-Release.Candidate.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.2)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 75.1.4
    • Dart plugin version 232.9559.10

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (4 available)
    • Nexus (mobile)       • 00008020-001875E83A38002E • ios            • iOS 17.0.1 21A340
    • Dean’s iPad (mobile) • 00008103-000825C811E3401E • ios            • iOS 17.0.1 21A340
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 117.0.5938.92

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```
</details>

**Comment by zanohikaru7** [comment]
Hello, it's still happening in the latest release when I include the `**google_maps_flutter**`, I also tried to `**flutter clean & flutter pub get**`. I tried it in a new project and the problem still occurs

 camera: ^0.10.5+5
 google_maps_flutter: ^2.5.0

**Comment by stuartmorgan** [comment]
> Hello, it's still happening in the latest release

Meaning that you ran `flutter pub upgrade`, and now have `camera_avfoundation` 0.9.13+6 in your pubspec.lock file?

**Comment by zanohikaru7** [comment]
> camera_avfoundation

Thanks for this information, It's already working now after I delete `pubspec.lock` and `Podfile.lock`, and do these steps:

- flutter clean
- flutter pub get
- pod install
- remove the existing app in the device or simulator
- flutter run
