### ISSUE TITLE
Firebase codelab uses Android Studio as example, but doesn't show IntelliJ version.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#13519]
For installing Google Repository, on [this page](https://codelabs.developers.google.com/codelabs/flutter-firebase/index.html#4), the codelab says to use "Android Studio > Tools > Android > SDK Manager > SDK Tools", but there is a similar method on IntelliJ that it doesn't show (or have screen shots for) which starts with File > Settings... > Appearance & Behavior > System Settings > Android SDK.

We should either standardize on one true IDE, or show steps for both.

**Comment by Sfshaza** [comment]
@gspencergoog, my understanding is that we have settled on AS. @eseidel, @Hixie, @mjohnsullivan, is that not the case?

**Comment by mjohnsullivan** [comment]
My understanding is that we'll move all our docs to refer to AS instead of
IntelliJ over time.

**Comment by Sfshaza** [comment]
Thanks, @mjohnsullivan, also my understanding.

**Comment by gspencergoog** [comment]
Ok, then, sounds definitive.  Closing.

**Comment by Sfshaza** [comment]
I still might add a note.  ;)
