### ISSUE TITLE
App crashes when Using the Impeller rendering backend

### ISSUE THREAD

**Issue by ToQuery** [flutter/flutter#135154]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

- macOS 13.5.2 (22G91)
- XCode Version 15.0 (15A240d)
- Simulator Version 15.0 (1015.2)
- iOS version iPhone 8 Plus iOS 16.4 (20E247)
- Flutter (Channel stable, 3.13.4, on macOS 13.5.2 22G91 darwin-arm64, locale
    zh-Hans-CN)

and  `flutter run` 

### Expected results

open the app

### Actual results

App crashes  , dont see anything

### Code sample

no

### Screenshots or Video

no

### Logs

<details><summary>Logs</summary>

```console

................

[   +9 ms] executing: /usr/bin/arch -arm64e xcrun simctl launch D616D730-1708-4207-9C4B-37D1FD90A943 com.yanse.peidui --enable-dart-profiling --enable-checked-mode --verify-entry-points
[ +105 ms] com.yanse.peidui: 5397
[        ] Waiting for VM Service port to be available...
[+1140 ms] [VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(37)] Using the Impeller rendering backend.

................


```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.4, on macOS 13.5.2 22G91 darwin-arm64, locale
    zh-Hans-CN)
    • Flutter version 3.13.4 on channel stable at
      /opt/homebrew/Caskroom/flutter/3.13.4/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 367f9ea16b (8 days ago), 2023-09-12 23:27:53 -0500
    • Engine revision 9064459a8b
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/toquery/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/toquery/Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/toquery/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.2)
    • IntelliJ at /Users/toquery/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (3 available)

.....


[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by gmr-renato** [comment]
Same issue here.

XCode version: 15.0
Flutter version: 3.13.4
iOS version: 17.0, 16.4 & 15.5 tested

**Comment by jonahwilliams** [comment]
We can't actually help find or fix the crash if you provide no details. Please file a new issue and follow the issue template.

**Comment by HarryToo** [comment]
The same issue occurs after upgrading to XCode 15.
This error occurs on my iOS 16.3.1 and other lower version devices, but the simulator of iOS 17 does not have this problem.

**Comment by rishabhchauhan421** [comment]
I had the same issue, its due to goole_mobile_ads package. Add below lines in info.plist
<key>GADApplicationIdentifier</key>
<string>ca-app-pub-xxxxxxxxxxxxxxxxxx</string>

**Comment by egyleader** [comment]
Same for me using xcode 15 & flutter 3.13.5 

```dart
Launching lib/main.dart on Ahmed’s iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: [REDUCTED]
Xcode build done.                                           41.0s
(lldb) 2023-09-25 12:44:01.048624+0300 [dev] dkilo walk[452:24041] [VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(37)] Using the Impeller rendering backend.
2023-09-25 12:44:01.066695+0300 [dev] dkilo walk[452:24041] Warning: Unable to create restoration in progress marker file
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x0000000000000000
error: memory read failed for 0x0
Target 0: ([dev] dkilo walk) stopped.
Error launching application on Ahmed’s iPhone.
Exited

```

**Comment by HarryToo** [comment]
I solved my problem temporarily. The error I reported here was caused by connectivity_plus. I temporarily removed connectivity_plus. I don’t know if other people also have errors due to this reason. At least that’s the case for me. You can refer to [here](https://github.com/fluttercommunity/plus_plugins/issues/2152).

**Comment by rishabhchauhan421** [comment]
I believe all this is due to some packages, try removing packages one by one to see which one is causing the issue. 
Method used by me - 
1) create a new project and all the packages from your current project
2) run the new project, I bet it will again show the same error. 
3) If yes, then keep commenting packages, untill you find the package with the issue.

then check documentation of that package and see where is your configuration missing for that specific package.

**Comment by zaferguler0** [comment]
> I solved my problem temporarily. The error I reported here was caused by connectivity_plus. I temporarily removed connectivity_plus. I don’t know if other people also have errors due to this reason. At least that’s the case for me. You can refer to [here](https://github.com/fluttercommunity/plus_plugins/issues/2152).

This worked for me also. Thank you

**Comment by sylvainjack** [comment]
I had exactly the same problem. I removed connectivity_plus and now it works... Strange... Everything worked fine a few weeks ago.... I guess before some updates...

**Comment by debovitch** [comment]
The Xcode 15 release supports on-device debugging in iOS 12 and later so you just have to update the iOS deployment target to 12.0+

**Comment by rakeshtsasi** [comment]
Install the latest connectivity_plus plugin.

**Comment by klaureta-cambridge** [comment]
> The Xcode 15 release supports on-device debugging in iOS 12 and later so you just have to update the iOS deployment target to 12.0+

This works on me. Thanks!

**Comment by isurucentronixx** [comment]
I turned off the "Debug executable" in Product -> Edit Scheme -> Info tab, and it worked.

**Comment by rahmanrezaee** [comment]
See the log while reporting 
Most of time have plugin issue

**Comment by PhdLapita** [comment]
I have the same issue but was solved updating connectivity_plus. Thanks guys.

**Comment by blackfrancis** [comment]
> I have the same issue but was solved updating connectivity_plus. Thanks guys.

I can't remove connectivity_plus due to dependency from amplify_api.  I can also not upgrade connectivity_plus to 5.0.1 for the same reason.  Any advice?

**Comment by blackfrancis** [comment]
I'm already targeting iOS 12.0+
I need to resolve the connectivity_plus version issue

**Comment by blackfrancis** [comment]
adding the code to my Podfile worked, except I had to target version 13.0 and reflect same in my XCode project

**Comment by IvanPavliuk** [comment]
Open Xcode -> Pods. 
Find connectivity_plus.
Increase the Minimum Deployments to 12.0

**Comment by nneuberger1** [comment]
After upgrading to connectivity_plus 5.0.1 (build 10/14/2023) it resolved my issue. This was indirectly caused by upgrading to Sonoma 14.0 / Xcode 15.0.1 / Android Studio Giraffe 2022.3.1 Patch 2 and pushing to iOS 16.7.2.

**Comment by dokind** [comment]
Same issue. how to resolve it...

**Comment by Christyansoft** [comment]
> I solved my problem temporarily. The error I reported here was caused by connectivity_plus. I temporarily removed connectivity_plus. I don’t know if other people also have errors due to this reason. At least that’s the case for me. You can refer to [here](https://github.com/fluttercommunity/plus_plugins/issues/2152).
Thank you so much 👏
