### ISSUE TITLE
[CP] fix for bgr10xr png compression

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#135157]
### Issue Link

https://github.com/flutter/flutter/issues/133013

### Commit Hash

n/a (skia fix)

### Target

stable

### PR Link

https://github.com/flutter/engine/pull/46103

### Changelog Description

**The cherry-pick PR is only for the Flutter test.**  This cherry-pick requires 2 cherry-picks to skia:
1) https://skia-review.googlesource.com/c/skia/+/752596
2) https://skia-review.googlesource.com/c/skia/+/757816

cc @CaseyHillers @zanderso 

### Impacted Users

iOS apps that encode to png decoded wide gamut images

### Impact Description

The app will crash.

### Workaround

Yes, turning off wide gamut support or converting all images to non-wide gamut before encoding them to PNG.  It may be the case that an app could release without knowing it needs a workaround if the app is ingesting arbitrary images.

### Risk

low

### Test Coverage

yes

### Validation Steps

There is reproduction code in the issue and a unit test.

**Comment by CaseyHillers** [comment]
Released in 3.13.6
