### ISSUE TITLE
[CP] fix wide gamut indexed colors png decompression

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#135153]
### Issue Link

https://github.com/flutter/flutter/issues/133013

### Commit Hash

n/a (Skia CL)

### Target

stable

### PR Link

https://github.com/flutter/engine/pull/46101

### Changelog Description

**The PR is just for the addition of the test, it also requires the following skia fix**: https://skia-review.googlesource.com/c/skia/+/751696

cc @CaseyHillers @zanderso 

### Impacted Users

iOS apps that open arbitrary images

### Impact Description

This will result in a crash in the Flutter app.

### Workaround

There is a workaround, turning off wide-gamut support in your app.  The problem is that that only works if you know you need it.  I suspect if one of the unsupported images is an asset, you'll probably catch it.  If you are reading images from the internet it is possible you wouldn't catch it in a test before releasing.

### Risk

low

### Test Coverage

yes

### Validation Steps

The issue has a linked image that can be used to test.  The unit test validates it as well.

**Comment by CaseyHillers** [comment]
Released in 3.13.6
