### ISSUE TITLE
AVD Manager not available in IDE plugin, yet `flutter doctor` says everything is OK

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#13514]
## Steps to Reproduce

When going through the codelab, I got to this page: https://codelabs.developers.google.com/codelabs/flutter/#2

In the "iOS Simulator or Android Emulator" section, it says to run the Android Emulator with  Tools > Android > AVD Manager, but when I do that, the AVD Manager is greyed out and unavailable.  Flutter doctor reports nothing missing.

![Screenshot of Menu](https://user-images.githubusercontent.com/8867023/33900638-02750cee-df24-11e7-936d-e1d160db5557.png)

I'm not sure if a step is missing from the instructions, or if there's a problem with the IntelliJ plugins.

I am able to run an already configured emulator from the devices pulldown.

## Flutter Doctor

```
[✓] Flutter (on Linux, locale en_US.UTF-8, channel unknown)
    • Flutter at /usr/local/google/home/gspencer/code/release/flutter
    • Framework revision 8f65fec5f5 (11 minutes ago), 2017-12-12 09:50:14 -0800
    • Engine revision edaecdc8b8
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.d8ae797298c3a6cf8dc9f4558707bd2672224d3e

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.1)
    • Android SDK at /usr/local/google/home/gspencer/Android/Sdk
    • Android NDK at /usr/local/google/home/gspencer/Android/Sdk/ndk-bundle
    • Platform android-26, build-tools 26.0.1
    • ANDROID_HOME = /usr/local/google/home/gspencer/Android/Sdk
    • Java binary at: /opt/android-studio-with-blaze-2.3/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio-with-blaze-2.3
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1)
    • Flutter plugin version 18.4
    • Dart plugin version 171.4694.29

[✓] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 20.0.2
    • Dart plugin version 172.4343.25

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1)
    • Flutter plugin version 18.2
    • Dart plugin version 171.4694.29

[✓] Connected devices
    • Nexus 6P • 84B7N15A07007628 • android-arm • Android 8.0.0 (API 26)
```

**Comment by sethladd** [comment]
cc @LarkAscending @mjohnsullivan

**Comment by LarkAscending** [comment]
@sethladd  Seems like a product issue to me WDYT?

**Comment by sethladd** [comment]
Hm, good question.

cc @devoncarew is there a symptom around "AVD Manager is greyed out" ? Does that indicate something that can be fixed by a user?

According to https://stackoverflow.com/questions/41290134/android-studio-avd-manager-button-is-disabled maybe the Android SDK is misconfigured or missing? If so, then maybe `flutter doctor` isn't doing to right thing, as it should complain here.

https://stackoverflow.com/questions/44015671/android-studio-2-3-avd-manager-greyed-out seems to hint that maybe some project files are missing?

In either case, I think the codelab doesn't need to add any explicit steps here, but we might need to make `flutter doctor` a bit smarter here to catch a potential project misconfiguration.

**Comment by rockingdice** [comment]
For anyone who still meets this issue on mac with Intellij idea, you can try find 'Android' tab in preferences, it may tell you android sdk is not installed, but if you try to install the ide will find the sdk and nothing will change but it recognized the sdk. After that you can use AVDManager.

**Comment by zoechi** [comment]
Issue moved to [flutter/flutter-intellij #3146](https://github.com/flutter/flutter-intellij/issues/3146) via [**ZenHub**](https://www.zenhub.com/)
