### ISSUE TITLE
Firebase does not like underscore in iOS bundle id

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter#13518]
Following instructions in:
[Flutter Firebase codelab](https://codelabs.developers.google.com/codelabs/flutter-firebase/#4)

I named my project `friendly_chat`.

The problem is that Dart packages need to use the `snake_case` naming convention. When the iOS bundle name is generated, it uses the project name unchanged. Copying and pasting that into the Firebase console won't work because Firebase does not accept the underscore.

**Comment by cbracken** [comment]
Thanks for reporting!

From [Apple's documentation](https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/ConfiguringYourApp/ConfiguringYourApp.html):

> The bundle ID string must be a uniform type identifier (UTI) that contains only alphanumeric characters (A-Z,a-z,0-9), hyphen (-), and period (.). The string should be in reverse-DNS format. For example, if your organization’s domain is Acme.com and you create an app named Hello, you could assign the string com.Acme.Hello as your app’s bundle ID.

Seems like a quick fix would be to fix `flutter create` to replace `_` with `-`.

**Comment by kroikie** [comment]
@stevemessick

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/928. Any further collaboration will be done there.
