### ISSUE TITLE
Add support for theming animation duration and curve

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter#135233]
For applications wishing to apply a single animation curve and duration to their app (or a subsection of their app), `ThemeData` would benefit from supporting animation curve and duration.

Any widget with `duration` and `curve` in their constructor could be impacted, e.g. `AnimatedSize`

**Comment by opxdelwin** [comment]
Hi @guidezpl, This is nice, I'll create a draft PR shortly as this might potentially be a huge implementation.

**Comment by guidezpl** [comment]
Sweet! @HansMuller or @QuncCccccc want to take a look?

**Comment by HansMuller** [comment]
As [noted here](https://github.com/flutter/flutter/pull/135259#issuecomment-1734265885), I think that finding a compact but comprehensive way to override component animations, as well as the theme's animation, is an important issue for Flutter.  We need to find a solution that's general enough to handle animations that track component state changes and then apply it systematically.

**Comment by Piinks** [comment]
This appears to have been fixed by #138721 👍
