### ISSUE TITLE
 Could you allow specifying the physics property for DraggableScrollableSheet? 

### ISSUE THREAD

**Issue by yamadade** [flutter/flutter#135298]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

 ```
return DraggableScrollableSheet(
      physics: BouncingScrollPhysics(),
      initialChildSize: 0.2,
      minChildSize: 0.1,
      maxChildSize: 0.3,
      snap: true,
      expand: false,
      builder: (BuildContext context, ScrollController scrollController) {
        return Container(
          width: 100,
          hight: 100,
    );
);
```

### Proposal

I would like to set BouncingScrollPhysics() for it.

**Comment by opxdelwin** [comment]
Interesting proposal, what do you think @HansMuller?

**Comment by huycozy** [comment]
@yamadade I think this can be solved when you add physic for the scrolling list inside:

```dart
child: DraggableScrollableSheet(
  builder: (BuildContext context, ScrollController scrollController) {
    return Container(
      color: Colors.blue[100],
      child: ListView.builder(
          physics: const BouncingScrollPhysics(),
```

https://github.com/flutter/flutter/assets/104349824/65710cb2-0164-40f7-bd19-107e5b4dca15

<details>
<summary>Complete sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp(
    title: 'Flutter Demo',
    home: HomePage(),
  ));
}

class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('DraggableScrollableSheet'),
      ),
      body: SafeArea(
        child: SizedBox.expand(
          child: DraggableScrollableSheet(
            builder: (BuildContext context, ScrollController scrollController) {
              return Container(
                color: Colors.blue[100],
                child: ListView.builder(
		 physics: const BouncingScrollPhysics(),
                  controller: scrollController,
                  itemCount: 25,
                  itemBuilder: (BuildContext context, int index) {
                    return ListTile(title: Text('Item $index'));
                  },
                ),
              );
            },
          ),
        ),
      ),
    );
  }
}

```
</details>

If this approach has any limitation, can you please share?

**Comment by yamadade** [comment]
@huycozy 
Thank you for the suggestion.
However, that is not what I had in mind.
I just want to be able to set BouncingScrollPhysics for DraggableScrollableSheet, not for the contents of the sheet.

**Comment by huycozy** [comment]
@yamadade Yes, I can see this issue proposes adding `physics` to `DraggableScrollableSheet` directly. But my point of view is: 

If you need a physic for it, it is implicitly understood that it will have a scrolling list inside `DraggableScrollableSheet`, so it will fall back to the case I shared above. So this proposal is trying to solve an issue that has already been solved, is that correct?

**Comment by yamadade** [comment]
@huycozy
No, there isn't a scrolling list inside DraggableScrollableSheet. I want to set BouncingScrollPhysics for DraggableScrollableSheet itself.

**Comment by darshankawar** [comment]
@yamadade 
Providing `physics` property or `BouncingScrollPhysics` directly to `DraggableScrollableSheet` widget isn't a feasible proposal, because `DraggableScrollableSheet` is a container for a [Scrollable](https://api.flutter.dev/flutter/widgets/Scrollable-class.html) in which we are suppose to use scrollable widgets that provides `physics` property.

You can have a scrollable widget in the builder of the DraggableScrollableSheet and assign the scroll controller from the builder to the scrollable.

Since the proposal isn't feasible, I'll go ahead and close this issue. If you disagree, write in comments and I'll reopen it.
