### ISSUE TITLE
Request for a "How to JSON with Flutter?" article

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#13520]
We've received many requests for opinions, examples, and best practices for using JSON (usually with REST) with Flutter.

* What JSON libraries exist, and what are their trade-offs?
* How do I minimize hand-coding boilerplate encoding/decoding code?
* Can I annotate my Dart objects and give them to some JSON encoder?
* What are the performance implications?

There may be solutions for the above, but it's not clear to a Flutter developer what's available, what's recommended, or how to start.

**Comment by sethladd** [comment]
We'd love for someone in our community to write a post about this. This article doesn't necessarily have to come from the Flutter team.

**Comment by roughike** [comment]
I could write an article on flutter.rocks about this if you like.

AFAIK, there's two ways for handling JSON in Flutter: 

* manually, using the `JSON.encode` (and `JSON.decode`) methods from `dart:convert` library
* using built_value, which I actually have a draft article on.

And the reason for `dartson` and similar JSON libraries not working with Flutter is because dart:mirrors isn't supported, due to interfering with tree-shaking.

Am I correct? Wouldn't want to give false information to anyone :)

**Comment by zoechi** [comment]
https://pub.dartlang.org/packages/json_serializable (which is maintained by the Dart team) is also based on code generation like `built_value` and therefore works with Flutter.
`built_value` is more opinionated (deep immutability)
There are others (jaguar, ...?)

**Comment by sethladd** [comment]
@roughike sounds like a great start! (and yes, dart:mirrors doesn't work in Flutter)

@kevmoo is working on making json_serializable easy to use. We can add that to @roughike 's article later.

**Comment by kevmoo** [comment]
Making good progress on docs

https://github.com/dart-lang/json_serializable/pull/83
https://github.com/dart-lang/json_serializable/tree/more_readme_fun/example

**Comment by roughike** [comment]
Awesome! I have a busy weekend, but I'll ping you when I have something :)

**Comment by sethladd** [comment]
@roughike something is better than nothing, so don't aim for perfection right away :) and thank you!

**Comment by sethladd** [comment]
@kevmoo I am standing by to be your UX study. Can't wait to give it a try!

**Comment by kevmoo** [comment]
@sethladd see https://github.com/dart-lang/json_serializable/tree/master/example

Give it a try!

...and try to make some progress on https://github.com/flutter/flutter/issues/13607

**Comment by roughike** [comment]
I have the base for the article and samples in place for the manual `dart:convert` way and `json_serializable` way. 

I'm pretty sure it's best to leave `built_value` out of this, and focus on those two ways, the pros and cons, and what to choose in which situation and why. Otherwise I'm afraid the article will become too heavy to read through.

Since my site now exists in GitHub, I'll make a Pull Request to it and notify you here when I'm done. That way you can have a chance for reviewing it before it goes public :)

I'll wrap up my work in the next couple days.

**Comment by zoechi** [comment]
You could add a link to this article from the author of built_value https://medium.com/dartlang/darts-built-value-for-serialization

**Comment by kevmoo** [comment]
Wonderful! Happy to review!

**Comment by sethladd** [comment]
@roughike thanks for the head's up! Looking forward to the draft.

**Comment by roughike** [comment]
@sethladd Sure!

Was planning on doing a blog post about it, but if it fits better in the flutter.io site then why not. Kinda busy with work and the New Year celebrations (doing both simultaneously), but I'll make a PR directly to the Flutter site then :)

**Comment by sethladd** [comment]
Cool. Let's take a look at the article. Please write it with the goal of being included in the main website. Worst case, you can publish as blog post. But, I suspect this is an area relevant to pretty much everyone so we should aim for the website. Thanks!

**Comment by roughike** [comment]
It's currently kind of my own writing style, and it's not quite there just yet.

I'll rework it a bit to be more of the writing style that the main website has. Give me a couple days into the next year and I'll have something then.

**Comment by roughike** [comment]
I feel like I'm finishing the first draft by tomorrow. Where do you want me to put it for you guys to have a look?

**Comment by MaikuB** [comment]
@sethladd I think it might be worth adding this link to the existing page on the website

https://javiercbk.github.io/json_to_dart/

Reduces the need to manually write the code, seems to cover the scenario covered at https://flutter.io/json/#serializing-json-inside-model-classes and can be used as a starting point to use the code generation libraries

**Comment by shakil807g** [comment]
@MaikuB  It's a great tool why this is not mention any where ??

**Comment by morningstarwang** [comment]
> @sethladd I think it might be worth adding this link to the existing page on the website
> 
> https://javiercbk.github.io/json_to_dart/
> 
> Reduces the need to manually write the code, seems to cover the scenario covered at https://flutter.io/json/#serializing-json-inside-model-classes and can be used as a starting point to use the code generation libraries

This is definitely  a good tool for Flutter JSON things.

**Comment by MaikuB** [comment]
I suspect that it might be because it's an site that Google don't maintain themselves so having the official documentation not depend on a site that could in theory be deleted seems reasonable IMO :)
