### ISSUE TITLE
Regression in release compilation time on iOS

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#135274]
SkiaPerf is reporting a regression in initial release compilation time on the commit https://github.com/flutter/flutter/commit/22e4088134b80c63faf3abd98bfbae8abe7ea8d6

https://flutter-flutter-perf.skia.org/e/?begin=1694115415&end=1695348859&keys=Xeb53656b4f751dea0b79aba8134af69c&requestType=0&selected=commit%3D36961%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253Drelease_initial_compile_millis%252Ctest%253Dflutter_gallery_ios__compile%252C&xbaroffset=36963

The regression is  ~77s -> ~85s.

cc @cyanglaz

**Comment by zanderso** [comment]
Multiple apps' compilation time has regressed, so not just a fluke:

https://flutter-flutter-perf.skia.org/e/?keys=X15b7647f191f2b39c8710699cc4b7ee6&selected=commit%3D36961%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253Drelease_initial_compile_millis%252Ctest%253Dbasic_material_app_ios__compile%252C&xbaroffset=36961

**Comment by cyanglaz** [comment]
There are more artifacts (extension_safe version of Flutter.framework) to download after https://github.com/flutter/flutter/commit/22e4088134b80c63faf3abd98bfbae8abe7ea8d6. 
This is expected.

Maybe we can add a tool command to download the extension safe framework separately when only needed?

**Comment by zanderso** [comment]
Makes sense. On reading the benchmark code, the "initial" compile benchmarks include artifact download time. The "full" compile benchmarks do not. Since there was no regression in the "full" compile benchmark, I'll go ahead and close this.
