### ISSUE TITLE
Presubmit never scheduled 50+ tasks

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#135235]
See ![image](https://github.com/flutter/flutter/assets/2148558/ad64a688-af33-4dc8-8422-eb8d44e07926)

https://github.com/flutter/flutter/pull/135097/checks?check_run_id=16999294129

Only 2 builds were scheduled, test_ownership and skp_generator. Since this PR touches the Flutter tool, many more tests should have been run. It's been 5 hours outside of peak hour, and I expect this is enough time for everything to run.

The only special thing to note is the PR is marked as draft, but that shouldn't prevent builds from being scheduled.

**Comment by yusuf-goog** [comment]
fyi @drewroengoogle

**Comment by drewroengoogle** [comment]
I looked at the logs and it seems like cocoon is determining there to only be 2 targets, which implies this is not a problem with github or the builds being scheduled, but the logic that is determining what targets to run. Continuing to take a look

**Comment by drewroengoogle** [comment]
Okay, I didn't get far enough into the logic to understand why, but it looks like there is a difference between merging to a default branch versus a non-default branch.

@CaseyHillers The PR in question was trying to merge to `main` instead of `master`, so switching the base in the PR triggered all of the targets. I am assuming that merging to `main` was not intended, but asked in the PR anyway to be safe.

**Comment by CaseyHillers** [comment]
Should Cocoon post a comment telling the user they should be merging to master instead? Generally, Cocoon should tell if the opposite of main|master is being used, and then automatically change it for the user.

**Comment by drewroengoogle** [comment]
Good point. I'm going to close this issue since the PR in question was resolved. I have created https://github.com/flutter/flutter/issues/135250 as a feature request for the cocoon scheduler!

**Comment by ricardoamador** [comment]
I disagree. It should not change the target branch. The user should know which branch they are targeting. If we don't want merges to the non default then we can protect the branch rather than having the scheduler change it.
