### ISSUE TITLE
[macOS] TextInputPlugin is visible when built on macOS 14

### ISSUE THREAD

**Issue by knopp** [flutter/flutter#135219]
Reproducible with code sample from https://github.com/flutter/flutter/issues/134699

<img width="420" alt="Screenshot 2023-09-21 at 15 07 20" src="https://github.com/flutter/flutter/assets/96958/08fa6f29-a38c-4659-b809-ef0d37f6c73c">

There was a breaking change in macOS 14 where NSView is not clipped to bounds by default. This affects our TextInputPlugin which has frame set to zero.

**Comment by cbracken** [comment]
This is a reappearance of https://github.com/flutter/flutter/issues/128956; going to close this in favour of reopening that so that we've got the full history.
