### ISSUE TITLE
Unresolved import io.flutter.embedding.android.FlutterActivity

### ISSUE THREAD

**Issue by mobiluse** [flutter/flutter#135261]
### Is there an existing issue for this?

- [x] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

<img width="1470" alt="Screenshot 2023-09-22 at 2 12 55 AM" src="https://github.com/flutter/flutter/assets/142053982/a6be552a-0ad1-4846-b44e-de52ee703c23">

### Expected results

No red lines

### Actual results

Red Lines.

Tried opening android project and building build. But didn't worked. Please help me.

### Code sample

package com.mobiluse.keyspu

import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
}

### Screenshots or Video

<img width="1470" alt="Screenshot 2023-09-22 at 2 14 20 AM" src="https://github.com/flutter/flutter/assets/142053982/35eb76e2-db03-45e6-b750-c406a313350b">
<img width="1470" alt="Screenshot 2023-09-22 at 2 15 12 AM" src="https://github.com/flutter/flutter/assets/142053982/1206ae49-3c5a-41a0-963b-4e59ff7e77d8">
<img width="1470" alt="Screenshot 2023-09-22 at 2 15 29 AM" src="https://github.com/flutter/flutter/assets/142053982/c2e68128-96ff-4d4a-aff9-0e25ad9962fe">
<img width="1470" alt="Screenshot 2023-09-22 at 2 15 34 AM" src="https://github.com/flutter/flutter/assets/142053982/738bf7f6-e40b-4e76-9686-c87d845cf639">
<img width="1470" alt="Screenshot 2023-09-22 at 2 15 49 AM" src="https://github.com/flutter/flutter/assets/142053982/bb
<img width="1470" alt="Screenshot 2023-09-22 at 2 16 22 AM" src="https://github.com/flutter/flutter/assets/142053982/5a9ec850-e777-458e-bbcc-551e24fb3806">
09edfe-38fe-4d18-89a7-31650ba6541a">
<img width="1470" alt="Screenshot 2023-09-22 at 2 16 31 AM"
<img width="1470" alt="Screenshot 2023-09-22 at 2 16 40 AM" src="https://github.com/flutter/flutter/assets/142053982/d9ee63dd-74a1-4c4b-95cd-289ad15bf45b">
 src="https://github.com/flutter/flutter/assets/142053982/b6bc8766-5b50-4e93-aff0-ff26e87d3851">

### Flutter Doctor output

<img width="697" alt="Screenshot 2023-09-22 at 2 17 25 AM" src="https://github.com/flutter/flutter/assets/142053982/d35ed549-d98a-4c5f-8cfe-23fb921b46eb">

**Comment by huycozy** [comment]
Hi @mobiluse 
Please provide reproduction steps in detail so that we may verify the issue properly. And please provide information in text format instead of a screenshot for better readability and investigation. 

You can also check [this](https://stackoverflow.com/questions/64468323/flutter-cannot-resolve-symbol-embedding-and-cannot-resolve-symbol-flutteracti) if it helps.

**Comment by mobiluse** [comment]
Hi @huycozy 

1. You can also check [this](https://stackoverflow.com/questions/64468323/flutter-cannot-resolve-symbol-embedding-and-cannot-resolve-symbol-flutteracti) if it helps.

The one you mentioned (which I mentioned above) was tried by me but still there are red lines under that. 
I created a new flutter project using android studio and then it appeared.
Tried opening the android folder in android studio. Waited for gradle build but still having red lines. 
Please help me out in this.
Thank you

![Image](https://github.com/flutter/flutter/assets/142053982/0ba4dbc3-6c90-4a6a-8acc-0385b8651bf3)

**Comment by huycozy** [comment]
I notice you are using `Android Studio Giraffe`; I also checked this on `Android Studio Giraffe | 2022.3.1` (and enabled `new UI beta`) but can't reproduce this:

![Screenshot 2023-09-25 at 11 49 35](https://github.com/flutter/flutter/assets/104349824/fc8eea0d-2263-4869-acee-ec4b6d2269c2)

I'm guessing this could be caused by different gradle version on `android` module. You can try using a different version from Gradle setting as below to see if it works (choose one of Gradle JDK sources there):

![Screenshot 2023-09-25 at 11 53 03](https://github.com/flutter/flutter/assets/104349824/f922b1c3-e91f-471b-a2ec-0a788dda4055)

**Comment by mobiluse** [comment]
I'm getting this in this tab. @huycozy 
<img width="1012" alt="Screenshot 2023-09-28 at 1 42 36 AM" src="https://github.com/flutter/flutter/assets/142053982/e2b3f704-a8a2-42aa-a2f3-8c64d1e9260e">

**Comment by mobiluse** [comment]
and still having this red.
<img width="1470" alt="Screenshot 2023-09-28 at 1 43 20 AM" src="https://github.com/flutter/flutter/assets/142053982/0473a777-69d7-4cba-ba17-8f0a2e94344e">

**Comment by huycozy** [comment]
>I'm getting this in this tab.

It looks like you are open flutter project directory instead, let's try opening `android` module to see if it works.

**Comment by mobiluse** [comment]
Here is this @huycozy 
<img width="1094" alt="Screenshot 2023-09-28 at 11 18 29 PM" src="https://github.com/flutter/flutter/assets/142053982/d75aef7f-7a24-48ea-825c-69b61ce454a4">

**Comment by huycozy** [comment]
Now let's try switching to other JDK versions there to see if it works. If it doesn't work, please share your sample project here so that I can help to check it.

Also, it seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any.

**Comment by mobiluse** [comment]
@huycozy I tried but still getting same on it. I tried making new project but this is also in that project. Please let me know how to solve this.
Thank you.

**Comment by huycozy** [comment]
Could you confirm the gradle sync finished successfully on `android` module? Please compress your newly created Flutter project and share it here so that I can try checking it on my end. Thanks!

**Comment by mobiluse** [comment]
@huycozy I'll share tomorrow. Was busy in sister's wedding.

**Comment by mobiluse** [comment]
Also, I waited for too long after gradle sync finish.

**Comment by huycozy** [comment]
It looks like a Gradle issue, please make sure Gradle sync finished successfully. You may check the internet connection (make sure it's not slow) or observe machine RAM/CPU usage to see if there is any process that consume resource abnormally.
