### ISSUE TITLE
[iOS][CupertinoDatePicker] - Cupertino Time Picker gets cut off from vertical edges

### ISSUE THREAD

**Issue by aakashawalkar** [flutter/flutter#135291]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a new Flutter app.
2. Implement a Cupertino Time Picker to pick a time.
3. The Time Picker is visible as being cut off at the vertical edges of the mobile device, which was not the case with Flutter 3.7.12 earlier.

PS: The Cupertino time picker was displayed as expected with Flutter 3.7.12 and earlier. However, with subsequent Flutter releases (3.10.0 and above), the Cupertino time picker is being cut off at the side edges.

- I discovered that Cupertino time picker's width is affected by lines 98 to 100 of [date_picker.dart](https://github.com/flutter/flutter/blob/12fccda598/packages/flutter/lib/src/cupertino/date_picker.dart#L98)

### Expected results

The TimePicker popup should not be trimmed from the sides.

![IMG_0101](https://github.com/flutter/flutter/assets/97581635/0dc03140-4f7c-4509-9fdf-e150149d0077)

### Actual results

The Cupertino Time Picker popup is being trimmed from the sides.

![IMG_0100](https://github.com/flutter/flutter/assets/97581635/559db235-c668-4a13-ae3a-5558dee37a84)

### Code sample

<details><summary>Code sample</summary>

```dart

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

/// Run main()
void main() {
  runApp(const MyApp());
}

/// The root of the App
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}

/// Home screen
class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final TextEditingController timeController = TextEditingController();

  Future<void> _showIOSTimePicker() async {
    final DateTime now = DateTime.now();

    await showCupertinoModalPopup(
      context: context,
      builder: (BuildContext context) {
        return SizedBox(
          height: 300,
          child: CupertinoDatePicker(
            minuteInterval: 30,
            use24hFormat: false,
            backgroundColor: Colors.white,
            mode: CupertinoDatePickerMode.time,
            initialDateTime: DateTime(now.year, now.month, now.day),
            minimumDate: DateTime(now.year, now.month, now.day),
            maximumDate: DateTime(now.year, now.month, now.day),
            onDateTimeChanged: (DateTime? value) {
              if (value != null) {
                setState(() {
                  timeController.text = DateFormat('hh:mm a').format(value);
                });
              }
            },
          ),
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Test Cupertino Time Picker'),
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            ElevatedButton(
              onPressed: _showIOSTimePicker,
              child: const Text('Open Cupertino Time Picker'),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

Actual Result: 

https://github.com/flutter/flutter/assets/97581635/41e750fa-8926-4657-bbff-a024e3c50b92

Expected Result: 

https://github.com/flutter/flutter/assets/97581635/6f4be833-6fb5-4aff-878d-346ff9e3bc4c

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.5 22G74 darwin-arm64 (Rosetta), locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.82.0)
[✓] Connected device (4 available)
[✓] Network resources

 

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @aakashawalkar 
Using the code sample you provided, I do see the same behavior as reported using latest stable. Although using the official [example](https://api.flutter.dev/flutter/cupertino/CupertinoDatePicker-class.html#cupertino.CupertinoDatePicker.1), I do see the expected behavior as below:

<img width="358" alt="Screenshot 2023-09-22 at 5 31 45 PM" src="https://github.com/flutter/flutter/assets/67046386/9c2e69ab-f34b-4c65-8e96-fbfad360e2e6">

Can you check your code implementation with the one with example provided and see if there's anything missing or need to be added in your code ?

**Comment by aakashawalkar** [comment]
Thank you for help @darshankawar 

Previously, it was not necessary to explicitly specify the BG colour for the time picker. However, according to the sample code, we must now surround the time picker with a container and explicitly specify the BG colour so that the picker does not appear to be cut off from the edge.

**Comment by darshankawar** [comment]
This sounds like you have found root-cause and solution to make it work as expected, so closing based on it. If you disagree, write in comments and I'll reopen it.
