### ISSUE TITLE
Http (fetch-XHR) requests are being canceled some time. i m using Flutter Web (get: ^4.6.6) + Xampp(Laravel)

### ISSUE THREAD

**Issue by MurtuzaSrashtaSoft** [flutter/flutter#135236]
### Is there an existing issue for this?

- [x] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Http (fetch-XHR) request goes canceled state and sometimes it's working.

Most Probably it's not working at first time after the page loads.

Once I do a hard refresh then it's working.

### Expected results

Http (fetch-XHR) request **not goes canceled** state

### Actual results

Http (fetch-XHR) request **not goes canceled** state

### Code sample

api_client.dart class

```
class ApiClient extends GetConnect {
  String getAuthorizationToken() {
    final String token = 'Bearer ${getToken()}';
    //debugPrint("token $token");
    return token;
  }
  String getToken() {
    return "Example Token";
  }
}
```

BidProvider.dart file

```
class BidProvider extends ApiClient {
  @override
  void onInit() {
    httpClient.addRequestModifier<Object?>((Request<Object?> request) {
      request.headers['Accept'] = 'application/json';
      request.headers['Access-Control-Allow-Origin'] = '*';
      return request;
    });
    super.onInit();
  }

    Future<Response<ResponseDataArrayModel<BidItem>>> getListForUser({
    required String baseUrl,
    String? queryParams,
  }) async {
    httpClient.defaultDecoder = (val) {
      printJasonString(val as Map<dynamic, dynamic>);
      return ResponseDataArrayModel<BidItem>.fromJson(
          BidItem.empty, val as Map<String, dynamic>);
    };
    httpClient.addRequestModifier<Object?>((Request<Object?> request) {
      request.headers['Accept'] = 'application/json';
      request.headers['Access-Control-Allow-Origin'] = '*';
      request.headers['Authorization'] = super.getAuthorizationToken();
      request.headers['Accept-Language'] = super.getLocal();
      printJasonString(request.headers);
      return request;
    });
    String url = '$baseUrl${ServiceUrl.bid}';
    if (queryParams != null) {
      url = '$url$queryParams';
    }
    //debugPrint('url $url');
    //await Future.delayed(const Duration(seconds: 3));
    return httpClient.get<ResponseDataArrayModel<BidItem>>(url);
  }

}
```

### Screenshots or Video

<img width="833" alt="Screenshot 2023-09-21 at 7 09 28 PM" src="https://github.com/flutter/flutter/assets/64843262/ec87b530-5685-49ea-94b6-04647390e3b5">
<img width="830" alt="Screenshot 2023-09-21 at 7 11 52 PM" src="https://github.com/flutter/flutter/assets/64843262/5f058e22-1d73-4459-b62b-abfd612ff119">

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

[!] Flutter (Channel stable, 3.13.5, on macOS 13.5.2 22G91 darwin-arm64, locale en-KW)
    • Flutter version 3.13.5 on channel stable at /Users/murtuzanalawala/Library/Android/fluttersdk/flutter
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.1.0/libexec/bin/dart, which is not inside your current Flutter SDK checkout at
      /Users/murtuzanalawala/Library/Android/fluttersdk/flutter. Consider adding /Users/murtuzanalawala/Library/Android/fluttersdk/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12fccda598 (2 days ago), 2023-09-19 13:56:11 -0700
    • Engine revision bd986c5ed2
    • Dart version 3.1.2
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/murtuzanalawala/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (3 available)
    • iPhone 15 Pro Max (mobile) • 2FA1D2B9-B88F-4C95-AC5F-3E8FDA4EECAF • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.5.2 22G91 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 116.0.5845.187

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

**Comment by darshankawar** [comment]
@MurtuzaSrashtaSoft 
`get` is a third party package and I think your issue / question is better suited for support channels like StackOverflow.
Closing from here.
