### ISSUE TITLE
How to save Video Player into a file using flutter?

### ISSUE THREAD

**Issue by AndreAhmed** [flutter/flutter#135240]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I'm very beginner in flutter. I would like to play a video using Video Player, in real time, I'm embedded some text, animations,..etc on while playing that video. Then I would like to save the full edited video into a file.

What are the current approaches support that in flutter ? Giving that I don't want missing frames, or laggy output

### Proposal

https://play.google.com/store/apps/details?id=io.instories&hl=en_US An example of what I plan to do

**Comment by AndreAhmed** [comment]
@opxdelwin The question there was about to get closed, and there are no answers

**Comment by darshankawar** [comment]
@AndreAhmed 
Your question is better suited for support channels like StackOverflow or Flutter's reddit help page, so please ask the same there.
Closing from here, as this is more of a `how to` question rather than a bug report or feature request.
