### ISSUE TITLE
[webview_flutter]When can onTitleChanged be supported on iOS

### ISSUE THREAD

**Issue by bh1270** [flutter/flutter#135287]
### Is there an existing issue for this?

- [ ] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [ ] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

[webview_flutter]When can onTitleChanged be supported on iOS

### Proposal

[webview_flutter]When can onTitleChanged be supported on iOS

**Comment by bh1270** [comment]
[webview_flutter]When can onTitleChanged be supported on iOS

**Comment by huycozy** [comment]
Hi @bh1270 
When opening an issue, please try to provide all information indicated in the template so that we can address this issue properly. 

Could you share to API source documentation in iOS here?

**Comment by bh1270** [comment]
When I use WebViewWidget，I cannot obtain real-time title changes because I can only use the onPageFinished and onUrlChange methods

**Comment by bh1270** [comment]
@huycozy When I use WebViewWidget，I cannot obtain real-time title changes because I can only use the onPageFinished and onUrlChange methods

**Comment by huycozy** [comment]
I just found `wkwebview`'s title property here: https://developer.apple.com/documentation/webkit/wkwebview/1415015-title and it's implemented in the plugin at [getTitle()](https://github.com/flutter/packages/blob/e548ae1d2045974a6be0b9c9e3517cf23b78240e/packages/webview_flutter/webview_flutter_wkwebview/lib/src/web_kit/web_kit.dart#L1071-L1076)


It can be accessed via `WebViewController` instance. Have you tried it to see if it can solve your case?

**Comment by bh1270** [comment]
@huycozy I know that using kvo in iOS can obtain titles, and using controller to obtain titles, but I use the plugin [webview_flutter] in Flutter, and when my title changes, I cannot obtain it in real time

**Comment by huycozy** [comment]
Thanks for your update. I see there's an open issue addressing the case you described (is filed for both Android and iOS): https://github.com/flutter/flutter/issues/49104

Closing this issue as a duplicate, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
