### ISSUE TITLE
Flutter inspector does not navigate to the Source Code of my app

### ISSUE THREAD

**Issue by AlHasanSony** [flutter/flutter#135375]
Previously, when I ran the app and turned on the widget mode in the Flutter Inspector, if I clicked on any widget in the APP, it would immediately navigate to the code related to that widget element inside the Dart file. But now, when I click, it only selects the widget in the widget tree. However, it doesn't navigate to the related code in the Dart file anymore. **What could be the possible solution for this?**

My expectation is: If I click on any widget in the app, it will immediately navigate to the code related to that widget element inside the Dart file like previously

_[It works fine in flutter version 3.10.6 and earlier, but in later versions, it doesn't work]_

**Comment by AlHasanSony** [comment]
I've found a solution from a youtube video. Here's the link below  ⤵️

[https://youtu.be/oHcjiMGG4ic?si=4Xi4bSql-iJ6sKAU](url)

**Comment by darshankawar** [comment]
@AlHasanSony 
Since the video shows usage of latest version of `flutter-intellij` plugin that solves the issue, I will go ahead and close as resolved. If you disagree, write in comments and I'll reopen it.

**Comment by Andreigr0** [comment]
Facing the same issue. Video didn't help. 
Flutter version 3.13.5

<details>
<summary>IntelliJ 2023.2.2</summary>
IntelliJ IDEA 2023.2.2 (Community Edition)
Build #IC-232.9921.47, built on September 13, 2023
Runtime version: 17.0.8+7-b1000.8 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.4
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Metal Rendering is ON
Registry:
    ide.intellij.laf.enable.animation=true
    debugger.new.tool.window.layout=true
    documentation.show.toolbar=true
    ide.experimental.ui=true
    ide.browser.jcef.gpu.disable=true
    ide.balloon.shadow.size=0
    ide.images.show.chessboard=true

Non-Bundled Plugins:
    AWSCloudFormation (232.8660.88)
    com.markskelton.one-dark-theme (5.8.0)
    com.tylerthrailkill.intellij.solarized (3.0.0)
    com.vermouthx.xcode-theme (1.6.3)
    atom-one (1.5.1)
    com.github.copilot (1.2.22.3129)
    net.antelle.intellij-xcode-dark-theme (1.2.4)
    com.arcticicestudio.nord.jetbrains (0.13.0)
    Dart (232.9559.10)
    com.localizely.flutter-intl (1.18.4-2023.2)
    com.4lex4.intellij.solarized (2.4.0)
    some.awesome (1.14)
    com.thvardhan.gradianto (5.4)
    com.mallowigi.idea (22.0.0)
    com.jetbrains.darkPurpleTheme (1.3)
    io.github.tbm98.flutter_generator_snippets (2.232.1)
    monokai-pro (1.10)
    com.bloc.intellij_generator_plugin (3.4.0)
    String Manipulation (9.11.3)
    com.jetbrains.packagesearch.intellij-plugin (232.9921.28)
    izhangzhihao.rainbow.brackets (2023.3.4)
    io.flutter (75.1.4)
    de.mariushoefler.flutter_enhancement_suite (1.7.0)
    zielu.gittoolbox (500.0.18+222)

Kotlin: 232-1.9.0-IJ9921.47
</details>
