### ISSUE TITLE
"Null check operator used on a null value.", exception thrown null at `State.context` in `framework.dart:957`

### ISSUE THREAD

**Issue by nilsreichardt** [flutter/flutter#135389]
Unfortunately, I don't have a code snippet to reproduce. We got this error report via Crashlytics and it seems to me an issue with Flutter (if it's not a bug in Flutter it lags documentation on how to prevent it).

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value
       at State.context(framework.dart:957)
       at _DashboardPageFABState.openDashboardFabSheet(dashboard_fab.dart:46)
```

This is the simplified code that caused the error:

```dart
Future<void> openDashboardFabSheet(BuildContext buildContext) async {
  final fabResult = await showModalBottomSheet<_DashboardFabResult>(
    isDismissible: true,
    context: context,
    builder: (context) => _DashboardFabSheet(),
  );

  if (!context.mounted) return; // This line caused the error.
  
  // Do stuff
}
```

Full code: https://github.com/SharezoneApp/sharezone-app/blob/168f3689738b8d6a6bfaa0089fd40207b3afc651/app/lib/dashboard/widgets/dashboard_fab.dart#L46

As in the code snipped described caused `context.mounted` the error. This is the exact location that caused the error:

https://github.com/flutter/flutter/blob/797d34e5af10ced9fdb6ce08a70a7553c9accdce/packages/flutter/lib/src/widgets/framework.dart#L958C10-L958C10

Because I'm already using `context.mounted` I'm unsure how to prevent this issue.

It's related to https://github.com/flutter/flutter/issues/122073.

**Comment by huycozy** [comment]
Hi @nilsreichardt 
It would be better if the issue could be actionable with clear steps to reproduce it.

It looks like you are pushing to a new page while also opening a bottom sheet with `showModalBottomSheet`. I managed to copy the main flow of your code to the minimal sample below but the issue didn't occur. Please see if I'm missing anything on that.

<details>
<summary>Minimal sample code</summary>

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [showModalBottomSheet].

void main() => runApp(const BottomSheetApp());

class BottomSheetApp extends StatelessWidget {
  const BottomSheetApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('Bottom Sheet Sample')),
        body: const BottomSheetExample(),
      ),
    );
  }
}

class BottomSheetExample extends StatelessWidget {
  const BottomSheetExample({super.key});

  @override
  Widget build(BuildContext context) {
    return Center(
      child: ElevatedButton(
        child: const Text('showModalBottomSheet'),
        onPressed: () {
          _handleClick(context);
        },
      ),
    );
  }

  void _handleClick(context) {
    showModalBottomSheet<void>(
      showDragHandle: true,
      context: context,
      builder: (BuildContext context) {
        return SizedBox(
          height: 200,
          child: Center(
            child: ElevatedButton(
              child: const Text('Close BottomSheet'),
              onPressed: () => Navigator.pop(context),
            ),
          ),
        );
      },
    );
    if (!context.mounted) return;
    Navigator.push(
      context,
      MaterialPageRoute(builder: (context) => const SecondRoute()),
    );
  }
}

class SecondRoute extends StatelessWidget {
  const SecondRoute({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Second Route'),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            Navigator.pop(context);
          },
          child: const Text('Go back!'),
        ),
      ),
    );
  }
}

```
</details>

Also, could you share the entire crash stack trace if any?

If the issue is only reproduced in production, please also share the list of affected device info and the percentage occurrence of the crash. Thanks!

**Comment by nilsreichardt** [comment]
Hi, thanks for taking a look.

> It looks like you are pushing to a new page while also opening a bottom sheet with showModalBottomSheet. 

No, I first call `showModalBottomSheet`, I await until the bottom sheet has been closed and then I open a new page. (small note: this is also wrong in your minimal sample code because you don't await).

This the corrected minimal code snippet:

<details>

<summary>Code Snippet</summary>

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [showModalBottomSheet].

void main() => runApp(const BottomSheetApp());

class BottomSheetApp extends StatelessWidget {
  const BottomSheetApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('Bottom Sheet Sample')),
        body: const BottomSheetExample(),
      ),
    );
  }
}

class BottomSheetExample extends StatelessWidget {
  const BottomSheetExample({super.key});

  @override
  Widget build(BuildContext context) {
    return Center(
      child: ElevatedButton(
        child: const Text('showModalBottomSheet'),
        onPressed: () {
          _handleClick(context);
        },
      ),
    );
  }

  Future<void> _handleClick(context) async {
    await showModalBottomSheet<void>(
      showDragHandle: true,
      context: context,
      builder: (BuildContext context) {
        return SizedBox(
          height: 200,
          child: Center(
            child: ElevatedButton(
              child: const Text('Close BottomSheet'),
              onPressed: () => Navigator.pop(context),
            ),
          ),
        );
      },
    );
    if (!context.mounted) return;
    Navigator.push(
      context,
      MaterialPageRoute(builder: (context) => const SecondRoute()),
    );
  }
}

class SecondRoute extends StatelessWidget {
  const SecondRoute({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Second Route'),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            Navigator.pop(context);
          },
          child: const Text('Go back!'),
        ),
      ),
    );
  }
}
```

</details>

> Also, could you share the entire crash stack trace if any?

I already posted the entire stack in the issue. It says that the error has been thrown at (`State.context(framework.dart:957)`) inside the framework.

> If the issue is only reproduced in production, please also share the list of affected device info and the percentage occurrence of the crash. Thanks!

The thing is, that it is, in general, it's not reproducible. We have 40k MAU and only 6 users had this issue. The device information is:

* Google Pixel 4a, Android 13, RAM free:  1.37 GB, disk free: 10.39 GB, rooted: no
* Samsung Galaxy A71, Android 11, RAM free: 1.69 GB, disk free:  25.34 GB, rooted: no
* iPad Air (5th generation), iOS: 16.6.1, Jailbroken: no
* iPad Air (5th generation), iOS: 17.0.1, Jailbroken: no
* iPad (6th generation), iOS: 16.2.0, Jailbroken: no
* iPad (9th generation), iOS: 16.6.1, Jailbroken: no

**Comment by tapeo** [comment]
I was having a similar issue with the same exception, pay attention to the context, it needs to be alive when you use it for show modal or push routes. Maybe this can help

**Comment by nilsreichardt** [comment]
> pay attention to the context, it needs to be alive when you use it for show modal or push routes. Maybe this can help

Yeah, I know that this will be issue. However, I don't know, how to check this. The documented way is to use `context.mounted`. However, calling `context.mounted` causes the error because the error is thrown inside the `context` getter. This means, whenever I would touch `context`, I would get this issue.

**Comment by huycozy** [comment]
@nilsreichardt Thanks for the update. I checked your updated sample code again but still can't reproduce the exception. Looks like it's only reproducible in the production. Labeling this for more insights.

Please also share the Flutter version you deployed the app with (`flutter doctor -v`)

**Comment by huycozy** [comment]
Ah yes, thanks for the correction.

**Comment by goderbauer** [comment]
Looks like you are accessing the `context` on a `State` object, i.e. [State.context](https://master-api.flutter.dev/flutter/widgets/State/context.html)? That's only valid if the State is still valid. You can check whether the State is valid by checking [State.mounted](https://master-api.flutter.dev/flutter/widgets/State/mounted.html). So you probably just want to change `if (!context.mounted) return;` to `if (!mounted) return`.

Does that work for you?

**Comment by nilsreichardt** [comment]
I'll provide an update in the next weeks when we rolled out the next version.

**Comment by Reprevise** [comment]
> Looks like you are accessing the `context` on a `State` object, i.e. [State.context](https://master-api.flutter.dev/flutter/widgets/State/context.html)? That's only valid if the State is still valid. You can check whether the State is valid by checking [State.mounted](https://master-api.flutter.dev/flutter/widgets/State/mounted.html). So you probably just want to change `if (!context.mounted) return;` to `if (!mounted) return`.
> 
> Does that work for you?

@goderbauer While this works, I think it's a larger problem that users can fall into. Because there are really now _two_ ways to check for mounted, it gets confusing. So now do users have to check for `BuildContext.mounted` _and_ `State.mounted`? If so, that's more work than before.

**Comment by goderbauer** [comment]
Checking one of them is enough. We are working with the linter team to make the lint clearer: https://github.com/dart-lang/linter/issues/4777
