### ISSUE TITLE
Flutter uses wrong Apple certificate

### ISSUE THREAD

**Issue by AugustAxelsson** [flutter/flutter#135335]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Flutter run on a physical device, in my case iOS

### Expected results

Flutter is using the correct certificate for the run command. In this case --debug mode.

### Actual results

Im getting this result: Could not build the precompiled application for the device.
Error (Xcode): Target debug_unpack_ios failed: Exception: Failed to codesign
And I can see that it tries to use my ios distribution certificate.

And I have set up the correct certificates in Xcode for both debug, profile and release. 

### Code sample

<details><summary>Code sample</summary>

```dart
flutter run
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
Launching lib/main.dart on <name> in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project:
<identifyer>
Running pod install...                                             17.3s
Running Xcode build...                                                  
Xcode build done.                                           148.6s
Failed to build iOS app
Could not build the precompiled application for the device.
Error (Xcode): Target debug_unpack_ios failed: Exception: Failed to codesign
<path>/build/ios/Debug-iphoneos/Flutter.framework/Flu
tter with identity
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.5, on macOS 14.0 23A344 darwin-arm64, locale en-SE)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.82.2)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @AugustAxelsson 
Since you seem to be using XCode 15, can you check [this](https://github.com/flutter/flutter/issues/130639) similar issue and see if it resembles your case ?
