### ISSUE TITLE
IOS wireless debugging in VSCode

### ISSUE THREAD

**Issue by Kevin301099** [flutter/flutter#135380]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Run App on Iphone xs ios 17

### Expected results

 Run App wirelessly on  iphone xs and ios 17

### Actual results

The Dart VM Service was not discovered after 75 seconds. This is taking much longer than expected...
Open the Xcode window the project is opened in to ensure the app is running. If the app is not running, try selecting "Product > Run" to fix the problem.

Click "Allow" to the prompt asking if you would like to find and connect devices on your local network. This is required for wireless debugging. If you selected "Don't Allow", you can turn it on in Settings > Your App Name > Local Network. If you don't see your app in the Settings, uninstall the app and rerun to see the prompt again.

### Code sample

```
void main() {
  WidgetsBinding widgetsBinding = WidgetsFlutterBinding.ensureInitialized();
  FlutterNativeSplash.preserve(widgetsBinding: widgetsBinding);

  MediaKit.ensureInitialized();

  GestureBinding.instance.resamplingEnabled = true;

  Check_Internt_Connection();

  SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp])
      .then((_) {
    runApp(const MyApp());
  });
}
```

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.13.5, on macOS 14.0 23A339 darwin-arm64, locale
    en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.78.2)
[✓] VS Code (version 1.78.2)
[✓] Connected device (2 available)
[✓] Network resources

**Comment by Kevin301099** [comment]
using Xcode, wireless debug is working as normal

**Comment by darshankawar** [comment]
@Kevin301099 
Issues related to vscode need to be reported in dedicated repo: https://github.com/Dart-Code/Dart-Code/issues
Closing from here.

**Comment by RafaelZasas** [comment]
I've been having this issue a while now. Saying just run from Xcode isn't a valid solution, and neither is telling users to complain somewhere else. This is a flutter issue.
