### ISSUE TITLE
Add new Cupertino calendar date picker mod

### ISSUE THREAD

**Issue by laterdayi** [flutter/flutter#135356]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Add new Cupertino calendar date picker mod

### Proposal

Add new Cupertino calendar date picker mod

**Comment by danagbemava-nc** [comment]
Hi @laterdayi, kindly share a link to this new mode you are referring to. 

Thank you

**Comment by laterdayi** [comment]
@danagbemava-nc   https://github.com/flutter/flutter/issues/63693  Thank you for your help. This problem has existed for several years

**Comment by danagbemava-nc** [comment]
Kindly subscribe to the original issue for updates since it is already open. 

It will be worked on. 

Closing from here as duplicate.
