### ISSUE TITLE
please mention 'flutter pub get' in the creating project page of the my first flutter app codelab

### ISSUE THREAD

**Issue by sujithrajs** [flutter/flutter#135322]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

add flutter pub get

### Proposal

add flutter pub get

**Comment by darshankawar** [comment]
@sujithrajs 
Can you provide the codelab link and point to what exactly is the issue you are facing using it ?
