### ISSUE TITLE
Firestore plugin: support for merge:true in setData()

### ISSUE THREAD

**Issue by bjornbjorn** [flutter/flutter#13537]
From the Firestore docs:

> If the document does exist, its contents will be overwritten with the newly provided data, unless you specify that the data should be merged into the existing document, as follows:

https://firebase.google.com/docs/firestore/manage-data/add-data#set_a_document

```
var cityRef = db.collection('cities').doc('BJ');

var setWithMerge = cityRef.set({
    capital: true
}, { merge: true });
```

Please add this feature to Flutter's Firestore plugin.

**Comment by jonasbark** [comment]
https://github.com/flutter/plugins/commit/2b89c20924da181dd53f8ca4bdb79bca27823962
it was added 8 days ago.

**Comment by bjornbjorn** [comment]
Aha, sorry - I missed that!

Closing this issue then. Thanks @jonasbark
