### ISSUE TITLE
FormState validation method to return a Map of the validation status of children FormField(s)

### ISSUE THREAD

**Issue by SharbelOkzan** [flutter/flutter#135363]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

In a screen containing a relatively long `Form` in a `SingleChildScrollView`, we want to bring the user's attention to the field that may cause a validation error after calling `FormState.validate()`. The solution was as follows:
```
  void _validateForm(BuildContext context) {
    if (_fomKey.currentState!.validate()) {
      fun();
    } else {
      WidgetsBinding.instance.addPostFrameCallback((_) {
        if (_someWidgetKey.currentContext != null && _someWidgetKey.currentContext!.mounted) {
          Scrollable.ensureVisible(
            _someWidgetKey.currentContext!,
          );
        }
      });
    }
  }
```

Now the problem is that where there are multiple widgets that may cause a validation error. There's currently no way to detect which one we should scroll to.
The only solution is to implement a custom validation logic, which defies the whole purpose of using `Form`

### Proposal

The proposal is to have another version of the `validate` method, let's call it, `validateGranularly` (naming suggestions are very welcome) that returns `Map<Key, bool>`, so the above problem will be addressed as follows:

```
  void _validateForm(BuildContext context) {
    if (_fomKey.currentState!.validate()) {
      fun();
    } else {
      Key invalidFieldKey =  
      _fomKey.currentState!.validateGranularly().firstWehere((e) => !e) // e==false
      WidgetsBinding.instance.addPostFrameCallback((_) {
        if (invalidFieldKey .currentContext != null && invalidFieldKey .currentContext!.mounted) {
          Scrollable.ensureVisible(
            invalidFieldKey .currentContext!,
          );
        }
      });
    }
  }

**Comment by Renzo-Olivares** [comment]
Hi @SharbelOkzan thanks for proposing this new API. Your use-case sounds reasonable and we would welcome a PR which looks like you have already started https://github.com/flutter/flutter/pull/135578 so thanks!

**Comment by Renzo-Olivares** [comment]
Closing this as #135578 has been merged.
