### ISSUE TITLE
reimage linux-40

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#135312]
### Is there an existing issue for this?

- [X] I have searched the [existing infra issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-infra)

### Type of Request

infra task

### Infrastructure Environment

Devicelab

### What is happening?

linux-40 was used for some experiments, please completely reimage the linux OS on linux-40 device and connect a Pixel to it.

**Comment by kentnguyen99** [comment]
Reimage machine linux-40 has been completed. linux-40 is back online and ready for service.
