### ISSUE TITLE
Unable to upgrade/downgrade subscription on android using in_app_purchase

### ISSUE THREAD

**Issue by Samiksha-Garg** [flutter/flutter#135381]
### Is there an existing issue for this?

- [X] I have searched the [existing package issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Apackage)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### What package does this bug report belong to?

in_app_purchase

### What target platforms are you seeing this bug on?

Android

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
in_app_purchase: ^3.1.1
in_app_purchase_android: ^0.3.0+13
```
</details>

### Steps to reproduce

I am fetching past purchase details and as mentioned in the documentation I am providing the fetched details to `ChangeSubscriptionParam` to `PurchaseParam` with required `ProationMode`.

### Expected results

The subscription should downgrade and upgrade accordingly.

### Actual results

The error in console says : `Activity finished with resultCode 0 and billing's responseCode: 5`. 
The playstore sheet shows error : `Something went wrong on our end. Please try again`

### Code sample

<details><summary>Code sample</summary>

```dart
final platform = iapConnection
            .getPlatformAddition<InAppPurchaseAndroidPlatformAddition>();
        final pastPurchases = await platform.queryPastPurchases();

        GooglePlayPurchaseDetails? oldPurchaseDetails;

        // Assumes 1 or none active purchase.
        for (var purchase in pastPurchases.pastPurchases) {
          oldPurchaseDetails = purchase;
        }

        final purchaseParam = GooglePlayPurchaseParam(
            productDetails: event.productDetails,
            changeSubscriptionParam: oldPurchaseDetails != null
                ? ChangeSubscriptionParam(
                    oldPurchaseDetails: oldPurchaseDetails,
                    prorationMode: ProrationMode.deferred)
                : null);

        await iapConnection.buyNonConsumable(purchaseParam: purchaseParam);
```

</details>

### Screenshots or Videos

<details>
<summary>Screenshots / Video demonstration</summary>
<img width="349" alt="Screenshot 2023-09-24 at 4 50 41 PM" src="https://github.com/flutter/flutter/assets/79906086/372f8bf8-c978-4727-85c8-1558b815c9f3">

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
Activity finished with resultCode 0 and billing's responseCode: 5

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.5, on macOS 13.2.1 22D68 darwin-arm64, locale en-IN)
    • Flutter version 3.13.5 on channel stable at /Users/samikshagarg/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12fccda598 (5 days ago), 2023-09-19 13:56:11 -0700
    • Engine revision bd986c5ed2
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/samikshagarg/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (3 available)            
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30)
      (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 13.2.1 22D68
      darwin-arm64
    • Chrome (web)              • chrome        • web-javascript • Google Chrome
      116.0.5845.187

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by dam-ease** [comment]
Hi @Samiksha-Garg. Thanks for filing this. From the logs, the error message seems to be with  Invalid arguments being provided to the API, you might want to read up more on this [here](https://stackoverflow.com/questions/49993253/android-billing-i-receive-response-code-5) to see if it helps.

**Comment by Samiksha-Garg** [comment]
Hey @dam-ease, Purchasing a new subscription seems to work fine if I just don't try to upgrade/downgrade any existing subscriptions i.e 
```
final purchaseParam = GooglePlayPurchaseParam(
            productDetails: event.productDetails);

        await iapConnection.buyNonConsumable(purchaseParam: purchaseParam);
```
seems to work fine. Providing `ChangeSubscriptionParam` makes all the difference. I don't know what I am doing wrong and what different change I need to do for this.

**Comment by dam-ease** [comment]
Hi @Samiksha-Garg. Thanks for your response. 

> Providing ChangeSubscriptionParam makes all the difference

Can you provide more information on this, please?

**Comment by Samiksha-Garg** [comment]
I just mean that the error comes up when I provide `ChangeSubcriptionParam` to the `GooglePurchaseParam`, without providing it the purchase of subscription takes place successfully. But I want to upgrade/downgrade any existing subscription. @dam-ease

**Comment by Samiksha-Garg** [comment]
Hey, I figured out the reason for my error. So I was trying subscription model in India and has 3 subscription model set up however 2 of them were priced above 5000 because of which they were being treated as prepaid plan ([India's Subscription Rules](https://www.revenuecat.com/blog/engineering/indias-new-subscription-rules/#:~:text=back%20in%20May.-,Auto%2Drenewing%20subscription%20products%20will%20be%20capped%20below%205%2C000%20INR,are%20priced%20under%205%2C000%20INR)). And according to [documentation](https://developer.android.com/google/play/billing/subscriptions#change) When upgrading, downgrading to a prepaid plan from auto-renewing plan, the only allowed proration mode is `IMMEDIATE_AND_CHARGE_FULL_PRICE` and I was aiming for `DEFERED` proration mode, hence the error.
