### ISSUE TITLE
Flutter flashes black screen on Android when resuming activity

### ISSUE THREAD

**Issue by JackieLovesProgramming** [flutter/flutter#135379]
### Is there an existing issue for this?

- [x] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

when i run any flutter app on my android 9 phone and move the app to background and then resume it after seconds , app flashes a black screen for like 200ms. is there any way to fix it without causing other problems?
https://github.com/flutter/flutter/issues/59552#issuecomment-713374392
the above answer causes splash screen to flash a black screen instead , and fixes on resume problem. is there anyway of fixing this without causing another problem?

### Expected results

all other android apps that arent made with flutter , look ok. this only happens with flutter apps.

### Actual results

this is actually what happens :
https://github.com/flutter/flutter/issues/66212#issuecomment-704942497

### Code sample

<details><summary>Code sample</summary>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.3, on Microsoft Windows
    [Version 10.0.22000.2176], locale fa-IR)
[√] Windows Version (Installed version of Windows is version 10
    or higher)
Checking Android licenses is taking an unexpectedly long time..                                                               
[√] Android toolchain - develop for Android devices (Android
    SDK version 34.0.0)
[√] Chrome - develop for the web
[!] Visual Studio - develop Windows apps (Visual Studio        
    Community 2022 17.6.4)
    X Visual Studio is missing necessary components. Please
      re-run the Visual Studio installer for the "Desktop      
      development with C++" workload, and include these        
      components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available,
         install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[!] Android Studio (version 2022.2)
    X Unable to find bundled Java version.
[√] Android Studio (version 2022.3)
[√] IntelliJ IDEA Ultimate Edition (version 2023.1)
[√] Connected device (3 available)
[√] Network resources

**Comment by iapicca** [comment]
@JackieLovesProgramming the issue 
- https://github.com/flutter/flutter/issues/59552

is still **_open_**, could this problem be addressed there? (possibly with a code sample)

**Comment by darshankawar** [comment]
@JackieLovesProgramming 
You can follow-up in below similar issues for further updates:

https://github.com/flutter/flutter/issues/59552
https://github.com/flutter/flutter/issues/34864

Closing this as a duplicate. You can share your findings in above issues for better tracking.
