### ISSUE TITLE
[two_dimensional_scrollables] TableView is unable to scroll vertically if horizontal scrolling is impossible and diagonalDragBehavior is not set to `none`

### ISSUE THREAD

**Issue by Quijx** [flutter/flutter#135384]
### Summary
`TableView` from the `two_dimensional_scrollables` pacakge is unable to scroll vertically using gestures if horizontal scrolling is impossible (at first build) due to the width of the table being smaller than the width of the container and `diagonalDragBehavior` is set to `free`, `weightedEvent` or `weightedContinuous`.
Srolling works fine on desktop when a mouse wheel is used. This is only a problem with gestures.
~~I am unsure whether this is a bug in the `two_dimensional_scrollables` package or the `TwoDimensionalScrollView` in the framework.~~ PS: It is  a problem with `TwoDimensionalScrollView`. See comment.
@Piinks

### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a project using the provided code sample
2. Run it and try to scroll vertically using a gesture. (So if on desktop, not the scroll wheel)

### Expected results

- You should be able to scroll

### Actual results

- Is is not possible to scroll further down in the table even though there are many more elements below outside the viewport.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:two_dimensional_scrollables/two_dimensional_scrollables.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      // Just so we can see the bug on desktop too.
      builder: (context, child) {
        final scrollBehavior = ScrollConfiguration.of(context);
        return ScrollConfiguration(
          behavior: scrollBehavior.copyWith(
            dragDevices: {
              ...scrollBehavior.dragDevices,
              PointerDeviceKind.mouse,
            },
          ),
          child: child!,
        );
      },
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: const Text('TableView Bug'),
      ),
      body: TableView.builder(
        cellBuilder: (context, vicinity) {
          return const Text('hello');
        },
        diagonalDragBehavior: DiagonalDragBehavior.free,
        columnCount: 3,
        columnBuilder: (int column) =>
            const TableSpan(extent: FixedTableSpanExtent(64)),
        rowCount: 100,
        rowBuilder: (int row) =>
            const TableSpan(extent: FixedTableSpanExtent(64)),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/48153628/dc8920e4-89f3-465e-ba52-41c744ce0f65

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.5, on Antergos Linux 6.5.3-arch1-1, locale en_DE.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 3.5)
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2022.2)
[✓] IntelliJ IDEA Community Edition (version 2023.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by Quijx** [comment]
Actually I think this is a problem with flutters `TwoDimensionalScrollView`.
Using the example from #135305 at https://dartpad.dev/?id=4424936c57ed13093eb389123383e894 and changing the `maxXIndex` from `9` to `1` shows that you can't scroll vertically any longer as long as the browser window is wide enough to fit all columns.

**Comment by darshankawar** [comment]
@Quijx 


> Using the example from #135305 at https://dartpad.dev/?id=4424936c57ed13093eb389123383e894 and changing the `maxXIndex` from `9` to `1` shows that you can't scroll vertically any longer as long as the browser window is wide enough to fit all columns.

I tried this in dartpad itself and was able to scroll vertically as shown below:


https://github.com/flutter/flutter/assets/67046386/58e87f33-a86f-4a7f-b16a-8fe6486a9cf1

**Comment by Quijx** [comment]
@darshankawar You seem to be scrolling using the srollwheel. That works as expected. Try scrolling by dragging with the mouse. That should work in this example, because of the added
```dart
scrollBehavior: const MaterialScrollBehavior().copyWith(
        // Mouse dragging enabled for this demo
        dragDevices: PointerDeviceKind.values.toSet(),
      ),
```
at the start. It does work if `maxXIndex: 9` and incorrectly does not work if `maxXIndex: 1`.

**Comment by Piinks** [comment]
Hi @Quijx I think this is the same issue as reported in https://github.com/flutter/flutter/issues/133529
That already has a PR out to resolve it as well:  https://github.com/flutter/flutter/pull/133750 🎉 

Thanks for reporting! I am going to close this as a duplicate. :)
