### ISSUE TITLE
In Flutter, when implementing the dark mode feature, the keyboard appearance does not change to dark mode when the system is using light mode. It remains in light mode when the keyboard is open

### ISSUE THREAD

**Issue by prituljogiya** [flutter/flutter#135488]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

When the system is in dark mode, the keyboard appearance follows the system settings. However, if the system is in light mode and the app is set to dark mode, the keyboard will be displayed in dark mode

### Expected results

![Screenshot_1695710611](https://github.com/flutter/flutter/assets/99915409/bf86150f-2121-4acc-9aeb-6930af30214d)

keyboard show in dark mode

### Actual results

![Screenshot_1695710611](https://github.com/flutter/flutter/assets/99915409/bf86150f-2121-4acc-9aeb-6930af30214d)

### Code sample

keyboardApperence  : themeData == darkmode ? Brightness.dark: Brightness.light

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<img width="1270" alt="Screenshot 2023-09-26 at 12 20 11 PM" src="https://github.com/flutter/flutter/assets/99915409/bf2bc041-99e5-41d2-851d-d2d0e8052d34">

**Comment by prituljogiya** [comment]
![Screenshot_1695711338](https://github.com/flutter/flutter/assets/99915409/28783147-9b84-4c73-a107-4f1503a56fa7)
 
 
 actual output

**Comment by dam-ease** [comment]
Hi @prituljogiya. I can't seem to reproduce this on the latest versions of flutter. Are you able to upgrade to the latest versions to check if this issue still persists? If it does, kindly provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code (a single `main.dart` file)?
Thank you
