### ISSUE TITLE
On screen keyboard pops up abnormally on touch screen tablets

### ISSUE THREAD

**Issue by nishat-nasir** [flutter/flutter#135492]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

If you run the app on Windows tablet mode and tap on textInputField, when the focus is there, once the keyboard appears, it doesn't unfocus. I think the problem is unfocused doesn't work on Windows.

Also if you close by tapping on the cross and touch it somewhere else, it keeps coming no matter where you tap. 

However, if there is a dropdown button and you tap on it, then only it gets unfocused.

### Expected results

When tap on anywhere else it should be unfocused.

### Actual results

Once the onscreen keyboard appears, it doesn't close. Also if you close by tapping on the cross and touch it somewhere else, it keeps coming no matter where you tap. 

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Hi @nishat-nasir 
Could you share a recorded video to illustrate the issue? And please provide the output of `flutter doctor -v` as well. Thanks!
