### ISSUE TITLE
I had some errors to start flutter project.

### ISSUE THREAD

**Issue by donuthappy** [flutter/flutter#135451]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

flutter run -d chrome

### Actual results

```
The platformViewRegistry getter is deprecated and will be removed in a future release. Please import it from `dart:ui_web` instead.
The platformViewRegistry getter is deprecated and will be removed in a future release. Please import it from `dart:ui_web` instead.
```

Flutter version 3.13.5
Dart 3.1.2

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.5, on Microsoft Windows [Version 10.0.19044.3086], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.5)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.82.2)
[√] Connected device (3 available)
[√] Network resources

**Comment by danagbemava-nc** [comment]
Hi @donuthappy, please provide a complete minimal reproducible code sample so that we can investigate this issue. 

Thank you
