### ISSUE TITLE
TabController animateTo Not Working as Expected on Specific Devices

### ISSUE THREAD

**Issue by 6cessfuldev** [flutter/flutter#135421]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

When using TabController with a specified initialIndex and trying to animate to a different tab using animateTo() inside a WidgetsBinding.instance.addPostFrameCallback, I've observed inconsistent behavior across different devices. On some devices, the animation successfully navigates to the target tab, while on others, it appears to halt on an intermediate tab.

0. Device and Android API Versions make trouble.(could be more).
-Pixel 6a android API 34
-Pixel 2 android API 33
-Pixel XL android API 34

1. Create a TabController with an initialIndex set to 2 (i.e., the third tab).
2. Use WidgetsBinding.instance.addPostFrameCallback to animate to the first tab immediately after initialization.
3. Observe the final tab shown on the screen.

When moving more than two tabs using tabController.animateTo, the TabBarView's PageController first uses jumpToPage to move to an adjacent page and then executes animateToPage. However, while jumpToPage is executed, animateToPage does not, leading to a bug. In cases where it stops at index 1, a DrivenScrollActivity is registered in beginActivity in ScrollActivity, but it immediately transitions to BallisticScrollActivity and ends.

While I am aware of workarounds for this issue, such as using Future.delayed or fetching the source code of TabBarView to avoid using animateToPage and instead use jumpToPage to skip the animation, I would like to understand the root cause of this problem.

### Expected results

Regardless of the device, the animation should consistently navigate to the first tab.

### Actual results

On certain devices, the animation stops at the second tab, despite the call to animate to the first tab.
TabController animateTo 

### Code sample

```
class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> with SingleTickerProviderStateMixin {
  late TabController _tabController;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 3, vsync: this, initialIndex: 2);

    WidgetsBinding.instance!.addPostFrameCallback((_) {
      _tabController.animateTo(0);
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: TabBarView(
        controller: _tabController,
        physics: const NeverScrollableScrollPhysics(),
        children: const [
          Center(child: Text('Tab 1')),
          Center(child: Text('Tab 2')),
          ThirdPage(),
        ],
      ),
    );
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }
}

class ThirdPage extends StatefulWidget {
  const ThirdPage({super.key});
  @override
  State<ThirdPage> createState() => _ThirdPageState();
}

class _ThirdPageState extends State<ThirdPage> {

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
        child: Text('Tab 3'),
      ),
    );
  }
}
```

### Flutter Doctor output

```
[!] Flutter (Channel unknown, 3.3.1, on macOS 13.5.1 22G90 darwin-arm, locale ko-KR)
    ! Flutter version 3.3.1 on channel unknown at /Users/yugseongmin/flutter
    ! Upstream repository unknown
    • Framework revision 4f9d92fbbd (1 year, 1 month ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/yugseongmin/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.80.1)
    • VS Code at /Users/yugseongmin/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0
[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 14 (API 34) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.5.1 22G90 darwin-arm
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 116.0.5845.187

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

```

**Comment by darshankawar** [comment]
> Channel unknown, 3.3.1

@6cessfuldev You are on obsolete version of the framework. Current version is 3.13.5. I recommend to upgrade to latest version and run your scenario again to check if the behavior still persists or not. 
I'll close it for now, as the version this issue is reported on is very old . If you disagree, write in comments and I'll reopen it.

**Comment by 6cessfuldev** [comment]
Thank you, @darshankawar, for your suggestion. I've tested this on the latest version, 3.13.5, as you recommended. However, I'm still encountering the same error. Can we reopen the issue to further investigate this on the current version?

this is flutter doctor -v result.

[!] Flutter (Channel stable, 3.13.5, on macOS 13.5.1 22G90 darwin-arm64, locale ko-KR)
    • Flutter version 3.13.5 on channel stable at /Users/yugseongmin/flutter_3.13.5-stable/flutter
    ! Warning: `flutter` on your path resolves to /Users/yugseongmin/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/yugseongmin/flutter_3.13.5-stable/flutter. Consider
      adding /Users/yugseongmin/flutter_3.13.5-stable/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/yugseongmin/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/yugseongmin/flutter_3.13.5-stable/flutter. Consider adding
      /Users/yugseongmin/flutter_3.13.5-stable/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12fccda598 (7일 전), 2023-09-19 13:56:11 -0700
    • Engine revision bd986c5ed2
    • Dart version 3.1.2
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/yugseongmin/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.80.1)
    • VS Code at /Users/yugseongmin/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 14 (API 34) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.5.1 22G90 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 116.0.5845.187

[✓] Network resources
    • All expected network resources are available.

**Comment by darshankawar** [comment]
Check https://github.com/flutter/flutter/issues/16892 and see if it resembles your case or not.
