### ISSUE TITLE
devicelab bot win-13 dead

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#135433]
### Is there an existing issue for this?

- [X] I have searched the [existing infra issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-infra)

### Type of Request

infra task

### Infrastructure Environment

devicelab

### What is happening?

Please check on devicelab win-13 bot, which is showing up as dead for the last hour.

### Steps to reproduce

Step 1:
Step 2:
..
Step n:

### Expected results

I expect to see X when Y is finished.

**Comment by kentnguyen99** [comment]
Machine is back online and running. Restart service on network adapter due it was disabled.
