### ISSUE TITLE
[CP] Regression Imagefilter.blur fix

### ISSUE THREAD

**Issue by remonh87** [flutter/flutter#135429]
### Issue Link

https://github.com/flutter/flutter/issues/132838

### Commit Hash

d38eb4acf6457104fb028336bc4cdd2fcb872337

### Target

stable

### PR Link

https://github.com/flutter/engine/pull/46271

### Changelog Description

Fix clip Imagefilter.blur on iOS (regression from version 3.10).

### Impacted Users

All users that use ImageFilter.blur on Flutter 3.13

### Impact Description

Visual degradation for everyone that upgrades from Flutter 3.10 to 3.13 and is using ImageFilter.blur. 

3.10
![Simulator Screenshot - iPhone 14 Pro Max - 2023-09-25 at 15 30 54](https://github.com/flutter/flutter/assets/20230599/06063af1-c5f0-43a7-9db5-1abac9369544)

3.13
![Simulator Screenshot - iPhone 14 Pro Max - 2023-09-25 at 15 28 25](https://github.com/flutter/flutter/assets/20230599/60b8f49e-008b-48ff-a301-597d131d9177)

### Workaround

No

### Risk

low

### Test Coverage

yes

### Validation Steps

You can use https://github.com/remonh87/backdrop_repo to test whether this fix works by running the app.

**Comment by itsjustkevin** [comment]
@flar and @jason-simmons could you take a look at this cherry-pick request?

**Comment by CaseyHillers** [comment]
@remonh87 in the PR link, can you update it to an open CP PR that is open against the flutter-3.13-candidate.0 branch? Thanks!

**Comment by remonh87** [comment]
@CaseyHillers  can you explain me how to do this since this is a fix in the flutter engine or can I just create the PR for that submodule?

**Comment by CaseyHillers** [comment]
```
git fetch --all
git checkout upstream/flutter-3.13-candidate.0 --track
git cherry-pick d38eb4acf6457104fb028336bc4cdd2fcb872337
# If needed, resolve any merge conflicts
git push origin HEAD
# Open the CP PR and update the issue
```

**Comment by remonh87** [comment]
@flar  updated the ticket and linked the pr.

**Comment by flar** [comment]
Just double checking that the test case was verified with this fix. Without having run the test case, the changes in this CP fix shouldn't have the impact of fixing the original problem AFAICT. They won't hurt anything, but they don't fix the clipping of the rendering of the blurs - they only fix the bounds rejection of the content of the blurs.

**Comment by remonh87** [comment]
@CaseyHillers  @flar  thanks for help integrating the fix.  I just tested the repo on the `flutter-3.13-candidate.0` branch and the issue is gone. I do not know if this is because of this CP or other fixes. At least this can be closed now
