### ISSUE TITLE
Developer Logs Not Working for 'log' Statements in 'Run Without Debugging' Mode

### ISSUE THREAD

**Issue by hsynshnl** [flutter/flutter#135445]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I've updated my Flutter version to **3.13.5**, 
and I'm encountering an issue where the 'log' statements, example `log("list $list");` 
are not functioning as expected in `"Run Without Debugging"` mode. 
However, I can view the logs when I use the `"Start Debugging"` mode. 
It used to work in `"Without Debugging"` mode as well.

### Expected results

Expected results: In `"Run Without Debugging"` mode, the 'log' statements, example` log("list $list");` 
should display the expected logs as they did before the Flutter version update.

### Actual results

Actual results: In `"Run Without Debugging"` mode, the 'log' statements, example `log("list $list");` are not displaying any logs, whereas they used to work correctly before the Flutter version update.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'dart:developer';

import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Material App Bar'),
        ),
        body: Center(
          child: ElevatedButton(
            onPressed: () {
              List<String> list = ["Example", "Example2", "Example3", "Example4"];
              log("list $list"); // TODO: Run Without Debugging mode doesn't work, but it works in Start Debugging mode. log func
            },
            child: const Text("Click Me"),
          ),
        ),
      ),
    );
  }
}


```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.5, on macOS 13.6 22G120 darwin-arm64
    (Rosetta), locale tr-TR)
    • Flutter version 3.13.5 on channel stable at
      /Users/huseyinsahinli/FlutterDev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12fccda598 (6 days ago), 2023-09-19 13:56:11 -0700
    • Engine revision bd986c5ed2
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/huseyinsahinli/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • EB36E91E-9973-464B-8E37-F1BB615B0396 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)        • macos                                •
      darwin-arm64   • macOS 13.6 22G120 darwin-arm64 (Rosetta)
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 117.0.5938.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@hsynshnl 
Are you using Android Studio or VSCode ?

**Comment by hsynshnl** [comment]
@darshankawar VSCode but this setting is on.
![Ekran Resmi 2023-09-26 11 00 59](https://github.com/flutter/flutter/assets/43808862/d9e0a299-8f38-4d53-8c04-f28d23f776a3)

**Comment by darshankawar** [comment]
I think this will need to be reported in dedicated repo: https://github.com/Dart-Code/Dart-Code/issues

Closing from here.

**Comment by Aravindhsiva** [comment]
Do we have any followup on this issue, Couldn't find any updates in [Dart-Code Link](https://github.com/Dart-Code/Dart-Code/issues) as well
