### ISSUE TITLE
Rebuilding issue when I declare MediaQuery within the build function.

### ISSUE THREAD

**Issue by VISHNUPRABHAKARAN-7100** [flutter/flutter#135400]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a normal stateless widget.
2. Write MediaQuery within the build function.
3. The MediaQuery is final Size size = MediaQuery.of(context).size;
4. Write a log within the build function log('Build function called');.
5. Write a column on the body of the Scaffold.
6. Set mainAxisAlignment to center.
7. Create a textformfiled.
8.  Open/ Focus the textformfiled then the build function will rebuild multiple times.
9. I understood that it is because, of a change in the size of the device screen when I open the textformfiled.

### Expected results

The build function should not call when I open/ Focus the textformfiled.

### Actual results

The build function is calling minium of 10 times when I open the textformfiled.

### Code sample

```dart

import 'package:bug_fix/home_screen.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: HomeScreen(),
    );
  }
}


import 'dart:developer';
import 'package:flutter/material.dart';

class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    log('Building home screen');
// Variable to find the size of the device screen.
    final Size size = MediaQuery.of(context).size;
    return Scaffold(
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          TextFormField(),
        ],
      ),
    );
  }
}

``` 

### Screenshots or Video

![bug](https://github.com/flutter/flutter/assets/110176330/080204c1-0347-41a8-9485-f0d3f58815b2)

### Logs

Building home screen

### Flutter Doctor output

![image](https://github.com/flutter/flutter/assets/110176330/bfcc7eb1-0b9b-49dc-858a-8bca08f75bd9)

Microsoft Windows [Version 10.0.22621.2283]
(c) Microsoft Corporation. All rights reserved.

C:\Users\VISHNU PRABHAKARAN>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
```
[√] Flutter (Channel stable, 3.13.5, on Microsoft Windows [Version 10.0.22621.2283], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.2)
[√] VS Code (version 1.82.2)
[√] Connected device (4 available)
[√] Network resources

! Doctor found issues in 1 category.

C:\Users\VISHNU PRABHAKARAN>
```

**Comment by dam-ease** [comment]
Hi @VISHNUPRABHAKARAN-7100. Thanks for filing this. There seems to be a currently open issue similar/related to the case you are describing. Can you check out https://github.com/flutter/flutter/issues/105184 to see if it's similar to yours?

**Comment by VISHNUPRABHAKARAN-7100** [comment]
@dam-ease
Thanks for your help,
Sir,
I got the solutions for this issue.

From Flutter 3.10 and above,
Replace:
final size = MediaQuery.of(context).size;
with
final size = MediaQuery.SizeOf(context);
