### ISSUE TITLE
Allow `Sliver`s to be zoomed more easily

### ISSUE THREAD

**Issue by yakagami** [flutter/flutter#135482]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Create a simple way for something like a `ListView` to be pinch-zoomed. This is a somewhat common pattern with a list of vertical images. If the images contain text then a user may want to zoom the entire list itself rather than each image when the user gets to it. Two concrete examples I can think of are a comic reader and reviewing a list of documents before submitting them. In the case of the former I am aware of at least one flutter app with millions of installs that already does this (not affiliated). Since that app is not open source I don't know how they did it but I suspect that they may have written their own custom `Viewport` for it. As for ways which this can be done now, they are all somewhat limited. The most obvious place to start would be a `ListView` warped in a `InteractiveViewer`: 
<details open>

<summary>naive method</summary>

```dart
InteractiveViewer(
  child: ListView.builder(
    itemCount: 100,
    itemBuilder: (context, index) {
      return Center(child: Text("text $index"));
    }
  ),
)
```
</details>

<details>

<summary>naive method video</summary>

https://github.com/flutter/flutter/assets/92773903/a6ccd7e3-160f-457b-a3ef-f71fbe7db99b

</details>

There is a major issue with this method, however.  The  zoom event in the `InteractiveViewer` may be swallowed by the `ListView` scroll physics. (https://github.com/flutter/flutter/issues/65006) This can be solved by setting `physics` to `NeverScrollableScrollPhysics()`  when two fingers are on the screen using a `Listener` widget (https://cloud.tencent.com/developer/ask/sof/107381999). 

<details>

<summary>Listener solution</summary>

```dart
Listener(
  onPointerDown: (event) {
    events.add(event.pointer);
    print("new event");
  },
  onPointerUp: (event) {
    events.clear();
    print("events cleared");
    setState(() {
      canScroll = true;
    });
  },
  onPointerMove: (event) {
    if (events.length == 2) {
      setState(() {
        canScroll = false;
      });
    }
  },
  child: SizedBox(
    height: 600,
    width: 300,
    child: InteractiveViewer(
      child: ListView.builder(
          physics:  canScroll
              ? const ScrollPhysics()
              : const NeverScrollableScrollPhysics(),
          itemCount: 10000000,
          itemBuilder: (context, index) {
            return Container(
              //enable to observe that the list rebuilds on every scroll
              //color: Colors.primaries[Random().nextInt(Colors.primaries.length)],
              child: Center(
                  child: Text("text $index")
              ),
            );
          }
      ),
    ),
  ),
)
```
</details>

<details>

<summary>Listener method video</summary>

https://github.com/flutter/flutter/assets/92773903/9a0e1017-d7b4-4aa9-98b0-ad1b58a50af7

</details>

There are still some more major issues:
1. sometimes the `ListView` is scrolling, meaning that you can't pan diagonally (as we are not panning at all, rather scrolling) and sometimes the `InteractiveViewer` is "scrolling" (ie. panning) meaning that it will run out of available view to scroll and not continue down the list. (Usually the Listview is in control.) This is shown in the above video.
2. When zoomed in you cannot pan to the top of the viewport, meaning you cannot view the first 10 px or so of the list.  (https://github.com/flutter/flutter/issues/68073). Observed in the above video.
3. The list is rebuilt on every scroll (enable the color in the container to observe). This turned out to be the worst drawback of all listed here. It is caused by the rebuild and this problem exists with zoom_widget as well which also needs the Listener workaround. I should mention that I am not using a plain List in production and this could be why performance is worse there as the build may be more expensive. I am also using images in the production list so that could be why. The examples given here already exhibit the other three issues however so I don't think the usecase should be rejected because of this fact. Removing the `Listener` makes the list mostly smooth again, but recreates the first issue.  Adding "`SingleFingerScrollPhysics`" or something to `ListView` could help here. This isn't a great general solution though. Implementing (https://github.com/flutter/flutter/issues/65006#issuecomment-858590637) for `InteractiveViewer` is slightly better.
4. It needs a set height (there are ways to solve this, however, perhaps with `LayoutBuilder` or similar)
 
One package sugested in some stackoverflow posts is https://pub.dev/packages/photo_view but this has an issue when trying to scroll a list as well (https://github.com/bluefireteam/photo_view/issues/392).

Combining the `Listener` method with the `Zoom` widget (https://pub.dev/packages/zoom_widget) fixes the second issue (and creates some new ones).

<details>
<summary>Zoom solution</summary>

```dart
import 'dart:math';
import 'package:flutter/material.dart';
import 'package:zoom_widget/zoom_widget.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final events = [];
  bool canScroll = true;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Listener(
          onPointerDown: (event) {
            events.add(event.pointer);
            print("new event");
          },
          onPointerUp: (event) {
            events.clear();
            print("events cleared");
            setState(() {
              canScroll = true;
            });
          },
          onPointerMove: (event) {
            if (events.length == 2) {
              setState(() {
                canScroll = false;
              });
            }
          },
          child: Zoom(
            maxZoomWidth: MediaQuery.of(context).size.width,
            opacityScrollBars: 0.0,
            centerOnScale: true,
            maxZoomHeight: 600,
            doubleTapZoom: true,
            enableScroll: true,
            child: ListView.builder(
                physics:  canScroll
                    ? const ScrollPhysics()
                    : const NeverScrollableScrollPhysics(),
                itemCount: 10000000,
                itemBuilder: (context, index) {
                  return Container(
                    //enable to observe that the list rebuilds on every scroll
                    //color: Colors.primaries[Random().nextInt(Colors.primaries.length)],
                    child: Center(
                        child: Text("text $index")
                    ),
                  );
                }
            ),
          ),
        )
    );
  }
}
```
</details>

I think in general this warrants a more first class method – I believe this is handled 'natively' in android `RecyclerVIew` with `ScaleGestureDetector` and with `UIScrollView` with `UIImageView` on iOS (comments here welcome, I haven't tested either of these).  Consider that zooming "just works" on web browsers, and must be actively disabled by the developer to change that behavior (not to say we need to act like browsers by default, mobile apps admittedly generally _don't_ need to be zoomed).

this seems to be a somewhat popular request:

https://stackoverflow.com/questions/73538288/flutter-how-to-create-list-of-zoomable-images
https://stackoverflow.com/questions/76777474/vertical-direction-zooming-not-working-when-listview-is-wrapped-with-interactive
https://stackoverflow.com/questions/76331178/how-to-pinch-to-zoom-listview-in-flutter
https://stackoverflow.com/questions/68392068/could-not-complete-vertical-scroll-of-listview-inside-interactiveviewer
https://stackoverflow.com/questions/64326715/flutter-interactiveviewer-doesnt-show-top-bottom-of-listview-when-panenabled
https://stackoverflow.com/questions/71898754/pinch-to-zoom-listview-in-flutter

### Proposal

To me there seems to be three ways to solve this. The first, which is the most simple method, is to add some extra argument to each sliver enabling or disabling zooming. I don't know how this would work with multiple slivers though, so it doesn't seem ideal. The second to to add an argument to `CustomScrollView` that allows zooming. This seems like where the option _should_ be, from a user perspective, but I can't say it how feasible that is. The third is some new widget, for example, `ZoomView`, that allows all its children to be both zoomed and scrolled. I would much prefer the last solution because it can work with existing custom scrolling widgets that people may already be using for navigation, for example. Here's what that would look like:

```dart
ZoomView(
  maxZoomWidth: maxZoomWidth, //some options to possibly add to this widget
  maxZoomHeight: maxZoomHeight,
  opacityScrollBars: opacityScrollBars,
  doubleTapZoom: true,
  child: ListView.builder(
      physics:  const ScrollPhysics() //no need to do anything here
      itemCount: 10000000,
      itemBuilder: (context, index) {
        return Container(
          //enable to observe that the list rebuilds on every scroll
          //color: Colors.primaries[Random().nextInt(Colors.primaries.length)],
          child: Center(
              child: Text("text $index")
          ),
        );
      }
  )
)
```

The zoom view would know that two fingers always sets the zoom scale (rather than equal the vectors out as is the case with flutter scrolling in general, see https://github.com/flutter/flutter/issues/11884#issuecomment-1624431066). It would not distinguish between scrolling the viewport and panning the current view of the viewport – it would always scroll. To me, that seems to be the difference between `InteractiveViewer` and the proposed `ZoomView`. `InteractiveViewer` pans an image while `ZoomVIew` zooms an existing viewport. One last point that I want to make is that `InteractiveViewer.builder` is not a good option on its own because it doesn't help with existing `CustomScrollView` lists. We should be able to make an existing viewport zoomable with as little work as possible. This would allow this to work with existing packages like eg. https://pub.dev/packages/scrollable_positioned_list , https://pub.dev/packages/grouped_list ect. The decision for a given list to be zoomable is not so great that it should warrant a separate widget. 

edit: I wrote a package here https://pub.dev/packages/zoom_view

**Comment by moffatman** [comment]
I don't really understand the proposal. What's preventing you from just using InteractiveViewer if you want a pannable and zoomable viewport? Scrolling is just the 1-dimensional form of 2D panning, you are always going to have some conflict if you use two different widgets for that.

**Comment by yakagami** [comment]
@moffatman  I am using https://pub.dev/packages/scrollable_positioned_list so I can't easily switch to `InteractiveViewer`. But in general it is a common pattern for lists to be used multiple times. Suppose I create a list and now I want to make it zoomable on one screen and not the other? Now consider if I have a large page as a widget that contains more widgets, one of which is a list. Now I want to create that page somewhere else but with zooming. How would I do this now? It would be better to just make this a parameter somewhere that I can change. The same way all the current scrolling physics properties are not seperate widgets, there should be a way to change the viewport zooming behavior. From a user perspective, these shouldn't be different things. Also I may be wrong on this but there are some differences between InteractiveViewer.builder and listview. For example I beleive the is no cachExtent for InteractiveViewer which can cause pop-in (see https://youtube.com/watch?v=qax_nOpgz7E from the flutter youtube channel for an example).

**Comment by moffatman** [comment]
Forwarding / swallowing inputs to subtrees is not possible today as far as I know.

So what should the Sliver do if its ancestor ZoomView starts getting zoomed. Just start expanding greater than its "natural" size in the vertical direction only. Or will it also introduce horizontal scrolling too?

Sorry for all these questions, maybe if you know of an interface that exists today with this principle I can try, to get a better idea.

**Comment by yakagami** [comment]
Thanks for your comment. That's a good point about forwarding inputs – I may open a separate issue for that to see if there is demand for that sort of feature. To answer your question about what the sliver should do: in the abstract, the sliver (or list of slivers, as in `CustomScrollView` ect.) should scroll when the users scrolls in the Sliver's `scrollAxis`. When the user zooms in, the Sliver should do nothing as the no new items need to be built. (Not sure how zooming out would work, this can be done in android wher you zoom out in `RecylcerView` and that will build more of the view as needed. We can ignore this for now though). When the users has zoomed in, and then scrolls horizontally (or, more accurately, in the cross axis), the Sliver should also not have to build anything as there is no new data. This is basically what already exists in the above `Listener` solution and the related source-code change for two finger event handling linked above as the `List` does not compete for `crossAxis` scrolls the `InteractiveViewer` wins when the `crossAxis` is scrolled and the `List` wins every time the `mainAxis` is scrolled with one finger. The issue arises, however, with diagonal panning. If I scroll diagonally, I need to both pan the current view and scroll and update the `List`. Currently when the user reaches the end of the `List`s `cacheExtent` the view can no longer be scrolled as we are really just panning the `cacheExtent` . (In fact, I'm not even sure if the `InteractiveView` goes into the `Sliver`s `cacheExtent` at all.) So in this case we need to scroll the `InteractiveViewer`/`ZoomView` as well as the `Sliver`.

Basically, the issue seems to be that `Sliver`s do three things: they take inputs, they scroll and they build new items when the result of their scrolling means the `cacheExtent` is lower than it minimum. Now if there was a way to tell the the Sliver "scroll such that you are x px down" using some function of the Sliver, say `scrollController` with `animateTo()`, then we could let `ZoomView` handle taking inputs, compute the change indicated by the user input to the `Sliver`s scroll axis, and then send *that* to the `Sliver` (and not the raw input), that would also work. I don't know what the performance implications of updating `ScrollController` every millisecond is though – probably not great. But abstractly that would work if the communication was there, not necessarily through  `ScrollController`.

The other way is `ZoomView` just tells the `Sliver` to become zoomable and nothing more. Truthfully this doesn't sound feasible and I think goes against the general widget structute. But it would be essentially akin to something like `ThemeData` or `SelectableText`. When the `Sliver` is built it should know that it's ancestor is a `ZoomView`, meaning that it should become a 2d viewport. I don't really like this idea and don't know if it would work or how.

**Comment by moffatman** [comment]
A `Sliver` does not position itself, that's up to its parent. The `Scrollable`, either `CustomScrollView` or `ListView` or whatever. `Sliver` is just a specialization of `RenderObject` protocol for 1D layout. Pretty much of the code changes of your proposed solution would be at that level, each `Sliver` should be kind of oblivious to whether it's in the true viewport or sub-viewport (zoomable/pannable). There is some effort ongoing at the moment about 2D scrollables, but not zooming at all as far as I know.

I think this would live as an alternative to `ScrollView` -> `Viewport`. Would need to be a `ZoomingScrollView` -> `Zooming1DViewport`. Or you could have it as an option on `ScrollView`, like how it might use `ShrinkWrappingViewport` if you set `shrinkWrap: true`. Also need to adjust `Scrollable` to handle scale gesture, and any gesture momentum simulation there too. 

I suggest that because nesting multiple viewports is not good, as you found, you have to drop the lazy loading in the inner level and make it a dumb tall rectangle. Which is too big of a performance hit.

**Comment by yakagami** [comment]
Thanks. I may just edit https://pub.dev/packages/scrollable_positioned_list to use `InteractiveViewer`. It may interest you that the app I mentioned with millions of installs is actually also broken in the same way I describe already: when you too much in a zoomed in view you actually run out of the `Sliver` and can no longer view new content. You can get into both states actually: a state wher you cannot pan in the `crossAxis` and a state where you cannot pan in the `mainAxis`. I suspect that they are using something like a `ListView` with with `InteractiveViewer`. It fails slightly less often but now that I know what to look for I can trigger it pretty easily. The app is [bilibili comics](https://play.google.com/store/apps/details?id=com.bilibili.comic.intl) with 10m+ installs. so I think that shows if nothing else that this is a common pattern and that developers use `Listview` to describe the lazy build method and not to represent a 1d viewport in specific, highlighting why this feature is needed.

**Comment by hgraceb** [comment]
> I suspect that they are using something like a ListView with InteractiveViewer.

I can share a solution that can achieve similar effects to what you said.

1. Rewrite `_onScaleStart`, `_onScaleUpdate`, `onScaleEnd` in `InteractiveViewer`.

```dart
return Listener(
  key: _parentKey,
  onPointerSignal: _receivedPointerSignal,
  child: GestureDetector(
    behavior: HitTestBehavior.opaque, // Necessary when panning off screen.
    onScaleEnd: _onScaleEnd,
    onScaleStart: _onScaleStart,
    onScaleUpdate: _onScaleUpdate,
    trackpadScrollCausesScale: widget.trackpadScrollCausesScale,
    trackpadScrollToScaleFactor: Offset(0, -1/widget.scaleFactor),
    child: child,
  ),
);
```

2. Using `Drag` to simulate scrolling of `ListView`.

```dart
drag ??= _listScrollController.position.drag(DragStartDetails());
```

3. And then, there are so many different ways to improve the solution. Such as you can base on `transformationController`'s value to decide what should you start to drag the list or not.

```dart
_drag!.update(DragUpdateDetails(
  globalPosition: details.focalPoint,
  delta: Offset(0, primaryDelta),
  primaryDelta: primaryDelta,
));
```

**Comment by yakagami** [comment]
@hgraceb Thanks but I actually already solved this problem by just exposing the `position` of the `ListView` in a custom `ScrollController` and then applying a `VelocityTracker` to the offset from the `ScaleUpdateDetails` of the `InteractiveViewer` and feeding that to the `position` of the `ListView`s `ScrollController`. I plan to make a package for this at some point.

**Comment by hgraceb** [comment]
@yakagami That's awesome. I'm looking forward to it. I've never seen a useable solution excluding that I was using.

**Comment by yakagami** [comment]
@hgraceb  here's a full example:

```dart

import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';


void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const Scaffold(
        body: ControllerInteractiveExample(),
      )
    );
  }
}



class ControllerInteractiveExample extends StatefulWidget {
  const ControllerInteractiveExample({super.key});

  @override
  State<ControllerInteractiveExample> createState() => _ControllerInteractiveExampleState();
}

class _ControllerInteractiveExampleState extends State<ControllerInteractiveExample> {
  DirectlySrollableScrollController customScroller = DirectlySrollableScrollController();
  TransformationController transformationController = TransformationController();

  @override
  Widget build(BuildContext context) {
    VelocityTracker tracker = VelocityTracker.withKind(PointerDeviceKind.touch);
    return SizedBox(
      width: 350,
      child: InteractiveViewer(
        transformationController: transformationController,
        onInteractionStart: (ScaleStartDetails details){
          if(details.pointerCount == 1){
            DragStartDetails dragDetails = DragStartDetails(
                globalPosition: details.focalPoint,
                kind: PointerDeviceKind.touch
            );
            customScroller.handleDragStart(dragDetails);
          }
        },
        onInteractionUpdate: (ScaleUpdateDetails details){
          if(details.pointerCount == 1){
            final Matrix4 transformationControllerValue = transformationController.value;
            final double currentScale = transformationControllerValue.getMaxScaleOnAxis();
            final double correctedDelta = details.focalPointDelta.dy / currentScale;
            final Offset correctedOffset = details.focalPoint/currentScale;
            final Duration currentTime = Duration(milliseconds: DateTime.now().millisecondsSinceEpoch);
            final double top = 600/currentScale;
            final double topOfViewport = (transformationControllerValue.row1[3]/currentScale) *-1;
            tracker.addPosition(currentTime, correctedOffset);
            if(topOfViewport  < 0.001 || topOfViewport + top > (600 - 0.001)){
              final DragUpdateDetails verticalDetails = DragUpdateDetails(
                  globalPosition: details.focalPoint,
                  sourceTimeStamp: currentTime,
                  primaryDelta: correctedDelta,
                  delta: Offset(0.0, correctedDelta)
              );
              customScroller.handleDragUpdate(verticalDetails);
            }
          }
        },
        onInteractionEnd: (ScaleEndDetails details){
          Offset velocity = tracker.getVelocity().pixelsPerSecond;
          //print(velocity.dy);
          DragEndDetails endDetails = DragEndDetails(
            velocity: Velocity(pixelsPerSecond: Offset(0.0, velocity.dy),),
            primaryVelocity: velocity.dy,
          );
          customScroller.handleDragEnd(endDetails);
        },
        child: SizedBox(
          height: 600,
          width: 350,
          child: ListView.builder(
              physics: const NeverScrollableScrollPhysics(),
              controller: customScroller,
              itemCount: 1000,
              itemBuilder: (context, index) {
                return Container(
                  child: Center(
                      child: Text("text $index")
                  ),
                );
              }
          ),
        ),
      ),
    );
  }
}

class DirectlySrollableScrollController extends ScrollController{

  final GlobalKey<RawGestureDetectorState> _gestureDetectorKey = GlobalKey<RawGestureDetectorState>();

  Drag? _drag;
  ScrollHoldController? _hold;
  void handleDragDown(DragDownDetails details) {
    assert(_drag == null);
    assert(_hold == null);
    _hold = position.hold(disposeHold);
  }

  void handleDragStart(DragStartDetails details) {
    // It's possible for _hold to become null between _handleDragDown and
    // _handleDragStart, for example if some user code calls jumpTo or otherwise
    // triggers a new activity to begin.
    assert(_drag == null);
    _drag = position.drag(details, disposeDrag);
    assert(_drag != null);
    assert(_hold == null);
  }

  void handleDragUpdate(DragUpdateDetails details) {
    // _drag might be null if the drag activity ended and called _disposeDrag.
    assert(_hold == null || _drag == null);
    _drag?.update(details);
  }

  void handleDragEnd(DragEndDetails details) {
    // _drag might be null if the drag activity ended and called _disposeDrag.
    assert(_hold == null || _drag == null);
    _drag?.end(details);
    assert(_drag == null);
  }

  void handleDragCancel() {
    if (_gestureDetectorKey.currentContext == null) {
      // The cancel was caused by the GestureDetector getting disposed, which
      // means we will get disposed momentarily as well and shouldn't do
      // any work.
      return;
    }
    // _hold might be null if the drag started.
    // _drag might be null if the drag activity ended and called _disposeDrag.
    assert(_hold == null || _drag == null);
    _hold?.cancel();
    _drag?.cancel();
    assert(_hold == null);
    assert(_drag == null);
  }

  void disposeHold() {
    _hold = null;
  }

  void disposeDrag() {
    _drag = null;
  }
}


```

**Comment by hgraceb** [comment]
@yakagami How amazing. Although I wouldn't use the same solution because I want to use BouncingScrollPhysics. It's also excellent working that can insight many peoples including me. Thanks.

By the way, my solution may open in the future but not now. Because there are too many hacks and almost can't put them into one file. And there are also some problems I have to resolve. Of course, I can show that to you in private by email or other methods if you are interested.

**Comment by yakagami** [comment]
@hgraceb Yes, I am very interested. My email is here: https://pastebin.com/tj03dsUi
let me know if you can see the pastebin link.

**Comment by yakagami** [comment]
Just published https://pub.dev/packages/zoom_view
