### ISSUE TITLE
Flutter web not opening on android web

### ISSUE THREAD

**Issue by Batsirai-sudo** [flutter/flutter#135465]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I have deployed flutter web to production, on IOS everything is fine but on android its getting stuck on the splash screen it loads forever not opening at all

### Expected results

Flutter web has to work on both android and ios web browser but only working on ios

### Actual results

Its not opeing on Android Device

### Code sample

<details><summary>Code sample</summary>

```dart

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Flutter (Channel stable, 3.13.2, on macOS 13.5.1 22G90 darwin-x64, locale en-GB)
    • Flutter version 3.13.2 on channel stable at /Users/batsiraimuchareva/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (5 weeks ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/batsiraimuchareva/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[!] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    ✗ Unable to get list of installed Simulator runtimes.
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)


```

</details>

**Comment by danagbemava-nc** [comment]
Hi @Batsirai-sudo, please provide a complete minimal reproducible code sample so that we can investigate this issue. 

You can also use the Chrome Inspector tool to check if any errors are being thrown when you open the app. 
You can checkout https://developer.chrome.com/docs/devtools/remote-debugging/ if you don't know how to use the inspector tool
