### ISSUE TITLE
Odd canvas rendering when drawing thin lines

### ISSUE THREAD

**Issue by yoshiask** [flutter/flutter#135446]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a custom painter
2. Set up `Paint` with a gray stroke color and small stroke width (e.g. 1 or 2 pixels)
3. Call `drawRect`, `drawRRect`, or `drawLine`

### Expected results

The lines drawn on the canvas should be using the given color and thickness.

### Actual results

All lines, even plain horizontal lines that aren't part of a rectangle, are drawn either with the wrong thickness, the wrong color, or both. From left to right, top to bottom:
* Every line has artifacting and is inconsistently lighter than the provided color.
* The left side is slightly too dark in its center, while the others are fine. Some edges appear thicker than others.
* The horizontal line is exactly one pixel thick, as it should be, but is too light.
* Every edge is a different color and is too light.
* The diagonal line is the correct thickness but is too light.
* The right edge is the correct color, but every other side is too light. The bottom edge is almost completely missing.

Setting`isAntiAlias = false` changes the behavior slightly, but does not resolve the issue.

### Code sample

<details><summary>Code sample</summary>

In `paint` implementation:
```dart
final center = (Offset.zero & size).center;
final outerRect = RRect.fromRectAndRadius(
    Rect.fromCenter(center: center, width: 25.0, height: 25.0),
    Radius.circular(6.0.sp));

// Border
final Paint paint = Paint()
  ..color = Color(0xFFBCBCBC)
  ..style = PaintingStyle.stroke
  ..strokeWidth = 1.0;
canvas.drawRRect(outerRect, paint);
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

All stroke colors are set to `#BCBCBC`.
The leftmost column and horizontal line show `drawRect`, `drawRRect`, and `drawLine` with a 1px stroke width. The top center box is `drawRect` with a 2px stroke width. The bottom center box is a diagonal `drawLine` with 1px width. The bottom right box is `drawRRect` with 1px and anti-aliasing disabled.

![incorrect_border_paint_demo](https://github.com/flutter/flutter/assets/7549325/f2f9feb7-0284-42c3-8d20-aee19787bbed)

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.5 22G74 darwin-x64, locale en-US)
    • Flutter version 3.13.0 on channel stable at /Users/joshua/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (6 weeks ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/joshua/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/joshua/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.10121639/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/joshua/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.10121639/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • macOS (desktop)              • macos         • darwin-x64     • macOS 13.5 22G74 darwin-x64
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 116.0.5845.187

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @yoshiask 
Using code snippet you provided, I came up with below runnable code sample that shows me as in screenshot:

<img width="193" alt="Screenshot 2023-09-26 at 1 53 06 PM" src="https://github.com/flutter/flutter/assets/67046386/c18e8063-02e5-4144-84ed-43cb18bcd763">


<details>
<summary> runnable code </summary>

```

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(),
      body: Center(
        child: Container(
          width: 300,
          height: 400,
        //  color: Colors.green,
          child: CustomPaint(
            painter: CanvasTest(),
            size: const Size(300, 400),
          ),
        ),
      ),
    );
  }
}

class CanvasTest extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {

    final center = (Offset.zero & size).center;
    final outerRect = RRect.fromRectAndRadius(
        Rect.fromCenter(center: center, width: 25.0, height: 25.0),
        Radius.circular(6.0));

    Paint paint = Paint()
      ..strokeWidth = 1.0
      ..color = Color(0xFFBCBCBC)
      ..style = PaintingStyle.stroke;
    canvas.drawRRect(outerRect, paint);
  }

  @override
  bool shouldRepaint(CanvasTest oldDelegate) {
    return true;
  }
}

```

</details>

Can you elaborate on the expected result using above code ?

**Comment by yoshiask** [comment]
That's odd, your screenshot looks as I'd expect. Perhaps this has something to do with the Android emulator, rather than Flutter?

**Comment by darshankawar** [comment]
You may try on different emulators and check if result varies or stays same.

**Comment by Sakari369** [comment]
Hello, i am also seeing ugly line rendering especially with low line widths and when scaling with canvas.scale() to small values.

Can provide a test case maybe, but are screenshots enough to prove it ?

Disabling Impeller on iOS and going back to Skia produces beautiful results, but on Impeller the lines get distorted, antialiasing seems broken, and the more you scale with canvas.scale, the more ugly the results become with small distances and line widths.

In my test case, I am rendering a bunch of fractal hexagon shapes.

Here you can see an image rendered on iOS hardware, screenshots captured on iPad 10.2":

**Skia**
![IMG_0082](https://github.com/flutter/flutter/assets/1212726/88169e4c-52c8-4bae-96cd-ad652db418a1)

And here you can see the same with impeller:

**Impeller**
![IMG_0085](https://github.com/flutter/flutter/assets/1212726/eb043a89-ff1d-45c9-8f25-a75954ad1933)

<details>
  <summary>Flutter doctor output</summary>  
  ```
  [✓] Flutter (Channel stable, 3.13.6, on macOS 13.5.2 22G91 darwin-arm64, locale en-FI)
    • Flutter version 3.13.6 on channel stable at /Users/sakari/dvl/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (6 days ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/sakari/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/sakari/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version unknown)
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.8+0-17.0.8b1000.22-10799086)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Sakari’s iPad (mobile) • 00008030-000E44293E22202E • ios            • iOS 16.7 20H19
    • macOS (desktop)        • macos                     • darwin-arm64   • macOS 13.5.2 22G91 darwin-arm64
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 114.0.5735.90

[✓] Network resources
    • All expected network resources are available.
  ```
</details>

**Comment by darshankawar** [comment]
@Sakari369 
I suggest you to file a new issue with relevant details and runnable code sample so that we can properly address the issue.
