### ISSUE TITLE
Add auto retry for top flaky targets in packages repo

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#135449]
With the presubmit auto retry supported: https://github.com/flutter/cocoon/pull/3059, we can enable the logic for top flaky targets in the packages repo.

This will help auto land bump PRs like: https://github.com/flutter/packages/pull/4988, where I have to rerun twice of the flaky targets `Linux_android android_platform_tests_shard_2 master` and re-add the `autosubmit` label to get it landed.

**Comment by keyonghan** [comment]
Will start with:
https://ci.chromium.org/ui/p/flutter/builders/luci.flutter.prod/Linux_android%20android_platform_tests_shard_2%20stable
https://ci.chromium.org/ui/p/flutter/builders/luci.flutter.prod/Linux_android%20android_platform_tests_shard_2%20master

**Comment by keyonghan** [comment]
@stuartmorgan Are there any other targets you would prefer an auto rerun?

**Comment by stuartmorgan** [comment]
See https://github.com/flutter/packages/pull/4995#pullrequestreview-1642769946

I don't think we should do this for Android platform tests. We could potentially do it for other tests in the future, but right now I don't have any specific candidates.

**Comment by keyonghan** [comment]
Flake tracking bug to fix the flakes is https://github.com/flutter/flutter/issues/130986. Closing here. We can open a new one tracking auto rerun functionality if needed in the future.
