### ISSUE TITLE
gif playing ghosting when using Image.network for some gif url

### ISSUE THREAD

**Issue by Codersdg** [flutter/flutter#135490]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

The gif url is 'https://cos.ap-shanghai.myqcloud.com/caae-shanghai-007-sharedv4-02-1303031839/7721-1400826961/dc46-100136408/ec590906958dad92f68e4d837d1e06fa.gif?imageMogr2/&imageView2/3/w/198/h/237', which  can cause the playing problem.

```
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.5.1 22G90 darwin-arm64, locale
    zh-Hans-CN)
    • Flutter version 3.10.5 on channel stable at /Users/bk/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (4 months ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/bk/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/bk/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.5.1 22G90 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 117.0.5938.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!

 
```

### Expected results

I hope the gif url loaded same with its original file
![a73710c3731b34fe32b6def35ba5b95b](https://github.com/flutter/flutter/assets/97607972/b4b50dc9-f1f0-4d89-8a07-3735d1eaa532)

### Actual results

play ghosting

### Code sample

```dart

   @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
          child: Image.network(
              'https://cos.ap-shanghai.myqcloud.com/caae-shanghai-007-sharedv4-02-1303031839/7721-1400826961/dc46-100136408/ec590906958dad92f68e4d837d1e06fa.gif?imageMogr2/&imageView2/3/w/198/h/237')),
    );
  }
```

</details>

### Screenshots or Video

https://github.com/flutter/flutter/assets/97607972/befa2b6f-8655-4196-8dc6-f0397719e353

**Comment by dam-ease** [comment]
Hi @Codersdg. Thanks for filing this. I can't seem to reproduce this on the latest versions of Flutter. Are you able to check this on the latest versions of Flutter? Can you share the output of your `flutter doctor -v`?

[untitled.webm](https://github.com/flutter/flutter/assets/53122008/c1cea949-8116-49c2-8188-85155b8ac477)

<details><summary>flutter doctor -v</summary>
<p>

```
[✓] Flutter (Channel stable, 3.13.5, on macOS 13.0 22A380 darwin-arm64, locale
    en-NG)
    • Flutter version 3.13.5 on channel stable at
      /Users/damilolaalimi/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12fccda598 (6 days ago), 2023-09-19 13:56:11 -0700
    • Engine revision bd986c5ed2
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554                        •
      android-arm64  • Android 14 (API 34) (emulator)
    • iPhone 14 Pro Max (mobile)      • BB55E997-7F31-462D-B3B1-6B177D9B40C7 •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • iPad (10th generation) (mobile) • 5B1DA2B3-69EC-435B-95F8-550B7F3A9FBB •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)                 • macos                                •
      darwin-arm64   • macOS 13.0 22A380 darwin-arm64
    • Chrome (web)                    • chrome                               •
      web-javascript • Google Chrome 116.0.5845.187

[✓] Network resources
    • All expected network resources are available.

• No issues found!
``` 

</p>
</details>

**Comment by Codersdg** [comment]
> Hi @Codersdg. Thanks for filing this. I can't seem to reproduce this on the latest versions of Flutter. Are you able to check this on the latest versions of Flutter? Can you share the output of your `flutter doctor -v`?
> 
>  untitled.webm 
> 
> Code Sample
> flutter doctor -v
> ```
> [✓] Flutter (Channel stable, 3.13.5, on macOS 13.0 22A380 darwin-arm64, locale
>     en-NG)
>     • Flutter version 3.13.5 on channel stable at
>       /Users/damilolaalimi/sdks/flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 12fccda598 (6 days ago), 2023-09-19 13:56:11 -0700
>     • Engine revision bd986c5ed2
>     • Dart version 3.1.2
>     • DevTools version 2.25.0
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
>     • Android SDK at /Users/damilolaalimi/Library/Android/sdk
>     • Platform android-34, build-tools 34.0.0
>     • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
>     • Java binary at: /Applications/Android
>       Studio.app/Contents/jbr/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build
>       17.0.6+0-17.0.6b802.4-9586694)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Build 14E300c
>     • CocoaPods version 1.12.1
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 2022.2)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build
>       17.0.6+0-17.0.6b802.4-9586694)
> 
> [✓] VS Code (version 1.82.2)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.50.0
> 
> [✓] Connected device (5 available)
>     • sdk gphone64 arm64 (mobile)     • emulator-5554                        •
>       android-arm64  • Android 14 (API 34) (emulator)
>     • iPhone 14 Pro Max (mobile)      • BB55E997-7F31-462D-B3B1-6B177D9B40C7 •
>       ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
>     • iPad (10th generation) (mobile) • 5B1DA2B3-69EC-435B-95F8-550B7F3A9FBB •
>       ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
>     • macOS (desktop)                 • macos                                •
>       darwin-arm64   • macOS 13.0 22A380 darwin-arm64
>     • Chrome (web)                    • chrome                               •
>       web-javascript • Google Chrome 116.0.5845.187
> 
> [✓] Network resources
>     • All expected network resources are available.
> 
> • No issues found!
> ```

My flutter version is 3.10.5, I have updated the info on reproudce step.

**Comment by Codersdg** [comment]
> Hi @Codersdg. Thanks for filing this. I can't seem to reproduce this on the latest versions of Flutter. Are you able to check this on the latest versions of Flutter? Can you share the output of your `flutter doctor -v`?
> 
>  untitled.webm 
> 
> Code Sample
> flutter doctor -v

The lastest flutter version works for me, thanks.
