### ISSUE TITLE
Expected a value of type 'Function', but got one of type 'Null' in FlutterImageCompress

### ISSUE THREAD

**Issue by donuthappy** [flutter/flutter#135491]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

flutter pub add flutter_image_compress
import 'package:flutter_image_compress/flutter_image_compress.dart';

### Expected results

I want to compress image using this package.

### Actual results

It worked well before.
But this is not work from few days.
I got error like this : `Expected a value of type 'Function', but got one of type 'Null'`

### Code sample

Uint8List resizedImage = await FlutterImageCompress.compressWithList( bytesImg, minHeight: newHeight, minWidth: newWidth, );

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.5, on Microsoft Windows [Version 10.0.19044.3086], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.5)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.82.2)
[√] Connected device (3 available)
[√] Network resources

**Comment by danagbemava-nc** [comment]
`flutter_image_compress` is a third-party plugin. Kindly file this issue on their repo so that it can be properly investigated. 

Closing from here. 

Thank you
