### ISSUE TITLE
[Impeller] OpenGLES embedder Flutter Scene example doesn't render.

### ISSUE THREAD

**Issue by jwinarske** [flutter/flutter#135538]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Clone engine for 3.15.0-15.2.pre
2. Patch with https://github.com/flutter/engine/pull/46287
3. Build using: 
    flutter/tools/gn --unoptimized --runtime-mode=debug --embedder-for-target --enable-fontconfig --no-build-embedder-examples --enable-impeller-3d --enable-impeller-opengles --no-lto --no-goma
4. Setup Flutter SDK for 3.15.0-15.2.pre
5. git clone https://github.com/bdero/flutter-scene-example.git
6. cd flutter-scene-example
7. flutter run --enable-impeller --local-engine=host_debug_unopt --local-engine-host=host_debug_unopt --local-engine-src-path=/mnt/raid10/workspace-automation/.config/flutter_workspace/flutter-engine/engine/src -d homescreen

### Expected results

3D scene to render

### Actual results

Only renders title bar and background.

### Code sample

<details><summary>Code sample</summary>

EGL Config

```c++
static constexpr std::array<EGLint, 5> kEglContextAttribs = {{
    // clang-format off
    EGL_CONTEXT_MAJOR_VERSION, 3,
    EGL_CONTEXT_MAJOR_VERSION, 2,
    EGL_NONE
    // clang-format on
}};

static constexpr std::array<EGLint, 27> kEglConfigAttribs = {{
    // clang-format off
    EGL_SURFACE_TYPE, EGL_WINDOW_BIT,
    EGL_RENDERABLE_TYPE, EGL_OPENGL_ES3_BIT,
    EGL_RENDERABLE_TYPE, EGL_OPENGL_ES2_BIT,

    EGL_RED_SIZE, 8,
    EGL_GREEN_SIZE, 8,
    EGL_BLUE_SIZE, 8,
    EGL_ALPHA_SIZE, 8,

    EGL_DEPTH_SIZE, 16,
    EGL_STENCIL_SIZE, 8,
    EGL_RENDERABLE_TYPE, 4,
    EGL_SAMPLE_BUFFERS, 1,
    EGL_SAMPLES, 4,
    EGL_BUFFER_SIZE, 32,

    EGL_NONE // termination sentinel
    // clang-format on
}};
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![Screenshot from 2023-09-26 11-12-26](https://github.com/flutter/flutter/assets/12262875/106c071d-f0ec-42f6-a67e-3d99634ca01e)

</details>

### Logs

<details><summary>Logs</summary>

```console
[log.txt](https://github.com/flutter/flutter/files/12732602/log.txt)
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel [user-branch], 3.15.0-15.2.pre, on Fedora Linux 38 (Workstation Edition) 6.4.15-200.fc38.x86_64, locale en_US.UTF-8)
    ! Flutter version 3.15.0-15.2.pre on channel [user-branch] at /mnt/raid10/workspace-automation/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision 0d074ced6c (5 days ago), 2023-09-21 10:24:15 -0700
    • Engine revision 453411bcf3
    • Dart version 3.2.0 (build 3.2.0-134.1.beta)
    • DevTools version 2.27.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 16.0.6 (Fedora 16.0.6-3.fc38)
    • cmake version 3.27.4
    • ninja version 1.11.1
    • pkg-config version 1.8.0

[✓] VS Code (version 1.82.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.72.0

[✓] Connected device (2 available)
    • Linux (desktop)              • linux              • linux-x64 • Fedora Linux 38 (Workstation Edition) 6.4.15-200.fc38.x86_64
    • Toyota homescreen (mobile)   • homescreen         • linux-x64 • homescreen x86_64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment]
Thanks for the report. I have some issues with local engine so can't check this now but I will label this for other's inputs.

**Comment by huycozy** [comment]
Thanks for the report. I have some issues with local engine so can't check this now but I will label this for other's inputs and come back later if my own issues have been solved.

**Comment by jonahwilliams** [comment]
I believe this was fixed with https://github.com/flutter/engine/pull/47217 . Please reopen if that isn't the case

**Comment by jwinarske** [comment]
It does not render correctly., as I shared with video on discord the week before last

**Comment by jwinarske** [comment]
Also the device tested on does support MSAA
