### ISSUE TITLE
Expose `onAttach` and `onDetach` in `PageController` constructor

### ISSUE THREAD

**Issue by timcreatedit** [flutter/flutter#135574]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

The new `onAttach` and `onDetach` in `ScrollController` are currently not usable with `PageController` since its constructor doesn't include them, and extending classes can't set the fields on `ScrollController`

As discussed in #124823:

>This resolves a long held pain point for developers. When using a scroll controller, there is not scroll position until the scrollable widget is built, and almost all methods of notification are only triggered when scrolling happens. Adding these two methods will help developers gain access to the scroll position when it is created. A common workaround for this was using a post frame callback to access controller.position after the first frame, but this is ripe for issues such as having multiple positions attached to the controller, or the scrollable no longer existing after that post frame callback. I think this can also be helpful for folks to debug cases when the scroll controller has multiple positions attached.

### Proposal

Add the callbacks to the `PageController` constructors.

**Comment by dam-ease** [comment]
Hi @timcreatedit. Thanks for filing this. Can you share a code sample of your implementation with `PageController`?

**Comment by timcreatedit** [comment]
Hi! I'm not quite sure what you are referring to, do you mean a proposal for the fix? The basic issue is the exact same as the ones mentioned in #124823, which has been merged. The problem I'm referring to, is that the changes haven't been propagated to `PageController` yet, which extends `ScrollController`.

A simple example of where this is a problem:

```dart
@override
Widget build(BuildContext context) {
  return ListenableBuilder(
    listenable: pageController,
    builder: (context, child) {
      final double? page;
      if (pageController.positions.length != 1) {
        page = null;
      } else {
        page = pageController.page;
      }

      // ... Do something with the page.
    },
  )
}
```

In this example, if `build` is executed before any `PageView` attached to the `PageController`, the page is set to null. Once a `PageView` attaches, one would expect the `ListenableBuilder` to rebuild, but that doesn't happen, even though a page is be available now.
A common workaround for this is adding a PostFrameCallback, but that brings a lot of issues in it's own right.

This is one part of why `onAttach` and `onDetach` were added to `ScrollController`. It would allow us to do something like: 

```dart
@override
void initState() {
  pageController = PageController(
    onAttach: (position) {
      // Simplified example with protected member for the sake of this issue.
      position.notifyListeners();
    }
    super.initState();
  );
}
```

Let me know if you have any more questions.

**Comment by Piinks** [comment]
Thanks for reporting this! the fix is in https://github.com/flutter/flutter/pull/135721 :)
