### ISSUE TITLE
The app template `pubspec.lock` should be in source control, but has relative paths

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#13559]
Breaking this out into a seperate bug from discussion in:
https://github.com/flutter/flutter/issues/13428

Pub recommends that for *applications* you add `pubspec.lock` to source control. However, we currently have this file in `.gitignore` in our application template:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/create/.gitignore.tmpl

We should remove it from `.gitignore` in this template, but leave it ignored in the package and plugin templates.

**Comment by mit-mit** [comment]
This is currently blocked on the fact that pubspec.lock has a relative path to `sky_engine`:

```
cd examples/hello_world/
flutter packages get
cat pubspec.lock
```

=>

```
...
  sky_engine:
    description:
      path: "../../bin/cache/pkg/sky_engine"
      relative: true
    source: path
    version: "0.0.99"
...

**Comment by mit-mit** [comment]
cc @Hixie why do we use a relative path here?

**Comment by Hixie** [comment]
If we used an absolute path, it would break if someone cloned the user's repository on a different machine.
Come to think of it, it could break with a relative path, too.
Why do we use a path dependency instead of an sdk dependency?

**Comment by mit-mit** [comment]
`sky_engine` is not in `<flutter root>/packages/` like the other flutter packages (`flutter`, `flutter_driver`, etc.). It's being downloaded along with the engine, and is placed in `<flutter root>/bin/cache/pkg/sky_engine`. Given that, I'm not sure an sdk dependency would work? 

Or, are you suggesting some combination of an sdk dependency and a relative path, e.g.: ?

```
sky_engine:
    source: sdk
    description:
      path: "./bin/cache/pkg/sky_engine"
      relative: true
```

Or should we just put is in `<flutter root>/packages/` when we download it?

**Comment by Hixie** [comment]
I'm not sure how sdk dependencies work. Is it just looking under `<sdk root>/packages`? If there was a way to label this particular dependency with a path like you suggest that would be pretty neat.

I don't think we should put it in `<flutter root>/packages/sky_engine`, i think that would mostly just confuse users and cause weird problems later (e.g. what if they try to edit it, we won't merge their changes like we would in the other packages).

**Comment by mit-mit** [comment]
cc @nex3, would it be possible to support a combination of sdk and local path as mentioned above in https://github.com/flutter/flutter/issues/13559#issuecomment-351953568 ?

**Comment by nex3** [comment]
We can make SDK dependencies for Flutter work more or less however you want. In this case, maybe it would be simpler to just say "look in either `<flutter>/packages` or `<flutter>/bin/cache/pkg`"?

**Comment by mit-mit** [comment]
@nex3 yes, that would also be a great solution!

**Comment by mit-mit** [comment]
Tagging milestone 3 as there have been several cases recently where the lack of pinning versions of consumed packages & plugins has caused build issues. Ensuring that small new teams using Flutter get a consistent build experience is critical.

**Comment by mit-mit** [comment]
@nex3 would you like a bug on the dart-side to track this request?

**Comment by nex3** [comment]
Yes please! File something against pub with the exact behavior you want.

**Comment by mit-mit** [comment]
Assigning to self for tracking from a Flutter POV. Pub issue for @nex3 is https://github.com/dart-lang/pub/issues/1775.

**Comment by mit-mit** [comment]
Pub fix landed in https://github.com/dart-lang/pub/pull/1778. Waiting for a roll.

**Comment by mit-mit** [comment]
This requires Dart SDK 2.0 dev 19 or later.
