### ISSUE TITLE
Post submit tasks show `In Process` though they have finished

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#135513]
This happens in different repositories, and is blocking tasks backfilling. Even block trees if any TOT task failed earlier.

Engine:
<img width="924" alt="Screenshot 2023-09-26 at 10 58 19 AM" src="https://github.com/flutter/flutter/assets/54558023/818aead1-a118-4c1f-a263-ab1e05f6e136">
Framework:
<img width="1016" alt="Screenshot 2023-09-26 at 10 59 15 AM" src="https://github.com/flutter/flutter/assets/54558023/cdf78437-6975-453a-99b6-dbdf28b96b95">

Taking look at one build:
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Framework%20Smoke%20Tests/14639/overview

We do see three processing entries, with the last one shows correct status update:
`Updated datastore from In Progress to Succeeded`

![Screenshot 2023-09-26 at 11 01 53 AM](https://github.com/flutter/flutter/assets/54558023/9e23b942-94eb-45b5-8e85-810404246936)

Sounds some issue from Datastore side.

**Comment by keyonghan** [comment]
Recovered Engine tree by manually marking the `In Progress` as `Succeeded` (validated that all `In Progress` tasks have finished with `Success` status.
Recovered Framework Tree by manually marking the `In Progress` as `New`, so the back filler can rerun them.

**Comment by keyonghan** [comment]
Packages repo are hanging waiting for tasks to be scheduled.

<img width="1185" alt="Screenshot 2023-09-26 at 11 16 17 AM" src="https://github.com/flutter/flutter/assets/54558023/b0fff63c-d4d9-404c-a866-80a098b4f4e7">

Seems we have a big backlog of unacked messages in pub/sub:
<img width="530" alt="Screenshot 2023-09-26 at 11 15 58 AM" src="https://github.com/flutter/flutter/assets/54558023/96085f72-9b83-4be8-8632-9cd783f1fb9c">

Potential culprit: https://github.com/flutter/flutter/issues/135508#issuecomment-1736031603

Reducing the `Subscription message retention duration` from 4 days to 12 hr.

**Comment by vashworth** [comment]
I have a framework PR that merged in ~ an hour ago but isn't showing up on the dashboard at all.
https://github.com/flutter/flutter/pull/135444

Not sure if it's related or not

**Comment by keyonghan** [comment]
Immediate issue has been recovered by staling outdated pub/sub messages.
Hanging tasks have been recovered. 
The missing commit issue should be resolved by https://github.com/flutter/cocoon/pull/3106.
