### ISSUE TITLE
GeneratedPluginRegistrant should not be checked in

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#13554]
We currently check in GeneratedPluginRegistrant.java/.m/.h to make sure that our example can run from an IDE (Android Studio/xcode) without previously running `flutter run`.

Would be good, if these files would just get generated on the fly even when running from IDE so that we don't have to check in and maintain generated files in the repository.

This is a continuation of the discussion in https://github.com/flutter/flutter/pull/13500.

/cc @mit-mit @mravn-google

**Comment by mit-mit** [comment]
tagging for something to look at in q1
