### ISSUE TITLE
Build issues when WSS agent is enabled - Unable to find valid certification path 

### ISSUE THREAD

**Issue by kmusham** [flutter/flutter#135520]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1) Enable WSS agent from Symantic on your mac
2) Try to build your flutter application for android (.apk)

Immediately android studio throws an error. (see the attached stack trace). This issue happens only when WSS agent is enabled by the organization. WE've tried commandline build and also with VC IDE, in all the cases, issues is same. 
[
![Screenshot 2023-09-25 at 12 48 19 PM](https://github.com/flutter/flutter/assets/6372373/95f9430c-9a03-4aba-a9a3-b091115ccd81)
](url) 

### Expected results

Build should create an .apk

### Actual results

Throws an error
![Screenshot 2023-09-25 at 12 48 19 PM](https://github.com/flutter/flutter/assets/6372373/ba64f08b-02dc-43b4-8521-57489b09bc3b)

### Code sample

<details><summary>Code sample</summary>
Any flutetr/dart code
```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]

[✓] Flutter (Channel stable, 3.13.5, on macOS 13.6 22G120 darwin-arm64, locale en-US)
    • Flutter version 3.13.5 on channel stable at /Users/kmusham/Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12fccda598 (7 days ago), 2023-09-19 13:56:11 -0700
    • Engine revision bd986c5ed2
    • Dart version 3.1.2
    • DevTools version 2.25.0

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/kmusham/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[!] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.80.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 14 (API 34) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.6 22G120 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 117.0.5938.92
    ! Error: Kiran’s iPhone 13 Pro is not available because it is unpaired. Pair with the device in the Xcode Devices Window, and respond to any pairing
      prompts on the device. (code -29)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
</details>

**Comment by darshankawar** [comment]
@kmusham 
I am not sure if Symantec's web security service's compatibility with Flutter, as it is external to the framework and also whether it is expected to work or not.

Check https://github.com/flutter/flutter/issues/51091#issuecomment-588575716 and see if it helps in your case or not.

**Comment by kmusham** [comment]
Thank for the response, for some reasons this solution didn't work for me. I've added the cert to java keystore and also included in the IDE server certs list. 
BTW, I'm using Amazon's Corretto 21 Java. Not sure if this version of java is anything to do with the issue.

**Comment by darshankawar** [comment]
@kmusham 
Can you try the same with Java 17 and see if you get same behavior / result or not ?
