### ISSUE TITLE
Apple pencil event is delayed

### ISSUE THREAD

**Issue by wolru** [flutter/flutter#135548]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

There was the same issue, but it closed. However, the same problem is still occurring today
There's no problem doing it with finger.

https://github.com/flutter/flutter/issues/109022

onPointerDown event comes seriously slow. This is serious problem in my app.

### Expected results

The event is the same as when you do it with fingers

### Actual results

Apple pencil event is delayed

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.13.4, on macOS 13.6 22G120 darwin-arm64, locale ko-KR)
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.19.3/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/hanbitkim/development/flutter. Consider adding /Users/hanbitkim/development/flutter/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
[✓] VS Code (version 1.82.2)
[✓] Connected device (4 available)
[✓] Network resources

```

</details>

**Comment by danagbemava-nc** [comment]
Hi @wolru, kindly share a complete minimal reproducible code sample so that we can investigate this issue. 

I used the code sample from #109022 and I could not discern any difference between using the apple pencil and my fingers. 

Thank you

**Comment by wolru** [comment]
Hi @danagbemava-nc 
The same error occurs in the sample code
https://github.com/flutter/flutter/issues/109022

**Comment by danagbemava-nc** [comment]
Hi @wolru, as I stated in https://github.com/flutter/flutter/issues/135548#issuecomment-1737028487,  I already used that code sample and there was not any difference between the time my fingers registered and the time the apple pencil registered. 

Can you share how you are measuring the difference?

**Comment by wolru** [comment]
Hi @danagbemava-nc . Thank you for your answer
Depending on the type of device and Apple Pencil, there are cases where there is no problem.
I use the 9th generation of iPad and the 1st generation of Apple Pencil, which causes problems at this time, and relatively modern devices and pencils often have no problems

**Comment by danagbemava-nc** [comment]
Hi @wolru, thanks for the info. Just for confirmation, what version of iOS are you running on the iPad? Can you also show the delay that happens when you try to register pointers with the pencil? 

I have an iPad Air M1 (2022) and a second gen apple pencil, that's probably why I can't see any issues on my end

**Comment by wolru** [comment]
Hi, @danagbemava-nc 
I have an iPad 9 gen(os 16.5.1) and first gen apple pencil
Thank you

**Comment by danagbemava-nc** [comment]
Hi @wolru, do you have this issue only with flutter apps or are other apps affected as well? 

We would also appreciate it if you could provide a recording that demonstrates the behaviour you're experiencing. A comparison between flutter and native would be even better.

Thank you

**Comment by wolru** [comment]
Hi, @danagbemava-nc 
I'm sorry.
One difference from the example code was that Listener's child was webview, but there was a problem when it was webview, and when the webview was wrapped with IgnorePointer, it worked normally.

**Comment by danagbemava-nc** [comment]
Hi @wolru, does this mean you have resolved your issue?

**Comment by wolru** [comment]
@danagbemava-nc yes, thank you very much
