### ISSUE TITLE
MethodChannels and platform threading documentation

### ISSUE THREAD

**Issue by kirill-21** [flutter/flutter#135502]
Hi, i've noticed that this [documentation for MethodChannel](https://docs.flutter.dev/platform-integration/platform-channels?tab=type-mappings-c-plus-plus-tab#channels-and-platform-threading) misses examples of jumping to the UI thread for C++(Windows Platform), it only provides examples for ios and android 

![image](https://github.com/flutter/flutter/assets/63228361/0e2e1267-3bc0-4d05-948c-c7f41327f21a)
![image](https://github.com/flutter/flutter/assets/63228361/6e788067-af65-456b-9fe5-548d8e2e4d5c)

It would be great to add more detailed info for Windows so that people understand better of how to handle this error
![image](https://github.com/flutter/flutter/assets/63228361/55ab73ad-8f4a-479f-80dc-b589537f04b0)

**Comment by stuartmorgan** [comment]
Windows doesn't have a convenient mechanism for this, so it's not something we would document on that page; the plan to address that error message for Windows is [to eliminate it](https://github.com/flutter/flutter/issues/134346).

See also discussion i nhttps://github.com/flutter/flutter/issues/79213, including a link to a PR that demonstrates how a plugin could do thread hopping.
