### ISSUE TITLE
Merged-in PR not showing in dashboard

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#135518]
### Is there an existing issue for this?

- [X] I have searched the [existing infra issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-infra)

### Type of Request

bug

### Infrastructure Environment

LUCI

### What is happening?

I have a PR (https://github.com/flutter/flutter/pull/135444) that merged at 12:48 CDT, but it isn't showing in the dashboard as of 2 PM CDT

One thing that may be of note is that I manually overrode the Google Testing status

### Steps to reproduce

1. Visit https://flutter-dashboard.appspot.com/#/build
2. See that my PR is not listed

### Expected results

I expect to see my PR in https://flutter-dashboard.appspot.com/#/build

**Comment by vashworth** [comment]
It just started showing on the dashboard at ~2:05 PM CDT

**Comment by keyonghan** [comment]
There seems a bug in webhook subscription when GOB commit copy over is slow (fails to show up even after 3 retries), it will fail to insert the data to datastore. To workaround, I manually vacuum the missing commits.

**Comment by keyonghan** [comment]
The webhook message is supposed to be resent to subscription API after 500 error, but it didn't. This causes the commit missing if GOB copybara slows.

I am trying to understand the difference between subscriptions [github-webhooks-sub](https://pantheon.corp.google.com/cloudpubsub/subscription/detail/github-webhooks-sub?project=flutter-dashboard&tab=details) and [luci-postsubmit](https://pantheon.corp.google.com/cloudpubsub/subscription/detail/luci-postsubmit?project=flutter-dashboard&tab=details):

where the [webhook message was not retried after 500](https://pantheon.corp.google.com/logs/query;query=resource.type%3D%22gae_app%22%0Aresource.labels.module_id%3D%22default%22%0Aresource.labels.version_id%3D%22version-de7e221%22%0A%223cfe3720d61ccfc4f092f15e67637425fc908015%20was%20not%20found%20on%20GoB.%20Failing%20so%20this%20event%20can%20be%20retried...%22%0A--%20%22%20for%203cfe3720d61ccfc4f092f15e67637425fc908015%22;cursorTimestamp=2023-09-26T17:49:52.865Z;startTime=2023-08-24T00:25:04.917Z;endTime=2023-09-26T19:25:03.972036Z?serviceId=default&project=flutter-dashboard) but [the postsubmit message did get retries](https://pantheon.corp.google.com/logs/query;query=resource.type%3D%22gae_app%22%0Aresource.labels.module_id%3D%22default%22%0Aresource.labels.version_id%3D%22version-de7e221%22%0Aseverity%3E%3DERROR%0A%22Processing%20message%209257745237444758%22;cursorTimestamp=2023-09-26T19:17:13.445Z;startTime=2023-08-24T00:25:04.917Z;endTime=2023-09-26T19:25:03.972036Z?serviceId=default&project=flutter-dashboard)
