### ISSUE TITLE
Error (Xcode): ../../Library/flutter/packages/flutter/lib/src/widgets/framework.dart:1102:9: Error: Expected ';' after this

### ISSUE THREAD

**Issue by anapimolodec** [flutter/flutter#135541]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Created a new Flutter project
2. Run and debug main.dart file without changing boiler code
3. Error appers

### Actual results

From yesterday, I am unable to run any flutter app, even the new Flutter boiler code app.

### Logs

<details>
<summary>Logs</summary>

```
Launching lib/main.dart on iPhone 15 Pro Max in debug mode...
Xcode build done.                                           11.6s
Failed to build iOS app
Error (Xcode): ../../Library/flutter/packages/flutter/lib/src/widgets/framework.dart:1102:9: Error: Expected ';' after this.

Could not build the application for the simulator.
Error launching application on iPhone 15 Pro Max.

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.5, on macOS 13.5.1 22G90 darwin-arm64, locale
    en-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version
    34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
[✓] VS Code (version 1.76.0)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by anapimolodec** [comment]
when simulation is on android, it throws this error:
../../Library/flutter/packages/flutter/lib/src/widgets/framework.dart:1102:9: Error: Expected ';' after this.
        01throw FlutterError.fromParts(<DiagnosticsNode>[
        ^^
Target kernel_snapshot failed: Exception

**Comment by anapimolodec** [comment]
I could not find the origin of the problem so I had to delete Flutter and reinstall it again and it works now, 
but still please let me know if anyone solved this issue without reinstalling the Flutter.

**Comment by danagbemava-nc** [comment]
Hi @anapimolodec, you might have accidentally modified your framework file while you were browsing through the source code.

There really isn't a fix if that was the case other than reverting the change you did. Unfortunately, without looking at your local copy of the framework source code, there isn't much we can do. 

Closing this for now since the issue seems like something with your local copy of flutter. 

Thank you
