### ISSUE TITLE
`FilterChip` should have `DeletableChipAttributes`/`trailing` to match Material 3 spec.

### ISSUE THREAD

**Issue by Jonas-Sander** [flutter/flutter#135595]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I'm trying to present several filters that a user can choose from, like shown [here](https://m3.material.io/components/chips/guidelines#11bc122b-5203-4cf5-bb12-470d86ecd3b5) in the material 3 spec. 

Additionally the user should be able to create more filter with a custom value. These custom filters should be deletable. Such a filter chip with the "X" symbol is shown in the material 3 spec [right here](https://m3.material.io/components/chips/guidelines#1ecdeead-f934-4f30-950d-25518eab90f4).   

Note: In the last link the description says: "[...]  filter chips may contain a trailing icon to directly remove the chip [...]" but subtext beneath the illustration says: "The X close icon indicates that a user can unselect the filter chip". I'm very sure "unselect" is wrong and should be replaced with "delete", since one can already unselect by tapping on the chip and as the "X" means deleting on other chip types.

### Proposal

Add `DeletableChipAttributes` to `FilterChip`.

Note: As there is also an [example with a "trailing menu item"](https://m3.material.io/components/chips/guidelines#dcf3eb06-5f81-4f7d-8299-e32a950d8572) maybe there should be a `trailing` attribute instead of only `onDeleted` etc? But as `_RawChip` specifically mentions `deleteIcon` I'm not sure if this would require a refactoring of other chip types as well.

**Comment by TahaTesser** [comment]
This seems to be an updated `FilterChip` specs 

![Screenshot 2023-09-28 at 13 37 02](https://github.com/flutter/flutter/assets/48603081/51d840a2-7e71-40e7-80c1-1afd4a8503ee)




I remember there was no trailing button on the  `FilterChip` specs. It can be confirmed using the Wayback machine (March 2023)

![Screenshot 2023-09-28 at 13 36 55](https://github.com/flutter/flutter/assets/48603081/30e4407f-739e-46f5-b479-3d56369d5fb6)

**Comment by TahaTesser** [comment]
blocked by https://github.com/flutter/flutter/pull/135751
