### ISSUE TITLE
TextFormField - when validation fails, cursor color is assigned to be the same as the error text color

### ISSUE THREAD

**Issue by lirantzairi** [flutter/flutter#135580]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Hi, I'm reopening this issue: https://github.com/flutter/flutter/issues/134451 because it was locked without solving

1. Run the code sample
2. Tap on the text field to set the focus to it
3. The cursor color is green as expected
4. Write something, no matter what, so the "Invalid" error text will appear in red under the text field

### Expected results

The cursor color should stay green.

### Actual results

The cursor color turns red like the error text color.
If this is intended, then the documentation of TextFormField should be updated, although I don't see the point in keeping this behavior.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Form(
          autovalidateMode: AutovalidateMode.always,
          child: Center(
            child: Padding(
              padding: const EdgeInsets.all(20),
              child: TextFormField(
                cursorColor: Colors.green,
                validator: (value) {
                  if (value?.isNotEmpty == true) return 'Invalid';
                  return null;
                },
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>
</details>

### Logs

<details><summary>Logs</summary>

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel unknown, 3.10.5, on macOS 13.3 22E252 darwin-arm64, locale en-IL)
    ! Flutter version 3.10.5 on channel unknown at /Users/liran/code/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    • Framework revision 796c8ef792 (3 months ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/liran/Library/Android/sdk
    • Platform android-34, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554             • android-arm64  • Android 14 (API 34) (emulator)
    • Liran's iPhone (mobile)     • 00008101-000265A20C84001E • ios            • iOS 16.6 20G75
    • macOS (desktop)             • macos                     • darwin-arm64   • macOS 13.3 22E252 darwin-arm64
    • Chrome (web)                • chrome                    • web-javascript • Google Chrome 116.0.5845.179

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by dam-ease** [comment]
Hi @lirantzairi. Thanks for this. I can reproduce this on the latest `master` and `stable`.  I see the functionality seems to have changed with https://github.com/flutter/flutter/pull/119225 which is a fix to this issue https://github.com/flutter/flutter/issues/113750.


https://github.com/flutter/flutter/assets/53122008/677907f4-0e86-4c4e-86c0-b1453332eacf


I'd label this for more insights from the team.
Thank you!

**Comment by lirantzairi** [comment]
Thanks @dam-ease :)

In https://github.com/flutter/flutter/pull/119225 and https://github.com/flutter/flutter/issues/113750 you wrote that it's per Material guidelines. However these guidelines don't specify that the cursor color **has to be** the same as the error text color. They only put these two examples:
![image](https://github.com/flutter/flutter/assets/42715466/7c278cf5-e292-417b-8710-e2a719d9d36a)
![image](https://github.com/flutter/flutter/assets/42715466/77d3277f-eae8-4e99-8c48-411fcce665ec)
But to me they just look like examples, not a rule specification. If we do consider them as a rule then the border color would also need to be the same color as the error text but in practice we're able to change them in Flutter using
```dart
focusedErrorBorder: UnderlineInputBorder(
  borderSide: BorderSide(
    color: Colors.green,
  ),
),
```

**Comment by Renzo-Olivares** [comment]
Hi @lirantzairi, thank you for reporting this issue. The color of the cursor when the `TextField` is in an error state should be customizable through `InputDecoration.errorStyle`, or `ThemeData.colorScheme.error` (if a custom `InputDecoration.errorStyle` is not being used). Does this fit your use-case?

**Comment by lirantzairi** [comment]
@Renzo-Olivares Using these suggestions will change both the cursor and error text color together. The issue here is that we don't have a way to set only the cursor color in an error state without changing the error text color. Material guidelines don't seem to require these two elements to have the same color. Consider this fairly standard example:
<img width="374" alt="Screenshot 2023-09-29 at 0 15 28" src="https://github.com/flutter/flutter/assets/42715466/7c20b53a-953d-422e-be89-7defe9d91328">
What you see here is a filled white text field on a blue background. Naturally the contrast between the two colors is high enough to make the text field distinguishable from the background. Now, since the error text appears on the background while the cursor appears in the text field, it would be very hard to find one color that would fit both these elements. In this case I wanted the error color to be white, which forced the cursor to be white too and therefore you can't see it.

**Comment by Renzo-Olivares** [comment]
@lirantzairi Thanks for the clear example. It makes sense that we should make the error cursor customizable somehow. We would definitely welcome a PR with this change. Some good places to put this would either be in `ThemeData`/`InputDecoration`/`DefaultSelectionStyle`. Going to switch the priority to p2 for now since this is a reasonable add.

**Comment by lirantzairi** [comment]
@Renzo-Olivares Started working on the PR. I can either:
1. Add functionality to set the error cursor color on top of what we have today
2. Revert [#119225](https://github.com/flutter/flutter/pull/119225)

If we agree that the Material guidelines don't require the error cursor color to match the error text color then option 2 is better but that will create a breaking change. What do you prefer?

**Comment by Renzo-Olivares** [comment]
Hi @lirantzairi, apologies for the delayed response i've been OOO. I think we should go with option 1 so we don't cause a breaking change and we add functionality as well. Thank you for working on this!

**Comment by lirantzairi** [comment]
@Renzo-Olivares Thanks :)
Created a pr: #136121
