### ISSUE TITLE
revert bot not landing reverts

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#135670]
https://github.com/flutter/flutter/pull/135668

It looks like the fluttergithubbot is not able to lgtm a change, and my lgtm appears to to appease the checks.

As a reminder, it is a requirement that the framework gardener and engine sheriff be able to land reverts without waiting for approvals or presubmit checks.

cc @godofredoc @ricardoamador

**Comment by zanderso** [comment]
I landed the revert the old way at https://github.com/flutter/flutter/pull/135672. Removing P0.

**Comment by ricardoamador** [comment]
Well shoot. Okay I think I know what the issue is. @godofredoc can you make sure that auto-submit[bot] is able to push to this repo please?

**Comment by godofredoc** [comment]
The problem is that the PR is trying to merge to main rather than master.

**Comment by godofredoc** [comment]
The error is correct, main is just the replica of master. Nothing should be merged to main.

**Comment by ricardoamador** [comment]
Not sure if this notifies on edits but @zanderso ^ was main intentionally the target of the merge?

**Comment by godofredoc** [comment]
Let's land a change and revert to validate the functionality end to end. We can use https://github.com/flutter/flutter/pull/135567

**Comment by zanderso** [comment]
No. I only applied the `revert` label to the PR I wanted to revert, and that is the PR that was created as a result.

**Comment by zanderso** [comment]
You can see me adding the label here: https://github.com/flutter/flutter/pull/135645

**Comment by ricardoamador** [comment]
Got it. Thanks.
