### ISSUE TITLE
Bottomsheet background breaks if used with alpha

### ISSUE THREAD

**Issue by Pablo-Aldana** [flutter/flutter#135659]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

On latest flutter version if you Create a modalBottomSheet with a background color using alpha
```
    showModalBottomSheet(
        backgroundColor: Theme.of(context).colorScheme.error.withAlpha(200),
        context: context,
        isScrollControlled: true,
        builder: (BuildContext context) {
          return Container(
            child: Center(child: Text("hello")),
          ) ;
        });
```
The bottom sheet it will "break" and weird behaviour with the on back screen will happen.

<img height="400" src="https://github.com/flutter/flutter/assets/9969839/c30d6528-2dfe-4a48-bf23-86e78a2acd1c">

you might appreciate the arrow at the bottom that is an animated widget from the screen is behind the modal and it should not appearing like this moving.

Not only that seems the way it is managing the alpha has changed from previous version as it might appreciated below with the colours,

NOTE: All test has been performed in iOS17 the ones that are the expected and the ones failing.
Devices tested:

Simulator iPhone 15 Pro Max 
Simulator iPhone SE

Real device iPhone XR
Real device Xiaomi RedMi

### Expected results

if you remove the alpha everything works as expected

<img height="400" src="https://github.com/flutter/flutter/assets/9969839/ed00b523-6631-414d-85fd-45b574364b54">

In the real application without examples you might well notice the difference between them 
Here is the real application with the stable version of flutter of July:

<img height="400" src="https://github.com/flutter/flutter/assets/9969839/07d36b3a-6916-4b65-8f29-24ae4524a57b">

Here the real application with the latest flutter version:

<img height="400" src="https://github.com/flutter/flutter/assets/9969839/34c15a72-f3de-4261-9d2d-8083765599c9">

### Actual results

The bottom sheet it will "break" and weird behaviour with the on back screen will happen.

<img height="400" src="https://github.com/flutter/flutter/assets/9969839/c30d6528-2dfe-4a48-bf23-86e78a2acd1c">

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

//import 'package:flutter_gen/gen_l10n/app_localizations.dart';
class FlutterIssue extends StatelessWidget {
  const FlutterIssue({super.key});

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        Container(
          width: MediaQuery.of(context).size.width,
          height: MediaQuery.of(context).size.height,
          child: Center(
            child: TextButton(
                onPressed: () {
                  showModal(context);
                },
                child: Text("OPEN ME")),
          ),
        ),
        SwipeUp_flutterIssue()
      ],
    );
  }

  showModal(context) {
    showModalBottomSheet(
        backgroundColor: Colors.amber.withAlpha(200),
        context: context,
        isScrollControlled: true,
        builder: (BuildContext context) {
          return Container(
            child: Center(child: Text("hello")),
          ) /*const VideoManager()*/;
        });
  }
}

class SwipeUp_flutterIssue extends StatefulWidget {
  const SwipeUp_flutterIssue(
      {Key? key,
      /*required this.onModifyUserResult*/
      this.color})
      : super(key: key);
  final Color? color;
  @override
  SwipeUp_flutterIssueState createState() => SwipeUp_flutterIssueState();
}

class SwipeUp_flutterIssueState extends State<SwipeUp_flutterIssue>
    with SingleTickerProviderStateMixin {
  /*late AnimationController controller;
  late Animation<Offset> offset;
*/

  late final AnimationController _controller = AnimationController(
    duration: const Duration(seconds: 2),
    vsync: this,
  )..repeat(reverse: true);
  late final Animation<Offset> _offsetAnimation = Tween<Offset>(
    begin: const Offset(0, 0.2),
    end: const Offset(0, 0),
  ).animate(CurvedAnimation(
    parent: _controller,
    curve: Curves.elasticIn,
  ));
  Color color = Colors.white; // Colors.transparent;
  bool _visible = false;
  @override
  void initState() {
    super.initState();
    Future.delayed(const Duration(milliseconds: 2000), () {
      // color = Colors.white;
      _visible = true;
      setState(() {});
    });
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
//    controller.forward();
    color = widget.color ?? Colors.white;
    return SizedBox(
        height: 100,
        child: SlideTransition(
            position: _offsetAnimation,
            child: AnimatedOpacity(
              // If the widget is visible, animate to 0.0 (invisible).
              // If the widget is hidden, animate to 1.0 (fully visible).
              opacity: _visible ? 1.0 : 0.0,
              duration: const Duration(milliseconds: 2500),
              child: Icon(
                FontAwesomeIcons.anglesUp,
                color: color,
                size: 25,
              ),
            )));
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

Adding videos for better clarifications:

Actual result with flutter 3.13.5 and the code sample provided.

https://github.com/flutter/flutter/assets/9969839/497b1846-be25-4ad4-925b-a335dd5bf4de

Actual result with flutter 3.13.5 and real application

https://github.com/flutter/flutter/assets/9969839/5832f91d-c4e5-4212-ae77-9ec3b2920bc9

Expected behaviour with flutter stable version of July, real app in production:

https://github.com/flutter/flutter/assets/9969839/9029ca56-0c4c-4c81-aebc-57f2db3afe45

</details>

### Logs

<details><summary>Logs</summary>

No errors shown on logs it is just UI behaviour
```console
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.5, on macOS 13.5.2 22G91
    darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK
    version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[!] Android Studio (version unknown)
    ✗ Unable to determine Android Studio version.
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.82.2)
[✓] VS Code (version 1.79.0-insider)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for Pablo’s
      Apple Watch. Ensure the device is unlocked and
      discoverable via Bluetooth. (code -27)
[✓] Network resources
```

</details>

EDIT: I've managed to tested in 3.10.6 and works as usual. I've seen releases notes and recently has been introduced some changes on the bottomsheet that could affect but didn't managed to confirm it: https://github.com/flutter/flutter/pull/128455/commits/37b265290f3858ac8a588079c96c0428209f8d2d

**Comment by dam-ease** [comment]
Hi @Pablo-Aldana. Thanks for filing this. I can't seem to reproduce this on my end (Testing on iOS 16.4), does this occur only with iOS 17? Tested on Android as well but can't seem to reproduce it.

![Screenshot_1695904440](https://github.com/flutter/flutter/assets/53122008/d9c1215d-b6dd-4964-a8f2-021b787af517)


<details><summary>Code Sample Used</summary>
<p>

```dart
import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(body: FlutterIssue());
  }
}

//import 'package:flutter_gen/gen_l10n/app_localizations.dart';
class FlutterIssue extends StatelessWidget {
  const FlutterIssue({super.key});

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        Container(
          width: MediaQuery.of(context).size.width,
          height: MediaQuery.of(context).size.height,
          child: Center(
            child: TextButton(
                onPressed: () {
                  showModal(context);
                },
                child: Text("OPEN ME")),
          ),
        ),
        SwipeUp_flutterIssue()
      ],
    );
  }

  showModal(context) {
    showModalBottomSheet(
        backgroundColor: Colors.amber.withAlpha(200),
        context: context,
        isScrollControlled: true,
        builder: (BuildContext context) {
          return Container(
            child: Center(child: Text("hello")),
          ) /*const VideoManager()*/;
        });
  }
}

class SwipeUp_flutterIssue extends StatefulWidget {
  const SwipeUp_flutterIssue(
      {Key? key,
      /*required this.onModifyUserResult*/
      this.color})
      : super(key: key);
  final Color? color;
  @override
  SwipeUp_flutterIssueState createState() => SwipeUp_flutterIssueState();
}

class SwipeUp_flutterIssueState extends State<SwipeUp_flutterIssue>
    with SingleTickerProviderStateMixin {
  /*late AnimationController controller;
  late Animation<Offset> offset;
*/

  late final AnimationController _controller = AnimationController(
    duration: const Duration(seconds: 2),
    vsync: this,
  )..repeat(reverse: true);
  late final Animation<Offset> _offsetAnimation = Tween<Offset>(
    begin: const Offset(0, 0.2),
    end: const Offset(0, 0),
  ).animate(CurvedAnimation(
    parent: _controller,
    curve: Curves.elasticIn,
  ));
  Color color = Colors.white; // Colors.transparent;
  bool _visible = false;
  @override
  void initState() {
    super.initState();
    Future.delayed(const Duration(milliseconds: 2000), () {
      // color = Colors.white;
      _visible = true;
      setState(() {});
    });
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
//    controller.forward();
    color = widget.color ?? Colors.white;
    return SizedBox(
        height: 100,
        child: SlideTransition(
            position: _offsetAnimation,
            child: AnimatedOpacity(
              // If the widget is visible, animate to 0.0 (invisible).
              // If the widget is hidden, animate to 1.0 (fully visible).
              opacity: _visible ? 1.0 : 0.0,
              duration: const Duration(milliseconds: 2500),
              child: Icon(
                FontAwesomeIcons.anglesUp,
                color: color,
                size: 25,
              ),
            )));
  }
}
``` 

</p>
</details> 

<details><summary>flutter doctor -v</summary>
<p>

```
[✓] Flutter (Channel stable, 3.13.6, on macOS 13.0 22A380 darwin-arm64, locale
    en-NG)
    • Flutter version 3.13.6 on channel stable at
      /Users/damilolaalimi/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (30 hours ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        •
      android-arm64  • Android 14 (API 34) (emulator)
    • iPhone 14 Pro (mobile)      • 6548B0D1-7674-4306-9852-198C465F1104 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • iPhone 14 Pro Max (mobile)  • BB55E997-7F31-462D-B3B1-6B177D9B40C7 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)             • macos                                •
      darwin-arm64   • macOS 13.0 22A380 darwin-arm64
    • Chrome (web)                • chrome                               •
      web-javascript • Google Chrome 117.0.5938.132

[✓] Network resources
    • All expected network resources are available.

• No issues found!
``` 

</p>
</details>

**Comment by Pablo-Aldana** [comment]
Hi @dam-ease  

Thanks in advance for the super quick answer!! 🚀

You are right I have tested it in an android simulator and it does not happen but it does on iOS 17.0 simulator and real device

Digging a bit more I've seen that the issue occurs with elevation > 0 (a parameter I have omitted in the pass) if elevation is 0 it does work as expected. 


In order to facilitate the debug I have created a repo with a dummy project https://github.com/Pablo-Aldana/flutter_bottom_sheet_issue 

In the meantime I will set elevation:0 on the showModalBottomSheet to achieve the desired behaviour


Thanks a lot again

**Comment by dam-ease** [comment]
Hi @Pablo-Aldana. Thanks for explaining further. We tested this on a device with iOS 17 and can see this works as expected. Also, testing with the minimal sample code below:

<details><summary>Code Sample</summary>
<p>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(body: FlutterIssue());
  }
}

//import 'package:flutter_gen/gen_l10n/app_localizations.dart';
class FlutterIssue extends StatelessWidget {
  const FlutterIssue({super.key});

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        Container(
          width: MediaQuery.of(context).size.width,
          height: MediaQuery.of(context).size.height,
          child: Center(
            child: TextButton(
                onPressed: () {
                  showModal(context);
                },
                child: Text("OPEN ME")),
          ),
        ),
        SwipeUp_flutterIssue()
      ],
    );
  }

  showModal(context) {
    showModalBottomSheet(
        backgroundColor: Colors.amber.withAlpha(200),
        context: context,
        isScrollControlled: true,
        builder: (BuildContext context) {
          return Container(
            child: Center(child: Text("hello")),
          ) /*const VideoManager()*/;
        });
  }
}

class SwipeUp_flutterIssue extends StatefulWidget {
  const SwipeUp_flutterIssue(
      {Key? key,
      /*required this.onModifyUserResult*/
      this.color})
      : super(key: key);
  final Color? color;
  @override
  SwipeUp_flutterIssueState createState() => SwipeUp_flutterIssueState();
}

class SwipeUp_flutterIssueState extends State<SwipeUp_flutterIssue>
    with SingleTickerProviderStateMixin {
  /*late AnimationController controller;
  late Animation<Offset> offset;
*/

  late final AnimationController _controller = AnimationController(
    duration: const Duration(seconds: 2),
    vsync: this,
  )..repeat(reverse: true);
  late final Animation<Offset> _offsetAnimation = Tween<Offset>(
    begin: const Offset(0, 0.2),
    end: const Offset(0, 0),
  ).animate(CurvedAnimation(
    parent: _controller,
    curve: Curves.elasticIn,
  ));
  Color color = Colors.white; // Colors.transparent;
  bool _visible = false;
  @override
  void initState() {
    super.initState();
    Future.delayed(const Duration(milliseconds: 2000), () {
      // color = Colors.white;
      _visible = true;
      setState(() {});
    });
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
//    controller.forward();
    color = widget.color ?? Colors.white;
    return SizedBox(
        height: 100,
        child: SlideTransition(
            position: _offsetAnimation,
            child: AnimatedOpacity(
              // If the widget is visible, animate to 0.0 (invisible).
              // If the widget is hidden, animate to 1.0 (fully visible).
              opacity: _visible ? 1.0 : 0.0,
              duration: const Duration(milliseconds: 2500),
              child: Icon(
                Icons.arrow_upward,
                color: color,
                size: 25,
              ),
            )));
  }
}
``` 

</p>
</details> 


Please can you share a demo video as well describing where the bug is and if possible the expected behaviour to help understand this issue better? 

| From Repo | Code above |
|--------|--------|
| <video src="https://github.com/flutter/flutter/assets/53122008/c81a1c5c-391a-442f-9c96-58bb3366b6eb"> | <video src="https://github.com/flutter/flutter/assets/53122008/3b4bd862-fc67-4690-983f-0670aafa32d3"> |

**Comment by stephaneleonard** [comment]
Hi, if I can share my own experience. It seems to be an issue with impeler, I use a bottomSheet with margin around the modal, and on android you can see the dark transparant background around, but on ios it bleed white color as if it was a blured shadow. I found 2 fix wich are

**Comment by dam-ease** [comment]
Hi @Pablo-Aldana. Thanks for your input. Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code that can reproduce this?

**Comment by tirth-multipl** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the [existing issues](https://github.com/flutter/flutter/issues)
> * [x]  I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)
> 
> ### Steps to reproduce
> On latest flutter version if you Create a modalBottomSheet with a background color using alpha
> 
> ```
>     showModalBottomSheet(
>         backgroundColor: Theme.of(context).colorScheme.error.withAlpha(200),
>         context: context,
>         isScrollControlled: true,
>         builder: (BuildContext context) {
>           return Container(
>             child: Center(child: Text("hello")),
>           ) ;
>         });
> ```
> 
> The bottom sheet it will "break" and weird behaviour with the on back screen will happen.
> 
> <img alt="" width="400" src="https://user-images.githubusercontent.com/9969839/271226884-c30d6528-2dfe-4a48-bf23-86e78a2acd1c.png">
> you might appreciate the arrow at the bottom that is an animated widget from the screen is behind the modal and it should not appearing like this moving.
> 
> Not only that seems the way it is managing the alpha has changed from previous version as it might appreciated below with the colours,
> 
> NOTE: All test has been performed in iOS17 the ones that are the expected and the ones failing. Devices tested:
> 
> Simulator iPhone 15 Pro Max Simulator iPhone SE
> 
> Real device iPhone XR Real device Xiaomi RedMi
> 
> ### Expected results
> if you remove the alpha everything works as expected
> 
> <img alt="" width="400" src="https://user-images.githubusercontent.com/9969839/271227229-ed00b523-6631-414d-85fd-45b574364b54.png">
> In the real application without examples you might well notice the difference between them Here is the real application with the stable version of flutter of July:
> 
> <img alt="" width="400" src="https://user-images.githubusercontent.com/9969839/271227786-07d36b3a-6916-4b65-8f29-24ae4524a57b.PNG">
> Here the real application with the latest flutter version:
> 
> <img alt="" width="400" src="https://user-images.githubusercontent.com/9969839/271227987-34c15a72-f3de-4261-9d2d-8083765599c9.png">
> ### Actual results
> The bottom sheet it will "break" and weird behaviour with the on back screen will happen.
> 
> <img alt="" width="400" src="https://user-images.githubusercontent.com/9969839/271226884-c30d6528-2dfe-4a48-bf23-86e78a2acd1c.png">
> ### Code sample
> Code sample
> ### Screenshots or Video
> Screenshots / Video demonstration
> ### Logs
> Logs
> ### Flutter Doctor output
> Doctor output
> EDIT: I've managed to tested in 3.10.6 and works as usual. I've seen releases notes and recently has been introduced some changes on the bottomsheet that could affect but didn't managed to confirm it: [37b2652](https://github.com/flutter/flutter/commit/37b265290f3858ac8a588079c96c0428209f8d2d)

It even breaks with Colors.transparent

**Comment by dam-ease** [comment]
Hi @tirth-multipl. Thanks for your input. Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code that can reproduce this?
