### ISSUE TITLE
friendly_chat is not aware of the iPhone X

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#13569]
https://10clouds.com/blog/flutter-cross-platform-apps/

Shows a picture of friendly_chat on a iphone X, seems like it's not respecting the safe area enough?

@collinjackson @cbracken Maybe this is already fixed?

**Comment by sethladd** [comment]
Good catch.

**Comment by collinjackson** [comment]
I think `_buildTextComposer`'s `Container` should have a `padding: new EdgeInsets.only(bottom: MediaQuery.of(context).padding.bottom)`. This will start to matter in step 3 of the UI codelab and needs to be propagated forward.

/cc @LarkAscending

**Comment by cbracken** [comment]
Arguably, introducing `SafeArea` is pretty valuable in teaching new developers how easy it is to account for system insets. I'm happy to make the code change, but we'll definitely want to update the docs to explain what's going on here.

**Comment by cbracken** [comment]
@LarkAscending I scheduled a quick catchup to run over the changes for this.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2082](https://github.com/flutter/website/issues/2082) via [**ZenHub**](https://www.zenhub.com/)
