### ISSUE TITLE
Allow customization of showMenu transition animation curves and duration

### ISSUE THREAD

**Issue by Caffeinix** [flutter/flutter#135638]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Currently `showMenu` (and classes that use it, such as `PopupMenuButton`) has a hard-coded 300ms animation when the menu opens or closes.  This cannot be modified by any means I have discovered.

This is inconsistent with `MenuAnchor`-based menus, which have no animation at all, and particularly for right-click context menus it feels far too slow.

### Proposal

Looking at the code, it would be fairly straightforward to allow the duration to be overridden via an optional parameter to `showMenu` and then passed through to the `_PopupMenuRoute` that's created to service the call.  Ideally, `PopupMenuButton` and friends would also accept that optional parameter and pass it through to `showMenu`.

**Comment by chunhtai** [comment]
should be a straight forward fix. @HansMuller does it make sense if we put the transitionDuration into the theme?

**Comment by alexvoina** [comment]
I have this issue too
