### ISSUE TITLE
Back button always pops app, and `Router._handleBackButtonDispatcherNotification` is never called

### ISSUE THREAD

**Issue by lukehutch** [flutter/flutter#135654]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I have been building an app using the Routemaster router library, which has always seemed to work fine before. Recently though, the Android Back button stopped working -- pressing Back pops the app every time, landing me back on the home screen.

I don't think I changed anything significant with the routing setup (Routemaster hasn't even seen a release in a long time), but I did upgrade Flutter a few times to the latest version, between when I know the back button was working, and now, when it no longer works.

I tried setting a breakpoint in `Router._handleBackButtonDispatcherNotification`, and this method is never called when the Back button is pressed. Also, my `RouterDelegate`'s `popRoute` method is never called when the Back button is pressed.

I verified that the root `Router` does in fact have a `backButtonDispatcher`, and that dispatcher has the `_handleBackButtonDispatcherNotification` callback added.

What could be going wrong here, and how do I even start to debug this, when there doesn't seem to be any Flutter code called when Back is pressed?

### Expected results

Back should work.

### Actual results

Back doesn't work.

### Code sample

<details><summary>Code sample</summary>

I can't share the full code, but it's just a basic Routemaster setup -- nothing special. It used to work.

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.13.6, on Fedora Linux 38 (Workstation Edition) 6.4.12-200.fc38.x86_64, locale en_US.utf8)
    • Flutter version 3.13.6 on channel stable at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (31 hours ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/luke/Android/Sdk
    • Platform android-UpsideDownCake, build-tools 33.0.1
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 16.0.6 (Fedora 16.0.6-2.fc38)
    • cmake version 3.27.3
    • ninja version 1.11.1
    • pkg-config version 1.8.0

[✓] Android Studio (version 2022.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 73.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.82.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.72.0

[✓] Connected device (3 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Linux (desktop)            • linux         • linux-x64      • Fedora Linux 38 (Workstation Edition) 6.4.12-200.fc38.x86_64
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 116.0.5845.110

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @lukehutch! 
`routemaster` is a 3rd package and there is no guarantee it will work well with the framework API changes without maintaining it. In order to investigate issue properly, please provide a minimal sample code (without using 3rd package) so that we can verify it. Thanks!

**Comment by lukehutch** [comment]
Hi @huycozy,

I know, this is not a bug report about Routemaster. As I pointed out, I set breakpoints in Flutter core classes, and Flutter doesn't seem to be getting the notifications.

I tried creating a minimal testcase, but I can't reproduce it. However, I dug deeper, and there's definitely an issue here, which I don't think has anything to do with Routemaster (but I'm not sure).

Flutter's `binding.dart` line 292 is:

```dart
    SystemChannels.navigation.setMethodCallHandler(_handleNavigationInvocation);
```

I set a breakpoint on this line (it was hit on application start), and I also set a notification on entry to `_handleNavigationInvocation` (it was never reached when the Back button is pressed). This means that the Flutter app is not being notified of the Back button press via the system navigation method channel.

I pushed this as far as I could, to the boundary between the system and Flutter. How do I debug further from here?

**Comment by huycozy** [comment]
Thanks for the update. Looks like you've progressed your debugging a bit further. From my point of view, it will only happen in "a certain case", which you need to build to be able to reproduce the issue. It will help the domain team have direction in their investigation (hope you understand this).

I would suggest you isolate the affected pages, then try using framework route/go_router instead to see if the issue can be reproduced or not.

**Comment by lukehutch** [comment]
@huycozy Here's a fairly minimal testcase using Routemaster (I'm still working to convert this to other routers to see if I can trigger it).

Just add routemaster to the pubspec.yaml file for a new project, and compile/run on the Android emulator.

Click the button to open the modal dialog, then observe that either the "Close modal" button or the `BackButton` correctly pops from the stack. However, when the modal is open, clicking the system Back button pops the entire app.

```dart
import 'package:flutter/material.dart';
import 'package:routemaster/routemaster.dart';

final navigatorKey = GlobalKey<NavigatorState>();

final router = RoutemasterDelegate(
  navigatorKey: navigatorKey,
  routesBuilder: (context) {
    return RouteMap(
      routes: {
        '/': (_) => MaterialPage(
              child: Scaffold(
                body: SafeArea(
                  child: Center(
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        ElevatedButton(
                          child: const Text('Open modal'),
                          onPressed: () => showFullScreenModal(
                            context: context,
                            child: Center(
                              child: ElevatedButton(
                                onPressed: () =>
                                    navigatorKey.currentState!.pop(context),
                                child: const Text('Close modal'),
                              ),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
            ),
      },
    );
  },
);

void showFullScreenModal(
    {required BuildContext context, required Widget child}) {
  navigatorKey.currentState!.push(
    PageRouteBuilder(
      opaque: false,
      pageBuilder: (BuildContext pageContext, _, __) {
        return Scaffold(
          backgroundColor: Colors.grey.shade300,
          body: SafeArea(
            child: Stack(
              children: [
                Column(
                  mainAxisAlignment: MainAxisAlignment.spaceAround,
                  children: [child],
                ),
                const BackButton(),
              ],
            ),
          ),
        );
      },
      transitionsBuilder: (context, animation, secondaryAnimation, child) =>
          SlideTransition(
        position: animation.drive(
            Tween(begin: const Offset(0.0, 1.0), end: Offset.zero)
                .chain(CurveTween(curve: Curves.ease))),
        child: child,
      ),
    ),
  );
}

void main() async {
  runApp(
    MaterialApp.router(
      routerDelegate: router,
      routeInformationParser: const RoutemasterParser(),
    ),
  );
}
```

**Comment by lukehutch** [comment]
@huycozy On further digging, I'm starting to believe you're right, Routemaster is doing something funky here that is messing up the back button behavior. Sorry for the distraction!

**Comment by lukehutch** [comment]
@huycozy After endless amounts of work bisecting away Dart source, then deps, then `android/` folder contents, I finally discovered what was causing the Back button to break for my app: I had `android:enableOnBackInvokedCallback="true"` in the `application` element of my `android/app/src/main/AndroidManifest.xml`. This disables the standard Flutter back button handling, because the standard `flutter create` does not add support for this model of interaction.

I created this issue about it: #135815
