### ISSUE TITLE
Impeller-golden tests failing on macOS 13

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#135620]
Impeller golden tests are failing on macOS 13 with Xcode 14.3.1.

The error:
```
Error uploading JSON file to GCS path skia-gold-flutter-engine...
x509: failed to load system roots and no roots provided; SecTrustSettingsCopyCertificates error: -36
```

https://ci.chromium.org/ui/p/flutter/builders/try.shadow/Mac%20Engine%20Drone/9563/overview

Looks like error -36 is an [I/O error](https://developer.apple.com/documentation/security/1542001-security_framework_result_codes/errsecio), but I'm not really sure what that means in this context.

Perhaps it's something wrong with the bot [mac-47-g572](https://chromium-swarm.appspot.com/bot?id=mac-47-g572)? 

Could be an issue with certificates trusting, but that's a different error code
https://github.com/golang/go/issues/42414#issuecomment-839498401
https://stackoverflow.com/questions/71731257/when-l-use-go-get-l-cant-download-package-x509-failed-to-load-system-roots-an

**Comment by vashworth** [comment]
@stuartmorgan @cyanglaz Any advice on this one? I'm not even sure how to label it. It seems like it could be an issue with the bot or maybe it's some issue with `goldctl`?

**Comment by chinmaygarde** [comment]
Triage: The root certificate store on the host machine looks to be missing the appropriate certifications. Perhaps we need to chase this down with the gold client?

**Comment by vashworth** [comment]
This is a blocker for https://github.com/flutter/flutter/issues/134736, which is part of our efforts to upgrade CI to macOS 13 and Xcode 15. 

@chinmaygarde Can we up the priority of this to P1? It's a blocker to our bigger effort of upgrading our CI

**Comment by vashworth** [comment]
Also, I ran it on a different machine to make sure it wasn't a machine-specific problem and got the same errors: https://chromium-swarm.appspot.com/task?id=6533dc2959074a10

**Comment by zanderso** [comment]
This is an issue with goldctl. We need help from the Skia team. Maybe @kjlubick or @jcgregorio can advise. This may be as simple as rolling the goldctl pin forward in the build config files like here: https://github.com/flutter/engine/blob/main/ci/builders/mac_host_engine.json#L149

**Comment by kjlubick** [comment]
I don't think this is an issue with the goldctl binary itself. Nothing about it has changed recently. I would be more inclined to believe that something needs to be installed on those machines to provide the certs.

**Comment by kjlubick** [comment]
Yes, the go version probably would have been updated twice in the last 12 months. You can try rolling the goldctl version if you like.

**Comment by vashworth** [comment]
Fixed by https://github.com/flutter/engine/pull/46771

Example: https://chromium-swarm.appspot.com/task?id=6537fecff3544710
