### ISSUE TITLE
"native assets for linux_x64" causes web tests to timeout

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#135624]
Recently there's been an increase in web test timeouts due to the compiler kicking off linux_x64 compilation in the middle of running web tests. Examples:

- https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20web_canvaskit_tests_0/37338/overview
- https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20web_canvaskit_tests_6/37182/overview
- https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_canvaskit_tests_5/10567/overview
- https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_canvaskit_tests_5/10552/overview
- https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_tests_7_last/13319/overview
- https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_tests_7_last/13314/overview

Issues filed by the bot:

- https://github.com/flutter/flutter/issues/135585
- https://github.com/flutter/flutter/issues/135581

The suspicious output in the logs looks like this:

```
00:22 +44: test/widgets/list_wheel_scroll_view_test.dart: pre-transform viewport A child is no longer painted after its last pixel leaves the viewport                                                 
00:22 +44: test/widgets/list_wheel_scroll_view_test.dart: viewport transformation Center child is magnified                                                                                            
00:23 +44: test/widgets/list_wheel_scroll_view_test.dart: viewport transformation Center child is magnified                                                                                            [+9421 ms] Discovered flutter_test_config.dart in /b/s/w/ir/x/w/flutter/packages/flutter/test
[   +3 ms] Compiler will use the following file as its incremental dill file: /b/s/w/ir/x/t/flutter_tools.BPYYLE/flutter_test_compiler.JUCQZT/output.dill
[        ] Listening to compiler controller...
[   +2 ms] Compiling file:///b/s/w/ir/x/t/flutter_tools.BPYYLE/flutter_web_platform.GGWQFP/listenerFDQEEA/listener.dart
[  +81 ms] Building native assets for linux_x64 debug.

00:24 +44: test/widgets/list_wheel_scroll_view_test.dart: viewport transformation Center child is magnified                                                                                            
00:25 +44: test/widgets/list_wheel_scroll_view_test.dart: viewport transformation Center child is magnified                                                                                            
00:26 +44: test/widgets/list_wheel_scroll_view_test.dart: viewport transformation Center child is magnified
...
10:23 +44 -1: test/widgets/list_wheel_scroll_view_test.dart: viewport transformation Center child is magnified [E]                                                                                     
  TimeoutException after 0:10:00.000000: Test timed out after 10 minutes.
  ../packages/test_api/src/backend/declarer.dart.js 705:36                    <fn>
```

Notice that the test is happily running right up until the "Discovered flutter_test_config.dart" and "Compiler will use" messages. Then the test immediately freezes and eventually times out.

I will deduplicate issues filed by the bot into this one.

**Comment by christopherfujino** [comment]
Yegor's confirming whether or not https://github.com/flutter/flutter/pull/135474 fixed this.

**Comment by yjbanov** [comment]
Tried again after rebasing and I don't see any flakes, so I'll consider it fixed. Thanks!
