### ISSUE TITLE
[CP - 3.13] Wait for CONFIGURATION_BUILD_DIR to update when debugging with Xcode

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#135610]
### Issue Link

https://github.com/flutter/flutter/issues/135442

### Commit Hash

3cfe372

### Target

stable

### PR Link

https://github.com/flutter/flutter/pull/135609

### Changelog Description

Fixes Xcode 15 install failure with physical iOS 17 devices related to being unable to access file system resources.

### Impacted Users

iOS Flutter developers

### Impact Description

Some iOS Flutter developers may experience an error when using Flutter CLI tools to run Flutter apps on iOS 17 physical devices.

### Workaround

Run the app from Xcode

### Risk

low

### Test Coverage

yes

### Validation Steps

This issue does not occur for everyone every time. I  was semi-consistently able to recreate using the following steps:

1. Create a flutter project
2. Open the project in Xcode
3. `flutter clean`
4. `flutter run --profile -v`

If I saw a print line `stderr: Current CONFIGURATION_BUILD_DIR: build/Debug-iphoneos while expecting xxx/build/ios/iphoneos` and then eventually see `stderr: CONFIGURATION_BUILD_DIR: xxx/build/ios/iphoneos`, that confirms it's working.

**Comment by itsjustkevin** [comment]
Approved by @christopherfujino in https://github.com/flutter/flutter/pull/135609.
