### ISSUE TITLE
cloud_firestore package version 0.1.2 not updated on pub.dartlang.org

### ISSUE THREAD

**Issue by bjornbjorn** [flutter/flutter#13561]
Latest version on pub.dartlang.org is 0.1.1 while the changelog references a 0.1.2 release:

https://pub.dartlang.org/packages/cloud_firestore#-changelog-tab-

**Comment by sethladd** [comment]
cc @goderbauer @collinjackson @kroikie

**Comment by goderbauer** [comment]
Easy fix! I uploaded a new version: https://pub.dartlang.org/packages/cloud_firestore

**Comment by kroikie** [comment]
@bjornbjorn

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/927. Any further collaboration will be done there.

**Comment by bjornbjorn** [comment]
Looks like this has been fixed so it can be closed https://github.com/flutter/flutter/issues/13561#issuecomment-351823394
