### ISSUE TITLE
Presubmit task on roll stuck in In Progress state even though the task failed, PR was closed

### ISSUE THREAD

**Issue by ricardoamador** [flutter/flutter#135640]
### Is there an existing issue for this?

- [X] I have searched the [existing infra issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-infra)

### Type of Request

bug

### Infrastructure Environment

LUCI, Github, Cocoon scheduler

### What is happening?

This pull request https://github.com/flutter/flutter/pull/135637 is showing a task that is in progress even though it has failed. Further more the task still shows as in progress even after the pull request was closed!

Here is the pull request closed with the In Progress task:
![image](https://github.com/flutter/flutter/assets/32242716/6e3e4d00-3e6b-4b1a-9d72-4db362cf17df)

Here is the failed task: https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20build_ios_framework_module_test/34046/overview

### Steps to reproduce

Step 1:
Step 2:
..
Step n:

### Expected results

I expect to see X when Y is finished.

**Comment by sealesj** [comment]
Very strange because I am now seeing that this task was marked as successful on the PR even though it failed
![Screenshot 2023-09-28 at 10 35 22 AM](https://github.com/flutter/flutter/assets/103135467/e710071e-133b-4c66-8e4e-a23597b97e44)

**Comment by keyonghan** [comment]
This sounds like the pub/sub message failed to get processed by the endpoint when the task status changes. Based on https://github.com/flutter/flutter/issues/135640#issuecomment-1739384681, the message seemed get processed in the end. 

I would look for the backend logs related to this specific checkrun to see if any useful info there.

**Comment by sealesj** [comment]
I do see `Bad state: No element` errors continuously occurring for this checkrun, however there is also this initial webhook error. Have you seen this before?
![Screenshot 2023-09-28 at 2 33 48 PM](https://github.com/flutter/flutter/assets/103135467/401600f6-19e2-41e8-9713-7815851633c8)

**Comment by sealesj** [comment]
It seems like https://pub.dev/documentation/_discoveryapis_commons/latest/_discoveryapis_commons/DetailedApiRequestError-class.html was not caught and caused this error due to having property `status` rather than `statusCode`?

**Comment by ricardoamador** [comment]
I think that is correct. I do remember Keyong made a change for this on the postsubmit side too. I will take a look in a bit.

**Comment by ricardoamador** [comment]
Ah okay I found it. Though this change might not directly translate to presubmit. Leaving for notes:
https://github.com/flutter/cocoon/commit/f6b39f5015bdaa60f967d2c97ba9e7b3963cf29a

**Comment by ricardoamador** [comment]
This could also be stale pub/sub messages. I have cleared the un-acked messages so we will see if this clears up the issue.

**Comment by ricardoamador** [comment]
Okay no more new errors for 20 minutes.

**Comment by ricardoamador** [comment]
Related in the same error and possibly condition: https://github.com/flutter/flutter/issues/135508

**Comment by ricardoamador** [comment]
Deploying a new version now. Added this change to hopefully address the issue: https://github.com/flutter/cocoon/pull/3111

**Comment by ricardoamador** [comment]
Okay here is an example of the odd behavior of what is being returned from the ciYaml:

![image](https://github.com/flutter/flutter/assets/32242716/48627ad9-239f-4ea7-888a-ff2341d2ddbc)

That example is from this pull request: https://github.com/flutter/flutter/pull/135691

**Comment by keyonghan** [comment]
Strange. That commit's ci.yaml is https://github.com/flutter/flutter/blob/b533c2a11d92949bbae28b7964be05793c41a461/.ci.yaml

**Comment by keyonghan** [comment]
I see the problem.

The checkrun was initially created with default branch `master`, but the default branch was updated to `main` when a manual rerun happens: https://github.com/flutter/cocoon/blob/main/app_dart/lib/src/service/luci_build_service.dart#L356, which is **incorrectly** based on the cipd version (which is always `main` for non-release branches).

The presubmit api auto retry happens based on the above manual retry using `main` branch, which caused all targets (without target level `enabled_branches` defined) missed when filtering targets https://github.com/flutter/cocoon/blob/main/app_dart/lib/src/model/ci_yaml/ci_yaml.dart#L171

The fix is to update the branch used in the manual checkrun rerun: https://github.com/flutter/cocoon/blob/main/app_dart/lib/src/service/luci_build_service.dart#L356

**Comment by ricardoamador** [comment]
Wow! Good catch!

**Comment by keyonghan** [comment]
https://github.com/flutter/cocoon/pull/3115 to fix.
