### ISSUE TITLE
Allow AppBar/SliverAppBar to take a single child

### ISSUE THREAD

**Issue by j4k0bk** [flutter/flutter#13568]
Sometimes its very useful to have a single child fill the app bar, for instance when a search field sould fill out the entire bar (and therefore display no title, actions, or whatever else).

**Comment by Hixie** [comment]
If you don't want the multi-child logic of AppBar, you can just use the widget that it's based on directly (PreferredSizeWidget and SliverPersistentHeader respectively, iirc).

**Comment by Hixie** [comment]
Please let me know if that answer is insufficient.
