### ISSUE TITLE
Mac_arm64 95% queue time jumps >11 mins exceeding SLO

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#135621]
The 95% queue time for Mac_arm64 has been roughly between 2 to 5 mins for weeks. In the recent cycle (09/11/2023-09/24/2023), the queue time jumps to 11.02 mins, exceeding SLO 10min.

**Comment by keyonghan** [comment]
Daily number of builds seem consistent for the past month:
<img width="764" alt="Screenshot 2023-09-27 at 10 21 54 AM" src="https://github.com/flutter/flutter/assets/54558023/6ef78a9e-a84a-4bae-9a64-5c151a5cdd32">

**Comment by keyonghan** [comment]
Packages repo (14 targets) now consumes most Mac_arm64 bots. Seems the execution time varies a lot. My guess here is that queue time jumps when multiple packages commits are merged in a short period of time with higher execution time.

<img width="1545" alt="Screenshot 2023-09-27 at 10 24 08 AM" src="https://github.com/flutter/flutter/assets/54558023/10eaa218-3104-49e6-9b39-d0fe96a864ed">

Are these large variations expected? /cc @stuartmorgan

**Comment by stuartmorgan** [comment]
> Are these large variations expected?

What are they variations in? I'm not clear on what this graph is exactly.

**Comment by keyonghan** [comment]
They are the daily median execution time of the specific builder.

**Comment by stuartmorgan** [comment]
Individual runs of a task are expected to have wildly varying times in flutter/packages due to our attempts to only test packages that can be affected by a change. A PR that changes a single package, for instance, will have ~0 execution time for most shards, whereas something like an engine roll will run every package, so have long runs on every shard.

**Comment by keyonghan** [comment]
I see. Then that may explain the queue time jump.
I will leave this bug open to track several cycles before giving a conclusion.

**Comment by keyonghan** [comment]
The mac_arm64 queue time has been relatively slow below 1min. Closing.
