### ISSUE TITLE
Testing docs need more detail on mocking

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#13562]
https://flutter.io/testing/ is our overview of how to test apps. More details about mocking would be very beneficial:

* Show an example of how to mock with `package:mockito`. For example, could show how to mock out a login state class.
* Needs to mention that widget tests also require mocking non-widget code, for example anything that requires a plugin.

**Comment by mit-mit** [comment]
Tagging for milestone 3 given how foundational this is

**Comment by Sfshaza** [comment]
@mit-mit, is this sufficient?

https://flutter.io/cookbook/testing/mocking/

**Comment by mit-mit** [comment]
That looks good, but we don't seem to link to it from https://flutter.io/testing/

**Comment by Sfshaza** [comment]
I'm not adding cross links at the moment, but will own this and add it soon.

**Comment by Sfshaza** [comment]
I'm holding off on cross linking right now, as that will just make the migration job harder for me. But I'm owning this and will fix.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1912](https://github.com/flutter/website/issues/1912) via [**ZenHub**](https://www.zenhub.com/)
