### ISSUE TITLE
Have hashValues() support even more values.

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1356]
and update `Theme` to use that.

**Comment by abarth** [comment]
We might want to ask for a VM intrinsic.  That could support an arbitrary number of arguments efficiently.

**Comment by Hixie** [comment]
See https://github.com/dart-lang/sdk/issues/25217

**Comment by Hixie** [comment]
cc @floitschG Do you think it would be possible for Dart to provide us with a version of hashValues that was better than the hack we have in dart:ui today?

**Comment by floitschG** [comment]
Providing a better way to combine hashCodes is on our list for Dart 2.0 library changes.

**Comment by kaikai4989** [comment]
Hi, any update on this one? I have a class that has 25 fields that need to be hashed.

**Comment by zoechi** [comment]
The related issue to combine hashCodes seems to be dart-lang/sdk#11617

**Comment by Hixie** [comment]
Since we've had so little need for this, I'm going to say we don't actually need it.
