### ISSUE TITLE
Force mandatory debugLabel on FocusNode

### ISSUE THREAD

**Issue by busslina** [flutter/flutter#135680]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I'm sick of having 'NO LABEL' on Flutter SDK widgets: 
![imagen](https://github.com/flutter/flutter/assets/73592852/227dd57a-8969-41cb-9075-cd14c59b8c9a)

### Proposal

Force to provide a debug label on all focus nodes

**Comment by huycozy** [comment]
Hi @busslina 
Could you share steps to reproduce along with a minimal sample code for this?

**Comment by busslina** [comment]
> Hi @busslina Could you share steps to reproduce along with a minimal sample code for this?

The problem is with the `(01) NO LABEL`. It must be inside MaterialApp. Sorry about not sharing a minimal code because it is a simple as that. The other `NO LABEL` were my bad due to putting the `debugLabel` inside `Focus`/``FcousScope` and not in its `Node`.

Thank you

**Comment by huycozy** [comment]
I'm still not quite clear about this. Could you please be more specific by sharing the detailed steps and a sample code?
