### ISSUE TITLE
E/flutter ( 5473): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Failed to create datagram socket (OS Error: Cannot assign requested address, errno = 99), address = 192.168.47.1, port = 54372

### ISSUE THREAD

**Issue by GautamSharma05** [flutter/flutter#135651]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a RawDatagramSocket and bind to a particular ipAddress not to any IPV4 in that case I am getting that issue.

### Expected results

I want to make a UDP connection using my mobile device to my other device with the **IP address and port** that I want to give. In my case, I want to fix **IP address and port**

### Actual results

Currently, I am not able to make a UDP connection with my Flutter app.

### Code sample

<details><summary>Code sample</summary>

```dart
 InternetAddress multicastAddress =  InternetAddress(Vars.iPAddressDefault);
    int multicastPort = Vars.iPPortDefault;
    RawDatagramSocket.bind(multicastAddress, multicastPort)
        .then((RawDatagramSocket socket){
      print('Datagram socket ready to receive');
      print('${socket.address.address}:${socket.port}');

      socket.joinMulticast(multicastAddress);
      print('Multicast group joined');

      socket.listen((RawSocketEvent e){
        Datagram? d = socket.receive();
        if (d == null) return;

        String message =  String.fromCharCodes(d.data).trim();
        print('Datagram from ${d.address.address}:${d.port}: ${message}');
      });
    });
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
E/flutter ( 5473): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Failed to create datagram socket (OS Error: Cannot assign requested address, errno = 99), address = 192.168.47.1, port = 54372
E/flutter ( 5473): #0      _NativeSocket.bindDatagram (dart:io-patch/socket_patch.dart:1051:7)
E/flutter ( 5473): <asynchronous suspension>
E/flutter ( 5473): 
```

</details>
 

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.4, on macOS 13.5.2 22G91 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.2)
[✓] VS Code (version 1.82.2)
[✓] Connected device (3 available)
    ! Error: Browsing on the local area network for Gautam’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network
      as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for iPhone 11. Ensure the device is unlocked and attached with a cable or associated with the same local area network as
      this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!

```

</details>

**Comment by dam-ease** [comment]
Hi @GautamSharma05. Thanks for filing this! I see this issue seems similar/related to https://github.com/flutter/flutter/issues/53477. Can you check this out please??

**Comment by GautamSharma05** [comment]
Hey @dam-ease. Thanks For helping. But #53477 does not work for me. Can you suggest me more or any other fixes availaible?

**Comment by dam-ease** [comment]
Thanks for your response @GautamSharma05. Okay, but can you confirm the issue being described in https://github.com/flutter/flutter/issues/53477 is similar to yours?
