### ISSUE TITLE
Socket Exception uncaught when request a down server

### ISSUE THREAD

**Issue by bkan36** [flutter/flutter#135681]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

On an http request to my server when it's off a Socket exception is thrown but I cannot caught it neither with a try-catch nor using runZonedGuarded.

### Expected results

I expect that my runZonedGuarded catch the socket exception.

### Actual results

code crash at 

   ` return await client.post(Uri.parse('$host/$loginSellerUrl'),`

**TERMINAL**

ClientException with SocketException: Connection failed (OS Error: Operation not permitted, errno = 1), address = 192.168.1.11, port = 1234, uri=http://192.168.1.11:1234//auth/login

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception
#0      NetworkClient.post.<anonymous closure>
network_client.dart:27
#1      _RootZone.runBinary (dart:async/zone.dart:1666:54)
#2      runZonedGuarded.<anonymous closure> (dart:async/zone.dart:1776:18)
#3      _Zone._processUncaughtError (dart:async/zone.dart:1081:14)
#4      _CustomZone.handleUncaughtError (dart:async/zone.dart:1285:5)
#5      Future._propagateToListeners (dart:async/future_impl.dart:790:16)
#6      Future._completeError (dart:async/future_impl.dart:649:5)
#7      _rootRunBinary (dart:async/zone.dart:1423:47)
#8      _CustomZone.runBinary (dart:async/zone.dart:1315:19)
#9      _FutureListener.handleError (dart:async/future_impl.dart:171:22)
#10     Future._propagateToListeners.handleError (dart:async/future_impl.dart:852:47)
#11     Future._propagateToListeners (dart:async/future_impl.dart:873:13)
#12     Future._completeError (dart:async/future_impl.dart:649:5)
#13     _rootRunBinary (dart:async/zone.dart:1423:47)
#14     _CustomZone.runBinary (dart:async/zone.dart:1315:19)
#15     _FutureListener.handleError (dart:async/future_impl.dart:171:22)
#16     Future._propagateToListeners.handleError (dart:async/future_impl.dart:852:47)
#17     Future._propagateToListeners (dart:async/future_impl.dart:873:13)
#18     Future._completeError (dart:async/future_impl.dart:649:5)
#19     _rootRunBinary (dart:async/zone.dart:1423:47)
#20     _CustomZone.runBinary (dart:async/zone.dart:1315:19)
#21     _FutureListener.handleError (dart:async/future_impl.dart:171:22)
#22     Future._propagateToListeners.handleError (dart:async/future_impl.dart:852:47)
#23     Future._propagateToListeners (dart:async/future_impl.dart:873:13)
#24     Future._completeError (dart:async/future_impl.dart:649:5)
#25     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:739:7)
#26     _rootRun (dart:async/zone.dart:1399:13)

### Code sample

<details><summary>Code sample</summary>

**WIDGET**

```dart
import 'package:bug/network_client/network_client.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  void apiCall() async {
    final http = NetworkClient();

    await http.post({'email': 'test@mail.com', 'pwd': 'qwerty123'});
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: const Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: apiCall,
        tooltip: 'API CALL',
        child: const Icon(Icons.wifi_calling_3_outlined),
      ),
    );
  }
}
```

**NETWORK CLIENT**

```dart
const loginSellerUrl = '/auth/login';
const host = 'http://192.168.1.11';
const port = 1234;

class NetworkClient {
  final client = Client();

  final Map<String, String> headers = <String, String>{
    'Content-Type': 'application/json'
  };

  Future<Response?> post(dynamic parameter) async {
    return runZonedGuarded<Future<Response?>>(() async {
      return await client.post(Uri.parse('$host/$loginSellerUrl'),
          body: json.encode(parameter), headers: headers);
    }, (error, stack) {
      log(error.toString());
      throw Exception();
    });
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[log] ClientException with SocketException: Connection failed (OS Error: Operation not permitted, errno = 1), address = 192.168.1.11, port = 1234, uri=http://192.168.1.11:1234//auth/login

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception
#0      NetworkClient.post.<anonymous closure>
network_client.dart:27
#1      _RootZone.runBinary (dart:async/zone.dart:1666:54)
#2      runZonedGuarded.<anonymous closure> (dart:async/zone.dart:1776:18)
#3      _Zone._processUncaughtError (dart:async/zone.dart:1081:14)
#4      _CustomZone.handleUncaughtError (dart:async/zone.dart:1285:5)
#5      Future._propagateToListeners (dart:async/future_impl.dart:790:16)
#6      Future._completeError (dart:async/future_impl.dart:649:5)
#7      _rootRunBinary (dart:async/zone.dart:1423:47)
#8      _CustomZone.runBinary (dart:async/zone.dart:1315:19)
#9      _FutureListener.handleError (dart:async/future_impl.dart:171:22)
#10     Future._propagateToListeners.handleError (dart:async/future_impl.dart:852:47)
#11     Future._propagateToListeners (dart:async/future_impl.dart:873:13)
#12     Future._completeError (dart:async/future_impl.dart:649:5)
#13     _rootRunBinary (dart:async/zone.dart:1423:47)
#14     _CustomZone.runBinary (dart:async/zone.dart:1315:19)
#15     _FutureListener.handleError (dart:async/future_impl.dart:171:22)
#16     Future._propagateToListeners.handleError (dart:async/future_impl.dart:852:47)
#17     Future._propagateToListeners (dart:async/future_impl.dart:873:13)
#18     Future._completeError (dart:async/future_impl.dart:649:5)
#19     _rootRunBinary (dart:async/zone.dart:1423:47)
#20     _CustomZone.runBinary (dart:async/zone.dart:1315:19)
#21     _FutureListener.handleError (dart:async/future_impl.dart:171:22)
#22     Future._propagateToListeners.handleError (dart:async/future_impl.dart:852:47)
#23     Future._propagateToListeners (dart:async/future_impl.dart:873:13)
#24     Future._completeError (dart:async/future_impl.dart:649:5)
#25     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:739:7)
#26     _rootRun (dart:async/zone.dart:1399:13)
#27     _CustomZone.run (dart:async/zone.dart:1301:19)
#28     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#29     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#30     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#31     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
Lost connection to device.
Exited
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.1, on macOS 13.6 22G120 darwin-arm64, locale en-TN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.82.2)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @bkan36 
This seems to be similar to https://github.com/dart-lang/sdk/issues/49774. Your question is more suitable on [dart-lang/sdk](https://github.com/dart-lang/sdk) repository, so please file another issue there if it is not a similar one. 

Closing this as it's not a Flutter framework issue.
