### ISSUE TITLE
[Impeller] Investigate validation issues and re-enable command pool resets on a background thread.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#135690]
Introduced in https://github.com/flutter/engine/pull/46166. This issue tracks investigating the validation issues and removing the flag to get back the performance gains.

**Comment by chinmaygarde** [comment]
cc @matanlurey. Just filing a followup in case there wasn't already one.

**Comment by matanlurey** [comment]
Closed by https://github.com/flutter/engine/pull/47184. Yay!
