### ISSUE TITLE
[Flutter 3.15.0-15.2.pre] - `flutter pub get` hanging on dependency downgrade

### ISSUE THREAD

**Issue by AlexDochioiu** [flutter/flutter#135664]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Add a dependency to the yaml file
2. Run flutter pub get
3. Downgrade the dep to the prev version
4. Run flutter pub get

### Expected results

The command should finish successfully.

### Actual results

The command seems to do the task and hang.

### Code sample

Running the terminal command prints the following and then hangs until I manually kill it.
```
➜  repo git:(main) ✗ flutter pub get
Resolving dependencies... 
! collection 1.18.0 (overridden)
  flutter_secure_storage_windows 2.1.1 (3.0.0 available)
< freezed 2.4.2 (was 2.4.3) (2.4.3 available)
  material_color_utilities 0.5.0 (0.8.0 available)
  meta 1.9.1 (1.10.0 available)
  web 0.1.4-beta (0.2.2-beta available)
Changed 1 dependency!
5 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
```

P.s. Running flutter pub get afterwards works fine.

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

➜  critical git:(main) ✗ flutter --version       
Flutter 3.15.0-15.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 0d074ced6c (7 days ago) • 2023-09-21 10:24:15 -0700
Engine • revision 453411bcf3
Tools • Dart 3.2.0 (build 3.2.0-134.1.beta) • DevTools 2.27.0

**Comment by dam-ease** [comment]
Hi @AlexDochioiu. Thanks for filing this! I see you are on the beta channel, I can't seem to reproduce the hand on the latest `master` channel. Are you able to switch to confirm this as well?
