### ISSUE TITLE
[Impeller] `impeller_component` wipes out `defines`

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#135685]
Adding `defines` definitions to an `impeller_component` has no effect on the compilation of the component.  I believe this is because `impeller_public_config` wipes out the defines: https://github.com/flutter/engine/blob/9789dbc2ec3f06ee56837bf86f9dcf451be8599a/impeller/BUILD.gn#L11
```c
config("impeller_public_config") {
  include_dirs = [ ".." ]

  defines = [] # <-- Here

  if (impeller_debug) {
    defines += [ "IMPELLER_DEBUG=1" ]
  }
```

## reproduction steps
1) Add `defines = [ " FOOBAR " ]` to the aiks impeller_component
2) In `canvas.h` add `#ifndef FOOBAR\n#error hi\n#endif`
3) Notice that the error is triggered

**Comment by matanlurey** [comment]
Nice find!

**Comment by gaaclarke** [comment]
It just needs to be switched to:
```
  if (!defined(defines)) {
    defines = []
  }
```

I plan on doing it as part of my canvas recorder pr, but in case that gets changed up I don't want us to lose this.

**Comment by gaaclarke** [comment]
Actually, that doesn't fix it.  I'm having a hard time understanding why it isn't being respected.

**Comment by gaaclarke** [comment]
I think this may be working WAI for GN although it is surprising behavior.  It has to do with how `source_set` isn't actually a target.  The solution was to put the define in a config, then add that to the `public_configs` of the source set.
