### ISSUE TITLE
Flutter macOS Sonoma Xcode build error

### ISSUE THREAD

**Issue by sametates4** [flutter/flutter#135768]
After the macOS Sonoma update, Flutter projects are not working in Xcode. The error message for macOS is " /Users/sametates/Desktop/development/flutter/project_eagle/build/macos/Build/Products/Debug/project_eagle.app: resource fork, Finder information, or similar detritus not allowed Command CodeSign failed with a nonzero exit code ** BUILD FAILED **. "

flutter doctor `[✓] Flutter (Channel stable, 3.13.6, on macOS 14.0 23A344 darwin-arm64, locale tr-TR)
    • Flutter version 3.13.6 on channel stable at /Users/sametates/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (3 days ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/sametates/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 117.0.5938.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!`

**Comment by KhalidSaud** [comment]
I have the same exact issue and I'm stuck, I need solution too.

**Comment by tung18417** [comment]
For temporary fix you have to run on non iCloud directory. Ex. Home directory (~)

**Comment by chhofi** [comment]
I can confirm. Same issue for me after the update to macOS 14.0.

**Comment by sametates4** [comment]
> For temporary fix you have to run on non iCloud directory. Ex. Home directory (~)

After moving my project files to the Home directory (~), I was able to open them without any issues. thanks

**Comment by darshankawar** [comment]
@sametates4 
It looks like you are hitting https://github.com/flutter/flutter/issues/123583 and https://github.com/flutter/flutter/issues/130639 so I suggest you to follow-up in these issue for further updates.
