### ISSUE TITLE
Directory.current differs from PWD on macos when built

### ISSUE THREAD

**Issue by alexeyinkin** [flutter/flutter#135740]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Directory.current differs from PWD on macos. This happens only in Flutter, not in pure Dart apps.

Flutter macos:
1. Create a new Flutter app.
2. Replace `main.dart` with the attached file.
3. Add macos platform: `flutter create --platforms macos .`
4. Replace `macos\Runner\Release.entitlements` with the attached file (disable sandbox).
5. `flutter build macos`
6. `open macos/Runner.xcworkspace`
7. In Xcode, run the app.

Flutter linux:
1. Create a new Flutter app.
2. Replace `main.dart` with the attached file.
3. Add linux platform: `flutter create --platforms linux .`
5. `flutter build linux`
6. Run the built app: `build/linux/x64/release/bundle/project_name`

Dart macos:
1. `dart compile exe main_pure_dart.dart`
2. `./main_pure_dart.exe`

### Expected results

Both Flutter and Dart apps show the same for the two sources of the current directory: `Directory.current.path` and `Platform.environment['PWD']`.

### With `flutter build`:
Flutter macos: `Platform.environment['PWD']` is correct, but `Directory.current.path` shows the root directory `/`.
Flutter linux: Correct.
Dart: Correct.

### With `flutter run`:
All platforms including macos show identical paths.

### Code sample

<details><summary>main.dart (Flutter)</summary>

```dart
import 'dart:io';

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Table(
          defaultColumnWidth: const IntrinsicColumnWidth(),
          children: [
            TableRow(
              children: [
                const Text('Directory.current:   '),
                Text(Directory.current.path),
              ],
            ),
            TableRow(
              children: [
                const Text('PWD:   '),
                Text(Platform.environment['PWD'] ?? ''),
              ],
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

<details>
<summary>Release.entitlements</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<!--<key>com.apple.security.app-sandbox</key>
	<true/>-->
</dict>
</plist>
```

</details>

<details>
<summary>main_pure_dart.dart</summary>

```dart
import 'dart:io';

void main() {
  print(Directory.current.path);
  print(Platform.environment['PWD']);
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots</summary>

`flutter run -d macos`

<img width="513" alt="image" src="https://github.com/flutter/flutter/assets/44893228/22b4360f-3897-4369-a76c-d01de8ee71c2">

`flutter build macos`

<img width="530" alt="image" src="https://github.com/flutter/flutter/assets/44893228/539cf76c-d383-4c38-82e8-0f6d4874777c">

`flutter run -d linux`

![Screenshot from 2023-09-29 12-18-52](https://github.com/flutter/flutter/assets/44893228/aa9204b3-264f-4ddd-8be0-ea3130f61180)

`flutter build linux`

![Screenshot from 2023-09-29 11-15-25](https://github.com/flutter/flutter/assets/44893228/1d5c62a1-ffd4-4452-963e-e0857f772d99)

</details>

### Flutter Doctor output

<details><summary>macos: flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.13.6, on macOS 13.6 22G120 darwin-arm64
    (Rosetta), locale en-GE)
    • Flutter version 3.13.6 on channel stable at /Users/ai/bin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (2 days ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/ai/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.6 22G120 darwin-arm64
      (Rosetta)
    • Chrome (web)    • chrome • web-javascript • Google Chrome 117.0.5938.92

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

<details><summary>linux: flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.13.6, on Ubuntu 22.04 LTS 6.2.0-33-generic,
    locale en_US.UTF-8)
    • Flutter version 3.13.6 on channel stable at
      /home/alexey/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (2 days ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[!] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /home/alexey/Android/Sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for
      more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/alexey/bin/android-studio
    • Flutter plugin version 65.2.2
    • Dart plugin version 211.7811
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Connected device (3 available)
    • SM T585 (mobile) • 52006be146d18475 • android-arm    • Android 8.1.0 (API
      27)
    • Linux (desktop)  • linux            • linux-x64      • Ubuntu 22.04 LTS
      6.2.0-33-generic
    • Chrome (web)     • chrome           • web-javascript • Google Chrome
      116.0.5845.140

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by stuartmorgan** [comment]
This is not a bug, it's a misunderstanding of how GUI apps work on macOS.

> Flutter macos: `Platform.environment['PWD']` is correct, but `Directory.current.path` shows the root directory `/`.

What you are describing as "correct" here is actually arbitrary. macOS provides *no guarantees* about the working directory of a GUI application, nor does it guarantee anything about the value of most environment variables. If you run it directly from Terminal you will inherit the working directory and environment from that context (as with all of your examples on other platforms, and the `flutter run` case on macOS). But when the application is launched through other mechanisms, such as Xcode, or opening the app from Finder (the usual way apps are launched), those values are decided by the OS.

You should never assume anything about the working directory of a GUI application. If you want to work with paths you should be starting from well defined locations.

**Comment by alexeyinkin** [comment]
Thanks for clarification @stuartmorgan 

Still I believe if we have `PWD` environment variable then `Directory.current` should stick to it.

This variable may be arbitrary from the app's own perspective, but its value or absence for each use case is defined by the operating system and is reproducible.

It's one thing to have this variable content "arbitrary" as decided by the OS, and completely another thing to let Flutter mess with it on top of what the operating system supplies. It's just a different level of problem and indirection.

As for my case, I am building an internal tool for my team, so I am fine with forcing users to run it from terminal.

But I can think of many points why diverting `Directory.current` from `PWD` if it exists is wrong:
1. Inconsistent behavior between `flutter run` and the built app within macos.
2. Inconsistent behavior between operating systems.
3. Inconsistent behavior of some otherwise reusable Dart code between Flutter and non-Flutter.
4. Overriding of what the [Dart documentation](https://api.flutter.dev/flutter/dart-io/Directory/current.html) assumes without explicitly telling it to users.

What if someone has a valid use of `Directory.current` on Linux where it works correctly and needs to port it on Mac quickly to just work even with a weird way to run it? (My case.)
Should we bar this option for them just because it is not how things are traditionally done on the new target OS?

I don't think we should assume use cases and have this added uncertainty when we have chance to keep things more consistent, as the OS tells us.

So I still think this is a bug that should be re-opened.

**Comment by stuartmorgan** [comment]
> Still I believe if we have `PWD` environment variable then `Directory.current` should stick to it.

Directory.current is implemented using native functionality that returns the *actual* working directory, rather than an environment variable that can be overridden. You will see exactly the same difference in a non-Flutter macOS application if you compare the current directory from `NSFileManager` and the environment from `NSProcessInfo`.

> and completely another thing to let Flutter mess with it on top of what the operating system supplies.

It doesn't.

> But I can think of many points why diverting `Directory.current` from `PWD` if it exists is wrong

Please feel free to file a bug against Apple if you want changes in how the current working directory of a process is defined.

> Inconsistent behavior between `flutter run` and the built app within macos.

That difference is due to the way the process is launched, and has nothing to do with Flutter itself.

> Inconsistent behavior between operating systems.

Flutter does not control operating system behavior.

> Inconsistent behavior of some otherwise reusable Dart code between Flutter and non-Flutter.

There is no inconsistency between Flutter and non-Flutter. The difference is in how you are launching the application. If you want your Flutter application to behave like a command-line tool, you are welcome to run it exclusively as such (step 6 in my comment above).

> Overriding of what the [Dart documentation](https://api.flutter.dev/flutter/dart-io/Directory/current.html) assumes without explicitly telling it to users.

Nothing on that page claims that the env variable `PWD` is how the current directory is defined.

> What if someone has a valid use of `Directory.current` on Linux where it works correctly and needs to port it on Mac quickly to just work even with a weird way to run it?

Then they are welcome to do so, and run their app exclusively in the weird way that gives them the results that they want. But that's not what your steps to reproduce do; you launched the app from Xcode rather than directly running the executable.

>  when we have chance to keep things more consistent, as the OS tells us.

The behavior you are objecting to *is* the OS behavior.

> So I still think this is a bug that should be re-opened.

Flutter is not going to unilaterally change the definition of a process's working directory on macOS.

**Comment by alexeyinkin** [comment]
Thanks for the details on the OS behavior, it makes all the sense now.

For anyone else finding this, the easiest workaround is

```dart
Directory.current = Directory(Platform.environment['PWD'] ?? '/');
```

**Comment by stuartmorgan** [comment]
Also, I recommend that you try running your pure-Dart example on Linux with:
```
$ PWD=something ./main_pure_dart.exe
```

I'm not sure why you believe that `PWD` *controls* working directory; it's not true on Linux either.

**Comment by alexeyinkin** [comment]
That was just a hint I was given here: https://stackoverflow.com/a/77197579/11382675
And it works in my controlled environment.

**Comment by stuartmorgan** [comment]
Nothing in that answer claims that the `PWD` environment variable defined the working directory of a process (on any platform), as you assert earlier should be true.
