### ISSUE TITLE
Firebase API NexusLowRes,version=29, emulator flaky. Re-enable when possible.

### ISSUE THREAD

**Issue by ricardoamador** [flutter/flutter#135784]
More details are available at [ https://console.firebase.google.com/project/flutter-infra-staging/testlab/histories/bh.f93c781079d437/matrices/4629674857943472580 ].
WARNING: Need help for test execution [NexusLowRes-29-en-portrait]? Please join the #test-lab Slack channel at https://firebase.community// and include test matrix ID [matrix-3i93ff86mb1gb] with your question.

| outcome | test_axis_value | test_details |
| --- | --- | --- |
| Passed | Nexus5-21-en-portrait | -- |
| Passed | Nexus5-22-en-portrait | -- |
| Passed | Nexus5-23-en-portrait | -- |
| Passed | Nexus6P-26-en-portrait | -- |
| Passed | Nexus6P-27-en-portrait | -- |
| Inconclusive | NexusLowRes-29-en-portrait | Infrastructure failure |

Current open issue with the FTL team regarding fixing this: https://buganizer.corp.google.com/issues/302753598

**Comment by keyonghan** [comment]
@reidbaker Do we still need this testbed from firebase lab for test validation?

**Comment by reidbaker** [comment]
I think we should assume yes unless there is evidence otherwise.

**Comment by ricardoamador** [comment]
Reenabling this and one other.
