### ISSUE TITLE
[in_app_purchase] Fix docs reference to `finishPurchase` to say `completePurchase`

### ISSUE THREAD

**Issue by TheCarpetMerchant** [flutter/flutter#135759]
### Is there an existing issue for this?

- [X] I have searched the [existing package issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Apackage)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### What package does this bug report belong to?

in_app_purchase

### What target platforms are you seeing this bug on?

iOS

### Have you already upgraded your packages?

Yes

### Steps to reproduce

finishPurchase is mentionned in the doc, but does not exist in the package. So, is that still relevant ? If so, where do I need to call this ?

**Comment by huycozy** [comment]
Could you please cite the documentation source along with the use case for `finishPurchase`? As I can see, it seems to be `completePurchase` which will invoke `finishTransaction` on iOS/macOS.

**Comment by huycozy** [comment]
IMHO, this could be a documentation issue. Perhaps, it's `completePurchase` but I'm not sure.

**Comment by droidbg** [comment]
@stuartmorgan @huycozy I like to pick this up.

**Comment by droidbg** [comment]
@stuartmorgan I have raised a PR, could you please review it when you have time. 
https://github.com/flutter/packages/pull/5081
