### ISSUE TITLE
[Impeller] OpenGLES: Enable `GL_CHECK`s on debug mode (not `--unopt`)

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#135767]
@jonahwilliams and I believe that, at least on Vulkan, we are now enabling validation errors on _debug_ mode, i.e. debug builds of the engine. That's valuable because not only will it run in most of our unit tests, end users that run the engine in debug mode will get/log these GL errors.

This issue is to be consistent with Vulkan (and perhaps Metal), and run `GL_CHECK` on _debug_ mode.

(Currently it only runs on `--unopt`, which AFAICT most engine developers don't actively use/isn't tested)

**Comment by chinmaygarde** [comment]
sgtm. I believe this is as simple as adding `|| flutter_runtime_mode == "debug"` to https://github.com/flutter/engine/blob/f7f4b51d29331e441ae05e7c52d5b8fc9063909a/impeller/tools/impeller.gni#L43.

Note that some GL errors are recoverable and there should still be some recoverable error mechanism. I don't think the existing `AutoErrorCheck` has a great way to do this. But perhaps I am overthinking it. Enabling checking by default in debug seems like a fine option to begin with and gets us more coverage than we currently have.

BTW, is there an existing `GL_CHECK` macro you are talking about? Or just a hypothetical one.

**Comment by matanlurey** [comment]
> Note that some GL errors are recoverable and there should still be some recoverable error mechanism

I don't think (?) we crash today, it's just logged similar to Vulkan validation errors? I can try it out!

> BTW, is there an existing `GL_CHECK` macro you are talking about? Or just a hypothetical one.

Sorry, `GL_CHECK` being the OpenGL API, but yes, `AutoErrorCheck` is what we use today.

**Comment by jonahwilliams** [comment]
Right now the Vulkan validation errors print a nasty message, but won't crash the application unless ... they happen to crash. So explicitly exiting probably shouldn't be a part of this functionality, but printing a nasty message that we can udate the tests to check for?

**Comment by chinmaygarde** [comment]
> Vulkan validation errors print a nasty message.

lol, I spent a non-trivial of time formatting those things 🙃 

> but won't crash the application unless ... they happen to crash.

[We can configure those to crash](https://github.com/flutter/engine/blob/f3a4cab69962486f1b3c710284871306ffc1ddcd/vulkan/vulkan_debug_report.cc#L171). There used to be a ton of validation errors during bringup. But it may be a good idea now to make this consistent across all backends.

**Comment by jonahwilliams** [comment]
Its a well formatted message! It just scary text!
