### ISSUE TITLE
[Impeller] Image cropped when drawn with translate and MatrixImageFilter

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#135777]
I found this bug when looking into https://github.com/flutter/flutter/issues/126583, it may be a more simple case, but seems to manifest differently.

cc @bdero 

## version
7b989a28514edbfa3191a91031c1ebc5d86e0e89

## test

```c++
TEST_P(AiksTest, MatrixImageFilterMagnify) {
  Canvas canvas;
  canvas.Scale(GetContentScale());
  auto image = std::make_shared<Image>(CreateTextureForFixture("airplane.jpg"));
  canvas.DrawImage(image, {100, 100}, {});
  canvas.Translate({600, -200});
  canvas.SaveLayer({
      .image_filter = std::make_shared<MatrixImageFilter>(
          Matrix{
              2, 0, 0, 0,  //
              0, 2, 0, 0,  //
              0, 0, 2, 0,  //
              0, 0, 0, 1   //
          },
          SamplerDescriptor{}),
  });
  canvas.DrawImage(image, {0, 0}, Paint{.color = Color(1.0, 1.0, 1.0, 0.5)});
  canvas.Restore();

  ASSERT_TRUE(OpenPlaygroundHere(canvas.EndRecordingAsPicture()));
}
```

## screenshot
<img width="1021" alt="Screenshot 2023-09-29 at 3 40 11 PM" src="https://github.com/flutter/flutter/assets/30870216/e1929966-6e81-4260-8385-7a8b76bbc3d9">

**Comment by gaaclarke** [comment]
Here is the render when the translate is set to (600, 0)

<img width="1024" alt="Screenshot 2023-09-29 at 3 49 20 PM" src="https://github.com/flutter/flutter/assets/30870216/edf3f103-ec21-4c85-a28e-b992939a555f">

**Comment by gaaclarke** [comment]
So the offscreen render pass is rendering to a viewport that is the incorrect size, that's where the cropping is coming from.  setViewport and setScissorRect have the wrong dimensions

## works (translation 600,0)
<img width="800" alt="Screenshot 2023-09-29 at 4 36 34 PM" src="https://github.com/flutter/flutter/assets/30870216/6158aedb-d636-4ec9-9b47-eb88a24e5253">

## broke (translation 600,-200)
<img width="800" alt="Screenshot 2023-09-29 at 4 34 28 PM" src="https://github.com/flutter/flutter/assets/30870216/c7b9c519-3ed0-49c8-8f7f-340d0eb89837">

**Comment by jonahwilliams** [comment]
I think this is actually the same issue as @flar found in entity pass. Change L205 to  !image_filter->IsTranslationOnly() and it works for me. @gaaclarke give it a shot on your end too?

**Comment by gaaclarke** [comment]
> I think this is actually the same issue as @flar found in entity pass. Change L205 to !image_filter->IsTranslationOnly() and it works for me. @gaaclarke give it a shot on your end too?

@jonahwilliams L205 of what file?

**Comment by gaaclarke** [comment]
found it, it does make it render correctly
```diff
--- a/impeller/entity/entity_pass.cc
+++ b/impeller/entity/entity_pass.cc
@@ -202,7 +202,7 @@ std::optional<Rect> EntityPass::GetSubpassCoverage(
   // has deviated too much from the parent pass to safely intersect with the
   // pass coverage limit.
   coverage_limit =
-      (image_filter && image_filter->IsTranslationOnly() ? std::nullopt
+      (image_filter && !image_filter->IsTranslationOnly() ? std::nullopt
                                                          : coverage_limit);
 
   auto entities_coverage = subpass.GetElementsCoverage(coverage_limit);
```

**Comment by jonahwilliams** [comment]
Sorry, entity_pass.cc, but I see you found it!

**Comment by bdero** [comment]
Yeah that line is wrong and the fix LGTM.
