### ISSUE TITLE
Page transitions should trigger both next and previous pages

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#135734]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Currently we can define page transitions for the page that's being pushed or popped. So any transition animations will only be triggered for the top-most page in the navigation stack. This limits our options of animations, since the previous page won't have any transitions triggered when the top-most page is transitioning.

For example, if I want to make a transition where a new page slides from the bottom and the old page is pushed to the top, while it does some crazy animation, I can't under the current API, since the old page transition builder won't be triggered.

### Proposal

We should have transition builders for all the transitions defined in `RouteAware`. Currently we only have for `didPop` and  `didPush`, but we lack transition control for when `didPushNext` and `didPopNext` were triggered.

**Comment by darshankawar** [comment]
@feinstein 
Can you take a look at [this](https://github.com/flutter/flutter/issues/22079) issue and check if it resembles your case and proposal ?

**Comment by Muddassar087** [comment]
Page transition is a major need most of the time this feature needs to be implemented. As most work arounds are not effective and efficient.

**Comment by darshankawar** [comment]
Thanks for the feedback @feinstein 
Since the other issue already has a priority, I'll close this in favor of it. You may follow-up in that issue for further updates and share your findings in it for better tracking. If you disagree, write in comments and I'll reopen it.
