### ISSUE TITLE
[Android] `file_selector_android` Android integration test fails on AVD running API 34

### ISSUE THREAD

**Issue by camsim99** [flutter/flutter#135756]
When trying to get the `flutter/packages` tests running on AVDs (Android virtual devices) with Android 34 (https://github.com/flutter/packages/pull/4804*), the `FileSelectorAndroidTest` fails in the `Linux_android android_platform_tests_shard_1 master` build (example: https://ci.chromium.org/ui/p/flutter/builders/try/Linux_android%20android_platform_tests_shard_1%20master/1750/overview) with an error that has so far not been reproducible (i) locally, (ii) on a Linux virtual machine, and (iii) on a devicelab machine.

Suspected causes are:

-  A dialog may be appearing on the emulator causing what the test is searching for to not be found.
- A missing graphical interface

*I've made some test changes in that particular PR, but they shouldn't impact the issue.

**Comment by camsim99** [comment]
Closing as a duplicate of https://github.com/flutter/flutter/issues/136757.

**Comment by ricardoamador** [comment]
I created the following pull request for testing as Camille was out on vacation I could not update her pull request: https://github.com/flutter/packages/pull/5157

And found that for some reason when we use sdk 34 with emulators 34 her test fails. But with Android sdk 33 and emulators version 34 they pass: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8766965849984793121/+/u/Run_package_tests/native_integration_tests/stdout

**Comment by ricardoamador** [comment]
I just removed the unit tests from running. Also it seems like we are filtering the tests to only run certain ones so is there a way to reduce the number of packages that are being built? This takes roughly 30+ minutes of the hour of test time to build all of those packages.

**Comment by camsim99** [comment]
Ah I see where you removed the native tests [here](https://github.com/flutter/packages/pull/5157/files#diff-48c8d4f1614d1045ca0319830739bd6fba01a1abf095fd924634318048692f80). On a build like this one https://ci.chromium.org/ui/p/flutter/builders/try/Linux_android%20android_platform_tests_api_33_shard_1%20stable/8/overview from https://github.com/flutter/packages/pull/5157/checks?check_run_id=17792079265 can you show me how you see all of the packages are being built?

**Comment by ricardoamador** [comment]
Sure can. From your linked build the step is here: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8766965849984793121/+/u/Run_package_tests/build_examples/stdout

It's called build_examples. Though I am not sure if you need to build all of that stuff.

**Comment by camsim99** [comment]
@stuartmorgan Do you have any insight as to why `build-examples` is building all of the packages examples even though it still is filtering to certain packages? For example, on https://ci.chromium.org/ui/p/flutter/builders/try/Linux_android%20android_platform_tests_api_33_shard_1%20master/13/overview I see:
```
--packages-for-branch: running on branch "HEAD".
Running for all packages, since a file has changed that could affect the entire repository.
--filter-packages-to is excluding packages that are not included in: file_selector,path_provider,quick_actions,webview_flutter
```
but it's building all of the examples. We think this may be part of the reason the tests are timing out (on https://github.com/flutter/packages/pull/5105 for example).

**Comment by stuartmorgan** [comment]
> @stuartmorgan Do you have any insight as to why `build-examples` is building all of the packages examples even though it still is filtering to certain packages?

Yes, looking at the tooling code I have a bug in the `filter-packages-to` logic when the "Running for all packages" case is triggered; it doesn't build the exclude list correctly. I won't have time to fix that today unfortunately, but I can definitely fix it tomorrow.

**Comment by ricardoamador** [comment]
So I was digging around in there as well, can we limit the run using the '--packages' flag for purposes of testing? That way we can just tell it to run and build examples for file_selector per se?

**Comment by ricardoamador** [comment]
Looks like another bug: 
```
Executing command [
  '/usr/bin/bash',
  '/b/s/w/ir/x/w/packages/script/tool_runner.sh',
  'build-examples',
  '--apk',
  '--filter-packages-to=script/configs/still_requires_api_33_avd.yaml',
  '--packages=file_selector',
]
```

Then I get this error: 
```
Only one of the package selection arguments (packages, run-on-changed-packages, run-on-dirty-packages, packages-for-branch, current-package) can be provided.
```

I only provided the packages option, so either the message is not up to date (cannot use packages with --filter-packages-to) or this is some other issue with a combined default flag I am not aware of.

**Comment by camsim99** [comment]
I would assume maybe you can't use `--filter-packages-to` and `packages`. Can you try using just `--packages`?

**Comment by ricardoamador** [comment]
Hmm, Okay. Let me try that.

**Comment by ricardoamador** [comment]
@camsim99 I was kind of able to bypass the restriction on the packages flags and was able to test only file selector:
https://ci.chromium.org/ui/p/flutter/builders/try/Linux_android%20android_platform_tests_api_33_shard_1%20stable/13/overview
The integration tests passed and the drive examples passed as well but that step failed due to:
```
The following packages had errors:
  packages/file_selector/file_selector:
    No tests ran (use --exclude if this is intentional).
 ```
However the android ones did run though.

**Comment by camsim99** [comment]
That's great! Hopefully that means that once we reduce the time of building packages, we will see the tests pass.

**Comment by stuartmorgan** [comment]
https://github.com/flutter/packages/pull/5182 should fix `filter-packages-to`.

**Comment by ricardoamador** [comment]
I'll try another run today.

**Comment by mossmana** [comment]
Assigning to @camsim99 just for tracking purposes as it appears there are multiple people actively involved with the solution. Feel free to find another assignee if it makes sense to do so.

**Comment by ricardoamador** [comment]
@camsim99 the test ran fine again and must faster too (thanks @stuartmorgan). Though the drive examples are still failing but without a clear error, to me at least. The integration tests passed again too. 
https://ci.chromium.org/ui/p/flutter/builders/try/Linux_android%20android_platform_tests_api_33_shard_1%20stable/15/overview

**Comment by stuartmorgan** [comment]
> Though the drive examples are still failing but without a clear error, to me at least.

That looks like the script that was running lost the flag to pass [this exclusion file](https://github.com/flutter/packages/blob/main/script/configs/exclude_integration_android.yaml)

**Comment by ricardoamador** [comment]
@stuartmorgan that is the issue! @camsim99 can you take a look here: https://ci.chromium.org/ui/p/flutter/builders/try/Linux_android%20android_platform_tests_api_33_shard_1%20stable/17/overview
Stuarts fix worked and the run time is allowing the test to finish.

**Comment by camsim99** [comment]
> @stuartmorgan that is the issue! @camsim99 can you take a look here: https://ci.chromium.org/ui/p/flutter/builders/try/Linux_android%20android_platform_tests_api_33_shard_1%20stable/17/overview Stuarts fix worked and the run time is allowing the test to finish.

Looks like this works! I updated my own PR for testing these changes, and it seems to be running and working as well (https://github.com/flutter/packages/pull/5105). Thank you so much!

**Comment by camsim99** [comment]
Thank you all for the help! I am going to update `file_selector_android` to run on AVDs running 34 in a future PR, but I will file separate issues to (i) track my progress on that (and on all of the [other packages I'm currently excluding](https://github.com/flutter/packages/blob/main/script/configs/still_requires_api_33_avd.yaml) and (ii) bump the Linux_android dependency causing this failure to 34.
