### ISSUE TITLE
Shrine title text isn't centered

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#13575]
Open Shrine on iPhone X and notice the title text isn't centered. The word SHRINE should be directly below the notch, centered.

![99542](https://user-images.githubusercontent.com/5479/34010938-418591ec-e0c3-11e7-8a57-dba7e27ee50a.jpg)

**Comment by sethladd** [comment]
I'm not sure if this is a generic issue with framework, or something with iPhone X.

cc @cbracken

**Comment by cbracken** [comment]
Thanks! Did some looking and the Contacts and other demos look right. This looks specific to the Shrine demo, which uses a lot of customisation. Tested on a few other devices and it doesn't look specific to the iPhone X.

 I've got a couple last Gallery cleanups; I'll take a look at this at the same time.

**Comment by sethladd** [comment]
Thanks for taking a look!

**Comment by cbracken** [comment]
Looks like this is also the case for Android actually. Fix out in #13586.

**Comment by cbracken** [comment]
Fixed.

**Comment by sethladd** [comment]
Wow, thank you! That was fast :)
