### ISSUE TITLE
Mirgrate Android build configurations from Groovy to Kotlin DSL

### ISSUE THREAD

**Issue by ahmedhnewa** [flutter/flutter#135786]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Hi, I already know Kotlin DSL has been around for a while and everyone knows that

but the Android Studio latest version is now by default using Kotlin DSL instead of Groovy

[Source](https://developer.android.com/build/releases/gradle-plugin#kotlin-dsl)

Kotlin DSL provides many features and null safety and prevents a lot of runtime errors

So I see it's necessary to update the default Android project

or why not make flutter generate the Android project using android studio directly so like
I go to android studio and then create the project

and then flutter will make it changes to the project

I suggest to provide that option

even if you don't plan on use it as default
at least add it as an options

so developers save some time

### Proposal

![Android website](https://github.com/flutter/flutter/assets/73608287/7f352a66-2405-42c8-839c-16c8452898fe)

![Android studio](https://github.com/flutter/flutter/assets/73608287/0c526171-799b-4b36-a4fa-d9045bc173f0)

**Comment by huycozy** [comment]
Thanks for the report!
I see there are open issues addressing the case you described https://github.com/flutter/flutter/issues/121541 (this is a more detailed issue), https://github.com/flutter/flutter/issues/93238.

Closing this issue as a duplicate. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
