### ISSUE TITLE
facing issue in local_auth: ^2.1.7 package

### ISSUE THREAD

**Issue by arivananthapandian** [flutter/flutter#135746]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

 Run the below mention function in both ios and android . Also before running it make sure that your device is not enrolled to any of the security (like pin, pattern , biometrics etc...)

1) canCheckBiometrics
2) isDeviceSupported()

### Expected results

In both ios and android , the functions should do the following

1) canCheckBiometrics - It should indicate whether hardware support is available or not
2) isDeviceSupported() - It should indicate whether security is enrolled in device or not.

### Actual results

In Android its working as expected .
But in ios , its working opposite

1) canCheckBiometrics - It  indicates whether security is enrolled in device or not. 
2) isDeviceSupported() -It indicates whether hardware support is available or not

so it totally opposite to the expected result . So please change it as soon as poosible

### Code sample

<details><summary>Code sample</summary>

```dart

import 'package:flutter/material.dart'; // Import the Flutter Material package for UI components.

import 'package:local_auth/local_auth.dart'; // Import the local authentication package.



void main() {
  runApp(const MyApp()); // Entry point of the app, where we run the 'MyApp' widget.
} 

// Create a stateful widget called 'MyApp'.
class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState(); // Create the state for 'MyApp'.
}

// Create the state class for 'MyApp'.
class _MyAppState extends State<MyApp> {

  final LocalAuthentication auth = LocalAuthentication(); // Create an instance of LocalAuthentication.

  _SupportState _supportState = _SupportState.unknown; // Define a state for device support.

  bool isBiometricAvailable = false;

  

  @override
  void initState() {

    super.initState();

    // Check if the device supports biometrics and update the support state accordingly.
    auth.canCheckBiometrics.then(
          (bool isSupported) => setState(() => _supportState = isSupported
              ? _SupportState.supported
              : _SupportState.unsupported),
        );

    auth.isDeviceSupported().then((value) => setState(() => isBiometricAvailable = value));
             
  }


  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Plugin example app'),
        ),
        body: ListView(
          padding: const EdgeInsets.only(top: 30),
          children: <Widget>[
            Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                // Display a loading spinner if device support is unknown.
                if (_supportState == _SupportState.unknown)
                  const CircularProgressIndicator()
                // Display a message if the device supports biometrics.
                else if (_supportState == _SupportState.supported)
                  const Text('This device is supported')
                // Display a message if the device doesn't support biometrics.
                else
                  const Text('This device is not supported'),

                const Divider(height: 100), // Add a divider for spacing.

                // Display whether biometrics can be checked.
                Text('Can check biometrics: $isBiometricAvailable\n'),

                const Divider(height: 100), // Add a divider for spacing.
                
              ]
            ),
          ],
        ),
      ),
    );
  }
}

// Define an enumeration for the support state of biometrics.
enum _SupportState {
  unknown,
  supported,
  unsupported,
}




```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by dam-ease** [comment]
Hi @arivananthapandian. Thanks for filing this. I see there is an already open issue describing this case https://github.com/flutter/flutter/issues/116179. 
Closing this in favour of the already open issue, kindly upvote, comment and follow up for updates.
Thank you!
