### ISSUE TITLE
[web] persistent_bottom_sheet_test.dart is infrequently flaky

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#135728]
This hasn't been picked up by the flake bot, but poking around the dashboard I found two occurrences of `persistent_bottom_sheet_test.dart` flaking out:

- https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8768952368461841073/+/u/run_test.dart_for_web_tests_shard_and_subshard_3/test_stdout
- https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8768667925900091937/+/u/run_test.dart_for_web_tests_shard_and_subshard_3/test_stdout

The specific test is "Verify that a back button resets a persistent BottomSheet" and it fails like this:

```
01:25 +105 ~1: test/material/persistent_bottom_sheet_test.dart: Verify that a back button resets a persistent BottomSheet                                                                              
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: exactly one matching candidate
  Actual: _TextWidgetFinder:<Found 0 widgets with text "Item 22": []>
   Which: means none were found but one was expected

When the exception was thrown, this was the stack:
../dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:3  throw_
../packages/matcher/src/expect/prints_matcher.dart.js 436:22                    fail
../packages/matcher/src/expect/prints_matcher.dart.js 433:12                    _expect
../packages/matcher/src/expect/prints_matcher.dart.js 368:12                    expect$
../packages/flutter_test/src/test_text_input_key_handler.dart.js 9381:12        expect$
persistent_bottom_sheet_test.dart.js 3818:21                                    <fn>
../dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50           <fn>
../packages/stack_trace/src/stack_zone_specification.dart.js 187:98             <fn>
../packages/stack_trace/src/stack_zone_specification.dart.js 239:16             [_run]
../packages/stack_trace/src/stack_zone_specification.dart.js 187:80             <fn>
../dart-sdk/lib/async/zone.dart 1407:47                                         _rootRunUnary
../dart-sdk/lib/async/zone.dart 1308:19                                         runUnary
../dart-sdk/lib/async/future_impl.dart 162:18                                   handleValue
../dart-sdk/lib/async/future_impl.dart 846:44                                   handleValueCallback
../dart-sdk/lib/async/future_impl.dart 875:13                                   _propagateToListeners
../dart-sdk/lib/async/future_impl.dart 647:5                                    [_completeWithValue]
../dart-sdk/lib/async/future_impl.dart 721:7                                    <fn>
../packages/fake_async/fake_async.dart.js 140:40                                flushMicrotasks
../packages/flutter_test/src/test_text_input_key_handler.dart.js 10530:19       <fn>
../dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54           runBody
../dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5           _async
../packages/flutter_test/src/test_text_input_key_handler.dart.js 10527:62       <fn>
../dart-sdk/lib/async/future.dart 280:37                                        <fn>
../packages/stack_trace/src/stack_zone_specification.dart.js 239:16             [_run]
../packages/stack_trace/src/stack_zone_specification.dart.js 182:71             <fn>
../dart-sdk/lib/async/zone.dart 1391:47                                         _rootRun
../dart-sdk/lib/async/zone.dart 1301:19                                         run
../dart-sdk/lib/async/zone.dart 1209:7                                          runGuarded
../dart-sdk/lib/async/zone.dart 1249:23                                         <fn>
../packages/stack_trace/src/stack_zone_specification.dart.js 239:16             [_run]
../packages/stack_trace/src/stack_zone_specification.dart.js 182:71             <fn>
../dart-sdk/lib/async/zone.dart 1399:13                                         _rootRun
../dart-sdk/lib/async/zone.dart 1301:19                                         run
../dart-sdk/lib/async/zone.dart 1209:7                                          runGuarded
../dart-sdk/lib/async/zone.dart 1249:23                                         callback
../dart-sdk/lib/async/schedule_microtask.dart 40:11                             _microtaskLoop
../dart-sdk/lib/async/schedule_microtask.dart 49:5                              _startMicrotaskLoop
../dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7           <fn>

The test description was:
  Verify that a back button resets a persistent BottomSheet
════════════════════════════════════════════════════════════════════════════════════════════════════

01:25 +105 ~1 -1: test/material/persistent_bottom_sheet_test.dart: Verify that a back button resets a persistent BottomSheet [E]                                                                       
  Test failed. See exception logs above.
  The test description was: Verify that a back button resets a persistent BottomSheet
  

To run this test again: /b/s/w/ir/x/w/flutter/bin/cache/dart-sdk/bin/dart test test/material/persistent_bottom_sheet_test.dart -p chrome --plain-name 'Verify that a back button resets a persistent BottomSheet'
```

**Comment by yjbanov** [comment]
The bot finally picked it up. Raising to P0.

**Comment by yjbanov** [comment]
Update: I tried reproducing this in https://github.com/flutter/flutter/pull/135729 by forcing the test to run many times, but I have yet to reproduce this. May need some intuition from the framework team on this one.

**Comment by yjbanov** [comment]
It looks like this also happens in `list_wheel_scroll_view_test.dart`. One common pattern is that both tests use `tester.fling`. Perhaps there's something unpredictable in fling emulation?

**Comment by yjbanov** [comment]
I found that, when the test flakes out, `pumpAndSettle` does not make the `fling` gesture to scroll forward like the test expects. Here's a normal successful run (with my extra logging added):

```
00:07 +9: Verify that a back button resets a persistent BottomSheet
>>> 14: before fling: offset = 0; items = (0, 5)
>>> 15: after fling: offset = 324; items = (6, 17)
>>> 16: after pumpAndSettle: offset = 971.3987783959512; items = (19, 30)
```

And here's the failing one:

```
00:08 +9: Verify that a back button resets a persistent BottomSheet                                                                                                                                    
>>> 14: before fling: offset = 0; items = (0, 5)
>>> 15: after fling: offset = 324; items = (6, 17)
>>> 16: after pumpAndSettle: offset = 324; items = (6, 17)
```

See that "after pumpAndSettle" shows the exact same scroll offset, and renders the exact same widgets, as at the time when the fling gesture was initiated.

**Comment by yjbanov** [comment]
After a little more investigation I see that the fling gesture's final pointer-up event does not result in the `ScrollDragController` going ballistic. Investigating this part now.

**Comment by yjbanov** [comment]
Update: my latest hypothesis is that the flakiness is due to the test relying on real `Stopwatch` implementation here: https://github.com/flutter/flutter/blob/9391a88b189be43c9f1721b435f2089dd1cb6b64/packages/flutter/lib/src/gestures/velocity_tracker.dart#L153. Testing it now.

**Comment by yjbanov** [comment]
Confirmed! When the test fails the `Stopwatch` reports elapsed time greater than 40ms, resulting in the drag gesture to not be considered a fling, e.g.:

```
_sinceLastSample.elapsedMilliseconds = 41
VerticalDragGestureRecognizer#25cef(start behavior: start) calling onEnd callback. VelocityEstimate(0.0, 0.0; offset: Offset(0.0, 0.0), duration: 0:00:00.000000, confidence: 1.0); judged to not be a fling.
```

**Comment by yjbanov** [comment]
This was the PR that introduced it: https://github.com/flutter/flutter/pull/132291

**Comment by chipweinberger** [comment]
@yjbanov , do you have any suggestions on how we can fix those tests? I'm the author of the PR.

Why do they take so long to run? Do we need to add some test method to reset the time elapsed to zero?

**Comment by yjbanov** [comment]
> @yjbanov , do you have any suggestions on how we can fix those tests? or the PR? I'm the author of the PR.

@Piinks is exploring a couple of options, both of which rely on some way for the `VelocityTracker` to use a fake source of time. For example, we have `SamplingClock` that does something similar and might be reusable here. Or we can use `Clock` directly, which was designed to be testable. My intuition tells me that for best results the source of clock/stopwatch time should be in sync with `FakeAsync` that's used by the test framework. This way if you pumped 3 seconds into the future, then all our clocks tick forward by the exact same amount of time. Otherwise, if one block moves 3 seconds, and another one moves 1 second, then the test would be testing some unrealistic scenario.

> Do we need to add some test method to reset the time elapsed to zero?

The velocity tracker is stateful, so I think resetting the elapsed time is not the right thing to do. It's not something that would happen in a real situation. Instead, we should teach our tests to emulate passage of time consistent with real time.

> why does the test fling gesture take so long?

In most cases it doesn't, but anything can cause it to run longer than normal, such as a random garbage collection cycle. We want our test harness and test code to be resilient to randomness inherent to measuring real time. We're essentially benchmarking the test, which is always noisy in practice, while in tests we want deterministic results.

**Comment by Piinks** [comment]
Hey @chipweinberger! I am working on tweaking the change so we can get it back in. Thanks for following up! I will cc you on the re-land once I can confirm it won't flake out.

**Comment by chipweinberger** [comment]
@yjbanov a fake source of time sounds ideal.  

@Piinks thanks for taking the charge on it!

**Comment by yjbanov** [comment]
Another data point for future reference: this was not limited to web (although the flaky rate was much higher on the web). Here's a sample flake from non-web tests:

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8767481603356697345/+/u/run_test.dart_for_framework_tests_shard_and_subshard_widgets/test_stdout
