### ISSUE TITLE
Refactor unnecessarily complex assert in AsyncSnapshot constructor

### ISSUE THREAD

**Issue by RandalSchwartz** [flutter/flutter#135731]
https://github.com/flutter/flutter/blob/ead455963c12b453cdb2358cad34969c76daf180/packages/flutter/lib/src/widgets/async.dart#L203

The expression `assert(!(data != null && error != null))` can be simplified to `assert(data == null || error == null)`

It took me about five readings of that to figure out what it meant.  deMorgan to the rescue!

**Comment by Topbrains** [comment]
Mr. Schartz, noticing that fact required having taken a class in Logic, which as far as I know is not a requirement in Computer Science. I took Logic in Engineering but it was optional. Today kids see the elements of it in grade school though Geometry, but just the basics. We teach them set theory and that would be another chance, but again just do unions and intersections. Pity!

**Comment by RandalSchwartz** [comment]
May I also add the suggestion that this be given the "good first commit" label, since the one-line change is almost entirely in the initial message here?
