### ISSUE TITLE
Incorrect URL's For Documentation When Using dart doc

### ISSUE THREAD

**Issue by Andrious** [flutter/flutter#135833]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Once my package is published to pub.dev, the resulting API reference documentation has an inaccuracy after advancing one-level deep into the documentation.

1. Starting from the 'top level' of the state_extended package documentation:
    https://pub.dev/documentation/state_extended/latest/state_extended/state_extended-library.html

2. Selecting from the right-hand side of the screen, a link under the Class or Mixin category:
    As an example, select the StateX class. 
    https://pub.dev/documentation/state_extended/latest/state_extended/StateX-class.html

3. Again, from the right-hand side of the screen, select any link under categories, constructor, properties, methods or operators.
   As an example, select the link, controller.
   https://pub.dev/documentation/state_extended/latest/state_extended/StateX/controller.html

4. Once on that particular page regarding the topic selected, looking now at any link listed on the left-hand side, select a link under categories, constructor, properties, methods or operators.
    As an example, select the 'controller' link again.
    Doing so will present an inaccurate link displaying 'not found':
    https://pub.dev/documentation/state_extended/latest/state_extended/state_extended/StateX/controller.html

### Expected results

The appropriate URL should be displayed:

https://pub.dev/documentation/state_extended/latest/state_extended/StateX/controller.html

### Actual results

The URL instead is incorrect with the 'name of the package' repeated twice (see below):

https://pub.dev/documentation/state_extended/latest/state_extended/state_extended/StateX/controller.html

### Code sample

[state_extended](https://pub.dev/documentation/state_extended/latest/state_extended/state_extended-library.html)

### Screenshots or Video

n/a

### Logs

n/a

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Programs\Tools\Android\SDK
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = C:\Programs\Tools\Android\SDK
    • ANDROID_SDK_ROOT = C:\Programs\Tools\Android\SDK
    • Java binary at: C:\Programs\Tools\Android\Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2022 17.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
    • Visual Studio Build Tools 2022 version 17.6.33829.357
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Programs\Tools\Android\Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.2361]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 117.0.5938.132
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 117.0.2045.47

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment]
Issues with `pub.dev` need to be reported to [the `pub.dev` project](https://github.com/dart-lang/pub-dev/issues); this issue tracker is for issues in Flutter itself.
