### ISSUE TITLE
Remove Kotlin deps as well as anything else redundant dependencies to make Flutter less platform and versions dependant

### ISSUE THREAD

**Issue by engilyin** [flutter/flutter#135834]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Flutter requires lots of Kotlin stuff for Android app which looks redundant and make it harder to maintain the app, longer to build, more bloated app etc.

### Proposal

There is no reason for Flutter to relay on extra layer for Android platform. Flutter itself is the native solution re-implements everything by its own.
So what is the rationale to have dependency on Kotlin for Android? Just add extra complexity and bloat into the output?

Please remove everything you can keeping just bare minimum to startup native Flutter app on Android. 
Any platform specific stuff must be minimized.

Especially any reference or usage of Kotlin should be eliminated. Android originally is based on Java so it should be sufficient.

**Comment by stuartmorgan** [comment]
It is not clear what "Kotlin stuff" you are referring to, or what you believe is extra code that doesn't need to exist, which means this is not actionable; closing accordingly. If you have specific technical suggestions, please file a new issue with details.

> Just add extra complexity and bloat into the output?

Please take a moment to read our code of conduct before engaging in the future. Suggesting that we are deliberately doing things for the express purpose of making Flutter worse is not constructive.

> Especially any reference or usage of Kotlin should be eliminated. Android originally is based on Java so it should be sufficient.

If you are referring to the runner, you are welcome to pass `-a java` when you create your application too generate a Java runner.
