### ISSUE TITLE
[Impeller] Linux_android platform_views_scroll_perf_impeller__timeline_summary hitting GL error.

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#135881]
Starting in https://github.com/flutter/engine/pull/46434 with an attempt at a fix in https://github.com/flutter/engine/pull/46443

Example in https://ci.chromium.org/ui/p/flutter/builders/staging/Linux_android%20platform_views_scroll_perf_impeller__timeline_summary/1811/overview

```
[2023-10-02 16:26:07.435243] [STDOUT] stdout: [  +59 ms] F/flutter (21544): [FATAL:flutter/impeller/renderer/backend/gles/proc_table_gles.h(36)] Fatal GL Error GL_INVALID_ENUM(1280) encountered on call to glTexParameteri
```

cc @jonahwilliams @matanlurey

**Comment by jonahwilliams** [comment]
Can we dedupe into https://github.com/flutter/flutter/issues/135524 ? Looks like the same error.

**Comment by zanderso** [comment]
Don't know if it makes a difference, but this one is error code `GL_INVALID_ENUM(1280)`, and https://github.com/flutter/flutter/issues/135524 is `GL_INVALID_OPERATION(1282)`.

**Comment by jonahwilliams** [comment]
Yeah, might be different or related. Will need investigation

**Comment by jonahwilliams** [comment]
This isn't causing any errors on my Pixel 6 pro.  I'm assuming this is runing on one of the samsung devices, I'll pick one up from the office next week and try there.

**Comment by zanderso** [comment]
`Linux_android` is Moto G4

**Comment by jonahwilliams** [comment]
Ahh

**Comment by jonahwilliams** [comment]
https://registry.khronos.org/OpenGL/extensions/OES/OES_EGL_image_external.txt

From the horses mouth:

>   "When <target> is TEXTURE_EXTERNAL_OES only NEAREST and LINEAR are
        accepted as TEXTURE_MIN_FILTER and only CLAMP_TO_EDGE is accepted as
        TEXTURE_WRAP_S and TEXTURE_WRAP_T.  Attempting to set other values for
        TEXTURE_MIN_FILTER, TEXTURE_WRAP_S, or TEXTURE_WRAP_T will result in
        an INVALID_ENUM error.

We're setting illegal values for the texture parameters for the platform view texture.

**Comment by jonahwilliams** [comment]
So there are a number of problems here:

1. When adding a texture with a non-trivial transform, we actually use a tiled texture: https://github.com/flutter/engine/blob/main/shell/platform/android/surface_texture_external_texture.cc#L67-L76
2a. The tiled texture contents does not use the OES shader.
2b. The OES textures only support kClamp (CLAMP_TO_EDGE) without extensions, but we use Repeat.
3. Impeller does not detect any of these cases and simply fails to render.

So there are a number of potential fixes here. I'm not sure how much that code is shared between Skia and Impeller, but if we could turn both versions into a drawImage call then everything should just work.

Barring that, Impeller needs to detect when an OES texture + sampler is in a state where it cannot be rendered correctly and perform a second render to texture to convert to a regular texture.

Though maybe this wasn't supposed to work for Impeller yet!

FYI @johnmccutchan

**Comment by jonahwilliams** [comment]
Even when I adjust these things, the platform views don't show up correctly. Also interestingly if I switch to using the right OES shader the invalid parameter warning for repeat tile mode goes away, so maybe that is not actually the issue.

```
diff --git a/impeller/entity/contents/tiled_texture_contents.cc b/impeller/entity/contents/tiled_texture_contents.cc
index 0b54d4ba01..1d6ed2fa53 100644
--- a/impeller/entity/contents/tiled_texture_contents.cc
+++ b/impeller/entity/contents/tiled_texture_contents.cc
@@ -119,6 +119,7 @@ bool TiledTextureContents::Render(const ContentContext& renderer,
 
   using VS = TextureFillVertexShader;
   using FS = TiledTextureFillFragmentShader;
+  using FSExternal = TextureFillExternalFragmentShader;
 
   const auto texture_size = texture_->GetSize();
   if (texture_size.IsEmpty()) {
@@ -153,9 +154,23 @@ bool TiledTextureContents::Render(const ContentContext& renderer,
     options.stencil_operation = StencilOperation::kIncrementClamp;
   }
   options.primitive_type = geometry_result.type;
+
+#ifdef IMPELLER_ENABLE_OPENGLES
+  bool is_external_texture =
+      texture_->GetTextureDescriptor().type == TextureType::kTextureExternalOES;
+
+  if (is_external_texture) {
+    cmd.pipeline = renderer.GetTextureExternalPipeline(options);
+  } else {
+    cmd.pipeline = uses_emulated_tile_mode
+                       ? renderer.GetTiledTexturePipeline(options)
+                       : renderer.GetTexturePipeline(options);
+  }
+#else
   cmd.pipeline = uses_emulated_tile_mode
                      ? renderer.GetTiledTexturePipeline(options)
                      : renderer.GetTexturePipeline(options);
+#endif  // IMPELLER_ENABLE_OPENGLES
 
   cmd.BindVertices(geometry_result.vertex_buffer);
   VS::BindFrameInfo(cmd, host_buffer.EmplaceUniform(frame_info));
@@ -177,10 +192,17 @@ bool TiledTextureContents::Render(const ContentContext& renderer,
         renderer.GetContext()->GetSamplerLibrary()->GetSampler(
             CreateDescriptor(renderer.GetDeviceCapabilities())));
   } else {
-    FS::BindTextureSampler(
-        cmd, texture_,
-        renderer.GetContext()->GetSamplerLibrary()->GetSampler(
-            CreateDescriptor(renderer.GetDeviceCapabilities())));
+    if (is_external_texture) {
+      FSExternal::BindSAMPLEREXTERNALOESTextureSampler(
+          cmd, texture_,
+          renderer.GetContext()->GetSamplerLibrary()->GetSampler(
+              sampler_descriptor_));
+    } else {
+      FS::BindTextureSampler(
+          cmd, texture_,
+          renderer.GetContext()->GetSamplerLibrary()->GetSampler(
+              CreateDescriptor(renderer.GetDeviceCapabilities())));
+      }
   }
 
   if (!pass.AddCommand(std::move(cmd))) {
diff --git a/shell/platform/android/surface_texture_external_texture.cc b/shell/platform/android/surface_texture_external_texture.cc
index de83114e32..f69f58e551 100644
--- a/shell/platform/android/surface_texture_external_texture.cc
+++ b/shell/platform/android/surface_texture_external_texture.cc
@@ -65,8 +65,8 @@ void SurfaceTextureExternalTexture::Paint(PaintContext& context,
     context.canvas->Scale(bounds.width(), -bounds.height());
 
     if (!transform_.isIdentity()) {
-      DlImageColorSource source(dl_image_, DlTileMode::kRepeat,
-                                DlTileMode::kRepeat, sampling, &transform_);
+      DlImageColorSource source(dl_image_, DlTileMode::kClamp,
+                                DlTileMode::kClamp, sampling, &transform_);
 
       DlPaint paintWithShader;
       if (context.paint) {
```

**Comment by johnmccutchan** [comment]
> So there are a number of problems here:
> 
> 1. When adding a texture with a non-trivial transform, we actually use a tiled texture: https://github.com/flutter/engine/blob/main/shell/platform/android/surface_texture_external_texture.cc#L67-L76

Just a note that the common case is a non-identity transform.

**Comment by bdero** [comment]
https://github.com/flutter/engine/pull/47586 rolled in via https://github.com/flutter/flutter/pull/138599 and the build is fixed now!
