### ISSUE TITLE
[go_router] An easy way to get the current route and the current route index

### ISSUE THREAD

**Issue by JGeek00** [flutter/flutter#135854]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Given this example: 
```
GoRouter(
  initialLocation: '/',
  routes: [
    GoRoute(
      path: '/route1',
      ...
    ),
    GoRoute(
      path: '/route2',
      ...
    ),
    GoRoute(
      path: '/route3',
      ...
    ),
  ]
)
```

I would like to be able to get the current route (ex: /route2) and the current index (1).

I found [this](https://docs.page/csells/go_router/navigation) on the documentation but it's outdated. 

### Proposal

Something like this should return the current path:
```GoRouter.of(context).currentPath```

Something like this should return the current index on the routes list:
```GoRouter.of(context).currentRoutesIndex```

**Comment by opxdelwin** [comment]
Hi @JGeek00,
You can get current path using `uri` from `GoRouter.of(context).routeInformationProvider.value.uri`

**Comment by huycozy** [comment]
@JGeek00 
You can get the current path/location with the following code:

```dart
  final RouteMatch lastMatch = _router.routerDelegate.currentConfiguration.last;
  final RouteMatchList matchList = lastMatch is ImperativeRouteMatch ? lastMatch.matches : _router.routerDelegate.currentConfiguration;
  final String location = matchList.uri.toString();
  print('location: $location');
```

You can follow https://github.com/flutter/flutter/issues/129833 for further updates.

For the route index, you can try:

```dart
  final int index = matchList.matches.indexWhere((RouteMatch match) => match.matchedLocation == location);
  print('index: $index');
```

Let me know if this works for you.

**Comment by huycozy** [comment]
Great! Closing the issue as solved.
