### ISSUE TITLE
how to pass a parameter to be added to strings localized like "Here is the number:$number"

### ISSUE THREAD

**Issue by EgHubs** [flutter/flutter#135875]
### Is there an existing issue for this?

- [X] I have searched the [existing package issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Apackage)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### What package does this bug report belong to?

animations

### What target platforms are you seeing this bug on?

Android, iOS

### Have you already upgraded your packages?

Yes

### Steps to reproduce

I use these two classes for localization in flutter
following this [article](https://medium.com/flutter-community/multi-language-support-in-flutter-a12de708f833) setup.
```
import 'package:flutter/cupertino.dart';

abstract class Languages {
  final String? extra;

  Languages({this.extra});
  static Languages? of(BuildContext context, {String? extra}) {
    return Localizations.of<Languages>(context, Languages);
  }
String get text199;
}

```

and this LanguageEn:

```
import 'languages.dart';

class LanguageEn extends Languages
{
  LanguageEn({String? extra}) : super(extra: extra);
  @override
String get text199 => "Update data($extra)";
}
```

when I pass this extra parameter I get null `"Update data(null)"` in whatever language I'm in

` Languages.of(context,extra: "$activeID")!.text199),
`

but when I directly select a language class and do this it works and I get the number and not null `"Update data(4)"`

` LanguageEn(extra: "$activeID").text199),
`                                                    

how to pass dynamic strings with this package?

### Expected results

the extra parameter should not be null

### Actual results

it's null if I called the Languages class and not null in the LanguagesEn class

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.6, on macOS 13.5.2 22G91 darwin-arm64, locale en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.82.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by Ignacio1110** [comment]
you didn't use the extra in your language class. 
this article is 3 years ago, you have other better choices to do localization. 
```
//this method received String? but did use it anywhere.
static Languages? of(BuildContext context, {String? extra}) {
    return Localizations.of<Languages>(context, Languages);
  }
```

**Comment by darshankawar** [comment]
@EgHubs 
Check above solution and see if it helps in your case or not. Also, take a look at official localization [documentation](https://docs.flutter.dev/ui/accessibility-and-localization/internationalization?gclid=CjwKCAjw9-6oBhBaEiwAHv1QvE6G04FxLvgSogOBJwkiW2vG097p1nw1o5-gQA7rLrkck06zPhvGDxoC19AQAvD_BwE&gclsrc=aw.ds) for further reference.

I'll close it for now, as above link and solution should help to resolve the issue. If not, write in comments and I'll reopen it.
