### ISSUE TITLE
[go_router] Responsive navigation stack

### ISSUE THREAD

**Issue by JGeek00** [flutter/flutter#135853]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I'm creating a responsive design that works for all platforms that Flutter supports, but I'm finding some problems doing it.

I want to create two separate navigators, one for desktop and another one for mobile.
On the desktop navigator I want to have a left sidebar (a fixed drawer) and the route content at the right of the sidebar, using a nested navigation system. 
On the mobile navigator I want to use a bottom navigation bar with the traditional navigation system, where the new screens that you push are set on top of the previous ones, including on top of the bottom navigation bar (no nested navigation). 

I tried to achieve that by creating two different navigators, and switching from one to the other based on the screen width, but when I switch to the other navigation the app "resets" and gets back to the initial route. I'm using the same global key for both navigators.

### Proposal

Allow to have two different navigators and switch between them based on the screen width (or any other parameter), but when the change happens, the current route should not change. Just repaint the UI but not change the current route.

**Comment by huycozy** [comment]
Hi @JGeek00 
You can handle this by using [flutter_adaptive_scaffold](https://pub.dev/packages/flutter_adaptive_scaffold) (navigational elements would be a BottomNavigationBar on a small mobile device and a NavigationRail on larger devices). 

I see there are open issues similar to the case you described https://github.com/flutter/flutter/issues/129850, https://github.com/flutter/flutter/issues/99100.

Closing this issue in favor of those issues, so please follow up on them for further updates.
