### ISSUE TITLE
flutter/engine has branches fuschia_R53 and fuschia_r53

### ISSUE THREAD

**Issue by RandalSchwartz** [flutter/flutter#135820]
### Is there an existing issue for this?

- [X] I have searched the [existing infra issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-infra)

### Type of Request

infra task

### Infrastructure Environment

github

### What is happening?

GIthub source for flutter/engine has *both* branches:

- fuschia_R53
- fuschia_r53

which on case-insensitive filesystems collide.  So every fetch from github causes this to flip back and forth.

### Steps to reproduce

1. Clone the repo on a mac
2. `git fetch` and watch the names flip back and forth.
3. repeat until you get it :)

### Expected results

I expect one of the two branches gets deleted by using a case-sensitive filesystem somewhere, like on linux, and then I'll never see these two branches show up on a fetch again. :)

**Comment by chinmaygarde** [comment]
It's gone now!
