### ISSUE TITLE
rendering artifacts/stuttering, 100x slower scrolling and animations in the Flutter Gallery app

### ISSUE THREAD

**Issue by wis** [flutter/flutter#13589]
## Steps to Reproduce
I installed the Flutter Gallery from the Play Store to test the frameworks performance on my phone and compare it to Xamarin, React Native, and NativeScript (all of them have bindings to the OS's UI framework/APIs, unlike Flutter).
I read that Skia, which everything is based on for drawing, is hardware accelerated. what explains that then?

Video: https://photos.google.com/share/AF1QipPREobPVjlgh_uoef95FjLEoqhNE4FTyBBP-5kq4oGHaJ1Gqj1Z2UMacmqUdOGcrw?key=Vjlqamo1OENwS3VWeWtkM2pMV1E3MXlPRlZPOTJ3
Can't upload videos to GitHub.

Screenshots:

Image 1             |  Image 2 | Image 3  | Image 4
:-------------------------:|:-------------------------:|:-------------------------:|:-------------------------:
<img src="https://user-images.githubusercontent.com/9993663/34021075-6f02c5cc-e140-11e7-91a1-80f711044fa7.png" width ="300"> | <img src="https://user-images.githubusercontent.com/9993663/34021074-6ee13286-e140-11e7-8153-c5183b7544f2.png" width ="300"> | <img src="https://user-images.githubusercontent.com/9993663/34021076-6f2748f2-e140-11e7-98b4-727eff527d50.png" width ="300"> | <img src="https://user-images.githubusercontent.com/9993663/34021078-6f48086c-e140-11e7-9981-109c1ad6d6b0.png" width ="300">

**Comment by wesamco** [comment]
tearing not stuttering I should've wrote. two different things.

**Comment by Hixie** [comment]
cc @chinmaygarde

**Comment by Hixie** [comment]
cc @cbracken

**Comment by Hixie** [comment]
Can you describe what device you are using?

**Comment by Hixie** [comment]
Also, can you include the output of `flutter doctor`? Thanks.

**Comment by wesamco** [comment]
it's the Galaxy s4 international with Exynos 5410, with a stock Android 7.1.2 ROM.
https://github.com/exynos5410
https://forum.xda-developers.com/galaxy-s4/i9500-orig-develop/rom-lineageos-14-1-samsung-galaxy-s4-t3586561
I'm not familiar flutter doctor, I haven't installed anything or do flutter development , is it a terminal CLI and can I use it with the Flutter gallery app installed from the play store?
chrome which also which IIRC, renders with Skia works just fine.

**Comment by wesamco** [comment]
Oh even Android it self renders with Skia, what was even talking about with that point about chrome.
I just installed and tested the Hamilton app, startup time was slower than the apps I tested that were built with JS (interpreting) native mobile frameworks (I know this can be application specific more than framework), unlike the gallery app, there's no rendering tearing, but it's unpredictably dropping frames, I can't find a pattern. even toggling a checkbox is dropping most frames of the animation.
vertical scrolling in the menu seems not to drop any frames, in the app scrolling horizontal scrolling in tabs and material design repelling animation in buttons does drop most frames.

**Comment by Hixie** [comment]
We really need to get a Galaxy S4, we keep hearing issues with it...

**Comment by chinmaygarde** [comment]
I haven't seen this type of failure before. Will attempt to get a hold of a Galaxy S4 and also bring this up with the Skia folks during our sync.

**Comment by wesamco** [comment]
@chinmaygarde note that there are two variants of the S4 for different markets, 
seems to me Exynos variant (9500) for Europe and the rest of the world markets and Qualcomm variant (9505) exclusive to the US market.

> Galaxy S4 models use one of two processors, depending on the region and network compatibility. The S4 version for North America, most of Europe, parts of Asia, and other countries contains Qualcomm'sSnapdragon 600 system-on-chip, containing a quad-core 1.9 GHz Krait 300 CPU and an Adreno 320 GPU. The chip also contains a modem which supports LTE.[24][25] Other models include Samsung's Exynos 5 Octa system-on-chip with a heterogeneous CPU. The octa-core CPU comprises a 1.6 GHz quad-core Cortex-A15 cluster and a 1.2 GHz quad-core Cortex-A7 cluster.[12][26] The chip can dynamically switch between the two clusters of cores based on CPU usage; the chip switches to the A15 cores when more processing power is needed, and stays on the A7 cores to conserve energy on lighter loads. Only one of the clusters is used at any particular moment, and software sees the processor as a single quad-core CPU.[24][26][27] The SoC also contains an IT tri-core PowerVR SGX 544 graphics processing unit (GPU). Regional models of the S4 vary in support for LTE; for Exynos 5-based models, while the E300K/L/S versions support LTE, with the Cortex-A15 also clocked at 1.6 GHz.[28][29][30] the GT-I9500 model does not.[31] The S4 GT-I9505 includes a multiband LTE transceiver.[8]

source: [Samsung Galaxy S4 - Wikipedia](https://en.wikipedia.org/wiki/Samsung_Galaxy_S4)

**Comment by chinmaygarde** [comment]
Update: @jason-simmons was able to get a hold of an S4 from the device lab. Unfortunately, I could not observe the reported issue and the performance seemed fine. However, I was running the last update provided by the OEM (in 2015!!!) and not the ROM listed by @wesamco. Also, `/proc/cpuinfo` indicates that the variant I have is the Qualcomm one.

The next steps are to get a hold of the Exynos variant and/or flash the updated ROM.

I also have a feeling this is related to the render to texture pass that was previously present for color correctness. We recently got rid of that pass. But, I would like for us to get a reproducible test case so we can verify/test the fix.

![flutter_04](https://user-images.githubusercontent.com/44085/34134962-a206b918-e412-11e7-8d6d-e902dcc5431a.png)
![flutter_03](https://user-images.githubusercontent.com/44085/34134963-a222423c-e412-11e7-8d0b-dc4b8217a1aa.png)
![flutter_02](https://user-images.githubusercontent.com/44085/34134964-a2388d80-e412-11e7-91db-915a9f88b31e.png)

**Comment by wis** [comment]
sorry, so this is not a one/few of a kind issue that's only related to specific devices, models and ROMs? then why does it have low priority?
my reasoning was, since Flutters mostly depends on and statically ahead of time compiles in the graphics libraries down the stack, it should have _less_, not _more_ of these types of bug.
It might be true but not while Flutter is alpha or beta.

**Comment by Hixie** [comment]
@wis Unfortunately we are very sensitive to the device drivers, because by including our own graphics stack we bypass the system's own workarounds for such issues.

**Comment by Hixie** [comment]
@wis do you still see this with the latest versions of Flutter applications?

**Comment by wis** [comment]
@Hixie yes, also now I noticed that scrolling down is very slow/choppy, but scrolling up is not.  
it looks like [all of the terrible 1 star reviews](https://play.google.com/store/apps/details?id=io.flutter.demo.gallery&hl=en&showAllReviews=true) are from other people who have the same issue them mention "frame drop" and "stutter", seems only half of them are S4 owners.

**Comment by wis** [comment]
on a relevant note, thank you for working on HTML5, it's the best thing that happened to the web,  
I love how customizable the web is on Desktop with browser extensions, how I get to and got used to watching every video on any website in 2.5+ playback speed (property on HTMLMediaElement that extensions can get/set), use custom shortcuts as controls,  
and how I now only use [vimium](https://github.com/philc/vimium) to browse. 

in a recent interview, Eric mentions that his background is web graphics and performance, 
he says in his answer [how Flutter started](https://youtu.be/h7HOt3Jb1Ts?t=1m15s), that his team at the time, the Chrome team, did some experiments that broke the web but made it 20 time faster.

- was it the internet (e.g hacker news, blog posts with titles/articles with headlines like "Google's new/fork web") that kept you to stay away from exploring this idea further? 
- considering the inception of Web Assembly and Fuchsia (which depends on Flutter), the popularity and adoption of PWAs, is it time to reconsider and explore this idea? 
  - from a 1000ft view, who other than you guys (given your backgrounds/what you worked on) and Google (apparently not GitHub, with Electron) can make an influential, independent, democratic and transparent Flutter and Dart foundations that work on, build and distribute a Flutter browser with a dart runtime, in the play store for Android, Windows, and have it native to (arguably) the next most popular OS, that apparently at some point will succeed Android, Fuchsia, 
    - that would enable customization of apps to the extent of Desktop web browsers, and even further with more fine grained capability/permission/access model?
      - all software can be easier-ly and as much modifiable as FLOSS and need not be FLOSS, given a runtime with the right constructs (reactivity being one, and probably exposable persistent/immutable data structures for state with provided right way to access them from multiple threads)
- or is the future better off with one open web, with new standard APIs such as custom elements, shadow DOM and web components*, Web Assembly (even though still there's no direct access to web APIs) and [Houdini](https://developers.google.com/web/updates/2016/05/houdini)?
  - [*](url) BTW these web APIs broke browser extensions by encapsulating DOM elements' events.
  - definitely, browser vendors are shipping new standard APIs much more frequently now, we have Annual releases of ECMAScript (ES2016,2017..).

**Comment by wis** [comment]
bump!
feel free to ignore my rambling in the last comment,
this is still an issue on all Galaxy S4 Exynos devices, check out the reviews on the Play store for the Flutter gallery app .
