### ISSUE TITLE
flutter setup instructions don't copy-n-paste work on mac

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#13582]
From https://flutter.io/setup-macos I copy and pasted `export PATH=`pwd`/flutter/bin:$PATH` but I got an error:

```
sethladd-macbookpro:Code sethladd$ $ export PATH=`pwd`/flutter/bin:$PATH
-bash: $: command not found
```

However, this worked:

```
export PATH=$PWD/flutter/bin:$PATH
```

**Comment by alibitek** [comment]
Why is there an additional $ copied in the clipboard?
Which browser are you using? When I try to copy from the page mentioned the browser doesn't allow the selection of the $ sign
The HTML element in the page is this: `<span class="noselect">$ </span>`
I don't think this is a problem.

**Comment by sethladd** [comment]
ah, good catch! that's it!

I was selecting both lines at the same time, with Chrome. For some reason, chrome is indeed still selecting the `$` on the first line.

Thank you :)

**Comment by alibitek** [comment]
Could be a bug in the version of Chrome for macOS or something else :-)

I've only tried on ArchLinux with latest versions of: Firefox stable, Chrome stable, Chrome unstable, Chromium stable, Chromium snapshot build and I cannot select the $ sign
