### ISSUE TITLE
ColoredBox doesn't have height and width properties

### ISSUE THREAD

**Issue by ayato91** [flutter/flutter#135863]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

## Use Case
In flutter, [ColoredBox](https://api.flutter.dev/flutter/widgets/ColoredBox-class.html) widget is used for paints its area with a specified Color and then draws its child on top of that color. 
``` 
ColoredBox(
  color: Colors.blue,
  child: SizedBox(
     height: 200,
     width: 200,
  ),
)
```
-> *This will create a blue box of 200x200 px.*
## Problem
There is no way to set or customize the size of the [ColoredBox](https://api.flutter.dev/flutter/widgets/ColoredBox-class.html) widget directly.

Without using other widget like [SizedBox](https://api.flutter.dev/flutter/widgets/SizedBox-class.html) as a child of [ColoredBox](https://api.flutter.dev/flutter/widgets/ColoredBox-class.html) widget, it is not possible to create a [ColoredBox](https://api.flutter.dev/flutter/widgets/ColoredBox-class.html) with a specific size. 

## Proposal
It would be more convenient to use [ColoredBox](https://api.flutter.dev/flutter/widgets/ColoredBox-class.html) with manual height and width, similar like [SizedBox](https://api.flutter.dev/flutter/widgets/SizedBox-class.html) widget.

This will help to make [ColoredBox](https://api.flutter.dev/flutter/widgets/ColoredBox-class.html) widget more adaptable for creating a color box with specific height and width.
### After:
```
ColoredBox(
 color: Colors.blue,
 height: 200,
 width: 200,
 child: //child widget 
)
```

**Comment by ayato91** [comment]
Can I contribute to solve this issue?

**Comment by immadisairaj** [comment]
It is already possible with existing widgets (using `Container`). I feel there is no extra need for `ColoredBox` to support this. You can easily use:
```dart
Container(
    color: Colors.blue,
    height: 200,
    width: 200,
    child: child,
),

**Comment by darshankawar** [comment]
@ayato91 
Check above solution and also see https://stackoverflow.com/a/48869889 if it helps to answer / resolve your use case or not.

**Comment by Ebrahim683** [comment]
**1. Wrape your COloredBox with SizedBox.**
        ```
  SizedBox(
          height: 200,
          width: 200,
          child: ColoredBox(
            color: Colors.red,
            child: YourChild(),
          ),
        ),
```
        
        
**2. You can use Container instead of ColoredBox.**
         ```
 Container(
          height: 200,
          width: 200,
          color: Colors.red,
          child: YourChild(),
        ),
```

**Comment by ayato91** [comment]
As we have `Sizedbox` as a shortcut replacement of `Container`, similarly I thought something like  `ColoredBox with dimension properties` or `SizedBox.color` widget.
