### ISSUE TITLE
plugin cloud_firestore CollectionReference.add function missing

### ISSUE THREAD

**Issue by tobytraylor** [flutter/flutter#13596]
cloud_firestore CollectionReference is missing "add" function shown in firestore documentation here: https://firebase.google.com/docs/firestore/manage-data/add-data.  This method would allow auto generation of the key/id by the store.

**Comment by Skylled** [comment]
This does seem like a good method to have, for consistency with native APIs.

The current way to get the behavior you're looking for:
```
CollectionReference collection = Firestore.instance.collection('foo');
// If you do not provide a document path, the API locally generates a unique ID to use.
DocumentReference newDoc = collection.document();
newDoc.setData({"your data": "here"});
```

**Comment by Arno-Z** [comment]
setData returns a null sadly. Would be nice to have a callback with a hande with the newly created document. 

Right now i am working around it by using the PushIdGenerator to create a PushID so i know the key to the newly created document (i have not found any callbacks to work).

**Comment by Skylled** [comment]
Right, but `CollectionReference.document()` returns the auto-generated ID. The same one you'd get from `PushIdGenerator`.

**Comment by Arno-Z** [comment]
I would love to see a working sample of that ;)

**Comment by Skylled** [comment]
One additional problem I could see is that DocumentReference doesn't have a `documentID` method like DocumentSnapshot does. That should probably also be remedied.

**Comment by Skylled** [comment]
This can be closed.

**Comment by Hixie** [comment]
Great!

**Comment by kroikie** [comment]
@tobytraylor

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/926. Any further collaboration will be done there.
