### ISSUE TITLE
Flutter packages integrations.shard test error

### ISSUE THREAD

**Issue by rzambroni** [flutter/flutter#135985]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Install Flutter version 3.16.0-2.0.pre.22

Clone the Flutter packages repository: git clone https://github.com/flutter/flutter

Navigate to the packages/flutter_tools directory: cd packages/flutter_tools

Run the command flutter pub get

Run the command: flutter test test/integrations.shard >> integrations.shard_logs.txt

### Expected results

Running all tests should succeed.

### Actual results

Exception:
 FAILURE: Build failed with an exception.

        * What went wrong:
        Execution failed for task ':gradle:compileGroovy'.
        > BUG! exception in phase 'semantic analysis' in source unit '/Users/hairon/Documents/flutter/packages/flutter_tools/gradle/src/main/groovy/app_plugin_loader.groovy' Unsupported class file major version 64
        
        * Try:
        > Run with --stacktrace option to get the stack trace.
        > Run with --info or --debug option to get more log output.
        > Run with --scan to get full insights.
        
        * Get more help at <https://help.gradle.org>
        
        BUILD FAILED in **11s**

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>
[integration.shard_logs.txt](https://github.com/flutter/flutter/files/12804724/integration.shard_logs.txt)
</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Flutter Doctor Output:

[✓] Flutter (Channel stable, 3.16.0-2.0.pre.22, on macOS 13.5.2 22G91 darwin-arm64, locale en-UY)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Community Edition (version 2023.2.2)
[✓] VS Code (version 1.82.3)
```

</details>

**Comment by christopherfujino** [comment]
Same comment here: https://github.com/flutter/flutter/issues/135989#issuecomment-1756269252

Closing this as I believe you were only intending to test the flutter/packages repository, feel free to re-open if I am mistaken.

**Comment by rzambroni** [comment]
Hi @christopherfujino, thanks for the comment, you are right, the cloned URL is wrong (my bad). 
However, the intention was indeed to test the **integrations.shard** and the issue is still reproducible by cloning the framework repo. 

I fixed the URL on the steps to reproduce section. 

Same case for: https://github.com/flutter/flutter/issues/135989#issuecomment-1756269252
But for that particular issue, we re-tested, and is not reproducible on the latest master version. So we can leave that issue closed.
