### ISSUE TITLE
Allow PlatformChannel communication without an activity (and thus FlutterView)

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#13597]
> This might be related/relevant to background execution of Dart code tracked at https://github.com/flutter/flutter/issues/3671

While trying to enhance a plugin for a Google-internal notification platform, we ran into a problem. On Android, the implementation requires initializing state during `Application.onCreate`. This initialization asks for a lot of information including assets, version, project id and flavor of the app.

For native Android apps, these are injected into the application context so they are available immediately. For Flutter apps, these are typically available only in Dart code which means they are inaccessible without a `FlutterView`. For now, we had to duplicate this information on Android side which is less than ideal.

Ideally, we would like to be able to ask the Dart application during `Application.onCreate` to supply this information. Going one step further, it would be nice if plugin framework allowed registration during application initialization instead of activity.

**Comment by mravn-google** [comment]
@mehmetf Would this require a synchronous response from the Dart application during the invocation of `Application.onCreate`?

I wonder if it makes sense to split this issue into two, one about avoiding duplication of information needed during `Application.onCreate`, and one about registering plugins at the application level?

/cc @zanderso

**Comment by mehmetf** [comment]
> Would this require a synchronous response from the Dart application during the invocation of Application.onCreate?

Likely, yes. Anything done in the app initialization should be very lightweight; e.g. no network access. I am imagining just returning a static map of configuration values from the dart app.

> I wonder if it makes sense to split this issue into two, one about avoiding duplication of information needed during Application.onCreate, and one about registering plugins at the application level?

Good point. "Avoiding duplication of information needed during Application.onCreate" by itself does not carry much weight. We are already forced to do some level of native configuration (e.g. we want to return a different icon asset based on dogfood, fishfood vs prod versions of the app). So _technically_, we can turn this flow around. Instead of having the dart app carry this information, have it available in the native shell and have the dart app fetch it using `MethodChannel`.

The problem is that when the plugin comes into picture, this becomes harder to swallow. Plugins are supposed to be application-agnostic. You are supposed to control them from Dart code. That's the reason why we try hard to make the native integration as seamless as possible. Once a native library needs information at Application.onCreate stage though, this nice plugin model falls apart. Now we are forced to write extensive documentation on how the apps are supposed to modify their native Android shell to be compliant with this particular plugin.

I opened this issue as a point of discussion to see what we can do about this. I can think of other solutions but none of them is as clean as being able to access the dart application during application lifecycle. However, if the effort is quite large to make this happen and will require a redesign/rethink of the entire plugin system, I would say it is not worth doing since I expect a very tiny fraction of plugins to require such special handling.

**Comment by zanderso** [comment]
I'm not sure I'm understanding all the requirements, but it sounds like it would be helpful to be able to run some Dart code earlier in the application lifecycle? I would want to experiment a bit, but on Android, we can probably create the `FlutterNativeView` anytime after `FlutterMain.startInitialization` returns (called from `FlutterApplication.onCreate`). Once we have a `FlutterNativeView` set up, we can call into Dart entrypoints in the root library (i.e. adjacent to main()). Giving those entrypoints access to plugins would require a small amount of additional juggling.

**Comment by mehmetf** [comment]
@zanderso 

Yes. What you laid down is exactly the requirement. I have two concerns:

> we can probably create the FlutterNativeView anytime after FlutterMain.startInitialization returns.

1. How much work is involved here in terms of eng effort and maintenance?

2. `Application.onCreate()` is supposed to be lightweight. I have not looked deep into `FlutterMain.initialization` sequence. Is it bootstrapping the DartVM?  I worry about the extra baggage this is going to introduce to the onCreate step.

If this is going to be a pain in any way (startup speed? maintenance cost?), please let me know and I will implement a workaround for this one plugin.

**Comment by zanderso** [comment]
I'd need to look at (1) a bit more, but as for (2), `FlutterMain.startInitialization` is basically just loading `libflutter.so`. Bringing up the Flutter Engine, Dart VM, and first Isolate are normally delayed until the app's `Activity.onCreate`. Shifting those to `Application.onCreate` would have some non-zero cost.

**Comment by mehmetf** [comment]
Thanks! Is there any way this can be linked with the background execution work? I mean that requires Dart VM and an isolate to be up and running without an Activity right? If so, do we get the fix for this issue for "free" ?

**Comment by zanderso** [comment]
Even in the background execution case, we don't bring up the engine and Dart VM until the background service's `onCreate` method runs. See https://github.com/flutter/plugins/blob/master/packages/android_alarm_manager/android/src/main/java/io/flutter/androidalarmmanager/AlarmService.java#L132.

What you get for free from the background execution work is a decoupling of the lifetime of the Dart Isolate from a drawing surface and rasterizer such that we can opt to bring up a Dart Isolate before we have those things, like during `Application.onCreate`. Whether doing so is too expensive, I'm not sure I can answer.

**Comment by mehmetf** [comment]
Much of this is obsolete now. The poorly named FlutterNativeView can be created and used to call a headless Dart method.
