### ISSUE TITLE
/dart-internal-subscription is throwing 500 errors from missing field in exception

### ISSUE THREAD

**Issue by ricardoamador** [flutter/flutter#135991]
### Is there an existing issue for this?

- [X] I have searched the [existing infra issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-infra)

### Type of Request

bug

### Infrastructure Environment

Cocoon scheduler

### What is happening?

The /dart-internal-subscription throws 500 errors on exceptions with field not found within exception. 'statusCode' is not a field that is part of the datastore exceptions.

### Steps to reproduce

whenever the /dart-internal-subscription is called it will produce this error.

### Expected results

I expect not to see the exception and a 500 returned if there is an internal error.

**Comment by ricardoamador** [comment]
We are currently getting 500 errors and exceptions for this branch: flutter-3.16-candidate.4 with this commit contributing the majority of the errors: c9e7d950d2a4bb689ad36137dd976f480a605513. 

I did some checking and it appears that this is a commit that is not yet merged into the candidate branch.
![image](https://github.com/flutter/flutter/assets/32242716/2d0b87c4-2f35-4584-83ca-d8319ca3ca97)
The image above shows commits that are in the master branch but not yet in the candidate branch.

And here is one of the errors where the dart-internal-subscription is expecting to find this entry in the datastore:
![image](https://github.com/flutter/flutter/assets/32242716/35d342a5-41e8-4d3f-a1fe-b8482d3fdbb0)
But it cannot because the key does not yet exist.

**Comment by ricardoamador** [comment]
The subscription was created here: https://dart-internal-review.git.corp.google.com/c/dart-internal/+/5140

**Comment by ricardoamador** [comment]
Looks like some logic that supported this (to add the commit to the datastore) was removed: 
https://github.com/flutter/cocoon/pull/3005
https://github.com/flutter/cocoon/pull/3099

Reassigning to the release team so they can fix according to their workflow.

**Comment by ricardoamador** [comment]
Some more context from infra's point of view: https://github.com/flutter/cocoon/pull/3124

**Comment by drewroengoogle** [comment]
Opened https://github.com/flutter/cocoon/pull/3168 to resolve. It looks like it got accidentally removed, so I added the portion we need back into the webhook subscription class!

**Comment by drewroengoogle** [comment]
The above PR was merged and future branch cuts should create a commit as intended. Going to close for now but feel free to repopen!
