### ISSUE TITLE
flutter doctor downloading sdk error in China.

### ISSUE THREAD

**Issue by eterrao** [flutter/flutter#13598]
I got Flutter in GDD 2017 in China, I'm glad to use it, but when I input <flutter doctor> in Terminal, it can't download SDK.

## Des
- Env1: Linux(Ubuntu 16.04)
- Info: "curl: (35) gnutls_handshake() failed: Error in the pull function." 

- Env2: Macbook Pro
- info: curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to storage.googleapis.com:443

PS: my Ubuntu VPN was configured, and MBP using VPS from USA Silicon valley.

**Comment by InMatrix** [comment]
Hello, please follow these instructions for using Flutter in China: https://github.com/flutter/flutter/wiki/Using-Flutter-in-China

You don't need to use a VPN following this method. It might be helpful to delete `~/.pub-cache` first. Please let us know if it works for you.

**Comment by linguowu** [comment]
@InMatrix thanks,it work now!

**Comment by InMatrix** [comment]
Glad to hear it!

**Comment by linguowu** [comment]
@InMatrix how long the mirror effective ?

**Comment by eterrao** [comment]
Thank you so much, it works, both Linux and Mac.

**Comment by InMatrix** [comment]
@linguowu We'd like the mirror to be available as long as possible, but it's a community effort so not directly under the control of the Flutter team.
