### ISSUE TITLE
Renderbox Was not laid out Bug

### ISSUE THREAD

**Issue by sharifdujee** [flutter/flutter#135920]
```
Exception caught by rendering library =====================================================
The following assertion was thrown during performLayout():
RenderBox was not laid out: RenderViewport#75734 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1966 pos 12: 'hasSize'
```

// Code Here

**Comment by sharifdujee** [comment]
StreamBuilder<QuerySnapshot>(
                stream: FirebaseFirestore.instance.collection('Car').where("Myear", isEqualTo: 2019).snapshots(),
                builder: (context, snapshot){
                  if(snapshot.connectionState == ConnectionState.active){
                    if(snapshot.hasData && snapshot.data !=null) {
                      return Expanded(child: ListView.builder(
                          itemCount: snapshot.data!.docs.length,
                          itemBuilder: (context, index) {
                            Map<String, dynamic> carData = snapshot.data!
                                .docs[index].data() as Map<String, dynamic>;
                            return Column(
                              children: <Widget>[
                                ListTile(
                                  leading: Text(carData["Myear"]),

                                ),

                              ],

                            );
                          }
                      ),
                      );
                    }
                    else{
                      return  Text("No data Found");
                    }
                  }
                  else{
                    return Text("OutSide The Context");

                  }

                },

              ),

**Comment by moffatman** [comment]
You have ListView -> Column -> ListTile. Column will always expand to fill available height, but ListView lets it have unlimited height. So your options to fix

1. Remove the Column
2. Set mainAxisSize: MainAxisSize.min on the Column

**Comment by yeasin50** [comment]
Can you include a full sample code-snippet that will reproduce the same error? More about [minimal-reproducible-example](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by darshankawar** [comment]
@sharifdujee 
This seems like a code implementation issue rather than a bug in framework. Check https://github.com/flutter/flutter/issues/135920#issuecomment-1745610513 for solution or ask raise such issues in support channels like StackOverflow.

Closing from here.
