### ISSUE TITLE
Unable to display markers on map at first load

### ISSUE THREAD

**Issue by sohitEngg** [flutter/flutter#135981]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I am using GoogleMap with bloc state management & loading markers from API. 
After loading markers I am adding GoogleMap widget to the screen as per below code.

`if(markers.isNotEmpty > 0)
 GoogleMap(
                                  mapType: MapType.terrain,
                                  myLocationEnabled: false,
                                  initialCameraPosition: _kGooglePlex,
                                  markers: markers,
                                )),`

The markers are not displayed at all in first time, it works after that every time when we go back and forth in the screens. 
I read some article and found out a match but there is no luck with this as well. In this we are trying to wait for google map to complete load and then apply setState to refresh the screen. 

`GoogleMap(
                                  mapType: MapType.terrain,
                                  myLocationEnabled: false,
                                  initialCameraPosition: _kGooglePlex,
                                  markers: markers,
                                  onMapCreated:
                                      (GoogleMapController controller) async {
                                    setState(() {
                                      markers.clear();
                                      markers = refreshMarkers;
                                    });
                                  },
                                )),`

I am unable to understand how it starts working after first load, it is reproducible only when we kill and relaunch the app otherwise it works. Is there a solution or work around to make it work in first load as well. Thank you in advance.

### Expected results

Markers should be displayed

### Actual results

Actual result - Only Map is displaying in first time, if I go back to previous screen and come back to this screen it works. Very strange and it is consistent issue. 

### Code sample

<details><summary>My code</summary>

`if(markers.isNotEmpty > 0)
 GoogleMap(
                                  mapType: MapType.terrain,
                                  myLocationEnabled: false,
                                  initialCameraPosition: _kGooglePlex,
                                  markers: markers,
                                )),`

</details>

<details><summary>I also tried map complete and setState()</summary>

`GoogleMap(
                                  mapType: MapType.terrain,
                                  myLocationEnabled: false,
                                  initialCameraPosition: _kGooglePlex,
                                  markers: markers,
                                  onMapCreated:
                                      (GoogleMapController controller) async {
                                    setState(() {
                                      markers.clear();
                                      markers = refreshMarkers;
                                    });
                                  },
                                )),`

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by dam-ease** [comment]
Hi @sohitEngg. Thanks for filing this. Can you try this out https://github.com/flutter/flutter/issues/93398#issuecomment-966031474 to see if it works in your case?

**Comment by sohitEngg** [comment]
No, they have a different problem.
In my case I don't have bitmap to download but only an API and I am already taking care of synchronisation by adding googleMap only after marker data is downloaded.
Image I am not downloading but I have web urls to show on markers.

**Comment by dam-ease** [comment]
Thanks for your response. Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code, just a single `main.dart` file?
Thank you!
