### ISSUE TITLE
Some text in api documentation is hard to read

### ISSUE THREAD

**Issue by mdakin** [flutter/flutter#13599]
Some text in api docs has washed out colors (probably to distinguish that they are inherited etc) but it is quite difficult to read them.

![image](https://user-images.githubusercontent.com/1647551/34034671-b0f9c478-e17f-11e7-88f6-0391f27f4634.png)

**Comment by Hixie** [comment]
cc @jcollins-g 

I'd be fine with making them a little less transparent, FWIW. I agree that the current styles are a touch too aggressively transparent still.

**Comment by zoechi** [comment]
@Hixie Should that be moved over to flutter/website?

**Comment by Hixie** [comment]
@zoechi The API docs aren't handled by the website team, so no. The website repo is just for https://flutter.io/ .

**Comment by kf6gpe** [comment]
This looks obsolete based on the current web site design. Closing.
