### ISSUE TITLE
Default value for TextEditingController

### ISSUE THREAD

**Issue by ameya730** [flutter/flutter#135994]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

At the present moment I use text editing controller a lot to control various elements on my state. I use it in dropdown fields to listen to its state change and add the filters accordingly. I also use the TextEditingController to manage which widgets should be shown especially with respect to the initial value that I input in my controller.

For example, in a filter of elements, my initial value of the controller is 'Select Element'. Then I typically say that when the controller.text == 'Select Element' show something if not show something else. 

### Proposal

If we can assign a "default" to the controller that should help with improving the written code.

For example, while initialising the widget, I say that the TextEditingController(default:'Select Element',text:'Select Element'). Then in my widgets I should be able to say 

if (controller.text.isDefault)...[Do something]else...[Do something else]

In addition, if the reset property can be associated so that if I controller.reset(), it should reset to default, that will help with state management.

**Comment by darshankawar** [comment]
Thanks for the report @ameya730 
I think initial value mostly acts like a default value already, as you can set it and then change it per your needs.

> For example, in a filter of elements, my initial value of the controller is 'Select Element'. Then I typically say that when the controller.text == 'Select Element' show something if not show something else.

Is there any issues with this approach / implementation ? 

Providing a new property named `default` value may conflict with initial value.



> In addition, if the reset property can be associated so that if I controller.reset(), it should reset to default, that will help with state management.

This seems like a different use case for which you may file a new issue with relevant details.
