### ISSUE TITLE
Improve Codesign asset failure log to show specific image causing failure

### ISSUE THREAD

**Issue by LauDijksterhuis** [flutter/flutter#135955]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Hi there,

As mentioned in this issue: https://github.com/flutter/flutter/issues/120046#issue-1571549369 from @elliotnash and a previous experience of mine. Sometimes running Flutter run / build with a "broken" image will result in to a error on iOS. When finding this specific image and "fixing" it (re-adding / new illustrator export etc.) it will work.

### Proposal

What I would like to suggest (if possible) to show in the logs **which** image has failed to codesign. For example, I have added like 40 images to my project, while debugging and it all worked.

But now running it in release it will crash..., so I know I need to find the specific image causing this, but it would be nice if the logs would give me exactly which image is causing the problem.

**Comment by dam-ease** [comment]
Hi @LauDijksterhuis. Thanks for proposing this.
Can you try to run xattr -cr in images directory and see if you get any meaningful logs ?

**Comment by LauDijksterhuis** [comment]
Hi @dam-ease 

Thank you for your quick response,
I'm not sure what this command is supposed to do, but I get this error: 

```
laudijksterhuis@MBP-van-Lau-2 file_extension_2 % xattr -cr                     
Not enough arguments for option -c. Expected at least 1 but got 0

usage: xattr [-l] [-r] [-s] [-v] [-x] file [file ...]
       xattr -p [-l] [-r] [-s] [-v] [-x] attr_name file [file ...]
       xattr -w [-r] [-s] [-x] attr_name attr_value file [file ...]
       xattr -d [-r] [-s] attr_name file [file ...]
       xattr -c [-r] [-s] file [file ...]

The first form lists the names of all xattrs on the given file(s).
The second form (-p) prints the value of the xattr attr_name.
The third form (-w) sets the value of the xattr attr_name to the string attr_value.
The fourth form (-d) deletes the xattr attr_name.
The fifth form (-c) deletes (clears) all xattrs.

options:
  -h: print this help
  -l: print long format (attr_name: attr_value and hex output has offsets and
      ascii representation)
  -r: act recursively
  -s: act on the symbolic link itself rather than what the link points to
  -v: also print filename (automatic with -r and with multiple files)
  -x: attr_value is represented as a hex string for input and output
```

So it indicates I need to run this for a specific file? I tried to run the following loop ([as I found here](https://apple.stackexchange.com/questions/464157/trying-to-read-xattr-values-on-multiple-files)):

```
for ATTR in $(xattr $FILE); do
  xattr -cr $ATTR $FILE
done
```

And I tried to run the command: 
```xattr -cr filename.png```

But all of the above options also don't give me any logs... so I am not sure what I am supposed to do now

**Comment by LauDijksterhuis** [comment]
Hi @hellohuanlin 

I attempted to recreate the error message when running `flutter run --release` however, I got other errors from cocoapods and other stuff. So after updating pods, flutter etc. the app runs fine with all assets.

So I will close this issue for now, if I encounter the same problem in the future I will reopen it.
