### ISSUE TITLE
[Impeller] RawMagnifier doesn't render at particular coordinates

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#136058]
This spawned off from https://github.com/flutter/flutter/issues/126583

cc @gerken-tss

## original comment ([link](https://github.com/flutter/flutter/issues/126583#issuecomment-1622004268))

Soo …

Sorry I got you waiting. I was a little busy and it took me some time to isolate the issue.
But now I have an easy-to-test example!

First the symptoms:

https://github.com/flutter/flutter/assets/84321030/9c68718f-461a-4544-b625-b23180cd87f0

As you can see, the `BackDropFilter` that is being used by [RawMagnifier](https://api.flutter.dev/flutter/widgets/RawMagnifier-class.html) widget here behaves strangely. While the right part of the image is being scaled properly within the magnifier, when I cross a certain threshold with the cursor, it kind of skips an area of the image.

I had a look into the implementation of `RawMagnifier` and saw that [Matrix4](https://api.flutter.dev/flutter/vector_math_64/Matrix4-class.html) is in use there.

Now the code:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final double _size = 160;
  Offset _position = Offset.zero;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        children: [
          GestureDetector(
            onPanUpdate: (DragUpdateDetails details) {
              final RenderBox? box = context.findRenderObject() as RenderBox?;

              setState(() {
                _position = _calculateFocalPointOffset(
                  box,
                  details.globalPosition,
                );
              });
            },
            child: Wrap(
              children: [
                for (int i = 1; i <= 100; i++)
                  Container(
                    width: 32,
                    height: 32,
                    color: i % 2 == 0 ? Colors.red : Colors.green,
                  ),
              ],
            ),
          ),
          Align(
            alignment: Alignment.topRight,
            child: RawMagnifier(
              decoration: MagnifierDecoration(
                shape: CircleBorder(
                  side: BorderSide(
                    color: Theme.of(context).primaryColor,
                    width: 5,
                  ),
                ),
              ),
              size: Size(_size, _size),
              focalPointOffset: _position,
              magnificationScale: 2.0,
            ),
          ),
        ],
      ),
    );
  }

  Offset _calculateFocalPointOffset(RenderBox? box, Offset globalTouchPoint) {
    return Offset(
      globalTouchPoint.dx - (box?.size.width ?? 0) + (_size / 2),
      globalTouchPoint.dy - (_size / 2),
    );
  }
}
```

You can just copy this off into the `main.dart` file of your application and run it. By dragging over the green-red-tiled widget you control the focal point of the magnifier. 
I replaced the image asset by this tiled widget in order for you to have no dependencies of downloading an image before running it.

* If you run this application in the iOS simulator (or real device) with impeller, you get the same behaviour as in the video
* If you run it with the `--no-enable-impeller` flag, everything works fine
* I also realized that replacing the `Alignment` widget with a `Positioned` widget makes it work. But in any case, the behaviour should not differ at all between the impeller app and the skia app.

I also tested re-implementing the `RawMagnifier` widget with my own implementation using a `Matrix4` and I got the same results, so it's nothing related to this particular `Magnifier` widget.

**Comment by gaaclarke** [comment]
I think I've finally got this reproduced in playgrounds.  This was really tricky because it depends on the size of the viewport.  So we can't test it with our current golden image tests setup.

cc @bdero 

## code
```c++
TEST_P(AiksTest, MatrixImageFilterClippedBackdropImageFilter) {
  auto callback = [&](AiksContext& renderer) -> std::optional<Picture> {
    Canvas canvas;
    canvas.Scale(GetContentScale());
    auto image =
        std::make_shared<Image>(CreateTextureForFixture("airplane.jpg"));
    canvas.DrawImageRect(image, {0, 0, 487, 378}, {0, 0, 1024, 768},
                     Paint{.color = Color::White().WithAlpha(0.5)});
    canvas.SaveLayer(
        {}, std::nullopt,
        std::make_shared<MatrixImageFilter>(
            Matrix::MakeTranslation({-300, 10, 0}) * Matrix::MakeScale({2, 2, 1}),
            SamplerDescriptor{}));
    canvas.Restore();
    return canvas.EndRecordingAsPicture();
  };
  ASSERT_TRUE(OpenPlaygroundHere(callback));
}
```

## video
![Untitled](https://github.com/flutter/flutter/assets/30870216/863703f7-60cf-490d-9649-be252ee60397)

**Comment by gaaclarke** [comment]
So I believe the cause is that `MatrixFilterContents::GetFilterCoverage` is based on `FilterInput::GetCoverage` which is based on the size of its `texture_` which is cropped by the viewport and doesn't represent the actual size of the coverage.  We need to make `TextureFilterInput` have another rect that represents the logical size of it's coverage separate from the texture's size.

**Comment by bdero** [comment]
This is a different behavior from the RawMagnifier bug. It's caused by the fact that the root pass is always a fixed size that covers only the screen and nothing more (which it must, because it's an on-screen surface texture). The backdrop filter is correctly transforming the backdrop texture, which is causing the backdrop entity to focus on an area outside the root pass texture, which has no information to sample from.

Checking against Skia fiddle, what we're doing here is actually pretty close to correct: https://fiddle.skia.org/c/c4581c5963cbb734b57463db5d4c9eb3

But by transforming the geometry instead of the "effect", we're always behaving like the tiling mode is kDecal and not respecting the sampling options. The correct behavior here would be to always render to a rectangle that matches the parent pass coverage, but have the matrix filter modify the effect transform and pass it on to the child contents instead (which should be a full TiledTextureContents rather than a texture filter input).

I think this particular issue will be pretty rare in practice. The RawMagnifier bug is definitely high priority though.

**Comment by gaaclarke** [comment]
I think you are thinking of the renderer bug demonstrated in the gif.  When setting the viewport width to 100, it is demonstrating the same ShouldRender->false coverage behavior that is seen in this bugs reproduction code.

![ZPNTIyCm4C3V-rU4FIaep4qdz464iSb0KARWetHTT86kBKaw_63_kzSaRI_DELh6IEv-zv6xvdglT29rjS-Yg8I5I4MPv9f9dc-vP8bYepExFXzvWAfAfpUhU95heR-V4wNwtCPHctyPRkG6SuolJujS0wCiCNSxd_aGcURotKUNHdZIGEHbfJ6zgWK-glcNhYItrAlTz3BCH0cn3rmcdvRp9F6Qf-0pSbMzl6jTnYoLFD4y](https://github.com/flutter/flutter/assets/30870216/b704a6c5-1c35-41f2-be7b-aa481d8146bf)

The test fails because Contents::ShouldRender returns false.  It returns false because there is no intersection between {0, 0, 200, 1536} and {-600, 20, 400, 3027}.  {0, 0, 200, 1536} is the rect that represents the visible pixels of the subpass, that is correct.  {-600, 20, 400, 3027} however is wrong because the width of the Filter's contents should be 2048, not 400.  That comes from 1024 from the destination of the image and 2x from the content scale.

**Comment by gaaclarke** [comment]
I went back and tested overwriting Contents::ShouldRender to always return true and the bug persists in the test I provided and in the reproduction code.  So, it's not just a coverage issue.  It's a rendering issue too.  I thought it was only a coverage issue judging from the way it just winks out of existence.
