### ISSUE TITLE
Build Apk release run Error

### ISSUE THREAD

**Issue by you814455** [flutter/flutter#136026]
flutter doctor -v
```
Flutter (Channel beta, 3.15.0-15.1.pre, on Ubuntu 22.04.2 LTS
    6.2.1-PRoot-Distro, locale C.UTF-8)
    • Flutter version 3.15.0-15.1.pre on channel beta at
      /root/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b2ec15bfa3 (3 weeks ago), 2023-09-14
      15:31:44 -0500
    • Engine revision 3ea1174ecf
    • Dart version 3.2.0 (build 3.2.0-191.0.dev)
    • DevTools version 2.28.0-dev.12
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
```

run Error
```
Redmi/marble/marble:13/TKQ1.221114.001/V14.0.1.0.TMRCNXM:user/release-keys
Abort message: '[FATAL:flutter/runtime/dart_vm_initializer.cc(89)] Error while initializing the Dart VM: Flag dedup_instructions is false in snapshot, but dedup_instructions is always true in product mode'
```

**Comment by darshankawar** [comment]
@you814455 
The error log seems similar to https://github.com/flutter/flutter/issues/106112 which was reported on iOS.
Yours seem to be occuring on Android. Can you provide entire crash log and possibly replicable steps or pattern that leads to this error ?

**Comment by you814455** [comment]
Full log

Redmi/marble/marble:13/TKQ1.221114.001/V14.0.1.0.TMRCNXM:user/release-keys
Abort message: '[FATAL:flutter/runtime/dart_vm_initializer.cc(89)] Error while initializing the Dart VM: Flag dedup_instructions is false in snapshot, but dedup_instructions is always true in product mode'

      #00 pc 000000000008d6f4  /apex/com.android.runtime/lib64/bionic/libc.so (abort+168) (BuildId: 2bb0d7188c0db2e8beecb24658ba9d71)
      #01 pc 000000000036f844  /data/app/~~Q499xrOtxCTwYgOpvH-O4Q==/com.example.demo-jn-amRdx25FAEr5mNC9LyQ==/lib/arm64/libflutter.so (BuildId: 260fb7d0d9697fef5e4484f1e99ef537a0af9961)
      #02 pc 000000000039df98  /data/app/~~Q499xrOtxCTwYgOpvH-O4Q==/com.example.demo-jn-amRdx25FAEr5mNC9LyQ==/lib/arm64/libflutter.so (BuildId: 260fb7d0d9697fef5e4484f1e99ef537a0af9961)
      #03 pc 000000000073703c  /data/app/~~Q499xrOtxCTwYgOpvH-O4Q==/com.example.demo-jn-amRdx25FAEr5mNC9LyQ==/lib/arm64/libflutter.so (BuildId: 260fb7d0d9697fef5e4484f1e99ef537a0af9961)
      #04 pc 00000000003871d0  /data/app/~~Q499xrOtxCTwYgOpvH-O4Q==/com.example.demo-jn-amRdx25FAEr5mNC9LyQ==/lib/arm64/libflutter.so (BuildId: 260fb7d0d9697fef5e4484f1e99ef537a0af9961)
      #05 pc 000000000021a354  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148) (BuildId: 5606c8728ec0bfc21cf8032cde939d22)
      #06 pc 000000000020a2b0  /apex/com.android.art/lib64/libart.so (nterp_helper+4016) (BuildId: 5606c8728ec0bfc21cf8032cde939d22)
      #07 pc 0000000000044514  /data/app/~~Q499xrOtxCTwYgOpvH-O4Q==/com.example.demo-jn-amRdx25FAEr5mNC9LyQ==/oat/arm64/base.vdex (io.flutter.embedding.engine.FlutterJNI.performNativeAttach+0)
      #08 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 5606c8728ec0bfc21cf8032cde939d22)
      #09 pc 0000000000044666  /data/app/~~Q499xrOtxCTwYgOpvH-O4Q==/com.example.demo-jn-amRdx25FAEr5mNC9LyQ==/oat/arm64/base.vdex (io.flutter.embedding.engine.FlutterJNI.attachToNative+30)
      #10 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 5606c8728ec0bfc21cf8032cde939d22)
      #11 pc 0000000000043ea2  /data/app/~~Q499xrOtxCTwYgOpvH-O4Q==/com.example.demo-jn-amRdx25FAEr5mNC9LyQ==/oat/arm64/base.vdex (io.flutter.embedding.engine.a.f+18)
      #12 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 5606c8728ec0bfc21cf8032cde939d22)
      #13 pc 0000000000043dee  /data/app/~~Q499xrOtxCTwYgOpvH-O4Q==/com.example.demo-jn-amRdx25FAEr5mNC9LyQ==/oat/arm64/base.vdex (io.flutter.embedding.engine.a.<init>+422)
      #14 pc 000000000020a958  /apex/com.android.art/lib64/libart.so (nterp_helper+5720) (BuildId: 5606c8728ec0bfc21cf8032cde939d22)
      #15 pc 0000000000043a86  /data/app/~~Q499xrOtxCTwYgOpvH-O4Q==/com.example.demo-jn-amRdx25FAEr5mNC9LyQ==/oat/arm64/base.vdex (io.flutter.embedding.engine.d.b+22)
      #16 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 5606c8728ec0bfc21cf8032cde939d22)
      #17 pc 00000000000439fc  /data/app/~~Q499xrOtxCTwYgOpvH-O4Q==/com.example.demo-jn-amRdx25FAEr5mNC9LyQ==/oat/arm64/base.vdex (io.flutter.embedding.engine.d.a+108)
      #18 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 5606c8728ec0bfc21cf8032cde939d22)
      #19 pc 0000000000039b1c  /data/app/~~Q499xrOtxCTwYgOpvH-O4Q==/com.example.demo-jn-amRdx25FAEr5mNC9LyQ==/oat/arm64/base.vdex (io.flutter.embedding.android.g.I+220)
      #20 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 5606c8728ec0bfc21cf8032cde939d22)
      #21 pc 00000000000392c2  /data/app/~~Q499xrOtxCTwYgOpvH-O4Q==/com.example.demo-jn-amRdx25FAEr5mNC9LyQ==/oat/arm64/base.vdex (io.flutter.embedding.android.g.q+14)
      #22 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 5606c8728ec0bfc21cf8032cde939d22)
      #23 pc 000000000003a496  /data/app/~~Q499xrOtxCTwYgOpvH-O4Q==/com.example.demo-jn-amRdx25FAEr5mNC9LyQ==/oat/arm64/base.vdex (io.flutter.embedding.android.f.onCreate+26)
      #24 pc 00000000004889fc  /system/framework/arm64/boot-framework.oat (android.app.Activity.performCreate+988) (BuildId: b836b41c0c28ae80f9cc7f7fb8c2a9cfaff17d0b)
      #25 pc 00000000001fc0c8  /system/framework/arm64/boot-framework.oat (android.app.Instrumentation.callActivityOnCreate+88) (BuildId: b836b41c0c28ae80f9cc7f7fb8c2a9cfaff17d0b)
      #26 pc 00000000002dc2a4  /system/framework/arm64/boot-framework.oat (android.app.ActivityThread.performLaunchActivity+3940) (BuildId: b836b41c0c28ae80f9cc7f7fb8c2a9cfaff17d0b)
      #27 pc 00000000002e407c  /system/framework/arm64/boot-framework.oat (android.app.ActivityThread.handleLaunchActivity+716) (BuildId: b836b41c0c28ae80f9cc7f7fb8c2a9cfaff17d0b)
      #28 pc 0000000000495904  /system/framework/arm64/boot-framework.oat (android.app.servertransaction.LaunchActivityItem.execute+484) (BuildId: b836b41c0c28ae80f9cc7f7fb8c2a9cfaff17d0b)
      #29 pc 000000000022c30c  /system/framework/arm64/boot-framework.oat (android.app.servertransaction.TransactionExecutor.executeCallbacks+588) (BuildId: b836b41c0c28ae80f9cc7f7fb8c2a9cfaff17d0b)
      #30 pc 000000000022c044  /system/framework/arm64/boot-framework.oat (android.app.servertransaction.TransactionExecutor.execute+772) (BuildId: b836b41c0c28ae80f9cc7f7fb8c2a9cfaff17d0b)
      #31 pc 00000000002c1bfc  /system/framework/arm64/boot-framework.oat (android.app.ActivityThread$H.handleMessage+1324) (BuildId: b836b41c0c28ae80f9cc7f7fb8c2a9cfaff17d0b)
      #32 pc 0000000000541420  /system/framework/arm64/boot-framework.oat (android.os.Handler.dispatchMessage+192) (BuildId: b836b41c0c28ae80f9cc7f7fb8c2a9cfaff17d0b)
      #33 pc 0000000000544818  /system/framework/arm64/boot-framework.oat (android.os.Looper.loopOnce+1080) (BuildId: b836b41c0c28ae80f9cc7f7fb8c2a9cfaff17d0b)
      #34 pc 0000000000544340  /system/framework/arm64/boot-framework.oat (android.os.Looper.loop+560) (BuildId: b836b41c0c28ae80f9cc7f7fb8c2a9cfaff17d0b)
      #35 pc 00000000002da2b4  /system/framework/arm64/boot-framework.oat (android.app.ActivityThread.main+1364) (BuildId: b836b41c0c28ae80f9cc7f7fb8c2a9cfaff17d0b)
      #36 pc 0000000000210c00  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+576) (BuildId: 5606c8728ec0bfc21cf8032cde939d22)
      #37 pc 000000000027b4ac  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+240) (BuildId: 5606c8728ec0bfc21cf8032cde939d22)
      #38 pc 000000000061a16c  /apex/com.android.art/lib64/libart.so (_jobject* art::InvokeMethod<(art::PointerSize)8>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1400) (BuildId: 5606c8728ec0bfc21cf8032cde939d22)
      #39 pc 0000000000599c88  /apex/com.android.art/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+52) (BuildId: 5606c8728ec0bfc21cf8032cde939d22)
      #40 pc 0000000000099148  /system/framework/arm64/boot.oat (art_jni_trampoline+120) (BuildId: 7998da7e10cd75385a266d754f3c1cda2bfdc9ea)
      #41 pc 0000000000734670  /system/framework/arm64/boot-framework.oat (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+144) (BuildId: b836b41c0c28ae80f9cc7f7fb8c2a9cfaff17d0b)
      #42 pc 000000000073d9ac  /system/framework/arm64/boot-framework.oat (com.android.internal.os.ZygoteInit.main+3228) (BuildId: b836b41c0c28ae80f9cc7f7fb8c2a9cfaff17d0b)
      #43 pc 0000000000210c00  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+576) (BuildId: 5606c8728ec0bfc21cf8032cde939d22)
      #44 pc 000000000027b4ac  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+240) (BuildId: 5606c8728ec0bfc21cf8032cde939d22)
      #45 pc 000000000061a8f4  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, std::__va_list)+452) (BuildId: 5606c8728ec0bfc21cf8032cde939d22)
      #46 pc 000000000061ade0  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+96) (BuildId: 5606c8728ec0bfc21cf8032cde939d22)
      #47 pc 0000000000501af8  /apex/com.android.art/lib64/libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+600) (BuildId: 5606c8728ec0bfc21cf8032cde939d22)
      #48 pc 00000000000c1c04  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+124) (BuildId: 362359a0fbd1851ef36271480f0271f4)
      #49 pc 00000000000cebe4  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+924) (BuildId: 362359a0fbd1851ef36271480f0271f4)
      #50 pc 0000000000002610  /system/bin/app_process64 (main+1464) (BuildId: 6363373b68588b10c93602a28a32bb57)
      #51 pc 000000000008593c  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+100) (BuildId: 2bb0d7188c0db2e8beecb24658ba9d71)

**Comment by darshankawar** [comment]
Thanks for the update. Does this error occur while trying to build apk for default counter app running on same device ?
