### ISSUE TITLE
64bit float storage of Path for CustomPainter

### ISSUE THREAD

**Issue by beelabcloud** [flutter/flutter#136016]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

```dart
Rect r=Rect.fromPoints(Offset(1696422077.3,227.98828125),Offset(1696422087.3,246.5546875));
Path p=Path();
p.moveTo(r.left, r.top);
p.lineTo(r.right, r.bottom);
Rect rb=p.getBounds();
print("rect actual: $r, width: ${r.width}, height: ${r.height}");
print("Path bound:  $rb, width: ${rb.width}, height: ${rb.height}");
```

The output would be like:, 

```console
flutter: rect actual: Rect.fromLTRB(1696422077.3, 228.0, 1696422087.3, 246.6), width: 10.0, height: 18.56640625
flutter: Path bound:  Rect.fromLTRB(1696422016.0, 228.0, 1696422144.0, 246.6), width: 128.0, height: 18.56640625
```

Obviously, the storage of path is single float rather than double float. Therefore, is it possible to provide an option to change the precision of storage of Path 

### Proposal

```dart
Path p=Path(doubleFloat:true);
```

**Comment by chinmaygarde** [comment]
I don't think we can consider this at this time. Is it possible to use floats and the scale the canvas prior to rendering??

**Comment by beelabcloud** [comment]
Sure, it's ok since the data can be translated.
