### ISSUE TITLE
Log error: FlutterDarwinContextMetalImpeller.mm

### ISSUE THREAD

**Issue by DiegoGW** [flutter/flutter#136046]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Get latest version of Wonderous app (This is the log when this issue was created - commit a04d8bbb71c2a1a00e393218de6e44dc2ad0559a (HEAD -> main, origin/main, origin/HEAD)
Merge: https://github.com/flutter/flutter/commit/8a29d67fa4eb7947b01c5eba330f1fd52a23da47 509487f
Author: Shawn [shawn@gskinner.com](mailto:shawn@gskinner.com)
Date: Mon Oct 2 14:02:12 2023 -0600
Merge pull request https://github.com/flutter/flutter/issues/124 from yangsfang/yangsfang-patch-1
Fix throttler calling an action twice
)

2. Run Wonderous in XCode (target: iPhone 14Pro + iOS 17.0.2)
3. Launch wonderous
4. Check the log:

```
[ERROR:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalImpeller.mm(42)] Using the Impeller rendering backend.
```

### Expected results

None errors should be logged

### Actual results

After launching any flutter app, the following error is logged:
```
[ERROR:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalImpeller.mm(42)] Using the Impeller rendering backend.

```

### Code sample

<details><summary>Code sample</summary>

```Wonderous
git clone  https://github.com/gskinnerTeam/flutter-wonderous-app.git
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[ERROR:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalImpeller.mm(42)] Using the Impeller rendering backend.
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.16.0-2.0.pre.8, on macOS 13.5 22G74 darwin-arm64, locale en-US)
    • Flutter version 3.16.0-2.0.pre.8 on channel master at /Users/diegogawenda/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b71f8ce7ae (2 hours ago), 2023-10-02 15:09:38 -0400
    • Engine revision f3a92cb0c4
    • Dart version 3.2.0 (build 3.2.0-221.0.dev)
    • DevTools version 2.28.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/diegogawenda/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/diegogawenda/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/diegogawenda/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.80.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (4 available)
    • Pixel 6 (mobile)         • 1A141FDF600823            • android-arm64  • Android 13 (API 33)
    • Somnio’s iPhone (mobile) • 00008120-001168D83C87C01E • ios            • iOS 17.0.2 21A351
    • macOS (desktop)          • macos                     • darwin-arm64   • macOS 13.5 22G74 darwin-arm64
    • Chrome (web)             • chrome                    • web-javascript • Google Chrome 117.0.5938.92

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by chinmaygarde** [comment]
This is working as intended for now during the migration to Impeller. This may be removed later in the future.

**Comment by rzambroni** [comment]
Hey @chinmaygarde, sorry to bug you about this but we still see this issue on recent versions of Flutter. I was wondering if the migration is still in motion or if we should be worried about this error log. 

Thanks!

**Comment by chinmaygarde** [comment]
There is no error here. We were logging it at the incorrect level which unfortunately caused alarm. In the latest releases, this should not be tagged as an error. There is nothing to worry about because of this log.
