### ISSUE TITLE
Recipe testing is not updating the run status

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#136084]
Recipe testing is blocking after triggering all the builds and not updating until everything finishes.

**Comment by keyonghan** [comment]
Could you provide more context? Is it the request to split the recipe testing to separate builds for chosen/triggered ones?

**Comment by godofredoc** [comment]
This is a consequence of moving recipe testing from swarming to buildbucket.

![image](https://github.com/flutter/flutter/assets/54371434/19c4ee84-bee5-420d-9100-f7c734974ddc)

Previously every few mins the completed of failed tasks were presented in the UI. Now everything is updated after all the builds complete or the collect step times out.

https://cs.opensource.google/flutter/recipes/+/master:recipe_modules/subbuild/api.py;l=272?q=buildbucket.collect_builds&sq=&ss=flutter%2Frecipes

In this case buildbucket.collect_builds is a blocker call.

**Comment by keyonghan** [comment]
Closing as dup of https://github.com/flutter/flutter/issues/136084.
