### ISSUE TITLE
Flutter Web crash in IOS mobile if greater than version of IOS 15

### ISSUE THREAD

**Issue by VishalUndhadeww** [flutter/flutter#136020]
I am developing one website in flutter web and that crash randomly in IOS device if device version is greater than 15. I am investing more time in that and i can't find any proper solution.

I have checked with different different way like clear cache and controller delete and many more.

**Comment by huycozy** [comment]
Hi @VishalUndhadeww 
When opening an issue, please try to provide all information indicated in the template so that we can address this issue properly (See bug issue template [here](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml))

**Comment by VishalUndhadeww** [comment]
That web site is working fine in local. But when I deploy in live server the crash randomly in mobile browser. So, I can't get any logs.

**Comment by huycozy** [comment]
You can try running your project in `release` mode to see if it occurs or not. 

In case the crash only occurs on mobile browser, you can try connecting with Macbook by cable and inspecting mobile browser console from Macbook's Safari browser (check [this video](https://www.youtube.com/watch?v=4gnxf9LFpC0&ab_channel=CodinginPublic) for details). The crash might be in the Console tab.

Also, please provide the output of `flutter doctor -v` and affected device information (OS, model).

**Comment by VishalUndhadeww** [comment]
Yes, I tried with release mode with render HTML and auto. 

Yes, this crash only occurs on mobile browser. That works fine in laptop and desktop. So, not sure what the issue.

Please find the below screenshot for `flutter doctor -v` command.

<img width="2519" alt="Screenshot 2023-10-09 at 2 07 24 PM" src="https://github.com/flutter/flutter/assets/114661145/b4438315-627d-474b-9654-e2ae1fb813ca">

**Comment by huycozy** [comment]
>Please find the below screenshot for flutter doctor -v command.

Please provide the output in text format instead of a screenshot for better readability. (You may want to refer to [writing and formatting syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) for beautifully formatted text)

>this crash only occurs on mobile browser.

Please try to get the crash log from browser as the method I shared above. Without more information, we are not sure what the issue you are having is.
