### ISSUE TITLE
[Impeller] Clip area is offsetting backdrop image filter

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#136083]
found while investigating https://github.com/flutter/flutter/issues/136058

cc @bdero 

## reproduction

```c++
TEST_P(AiksTest, MatrixImageFilterClippedBackdropImageFilter) {
  Canvas canvas;
  canvas.Scale(GetContentScale());
  auto image = std::make_shared<Image>(CreateTextureForFixture("airplane.jpg"));
  canvas.DrawImage(image, {0, 0},
                   Paint{.color = Color::White().WithAlpha(0.5)});
  // Commenting and uncommenting the following line changes what renders inside of the box.
  // canvas.ClipRect({800, 10, 200, 200});
  canvas.SaveLayer(
      {}, std::nullopt,
      std::make_shared<MatrixImageFilter>(
          Matrix::MakeTranslation({800, 10, 0}) * Matrix::MakeScale({2, 2, 2}),
          SamplerDescriptor{}));
  canvas.Restore();
  ASSERT_TRUE(OpenPlaygroundHere(canvas.EndRecordingAsPicture()));
}
```

## with clip
<img width="1024" alt="Screenshot 2023-10-06 at 12 14 06 PM" src="https://github.com/flutter/flutter/assets/30870216/5b694e80-6f3a-4677-b79d-ca0652ff892a">

## without clip
<img width="1026" alt="Screenshot 2023-10-06 at 12 13 31 PM" src="https://github.com/flutter/flutter/assets/30870216/6a9eef3c-8010-4542-929e-e3c6e95b322a">

## expected results

I expect the pixels inside of the clip rect to be the same.

**Comment by gaaclarke** [comment]
Actually the results should probably be a black clip rect.  Because if the SaveLayer call is supposed to be affected by the clip region, it should be grabbing the contents at {800, 10, 200, 200}, then drawing that in the save layer restore with the matrix.  The box should be all black.  It appears that the region being grabbed is {400, 5, 100, 100} which is not respecting the scale specified in `canvas.Scale(GetContentScale());`

**Comment by chinmaygarde** [comment]
@gaaclarke @bdero We don't know if this is still an issue after all the work around save layers recently. If you know off the top of your head, can you add an update? If not, we'll keep this as a blocker for removal of Skia.

**Comment by gaaclarke** [comment]
This still exhibits the same behavior.  This issue doesn't compare the output with skia's definitively.  I'll attempt that.

**Comment by gaaclarke** [comment]
I've tried to reproduce this at the Dart level and I can't.  The clip isn't respected on Skia or Impeller.  So while this behavior might not be correct, it doesn't matter if it can't be accessed via the Dart interface.

```
  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return Directionality(
        textDirection: TextDirection.ltr,
        child: Stack(
          fit: StackFit.expand,
          children: <Widget>[
            Image.asset('assets/airplane.jpg'),
            ClipRect(
              child: BackdropFilter(
                filter: ui.ImageFilter.matrix(Matrix4(//
                  2.0, 0.0, 0.0, 0.0,//
                  0.0, 2.0, 0.0, 0.0,//
                  0.0, 0.0, 1.0, 0.0,//
                  10.0, 10.0, 0.0, 1.0).storage),
                child: Container(
                  alignment: Alignment.center,
                  width: 10.0,
                  height: 10.0,
                ),
              ),
            ),
          ],
        ),
      );
    });
  }
```
<img width="968" alt="Screenshot 2024-03-12 at 9 39 28 AM" src="https://github.com/flutter/flutter/assets/30870216/c07a8598-88ae-4b23-9e55-37012c04c2da">
