### ISSUE TITLE
google_sign_in 1.0.1 and firebase_auth 0.3.2: DexException

### ISSUE THREAD

**Issue by jmnyv** [flutter/flutter#13609]
Using the latest version of `google_sign_in` (`1.0.1`) in `pubspec.yaml`, together with `classpath 'com.google.gms:google-services:3.1.0'` in the root level gradle file and `apply plugin: 'com.google.gms.google-services'` on the last level of the app gradle file, results in:

```
Execution failed for task ':app:transformClassesWithDexForDebug'.
com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzdld;

```

 

Version 0.3.1 does not have this issue.

**Comment by bjornbjorn** [comment]
Most likely related to #12945 since firebase_auth has updated its GMS dependency to 11.4.+

However, I'm still getting the same error you're getting even after updating the dependency reference directly in the android/build.grade file to this:

```
dependencies {
    compile 'com.google.android.gms:play-services-auth:11.4.+'
    compile 'com.google.guava:guava:20.0'
}
```

**Comment by Hixie** [comment]
cc @collinjackson

**Comment by zoechi** [comment]
Similar to #13079

**Comment by kroikie** [comment]
@jmnyv

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/925. Any further collaboration will be done there.

**Comment by BondarenkoStas** [comment]
Is the issue still relevant?
