### ISSUE TITLE
There are wrong de-CH translations in package/flutter-localization

### ISSUE THREAD

**Issue by rekire** [flutter/flutter#136090]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I found in [`MaterialLocalizationDe`](https://github.com/flutter/flutter/blob/420ec92e7274135b3611a0ab92f8645bd5504f5e/packages/flutter_localizations/lib/src/l10n/generated_material_localizations.dart#L6769) a translation "TBD" and some clear translation errors like there is no `ß` in de-CH

### Expected results

No TBD translations in German and no `ß` letters in de-CH.

### Actual results

There is a translation "TBD" which seems to be wrong. I also found wrong translations for de-CH (basically de-DE just in upper case) and some clear translation errors like there is no `ß` in de-CH

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by goderbauer** [comment]
FYI @HansMuller

**Comment by rekire** [comment]
Any updates here?

Might be not the right place here, but is a test required for fixing this?

**Comment by rekire** [comment]
Just FYI there are more such wrong translations. I just cannot translate those languages and I think it doesn't make sense to use some automatic translation tools.

**Comment by rekire** [comment]
```bash
% grep TBD packages/flutter_localizations/lib/src/l10n/*.arb | wc -l
65
```

**Comment by rekire** [comment]
Those "TBD" translations [are from 2018](https://github.com/flutter/flutter/pull/21029)

**Comment by rekire** [comment]
@HansMuller what is about my PR #136091 which corrects some translations? Is it worthless since I cannot edit the Google internal message IDs?

**Comment by HansMuller** [comment]
@rekire - your suggestions for translation updates in https://github.com/flutter/flutter/pull/136091 are useful. I'll need to route them through Google's localization team.
