### ISSUE TITLE
Networking documentation point to deprecated API

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#13602]
Our networking documentation recommends using [`createHttpClient`](https://docs.flutter.io/flutter/services/createHttpClient.html):
https://flutter.io/networking/

This is marked deprecated.

**Comment by mit-mit** [comment]
@Hixie, I'm having trouble understanding the recommendation. Is it to replace:

```
import 'package:flutter/services.dart';
var httpClient = createHttpClient();
```

with:

```
import 'dart:io';
var httpClient = new HttpClient();
```

?

**Comment by sethladd** [comment]
with:

```
class MyHttpClient implements HttpClient {
   ...
   // An implementation of the HttpClient interface
   ...
}

main() {
   HttpOverrides.runZoned(() {
     ...
     // Operations will use MyHttpClient instead of the real HttpClient
     // implementation whenever HttpClient is used.
     ...
   }, createHttpClient: (SecurityContext c) => new MyHttpClient(c));
 }
```

**Comment by Hixie** [comment]
Woah, I didn't realize the dart:io overrides required using zones. That's unfortunate. How do you override it for everything including things not in your zone, e.g. if you want other libraries and widgets and so forth to also be overridden?

**Comment by sethladd** [comment]
cc @zanderso @floitschG

**Comment by zanderso** [comment]
In an initial draft of the API, I had a way to set overrides in the root Zone, which all zones would then inherit from unless installing their own overrides. Maybe @floitschG remembers why we decided to remove that. I think it shouldn't be too hard to add back, though.

**Comment by zanderso** [comment]
https://dart-review.googlesource.com/c/sdk/+/30100

**Comment by mit-mit** [comment]
Sorry, I'm more confused now: If I just want to make an http request, why do I need to create a custom client class?

**Comment by mit-mit** [comment]
Just had a chance to discuss with Florian. The example above for overrides is only meant for cases like mocking for testing, right? If I just want to make an http request, I can just do this, right?

```
import 'dart:io';
var httpClient = new HttpClient();
var response = await httpClient.read('https://httpbin.org/ip');
```

**Comment by sethladd** [comment]
`var httpClient = new HttpClient();` is how you use the client.

You need `HttpOverrides` when you want to:

* provide a mock
* extend the behavior of the default HttpClient class, for example if you want to add custom caching or retry logic

Even when you use `HttpOverrides`, you still use `new HttpClient()` when you want to use the client in your code.

**Comment by mit-mit** [comment]
Got it. Lastly, when do we recommend `dart:io`'s `HttpClient` vs `package:http`?

**Comment by sethladd** [comment]
We don't :) We leave it up to the developer. The framework itself it attempting to reduce dependencies, so the choice to use package:http can be made by the developer.

**Comment by mit-mit** [comment]
PR: https://github.com/flutter/website/pull/769

**Comment by sethladd** [comment]
For anyone following this trail, there is a new convenience method for globally overriding HttpClient: https://github.com/dart-lang/sdk/blob/master/sdk/lib/_http/overrides.dart#L44

(specifically: HttpOverrides.global)
