### ISSUE TITLE
App Crash on pick image

### ISSUE THREAD

**Issue by cp-pratik-k** [flutter/flutter#136028]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Create flutter app on letest flutter version 3.13.6
Add image_picker 1.0.4 dependency
Try to pic image from gallery using iOS 17, (i have used i phone 14 with i0S 17)

### Expected results

pick image from gallery normally.

### Actual results

App was creshed and closed.

### Code sample

 final XFile? image =    await ImagePicker().pickImage(source: ImageSource.gallery);

### Logs
Exception: Unable to terminate {app_bundle_id} on XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX:
ProcessException: Process exited abnormally:
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):
Simulator device returned an error for the requested operation.
found nothing to terminate
Underlying error (domain=NSPOSIXErrorDomain, code=3):
	The request to terminate "{app_bundle_id}" failed. found nothing to terminate
	found nothing to terminate
  Command: /usr/bin/arch -arm64e xcrun simctl terminate XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
  {app_bundle_id}
  
  i have replaced {app_bundle id} and code under X.

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.13.6, on macOS 14.0 darwin-arm64, locale en-IN)
    • Flutter version 3.13.6 on channel stable at /Users/pratikcanopas/Flutter_sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (8 days ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/pratikcanopas/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Connected device (4 available)
    • iPhone 14 Pro (mobile) •{device id } • ios             • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • iPhone 15 Pro (mobile) • {device id} • ios             • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)        • macos                              • darwin-arm64   • macOS 14.0 
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 
[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by cp-pratik-k** [comment]
@jonahwilliams please review this

**Comment by huycozy** [comment]
Hi @cp-pratik-k 
I checked [plugin sample code](https://github.com/flutter/packages/tree/main/packages/image_picker/image_picker/example) on iOS 17 device but can't reproduce this.

Can you try this sample code and confirm? If the crash only occur on your code, please provide the complete output of `flutter run -v`.
