### ISSUE TITLE
Screen orientation on iOS is always default.

### ISSUE THREAD

**Issue by olintosynergy** [flutter/flutter#136049]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I'm setting the screen orientation in: 
SystemChrome.setPreferredOrientations(
          [DeviceOrientation.portraitUp]);

But inside controller?.value.deviceOrientation, even with the iPhone in portrait format I receive:
flutter: DeviceOrientation.landscapeLeft

If I go to the IOS settings and lock the screen orientation, everything works as expected. However, I already define this in the code, as the App has screens where I need to use the orientation in LandsCap and other screens in Portrait

### Expected results

Respect the defined guidance:  DeviceOrientation.portraitUp

### Actual results

flutter: DeviceOrientation.landscapeLeft

### Code sample

<details><summary>Code sample</summary>

```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await EasyLocalization.ensureInitialized();

  // Screen in Portrait Mode
  SystemChrome.setPreferredOrientations(
      [DeviceOrientation.portraitUp]);


```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
not
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.0 22A8381 darwin-arm64, locale fr-CA)
    • Flutter version 3.13.0 on channel stable at /Users/olinto.souza/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (7 weeks ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/olinto.souza/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.81.1)
    • VS Code at /Users/olinto.souza/Documents/Visual Studio Code 3.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 12 (API 32) (emulator)
    • iPhone de Olinto (mobile)   • 00008101-0014305924A1401E            • ios            • iOS 16.6.1 20G81
    • iPhone12 (mobile)           • FC7F4D88-C23E-4A53-8A0F-34DD27288FCE • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 13.0 22A8381 darwin-arm64
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 117.0.5938.149
    ! Error: Apple Watch de Olinto has not finished loading development services. Please select a different device, or wait for the device to load development services and try again. (code 8)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by huycozy** [comment]
I check this issue with below sample code but the app persists in portrait mode as expected (even when device's orientation is not locked):

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();

  // Screen in Portrait Mode
  SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);

  runApp(
    MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const Scaffold(
        body: Center(
          child: Text(
            'Hello',
          ),
        ),
      ),
    ),
  );
}

```
</details>

Please provide a complete sample code and step-by-step to reproduce the issue you see.

**Comment by olintosynergy** [comment]
Yes, because portrait mode has been set, so even if the device's orientation is locked or not, it will always be in portrait mode. What I can say is that even so, when I activate the camera, it turns, it's as if it hadn't stopped.

class DocumentScanScreen extends StatefulWidget {
  const DocumentScanScreen({Key? key, required this.title, required this.typeCard, required this.iconAsset}) : super(key: key);

  final String title;
  final String typeCard;
  final String iconAsset;

  @override
  State<DocumentScanScreen> createState() => _DocumentScanScreenState();
}

class _DocumentScanScreenState extends State<DocumentScanScreen> {
  List<CameraDescription> cameras = [];
  CameraController? controller;
  XFile? image;
  Size? size;
  double turns = 0.0;
  bool inCapture = false;
  bool loadCamera = false;

  final GlobalKey<ScaffoldState> _scaffoldKey = GlobalKey<ScaffoldState>();
  late Future<bool> Function() onBackPress;

  @override
  void initState() {
    super.initState();

    onBackPress = () async {
      Navigator.of(context).pop();
      return true;
    };
  }

  @override
  void dispose() {
    super.dispose();
  }

  _loadCameras() async {
    try {
      cameras = await availableCameras();
      _startCamera();
    } on CameraException catch (e) {
      debugPrint(e.description);
    }
  }

  _startCamera() {
    if (cameras.isEmpty) {
      debugPrint('Camera not found!');
      showSnackBar(
          context: context,
          text: const Text(
            'Camera not found!',
            style: TextStyle(fontSize: 16, fontWeight: FontWeight.w700),
          ),
          color: kColorRedError);
    } else {
      _previewCamera(cameras.first);

      setState(() {
        loadCamera = true;
      });
    }
  }

  _previewCamera(CameraDescription camera) async {
    final CameraController cameraController = CameraController(
      camera,
      ResolutionPreset.medium,
      enableAudio: false,
      imageFormatGroup: ImageFormatGroup.jpeg,
    );
    controller = cameraController;

    try {
      await cameraController.initialize();
    } on CameraException catch (e) {
      debugPrint(e.description);
    }

    if (mounted) {
      setState(() {});
    }
  }

  @override
  Widget build(BuildContext context) {
    size = MediaQuery.of(context).size;

    return Scaffold(
        key: _scaffoldKey,
        body: Consumer<LoginManager>(
          builder: (_, loginManager, __) {
            if (loginManager.loading) {
              return const Center(
                child: CircularProgressIndicator(
                  valueColor: AlwaysStoppedAnimation<Color>(kColorGrey4),
                ),
              );
            }

            return Stack(
              alignment: Alignment.center,
              children: [
                if (loadCamera) _cardCameraPreviewWidget(),
                Padding(
                  padding: const EdgeInsets.only(top: 150, left: 16, right: 16),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      if (!loadCamera) ...[
                        Text(
                          widget.typeCard,
                          style: const TextStyle(fontWeight: FontWeight.w600, fontSize: 16),
                        ),
                        const SizedBox(
                          height: 10,
                        ),
                        InkWell(
                            onTap: () {
                              setState(() {
                                image = null;
                              });

                              _loadCameras();
                            },
                            child: _cardPicture()),
                        if (image != null) ...[
                          Padding(
                            padding: const EdgeInsets.only(top: 10),
                            child: SizedBox(
                              height: 60,
                              child: CustomPrimaryButton(
                                icon: Icomoon.send,
                                iconColor: Colors.white,
                                title: 'lbl_btn_save'.tr(),
                                backgroundColor: kColorRed,
                                borderColor: kColorRed,
                                fontSize: 16,
                                fontWeight: FontWeight.w600,
                                textColor: Colors.white,
                                onPressed: () async {
                                  // 1 - Step: Send picture to Blob
                                  await loginManager.uploadPictureCardStorage(
                                      file: File(image!.path),
                                      onError: (e) => showSnackBar(context: context, text: Text(e.toString()), color: kColorRed),
                                      onSuccess: (url) {
                                        // 2 - Step: Send URL to IA

                                        // Verify type card
                                        if (widget.title.contains('CCQ')) {
                                          loginManager.sendUrlCCQToIa(
                                              url: url,
                                              onError: (e) => showSnackBar(context: context, text: Text(e.toString()), color: kColorRed),
                                              onSuccess: () {
                                                showSnackBar(context: context, text: const Text('lbl_snack_success_card').tr(), color: kColorGreen);

                                                Navigator.pop(context);
                                              });
                                        } else {
                                          loginManager.sendUrlDriverLicenceToIa(
                                              url: url,
                                              onError: (e) => showSnackBar(context: context, text: Text(e.toString()), color: kColorRed),
                                              onSuccess: () {
                                                showSnackBar(context: context, text: const Text('lbl_snack_success_card').tr(), color: kColorGreen);

                                                Navigator.pop(context);
                                              });
                                        }
                                      });
                                },
                              ),
                            ),
                          ),
                          Padding(
                            padding: const EdgeInsets.only(top: 10),
                            child: SizedBox(
                              height: 60,
                              child: CustomPrimaryButton(
                                icon: Icons.camera_alt,
                                iconColor: kColorRed,
                                title: 'lbl_btn_try_again'.tr(),
                                backgroundColor: Colors.white,
                                borderColor: kColorRed,
                                fontSize: 16,
                                fontWeight: FontWeight.w600,
                                textColor: kColorRed,
                                onPressed: () {
                                  setState(() {
                                    image = null;
                                  });

                                  _loadCameras();
                                },
                              ),
                            ),
                          )
                        ],
                        const SizedBox(
                          height: 30,
                        ),
                        const Text(
                          'lbl_title_guide_carte',
                          style: TextStyle(fontSize: 14, fontWeight: FontWeight.w400),
                        ).tr(),
                        const SizedBox(
                          height: 30,
                        ),
                        Center(child: SvgPicture.asset(widget.iconAsset))
                      ],
                    ],
                  ),
                ),
                Positioned(
                  top: 60,
                  left: 0,
                  right: 0,
                  child: Column(
                    children: [
                      SvgPicture.asset(
                        "assets/images/scan2_icon.svg",
                        key: const Key("image"),
                        height: 30,
                      ),
                      const SizedBox(
                        height: 10,
                      ),
                      Text(
                        key: const Key("title"),
                        widget.title,
                        style: const TextStyle(fontSize: 16, fontWeight: FontWeight.w600),
                      ),
                    ],
                  ),
                ),
                Align(
                  alignment: Alignment.topLeft,
                  child: Padding(
                    padding: const EdgeInsets.only(top: 60, left: 16),
                    child: CustomIconButton(
                        key: const Key('backButton'), iconData: Icomoon.chevronLeft, color: Colors.black, size: 30, onTap: onBackPress),
                  ),
                ),
              ],
            );
          },
        ));
  }

  _cardCameraPreviewWidget() {
    return SizedBox(
        width: size!.width - 60,
        height: image == null ? size!.height - (size!.height / 3) : 300,
        child: _cameraPreviewWidget()
    );
  }

  _cameraPreviewWidget() {
    final CameraController? cameraController = controller;

    if (cameraController == null || !cameraController.value.isInitialized) {
      return const Center(child: CircularProgressIndicator(valueColor: AlwaysStoppedAnimation<Color>(kColorGrey4)));
    } else {

      return Stack(
        alignment: Alignment.center,
        children: [
          Row(
            children: [
              const SizedBox(
                width: 15,
              ),
              Expanded(
                  child: CameraPreview(controller!,
                      child: inCapture
                          ? Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          const Text(
                            'lbl_progress_picture',
                            textAlign: TextAlign.center,
                            style: TextStyle(color: Colors.white, fontWeight: FontWeight.w600, fontSize: 25),
                          ).tr(),
                          const SizedBox(
                            height: 10,
                          ),
                          const CircularProgressIndicator(
                            valueColor: AlwaysStoppedAnimation<Color>(kColorGrey4),
                          )
                        ],
                      )
                          : Container()),
              ),
              const SizedBox(
                width: 10,
              ),
              RotatedBox(
                quarterTurns: 1,
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    const Text(
                      'lbl_text_scan_1',
                      textAlign: TextAlign.center,
                      style: TextStyle(color: Colors.black, fontWeight: FontWeight.w600, fontSize: 14),
                    ).tr(),
                    const Text(
                      'lbl_text_scan_2',
                      textAlign: TextAlign.center,
                      style: TextStyle(color: kColorRed, fontWeight: FontWeight.bold, fontSize: 14),
                    ).tr(),
                    const Text(
                      'lbl_text_scan_3',
                      textAlign: TextAlign.center,
                      style: TextStyle(color: Colors.black, fontWeight: FontWeight.w600, fontSize: 14),
                    ).tr(),
                  ],
                ),
              )
            ],
          ),
          Positioned(
            left: 0,
            child: _captureButtonWidget(),
          )
        ],
      );
    }
  }

  _captureButtonWidget() {
    return Padding(
        padding: const EdgeInsets.only(bottom: 24),
        child: RotatedBox(
          quarterTurns: 1,
          child: CircleAvatar(
            radius: 40,
            backgroundColor: Colors.black.withOpacity(0.5),
            child: CustomIconButton(
              iconData: Icons.camera_alt,
              color: Colors.white,
              size: 45,
              onTap: () {
                setState(() {
                  inCapture = true;
                });

                _takePicture();
              },
            ),
          ),
        ));
  }

  _takePicture() async {
    final CameraController? cameraController = controller;

    if (cameraController != null && cameraController.value.isInitialized) {
      try {
        XFile file = await cameraController.takePicture();
        if (mounted) {
          setState(() {
            image = file;

            inCapture = false;
            loadCamera = false;
          });
        }
      } on CameraException catch (e) {
        debugPrint(e.description);
      }
    }
  }

  _cardPicture() {
    return Container(
        margin: const EdgeInsets.only(top: 10),
        height: 210,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(10),
          border: Border.all(
            color: kColorGrey5,
            width: 1,
          ),
        ),
        child: Center(
          child: (image == null && !loadCamera)
              ? SvgPicture.asset(
                  'assets/images/camera_plus_icon.svg',
                  width: 30,
                  height: 30,
                )
              : RotatedBox(
                  quarterTurns: 3,
                  child: Image.file(
                    File(image!.path),
                    width: double.infinity,
                    height: double.infinity,
                    fit: BoxFit.cover,
                  ),
                ),
        ));
  }
}

**Comment by huycozy** [comment]
I put your sample code into a code block for better readability. But it's a production code that will be not easy for us to debug the issue. It seems you are using `camera` plugin, I'd recommend you provide:

- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code
- Detailed steps to reproduce the issue (for instance: open screen A, navigate to screen B, etc)

**Comment by olintosynergy** [comment]
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:camera/camera.dart';
import 'package:flutter/services.dart';

class DocumentsPage extends StatefulWidget {
  const DocumentsPage({Key? key}) : super(key: key);

  @override
  State<DocumentsPage> createState() => _DocumentsPageState();
}

class _DocumentsPageState extends State<DocumentsPage> {
  List<CameraDescription> cameras = [];
  CameraController? controller;
  XFile? imagem;
  Size? size;

  @override
  void initState() {
    super.initState();
    _loadCameras();

    // Screen in Portrait Mode
    SystemChrome.setPreferredOrientations(
        [DeviceOrientation.portraitUp]);
  }

  _loadCameras() async {
    try {
      cameras = await availableCameras();
      _startCamera();
    } on CameraException catch (e) {
      debugPrint(e.description);
    }
  }

  _startCamera() {
    if (cameras.isEmpty) {
      debugPrint('Câmera não foi encontrada');
    } else {
      _previewCamera(cameras.first);
    }
  }

  _previewCamera(CameraDescription camera) async {
    final CameraController cameraController = CameraController(
      camera,
      ResolutionPreset.high,
      enableAudio: false,
      imageFormatGroup: ImageFormatGroup.jpeg,
    );
    controller = cameraController;

    try {
      await cameraController.initialize();
    } on CameraException catch (e) {
      debugPrint(e.description);
    }

    if (mounted) {
      setState(() {});
    }
  }

  @override
  Widget build(BuildContext context) {
    size = MediaQuery.of(context).size;
    return Scaffold(
      appBar: AppBar(
        title: const Text('Documento Oficial'),
        backgroundColor: Colors.grey[900],
        centerTitle: true,
        elevation: 0,
      ),
      body: Container(
        color: Colors.grey[900],
        child: Center(
          child: _fileWidget(),
        ),
      ),
      floatingActionButton: (imagem != null)
          ? FloatingActionButton.extended(
        onPressed: () => Navigator.pop(context),
        label: const Text('Finalizar'),
      )
          : null,
      floatingActionButtonLocation: FloatingActionButtonLocation.centerFloat,
    );
  }

  _fileWidget() {
    return SizedBox(
      width: size!.width - 50,
      height: size!.height - (size!.height / 3),
      child: imagem == null
          ? _cameraPreviewWidget()
          : Image.file(
        File(imagem!.path),
        fit: BoxFit.contain,
      ),
    );
  }

  _cameraPreviewWidget() {
    final CameraController? cameraController = controller;

    if (cameraController == null || !cameraController.value.isInitialized) {
      return const Text('Widget para Câmera que não está disponível');
    } else {
      return Stack(
        alignment: AlignmentDirectional.bottomCenter,
        children: [
          CameraPreview(controller!),
          _btnTakeWidget(),
        ],
      );
    }
  }

  _btnTakeWidget() {
    return Padding(
      padding: const EdgeInsets.only(bottom: 24),
      child: CircleAvatar(
        radius: 32,
        backgroundColor: Colors.black.withOpacity(0.5),
        child: IconButton(
          icon: const Icon(
            Icons.camera_alt,
            color: Colors.white,
            size: 30,
          ),
          onPressed: takePicture,
        ),
      ),
    );
  }

  takePicture() async {
    final CameraController? cameraController = controller;

    if (cameraController != null && cameraController.value.isInitialized) {
      try {
        XFile file = await cameraController.takePicture();
        if (mounted) setState(() => imagem = file);
      } on CameraException catch (e) {
        debugPrint(e.description);
      }
    }
  }
}

**Comment by huycozy** [comment]
Thanks for your sample code but I'm still not clear on what is the issue and how to reproduce it.

I ran your sample code (it's a single page only) on my device, the camera preview is in portrait mode as expected. Is it in landscape mode on your device? If so, could you share the device information? (OS, model)

<details>
<summary>Demo screenshot on my device (iPhone 7, iOS 15.7.9)</summary>

<img width="400" src="https://github.com/flutter/flutter/assets/104349824/273e9a7d-4a72-4433-9288-1d1a3212f346">

</details>

**Comment by huycozy** [comment]
Below is the demo on my device `iPhone 7, iOS 15.7.9` with your sample code above:

1. device rotation locked: When rotating device, camera preview is not rotated
2. device rotation unlocked: When rotating device, camera preview is rotated

| device rotation locked | device rotation unlocked |
| --------------- | --------------- |
<video src="https://github.com/flutter/flutter/assets/104349824/f3292a1d-0bd8-4f26-a7ed-0f485295c3be"/> | <video src="https://github.com/flutter/flutter/assets/104349824/4ad3d276-be5c-4f96-8194-3b2910614fec"/>

To make sure we are understanding the issue correctly, could you confirm that the result on your device are different from my first case above? (It means the camera preview is rotated when rotating your device) 

It will be more clear if there is a recorded video from your side. Thank you!

**Comment by olintosynergy** [comment]
Exactly, what happens to me is the result shown in your second video, where I unlock the screen rotation via the OS, but within the App I leave it locked, the camera rotation still happens. 

The result I expected would be the result in the first video: Rotation locked, and the camera is not rotated. 

Thanks.

**Comment by huycozy** [comment]
Thank you for making this clearer. I understand now after comparing results between iOS and Android. I also compared Flutter app with iPhone device's camera app and saw the issue you reported. 

However, this is a known issue being tracked at https://github.com/flutter/flutter/issues/111063. So I will close this issue in favor of that one, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
