### ISSUE TITLE
Auto replace character '+' to whitespace when convert base64string 

### ISSUE THREAD

**Issue by muonroi** [flutter/flutter#136018]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

When convert json base64 to object, character '+' will change to ' '. 

### Expected results

`wNYmO41/48SHNstaLVXxHCCre29BZQl1NhC6NM3R3rzpXtPQxVzH6jEzA/QhXFN5tu6Fk7pO53uppm1mVXMZgxbyRVz26dnepi/FyB6axBY+6gq1GL+uRQgoiFUCjRN2p8w6LevViwKlHyWZZJZO1DGVSjAi1m2U+og9pkHw9/QPCJqMV1jD/ebaerIAQkko1ztcqERrivKabxBpGucE4RipqyTXjTZ2pfrRc9TGDjFwMBU4j2QVAcltWDU79ctUqCCdAeZELVz2ZntLsHsYbf6itnwtcwa7FJZCK+1/Dq2d7vHAWO9THfRLjsY1v4gkiUdH3ilA7AeLNabpMPBxhbFuKFzPf9ZfJQ/UxW44I0ipudmIcollyY4c0RJu58THBs6e8bEgW/t/kLLoRy4DUoyx3naYjznNpgXOyK7nr5xj58KsGo13I0Hu1RLpSgwqUcgj+VAja9ULUmCbiJiCedQUuPF7g5WCbdgi7CPNOZddutpeKn/5+ijj+Md6mWQwvzkTVOcZaAUaPXOVNt0BqHV7fwXQ7g0npQU/1SPXshAmh9Pyb8M+GWCwZC+VKxKGrNLEeUSqikz3eugb1vRZnbspUU+0Sl/RWB5zRfW8C500hoqK5B0lcTOZytIUti/dC7ema+X7u//3loglAKE3XMvCTgn7HuWlgSsoDkdxFvM90udtRc+L5EjYvi00LcF2yo8kkoM+MzicFqWqlWGutbxib3eYkhIfG3nCc0Y2a56fn4h+v2qQa1ukkBzXhL52PA4280QcRwZ1W2ttfvaTZot1vjGeJTqtLzm2gWuGOweDtw3F/GLNUs8Y4aH/PNh6YUlf1DQMXZU+ueaQvke+p7pbvd4v8x3YX6ClGYMAtWHZRtEid7xKU9nO3v6HHUAkRZ/mHQCFZnljT6A69JgZAaUTD1Re54c2ApD/gMXe5gDhjPCGRtusED2unrldUKyAzqKH15kxxzvJeK8An03sni0IJtkzjxCIITb3bjqM3G7+SaHrsthWkxBZMvj2odZmkc7KWMk9D4zDqwenv/mFICbRjjE5gV6Om7F9wwLukLNrI2KfRnmqbHZFMHWrSE3UuD+mUjAdQ2Mx2FXtbw457jK8zCb9TTZCP3N7aLDmjko/ATE6uir/2Hl1HTntHLpuMqwKW3WHjdD6mHv4XcCMnBdfaNU2Y96tzGibEgIU/1XwMqADpuyMml2oA0k7AL+qFNSOVElud9YhzkvQ/VxY7tZuorIir+a3Da7cVlWmib4IVnzviHIoq4NscwBFqCfiiltMDeDZQ+PMtyH8jRvD7/0vC27xd7vjR2TX2/Wl00kqBPf2nJA2M/keR2KQ2GyTuDtHF4U840T71rhNN07Ul1AApoWbfM2cuOgS8470paGaKJER3k3A/foHnjQA9fgtP/rDXYnuapFpxycVetSDNCCW43y2AxTu4R6evM3xfikTzLyfEdqYkOU7UWKCpXZmquAHxqHhCVGZdx+D4qPQ74yRYxnPkOzZcF6WRnDk2F9NTnoItz7azjQbyVH8k5UvzqmlrnKEu351rpBpl9tK1W9TGpwrek3R4hojaHDIBFEtaqYoshPENi+QYKEWxQk5Q/QXZ1hCEKlWEDW7OXSogICcmo3Fsfe5aPt+vdj+iNyFjg3asyXmwOfx4RmLUXPHBdk6x6iBqzQk2OYDpW5oAsrOo6uDLdlb/mIxafZaCBfCaHAtXcsPeGigGihl/KIDjIXDxejoRP9mxF9fn/e/yQUDsZlAWjN/Y458TdoY31Dr3ZqHKPvrH9nozjk+TyNne7e//SIIQtcq9u+gGArMDQ==`

### Actual results

`wNYmO41/48SHNstaLVXxHCCre29BZQl1NhC6NM3R3rzpXtPQxVzH6jEzA/QhXFN5tu6Fk7pO53uppm1mVXMZgxbyRVz26dnepi/FyB6axBY 6gq1GL uRQgoiFUCjRN2p8w6LevViwKlHyWZZJZO1DGVSjAi1m2U og9pkHw9/QPCJqMV1jD/ebaerIAQkko1ztcqERrivKabxBpGucE4RipqyTXjTZ2pfrRc9TGDjFwMBU4j2QVAcltWDU79ctUqCCdAeZELVz2ZntLsHsYbf6itnwtcwa7FJZCK 1/Dq2d7vHAWO9THfRLjsY1v4gkiUdH3ilA7AeLNabpMPBxhbFuKFzPf9ZfJQ/UxW44I0ipudmIcollyY4c0RJu58THBs6e8bEgW/t/kLLoRy4DUoyx3naYjznNpgXOyK7nr5xj58KsGo13I0Hu1RLpSgwqUcgj VAja9ULUmCbiJiCedQUuPF7g5WCbdgi7CPNOZddutpeKn/5 ijj Md6mWQwvzkTVOcZaAUaPXOVNt0BqHV7fwXQ7g0npQU/1SPXshAmh9Pyb8M GWCwZC VKxKGrNLEeUSqikz3eugb1vRZnbspUU 0Sl/RWB5zRfW8C500hoqK5B0lcTOZytIUti/dC7ema X7u//3loglAKE3XMvCTgn7HuWlgSsoDkdxFvM90udtRc L5EjYvi00LcF2yo8kkoM MzicFqWqlWGutbxib3eYkhIfG3nCc0Y2a56fn4h v2qQa1ukkBzXhL52PA4280QcRwZ1W2ttfvaTZot1vjGeJTqtLzm2gWuGOweDtw3F/GLNUs8Y4aH/PNh6YUlf1DQMXZU ueaQvke p7pbvd4v8x3YX6ClGYMAtWHZRtEid7xKU9nO3v6HHUAkRZ/mHQCFZnljT6A69JgZAaUTD1Re54c2ApD/gMXe5gDhjPCGRtusED2unrldUKyAzqKH15kxxzvJeK8An03snsX1o9Otv5XqHdi5hb5V5kZ/yh88QRut9Ym8CNXRm0xE6BLNIEuPcR1Dm0AU4tvA2937iLGNm5tKWfKNZSicL9JxgkvrHbVnFt1puqIYG/QLa o8Rg 7H1NelOZCXW0pMg1OZ2MZdO8NuXsGCYZYU84QPWRchYavvsnrl/fuqSKZuUqbechzHJSaRAueJM9WTnYpFhk3HlOIbYr9Hu1OC1qVWxY142TuXAcI5Nq8MrB0Z1bNBpXFtFONJWQJtAWCusOE sz7Qer8EHN0rjP1WhNq3U3BIx aiVOP198oWVts3FVtPMkJ0M9CoSxEknsenW42Pqr55v4wzsgDNs 5lQe8g/HSTEQjRAG7QVZlWPrbKkeHkALF6iAW0MRZwq5QTFKEE3W/bcV5/n85kumNSDGeNTK2UDUD9exOboH8youXGjn5eCVF8NFfVMpt6JR8TtwmTRI/NiFKP8U5cB0GJx4QmIWyPTTdehOHvcvJ0a8unaJNnPSMq1rL8BIcfIZr0qn1wX7spcNyeNp7VygahPVw0rukqqXsdC8gyUy3F8ayufhMroqNYpLTxFE6GEjs5/A/SlKolBWoGAqRwlqxVReaS55d36QyvholB SeYPaqQgdCdFaA8agp3mavVgW28YY/d4kqSBrTpvM99rymgM0m2dRKTq9T4Bwg ynGzIHaYJ4wIhNfHfJBEini8u7geCg8aPHfUFRhDVq/ryTFsk9GdIym9/tip9CYMoKY9 ps4y3OvEKvkg6ajz4GnTuMIpdE4CLHAuUBY33gOrnkAV7MJIb6T1KicWf6I6zhVowuIDj//AlEnT2M6JU0uWMqQA==` 

### Code sample

<details><summary>Code sample</summary>

```dart
class AuthenticateResult {
  String accessToken;
  String encryptedAccessToken;
  int expireInSeconds;
  bool shouldResetPassword;
  dynamic passwordResetCode;
  int tenantId;
  int userId;
  bool requiresTwoFactorVerification;
  dynamic twoFactorAuthProviders;
  dynamic twoFactorRememberClientToken;
  dynamic returnUrl;
  String refreshToken;
  int refreshTokenExpireInSeconds;
  dynamic c;
  String metabaseSessionTokenForSystem;
  String metabaseSessionTokenForCookie;

  AuthenticateResult({
    required this.accessToken,
    required this.encryptedAccessToken,
    required this.expireInSeconds,
    required this.shouldResetPassword,
    required this.passwordResetCode,
    required this.tenantId,
    required this.userId,
    required this.requiresTwoFactorVerification,
    required this.twoFactorAuthProviders,
    required this.twoFactorRememberClientToken,
    required this.returnUrl,
    required this.refreshToken,
    required this.refreshTokenExpireInSeconds,
    required this.c,
    required this.metabaseSessionTokenForSystem,
    required this.metabaseSessionTokenForCookie,
  });

  factory AuthenticateResult.fromJson(Map<String, dynamic> json) =>
      AuthenticateResult(
        accessToken: json["accessToken"],
        encryptedAccessToken: json["encryptedAccessToken"].toString(),
        expireInSeconds: json["expireInSeconds"],
        shouldResetPassword: json["shouldResetPassword"],
        passwordResetCode: json["passwordResetCode"],
        tenantId: json["tenantId"],
        userId: json["userId"],
        requiresTwoFactorVerification: json["requiresTwoFactorVerification"],
        twoFactorAuthProviders: json["twoFactorAuthProviders"],
        twoFactorRememberClientToken: json["twoFactorRememberClientToken"],
        returnUrl: json["returnUrl"],
        refreshToken: json["refreshToken"],
        refreshTokenExpireInSeconds: json["refreshTokenExpireInSeconds"],
        c: json["c"],
        metabaseSessionTokenForSystem: json["metabaseSessionTokenForSystem"],
        metabaseSessionTokenForCookie: json["metabaseSessionTokenForCookie"],
      );

  Map<String, dynamic> toJson() => {
        "accessToken": accessToken,
        "encryptedAccessToken": encryptedAccessToken,
        "expireInSeconds": expireInSeconds,
        "shouldResetPassword": shouldResetPassword,
        "passwordResetCode": passwordResetCode,
        "tenantId": tenantId,
        "userId": userId,
        "requiresTwoFactorVerification": requiresTwoFactorVerification,
        "twoFactorAuthProviders": twoFactorAuthProviders,
        "twoFactorRememberClientToken": twoFactorRememberClientToken,
        "returnUrl": returnUrl,
        "refreshToken": refreshToken,
        "refreshTokenExpireInSeconds": refreshTokenExpireInSeconds,
        "c": c,
        "metabaseSessionTokenForSystem": metabaseSessionTokenForSystem,
        "metabaseSessionTokenForCookie": metabaseSessionTokenForCookie,
      };
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[[Video bug here]
](https://drive.google.com/file/d/1ZfyntglEVp_v5gal9pqVzk3WrVRwivxX/view?usp=sharing)

https://github.com/flutter/flutter/assets/53122008/1b3580bb-7827-41d5-acd3-f35dbbc88579

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console

flutter doctor -v: 
`[√] Flutter (Channel stable, 3.13.2, on Microsoft Windows [Version 10.0.22621.2283], locale en-US)
    • Flutter version 3.13.2 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (6 weeks ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\muonroi\AppData\Local\Android\Sdk
    • Platform android-33-ext5, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Enterprise 2022 17.6.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Enterprise
    • Visual Studio Enterprise 2022 version 17.6.33829.357
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] VS Code (version 1.82.3)
    • VS Code at C:\Users\muonroi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.74.0

[√] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.2283]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 117.0.5938.132
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 117.0.2045.47

[√] Network resources
    • All expected network resources are available.

• No issues found!````

</details>

**Comment by dam-ease** [comment]
Hi @muonroi. Thanks for filing this. Can you help with more information on this issue.

- Are you trying to do any string conversion here? From the explanation, you seem to be describing a case of an auto replacement
- Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code? This would help us in reproducing and providing more information on this.
- I see you are on an older version of flutter as well, can you upgrade to the latest versions to verify you still experience the issue as well.

Thank you!

**Comment by muonroi** [comment]
Hi everyone! I solved issue when update flutter to new version.
