### ISSUE TITLE
Bug in flutterweb when preventing to use cached website when uploading new version 

### ISSUE THREAD

**Issue by eliudio** [flutter/flutter#136072]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. flutter build web --web-renderer html --release --no-tree-shake-icons
2. firebase login
3. firebase deploy
4. open your website

### Expected results

new version of your website is loaded 

### Actual results

new version of your website is loaded 

HOWEVER. It seems the issue is with "--web-renderer html" . When using these steps then the actual results are that the new version of your website are loaded

1. flutter build web --release --no-tree-shake-icons
2. firebase login
3. firebase deploy
4. open your website

### Code sample

<details><summary>Code sample</summary>

```dart
1. flutter build web --web-renderer html --release --no-tree-shake-icons
2. firebase login
3. firebase deploy
4. open your website
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
No logs
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.0, on Microsoft Windows [Version 10.0.22621.2283], locale en-GB)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.1)
[√] Android Studio (version 2021.3)
[√] IntelliJ IDEA Community Edition (version 2019.2)
[√] VS Code (version 1.83.0)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @eliudio 

>HOWEVER. It seems the issue is with "--web-renderer html" . When using these steps then the actual results are that the new version of your website are loaded

Is that a typing mistake in the actual result? Should it be: "...new version of your website are **not** loaded"? If so, please update the issue description.

Also, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the issue. With the little information above, it is not easy for us to verify it. Thank you!
