### ISSUE TITLE
Need a way to disable malioc diff testing for shader + GPU combinations that aren't supported

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#136080]
For https://github.com/flutter/engine/pull/46585 

Malioc diff does not support analyzing shaders that use gl_LastFragData (framebuffer fetch) on GPUs which did not support it. Previously we turned this off by setting the target GL version to something high enough that malioc diff wouldn't run, but we can't do that anymore if we're going to actually use the shaders on OpenGL.

See https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8768070639964688369/+/u/build_android_debug_unopt_flutter_impeller_flutter_shell_platform_android:android_jar_flutter_shell_platform_android:robolectric_tests/stdout

**Comment by jonahwilliams** [comment]
FYI @zanderso

**Comment by zanderso** [comment]
Can you use the parameter here? https://github.com/flutter/engine/blob/main/impeller/tools/impeller.gni#L671.

**Comment by jonahwilliams** [comment]
Ahh thats nice, that will unblock me!
