### ISSUE TITLE
Flutter Web: StreamedRequest is a lie

### ISSUE THREAD

**Issue by jezell** [flutter/flutter#136055]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Try to upload a large file using http.StreamedRequest with Flutter web (try 4GB). You'll always get an error:

The browser implementation of StreamedRequest always reads the entire request and response into memory. This doesn't have to happen as browsers have supported streaming via fetch for a very long time and makes flutter web totally broken if you need to deal with large files such as video, as this will cause the browser to complain that it can't allocate buffers that large: "RangeError: Array buffer allocation failed"

https://github.com/dart-lang/http/blob/master/pkgs/http/lib/src/browser_client.dart

StreamedRequest/StreamedResponse should be updated to use streaming fetch requests, as the current implementation defeats the point of why you would be using the streamed APIs in the first place. As of the moment, there's no way to upload large files to an S3 / Google cloud storage presigned url without throwing away the http package entirely on web.

### Expected results

To not fail

### Actual results

Failure

### Code sample

<details><summary>Current implementation, easy to see the problem here:</summary>

```dart
  Future<StreamedResponse> send(BaseRequest request) async {
    if (_isClosed) {
      throw ClientException(
          'HTTP request failed. Client is already closed.', request.url);
    }
    var bytes = await request.finalize().toBytes();
    var xhr = HttpRequest();
    _xhrs.add(xhr);
    xhr
      ..open(request.method, '${request.url}', async: true)
      ..responseType = 'arraybuffer'
      ..withCredentials = withCredentials;
    request.headers.forEach(xhr.setRequestHeader);

    var completer = Completer<StreamedResponse>();

    unawaited(xhr.onLoad.first.then((_) {
      if (xhr.responseHeaders['content-length'] case final contentLengthHeader?
          when !_digitRegex.hasMatch(contentLengthHeader)) {
        completer.completeError(ClientException(
          'Invalid content-length header [$contentLengthHeader].',
          request.url,
        ));
        return;
      }
      var body = (xhr.response as ByteBuffer).asUint8List();
      completer.complete(StreamedResponse(
          ByteStream.fromBytes(body), xhr.status!,
          contentLength: body.length,
          request: request,
          headers: xhr.responseHeaders,
          reasonPhrase: xhr.statusText));
    }));

    unawaited(xhr.onError.first.then((_) {
      // Unfortunately, the underlying XMLHttpRequest API doesn't expose any
      // specific information about the error itself.
      completer.completeError(
          ClientException('XMLHttpRequest error.', request.url),
          StackTrace.current);
    }));

    xhr.send(bytes);

    try {
      return await completer.future;
    } finally {
      _xhrs.remove(xhr);
    }
  }
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Hi @jezell 
As I can see, this is best suited in `dart-lang/http` repository. You can check a similar issue at https://github.com/dart-lang/http/issues/854 or file a new issue for better support there.

Closing, as this isn't an issue with Flutter framework itself.
