### ISSUE TITLE
`flutter dart foo.dart` to run `dart foo.dart` with FLUTTER_ROOT set

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#13607]
Required to run things like `source_gen` generators.

https://github.com/flutter/flutter/issues/13360 deals with `pub run`. This is just getting access to the `dart` command to run things not in the `bin` directory.

Here's the draft text I've included in `json_serializable` – which is pretty gnarly.

---

*NOTE*: If you're using Flutter, running a Dart script is a bit tricky. You can
find the Dart entry point at `$FLUTTER_ROOT/bin/cache/dart-sdk/bin/dart`.
You can determine `FLUTTER_ROOT` by looking at the first few lines of
`flutter doctor`.

```console
> flutter doctor
[✓] Flutter (on Mac OS X 10.12.6 16G1114, locale en-US, channel master)
    • Flutter at YOUR_FLUTTER_ROOT_HERE
    • Framework revision 235b64ed2f (13 hours ago), 2017-12-14 20:38:39 -0800
...
```

**Comment by kevmoo** [comment]
CC @sethladd @mit-mit

**Comment by sethladd** [comment]
Strawman: `flutter cmd <path_to_cli_script>` which simply runs the script via the same Dart version that is used in the engine (so the API in docs.flutter.io applies to scripts run via the Flutter cmd line. I don't want "two darts" for Flutter developers, there is one Dart for Flutter developers: the Dart that is documented on docs.flutter.io)

In the meantime, could source_gen ship a generic runner accessible from `pub run` ?

**Comment by kevmoo** [comment]
> Strawman: `flutter cmd <path_to_cli_script> `

SGTM...

> In the meantime, could source_gen ship a generic runner accessible from pub run ?

Sadly, no. We're working on a solution w/ pkg/build where there will be a common entry point. Hoping to have that nailed down in Q1.

**Comment by mit-mit** [comment]
Would a more idea solution be some way to register (maybe in `pubspec.yaml`, that flutter should execute some dart "script" during build? Then you wouldn't need to remember to manually run the generators?

**Comment by kevmoo** [comment]
That'd be good, too... We'd want to start talking about a real design at
that point...

**Comment by zoechi** [comment]
`flutter packages pub run tool/build.dart` does this currently.

**Comment by jonahwilliams** [comment]
Closing as pub can run dart scripts, and because we'll likely use a different solution for build_runner integration.

**Comment by mit-mit** [comment]
Also, note that I recently added passthrough for all `pub` commands, so the current shortest way of doing this is:

```
flutter pub run tool/build.dart
```
