### ISSUE TITLE
[go_router] programatically update routing table

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#136005]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

When coverting Devtool to use go_router, some of the route is dynamically loaded, e.g. extensions.

go_router should provide a way to dynamically updates the routing table.

### Proposal

An API to update routing table after GoRouter is created.

**Comment by pavanpodila** [comment]
This is great and I was looking for this. When can we expect this to land ?
