### ISSUE TITLE
Error after add firebase_messaging plugin

### ISSUE THREAD

**Issue by romaluca** [flutter/flutter#13603]
I'm using google_sign_in in my app. It works well
I wanted add notification to my app, and so i followed the Android integration like explained here:
[https://github.com/flutter/plugins/tree/master/packages/firebase_messaging](https://github.com/flutter/plugins/tree/master/packages/firebase_messaging)

If i try to build the app i receive this error:

* What went wrong:
```
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/firebase/iid/zzb;

```

**Comment by chiragshenoy** [comment]
How did you resolve this issue ?
