### ISSUE TITLE
The radius of inkwell cannot be set through theme configuration

### ISSUE THREAD

**Issue by laterdayi** [flutter/flutter#136174]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

```
 theme.copyWith(
      inputDecorationTheme: theme.inputDecorationTheme.copyWith(
        isDense: true,
        contentPadding: const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
      ),
..... 
inkwellTheme......
```

### Expected results

The radius of inkweel cannot be set through theme configuration

### Actual results

The radius of inkweel cannot be set through theme configuration

### Code sample

The radius of inkweel cannot be set through theme configuration

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

The radius of inkweel cannot be set through theme configuration

### Flutter Doctor output

The style of inkweel cannot be set through theme configuration

**Comment by dam-ease** [comment]
Hi @laterdayi. Thanks for filing this. I can see this as well but this seems to me to be more of a proposal than an actual issue, are you able to file a separate proposal for this? This would make it more readable and easier to track.
