### ISSUE TITLE
Support deferred components on desktop platform(MacOS/Windows/Linux)

### ISSUE THREAD

**Issue by xuzhongpeng** [flutter/flutter#136113]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case
1. On the desktop side, we want to achieve code dynamic based on different interfaces which rely on the implementation of deferred components, so we can only globally update app. so, we cannot only update a certain part.
2. We have two different flutter process and two `app.so` in one application. We want use deferred components to reduce app size by sharing the same compiled file(`flutter framework` compile separately)

Related:
- https://github.com/flutter/flutter/issues/79327. 

### Proposal
Deferred components was implemented for Android in https://github.com/flutter/flutter/issues/57617. We should support similar functionality on desktop(MacOS/Windows/Linux).

1. Provider APIs like `LoadDartDeferredLibrary` and `LoadDartDeferredLibraryError` and `RequestDartDeferredLibrary` on `embedder.h`
3. Support platform code in shell/platform/(darwin|windows|linux)
4. Add build tools params to build part aot files.

**Comment by xuzhongpeng** [comment]
I just saw the same [issue](https://github.com/flutter/flutter/issues/131202), but I don't think the response from that issue has solved my problem. The implementation of delayed components does not require code push capabilities. We only need to provide relevant APIs, and code push can be implemented by users themselves.

**Comment by stuartmorgan** [comment]
> ### Use case
> Deferred components was implemented for Android in #57617. We should support similar functionality on desktop(MacOS/Windows/Linux).

This isn't a use case; a use case would be a problem you are trying to solve, not a suggested solution. What is the use case you are trying to support?

> We only need to provide relevant APIs, and code push can be implemented by users themselves.

As it says in the issue referenced, this is not correct. Implementing deferred components does not allow code push updates. They are unrelated functionality.

**Comment by xuzhongpeng** [comment]
> This isn't a use case; a use case would be a problem you are trying to solve, not a suggested solution. What is the use case you are trying to support?

Thanks for your reply. I have edited the above content again.

> As it says in the issue referenced, this is not correct. Implementing deferred components does not allow code push updates. They are unrelated functionality.

Yes. I don't want to implement code push in this issue.

**Comment by loic-sharma** [comment]
> Yes. I don't want to implement code push in this issue.

FYI, deferred components is **not** a step towards code push. Deferred components must be from the compilation; you cannot "swap out" components with updated code that was compiled separately.

I'm curious to your desktop use case. Deferred components are useful to circumvent mobile limitations such as poor internet connection or limited disk space. These are generally less of a concern for desktop apps. Could you expand on your scenario?

**Comment by xuzhongpeng** [comment]
Thanks. Maybe I misunderstood the meaning of deferred components. 

Close
