### ISSUE TITLE
flutter\packages\flutter_tools\gradle\src\main\groovy\flutter.groovy' line: 482,  Cannot run Project.afterEvaluate(Closure) when the project is already evaluated.

### ISSUE THREAD

**Issue by RuberDucky** [flutter/flutter#136180]
```
Launching lib\main.dart on LE2117 in debug mode...
main.dart:1

FAILURE: Build failed with an exception.

* Where:
Script 'E:\android studio\new flutter\flutter 3\flutter\packages\flutter_tools\gradle\src\main\groovy\flutter.groovy' line: 482

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Cannot run Project.afterEvaluate(Closure) when the project is already evaluated.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15m 54s
Exception: Gradle task assembleDebug failed with exit code 1

```
i also did this: 
flutter channel stable
flutter upgrade --force
flutter pub cache repair
cd <YOUR APP FOLDER>
flutter clean

here is flutter doctor -v  

[√] Flutter (Channel stable, 3.13.6, on Microsoft Windows [Version 10.0.19044.3086], locale en-US)
    • Flutter version 3.13.6 on channel stable at E:\android studio\new flutter\flutter 3\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (12 days ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at E:\android studio\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: E:\android studio\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2022 17.5.3)
    • Visual Studio at F:\VS C++\BuildTools
    • Visual Studio Build Tools 2022 version 17.5.33516.290
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2021.3)
    • Android Studio at E:\android studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] Android Studio (version 2022.2)
    • Android Studio at E:\android studio\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694) 

[√] Connected device (4 available)
    • LE2117 (mobile)   • 192.168.1.5:5555 • android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19044.3086]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 117.0.5938.134
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 116.0.1938.62

[√] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by harryhritik12** [comment]
Try to do this 
Check Flutter and Dart Versions: Ensure that your Flutter and Dart versions are compatible with each other. 
Run flutter --version to check your Flutter version and make sure your project's pubspec.yaml specifies a compatible Dart SDK version.
run another app with same file .
recheck path .

**Comment by RuberDucky** [comment]
flutter --version:

Flutter 3.13.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ead455963c (12 days ago) • 2023-09-26 18:28:17 -0700
Engine • revision a794cf2681
Tools • Dart 3.1.3 • DevTools 2.25.0


here is Pubspec.yaml file Data regarding SDK:


version: 1.0.0+2
environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

**Comment by darshankawar** [comment]
@RuberDucky 
It is not clear without providing relevant details as to why the error you are reporting could be occuring. It could be related to your configuration or any third party SdK you might be using in your gradle configuration. You can check the `classpath` you are using and see if they might be causing the error or not.

Also, I suggest you to ask such questions on support channels like StackOverflow for solutions. Closing from here. If you disagree or have a concrete way to replicate the error reported, write in comments by providing all required details and I'll reopen it.

**Comment by RuberDucky** [comment]
app/build.gradle: 

apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

buildscript {
    repositories {
        google()
        mavenCentral()
        jcenter()
        maven { url 'https://plugins.gradle.org/m2/' }
    }
    dependencies {
        // OneSignal-Gradle-Plugin
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.14.0, 0.99.99]'
    }
}



def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
   keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}
android {
    compileSdkVersion 33
    // ndkVersion 23

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
        disable "Instantiatable"
        checkReleaseBuilds false
        abortOnError false
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.yuloapp.apps"
        minSdkVersion 24
        targetSdkVersion 33
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now,
            // so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }

}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.google.firebase:firebase-messaging:21.0.0'
    implementation 'com.google.android.exoplayer:exoplayer:2.17.0'
    implementation 'com.google.firebase:firebase-analytics-ktx'
    implementation 'com.google.firebase:firebase-dynamic-links-ktx'
    implementation 'com.onesignal:OneSignal:[0.14.0, 0.99.99]'
    implementation platform('com.google.firebase:firebase-bom:32.1.1')
}
apply plugin: 'com.google.gms.google-services'



android/build.gradle

buildscript {
    ext.kotlin_version = '1.6.21'
    repositories {
        google()
        mavenCentral()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.15'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
ext.flutterFFmpegPackage = 'min-gpl-lts'  




gradle-wrapper.properties file: 


#Fri Jun 23 08:50:38 CEST 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-all.zip

**Comment by ducnmhn** [comment]
@RuberDucky  any update for fix this bug

**Comment by RuberDucky** [comment]
yes roll back my flutter version to 3.7 and the main problem was because of the one signal, when this plugin added after reading the documentation: *apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin* i pasted this in wrong place the correct place is right down these plug-ins

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle" 


apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'



then it will  solved

**Comment by darshankawar** [comment]
This could be occuring to due to third party sdk you are using `apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'`.

**Comment by RuberDucky** [comment]
Yes you are right. Now issue resolved
