### ISSUE TITLE
In iOS 12 versions, the application runs in debug mode but doesn't work in release mode.

### ISSUE THREAD

**Issue by Berkant35** [flutter/flutter#136194]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.4, on macOS 13.4.1 22F770820d darwin-arm64, locale en-TR)
I think you could run --profile any real device

### Expected results

To be able to run the application in release mode on iOS 12 versions as well

### Actual results

While IOS 12 versions can run flawlessly on debug mode, the release mode application crashes directly after a certain period of time from the splash screen. I do not encounter such a problem in other IOS versions.

### Code sample

In other words, since the problem does not occur on a code I have written, you may not find the environment to perform this action through the codes I have specified to you. But maybe on an ios 12 version device and "[✓] Flutter (Channel stable, 3.13.4, on macOS 13.4.1 22F770820d darwin-arm64, locale en-TR)
" you can try flutter run --profile in the following versions, maybe it will cause you to have this problem

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter run --profile

## exception

String: failed to connect to http://127.0.0.1:49212/VGS2WujR4XE=/

```
#0      DartDevelopmentServiceImpl.startService (package:dds/src/dds_impl.dart:136:7)
<asynchronous suspension>
#1      DartDevelopmentService.startDartDevelopmentService (package:dds/dds.dart:97:5)
<asynchronous suspension>
#2      DartDevelopmentService.startDartDevelopmentService (package:flutter_tools/src/base/dds.dart:55:22)
<asynchronous suspension>
#3      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:298:11)
<asynchronous suspension>
```

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.4, on macOS 13.4.1 22F770820d darwin-arm64, locale en-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Android Studio (version 2022.2)
[✓] Android Studio (version 2022.3)
[!] Android Studio (version unknown)
    ✗ Unable to determine Android Studio version.
[✓] IntelliJ IDEA Community Edition (version 2022.2.4)
[✓] IntelliJ IDEA Community Edition (version 2023.2)
[✓] VS Code (version 1.82.2)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 categ
```

</details>

**Comment by darshankawar** [comment]
> I have iPhone 6+ device running on OS 12 version on which I'll try to replicate the reported behavior. I have just put it on charge so it'll take some time before it is up and running and will see if it is compatible with my setup

So I was able to run sample app on OS 12.4 version using latest stable version (3.13.6) in profile and release mode using XCode and the app compiled and ran properly without throwing the reported error. The XCode console log is as below:

```
2023-10-10 15:35:49.301691+0530 Runner[859:29025] [DYMTLInitPlatform] platform initialization successful
2023-10-10 15:35:49.587907+0530 Runner[859:28754] Metal GPU Frame Capture Enabled
2023-10-10 15:35:49.589386+0530 Runner[859:28754] Metal API Validation Enabled
2023-10-10 15:35:49.947002+0530 Runner[859:28754] Warning: Unable to create restoration in progress marker file
2023-10-10 15:35:50.266385+0530 Runner[859:29083] flutter: The Dart VM service is listening on http://127.0.0.1:50113/o03w53tJ8fo=/
```

@Berkant35 If you can share a runnable code sample that leads to the error, that'll help to properly investigate further.

**Comment by Berkant35** [comment]
@darshankawar hi,

Thanks for response and i m sorry for late response.

#11846 this issue same with my problem i will continue with it. 

Thank you again.
