### ISSUE TITLE
Uncategorized (Xcode): Command CodeSign failed with a nonzero exit code

### ISSUE THREAD

**Issue by xonaman** [flutter/flutter#136131]
### Is there an existing issue for this?

- [x] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

`flutter run --verbose` (iOS device)

This issue happens on a project that has worked completely fine before and nothing was changed before the error occurred. I may have updated my system, Xcode, flutter or all (I don't remember correctly).

### Actual results

```console
[   +1 ms] Uncategorized (Xcode): Command CodeSign failed with a nonzero exit code

[   +1 ms] Could not build the application for the simulator.
[        ] Error launching application on iPhone 15 Pro Max.
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:760:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
```

### Terminal Logs

[logs.txt](https://github.com/flutter/flutter/files/12838337/logs.txt)

### Xcode Logs

[Build Runner_2023-10-07T18-54-57.txt](https://github.com/flutter/flutter/files/12838373/Build.Runner_2023-10-07T18-54-57.txt)

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.6, on macOS 14.0 23A344 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.82.2)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!


```

</details>

**Comment by xonaman** [comment]
When running `flutter build ipa --release --verbose`, I also encounter an error, maybe these two are interconnected:

```console
[ +132 ms] Error (Xcode): [+36452 ms] Unhandled exception:

[   +1 ms] Encountered error while archiving for device.
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:665:7)
           <asynchronous suspension>
           #2      BuildIOSArchiveCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:417:50)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
```

Complete output: [logs.txt](https://github.com/flutter/flutter/files/12838359/logs.txt)

**Comment by szucsyf** [comment]
I'm facing the same issue.

**Comment by mesterbence** [comment]
I have the same on M1 Macbook

**Comment by huycozy** [comment]
@xonaman From your output logs file:

>resource fork, Finder information, or similar detritus not allowed
            Command CodeSign failed with a nonzero exit code

It looks like you are hitting https://github.com/flutter/flutter/issues/123583 and https://github.com/flutter/flutter/issues/130639. I would suggest you to follow up on these issues for updates. Closing this as a duplicate.

@Feusy @mesterbence Please also check linked issues as well. If your issue is difference, please file a new one.

**Comment by xonaman** [comment]
@huycozy Thank you very much!

**Comment by projectalpha-spaceserve** [comment]
Pls, I am having the same error after upgrading from XCode 14 to 15 and MacOS Ventura to MacOS Sonoma.

Launching lib/main.dart on iPhone SE (3rd generation) in debug mode...
main.dart:1
Xcode build done.                                           28.0s
Failed to build iOS app
Uncategorized (Xcode): Command CodeSign failed with a nonzero exit code

Could not build the application for the simulator.
Error launching application on iPhone SE (3rd generation).

**Comment by mesterbence** [comment]
My solution was moving project dir to a folder which is not synchronized with iCloud. Try it! :)

**Comment by Lanysc** [comment]
> My solution was moving project dir to a folder which is not synchronized with iCloud. Try it! :)

Thank you so much :D

**Comment by LReinacher** [comment]
> My solution was moving project dir to a folder which is not synchronized with iCloud. Try it! :)

This is the only solution that worked for me, even though I had the project already in a folder suffixed with ".nosync"  which worked previously and up until the upgrade to MacOS Sonoma.

**Comment by carlosfarfangalindoNL222** [comment]
> My solution was moving project dir to a folder which is not synchronized with iCloud. Try it! :)

You just fucking solved the problem that I am having for 2 years. Now I don't have to open xcode anymore every single time. 

THANK YOU!

**Comment by th38amorim** [comment]
> My solution was moving project dir to a folder which is not synchronized with iCloud. Try it! :)

Omg... It worked for me. Ty. Saved my week

**Comment by nguyenminhtai123** [comment]
> My solution was moving project dir to a folder which is not synchronized with iCloud. Try it! :)

OMG, it works for me, very grateful !!!

**Comment by YusifAghasalamli** [comment]
> My solution was moving project dir to a folder which is not synchronized with iCloud. Try it! :)

Also, worked for me.

**Comment by annabohac** [comment]
Worked for me too! Thanks so much!

**Comment by yusufelyldrm** [comment]
> My solution was moving project dir to a folder which is not synchronized with iCloud. Try it! :)

This saved me too, Thank you man

**Comment by AdrianBakalarz** [comment]
I also have to thank you, cause no one know, where problem was until I found this solution :D

**Comment by ChengyanOo** [comment]
> My solution was moving project dir to a folder which is not synchronized with iCloud. Try it! :)

First of all! This works for me too! 

I wanna share with yall my **system config** just FYI, I'm using macOS 14.0, Xcode Version 15.0.1, Flutter 3.16.0, and Dart 3.2.0 • DevTools 2.28.2.

The solution still seems a bit confusing and sorta magical for me, I had to give it a minute a two and reopen Xcode, IDE, new shell, ran "flutter clean" before running it again. Not too sure which actually worked

**Comment by useynyav** [comment]
> My solution was moving project dir to a folder which is not synchronized with iCloud. Try it! :)

That's a perfect solution, I have tried that and it is working right, Thank you so muchh
