### ISSUE TITLE
[Android] [in_app_purchase] _inAppPurchase.queryProductDetails always response empty products why?

### ISSUE THREAD

**Issue by Jonili1989** [flutter/flutter#136191]
My app already publish a alpha channel version and official version. but my app always query any products, it's always empty.
I'm sure my in-app product all activated。

I tired use in_app_purchase example replace my app package id, but the result is the same

Why can help me? thanks 

The in_app_purchase version:
in_app_purchase: 3.1.5

Flutter version: 3.10.6

**Comment by dam-ease** [comment]
Hi @Jonili1989. I see you are on an older version of Flutter, can you upgrade to the latest version of flutter to confirm you still experience this issue?

**Comment by Jonili1989** [comment]
My release app in Google play store version is 1.0.2+3; but the alpha version in PDC is 1.05+6
![image](https://github.com/flutter/flutter/assets/23514357/bdefe0df-9631-45d6-9c68-fe343620d22e)

**Comment by dam-ease** [comment]
> @dam-ease Hi, thank you for your suggestion. Is my flutter version 3.10.6 is older or the in_app_purchase plugin version 3.1.5 is older, or both?

Both are older versions.

> I found another problem, i tried used normal google play account to download my release app in google play store. but also
still unable to get any products. my release app is only published in Korea.
Does my Google play store configuration wrong?

I can't tell this for sure, but this might be an issue on your end.
