### ISSUE TITLE
Extract ChangeNotifier from Flutter to pure Dart

### ISSUE THREAD

**Issue by alexeyinkin** [flutter/flutter#136155]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Flutter has `Listenable`, `ChangeNotifier` and `ValueNotifier`. It's a common need to allow object to have listeners and notify them. It has applications in pure Dart code without Flutter.

I personally want to use it in my package that loads data from network and notifies when the next batch is loaded. If used in a Flutter app, it can be listened to by `AnimatedBuilder`, and so it must implement `Listenable`, which is Flutter-only. But my package has no other Flutter dependencies and can be used in CLI or server apps.

So far I use a `Stream<void>` of events in the object. In pure Dart, the stream can be listened to. In Flutter, a `StreamBuilder` can be used to rebuild things on the events. But the complexity of streams over a simple `ChangeNotifier` is redundant.

### Proposal

Move `Listenable`, `ChangeNotifier`, `ValueNotifier`, etc. to a separate package that can be used without Flutter. Make Flutter depend on it.

**Comment by TekExplorer** [comment]
Okay, how is this issue completely quiet? This would be a massive win for the dart ecosystem as a whole, and would make inter-compatibility drastically more likely. Plus, more and more listenable-based tools would come about.

**Comment by alexeyinkin** [comment]
Can someone on the team give thoughts on this? Pros / cons / the destination package suggestions... So a volunteer can work on this.

**Comment by TekExplorer** [comment]
@alexeyinkin turns out this is a duplicate of https://github.com/flutter/flutter/issues/149466

**Comment by alexeyinkin** [comment]
Except this one is 8 months older. However, that one has more votes, and Kevin can get it farther.

**Comment by alexeyinkin** [comment]
Closing in favor of
- #149466
