### ISSUE TITLE
Add Ability to Constrain Dragging within ReorderableListView

### ISSUE THREAD

**Issue by JerContact** [flutter/flutter#136146]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

The problem I'm having right now is within the ReorderableListView.  If I drag a widget it can be dragged outside the constraints of the ReorderableListView.  I would like to request a way to constain the dragging for both vertical and horizontal.  Right now it's only constrained on one axis.

![image](https://github.com/flutter/flutter/assets/38195772/0781e7c2-2a1b-475f-a50f-0e7579a9f17c)

### Proposal

I would like to add a boolean to constain widgets inside the bounds of the ReorderableListView.

![image](https://github.com/flutter/flutter/assets/38195772/57944d1b-b409-456b-a60e-b52c700a46fa)

**Comment by dam-ease** [comment]
Hi @JerContact. Thanks for filing this. Can you please provide more information on this. Do you mean enabling ability to restrict dragging from occurring??

**Comment by JerContact** [comment]
So, you should still be able to drag horizontal in this example, but ONLY inside the bounds of the ReorderableListView

**Comment by dam-ease** [comment]
Thanks for your response @JerContact. Looking through https://github.com/flutter/flutter/issues/86502, I think it might be related to what you are describing, can you check that out as well?
