### ISSUE TITLE
Can I run google_sign_in on macOS?

### ISSUE THREAD

**Issue by TakaTeke** [flutter/flutter#136188]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I want to get the body text from Gmail.

### Proposal
Hello.
Can I run google_sign_in on macOS?
I'll write the code from now.
Please let me know if you have any good ideas.
thank you.

**Comment by stuartmorgan** [comment]
Closing as a duplicate of https://github.com/flutter/flutter/issues/46157
