### ISSUE TITLE
Display error when devicePixelRatio is 3.5

### ISSUE THREAD

**Issue by Bigniuql** [flutter/flutter#136152]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

As shown in the code and video，the rendering error resulted in unexpected blank lines. A reasonable conclusion at present is that the product of devicePixelRatio and size is not an integer, causing this error.
Hope this problem can be solved soon.

### Expected results

Displayed correctly

### Actual results

Display Error

### Code sample

<details><summary>Code sample</summary>

```dart
class ListTest extends StatelessWidget {
  const ListTest({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: _buildBody(),
    );
  }

  Widget _buildBody() {
    return Row(
      children: [
        Expanded(
          child: ListView(
              scrollDirection: Axis.horizontal,
              children: List.filled(
                  10,
                  Container(
                    width: 41,
                    height: 99,
                    color: randomColor(),
                    alignment: Alignment.center,
                    child: Text("${window.devicePixelRatio}"),
                  ))),
        )
      ],
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>
https://github.com/flutter/flutter/assets/22394343/54d532db-7e01-4c33-a73c-2bfc66ccaa3a
</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
> A reasonable conclusion at present is that the product of devicePixelRatio and size is not an integer, causing this error.

@Bigniuql 
The [documentation](https://api.flutter.dev/flutter/dart-ui/FlutterView/devicePixelRatio.html) says the same. `This number might not be a power of two. Indeed, it might not even be an integer. For example, the Nexus 6 has a device pixel ratio of 3.5.` Check the same and see if it helps in your case or not.



> ```dart
> window.devicePixelRatio
> ```

Can you provide what Flutter version are you on ? I verified the code sample on latest stable (3.13.6) in which, the `window` property is deprecated.

<img width="929" alt="Screenshot 2023-10-09 at 3 50 30 PM" src="https://github.com/flutter/flutter/assets/67046386/ea3ee3bb-0c51-477a-91ee-4fd0fe584084">

You may try with the newer version and check if using it, you get same behavior or not.

**Comment by Bigniuql** [comment]
> Check the same and see if it helps in your case or not.

Thanks. My Flutter version is 3.3.2, i will have a try with the latest version

**Comment by Bigniuql** [comment]
> > A reasonable conclusion at present is that the product of devicePixelRatio and size is not an integer, causing this error.
> 
> @Bigniuql The [documentation](https://api.flutter.dev/flutter/dart-ui/FlutterView/devicePixelRatio.html) says the same. `This number might not be a power of two. Indeed, it might not even be an integer. For example, the Nexus 6 has a device pixel ratio of 3.5.` Check the same and see if it helps in your case or not.
> 
> > ```dart
> > window.devicePixelRatio
> > ```
> 
> Can you provide what Flutter version are you on ? I verified the code sample on latest stable (3.13.6) in which, the `window` property is deprecated.
> 
> <img alt="Screenshot 2023-10-09 at 3 50 30 PM" width="929" src="https://user-images.githubusercontent.com/67046386/273556927-ea3ee3bb-0c51-477a-91ee-4fd0fe584084.png">
> You may try with the newer version and check if using it, you get same behavior or not.

I verified with the version 3.13.6, but the problem still exists. 
Code is as below:
```
class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          backgroundColor: Theme.of(context).colorScheme.inversePrimary,
          title: Text(title),
        ),
        body: Center(
          child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [
            Expanded(
              child: ListView.builder(
                itemBuilder: (context, index) {
                  return Container(
                    width: double.infinity,
                    color: Colors.blueAccent,
                    alignment: Alignment.center,
                    child: Text("${View.of(context).devicePixelRatio}"),
                  );
                },
                itemCount: 10,
                itemExtent: 100,
              ),
            )
          ]),
        ));
  }
}
```

When i use realme X7 Pro:

https://github.com/flutter/flutter/assets/22394343/ddb59b36-194e-43c3-a6f8-a32dae05844c

When i use Honor magic 5 Pro:

https://github.com/flutter/flutter/assets/22394343/b2470dc3-d8d0-461b-9a67-1d975b8ca184

Now i think the point of this issue is not the device pixel ratio or size, the phenomenon may be common.And not only ListView, Flex also has this issue.

**Comment by darshankawar** [comment]
Thanks for the update. I believe you are hitting below similar issues in which you can follow-up for further updates:

Antialiasing behaviour when same-colour  #14288
https://github.com/flutter/flutter/issues/22056

Closing this issue as a duplicate.
