### ISSUE TITLE
Display bug: Images don't take up all the space in a stack with rounded edges

### ISSUE THREAD

**Issue by LeRomino** [flutter/flutter#136124]
### Is there an existing issue for this?

- [x] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Start by creating a "ClipRRect" widget with borderRadius.
2. Then add a "Stack" widget using the "child" property and set the "fit" property to "StackFit.expand".
3. Within the "Stack" widget, add two or more children. The first child can be a "Container" widget with a white background color for testing.
4. The last child of the "Stack" widget is an "Image.network" widget. Use this image because it's black (so easier to see the bug with contrast): 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/A_black_image.jpg/640px-A_black_image.jpg'. Set the "fit" property of the "Image.network" widget to "BoxFit.cover".

### Expected results

I expect to see the image taking up all the available space with rounded corners and a simple white color when the image is not loaded.

### Actual results

When the image is loaded, I can see a bit of the white container in the rounded corners!

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

class Test extends StatelessWidget {
  const Test({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Center(
      child: AspectRatio(
        aspectRatio: 1 / 1,
        child: ClipRRect(
          borderRadius: const BorderRadius.all(Radius.circular(30)),
          child: Stack(
            fit: StackFit.expand,
            children: [
              Container(
                color: Colors.white,
              ),
              Image.network(
                'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/A_black_image.jpg/640px-A_black_image.jpg',
                fit: BoxFit.cover,
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshot</summary>

![image](https://github.com/flutter/flutter/assets/86157775/a9ab4d51-e923-4de0-aa43-f583461b28a0)

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.13.3, on Microsoft Windows [version 10.0.22621.2283], locale fr-FR)
    • Flutter version 3.13.3 on channel stable at C:\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2524052335 (4 weeks ago), 2023-09-06 14:32:31 -0700
    • Engine revision b8d35810e9
    • Dart version 3.1.1
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\u\AppData\Local\Android\sdk
    • Platform android-33-ext5, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.18)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.32802.440
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] VS Code (version 1.83.0)
    • VS Code at C:\Users\u\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.74.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [version
      10.0.22621.2283]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 117.0.5938.149
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 117.0.2045.43
    ! Device emulator-5562 is offline.

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by mandgeprathamesh** [comment]
Just Add clip bahaviour as hardedge

**Comment by LeRomino** [comment]
Thanks a lot, the problem is solved but with this the corner is no longer smooth!
Is it possible to fix this unwanted effect please?

![image](https://github.com/flutter/flutter/assets/86157775/aec4c67e-b514-44f1-ac38-56c20ea72869)

**Comment by LeRomino** [comment]
The corner should be made as smooth as before but the image should still take up all the space.

**Comment by LeRomino** [comment]
I found Clip.antiAliasWithSaveLayer, thank you very much!
