### ISSUE TITLE
Proposal to implement `switch` expressions throughout the Flutter repo.

### ISSUE THREAD

**Issue by nate-thegrate** [flutter/flutter#136139]
`switch` expressions are designed for specific use cases; several such cases exist in the flutter repo, but right now they're implemented as `switch` statements.

#### Example (animation.dart):

```dart
String toStringDetails() {
  switch (status) {
    case AnimationStatus.forward:
      return '\u25B6'; // >
    case AnimationStatus.reverse:
      return '\u25C0'; // <
    case AnimationStatus.completed:
      return '\u23ED'; // >>|
    case AnimationStatus.dismissed:
      return '\u23EE'; // |<<
  }
}
```

```dart
String toStringDetails() {
  return switch (status) {
    AnimationStatus.forward   => '\u25B6'; // >
    AnimationStatus.reverse   => '\u25C0'; // <
    AnimationStatus.completed => '\u23ED'; // >>|
    AnimationStatus.dismissed => '\u23EE'; // |<<
  };
}
```

They both work, but in my opinion the latter is easier to understand and thus more helpful for debugging.

<br>

Additionally, there are places where implementing `switch` expressions can remove the need for a variable, or allow you to make it `final` or non-nullable when you otherwise wouldn't be able to:

#### Example 2 (list_tile.dart):

```dart
EdgeInsetsGeometry? padding = widget.padding;
if (padding == null) {
  switch (widget._type) {
    case _CupertinoListTileType.base:
      padding = widget.subtitle == null ? _kPadding : _kPaddingWithSubtitle;
    case _CupertinoListTileType.notched:
      padding = widget.leading == null ? _kNotchedPaddingWithoutLeading : _kNotchedPadding;
  }
}
```

```dart
final EdgeInsetsGeometry padding = widget.padding ?? switch (widget._type) {
  _CupertinoListTileType.base   => widget.subtitle == null ? _kPadding : _kPaddingWithSubtitle,
  _CupertinoListTileType.notched => widget.leading == null ? _kNotchedPaddingWithoutLeading : _kNotchedPadding,
};
```

**Comment by stuartmorgan** [comment]
Why? A proposal for a change should provide motivation for it, and evaluate pros and cons. This just asserts a solution without describing a problem.

**Comment by nate-thegrate** [comment]
Oh, my bad! I've updated the original comment to be more explanatory.

**Comment by darshankawar** [comment]
@nate-thegrate 
Can you take a look at [this](https://github.com/dart-lang/language/issues/3061) issue and see if it would affect your proposal and implementation ?

**Comment by nate-thegrate** [comment]
@darshankawar  
The issue you linked points out that Dart doesn't look ahead into a `switch` body to tell whether it's a switch statement or a switch expression; instead the evaluation is based on whether `switch` is present at the beginning of the line or is being assigned/returned (e.g. `final x = switch (foo) {…}` or `return switch (foo) {…}`).

Fortunately, this issue does not affect any of my proposed changes.
