### ISSUE TITLE
packages pointer_interceptor test fails

### ISSUE THREAD

**Issue by rzambroni** [flutter/flutter#136176]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Install Flutter version 3.16.0-6.0.pre.10 

2. Clone the Flutter packages repository: git clone [GitHub - flutter/packages: A collection of useful packages maintained by the Flutter team](https://github.com/flutter/packages) 

3. Navigate to the packages/pointer_interceptor/example directory: cd packages/pointer_interceptor/example

4. Run the command flutter pub get

5. Run the command: flutter drive \                        
  --driver=test_driver/integration_test.dart \
  --target=integration_test/widget_test.dart \
  -d chrome >> pointer_interceptor-logs.txt

### Expected results

Running all tests should succeed. 
Note: This test works as expected with the latest stable (3.13.6)

### Actual results

The following test fails.

Logs:

```console
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: 'background-html-view'
  Actual: 'flt-semantic-node-6'
   Which: is different.
          Expected: background ...
            Actual: flt-semant ...
                    ^
           Differ at offset 0

When the exception was thrown, this was the stack:
dart-sdk/lib/internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:3  throw
packages/matcher/src/expect/expect.dart 149:31                               fail
packages/matcher/src/expect/expect.dart 144:3                                _expect
packages/matcher/src/expect/expect.dart 56:3                                 expect$
packages/flutter_test/src/widget_tester.dart 458:18                          expect$
widget_test.dart 49:7                                                        <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50           <fn>
dart-sdk/lib/async/zone.dart 1407:47                                         _rootRunUnary
dart-sdk/lib/async/zone.dart 1308:19                                         runUnary
dart-sdk/lib/async/future_impl.dart 162:18                                   handleValue
dart-sdk/lib/async/future_impl.dart 846:44                                   handleValueCallback
dart-sdk/lib/async/future_impl.dart 875:13                                   _propagateToListeners
dart-sdk/lib/async/future_impl.dart 647:5                                    [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 721:7                                    <fn>
dart-sdk/lib/async/zone.dart 1399:13                                         _rootRun
dart-sdk/lib/async/zone.dart 1301:19                                         run
dart-sdk/lib/async/zone.dart 1209:7                                          runGuarded
dart-sdk/lib/async/zone.dart 1249:23                                         callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                             _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                              _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7           <fn>

The test description was:
  on wrapped elements with intercepting set to false, the browser hits the background-html-view
```

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

[pointer_interceptor-logs.txt](https://github.com/flutter/flutter/files/12842435/pointer_interceptor-logs.txt)

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Flutter Doctor Output:

[✓] Flutter (Channel stable, 3.16.0-6.0.pre.10, on macOS 14.0 23A344 darwin-arm64, locale en-UY)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Community Edition (version 2023.2.2)
[✓] VS Code (version 1.82.3)
```

</details>

**Comment by stuartmorgan** [comment]
I would expect this to have failed in CI since we should be running these tests against master and stable there.

**Comment by rzambroni** [comment]
Hi @stuartmorgan, thanks for the response. I'm closing this issue since we re-tested this with a newer version and it worked fine. (We also validated stable)

Channel master, 3.16.0-12.0.pre.92
Channel stable, 3.13.7
