### ISSUE TITLE
Allow ~ in dependencies in pubspec.yaml

### ISSUE THREAD

**Issue by dragonfax** [flutter/flutter#13614]
Full on glob might be a bit much. But i'm sure dev pubspec's world-wide are filled with references to /Users/<blah> or /home/<blah>.

pubspec.yaml
```
  android_alarm_manager:
    path: ~/Code/flutter/plugins/packages/android_alarm_manager
```

flutter packges get
```
ERR : Could not find package android_alarm_manager at "~/Code/flutter/plugins/packages/android_alarm_manager".
```

**Comment by cbracken** [comment]
Thanks for filing! 



One thing to note is that pub is designed as a cross-platform tool and `~`-expansion is a platform-specific shell feature. 

@munificent @nex3 does pub currently support any convention for cross-platform home directory expansion (`$HOME` on linux/macOS and `%userprofile%` on Windows)?

**Comment by munificent** [comment]
See this very old bug: https://github.com/dart-lang/pub/issues/491. The relevant comment, which I think still applies, is:

> This would be nice, but I think it opens up some confusing questions about what goes in the lockfile. Putting the shell expanded path in the lockfile would make the lockfile not portable where the pubspec is. Putting the non-shell expanded path in there means changing environment variables could spontaneously change the behavior of an otherwise locked package.
>
> I think the simplest, safest, thing to do is to just not allow path expansion.

I don't know what fraction of pubspecs contain absolute paths, but I think almost all of them would be better off using relative paths.

**Comment by dragonfax** [comment]
Too many arguments against this. I'm going to admit defeat, and close it. Thanks for the responses.
