### ISSUE TITLE
Subclass of FlutterViewController, overriding canBecomeFirstResponder causes an error.

### ISSUE THREAD

**Issue by GordonHuangYong** [flutter/flutter#136184]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Objective-c

1. create subclass of `FlutterViewController`

* MyViewController.h
``` 
@interface MyViewController : FlutterViewController

@end
```

* MyViewController.m
```
@interface MyViewController ()

@end

@implementation MyViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
}
-(BOOL)canBecomeFirstResponder{
    return YES;
}
```
3.  Replace the `FlutterViewController` in Main.storyboard with `MyViewController`
4. lanuch app, then error occurred
```
2023-10-09 14:32:22.014393+0800 Runner[11115:412577] void * _Nullable NSMapGet(NSMapTable * _Nonnull, const void * _Nullable): map table argument is NULL
2023-10-09 14:32:22.114439+0800 Runner[11115:412922] flutter: The Dart VM service is listening on http://127.0.0.1:50688/ZNUf_kKSZZs=/

```

### Expected results

no error occurred.

### Actual results

error occurred
```
2023-10-09 14:32:22.014393+0800 Runner[11115:412577] void * _Nullable NSMapGet(NSMapTable * _Nonnull, const void * _Nullable): map table argument is NULL
2023-10-09 14:32:22.114439+0800 Runner[11115:412922] flutter: The Dart VM service is listening on http://127.0.0.1:50688/ZNUf_kKSZZs=/
```

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.6, on macOS 13.4.1 22F770820d darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
[✓] IntelliJ IDEA Community Edition (version 2023.2.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.5)
[✓] VS Code (version 1.75.0)
[!] Proxy Configuration
    ! NO_PROXY is not set
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by dam-ease** [comment]
Hi @GordonHuangYong. Thanks for filing this. I see a similar log, can you check out https://developer.apple.com/forums/thread/718179 to see if the possible solution provides more information. If not, can you share a sample repo that we could run to reproduce this?
