### ISSUE TITLE
video_player is not displayed in ConsumerWidget

### ISSUE THREAD

**Issue by ko-key** [flutter/flutter#136209]
### Is there an existing issue for this?

- [x] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Use ConsumerWidget instead of StatefulWidget
2. Get video from URL instead of Local
3. Display videos with the VideoPlayer widget

### Expected results

I would like to know how I can get the video to display without having to do Reload, etc.

### Actual results

The widget will appear only after reloading, etc.
Local videos would not have this problem. Also, if you do a hot reload, etc., the video will be displayed normally.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

class VideoPlayerControllerWrapper
    extends ValueNotifier<VideoPlayerController> {
  VideoPlayerControllerWrapper(VideoPlayerController videoPlayerController)
      : super(videoPlayerController);
}

ValueNotifier<bool> isInitialized = ValueNotifier<bool>(false);

final videoPlayerControllerProvider =
    Provider<VideoPlayerControllerWrapper>((ref) {
  final controller = VideoPlayerController.networkUrl(Uri.parse(
      "https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4"));

  controller.initialize().then((value) => isInitialized.value = true);

  return VideoPlayerControllerWrapper(controller);
});

class VideoDisplay extends ConsumerWidget {
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    var controller = ref.read(videoPlayerControllerProvider);

    return ValueListenableBuilder(
      valueListenable: isInitialized,
      builder: (_, value, __) {
        if (value) {
          return Scaffold(
            body: Center(
              child: Align(
                  alignment: Alignment.topCenter,
                  child: AspectRatio(
                    aspectRatio: 16 / 11,
                    child: VideoPlayer(controller.value),
                  )),
            ),
          );
        } else {
          return const Scaffold(
            body: Center(child: CircularProgressIndicator()),
          );
        }
      },
    );
  }
}

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.6, on macOS 13.5 22G74
    darwin-arm64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android
    SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.82.3)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by ko-key** [comment]
Local videos would not have this problem. Also, if you do a hot reload, etc., the video will be displayed normally.

**Comment by danagbemava-nc** [comment]
Hi @ko-key, what platform(s) are you seeing this issue on? What version of video_player are you using? 

Have you tried triggering a rebuild after the initialization phase to see if the video frame is displayed?

**Comment by ko-key** [comment]
Thanks for replying.

video_player: ^2.7.2
iOS 16.6(Actual device)


We have not tried to detect rebuilds.


The same situation occurred with the code I tried using the method from the video_player reference. Here is the code I used

### 

<details><summary>Rewritten Code</summary>

```dart
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

class VideoPage extends StatefulWidget {
  const VideoPage({super.key});

  @override
  State<VideoPage> createState() => _VideoPageState();
}

class _VideoPageState extends State<VideoPage> {
  late VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.asset('videos/video-1.mp4')
      ..addListener(() => setState(() {}))
      ..setLooping(true)
      ..initialize().then((_) => setState(() {}));
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SizedBox.expand(
        child: FittedBox(
          fit: BoxFit.cover,
          child: SizedBox(
            width: _controller.value.size.width,
            height: _controller.value.size.height,
            child: VideoPlayer(_controller),
          ),
        ),
      ),
    );
  }
}


```

</details>

**Comment by ko-key** [comment]
The most puzzling thing is that this is only reproduced on IOS. (I haven't tried Android)

**Comment by ko-key** [comment]
@danagbemava-nc

**Comment by ko-key** [comment]
By any chance, is video_player transparent before playback? Does it not show the thumbnail view, I can see the thumbnails in Chrome, does this mean it's a Chrome glitch?

**Comment by ko-key** [comment]
I added code that  Print Video status each time it is built.

```dart
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(),
      home: const VideoPage(),
    );
  }
}

class VideoPage extends StatefulWidget {
  const VideoPage({super.key});

  @override
  State<VideoPage> createState() => _VideoPageState();
}

class _VideoPageState extends State<VideoPage> {
  late VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network(
        "https://flutter.github.io/assets-for-api-docs/assets/videos/butterfly.mp4")
      ..addListener(() => setState(() {}))
      ..setLooping(true)
      ..initialize().then((_) => setState(() {}));
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    print(_controller);
    return Scaffold(
      body: SizedBox.expand(
        child: FittedBox(
          fit: BoxFit.cover,
          child: SizedBox(
            width: _controller.value.size.width,
            height: _controller.value.size.height,
            child: VideoPlayer(_controller),
          ),
        ),
      ),
    );
  }
}



```

Result is

`flutter: VideoPlayerController#fa305(VideoPlayerValue(duration: 0:00:00.000000, size: Size(0.0, 0.0), position: 0:00:00.000000, caption: Caption(number: 0, start: 0:00:00.000000, end: 0:00:00.000000, text: ), captionOffset: 0:00:00.000000, buffered: [], isInitialized: false, isPlaying: false, isLooping: true, isBuffering: false, volume: 1.0, playbackSpeed: 1.0, errorDescription: null, isCompleted: false),)


flutter: VideoPlayerController#fa305(VideoPlayerValue(duration: 0:00:07.540000, size: Size(1280.0, 720.0), position: 0:00:00.000000, caption: Caption(number: 0, start: 0:00:00.000000, end: 0:00:00.000000, text: ), captionOffset: 0:00:00.000000, buffered: [], isInitialized: true, isPlaying: false, isLooping: true, isBuffering: false, volume: 1.0, playbackSpeed: 1.0, errorDescription: null, isCompleted: false),)

flutter: VideoPlayerController#fa305(VideoPlayerValue(duration: 0:00:07.540000, size: Size(1280.0, 720.0), position: 0:00:00.000000, caption: Caption(number: 0, start: 0:00:00.000000, end: 0:00:00.000000, text: ), captionOffset: 0:00:00.000000, buffered: [DurationRange(start: 0:00:00.000000, end: 0:00:07.540000)], isInitialized: true, isPlaying: false, isLooping: true, isBuffering: false, volume: 1.0, playbackSpeed: 1.0, errorDescription: null, isCompleted: false),)
Reloaded 1 of 1266 libraries in 134ms (compile: 27 ms, reload: 51 ms, reassemble: 37 ms).`



I think it is due to the fact that Size 0 . Can you come up with a solution?
