### ISSUE TITLE
Broken Links in `Add Homescreen widget` codelab

### ISSUE THREAD

**Issue by joeatnovvia** [flutter/flutter#136204]
https://github.com/flutter/codelabs/blob/homescreen_widgets/homescreen_codelab/step_04/ios/NewsWidgets/NewsWidgets.swift#L48-L57
Not Found error

https://github.com/flutter/codelabs/blob/homescreen_widgets/homescreen_codelab/step_04/lib/article_screen.dart#L32
Not Found error

**Comment by danagbemava-nc** [comment]
Hi @joeatnovvia, where did you find these links so that we can fix them over there?

PS: This is the correct link https://github.com/flutter/codelabs/tree/main/homescreen_codelab

**Comment by joeatnovvia** [comment]
I would have assumed the "Report a mistake" would tell you what page the
mistake was on.  That would be helpful to your support team in the future.
I was on the CodeLab for Adding a Home Screen widget to your Flutter App "
https://codelabs.developers.google.com/flutter-home-screen-widgets?hl=en
all of the links on the page referring to github are broken.

**Comment by danagbemava-nc** [comment]
Thanks for the link. 

cc @domesticmouse

**Comment by domesticmouse** [comment]
PTAL @ericwindmill

**Comment by domesticmouse** [comment]
I believe this is now fixed

**Comment by joeatnovvia** [comment]
Thank you so much!
