### ISSUE TITLE
[image_picker] Image picker android is updating Kotlin on a minor release

### ISSUE THREAD

**Issue by zeucxb** [flutter/flutter#136262]
I’m facing an issue with image_picker, image picker started to use there plugin code as dependency. But it’s always upgrading just the minor and using minor auto update (^) so any image_picker version always get the last image_picker_android even with different Kotlin versions. Basically image_picker_android upgraded the kotlin on minor 0.8.6+15 to 1.8.x so to use a different kotlin version I need to dependency override 0.8.6+14 that has not the Kotlin 1.8 version. 

image_picker is publishing versions with sub packages ^0.8.5 than ^0.8.6 what’s do not makes sense, because even downgrading image_picker it'll not downgrade image_picker_android, just with dependency override.

[v0.8.6+14](https://github.com/flutter/packages/blob/image_picker_android-v0.8.6%2B14/packages/image_picker/image_picker_android/android/build.gradle)

[v0.8.6+15](https://github.com/flutter/packages/blob/image_picker_android-v0.8.6%2B15/packages/image_picker/image_picker_android/android/build.gradle) - on line 47

We are using image_picker in a flutter module project that is embedded on a android application with Kotlin 1.7.x.

**Comment by stuartmorgan** [comment]
Please don't ignore the issue template when filling issues; the structure there exists for a reason. As I said in both the PR and Discord, we need details about steps to reproduce, failure logs (i.e., what exactly is the output when you try to build with the latest version), etc.

I'm going to close this as it's missing almost all of the information needed to be actionable, and trying to address that without the template will be difficult. Please file a new issue using the relevant issue template, and fill it out completely.

**Comment by zeucxb** [comment]
@stuartmorgan Sorry, I just clicked the link you sent on the doc. It opened without template, now I saw the form. 😞

**Comment by stuartmorgan** [comment]
> Sorry, I just clicked the link you sent. On the doc it opened without template

Oops, I'll fix that in the packages repo README. Sorry about that!
