### ISSUE TITLE
[go_router] clearing browser history stack

### ISSUE THREAD

**Issue by rnp0728** [flutter/flutter#136253]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use Case
After logging out I don't want my users to go back even on clicking the browser's back button. I know I can use route guards to redirect the user back to login page, but I want to clear the bowser's stack.

Flutter version : 3.13.3
GoRouter version : 7.0.2

### Expected results

The code should clear the browser history stack & navigate to signin page.

### Actual results

The routes are not popping, but navigates to signin page.

### Code sample

<details><summary>Code sample</summary>

```dart
while (GoRouter.of(event.context).canPop()) {
    GoRouter.of(event.context).pop();
}

GoRouter.of(event.context).pushReplacementNamed(RoutesName.signinRoute);
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.3, on Pop!_OS 22.04 LTS
    6.5.4-76060504-generic, locale en_US.UTF-8)
    • Flutter version 3.13.3 on channel stable at
      /home/rnp/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2524052335 (5 weeks ago), 2023-09-06 14:32:31 -0700
    • Engine revision b8d35810e9
    • Dart version 3.1.1
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/rnp/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /snap/android-studio/128/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2022.3)
    • Android Studio at /snap/android-studio/128/android-studio
    • Flutter plugin version 75.1.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.83.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.74.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Pop!_OS 22.04 LTS 6.5.4-76060504-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 117.0.5938.149

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by huycozy** [comment]
Hi @rnp0728 

>The code should clear the browser history stack

I think this is impossible, see: https://developer.mozilla.org/en-US/docs/Web/API/Window/history#notes:

```
There is no way to clear the session history or to disable the back/forward navigation from unprivileged code. The closest available solution is the [location.replace()](https://developer.mozilla.org/en-US/docs/Web/API/Location/replace) method, which replaces the current item of the session history with the provided URL.
```

>After logging out I don't want my users to go back even on clicking the browser's back button. 

What do you expect if the user keeps clicking on browser's back button? Will it do nothing or something else? Could you share a sample web app/website having this feature?

Also, you can take a look at https://github.com/flutter/flutter/issues/108114. It could be an alternative option for your case.
