### ISSUE TITLE
XCTest Failing ('webview_flutter' not found)

### ISSUE THREAD

**Issue by rzambroni** [flutter/flutter#136263]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Install Flutter version 3.16.0-7.0.pre.38

2. Clone the Flutter packages repository: git clone [GitHub - flutter/packages: A collection of useful packages maintained by the Flutter team](https://github.com/flutter/packages)

3. Navigate to the packages/webview_flutter/webview_flutter directory: cd packages/webview_flutter/webview_flutter

4. Run the command flutter pub get

5. Navigate to the example/ios directory: cd example/ios

6. Run the command pod install

7. Run the command: (Replace $simulator_id)

```shell
 xcodebuild test -workspace Runner.xcworkspace -scheme Runner \
-destination 'platform=iOS Simulator,id=$simulator_id' >> webview_flutter-logs.txt
```

### Expected results

Running all tests should succeed.

### Actual results

The following test case fails: 

```console
/Users/hairon/Documents/packages/packages/webview_flutter/webview_flutter/example/ios/RunnerTests/FLTWebViewTests.m:7:9: fatal error: module 'webview_flutter' not found
@import webview_flutter;
````

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

[webview_flutter-logs.txt](https://github.com/flutter/flutter/files/12859194/webview_flutter-logs.txt)

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.16.0-7.0.pre.38, on macOS 14.0 23A344 darwin-arm64, locale en-UY)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Community Edition (version 2023.2.2)
[✓] VS Code (version 1.82.3)
[✓] Connected device (3 available)
```

</details>

**Comment by stuartmorgan** [comment]
Running `xcodebuild` commands directly requires running some kind of `flutter build` (e.g., `flutter build ios --no-codesign --config-only`) first.

Closing as the steps here are not expected to work.
