### ISSUE TITLE
Upgrade another chromium x86 bot to macOS 13.5+ from try pool 

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#136257]
### Is there an existing issue for this?

- [X] I have searched the [existing infra issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-infra)

### Type of Request

infra task

### Infrastructure Environment

Devicelab

### What is happening?

Upgrade one chromium x86 bot to macOS 13.5+ from try pool

**Comment by yusuf-goog** [comment]
filed: https://bugs.chromium.org/p/chromium/issues/detail?id=1496962

**Comment by yusuf-goog** [comment]
completed.
