### ISSUE TITLE
Feature - CalendarDatePicker theme for disabled years selection

### ISSUE THREAD

**Issue by petrnymsa** [flutter/flutter#136242]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Currently, if DatePicker has disabled some years, e.g firstDate is in 2023 and last date in 2024, thus years before (or later) can not be selected, there is no UI indication.

```dart
Widget build(BuildContext context) {
    final firstDate = DateTime(2023, 1, 1);
    final selectedDate = DateTime(2023, 10, 10);
    final lastDate = DateTime(2024, 12, 31);

    return MaterialApp(
      darkTheme: ThemeData.dark(),
      home: Scaffold(
        body: Center(
          child: CalendarDatePicker(
            initialDate: selectedDate,
            firstDate: firstDate,
            lastDate: lastDate,
            onDateChanged: (d) {},
            selectableDayPredicate: (d) => ![6, 7].contains(d.weekday), //skip weekend
          ),
        ),
      ),
    );
```
Only 2023 (currently selected) and 2024 are selectable. 

![image](https://github.com/flutter/flutter/assets/21087414/d9018cda-ae8c-4ef7-9950-e81c2046d297)

### Proposal

Provide a way to style year selection or at least have a default "disabled" state for years, so user know which years are selectable

**Comment by danagbemava-nc** [comment]
Hi @petrnymsa, you can use the `datePickerTheme` in conjunction with the `MaterialStateProperty` to set the disabled color for years. Does the example below suffice for your use case?

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() async {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    final firstDate = DateTime(2023, 1, 1);
    final selectedDate = DateTime(2023, 10, 10);
    final lastDate = DateTime(2024, 12, 31);

    return MaterialApp(
      darkTheme: ThemeData.dark().copyWith(datePickerTheme: DatePickerThemeData(
        yearForegroundColor: MaterialStateProperty.resolveWith(
          (states) {
            if (states.contains(MaterialState.disabled)) {
              return Colors.grey;
            }

            return Colors.green;
          },
        ),
      )),
      home: Scaffold(
        body: Center(
          child: CalendarDatePicker(
            initialDate: selectedDate,
            firstDate: firstDate,
            lastDate: lastDate,
            onDateChanged: (d) {},
            selectableDayPredicate: (d) => ![6, 7].contains(d.weekday), //skip weekend
          ),
        ),
      ),
    );
  }
}
```
</details>

**Comment by petrnymsa** [comment]
> ```dart
>   darkTheme: ThemeData.dark().copyWith(datePickerTheme: DatePickerThemeData(
>         yearForegroundColor: MaterialStateProperty.resolveWith(
>           (states) {
>             if (states.contains(MaterialState.disabled)) {
>               return Colors.grey;
>             }
> 
>             return Colors.green;
>           },
>         ),
>       )),
> ```

Works! I've missed that theme. Thank you. Closing
