### ISSUE TITLE
[CP] Link PlatformView back to semantics tree 

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#136266]
### Issue Link

https://github.com/flutter/flutter/issues/135504

### Commit Hash

250daadbca517677317277f314ea2a40568eb345

### Target

beta

### PR Link

https://github.com/flutter/engine/pull/46715

### Changelog Description

Fix a regression on iOS where the voice over traversal stops after visiting a PlatformView.

### Impacted Users

end-customers on iOS

### Impact Description

voice over not working properly

### Workaround

No.

### Risk

low

### Test Coverage

yes

### Validation Steps

Sample app in https://github.com/flutter/flutter/issues/135504

**Comment by cyanglaz** [comment]
I would like to have a cherry-pick to stable after this lands.

**Comment by itsjustkevin** [comment]
Approved by @stuartmorgan in the PR.
