### ISSUE TITLE
[flutter release] gcloud bucket path error when verifying provenance

### ISSUE THREAD

**Issue by XilaiZhang** [flutter/flutter#136218]
linux engine release builder: https://ci.chromium.org/ui/p/dart-internal/builders/flutter/Linux%20engine_release_builder/686/overview

Looks like the gcloud path could not be located when downloading to verify provenance. the error seems to point to @drewroengoogle 's [recent changes](https://cs.opensource.google/flutter/recipes/+/master:recipe_modules/flutter_bcid/api.py;l=55;bpv=1?q=provenan&sq=&ss=flutter%2Frecipes)?

sample error looks like 
```
CommandException: No URLs matched: gs://download.flutter.io/io/flutter/armeabi_v7a_profile/1.0.0-379f2e8719f62051c35a4a4e0bab3b959c6c0609/armeabi_v7a_profile-1.0.0-379f2e8719f62051c35a4a4e0bab3b959c6c0609.jar.intoto.jsonl
WARNING:root:Command /b/s/w/ir/cipd_bin_packages/cpython3/bin/python3 -u /b/s/w/ir/kitchen-checkout/depot_tools/gsutil.py -- cp gs://download.flutter.io/io/flutter/armeabi_v7a_profile/1.0.0-379f2e8719f62051c35a4a4e0bab3b959c6c0609/armeabi_v7a_profile-1.0.0-379f2e8719f62051c35a4a4e0bab3b959c6c0609.jar.intoto.jsonl /b/s/w/ir/x/w/recipe_cleanup/verify3nri293k/armeabi_v7a_profile-1.0.0-379f2e8719f62051c35a4a4e0bab3b959c6c0609.jar.intoto.jsonl failed with retcode 1, try 1.1.
```

**Comment by XilaiZhang** [comment]
cc @godofredoc

**Comment by godofredoc** [comment]
This error is correct, the real problem is that no provenance is being generated for jar files.

**Comment by godofredoc** [comment]
ACLs to write provenance for jar files has been fixed.
