### ISSUE TITLE
[process] Remove reference to record/replay in README

### ISSUE THREAD

**Issue by bartekpacia** [flutter/flutter#136221]
This issue is copied from https://github.com/google/process.dart/issues/73

---

The readme of `packages/process` talks about:

> Comes with a record-replay implementation out-of-the-box, making it super easy to test code that spawns processes in a hermetic way.

but I couldn't find any info about it except that it was removed. Why was that? Will it be re-added at some point? Or should the readme simply be adjusted?

See also:

https://github.com/google/process.dart/pull/47

**Comment by stuartmorgan** [comment]
Retitling to reflect that this is a documentation problem; re-adding that much complexity for a feature we apparently weren't using and haven't needed in the last several years is out of scope.

**Comment by neiljaywarner** [comment]
@stuartmorgan  can we have record/replay it as a low priority someday maybe feature request ? :)

**Comment by stuartmorgan** [comment]
@neiljaywarner Anyone is welcome to file feature requests.
