### ISSUE TITLE
`test: run suite safari-dart2js-canvaskit-canvaskit` fails on macOS 13 in CI

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#136274]
Fails consistently with the following error:

```
00:01 +32 ~2 -1: semantics_test.dart: CanvasKit semantics container container node compensates for rect offset [E]                                                                                     
  Expected: '0px 0px 0px'
    Actual: '0px 0px'
     Which: is different. Both strings start the same, but the actual value is missing the following trailing characters:  0px
```

https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Engine%20Drone/439889/overview

**Comment by vashworth** [comment]
This is a blocker for https://github.com/flutter/flutter/issues/134736.

**Comment by eyebrowsoffire** [comment]
Well this is annoying. See the following jsfiddle: https://jsfiddle.net/afeuvh9p/3/

In Chrome, it outputs `transform origin: 0px 0px 0px` but in Safari it outputs `transform origin: 0px 0px`
