### ISSUE TITLE
Add transition duration property to PopupMenuThemeData 

### ISSUE THREAD

**Issue by alexvoina** [flutter/flutter#136243]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I want to use PopupMenu in my desktop app, but I don't like the default 300ms animation when rendering the popup menu. 

```
material/popup_menu.dart

const Duration _kMenuDuration = Duration(milliseconds: 300);
```

https://github.com/flutter/flutter/assets/32097135/0b4473b4-add8-4324-bfaa-016626bb853a

I looked at the code but there doesn't seem a way to control this animation through material properties.. 

I don't see the point for this imposed constant value since most desktop apps use a faster animation or no animation at all for showing popup menus (e.g Spotify, Linear, Ableton, Capcut)

https://github.com/flutter/flutter/assets/32097135/22dc5145-671c-472c-af38-1978dd9162c7

### Proposal

Expose the _PopupMenuRoute's  transitionDuration parameter in the PopupMenuThemeData parameters

**Comment by dam-ease** [comment]
Hi @alexvoina.Thanks for proposing this. I see there is an open proposal describing this https://github.com/flutter/flutter/issues/135638. Kindly comment, upvote and follow up on this issue for updates. Closing this in favour of the already open issue, if you disagree, please comment and I'll reopen this.
