### ISSUE TITLE
After extracting the simplest Flutter program to a specific directory, it encounters a white screen when executed on a windows machine

### ISSUE THREAD

**Issue by 21pages** [flutter/flutter#136249]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Note

* This issue is only reproducible on the computer belonging to user @Morkph.
* Let's refer to `C:\Users\<username>\AppData\Local\rustdesk` as `directory A`. The occurrence of the white screen is closely related to the directory where the program is run. It can only be reproduced in `directory A`.

### How reproduced on user's machine

on developer's machine:
1. Run `flutter create simple_flutter_demo` to create a simplest flutter demo.
2. Run `flutter build windows`.
3. Compress the files located in `build/windows/runner/release` into zip.

on user‘s machine:

4. Extract the zip file to `directory A`, click and run, get white screen.
5. Extract the zip file to a common directory, click and run, works fine.

### Expected results

The white screen issue does not occur when running on the user's machine in `directory A`.

### Actual results

Following the steps mentioned above, running the program located in `directory A` results in a white screen on the user's machine.

### Code sample

<details><summary>Code sample</summary>

Run `flutter create simple_flutter_demo`, then get the code. 

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/flutter/flutter/assets/14891774/ff317c16-0962-4199-87a0-599510ebd8e3)

</details>

### Logs

<details><summary>flutter create simple_flutter_demo -v</summary>

```console
$ flutter create simple_flutter_demo
Flutter assets will be downloaded from https://pub.dev. Make sure you trust this source!
Creating project simple_flutter_demo...
Resolving dependencies in simple_flutter_demo...
Got dependencies in simple_flutter_demo.
Wrote 129 files.

All done!
You can find general documentation for Flutter at: https://docs.flutter.dev/
Detailed API documentation is available at: https://api.flutter.dev/
If you prefer video documentation, consider: https://www.youtube.com/c/flutterdev

In order to run your application, type:

  $ cd simple_flutter_demo
  $ flutter run

Your application code is in simple_flutter_demo\lib\main.dart.


selfd@pc MINGW64 /d/flutter
$ cd simple_flutter_demo

selfd@pc MINGW64 /d/flutter/simple_flutter_demo
$ flutter build windows
Flutter assets will be downloaded from https://pub.dev. Make sure you trust this source!

Building Windows application...                                    29.5s
√  Built build\windows\runner\Release\simple_flutter_demo.exe (0.1MB).

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
$ flutter doctor -v
Flutter assets will be downloaded from https://pub.dev. Make sure you trust this source!
[!] Flutter (Channel unknown, 3.10.6, on Microsoft Windows [版本 10.0.22621.2283], locale zh-CN)
    ! Flutter version 3.10.6 on channel unknown at D:\program\flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    • Framework revision f468f3366c (3 months ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1
    • Pub download mirror https://pub.dev
    • Flutter download mirror https://pub.dev
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at D:\program\Android\SDK
    • Platform android-33-ext5, build-tools 33.0.2
    • Java binary at: D:\program\Android\AndroidStudio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.5)
    • Visual Studio at D:\program\MicrosoftVisualStudio\2022\Community
    • Visual Studio Community 2022 version 17.5.33627.172
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2022.1)
    • Android Studio at D:\program\Android\AndroidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.22621.2283]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 117.0.5938.150
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 117.0.2045.47

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

</details>

**Comment by Morkph** [comment]
@21pages do you want me to follow the steps mentioned above?

**Comment by 21pages** [comment]
You have already done today.

**Comment by stuartmorgan** [comment]
What is `<username>`; does it contain any special characters? Windows path handling of Unicode has some edge cases that can be problematic for Flutter applications.

**Comment by 21pages** [comment]
> What is `<username>`; does it contain any special characters? Windows path handling of Unicode has some edge cases that can be problematic for Flutter applications.

all English, no special characters

**Comment by Morkph** [comment]
I have recorded a reproduction of the issue. Hope this clarifies things.
[2023-10-10 23-41-05.zip](https://github.com/flutter/flutter/files/12862102/2023-10-10.23-41-05.zip)

**Comment by 21pages** [comment]
Tried many `common directory`, both in in drive C or drive D, only `directory A` reproduced.

**Comment by huycozy** [comment]
@21pages I tried installing the latest rustdesk [here](https://github.com/rustdesk/rustdesk/releases/tag/1.2.2) and extracted flutter Windows build `Release` directory to `C:\Users\<username>\AppData\Local\rustdesk` but can't reproduce this. 

Also, it can just copy whole `Release` directory to `rustdesk` directory . If you copy subfiles inside `Release`, there will be a warning about overwriting `flutter_windows.dll` file with `rustdesk`.

<details>
<summary>Demo video</summary>

https://github.com/flutter/flutter/assets/104349824/551c8ef4-9f9d-4730-8073-350c5ca42e0e

</details>

Does this issue only happen on @Morkph machine? If so, could @Morkph share the file/folder structure there inside `rustdesk` directory?

**Comment by rustdesk** [comment]
> @21pages I tried installing the latest rustdesk [here](https://github.com/rustdesk/rustdesk/releases/tag/1.2.2) and extracted flutter Windows build `Release` directory to `C:\Users\<username>\AppData\Local\rustdesk` but can't reproduce this.

We can not reproduce it either. It can be reproduced on @Morkph 's machine only.

**Comment by rustdesk** [comment]
> Does this issue only happen on @Morkph machine? If so, could @Morkph share the file/folder structure there inside `rustdesk` directory?

His file/folder structure does not have anything special, we had checked.

**Comment by huycozy** [comment]
Unfortunately, if the steps to reproduce are not clear, it is not easy to take the issue forward. So I would suggest you keep an eye on it if you are able to replicate it consistently and see if it has any pattern. If you are unable to see it again, feel free to close it and write a comment when you have clear steps to reproduce. Thanks!

**Comment by 21pages** [comment]
Thanks
