### ISSUE TITLE
[CP] Fix PointFieldGeometry coverage

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#136372]
### Issue Link

flutter/flutter#134068

### Commit Hash

f3a4cab

### Target

beta

### PR Link

https://github.com/flutter/engine/pull/46776

### Changelog Description

Fix coverage values when using drawPoints in a save layer

### Impacted Users

iOS users that use drawPoints

### Impact Description

drawPoints may render incorrectly if it is in a save layer.

### Workaround

Use Skia renderer

### Risk

low

### Test Coverage

yes

### Validation Steps

Run attached unittests

**Comment by itsjustkevin** [comment]
@zanderso could you take a look at this cherry-pick?

**Comment by zanderso** [comment]
LGTM
