### ISSUE TITLE
CircularProgressIndicator should provide a simple color setting

### ISSUE THREAD

**Issue by ride4sun** [flutter/flutter#13630]
## Steps to Reproduce

```dart
new CircularProgressIndicator(
        valueColor: new AlwaysStoppedAnimation<Color>(Colors.green)
```

I had search quite a bit to find the information in gitter how to change the progress bar color and wondered why there is no direct setting for the color to make this easier.

## Flutter Doctor
```

C:\Projects\emoji>flutter doctor
[√] Flutter (on Microsoft Windows [Version 10.0.16299.125], locale en-US, channel alpha)
    • Flutter at c:\sdks\flutter
    • Framework revision 8f65fec5f5 (3 days ago), 2017-12-12 09:50:14 -0800
    • Engine revision edaecdc8b8
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.d8ae797298c3a6cf8dc9f4558707bd2672224d3e

[√] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at C:\Users\ride4\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 19.1
    • Dart plugin version 172.4343.25

[√] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)
```

**Comment by rahulmishra1991** [comment]
You can use Theme here

    new Theme(
          data: Theme.of(context).copyWith(accentColor: Colors.yellow),
          child: new CircularProgressIndicator(),
        );

**Comment by HansMuller** [comment]
I agree that the fact that one can use `AlwaysStoppedAnimation<Color>(color)` as `valueColor` is a little obscure.  It's currently mentioned in the documentation for the `valueColor` properties but not in the progress indicator class docs.

Providing a parameter that's just shorthand for AlwaysStoppedAnimation seemed like overachieving a little. 

Updated the progress indicator docs here: https://github.com/flutter/flutter/pull/29564. Hopefully that should bring AlwaysStoppedAnimation out of the shadows :-).

**Comment by ride4sun** [comment]
I disagree - from the user perspective, it takes several minutes if not longer to find the docs for this obscure setting. As a developer, I start with the IDE (Intelly Sense) dropdown help. Then I have startup the docs... etc. Adding a shorthand would probably take less than a minute to add but would save many people valuable time down the road and adds consistency throughout the framework. Just my 2 Cents.

**Comment by patelkrunal78** [comment]
You can add this code.

CircularProgressIndicator(
valueColor: new AlwaysStoppedAnimation<Color>(Colors.white),
),

Found At [Here](https://icetutor.com/question/how-to-change-color-of-circularprogressindicator)

**Comment by milanpatel18** [comment]
You can add this code.

CircularProgressIndicator(
valueColor: new AlwaysStoppedAnimation<Color>(Colors.white),
),

Found At [Here](https://icetutor.com/question/how-to-change-color-of-circularprogressindicator/)
