### ISSUE TITLE
Platform Isolate

### ISSUE THREAD

**Issue by liamappelbe** [flutter/flutter#136314]
This is a tracking bug for the Platform Isolate feature. The design details are still being worked out, but the general idea is to provide a way of using FFI to invoke native APIs that can only be be called from the platform thread.

Some related bugs: https://github.com/flutter/flutter/issues/113099, https://github.com/flutter/flutter/issues/28310, https://github.com/dart-lang/sdk/issues/52106, https://github.com/dart-lang/sdk/issues/38315, https://github.com/dart-lang/sdk/issues/42570, https://github.com/dart-lang/sdk/issues/46943, https://github.com/dart-lang/native/issues/463

Remaining work tasks after initial PR landed

- Allow calling `runInPlatformThread()` from helper isolates: https://github.com/flutter/flutter/issues/150584
- In `PlatformIsolateManager::RemovePlatformIsolate` and `PlatformIsolateManager::ShutdownPlatformIsolates`, find a way of asserting that we're on the platform thread: https://github.com/flutter/flutter/issues/150586

**Comment by insinfo** [comment]
I believe that perhaps this could solve the problem of low-level audio API callbacks in the system that today cannot be called with dart ffi

**Comment by liamappelbe** [comment]
@insinfo Only if the audio API calls those callbacks on the platform thread. Audio APIs often create their own internal thread dedicated to audio rendering, and in that case platform isolates wouldn't help.

**Comment by nadaeltorgoman** [comment]
I still have a problem with that

**Comment by halildurmus** [comment]
@liamappelbe I wanted to use the `runOnPlatformThread` function but it appears to be not defined.

I can see the `platform_isolate.dart` file defined in the `dart:ui` library:

![Screenshot 2024-03-19 201614](https://github.com/flutter/flutter/assets/45524029/29788260-9667-45d5-bfbc-6e190ac0924e)

However, it's missing in the `ui` folder:

![Screenshot 2024-03-19 202057](https://github.com/flutter/flutter/assets/45524029/3d3c2efc-2772-4fc9-b7ee-662ff826a35a)

My Dart version:
```
Dart SDK version: 3.4.0-247.0.dev (dev) (Tue Mar 19 05:02:52 2024 -0700) on "windows_x64"
```

**Comment by liamappelbe** [comment]
> Edit: I'm curious if this issue might be linked to the absence of an entry for `platform_isolate.dart` in the [dart_ui.gni](https://github.com/flutter/engine/blob/main/lib/ui/dart_ui.gni#L5-L25) file.

Maybe. I'm not a regular contributor to the engine, so I'm not sure what plumbing is needed when a new file is added. I'm surprised this wasn't caught by CI though. @jason-simmons should I add platform_isolate.dart to dart_ui.gni?

**Comment by jason-simmons** [comment]
Sent a PR to add it to `dart_ui.gni`: https://github.com/flutter/engine/pull/51538

**Comment by halildurmus** [comment]
The Platform Isolate API is now available on the master channel.

I've tried calling the [runOnPlatformThread](https://github.com/flutter/engine/blob/main/lib/ui/platform_isolate.dart#L29) function in a Flutter Counter app but the app crashed with this error:
```
[FATAL:flutter/fml/message_loop.cc(21)] Check failed: loop != nullptr. MessageLoop::EnsureInitializedForCurrentThread was not called on this thread prior to message loop use.
```

It doesn't matter what you do in the function that you pass to the runOnPlatformThread function. Even calling it this way crashes the app with the above error:
```dart
  void _incrementCounter() async {
    await runOnPlatformThread(() {});
    // ...
  }
```

**Comment by jason-simmons** [comment]
What platform did this happen on?

From the screenshot in https://github.com/flutter/flutter/issues/136314#issuecomment-2007757919 it looks like you're running on Windows.

The `runOnPlatformThread` API is not supported on embedders such as Linux and Windows that use a custom task runner for the platform thread (see https://github.com/flutter/engine/pull/48551#issuecomment-1962190896)

I'm planning to add a Flutter engine flag that embedders can use to indicate whether they support this API.

**Comment by halildurmus** [comment]
> What platform did this happen on?
> 
> From the screenshot in [#136314 (comment)](https://github.com/flutter/flutter/issues/136314#issuecomment-2007757919) it looks like you're running on Windows.

Yes, I tested this on Windows.

> The `runOnPlatformThread` API is not supported on embedders such as Linux and Windows that use a custom task runner for the platform thread (see [flutter/engine#48551 (comment)](https://github.com/flutter/engine/pull/48551#issuecomment-1962190896))
> 
> I'm planning to add a Flutter engine flag that embedders can use to indicate whether they support this API.

I see. Thanks for the explanation.

**Comment by liamappelbe** [comment]
@halildurmus What's your use case? Windows APIs aren't usually thread locked

**Comment by halildurmus** [comment]
> @halildurmus What's your use case? Windows APIs aren't usually thread locked

I think I've found a Win32 API ([ShowCursor](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-showcursor)) that needs to be called on the platform thread in order to work (see https://github.com/dart-windows/win32/issues/313).

I've confirmed that it works (hides the cursor) if I call the API inside the Windows runner (windows\runner\main.cpp).

**Comment by jason-simmons** [comment]
Looked at this again and found a viable way to make the current platform isolates implementation work with the task runner design used on Linux and Windows.

Proposed a PR: https://github.com/flutter/engine/pull/51573

**Comment by halildurmus** [comment]
Not entirely sure whether the changes made in https://github.com/flutter/engine/pull/51573 were intended to completely resolve the problems on Linux and Windows but after trying again, I still encountered the same error. I even gave it a shot on Linux, but it didn't work there either.

**Comment by jason-simmons** [comment]
No - that PR is not a complete solution.

There is still the issue of supporting embedders where the platform thread does not have a message loop (see https://github.com/flutter/engine/pull/48551#issuecomment-1962190896).

With https://github.com/flutter/engine/pull/51573 a call to `runOnPlatformThread` in a `host_debug_unopt` Linux or Windows desktop engine build will execute the function on the platform thread.

But that only works because an internal debugging feature (`DebugTaskRunnerChecker`) is creating a message loop on the platform thread.  Production builds will not enable this, so platform isolate initialization will fail with the `MessageLoop::EnsureInitializedForCurrentThread was not called` assertion seen above.

The Linux and Windows embedders will need to solve this in order to enable support for platform isolates.

The message loop is needed because `UIDartState` is trying to install a callback that runs after each message in order to execute Dart microtasks.  If platform isolates need to support microtasks, then the embedder must create a message loop on the platform thread and also run the loop and execute this callback.

So until this is resolved I think it makes sense to also add the engine flag that embedders can use to declare whether they support platform isolates.

**Comment by orestesgaolin** [comment]
Wondering if there's a design doc or summary of what this means to Flutter developers?

**Comment by l619534951** [comment]
May I ask if after this feature is implemented, I will be able to call the native function from the thread where the win32 window was created?

For example,  [SetWindowSubclass](https://learn.microsoft.com/en-us/windows/win32/api/commctrl/nf-commctrl-setwindowsubclass) for win32 can only be called from the thread that created the win32 window. ```SetWindowSubclass``` can not be used across threads.

So I can't do it with pure dart code at the moment, I need to use platform channels for that.

**Comment by liamappelbe** [comment]
> May I ask if after this feature is implemented, I will be able to call the native function from the thread where the win32 window was created?

The feature is already implemented (as [`runOnPlatformThread`](https://api.flutter.dev/flutter/dart-ui/runOnPlatformThread.html)), but unfortunately it's only fully supported on iOS and Android. I think there's partial support on windows and linux (debug mode only). See [Jason's comment](https://github.com/flutter/flutter/issues/136314#issuecomment-2015872797) for details.

**Comment by liamappelbe** [comment]
I've split off the remaining bits of work into their own issues. Closing this now.

**Comment by knopp** [comment]
@jason-simmons, I don't think `fml::MessageLoop` can be used on platform thread for windows and linux, the implementation differs from what the platform would normally use (`GMainContext` and `GetMessage`/`DispatchMessage`). We'll probably need another way to drain the microtask queue from platform thread (one that does not depend on `fml::MessageLoop`. I'm currently building macOS prototype for https://github.com/flutter/engine/pull/53656 and microtask draining is one of the issues.
