### ISSUE TITLE
[camera] NSError bacause of old version camera_avfoundation 

### ISSUE THREAD

**Issue by inventor97** [flutter/flutter#136354]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

dyld[751]: Symbol not found: _OBJC_CLASS_$_NSError
  Referenced from: <BBBDBA94-91FA-308F-B5FF-165935A899CD> /private/var/containers/Bundle/Application/DD4A631B-60CE-466F-BE14-0B7353697CE0/Runner.app/Runner

### Expected results

Please upgrade camera_avfoundation to 0.19.3+6

### Actual results

  Expected in:     <28C38A38-CDE5-389C-BB6F-4DE6F9283AFC> /private/var/containers/Bundle/Application/DD4A631B-60CE-466F-BE14-0B7353697CE0/Runner.app/Frameworks/camera_avfoundation.framework/camera_avfoundation

### Code sample

dyld`:
    0x1d1b2ae58 <+0>:  mov    x16, #0x209
    0x1d1b2ae5c <+4>:  svc    #0x80
->  0x1d1b2ae60 <+8>:  b.lo   0x1d1b2ae80               ; <+40>
    0x1d1b2ae64 <+12>: pacibsp 
    0x1d1b2ae68 <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1d1b2ae6c <+20>: mov    x29, sp
    0x1d1b2ae70 <+24>: bl     0x1d1adc98c               ; cerror_nocancel
    0x1d1b2ae74 <+28>: mov    sp, x29
    0x1d1b2ae78 <+32>: ldp    x29, x30, [sp], #0x10
    0x1d1b2ae7c <+36>: retab  
    0x1d1b2ae80 <+40>: ret    

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.4)
[✓] Connected device (4 available)

**Comment by stuartmorgan** [comment]
> ### Expected results
> Please upgrade camera_avfoundation to 0.19.3+6

Updating dependencies is done at the app level; see `flutter pub upgrade`. Closing as there is no action for the Flutter team here.

Also, in the future please provide steps to reproduce in that section of the template, rather than error messages.
