### ISSUE TITLE
[Impeller] OpenGL: Use `glClearDepth` and `glDepthRange` on desktop GL.

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#136322]
The macOS GL driver throws GL_INVALID_OPERATION when attempting to use the ES variants `glClearDepthf` and `glDepthRangef`.

**Comment by jonahwilliams** [comment]
Its worth noting that Flutter on macOS desktop and iOS explicitly do not support OpenGL.

**Comment by chinmaygarde** [comment]
Can we just use Angle instead on macOS? Or not support this backend.

**Comment by bdero** [comment]
This is needed for desktop GL support in general.
