### ISSUE TITLE
How to work with icons assets on Flutter

### ISSUE THREAD

**Issue by mobilemindtec** [flutter/flutter#13635]
Hi,

I'm developing my first real flutter project and I have a question about assets. Can I use platform assets to load my app icons? If no, I need create flutter assets to my app. But, what is recommended size to general icons?

Flutter documentation says:

`Main assets are presumed to match a nominal pixel ratio of 1.0. To specify assets targeting different pixel ratios, place the variant assets in the application bundle under subdirectories named in the form "Nx", where N is the nominal device pixel ratio for that asset.`

But Android and IOS have many screen sizes. Using platform assets I create all icons according platform specification. So how I do in flutter? What are the specifications of general purpose icons?

Thanks!

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2000](https://github.com/flutter/website/issues/2000) via [**ZenHub**](https://www.zenhub.com/)
