### ISSUE TITLE
Tests running on staging bots even when not in bringup

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#136389]
### Is there an existing issue for this?

- [X] I have searched the [existing infra issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-infra)

### Type of Request

feature request

### Infrastructure Environment

LUCI

### What is happening?

There are some tests that are running that are suffixed with `_staging` that are not in bringup and don't show in the tree.

You can find some examples on these bots:
https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-4
https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-26
https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-33

According to @keyonghan:
> They are legacy ones from old staging configs. https://ci.chromium.org/p/flutter/g/devicelab_staging/console. But I don't see issues to clean up considering we have `bringup: true` targets validating staging pool now.

### Expected results

I expect these tests not to run.

**Comment by keyonghan** [comment]
Cleaned up in https://flutter-review.googlesource.com/c/infra/+/51563.
