### ISSUE TITLE
Contradictory instruction in flutter-firebase codelab 6, GoogleService-Info.plist

### ISSUE THREAD

**Issue by jmnyv** [flutter/flutter#13636]
According to step 6 in the flutter-firebase codelab:

> Add the bundle ID and the reverse URL of your client id to the main dictionary of your app's **GoogleService-Info.plist** file

According to https://pub.dartlang.org/packages/google_sign_in

> Then add the CFBundleURLTypes attributes below into the [my_project]/ios/Runner/**Info.plist** file.

The two instructions contradict each other. I ended up using the latter and it worked.

**Comment by colinricardo** [comment]
@jmnyv this has been updated.

**Comment by Hixie** [comment]
Closing per last comment. Thanks!
