### ISSUE TITLE
[CP] Correct warning for compatible Java versions range given template AGP & Gradle versions

### ISSUE THREAD

**Issue by camsim99** [flutter/flutter#136388]
### Issue Link

https://github.com/flutter/flutter/pull/135710 has a description of the problem (I don't have one but I can open one if needed)

### Commit Hash

54cf286

### Target

beta

### PR Link

~https://github.com/flutter/flutter/pull/135710~ https://github.com/flutter/flutter/pull/136766

### Changelog Description

Corrects the range of Java versions that `flutter create` will show if your Java version is incompatible with Flutter's template AGP & Gradle versions and/or is too new/old a version to be recognized by Flutter's tooling.

The range currently printed suggests that the upper bound is inclusive, whereas it is exclusive, so it may confuse developers.

### Impacted Users

All Flutter devs running `flutter create` for something running on Android

### Impact Description

They will see a range of Java versions that is confusing. It can easily be found out as incorrect by following documentation linked in the warning, but we can't guarantee devs will look there to confirm the range of Java versions that we suggest.

### Workaround

Following the documentation linked in the warning to check the Java versions.

### Risk

low

### Test Coverage

yes

### Validation Steps

There are many tests that prove that the range is exclusive (https://github.com/flutter/flutter/blob/a047358c5c8d6cdb395d833fdd365ae1492e7e32/packages/flutter_tools/test/general.shard/android/gradle_utils_test.dart#L945). I just forgot to format the warning appropriately in https://github.com/flutter/flutter/pull/131444, where I added the warning.

**Comment by itsjustkevin** [comment]
@reidbaker could you take a look at this cherry-pick and attach the `cp: approved` label if you agree?

**Comment by itsjustkevin** [comment]
@camsim99 can you link the cherry-pick PR you created?

**Comment by reidbaker** [comment]
Labels added for approval.

**Comment by camsim99** [comment]
> @camsim99 can you link the cherry-pick PR you created?

https://github.com/flutter/flutter/pull/135710
