### ISSUE TITLE
camera_web should produce seekable videos

### ISSUE THREAD

**Issue by jezell** [flutter/flutter#136316]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Using the camera package on web you can obtain a video, you can then play this video directly in a video player to preview it. Unfortunately, Chrome has a longstanding bug that it creates bad unseekable videos, and camera_web inherits this problem, making camera_web and video_player_web integrate together poorly in Chrome:

https://bugs.chromium.org/p/chromium/issues/detail?id=642012

### Proposal

The webm spec was changed because this is a really big problem in practice, but the Chrome team hasn't fixed chrome yet (firefox does it properly). Until the Chrome team gets around to fixing Chrome (if they ever reopen the issue), it would be nice if the camera_web package fixed up the video to be seekable before returning it so that the video player package can deal with it more properly. Here's an example package that does this:

https://github.com/buynao/webm-duration-fix

**Comment by stuartmorgan** [comment]
If the only way to resolve it is to post-process the video with a third party package anyway (and thus not something that can be done more efficiently if implemented within the plugin), what is the argument for adding that complexity to the plugin? The purpose of the plugin is to allow capture, not to do post-processing, and there are nearly infinite possible things clients could want to do to a video; I don't see a compelling reason to add this specific one to the plugin.

**Comment by stuartmorgan** [comment]
> As it is now, any app built with flutter that tries to record a video and pop it in the video recorder directly so it can be previewed before upload will be broken in chrome with regard to seek and duration information.

Isn't that also true of any web app *not* built with Flutter?

> This is not about adding complexity to the plugin

How do you propose implementing this proposal without adding any complexity to the plugin?

> it's about making the interaction between the camera and video_player plugins flutter work consistently across all platforms with regard to expected user behavior. I believe every anyone using the camera and video_player package on web will hit this issue and have a subpar experience.

What about people using `camera` but not using `video_player`, and who don't want this alteration to the data? Which means increased API complexity to opt into running a step that could just as easily be run directly by clients who do want that behavior instead.

> If making things work consistently across all platforms requires a little extra complexity to get right, isn't that exactly the value proposition of flutter?

Abstracting away all platform differences is not a goal of our plugins. For instance, some people have asked for us to add transcoders to `camera` in the name of abstracting away platform differences in recording formats, and we don't do that either.

To the extent that abstracting things is a goal for the Flutter ecosystem as whole, having a separate package that does this would also allow people to build experiences that work consistently across all platforms (presumably with one or two lines of code in the app). What is the downside to that approach?

**Comment by jezell** [comment]
> Isn't that also true of any web app _not_ built with Flutter?

The issue isn't whether it's true of any web app not built with flutter. The issue is that this basic and common scenario works on iOS native, works on Android native, works on Desktop native, works on Firefox, works on Safari, and fails in Chrome. I don't expect my web app to give me a native iOS app, I do expect Flutter to give me an app that works across platforms, that's the whole reason I'm using it.
 
> How do you propose implementing this proposal without adding any complexity to the plugin?

I would propose that moving the headers around is fairly low in complexity for the value it provides.
 
> What about people using `camera` but not using `video_player`, and who don't want this alteration to the data? Which means increased API complexity to opt into running a step that could (as far as I can tell from the discussion above) just as easily be run directly by clients who do want that behavior instead.

There isn't anyone who prefers a video that is not seekable, that's why Firefox and other browsers give you the video this way already. It's only Chrome where this issue occurs. There would be zero breaking changes introduced by fixing the data transparently and it requires zero changes to the API interface to make happen. 

> Abstracting away all platform differences is not a goal of our plugins. For instance, some people have asked for us to add transcoders to `camera` in the name of abstracting away platform differences in recording formats, and we don't do that either. Instead we encourage people who want to transcode the videos produced by `camera` to find stand-alone packages that do that post-processing step.

This is not transcoding, it's not changing the format. It's patching a bug that only occurs in a specific browser, which is not unusual at all for web libraries to do to save their users frustration.
 
> To the extent that abstracting things is a goal for the Flutter ecosystem as whole, having a separate package that does this would also allow people to build experiences that work consistently across all platforms (presumably with one or two lines of code in the app). What is the downside to that approach?

The downside is that anyone who ever tries to use the camera package on web and preview their file before uploading it will have a bad experience, then have to go hunt for another package to fix the problem. 

The better question is what's the real downside to the plugin working out of the box? A few lines of code? Certainly another package to fix the data or a utility function within the camera_web package would be better than nothing, but I'd be interested to know if there's really any user who is using camera_web + video_player_web and thinks the current behavior is desirable and that fixing this would not be worth the effort.

Regardless, such a package does not currently exist, so every flutter web user that needs to preview a captured video on web is going to be faced with a significant problem, and have no solution outside of writing it themselves or figuring out how to integrate an npm package into their flutter app to solve the problem. I'd suggest that it's worth the flutter team solving that general problem, regardless of whether it's fixing the camera plugin to work properly out of the box (my preference), adding a utility function to the package, or publishing another package.

**Comment by stuartmorgan** [comment]
> I do expect Flutter to give me an app that works across platforms, that's the whole reason I'm using it.

It currently works as well as the platform does. Again, abstracting away *all* platform differences is a non-goal for our plugins. If people want to write wrappers that provider higher levels of abstraction with more polyfill, that's certainly an option.

> There isn't anyone who prefers a video that is not seekable [...] There would be zero breaking changes introduced by fixing the data transparently

How have you determined that nobody using `camera` has any reliance on the output matching the underlying platform?

> This is not transcoding, it's not changing the format.

I didn't say it was; please re-read my comment. I was providing an example of previous cases of us explicitly *not* abstracting away platform differences in `camera` even though it's something that has been requested by other developers, using exactly the same argument you are making here (i.e., the proposition that we have an obligation in the 1P plugins to use polyfills to abstract away any platform differences).

> The downside is that anyone who ever tries to use the camera package on web and preview their file before uploading it will have a bad experience, then have to go hunt for another package to fix the problem.

That seems easily resolvable with a comment in the `camera_web` README.

> The better question is what's the real downside to the plugin working out of the box?

Expending finite resources on maintaining complexity that could just as easily be done by the community at large, so the Flutter team can focus those limited resources on things that *can't* trivially be separate packages.

> A few lines of code?

The package you linked to is over 6,000 lines of code. It is substantially more code than the entire `camera_web` implementation.

> Regardless, such a package does not currently exist, so every flutter web user that needs to preview a captured video on web is going to be faced with a significant problem, and have no solution outside of writing it themselves or figuring out how to integrate an npm package into their flutter app to solve the problem. I'd suggest that it's worth the flutter team solving that general problem

This argument can be (and often is) applied to literally any functionality that any developer wants.jJust because there exist people in the Flutter community who want some piece of functionality doesn't mean the Flutter team should be the ones to implement it, nor is that even remotely possible for that to be the case.

This can easily be a separate package, and doesn't require any specialized knowledge that is specific to the Flutter team, so seems very well positioned to be implemented by the community in general.

I'll also point out that you are simultaneously arguing that:
- this is so trivial to implement that it would cost the Flutter team essentially nothing to write and maintain, and also that
- this is so hard that the Flutter team needs to step in because it's too complex for the community to be able to resolve.

Both cannot be true.

**Comment by jezell** [comment]
> I'll also point out that you are simultaneously arguing that:
> 
> * this is so trivial to implement that it would cost the Flutter team essentially nothing to write and maintain, and also that
> * this is so hard that the Flutter team needs to step in because it's too complex for the community to be able to resolve.
> 
> Both cannot be true.

No, I am arguing that a user wanting to see a seekable preview a video that they recorded before uploading is something that should be supported out of the box.

You are putting words in my mouth. I didn't say ever say it would cost nothing to maintain. I said everyone who uses flutter web and wants to preview a video before they upload it is going to have a bad experience in Chrome and I believe that they should not have a bad experience.

I do think it's worth the flutter team spending time to fix it, but that's not really the issue. I wouldn't even mind contributing the fix myself. The question is whether the flutter team cares that this very basic scenario is broken in Chrome enough to even accept a pull request that fixes it.

**Comment by jezell** [comment]
@stuartmorgan there is another potential solution if someone on the flutter team has contacts on the Chrome team, which is if the Flutter team could reach out to the Chrome team and request that they fix it, then everyone could be happy. Either way, the state of Chrome and Flutter together leave something to be desired in this area. This is something that video recording packages in the JS ecosystem have worked around and have solutions for, but there is not currently a Dart / Flutter solution to the problem and it's certainly frustrating as an end user when you run into things like this doing very basic things which are unique to the Flutter ecosystem and the Flutter team doesn't seem to care about. I see 18 different video recorder packages on NPM that have this fix built in. Zero on pub.dev.

**Comment by stuartmorgan** [comment]
> You are putting words in my mouth. I didn't say ever say it would cost nothing to maintain.

Apologies, that was not my intent. I read the argument that the only downside would be "a few lines of code" as suggesting that this would be trivial.

> if the Flutter team could reach out to the Chrome team and request that they fix it, then everyone could be happy

Lack of requests to change the behavior does not appear to be a factor in the Chromium issue you linked above.

> it's certainly frustrating as an end user when you run into things like this doing very basic things which are unique to the Flutter ecosystem

This problem isn't unique to the Flutter ecosystem though. The lack of existing solutions in the ecosystem may be, but I haven't suggested that the Flutter ecosystem shouldn't address it.

> I wouldn't even mind contributing the fix myself.
> [...]
> there is not currently a Dart / Flutter solution to the problem

The lack of of-the-shelf solutions on pub.dev is, as I mentioned earlier, something that anyone could fix. If you are willing to create a Dart solution as a PR for `camera`, why not as a stand-alone package, solving the problem of the being no Dart solutions to the problem (and being usable with any package, rather than just `camera`)? Notably, the thing you linked to in the initial issue report is exactly that: a stand-alone package that allows adjusting video files, not connected to or embedded in a video player.

**Comment by jezell** [comment]
> The lack of of-the-shelf solutions on pub.dev is, as I mentioned earlier, something that anyone could fix. If you are willing to create a Dart solution as a PR for `camera`, why not as a stand-alone package, solving the problem of the being no Dart solutions to the problem (and being usable with any package, rather than just `camera`)? Notably, the thing you linked to in the initial issue report is exactly that: a stand-alone package that allows adjusting video files, not connected to or embedded in a video player.

It is, yet it's also something no one has fixed. I love flutter, but flutter web is a mess when it comes to things like video and media right now. Anyone trying to build any solution that has to playback videos has to deal with things like the video player randomly crashing, running out of platform layers, and basic things like playing back a recorded video not working. The Flutter team of course is free to do whatever they want, but as a user who has done all of this stuff both outside of Flutter web and inside of Flutter web, it sucks a hell of a lot more to do this stuff on Flutter. Seems like the Flutter web team has a drastically lower bar than the other teams, as well as a drastically lower bar than random dudes publishing JS packages on NPM. Yeah, we can keep fixing all this crap ourselves, but it's really unfortunate that the team even thinks it's acceptable for the web story to suck so bad out of the box.

**Comment by yjbanov** [comment]
> Seems like the Flutter web team has a drastically lower bar than the other teams, as well as a drastically lower bar than random dudes publishing JS packages on NPM.

@jezell I wouldn't characterize it as a quality bar, but more feature completeness. It's actually quite likely that random dudes on NPM have more time and dedication to provide a more complete feature set in their packages. We have limited resources on the Flutter Web team, and so we have to control the scope of features that we can support. In particular, we have to prioritize issues that cannot be solved by pub packages, such as bugs and performance issues in the engine and in the framework. So, PRs are welcome, but also, as @stuartmorgan is saying, maybe this is better achieved as a community package (maintained by random dudes 😄).

**Comment by stuartmorgan** [comment]
> Seems like the Flutter web team has a drastically lower bar than the other teams

Examples of other web development frameworks where this workaround is maintained by the developers of the core framework itself could be helpful in giving context to the request that the Flutter team own this.

**Comment by jezell** [comment]
> @jezell I wouldn't characterize it as a quality bar, but more feature completeness. It's actually quite likely that random dudes on NPM have more time and dedication to provide a more complete feature set in their packages. We have limited resources on the Flutter Web team, and so we have to control the scope of features that we can support. 

I get it, and the team has accomplished a lot of great stuff, but come on, we can't even play a video more than a couple times without the video player crashing on web (https://github.com/flutter/flutter/issues/136309). That's a cop out. Media support sucks on flutter web, that's a fact that we have to deal with every day. Flutter is so great at solving everything else on the cross platform side that we are still happy to work around it, but it's not production level stuff on the media end. It's  an endless stream of fighting Flutter to do basic stuff. Those issues are unique to Flutter web. We don't have those issues with the other implementations of the engine.

**Comment by jezell** [comment]
@yjbanov here's another example: https://github.com/dart-lang/http/issues/1030. I can't even upload a media file to S3 or GCS because dart web is stuck in IE 5.5 land. The response from the team is that it's fine that a class that exists to stream http requests doesn't actually stream and I should just use another package instead of the built in one. I get the value of having packages to fill gaps in the ecosystem, but I can't even make a simple demo app that records a video, plays the video with a seek bar, and then uploads it right now without throwing away broken classes in the framework and getting alternative ones or building my own.

**Comment by jezell** [comment]
@yjbanov I mean, it's three very basic things I want to do. I need a video recorder, a video player, and an http request to work. The video recorder is broke. The video player is broke. The http request is broke. This is what I mean about a low quality bar. These are unique issues to flutter web. They don't exist on android and ios and they don't exist if I throw flutter out and go with pretty much any random js lib.

**Comment by Hixie** [comment]
Please consult our [code of conduct](https://github.com/flutter/flutter/blob/0f082889a8bd1db7cbc97a68270a2f9489ee24ab/CODE_OF_CONDUCT.md). The last few comments are way out of line.
