### ISSUE TITLE
Upgrade 1 arm devicelab bot in staging pool with msm8952 device to macOS 13.5+

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#136396]
### Is there an existing issue for this?

- [X] I have searched the [existing infra issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-infra)

### Type of Request

infra task

### Infrastructure Environment

Devicelab

### What is happening?

We need to upgrade 1 bot from the following list to be upgraded to macOS 13.5+ to complete testing
https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=os&c=status&d=asc&f=pool%3Aluci.flutter.staging&f=device_type%3Amsm8952&f=os%3AMac&f=cpu%3Aarm64&k=cpu&s=id

**Comment by yusuf-goog** [comment]
@kentnguyen99  please upgrade macOS on https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-33 to newest 13.5.x version.

**Comment by kentnguyen99** [comment]
@yusuf-goog The newest OS version is 14.0.  Can I upgrade mac-33 OS to version 14.0?

**Comment by yusuf-goog** [comment]
No, please upgrade to 13.5.x . cc @vashworth

**Comment by vashworth** [comment]
I agree with @yusuf-goog, would be best to be 13.5.x

**Comment by kentnguyen99** [comment]
@yusuf-goog & @vashworth,  Upgrading mac-33 OS to version 13.5 is done.
