### ISSUE TITLE
Can't build/archive to iOS outside simulators

### ISSUE THREAD

**Issue by Solido** [flutter/flutter#13638]
## Steps to Reproduce

I've been on this and I still can't figure it out. Is this a Flutter configuration problem or and XCode one. App is relying on Firestore.

`flutter release ios `
and then open Xcode

When working to prepare the IOS in XCode

Working :
 - deploy to any simulator
 - build and sign Runner>MyDevice

Archive Runner>MyDevice : 6 errors
`error: cannot parse the debug map for "/Users/user/Library/Developer/Xcode/DerivedData/Runner-bchmvqsnnuutcidnkxvqpmjnnzgm/ArchiveIntermediates/Runner/InstallationBuildProductsLocation/Applications/Runner.app/Runner": No such file or directory`
...

Build Runner > Generic IOS Device : 54 errors
`Undefined symbols for architecture armv7:
  "_pb_ostream_from_buffer", referenced from:
      _nano_two_pass_encoding in FirebaseNanoPB(encoder_common_a8c04d66ab304e1876b0dcfd3beba841.o)`

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.13.2 17C88, locale en-FR, channel master)
    • Flutter at /Users/robbie/Install/flutter
    • Framework revision e85d099229 (15 hours ago), 2017-12-15 19:10:18 -0800
    • Engine revision d945976b04
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.102a3c8e728a5e92a913cace4553995f8421f3e5

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

**Comment by Hixie** [comment]
cc @cbracken

**Comment by cbracken** [comment]
This sounds somewhat similar to some issues I ran into while adding support for armv7 where we required `pod install` to be re-run in certain cases (where architecture settings had changed in either the app, or flutter).

Related comments:
* https://github.com/flutter/flutter/issues/2089#issuecomment-386179186
* https://github.com/flutter/flutter/issues/2089#issuecomment-386349185

Can you try:
```
flutter clean
cd ios
pod install
cd ..
```
then rebuild?

**Comment by Black-Horse** [comment]
running `pod install` again reinstalled nanopb which solved this issue! Thanks!

**Comment by cbracken** [comment]
Great news! Thanks for confirming.
