### ISSUE TITLE
Windows platform view implementation possibilites

### ISSUE THREAD

**Issue by yaakovschectman** [flutter/flutter#136481]
Investigate how we might be able to implement platform views on Windows, keeping in mind the following requirements:

- Display an externally supplied window as at least an untransformed, rectangular, unclipped view,
- a11y, prioritizing display-only functionality,
- Pointer input\

DirectComposition and raw Win32 are possibilities.

**Comment by darshankawar** [comment]
@yaakovschectman 
Can you check [this](https://github.com/flutter/flutter/issues/31713) similar issue and see if it resembles your case ? If so, you may track in that issue for further updates and share your findings in it as well.
