### ISSUE TITLE
TextField support inline images like ChatGPT input box

### ISSUE THREAD

**Issue by lucasjinreal** [flutter/flutter#136438]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

TextField support inline images like ChatGPT input box

### Proposal

TextField support inline images like ChatGPT input box

**Comment by lucasjinreal** [comment]
https://github.com/flutter/flutter/issues/19204 related issue but not resolved still being closed and limited to collabrators

**Comment by dam-ease** [comment]
Hi @lucasjinreal. Thanks for proposing this. Can you try out https://github.com/flutter/flutter/issues/19204#issuecomment-511670508 to see if it suits your use case?

**Comment by lucasjinreal** [comment]
@dam-ease Clearly not, please have a look on ChatGPT's input box, at least flutter should make textfiled have image as inline widget support?

**Comment by dam-ease** [comment]
Hi @lucasjinreal. Thanks for your response. By the ChatGPT's input box, are you referring to this:
<img width="679" alt="Screenshot 2023-10-13 at 09 17 34" src="https://github.com/flutter/flutter/assets/53122008/59966e8d-36dd-4c62-ae8d-020ce1e743b8">

If so, this could be achieved. Also if you are referring to creating text with inline images, I see there is a package you could use in achieving that https://pub.dev/packages/drop_cap_text. If I'm misinterpreting this, kindly provide more information on this (if possible screenshots).
Thank you!
