### ISSUE TITLE
Better error messages for error codes in Google Sign-In package

### ISSUE THREAD

**Issue by songyang-dev** [flutter/flutter#136429]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

When Google Sign-In fails with an exception, the console gives error codes. It would be nice to get some messages about what they mean. For example, I frequently get `com.google.android.gms.common.api.ApiException: 10` when my Firebase is not working properly. 

### Proposal

Looking at StackOverflow can give you a very wide range of reasons. I'd like the error message itself to give a bit more clue about what is going on. This way, I can speed up the debugging processing by narrowing the possibilities.

**Comment by darshankawar** [comment]
Thanks for the report @songyang-dev 
There's a similar issue open but for iOS platform: https://github.com/flutter/flutter/issues/32441
Can you check that and see if it'll be ok to follow-up in that issue for your use case and proposal ? Or you are specifically looking for better error handling on Android ?
