### ISSUE TITLE
DevTool converting a model to Map<String, dynamic> when selecting [Toggle select widget mode].

### ISSUE THREAD

**Issue by muhammadkamel** [flutter/flutter#136427]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I have a model for product and using Go Router for naviagtion and when I navigate to Product Screen and open DevTool and selecting [Toggle select widget mode], the model GoRouter state changed to Map<String, dynamic>.

### Expected results

```
GoRoute(
      path: Routes.product.withSlash,
      name: Routes.product,
      builder: (context, state) {
        log("${state.extra.runtimeType}state.runtimeType");

        final product = state.extra as Product;
        return ProductScreen(product);
      },
    ),
```

### Actual results

[log] _$ProductImplstate.runtimeType
[log] _$ProductImplitem.runtimeType
[log] _$ProductImplstate.runtimeType
[log] _$ProductImplitem.runtimeType
[log] _$ProductImplstate.runtimeType
[log] _Map<String, dynamic>state.runtimeType
[log] _Map<String, dynamic>state.runtimeType
[log] _Map<String, dynamic>state.runtimeType
[log] _Map<String, dynamic>state.runtimeType

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Flutter (Channel stable, 3.13.7, on macOS 14.0 23A344 darwin-arm64, locale en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.83.1)
[✓] Connected device (3 available)
[✓] Network resources

**Comment by darshankawar** [comment]
Thanks for the report @muhammadkamel 
You seem to be hitting https://github.com/flutter/flutter/issues/99099, so please follow-up in it for further updates.
Closing this as a duplicate.

**Comment by muhammadkamel** [comment]
<img width="1435" alt="Screenshot 2023-10-19 at 1 12 52 AM" src="https://github.com/flutter/flutter/assets/17657941/804e9a8b-56ed-4385-a393-f14f03ee9001">

**Comment by muhammadkamel** [comment]
I attempted to use the Go Router Builder, but I'm still facing an issue with the DevTool when I activate the "Toggle Select Widget mode."
