### ISSUE TITLE
Hotjar capabilities

### ISSUE THREAD

**Issue by foo-fetchpet** [flutter/flutter#136426]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Problem Statement: I am trying to have session replay in both App and Web. Traditionally, tools like Hotjar, CrazyEgg, Insightech are used to record user sessions for replay and other summarisation purposes. They all use utilise the dom which Flutter doesn't use. Therefore, these tools don't work particularly well with Flutter built apps / web pages.

### Proposal

Desired Outcome: A library / tool that allows us to record user sessions to analyse service issues / customer journey / customer interactions. @domesticmouse

**Comment by darshankawar** [comment]
@foo-fetchpet 
Can you take a look at [this](https://github.com/flutter/flutter/issues/129098) issue and check if it resembles your case and proposal ?

**Comment by domesticmouse** [comment]
IIUC that issue is largely the same use case. @foo-fetchpet can add additional color.

**Comment by darshankawar** [comment]
Closing this in favor of https://github.com/flutter/flutter/issues/129098. Please follow-up in that issue for further updates. You may share your findings in that issue for better tracking.
