### ISSUE TITLE
height on the new DropdownMenu(Material 3)

### ISSUE THREAD

**Issue by rafaelbenedetti1** [flutter/flutter#136407]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I was using a dropdown button to show my selectable items, but now i'm using the new dropdown menu from Material 3, butt is not possible to set a height, only a width.

### Proposal

![image](https://github.com/flutter/flutter/assets/86314804/ba2dc1a4-38cd-4554-af16-111910b21683)

**Comment by huycozy** [comment]
Hi @rafaelbenedetti1 
There is a known issue at #135903 that proposed the same thing initially.

In case you expect to increase its height, you can increase inputDecorationTheme's contentPadding. 

But if you expect to decrease the height (smaller than the current default height), please take a look at my [comment](https://github.com/flutter/flutter/issues/135903#issuecomment-1748014507) that leads to the proposal for `Optional padding for DropdownMenu's leadingIcon and trailingIcon`. 

Closing this as a duplicate. Please follow up on #135903 for updates.
