### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by tshiamo-masilo** [flutter/flutter#136456]
_flutter.renderFrameWithRasterStats: (-32000) Failed to render the last frame with raster stats. Rasterizer does not hold a
valid last layer tree. This could happen if this method was invoked before a frame was rendered
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1822:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2366:21)
#2      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:2337:14)
#3      VmService.callMethod (package:vm_service/src/vm_service.dart:2319:12)
#4      FlutterVmService.callMethodWrapper (package:flutter_tools/src/vmservice.dart:529:28)
#5      FlutterVmService.renderFrameWithRasterStats (package:flutter_tools/src/vmservice.dart:629:49)
#6      ResidentHandlers.debugFrameJankMetrics (package:flutter_tools/src/resident_runner.dart:718:35)
<asynchronous suspension>
#7      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1821:7)
<asynchronous suspension>

Application finished.

Oops; flutter has exited unexpectedly: "_flutter.renderFrameWithRasterStats: (-32000) Failed to render the last frame with
raster stats. Rasterizer does not hold a valid last layer tree. This could happen if this method was invoked before a frame
was rendered".
A crash report has been written to D:\Flutter apps\flutterversion\flutter_01.log.

**Comment by dam-ease** [comment]
Hi @tshiamo-masilo. Thanks for filing this. I see there is an open issue with similar logs https://github.com/flutter/flutter/issues/132169. Can you follow up on this for updates.
Closing this in favor of the already open issue, if you disagree, please comment and I’ll reopen this.
