### ISSUE TITLE
Coordinate a stable release of pkg:web (v0.3.0) with next stable release of Flutter

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#136405]
Right now, there are packages in `flutter` that pin pre-release versions of `pkg:web`. We'll want to coordinate releasing the non-beta of pkg web (v0.3.0) with Flutter packages before the next release!

- [x] https://github.com/dart-lang/web/pull/85
- [x] Publish
- [x] Roll pkg:web into Flutter @ master - part of https://github.com/flutter/flutter/pull/132445
- [x] Cherry-pick to flutter stable

**Comment by srujzs** [comment]
The cherry-pick was picked onto beta (which will become 3.2 stable), so this is done right?

**Comment by kevmoo** [comment]
Going to double-check locally...but I think so!

**Comment by kevmoo** [comment]
Let's keep this open until `flutter-3.16-candidate.0` lands in beta!

**Comment by itsjustkevin** [comment]
This landed in https://github.com/flutter/flutter/releases/tag/3.16.0-0.4.pre
