### ISSUE TITLE
BottomNavigationBar items become white when more than 3 items are present

### ISSUE THREAD

**Issue by DirkWillem** [flutter/flutter#13642]
## Steps to Reproduce

When adding more than 3 items in a `BottomNavigationBar`, all items turn white, and are unreadable on the light-gray background. Also, the active item is also white, and not the provided `fixedColor`. A minimal code sample can be found [here](https://gist.github.com/DirkWillem/454f0fa60ede93a6cb40f0208a291e20)

Also see the following images:

<img width="545" alt="schermafbeelding 2017-12-17 om 20 52 39" src="https://user-images.githubusercontent.com/3536557/34083181-492a2b8c-e36c-11e7-8531-5c56061aecda.png">

<img width="545" alt="schermafbeelding 2017-12-17 om 20 52 50" src="https://user-images.githubusercontent.com/3536557/34083183-4ace4edc-e36c-11e7-8048-88ebec838cda.png">

## Logs

N/A

## Flutter Doctor
```
[✓] Flutter (on Mac OS X 10.13.1 17B1003, locale nl-NL, channel alpha)
    • Flutter at /Users/dirk/Developer/flutter/sdk
    • Framework revision 8f65fec5f5 (5 days ago), 2017-12-12 09:50:14 -0800
    • Engine revision edaecdc8b8
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.d8ae797298c3a6cf8dc9f4558707bd2672224d3e

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /Users/dirk/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-26, build-tools 26.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3)
    • Flutter plugin version 20.0.3
    • Dart plugin version 173.3727.108

[✓] Connected devices
    • iPhone X • 9500EA8E-1292-4223-BFFF-1B2134D5C47C • ios • iOS 11.2 (simulator)
```

**Comment by xster** [comment]
cc @HansMuller, I vaguely remember seen an older bug about this

**Comment by flyou** [comment]
when use BottomNavigationBarType.fixed that ok ，but when use BottomNavigationBarType.shifting that wrong

**Comment by wiltwitt** [comment]
I too have this problem.  anyone know how to fix this?

**Comment by chusmf** [comment]
same problem to me

**Comment by Hixie** [comment]
I have added this to our list of things to look at later this year. We would be happy to review patches if anyone has the opportunity to look at the code and figure out what's going on before we get to it, though.

**Comment by HansMuller** [comment]
When more than 3 BottomNavigationBar items are provided the type, if unspecified, changes to `BottomNavigationBarType.shifting` per https://docs.flutter.io/flutter/material/BottomNavigationBar/BottomNavigationBar.html. This bit of information should be highlighted in the class's doc. It's easy to overlook where it is (I overlooked it).

When the BottomNavigationBar's type is `BottomNavigationBarType.shifting` the items text and icons are rendered in white, via DefaultTextStyle and IconTheme. It's assumed that their`BottomNavigationBarItem.backgroundColor` will be specified as a contrasting color. This is obviously confusing.

The overall idea with `shifting` type bottom navigation bars is that each item will have a different background color (that contrasts with white), since that color will become the color of the entire navigation bar, when the item is selected.

The doc for BottomNavigationBar, and NavigationBarItem needs to be improved.

**Comment by wiltwitt** [comment]
@HansMuller  Thanks, that worked!

**Comment by tygryk** [comment]
@HansMuller, kudos!

**Comment by eshinkawa** [comment]
```
bottomNavigationBar: BottomNavigationBar(
          type: BottomNavigationBarType.fixed,
```

**Comment by ThinkDigitalRepair** [comment]
Am I the only one that thinks that it shouldn't change behavior based on the number of tabs automatically?

**Comment by bachtiaryayan** [comment]
thank you 👍

**Comment by Morosko** [comment]
What do I do, if I don't want the icons to be white, yet it should have the behavior of shifting?

**Comment by mliitfall** [comment]
Why don't just make the default type .fixed?

**Comment by JPM84** [comment]
I know this issue has been closed but it still feels like a bug even though the documentation has been nicely updated.
I'd suggest making fixed the default or fixing the behavior of BottomNavigationBarType.shifting with four items.

**Comment by augustoximenes** [comment]
bottomNavigationBar: BottomNavigationBar(
        type: BottomNavigationBarType.fixed,

**Comment by augustoximenes** [comment]
`bottomNavigationBar: BottomNavigationBar(
        type: BottomNavigationBarType.fixed,`

**Comment by speedynik** [comment]
I provided the " backgroundColor" agrument for each "BottomNavigationBarItem" and the problem is solved.

**Comment by SilvaEngComp** [comment]
Eu consegui resolver o problema inserindo a propriedade showUnselectedLabels: true, no BottomNavigationBar

return new BottomNavigationBar(

      showUnselectedLabels: true,

      items: <BottomNavigationBarItem>[...

**Comment by Mahn00rMalik** [comment]
what is we don't want the behavior to be shifting if we have more than three items. Is there any work around for it ?

**Comment by SharkLib** [comment]
add  showUnselectedLabels:true to BottomNavigationBar
add backgroundColor: Colors.blue to BottomNavigationBarItem
Then all shown

**Comment by Quiqueitc** [comment]
> ¿Soy el único que piensa que no debería cambiar el comportamiento en función del número de pestañas automáticamente?
> No me parece intuitivo esperar un comportamiento diferente.

I think the same

**Comment by errorsolve** [comment]
[[Solved] Flutter BottomNavigationBar not working with more than three items](https://fluttercorner.com/flutter-bottomnavigationbar-not-working-with-more-than-three-items/)
