### ISSUE TITLE
problem in generating signed apk

### ISSUE THREAD

**Issue by mariam-wahba** [flutter/flutter#136459]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

what can cause this msg when generating a signed apk "APK(s) generated successfully for module 'android.app.main' with 1 build variant: Build variant 'release': locate or analyze the APK" and why??

why i don't get a 0 build variant message??

### Actual results

i need explanation in details

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by darshankawar** [comment]
@mariam-wahba 
This doesn't seem to be specific to Flutter and could be related to Android studio + gradle config / setup.
Check [this](https://stackoverflow.com/questions/69408222/android-studio-generate-signed-apks-broke) and see if it helps in your case or not. Also, you need to raise these type of issues / questions on support channels like StackOverflow.

Closing from here, as this is neither a bug report or a feature request.
