### ISSUE TITLE
Performing “hot reload” and “Hot restart” in Flutter 3.13.x on macOS M1 Pro Sonoma version is experiencing exceptionally slow performance

### ISSUE THREAD

**Issue by superorange** [flutter/flutter#136464]
### Is there an existing issue for this?

- [X] I have searched the [existing infra issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-infra)

### Type of Request

bug

### Infrastructure Environment

LUCI, Github, Cocoon scheduler, Autosubmit, etc...

### What is happening?

I updated my M1 Pro computer to the Sonoma version and upgraded Flutter to 3.13.7. When I initially run the flutter program in iPhone 14 Pro simulator, it's fast. However, when I perform a 'hot reload' or 'hot restart' it becomes exceptionally slow, often taking several tens of seconds or getting stuck with no response for minutes.
<img width="847" alt="image" src="https://github.com/flutter/flutter/assets/49134865/d995c385-470d-4f55-8912-5bce405e47c3">

### Steps to reproduce

Step 1: flutter create test_app && cd test_app 
Step 2: flutter pub get
Step 3: flutter run -d 
Step 3: operation Hot reload (R)

### Expected results

I hope for both Hot reload and Hot restart to be fast

**Comment by huycozy** [comment]
Hi @superorange 
Could you open Activity Monitor and observe if Simulator or Dart process consumes too much CPU/RAM? Does the issue occur every time you do `Hot reload`/`Hot restart`?
