### ISSUE TITLE
[Linux] Verify GTK4 can render to multiple windows using 1 GL context

### ISSUE THREAD

**Issue by loic-sharma** [flutter/flutter#136400]
## Background

On Windows we plan to use a single GL context to render to multiple windows: for each view, the engine will request a framebuffer from the Windows embedder to render into. The Windows embedder will then use that framebuffer to present to a surface.

Unfortunately, this approach does not work on GTK 3 (which is what the Linux embedder uses).

## Work

We are currently investigating migrating the Linux embedder to GTK 4. GTK 4 *might* allow us to use a single GL context to render to multiple windows. We should verify this by creating a simple GTK 4 prototype app (without Flutter) that renders to multiple windows using a single GL context.

/cc @robert-ancell

**Comment by robert-ancell** [comment]
I think I've got this case working in https://github.com/robert-ancell/gtk4-multi-render - @loic-sharma please see if this looks right to you.

**Comment by m-theis** [comment]
If GTK is getting upgraded, should we maybe think about changing it in a way that it becomes possible to build without a dependency on GTK at all? This is basically what the custom embedders https://github.com/ardera/flutter-pi, https://github.com/sony/flutter-elinux do, isn't it?

**Comment by loic-sharma** [comment]
@robert-ancell Looks perfect, thank you for verifying this!

@m-theis We haven't committed to upgrading to GTK4 yet. Before moving forward, we'll create a design document. This would be an interesting conversation to have on that design document.

**Comment by m-theis** [comment]
@loic-sharma Thanks, alright! Yea I think support for embedded devices could play a big part in this discussion (going to GTK4 as well as making a non-GTK build possible would be big step towards embedded)

**Comment by jwinarske** [comment]
I'm putting together two proposals myself around this topic:
1. Make GTK an optional component in Linux GTK
2. Make common embedder code for Windows and Linux (no glib)

If I were clean room building this having the most overlap between the platforms would be the primary goal.  GTK is not a requirement for Linux (it's a choice/preference), and is very much the exception among the other platforms.

I think proposal two should be the long term strategy.

**Comment by m-theis** [comment]
@jwinarske if we can help you with that, let us know!
