### ISSUE TITLE
ResizeImage should make clear in its documentation that the width represents the physical pixels and not the logical pixels

### ISSUE THREAD

**Issue by stephane-archer** [flutter/flutter#136508]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

ResizeImage should make clear in its documentation that the width represents the physical pixels and not the logical pixels
```
      return LayoutBuilder(builder: (context, constraints) {
        return Image(
            image: ResizeImage(
          FileImage(File(pathRefImage)),
          width:
              (constraints.maxWidth * MediaQuery.of(context).devicePixelRatio)
                  .toInt(),
        ));
```

### Proposal

ResizeImage should make clear in its documentation that the width represents the physical pixels and not the logical pixels

**Comment by nate-thegrate** [comment]
Re-opening this one, since unfortunately there are still some inaccuracies in the docs.

https://github.com/flutter/flutter/pull/154212#issuecomment-2438118356
