### ISSUE TITLE
Rasterization jank

### ISSUE THREAD

**Issue by lukehutch** [flutter/flutter#136597]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I am seeing significant jank in my Flutter app, which seems to be due to large variance in rasterization time. Every frame should take the same work to rasterize -- I'm scrolling through an Instagram-grid-like view of images, all of which have been pre-scaled to the same physical size before rasterization. 

The jank seems to be happening in `SurfaceFrame::Submit`, after `GrDirectConext::flushAndSubmit` has completed (see screenshots below). There isn't any more fine-grained profiling information available (even with all profile options enabled) to debug what is actually taking the time.

Is there anything I can do to debug this further?

I'm not using any custom shaders, or anything fancy. I'm not running Impeller yet (it was buggy on Android last time I tested it, a month or two ago).

### Expected results

No jank

### Actual results

Jank

### Code sample

I can't share the code, sorry.

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

Here is an example of a janky frame:

![image](https://github.com/flutter/flutter/assets/811305/b1259107-57e8-4b9d-9fe9-e9e877f25c50)
![image](https://github.com/flutter/flutter/assets/811305/ea8821a9-2d52-436e-adde-d7622fef101e)

I just noticed that the janky frame is running `PlatformVsync` in the UI thread, whereas the non-janky frames are running `VsyncProcessCallback`:

![image](https://github.com/flutter/flutter/assets/811305/6bd2e3f7-7d60-4fa2-94ff-48a16109b0c0)

</details>

### Logs

N/A

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
$ flutter doctor -v
[✓] Flutter (Channel beta, 3.16.0-0.2.pre, on Fedora Linux 38 (Workstation Edition) 6.5.6-200.fc38.x86_64, locale en_US.utf8)
    • Flutter version 3.16.0-0.2.pre on channel beta at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fe6553b689 (3 days ago), 2023-10-11 19:07:11 -0700
    • Engine revision 249cc9b86c
    • Dart version 3.2.0 (build 3.2.0-210.2.beta)
    • DevTools version 2.28.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/luke/Android/Sdk
    • Platform android-UpsideDownCake, build-tools 33.0.1
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 16.0.6 (Fedora 16.0.6-3.fc38)
    • cmake version 3.27.7
    • ninja version 1.11.1
    • pkg-config version 1.8.0

[✓] Android Studio (version 2022.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 73.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.83.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.74.0

[✓] Connected device (4 available)
    • Pixel 7 Pro (mobile)       • 29161FDH300BLP • android-arm64  • Android 13 (API 33)
    • sdk gphone x86 64 (mobile) • emulator-5554  • android-x64    • Android 13 (API 33) (emulator)
    • Linux (desktop)            • linux          • linux-x64      • Fedora Linux 38 (Workstation Edition) 6.5.6-200.fc38.x86_64
    • Chrome (web)               • chrome         • web-javascript • Google Chrome 118.0.5993.70

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by jonahwilliams** [comment]
> I am seeing significant jank in my Flutter app, which seems to be due to large variance in rasterization time. Every frame should take the same work to rasterize

The same amount of work doesn't really imply the same amount of time though, as your application is running on a device with limited CPUs/memory that is doing other things too. In this particular case, what I'd bet is that the thread running the raster workload was either moved to a slow core or interrupted so the phone could do other work. Keep in mind that one of these "other things" can actually be running the Dart profiler. IN a pinch, you can turn on the performance overlay via the MaterialApp options and run in release mode to confirm.

https://perfetto.dev/ has an online tracer you can run that will show everything your phone is doing (Android only). This includes slow/fast core scheduling and when interruptions occured.

**Comment by lukehutch** [comment]
> In this particular case, what I'd bet is that the thread running the raster workload was either moved to a slow core or interrupted so the phone could do other work.

@jonahwilliams I'd be more likely to believe this if the jankiest frames didn't have a totally different profile trace than non-janky frames. As I pointed out:

> I just noticed that the janky frame is running `PlatformVsync` in the UI thread, whereas the non-janky frames are running `VsyncProcessCallback`.

Any idea of the difference here?

**Comment by darshankawar** [comment]
Labeling this for further discussion and tracking.

**Comment by chinmaygarde** [comment]
There isn't enough actionable information here to make progress. We'd want a reduced test case of the app with the slowdown to explain whats happening here. There are additional options like `--trace-skia` or other system tracing like with Perfetto that @jonahwilliams linked. But it is also possible that we'd want to get a GPU trace to see if that is causing us to block on acquisition of the next swapchain image.  The CPUs will be idling in this case.

So there are really too many variables here and we are guessing at this point without a reduced test case. Closing as un-actionable but please re-open if you have one.
