### ISSUE TITLE
ResizeImage doesn't work with AssetImage

### ISSUE THREAD

**Issue by stephane-archer** [flutter/flutter#136505]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

ResizeImage doesn't work with AssetImage
With the following code:
````
ResizeImage(
            const AssetImage("assets/imgs/Spinner.gif"),
            width: 360)
````
I have the following message:
````
Image assets/imgs/Spinner.gif - Resized(360×null) has a display size of 489×275 but a decode size of 800×800, which uses an additional 2632KB (assuming a device pixel ratio of 2.0).

Consider resizing the asset ahead of time, supplying a cacheWidth parameter of 489, a cacheHeight parameter of 275, or using a ResizeImage.
````

### Expected results

the decode size should not be 800x800

### Actual results

````
Image assets/imgs/Spinner.gif - Resized(360×null) has a display size of 489×275 but a decode size of 800×800, which uses an additional 2632KB (assuming a device pixel ratio of 2.0).

Consider resizing the asset ahead of time, supplying a cacheWidth parameter of 489, a cacheHeight parameter of 275, or using a ResizeImage.
````

### Code sample

````
ResizeImage(
            const AssetImage("assets/imgs/Spinner.gif"),
            width: 360)
````

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.13.4, on macOS 13.4.1 22F770820d darwin-x64, locale en-GB)
    • Flutter version 3.13.4 on channel stable at /Users/fractale/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 367f9ea16b (4 weeks ago), 2023-09-12 23:27:53 -0500
    • Engine revision 9064459a8b
    • Dart version 3.1.2
    • DevTools version 2.25.0

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/fractale/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.4.1 22F770820d darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 118.0.5993.70

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

**Comment by darshankawar** [comment]
Thanks for the report @stephane-archer 
`ResizeImage` decodes the image with the specified dimensions instead of the native image size.
Taking a hint from the message you are getting, specially `devicePixelRatio` and since you are passing width too, can you try by passing `width` (360) x devicePixelRatio to `ResizeImage` and check if it helps in your case or not ?

**Comment by stephane-archer** [comment]
Here is the full code using `devicePixelRatio`
```
AspectRatio(
          aspectRatio: mainPreviewProvider.aspectRatio,
          child: FadeInImage(
            image: ResizeImage(
              FileImage(
                File(_pathOutput),
              ),
              width: (constraints.maxWidth *
                      MediaQuery.of(context).devicePixelRatio)
                  .toInt(),
            ),
            placeholder: ResizeImage( const AssetImage("assets/imgs/Spinner.gif"),
              width: (constraints.maxWidth *
                      MediaQuery.of(context).devicePixelRatio)
                  .toInt(),
            ),
          ),
        )
```
I still have the same error message:
```
════════ Exception caught by painting library ══════════════════════════════════
Image assets/imgs/Spinner.gif - Resized(265×null) has a display size of 265×149 but a decode size of 800×800, which uses an additional 3127KB (assuming a device pixel ratio of 2.0).

Consider resizing the asset ahead of time, supplying a cacheWidth parameter of 265, a cacheHeight parameter of 149, or using a ResizeImage.
```
the ResizeImage on FileImage works perfectly but not on the const AssetImage.
Also, the documentation should make it clear that ResizeImage uses physical pixels and not logical pixels like most flutter widgets.

**Comment by darshankawar** [comment]
Thanks for the update @stephane-archer 
Does this error only occur with .gif or with other extensions too ? like jpeg, jpg or png ?


> the documentation should make it clear that ResizeImage uses physical pixels and not logical pixels like most flutter widgets.

I see that you have already raised an issue for this.

**Comment by stephane-archer** [comment]
it only occurs with .gif, png has no issue
Here is the gif:
![Spinner](https://github.com/flutter/flutter/assets/2981437/1bc8ee3e-712f-4e55-837b-382181ce860b)

**Comment by darshankawar** [comment]
> it only occurs with .gif, png has no issue

Thanks for the update. I believe you are hitting https://github.com/flutter/flutter/issues/90804, so please follow-up in it for further updates. Closing this as a duplicate.
