### ISSUE TITLE
Windows time API too inaccurate for AutoResetWaitableEventTest.Timeouts test?

### ISSUE THREAD

**Issue by mravn-google** [flutter/flutter#13654]
https://build.chromium.org/p/client.flutter/builders/Windows%20Engine/builds/1030/steps/Test%20FXL/logs/stdio

Has allegedly been seen more than once.

**Comment by goderbauer** [comment]
Failure message:
> e:\b\build\slave\windows_engine\build\src\garnet\public\lib\fxl\synchronization\waitable_event_unittest.cc(138): error: Expected: (elapsed) >= (timeout - kTimeoutTolerance), actual: 9322341 vs 9500000

I believe the Windows' time API we are using is not that accurate.

@bkonyi FYI.

**Comment by Hixie** [comment]
I haven't heard anyone complaining about this recently. I am going to guess this is no longer an issue.
