### ISSUE TITLE
Too many images in the stack cause ui to block

### ISSUE THREAD

**Issue by fangkyi03** [flutter/flutter#136569]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

When the page needs to use the background image and the background image is loaded over the network

### Expected results

Hopefully, it won't block the ui so it can display properly

### Actual results

Blocked ui needs to wait for the image to load before normal display

### Code sample

```dart
Stack(
        children: [
          image(
                url: background.value,
              ),
          Positioned(
            left: 0,
            right: 0,
            top: 0,
            bottom: 0,
            child: renderIcon(),
          )
        ],
      )
```
If the image content is large or the image server takes a long time to return, Positioned cannot be rendered, and ui is blocked until the image is fully loaded

### Flutter Doctor output

[!] Flutter (Channel stable, 3.13.6, on macOS 14.0 23A344 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.13.6 on channel stable at /Users/mozhu/Desktop/flutter
    ! Upstream repository https://gitee.com/fangkyi03/flutter.git is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to https://gitee.com/fangkyi03/flutter.git to dismiss this error.
    • Framework revision ead455963c (2 weeks ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/mozhu/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.83.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 117.0.5938.132
    ! Error: Browsing on the local area network for L. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this
      Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

**Comment by huycozy** [comment]
Hi @fangkyi03 
Please provide a complete and minimal sample code so that we may verify this. What is the image size that causes the UI to be blocked?

And which platform are you seeing this issue? Please share the device information as well (OS, model)

**Comment by ZTXBEST** [comment]
me too! In the mixed editing project, after the app starts, the first page  build is blocked, killing the process and running it again is enough

**Comment by fangkyi03** [comment]
> Hi @fangkyi03 Please provide a complete and minimal sample code so that we may verify this. What is the image size that causes the UI to be blocked?
> 
> And which platform are you seeing this issue? Please share the device information as well (OS, model)
> 
> 
> @fangkyi03 请提供一个完整的和最小的示例代码，以便我们可以验证这一点。导致UI被阻止的图像大小是多少？
> 
> 你在哪个平台看到这个问题？请同时分享设备信息（操作系统、型号）

Of course, the server is not very good either, so it takes about 7 seconds for this image to return and during this time the page has been blocked

**Comment by fangkyi03** [comment]
I'm not sure if this is due to a large image that needs to be parsed or if the server is blocking because it hasn't returned and has been waiting, but theoretically neither of these reasons should be a reason to block the display of other components of the page

**Comment by huycozy** [comment]
@fangkyi03 Please try to provide all information indicated at https://github.com/flutter/flutter/issues/136569#issuecomment-1763745667 so we can verify this issue (complete sample code, affected platforms, devices info)
