### ISSUE TITLE
Could not parse java version from: java 21 2023-09-19 LTS Java(TM) SE Runtime Environment (build 21+35-LTS-2513) Java HotSpot(TM) 64-Bit Server VM (build 21+35-LTS-2513, mixed mode, sharing)

### ISSUE THREAD

**Issue by safalgautam12** [flutter/flutter#136583]

**Comment by NileshChoundikar** [comment]
Flutter doesn’t support java 21 . Try with Java 17

**Comment by NileshChoundikar** [comment]
> No description provided.

Flutter doesn’t support java 21 . Try with Java 17

**Comment by huycozy** [comment]
Thanks for the report! 

This is a known issue being tracked at https://github.com/flutter/flutter/issues/135402. Closing this issue as a duplicate, so please follow up on it for further updates.
