### ISSUE TITLE
Investigate why flutter-devicelab-mac-45 is quarantined 

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#136549]
### Is there an existing issue for this?

- [X] I have searched the [existing infra issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-infra)

### Type of Request

bug

### Infrastructure Environment

Devicelab

### What is happening?

Bot [flutter-devicelab-mac-45](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-45) is quarantined and shows error:

```
Device doctor tool error: b'Unhandled exception:\nidevice_id not found.\n#0 fail (package:device_doctor/src/utils.dart:33)\n#1 getMacBinaryPath (package:device_doctor/src/utils.dart:161)\n<asynchronous suspension>\n#2 IosDeviceDiscovery.deviceListOutput (package:device_doctor/src/ios_device.dart:53)\n<asynchronous suspension>\n#3 IosDeviceDiscovery.discoverDevices (package:device_doctor/src/ios_device.dart:45)\n<asynchronous suspension>\n#4 IosDeviceDiscovery.checkDevices (package:device_doctor/src/ios_device.dart:62)\n<asynchronous suspension>\n#5 main (file:///opt/s/w/ir/x/w/cocoon/device_doctor/bin/main.dart:79)\n<asynchronous suspension>\n'
```

Perhaps cause by https://github.com/flutter/flutter/issues/136382?

I need this device to run tests for macOS 13 for https://github.com/flutter/flutter/issues/134736.

### Expected results

I expect mac-45 to be working and iOS device to be connected

**Comment by PuzzleTakX** [comment]
It seems like there might be an issue with the Devicelab infrastructure, specifically with Bot flutter-devicelab-mac-45. The error message indicates that the 'idevice_id' is not found, which may be causing the problem. However, I don't have access to real-time information on specific issues or their resolutions.

I would recommend checking the issue tracker or contacting the relevant team responsible for Devicelab or Flutter for more information and updates on this specific issue. You can also consider searching for similar issues that may have been reported by others for potential solutions.

**Comment by vashworth** [comment]
https://github.com/flutter/flutter/issues/136550 seems to be same problem, different bot

**Comment by ricardoamador** [comment]
@kentnguyen99 can you take a look at https://github.com/flutter/flutter/issues/136550 and see if this is addressed with the same fix as shown there? Thank you!

**Comment by kentnguyen99** [comment]
@ricardoamador Problem has been resolved and fixed on mac-45.
https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-45

**Comment by ricardoamador** [comment]
Awesome! Thank you @kentnguyen99 !

**Comment by ricardoamador** [comment]
Can this be closed @kentnguyen99 ?

**Comment by kentnguyen99** [comment]
Problem has been resolved and fixed by Godofredo. This ticket related to https://github.com/flutter/flutter/issues/136550#issuecomment-1762365391
