### ISSUE TITLE
Add "postsubmit_overrides" to build config json spec

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#136570]
The purpose of this feature would be to support configurations that need e.g. different `gn` flags between pre- and post-submit.

@godofredoc I will wait on making changes to the goma setup for the builds we discussed until we can write these in the build configs.

**Comment by zanderso** [comment]
The migration to RBE is blocked on this issue, which (AFAIK) must be completed in Q4, so I will bump this up to P1.

**Comment by zanderso** [comment]
This will still be needed to keep presubmit cycle times low. Completing the migration to reclient is still blocked on this.

**Comment by godofredoc** [comment]
Recipes change: https://flutter-review.googlesource.com/c/recipes/+/57022

**Comment by godofredoc** [comment]
Closing as completed!!!
