### ISSUE TITLE
[CP] [ios] Link PlatformView back to semantics tree

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#136552]
### Issue Link

flutter/flutter#135504

### Commit Hash

250daadbca517677317277f314ea2a40568eb345

### Target

stable

### PR Link

https://github.com/flutter/engine/pull/46900

### Changelog Description

Fix a regression on iOS where the voice over traversal stops after visiting a PlatformView.

### Impacted Users

end-customers on iOS

### Impact Description

voice over not working properly

### Workaround

No

### Risk

low

### Test Coverage

yes

### Validation Steps

Sample app in https://github.com/flutter/flutter/issues/135504

**Comment by itsjustkevin** [comment]
@vashworth could you take a look at this cherry-pick and attach the cp: approved label if you agree?
