### ISSUE TITLE
Flutter should perform project validation checks

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#13662]
There's a certain class of project-specific issues that are easily detectable by tooling, but that we don't currently automatically check for. `flutter doctor` performs system-wide validation of Flutter dependencies (Xcode/IntelliJ/Android SDK version, homebrew dependencies, etc.) but doesn't currently do any project-specific checks.

It would be useful if, when invoked in a Flutter project directory, `flutter doctor` performed an additional set of project-specific checks. For example, for iOS builds, ensure that the project architectures are set to `arm64` rather than `$(ARCHS_STANDARD)`, or that both `xcode_backend.sh`-powered build phases are enabled. 

Ideally, we'd also include a means to automatically fix the issue (with the user's permission), though that's a significantly trickier problem.

**Comment by xster** [comment]
Maybe #12983?

**Comment by cbracken** [comment]
Thanks -- somehow I completely failed to find that in my issues search. Closing as dupe of #12983.
