### ISSUE TITLE
InteractiveViewer blocks Gestures after zooming activity

### ISSUE THREAD

**Issue by osaxma** [flutter/flutter#136622]
### Steps to reproduce

1. Run the Sample Code provided below on MacOS 
2. Tap anywhere in the viewer (it should print `Tap Tap`). 
3. Using the trackpad on macOS:
  a. Pinch to zoom in (do it few even if fully zoomed in)
  b. Pinch to zoom out (again, do it few times even if fully zoomed out).
6. Tap again, and nothing would print.

Step three and four are important to keep zooming-in few times and zooming-out few times. See screen recording where you can observe at the end that the taps don't work even after I reset the scale to 1. 

### Expected results

I expect gesture detectors to receive hits. 

### Actual results

Gesture detector is blocked even after resetting the scale to 1. 

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [InteractiveViewer].

void main() => runApp(const InteractiveViewerExampleApp());

class InteractiveViewerExampleApp extends StatelessWidget {
  const InteractiveViewerExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('InteractiveViewer Issue')),
        body: const InteractiveViewerExample(),
      ),
    );
  }
}

class InteractiveViewerExample extends StatefulWidget {
  const InteractiveViewerExample({super.key});

  @override
  State<InteractiveViewerExample> createState() => _InteractiveViewerExampleState();
}

class _InteractiveViewerExampleState extends State<InteractiveViewerExample> {
  final controller = TransformationController();

  void resetZoom() {
    setState(() {
      controller.value = Matrix4.identity();
    });
  }

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () {
        print('Tap Tap');
      },
      child: Center(
        child: Column(
          children: [
            Center(
              child: TextButton(
                  onPressed: () {
                    resetZoom();
                  },
                  child: Text('Reset Zoom')),
            ),
            Expanded(
              child: InteractiveViewer(
                boundaryMargin: const EdgeInsets.all(20.0),
                transformationController: controller,
                minScale: 0.1,
                maxScale: 1.6,
                child: Container(
                  height: 1000,
                  width: 1000,
                  decoration: const BoxDecoration(
                    gradient: LinearGradient(
                      begin: Alignment.topCenter,
                      end: Alignment.bottomCenter,
                      colors: <Color>[Colors.red, Colors.orange, Colors.blue],
                      stops: <double>[0.0, 0.5, 1.0],
                    ),
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

Screenshots / Video demonstration

https://github.com/flutter/flutter/assets/46427323/4fe7118b-55fc-4618-8e90-c1fa18f33b84

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.6, on macOS 12.6 21G115 darwin-x64, locale en)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.83.1)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 1 category.

```

</details>

**Comment by dam-ease** [comment]
Hi @osaxma. Thanks for filing this. I see this seems similar to a currently open issue https://github.com/flutter/flutter/issues/134615. Can you confirm it is similar to the case you are describing here?

**Comment by osaxma** [comment]
Hi @dam-ease 

No, it does not appear to be the same. The issue I am having is that `GestureDetector` stops responding to events such as `onTap` after zooming-in and then zooming-out. 

I am not sure what is the cause -- it could be the trackpad or something else. I have only tested this on macOS while zooming by pinching on the trackpad.

**Comment by dam-ease** [comment]
Hi @osaxma. Thanks for your response. I can reproduce this on the latest `stable` channels but can't seem to reproduce on `master`, are you able to check this on the `master` channel?

**Comment by osaxma** [comment]
I was able to reproduce on latest `master` using the same example (first attempt, then i couldn't, then I hot reloaded few times and it happened again -- not sure what exactly triggers this behavior) 

```
Flutter 3.16.0-12.0.pre.132 • channel master •  on macOS 12.7 21G816 darwin-x64
Framework • revision 24530b8021 (24 minutes ago) • 2023-10-18 12:00:53 -0700
Engine • revision 0eff5d1918
Tools • Dart 3.3.0 (build 3.3.0-35.0.dev) • DevTools 2.28.1
```

https://github.com/flutter/flutter/assets/46427323/8e20883e-156e-4818-91ce-f57487093b57

**Comment by dam-ease** [comment]
Thanks for your response. I can see this on my end as well, on the latest `master` channel, it doesn't reproduce on the first attempt but after hot reload/hot restart a few times, I can reproduce this.

**Comment by gspencergoog** [comment]
Does this happen in release builds? (Desktop Triage)

**Comment by osaxma** [comment]
FYI: 

I believe that the root cause comes from `GestureDetector` -- I have filed a separate issue for that:

- https://github.com/flutter/flutter/issues/140730
