### ISSUE TITLE
[Impeller] Rework entity framework for easier and more composable optimizations.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#136667]
_Creating a stub issue from the discussion during the Impeller weekly on October 11, 2023. Adding some initial note on conversations with @bdero and others._

As we add additional optimizations to the entity framework, the need for a coherent framework for composable optimizations has become apparent. Today, these optimizations often step on each other and the code may get confusing and require a nuanced understanding of the rendering intent.

Some rough requirements:
* Modeled after `impeller::EntityPassDelegate` (and perhaps subsuming them), optimizations must be easy to reason about with their entire implementation confined to their own TU in a separate folder in the codebase (`//impeller/entity/optimization`).
* The optimization framework must have a separate affordance for determining the predicate.
  * This will allow fine grained control over how each optimization is enabled.
  * The predicate mechanism must allow us to ask and answer each of the following questions:
    * Allow controlling if we should bother determining whether an optimization is possible.
      * Flags and such would go here.
    * Allow determining whether the optimization is possible.
    * Allow making a go/no-go call on a possible optimization after consulting other optimizations that are also possible.
    * Some reference and prior art (in other domains) that may come in handy when thinking about such a framework:
      * [Gesture recognizers delegates](https://developer.apple.com/documentation/uikit/uigesturerecognizerdelegate?language=objc).
      * Compiler optimization passes.
      * `impeller::EntityPassDelegate`.
* The nomenclature must be clearly documented. Today, things like the coordinate spaces being in pass-space, coverage-space, screen-space, etc. gets hard to reason about. We can make up our own terminology if needed, but it needs to be documented (at go/impeller-coordinates perhaps).

Success of this optimization framework would mean the follow current and future optimizations would be effectively and clearly expressed using this framework.
* Opacity peephole.
* Pass elision.
* Pass collapsing.
  * In the presence of non-overlapping coverage.
  * Filters applied to entities that are contiguous but not overlapping.
* Draw call batching.
* Draw call re-ordering.

**Comment by jonahwilliams** [comment]
Closing as I don't believe we're going to do any more reworks to the entity frameworks. We seem to have sufficient optimizations for now, and for future optimizations we can determine if it is something that can be handled in the front end (display list) or during disaptching.
