### ISSUE TITLE
Study names of animation API classes (e.g. Curve)

### ISSUE THREAD

**Issue by appsforartists** [flutter/flutter#13669]
I was just perusing the docs and found this type:

https://docs.flutter.io/flutter/animation/Curve-class.html

It appears to define easing functions (which are sometimes called easing curves, because when plotted they often form a curved line).  This is an unfortunately ambiguous name - "curve" could also be interpreted as the arc that an object moves through in XY space.

I haven't looked thoroughly enough at the APIs to know if this is the right name, but perhaps `Easing` would be more accurate and less ambiguous.

Sorry to open an issue without a definitive recommendation, but I wanted to note this while it's fresh in my mind.

cc @sethladd @InMatrix

**Comment by InMatrix** [comment]
I've also seen this issue in the animation API UX study. P3 interpreted "curve" as the path of movement, when he saw the charts in the [Curves](https://docs.flutter.io/flutter/animation/Curves-class.html) doc.

**Comment by appsforartists** [comment]
This is probably part of a larger naming pass over the animation subsystem - it looked like `Curve` is used in other places like [`CurveTween`](https://docs.flutter.io/flutter/animation/CurveTween-class.html).  They should all change together.

**Comment by appsforartists** [comment]
`Interpolator` might also be a good alternative.  Some of these (like `interval`) aren't themselves curves.

**Comment by appsforartists** [comment]
I just checked with Eric Henry (Motion Lead for Material).  He agrees that `Easing` is a better choice than `Curve`.

**Comment by Hixie** [comment]
Changing this would be a massively breaking change, unfortunately. I don't think we can change the actual names. It would break lots of people's code.

We can definitely improve the docs for this though. They should be much clearer about this.

**Comment by appsforartists** [comment]
Is there a process for deprecating old APIs and replacing them with new ones in Flutter?  This seems like a thing you'd want to be able to do (independently of this particular issue).

**Comment by Hixie** [comment]
The process is https://flutter.io/design-principles/#handling-breaking-changes, but not mentioned there is that we try really hard not to break existing developers. We need a really good reason to make a change, usually correctness (without the change the code just doesn't work) or performance (the change allows us to make apps much faster). Making the API easier to use is important, don't get me wrong, but for an API that's been used for a year or more, it's hard to use that alone as justification for the change.

**Comment by appsforartists** [comment]
Thanks.

To minimize breaks and ensure a consistent story, I want some time to play with the current APIs before proposing a batch of animation API changes.  Afterwards, I'll go through the steps you linked to.

**Comment by Hixie** [comment]
Should we close this issue in the meantime?

**Comment by appsforartists** [comment]
I do think there's action to take here, but I probably won't be taking it right away.  As Tao mentioned, this has also come up in user testing.

I'm inclined to keep it open, but it's your issue tracker.

**Comment by Hixie** [comment]
If you plan to take action on this I'm happy to leave the bug open and assigned to you; what action would you like to take (whenever that is, doesn't have to be now)? :-)

**Comment by appsforartists** [comment]
I'll propose a name change, but I want to learn the animation APIs first.  If I'm proposing changes, I intend to do them with an understanding of the system (rather than thrashing the API with multiple uncoordinated changes).

**Comment by Hixie** [comment]
Ok. For the record, I don't think we'll be able to do a name change. We might be able to change the name if we find we also need to improve the API for more critical reasons like performance or correctness, but if the only reason is to make the API more usable, as described above, I don't think we'll be able to do the change.

**Comment by Hixie** [comment]
Filed https://github.com/flutter/flutter/issues/13737 for the docs improvements.

**Comment by appsforartists** [comment]
`CurvedAnimation` is even worse - it sounds like an arc move.

**Comment by appsforartists** [comment]
It looks like `AnimationController` should be called `Timeline`.

**Comment by Hixie** [comment]
Since we didn't make the change, we're probably not invested in doing it, so I'm going to close this bug. If someone does want to make this change (and follow our new breaking change policy) please file a new bug and a PR at the same time (no need to have the bug alone).

**Comment by InMatrix** [comment]
The new animated diagrams in this doc probably can sufficiently clarify what "curve" means in this context.
