### ISSUE TITLE
[google_maps_flutter] Unknown Map Id

### ISSUE THREAD

**Issue by veronikalaskova** [flutter/flutter#136612]
### Is there an existing issue for this?

- [X] I have searched the [existing package issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Apackage)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### What package does this bug report belong to?

google_maps_flutter

### What target platforms are you seeing this bug on?

iOS

### Have you already upgraded your packages?

No

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
 google_maps_flutter:
    dependency: "direct main"
    description:
      name: google_maps_flutter
      sha256: "24392ef192f3b00bcd93151375676805a9933574423a5bd5509a0ead2e8a4215"
      url: "https://pub.dev"
    source: hosted
    version: "2.2.5"
google_maps_flutter_ios:
    dependency: transitive
    description:
      name: google_maps_flutter_ios
      sha256: "3a69e04df77afb60587b5270baf43dc51f1c254c79f69ddf1d9546f758d9f709"
      url: "https://pub.dev"
    source: hosted
    version: "2.2.0"
```

</details>

### Steps to reproduce

Unable to reproduce on my device (iPhone 11 pro, running iOS 17.0.3)
Unable to reproduce when debugging, issue only present in production release of our app
Only found one mention of this error online (with no answers)

### Expected results

Should not error

### Actual results

Sentry log getting spammed by the same error "Map Id Unknown", different parts of google_maps_flutter code:
GoogleMapsFlutterIOS.updateTileOverlays
GoogleMapsFlutterIOS.updateMarkers
GoogleMapsFlutterIOS.updatePolygons
GoogleMapsFlutterIOS.updatePolylines
GoogleMapsFlutterIOS.updateCircles

All always with the same timestamp. 

This error has started popping up fairly recently (July 2023) without having made any changes to our codebase. Only affects iOS devices.
flutter version: 3.13.4
google_maps_flutter version: 2.2.5

### Code sample

<details><summary>Code sample</summary>

```dart
```

</details>

### Screenshots or Videos

<details>
<summary>Screenshots / Video demonstration</summary>

</details>

### Logs

<details><summary>Logs</summary>

```console
google_maps_flutter_ios.dart in GoogleMapsFlutterIOS._channel at line 58 within google_maps_flutter_ios
google_maps_flutter_ios.dart in GoogleMapsFlutterIOS.updateTileOverlays at line 362 within google_maps_flutter_ios
controller.dart in GoogleMapController._updateTileOverlays at line 152 within google_maps_flutter
google_map.dart in _GoogleMapState._updateTileOverlays at line 404 within google_maps_flutter
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console

```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @veronikalaskova but without a reproducible code sample or a pattern that leads to the error, would be difficult to make this issue actionable, so if you could provide either or it, would help to properly address the issue.
