### ISSUE TITLE
Document new package system

### ISSUE THREAD

**Issue by LarkAscending** [flutter/flutter#13663]
Update flutter.io/setup with the one-step install option. Keep the current long-form instructions (git clone, etc.) but make it clear they're secondary.

Update codelabs to use the short-form package system, replacing the long-form procedure.

/cc @gspencergoog

**Comment by Sfshaza** [comment]
This was fixed for beta 3. Also, the new codelabs refer to the Install page on flutter.io, so it's all good.

https://flutter.io/setup-macos/
