### ISSUE TITLE
[CP] Disable hardware buffer backed platform views rendering target

### ISSUE THREAD

**Issue by johnmccutchan** [flutter/flutter#136654]
### Issue Link

https://github.com/flutter/engine/pull/45430

### Commit Hash

6a13607008ed3461eebc529d7eda98bad676264c

### Target

stable

### PR Link

https://github.com/flutter/engine/pull/45430

### Changelog Description

Disables the ImageReader Platform Views render target (always use SurfaceTexture)

### Impacted Users

All Android users running Android >= 29.

### Impact Description

Visual glitches (partially rendered frames) in Android Platform Views (rendered via Texture Layer) on high frame rate phones.

### Workaround

No

### Risk

low

### Test Coverage

yes

**Comment by johnmccutchan** [comment]
Use this PR: https://github.com/flutter/engine/pull/46968

**Comment by itsjustkevin** [comment]
Updated the issue with the new cherry-pick PR.

@johnmccutchan could you update the descriptions in this cherry-pick request?  
1. `Issue Link` points the the abandoned Engine PR.
2. Descriptions are vague.

As this is a stable hotfix, we will point users back to this issue for context on the hotfix, leaving them without vital information.

**Comment by johnmccutchan** [comment]
Updated link and added more context.
