### ISSUE TITLE
[Impeller] Validation errors and no output for saveLayer with drawPaint broken again

### ISSUE THREAD

**Issue by flar** [flutter/flutter#136663]
This was originally filed as https://github.com/flutter/flutter/issues/135766 along with a suggested fix. The original fix did work at one point, but the test case is broken again on ToT due to another code change.

<details>
<summary>Example code</summary>

```
import 'dart:ui' as ui;

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'SaveLayer DrawPaint issue'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: SizedBox(
          width: 200,
          height: 200,
          child: CustomPaint(
            painter: _MyPainter(),
          ),
        ),
      ),
    );
  }
}

class _MyPainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    Paint savePaint = Paint()
      ..imageFilter = ui.ImageFilter.blur(sigmaX: 5, sigmaY: 5);
    canvas.saveLayer(null, savePaint);
    Paint paint = Paint()
      ..shader = ui.Gradient.linear(
        Offset.zero,
        const Offset(2, 2),
        <Color>[
          Colors.blue,
          Colors.green,
        ],
        null,
        TileMode.mirror,
      );
    canvas.drawPaint(paint);
    canvas.restore();
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) => true;
}
```
</details>

The code runs fine with Skia, but gets the validation errors and draws nothing with Impeller.

**Comment by flar** [comment]
Originally the problem was caused for all rendering operations and so when the fix in the earlier issue was submitted, it included a test case that used drawImage instead of drawPaint. The new problem seems to be that it only occurs for unbounded drawing content so the fact that the test case was using drawImage means it is not testing the unbounded case. The new problem only happens for unbounded cases like drawPaint, drawColor, or any other rendering operation that has an unbounded output.

The problem appears to be that the clip bounds are discarded when there is a filter due to an inability to reverse map the output rectangle to a filter's input rectangle. For bounded content, that just means that the entire content bounds are rendered to apply to the filter, but for drawPaint, the code attempts an unbounded layer which fails.

Commenting out this line of code can fix the validation errors, but obviously can produce bad output in other cases. This simply points out that `nullopt` is not the right result to fall back on...

https://github.com/flutter/engine/blob/c24f30343cf6506bda6a56b833e77461f299fd0c/impeller/entity/entity_pass.cc#L204

**Comment by jonahwilliams** [comment]
We fixed the image filter reverse bounds mapping issue in https://github.com/flutter/engine/pull/54604 

The cull rect itself is only a hint and won't determine saveLayer size.
