### ISSUE TITLE
[flutter_tools]customize systemTempDirectory

### ISSUE THREAD

**Issue by RelicOfTesla** [flutter/flutter#136631]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

The 'systemTempDirectory' can be customized through environment variables

There are too many directories in the '% tmp%/flutter_tools. xxxx' directory, and dozens of GB have not been automatically cleared.

It's too easy to fill up my Windows system disk. 

flutter_tools can customize a temporary directory for easy cleaning.

My envionment win10 + Flutter 3.13.3 + IntelliJ IDEA 2023.2

### Proposal

FLUTTER_SYSTEM_TEMP_DIRECTORY=e:\dev\flutter_tmp

**Comment by darshankawar** [comment]
@RelicOfTesla 
Can you take a look at [this](https://github.com/flutter/flutter/issues/84094) issue and check if it helps to answer your case or not ?

**Comment by RelicOfTesla** [comment]
Not help..IntelliJ IDEA 2023.2 plugin - Flutter 75.1.4,  Debug,Stop,Debug,Stop,Debug,Stop..........Debug,Stop.. Now, You can see many fluters_tools.xxxx  directory appears and has not been deleted(directory count>10), and executing "flutter doctor - v" will not automatically clear it.

**Comment by darshankawar** [comment]
> Manually execute the cmd.exe command "flutter run -d chrome" and after opening it, press "ctrl+c" or close cmd.exe window to still not delete the directory.

The flutter command has a thin .bat wrapper on Windows to make it a runnable command; Ctrl-C terminates the Flutter tool's Dart script, as it is supposed to. Then, because it's how the console on Windows works, you get a prompt asking if you want to terminate the enclosing .bat script.



> Now, You can see many fluters_tools.xxxx directory appears and has not been deleted

Can you provide screenshot of these directories generated ?

**Comment by RelicOfTesla** [comment]
```
F:\tmp>flutter create test1
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Creating project test1...
Resolving dependencies in test1... (25.9s)
Got dependencies in test1.
Wrote 129 files.

All done!
You can find general documentation for Flutter at: https://docs.flutter.dev/
Detailed API documentation is available at: https://api.flutter.dev/
If you prefer video documentation, consider: https://www.youtube.com/c/flutterdev

In order to run your application, type:

  $ cd test1
  $ flutter run

Your application code is in test1\lib\main.dart.


F:\tmp>cd test1

F:\tmp\test1>flutter run -d chrome
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Launching lib\main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             18.2s
This app is linked to the debug service: ws://127.0.0.1:56416/qM0nngy8xgE=/ws
Debug service listening on ws://127.0.0.1:56416/qM0nngy8xgE=/ws

  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

A Dart VM Service on Chrome is available at: http://127.0.0.1:56416/qM0nngy8xgE=
The Flutter DevTools debugger and profiler on Chrome is available at:
http://127.0.0.1:9103?uri=http://127.0.0.1:56416/qM0nngy8xgE=
终止批处理操作吗(Y/N)? y

F:\tmp\test1>


```

translated:
```
终止批处理操作吗(Y/N)? y      =>    Terminate batch job (Y/N)?
```

**Comment by darshankawar** [comment]
Thanks for the update. Keeping this issue open for team's attention / tracking.

**Comment by christopherfujino** [comment]
I agree that it is a problem that these temp directories grow over time. How would customizing the path we use help, though?

**Comment by christopherfujino** [comment]
I'm actually going to close this in favor of re-opening https://github.com/flutter/flutter/issues/84094. Thanks for the research @RelicOfTesla
