### ISSUE TITLE
Alignment of Interactive Viewer to center the contents

### ISSUE THREAD

**Issue by matriculus** [flutter/flutter#136606]
https://github.com/flutter/flutter/blob/b00216b3201d7c1211ad22cfe76d79a9b8655e5e/packages/flutter/lib/src/widgets/interactive_viewer.dart#L1272C33-L1272C33

The above link shows that the `alignment` parameter of the `InteractiveViewer` is not used when `constraint` is set to `false`. This leads to alignment issues when using `InteractiveViewer`.

Please change this to use the `alignment` parameter of the widget.

This is also the solution to this problem.
https://github.com/flutter/flutter/issues/90517

**Comment by darshankawar** [comment]
Thanks for the report @matriculus 
I believe your issue is same as https://github.com/flutter/flutter/issues/97813, so please follow-up in it for further updates.
Closing this as a duplicate.
