### ISSUE TITLE
How can I drag the last element of ListView.builder up to a certain distance?

### ISSUE THREAD

**Issue by therasuldev** [flutter/flutter#136664]
I want the last element of ListView.builder to be stretched upwards by the distance I set, but BouncingScrollPhysics() allows the last element to be stretched almost to the middle of the screen. How can I change it to custom? What lines of code should I change?
[https://youtu.be/MpVcfr4tnA8?si=TWpe74RR3MN2kTwo](url)

**Comment by darshankawar** [comment]
@therasuldev 
Your question is better suited for support channels like StackOverflow.
Closing from here, as this is more of a support question and not a feature request or a bug report.
