### ISSUE TITLE
ThemeData copy with not work with brightness

### ISSUE THREAD

**Issue by a1573595** [flutter/flutter#136613]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run the sample code.
2. Go to the system and open dark theme.

### Expected results

Show dark mode when the system is in dark mode.

### Actual results

Nothing changed.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.light(useMaterial3: true),
      // darkTheme: ThemeData.dark(useMaterial3: true),
      /// not working
      darkTheme: ThemeData.light(useMaterial3: true).copyWith(brightness: Brightness.dark),
      themeMode: ThemeMode.system,
      home: const HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Column(
        children: [TextField()],
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![截圖 2023-10-16 上午9 27 52](https://github.com/flutter/flutter/assets/25738593/797ee039-8f00-4638-ad0c-3bcd8757fc36)

</details>

### Logs

<details><summary>Logs</summary>

```console
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
Running Gradle task 'assembleDebug'...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Debug service listening on ws://127.0.0.1:61897/gg2qm16I3zM=/ws
Syncing files to device sdk gphone64 arm64...
I/xample.untitled( 6511): Compiler allocated 4579KB to compile void android.view.ViewRootImpl.performTraversals()
W/Parcel  ( 6511): Expecting binder but got null!
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.7, on macOS 13.6 22G120 darwin-arm64, locale
    zh-Hant-TW)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.82.2)
[✓] Connected device (5 available)
[✓] Network resources
```

</details>

**Comment by dam-ease** [comment]
Hi @a1573595. Thanks for filing this. This seems to be the expected behaviour. I see you are setting the `theme` to `Light` but only changing the `Brightness`. Can you provide more information on what your expected behaviour is?

**Comment by a1573595** [comment]
> Hi @a1573595. Thanks for filing this. This seems to be the expected behaviour. I see you are setting the `theme` to `Light` but only changing the `Brightness`. Can you provide more information on what your expected behaviour is?

This is not expected behavior and doesn't work when I want the code to be modular, causing me to repeat the declaration.

```dart=
    final lightTheme = ThemeData(
      brightness: Brightness.light,
      useMaterial3: true,
      /// set some theme
      dialogTheme: DialogTheme(),
      dividerTheme: DividerThemeData(),
    );

    /// use copyWith change brightness but override other theme settings
    final darkTheme = lightTheme.copyWith(
      brightness: Brightness.dark,
    );

    // /// I do not want to do it again.
    // final darkTheme = ThemeData(
    //   brightness: Brightness.dark,
    //   useMaterial3: true,
    //   /// set some theme
    //   dialogTheme: DialogTheme(),
    //   dividerTheme: DividerThemeData(),
    // );
```

**Comment by dam-ease** [comment]
Thanks for explaining further @a1573595. I see the issue now but https://github.com/flutter/flutter/issues/22913 seems similar/related to what you are describing. Can you check this out?

**Comment by rydmike** [comment]
The behavior is expected. Here is a bit of explanation of why it is so, and also why it most likely will remain so for the forseable future.

The theme `brightness` does not actually control the light/dark look of the theme, changing it in raw `ThemeData` object does nothing, never has. It is actually sourced from the `brightness` in the `ThemeData.colorScheme`, where it also does nothing, only basically serves as info that the `ColorScheme` and `ThemeData` is intended for a light or dark mode theme. You can typically trust it, and use it to do various light/dark mode logic based on it of course in an app.

It is actually **all the color properties** in `ThemeData` and primarily in M3 in its `colorScheme` property object `ColorScheme`, that determines what the widgets that use the theme actually look like.

The **ThemeData** creation factories, like `ThemeData()` (yes it is factory, not a direct object constructor, the actual object constructor is `ThemeData.raw` which may be confusing), and `ThemeData.from()` or `ThemeData.light()` and `ThemeData.dark()` are all factories that use their `brightness` input parameter or its `light` default, as a way to create a light/dark theme by setting a lot of color values using additional input color values (preferably via a provided ColorScheme, but also direct ThemeData color property values), M2/M3 mode toggle and default color values for the mode, to actually the create the full `ThemeData` object with all its needed color values, that determine the color style of the app using the theme.

Adjusting only the `brightness` property using `copyWith`, only changes the brightness value of the raw `ThemeData` object, it does not do any of the factory magic to change all the color values to actually make a theme light or dark.

The expected nature of a `copyWith` is not function as a factory, only to change the modified property and create a new copy of an object with that property value changed. It does that correctly. The nature of this data object is however such, that to make a `ThemeData` object designed for light mode, to one suitable for dark mode, pretty much all color properties in it also needs to change their values. This is not what an object `copyWith` function does.

This also applies as an answer to issue https://github.com/flutter/flutter/issues/22913.

This may imo be used as an answer and rationale to close both issues, if the Flutter team thinks that is appropriate of course.

I do agree that this can be a bit confusing when you start out using theming and the `ThemeData` object in Flutter. That the unnamed constructor `ThemeData()` is actually a factory constructor, that behind the scenes does a lot of magic before actually creating a `ThemeData` object, is probably one source of the confusion.

**Comment by a1573595** [comment]
Thank you for your explanation.
