### ISSUE TITLE
When specifying a ColumnWidget as the child property of an AlignWidget, the Alignment's [Y] doesn't work.

### ISSUE THREAD

**Issue by yamadade** [flutter/flutter#136602]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

[Dart Pad](https://dartpad.dev/?id=77ca120634d8ec22500bbd6ef4d61166)

### Expected results

the Alignment's [Y] doesn't work.

### Actual results

When specifying a ColumnWidget as the child property of an AlignWidget, the Alignment's [Y] doesn't work.

### Code sample
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(home: MyHomePage());
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Align(
          alignment: const Alignment(0.0, 0.0), // [Y] Not Working
          child: Column(
            children: [
              Container(
                height: 50,
                width: 50,
                color: Colors.amber,
              ),
            ],
          )),
    );
  }
}

```

</details>

**Comment by Juliotati** [comment]
@yamadade you have to be clear on what you want to align.
`Column`s have alignment properties for their children (`crossAxisAlignment` or `mainAxisAlignment`)

**Comment by huycozy** [comment]
Hi @yamadade 
As I can see, this is an expected result as the content is in the center:

![Screenshot 2023-10-16 at 16 45 27](https://github.com/flutter/flutter/assets/104349824/85db9af2-4e5b-49ac-b929-2f3c77fe68c3)

It's also stated in the documentation:

https://github.com/flutter/flutter/blob/0b035e026a5244215a0dffa4870783d209b78405/packages/flutter/lib/src/painting/alignment.dart#L148

If you want the Container to be located in the center, you should adjust Column property instead (apply `mainAxisAlignment: MainAxisAlignment.center` to Column):

![Screenshot 2023-10-16 at 16 49 39](https://github.com/flutter/flutter/assets/104349824/2559ec27-f474-4dec-9d1d-a41f29faaed5)

Closing as it's WAI. If you disagree, please write in the comments and I will reopen it.
