### ISSUE TITLE
DropdownMenu The named parameter 'expandedInsets' isn't defined

### ISSUE THREAD

**Issue by Jannik-dev** [flutter/flutter#136759]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a new project
2. Place a DropDownMenu in the body of MyHomePage
3. Try to access expandedInsets

### Expected results

The named parameter exists as in the current state of the master branch.

I tried to upgrade flutter, but I am using the newest stable version (3.13.7).
I guess that it is a problem at my end, but I cannot figure it out.

The property is also missing in the documentation: https://api.flutter.dev/flutter/material/DropdownMenu-class.html, but it was merged in #129753 and related in #134291.

### Actual results

expandedInsets is underlined in red – The named parameter 'expandedInsets' isn't defined

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: DropdownMenu<String>(
        expandedInsets: EdgeInsets.zero,
        dropdownMenuEntries: [],
      ),// This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.13.7, on Microsoft Windows [Version 10.0.22000.2416], locale en-DE)
    • Flutter version 3.13.7 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2f708eb839 (8 days ago), 2023-10-09 09:58:08 -0500
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\devja\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33717.318
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.81.1)
    • VS Code at C:\Users\devja\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.2416]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 117.0.5938.150
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 117.0.2045.60

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @Jannik-dev 

It seems the property is currently only available on master version and not in stable yet and that's why you are seeing it as underlined in red.


> The property is also missing in the documentation: https://api.flutter.dev/flutter/material/DropdownMenu-class.html,

You can check https://master-api.flutter.dev/flutter/material/DropdownMenu-class.html wherein, the said property is mentioned and available.

I think it'll be a matter of a new stable release in which the said property should be available. Since it is available in master version and also in master api docs, I'll close this as resolved and working as expected. You may read about the [flutter release policy](https://github.com/flutter/flutter/wiki/Release-process) and keep an eye on the next stable release.
