### ISSUE TITLE
Flutter doctor can't locate iOS SDK 17.0 on Mac despite installation

### ISSUE THREAD

**Issue by mycar98765** [flutter/flutter#136710]
I'm experiencing an issue with Flutter where 'flutter doctor -v' can't locate the iOS SDK 17.0 installed on my Mac, and instead, it's looking for SDK for iPhoneOS16.4. I've confirmed that I have iOS 17.0 installed. Can anyone help me identify and resolve this issue? Here are the details:

**Environment:**
- macOS: 14.0
- Xcode: 15.0
- Flutter: 3.13.7
- Dart: 3.1.3

**Issue:**
When I run 'flutter doctor -v,' I receive the following error message:

```
Error executing simctl: 72
xcodebuild: error: SDK "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.plOS.plOS.platform/Developer/SDKs/iPhoneOS16.4.sdk" cannot be located.
```

**Steps Taken:**
I have already tried the following steps:
- Installed iOS SDK 17.0 through Xcode.
- Checked that my Xcode path is correctly set: "/Applications/Xcode.app/Contents/Developer"
- Reset the Xcode path.

What I haven't tried: 
- Uninstall and reinstall Flutter.

How can I make Flutter recognize the installed iOS SDK 17.0 correctly and resolve this issue?

Your help is greatly appreciated, and any insights on making Flutter recognize the installed SDK version would be valuable. Thank you!

**More information:**

I upgraded to Sonoma approximately 1-2 weeks ago and have been encountering this issue since then.

When I run 'xcrun simctl list runtimes,' I receive the following error message:

```
2023-10-16 06:17:10.264 xcodebuild[3232:16068] Writing error result bundle to /var/folders/kj/5sq9x1v92mjch2hl26lrxvxw0000gn/T/ResultBundle_2023-16-10_06-17-0010.xcresult
xcodebuild: error: SDK '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.4.sdk' cannot be located.
xcrun: error: Failed to determine realpath of '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.4.sdk' (errno=No such file or directory)
xcrun: error: sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.4.sdk -find simctl 2> /dev/null' failed with exit code 16384: (null) (errno=No such file or directory)
xcrun: error: unable to find utility 'simctl,' not a developer tool or in PATH
```

I also attempted to run 'xcode-select --install,' but I received the following message:

```
xcode-select: note: Command line tools are already installed. Use 'Software Update' in System Settings or the softwareupdate command line interface to install updates.
```

I'm uncertain whether the error is related to the installation failure of Xcode Command Line Tools or if there are other issues at play.

I tried to run the "ls -l /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs" command, and it returned a result:

```
total 0
drwxrwxr-x 8 root wheel 256 Sep 1 03:07 iPhoneOS.sdk
lrwxr-xr-x 1 root wheel 12 Sep 20 17:47 iPhoneOS17.0.sdk -> iPhoneOS.sdk
```

But I don't know where in my Mac it's written to read "iPhoneOS.plOS.plOS.platform" instead of "iPhoneOS.platform."

**Comment by huycozy** [comment]
Hi @mycar98765 
This is more like an XCode issue than a Flutter issue. Have you checked any given solutions from [this](https://stackoverflow.com/questions/29108172/how-do-i-fix-the-xcrun-unable-to-find-simctl-error) to see if one of them works?

**Comment by mycar98765** [comment]
Hi @huycozy , thank you for your reply. The answer provided didn't solve my issue. I managed to resolve it on my own by updating the SDKROOT to the correct path in the .zshrc file.

**Comment by mycar98765** [comment]
@huycozy By the way, I encountered a new problem when achieving it in Xcode: Flutter.h cannot be found. Do you have a solution?

**Comment by huycozy** [comment]
>I encountered a new problem when achieving it in Xcode: Flutter.h cannot be found. 

That's another issue which could be caused by various reasons. You can check [this](https://stackoverflow.com/questions/64973346/error-flutter-flutter-h-file-not-found-when-flutter-run-on-ios) to see if solutions there may be applied.
