### ISSUE TITLE
Re-add firebase lab tests to android engine builds

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#136767]
These tests were missed during the migration to engine v2.

Link to v1 build running the tests:

https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Android%20AOT%20Engine/52866/overview

```
14.6
Build and test arm64 profile > test: Android Firebase Test
```

Test implementation in old build:

https://cs.opensource.google/flutter/recipes/+/main:recipes/engine/engine.py;l=406

**Comment by godofredoc** [comment]
\cc @gmackall

**Comment by gmackall** [comment]
For context I believe the cc is because it came from discord discussion here
https://discord.com/channels/608014603317936148/1163923810978898010/1163964828440871033
