### ISSUE TITLE
Add onSubmitted property to SearchAnchor

### ISSUE THREAD

**Issue by SpencerRiddering** [flutter/flutter#136790]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

SearchAnchor has two distinct experiences: "search bar" and "search view". The "search bar" (defined by a SearchBar instance) is returned by  SearchAnchor's "builder" property. The "search view" is constructed within SearchAnchor when controller.openView() is called. 

We want to receive callbacks when the search is submitted, both from the "search bar" and from the "search view".  #126551 enabled us to apply an onSubmitted handler on the "search bar". What we need is the ability to apply an onSubmitted handler to the "search view".  

### Proposal

Add an optional "viewOnSubmitted" property to SearchAnchor and then apply that handler to the "search view".

**Comment by huycozy** [comment]
Thanks for your proposal. 
I see there's a similar issue addressing the case you described https://github.com/flutter/flutter/issues/130687. Even though it's proposed for `SearchAnchor.bar` factory, I think it could be done for `SearchAnchor` as well. 

Closing this issue in favor of that one, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
