### ISSUE TITLE
[CP] migrate API docs to use GA4

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#136743]
### Issue Link

https://github.com/flutter/flutter/issues/136741

### Commit Hash

4dcd1598b77f51347a3985118d29770f9e392128

### Target

beta

### PR Link

https://github.com/flutter/flutter/pull/136742

### Changelog Description

Update the analytics instance used on api.flutter.dev.

### Impacted Users

All Flutter developers using api.flutter.dev

### Impact Description

The impact of not landing this cherrypick would mean that, moving forward (once Universal Analytics is deprecated), we will have one less stable cycle worth of API docs analytics in GA4.

### Workaround

no workaround needed

### Risk

low

### Test Coverage

yes

**Comment by itsjustkevin** [comment]
@gspencergoog please review this cherry-pick.

CC: @jayoung-lee

**Comment by gspencergoog** [comment]
LGTM
