### ISSUE TITLE
Most error messages in gradle_errors.dart assume a unix like path separator/environment

### ISSUE THREAD

**Issue by gmackall** [flutter/flutter#136763]
Examples
path separators 
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/gradle_errors.dart#L114
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/gradle_errors.dart#L149

`./gradlew` vs `./gradlew.bat`
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/gradle_errors.dart#L524

**Comment by thisisjaymehta** [comment]
@mike-v2 Are you going to create pull request?

**Comment by mike-v2** [comment]
> @mike-v2 Are you going to create pull request?

Thanks for reminding me, I forgot about this!
It looks like the first two examples have been removed from the code base, but I can fix the third example.
