### ISSUE TITLE
Help to debug Android Emulator issues

### ISSUE THREAD

**Issue by ricardoamador** [flutter/flutter#136757]
### Is there an existing issue for this?

- [X] I have searched the [existing infra issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-infra)

### Type of Request

infra task

### Infrastructure Environment

Recipes

### What is happening?

Work with the Android team to determine why they are getting failures when using API version 34 emulators.

### Steps to reproduce

NA

### Expected results

NA

**Comment by ricardoamador** [comment]
I created the following pull request for testing as Camille was out on vacation I could not update her pull request: https://github.com/flutter/packages/pull/5157

And found that for some reason when we use sdk 34 with emulators 34 her test fails. But with Android sdk 33 and emulators version 34 they pass: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8766965849984793121/+/u/Run_package_tests/native_integration_tests/stdout

**Comment by ricardoamador** [comment]
FYI @camsim99

**Comment by camsim99** [comment]
Original bug I filed: https://github.com/flutter/flutter/issues/135756

**Comment by ricardoamador** [comment]
Ah you didn't need to close it. We can use that one instead if you like?

**Comment by ricardoamador** [comment]
In fact I would reopen that so you have tracking in your team as well.

**Comment by ricardoamador** [comment]
I can close this one too and add fyi-infra. I will add all this information there as well.

**Comment by ricardoamador** [comment]
Closing in favor of Camille's issue and adding fyi-infra for us.
