### ISSUE TITLE
video_player Aspect Ratio

### ISSUE THREAD

**Issue by abbadabbatech** [flutter/flutter#13670]
Is there any provision to dynamically decide the aspect ratio based on the orientation of the video being played?  For instance, I modified image_picker to choose a video and want to have it displayed in the orientation it was recorded in.  If I take that video and upload it and play it via an http get, then it plays in the default browser in the correct orientation, but in video player it is based on the hard coded aspect ratio.

Any ideas or thoughts would be great.

**Comment by sigurdm** [comment]
Yes a size operation is needed.
