### ISSUE TITLE
[Fonts][Material-Icon] Outdated

### ISSUE THREAD

**Issue by andrefedev** [flutter/flutter#136787]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

The material icons are outdated, I was looking and a lot of icons are missing. Is it possible to update them without the need to wait for a new version of Flutter?

### Proposal

<img width="1523" alt="Screenshot 2023-10-18 at 12 45 02 AM" src="https://github.com/flutter/flutter/assets/14114839/b9beb0dc-f8d7-4f36-b449-76f5a9b160b2">

**Comment by dam-ease** [comment]
Hi @andrefedev. Thanks for filing this. Not too sure I understand this. Are you proposing adding some missing icons similar to https://github.com/flutter/flutter/issues/27956? If yes, can you provide more information on these icons or check out this community package https://pub.dev/packages/font_awesome_flutter if it helps
