### ISSUE TITLE
DropdownMenu shows incorrect currentHighlight

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#136735]
b/305662376

Customer reports the current highlight of their DropdownMenu is not correct.
I have not been able to reproduce this in an independent code sample, but the customer code and a video of the bug is available in the internal bug listed above.

Steps:

1. DropdownMenu has initial index of 0.
2. Customer opens menu, selects index 2, menu closes.
3. Customer opens menu, index 1 is highlighted.

@QuncCccccc do you have any thoughts on this? It looks like currentHighlight is incorrect. 

I think this could be the way we choose the currentHighlight based on filtering. The customer case has 3 items in the menu, in this order
* All
* Unread
* Read

The bug presents itself when `Read` is selected and the menu is reopened, and `Unread` is highlighted instead. At this point `Read` is in the text field of the menu, so we could be highlighting the first match to the String `read`. Maybe?

**Comment by QuncCccccc** [comment]
Thanks for the code sample! Taking a look.

**Comment by QuncCccccc** [comment]
Ah interesting. It looks like when dropdown menu is looking for the target, it will show the first target which contains the text in the text field instead of getting a exact match😂. If we put 'Read' in the second place, it will work correctly. I can add an option for users to define their own formula to get the result, or provide a flag to find the "exact match".

**Comment by kirpit** [comment]
I was scratching my head until I've found this issue, surprised it's been reported only recently as I'm on `3.12.0` that is from 4 months ago. Exact same thing is happening with this example:

* ...
* Caravan Park
* ...
* Park

When the "Park" is selected, "Caravan Park" is highlighted. Thankfully it actually saves and returns the correct value.

**Comment by QuncCccccc** [comment]
> When the "Park" is selected, "Caravan Park" is highlighted. Strange thing is their value is not string but enums and it does give the correct enum value with the `onSelected` event. I would simply expect that widget to highlight first `==` matching **value**, not the string label `.contains()` test result, instead of writing a custom "search algorithm" TBH...

Thanks for the suggestion. I think comparing value would be a little difficult because searching happens when we are typing text in the text field, but the entry's value could be any types.
