### ISSUE TITLE
Curve.Threshold should be called Curve.Step 

### ISSUE THREAD

**Issue by appsforartists** [flutter/flutter#13677]
Looking through [the subtypes of `Curve`](https://docs.flutter.io/flutter/animation/Curve-class.html), one is called [`Threshold`](https://docs.flutter.io/flutter/animation/Threshold-class.html).  In CSS, this is called ["step"](https://developer.mozilla.org/en-US/docs/Web/CSS/transition-timing-function) (because it's a step-function).

Related #13669 (rename `Curve`)

**Comment by Hixie** [comment]
`Step` sounds like it would have multiple steps. `Threshold` is more like the [threshold littlebit](https://shop.littlebits.cc/products/threshold).

**Comment by appsforartists** [comment]
I need to play with the animation APIs more before I can give more thoughtful feedback.

**Comment by goderbauer** [comment]
Please let us know when you can give us more thoughtful feedback.
