### ISSUE TITLE
host_debug build on Mac: Segmentation fault 

### ISSUE THREAD

**Issue by szakarias** [flutter/flutter#13673]
https://uberchromegw.corp.google.com/i/client.flutter/builders/Mac%20Engine/builds/2108/steps/build%20host_debug/logs/stdio

Has been seen a couple of times.

**Comment by zoechi** [comment]
Is this still an issue?

**Comment by iapicca** [comment]
Hi @szakarias is this issue still meant to be open?

**Comment by szakarias** [comment]
I would assume this is outdated by now. Closing the issue.
