### ISSUE TITLE
Add ability to share context between Draggable.feedback and Draggable

### ISSUE THREAD

**Issue by AlexanderFarkas** [flutter/flutter#136723]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

`Draggable.feedback` having not the same context as Draggable itself - is not developer friendly. I would like to access the same Theme/MediaQuery/other InheritedWidgets inside `feedback` widget.

### Proposal

I propose `feedbackBuilder` property which shares context naturally.
```dart
Draggable(
  feedbackBuilder: (context) => ...
);
```

I believe new `OverlayPortal` already solves the problem with context sharing. The only task is to link it with `Draggable`.

Though, it would be more natural to entirely replace `feedback` old behavior.

**Comment by huycozy** [comment]
Hi @AlexanderFarkas 
Could you share a practical case (minimal sample code) in which you have the issue with context on `feedback` widget?

**Comment by AlexanderFarkas** [comment]
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: DefaultTextStyle(
            style: TextStyle(color: Colors.blue),
            child: Draggable(
              feedback: Feedback(),
              child: Text("hello, world"),
            ),
          ),
        ),
      ),
    );
  }
}

class Feedback extends StatelessWidget {
  const Feedback({super.key});

  @override
  Widget build(BuildContext context) {
    return Text("hello, world");
  }
}

```

Try to drag, and you will see it doesn't inherit context.

**Comment by huycozy** [comment]
Thanks for the update but the sample code doesn't seem to represent the case. Instead, I found there is a similar issue https://github.com/flutter/flutter/issues/60941 that has clear steps and use case. 

Closing this issue in favor of that one. Please follow up on it for updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
