### ISSUE TITLE
Interfacing with golang and CPP.

### ISSUE THREAD

**Issue by gedw99** [flutter/flutter#13671]
It's a pity there is no support for using protobuf in order to interoperate with other languages.

Method channel looks very bespoke 

Can the team think about this use case..

I write tons of logic in golang because I use it on all devices. I want to have two way calling between the flutter GUI and my golang. I don't want to use flutter for anything but display.

What's the options today ?

1. Method channels.
Could not find a single example with golang.

2. Protobuf
Gomatcha uses this to achieve the same need very well.

Is it because no one else wants this or that flutter is not ready for this in its roadmap yet ?

**Comment by rusenask** [comment]
Hi,  sorry for off-topic but could you point me to any examples of calling Go code from flutter/dart?

**Comment by foxundermoon** [comment]
+1

**Comment by gedw99** [comment]
run golang inside Flutter:

https://github.com/adieu/flutter_go
- this one is awesome because it just uses rpc and so its generic. So you dont have to write any swift or java !

https://github.com/renatoathaydes/go-hash
https://github.com/renatoathaydes/gohash_mobile_app
https://github.com/renatoathaydes/gohash_mobile
- this one shows a DB and how to do it in detail.
- great long tutorial about how to get everything working: https://sites.google.com/a/athaydes.com/renato-athaydes/posts/buildingamobilefrontendforagoapplicationusingflutter

**Comment by charafau** [comment]
I don't think json-rpc is the right approach...

**Comment by gedw99** [comment]
@charafau 
Can you explain your own reasons ?

My own view:
-  Its a hack to get stuff done quickly in terms fo development.
- I was planning to change over to protobufs for perf reasons and easy codegen

**Comment by gedw99** [comment]
BTW FIDL cant be done at Flutter level because it relied on kernel code from zircon in Fuchsia.

**Comment by gedw99** [comment]
@zoechi 
Yeah its similar to #7053. Maybe i should close it ?

**Comment by zoechi** [comment]
@gedw99 I guess so. I eouldn't expect something specific to Go.
