### ISSUE TITLE
Glitches with zooming and scrolling while using InterativeViewer with singleChildScrollView

### ISSUE THREAD

**Issue by SharveenKarunakaran** [flutter/flutter#136808]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Just run the snippet of code and do vertical zooming and scrolling. issue will  be replicated

### Expected results

Need for fast and smooth zooming in all directions, as well as for scrolling without any glitches

### Actual results

Pinch zooming was not functioning properly in the vertical direction when I wrapped InteractiveViewer with a SingleChildScrollView, so I changed the scrollPhysics with a bool value by using bloc and also tried with setState in both cases there is a glitch like sometimes scrollings was not functioning properly and sometimes vertical zooming was not works properly. Can you guide me on how to fix this problem?

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool canScroll = true;
  final events = [];
  ScrollController controller = ScrollController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
          child: Listener(
        onPointerDown: (event) {
          events.add(event.pointer);
        },
        onPointerUp: (event) {
          events.clear();
          if (!canScroll) {
            setState(() {
              canScroll = true;
            });
          }
        },
        onPointerMove: (event) {
          if (events.length == 2) {
            if (canScroll) {
              setState(() {
                canScroll = false;
              });
            }
          }
        },
        child: InteractiveViewer(
          child: SingleChildScrollView(
            controller: controller,
            physics: canScroll
                ? const AlwaysScrollableScrollPhysics()
                : const NeverScrollableScrollPhysics(),
            child: Column(
              children: List.generate(500, (index) {
                return Padding(
                    padding: const EdgeInsets.all(8.0),
                    child: Container(
                      color: index % 2 == 0 ? Colors.red : Colors.green,
                      width: MediaQuery.of(context).size.width,
                      height: 300,
                      child: Align(
                          alignment: Alignment.bottomCenter,
                          child: Text('My name is Index $index')),
                    ));
              }),
            ),
          ),
        ),
      )),
    );
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/105288409/77b6f0ad-50dd-4c43-89fd-6d1b7f61d6b1

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.1, on macOS 13.6 22G120 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.83.0)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 2 categories.
```

</details>

**Comment by darshankawar** [comment]
Thanks for the detailed report @SharveenKarunakaran 
Can you take a look at [this](https://github.com/flutter/flutter/issues/86531) issue and check if it resembles your case or not ?

**Comment by SharveenKarunakaran** [comment]
[12:27 PM] Dharanidharan Dharmasivam
@darsh...  thanks for getting back, in that [issue](https://github.com/flutter/flutter/issues/86531), unable to move to end of page after zooming, but my issue is scrolling or zooming not working at some cases. For example run the attached code, keep on scrolling fastly, in some cases  the scroll functionality doesn't work at all. In my code I have changed the scrollPhysics dynamically based on the pointer, now remove the dynamic changes for scrollPhysics property and assign AlwaysScrollableScrollPhysics similar to below code, now scrolling will work in all scenarios.  
 
`scrollPhysics: AlwaysScrollableScrollPhysics()`
 
In same way if you change scrollPhysics to Neverscr....... like below pinch zooming will work on all scenarios.
 
`scrollPhysics: NeverScrollableScrollPhysics()`

My requirement is to have the pdf viewer with zooming functionality (for this I used InterativeViewer with SingleChildScrollableView), this use case might be similar to this issue but my issue is different from that. Please let me know if you need further details on my issue.

**Comment by darshankawar** [comment]
Thanks for the update @SharveenKarunakaran 
Since you are trying to zoom and scroll, can you take a look at https://pub.dev/packages/two_dimensional_scrollables which is Flutter's first party package and see if it helps to cover your scenario ?

**Comment by SharveenKarunakaran** [comment]
Hi @darshankawar  thanks for your suggestion, unfortunately [this widget](https://pub.dev/packages/two_dimensional_scrollables) can't be used for my scenario, since it is used for grid view, in my case its no grid view. As said earlier, am trying to create pdf viewer with zooming functionality. Kindly provide suggestion on resolving [this issue](https://github.com/flutter/flutter/issues/136808#issuecomment-1770211381) and please let me know if you need further details on my issue.

**Comment by darshankawar** [comment]
@SharveenKarunakaran 
Have you already looked at community packages which offers the feature you are trying to achieve ?
You can take a look at https://pub.dev/packages?q=pdf+viewer and see if any package suits your requirement or not.

**Comment by SharveenKarunakaran** [comment]
@darshankawar , thanks for your suggestion. We have already checked on few community packages, doesn't suit to our requirement. However, we will check with suggestions and get back to you sooner
