### ISSUE TITLE
Under multiple engines, destroying the page will not trigger dispose

### ISSUE THREAD

**Issue by yangha886** [flutter/flutter#136885]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Flutter (Channel stable, 3.13.1）

Under multiple engines, destroying the page will not trigger dispose

It can be reproduced in the official 'multiple_flutters' demo.

### Proposal

I found that when using multiple engines, if the FlutterViewController is destroyed, it will directly destroy the engine and channel, and the dispose in the Flutter page will not be triggered. Is there any way to change this problem? Because if dispose is not triggered, we will have a lot of inconvenience.

**Comment by darshankawar** [comment]
Thanks for the report @yangha886 
I tried running the multiple_flutters sample from the repo, but I am unsure to pinpoint how it will show that dispose is not triggering. Can you provide us with an example that shows the reported behavior, ie, dispose not getting called and what possible issue it could arise ?

**Comment by yangha886** [comment]
I added the following code in _MyHomePageState:
@override
  void dispose() {
    // TODO: implement dispose
    super.dispose();
    print("_MyHomePageState dispose");
  }

and if this page gets destroyed it should trigger dispose, so it should definitely print '_MyHomePageState dispose', but unfortunately it doesn't

> Thanks for the report @yangha886 I tried running the multiple_flutters sample from the repo, but I am unsure to pinpoint how it will show that dispose is not triggering. Can you provide us with an example that shows the reported behavior, ie, dispose not getting called and what possible issue it could arise ?

**Comment by darshankawar** [comment]
@yangha886 
Can you take a look at [this](https://github.com/flutter/flutter/issues/77621) issue and check if it resembles your case or not ?

**Comment by yangha886** [comment]
> @yangha886 您能看一下[这个](https://github.com/flutter/flutter/issues/77621)问题并检查它是否与您的情况相似吗？

@darshankawar 
It doesn't seem quite like it, but the issue he raised is more inclined towards memory leaks. Initially, I suspected that destroying FlutterViewController directly caused the engine to be destroyed without triggering dispose (similar to how killing an iOS application directly from the background does not trigger deinit/dealloc), but I found that even if FlutterViewController is delayed in destruction, Flutter still does not trigger dispose.

**Comment by darshankawar** [comment]
Thanks for the update. Keeping it open for team's input / tracking.

**Comment by zanderso** [comment]
I believe there isn't a guarantee that `dispose()` will be called in this situation, but @gaaclarke and @dnfield to verify and close as working-as-intended if appropriate.

**Comment by gaaclarke** [comment]
What is the behavior when there is one engine?  Is `dispose` called when killing a single engine?  I would expect the multiple engines case to behave similarly.  The behavior isn't documented anywhere I know of.

**Comment by yangha886** [comment]
> I believe there isn't a guarantee that `dispose()` will be called in this situation, but @gaaclarke and @dnfield to verify and close as working-as-intended if appropriate.

My idea is, if there is at least one engine in the engine group, can we prioritize triggering dispose before destroying the engine, and then destroy the engine after dispose is completed? Except for the first engine, all other engines are spawned and do not want to terminate the entire application's lifecycle directly like killing the application.

**Comment by yangha886** [comment]
> What is the behavior when there is one engine? Is `dispose` called when killing a single engine? I would expect the multiple engines case to behave similarly. The behavior isn't documented anywhere I know of.

I haven't tried killing the engine in a single-engine scenario, so I don't know what the behavior would be like. Based on the multi-engine scenario, I guess it could have the same behavior.
