### ISSUE TITLE
[Flake] Linux_clang_tidy

### ISSUE THREAD

**Issue by itsjustkevin** [flutter/flutter#136812]
`Linux_clang_tidy` takes multiple runs to pass.  Each linux clang tidy run times out after an hour. 

With the tests requiring 4 runs to pass in presubmit and 4 runs to pass in postsubmit, this has added 8 hours to conducting a release.

Offending commit: [767d8c75e898091b925519803830fc2721658d07](https://github.com/flutter/engine/commit/767d8c75e898091b925519803830fc2721658d07)

CC: @godofredoc

**Comment by chinmaygarde** [comment]
Can you link to the failure?
