### ISSUE TITLE
Internal build failure: 'status_or.h' file not found

### ISSUE THREAD

**Issue by dkwingsmt** [flutter/flutter#136858]
I'm trying to run performance tests in Google's internal system and got the following kind of building errors: 
```
In file included from third_party/flutter_engine/lib/ui/painting/image.cc:11:
./third_party/flutter_engine/lib/ui/painting/image_encoding_impeller.h:10:10: fatal error: 'third_party/flutter_engine/fml/status_or.h' file not found
   10 | #include "third_party/flutter_engine/fml/status_or.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

sponge2/34a90d3c-29af-45ca-952f-6e9733c86612

Adding `status_or.h` to the internal `fml/BUILD` file resolves the error.

The file was added in https://github.com/flutter/engine/pull/46738 which introduces this new file without adding it to `BUILD.gn`

**Comment by dkwingsmt** [comment]
cc @jonahwilliams @gaaclarke 

(I could've just filed a PR that adds this file to `BUILD.gn` but I'm not sure if the `BUILD.gn` is converted to the internal `BUILD`.)

**Comment by jiahaog** [comment]
Note that this breakage is tangential to the internal production build and is mainly used for debugging. It's expected for this to be broken from time to time (with fix forwards), and I'm actively looking into fixing the build at this time. 

@dkwingsmt let's talk more internally about your use case :)

**Comment by dkwingsmt** [comment]
@jiahaog Thank you! Sure!

**Comment by chinmaygarde** [comment]
`status_or` is missing from the GN rule which is an engine issue and will be patched. I am unable to provide guidance about the internal failure.

**Comment by dkwingsmt** [comment]
I'm discussing the internal building issue with jiahaog and we agreed this Github issue can now be closed.
