### ISSUE TITLE
linux engine_release_builder timing out on host_engine on flutter-3.16-candidate.10

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#136861]
https://ci.chromium.org/ui/p/dart-internal/builders/flutter/Linux%20Production%20Engine%20Drone/26352/overview

This is preventing CPs from being processed (b/306089854)

**Comment by drewroengoogle** [comment]
Casey reran this a couple of times and all of them are timing out due to the `Linux host_engine` tests taking too long to run. Is there a good way to confirm this isn't an issue from the tests themselves?

**Comment by ricardoamador** [comment]
Removing from ticket queue.

**Comment by CaseyHillers** [comment]
https://github.com/flutter/engine/pull/47112 fixed this. Thank you @jason-simmons !
