### ISSUE TITLE
Flutter/Flutter.h file not found in Xcode

### ISSUE THREAD

**Issue by mycar98765** [flutter/flutter#136893]
I am trying to build my Flutter iOS app in Xcode, but I am getting the following error:

    'Flutter/Flutter.h' file not found
    failed to emit precompiled header '/Users/user/Library/Developer/Xcode/DerivedData/Runner-bqwgaclmizdztbgwvyuydjgnmjad/Build/Intermediates.noindex/ArchiveIntermediates/Runner/PrecompiledHeaders/Runner-Bridging-Header-swift_3AO5QSACASUGH-clang_24K6MS22YMY0N.pch' for bridging header '/Users/user/development/projects/flutter/project/ios/Runner/Runner-Bridging-Header.h'
    in file included from /Users/user/development/projects/flutter/project/ios/Runner/Runner-Bridging-Header.h:1:

I have tried the following steps to resolve the error:

* I have removed the `ios` folder and created a new one.
* I have run `pod install` in the `ios` folder.

I am still getting the error. What else can I do to resolve this error?

**Additional information:**

* Flutter version: 3.13.7
* Xcode version: 15.0
* No error displayed in the output of `flutter doctor -v` command:

**Comment by darshankawar** [comment]
@mycar98765 
Can you provide complete verbose log ?

**Comment by israelglory** [comment]
@mycar98765  Make sure you are opening the Runner.xcworkspace not the Runner.xcodeproj

**Comment by mycar98765** [comment]
@israelglory , yes, I am sure that I am opening Runner.xcworkspace.

**Comment by mycar98765** [comment]
@darshankawar @israelglory any updates?

**Comment by darshankawar** [comment]
@mycar98765 
Can you run `flutter build ios -v` and share the log here ?
