### ISSUE TITLE
Cannot run mobile app at iOS simulator

### ISSUE THREAD

**Issue by karomak** [flutter/flutter#136883]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

 cannot run flutter mobile app at iOS simulator, after put in terminal fvm flutter run I just see empty line.

When I run with '-v' it stops at:

```
{
               "ignored" : false,
               "modelCode" : "MacBookPro16,2",
               "simulator" : false,
               "modelName" : "MacBook Pro",
               "operatingSystemVersion" : "14.0 (23A344)",
               "identifier" : "4117DDB0-D402-5B75-9AEC-C5D6BCD3AF8E",
               "platform" : "com.apple.platform.macosx",
               "architecture" : "x86_64h",
               "interface" : "usb",
               "available" : true,
               "name" : "My Mac",
               "modelUTI" : "com.apple.macbookpro-13-retina-four-usb-ports-2020"
             },
             {
               "simulator" : true,
               "operatingSystemVersion" : "17.0 (21A328)",
               "available" : true,
               "platform" : "com.apple.platform.iphonesimulator",
               "modelCode" : "iPad13,17",
               "identifier" : "ED28F503-BF45-423F-9517-559398CB41FB",
               "architecture" : "x86_64",
               "modelUTI" : "com.apple.ipad-air5-1",
               "modelName" : "iPad Air (5th generation)",
               "name" : "iPad Air (5th generation)",
               "ignored" : false
             },
             {
               "simulator" : true,
               "operatingSystemVersion" : "17.0 (21A328)",
               "available" : true,
               "platform" : "com.apple.platform.iphonesimulator",
               "modelCode" : "iPad13,18",
               "identifier" : "85A83F5E-65BF-4A34-88E1-38F7546DE43D",
               "architecture" : "x86_64",
               "modelUTI" : "com.apple.ipad-10-1",
               "modelName" : "iPad (10th generation)",
               "name" : "iPad (10th generation)",
               "ignored" : false
             }
           ]
```
'flutter doctor -v' shows

```
Could not parse java version from: 

If there is a version please look for an existing bug https://github.com/flutter/flutter/issues/ and if one does not exist file a new issue.
[✓] Flutter (Channel stable, 3.13.1, on macOS 14.0 23A344 darwin-x64, locale en-PL)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ Could not determine java version
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.83.1)
[✓] VS Code (version 1.73.0)
Scanning for devices is taking a long time...
```
Device: Macbook - Sonoma 14.0 - Intel Core i5

Me and my colleges thought that it is connected with i5, but guy who has M1 has the same error.

### Expected results

Run app at iOS simulator without need to restart computer

### Actual results

For now I need to restart MacBook before run app. It is really irritating.

### Code sample

No code needed

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Could not parse java version from: 

If there is a version please look for an existing bug https://github.com/flutter/flutter/issues/ and if one does not exist file a new issue.
[✓] Flutter (Channel stable, 3.13.1, on macOS 14.0 23A344 darwin-x64, locale en-PL)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ Could not determine java version
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.83.1)
[✓] VS Code (version 1.73.0)
Scanning for devices is taking a long time...

**Comment by dam-ease** [comment]
Hi @karomak. Thanks for filing this issue. Does this reproduce only with simulator?
Can you try running this on a real  iOS device or on an emulator to see if this reproduces ?

**Comment by karomak** [comment]
> Hi @karomak. Thanks for filing this issue. Does this reproduce only with simulator? Can you try running this on a real iOS device or on an emulator to see if this reproduces ?

I just borrow iOS device. Unfortunately I cannot run app with real iOS device

**Comment by dam-ease** [comment]
Hi @karomak. Thanks for your response. Can you try the following steps and share your results?

- Create a new project from the terminal by running `flutter create`
- Then change directory to the project
- And run `flutter run -v`

Kindly share the full output of your `flutter run -v`.

**Comment by karomak** [comment]
`flutter_application_1 % flutter run -v
[   +8 ms] executing: sw_vers -productName
[  +25 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +23 ms] Exit code 0 from: sw_vers -productVersion
[        ] 14.0
[        ] executing: sw_vers -buildVersion
[  +18 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 23A344
[        ] executing: uname -m
[   +9 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +8 ms] executing: sysctl hw.optional.arm64
[   +9 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[ +138 ms] executing: sysctl hw.optional.arm64
[  +12 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[   +9 ms] executing: xcrun xcodebuild -version
[ +449 ms] Exit code 0 from: xcrun xcodebuild -version
[        ] Xcode 15.0.1
           Build version 15A507
[   +3 ms] executing: xcrun xcdevice list --timeout 5
[  +12 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +96 ms] executing: /Users/karolinam/Library/Android/sdk/platform-tools/adb devices -l
[        ] executing: xcrun xcdevice list --timeout 2
[   +2 ms] xcrun simctl list devices booted iOS --json
[        ] executing: xcrun simctl list devices booted iOS --json
[   +5 ms] executing: xcrun simctl list devices booted
[ +195 ms] Exit code 0 from: xcrun simctl list devices booted
[        ] == Devices ==
           -- iOS 17.0 --
               iPhone 15 Pro Max (FDF16002-0096-4C38-B16C-3707144C0CF4) (Booted)
[ +233 ms] {
                      "devices" : {
                        "com.apple.CoreSimulator.SimRuntime.iOS-17-0" : [
                          {
                            "lastBootedAt" : "2023-10-20T08:10:16Z",
                            "dataPath" : "\/Users\/karolinam\/Library\/Developer\/CoreSimulator\/Devices\/FDF16002-0096-4C38-B16C-3707144C0CF4\/data",
                            "dataPathSize" : 2959728640,
                            "logPath" : "\/Users\/karolinam\/Library\/Logs\/CoreSimulator\/FDF16002-0096-4C38-B16C-3707144C0CF4",
                            "udid" : "FDF16002-0096-4C38-B16C-3707144C0CF4",
                            "isAvailable" : true,
                            "logPathSize" : 282624,
                            "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-15-Pro-Max",
                            "state" : "Booted",
                            "name" : "iPhone 15 Pro Max"
                          }
                        ]
                      }
                    }
[+3026 ms] [
                      {
                        "ignored" : false,
                        "modelCode" : "MacBookPro16,2",
                        "simulator" : false,
                        "modelName" : "MacBook Pro",
                        "operatingSystemVersion" : "14.0 (23A344)",
                        "identifier" : "4117DDB0-D402-5B75-9AEC-C5D6BCD3AF8E",
                        "platform" : "com.apple.platform.macosx",
                        "architecture" : "x86_64h",
                        "interface" : "usb",
                        "available" : true,
                        "name" : "My Mac",
                        "modelUTI" : "com.apple.macbookpro-13-retina-four-usb-ports-2020"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.0 (21A328)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone16,2",
                        "identifier" : "FDF16002-0096-4C38-B16C-3707144C0CF4",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-15-pro-max-1",
                        "modelName" : "iPhone 15 Pro Max",
                        "name" : "iPhone 15 Pro Max",
                        "ignored" : false
                      }
                    ]
[   +2 ms] executing: xcrun devicectl --version
[ +128 ms] Exit code 0 from: xcrun devicectl --version
[        ] 348.1
[   +5 ms] executing: xcrun devicectl list devices --timeout 5 --json-output /var/folders/q2/wtdxt7zs0qj25lc78xd_wz2h0000gn/T/flutter_tools.znnnnt/core_devices.o4enPM/core_device_list.json
[  +96 ms] No devices found.
[        ] {
             "info" : {
               "arguments" : [
                 "devicectl",
                 "list",
                 "devices",
                 "--timeout",
                 "5",
                 "--json-output",
                 "/var/folders/q2/wtdxt7zs0qj25lc78xd_wz2h0000gn/T/flutter_tools.znnnnt/core_devices.o4enPM/core_device_list.json"
               ],
               "commandType" : "devicectl.list.devices",
               "environment" : {
                 "TERM" : "xterm-256color"
               },
               "jsonVersion" : 2,
               "outcome" : "success",
               "version" : "348.1"
             },
             "result" : {
               "devices" : [

               ]
             }
           }

[+2768 ms] [
                      {
                        "ignored" : false,
                        "modelCode" : "MacBookPro16,2",
                        "simulator" : false,
                        "modelName" : "MacBook Pro",
                        "operatingSystemVersion" : "14.0 (23A344)",
                        "identifier" : "4117DDB0-D402-5B75-9AEC-C5D6BCD3AF8E",
                        "platform" : "com.apple.platform.macosx",
                        "architecture" : "x86_64h",
                        "interface" : "usb",
                        "available" : true,
                        "name" : "My Mac",
                        "modelUTI" : "com.apple.macbookpro-13-retina-four-usb-ports-2020"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.0 (21A328)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone16,2",
                        "identifier" : "FDF16002-0096-4C38-B16C-3707144C0CF4",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-15-pro-max-1",
                        "modelName" : "iPhone 15 Pro Max",
                        "name" : "iPhone 15 Pro Max",
                        "ignored" : false
                      }
                    ]
[   +1 ms] executing: xcrun devicectl list devices --timeout 5 --json-output /var/folders/q2/wtdxt7zs0qj25lc78xd_wz2h0000gn/T/flutter_tools.znnnnt/core_devices.LNlT4U/core_device_list.json
[  +89 ms] No devices found.
[        ] {
             "info" : {
               "arguments" : [
                 "devicectl",
                 "list",
                 "devices",
                 "--timeout",
                 "5",
                 "--json-output",
                 "/var/folders/q2/wtdxt7zs0qj25lc78xd_wz2h0000gn/T/flutter_tools.znnnnt/core_devices.LNlT4U/core_device_list.json"
               ],
               "commandType" : "devicectl.list.devices",
               "environment" : {
                 "TERM" : "xterm-256color"
               },
               "jsonVersion" : 2,
               "outcome" : "success",
               "version" : "348.1"
             },
             "result" : {
               "devices" : [

               ]
             }
           }`

> Hi @karomak. Thanks for your response. Can you try the following steps and share your results?
> 
> * Create a new project from the terminal by running `flutter create`
> * Then change directory to the project
> * And run `flutter run -v`
> 
> Kindly share the full output of your `flutter run -v`.

**Comment by karomak** [comment]
`flutter_application_1 % flutter run -v
[   +8 ms] executing: sw_vers -productName
[  +25 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +23 ms] Exit code 0 from: sw_vers -productVersion
[        ] 14.0
[        ] executing: sw_vers -buildVersion
[  +18 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 23A344
[        ] executing: uname -m
[   +9 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +8 ms] executing: sysctl hw.optional.arm64
[   +9 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[ +138 ms] executing: sysctl hw.optional.arm64
[  +12 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[   +9 ms] executing: xcrun xcodebuild -version
[ +449 ms] Exit code 0 from: xcrun xcodebuild -version
[        ] Xcode 15.0.1
           Build version 15A507
[   +3 ms] executing: xcrun xcdevice list --timeout 5
[  +12 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +96 ms] executing: /Users/karolinam/Library/Android/sdk/platform-tools/adb devices -l
[        ] executing: xcrun xcdevice list --timeout 2
[   +2 ms] xcrun simctl list devices booted iOS --json
[        ] executing: xcrun simctl list devices booted iOS --json
[   +5 ms] executing: xcrun simctl list devices booted
[ +195 ms] Exit code 0 from: xcrun simctl list devices booted
[        ] == Devices ==
           -- iOS 17.0 --
               iPhone 15 Pro Max (FDF16002-0096-4C38-B16C-3707144C0CF4) (Booted)
[ +233 ms] {
                      "devices" : {
                        "com.apple.CoreSimulator.SimRuntime.iOS-17-0" : [
                          {
                            "lastBootedAt" : "2023-10-20T08:10:16Z",
                            "dataPath" : "\/Users\/karolinam\/Library\/Developer\/CoreSimulator\/Devices\/FDF16002-0096-4C38-B16C-3707144C0CF4\/data",
                            "dataPathSize" : 2959728640,
                            "logPath" : "\/Users\/karolinam\/Library\/Logs\/CoreSimulator\/FDF16002-0096-4C38-B16C-3707144C0CF4",
                            "udid" : "FDF16002-0096-4C38-B16C-3707144C0CF4",
                            "isAvailable" : true,
                            "logPathSize" : 282624,
                            "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-15-Pro-Max",
                            "state" : "Booted",
                            "name" : "iPhone 15 Pro Max"
                          }
                        ]
                      }
                    }
[+3026 ms] [
                      {
                        "ignored" : false,
                        "modelCode" : "MacBookPro16,2",
                        "simulator" : false,
                        "modelName" : "MacBook Pro",
                        "operatingSystemVersion" : "14.0 (23A344)",
                        "identifier" : "4117DDB0-D402-5B75-9AEC-C5D6BCD3AF8E",
                        "platform" : "com.apple.platform.macosx",
                        "architecture" : "x86_64h",
                        "interface" : "usb",
                        "available" : true,
                        "name" : "My Mac",
                        "modelUTI" : "com.apple.macbookpro-13-retina-four-usb-ports-2020"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.0 (21A328)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone16,2",
                        "identifier" : "FDF16002-0096-4C38-B16C-3707144C0CF4",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-15-pro-max-1",
                        "modelName" : "iPhone 15 Pro Max",
                        "name" : "iPhone 15 Pro Max",
                        "ignored" : false
                      }
                    ]
[   +2 ms] executing: xcrun devicectl --version
[ +128 ms] Exit code 0 from: xcrun devicectl --version
[        ] 348.1
[   +5 ms] executing: xcrun devicectl list devices --timeout 5 --json-output /var/folders/q2/wtdxt7zs0qj25lc78xd_wz2h0000gn/T/flutter_tools.znnnnt/core_devices.o4enPM/core_device_list.json
[  +96 ms] No devices found.
[        ] {
             "info" : {
               "arguments" : [
                 "devicectl",
                 "list",
                 "devices",
                 "--timeout",
                 "5",
                 "--json-output",
                 "/var/folders/q2/wtdxt7zs0qj25lc78xd_wz2h0000gn/T/flutter_tools.znnnnt/core_devices.o4enPM/core_device_list.json"
               ],
               "commandType" : "devicectl.list.devices",
               "environment" : {
                 "TERM" : "xterm-256color"
               },
               "jsonVersion" : 2,
               "outcome" : "success",
               "version" : "348.1"
             },
             "result" : {
               "devices" : [

               ]
             }
           }

[+2768 ms] [
                      {
                        "ignored" : false,
                        "modelCode" : "MacBookPro16,2",
                        "simulator" : false,
                        "modelName" : "MacBook Pro",
                        "operatingSystemVersion" : "14.0 (23A344)",
                        "identifier" : "4117DDB0-D402-5B75-9AEC-C5D6BCD3AF8E",
                        "platform" : "com.apple.platform.macosx",
                        "architecture" : "x86_64h",
                        "interface" : "usb",
                        "available" : true,
                        "name" : "My Mac",
                        "modelUTI" : "com.apple.macbookpro-13-retina-four-usb-ports-2020"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.0 (21A328)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone16,2",
                        "identifier" : "FDF16002-0096-4C38-B16C-3707144C0CF4",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-15-pro-max-1",
                        "modelName" : "iPhone 15 Pro Max",
                        "name" : "iPhone 15 Pro Max",
                        "ignored" : false
                      }
                    ]
[   +1 ms] executing: xcrun devicectl list devices --timeout 5 --json-output /var/folders/q2/wtdxt7zs0qj25lc78xd_wz2h0000gn/T/flutter_tools.znnnnt/core_devices.LNlT4U/core_device_list.json
[  +89 ms] No devices found.
[        ] {
             "info" : {
               "arguments" : [
                 "devicectl",
                 "list",
                 "devices",
                 "--timeout",
                 "5",
                 "--json-output",
                 "/var/folders/q2/wtdxt7zs0qj25lc78xd_wz2h0000gn/T/flutter_tools.znnnnt/core_devices.LNlT4U/core_device_list.json"
               ],
               "commandType" : "devicectl.list.devices",
               "environment" : {
                 "TERM" : "xterm-256color"
               },
               "jsonVersion" : 2,
               "outcome" : "success",
               "version" : "348.1"
             },
             "result" : {
               "devices" : [

               ]
             }
           }`

**Comment by karomak** [comment]
flutter_application_1 % flutter run -v
[   +8 ms] executing: sw_vers -productName
[  +25 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +23 ms] Exit code 0 from: sw_vers -productVersion
[        ] 14.0
[        ] executing: sw_vers -buildVersion
[  +18 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 23A344
[        ] executing: uname -m
[   +9 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +8 ms] executing: sysctl hw.optional.arm64
[   +9 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[ +138 ms] executing: sysctl hw.optional.arm64
[  +12 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[   +9 ms] executing: xcrun xcodebuild -version
[ +449 ms] Exit code 0 from: xcrun xcodebuild -version
[        ] Xcode 15.0.1
           Build version 15A507
[   +3 ms] executing: xcrun xcdevice list --timeout 5
[  +12 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +96 ms] executing: /Users/karolinam/Library/Android/sdk/platform-tools/adb devices -l
[        ] executing: xcrun xcdevice list --timeout 2
[   +2 ms] xcrun simctl list devices booted iOS --json
[        ] executing: xcrun simctl list devices booted iOS --json
[   +5 ms] executing: xcrun simctl list devices booted
[ +195 ms] Exit code 0 from: xcrun simctl list devices booted
[        ] == Devices ==
           -- iOS 17.0 --
               iPhone 15 Pro Max (FDF16002-0096-4C38-B16C-3707144C0CF4) (Booted)
[ +233 ms] {
                      "devices" : {
                        "com.apple.CoreSimulator.SimRuntime.iOS-17-0" : [
                          {
                            "lastBootedAt" : "2023-10-20T08:10:16Z",
                            "dataPath" : "\/Users\/karolinam\/Library\/Developer\/CoreSimulator\/Devices\/FDF16002-0096-4C38-B16C-3707144C0CF4\/data",
                            "dataPathSize" : 2959728640,
                            "logPath" : "\/Users\/karolinam\/Library\/Logs\/CoreSimulator\/FDF16002-0096-4C38-B16C-3707144C0CF4",
                            "udid" : "FDF16002-0096-4C38-B16C-3707144C0CF4",
                            "isAvailable" : true,
                            "logPathSize" : 282624,
                            "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-15-Pro-Max",
                            "state" : "Booted",
                            "name" : "iPhone 15 Pro Max"
                          }
                        ]
                      }
                    }
[+3026 ms] [
                      {
                        "ignored" : false,
                        "modelCode" : "MacBookPro16,2",
                        "simulator" : false,
                        "modelName" : "MacBook Pro",
                        "operatingSystemVersion" : "14.0 (23A344)",
                        "identifier" : "4117DDB0-D402-5B75-9AEC-C5D6BCD3AF8E",
                        "platform" : "com.apple.platform.macosx",
                        "architecture" : "x86_64h",
                        "interface" : "usb",
                        "available" : true,
                        "name" : "My Mac",
                        "modelUTI" : "com.apple.macbookpro-13-retina-four-usb-ports-2020"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.0 (21A328)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone16,2",
                        "identifier" : "FDF16002-0096-4C38-B16C-3707144C0CF4",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-15-pro-max-1",
                        "modelName" : "iPhone 15 Pro Max",
                        "name" : "iPhone 15 Pro Max",
                        "ignored" : false
                      }
                    ]
[   +2 ms] executing: xcrun devicectl --version
[ +128 ms] Exit code 0 from: xcrun devicectl --version
[        ] 348.1
[   +5 ms] executing: xcrun devicectl list devices --timeout 5 --json-output /var/folders/q2/wtdxt7zs0qj25lc78xd_wz2h0000gn/T/flutter_tools.znnnnt/core_devices.o4enPM/core_device_list.json
[  +96 ms] No devices found.
[        ] {
             "info" : {
               "arguments" : [
                 "devicectl",
                 "list",
                 "devices",
                 "--timeout",
                 "5",
                 "--json-output",
                 "/var/folders/q2/wtdxt7zs0qj25lc78xd_wz2h0000gn/T/flutter_tools.znnnnt/core_devices.o4enPM/core_device_list.json"
               ],
               "commandType" : "devicectl.list.devices",
               "environment" : {
                 "TERM" : "xterm-256color"
               },
               "jsonVersion" : 2,
               "outcome" : "success",
               "version" : "348.1"
             },
             "result" : {
               "devices" : [

               ]
             }
           }

[+2768 ms] [
                      {
                        "ignored" : false,
                        "modelCode" : "MacBookPro16,2",
                        "simulator" : false,
                        "modelName" : "MacBook Pro",
                        "operatingSystemVersion" : "14.0 (23A344)",
                        "identifier" : "4117DDB0-D402-5B75-9AEC-C5D6BCD3AF8E",
                        "platform" : "com.apple.platform.macosx",
                        "architecture" : "x86_64h",
                        "interface" : "usb",
                        "available" : true,
                        "name" : "My Mac",
                        "modelUTI" : "com.apple.macbookpro-13-retina-four-usb-ports-2020"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.0 (21A328)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone16,2",
                        "identifier" : "FDF16002-0096-4C38-B16C-3707144C0CF4",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-15-pro-max-1",
                        "modelName" : "iPhone 15 Pro Max",
                        "name" : "iPhone 15 Pro Max",
                        "ignored" : false
                      }
                    ]
[   +1 ms] executing: xcrun devicectl list devices --timeout 5 --json-output /var/folders/q2/wtdxt7zs0qj25lc78xd_wz2h0000gn/T/flutter_tools.znnnnt/core_devices.LNlT4U/core_device_list.json
[  +89 ms] No devices found.
[        ] {
             "info" : {
               "arguments" : [
                 "devicectl",
                 "list",
                 "devices",
                 "--timeout",
                 "5",
                 "--json-output",
                 "/var/folders/q2/wtdxt7zs0qj25lc78xd_wz2h0000gn/T/flutter_tools.znnnnt/core_devices.LNlT4U/core_device_list.json"
               ],
               "commandType" : "devicectl.list.devices",
               "environment" : {
                 "TERM" : "xterm-256color"
               },
               "jsonVersion" : 2,
               "outcome" : "success",
               "version" : "348.1"
             },
             "result" : {
               "devices" : [

               ]
             }
           }

**Comment by dam-ease** [comment]
Thanks for your response. From the logs you shared, I can see that this occurs because of this message

> No devices found.

Can you run `flutter doctor -v` and share the full output?

**Comment by karomak** [comment]
> Thanks for your response. From the logs you shared, I can see that this occurs because of this message
> 
> > No devices found.
> 
> Can you run `flutter doctor -v` and share the full output?

Hi yesterday I updated iOS to 17 at simulator  and for now I have:
`flutter doctor -v

┌──────────────────────────────────┐
│ A new version of Flutter is      │
│ available!                       │
│                                  │
│ To update to the latest version, │
│ run "flutter upgrade".           │
└──────────────────────────────────┘
Could not parse java version from: 

If there is a version please look for
an existing bug
https://github.com/flutter/flutter/issu
es/ and if one does not exist file a
new issue.
[✓] Flutter (Channel stable, 3.13.1, on
    macOS 14.0 23A344 darwin-x64,
    locale en-PL)
    • Flutter version 3.13.1 on channel
      stable at
      /Users/karolinam/Documents/flutte
      r
    • Upstream repository
      https://github.com/flutter/flutte
      r.git
    • Framework revision e1e47221e8 (9
      weeks ago), 2023-08-22 21:43:18
      -0700
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[!] Android toolchain - develop for
    Android devices (Android SDK
    version 34.0.0)
    • Android SDK at
      /Users/karolinam/Library/Android/
      sdk
    • Platform android-34, build-tools
      34.0.0
    • Java binary at:
      /Applications/Android
      Studio.app/Contents/jre/jdk/Conte
      nts/Home/bin/java
    ✗ Could not determine java version
    ✗ Android license status unknown.
      Run `flutter doctor
      --android-licenses` to accept the
      SDK licenses.
      See
      https://flutter.dev/docs/get-star
      ted/install/macos#android-setup
      for more details.

[✓] Xcode - develop for iOS and macOS
    (Xcode 15.0.1)
    • Xcode at
      /Applications/Xcode.app/Contents/
      Developer
    • Build 15A507
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google
      Chrome.app/Contents/MacOS/Google
      Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at
      /Applications/Android
      Studio.app/Contents
    • Flutter plugin can be installed
      from:
      🔨
      https://plugins.jetbrains.com/plu
      gin/9212-flutter
    • Dart plugin can be installed
      from:
      🔨
      https://plugins.jetbrains.com/plu
      gin/6351-dart
    • Java version OpenJDK Runtime
      Environment (build
      1.8.0_242-release-1644-b3-6915495
      )

[✓] VS Code (version 1.83.1)
    • VS Code at /Applications/Visual
      Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] VS Code (version 1.73.0)
    • VS Code at /Applications/Visual
      Studio Code 2.app/Contents
    • Flutter extension version 3.74.0

Scanning for devices is taking a long time
 [✓] Connected device (3 available)
    • iPhone 15 Pro Max (mobile) •
      FDF16002-0096-4C38-B16C-3707144C0
      CF4 • ios            •
      com.apple.CoreSimulator.SimRuntim
      e.iOS-17-0 (simulator)
    • macOS (desktop)            •
      macos
      • darwin-x64     • macOS 14.0
      23A344 darwin-x64
    • Chrome (web)               •
      chrome
      • web-javascript • Google Chrome
      118.0.5993.88

[✓] Network resources
    • All expected network resources
      are available.

! Doctor found issues in 1 category.`

Earlier as I remember it stacked at 'Scanning for devices is taking a long time..'

**Comment by dam-ease** [comment]
Hi @karomak. Thanks for your response and patience. Still can't find a root cause from the logs shared, are you able to do another test by upgrading to the latest flutter version and testing on a real iOS device? Also have you tested with Android and can confirm this is peculiar to only iOS?

**Comment by karomak** [comment]
> Hi @karomak. Thanks for your response and patience. Still can't find a root cause from the logs shared, are you able to do another test by upgrading to the latest flutter version and testing on a real iOS device? Also have you tested with Android and can confirm this is peculiar to only iOS?

Ok, so I upgrade flutter to the latest version and connect it with iOS device - it works correctly. I don't have android device to test it now, but I will try with simulator.
