### ISSUE TITLE
Autocorrect highlighting first part of word when there is a suggestion. IOS17

### ISSUE THREAD

**Issue by iamhyrumharris** [flutter/flutter#136837]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Created new flutter project
2. Added TextField in the body of a scaffold.
3. Run on IOS device that has iOS17

### Expected results

When typing an incorrect word, the word will completely highlight and suggest a new correct word. When you press the space bar it will correct the word.

### Actual results

When typing an incorrect word, the first letter of the incorrect word will be highlighted. When you press spacebar it will change to the correct word. It's only the highlighting that is the issue.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    home: Scaffold(
      appBar: AppBar(
        title: const Text('flutte'),
      ),
      body: 
      TextFormField(),
    ),
  ));
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/flutter/flutter/assets/82340621/eccaff3e-7794-48ad-8efd-60958584e05f)
<img width="306" alt="image" src="https://github.com/flutter/flutter/assets/82340621/13967e16-efc6-4a66-a3c5-81b7f2651041">

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.2, on macOS 14.0 23A344 darwin-x64, locale en-US)
    • Flutter version 3.13.2 on channel stable at /Users/hyrumharris/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (8 weeks ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.12.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google
    Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.81.1)
    • VS Code at /Users/hyrumharris/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (3 available)
    • Azin (mobile)      • 00008130-0009545434C0001C            • ios        • iOS 17.0.3 21A360
    • iPhone 15 (mobile) • 411F51E6-3DED-4E94-BBAB-A25EAB26ADB1 • ios        • com.apple.CoreSimulator.SimRuntime.iOS-17-0
      (simulator)
    • macOS (desktop)    • macos                                • darwin-x64 • macOS 14.0 23A344 darwin-x64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @iamhyrumharris 
There have been couple of autocorrect issues on iOS 17 fixed recently which are in master version. I see that you are in stable 3.13.2, so can you switch to latest master version and run your scenario again to check if the behavior you reported still persists on it ?

`flutter channel master`
`flutter upgrade`

**Comment by iamhyrumharris** [comment]
That fixed it! Thanks!
