### ISSUE TITLE
flutter start should build SkyShell.apk if needed

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#1368]
Rather than downloading a prebuilt SkyShell.apk from the cloud, I think we should teach flutter to run flutter apk and launch that apk instead. This will ensure that we're always using the same commands and down the same code path for development, whether we're using extra services like Firebase/GCM or not. It will have the added benefit that developers will see the correct name and icon for their app when they're debugging in Atom.

cc @mpcomplete, @abarth, @sethladd

**Comment by eseidelGoogle** [comment]
Yes.  We need to separate "build the shell" from "run with this shell", and the "fully prebuilt shell" needs to go away since it doesn't make sense in a world where you can add/remove services from your shell.  `flutter start` can be magical and know how to call the build-the-shell-if-needed code.

Right now I think the shell's only dependency for a `flutter` CLI user is the flutter.yaml file.

**Comment by sethladd** [comment]
cc @tvolkert since we just talked about building

**Comment by mpcomplete** [comment]
To be clear, you're saying we should remove the pre-built SkyShell.apk entirely, and always use a custom-built apk? Even for the simple case? (That would actually simplify the code a lot, since there's a lot of logic around finding the right SkyShell.apk.)

**Comment by abarth** [comment]
> To be clear, you're saying we should remove the pre-built SkyShell.apk entirely, and always use a custom-built apk? Even for the simple case?

If we can make that work, I think it would simplify things.

**Comment by eseidelGoogle** [comment]
Yes.  The pre-built SkyShell.apk is premature optimization in a world where we have lots of services.  Most developers are going to want to add at least one service to the built-in set.

**Comment by sethladd** [comment]
The iOS-equivalent of this issue was filed here: https://github.com/flutter/flutter/issues/1414

**Comment by mpcomplete** [comment]
It's easy enough to make 'flutter start' call 'flutter apk' before running. But this always rebuilds the apk even if nothing changed since the last call to 'flutter start'. Being smart about when to rebuild is not easy, AFAICT, because we don't actually know the list of input files.

**Comment by abarth** [comment]
Yeah, we'll need to approximate the list of dependencies.  For starters, we can try `flutter.yaml` and `AndroidManifest.xml` as the dependencies.  At some point, we'll need to tech up to a fancier dependency tracking system (e.g., make).

**Comment by collinjackson** [comment]
This seems like maybe it's working on Android. Can we close this issue?

We're still launching with SkyShell.apk if an AndroidManifest.xml file isn't found. It seems like we should delete the code paths that use SkyShell.apk, to avoid having two different manifests that can get out of sync (this came up in #1587). We can track that in a separate issue if you want.
