### ISSUE TITLE
Regression in web size

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#136822]
SkiaPerf is reporting a regression in web app size:

https://flutter-flutter-perf.skia.org/e/?begin=1696393467&end=1697646347&keys=X5fca5a031b9159f9008ccc2a5e12abae&requestType=0&selected=commit%3D37453%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253Dnone%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253Dhello_world_web_build_dir_compressed_bytes%252Ctest%253Dweb_size__compile_test%252C&xbaroffset=37451

Guessing it's due to https://github.com/flutter/engine/pull/46973, and that this might be intentional, but filing this issue just in case

cc @eyebrowsoffire @yjbanov

**Comment by eyebrowsoffire** [comment]
Yep, that's expected. Thanks for flagging it, I think we can close.
