### ISSUE TITLE
A problem occurred evaluating project ':flutter_local_notifications'.

### ISSUE THREAD

**Issue by git-amey** [flutter/flutter#136913]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

When I am trying to run the code I am getting the below issue with ':flutter_local_notifications'.

### Expected results

run the code

### Actual results

Launching lib/main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/Users/ameypangaonkar/.pub-cache/hosted/pub.dev/flutter_local_notifications-16.1.0/android/build.gradle' line: 25

* What went wrong:
A problem occurred evaluating project ':flutter_local_notifications'.
> Could not find method namespace() for arguments [com.dexterous.flutterlocalnotifications] on extension 'android' of type com.android.build.gradle.LibraryExtension.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* Where:
Script '/Users/ameypangaonkar/Documents/FlutterDev/sdk/flutter/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy' line: 483

* What went wrong:
A problem occurred configuring project ':flutter_local_notifications'.
> Failed to notify project evaluation listener.
   > Cannot invoke method substring() on null object
   > compileSdkVersion is not specified.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Exception: Gradle task assembleDebug failed with exit code 1

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by stuartmorgan** [comment]
Issues with third-party plugins need to be reported to the authors of those plugins. The issue there is the unconditional use in that plugin's build file of a property that doesn't exist in old versions of AGP.
