### ISSUE TITLE
Crash occurs when using PlatformView and EngineGroup simultaneously

### ISSUE THREAD

**Issue by tianrp** [flutter/flutter#136958]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1.Start an engine using EngineGroup and open a page containing a PlatformView, then remove the PlatformView from the page.
2.Use the same EngineGroup to create a new engine to render a new page containing a PlatformView, which will trigger a crash.

https://github.com/flutter/flutter/assets/42142356/f6e3d0d6-0a5c-4395-b986-0bfd4414bec9

### Expected results

PlatformView should display properly when using EngineGroup.

### Actual results

A crash occurred.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
https://github.com/tianrp/flutter_blank_demo
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
[VERBOSE-3:shared_thread_merger.cc(59)] Check failed: lease_term_ref > 0. lease_term should always be positive when merged, lease_term=0
2023-10-20 14:44:03.206019+0800 Runner[44679:2472818]
 [VERBOSE-2:profiler_metrics_ios.mm(203)] Error retrieving thread information: (os/kern) invalid argument
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
[!] Flutter (Channel [user-branch], 3.13.8-0.0.pre.4, on macOS 13.3.1 22E772610a darwin-arm64, locale zh-Hans-CN)
    ! Flutter version 3.13.8-0.0.pre.4 on channel [user-branch] at 
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Upstream repository  is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL"  to dismiss this error.
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.4)
[✓] IntelliJ IDEA Community Edition (version 2021.3.3)
[✓] VS Code (version 1.82.2)
[✓] Connected device (4 available)
[✓] Network resources
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @tianrp 
I tried running the repo on iOS but getting below error in Xcode:

<img width="272" alt="Screenshot 2023-10-23 at 11 27 19 AM" src="https://github.com/flutter/flutter/assets/67046386/9d146ef7-9223-4057-a2f3-9a1d67e300ab">

Can you provide steps to replicate / run the app ?
Also, can you check if the crash occurs with and without Impeller ?

**Comment by tianrp** [comment]
> 感谢您的报告@tianrp 我尝试在 iOS 上运行存储库，但在 Xcode 中出现以下错误：
> 
> <img alt="屏幕截图 2023 年 10 月 23 日 11 月 27 日 19 点" width="272" src="https://user-images.githubusercontent.com/67046386/277241667-9d146ef7-9223-4057-a2f3-9a1d67e300ab.png">
> 您能提供复制/运行应用程序的步骤吗？ 另外，你能检查一下有叶轮还是没有叶轮时是否会发生碰撞吗？



> 感谢您的报告@tianrp 我尝试在 iOS 上运行存储库，但在 Xcode 中出现以下错误：
> 
> <img alt="屏幕截图 2023 年 10 月 23 日 11 月 27 日 19 点" width="272" src="https://user-images.githubusercontent.com/67046386/277241667-9d146ef7-9223-4057-a2f3-9a1d67e300ab.png">
> 您能提供复制/运行应用程序的步骤吗？ 另外，你能检查一下有叶轮还是没有叶轮时是否会发生碰撞吗？

@darshankawar Please open the project using Android Studio

**Comment by tianrp** [comment]
> Thanks for the report @tianrp I tried running the repo on iOS but getting below error in Xcode:
> 
> <img alt="Screenshot 2023-10-23 at 11 27 19 AM" width="272" src="https://user-images.githubusercontent.com/67046386/277241667-9d146ef7-9223-4057-a2f3-9a1d67e300ab.png">
> Can you provide steps to replicate / run the app ? Also, can you check if the crash occurs with and without Impeller ?

@darshankawar Please open the project using Android Studio

**Comment by darshankawar** [comment]
@tianrp 
Ran it using latest master and stable versions, but didn't observe the crash. Please see below video:


https://github.com/flutter/flutter/assets/67046386/3fb4271d-9cd9-42cc-a89f-c9305b9cfa1d
