### ISSUE TITLE
Make both RichText and Text widgets use the textScaleFactor by default

### ISSUE THREAD

**Issue by DarioCorno** [flutter/flutter#136953]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Passing a simple string to RichText and Text widgets with default values a user would expect the text to be rendered the same way on screen.
While in Text widget the textScaleFactor parameter is not being initialized in the RichText it is, leading to two different text sizes if the end user has a textScaleFactor different from 1.

### Proposal

Would it be a good idea to choose if set or not to set the textScaleFactor for both widgets using the same logic?

**Comment by darshankawar** [comment]
Thanks for the report @DarioCorno 
According to the docs, they seem to have same implementation apart from being the fact that in text widget, the property could be `null`.

https://api.flutter.dev/flutter/widgets/Text/textScaleFactor.html
https://api.flutter.dev/flutter/widgets/RichText/textScaleFactor.html

What exactly is your proposal pertaining to both widgets ?

**Comment by huanghui1998hhh** [comment]
Maybe you need `Text.rich`
