### ISSUE TITLE
When I tried to use Virtual Display (VD) or Hybrid Composition (HC) to load a native TextView to my Flutter page, I found that this was not effective.

### ISSUE THREAD

**Issue by Zsama** [flutter/flutter#136940]
-flutter version: 3.10.3
-My project is the Android original main project that relies on Flutter's module,
-When I tried to use Virtual Display (VD) or Hybrid Composition (HC) to load a native TextView to my Flutter page, I found that this was not effective.
-The implementation steps I refer to: https://flutter.cn/docs/platform-ntegration/android/platform- video.
-I refer to some articles, and I also tried to wrap Expanded or Sizedbox for AndroidView, which still has no effect.
The specific layout of the Flutter is as follows:
Expanded (
                 Child: AndroidView (

                   ViewType: ViewType,

                   layoutDirection: textdirection.ltr,
                   CreationParams: CreationParams,
                   CreationParamsCodec: CONST StandardMessageCodec (),
                 ),,
               ),,
               SIZEDBOX (
                 Height: 250.0,
                 width: 150.0,
                 Child: PlatformViewlink (
                   ViewType: ViewType,
                   SurfaceFactory:
                       (Context, Controller) {
                     Return AndroidViewSurface (
                       Controller: Controller as androidViewController,
                       GESTURERECOGNIZERS: CONST <Factory <OneSequenceGestureCognizer >> {},
                       Hittestbehavior: PlatformViewHittestbehavior.opaque,
                     );
                   },
                   OncreatePlatformView: (Params) {
                     Return PlatformViewsservice.InitsurfaceandroidView (
                       ID: Params.id,
                       ViewType: ViewType,
                       layoutDirection: textdirection.ltr,
                       CreationParams: CreationParams,
                       CreationParamsCodec: CONST StandardMessageCodec (),
                       onFocus: () {
                         Params.onFocusChanged (true);
                       },
                     Cure
                       ..addonplatformViewCreatedListener (Params.onPlatformViewCreated)
                       ..create ();
                   },
                 ),,
               ),,

The attribute values of ViewType are consistent with the original statement.

**Comment by huycozy** [comment]
Hi @Zsama 
When opening an issue, please provide all information following the template. More specifically, please provide the information indicated below:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without using 3rd plugins or production code.
- The output of `flutter doctor -v`
- Reproduction steps, Expected results, Actual results

Thank you!
