### ISSUE TITLE
Build dashboard shows LUCI infra failures as red failures instead of purple

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#136908]
![image](https://github.com/flutter/flutter/assets/2148558/7311b30d-5712-4c4b-a451-2a5aece70862) The following red squares are expected to be purple.

This range of commits had an infra failure on them.

Swarming is showing https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20linux_host_engine/6994/overview as an infra failure due to timeout.

The expectation is infra failures are reflected in the build dashboard the same way.

**Comment by keyonghan** [comment]
Datastore task status is based on the `result` value of buildbucket build response. The possible values are: https://github.com/luci/luci-go/blob/main/common/api/buildbucket/buildbucket/v1/buildbucket-gen.go#L247-L251
```
// Possible values:
//   "CANCELED"
//   "FAILURE"
//   "SUCCESS"
//   "UNSET"
```

However, cocoon is updating infra failed task status based on a non-existent value: `INFRA_FAILURE`: https://github.com/flutter/cocoon/blob/5d3c2be3f4ea9f4e6d8d52ece7f2a5f51d32af7d/app_dart/lib/src/model/appengine/task.dart#L452

Instead, we should update the infra failed tasks based on `failure_reason` whose possible values are (https://github.com/luci/luci-go/blob/main/common/api/buildbucket/buildbucket/v1/buildbucket-gen.go#L229-L234):
```
// Possible values:
//   "BUILDBUCKET_FAILURE"
//   "BUILD_FAILURE"
//   "INFRA_FAILURE"
//   "INVALID_BUILD_DEFINITION"
//   "UNSET"
```
