### ISSUE TITLE
Disable option for SearchBar

### ISSUE THREAD

**Issue by mauricev** [flutter/flutter#136943]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Sometimes, a user interface element is inappropriate/not applicable for the current program conditions and it would be confusing to entire hide this element. The best alternative is being able to disable the element. Flutter provides this capability for some widgets by passing null to the onPressed.

[SearchBar](https://api.flutter.dev/flutter/material/SearchBar-class.html) is a widget utilized by some third party plugins such as [simple_search_dropdown](https://pub.dev/packages/simple_search_dropdown). I can find no way to disable its widget. However, since it utilizes searchbar, it would be good if searchbar could provide an "enabled" parameter. Passing false to this widget would cause it to ignore mouse clicks, tabbing into it and have it display with a grayed out look to let the user know it's disabled. 

### Proposal

Explained above.

**Comment by dam-ease** [comment]
Hi @mauricev. Thanks for proposing this. Can you explain what you mean by `disable`, I think this can be controlled in the `onTap` of the `SearchBar`. Can you help with more information on this proposal.

**Comment by Macacoazul01** [comment]
@dam-ease i'm not sure if this is the only thing that need to be done, but the point here is exposing the enable property of the Textfield widget that composes the SearchBar.

**Comment by Macacoazul01** [comment]
So them it will be possible to block tapping/writing on the bar depending on some condition

**Comment by mauricev** [comment]
As I explain in my first post, there are times when I don't want to hide an inapplicable or inappropriate widget, so I want to have it appear disabled and behave that way as well. It should not respond to the mouse, the tab key or any keyboard key, and it should draw itself grayed out. This is much the same way if I pass "null" to the onPressed parameter of a button.

**Comment by tirth-multipl** [comment]
> As I explain in my first post, there are times when I don't want to hide an inapplicable or inappropriate widget, so I want to have it appear disabled and behave that way as well. It should not respond to the mouse, the tab key or any keyboard key, and it should draw itself grayed out. This is much the same way if I pass "null" to the onPressed parameter of a button.
> 
> Passing null to the onTap of the SearchBar does not disable it.

You could use IgnorePointer/AbsorbPointer.

**Comment by Macacoazul01** [comment]
> You could use IgnorePointer/AbsorbPointer.

Why should I do a complete different implementation from using a custom `TextField` instead of just changing a parameter from true to false on `SearchBar` if the widget is literaly constructed using a `TextField `:

![image](https://github.com/flutter/flutter/assets/57464965/4b082b0b-30c0-4b56-af55-a02f9eb39062)

**Comment by Macacoazul01** [comment]
@HansMuller can you review?

**Comment by tirth-multipl** [comment]
I think PR is merged, this issue can be closed. always handy to use `fixes: #issue-number` in PR to auto-close issues.

**Comment by HansMuller** [comment]
Fixed in #137388
