### ISSUE TITLE
Workflows using macos-runners are backed up.

### ISSUE THREAD

**Issue by CoderDake** [flutter/flutter#136983]
### Is there an existing issue for this?

- [X] I have searched the [existing infra issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-infra)

### Type of Request

infra task

### Infrastructure Environment

Github Workflows, Dependabot,

### What is happening?

workflows that use `runs-on: macos-*` are stalled waiting for a runner to pick them up.
After doing a bit of research i was able to find that flutter/codelabs triggered a collosal number of macos workflows yesterday and has yet to finish working through them 18 hours later.

The number of workflows is >1000, but we can't find out how many specifically since it maxes out github's paging ability which stops at 40 pages.

these workflows seem to have been triggered dependabot which tried to open up 160 PRs to update dependecies in the repos. 

This means that all repos in the org have to wait until the codelabs workflows resolve before their macos workflows can get a runner.

**Comment by CoderDake** [comment]
@kenzieschmoll

**Comment by devoncarew** [comment]
Some drive by comments:

- the dependeabot config for that repo should be simpified so that it opens up far fewer PRs
- the CI for that repo should be updated that we only perform work for the codelabs that have been modified in the PR (for prior art, see the `melos` tool, which I believe has some logic related to files modified in a PR)

**Comment by parlough** [comment]
I was able to cancel the remaining 700+ queued and in-progress workflows on the codelabs repository. Hopefully that starts to free it up.

**Comment by parlough** [comment]
I'm going to close this as we were able to eliminate the backlog and the repository setup was updated to greatly reduce the amount of dependabot PRs.

If anyone has some follow-up work to complete, please reopen or open a new, more specific issue. Thanks!
