### ISSUE TITLE
Flakiness in rollers trying to set up environment

### ISSUE THREAD

**Issue by flar** [flutter/flutter#136923]
The following rolls failed due to some missing files that failed to populate. This looks to be an intermittent issue.

Failed Skia roll: https://github.com/flutter/engine/pull/47108
Failed Fuchsia roll: https://github.com/flutter/engine/pull/47109

**Comment by godofredoc** [comment]
This was caused by the false assumption that local are always complete and that they reliably include the vs_toolchain configuration file.

**Comment by godofredoc** [comment]
Fix: https://flutter-review.googlesource.com/c/recipes/+/51662

**Comment by godofredoc** [comment]
Change has landed and builds should now be working as expected.
