### ISSUE TITLE
[CP] Unmerge threads if the current merger is the only one that's merged.

### ISSUE THREAD

**Issue by dodatw** [flutter/flutter#136937]
### Issue Link

https://github.com/flutter/engine/pull/43652

### Commit Hash

7b7abd1 

### Target

stable

### PR Link

https://github.com/flutter/engine/pull/47274

### Changelog Description

UnMergeNowIfLastOne is called during shell destruction. When there are other shells with threads unmerged and the current destroying shell with thread merged. UnMergeNowIfLastOne should unmerge the threads.

This PR Make UnMergeNowIfLastOne not only unmerge if the current merger is the last merger, but also unmerge if the current merger is the last merger that is merged.

### Impacted Users

all Flutter devs

### Impact Description

PlafromView in FlutterEngineGroup

### Workaround

Don't use FlutterEngineGroup can workaround this issue. But we need FlutterEngineGroup to reduce resource usage.

### Risk

medium

### Test Coverage

yes

**Comment by itsjustkevin** [comment]
Hey @dodatw, for the cherry-pick, a pr needs to be opened to the appropriate branch.  Your pr_link points to the original PR.  

CC @cyanglaz

**Comment by cyanglaz** [comment]
I just created the PR: https://github.com/flutter/engine/pull/47274

**Comment by dodatw** [comment]
> Hey @dodatw, for the cherry-pick, a pr needs to be opened to the appropriate branch. Your pr_link points to the original PR.
> 
> CC @cyanglaz

PR Link Updated

**Comment by zanderso** [comment]
The CP is small and has a test, however the impact of the issue it solves does not appear to be widespread, so a CP this late in the release cycle is probably not appropriate. The fix exists in >1 beta releases, and the next stable is not far off. So, overall this CP not lgtm.

**Comment by itsjustkevin** [comment]
Closing based on above comments by @zanderso
