### ISSUE TITLE
Can't focus text fields in "Dialog > FULLSCREEN" demo in Gallery

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#13690]
Gallery, release build, Android, Pixel 2 XL.
Tap the Dialog demo item, then the FULLSCREEN button, then try to focus "Event name".

Right now, I get nothing. It's as if they're just Text fields.

cc @HansMuller who is working on text fields.

**Comment by jason-simmons** [comment]
That widget is not an editable text field:
    https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/material/full_screen_dialog_demo.dart#L169

**Comment by Hixie** [comment]
Haha, well that would certainly do it.

**Comment by HansMuller** [comment]
The "event name" field in the full-screen dialog demo is now editable and can be edited.
