### ISSUE TITLE
Provide a Cupertino-style TextField

### ISSUE THREAD

**Issue by seenickcode** [flutter/flutter#13695]
Popular components like TextFields, when rendered in the Material Design style, [is not ideal](https://groups.google.com/forum/#!topic/flutter-dev/gBelzRafao4) for iOS users in terms of user experience.  

Please provide a Cupertino-style TextField.

Thanks.

**Comment by Asoseil** [comment]
Where can i find the specs for cupertino text field?

**Comment by xster** [comment]
I agree this is worth adding to the list. 

There are 2 styles that are worth adding to the default bundle: 
A form text entry type illustrated in https://developer.apple.com/ios/human-interface-guidelines/controls/text-fields/ and a search field rounded corner type we can derive from https://developer.apple.com/design/resources/#ios-apps (like the one embedded in the app bar in 'UI Elements')

**Comment by Asoseil** [comment]
<img width="304" alt="screen shot 2018-05-30 at 20 53 37" src="https://user-images.githubusercontent.com/6354203/40741335-9fe3fe66-644b-11e8-97c3-a7292af504fb.png">
I'm working on this but sometimes there are some lacks on the input submission.
I added some options like placeholder, changeEvents, autofocus and so on. I need to understand the right method to validate input and display errors

**Comment by Abubarrett** [comment]
where can i find this? @Asoseil

**Comment by xster** [comment]
@sandrasandeep actually the most default TextField has a RRect border. Let's start with that one. Also let's make it easy to have a clear button (the X button in a circle) in the text field like iOS as well.

**Comment by jinfagang** [comment]
So there is no textfield right now? Have to wait for Q4?

**Comment by xster** [comment]
Pulling various carat UI fidelity issues out of this task https://github.com/flutter/flutter/issues/22879

**Comment by Johnix1337** [comment]
Are there plans to include the auto correct feature present in iOS?
![autocomplete](https://user-images.githubusercontent.com/1659532/46790980-5e63cd00-cd40-11e8-9611-aaa0d152a849.jpg)
