### ISSUE TITLE
Flutter version >= 3.13.0 cause a smartphone reboot in iOS debug mode only

### ISSUE THREAD

**Issue by RexIron** [flutter/flutter#137060]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Using the versions of flutter >= 3.13.0 and XCode15, I noticed that my applications in Debug mode made the iOS smartphone reboot by itself (may be a unknown crash). 

This problem only occurs when I launch applications in Debug mode and does not occur for an application in Release mode and only on iOS device.

Flutter 3.13.7 • channel [user-branch] • unknown source
Framework • revision 2f708eb839 (2 weeks ago) • 2023-10-09 09:58:08 -0500
Engine • revision a794cf2681
Tools • Dart 3.1.3 • DevTools 2.25.0

### Expected results

Smartphone should not reboot

### Actual results

The reboot of the smartphone occurs on different applications with completely different actions

Versions of flutter < 1.13.0 such as 1.10.6 or 3.7.7, for example, works very well.

Is there a problem on versions of flutter >= 3.13.0 that would cause a reboot of the Smartphone?

Having no indication in the debug console or in the systems logs, I see absolutely no or can come the problem.

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel [user-branch], 3.13.7, on macOS 14.0 23A344 darwin-arm64 (Rosetta), locale fr-FR)
    ! Flutter version 3.13.7 on channel [user-branch] at /***/Flutter/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at
      https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] Connected device (1 available)
    ! Error: Browsing on the local area network for iPhone de Dev. Ensure the device is unlocked and attached with a
      cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by dam-ease** [comment]
Hi @RexIron. Thanks for filing this. 
Does this occur on a simulator or a real device? Could you help check on both to see which reboots and share the device information where the crash happens?
Also, are there specific actions being performed when the reboot happens? If possible, you could also share the output of your `flutter run -v` up until the reboot action?
Thank you!

**Comment by RexIron** [comment]
> Hi @RexIron. Thanks for filing this. Does this occur on a simulator or a real device? Could you help check on both to see which reboots and share the device information where the crash happens? Also, are there specific actions being performed when the reboot happens? If possible, you could also share the output of your `flutter run -v` up until the reboot action? Thank you!


I do not have the problem on the iOS 17.0 simulator and physical iPhone 12 (iOS stable 17.0.3), 
But I encounter it on a physical iPhone 13 mini (Stable iOS 17.0.3) and a physical iPhone 14 iOS 17.1 Beta.

Here are the logs that I obtain on the console via flutter run -v when I press a button on my interface, just before smartphone reboot :

````
[+20276 ms] Service protocol connection closed.
[   +3 ms] Lost connection to device.
[   +2 ms] DevFS: Deleting filesystem on the device (file:///private/var/mobile/Containers/Data/Application/F2A89760-1B7B-458E-9965-BAE327CDAF63/tmp/********jjXZZa/********/)
[ +255 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed

[   +6 ms] “flutter run” took 271 576ms.
[   +7 ms] ensureAnalyticsSent: 0ms
[        ] Running 1 shutdown hook
[   +2 ms] Shutdown hooks complete
[        ] exiting with code 0`
````

**Comment by iapicca** [comment]
@RexIron 
your flutter doctor in the initial post gives an informative warning

```
[!] Flutter (Channel [user-branch], 3.13.7, on macOS 14.0 23A344 darwin-arm64 (Rosetta), locale fr-FR)
    ! Flutter version 3.13.7 on channel [user-branch] at /***/Flutter/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at
      https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
  ```
  
  I'd just reinstall flutter
  if you use multiple versions I recommend [fvm](https://fvm.app/)

**Comment by RexIron** [comment]
@dam-ease 
I have reinstall flutter and there is my new flutter doctor : 

````
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.8, on macOS 14.0 23A344 darwin-arm64 (Rosetta), locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] Connected device (1 available)
[✓] Network resources
````


I use fvm to switch to specific flutter version (like the version 3.13.7) and i used `fvm flutter run`, but, the problem is still there

**Comment by jason-simmons** [comment]
See https://github.com/flutter/flutter/issues/136980

**Comment by dam-ease** [comment]
Hi @RexIron. Thanks for your response. Are you making use of any database package? If yes, this could be similar to https://github.com/flutter/flutter/issues/136980. Can you confirm this?

**Comment by RexIron** [comment]
Hi @dam-ease , I actually use Objectbox as my database package. (In version 2.3.1).
I have no Reboot problem on applications not using Objectbox).

So I think the problem is similar, but I don't know how to fix it yet

**Comment by dam-ease** [comment]
Thanks for your response. Kindly, upvote, comment and follow up on the existing issue for updates. I'll be closing this in favour of the already open issue.
Thank you!
