### ISSUE TITLE
Latest Dart roll blocked by deprecated code in the engine

### ISSUE THREAD

**Issue by flar** [flutter/flutter#137054]
See: https://github.com/flutter/engine/pull/47175

Failure at:

```
Analyzing ui...

   info - platform_dispatcher.dart:76:31 - 'UnmodifiableByteDataView' is deprecated and shouldn't be used. Use ByteData.asUnmodifiableView() instead. Try replacing the use of the deprecated member with the replacement. - deprecated_member_use
```

**Comment by zanderso** [comment]
Likely due to https://dart-review.googlesource.com/c/sdk/+/321922

cc @rakudrama @derekxu16

This issue was caught on Friday morning by the monorepo builder: https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/flutter-linux-flutter-plugins/1367/overview.

**Comment by lrhn** [comment]
Flutter makes it impossible to deprecate something and introduce the replacement in the same CL.

Need to first introduce the replacement, then migrate Flutter, and then deprecate.
(Or, prepare a CL to land in Flutter at the same time, which does the migration. Needs more cooperation.)

**Comment by derekxu16** [comment]
revert CL here: https://dart-review.googlesource.com/c/sdk/+/331680

**Comment by flar** [comment]
This looks like a 1-line change, can't we just fix the 1 line and let the Dart roll through?

Or do we have evidence the change will impact more than 1 line in the framework?

**Comment by rakudrama** [comment]
I am going to revert the revert, but without the deprecation annotations.

Then someone can change the Flutter engine to use the new API.
Who is doing this?

**Comment by chinmaygarde** [comment]
xref [go/137054-chat](http://goto.google.com/137054-chat)

**Comment by rakudrama** [comment]
This is the reapplication of the reverted CL with the `@Deprecated` annotations commented-out: https://dart-review.googlesource.com/c/sdk/+/331741

Once that lands it will be possible to change
```
ByteData? _wrapUnmodifiableByteData(ByteData? byteData) =>
    byteData == null ? null : UnmodifiableByteDataView(byteData);
```
to
```
ByteData? _wrapUnmodifiableByteData(ByteData? byteData) =>
    byteData?.asUnmodifiableView();
```

**Comment by flar** [comment]
Here is the list of Unmodifiable hits currently in the our repos:

<details>
<summary>List of `Unmodifiable` references in the engine repo</summary>

```
% git grep Unmodifiable
lib/ui/fixtures/ui_test.dart:    if (result is UnmodifiableByteDataView &&
lib/ui/platform_dispatcher.dart:ByteData? _wrapUnmodifiableByteData(ByteData? byteData) =>
lib/ui/platform_dispatcher.dart:    byteData == null ? null : UnmodifiableByteDataView(byteData);
lib/ui/window/platform_message_response_dart.cc:          byte_buffer = Dart_NewUnmodifiableExternalTypedDataWithFinalizer(
lib/ui/window/platform_message_response_dart.cc:                                        "_wrapUnmodifiableByteData"),
shell/platform/fuchsia/dart-pkg/zircon/test/zircon_tests.dart:      Uint8List fileData = UnmodifiableUint8ListView(mapResult.data);
shell/platform/fuchsia/dart-pkg/zircon/test/zircon_tests.dart:      Uint8List vmoData = UnmodifiableUint8ListView(mapResult.data);
```
</details>

<details>
<summary>List of `Unmodifiable` references in the framework repo</summary>

```
% git grep Unmodifiable
packages/flutter_tools/lib/src/android/application_package.dart:      UnmodifiableMapView<String, Map<String, String>>(_data);
packages/flutter_tools/lib/src/base/context.dart:            UnmodifiableListView<Type>(_reentrantChecks!.sublist(index)));
```
</details>

**Comment by rakudrama** [comment]
> Here is the list of Unmodifiable hits currently in the our repos:

Thanks for the lists.

> 
> List of `Unmodifiable` references in the engine repo
> ```
> % git grep Unmodifiable
> lib/ui/fixtures/ui_test.dart:    if (result is UnmodifiableByteDataView &&
> ```
This needs to be changed. Perhaps to a try-catch containing an attempted write of a byte that was accessed from the result.
> ```
> lib/ui/platform_dispatcher.dart:ByteData? _wrapUnmodifiableByteData(ByteData? byteData) =>
> lib/ui/platform_dispatcher.dart:    byteData == null ? null : UnmodifiableByteDataView(byteData);
> ```
The migration for this is described two messages above.
> ```
> lib/ui/window/platform_message_response_dart.cc:          byte_buffer = Dart_NewUnmodifiableExternalTypedDataWithFinalizer(
> lib/ui/window/platform_message_response_dart.cc:                                        "_wrapUnmodifiableByteData"),
> ```
These should work unchanged.
> ```
> shell/platform/fuchsia/dart-pkg/zircon/test/zircon_tests.dart:      Uint8List fileData = UnmodifiableUint8ListView(mapResult.data);
> shell/platform/fuchsia/dart-pkg/zircon/test/zircon_tests.dart:      Uint8List vmoData = UnmodifiableUint8ListView(mapResult.data);
> ```
Change these to `= mapResult.data.asUnmodifiableView();`
> 
> List of `Unmodifiable` references in the framework repo
> ```
> % git grep Unmodifiable
> packages/flutter_tools/lib/src/android/application_package.dart:      UnmodifiableMapView<String, Map<String, String>>(_data);
> packages/flutter_tools/lib/src/base/context.dart:            UnmodifiableListView<Type>(_reentrantChecks!.sublist(index)));
> ```
These wrapper views are unrelated to the deprecated typed_data classes. No change needed.

**Comment by rakudrama** [comment]
CL available: https://github.com/flutter/engine/pull/47276

**Comment by flar** [comment]
Fixed in https://github.com/flutter/engine/pull/47276
