### ISSUE TITLE
application re-open instead of browser when click on links in application

### ISSUE THREAD

**Issue by wijesijp** [flutter/flutter#137058]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

setup deep linking with the application 
go to application settings and configure always open the application when click on link (abc.com)
now trigger a link in the same domain (abc.com/info)

If the user accidently click always open the app, there is no way to reset it unless the user re-set the configuration. 

### Expected results

Expect a message pop up to allow me to pick open the link on browser or open it with the application.

This happen by default if the user didn't set the configuration

### Actual results

Reopen the application instead of the URL in browser

### Code sample

<details><summary>Code sample</summary>

```dart
if (await canLaunch(url)) {
      await launch(
        url,
        forceSafariVC: false,
        forceWebView: false,
        enableJavaScript: true,
      );
    } 
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19045.3570], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
[√] Chrome - develop for the web
[√] Android Studio (version 2021.2)
[√] IntelliJ IDEA Ultimate Edition (version 2023.2)
[√] VS Code (version 1.83.0)
[√] Connected device (3 available)

• No issues found!
```

</details>

**Comment by dam-ease** [comment]
Hi @wijesijp. Thanks for filing this. I see you are on an older version of Flutter, can you please upgrade to the latest versions to see if this issue still persists? If it does, please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code?
