### ISSUE TITLE
[video_player] The video is upside down when it is recorded at landscape left

### ISSUE THREAD

**Issue by ahmad-whizpool** [flutter/flutter#137047]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Record video in Landscap left
2. now play that video in chewie player
3. video will be up down side

### Expected results

Want to show video down up side

### Actual results

show video in up down

### Code sample

<details><summary>Code sample</summary>

```dart
 void _createChewieController() {
    _chewieController = ChewieController(
      videoPlayerController: _videoPlayerController1,
      autoPlay: true,

      looping: false,
      progressIndicatorDelay:
          bufferDelay != null ? Duration(milliseconds: bufferDelay!) : null,
      hideControlsTimer: const Duration(seconds: 3),
 
    );
  
  }

Chewie(
                      controller: _chewieController!,
                    )
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![1698035731628](https://github.com/flutter/flutter/assets/143999277/0679cd33-e156-460d-b681-07d59baa864a)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
 flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.4, on macOS 12.7 21G816 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.83.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by ahmad-whizpool** [comment]
Hey thank you for the response after reviewing my code i get to no the issue not with video_player. The issue come when i use chewie package. It's not related with video_player. My bad :( , and i really appreciate your time.

**Comment by ahmad-whizpool** [comment]
Hey still getting the issue

**Comment by ahmad-whizpool** [comment]
record video in landscape left mode then check it. player showing it in 180 degree means it up down side

**Comment by ahmad-whizpool** [comment]
it fine in landscape right

**Comment by dam-ease** [comment]
Hi @ahmad-whizpool. Can you share the video you recorded in the landscape right?

**Comment by ahmad-whizpool** [comment]
it fixed when i share it and then play it but when i record it and within App i want to play at the moment it get mirrored. but when i record video in landscapeLeft... It working in landscape Right recorded video

**Comment by dam-ease** [comment]
Okay, got this. Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code ( a single main.dart file as seen in https://github.com/flutter/flutter/issues/137047#issuecomment-1774988258) with reproduction steps?
