### ISSUE TITLE
Move create_updated_flutter_deps.py out of the buildroot.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#137084]
The [buildroot is being merged into the engine](https://github.com/flutter/flutter/issues/67373). This will cause files and directories to be shuffled. That in itself is usually not a concern as accompanying changes to the build rules will account for these changes.

However, some files like [create_update_flutter_deps.py](https://github.com/flutter/buildroot/blob/5ced4367fee2721f6eda34802dc28b1335637c63/tools/dart/create_updated_flutter_deps.py) are used by CI jobs and autorollers. It is hard to tell who uses such scripts, if the location of the scripts is relevant, and if the scripts can be tested.

This issue tracks moving the scripts the the repos that use them.

**Comment by chinmaygarde** [comment]
cc @zanderso @matanlurey @cbracken

**Comment by zanderso** [comment]
Maybe @aam or @whesse might be able to help remember where references to this script come from?

**Comment by chinmaygarde** [comment]
Do you remember if it was just one autoroller?

**Comment by aam** [comment]
Two places come to mind:
* dart->engine autoroller https://skia.googlesource.com/buildbot/+/main/autoroll/go/repo_manager/parent/pre_upload_steps.go#146
* dart monorepo https://dart.googlesource.com/monorepo/+/refs/heads/tools/tools/create_monorepo_deps.dart#39

**Comment by matanlurey** [comment]
This is effectively stale with the monorepo completion.
