### ISSUE TITLE
[linux] Snap build fails with LTO enabled

### ISSUE THREAD

**Issue by knopp** [flutter/flutter#137036]
To reproduce install Flutter via `snap` add add `set(CMAKE_INTERPROCEDURAL_OPTIMIZATION TRUE)` inside `linux/CMakeLists.txt`, before declaring targets.

The run will fails with `LLVMgold.so` unable to load plugins. I'm not sure why gold plugin is used though. The bfd linker will also fail with the following error, depending on platform

```
[  +23 ms]   = note: /snap/flutter/current/usr/bin/ld: /usr/libexec/gcc/x86_64-redhat-linux/13/liblto_plugin.so: error loading plugin: /var/lib/snapd/snap/flutter/141/usr/bin/../../lib/x86_64-linux-gnu/libc.so.6: version
`GLIBC_2.33' not found (required by /usr/libexec/gcc/x86_64-redhat-linux/13/liblto_plugin.so)
```
In case of Fedora 38, the system liblto plugin requires glibc 2.33, but flutter snap ships with 2.31 and the linker trying to load the plugin is using glibc shipped with the snap.

**Comment by huycozy** [comment]
Hi @knopp 
Per your comment [here](https://github.com/superlistapp/super_native_extensions/issues/214#issuecomment-1774119991), I think this issue is more suited to [flutter-snap](https://github.com/canonical/flutter-snap) repository. Do you think it's appropriate?

**Comment by knopp** [comment]
This indeed should be reported to flutter-snap. Closing.
