### ISSUE TITLE
Pigeon: error: type 'FlutterError' does not conform to protocol 'Error'

### ISSUE THREAD

**Issue by renanyoy** [flutter/flutter#137057]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

- add a @FlutterApi() section in pigeon
- generate the files
- try building 

### Expected results

- no errors

### Actual results

- errors

### Code sample

<details><summary>Code sample</summary>

```dart
@FlutterApi()
abstract class MessageFlutterAlibApi {
  void assetPreview(String moduleId, String assetId, Preview preview);
  void modulePreview(String moduleId, Preview preview);
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

<img width="1311" alt="Screenshot 2023-10-23 at 10 43 35" src="https://github.com/flutter/flutter/assets/259671/0eb08bfe-a31d-4f5d-90ba-c4aff9c97efd">
</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.8, on macOS 14.0 23A344 darwin-arm64, locale en-FR)
    • Flutter version 3.13.8 on channel stable at /Users/renanyoy/code/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6c4930c4ac (5 days ago), 2023-10-18 10:57:55 -0500
    • Engine revision 767d8c75e8
    • Dart version 3.1.4
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/renanyoy/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.83.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (3 available)
    • IPhone10.renan (mobile) • 00008020-000640992209002E • ios            • iOS 16.7 20H19
    • macOS (desktop)         • macos                     • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)            • chrome                    • web-javascript • Google Chrome 118.0.5993.70

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment]
(If we go that route we should still keep [this code](https://github.com/flutter/packages/blob/4bf51144c295be03f37287600ce7eee438c5b102/packages/pigeon/lib/swift_generator.dart#L756-L764), and just have a second copy for the new error type, to avoid subtly breaking existing plugins' error handling when they update Pigeon.)

**Comment by renanyoy** [comment]
I think it just miss that FlutterError is an extend from Swift.Error 

```
- @interface FlutterError : NSObject {} 
+ @interface FlutterError : Error {}
```

**Comment by stuartmorgan** [comment]
`FlutterError` is an engine type; changing the type in the engine itself would take several months to propagate to the `stable` Flutter channel, and it would also break plugins that have added the Pigeon-README-recommended workaround for the `HostApi` version of this.

**Comment by renanyoy** [comment]
ok ;)

**Comment by tarrinneal** [comment]
> `FlutterError` is an engine type; changing the type in the engine itself would take several months to propagate to the `stable` Flutter channel, and it would also break plugins that have added the Pigeon-README-recommended workaround for the `HostApi` version of this.

I do wonder if this is something that is going to happen at some point, and making the changes at the pigeon level to allow for the engine change should happen asap. I guess making a `PigeonError` is the solution either way though.

**Comment by hellohuanlin** [comment]
Related issue: https://github.com/flutter/flutter/issues/136081

> so just just a PigeonError extending both FlutterError and Error

The new `PigeonError` should just conform to Swift `Error`, and not extend `FlutterError`. 

> I do wonder if this is something that is going to happen at some point

For long term, We probably shouldn't change `FlutterError` since it will break existing plugins that follow pigeon's recommendation. Instead, we may consider creating a new type (say `FLTError`) in the engine that extends `NSError`, which will be helpful after most plugins bump the flutter version (likely after many years). 

For near term: 
(1) keep using FlutterError with an empty extension, as recommended in current pigeon doc. 
(2) create this `PigeonError` in pigeon. 

For (1), we need to ask developers to to write this empty extension. For (2), we need to ask developers to use this new type. 

Maybe Option (2) is less confusing? I don't have a strong opinion here.

**Comment by renanyoy** [comment]
> #136081

thank you
```
extension FlutterError: Swift.Error {}
```
fix it..

**Comment by masreplay** [comment]
Create a new file for example Error.swift not to be deleted by generation every time

Add the following code

```dart
extension FlutterError: Swift.Error {}
```

**Comment by hellohuanlin** [comment]
Looks like it's been resolved. Closing as complete. Feel free to re-open if needed.
