### ISSUE TITLE
[Impeller] OpenGLES MSAA Follow-up: Support < OpenGL 3.0

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#137093]
In https://github.com/flutter/engine/pull/47030, we support off-screen MSAA by using [`glBlitFramebuffer`](https://registry.khronos.org/OpenGL-Refpages/es3.0/html/glBlitFramebuffer.xhtml), which is only available in 3.0+.

Most devices that use native Open GL (not ANGLE, etc) are 2.0, so we need another way of accomplishing this. As a hack, we can modify the HAL:

```
  // Do not use the resolve_texture, and instead use the MSAA texture only.
  // To preview what this would look like (but should not be implemented this
  // way - would impact the HAL):
  //
  //    @@ render_target.cc @@ CreateOffscreenMSAA
  //    - color0.resolve_texture = color0_resolve_tex;
  //    + color0.resolve_texture = color0_msaa_tex;
```

... but obviously we don't want to check this in, so we should better understand why this works, and what a backend-specific way we could represent it.

**Comment by jonahwilliams** [comment]
We should be able to do this with a draw insead of glBlitFramebuffer. I don't think we'll need the hack :)
