### ISSUE TITLE
[Android] Bump `flutter/packages` linux_android version to 34

### ISSUE THREAD

**Issue by camsim99** [flutter/flutter#137083]
Currently, the `linux_android` target depends on Android 33 ([source](https://github.com/flutter/packages/blob/a64da5ca8a30c6024ffa5516b8334f817d5e2872/.ci.yaml#L28)), but as we begin testing `flutter/packages` Android tests on Android virtual devices running 34 (https://github.com/flutter/flutter/issues/137082), we will need to bump this to a version of Android 34.

FYI that attempting to bump this in the past caused https://github.com/flutter/flutter/issues/135756, so a version besides 34v1 (used in https://github.com/flutter/packages/pull/4804) may need to be used.

**Comment by camsim99** [comment]
@gmackall I recall that you had an understanding as to how the `android_sdk` version defined for `linux_android` was used, something about indicating what SDK would need to be downloaded for use in testing. Is that correct?

**Comment by gmackall** [comment]
Yes, it just pre-downloads a version of the android sdk. 

As I remember, tests will generally still pass if you don't change this though. I believe different versions get downloaded as needed by AGP. So if you, for example, set this to version `33v6`, but then compiled an example app with `compileSdk` set to 31, AGP would still download the right version (but we would then be downloading the dependency as part of an actual testing step, not marked as infra).

**Comment by camsim99** [comment]
Bumping down to P2 as this is to follow getting packages tests running on Android 34 AVDs.
