### ISSUE TITLE
[Windows][UWP] Re-enable UWP support for Xbox app development

### ISSUE THREAD

**Issue by raymon-io** [flutter/flutter#137045]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I understand that UWP support has been removed https://github.com/flutter/flutter/issues/102172 long time ago but UWP is still the only way to make Xbox apps even after years later Microsoft announced UWP's deprecation.

### Proposal

I know Flutter team will probably never consider re-enabling UWP support again but before this issue will be closed, I am asking for some guidelines to see if it is possible to enable the old UWP tooling to work with the current sdk or make Flutter Visual Studio C++ project into UWP compatible.
Few ideas or questions on how to solve this:
1) **Custom engine and tooling**: The last working sdk version that had working UWP support was 2.13 Beta channel. I am looking for guidelines or existing projects that uses custom engine and tooling to build for UWP. The only project that attempts to make custom engine seems to be 2 years old https://github.com/clarkezone/engine
2) **Modifying C++ Project**: Looking at an old UWP Visual Studio Project, Flutter uses IFrameworkView to show the application [FlutterGalleryUWP](https://github.com/clarkezone/fluttergalleryuwp/blob/master/src/FlutterGalleryUWP/App.cpp#L27) . I am wondering if it will be possible to modify the current flutter Windows Desktop C++ project and integrate IFrameworkView and IFrameworkViewSource ?
3) Other options to consider are using [Microsoft Desktop Bridge](https://techcommunity.microsoft.com/t5/modern-work-app-consult-blog/desktop-bridge-8211-the-bridge-between-desktop-apps-and-the/ba-p/316488) but just converting a compiled executable using Desktop App Converter is not going to run on Xbox. Part of the reason is because uwp apps uses different app entrypoint (on appxmanifest file).

**Comment by jonahwilliams** [comment]
I don't think that you're going to have a lot of luck. Aside from the fact that the old tooling barely worked and the windows engine has continually changed - the UWP embedding was also far from done. I would strongly recommend choosing a different technology than Flutter if you're targeting Xbox.

**Comment by raymon-io** [comment]
Looks like discord is the number one place for such discussions. I would say if there was Github discussions or forum that would have been much better for the community, something that is easily searchable. I am pretty sure once in a while some developer would look into the same problem that I discussed so I shared my own experience and findings.
