### ISSUE TITLE
[CP] Cherry-pick package:web update to version 0.3.0 from 0.2.1-beta

### ISSUE THREAD

**Issue by srujzs** [flutter/flutter#137196]
### Issue Link

https://github.com/flutter/flutter/issues/136405

### Commit Hash

https://github.com/flutter/flutter/pull/132445 (there are several commits)

### Target

beta

### PR Link

https://github.com/flutter/flutter/pull/137195

### Changelog Description

Updates package:web version to 0.3.0. Makes some small changes to code to handle the version change.

### Impacted Users

Flutter package/plugin owners

### Impact Description

Without this version change, Flutter will be pinned to a beta package:web version. Flutter plugins can't migrate with a beta version.

### Workaround

Not that I know of.

### Risk

low

### Test Coverage

yes

**Comment by srujzs** [comment]
cc @kevmoo @itsjustkevin

**Comment by itsjustkevin** [comment]
@christopherfujino and @CaseyHillers can you take a look at this cherry pick request? It’s a tough one.

**Comment by christopherfujino** [comment]
Also LGTM
