### ISSUE TITLE
google signin in release mode issue

### ISSUE THREAD

**Issue by eng-sayed** [flutter/flutter#137142]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

When i tried to use google signin in release mode and choose the account which i want to sign in

### Expected results

success login 

### Actual results

always i get this problem PlatformException(sign_in_failed, n3.b: 10: , null, null)

### Code sample

GoogleSignInAccount? res =
                                        await Utils.googleSignIn.signIn();

### Screenshots or Video

![Screenshot 2023-10-24 at 2 38 39 PM](https://github.com/flutter/flutter/assets/56679747/f1c72e6f-df2f-40c0-9a3e-0916661641c7)

### Logs

GoogleSignInAccount? res =
                                        await Utils.googleSignIn.signIn();

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.2 22D49 darwin-x64, locale
    en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.83.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

**Comment by dam-ease** [comment]
Hi @eng-sayed. Thanks for filing this.  I see similar issues currently open and some workarounds, please follow up on similar issues below and check if the workarounds work in your case:

#75224
#33393

Closing this as a duplicate, if you disagree, please comment and I'll reopen this.
Thank you!
