### ISSUE TITLE
[multicast_dns] Exception thrown on calling client.start() on real iOS device: OSError (OS Error: Address already in use, errno = 48)

### ISSUE THREAD

**Issue by SylberG** [flutter/flutter#137155]
### Is there an existing issue for this?

- [x] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run the provided code on a real iOS device.
2. Observe the exception being thrown.

## Issue Description

When running the following code on a real iOS device, the `client.start()` method is throwing an exception with the message `OSError (OS Error: Address already in use, errno = 48)`. It works perfectly on the iOS simulator and real Android devices and emulators. It just wont work on real iOS devices.

## Code Snippet

```dart
import 'package:multicast_dns/multicast_dns.dart';

Future<String?> findMdns() async {
  const String name = '_hyperiond-protobuf._tcp';
  final MDnsClient client = MDnsClient();

  await client.start();
  await for (final PtrResourceRecord ptr in client
      .lookup<PtrResourceRecord>(ResourceRecordQuery.serverPointer(name))) {
    await for (final SrvResourceRecord srv in client.lookup<SrvResourceRecord>(
        ResourceRecordQuery.service(ptr.domainName))) {
      await for (final IPAddressResourceRecord ip
          in client.lookup<IPAddressResourceRecord>(
              ResourceRecordQuery.addressIPv4(srv.target))) {
        return ip.address.address;
      }
    }
  }
  client.stop();
  return null;
}
```

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.8, on macOS 14.0 23A344 darwin-arm64, locale en-NL)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.83.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by huycozy** [comment]
Hi @SylberG 
I can run the example normally without issue on my physical iOS device. Taking look at your flutter doctor output, there is an issue with your connection to device. Please make sure there is no issue and retry.

**Comment by SylberG** [comment]
> Hi @SylberG I can run the example normally without issue on my physical iOS device. Taking look at your flutter doctor output, there is an issue with your connection to device. Please make sure there is no issue and retry.

Hi @huycozy ,

After updating my iPhone 12 Pro to the latest version 17.0.3, the flutter doctor output appears clean with no apparent issues. However, despite this update, the problem persists. To investigate further, I retrieved an old iPhone 7 from my drawer. Testing it with iOS version 15.7.9, and it functions perfectly on this device.

**Comment by huycozy** [comment]
I'm also using iPhone 7, iOS 15.7.9, and don't see the issue there. I don't have a newer device/iOS version to check this. 

Could you share the `multicast_dns` package version in use and the entire output exception?

**Comment by SylberG** [comment]
> I'm also using iPhone 7, iOS 15.7.9, and don't see the issue there. I don't have a newer device/iOS version to check this.
> 
> Could you share the `multicast_dns` package version in use and the entire output exception?

I am using `multicast_dns: ^0.3.2+4`

And this is the output of the catch/exception:

```
Restarted application in 613ms.
flutter: Exception: OS Error: Address already in use, errno = 48
flutter: Stack trace: #0      _NativeSocket.nativeJoinMulticast (dart:io-patch/socket_patch.dart:1793:68)
#1      _NativeSocket.joinMulticast (dart:io-patch/socket_patch.dart:1712:5)
#2      _RawDatagramSocket.joinMulticast (dart:io-patch/socket_patch.dart:2589:13)
#3      MDnsClient.start
<asynchronous suspension>
#4      findMdns
<asynchronous suspension>
#5      HyperionDeviceCubit.detectHyperion
<asynchronous suspension>
```
![image](https://github.com/flutter/flutter/assets/50016143/58e272ae-7152-4aed-9c61-06b0817e0f8d)

**Comment by vashworth** [comment]
Although it presents differently, this is technically the same issue as https://github.com/flutter/flutter/issues/78937, so closing as a duplicate.

**Comment by vashworth** [comment]
Although it presents differently, this is technically the same issue as https://github.com/flutter/flutter/issues/78937, so closing as a duplicate.
