### ISSUE TITLE
Most windows_arm64 testbeds are dead

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#137104]
<img width="1323" alt="Screenshot 2023-10-23 at 3 21 52 PM" src="https://github.com/flutter/flutter/assets/54558023/046712ec-eb7a-439c-a18f-01c660d7b7c7">

This blocks https://github.com/flutter/flutter/issues/134083

**Comment by yusuf-goog** [comment]
They are all working. Must have been some transient network/other outage. We have generally seen them to be pretty consistently up. Closing for now, please reopen if it happens again.
