### ISSUE TITLE
Dart -> Engine roll failing on a dart2wasm web test

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#137120]
The Dart roll to the Engine is failing starting with the roll attempt here https://github.com/flutter/engine/pull/47243 containing the Dart commits here:

https://dart.googlesource.com/sdk.git/+log/901e92d10627..c1afe02a0274

The following change in that list looks related to dart2wasm

https://dart.googlesource.com/sdk.git/+/405a03909c34fda331f4368be8029b49f1e263c5

@osa1

cc @derekxu16 @flar 

The failures are like:

https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Engine%20Drone/1513014/overview

```
00:06 +215 ~6 -1: semantics/semantics_test.dart: platform view is reachable via a hit test [E]                                                                                                         
  Null check operator used on a null value
  unparsed  unparsed      at _awaitHelper closure at file:///b/s/w/ir/cache/builder/src/flutter/prebuilts/linux-x64/dart-sdk/lib/_internal/wasm/lib/async_patch.dart:82:16 (http://localhost:35451/semantics/semantics_test.dart.browser_test.dart.wasm:wasm-function[9404]:0x223442)
  unparsed  unparsed      at closure wrapper at file:///b/s/w/ir/cache/builder/src/flutter/prebuilts/linux-x64/dart-sdk/lib/_internal/wasm/lib/async_patch.dart:82:16 trampoline (http://localhost:35451/semantics/semantics_test.dart.browser_test.dart.wasm:wasm-function[9407]:0x223529)
  unparsed  unparsed      at _rootRunUnary (http://localhost:35451/semantics/semantics_test.dart.browser_test.dart.wasm:wasm-function[1178]:0xc1aa1)
  unparsed  unparsed      at _rootRunUnary tear-off trampoline (http://localhost:35451/semantics/semantics_test.dart.browser_test.dart.wasm:wasm-function[5011]:0x13ec28)
  unparsed  unparsed      at _CustomZone.runUnary (http://localhost:35451/semantics/semantics_test.dart.browser_test.dart.wasm:wasm-function[4876]:0x13cc8f)
  unparsed  unparsed      at _FutureListener.handleValue (http://localhost:35451/semantics/semantics_test.dart.browser_test.dart.wasm:wasm-function[1172]:0xc1802)
  unparsed  unparsed      at _Future._propagateToListeners closure at file:///b/s/w/ir/cache/builder/src/flutter/prebuilts/linux-x64/dart-sdk/lib/async/future_impl.dart:844:33 (http://localhost:35451/semantics/semantics_test.dart.browser_test.dart.wasm:wasm-function[1147]:0xc1052)
```

**Comment by whesse** [comment]
Yes, we can add an additional test builder to the flutter-web monorepo builders.  Our existing builders run all the flutter framework tests, this would be a tester running a suite of flutte engine tests, using the engine_v2/engine_tester recipe configuration run by https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Engine%20Drone/1513014/overview .

Note that all the test builds on the Flutter CI use the same LUCI builder - Linux Engine Drone, while we have a different LUCI builder for each test builder, so only that specific build above has the configuration we want to add.

**Comment by osa1** [comment]
Reverting the problematic commit in https://dart-review.googlesource.com/c/sdk/+/331921.

**Comment by osa1** [comment]
I have a fix in https://dart-review.googlesource.com/c/sdk/+/331922 I abandoned the revert CL.

**Comment by osa1** [comment]
Fix merged as https://github.com/dart-lang/sdk/commit/1b426ea6f82c3f06669a71ac6786800dc8f985e0.

**Comment by gaaclarke** [comment]
Roll working now after the fix.
