### ISSUE TITLE
Error with forgot-password route

### ISSUE THREAD

**Issue by gianglt** [flutter/flutter#137138]
https://firebase.google.com/codelabs/firebase-get-to-know-flutter
At step 5. Add RSVP functionality] there is a minor error at line 71 with the new version of Flutter
_final arguments = state.queryParameters;_
should be replaced with
_final arguments = state.uri.queryParameters;_

**Comment by dam-ease** [comment]
Hi @gianglt. Thanks for filing this. Per this PR https://github.com/flutter/codelabs/pull/1791, I see this has been fixed and should be released soon. See also: firebase-get-to-know-flutter/step_05/lib/main.dart
Thank you!
