### ISSUE TITLE
Firebase tests timing out for `Linux_android android_device_tests` shards

### ISSUE THREAD

**Issue by camsim99** [flutter/flutter#137179]
In `flutter/packages`, the `Linux_android android_device_tests` shards are failing due to Firebase test lab timeouts, regardless of the actual outcome of the tests, with the failure `Infra Failure: Step('Run package tests.Firebase Test Lab') (canceled) (retcode: -15).` e.g. [these failed builds](https://github.com/flutter/packages/pull/5216#issuecomment-1777864982) on the latest `flutter/flutter` --> `flutter/packages` roll attempt.

**Comment by ricardoamador** [comment]
I see what has happened. Taking one of the shard tests it appears that the builds are pending for extended periods of time waiting to be run on firebase.

For example: https://ci.chromium.org/ui/p/flutter/builders/try/Linux_android%20android_device_tests_shard_2%20master/2058/overview

Only 3 sets of tests were run:

1. packages/flutter_plugin_android_lifecycle
Build package - 2 m
Running for packages/flutter_plugin_android_lifecycle - Test was pending for 9 m took 1 m to run.

2. packages/google_maps_flutter/google_maps_flutter
Build package - 2 m
Running for packages/google_maps_flutter/google_maps_flutter - Test was pending for ~ 30 m, took 1 m to run.

3. packages/google_maps_flutter/google_maps_flutter_android
Build package - 2 m 
Running for packages/google_maps_flutter/google_maps_flutter_android - Test was pending for at least 8 m before timeout.

**Comment by ricardoamador** [comment]
After delving into this further: firebase has about 33 devices (27 oriole/33 devices) which these tests target. There are 6 shards which means that we are potentially using 6 devices on each pull request. At the time this was reported there 5 open pull requests, meaning that we are requesting 30 devices across 5 pull requests just for the try pool. So if there were tests running in prod then this will only compound the issue.

**Comment by ricardoamador** [comment]
The option here would be to move some of these to emulators which might already be happening or change the target device for some of these tests depending on pool.

**Comment by stuartmorgan** [comment]
Are there significantly more redfin/30 devices? Because our setup has worked this way for a long time (the device is the only thing we changed recently), and the only times we ever saw incredibly long delays like this were when there was some kind of quasi-outage on the FTL side.

> The option here would be to move some of these to emulators

We recently brought up emulator versions of most of these tests, although we're still having trouble with a few: https://github.com/flutter/packages/blob/main/script/configs/exclude_integration_android_emulator.yaml

Once those are addressed we could consider moving these to postsubmit-only tests (/cc @reidbaker)

**Comment by ricardoamador** [comment]
Hi @stuartmorgan here was the info from the FTL team:

```
FYI: Higher capacity options include: pixel5/30, pixel6/31, pixel7/33, pixel8/34

pixel6/33 (which is what you're using here) is a bit lower capacity
```

**Comment by gmackall** [comment]
This was my mistake, I didn't realize that the device capacities are by version (here is the full output):
```
{
        "id": "oriole",
        "name": "Pixel 6",
        "manufacturer": "Google",
        "form": "PHYSICAL",
        "screenX": 1080,
        "screenY": 2400,
        "supportedVersionIds": [
          "32",
          "33",
          "31"
        ],
        "brand": "google",
        "codename": "oriole",
        "supportedAbis": [
          "arm64-v8a",
          "armeabi-v7a",
          "armeabi"
        ],
        "screenDensity": 420,
        "formFactor": "PHONE",
        "thumbnailUrl": "https://lh3.googleusercontent.com/NHjiDpnVPpfRgpXRroEWwojXOXrnu_V04k5Hpw0_1QmDvcjk5jtdEvJDC8zoL20dz0839Vhy9ow",
        "perVersionInfo": [
          {
            "versionId": "31",
            "deviceCapacity": "DEVICE_CAPACITY_HIGH",
            "directAccessVersionInfo": {
              "directAccessSupported": true
            }
          },
          {
            "versionId": "32",
            "deviceCapacity": "DEVICE_CAPACITY_HIGH"
          },
          {
            "versionId": "33",
            "deviceCapacity": "DEVICE_CAPACITY_LOW"
          }
        ]
      },
```

**Comment by stuartmorgan** [comment]
Closing since the switch to `pather` landed.
