### ISSUE TITLE
[Impeller] Vulkan backend needs to support platforms that only support combined depth-stencil.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#137108]
See https://github.com/flutter/engine/blob/main/impeller/renderer/backend/vulkan/capabilities_vk.cc#L351

We will lose ~25% of all Vulkan capable devices by requiring stencil only formats.

**Comment by gaaclarke** [comment]
Is this just something we can fix in the setup of vulkan?  Like do we ever read from the stencil buffer in a way that its format would change how we have to read from it if it also had the depth information in it?

**Comment by jonahwilliams** [comment]
I'm not sure if the HAL needs any adjustments for combined depth-stencil. We may use a depth buffer in the future, but they're treated as different attachments today.

We likely can't get away with storing the multisampled combined depth-stencil format, but we can't get away with storing the stencil format either, so 🤷

**Comment by bdero** [comment]
I think this is done? We are using the combined depth-stencil on Vulkan and I don't think we need an extension to do so in Vulkan 1.1.

**Comment by jonahwilliams** [comment]
https://github.com/flutter/engine/blob/19ae46afed69f6a14c0fe63e8553f5e74fa8b80f/impeller/renderer/backend/vulkan/capabilities_vk.cc#L352

**Comment by bdero** [comment]
The issue description says "We will lose ~25% of all Vulkan capable devices by requiring stencil only formats" and you're pointing to a line for setting the preferred stencil-only format, but our renderer doesn't use the stencil-only format anymore.

The issue title is about needing supporting the combined depth-stencil textures, which should be supported by basically everything.

**Comment by bdero** [comment]
Ah I think I get it now. Correct me if I'm wrong, but this issue is for adding a _fallback_ route for renderers that happen to select a stencil-only texture, so that we can basically always support stencil-only textures.

I was trying to determine whether this is a real blocker for releasing Impeller on Android. I think either way it isn't.

**Comment by jonahwilliams** [comment]
The problem is that whether or not we use S8 format (which we do not anymore?) we will fail to initialize the vulkan context if S8 is not available.
