### ISSUE TITLE
[autosubmit] Revert PRs should mention the original author and reviewers

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#137156]
See https://github.com/flutter/flutter/pull/137121

When revert PRs are created, they should mention the authors and reviewer's by @ing them. This will ensure the revert PR is surfaced to them in email.

Currently, I can work around this by pinging them in the PR.

**Comment by ricardoamador** [comment]
Fix for this is here: https://github.com/flutter/cocoon/pull/3455
