### ISSUE TITLE
flutter run log for iOS Simulator swallows lines

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#13713]
1. Do a `flutter run` on any flutter app and target the iOS Simulator (tested with hello_world example app)
2. Press one of the keys in the terminal to print more information about the app, e.g. widget hierarchy (w) or semantics tree (S)
3. Notice that only parts of the tree show up in the terminal

The entire tree is still shown in the log provided by the Console app.

/cc @cbracken @xster

**Comment by Hixie** [comment]
This should be fixed now. Closing; @goderbauer, can you verify that it's fixed?
