### ISSUE TITLE
use camera for detection face but my aplication orientation lock it to landscape but i want camera is potrait is posible?

### ISSUE THREAD

**Issue by bagusandrewijaya** [flutter/flutter#137243]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

camera orientation cant change manually

### Expected results

i want changes camera orientation manuall

### Actual results

camera orientation fixed

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@bagusandrewijaya 
Your question is better suited for support channels like StackOverflow, so please ask the same there. Closing from here, as this is more of a how to question rather than a bug report or a feature request.
