### ISSUE TITLE
My editor crashed

### ISSUE THREAD

**Issue by zarub2k** [flutter/flutter#13729]
## Steps to Reproduce

When I try to setup my debug and enable some debugging line, my idea has crashed with errors
## exception

VersionCheckError: VersionCheckError: Command exited with code 69: git log -n 1 --pretty=format:%ad --date=iso
Standard error: 

Agreeing to the Xcode/iOS license requires admin privileges, please run “sudo xcodebuild -license” and then retry this command.

## Flutter Doctor

Paste the output of running `flutter doctor` here.

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by zarub2k** [comment]
It shows some licensing requirement. After agreeing to the license of Xcode, the debug problem is resolved. But I have no idea why I got this error when I worked with Android Emulator.

**Comment by mraleph** [comment]
I think this issue is stale and non-actionable. Please reopen if you experience the crash again.
