### ISSUE TITLE
`flutter ios --init` should not launch XCode

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#1372]
Currently `flutter ios --init` launches Xcode upon completion.  Is that the behavior we want?  It surprised me.  @chinmaygarde @sethladd @devoncarew

**Comment by devoncarew** [comment]
Probably would be unexpected.

Long term will `flutter ios --init ` be necessary? It would be nice if `flutter init` created all the necessary files for a project to be used for either android or iOS development.

**Comment by sethladd** [comment]
ah, I was about to file this issue, too! :)

I didn't expect flutter ios --init to open XCode.

**Comment by sethladd** [comment]
When we change this, we should also update Getting Started, which references this behavior.
