### ISSUE TITLE
[path_provider] Throw rather than crash when run in non-application executable on macOS

### ISSUE THREAD

**Issue by mvaanakoskisc** [flutter/flutter#137259]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create an executable on MacOS which runs Flutter engine.
2. Try to get support directory path in the dart code.
3. Executable crashes to `path_provider_foundation/PathProviderPlugin.swift:36: Fatal error: Unexpectedly found nil while unwrapping an Optional value`

### Expected results

Not to crash when `Bundle.main.bundleIdentifier` is `nil`.

### Actual results

`path_provider_foundation/PathProviderPlugin.swift:36: Fatal error: Unexpectedly found nil while unwrapping an Optional value`

### Code sample

Requires creating an executable which doesn't have a bundle identifier.

### Logs

<details><summary>Logs</summary>

```console
path_provider_foundation/PathProviderPlugin.swift:36: Fatal error: Unexpectedly found nil while unwrapping an Optional value
```

</details>

### Flutter Doctor output

path_provider 2.1.1

**Comment by stuartmorgan** [comment]
> Requires creating an executable which doesn't have a bundle identifier.

In what scenario would that happen? macOS applications are required to have bundle identifiers; is this a command-line executable that's running a headless Flutter engine?

**Comment by mvaanakoskisc** [comment]
Yes, we run some C++ tests using a command-line executable with headless Flutter.

**Comment by stuartmorgan** [comment]
We can make this throw a `PlatformException` instead of crashing outright. It still won't actually work, because the concept of an application support path doesn't apply to something that is not an application.

In general, Flutter is designed to run in applications; lots of things are simply not going to work if you run it in another context. For a test you could replace `path_provider`'s platform implementation with a fake.

**Comment by gspencergoog** [comment]
Unfortunately, since this isn't really a supported scenario, we're going to close this issue. If you encounter a similar issue in a supported use case for Flutter, please feel free to open a new issue with those details.

(Desktop Triage)
