### ISSUE TITLE
[web] Pointer events support multi-view

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#137289]
This is a tracking issue for the work to make pointer events support multi-view on the web.

**Summary**: The [PointerData](https://github.com/flutter/engine/blob/e88745051c6e1ba59f99393e2beb94a6e878f0d2/lib/web_ui/lib/pointer.dart#L39) class has a new `viewId` parameter that we should use to indicate which view received the pointer event.

**Questions**:
1. Are pointer event offsets supposed to be relative to the top-left of the Flutter View that received them?
2. What's the expectation when drag-n-dropping across Flutter Views?
    - Is the down state shared across all views?
    - Should we send move events to the source view and hover events to the destination view?
    
cc @goderbauer @ditman

**Comment by goderbauer** [comment]
> Are pointer event offsets supposed to be relative to the top-left of the Flutter View that received them?

Yes.

> What's the expectation when drag-n-dropping across Flutter Views?

Good question, so far, we haven't really been considering pointer events that span multiple views. I imagine that the down state would be shared across views. I wonder what the current behavior is if a pointer goes down outside of a view and then enters it.
