### ISSUE TITLE
Create a README for auto building cipd packages

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#137282]
A couple of cipd packages used by Flutter CI have been auto built and deployed: https://github.com/flutter/cocoon/tree/main/cipd_packages

We need to provide a detailed doc instructing how to contribute new packages, and then link to the central self-service wiki page.

**Comment by godofredoc** [comment]
Once we have the docs ready let's also work in an announcement.

**Comment by keyonghan** [comment]
https://github.com/flutter/cocoon/pull/3191 to add the wiki.

**Comment by keyonghan** [comment]
More self services are added: https://github.com/flutter/flutter/wiki/Flutter-Self-Service-Index

**Comment by keyonghan** [comment]
Also added release/security ones: https://github.com/flutter/flutter/wiki/Flutter-Self-Service-Index

**Comment by keyonghan** [comment]
Announcement sent. Closing as complete.
