### ISSUE TITLE
Migrate dart-lang/site-www from Github Actions to GCB

### ISSUE THREAD

**Issue by drewroengoogle** [flutter/flutter#137269]
Move https://github.com/dart-lang/site-www/blob/main/.github/workflows/build.yml to Cloud Build

**Comment by keyonghan** [comment]
@drewroengoogle Please feel free to update the priority as you see fit.

**Comment by ricardoamador** [comment]
@drewroengoogle Is this complete? If so please go ahead and close the issue. Thanks.

**Comment by drewroengoogle** [comment]
This is not complete yet, but I'm starting it next 😄

**Comment by drewroengoogle** [comment]
https://github.com/dart-lang/site-www/pull/5418 landed. Need to enable the PR trigger and this should be good to close!

**Comment by drewroengoogle** [comment]
This has been completed!
