### ISSUE TITLE
flutter/packages `release` sometimes fails due to slow task check-in

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#137299]
[This code](https://github.com/flutter/packages/blob/fea24c5b93b46400aab4b4113caa646f6e3566fc/.github/workflows/release.yml#L46-L60) in the flutter/packages CI `release` step was added to fix a problem where [the following section](https://github.com/flutter/packages/blob/fea24c5b93b46400aab4b4113caa646f6e3566fc/.github/workflows/release.yml#L62-L72) would run *before* any of the LUCI checks had checked in (especially when there was an incident causing slow webhooks), causing `release` to run before any of the tests. It's fixed that problem, but the same basic problem now manifests in a different way: sometimes the new code runs before `Linux ci_yaml packages roller` has checked in, causing the step to immediately fail.

This is a lot better than publishing plugins that haven't passed any tests, but it's now a flaky failure, which is not ideal since it then requires manual intervention to re-run to open the tree. Ideally what we want is a step that waits until that step both exits and completes, rather than failing if it's not there yet. I don't see a way to do that with the wait action we're using though, so we may well need to build our own replacement to get that behavior.

**Comment by stuartmorgan** [comment]
This was fixed a while ago by https://github.com/flutter/packages/pull/4911, I just forgot to link it.

**Comment by stuartmorgan** [comment]
I closed this incorrectly, this is the result of https://github.com/flutter/packages/pull/4911

**Comment by stuartmorgan** [comment]
This seems to have gotten much worse recently; GitHub Actions appears to be winning the race against the LUCI test checkin a substantial amount of the time now, causing the step to fail and need manual poking. It's causing manual drain on the team, and package releases getting delayed for sometimes days at a time.

**Infra team, what is the right way to structure a replacement here?** The behavior we need is:
- Wait for all tests to pass, *including ensuring that test checkin has actually happened* (i.e., we must absolutely avoid the old failure case where no LUCI tests would check in for a while due to infra issues, and the step would happily continue because all of the ~0 tests that had checked in passed.)
- If and when that has happened, run a task.

The stock `wait-on-check-action` action doesn't have this ability. Should we be:
- building a replacement GitHub action as Flutter infra?
- transitioning this to some kind of new Cocoon capability?
- something else?

**Comment by stuartmorgan** [comment]
> Is there a link to the failure?

https://github.com/flutter/packages/actions/runs/8192175208/job/22403111361 is an example failure. See https://github.com/flutter/flutter/issues/144663 for some more details.

> As for this github action, is there a timeout that we can control?

As far as I can tell, this action does not have a concept of a test not existing at all, only waiting for a test to finish. I don't think delayed checkin was a use case that its design considered.

**Comment by keyonghan** [comment]
How about adding a sleep step to the action: https://cardinalby.github.io/blog/post/github-actions/implementing-deferred-steps? This is not a real fix, but could help mitigate the issue when github webhook regression happens (before we have a long term fix).

**Comment by stuartmorgan** [comment]
Yes, we could do that. Do we have historical stats on how long checkin generally takes when it has these slowdown regressions? I don't want to make it sleep for *too* long, because while we wouldn't notice for standard triggers (since we have to wait for other tests to run anyway), it could make re-runs annoying if we sleep for too long.

**Comment by keyonghan** [comment]
> Do we have historical stats on how long checkin generally takes when it has these slowdown regressions?

That really depends on how long GitHub issue gets resolved. Whenever the issue is mitigated, the task status should be posted to GitHub in seconds. We can start with a small number like 1 min to mitigate the too-fast github action. If working well, we can readjust the number further.

**Comment by ditman** [comment]
I just saw this happen again, I'll try adding a 60s delay to mitigate as suggested by @keyonghan!

**Comment by ditman** [comment]
I landed the timeout, but should we keep this open to track the fine-tuning of the timeout, or landing a more proper fix?

**Comment by ditman** [comment]
(The extra minute gets completely lost in the CI run; it's barely noticeable)

**Comment by stuartmorgan** [comment]
Let's leave it closed for now, and we can re-open if we have more issues later.
