### ISSUE TITLE
App bars have a smaller padding for actions on the right side

### ISSUE THREAD

**Issue by Craftplacer** [flutter/flutter#137274]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Flutter enforces a [quirk/spec from Material 2](https://m2.material.io/components/app-bars-top#specs) which accommodates the slim appearance of the "more vert" icon. With Material 3, this is [not being done anymore](https://m3.material.io/components/top-app-bar/specs#2be41d8e-79cf-4f1a-abc1-962744ca9291). This also makes other trailing icon buttons who aren't the overflow menu look out of place.

### Proposal

An ideal solution would be to introduce something along the lines of `trailingMargin` or `trailingPadding` *(depending on what your meaning of layout space is)* which controls this. I'd be opposed to completely removing this, to let developers have control (just like `leadingWidth`). Perhaps make it have M2 (8dp) & M3 (16dp) defaults.

Here's a code sample that illustrates the difference:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool _useWorkaround = false;
  
  @override
  Widget build(BuildContext context) {
    final iconBackground = Theme.of(context).colorScheme.primaryContainer;
    return Scaffold(
      appBar: AppBar(
        leading: IconButton(
          icon: ColoredBox(
            color: iconBackground,
            child: Icon(Icons.adaptive.arrow_back),
          ),
          onPressed: () {},
        ),
        title: const Text("Title"),
        actions: [
          IconButton(
            icon: ColoredBox(
              color: iconBackground,
              child: _useWorkaround ? const Icon(Icons.star) : const Icon(Icons.more_vert),
            ),
            onPressed: () => setState(() => _useWorkaround = !_useWorkaround),
          ),
          if (_useWorkaround) const SizedBox(width: 8),
        ],
      ),
    );
  }
}
```

**Comment by darshankawar** [comment]
Thanks for the report @Craftplacer 
I think you are hitting https://github.com/flutter/flutter/issues/91884 which was closed citing https://github.com/flutter/flutter/issues/91884#issuecomment-1730037283
Also check https://github.com/flutter/flutter/issues/115349#issuecomment-1315582192 and https://github.com/flutter/flutter/issues/115349#issuecomment-1317833294 for your reference.

Based on above links and reasoning, I'll close this issue. If you disagree, write in comments and I'll reopen it.
