### ISSUE TITLE
Modify engine v2 recipes to allow passing a version to android emulators via ci.yaml or the config file

### ISSUE THREAD

**Issue by gmackall** [flutter/flutter#137350]
I'm trying to change the android emulator tests in the engine to use android 14 (api 34). They currently are defaulting to api 31. From what I can see in the recipes, they currently don't allow configuration of the emulator version in the ci.yaml or the [config file](https://cs.opensource.google/flutter/engine/+/master:ci/builders/standalone/linux_android_emulator.json?q=linux_android_emulator).

My understanding based on my limited recipes knowledge is that the version is determined by a parameter passed in to methods in `android_virtual_device.py`. For this particular test (from what I can tell) [we initialize this dependency by calling](https://cs.opensource.google/flutter/recipes/+/master:recipes/engine_v2/builder.py;l=111?q=enter_contexts&ss=flutter) `flutter_deps.enter_contexts(android_virtual_device)`, which then calls `android_virtual_device.py` [but doesn't pass a version](https://cs.opensource.google/flutter/recipes/+/master:recipe_modules/flutter_deps/api.py;l=642?q=required_deps&ss=flutter), so it defaults to 31.

For context I've tried a couple of syntaxes here https://github.com/flutter/engine/pull/45737, with no success. Please let me know if I'm missing something!

**Comment by godofredoc** [comment]
@ricardoamador may have some suggestions

**Comment by godofredoc** [comment]
Removing from ticket queue as it is not blocking any workflows.

**Comment by godofredoc** [comment]
Seems like the functionality was removed with https://flutter-review.googlesource.com/c/recipes/+/51120

**Comment by ricardoamador** [comment]
Actually that fixed it for packages and the other repositories. In the other cases we were defaulting to version 31 for everything. I can take a look at why this is not working for Engine tomorrow.

**Comment by ricardoamador** [comment]
I don't see where a version is being supplied in the original config file:
![image](https://github.com/flutter/flutter/assets/32242716/590ec4af-ed91-4bf5-91ca-d236f84d15df)

**Comment by godofredoc** [comment]
I believe it is caused by context vs explicit call. Let's review it tomorrow

**Comment by ricardoamador** [comment]
Working on this now.

**Comment by ricardoamador** [comment]
Okay I have a fix but I need to do some more testing. Will have hopefully have a PR shortly.
