### ISSUE TITLE
Add offset's to SelectionArea callback

### ISSUE THREAD

**Issue by Dall127** [flutter/flutter#137362]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

In the current implementation of SelectionArea, the callback only returns the selected text. However, for my use case, I need a TextSelection object that starts with an offset of 0 for each SelectionArea. This is important for distinguishing objects based on character offsets. For example, the word "can" at offsets 23-26 should be treated differently from another "can" at offsets 80-83, as they might have distinct contextual meanings. This change would also make the SelectionArea more consistent with SelectableText, which returns a TextSelection that includes the offsets.

### Proposal

Modify the code in /lib/src/rendering/paragraph.dart to return the TextSelection object in addition to the string. It appears that all the necessary data is already available; it's just a matter of making a few adjustments to include that data along with the string being returned. Something to note as well, is that the Offset 0 should be (and probably already is by default) the 0th character for each SelectableArea. This way, people can have multiple selectable areas for different languages, getting for example a contextually relevant definition. My current thought is that SelectedContent require a TextSelection variable.

@chunhtai

**Comment by huycozy** [comment]
Thanks for filing the issue. 
I see there's an open issue addressing the case you described https://github.com/flutter/flutter/issues/110594.

Closing this issue as a duplicate, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
