### ISSUE TITLE
flutter_gallery__transition_perf worst_frame_rasterizer_time_millis >2x regression

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#13731]
When https://github.com/flutter/flutter/pull/13696 rolled the engine, it regressed this benchmark by more than 2x.

**Comment by Hixie** [comment]
@jason-simmons volunteered to look at this

**Comment by jason-simmons** [comment]
Traced this to the GpuPathRenderers::kCoverageCounting flag in Skia (https://github.com/google/skia/commit/dde37e5f6613bec240b8ea9336e56f58ba63e418)

**Comment by Hixie** [comment]
@jason-simmons What's the status of this bug? Did you follow up with Skia?

**Comment by Hixie** [comment]
Looks like these two related benchmarks also noticed the regression at the same time, but they're not as badly affected (since they just look at the average times, not the worst times) so it's not as obvious:
    flutter_gallery__transition_perf average_frame_rasterizer_time_millis
    flutter_gallery__transition_perf frames missed_frame_rasterizer_budget_count

**Comment by Hixie** [comment]
This was an expected regression; it's the initial shader compilation which got more expensive in theory as a way to make other things cheaper. @cbracken is working on the initial cost separately.
