### ISSUE TITLE
[webview_flutter] AppSweep reports "Custom SSL Error Handling"

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#137357]
We got a security report saying that the AppSweep tool reports Flutter applications using webview_flutter 4.4.1 as having "Custom SSL Error Handling", which may be a security vulnerability.

We should make sure we have tests that verify that we are correctly handling TLS errors in the webview component by default (though we may provide APIs to override this).

(If we are confident that there is no security vulnerability here we can close this issue.)

**Comment by stuartmorgan** [comment]
We don't do anything custom with SSL errors at the moment that I'm aware of or can find in our code, so we'll need more information from the reporter about what it flagged specifically, and on one platform.
