### ISSUE TITLE
google_maps_flutter_web: migrate to pkg:web from dart:html

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#137374]
* Required to support Wasm.
* Needed by Wonderous app. Parent issue: https://github.com/gskinnerTeam/flutter-wonderous-app/issues/135
* Work *could* happen now, but package cannot be published until the next stable release!

Googlers: [go/wasm-ready-pkg-migrate](https://goto.google.com/wasm-ready-pkg-migrate)

**Comment by navaronbracke** [comment]
@kevmoo I am currently taking a swing at this. I do have some minor questions, but I'll bring those up during review.

**Comment by navaronbracke** [comment]
I am aware of that. In fact, there are some things that I cannot resolve just yet, but I will finish as much as possible and then submit a draft. Then we can gather feedback first.

And yes, I'm currently using v0.3.0, as v0.3.1 is a dev release still :)
