### ISSUE TITLE
[go_router_builder] add onExit parameter

### ISSUE THREAD

**Issue by benjaminledet** [flutter/flutter#137394]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

The parameter `onExit` was [recently added](https://github.com/flutter/packages/pull/4699) to goRouter. I would like to use it with the goRouter builder but it is not possible at the moment.

### Proposal

Add `onExit` as an optional parameter on the go_router_builder api.

**Comment by rorystephenson** [comment]
@chunhtai would you have any pointers for opening a PR for this?

**Comment by ValentinVignal** [comment]
@benjaminledet You should be able to use `onExit` with `go_router: ^14.0.0`

**Comment by rorystephenson** [comment]
@ValentinVignal this issue is for go_router_builder, based on the changelog it doesn't look like onExit is available in go_router_builder yet.

**Comment by ValentinVignal** [comment]
@rorystephenson `GoRouteData` comes from `go_router` not `go_router_builder`.

It is then used by `go_router_builder`
