### ISSUE TITLE
setting backgroundColor for snack bar does not change background color

### ISSUE THREAD

**Issue by deborah-ufw** [flutter/flutter#13732]
## Steps to Reproduce

Here is the code I am using to generate a snackbar. The snackbar generates with the content. However, the snackbar background color is still dark gray in the app.

```dart
  void _confirmAction(BuildContext context) {
    new SnackBar(
        content: new Text(ChqStrings.of(context).confirmed()),
        backgroundColor: Colors.blue,
    );
  }
```

**Comment by jonahwilliams** [comment]
On master I can give the Snackbar a background color, perhaps this was already fixed?

```
Scaffold.of(context).showSnackBar(
  new SnackBar(
    content: const Text('hello'),
    backgroundColor: Colors.red,
));
```

<img width="300" src="https://user-images.githubusercontent.com/8975114/38905291-9e2075ea-4264-11e8-923a-2635b5b77010.png"></img>

**Comment by jonahwilliams** [comment]
CC @deborah-ufw

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
