### ISSUE TITLE
[web:multi-view] Devise a public API for multi-view

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#137377]
Devise a public API for embedding FlutterViews into arbitrary number of elements.

# Goals

- Platform-specific API exposed through `dart:ui_web`, `flutter.js`, or both.
- Supports all CRUD operations.

# Non-goals

- Cross-platform API is out of scope. The desired API is web-specific that deals with DOM elements directly, and provides easy integration path with the host page written in any language, particularly JavaScript.

**Comment by ditman** [comment]
WIP here: https://docs.google.com/document/d/17FrGclUcIpthNEVbz60ZrZhYv8IElESOYclpW9zixcI/edit?resourcekey=0-3sYyBJD_BItOSwSm9pndqg
