### ISSUE TITLE
Dropped frames when spinning time picker clock hand

### ISSUE THREAD

**Issue by LouisCAD** [flutter/flutter#13738]
## Steps to Reproduce
1. Open the Flutter Gallery Android app
2. From the list, open the "Dialog" screen
3. Click on the "Confirmation" button: this will open a popup with a time picker
4. Rotate quickly repeatedly the clock hand like it was a fidget spinner…
You should notice a few lags every few seconds, probably indicating an issue in the garbage collector, or something else. In my cas, I rotate the clock hand at about 3rpm, and I notice a significant lag about every 2-3 seconds

The lags showed up consistently on my Nexus 6P.

IMO, Flutter should be tested on low end devices to flag these issues faster. The issue probably appears on other Android devices regardless of how expensive or how cheap they can be. iOS devices may also be affected.

**Comment by zoechi** [comment]
```
[✓] Flutter (Channel dev, v1.1.9, on Mac OS X 10.14.1 18B75, locale en-AT)
[✓] Connected device (1 available)
    • Pixel XL                  • HT69V0203649  • android-arm64 • Android 9 (API 28)
```

![screenshot_time_picker_dropped_frames](https://user-images.githubusercontent.com/405837/51480729-f9356400-1d91-11e9-8c65-14796c776f9e.png)

**Comment by darshankawar** [comment]
Hi @LouisCAD,
Can you please confirm if you still experience this issue on latest Flutter channel (eg: dev, master) ?

**Comment by LouisCAD** [comment]
Hi @darshankawar, I tried on the latest Flutter Gallery (updated on the 29th of May), and I'm unable to notice dropped frames (with naked eye), so… congratulations to the team on fixing the issue!
