### ISSUE TITLE
[webview_flutter] AppSweep reports "Incorrect TLS Certificate Validation"

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#137358]
We got a security report saying that the AppSweep tool reports Flutter applications using webview_flutter 4.4.1 as having "Incorrect TLS Certificate Validation", which may be a security vulnerability.

We should make sure we have tests that verify that we are correctly handling TLS certificate errors in the webview component by default (though we may provide APIs to override this).

(If we are confident that there is no security vulnerability here we can close this issue.)

**Comment by stuartmorgan** [comment]
We don't do anything custom with TLS at the moment, so we'll need more information from the reporter about what it flagged specifically, and on one platform. Looking at documentation, I found https://www.guardsquare.com/blog/insecure-tls-certificate-checking-in-android-apps, but we don't do any of the things referenced in the examples there.
