### ISSUE TITLE
Launching the app from a non-main monitor shows a white screen on Windows

### ISSUE THREAD

**Issue by OptimisticSean** [flutter/flutter#137321]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

On Flutter 3.16
If building the app using vscode:
1. Drag vscode to any monitor that is NOT the main monitor set in Windows Settings
2. Start debugging or run the app with flutter run

If you have the compiled exe,:
1. Launch the app on a non-main monitor

### Expected results

The app shows something

### Actual results

Nothing is shown

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/20208481/2683d0e2-c594-4ea7-9271-2cad839c5ee2

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel beta, 3.16.0-0.3.pre, on Microsoft Windows [版本 10.0.22621.2428], locale zh-TW)
    • Flutter version 3.16.0-0.3.pre on channel beta at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 476aa717cd (6 days ago), 2023-10-19 20:10:52 -0500
    • Engine revision 91cde06da0
    • Dart version 3.2.0 (build 3.2.0-210.3.beta)
    • DevTools version 2.28.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.5.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33516.290
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.83.1)
    • VS Code at C:\Users\rd1-9\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.74.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.22621.2428]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 118.0.5993.118
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 118.0.2088.61

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by huycozy** [comment]
Hi @OptimisticSean 
I checked this issue on two monitors but the app window is always opening on the primary monitor. Are there any specific settings on your second monitor? 

Could you also check if there are any non-Flutter app having this issue?

**Comment by OptimisticSean** [comment]
Now that you mention it, I do have PowerToys installed and have this option enabled!
![Screenshot 2023-10-26 192610](https://github.com/flutter/flutter/assets/20208481/7b975695-0603-4d16-aa41-257a6bad9616)
Turning that off stops the app from opening on other monitors thus prevent the issue from happening!
