### ISSUE TITLE
[web:multi-view] Teach Renderer to target multiple elements

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#137378]
The `Renderer` class in the web engine currently assumes a single target element that it renders into. It also currently sizes itself based on global information provided by `EmbeddingStrategy`.

To support multiple views, the `Renderer` class must be reshaped to support rendering multiple `Scene` graphs each into its own element with its own size.

**Comment by harryterkelsen** [comment]
Closed with https://github.com/flutter/engine/pull/48301
