### ISSUE TITLE
Clean up memory leaks in Flutter Framework, phase 2.

### ISSUE THREAD

**Issue by polina-c** [flutter/flutter#137311]
Looking for **volunteers** to help with this!!! 🚀

Issues: [all](https://github.com/issues?q=is%3Aissue+label%3A%22a%3A+leak+tracking%22+), [open](https://github.com/issues?q=is%3Aopen+is%3Aissue+label%3A%22a%3A+leak+tracking%22).
PRs: [all](https://github.com/pulls?q=is%3Apr+label%3A%22a%3A+leak+tracking%22+), [open](https://github.com/pulls?q=is%3Aopen+is%3Apr+archived%3Afalse+label%3A%22a%3A+leak+tracking%22+).

Focus areas: 
@polina-c: kick off cleanup for notGCed and [integration with testWidgets](https://docs.google.com/document/d/1bXannXQ8rEtfwxEVd7LDo7xiVu5-QxRoall28MIIFss/edit#heading=h.dk8qogiupft4)

Bigger issue: https://github.com/flutter/flutter/issues/134787

# Goal of this issue 
1. All disposables in FlutterFramework (listed below) should be instrumented for leak tracking ([example](https://github.com/flutter/flutter/pull/137309)).
2. There should not be `.withIgnored(` under [flutter/test](https://github.com/flutter/flutter/tree/master/packages/flutter/test) (or `.withIgnored(` should have a comment that explains why the ignored leaks are ok).

# How to turn on leak tracking?

Leak tracking is now off by default for Flutter Framework. 
To turn it on, follow [the instruction](https://github.com/flutter/flutter/blob/d8a5f3d11bd4216c63766febe0cfb15bf79f44af/packages/flutter/test/flutter_test_config.dart#L30).
To check your changes for leaks, temporarily turn on leak tracking, then, to merge your change, turn it off.

This PR is regularly refreshed and runs bots with leak tracking on, to verify current status of flutter master: https://github.com/flutter/flutter/pull/138581.

# Steps

The goal should be achieved by iteratively instrumenting the objects and removing them from ignore lists:

1. Identify area that you plan to work on and comment on this issue so that I add you to the focus areas above so that we do not duplicate work. If your plans changed, also let me know.  

2. Instrument a new class:
    a. Create PR with instrumentation for one more object, mark it as draft, and check if bots pass
    a. If all bots pass, merge PR
    b. If number of failures is small and they are easy to fix, fix them in the same PR
    c. If failures are massive or unclear, add `withIgnored(` for the instrumented class either [in root folder](https://github.com/flutter/flutter/blob/fe96c2b8dfcbdf45a8e493bca3192d75f7e98ccf/packages/flutter/test/flutter_test_config.dart#L37), or in sub-folder, or in a test file (in setUpAll), or for individual tests.

3. Remove ignored leaks
    a. Identify `withIgnored` on any level ([flutter_test_config.dart](https://github.com/flutter/flutter/blob/961f955af2b139e31117d963e8c533912e2cc0b9/packages/flutter/test/flutter_test_config.dart#L33C18-L33C18), test library or individual test), create draft PR with removed ignored leak types or classes and check if bots pass
    b. If bots pass remove all inclusions (withTracked) for this class/leak-type in subsets of tests and merge the PR
    c. If bots fail, return the `withIgnored`, and add `withTracked` for the leak to one of the failed tests
    d. Check the list of issues/PRs for work in progress for the failure.
    e. If you know how to fix the leak, fix it and merge the PR ([example](https://github.com/flutter/flutter/pull/137812))
    f. If the fix is unclear, remove`withTracked`, create an [issue](https://github.com/flutter/flutter/issues/138455), link the issue in TODO for the test, and merge the PR

4. While testWidgets is not integrated with leak tracking, convert `testWidgets` to `testWidgetsWithLeakTracking` as instructed [in phase 1](https://github.com/dart-lang/leak_tracker/issues/134)

# Templates

Template for steps to repro for leak issues:
1. Locate the test: \<perm link to the test\>
2. (Either) Add parameter `leakTesting = LeakTesting.settings.withTracked(classes: ['TheClass'])`
3. (Or) Remove parameter  `leakTesting = LeakTesting.settings.withIgnored(...)`
5. See the test failing

Template for TODO:
```
TODO(<your alias>): fix the leak and remove ignore (or add tracking for <name of class>)
<link to the issue>
```
Note: your alias in TODO does not mean your obligation to fix the issue, it just indicates you have some knowledge about it.

# Classes to instrument 
Instrumentation for test-only classes is not a goal, but if it is needed to catch other leaks, feel free to instrument them.

- [x] _RouteEntry
- [x] AnimationController
- [ ] AnimationEagerListenerMixin
- [x] BannerPainter
- [x] ChangeNotifier
- [ ] CurvedAnimation
- [x] DisposableBuildContext
- [x] Element
- [x] GestureRecognizer
- [x] Image
- [ ] ImageInfo
- [x] ImageStreamCompleterHandle
- [x] Layer
- [x] MultiDragPointerState
- [x] OverlayEntry
- [x] PerformanceModeRequestHandle
- [x] Picture
- [x] PipelineOwner
- [x] RenderObject
- [x] RestorationBucket
- [x] Route
- [ ] ScrollDragController
- [ ] SelectionOverlay
- [x] SemanticOwner
- [ ] SnapshotPainter
- [x] State
- [x] TextPainter
- [ ] TextSelectionOverlay

(Let me know if I missed something)

**Comment by darshankawar** [comment]
Labeling for tracking.

**Comment by ksokolovskyi** [comment]
Hi @polina-c!
I will be unavailable next week. Then, I plan to continue to work on this issue.

**Comment by polina-c** [comment]
@ksokolovskyi, @droidbg, @LinXunFeng, heads up: leak tracking is off by default now. See section 'How to turn on leak tracking?' in the description for details.

**Comment by polina-c** [comment]
Closing in favor of phase 3: https://github.com/flutter/flutter/issues/141198

**Comment by polina-c** [comment]
- [x] https://github.com/flutter/flutter/pull/134839#issuecomment-1721899337
        - [x] https://github.com/flutter/flutter/pull/133660
