### ISSUE TITLE
Windows Error: Unable to find git in your PATH. Git is installed

### ISSUE THREAD

**Issue by dfvalenciav** [flutter/flutter#137308]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I have windows 10 and i download flutter 3.13.9 .zip file
I unzip file and add route to PATH variable C:\Users\pipet\flutter\bin as documentation. Also i include more routes to path like this one C:\Program Files\Git\bin, C:\Program Files\Git\bin\git.exe, C:\Program Files\Git\cmd, C:\Program Files\Git, 

However always that i run a command related to flutter ex . flutter --version i got the same message on CMD or powerShell or Android Studio :

Error: Unable to find git in your PATH.

I have read several threads but none of solutions propuse there works for me

### Actual results

Error: Unable to find git in your PATH.

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>
Error: Unable to find git in your PATH.

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```Error: Unable to find git in your PATH.

</details>

**Comment by huycozy** [comment]
Hi @dfvalenciav 
Could you check [this](https://stackoverflow.com/a/75511498/5921933) or [this](https://stackoverflow.com/a/76156928/5921933) solution to see if one of them can solve this issue?

**Comment by dfvalenciav** [comment]
Hi, none of those solutions work for me.  I include in PATH C:\Program Files\Git\bin\git.exe;C:\Program Files\Git\cmd;C:\Windows\System32 . Also i use git config --global --add safe.directory C:/tools/flutter-base-dir but the issue persist. 
Windows 10 Pro
git version 2.39.1.windows.1

**Comment by huycozy** [comment]
You should modify `C:/tools/flutter-base-dir` path to yours. In your case, I think the command should be:

```
git config --global --add safe.directory C:/Users/pipet/flutter
```

Or you can try below command to see if it works as well:

```
git config --global --add safe.directory '*'
```

**Comment by dfvalenciav** [comment]
Thanks it works, the issue was that i was using wrong this one git config --global --add safe.directory C:/Users/pipet/flutter
