### ISSUE TITLE
After updating to XCode 15, Flutter app not able to launch on devices lower than iOS 17

### ISSUE THREAD

**Issue by zfc0812** [flutter/flutter#137390]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Update MacOS to Sonoma 14.0
2. Was forced to update XCode to 15.0
3. Flutter app only able to launch on iOS 15, iOS 16 and iOS 17 simulators. However on the real device, it is only able to launch on iOS 17 and not the lower iOS versions

### Expected results

Flutter app able to launch on the supported iOS versions (minimum deployment target for my project is iOS 11)

### Actual results

Flutter app only able to launch on iOS 17, but not able to launch on the lower iOS versions. This issue is not even realised by App Store review team and they approved the app.

### Code sample

My Flutter doctor:
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.0 23A344 darwin-arm64, locale
    en-MY)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2022.3)
[✓] Connected device (1 available)
[✓] Network resources

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.0 23A344 darwin-arm64, locale
    en-MY)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2022.3)
[✓] Connected device (1 available)
[✓] Network resources
```

</details>

**Comment by zfc0812** [comment]
> Hi @zfc0812 What is the iOS minimum deployment target? And which error did you see when running the project? Please share the output of `flutter run -v`.

Minimum deployment target is iOS 11. There is no any error from the project. The app can be launched normally on iOS 15 and iOS 16 simulators. However, it failed to launch on the real  iOS 15 and iOS 16 devices.

**Comment by chenzelin1222** [comment]
dyld: Symbol not found: ___chkstk_darwin
  Referenced from: /private/var/containers/Bundle/Application/5557F3E7-D33B-4D6B-B19E-D4F3623F4F6C/Runner.app/Frameworks/WalletCore.framework/WalletCore (which was built for iOS 13.0)
  Expected in: /usr/lib/libSystem.B.dylib
 in /private/var/containers/Bundle/Application/5557F3E7-D33B-4D6B-B19E-D4F3623F4F6C/Runner.app/Frameworks/WalletCore.framework/WalletCore

**Comment by zfc0812** [comment]
Problem solved after changing the minimum deployment target to iOS 12.

**Comment by huycozy** [comment]
Maybe you are using some of packages that have minimum deployment target as iOS 12, see https://github.com/flutter/flutter/issues/136060#issuecomment-1755558245. Please see #136060 and follow it if it is a similar case.
