### ISSUE TITLE
[Impeller] Make coverage testable in EntityPass.

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#137356]
Coverage computation has become very compex in EntityPass, and it desperately needs a comprehensive suite of tests that can cover all the cases (and more rigidly define its intended behavior) -- some cases are theoretical and don't show up with real entities (yet), and so we can't always rely on goldens for stuff like this. Self-contained pieces like GetSubpassCoverage() don't require any render state.

**Comment by jonahwilliams** [comment]
@bdero I unassigned you because I don't think you are working on this.

**Comment by jonahwilliams** [comment]
For entities themselves we use the display list computed values. For RT sizes we refactored the computation into a testable method in https://github.com/flutter/engine/commit/7cfef4b05c652e34972f6bcd1413b14f01cb8d2e
