### ISSUE TITLE
dart->engine roller blocked on deprecated `UnmodifiableUint8ListView` in plugins

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#137428]
The manual dart roll was reverted for this: https://github.com/flutter/engine/pull/47380#issuecomment-1782993395

Here is the failure:
```
Running command: "dart analyze --fatal-infos" in /b/s/w/ir/x/t/flutter_packages.LUDBEX/packages/image_picker/image_picker_platform_interface
Analyzing image_picker_platform_interface...

info - lib/src/types/picked_file/html.dart:30:38 - 'UnmodifiableUint8ListView' is deprecated and shouldn't be used. Use Uint8List.asUnmodifiableView() instead. Try replacing the use of the deprecated member with the replacement. - deprecated_member_use
```

The linter is being reverted too in https://dart-review.googlesource.com/c/sdk/+/332580

**Comment by gaaclarke** [comment]
dry runs are passing now, closing this out.

**Comment by ditman** [comment]
@gaaclarke @rakudrama this shouldn't be an issue anymore, we've just pushed the removal of `UnmodifiableUint8ListView` from `flutter/packages`, [here](https://github.com/flutter/packages/pull/6177).
