### ISSUE TITLE
Regression in UserAccountsDrawerHeader layout

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#13743]
https://github.com/flutter/flutter/pull/13711 caused a regression in the layout of user user name and email in the user account switcher:

![user-accounts-drawer-header](https://user-images.githubusercontent.com/15253456/34282945-36a33d18-e697-11e7-90ac-99b41279d18d.gif)

**Comment by tvolkert** [comment]
Current status: the PR that triggered this has been (partially) reverted and needs to be re-applied with a fix.

**Comment by yjbanov** [comment]
Thanks for catching this! I'll look into it.

**Comment by yjbanov** [comment]
@goderbauer already started on this. Reassigning to him.
