### ISSUE TITLE
[Impeller] Track if selected heap for buffer memory is coherent, avoid flush.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#137454]
Right now we unconditionally flush because we don't otherwise handle host visible memory that isn't coherent. This adds some overhead, at some point we should make sure we track the different heap types and determine if the heap we've allocated from is already coherent.

Example of processing heap data:

https://github.com/flutter/engine/blob/main/impeller/renderer/backend/vulkan/capabilities_vk.cc#L374-L387

Where we would need to check:

https://github.com/flutter/engine/blob/main/impeller/renderer/backend/vulkan/device_buffer_vk.cc#L42-L45

That is, the `VmaAllocationInfo info` heapIndex will be the index of some specific heap, like https://vulkan.gpuinfo.org/displayreport.php?id=24254#memory . If we know this is coherent, avoid this call.

**Comment by coluzziandrea** [comment]
Hello there!

I'd like to work on this, can you assign it to me?

**Comment by jonahwilliams** [comment]
Sure! but you don't have to be assigned to an issue to work on it btw.

**Comment by ditman** [comment]
This is weird; I'm going to try to make my clone of flutter-engine private so it doesn't auto-close the OG issues :/
