### ISSUE TITLE
Different style for DropDownButton and DropDownMenuItem

### ISSUE THREAD

**Issue by At738343** [flutter/flutter#137493]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

We need this feature in most of the cases

### Proposal

<img width="331" alt="Screenshot 2023-10-29 at 11 17 17 AM" src="https://github.com/flutter/flutter/assets/92142995/41173aed-1045-4950-9430-40739ebabed2">

**Comment by dam-ease** [comment]
Hi @At738343. Thanks for filing this. If I got you right, I see you are trying to achieve a different `TextStyle` in the button different from that of the items. This can be achieved, see the screenshot and code sample below.

<details><summary>ScreenRecord</summary>
<p>

https://github.com/flutter/flutter/assets/53122008/240207e4-3597-41cd-9711-fb513444092a


</p>
</details> 

<details><summary>Code Sample</summary>
<p>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<String> options = <String>['One', 'Two', 'Free', 'Four'];
  String dropdownValue = 'One';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: Container(
        color: Colors.blue,
        child: Center(
          child: DropdownButton<String>(
            value: dropdownValue,
            onChanged: (String? newValue) {
              setState(() {
                dropdownValue = newValue!;
              });
            },
            selectedItemBuilder: (BuildContext context) {
              return options.map((String value) {
                return Text(
                  dropdownValue,
                  style: TextStyle(color: Colors.white),
                );
              }).toList();
            },
            items: options.map<DropdownMenuItem<String>>((String value) {
              return DropdownMenuItem<String>(
                value: value,
                child: Text(value),
              );
            }).toList(),
          ),
        ),
      ),
    );
  }
}

``` 

</p>
</details> 

Kindly let me know if this suits your use case or help with further details on your proposal.

**Comment by At738343** [comment]
i want to change textstyle color like when Dropdown expand i wanna set color black and with collapsed i wanna set white
