### ISSUE TITLE
[web:multi-view] Make keyboard and focus multi-view aware

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#137443]
Currently Flutter always listens to keyboard events assuming it owns the page. That should not be the case in multi-view state (not even in non-full-page single view case).

It's not yet clear what exactly needs to be done here. If we shut off keyboard events at the engine level, that could be limiting for some use-cases. For example, multi-view may be used for reasons _other_ than add-to-app deployments, and the app may still want to handle keyboard globally. At the framework-level, we could be aware of when and which view is currently focused and only listen to keyboard events there while still giving the developer the option to handle keyboard globally. But before fixing keyboard we need to introduce focusability at the `FlutterView` level.

See also: https://github.com/flutter/flutter/issues/137344

**Comment by tugorez** [comment]
Design Doc details can be found in https://github.com/flutter/flutter/issues/141711

**Comment by tugorez** [comment]
Before marking this issue as fixed I need to address a few comments

* https://github.com/flutter/engine/pull/50273#pullrequestreview-1860018340
* https://github.com/flutter/engine/pull/50843#pullrequestreview-1894672586

**Comment by ditman** [comment]
The main engine bits for this issue have landed.

There's some things that are still missing:

* https://github.com/flutter/flutter/issues/144235 (framework side)
  * Alternatively: https://github.com/flutter/flutter/issues/144853
* https://github.com/flutter/flutter/issues/145362 (polish: text fields)
* https://github.com/flutter/flutter/issues/145363 (polish: platform views)

Closing this one!
