### ISSUE TITLE
SearchAnchor error on selecting an item for second time.

### ISSUE THREAD

**Issue by amin79** [flutter/flutter#137469]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

using the demo here https://api.flutter.dev/flutter/material/SearchAnchor-class.html

For SearchAnchor.bar everything works as expected.
But get error on SearchAnchor.bar (first example)

### Expected results

I need to be able to select an item as many time I like.

### Actual results

When I click on the icon button, the dialog opens and I'm able to select an item. but when I click on the iconButton U get the following error:

The following assertion was thrown while handling a gesture:
'package:flutter/src/material/search_anchor.dart': Failed assertion: line 953 pos 12: '_anchor != null': is not true.

(elided 2 frames from class _AssertionError)

Handler: "onTap"
Recognizer: TapGestureRecognizer#c5bf9
    debugOwner: GestureDetector
    state: ready
    won arena
    finalPosition: Offset(40.5, 432.0)
    finalLocalPosition: Offset(19.8, 21.3)
    button: 1
    sent tap down

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [SearchAnchor].

void main() => runApp(const SearchBarApp());

class SearchBarApp extends StatefulWidget {
  const SearchBarApp({super.key});

  @override
  State<SearchBarApp> createState() => _SearchBarAppState();
}

class _SearchBarAppState extends State<SearchBarApp> {
  final SearchController controller = SearchController();

  @override
  Widget build(BuildContext context) {
    final ThemeData themeData = ThemeData(useMaterial3: true);

    return MaterialApp(
      theme: themeData,
      home: Scaffold(
        appBar: AppBar(title: const Text('Search Anchor Sample')),
        body: Column(
          children: <Widget>[
            SearchAnchor(
                searchController: controller,
                builder: (BuildContext context, SearchController controller) {
                  return IconButton(
                    icon: const Icon(Icons.search),
                    onPressed: () {
                      controller.openView();
                    },
                  );
                },
                suggestionsBuilder:
                    (BuildContext context, SearchController controller) {
                  return List<ListTile>.generate(5, (int index) {
                    final String item = 'item $index';
                    return ListTile(
                      title: Text(item),
                      onTap: () {
                        setState(() {
                          controller.closeView(item);
                        });
                      },
                    );
                  });
                }),
            Center(
              child: controller.text.isEmpty
                  ? const Text('No item selected')
                  : Text('Selected item: ${controller.value.text}'),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.16.0-7.0.pre.33, on macOS 14.0 23A344 darwin-x64, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.83.1)
[✓] Connected device (4 available)
[✓] Network resources
```

</details>

**Comment by huycozy** [comment]
Hi @amin79 
I can't reproduce this issue (checking on Web platform). I'm still able to select an item many times. 

Which platform are you seeing this issue? Please provide a recorded video if possible (that would be appreciated).

Also, please provide the entire output of `flutter run -v` as well. Thanks!
