### ISSUE TITLE
Error in  "Get to know Firebase to Flutter"

### ISSUE THREAD

**Issue by SDBHJ** [flutter/flutter#137403]
Hello, I'm a student in Korea who is studying firebase and flutter based on your documents.
By the way, I had found out one mistake on your "Get to know Firebase to Flutter" documents in level 6 which is  "write messages to Firestore". The error is that the picture that you provide for example about leaving messages. The emulator which is on left side are also updating the message, which shouldn't be update in emulator. (App preview)
Thankyou for your great documents.

**Comment by dam-ease** [comment]
Hi @SDBHJ. Thanks for filing this, I see there is a similar open issue to this https://github.com/flutter/flutter/issues/137402. Please comment, upvote and follow up on that issue for updates. 
Closing this in favour of the already existing issue.
Thank you
