### ISSUE TITLE
Flutter Build Web Cache issue when we changing local.env

### ISSUE THREAD

**Issue by syed-growexxer** [flutter/flutter#137420]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. You have a working flutter app with .env file with some base url or encryption key etc.
2. Change any variable in .env file
3. Upload the build on web 
4. you will see the cache is not cleared and new .env variable is not upload.
5. Because flutter only reload cache data when we change something in pages in mainfest.js
6. But when we directly change some asset or.env file it will not reload the cache data and you wont get the new updates

### Expected results

when i change in .env it should update it when web application when it goes live and start working with new client id i should not have to clear the cache first

### Actual results

I have change the google client id in .env file
upload it but when i open live website it is working with old client id
then i had to clear cache then it start working 
it was suppose to take care if that

### Code sample

<details><summary>Code sample</summary>

```dart
class GoogleSignInService {

  static final _googleSignIn = GoogleSignIn(
    clientId: dotenv.env[Environment.clientId],
  );

  static Future<GoogleSignInAccount?> login() => _googleSignIn.signIn();

  static Future logout() => _googleSignIn.disconnect();

}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.7, on macOS 14.0 23A344 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[!] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    ✗ Unable to get list of installed Simulator runtimes.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.83.0)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 1 category.

```

</details>

**Comment by huycozy** [comment]
Hi @syed-growexxer 
Could you share a complete sample code for this issue? (a simple app only reads env variable for eg)
