### ISSUE TITLE
[web:multi-view] define an MVP for FlutterViews participation in host page layout

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#137444]
Currently if you embed a Flutter view onto a custom element (even in single-view case), you have to know in advance how wide and how tall it should be. However, what if the height of the view depends on the available width. In the simplest case, consider Flutter rendering a single paragraph of text. When you squeeze is horizontally the text will break into multiple lines and become taller. We should find a way to provide width (and maybe height) constratings from the host page and output the finished layout result for the host page to size itself according to what Flutter decided to do internally.

**Comment by ditman** [comment]
There has been some preliminary work here:

* https://github.com/goderbauer/engine/pull/3
* https://github.com/flutter/flutter/compare/master...goderbauer:flutter:dynamic-view-sizing-prototype
* https://github.com/goderbauer/scratchpad/pull/6

**Comment by ditman** [comment]
The prototype above needs some extra work in the framework. Related:

* https://github.com/flutter/flutter/issues/134501
* https://github.com/flutter/flutter/issues/137875
