### ISSUE TITLE
luci.flutter.staging linux bots are missing the device_os dimension

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#137427]
device_os for non devicelab machines are expected to be set to `none`

**Comment by godofredoc** [comment]
All the staging builds using linux are failing.

**Comment by godofredoc** [comment]
![image](https://github.com/flutter/flutter/assets/54371434/d2c6be4b-b38f-48aa-a8ea-7c0208c7ba3f)

**Comment by yusuf-goog** [comment]
The bots have the expected field? https://chromium-swarm.appspot.com/bot?id=build796-m9
![image](https://github.com/flutter/flutter/assets/91688203/740a4991-e693-4dfc-b7db-27432ed704ec)

Is there something else that needs to be set as well?

**Comment by yusuf-goog** [comment]
IP address issues fixed with the new GCP project, linux bots have reappeared in the `staging` pool, and this should be resolved.
