### ISSUE TITLE
[Impeller][Android] Poor performance with cached lottie images on Vulkan.

### ISSUE THREAD

**Issue by delfme** [flutter/flutter#137423]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Run this sample
https://github.com/delfme/sample_demo

Tested with master 3.16.0-15.0.pre.27 on iphone 13 pro ios16 and android 13 Xiaomi Mi Lite 5g

Issue occurs when there are many images on the scene.

To reproduce issue for this, I created a simple sample that:
- fetches a lottie json animation
- caches all images inside the animation
- displays a grid view of 60 items.

Rendering and scrolling is blazing fast with Impeller iOS.
Current version of Impeller Android still not on par with iOS.

### Expected results

Same performance as with iOS Impeller

### Code sample

Code available here:
https://github.com/delfme/sample_demo

### Screenshots or Video

Android Impeller not on par with iOS: Raster max about 20-30ms/frame and UI max about 20-40 ms/frame 

https://github.com/flutter/flutter/assets/53510751/2b53e0e4-d605-428f-b85b-183ec29cdf45

iOS Impeller is blazing fast with Raster max below 3ms/frame and average UI max about 10 ms/frame 

https://github.com/flutter/flutter/assets/53510751/673a079a-7256-43bd-b713-06b4a2e96038

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.16.0-15.0.pre.27, on macOS 12.6.5 21G531 darwin-arm64, locale en-IT)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] Connected device (3 available)
[✓] Network resources
```
</details>

**Comment by jonahwilliams** [comment]
Why would performance on Android match iOS, impeller or no impeller?

**Comment by jonahwilliams** [comment]
If you have examples of perofrmance being worse than Skia, I'd be happy to look at that. We'd also need information on what backend is being used on that phone - OpenGLES or Vulkan, as only one is near preview readyness.

**Comment by delfme** [comment]
Hi @jonahwilliams we have this messaging app which is pretty demanding. With iOS Impeller it performs native-like, but not on android.

For example, we have this stickers keyboard which is smooth on iOS and janky on android (both Impeller and Skia).

![D0ADC772-F073-42EA-94A2-F8F77BED2C29](https://github.com/flutter/flutter/assets/53510751/7ee79e1a-836f-4226-bfe6-41c650cf4153)

The janks occur when many images are on the scene, in our case: chat screen, contents feeds and user profile screen.

**Comment by jonahwilliams** [comment]
But again, why would Impeller allow us to deliver iOS like experience on Android? These are very different hardware specs. Our immediate term goal is to just do no worse than Skia, and long term improve performance on Android. Its just not feasible to get comparable performance to iOS

**Comment by delfme** [comment]
> If you have examples of perofrmance being worse than Skia, I'd be happy to look at that.

Is Skia a performance reference for Impeller android or can we expect native-like performance also on impeller android in the future?

> We'd also need information on what backend is being used on that phone - OpenGLES or Vulkan, as only one is near preview readyness.

How to get this data?

**Comment by jonahwilliams** [comment]
Impeller on iOS can't be a native reference point for Android hardware, you'd need a Android framework built application for that.

RE: rendering backend, you can check in the device logs when you flutter run. It should print something like:

```
jonahwilliams-macbookpro3:macrobenchmarks jonahwilliams$ android-debug 
Launching lib/main.dart on Pixel 6 Pro in debug mode...
Running Gradle task 'assembleDebug'...                             30.0s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app-debug.apk...          20.5s
E/flutter (12814): [ERROR:flutter/shell/platform/android/android_context_vulkan_impeller.cc(45)] Using the Impeller rendering backend (Vulkan with Validation Layers).
Syncing files to device Pixel 6 Pro...                              29ms
```

Keep in mind that debug mode will be running much slower than profile mode with Impeller, as we have additional debugging enabled in the engine.

**Comment by delfme** [comment]
> But again, why would Impeller allow us to deliver iOS like experience on Android? These are very different hardware specs. Our immediate term goal is to just do no worse than Skia, and long term improve performance on Android. Its just not feasible to get comparable performance to iOS

Yea I used wrong sentence. I meant to say, performance good enough to have a smooth UI also on android. We are testing on mid and high end phones and we dont notice much difference. Thought to share that sample in the hope that you can see something.

**Comment by delfme** [comment]
On my phone it is Vulcan:

```
Installing build/app/outputs/flutter-apk/app-debug.apk...           8.8s
E/flutter (24953): [ERROR:flutter/shell/platform/android/android_context_vulkan_impeller.cc(45)] Using the Impeller rendering backend (Vulkan with Validation Layers).
```

I also gets some logs that I always considered as spamming from system but maybe they refers to real issues:

```
A Dart VM Service on 2109119DG is available at: http://127.0.0.1:56933/bB1g1v7C0II=/
The Flutter DevTools debugger and profiler on 2109119DG is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:56933/bB1g1v7C0II=/
E/qdgralloc(24953): GetGpuPixelFormat: No map for format: 0x38
E/AdrenoUtils(24953): <validate_memory_layout_input_parmas:1970>: Unknown Format 0
E/AdrenoUtils(24953): <adreno_init_memory_layout:4720>: Memory Layout input parameter validation failed!
E/qdgralloc(24953): GetGpuResourceSizeAndDimensions Graphics metadata init failed
E/Gralloc4(24953): isSupported(1, 1, 56, 1, ...) failed with 1
E/GraphicBufferAllocator(24953): Failed to allocate (4 x 4) layerCount 1 format 56 usage b00: 1
E/AHardwareBuffer(24953): GraphicBuffer(w=4, h=4, lc=1) failed (Unknown error -1), handle=0x0
E/qdgralloc(24953): GetGpuPixelFormat: No map for format: 0x38
E/AdrenoUtils(24953): <validate_memory_layout_input_parmas:1970>: Unknown Format 0
E/AdrenoUtils(24953): <adreno_init_memory_layout:4720>: Memory Layout input parameter validation failed!
E/qdgralloc(24953): GetGpuResourceSizeAndDimensions Graphics metadata init failed
E/Gralloc4(24953): isSupported(1, 1, 56, 1, ...) failed with 1
E/GraphicBufferAllocator(24953): Failed to allocate (4 x 4) layerCount 1 format 56 usage b00: 1
E/AHardwareBuffer(24953): GraphicBuffer(w=4, h=4, lc=1) failed (Unknown error -1), handle=0x0
E/qdgralloc(24953): GetGpuPixelFormat: No map for format: 0x38
E/AdrenoUtils(24953): <validate_memory_layout_input_parmas:1970>: Unknown Format 0
E/AdrenoUtils(24953): <adreno_init_memory_layout:4720>: Memory Layout input parameter validation failed!
E/qdgralloc(24953): GetGpuResourceSizeAndDimensions Graphics metadata init failed
E/Gralloc4(24953): isSupported(1, 1, 56, 1, ...) failed with 1
E/GraphicBufferAllocator(24953): Failed to allocate (4 x 4) layerCount 1 format 56 usage b00: 1
E/AHardwareBuffer(24953): GraphicBuffer(w=4, h=4, lc=1) failed (Unknown error -1), handle=0x0
E/qdgralloc(24953): GetGpuPixelFormat: No map for format: 0x38
E/AdrenoUtils(24953): <validate_memory_layout_input_parmas:1970>: Unknown Format 0
E/AdrenoUtils(24953): <adreno_init_memory_layout:4720>: Memory Layout input parameter validation failed!
E/qdgralloc(24953): GetGpuResourceSizeAndDimensions Graphics metadata init failed
E/Gralloc4(24953): isSupported(1, 1, 56, 1, ...) failed with 1
E/GraphicBufferAllocator(24953): Failed to allocate (4 x 4) layerCount 1 format 56 usage b00: 1
E/AHardwareBuffer(24953): GraphicBuffer(w=4, h=4, lc=1) failed (Unknown error -1), handle=0x0
D/impeller_issues(24953): MiuiProcessManagerServiceStub setSchedFifo
I/MiuiProcessManagerImpl(24953): setSchedFifo pid:24953, mode:3
```

**Comment by jonahwilliams** [comment]
I've retitled the issue to reflect the specific issue. We can look into this and see if there is anything obvious that could be improved.

**Comment by delfme** [comment]
Thx. I really appreciate it.
What Raster max and Ui max values you get on your Pixel 6 Pro?

**Comment by jonahwilliams** [comment]
# Skia

Starts out incredibly slow but speeds up

<img src="https://github.com/flutter/flutter/assets/8975114/0e54a83e-9c35-4288-ac81-2af4e0433b3a" width="200"/>

<img src="https://github.com/flutter/flutter/assets/8975114/e8cb456b-5038-4ed6-81e3-dea9a3232d30" width="200"/>

# Impeller

Seems to have more consistent performance, though I notice the UI thread seems to block a bit more during encoding.

<img src="https://github.com/flutter/flutter/assets/8975114/0520742a-4b77-4479-b5fa-bea566e567c0" width="200"/>

**Comment by jonahwilliams** [comment]
@delfme can you share a timeline from the Impeller recording you took?

**Comment by delfme** [comment]
Timeline
https://drive.google.com/file/d/10grUyuycXl48pIKvT0yk83VeebNizsaU/view?usp=sharing

<img width="1262" alt="Screenshot 2023-10-27 at 19 55 55" src="https://github.com/flutter/flutter/assets/53510751/a9a944d0-0961-4acc-a1f5-3c217769cb22">

Indeed I think there is hope. It seems it is images issue but mostly due to animations.
I changed a bit the sample to let you notice the difference when using still images.
Will share it soon.

**Comment by jonahwilliams** [comment]
@delfme that is a Skia trace

**Comment by delfme** [comment]
Here it is:
Please try to set `testStillImages` to true. In that case we will load still images and situation gets back under control, Raster max and Ui max below 16 ms/frame most of time.

https://github.com/delfme/sample_demo/blob/27e88cefa4a088fbe4b5cee5291925f960c07334/lib/main.dart#L100

**Comment by delfme** [comment]
> @delfme that is a Skia trace

Is this correct?
https://drive.google.com/file/d/1HSYznWaATAi-QjQSVfzpbbGXcCgGRLT4/view?usp=sharing

**Comment by delfme** [comment]
> # Skia
> Starts out incredibly slow but speeds up
> 
> <img alt="" width="200" src="https://user-images.githubusercontent.com/8975114/278720364-0e54a83e-9c35-4288-ac81-2af4e0433b3a.png"> <img alt="" width="200" src="https://user-images.githubusercontent.com/8975114/278720346-e8cb456b-5038-4ed6-81e3-dea9a3232d30.png">
> # Impeller
> Seems to have more consistent performance, though I notice the UI thread seems to block a bit more during encoding.
> 
> <img alt="" width="200" src="https://user-images.githubusercontent.com/8975114/278720635-0520742a-4b77-4479-b5fa-bea566e567c0.png">

Woah I never see your Impeller screenshot. If we get when scrolling, that would be native.

**Comment by jonahwilliams** [comment]
That is better. So something I can point out, it looks like we're bottlenecked on the GPU on your phone.

![image](https://github.com/flutter/flutter/assets/8975114/9d48431b-f44f-4d44-a6e0-db51ef4fb980)

**Comment by delfme** [comment]
The feeling is that a fix would increase smoothness also everywhere, coz although we use lottie, we are caching/animating the internal images, which is not really like using lottie.

Here is for visual comparison, see screen transition on the two platforms (relase mode)


https://github.com/flutter/flutter/assets/53510751/549e719a-caab-434e-8068-deb862c4046e



https://github.com/flutter/flutter/assets/53510751/edfb5ce5-b383-4166-a8c5-e6885a101e2e

**Comment by jonahwilliams** [comment]
@delfme the timeline you posted shows pretty consisted 12ms frame times. Is this a high frame rate device or is it 60fps? This doesn't seem to match the video you posted which is showing ~30ms frame times.

**Comment by delfme** [comment]
Refresh rate is set to 90Hz specs below. It is mid end phone but pretty smooth.

![21D8D333-6B9E-4669-9025-96A3658D9074](https://github.com/flutter/flutter/assets/53510751/fde2c2c7-a514-4667-b87b-976771a514b2)
![77443722-E404-4A04-9A2E-98AE99545F73](https://github.com/flutter/flutter/assets/53510751/77c46331-948e-4d79-b843-30520dce7c46)

**Comment by delfme** [comment]
But jittery occurs also with simpler screen. This is a bunch of texts and small-sized still images (20KB each), no logic is running underneath during this scrolling. I will share a timeline soon.


https://github.com/flutter/flutter/assets/53510751/bd0cc102-1ec0-4723-8bfe-0bdc46783e2a

**Comment by delfme** [comment]
Timeline
https://drive.google.com/file/d/1EraTdg7cPA1xMXkvD1s_CeA8i8RIJ38m/view?usp=sharing

**Comment by jonahwilliams** [comment]
@delfme that looks like an entirely different application then the one you originally filled. Again, let me ask: The original bug you filled shows raster times in excess of 20ms. The timeline you posted afterwards shows ~12ms.

Now you'e posted a second app/timeline but no code for this either.

I can't really help you if you can't nail down the specific issue you're filling a bug for. We don't really want to have "make Impeller faster bugs" open. Thats already the goal.

**Comment by delfme** [comment]
I tested the sample code with same phone. Prolly I switched from 60Hz to 90Hz and vice-versa while testing and shared same timeline with different device settings. Let me share here the 2 timelines for the sample at both 60Hz and 90Hz.

`testStillImages` is used to reproduce two cases:
A) property set to `true` will load cached lotties (the heavy case where engine struggles with many janks). 
B) property set to `false` will load network still images (lightweight case where some janks are still noticeable).

https://github.com/delfme/sample_demo/blob/27e88cefa4a088fbe4b5cee5291925f960c07334/lib/main.dart#L100

### Timelines
CASE A)
Timeline with phone display set at 90Hz and max performance mode
https://drive.google.com/file/d/1cK6vvDy4RrYJmgRFDvqwWWySUzdUVtMD/view?usp=sharing

Timeline with phone display set at 60Hz
https://drive.google.com/file/d/1Mk7Iv9IkrK_HUnfEA79MPtWXRkOShsZn/view?usp=sharing

CASE B)
Timeline sample code 60Hz 
https://drive.google.com/file/d/1IbktfHi0GLCWbdvx5PttfeYQiJKoruoJ/view?usp=sharing

Timeline sample code 60Hz 
https://drive.google.com/file/d/16OO-WO8gvMpykOnK9CJEjEfyKkvNUjvl/view?usp=sharing

**Comment by delfme** [comment]
> Now you'e posted a second app/timeline but no code for this either.

@jonahwilliams I will try to create another sample for the case where I'm hit by performance issue "on Xiaomi mid-end android phone when no heavy widgets are on the scene". But that will take me time, just shared that other timeline to let you see what I meant.

**Comment by jonahwilliams** [comment]
Thank you!

**Comment by jonahwilliams** [comment]
@delfme you never provided the follow ups needed to triage this bug, so I'm closing the issue. Its impossible to make sense of the information you've provided which is all over the place. Please make an effort to file more focused and clear bugs.
