### ISSUE TITLE
Android compilation time regression (12%)

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#137432]
benchmark: [skiaperf](https://flutter-flutter-perf.skia.org/e/?begin=1698368710&end=1698427832&keys=X6204acaf96c14c08af685caed6b33add&num_commits=50&request_type=1&xbaroffset=37678)

Introduced in https://github.com/flutter/flutter/pull/136880

cc @mkustermann @reidbaker

**Comment by gaaclarke** [comment]
Marking it a P0 to get eyes on it to make a decision, not to say everything has to be dropped to fix it.  P0 is supposed to be used for regressions I believe.

**Comment by reidbaker** [comment]
I imagine that this is an okay outcome. We would prefer slower build times and the default optimizations for Android to be on. There's not really a way that we could make this faster.

**Comment by camsim99** [comment]
PR reverted in https://github.com/flutter/flutter/commit/4cae1af41d138c29e59eac2c9dcfad21421b98c4

**Comment by gaaclarke** [comment]
Here's the other benchmark this moved positively: https://flutter-flutter-perf.skia.org/e/?begin=1698427333&end=1698435077&keys=X58d76f6ebe8dc390d0c50d3f452835bd&num_commits=50&request_type=1&xbaroffset=37686

It's the release bytes size.

**Comment by gaaclarke** [comment]
Sounds like @reidbaker want to reland this.  I'll drop the priority on this and @reidbaker when you reland it can you close and link this issue please.
