### ISSUE TITLE
Scrollbar doesn't jump to clicked position in scrollbar track (Desktop)

### ISSUE THREAD

**Issue by dannyglover** [flutter/flutter#137440]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1) Paste the example code into main.dart
2) Run the app
3) Click the scrollbar track at a position below or above the scrollbars current position.

### Expected results

Clicking the scrollbar track on desktop should make the scrollbar jump to the clicked position, as it is the default behavior of scrollbars on desktop.

### Actual results

The scrollbar jumps by a tiny amount (50>200 px) and stops way short of the clicked position on the track.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: true),
      darkTheme: ThemeData.dark(),
      themeMode: ThemeMode.dark,
      home: const MyHomePage(title: "Test"),
      debugShowCheckedModeBanner: false,
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView.builder(
        addAutomaticKeepAlives: false,
        addRepaintBoundaries: false,
        addSemanticIndexes: false,
        itemCount: 100,
        itemExtent: 35,
        itemBuilder: (BuildContext context, int index) {
          return ListTile(
            title: Text("Row: $index"),
          );
        },
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/80641670/fad205bf-fbdd-4a61-94af-79eeab3f87db

</details>

### Logs

<details><summary>Logs</summary>

```console
Logs not applicable
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.6, on Fedora Linux 38 (Workstation Edition) 6.5.7-200.fc38.x86_64,
    locale en_GB.UTF-8)
    • Flutter version 3.13.6 on channel stable at /home/danny/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (4 weeks ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/danny/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at:
      /var/lib/flatpak/app/com.google.AndroidStudio/current/active/files/extra/android-studio/jbr/bi
      n/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 16.0.6 (Fedora 16.0.6-3.fc38)
    • cmake version 3.27.7
    • ninja version 1.11.1
    • pkg-config version 1.8.0

[!] Android Studio (version unknown)
    • Android Studio at
      /var/lib/flatpak/app/com.google.AndroidStudio/current/active/files/extra/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • android-studio-dir =
      /var/lib/flatpak/app/com.google.AndroidStudio/current/active/files/extra/android-studio
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.83.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.74.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Fedora Linux 38 (Workstation Edition)
      6.5.7-200.fc38.x86_64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 118.0.5993.117

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by dannyglover** [comment]
Here's a patch for `scrollbar.dart` that implements this behaviour. Feel free to add it to flutter if you wish:

```
void _handleTrackTapDown(TapDownDetails details) {
    // The Scrollbar should page towards the position of the tap on the track.
    assert(_debugCheckHasValidScrollPosition());
    _cachedController = _effectiveScrollController;

    final ScrollPosition position = _cachedController!.position;
    if (!position.physics.shouldAcceptUserOffset(position)) {
      return;
    }

    // Determines the scroll direction.
    final bool scrolledVertically = switch (position.axisDirection) {
      AxisDirection.up || AxisDirection.down => true,
      _ => false
    };
    final double trackSize = scrollbarPainter._trackExtent;
    final double tapPosition = (scrolledVertically)
        ? details.localPosition.dy
        : details.localPosition.dx;
    final double scrollPositionPercentage = (tapPosition / trackSize);
    final double maxScrollExtent = _cachedController!.position.maxScrollExtent;
    final double positionToScroll =
        (scrollPositionPercentage * maxScrollExtent);

    _cachedController!.jumpTo(positionToScroll);
  }
  ```

**Comment by huycozy** [comment]
Hi @dannyglover 
I'm checking this behavior on some applications (on macOS):

- Notes/Sublime Text/Chrome/Slack: It looks like Scrollbar will jump a defined distance on each click
- VS Code/Android Studio: Scrollbar jumps to the clicked position

So I think this could be a proposal/feature request, correct?

**Comment by dannyglover** [comment]
> Hi @dannyglover 
> I'm checking this behavior on some applications (on macOS):
> 
> - Notes/Sublime Text/Chrome/Slack: It looks like Scrollbar will jump a defined distance on each click
> - VS Code/Android Studio (file editor layout): Scrollbar jumps to the clicked position
> 
> So I think this could be a proposal/feature request, correct?

Hello again 👋. So it seems there's a bug here and a missing feature.

Bug: open chrome and click and hold your mouse left click down on the scroll track > observe how the thumb moves towards the clicked position until it reaches it.

Feature: what I've said in my initial post, plus the ability to set the preferred track clicking behaviour.

**Comment by huycozy** [comment]
>Bug: open chrome and click and hold your mouse left click down on the scroll track > observe how the thumb moves towards the clicked position until it reaches it. Flutter doesn't replicate this behaviour. Holding click down only moves the thumb once.

This is also not available on desktop (checked on macOS target platform). Thus, I think this is a feature request as well.

>what I've said in my initial post, plus the ability to set the preferred track clicking behaviour, that can also be changed at runtime.

I think these two features could be consolidated into one request (track-clicking behavior type)

>Maybe I should split this issue into three separate issues?

If you agree with my proposal, feel free to close this and open new corresponding issues ([feature request template](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=3_feature_request.yml)) for these. Thanks!
