### ISSUE TITLE
Change notice from `flutter start` when and multiple devices are detected

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1374]
Scenario:

* iOS simulator started
* Android device connected
* Run `flutter start`

Expected:

* Tool should attempt to run the app on all supported and connected devices.
* Output should say: "Note: multiple supported devices and/or simulators detected. You can specify a specific device/simulator with --device-id."

Actual:

```
~/flutter/testme $ flutter start
severe: Warning: Multiple devices are connected, but no device ID was specified.
```

and then both simulator and android device attempt to reload the app. And `flutter start` starts an iOS build process.

Two issues:

* "severe" and "Warning" are contradictory. A warning usually isn't a huge deal, but severe is a big deal. And neither really apply: it's more like a Note to the developer
* No specific message for how to specify a device/simulator

**Comment by sethladd** [comment]
cc @devoncarew @chinmaygarde

**Comment by eseidelGoogle** [comment]
`flutter start` (perhaps controversially) was originally designed to start all things on all devices at once.  This was done for an earlier demo of developing on both Android and iOS at the same time.  Unclear if that's still the behavior we want, but would require some refactoring of the command system to fix.

**Comment by sethladd** [comment]
> flutter start (perhaps controversially) was originally designed to start all things on all devices at once. 

That's not bad behavior. If we keep that, suggest we take off the "severe" notice from the output, and change "Warning" to "Note:". And then add "Attempting to run app on all connected and supported devices and simulators."
