### ISSUE TITLE
Uncategorized (Xcode): Command CodeSign failed with a nonzero exit code in Android Studio - Flutter

### ISSUE THREAD

**Issue by A-Eric-J** [flutter/flutter#137485]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I've updated my macOS to Sonoma version 14.1, and updated flutter to the latest version, and updated Xcode to 15.0.1 

### Actual results

when I want to run on iOS simulator using `iPhone 15 Pro Max - iOS 17.0`, on Android Studio it shows this Error:

> Uncategorized (Xcode): Command CodeSign failed with a nonzero exit
> code
> 
> Could not build the application for the simulator. Error launching
> application on iPhone 15 Pro Max.

But when I run the project using Xcode everything is fine and can run in a right way but has problem in Android Studio.

Android Studio:

Android Studio Electric Eel | 2022.1.1

### Logs

<details>
<summary>Logs</summary>

```console

 Xcode build done.                                            5.7s
Failed to build iOS app
Uncategorized (Xcode): Command CodeSign failed with a nonzero exit code

Could not build the application for the simulator.
Error launching application on iPhone 15 Pro Max.

```

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):

[✓] Flutter (Channel stable, 3.13.9, on macOS 
14.1 23B74 darwin-arm64, locale en-US)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)

[✓] Chrome - develop for the web

[✓] Android Studio (version 2022.1)

[✓] Connected device (3 available)

[✓] Network resources

**Comment by darshankawar** [comment]
@A-Eric-J 
Can you run `flutter run -v` and provide the entire log here in properly formatted text ?

**Comment by A-Eric-J** [comment]
@darshankawar  Many thanks for your comment,
Here is my flutter run -v:
because it was too long, I've provided the response in a PDF file.
[flutter run -v.pdf](https://github.com/flutter/flutter/files/13204447/flutter.run.-v.pdf)

**Comment by darshankawar** [comment]
Thanks for the logs. It shows couple of noticeable entries:

```
Details: createItemModels creation requirements should not create capability item
model for a capability item model
 that already exists.
 Function: createItemModels(for:itemModelSource:)
 Thread: <_NSMainThread: 0x600003b202c0>{number = 1, name = main}
 Please file a bug at https://feedbackassistant.apple.com with this warning
message and any useful information you can
 provide.
 ** BUILD FAILED **

```
For above, there's already open issue: https://github.com/flutter/flutter/issues/135277

For original error:

```
[ +8 ms] Failed to build iOS app
[ +1 ms] Uncategorized (Xcode): Command CodeSign failed with a nonzero exit code

[ +2 ms] Could not build the application for the simulator.
[ ] Error launching application on iPhone 15 Pro Max.
[ +1 ms] "flutter run" took 11,068ms.
[ +1 ms]
 #0 throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
 #1 RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:760:9)
 <asynchronous suspension>
 #2 FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/
flutter_command.dart:1297:27)
 <asynchronous suspension>
 #3 AppContext.run.<anonymous closure> (package:flutter_tools/src/base/
context.dart:150:19)
 <asynchronous suspension>
 #4 CommandRunner.runCommand (package:args/command_runner.dart:212:13)
 <asynchronous suspension>
 #5 FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
 <asynchronous suspension>
 #6 AppContext.run.<anonymous closure> (package:flutter_tools/src/base/
context.dart:150:19)
 <asynchronous suspension>
 #7 FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/
flutter_command_runner.dart:285:5)
 <asynchronous suspension>
 #8 run.<anonymous closure>.<anonymous closure> (package:flutter_tools/
runner.dart:115:9)
 <asynchronous suspension>
 #9 AppContext.run.<anonymous closure> (package:flutter_tools/src/base/
context.dart:150:19)
 <asynchronous suspension>
 #10 main (package:flutter_tools/executable.dart:90:3)
 <asynchronous suspension>


[ +66 ms] ensureAnalyticsSent: 63ms
[ ] Running 1 shutdown hook
[ ] Shutdown hooks complete
[ ] exiting with code 1
```

This doesn't seem to be similar / related to other open issues related to Sonoma and XCode.

@A-Eric-J Is above error occuring only in your existing project or if you create a new project as well ?

**Comment by A-Eric-J** [comment]
Dear @darshankawar,
I had the same problem in new project and existing project as well.
After 2 days searching and trying different ways,I found out that, after upgrading my macOS to Sonoma v14.1, all of my project files was stored within iCloud Drive and sync was on.
So the solution is to getting backup from your projects(if they are not in Git repositories) and making the syncing of the files  with iCloud off, then your project that is on your HD will be run as well.
Many thanks.

**Comment by samtoya** [comment]
I had the same issue and I got it to build on my iPhone. Try these steps:

0. Clean the build folder both on Flutter and Xcode.
1. Open Keychain Access.
2. Look through the certificates for all expired ones & delete them.
3. Open Xcode and sign out from all accounts connected & close it.
4. Reopen Xcode, sign into your account, and "Download Manual Profiles"
5. Then rebuild the app.
6. It should work fine now.
