### ISSUE TITLE
Shadows too dark

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#13742]
In the recent change from Skia version `03588412c89899fba09893e1812866f0069fc6f6` to version `ef0384835757df463f5157145650a60ba8b14a63`, the shadows got unexpectedly darker.  For example:

![bar](https://user-images.githubusercontent.com/15253456/34281044-fadefa90-e689-11e7-9075-bcf392a5ce1a.gif)

![button](https://user-images.githubusercontent.com/15253456/34281047-fe4199fe-e689-11e7-8062-ad42c7e7dc5b.gif)

**Comment by brianosman** [comment]
Almost certainly caused by https://skia-review.googlesource.com/c/skia/+/85002, although Jim's been on vacation (since before this was reported). How critical is this, given the holiday weekend? I really don't want to revert the roll, just because Flutter was already well behind Skia ToT.

**Comment by tvolkert** [comment]
It can be fixed after the holidays. Thanks!

**Comment by tvolkert** [comment]
@jvanverth, can you have a look when you're back from vacation?

**Comment by jvanverth** [comment]
I'll take a look. This will probably have to be something that gets fixed in the Flutter engine rather than Skia, as that change was fixing bad behavior.

**Comment by jvanverth** [comment]
This is caused by https://skia-review.googlesource.com/c/skia/+/73900. It is fixed by https://skia-review.googlesource.com/c/skia/+/85002, which hasn't been rolled into Flutter yet.

**Comment by tvolkert** [comment]
So @jvanverth is there any work required in the Flutter engine, or should updating the Skia rev in the engine be sufficient?

**Comment by jvanverth** [comment]
Updating the Skia rev should be sufficient. The change that @brianosman was referring to was not in the roll and so was not causing the issue -- instead, it's actually the fix for the issue.
