### ISSUE TITLE
How to embed a flutter module which loads variables using --dart-define-from-file into iOS project

### ISSUE THREAD

**Issue by tomisacat** [flutter/flutter#137588]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a flutter module following the docuemnt: https://docs.flutter.dev/add-to-app/ios/project-setup
2. Use option C to try embedding the module manually

    2.1 build the module: 

    ```
   flutter build ios-framework --cocoapods --output=$FlutterModulePathDebug --dart-define-from-file=envs/.env.staging --no-tree-shake-icons --no-profile --no-release
    ```

    `$FlutterModulePathDebug` is a predefined environment variable points to a subfolder in the iOS app project.

    2.2 add to the searching path:

    ![image](https://github.com/flutter/flutter/assets/1179735/4a058704-1c11-4121-8878-1a7df5bd887f)

    2.3 but can't add framework from the searching path:

    <img src="https://github.com/flutter/flutter/assets/1179735/d42e2e80-e17a-425f-8a42-e231199103c1" width=550>

### Expected results

1. I can embed the Flutter module as well as all the packages and plugins it depends on
2. I can embed the Flutter module for different configurations, e.g `Debug`, `Staging`, `Release`.

### Actual results

I can't even embed any Flutter module

### Code sample

No code sample needed.

### Screenshots or Video

Already pasted in the `Steps to reproduce`.

### Logs

No logs needed.

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.6, on macOS 13.6 22G120 darwin-arm64,
    locale en-CN)
    • Flutter version 3.13.6 on channel stable at /Users/junma1/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (5 weeks ago), 2023-09-26 18:28:17
      -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version
    33.0.2)
    • Android SDK at /Users/junma1/Library/Android/sdk
    • Platform android-34, build-tools 33.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google
      Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.83.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • 77A21DEA-7B7D-4BFA-B857-6CCE2DFDA0D9 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)        • macos                                •
      darwin-arm64   • macOS 13.6 22G120 darwin-arm64
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 118.0.5993.117

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @tomisacat 
Have you added `Flutter.podspec` to your Podfile? Could you share an example project you are trying to do?

**Comment by tomisacat** [comment]
@huycozy yes, i've added `Flutter.podspec` to Podfile

**Comment by tomisacat** [comment]
@huycozy actually what i want is to embed a Flutter module into an existing iOS project no matter through CocoaPods or embed manually, and the Flutter module loads environment variables using `--dart-define-from-file`

**Comment by huycozy** [comment]
Do you mean it can't read environment variables using `--dart-define-from-file` (even with option A/B/C)? Does it still work with `--dart-define` when doing build ios-framework? (I haven't tried this as there is an open issue at https://github.com/flutter/flutter/issues/88092, you may check the alternative solution [here](https://github.com/flutter/flutter/issues/88092#issuecomment-900507989))
