### ISSUE TITLE
[camera_android] sometimes crashes on pausePreview

### ISSUE THREAD

**Issue by PROGrand** [flutter/flutter#137544]
## Description
Android applications using `camera_android` sometimes crashes on pausePreview

### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. call close capture session 
2. call pause preview

### Expected results

call to pause preview does not throws NullPointerException

### Actual results

NullPointerException thrown in native

**Comment by huycozy** [comment]
Hi @PROGrand 
I'm not sure which function will trigger `close capture session`. Could you share a minimal sample code for this case?
