### ISSUE TITLE
What is the right way to start any async task on GUI event

### ISSUE THREAD

**Issue by SeniorIvan** [flutter/flutter#13752]
At this moment it is not very clear and easy to start async task on GUI event.

So, we use Http.Dart and it uses Future without Isolated. And it works perfectly and doesn't freeze main GUI thread.

If we use future async on GUI event (for example - button) we receive freeze.

Could you please explain to us, what is the shortest and most right way to start async task.

At this moment, for example, if we want to start long duration task on button click, we need to wrap our sync function (for example infinite loop) in async function which use dart isolate. 
It will be good if you implement something like in Android SDK(Async task). 

It is example of dart http request using.
```
var url = "http://example.com/whatsit/create";
http.post(url, body: {"name": "doodle", "color": "blue"})
    .then((response) {
  print("Response status: ${response.statusCode}");
  print("Response body: ${response.body}");
});
```

What we found if we want to start any task in none GUI thread (event loop).
```
import 'dart:io';
import 'dart:isolate';

/// Wrapper function for async call of our real function
Future<int> asyncTask() async {
  final response = new ReceivePort();
  await Isolate.spawn(_isolate, response.sendPort);
  final sendPort = await response.first as SendPort;
  final answer = new ReceivePort();
  sendPort.send([answer.sendPort]);
  return answer.first;
}

/// Here we pass our real task to response
void _isolate(SendPort initialReplyTo) {
  final port = new ReceivePort();
  initialReplyTo.send(port.sendPort);
  port.listen((message) {
    final send = message[0] as SendPort;
    send.send(syncTask());
  });
}

/// real task for execution.
syncTask() {
  int index = 0;
  while (true) {
    sleep(new Duration(seconds: 1));
    print(++index);
  }
}

floatingActionButton: new FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: new Icon(Icons.add),
 ),

/// here we must do not forget to make it async because we call  "await asyncTask();"
_incrementCounter() async {
    await asyncTask();
    setState(() {
      _counter++;
});

```

**Comment by thosakwe** [comment]
If you run `_incrementCounter` without `await`, it will run asynchronously, as you might imagine. You'll need a `then` callback.

```
void _incrementCounter() {
    asyncTask().then((_) {
      setState(() {
        _counter++;
      }
    });
});
```

**Comment by Hixie** [comment]
@SeniorIvan  Does the `compute` function address your use case?
https://master-docs-flutter-io.firebaseapp.com/flutter/foundation/compute.html

I don't really understand what you would like changed. Can you elaborate?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
