### ISSUE TITLE
A Path with a MaskFilter.blur and a negative shift in CustomPainter runs away

### ISSUE THREAD

**Issue by antontishkov** [flutter/flutter#137538]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a CustomPainter
2. Create a simple Path with a fillType = PathFillType.nonZero
3. Draw this path using drawPath with a negative shift (for example path.shift(const Offset(-20, 0))) and a small blur (for example MaskFilter.blur(BlurStyle.normal, 0.1)).
4. Draw this path again with a same negative shift, with different color AND without any blur.

### Expected results

The red shadow should be exactly below the blue figure so that the last one covers the red shadow almost completely.
![flutter_bug_01](https://github.com/flutter/flutter/assets/9081791/21a802ef-76a1-445e-a88c-b86840cc57c4)

### Actual results

The red shadow runs away despite the fact that they have the same shift. This problem appears only with negative x or y shift. With a positive shift everything works as expected.
![flutter_bug_02](https://github.com/flutter/flutter/assets/9081791/ef07630b-5d58-40c1-b6a9-d3241ad28c62)

### Code sample

<details><summary>Code sample</summary>

```
class ProblemWithMaskFilter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    final path = Path()
      ..moveTo(80, 0)
      ..lineTo(160, 50)
      ..lineTo(160, 110)
      ..lineTo(80, 160)
      ..lineTo(0, 110)
      ..lineTo(0, 50)
      ..close()
      ..fillType = PathFillType.nonZero;

    canvas.drawPath(
        path.shift(const Offset(-20, 0)),
        Paint()
          ..color = Colors.red
          ..maskFilter = const MaskFilter.blur(BlurStyle.normal, 0.1));

    canvas.drawPath(
        path.shift(const Offset(-20, 0)), Paint()..color = Colors.blueAccent);
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) {
    return false;
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
flutter doctor -v
[✓] Flutter (Channel stable, 3.13.9, on macOS 12.5 21G72 darwin-x64, locale ru)
    • Flutter version 3.13.9 on channel stable at /Users/.../Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (5 days ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/Anton/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.83.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • 99606E77-93FC-45F2-A8D2-172A52DF1378 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 12.5
      21G72 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome
      118.0.5993.117

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by antontishkov** [comment]
**Update!** Looks like the bug is fixed in the master channel

**Comment by darshankawar** [comment]
Thanks for the report and update @antontishkov 
Yes, it seems to be working as expected on master when I verified, hence, I'll close this issue as fixed. It'll be available in next stable release per team's release policy.
Closing for now. If you disagree, write in comments and I'll reopen it.
