### ISSUE TITLE
requestFocus() doesn't work on Android 13 after upgrade Flutter to 3.13.7

### ISSUE THREAD

**Issue by xujw701** [flutter/flutter#137581]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Open the mobile number entry page
2. Observe behaviour(focus and soft keyboard) of the mobile number input field

p.s. I found there is a closed ticket for similar issue, but the author didn't highlight it only happens _**on Android 13 (tested on Android 9, 10, and 12, they are working fine)**_

(https://github.com/flutter/flutter/issues/132908)

**The devices that had the autofocus issue:
Samsung Galaxy S21 + 5G
Samsung Galaxy A22**

### Expected results

1. The mobile number input field should get the focus (The cursor should be blinking).
2. Soft keyboard pops up.
4. The above results are working on Flutter 3.10.6

### Actual results

1. The mobile number input field doesn't get the focus 
2. Soft keyboard pops up.

### Code sample

<details><summary>Request focus</summary>

```
late FocusNode _focusNode;

  @override
  void initState() {
    super.initState();
    _focusNode = FocusNode();

    Future.delayed(Duration.zero, () {
      if (widget.reactiveTime == null) return;
      _focusNode.requestFocus();
    });
  }
```

</details>

<details><summary>TextFormField</summary>

```
TextFormField(
            key: const ValueKey(value_keys.phoneInputKey),
            enabled: widget.enabled,
            keyboardType: TextInputType.phone,
            decoration: InputDecoration(
              fillColor: widget.enabled ? Colors.white : theme.lightGreyColor,
              filled: true,
              labelText: LanguageHelper.translate(
                keys.registerMobileNumberField,
                fallbackText: strings.mobileNumber,
              ),
              prefixText: constants.nzCountryCode,
              prefixStyle: theme.labelStyle.copyWith(fontSize: 17, height: 0),
            ),
            style: widget.enabled ? null : const TextStyle(color: theme.grey),
            focusNode: _focusNode,
            controller: _textController,
            textInputAction: TextInputAction.done,
            autofillHints: const [AutofillHints.telephoneNumber],
            inputFormatters: [
              FilteringTextInputFormatter.deny(
                RegExp(r"^\+64"),
                replacementString: '',
              ),
              MaskedInputFormatter('00 000 000000000'),
            ],
            onFieldSubmitted: (String? value) => _validateAndSubmit(),
          )
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![Screenshot 2023-10-31 at 11 10 34 AM](https://github.com/flutter/flutter/assets/13247016/2edbe66c-dd84-4ccd-9d5b-d406d7b67e5c)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.7, on macOS 13.0 22A8380 darwin-arm64, locale en-NZ)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

</details>

**Comment by darshankawar** [comment]
Thanks for the report @xujw701 
I tried [this](https://docs.flutter.dev/cookbook/forms/focus#interactive-example) code sample from official documentation running on Android emulator and it seems to work as expected as it shows blinking cursor in the textfield.

Can you try the same and compare it with yours and see if there's any missing implementation ? If not, can you elaborate how is this code different from yours ?

**Comment by xujw701** [comment]
Hey @darshankawar thank you so much for your update. I've double checked with out testers, and we found it can be only replicated on Android 13, I've tested Android 9/10/12, they all work fine. Could you please help check it again? Many thanks

**Comment by darshankawar** [comment]
Thanks for the update @xujw701 
I earlier had tried on Android 13 itself running on api 33:

<img width="283" alt="Screenshot 2023-11-01 at 11 27 25 AM" src="https://github.com/flutter/flutter/assets/67046386/3fa74ac2-0728-414b-8d14-599225c7630a">

**Comment by xujw701** [comment]
Hey @darshankawar, right, I've tried it on the simulator, it works. However, on Samsung Galaxy, Android 13, it can be replicated. Here is the video recorded. Could you please help double check?

https://github.com/flutter/flutter/assets/13247016/4097a730-ca32-4c57-8a41-74287767c2cd

**Comment by xujw701** [comment]
It worked very well on Flutter 3.10.6, but failed to request the focus on some specific devices, so we revert the Flutter upgrade internally to fix the issues. Hope you guys can help.

**Comment by xujw701** [comment]
The devices that had the autofocus issue:
Samsung Galaxy S21 + 5G
Samsung Galaxy A22

**Comment by darshankawar** [comment]
Thanks for the update @xujw701 
I currently don't have Samsung device to verify this, but meantime, can you try by setting `autofocus: true` on the field and check if it helps ?

**Comment by xujw701** [comment]
Hey man, thanks. I don't have the device with hand, but has sent a new version to testers, will update the status next Monday! Happy Friday!

**Comment by xujw701** [comment]
Hey @darshankawar, sorry for the wait, the tester doesn't provide any feedback today, will chase him up tomorrow, thanks for the waiting.

**Comment by xujw701** [comment]
Hey @darshankawar, with the autoFocus set, it looks better, but could you please wait a couple of days, and our tester is testing more cases, will let you know if that can fix them all or not. thanks!
