### ISSUE TITLE
On linux constraints are not reported correctly

### ISSUE THREAD

**Issue by Silfalion** [flutter/flutter#137533]
### Steps to reproduce

1. Run the code supplied on Linux
2.notice that the constraints printed are not respected

### Expected results

1080
1920

(for my screen)

### Actual results

720
1280

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

class TestView extends StatelessWidget {
  const TestView({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: LayoutBuilder(
        builder: (context, constraints) {
          print(constraints.maxHeight);
          print(constraints.maxWidth);
          return Container();
        },
      ),
    );
  }
}

```

</details>

### Logs

<details><summary>Logs</summary>

```console
Launching lib/main.dart on Linux in debug mode...

(jigsaw_puzzle:1440100): Gdk-CRITICAL **: 12:18:05.736: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
Connecting to VM Service at ws://127.0.0.1:39659/z625N-OgCY4=/ws
flutter: 720.0
flutter: 1280.0
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.9, on Ubuntu 23.04 6.5.7-060507-generic,
    locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.83.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @Silfalion 
Could you share the complete sample code? `LayoutBuilder` depends on the parent widget's size. Thus, the printed size inside builder may changed by your wrapper parent widget.

**Comment by huycozy** [comment]
Is your app window maximized to fullscreen?

**Comment by Silfalion** [comment]
Not at first, no, but after that I tested in both sceneratio and it outputs the same dimensions, 1280x720

**Comment by huycozy** [comment]
Do you mean it still outputs 1280x720 even when the app window is maximized? Please be more specific.

On my end, I checked this on both Linux and macOS platforms: When the app window is maximized, LayoutBuilder's constraints give the correct size similar to two alternative ways below:

On macOS:
- flutter: View physicalSize: Size(1920.0, 1080.0)
- flutter: PlatformDispatcher physicalSize: Size(1920.0, 1080.0)
- flutter: LayoutBuilder constraints: BoxConstraints(0.0<=w<=1920.0, 0.0<=h<=1080.0)

On Linux:
- flutter: View physicalSize: Size(1920.0, 1006.0)
- flutter: PlatformDispatcher physicalSize: Size(1920.0, 1006.0)
- flutter: constraints: BoxConstraints(0.0<=w<=1920.0, 0.0<=h<=1006.0)

The missing height on Linux is probably due to menu bar (which runs along the top of the screen). The app window can not be fullscreen as on macOS, it is still below menu bar. That being said, LayoutBuilder constraints are still correct.

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';
import 'dart:ui';

void main(List<String> args) {
  runApp(MaterialApp(home: TestView()));
}

class TestView extends StatelessWidget {
  const TestView({super.key});

  @override
  Widget build(BuildContext context) {
    print('View physicalSize: ${View.of(context).physicalSize}');
    print(
        'PlatformDispatcher physicalSize: ${PlatformDispatcher.instance.views.first.physicalSize}');
    return Scaffold(
      body: LayoutBuilder(
        builder: (context, constraints) {
          print('LayoutBuilder constraints: $constraints');
          return Container();
        },
      ),
    );
  }
}
```
</details>

Please retry and confirm if you have the same results.

**Comment by Silfalion** [comment]
Sure, to be clearer:

- my screen is 1920x1080
- when using the MediaQuery or constraints functions **on Linux**, I always get 1280x720, whether the window is maximaized or not
- when I run the same app **on web**(the host is still Linux), I get the correct dimensions no matter the size of the window

**Comment by huycozy** [comment]
It looks like a device-specific issue. Labeling this for other's insights.

**Comment by huycozy** [comment]
Could you share the output of `flutter doctor -v` and the monitor info?

**Comment by Silfalion** [comment]
Yes, here it is:

```
[✓] Flutter (Channel stable, 3.13.9, on Ubuntu 23.10 6.5.7-060507-generic,
    locale en_US.UTF-8)
    • Flutter version 3.13.9 on channel stable at /home/sil/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (13 days ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/sil/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /usr/local/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 16.0.6 (15)
    • cmake version 3.27.4
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[✓] Android Studio (version 2022.2)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.84.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.74.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 23.10
      6.5.7-060507-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 119.0.6045.105

[✓] Network resources
    • All expected network resources are available.

```

**Comment by gspencergoog** [comment]
@Silfalion Could you post the exact code sample that you're using to test this instead of just part of it?  We want to make sure we're trying to reproduce with the correct code. (Desktop Triage)
