### ISSUE TITLE
Flutter should stop using Skia's BUILD.gn directly

### ISSUE THREAD

**Issue by kjlubick** [flutter/flutter#137567]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Skia is migrating away from GN as the default buildsystem onto Bazel. Thus, the BUILD.gn rules that Skia uses will eventually go away.

### Proposal

Skia has a mechanism for generating file lists in `.gni` files ([example_1](https://github.com/google/skia/blob/main/gn/gpu.gni) [example_2](https://github.com/google/skia/blob/main/gn/core.gni)) and we intend to support the generation of these for clients of Skia that do use GN. 

If Flutter defines their own skia target that uses our .gni files and file lists, that will allow us to eventually remove our BUILD.gn files after the migration to Bazel is complete.

**Comment by gaaclarke** [comment]
This was also raised when a change to a skia `BUILD.gn` changed the runtime behavior of flutter's tests: https://github.com/flutter/flutter/issues/137558

Although those tests were flimsy for relying on a default font for tests.

**Comment by zanderso** [comment]
This will likely make https://github.com/flutter/flutter/issues/67373 easier.

**Comment by zanderso** [comment]
@kjlubick Looking in the `BUILD.gn` file, I see some places where source lists are inlined directly into the build targets. Here's one in the `skia` target that Flutter uses a lot: https://github.com/google/skia/blob/75507da748f9062ea43003a87291b0ae61e62e32/BUILD.gn#L1520.

What's the distinction between the lists of sources in the `.gni` files and the lists of sources outside of them?

Also, is there already an example of a `GN` build somewhere that uses the `.gni` files that we could crib from?

**Comment by kjlubick** [comment]
The hard-coded files simply reflect cases where we have not finished extracting the files into groups. Our primary client of these file lists (outside of ourself) is Chromium: https://source.chromium.org/chromium/chromium/src/+/main:skia/BUILD.gn;l=367-386?q=skia%2FBUILD&ss=chromium%2Fchromium%2Fsrc

You will see Chromium also hard-codes some files. That's mostly because those files have been stable and we haven't tried to move them around (which was the impetus for creating many of those filelists anyway)

**Comment by zanderso** [comment]
This is done.
