### ISSUE TITLE
Android/iOS tests not cleaning up applications after test

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#137555]
Some tests are not cleaning up applications after running tests causing the devices to eventually run out of space. The packages not being deleted are:

package:com.example.image_list
package:com.yourcompany.integration_ui
package:com.example.app
package:com.example.platform_channels_benchmarks

**Comment by godofredoc** [comment]
@reidbaker @stuartmorgan @mossmana is this something your teams can help us with?

**Comment by reidbaker** [comment]
> @reidbaker @stuartmorgan @mossmana is this something your teams can help us with?

I have paired with @yusuf-goog several times in this already. What specifically are you asking for?

**Comment by yusuf-goog** [comment]
@reidbaker this ask is to update the tests to clean up what they install

**Comment by reidbaker** [comment]
We will talk about it in triage this week but my guess is that this is not more important than the api 34 work which most of the team is working on. 

FYI @mariamhas @johnmccutchan

**Comment by godofredoc** [comment]
This is generating a lot of flakiness on android tests impacting everyone. Context: https://github.com/flutter/flutter/issues/135035

An example of test that is not cleaning up is https://cs.opensource.google/flutter/flutter/+/master:dev/devicelab/bin/tasks/image_list_reported_duration.dart?q=com.example.image_list&ss=flutter which is delegating to https://cs.opensource.google/flutter/flutter/+/master:dev/devicelab/lib/tasks/perf_tests.dart;l=2024?q=ReportedDurationTest&sq=&ss=flutter and is not doing proper cleanup.

**Comment by mossmana** [comment]
@godofredoc Can you please also provide an example for the iOS impact?

Another note of interest is that the ReportedDurationTest appears to wait up to 1 hr before bailing (https://github.com/flutter/flutter/blob/master/dev/devicelab/lib/tasks/perf_tests.dart#L2134). I'm really hoping this isn't run every time a PR is submitted.

**Comment by stuartmorgan** [comment]
When you say "clean up applications", do you mean explicitly uninstalling them from mobile devices/simulators?

**Comment by johnmccutchan** [comment]
At first impression this seems like something our infrastructure should do automatically for us? We shouldn't allow for artifacts to bleed across test runs, etc.

**Comment by camsim99** [comment]
@godofredoc Do you know the package/file that does the cleanup and can you link it in the description?

**Comment by godofredoc** [comment]
@stuartmorgan yes, many of the tests are not uninstalling the applications. This is not required for emulators as they are always started in a clean state but it is important for physical devices.

@johnmccutchan infra does cleanup of physical devices but only after certain events (e.g. after a test failure) doing it after every test is expensive (in the order of 5 mins because the device needs to be brought back to a good known state).

**Comment by mossmana** [comment]
@godofredoc Unassigning for now as this is not an issue that we believe should be solved from a platform team perspective.

**Comment by goderbauer** [comment]
@godofredoc @reidbaker @godofredoc @yusuf-goog @mossmana @stuartmorgan @johnmccutchan 

Hello from the critical triage meeting. This issue came up in our review as an unowned issue and from the discussion it sounds like no team wants to own this. Unless we find an owner I am tempted to close this per our [guidelines](https://github.com/flutter/flutter/wiki/Issue-hygiene#closing-issues):

> [An issue should be closed if] it is an issue regarding internal processes, tooling, or infrastructure [...] that we have no plans to get to

**Comment by Hixie** [comment]
I'll go through an audit everything in the devicelab package and make sure anything that calls 'run' or 'drive' also calls the uninstall thingy.

**Comment by Hixie** [comment]
The following files in devicelab call either `run` or `drive`:
- [ ] bin/tasks/complex_layout_semantics_perf.dart
- [ ] bin/tasks/drive_perf_debug_warning.dart
- [ ] bin/tasks/flutter_gallery_v2_chrome_run_test.dart
- [ ] bin/tasks/hello_world__memory.dart
- [ ] bin/tasks/hello_world_impeller.dart
- [ ] bin/tasks/route_test_ios.dart
- [ ] bin/tasks/routing_test.dart
- [ ] bin/tasks/service_extensions_test.dart
- [ ] lib/framework/utils.dart
- [ ] lib/tasks/android_choreographer_do_frame_test.dart
- [ ] lib/tasks/android_lifecycles_test.dart
- [ ] lib/tasks/android_verified_input_test.dart
- [ ] lib/tasks/android_views_test.dart
- [ ] lib/tasks/build_test_task.dart
- [ ] lib/tasks/dart_plugin_registry_tests.dart
- [ ] lib/tasks/entrypoint_dart_registrant.dart
- [ ] lib/tasks/gallery.dart
- [ ] lib/tasks/hot_mode_tests.dart
- [ ] lib/tasks/integration_tests.dart
- [ ] lib/tasks/microbenchmarks.dart
- [ ] lib/tasks/native_assets_test.dart
- [ ] lib/tasks/perf_tests.dart
- [ ] lib/tasks/platform_channels_benchmarks.dart
- [ ] lib/tasks/run_tests.dart
- [ ] lib/tasks/web_dev_mode_tests.dart

**Comment by Hixie** [comment]
If someone who understands this problem better than me would like to review the PR, that would be great. https://github.com/flutter/flutter/pull/146856

**Comment by Hixie** [comment]
So I have a PR for this that's leady to land (https://github.com/flutter/flutter/pull/146856), but since it changes devicelab and devicelab does not run pre-commit (as far as I know), it seems highly likely that it would break the tree, so I'll work with whoever is on call in #tree-status to land it.
