### ISSUE TITLE
ExpansionTile Improvements

### ISSUE THREAD

**Issue by mhbdev** [flutter/flutter#137530]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

There is no problem indeed but this would be much better if the `ExpansionTile` widget supports these parameters:
* dense
* visualDensity
* reverse (if it is `true` then the tile should render beneath its children) - defaults to `false`
* enabled
* enableFeedback

> I know that we can wrap this widget with ExpansionTileTheme or even ListTileTheme to force changes but it would be much easier to have direct access to those parameters in the main widget.

### Proposal

I want to add more access to the ExpansionTile widget's ListTile and make it possible to change the arrangement of placing ListTile and the children.

**Comment by dam-ease** [comment]
Hi @mhbdev. Thanks for proposing this. I see similar individual issues are requesting for some of the capabilities listed e.g. https://github.com/flutter/flutter/issues/135770.
Labelling as some other parameters are included in this proposal.

**Comment by HansMuller** [comment]
Labeled this P3 only because we're not planning on making these improvements in the short term. The ListTile pass throughs sound reasonable; happy to review a PR.

**Comment by mhbdev** [comment]
I am closing this as the PR attached is going to partially add the features to ExpansionTile.
