### ISSUE TITLE
Feature Request: Preserve Original Colors for Image Icons in BottomNavigationBar with ImageIcon

### ISSUE THREAD

**Issue by YuneshShrestha** [flutter/flutter#137520]
### Is there an existing issue for this?

- [x] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

In this scenario, let's focus on the "Profile" section of the app, represented by a user avatar icon in the BottomNavigationBar. This avatar icon is designed with a specific set of colors that match the app's branding.

![Nav bar](https://github.com/flutter/flutter/assets/52854563/f7ed17db-b53b-4737-a9db-c8f95003fb00)

### Proposal

One possible solution could be to introduce a property or parameter to the ImageIcon that allows developers to specify whether they want to preserve the original colors of the image icons in BottomNavigationBar. For example:

```
BottomNavigationBar(
  items: [
    BottomNavigationBarItem(
      icon: ImageIcon(
        AssetImage('assets/icon1.png'),
        preserveOriginalColors: true,
      ),
      label: 'Account',
    ),
    // Other items
  ],
  // Other BottomNavigationBar properties
)

```

By using   preserveOriginalColors: true:
output:
![Nav bar](https://github.com/flutter/flutter/assets/52854563/f8ed1760-d7ab-4ea9-af2c-3ee7f55f6437)

When  preserveOriginalColors: false
![Screenshot 2023-10-30 123134](https://github.com/flutter/flutter/assets/52854563/14b1114e-8c04-4106-9f10-2f0febd564a6)

**Comment by dam-ease** [comment]
Hi @YuneshShrestha. Thanks for proposing this. Not sure I fully understand this. Can you provide more information on this? Do you mean when `preserveOriginalColors` is true, the image on selected should take the color of the image?

**Comment by YuneshShrestha** [comment]
Sorry but found out that I could direcly use:  ```
BottomNavigationBarItem(
            icon: Image.asset(
              AppImages.defaultAvatar,
              height: HeightManager.h24,
              width: WidthManager.w24,
            ),
            label: '',
          ),
```
