### ISSUE TITLE
[pigeon] Only generate ObjC enum box classes if they are needed

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#137556]
While updating 1P plugins to the latest version of Pigeon, I noticed that we are getting a `FooBox` class generated for every `Foo` enum, even if we never use the enum in a context where it has to be nullable. We should ideally check the AST for the cases that will need it, and only generate it if any of them exist.

**Comment by tarrinneal** [comment]
I do believe this is no longer relevant with the latest codec changes, I'm going to close it.
