### ISSUE TITLE
[Impeller] FlutterView.mm takeScreenshot method will fall back to software rasterization.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#137571]
This calls the engine screenshot functionality which attempts to render via an offscreen surface. This is unimplemented for Impeller.

We may wish to change how this API is implemented. For example:

1. We could bypass the generic engine APIs and use a render to texture approach from Impeller. This would be simpler in general.
2. We could implement the offscreen layer API for Impeller. We probably need to do this for raster stats anyway.
3. We could remove this method altogether.

I tried seeing if we could somehow delegate to the CAMetalLayer drawInContext method, but that doesn't seem to work.

* https://developer.apple.com/documentation/quartzcore/calayerdelegate/2097262-drawlayer?language=objc
* https://github.com/cyanglaz/engine/commit/0a3c0b5ecf4ebead950f190b99d7d0819e24c3c2#diff-06e447adb57cfdb87b32298bf525548b1fd35085b40dc23548bfa61d36cdf666

**Comment by chinmaygarde** [comment]
Triage: From @jonahwilliams s recollection, this was fixed by @dnfield. But we need to double check.

**Comment by jonahwilliams** [comment]
This was fixed
