### ISSUE TITLE
allow developer to set headers like x-ios-bundle-identifier to enable us to secure our google maps api keys when using google_maps_flutter

### ISSUE THREAD

**Issue by leeflix** [flutter/flutter#137586]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I want to secure our google maps api keys but in order to follow the guide of google I need to set some extra headers which is not possible right now when using google_maps_flutter

### Proposal

allow developer to set extra headers when using google_maps_flutter

**Comment by darshankawar** [comment]
@leeflix 
Can you elaborate on your use case with an example so that we'll have clear understanding of the proposal ?

**Comment by leeflix** [comment]
we would like to follow googles advise on restricting our api keys since they are part of of the app and can be extracted with little effort

https://developers.google.com/maps/api-security-best-practices#restricting-api-keys

in order for the google maps api to accept these restricted keys we need to send some additional headers in the request according to the docs:

https://cloud.google.com/docs/authentication/api-keys?hl=de&_ga=2.127072461.-1715637411.1698742988&_gac=1.19912394.1698743158.Cj0KCQjwy4KqBhD0ARIsAEbCt6hkwsr2V0q1Hg57lzEzifJlBi08Bjc36X8TesJHUJtvHW_-rp8vkngaAo7jEALw_wcB#ios

because there is no way of adding headers to the requests send to the google maps api by the google_maps_flutter plugin and because we would like to continue using the plugin we need a way to add headers or at least these headers (android also needs two additional headers)

**Comment by stuartmorgan** [comment]
What APIs are you calling that require manually setting headers? In general the Google Maps SDK is issuing requests internally, and should be managing any restrictions internally.

**Comment by leeflix** [comment]
[here](https://cloud.google.com/docs/authentication/api-keys?hl=de&_ga=2.127072461.-1715637411.1698742988&_gac=1.19912394.1698743158.Cj0KCQjwy4KqBhD0ARIsAEbCt6hkwsr2V0q1Hg57lzEzifJlBi08Bjc36X8TesJHUJtvHW_-rp8vkngaAo7jEALw_wcB#ios) you can see that google instructs us to send additional headers to the **google maps api** in order to protect our api keys

**Comment by stuartmorgan** [comment]
Yes, I read that documentation, which would be relevant to any code manually constructing web requests to the API. What `google_maps_flutter` API(s) are you calling that construct requests manually and thus need the ability to set headers?

**Comment by leeflix** [comment]
I am using the ```GoogleMap``` widget (https://pub.dev/documentation/google_maps_flutter/latest/google_maps_flutter/GoogleMap-class.html) which I assume makes api requests under the hood where I can't set headers

**Comment by stuartmorgan** [comment]
Per my earlier comment:

> In general the Google Maps SDK is issuing requests internally, and should be managing any restrictions internally.

It sounds like this issue was filed speculatively based on a misunderstanding of the structure of the Google Maps SDK; closing as this is not actionable.

If you have any actual bugs when setting app restrictions on the server side, please file a new issue with specific error details and reproduction steps.

**Comment by leeflix** [comment]
so how are we supposed to use the google maps plugin while following googles best practices to use restricted api keys?

**Comment by stuartmorgan** [comment]
> so how are we supposed to use the google maps plugin while following googles best practices to use restricted api keys?

The same way you would use it without a restricted API key. Per my comment above, if that does not work please file an issue with details.
