### ISSUE TITLE
TextStyle foreground rendered incorrectly on ios with impeler

### ISSUE THREAD

**Issue by guyluz11** [flutter/flutter#137537]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

As this issue was closed by GitHub bot for inactivity I am just pasting some content from there

Related issues
https://github.com/flutter/flutter/issues/126010
https://github.com/flutter/flutter/issues/126740

Just create a TextField with a foreground attribute

### Expected results

Rendered same on Android and IOS 

### Actual results

IOS impeller is drawn incorrectly

### Code sample

<details><summary>Code sample</summary>

```dart
 Text(
              'SAMPLE TEXT',
              style: Theme.of(context).textTheme.bodyLarge!.copyWith(
                    fontSize: 40,
                    fontWeight: FontWeight.bold,
                    foreground: Paint()
                      ..style = PaintingStyle.stroke
                      ..strokeWidth = 3
                      ..color = Colors.red,
                  ),
            )
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

Android and ios without impeller 

![image](https://github.com/flutter/flutter/assets/9304740/eca24169-b5c1-46a9-a364-b89c63eb44d5)

ios with impeller

![image](https://github.com/flutter/flutter/assets/9304740/5fafdc57-9046-4f49-bded-9518aed64a80)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```consoleDoctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.0 23A344 darwin-arm64, locale en-IL)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.83.1)
[✓] Connected device (5 available)
[✓] Network resources
! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment]
@guyluz11 
I believe you are hitting https://github.com/flutter/flutter/issues/137134 for which the response from engine team is: https://github.com/flutter/flutter/issues/137134#issuecomment-1777677709
So you can check by switching to latest master as the feature is currently available on master but not in stable yet.
Closing based on above explanation. If you disagree, write in comments and I'll reopen it.
