### ISSUE TITLE
5.회신기능 추가

### ISSUE THREAD

**Issue by ChilsungCider** [flutter/flutter#137535]
lib/main.dart에 'forgot-password'가 path로 설정되어 있는 GoRoute 부분에 final arguments = state.queryParameters; 부분에서 이대로 실행할 시 queryParameters 부분에서 "The getter 'queryParameters' isn't defined for the type 'GoRouterState'. Try importing the library that defines 'queryParameters', correcting the name to the name of an existing getter, or defining a getter or field named." 라는 error가 발생합니다. 이를 final arguments = state.uri.queryParameters;로 수정하니 잘 실행되었습니다.

**Comment by ChilsungCider** [comment]
Firebase for Flutter -> 5.(Add reply function.. maybe?)
In the lib/main.dart file, within the GoRoute section where 'forgot-password' is set as the path, when executing as it is with 'final arguments = state.queryParameters;', an error "The getter 'queryParameters' isn't defined for the type 'GoRouterState'. Try importing the library that defines 'queryParameters', correcting the name to the name of an existing getter, or defining a getter or field named." occurs. This was resolved by modifying it to 'final arguments = state.uri.queryParameters;'.

**Comment by dam-ease** [comment]
Hi @ChilsungCider. Thanks for filing this. Per this PR https://github.com/flutter/codelabs/pull/1791, I see this has been fixed and should be released soon. See also: https://github.com/flutter/codelabs/blob/main/firebase-get-to-know-flutter/step_05/lib/main.dart
Thank you!
