### ISSUE TITLE
Check validate Fingerprint data

### ISSUE THREAD

**Issue by vickygaugau** [flutter/flutter#137589]
Hi everyone,
I have an issues.
The mobile (both iOS, android) can be registered a lot of finger or face (of diffirent people)
But my app want to accept for just only 1 pepople (for others security)
So that my app want to get data response when finger or face is checked to compare finger or face before (or another ways)
(Just only 1 finger or face is registered before in my app, maybe compare by data response)
Have you any idea to resolve this issues
Thanks alot

**Comment by danagbemava-nc** [comment]
At this point in time, neither android nor iOS provides a way for you to know which user the biometric data belongs to. It is unlikely that they will provide this information as that would be a breach of the users' privacy. 

Your best bet to use a PIN or some other authentication mechanism in addition to the biometrics to ensure that the user who is logging in is the one you expect to login. 

Closing from here as this is not a flutter issue. In the future, you may ask these types of questions on StackOverflow or other community channels.
