### ISSUE TITLE
Firebase for Flutter -> 6.Firebase에 메세지 쓰기

### ISSUE THREAD

**Issue by ChilsungCider** [flutter/flutter#137536]
6.Firebase에 메세지 쓰기에 중간 부분에 있는 앱 미리보기 부분에 Android 부분 미리보기에서 앱 맨 하단에만 "Foo Bar: Hi Bob!", "Bob Katz: Hi Foo!" 이 두 메세지가 표시되면 안되는데 표시되어 있습니다!

**Comment by ChilsungCider** [comment]
Firebase for Flutter -> 6.Writing Message to Firebase
In the middle part of the "6. Writing Messages to Firebase," within the app preview section, in the Android preview, the two messages "Foo Bar: Hi Bob!" and "Bob Katz: Hi Foo!" should not be displayed at the bottom of the app, but they are being shown!

**Comment by dam-ease** [comment]
Hi @ChilsungCider. Thanks for filing this. I see there is an already open issue describing this case https://github.com/flutter/flutter/issues/137402. Closing this in favour of the already open issue.
Thank you
