### ISSUE TITLE
Add support for tone-based surface colors

### ISSUE THREAD

**Issue by amal-stack** [flutter/flutter#137679]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case
[Part of #91605]
Material 3 has introduced tone-based surface colors:
https://m3.material.io/styles/color/overview#fb46760e-a96a-4d05-9ca6-2b6754ddfb73

These changes appear to be part of a wider set of updates to the color system, see [this](https://youtu.be/vnDhq8W98O4?t=649). 
 
# Updates

## Added

The following color roles have been added. See: https://m3.material.io/styles/color/the-color-system/color-roles:
| Color Role                           | Tone: Light | Tone: Dark |
| ------------------------------------ | ----------- | ---------- |
| Surface Dim                          | N-87        | N-6        |
| Surface Bright                       | N-98        | N-24       |
| Surface Container Lowest             | N-100       | N-4        |
| Surface Container Low                | N-96        | N-10       |
| Surface Container                    | N-94        | N-12       |
| Surface Container High               | N-92        | N-17       |
| Surface Container Highest            | N-90        | N-22       |

New fixed accent colors have also been introduced (see #137683).

## Changed
1. Tones for the "Surface" color role have been updated:
    ### Old
    | Color Role | Tone: Light | Tone: Dark |
    | ---------- | ----------- | ---------- |
    | Surface    | ~~N-99~~    | ~~N-10~~   |

    ### New
    | Color Role | Tone: Light | Tone: Dark |
    | ---------- | ----------- | ---------- |
    | Surface    | N-98        | N-6        |

2. The chroma for the neutral palette has been increased from 4 to 6.

## Deprecated
The following color roles are marked as legacy/deprecated:
* ~~Background~~
* ~~On background~~
*  ~~Surface variant~~

As stated [here](https://m3.material.io/styles/color/the-color-system/tokens):
> Note: Background is a legacy color role. It is recommended to use Surface instead of Background.

The "On background" and "Surface Variant" roles still exist in the list of tokens but are not shown as part of the color scheme and possibly will be deprecated soon.

### Proposal
Update the `ColorScheme` implementation to add color roles for tone-based surface colors. Many components also use the new surface color roles as part of their specification. Update the components to use the new color roles. 
## Implementation
Currently, Flutter generates the Material 3 color schemes using `ColorScheme.fromSeed` which, in turn, uses the [`Scheme`](https://api.flutter.dev/flutter/package-material_color_utilities_scheme_scheme/Scheme-class.html) class of the [Material Color Utilities](https://github.com/material-foundation/material-color-utilities) package. 

However, it appears that the `Scheme` class will be deprecated soon in favor of [`DynamicScheme`](https://pub.dev/documentation/material_color_utilities/latest/scheme_dynamic_scheme/DynamicScheme-class.html). The *make_schemes.md* file in the Material Color Utilities [GitHub repository](https://github.com/material-foundation/material-color-utilities) has instructions for [migrating from `Scheme`](https://github.com/material-foundation/material-color-utilities/blob/main/make_schemes.md).

The `ColorScheme` class will also have to be updated to include the new color roles.

**Comment by huycozy** [comment]
Thanks for filing a detailed issue. However, I see there's an open issue addressing the case you described https://github.com/flutter/flutter/issues/115912. 

Closing this issue as a duplicate, so please leave your comment there that will help consolidate the issue. Thank you!

**Comment by peter100u** [comment]
What is the specific API that I couldn't find in the theme

**Comment by amal-stack** [comment]
@peter100u Are you referring to the `Scheme` or `DynamicScheme` class?

**Comment by peter100u** [comment]
> @peter100u你指的是`Scheme`or`DynamicScheme`类吗？

![image](https://github.com/flutter/flutter/assets/14010579/fe2e5b82-5b6d-4924-a3fe-bca4314d72ca)
I mean how to obtain different height APIs

**Comment by amal-stack** [comment]
@peter100u Flutter's `ColorScheme` class does not provide access to the tonal palette directly. It uses the [Material Color Utilities package](https://pub.dev/packages/material_color_utilities) to generate the palettes. If you want access to the tonal palettes directly, you have to add this package and generate a `CorePalette` :
```
Color seed = yourColor;
CorePalette palette = CorePalette.of(seed);
```
In the above image "*N*" stands for the neutral palette. For example, "Surface Dim" in light theme is "N-87". This can be accessed as:
```
Color surfaceDim = Color(palette.neutral.get(87));
```

**Comment by peter100u** [comment]
> @peter100uFlutter 的`ColorScheme`类不提供直接访问色调调色板的功能。它使用[Material Color Utilities 包](https://pub.dev/packages/material_color_utilities)来生成调色板。如果您想直接访问色调调色板，则必须添加此包并生成`CorePalette`：
> 
> ```dart
> Color seed = yourColor;
> CorePalette palette = CorePalette.of(seed);
> ```
> 
> 在上图中，“ _N_ ”代表中性调色板。例如，浅色主题中的“Surface Dim”是“N-87”。可以通过以下方式访问：
> 
> ```dart
> Color surfaceDim = Color(palette.neutral.get(87));
> ```

Thank you for your reply. It would be great if different tones could be obtained from the theme or colorschme, as our project theme is dynamic and not fixed, making it difficult to obtain them from a single color. We will obtain them from the main color of the current theme, etc
