### ISSUE TITLE
run demo crash on oppo devices.please help me 

### ISSUE THREAD

**Issue by steven-gao** [flutter/flutter#137684]
i download demo from " https://github.com/flutter/packages/tree/main/packages/image_picker/image_picker" address.
i entered the home page and clicked camera button ,I tried it 3 times and it happened again。
some information will help you to Positioning error。

i recorded the step by mobile System recorder。

https://github.com/flutter/flutter/assets/4360916/697c6e53-c2dd-4095-9cd9-6d6445954b79

Device details:
brand : oppo A72 5G /PDYT 20
android 12
the log trace：
`Installing build/app/outputs/flutter-apk/app-debug.apk...         419.3s
Syncing files to device PDYT20...                                  137ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on PDYT20 is available at: http://127.0.0.1:51603/F1NOV179ATs=/
D/hw-ProcessState(10886): Binder ioctl to enable oneway spam detection failed: Invalid argument
The Flutter DevTools debugger and profiler on PDYT20 is available at: http://127.0.0.1:9102?uri=http://127.0.0.1:51603/F1NOV179ATs=/
D/SurfaceComposerClient(10886): VRR [FRTC] client handle [bufferId:18446744073709551615 framenumber:0] [ffffffff, ffffffff]
E/OpenGLRenderer(10886): fbcNotifyFrameComplete error: undefined symbol: fbcNotifyFrameComplete
E/OpenGLRenderer(10886): fbcNotifyNoRender error: undefined symbol: fbcNotifyNoRender
D/ViewRootImpl[FlutterActivity](10886):  debugCancelDraw  cancelDraw=false,count = 212,android.view.ViewRootImpl@2e52cd4
D/SurfaceComposerClient(10886): VRR [FRTC] client handle [bufferId:18446744073709551615 framenumber:0] [ffffffff, ffffffff]
D/ProfileInstaller(10886): Installing profile for io.flutter.plugins.imagepicker.example
V/AutofillManager(10886): requestHideFillUi(null): anchor = null
E/BLASTBufferQueue(10886): [SurfaceView[io.flutter.plugins.imagepicker.example/io.flutter.embedding.android.FlutterActivity]#1](f:0,a:2) isEGL=1, mPendingRelease.size()=1, mMaxAcquiredBuffers=4, currentMaxAcquiredBufferCount=2
E/BLASTBufferQueue(10886): [SurfaceView[io.flutter.plugins.imagepicker.example/io.flutter.embedding.android.FlutterActivity]#1](f:0,a:3) isEGL=1, mPendingRelease.size()=2, mMaxAcquiredBuffers=4, currentMaxAcquiredBufferCount=2
V/AutofillManager(10886): requestHideFillUi(null): anchor = null
I/BufferQueueProducer(10886): [SurfaceView[io.flutter.plugins.imagepicker.example/io.flutter.embedding.android.FlutterActivity]#1(BLAST Consumer)1](id:2a8600000001,api:1,p:10886,c:10886) disconnect: api 1
E/BLASTBufferQueue(10886): BLASTBufferItemConsumer::onDisconnect()
I/BufferQueueProducer(10886): [SurfaceView[io.flutter.plugins.imagepicker.example/io.flutter.embedding.android.FlutterActivity]#1(BLAST Consumer)1](id:2a8600000001,api:0,p:-1,c:10886) disconnect: api -1
I/BLASTBufferQueue(10886): [SurfaceView[io.flutter.plugins.imagepicker.example/io.flutter.embedding.android.FlutterActivity]#1] destructor()

V/AutofillManager(10886): requestHideFillUi(null): anchor = null
V/AutofillManager(10886): requestHideFillUi(null): anchor = null
I/BufferQueueProducer(10886): [SurfaceView[io.flutter.plugins.imagepicker.example/io.flutter.embedding.android.FlutterActivity]#3(BLAST Consumer)3](id:2a8600000003,api:1,p:10886,c:10886) disconnect: api 1
E/BLASTBufferQueue(10886): BLASTBufferItemConsumer::onDisconnect()
I/BufferQueueProducer(10886): [SurfaceView[io.flutter.plugins.imagepicker.example/io.flutter.embedding.android.FlutterActivity]#3(BLAST Consumer)3](id:2a8600000003,api:0,p:-1,c:10886) disconnect: api -1
I/BLASTBufferQueue(10886): [SurfaceView[io.flutter.plugins.imagepicker.example/io.flutter.embedding.android.FlutterActivity]#3] destructor()
I/BufferQueueConsumer(10886): [SurfaceView[io.flutter.plugins.imagepicker.example/io.flutter.embedding.android.FlutterActivity]#3(BLAST Consumer)3](id:2a8600000003,api:0,p:-1,c:10886) disconnect
I/BufferQueueProducer(10886): [ViewRootImpl[FlutterActivity]#2(BLAST Consumer)2](id:2a8600000002,api:1,p:10886,c:10886) disconnect: api 1
E/BLASTBufferQueue(10886): BLASTBufferItemConsumer::onDisconnect()
I/BLASTBufferQueue(10886): releaseBufferCallbackThunk bufferId:46755013984271 framenumber:19 blastBufferQueue is dead
I/BLASTBufferQueue(10886): [ViewRootImpl[FlutterActivity]#2] destructor()
I/BufferQueueConsumer(10886): [ViewRootImpl[FlutterActivity]#2(BLAST Consumer)2](id:2a8600000002,api:0,p:-1,c:10886) disconnect
I/BLASTBufferQueue(10886): releaseBufferCallbackThunk bufferId:46755013984264 framenumber:33 blastBufferQueue is dead
Lost connection to device.`

Looking forward to your reply！
thank you for your time!

**Comment by stuartmorgan** [comment]
What's shown in the video is not a crash, it's background activity destruction; see the section "Handling MainActivity destruction" is [the README](https://pub.dev/packages/image_picker#android).

Closing as this is OS behavior that is beyond the plugin's ability to control.

**Comment by steven-gao** [comment]
firstly ,thank your reply.
but i have a question that why other brand phone is not have this Phenomenon?and this action very list app crash.
