### ISSUE TITLE
[Impeller] Support external (surface) textures in Vulkan

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#137639]
> [!NOTE]  
> This is a quasi-placeholder issue, as I only learned what a "Surface Texture" is ~5 minutes ago, so part of the resolution will be updating this issue with actual useful information. Thanks for your patience 😄 

---

An Android [`SurfaceTexture`](https://source.android.com/docs/core/graphics/arch-st) is a combination of a surface and an [OpenGL ES (GLES)](https://www.khronos.org/opengles/) texture [^1].

For example, this would be used to display frames from a camera plugin:

![](https://source.android.com/static/docs/core/graphics/images/continuous_capture_activity.png)

On newer devices (or is it APIs? I'm not sure), Android provides a backend-agnostic hardware buffer that can be used (directly) by Vulkan but on older devices we'll receive an OpenGL-backed surface texture, and need to adapt it for use within Vulkan - that will involve creating a new OpenGL context, and some interop.

Some possible references:

- https://stackoverflow.com/questions/56970011/how-to-pass-a-texture-between-opengl-es-and-vulkan
- https://stackoverflow.com/questions/38907764/how-to-render-to-opengl-from-vulkan?rq=3

As an initial look, I'll try [`package:camera`](https://pub.dev/packages/camera) in an Impeller+Vulkan demo. It might also be worth looking into Skia's codebase to see how they handle this.

/cc @jonahwilliams @johnmccutchan (feel free to edit this description if inaccurate!)

[^1]: https://source.android.com/docs/core/graphics/arch-st

**Comment by johnmccutchan** [comment]
Jonah is correct, SurfaceTexture support is part of our public API and so any application is free to give us a SurfaceTexture and ask Flutter to render it as a texture layer forever regardless of Android version.

Based on research I did, a tractable path to solving this problem is to:

1. Allocate a Vulkan texture
2. Use the GL external memory extensions to create a rendering target that is backed by the Vulkan allocated texture.
3. Do a blit pass to copy the GL_TEXTURE_EXTERNAL_OES texture into the Vulkan image.

I've also dug into the implementation of SurfaceTextures and internally they are backed by HardwareBuffers, there is even a non-public NDK function that will retrieve the HardwareBuffer from the SurfaceTexture. I was planning on proposing that Android make the function public in a future SDK release. We would still need the above approach in the meantime.

**Comment by matanlurey** [comment]
This was useful (and somewhat buried): https://docs.flutter.dev/tools/android-studio#android-ide.

**Comment by matanlurey** [comment]
I have a [basic app](https://github.com/matanlurey/flutter_engine_demos/tree/main/surface_texture) that draws a yellow texture from the Android side to render on the Dart side.

<details>

<summary>Kotlin</summary>

```kt
package com.example.surface_texture

import android.graphics.SurfaceTexture
import android.view.Surface
import androidx.annotation.NonNull
import io.flutter.embedding.engine.plugins.FlutterPlugin
import io.flutter.plugin.common.MethodCall
import io.flutter.plugin.common.MethodChannel
import io.flutter.plugin.common.MethodChannel.MethodCallHandler

class SurfaceTexturePlugin : FlutterPlugin, MethodCallHandler {
    private lateinit var channel: MethodChannel
    private lateinit var mFlutterPluginBinding: FlutterPlugin.FlutterPluginBinding
    private lateinit var mSurfaceTexture: SurfaceTexture
    private lateinit var mSurface: Surface

    override fun onAttachedToEngine(@NonNull binding: FlutterPlugin.FlutterPluginBinding) {
        mFlutterPluginBinding = binding
        channel = MethodChannel(mFlutterPluginBinding.binaryMessenger, "surface_texture")
        channel.setMethodCallHandler(this)
    }

    override fun onMethodCall(@NonNull call: MethodCall, @NonNull result: MethodChannel.Result) {
        when (call.method) {
            "generateSurfaceTexture" -> {
                val surfaceHeight = call.argument<Int>("height")
                val textureId = generateSurfaceTexture(surfaceHeight ?: 0)
                result.success(textureId)
            }
            "setSurfaceBufferSize" -> {
                val surfaceHeight = call.argument<Int>("height");
                setSurfaceBufferSize(surfaceHeight ?: 0)
                result.success(null)
            }
            else -> {
                result.notImplemented()
            }
        }
    }

    override fun onDetachedFromEngine(binding: FlutterPlugin.FlutterPluginBinding) {
        channel.setMethodCallHandler(null)
    }

    private fun generateSurfaceTexture(surfaceHeight: Int): Long {
        val textureRegistry = mFlutterPluginBinding.textureRegistry
        val surfaceTextureEntry = textureRegistry.createSurfaceTexture()
        mSurfaceTexture = surfaceTextureEntry.surfaceTexture()
        mSurfaceTexture.setDefaultBufferSize(1080, surfaceHeight)
        mSurface = Surface(mSurfaceTexture)

        val canvas = mSurface.lockCanvas(null)
        canvas.drawRGB(255, 230, 15)
        mSurface.unlockCanvasAndPost(canvas)

        return surfaceTextureEntry.id()
    }

    private fun setSurfaceBufferSize(surfaceHeight: Int) {
        mSurfaceTexture.setDefaultBufferSize(1080,surfaceHeight)
        val canvas = mSurface.lockCanvas(null)
        canvas.drawRGB(255, 230, 15)
        mSurface.unlockCanvasAndPost(canvas)
    }
}
```

</details>

<details>

<summary>Dart</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MainApp());
}

final class SurfaceTexturePlugin {
  static const _channel = MethodChannel('surface_texture');

  static Future<int?> generateSurfaceTexture({int height = 0}) async {
    return await _channel.invokeMethod(
      'generateSurfaceTexture',
      {'height': height},
    );
  }

  static Future<void> setSurfaceBufferSize({int height = 0}) async {
    return await _channel.invokeMethod(
      'setSurfaceBufferSize',
      {'height': height},
    );
  }
}

final class MainApp extends StatefulWidget {
  const MainApp({super.key});

  @override
  State<MainApp> createState() => _MainAppState();
}

final class _MainAppState extends State<MainApp> {
  int? _textureId;
  double _height = 0;

  @override
  void initState() {
    super.initState();
    _initTextureState();
  }

  Future<void> _initTextureState() async {
    int? textureId;

    try {
      textureId = await SurfaceTexturePlugin.generateSurfaceTexture(
        height: _height.toInt(),
      );
    } on PlatformException {
      debugPrint('Failed to generate surface texture.');
    }

    if (!mounted) {
      return;
    }

    setState(() {
      _textureId = textureId;
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
          appBar: AppBar(
            title: const Text('Surface Texture Demo'),
          ),
          body: _textureId == null
              ? const Center(child: CircularProgressIndicator())
              : SingleChildScrollView(
                  child: Column(
                    children: [
                      Text('Texture ID: $_textureId, Height: $_height'),
                      Slider(
                        value: _height,
                        min: 0,
                        max: 1080 * 2,
                        onChanged: (value) {
                          setState(() {
                            _height = value;
                          });
                          SurfaceTexturePlugin.setSurfaceBufferSize(
                            height: _height.toInt(),
                          );
                        },
                      ),
                      _Texture(textureId: _textureId!, height: _height),
                    ],
                  ),
                )),
    );
  }
}

final class _Texture extends StatelessWidget {
  final int _textureId;
  final double _surfaceHeight;

  const _Texture({
    required int textureId,
    double height = 0,
  })  : _textureId = textureId,
        _surfaceHeight = height;

  @override
  Widget build(BuildContext context) {
    return Center(
      child: SizedBox(
        width: 1080,
        height: _surfaceHeight,
        child: Texture(textureId: _textureId),
      ),
    );
  }
}
```

</details>

With the Skia backend, it works as expected:

![flutter_01](https://github.com/flutter/flutter/assets/168174/cdec6de8-5e9b-443a-bdeb-f37b65ae4275)

With Impeller (Vulkan, Pixel 5):

![flutter_02](https://github.com/flutter/flutter/assets/168174/8966e6f8-5c89-4ad0-8b0d-8a8db1872ff0)

**Comment by matanlurey** [comment]
For my own self discovery, how this works from framework <-> engine is:

- [`ui.SceneBuilder`](https://github.com/flutter/engine/blob/3b944b6a67613e78e3253b88fd6b0603629753f4/lib/ui/compositing.dart) has an `void addTexture(int textureId, ...)` method.
- [`SceneBuilder`](https://github.com/flutter/engine/blob/7a2eaf42dbaed57406eb9be4f8fdbfaa079c3d71/lib/ui/compositing/scene_builder.cc) receives it, and creates a [`flutter::TextureLayer`](https://github.com/flutter/engine/blob/5b31f4f0d9b6973944aba742a70133d8078c23fe/flow/layers/texture_layer.h). 
- I think `TextureLayer::Paint` (https://github.com/flutter/engine/blob/0d5b780b16ebff2b520e90c1107ba7503a9833b4/flow/layers/texture_layer.cc#L50-L69) is what actually passes this information on to the canvas/displaylist.

**Comment by matanlurey** [comment]
https://github.com/flutter/engine/pull/36498 added support for iOS (though I think this PR meant to say, "on iOS in Impeller"). Also a quick check, if I try on an OpenGL device (Moto G4), I get a hard crash (where on a Vulkan device, nothing renders but there is no crash):

```txt
Abort message: '[FATAL:flutter/impeller/renderer/backend/gles/proc_table_gles.h(38)] Fatal GL Error GL_INVALID_ENUM(1280) encountered on call to glTexParameteri
```

**Comment by matanlurey** [comment]
@jonahwilliams Can you clarify if the goal is to _only_ wire up Vulkan and did you expect GLES to be working already?

**Comment by jonahwilliams** [comment]
GLES is a separate issue

**Comment by matanlurey** [comment]
Chatted with @jonahwilliams:

> For what needs to be done with Impeller I would look at John's more recent PRs.

Some examples:

- https://github.com/flutter/engine/pull/44979
- https://github.com/flutter/engine/pull/46786
- https://github.com/flutter/engine/pull/47358

> That does most of the plumbing on GLES. But the external/is_wrapped flag isn't something that will be usable - that only works for GLES - GLES interop, not GLES Vulkan interop
>
> You'll want to look at surface_texture_external_texture variants

See [`surface_texture_external_texture.h`](https://github.com/flutter/engine/blob/d41d85349189e5f89023342471faa3ba6f6f7036/shell/platform/android/surface_texture_external_texture.h) and [`surface_texture_external_texture_gl.h`](https://github.com/flutter/engine/blob/d41d85349189e5f89023342471faa3ba6f6f7036/shell/platform/android/surface_texture_external_texture_gl.h).

> that is where you will need to 1) allocate a vulkan texture with the extensions/external info that John linked in the bug and 2) copy the OES texture into that vulkan texture

**Comment by matanlurey** [comment]
@jonahwilliams Just to clarify before I get started (I realize it will take a few iterations), my goal is to do something similar to https://github.com/flutter/engine/pull/44734#issue-1851988330, i.e. I'd end up with a `surface_texture_external_texture_vk.[cc|h]`, and obviously have it working as well.

**Comment by jonahwilliams** [comment]
Yeah that seems like a good place to start.

**Comment by matanlurey** [comment]
I made some progress in https://github.com/flutter/engine/pull/47632 on being able to test the texture selection logic, but ran into too many hickups (https://github.com/flutter/flutter/issues/138015, for example), and found out that it doesn't appear possible to setup a (real) EGL surface in the Android emulator (or it was not trivial):

```shell
$ adb logcat

11-07 12:56:58.180 10067 10067 E flutter : [ERROR:flutter/shell/platform/android/platform_view_android.cc(75)] CreateAndroidContext
11-07 12:56:58.263 10067 10067 D libEGL  : loaded /vendor/lib64/egl/libEGL_emulation.so
11-07 12:56:58.268 10067 10067 D libEGL  : loaded /vendor/lib64/egl/libGLESv1_CM_emulation.so
11-07 12:56:58.271 10067 10067 D libEGL  : loaded /vendor/lib64/egl/libGLESv2_emulation.so
11-07 12:56:58.308 10067 10067 E flutter : [ERROR:flutter/shell/platform/android/android_context_gl_skia.cc(87)] Could not choose an EGL configuration.
11-07 12:56:58.308 10067 10067 E flutter : [ERROR:flutter/shell/platform/android/android_egl_surface.cc(52)] EGL Error: EGL_SUCCESS (12288)
11-07 12:56:58.309 10067 10067 F flutter : [FATAL:flutter/shell/platform/android/platform_view_android.cc(153)] Check failed: android_context_->IsValid(). Could not create surface from invalid Android context.
```

Given this isn't making any real progress towards getting surface textures working, I'm going to halt trying to have a good testing workflow (outside of manual tests) until I have something working end-to-end locally, and then explore some refactors (like https://github.com/flutter/flutter/issues/137798) to make testing the code easier.

**Comment by matanlurey** [comment]
Closing this issue in favor of https://github.com/flutter/flutter/issues/139702. Thanks!

**Comment by yann-q-20230331** [comment]
> I made some progress in [flutter/engine#47632](https://github.com/flutter/engine/pull/47632) on being able to test the texture selection logic, but ran into too many hickups (#138015, for example), and found out that it doesn't appear possible to setup a (real) EGL surface in the Android emulator (or it was not trivial):
> 
> ```shell
> $ adb logcat
> 
> 11-07 12:56:58.180 10067 10067 E flutter : [ERROR:flutter/shell/platform/android/platform_view_android.cc(75)] CreateAndroidContext
> 11-07 12:56:58.263 10067 10067 D libEGL  : loaded /vendor/lib64/egl/libEGL_emulation.so
> 11-07 12:56:58.268 10067 10067 D libEGL  : loaded /vendor/lib64/egl/libGLESv1_CM_emulation.so
> 11-07 12:56:58.271 10067 10067 D libEGL  : loaded /vendor/lib64/egl/libGLESv2_emulation.so
> 11-07 12:56:58.308 10067 10067 E flutter : [ERROR:flutter/shell/platform/android/android_context_gl_skia.cc(87)] Could not choose an EGL configuration.
> 11-07 12:56:58.308 10067 10067 E flutter : [ERROR:flutter/shell/platform/android/android_egl_surface.cc(52)] EGL Error: EGL_SUCCESS (12288)
> 11-07 12:56:58.309 10067 10067 F flutter : [FATAL:flutter/shell/platform/android/platform_view_android.cc(153)] Check failed: android_context_->IsValid(). Could not create surface from invalid Android context.
> ```
> 
> Given this isn't making any real progress towards getting surface textures working, I'm going to halt trying to have a good testing workflow (outside of manual tests) until I have something working end-to-end locally, and then explore some refactors (like #137798) to make testing the code easier.

I meet the same error. Your problem has been resolved? Can you tell me about how to resolve this issue.Thanks, look forward to your reply
