### ISSUE TITLE
`flutter --version` could print the engine version that I downloaded from cloud storage

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1376]
This is what I see now:

```
~/flutter/testme $ flutter --version
Flutter
Repository: git@github.com:flutter/flutter.git
Branch: alpha
Revision: 2d6dd63e377b9d4131fa120fad249461f9602684 (2 days ago)
```

It might be useful for debugging issues, if this output included the version of the engine that was downloaded by the tools. Especially for iOS.

**Comment by sethladd** [comment]
cc @chinmaygarde thoughts?

**Comment by eseidelGoogle** [comment]
packages/sky_engine/REVISION is the version which is used for populating the artifact cache `flutter cache populate`, etc.

I'm not entirely sure what use case you're looking for here.

**Comment by sethladd** [comment]
My iOS app doesn't start, and I'd like to provide as much info as possible to the Flutter team so they can help diagnose the problem.

If it's not useful to confirm that I have the right engine version, we can close this.

**Comment by sethladd** [comment]
Addressed by https://github.com/flutter/flutter/pull/1477
