### ISSUE TITLE
[shared_preferences] Support namespaces/prefixes for multi-account apps

### ISSUE THREAD

**Issue by tmpfs** [flutter/flutter#137608]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I have an app that supports multiple accounts and want separate `SharedPreferences` per account.

### Proposal

If an app supports multiple accounts and wants to use separate preferences per account the current `shared_preferences` implementation does not suffice.

I suggest allowing `SharedPreferences.setPrefix()` to be allowed to be called multiple times (currently it throws an error) and to invalidate the cache each time `setPrefix()` is called.

This would allow multi-account apps to separate preferences per account.

**Comment by dam-ease** [comment]
Hi @tmpfs. Thanks for filing this. I see there was a similar proposal https://github.com/flutter/flutter/issues/52544 which has been implemented with https://github.com/flutter/packages/pull/3596. Can you check this out to see if its similar to the case you described?

**Comment by tmpfs** [comment]
@dam-ease I don't think that issue is related.

SharedPreferences recently got setPrefix() which would have resolved that issue however getPrefix() can only be called once before getInstance() is called.

If it were possible to call it multiple times (and invalidate the cache - maybe a manual call to reload()) then it would be possible to separate preferences per account by using an account identifier as the prefix.

**Comment by tmpfs** [comment]
FWIW, I have implemented this for my app with an API exactly the same as `SharedPreferences` backed by JSON files on disc I am raising this as it's an obvious shortcoming of the shared_preferences API and would have saved me time if setPrefix() worked in the way I describe.

**Comment by stuartmorgan** [comment]
The prefix was related to a specific legacy behavior that we were constrained to work around for backward compatibility, and isn't something we currently plan to keep in the API.

It seems like this could be trivially implemented at the application level via a wrapper around `SharedPreferences`, where each instance of the wrapper takes a prefix when it is created, and it adds that prefix to all get/set calls. Is there a reason that wouldn't work in your use case?

**Comment by tmpfs** [comment]
@stuartmorgan , that would work. Should I not rely on `setPrefix()` remaining in the API?

I still think it would be good if it was supported as it would make this use case trivial as opposed to everybody implementing wrappers. I imagine I am not the only person making multi-account apps that require preference separation.

**Comment by stuartmorgan** [comment]
> I still think it would be good if it was supported as it would make this use case trivial as opposed to everybody implementing wrappers.

This sounds like a good argument for someone releasing a package that implements the wrappers, which avoids the need for re-implementation without adding that API complexity to the new API surface of the core plugin.

> I imagine I am not the only person making multi-account apps that require preference separation.

That is likely true, but it's also the case that as far as I know nobody has ever requested that feature before, which is evidence that this is not so common a use case that it warrants additional API in the plugin itself.

Closing since a community package providing the wrapper seems like the best option here.
