### ISSUE TITLE
BackgroundIsolateBinaryMessenger.ensureInitialized spamming error logging when it could gracefully handle the null case

### ISSUE THREAD

**Issue by dallas1287** [flutter/flutter#137687]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

```
  static void ensureInitialized(ui.RootIsolateToken token) {
    if (_instance == null) {
      ui.PlatformDispatcher.instance.registerBackgroundIsolate(token);
      final BackgroundIsolateBinaryMessenger portBinaryMessenger =
          BackgroundIsolateBinaryMessenger._();
      _instance = portBinaryMessenger;
      portBinaryMessenger._receivePort.listen((dynamic message) {
        try {
          final List<dynamic> args = message as List<dynamic>;
          final int identifier = args[0] as int;
          final Uint8List bytes = args[1] as Uint8List;
          final ByteData byteData = ByteData.sublistView(bytes);
          portBinaryMessenger._completers
              .remove(identifier)!
              .complete(byteData);
        } catch (exception, stack) {
          FlutterError.reportError(FlutterErrorDetails(
            exception: exception,
            stack: stack,
            library: 'services library',
            context:
                ErrorDescription('during a platform message response callback'),
          ));
        }
      });
    }
  }

```
This function spams pretty hard when I try to use it about the _completers.remove(identifier)! executing on a null reference. It seems like instead of try catching this, it could just optionally be completed if it actually removes the object from the list? It's also possible I'm using it wrong but I don't think so as anytime I try to call it while not being the background isolate I'm trying to use I get the error that it hasn't been initialized. But despite this spamming the thread and the plugin work fine when I call this at start up of the thread.
Again, I could be doing something wrong and will take any advice there as well, but it does seem like this is a pretty easy switch to avoid spamming debug exception messages.

### Proposal

I'd imagine something like this would be minimally acceptable. But if you wanted to break it up and log a warning about not having a completer to remove for the identifier, that seems like it'd be pretty straight forward as well.
```
          portBinaryMessenger._completers
              .remove(identifier)?
              .complete(byteData);
```

**Comment by chinmaygarde** [comment]
From Triage: We weren't able to figure out when an unknown identifier would be encountered. Is this a bug disguised as a feature request? Can we have a reproducible test case please?
