### ISSUE TITLE
Missing calls to "registerWith()" in generated dart_plugin_registrant.dart

### ISSUE THREAD

**Issue by zr6328** [flutter/flutter#137607]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1.create a plugin by dartPluginClass
2. create a flutter project
3. compile the app by using cross-build's method
4. open the file `.dart_tool/flutter_build/dart_plugin_registrant.dart`
5. find the symbol of registerWith in libapp.so

### Expected results

The symbol of registerWith in libapp.so will both in linux-x64 and  linux-arm64

### Actual results

In linux-x64 the symbol of registerWith exists in libapp.so, but in linux-arm64, we can't not find symbol of registerWith in libapp.so

### Code sample

the plugin's code look like this:

```dart
  plugin:
      implements: plugin_platform_template_interface
      platforms:
        macos:
          dartPluginClass: FlutterMacPlugin
```

the dart_plugin_registrant.dart look like this:
```dart
@pragma('vm:entry-point')
class _PluginRegistrant {
  @pragma('vm:entry-point')
  static void register() {
    print('zrzrzrzr register function called!!!!');
    if (Platform.isAndroid) {
      print("zrzrzrzr platform is android");
    } else if (Platform.isIOS) {
      print("zrzrzrzr platform is ios");
    } else if (Platform.isLinux) {
      print("zrzrzrzr platform is Linux");
      try {
        FlutterLinuxPlugin.registerWith();
      } catch (err) {
        print(
          '`flutter_linux_plugin` threw an error: $err. '
          'The app may not function as expected until you remove this plugin from pubspec.yaml'
        );
      }

    } else if (Platform.isMacOS) {
      print("zrzrzrzr platform is Macos");
      try {
        FlutterMacPlugin.registerWith();
      } catch (err) {
        print(
          '`flutter_mac_plugin` threw an error: $err. '
          'The app may not function as expected until you remove this plugin from pubspec.yaml'
        );
      }

    } else if (Platform.isWindows) {
      print('zrzrzrzr platform is Windows');
    }
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

no value

**Comment by zr6328** [comment]
> Hi @zr6328. Thanks for filing this. I see there is an issue similar to the case you are describing #99883. Can you check this out to see if it fully describes your issue?

sorry, i think this method can't help me

**Comment by zr6328** [comment]
> Hi @zr6328. Thanks for filing this. I see there is an issue similar to the case you are describing #99883. Can you check this out to see if it fully describes your issue?

I think this is caused by cross-build form linux-x64 to linux-arm64

**Comment by dam-ease** [comment]
Thanks for your response. Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code, in this case you could share a sample repo and steps in which we could run and reproduce this issue with your repo?
