### ISSUE TITLE
from flutter page jump to Activity, then back to flutter page, Page display is abnormal.

### ISSUE THREAD

**Issue by longdw** [flutter/flutter#137663]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [x] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. flutter page, use MethodChannel connect to native.
2. flutter page jump to Activity.
3. after a while back to flutter page.
4. all text and some image can't display.

### Expected results

all widget can display normal

### Actual results

 all text and some image can't display.

### Code sample

<details><summary>Code sample</summary>

```dart
@override
  Future<bool?> startNavi(BNFCoordinate startLocation, BNFCoordinate endLocation, String routesInfoExt) async {

    bool result = false;
    try {
      Map map = (await naviChannel.invokeMethod(
      BNFNaviMethodID.kStartNavi,
          {
            'startLocation': startLocation.toMap(),
            'endLocation': endLocation.toMap(),
            'routesInfoExt': routesInfoExt
          } as dynamic)) as Map;
      result = map['result'] as bool;
    } on PlatformException catch (e) {
      print(e.toString());
    }
    return result;
  }

Communit with native applications through MethodChannel, and then jump to native page BaiduMapNaviActivity : FragmentActivity() {
 xxx
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/4987178/d53695ee-72f8-4813-86c3-7de77d8ff669

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.1, on macOS 13.5.2 22G91 darwin-arm64, locale
    en-CN)
    • Flutter version 3.13.1 on channel stable at
      /Users/longdawei/flutter_3.13.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e1e47221e8 (2 months ago), 2023-08-22 21:43:18 -0700
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/longdawei/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/longdawei/Library/Android/sdk
    • Java binary at: /Applications/Android Studio
      2.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
```

</details>

**Comment by dam-ease** [comment]
Hi @longdw. Thanks for filing this. Can you upgrade to the latest version of flutter to verify this issue still persists? Also, I'm trying to reproduce this on my end but will need you to help provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), it could be a sample repo as in this case?

**Comment by longdw** [comment]
hi @dam-ease. Thanks for your reply. This issue is not exist when I upgrade flutter to 3.13.9.

**Comment by dam-ease** [comment]
Thanks for your response. I guess this has been fixed in latest versions and I'll be closing this issue per your last comment.
Thank you!
