### ISSUE TITLE
Upgrading flutter should upgrade files we originally created

### ISSUE THREAD

**Issue by maxatcn** [flutter/flutter#13766]
The latest flutter tools upgraded to Gradle 4.1 and Android Studio Gradle plugin 3.0.1, for old flutter projects, I have updated the configuration files to align the change.  But for the new created flutter projects, it will still have to update these configuration files manually.  Otherwise, it will get compile errors.

When the next alpha release comes in(currently, 2017-12-12)?  So that it is with the updates synchronizing with latest flutter tools?   Thank you.

**Comment by Hixie** [comment]
cc @xster @tvolkert

**Comment by xster** [comment]
Merging into #12573
