### ISSUE TITLE
Error with gradle in vs code running flutter

### ISSUE THREAD

**Issue by henri045** [flutter/flutter#137645]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Create a new project in vs code.
Use a virtual device to run the software.
Run the program, debug does not work properly and error with gradle comes.

### Actual results

```
FAILURE: Build failed with an exception.

* Where:
Build file 'D:\user 1\Documents\flutter_project\sec\flutter_app\android\app\build.gradle' line: 4

* What went wrong:
An exception occurred applying plugin request [id: 'dev.flutter.flutter-gradle-plugin', version: '1.0.0']
> Could not find implementation class 'FlutterPlugin' for plugin 'dev.flutter.flutter-gradle-plugin' specified in jar:file:/C:/Users/user%201/.gradle/caches/jars-9/55f6f16d092dc62aa715ddea74c1b9ca/gradle-1.0.0.jar!/META-INF/gradle-plugins/dev.flutter.flutter-gradle-plugin.properties.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 772ms
Running Gradle task 'assembleDebug'...                           1,467ms
Exception: Gradle task assembleDebug failed with exit code 1
```

Hello, it would be grateful if someone could help to solve this issue with my coding, please, I'm really exhausted with this thing now. Below you can see my code for gradle:

```
buildscript {
    ext.kotlin_version = '1.9.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
```

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by danagbemava-nc** [comment]
Hi @henri045, please provide the output of `flutter doctor -v`. 

Can you also share the full content of `android/app/build.gradle`? 

Thank you

**Comment by henri045** [comment]
Hello, I conducted some tweaks and was able to run flutter smoothly as from there.
Thanks for your response and have a good day.
