### ISSUE TITLE
[cupertino_icons] Add example

### ISSUE THREAD

**Issue by foxtrotravi** [flutter/flutter#137682]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I was trying to look for an implementation of the [cupertino_icons](https://pub.dev/packages/cupertino_icons/) but there wasn't any example present on pub.dev. So, I think we should provide an example app.

It would also increase the pub points on cupertino_icons. Currently, it's 120/140.

I would be happy to contribute to this.

### Proposal

There should be an example app present on all of the packages as it makes implementation really easy for any developer.

**Comment by dam-ease** [comment]
Hi @foxtrotravi. Thanks for proposing this. I see there is an example in the documentation attached to the readme https://api.flutter.dev/flutter/cupertino/CupertinoIcons-class.html#constants. Can you can check this out?

**Comment by foxtrotravi** [comment]
@dam-ease yeah, that also works. I was wondering if we could add the same thing to the package's Example tab.

**Comment by foxtrotravi** [comment]
@dam-ease I think you can add the label `good-first-issue` to this. I would be more than happy to contribute to this. I will create a PR for this.

**Comment by stuartmorgan** [comment]
Retitling since per discussion in the PR we likely want an example README rather than app.
