### ISSUE TITLE
Newline on multiline TextField doesn't appear until next character input

### ISSUE THREAD

**Issue by lucaslcode** [flutter/flutter#13765]
## Expected

Press 'return', and the multiline TextField should grow by one line

## What happens

The TextField doesn't grow until the next character is entered.

## Steps to Reproduce

```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'TextField',
      home: new Scaffold(
        appBar: new AppBar(),
        body: new TextField(maxLines: null),
      ),
    );
  }
}
```

![demo](https://user-images.githubusercontent.com/32044095/34325574-6dcf818a-e8e9-11e7-9028-cb7cc410e2f9.gif)

**Comment by jerrywell** [comment]
+1 for this issue.

**Comment by eseidelGoogle** [comment]
This is likely just a quirk of the web-platform's text engine that we're using.  It's possible there are whitespace settings (@abarth or @Hixie might remember) we could apply internally to get the correct behavior, or this is likely just fixed by @jason-simmons in-progress migration to a new text engine.

**Comment by zoechi** [comment]
That's working now for me
```
Flutter 0.2.2-pre.5 • channel dev • https://github.com/flutter/flutter.git
Framework • revision 0608a7a2cc (6 days ago) • 2018-03-23 11:10:37 +0100
Engine • revision 6280adbfb1
Tools • Dart 2.0.0-dev.39.0.flutter-06949dc985
```

**Comment by apgapg** [comment]
Not working:

```
TextField(
              keyboardType: TextInputType.multiline,
              maxLines: null,
            ),

```

[✓] Flutter (Channel dev, v1.14.6, on Mac OS X 10.15.2 19C57, locale en-GB)
