### ISSUE TITLE
`Platform.script` should return a meaningful directory in tests.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#137638]
Right now, `Platform.script` basically returns `path.join(Directory.current, 'main.dart')` in flutter_tester.

There are tests leveraging this to more-or-less figure out what directory they should be looking in for relative things, but it's actually not quite right.

I tried to fix this in https://github.com/flutter/engine/pull/46911, but it was reverted because when flutter_tools runs a test the actual test script is in some temp directory e.g. `/var/tmp/whatever/listener.dart` and it imports the actual test file.

This is frustrating in the engine repo because it means `Platform.script` can't sanely be used. It's also frustrating in the framework repo because it means `Platform.script` doesn't actually tell you what test file is under test.

IMHO we should fix `Platform.script` so that it still points to the actual file being executed, but we also need to provide some information to tests about what file the test originally came from when they're run via flutter_tester. One way to do this would be allowing some method of overriding `Platform.script`, another would be providing some other special/static constant for tests to use.

**Comment by dnfield** [comment]
We may need help from the Dart team if we want to have something like `PlatformOverrides.runZoned` akin to `HttpOverrides.runZoned`.

**Comment by chinmaygarde** [comment]
> There are tests leveraging this to more-or-less figure out what directory they should be looking in for relative things, but it's actually not quite right.

This wasn't intentional and the "script" location almost never made sense in Flutter. Perhaps we should deprecate this and provide a documented way to achieve what the test are trying to divine.

**Comment by a-siva** [comment]
Is there still anything actionable from the dart side on this. I am removing the dart:dependency label and if there is something to be done please relabel it back.

**Comment by busslina** [comment]
In my case, I'm not testing, I'm just wanna know what is the current script to be able to get its parent directory. How can be possible that it just returns `path.join(Directory.current, 'main.dart')`.

This issue was opened 4 months ago and still not solved.

This is not serious.

**Comment by dnfield** [comment]
@busslina This issue is somewhat challenging to fix because the API doesn't work in a rational way but people have come to depend on it. I think it's unlikely that we'll be able to fix `Platform.script` and should probably just document that it's not safe to use in tests, and instead provide some other mechanism in tests (such as a dart defined constant).

**Comment by busslina** [comment]
@dnfield Sorry about the upset. Is there an alternative to know what the directory of the current executing script is?

This is not just an accessory feature, but a fundamental one.

Thanks

**Comment by dnfield** [comment]
The challenge is that when you're running a flutter test, the currently executing script is a generated file in a temp directory.

If you want to know the location of the original source location of the test file, it's more difficult.

**Comment by busslina** [comment]
@dnfield okay, I don't know the flutter implementation. If we got the script path file that we are going to execute why it is so difficult to chain it to Platform.script?

If we are able now to mock it into current directory + main.dart. Can't we know the real path where that is done?

**Comment by jonahwilliams** [comment]
We don't intend to anything more with this
