### ISSUE TITLE
flutter_gallery_assets cannot use alternate storage locations 

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter#13763]
Flutter Gallery's assets are not stored in https://storage.googleapis.com/flutter_infra/. As a result, users cannot use alternate storage locations by specifying the FLUTTER_STORAGE_BASE_URL environment variable.  

https://github.com/flutter/flutter/blob/dd796853ccb8e90d4ce5e9d5a101d66d35c2e6a4/examples/flutter_gallery/pubspec.yaml#L15-L18

The current URL is not accessible from China, as the user reported on Gitter:

![img-2592](https://user-images.githubusercontent.com/348942/34324261-28053f88-e8a7-11e7-8a95-4c32bd4f9197.PNG)

Cc: @jakobr-google @mit-mit 
Related issue: #11681

**Comment by mit-mit** [comment]
@Hixie can we move those assets?

**Comment by jakobr-google** [comment]
Sounds like there's access to GitHub, so we could maybe host them there, instead?

We could also publish the package on pub. That'd just work with the existing mechanism, but I personally don't think it's a good idea to publish this kind of private package on pub -- especially since we don't have a namespace mechanism.

**Comment by Hixie** [comment]
There's legal implications to the storage of these assets.

**Comment by InMatrix** [comment]
Can we work out the legal implications? "Customer: Gold" asked about this in an email as well. This issue might make it harder for them to introduce Flutter to their colleagues.

**Comment by LiWenGu** [comment]
Although i can solve the problem through the VPN, but this makes getting started harder. **Not friendly to beginners**

**Comment by bagualing** [comment]
I also encountered the same problem. But I solved it by setting up git's proxy.
>git config --global http.proxy http://127.0.0.1:1880
>git config --global https.proxy http://127.0.0.1:1880

127.0.0.1:1880 is my proxy service's address & port.

**Comment by yy1300326388** [comment]
我是这样做的
**flutter_gallery/pubspec.yaml**
```java
flutter_gallery_assets:
   git:
  #   url: https://flutter.googlesource.com/gallery-assets
     url: https://github.com/yy1300326388/gallery-assets-china
````
改变 url 为`https://github.com/yy1300326388/gallery-assets-china`
我会持续更新，并且 commit id 不会变，直接同步的 [https://flutter.googlesource.com/gallery-assets/](https://flutter.googlesource.com/gallery-assets/)的

**Comment by FirePrayer** [comment]
@yy1300326388 用你给的那个地址,Gallery终于跑起来了

**Comment by yy1300326388** [comment]
@FirePrayer  用的好就行，我会持续更新，有更新了可以提醒我

**Comment by dengyiqian** [comment]
@yy1300326388 修改了url之后编译提示：
Git error. Command: git rev-list --max-count=1 43590e625ab1b07f6a5809287ce16f7e61d9e165
fatal: bad object 43590e625ab1b07f6a5809287ce16f7e61d9e165

**Comment by yy1300326388** [comment]
@dengyiqian  把你的修改贴出来

**Comment by dengyiqian** [comment]
@yy1300326388
flutter_gallery_assets:
    git:
      url: https://github.com/yy1300326388/gallery-assets-china
      ref: 43590e625ab1b07f6a5809287ce16f7e61d9e165

**Comment by yy1300326388** [comment]
@dengyiqian  这个看起来是Git 的错误，但是我建议你先做这样一个操作，先把flutter_gallery 切换到dev 分支的v0.4.0版本，然后跑一下试试。最新的版本我也是跑步起来的。

**Comment by dhc5251** [comment]
> Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

FormatException: FormatException: Bad UTF-8 encoding 0x3f (at offset 237)

```
#0      _Utf8Decoder.convert (dart:convert/utf.dart:490)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:345)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#5      _rootRunUnary (dart:async/zone.dart:1134)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#10     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#11     _StreamController._add (dart:async/stream_controller.dart:639)
#12     _StreamController.add (dart:async/stream_controller.dart:585)
#13     _Socket._onData (dart:io-patch/socket_patch.dart:1672)
#14     _rootRunUnary (dart:async/zone.dart:1138)
#15     _CustomZone.runUnary (dart:async/zone.dart:1031)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#19     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#20     _StreamController._add (dart:async/stream_controller.dart:639)
#21     _StreamController.add (dart:async/stream_controller.dart:585)
#22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1245)
#23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:797)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#26     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.14393], locale zh-CN)
    • Flutter version 0.5.1 at D:\flutter
    • Framework revision c7ea3ca377 (10 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at D:\Android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: D:\Programs\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at D:\Programs\Android Studio
    • Flutter plugin version 27.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at D:\Programs\Jetbrains\ideaIC
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected devices (1 available)
    • MI 5X • 8e72de860804 • android-arm64 • Android 7.1.2 (API 25)

! Doctor found issues in 1 category.
```

**Comment by accwill** [comment]
@yy1300326388 干的漂亮。bug I solve the way of the problem, the same as @bagualing

**Comment by InMatrix** [comment]
@mit-mit Did we already resolve this issue with the new Gallery assets?

**Comment by InMatrix** [comment]
Since it's on pub, it should work with the CN mirror site. I'm closing this issue, but feel free to reopen if anyone still runs into problems.
