### ISSUE TITLE
Improved explanation of scopes for google_sign_in would be useful

### ISSUE THREAD

**Issue by jmnyv** [flutter/flutter#13761]
The documentation and code example for google_sign_in list two possible scopes, but there is no mention of an exhaustive list of possible scopes. The second scope below is listed on "https://developers.google.com/identity/protocols/googlescopes", under the "Google People API, v1", but the scope "email" is not listed at all on that page.

> scopes: [
>     'email',
>     'https://www.googleapis.com/auth/contacts.readonly',
>   ]

**Comment by Hixie** [comment]
cc @mravn-google
