### ISSUE TITLE
Firebase Storage plugin does not allow to set metadata and set wrong content-type

### ISSUE THREAD

**Issue by FastNinja** [flutter/flutter#13760]
Firebase Storage Plugin is very basic - when uploading the file it does not allow to set metadata.
This results in Firebase Storage trying to guess content-type and in my case it misses 50% of the time.
I.e. I am uploading images and half of them are having wrong content type.

This is from Firebase Storage doco:

>  Cloud Storage automatically infers the content type from the file extension where the file is stored on disk, but if you specify a contentType in the metadata it will override the auto-detected type. If no contentType metadata is specified and the file doesn't have a file extension, Cloud Storage defaults to the type application/octet-stream.

I am happy to do a Pull request that will enhance Firebase Storage Plugin. I can try to mimic official Firebase API - so metadata can passed in the put method (this is a Swift example)

```swift
// Create storage reference
let mountainsRef = storageRef.child("images/mountains.jpg")

// Create file metadata including the content type
let metadata = StorageMetadata()
metadata.contentType = "image/jpeg"

// Upload data and metadata
mountainsRef.putData(data, metadata: metadata)
```

**Comment by Hixie** [comment]
cc @collinjackson

**Comment by Hixie** [comment]
@FastNinja If you want to submit PRs please do! We absolutely accept contributions. Feel free to reach out to me (ian@hixie.ch) if you need anything.

**Comment by zoechi** [comment]
metadata might be fixed when flutter/plugins#553 lands

**Comment by zoechi** [comment]
Sorry for not coming back to this earlier.
I assume this issue is stale. Please let us know if you're still seeing this problem.

**Comment by theochampion** [comment]
@zoechi I'm having the same problem, even when uploading with a valid (.jpg) extension, the images appear on file storage as `application/octet-stream`

**Comment by kroikie** [comment]
@FastNinja

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/923. Any further collaboration will be done there.
