### ISSUE TITLE
Unable to use Flexible / Expanded on a DropdownMenu

### ISSUE THREAD

**Issue by KevinCCucumber** [flutter/flutter#137730]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a new Project
2. Add a Row or Column
3. Put the DropdownMenu in a Flexible Widget
4. The size of the menu is limited to a fixed size

### Expected results

The Dropdown menu takes up the available space

### Actual results

The Dropdownmenu stays fixed to a seemingly set maxwidth

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

const Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: darkBlue,
      ),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Row(children: [
      Expanded(child: 
         DropdownMenu(dropdownMenuEntries: [
            DropdownMenuEntry(
                value: 'Text1',
                label: 'Label1',),
            DropdownMenuEntry(
                value: 'Text2',
                label: 'Label2'),
          ]))
    ]);
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.0 23A344 darwin-arm64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.83.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @KevinCCucumber 
I see there's an open issue addressing the case you described https://github.com/flutter/flutter/issues/137514. You can try the solution provided at https://github.com/flutter/flutter/issues/137514#issuecomment-1784709841 to see if it can apply for your case.

Closing this issue as a duplicate, so please follow up on it for further updates.
