### ISSUE TITLE
When I called function 'Process.run()' app was shut down that only release app.

### ISSUE THREAD

**Issue by kwang87** [flutter/flutter#137746]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. macos app develop
2. install putty for mac
3.  run putty
4.debug mode is working
5. release mode is shutdown app.
* I try to try~catch exception log wrtie file with '_logger' , but I can't get it.

### Expected results

launch putty

### Actual results

macos flutter app shutdown

### Code sample

<details><summary>Code sample</summary>

```dart
 import "dart:io";
void run(){
String toolExecuteable = 'putty'
 List<String> params = makeToolParams();
 try {
final procResult = await Process.start( toolExecuteable, params);
...
}catch(e){
_logger.d(e.toString());
}
...
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by kwang87** [comment]
solved this problem 
Process.run('putty'); < only work debug mode
Process.run('/opt/local/bin/putty'); < debug,release work.

why?

**Comment by dam-ease** [comment]
Hi @kwang87. Thanks for filing this. From your reproduction steps, are you trying to launch `putty` from a macOS flutter app?
Also, per this https://github.com/flutter/flutter/issues/137746#issuecomment-1790207738, I understand that this solves the issue and works fine, is it fine to close this as solved or does this issue still persist?

**Comment by kwang87** [comment]
> Hi @kwang87. Thanks for filing this. From your reproduction steps, are you trying to launch `putty` from a macOS flutter app? Also, per this [#137746 (comment)](https://github.com/flutter/flutter/issues/137746#issuecomment-1790207738), I understand that this solves the issue and works fine, is it fine to close this as solved or does this issue still persist?

I solved the issue, but I'm curious why there is such a difference between debug and release.

**Comment by dam-ease** [comment]
Hello, thanks for your response. I think the expected behaviour is that the full PATH is added, can't say for sure but you can read up more on calling `Process.run()` in the docs here: https://api.flutter.dev/flutter/dart-io/Process-class.html.
Closing this as it has been solved as confirmed in last comment, if you disagree please comment and I'll reopen this. 
Thank you!
