### ISSUE TITLE
Build web base-href validation is wrong for git bash on windows

### ISSUE THREAD

**Issue by sebastianbuechler** [flutter/flutter#137700]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Build application for web with `flutter build web -t lib/main_web.dart --base-href=/Flutter/` while using git bash on Windows.

If escaping the slashes in the path with `//Flutter//` the build works, but obviously the `base-href` is then set to `//Flutter//`, so the check before the build seems to work wrongly here.

### Expected results

Builds a web version of the application with the correct `base-href` set.

### Actual results

`base-href should start and end with /`

### Code sample

Any application that supports web will do.

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.9, on Microsoft Windows [Version 10.0.22621.2428], locale de-CH)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.8)
[!] Android Studio (version 2021.2)
    X Unable to determine bundled Java version.
[√] Android Studio (version 2022.2)
[√] VS Code (version 1.83.1)
[√] Connected device (4 available)
[√] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment]
I can see this issue with Git Bash on Windows. It doesn't happen on Command Prompt or PowerShell. 

<details>
<summary>flutter doctor -v (stable & master)</summary>

```bash
[√] Flutter (Channel stable, 3.13.9, on Microsoft Windows [Version 10.0.19045.3570], locale en-US)
    • Flutter version 3.13.9 on channel stable at C:\WIP\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (7 hours ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\AndroidSDK
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = C:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio Electric Eel 2022.1.1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.4)
    • Visual Studio at D:\DOWNLOADWORK\VS2022
    • Visual Studio Community 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio Electric Eel 2022.1.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.83.1)
    • VS Code at C:\Users\ADMIN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.74.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.3570]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 118.0.5993.89
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 116.0.1938.62

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[√] Flutter (Channel master, 3.16.0-21.0.pre.42, on Microsoft Windows [Version 10.0.19045.3570], locale en-US)
    • Flutter version 3.16.0-21.0.pre.42 on channel master at C:\WIP\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f7d1b35dca (53 minutes ago), 2023-11-02 03:21:43 -0400
    • Engine revision 3c1e8f457e
    • Dart version 3.3.0 (build 3.3.0-87.0.dev)
    • DevTools version 2.29.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\AndroidSDK
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = C:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio Electric Eel 2022.1.1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.4)
    • Visual Studio at D:\DOWNLOADWORK\VS2022
    • Visual Studio Community 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio Electric Eel 2022.1.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.84.0)
    • VS Code at C:\Users\ADMIN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.74.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.3570]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 119.0.6045.105
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 116.0.1938.62

[√] Network resources
    • All expected network resources are available.

• No issues found!
```
</details>

**Comment by sebastianbuechler** [comment]
> I can see this issue with Git Bash on Windows. It doesn't happen on Command Prompt or PowerShell.
> 
> flutter doctor -v (stable & master)

Exactly. Any idea why?

**Comment by eliasyishak** [comment]
cc @andrewkolos

**Comment by andrewkolos** [comment]
If I recall correctly, Git For Windows/Git Bash runs commands in an MSYS environment, so it sounds like you are running into the automatic path conversion that MSYS will do[^1].

From an internet search, I found that this can be disabled by setting `MSYS_NO_PATHCONV`.

If you run the command as follows, it should work: `MSYS_NO_PATHCONV=1 flutter build web -t lib/main_web.dart --base-href=/flutter/`.

This is all to say that this is not an issue with `flutter`. However, your issue does point out something worth fixing. The error message you received is lacking. If it had displayed the argument value it received for `--base-href`, you would have been better able to figure this out yourself, so I'll work on improving that.

[^1]: https://www.msys2.org/docs/filesystem-paths/ (though this is MSYS2 documentation, not MSYS, it's close enough to introduce the topic)

**Comment by andrewkolos** [comment]
If you have `cygpath` available on your machine, you can run `cygpath -m /flutter/` to see what the path is getting converted to.

**Comment by sebastianbuechler** [comment]
> If I recall correctly, Git For Windows/Git Bash runs commands in an MSYS environment, so it sounds like you are running into the automatic path conversion that MSYS will do[1](#user-content-fn-1-e7b049ca15d1c629695c73f664c0b167).
> 
> From an internet search, I found that this can be disabled by setting `MSYS_NO_PATHCONV`.
> 
> If you run the command as follows, it should work: `MSYS_NO_PATHCONV=1 flutter build web -t lib/main_web.dart --base-href=/flutter/`.
> 
> This is all to say that this is not an issue with `flutter`. However, your issue does point out something worth fixing. The error message you received is lacking. If it had displayed the argument value it received for `--base-href`, you would have been better able to figure this out yourself, so I'll work on improving that.
> 
> ## Footnotes
> 1. https://www.msys2.org/docs/filesystem-paths/ (though this is MSYS2 documentation, not MSYS, it's close enough to introduce the topic) [↩](#user-content-fnref-1-e7b049ca15d1c629695c73f664c0b167)

The `MSYS_NO_PATHCONV=1` works for git bash on windows. But obviously, it will not work for cmd on windows, where the `flutter build web -t lib/main_web.dart --base-href=/flutter/` will also fail with `base-href should start and end with /`. 

I kind of agree that it's not really a flutter issue, but it makes the `--base-href` flag on windows systems barely useable. Instead of failing, wouldn't it be better to adjust the path with a leading and trailing slash, if none is present?

**Comment by sebastianbuechler** [comment]
> If you have `cygpath` available on your machine, you can run `cygpath -m /flutter/` to see what the path is getting converted to. On my machine for example, it gets converted to `C:/Program Files/Git/flutter/` (which doesn't exist :)).

Same result for me.
