### ISSUE TITLE
Add docstrings for FilterContents coverage functions

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#137703]
Symbols needing documentation:
- `impeller::FilterContents::GetFilterCoverage` 
- `impeller::FilterContents::GetFilterSourceCoverage`

I have no idea what a "FilterSource" is, is this `FilterInput`?

**Comment by flar** [comment]
They seem to follow a convention of "Get<Filter>ThingThatHasAPublicMethod", so "GetFilterCoverage" is the private internal method for doing "GetCoverage" and "GetFilterSourceCoverage" is the private internal method for "GetSouceCoverage". I'll add a one-line comment pointing to their public method.

**Comment by flar** [comment]
They could probably be named better as well. The public methods manage the operation over all of the inputs and the private methods just compute an answer for the object itself ignoring its inputs. Not sure how to encapsulate that in a name.

**Comment by gaaclarke** [comment]
@flar the problem I ran into is that I'm implementing a FilterContents.  So it's my job to implement those methods and I don't really know what they are supposed to do.  I'm having to backfill unit tests on existing filters to understand.
