### ISSUE TITLE
Keyboard on iOS when using dictation removes characters when you go back to keyboard

### ISSUE THREAD

**Issue by abbadabbatech** [flutter/flutter#13771]
## Steps to Reproduce

I am using a keyboard on iOS, when a user clicks the microphone to use dictation it successfully puts the text in my textinput field. However if the user needs to edit and clicks the keyboard on the dictation panel it pads the front of the text in the field with spaces and removes characters from the end of the line. Anyone seen this? Any ideas?

**Comment by xster** [comment]
cc @cbracken

**Comment by abbadabbatech** [comment]
Any progress on this or a workaround?  It is causing a delay in release of my app, so just wondering.

**Comment by abbadabbatech** [comment]
Just hoping to see if this is on the radar or has been seen by anyone else.

**Comment by gluix20** [comment]
Tested at v0.4.4 and has the above described behavior. It would be great have this solved for the release of my app too.

**Comment by cbracken** [comment]
Adding this to my backlog, but I've got a few other things on my plate first. That shouldn't stop anyone else who may be interested in submitting a patch to fix this if they're so inclined :) More than happy to review if someone else gets to it first.

**Comment by abbadabbatech** [comment]
Any update on this?  It is holding up a release as the app needs this for text input as users want it.

**Comment by abbadabbatech** [comment]
Does anyone know of a coding work around until a fix is done?

**Comment by douglascaurismo** [comment]
I tried a simple fix. But I am waiting for real fix.
var backup = "";
controller.addListener((){
  var r = RegExp(" {10}", multiline:true);
  if(r.hasMatch(controller.text)){
    controller.text = backup;
  } else {
    backup = controller.text;
  }
});

There are almost always a 10 white spaces chars that come from nowhere.

**Comment by matthewtsmith** [comment]
@wmleler @cbracken I've submitted a PR for this in the flutter/engine. https://github.com/flutter/engine/pull/6607

**Comment by jl-gogovapps** [comment]
I seem to still be experiencing this on Flutter 1.12.13+hotfix.8

If i say, "This is a test", the input field looks correct.  However, when tapping on the keyboard at the bottom of the Dictation panel, the input field is replaced with " this is a test "

Anyone have a thought here?  I don't think I'm doing anything special, but this is iOS 13.3.1, iPhone XR

Thanks!
