### ISSUE TITLE
image_picker Take picture with front and back camera at the same time

### ISSUE THREAD

**Issue by Sun3** [flutter/flutter#137718]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

There are many situations that need the ability to take pictures with the Front and Back cameras at the same time for iOS and Android. 

### Proposal

Take pictures with the Front and Back cameras at the same time.

**Comment by darshankawar** [comment]
@Sun3 I think your use case is similar to the one described here: https://github.com/flutter/flutter/issues/51928
Although it is for camera package, but the underlying support would probably remain same, so I suggest you to follow-up in it for further updates.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.

**Comment by Sun3** [comment]
Hi @darshankawar, I checked out that ticket and will follow it. I am hoping that this feature as a chance to be implemented, it's extremely needed.

Thank you.

**Comment by Sun3** [comment]
Hi @darshankawar, If the camera plugin receives this features, will the image_picker plugin also receive it? My applications use the image_picker to take photos, not the camera plugin.

I believe it's very important that the image_picker obtains this multi camera feature.

Thank you
