### ISSUE TITLE
Error executing simctl: -6 during flutter doctor

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#13779]
I got this error when running `flutter doctor`:

```
Error executing simctl: -6
dyld: Library not loaded: /Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/CoreSimulator
  Referenced from: /Applications/Xcode.app/Contents/Developer/usr/bin/simctl
  Reason: image not found
```

No idea why.

MacOS 10.13.2 on a 2012 MacBook Pro.

**Comment by Hixie** [comment]
This actually happens with almost all commands I run, including. `flutter run`.

**Comment by franzsilva** [comment]
What version of xcode is installed?, is it a full install or only the developer tools?

**Comment by Hixie** [comment]
I do not recall. I don't have that device anymore. Let's close until someone else hits this.

**Comment by xster** [comment]
It's the same as #13063
