### ISSUE TITLE
[go_router] Add ability use query parameters during redirection with go_router

### ISSUE THREAD

**Issue by Mounix99** [flutter/flutter#137721]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I need to pass "from" as a query to the route. After everything I needed will be done on that route I want to redirect back to the uri from route parameter. Now it doesn't work, but I'm pretty sure it was working like this before. For example here's the logs: 
```
[GoRouter] getting location for name: "verifyPhoneNumber", queryParameters: {from: /join/hoopit-746087/open/lukas-sitt-lag-385239/roles}
[GoRouter] redirecting to RouteMatchList(/join/verify)
```
And as you can see in the second line no info about query parameters has been passed. If I missing something, please let me know, but so far seem like unreasonable restriction

### Proposal

I propose add/return ability to pass query params to redirection callback

**Comment by chunhtai** [comment]
Is this related to https://github.com/flutter/flutter/issues/137513 ?

**Comment by Mounix99** [comment]
@chunhtai  I'm not 100% sure but this behaviour also presented in `12.0.0` so probably it is'n the same situation as in [#137513](https://github.com/flutter/flutter/issues/137513)  Here is the problem that during redirection all query params get lost

**Comment by Mounix99** [comment]
@chunhtai  any updates on this?

**Comment by chunhtai** [comment]
The pr is merged, can you double check if the latest version fixes the issue?

**Comment by Mounix99** [comment]
@chunhtai  Seems now work as expected, thanks!

**Comment by noskap** [comment]
#137513 didn't seem to fix it on my end :( 

Params completely disappear by the time the redirect function is called on app refresh

**Comment by Mounix99** [comment]
@noskap I have same problem, but it was because I was initializing my router inside build method so each time after refreshing, app was rebuilding it, could be the same situation in your case?

**Comment by chunhtai** [comment]
can you provide a repro?

**Comment by chunhtai** [comment]
Still waiting for repro
