### ISSUE TITLE
[google_maps_flutter] `ARC Semantic Issue (Xcode): No known class method for selector` on Xcode 15 and iOS 17

### ISSUE THREAD

**Issue by anggiedwarsa** [flutter/flutter#137756]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I just upgrade xcode due to Sonoma Update.

### Expected results

The app should run withour error.

### Actual results

Running Xcode build...                                                  
Xcode build done.                                           41.6s
Failed to build iOS app
Could not build the precompiled application for the device.
ARC Semantic Issue (Xcode): No known class method for selector 'mapIDWithIdentifier:'
/Users/admin/.pub-cache/hosted/pub.dev/google_maps_flutter_ios-2.3.2/ios/Classes/GoogleMapController.m:87:26

ARC Semantic Issue (Xcode): No known class method for selector 'mapWithFrame:mapID:camera:'
/Users/admin/.pub-cache/hosted/pub.dev/google_maps_flutter_ios-2.3.2/ios/Classes/GoogleMapController.m:92:26

Error launching application

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
Running Xcode build...                                                  
Xcode build done.                                           41.6s
Failed to build iOS app
Could not build the precompiled application for the device.
ARC Semantic Issue (Xcode): No known class method for selector 'mapIDWithIdentifier:'
/Users/admin/.pub-cache/hosted/pub.dev/google_maps_flutter_ios-2.3.2/ios/Classes/GoogleMapController.m:87:26


ARC Semantic Issue (Xcode): No known class method for selector 'mapWithFrame:mapID:camera:'
/Users/admin/.pub-cache/hosted/pub.dev/google_maps_flutter_ios-2.3.2/ios/Classes/GoogleMapController.m:92:26



Error launching application
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.5, on macOS 14.1 23B74 darwin-arm64, locale en-ID)
    • Flutter version 3.10.5 on channel stable at /Users/admin/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (5 months ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.83.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (4 available)
    • Anggi’s iPhone (mobile)    • 00008101-000D4C2E3E90801E            • ios            • iOS 17.1 21B74
    • iPhone 15 Pro Max (mobile) • DC5FCC56-E03C-45E1-A568-C84C4BB5AADF • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 14.1 23B74
      darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome
      118.0.5993.117

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by anggiedwarsa** [comment]
I found same issue posted, but no answer. https://stackoverflow.com/questions/77252998/arc-semantic-issue-xcode-no-known-class-method-for-selector-mapidwithidentif?noredirect=1&lq=1

**Comment by huycozy** [comment]
Looks like you are having this issue with maps plugin. Could you try running plugin [example](https://github.com/flutter/packages/tree/main/packages/google_maps_flutter/google_maps_flutter/example) to see if the issue still persists?

I ran it on iPhone 15, iOS 17 (simulator), macOS Sonoma but the issue didn't appear.

**Comment by anggiedwarsa** [comment]
> Looks like you are having this issue with maps plugin. Could you try running plugin [example](https://github.com/flutter/packages/tree/main/packages/google_maps_flutter/google_maps_flutter/example) to see if the issue still persists?
> 
> I ran it on iPhone 15, iOS 17 (simulator), macOS Sonoma but the issue didn't appear.

Yea. I can run it using example. So what happen to my project. This is my pod file.
`# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64 i386'

      # You can remove unused permissions here
      # for more infomation: https://github.com/BaseflowIT/flutter-permission-handler/blob/develop/permission_handler/ios/Classes/PermissionHandlerEnums.h
      # e.g. when you don't need camera permission, just add 'PERMISSION_CAMERA=0'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
      '$(inherited)',

      ## dart: PermissionGroup.calendar
      'PERMISSION_EVENTS=0',

      ## dart: PermissionGroup.reminders
      'PERMISSION_REMINDERS=0',

      ## dart: PermissionGroup.contacts
      'PERMISSION_CONTACTS=1',

      ## dart: PermissionGroup.camera
      'PERMISSION_CAMERA=1',

      ## dart: PermissionGroup.microphone
      'PERMISSION_MICROPHONE=0',

      ## dart: PermissionGroup.speech
      'PERMISSION_SPEECH_RECOGNIZER=0',

      ## dart: PermissionGroup.photos
      'PERMISSION_PHOTOS=1',

      ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
      'PERMISSION_LOCATION=1',

      ## dart: PermissionGroup.notification
      'PERMISSION_NOTIFICATIONS=1',

      ## dart: PermissionGroup.mediaLibrary
      'PERMISSION_MEDIA_LIBRARY=0',

      ## dart: PermissionGroup.sensors
      'PERMISSION_SENSORS=0',

      ## dart: PermissionGroup.bluetooth
      'PERMISSION_BLUETOOTH=0'
      ]
    end
  end
end
`

**Comment by huycozy** [comment]
Looking at your Podfile, it seems it's different at `build_configurations`. I also tried adding those configs but can't reproduce the issue. 
You should narrow down the issue by removing the usage of 3rd party plugins/packages one by one, unrelated/unaffected pages until find the page/setting that can cause the issue so that we have clear steps to reproduce this.

**Comment by anggiedwarsa** [comment]
Thanks for info. I fixed the issue by downgrade the google_maps_flutter_ios. Thank u.

**Comment by huycozy** [comment]
Which version do you downgrade to? If it is an issue with `google_maps_flutter_ios`, I think you should leave the issue open for further investigation.

**Comment by anggiedwarsa** [comment]
I downgraded to version 2.2.3

**Comment by huycozy** [comment]
Could you help to check if this issue only happens on iOS 17 devices? Also, please share the entire output of `flutter run -v` when the issue occurs, thanks!

**Comment by anggiedwarsa** [comment]
Yea. It's only happens on iOS17. I already provide entire output of flutter run -v here https://github.com/flutter/flutter/issues/137756#issue-1973786295

**Comment by huycozy** [comment]
The initial output log is the tailed log only. Do you use any firebase plugins in your project? We should narrow it down to see if the combination of using plugins causing this error.

**Comment by anggiedwarsa** [comment]
yes. I have firebase. Here's versions i used.
-   firebase_core: ^2.15.1
-   firebase_analytics: ^10.4.5
-   firebase_crashlytics: ^3.3.5
-   firebase_messaging: ^14.6.7

**Comment by huycozy** [comment]
Thanks. I see these versions are not the latest. Could you try updating them all and retry to see if the initial issue still occurs?

**Comment by Malik056** [comment]
It is hapenning in iOS 15 simulator too

**Comment by anggiedwarsa** [comment]
> Thanks. I see these versions are not the latest. Could you try updating them all and retry to see if the initial issue still occurs?

yea. still occurs even updated to the latest version

**Comment by huycozy** [comment]
I also tried adding those Firebase packages to a new project but still can't reproduce this issue; verifying on iPhone 15, iOS 17.0 emulator. Labeling the issue for other's input.

**Comment by cyanglaz** [comment]
The error means the API in GoogleMapSDK (not the google_map_flutter plugin, but the SDK that the plugin depends on)  `mapIDWithIdentifier` is not available. 

I think you might have gotten a unsupported version of GoogleMapSDK, could you share your Podfile.lock? You should see the actual GoogleMapsSDK your project resolves to. google_maps_flutter plugin locks the version to below 8.0 and it is tested to work with all the version below 8.0. I'm not sure why you could get a version that is not supported in the plugin.

**Comment by stuartmorgan** [comment]
One possibility here is that Xcode has become more strict about calling methods (even conditionally) when the method isn't declared anywhere. These are methods that exists only in some of the newer versions of the SDK.

**Comment by stuartmorgan** [comment]
Do you have any extra warnings or build flags set in your project? We'll need that information, or the full run log requested earlier, to be able to make progress here. I see what's likely happening here (the compiler doesn't know what the return type is for this unknown method, and so ARC isn't able to handle it correctly) but I haven't figured out why it's specific to some projects, or how to reproduce it locally in order to try a fix.
