### ISSUE TITLE
`flutter logs` doesn't print any acknowledgement when run

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1377]
This is what I see:

```
~/flutter/testme $ flutter logs

```

In this scenario, I have a single iOS simulator started. And I already ran `flutter start`.

Not sure if things are working, or there are no logs. Could we print something like "Connected, now streaming logs..." or an acknowledgement that A) the tool is connected to the device/simulator and that B) if there were logs, they would be streaming now.

Also, if there's an error, we should print that and exit.

Thanks!

**Comment by sethladd** [comment]
cc @chinmaygarde because this might be an iOS issue.

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/flutter/issues/869 https://github.com/flutter/flutter/issues/868 https://github.com/flutter/flutter/issues/360 appear to all be this bug. :)
