### ISSUE TITLE
`compileSdkVersion` is marked as deprecated

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#137742]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

`flutter create` generates a build.gradle with a `compileSdkVersion`, but Android Studio warns it's being deprecated, so the template should be updated.

### Proposal

Update the app/build.gradle template for new apps, with the migrations from the now depracated `compileSdkVersion`.

**Comment by danagbemava-nc** [comment]
Hi @feinstein, I believe this is a duplicate of https://github.com/flutter/flutter/issues/137621.

Closing this in favour of the issue linked above. 

If you disagree, kindly leave a comment below and I will reopen this. 

Thank you
