### ISSUE TITLE
Target debug_unpack_ios failed: Exception: Binary Runner-awrnqrokajwopwfmntfvyuaeruxs/Build/Products/Debug-iphoneos/Flutter.framework/Flutter does not contain . Running lipo -info:

### ISSUE THREAD

**Issue by nusminhtv** [flutter/flutter#137765]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

•  The simulator runs the app without any errors.

•  The problem only occurs on real devices, not on the simulator.

•  I tried logging out and deleting all the keychain access and account data, but the problem still persists.

### Expected results

No error

### Actual results

Target debug_unpack_ios failed: Exception: Binary /Users/mike/Library/Developer/Xcode/DerivedData/Runner-awrnqrokajwopwfmntfvyuaeruxs/Build/Products/Debug-iphoneos/Flutter.framework/Flutter does not contain . Running lipo -info:

### Code sample

<details>
<summary>Code sample</summary>

https://pastebin.com/raw/eR2zuJhE

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

<img width="1010" alt="Screenshot 2023-11-02 at 22 10 02" src="https://github.com/flutter/flutter/assets/135003722/acfa0935-f2eb-406d-9491-b1f84fcb15e6">

</details>

### Logs

https://pastebin.com/raw/eR2zuJhE

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.16.0-21.0.pre.21, on macOS 14.0 23A344 darwin-arm64, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.84.0)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @nusminhtv 
Please share the entire output of `flutter run -v` so that we have more information to verify this. Maybe similar to https://github.com/flutter/flutter/issues/135232 or https://github.com/flutter/flutter/issues/125130 (please take a look at EXCLUDED_ARCHS values)
