### ISSUE TITLE
[CP] fix clear color optimization for large subpasses

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#137732]
### Issue Link

https://github.com/flutter/flutter/issues/136507

### Commit Hash

d5ca128 

### Target

beta

### PR Link

https://github.com/flutter/engine/pull/47577

### Changelog Description

Fixes a case where the color would be dropped for subpass textures that were larger than the parent pass. This could be observed in the non-cached implementation of the Android zoom page transition.

### Impacted Users

Impeller / iOS users

### Impact Description

Color will disppear from certain surfaces based on sizing.

### Workaround

Disable impeller

### Risk

low

### Test Coverage

yes

### Validation Steps

Run attached unit tests

**Comment by itsjustkevin** [comment]
@zanderso could you take a look at this issue and the associated PR?

**Comment by zanderso** [comment]
CP LGTM
