### ISSUE TITLE
Cocoon dashboard icons became oddly sized on the morning of 11/1 PST

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#137705]
<img width="430" alt="Screenshot 2023-11-01 at 08 49 21" src="https://github.com/flutter/flutter/assets/6343103/1fc74dc9-b695-4bc8-9525-e2958360fde1">

**Comment by zanderso** [comment]
cc @CaseyHillers

**Comment by bdero** [comment]
Unintended side effect of https://github.com/flutter/cocoon/pull/3200?

**Comment by ricardoamador** [comment]
Not just the oddly size icons but if you click the square the highlighted part is tiny.
![image](https://github.com/flutter/flutter/assets/32242716/aaa93e08-74d2-4df8-88b2-e059243c69b9)

**Comment by ricardoamador** [comment]
Issue has been assigned but is not blocking anything. Removing from the ticket queue.

**Comment by CaseyHillers** [comment]
\cc @tvolkert

**Comment by tvolkert** [comment]
Yeah definitely https://github.com/flutter/cocoon/pull/3200.  I can have a look when I find some time - if anyone wants to have a look in the meantime, I'm happy to review a fix 🙂

**Comment by keyonghan** [comment]
Thanks for the fix @CaseyHillers . But seems the click pop up still bear the issue:
![Screenshot 2023-11-09 at 11 27 08 AM](https://github.com/flutter/flutter/assets/54558023/7d27ff2f-e199-45b9-9d4e-77f4c637f8cb)
