### ISSUE TITLE
web build: add a CLI option to allow force-flipping between JS and Wasm compiled output

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#137784]
Depends on https://github.com/flutter/flutter/issues/137724

Most apps should ONLY decide Wasm vs JS based on feature detection.

Make it possible, via an opt-in option, to allow app users to FORCE loading wasm vs JS based on a URL query param.

Goal: allow easy side-by-side evaluation of the two outputs from the SAME build without deploying twice. REALLY nice to verify performance and/or behavior differences!

CLI brainstorm: `--force-web-mode=[query param key]`

If `force-web-mode` is provided as `code-mode`, the value is used as the key in something like `myapp.com/?code-mode=js` or `myapp.com/?code-mode=wasm`

**Comment by kevmoo** [comment]
Or, per @eyebrowsoffire – maybe we just have a flag that can be put in `index.html` and passed to the initialization logic. Then this can be configured without rebuilding!

**Comment by yjbanov** [comment]
Maybe not the URL, since that would interfere with the app's URL strategy, but there are other ways probably.

**Comment by yjbanov** [comment]
For example, it could be a persistent flag in some local storage that can be set in the JS console.

**Comment by eyebrowsoffire** [comment]
I personally think we shouldn't directly implement this with the flutter tool. Perhaps in documentation we can provide a "recipe" for bootstrapping code that uses the URL parameters to change the user configuration, but I think currently we have all the customization points we should provide. I don't think we need a bespoke mechanism for this.
