### ISSUE TITLE
Request for Feature: Default Enabling of Accessibility Features in Flutter Web Applications

### ISSUE THREAD

**Issue by oaron** [flutter/flutter#137736]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I would like to request a feature for Flutter web applications that allows accessibility features to be enabled by default, without the need for user interaction. Currently, users are required to manually activate accessibility options, which can be inconvenient and create barriers for users with disabilities. Additionally, after enabling accessibility, the screen reader focus does not automatically shift to the entry point of the application, which further complicates navigation and usability for screen reader users.
I am seeking a solution that ensures accessibility is prioritized and automatically activated, providing a more inclusive and user-friendly experience right from the start. This feature would greatly enhance the usability of Flutter web applications for all users, regardless of their abilities, and ensure that the application is immediately accessible and navigable for users relying on screen readers.

### Proposal

I propose the implementation of a feature in Flutter for web applications that provides developers with the option to automatically enable accessibility features by default within their applications. This functionality would eliminate the need for manual activation by the user, creating a smoother and more inclusive user experience, particularly for individuals with disabilities.

**Comment by darshankawar** [comment]
Thanks for the report @oaron 
Can you take a look at https://docs.flutter.dev/ui/accessibility-and-internationalization/accessibility?tab=browsers#screen-readers and check if it helps to serve your use case or not ?
