### ISSUE TITLE
fullscreen_textfield_perf_ios__e2e_summary average frame rasterizer time is bimodal

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#137768]
It jumps between >15ms and <1ms. Does the benchmark not run over enough frames? Is this an artifact of the e2e summary harness?

https://flutter-flutter-perf.skia.org/e/?begin=1698766627&end=1698796465&keys=Xf8394802a664915d1b795484abb21a58&num_commits=50&request_type=1&xbaroffset=37729

**Comment by chinmaygarde** [comment]
This is related to backpressure from `AcquireNextDrawable`. The happens when the GPU workload is very close to the frame interval.

Should the benchmarks be measuring the acquisition time? Or just the time to generate a frame.

**Comment by chinmaygarde** [comment]
cc @zanderso for summarizing the findings.

**Comment by zanderso** [comment]
The number reported by the benchmark is bimodal because while the CPU time on the raster thread is short, the time spent on the GPU is near the frame budget. When the CPU+GPU time goes over budget, the raster thread stalls on the CPU waiting for a drawable, and this stall time begins to be included in the raster thread metric reported by the benchmark. When the CPU+GPU time stays consistently under budget, we get the low mode. When any frame's CPU+GPU time goes over budget, we get the high mode.

The solution is to measure the CPU and GPU time separately, and not include the GPU time (waiting for next drawable) in the raster thread CPU metric.

cc @jonahwilliams do we have an issue already filed for that to de-dup this against?

**Comment by jonahwilliams** [comment]
[Done: https://github.com/flutter/flutter/issues/new/](https://github.com/flutter/flutter/issues/138094)
