### ISSUE TITLE
`flutter build web` should produce a single build that automatically switches between wasm and JS if needed

### ISSUE THREAD

**Issue by eyebrowsoffire** [flutter/flutter#137724]
We should produce a single build that dynamically selects and bootstraps the proper wasm or JS application bundle depending on the user's preferences.

**Comment by amrgetment** [comment]
@eyebrowsoffire Is the JS application bundle will be HTML rendering or canvaskit? or I understand WASM wrong ?

**Comment by eyebrowsoffire** [comment]
> @eyebrowsoffire Is the JS application bundle will be HTML rendering or canvaskit? or I understand WASM wrong ?

It's a valid question. To clarify, when I'm talking about wasm, I am talking about what the dart code is compiled to (rather than auxiliary packages like CanvasKit which are wasm but compiled from C/C++ code). The combined build will have (by default) two variants:

* Dart code compiled to JavaScript (via dart2js) using the CanvasKit renderer
* Dart code compiled to wasm (via dart2wasm) using the Skwasm renderer.

The HTML renderer will not be supported (at least initially) for the combined build this issue describes.

**Comment by eyebrowsoffire** [comment]
Initial implementation of this has landed with https://github.com/flutter/flutter/pull/141396

**Comment by awvreenen95** [comment]
Can we please have the option to switch between the dual compile and compiling the JS / wasm seperately depending on which we choose? 

Having something as before with `flutter build web --wasm` to build the wasm only output, but then include `flutter build web --js` to build for javascript only, and then `flutter build web` does the single build with both.
