### ISSUE TITLE
Cocoon scheduler should reschedule presubmit tasks when base ref changes

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#137776]
See https://github.com/flutter/engine/pull/47598/checks?check_run_id=18299494890

This PR was originally on the master branch, then Cocoon swapped it to main. However, the tests were not rerun, which left it in a bad state.

**Comment by ricardoamador** [comment]
Why is cocoon swapping branches?

**Comment by ricardoamador** [comment]
Related: https://github.com/flutter/flutter/issues/135250

**Comment by ricardoamador** [comment]
Will take a look but removing from ticket queue.
