### ISSUE TITLE
[CP] Disable raster stats service protocol for Impeller.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#137733]
### Issue Link

flutter/flutter#136847

### Commit Hash

e2d006d 

### Target

beta

### PR Link

https://github.com/flutter/engine/pull/47578

### Changelog Description

Disable raster stats service protocol for Impeller.

### Impacted Users

Impeller Users

### Impact Description

Raster stats cannot be used without triggering crashing. Additionally, raster stats protocol was providing bad data and potentially misleading users.

### Workaround

Dont use raster stats service protocol.

### Risk

low

### Test Coverage

yes

### Validation Steps

Run attached unit test. Risk is low as this is only debugging functionality.

**Comment by itsjustkevin** [comment]
@zanderso could you take a look at this issue and the associated PR?

**Comment by zanderso** [comment]
CP LGTM
