### ISSUE TITLE
video_player size property

### ISSUE THREAD

**Issue by abbadabbatech** [flutter/flutter#13776]
## Steps to Reproduce

I am trying to use the new version and access the size property, but no matter what video I choose, the controller always shows a null size property.  Is there something special that needs to be done to get the size property to populate?  I have tried from iphone on .mov and .mp4 videos and its always null.  I confirmed I am using the correct version and size is available but just comes back null.

Not sure if its a bug or missing details on how to populate.

**Comment by abbadabbatech** [comment]
Needed to wait for the video to be initialized, not always working, but better then before.  This feature still does not help with video orientation, thought it would but it still produces wrong even though the video views properly in native viewer on iphone.  I will close this one and open another related to orientation.

**Comment by Hixie** [comment]
cc @mit-mit @mravn-google

**Comment by mravn-google** [comment]
cc @sigurdm

**Comment by sigurdm** [comment]
Yes - it should be documented that the size property is only populated after a call to ```initialize()```.

**Comment by abbadabbatech** [comment]
Also need to wait for video to be fully initialized.

**Comment by sigurdm** [comment]
Yep
