### ISSUE TITLE
[Impeller] Depth/Stencil changes for improved rendering performance of complex geometry.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#137714]
Now that we've resolved clip storage via stencil record/replay, we're unblocked on some new features in Impeller. This issue aggregates several other issues into a single arc of work.

1. (issue Not Filled) Add new contents that support clipping via depth buffer. This doesn't need to be wired up anywhere besides testing.
   * Related: https://github.com/flutter/flutter/issues/138460
3. (Issue Not Filled) Ensure backends support having both depth and stencil buffer attached, including when a combined depth-stencil is used.
   * Related: https://github.com/flutter/flutter/issues/137108
4. Add new Geometry methods that describe the appropriate rendering technique (StC or not). Add functionality to color source contents to conditionally use stencil techniques. This may require some design work.
   * Prototype: https://github.com/flutter/engine/pull/46442 . Note this one uses a technique that only works for nonZero, but the other fill modes can be implemented by following the instructions in the issue linked below.
   * https://github.com/flutter/flutter/issues/123671 
5. Evaluate performance and switch all clipping to use depth and enable StC.
6. Revisit polyline generation in Compute and potentially simplify by eagerly converting cubics to quadradics. There are some tessellation benchmarks that would be appropriate for this.

Cleanups:

If we're able to use StC everywhere (which we should be able to do), then we can consider removing libtess2. This would also remove the benefit for vector_graphics to perform pre-tessellation.

Notes:
*  We may determine that StC is slower than Triangulate and draw in some cases where the path is known to be static
* We should never use StC with convex shapes.

**Comment by bdero** [comment]
StC was enabled with https://github.com/flutter/engine/pull/51219
