### ISSUE TITLE
crash error loop when inizializing the flutter SDK. Error: Unable to create dart snapshot for flutter tool.

### ISSUE THREAD

**Issue by GIOTUBA** [flutter/flutter#137739]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

In VS code when i open a flutter project there is this error message going on forever. I tried uninstalling both flutter and vscode and reinstalling them but it doesn't work. I didn't found anything on the web.

### Actual results

![Screenshot (74)](https://github.com/flutter/flutter/assets/130096726/f9c89c4c-482d-4f6e-a150-2795a5cdf770).

```console
Building flutter tool... 
Running pub upgrade... 
Resolving dependencies...
Got dependencies.

===== CRASH =====
ExceptionCode=-1073741819, ExceptionFlags=0, ExceptionAddress=00000267CB733000
version=3.1.5 (stable) (Tue Oct 24 04:57:17 2023 +0000) on "windows_x64"
pid=5408, thread=9612, isolate_group=kernel-service(00000267C8A144E0), isolate=kernel-service(00000267C8A0F120)
os=windows, arch=x64, comp=no, sim=no
isolate_instructions=267cade0000, vm_instructions=7ff6330f6cb0
fp=cfd53ff2a0, sp=cfd53ff270, pc=267cb733000
  pc 0x00000267cb733000 fp 0x000000cfd53ff2a0 Unknown symbol
  pc 0x00000267c6f02bdf fp 0x000000cfd53ff3c0 Unknown symbol
-- End of DumpStackTrace
Error: Unable to create dart snapshot for flutter tool. 
```

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.9, on Microsoft Windows [Versione 10.0.22621.2428], locale it-IT)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.6)
[√] Android Studio (version 2022.1)
[√] VS Code (version 1.84.0)
[√] Connected device (3 available)
[√] Network resources

• No issues found!

**Comment by huycozy** [comment]
Hi @GIOTUBA, please check [this](https://github.com/flutter/flutter/issues/114763#issuecomment-1305199680) to see if it can solve your issue.
