### ISSUE TITLE
No apparent way to specify which iOS device/simulator to run on

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1378]
`flutter --help` shows me `--android-device-id    Serial number of the target Android device.` and I can't seem to find a way to specify which iOS device/simulator to run on.

Should we introduce a more general `--device-id` that takes IDs as listed from `flutter list` ?

**Comment by devoncarew** [comment]
This is fixed now - we have a `--device-id` (or `-d)` flag.

```
flutter -d B0484E69-8A54-4CCF-8804-4780BD7D5DD4 start
```
