### ISSUE TITLE
Proposal to have unified naming standard while parameter naming

### ISSUE THREAD

**Issue by Nekobaex** [flutter/flutter#137885]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Why can TextStyle omit text, but TextAlign cannot?
There are many similar places, which often confuse me.
<img width="331" alt="c5e07804b3bab16bde7b43477babbcb1" src="https://github.com/flutter/flutter/assets/89440464/5dd17c4c-c5df-4d00-a9c8-d4d117b4e17e">

### Proposal

I hope to have a unified naming standard.

**Comment by iapicca** [comment]
I also find that sometimes parameter naming is inconsistent

**Comment by goderbauer** [comment]
I agree that there are some naming inconsistencies. But it would be a major breaking change to fix some of these now and we have no plans to do this. This could be added to the list in #24722, though.
