### ISSUE TITLE
Correct the first observation in Step 6 of the Codelab on 'Building a Cupertino app with Flutter' page

### ISSUE THREAD

**Issue by vietstone-ng** [flutter/flutter#137888]
### Page URL

https://codelabs.developers.google.com/codelabs/flutter-cupertino#5

### Describe the problem

In step  _**6. List products for sale**_, the first _**Observations**_ is wrong.
It should describe `ProductRowItem` as a `StatelessWidget`, and the layout.
Currently, it describe `CupertinoSliverNavigationBar` and `Stateful Hot Reload`describes

### Expected fix

Describe the correct information.

**Comment by Piinks** [comment]
It looks like this codelab does not exist anymore. Can this then be closed?
