### ISSUE TITLE
App Crash: unknown Fatal Unhandled Segfault

### ISSUE THREAD

**Issue by MobIS1User** [flutter/flutter#137851]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

None that we know of.
We get the following issue reported to us via Sentry on occasion:
https://hunter-industries-mz.sentry.io/share/issue/d27c32bd6e4c40d19f0802d95ebe85c1/

### Expected results

No app crash

### Actual results

App Crash

### Code sample

n/a

### Screenshots or Video

n/a

### Logs

https://hunter-industries-mz.sentry.io/share/issue/d27c32bd6e4c40d19f0802d95ebe85c1/

### Flutter Doctor output

C:\git\mob> flutter doctor                    
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.6, on Microsoft Windows [Version 10.0.19045.3570], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Enterprise 2022 17.6.4)
[√] Android Studio (version 2022.3)
[√] VS Code, 64-bit edition (version 1.83.1)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
C:\git\mob>

**Comment by darshankawar** [comment]
@MobIS1User 
Looking at the log, it seems to be mostly coming from native SDK. So there's very little info to properly address the issue. If you could provide more details like, a pattern or any other logs would help to properly investigate this issue.
