### ISSUE TITLE
flutter_lints missing v3.0.0 tag

### ISSUE THREAD

**Issue by StephenWithPH** [flutter/flutter#137856]
### Is there an existing issue for this?

- [X] I have searched the [existing package issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Apackage)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### What package does this bug report belong to?

flutter_lints

### What target platforms are you seeing this bug on?

Android, iOS, Web, macOS, Linux, Windows

### Have you already upgraded your packages?

Yes

### Steps to reproduce

1. Go to https://github.com/flutter/packages.
1. Search for all tags `flutter_lints`
1. See that there's no `v3.0.0` tag

### Expected results

 There's a `v3.0.0` tag.

### Actual results

There's no `v3.0.0` tag

### Code sample

n/a

### Screenshots or Videos

<details>
<summary>Screenshots / Video demonstration</summary>

<img width="489" alt="Screenshot 2023-11-03 at 10 09 44 AM" src="https://github.com/flutter/flutter/assets/2990492/f423643b-1564-425c-89f7-acfd3cf4a130">

</details>

### Logs

<details><summary>Logs</summary>

```console
not applicable
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
not applicable
```

</details>

**Comment by stuartmorgan** [comment]
@devoncarew Did you release 3.0.0 manually? I see that the `release` step for that commit failed, and yet it's published.

**Comment by stuartmorgan** [comment]
I'm not sure what happened there, but I've tagged it manually.

**Comment by devoncarew** [comment]
> @devoncarew Did you release 3.0.0 manually? I see that the `release` step for that commit failed, and yet it's published.

I didn't - I believe I just followed the regular land-a-well-formed-PR process.

**Comment by stuartmorgan** [comment]
Weird, the first run failed with:

> Uploading...
>
> Version 3.0.0 of package flutter_lints already exists.
>
> Publishing flutter_lints failed.

But I just found the email notification, and it was uploaded by the role account. Maybe pub.dev gave us the wrong response, and that was actually a successful publish. 🤷🏻

**Comment by StephenWithPH** [comment]
It seems you might have an off-by-one behavior somewhere in your build system. There's a `3.0.1` release on pub.dev whose timing closely aligns with the manual workaround discussed above.

<img width="722" alt="Screenshot 2023-11-06 at 7 04 19 PM" src="https://github.com/flutter/flutter/assets/2990492/8ddc0e4b-cb53-4f2c-9d97-c394c9041b7b">

Meanwhile, there's no `v3.0.1` tag in GitHub:

<img width="344" alt="Screenshot 2023-11-06 at 7 05 03 PM" src="https://github.com/flutter/flutter/assets/2990492/96423b01-2a35-4ef6-816c-2b0ec9750863">

**Comment by StephenWithPH** [comment]
Got it. I was speculating that the `3.0.1` on pub.dev might have been triggered by some behind-the-scenes automation related to manually tagging.

Regardless, I see that there's now a `3.0.1` tag in GitHub as well.
