### ISSUE TITLE
Flutter Widget disappears

### ISSUE THREAD

**Issue by veereshkanavalli** [flutter/flutter#13786]
We upgraded to latest flutter on 26 DEC 2017 along with Gradle 4.1. 
Earlier both were 40 days old versions on which we were building the code.
All the controls were working fine on all handsets.

After upgrade, on Mi4i the widgets started disappearing and those continued to work on other phones.

Then started to remove component by component from the screen and checked where it started disappearing.

Finally we changed the widget structure to (earlier it was ListView)
SingleScrollableView
	Column
	rest of the controls like Text, List, Row, etc

Then it started working fine on Mi4i. 

**We still see issue with Stepper with Column**

Really not sure the cause of the issue. 
Anyone faced this issue ?
=================================
Flutter doctor output as below

[✓] Flutter (on Mac OS X 10.13.2 17C88, locale en-IN, channel alpha)
    • Flutter at /Users/aditya/flutter/flutter
    • Framework revision 8f65fec5f5 (2 weeks ago), 2017-12-12 09:50:14 -0800
    • Engine revision edaecdc8b8
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.d8ae797298c3a6cf8dc9f4558707bd2672224d3e

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/aditya/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.2.6)
    • Flutter plugin version 19.1
    • Dart plugin version 172.4343.25

[✓] Connected devices
    • Mi 4i • 12acd8ff • android-arm • Android 5.0.2 (API 21)

**Comment by goderbauer** [comment]
Can you please provide some sample code that illustrates the issue?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
