### ISSUE TITLE
[camera] Allow disabling orientation change callback

### ISSUE THREAD

**Issue by MrCube72** [flutter/flutter#137838]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Hi,
Please make a new switch int this component, to able to turn on/off the listening "onDeviceOrientationChanged"

camera_controller.dart 301

```dart
_deviceOrientationSubscription = CameraPlatform.instance
          .onDeviceOrientationChanged()
          .listen((DeviceOrientationChangedEvent event) {
       //if (CameraPlatfotm.instance.listenToOrientationChange) {
        value = value.copyWith(
          deviceOrientation: event.orientation,
      //}
        );
      });
```
I think lot of people will like this ...
Thanks:

MrCube72

### Proposal

camera_controller.dart 301

```dart
_deviceOrientationSubscription = CameraPlatform.instance
          .onDeviceOrientationChanged()
          .listen((DeviceOrientationChangedEvent event) {
       //if (CameraPlatfotm.instance.listenToOrientationChange) {
        value = value.copyWith(
          deviceOrientation: event.orientation,
      //}
        );
      });
```

**Comment by stuartmorgan** [comment]
> ### Use case
> Hi, Please make a new switch int this component, to able to turn on/off the listening "onDeviceOrientationChanged"

This is the proposal rather than a use case. What's the use case for being able to disable this? It seems like clients could just ignore this callback (or not register for it) when they don't want to be informed of orientation cahnges.
