### ISSUE TITLE
ArcGIS Map

### ISSUE THREAD

**Issue by zhangChain** [flutter/flutter#137828]
Flutter :
the webMap in ios after touch a widget on top of the webview, then once drag the map ,the map will zoom in and out.
but the webMap in android has no such problem.  who encountered the same problem.

**Comment by huycozy** [comment]
Hi @zhangChain 
When opening an issue, please try to provide all information indicated in the template so that we can address this issue properly (See first-party packages issue template [here](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=9_first_party_packages.yml))

More specifically, please provide the information indicated below:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of `flutter doctor -v`
- Affected plugin version

**Comment by zhangChain** [comment]
hi@huycozy 
The code ran without any errors，webview_flutter version is 4.4.1.
here is html code:
`<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=0" />
		<title>
			Load a basic WebMap | Sample | ArcGIS Maps SDK for JavaScript 4.26
		</title>

		<style>
			html,
			body,
			#viewDiv {
				padding: 0;
				margin: 0;
				height: 100%;
				width: 100%;
			}
		</style>

		<link rel="stylesheet" href="https://js.arcgis.com/4.26/esri/themes/light/main.css" />

		<script src="https://js.arcgis.com/4.26/"></script>

		<script>
			require(["esri/views/MapView", "esri/WebMap","esri/widgets/Home"], (MapView, WebMap,Home) => {//
				const webmap = new WebMap({
					portalItem: {
						id: "29c2503d155e40c8a04b2b91b0e7dce9"
					}
				});
				const view = new MapView({
					map: webmap,
					container: "viewDiv",
					scale: 7500,
					constraints: {
						rotationEnabled: false,
						multipleSelectionEnabled: false,
					},
				});
				view.ui.remove("zoom");

			});
		</script>
	</head>

	<body>
		<div id="viewDiv"></div>
	</body>
</html>`

user webview_flutter code:
`class _MyHomePageState extends State<MyHomePage> {
  late final WebViewController _controller;

  @override
  void initState() {
    super.initState();
    _controller = WebViewController()
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setBackgroundColor(Colors.grey)
      ..loadFlutterAsset("assets/files/map_js.html");
  }

  @override
  Widget build(BuildContext context) {
    return Container(
        width: double.infinity,
        height: double.infinity,
        color: Colors.grey[350],
        child: Stack(
          alignment: Alignment.bottomCenter,
          children: [
            WebViewWidget(controller: _controller),
            Container(
              width: double.infinity,
              height: 60,
              color: Colors.red,
            )
          ],
        ));
  }
}
`

**Comment by zhangChain** [comment]
> Hi @zhangChain When opening an issue, please try to provide all information indicated in the template so that we can address this issue properly (See first-party packages issue template [here](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=9_first_party_packages.yml))
> 
> More specifically, please provide the information indicated below:
> 
> * A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
> * The output of `flutter doctor -v`
> * Affected plugin version

hi@huycozy
The code ran without any errors，webview_flutter version is 4.4.1.

after running,i draged the map well,but i touched bottom red widget,the map will zoom in and out.

here is html code:
`



<title>
Load a basic WebMap | Sample | ArcGIS Maps SDK for JavaScript 4.26
</title>

	<style>
		html,
		body,
		#viewDiv {
			padding: 0;
			margin: 0;
			height: 100%;
			width: 100%;
		}
	</style>

	<link rel="stylesheet" href="https://js.arcgis.com/4.26/esri/themes/light/main.css" />

	<script src="https://js.arcgis.com/4.26/"></script>

	<script>
		require(["esri/views/MapView", "esri/WebMap","esri/widgets/Home"], (MapView, WebMap,Home) => {//
			const webmap = new WebMap({
				portalItem: {
					id: "29c2503d155e40c8a04b2b91b0e7dce9"
				}
			});
			const view = new MapView({
				map: webmap,
				container: "viewDiv",
				scale: 7500,
				constraints: {
					rotationEnabled: false,
					multipleSelectionEnabled: false,
				},
			});
			view.ui.remove("zoom");

		});
	</script>
</head>

<body>
	<div id="viewDiv"></div>
</body>
`
user webview_flutter code:
`class _MyHomePageState extends State {
late final WebViewController _controller;

@OverRide
void initState() {
super.initState();
_controller = WebViewController()
..setJavaScriptMode(JavaScriptMode.unrestricted)
..setBackgroundColor(Colors.grey)
..loadFlutterAsset("assets/files/map_js.html");
}

@OverRide
Widget build(BuildContext context) {
return Container(
width: double.infinity,
height: double.infinity,
color: Colors.grey[350],
child: Stack(
alignment: Alignment.bottomCenter,
children: [
WebViewWidget(controller: _controller),
Container(
width: double.infinity,
height: 60,
color: Colors.red,
)
],
));
}
}
`

**Comment by huycozy** [comment]
Can you share the demo from your side? 

I completed you sample code as below but the map is not loaded, there is only a back screen:

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() async {
  runApp(
    MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: MyHomePage(),
    ),
  );
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late final WebViewController _controller;

  @override
  void initState() {
    super.initState();
    _controller = WebViewController()
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setBackgroundColor(Colors.grey)
      ..loadFlutterAsset("assets/files/map_js.html");
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      height: double.infinity,
      color: Colors.grey[350],
      child: Stack(
        alignment: Alignment.bottomCenter,
        children: [
          WebViewWidget(controller: _controller),
          Container(
            width: double.infinity,
            height: 60,
            color: Colors.red,
          ),
        ],
      ),
    );
  }
}

```
</details>

<details>
<summary>Demo (Android)</summary>

![Screenshot 2023-11-06 at 12 49 29](https://github.com/flutter/flutter/assets/104349824/e5b6baf9-802f-4764-bbff-e2060f42e840)
</details>
