### ISSUE TITLE
☂️ Migrate iOS embedder objective-c code to ARC (Auto Reference Counting)

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#137801]
Most of the files in [ios Embedder](https://github.com/flutter/engine/tree/main/shell/platform/darwin/ios) and some [shared darwin codes](https://github.com/flutter/engine/blob/main/shell/platform/darwin/common/BUILD.gn#L12) use MRC(Manual Reference Counting). 

Manual Reference Counting is easy to make memory management mistake with. Objecgtive-C with Manual Reference Counting is not pleasant to work with, often scaring away contributors. 

Migrate all the objective-C code to ARC will boosts Flutter's stability on iOS and making contributing to Flutter iOS embedder more efficient. 

This is an umbrella issue tracks all the work needs to be done to migrate the iOS embedder to ARC:

1. [x] [Temporarily enable Objective-C smart pointers (scoped_nsobject, scoped_block etc) to work with both ARC and MRC.](https://github.com/flutter/flutter/issues/137802)
3. [x] Migrate all Objective-C files to ARC.
4. [x] https://github.com/flutter/flutter/issues/155943
5. [x] Remove the support of Objective-C smart pointers

**Comment by chinmaygarde** [comment]
Is there a general issue for this that include macOS?

**Comment by cbracken** [comment]
Correct -- we're already building with ARC for macOS. I can't remember if the shared code in '//flutter/platform/darwin/common' is built with ARC enabled or not.

**Comment by cbracken** [comment]
To answer my own question, the common code is ARC-enabled.
https://github.com/flutter/engine/blob/cc925b0021330759e18960e1ccbd7e55dec3c375/shell/platform/darwin/common/BUILD.gn#L61-L63

**Comment by cbracken** [comment]
Just realised I hadn't updated this in a while. The entire codebase, other than impeller, is migrated to ARC. ScopedBlock, scoped_nsobject, scoped_nsprotocol, etc. have all been deleted. Once impeller is migrated, I'll close this issue.

**Comment by chinmaygarde** [comment]
Impeller [is and always has been ARC only](https://github.com/flutter/engine/blob/4693aa05e766fa4627ad912de4ba40142d6115c8/impeller/tools/component.gni#L46).

**Comment by cbracken** [comment]
Ah that's why I didn't spot it in the targets explicitly!

Well... in that case, I think we're done. Just one more patch.

**Comment by cbracken** [comment]
DONE!

**Comment by cbracken** [comment]
The entire Flutter codebase is now ARC!
