### ISSUE TITLE
[flutter_web_plugins] Error: Dart library 'dart:ui_web' is not available on this platform.

### ISSUE THREAD

**Issue by Patrick386** [flutter/flutter#137881]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

My app is being developed to support both web and mobile. When I develop for the web first and then run it on mobile, I encounter the following package error:
launching application on iPhone 14.

1. flutter run

### Expected results

To remove the '#' hash tag in a web browser, I used 'flutter_web_plugins'.

### Actual results

Error (Xcode): ../../flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:5:8: Error: Dart library 'dart:ui_web' is not available on this platform.

Could not build the application for the simulator.
Error launching application on iPhone 14.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<img width="1420" alt="스크린샷 2023-11-04 오후 12 58 55" src="https://github.com/flutter/flutter/assets/49754877/a0e185ac-42ce-4fda-9acc-e3c40973a4de">

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.9, on macOS 13.0 22A380 darwin-arm64 (Rosetta), locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.4)
[✓] VS Code (version 1.71.1)
[✓] VS Code (version 1.75.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

**Comment by darshankawar** [comment]
@Patrick386 
Check [this](https://github.com/flutter/flutter/issues/136035) and see if it helps to answer your issue or not.

**Comment by Patrick386** [comment]
> @Patrick386 Check [this](https://github.com/flutter/flutter/issues/136035) and see if it helps to answer your issue or not.

This is my mistake. I haven't been using the correct approach for Flutter multi-platform development. When running on mobile, I should have used it like this, but I didn't. I'll need to do more testing to see if there's another issue. Since all the code is already built for the web, I have to examine many screens. Thank you.

**Ex:**
```
import 'check_out_screen.dart'
  if(dart.library.html) 'check_out_screen_web.dart'; 
  if(dart.library.io) 'check_out_screen_mobile.dart'; 
```
