### ISSUE TITLE
API docs for Column and ListView should give hint for scrolling with flexible size

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#13789]
Sometimes you want a layout that uses spaceBetween to space out some widgets, but with a minimum height below which it scrolls if it overflows.

We should add an example to SingleChildScrollView, pointed to by Column and ListView, that does this. An easy structure to implement it is:

   LayoutBuilder -> SingleChildScrollView -> ConstrainedBox -> Padding -> Column

...where ConstrainedBox is constrained to min/max width same as layout builder constraints, min height set to layout builder constraints max height, and max height set to infinity. The column should either not have flexible children or be MainAxisSize.min.

**Comment by kf6gpe** [comment]
If I'm parsing the code at "Centering, spacing, or aligning fixed-height content" we now do this, but don't have cross references.

**Comment by Hixie** [comment]
yeah this is already done
