### ISSUE TITLE
Some tests on 3.13 stable run on any Mac version and may fail on macOS 13

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#137800]
Some tests on 3.13 stable run on any Mac version and may fail on macOS 13.

If `Linux linux_web_engine` or `Mac mac_clang_tidy` fail, you may need to make a CP to limit it to run on macOS 12. I've prepared a CP you can use if needed: https://github.com/flutter/flutter/issues/137852

**Comment by vashworth** [comment]
fyi @itsjustkevin, @CaseyHillers, @godofredoc

Also, please fyi anyone else you feel should know

**Comment by XilaiZhang** [comment]
From triage: does this reproduce on flutter-3.16-candidate.0? 3.13 has been deprecated and 3.16 is the new stable

**Comment by vashworth** [comment]
This only affects 3.13, I filed this issue so release team can be aware and there's notes on what to do in the off chance they need to build 3.13 in the future
