### ISSUE TITLE
kTouchSlop const needs to change from 18 to 64 for touches to feel responsive

### ISSUE THREAD

**Issue by jwinarske** [flutter/flutter#137962]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

using gestures on custom touch controller responsiveness is very sluggish.

### Expected results

touch gestures not be sluggish

### Actual results

`kTouchSlop` const needs to change from 18 to 64 for touches to feel responsive on our supplier touch screens.

https://github.com/flutter/flutter/blob/925f3eee66f14cd8d517cee745ee432982adcfbe/packages/flutter/lib/src/gestures/constants.dart#L61

We need a way to allow adjustment without having to fork the sdk.

### Code sample

NA

### Screenshots or Video

NA

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel main, 3.17.0-1.0.pre.44, on Fedora Linux 38 (Workstation Edition) 6.5.8-200.fc38.x86_64, locale en_US.UTF-8)
    • Flutter version 3.17.0-1.0.pre.44 on channel main at /mnt/raid10/workspace-automation/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 377e40e8e0 (8 hours ago), 2023-11-06 08:35:51 -0500
    • Engine revision 4f6ed31bd8
    • Dart version 3.3.0 (build 3.3.0-97.0.dev)
    • DevTools version 2.29.0

[✓] Linux toolchain - develop for Linux desktop
    • clang version 16.0.6 (Fedora 16.0.6-3.fc38)
    • cmake version 3.27.7
    • ninja version 1.11.1
    • pkg-config version 1.8.0

[✓] VS Code (version 1.84.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.76.0

[✓] Connected device (2 available)
    • Linux (desktop)            • linux              • linux-x64 • Fedora Linux 38 (Workstation Edition) 6.5.8-200.fc38.x86_64
    • Toyota homescreen (mobile) • desktop-homescreen • linux-x64 • homescreen x86_64

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by jonahwilliams** [comment]
This is configured on Android via DeviceGestureSettings / view.gestureSettings .

There is no API in the embedder to configure this, but by adding that in theory you could configure touch slop per device.

**Comment by jonahwilliams** [comment]
Also see: https://github.com/flutter/engine/blob/e4e3f1c4fd0ea4817a3b0bd0913bb3b5662b1312/shell/platform/android/io/flutter/embedding/android/FlutterView.java#L1518C5-L1518C20 for how it is configured on Android.

**Comment by jwinarske** [comment]
If you provide the gesture settings in dart code, it will successfully return the new touch slop if you ask for it on the build context. The problem is that there is a bunch of gesture logic built into the SDK that doesn't look at the value in those gesture settings at all. It just looks up `kTouchSlop`.  Which I think is the real issue.

**Comment by jwinarske** [comment]
This is with the built-in gesture detector.  If you write your own, then it's not a problem :)

**Comment by jonahwilliams** [comment]
Which gestures?

**Comment by jonahwilliams** [comment]
I would suggest something like a dart-define constant value, but it looks like there is no double.fromEnvironment constructor :(

**Comment by jwinarske** [comment]
Pretty much all of them, but the most noticeable issue is just tapping a button.  If you use the built in touch slop it's super hard to do it. the tap usually gets counted as canceled if it's a short tap.  If you change the touch slop it feels much better and touches register much more normally

**Comment by jwinarske** [comment]
There needs to be a `customer: toyota` tag

**Comment by jonahwilliams** [comment]
> If you provide the gesture settings in dart code, it will successfully return the new touch slop if you ask for it on the build context. 

Can you show me an example of how you are doing this?

**Comment by jwinarske** [comment]
Just like in the test cases:
https://github.com/flutter/engine/blob/e4e3f1c4fd0ea4817a3b0bd0913bb3b5662b1312/testing/dart/gesture_settings_test.dart#L11

**Comment by jwinarske** [comment]
If you query the returned values, they are as set.  I believe the issue is the values are not being used by all the gesture code in the SDK, instead some references `kTouchSlop`.

**Comment by jonahwilliams** [comment]
Most of the tap gestures are using GestureSettings retrieved from the MediaQuery. If you can providide a minimal repro I can take a look. I believe that you are right and some gesture detectors are ignoring this value, but I need some place to start here.

**Comment by jwinarske** [comment]
We're deliberating internally.  It's a challenge for a repro due to it not being of the shelf hardware, like a phone.

One approach might be a test case that confirms the override is correctly used.

**Comment by jonahwilliams** [comment]
I understand you can't share your code as is, but as it stands:

* We have a means to configure touch slop, its gesture settings.
* In your codebase, gesture settings isn't working correctly.

We definitely have tests that confirm gesture settings work correctly in general, but I can't say why its not working correctly in your example without some sort of hint, repro, stack trace, debugging info, something.

**Comment by jwinarske** [comment]
What about getting clues from a trace session?

We appreciate the willingness to help 👍

**Comment by darshankawar** [comment]
Labeling for further continued discussion and tracking.



> There needs to be a `customer: toyota` tag

Adding this now.

**Comment by jwinarske** [comment]
One thing I see is that the pointer update rate coming from the controller is very high.  To mitigate engine load I am coalescing the events. Trying some experiments on my side around how often to send batched pointer events.

What is the recommendation around how often to send pointer events for gestures to be at the sweet spot?  Coalesce pointer events to 1/2 frame rate, once per frame, or call once per event regardless of rate?

Then there is some correlation between Dart VM isolate load and external events.  Like sometime I may see grouped events come through the isolate.

I'm figuring this is more of a system dynamics issue, more than a SDK API issue.

**Comment by jonahwilliams** [comment]
@jwinarske what I need to know is which gesture detector is behaving like this and how you are configuring gesture settings. because like I mentioned, most have gesture settings overrides, so either we missed one and I need some help pinpointing it - or the way you are configuring gesture settings isn't working correctly.

**Comment by jwinarske** [comment]
@mraleph Is there a way to determine isolate queue high water marks in the system?  I'm looking at touch latency on a loaded system.  I'm finding some events (external calls made from Dart) that are outcome of Dart VM getting grouped together, as there is heavy isolate activity.  Which looks like a generic command queue running to completion; expected isolate behavior.  On a lightly loaded system this doesn't show up.  The classic solution to a problem like this is to have multiple queues, one handling the higher priority with a guaranteed minimum time quantum.  Are there trace event markers to quantify this pattern of loading?
