### ISSUE TITLE
The argument type 'dynamic Function(String?)?' can't be assigned to the parameter type 'String? Function(String?)?'.

### ISSUE THREAD

**Issue by Kerollosnagy12** [flutter/flutter#137971]
import 'package:flutter/material.dart';

typedef Validator = Function(String?);

class CustomForFeild extends StatelessWidget {
  String hint;
  TextInputType keyboardType;
  bool secureText;
  TextEditingController? controller;
  Validator? validator;
  CustomForFeild(
      {required this.hint,
      this.keyboardType = TextInputType.text,
      this.secureText = false,
      this.validator,
      this.controller});
  @override
  Widget build(BuildContext context) {
    return TextFormField(
      validator: validator,   /// error here
      keyboardType: keyboardType,
      controller: controller,
      obscureText: secureText,
      decoration: InputDecoration(
          labelText: hint, labelStyle: TextStyle(fontFamily: 'Poppins')),
    );
  }
}

**Comment by hussenIbrahim** [comment]
Validator must have return type 'String?'
`typedef Validator = String? Function(String?);`

**Comment by danagbemava-nc** [comment]
As pointed out above, the validator must have a String? return type. 

Closing this as an implementation issue.
