### ISSUE TITLE
CustomScrollView with SliverList: items shake when scrolling

### ISSUE THREAD

**Issue by reliance-engineer** [flutter/flutter#137940]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Created a testing app with an AppBar, a BottomNavigationBar and a CustomScrollView with SliverList of 10 elements.
The list element consist on a header row, an Image and a footer Row (like social network)

### Expected results

The list scroll is smoothy

### Actual results

The list items shake when scrolling making a very weird experience.

### Code sample

<details><summary>Code sample</summary>

Code can be found here: [Gist with code](https://gist.github.com/reliance-engineer/98834c9360603bccfb5d535fdd0cae56)

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/114175138/43f2b46c-d21b-439e-8fdf-cde378763980

</details>

### Logs

<details><summary>Logs</summary>

```console
NO LOGS...
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.9, on macOS 13.1 22C65 darwin-x64, locale en-DE)
    • Flutter version 3.13.9 on channel stable at /Users/charlie/fvm/versions/3.13.9
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (12 days ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/charlie/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.81.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone de Ernesto (mobile) • 00008110-000A40992146801E • ios            • iOS 16.6.1 20G81
    • macOS (desktop)            • macos                     • darwin-x64     • macOS 13.1 22C65 darwin-x64
    • Chrome (web)               • chrome                    • web-javascript • Google Chrome 119.0.6045.105

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @reliance-engineer 
I tried the code sample and ran on iOS 15.x device as I don't have 17 version yet, but it didn't show the image under each card as shown in your video. I observed below and the scrolling was smooth:


https://github.com/flutter/flutter/assets/67046386/8221507e-926e-44c5-bc4b-989aac5dcf8e

Also, since this you are seeing on iOS platform, can you check by disabling impeller to confirm if the reported behavior persists without it or not ? That way we could narrow down the behavior to rendering engine.
