### ISSUE TITLE
ActionChip constructor documentation does not match class documentation

### ISSUE THREAD

**Issue by JaspervanRiet** [flutter/flutter#137964]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I encountered this today while working on our Flutter app, and was confused for a minute at the behaviour I saw (aka not great dev ex). The `ActionChip` [constructor documentation](https://github.com/flutter/flutter/blob/925f3eee66f14cd8d517cee745ee432982adcfbe/packages/flutter/lib/src/material/action_chip.dart#L87) is clear:

```dart
  /// ...
  /// The [label], [onPressed], [autofocus], and [clipBehavior] arguments must
  /// not be null. ...
```

Got it, `onPressed` must be non-null. Yet the type of `onPressed` is `VoidCallback?` and the argument is not required in the constructor, nor is there a constructor assert. When you leave it out, the ActionChip has a very non-intuitive background color, which turns out to be the disabled state. [This is actually written about in the class documentation](https://api.flutter.dev/flutter/material/ActionChip-class.html):

```dart
/// ... For Material 3, a disabled state is supported for Action
/// chips and is specified with [onPressed] being null. For previous versions
/// of Material Design, it is recommended to remove the Action chip from
/// the interface entirely rather than display a disabled chip.
```

So it is allowed to be null. That makes the constructor documentation wrong.

### Proposal

The intention here seems to me that `onPressed` should always be set, unless the user desires a disabled state. Thus it would make sense to me to make the `onPressed` required in the constructor, that makes it intentional. Then, I'd suggest amending the constructor documentation to no longer say that `onPressed` should be non-null. Happy to make a PR.

**Comment by HansMuller** [comment]
Good point, sorry about the confusion.
