### ISSUE TITLE
Hot reload is not triggered when an imported file is modified on Android Studio

### ISSUE THREAD

**Issue by martinboue** [flutter/flutter#137916]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

# Issue
When extracting a widget in a separate file, hot reload is no longer triggered when updating the extracted widget.

# Context
Flutter version: 3.13.9
IDE: Android Studio v2022.3.1 Patch 2
OS: Windows 11
Target device: Android, OnePlus 7T, physical device
Android Studio settings : 'Languages & Frameworks > Flutter > Perform hot reload on save' is checked

# Steps to reproduce
1. Create a new Flutter project with Android Studio, leave all options to default
2. Update the `main.dart` file with the following code:

```dart
import 'package:flutter/material.dart';
import 'other.dart';

void main() {
  runApp(const App());
}

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: ProfileScreen(),
    );
  }
}
```
4. Create a new file `other.dart` with the following content:
```dart
import 'package:flutter/material.dart';

class ProfileScreen extends StatelessWidget {
  const ProfileScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Text("Try to change this text"),
    );
  }
}
``` 

5. Run the app
6. Change the text inside the ProfileScreen widget and save file => **It does NOT trigger hot reload**

# What I've tried without success
- Restarting computer
- Restarting Android Studio
- Invalidate Android Studio cache
- Flutter clean
- Manual Flutter Hot Reload and Flutter Hot Restart
- Building on a virtual device
- Import `other.dart` file with `import 'package:mypackage/other.dart';` instead of `import 'other.dart';`

### Expected results

Hot reload

### Actual results

Nothing happen. Hot reload is not triggered, no log in the console.

### Code sample

<details><summary>Doctor output</summary>

main.dart :

```dart
import 'package:flutter/material.dart';
import 'other.dart';

void main() {
  runApp(const App());
}

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: ProfileScreen(),
    );
  }
}
```

other.dart:

```dart
import 'package:flutter/material.dart';

class ProfileScreen extends StatelessWidget {
  const ProfileScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Text("Try to change this text"),
    );
  }
}
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.13.9, on Microsoft Windows [Version 10.0.22621.2428], locale fr-FR)
    • Flutter version 3.13.9 on channel stable at C:\Users\martb\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (11 days ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\martb\AppData\Local\Android\sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at:
      C:\Users\martb\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\223.8836.35.2231.10811636\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.5.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33627.172
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Users\martb\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\223.8836.35.2231.10811636    • Flutter plugin version 76.2.2
    • Dart plugin version 223.8977
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] Android Studio (version 4.2)
    • Android Studio at C:\Users\martb\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\202.7486908
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at C:\Users\martb\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\212.5284.40
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] IntelliJ IDEA Ultimate Edition (version 2022.2)
    • IntelliJ at C:\Users\martb\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\222.4167.29
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.81.1)
    • VS Code at C:\Users\martb\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • HD1900 (mobile)   • 20bd02be • android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.22621.2428]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 119.0.6045.105
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 119.0.2151.44

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by dam-ease** [comment]
Hello @martinboue. Thanks for filing this issue. I'm unable to reproduce this issue on my end both with Android Studio and Visual Studio Code. Hot Reload works fine and the text change is effected after the action. Is this peculiar to Android Studio on your end? Could you try this on Visual Studio Code to see if you can reproduce there as well?

**Comment by martinboue** [comment]
Thanks @dam-ease fort testing it out! For you information, I was able to reproduce the issue on a different computer with the latest version of Android Studio (2022.3.1 Patch 2).

**I wasn't able to reproduce the issue with Visual Studio Code**, so it seems to be Android Studio specific. Which Android Studio version did you use? I don't really want to switch to VS Code. Thanks

**Comment by martinboue** [comment]
I just did some more research and found out those issues on Flutter IntelliJ Plugin repo:
- https://github.com/flutter/flutter-intellij/issues/7063
- https://github.com/flutter/flutter-intellij/issues/7040
- https://github.com/flutter/flutter-intellij/issues/7027

**After doing downgrading Android Studio to 2022.2.1 and Flutter plugin to 76.0.1 it works fine on Android Studio!**
I guess we can close this issue as it seems to be a duplicate.

**Comment by mergederg** [comment]
I ran into this yesterday and was able to solve it as a lot of others did [here](https://github.com/flutter/flutter-intellij/issues/6996) by downgrading the flutter intellij plugin to 76.0.x.  The same project always hot reloaded all files under vscode, go guessing its something specific to `flutter-intellij`.

**Comment by maheshmnj** [comment]
Going forward any issues related to Flutter plugin for Android Studio should be filed in https://github.com/flutter/flutter-intellij
This issue seems related:  https://github.com/flutter/flutter-intellij/issues/7040

**Comment by jacob314** [comment]
Short term we should absolutely fix this issue. Longer term we should use this as motivation to move hot reload on save functionality out of the IDE plugin and into Flutter Tools. https://github.com/flutter/flutter/issues/82190

**Comment by reidbaker** [comment]
This looks related to https://github.com/flutter/flutter-intellij/issues/6996 which just had someone confirm that the latest version was fixed for them. Can you update and try again?

**Comment by martinboue** [comment]
> This looks related to https://github.com/flutter/flutter-intellij/issues/6996 which just had someone confirm that the latest version was fixed for them. Can you update and try again?

Tested and it works, thanks!

**Comment by jwren** [comment]
Thank you all for confirming.  If there is still a regression here, open a new issue and tag me to escalate.
