### ISSUE TITLE
Platform Channel documentation error

### ISSUE THREAD

**Issue by BenSower** [flutter/flutter#13799]
## Steps to Reproduce
In the docs this https://flutter.io/platform-channels/ page contains some java as well as some kotlin code.
The java code seems to be missing the 
`    
GeneratedPluginRegistrant.registerWith(this)
` call as well as the related import:
`import io.flutter.plugins.GeneratedPluginRegistrant
`
the kotlin example seems to be complete, though.

**Comment by Hixie** [comment]
cc @Sfshaza @mravn-google

**Comment by mravn-google** [comment]
Actually, it is the Kotlin code that is wrong. The sample does not use plugins, but instead wire up channels directly in the platform-specific parts of the app. I'll go fix.

**Comment by mravn-google** [comment]
https://github.com/flutter/website/pull/1041

**Comment by BenSower** [comment]
@mravn-google lgtm, I guess I'll close this ticket, once the travis build is working!

**Comment by Sfshaza** [comment]
Thanks, @mravn-google!
