### ISSUE TITLE
[Impeller] Partial Repaint for Vulkan.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#137978]
Two separate bugs:

* Wire up incremental present (https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_incremental_present.html )

This extension claims that the damage region provides are a _hint_ - but its not clear if that means that we are allowed to _only_ render in the dirty regions. If not, then we can't do part 2:

* Cull all elements outside of the dirty region.

We need to investigate CPU overhead, especially since there is a cost in diffing display lists. We should consider simplifying this if we're able to make blinking cursor significantly faster. We need to be concerned about the cost when partial repaint would be ineffective, like scrolling or page transitions.

**Comment by chinmaygarde** [comment]
I forget what the current state of the world is on partial repaint on Android. I thought we had disabled it.

**Comment by jonahwilliams** [comment]
we disabled it on GLES because it had seemingly much higher CPU cost to compute the damage rect, and there were numerous reported bugs with several android versions / driver issues.

I think we should probably not do this for Vulkan. Its going to be a massive pain.

**Comment by chinmaygarde** [comment]
The CPU costs should be identical. And if those were prohibitively high with OpenGL, they are going to be similar for Vulkan. I'm closing this as wont-fix.
