### ISSUE TITLE
Flutter web | Can't open external Deeplink working correct with some browser

### ISSUE THREAD

**Issue by Kimsoer** [flutter/flutter#137930]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Dear team, I use to implement it to open external deeplink for payment gateway, and I have some problem to open some browser and some device in flutter web . if I test on app it working fine. 

### Expected results

Open deeplink from flutter web 

### Actual results

Can't redirect to deeplink correctly

### Code sample

```dart

  Future<void> _launchInBrowser(Uri url) async {
    if (!await launchUrl(
      url,
      mode: LaunchMode.externalApplication,
    )) {
      throw Exception('Could not launch $url');
    }
  }
``` 

### Screenshots or Video

```dart

  Future<void> _launchInBrowser(Uri url) async {
    if (!await launchUrl(
      url,
      mode: LaunchMode.externalApplication,
    )) {
      throw Exception('Could not launch $url');
    }
  }
``` 

### Logs

No see any return error but not redirect correct way

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.9, on macOS 13.5 22G74 darwin-arm64, locale en-KH)
    • Flutter version 3.13.9 on channel stable at /Users/kimsoer/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (12 days ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

```

</details>

**Comment by darshankawar** [comment]
@Kimsoer 
I tried the [plugin example](https://github.com/flutter/packages/tree/main/packages/url_launcher/url_launcher/example) running on web and was able to launch the url in the browser properly:

<img width="749" alt="Screenshot 2023-11-07 at 11 55 06 AM" src="https://github.com/flutter/flutter/assets/67046386/762c0443-88f4-45b8-bf49-01a750e6236a">

Check the same and see if it helps to resolve your issue or not. If not, please provide relevant details as on which browser are you seeing the reported behavior.
