### ISSUE TITLE
[go_router] Clear StatefulShellRoute restoration cache

### ISSUE THREAD

**Issue by yustapps** [flutter/flutter#137909]
Hi,

I have a problem because I don't found the way to restore StatefulShellRoute cache. My problem is language loads with EasyLocalization and when user change the language, the pages that are save on indexed stack not reloads and language is previous.

Is some way to refresh this data? 

Thank you so much.

**Comment by darshankawar** [comment]
@yustapps 
Can you provide a complete minimal but runnable code sample that shows the actual behavior along with what's the expected behavior you are looking to achieve ?
