### ISSUE TITLE
env variable Path configuration for FlutterFire in windows

### ISSUE THREAD

**Issue by Cicr** [flutter/flutter#137966]
I was following the code lab. https://firebase.google.com/codelabs/firebase-get-to-know-flutter?hl=en#3

In the  Step 4, "Configure Firebase". it does not mention for windows users the need to app flutterfire to the env variable path. to work.

C:\Users\<YOUUSERNAME>\AppData\Local\Pub\Cache\bin

**Comment by darshankawar** [comment]
Maybe this is related to https://github.com/invertase/flutterfire_cli/issues/219

**Comment by Cicr** [comment]
It is more with the way the codelab guide the person following the instructions,

If there is a step like 

1- "Please run the following command in windows"-->dart pub global activate flutterfire_cli and then 
2-"Please run the following command in windows"--> flutterfire configure.

it is going to fail in windows, it should be:

1- "Please run the following command in windows"-->dart pub global activate flutterfire_cli and then 

--Remember to add the flutterfire  bin route to the PATH variable in windows in order for the command to work. Also, if you do not have nodejs installed yet, please install nodejs and run the npm install -g firebase-tools, because the flutterfire requires the official firebase cli.

2-"Please run the following command in windows"--> flutterfire configure.


for the sake of the codelab clarity. I find did more understandable to add a note to explain there are pre-requisites before just using flutterfire configure out of the box.

**Comment by ericwindmill** [comment]
This is fixed by https://github.com/invertase/flutterfire_cli/pull/229
