### ISSUE TITLE
[DropdownMenu] Able to disable horizontal scrolling for the selected menu

### ISSUE THREAD

**Issue by rivella50** [flutter/flutter#137985]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run the attached demo app
2. Horizontally scroll the text in the dropdown menu

### Expected results

I would like to have an option which disables horizontal scrolling of the text.
When i limit the width of the dropdown menu i am aware that menu item's labels can have a larger text and therefore are not fully visible.
At the moment it seems that the text is always scrollable when i drag it horizontally.
Since i have to horizontally scroll some DropdownMenu instances in a Row the scrolling of an overflowing text inside a menu at the same time is quite disturbing.

### Actual results

When horizontally dragging the overflowing text of a dropdown menu it is always scrolling.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

const Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: darkBlue,
      ),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: const BoxDecoration(
        color: Colors.lightGreen,
      ),
      child: DropdownMenu<String>(
        width: 150,
        initialSelection: 'test',
        dropdownMenuEntries:  const [
          DropdownMenuEntry<String>(
            value: 'test',
            label: 'my long test string which overflows',
          )
        ],
        onSelected: (value) => null,
        inputDecorationTheme: const InputDecorationTheme(
          isDense: true,
          contentPadding: EdgeInsets.all(7),
          constraints: BoxConstraints(
            maxHeight: 35,
          ),
        ),
      )
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/54292/1cc4b14a-6b92-4578-b808-661e421a39a0

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.13.6, on macOS 13.5.1 22G90 darwin-arm64, locale en-CH)
    • Flutter version 3.13.6 on channel stable at /Users/valley/fvm/versions/3.13.6
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.18.4/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/v/fvm/versions/3.13.6. Consider adding /Users/v/fvm/versions/3.13.6/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (6 weeks ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/v/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/v/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/v/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode-14.3.1.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 76.2.4
    • Dart plugin version 232.10072.19

[✓] VS Code (version 1.82.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.5.1 22G90 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 119.0.6045.105

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by huycozy** [comment]
Hi @rivella50 
It looks like your demo video is not presented for sample code. When I ran the sample code, the mouse cursor was in editing mode, and its behavior looked correct:

https://github.com/flutter/flutter/assets/104349824/2f9906c4-123a-4776-af59-052da1813a29

>I would like to have an option which disables horizontal scrolling of the text.

This is more like a proposal/feature request than a bug, I think. If it is, do you mean the text will be ellipsis, right?

**Comment by rivella50** [comment]
Hi @huycozy,
yes, the demo video is from my project, but the effect is the very same.
The text can be cutted by using ellipsis, yes.
Ok, it's more like a feature, you're right.

**Comment by huycozy** [comment]
For entries (DropdownMenuEntry), you can apply `TextOverflow.ellipsis` for its `labelWidget` (see https://github.com/flutter/flutter/pull/133491). 

But for the TextField inside DropdownMenu which is scrollable currently, this seems to be blocked by https://github.com/flutter/flutter/issues/61069 (`ability to change text overflow on the TextField`).

Keeping this issue as a feature request.

**Comment by rivella50** [comment]
Perhaps disabling scrolling could be solved without having to respect the mentioned ticket - that one is over 3 years old and it doesn't seem to have had much attention so far.
For the moment i switched to `DropdownButtonFormField`.

**Comment by QuncCccccc** [comment]
Hi @rivella50! I think we can use `ScrollConfiguration` to make a `DropdownMenu` stop scrolling🙂

Could you try:
```
ScrollConfiguration(
  behavior: ScrollConfiguration.of(context).copyWith(physics: const NeverScrollableScrollPhysics()),
  child: DropdownMenu(
    ...
  )
)
```

**Comment by rivella50** [comment]
@QuncCccccc That would actually work, yes. Thanks for the tip.

**Comment by QuncCccccc** [comment]
Glad to help!
