### ISSUE TITLE
[web] Implement minimum overlay optimization for CanvasKit

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#137953]
Implement [the minimum overlay optimization](https://docs.google.com/document/d/1aCIOEEYe31HqCaCGUKsAmUu9T0U6o2zUMGpqdPEdJoQ/edit?usp=sharing).

The [single GL context redesign](https://github.com/flutter/engine/pull/47241) allows creating virtually unlimited number of render surfaces, which allows setting the value of `canvasKitMaximumSurfaces` to a bigger number without running into the browser's WebGL context limit. However, the default overlay limit remains in place for now, since overlays still have impact on memory usage. To fix that, we should reduce the need for overlays.

**Comment by yjbanov** [comment]
This is fixed.

**Comment by harryterkelsen** [comment]
Fixed with https://github.com/flutter/engine/pull/47317
