### ISSUE TITLE
Integration of debbugging apps in Windows subsystem for Android.

### ISSUE THREAD

**Issue by CntrlX** [flutter/flutter#137905]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

The problem I ran into was that when I was developing with Flutter I was listening to music with a Flutter app called Blackhole in Windows subsystem for Android. When I started to run my Flutter debugging in Android Studio both the Android Studio emulator and the WSA started to glitch. It led me to this great idea where we could debug our Flutter app in WSA as it will also make it easier for beginners to set up in WSA rather than Android Studio.

### Proposal

I would want to develop and debug Flutter apps using Windows Subsystem for Android. Considering it is easier and much more efficient than Android Studio.

**Comment by CntrlX** [comment]
I know where to start on this issue

**Comment by huycozy** [comment]
>it will also make it easier for beginners to set up in WSA rather than Android Studio.

Could you be more specific on how it will be easier? As far as I understand this, you would like to develop and debug Flutter app in WSA. Is this similar to developing and debugging on Android OS?

**Comment by CntrlX** [comment]
With Android studio we have to install the studio and then install extra packages as needed but with WSA we just have to install the wsa file also WSA is very light on the pc compared to Android studio.

**Comment by CntrlX** [comment]
It's not just similar it's the same, consider WSA like an Android emulator which is built by windows which makes it that much faster.

**Comment by huycozy** [comment]
>WSA we just have to install the wsa file also WSA is very light on the pc compared to Android studio.

> consider WSA like an Android emulator

You are mentioning two different things. The first one is about considering WSA as an IDE, but the second one is about the target platform (Android). 

To make this more clear, can you confirm this [video ](https://www.youtube.com/watch?v=vKvtLRvvmRs) demonstrates what you are proposing?

**Comment by CntrlX** [comment]
Actually the video does what i need

**Comment by huycozy** [comment]
Thanks for your confirmation. Since the video provided a solution (use WSA as a target platform), I will close the issue from here.
