### ISSUE TITLE
Developers wish to inline a WebView

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#13790]
A tracking issue for this feature request, for voting and updates.

Use cases include:

* Rendering content created by a third-party CMS (often in HTML)

**Comment by sergiandreplace** [comment]
:+1:

**Comment by Rockvole** [comment]
Would also like to send html generated locally to the WebView.

**Comment by mit-mit** [comment]
@sethladd how is the present issue differnt from 730 ?

**Comment by sethladd** [comment]
Hm, now I'm not sure.

Closing as a dupe of https://github.com/flutter/flutter/issues/730
