### ISSUE TITLE
Update http docs with override details

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#13792]
https://github.com/flutter/website/pull/769 updated https://flutter.io/networking/ to not use the deprecated client override. Once lands, we should add details on how to do mocking of the client for test, etc.

**Comment by sethladd** [comment]
HttpOverrides.global have landed: https://github.com/dart-lang/sdk/blob/master/sdk/lib/_http/overrides.dart#L44

This would make it easier to override. Hope this helps!

(cc @zanderso )

**Comment by mit-mit** [comment]
I don't have bandwidth to do this personally; unassigning from self

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1846](https://github.com/flutter/website/issues/1846) via [**ZenHub**](https://www.zenhub.com/)
