### ISSUE TITLE
Text widget should have a constructor where you give a TextSpan

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#13791]
This would let people create const text widgets that are affected by the DefaultTextStyle.

**Comment by jonahwilliams** [comment]
Looking at the implementation for Text, it looks like it does lookup the DefaultTextStyle in the build method.  Or is this feature desirable regardless?

**Comment by Hixie** [comment]
This would be to let you write things like "hello *beautiful* world" where one word is italics and all the text inherits from the ambient DefaultTextStyle.
