### ISSUE TITLE
Issue In scroll behavior in latest Flutter release iOS 

### ISSUE THREAD

**Issue by ahmedshikashaker** [flutter/flutter#137989]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

<img width="1654" alt="Screenshot 2023-11-07 at 10 23 44 AM" src="https://github.com/flutter/flutter/assets/65731826/45c02931-c56b-4619-9695-030a4a272a4f">

a. Open the app and navigate to the screen with Listview or Scrollview containing TextFields and a sticky button.
b. Scroll down the screen.
c. Observe the appearance of white lines over the button, as shown in the attached screenshot.

### Expected results

When scrolling down the screen with Listview or Scrollview containing TextFields and a sticky button at the bottom, the application should exhibit smooth scrolling without any visual artifacts. There should be no lines or graphical glitches appearing over the button or any other UI elements. The scrolling action should be seamless and free from any distracting visual elements, ensuring a pleasant user experience.

### Actual results

<img src="https://github.com/flutter/flutter/assets/65731826/7b045288-8be1-4ca2-a114-e5f478144cd6" width="300"/>

Observe the appearance of white lines over the button, as shown in the attached screenshot.

### Code sample

<details><summary>Code sample</summary>

```dart
Column(
          children: [
            Expanded(
              child: SingleChildScrollView(
                controller: widget.scrollController,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    AppAlert.information(
                      content: context.shareRequestAmountScreenDepositInfoLabel,
                    ),
                    const AppGap.m(),
                    SectionHeader(
                      context.depositTo,
                      padding: const AppEdgeInsets.symmetric(
                        horizontal: AppGapSize.xs,
                      ),
                    ),
                    const AppGap.xxs(),
                    RequestMoneySelectAccountsWidget(
                        initialAccountNumber: widget.initialAccountNumber,
                        initialAccount: widget.initialAccount),
                    const AppGap.s(),
                    FocusAwareScrollerWidget(
                      scrollController: widget.scrollController,
                      child: const RequestMoneyAmountWidget(),
                    ),
                    const AppGap.s(),
                    const RequestMoneyDepositReasonWidget(),
                    const AppGap.s(),
                    const RequestMoneyDepositDescriptionWidget(),
                    const AppGap.m(),
                    AppPadding(
                      padding: const AppEdgeInsets.symmetric(
                          horizontal: AppGapSize.xs),
                      child: AppText.captionBold(
                          context
                              .shareRequestPayerScreenQuestionWhoIsTheRecipient,
                          color: AppTheme.of(context).colors.textBodySecondary),
                    ),
                    const AppGap.xxs(),
                    const PayerNameWidget(),
                    const AppGap.xs(),
                    const PayerLanguageItem(),
                    const AppGap.m(),
                  ],
                ),
              ),
            ),
            const ShareRequestButtonWidget(),
          ],
        )
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[[Video of The Issue]](https://drive.google.com/file/d/1wbyBdRjmI6kH5y4_4KCfHdrAYg9JQspq/view?usp=sharing)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.9, on macOS 13.4.1 22F770820d darwin-arm64, locale en-KW)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.84.0)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by danagbemava-nc** [comment]
Hi @ahmedshikashaker, the code sample you have provided is not complete. 

Please provide a complete minimal runnable code sample preferably without any third-party packages/plugins so that we can investigate this. If you could also share a video of the issue, that would be appreciated. 

PS: It would be best if the sample is a single main.dart file. It also does not have to be code from your project. Just the smallest code sample that reproduces the issue is fine. 

Thank you

**Comment by ahmedshikashaker** [comment]
@danagbemava-nc i found the issue,
the issue is in the button in clipBehavior: Clip.antiAliasWithSaveLayer,  in Material Widget like
Material(
      clipBehavior: Clip.antiAliasWithSaveLayer,
      color: Colors.transparent,
      
when i removed  clipBehavior or changing it to Clip.hardEdge  it works fine

**Comment by danagbemava-nc** [comment]
Hi @ahmedshikashaker, can you provide a complete minimal reproducible code sample so that we can investigate this? I don't think visual artefacts are expected regardless of the clip behaviour you use. 

Thank you
