### ISSUE TITLE
ContainerLayer#applyTransform's behavior does not match its document.

### ISSUE THREAD

**Issue by pinyin** [flutter/flutter#137923]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

At this moment, the comments on `applyTransform` of `ContainerLayer` says it would:
```
/// Applies the transform that would be applied when compositing the given
/// child to the given matrix.
///...
void applyTransform(Layer? child, Matrix4 transform) {
```
Some subclasses of `ContainerLayer`, such as an `OffsetLayer`, would work as expected: 
```
/// OffsetLayer#applyTransform
  void applyTransform(Layer? child, Matrix4 transform) {
    assert(child != null);
    transform.translate(offset.dx, offset.dy);
  }
```
The `offset` is updated instantly after a `paint` call sets its `offset` and before the next `addToScene`. This behavior seems to be consistent with the above comments.
While some other subclasses, such as a `TransformLayer`, would transform the passed parameter `transform` with one transform set in its previous `addToScene` call.
```
/// TransformLayer#applyTransform
  void applyTransform(Layer? child, Matrix4 transform) {
    assert(child != null);
    assert(_lastEffectiveTransform != null || this.transform != null);
    if (_lastEffectiveTransform == null) {
      transform.multiply(this.transform!);
    } else {
      transform.multiply(_lastEffectiveTransform!);
    }
  }

/// TransformLayer#addToScene
  @override
  void addToScene(ui.SceneBuilder builder) {
    assert(transform != null);
    _lastEffectiveTransform = transform;
    if (offset != Offset.zero) {
      _lastEffectiveTransform = Matrix4.translationValues(offset.dx, offset.dy, 0.0)
        ..multiply(_lastEffectiveTransform!);
    }
    engineLayer = builder.pushTransform(
      _lastEffectiveTransform!.storage,
      oldLayer: _engineLayer as ui.TransformEngineLayer?,
    );
    addChildrenToScene(builder);
    builder.pop();
  }
``` 
In this case, the `applyTransform` is not available before `addToScene`.
I don't know which behavior is intended, but there appears to be two difference logic in `applyTransform`, making it harder to decide `ContainerLayer`s' transforms before `addToScene`.

### Expected results

All `ContainerLayer`s `applyTransform` should apply the incoming transform in next `addToScene` (instead of the one from previous frame) to parameter.

### Actual results

Inconsistence behavior across subclasses.

### Code sample

Trying to call descendants' `applyTransforms` before `addToScene` with a matrix, the matrix would be applied with either the current (displaying) transform or the transform in next frame (adding to scene).
The later behavior would be more useful, in my humble opinion.

### Flutter Doctor output

Unrelated to flutter doctor, though it does make some use cases harder to implement.

**Comment by huycozy** [comment]
Hi @pinyin 
Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) to represent the case so that we may verify this. 

Also, please provide the output of `flutter doctor -v` as well (it gives us the Flutter version at the time the issue is filed, it will be useful to reconfirm the issue later)
