### ISSUE TITLE
Could not resolve all files for configuration ':classpath'.

### ISSUE THREAD

**Issue by nani-samireddy** [flutter/flutter#138026]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I don't know to reproduce i've just installed the flutter and android studio and everything.
When I wanted to run I'm getting the following error

- I have active internet connection and everything is working fine except this
please help me 
this is the log that came when i ran flutter run -v
[https://pastebin.com/PAwAbtwX]( https://pastebin.com/PAwAbtwX
)### Actual results

i ran the application using flutter run and I'm getting this
`
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:7.3.0.
     Required by:
         project :
      > Could not resolve com.android.tools.build:gradle:7.3.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/7.3.0/gradle-7.3.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/7.3.0/gradle-7.3.0.pom'.
               > The server may not support the client's requested TLS protocol versions: (TLSv1.2, TLSv1.3). You may need to configure the client to allow other protocols to be used. See: https://docs.gradle.org/7.5/userguide/build_environment.html#gradle_system_properties
                  > PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
[!] Gradle threw an error while downloading artifacts from the network.
`

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->
[https://pastebin.com/PAwAbtwX](https://pastebin.com/PAwAbtwX
)```

</details>


### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

samireddynani@Nanis-Macbook test % flutter doctor -v
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.0 23A344 darwin-arm64, locale en-IN)
    • Flutter version 3.13.9 on channel stable at /Users/samireddynani/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (13 days ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/samireddynani/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.84.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (3 available)
    • AIN065 (mobile) • e57c0a12 • android-arm64  • Android 13 (API 33)
    • macOS (desktop) • macos    • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 119.0.6045.105

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by darshankawar** [comment]
> PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

@nani-samireddy Looking at the logs and also above error, it could be related to gradle + android studio configuration and may not be specific to Flutter itself.
Check https://stackoverflow.com/questions/26697118/android-studio-unable-to-find-valid-certification-path-to-requested-target and see if it helps in your case or not.

Closing from here, as this doesn't look like a bug in flutter framework. If you disagree, write in comments and I'll reopen it.
