### ISSUE TITLE
Flutter Engine performance tracing on Fuchsia, including Vulkan

### ISSUE THREAD

**Issue by schwa423** [flutter/flutter#13803]
The Flutter Engine should add support for performance tracing using the macros in //zircon/system/ulib/trace/include/trace/event.h (#include <trace/event.h>).

It would be useful to see both CPU and GPU time consumed by render tasks.  The CPU time is easily measured by using the various trace macros.

GPU time is a bit more involved, and it might require changes to Skia (if so, please file a bug against them, copying the appropriate info from here).  The basic idea is to: 
1) use Vulkan APIs to write timestamp events into a query pool
2) when the frame is finished, retrieve those events and add them to the system trace log.

The timestamps received from the query pool are not in the same timebase as the trace log, so the times need to be transformed appropriately.  An example of how to do this can be found in Escher; here's an overview:

First, since the Vulkan events are in a GPU/driver-dependent timebase; the escher::TimestampProfiler class retrieves the query results and transforms them into a vector of TimestampProfiler::Result, which contain the ZX_CLOCK_MONOTONIC time, as well as the number of GPU microseconds used by that part of the frame.

Next, escher::Frame::TraceQueryResults() adds the events to the trace log.  The tricky part is that these events happened in the past, and inserting past events into the trace log isn't directly supported by the convenience macros in <trace/event.h>.  TraceQueryResults() transforms the query times from ZX_CLOCK_MONOTONIC to the "ticks" used by the trace machinery, and then uses the underlying trace APIs to add the events at the proper times.

**Comment by Hixie** [comment]
cc @chinmaygarde @jason-simmons @cbracken

**Comment by chinmaygarde** [comment]
Currently, all tracing in the Flutter engine is redirected to the Dart timeline and is available to view only via the observatory. This is because timeline events from Dart do not provide a callback into native code that we can then use to forward to platform specific tracing APIs. Instead, we go the other way around and forward all tracing information to the Dart VM.

If we choose to not support traces from Dart code, it is fairly straightforward to augment the existing macros to redirect traces from the native engine code to a platform specific tracing implementation. Accounting for disparate timebases should be equally straightforward.

**Comment by rmacnak-google** [comment]
Flutter on Fuchsia [configures](https://github.com/flutter/engine/blob/4c82c566edf394a5cfc237a266aea5bd37a6c172/runtime/dart_init.cc#L141) the Dart VM's timeline to also forward to the system trace log, so you should already see events from both the Flutter engine and the Dart code it is running in both Observatory and the trace command.

**Comment by schwa423** [comment]
What about GPU profiling?  This will probably require collaborating with Skia.

**Comment by tvolkert** [comment]
Related: https://fuchsia.atlassian.net/projects/FL/issues/FL-28

**Comment by tvolkert** [comment]
@brianosman can you lend your thoughts on the Skia integration required here?

**Comment by brianosman** [comment]
We've discussed this, and have a few questions: What granularity of GPU timing were you hoping to get? Given some of Skia's internal complexity (off-screen surfaces, reordering of operations, etc...), getting detailed information with references back to the initiating CPU work is going to be difficult.

For coarse information, we could track events for the start and end of each flush (note that there may be multiple flushes per frame). Skia also doesn't have a strong "frame" concept, so knowing when to query events is tricky.

Alternatively, we could allow events to be supplied by the client (similar to the semaphore wait/flush API). In that case, it would probably make sense to put the API higher level (e.g. GrContext). In that case, if the client just needs markers for the start and end of a frame, it could decide when that is, insert the begin (and later, end), and also manage querying the events from the previous frame.

Would that be acceptable/easier?

[ @bsalomon @egdaniel]

**Comment by GaryQian** [comment]
It seems that this should work already, since Dart timeline passes the tracing information to the Fuchsia tracer, and the Flutter engine passes tracing of both CPU and GPU to the Dart timeline.

I will verify this is the case.

**Comment by GaryQian** [comment]
I can confirm that the fuchsia tracing currently includes the Flutter engine traces.
![alt text](https://i.imgur.com/a7hDvRZ.png "Logo Title Text 1")
