### ISSUE TITLE
[url_launcer] Add Support for ASWebAuthenticationSession

### ISSUE THREAD

**Issue by Bassiuz** [flutter/flutter#138059]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

For implementing a nice and seamless authentication experience on iOS, the best practice is to use an in app browser to do the navigation. Specifically the ASWebAuthenticationSession should be used to share cookies and enable SSO for the user.

For more background on the current state of Mobile SSO:
https://developer.okta.com/blog/2022/01/13/mobile-sso

### Proposal

It would be very nice of this is supported in url_launcher, as an option or a launch mode. I created a draft/suggestion of how this could be implemented and made a fork/pr on the packages repository. Completing this feature would cost me some time, so I wanted to start with asking for some guidance if this is the right approach.

https://github.com/flutter/packages/pull/5349

**Comment by danagbemava-nc** [comment]
Hi @Bassiuz, thanks for raising the PR. Turns out there's already an existing issue requesting this feature. See  https://github.com/flutter/flutter/issues/25928. Kindly update your PR to point to the original issue. 

Closing this in favour of the issue linked above. 

Thank you
