### ISSUE TITLE
 Add local notification support for Android and iOS via flutter APIs

### ISSUE THREAD

**Issue by jacksontempra** [flutter/flutter#13806]
It would be really helpful for non-native developers like myself to be able to schedule local notifications on the device for things like reminders.

**Comment by zoechi** [comment]
something like https://github.com/flutter/plugins/tree/master/packages/android_alarm_manager ?

**Comment by jacksontempra** [comment]
@zoechi thanks for the link, sorry if this is a stupid question but is this for alarms or notifications? And if it is for notifications, is there something similar for iOS? Thanks :)

**Comment by mit-mit** [comment]
Is this the same as https://github.com/flutter/flutter/issues/2731 ? If so, please add a "vote" in that bug by pressing thumbs up in the top-most comment of that bug.

**Comment by jacksontempra** [comment]
@mit-mit yes it seems to be, have done so :)

**Comment by mit-mit** [comment]
Thanks for confirming
