### ISSUE TITLE
[CP] DevTools hotfix 2.28.2

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#138003]
### Issue Link

https://github.com/flutter/devtools/pull/6644

### Commit Hash

[8db42fc4a0b7a4ca180ba73fc387b81b0927e8a0](https://github.com/flutter/devtools/commit/a114b4851ff4538ce52a77eb1505eed6d516948c) (from flutter/devtools)

### Target

beta

### PR Link

https://dart-review.googlesource.com/c/sdk/+/334940

### Changelog Description

I am not sure how to push this DevTools cherry-pick through, so I'll be very descriptive here and hopefully can get some guidance from the Flutter / Dart SDK rollers.

There was an issue in DevTools that was fixed by https://github.com/flutter/devtools/pull/6644. DevTools extensions were broken for test debugging targets because we were only looking for `lib/main.dart` as an app's entry point. This PR modifies the RegExp search to support other targets within a project.

The current DevTools version set to go into the November Dart / Flutter stable release is 2.28.1. I created a branch on the `flutter/devtools` repo [2.28.2](https://github.com/flutter/devtools/commits/2.28.2). This branch is created from 2.28.1 and cherry picks the fix from https://github.com/flutter/devtools/pull/6644 as well as bumps the version to 2.28.2 (see [diff](https://github.com/flutter/devtools/compare/v2.28.1...2.28.2)).

### Impacted Users

DevTools extension authors

### Impact Description

DevTools extensions are not supported for debugging targets that are not `lib/main.dart`. For example, a package that is for debugging tests might want to provide an extension to give their users tooling. The DevTools extension author who submitted this fix will not be able to publish their extension unless this cherry-pick goes through. This will delay them shipping their extension until the next flutter stable.

Since this upcoming Flutter stable release will be the first that includes DevTools extension support altogether, it would also be ideal to not release with this bug that limits the type of debugging tools DevTools extensions authors can provide.

### Workaround

There is no workaround. This DevTools extension author cannot expect their users to work from Flutter master in order to get access to the extension.

### Risk

low

### Test Coverage

yes

**Comment by kenzieschmoll** [comment]
I am not sure how to proceed with this cherry-pick. The Dart SDK CL here (https://dart-review.googlesource.com/c/sdk/+/334580) updates the "devtools_rev" hash in the SDK DEPS file to `8db42fc4a0b7a4ca180ba73fc387b81b0927e8a0`, which is the tip of flutter/devtools @ branch 2.28.2. However, this hash does not correspond to a devtools build in CIPD because the [DevTools LUCI builder](https://ci.chromium.org/ui/p/dart-internal/builders/flutter/devtools) only uploads DevTools builds to CIPD for commits to `flutter/devtools` @ `master`. @sortie 

A lot has changed with the DevTools release process since we last had to do a cherry pick, so I will document the DevTools cherry-pick process for DevTools with the recommended steps once we outline them here. Thanks.

**Comment by kenzieschmoll** [comment]
Cherry pick CL is submitted (https://dart-review.googlesource.com/c/sdk/+/334940). Next step is for @itsjustkevin to re-build the stable branch.

**Comment by CaseyHillers** [comment]
This was released in the 3.16.0 stable.
