### ISSUE TITLE
Move A02s from win to linux

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#138036]
### Is there an existing issue for this?

- [X] I have searched the [existing infra issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-infra)

### Type of Request

bug

### Infrastructure Environment

devicelab

### What is happening?

There is no need for A02s devices on anything but linux hosts. So move the device from win-7 to another bot.

**Comment by yusuf-goog** [comment]
Moving the host to correct config : go/cirgs/6644797

**Comment by kentnguyen99** [comment]
Moving A02s phone from win-7 to mac-17 due to existing phone on mac-17 has battery issues.

**Comment by yusuf-goog** [comment]
@kentnguyen99 do not move the A02s to a mac or windows host. They are not needed there. Please move to a linux host.

**Comment by kentnguyen99** [comment]
I moved A02s phone to linux-16.
