### ISSUE TITLE
You could try re-setting up your Java in android studio settings. in my case, Studios java version was not matching therefore it was giving issues.

### ISSUE THREAD

**Issue by Apliarte** [flutter/flutter#138019]
Thank you Thank you Thank you, you helped me to solve my problem.
_Originally posted by @Shreyans13 in https://github.com/flutter/flutter/issues/134241#issuecomment-1723331926_

**Comment by darshankawar** [comment]
@Apliarte 
Please don't use comments from other issues to file a new issue. Please try to use new issue template and fill out requested details so that we'll have enough info to work with.
Closing for now.
