### ISSUE TITLE
Regression in golden testing a disabled chip with delete button in CanvasKit

### ISSUE THREAD

**Issue by TahaTesser** [flutter/flutter#138009]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Test a disabled Chip with delete button before and after https://github.com/flutter/flutter/pull/136918 in canvas kit.

This seems to be caused by  https://github.com/flutter/flutter/pull/136918 

### Test Code

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('Disabled Chip with delete button', (WidgetTester tester) async {
    await tester.pumpWidget(
      MaterialApp(
        home: Material(
          child: RawChip(
            isEnabled: false,
            label: const Text('Label'),
            onDeleted: () {},
          ),
        ),
      ),
    );

    // Delete button should be visible.
    await expectLater(find.byType(RawChip), matchesGoldenFile('disabled_chip_with_delete_button.png'));
  });
}
```

####  Test Command
`flutter test --web-renderer canvaskit  --platform=chrome  --update-goldens`

### Note
This is blocking a Chips PR https://github.com/flutter/flutter/pull/137685

When testing the fix, I run to this issue with no label or delete icon being rendered by the golden test.

<img width="1067" alt="Screenshot 2023-11-07 at 19 33 43" src="https://github.com/flutter/flutter/assets/48603081/0f12be4d-c6f8-4f2e-8597-d2186b63f43c">

### Before  https://github.com/flutter/flutter/pull/136918 

![disabled_chip_with_delete_button_before](https://github.com/flutter/flutter/assets/48603081/f8c5358b-9e3f-4a84-9d48-c033ae9a6d04)

### After  https://github.com/flutter/flutter/pull/136918 

![disabled_chip_with_delete_button_after](https://github.com/flutter/flutter/assets/48603081/4285d39c-7470-43d2-9a40-ac938eab671cA)

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by dam-ease** [comment]
I can reproduce this as well using the test code in the original comment.

| Before #136918  | After #136918 |
|--------|--------|
| <img src="https://github.com/flutter/flutter/assets/53122008/06b6bd42-b998-4a88-8579-b41516ce4e1c"> | <img src="https://github.com/flutter/flutter/assets/53122008/10ce2651-7573-4c74-aab2-12888e64d587"> |

**Comment by HansMuller** [comment]
@harryterkelsen can you take a look at this issue since  it seems to have been caused by https://github.com/flutter/flutter/pull/136918

**Comment by Piinks** [comment]
@harryterkelsen @yjbanov can you take a look at this regression in canvaskit? Should https://github.com/flutter/flutter/pull/136918 be reverted?

**Comment by harryterkelsen** [comment]
I looked into this a bit today. There is something specific about the combination of: chip disabled, chip has delete button, and rendering using Picture.toImageSync that is causing the text not to render in this failing test. The chip renders correctly when running normally (i.e. if you were to copy-paste this misbehaving in a real app and run it, you would see the chip render as expected). I am trying to find a minimal repro for this problem; I suspect the problem repros with text with opacity styling and glyphs that have no font (the delete button in this case).

**Comment by TahaTesser** [comment]
>  (i.e. if you were to copy-paste this misbehaving in a real app and run it, you would see the chip render as expected).

Exactly, this is only in golden test.
