### ISSUE TITLE
Opening plugins using intellij does not recognize flutter

### ISSUE THREAD

**Issue by seklum** [flutter/flutter#13805]
When opening the plugins repository in intellij it does not prompt for the flutter plugin. It recognizes the it only as a dart project. Manually setting the flutter sdk does add the dart sdk properly but it any flutter imports etc are not recognized.

## Steps to Reproduce
Android studio -> new project from version control -> plugins

**Comment by zoechi** [comment]
What happens when you run `flutter doctor` in the project directory?
Please post the output.

**Comment by seklum** [comment]
flutter doctor
```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\Charles\StudioProjects\plugins>flutter doctor
[√] Flutter (on Microsoft Windows [Version 10.0.14393], locale en-US, channel master)
    • Flutter at C:\Users\Charles\flutter
    • Framework revision 4d2c2aaaa1 (3 days ago), 2017-12-27 07:30:31 -0800
    • Engine revision 7c126001d8
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.9e8a3e2d31621c1bdf6139d068e7898a2ac2ab5a

[√] Android toolchain - develop for Android devices (Android SDK 27.0.2)
    • Android SDK at C:\Users\Charles\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[-] Connected devices
    • None
```

**Comment by Hixie** [comment]
cc @devoncarew Is this an IntelliJ issue?

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
