### ISSUE TITLE
Regression when switching to Impeller with ClipOval and ImageFiltered blur

### ISSUE THREAD

**Issue by Reprevise** [flutter/flutter#138052]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Copy the code below
2. Run using `flutter run --no-enable-impeller` to see the desired result (blur is clipped)
3. Run using `flutter run --enable-impeller` to see what happens on Impeller (blur isn't clipped)

### Expected results

The blur should be oval-clipped.

### Actual results

The blur isn't oval-clipped and instead is like a square.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'dart:ui' as ui;

import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Material App Bar'),
        ),
        body: SizedBox.square(
          dimension: 96,
          child: ClipOval(
            child: UnconstrainedBox(
              child: ImageFiltered(
                imageFilter: ui.ImageFilter.blur(
                  sigmaX: 15,
                  sigmaY: 15,
                  tileMode: TileMode.decal,
                ),
                child: const SizedBox.square(
                  dimension: 56,
                  child: DecoratedBox(
                    decoration: BoxDecoration(
                      shape: BoxShape.circle,
                      color: Colors.red,
                    ),
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

No impeller:

![Simulator Screenshot - iPhone 15 Pro Max - 2023-11-07 at 20 16 29](https://github.com/flutter/flutter/assets/25782944/94ea4666-e000-4ef6-b633-49df088713f5)

Impeller:

![Simulator Screenshot - iPhone 15 Pro Max - 2023-11-07 at 20 17 03](https://github.com/flutter/flutter/assets/25782944/c661ab3d-a265-46f8-bb0a-6492ee0f502b)

</details>

### Logs

N/A

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.9, on macOS 13.5 22G74 darwin-arm64, locale en-US)
    • Flutter version 3.13.9 on channel stable at /Users/ben/.puro/envs/stable/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (13 days ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.13.0

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.84.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (2 available)
    • iPhone 15 Pro Max (mobile) • C7F79C45-4A02-4C0F-8F46-7F85136A964B • ios          • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64 • macOS 13.5 22G74 darwin-arm64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

</details>

**Comment by Reprevise** [comment]
Did some further investigation, this issue appears to have been fixed in the beta and master channels, perhaps the commit that has fixed it can be cherry picked into stable?

**Comment by darshankawar** [comment]
Thanks for the report and update @Reprevise 


> that has fixed it can be cherry picked into stable?

You may file this request using the [template](https://github.com/flutter/flutter/issues/new?assignees=&labels=cp%3A+review&template=7_cherry_pick.yml&title=%5BCP%5D+%3Ctitle%3E) so that the concerned team can make a decision whether it is feasible to be cherry picked or not. You can also read more about the CP process [here](https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process) for your reference. 

Since the reported issue is working as expected on master, I'll close this issue as fixed based on our triage policy.
