### ISSUE TITLE
[CP] catch StdinException when STDIN pipe is broken

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#138040]
### Issue Link

https://github.com/flutter/flutter/issues/129198

### Commit Hash

https://github.com/flutter/flutter/commit/b416473bbb196dc03eed717fd412698cb61b5dbb

### Target

beta

### PR Link

https://github.com/flutter/flutter/pull/138032

### Changelog Description

Ignore exceptions when trying to set the echo mode of the terminal when the STDIN pipe has been broken.

### Impacted Users

flutter developers who use `flutter run ...`

### Impact Description

I'm not sure the exact way users get in this situation, but it is our top tool crasher. Somehow, users are triggering flutter run, but when the tool attempts to modify the STDIN file descriptors echo mode, it reaches an exception that the STDIN pipe has been broken.

Without this fix, the tool will crash and the app will not be run. With this fix, the tool will continue launching the app, without modifying the STDIN echo mode (which shouldn't matter since there's no longer anything attached to STDIN anyway).

### Workaround

It's unclear to me the workaround here since I'm not sure why the STDIN pipe is being broken.

### Risk

low

### Test Coverage

yes

### Validation Steps

Unclear to me, see "Impact Description". The unit test in the CP PR at least will verify that at the point the crash is happening we will catch StdinExceptions.

**Comment by christopherfujino** [comment]
@zanderso can you review this request?

**Comment by zanderso** [comment]
CP LGTM

**Comment by XilaiZhang** [comment]
oh I missed this one yesterday afternoon, beta has already shipped this morning. 
If this is for flutter-3.16-candidate.0, is it okay if we land it as stable hotfix?

**Comment by christopherfujino** [comment]
> oh I missed this one yesterday afternoon, beta has already shipped this morning. If this is for flutter-3.16-candidate.0, is it okay if we land it as stable hotfix?

Yes, that sounds like the best course of action. Although this is important, I don't think it's worth doing an emergency additional release.

**Comment by CaseyHillers** [comment]
Released in 3.16.1
