### ISSUE TITLE
Android toolchain - Could not determine java version

### ISSUE THREAD

**Issue by shehanm95** [flutter/flutter#138085]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    X Could not determine java version

### Actual results

![Screenshot (818)](https://github.com/flutter/flutter/assets/45226619/0559ff3f-b766-462d-896f-5db0e394b27b)

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by bartekpacia** [comment]
Hi @shehanm95, do you have Java installed? Try typing `java` or `javac` in your command prompt to verify you do. These binaries should be present in your $PATH.

I also see you have Android Studio 4.1 installed - [that's pretty old](https://developer.android.com/studio/releases/past-releases/as-4-1-0-release-notes). Consider upgrading to the latest version.

**Comment by arodme** [comment]
I'm having the same issue. 

I have java installed:

$ java -version
java version "1.8.0_391"
Java(TM) SE Runtime Environment (build 1.8.0_391-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.391-b13, mixed mode)

I do have an older macOS Monterey 12.7.1

Here is my flutter doctor response

$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
Could not parse java version from: 

If there is a version please look for an existing bug
https://github.com/flutter/flutter/issues/ and if one does not exist file a new
issue.
[✓] Flutter (Channel stable, 3.13.9, on macOS 12.7.1 21G920 darwin-x64, locale
    en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ Could not determine java version
[!] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 3 categories.
