### ISSUE TITLE
Upgrade initial set of devicelab mac hosts to 13.6.1

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#138011]
### Is there an existing issue for this?

- [X] I have searched the [existing infra issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-infra)

### Type of Request

infra task

### Infrastructure Environment

devicelab

### What is happening?

We need to upgrade the following mac hosts to macOS 13.6.1:

### Staging pool
flutter-devicelab-mac-10
flutter-devicelab-mac-4
flutter-devicelab-mac-11 (already at 13.x, please upgrade to 13.6.1 if needed)
flutter-devicelab-mac-33

### Try pool
flutter-devicelab-mac-1 (already at 13.x, please upgrade to 13.6.1 if needed)
flutter-devicelab-mac-45 (already at 13.x, please upgrade to 13.6.1 if needed)

### Prod pool
flutter-devicelab-mac-2
flutter-devicelab-mac-3
flutter-devicelab-mac-6
flutter-devicelab-mac-43
flutter-devicelab-mac-20
flutter-devicelab-mac-35

### Steps to reproduce

~~One upgraded please contact @vashworth to reset the Xcode cache.~~
Delete any directories within `/opt/flutter/xcode`if applicable.

Also verify `/opt/flutter/xcode` is owned by `swarming` user.

Also, ensure `DevToolsSecurity` is enabled. 
* Run `DevToolsSecurity` - should get response "Developer mode is already enabled." 
* If you don't get the message, run `sudo /usr/sbin/DevToolsSecurity -enable` to enable.

### Expected results

I expect to see X when Y is finished.

**Comment by yusuf-goog** [comment]
Ran cache clobber command for mac-1, mac-11, mac-33 and mac-45

**Comment by vashworth** [comment]
https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-11 needs to have `DevToolsSecurity` enabled

**Comment by vashworth** [comment]
@kentnguyen99 @yusuf-goog Please ensure `DevToolsSecurity` is enabled after upgrading to macOS 13

**Comment by yusuf-goog** [comment]
@kentnguyen99  please run this command on all macs after upgrade:
`DevToolsSecurity`

you should the response:
`Developer mode is already enabled.`

**Comment by yusuf-goog** [comment]
ran:
`~/src/chromium/src/tools/infra$ vpython3 named-cache-clobber.py --pool luci.flutter.prod -S chromium-swarm.appspot.com --cache flutter_xcode --bot-id  flutter-devicelab-mac-2`

and `DevtToolsSecurity`

for mac-2, mac-4, mac-10

**Comment by kentnguyen99** [comment]
Upgrading Mac OS 13.6.1 all machines in ticket has been completed.

**Comment by yusuf-goog** [comment]
ran:
~/src/chromium/src/tools/infra$ vpython3 named-cache-clobber.py --pool luci.flutter.prod -S chromium-swarm.appspot.com --cache flutter_xcode --bot-id  flutter-devicelab-mac-2

and DevtToolsSecurity

mac-3, 6, 43, 20, 35

**Comment by yusuf-goog** [comment]
all machines updated. closing.
