### ISSUE TITLE
Firebase Authentication: Email verification and password recovery

### ISSUE THREAD

**Issue by bramvbilsen** [flutter/flutter#13802]
It is possible to check whether a user's email address is verified at the moment, but there is no way to actually verify an email address with the current Firebase Auth plugin. Neither is password recovery.
This should be added :)

**Comment by abogdanovich1** [comment]
Please add this feature! Very crucial for my application and is probably the only thing keeping me from full adoption of Flutter!

**Comment by Arno-Z** [comment]
Bumping this. Also missing a password change feature for native firebase users.

**Comment by zoechi** [comment]
Looks like a dup of #12459

**Comment by Hixie** [comment]
closed as dupe
