### ISSUE TITLE
The developer of Maps SDK for Android (com.google.android.gms:play-services-maps) has reported version 16.0.0 as outdated

### ISSUE THREAD

**Issue by BunnyBuddy** [flutter/flutter#138079]
Hi, 
We've been updating our app (build without null safety its an old app using Flutter 2.10.4) on PlayStore and AppStore every now and then. Yesterday, I got a warning while publishing an update for our app on PlayStore and it said,

```
Warning
The developer of Maps SDK for Android (com.google.android.gms:play-services-maps) has reported version 16.0.0 as outdated. After 90 days from releasing this version of your app, you won't be able to release new versions which contain this SDK until you upgrade to a newer version (17.0.0+).
Learn more about the SDKs that you're using and make informed SDK choices with [Google Play SDK Index](https://play.google.com/sdks).
```

Now, I am not using google maps anywhere in my app (its an ecommerce app) and if I search in the project directory the only line I found to have **play-services-map** was in a third party package flutter_braintree/android/ivy.xml.

```
<dependency org="com.google.android.gms" name="play-services-maps" rev="16.0.0" transitive="false" conf="releaseCompileClasspath-&gt;default"/>
```
I changed the rev=16.0.0 to 17.0.0 just to check if playstore considers it okay or not but still I get the same warning.
I don't know which file/library/package is causing this issue as I've not changed anything in the app and it was fine.
I've really hit a wall now. Have been google, gpt, stackoverflow, no one seems to know whats wrong.

**Here's my flutter doctor -v,**

```
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.6.8 21G725 darwin-x64, locale en-PK)
    • Flutter version 2.10.4 at /Users/macbookpro/src/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (1 year, 7 months ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/macbookpro/Library/Android/sdk
    • Platform android-34, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Connected device (2 available)
    • M iPhone (mobile) • 0000-001 • ios            • iOS 16.6.1 20G81
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 119.0.6045.123

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Here's our app's android/build.gradle file contents,**
```
buildscript {
    ext.kotlin_version= "1.5.31"
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath 'com.google.gms:google-services:4.3.10'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by dam-ease** [comment]
Hi @BunnyBuddy. Thanks for filing this. From the warning message, my guess will be that there is a package in your app that probably depends on this package. Are you open to upgrading your packages or suspected packages that could be depending on this to the latest versions?

**Comment by stuartmorgan** [comment]
Flutter itself does not have any dependencies on that library, and the only plugin maintained by the Flutter team that depends on it (`google_maps_fluttter`) uses a newer version, so this is not coming from any code within the control of the Flutter team. Given that, it's not in scope for this issue tracker.

> Now, I am not using google maps anywhere in my app (its an ecommerce app) and if I search in the project directory the only line I found to have **play-services-map** was in a third party package flutter_braintree/android/ivy.xml.

If you have a dependency coming from a third-party package, you'll need to contact the developers of that package.

**Comment by BunnyBuddy** [comment]
> Hi @BunnyBuddy. Thanks for filing this. From the warning message, my guess will be that there is a package in your app that probably depends on this package. Are you open to upgrading your packages or suspected packages that could be depending on this to the latest versions?

Yes I am willing to upgrade the packages but how do I know which package is the suspected package ?

**Comment by BunnyBuddy** [comment]
@dam-ease 
**This is the pubspec.yaml file**

`name: aaa
description: A new Flutter application.

# ios
#version: 0.1.37+1

# android
version: 0.1.39+52

environment:
  sdk: ">=2.7.0 <3.0.0"

dependency_overrides:
  firebase_core_platform_interface: 4.2.0
  url_launcher_android:
    path: ./url_launcher_android

dependencies:
  flutter:
    sdk: flutter
  flutter_braintree:
    path: ./flutter-braintree-master
  onesignal_flutter:
    path: ./flutter-onesignal
  cupertino_icons: ^1.0.2
  get: 4.5.0
  carousel_slider: ^3.0.0
  email_validator: ^2.0.1
  tab_indicator_styler: ^1.0.0
  flutter_rating_bar:
  flutter_staggered_grid_view: ^0.3.4
  dotted_border: ^2.0.0
  http: ^0.13.1
  shimmer: ^2.0.0
  flutter_slidable: ^0.6.0
  google_sign_in: ^5.0.3
  flutter_facebook_auth: ^3.5.3
  sign_in_with_apple: ^3.2.0
  sqflite: ^2.0.0+3
  google_place: ^0.4.0
  shared_preferences: ^2.0.6
  nuts_activity_indicator: ^0.1.1
  graphql_flutter: ^5.0.0
  flutter_html: ^2.2.1
  equatable: ^2.0.3
  pull_to_refresh: ^2.0.0
  badges: ^2.0.1
  image_picker: ^0.8.4+1
  firebase_core: 1.14.0
  firebase_analytics: 8.3.4
  firebase_performance: ^0.6.0+2
  url_launcher: ^6.0.9
  dio: ^4.0.0
  flutter_svg: ^0.22.0
  syncfusion_flutter_datepicker: ^19.3.45
  flutter_typeahead: ^3.2.1
  lottie: ^1.2.1
  google_fonts: ^2.1.0
  flutter_screenutil: 5.0.0+2
  app_tracking_transparency: ^2.0.2+1
  new_version_plus: ^0.0.1+4
  uni_links: ^0.5.1
  app_links: ^3.4.1
  flutter_phoenix: ^1.0.0
  device_info_plus: ^4.0.0
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  pusher_channels_flutter: 2.0.1
  intl: ^0.17.0
  social_share: ^2.2.1
  share_plus: ^4.5.3
  upgrader: ^4.7.0
  photo_view: ^0.14.0
  file_picker: ^4.6.1
  flutter_native_splash:
  multi_image_picker2: ^5.0.2
  youtube_player_iframe: ^2.2.2
  cached_network_image: ^3.2.0
  http_auth: ^1.0.1
  flutter_inappwebview: ^5.6.0+2
  uuid: ^3.0.7
  country_icons: ^2.0.2
  flutter_animate: ^4.1.0
  animated_text_kit: ^4.2.1
  like_button: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/launcher_icon.png"
`

**Comment by elingersin1** [comment]
@BunnyBuddy did you manage to solve it?

**Comment by chiragvorasav** [comment]
I'm also facing the same issue

**Comment by dam-ease** [comment]
Hi everyone!
As mentioned [here](https://github.com/flutter/flutter/issues/138079#issuecomment-1801850728),  this is not coming from any code within the control of the Flutter team, kindly try upgrading the other third-party packages in your code and file an issue in the appropriate package that might be causing this.
