### ISSUE TITLE
Videoplayer continues to play in background when changing state

### ISSUE THREAD

**Issue by seklum** [flutter/flutter#13804]
Videos using the video player plugin are not removed when calling setState(). This results in multiple videos playing in the background of the app with no way to close them.

## Steps to Reproduce
Use video player play a video and then update/change the state of the widget containing that video.

**Comment by sigurdm** [comment]
The video playback is controlled by the ```VideoPlayerController``` object, not the ```VideoPlayer``` widget that only displays the video.
If you want to control the playback with the lifecycle of a widget, use a StatefulWidget and the ```initState()```, ```deactivate()``` and ```dispose()``` methods. Check the example: https://github.com/flutter/plugins/blob/master/packages/video_player/example/lib/main.dart

**Comment by seklum** [comment]
Thanks, I had set it up with an older version.

**Comment by RIddhiIroid** [comment]
@seklum which version did you use?
