### ISSUE TITLE
Expose animation parameters for the [ExpansionTile] widget

### ISSUE THREAD

**Issue by matheus-kirchesch-btor** [flutter/flutter#138047]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

The default ExpansionTile animation looks glitchy because the speeds in which the tile expands and collapses are different.

I will post 3 videos comparing the default one, one with a linear curve and another one with a linear curve and a little longer duration so what I mean is more clear.

Default ExpansionTile animation

https://github.com/flutter/flutter/assets/68293882/d88f7fb1-3029-4df1-ba57-368c2de929ac

ExpansionTile with linear curve

https://github.com/flutter/flutter/assets/68293882/e5600378-638b-43ad-b155-85a36f65e736

ExpansionTile with linear curve and a little longer animation (a little bit smoother)

https://github.com/flutter/flutter/assets/68293882/a3e0cab8-33b7-48d5-9fbd-177237320b6e

### Proposal

The proposed fix is simply to expose parameters to let us control the curve and duration of the expansion animation.
![image](https://github.com/flutter/flutter/assets/68293882/feb4a456-4a69-405d-a68d-94508baecd12)
![image](https://github.com/flutter/flutter/assets/68293882/a31b238d-50c1-4161-9b48-3af6e1e35479)

**Comment by HansMuller** [comment]
CC @TahaTesser 
The approach we're considering for overriding animation parameters is described here: https://github.com/flutter/flutter/pull/137945 and could be applied to ExpansionTile.  We'd appreciate your feedback on #137945 if you have time to take a look.

**Comment by TahaTesser** [comment]
@matheus-kirchesch-btor 
I plan to add the upcoming `AnimationOverride` class to this widget.
