### ISSUE TITLE
Rebuild screen when resize window on web

### ISSUE THREAD

**Issue by M97Chahboun** [flutter/flutter#138078]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. install go_router package last 
2. add routers.dart and configure MaterialApp
3. open login screen and type password then resize window the password field will reset (as include on screenshot)
4. when access login screen from built-in navigator working as expected

### Expected results

The password field keep data

### Actual results

The password field reset

### Code sample

<details><summary>routers.dart</summary>

```dart

// extension.dart
extension Responsive on BuildContext {
  Size get size => MediaQuery.of(this).size;
  bool get isLarge => size.width >= largeBreakpoint;
  bool get isMeduim =>
      size.width < largeBreakpoint && size.width >= smallBreakpoint;
  bool get inMeduimAndLarge => isMeduim || isLarge;
}



class RoutersConfig {
  
static FutureOr<String?> handleRedirect(
      BuildContext context, GoRouterState state) {
    String target = state.uri.toString();
    String? to = context.inMeduimAndLarge ||  kIsWeb ? Boarding.route : Welcome.route;
    final bool loginNotRequired =
        notNeedLogin.where((e) => e.startsWith(to!)).isNotEmpty;
    to = target.startsWith("/exam/") ? Login.route + "?next=" + target : to;
    to = loginNotRequired && target != "/" ? null : to;
    return to;
  }

  static GoRouter routers = GoRouter(
  redirect: handleRedirect,
    routes: [
      GoRoute(
        path: '/login',
        builder: (context, state) => Login(),
      ),
    ],
    errorPageBuilder: (context, state) => NoTransitionPage<void>(
      key: state.pageKey,
      child: const NotFoundPage(),
    ),
  );
}
```

</details>

<details><summary>main.dart</summary>

```dart
  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerConfig: RoutersConfig.routers,
      scrollBehavior: CustomScrollBehavior(),
      debugShowCheckedModeBanner: false,
      title: "أكاديمية جاهز",
      localizationsDelegates: context.localizationDelegates,
      supportedLocales: context.supportedLocales,
      locale: context.locale,
    );
  }
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![Upload media here](https://github.com/flutter/flutter/assets/69054810/edc6f4d3-d7ea-49b5-871c-ecd79bb95fa0
)

</details>

### Logs

<details><summary>Logs</summary>

```console
Nothing..
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.7, on macOS 13.3.1 22E772610a darwin-arm64,
    locale en-MA)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.82.2)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by dam-ease** [comment]
Hi @M97Chahboun. The code snippets shared seem to be incomplete.
Please can you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code?
Thank you.

**Comment by M97Chahboun** [comment]
@dam-ease I updated snippets...
I detected the issue on `context.inMeduimAndLarge` when used on redirect method
when I removed context.inMeduimAndLarge from redirect method the app worked as expected...

**Comment by dam-ease** [comment]
Thanks for your response. 

> when I removed context.inMeduimAndLarge from redirect method the app worked as expected...

Per this comment, does this imply the issue is solved and can be closed?

I see the snippets but for an issue to be workable, it needs to be reproducible with a minimal complete code sample that doesn’t include 3rd party plugins or complex production code. This should be one we could run directly to produce this issue.

**Comment by M97Chahboun** [comment]
Yes you can close it I will try to reproduce it for detect the issue
