### ISSUE TITLE
[Impeller] Run framework tests with --enable-impeller.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#138170]
Probably should do https://github.com/flutter/flutter/issues/138169 first to make this easier, since if swiftshader is dynamically linked we'll need to upload that and add it to the dylib path to work - but if we can statically link it, we can just invoke flutter_tester with the new arguments more easily.

We should be able to launch `flutter_tester` with `--enable-impeller` now on the framework tests. This would get us coverage (in the Vulkan backend only at this point) of more Impeller code paths, and more goldens to look at.

We'd want to make sure these goldens are appropriately tagged as being rendered with Impeller as part of implementing this.

**Comment by jonahwilliams** [comment]
This will be easier to do if we link swiftshader, but should be fairly straightforward once that is done.

**Comment by jonahwilliams** [comment]
We are now running framework tests with enable-impeller on macOS
