### ISSUE TITLE
[Impeller] Add flush API to DeviceBuffer for avoiding copies.

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#138119]
Provide an API that allows for grabbing a mutable reference to the fixed size CPU backing store underpinning a DeviceBuffer so that it may be written to directly (e.g. by passing it to libtess), and then explicitly Flush changes.

Right now, we render out geometry to staging buffers, which is _then_ copied into a DeviceBuffer's staging buffer, for example.

**Comment by jonahwilliams** [comment]
how do we handle the reallocation of the device buffer performed by the host buffer?

**Comment by bdero** [comment]
Writing a separate proposal for that at the moment. ;)

**Comment by bdero** [comment]
For Metal this would be getting a pointer to the `MTLBuffer.contents`.
And `DeviceBuffer::Flush` should also take a range for the region to upload `MTLBuffer didModifyRange`, etc.

**Comment by bdero** [comment]
Bug for the HostBuffer is here: https://github.com/flutter/flutter/issues/138161

**Comment by chinmaygarde** [comment]
Not all device buffers can map their allocations in user space. I am having a hard time envisioning how such an API might work.

**Comment by jonahwilliams** [comment]
We don't use a HostBuffer staging buffer anymore, all allocations are written to actual device buffers (except on GLES) and flushing writes is avoided via usage of host coherent memory.
