### ISSUE TITLE
Disable partial repaint on iOS simulators.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#138125]
Two reports:
 * https://github.com/flutter/flutter/issues/137755
 * https://github.com/flutter/flutter/issues/138104
 
Can be easily reproduced locally but not clear how to fix. Since simulator performance is less important than fidelity, we should disable partial repaint on Simulators.

**Comment by jonahwilliams** [comment]
I'm currently working on rethinking partial repaint for iOS, so this may or may not be relevant.

**Comment by chinmaygarde** [comment]
xref [go/flutter-reduce-drawable-latency](http://goto.google.com/flutter-reduce-drawable-latency) for additional context on related topics.

**Comment by chinmaygarde** [comment]
Based on the context in the linked doc. I don't think we are going to go ahead with this. Closing as stale.

**Comment by jonahwilliams** [comment]
This issue has nothing to do with the document you linked

**Comment by jonahwilliams** [comment]
Closing this, as the issues ended up being related to additional validation present on simulators that we missed. See also: https://github.com/flutter/engine/pull/50539
