### ISSUE TITLE
The Windows embedder should support multiple views or windows

### ISSUE THREAD

**Issue by dkwingsmt** [flutter/flutter#138179]
The Windows embedder should be able to create multiple views, and use the correct view ID in components/callbacks.

Related: https://github.com/flutter/flutter/issues/30701

(This issue is mostly created for tracking purposes and for TODO.)

**Comment by loic-sharma** [comment]
This is ongoing work. You can track progress here: https://github.com/flutter/flutter/issues/142845

**Comment by dkwingsmt** [comment]
Duplicate of  https://github.com/flutter/flutter/issues/143767 and please go there for progress.
