### ISSUE TITLE
Intermediate representaiton of Dart code for static analysis

### ISSUE THREAD

**Issue by stereotype441** [flutter/flutter#138175]
### Document Link

http://flutter.dev/go/dart-static-analysis-ir

### What problem are you solving?

There’s a large amount of duplication of effort in the linter, because many lint rules need to model the semantics of every possible Dart expression, statement, or pattern. This makes adding new lint rules difficult (since each new lint rule needs to potentially handle all language constructs), and it makes adding new language constructs difficult (since potentially all lint rules need to be updated to handle each new language construct).

This document describes the instruction set for a stack-based virtual machine that can model Dart execution semantics. Then it describes validation rules that determine whether a given instruction sequence is considered well-formed; these well-formedness rules are intended to make it easier to implement static analyses based on this instruction set, by providing for invariants that the static analysis can rely on.

**Comment by stereotype441** [comment]
(Note: I'm filing this issue here because I was directed to so by http://flutter.dev/go/template. But it's really more of a Dart design document than a Flutter one. I'd be glad to find another home for the issue if this isn't the right place for it).

**Comment by bernaferrari** [comment]
Document link doesn't work here.

**Comment by stereotype441** [comment]
> Document link doesn't work here.

@bernaferrari You're right. It should work once https://github.com/flutter/website/pull/9779 lands and gets deployed to flutter.dev. I'm not sure precisely how long that takes.

In the meantime you can access the document directly at https://docs.google.com/document/d/1xJYGBSoXL7h1z43NnjFsXxauQGXvUnacef4XR1zmeGA/edit.

**Comment by darshankawar** [comment]
@stereotype441 
I think this will need to be filed in dart-lang repo: https://github.com/dart-lang/sdk/issues
I can't transfer to that repo, so you will need to file separately in it.
Closing from here.
