### ISSUE TITLE
Build flutter app for linux armhf platform failed

### ISSUE THREAD

**Issue by sonying** [flutter/flutter#138129]
I want run flutter app on debian 9.0 with rockchip rk3288 (armhf) platform

I cross-compile flutter engine for host(X64) and target(armhf)

compile flutter engine for host(X64) use this :
./flutter/tools/gn \
    --runtime-mode release \
    --no-prebuilt-dart-sdk \
    --enable-fontconfig

compile flutter engine for target(armhf) use this :
./flutter/tools/gn \
    --target-sysroot $HOME/flutter-engine/sdk/sysroot \
    --target-toolchain $HOME/flutter-engine/sdk/toolchain \
    --target-triple arm-linux-gnueabihf \
    --target-os linux \
    --linux-cpu arm \
    --embedder-for-target \
    --no-prebuilt-dart-sdk \
    --enable-fontconfig \
    --disable-desktop-embeddings \
    --no-lto \
    --no-goma \
    --runtime-mode release \
    --arm-float-abi hard

compile success and output files in
/home/build/flutter-engine/engine/src/out/host_release/ 
/home/build/flutter-engine/engine/src/out/linux_release_arm/

then exec flutter create sample and use our flutter engine build bundle
$flutter create myapp
$cd myapp
$flutter build bundle --local-engine-src-path /home/build/flutter-engine/engine/src --local-engine=linux_release_arm --target-platform=linux-arm --release -v

but i got an error : 
"linux-arm" is not an allowed value for option "target-platform".

How to do i could build app for linux armhf platform ?

**Comment by huycozy** [comment]
Hi @sonying 
I see there's an open issue addressing the case you described https://github.com/flutter/flutter/issues/75823.

Closing this issue in favor of that one, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
