### ISSUE TITLE
Disable implicit casts

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#13815]
I was just doing some testing and changed the colour in the Stocks app and hot reloaded:

```dart
   switch (_configuration.stockMode) {
      case StockMode.optimistic:
        return new ThemeData(
            brightness: Brightness.light, primarySwatch: Colors.black);// This was Colors.blue
      case StockMode.pessimistic:
        return new ThemeData(
            brightness: Brightness.dark, accentColor: Colors.redAccent);
    }
    assert(_configuration.stockMode != null);
    return null;
```

When I hit hot reload I got this:

```text
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
type 'Color' is not a subtype of type 'MaterialColor' of 'primarySwatch' where
Color is from dart:ui
MaterialColor is from package:flutter/src/material/colors.dart
int is from dart:core
Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
https://github.com/flutter/flutter/issues/new
When the exception was thrown, this was the stack:
════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 13 of 506 libraries in 871ms.
```

I don't know if this is actually a Flutter issue or not, but it seems like if it's not valid to use `Colors.black` that it shouldn't be in the code-completion and it should provide an error in the editor?

**Comment by furkantektas** [comment]
I think this is because ThemeData accepts `MaterialColor` objects while `Colors.black` is a `Color` object which is the super class of `MaterialColor`. `MaterialColor` class provides 10 shades of the given color. Maybe you should instantiate a `MaterialColor` object.

**Comment by DanTup** [comment]
Oh man, have I been bitten by implicit downcasts *again*?! :'(

https://github.com/dart-lang/sdk/issues/30392
https://github.com/dart-lang/sdk/issues/31410

**Comment by leafpetersen** [comment]
@DanTup  Setting aside the possibility of changing this in the language, are there things that are blocking you from turning this off via flag?  That is
 -  Are there granularity issues (some code isn't downcast clean, and can't restrict the scope of the flag appropriately)?
 - Usability: too hard to turn it on in the right places?
 - Wrong default: too hard to remember to flip the default when you create a new project?
 - Wrong semantics: flag catches too much/too little?
 - Other?

I haven't had much time to follow up on this and the implicit dynamic issues, but I'd like to circle back when I can, and it would help to understand what's blocking adoption.

**Comment by DanTup** [comment]
Nothing blocking me, but this is the stocks app the flutter repo which I often use for testing so I can't commit a change to turn it on.

My frustration isn't for any particular project but just the bad default. My thoughts are detailed in the other cases so probably not worth going over again here - I think this case is really just a dupe of those links above now (I guess I didn't parse the error properly when I first hit it).

**Comment by leafpetersen** [comment]
Gotcha.  I think there is some interest in trying to turn this on in the flutter repo at some point, but various things have been blocking it.

**Comment by Hixie** [comment]
Yeah we definitely want to turn this on, Dart's just not quite ready yet. I forget what the exact blockers are too.

**Comment by jonahwilliams** [comment]
I investigated this for the flutter_tools project. There were many cases where I could refactor the API to remove the need for either type of cast, but there were two fairly common pain points:

- stdout/stderr on the Process API is `dynamic`, since it can be either a `List<int>` if no encoding was specified or, always in our case, a String. It would be nice to have `stdoutText` and `stderrText` as typed getters, otherwise we'll have to wrap all of our dart:io code.

- The args package only provides an untyped method of accessing values, but the args themselves are registered in such a way that we should already know their type. Example: `getFlag`, `getOption`, and `getMultioption`.

**Comment by Hixie** [comment]
cc @a14n should we assign this to you? I think you're working on this now right?

**Comment by a14n** [comment]
self-assigned
