### ISSUE TITLE
Reinstall certs on macOS 13 bots

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#138194]
### Is there an existing issue for this?

- [X] I have searched the [existing infra issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-infra)

### Type of Request

bug

### Infrastructure Environment

LUCI

### What is happening?

After being upgraded to macOS 13, it appears that chromium bots lose their codesigning cert:

https://luci-milo.appspot.com/ui/p/flutter/builders/prod/Mac_build_test%20flutter_gallery__transition_perf_e2e_ios/3160/overview

**Comment by yusuf-goog** [comment]
Opened an issue for chromium team to check cert installs on the new macs.

**Comment by ricardoamador** [comment]
@yusuf-goog is this complete? If not can you add the bug that you created here please?

**Comment by keyonghan** [comment]
This should have been completed.
