### ISSUE TITLE
[CP] prevent tool crash when `IntelliJValidatorOnMac` encounters an installation with a missing `CFBundleIdentifier`

### ISSUE THREAD

**Issue by andrewkolos** [flutter/flutter#138180]
### Issue Link

https://github.com/flutter/flutter/issues/138029

### Commit Hash

94550c6

### Target

stable

### PR Link

https://github.com/flutter/flutter/pull/138176

### Changelog Description

Prevents a crash in `flutter doctor` for macOS users who have an IntelliJ or Android Studio installation with a missing `CFBundleIdentifier` in its plist.

### Impacted Users

Flutter devs developing on macOS

### Impact Description

`fluter doctor` crashes for macOS users who have an IntelliJ or Android Studio installation with a missing `CFBundleIdentifier` (which is a required field) in its plist.

### Workaround

Reinstall IntelliJ/Android Studio, or edit the installation's plist file to have an appropriate `CFBundleIdentifier` value.

### Risk

low

### Test Coverage

yes

**Comment by christopherfujino** [comment]
LGTM

**Comment by CaseyHillers** [comment]
Released in 3.16.1
