### ISSUE TITLE
FlatButton Class

### ISSUE THREAD

**Issue by hdkiranbharadwaj** [flutter/flutter#138122]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Flatbutton is non existent but textbutton has replaced it but the thing is most of the older code still uses flatbutton thus we need a flatbutton class to solve this issue.

### Proposal

Flutter team could involve a class in material package with name flatbutton which takes input from the user and then gives the parameter to the non depricated textbutton

**Comment by danagbemava-nc** [comment]
Hi @hdkiranbharadwaj, what are you trying to achieve with the `FlatButton` that you cannot do with the `TextButton`?

**Comment by TahaTesser** [comment]
@hdkiranbharadwaj 
Please follow the migration guide to update codebase. This landed in Stable 2.0.0
https://docs.flutter.dev/release/breaking-changes/buttons

Per deprecation policy, the code is removed after 12 month period, which provides time for developers to migrate their code following migration guide. 

Closing as there is no action here.
