### ISSUE TITLE
Using the `revert` label should require specifying a reason for the revert

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#138164]
### Is there an existing issue for this?

- [X] I have searched the [existing infra issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-infra)

### Type of Request

feature request

### Infrastructure Environment

`revert` label on github.

### What is happening?

When someone reverts a PR with the `revert` label they should be required to specify a reason (e.g. link to a failing test) for why the PR was reverted to give the PR author context.

**Comment by matanlurey** [comment]
IMO this is a very serious issue, and potentially even a security/correctness flaw that we can't audit and understand why PRs were reverted.

**Comment by christopherfujino** [comment]
I think one way to make this happen would be a requirement of adding the revert label is to have a special bot-parseable comment with the relevant data. If it's missing or malformed, the bot comments the validation error and takes off the revert label.

Here's one possible example comment schema:

REVERT_ISSUE_NUMBER=#138164

This will be trivial to pattern match for from bot code, but also GitHub will parse this as an GitHub issue and auto-generate a link for human use.
