### ISSUE TITLE
Android app size become increases (almost double) after upgrading from flutter version 3.10.5 to version 3.13.9.

### ISSUE THREAD

**Issue by SmueezApex** [flutter/flutter#138130]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

run "flutter build apk --release"
app sized become almost double than before. I can assure you that there were no change in my codes.

### Expected results

The app size must be the same as before.

### Actual results

App sized increased almost double.

**Comment by dam-ease** [comment]
Hi @SmueezApex. Thanks for filing this. Are you able to test this on a newly created Flutter project without using any plugins/packages and share the sizes you are able to obtain?

**Comment by SmueezApex** [comment]
> Hi @SmueezApex. Thanks for filing this. Are you able to test this on a newly created Flutter project without using any plugins/packages and share the sizes you are able to obtain?

Hello @dam-ease 
Thank you for your response. So I have opened another fresh new project without any package or anything. the size of the release apk is 17.4MB.
This seems alright no?
But any idea why my app size got double right after I have upgraded the flutter version?

**Comment by dam-ease** [comment]
Thanks for your response. Per your last comment, I see the new flutter project seem to have the same size. 

> But any idea why my app size got double right after I have upgraded the flutter version?

Possibly upgrades in your existing packages.

Closing this as this doesn't seem to be an issue with flutter itself, if you disagree please comment and I'll reopen this.
Thank you!
