### ISSUE TITLE
[Impeller] Change the transient buffer to be a per-frame arena.

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#138161]
* Uniforms and geometry get thrown into per-pass HostHuffers.
* HostBuffers are created per-pass and managed in a pool.
* All emplaced HostBuffer data is copied into a second buffer on the CPU prior to upload.
* There is zero reuse of Device-side allocations across frames, as managed by HostBuffers today.

We can switch to a per-frame arena to reuse DeviceBuffer allocations and remove the need for the additional scratch buffer.

https://docs.google.com/document/d/1hgh57Y14l7M0HYRbq_LAlk8TrkJPeZXXotMEpYWhEAI/edit#heading=h.mf6k21cohky2

**Comment by jonahwilliams** [comment]
@bdero assigning to you assuming that you are also working on this currently.
