### ISSUE TITLE
Newer versions of mac_toolchain slow down Xcode install by ~2 minutes

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#138109]
### Is there an existing issue for this?

- [X] I have searched the [existing infra issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-infra)

### Type of Request

bug

### Infrastructure Environment

LUCI

### What is happening?

Due to [this change](https://chromium.googlesource.com/infra/infra/+/32d81d877ee07af07bf03b7f70ce597e323b80ce%5E%21/#F0) in mac_toolchain, Xcode install takes ~2 minutes longer for every build.

As a workaround [we're hardcoding the mac_toolchain version to an older one](https://flutter-review.googlesource.com/c/recipes/+/52341), but we need a permanent solution.

Example: 
On macOS 12, install xcode step takes 5.5s - https://luci-milo.appspot.com/ui/p/flutter/builders/staging/Mac_ios%20integration_ui_ios_driver_xcode_debug/1557/overview
With macOS 13, install xcode step takes 1.9m - https://luci-milo.appspot.com/ui/p/flutter/builders/staging/Mac_ios%20integration_ui_ios_driver_xcode_debug/1559/overview

### Expected results

Xcode install takes less than 10 seconds when using from cache

**Comment by keyonghan** [comment]
@vashworth assigning this to you considering you are working on this bug. Please reassign if you need infra help.

**Comment by keyonghan** [comment]
Created https://crbug.com/1501416 to track if we can opt out the gatekeeper check or if any option to improve the xcode installation time.

**Comment by vashworth** [comment]
The gatekeeper check was removed from mac_toolchain, so we should try using latest again. I'm going to wait until next week, though, since we're doing macOS Upgrade Phase 2 this week.

**Comment by vashworth** [comment]
All repos have been switch to use latest mac_toolchain again. Slow down no longer observed. Closing.
