### ISSUE TITLE
dart.bat can't find git, but dart.exe works fine

### ISSUE THREAD

**Issue by 1EDExg0ffyXfTEqdIUAYNZGnCeajIxMWd2vaQeP** [flutter/flutter#138144]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Install flutter
2. Notice that the flutter sdk is added to the path: `where.exe flutter dart`
```
C:\tools\flutter\bin\flutter
C:\tools\flutter\bin\flutter.bat
C:\tools\flutter\bin\dart
C:\tools\flutter\bin\dart.bat
```
3. `dart info`
`Error: Unable to find git in your PATH. `
4. But, if I run `C:\tools\flutter\bin\cache\dart-sdk\bin\dart.exe info`, everything is fine
```

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.1.5 (stable) (Tue Oct 24 04:57:17 2023 +0000) on "windows_x64"
- on windows / "Windows 10 Pro" 10.0 (Build 22631)
- locale is en-US

[...]
```

### Actual results

I don't understand why dart.bat tests for git, when it doesn't actually need it. It should be possible to ignore the error (make it into a warning), and/or set a git installation dir with an environment variable.

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

[√] Flutter (Channel stable, 3.13.9, on Microsoft Windows [Version 10.0.22631.2428], locale en-US)
    • Flutter version 3.13.9 on channel stable at C:\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (2 weeks ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\PC\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Users\PC\AppData\Local\Programs\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.5.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
    • Visual Studio Professional 2022 version 17.5.33530.505
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Users\PC\AppData\Local\Programs\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code, 64-bit edition (version 1.83.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.2428]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 117.0.2045.60

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.


```

</details>

**Comment by huycozy** [comment]
Hi @1EDExg0ffyXfTEqdIUAYNZGnCeajIxMWd2vaQeP 
I checked this on my Windows machine but didn't see the error. `dart info` can output the same to `\dart.exe into`.

What is your current Git version? (please share `git --version` output). I'm using git `2.29.2.windows.3`.

**Comment by 1EDExg0ffyXfTEqdIUAYNZGnCeajIxMWd2vaQeP** [comment]
There is no git on my path, which is intentional. I mostly work inside wsl, and have all my git config there. On windows, I use https://github.com/andy-5/wslgit/. All programs I use let me configure the path to the git executable, Including VSCode and Android Studio. I noticed that flutter comes with it's own installation if git for windows under `C:\tools\flutter\bin\mingit`. My expectation would be that it just uses that, unless told otherwise. Another acceptable option to me would be to allow running dart without git on the path, as it works fine. Unless I misunderstand something, most commands of the dart cli don't need git.

**Comment by huycozy** [comment]
>There is no git on my path, which is intentional. I mostly work inside wsl, and have all my git config there.

I'm not sure I can understand this. There is no issue inside WSL, right? And you are reporting an issue for Windows host machine; but you haven't installed git there. Let's try installing git to Windows to see if it works. 

Also, per [System requirements for Windows](https://docs.flutter.dev/get-started/install/windows#system-requirements), git is an essential tool.

**Comment by 1EDExg0ffyXfTEqdIUAYNZGnCeajIxMWd2vaQeP** [comment]
If git is a prerequisite, why does flutter contain a git installation inside `C:\tools\flutter\bin\mingit`?

**Comment by huycozy** [comment]
From my side, I don't see there is `mingit` file/directory from `\flutter\bin\`:

![image](https://github.com/flutter/flutter/assets/104349824/d7748eae-e720-4c9b-b5c4-b11aa5134e64)

Did you set up something extra?

**Comment by 1EDExg0ffyXfTEqdIUAYNZGnCeajIxMWd2vaQeP** [comment]
https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_3.13.9-stable.zip contains the mingit folder

**Comment by huycozy** [comment]
I can see `mingit` there. But I would like to confirm the issue that you haven't installed Git in the Windows system and see the initial error. Your expectation is `dart` CLI can work without Git, right?

**Comment by 1EDExg0ffyXfTEqdIUAYNZGnCeajIxMWd2vaQeP** [comment]
I haven't installed git beforehand.

My exceptation is that the dart CLI can
1. work without git (as I've shown dart.exe does work, just dart.bat doesn't). 
OR
2. use the git from the mingit folder inside the flutter sdk download.

Either of those is fine for me.

**Comment by christopherfujino** [comment]
> 1. Install flutter

The Flutter SDK requires git, so I think it is reasonable for `dart.bat` to fail if you do not have git installed.

**Comment by 1EDExg0ffyXfTEqdIUAYNZGnCeajIxMWd2vaQeP** [comment]
@christopherfujino If the flutter SDK has git as a prerequisite, why does the download contain another copy if git?

https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_3.16.0-stable.zip has a git installation in `bin/mingw` 

That makes the configuration of a development environment with flutter more confusing, as I now have to keep track of my PATH and what git binaries I'm calling.
