### ISSUE TITLE
[Impeller] Link swiftshader statically into flutter_tester

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#138169]
Right now, `flutter_tester --enable-impeller` is dynamically resolving libvk_swiftshader from the dyld path, but we should be able to link it statically.

When I worked on this I tried static linking initially and had some trouble, so I just did some dynamic linking as we do in other test harnesses. It would be easier for customers downstream (e.g. the framework) if it's linked statically.

/cc @chinmaygarde @bdero @jonahwilliams

**Comment by zanderso** [comment]
Wondering how this will work since it looks like the swiftshader target is hardcoded to be a shared library: https://swiftshader.googlesource.com/SwiftShader.git/+/refs/heads/master/src/Vulkan/BUILD.gn#129

**Comment by dnfield** [comment]
Chinmay and I chatted about this a bit today and we'd need to patch swiftshader to be buildable as a static library, and then patch up the trampoline mechanism in the vulkan loader code to be able to dlsym from the current process.
