### ISSUE TITLE
Error: Error -11814 flutter: Error Message: Cannot Record on ios

### ISSUE THREAD

**Issue by sachinbpatil619** [flutter/flutter#138151]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

working in android but in ios, checked camera permission and everything with latest version of camera package

### Expected results

should open camera

### Actual results

camera not opening, instead getting an error saying 

Error: Error -11814
flutter: │ Error Message: Cannot Record

on snackbar

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by dam-ease** [comment]
Hi @sachinbpatil619. Thanks for filing this. Are you testing with a real device or simulator on iOS? Also, can you create a new flutter project and make use of the example in the camera package to see if this issue reproduces?
If it does, kindly share more information on this issue. More specifically:

- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of flutter 

Thank you!

**Comment by Mairramer** [comment]
@sachinbpatil619 I have the same error, but dont happens all time. Some clients of our app have this error but I am unable to reproduce it.

**Comment by Mairramer** [comment]
@sachinbpatil619 @dam-ease From what I've seen, this error is returned when the device is not connected. Reference [AVError.Code.deviceNotConnected](https://developer.apple.com/documentation/avfoundation/averror/code/devicenotconnected/)
