### ISSUE TITLE
[url_launcher] Provide better error message for `SE_ERR_NOASSOC` (code 31)

### ISSUE THREAD

**Issue by KristijanMitrik** [flutter/flutter#138142]
### Is there an existing issue for this?

- [X] I have searched the [existing package issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Apackage)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### What package does this bug report belong to?

url_launcher

### What target platforms are you seeing this bug on?

Windows

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
[Paste file content here]
```

</details>

### Steps to reproduce

1. launchUrl(
                                  Uri.parse('URL'),
                                  mode: LaunchMode.externalNonBrowserApplication,
                                ),

### Expected results

Launching the url

### Actual results

PlatformException: PlatformException(open_error, Failed to open "URL HERE" ShellExecute error code 31, null, null)

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```
launchUrl(
                                  Uri.parse('URL'),
                                ),
</details>

### Screenshots or Videos

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by stuartmorgan** [comment]
Error code 31 is `SE_ERR_NOASSOC`, meaning there's no handler registered for that URL. We should provide better feedback in that case; most likely we should just return `false`.

**Comment by stuartmorgan** [comment]
We don't have any more information that what is in the error message: the plugin requested (via `ShellExecute`) that the OS open the URL you provided, and got an error in response saying there is no associated handler. Perhaps your default browser has not correctly registered itself as the handler for web URLs, or perhaps there's an issue with the URL itself (you haven't provided the string you are using, so we have less information here than you do).

**Comment by KristijanMitrik** [comment]
@stuartmorgan URL that we try to launch looks something like this `https://appdomain.com/oauth/authorize?client_id=app&response_type=code&code_challenge=pvMiMthjGCumrvqcgCJRd2u_sMedCIqbrf0h0BgcnIU&code_challenge_method=s256`. I can't reproduce the error myself on windows 10 but I see that couple of users encounter this problem in the Sentry logs and all the users are using windows 10. Maybe you see something in the URL that can be a problem?
