### ISSUE TITLE
[url_launcher] Open directory with Cyrillic symbols

### ISSUE THREAD

**Issue by execOQ** [flutter/flutter#138225]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Create folder with Cyrillic and try open this directory through url_launcher. 
Original path is "C:\\Users\\execo\\OneDrive\\Документы\\FollowPhoto", but then Cyrillic symbols starting be replaced with some encoded symbols. Can I do something with it?

### Expected results

Open explorer with directory

### Actual results

Error: 
Could not open file:///C:/Users/execo/OneDrive/%D0%94%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B/FollowPhoto/.

### Code sample

<details><summary>Code sample</summary>

```dart
String path = "C:\\Users\\execo\\OneDrive\\Документы\\FollowPhoto";

final Uri url = Uri.directory(path);

 try {
    await launchUrl(url);
} catch (e) {
    CustomSnackBar(message: 'Could not open $url.').show(context);
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.13.9, on Microsoft Windows [Version 10.0.23580.1000], locale ru-RU)
    • Flutter version 3.13.9 on channel stable at C:\Users\execo\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (2 weeks ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34003.232
    • Windows 10 SDK version 10.0.22621.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.84.1)
    • VS Code at C:\Users\execo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.76.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.23580.1000]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 119.0.6045.124
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 119.0.2151.44

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by stuartmorgan** [comment]
> but then Cyrillic symbols starting be replaced with some encoded symbols

That is `Uri.directory` behaving correctly; a valid URL must percent-encode Unicode characters.

> Can I do something with it?

If Windows doesn't recognize the `file:` URL form of the path as valid, that's a system limitation that is beyond the control of `url_launcher`. Since URLs are the only thing `url_launcher` supports, if URLs don't work for your use case you would need to find or write a different plugin specifically for launching filesystem paths.

**Comment by illogicallogic4** [comment]
@execOQ 
```
launchUrlString('file:///${dirPathUri.toFilePath(windows: Platform.isWindows)}', mode: LaunchMode.externalApplication);
```

**Comment by execOQ** [comment]
@illogicallogic4 That one works! Thank you :)
