### ISSUE TITLE
[flutter_lints] Add avoid_redundant_argument_values

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#138268]
This would help developers immensely to have this in the recommended set. In the design systems study, we found users were writing a bunch of code that reflected the default widget values that were already there.

Enabling the lint for these would help users not write code they don't need to.

**Comment by Piinks** [comment]
@goderbauer WDYT?

**Comment by goderbauer** [comment]
We track suggestions for lints that should be added to core, recommended, or flutter_lints over in the lints repository: https://github.com/dart-lang/lints, see also the README of package:flutter_lints: https://pub.dev/packages/flutter_lints#adding-new-lints

Would you mind opening an issue over there and closing this one? Then, we can discuss the topic over there. Sadly, github isn't allowing me to transfer the issue over. :/

**Comment by Piinks** [comment]
Thanks! Filed https://github.com/dart-lang/lints/issues/170
