### ISSUE TITLE
Icon alignment issue when icon tree shaking is enabled for Flutter Web

### ISSUE THREAD

**Issue by jacobsimionato** [flutter/flutter#138201]
An Google app is having an issue where icons are not aligned properly when icon tree shaking is enabled. This is occurring on Web with the HTML renderer.

Example:
<img width="186" alt="Screenshot 2023-11-10 at 1 21 34 pm" src="https://github.com/flutter/flutter/assets/6869388/12e0cdb9-3bee-46c7-bac0-700c865652a0">

See internal bug b/278484455 for more details and repro instructions.

**Comment by jacobsimionato** [comment]
We originally thought the team was seeing this issue: https://github.com/flutter/flutter/issues/127270, but https://github.com/flutter/flutter/pull/128302 did not fix the issue, sadly.

**Comment by christopherfujino** [comment]
it turns out that https://github.com/flutter/flutter/pull/128302 only fixes the open source workflow, and the internal one requires an additional fix.

**Comment by christopherfujino** [comment]
Closing as the internal bug was resolved
