### ISSUE TITLE
Migration guide from `DataTable` to `TableView.builder`

### ISSUE THREAD

**Issue by FMorschel** [flutter/flutter#138221]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I have a Flutter project that uses a `DataTable` inside two `SingleChildScrollView`s one with the `scrollDirection` set to horizontal and the other to the default vertical `scrollDirection`. 

### Proposal

Now that we have the `TableView` widget with a `TableView.builder` for lazy building, I believe that it would be nice if we had a migration guide on how to best update your code to the new version of the API.

**Comment by huycozy** [comment]
Could tell us the problem you are running into when doing this migration?

**Comment by FMorschel** [comment]
I've struggled to make it so that the table column/row takes the size of the biggest child. 

The most I was able to do, was to make the line/column work like an `Expanded` by using `FractionalTableSpanExtent` inside `TableSpan` in both `rowBuilder` and `columnBuilder`.

But this is not exactly what I wanted because this way I'm limited to my screen size.

**Comment by huycozy** [comment]
Looks like it's a case I'm not sure if it's common or not. If this is an issue with documentation, please file a new one for that. Instead, if you still think there should be a guideline, please be more specific about the content of the migration guide (let's refer to existing migration guides). Thanks!
