### ISSUE TITLE
Problem installing CocoaPods on MacOS

### ISSUE THREAD

**Issue by kaimacuser** [flutter/flutter#138293]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Try to install cocoapods via (macOS Sonoma 14.1.1 on MacBook Air and MacMini):
`sudo gem install cocoapods`

### Actual results

It trys to install cocoapods but runs into an error because the version of ruby, that is delivered with macOS, seems to be too old for installing the latest version of cocoapods.

The solution for me was to install an older version of cocoapods which seems to be based on Ruby 2.6.* (the version macOS ist delivered with). While executing the command I was asked to install a few other things, so the final order was:

1. `sudo gem install drb -v 2.0.5`
2. `sudo gem install activesupport -v 6.1.7.6`
3. `sudo gem install cocoapods -v 1.13.0`

### Logs

<details>
<summary>Logs</summary>

```console

ERROR:  Error installing cocoapods: There are no versions of cocoapods-downloader (>= 2.0) compatible with your Ruby & RubyGems. Maybe try installing an older version of the gem you're looking for? cocoapods-downloader requires Ruby version >= 2.7.4. The current ruby version is 2.6.10.210.

```

</details>

### Flutter Doctor output

Flutter just complained that cocoapods is not installed - which actually wasn't the case

**Comment by ShubhamKNIT** [comment]
While working on flutter I also encountered the same issue recently but was able to tackle it and install cocoapods required for macOS. Can u assign me this issue? I'm sure to help you find the solution.

**Comment by dam-ease** [comment]
Thanks for your input @kaimacuser.
@kaimacuser. Can you try out https://github.com/flutter/flutter/issues/138293#issuecomment-1807079638 to see if it works in your case?

**Comment by kaimacuser** [comment]
Thank you for the quick answer!
I haven't installed brew yet (I should definitely catch up)

I have found an open issue on the [cocoapods GitHub](https://github.com/CocoaPods/CocoaPods/issues/12122)

Their advise was to install a newer version of ruby.

**Comment by ShubhamKNIT** [comment]
Yeah, Let me know if it works for you.
