### ISSUE TITLE
Sub-constructors to wrap every widget

### ISSUE THREAD

**Issue by StefanoV1989** [flutter/flutter#138250]
### Use case

Imagine you are creating a UI as usual, you have a lot of Rows, Columns, and other elements... but you need to space them in your layout.
What's the most common thing to do? Wrap with a Container widget and use the margin or padding option.
Also, if you use a lot of ElevatedButtons, you need to wrap them into a SizedBox if you want to specify the real size.

```
    return Column(
      children: [
        Container(
          margin: const EdgeInsets.only(top: 5),
          child: Text('Hello'),
        ),
        Container(
          margin: const EdgeInsets.only(top: 10),
          child: Text('World'),
        ),
        Container(
          margin: const EdgeInsets.only(top: 15),
          child: Text('How'),
        ),
        Container(
          margin: const EdgeInsets.only(top: 2),
          child: Text('Are'),
        ),
        Container(
          margin: const EdgeInsets.only(top: 6),
          child: Text('You?'),
        ),
        SizedBox(
          height: 50,
          child: ElevatedButton(
            onPressed: () {},
            child: const Text('My button'),
          ),
        )
      ],
    );
```

I currently use a custom widget like this, to wrap my text:

```
  Widget WrappedText({required String child, EdgeInsetsGeometry? margin, TextStyle? style, EdgeInsetsGeometry? padding}) {
    return Container(
      margin: margin,
      padding: padding,
      child: Text(
        child,
        style: style,
      ),
    );
  }
```

But when i need to wrap a lot of things, or i need different props, it's not that easy to customize.

### Proposal

Why don't we use the same method we have for Listview.builder, so sub-constructors, to join widgets and use property in a single place.

I'm going to post the same code as above, but with the sub-constructor syntax i imagine:

```
     return Column(
      children: [
        Text.container(
          margin: const EdgeInsets.only(top: 5),
          child: 'Hello',
        ),
        Text.container(
          margin: const EdgeInsets.only(top: 10),
          child: 'World',
        ),
        Text.container(
          margin: const EdgeInsets.only(top: 15),
          child: 'How',
        ),
        Text.container(
          margin: const EdgeInsets.only(top: 2),
          child: 'Are',
        ),
        Text.container(
          margin: const EdgeInsets.only(top: 6),
          child: 'You?',
        ),
        ElevatedButton.sizedBox(
          height: 50,
          child: Text('My button'),
          onPressed: () {},
        )
      ],
    );
```

So, what i suggest is to make every Widget bindable with others, referring the child property always to the original Widget (Text.container: child is where you put the text. ElevatedButton.sizedBox: child is ElevatedButton's child, etc).
When we have props with same names, we can refer to the original widget property, or create also a "parentProperty".

This would help with long codebases with Container and SizedBox used to space every widget.

Another different way, could be join at the end, this way:
```
   return Column(
      children: [
        Text('Hello').Container(margin: const EdgeInsets.only(top: 5)),
        Text('World').Container(margin: const EdgeInsets.only(top: 10)),
        Text('How').Container(margin: const EdgeInsets.only(top: 15)),
        Text('Are').Container(margin: const EdgeInsets.only(top: 2)),
        Text('You').Container(margin: const EdgeInsets.only(top: 6)),
        ElevatedButton(
            onPressed: () {},
            child: const Text('My button'),
        ).SizedBox(
          height: 50,
        )
      ],
    );
```

How easy become to just add .Container at the end, and even combine with other widgets in this way.

Obviously this is just to make code clean when there are a lot of "spacer". I like the current way to make widgets. This would be a "plus".

**Comment by iapicca** [comment]
@StefanoV1989 
1. you don't need a custom widget, you can just use an extension

```dart
import 'package:flutter/widgets.dart'; /// better keep it non-material

extension ContainerWrapperX on Widget {
  Widget container({
    EdgeInsetsGeometry? margin,
    EdgeInsetsGeometry? padding,
    // ... 
  }) =>
      Container(
        margin: margin,
        padding: padding,
        // ... 
        child: this,
      );
}

```

2. careful setting [TextStyle](https://api.flutter.dev/flutter/painting/TextStyle-class.html) like in your example, this may cause inconsistency with [theming](https://docs.flutter.dev/cookbook/design/themes#create-an-app-theme)

3. I don't think is a good idea to bloat flutter with `helpers`

**Comment by StefanoV1989** [comment]
> @StefanoV1989 
> 1. you don't need a custom widget, you can just use an extension
> 
> ```dart
> import 'package:flutter/widgets.dart'; /// better keep it non-material
> 
> extension ContainerWrapperX on Widget {
>   Widget container({
>     EdgeInsetsGeometry? margin,
>     EdgeInsetsGeometry? padding,
>     // ... 
>   }) =>
>       Container(
>         margin: margin,
>         padding: padding,
>         // ... 
>         child: this,
>       );
> }
> 
> ```
> 
> 2. careful setting [TextStyle](https://api.flutter.dev/flutter/painting/TextStyle-class.html) like in your example, this may cause inconsistency with [theming](https://docs.flutter.dev/cookbook/design/themes#create-an-app-theme)
> 
> 3. I don't think is a good idea to bloat flutter with `helpers`

Oh! I didn't know I could do an extension directly on the Widget! 

Thank you so much, I'm gonna close the topic, since this is a perfect solution for me.
