### ISSUE TITLE
[Impeller] Gaussian blur exhibits banding

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#138259]
In some cases the current implementation of the gaussian blur can manifest banding.  We are working on reworking the blur, this just captures that the old behavior was off sometimes too.

## old gaussian blur (with step 2.0 in fragment shader)
<img width="250" alt="foo" src="https://github.com/flutter/flutter/assets/30870216/b4c5375c-8cef-4016-a879-49aa8f21e087">

Notice the slight vertical banding in the yellow circle.

## [experimental gaussian blur](https://github.com/flutter/engine/pull/47576) (with step 1.0 in fragment shader)
<img width="250" alt="bar" src="https://github.com/flutter/flutter/assets/30870216/af123f3d-d014-4c8d-b7b5-876e8d148b1c">

Notice the differences with what pixels are being sampled at the left and top edges.  It seems like the old algorithm is grabbing more of the black pixels.

## diff

<img width="812" alt="Screenshot 2023-11-10 at 2 37 42 PM" src="https://github.com/flutter/flutter/assets/30870216/7f949984-0ed7-4844-9bfc-05926f54951c">

**Comment by jonahwilliams** [comment]
@gaaclarke assigning to you based on my understanding you are working on this now.
