### ISSUE TITLE
Shader + JS interop demo is broken

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#138366]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Run `flutter build web --wasm` on the sample and host the output (`dhttpd --path=build/web_wasm`)

### Expected results

The app should work, since it runs in the non-wasm mode

### Actual results

```
Failed to fetch and instantiate wasm module: CompileError: WebAssembly.compileStreaming(): supertype count of 3632 exceeds internal limit of 1 @+25
```

### Code sample

https://github.com/johnpryan/web_audio_visualizer/

### Logs

<details><summary>Logs</summary>

```
Failed to fetch and instantiate wasm module: CompileError: WebAssembly.compileStreaming(): supertype count of 3632 exceeds internal limit of 1 @+25
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

main channel

</details>

**Comment by eyebrowsoffire** [comment]
I think this might be the result of version skew. I tried both `flutter build web --wasm` and `flutter build web --wasm --web-renderer=skwasm` and both the wasm modules were able to be instantiated without issue on Chrome 119. It's possible that the hosted wasm module was built with an older version of the flutter framework before dart2wasm was emitting the final WasmGC encodings. @johnpryan could you try this against an updated version of the framework and confirm that it works for you?

**Comment by johnpryan** [comment]
I'm getting some different errors now:

```
manifest.json:8 Manifest: Line: 8, column: 22, Syntax error.
```

```
skwasm.js:8 Uncaught (in promise) ReferenceError: SharedArrayBuffer is not defined
```

The manifest issue seems to be because it's generating extra quotes:

```
    "description": ""A new Flutter project."",
```

**Comment by eyebrowsoffire** [comment]
The `SharedArrayBuffer` issue is that you need to serve your assets with the right CORS headers for Skwasm's multi-threaded rendering to work. You have to serve the html/JS with the following HTTP headers:
```
Cross-Origin-Opener-Policy: same-origin
Cross-Origin-Embedder-Policy: require-corp
```

This is not well documented at the moment. Skwasm is on the bleeding edge.

Not sure abou tthe manifest thing though

**Comment by johnpryan** [comment]
Thanks, I'll close this issue and open one for the manifest issue if I can reproduce it.
