### ISSUE TITLE
LoginPage

### ISSUE THREAD

**Issue by Turrell14** [flutter/flutter#138361]
<-- Please describe your problem here. Be sure to include repro steps. -->
___why is flutter app showing a  white screen on chrome after running it
**DevTools version**: 2.30.0-dev.1
**IDE**: VSCode
**Connected Device**:
CPU / OS: Web windows
Connected app type: Flutter web (debug build)
Dart Version: 3.3.0-120.0.dev
Flutter Version: 3.17.0-5.0.pre.63 / master
Framework / Engine: e33d4b8627 / 828e4dbf66

**Comment by muchirajunior** [comment]
If you create a new app does it display the counter app. Also could you share the flutter doctor output

**Comment by danagbemava-nc** [comment]
Hi @Turrell14, please provide a complete minimal reproducible code sample along with the output of `flutter doctor -v`. 

Please also check your console to see if there are any errors. Lastly, kindly try with the counter app to see if you still experience this issue. 

Thank you

**Comment by Turrell14** [comment]
![image](https://github.com/flutter/flutter/assets/131712404/2ce2c8ae-6ec5-407b-add7-0ab6d34822a9)
![image](https://github.com/flutter/flutter/assets/131712404/42d8d7d9-a54f-4df6-ac27-c9d9896e29cb)
![image](https://github.com/flutter/flutter/assets/131712404/1021d90e-7209-4fe6-aca9-4ee76d63bd3c)

**Comment by danagbemava-nc** [comment]
Hi @Turrell14, please provide the complete code sample in a repository we can clone or in text format. Do not post screenshots of your code. The same goes for the output of flutter doctor -v.

**Comment by Turrell14** [comment]
lib/main.dart
lib/pages/Login_page.dart

**Comment by Turrell14** [comment]
https://github.com/Turrell14/makeup.git

**Comment by danagbemava-nc** [comment]
Hi @Turrell14, this is an issue with your code. 

In your `main.dart` you have created a function with the signature `LoginPage(){}` which is overriding the import of your `LoginPage` widget so the widget never loads. 

You have something similar going in your login_page.dart file where you have a `MySquareTile` function which doesn't return anything where a widget is expected, so you'll need to fix that as well. 

Closing from here as this is an issue with your implementation and not a flutter issue.

**Comment by Turrell14** [comment]
how do I fix it
