### ISSUE TITLE
LongPressGestureRecognizer be interrupted by window switch

### ISSUE THREAD

**Issue by huanghui1998hhh** [flutter/flutter#138394]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [x] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a `Widget` which have a `LongPressGestureRecognizer`
2. Tap down your mouse don't release
3. Then use `alt + Tab` to switch the window
4. Release mouse button
5. Move your mouse out of the flutter window position
6. Come back to flutter window

(My platform is Flutter-web on Windows, but this problem exists on all platform, I think)
And a simple way to check this, is using `Scrollbar`, see code&video below.

### Expected results

`onLongPressCancel` or `onLongPressEnd` need to be called when Flutter window come back.

### Actual results

When i switching window, ongoing `LongPressGestureRecognizer` will be interrupted. It means, it will not call `onLongPressCancel` or `onLongPressEnd`. And then, maybe with some inner state not refresh, the `LongPressGestureRecognizer` will lose it feature.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: SizedBox(
            height: 300,
            child: SingleChildScrollView(
              child: Column(
                children: Colors.primaries
                    .map((e) => Container(
                          height: 100,
                          color: e,
                        ))
                    .toList(),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/65709676/ac13b7b3-4deb-4a19-a684-b43be592c640

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.13.9, on Microsoft Windows [版本 10.0.19045.3570], locale zh-CN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 2022.2)
[√] Connected device (2 available) 
[√] Network resources
```
```console
[!] Flutter (Channel master, 3.16.0-18.0.pre.14, on Microsoft Windows [版本 10.0.19045.3570], locale zh-CN)
    ! Warning: `flutter` on your path resolves to E:\git\flutter\bin\flutter, which is not inside your current Flutter SDK checkout at C:\Users\Admin\fvm\versions\master. Consider adding C:\Users\Admin\fvm\versions\master\bin to the front of your path.
    ! Warning: `dart` on your path resolves to E:\git\flutter\bin\dart, which is not inside your current Flutter SDK checkout at C:\Users\Admin\fvm\versions\master. Consider adding C:\Users\Admin\fvm\versions\master\bin to the front of your path.
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 2022.2)
[√] Connected device (2 available)
[√] Network resources
```

</details>

**Comment by huycozy** [comment]
Hi @huanghui1998hhh 
It's not quite clear from your demo video. Is scrolling not working after returning to flutter window? It would be helpful if you could update the sample code to make the actual result more intuitive.

**Comment by huanghui1998hhh** [comment]
Thanks for your reply @huycozy 

As title said, the essential reason is because `LongPressGestureRecognizer` be interrupted. Like the video shown, i do something strange as mentioned in the steps above. Then when come back to Flutter window, whole feature about `LongPressGestureRecognizer` is not working, but `TapGestureRecognizer` still well (in video, i can use tap gesture to scroll, but longPress can't). Use `Scrollbar` to show this problem just cause `Scrollbar` is very common. 

In my scenes, i'm trying to build a SlideBlockCaptcha, so I use `LongPressGestureRecognizer`, then found this bug.

**Comment by huycozy** [comment]
>whole feature about LongPressGestureRecognizer is not working

What are the symptoms of this? Can't you do long press and  scroll the list?

From my side, when coming back Flutter window, the scrollbar is still working as usual, the list can be scrolled. 

<details>
<summary>Demo video (Windows)</summary>


https://github.com/flutter/flutter/assets/104349824/30fdb5f9-7dc5-4225-a32e-168b16464dda


</details>

**Comment by huanghui1998hhh** [comment]
I recorded a clearer video with explanation.

https://github.com/flutter/flutter/assets/65709676/a0e76cbc-23c1-4ff8-8267-9ad32538cd29

**Comment by huycozy** [comment]
Thanks, I can see the issue now. But it only occurs on Web browsers (Chrome, Edge) on Windows host machine. It is not reproducible on Windows Flutter app. Could you also confirm this on your side?

And the special thing is that it doesn't happen on macOS (macOS Flutter app or Web Flutter app on Chrome/Safari browser there).
