### ISSUE TITLE
same screen rebuilds while navigating 

### ISSUE THREAD

**Issue by akshay-khapare** [flutter/flutter#138334]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [x] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

**I'm using riverpod with gorouter **

### Expected results

navigating to next screen

### Actual results

it rebuilds same screen if  used `GoRouter.of(context).push('/signup');`

and nothing happen if used `ref.read(routerProvider).go('/signup')`

### Code sample

<details><summary>Code sample</summary>

```dart
final authStateChanges = StreamProvider<User?>(
    (ref) => ref.watch(firebaseAuthProvider).authStateChanges());

final routerProvider = Provider<GoRouter>((ref) {
  return GoRouter(
    redirect: (context, state) {
      final loggedIn = ref.watch(authStateChanges).asData?.value != null;

      if (loggedIn) {
        return '/mainScreen';
      }
      return '/';
    },
    routes: [
      GoRoute(
        path: '/',
        builder: (context, state) => const LoginScreen(),
      ),
      GoRoute(
        path: '/mainScreen',
        builder: (context, state) => const MainScreen(),
      ),
      GoRoute(
        path: '/signup',
        builder: (context, state) => const SignupScreen(),
      ),
      GoRoute(
        path: '/profile',
        builder: (context, state) => const ProfileScreen(),
      ),
    ],
  );
});

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/139696100/a11d1fb3-d4d2-4aee-b6a7-5118346b669c

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.9, on Microsoft Windows [Version 10.0.22631.2506], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.27)
[√] Android Studio (version 2022.2)
[√] VS Code (version 1.84.2)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
```

</details>

**Comment by Puspharaj** [comment]
This is happens with go routing pushNamed. When textfield at the next routing page. The whole page gets reloads.

Not sure how to stop.

**Comment by huycozy** [comment]
Hi @akshay-khapare (and also cc @Puspharaj)
The goal of this Github repo is not to give assistance on personal code or the whole package/plugin project, but to improve flutter reporting bugs or feature requests.

It seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any. 

If you still believe this is a Flutter framework or first-party package (go_router) bug, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that represents the problem.
