### ISSUE TITLE
Missing call registerWith() function in the dart_plugin_registrant.dart

### ISSUE THREAD

**Issue by zr6328** [flutter/flutter#138384]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

none

### Expected results

none

### Actual results

none

### Code sample

#pubspec.yaml
```
dependences:
audioplayers: ^1.0.0
myAudioPlayers: ^1.0.0
```
the myAudioPlayers is a plugin that based on the audioplayers. its pubspec.yaml is shown as this:
`
plugin:
implements: audioplayers
platforms:
linux:
dartPluginClass: AudioplayerPlugin
`

when i run flutter build linux, the registerWith() is not called in the dart_plugin_registrant.dart

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

none

**Comment by stuartmorgan** [comment]
> ### Steps to reproduce
> none

Without steps to reproduce, this is not actionable; closing accordingly. If you would like us to investigate, please file a new issue and fill out the template completely.
