### ISSUE TITLE
TextFormField is not focused when tapping it again after entering Japanese characters without pressing done but closing keyboard

### ISSUE THREAD

**Issue by shm40** [flutter/flutter#138395]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Add a Japanese Keyboard to your iPad
2. Run the below code sample
3. Enter あいう (these are Japanese characters) on TextFormField A
4. Tap the right bottom button on the keyboard 
5. Tap TextFormField A again
6. Enter あいう (but nothing reflects on TextFormField A)

I am testing this on iPad Air third generation on iPad OS 16.6.1.

### Expected results

Without even tapping the done button on the keyboard, any Japanese characters can be reflected after opening the keyboard again.

### Actual results

Any Japanese characters cannot be reflected on TextFormFiled after hiding the keyboard from the right bottom button.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          TextFormField(
            decoration: const InputDecoration(labelText: 'TextFormField A'),
          ),
          TextFormField(
            decoration: const InputDecoration(labelText: 'TextFormField B'),
          ),
        ],
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/125345277/475d5f22-56eb-4655-a6aa-f2efab296f8b

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.9, on macOS 13.4.1 22F770820d darwin-x64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.84.2)
[✓] Connected device (3 available)
[✓] Network resources
```

</details>

**Comment by shm40** [comment]
@dam-ease 
Thanks for trying this issue if it can reproduce.
When I tried this case on the Simulator, there was no problem. But when I use the physical device, it happens.
Could you please try not on the Simulator but the physical device if you have any?

**Comment by shm40** [comment]
Thanks for testing on the physical device but iPhone.
I also tested on my iPhone X but it seems that the issue happens only on the physical iPad device.

I really hope that anyone who has a physical iPad device could test this case.
Thanks.

**Comment by zhouzhuo810** [comment]
> Thanks for testing on the physical device but iPhone. I also tested on my iPhone X but it seems that the issue happens only on the physical iPad device.
> 
> I really hope that anyone who has a physical iPad device could test this case. Thanks.

I also encountered this issue, my device is an iPad (9th generation) [#141546](https://github.com/flutter/flutter/issues/141546)

**Comment by wanjm** [comment]
I have encoutered this too in https://github.com/flutter/flutter/issues/142294 and https://github.com/flutter/flutter/issues/142437; 
and operate sequence is exactly the same;  when reproduce you should use the bottom-right key instead of the done/enter key; 
it can be reproduced with iPad of 15.X and 16.X using flutter 3.13 and above ;  flutter 3.10 had no such problem;
iPad 17 had no such problem;

**Comment by wanjm** [comment]
@huycozy @dam-ease @danagbemava-nc I hope you can find a physical device to help reproduce it; and hope we can make some progress; 

Please!

**Comment by shm40** [comment]
I tested this issue on Flutter 3.19.2 but could not reproduce so it might be fixed through Flutter upgrade.

@wanjm I hope you can test the same issue where it could be reproduced and report the result.

**Comment by hohoins** [comment]
The same problem can be reproduced in flutter 3.19.2. Please check and respond.
https://github.com/flutter/flutter/issues/144768

**Comment by hohoins** [comment]
@shm40 @dam-ease 
This problem is currently being reproduced in flutte 3.19.2.
It can be reproduced on the actual iPad device.
The keyboard can be reproduced by setting it to Japanese (romaji).

If this problem occurs once, the app will malfunction from then on until you run the app again.
As an example, even after moving to another screen, the keyboard is displayed when you touch the screen.

The problem is serious. Once this happens, it becomes difficult to use the App anymore.
It definitely needs correction.
I hope this will be fixed in the next version of Flutter.

Please respond to the issue.

**Comment by sanghyuk-nam** [comment]
I was able to reproduce it by pressing the hide button at the bottom right of the iPad software keyboard.
![image-1](https://github.com/flutter/flutter/assets/116542772/6e5a4506-ddec-45b3-933b-c5d7145df935)

**Comment by hohoins** [comment]
> I was able to reproduce it by pressing the hide button at the bottom right of the iPad software keyboard. ![image-1](https://private-user-images.githubusercontent.com/116542772/312440579-6e5a4506-ddec-45b3-933b-c5d7145df935.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzODM5MTgsIm5iZiI6MTcxMDM4MzYxOCwicGF0aCI6Ii8xMTY1NDI3NzIvMzEyNDQwNTc5LTZlNWE0NTA2LWRkZWMtNDViMy05MzNiLWM1ZDcxNDVkZjkzNS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTRUMDIzMzM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODg3NjYyMmRhYjEzODVmNTEzMGViYjMyYWIwYmIzNGM0NTYzZDg0YWMxMTRhNzYzZDJlNzg0MTUwMzU5MDg4YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EsJDWEBScW-SyKS6qrOUpLoeruCdcA60jFV73Quq-Dc)

you're right. Same in my case.
  This was reproduced when I pressed the keyboard down button located at the bottom right of the keyboard.

**Comment by wanjm** [comment]
@hohoins @sanghyuk-nam @shm40 please thumbs the first post, and try to make it be noticeable;

**Comment by hohoins** [comment]
https://github.com/flutter/flutter/assets/3438181/29e00bf0-0c84-4601-b817-2ef90422b4fa

**Comment by shm40** [comment]
@hohoins 
Thanks for your reports.
I tested this issue with your sample code on iPad Airt 3rd gen with iPad OS 17.3.1 but could not reproduce it.

It seems that your iPad OS Version is older than me.
Could you please test the issue again after upgrading the iPad OS version?


https://github.com/flutter/flutter/assets/125345277/c3cd72be-d52d-4a16-8148-0ae4e5ca0f9f

**Comment by hohoins** [comment]
> @hohoins Thanks for your reports. I tested this issue with your sample code on iPad Airt 3rd gen with iPad OS 17.3.1 but could not reproduce it.
> 
> It seems that your iPad OS Version is older than me. Could you please test the issue again after upgrading the iPad OS version?
> 
>  b8a3584d-74ec-4753-9932-f4f87867f09e.mp4

Thank you for your interest in this bug.
I will try to reproduce it again by updating iPad OS.
I will contact you.
thank you
👍👍👍👍👍👍👍

**Comment by hohoins** [comment]
@shm40 

I upgraded to iOS 17.4.1 on my iPad.
After the upgrade, it seems that it cannot be reproduced by simply opening and closing the keyboard.
👍👍👍👍👍 

But if I change the way I reproduce it, it's still possible.
If you need to register a new issue, please contact me.
A reproduction video is attached.

How to reproduce:
1. Enter a few characters of text in TextField
2. Select a letter by long pressing it in the TextField
3. Press the back button on the keyboard to delete a letter
4. Close the keyboard with the down button at the bottom right of the keyboard.
5. TextField does not respond when touched

If reproduction is not possible, repeat the above process.
In my case, it was possible to reproduce it within 10 times.
If I put my mind to it, I can 100% reproduce it.

https://github.com/flutter/flutter/assets/3438181/5c3d5f83-677c-4f7e-a3eb-62eb7bee71ed

**Comment by LongCatIsLooong** [comment]
I tried this on a device with an older version of iPadOS (13.3), and iOS17.2 simulator. The bug is not reproducible on either of them. It looks like this isn't reproducible on iOS 17+ devices so I'll close this one as not reproducible anymore. 

@hohoins I'm not able to reproduce the other bug either, could you create a new issue for this?

**Comment by hohoins** [comment]
@LongCatIsLooong @shm40 
The issue has been closed.
But it didn't solve the TextField issue.
This issue is still reproducible in the latest version.
It even has nothing to do with keyboard language settings.
I plan to register this phenomenon as a separate issue.
thank you

**Comment by wanjm** [comment]
@hohoins  where is your new issue;

**Comment by hohoins** [comment]
> wanjm

Thank you for contacting me.
The newly created issue is here.
https://github.com/flutter/flutter/issues/145751
