### ISSUE TITLE
Changes to dialogs cannot be hot reloaded

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#13831]
## Steps to Reproduce

1. Create an app with the following main.dart:
```dart
import 'package:flutter/material.dart';

void main() => runApp(
      new MaterialApp(
        home: new Scaffold(
          appBar: new AppBar(
            title: new Text('Test app'),
          ),
          body: new MyHome(),
        ),
      ),
    );

class MyHome extends StatefulWidget {
  const MyHome({Key key}) : super(key: key);

  @override
  MyHomeState createState() => new MyHomeState();
}

class MyHomeState extends State<MyHome> {
  @override
  Widget build(BuildContext context) {
    return new Center(
      child: new RaisedButton(
        child: new Text('Click me 2'),
        onPressed: () {
          showDialog(
            context: context,
            child: new AlertDialog(
              title: new Text("My dialog"),
              content: new Text("Hi from dialog 2"),
            ),
          );
        },
      ),
    );
  }
}
```
Run it.

* Change `Click me` to `Click me2`. Hot reload. => Screen is updated.

* Change `Hi from dialog` to `Hi from dialog2`. Hot reload. => Screen is not updated.

**Comment by Hixie** [comment]
This is working as expected (hot reload doesn't re-run code, it just updates code that would normally run, then marks everything dirty). You can work around this by using a custom widget instead of `AlertDialog`, then having that custom widget build an `AlertDialog`. Your custom widget will be rebuilt, which will then let you do whatever you want from hot reload.

**Comment by Hixie** [comment]
(This is exactly the same reason why `main` doesn't re-run and thus why changes in the call to `runApp` don't hot reload.)

**Comment by mit-mit** [comment]
Ah, yes, that makes sense!
