### ISSUE TITLE
For plugin cupertino_icons. The image in README is not found on pub site.

### ISSUE THREAD

**Issue by asaarnak** [flutter/flutter#13833]
See:
https://pub.dartlang.org/packages/cupertino_icons
 
Error in console logs: 
GET https://pub.dartlang.org/packages/map.png 404 ()

**Comment by xster** [comment]
https://github.com/flutter/cupertino_icons/commit/669d3f051435d6073fe1524f926031c9c02c327d

**Comment by xster** [comment]
Will need to republish. In the meantime, you can look at the same readme in https://github.com/flutter/cupertino_icons directly

**Comment by xster** [comment]
Should work now
