### ISSUE TITLE
engine embedder glfw examples not update

### ISSUE THREAD

**Issue by hongeSunCoder** [flutter/flutter#138340]
The cmake glfw directory path did not update after moving //third_party/glfw to //flutter/third_party/glfw.

**Comment by dam-ease** [comment]
Thanks for filing this!
I see this seems similar/ related to https://github.com/flutter/flutter/issues/136284 which was fixed recently, can you please check this out?
If not, kindly provide more information on this so this issue can be workable, thank you!

**Comment by hongeSunCoder** [comment]
> Thanks for filing this! I see this seems similar/ related to #136284 which was fixed recently, can you please check this out? If not, kindly provide more information on this so this issue can be workable, thank you!

hi, yes, I checked that fix,  this  one is a different issue, and I've just create a PR to fix.
