### ISSUE TITLE
Upgrade gradle to fix security vulnerabilities

### ISSUE THREAD

**Issue by ZorinFoss** [flutter/flutter#138336]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Hi,

The current gradle version in `flutter v3.13.9` is `7.6.1` which contain security vulnerabilities.

### Proposal

Upgrade gradle to `v7.6.3` or even `v8.4` if it possible

**Comment by reidbaker** [comment]
Can you elaborate on the security risk so we can understand the urgency?

**Comment by ZorinFoss** [comment]
Greadle `v7.6.3`

 fix these security vulnerabilities:

[Incorrect permission assignment for symlinked files used in copy or archiving operations](https://github.com/gradle/gradle/security/advisories/GHSA-43r3-pqhv-f7h9)
[Possible local text file exfiltration by XML External entity injection](https://github.com/gradle/gradle/security/advisories/GHSA-mrff-q8qj-xvg8)

It also fixes the following issues:

https://github.com/gradle/gradle/issues/25781 Backport finalized task performance fix to 7.6.x
https://github.com/gradle/gradle/issues/25802 Backport cgroups fix to 7.6.x

Gradle `v7.6.2` 

fix these security vulnerabilities:

[Dependency cache path traversal](https://github.com/gradle/gradle/security/advisories/GHSA-2h6c-rv6q-494v)
[Path traversal vulnerabilities in handling of Tar archives](https://github.com/gradle/gradle/security/advisories/GHSA-84mw-qh6q-v842)

It also fixes the following issues:

https://github.com/gradle/gradle/issues/23201 Backport dependency upgrades to 7.x
https://github.com/gradle/gradle/issues/23202 Backport Scala incremental compilation fixes
https://github.com/gradle/gradle/issues/23325 Backport JSoup update to resolve https://github.com/advisories/GHSA-gp7f-rwcx-9369
https://github.com/gradle/gradle/issues/23458 Backport JUnit5 dynamic test logging bug fix
https://github.com/gradle/gradle/issues/23681 Dependency graph resolution: Equivalent excludes can cause un-necessary graph mutations [backport 7.x]
https://github.com/gradle/gradle/issues/23922 Backport "Use Compiler API data for incremental compilation after a failure" to 7.x
https://github.com/gradle/gradle/issues/23951 Exclude rule merging: missing optimization [Backport 7.x]
https://github.com/gradle/gradle/issues/24132 Extending an already resolved configuration no longer works correctly [backport 7.x]
https://github.com/gradle/gradle/issues/24234 7.6.1 breaks gradle-consistent-versions
https://github.com/gradle/gradle/issues/24390 Gradle 7.4 fails on multi release jar's with JDK 19 code
https://github.com/gradle/gradle/issues/24439 Gradle complains about invalid tool chain - picking up the source package location - it should just ignore them [Backport]
https://github.com/gradle/gradle/issues/24443 Maven artifact referenced only in dependency constraints raises IllegalStateException: Corrupt serialized resolution result [backport]
https://github.com/gradle/gradle/issues/24901 Backport fix for test exception that cannot be deserialized to 7.x

**Comment by camsim99** [comment]
Fixed by https://github.com/flutter/packages/pull/5522 and https://github.com/flutter/flutter/pull/139276!
