### ISSUE TITLE
Flutter tool extensibility support

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#13834]
It's not sustainable for the `flutter` tool to support all the commands that all developers collectively desire. It's much more sustainable to support an extensibility model where the tool itself can be extended by adding in "tools plugins". 

* Run Dart commend / do codegen: https://github.com/flutter/flutter/issues/13607
* Generate app icon: https://github.com/flutter/flutter/issues/10387
* Determining the size of an app: https://github.com/flutter/flutter/issues/13189
* Customize the build: https://github.com/flutter/flutter/issues/9870

**Comment by fmatosqg** [comment]
I'd like to see some specs that would allow me to do code generation before build starts. 
My proposal is adding a line to pubspec, something like this:
```
hooks:
  hookFolder/hookScript.dart hookParameter1 hookParameter2
```

and preferrably extensible to packages in some shape or form, but I'd be happy to develop based on the above spec to kick it off.

**Comment by fmatosqg** [comment]
I get the feeling that this `pub ... watch` thing is popular, although very new to me. And my guess is that it could solve the problem with first class support to both `build_runner` and `watch` so they can integrate seamlessly with `flutter run`
ref 14703.

**Comment by eseidelGoogle** [comment]
Related: https://github.com/flutter/flutter/issues/16603 https://github.com/flutter/flutter/issues/15545 https://github.com/flutter/flutter/issues/20865

**Comment by tvolkert** [comment]
Closing as a dup of https://github.com/flutter/flutter/issues/25377

**Comment by stuz5000** [comment]
Crazy question -- it seems like a lot of uses of annotations could be support be the language itself, rather that making dependencies on specific build tool (e.g. annotations macros that take a class and return a class, or take a function and return a function). Any plans to support this in the future?

**Comment by Levi-Lesches** [comment]
@stuz5000 While I completely agree with you, I think that's probably a better issue for the `dart-lang/lang` repo, where work for Dart itself (not to be confused with Flutter, that uses Dart) is done.
