### ISSUE TITLE
Can we add Google logo to Icons?

### ISSUE THREAD

**Issue by under3415** [flutter/flutter#138308]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

There are icons for Facebook (Icons.facebook), Apple (icons.Apple) and even Microrsoft (Icons.window), but there is no icon for Google!? For some reason there is Google translate icon (Icons.g_translate) and something called Icons.g_mobiledata that has letter G but is smaller and different looking so could be confusing and looks ugly.

Can we please add Google logo icon so that we don't have to include another font just for this!

### Proposal

Have a Google logo icon in Icons that ship with Flutter

**Comment by rituparna-ui** [comment]
The irony is Google is the maintainer of Flutter.

**Comment by dam-ease** [comment]
Thanks for proposing this. Per https://github.com/flutter/flutter/issues/102964#issuecomment-1116000787, the icons added are generally the ones that are available on the Google Fonts site.

I see there is a similar Icon request there https://github.com/google/material-design-icons/issues/1521. You can upvote and follow up on this request for updates or you can create a custom SVG and use https://www.fluttericon.com/ to generate an icon suitable for your project.

I'm going to have to close this issue as unactionable for now.

Thank you
