### ISSUE TITLE
Wonderous gets frozen after adding an item to the collection

### ISSUE THREAD

**Issue by DiegoGW** [flutter/flutter#138373]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Get latest version of Wonderous app (commit 5d7f14fd17038c8bdd3a75ce8cf3e6200728c54d (HEAD -> main, origin/main, origin/HEAD)
Author: Shawn <shawn@gskinner.com>
Date:   Fri Nov 3 14:30:05 2023 -0600
    Fix centering issue in photo gallery with hidden collectibles )
2. Run Wonderous in XCode (target: iphone 14 pro + iOS17.1.1) so that it is installed from scratch
3. Navigate to the Great Wall (Navigate to: /wonder/greatWall?t=0)
4. Check that you cannot enter this wonder after a couple of taps
5. Once you are in the Great Wall scroll down until the bottom of the page
6. Add the collectible item
7. Check that the app gets frozen and following error is logged:

```
-[MTLDebugBlitCommandEncoder internalValidateCopyFromTexture:sourceSlice:sourceLevel:sourceOrigin:sourceSize:toTexture:destinationSlice:destinationLevel:destinationOrigin:options:]:388: failed assertion `Copy From Texture Validation
[sourceTexture pixelFormat](MTLPixelFormatBGRA8Unorm) must be compatible with [destinationTexture pixelFormat](MTLPixelFormatRGBA16Float).
'
```

### Expected results

Collectible item should be added without errors

### Actual results

1. You need to tap a couple of times until you can navigate through the Great Wall wonder (Navigate to: /wonder/greatWall?t=0)
2. Once you add the collecitble item, the following error is returned: 
```
-[MTLDebugBlitCommandEncoder internalValidateCopyFromTexture:sourceSlice:sourceLevel:sourceOrigin:sourceSize:toTexture:destinationSlice:destinationLevel:destinationOrigin:options:]:388: failed assertion `Copy From Texture Validation
[sourceTexture pixelFormat](MTLPixelFormatBGRA8Unorm) must be compatible with [destinationTexture pixelFormat](MTLPixelFormatRGBA16Float).
'
```

### Code sample

<details><summary>Code sample</summary>

```
git clone https://github.com/gskinnerTeam/flutter-wonderous-app.git
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

<img width="1430" alt="Screenshot 2023-11-13 at 6 21 51 PM" src="https://github.com/flutter/flutter/assets/11681325/8a7d9b32-a4fe-4035-b161-5770379a3fee">

Video:
https://drive.google.com/file/d/1zvFLrlH9zEFgt2JV5rJ7EMbOMLs888iw/view?usp=sharing 

</details>

### Logs

<details><summary>Logs</summary>

```console
-[MTLDebugBlitCommandEncoder internalValidateCopyFromTexture:sourceSlice:sourceLevel:sourceOrigin:sourceSize:toTexture:destinationSlice:destinationLevel:destinationOrigin:options:]:388: failed assertion `Copy From Texture Validation
[sourceTexture pixelFormat](MTLPixelFormatBGRA8Unorm) must be compatible with [destinationTexture pixelFormat](MTLPixelFormatRGBA16Float).
'
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.17.0-5.0.pre.71, on macOS 14.1 23B74 darwin-arm64, locale en-US)
    • Flutter version 3.17.0-5.0.pre.71 on channel master at /Users/diegogawenda/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5980342ead (2 hours ago), 2023-11-13 14:31:12 -0500
    • Engine revision db6da000a1
    • Dart version 3.3.0 (build 3.3.0-120.0.dev)
    • DevTools version 2.30.0-dev.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/diegogawenda/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/diegogawenda/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/diegogawenda/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.83.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (3 available)
    • Somnio’s iPhone (mobile) • 00008120-001168D83C87C01E • ios            • iOS 17.1.1 21B91
    • macOS (desktop)          • macos                     • darwin-arm64   • macOS 14.1 23B74 darwin-arm64
    • Chrome (web)             • chrome                    • web-javascript • Google Chrome 119.0.6045.123

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by jonahwilliams** [comment]
The problem here is that if the onscreen surface format is wide gamut and the offscreen format is not, then we can't blit that onto the onscreen and instead need to fall back to a draw. I think we can handle this in EntityPass
