### ISSUE TITLE
Flutter ecosystem needs supported, high-performance, idiomatic crypto library

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#13846]
There are some libraries that exist but they are not maintained.

(Filing this bug to track us ensuring this is available; it doesn't necessarily have to be implemented by the Flutter or Dart teams nor does it necessarily have to ship with those products, it just needs to be available and supported/maintained.)

**Comment by bhauj** [comment]
Any current package is not having 100% score and using them in commercialization products looks to be risky. Is there any deadline for this?

**Comment by dcharkes** [comment]
cc @jonasfj

**Comment by stuartmorgan** [comment]
Closing in favor of https://github.com/dart-lang/sdk/issues/50290.
