### ISSUE TITLE
URL launcher close event

### ISSUE THREAD

**Issue by Cha195** [flutter/flutter#138405]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Could there be a way to listen to a close event for `inAppBrowserView` mode?
Currently, I set a boolean value post launch and make use of the `LifecycleEventHandler` `resumeCallBack` to call some functions (such as reload of the app).

### Proposal

There could be a way to make the code more robust by having a close event from the package itself to listen to close of `inAppWebview` and `inAppBrowserView`

**Comment by dam-ease** [comment]
Hi @Cha195. Thanks for proposing this. 
This seems similar/related to https://github.com/flutter/flutter/issues/57536 which per this https://github.com/flutter/flutter/issues/57536#issuecomment-1627772809, the plugin has no access to information about what happens after the URL is launched. Hence, this doesn't seem to be feasible.

Closing based on this
Thank you!
