### ISSUE TITLE
Dart rolls to the Engine blocked on Framework test error

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#138413]
Starting with the Engine roll here https://github.com/flutter/flutter/pull/138389

Engine rolls to the framework started failing like this: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20framework_tests_slow/23089/overview

```
00:09 +1 -1: /b/s/w/ir/x/w/flutter/dev/tracing_tests/test/image_cache_tracing_test.dart: (setUpAll) [E]                                                                                                
  Unsupported operation: Mocked response
  dart:async                                        new Future.error
  package:flutter_test/src/_binding_io.dart 313:12  _MockHttpResponse.detachSocket
  ===== asynchronous gap ===========================
  dart:_http                                        WebSocket.connect
  package:vm_service/vm_service_io.dart 26:44       vmServiceConnectUriWithFactory
  package:vm_service/vm_service_io.dart 12:10       vmServiceConnectUri
  test/common.dart 27:24                            initTimelineTests.<fn>
  ===== asynchronous gap ===========================
  dart:async                                        _CustomZone.registerUnaryCallback
  test/common.dart 23:48                            initTimelineTests.<fn>
  
Warning: At least one test in this suite creates an HttpClient. When running a test suite that uses
TestWidgetsFlutterBinding, all HTTP requests will return status code 400, and no network request
will actually be made. Any test expecting a real network connection and status code will fail.
To test code that needs an HttpClient, provide your own HttpClient implementation to the code under
test, so that your test can consistently provide a testable response to the code under test.
```

The Engine roll contained only a Dart roll here: https://github.com/flutter/engine/pull/48006 with commits https://dart.googlesource.com/sdk.git/+log/6219f11bf0fb..b3d3b381fd7b.

The change here https://dart.googlesource.com/sdk.git/+/92e7989fbcf0296231df34925f4333d124b30138 looks related cc @brianquinlan 

I reverted the Dart roll and stopped the Dart -> Engine roller, but marking this P0 to get the Dart -> Engine roll restarted.

**Comment by brianquinlan** [comment]
Yes, that change is very likely the cause - it modifies `WebSocket` to honor `HttpOverrides`.

It looks like [Flutter mocks `HttpClient`](https://github.com/flutter/flutter/blob/463c02daafa50c15cb79e1e2caee38062af01682/packages/flutter_test/lib/src/_binding_io.dart#L74) and this messes with the `WebSocket` used as part of the VmService implementation.

I'll revert the change.

**Comment by TahaTesser** [comment]
@zanderso 
Is this related? https://github.com/flutter/flutter/pull/135855#issuecomment-1810633213

**Comment by brianquinlan** [comment]
https://dart.googlesource.com/sdk.git/+/92e7989fbcf0296231df34925f4333d124b30138  reverted

**Comment by zanderso** [comment]
@TahaTesser probably not. The roll being discussed in this issue never landed in the framework repo.

**Comment by brianquinlan** [comment]
Dev has picked up the change and the roll has been resumed.
