### ISSUE TITLE
Where's the documentation for the new Releases API?

### ISSUE THREAD

**Issue by coolaj86** [flutter/flutter#138422]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

The old release URLs were:
- https://storage.googleapis.com/flutter_infra/releases/releases_macos.json
- https://storage.googleapis.com/flutter_infra/releases/releases_linux.json
- https://storage.googleapis.com/flutter_infra/releases/releases_windows.json

I don't remember where I found that documented, but those URLs are no longer being updated (still at v2.2.1) and I can't find the docs with the updated URLs.

P.S. I'm the primary maintainer of https://webistall.dev/ and I just released that our release info for flutter (<https://webistall.dev/flutter>) is waaaaaaaay out of date.

### Actual results

Getting v2.2.1 as the latest.

### Logs

Places I've looked to find reference to the releases API or a "see all releases" type of link:

- https://docs.flutter.dev/release/archive?tab=windows
- https://github.com/flutter/flutter/wiki/Flutter-Installation-Bundles
- https://github.com/flutter/flutter/wiki/Flutter-build-release-channels
- https://github.com/flutter/flutter/wiki/Release-process

### Flutter Doctor output

N/A

**Comment by stuartmorgan** [comment]
The storage bucket changed from `flutter_infra` to `flutter_infra_release`; see https://github.com/flutter/flutter/issues/75363. The json URLs you were using just need to be updated accordingly.

**Comment by coolaj86** [comment]
@stuartmorgan Thanks. Where's the official documentation for that so that I can reference it again in the future if needed?

**Comment by stuartmorgan** [comment]
Offhand, I'm not aware of any documentation of the internals of our artifact management.

**Comment by coolaj86** [comment]
It might seem like a silly thing, but we also automate the download, extract, and add-to-`PATH` process for Node, Go, Zig, Rust, Sass, Deno, Bun, PowerShell, and another hundred+ lesser known tools and they all provide a public release API or publicly documented script for automation - granted, for about 90% its either GithHub Releases or just git tags, but still.

So where I'm coming from it's a very normal thing.

Anyway, I appreciate the quick response and I'm glad we got it documented here for anyone else that's doing install management.
