### ISSUE TITLE
implementation Android `Presentation` API for show Flutter Widget in a second screen

### ISSUE THREAD

**Issue by elliotPopina** [flutter/flutter#138410]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

On Android in Kotlin we have access to the `Presentation` class which allows us to display UI components on a second screen (before we need to recover a `Display`). 
On Flutter we have no equivalent, it would be really great to have the same possibility

https://developer.android.com/reference/kotlin/android/app/Presentation

### Proposal

With a plugin we are able to retrieve the connected screens and display native views. I also tried to launch a second Flutter Engine on a native view which extends `Presentation` but this very quickly becomes complex and even more so to communicate information between the 2 engines. **It would be much better to have the possibility of building a Widget directly by telling it which screen to use**

**Comment by elliotPopina** [comment]
my bad, i just found this issue for the same problem: [#134405](https://github.com/flutter/flutter/issues/134405)

**Comment by dam-ease** [comment]
Thanks for filing this @elliotPopina.
I see this is similar to https://github.com/flutter/flutter/issues/134405. Closing this in favour of the already existing issue. 
Kindly upvote, comment and follow up on that issue for updates.
Thank you!
