### ISSUE TITLE
[CP][ios17][text_input]fix ios 17.0 keyboard freeze when switching languages

### ISSUE THREAD

**Issue by hellohuanlin** [flutter/flutter#138440]
### Issue Link

https://github.com/flutter/flutter/issues/134716

### Commit Hash

ffcc5bf

### Target

beta

### PR Link

https://github.com/flutter/engine/pull/48041

### Changelog Description

Fix ios 17.0 keyboard freeze when switching languages

### Impacted Users

all iOS end-customers under iOS 17.0

### Impact Description

This affects all flutter apps with text inputs (e.g. text field) on iOS 17.0.

It's been fixed in iOS 17.1 by Apple a few weeks ago, but there are still many users in iOS 17.0, so we need this CP for those users

### Workaround

No workaround

### Risk

low

### Test Coverage

yes

### Validation Steps

Repro steps in https://github.com/flutter/flutter/issues/134716

**Comment by hellohuanlin** [comment]
This needs CP to both the previous stable (https://github.com/flutter/flutter/issues/138439) and the new beta (https://github.com/flutter/flutter/issues/138440)

**Comment by stuartmorgan** [comment]
This has my approval for cherry-picking.

**Comment by hellohuanlin** [comment]
i believe this is already done.
