### ISSUE TITLE
[webview_flutter] Is there a way to launch a url in a webview using Microsoft edge rendering engine? 

### ISSUE THREAD

**Issue by JohnSamy11** [flutter/flutter#138414]
### Is there an existing issue for this?

- [X] I have searched the [existing package issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Apackage)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### What package does this bug report belong to?

webview_flutter

### What target platforms are you seeing this bug on?

Android, iOS

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
[Paste file content here]
```

</details>

### Steps to reproduce

Trying to launch a url using the webview_flutter package while this url is limited to work only on Microsoft Edge browser as company regulations and limitations by conditional access. 

### Expected results

A method to chose the render engine (Microsoft edge) or like a normal web page that behaves as if it is on Microsoft edge browser without leaving the app.

### Actual results

web page saying: blocked by conditional access.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Videos

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[[✓] Flutter (Channel stable, 3.13.8, on macOS 14.0 23A344 darwin-arm64, locale en-EG)
    • Flutter version 3.13.8 on channel stable at /Users/johnsamy/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6c4930c4ac (4 weeks ago), 2023-10-18 10:57:55 -0500
    • Engine revision 767d8c75e8
    • Dart version 3.1.4
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/johnsamy/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/johnsamy/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • John’s iPhone (mobile) • 00008110-001159E10208401E • ios            • iOS 17.1.1 21B91
    • macOS (desktop)        • macos                     • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 119.0.6045.123

[✓] Network resources
    • All expected network resources are available.

• No issues found!
]
```

</details>

**Comment by stuartmorgan** [comment]
`webview_flutter` wraps the OS-provided webviews, which do not provide renderer selection. If you want to bundle an entire rendering engine with your application, you would need to do that via a third-party plugin.

Note though that Edge is a browser, not a rendering engine; if the site requires the Edge browser then by definition you cannot access it with an application that you build, because that won't be Edge. If you mean the `EdgeHTML` rendering engine that hasn't been updated since 2020, it only exists on Windows. Either way, you will not be able to build an application for either Android or iOS (whether you use Flutter or not) that meets the regulations you've described.
