### ISSUE TITLE
[iOS] Keyboard stuck and text editor is unfocused when app is taken to background and then to foreground 

### ISSUE THREAD

**Issue by prateekrk** [flutter/flutter#138403]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Have a TextField widget
2. Open another app for ex. notepad and start editing, so that the keyboard appears
3. Click on home then open your app from the launch screen
4. Repeat the above steps

**Note**. I was able to reproduce this consistently, on avg 15-20 tries.

I had the similar kind of issue previously which i have raised here [https://github.com/flutter/flutter/issues/131840](https://github.com/flutter/flutter/issues/131840). As per suggest i upgraded the flutter.

### Expected results

1. Keyboard should not be glued to the screen if textfield is not focused and other way around

### Actual results

1. The Keyboard is glued to the screen of the app, even when clicking back from the navigator and moving to the previous screen this keyboard does not closed.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const LandingPage(title: 'Page 1'),
    );
  }
}

class LandingPage extends StatefulWidget {
  const LandingPage({super.key, required this.title});
  final String title;

  @override
  State<LandingPage> createState() => _LandingPage();
}

class _LandingPage extends State<LandingPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        backgroundColor: Colors.white,
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: Center(
            child: Container(
          padding: const EdgeInsets.all(10),
          child: OutlinedButton(
              onPressed: () {
                Navigator.push(
                    context,
                    MaterialPageRoute(
                        builder: ((context) =>
                            const MyHomePage(title: "Page 2"))));
              },
              child: const Text("Go to next screen")),
        )));
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> with WidgetsBindingObserver {
  @override
  void initState() {
    WidgetsBinding.instance.addObserver(this);
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        backgroundColor: Colors.white,
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: Center(
            child: Container(
          padding: const EdgeInsets.all(10),
          child: TextField(
            autofocus: true,
            textInputAction: TextInputAction.search,
            onSubmitted: (value) => {print(value)},
          ),
        )));
  }
}

``` 

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![flutter-keyboard-issue](https://github.com/flutter/flutter/assets/35128534/ceaf27cf-e73f-4673-b380-61ac517ecc4c)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```
[✓] Flutter (Channel stable, 3.13.9, on macOS 12.6 21G115 darwin-arm64, locale
    en-IN)
    • Flutter version 3.13.9 on channel stable at
      /Users/kovallip/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (3 weeks ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/kovallip/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.2)
    • IntelliJ at /Users/kovallip/Applications/JetBrains Toolbox/IntelliJ IDEA
      Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.2)
    • IntelliJ at /Users/kovallip/Library/Application
      Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/232.9921.47/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.4)
    • IntelliJ at /Users/kovallip/Library/Application
      Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9225.16/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] VS Code (version 1.82.0)
    • VS Code at /Users/kovallip/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (4 available)
    • Android SDK built for arm64 (mobile) • emulator-5554
      • android-arm64  • Android 10 (API 29) (emulator)
    • Prateek Koval li’s iPod (mobile)     •
      d2a65f89a60a14829e79399fae6cb7250b82a27a • ios            • iOS 15.5 19F77
    • macOS (desktop)                      • macos
      • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)                         • chrome
      • web-javascript • Google Chrome 119.0.6045.123

[✓] Network resources
    • All expected network resources are available.

• No issues found!
``` 

</details>

**Comment by dam-ease** [comment]
Thanks for filing this @prateekrk.
I can't seem to reproduce this on my end (testing with a real device, iPhone 13, iOS 17.0). I tested this on the latest `master` and `stable` channels. The `TextField` in the Flutter app doesn't get unfocused during the switch on my device and when unfocused before the switch, the keyboard doesn't reappear. Are you able to test this on another device (either the simulator or the real device) to see if this could be device-specific? Also, kindly share the device information of where this reproduces.


https://github.com/flutter/flutter/assets/53122008/92380d8e-6bdb-4ba5-8cf5-cf7690daa73b

**Comment by prateekrk** [comment]
I have tested this on iPod 7th gen, with iOS 15.5. The behaviour you described is correct and expected behaviour. But as you keep on trying this for 15-20 I think you might reproduce that.

It's not a very straightforward use case, but my concern is when this happens with the end-user then the whole UI alignment will be messed up and overflow issues will also show up.

**Comment by dam-ease** [comment]
Thanks for your response. I tried this multiple times but can't reproduce as well, could this be peculiar to the device you are testing with?
Can you please try on an iPhone device to see if this also reproduces there?

**Comment by prateekrk** [comment]
Hi @dam-ease , just wanted to check this

We are not using the manual focuses, we use only autofocus in our enterprise application. Since i was able to reproduce this with minimal code in sample app, can we rule out the possibility that this bug is because of developer implementation.

Also flutter has released 3.16 stable version so will check with that.

**Comment by dam-ease** [comment]
Thanks for your response.

> Since i was able to reproduce this with minimal code in sample app, can we rule out the possibility that this bug is because of developer implementation.

Are you able to reproduce with the minimal sample? You could share a screen record, that'll help

> can we rule out the possibility that this bug is because of developer implementation.

Can say this for sure, if it happens with the minimal code sample then it might not be an issue with implementation 

> Also flutter has released 3.16 stable version so will check with that.

Please do and share the results

Thank you!

**Comment by prateekrk** [comment]
> Are you able to reproduce with the minimal sample? You could share a screen record, that'll help

 Recording is attached to the issue, But i have not tried in iPhone, will test and let you know by Monday

**Comment by prateekrk** [comment]
Sorry, we were not able to test in iPhone because of its unavailability.

**Comment by huycozy** [comment]
@prateekrk I also checked this issue on `iPhone 7, iOS 15.8` but can't reproduce it. This could be a device-specific issue on your device `iPod 7th gen`.

Has this issue appeared before in older releases of Flutter? Does this issue persist if there is no navigation between pages? (I mean in a case when there is only a screen with a TextField, to rule out the possibility of a navigator-issue).
