### ISSUE TITLE
Windows Platform Views

### ISSUE THREAD

**Issue by yaakovschectman** [flutter/flutter#138431]
### Document Link

https://flutter.dev/go/flutter-platform-views-windows

### What problem are you solving?

Provide an implementation using native Win32 HWND parent-child model to allow embedding of native Windows views as platform view widgets within Flutter applications.

**Comment by wanjm** [comment]
what is the status;

**Comment by yaakovschectman** [comment]
@wanjm This is paused until further notice.

**Comment by wanjm** [comment]
@yaakovschectman  
Thanks for your reply;
how much work left?
does it still blocked by the feature of multi-window

**Comment by loic-sharma** [comment]
Closing this issue as the design doc is closed for feedback
