### ISSUE TITLE
[in_app_purchase_storekit] Unable to encode userInfo of type __NSDictionaryI

### ISSUE THREAD

**Issue by ANorcia** [flutter/flutter#138407]
**### Is there an existing issue for this?**

When I try to pay after having correctly implemented https://pub.dev/packages/in_app_purchase I get an error that is not very clear and I don't know how to get out of it. I've already looked for a possible solution but haven't found it

Below I attach the complete error message:
`IAPError(code: purchase_error, source: app_store, message: SKErrorDomain, details: {NSLocalizedDescription: An unknown error occurred, NSUnderlyingError: {domain: ASDErrorDomain, userInfo: {NSUnderlyingError: {domain: AMSErrorDomain, userInfo: {NSLocalizedFailureReason: The server encountered an error, AMSServerErrorCode: 3038, AMSServerPayload: Unable to encode native userInfo object of type __NSDictionaryI to map. Please submit an issue at https://github.com/flutter/flutter/issues/new with the title "[in_app_purchase_storekit] Unable to encode userInfo of type __NSDictionaryI" and add reproduction steps and the error details in the description field., AMSURL: http://localhost:49436/WebObjects/MZBuy.woa/wa/inAppBuy, AMSStatusCode: 200, NSLocalizedDescription: Server Error}, code: 305}}, code: 504}})`

Thanks to everyone who will answer this question

**Comment by stuartmorgan** [comment]
Reformatting to show the structure:

```
IAPError(
  code: purchase_error
  source: app_store
  message: SKErrorDomain
  details: {
    NSLocalizedDescription: An unknown error occurred
    NSUnderlyingError: {
      domain: ASDErrorDomain
      userInfo: {
        NSUnderlyingError: {
          domain: AMSErrorDomain
          userInfo: {
            NSLocalizedFailureReason: The server encountered an error
            AMSServerErrorCode: 3038
            AMSServerPayload: Unable to encode native userInfo object of type __NSDictionaryI to map. Please submit an issue at https://github.com/flutter/flutter/issues/new with the title "[in_app_purchase_storekit] Unable to encode userInfo of type __NSDictionaryI" and add reproduction steps and the error details in the description field.
            AMSURL: http://localhost:49436/WebObjects/MZBuy.woa/wa/inAppBuy
            AMSStatusCode: 200
            NSLocalizedDescription: Server Error
          }
          code: 305
        }
      }
      code: 504
    }
  }
)
```

So we have several layers of errors here, and the part we're missing is part of the info dict in an error nested in another error. We should add nested dictionaries to the recursive handling, apparently.

**Comment by stuartmorgan** [comment]
(As for the cause of the error in the first place, I would suggest reporting the issue to Apple. The error messages don't provide any useful information about what "AMSServerErrorCode: 3038" indicates, so only Apple would be able to answer that.)

**Comment by MilkBiscuit** [comment]
Same issue here, and I am using 'StoreKit Testing' in Xcode, after purchase it pop up this dialog
