### ISSUE TITLE
Allow (on demand/toggle) running post-submits as pre-submits

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#138430]
### Is there an existing issue for this?

- [X] I have searched the [existing infra issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-infra)

### Type of Request

feature request

### Infrastructure Environment

I'd like to see this implemented in the code that parses and/or understands `.ci.yaml`, which, IIRC, is Cocoon?

---

Similar requests:

- @gaaclarke's https://github.com/flutter/flutter/issues/111418.

## Background

The engine repo has insufficient capacity to run every kind of test on every kind of platform on every commit.

As a result, we run many tests as [`presubmit: false`](https://github.com/flutter/engine/blob/main/.ci.yaml), i.e.: [this config](https://github.com/flutter/engine/blob/eba757803a6f3144d4875c54db51a0add551c72c/.ci.yaml#L245-L248). That works fine for the vast majority of commits, but sometimes we are changing things that are _only_ exhaustively tested by postsubmit.

Two recent examples:

1. https://github.com/flutter/flutter/issues/138381; 
  due to not running the clang-tidy postsubmits.

2. https://github.com/flutter/engine/pull/47397;
  caused a device lab failure due to not running the device lab physical devices.

## Proposal

The currently suggested workflow is to make _manual edits_ to `.ci.yaml`, and remember to revert them before merging.

While we could bike shed on granularity (like a `test: physical-android-devices`), I'd like to propose starting with a simple Github label (i.e. `test: include-postsubmit`, or whatever follows our label philosophy) that treats `presubmit: false` as `presubmit: true`.

That should be sufficient to see, particularly on the engine repo, if we can catch more of these issues in pre-submit.

**Comment by matanlurey** [comment]
/cc @gaaclarke @zanderso @CaseyHillers.

As I mentioned to @CaseyHillers offline, I'd be happy to contribute this feature, and also own reverting it if ends up being insufficient or causes problems that I can't really imagine :)

**Comment by CaseyHillers** [comment]
For the engine repo, there's 7 targets that are marked as `presubmit: false`. Most seem fine to run on presubmit, I'd be curious if the builder_cache targets would be fine.

It looks like this would only require updating https://github.com/flutter/cocoon/blob/818801ea79eb8de141fb8aab11e26f96bc2b8329/app_dart/lib/src/service/scheduler.dart#L422 to check the labels on the PullRequest object to verify `test: include-postsubmit` exists. However, this wouldn't catch cases where the label is added after the commit is pushed, but we could pair program on it to finalize those details.

My larger concern here is how to handle the framework repo. There's no way to run everything, so we may need to mark targets as being in the special presubmit pool. Such as updating `presubmit` to mark a target as being able to run in presubmit via this workflow.

**Comment by matanlurey** [comment]
@CaseyHillers:

> My larger concern here is how to handle the framework repo. There's no way to run everything, so we may need to mark targets as being in the special presubmit pool. Such as updating `presubmit` to mark a target as being able to run in presubmit via this workflow.

I'd be OK with special casing the engine repo (repo must == `engine`) to avoid that problem.

> I'd be curious if the builder_cache targets would be fine.

I suppose we could also special case to ignore `builder_cache` targets?

> but we could pair program on it to finalize those details

👍🏼

**Comment by godofredoc** [comment]
@keyonghan please take a look
