### ISSUE TITLE
Add a `flutter bug-report` command

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#13842]
`flutter run --bug-report` will run with recording enabled and serialize a bunch of info to disk that can be attached as a bug report.  There are a couple of things about this that don't always meet the developer's needs:

1. It requires them to attach a full recording of their run, which may include source code of their app, and also is potentially very large.
2. It requires them to run.  In the event of the developer running into problems well before the "I want to try to run my app" stage, it doesn't make sense to have them go through the "run" workflow in order to capture a bug report.

I propose that we add a `flutter bug-report` command.  It would capture basic system info relevant to diagnosing developer-reported bugs.  We would then make `flutter run --bug-report` hook into this basic bug reporting mechanism, while augmenting it with recording info.

Once this is done, we should integrate it into the IDE as well.

**Comment by jmagman** [comment]
Is this covered by https://github.com/flutter/flutter/issues/1657?

**Comment by tvolkert** [comment]
Yep!
