### ISSUE TITLE
Support for Material's multi-select on Cards and Images using standard Flutter or a package

### ISSUE THREAD

**Issue by ptepper** [flutter/flutter#138562]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Material design has a design spec for multi-selection of "Larger selections" like cards or images. When the items go into selectable mode, a circular checkbox appears in the upper left corner. It's used in Google Photos.

I don't see it in the Flutter docs, so I don't think it's supported out-of-the-box. I know it could be custom implemented, but it would be hard to get the same look & feel, and it would be easier if it were built-in.

It's in the Material Design 3 spec here: [Foundations > Interaction > Selection > Larger selections](https://m3.material.io/foundations/interaction/selection#97a46ad7-9596-4959-ada4-22b9cbb2cc0c)

### Proposal

My proposal is a to implement the multi-selection of "Larger selections" in Flutter.  Ideally Flutter would provide an easy way to do all of the Selection Interactions shown in Material 3. See the link above for details on what this looks like. This could probably be provided in a flutter package if someone had the time.

**Comment by huycozy** [comment]
Hi @ptepper 
I understand this is in the M3 specs but the proposal doesn't seem to specify what needs to be done on the framework side. I think this belongs to the scope of implementation, you can refer to this [article](https://medium.com/@mnhmasum/flutter-drag-to-select-multiple-items-from-gridview-86175a1052e4) where the author has implemented the same thing.

It would be more helpful if you could specify this around aspects like: adding a widget A or enhancing something in an existing widget B to achieve this, etc.
