### ISSUE TITLE
[Docs] Provide Documentation on how to set Material 3 color scheme to previous flutter default

### ISSUE THREAD

**Issue by yakagami** [flutter/flutter#138582]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I see there is a migration guide for how to use the new `ColorScheme`. It would be great if also included was what is necessary to get the previous default colors back. At least for testing it is slightly jarring to see what is now multiple color schemes due to some Widgets using custom colors that worked well with the previous default and now the default colors look random while the explicitly set ones don't fit with them. I would also note that many google apps do not heavily use material you colors (eg. youtube). Right now my scaffold background color is pink and buttons are purple due to this update which is not something I have ever seen in any material you app and frankly looks dreadful.

### Proposal

Add something like "to change the default color scheme back to the flutter 3.13 color scheme, do x".

**Comment by Adam-Langley** [comment]
Simply assign a ThemeData to your Theme widget, using the 'useMaterial3: false' argument...

```
MaterialApp.router(
    theme: ThemeData.light(useMaterial3: false)
)
```

Docs here:
https://api.flutter.dev/flutter/material/ThemeData/useMaterial3.html

**Comment by dam-ease** [comment]
Thanks for your input @Adam-Langley.
@yakagami As said in the last comment, this is currently in the docs, and setting `useMaterial3: false` allows you to make use of the features of Material 2.
Closing this as this has already been implemented, if you disagree, please comment and I'll reopen this.
Thank you!

**Comment by yakagami** [comment]
@dam-ease Thanks for your reply. Yes, I disagree. From the docs:

>In the long run this flag will be deprecated and eventually only Material 3 will be supported. 

I think it makes sense to deprecate default Material 2 widgets because maintaining that would be difficult and without much use but the color scheme should certainly have a default non dynamic-Material-colors color scheme that is similar to the current one with eg. Colors.grey[50] scaffold background color and blue buttons. This isn't about a way to keep using Material 2, just a way for Material 3 to provide a usable non wallpaper based light theme. When I look at any of the top apps on android, non of them use Material Colors, even if they otherwise use Material 3. There is a reason why this is the case. Even most Google apps do not use it: Gmail, Chrome, Maps, YouTube. WhatsApp does not use it. I don't think it's fair for a UI design to be so opinionated about Colors to the extent that to turn it off one must manually select each default color. Especially in the context of multi platform apps where no other supported operating system (iOS, Windows, macOS, Linux) has the concept of Material You wallpaper based color schemes.

**Comment by yakagami** [comment]
In the meantime I fixed this by switching to `CupertinoApp` and `CupertinoPageScaffold`.

**Comment by dam-ease** [comment]
Thanks for your response. If I got you right, you should be able to make changes to the ColorScheme using https://api.flutter.dev/flutter/material/ColorScheme-class.html.
Can you check this out?
If your proposal encompasses a single parameter to make these changes instead which altering the `colorScheme` property might not achieve, please write in the comments with more information.
Thank you
