### ISSUE TITLE
Migration from `textScaleFactor` to `TextScalar.scale` not ready for `ButtonStyleButton.scaledPadding`

### ISSUE THREAD

**Issue by spydon** [flutter/flutter#138547]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Call `ButtonStyleButton.scaledPadding` from a context where you don't have any font size available to provide for the non-linear scaling:
```dart
    ButtonStyleButton.scaledPadding(
      const EdgeInsets.symmetric(horizontal: 16),
      const EdgeInsets.symmetric(horizontal: 8),
      const EdgeInsets.symmetric(horizontal: 4),
      MediaQuery.maybeOf(context)?.textScaler.scale(??),
    );
```

### Expected results

A possibility to use `ButtonStyleButton.scaledPadding` without using the deprecated `textScaleFactor` variable.

### Actual results

Currently it doesn't seem possible to use  `ButtonStyleButton.scaledPadding` without using the deprecated `textScaleFactor` variable.

### Code sample

<details><summary>Code sample</summary>
Now:

```dart
    ButtonStyleButton.scaledPadding(
      const EdgeInsets.symmetric(horizontal: 16),
      const EdgeInsets.symmetric(horizontal: 8),
      const EdgeInsets.symmetric(horizontal: 4),
      MediaQuery.maybeOf(context)?.textScaler.scale(??),
    );
```

Previously:

```dart
    ButtonStyleButton.scaledPadding(
      const EdgeInsets.symmetric(horizontal: 16),
      const EdgeInsets.symmetric(horizontal: 8),
      const EdgeInsets.symmetric(horizontal: 4),
      MediaQuery.maybeOf(context)?.textScaleFactor,
    );
```

</details>

### Logs

Other people with the same issue:
https://stackoverflow.com/questions/77494443/how-to-migrate-from-textscalefactor-to-textscalar-scale

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.0, on Ubuntu 23.10 6.5.0-10-generic, locale
    en_US.UTF-8)
    • Flutter version 3.16.0 on channel stable at /home/spydon/bin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (20 hours ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2
```

</details>

**Comment by dam-ease** [comment]
Thanks for filing this @spydon.
I can see this on the latest `master` and `stable` channels.
But from the docs: https://docs.flutter.dev/release/breaking-changes/deprecate-textscalefactor
I see this could work in your use case, can you try this out?

```dart
ButtonStyleButton.scaledPadding(
                  const EdgeInsets.symmetric(horizontal: 16),
                  const EdgeInsets.symmetric(horizontal: 8),
                  const EdgeInsets.symmetric(horizontal: 4),
                  MediaQuery.maybeOf(context)!.textScaler.scale(20) / 20,
                )
```

**Comment by spydon** [comment]
@dam-ease since it is non-linear scaling with `textScaler.scale`, how would I choose the number that you chose to be 20 here? It will give different output depending on the number I choose, right?

**Comment by spydon** [comment]
@LongCatIsLooong seems like you forgot to add a priority label?

**Comment by LongCatIsLooong** [comment]
I think that method wasn't really meant to be called outside of the framework. Are you using it to calculate the padding value to use for your `ButtonStyleButton`?

**Comment by spydon** [comment]
> I think that method wasn't really meant to be called outside of the framework.

Interesting that it wasn't marked as `@internal` then, maybe someone forgot.

> Are you using it to calculate the padding value to use for your ButtonStyleButton?

Probably easier to show you the code, this is where I found it (I didn't build this code-base, just upgrading it to the latest versions):
https://github.com/canonical/ubuntu-flutter-plugins/blob/main/packages/ubuntu_widgets/lib/src/menu_button_builder.dart#L237

**Comment by LongCatIsLooong** [comment]
Ah if the app targets Ubuntu then text scaling is still linear in which case you could plug in an arbitrary font size (using 1 here): `MediaQuery.maybeOf(context)!.textScaler.scale(1) / 1,`

Alternatively you could make a change similar to https://github.com/flutter/flutter/pull/139014, so the default padding depends on the actual font size instead of `textScaleFactor`.
