### ISSUE TITLE
`flutter build bundle` not working on latest stable

### ISSUE THREAD

**Issue by fertrig** [flutter/flutter#138514]
Hi. I created issue #136547 which is a blocker for our tool. The issue was fixed almost a month ago. However, the fix hasn't been release yet. I was hoping the fix would make it to the next beta release and then onto the next stable release. However, there hasn't been a beta release yet, and a new stable release (Flutter 3.16.0) just dropped.

Our users that upgrade to Flutter 3.16.0 won't be able to use our tool because the fix is not in the latest stable release.

Is there anyway to do a hotfix to Flutter 3.16.0 which includes the fix for #136547?

@stuartmorgan

**Comment by stuartmorgan** [comment]
> Is there anyway to do a hotfix to Flutter 3.16.0 which includes the fix for #136547?

See https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process for the cherry-pick process.

Closing this as cherry picks need to follow the template and process, so a new issue needs to be opened as described there.
