### ISSUE TITLE
Blocking those who describe Flutter dev from reading the flutter changes stories that Kevin Chisholm generates

### ISSUE THREAD

**Issue by fredgrott** [flutter/flutter#138541]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Like the title says I am blocked from those medium stories about flutter SDK changes.

Is that a effing bright idea given the hard work the flutter community outside the SDK do to fill the holes in the SDK even to me as I am a contributor to several community packages including Flutter Platform Widgets, Catcher, etc.

Given I have access to said medium stories by just logging out of medium I can be only seen as community contributors as dick move by KC.

I mean honestly, codelabs should have an example of Flutter Adaptive Scaffold. How do you expect to get such contributions from the community by pulling such a dick move?

### Proposal

Stop banning people from reading the Flutter SDK changes linked in the website due to personal feelings of the poster.

**Comment by dam-ease** [comment]
Hi @fredgrott. 
Thanks for filing this.
The best place to raise this issue will be on Discord, kindly raise this on the Flutter Discord Channel.

I'll be closing this from here as this isn't an issue with Flutter itself.

Also, please refer to our [code of conduct](https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md) in regard to respectful and welcoming communication

**Comment by dnfield** [comment]
@fredgrott as mentioned, please take a moment to review our [Code of Conduct](https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md).

The language and tone of your post is not following the expectations of that document. If you cannot understand why that is the case, I would encourage you to take some time away from this community to reflect on that. 

The expectations of that code of conduct extend to the Discord server and Medium articles posted by members of this community.
