### ISSUE TITLE
[Impeller] Use OES address sampling mode extensions.

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#138504]
We added the ability to use external textures in TiledTextureContents in this patch: https://github.com/flutter/engine/pull/47586

OES_EGL_image_external only allows CLAMP_TO_EDGE address sampling modes, and so we emulate all the others when an external texture is drawn with Impeller.

However, there are extensions we could use to support decal (OES_texture_border_clamp) and mirror (OES_texture_border_clamp) modes that we could use to marginally reduce fragment load for some sampling configurations.

https://registry.khronos.org/OpenGL/extensions/OES/OES_texture_border_clamp.txt
https://registry.khronos.org/OpenGL/extensions/OES/OES_texture_mirrored_repeat.txt

**Comment by jonahwilliams** [comment]
This probably isn't that important to do. I doubt we'll have performance issues from the sampling mode.
