### ISSUE TITLE
【pigeon】In Windows desktop development, the header file and cpp file automatically generated by pigeon are in UTF-8 encoded format without UTF-8 boom.

### ISSUE THREAD

**Issue by azeek** [flutter/flutter#138528]
### Is there an existing issue for this?

- [X] I have searched the [existing package issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Apackage)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### What package does this bug report belong to?

pigeon

### What target platforms are you seeing this bug on?

Windows

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
[Paste file content here]
```

</details>

### Steps to reproduce

In Windows desktop development, the header file and cpp file automatically generated by pigeon are in UTF-8 encoded format without UTF-8 boom. 

Sometimes users want to write documentation annotations in their native language during product development.

### Expected results

If you generate the code through piegon and build it, the build should complete normally.

### Actual results

If the dart source I'm putting into pigeon has documentation comments in Korean and Chinese characters, I get visual studio error C2220. 

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:pigeon/pigeon.dart';


@ConfigurePigeon(PigeonOptions(
  dartOut: 'lib/unicode_test.dart',
  dartOptions: DartOptions(),
  cppOptions: CppOptions(namespace: 'ICONV'),
  cppHeaderOut: 'windows/unicode_test.h',
  cppSourceOut: 'windows/unicode_test.cpp',
))




@HostApi()
abstract class KGridGcdn {  

  /// ### 자막 파일의 인코딩을 확인하는 함수
  /// * [filePath] : 자막 파일 경로
  /// - return : 인코딩 타입
  @async
  String detectSubtitleEncoding(String filePath);

  /// ### 자막 파일을 읽어 들여서 utf8로 변환 후 반환하는 함수
  /// * [filePath] : 자막 파일 경로
  /// - return : utf8로 변환된 자막 파일 문자열
  @async
  String loadSubtitleToUtf8(String filePath);

  /// ### 텍스트의 인코딩을 확인하는 함수
  /// * [text] : 텍스트
  /// - return : 인코딩 타입
  @async
  String detectTextEncoding(String text);

  /// ### 텍스트를 읽어 들여서 utf8로 변환 후 반환하는 함수
  /// * [text] : 변환할 문자열
  /// - return : utf8로 변환된 문자열
  @async
  String loadTextToUtf8(String text);
}
```

</details>

### Screenshots or Videos

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
1>desktop_streaming_plugin.cpp
1>D:\project\desktop_streaming\example\windows\flutter\ephemeral\.plugin_symlinks\desktop_streaming\windows\kgrid_gcdn_base.h(1,1): error C2220: 다음 경고는 오류로 처리됩니다.
1>(소스 파일 '../../../../windows/flutter/ephemeral/.plugin_symlinks/desktop_streaming/windows/desktop_streaming_plugin.cpp'을(를) 컴파일하는 중)
1>D:\project\desktop_streaming\example\windows\flutter\ephemeral\.plugin_symlinks\desktop_streaming\windows\kgrid_gcdn_base.h(1,1): warning C4819: 현재 코드 페이지(949)에서 표시할 수 없는 문자가 파일에 들어 있습니다. 데이터가 손실되지 않게 하려면 해당 파일을 유니코드 형식으로 저장하십시오.
1>(소스 파일 '../../../../windows/flutter/ephemeral/.plugin_symlinks/desktop_streaming/windows/desktop_streaming_plugin.cpp'을(를) 컴파일하는 중)
1>D:\project\desktop_streaming\example\windows\flutter\ephemeral\.plugin_symlinks\desktop_streaming\windows\kgrid_gcdn_base.h(234,53): error C3646: 'result': 알 수 없는 재정의 지정자입니다.
1>(소스 파일 '../../../../windows/flutter/ephemeral/.plugin_symlinks/desktop_streaming/windows/desktop_streaming_plugin.cpp'을(를) 컴파일하는 중)
1>D:\project\desktop_streaming\example\windows\flutter\ephemeral\.plugin_symlinks\desktop_streaming\windows\kgrid_gcdn_base.h(234,59): error C2059: 구문 오류: ')'
1>(소스 파일 '../../../../windows/flutter/ephemeral/.plugin_symlinks/desktop_streaming/windows/desktop_streaming_plugin.cpp'을(를) 컴파일하는 중)
1>D:\project\desktop_streaming\example\windows\flutter\ephemeral\.plugin_symlinks\desktop_streaming\windows\kgrid_gcdn_base.h(234,10): error C2838: 'function': 멤버 선언의 정규화된 이름이 잘못되었습니다.
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Visual Studio - develop Windows apps (Visual Studio Enterprise 2022 17.8.0)
[√] Android Studio (version 2022.3)
[√] IntelliJ IDEA Ultimate Edition (version 2023.2)
[√] VS Code (version 1.84.2)
[√] Connected device (1 available)
[√] Network resources

```

</details>

**Comment by huycozy** [comment]
Hi @azeek 
>If the dart source I'm putting into pigeon has documentation comments in Korean and Chinese characters, I get visual studio error C2220.

Do you mean you have this error when executing pigeon command ` flutter pub run pigeon`? 

I checked this with your code above and saw it executed successfully.

**Comment by jwinarske** [comment]
@huycozy the reported error is a compilation error, post pigeon generation.

**Comment by stuartmorgan** [comment]
> the header file and cpp file automatically generated by pigeon are in UTF-8 encoded format without UTF-8 boom

This is the standard format for UTF-8 files; UTF-8 doesn't require a BOM.

> Sometimes users want to write documentation annotations in their native language during product development.

Doing so is perfectly valid in a UTF-8 file. The reason compilation fails isn't that there's something wrong with the UTF-8 file, it's that Visual Studio by default assumes that code files are in your default codepage (which is deeply unfortunate in a modern environment).

Does adding `target_compile_options(${PLUGIN_NAME} /utf-8)` to your plugin's CMakeLists.txt file address this?

**Comment by azeek** [comment]
> > the header file and cpp file automatically generated by pigeon are in UTF-8 encoded format without UTF-8 boom
> 
> This is the standard format for UTF-8 files; UTF-8 doesn't require a BOM.
> 
> > Sometimes users want to write documentation annotations in their native language during product development.
> 
> Doing so is perfectly valid in a UTF-8 file. The reason compilation fails isn't that there's something wrong with the UTF-8 file, it's that Visual Studio by default assumes that code files are in your default codepage (which is deeply unfortunate in a modern environment).
> 
> Does adding to your plugin's CMakeLists.txt file address this?


Thanks @stuartmorgan

This issue has been resolved. 

I added the following to the plugin cmake file and it compiled!

```
target_compile_options(${PLUGIN_NAME} PRIVATE "/utf-8")
```
