### ISSUE TITLE
[iOS] Performance hit in some animations

### ISSUE THREAD

**Issue by 23doors** [flutter/flutter#138575]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Getting same performance hit as described in this comment https://github.com/flutter/flutter/issues/138490#issuecomment-1814577937 but seems like there is no issue for it just yet.

Everything works fine on 3.13.9, 3.16 is very janky on:
* pushing a new route (uses default slider animation on iOS) looks choppy
* showModalBottomSheet also seems to be appearing in a pretty janky way.

Performance tab in devtools looks then like one from the comment.

### Expected results

Same performance results as on 3.13.9 where both route pushing and showing modal is smooth.

### Actual results

Severe jank on iPhone 13 Pro Max running iOS 17.0.3 when using flutter 3.16.

### Code sample

Reproducible on any basic use of showModalRoute or pushing a route (using GoRouter myself for it but pretty sure it's not navigator specific). 

https://github.com/flutter/packages/tree/main/packages/go_router/example

### Flutter Doctor output

Note that I downgraded to 3.13.9 for the time being.

[✓] Flutter (Channel stable, 3.13.9, on macOS 14.0 23A344 darwin-arm64, locale en-US)
    • Flutter version 3.13.9 on channel stable at /opt/homebrew/Caskroom/flutter/3.7.7/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (3 weeks ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/V/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/V/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Community Edition (version 2023.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 76.2.4
    • Dart plugin version 232.10072.19

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (5 available)
    • SHIELD Android TV (mobile) • shield.lan:5555                      • android-arm64  • Android 11 (API 30)
    • RK iPhone (mobile)         • 00008110-001478C22281801E            • ios            • iOS 17.0.3 21A360
    • iPhone 12 mini (mobile)    • 001B9E35-317E-4089-9C8B-DCE8B3ED0829 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 119.0.6045.123

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by jonahwilliams** [comment]
@23doors you've basically filled an issue with no details on your specific issue or application. "I'm seeing some jank" isn't generally applicable.

Please see the performance issue template for some examples of the information we need to make this bug actionable: https://github.com/flutter/flutter/issues/new?assignees=&labels=from%3A+performance+template&projects=&template=5_performance_speed.yml

**Comment by 23doors** [comment]
@jonahwilliams You're right, I wrongfully assumed that this issue is more widespread and easier to reproduce. Will try to isolate it first as seems it doesn't occur on example I provided.

**Comment by 23doors** [comment]
Closing this one for now.

**Comment by 23doors** [comment]
For anyone who encounters this, my issue was linked to use of BackdropFilter with blur which degraded quite heavily post 3.13 on ios. There are other issues tracking this though.

**Comment by jonahwilliams** [comment]
We have issues open for improving blur performance but we're not aware of _any_ regressions in backdrop filter performance from 3.13 to 3.16

**Comment by 23doors** [comment]
Well. According to e.g. https://github.com/flutter/flutter/issues/132735#issuecomment-1715518498 there actually is post 3.13 degradation and it's affecting me as well.

**Comment by jonahwilliams** [comment]
The bug that issue is tracking was not a regression between 3.13 and 3.16. if you are claiming this happened between 3.13 and 3.16 you _really_ need to file a new bug, because we have nothing tracking your problem. Fixing the blur issue linked there may not fix your problem.

**Comment by jonahwilliams** [comment]
This might have been helped by https://github.com/flutter/engine/pull/47808 . You could try out master channel and see if it reproduces there?
