### ISSUE TITLE
[in_app_purchase] - Never getting purchased Status in iOS 17.1.1 Sandbox

### ISSUE THREAD

**Issue by lukeirvin** [flutter/flutter#138522]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. iPhone running iOS 17+
2. Go through the subscription process via iOS In App Purchase
3. Receive Successful Purchase Prompt
4. Purchase Status is never sent so stuck without a completion.

### Expected results

After a successful purchase, I should receive the purchased prompt to finish the transaction.

### Actual results

I get the Sandbox success prompt, but no purchased status response.s

### Code sample

.

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.8, on macOS 13.6 22G120 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.84.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by dam-ease** [comment]
Thanks for filing this. 
The issue you are describing seems similar/related to https://github.com/flutter/flutter/issues/138134.
Can you try out the solution that worked in this case/ confirm you have this set up in your case https://github.com/flutter/flutter/issues/138134#issuecomment-1806390002.

**Comment by lukeirvin** [comment]
Hi @dam-ease. 

My apologies, I'm not really seeing a solution on that page. My guess is it is the StoreKit configuration. 

I'm primarily testing on my physical iPhone & not in the simulator. Would that still matter here? 

Can you point me to the latest example project that has this?

**Comment by dam-ease** [comment]
Thanks for your response.
You can check out the example/ configuration here: https://github.com/flutter/packages/blob/main/packages/in_app_purchase/in_app_purchase/example/README.md#ios

**Comment by lukeirvin** [comment]
I have implemented the Storekit configuration. One thing I have noticed is that if I test this via simulator I get stuck in an infinite loop. But it seems to work when testing on a device. Any suggestions?

**Comment by dam-ease** [comment]
> if I test this via simulator I get stuck in an infinite loop

Can you provide more information on this infinite loop, from the referenced issue and the example I shared, this should work fine both on a simulator and on a real device.

**Comment by lukeirvin** [comment]
Yes, my apologies.

When I run in the simulator, I am able to get the IAP sign-in alert. After I sign in I see it right after, again & again. I don't get that experience from a physical device though.

**Comment by dam-ease** [comment]
Thanks for your response.

> When I run in the simulator, I am able to get the IAP sign-in alert. After I sign in I see it right after, again & again.

Do you mean the sign-in alert, if possible, attaching a screen record could help in this case.
