### ISSUE TITLE
##ISSUE Flutterfire_CLI Unhandle Exception...

### ISSUE THREAD

**Issue by SandyCooper** [flutter/flutter#138526]
I have this following issue,

`$ dart pub global run flutterfire_cli:flutterfire configure
Fetching available Firebase projects...
Unhandled exception:
FormatException: Unexpected end of input (at character 1)

^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)     
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501:7)     
#2      _parseJson (dart:convert-patch/convert_patch.dart:36:10)
#3      JsonDecoder.convert (dart:convert/json.dart:610:36)
#4      runFirebaseCommand (package:flutterfire_cli/src/firebase.dart:95:25)       
<asynchronous suspension>
#5      getProjects (package:flutterfire_cli/src/firebase.dart:114:20)
<asynchronous suspension>
#6      ConfigCommand._selectFirebaseProject (package:flutterfire_cli/src/commands/config.dart:300:24)
<asynchronous suspension>
#7      ConfigCommand.run (package:flutterfire_cli/src/commands/config.dart:390:37)<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#9      main (file:///C:/Users/Lenovo/AppData/Local/Pub/Cache/hosted/pub.dev/flutterfire_cli-0.2.7/bin/flutterfire.dart:57:5)
<asynchronous suspension>`

I have check all Stack flow forum and GitHub including this https://github.com/invertase/flutterfire_cli/issues/55 . I have tried all the solution in that forum none of them worked for me. I have been trying for more than 1 week nothing happens.  Please Kindly rectify this issue. PLEASE!!!

**Comment by danagbemava-nc** [comment]
flutterfire cli is not maintained by the flutter team. This should be reported on the flutterfire_cli repo. 

Closing from here.
