### ISSUE TITLE
[CP] Don't build native assets in `flutter build bundle`

### ISSUE THREAD

**Issue by fertrig** [flutter/flutter#138519]
### Issue Link

https://github.com/flutter/flutter/issues/136547

### Commit Hash

402a545

### Target

stable

### PR Link

https://github.com/flutter/flutter/pull/138518

### Changelog Description

On macOS, native asset changes break `build bundle` command.

### Impacted Users

Users of dev tools that use the `build bundle` command, and any other users who use `build bundle`

### Impact Description

It impacts development.

### Workaround

No, there isn't any.

### Risk

low

### Test Coverage

yes

**Comment by CaseyHillers** [comment]
@christopherfujino can you review this CP request? If it looks good to you, add the "cp: approved" label.

**Comment by christopherfujino** [comment]
> Risk
>
> low

Can you explain more to me why this is a low-risk change? Given the size of the diff to lib/src/build_system/targets/native_assets.dart, it is not clear to me that this is low risk.

> Impacted Users
>
> Users of dev tools that use the build bundle command, and any other users who use build bundle

@fertrig can you clarify more "impacted users". To my knowledge, very few users directly invoke `flutter build bundle` (I'm the tech lead of the CLI tool, and I'd never heard of this command until I saw this bug).

**Comment by fertrig** [comment]
@christopherfujino: 

Re risk, I thought it was low risk because the fix has been in master for a while. However, I see what you are saying. This is a hotfix thus the fix should be simpler. I'll work on a simpler fix. I may need some help though.

Re impacted users, we have hundreds of users, perhaps close to a thousand users, per month which use our tool. Most of our users use macOS, thus this bug blocks them from using our tool. And, for our organization this bug is very impactful, we are trying to grow a tool in the Flutter space, thus this bug would be a major setback.

**Comment by christopherfujino** [comment]
> @christopherfujino:
> 
> Re risk, I thought it was low risk because the fix has been in master for a while. However, I see what you are saying. This is a hotfix thus the fix should be simpler. I'll work on a simpler fix. I may need some help though.
> 
> Re impacted users, we have hundreds of users, perhaps close to a thousand users, per month which use our tool. Most of our users use macOS, thus this bug blocks them from using our tool. And, for our organization this bug is very impactful, we are trying to grow a tool in the Flutter space, thus this bug would be a major setback.

Given that this fix is already on the beta channel, I would suggest your tool and/or your users use that channel: https://github.com/flutter/flutter/blob/beta/packages/flutter_tools/lib/src/commands/build_bundle.dart#L135

I think I will not approve this cherrypick as it is risky as a regression here would potentially affect all build targets, while the bug only affects a small subset of Flutter's users.

I'm sorry to not give you the outcome you wanted, however I appreciate you contributing.

**Comment by fertrig** [comment]
I understand your point. However, I'm afraid Flutter 3.16 will be stable for several months which could be disastrous for us. If I provide a simpler fix that reduces the risk and that doesn't affect all build targets, would you re-consider the hot fix?

**Comment by christopherfujino** [comment]
> I understand your point. However, I'm afraid Flutter 3.16 will be stable for several months which could be disastrous for us. If I provide a simpler fix that reduces the risk and that doesn't affect all build targets, would you re-consider the hot fix?

sure, I will consider it. I don't want to get your hopes up though, it seems difficult to create a version of this fix that will not affect other targets given the current structure of the build system.

Out of curiosity, can you clarify more why "Flutter 3.16 will be stable for several months" would be disastrous?

**Comment by fertrig** [comment]
It could be disastrous for us because our tool has to use the Flutter version that the user's Flutter project uses. In other words, if the users's project is running Flutter 3.16 then our tool needs to also use Flutter 3.16. Also, most of our users use Flutter stable on their projects and they won't want to switch to Flutter beta because most of the time they are developing apps on Flutter stable. Thus, the impact is massive for us.

I'm afraid our user growth would stop for several months. Since we are a young startup, I'm not sure we can recover from that impact.

**Comment by christopherfujino** [comment]
> It could be disastrous for us because our tool has to use the Flutter version that the user's Flutter project uses.

ahh, I see. I didn't realize you were relying on the user having their own upstream Flutter SDK.

**Comment by fertrig** [comment]
@christopherfujino Here is a PR which I think reduces the risk drastically #138816. Please let me know what you think.
