### ISSUE TITLE
[Impeller] backdrop filter blur on screen with platform view results in two fullscreen blurs

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#138656]
I'd expect the overlay blur to be much smaller - only covering part of the screen. but with the Backdrop blur it expands to be the same size as the flutter view despite having no content.

This can be reproduced on the wonderous grreat wall section. Scroll to the bottom and discover the item there and take a frame capture.

![image](https://github.com/flutter/flutter/assets/8975114/8f977dfb-ae99-4c58-8f8c-6a54826b30aa)

**Comment by jonahwilliams** [comment]
FYI @bdero , a case like https://github.com/flutter/engine/pull/46084 but more significant: we don't optimize out backdrops from the overlay layers when there are platform views. So any blur that intersects a platform view will result in two blurs, even if the overlay layer is completely empty.

**Comment by jonahwilliams** [comment]
I went back to 3.13 and it appears this still works similarly, so this isn't a regression.

**Comment by chinmaygarde** [comment]
May I close https://github.com/flutter/flutter/issues/138615 as the assertion that this is a regression has been disproven? Leaving this up is fine as the poor performance is still an issue.

**Comment by jonahwilliams** [comment]
As fixed as its gonna get!
