### ISSUE TITLE
Flutter app not opening after install

### ISSUE THREAD

**Issue by tanvireven** [flutter/flutter#138695]
Flutter app build and install successfully by "flutter run" command but it's not open. Just show the flutter default splash white screen with flutter logo.
I was trying 4 different emulator and 3 physical device.
i use firebase email/pass sign-in.

**Here the "flutter run --release --verbose" result:**

```
 adb: failed to install D:\Flutter Backup\VU\vu_bloodline\build\app\outputs\flutter-apk\app-release.apk: Failure
[INSTALL_PARSE_FAILED_NO_CERTIFICATES:
           Failed to collect certificates from /data/app/vmdl1938660613.tmp/base.apk: Attempt to get length of null array]
[   +3 ms] Error: Failed to install APK again.
[   +7 ms] Error running application on sdk gphone x86 64.
[  +67 ms] "flutter run" took 336,189ms.
[  +82 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:760:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>


[ +320 ms] ensureAnalyticsSent: 267ms
[   +3 ms] Running 1 shutdown hook
[  +14 ms] Shutdown hooks complete
[        ] exiting with code 2

```

**Comment by danagbemava-nc** [comment]
Hi @tanvireven, please provide the output of `flutter doctor -v`. 

Please also provide the content of your `android/app/build.gradle`.

Thank you

**Comment by tanvireven** [comment]
**Hello @danagbemava-nc , Here the `flutter doctor -v` output..**

> [√] Flutter (Channel stable, 3.13.9, on Microsoft Windows [Version 10.0.19045.3693], locale en-US)
>     • Flutter version 3.13.9 on channel stable at C:\src\flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision d211f42860 (4 weeks ago), 2023-10-25 13:42:25 -0700
>     • Engine revision 0545f8705d
>     • Dart version 3.1.5
>     • DevTools version 2.25.0
> 
> [√] Windows Version (Installed version of Windows is version 10 or higher)
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
>     • Android SDK at C:\Users\hi\AppData\Local\Android\sdk
>     • Platform android-34, build-tools 34.0.0
>     • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
>     • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
>     • All Android licenses accepted.
> 
> [√] Chrome - develop for the web
>     • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
> 
> [X] Visual Studio - develop Windows apps
>     X Visual Studio not installed; this is necessary to develop Windows apps.
>       Download at https://visualstudio.microsoft.com/downloads/.
>       Please install the "Desktop development with C++" workload, including all of its default components
> 
> [√] Android Studio (version 2022.3)
>     • Android Studio at C:\Program Files\Android\Android Studio1
>     • Flutter plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
> 
> [√] VS Code (version 1.84.2)
>     • VS Code at C:\Users\hi\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension can be installed from:
>        https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
> 
> [√] Connected device (4 available)
>     • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
>     • Windows (desktop)          • windows       • windows-x64    • Microsoft Windows [Version 10.0.19045.3693]
>     • Chrome (web)               • chrome        • web-javascript • Google Chrome 119.0.6045.160
>     • Edge (web)                 • edge          • web-javascript • Microsoft Edge 119.0.2151.72
> 
> [√] Network resources
>     • All expected network resources are available.
> 
> ! Doctor found issues in 1 category.



**And  the content of  android/app/build.gradle**

```
plugins {
    id "com.android.application"
    id "kotlin-android"
    id "dev.flutter.flutter-gradle-plugin"
    id 'com.google.gms.google-services'
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

android {
    namespace "com.example.vu_bloodline"
    compileSdkVersion 33
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    lintOptions {
        warning 'unchecked'
        warning 'deprecation'
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {

        applicationId "com.example.vu_bloodline"
        minSdkVersion 21
        targetSdkVersion 33
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
    }

    buildTypes {
        release {
            // signingConfig signingConfigs.debug
            // signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation(platform("com.google.firebase:firebase-bom:32.6.0"))

}

```

**Comment by danagbemava-nc** [comment]
Hi @tanvireven, the app is not running because you have commended out the signingConfig. 

Android requires all apps to be signed if they are going to be installed. Since you do not have your release config at this point, you can just use the default (debug) config. So in your buildTypes block, you should update it as follows

```groovy
buildTypes {
	release {
		signingConfig signingConfigs.debug
	}
}
```

Closing as this is not a flutter issue.

Thank you
