### ISSUE TITLE
Flutter 3.16 having bug on overriding the iOS systemOverlayUI statusBarBrightness

### ISSUE THREAD

**Issue by issacbot1499** [flutter/flutter#138671]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Upgraded to flutter 3.16.0
2. Try to change the statusBarBrightness inside ThemeData -> AppBarTheme -> systemOverlayStyle
3. Doesn't has any effect
4. Change the appearance in device setting, will changes the statusBar text to contrast with the theme selected.
5. Previously it was working in Flutter version 3.13.9

### Expected results

The statusBarBrightness should change when set in ThemeData, no like only follow the system setting.

### Actual results

The statusBarBrightness does nothing in the ThemeData -> AppBarTheme -> systemOverlayStyle

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import 'color_config.dart';
import 'dimen_config.dart';
import 'text_style_config.dart';

class ThemeConfig {
  static final lightTheme = ThemeData.light().copyWith(
    appBarTheme: AppBarTheme(
      systemOverlayStyle: const SystemUiOverlayStyle(
        statusBarColor: Colors.transparent,
        statusBarIconBrightness: Brightness.dark,
        statusBarBrightness: Brightness.light,
      ),
      titleTextStyle: TextStyleConfig.boldTextStyle(
        fontSize: DimenConfig.textSize_22,
        color: ColorConfig.blackColor,
      ),
      iconTheme: const IconThemeData(
        color: ColorConfig.blackColor,
      ),
    ),
    scaffoldBackgroundColor: ColorConfig.whiteColor,
  );

  static final darkTheme = ThemeData.dark().copyWith(
    appBarTheme: AppBarTheme(
      systemOverlayStyle: const SystemUiOverlayStyle(
        statusBarColor: Colors.transparent,
        statusBarIconBrightness: Brightness.light,
        statusBarBrightness: Brightness.dark,
      ),
      titleTextStyle: TextStyleConfig.boldTextStyle(
        fontSize: DimenConfig.textSize_22,
        color: ColorConfig.whiteColor,
      ),
      iconTheme: const IconThemeData(
        color: ColorConfig.whiteColor,
      ),
    ),
    scaffoldBackgroundColor: ColorConfig.darkCharcoalColor,
  );
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.0, on macOS 14.1.1 23B81 darwin-arm64, locale en-US)
    • Flutter version 3.16.0 on channel stable at /Users/dev/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (3 days ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (3 available)
[✓] Network resources

```

</details>

**Comment by navaronbracke** [comment]
Might be related to https://github.com/flutter/flutter/issues/138604

**Comment by ferozstk** [comment]
Same issue here.

**Comment by huycozy** [comment]
Hi @issacbot1499 
Can you please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code?

Also, it would be more intuitive if there was a demo video for this. Thanks!

**Comment by starshipcoder** [comment]
Same problem

**Comment by DennisKinuthia** [comment]
Same issue. Not the AnnotatedRegion<SystemUiOverlayStyle>() not the SystemChrome seems to have any effect on IOS

**Comment by MarcinusX** [comment]
I had the same issue. I wanted to create a new app that shows the problem:
```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Brightness statusBarBrightness = Brightness.light;

  @override
  Widget build(BuildContext context) {
    return AnnotatedRegion<SystemUiOverlayStyle>(
      value: SystemUiOverlayStyle(
        statusBarBrightness: statusBarBrightness,
        statusBarIconBrightness: statusBarBrightness,
      ),
      child: Scaffold(
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              const Text('Status bar demo'),
              ElevatedButton(
                onPressed: () => setState(
                  () {
                    if (statusBarBrightness == Brightness.light) {
                      statusBarBrightness = Brightness.dark;
                    } else {
                      statusBarBrightness = Brightness.light;
                    }
                  },
                ),
                child: const Text('Change status bar brightness'),
              )
            ],
          ),
        ),
      ),
    );
  }
}
```

However, this code worked for me on Flutter 3.16. So I thought it may be the iOS config.

Turns out I had the following entries in `Info.plist`:
```
<key>UIStatusBarStyle</key>
<string>UIStatusBarStyleLightContent</string>
<key>UIViewControllerBasedStatusBarAppearance</key>
<false/>
```

Removing them made the code above work in my app.

**Comment by ferozstk** [comment]
> I had the same issue. I wanted to create a new app that shows the problem:
> 
> ```dart
> import 'package:flutter/material.dart';
> import 'package:flutter/services.dart';
> 
> void main() {
>   runApp(const MyApp());
> }
> 
> class MyApp extends StatelessWidget {
>   const MyApp({super.key});
> 
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       theme: ThemeData(
>         colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
>         useMaterial3: true,
>       ),
>       home: const MyHomePage(),
>     );
>   }
> }
> 
> class MyHomePage extends StatefulWidget {
>   const MyHomePage({super.key});
> 
>   @override
>   State<MyHomePage> createState() => _MyHomePageState();
> }
> 
> class _MyHomePageState extends State<MyHomePage> {
>   Brightness statusBarBrightness = Brightness.light;
> 
>   @override
>   Widget build(BuildContext context) {
>     return AnnotatedRegion<SystemUiOverlayStyle>(
>       value: SystemUiOverlayStyle(
>         statusBarBrightness: statusBarBrightness,
>         statusBarIconBrightness: statusBarBrightness,
>       ),
>       child: Scaffold(
>         body: Center(
>           child: Column(
>             mainAxisAlignment: MainAxisAlignment.center,
>             children: <Widget>[
>               const Text('Status bar demo'),
>               ElevatedButton(
>                 onPressed: () => setState(
>                   () {
>                     if (statusBarBrightness == Brightness.light) {
>                       statusBarBrightness = Brightness.dark;
>                     } else {
>                       statusBarBrightness = Brightness.light;
>                     }
>                   },
>                 ),
>                 child: const Text('Change status bar brightness'),
>               )
>             ],
>           ),
>         ),
>       ),
>     );
>   }
> }
> ```
> 
> However, this code worked for me on Flutter 3.16. So I thought it may be the iOS config.
> 
> Turns out I had the following entries in `Info.plist`:
> 
> ```
> <key>UIStatusBarStyle</key>
> <string>UIStatusBarStyleLightContent</string>
> <key>UIViewControllerBasedStatusBarAppearance</key>
> <false/>
> ```
> 
> Removing them made the code above work in my app.

Thanks, work for me.

**Comment by navaronbracke** [comment]
> I had the same issue. I wanted to create a new app that shows the problem:
> 
> ```dart
> import 'package:flutter/material.dart';
> import 'package:flutter/services.dart';
> 
> void main() {
>   runApp(const MyApp());
> }
> 
> class MyApp extends StatelessWidget {
>   const MyApp({super.key});
> 
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       theme: ThemeData(
>         colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
>         useMaterial3: true,
>       ),
>       home: const MyHomePage(),
>     );
>   }
> }
> 
> class MyHomePage extends StatefulWidget {
>   const MyHomePage({super.key});
> 
>   @override
>   State<MyHomePage> createState() => _MyHomePageState();
> }
> 
> class _MyHomePageState extends State<MyHomePage> {
>   Brightness statusBarBrightness = Brightness.light;
> 
>   @override
>   Widget build(BuildContext context) {
>     return AnnotatedRegion<SystemUiOverlayStyle>(
>       value: SystemUiOverlayStyle(
>         statusBarBrightness: statusBarBrightness,
>         statusBarIconBrightness: statusBarBrightness,
>       ),
>       child: Scaffold(
>         body: Center(
>           child: Column(
>             mainAxisAlignment: MainAxisAlignment.center,
>             children: <Widget>[
>               const Text('Status bar demo'),
>               ElevatedButton(
>                 onPressed: () => setState(
>                   () {
>                     if (statusBarBrightness == Brightness.light) {
>                       statusBarBrightness = Brightness.dark;
>                     } else {
>                       statusBarBrightness = Brightness.light;
>                     }
>                   },
>                 ),
>                 child: const Text('Change status bar brightness'),
>               )
>             ],
>           ),
>         ),
>       ),
>     );
>   }
> }
> ```
> 
> However, this code worked for me on Flutter 3.16. So I thought it may be the iOS config.
> 
> Turns out I had the following entries in `Info.plist`:
> 
> ```
> <key>UIStatusBarStyle</key>
> <string>UIStatusBarStyleLightContent</string>
> <key>UIViewControllerBasedStatusBarAppearance</key>
> <false/>
> ```
> 
> Removing them made the code above work in my app.

I didn't have `UIViewControllerBasedStatusBarAppearance`, but I do need `UIStatusBarStyleLightContent` to fix an issue with status bar text contrast when showing the splash screen of my app.

**Comment by bernardoveras** [comment]
Same problem

**Comment by nohli** [comment]
> Turns out I had the following entries in `Info.plist`:
> 
> ```
> <key>UIViewControllerBasedStatusBarAppearance</key>
> <false/>
> ```
> 
> Removing them made the code above work in my app.

Also works for me, thanks! 🙏🏽

**Comment by stuartmorgan** [comment]
@LinXunFeng Have you requested a cherry-pick for that fix?

**Comment by LinXunFeng** [comment]
> @LinXunFeng Have you requested a cherry-pick for that fix?

@stuartmorgan I'm working on it : )

**Comment by miguelangelflores1993** [comment]
android same problem

**Comment by AndreCosta101** [comment]
The problem remains at this date.
