### ISSUE TITLE
Flutter SDK not found. Define location with flutter.sdk in the local.properties file.

### ISSUE THREAD

**Issue by linguowu** [flutter/flutter#13860]
when i import the project in flutter/examples/hello_world/android/app with android studio 3.0.1,it report that:
> Flutter SDK not found. Define location with flutter.sdk in the local.properties file.

 #
the build.gradle file
>def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}
#
the local.properties file
>
>ndk.dir=/Users/country5/Development/android-sdk-macosx/ndk-bundle
sdk.dir=/Users/country5/Development/android-sdk-macosx
#
 so i manually set the flutter.sdk path in th local.properties file
>ndk.dir=/Users/country5/Development/android-sdk-macosx/ndk-bundle
sdk.dir=/Users/country5/Development/android-sdk-macosx
flutter.sdk = /Users/country5/flutter
#
but the android studio still report
 > Flutter SDK not found. Define location with flutter.sdk in the local.properties file.

**Comment by long1eu** [comment]
You problem is that you have spaces in your local.properties. Try flutter.sdk=/Users/country5/flutter

**Comment by linguowu** [comment]
@long1eu 
>ndk.dir=/Users/country5/Development/android-sdk-macosx/ndk-bundle
sdk.dir=/Users/country5/Development/android-sdk-macosx
flutter.sdk=/Users/country5/flutter
#
it still report that problem

**Comment by zoechi** [comment]
Sorry for the late response.
Is this still an issue with recent Flutter versions?

**Comment by linguowu** [comment]
@zoechi, it's fine now,thanks!

**Comment by zoechi** [comment]
@linguowu thanks for the update!

**Comment by potatoker** [comment]
> @zoechi, it's fine now,thanks!

How did you fix it?

**Comment by linguowu** [comment]
@potatoker :当时是我的计算机上有两个flutter 目录，删除了其中一个就可以了；

**Comment by cgalaxy** [comment]
I was still have this problem. who could help me?

set flutter.sdk in local.properties file,still not valid

**Comment by cgalaxy** [comment]
> Sorry for the late response.
> Is this still an issue with recent Flutter versions?

I was still have this problem. Can you help me?

set flutter.sdk in local.properties file,still not valid

**Comment by emailsubjekt** [comment]
No one will help you

> > Sorry for the late response.
> > Is this still an issue with recent Flutter versions?
> 
> I was still have this problem. Can you help me?
> 
> set flutter.sdk in local.properties file,still not valid

You're starting the wrong project, you should start the flutter, not the android project inside flutter

**Comment by boyad-zl** [comment]
@cgalaxy you can upgrade your flutter version. In this way,  I solution this issue

**Comment by cgalaxy** [comment]
Thank you very much.


发自网易邮箱 iPhone 版
在2019年08月13日 17:31，boyad-zl 写道:

@cgalaxy you can upgrade your flutter version. In this way, I solution this issue

**Comment by mulugu** [comment]
Setting the ANDROID_HOME path solved the problem. Hope this helps someone

Link [Set ANDROID_HOME](https://stackoverflow.com/questions/26256279/how-to-set-android-home-path-in-ubuntu)

**Comment by himanshusharma89** [comment]
Updating the Flutter plugin and restarting the IDE helped me.
