### ISSUE TITLE
Flutter CLI run/build commands fail when Xcode 15 has a non-Runner schema selected

### ISSUE THREAD

**Issue by stx** [flutter/flutter#138694]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

`flutter run` fails with a non-Runner schema selected:

<img width="312" alt="image" src="https://github.com/flutter/flutter/assets/1284134/cd9888a5-ebed-4c35-8d10-243f1e8c33eb">

```
2023-11-19 14:49:36.313 xcodebuild[10466:4834422] Requested but did not find extension point with identifier Xcode.InterfaceBuilderBuildSupport.PlatformDefinition
[+1461 ms] Error launching application on [device name]
```

`flutter run` succeeds with the Runner schema selected:

<img width="158" alt="image" src="https://github.com/flutter/flutter/assets/1284134/7073a203-2465-4dfc-8e89-59810c2d840c">

### Expected results

Ideally shouldn't matter what Xcode has selected. Makes development very annoying in multi-target apps.

If the Flutter CLI cannot be made to work with a different schema setting, it should select the Runner schema automatically. Just failing is pretty miserable and takes awhile to figure out why.

### Actual results

Xcode schema selection determines the success/fail state of flutter commands.

### Code sample

N/A

### Screenshots or Video

N/A

### Logs

N/A

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.0, on macOS 14.1.1 23B2082 darwin-arm64, locale en-US)
    • Flutter version 3.16.0 on channel stable at /Users/james/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (4 days ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/james/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (3 available)
    • Apollo (mobile) • 00008110-0004752E3AB8801E • ios            • iOS 17.0.3 21A360
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 14.1.1 23B2082 darwin-arm64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 119.0.6045.159

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by stx** [comment]
> Hi @stx
> 
> > with a non-Runner schema selected
> 
> Could you share how to create this case?

Add a target in Xcode, like a watch app, and select it from the menu at the top.

**Comment by stx** [comment]
> Thanks, I also created one, but the watch simulator is not listed in `flutter devices`. I wonder how can you select/pick it when running Flutter with CLI? (sorry I'm not experienced in the watch development).

The watch simulator will not be listed in `flutter devices` and you cannot select it when running Flutter with the CLI. These things are unrelated to the original issue, which is that Flutter CLI run/build commands fail when Xcode 15 has a non-Runner schema selected

**Comment by huycozy** [comment]
Yes, but even when I select a non-Runner target from XCode, `flutter run` still works fine:

 ![Screenshot 2023-11-24 at 12 22 26](https://github.com/flutter/flutter/assets/104349824/c8ba8fbf-7e5b-4cee-a656-4a4d44895424)

Could you share the entire output of `flutter run -v`?

**Comment by stx** [comment]
@huycozy That file has proprietary data and is too large for GitHub, so here is the relevant portion from `flutter run`:

```
[  +38 ms] stderr: {"command":"debug","xcodePath":"/Applications/Xcode.app","projectPath":"/redacted/Runner.xcodeproj","projectName":"Runner","expectedConfigurationBuildDir":"/redacted/build/ios/iphoneos","workspacePath":"/redacted/Runner.xcworkspace","targetDestinationId":"00008110-0004752E3AB8801E","targetSchemeName":"Runner","skipBuilding":true,"launchArguments":["--enable-dart-profiling"],"closeWindowOnStop":null,"promptToSaveBeforeClose":null,"verbose":true}
[  +97 ms] stderr: Workspace: /redacted/ios/Runner.xcworkspace
[  +50 ms] stderr: Device: Any watchOS Device (dvtdevice-DVTiOSDevicePlaceholder-watchos:placeholder)
[  +44 ms] stderr: Device: Any watchOS Simulator Device (dvtdevice-DVTiOSDeviceSimulatorPlaceholder-watchsimulator:placeholder)
[  +39 ms] stderr: Device: Apple Watch SE (40mm) (2nd generation) (B658BC9E-52CA-4D51-8D8D-E2087723F2B1)
[  +40 ms] stderr: Device: Apple Watch SE (40mm) (2nd generation) (B658BC9E-52CA-4D51-8D8D-E2087723F2B1)
[  +37 ms] stderr: Device: Apple Watch SE (44mm) (2nd generation) (A23C7F17-20DA-48C6-BE7E-AE0A75A4E073)
[  +68 ms] stderr: Device: Apple Watch SE (44mm) (2nd generation) (A23C7F17-20DA-48C6-BE7E-AE0A75A4E073)
[  +43 ms] stderr: Device: Apple Watch Series 9 (41mm) (37E182CB-C725-48A9-8596-5C3DA87C3808)
[  +38 ms] stderr: Device: Apple Watch Series 9 (41mm) (37E182CB-C725-48A9-8596-5C3DA87C3808)
[  +35 ms] stderr: Device: Apple Watch Series 9 (45mm) (D123142C-2B60-4230-9ECD-B7B896E840B2)
[  +34 ms] stderr: Device: Apple Watch Series 9 (45mm) (D123142C-2B60-4230-9ECD-B7B896E840B2)
[  +44 ms] stderr: Device: Apple Watch Ultra 2 (49mm) (F4E8D728-CD40-43BB-BAB5-0CCF16EE540F)
[  +52 ms] stderr: Device: Apple Watch Ultra 2 (49mm) (F4E8D728-CD40-43BB-BAB5-0CCF16EE540F)
[  +13 ms] {"status":false,"errorMessage":"Unable to find target device. Ensure that the device is paired, unlocked, connected, and has an iOS version at least as high as the Minimum Deployment.","debugResult":null}
```

The devices listed are _not_ from the Runner scheme. They are from the Apple Watch scheme that is selected in Xcode.

When changing the scheme in Xcode to Runner, `flutter run` works.

**Comment by huycozy** [comment]
Could you confirm this issue also happens with a newly created Flutter project? If this is only reproduced on your project, we need to know which configuration made this issue occur.
