### ISSUE TITLE
connected device problem

### ISSUE THREAD

**Issue by AnandMohokar09** [flutter/flutter#138601]
I followed all the steps for android studio and flutter . Successfully created a virtual device but when i run the command flutter doctor it shows error of " Connected device (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Unable to run "adb", check your Android SDK installation and ANDROID_SDK_ROOT environment variable:
      C:\Users\Anand Mohokar\AppData\Local\Android\sdk\platform-tools\adb.exe"

**Comment by dam-ease** [comment]
Thanks for filing this.
Can you try out the possible solutions in these threads to see if any works in your case:
https://stackoverflow.com/questions/65262594/flutter-unable-to-run-adb-check-your-android-sdk-installation-and-android-sdk
https://github.com/flutter/flutter/issues/72101
