### ISSUE TITLE
20% regression in platform channels benchmark

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#138689]
On the engine roll https://github.com/flutter/flutter/pull/138647, SkiaPerf is reporting a ~20% regression in the `platform_channel_basic_standard_2host_large` metric from the `platform_channels_benchmarks` benchmark:

https://flutter-flutter-perf.skia.org/e/?begin=1700183293&end=1700312483&keys=X25251bae98644a72a9a678545659f5cc&num_commits=50&request_type=1&xbaroffset=38025

That Engine -> Dart roll has a Dart SDK roll (https://github.com/flutter/engine/pull/48187), and from that roll, the following commit looks like it could be related:

https://dart.googlesource.com/sdk.git/+/904354f108818630c98ef5d019bc0a99e1c6f2fd

cc @gaaclarke @sstrickl @mkustermann

**Comment by mkustermann** [comment]
From the skia link it seems this may be 32-bit arm - which we also saw a regression from golem. I think @sstrickl is looking into this.

**Comment by zanderso** [comment]
Yes, Moto G4 is 32-bit.
