### ISSUE TITLE
[codesign] notarytool submit is recently flaking on dart-internal builders

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#138636]
See https://ci.chromium.org/ui/p/dart-internal/builders/flutter/Linux%20engine_release_builder/737/overview. Reruns eventually pass.

The notarytool submit command seems to be failing occasionally, which prevents the overall builder.

We should add retries around this to deal with any intermittent flakiness from Apple.

**Comment by godofredoc** [comment]
Could it be quota?

**Comment by XilaiZhang** [comment]
Umm my understanding is that the root cause might be something other than retry. (previous code sign implementations that had retry didn't seem to make a difference)
