### ISSUE TITLE
I can't change the flutter sdk version using the fvm use 3.16.0 command

### ISSUE THREAD

**Issue by vanred79** [flutter/flutter#138685]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I can't change the flutter sdk version using the fvm use 3.16.0 command

### Expected results

I expected the flutter sdk version to change, but this did not happen. 

### Actual results

After running this command PS E:\myapplication> fvm use 3.16.0 came out PS E:\myapplication> fvm use 3.16.0. Tell me what I did wrong? And how to change the current version of flutter sdk to 3.16.0?

### Code sample

<details><summary>Code sample</summary>

flutter --version

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media h
![Скрин 1](https://github.com/flutter/flutter/assets/73446311/b341f2fc-abcd-470a-8b9f-2dce9a77d74f)
ere]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
PS E:\myapplication> flutter doctor -v
[√] Flutter (Channel dev, 3.4.0-17.2.pre, on Microsoft Windows [Version 10.0.22621.2715], locale ru-KZ)
    • Flutter version 3.4.0-17.2.pre on channel dev at E:\flutter_windows_3.16.0-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d6260f127f (1 year, 2 months ago), 2022-09-21 13:33:49 -0500
    • Engine revision 3950c6140a
    • Dart version 2.19.0 (build 2.19.0-146.2.beta)
    • DevTools version 2.16.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\serzh\AppData\Local\Android\sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    • Flutter extension version 3.76.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.2715]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 119.0.6045.160
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 117.0.2045.41

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.


```

</details>

**Comment by stuartmorgan** [comment]
Issues with third-party tools need to be reported to the authors of those tools.

Closing as `fvm` is not made my the Flutter team.

**Comment by vanred79** [comment]
Tell me what the command PS E:\myapplication> E:\flutter\bin\flutter.bat doctor --verbose means?

**Comment by vanred79** [comment]
It outputs the following:
  Flutter (Channel dev, 3.4.0-17.2.pre, on Microsoft Windows [Version 10.0.22621.2715], locale ru-KZ)
     • Flutter version 3.4.0-17.2.pre on channel dev at E:\flutter
     • Upstream repository https://github.com/flutter/flutter.git
     • Framework revision d6260f127f (1 year, 2 months ago), 2022-09-21 13:33:49 -0500
     • Engine revision 3950c6140a
     • Dart version 2.19.0 (build 2.19.0-146.2.beta)
     • DevTools version 2.16.0

**Comment by vanred79** [comment]
And the command flutter doctor -v
Gives a different result:
PS E:\myapplication> flutter doctor -v
[√] Flutter (Channel stable, 3.16.0, on Microsoft Windows [Version 10.0.22621.2715], locale ru-KZ)
     • Flutter version 3.16.0 on channel stable at E:\flutter_windows_3.16.0-stable\flutter
     • Upstream repository https://github.com/flutter/flutter.git
     • Framework revision db7ef5bf9f (4 days ago), 2023-11-15 11:25:44 -0800
     • Engine revision 74d16627b9
     • Dart version 3.2.0
     • DevTools version 2.28.2

**Comment by vanred79** [comment]
The problem is that I cannot install flutter_map_marker_cluster from the Dart SDK version. Tell me how you can solve this problem?
