### ISSUE TITLE
XCTest-XCUITest: google_maps_flutter (ios13) fails [XCode 15.1 beta 3]

### ISSUE THREAD

**Issue by rzambroni** [flutter/flutter#138640]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Install XCode 15.1 beta 3 and iOS 17.2 Simulator.
2. Clone the Flutter packages repository: git clone https://github.com/flutter/packages
3. Navigate to the google_maps_flutter (ios13) example iOS directory: cd packages/google_maps_flutter/google_maps_flutter_ios/example/ios13/ios
4. Get the Flutter dependencies: flutter pub get
5. Install the required CocoaPods dependencies: pod install
6. Run the test using the following command (replace $simulator_id with the actual simulator ID):
xcodebuild test -workspace Runner.xcworkspace -scheme Runner \
-destination 'platform=iOS Simulator,id=$simulator_id' > logs.txt

### Expected results

Running all tests should succeed.

### Actual results

The following test case fails on:

Flutter master  3.17.0-10.0.pre.13

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

[google_maps_flutter_google_maps_flutter_ios_example_ios13-master-logs (1).txt](https://github.com/flutter/flutter/files/13427407/google_maps_flutter_google_maps_flutter_ios_example_ios13-master-logs.1.txt)

```console
Test Case '-[RunnerUITests testMarkerDraggingCallbacks]' started.
    t =     0.00s Start Test at 2023-11-16 10:57:14.730
    t =     0.08s Set Up
    t =     0.09s Open dev.flutter.plugins.googleMobileMapsExample
    t =     0.09s     Launch dev.flutter.plugins.googleMobileMapsExample
/Users/haironchaviano/Documents/packages/packages/google_maps_flutter/google_maps_flutter_ios/example/ios13/ios/RunnerUITests/RunnerUITests.m:17: error: -[RunnerUITests testMarkerDraggingCallbacks] : Failed to get launch progress for <XCUIApplicationImpl: 0x600000cd96b0 dev.flutter.plugins.googleMobileMapsExample at /Users/haironchaviano/Library/Developer/Xcode/DerivedData/Runner-flcfdsgcsdpgbwhlgbrgygeotbkd/Build/Products/Debug-iphonesimulator/Runner.app>: Simulator device returned an error for the requested operation. The request was denied by service delegate (SBMainWorkspace). (Underlying Error: The request to open "dev.flutter.plugins.googleMobileMapsExample" failed. The request was denied by service delegate (SBMainWorkspace). (Underlying Error: The operation couldn't be completed. The process failed to launch. (Underlying Error: The operation couldn't be completed. Launch failed. (Underlying Error: Launchd job spawn failed))))
    t =     0.40s Tear Down
Test Case '-[RunnerUITests testMarkerDraggingCallbacks]' failed (0.428 seconds).
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.17.0-10.0.pre.13, on macOS 14.0 23A344 darwin-arm64, locale en-UY)

Flutter version 3.17.0-10.0.pre.13 on channel master at /Users/haironchaviano/Documents/flutter

Upstream repository [GitHub - flutter/flutter: Flutter makes it easy and fast to build beautiful apps for mobile and beyond](https://github.com/flutter/flutter.git) 

Framework revision ca31aa17b2 (20 hours ago), 2023-11-15 14:48:18 -0500

Engine revision 30327eae08

Dart version 3.3.0 (build 3.3.0-135.0.dev)

DevTools version 2.30.0-dev.4

 

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)

Android SDK at /Users/haironchaviano/Library/Android/sdk

Platform android-34, build-tools 34.0.0

Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java

Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

All Android licenses accepted.

 

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)

Xcode at /Applications/Xcode-beta.app/Contents/Developer

Build 15C5059c

CocoaPods version 1.13.0

 

[✓] Chrome - develop for the web

Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

 

[✓] Android Studio (version 2022.3)

Android Studio at /Applications/Android Studio.app/Contents

Flutter plugin can be installed from:

      🔨 [Flutter - IntelliJ IDEs Plugin | Marketplace](https://plugins.jetbrains.com/plugin/9212-flutter) 

Dart plugin can be installed from:

      🔨 [Dart - IntelliJ IDEs Plugin | Marketplace](https://plugins.jetbrains.com/plugin/6351-dart) 

Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

 

[✓] VS Code (version 1.84.2)

VS Code at /Users/haironchaviano/Downloads/Visual Studio Code.app/Contents

Flutter extension version 3.76.0

 

[✓] Connected device (5 available)

SM G950U (mobile)          • 98897a314d334d504a                   • android-arm64  • Android 9 (API 28)

iPhone 15 Pro (mobile)     • 07D35B8C-CE19-4703-82F7-D0FC5AD8905F • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)

iPhone 15 Pro Max (mobile) • 2D8A5E37-6BE7-4735-BBB4-9E5A5427E7D2 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)

macOS (desktop)            • macos                                • darwin-arm64   • macOS 14.0 23A344 darwin-arm64

Chrome (web)               • chrome                               • web-javascript • Google Chrome 119.0.6045.159

 

[✓] Network resources

All expected network resources are available.
```

</details>

**Comment by hellohuanlin** [comment]
This seems to be an issue in Xcode or simulator. Can you try to relaunch xcode or relaunch/reset the simulator?

**Comment by rzambroni** [comment]
Hi @hellohuanlin, this continues to fail after relaunching both XCode and the sim. (I attached the full log of the first run to the ticket) and here is the log of this re-test. I agree this could be an issue introduced with Xcode 15.1 Beta 3, let me know if there is something else we can do to help.

[ios13_logs.txt](https://github.com/flutter/flutter/files/13427443/ios13_logs.txt)

**Comment by hellohuanlin** [comment]
@rzambroni have you tried resetting simulator? (Device -> Erase all contents and settings)

**Comment by hellohuanlin** [comment]
I did some research and it looks like a common problem with simulator, and many are fixed by resetting the simulator: 

![Screenshot 2023-11-28 at 2 54 59 PM](https://github.com/flutter/flutter/assets/41930132/dbac3d80-4505-4658-a247-97a9e09ac4c8)
