### ISSUE TITLE
Flutter 3.16 CupertinoApp and Material Widgets

### ISSUE THREAD

**Issue by Fernandomr88** [flutter/flutter#138621]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Just ran the app as usual

### Expected results

So I have an App that since upgraded to Flutter 3.16.0 has suffered some changes on colors and text.

I have attached below some pictures of the screen rendered using both Flutter 3.13.9 and 3.16.0 and also the Color Measure tool results on each screen.

What I expected was that the colors remained the same, since I haven't found anything on the changelogs saying anything about changes on that matter.

Also looking at AppBar title, it changed to black with default font, and it was white before with my font.

### Actual results

Different colors:

On v3.13.9 those buttons where white (255, 255, 255) and on v3.16.0 became "purple-ish" (246, 240, 248)

Also, AppBar title became black and with different font.

### Code sample

This is my CupertinoApp (unchanged from each version)

```dart
    final CupertinoApp iosApp = CupertinoApp(
      title: _title,
      debugShowCheckedModeBanner: false,
      theme: const CupertinoThemeData(
        primaryColor: FortmobileColors.purple,
        barBackgroundColor: FortmobileColors.purple,
        scaffoldBackgroundColor: FortmobileColors.purple,
        textTheme: CupertinoTextThemeData(
          textStyle: TextStyle(fontFamily: 'Inter'),
          actionTextStyle: TextStyle(fontFamily: 'Inter'),
          navActionTextStyle: TextStyle(fontFamily: 'Inter'),
          dateTimePickerTextStyle: TextStyle(fontFamily: 'Inter'),
          pickerTextStyle: TextStyle(fontFamily: 'Inter'),
          tabLabelTextStyle: TextStyle(fontFamily: 'Inter'),
          navTitleTextStyle: TextStyle(fontFamily: 'Inter'),
          navLargeTitleTextStyle: TextStyle(fontFamily: 'Inter'),
        ),
        brightness: Brightness.light,
      ),
      initialRoute: '/',
      routes: Routes.getRoutes(context),
      navigatorObservers: <NavigatorObserver>[FirebaseAnalyticsObserver(analytics: Requests.analytics)],
      navigatorKey: NavigationService.navigatorKey,
      color: FortmobileColors.purple,
      localizationsDelegates: const [
        GlobalMaterialLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        DefaultWidgetsLocalizations.delegate,
      ],
      supportedLocales: const [Locale('pt', 'BR')],
    );
```

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

### Flutter 3.13.9:

![Simulator Screenshot - iPhone 14 Pro - 2023-11-17 at 10 44 54](https://github.com/flutter/flutter/assets/14304128/0f3470f3-1f8d-4657-a01a-6cd3902d127c)

## COLOR:

![Captura de Tela 2023-11-17 às 11 30 48](https://github.com/flutter/flutter/assets/14304128/74ba7da4-65a4-496e-8632-0082a88ae964)

### Flutter 3.16.0:

![Simulator Screenshot - iPhone 14 Pro - 2023-11-17 at 11 26 48](https://github.com/flutter/flutter/assets/14304128/e30c8879-8e9a-4b78-8c74-478339a9d912)

## COLOR
![Captura de Tela 2023-11-17 às 11 30 28](https://github.com/flutter/flutter/assets/14304128/3111dfcd-5f77-4bc8-a17e-debbbcd62bc4)

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.0, on macOS 14.1 23B74 darwin-arm64, locale pt-BR)
    • Flutter version 3.16.0 on channel stable at /Users/fernandorocha/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (2 days ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/fernandorocha/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (2 available)
    • iPhone 14 Pro (mobile) • FD97ADA4-9B37-4F8B-87EB-60EB9796CC71 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 119.0.6045.159
    ! Error: Browsing on the local area network for iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Fernando Rocha. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by navaronbracke** [comment]
In Flutter 3.16.0, the default for `useMaterial3` is `true`. Before this release it was `false`. Perhaps that is why you are seeing this change?

**Comment by TahaTesser** [comment]
Hi @Fernandomr88 
@navaronbracke is correct. You can set `ThemeData. useMaterial3` to `false` if you're using `MaterialApp` somewhere in your app.

**Comment by Fernandomr88** [comment]
> In Flutter 3.16.0, the default for `useMaterial3` is `true`. Before this release it was `false`. Perhaps that is why you are seeing this change?
> 
> 
> 
> You seem to be using CupertinoApp, which should not be affected, but we don't see the rest of your code so I can only do a guess.

Thanks for your resposne, 
It is already false.

**Comment by TahaTesser** [comment]
@Fernandomr88 
That sounds unusual.

Could you please provide a minimal reproducible code sample?

**Comment by Fernandomr88** [comment]
> @Fernandomr88 That sounds unusual.
> 
> Could you please provide a minimal reproducible code sample?

Sure.

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const CupertinoApp(
      title: "test",
      debugShowCheckedModeBanner: false,
      theme: CupertinoThemeData(
        primaryColor: Colors.green,
        barBackgroundColor: Colors.green,
        scaffoldBackgroundColor: Colors.green,
        brightness: Brightness.light,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
      color: Colors.green,
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

This produces this, with a purple-ish floating button, even if theme is all green.

![simulator_screenshot_9DCBE1F6-8462-4365-8A41-C81B81098FC2](https://github.com/flutter/flutter/assets/14304128/b5a97167-485c-4df6-af8a-15e2bd95fe81)

**Comment by Fernandomr88** [comment]
I was reading on the CupertinoApp class and it says

/// The [CupertinoApp] widget isn't a required ancestor for other Cupertino
/// widgets, but many Cupertino widgets could depend on the [CupertinoTheme]
/// widget, which the [CupertinoApp] composes. **If you use Material widgets, a
/// [MaterialApp] also creates the needed dependencies for Cupertino widgets.**

I was wondering if the problem is that `MaterialApp` is instantiated to create those Widgets such as `Container` or `Scaffold` and by consequence `useMaterial3` is true in this case (since now it's true)

**Comment by Fernandomr88** [comment]
It seems that using any Material widget (most of them) comes with Material 3 pattern.

using CupertinoPageScaffold instead of Scaffold made it inherit correct title style, navbar style and scaffold background.

Note that the floating button (material widget) is still purple (material3 design).

Here's the code and produced example:

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const CupertinoApp(
      debugShowCheckedModeBanner: false,
      theme: CupertinoThemeData(
        primaryColor: Colors.green,
        barBackgroundColor: Colors.green,
        // scaffoldBackgroundColor: Colors.white,

        brightness: Brightness.light,
        textTheme: CupertinoTextThemeData(
          primaryColor: Colors.green,
          navTitleTextStyle: TextStyle(
            color: Colors.yellow,
            fontWeight: FontWeight.bold,
            fontSize: 20,
          ),
        ),
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
      color: Colors.green,
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(
        middle: Text(widget.title),
      ),
      child: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            FloatingActionButton(
              onPressed: () {},
              tooltip: 'Increment',
              child: const Icon(Icons.add),
            ),
          ],
        ),
      ),
    );
  }
}

```

![image](https://github.com/flutter/flutter/assets/14304128/e7c5817e-37a1-43b2-9e9c-bcf9153c17bd)

**Comment by TahaTesser** [comment]
Hi @Fernandomr88 
I can produce it with the default M3 flag using code sample. Looks like there is no way to disable M3 from `CupertinoThemeData`

<img width="660" alt="Screenshot 2023-11-20 at 12 03 20" src="https://github.com/flutter/flutter/assets/48603081/123a69f7-86d4-46b5-a3ed-ed1b3ffb3818">

You can workaround this by wrapping your `CupertinoPageScaffold` with `Theme`. This will disable M3 for the descendent material widgets

```dart
  Widget build(BuildContext context) {
    return Theme(
      data: ThemeData(useMaterial3: false),
      child: CupertinoPageScaffold(
```

**Comment by TahaTesser** [comment]
cc: @HansMuller

**Comment by Fernandomr88** [comment]
> Hi @Fernandomr88 I can produce it with the default M3 flag using code sample. Looks like there is no way to disable M3 from `CupertinoThemeData`
> 
> <img alt="Screenshot 2023-11-20 at 12 03 20" width="660" src="https://user-images.githubusercontent.com/48603081/284229053-123a69f7-86d4-46b5-a3ed-ed1b3ffb3818.png">
> You can workaround this by wrapping your `CupertinoPageScaffold` with `Theme`. This will disable M3 for the descendent material widgets
> 
> ```dart
>   Widget build(BuildContext context) {
>     return Theme(
>       data: ThemeData(useMaterial3: false),
>       child: CupertinoPageScaffold(
> ```
> 
> <img alt="Screenshot 2023-11-20 at 12 08 51" width="660" src="https://user-images.githubusercontent.com/48603081/284230654-06b55c4c-02c3-4664-99fd-7926860bc9e0.png">

Thanks for the suggestion, what I did was wrap CupertinoApp with Theme to temporary solve the whole app issue.

**Comment by MitchellGoodwin** [comment]
Looking into this. Worth noting that if you include `Theme` under `CupertinoApp` it will actually overwrite your CupertinoTheme. `Theme` creates it's own `CupertinoTheme` in order to solve issues in the opposite direction.

**Comment by Fernandomr88** [comment]
> Looking into this. Worth noting that if you include `Theme` under `CupertinoApp` it will actually overwrite your CupertinoTheme. `Theme` creates it's own `CupertinoTheme` in order to solve issues in the opposite direction.

Under or above? What I did was add `Theme` and `CupertinoApp` inside `Theme`

```dart
  Widget build(BuildContext context) {
    return Theme(
      data: ThemeData(useMaterial3: false),
      child: CupertinoApp(
```

**Comment by MitchellGoodwin** [comment]
Under. If you structure it that way it should work as expected.

**Comment by MitchellGoodwin** [comment]
Still working through this. The work arounds mentioned above work, but trying to find a good way for the two themes to get along in Cupertino.
