### ISSUE TITLE
Apple Fairplay Streaming support.

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#13868]
_From @nampdn on November 21, 2017 1:56_

Hi, It would be great if we can make this plugin work with Apple FPS natively.
Can we work on [this](https://developer.apple.com/streaming/fps/) ?

_Copied from original issue: sigurdm/video_player#8_

**Comment by mit-mit** [comment]
Hi @nampdn, we moved the issue here as this plugin is now maintained out of https://github.com/flutter/plugins

**Comment by nampdn** [comment]
Awesome!!
I'm very excited to see this on progress.

**Comment by sigurdm** [comment]
Don't be excited too early :( . We moved the issue to the new location - but we currently have no short-term plans of providing fps or other DRM support in the video_player.

**Comment by darwinvtomy** [comment]
I tried implement widevine on flutter using exoplayer. I might need some multi drm content. This is my code https://github.com/darwinvtomy/drm_wv_fp_player

**Comment by JohnGalt1717** [comment]
Here's  Microsoft's samples. The drm is playready, widevine or fair play depending on device so should be a good test.

The aes with token sample uses headers to pass the token so good test for that.

Basically all 4 should be supported now that this is on the web and desktop by the time this is done.

**Comment by xinoxapps** [comment]
Any news on this topic?

Did anyone succeeded

**Comment by stuartmorgan** [comment]
Closing as a duplicate of https://github.com/flutter/flutter/issues/24923 since that's where most of the voting and discussion is.
