### ISSUE TITLE
 I can't git push flutter file

### ISSUE THREAD

**Issue by Yeonnies** [flutter/flutter#138673]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I make my flutter_application file for study.
It doesn't have any problem, anyway, I want to git push it but I have a problem in here.
"remote: error: File flutter_application_1/windows/flutter/ephemeral/flutter_windows.dll.pdb is 238.41 MB; this exceeds GitHub's file size limit of 100.00 MB"
This error is my error. I tried a lot to fix this error.
First, we used rm --chache to delete this large file, but only the warning 
"fatal: pathspec 'flutter_application_1/windows/flutter/ephemeral/flutter_windows.dll.pdb' did not match any files"
I using LFS and do gitignore but there was always this error. What's even more annoying is that I don't even know where this file is. I followed the file location, but I couldn't find this file in File Explorer. I promised to post my flutter practice, and I want to find a solution to this problem as soon as possible.

### Actual results

I can't do git push.
remote: error: File flutter_application_1/windows/flutter/ephemeral/flutter_windows.dll.pdb is 238.41 MB; this exceeds GitHub's file size limit of 100.00 MB   
I saw this error text but I can't fixed it.

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

``[√] Flutter (Channel stable, 3.13.9, on Microsoft Windows [Version 10.0.19045.3570], locale ko-KR)
    • Flutter version 3.13.9 on channel stable at C:\Users\eliye\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (3 weeks ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\eliye\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.3.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32825.248
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.1.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.84.2)
    • VS Code at C:\Users\eliye\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.76.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.3570]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 119.0.6045.124
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 119.0.2151.58

[√] Network resources
    • All expected network resources are available.

• No issues found!"

</details>

**Comment by moffatman** [comment]
Not any flutter issue. But probably the reason you can't delete it, is you already committed it? So I would look in git history, and revert that commit, and restore any changes to other affected files

**Comment by danagbemava-nc** [comment]
As pointed out above. This is not a flutter issue. 

Kindly follow the recommendation above. 

Closing from here. 

Thank you
