### ISSUE TITLE
Scrollable Tabs have a gap on the left

### ISSUE THREAD

**Issue by Epikur86** [flutter/flutter#138606]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Since  3.16 there is a gap on the left side, when using scrollable Tabs. In 3.13 the gap was much smaller, which looked better. Can't find a workaround yet. 

```
import 'package:flutter/material.dart';

/// Flutter code sample for [TabController].

void main() => runApp(const TabControllerExampleApp());

class TabControllerExampleApp extends StatelessWidget {
  const TabControllerExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: TabControllerExample(),
    );
  }
}

const List<Tab> tabs = <Tab>[
  Tab(text: 'Zeroth'),
  Tab(text: 'First'),
  Tab(text: 'Second'),
  Tab(text: 'Zeroth'),
  Tab(text: 'First'),
  Tab(text: 'Second'),
  Tab(text: 'Zeroth'),
  Tab(text: 'First'),
  Tab(text: 'Second'),
  Tab(text: 'Zeroth'),
  Tab(text: 'First'),
  Tab(text: 'Second'),
];

class TabControllerExample extends StatelessWidget {
  const TabControllerExample({super.key});

  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: tabs.length,
      // The Builder widget is used to have a different BuildContext to access
      // closest DefaultTabController.
      child: Builder(builder: (BuildContext context) {
        final TabController tabController = DefaultTabController.of(context);
        tabController.addListener(() {
          if (!tabController.indexIsChanging) {
            // Your code goes here.
            // To get index of current tab use tabController.index
          }
        });
        return Scaffold(
          appBar: AppBar(
            bottom: const TabBar(
              isScrollable: true,
              tabs: tabs,
            ),
          ),
          body: TabBarView(
            children: tabs.map((Tab tab) {
              return Center(
                child: Text(
                  '${tab.text!} Tab',
                  style: Theme.of(context).textTheme.headlineSmall,
                ),
              );
            }).toList(),
          ),
        );
      }),
    );
  }
}
```

### Expected results

Gap was smaller

### Actual results

Gap ist too big.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![Screenshot_1700215081](https://github.com/flutter/flutter/assets/71758118/c0fa3e16-23f5-40b7-a506-a9860d2e56dc)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by appcapsergen** [comment]
+1, same issue for me!

**Comment by danagbemava-nc** [comment]
Hi @Epikur86, for scrollable tabs, the default alignment is `TabAlignment.startOffset` which adds 52px padding to the start of the Tab. 

Does switching to `TabAligmnent.start` resolve this issue for you?

**Comment by appcapsergen** [comment]
That does solve the issue, thanks!

**Comment by navaronbracke** [comment]
@appcapsergen This is mentioned in the breaking changes for 3.16.0 here: https://docs.flutter.dev/release/breaking-changes/tab-alignment

**Comment by Epikur86** [comment]
Thanks a lot. TabAligmnent.center was what I was looking for.

**Comment by MAlazhariy** [comment]
`tabAlignment: TabAlignment.start` in the `TabBar` Solved my issue.
Thanks @danagbemava-nc for the solution.

**Comment by JGeek00** [comment]
I had the same issue and the `tabAlignment: TabAlignment.start` fixed it. Thank you.

**Comment by danagbemava-nc** [comment]
Closing this as solved. 

Thank you

**Comment by TahaTesser** [comment]
Please follow this migration guide https://docs.flutter.dev/release/breaking-changes/tab-alignment.

The `TabBar` now supports several tab alignments in both scrollable and non-scrollable states.
You can customize the tabs alignment in the new `TabBar.tabAlignment` property. 
Use `TabAlignment.start` to aligns to the start of the `TabBar`.

**Comment by gemunet** [comment]
For some reason the space on the sides of the "indicator" is because they changed a default property, now you must set it explicitly like this so that it looks like before

```
TabBar(
     indicatorSize: TabBarIndicatorSize.tab,
```
