### ISSUE TITLE
Error `error: macro name must be an identifier` when building on Fedora 39

### ISSUE THREAD

**Issue by zyrouge** [flutter/flutter#138665]
### Steps to reproduce

1. Install `media-kit`.
2. Compile the program.

### Expected results

Successfully compile.

### Actual results

Get an error saying `<command line>:1:9: error: macro name must be an identifier`. But as far as the log goes, the compile command seems to have `-pthread` seems to be prefixed by `-D` but also `-pthread` passed at the end. This seems to occur for me only on Fedora 39, it did not occur in Fedora 38. The only thing changed in my Clang version from 16 to 17. I do not face this issue in Ubuntu LTS with Clang 16. I checked every possible `CMakeLists.txt` in my project to make sure no such flags were being defined. I've also created an issue in `media-kit`'s repository (https://github.com/media-kit/media-kit/issues/595). Could this be a Clang issue or is it just a me thing?

### Logs

<details><summary>Logs</summary>

```
[+2082 ms] [1/19] Building CXX object plugins/media_kit_native_event_loop/shared/CMakeFiles/media_kit_native_event_loop.dir/media_kit_native_event_loop.cc.o
[   +2 ms] FAILED: plugins/media_kit_native_event_loop/shared/CMakeFiles/media_kit_native_event_loop.dir/media_kit_native_event_loop.cc.o 
[  +56 ms] /usr/bin/clang++ -D-pthread -DAPPLICATION_ID=\"io.github.yukino_org.kazahana\" -DDART_SHARED_LIB -D_REENTRANT -Dmedia_kit_native_event_loop_EXPORTS -isystem
/usr/include/spa-0.2 -isystem /usr/include/vapoursynth -isystem /usr/include/freetype2 -isystem /usr/include/cdio -isystem /usr/include/ffmpeg -isystem
/usr/include/lua-5.1 -isystem /usr/include/SDL2 -isystem /usr/include/uchardet -isystem /usr/include/AL -isystem /usr/include/pipewire-0.3 -isystem /usr/include/libdrm
-isystem /usr/include/ffnvcodec -isystem /usr/include/sysprof-6 -isystem /usr/include/python3.12 -isystem /usr/include/fribidi -isystem /usr/include/glib-2.0 -isystem
/usr/lib64/glib-2.0/include -isystem /usr/include/libpng16 -isystem /usr/include/libxml2 -isystem /usr/include/harfbuzz -g -std=gnu++17 -fPIC -D_REENTRANT -pthread -MD
-MT plugins/media_kit_native_event_loop/shared/CMakeFiles/media_kit_native_event_loop.dir/media_kit_native_event_loop.cc.o -MF
plugins/media_kit_native_event_loop/shared/CMakeFiles/media_kit_native_event_loop.dir/media_kit_native_event_loop.cc.o.d -o
plugins/media_kit_native_event_loop/shared/CMakeFiles/media_kit_native_event_loop.dir/media_kit_native_event_loop.cc.o -c
/home/zyrouge/Vault/ZDev/yukino-org/kazahana/linux/flutter/ephemeral/.plugin_symlinks/media_kit_native_event_loop/src/media_kit_native_event_loop.cc
[  +27 ms] In file included from <built-in>:446:
[        ] <command line>:1:9: error: macro name must be an identifier
[   +3 ms]     1 | #define -pthread 1
[        ]       |         ^
[        ] 1 error generated.
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel beta, 3.16.0-0.5.pre, on Fedora Linux 39 (Workstation Edition) 6.5.11-300.fc39.x86_64, locale en_US.UTF-8)
    • Flutter version 3.16.0-0.5.pre on channel beta at /home/zyrouge/TPBinaries/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision adc7dfe87e (10 days ago), 2023-11-07 18:30:33 -0800
    • Engine revision ab14aba1d5
    • Dart version 3.2.0 (build 3.2.0-210.4.beta)
    • DevTools version 2.28.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/zyrouge/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /home/zyrouge/.asdf/shims/java
    • Java version OpenJDK Runtime Environment Zulu17.46+19-CA (build 17.0.9+8-LTS)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /var/lib/flatpak/exports/bin/com.google.Chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 17.0.3 (Fedora 17.0.3-1.fc39)
    • cmake version 3.27.7
    • ninja version 1.11.1
    • pkg-config version 1.9.5

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Fedora Linux 39 (Workstation Edition) 6.5.11-300.fc39.x86_64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 119.0.6045.123 unknown

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by iapicca** [comment]
I think nobody should receive an answer like [this](https://github.com/media-kit/media-kit/issues/595#issuecomment-1812062453)!

I recommend to switch to the latest stable `Channel stable, 3.16.0`
and try running one of these [examples](https://dart.dev/guides/libraries/c-interop#examples) 
imho if runs [sql_lite](https://github.com/dart-lang/sdk/tree/main/samples/ffi/sqlite) is most likely the package causing the issue

**Comment by zyrouge** [comment]
> I think nobody should receive an answer like [this](https://github.com/media-kit/media-kit/issues/595#issuecomment-1812062453)!
> 
> I recommend to switch to the latest stable `Channel stable, 3.16.0` and try running one of these [examples](https://dart.dev/guides/libraries/c-interop#examples) imho if runs [sql_lite](https://github.com/dart-lang/sdk/tree/main/samples/ffi/sqlite) is most likely the package causing the issue

I did it with stable channel, would try building `sql_lite`.

**Comment by huycozy** [comment]
Hi @zyrouge 
I haven't experienced this package, could you be more specific on `steps to reproduce`? Also, per discussion at https://github.com/media-kit/media-kit/issues/595, is this issue an OS and Clang version specific issue (only occurs with Fedora 39 has Clang 17)?

**Comment by zyrouge** [comment]
> Hi @zyrouge I haven't experienced this package, could you be more specific on `steps to reproduce`? Also, per discussion at [media-kit/media-kit#595](https://github.com/media-kit/media-kit/issues/595), is this issue an OS and Clang version specific issue (only occurs with Fedora 39 has Clang 17)?

Just adding `media_kit` as a dependency and trying to build will make the build fail. I cannot be sure if it Fedora 39 or Clang 17 issue since both changed simultaneously (Fedora 39 comes with Clang 17). I am saying this might be Clang 17 issue since it did build successfully on Fedora 38 (Clang 16) and Ubuntu 22.04 (Clang 16). As far as I know, no Ubuntu releases have Clang 17 yet.

**Comment by huycozy** [comment]
I'm on `Ubuntu 22.04.3 LTS` with `clang version 14.0.0-1ubuntu1.1` but it builds well without issue. Labeling the issue for further information from others.

**Comment by gspencergoog** [comment]
I'm not sure what we can do to help here at this point, without more specific information. We explicitly support Debian and Ubuntu, but we don't really have the resources to debug things on Fedora (and we don't have machines with that installed).

So, unfortunately, we're going to have to close this issue.  If you have a specific PR or solution to contribute, we would gladly review that.
(Desktop Triage)

**Comment by femalemonkeyman** [comment]
Solved
