### ISSUE TITLE
[two_dimensional_scrollables] - Add `BorderRadiusGeometry` to `TableSpanDecoration`

### ISSUE THREAD

**Issue by LathDevers** [flutter/flutter#138605]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

```dart
TableSpan(
  backgroundDecoration = MyTableSpanDecoration(
    color: index.isEven
        ? MacosTheme.brightnessOf(context).resolve(
            const Color(0xfff4f5f5),
            const Color(0xff393939),
          )
        : Colors.transparent,
    borderRadius: BorderRadius.circular(5),
  ),
  extent = FractionalTableSpanExtent(index == 0 ? .028 : .02),
);
```

### Proposal

@Piinks Please add `borderRadius` to paint `TableSpanDecoration` background `Rect` decoration.

For now, I've written a class that extends `TableSpanDecoration` and have overridden the `paint` method. See the code below.

Override function:

```dart
void paint(TableSpanDecorationPaintDetails details) {
  if (color != null) {
    details.canvas.drawRRect(
      borderRadius.resolve(TextDirection.ltr).toRRect(details.rect),
      Paint()
        ..color = color!
        ..isAntiAlias = false,
    );
  }
  if (border != null) {
    border!.paint(details);
  }
}
```

Original code:

```dart
void paint(TableSpanDecorationPaintDetails details) {
  if (color != null) {
    details.canvas.drawRect(
      details.rect,
      Paint()
        ..color = color!
        ..isAntiAlias = false,
    );
  }
  if (border != null) {
    border!.paint(details);
  }
}
```

**Comment by dam-ease** [comment]
Thanks for proposing this @LathDevers.
I see this was implemented per https://github.com/flutter/packages/pull/5184.
Can you check this out to confirm it is similar to your proposal?

**Comment by LathDevers** [comment]
Yes, it is. Thanks.
