### ISSUE TITLE
'cloud-firestore' plugin misses transactions implementation

### ISSUE THREAD

**Issue by docet85** [flutter/flutter#13869]
I took my time to explore the source code of cloud-firestore, but it seems there's no transactions support at the moment. Am I wrong? Even if it is possible to listen to a document changes as well as to 'update' it, it would be cumbersome to implement transactions just with those.

Firestore provides documents transactions natively for both iOS and Android, so I guess it would be nice to have them also in the Flutter plugin.

**Comment by alibitek** [comment]
As an inspiration one can probably use the transaction support implemented for Firebase Realtime Database in PR https://github.com/flutter/plugins/pull/199/files

**Comment by docet85** [comment]
Not sure it is what @alibitek refers to - but for sake of simplicity and parallelism it would be good to have the same structure and usage that the cloud-firestore libraries for iOS and Android have. In my opinion it's win-win (as they did for Firebase Realtime DB): it should be easier to wrap and the cloud-firestore documentation is still valid when developers look for information and examples (as the original ones for Android and iOS have the same pattern).

**Comment by Hixie** [comment]
cc @collinjackson

**Comment by ened** [comment]
@docet85 could you please confirm if current transaction support in `cloud_firestore` is what you were referring to?

**Comment by docet85** [comment]
Sorry I discontinued the project a year ago, I have no way to check this.

Best

**Comment by ened** [comment]
In that case we can close the issue for the moment, as transaction functionality has been added. @zoechi

**Comment by collinjackson** [comment]
Closing since transactions are now supported

**Comment by kroikie** [comment]
@docet85

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/921. Any further collaboration will be done there.
