### ISSUE TITLE
beta release candidate branch information is missing

### ISSUE THREAD

**Issue by XilaiZhang** [flutter/flutter#138738]
beta release branch info is absent after 3.17 release
https://github.com/flutter/flutter/blob/beta/bin/internal/release-candidate-branch.version
this causes flutter dashboard to fail to retrieve beta branch information

**Comment by Jasguerrero** [comment]
What would be the proper way to update the branch "beta"? It seems like https://github.com/flutter/flutter/pull/138646 can not be merged @XilaiZhang

**Comment by XilaiZhang** [comment]
> What would be the proper way to update the branch "beta"? It seems like #138646 can not be merged @XilaiZhang

I think the pushers-beta permission was removed from the release eng group. @CaseyHillers would definitely know if manually updating the https://github.com/flutter/flutter/blob/beta/bin/internal/release-candidate-branch.version file is the correct approach. If so, can we get temporary pushers beta permission?

**Comment by CaseyHillers** [comment]
It's WAI to not be able to submit to beta|stable directly. If PRs were merged there, it'll cause minor issues with the version calculating as the HEAD commit won't have a tag.

Instead, we want to push a new beta release based on the RC branch.

However, I recommend yak shaving and fixing the underlying issue in Cocoon. The channel values are a `String` when they should be a `String?`. So if the version file 404's, we can mark it as null.

**Comment by XilaiZhang** [comment]
> So if the version file 404's, we can mark it as null.
my understanding is that suppressing the error when file 404 wouldn't fix the missing branch information?

https://github.com/flutter/flutter/issues/138755 happens when users want to find out beta information.
And cocoon would still return nothing for beta branch.

Before the next beta is released, would it be possible to temporarily host this information somewhere else?
