### ISSUE TITLE
[Impeller] Poor performance with lots of emojis.

### ISSUE THREAD

**Issue by FizbyteSoftware** [flutter/flutter#138798]
### Steps to reproduce

see https://github.com/flutter/flutter/issues/134292
The only difference is that the emojis get displayed, which fixed that task, but they are super janky.
(check Video demonstration)
### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Performance profiling on master channel

- [X] The issue still persists on the master channel

### Timeline Traces

<details><summary>Timeline Traces JSON</summary>

```json
[Paste the Timeline Traces here]
```

</details>

### Video demonstration

<details>
<summary>Video demonstration</summary>

[Upload media here]

https://github.com/flutter/flutter/assets/137168283/f73eb572-033e-42c4-a3fe-d29613d88872

https://github.com/flutter/flutter/assets/137168283/a5e2bf53-fd76-4302-880d-77dacdf55b8c

[</details>

### What target platforms are you seeing this bug on?

iOS

### OS/Browser name and version | Device information

IOS 16.7.2, Iphone X

### Does the problem occur on emulator/simulator as well as on physical devices?

Yes

### Is the problem only reproducible with Impeller?

Yes

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by jonahwilliams** [comment]
Code sample is in https://github.com/flutter/flutter/issues/134292#issue-1887553525

**Comment by emesterhazy** [comment]
I recorded two videos, [one with Skia](https://drive.google.com/file/d/17GxxC1NZLFZ-2QkHgMa7hQ4PNXKIAhG-/view?usp=drive_link) and [one with Impeller](https://drive.google.com/file/d/13lAIxepRE-19I_RNX7okFK6gMFb5SXqd/view?usp=drive_link). I think the jank in the Impeller video is pretty noticeable in comparison. It might be easier to see the difference if you download the videos instead of viewing them in Google Drive's player.

**Comment by jonahwilliams** [comment]
@FizbyteSoftware your videos aren;t working and you don't have a timeline.

**Comment by FizbyteSoftware** [comment]
https://github.com/flutter/flutter/assets/137168283/6a47aed7-1895-4a6f-a4bf-afa29e418cdc

to me the videos are working fine

**Comment by borjandev** [comment]
This is causing severe performance issues and prevents us from using impeller 

More severe reproduction sample below:

```import 'package:flutter/material.dart';
import 'dart:math';

void main() {
  runApp(const MaterialApp(
    home: ImpellerSlowFrame(),
  ));
}

class ImpellerSlowFrame extends StatefulWidget {
  const ImpellerSlowFrame({super.key});

  @override
  ImpellerSlowFrameState createState() => ImpellerSlowFrameState();
}

class ImpellerSlowFrameState extends State<ImpellerSlowFrame> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView.builder(
          scrollDirection: Axis.horizontal,
          itemBuilder: (context, index) {
            return SizedBox(
              width: 25,
              child: ListView.builder(
                  scrollDirection: Axis.vertical,
                  itemBuilder: (context, index) {
                    return const RandomEmoji();
                  }),
            );
          }),
    );
  }
}

class RandomEmoji extends StatefulWidget {
  const RandomEmoji({super.key});

  @override
  RandomEmojiState createState() => RandomEmojiState();
}

class RandomEmojiState extends State<RandomEmoji> {
  late String _randomEmoji;

  @override
  void initState() {
    super.initState();
    _randomEmoji = getRandomEmoji();
  }

  String getRandomEmoji() {
    List<List<int>> emojiRanges = [
      [0x1F600, 0x1F64F],
      [0x1F300, 0x1F5FF],
      [0x1F680, 0x1F6FF],
      [0x1F700, 0x1F77F],
    ];

    Random random = Random();
    List<int> selectedRange = emojiRanges[random.nextInt(emojiRanges.length)];
    int emojiCode = random.nextInt(selectedRange[1] - selectedRange[0]) + selectedRange[0];
    return String.fromCharCode(emojiCode);
  }

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () {
        setState(() {
          _randomEmoji = getRandomEmoji();
        });
      },
      child: RichText(
        text: TextSpan(
          text: _randomEmoji,
          style: const TextStyle(fontSize: 25, color: Colors.black),
        ),
      ),
    );
  }
}
```


https://github.com/flutter/flutter/assets/64651636/8ae5b72d-aea3-4b92-bd18-4f66d40c61ee


https://github.com/flutter/flutter/assets/64651636/48ca92dd-1d93-469b-aeae-26203fc98d03


https://github.com/flutter/flutter/assets/64651636/946debfd-b120-44a3-b062-51dc862d460f


I wonder why the UI thread is getting hammered as well on the impeller run?

Any ideas @jonahwilliams ? or maybe if there is some way to be able to render the emojis the way that skia does while using impeller?

Reproducible on latest master 9f8fe3f04c468f7a503b58f29067f7392dc94b95 and latest stable [3.16.9](https://github.com/flutter/flutter/releases/tag/3.16.9)

iPhone 13 Pro Max on iOS 17.0 

Reproducible on MacOS Impeller as well as far as I can tell but maybe needs to be triaged

**Comment by jonahwilliams** [comment]
This just needs some work to fix in Impeller, there are no work arounds I am aware of.

**Comment by jonahwilliams** [comment]
Basic idea:

1. Update texture API to allow updating sub regions:  (https://github.com/flutter/engine/pull/50768)
2. Change incremental atlas update strategy to use this API instead of clearing the texture.
3. Update criteria for reseting atlas to erase unused entries first.

**Comment by Liloupar** [comment]
@jonahwilliams 
Does this also impact the rendering performance of CJK text? Since CJK has a vast array of unique character forms, as opposed to English, which only has 26 letters...
thanks

**Comment by jonahwilliams** [comment]
Have you observed poor performance with CJK text?

**Comment by jonahwilliams** [comment]
We've discussed this a bit in our last weekly: We're going to adjust the caching herustics to better handle overflows, by using the previous glyph atlas to seed the next growth (up to the memory limit). This requires a few changes and refactors:

1. We need to fix the thread safety of TextureMTL (https://github.com/flutter/flutter/issues/144498 ). I plan to do that by removing these APIs on TextureMTL and TextureVK and only using blit passes.
2. Add support to blit pass for updating a subregion of a texture  https://github.com/flutter/flutter/issues/144498
3. Update heurstics as discussed.

There may be more follow ups that will further improve performance:

**Comment by jonahwilliams** [comment]
Okay, current state of things. Not quite done yet but its looking much better:


https://github.com/flutter/flutter/assets/8975114/3cbc71c2-0214-4bc1-a587-629f14f2b7c2

**Comment by jonahwilliams** [comment]
Still jitters when we add lots of new emojis though.


https://github.com/flutter/flutter/assets/8975114/985710cc-3ff4-4190-a313-37408dba0d1f
