### ISSUE TITLE
IOS, simulator 'flutter run' get's stuck at "xcrun simctl spawn ..." 

### ISSUE THREAD

**Issue by Genhain** [flutter/flutter#138713]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

flutter run -v

### Actual results

It get's stuck at `xcrun simctl spawn`  everytime.

Runner.xcworkspace is fine.
 
 I can remedy it if i delete the project and clone the repo again, but not before long the same issue happens.

`flutter clean` does not help.

If i create a brand new flutter project it seems fine. although i will try again a few times and see if its an over time issue.

### Logs

<details>
<summary>Logs</summary>

[output.txt](https://github.com/flutter/flutter/files/13413112/output.txt)

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.16.0, on macOS 13.6.1 22G313 darwin-x64, locale en-GB)
    • Flutter version 3.16.0 on channel stable at /Users/benfowler/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (5 days ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/benfowler/Library/Android/sdk
    • Platform android-30, build-tools 34.0.0
    • ANDROID_HOME = /Users/benfowler/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (2 available)
    • iPhone 14 iOS 16 (mobile) • 195F92C7-40A7-45CE-AE06-D6F401CD9AC9 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • Chrome (web)              • chrome                               • web-javascript • Google Chrome 119.0.6045.159

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by huycozy** [comment]
Hi @Genhain 
I can't find the issue from your output log. I would suggest you keep an eye on it if you are able to replicate it consistently and see if it has any pattern then share more information here so that we can verify the issue better.

**Comment by Genhain** [comment]
@huycozy Thanks for the look. I have a suspicion that it is fine, until i run tests and thats when flutter run get's stuck. And then i have to do the whole dance of cloning the repo again

**Comment by Genhain** [comment]
It was not easy to reproduce, and i also switched from using the downloaded flutter to a managed version with brew and no longer encounter the issue.
