### ISSUE TITLE
Empty space in tab bar and scaffold within new flutter version.

### ISSUE THREAD

**Issue by mnts** [flutter/flutter#138706]
Hello, first in scaffold after flutter upgrade I started to get entire one lne spacing within scaffold, and setting default height, box constrains, safearea.. nothing helped, still empty line on top, so I made my own scaffold.
Now after update to flutter 3.16 also tab bar widget started to show empty space of one tile in front if I set to isScrollable: true, to remake tabBar seems like a lot of play.. is there are other ways to deal with these unknown extra spaces on widgets after flutter upgrades? I can see anyt i nfo any docs.. just upgraded flutter and new weird layout issues..

**Comment by TahaTesser** [comment]
duplicate of https://github.com/flutter/flutter/issues/138606

**Comment by gemunet** [comment]
For some reason the space on the sides of the "indicator" is because they changed a default property, now you must set it explicitly like this so that it looks like before

```
TabBar(
     indicatorSize: TabBarIndicatorSize.tab,
```

**Comment by gemunet** [comment]
For some reason the space on the sides of the "indicator" is because they changed a default property, now you must set it explicitly like this so that it looks like before

```
TabBar(
     indicatorSize: TabBarIndicatorSize.tab,
```
