### ISSUE TITLE
Not able to play presigned video Url using video player in flutter web.

### ISSUE THREAD

**Issue by sanalkv** [flutter/flutter#138716]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Try to load a presigned video url from s3 bucket in video_player package. The issue is happening only in flutter web. Works fine in macos.

### Expected results

Should play video normally without any error. 

### Actual results

The video_player shows error in flutter web. In macos, it works fine.

### Code sample

<details><summary>Code sample</summary>

```dart
try {
      videoPlayerController = VideoPlayerController.networkUrl(
        Uri.parse(viewModel.lastScanVideo!),
      );
      await videoPlayerController?.initialize();
      chewieController = ChewieController(
          videoPlayerController: videoPlayerController!,
          autoInitialize: true,
          allowMuting: false,
          hideControlsTimer: const Duration(milliseconds: 500),
          progressIndicatorDelay: const Duration(milliseconds: 100),
          deviceOrientationsOnEnterFullScreen: DeviceOrientation.values,
          autoPlay: false,
          customControls: const CupertinoControls(
            backgroundColor: appColor23272B,
            iconColor: Colors.white70,
          ),
          routePageBuilder: (_, anim1, anim2, widget) {
            return FadeTransition(
              opacity: anim1,
              child: Material(
                color: Theme.of(context).scaffoldBackgroundColor,
                child: widget,
              ),
            );
          });
      if (mounted) {
        setState(() {});
      }
    } catch (e) {
    print(e);
    }
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

<img width="1006" alt="Screenshot 2023-11-20 at 7 00 29 PM" src="https://github.com/flutter/flutter/assets/30585556/444e3d59-1225-4a4c-b349-6b7b0d79f4f1">

PlatformException (MEDIA_ERR_SRC_NOT_SUPPORTED, No further diagnostic information can be determined or provided., The video has been found to be unsuitable (missing or in a format not supported by your browser)., null)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.8, on macOS 14.0 23A344 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.84.0)
[✓] Connected device (3 available)
    ! Error: Browsing on the local area network for Qa iPhone 11 Pro Max. Ensure the device is unlocked and attached with a cable or associated with
      the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!
```

</details>

**Comment by reeteshranjan** [comment]
```dart
import "package:flutter/cupertino.dart";
import "package:flutter/material.dart";
import "package:video_player/video_player.dart";

class NetworkVideoPlayerView extends StatefulWidget {
  const NetworkVideoPlayerView({required this.url, super.key});

  final String url;

  @override
  NetworkVideoPlayerViewState createState() => NetworkVideoPlayerViewState();
}

class NetworkVideoPlayerViewState extends State<NetworkVideoPlayerView> {
  late VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.networkUrl(Uri.parse(widget.url))
      ..initialize().then(
        (final _) => Future.delayed(
          Duration.zero,
          () => setState(() {}),
        ),
      );
  }

  @override
  Widget build(final BuildContext context) {
    return Center(
          child: _controller.value.isInitialized
              ? AspectRatio(
                  aspectRatio: _controller.value.aspectRatio,
                  child: VideoPlayer(_controller),
                )
              : Container(),
        ),
      ),
    );
  }
}
```

I use this simple code to play a presigned S3 video URL and as per the network logs in inspector, a 206 is returned. However; the video player view is stuck on the 1st frame itself and won't play anything post that.

**Comment by sanalkv** [comment]
> Hi @sanalkv In order to address the issue properly, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so that we may verify this. Thanks!

@huycozy thanks for the reply. Looks like the issue was with the video codec. it wasn't supporting the chrome browser.

**Comment by reeteshranjan** [comment]
> ```dart
> import "package:flutter/cupertino.dart";
> import "package:flutter/material.dart";
> import "package:video_player/video_player.dart";
> 
> class NetworkVideoPlayerView extends StatefulWidget {
>   const NetworkVideoPlayerView({required this.url, super.key});
> 
>   final String url;
> 
>   @override
>   NetworkVideoPlayerViewState createState() => NetworkVideoPlayerViewState();
> }
> 
> class NetworkVideoPlayerViewState extends State<NetworkVideoPlayerView> {
>   late VideoPlayerController _controller;
> 
>   @override
>   void initState() {
>     super.initState();
>     _controller = VideoPlayerController.networkUrl(Uri.parse(widget.url))
>       ..initialize().then(
>         (final _) => Future.delayed(
>           Duration.zero,
>           () => setState(() {}),
>         ),
>       );
>   }
> 
>   @override
>   Widget build(final BuildContext context) {
>     return Center(
>           child: _controller.value.isInitialized
>               ? AspectRatio(
>                   aspectRatio: _controller.value.aspectRatio,
>                   child: VideoPlayer(_controller),
>                 )
>               : Container(),
>         ),
>       ),
>     );
>   }
> }
> ```
> 
> I use this simple code to play a presigned S3 video URL and as per the network logs in inspector, a 206 is returned. However; the video player view is stuck on the 1st frame itself and won't play anything post that.
> 
> <img alt="Screenshot 2023-11-22 at 3 34 00 PM" width="1328" src="https://user-images.githubusercontent.com/5516599/284865545-08aa5402-89f2-4112-a774-f0967020d400.png">
> I debug Flutter web using Chrome and in the same browser window if I paste the presigned S3 URL in a new tab, the video plays. But it won't play with the code as given above. In case of using this new tab to just play video, I see different network logs. There is a request with 200 response before a request with 206 response, while in case of using the VideoPlayer package, there is only a request with 206 response.
> 
> <img alt="Screenshot 2023-11-22 at 3 42 42 PM" width="1326" src="https://user-images.githubusercontent.com/5516599/284868006-7a967b5f-31d1-4d95-b470-b5441c7d6c22.png">

Please ignore this comment. Rookie mistake of not following the example properly. Missed on initiating 'play' as in the short/detailed examples.

**Comment by huycozy** [comment]
I guess you are hitting the same issue at https://github.com/flutter/flutter/issues/115860 which indicates that HLS is not supported currently on Chrome but on Safari (see https://github.com/flutter/flutter/issues/46778#issuecomment-567738693 for more information). 

And there is a feature request for it here: https://github.com/flutter/flutter/issues/53011. Please take a look and confirm this.

**Comment by sanalkv** [comment]
It's not related to HLS. It's with the m4v codec of the .mp4 video file. Chrome doesn't support the m4v codec. I'm not sure if video_player plugin can do something to make it support these codec. 

It's mentioned that chrome doesn't support this directly but can make it work through an external plugin.

Also the video_player doesn't have the option to mention the content type for web, something like 'type="video/mp4"' which i think is an important factor as well. I have seen this possible while we load a video link in HTML5.

**Comment by huycozy** [comment]
I see `m4v` file is not playing on Chrome and Safari as well. I think this can be a proposal as https://github.com/flutter/flutter/issues/53011 requested. Please help to file a new issue (feature request) for this so everyone can grasp the issue right from the begin. Closing this issue from here. Thank you!
