### ISSUE TITLE
Deeplinking not working on Android 33 Devices

### ISSUE THREAD

**Issue by chrisDK1977** [flutter/flutter#138789]
I have implemented deeplinking for android as in the flutter docs (https://docs.flutter.dev/cookbook/navigation/set-up-app-links)

with

        <meta-data android:name="flutter_deeplinking_enabled" android:value="true" />
        <intent-filter android:autoVerify="true">
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="https" android:host="myApp.my-server.de"/>
        </intent-filter>

in the android manifest. (myApp.my-server.de is a placeholder and not the real server name in my code)

Calling .\adb shell 'am start -a android.intent.action.VIEW -c android.intent.category.BROWSABLE -d "https://myApp.my-server.de/my-deeplink/1"' on an virtual device with sdk 30 opens the choice to open the app or the website on the virtual device and everything is working. But with an device and sdk 33 it just opens the browser.

What could be the problem? The play store tells me the deeplink-url is valid (GooglePlayConsole > Deeplinks > "All links work. Users go directly to your app" [translated from de]).

Also see https://github.com/flutter/flutter/issues/129260#issuecomment-1645104531_

**Comment by danagbemava-nc** [comment]
Hi @chrisDK1977, android 12 changed the way deep-links are handled on android. Can you check https://developer.android.com/training/app-links#web-links to see if helps.
