### ISSUE TITLE
[cocoon] get-release-branches returning error 500

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#138747]
### Is there an existing issue for this?

- [X] I have searched the [existing infra issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-infra)

### Type of Request

bug

### Infrastructure Environment

Cocoon

### What is happening?

After signing-in into Cocoon, when looking at a build dashboard, I get an error toast at the bottom of the page that says:

> ❗️ An error occurred fetching branches from flutter/flutter on Cocoon.: /api/public/get-release-branches returned 500

<img width="857" alt="Screenshot 2023-11-20 at 11 23 21 AM" src="https://github.com/flutter/flutter/assets/1255594/48af9433-c4b0-4ae7-925f-e7b97a99b515">

The error seems to come from this method (well, the [`fetchFlutterBranches` method](https://github.com/flutter/cocoon/blob/65bba1500e1fee92e50f352ad89a0ec831895fac/dashboard/lib/service/appengine_cocoon.dart#L118) from the cocoon service.):

https://github.com/flutter/cocoon/blob/65bba1500e1fee92e50f352ad89a0ec831895fac/dashboard/lib/state/build.dart#L141-L151

### Steps to reproduce

1. Sign-in into the build dashboard
2. Wait a few seconds
3. The error pop-up shows up with any other interaction

### Expected results

I don't expect to see the error, and maybe the list of branches in the dashboard to be populated.

**Comment by ditman** [comment]
Related? https://github.com/flutter/flutter/issues/129028

**Comment by Jasguerrero** [comment]
There was a b/ but we still needed a github issue. Last I know @XilaiZhang was opening one but idk if he got around to it, defer to him to either close this one or keep it

**Comment by Jasguerrero** [comment]
Found the issue https://github.com/flutter/flutter/issues/138738

**Comment by XilaiZhang** [comment]
I posted in chat last Friday but my understanding is that this should be fixed as long as the https://github.com/flutter/flutter/blob/beta/bin/internal/release-candidate-branch.version file is restored

**Comment by CaseyHillers** [comment]
Can we fix the issue in Cocoon to prevent future breakages? We should demote the branches from `String` to `String?`

**Comment by XilaiZhang** [comment]
umm good point I guess we can add a try catch block around fetch file content, and if file doesn't exist, return empty.

But my understanding is that this doesn't fix cocoon dashboard? i think its more like (not returning anything and DONT't throw an error) versus (not returning anything and throw an error)?

**Comment by Jasguerrero** [comment]
> But my understanding is that this doesn't fix cocoon dashboard?
Right but this will be the first step towards a solution, the second is to force push the next beta

**Comment by XilaiZhang** [comment]
> > But my understanding is that this doesn't fix cocoon dashboard?
> 
> Right but this will be the first step towards a solution, the second is to force push the next beta

umm if I am understanding correctly, the effect of this is suppressing the error and return nothing. 
I think returning nothing and throwing an error to report it(the current state), would be better than returning nothing(the proposed solution)?

**Comment by XilaiZhang** [comment]
> > But my understanding is that this doesn't fix cocoon dashboard?
> 
> Right but this will be the first step towards a solution, the second is to force push the next beta

If I am understanding correctly, i think the next time a new beta is shipped might be months later?

**Comment by Jasguerrero** [comment]
> If I am understanding correctly, i think the next time a new beta is shipped might be months later?

I mean the next beta hotfix

**Comment by XilaiZhang** [comment]
umm personally i think snackbar error(UI) is better than logs since its transient (only there for a few seconds), not blocking existing functions and help us to find things faster (it was so long ago since I last logged onto appengine to scrape through logs).

I feel like the most crucial thing at the moment is how to unblock users encountering https://github.com/flutter/flutter/issues/138755.

**Comment by ditman** [comment]
(I think the snackbar error is all right, otherwise I would haven't noticed the problem probably)
