### ISSUE TITLE
No beta branch version for cherry pick process

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#138755]
When you click the "beta" link in https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process, it directs to https://github.com/flutter/flutter/blob/beta/bin/internal/release-candidate-branch.version, which results in a 404.

**Comment by godofredoc** [comment]
@XilaiZhang FYI this is related to the other bug for release candidate branches that you are working on.

**Comment by XilaiZhang** [comment]
Right for some reasons the beta [release-candidate-branch.version](https://github.com/flutter/flutter/blob/beta/bin/internal/release-candidate-branch.version) file was removed when the new 3.17 beta shipped. cocoon dashboard was also impacted.

brief summary of https://github.com/flutter/flutter/issues/138738 and chat threads last week: The solution proposed by Casey is to force push the next beta release to fix this file. 

Before the next beta come out and the file is restored, users might need another way to get beta branch information

**Comment by XilaiZhang** [comment]
temporarily hard coded the beta release candidate branch name (3.17.0) in https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process for now to unblock contributors @vashworth 

Will restore the file when the next beta is pushed.

**Comment by CaseyHillers** [comment]
Fixed in 3.17.0-0.1.pre and I cleaned up the CP docs.
