### ISSUE TITLE
Error: A value of type 'RenderObject?' can't be assigned to a variable of type 'AbstractNode?'

### ISSUE THREAD

**Issue by dishankjindal1** [flutter/flutter#138878]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I have a existing project running and i upgraded from 3.13.9 stable to 3.16.0

### Expected results

should be able to build

### Actual results

not be able to build

### Code sample

<details><summary>I upgraded to Flutter 3.16.0 from 3.13.9 and this error started poping</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.0, on macOS 14.1.1 23B81 darwin-arm64,
    locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version
    34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.81.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
: Error: A value of type 'RenderObject?' can't be assigned to a variable of type 'AbstractNode?'.
- 'RenderObject' is from 'package:flutter/src/rendering/object.dart' ('../../../flutter/packages/flutter/lib/src/rendering/object.dart').
- 'AbstractNode' is from 'package:flutter/src/foundation/node.dart' ('../../../flutter/packages/flutter/lib/src/foundation/node.dart').
      final AbstractNode? targetParent = renderObject.parent;
                                                      ^
: Error: A value of type 'RenderObject?' can't be assigned to a variable of type 'AbstractNode?'.
- 'RenderObject' is from 'package:flutter/src/rendering/object.dart' ('../../../flutter/packages/flutter/lib/src/rendering/object.dart').
- 'AbstractNode' is from 'package:flutter/src/foundation/node.dart' ('../../../flutter/packages/flutter/lib/src/foundation/node.dart').
      final AbstractNode? targetParent = renderObject.parent;
                                                      ^

: Error: Member not found: 'fadeDuration'.
        duration: TextSelectionOverlay.fadeDuration, vsync: this);
                                       ^^^^^^^^^^^^
: Error: The argument type 'void Function(TapDownDetails)' can't be assigned to the parameter type 'void Function(TapDragDownDetails)?'.
- 'TapDownDetails' is from 'package:flutter/src/gestures/tap.dart' ('../../../flutter/packages/flutter/lib/src/gestures/tap.dart').
- 'TapDragDownDetails' is from 'package:flutter/src/gestures/tap_and_drag.dart' ('../../../flutter/packages/flutter/lib/src/gestures/tap_and_drag.dart').
        onTapDown: onTapDown,
                   ^
: Error: The argument type 'void Function(TapUpDetails)' can't be assigned to the parameter type 'void Function(TapDragUpDetails)?'.
- 'TapUpDetails' is from 'package:flutter/src/gestures/tap.dart' ('../../../flutter/packages/flutter/lib/src/gestures/tap.dart').
- 'TapDragUpDetails' is from 'package:flutter/src/gestures/tap_and_drag.dart' ('../../../flutter/packages/flutter/lib/src/gestures/tap_and_drag.dart').
        onSingleTapUp: onSingleTapUp,
                       ^
: Error: The argument type 'void Function(TapDownDetails)' can't be assigned to the parameter type 'void Function(TapDragDownDetails)?'.
- 'TapDownDetails' is from 'package:flutter/src/gestures/tap.dart' ('../../../flutter/packages/flutter/lib/src/gestures/tap.dart').
- 'TapDragDownDetails' is from 'package:flutter/src/gestures/tap_and_drag.dart' ('../../../flutter/packages/flutter/lib/src/gestures/tap_and_drag.dart').

        onDoubleTapDown: onDoubleTapDown,
                         ^
: Error: The argument type 'void Function(DragStartDetails)' can't be assigned to the parameter type 'void Function(TapDragStartDetails)?'.
- 'DragStartDetails' is from 'package:flutter/src/gestures/drag_details.dart' ('../../../flutter/packages/flutter/lib/src/gestures/drag_details.dart').
- 'TapDragStartDetails' is from 'package:flutter/src/gestures/tap_and_drag.dart' ('../../../flutter/packages/flutter/lib/src/gestures/tap_and_drag.dart').
        onDragSelectionStart: onDragSelectionStart,
                              ^
: Error: The argument type 'void Function(DragStartDetails, DragUpdateDetails)' can't be assigned to the parameter type 'void Function(TapDragUpdateDetails)?'.
- 'DragStartDetails' is from 'package:flutter/src/gestures/drag_details.dart' ('../../../flutter/packages/flutter/lib/src/gestures/drag_details.dart').
- 'DragUpdateDetails' is from 'package:flutter/src/gestures/drag_details.dart' ('../../../flutter/packages/flutter/lib/src/gestures/drag_details.dart').
- 'TapDragUpdateDetails' is from 'package:flutter/src/gestures/tap_and_drag.dart' ('../../../flutter/packages/flutter/lib/src/gestures/tap_and_drag.dart').
        onDragSelectionUpdate: onDragSelectionUpdate,
                               ^
: Error: The argument type 'void Function(DragEndDetails)' can't be assigned to the parameter type 'void Function(TapDragEndDetails)?'.
- 'DragEndDetails' is from 'package:flutter/src/gestures/drag_details.dart' ('../../../flutter/packages/flutter/lib/src/gestures/drag_details.dart').
- 'TapDragEndDetails' is from 'package:flutter/src/gestures/tap_and_drag.dart' ('../../../flutter/packages/flutter/lib/src/gestures/tap_and_drag.dart').
        onDragSelectionEnd: onDragSelectionEnd,
                            ^

Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* Where:
Script '/Users/dishankjindal/flutter/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy' line: 1350

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/dishankjindal/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (1)

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.0, on macOS 14.1.1 23B81 darwin-arm64,
    locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version
    34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.81.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by dam-ease** [comment]
Thanks for filing this.

> I have a existing project running and i upgraded from 3.13.9 stable to 3.16.0

Can you try with a new project to see if this error persists?
Also, from issues related to this, I see this was caused in an issue by an outdated version of the `sliver_tools ` package,
Are you making use of this in your existing project?
Also, can you upgrade your packages to the latest versions?

**Comment by dishankjindal1** [comment]
Launching lib/main.dart on LE2101 in release mode...
: Error: A value of type 'RenderObject?' can't be assigned to a variable of type 'AbstractNode?'.
- 'RenderObject' is from 'package:flutter/src/rendering/object.dart' ('../../../flutter/packages/flutter/lib/src/rendering/object.dart').
- 'AbstractNode' is from 'package:flutter/src/foundation/node.dart' ('../../../flutter/packages/flutter/lib/src/foundation/node.dart').
      final AbstractNode? targetParent = renderObject.parent;
                                                      ^
: Error: A value of type 'RenderObject?' can't be assigned to a variable of type 'AbstractNode?'.
- 'RenderObject' is from 'package:flutter/src/rendering/object.dart' ('../../../flutter/packages/flutter/lib/src/rendering/object.dart').
- 'AbstractNode' is from 'package:flutter/src/foundation/node.dart' ('../../../flutter/packages/flutter/lib/src/foundation/node.dart').
      final AbstractNode? targetParent = renderObject.parent;
                                                      ^

: Error: The argument type 'void Function(TapDownDetails)' can't be assigned to the parameter type 'void Function(TapDragDownDetails)?'.
- 'TapDownDetails' is from 'package:flutter/src/gestures/tap.dart' ('../../../flutter/packages/flutter/lib/src/gestures/tap.dart').
- 'TapDragDownDetails' is from 'package:flutter/src/gestures/tap_and_drag.dart' ('../../../flutter/packages/flutter/lib/src/gestures/tap_and_drag.dart').
        onTapDown: onTapDown,
                   ^
: Error: The argument type 'void Function(TapUpDetails)' can't be assigned to the parameter type 'void Function(TapDragUpDetails)?'.
- 'TapUpDetails' is from 'package:flutter/src/gestures/tap.dart' ('../../../flutter/packages/flutter/lib/src/gestures/tap.dart').

- 'TapDragUpDetails' is from 'package:flutter/src/gestures/tap_and_drag.dart' ('../../../flutter/packages/flutter/lib/src/gestures/tap_and_drag.dart').
        onSingleTapUp: onSingleTapUp,
                       ^
: Error: The argument type 'void Function(TapDownDetails)' can't be assigned to the parameter type 'void Function(TapDragDownDetails)?'.
- 'TapDownDetails' is from 'package:flutter/src/gestures/tap.dart' ('../../../flutter/packages/flutter/lib/src/gestures/tap.dart').
- 'TapDragDownDetails' is from 'package:flutter/src/gestures/tap_and_drag.dart' ('../../../flutter/packages/flutter/lib/src/gestures/tap_and_drag.dart').
        onDoubleTapDown: onDoubleTapDown,
                         ^
: Error: The argument type 'void Function(DragStartDetails)' can't be assigned to the parameter type 'void Function(TapDragStartDetails)?'.
- 'DragStartDetails' is from 'package:flutter/src/gestures/drag_details.dart' ('../../../flutter/packages/flutter/lib/src/gestures/drag_details.dart').

- 'TapDragStartDetails' is from 'package:flutter/src/gestures/tap_and_drag.dart' ('../../../flutter/packages/flutter/lib/src/gestures/tap_and_drag.dart').
        onDragSelectionStart: onDragSelectionStart,
                              ^

: Error: The argument type 'void Function(DragStartDetails, DragUpdateDetails)' can't be assigned to the parameter type 'void Function(TapDragUpdateDetails)?'.
- 'DragStartDetails' is from 'package:flutter/src/gestures/drag_details.dart' ('../../../flutter/packages/flutter/lib/src/gestures/drag_details.dart').
- 'DragUpdateDetails' is from 'package:flutter/src/gestures/drag_details.dart' ('../../../flutter/packages/flutter/lib/src/gestures/drag_details.dart').
- 'TapDragUpdateDetails' is from 'package:flutter/src/gestures/tap_and_drag.dart' ('../../../flutter/packages/flutter/lib/src/gestures/tap_and_drag.dart').
        onDragSelectionUpdate: onDragSelectionUpdate,
                               ^
: Error: The argument type 'void Function(DragEndDetails)' can't be assigned to the parameter type 'void Function(TapDragEndDetails)?'.
- 'DragEndDetails' is from 'package:flutter/src/gestures/drag_details.dart' ('../../../flutter/packages/flutter/lib/src/gestures/drag_details.dart').

- 'TapDragEndDetails' is from 'package:flutter/src/gestures/tap_and_drag.dart' ('../../../flutter/packages/flutter/lib/src/gestures/tap_and_drag.dart').
        onDragSelectionEnd: onDragSelectionEnd,
                            ^

: Error: Member not found: 'fadeDuration'.
        duration: TextSelectionOverlay.fadeDuration, vsync: this);
                                       ^^^^^^^^^^^^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* Where:
Script '/Users/dishankjindal/flutter/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy' line: 1350
* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command '/Users/dishankjindal/flutter/bin/flutter'' finished with non-zero exit value 1
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
Exception: Gradle task assembleRelease failed with exit code 1
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:491:9)
<asynchronous suspension>
#2      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:220:5)
<asynchronous suspension>
#3      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:578:7)
<asynchronous suspension>
#4      FlutterDevice.runCold (package:flutter_tools/src/resident_runner.dart:533:33)
<asynchronous suspension>
#5      ColdRunner.run (package:flutter_tools/src/run_cold.dart:57:28)
<asynchronous suspension>
#6      AppDomain.launch.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:655:9)
<asynchronous suspension>
#7      AppDomain.launch (package:flutter_tools/src/commands/daemon.dart:653:5)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:646:15)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1350:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>

Exited (1)

**Comment by huycozy** [comment]
>Also, from issues related to this, I see this was caused in an issue by an outdated version of the sliver_tools  package,
Are you making use of this in your existing project?

@dishankjindal1 Please confirm what @dam-ease mentioned above (maybe similar to https://github.com/flutter/flutter/issues/133037)

**Comment by dishankjindal1** [comment]
> Also, from issues related to this, I see this was caused in an issue by an outdated version of the `sliver_tools ` package,
> Are you making use of this in your existing project?
I am not using sliver_tools, i checked my pubspec.lock file

> Also, can you upgrade your packages to the latest versions?
I upgraded to latest stable version 3.16.2 i am seeing the same error.

**Comment by huycozy** [comment]
It could come from other packages and it's not compatible with new Flutter SDK. I would suggest you check all packages in use, go through the changelog, and corresponding issue reports in its repository to see if there are any updates or fixes available. This will help you to identify and resolve any compatibility issues and ensure that all the packages are compatible with the new Flutter SDK.

**Comment by huycozy** [comment]
Did you use [flutter_math_fork](https://pub.dev/packages/flutter_math_fork) package? (looks similar to https://github.com/flutter/flutter/issues/100343). If it is, the fetched package may be still on `pub-cache`, that's reason why you still see the issue even after removing all dependencies in `pubspec.yaml` file.

**Comment by dishankjindal1** [comment]
I found the issue, it was related to flutter_layout_grid. For some reason, this was using the older version and it is a direct dependency of flutter_html which I use. 

As i mentioned above, i am explicitly leaving "" as version in my pubspec.yaml for all dependencies so for some reasons flutter_layout_grid was resolving to an older version which is currently not supported and hence compile errors.

Note:- the same thing was working fine in the previous stable build. So something is definitely wrong which causes problems for dependencies resolver.

**Comment by huycozy** [comment]
Since it's an issue with a `flutter_layout_grid` version, I would suggest you file an issue to its developers if you think there should be an improvement/a fix. Closing this issue as it's not Flutter framework issue.
