### ISSUE TITLE
Ios Simulator Crashed On Startup After Imported The Google_Maps Package In Flutter 

### ISSUE THREAD

**Issue by PANGSHENGFENG69** [flutter/flutter#138862]
### Steps to reproduce

1.My iOS Simulator iPhone 12 with iOS 14.3 Version Just crashed on startup without any Exception.

2.I had imported the API Keys to AndroidManifest.xml and AppDelegate.swift

3.Flutter clean -> Flutter Pub get -> Flutter run(iOS Simulator), Still did not working

4.Tried Run with Xcode and Still Same.

5.I created a new stateful page without import the google_map package for testing, it is still same.

### Expected results

I Hope The Simulator is working fine.

### Actual results

I had tested with using Android Simulator and my own physical iPhone 11 , it is working fine.

### Screenshots or Video
<details><summary>Logs</summary>
1.https://github.com/flutter/flutter/assets/80751783/435174da-ffc9-4ce9-9380-c3200350bcb1
(This is the Scenario,i recorded it up)
</details>

### Logs

<details><summary>Logs</summary>

1.https://github.com/flutter/flutter/assets/80751783/ec3e8192-374a-4e18-90c7-0c3adf7f66d0
(This is the Log, it loads forever)

</details>

### Flutter Doctor output
<details><summary>Logs</summary>

```
[✓] Flutter (Channel stable, 3.13.6, on macOS 13.5 22G74 darwin-arm64, locale en-TW)
    • Flutter version 3.13.6 on channel stable at /Users/psf/Desktop/flutterSDK
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (8 weeks ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/psf/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.72.2)
    • VS Code at /Users/psf/Downloads/AllShit/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (4 available)
    • psf69 (mobile)     • 00008030-000239D43AC3402E            • ios            • iOS 16.6.1 20G81
    • iPhone 12 (mobile) • DAF1635B-62AB-49FE-B44B-93B9B63AA1EF • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 13.5 22G74 darwin-arm64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 119.0.6045.159

[✓] Network resources
    • All expected network resources are available.

• No issues found!
``` 

</details>

**Comment by dam-ease** [comment]
Thanks for filing this @PANGSHENGFENG69.
I can't seem to reproduce this testing with an iPhone 12 although with iOS 16.4 and iOS 17.0.
Is this specific to this version?
Are you able to test this on other iOS versions to see if this still reproduces on your end?
Also, it would be helpful if you could share the full output of your `flutter run -v`

**Comment by PANGSHENGFENG69** [comment]
> Thanks for filing this @PANGSHENGFENG69. I can't seem to reproduce this testing with an iPhone 12 although with iOS 16.4 and iOS 17.0. Is this specific to this version? Are you able to test this on other iOS versions to see if this still reproduces on your end?
> 
> Can you also upgrade to the latest version of Flutter and of the package while testing this again as well. Also, it would be helpful if you could share the full output of your `flutter run -v`


OMG!!! You saved me!!

Now i tried with running Iphone15 iOS 17.0 , its working fine

**Comment by dam-ease** [comment]
Thanks for your response.
Closing this per your last comment, if you disagree, please comment and I'll reopen this.
Thank you!
