### ISSUE TITLE
[Impeller] vulkan: recycle vkRenderPass and vkFramebuffer

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#138856]
https://github.com/flutter/engine/pull/44861 attempted this optimization but had difficulty getting completed.  In more simple usage of vulkan these are recycled, but it was difficult to implement with our abstractions.

**Comment by jonahwilliams** [comment]
If we want to recycle these objects, we actually have to recycle everything and not individual textures and things. That might work OK for the onscreen descriptor but not for offscreens.

**Comment by jonahwilliams** [comment]
Fixed via https://github.com/flutter/engine/pull/50142
