### ISSUE TITLE
[Proposal] Add renderViewCreator for creating a custom RenderView

### ISSUE THREAD

**Issue by sososdk** [flutter/flutter#138892]
### Is there an existing issue for this?

- [x] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I need to customize `RenderView` and handle some things in `compositeFrame` method:
```dart

class CustomRenderView extends RenderView {
  CustomRenderView({
    ...
    required super.view,
  }) : _view = view;

  final ui.FlutterView _view;

  @override
  void compositeFrame() {
    ...
    try {
      ...
      if (automaticSystemUiAdjustment) {
        _updateSystemChrome();
        _doSomething();
      }
      ...
    } finally {
     ...
    }
  }

  void _updateSystemChrome() {
    // ...
  }

  void _doSomething() {
    // ...
  }
}
```

#### Before `Flutter 3.16.0`

I use `CustomRenderView` like this:
```dart
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  WidgetsBinding.instance
    ..renderView = CustomRenderView(
      configuration: WidgetsBinding.instance.createViewConfiguration(),
      view: PlatformDispatcher.instance.implicitView!,
    )
    ..renderView.prepareInitialFrame();
  
  ...
}
```

#### In `Flutter 3.16.0`

I use `CustomRenderView` like this:
```dart
void main() {
  final binding = WidgetsFlutterBinding.ensureInitialized();
  final flutterView = binding.platformDispatcher.implicitView!;
  // ignore: deprecated_member_use
  final pipelineOwner = binding.pipelineOwner;
  final renderView = CustomRenderView(view: flutterView);
  final root = View(
    view: flutterView,
    // ignore: deprecated_member_use
    deprecatedDoNotUseWillBeRemovedWithoutNoticePipelineOwner: pipelineOwner,
    // ignore: deprecated_member_use
    deprecatedDoNotUseWillBeRemovedWithoutNoticeRenderView: renderView,
    child: const MyApp(),
  );
  Timer.run(() => binding.attachRootWidget(root));
  binding.scheduleWarmUpFrame();
  
  ...
}
```

The `PipelineOwner` and `RenderView` parameters of the `View` class have been deprecated. How should I use `CustomRenderView` in the future?

### Proposal

The `View` class add `renderViewCreator` for creating custom `RenderView`:

```dart
View({
  super.key,
  required this.view,
  RenderView Function()? renderViewCreator,
  required this.child,
})
```

**Comment by huycozy** [comment]
Related PR https://github.com/flutter/flutter/pull/125003 and design doc: [flutter.dev/go/multiple-views](https://flutter.dev/go/multiple-views).

**Comment by goderbauer** [comment]
If you want to use your own custom render object you'll also have to implement your own custom widget that manages that render object. Flutter doesn't support replacing RenderObjects of widgets and we don't plan to enable that. I am going to close this.

(In general, its better to open issues describing a problem, not a solution)
