### ISSUE TITLE
CompilerSkSL should be able to handle UBOs and push constants

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#138866]
SkSL does not support UBOs (possible in GL or Vulkan) or push constants (Vulkan only).

We could make impellerc generate compliant SkSL from GLSL that has UBOs or push constants either by using `emit_uniform_buffer_as_plain_uniforms` (I think) from SPIRV-Cross or just by manually manipulating the UBOs into flattened uniforms (should work for sure).

**Comment by chinmaygarde** [comment]
The update in the last Impeller Weekly was that we are not going to go out of our way to support additional features in fragment program shaders at this time. Closing this as wont-fix.
