### ISSUE TITLE
Provide ability to override `NavigationBar` indicator ink response overlay

### ISSUE THREAD

**Issue by TahaTesser** [flutter/flutter#138850]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Currently, there is no overlayColor property in the `NavigationBar` which should allow overriding ink response overlay. 
This is typically found in other material widgets

For cases when you want override ink focus, hover and highlight effects, a Material State overlay can be used.

Take this example where we can set indicator color to be transparent but cannot override ink response overlay.

### Code sample

<details>
<summary>expand to view the code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        bottomNavigationBar: NavigationBarExample(),
      ),
    );
  }
}

class NavigationBarExample extends StatefulWidget {
  const NavigationBarExample({super.key});

  @override
  State<NavigationBarExample> createState() => _NavigationBarExampleState();
}

class _NavigationBarExampleState extends State<NavigationBarExample> {
  int index = 0;

  @override
  Widget build(BuildContext context) {
    return NavigationBar(
      elevation: 0,
      indicatorColor: Colors.transparent,
      selectedIndex: index,
      onDestinationSelected: (int index) {
        setState(() {
          this.index = index;
        });
      },
      destinations: const <Widget>[
        NavigationDestination(
          selectedIcon: Icon(Icons.home_filled),
          icon: Icon(Icons.home_outlined), label: 'Home'),
        NavigationDestination(
          selectedIcon: Icon(Icons.favorite),
          icon: Icon(Icons.favorite_outline), label: 'Favorites'),
      ],
    );
  }
}

```

</details> 

https://github.com/flutter/flutter/assets/48603081/10333bbd-cd1a-4ff4-bee4-14a104172385

### Proposal

Provide an overlay color property for the indicator ink response

`overlayColor: MaterialStatePropertyAll(Colors.transparent),` should be able to override the default ink response overlay.

https://github.com/flutter/flutter/assets/48603081/98d5b962-f8dc-4758-94dc-f4859ba4703b

**Comment by TahaTesser** [comment]
cc: @leighajarett

**Comment by Piinks** [comment]
Awesome! I think this makes sense as a cherry pick as well.

**Comment by TahaTesser** [comment]
@leighajarett 
https://github.com/flutter/flutter/pull/138901 should allow to customize M3 style indicator overlay.
