### ISSUE TITLE
The SystemCursor for corner resizing (i.e. UpLeft, UpRight, DownLeft, DownRight)  are not shown on macOS

### ISSUE THREAD

**Issue by osaxma** [flutter/flutter#138887]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

> I believe this should be a feature request as I only realized that they are not implemented for macOS after creating the issue

### Steps to reproduce

Run the sample code given below and hover the mouse like in the given screen recording

### Expected results

I expect all the following to show the correct cursor on macOS:

```dart
SystemMouseCursors.resizeUpLeft
SystemMouseCursors.resizeUpRight
SystemMouseCursors.resizeDownLeft
SystemMouseCursors.resizeUpLeftDownRight
```

### Actual results

None of the above cursors show up when used in macOS:

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  Widget child(MouseCursor cursor, [Color color = Colors.blue]) => MouseRegion(
        cursor: cursor,
        child: Container(
          color: color,
          height: 100,
          width: 100,
          child: Center(
              child: Text(
            cursor.toString(),
            textAlign: TextAlign.center,
          )),
        ),
      );

  @override
  Widget build(BuildContext context) {
    final size = MediaQuery.of(context).size;
    return MaterialApp(
      title: 'system cursors not shown',
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Stack(
          children: [
            Positioned(
              top: 0,
              left: 0,
              child: child(SystemMouseCursors.resizeUpLeft, Colors.red),
            ),
            Positioned(
              top: 0,
              left: (size.width / 2) - 50,
              child: child(SystemMouseCursors.resizeUp, Colors.green),
            ),
            Positioned(
              top: 0,
              right: 0,
              child: child(SystemMouseCursors.resizeUpRight, Colors.red),
            ),
            Positioned(
              top: (size.height / 2) - 50,
              left: 0,
              child: child(SystemMouseCursors.resizeLeft, Colors.green),
            ),
            Positioned(
              top: (size.height / 2) - 50,
              right: 0,
              child: child(SystemMouseCursors.resizeRight, Colors.green),
            ),
            Positioned(
              bottom: 0,
              left: 0,
              child: child(SystemMouseCursors.resizeDownLeft, Colors.red),
            ),
            Positioned(
              bottom: 0,
              left: (size.width / 2) - 50,
              child: child(SystemMouseCursors.resizeDown, Colors.green),
            ),
            Positioned(
              bottom: 0,
              right: 0,
              child: child(SystemMouseCursors.resizeUpLeftDownRight, Colors.red),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/46427323/350a5f5d-48c4-4584-95ab-8519e3e32967

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.0, on macOS 12.7 21G816 darwin-x64, locale en)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.84.2)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by dam-ease** [comment]
Thanks for filing this.
I see this is similar to https://github.com/flutter/flutter/issues/92894 which is a known issue being tracked in https://github.com/flutter/flutter/issues/89351.
Kindly upvote, comment follow up on this issue for updates.
Closing this in favour of the already existing issue https://github.com/flutter/flutter/issues/89351, if you disagree, please comment and I'll reopen this.
Thank you!

**Comment by dkwingsmt** [comment]
The requested cursors, along with other cursors such as "help" "busy", are not available with `NSCursor` public APIs. Although they're available through private APIs (as I proposed and got rejected in https://github.com/flutter/engine/pull/48754), using these APIs might cause the app to be rejected by the App Store. Those who don't plan to publish their app on the store and wish to pursue these cursors can try to apply the said PR to a custom engine. I think a better way is to make it a plugin, but I'm not familiar with plugin API and I'm assuming we probably need some extra plugin APIs to allow the system cursor set to be extended. (If you're willing to contribute to this project, let me know I'm more than happy to help!)
