### ISSUE TITLE
[engine] unoptimized - non-platform thread error

### ISSUE THREAD

**Issue by jwinarske** [flutter/flutter#138859]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

* Build unoptimized engine for external embedder use
* Configure engine to use a custom platform task runner
* start flutter application

### Expected results

I don't expect to see errors

### Actual results

```
[ERROR:flutter/shell/common/shell.cc(1004)] The 'flutter/localization' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.

[ERROR:flutter/shell/common/shell.cc(1004)] The 'flutter/keyevent' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.
```
These are coming from engine source code.

With a complex app that uses async events (lots of platform I/O) no errors are generated.  Which indicates there is a discrepancy with what thread the engine is using for internal platform I/O.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
$ flutter doctor -v
[!] Flutter (Channel [user-branch], 3.13.9, on Fedora Linux 38 (Workstation
    Edition) 6.5.10-200.fc38.x86_64, locale en_US.UTF-8)
    ! Flutter version 3.13.9 on channel [user-branch] at
      /mnt/raid10/workspace-automation/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an
      official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions
      at https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss
      this error.
    • Framework revision d211f42860 (4 weeks ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 16.0.6 (Fedora 16.0.6-3.fc38)
    • cmake version 3.27.7
    • ninja version 1.11.1
    • pkg-config version 1.8.0

[✓] VS Code (version 1.84.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.76.0

[✓] Connected device (2 available)
    • Linux (desktop)            • linux              • linux-x64 • Fedora Linux
      38 (Workstation Edition) 6.5.10-200.fc38.x86_64
    • Toyota homescreen (mobile) • desktop-homescreen • linux-x64 • homescreen
      x86_64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by jonahwilliams** [comment]
Assigning @chinmaygarde to take a look at the embedder code to make sure its doing the right thing.

**Comment by jwinarske** [comment]
I resolved these.  It's not entirely clear what engine calls should only be called from the platform thread.

The other vague item is render runner.  What is the case that separating render vs platform addresses?

**Comment by chinmaygarde** [comment]
Platform channel calls should be received and their responses dispatched on the platform task runner (as mentioned in the linked document). This used to be a cause of engine instability when dealing with plugins (especially during shutdown). While this was documented (and an assert present in unopt modes), some plugins ignored this guidance and we couldn't make this a fatal error. So a log was added recently.

> What is the case that separating render vs platform addresses?

The render task runner is separate from the platform task runner for additional concurrency and this is how all embedders work by default. Though restrictions due to the presence of platform views forces a merged thread configuration.
