### ISSUE TITLE
Firebase testlab tests failing on beta release infra

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#138835]
https://logs.chromium.org/logs/dart-internal/buildbucket/cr-buildbucket/8765433514531005809/+/u/test:_test:_Android_Firebase_Test__2_/stdout

```
API [testing.googleapis.com] not enabled on project [1013304541057]. Would you
like to enable and retry (this will take a few minutes)? (y/N)?
```

**Comment by CaseyHillers** [comment]
The issue is this is the first time we're running firebase tests on release infra. This error is mentioning that dart-ci-internal does not have firebase testlabs configured.

**Comment by CaseyHillers** [comment]
@drewroengoogle sent a Google CL to enable firebase on the dart-internal project. This week's Thanksgiving in the US, so we're not expecting to make progress on the beta until next week.

**Comment by drewroengoogle** [comment]
The CL has landed, assuming it propagates smoothly in the next couple of minutes we should be able to retry these testlab tests.

**Comment by CaseyHillers** [comment]
\cc @Jasguerrero I'll spend some cycles on this to disable the tests on releases. I expect this should be done before we ship the next stable.

**Comment by drewroengoogle** [comment]
Additional context: enabling firebase testing on dart-internal would potentially block many builds as they may take a while to finish. Closing the internal CL in lieu of Casey disabling these tests on releases.

**Comment by CaseyHillers** [comment]
I drafted https://flutter-review.googlesource.com/c/recipes/+/52720 to add `test_if` to enable us to filter where tests run. If that's approved, I'll need to update the engine at HEAD, and then file CP requests for the CL and PR.

**Comment by CaseyHillers** [comment]
With the latest beta builds, I'm still seeing these tests run and fail:

https://ci.chromium.org/ui/p/dart-internal/builders/flutter/Linux%20engine_release_builder/774/overview

I wonder if the issue is with how branch detection is being done on the drones. The gitiles property appears correct, so I'm going to swap it over to read that.

**Comment by CaseyHillers** [comment]
I sent https://flutter-review.googlesource.com/c/recipes/+/53100 as a follow up to change from git to gitiles

**Comment by CaseyHillers** [comment]
Fixed. See https://ci.chromium.org/ui/p/dart-internal/builders/flutter/Linux%20engine_release_builder/777/overview as an example.
