### ISSUE TITLE
[go_router] Handling URL Paths While Using the push Method with goRouter.

### ISSUE THREAD

**Issue by ShubhamHande99** [flutter/flutter#138964]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

In Flutter Web:

1. Use `context.push('/listitem/id');`
2. Screen navigate to defined route
3. URL doesn't update in the browser as page navigates.

### Expected results

Using **context.push('/listitem/id')** does not display the path in the URL as **www.example.com/listitem/id**. 

Why is the **optionURLReflectsImperativeAPI** option false by default, as it is  said to be against using it? if it so what should be the proper way of handling the below use case?

Let's consider a route path like 'listItemDetails/id,' which shows the list detail screen and can be navigated from different screens. It's better to use 'push' instead of writing nested navigation routes. However, with 'push,' the URL in the web bar does not show up. This means that users cannot bookmark or open that screen directly, for example, www.example.com/listItemDetails/1.

What are the best practices for such cases? Should we use the 'push' method or not and only go with nested routes?

If we only use 'go,' then for complex navigation, the URL will get messed up with long route paths. For example, www.example.com/home/page1/page2/page3?data=1/listItemDetails/1. The URL bar can even get filled up, which does not look nice. So, what should be the proper way to handle this?"

### Actual results

URL doesn't update in the browser as page navigates.

I have read the existing issues with same use case.
 [#134318](https://github.com/flutter/flutter/issues/134318)
 [#115962](https://github.com/flutter/flutter/issues/115962)

### Code sample

`context.push('/listitem/1');`

### Screenshots or Video

No response

### Logs

No response

### Flutter Doctor output

No response

**Comment by sachin96Boy** [comment]
Hi @ShubhamHande99, when using Navigations with GoRouter, You could pass query parameters onto your route. Let's say you wanted to pass some ID value on to the new route, you could achieve this by,

 `GoRouter.of(context)
          .pushNamed('/newpath', queryParameters: {'id': 'yourid'});`. 

Here for queryParameters We can pass a key, and value pair map and We can obtain these values that we passed on the new route by  using, 

` final args =
        ModalRoute.of(context)?.settings.arguments as Map<String, dynamic>;`. 

hope this helps

**Comment by ShubhamHande99** [comment]
@sachin96Boy , The issue is not about the passing the data or navigation but rather in the URL path, which is not updating in the browser when using the push method as described above.

**Comment by ps60679666** [comment]
GoRouter.optionURLReflectsImperativeAPIs = true;

> @sachin96Boy 

GoRouter.optionURLReflectsImperativeAPIs = true;

in main function you can use this code. I'm not sure what does this code mean, but it solves the problem.

**Comment by ShubhamHande99** [comment]
@ps60679666 However, the documentation strongly emphasizes not to set this option to true.

**Comment by ps60679666** [comment]
> @ps60679666 However, the documentation strongly emphasizes not to set this option to true.

https://github.com/flutter/flutter/issues/132430
There is github issue for this.

**Comment by ps60679666** [comment]
if(kIsWeb) {
GoRouter.optionURLReflectsImperativeAPIs = true;
}

**Comment by ShubhamHande99** [comment]
@ps60679666 Setting **optionURLReflectsImperativeAPI=true** solves the problem. I just wanted to know if we should use imperative methods when using go_router?

**Comment by ps60679666** [comment]
> @ps60679666 Setting **optionURLReflectsImperativeAPI=true** solves the problem. I just wanted to know if we should use imperative methods when using go_router?

No Idea bro.

**Comment by ps60679666** [comment]
import 'package:flutter/material.dart';

class NoTransitionsBuilder extends PageTransitionsBuilder {
  const NoTransitionsBuilder();

  @override
  Widget buildTransitions<T>(
    PageRoute<T>? route,
    BuildContext? context,
    Animation<double> animation,
    Animation<double> secondaryAnimation,
    Widget? child,
  ) {
    return child!;
  }
}



In theme data 
pageTransitionsTheme: PageTransitionsTheme(
        builders: kIsWeb
            ? {
                for (final platform in TargetPlatform.values)
                  platform: const NoTransitionsBuilder(),
              }
            : const {},
      ),
      
  
  This makes page transition in web smoother.

**Comment by dam-ease** [comment]
Hi @ShubhamHande99.
I also see that setting `optionURLReflectsImperativeAPI=true` should solve this issue and suit your use case.
As regards what the documentation says about this, there is an open proposal addressing this https://github.com/flutter/flutter/issues/132430. 
Can you please upvote and comment on that issue? Also, follow up on that issue for updates.
Closing this in favour of the already open issue, if you disagree, please comment and I'll reopen this.
Thank you!
