### ISSUE TITLE
Add automated test to prevent package changes without version changes

### ISSUE THREAD

**Issue by xster** [flutter/flutter#13897]
It's currently possible to update behaviours in our first party published packages in https://github.com/flutter/plugins without changing the package's version number. 

Therefore it's possible for people on the same team to have pub got the package before and after the behaviour change and get different behaviours despite being on the same version. 

Create a test to machine enforce version changes.

**Comment by mit-mit** [comment]
I'm not sure I entirely follow; I don't believe pub allows uploading changes without changing the version number?

**Comment by xster** [comment]
I may have had an incomplete interpretation of what happened. But I think posse experienced this:

Person A gets the latest published version of firebase_analytics before 
https://github.com/flutter/plugins/pull/287

Person B gets the latest published version of firebase_analytics after 
https://github.com/flutter/plugins/pull/287

They're now on the same version but have different behavior

I think if a mechanism forced https://github.com/flutter/plugins/pull/293 to happen at the same time as https://github.com/flutter/plugins/pull/287, this issue wouldn't occur.

**Comment by xster** [comment]
At a glance, I feel like it's different. I have an impression that that one, like #12945, is more about plugins themselves having incompatible secondary dependencies between them. cc @collinjackson in case I'm incorrectly describing it.

This one is about one plugin being retrieved at different time having different code despite being on the same version.

**Comment by zoechi** [comment]
Might be related to the download
`flutter pub-get` tries to get the versions listed in `pubspec.lock` (if there is one, might be worth committing to ensure all have the same)
`flutter upgrade` and `flutter packages upgrade` ignore `pubspec.lock` and just try to find the most recent versions that are compatible with each other.

@xster what are the dependency constrains in `pubspec.yaml`?

**Comment by stuartmorgan** [comment]
It's useful to be able to make minor changes without updating the version with no intent to publish (e.g., test or example code changes), and per the comment above it shouldn't be possible to accidentally publish in that case.

Absent definitive evidence that this can somehow happen, I'm going to close this.
