### ISSUE TITLE
Limited String length

### ISSUE THREAD

**Issue by Entrebear** [flutter/flutter#138941]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Recently my Strings have become limited in length. It seems to be limited to 1023 characters. When setting a string directly to a value of more than 1023 characters, or when concatenating multiple strings into a single string that is more than 1023 characters, it seems to only set the string as the first 1023 characters, cutting the rest of the characters off. I am able to set the same value in a Map without a problem. 

### Expected results

```
String randomString = "b2DLwwJ3hoewiSLb7PuBtNdRiRK9yQU2GO64dMjbiBU7JTD6Af6S2zvT4JgndUHOuL2V5tXAPdRBen5jvyWI9glAQ6ScH2goXVwmXneLI3WgrMBr8eyLlqKvD8HsCXU9dXb7kzJMA8uXliYabU0V54LNpLS9s8IHpVGsAo3AYR5NwqEN5gOx27f5eNJXt4sjSFrQxiP8qM4AXAV1cJxHUYA4qivJ9jmxksy2vuB83psMpnXOvijdSxND8jNFgEGfL9Utb16gDPHcuR6jhnPANOjTe3lPafc6oHVw362OgvekDJZ3TSktFzeme1FDnMAoBTKpY481tYRppm1w0zph5hILo4YEJD4LwR9puPyozZtZO2oD1qUXjcFA3qXyTkMF9wsoSyfyKzYIguhWJwM6GkAusySUpy9FlatWBpd3KqLo44IzPzyCnHJZQEfGMEFShrpNX5JOAL2iOho3iArU6DLTPUJsjcHPRvFELOljHbyOiwpz1iOXXDOn6AAhAVKrtpwOWPf8SUDO71e6sEaHYz63icHPS1rRyour0Dj0U3uG6FqxhBSRONrQusMdVpOgtVtNlPvA17X0oHFKx7nfr7pLg7Ml0BLL2W6Ja0hBX16tIOWbmGwRWC4nMpPonKSIT9YFD8V6oEIjxK5hbio9csKno2lnpBLsYXGuvaK5EUSviBvO5YfhrdpWXE0GXE1ppxh2F157mzUcMUptM44jEc9ZFXC4m4Tg0fVxsT2ZDcXn2QPlYnn9skdR2OgBNQDYGT0RVHu4WyYYxEeYi6K3Hade1hQ6eAztKm7IhmmHVxoFmH2uRtPJsxMp2dtEgUAXEM87mM9QKURajT4a8EVM3okMgYyMMsvPAwYTBoklv2mmiLFMPXEKmufCsGvlJUaqhHF6V05sJWfZwCwiJa7MJmb9tSEgbttPHqSMuy5vIjcppRWk9HO4E92CTgRmI5GvHYmWS9xliI2kOWqvHxovzzo7DTOSQ9iNW0RQEjBVOSKddoR3GI5iBfCj6eWbqRLwGWTVaampZHci872VofZJe6fe7JNWGbN7feXrx0TIP4SsIxStNeNApMDq095SUzZlLwNE34vJq17ZswNIvv32uKmbAJozVeMSfmUOd4Vy7DB02FWv4oiYkGhCs4t9gJ6qJfoLODwcbuWoSc9ew6JugGi8nbkBMgxrbVuWXI4pk270AZ0cXgnRh6tw52nSMoLGKJXu0D0BU58hSterOP84YqyI0LruySTmC2HTjfoph2RZDRGQjsEqTHErqIblkBynBmclZW2NBanJxCsazokiuTvdJH5WIq0PLQOxr4w01LDUmtDSn9aopNLFnXOZTNIcKGUArURlKQ8kvQ9eKttQtAAbVJ8p5GzXejW4mk8mfyjUs85So9UVloZ73Gf2nu9roIiUxVNCIdx4hnYynxkPMAAZ0DT1o4cXKFebykqBJpSwuEOsU911YBdsdOzhVZSgEx4xLAJpUUanWUUl6aujeytB4z0xWYcUsC68lUBIbsD83qYkV3tsNRwJe25p7QFONojER7pLtAadfEbl9UW8cka3FBKylwlF25GF9ACWV99msw4p99TO5W57TlweNjh7gt14xYqfmprCtnylv6aXT82OuRogZUcvg4MyTYj07JqiQxzK9kGJEN88ELdMhe8gwqmic0Z5QJcDvxvVpFjSpCa2DFfrrBvM2JIVrG7AU7TrZQEbSrA89yAkCfKsEvs4LbyV8ImXelU6URAR3t3QzrN7GRtOFDZzwyxX2tD7J8BSIsmfgzVvgsvPtQsuwgYiJjpX3wsroP21Ja93SNFozFylOUdYFvKggI3EACs6nNn6uz0g8DnAbax1WWziprLRXw2r8n9WE1GMbsBJbyCthP7TM8a0nVlxJrGcB8fFXFAJElwyxxDn17TdzjsldqYM8EKDLcK7Wv4lOHBtTyk4L68lT64WUtBKqZrPaYSUTHF7QKYQt4mpyIfFVdv0eY9lEBUKrQppyWsr5v4asaM4fBH5BX9dF56nNm0OD5XID9SbnihzKxlASYF8vPr1F5bW"

print(randomString);

```
`I/flutter ( 8689): b2DLwwJ3hoewiSLb7PuBtNdRiRK9yQU2GO64dMjbiBU7JTD6Af6S2zvT4JgndUHOuL2V5tXAPdRBen5jvyWI9glAQ6ScH2goXVwmXneLI3WgrMBr8eyLlqKvD8HsCXU9dXb7kzJMA8uXliYabU0V54LNpLS9s8IHpVGsAo3AYR5NwqEN5gOx27f5eNJXt4sjSFrQxiP8qM4AXAV1cJxHUYA4qivJ9jmxksy2vuB83psMpnXOvijdSxND8jNFgEGfL9Utb16gDPHcuR6jhnPANOjTe3lPafc6oHVw362OgvekDJZ3TSktFzeme1FDnMAoBTKpY481tYRppm1w0zph5hILo4YEJD4LwR9puPyozZtZO2oD1qUXjcFA3qXyTkMF9wsoSyfyKzYIguhWJwM6GkAusySUpy9FlatWBpd3KqLo44IzPzyCnHJZQEfGMEFShrpNX5JOAL2iOho3iArU6DLTPUJsjcHPRvFELOljHbyOiwpz1iOXXDOn6AAhAVKrtpwOWPf8SUDO71e6sEaHYz63icHPS1rRyour0Dj0U3uG6FqxhBSRONrQusMdVpOgtVtNlPvA17X0oHFKx7nfr7pLg7Ml0BLL2W6Ja0hBX16tIOWbmGwRWC4nMpPonKSIT9YFD8V6oEIjxK5hbio9csKno2lnpBLsYXGuvaK5EUSviBvO5YfhrdpWXE0GXE1ppxh2F157mzUcMUptM44jEc9ZFXC4m4Tg0fVxsT2ZDcXn2QPlYnn9skdR2OgBNQDYGT0RVHu4WyYYxEeYi6K3Hade1hQ6eAztKm7IhmmHVxoFmH2uRtPJsxMp2dtEgUAXEM87mM9QKURajT4a8EVM3okMgYyMMsvPAwYTBoklv2mmiLFMPXEKmufCsGvlJUaqhHF6V05sJWfZwCwiJa7MJmb9tSEgbttPHqSMuy5vIjcppRWk9HO4E92CTgRmI5GvHYmWS9xliI2kOWqvHxovzzo7DTOSQ9iNW0RQEjBVOSKddoR3GI5iBfCj6eWbqRLwGWTVaampZHci872VofZJe6fe7JNWGbN7feXrx0TIP4SsIxStNeNApMDq095SUzZlLwNE34vJq17ZswNIvv32uKmbAJozVeMSfmUOd4Vy7DB02FWv4oiYkGhCs4t9gJ6qJfoLODwcbuWoSc9ew6JugGi8nbkBMgxrbVuWXI4pk270AZ0cXgnRh6tw52nSMoLGKJXu0D0BU58hSterOP84YqyI0LruySTmC2HTjfoph2RZDRGQjsEqTHErqIblkBynBmclZW2NBanJxCsazokiuTvdJH5WIq0PLQOxr4w01LDUmtDSn9aopNLFnXOZTNIcKGUArURlKQ8kvQ9eKttQtAAbVJ8p5GzXejW4mk8mfyjUs85So9UVloZ73Gf2nu9roIiUxVNCIdx4hnYynxkPMAAZ0DT1o4cXKFebykqBJpSwuEOsU911YBdsdOzhVZSgEx4xLAJpUUanWUUl6aujeytB4z0xWYcUsC68lUBIbsD83qYkV3tsNRwJe25p7QFONojER7pLtAadfEbl9UW8cka3FBKylwlF25GF9ACWV99msw4p99TO5W57TlweNjh7gt14xYqfmprCtnylv6aXT82OuRogZUcvg4MyTYj07JqiQxzK9kGJEN88ELdMhe8gwqmic0Z5QJcDvxvVpFjSpCa2DFfrrBvM2JIVrG7AU7TrZQEbSrA89yAkCfKsEvs4LbyV8ImXelU6URAR3t3QzrN7GRtOFDZzwyxX2tD7J8BSIsmfgzVvgsvPtQsuwgYiJjpX3wsroP21Ja93SNFozFylOUdYFvKggI3EACs6nNn6uz0g8DnAbax1WWziprLRXw2r8n9WE1GMbsBJbyCthP7TM8a0nVlxJrGcB8fFXFAJElwyxxDn17TdzjsldqYM8EKDLcK7Wv4lOHBtTyk4L68lT64WUtBKqZrPaYSUTHF7QKYQt4mpyIfFVdv0eY9lEBUKrQppyWsr5v4asaM4fBH5BX9dF56nNm0OD5XID9SbnihzKxlASYF8vPr1F5bW

`

### Actual results

```
String randomString = "b2DLwwJ3hoewiSLb7PuBtNdRiRK9yQU2GO64dMjbiBU7JTD6Af6S2zvT4JgndUHOuL2V5tXAPdRBen5jvyWI9glAQ6ScH2goXVwmXneLI3WgrMBr8eyLlqKvD8HsCXU9dXb7kzJMA8uXliYabU0V54LNpLS9s8IHpVGsAo3AYR5NwqEN5gOx27f5eNJXt4sjSFrQxiP8qM4AXAV1cJxHUYA4qivJ9jmxksy2vuB83psMpnXOvijdSxND8jNFgEGfL9Utb16gDPHcuR6jhnPANOjTe3lPafc6oHVw362OgvekDJZ3TSktFzeme1FDnMAoBTKpY481tYRppm1w0zph5hILo4YEJD4LwR9puPyozZtZO2oD1qUXjcFA3qXyTkMF9wsoSyfyKzYIguhWJwM6GkAusySUpy9FlatWBpd3KqLo44IzPzyCnHJZQEfGMEFShrpNX5JOAL2iOho3iArU6DLTPUJsjcHPRvFELOljHbyOiwpz1iOXXDOn6AAhAVKrtpwOWPf8SUDO71e6sEaHYz63icHPS1rRyour0Dj0U3uG6FqxhBSRONrQusMdVpOgtVtNlPvA17X0oHFKx7nfr7pLg7Ml0BLL2W6Ja0hBX16tIOWbmGwRWC4nMpPonKSIT9YFD8V6oEIjxK5hbio9csKno2lnpBLsYXGuvaK5EUSviBvO5YfhrdpWXE0GXE1ppxh2F157mzUcMUptM44jEc9ZFXC4m4Tg0fVxsT2ZDcXn2QPlYnn9skdR2OgBNQDYGT0RVHu4WyYYxEeYi6K3Hade1hQ6eAztKm7IhmmHVxoFmH2uRtPJsxMp2dtEgUAXEM87mM9QKURajT4a8EVM3okMgYyMMsvPAwYTBoklv2mmiLFMPXEKmufCsGvlJUaqhHF6V05sJWfZwCwiJa7MJmb9tSEgbttPHqSMuy5vIjcppRWk9HO4E92CTgRmI5GvHYmWS9xliI2kOWqvHxovzzo7DTOSQ9iNW0RQEjBVOSKddoR3GI5iBfCj6eWbqRLwGWTVaampZHci872VofZJe6fe7JNWGbN7feXrx0TIP4SsIxStNeNApMDq095SUzZlLwNE34vJq17ZswNIvv32uKmbAJozVeMSfmUOd4Vy7DB02FWv4oiYkGhCs4t9gJ6qJfoLODwcbuWoSc9ew6JugGi8nbkBMgxrbVuWXI4pk270AZ0cXgnRh6tw52nSMoLGKJXu0D0BU58hSterOP84YqyI0LruySTmC2HTjfoph2RZDRGQjsEqTHErqIblkBynBmclZW2NBanJxCsazokiuTvdJH5WIq0PLQOxr4w01LDUmtDSn9aopNLFnXOZTNIcKGUArURlKQ8kvQ9eKttQtAAbVJ8p5GzXejW4mk8mfyjUs85So9UVloZ73Gf2nu9roIiUxVNCIdx4hnYynxkPMAAZ0DT1o4cXKFebykqBJpSwuEOsU911YBdsdOzhVZSgEx4xLAJpUUanWUUl6aujeytB4z0xWYcUsC68lUBIbsD83qYkV3tsNRwJe25p7QFONojER7pLtAadfEbl9UW8cka3FBKylwlF25GF9ACWV99msw4p99TO5W57TlweNjh7gt14xYqfmprCtnylv6aXT82OuRogZUcvg4MyTYj07JqiQxzK9kGJEN88ELdMhe8gwqmic0Z5QJcDvxvVpFjSpCa2DFfrrBvM2JIVrG7AU7TrZQEbSrA89yAkCfKsEvs4LbyV8ImXelU6URAR3t3QzrN7GRtOFDZzwyxX2tD7J8BSIsmfgzVvgsvPtQsuwgYiJjpX3wsroP21Ja93SNFozFylOUdYFvKggI3EACs6nNn6uz0g8DnAbax1WWziprLRXw2r8n9WE1GMbsBJbyCthP7TM8a0nVlxJrGcB8fFXFAJElwyxxDn17TdzjsldqYM8EKDLcK7Wv4lOHBtTyk4L68lT64WUtBKqZrPaYSUTHF7QKYQt4mpyIfFVdv0eY9lEBUKrQppyWsr5v4asaM4fBH5BX9dF56nNm0OD5XID9SbnihzKxlASYF8vPr1F5bW"

print(randomString);
```

`I/flutter ( 8689): b2DLwwJ3hoewiSLb7PuBtNdRiRK9yQU2GO64dMjbiBU7JTD6Af6S2zvT4JgndUHOuL2V5tXAPdRBen5jvyWI9glAQ6ScH2goXVwmXneLI3WgrMBr8eyLlqKvD8HsCXU9dXb7kzJMA8uXliYabU0V54LNpLS9s8IHpVGsAo3AYR5NwqEN5gOx27f5eNJXt4sjSFrQxiP8qM4AXAV1cJxHUYA4qivJ9jmxksy2vuB83psMpnXOvijdSxND8jNFgEGfL9Utb16gDPHcuR6jhnPANOjTe3lPafc6oHVw362OgvekDJZ3TSktFzeme1FDnMAoBTKpY481tYRppm1w0zph5hILo4YEJD4LwR9puPyozZtZO2oD1qUXjcFA3qXyTkMF9wsoSyfyKzYIguhWJwM6GkAusySUpy9FlatWBpd3KqLo44IzPzyCnHJZQEfGMEFShrpNX5JOAL2iOho3iArU6DLTPUJsjcHPRvFELOljHbyOiwpz1iOXXDOn6AAhAVKrtpwOWPf8SUDO71e6sEaHYz63icHPS1rRyour0Dj0U3uG6FqxhBSRONrQusMdVpOgtVtNlPvA17X0oHFKx7nfr7pLg7Ml0BLL2W6Ja0hBX16tIOWbmGwRWC4nMpPonKSIT9YFD8V6oEIjxK5hbio9csKno2lnpBLsYXGuvaK5EUSviBvO5YfhrdpWXE0GXE1ppxh2F157mzUcMUptM44jEc9ZFXC4m4Tg0fVxsT2ZDcXn2QPlYnn9skdR2OgBNQDYGT0RVHu4WyYYxEeYi6K3Hade1hQ6eAztKm7IhmmHVxoFmH2uRtPJsxMp2dtEgUAXEM87mM9QKURajT4a8EVM3okMgYyMMsvPAwYTBoklv2mmiLFMPXEKmufCsGvlJUaqhHF6V05sJWfZwCwiJa7MJmb9tSEgbttPHqSMuy5vIjcppRWk9HO4E92CTgRmI5GvHYmWS9xliI2kOWqvHxovzzo7DTOSQ9iNW0RQEjBVOSKddoR3GI5iBfCj6eWbqRL
`

### Code sample

<details><summary>Code sample</summary>
As seen in expected and actual results.

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.16.0, on Microsoft Windows [Version 10.0.22000.2538], locale en-ZA)
    • Flutter version 3.16.0 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (8 days ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\BarryB\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.2.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32516.85
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.84.2)
    • VS Code at C:\Users\BarryB\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.76.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.2538]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 116.0.5845.180
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 119.0.2151.72

[√] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by RandalSchwartz** [comment]
The debug print is necessarily truncated.  When I ran your code but changed it to print the length, it was indeed 2048 chars long.  I hope that resolves it for you.
