### ISSUE TITLE
[web] Multiview management JS API.

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#138930]
### Document Link

https://flutter.dev/go/web-multiview-js-api

### What problem are you solving?

Flutter Web only supports rendering to a single "view". This used to be limited to the `body` tag, but now it can be any `hostElement`.

Multi-view support is coming to desktop platforms, and for the web it's a good match to render an app split across multiple `hostElement`s.

This design document proposes a JS API that would enable an external application (JS) to add/remove views to a running Flutter Web app.

**Comment by p-mazhnik** [comment]
I understand this is all work in progress, but is it necessary for `addView`/`removeView` functions to return Promise? As I see in implementation, dart functions return Future, but this is not needed currently

https://github.com/flutter/engine/blob/da3d49c30bccfbe0573d539d0aac55356b58e00e/lib/web_ui/lib/src/engine/app_bootstrap.dart#L71-L74

From the design doc:
```js
let viewId1 = (await flutterApp).addView({
  hostElement: document.querySelector('#flutter_view_1');
});
```

but currently two awaits are needed:
```js
let viewId1 = await (await flutterApp).addView({
  hostElement: document.querySelector('#flutter_view_1');
});
```

Having async functions make it unsafe to use the functions in lifecycle methods of other frameworks. For example, React doesn't support async lifecycle methods.

**Comment by ditman** [comment]
Hm, I understand what you're saying.

The two awaits shouldn't be a problem, it just happens that it's very convenient to leak the Promise of a FlutterApp, rather than the FlutterApp itself. (The JS code could be changed to await for the resolved promise).

I originally made those methods async, because I wasn't sure how "expensive" it was going to be to register/deregister views on the engine. It seems pretty unnecessary now.

WDYT @mdebbar, should add/removeView JS methods be sync?

**Comment by p-mazhnik** [comment]
@ditman @mdebbar I've created a PR so it will be easier to discuss proposed change there

**Comment by ditman** [comment]
Also @jacobsimionato! I'll ping you later tonight!

**Comment by jacobsimionato** [comment]
I personally think that some goals (in order of priority) for this API are:

1. Make it possible to create and destroy Flutter views within the host site without any visual glitches. I.e. you should be able to show a loading screen or spinner during any asynchronous parts of the bootstrap process and then hide the loading UI and show Flutter in the same frame.

2. Ensure creating and destroying Flutter views has minimal or no jank impact on the host app. E.g. if there is (regrettably)  heavy work to do when creating or destroying Flutter views, it's preferable to spread it out asynchronously vs doing it in one blocking chunk that causes the browser to block frames. I'm not even sure if there are choices to make here given the constraints of the browser environment, event loop etc.

3. Make `addView` and `removeView` APIs synchronous which would make it much simpler for developers to work with.

So I agree with @p-mazhnik that these APIs would be much more user friendly if they were synchronous, but I was just curious that we aren't going to negatively impact goals 1 and 2 above in the long term if we make this change. E.g. if we switch to a synchronous API, I think it's important that we can guarantee we'll draw actual Flutter content in the next frame after addView returns.

**Comment by p-mazhnik** [comment]
I mostly agree with what you're saying. I think the real issue with the current async API is that there is no way to cancel what `addView` is doing until it is completed – you have to wait for it to get the `viewId`, which is then needed for `removeView`. I wanted to solve this by making it synchronous (because it is synchronous internally) – this way view can be cleaned up in the same external synchronous process that initialized addition of the view, without any side-effects. Otherwise, in case of asynchronous api, i don't think we currently can guarantee that a view can be added and immediately removed before the next repaint? If it is true, I think it also breaks goals 1 and 2?

**Comment by ditman** [comment]
Something that we don't have yet, but could be added, is some internal support for views that are "yanked" that means, removed from the DOM externally, but not with `removeView`. I think that'd solve @p-mazhnik's problem.

In any case, I don't know if it can be guaranteed that adding a view is always going to be fully sync, hence why the method is `async`. In every other platform AFAIK, adding a view is certainly async.

**Comment by ditman** [comment]
The desktop team is OK with our API being sync, let me give it a shot, and see how it goes in our test apps!

**Comment by jacobsimionato** [comment]
Sounds good re trying it out! Is there any reason the behavior will be different right now? The future returns synchronously anyway, so I assumed marking the API synchronous will be a no-op and the question here is more about future changes to the implementation that may need to be asynchronous.

Re yanked views: Even if this became a synchronous API, it would be really nice if this could be supported in the same API layer without wrapping it in another layer of hideable DOM. Another possibility is an API that returns some object that contains the viewId synchronously, but could potentially have a promise on it that resolves when the view is fully loaded. E.g.

```js
// Create a view
let myView = flutterApp.addView(hostElement: someElement);

// Remove a view, which can be done synchronously after creation.
flutterApp.removeView(myView.id);

// Alternative API for removing a view?
myView.remove();

// Wait for view to load
await myView.loadingPromise;
```

I'm just bouncing some ideas around, but overall I'd be thrilled to have synchronous APIs as @p-mazhnik is requesting as long as there is no major risk of glitchy behavior!

**Comment by ditman** [comment]
That API looks interesting Jacob. The yanking support is needed anyways, just to build some resilience into the Flutter App when views go missing outside of its control (not because the API to remove the view is lacking).

I like returning something more than a viewId to the JS code, and we can definitely explore that in the next version, or if we decide that we want to add some asynchronicity in the API without really making the methods async!

I will definitely add the "return something other than a viewId" proposal to the API, as a possible future addition, especially if at some point the API needs to be more asynchronous.

**Comment by ditman** [comment]
As of the behavior now: I don't think that much would change. We'd start returning a straight viewId rather than a Promise(viewId), but in JS you can `await NotAPromise` and it'll immediately return `NotAPromise`, so there's probably no changes needed in current user apps (only to clean up the unneeded `await`s, of course)

**Comment by p-mazhnik** [comment]
I like @jacobsimionato's idea with API that returns some object. Here are some examples from web frameworks that could be used for inspiration:
```js
// Angular
const app = await createApplication();
app.bootstrap(AngularComponent, document.getElementById('root'));
app.destroy();

// React
const root = React.createRoot(
  document.getElementById('root') as HTMLElement
);
root.render(<ReactApp />);
root.unmount();

// Vue
const app = createApp(VueApp);
app.mount('#root');
app.unmount();
```

So potentially we could have something similar in Flutter
```js
// sync view object creation
const view = flutterApp.createView();
// async mount function
await view.mount({hostElement: document.getElementById('root')});

view.remove();
```

**Comment by p-mazhnik** [comment]
> The reason I don't want to remove hostElement from Flutter is that it is not created by Flutter, so JS should own its complete lifecycle

Completely agree, this is reasonable and aligns with how react/vue/angular behave as well. 

> Should addView/removeView be called something like mount(config) and unmount(viewId)

`flutterApp.mount` sounds like flutter app itself is rendered on the screen, and not the flutter view. For example, from the two calls in a row:
```js
flutterApp.mount()
flutterApp.mount()
```
I would expect that something is trying to mount twice, rather than two independent views being mounted.

`flutterApp.addView` seems to make more sense... Maybe if JS object is ever needed, it can be returned using naming `flutterApp.createView`?

**Comment by ditman** [comment]
> flutterApp.mount sounds like flutter app itself is rendered on the screen, and not the flutter view. For example, from the two calls in a row:
>
> ```js
> flutterApp.mount()
> flutterApp.mount()
> ```

I mean, you'd never call `mount` without any parameters, it'd be more like:

```js
flutterApp.mount({
  hostElement: document.querySelector('#view_id_1'),
});
// or
flutterApp.mount(anotherViewConfig);
```

Maybe it looks weird because every other framework only supports a single root? 😎

**Comment by p-mazhnik** [comment]
> you'd never call `mount` without any parameters

Yeah, so by providing new parameters to `mount` function, it feels like you're trying to re-mount the same object with the new parameters...

I think `mount` in linux should have a source and target that need to be specified: **what** drive is mounted and **where**.
If we apply this to the `flutterApp.mount({ hostElement: document.getElementById('view_root')})`, it seems that **flutterApp** is mounted to **hostElement**, which is not what we expect. For the `mount` naming, `flutterView.mount({ hostElement: document.getElementById('view_root')})` seems more appropriate to me :)

btw Vue has support for multiple roots:
```js
const app1 = createApp({
  /* ... */
})
app1.mount('#container-1')

const app2 = createApp({
  /* ... */
})
app2.mount('#container-2')
```
They also have a restriction that for each app instance, `mount()` can only be called once.

**Comment by ditman** [comment]
> They also have a restriction that for each app instance, mount() can only be called once.

Right, in flutter web, that restriction doesn't exist, because one single app instance can render to multiple "roots".

> I am not strictly against mount, but I think it might be confusing for the developers, although I could be mistaken

Nope, let's find a better name. I'd like for it to not have `view` in the name. Something like `connect`/`disconnect` or `attach`/`detach` or similar.

Connect sounds good too, because it reminds me of [isConnected](https://developer.mozilla.org/en-US/docs/Web/API/Node/isConnected).

(Also: maybe `addView` is the way to go, but I'd like to reserve it for the later methods that return a `View` object, if we ever add them)

**Comment by jacobsimionato** [comment]
If you're quite convinced that we need a `view` object eventually, I think you may as well add it now. I quite like the idea of moving `removeView` to a method on the `view` object because it eliminates a category of errors - trying to call `removeView` with an invalid `viewId` (obviously there is still the error of trying to call `removeView` twice).

If if you don't want to go down that path, maybe it's fine to just keep calling the current version `addView`? Otherwise I don't mind attach/detach.

**Comment by ditman** [comment]
> If you're quite convinced that we need a view object eventually, I think you may as well add it now.

Definitely not convinced that we'll need that object in the future, but it's a good extension point if we want to add more view-related APIs to the embedder.

If `addView` sounds good to everybody, I can revert the renaming pretty easily. Here's some code that I've written applying @p-mazhnik's PR + renaming to `mount`:

* https://github.com/ditman/flutter-experimental/blob/c7cc2c4b06f8cf1b8bd8439607e40bf9b8d59515/multi_counter/web/index.html#L56-L118

(That's the source for [this app](https://dit-multiview-tests.web.app/))

**Comment by ditman** [comment]
OK, you guys convinced me to not rename the methods. If you're not concerned with `addView` not returning a view right away, I'm not either. I'll take a look at the performance implications of the change to sync, and if it'll hurt us in the future.

For example, right now there's a couple of white frames between adding a view and having flutter take over and start rendering, and it'd be nice to have a way to reduce that lapse of unrendered content (or have a way to tell HTML: the view is not fully rendered yet, don't show it).

**Comment by jacobsimionato** [comment]
Awesome - thanks for looking deep into this! Helping avoid those white frames would be fantastic - I think that's the top priority see https://github.com/flutter/flutter/issues/138930#issuecomment-1979854244 above.

If we can't get Flutter to reliably paint in the next frame after `addView` is called, I think the ideal chain of events is something like:
1. Browser calls Flutter's requestAnimationFrame callback to tell it to render a frame.
2. If Flutter is truly ready to layout and paint the first frame for a given view, it resolves the loading Promise for that view.
3. The host framework then hides any loading spinners and ensures that the Flutter view has the correct size etc.
4. Flutter performs the actual layout and paint logic, based on the size of the host elements and constraints etc which may have been updated in step 3.
5. The frame is rendered by the browser. User sees a clean transition from DOM-based loading UI to Flutter UI.

**Comment by ditman** [comment]
OK, I think I understand the white frames better now. Flutter is removing whatever HTML tricks the programmer writes into the flutter view right as the view gets registered [here](https://github.com/flutter/engine/blob/5097f0b5f3c40d25d790fccce166b24b20ebfb2b/lib/web_ui/lib/src/engine/view_embedder/flutter_view_manager.dart#L42-L47), but then that has an async gap where we [trigger an event](https://github.com/flutter/engine/blob/5097f0b5f3c40d25d790fccce166b24b20ebfb2b/lib/web_ui/lib/src/engine/view_embedder/flutter_view_manager.dart#L66C5-L66C29) so the app is aware that the [views have changed](https://github.com/ditman/flutter-experimental/blob/7995a4324a527c8e2d46f3f36b01a36bf675ffb2/multi_counter/lib/src/multiview.dart#L47-L53) calls setState, which then causes the tree to [recompose](https://github.com/ditman/flutter-experimental/blob/7995a4324a527c8e2d46f3f36b01a36bf675ffb2/multi_counter/lib/src/multiview.dart#L60).

One way of removing the gap between HTML and Flutter may be to postpone the injection of the DOM of the Flutter view into the hostElement until we've started painting frames there, so the handoff is more immediate.

**Comment by jacobsimionato** [comment]
Okay, I know I've been pushing for having an async API based on the assumption that rendering the first frame will likely always need to occur after an async gap. But it sounds like I was wrong about that based on the conversation today with @ditman and @yjbanov , so sync sounds great. Much easier for the developer if we can get to the point where they call synchronous `addView` and then Flutter renders real content ready for the next frame. Apologies for the noise!

**Comment by p-mazhnik** [comment]
Great investigation @ditman! 

Just in case, attaching the demo of the issue so that others can better understand what we are discussing.

In the demo, loading spinner is displayed in the `hostElement` provided to the `addView` function (I used current async version for the recording, if it matters (it doesn't)), then Flutter removes child dom elements and renders its ui after the gap.

<details>
<summary>demo</summary>
<video src="https://github.com/flutter/flutter/assets/25964451/a3ac3c8e-7e4e-4d8b-8ba9-23d0151be8c8" />
</details>

**Comment by ditman** [comment]
> loading spinner is displayed in the hostElement provided to the addView function

Correct, and it only shows for a few frames, until flutter takes control of the view and erases its contents (before it's ready to render).

We're thinking of (maybe) delaying the injection of the Flutter View into the DOM, until the renderer is going to do something with it.

**Comment by ditman** [comment]
The `addView`/`removeView` methods have been made sync in the code.

I've tweaked the docs to reflect this better. I've also tweaked some types because the JS-interop that we're actually using is less wishy-washy than what I knew about when I originally wrote the document!

**Comment by wanjm** [comment]
what is the status of this now?

**Comment by ditman** [comment]
@wanjm this should be available in Flutter 3.22 stable, but we're still polishing some bits of the embedding (like wheel scrolling, text inputs, and things like that). Expect a somewhat public announcement (alongside proper documentation) when this is ready to be tested!

**Comment by wanjm** [comment]
@ditman  thanks for your reply;
as been told in multi-window, flutter raster views that has not been changed for it raster all the views when it need to refresh;   does web version has the problem?

**Comment by ditman** [comment]
> flutter raster views that has not been changed for it raster all the views when it need to refresh

Hm, as far as I know, multi-view is implemented with Widgets, so I guess it depends on how your state propagates to your different views and your repaint boundaries. When I tested with my "multi-apps" I don't think it was re-rendering more than one "scaffold" at a time, but of course that's also not the typical layout...

This is a very long way of saying: the web engine has no opinion about what needs to be re-rendered, if the framework says that a certain widget tree needs to be re-rendered, it'll do that.

**Comment by p-mazhnik** [comment]
@ditman I noticed that current implementation of `ui_web.views.getHostElement` API only returns `hostElement` when multi-view embedding is used. I believe we need to support implicit view case as well, so this API can be independent of the different embedding strategies. I created a PR to support implicit view case: https://github.com/flutter/engine/pull/53296

**Comment by ditman** [comment]
This has landed, and is part of the Flutter framework now.

See: 

* https://docs.flutter.dev/platform-integration/web/embedding-flutter-web
