### ISSUE TITLE
Build hook for Flutter Web?

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#138992]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Hi thanks for the great framework! When developing https://github.com/fzyzcjy/flutter_rust_bridge v2, we are having the following scenario: We need to compile some Rust code into WASM, which is used by Flutter code.

For the native platforms, the build can be invoked easily. For example, in Android, we can just modify the build.gradle and let it invoke the build commands; similar for iOS, windows, macos, linux. However, IMHO there is no place to inject such "hooks" when building.

Surely, we can just create another tool that wraps the "build rust + call flutter run" process (that's what we are doing currently) - but that looks suboptimal.

I guess it is somehow related to the native assets https://github.com/dart-lang/sdk/issues/50565 / https://github.com/flutter/flutter/issues/129757, but this is just a (small) part of what native asset system is going to cover, and seems to be also possibly orthogonal (e.g. today's Android/iOS/... build hook can be implemented, but without native assets), so I make a separate issue here.

### Proposal

(see above)

**Comment by jonahwilliams** [comment]
> Surely, we can just create another tool that wraps the "build rust + call flutter run" process (that's what we are doing currently) - but that looks suboptimal.

Why? This could be as cheap as `flutter build web && ./your_tool`

**Comment by fzyzcjy** [comment]
@jonahwilliams Good question! There may be some cases, for example:

* If someone wants to publish a pub.dev package with native (say Rust) code, it is not very great to require every user of the package to execute this extra tool when they want to run their app
* People may not be using `flutter run -p chrome` / `flutter build web`, but use VSCode / Intellij IDEA / other tools. For example, suppose one clicks the "run" button in Intellij IDEA. In that case, to ensure the extra Rust compilation happens, it is not super trivial.
* In the 5 native platforms (android/ios/...), there already exists build hook. Flutter aims uniform experience across platforms, so why not for web ;)

Personally speaking, I want to make V2 of https://github.com/fzyzcjy/flutter_rust_bridge as convenient to use as possible.

**Comment by harryfei** [comment]
We need this

**Comment by yjbanov** [comment]
Flutter's web build tool is pretty simple. It knows how to build the Flutter bits, but it has no opinion about how to build anything other than Flutter. Unlike the Android toolchain, which includes gradle, our web tools do not include any fancy build systems, like NPM, WebPack, etc. If you need to combine Flutter Web with non-Flutter code, I think the best place to put that functionality is _above_ Flutter, rather than inside it. For example, you could use `make` or `bazel` to call into `flutter build`, but also invoke the Rust tools.

**Comment by yjbanov** [comment]
cc @dcharkes who is working on something related

**Comment by dcharkes** [comment]
Yes, I envision having an asset type "wasm" in the future, which would then be consumed by the flutter tooling. Flutter web should then start invoking `build.dart` just like we do for flutter mobile/desktop.

I had some discussions with @eyebrowsoffire about this recently. Some notes can be found in:

* https://github.com/dart-lang/native/issues/156

Some earlier issues filed relevant for this:

* https://github.com/dart-lang/native/issues/325
* https://github.com/dart-lang/sdk/issues/46690

> Flutter's web build tool is pretty simple. It knows how to build the Flutter bits, but it has no opinion about how to build anything other than Flutter. Unlike the Android toolchain, which includes gradle, our web tools do not include any fancy build systems, like NPM, WebPack, etc. If you need to combine Flutter Web with non-Flutter code, I think the best place to put that functionality is above Flutter, rather than inside it. For example, you could use make or bazel to call into flutter build, but also invoke the Rust tools.

I was having a similar discussion recently with @mosuem in our quest of adding tree-shakable data assets to Dart/Flutter. The web frameworks on Dart all wrap dart2js or dart2wasm and don't have a full bundle format. So we need to do some exploration on how to address that. (E.g. lazy loading, modules, where are WASM modules hosted etc.)

**Comment by fzyzcjy** [comment]
Get it, thank you!

**Comment by christopherfujino** [comment]
Thank you for filing this. I am going to close this however, as given the work with native assets and yjbanov's point about composing complex web builds with some higher level tool, I don't think we would accept a proposal for ANOTHER way to do this.

**Comment by fzyzcjy** [comment]
You are welcome and also thank you!
