### ISSUE TITLE
[path_provider] documents folder

### ISSUE THREAD

**Issue by FMorschel** [flutter/flutter#138944]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

When we want our project to be able to find documents inside the user's computer, I believe that a good practice would be to find the `Documents` folder inside the user folder in all OSs. Sibling to the `Download` folder in all Desktop environments I believe. 

### Proposal

Create a `getDocumentssDirectory` method on `path_provider`. I believe this one should aim to simply have the functionality on all Desktop environments, not on Android or iOS.

**Comment by dam-ease** [comment]
Thanks for proposing this.
Can you help with more information on how this would differ from `getApplicationDocumentsDirectory()`?

**Comment by FMorschel** [comment]
I do not have a Mac, but I will try and test this on a virtual machine with Linux if needed. The issue was raised by me mostly because [this one](https://github.com/flutter/flutter/issues/118571) is not solved, maybe you can help me clarify that. 

The first comment there, after the description, shows the following path: `/Users/bbkane/Library/Containers/com.bbkane.readingWritingFiles/Data/Documents`. From what I could tell, this is running on a Mac the `getApplicationDocumentsDirectory` function.

I still have a question:
- Why is it that on Windows I get redirected to the Documents folder under my user's folder whereas on Mac (assuming my previous paragraph is right), Android and other systems give me a folder specific to my own app?

This question is asked because I can see a difference between the user Documents folder and a folder for documents my own app will store. Would then the second one be `getApplicationSupportDirectory`?

**Comment by dam-ease** [comment]
Thanks for your detailed response.
I think I understand that the `Documents ` folder you are referring to here is that of the device and not one specifically in the application.
Your proposal will be synonymous with `getExternalStorageDirectory` which is available only on Android.
If this is the case, kindly check out https://github.com/flutter/flutter/issues/127101, to confirm it's similar/related to the use case you are describing?

**Comment by FMorschel** [comment]
Yes, it is. Should this issue be closed then? Since that issue is more broad than this one?

**Comment by FMorschel** [comment]
Following the suggested issue and related ones, I found #77628 which is exactly what I was trying to say. I'm closing this in favour of that one ([this comment](https://github.com/flutter/flutter/issues/77628#issuecomment-1260894777) explains my thoughts as well)
