### ISSUE TITLE
[GoRouter] Using the same named route inside multiple routes as a sub-route gives error.

### ISSUE THREAD

**Issue by ShubhamHande99** [flutter/flutter#138948]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Steps to reproduce - 

1. Use the following routerConfig configuration.
2. Add routerConfig to materialApp
3. And run the app 
4. throws the exception.

Router configuration - 
```
final routerConfig = GoRouter(
 initialLocation: '/',
 debugLogDiagnostics: true,
 routes: [
   GoRoute(
     path: '/',
     builder: (context, state) => const TestHome(),
     routes: [
       GoRoute(
         name: 'profile',
         path: 'profile_detail',
         builder: (context, state) => const TestProfileDetail(),
         routes: [
           GoRoute(
             name: 'contact',
             path: 'contact',
             builder: (context, state) => const TestUserContact(),
           ),
         ],
       ),
       GoRoute(
         name: 'more',
         path: 'more',
         builder: (context, state) => const TestMore(),
         routes: [
           GoRoute(
             name: 'contact',
             path: 'contact',
             builder: (context, state) => const TestUserContact(),
           ),
         ],
       ),
     ],
   ),
 ],
);
```

### Expected results

I'm trying to use the **contact** route as sub-route within both the **profile** and **more** routes, navigating as follows:

**profile_detail/contact**
**more/contact**

### Actual results

But doing so is throwing the following exception when running the app - 
```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building TestApp(dirty, state: _TestAppState#baba7):
Assertion failed: 
!_nameToPath.containsKey(name)
"duplication fullpaths for name \"contact\":/profile_detail/contact, /more/contact"

**Comment by sachin96Boy** [comment]
The name property in GoRoute needs to be unique, Did you try changing the name property to a unique one to see if the issue resolves?

**Comment by ShubhamHande99** [comment]
@sachin96Boy thanks, It works as expected when using a unique name. 
I have one question: Is it proper to use multiple nested sub-routes like this, or are there any drawbacks in terms of performance issues?

**Comment by sachin96Boy** [comment]
Hi @ShubhamHande99, I don't think having Nested routes will affect the overall performance of the Flutter app. You might need to use more dummy widgets and have a const modifier for widgets that won't change over refreshes to have performance optimizations if needed.

**Comment by ShubhamHande99** [comment]
Using a unique name in the GoRoute solves the issue.
