### ISSUE TITLE
can't run flutter commands due to permissions issues in the path of .pub-cache folder

### ISSUE THREAD

**Issue by Jephtha** [flutter/flutter#138991]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

was having issues installing flutter in home dir ~ so i tried it again with sudo
eventually found out i don't have permissions to read or write files in home dir ~ (this is because i am using an organization laptop and i don't have administrator privileges)
i delete current flutter installation and reinstall in a dir i have permissions (~/Documents)
I install flutter by extracting the zip folder for mac with the apple silicion chip, add flutter to path and run flutter doctor

### Actual results

i can't run any flutter commands due to not have read and write permissions for my ~ dir. would like to specify the location flutter puts its .pub-cache folder and any related folders

i could request permissions temporarily and delete the .dartServer, .pub-cache, .dart-tool and any other flutter/dart related folders and files from home dir ~ 
and attempt a reinstallation of flutter. but before i do so, i wanted to confirm that flutter won't attempt to add those files back in home dir

is there a way to specify the dir of flutter pub cache folders? i would ideally like to have the paths to all those folders in ~/Documents

a similar request to this issue: https://github.com/flutter/flutter/issues/105257

### Logs

<details>
<summary>Logs</summary>

```console

dart fix
Building flutter tool...                                          
Resolving dependencies... (3.7s)
Creation failed, path = '/Users/jefang/.pub-cache/hosted-hashes' (OS Error: Permission denied, errno = 13)
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

```

</details>

<details>
<summary>Logs</summary>

```console

flutter pub get
Resolving dependencies...
Creation failed, path = '/Users/jefang/.pub-cache/hosted-hashes' (OS Error: Permission denied, errno = 13)
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries lef

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

Found an existing Pub cache at /Users/jefang/.pub-cache.
It can be repaired by running `dart pub cache repair`.
It can be reset by running `dart pub cache clean`.
Found an existing Dart Analysis Server cache at /Users/jefang/.dartServer.
It can be reset by deleting /Users/jefang/.dartServer.

```

</details>

**Comment by christopherfujino** [comment]
@Jephtha I think you really need to follow up with your network administrator. FWIW, `~` is a bash expansion, and I suspect the various dart tools are actually defaulting to the path pointed at by the `$HOME` env variable, so you may try overriding that to a path you control. However, I am not really qualified to give you IT advice :)
