### ISSUE TITLE
error: The class 'AutomaticKeepAliveClientMixin' can't be used as a mixin because it extends a class other than Object.

### ISSUE THREAD

**Issue by pulyaevskiy** [flutter/flutter#13895]
## Steps to Reproduce

I declared a class similar to `EditableTextState` from the SDK:

```
class RichTextEditorState extends State<RichTextEditor>
    with AutomaticKeepAliveClientMixin
    implements TextInputClient {
  // implementation...
}

## Logs

```
> flutter analyze
Analyzing /Users/anatoly/Projects/memspace...
  error • The class 'AutomaticKeepAliveClientMixin' can't be used as a mixin because it extends a class other than Object at lib/src/richtext/widgets.dart:61:10 • mixin_inherits_from_not_object
  hint • The value of the local variable 'memo' isn't used at lib/src/middleware/firebase_database.dart:71:9 • unused_local_variable
2 issues found.
```

## Flutter Doctor

```
> flutter doctor
[✓] Flutter (on Mac OS X 10.13.2 17C88, locale en-BY, channel master)
    • Flutter at /Users/anatoly/flutter
    • Framework revision 80c94446a5 (4 hours ago), 2018-01-03 13:05:12 -0800
    • Engine revision 37789650cb
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.e122f4825726035e4579471ef83848b1aa796444

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.3)
    • Android SDK at /Users/anatoly/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-26, build-tools 26.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.3.2)
    • Flutter plugin version 20.0.3
    • Dart plugin version 173.4127.31

[✓] Connected devices
    • iPhone 7 Plus • 1E60E39F-D6EB-4368-B84A-5356E2ED0854 • ios • iOS 11.2 (simulator)
```

**Comment by Hixie** [comment]
Sounds like somehow you've ended up with your project having "super_mixins" turned off.

If you have an `analysis_options.yaml` file, make sure it says 
```yaml
analyzer:
  language:
    enableStrictCallChecks: true
    enableSuperMixins: true
    enableAssertInitializer: true
```
...at the top.

**Comment by pulyaevskiy** [comment]
Thanks, that's what I was missing!

My project was created a few months ago so maybe it wasn't part of the project template at that point.
