### ISSUE TITLE
In App Purchase not completing purchasing status when user buy the product

### ISSUE THREAD

**Issue by iSaqibShafique** [flutter/flutter#138996]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I have completed a purchase in flutter, the purchase sheet says "Complete" with a "tick" mark on iOS, but after 3 seconds it reshow the purchase sheet in iOS.

### Expected results

When a purchased completed, obviously the purchase sheet have to dispose.

### Actual results

When a user buy the products, after 4 seconds It shows the purchase sheet again.

### Code sample

```
static InAppPurchase inAppPurchase = InAppPurchase.instance;
  late StreamSubscription subscription;
  List<ProductId> productIds = [
    ProductId(id: "monarchjournal_999_1m", isConsumable: true),
    ProductId(id: "monarchjournal_1999_1m", isConsumable: true),
  ];

  RxList<ProductDetails> productDetails = <ProductDetails>[].obs;

  Future<void> init() async {
    if (await inAppPurchase.isAvailable()) {
      await inAppPurchase.queryProductDetails({
        "monarchjournal_999_1m",
        "monarchjournal_1999_1m",
      }).then((value) {
        Logger logger = Logger();
        logger.d(value.notFoundIDs);
        ProductDetailsResponse response = value;
        productDetails.value = response.productDetails;
      });
    }
  }

  @override
  void onInit() {
    init();
    listenPurchase();
    super.onInit();
  }

  void listenPurchase() {
    subscription = inAppPurchase.purchaseStream.listen(
      (List<PurchaseDetails> details) =>
          listenToPurchaseUpdate(purchaseDetails: details),
      cancelOnError: true,
      onError: (error) {
        Fluttertoast.showToast(
            msg:
                "We've got an error while trying to purchase the subscription,please try again later",
            gravity: ToastGravity.TOP);
      },
      onDone: () {
        subscription.cancel();
      },
    );
  }

  Future<void> purchase(ProductDetails product,
      {required BuildContext context}) async {
    Dialogs.materialDialog(
        color: Theme.of(context).colorScheme.background,
        context: context,
        lottieBuilder: LottieBuilder.asset("assets/animations/loading.json"),
        title: "Please Wait",
        msg: "Please wait, while we are trying to get the subscription",
        titleStyle: TextStyle(
            fontFamily: "Lato",
            fontSize: 18,
            color: Theme.of(context).colorScheme.inverseSurface,
            fontWeight: FontWeight.w800),
        msgStyle: TextStyle(
            fontFamily: "Lato",
            fontSize: 14,
            color: Theme.of(context).colorScheme.inverseSurface,
            fontWeight: FontWeight.w500),
        msgAlign: TextAlign.center);
    String email = await LocalDBKeys.email();
    await inAppPurchase.buyConsumable(
        purchaseParam:
            PurchaseParam(productDetails: product, applicationUserName: email));
    Timer(const Duration(seconds: 8), () => Navigator.pop(context));
  }

  void listenToPurchaseUpdate(
      {required List<PurchaseDetails> purchaseDetails}) {
    Logger logger = Logger();
    purchaseDetails.forEach((PurchaseDetails detail) async {
      logger.i(detail.status);
      if (detail.status == PurchaseStatus.purchased ||
          detail.status == PurchaseStatus.restored) {
        giveReward(detail);
      }
      if (detail.status == PurchaseStatus.error) {
        logger.e("We've got an error at :  $detail");
      }
      if (detail.pendingCompletePurchase) {
        await inAppPurchase.completePurchase(detail);
        logger.i("Pending purchase completed");
      }
    });
  }
```

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Flutter (Channel stable, 3.13.9, on macOS 14.1.1 23B81 darwin-x64, locale
    en-AE)
    • Flutter version 3.13.9 on channel stable at /Users/mac/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (4 weeks ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (3 available)
    • iPhone 15 Pro Max (mobile) • 9D4A8F8E-8F9E-49A5-84F6-CB8A0C0E1FF1 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • macOS 14.1.1 23B81 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 119.0.6045.159
    ! Error: Browsing on the local area network for Half’s iPhone. Ensure the
      device is unlocked and attached with a cable or associated with the same
      local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)
    ! Error: Browsing on the local area network for iPhone. Ensure the device is
      unlocked and attached with a cable or associated with the same local area
      network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by darshankawar** [comment]
Thanks for the report @iSaqibShafique 
Can you provide on which platform are you seeing this behavior ? (Android or iOS) ?

Also, since you are calling `InAppPurchase.instance.completePurchase` if `pendingCompletePurchase` is `true`,  after restoring purchase, do you still see `PurchaseDetails.pendingCompletePurchase` as `true` or ` false` ?

**Comment by siqin-shen** [comment]
I have the exact same problem, and I'm on iOS using SandBox, in_app_purchase: ^3.1.11. After the buyConsumable function called, purchaseDetails.status not being updated, and it kept showing the purchase sheet every 3-4 seconds.

And here's the screen record.
https://github.com/flutter/flutter/assets/61429718/4bfb14a3-f4e5-47ef-8c2e-0ab96cace567

and here's my code snippet.
```
CoinPurchases(this.firebaseNotifier, this.iapRepo) {
    final purchaseUpdated = iapConnection.purchaseStream;
    _subscription = purchaseUpdated.listen(
      _onPurchaseUpdate,
      onDone: _updateStreamOnDone,
      onError: _updateStreamOnError,
    );
    loadPurchases();
  }


  @override
  void dispose() {
    _subscription.cancel();
    super.dispose();
  }

  Future<void> loadPurchases() async {
    final available = await iapConnection.isAvailable();
    if (!available) {
      storeState = StoreState.notAvailable;
      notifyListeners();
      return;
    }
    const ids = <String>{
      coin100,
      // coin200,
      // coin500,
    };
    final response = await iapConnection.queryProductDetails(ids);
    for (var element in response.notFoundIDs) {
      debugPrint('Purchase $element not found');
    }
    products =
        response.productDetails.map((e) => PurchasableProduct(e)).toList();
    storeState = StoreState.available;
    notifyListeners();
  }

  Future<void> buy(PurchasableProduct product) async {
    final purchaseParam = PurchaseParam(productDetails: product.productDetails);

    switch (product.id) {
      case coin100:
        await iapConnection.buyConsumable(purchaseParam: purchaseParam);
        break;
      // case coin200:
      //   await iapConnection.buyConsumable(purchaseParam: purchaseParam);
      //   break;
      // case coin500:
      //   await iapConnection.buyConsumable(purchaseParam: purchaseParam);
      //   break;
      default:
        throw ArgumentError.value(
            product.productDetails, '${product.id} is not a known product');
    }
  }

  Future<void> _onPurchaseUpdate(
      List<PurchaseDetails> purchaseDetailsList) async {
    for (var purchaseDetails in purchaseDetailsList) {
      await _handlePurchase(purchaseDetails);
    }
    notifyListeners();
  }

  Future<void> _handlePurchase(PurchaseDetails purchaseDetails) async {
    if (purchaseDetails.status == PurchaseStatus.purchased) {
      var validPurchase = await _verifyPurchase(purchaseDetails);
      if (validPurchase) {
        switch (purchaseDetails.productID) {
          case coin100:
            await purchaseWinCoins(100, purchaseDetails.productID,
                purchaseDetails.purchaseID, firebaseNotifier.user?.uid);
            break;
          // case coin200:
          //   // await iapConnection.buyConsumable(purchaseParam: purchaseParam);
          //   break;
          // case coin500:
          //   // await iapConnection.buyConsumable(purchaseParam: purchaseParam);
          //   break;
        }
      } else {
        print("not verified");
      }
    } else if (purchaseDetails.status == PurchaseStatus.pending) {
    } else {
      print('this is purchase status not purchased ${purchaseDetails.status}');
    }

    if (purchaseDetails.pendingCompletePurchase) {
      await iapConnection.completePurchase(purchaseDetails);
    }
  }
```

**Comment by iSaqibShafique** [comment]
> Thanks for the report @iSaqibShafique 
> Can you provide on which platform are you seeing this behavior ? (Android or iOS) ?
> 
> Also, since you are calling `InAppPurchase.instance.completePurchase` if `pendingCompletePurchase` is `true`,  after restoring purchase, do you still see `PurchaseDetails.pendingCompletePurchase` as `true` or ` false` ?


Hello,
I'm experiencing this issue on both iPhone Simulator and physical devices. Additionally, I've identified another bug: when a user purchases a subscription and logs in with a different email ID (Firebase), upon navigating to the subscription page, the purchase is restored after 2 seconds, providing benefits to the user.

**Comment by darshankawar** [comment]
@iSaqibShafique 
Were you able to confirm below ?



> since you are calling `InAppPurchase.instance.completePurchase` if `pendingCompletePurchase` is `true`, after restoring purchase, do you still see `PurchaseDetails.pendingCompletePurchase` as `true` or ` false`



> I've identified another bug: when a user purchases a subscription and logs in with a different email ID (Firebase), upon navigating to the subscription page, the purchase is restored after 2 seconds, providing benefits to the user.

please file a new issue using issue template and fill out relevant details so that it can be addressed properly.

**Comment by Yodesoft** [comment]
Does anyone know how to solve this issue?

**Comment by iSaqibShafique** [comment]
> Does anyone know how to solve this issue?

Certainly • While encountering the issue on the iPhone Simulator, everything functions properly on an actual device.

**Comment by darshankawar** [comment]
> While encountering the issue on the iPhone Simulator, everything functions properly on an actual device.

@iSaqibShafique This most probably indicates it may not be an issue with the plugin but could be due to sandbox. I suggest you to reach out to apple support forum for further resolution.

**Comment by darshankawar** [comment]
> While encountering the issue on the iPhone Simulator, everything functions properly on an actual device.

@iSaqibShafique This most probably indicates it may not be an issue with the plugin but could be due to sandbox. I suggest you to reach out to apple support forum for further resolution.
