### ISSUE TITLE
No way to launch a sky app into a specific URL

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#139]
<a href="https://github.com/eseidelGoogle"><img src="https://avatars.githubusercontent.com/u/11857803?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [eseidelGoogle](https://github.com/eseidelGoogle)**
_Monday Aug 24, 2015 at 19:39 GMT_
_Originally opened as https://github.com/flutter/engine/issues/776_

----

Say I want to iterate on the settings page of my app.  How do I do that?

Ideally this would also work with the new 'listen' hotness.

@collinjackson @iansf

**Comment by abarth** [comment]
You can now do this with the `--route` option to `flutter start`.
