### ISSUE TITLE
FormatException: Unexpected character (at character 1) ... on Windows 10 Home Single Language Operating Systems

### ISSUE THREAD

**Issue by huseyinhamad** [flutter/flutter#139046]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

**Environment Information:**

Operating System: Windows 10 Home Single Language
Architecture: [x64 or x86]
Visual Studio: Build tried with both 2019 and 2022 version

**Observed Behavior:**
The application window opens but remains stuck on a white screen.

**Expected Behavior**
The application should launch successfully without getting stuck on a white screen, and no FormatException error should occur.

**Packages**
-   mobx: ^2.0.7+3
-   flutter_mobx: ^2.0.6+1
-   mobx_codegen: ^2.0.7
-   get_it: ^7.2.0
-   dio: ^5.3.3
-   logger: ^1.1.0
-   openid_client: ^0.4.6
-   url_launcher: ^6.1.3
-   shared_preferences: ^2.0.15
-   xxtea: ^2.1.0
-   sembast: ^3.2.0+1
-   path_provider: ^2.0.11
-   intl: ^0.18.0
-   connectivity_plus: ^4.0.1
-   lottie: ^2.0.0
-   flutter_form_builder: ^7.7.0
-   form_builder_validators: ^9.0.0
-   flutter_awesome_select: ^6.4.0
-   load: ^1.0.0
-   get: ^4.6.5
-   throttling: ^1.0.0
-   font_awesome_flutter: ^10.1.0
-   simple_gesture_detector: ^0.2.0
-   flutter_picker: ^2.0.4
-   flutter_bounceable: ^1.0.3
-   animations: ^2.0.3
-   introduction_screen: ^3.0.2
-   im_stepper: ^1.0.1+1
-   badges: ^3.0.2
-   flutter_svg: ^1.1.3
-   animate_do: ^3.0.2
-   timelines: ^0.1.0
-   flutter_keyboard_visibility: ^5.4.0
-   flutter_slidable: ^3.0.0
-   number_text_input_formatter: ^1.0.0+1
-   iconsax: ^0.0.8
-   window_manager: ^0.3.4
-   flutter_cupertino_datetime_picker: ^3.0.0
-   built_collection: ^5.1.1
-   dropdown_button2: ^2.1.3
-   printing: ^5.11.0
-   share_plus: ^7.0.2
-   path_provider_windows: ^2.1.3
-   file_picker: ^5.2.4
-   clipboard: ^0.1.3
-   shimmer: ^3.0.0
-   oauth2: ^2.0.1
-   uni_links: ^0.5.1
-   excel: ^2.0.1
-   dart_ipify: ^1.1.1
-   flutter_html: ^3.0.0-alpha.6
-   modal_bottom_sheet: ^3.0.0-pre
-   syncfusion_flutter_datagrid: ^20.4.49
-   syncfusion_flutter_core: ^20.4.49
-   flutter_native_splash: ^2.2.16
-   flutter_tawk: ^0.1.0
-   syncfusion_flutter_pdfviewer: ^20.4.53
-   webview_flutter: ^3.0.4
-   percent_indicator: ^4.2.3
-   credit_card_type_detector: ^2.0.0
-   carousel_slider: ^4.2.1
-   firebase_core: ^2.9.0
-   firebase_messaging: ^14.4.0
-   firebase_in_app_messaging: ^0.7.1
-   audioplayers: ^4.0.1
-   flutter_local_notifications: ^14.1.1
-   flutter_inappwebview: ^5.7.2+3
-   keyboard_name: ^0.0.1
-   device_info_plus: ^9.0.2
-   package_info_plus: ^4.0.2
-   in_app_purchase: ^3.1.7
-   settings_ui: ^2.0.2
-   accordion: ^2.5.1
-   flutter_html_to_pdf: ^0.7.0

**Notes**
This issue is specific to the Windows 10 Home Single Language environment.
No similar issues have been observed on other operating systems.

### Actual results

When attempting to launch the executable on Windows 10 Home Single Language, the application gets stuck on a white screen, and the following error is encountered:
```console
27-11-2023 10:34: FormatException: Unexpected character (at character 1)

                                                                           ...

^
```

### Logs

<details>
<summary>Logs</summary>

```console
27-11-2023 10:34: FormatException: Unexpected character (at character 1)

                                                                           ...

^
```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.9, on Microsoft Windows [Version 10.0.19045.3324], locale tr-TR)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2019 16.11.32)
[√] Android Studio (version 2022.3)
[√] IntelliJ IDEA Ultimate Edition (version 2022.3)
[√] VS Code (version 1.84.2)
[√] Connected device (3 available)
[√] Network resources
```

</details>

**Comment by darshankawar** [comment]
@huseyinhamad 
The package list you shared contains lot of third party libraries. If you create a new Flutter project and try to run, does it throw the same error as reported ?



> When attempting to launch the executable on Windows 10 Home Single Language,

Are you trying to double click the .exe or building using `flutter build windows` which gives you the said error ?

**Comment by darshankawar** [comment]
Is that the only error log you get or there's more ? If so, can you provide more details that will help to replicate locally ?
