### ISSUE TITLE
Document video player plugin's supported formats

### ISSUE THREAD

**Issue by xster** [flutter/flutter#13909]
Maybe a matrix on the plugin's readme for HLS, DASH, smooth streaming etc

**Comment by xster** [comment]
cc @mravn-google

**Comment by fukemy** [comment]
Hi.
I found flutter video_player based on AVPlayer in IOS, which does not support rtsp url. 
Can anyone help me know how to play a video with format like 'rstp/rtmp' in flutter? 🤔

**Comment by xster** [comment]
I'd assume there isn't an easy way to support it on iOS since the standard is slowly going away. I think the workaround would be to either have the RTSP converted to HLS remotely or create a separate plugin that uses a RTSP capable native player.

**Comment by Sfshaza** [comment]
Here's the README we'd like updated:  https://pub.dartlang.org/packages/video_player#-readme-tab-

I'm removing the website tag. Do we need to add a docs-pub.dartlang tag?

**Comment by paayao** [comment]
> Hi.
> I found flutter video_player based on AVPlayer in IOS, which does not support rtsp url.
> Can anyone help me know how to play a video with format like 'rstp/rtmp' in flutter? 🤔

Having the same issue with flutter on android, help me if  you were able to solve it. thank you

**Comment by fukemy** [comment]
no sir, still have to code navite framework event i love flutter. you can dream for a long time to get ijkplayer work in flutter

**Comment by paayao** [comment]
> no sir, still have to code navite framework event i love flutter. you can dream for a long time to get ijkplayer work in flutter

Thank you.

**Comment by zoechi** [comment]
#22937 is about RTMP support

**Comment by fukemy** [comment]
i still recommend ijkplayer ( based on ffmpeg) because it's can play all format video, even Avplayer(IOS) and ExoPlayer(Android) does not support. Hope it's available on flutter in some day

**Comment by zoechi** [comment]
I found

- iOS https://developer.apple.com/documentation/avfoundation/avfiletype should be supported
- Android https://google.github.io/ExoPlayer/supported-formats.html

**Comment by paysen-z** [comment]
> i still recommend ijkplayer ( based on ffmpeg) because it's can play all format video, even Avplayer(IOS) and ExoPlayer(Android) does not support. Hope it's available on flutter in some day

hi,does it work? And how to use with ijkplayer?

**Comment by iskakaushik** [comment]
Fixed by https://github.com/flutter/plugins/pull/1214
