### ISSUE TITLE
Add `TimeOfDay` compareTo() function

### ISSUE THREAD

**Issue by subzero911** [flutter/flutter#139098]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Unlike DateTime, TimeOfDay does not have compareTo() method.
In order to compare 2 TimeOfDay objects, you have to use this awkward way:

1) Create a helper extension:
```dart
extension TimeOfDayExt on TimeOfDay {
  /// note: 'hour' is in 24-hour format
  double toDouble() => hour + minute/60.0;
}
```

2) Convert both TimeOfDay's to double:
```dart
    final double nowTime = TimeOfDay.now().toDouble();
    final double deadlineTime = TimeOfDay.fromDateTime(deadline).toDouble();
```

3) Compare these doubles:
```dart
if (nowTime >= deadlineTime) {
    // you're fired
}
```

### Proposal

Add a compareTo() method for `TimeOfDay`, so we can compare them directly.

**Comment by HansMuller** [comment]
CC @MitchellGoodwin

**Comment by subzero911** [comment]
We considering time separate from a date.
The `TimeOfDay` values are ordered from 00:00 to 23:59, then start over. So 00:00 is definitely less than 23:59.
"The 00:00 of the next day after 23:59" is required to be handled by user.

**Comment by mateusfccp** [comment]
We don't need to convert it to double. We could simply delegate to the internal components' `compareTo` methods.

```dart
int compareTo(TimeOfDay other) {
  final hourComparison = hour.compareTo(other.hour);
  return hourComparison == 0 ? minute.compareTo(other.minute) : hourComparison;
}
```

**Comment by subzero911** [comment]
Oh, that's a great idea! I completely forgot that a `num` type has a `compareTo()` too.
So we have a strategy now and I see no obstacles to its implementation.

**Comment by NobodyForNothing** [comment]
Has this come to a conclusion? I recently came across this issue myself and would like to make a PR.

**Comment by mateusfccp** [comment]
> Has this come to a conclusion? I recently came across this issue myself and would like to make a PR.

You may open a PR. If it's going to be accepted or not is another history.

If you do, try to be as non-breaking as possible. Adding methods to an API of a non-final class is breaking.

**Comment by mateusfccp** [comment]
This may be closed.
