### ISSUE TITLE
Investigate why MS Visual studio has problems with initializer list in closure.

### ISSUE THREAD

**Issue by aam** [flutter/flutter#13908]
https://github.com/flutter/engine/pull/4514 contains the workaround, the root cause is not clear.

**Comment by aam** [comment]
cc @bkonyi

**Comment by bkonyi** [comment]
This is an MS bug, but I can't remember where I saw it... here's a SO question with the same issue and a broken link to MS support: https://stackoverflow.com/questions/39147294/lambda-capture-by-move-fails-for-const-variables

**Comment by aam** [comment]
@bkonyi wrote:

> This is an MS bug

What is the bug, do you know? Is it handling of const references in the std::move?

**Comment by aam** [comment]
I think https://stackoverflow.com/questions/28595117/why-can-we-use-stdmove-on-a-const-object is actually relevant here.

**Comment by bkonyi** [comment]
Hm, honestly, I can't remember if I found a filed issue (there was a few oddities like this that I came across when getting `flutter test` running). I'll look around to see if I can find an issue.

**Comment by markusaksli-nc** [comment]
Is this still a relevant issue?

**Comment by jonahwilliams** [comment]
Closing as no longer relevant
