### ISSUE TITLE
The argument type 'Object' can't be assigned to the parameter type 'ImageProvider<Object>'

### ISSUE THREAD

**Issue by ikramakro** [flutter/flutter#139003]
I am using flutter Channel stable, 3.13.9, flutter version
<img width="723" alt="flutter issue " src="https://github.com/flutter/flutter/assets/88956494/500e1b48-e35a-4a4c-afe0-700485475006">
<img width="607" alt="flutter doctor" src="https://github.com/flutter/flutter/assets/88956494/6360890a-a6ce-426d-8dfa-545454ab5d87">

**Comment by Rafik-Belkadi** [comment]
don't forget to put `:` for your ternary condition

which you have to move up, you can't put that there

**Comment by Rafik-Belkadi** [comment]
Should be closed

**Comment by ikramakro** [comment]
i put the ternary operator is you see in the below image  
<img width="809" alt="f" src="https://github.com/flutter/flutter/assets/88956494/0cfb40c0-4fbe-4774-b963-aa4191e36fad">

**Comment by ikramakro** [comment]
@Rafik-Belkadi

**Comment by roohaani786** [comment]
Hi @ikramakro  This is a known issue [](https://github.com/flutter/flutter/issues/77782) And can be solved by casting your AssetImage as ImageProvider.

` image: index == 0 ? NetworkImage("url"):AssetImage("assetName") as ImageProvider,`

**Comment by darshankawar** [comment]
@ikramakro 
Above should be able to resolve your issue which has solution on how to solve it. Based on it, closing this issue. If you disagree, write in comments and I'll reopen it.
