### ISSUE TITLE
Flutter currently support win32 archtecture add support for 64 architecture when deploying windows app

### ISSUE THREAD

**Issue by alihassan143** [flutter/flutter#139042]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

i am uploading app to the windows store it showing the warning message 

### Proposal

<img width="1044" alt="Screenshot 2023-11-27 at 11 41 06 AM" src="https://github.com/flutter/flutter/assets/71745182/117c3ee0-971f-45d8-8684-64744fad665e">
add support for 64 architecture

**Comment by darshankawar** [comment]
@alihassan143 
Can you check if your issue is same as https://github.com/flutter/flutter/issues/53120 ?

**Comment by alihassan143** [comment]
@darshankawar I don't have an issue related to installation i created a windows app and created an msix but the Microsoft store complaining that my app supports arch32 is flutter windows apps support arch64?

**Comment by darshankawar** [comment]
this might be it then https://github.com/flutter/flutter/issues/62597

**Comment by alihassan143** [comment]
yes that it

**Comment by darshankawar** [comment]
Closing as duplicate.
