### ISSUE TITLE
cloud_firestore crashes on failed Query

### ISSUE THREAD

**Issue by Skylled** [flutter/flutter#13904]
Example: 
```dart
Firestore.instance.collection("jobs")
         .where("location", isEqualTo: locationReference)
         .orderBy("datetime")
```

When using a complex query with multiple fields checked, as above, the underlying library will kick back with the below error, if an Index has not been created in the Firebase Console.
```I/System.out(32065): com.google.firebase.firestore.FirebaseFirestoreException: FAILED_PRECONDITION: The query requires an index. You can create it here: [link omitted]```

But because errors are not caught, only printed to system.out, it leads to more problems down the line followed by a hard crash:

```
D/AndroidRuntime(32065): Shutting down VM
E/AndroidRuntime(32065): FATAL EXCEPTION: main
E/AndroidRuntime(32065): java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.google.firebase.firestore.QuerySnapshot.getDocuments()' on a null object reference
E/AndroidRuntime(32065): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$EventObserver.onEvent(CloudFirestorePlugin.java:140)
E/AndroidRuntime(32065): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$EventObserver.onEvent(CloudFirestorePlugin.java:122)
E/AndroidRuntime(32065): 	at com.google.firebase.firestore.zzi.onEvent(Unknown Source)
```

**Comment by Arno-Z** [comment]
That is supposed to happen, according to Firebase. Same behaviour in the web SDK. Follow the link in the log file to create the index.

**Comment by Skylled** [comment]
I agree that the lack of index is supposed to cause a problem, but it shouldn't hard crash the app. The error should be handled and reported.

**Comment by Hixie** [comment]
cc @collinjackson

**Comment by ened** [comment]
Can confirm Firestore does not crash anymore in case of a missing index. There is clear error description in the logs.

I would, however, expect the AsyncSnapshot to have the error field clearly set.

Sample code:

```
StreamBuilder<QuerySnapshot>(
  stream: state.myQuery,
  builder: (BuildContext context, AsyncSnapshot<QuerySnapshot> snapshot) {
    if (snapshot.hasError) {
      return Text('Error: ${snapshot.error}');
    }
    print('snapshot: ${snapshot.connectionState}');
    switch (snapshot.connectionState) {
      case ConnectionState.done:
      case ConnectionState.waiting:
        return Container(
          child: const Center(child: CircularProgressIndicator()),
        );

      default:
        if (snapshot.data.documents.isEmpty) {
          return _buildEmptyPage();
        }

        return _buildListView(snapshot, context);
    }
  },
),
```

`snapshot.error` & `snapshot.hasErro` really should be set in that case.

**Comment by kroikie** [comment]
@Skylled

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/918. Any further collaboration will be done there.
