### ISSUE TITLE
How to debug "Multiple widgets used the same GlobalKey"?

### ISSUE THREAD

**Issue by pedia** [flutter/flutter#13902]
How to debug "Multiple widgets used the same GlobalKey"?

What output after press 'W' in the console, should more helpful for this?

## Logs

Another exception was thrown: Child with id 134 is invisible and should not be added to tree.
Another exception was thrown: Child with id 134 is invisible and should not be added to tree.
Another exception was thrown: Child with id 134 is invisible and should not be added to tree.
Another exception was thrown: Multiple widgets used the same GlobalKey.
Another exception was thrown: Duplicate GlobalKey detected in widget tree.

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.13.2 17C88, locale en-HK, channel master)
    • Flutter at /Users/-/wa/flutter/flutter
    • Framework revision 598c0427a1 (33 hours ago), 2018-01-02 16:29:00 -0800
    • Engine revision 0a93f9ffbf
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.e122f4825726035e4579471ef83848b1aa796444

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.3)
    • Android SDK at /Users/-/Library/Android/sdk
    • Android NDK at /Users/-/Library/Android/sdk/ndk-bundle
    • Platform android-26, build-tools 26.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.3)
    • Flutter plugin version 20.0.3
    • Dart plugin version 173.3727.108

**Comment by Hixie** [comment]
If it says "Another exception was thrown" that means you've had another exception report earlier. If you can resolve that issue, then eventually you'll have the "Multiple widgets used the same GlobalKey" exception be your first exception, and that will include a bunch of additional information in the logs about what widgets are in trouble and what keys they have.

**Comment by pedia** [comment]
OK, I close this first.

**Comment by 4fox4** [comment]
I had the same problem. First of all, try a full reload of the app.
Hot reload updates only part of the tree

**Comment by leslieharland** [comment]
Check whether there is an Expanded inside the Column widget

**Comment by SurrealShock** [comment]
Why would it matter if there is an expanded within the column widget?
