### ISSUE TITLE
Flutter can't find android studio

### ISSUE THREAD

**Issue by ArthurRbn** [flutter/flutter#139000]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

My configuration:
- Ubuntu 22.04.3 LTS
- Flutter installed via snap (Flutter (Channel stable, 3.16.0, on Ubuntu 22.04.3 LTS 6.2.0-37-generic, locale en_US.UTF-8))
- Android studio installed from jetbrains toolbox (Android Studio Giraffe 2022.3.1 Patch 4)
- SDK: Android 14.0 "UpsideDownCake" API Level 34 Revision 2
- AvdId Pixel_3a_API_34_extension_level_7_x86_64

I want to be able to run `flutter run -d {android device}` with my simulated phone as the target.

I have also configured flutter like so:
`flutter config --android-sdk="$HOME/Android/Sdk"`
`flutter config --android-studio-dir="/home/arthur/.local/share/JetBrains/Toolbox/apps/android-studio"`

The command `flutter devices` returns this:
Found 2 connected devices:
  Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.3 LTS 6.2.0-37-generic
  Chrome (web)    • chrome • web-javascript • Google Chrome 119.0.6045.159

The commands `flutter emulators` and `flutter emulators --create` return this:
Unable to find any emulator sources. Please ensure you have some
Android AVD images available.

### Actual results

Currently flutter doctor doesn't detect android on my desktop as the android toolchain isn't displayed in flutter doctor.
I am unable to run my flutter app with my android simulated phone as the target and I don't find any other solution on internet to fix this configuration problem.

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.0, on Ubuntu 22.04.3 LTS 6.2.0-37-generic, locale en_US.UTF-8)
    • Flutter version 3.16.0 on channel stable at /home/arthur/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (10 days ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
    • IntelliJ at /snap/intellij-idea-ultimate/462
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version unknown)
    • VS Code at /snap/code/current
    • Flutter extension version 3.76.0
    ✗ Unable to determine VS Code version.

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.3 LTS 6.2.0-37-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 119.0.6045.159

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by bartekpacia** [comment]
> Unable to find any emulator sources. Please ensure you have some
Android AVD images available.

Try installing AVD images:

```
sdkmanager --install 'system-images;android-34;google_apis;x86_64'
```

The `sdkmanager` binary should be in `$HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager`.

**Comment by ArthurRbn** [comment]
I was in fact missing the sdkmanager. I installed it via Android studio and ran you command without problem. That said, `flutter doctor -v` output hasn't changed and there is no mention of android toolchain in it. What I have trouble to understand is that most people still have android toolchain showing up in the flutter doctor output even when they have installation problems. For me it's like flutter is completely ignoring it.
Also `flutter emulators` and `flutter emulators --create` output is still the same:
```console
Unable to find any emulator sources. Please ensure you have some
Android AVD images available
```

**Comment by bartekpacia** [comment]
I think you have Android SDK set up incorrectly. Do you have `ANDROID_HOME` env var set? Android Studio isn't really needed for Android development, all you need for `flutter build apk` and `flutter run` is to have Android command line tools.

E.g. [here is how](https://github.com/bartekpacia/dotfiles/blob/1f7678e8dcafc370eb40de8d0232c82c09fa7b61/dot/shrc#L39-L58) I configure Android SDK in my shell startup file. You likely have Android SDK at different location than `~/androidsdk`, but that's the only change you'd have to make. It should help.

**Comment by bartekpacia** [comment]
I also wrote a blog post on how to configure Android SDK "the right way" (IMHO), you might find it helpful: https://garden.pacia.tech/suckless-androidsdk-setup.html

**Comment by huycozy** [comment]
>I also wrote a blog post on how to configure Android SDK "the right way" (IMHO), you might find it helpful: https://garden.pacia.tech/suckless-androidsdk-setup

Great article, I think you could share it here as well: https://github.com/flutter/flutter/issues/71368

**Comment by ArthurRbn** [comment]
Hi !

Thank you again for you answers, I will try @bartekpacia 's shell startup file and if it doesn't work I will try his blog post about how to setup Android SDK properly. Will update soon.

Here is my output of `flutter emulators -v`:
```console
[  +27 ms] executing: uname -m
[   +4 ms] Exit code 0 from: uname -m
[        ] x86_64
[+1974 ms] 
                    ┌─────────────────────────────────────────────────────────┐
                    │ A new version of Flutter is available!                  │
                    │                                                         │
                    │ To update to the latest version, run "flutter upgrade". │
                    └─────────────────────────────────────────────────────────┘
                    
[+2033 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[   +6 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'LegacyCanvasKitRemover' is not required,
skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[  +75 ms] Artifact Instance of 'MaterialFonts' is not required, skipping
update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping
update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping
update.
[  +48 ms] "flutter emulators" took 162ms.
[   +3 ms] Unable to find any emulator sources. Please ensure you have some
           Android AVD images available.
[   +2 ms] 
           #0      throwToolExit
(package:flutter_tools/src/base/common.dart:10:3)
           #1      EmulatorsCommand.runCommand
           (package:flutter_tools/src/commands/emulators.dart:43:7)
           #2      FlutterCommand.verifyThenRunCommand
           (package:flutter_tools/src/runner/flutter_command.dart:1662:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1350:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand
(package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure>
           (package:flutter_tools/runner.dart:112:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[ +148 ms] ensureAnalyticsSent: 132ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

**Comment by huycozy** [comment]
@ArthurRbn I see you are using Flutter which is installed through snap (it could be the cause, please see an old related issue https://github.com/flutter/flutter/issues/74538). You can try using Flutter installation manually to see if it works.

**Comment by ArthurRbn** [comment]
Hi @huycozy, it worked !

I spent last night installing tools, exporting environment variables, upgrading my java version etc... Nothing changed.
Today I just reinstalled flutter manually and it worked instantly. Flutter doctor tells me that the android toolchain is correctly setup and it detects my emulators. When I start my emulator it is correctly listed in the devices and I can run my app with `flutter run -d emulator-5554`.

If this can help anyone I installed flutter manually like described [here](https://docs.flutter.dev/get-started/install/linux) and this is my `~.bashrc`:
```bash
export ANDROID_HOME="/home/${USER}/Android/Sdk"
export PATH="bin:$PATH:$ANDROID_STUDIO/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/emulator:/home/${USER}/flutter/bin"
```

Thank you guys for helping me !

**Comment by huycozy** [comment]
Glad it helps. You can file an issue on their dedicated Github [repository](https://github.com/canonical/flutter-snap/issues) if you persist with flutter from snap. 

Also, I just found this [issue](https://github.com/canonical/flutter-snap/issues/16), a user there solved it with AS path from snap. So I think this issue may be also solved if you install AS from snap as well (not from Toolbox)
