### ISSUE TITLE
[FATAL:flutter/shell/platform/android/platform_view_android.cc(114)] Check failed: android_context_->IsValid(). Could not create surface from invalid Android context.

### ISSUE THREAD

**Issue by yann-q-20230331** [flutter/flutter#139043]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

The crashes occurrence  about 200 times per day. According to logs, it happens when construct FlutterEngine. 
flutter version: 3.7.5
<img width="1507" alt="image" src="https://github.com/flutter/flutter/assets/129529240/806d2764-17c2-40a9-bac8-270e3ffdea9d">

### Expected results

no crash

### Actual results

<img width="1494" alt="image" src="https://github.com/flutter/flutter/assets/129529240/8d246a33-d106-414b-9ee5-79aa01034d31">
<img width="1227" alt="image" src="https://github.com/flutter/flutter/assets/129529240/b9782420-bfbc-4a8e-a561-9c3c39aee6ab">

### Code sample

```
 val flutterEngine = FlutterEngine(appContext, null, false).apply {
            plugins.removeAll()
        }
        flutterEngine.getNavigationChannel().setInitialRoute(skylinf)
        flutterEngine.dartExecutor.executeDartEntrypoint(
                DartExecutor.DartEntrypoint.createDefault()
       )
```

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>
<img width="1196" alt="截屏2023-11-24 17 40 14" src="https://github.com/flutter/flutter/assets/129529240/93927d9a-eec3-4348-b629-0dcd01db8808">

### Logs

```
[FATAL:flutter/shell/platform/android/platform_view_android.cc(114)] Check failed: android_context_->IsValid(). Could not create surface from invalid Android context.
backtrace:
  #00  pc 0x000000000008cc74  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164)
  #01  pc 0x0000000000322f14  /data/app/~~bJcSlGkrhtKuuvBKJZ_-EQ==/com.binance.dev-oWo875fNX5HEFr-MXKMRtg==/lib/arm64/libflutter.so (BuildId: 028a6106106c47417a30c3938d08947a1e8ed0ef)
  #02  pc 0x000000000034bf58  /data/app/~~bJcSlGkrhtKuuvBKJZ_-EQ==/com.binance.dev-oWo875fNX5HEFr-MXKMRtg==/lib/arm64/libflutter.so (BuildId: 028a6106106c47417a30c3938d08947a1e8ed0ef)
  #03  pc 0x0000000000335880  /data/app/~~bJcSlGkrhtKuuvBKJZ_-EQ==/com.binance.dev-oWo875fNX5HEFr-MXKMRtg==/lib/arm64/libflutter.so (BuildId: 028a6106106c47417a30c3938d08947a1e8ed0ef)
  #04  pc 0x000000000032decc  /data/app/~~bJcSlGkrhtKuuvBKJZ_-EQ==/com.binance.dev-oWo875fNX5HEFr-MXKMRtg==/lib/arm64/libflutter.so (BuildId: 028a6106106c47417a30c3938d08947a1e8ed0ef)
  #05  pc 0x00000000005af6d8  /data/app/~~bJcSlGkrhtKuuvBKJZ_-EQ==/com.binance.dev-oWo875fNX5HEFr-MXKMRtg==/lib/arm64/libflutter.so (BuildId: 028a6106106c47417a30c3938d08947a1e8ed0ef)
  #06  pc 0x00000000005aec40  /data/app/~~bJcSlGkrhtKuuvBKJZ_-EQ==/com.binance.dev-oWo875fNX5HEFr-MXKMRtg==/lib/arm64/libflutter.so (BuildId: 028a6106106c47417a30c3938d08947a1e8ed0ef)
  #07  pc 0x00000000005ae2f0  /data/app/~~bJcSlGkrhtKuuvBKJZ_-EQ==/com.binance.dev-oWo875fNX5HEFr-MXKMRtg==/lib/arm64/libflutter.so (BuildId: 028a6106106c47417a30c3938d08947a1e8ed0ef)
  #08  pc 0x0000000000336f70  /data/app/~~bJcSlGkrhtKuuvBKJZ_-EQ==/com.binance.dev-oWo875fNX5HEFr-MXKMRtg==/lib/arm64/libflutter.so (BuildId: 028a6106106c47417a30c3938d08947a1e8ed0ef)
  #09  pc 0x00000000007e38d0  /data/app/~~bJcSlGkrhtKuuvBKJZ_-EQ==/com.binance.dev-oWo875fNX5HEFr-MXKMRtg==/oat/arm64/base.odex (art_jni_trampoline+128)
  #10  pc 0x00000000022b8ea4  /data/app/~~bJcSlGkrhtKuuvBKJZ_-EQ==/com.binance.dev-oWo875fNX5HEFr-MXKMRtg==/oat/arm64/base.odex (io.flutter.embedding.engine.FlutterJNI.performNativeAttach+52)
  #11  pc 0x00000000022b7da8  /data/app/~~bJcSlGkrhtKuuvBKJZ_-EQ==/com.binance.dev-oWo875fNX5HEFr-MXKMRtg==/oat/arm64/base.odex (io.flutter.embedding.engine.FlutterJNI.attachToNative+152)
  #12  pc 0x00000000009a4150  /data/app/~~bJcSlGkrhtKuuvBKJZ_-EQ==/com.binance.dev-oWo875fNX5HEFr-MXKMRtg==/oat/arm64/base.odex (io.flutter.embedding.engine.FlutterEngine.<init>+5056)
```

### Flutter Doctor output

[!] Flutter (Channel unknown, 3.7.5, on macOS 13.5.2 22G91 darwin-arm64, locale zh-Hans-CN)
    ! Flutter version 3.7.5 on channel unknown at /Users/user/.flutter_wrapper/3.7.5
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    • Framework revision c07f788888 (9 months ago), 2023-02-22 17:52:33 -0600
    • Engine revision 0f359063c4
    • Dart version 2.19.2
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

**Comment by darshankawar** [comment]
@yann-q-20230331 
The flutter version you are on, is old. Current is 3.16. I suggest you to upgrade to latest and run your scenario again to check if you still get the same crash or not. That way, we can properly address the issue.

**Comment by yann-q-20230331** [comment]
> @yann-q-20230331 The flutter version you are on, is old. Current is 3.16. I suggest you to upgrade to latest and run your scenario again to check if you still get the same crash or not. That way, we can properly address the issue.

Thanks for your reply, i will try and confirm later.

**Comment by yann-q-20230331** [comment]
@darshankawar  we can't upload flutter version quickly because of many compline pub upgrade. So we'd like to find a way to work for this crash. I  look up flutter engine(https://github.com/flutter/engine) code in branch flutter-3.7-candidate.5. I find these code.Maybe this crash happens in 114 row
<img width="879" alt="image" src="https://github.com/flutter/flutter/assets/129529240/8a73f5cc-fb2f-4410-b421-c541f7ac3300">

**Comment by yann-q-20230331** [comment]
I address this logic why function android_context_->IsValid() is false. I find in class AndroidContext or AndroidContextGLImpeller class, isValid() function always return true, so the only reason is in AndroidContextGLSkia class
<img width="776" alt="image" src="https://github.com/flutter/flutter/assets/129529240/7bd3756c-29c6-451b-82c1-9aeb6673eeae">

**Comment by yann-q-20230331** [comment]
in android_context_gl_skia.cc, i find these codes.

bool AndroidContextGLSkia::IsValid() const {
  return valid_;
}
AndroidContextGLSkia::AndroidContextGLSkia(
    AndroidRenderingAPI rendering_api,
    fml::RefPtr<AndroidEnvironmentGL> environment,
    const TaskRunners& task_runners,
    uint8_t msaa_samples)
    : AndroidContext(AndroidRenderingAPI::kOpenGLES),
      environment_(std::move(environment)),
      config_(nullptr),
      task_runners_(task_runners) {
  if (!environment_->IsValid()) {
    FML_LOG(ERROR) << "Could not create an Android GL environment.";
    return;
  }

  bool success = false;

  // Choose a valid configuration.
  std::tie(success, config_) =
      ChooseEGLConfiguration(environment_->Display(), msaa_samples);
  if (!success) {
    FML_LOG(ERROR) << "Could not choose an EGL configuration.";
    LogLastEGLError();
    return;
  }

  // Create a context for the configuration.
  std::tie(success, context_) =
      CreateContext(environment_->Display(), config_, EGL_NO_CONTEXT);
  if (!success) {
    FML_LOG(ERROR) << "Could not create an EGL context";
    LogLastEGLError();
    return;
  }

  std::tie(success, resource_context_) =
      CreateContext(environment_->Display(), config_, context_);
  if (!success) {
    FML_LOG(ERROR) << "Could not create an EGL resource context";
    LogLastEGLError();
    return;
  }

  // All done!
  valid_ = true;
}
So maybe run code in function AndroidContextGLSkia construct something wrong, it leads valid_ is still wrong. i have no idea. can you give me some advice. look forward to your replay. thanks. @darshankawar

**Comment by darshankawar** [comment]
Thanks for the update @yann-q-20230331 
If you could provide us a minimal reproducible code sample that we can directly use and run that shows the reported error, would be helpful to properly address the issue. You may also create a sample repo that we can clone.

**Comment by yann-q-20230331** [comment]
fun createNewEngine(appContext: Context) : FlutterEngine {
        val flutterEngine = FlutterEngine(appContext, null, false).apply {
            plugins.removeAll()
        }
        flutterEngine.getNavigationChannel().setInitialRoute(skylinf)
        flutterEngine.dartExecutor.executeDartEntrypoint(
                DartExecutor.DartEntrypoint.createDefault()
        )
        flutterEngine.plugins.add(SharedPreferencesPlugin())
        flutterEngine.plugins.add(DeviceInfoPlugin())
        // Cache the FlutterEngine to be used by FlutterActivity.
        return flutterEngine
    }  we only construct flutterEngine when fragment onViewCreate, this crash occurs occasional and i have no way to reproduce it  frequently

**Comment by darshankawar** [comment]
Thanks for the update @yann-q-20230331 
Check if [this](https://github.com/flutter/flutter/issues/137639#issuecomment-1800107909) helps in your case or not ?

**Comment by yann-q-20230331** [comment]
@darshankawar  i see the issue(https://github.com/flutter/flutter/issues/137639#issuecomment-1800107909)  has been closed and i can't see any resolution. Can you give me another idea. Thanks

**Comment by darshankawar** [comment]
@yann-q-20230331 Thanks for your patience. I see that the above linked issue was closed in favor of https://github.com/flutter/flutter/issues/139702 which is still open, so I think under the hood you might be hitting the same behavior as mentioned in that issue which you can check and confirm.
