### ISSUE TITLE
widget shake when hiding the system navigation bar

### ISSUE THREAD

**Issue by zhujiageng** [flutter/flutter#139022]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. set android device's navigation type to 'Buttons'
2. run the sample code
3. click 'Hide System Overlays' button

### Expected results

button should remain unchanged, without any shaking

### Actual results

the button shaked

### Code sample

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Container(
          alignment: Alignment.topCenter,
          padding: const EdgeInsets.only(top: 100),
          child: ElevatedButton(
            onPressed: () {
              SystemChrome.setEnabledSystemUIMode(
                SystemUiMode.manual,
                overlays: [],
              );
            },
            child: const Text(
              'Hide System Overlays',
              style: TextStyle(fontSize: 60),
            ),
          ),
        ),
      ),
    );
  }
}

```

### Screenshots or Video

https://github.com/flutter/flutter/assets/103102265/dfad971b-0aad-46fd-824a-64eef992697d

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.16.0, on macOS 14.1.1 23B81 darwin-arm64, locale zh-Hans-CN)

**Comment by moffatman** [comment]
What device is this on? I have seen it on a few MIUI devices. There isn't much good news here in my experience...

**Comment by zhujiageng** [comment]
@moffatman the device is Galaxy Tab S8.

**Comment by zhujiageng** [comment]
@moffatman 
Is this related to the implementation principle of Flutter? I speculate that the drawable area of Flutter has become larger, and then the entire Flutter canvas is stretched like an image, and then it quickly adapts to the new area correctly?

**Comment by zhujiageng** [comment]
I don't know what the differences are in the implementation of Flutter on Android and Windows. I remember that when resizing the window on Windows, there is no such shaking phenomenon.

**Comment by moffatman** [comment]
Yes you're right about drawable area. Ideally the system shall keep the drawable area the same and adjust the edge padding hints. You might be able to fix it by tweaking the exact argument for showing and hiding bars. To keep the bars as transparent while shown, so the drawable area is always the full screen.

**Comment by zhujiageng** [comment]
@moffatman I've tried it, and the issue is not resolved. You can also try it yourself; this is the code I modified.

``` dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      systemNavigationBarColor: Colors.transparent,
    ),
  );
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Container(
          alignment: Alignment.topCenter,
          padding: const EdgeInsets.only(top: 100),
          child: ElevatedButton(
            onPressed: () {
              SystemChrome.setEnabledSystemUIMode(
                SystemUiMode.manual,
                overlays: [],
              );
            },
            child: const Text(
              'Hide System Overlays',
              style: TextStyle(fontSize: 60),
            ),
          ),
        ),
      ),
    );
  }
}

```

**Comment by moffatman** [comment]
Need to use alternative systemoverlaymode such as lean back instead of manual

**Comment by zhujiageng** [comment]
@moffatman I've noticed an interesting phenomenon: the first time I use "leanBack," it shaked, but after that, when entering this mode again, it doesn't shake.

**Comment by zhujiageng** [comment]
@moffatman The behavior of "immersive" and "leanBack" is the same. When first activated, there button shaked, but later, if you bring back the navigation bar using system gestures and then activate "immersive" or "leanBack," button doesn't shake.

**Comment by moffatman** [comment]
Maybe you need some method call to set mode to edgeToEdge upon app launch?

**Comment by zhujiageng** [comment]
@moffatman great! the problem is solved, thank you very much.

**Comment by moffatman** [comment]
Don't go back to manual. Just go back to edgeToEdge.
