### ISSUE TITLE
[CP] Fix not being able to hide iOS status bar via setEnabledSystemUIMode

### ISSUE THREAD

**Issue by LinXunFeng** [flutter/flutter#139069]
### Issue Link

https://github.com/flutter/flutter/issues/138604
https://github.com/flutter/flutter/issues/138671

### Commit Hash

bec0dacaae

### Target

stable

### PR Link

https://github.com/flutter/engine/pull/48403

### Changelog Description

Fix not being able to hide iOS status bar via setEnabledSystemUIMode

### Impacted Users

iOS Developers

### Impact Description

When the `UIViewControllerBasedStatusBarAppearance`  is false in the Info.plist, the status bar cannot be hidden through `SystemChrome.setEnabledSystemUIMode`, and statusBarBrightness cannot be set through systemOverlayUI.

### Workaround

No

### Risk

low

### Test Coverage

yes

**Comment by CaseyHillers** [comment]
@stuartmorgan can you review this CP request? If it looks good to you, add the "cp: approved" label.

**Comment by LinXunFeng** [comment]
It's done, thanks everyone

**Comment by csandovalgt** [comment]
@LinXunFeng hi! is this released in flutter 3.16.2?

**Comment by Liloupar** [comment]
Is this included in version 3.16.3? I didn't see it mentioned in the update log.
@LinXunFeng
