### ISSUE TITLE
ci.yaml validation is stuck

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#139087]
### Is there an existing issue for this?

- [X] I have searched the [existing infra issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-infra)

### Type of Request

bug

### Infrastructure Environment

Github

### What is happening?

The ci.yaml validation Github check has been "Waiting for status to be reported" for more than 20 minutes in multiple PRs:
https://github.com/flutter/packages/pull/5494
https://github.com/flutter/engine/pull/48418
https://github.com/flutter/flutter/pull/139083

### Expected results

I expect it to pass quickly

**Comment by sealesj** [comment]
I'm seeing that the checks recently completed but took around ~40 minutes until reporting status as successful

**Comment by vashworth** [comment]
I just saw this: https://www.githubstatus.com/incidents/66vhjmd266r9, probably related? Feel free to close

**Comment by sealesj** [comment]
Yes, likely related. I'll close but send a PSA since this is a significant amount of delay
