### ISSUE TITLE
Flutter ios app is not running (Error (Xcode): Undefined symbols)

### ISSUE THREAD

**Issue by AlqallafAli** [flutter/flutter#139024]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I have been trying to run my app for a long time, and I have tried many things but I could not run it. I have tried to update some packages, run older versions of the app, update Flutter SDK, and update Xcode and my MacOS but nothing really worked. I have also tried
```
flutter clean
rm -rf Pods Podfile.lock
pod repo update
pod deintegrate
pod update
rm -rf ~/Library/Developer/Xcode/DerivedData/
pod deintegrate
pod install 
```
 but nothing worked for me.

### Actual results

This is the error I am getting.
```
Launching lib/main.dart on iPhone 15 Pro in debug mode...
Running pod install...                                             56.5s
Running Xcode build...                                                 ⠉ 
 └─Compiling, linking and signing...                        25.3s
Xcode build done.                                           405.1s
Failed to build iOS app
Error (Xcode): Undefined symbols:


Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

Could not build the application for the simulator.
Error launching application on iPhone 15 Pro.
```

### Logs

<details>
<summary>Logs</summary>

this is the error with flutter run -v

```console

[ +120 ms] Failed to build iOS app
[   +2 ms] Error (Xcode): Undefined symbols:
           
[   +2 ms] Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)
           
[   +4 ms] Could not build the application for the simulator.
[        ] Error launching application on iPhone 15 Pro.
[   +3 ms] "flutter run" took 378,969ms.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:752:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1350:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[   +7 ms] Running 1 shutdown hook
[  +10 ms] Shutdown hooks complete
[        ] exiting with code 1

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.0, on macOS 13.6.1 22G313 darwin-x64, locale en-BH)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Community Edition (version 2021.1.3)
[✓] VS Code (version 1.84.2)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for Ali’s Apple Watch. Ensure the device is unlocked and
      discoverable via Bluetooth. (code -27)
[✓] Network resources

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
@AlqallafAli 
Can you run `flutter run -v` and provide the entire verbose log ? It'll be huge log so you can put that in a text file and share it here.
Also, if you run through xcode, does it run properly or gives any error ? If so, can you provide that log here too ?

**Comment by AlqallafAli** [comment]
flutter run -v output
[output.txt](https://github.com/flutter/flutter/files/13474045/output.txt)

Xcode output (i can't run it even on Xcode)
[Build Prod_2023-11-27T21-18-28.txt](https://github.com/flutter/flutter/files/13474289/Build.Prod_2023-11-27T21-18-28.txt)

**Comment by caleb654** [comment]
I also have this same issue.

**Comment by darshankawar** [comment]
@AlqallafAli 
From the verbose log, I see below:

```
},
                       "_value" : "Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found"
}

 "_value" : "The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.0.99."
                     }                       



2023-11-27 21:10:10.499 xcodebuild[53602:1152917]  DVTPortal: Error:
           Error Domain=DVTPortalServiceErrorDomain Code=1100 "Your session has expired. Please log in." UserInfo={payload={
               creationTimestamp = "2023-11-27T12:10:10Z";
               httpCode = 200;
               protocolVersion = QH65B2;
               requestUrl = "https://developerservices2.apple.com/services/QH65B2/viewDeveloper.action";
               responseId = "88cae808-424a-42d3-81e8-094dd327b338";
               resultCode = 1100;
               resultString = "Your session has expired. Please log in.";
               userLocale = "en_US";
               userString = "Your session has expired. Please log in.";
           }, NSLocalizedDescription=Your session has expired. Please log in.}
           ** BUILD FAILED **
```

So you'll need to cross-check your pods installation along with deployment target for each pod you are using to confirm that they support minimum deployment target.

Also, in order to address the issue properly, please try to narrow down the issue to minimum replicable setup that still throws the same error so that we know it is actually a bug in framework, but currently it looks like a config issue at your end.

**Comment by noelmansour** [comment]
Not sure how much it'll help, but there is a thread about this issue on the apple developer forums: https://developer.apple.com/forums/thread/736152

**Comment by noelmansour** [comment]
I hit the same issue. It was related to iOS Firestore dependency being >= 10.17.0.

FlutterFire issue: https://github.com/firebase/flutterfire/issues/11858
Linked firestore-ios-sdk-frameworks issue: https://github.com/invertase/firestore-ios-sdk-frameworks/issues/79

I downgraded to pre-10.17.0 dependencies: https://github.com/firebase/flutterfire/blob/master/CHANGELOG.md#2023-10-31.

However, there are workarounds to use later versions in the firestore-ios-sdk-frameworks issue linked above.

**Comment by saizdx2010** [comment]
Got the same issue here

**Comment by MariusBelciug** [comment]
I spent two day on this issue. The old settings I had were: 
`cloud_firestore: ^4.8.0`
`firebase_core: ^2.13.1`

And the fix that worked for me is: 
```
cloud_firestore: 4.12.1
firebase_core: 2.20.0
```

After that I had a sandbox error in Xcode that was fixed very easily by changing the `User Script Sandboxing to NO in Runner - Build Settings.`

**Comment by apaolino** [comment]
Despite I downgrade the versions, I'm getting this error:

```
Error (Xcode): Framework 'FirebaseFirestoreInternal' not found
Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)
```

Already tried pod deintegrate, flutter clean, and usual stuff. I couldn't get iOS build successful.
