### ISSUE TITLE
Class 'int' has no instance getter

### ISSUE THREAD

**Issue by heshesh2010** [flutter/flutter#139049]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

when try to debug any code in VS code , I got error : 

```
Unhandled exception:
NoSuchMethodError: Class 'int' has no instance getter 'controller'.
Receiver: 3052316128
Tried calling: controller
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
#1      Eval ()
```

but I'm sure this code is working without debug 

### Expected results

show debug results 

### Actual results

error 

```
Unhandled exception:
NoSuchMethodError: Class 'int' has no instance getter 'controller'.
Receiver: 3052316128
Tried calling: controller
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
#1      Eval ()
```

### Code sample

<details><summary>Code sample</summary>

```dart
CachedNetworkImage(
            imageUrl:
                controller.worksList[controller.worksIndex.value].photo.path ??
                    "",
            imageBuilder: (context, imageProvider) => Container(
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(10),
                image: DecorationImage(
                  image: imageProvider,
                  fit: BoxFit.cover,
                ),
              ),
            ),
            placeholder: (context, url) => Image.asset(unknownPerson),
            errorWidget: (context, url, error) => Image.asset(defaultUser),
          ),
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![Screenshot 2023-11-27 at 10 20 46 AM](https://github.com/flutter/flutter/assets/16393042/355790bd-d6ca-4be2-bdbb-fb817e5ddbce)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.1.1 23B81 darwin-x64, locale en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.84.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @heshesh2010, please provide a complete minimal reproducible so that we can investigate this. From your screenshot it seems like you are using get. It has some extensions which may not be working as intended. So in order for this to be properly investigated, please provide a complete minimal reproducible code sample that does not use getx so that we can investigate this issue. 

Thank you

**Comment by heshesh2010** [comment]
> @heshesh2010 since you didn't give proper stacktrace and code, are you trying to execute the getter controller as a function () ?
> 
> Instead of This ` int len = recievedData.controller();` use ` int len = recievedData.controller;`
> 
> (where controlller might be a getter)
> 
> If you are trying to access a getter.

no I have passed the controller instance to my widget and in parent widget I init the controller by extends 

GetWidget<WorksScreenController>

**Comment by heshesh2010** [comment]
> Hi @heshesh2010, please provide a complete minimal reproducible so that we can investigate this. From your screenshot it seems like you are using get. It has some extensions which may not be working as intended. So in order for this to be properly investigated, please provide a complete minimal reproducible code sample that does not use getx so that we can investigate this issue.
> 
> Thank you

Yes I'm using Getx , here is my code sample 


`class ShowWorksItemsScreen extends GetWidget<WorksScreenController> {
  const ShowWorksItemsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return NetworkAwareScaffold(
      child: Scaffold(
          resizeToAvoidBottomInset: true,
          appBar: CustomAppBarWidget(
            'our_works'.tr,
            isBackEnabled: true,
            backButtonCallback: () {
              Get.delete<WorksScreenController>();
              Get.offNamed(Routes.worksScreen);
            },
          ),
          body: SafeArea(
            child: GestureDetector(
              onHorizontalDragEnd: (dragDetail) {
                // Swiping in right direction.
                if (dragDetail.velocity.pixelsPerSecond.dx < 1) {
                  if (controller.worksIndex.value == 0) {
                    // controller.worksIndex.value =
                    //     controller.worksList.length - 1;
                    return;
                  } else {
                    controller.worksCarouselController.previousPage();

                    controller.worksIndex.value =
                        controller.worksIndex.value - 1;
                  }
                }

                // Swiping in left direction.
                else {
                  if (controller.worksIndex.value ==
                      controller.worksList.length - 1) {
                    //controller.worksIndex.value = 0;
                    return;
                  } else {
                    controller.worksCarouselController.nextPage();
                    controller.worksIndex.value =
                        controller.worksIndex.value + 1;
                  }
                }
              },
              child: Padding(
                padding: EdgeInsets.symmetric(horizontal: 16.0.w),
                child: Center(
                  child: Obx(
                    () => controller.worksCommentControllerList.isEmpty
                        ? Center(
                            child: Text(
                              'no_works_found'.tr,
                              style: Get.textTheme.bodyLarge!,
                            ),
                          )
                        : SingleChildScrollView(
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.center,
                              mainAxisAlignment: MainAxisAlignment.start,
                              children: [
                                // 25.verticalSpace,
                                // grid view
                                CarouselSliderWidget(controller: controller),
                                24.verticalSpace,
                                // show selected works photo widget
                                SelectedWorksPhotoWidget(
                                    controller: controller),

                              ],
                            ),
                          ),
                  ),
                ),
              ),
            ),
          )),
    );
  }
}`



`
class SelectedWorksPhotoWidget extends StatelessWidget {
  const SelectedWorksPhotoWidget({
    super.key,
    required this.controller,
  });

  final WorksScreenController controller;

  @override
  Widget build(BuildContext context) {
    return Obx(() => controller.isWorksPicUploadingList.isEmpty
        ? Center(
            child: Text(
              'no_works_found'.tr,
              style: Get.textTheme.bodyLarge!,
            ),
          )
        : controller.isWorksPicUploadingList[controller.worksIndex.value].value
            ? Helper().shimmerSmallImageWidget()
            : Stack(
                children: [
                  SizedBox(
                    height: 326.h,
                    //    width: 326.w,
                    child: GetUtils.isURL(controller
                            .worksList[controller.worksIndex.value].photo.path!)
                        ? CachedNetworkImage(
                            imageUrl: controller
                                    .worksList[controller.worksIndex.value]
                                    .photo
                                    .path ??
                                "",
                            imageBuilder: (context, imageProvider) => Container(
                              decoration: BoxDecoration(
                                borderRadius: BorderRadius.circular(10),
                                image: DecorationImage(
                                  image: imageProvider,
                                  fit: BoxFit.cover,
                                ),
                              ),
                            ),
                            placeholder: (context, url) =>
                                Image.asset(unknownPerson),
                            errorWidget: (context, url, error) =>
                                Image.asset(defaultUser),
                          )
                        : ClipRRect(
                            borderRadius: BorderRadius.circular(10.0),
                            child: Image.file(
                              File(controller
                                  .worksList[controller.worksIndex.value]
                                  .photo
                                  .path!),
                              fit: BoxFit.cover,
                            )),
                  ),
                  // edit works photo button
                  Positioned(
                    left: 10,
                    top: 10,
                    child: InkWell(
                      onTap: () => controller.updateWorksPic(),
                      child: Container(
                        height: 40.h,
                        width: 40.w,
                        decoration: BoxDecoration(
                          color: Colors.white,
                          borderRadius: BorderRadius.circular(8),
                        ),
                        child:
                            Icon(Icons.edit, color: AppColors().greenColor(1)),
                      ),
                    ),
                  ),
                ],
              ));
  }
}
`

**Comment by danagbemava-nc** [comment]
Hi @heshesh2010, please provide a minimal reproducible sample that does not use getx or any third-party packages so that we can investigate the issue. If it is an issue with the framework, it should be reproducible without the third-party packages.

**Comment by TaufeeqNoamaan** [comment]
I think the use of "super" keyword in your case is incorrect. You should not use a superclass constructer with the "key" parameter.  A classic syntax error in my opinion

Use this instead: 
`const SelectedWorksPhotoWidget({
  Key? key,
  required this.controller,
}) : super(key: key);`

This should solve your issue.
