### ISSUE TITLE
[camera_avfoundation] CameraException(Error -11803, Cannot Record)

### ISSUE THREAD

**Issue by Mairramer** [flutter/flutter#139061]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I can't simulate it on my devices, but it happens to some clients. But it returns the following error:
Non-fatal Exception: FlutterError
CameraException(Error -11803, Cannot Record)
Documentation reference below:
[AVErrorSessionNotRunning](https://developer.apple.com/documentation/avfoundation/averror/averrorsessionnotrunning/)

### Expected results

Open the camera normally.

### Actual results

Black screen when opening the camera.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
> I can't simulate it on my devices, but it happens to some clients.

Can you provide list of devices on which this exception occurs ?

Also, without a replicable code or pattern that leads to the exception, it'll be difficult to make the issue actionable, so if you could provide more details, would help to properly analyze it.

**Comment by Mairramer** [comment]
@darshankawar It occurs on the following devices according to firebase:
iPhone 11 - 432 events
iPhone 13 - 227 events
iPhone XR - 183 events
iPhone 12 - 145 events
iPhone 14 - 102 events
iPhone 13 Pro Max - 80 events
iPhone 12 Pro - 63 events
iPhone 12 Pro Max - 51 events
iPhone 6s -45 events
iPhone 14 Pro Max - 42 events
iPhone 11 Pro Max - 41 events
iPhone SE (2nd generation) - 37 events
iPhone 8 Plus - 30 events
iPhone 11 Pro - 28 events
iPhone 8 - 28 events
iPhone 14 Pro - 27 events
iPhone 13 Pro - 20 events
iPhone 13 Mini - 18 events
iPhone 7 - 12 events
iPhone 15 Pro - 11 events
iPhone XS Max -10 events
iPhone 14 Plus - 8 events
iPhone X - 8 events
iPhone 7 Plus - 7 events
iPhone 6s Plus - 6 events
iPhone 15 Pro Max - 6 events
iPhone 12 Mini - 5 events
iPhone SE - 4 events
iPhone SE (3rd generation) -1 event

I can only simulate it by commenting the code below, on FLTCam.m:
```
- (void)start {
  [_videoCaptureSession startRunning];
  [_audioCaptureSession startRunning];
}
```
It runs after the initialize method, on CameraPlugin.m:
```
    NSDictionary *argsMap = call.arguments;
    NSUInteger cameraId = ((NSNumber *)argsMap[@"cameraId"]).unsignedIntegerValue;
    if ([@"initialize" isEqualToString:call.method]) {
     ...rest of code
      [_camera start];
      [result sendSuccess];
```

**Comment by darshankawar** [comment]
Thanks for the update @Mairramer 


> I don't know if it doesn't have an AVCaptureSession allocated or it is running before allocation.

Can you take a look at below and see if it helps to resolve the error or not ?

https://github.com/flutter/flutter/issues/131553#issuecomment-1688848234
https://github.com/flutter/flutter/issues/131553#issuecomment-1688904048

**Comment by Mairramer** [comment]
Unfortunately this doesn't apply to me.

**Comment by Mairramer** [comment]
I tried to find new evidence but so far I haven't found any.

**Comment by darshankawar** [comment]
Without replicable steps or pattern, unfortunately, we won't be able to make the issue actionable. If you observe the exception consistently, please provide more details.
