### ISSUE TITLE
(Will PR) Allow to provide custom headers to flutter web run

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#139008]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Hi, when developing https://github.com/fzyzcjy/flutter_rust_bridge v2, I hope to use `flutter run` to host the WASM (compiled from Rust) as well. However, it seems that to use certain features of WASM, the browsers require some http headers to be set.

The current workaround is that, we write our own code to create a devserver with such headers (if you are interested: https://github.com/fzyzcjy/flutter_rust_bridge/blob/68b1a9415d5a47b9a793074974af8b2f8a8bcfc0/frb_dart/bin/serve.dart#L325), and require users to use this code, instead of the familiar `flutter run` or whatever.

Surely, this is suboptimal: It is most natural and fluent to use `flutter run`, and every IDE has good support or it, etc. And things like `flutter test` may not have a easy substitution by the custom code because it has a lot of other logic inside.

I will PR for this, but I am not sure whether this looks good to Flutter dev team. If looks ok, just ping me and I will submit code!

### Proposal

(see above)

**Comment by danagbemava-nc** [comment]
Hi @fzyzcjy, it seems like this feature already exists on the master channel. See https://github.com/flutter/flutter/pull/136297. 

Is that what you're referring to or are you talking about something else?

**Comment by fzyzcjy** [comment]
Wow that's great, yes this is what I mention in the issue! I really do not expect this to be implemented in master (since it is not there for the whole history), and thanks for pointing out that PR and issue to me.

**Comment by aran** [comment]
@fzyzcjy I implemented specifically to use with flutter_rust_bridge :)
