### ISSUE TITLE
Remove set asset path RPC API from release build

### ISSUE THREAD

**Issue by aam** [flutter/flutter#13907]
https://github.com/flutter/engine/pull/4323 introduced new API to set asset bundle path to enable hot reload of updated assets. This API should not be available in release build.

**Comment by Hixie** [comment]
Marking m3 since this is a potential security issue.

**Comment by aam** [comment]
https://github.com/flutter/engine/blob/master/shell/common/platform_view_service_protocol.cc#L130 seems to actually take care of only registering this API for debug builds. So it won't be available in release builds.
