### ISSUE TITLE
Flutter doctor cannot determine VS Code version (Ubuntu 22.04.3 LTS)

### ISSUE THREAD

**Issue by songyang-dev** [flutter/flutter#139027]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Install Flutter through "Ubuntu Software"
2. Install Android Studio and VS Code through "Ubuntu Software"
3. Open Android Studio and install the command line tools from its SDK manager
4. Install the Flutter extension in VS Code
5. Run `flutter doctor`

### Actual results

Flutter doctor output
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.0, on Ubuntu 22.04.3 LTS 6.2.0-37-generic,
    locale en_CA.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.3)
[✓] VS Code (version unknown)
    ✗ Unable to determine VS Code version.
[✓] Connected device (2 available)
[✓] Network resources
```

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.0, on Ubuntu 22.04.3 LTS 6.2.0-37-generic,
    locale en_CA.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.3)
[✓] VS Code (version unknown)
    ✗ Unable to determine VS Code version.
[✓] Connected device (2 available)
[✓] Network resources


```

</details>

**Comment by navaronbracke** [comment]
Could you perhaps provide the output of `flutter doctor -vv` (yes that's a double v).

This will provide us with the output of the verbose `flutter doctor` output, in extra verbose mode, so that we can see what flutter doctor is doing.

**Comment by songyang-dev** [comment]
> The following seems to be related: #136997 but that only landed on master recently.
> 
> Does this work for you when on the master channel?

How do you switch to the master channel?

**Comment by navaronbracke** [comment]
The command `flutter channel master && flutter upgrade` switches you to the master channel.

To go back to stable, use `flutter channel stable && flutter upgrade`.

**Comment by huycozy** [comment]
@songyang-dev This may be a new issue by VS Code is installed from Ubuntu Software Center. It can be located at a different path than snap or Flatpak. But it's worth a try on master channel as mentioned above.

cc @KristijanZic as you have experience in this area and it would be appreciated if you could help to check this (I will also check this later on my machine)

**Comment by KristijanZic** [comment]
@songyang-dev  @huycozy thanks for the report and the ping. This is fixed in master with https://github.com/flutter/flutter/pull/136997 it's the exact same issue as https://github.com/flutter/flutter/issues/136996

Just to be sure, like @navaronbracke pointed out, I've switched to master by running `flutter channel master && flutter upgrade` and checked the positive result of the flutter doctor:

```console
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.17.0-16.0.pre.46, on Ubuntu 22.04.3 LTS
    6.2.0-36-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.84.2)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

For switching back to stable, like @navaronbracke stated, I ran: `flutter channel stable && flutter upgrade` and it went perfectly smooth.

@songyang-dev thankfully this is not a critical issue for development, it's just annoying to not see the green check. You can safely run the stable channel until the fix for this lands. It doesn't change affect anything in terms of dev experience or functionality so nothing to worry about there.

**Comment by songyang-dev** [comment]
Hi @KristijanZic, thank you for your response. I am not using Ubuntu at the moment. So I cannot confirm this at the moment.

I have switched to Windows and I am using WSL. I am not sure if this issue exists over there. I can provide an update on that issue should it happen over there. Feel free to close this in the meanwhile.

**Comment by huycozy** [comment]
@songyang-dev I think this is fixed by https://github.com/flutter/flutter/pull/136997 as VS Code in Ubuntu Software using the same source from Snap store:

![Screenshot from 2023-12-05 11-05-00](https://github.com/flutter/flutter/assets/104349824/b6ed74b4-dc0d-41eb-99b7-d861866b4159)

Confirm this on master channel:

```console
[✓] VS Code (version 1.84.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.78.0

[✓] VS Code (version 1.84.2)
    • VS Code at /snap/code/current/usr/share/code
    • Flutter extension version 3.78.0
```

<details>
<summary>flutter doctor -v</summary>

```bash
[!] Flutter (Channel master, 3.18.0-1.0.pre, on Ubuntu 22.04.3 LTS 6.2.0-37-generic, locale en_US.UTF-8)
    • Flutter version 3.18.0-1.0.pre on channel master at /home/huynq/Documents/Working/flutter_master
    ! Warning: `flutter` on your path resolves to /home/huynq/Documents/Working/flutter/bin/flutter,
      which is not inside your current Flutter SDK checkout at
      /home/huynq/Documents/Working/flutter_master. Consider adding
      /home/huynq/Documents/Working/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /home/huynq/Documents/Working/flutter/bin/dart, which is
      not inside your current Flutter SDK checkout at /home/huynq/Documents/Working/flutter_master.
      Consider adding /home/huynq/Documents/Working/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18f365d6da (29 hours ago), 2023-12-03 17:37:36 -0500
    • Engine revision 69cbf87f33
    • Dart version 3.3.0 (build 3.3.0-186.0.dev)
    • DevTools version 2.30.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use
      "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
    • Android SDK at /home/huynq/Android/Sdk/
    • Platform android-33, build-tools 34.0.0-rc3
    • Java binary at: /home/huynq/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2022.3)
    • Android Studio at /snap/android-studio/128/android-studio
    • Flutter plugin version 76.2.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/huynq/Documents/android-studio/
    • Flutter plugin version 67.0.1
    • Dart plugin version 211.7817
    • android-studio-dir = /home/huynq/Documents/android-studio/
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.84.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.78.0

[✓] VS Code (version 1.84.2)
    • VS Code at /snap/code/current/usr/share/code
    • Flutter extension version 3.78.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.3 LTS 6.2.0-37-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 119.0.6045.123

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```
</details>

I will close this issue as fixed. Once you come back your machine and still see the issue on master channel, feel free to comment here and I will reopen this. Thanks!
