### ISSUE TITLE
[CP] revert non-zero tessellation optimization

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#139146]
### Issue Link

https://github.com/flutter/flutter/issues/138598

### Commit Hash

3493f9b 

### Target

stable

### PR Link

https://github.com/flutter/engine/pull/48459

### Changelog Description

* Revert an incorrect optimization that causes paths to render incorrectly for certain SVGs

### Impacted Users

Flutter iOS users

### Impact Description

Rendering is incorrect with certain SVGs.

### Workaround

Disable Impeller

### Risk

low

### Test Coverage

yes

### Validation Steps

Run the attached app and unit tests on engine CI

**Comment by CaseyHillers** [comment]
@matanlurey can you review this CP request? If it looks good to you, add the "cp: approved" label.

**Comment by matanlurey** [comment]
Done.
