### ISSUE TITLE
[google_sign_in_web] migrate to pkg:web

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#139169]
Needed to support wasm compilation

Blocking migration of flutter dashboard to wasm

**Comment by amrgetment** [comment]
@kevmoo What will happen if the browser doesn't support WASM? and you built your app by 
`flutter build web --wasm`

**Comment by kevmoo** [comment]
@amrgetment – this is NOT the best place for this convo. Hit me up on Twitter. But...short version...

As of end-of-November 2023 things won't work if your browser doesn't support Wasm. VERY soon we'll enable dual-compile so developer will compile js & wasm. And we'll do runtime fallback if wasm-gc doesn't work

**Comment by amrgetment** [comment]
@kevmoo Thanks, a lot, I am excited to see it in action 😍
