### ISSUE TITLE
[CP] Add ability to customize `NavigationBar` indicator overlay and fix indicator shape for the overlay

### ISSUE THREAD

**Issue by TahaTesser** [flutter/flutter#139159]
### Issue Link

https://github.com/flutter/flutter/issues/138850 & https://github.com/flutter/flutter/issues/138900

### Commit Hash

397fd25be105e927cda4dd35e95664fc536a7d86

### Target

stable

### PR Link

Original PR: https://github.com/flutter/flutter/pull/138901
CP PR: https://github.com/flutter/flutter/pull/139162

### Changelog Description

Add ability to customize `NavigationBar` indicator overlay and fixes a bug with the indicator shape. 

### Impacted Users

Devs trying to create a custom nav bar 

### Impact Description

Visual impact, cannot change indicator overlay color and shape.

### Workaround

None

### Risk

low

### Test Coverage

yes

**Comment by TahaTesser** [comment]
cc: @Piinks @leighajarett

**Comment by CaseyHillers** [comment]
@HansMuller can you review this CP request? If it looks good to you, add the "cp: approved" label.
