### ISSUE TITLE
RouteObserver calls didPop too early

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#13919]
`RouteObserver` should call `_listeners[route]?.didPop()` in `unsubscribe` instead of `didPop`. This likely affects the accuracy of the Firebase Analytics plugin; it could report that routes have been popped when they are still visible.

More context: https://github.com/flutter/flutter/pull/11236/files/40240cf80e55970246b77f651666c4f33e936b43#r159754696

/cc @weisong0 @Hixie

**Comment by Hixie** [comment]
See also https://github.com/flutter/flutter/pull/13757

**Comment by Hixie** [comment]
Can you talk more about why this matters?

**Comment by kroikie** [comment]
@collinjackson

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/916. Any further collaboration will be done there.
