### ISSUE TITLE
[CP] DDS fix to ensure all DAP clients will correctly serialize Dart thread IDs

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#139177]
### Issue Link

https://github.com/dart-lang/sdk/issues/53086

### Commit Hash

DDS version 2.9.5

### Target

stable

### PR Link

https://github.com/flutter/flutter/pull/139158

### Changelog Description

DDS fix to ensure threadID integers are serialized correctly by Debug Adapter Protocol (DAP) clients.

### Impacted Users

Flutter developers using a debug client that happens to serialize big integers in scientific notation (currently VSCode is not affected)

### Impact Description

If using an affected debug client (e.g. neovim's), the client will crash if the ID of the Dart isolate thread that the developer is trying to debug is larger than the threshold for where it serializes numbers in scientific notation.

### Workaround

keep re-running the app and hope you get small thread IDs.

### Risk

low

### Test Coverage

yes

**Comment by CaseyHillers** [comment]
Shipped in Flutter 3.16.3
