### ISSUE TITLE
When flutter uses the default font, the Chinese font of FontWeight.w500 is not bold on ios.

### ISSUE THREAD

**Issue by FairyWorld** [flutter/flutter#139116]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. When flutter uses the default font, the Chinese font of FontWeight.w500 is not bold on ios.
2. If it is in English or on an Android phone, the font is normally bold.
3. Only ios does not take effect in Chinese fonts and FontWeight.w500

### Expected results

Use FontWeight.w500 to make Chinese fonts thicker in ios

### Actual results

Using FontWeight.w500 for Chinese fonts on iOS fails

### Code sample

<details><summary>Code sample</summary>

```dart
Text(
  'hello 世界',
  style: TextStyle(
    fontSize: 18,
    fontWeight: FontWeight.w400,
    color: Colors.red,
  ),
),
Text(
  'hello 世界',
  style: TextStyle(
    fontSize: 18,
    fontWeight: FontWeight.w500,
    color: Colors.red,
  ),
),
Text(
  'hello 世界',
  style: TextStyle(
    fontSize: 18,
    fontWeight: FontWeight.w700,
    color: Colors.red,
  ),
),
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Thanks for the report! 

This is a known issue being tracked at https://github.com/flutter/flutter/issues/105014. Closing this issue as a duplicate, so please follow up on it for further updates.
