### ISSUE TITLE
Can't select photos from Google Photos in `image_picker` after 0.8.7

### ISSUE THREAD

**Issue by lukehutch** [flutter/flutter#139111]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

See #121744 -- it was marked as fixed, but it is not.

The new `image_picker`, after version 0.8.7, disables Google Photos access.

In #121744, @tarrinneal said:
> We're going to add a config option to decide which version of the picker you would like to use while we wait for the cloud features to be added to the new image picker.
> 
> This will default to the old version, so you shouldn't need to change anything to get this feature back. 

Has that option been added yet? When will the cloud features be added to the new image picker?

Right now the image picker is nearly unusable, because for a lot of people, Google Photos is their primary photo album.

@danagbemava-nc @DanMossa @tarrinneal @stuartmorgan 

### Expected results

The user should be able to select photos from Google Photos

### Actual results

Right now (`image_picker` 1.0.4), this is the first picker screen, which indicates that you can select photos from Google Photos:

![image](https://github.com/flutter/flutter/assets/811305/cae68417-c91a-460b-ace4-7391220f95db)

However, clicking on the Photos icon gives only this:

![image](https://github.com/flutter/flutter/assets/811305/688d6772-13e8-4143-9d21-4596fef98911)

(The black "Photos" icon on this second screen does nothing.)

### Code sample

N/A

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.16.0, on Fedora Linux 39 (Workstation Edition) 6.5.12-300.fc39.x86_64, locale en_US.utf8)
    • Flutter version 3.16.0 on channel stable at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (12 days ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/luke/Android/Sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 17.0.4 (Fedora 17.0.4-1.fc39)
    • cmake version 3.27.7
    • ninja version 1.11.1
    • pkg-config version 1.9.5

[✓] Android Studio (version 2022.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 73.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.84.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.77.20231101

[✓] Connected device (3 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Linux (desktop)            • linux         • linux-x64      • Fedora Linux 39 (Workstation Edition) 6.5.12-300.fc39.x86_64
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 119.0.6045.159

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by lukehutch** [comment]
Update: after trying this several times, now the picker does in fact display Google Photos photos. I didn't change anything in my app. So somehow, the picker's ability to get Google Photos to show its albums is not 100% reliable.

As a separate issue, the Google Photos album view keeps flickering and redrawing. Where should I file a bug about that?

**Comment by lukehutch** [comment]
It's on the Android emulator, and I don't think that Play is set up to upgrade apps by default, so I doubt that Photos got upgraded. But I'll keep an eye on it.

See also this question:

> As a separate issue, the Google Photos album view keeps flickering and redrawing. Where should I file a bug about that?

**Comment by huycozy** [comment]
>As a separate issue, the Google Photos album view keeps flickering and redrawing. Where should I file a bug about that?

You can try this https://support.google.com/photos/answer/6156065?hl=en&co=GENIE.Platform%3DAndroid&oco=1 or post a question at https://support.google.com/photos/thread/new?hl=en

**Comment by stuartmorgan** [comment]
The UI in your screenshot is not controlled by the plugin, it's just launched via an intent. Once it has opened, the plugin is no longer involved until you complete the selection process and the OS switches back to you app's activity, so in cases like this where the expected UI is opening but you have issues *within* that UI you'd need to file issues against Android.
