### ISSUE TITLE
web's release vs debug environments split() differently

### ISSUE THREAD

**Issue by toekneema** [flutter/flutter#139128]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I have this arr of strings:
`[, td class="list-column", FN, /td, ]`
when i call `arr[2].split(", ")[1]`

in debug mode: it gives me an error
in release mode: it evaluates to null

### Expected results

i expect debug mode and release mode to evaluate it to the same value

### Actual results

stated above

### Code sample

use example from above

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

not necessary

**Comment by darshankawar** [comment]
@toekneema 
Can you provide a complete minimal reproducible code sample ?
