### ISSUE TITLE
developer.log not working as expected.

### ISSUE THREAD

**Issue by suhail600** [flutter/flutter#139131]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Upgrade Flutter to version 3.16.0.
2. Attempt to use developer.log to log messages.
3. Observe that the logs are not being captured as expected.

### Expected results

The developer.log should capture and display log messages as it did in version 3.10.5 and before 3.10.5.

![image_2023_11_28T10_00_06_983Z](https://github.com/flutter/flutter/assets/62710125/999053c4-75cf-4435-9fc7-0b187758d2ac)

it should be working like as in the image as flutters default behavior.

### Actual results

The developer.log functionality is not logging messages as expected after upgrading to version 3.16.0.

![image_2023_11_28T10_01_25_374Z](https://github.com/flutter/flutter/assets/62710125/61f49c5e-e43a-4b30-b023-129dfa884475)

### Code sample

```
import 'dart:developer' as developer;

void main() {
  developer.log(
    'This is a test print --> 3.16.0 Flutter SDK 3.2.0, (Flutter)Dart SDK',
  );
}
```

### Screenshots or Video

![image_2023_11_28T10_01_25_374Z](https://github.com/flutter/flutter/assets/62710125/b4d85b8f-935f-4c85-981c-8d321ba4c18a)

![image_2023_11_28T10_00_06_983Z](https://github.com/flutter/flutter/assets/62710125/c2f53680-3c06-47ff-8045-bf34f79e8b50)

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

```
[√] Flutter (Channel stable, 3.16.0, on Microsoft Windows [Version 10.0.22621.2428], locale en-IN)
    • Flutter version 3.16.0 on channel stable at C:\Users\userData\development\sdks\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (13 days ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\userData\AppData\Local\Android\sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[√] VS Code (version 1.84.2)
    • VS Code at C:\Users\userData\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.76.0

[√] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.2428]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 119.0.6045.160
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 119.0.2151.72

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

**Comment by danagbemava-nc** [comment]
Hi @suhail600, `dart:developer` is a part of the dart-sdk and should be reported on their repo https://github.com/dart-lang/sdk/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

Closing from here. 

PS: You might want to check if this happens with just vscode or it happens in the terminal or other IDEs as well. 

Thank you

**Comment by thoAEH** [comment]
I also had the same problem
