### ISSUE TITLE
DescriptorPoolRecyclerVKTest.ReclaimMakesDescriptorPoolAvailable is flaky

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#139184]
Starting with https://github.com/flutter/engine/commit/01fcec7214dbd0ec77032cd87a15712c2306d0ec, which looks unrelated, the test `DescriptorPoolRecyclerVKTest.ReclaimMakesDescriptorPoolAvailable` is flaking.

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Production%20Engine%20Drone/489442/overview

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Production%20Engine%20Drone/489363/overview

**Comment by zanderso** [comment]
I think the flakes might have started with https://flutter.googlesource.com/mirrors/engine/+/4168cf737fd739362ad082bb22555fdd86bfd25f, which is the first commit where I'm seeing the flakes today.

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Production%20Engine%20Drone/489144/overview

cc @gaaclarke

**Comment by jonahwilliams** [comment]
Fixed in https://github.com/flutter/engine/pull/48479


![image](https://github.com/flutter/flutter/assets/8975114/27bb84ab-62c4-4398-abd3-bab963583818)
