### ISSUE TITLE
Got Error Release Build Web

### ISSUE THREAD

**Issue by AntonLie** [flutter/flutter#139109]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I already running `flutter build web`

and copy to directory deployment with nginx.

in local there's no problem and Firebase too after deployment 

Nginx:
http://18.140.222.208:82/#/scc/web/login

Firebase: 
https://scc-project-7767a.web.app/#/scc/web/login

### Expected results

Expected Result Working Well like: 
https://scc-project-7767a.web.app/#/scc/web/login

### Actual results

Got Error like this:
<img width="1440" alt="Screenshot 2023-11-28 at 08 18 25" src="https://github.com/flutter/flutter/assets/89154283/91b98cdb-be32-4c95-8d2d-409f6972b792">

<img width="1440" alt="Screenshot 2023-11-28 at 08 19 01" src="https://github.com/flutter/flutter/assets/89154283/d2b358a0-a7d9-4b15-bbbc-ebadffd7cfa7">

### Code sample

-

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.16.0, on Ubuntu 20.04.4 LTS 5.15.0-1047-aws, locale C.UTF-8)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
    ✗ CMake is required for Linux development.
      It is likely available from your distribution (e.g.: apt install cmake), or can be downloaded from https://cmake.org/download/
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from
      https://github.com/ninja-build/ninja/releases
    ✗ pkg-config is required for Linux development.
      It is likely available from your distribution (e.g.: apt install pkg-config), or can be downloaded from
      https://www.freedesktop.org/wiki/Software/pkg-config/
[!] Android Studio (not installed)
[✓] Connected device (1 available)
[✓] Network resources

**Comment by toufchuan** [comment]
i have the same problem.

**Comment by toufchuan** [comment]
@AntonLie seems 3.16.1 fixed this,try it

**Comment by AntonLie** [comment]
@toufchuan do you mean need upgrade flutter version?

**Comment by toufchuan** [comment]
> @toufchuan do you mean need upgrade flutter version?

yes,run flutter upgrade

**Comment by huycozy** [comment]
@AntonLie Let's try upgrading Flutter to see if the issue is fixed or not. If it still persists, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so that we may verify this. Thanks!

**Comment by toufchuan** [comment]
This problem still exists, I don't know when it will happen, now I can only access the web page I built through 127.0.0.1.
