### ISSUE TITLE
Icons.keyboard_double_arrow_right_rounded is not visible on mobile web

### ISSUE THREAD

**Issue by tomasbaran** [flutter/flutter#139171]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Use Icons.keyboard_double_arrow_right_outlined in your code

Other icons I tried worked on both mobile and desktop.

see example here: https://github.com/tomasbaran/dayagenda/blob/main/lib/widgets/task_card.dart 

### Expected results

Open it on desktop web: you can see it: 
<img width="1440" alt="Screenshot 2023-11-28 at 3 00 38 p m" src="https://github.com/flutter/flutter/assets/25743901/7a1aa64b-b926-4227-9c86-c31feaedd450">

### Actual results

 Open it on mobile web: safari/chrome: you cannot see it:
<img width="324" alt="Screenshot 2023-11-28 at 3 01 26 p m" src="https://github.com/flutter/flutter/assets/25743901/b7089e50-8213-4ab2-adde-7592f2bd83e0">

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.0 23A344 darwin-arm64, locale en-MX)
    • Flutter version 3.13.9 on channel stable at /Users/tomas/code/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (5 weeks ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 119.0.6045.159

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by huycozy** [comment]
This could be an implementation issue as the screen is wider on desktop. In order to verify the issue properly, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Thanks!

**Comment by tomasbaran** [comment]
You are right — it seems only an implementation issue since the minimal repro code is not showing it. Thanks @huycozy!
