### ISSUE TITLE
Can't Build My App for Android

### ISSUE THREAD

**Issue by GabrielPintoo** [flutter/flutter#139296]
### Is there an existing issue for this?

- [x] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run flutter for android.
2. Receive error.
![image](https://github.com/flutter/flutter/assets/125649430/722605fb-1359-4950-8b1b-7f0c4ed41f25)
3. Running Flutter doctor gives out an error with android license:
![image](https://github.com/flutter/flutter/assets/125649430/00bd09e5-6e5f-41d9-8617-b1bd314f2df4)
![image](https://github.com/flutter/flutter/assets/125649430/235fe3b4-24bf-4d25-95c6-81d1ef3a38c8)

### Actual results

I was programming a Flutter App. Yesterday it was all working perfectly fine, but today I upgraded flutter and I started having issues building for flutter.
When I run the app for android:
![image](https://github.com/flutter/flutter/assets/125649430/722605fb-1359-4950-8b1b-7f0c4ed41f25)

When I run flutter doctor:
![image](https://github.com/flutter/flutter/assets/125649430/00bd09e5-6e5f-41d9-8617-b1bd314f2df4)
![image](https://github.com/flutter/flutter/assets/125649430/235fe3b4-24bf-4d25-95c6-81d1ef3a38c8)

For Windows and Web I can build and everything works fine so I really doubt is a plugin issue. I need some help, been stuck here too long.

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by stuartmorgan** [comment]
This error is coming from the third-party `motion_sensors` plugin; it hasn't been updated in several years and is requiring a very old version of Android tooling. You'll need to report this issue to the developer of the plugin.

**Comment by GabrielPintoo** [comment]
> This error is coming from the third-party `motion_sensors` plugin; it hasn't been updated in several years and is requiring a very old version of Android tooling. You'll need to report this issue to the developer of the plugin.

Did you check my flutter doctor output? flutter doctor --android-licenses gives me a very suspicious error. As I said, 2 days ago it worked perfectly fine...
