### ISSUE TITLE
command line tools missing (when i run flutter doctor) ##(vs-code editior)

### ISSUE THREAD

**Issue by anand9773** [flutter/flutter#139288]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### problem is : -
- when is use flutter doctor command  =>i face   error command line missing and i use vscode and every thing i asses through command line  

###  i try many method  here is my more information:-
`$ flutter doctor`
**[✗] Android toolchain - develop for Android devices
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.**

--------------------------------------------------------------------------------------
### my sdkmanager locations  :- 
`export PATH=$PATH:"/opt/android_sdk/cmdline-tools/latest/bin"
`

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.0, on Ubuntu 22.04.2 LTS 6.2.0-26-generic, locale en_IN)
[✗] Android toolchain - develop for Android devices
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (version unknown)
    ✗ Unable to determine Android Studio version.
    ✗ android-studio-dir = /opt/android_sdk/cmdline-tools/latest/bin
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.84.2)
[✓] Connected device (2 available)
[✓] Network resources

```
</details>

<b> i know i make mistake in the Android Studio  path  => this path is actually android command line tools  => this thing happens because i use command `flutter config --android-studio-dir=<directory>`    so place ignore this area they are not effecting    <b>

**Comment by huycozy** [comment]
It indicates that `Android SDK Command-line Tools` hasn't been installed yet. Please check [this](https://stackoverflow.com/questions/68236007/i-am-getting-error-cmdline-tools-component-is-missing-after-installing-flutter) to see if it helps.

>this thing happens because i use command flutter config --android-studio-dir=<directory>

You should replace `<directory>` with the real Android Studio path in your system.
