### ISSUE TITLE
Add option to control whether the root DropdownMenu can be closed or not

### ISSUE THREAD

**Issue by josh-burton** [flutter/flutter#139269]
### Steps to reproduce

1. Created nested MenuAnchors
2. Select a MenuItem from the child MenuAnchor

### Expected results

The child Menu is closed (or a configuration option exists to control whether the root menu will be closed)

### Actual results

The child and parent menus are both closed

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

const Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: darkBlue,
      ),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Center(
          child: MenuAnchor(
            menuChildren: [
              ParentMenuModal(),
            ],
            builder: (context, controller, widget) {
              return ElevatedButton(
                child: const Text("Click me"),
                onPressed: () {
                  controller.open();
                },
              );
            },
          ),
        )
    );
  }
}

class ParentMenuModal extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return DropdownMenu(
      label: const Text('Menu'),
      initialSelection: "1",
      dropdownMenuEntries: ["1", "2", "3"]
          .map(
            (it) =>
            DropdownMenuEntry(
              value: it,
              label: it,
            ),
      )
          .toList(),
    );
  }
}

```

</details>

**Comment by huycozy** [comment]
Hi @josh-burton 
A similar proposal was implemented at https://github.com/flutter/flutter/pull/123723 but it's for MenuItemButton with a new `closeOnActivate` option. In this case, you are using DropdownMenuEntry which is not the same child under MenuAnchor. 

I'm not sure if it's feasible to implement the same way to DropdownMenuEntry or not. Labeling this as a proposal to have other's opinions.

**Comment by josh-burton** [comment]
> Hi @josh-burton A similar proposal was implemented at #123723 but it's for MenuItemButton with a new `closeOnActivate` option. In this case, you are using DropdownMenuEntry which is not the same child under MenuAnchor.
> 
> I'm not sure if it's feasible to implement the same way to DropdownMenuEntry or not. Labeling this as a proposal to have other's opinions.

Yes this `closeOnActivate` option is essentially what needs enhancing I think. DropdownMenu internally uses MenuItemButton from MenuAnchor, and `closeOnActivate` is true by default.

I think perhaps what we need is:

- deprecate `closeOnActivate`
- introduce new `closeOnActivateBehaviour` enum class with values `none`, `self`, `all`
- add the `closeOnActivateBehaviour` to DropdownMenu which will internally pass it down to MenuItemButton

**Comment by josh-burton** [comment]
Pinging @whiskeyPeak and @gspencergoog for some input

**Comment by josh-burton** [comment]
My use case is a settings panel that gets opened from a toolbar. That panel then has various other dropdowns etc. 

A dialog could work for the panel but I don't want it centered on screen, or a scrim. MenuAnchor works well here as it handles positioning the panel near the button etc.

I feel like MenuAnchor is flexible enough that it may be used in similar ways in many apps.

**Comment by AlessandroDeStefano** [comment]
I’m providing a workaround for the similar issue I reported a month ago (#152933). Despite my efforts, I couldn’t get the `labelWidget` to occupy the entire dropdown entry. However, I discovered that the `ButtonStyle` constructor, passed to the `style` property of `DropdownMenuEntry`, includes the `backgroundBuilder` property. This enables you to build the background for the entry itself, allowing you to incorporate part of the code provided by @PurplePolyhedron to absorb the tap action and prevent the dropdown menu from closing.
Here the extracted code:
```dart
DropdownMenuEntry(
...
  style: ButtonStyle(
    backgroundBuilder: (context, states, child) {
      if (child == null) {
        print('DropdownMenu backgroundBuilder has null child');
        return const SizedBox();
      }
  
      return GestureDetector(
        onTap: () {
          handleOnTap();
        },
        child: Stack(
          children: [
            const Positioned.fill(child: AbsorbPointer()),
            child,
          ],
        ),
      );
    },
    ...
  ),
...
)
```
