### ISSUE TITLE
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#13925]
I do not have repro steps, these are reports from the wild that I see in the Google Play Console (for a personal pet project app).
I get these reports for Android 7.0 and Android 7.1, on: Moto X (4) (payton_sprout) and Galaxy S8 (dreamqltesq)

backtrace:
```
pid: 0, tid: 0 >>> us.chardons.c511 <<<

backtrace:
  #00  pc 000000000004f6da  /data/app/us.chardons.c511-1/lib/arm/libflutter.so
  #01  pc 0000000000346961  /data/app/us.chardons.c511-1/oat/arm/base.odex
```

**Comment by zoechi** [comment]
Is this issue still relevant?

**Comment by amirh** [comment]
Hard to say, but I'd close this specific report as it's not very actionable given we're missing information to de-obfuscate the stack.
