### ISSUE TITLE
[Docs] document who can add labels to PRs

### ISSUE THREAD

**Issue by yakagami** [flutter/flutter#139244]
From https://github.com/flutter/flutter/wiki/Tree-hygiene

>Once everything is green and you have an LGTM from the owners of the code you are affecting (or someone to whom they have delegated), and an LGTM from any other contributor who left comments, add the "autosubmit" label. A bot will land the patch when it feels like it.

Unless I'm missing something, contributors without write access cannot add labels to PRs. I think that should be made more clear in this paragraph because as it stands it sounds like that's the next thing I should do but I can't. Also beneficial to mention would be who to ask to add the label and where (in the PR, on Discord ect.)

**Comment by goderbauer** [comment]
Fixed.
