### ISSUE TITLE
MacOS build release app got a typing view on bottom

### ISSUE THREAD

**Issue by luohao123** [flutter/flutter#139209]
<img width="627" alt="image" src="https://github.com/flutter/flutter/assets/49749220/b64df291-8be2-43dc-b122-d25b438ba335">

Why?

**Comment by darshankawar** [comment]
@luohao123 
It seems your issue is same as https://github.com/flutter/flutter/issues/128956 that has been fixed already. Please check the same along with underlying comments and see if it helps in your case or not.

**Comment by luohao123** [comment]
Solved
