### ISSUE TITLE
[google_sign_in] GoogleSignIn.games().signIn() or signInSilently() raise "IllegalStateException: Nonnull field "email" is null" then VM crashes

### ISSUE THREAD

**Issue by andynewman10** [flutter/flutter#139219]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a Flutter application and configure Firebase (google-services.json). Declare `google_sign_in: ^6.1.6` in pubspec.yaml.
2. Call `WidgetsFlutterBinding.ensureInitialized()` then run the following code somewhere in a test Widget:

final account = await GoogleSignIn.games().signIn();

3. The following exception is shown in the Console:

```
D/AndroidRuntime(22997): Shutting down VM
E/AndroidRuntime(22997): FATAL EXCEPTION: main
E/AndroidRuntime(22997): Process: com.example.application, PID: 22997
E/AndroidRuntime(22997): java.lang.IllegalStateException: Nonnull field "email" is null.
E/AndroidRuntime(22997): 	at io.flutter.plugins.googlesignin.Messages$UserData.setEmail(Messages.java:264)
E/AndroidRuntime(22997): 	at io.flutter.plugins.googlesignin.Messages$UserData$Builder.build(Messages.java:362)
E/AndroidRuntime(22997): 	at io.flutter.plugins.googlesignin.GoogleSignInPlugin$Delegate.onSignInAccount(GoogleSignInPlugin.java:710)
E/AndroidRuntime(22997): 	at io.flutter.plugins.googlesignin.GoogleSignInPlugin$Delegate.onSignInResult(GoogleSignInPlugin.java:685)
E/AndroidRuntime(22997): 	at io.flutter.plugins.googlesignin.GoogleSignInPlugin$Delegate.$r8$lambda$ZecMDYPyEjlKS_0d6gVa9h0Lnk8(GoogleSignInPlugin.java)
E/AndroidRuntime(22997): 	at io.flutter.plugins.googlesignin.GoogleSignInPlugin$Delegate$$ExternalSyntheticLambda6.onComplete(D8$$SyntheticClass)
E/AndroidRuntime(22997): 	at com.google.android.gms.tasks.zzi.run(com.google.android.gms:play-services-tasks@@18.0.2:1)
E/AndroidRuntime(22997): 	at android.os.Handler.handleCallback(Handler.java:751)
E/AndroidRuntime(22997): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(22997): 	at android.os.Looper.loop(Looper.java:241)
E/AndroidRuntime(22997): 	at android.app.ActivityThread.main(ActivityThread.java:6274)
E/AndroidRuntime(22997): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(22997): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
E/AndroidRuntime(22997): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

Tested devices:

- Sony Z5C with Android 7.1.1
- Motorola E13 with Android 13 Go

On the Motorola device, where I am testing things on an occasional basis only, the signIn() call did trigger the appearance of a consent screen "Connect with Google. Project XYZ wants to access your Google Account. Create, modify and delete your activity in Google Play Games ; Create a relation between you and your personal information on Google", and I clicked "Authorize". The exception and crash happens after that, even though I was in a debug session.

### Expected results

No exception and sign-in successful.

### Actual results

An exception is raised.

### Code sample

<details><summary>Code sample</summary>

```dart
final account = await GoogleSignIn.games().signIn();
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.16.0, on Microsoft Windows [version 10.0.22000.2538], locale fr-FR)
    • Flutter version 3.16.0 on channel stable at C:\Users\andy\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (2 weeks ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\andy\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.0.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.0.31919.166
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Users\andy\Documents\Applications\android-studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at C:\Users\andy\Documents\Applications\IntelliJ
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.84.2)
    • VS Code at C:\Users\andy\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.76.0

[√] Connected device (4 available)
    • E5823 (mobile)    • CB5A28LMYH • android-arm64  • Android 7.1.1 (API 25)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [version 10.0.22000.2538]
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 119.0.6045.160
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 119.0.2151.72

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @andynewman10, if you add the email scope, do you still get this issue? 

You can try using the `GoogleSignIn(scope: [], signInOption: ...).signIn()` instead of `GoogleSignIn.games().signIn()`.

**Comment by andynewman10** [comment]
@danagbemava-nc Thanks for your reply.

I have the same problem with `GoogleSignIn(scopes: [], signInOption: SignInOption.games).signIn()`.

**Comment by andynewman10** [comment]
@danagbemava-nc Sorry, I misread your reply. Doing properly what you said now.

With `GoogleSignIn(scopes: [ 'email' ], signInOption: SignInOption.games).signIn(`), on my Z5C device, this time the call to `signIn()` does bring me to the consent dialog. This dialog has the additional 'email' scope (obviously) compared to the earlier experience on my Motorola E13. It's weird that the consent dialog did appear without the email scope on the Motorola E13, isn't it?

Still Z5C, if I click Authorize, then the crash still occurs.

**Comment by danagbemava-nc** [comment]
That is rather interesting. It seems like with the playgames v2 we don't need to request any additional scopes. 

Are you signing in with the same account on both devices? Also, can you provide the steps you used to setup the play games sign in? I tried following the docs, but I get the api error 10 when I attempt to sign In. Regular google sign in works just fine.

**Comment by andynewman10** [comment]
> That is rather interesting. It seems like with the playgames v2 we don't need to request any additional scopes.

This is what I understood from the Play Games v2 docs, yes.

> Are you signing in with the same account on both devices?

It is not the same account.

> Also, can you provide the steps you used to setup the play games sign in? I tried following the docs, but I get the api error 10 when I attempt to sign In. Regular google sign in works just fine.

- create a Flutter 3.16.0 application using VS code, on Windows.
- pubspec.yaml: use `google_sign_in: 6.1.6`
- use the following code:
```
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  GoogleSignIn.games().signIn();
}
```
- run the code on an Android 7.1.1 or 13 Go device.

**Comment by danagbemava-nc** [comment]
Hi @andynewman10, did you have to do any setup on google play?

Would it be possible to provide a complete project setup in a repo that we can clone so that we can investigate? We will replace any keys with our own

**Comment by danagbemava-nc** [comment]
Hi @andynewman10, I don't think that is likely, but I can't definitively say so. 

From what I understand about the sign in process with google, if the configuration is wrong, it will throw an error with code 10, indicating a developer error. The error in this case, seems to be that a value which is not expected to be null ends up being null.

**Comment by andynewman10** [comment]
> Are you signing in with the same account on both devices? Also, can you provide the steps you used to setup the play games sign in? I tried following the docs, but I get the api error 10 when I attempt to sign In. Regular google sign in works just fine.

@danagbemava-nc my sincere apology if I misunderstand the current requests, but do you manage to write a simple application that succeeds in signing-in? From your above cited message, I understand you do not manage (at all) to sign in with `GoogleSignIn(scopes: [], signInOption: SignInOption.games).signIn()`. Based on that, how do you want to help? Again, sorry but I am confused here: what can I do if, on your side, you cannot sign-in either? Please let me know.

**Comment by danagbemava-nc** [comment]
Hi @andynewman10, I want to know if you had to do some additional steps to get the sign in working. The sample app I have works if I use regular google sign in but if I attempt to sign in using google play games, it fails with a developer error. I'm not sure if I missed something in the setup stage, but I was wondering if you had to do any setup, on either gcp or google play games for you to be able to sign up with games
