### ISSUE TITLE
Replacement for deprecated ``textScaleFactor``?

### ISSUE THREAD

**Issue by JGeek00** [flutter/flutter#139213]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I want to get the text scale factor defined on system settings. Previously I could do it with ``MediaQuery.of(context).textScaleFactor``, but now this is deprecated. I don't find any documentation that tells you how to do that now. How can I replace that deprecated feature to keep the same behavior? I see that now we have a ``textScaler``, but I cannot get a double value from there with the scale factor.

### Proposal

An attribute that does the same as the deprecated ``textScaleFactor``.

**Comment by darshankawar** [comment]
@JGeek00 
Can you take a look at [this](https://github.com/flutter/flutter/issues/138547) and see if it helps in your case or not ?

**Comment by JGeek00** [comment]
That worked for me. Thank you.
