### ISSUE TITLE
Keyboard not pushing the content at top Flutter version 3.13.8

### ISSUE THREAD

**Issue by theatifmalik** [flutter/flutter#139295]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Form field is touched and keyboard open
the keyboard should push the fields above it but it is overlapping the form and scroll is not working
It works on previous version

### Expected results

Keyboard should push the view above it

### Actual results

It is not pushing the fields upward instead it makes them hide

### Code sample

  ```
@override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        const BackgroundImage(),
        Scaffold(
          resizeToAvoidBottomInset: false,
          backgroundColor: Colors.transparent,
          appBar: AppBar(
            automaticallyImplyLeading: false,
            backgroundColor: Theme.of(context).appBarTheme.backgroundColor,
            toolbarHeight: 42.0,
            title: Row(
              children: [
                GestureDetector(
                  child: Image.asset(
                    'assets/images/left_arrow_50.png',
                    color: const Color(0xfffc9e1e),
                    width: 30,
                  ),
                  onTap: () {
                    Get.back(closeOverlays: true);
                  },
                ),
                const SizedBox(
                  width: 20,
                ),
                const Text(
                  ',
                  style: TextStyle(color: Color(0xfffc9e1e), fontSize: 18),
                ),
              ],
            ),
          ),
          body: SafeArea(
            child: SingleChildScrollView(
              controller: ScrollController(),
              child: Padding(
                padding: const EdgeInsets.symmetric(horizontal: 12.0),
                child: Obx(() => Column(
//form data)
```
This is parent widgets structure

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.8, on Microsoft Windows [Version 10.0.19044.2130], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)                        
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)                                                                                             
[√] Chrome - develop for the web                                                                                                                                             
[!] Visual Studio - develop Windows apps (Visual Studio Community 2019 16.11.30)                                                                                             
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools                               
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows                                               
        Windows 10 SDK                                                            
[√] Android Studio (version 2022.2)                                               
[√] IntelliJ IDEA Community Edition (version 2023.1)                              
[√] VS Code (version 1.84.2)                                                      
[√] Connected device (4 available)                                                
[√] Network resources                                                             
                                                                                  
! Doctor found issues in 1 category.

**Comment by darshankawar** [comment]
@theatifmalik 
From your code sample, you seem to be using third party package like `get`. In order to properly address the issue, we would need a minimal but complete reproducible code sample without any third party package implementation that still shows the reported behavior, so if you see the behavior with bare minimum framework code, provide the same here.

Also, in your code, you seem to have `resizeToAvoidBottomInset: false,` which ideally should be `true` to see the content being pushed up when keyboard opens. You can also look for solutions on support channels like StackOverflow wherein, similar cases are frequently asked.
