### ISSUE TITLE
Close context menu on back press.

### ISSUE THREAD

**Issue by AsfaqueAhmed** [flutter/flutter#139211]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I am facing a issue regarding context menu in flutter. I have the following case scenario- 

- I have a text field with custom context menu button. 
- When the context menu is opened and i press back button, this removes the keyboard from the screen and remove the context menu. 

### Proposal

- I want to remove the context menu but keep the keyboard opened. this is doable in native but not in flutter.

**Comment by darshankawar** [comment]
@AsfaqueAhmed 
Can you provide `flutter doctor -v` and a minimal reproducible code sample that shows the current behavior and what's the expected behavior you are looking for ?
