### ISSUE TITLE
[infra][cocoon] Unable to use the dashboard

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#139382]
The login button is gone and I can't use the dashboard anymore. I see a suspicious `Getting ready` message in the top right corner.

<img width="962" alt="image" src="https://github.com/flutter/flutter/assets/1278212/2e0c31b1-949e-4a4f-80f3-f5c943e6725b">

cc @zanderso who also sees the same issue.

**Comment by keyonghan** [comment]
Switched to an earlier version to unblock.
Based on what @ditman mentioned in discord, from Infra side, we need to bump `google_sign_in_web` to 0.12.1. @sealesj could you help bump the deps to fix forward?

**Comment by sealesj** [comment]
Great, thanks for switching the version!
Yes, I will bump that dep

**Comment by sealesj** [comment]
Lowering priority since switching dashboard to earlier version resolved the immediate issue until `google_sign_in_web` is bumped

**Comment by ditman** [comment]
I'm working on a fix forward for the web plugin. **The bad version is `google_sign_in_web: 0.12.2`**. I'm going to try and publish `0.12.3`, but `0.12.1` would temporarily fix the issue as well. (0.12.2 has been removed from pub).
