### ISSUE TITLE
Regressions in velocity_tracker_iteration and velocity_tracker_iteration_ios_fling microbenchmarks

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#139306]
On the PR https://github.com/flutter/flutter/pull/139166, SkiaPerf has flagged regressions in a couple of velocity tracker microbenchmarks.

https://flutter-flutter-perf.skia.org/e/?begin=1701246320&end=1701288562&keys=Xcd5422c1ceffafcffeddb33f5ee0384a&num_commits=50&request_type=1&xbaroffset=38174

Routing to `team-framework` and marking P0 for triage.

cc @Piinks

**Comment by zanderso** [comment]
It looks like the PR modified the benchmarks, so the change in performance may be expected, but I'll leave this open anyway as a sanity check.

**Comment by jonahwilliams** [comment]
The same benchmark regressed last time and we discussed and concluded that was WAI.

See https://github.com/flutter/flutter/issues/135503#issuecomment-1736090440
