### ISSUE TITLE
Custom install fonts and other files

### ISSUE THREAD

**Issue by tas-unn** [flutter/flutter#139350]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Is it possible to do a local installation of all external files that are downloaded from the server, to your server, or directly to the asset?
This is necessary for two cases:
1) If you need to install the site (web version) on a secure network without access to the external Internet
2) Long time downloading a file from the server. If you put the file on the local network, the download will probably happen faster.

[Example file](https://fonts.gstatic.com/s/notosanssc/v36/k3kCo84MPvpLmixcA63oeAL7Iqp5IZJF9bmaG9_FnYxNbPzS5HE.ttf
)
Here you can see that this file takes quite a long time to download, which leads to a long loading time for the site.

![image](https://github.com/flutter/flutter/assets/92320184/2dfcb19c-eba1-453c-998d-06f4017c61fe)

### Proposal

Local install fonts

**Comment by yjbanov** [comment]
Deduplicating with https://github.com/flutter/flutter/issues/132689
