### ISSUE TITLE
Add version numbers to flutter daemon/flutter run --machine

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#13933]
The analysis server sends its version number in a "connected" event at startup. This is both useful for debugging if someone sends a log file but also for enabling functionality only when it's known to be supported.

It would be useful if `flutter run --machine`/`flutter daemon` did the same. That way if there's new functionality in future (for example, the ability to launch emulators) the client can avoid sending unknown commands to older versions.

I know it's possible to run `flutter --version` , but relying on users to do this is error-prone (their PATH not match the flutter path they've set for the IDE) and it feels a bit naff for the IDEs to have to it separately.

**Comment by zanderso** [comment]
@DanTup It looks like the tool can now print machine readable version info. Is that sufficient to address this?

**Comment by DanTup** [comment]
Yeah - #17873 address this (though the above is a bit confused, since it's the protocol version rather than the Flutter version we use for things like emulator support). The main Flutter SDK version is read from the VERSION file to include in logs and things.

So I don't think anything else is needed here.
