### ISSUE TITLE
CustomTransitionPage ios swipes gestures not working 

### ISSUE THREAD

**Issue by awaisjamil-vd** [flutter/flutter#139324]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I am using go_router and CustomTransitionPage it is causing ios swipe gestures disabled and I have been stuck here for long time please help 

### Expected results

I am using go_router and CustomTransitionPage it is causing ios swipe gestures disabled and I have been stuck here for long time please help 

### Actual results

I am using go_router and CustomTransitionPage it is causing ios swipe gestures disabled and I have been stuck here for long time please help 

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @awaisjamil-vd, please provide the following information

- The version of go_router you're using
- A minimal complete reproducible code sample 
- Your output of flutter doctor -v

Thank you
