### ISSUE TITLE
Flutter create dart101 permission denied

### ISSUE THREAD

**Issue by alperrkara** [flutter/flutter#139358]
Hello I'm trying this command on MacOS terminal 
`~ flutter create dart101`
it gives me a permission denied reply. How can I resolve this?

**Comment by darshankawar** [comment]
@alperrkara 
Can you provide the entire error log that you get along with `flutter doctor -v` ?

**Comment by alperrkara** [comment]
I need to add the path every time that I opened up it Terminal. So it's looking like this:


<img width="702" alt="Ekran Resmi 2023-12-01 16 03 29" src="https://github.com/flutter/flutter/assets/117166989/ed120e86-6e2f-48d1-8111-6da4c3b4e1e3">


After this I'm trying to `~ flutter create dart101` then I get this: 

<img width="652" alt="Ekran Resmi 2023-12-01 16 04 36" src="https://github.com/flutter/flutter/assets/117166989/05ef0003-bf61-4f09-b860-c5154d0c1800">
