### ISSUE TITLE
TextField keyboardType number - onSubmitted does not trigger on iOS even when using physical keyboard

### ISSUE THREAD

**Issue by TDuffinNTU** [flutter/flutter#139304]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Create a `TextField` widget with `keyboardType: TextInputType.number`, and  ` onSubmitted: (_) => print("submitted!")`

Enter some text and attempt to submit with a physical keyboard

### Expected results

onSubmit should be triggered when enter is pressed via a physical keyboard.

### Actual results

onSubmit doesn't trigger.

### Code sample

<details><summary>Code sample</summary>

```dart

TextField(
        keyboardType: TextInputType.number,
        onSubmitted: (_) => print("submitted!"),
      ),

```
</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/43959652/59bd1d45-fb4c-4012-a185-e2c5f81eb928

</details>

### Logs

<details><summary>Logs</summary>

NA

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.6, on macOS 14.1.1 23B81 darwin-arm64, locale en-GB)
    • Flutter version 3.13.6 on channel stable at /Users/tomduffin/Dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (9 weeks ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/tomduffin/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • C00CFC3A-963E-4561-849A-B778B23F5623 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 14.1.1 23B81 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 119.0.6045.159

[✓] Network resources
    • All expected network resources are available.

```

</details>

**Comment by TDuffinNTU** [comment]
https://github.com/flutter/flutter/issues/12220 I believe this issue is related, hence the very similar title.

**Comment by darshankawar** [comment]
Thanks for the report @TDuffinNTU 
My colleague verified this behavior using physical keyboard and running the code on iPhone 7 with which he was able to see the `onSubmitted` method being triggered properly. He also tried running on simulator but couldn't input anything via physical keyboard. Note that, he has regular keyboard with `Enter` key and not a mac keyboard with `return` key. I am wondering if that could be related or not.

Can you provide on which iOS device are you seeing the reported behavior ? or whether you are using simulator ? Also, the physical keyboard type you are using.  If possible, would be good to check the behavior using native iOS as well, whether the issue persists on it as well or not, or this is just Flutter specific.

**Comment by TDuffinNTU** [comment]
I'm using a physical keyboard connected to an M1 Mac Mini, Sonoma 14.1.2. This was tested on an iPhone simulator. This was a physical connection with "connect hardware keyboard" selected in the iOS simulator menu.

I also managed to recreate it on my iPhone SE (2020) when connected to the keyboard via bluetooth using an internal build on testflight/

**Comment by TDuffinNTU** [comment]
If it helps, my minimal example does exclude the fact we have a focus node assigned to the text field, though it didn't have any kind of keyboard input listener until I added one as a workaround for this issue.
