### ISSUE TITLE
[go-router] Add a ShellRoute.indexed constructor.

### ISSUE THREAD

**Issue by ips-jm** [flutter/flutter#139384]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Go router currently provides the StatefulShellRoute.indexedStack() constructor. It works well when you are working with any index-based navbar and want to keep the widget state. But there is no clean way to dispose or reload the state once you are going to another location / coming back to the old location. The lack of methods to dispose the state is a problem with big apps especially.

In order to achieve a clean dispose-architecture, you can use the normal ShellRoute, but when working with a NavigationRail e.g. you have much boilerplate code to manage for initial selection, pushing routes if the selection changes and so on. 

### Proposal

A constructor like "ShellRoute.indexed()" would be great for this use case, with getters like in "StatefulShellRoute.indexedStack()" (getter for index and the ability to go to a route with an index).

If I'm overlooking another way of achieving this in a clean manner, please let me know. 

If needed, I can provide some minimal code samples of my current implementation and what I'm looking for with "ShellRoute.indexed", although I think it should be pretty clear.

**Comment by chunhtai** [comment]
If you want a cleaner way to navigate between subroute of a ShellRoute, you can give name to each of the subroute use goNamed instead.
