### ISSUE TITLE
DropdownButtonFormField inner padding

### ISSUE THREAD

**Issue by nickolight** [flutter/flutter#139355]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I can't make the correct inner padding(EdgeInsets.zero) for the selected item in DropdownButtonFormField, because that value is hardcoded and depends on the 'alignedDropdown' field in the "dropdown.dart" file.

```
const EdgeInsetsGeometry _kAlignedButtonPadding = EdgeInsetsDirectional.only(start: 16.0, end: 4.0);
const EdgeInsets _kUnalignedButtonPadding = EdgeInsets.zero;
```
```
    final EdgeInsetsGeometry padding = ButtonTheme.of(context).alignedDropdown
      ? _kAlignedButtonPadding
      : _kUnalignedButtonPadding;
```

But I want to use the field "alignedDropdown" with a "true" value and "_kAlignedButtonPadding" with a "EdgeInsets.zero" value

How it works now:
<img width="298" alt="Screenshot 2023-12-01 at 11 22 24" src="https://github.com/flutter/flutter/assets/17278021/66045c42-bae5-4b26-abaf-8f98e075e380">

What I want:
<img width="295" alt="Screenshot 2023-12-01 at 11 23 04" src="https://github.com/flutter/flutter/assets/17278021/0730e614-b020-4539-a523-9840c0515ad1">

Code:
```
              ButtonTheme(
                alignedDropdown: true,
                child: DropdownButtonFormField<RequestType>(
                  value: requestType,
                  items: RequestType.values.map((requestType) {
                    return DropdownMenuItem<RequestType>(
                      value: requestType,
                      child: Text(
                        requestType.requestTypeName,
                      ),
                    );
                  }).toList(),
                ),
```

### Proposal

Add the opportunity to handle this inner padding.
This problem has been around for so long and you still can't solve it.

**Comment by huycozy** [comment]
Thanks for the report! 

This is a known issue being tracked at https://github.com/flutter/flutter/issues/123783. Closing this issue as a duplicate, so please follow up on it for further updates.
