### ISSUE TITLE
Seeking Advice on Gradually Replacing Existing Native Android and iOS Apps with Flutter-Based UI

### ISSUE THREAD

**Issue by faisalansari0367** [flutter/flutter#139312]
Greetings everyone,

Our team is currently navigating a significant challenge with our in-production native Android and iOS applications. We've recently developed a new application using Flutter, featuring a revamped UI and several new features. Our end goal is to seamlessly replace both native applications with the Flutter version.

However, integrating this new Flutter-based UI into our existing native apps without releasing an entirely new version poses a significant concern.

We aim to prevent user confusion due to a drastic UI change while safeguarding our current ratings and download statistics.

We've contemplated two approaches: Integrating the entire Flutter application into our existing native apps, but this poses concerns about maintainability due to dependencies on various third-party SDKs and libraries.

Exploring the possibility of integrating the native app into a Flutter application as an framework, although we are uncertain about the feasibility of this approach.

We're seeking advice and alternative solutions on how to seamlessly introduce a new UI experience without compromising user satisfaction or losing existing app metrics. Are there any recommended strategies or best practices to achieve this transition effectively? We'd greatly appreciate any insights, experiences, or suggestions the community might offer. 

Thank you in advance for your valuable input and guidance.

Sorry for posing it here, but I wanted some suggestions asap.

**Comment by darshankawar** [comment]
@faisalansari0367 
This repo is mostly about tracking bugs and feature requests so this isn't the correct platform to seek suggestions on your use case. I suggest you to reach out in support channels like StackOverflow, flutter's reddit help page or on social media platforms like Twitter to get feedback or response.
I'll close it for now, as this isn't an issue to be tracked in this repo.
