### ISSUE TITLE
Enable auto-submit on the `flutter/games` repository

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#139326]
The `flutter/games` repository has Dependabot configured without the ability to autosubmit dependabot PRs.

Can we please update the configuration of `flutter/games` to autosubmit these PRs? Thanks!

**Comment by ricardoamador** [comment]
Yes sir. Let me check it out.

**Comment by ricardoamador** [comment]
@sealesj @domesticmouse I just added the flutter/games repository to the auto-submit app. Is there a request that you need to accept @domesticmouse ?

**Comment by domesticmouse** [comment]
I can't see any requests that I can accept regarding this. I just added the `autosubmit` tag so that dependabot will tag PRs it creates automagically. Hopefully, after that, it should all just work. We will find out next time one of my dependencies increments. 

Thanks all!

**Comment by ricardoamador** [comment]
@domesticmouse I took a look at your most recent PR where autosubmit was added and it looks like the label was not created yet. We could create a test PR to make sure if you are open to that. If that does not work let me ask Godofredo, he is an admin and while I can see the settings for the apps I don't have permissions for much else.

**Comment by ricardoamador** [comment]
No problem. Just so you know though, the check runs will have to pass before the app will submit this pull request.

**Comment by domesticmouse** [comment]
Looks like things are still broken https://github.com/flutter/games/pull/13#issuecomment-1840028417:

> auto label is removed for flutter/games/13, Failed to merge flutter/games/13 with Pull request flutter/games/13 could not be merged: Squash merges are not allowed on this repository..

**Comment by sealesj** [comment]
Are squash merges enabled on the repository? I don't have access to check but it should be an available option on the repo settings.

**Comment by domesticmouse** [comment]
> Are squash merges enabled on the repository? I don't have access to check but it should be an available option on the repo settings.

I also don't have access. Help  @godofredoc please 😂

**Comment by ricardoamador** [comment]
@domesticmouse while I cannot look to see if that merge option is configurable, you may however accelerated my timeline on this: https://github.com/flutter/flutter/issues/114557 which would allow you to work around the issue.

**Comment by sealesj** [comment]
@domesticmouse @godofredoc has enabled squash merges on the repo now - could you let me know if you have success with the autosubmit bot?

**Comment by domesticmouse** [comment]
I'll close for now and re-open if there is an issue. Thanks!
