### ISSUE TITLE
Gclient sync on stable channel / windows fails due to missing arm64 windows prebuilts.

### ISSUE THREAD

**Issue by eladm-ultrawis** [flutter/flutter#139370]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. follow the steps to setup the engine development on a windows machine
2. run gclient sync with a specific revisions
3. there as a 50/50 chances you will encounter an error similar to a previously unresolved (yet closed) [issue](https://github.com/flutter/flutter/issues/131980)

In my case I am trying to compile the flutter engine for flutter 3.16.
In the `engine.version` file on `flutter/bin/internal/engine.version` I have:

```
74d16627b940bb15e50891f82cad6c3e3465bd6d
``` 

And so I run:

```
C:\libs\engine> gclient sync --revision=src/flutter@74d16627b940bb15e50891f82cad6c3e3465bd6d    
``` 

### Expected results

gclient sync should succeed

### Actual results

PS C:\libs\engine> gclient sync --revision=src/flutter@74d16627b940bb15e50891f82cad6c3e3465bd6d
Updating depot_tools...
Syncing projects: 100% (135/135), done.

________ running 'cipd ensure -log-level error -root C:\libs\engine -ensure-file C:\Users\mrmai\AppData\Local\Temp\tmpygn1vmbd.ensure' in '.'
Errors:
  failed to resolve flutter/dart-sdk/windows-arm64@git_revision:525f5bb94e01a9e5c6c9ecb9b7919b717020d525 (line 8): no such tag
Error: Command 'cipd ensure -log-level error -root C:\\libs\\engine -ensure-file C:\\Users\\mrmai\\AppData\\Local\\Temp\\tmpygn1vmbd.ensure' returned non-zero exit status 1
Errors:
  failed to resolve flutter/dart-sdk/windows-arm64@git_revision:525f5bb94e01a9e5c6c9ecb9b7919b717020d525 (line 8): no such tag

### Code sample

C:\libs\engine> gclient sync --revision=src/flutter@74d16627b940bb15e50891f82cad6c3e3465bd6d    

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

[√] Flutter (Channel stable, 3.16.0, on Microsoft Windows [Version 10.0.22631.2715], locale en-US)
    • Flutter version 3.16.0 on channel stable at C:\libs\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (2 weeks ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34316.72
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.84.2)
    • VS Code at C:\Users\mrmai\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.78.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.2715]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 119.0.2151.72

[√] Network resources
    • All expected network resources are available.

**Comment by huycozy** [comment]
Hi @eladm-ultrawis 
Are you using Windows with ARM-based processors? Could you share step-by-step including commands you did?

**Comment by huycozy** [comment]
Looks like this happened to https://github.com/flutter/flutter/issues/131980 as well. Which channel do you see a working commit? If it's on master, it's probably fixed.

**Comment by eladm-ultrawis** [comment]
I am using the stable channel.

**Comment by jonahwilliams** [comment]
@eladm-ultrawis in order to build flutter engine on windows / stable channel you need to set the following variable to false:

https://github.com/flutter/engine/blob/main/DEPS#L579

basically there is no arm64 build of windows on stable channel but the deps file will still try to pull it. Please try this out and let me know if it solves the problem.

**Comment by eladm-ultrawis** [comment]
@jonahwilliams as far as I know the `gclient sync` command starts with an empty folder (just a .gclient file). So I am not sure when exactly to set it. Can you please elaborate?

**Comment by whesse** [comment]
In the solutions file, after the "safesync_url" line (but inside the following brace), add the following:

    "custom_vars": {
        "release_candidate": True,
    },

**Comment by eladm-ultrawis** [comment]
@whesse it worked! thanks! I think this should be noted on the official docs on compiling the engine. It is really hard to deduce from those docs what is the correct way to have compatible SDK + engine.

**Comment by zanderso** [comment]
@whesse Is Dart now publishing the arm64 SDK on the beta and stable channels going forward? Should we remove this guard from the Engine DEPS file?

**Comment by sortie** [comment]
@zanderso Yep the Windows ARM64 and Linux RISCV64 builds are now on the stable channel :)
