### ISSUE TITLE
Validate topic format in pubspec check

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#139305]
Apparently the check that `topics` entries meet the allowed syntax is a server-side check; we had a PR pass our CI, including the dry-run publish check, but then fail to actually publish in post-submit and thus break the tree with:
> Invalid `topics` value (`platform views`): must consist of lowercase alphanumerical characters or dash (but no double dash), starting with a-z and ending with a-z or 0-9.

We should put that validation logic into our existing pubspec validation.

**Comment by stuartmorgan** [comment]
Reassigning to @LouiseHsu per discussion. Thanks!

This just needs validation [here](https://github.com/flutter/packages/blob/293b0718889391a340e52bfb748449d82c3689f7/script/tool/lib/src/pubspec_check_command.dart#L337) that each topic meets the requirements described in that error message. (And we should fix my copypasta in the documentation comment for that method, since it says it's validating a different keyword than it actually is.)

**Comment by parlough** [comment]
This extra validation is great, but adding a cross-link to https://github.com/dart-lang/sdk/issues/52256 for further improvements in this area.
