### ISSUE TITLE
Use diagrams to illustrate the relationships between AnimationController, Animation, Tween, CurveTween, and CurvedAnimation objects

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter#13931]
The Q4 UX study shows that developers have difficulty understanding how different objects in an animation are related to one another. It would be great to use diagrams to illustrate their relationships in the [Tween Animation Tutorial](https://flutter.io/tutorials/animation/). 

I recommend using a [timing chart](https://developers.google.com/web/tools/chrome-devtools/inspect-styles/animations) to tie different concepts together. Since this type of diagram is already used in [the staggered animations tutorial](https://flutter.io/animations/staggered-animations/), it would be nice to introduce this representation earlier with a single tween animation occupying the full timeline and show how an easing curve affects the progression of the animation. In addition, it's also useful to visually show the "controls" on the AnimationControl object such as forward, reset, stop, etc. 

This issue depends on API changes that might be resulted from #14482.

**Comment by xster** [comment]
Perhaps in a separate more zoomed out diagram but consider adding Ticker, ImplicitlyAnimatedWidget, AnimatedWidget as well

**Comment by InMatrix** [comment]
@xster Good idea for zooming into a under-the-hood view for those who're curious.

**Comment by InMatrix** [comment]
As an example, this is the diagram I showed in my DartConf talk: 
![image](https://user-images.githubusercontent.com/348942/36568560-4d9e6046-17df-11e8-9706-0bc02fbb3fbd.png)

@Sfshaza, let me know if you think this is useful when you have a chance to take a look. I'm happy to provide the source file.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2076](https://github.com/flutter/website/issues/2076) via [**ZenHub**](https://www.zenhub.com/)
