### ISSUE TITLE
Introduce subclasses of  ImplicitlyAnimatedWidget and `*Transitions` widgets

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter#13932]
The Q4 UX study shows that developers tend to look for animation examples closely matching the ones they wanted to implement, e.g., translating the location of a widget or changing the size of a widget. The current [landing page for Animation](https://flutter.io/animations/) points the user to a tutorial which teaches them how to build such animations from scratch using `AnimationController` and `Tween`. This can be overwhelming for users who are building simple animations.   

This problem can be solved by introducing subclasses of [ImplicitlyAnimatedWidget](https://docs.flutter.io/flutter/widgets/ImplicitlyAnimatedWidget-class.html) and `*Transitions` widgets, which implement different kinds of local transitions (animations applied to a single object), before the link to the tween animation tutorial. My specific request is to show a grid of different types of local transitions in animated GIFs and link to the applicable API from each of them.

**Comment by InMatrix** [comment]
Related to #14017

**Comment by InMatrix** [comment]
There was also a user looking for an example similar to the one used in the study but didn't find it. See the Gitter conversation: https://gitter.im/flutter/flutter?at=5a5dd5d1ba39a53f1a1f713a

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2075](https://github.com/flutter/website/issues/2075) via [**ZenHub**](https://www.zenhub.com/)
