### ISSUE TITLE
Improve and fix MenuAnchor/MenuItemButton UX for desktop

### ISSUE THREAD

**Issue by Fernthedev** [flutter/flutter#139395]
MenuAnchor for Material 3 is great for contextual menus but there are some minor issues related to accessibility. Specifically, keyboard navigation does not auto-select an element when opening the menu. This causes some UX confusion where the user has to navigate further to access the menu he or she just opened, which in my case is not user friendly.

Setup:
- Material 3
- Windows 10 22H2
- Flutter 3.16.2

Relevant PR:
- [ ] https://github.com/flutter/flutter/pull/139396 MenuItemButton doesn't have an `autofocus` attribute, thereby making it harder to navigate with the keyboard. 

Thanks Flutter Team!

**Comment by Fernthedev** [comment]
I started looking and saw `TapRegion` was the ancestor widget which handles outside clicks for closing the menu. 
This line is responsible for the secondary tap issue mentioned previously.
https://github.com/flutter/flutter/blob/d7d1572f37f365f7c5a41ac0be875cbec838c456/packages/flutter/lib/src/widgets/tap_region.dart#L237-L239

**Comment by huycozy** [comment]
Hi @Fernthedev 
Using the 1st example at [MenuAnchor](https://api.flutter.dev/flutter/material/MenuAnchor-class.html), I can navigate between menus normally with arrow keys. I'm not sure which case `autofocus` can be used, could you be more specific?

https://github.com/flutter/flutter/assets/104349824/6f3a3cf6-a4a5-4839-abc5-769391cdbbd0

Also, will the linked PR solve the 2nd and 3rd problems above? Or are they other issues?

**Comment by Fernthedev** [comment]
Hi, thanks for getting back to me. The other issues will not be resolved with the PR. I might look into those if Flutter gives me a direction for resolving them. Specifically, whether if TapRegion should have an option to listen to other mouse buttons, or some other solution.

As for the 1st issue, yes you can navigate the menu with the keyboard. However the autofocus attribute is useful in the case where the focus can be requested for a specific element on menu open. For my use case, this is better as it doesn't rely on Flutter's keyboard navigation to figure out how to focus the menu in a listview (Maybe that's just me or a bug in my code, but I don't think the PR can be disregarded yet anyways). I'll try to get some video footage later today.

Thanks!

**Comment by huycozy** [comment]
>However the autofocus attribute is useful in the case where the focus can be requested for a specific element on menu open.

Thanks for the update. Labeling this point as a feature request. 

For two remaining issues, please file separate issues for them for better tracking.

**Comment by Fernthedev** [comment]
Done, should I adjust this issue to focus on the `autofocus` feature then?

Here are the new subsequent issues:
https://github.com/flutter/flutter/issues/139555
https://github.com/flutter/flutter/issues/139556

**Comment by Fernthedev** [comment]
Here's some footage example showcasing the difficulty of navigating to the menu in my desktop app. It also accidentally shows a separate MenuAnchor keyboard bug, which seems harder to resolve since each MenuAnchor is individually controlled.

https://streamable.com/t807zn
