### ISSUE TITLE
Running Integration Tests in debug Mode on web-server Device Does Not Display Prints

### ISSUE THREAD

**Issue by JMAK13** [flutter/flutter#139322]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run an integration test with flutter drive similar to below command. Just need to make sure to specify `--debug` and `-d webserver`
```
  flutter drive -d web-server --web-port=3001 --debug --no-headless 
            --no-pub
            --driver-port 4444
            --browser-name chrome
            --browser-dimension=1512,944
        --web-renderer canvaskit
                --driver=test_driver/integration_test.dart
```
2. Add some `print` statements to the integration test file you're running using the command above.

### Expected results

1. Our debug print statements show up in the Debug Console.

### Actual results

1. Our debug print statements only show up in Chrome's browser console. This is a bug because we are running in debug mode and our debug print statements do not show up in the Debug Console. We also use these debug statements to report the results of individual tests, but currently this is broken because the print statements do not show up in standard output.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.5, on macOS 13.6.2 22G320 darwin-arm64, locale en-US)
    • Flutter version 3.13.5 on channel stable at /Users/joshmcintyre/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12fccda598 (2 months ago), 2023-09-19 13:56:11 -0700
    • Engine revision bd986c5ed2
    • Dart version 3.1.2
    • DevTools version 2.25.0

[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/joshmcintyre/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[!] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    ✗ Unable to get list of installed Simulator runtimes.
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.6.2 22G320 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 119.0.6045.159

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by quannguyen42** [comment]
As an alternative, how would we write a reporter for a `flutter drive` command that allows us to report of each `testWidgets`? Basically, it's similar to how IDEs like Android Studio and Visual Studio Code report on `flutter test` runs.

Any pointer would be greatly appreciated.
