### ISSUE TITLE
Option to render Flutter Web using plain DOM elements

### ISSUE THREAD

**Issue by jsloop42** [flutter/flutter#139353]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

My main pain points are to use existing UI automation tools like Selenium for testing Flutter web. We have a framework built on top of selenium that does UI testing for HTML based site. Since Flutter doesn't generate HTML DOM elements and uses canvas, SVG etc. in html web renderer mode, doing UI automation like fill forms, etc are currently not possible.

Another issue is in regards to SEO. It would be great if SEO and discoverability is improved so that use cases like e-commerce website can be developed instead of web apps like portals behind and login that doesn't need indexing.

### Proposal

My proposal is that Flutter Web provide an option to use plain DOM elements. This will help us in using automation tools that targets HTML and since we have the DOM elements, it will help with SEO as well. 

I know this is a huge ask as it requires to map all Widgets to HTML elements. If there is a solution to use Selenium like tools to run automation in the final rendered HTML, that's what I am looking for.

And Flutter is great so far!

Thank You.

**Comment by jsloop42** [comment]
I am also looking to see if I can write some sort of JS to Dart interop library that can expose methods which can be called for automation testing. Will keep posted.

**Comment by jsloop42** [comment]
> @jsloop42 
> 
> Can you take a look at [this](https://github.com/flutter/flutter/issues/47600) issue and check if it resembles your use case ?
> 
> 

This should also work. If we have server side rendering and outputs HTML, we will in fact get the DOM. And we can work from there.

**Comment by darshankawar** [comment]
Thanks for the update. Closing this in favor of the linked issue.
