### ISSUE TITLE
Design discussion for State/StatefulWidget: Why does StatelessWidget have a build but the build for StatefulWidget is on the State?

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#13938]
We should add a Design Discussion section to State/StatefulWidget that discusses the design.

Questions:

> Subclassing both `StatefulWidget` and `State<MyClass>` seems like unnecessary boilerplate, although I’m sure there’s a good reason;

Answer from @abarth was:

> The main issue with that is that closures in Dart implicitly capture |this|. When the build function is on StatefulWidget, that means you'll capture the widget, which can change when the parent rebuilds. With the build function on the State, you capture the State object, which persists across rebuilds. You can still access the widget using the |widget| property, but that property always leads to the latest widget even if the parent rebuilds.

This video also explains it in different terms: https://www.youtube.com/watch?v=dkyY9WCGMi0

**Comment by Hixie** [comment]
See also https://github.com/flutter/flutter/issues/13938 https://github.com/flutter/flutter/issues/12296 https://github.com/flutter/flutter/issues/11649

**Comment by Hixie** [comment]
(cc @HansMuller @willlarche)

**Comment by willlarche** [comment]
Just some opinions as someone new to the platform.

I had thought this was unusual from an MVC / MVVM point of view. I'm used to something like:

Widget = View
State = View Model

The view would consume the view model and make changes based on its values. The view model wouldn't control any part of the view. 

Instead it's:

Widget = View
State = Controller

The view is changed / controlled by the state. But the view also created the state (in the examples) which is unusual. I'd expect the controller to create or own the view and the view to be dumb which is the other way around.

**Comment by Hixie** [comment]
Flutter's widgets layer isn't really MVC. It's more reactive-based.

**Comment by Hixie** [comment]
I recommend watching the video linked to above, though, for a more thorough treatment of this question.

**Comment by willlarche** [comment]
That totally makes sense. This is definitely not the same. But as someone coming from iOS, MVC and its descendants are my best frame of reference.

**Comment by markusaksli-nc** [comment]
Closing as this was added to [State](https://api.flutter.dev/flutter/widgets/State/build.html).
