### ISSUE TITLE
Update go_router code in `Get to know firebase for flutter` codelab

### ISSUE THREAD

**Issue by emilyabest** [flutter/flutter#139320]
Link to "Get to know Firebase for Flutter" Codelab: https://firebase.google.com/codelabs/firebase-get-to-know-flutter#4

In the "Get to know Firebase for Flutter" Codelab, Step 5 has an outdated call to "state.queryParameters."

In the code snippet for lib/main.dart, this line:

> final arguments = state.queryParameters;

should be changed to this line:

> final arguments = state.uri.queryParameters;

as mentioned in go_router update 10.1.3 (https://github.com/flutter/packages/blob/main/packages/go_router/CHANGELOG.md)

Thank you!

**Comment by RobPayne1** [comment]
I ran into this problem as well on https://firebase.google.com/codelabs/firebase-get-to-know-flutter?hl=en#4

Changing final arguments = state.queryParameters; to final arguments = state.uri.queryParameters; solved the issue. It just needs to be updated.

**Comment by ericwindmill** [comment]
Submitted fix via CL #591028993

**Comment by domesticmouse** [comment]
This should now be published
