### ISSUE TITLE
Crash in macos

### ISSUE THREAD

**Issue by zhouyongqiang228** [flutter/flutter#139451]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

flutter version:  macos intel 3.16.0
macos version: 14.1.1 (23B81) / IMac 2019 / inter core i9 / 48GB 2667 MHz DDR4 / Redeon Pro 580 8GB

1. create new flutter project
2. open macos xcodeProject
3. class MainFlutterWindow: NSWindow    =>   class MainFlutterWindow: NSPanel 
4. add NSStatusItem in AppDelegate.swift,like this:
` import Cocoa
import FlutterMacOS

@NSApplicationMain
class AppDelegate: FlutterAppDelegate {
    var statusBarItem: NSStatusItem!
    override func applicationDidFinishLaunching(_ aNotification: Notification) {
        statusBarItem = NSStatusBar.system.statusItem(withLength: 10)
        if let button = statusBarItem.button {
            button.title = "aaa";
                   button.action = #selector(toggleMenu(_:)) // 设置点击事件
               }
        let menu = NSMenu()
        menu.addItem(NSMenuItem(title: "Quit", action: #selector(test), keyEquivalent: "q"))
        statusBarItem.menu = menu
    }
    @objc func toggleMenu(_ sender: Any?) {
    }
    @objc func test() {
    }
  override func applicationShouldTerminateAfterLastWindowClosed(_ sender: NSApplication) -> Bool {
    return true
  }
}
`
5. run
6. click the status button, the app will crash when moush up

### Expected results

nothing happend

### Actual results

app crash

### Code sample

<details><summary>Code sample</summary>

```swift
//AppDelegate.swift
import Cocoa
import FlutterMacOS

@NSApplicationMain
class AppDelegate: FlutterAppDelegate {
    var statusBarItem: NSStatusItem!
    override func applicationDidFinishLaunching(_ aNotification: Notification) {
        
        statusBarItem = NSStatusBar.system.statusItem(withLength: 10)
        if let button = statusBarItem.button {
            button.title = "aaa";
                   button.action = #selector(toggleMenu(_:)) // 设置点击事件
               }
        let menu = NSMenu()
        menu.addItem(NSMenuItem(title: "Quit", action: #selector(test), keyEquivalent: "q"))
        statusBarItem.menu = menu
    }
    
    
    @objc func toggleMenu(_ sender: Any?) {
    }
    @objc func test() {
    }
    
    
    
  override func applicationShouldTerminateAfterLastWindowClosed(_ sender: NSApplication) -> Bool {
    return true
  }
}

```

```swift
//MainFlutterWindow.swift
import Cocoa
import FlutterMacOS

class MainFlutterWindow: NSPanel {
  override func awakeFromNib() {
    let flutterViewController = FlutterViewController()
    let windowFrame = self.frame
    self.contentViewController = flutterViewController
    self.setFrame(windowFrame, display: true)

    RegisterGeneratedPlugins(registry: flutterViewController)

    super.awakeFromNib()
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
none
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
none
```

</details>

**Comment by stuartmorgan** [comment]
> Logs
> ```
> none
> ```

Please provide the crash log for the crash.
