### ISSUE TITLE
[web]: RichText inconsistencies in Dark mode, TextSpan has black color in Web only

### ISSUE THREAD

**Issue by Gustl22** [flutter/flutter#139401]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Execute Code Sample below

### Expected results

Show white text on dark background (for web only)

### Actual results

Shows black text on dark background (for web only). All other platforms work fine. Also using `Text.rich` works as expected.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'RichText Dark Demo',
      themeMode: ThemeMode.dark,
      theme: ThemeData.light(),
      darkTheme: ThemeData.dark(),
      home: Scaffold(
        appBar: AppBar(title: Text('RichText Dark Demo')),
        body: Center(
          child: Column(children: [
            Divider(),
            Text.rich(TextSpan(text: "Text.rich()")),
            Divider(),
            RichText(text: TextSpan(text: "RichText()")),
            Divider(),
          ]),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

Left: Web, Right: Linux
![Screenshot from 2023-12-02 00-45-21](https://github.com/flutter/flutter/assets/18537755/e19c8aaa-0222-4594-90ac-a27a9c2ec9c5)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

On stable, but also reproducible on latest master.

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.0, on Ubuntu 23.10 6.5.0-13-generic, locale en_US.UTF-8)
    • Flutter version 3.16.0 on channel stable at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (2 weeks ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/gustl/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_SDK_ROOT = /home/gustl/Android/Sdk
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+9-Ubuntu-123.10)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 16.0.6 (15)
    • cmake version 3.27.4
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
    • IntelliJ at /opt/intellij-idea-ultimate
    • Flutter plugin version 76.3.4
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 23.10 6.5.0-13-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 119.0.6045.199

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @Gustl22 
Although I do see the same behavior as reported specially on web, I cam across [this](https://github.com/flutter/flutter/issues/61452#issuecomment-658219360) comment which might be one of the reason as why the theme may not be applicable to `RichText`. Can you check the same and see if it helps further ?

**Comment by mdebbar** [comment]
One of the differences between `Text.rich` and `RichText` is that the former inherits default text styles from the app's theme, while the latter doesn't. The dark theme of your sample app has a white-ish color for text, and that is what's used for `Text.rich()`.

`RichText`'s style, on the other hand, has no color (because you didn't specify one, and it didn't inherit it from the theme). This means it'll use whatever color the underlying engine decides (if you pay close attention in your right screenshot, the color of `RichText()` is slightly "whiter" than `Text.rich()`).

By switching the `themeMode` to `light` instead of `dark`, I got this:

![image](https://github.com/flutter/flutter/assets/1278212/4bc27096-1e08-4a37-acf7-cacb855a55e5)

It turns out, if you don't specify a color, the text always defaults to black on the web, and white on other platforms.

The recommendation here is to always specify the style of your text. Either use `Text.rich()` so it inherits the styles from the theme, or if you use `RichText` you should specify any and all text styles that you care about.

**Comment by Gustl22** [comment]
Thanks for explaining. But it would be good to actively discourage developers from using `RichText` without styled components.

> The recommendation here is to always specify the style of your text. Either use Text.rich() so it inherits the styles from the theme, or if you use RichText you should specify any and all text styles that you care about.

Wouldn't it make sense to add a mechanism, to drop a warning (either in the editor, or while compiling), if a TextSpan has no style? This would protect from unintended styling. 

I can't imagine any use case where a developer wants that behavior.
