### ISSUE TITLE
when i build my project,the flutter will upload /ios/Runner/GeneratedPluginRegistrant.h  and android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistra to some unknow ip address

### ISSUE THREAD

**Issue by tiangaopan** [flutter/flutter#139467]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Create a flutter example project or any project could run normaly,and excute flutter run

### Actual results

The flutter will upload /ios/Runner/GeneratedPluginRegistrant.h  and android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistra to some unknow ip address.And sometimes will upload some .h file from third party package. So,why flutter appear these acitons?And if i could forbidden these actions?

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

It looks like everything is right.And no any useful infomation.

**Comment by darshankawar** [comment]
@tiangaopan 
It is not clear what exactly is the issue you are reporting. Please provide any console logs that might be useful to properly address the issue and elaborate on your use case you are trying to run.
If this is a question, please provide some visuals or supporting information that will help us to properly understand it.
