### ISSUE TITLE
Get main activity view to setOnTouchListener. 

### ISSUE THREAD

**Issue by 0xffffa** [flutter/flutter#139461]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I want to be able to listen on the touch listener from kotlin to have android specific native touch handling. However even when getting the main view with `findViewById<View>(android.R.id.content).getRootView().setOnTouchListener` the touch listener is never registered.

### Actual results

Nothing is happening, when the touch listener function should be called

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.16.2, on Ubuntu 22.04.3 LTS 6.2.0-37-generic,
    locale en_US.UTF-8)
    • Flutter version 3.16.2 on channel stable at
      /home/k/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9e1c857886 (4 days ago), 2023-11-30 11:51:18 -0600
    • Engine revision cf7a9d0800
    • Dart version 3.2.2
    • DevTools version 2.28.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/k/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+9-Ubuntu-122.04)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] VS Code (version unknown)
    • VS Code at /snap/code/current
    • Flutter extension version 3.78.0
    ✗ Unable to determine VS Code version.

[✓] Connected device (2 available)
    • moto g pure (mobile) • ZY22F48G5R • android-arm • Android 11 (API 30)
    • Linux (desktop)      • linux      • linux-x64   • Ubuntu 22.04.3 LTS
      6.2.0-37-generic

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories
```

</details>

**Comment by huycozy** [comment]
Hi @0xffffa 
In order to address the issue properly, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so that we may verify this. 

As this is related to native code, it would be better if you could provide it in a GitHub repository and please add license the code in the repository under some open-source license (e.g. MIT, Apache, BSD, GPL) so that we may look into it. Thank you!
