### ISSUE TITLE
Clipboard getData crashes when running from a flutter test

### ISSUE THREAD

**Issue by guyluz11** [flutter/flutter#139448]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Create a flutter test that the page calls in the initialize  `await Clipboard.getData('text/plain')` 

### Expected results

`Clipboard.getData` returns data or null while running in the test

### Actual results

The test crash with `<asynchronous suspension>`

It didn't crash while running on Linux outside of the test.

### Code sample

<details><summary>Code sample</summary>
This is not a full page with a call to `Clipboard.getData` in the initialization but it does not continue after the await Clipboard.getData and the error in the test is <asynchronous suspension> so probably the same case.

```dart
void main() {
  testWidgets('Clipboard getData works', (tester) async {
    await Clipboard.getData('text/plain');
    expect(1, 1);
  });
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: exactly one matching node in the widget tree
  Actual: _WidgetTypeFinder:<zero widgets with type "RemedyPage" (ignoring offstage widgets)>
   Which: means none were found but one was expected

When the exception was thrown, this was the stack:
#4      main.<anonymous closure>.<anonymous closure> (file:///home/guy/Documents/git/remepy/frontend/packages/widgets/test/remedy/remedy_routes_test.dart:295:7)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///home/guy/Documents/git/remepy/frontend/packages/widgets/test/remedy/remedy_routes_test.dart line 295
The test description was:
  From notification
════════════════════════════════════════════════════════════════════════════════════════════════════

Test failed. See exception logs above.
The test description was: From notification

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.9, on Ubuntu 23.04 6.2.0-37-generic, locale en_IL)
    • Flutter version 3.13.9 on channel stable at /home/guy/Programs/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (6 weeks ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/guy/Programs/Android/jdk/
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /snap/android-studio/128/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 15.0.7
    • cmake version 3.25.1
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[✓] Android Studio (version 2022.3)
    • Android Studio at /snap/android-studio/128/android-studio
    • Flutter plugin version 76.3.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version unknown)
    • VS Code at /snap/code/current
    • Flutter extension version 3.76.0
    ✗ Unable to determine VS Code version.

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 23.04 6.2.0-37-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 119.0.6045.159
    ! Device R5CRA086D6N is not authorized.
      You might need to check your device for an authorization dialog.

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @guyluz11 
I am unable to replicate the reported error using latest stable and master versions. Can you upgrade to same and run your scenario again to confirm if the error persists or not ?

**Comment by darshankawar** [comment]
Thanks for the update, but I am unable to replicate still. I see that you re on Linux, I am on mac, maybe that's a factor ?

**Comment by guyluz11** [comment]
The example code doesn't hangs forever?

```dart
void main() {
  testWidgets('Clipboard getData works', (tester) async {
    await Clipboard.getData('text/plain');
    expect(1, 1);
  });
}
```

I will check if I can find a way to test it on another os

**Comment by darshankawar** [comment]
Above does hang running on mac, but if possible, a code to replicate the crash would be helpful to properly make the issue actionable.

**Comment by rutvik-pieces** [comment]
I've a similar issue running on macOS with Flutter 3.13.6. Attempts to retrieve any clipboard data with `Clipboard.getData` hangs the test till it timeouts.

**Comment by rutvik-pieces** [comment]
I believe this is by design. `Clipboard` works with platform channels to copy/retrieve data from the system clipboard and testing for platform channels through widget tests isn't possible right now as far as I know. Thus the tests hang.
