### ISSUE TITLE
Flavor based translation / intl / arb

### ISSUE THREAD

**Issue by dleurs** [flutter/flutter#139476]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Hello.

How to get flavor-based intl translations ?

Indeed, my app is international. I use flavor to differenciate each country and environment, like dev_fr (dev for france), prod_fr, dev_ca (dev for canada) and prod_ca

I also use intl to generate translations :
```intl: ^0.18.1``` and ```context.translate.home_page_title``` inside my code

However, I could not find a way to generate specific country based .arb files

For now, I have inside my app : 
- app_en.arb
- app_fr.arb

But i would like to get differente translations country based, like this : 
- app_fr_fr.arb
- app_ca_fr.arb
- app_fr_en.arb
- app_ca_en.arb

For now, I created two folders /fr and /ca with each the two files ```app_en.arb```, ```app_fr.arb```, and I have a script that move these two files inside lib/l10n/arb. But I have to execute it manually before deploying or testing (if the current flavor inside lib/l10n/arb is not the good one), and it is also making testing more difficult as my script is sh

I did not write this inside intl because intl is dart based while my usecase is flutter based

### Proposal

Being able to launch a pre-script before running flutter run or build ? Or new options around flavor ?

**Comment by darshankawar** [comment]
Thanks for the report @dleurs 
Can you take a look at [this](https://github.com/dart-lang/i18n/issues/19) issue and [this](https://github.com/dart-lang/i18n/issues/19#issuecomment-1513210792) comment to see if it helps in your case or not ?

Also, since `intl` is a dart package, the proposal most probably need to be raised in dedicated repo.
