### ISSUE TITLE
[Impeller] Entity pass has hundreds of clips when rendering backdrop filter.

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#139493]
## reproduction code
```c++
TEST_P(AiksTest, GaussianBlurAtPeriphery) {
  Canvas canvas;

  canvas.Scale(GetContentScale());
  canvas.DrawRRect(Rect::MakeLTRB(0, 0, GetWindowSize().width, 100),
                   Point(10, 10), Paint{.color = Color::LimeGreen()});
  canvas.DrawRRect(Rect::MakeLTRB(0, 110, GetWindowSize().width, 210),
                   Point(10, 10), Paint{.color = Color::Magenta()});
  canvas.ClipRect(Rect::MakeLTRB(0, 50, GetWindowSize().width, 150));
  canvas.SaveLayer({.blend_mode = BlendMode::kSource}, std::nullopt,
                   ImageFilter::MakeBlur(Sigma(20.0), Sigma(20.0),
                                         FilterContents::BlurStyle::kNormal,
                                         Entity::TileMode::kClamp));
  canvas.Restore();

  ASSERT_TRUE(OpenPlaygroundHere(canvas.EndRecordingAsPicture()));
}
```

## observed result

The gpu frame debugger shows hundreds of clips being applied.

<img width="476" alt="Screenshot 2023-12-04 at 10 27 38 AM" src="https://github.com/flutter/flutter/assets/30870216/b7bf087b-d86f-46f4-af58-f349cab867a1">

## expected result
I expect only a couple of clip operations max, not hundreds.

## version
b87c1b32d55f9d8b258623241c98fc64495b4217

**Comment by jonahwilliams** [comment]
@gaaclarke probably related to the clip restore, if you want to sync up on this. In theory we should be reseting the state correctly, but perhaps this code is triggering something unexpected.

**Comment by gaaclarke** [comment]
I'm going to ignore it for now.  I got momentum on fixing this blur issue demonstrated in that test.  I don't think this is impeding me.

**Comment by jonahwilliams** [comment]
That is fine, I will try to repro this.

**Comment by gaaclarke** [comment]
I'm not seeing this anymore in c60b00a20fc3ddbb4f27807d17bba24df6e4366a, stencil then cover probably got rid of it if it still existed.
