### ISSUE TITLE
file.writeAsString('') writing [NULL][NULL][NULL] in file

### ISSUE THREAD

**Issue by sachinbpatil619** [flutter/flutter#139484]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

create a file, then dump all the data to another file by copy() method, and to truncate the current file call file.writeAsString('') or even truncate(0), it fails to truncate and the data written on the file will be replaced with [NULL].

### Expected results

file should be empty

### Actual results

file is filled with  [NULL][NULL][NULL][NULL][NULL][NULL][NULL][NULL][NULL][NULL][NULL][NULL]

### Code sample

<details><summary>Code sample</summary>

```dart
await file.writeAsString('');
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/flutter/flutter/assets/44753464/9aee61c0-f436-41c9-b634-5b905db2b043)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.16.2, on Microsoft Windows [Version 10.0.23595.1001], locale en-IN)
    • Flutter version 3.16.2 on channel stable at C:\Users\sachin\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9e1c857886 (4 days ago), 2023-11-30 11:51:18 -0600
    • Engine revision cf7a9d0800
    • Dart version 3.2.2
    • DevTools version 2.28.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\sachin\AppData\Local\Android\sdk
    • Platform android-34, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2023.1)
    • Android Studio at D:\Android Studio Preview
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10353782)

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] Connected device (4 available)
    • SM M215G (mobile) • RZ8R81NYF2E • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.23595.1001]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 119.0.6045.200
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 120.0.2210.49

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by huycozy** [comment]
Hi @sachinbpatil619 
Can you share the entire sample code? You have the flexibility to build upon this basic one and tailor it to your case.

<details>
<summary>Sample code</summary>

```dart
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('File Write Example'),
        ),
        body: Center(
          child: ElevatedButton(
            onPressed: () async {
              // Get the app's documents directory
              Directory appDocDir = await getApplicationDocumentsDirectory();
              String appDocPath = appDocDir.path;
              File file = File('$appDocPath/example.txt');
              await file.writeAsString('');
              print('String written to file successfully.');
            },
            child: const Text('Write to File'),
          ),
        ),
      ),
    );
  }
}

```
</details>

**Comment by sachinbpatil619** [comment]
@huycozy 

i have tried the same way as u have mentioned 

```
///
        String backupFileUrl = await getBackupLogFileURL();
        await file.copy(backupFileUrl);
        print("backup log file size after reset ${File(backupFileUrl).lengthSync()}");    
        await file.writeAsString('',mode: FileMode.write);

/// tried alternatively 
        File file2 = File(logFilePath);
        await file2.writeAsString('',mode: FileMode.write);

///tried truncate also
        RandomAccessFile raFile = await File(logFilePath).open(mode: FileMode.write);
        await raFile.truncate(0);
        await raFile.close();
```

**Comment by sachinbpatil619** [comment]
`import 'dart:io';
import 'dart:async';
import 'dart:math';
import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late String logFilePath;
  late String backupFilePath;
  final int maxSizeInBytes = 1024; // 1KB

  @override
  void initState() {
    super.initState();
    _initPaths();
  }

  Future<void> _initPaths() async {
    Directory appDocDir = await getApplicationDocumentsDirectory();
    logFilePath = appDocDir.path + "/logger.txt";
    backupFilePath = appDocDir.path + "/backup.txt";
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Log Rotation Example"),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: _writeToLogFile,
          child: Text("Write to Log"),
        ),
      ),
    );
  }

  Future<void> _writeToLogFile() async {
    try {
      File logFile = File(logFilePath);
      String logData = _generateRandomString();

      // Check if the log file exists
      if (!await logFile.exists()) {
        await logFile.create();
      }

      // Check if the log file exceeds the size limit
      await checkLogSizeAndUpdate();

      // Append the log data to the log file
      await logFile.writeAsString(logData, mode: FileMode.append);
    } catch (e) {
      print("Error writing to log file: $e");
    }
  }

  Future<void> checkLogSizeAndUpdate() async {
    File logFile = File(logFilePath);
    File backupFile = File(backupFilePath);
    
    print('checkLogSizeAndUpdate');
    int length = 0;
    length = await logFile.length();
    print(length);
    if (length >= maxSizeInBytes) {
      await logFile.copy(backupFile.path);
      print(logFile.lengthSync());
      logFile.writeAsStringSync("===LOG START===");
      print(logFile.lengthSync());
      print('backup added');
    } else {
      print('no backup stored');
    }
  }

  String _generateRandomString() {
    const String chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
    final Random random = Random();
    return String.fromCharCodes(
      List.generate(100, (index) => chars.codeUnitAt(random.nextInt(chars.length))),
    );
  }
}
`

Happenning in android need to test it on ios
