### ISSUE TITLE
WIP check in assets-for-api-docs doesn't ever start or report status.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#139413]
### Type of Request

bug

### Infrastructure Environment

Autosubmit and/or WIP check

### What is happening?

In this PR: https://github.com/flutter/assets-for-api-docs/pull/229 There is a "WIP" check that never reports its status.  I'm no longer allowed to commit PRs in that repo, and the `autosubmit` label just gets removed by the bot because the WIP check never reported status.

I've tried pushing an empty change to trigger the check again, but it doesn't seem to get triggered.

What can I do to unstick this?

### Expected results

I expect the WIP check to complete in a reasonable time.

**Comment by godofredoc** [comment]
WIP was being enforced during branch protection but the WIP app was removed from the flutter org. Removed WIP from branch protection.

Please rebase the PR to clear out the WIP status check.
