### ISSUE TITLE
Mac Phase 2 devicelab upgrades

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#139499]
### Is there an existing issue for this?

- [X] I have searched the [existing infra issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-infra)

### Type of Request

infra task

### Infrastructure Environment

Devicelab

### What is happening?

Please upgrade the following devicelab mac hosts to 13.6.x as part of phase2 in https://github.com/flutter/flutter/issues/134737 :

[staging pool] x86 iOS devicelab bots - Upgrade 1 bots to macOS 13 (2 / 3):
* [flutter-devicelab-mac-23](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-23)

[staging pool] arm64 iOS devicelab bots - Upgrade 1 bots to macOS 13 (3 / 5)
* [flutter-devicelab-mac-39](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-39)

 [staging pool] x86 msm8952 devicelab bots - Upgrade all to macOS 13 (1 / 1)
* [flutter-devicelab-mac-23](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-23)

 [staging pool] arm64 msm8952 devicelab bots - Upgrade 1 bots to macOS 13 (2 / 3)
* [flutter-devicelab-mac-34](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-34)

 [staging pool] x86 Pixel 7 Pro devicelab bots - Upgrade all to macOS 13 (1 / 1)
*  [flutter-devicelab-mac-13](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-13)

---

 [try pool] x86 iOS devicelab bots - Upgrade 1 bots to macOS 13 (2 / 3)
* [flutter-devicelab-mac-12](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-12)

 [try pool] arm64 iOS devicelab bots - Upgrade 1 bots to macOS 13 (2 / 3)
* [flutter-devicelab-mac-38](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-38)

 [try pool] x86 Pixel 7 Pro devicelab bots - Upgrade all to macOS 13 (1 / **1)**
* [flutter-devicelab-mac-19](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-19)

---

 [prod pool] x86 iOS devicelab bots - Upgrade 3 bots to macOS 13 (6 / 12)
* [flutter-devicelab-mac-7](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-7)
* [flutter-devicelab-mac-8](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-8)
* [flutter-devicelab-mac-9](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-9)

 [prod pool] arm64 iOS devicelab bots - Upgrade 1 bots to macOS 13 (2 / 4)
* [flutter-devicelab-mac-41](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-41)

 [prod pool] x86 msm8952 devicelab bots - Upgrade 1 bots to macOS 13 (2 / 4)
* [flutter-devicelab-mac-21](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-21)

### Steps to reproduce

Step 1:
Step 2:
..
Step n:

### Expected results

I expect to see X when Y is finished.

**Comment by yusuf-goog** [comment]
cc @vashworth

**Comment by vashworth** [comment]
Also, please ensure the following after each upgrade:

Delete any directories within `/opt/flutter/xcode` if applicable.

Also verify `/opt/flutter/xcode` is owned by swarming user.

Run `DevToolsSecurity` - should get response "Developer mode is already enabled."
If you don't get the message, run `sudo /usr/sbin/DevToolsSecurity -enable` to enable.

**Comment by kentnguyen99** [comment]
Upgrading macOS 13.6.1 to all Mac machines in this service ticket has been completed.  All Mac machines are online and ready for service.
