### ISSUE TITLE
======== Exception caught by gesture =============================================================== The following assertion was thrown while handling a gesture: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 4387 pos 12: '!_debugLocked': is not true.   Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause. In either case, please report this assertion by filing a bug on GitHub:

### ISSUE THREAD

**Issue by azamongithub** [flutter/flutter#139494]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1

### Expected results

The navigation is not working in my whole app

### Actual results

but i am getting this on every navigation try:

```
======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 4387 pos 12: '!_debugLocked': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
```

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
This is an issue with your code. See https://stackoverflow.com/a/55622474 for why this might be happening. 

You should check how you use the navigator in your code. 

Closing from here. 

If you still experience this issue after reading and applying the stackoverflow response and checking your usage of navigator, please provide a complete minimal reproducible code sample and I will reopen this issue. 

Thank you
