### ISSUE TITLE
Expose foreground property of TextStyle in Icon widget

### ISSUE THREAD

**Issue by evan361425** [flutter/flutter#139411]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I would like to make my icon's color change when background color changes. I realized that it can achieve by `BlendMode.different` from my own [SO question](https://stackoverflow.com/q/77420149/12089368).

I can do this in my local test with below code:

```dart
final style = TextStyle(
  foreground: Paint()
    ..blendMode = BlendMode.difference
    ..color = Colors.white,
  // other properties
);

TextSpan(text: String.fromCharCode(icon.codePoint), style: style);
```

https://github.com/flutter/flutter/assets/14554683/4c87f3ca-3a4e-41d1-bd14-4f9ae8f966f1

### Proposal

Expose the foreground property of `TextStyle` in [Icon](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/icon.dart) so that we can use it!

```dart
class Icon extends StatelessWidget {
  const Icon(
      this.icon, {
      this.foreground,
      // other properties
  })

  Widget build(context) {
    // ...
    TextStyle(
      forground: forground,
      // ...
    )
  }
}
```

Also tested on `IconButton`:

https://github.com/flutter/flutter/assets/14554683/88e50f0d-95fc-46d7-baf9-47dd78061252

**Comment by lukehutch** [comment]
I created the dup, #149066. I would love to see this change too, because it is needed (in combination with multiple differently-`Paint`-ed renderings of the same text using `Stack`) for font effects such as outlined text and text with blurred halo effects.

**Comment by evan361425** [comment]
@LongCatIsLooong I think it would be better to continue our discussion about `color` and `foreground` in the issue.

I see three possible directions:

1. Use `assert` to prevent developers from passing in both properties. However, developers would need to set the color themselves, for example:
```dart
final iconTheme = IconTheme.of(context);
final color = iconTheme.color.withOpacity(iconTheme.color.opacity * iconTheme.opacity);
final foreground = Paint()
  ..color = color
  ..blendMode = BlendMode.difference;
Icon(Icons.abc, foreground: foreground);
```

2. Allow the `color` value to override the `foreground` color. This needs to be documented for developers, making it less self-explanatory:
```dart
final foreground = Paint()
  ..color = Colors.red
  ..blendMode = BlendMode.difference;
// the final color will be `blue`
Icon(Icons.abc, color: Colors.blue, foreground: foreground);
```

3. Provide a constructor for `foreground`, but this would require additional discussion on which `Paint` properties to include. The reason for this approach, instead of letting developers pass in `Paint` directly, is that `Paint` has a default color, which brings us back to the initial issue: whether to use the paint's color or the icon's color, or if passing `null` should use the default color (from IconTheme). In summary, the new constructor might look like this:
```dart
Icon.foreground(
  // Our main attribute
  color: color,
  // Other Icon properties
  // Foreground properties
  isAntiAlias: isAntiAlias,
  blendMode: blendMode,
  style: style,
  strokeWidth: strokeWidth,
  strokeCap: strokeCap,
  strokeJoin: strokeJoin,
  strokeMiterLimit: strokeMiterLimit,
  maskFilter: maskFilter,
  filterQuality: filterQuality,
  shader: shader,
  colorFilter: colorFilter,
  imageFilter: imageFilter,
  invertColors: invertColors,
  fillType: fillType,
)
```

Personally, I support the second method. If I have missed or misunderstood anything, please help clarify!

If there are no other suggestions, I will respect reviewer LongCatIsLooong's opinion and proceed with the implementation of the third direction.

**Comment by lukehutch** [comment]
Another very simple solution would be to offer an `Icon.asText` method that simply returns the Icon as a Text object, also offering all the fields of Text in that method as overrides.

Personally I would also love to have a handful of static methods that would pull out the codepoint of an IconData as a String, along with its font daily etc. (I never realized that icons were just characters in a specific font until I looked at the code.)

However I on really needs to support all the fields of Text, simply for completeness, given that under the hood, it is just a Text widget.

**Comment by LongCatIsLooong** [comment]
@evan361425  my interpretation is that `color` is just be a shorthand for `foreground.color` (see also [TextStyle.color](https://main-api.flutter.dev/flutter/painting/TextStyle/color.html)). 
```dart
final foreground = Paint()
  ..color = Colors.red
  ..blendMode = BlendMode.difference;
// the final color will be `blue`
Icon(Icons.abc, color: Colors.blue, foreground: foreground);
```
Setting both `foreground` and `color` (the sample code above) is more often than not by mistake, and IMO that should be treated as an error like in `TextStyle`. 

Regarding verbosity: 
> However, developers would need to set the color themselves, for example:
```dart
final iconTheme = IconTheme.of(context);
final color = iconTheme.color.withOpacity(iconTheme.color.opacity * iconTheme.opacity);
final foreground = Paint()
  ..color = color
  ..blendMode = BlendMode.difference;
Icon(Icons.abc, foreground: foreground);
```

What happens if you take the second approach (letting `color` override `foreground.color`) here? Don't you still have to set the color if you want to change the blend mode? Since local configurations (i.e. widget parameters) always override theme configurations, I don't see how letting `color` override `foreground.color` would simplify this use case? 

> Provide a constructor for foreground

Alternatively you could introduce an `Either` type and make the parameter `Either<Color, Paint>`. Like adding a constructor, it's statically impossible to specify both `color` and `foreground` with that API, but it unfortunately breaks the current API.

**Comment by evan361425** [comment]
I totally understand what you means when you say

> should be treated as an error like in `TextStyle`.

The reason why we needed to add the default color from `IconTheme` when only given `foreground` is that `foreground` already has a default color (I remember it is `Colors.black`), which will overwrite the default color.

However, when we consider the `color` property as the only way to provide a color to the icon, we don't need to pass the default color from `IconTheme`. When `color` is `null`, the `Icon` already helps us extracts the correct color from `IconTheme`.

And this simplicity let me choose second method, although it is less self-explanatory.

**Comment by LongCatIsLooong** [comment]
> However, when we consider the color property as the only way to provide a color to the icon, we don't need to pass the default color from IconTheme. When color is null, the Icon already helps us extracts the correct color from IconTheme.

Ah do you mean that `color` will always be the source, even when it's not set and `foreground.color` is set to something different from the default `paint` color? 

> The reason why there are no warnings is that we cannot identify whether the color is passed by the developers or if it is just the default Paint color.

You can check in `build` that `foreground.color == Paint().color` right? Although it's a bit strange.

Honesty I don't think 
```dart
Icon(icon,
  foreground: Paint()
  ..blendMode = BlendMode.difference
  ..color = IconTheme.of(context).color,
)
```
is that much worse than
```dart
Icon(icon,
  foreground: Paint()
  ..blendMode = BlendMode.difference,
)
```
, if you really want theming support you could add that to `IconTheme`.

**Comment by evan361425** [comment]
> Ah do you mean that `color` will always be the source, even when it's not set and `foreground.color` is set to something different from the default `paint` color?

Yes.

Another consideration is `opacity`, the original calculation from `Icon` is more complex than:

```dart
final iconTheme = IconTheme.of(context);
final color = iconTheme.color.withOpacity(iconTheme.color.opacity * iconTheme.opacity);
```

Which I think is not simple for developers to retrieve `IconTheme` and calculate the opacity themselves.

Using original `Icon` provided `color` and `opacity` is quit intuitive for me.

**Comment by LongCatIsLooong** [comment]
> `Icon(icon, foreground: Paint()..color = Colors.black);`

I don't think `assert(foreground.color == Paint().color)` is going to produce a false positive.

> `opacity`

The API docs says 
> An opacity to apply to both explicit and default icon colors.

So the opacity should always be applied by the `Icon` widget no matter how the color is specified.

**Comment by evan361425** [comment]
OK.

If there are no other suggestions, I will implement the first method.

**Comment by evan361425** [comment]
I notice `IconButton` using `IconTheme.merge`:

```dart
IconTheme.merge(
  data: IconThemeData(
    size: effectiveIconSize,
    color: currentColor,
  ),
  child: icon,
)
```

In this case, developers are hard to pass the desired default color to `Icon` isn't it?

**Comment by LongCatIsLooong** [comment]
> I notice `IconButton` using `IconTheme.merge`:
> 
> ```dart
> IconTheme.merge(
>   data: IconThemeData(
>     size: effectiveIconSize,
>     color: currentColor,
>   ),
>   child: icon,
> )
> ```
> 
> In this case, developers are hard to pass the desired default color to `Icon` isn't it?

Do you have an example? `IconButton`'s constructors all take `color` as an argument?

**Comment by evan361425** [comment]
This is `IconButton` partial constructor in build:

```dart
IconTheme.merge(
  data: IconThemeData(
    size: effectiveIconSize,
    color: currentColor,
  ),
  child: icon,
)
```

and the `currentColor` come from:

```dart
Color? currentColor;
if (onPressed != null) {
  currentColor = color;
} else {
  currentColor = disabledColor ?? theme.disabledColor;
}
```

In my personal [use case](https://github.com/flutter/flutter/issues/139411#issue-2021829533), I only need `foreground` when using `IconButton`:

```dart
IconButton(
  onPressed: () {},
  icon: const Icon(icon, foreground: foreground),
)
```

In this case, it is really hard to provide correct color to it

**Comment by evan361425** [comment]
`IconButton`'s color come from `MaterialStateProperty` which including state `selected`, `hovered` and more.

In my personal [use case](https://github.com/flutter/flutter/issues/139411#issue-2021829533), I only need `foreground` when using `IconButton`:

```dart
IconButton(
  onPressed: () {},
  icon: const Icon(icon, foreground: foreground),
)
```

In this case, it is really hard to provide correct color to it

**Comment by LongCatIsLooong** [comment]
It seems `IconButton` creates an `IconTheme` as the parent of the `icon` widget the user supplies. So the `icon` widget could just be:
```dart
Builder((context) => Icon(icon, foreground: Paint()..blendMode = BlendMode.difference...color = IconTheme.of(context).color)
```
if you want to let the `IconButton` control the color?

**Comment by evan361425** [comment]
@LongCatIsLooong I've updated the PR, please help review it.

However I still think `foreground`'s color should be set by `color`, because in some cases like `Chip` It is tricky to set the correct color for it: https://github.com/flutter/flutter/blob/9473c8b5d168e1996711f61071d56e04abaa2dfe/packages/flutter/lib/src/material/chip.dart#L1296-L1302

**Comment by LongCatIsLooong** [comment]
> @LongCatIsLooong I've updated the PR, please help review it.
> 
> However I still think `foreground`'s color should be set by `color`, because in some cases like `Chip` It is tricky to set the correct color for it:
> 
> https://github.com/flutter/flutter/blob/9473c8b5d168e1996711f61071d56e04abaa2dfe/packages/flutter/lib/src/material/chip.dart#L1296-L1302
> 
> When we use `foreground`, we typically want to leverage its non-color properties (otherwise, we'd just use `color`). In this case, we don't think about moving the `color` property into `foreground`, or even putting the color from `IconTheme` into `foreground`. I understand your intention to make the two properties mutually exclusive to avoid confusion. However, in actual usage, some users are already accustomed to setting colors directly with `color` and `IconThemeData`. Changing this behavior could also lead to confusion.
> 
> From an intuitive usage perspective, I would still prefer that `foreground` handle non-color aspects, while the existing color settings remain as they are.

Yeah that makes sense. Maybe we should take a `blendMode` instead of the whole `paint`?

**Comment by evan361425** [comment]
It makes sense. I will update the PR this weekend.

**Comment by piedcipher** [comment]
@evan361425 since PR is merged, shall we close this issue?

**Comment by evan361425** [comment]
Ok, thanks a lot!
