### ISSUE TITLE
image_picker shows an html input file button on web browser

### ISSUE THREAD

**Issue by sebat94** [flutter/flutter#139442]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

**Easy to reproduce:**

1) Download the repository where I reproduced the bug ( https://github.com/sebat94/flutter_image_picker_bug )
2) Once the application is started, select an image by clicking the grey circle and then click on the link below that navigates to the next page.
3) On the next page you will see the bug.

_I am debugging my flutter app with chrome version: '119.0.0.0'_

**Note:** This bug was reported some time ago but was not resolved due to lack of evidence. ( [109782](https://github.com/flutter/flutter/issues/109782) )

### Expected results

You will see an html input file
![image](https://github.com/flutter/flutter/assets/15348083/e41a4bb0-fb71-42d3-b677-810e25447f0e)

### Actual results

When I select an image and redirect to a new page, an html input file appears on the new page.

I also tried a "pushReplacement"  just in case removing the previous Page from the stack made any difference, but that didn't work either.

**Interesting fact:** The input file appears in my web browser but does not exist in my widget tree.
![image](https://github.com/flutter/flutter/assets/15348083/f7648220-7579-471c-950d-56c9e4579f5c)

### Code sample

https://github.com/sebat94/flutter_image_picker_bug

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/15348083/70b3683c-ddbc-4e0d-9abc-40ac7901ddb3

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.8, on Microsoft Windows [Versi¢n 10.0.22621.2715], locale es-ES)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.5)
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.84.2)
[√] Connected device (3 available)
[√] Network resources

• No issues found!
```

</details>

**Comment by mdebbar** [comment]
The image picker package creates the file input but never removes it (see [here](
https://github.com/flutter/packages/blob/0b78be3c08c8078894c970004d936cb9c06c1f6d/packages/image_picker/image_picker_for_web/lib/image_picker_for_web.dart#L154-L161) if anyone is interested in tackling this 🙂)

**Comment by sebat94** [comment]
I see that the issue has been closed but the release couldn't be done due to an error on the tests.
Can you take a look at it? @Amir-P @ditman @mdebbar 

Thank you for your outstanding work, much appreciated.

![image](https://github.com/flutter/flutter/assets/15348083/982d8541-e7ef-4055-8dd0-f8921fd1daea)

**Comment by ditman** [comment]
> the release couldn't be done due to an error on the tests.

@sebat94 it got released a few hours later! thanks for letting us know! https://pub.dev/packages/image_picker_for_web/changelog#302

**Comment by sebat94** [comment]
> > the release couldn't be done due to an error on the tests.
> 
> @sebat94 it got released a few hours later! thanks for letting us know! https://pub.dev/packages/image_picker_for_web/changelog#302

Just one last question @ditman ,
will this fix be mirrored into the "image_picker" package?

I see that you provided that functionality some time ago:

![image](https://github.com/flutter/flutter/assets/15348083/d70427bd-5d2e-479e-9766-8020af49ba1d)

It would be great to have this fix mirrored also in the "image_picker" package so we don't need to switch between the "image_picker" package and the "image_picker_for_web" package if our app can run in both, mobile and web environments.

Thanks.

**Comment by ditman** [comment]
@sebat94 `image_picker` depends on `image_picker_web`. You should get the fix without any changes on your end. Just remember to do a `flutter pub upgrade` to ensure that you get the latest version of `image_picker_web`!

**Comment by sebat94** [comment]
> @sebat94 `image_picker` depends on `image_picker_web`. You should get the fix without any changes on your end. Just remember to do a `flutter pub upgrade` to ensure that you get the latest version of `image_picker_web`!

Brilliant! Thanks for clarifying it for me.

Works like a charm 🔥
Thank you for your efforts and keep up the good work!

**Comment by ditman** [comment]
You're welcome @sebat94! Also, thanks for your contribution, keep them coming!! 🙏
