### ISSUE TITLE
Listview builder with horizontal scroll direction is not working in flutter web

### ISSUE THREAD

**Issue by shibinnvc** [flutter/flutter#139562]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a Listviewbuilder.
2. Change the scroll direction to Axis.horizontal.

### Expected results

Able to scroll in the horizontal direction

### Actual results

Unable to scroll in the horizontal direction

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: SizedBox(
        height: 400,
        child: ListView.builder(
          scrollDirection: Axis.horizontal,
          itemCount: 14,
          itemBuilder: (context, index) => Container(
            margin: const EdgeInsets.all(30),
            height: 100,
            width: 100,
            color: Colors.red,
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here

https://github.com/flutter/flutter/assets/109967452/5f52c287-1433-48c8-aa3a-329841926972

]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
See https://docs.flutter.dev/release/breaking-changes/default-scroll-behavior-drag. 

Closing from here as there is documentation on how to achieve the drag scrolling behaviour on desktop platforms.
