### ISSUE TITLE
Can we / shouldn't we use Dart VM (GC) to auto manage non-Dart objects in 2023, inside a Flutter app?

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/flutter#139525]
Cross-posted from https://github.com/dart-lang/sdk/issues/54233. I post to Flutter as well, because if we are only talking about non-Flutter dart, then I guess the answer is "yes"; but for Flutter, especially Flutter Android/iOS, I am worried about the answer due to the limitation of memory on mobile devices.

**Comment by jonahwilliams** [comment]
Answered in dart tracker.
