### ISSUE TITLE
Unable to Close Camera by Clicking the 'X' Button

### ISSUE THREAD

**Issue by aagacek2** [flutter/flutter#139537]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Open the camera to capture an image
2. Attempt to close the camera without taking a photograph by clicking the 'X' button in the top left corner.

### Expected results

The camera closes.

### Actual results

The camera does not close.

### Code sample

<details><summary>Code sample</summary>

```dart
final XFile? photo = await _picker.getImageFromSource(source: ImageSource.camera)
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/95547587/d63f5a26-e16b-46d2-80eb-e6d7c618707c

</details>

### Logs

<details><summary>Logs</summary>

```console
No logs produced.
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.22621.2715], locale en-US)
    • Flutter version 3.10.6 on channel stable at C:\Users\aagacek2\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (5 months ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\aagacek2\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2022 17.2.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
    • Visual Studio Build Tools 2022 version 17.2.32526.322
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.84.2)
    • VS Code at C:\Users\aagacek2\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.78.0

[√] Connected device (4 available)
    • Pixel 7 Pro (mobile) • 29141FDH300AF8 • android-arm64  • Android 14 (API 34)
    • Windows (desktop)    • windows        • windows-x64    • Microsoft Windows [Version 10.0.22621.2715]
    • Chrome (web)         • chrome         • web-javascript • Google Chrome 119.0.6045.123
    • Edge (web)           • edge           • web-javascript • Microsoft Edge 119.0.2151.97

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment]
Hi @aagacek2 
I checked this on my device Realme 6, Android 11, it's still working as usual (can close camera preview screen). If you capture a picture and then close camera, will it work? 

If you're familiar with Android native development, it might be worth trying this out with native code, as this seems like a device-specific issue.

**Comment by aagacek2** [comment]
Thanks for the response @huycozy ! If I capture a picture, the camera closes as expected. Additionally, I can use on-screen gestures to go back and close the camera. It appears that it's only the 'X' button that isn't functional. This occurs for me on a Pixel 7 with Android 14. It's odd because the 'X' button that appears for the image picker when `_picker.getMultiImageWithOptions()` is executed behaves as expected, though I understand this does not use the camera and may not be an apt comparison.
I'll start looking into a native code approach, thank you for the tip.

**Comment by huycozy** [comment]
I also checked this on `Pixel 7, Android 14` but can't reproduce this. Please comment when you have more information for us. Thanks!
