### ISSUE TITLE
image_picker selects a large-resolution image that has been saved in the IOS mobile phone album. The Xfile file size information obtained does not match the information seen in the album. There is a big difference.

### ISSUE THREAD

**Issue by luoyajun0911** [flutter/flutter#139545]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1、Use the pickImage method in image_picker to debug on IOS mobile phone
2、Get file size
3、It was found that the size data was completely inconsistent with the image information displayed in the album.

### Expected results

The error between the image information obtained and the real data cannot be too large

### Actual results

It was found that the size data was completely inconsistent with the image information displayed in the album.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@luoyajun0911 
While capturing an image, what resolution and imageQuality are you passing ? 
Can you provide minimal reproducible code sample along with `flutter doctor -v` and plugin version being used ?
