### ISSUE TITLE
Touch events before first frame causes errors

### ISSUE THREAD

**Issue by xster** [flutter/flutter#13950]
```
Caught error: Cannot hit test a render box that has never been laid out.
The hitTest() method was called on this RenderBox:
  RenderCustomPaint#1b696 NEEDS-LAYOUT NEEDS-PAINT
Unfortunately, this object's geometry is not known at this time, probably because it has never been laid out. This means it cannot be accurately hit-tested. If you are trying to perform a hit test during the layout phase itself, make sure you only hit test nodes that have completed layout (e.g. the node's children, after their layout() method has been called).
Stack track: #0      RenderBox.hitTest.<anonymous closure> (package:flutter/src/rendering/box.dart:1838:11)
#1      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1861:6)
#2      RenderView.hitTest (package:flutter/src/rendering/view.dart:162:13)
#3      BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.hitTest (package:flutter/src/rendering/binding.dart:293:16)
#4      BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:86:7)
#5      BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
#6      BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
#7      _rootRunUnary (dart:async/zone.dart:1138)
#8      _CustomZone.runUnary (dart:async/zone.dart:1031)
#9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#10     _invoke1 (file:///Users/xiao/Development/engine/src/flutter/lib/ui/hooks.dart:136)
#11     _<…>
```

is thrown if the screen is touched before the engine calls beginFrame the first time. The screen's widgets are already built at that point but the entire render tree is still in NEEDS-LAYOUT NEEDS-PAINT state. 

The error isn't particularly useful. At best, the user touched the splash screen from his/her perspective and didn't really express intent to touch the widget that threw the error. 

The touch callback still crashes in release mode at https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/box.dart#L1861 since `_size` is null.

**Comment by Hixie** [comment]
o_O

How can they be built but not laid out? They get build and laid out in the same synchronous callback. I don't understand how this error can occur if you're using the widgets library (as opposed to if you're using the rendering library directly, in which case it's easy to accidentally do this).

**Comment by xster** [comment]
Not sure I understand it completely either :S. Though it happens on a blank flutter create project as well on android and ios. Doing more tests now.

**Comment by jason-simmons** [comment]
This can happen in the window between when SchedulerBinding.scheduleWarmUpFrame is called and when the tasks queued by scheduleWarmUpFrame execute.

At this point the PipelineOwner has a root node and the render object tree has been constructed under that root node, but the render objects do not yet know their sizes.  If pending pointer event handlers execute before the warm up frame is built, then the invocations of RendererBinding.hitTest will see the incomplete object tree.
