### ISSUE TITLE
IOS selects local album pictures. When the file is too large, the file size obtained does not match the actual size.

### ISSUE THREAD

**Issue by luoyajun0911** [flutter/flutter#139544]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

IOS selects local album pictures. When the file is too large, the file size obtained does not match the actual size.

### Proposal

IOS selects local album pictures. When the file is too large, the file size obtained does not match the actual size.

**Comment by huycozy** [comment]
Hi @luoyajun0911 
It seems you are reporting a bug. Please help to file another issue with a suitable issue template. 
- If you think this is a Flutter issue, please use [Report a bug](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml)
- If you think this is a Flutter's first-party package issue, please use [Report a bug in one of Flutter's first-party packages](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=9_first_party_packages.yml)

Closing. If you disagree, please write in the comments and I will reopen it.
