### ISSUE TITLE
Declaring both error and errorText is not supported. Event If i Give errorText as null.

### ISSUE THREAD

**Issue by AHDCraftsilicon** [flutter/flutter#139553]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

give error on input decoration and give errorText as null

### Expected results

not give error

### Actual results

give error
Declaring both error and errorText is not supported.
'package:flutter/src/material/input_decorator.dart':
Failed assertion: line 2623 pos 15: '!(error != null && errorText != null)'

### Code sample

```
decoration: InputDecoration(
        counterText: '',
        error: TextClass(textContent: widget.errorText??"", fontSize: 10, fontWeight: FontWeight.w400, textColor: colorFF0707),
        // errorText: widget.errorText,
        // errorStyle: const TextStyle(color: colorFF0707, fontFamily: "Poppins-Regular"),
        // errorMaxLines: 2,
        focusedBorder: const OutlineInputBorder(borderSide: BorderSide(color: colorE2E2E2)),
        enabledBorder: const OutlineInputBorder(borderSide: BorderSide(color: colorE2E2E2)),
        disabledBorder: const OutlineInputBorder(borderSide: BorderSide(color: colorE2E2E2)),
        errorBorder: const OutlineInputBorder(borderSide: BorderSide(color: colorE2E2E2)),
        focusedErrorBorder: const OutlineInputBorder(borderSide: BorderSide(color: colorE2E2E2)),
        isDense: true,
        fillColor: widget.readOnly == true ? colorF8F8F8 : color03AA59.withOpacity(0.05),
        filled: true,
        contentPadding: const EdgeInsets.fromLTRB(10, 10, 10, 10),
      ),

```
### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

not run

**Comment by darshankawar** [comment]
> Declaring both error and errorText is not supported.

This is WAI. See the [documentation](https://api.flutter.dev/flutter/material/InputDecoration/errorText.html) which states:

`Only one of [error](https://api.flutter.dev/flutter/material/InputDecoration/error.html) and [errorText](https://api.flutter.dev/flutter/material/InputDecoration/errorText.html) can be specified.`

Closing as not an issue.
