### ISSUE TITLE
Change Videos Dynamically

### ISSUE THREAD

**Issue by AALAMILLO** [flutter/flutter#139584]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Hi! i'm trying to change videos Dynamically but the package doesn´t have this feature =( any ideas? y try to do this:

Future<void> openMedia(String url) async{

    if(_videoController.value.isInitialized){
      await _videoController.dispose();
    }

    _videoController = VideoPlayerController.networkUrl(Uri.parse(url));
    await _videoController.initialize();

    return _videoController.play();

  }
  
  But it takes a lot of seconds to reinitialize!

### Proposal

An option like SETVIDEO.

**Comment by darshankawar** [comment]
@AALAMILLO 
I think your issue is same as https://github.com/flutter/flutter/issues/44690, so please follow-up in it for further updates.
Closing as duplicate.
