### ISSUE TITLE
Material 3 property missing [shapeAppearanceCornerSmall]

### ISSUE THREAD

**Issue by pks050505** [flutter/flutter#139559]
### Is there an existing issue for this?

- [x] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [x] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

.

### Expected results

d

### Actual results

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> /Users/idigitalpreneurpvtltd/.gradle/caches/transforms-3/8c04f28337ed37f4cc23b3101476ceaa/transformed/material-1.9.0/res/values/values.xml: Error: Can't determine type for tag '<macro name="m3_comp_assist_chip_container_shape">?attr/shapeAppearanceCornerSmall</macro>'

### Code sample

.

### Logs

Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
lib/main.dart:1
ERROR:/Users/idigitalpreneurpvtltd/.gradle/caches/transforms-3/8c04f28337ed37f4cc23b3101476ceaa/transformed/material-1.9.0/res/values/values.xml: Resource and asset merger: Can't determine type for tag '<macro name="m3_comp_assist_chip_container_shape">?attr/shapeAppearanceCornerSmall</macro>'

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> /Users/idigitalpreneurpvtltd/.gradle/caches/transforms-3/8c04f28337ed37f4cc23b3101476ceaa/transformed/material-1.9.0/res/values/values.xml: Error: Can't determine type for tag '<macro name="m3_comp_assist_chip_container_shape">?attr/shapeAppearanceCornerSmall</macro>'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
Exception: Gradle task assembleDebug failed with exit code 1

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.2, on macOS 14.1 23B74 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.74.3)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!

**Comment by pks050505** [comment]
in ios run correctly

**Comment by darshankawar** [comment]
@pks050505 
Check if [this](https://github.com/flutter/flutter/issues/124373#issuecomment-1500787053) helps to resolve the issue at your end or not.

**Comment by pks050505** [comment]
i have user latest version of kotlin version  according to android studio
https://kotlinlang.org/docs/releases.html#release-details
and got solved
ext.kotlin_version = '1.9.10'
