### ISSUE TITLE
bug: MenuAnchor does not close the menu when clicking outside with right click

### ISSUE THREAD

**Issue by Fernthedev** [flutter/flutter#139555]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Make a MenuAnchor. Second example in flutter docs which uses right click for open: https://api.flutter.dev/flutter/material/MenuAnchor-class.html
2. Open the menu
3. Right click outside the menu
4. Menu stays open

### Expected results

Menu should close on right click outside its area. This works with left click.

### Actual results

Menu stays open. This causes my app to have several contextual menus open simultaneously as each list element has its own MenuAnchor.

In my brief investigation, I found `TapRegion` is the widget handling the outside area close. This line checks only for the primary button, which then allows the menu to stay open on other mouse button events.

https://github.com/flutter/flutter/blob/d7d1572f37f365f7c5a41ac0be875cbec838c456/packages/flutter/lib/src/widgets/tap_region.dart#L237-L239

### Code sample

<details><summary>Code sample from flutter.dev</summary>

https://dartpad.dev/?id=1f43e84f2c6df2c5f97d72e73fa5c87d

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/flutter/flutter/assets/15272073/ef053493-36af-42c7-a873-c576aaac6117)

</details>

### Logs

N/A

### Flutter Doctor output

<details>
<summary>Flutter doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.2, on Pop!_OS 22.04 LTS 6.5.6-76060506-generic, locale
    en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] VS Code (version 1.84.2)
[✓] Connected device (1 available)
[✓] Network resources

! Doctor found issues in 2 categories.
```
</details>

**Comment by danagbemava-nc** [comment]
Hi @Fernthedev, on what platform(s) are you seeing this issue?

**Comment by Fernthedev** [comment]
Thanks for the quick response!
> Hi @Fernthedev, on what platform(s) are you seeing this issue?

I've seen the issue on Windows, Linux and web. I have not attempted:
- iOS
- MacOS
- Android

I believe this issue would occur on any platform, as it checks specifically for `kPrimaryButton` in `TapRegion`.

**Comment by Fernthedev** [comment]
I should also mention you should right click outside the `GestureDetector` widget as well to see the issue in the mentioned sample.

**Comment by danagbemava-nc** [comment]
Hi @Fernthedev, can you check on the master channel to see if you still experience this issue? It seems like it has been fixed. 

See the recordings below 

| master | stable | 
| -- | -- |
| <video src="https://github.com/flutter/flutter/assets/88313112/7b5518ac-292a-439a-a9b3-b789c8877cca" /> | <video src="https://github.com/flutter/flutter/assets/88313112/49e2a673-299f-4954-b9d7-0eb16ac7f180" /> |

**Comment by danagbemava-nc** [comment]
It has indeed been fixed on the master channel. It seems like there was another issue tracking this. See https://github.com/flutter/flutter/issues/136706. 

Closing from here as this has already been fixed. 

Thank you

**Comment by Fernthedev** [comment]
Can confirm it is resolved, thank you Flutter team <3
