### ISSUE TITLE
iOS Status bar icons are always white text when system theme is dark.

### ISSUE THREAD

**Issue by iampopal** [flutter/flutter#139557]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1) Create a simple app with only white text
2) Change the device system theme to dark
3) The ios status bar icon will change to white

4) try to force it with the following code to make the text black with statusBrBrightness Property
```
return Scaffold(
      appBar: AppBar(
        title: const Text('App Name'),
        systemOverlayStyle: SystemUiOverlayStyle(
          statusBarBrightness: Brightness.light,
        ),
      ),
   );
```

It will always be white in when device system theme is dak and this is issue

### Expected results

We want to change to keep only one light theme and do not want to support black theme so we expect our app status bar icons keep black always

### Actual results

status bar icons change to white when device theme is dark

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
abdurahmanpopal@Popals-MacBook-Air exact % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.2, on macOS 13.1 22C65 darwin-arm64, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.68.1)
[✓] VS Code (version 1.68.1)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 category.```

</details>

**Comment by andrewsheridan** [comment]
I have the same issue running flutter 3.16.0. Just updated my iOS emulators and XCode.

**Comment by darshankawar** [comment]
@iampopal 
I think you are hitting https://github.com/flutter/flutter/issues/77904 so please follow-up in it for further updates.
Closing this as a duplicate.
