### ISSUE TITLE
Camera rotating in 3 positions on diagonal its changing position

### ISSUE THREAD

**Issue by afaq3522** [flutter/flutter#139552]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

https://github.com/flutter/flutter/assets/136465577/a6050960-31fb-45d0-bcc3-e2e00ec611d9

### Expected results

It should be just on portrait and landscape mode

### Actual results

there are three orientations of camera i showing

### Code sample

  RotatedBox(
                  quarterTurns: quarterTurns(), child: _cameraPreviewWidget()),
            ),
  Widget _cameraPreviewWidget() {
    final CameraController? cameraController = controller;

    if (cameraController == null || !cameraController.value.isInitialized) {
      return const SizedBox.shrink();
    } else {
      return Listener(
        onPointerDown: (_) => _pointers++,
        onPointerUp: (_) => _pointers--,
        child: CameraPreview(
          controller!,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            return GestureDetector(
              behavior: HitTestBehavior.opaque,
              onScaleStart: _handleScaleStart,
              onScaleUpdate: _handleScaleUpdate,
              onTapDown: (TapDownDetails details) =>
                  onViewFinderTap(details, constraints),
            );
          }),
        ),
      );
    }
  }

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.16.2, on macOS 13.6.1 22G313 darwin-x64, locale en-GB)
    • Flutter version 3.16.2 on channel stable at /Users/xheenapps/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9e1c857886 (5 days ago), 2023-11-30 11:51:18 -0600
    • Engine revision cf7a9d0800
    • Dart version 3.2.2
    • DevTools version 2.28.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/xheenapps/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Connected device (3 available)
    • Xheen Apps’s iPhone (mobile) • 00008110-001C5D820EE3401E • ios            • iOS 16.2 20C65
    • macOS (desktop)              • macos                     • darwin-x64     • macOS 13.6.1 22G313 darwin-x64
    • Chrome (web)                 • chrome                    • web-javascript • Google Chrome 119.0.6045.199

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by huycozy** [comment]
Hi @afaq3522 
Could you share a complete & minimal sample code for this? Also, it will be more clear if you can take a screenshot of the 3rd orientation as you observed. Thank you!

**Comment by afaq3522** [comment]
> Hi @afaq3522 Is this issue only reproducible on iOS? Does it happen on Android?
> 
> Could you share a complete & minimal sample code for this? Also, it will be more clear if you can take a screenshot of the 3rd orientation as you observed. Thank you!

basically what i'm doing just using native sensor orientation package to sense orientation so in case if device's orientation is locked than i can rotate camera. I m just rotating preview with rotated box and lock orientation after rotation change
 void setOrientation(Orientation orientation) async {
    if (prankController.isRecordingStarted.isFalse) {
      this.orientation = orientation;
      // await Future.delayed(const Duration(milliseconds: 300));
      if (controller != null) {
        controller!.lockCaptureOrientation(orientation == Orientation.portrait
            ? DeviceOrientation.portraitUp
            : orientation == Orientation.landscapeRight
                ? DeviceOrientation.landscapeLeft
                : DeviceOrientation.landscapeRight);
      }
    }
  }
  this function calls when orientation sensor sense change in orientation.
  but the issue is that you know default behaviour of camera. on device rotation to landscape mode it make the video orientation landscape but video and its aspect ratio is not landscape video is still portrait.
so now issue is that on orientation change if it shows default behaviour like going to straight landscape then actual landscape after rotation

**Comment by afaq3522** [comment]
> Sorry, but I still don't understand your cases. Do you mean the camera preview is distorted when the device is rotated?
> 
> It would be clearer if you could take advantage of the [plugin demo app](https://github.com/flutter/packages/tree/main/packages/camera/camera/example) and break it down into separate issues (three "orientations" as mentioned)


https://github.com/flutter/flutter/assets/136465577/8f04f777-1d79-4bd8-ad10-e7ad0f14c387

now look that if i don't rotate widget of camera this is what happening in landscape mode. that's why i m rotating camera widget so that i can create video in landscape mode. you can see that without rotation on landscape mode camera orientation is not right.

**Comment by huycozy** [comment]
>now look that if i don't rotate widget of camera this is what happening in landscape mode.

Do you set device orientation as auto-rotate or fixed orientation (portrait/landscape)? What is your device mode?

I checked this using [plugin demo app](https://github.com/flutter/packages/tree/main/packages/camera/camera/example) on both Android and iOS. Below are results in two cases (as title), it doesn't look like the issue in your video above. 

<details>
<summary>Demo video (device orientation is in portrait)</summary>

| Android | iOS |
| --------------- | --------------- |
<video src="https://github.com/flutter/flutter/assets/104349824/52340191-3a36-4637-8051-2f2cb73163f1"/> | <video src="https://github.com/flutter/flutter/assets/104349824/61b169ed-023a-43ae-af84-73d00836a5fb"/>

</details> 

<details>
<summary>Demo video (device orientation is auto rotate)</summary>

| Android | iOS |
| --------------- | --------------- |
<video src="https://github.com/flutter/flutter/assets/104349824/2128172e-d541-4ae5-906f-cf88bd085159"/> | <video src="https://github.com/flutter/flutter/assets/104349824/8e58fef5-980d-4346-8f33-cda4d481ee43"/>

</details> 

Please also use [plugin demo app](https://github.com/flutter/packages/tree/main/packages/camera/camera/example) and confirm if you see the same behavior as mine. If you have a different case with your implementation, please share a complete minimal sample code.

**Comment by afaq3522** [comment]
> > now look that if i don't rotate widget of camera this is what happening in landscape mode.
> 
> Do you set device orientation as auto-rotate or fixed orientation (portrait/landscape)? What is your device mode?
> 
> I checked this using [plugin demo app](https://github.com/flutter/packages/tree/main/packages/camera/camera/example) on both Android and iOS. Below are results in two cases (as title), it doesn't look like the issue in your video above.
> 
> Demo video (device orientation is in portrait)
> Android	iOS
>  Record_2023-12-08-11-12-53_2088dbc85c3063e5c5d863d1c7dbeaa5.mp4 
>  RPReplay_Final1702009043.mp4 
> Demo video (device orientation is auto rotate)
> Android	iOS
>  android.mp4 
>  ios.mp4 
> Please also use [plugin demo app](https://github.com/flutter/packages/tree/main/packages/camera/camera/example) and confirm if you see the same behavior as mine. If you have a different case with your implementation, please share a complete minimal sample code.

i already know that thing but my scenerio is rotating camera and icons without device orientation means in case if device orientation is locked then too screen should rotate in landscape mode and video too should be with landscape aspect ratio same like native camera behaviour. i achieved that behaviour with a package native_device_orientation it sense orientation in every case like if device orientation is locked or unlocked
but you can see that in your demo if device orientation is portrait than video capture in  portrait and landscape both cases after capture video orientation will be potrait.
so due to overcome this issue you will require to rotate the widget.
below is sample code:
void setOrientation(Orientation orientation) async {
    if (prankController.isRecordingStarted.isFalse) {
      this.orientation = orientation;
      // await Future.delayed(const Duration(milliseconds: 300));
      if (controller != null) {
        controller!.lockCaptureOrientation(orientation == Orientation.portrait
            ? DeviceOrientation.portraitUp
            : orientation == Orientation.landscapeRight
                ? DeviceOrientation.landscapeLeft
                : DeviceOrientation.landscapeRight);
      }
    }
  }

  int quarterTurns() {
    return orientation == Orientation.landscapeLeft
        ? 1
        : orientation == Orientation.landscapeRight
            ? -1
            : 0;
  }

  @override
  Widget build(BuildContext context) {
    return NativeDeviceOrientedWidget(
      landscapeLeft: (context) {
        setOrientation(Orientation.landscapeLeft);
        return screen();
      },
      landscapeRight: (context) {
        setOrientation(Orientation.landscapeRight);
        return screen();
      },
      portraitUp: (context) {
        setOrientation(Orientation.portrait);
        return screen();
      },
      fallback: (_) {
        setOrientation(Orientation.portrait);
        return screen();
      },
      useSensor: true,
    );
  }
SizedBox(
              height: cameraHeight,
              width: double.infinity,
              child: RotatedBox(
                  quarterTurns: quarterTurns(), child: _cameraPreviewWidget()),
            ),
  Widget _cameraPreviewWidget() {
    final CameraController? cameraController = controller;

    if (cameraController == null || !cameraController.value.isInitialized) {
      return const SizedBox.shrink();
    } else {
      return Listener(
        onPointerDown: (_) => _pointers++,
        onPointerUp: (_) => _pointers--,
        child: CameraPreview(
          controller!,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            return GestureDetector(
              behavior: HitTestBehavior.opaque,
              onScaleStart: _handleScaleStart,
              onScaleUpdate: _handleScaleUpdate,
              onTapDown: (TapDownDetails details) =>
                  onViewFinderTap(details, constraints),
            );
          }),
        ),
      );
    }
  }
  Future<void> onNewCameraSelected(CameraDescription cameraDescription) async {
    if (controller != null) {
      return controller!.setDescription(cameraDescription);
    } else {
      return _initializeCameraController(cameraDescription);
    }
  }
late double cameraHeight;

  // Counting pointers (number of user fingers on screen)
  int _pointers = 0;

  @override
  void initState() {
    cameraHeight = Get.height;
    WidgetsBinding.instance.addObserver(this);
    onNewCameraSelected(AppConfig.cameras.first);
    Wakelock.enable();
    super.initState();
  }

**Comment by huycozy** [comment]
>if device orientation is locked then too screen should rotate in landscape mode and video too should be with landscape aspect ratio same like native camera behaviour. 

I also tried comparing device's native camera and Flutter plugin camera with [plugin demo app](https://github.com/flutter/packages/tree/main/packages/camera/camera/example) but they outputted the same result:

<details>
<summary>Demo video (native app vs Flutter app)</summary>

| Android device native app's camera | Flutter plugin app's camera |
| --------------- | --------------- |
<video src="https://github.com/flutter/flutter/assets/104349824/2a8c9b92-de3e-4c81-aa77-e066884c7f2f"/> | <video src="https://github.com/flutter/flutter/assets/104349824/276b4430-f127-4c8b-9362-f76179fecfec"/>

</details>

Please share your result with [plugin demo app](https://github.com/flutter/packages/tree/main/packages/camera/camera/example) so that we can make sure the issue is not caused by your implementation or 3rd plugins.

**Comment by afaq3522** [comment]
> > if device orientation is locked then too screen should rotate in landscape mode and video too should be with landscape aspect ratio same like native camera behaviour.
> 
> I also tried comparing device's native camera and Flutter plugin camera with [plugin demo app](https://github.com/flutter/packages/tree/main/packages/camera/camera/example) but they outputted the same result:
> 
> Demo video (native app vs Flutter app)
> Android device native app's camera	Flutter plugin app's camera
>  VID20231211121411.mp4 
>  REC2736796883047982484.mp4 
> Please share your result with [plugin demo app](https://github.com/flutter/packages/tree/main/packages/camera/camera/example) so that we can make sure the issue is not caused by your implementation or 3rd plugins.

just one thing more check please after recording video then check result of video native and flutter plugin camera in rotation mode

**Comment by huycozy** [comment]
>just one thing more check please after recording video then check result of video native and flutter plugin camera in rotation mode

I assume `rotation mode` here means "device orientation is unlocked". I checked this and see the same result between native camera and Flutter camera apps:

<details>
<summary>Demo video in rotation mode (native app vs Flutter app)</summary>

| Android device native app's camera | Flutter plugin app's camera |
| --------------- | --------------- |
<video src="https://github.com/flutter/flutter/assets/104349824/2a8c9b92-de3e-4c81-aa77-e066884c7f2f"/> | <video src="https://github.com/flutter/flutter/assets/104349824/26790db3-664e-4af4-94fe-89c94816ce9b"/>

</details>
