### ISSUE TITLE
[CP] have `Java.version` return null if `java --version` fails or cannot be run

### ISSUE THREAD

**Issue by andrewkolos** [flutter/flutter#139699]
### Issue Link

https://github.com/flutter/flutter/issues/139180

### Commit Hash

c22c19b

### Target

stable

### PR Link

https://github.com/flutter/flutter/pull/139698

### Changelog Description

Fixes `flutter` tool crash that can occur during `flutter create` when Flutter is unable to run Java. 

### Impacted Users

All Flutter devs that create Android-enabled projects

### Impact Description

`flutter create` crashes with a vague error message stating that `<some path here>/java` could not be found.

### Workaround

Users will have to troubleshoot their Java installation. They can start with `flutter doctor -v`, which will print a validation failure when `java` cannot be run.

### Risk

low

### Test Coverage

yes

**Comment by CaseyHillers** [comment]
Released in 3.16.4
