### ISSUE TITLE
Possible over-complication in Navigator docs

### ISSUE THREAD

**Issue by IljaDaderko** [flutter/flutter#13965]
I was trying to get custom route animation going following navigator docs: https://docs.flutter.io/flutter/widgets/Navigator-class.html

They use `transitionBuilder`, but to my understanding 

```dart
pageBuilder: (BuildContext context, Animation<double> animation, Animation<double> secondaryAnimation)
```

Can produce needed animation values as well? At least I was able to wrap pageBuilder's child in animation widgets and use those values to perform same animation and it seems much cleaner. This raised question, why do we even need `transitionBuilder` in `PageRouteBuilder` widget? My sense of flutter docs in general right now is that there are so many ways to do one thing, docs show one way, when I view commented documentation in intelij, there seems to be a better way. Its very complex for beginner to get into this without spending several hours figuring something like this out.

I feel like if there is one way to achieve something there shouldn't be another?

This is full code I was able to use to replicate example from navigator and now when I did it like this, I have no clue why `transitionsBuilder` is needed:

```dart
return new PageRouteBuilder(
      opaque: true,
      pageBuilder: (BuildContext context, Animation<double> animation, _) {
        return new FadeTransition(
          opacity: animation,
          child: new RotationTransition(
            turns: new Tween<double>(begin: 0.5, end: 1.0).animate(animation),
            child: route,
          ),
        );
      });
```

**Comment by Hixie** [comment]
The reason for using transitionsBuilder is that it's more efficient, because then you only rebuild the transitions when they animate, not the whole page. You can certainly structure the code such that the same is true with the other pageBuilder, of course.

**Comment by darshankawar** [comment]
Hi @IljaDaderko,
Does [this](https://github.com/flutter/flutter/issues/13965#issuecomment-363275403) answer your question ? Can this issue be closed ?
Thanks

**Comment by darshankawar** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
