### ISSUE TITLE
Invalid constant value

### ISSUE THREAD

**Issue by YuInseo** [flutter/flutter#139622]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Hi guys, I just learned dart language and 
I am confusing how to use variable to parameter's value 

How can I use variable on parameter's value? 

Here's my code

```dart
class InputText extends StatelessWidget
{


  final String name;

  const InputText({super.key, required this.name})


  @override
  Widget build(BuildContext context) {


    return const Column(
      children: [

        TextField(

          decoration: InputDecoration(
            border: UnderlineInputBorder(),
            hintText: name
          ),
        )
      ],
    );
  }
}
```

### Actual results

lib/components/input_text.dart:21:23: Error: Undefined name '_hint'.
            hintText: _hint
                      ^^^^^

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by bastislack** [comment]
To make it work, add a semicolon after the constructor body: `const InputText({super.key, required this.name});`.

And remove the const keyword in your return statement: `return Column(`

In order to make the `Column` a `const` Widget, you would have to declare `name` as `static const` and initialize it with a value like this: `static const String name = 'test';`

Hope that helps :)

**Comment by danagbemava-nc** [comment]
Kindly follow the tips in https://github.com/flutter/flutter/issues/139622#issuecomment-1842502755. 

Closing from here as this is not a flutter issue. 

In the future, please post such questions on stackoverflow. 

Thank you
