### ISSUE TITLE
[Flutter gallery] animation section's background color should be picked from the Theme

### ISSUE THREAD

**Issue by lokeshj** [flutter/flutter#13962]
https://github.com/flutter/flutter/blob/c3fab029c242fa6401d9d7939ab685c3c81b6ee9/examples/flutter_gallery/lib/demo/animation/widgets.dart#L160

It should probably be 
```dart
      decoration: new BoxDecoration(color: Theme.of(context).backgroundColor),
```

The text is unreadable otherwise when `dark` mode is selected in the drawer. Is this a real issue? Can i submit a PR for this if yes?

**Comment by Hixie** [comment]
cc @HansMuller

**Comment by markusaksli-nc** [comment]
Closing since this is no longer relevant here.
