### ISSUE TITLE
Issue with Autofillhint for Credit Card Information on iOS

### ISSUE THREAD

**Issue by rutulchauhan** [flutter/flutter#139682]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run the command flutter run on the provided code sample using an iOS device.
2. Navigate to and enter the creditcardNumber text field.

Additionally, the "well-known/apple-app-site-association" file has been uploaded and verified as part of this setup.

### Expected results

Should show suggestions to autofill existing saved card details.

### Actual results

None of any saved card showing as suggestion on keyboard when focus on credit card field.

### Code sample

<details><summary>Code sample</summary>

AutofillGroup(
child: TextFormField(
                                                  onChanged: (v) {
                                                  },
                                                  autofillHints: const <String>[AutofillHints.creditCardName],
                                                  controller: _nameController,
                                                  keyboardType: TextInputType.name,
                                                  textInputAction: TextInputAction.next,
                                                  cursorColor: AppColor.appColor,
                                                  style: TextStyle(
                                                    fontSize: 16,
                                                  ),
                                                  textAlign: TextAlign.start,
                                                  decoration: InputDecoration(
                                                      contentPadding: EdgeInsets.all(10),
                                                      focusedBorder: OutlineInputBorder(
                                                        borderRadius: BorderRadius.circular(10),
                                                        borderSide: BorderSide(color: AppColor.appColor, width: 2.0),
                                                      ),
                                                      enabledBorder: OutlineInputBorder(
                                                        borderRadius: BorderRadius.circular(10),
                                                        borderSide: BorderSide(color: Colors.grey, width: 1.0),
                                                      ),
                                                      hintStyle: TextStyle(
                                                        fontSize: 16,
                                                      )),
                                                ),
)

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.9, on macOS 13.6 22G120 darwin-arm64, locale
    en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.84.2)
[✓] Connected device (2 available)
    ! Error: Browsing on the local area network for Rutul’s iPhone. Ensure the
      device is unlocked and attached with a cable or associated with the same
      local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)
[✓] Network resources

</details>

**Comment by huycozy** [comment]
>and if you want to add card just go to settings -> Safari -> Autofill and add card details there.

I tried it but I think it's for Web platform, right? 

For iOS app, I think it should be in `Settings > Passwords` but it seems it only stores passwords there. Please correct me if I'm wrong, I mainly use Android OS. It would be helpful if you can share some apps that already work on iOS so that I can try.

Also, I see you set `AutofillHints.creditCardName` for TextFormField but you enter `creditcardNumber`, does it work if you start entering card name instead?
