### ISSUE TITLE
Re-enable assorted_layout_widgets tests

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#139610]
Basically, comment the following line back in and make it pass:

https://github.com/flutter/tests/blob/2e742c62f42e9b33a6d44d0f7b7511ed96f3e5cd/registry/assorted_layout_widgets.test#L6

**Comment by Hixie** [comment]
Upstream fixes: https://github.com/marcglasberg/assorted_layout_widgets/pull/30
