### ISSUE TITLE
Tv Dpad centre button not working on all the custom widgets

### ISSUE THREAD

**Issue by SmartQ-Rohit** [flutter/flutter#139631]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Shortcuts(
        shortcuts: <LogicalKeySet, Intent>{
          LogicalKeySet(LogicalKeyboardKey.arrowUp): UpIntent(),
      LogicalKeySet(LogicalKeyboardKey.arrowDown): DownIntent(),
      LogicalKeySet(LogicalKeyboardKey.arrowLeft): LeftIntent(),
      LogicalKeySet(LogicalKeyboardKey.arrowRight): RightIntent(),
      LogicalKeySet(LogicalKeyboardKey.accept): ActivateIntent(),
        },

### Expected results

It should navigate properly to each clickable widgets and centre button of Dpad remote should consider as click event of that widget

### Actual results

navigator not happening properly in custom widgets and centre button not working.

### Code sample

<details><summary>Code sample</summary>

```dart
Shortcuts(
        shortcuts: <LogicalKeySet, Intent>{
          LogicalKeySet(LogicalKeyboardKey.arrowUp): UpIntent(),
      LogicalKeySet(LogicalKeyboardKey.arrowDown): DownIntent(),
      LogicalKeySet(LogicalKeyboardKey.arrowLeft): LeftIntent(),
      LogicalKeySet(LogicalKeyboardKey.arrowRight): RightIntent(),
      LogicalKeySet(LogicalKeyboardKey.accept): ActivateIntent(),
        },
        child: MaterialApp(
          showSemanticsDebugger: false,
          theme: ThemeData(),
          debugShowCheckedModeBanner: false,
          onGenerateRoute: AppRoutes.onGeneratedRoute,
          initialRoute: initialRoute,
        ),
      )
```
</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

[✓] Flutter (Channel stable, 3.13.1, on macOS 14.1.1 23B81 darwin-arm64, locale en-IN)
    • Flutter version 3.13.1 on channel stable at /Users/Rohit.Pachori/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e1e47221e8 (4 months ago), 2023-08-22 21:43:18 -0700
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/Rohit.Pachori/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_SDK_ROOT = /Users/Rohit.Pachori/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (3 available)
    • sdk google atv64 amati arm64 (mobile) • emulator-5556 • android-arm64  • Android 12 (API 31) (emulator)
    • macOS (desktop)                       • macos         • darwin-arm64   • macOS 14.1.1 23B81 darwin-arm64
    • Chrome (web)                          • chrome        • web-javascript • Google Chrome 119.0.6045.199

[✓] Network resources
    • All expected network resources are available.

</details>

**Comment by huycozy** [comment]
Hi @SmartQ-Rohit 
>centre button not working

This doesn't seem to be supported yet, please check https://github.com/flutter/flutter/issues/1670.

>navigator not happening properly in custom widgets

Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Thanks!
