### ISSUE TITLE
intellij 2023.3 flutter plugin 

### ISSUE THREAD

**Issue by xtien** [flutter/flutter#139670]
My Intellij IDE updated to 2023.3, now the Flutter plugin stopped working because it requires an older version of Intellij. Will there be an updated plugin? Or do I need to revert the Intellij update?

**Comment by danagbemava-nc** [comment]
Closing this in favour of https://github.com/flutter/flutter-intellij/issues/7113. 

PS: the IntelliJ plugin for flutter lives in a different repo with its own issue tracker so issues related to it should be reported over there.

**Comment by davidnwaneri** [comment]
I think this issue is a different issue from https://github.com/flutter/flutter-intellij/issues/7113
I solved it though by installing a new and required plugin called "Android"

https://plugins.jetbrains.com/plugin/22989-android
