### ISSUE TITLE
Flutter doesn't update the code changes on Android device

### ISSUE THREAD

**Issue by stoichoandreev** [flutter/flutter#13968]
Hi Flutter team. First of all well done for the good work with Flutter 👍 .

I am working on new application and I decided to build it with Flutter. Everything was good until one day I saw that when I change something inside the code, on Android device the change doesn't apply at all. On iOS device (simulator) everything works perfect, but on Android doesn't work at all. At the beginning when I started it was fine, but after that I decide to include SharedPreferences plugin inside the app and the application updates on Android stop working. I am not sure does the new Plugin did something, but no matter what I do, the source code updates don't apply. I have tried with Android native simulator (with Google play service) and real device, but when the app runs I see the same view. I have tried to update simple button text and I still see the old text. I have tried also to update some of the application screens, but again without success. It seems like the app state was saved at some point and every time when I run the project I see that state (it does not accept any changes). This is super strange, because if I use iOS simulator everything works. For the development I am using Intellij IDE:
<img width="643" alt="screen shot 2018-01-07 at 19 08 41" src="https://user-images.githubusercontent.com/7113524/34653049-4468cacc-f3de-11e7-8911-ee72b80a9276.png">
When I run flutter doctor -v I get this output:
`[  +18 ms] [/Users/sniper/Library/Flutter/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +36 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/alpha
[        ] [/Users/sniper/Library/Flutter/flutter/] git rev-parse --abbrev-ref HEAD
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] alpha
[        ] [/Users/sniper/Library/Flutter/flutter/] git ls-remote --get-url origin
[  +11 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [/Users/sniper/Library/Flutter/flutter/] git log -n 1 --pretty=format:%H
[  +21 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 8f65fec5f5f7d7afbb0965f4a44bdb330a28fb19
[        ] [/Users/sniper/Library/Flutter/flutter/] git log -n 1 --pretty=format:%ar
[  +11 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 4 weeks ago
[ +155 ms] /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[  +58 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[        ] 3.0
[ +601 ms] [✓] Flutter (on Mac OS X 10.13.2 17C88, locale en-GB, channel alpha)
[        ]     • Flutter at /Users/sniper/Library/Flutter/flutter
[        ]     • Framework revision 8f65fec5f5 (4 weeks ago), 2017-12-12 09:50:14 -0800
[        ]     • Engine revision edaecdc8b8
[        ]     • Tools Dart version 1.25.0-dev.11.0
[        ]     • Engine Dart version 2.0.0-edge.d8ae797298c3a6cf8dc9f4558707bd2672224d3e
[   +6 ms] /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[  +48 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[        ] 3.0
[  +87 ms] java -version
[  +74 ms] [✓] Android toolchain - develop for Android devices (Android SDK 27.0.2)
[        ]     • Android SDK at /Users/sniper/Library/Android/sdk
[        ]     • Android NDK at /Users/sniper/Library/Android/sdk/ndk-bundle
[        ]     • Platform android-27, build-tools 27.0.2
[        ]     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
[        ]     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
[+1009 ms] DevToolsSecurity -status
[  +38 ms] Developer mode is currently enabled.
[        ] python -c import six
[  +64 ms] idevice_id -h
[   +6 ms] idevice_id -h
[   +5 ms] idevice_id -l
[  +14 ms] ideviceinstaller -h
[  +10 ms] ios-deploy --version
[  +27 ms] ios-deploy --version
[  +23 ms] 1.9.2
[        ] ios-deploy --version
[  +48 ms] ios-deploy --version
[  +21 ms] 1.9.2
[   +6 ms] pod --version
[ +728 ms] pod --version
[ +662 ms] 1.3.1
[   +2 ms] pod --version
[ +715 ms] 1.3.1
[        ] [✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[        ]     • Xcode at /Applications/Xcode.app/Contents/Developer
[        ]     • Xcode 9.2, Build version 9C40b
[        ]     • ios-deploy 1.9.2
[        ]     • CocoaPods version 1.3.1
[   +1 ms] [✓] Android Studio (version 3.0)
[        ]     • Android Studio at /Applications/Android Studio.app/Contents
[        ]     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
[   +1 ms] /usr/bin/defaults read /Applications/IntelliJ IDEA CE.app/Contents/Info CFBundleShortVersionString
[  +69 ms] Exit code 0 from: /usr/bin/defaults read /Applications/IntelliJ IDEA CE.app/Contents/Info CFBundleShortVersionString
[        ] 2017.2.6
[  +72 ms] [✓] IntelliJ IDEA Community Edition (version 2017.2.6)
[        ]     • Flutter plugin version 20.0.2
[        ]     • Dart plugin version 172.4343.25
[   +3 ms] /Users/sniper/Library/Android/sdk/platform-tools/adb devices -l
[  +20 ms] Exit code 0 from: /Users/sniper/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:2
[  +23 ms] idevice_id -h
[  +31 ms] /usr/bin/xcrun simctl list --json devices
[ +137 ms] /Users/sniper/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop
[  +45 ms] ro.hardware = ranchu
[   +2 ms] [✓] Connected devices
[        ]     • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)
[  +26 ms] "flutter doctor" took 4,772ms.
[  +33 ms] ensureAnalyticsSent: 31ms
[   +9 ms] exiting with code 0`

Please let me know if you need some other information about installed Android SDK version etc.

Thanks.

**Comment by Gogetter** [comment]
Hi @stoichoandreev, I noticed this recently. And re-building project via `Build > Rebuild Project` on intelliJ fixes code change (for example repositioning of widget) issue for android devices. 
Not exactly sure if its an issue with the flutter intelliJ plugin though(?). Hope this sorts this for you.

**Comment by mravn-google** [comment]
@stoichoandreev This could be because your Flutter project is still using Gradle 3.x, but you have included the newest version of the SharedPreferences plugin, which requires Gradle 4.x.

In that case you should see a Gradle-related build error on Android, if you execute `flutter run` in a terminal. The error should include something like the following:
```text
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/mravn/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.3.0/android/build.gradle' line: 6

* What went wrong:
A problem occurred evaluating project ':shared_preferences'.
> Could not find method google() for arguments [] on repository container.
```
If this happens, your Android project is not getting rebuilt, which explains why you don't see code changes reflected.

To solve the problem, you should either downgrade your dependency on SharedPreferences to 0.2.6 or update your Flutter project to Gradle 4.x as described [here](https://github.com/flutter/flutter/wiki/Updating-Flutter-projects-to-Gradle-4.1-and-Android-Studio-Gradle-plugin-3.0.1)

**Comment by stoichoandreev** [comment]
@Gogetter , @mravn-google thank you for your answers. 
@mravn-google was absolutely right! In the moment when I updated my build gradle tool version from 3.0.1 to 4.0.1, the project start working again on Android. The issue was that **google()** can't be found on Gradle 3.0.1 and I remember that I added **google()** manually in the project, but I forgot to update the Gradle version. As I know if you want to add google repository to the Android build system, you need to use the url to that repository (if you know it) or if you use the latest Gradle you can just use **google()** .
I remember that I did the pods update on XCode, but I forgot to update the Gradle version. The strange thing is that I did not see the error about 

`Could not find method google() for arguments [] on repository container.` and the project was looking like successful builded and installed for me, that's why I was confused.

Once again, thanks @mravn-google for your help.
This issue could be closed.

**Comment by mravn-google** [comment]
Closed per above comment.

**Comment by jay3112000** [comment]
I had the same problem try Hot Restart in flutter console it worked for me
