### ISSUE TITLE
Platform code in flutter/engine needs a testing harness

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#13964]
As discussed (briefly) in https://github.com/flutter/engine/pull/4491 we need a way to write tests for platform specific code in the engine repo. @Hixie probably has a rough idea of how this should be done so I am creating this placeholder issue for it.

**Comment by Hixie** [comment]
I don't know if Java makes this more complicated than other languages, but for Dart, all we do is just have some dart files that we run from `run_tests.sh`, and for C++, all we do is have some targets that get built that we then run from `run_tests.sh`.

**Comment by cbracken** [comment]
We now have a test harness for Android code, for iOS code, and for the embedding API  (aside from the unittests coverage). There's still more to do, but I we should file more specific bugs for any remaining gaps.
