### ISSUE TITLE
Flutter web custom background notification

### ISSUE THREAD

**Issue by amrgetment** [flutter/flutter#139657]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1- Follow flutter messaging tutorial to make integrate Flutter and Firebase messaging
2- Go to the background
2- Send notification from Firebase
3- Add a custom icon image to the notification and send again

### Actual results

Notifications shows as expected but the image icon is not show but the chrome icon
![image](https://github.com/flutter/flutter/assets/149420647/ebc4654d-a0f4-40b8-9d5c-b1035f49c6cd)

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.16.1, on macOS 14.1 23B74 darwin-x64, locale
    en-EG)
    • Flutter version 3.16.1 on channel stable at /Users/apple/.pvotal/flutter
    • Upstream repository ssh://git@github.com/flutter/flutter.git
    • Framework revision 7f20e5d18c (9 days ago), 2023-11-27 09:47:30 -0800
    • Engine revision 22b600f240
    • Dart version 3.2.1
    • DevTools version 2.28.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Community Edition (version 2023.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.10248

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 119.0.6045.199

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by amrgetment** [comment]
if I override the messaging on my firebase service js (firebase-messaging-sw.js) file it show the default notification and the custom notification


firebase-messaging-sw.js
```
// Necessary to receive background messages:
const messaging = firebase.messaging();

// Optional:
messaging.onBackgroundMessage((payload) => {
    console.log("onBackgroundMessage", payload);

    const { title, body, image } = payload.notification ?? {};
    console.log("onBackgroundMessage title", title);
    console.log("onBackgroundMessage body", body);
    console.log("onBackgroundMessage image", image);

    if (!title) {
        return;
    }
    console.log("onBackgroundMessage Make sure macOS allow chrome to show notification from macOS settings/notifications/chrome");

    self.registration.showNotification(title, {
        body,
        icon: image || '/icons/Icon-192.png',
    });
});
```

**Comment by amrgetment** [comment]
I found that I should use the same image url as my domain, I wonder how Could I test in localhost? and if possible make messaging.onBackgroundMessage in my js file override the default message and not show twice?

_CORS: Note that if the image URL is hosted on a different server than the Firebase server, the image server must comply with CORS policies. Otherwise, the image cannot be uploaded by Firebase and displayed in the notification. Check the image server's CORS policies and edit if necessary._

**Comment by amrgetment** [comment]
I tried to use the image from the same domain but still the same result

**Comment by darshankawar** [comment]
@amrgetment 
I think this should be reported in flutterfire repo, as you are looking to have an image in your push notification.
Closing from here. If you disagree, write in comments and I'll reopen it.

**Comment by amrgetment** [comment]
@darshankawar thanks,
I open it here
https://github.com/firebase/flutterfire/issues/11985
