### ISSUE TITLE
Regression in flutter_gallery iOS release size

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#139605]
On the PR here https://github.com/flutter/flutter/pull/139203 from @Hixie that rolled some pub deps forward, SkiaPerf is reporting a ~13MB regression in the iOS release size of the flutter_gallery. 

https://flutter-flutter-perf.skia.org/e/?begin=1699661770&end=1701816185&keys=X002a387933ee8947522cae13fbd696c3&requestType=0&selected=commit%3D38182%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253Drelease_size_bytes%252Ctest%253Dflutter_gallery_ios__compile%252C&xbaroffset=38181

Is this intentional or a benign side-effect of rolling the dependencies forward?

**Comment by Hixie** [comment]
Potential sources:
- shrine_images rolled from 2.0.1 to 2.0.2
- video_player moved from 2.2.11 to 2.8.1, a significant change

nothing else looks suspicious.

**Comment by Hixie** [comment]
shrine_images is unlikely to be the problem, the [only change](https://github.com/material-components/material-components-flutter-codelabs-packages/commit/81bcf05e3c5307497093e45490db43ecebf6988a) there was a trivial SDK version bump.

**Comment by Hixie** [comment]
@stuartmorgan any idea if bumping video_player that much (2.2.11 to 2.8.1) could be the cause of a ~13MB regression in iOS release size on flutter_gallery?

**Comment by jason-simmons** [comment]
https://github.com/flutter/flutter/pull/139203 updated Gallery's version of the `url_launcher_ios` plugin.

The new version of `url_launcher_ios` includes Swift code, and that brought in 10MB of Swift runtime libraries.

**Comment by stuartmorgan** [comment]
I assume that this is being measured pre-[thinning](https://developer.apple.com/documentation/xcode-release-notes/swift-5-release-notes-for-xcode-10_2#App-Thinning)? If so, I think we should just reset the baseline.

Is this our only size baseline? If so, we should seriously consider either replacing it, or at least adding a second one; the default project creation has been Swift/Kotlin for more than four years now, so the utility of a baseline that uses an Obj-C/Java template is questionable.

**Comment by jmagman** [comment]
Making the minimum iOS version 12.2 instead of 11.0 prevents the Swift runtime from being pulled in.  https://developer.apple.com/documentation/xcode-release-notes/swift-5-release-notes-for-xcode-10_2#App-Thinning

**Comment by jmagman** [comment]
I've talked to @zanderso and the compressed app size isn't an accurate proxy for downloaded app size since the App Store encrypts and then recompresses the app.

> When your app is approved for the App Store, it’s encrypted with Digital Rights Management (DRM) and recompressed. App Store file size for your binary may be larger than it is for the binary you uploaded in App Store Connect. The exact final size for your app can't be determined in advance.

https://developer.apple.com/help/app-store-connect/manage-builds/view-builds-and-metadata#view-the-file-sizes-of-a-build

One thing at a time though.  https://github.com/flutter/flutter/pull/140188 will set the minimum deployment target for iOS compile perf tests to 12.2 which should fix some of the size regression.

**Comment by jmagman** [comment]
> I've talked to @zanderso and the compressed app size isn't an accurate proxy for downloaded app size since the App Store encrypts and then recompresses the app.

This comment suggests another reason measuring compressed app size is important is to validate that changes in Dart snapshot format and data layout do not change compression size.
https://github.com/flutter/flutter/blob/0b6da5b45088bb1d8a9b1d1e89f3b7d1437390c4/dev/devicelab/lib/tasks/perf_tests.dart#L1701-L1702

But then I looked at where we decided that matters and it was past-me and I can't remember why:
https://github.com/flutter/flutter/pull/109891/files#r954405126

**Comment by jmagman** [comment]
> It's a straight up tar gz of the `flutter build` output directory, it looks like?

No, it's a tar gz of the app, not the whole output directory.
https://github.com/flutter/flutter/blob/0b6da5b45088bb1d8a9b1d1e89f3b7d1437390c4/dev/devicelab/lib/tasks/perf_tests.dart#L2224-L2231
https://github.com/flutter/flutter/blob/0b6da5b45088bb1d8a9b1d1e89f3b7d1437390c4/dev/devicelab/lib/tasks/perf_tests.dart#L1696-L1703

**Comment by zanderso** [comment]
@jmagman Thanks for investigating!

**Comment by jmagman** [comment]
![Screenshot 2023-12-15 at 12 34 49 PM](https://github.com/flutter/flutter/assets/682784/81950c56-1c36-4049-8260-0d617c2c14b0)
