### ISSUE TITLE
"EXC_BREAKPOINT" exception. application closed suddenly while in use.

### ISSUE THREAD

**Issue by naturalitchy** [flutter/flutter#139652]
I was testing on my phone. So I can show only Sentry error message.

I'm an attaching an images.

<img width="842" alt="Screenshot 2023-12-06 at 8 07 15 PM" src="https://github.com/flutter/flutter/assets/114861184/6d1609bf-8868-47dc-b5d9-7454733ecbad">
<img width="830" alt="Screenshot 2023-12-06 at 8 09 07 PM" src="https://github.com/flutter/flutter/assets/114861184/0e7f9157-6465-488f-913a-1e2973045948">
<img width="855" alt="Screenshot 2023-12-06 at 8 13 13 PM" src="https://github.com/flutter/flutter/assets/114861184/3cfa1b90-23c6-4518-92a9-a1cc267641f2">

and my flutter doctor -v state

<img width="894" alt="Screenshot 2023-12-06 at 8 14 43 PM" src="https://github.com/flutter/flutter/assets/114861184/a881c289-d927-4dd0-8e1d-4267c56fae50">

**Comment by darshankawar** [comment]
@naturalitchy 
Can you provide all crash logs in properly formatted text instead of in screenshots ?
Also, any pattern or steps to replicate these crashes would help to properly address the issue.

**Comment by naturalitchy** [comment]
I was testing with a real device
I have only that error msg

My action was to just infinite scroll down in my application
