### ISSUE TITLE
[pointer_interceptor] migrate to pkg:web

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#139753]

**Comment by parlough** [comment]
Eh nevermind @johnpryan, looks like @ditman beat you to it :)

Thank you both!

**Comment by ditman** [comment]
Welp! Sorry! I wasn't sure when I was going to touch `pointer_interceptor_web` again, and decided to go all in in the changes, didn't mean to step on @johnpryan's toes!

**Comment by parlough** [comment]
Oh no worries, I just wanted to make sure he knew. We can run the new DartPad frontend in Wasm with the update now :)

**Comment by johnpryan** [comment]
LGTM 👍
