### ISSUE TITLE
Clang Tidy ideally needs to run as pre-submit, but is too slow

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#139769]
### Is there an existing issue for this?

- [X] I have searched the [existing infra issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-infra)

### Type of Request

feature request

### Infrastructure Environment

I'm not sure (partially Goma -> RBE, but potentially other improvements as well)

## Background

[Clang Tidy](https://github.com/flutter/flutter/wiki/Engine-Clang-Tidy-Linter) is a **critical** component to the Flutter engine - it provides style guide enforcement, and even catches critical performance-lints (like copying expensive objects that should be moved instead in C++). As of [#48145](https://github.com/flutter/engine/pull/48145), we now run Clang Tidy on all C++ source and header files.

## Problem

Clang Tidy (with the lints we've chosen to enable) is _slow_.

There is unfortunately a lot of complaints on the web that indicate to me it's a wide problem:

> My workplace had such a debacle with clang-tidy that we had to disable it in a PR's CI...
> (https://www.reddit.com/r/cpp_questions/comments/10jx0uc/clang_tidy_is_very_slow_when_using_headers_like/)

As a result, we've created a lot of complexity (and are considering more) to defer and shard Clang Tidy:

- [Separate pre and post submit checks for clang_tidy per-platform](https://github.com/flutter/engine/blob/89ad167cc8b91530846485529aa1a17196479f44/.ci.yaml#L200-L235)
- [An option, currently unused, to shard](https://github.com/flutter/engine/blob/89ad167cc8b91530846485529aa1a17196479f44/tools/clang_tidy/lib/clang_tidy.dart#L171-L181)

## Ideas

I don't have a concrete suggestion, but I'm opening this issue to discuss one. Some _ideas_:

1. Use something like [ctccache](https://github.com/matus-chochlik/ctcache)
2. Hope that the [migration to RBE (and Reclient)](https://github.com/flutter/flutter/issues/132701) provides adequate caching

### Expected results

We can get rid of the post-submit, and always run the full set of Clang Tidy on pre-submit

**Comment by keyonghan** [comment]
I would expect reclient helps, where the migration is being tracked: https://github.com/flutter/flutter/issues/132701

> Clang Tidy (with the lints we've chosen to enable) is slow.

Has it been enabled in our CI? The execution time is roughly around 20 mins (https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20linux_clang_tidy). Do you mean the 20 mins is too slow or this is without lints?
