### ISSUE TITLE
[google_maps_flutter][iOS 17]  takeSnapshot renders a blank map

### ISSUE THREAD

**Issue by GeeRajasekaran** [flutter/flutter#139733]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

In My Flutter project I am using Googlemap and using "map#takeSnapshot" taking snapshot till XCode 14.3.1 it was working fine. Now I am getting blank screen while taking snapshot.

### Expected results

Taking snapshot map should be visible

### Actual results

Getting blank with google logo at bottom

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @GeeRajasekaran, please provide the following information. 

- The version of `google_maps_flutter` you're using and `google_maps_flutter_ios`
- The output of `flutter doctor -v`
- A complete minimal reproducible code sample without any third-party packages so that we can investigate this issue. 

Thank you

**Comment by GeeRajasekaran** [comment]
Hi @danagbemava-nc 
  google_maps_flutter - 2.5.0
 google_maps_flutter - 2.3.3

<img width="650" alt="Screenshot 2023-12-08 at 10 30 58 AM" src="https://github.com/flutter/flutter/assets/17061447/22eb27a8-3270-4f39-a3d4-a650b8db0611">

Below is the code  calling for take a snapshot

else if ([call.method isEqualToString:@"map#takeSnapshot"]) {
    if (self.mapView != nil) {
      UIGraphicsImageRendererFormat *format = [UIGraphicsImageRendererFormat defaultFormat];
      format.scale = [[UIScreen mainScreen] scale];
      UIGraphicsImageRenderer *renderer =
          [[UIGraphicsImageRenderer alloc] initWithSize:self.mapView.frame.size format:format];

      UIImage *image = [renderer imageWithActions:^(UIGraphicsImageRendererContext *context) {
        [self.mapView.layer renderInContext:context.CGContext];
      }];
      result([FlutterStandardTypedData typedDataWithBytes:UIImagePNGRepresentation(image)]);
    }

**Comment by danagbemava-nc** [comment]
Reproducible on iOS 17. When tested on iOS below 17 (16.4 & 15.8), it worked just fine. See the screenshots below

| below iOS 17 | iOS 17 | 
| -- | -- |
| <img src="https://github.com/flutter/flutter/assets/88313112/4bc5a965-08e0-4520-984d-e5c054c1f370" width="300" /> | <img src="https://github.com/flutter/flutter/assets/88313112/4e6787c3-c7c0-454a-9c3f-89730a846302" width="300" /> |

To reproduce, run the code sample below on iOS 17 and tap the floating action button. I tested on iOS 17.1.2

<details>
<summary>runnable code sample</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';


void main() => runApp(const MapsExampleApp());

class MapsExampleApp extends StatelessWidget {
  const MapsExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MapSample(),
    );
  }
}

class MapSample extends StatefulWidget {
  const MapSample({super.key});

  @override
  State<MapSample> createState() => MapSampleState();
}

class MapSampleState extends State<MapSample> {
  final Completer<GoogleMapController> _controller =
      Completer<GoogleMapController>();

  static const CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(37.42796133580664, -122.085749655962),
    zoom: 14.4746,
  );

  static const CameraPosition _kLake = CameraPosition(
      bearing: 192.8334901395799,
      target: LatLng(37.43296265331129, -122.08832357078792),
      tilt: 59.440717697143555,
      zoom: 19.151926040649414);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: GoogleMap(
        mapType: MapType.hybrid,
        initialCameraPosition: _kGooglePlex,
        onMapCreated: (GoogleMapController controller) {
          _controller.complete(controller);
        },
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: _goToTheLake,
        label: const Text('To the lake!'),
        icon: const Icon(Icons.directions_boat),
      ),
    );
  }

  Future<void> _goToTheLake() async {
    final GoogleMapController controller = await _controller.future;
    final image = await controller.takeSnapshot();

    if(image != null) {
      showDialog(context: context, builder: (context) {
        return AlertDialog(
          content: SizedBox(
            height: 300,
            width: 300,
            child: Image.memory(image),
          ),
        );
      });
    }
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[!] Flutter (Channel stable, 3.16.3, on macOS 14.1.2 23B92 darwin-arm64, locale en-GB)
    • Flutter version 3.16.3 on channel stable at /Users/nexus/dev/sdks/flutter
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutters/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutter. Consider adding /Users/nexus/dev/sdks/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutters/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutter. Consider adding /Users/nexus/dev/sdks/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0366e0a3f (2 days ago), 2023-12-05 19:46:39 -0800
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc1)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0-rc1
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-15.0.0-Release.Candidate.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.10072.19

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (4 available)
    • Pixel 7 (mobile) • 28291FDH2001SA            • android-arm64  • Android 14 (API 34)
    • Nexus (mobile)   • 00008020-001875E83A38002E • ios            • iOS 17.1.2 21B101
    • macOS (desktop)  • macos                     • darwin-arm64   • macOS 14.1.2 23B92 darwin-arm64
    • Chrome (web)     • chrome                    • web-javascript • Google Chrome 119.0.6045.199
    ! Error: Browsing on the local area network for Dean’s iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

```
[✓] Flutter (Channel master, 3.18.0-7.0.pre.36, on macOS 14.1.2 23B92 darwin-arm64, locale en-GB)
    • Flutter version 3.18.0-7.0.pre.36 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e31ac61813 (7 hours ago), 2023-12-07 17:28:32 -0800
    • Engine revision 6a687bef2c
    • Dart version 3.3.0 (build 3.3.0-200.0.dev)
    • DevTools version 2.30.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc1)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0-rc1
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-15.0.0-Release.Candidate.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.10072.19

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (4 available)
    • Pixel 7 (mobile) • 28291FDH2001SA            • android-arm64  • Android 14 (API 34)
    • Nexus (mobile)   • 00008020-001875E83A38002E • ios            • iOS 17.1.2 21B101
    • macOS (desktop)  • macos                     • darwin-arm64   • macOS 14.1.2 23B92 darwin-arm64
    • Chrome (web)     • chrome                    • web-javascript • Google Chrome 119.0.6045.199
    ! Error: Browsing on the local area network for Dean’s iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
</details>

**Comment by bahadirarslan** [comment]
Same problem here. It was working before iOS 17 and now it is only produces gray screen.

**Comment by GavrielRosendorn74** [comment]
Even when the sdk is updated to 8.3.1.0 it still show the grey screen do someone have a temporary fix ?

**Comment by GavrielRosendorn74** [comment]
I have a fix for IOS you can change this : 

`else if ([call.method isEqualToString:@"map#takeSnapshot"]) {
    if (self.mapView != nil) {
      UIGraphicsImageRendererFormat *format = [UIGraphicsImageRendererFormat defaultFormat];
      format.scale = [[UIScreen mainScreen] scale];
      UIGraphicsImageRenderer *renderer =
          [[UIGraphicsImageRenderer alloc] initWithSize:self.mapView.frame.size format:format];

      UIImage *image = [renderer imageWithActions:^(UIGraphicsImageRendererContext *context) {
        [self.mapView.layer renderInContext:context.CGContext];
      }];
      result([FlutterStandardTypedData typedDataWithBytes:UIImagePNGRepresentation(image)]);
    }`

By this in the native code : 

`else if ([call.method isEqualToString:@"map#takeSnapshot"]) {
    if (self.mapView != nil) {
      // Get the snapshot of the mapView
      UIGraphicsImageRenderer *renderer = [[UIGraphicsImageRenderer alloc] initWithSize:self.mapView.bounds.size];
      UIImage *image = [renderer imageWithActions:^(UIGraphicsImageRendererContext *context) {
          [self.mapView drawViewHierarchyInRect:self.mapView.bounds afterScreenUpdates:YES];
      }];

      // Convert the UIImage to FlutterStandardTypedData
      NSData *imageData = UIImagePNGRepresentation(image);
      FlutterStandardTypedData *typedData = [FlutterStandardTypedData typedDataWithBytes:imageData];

      // Pass the typedData to Flutter
      result(typedData);
    } else {
      result([FlutterError errorWithCode:@"GoogleMap uninitialized"
                                 message:@"takeSnapshot called prior to map initialization"
                                 details:nil]);
    }
  }`

**Comment by jmagman** [comment]
@GavrielRosendorn74 we take PRs 🙂 
Code is here:
https://github.com/flutter/packages/blob/0009545dd2a8b730d62e9b1c595b1e03fcad5f18/packages/google_maps_flutter/google_maps_flutter_ios/ios/Classes/GoogleMapController.m#L253-L261

And then make this test actually something about the data:
https://github.com/flutter/packages/blob/0009545dd2a8b730d62e9b1c595b1e03fcad5f18/packages/google_maps_flutter/google_maps_flutter_ios/example/ios11/integration_test/google_maps_test.dart#L848-L851

**Comment by GeeRajasekaran** [comment]
Now it was working without issue.Thanks @GavrielRosendorn74

**Comment by GavrielRosendorn74** [comment]
It means that the fix is not needed anymore or should i make a PR ? @GeeRajasekaran

**Comment by GeeRajasekaran** [comment]
Your fix is required. Your fix has only made it function properly. You can make a PR. Thanks

**Comment by GavrielRosendorn74** [comment]
PR submitted ! Thanks @jmagman ! 😍

**Comment by Bonissauro** [comment]
> I have a fix for IOS you can change this :
> 
> ```
> else if ([call.method isEqualToString:@"map#takeSnapshot"]) {
>     if (self.mapView != nil) {
>       UIGraphicsImageRendererFormat *format = [UIGraphicsImageRendererFormat defaultFormat];
>       format.scale = [[UIScreen mainScreen] scale];
>       UIGraphicsImageRenderer *renderer =
>           [[UIGraphicsImageRenderer alloc] initWithSize:self.mapView.frame.size format:format];
>       UIImage *image = [renderer imageWithActions:^(UIGraphicsImageRendererContext *context) {
>         [self.mapView.layer renderInContext:context.CGContext];
>       }];
>       result([FlutterStandardTypedData typedDataWithBytes:UIImagePNGRepresentation(image)]);
>     } else {
>       result([FlutterError errorWithCode:@"GoogleMap uninitialized"
>                                  message:@"takeSnapshot called prior to map initialization"
>                                  details:nil]);
>     }
> }
> ```
> 
> By this in the native code :
> 
> ```
> else if ([call.method isEqualToString:@"map#takeSnapshot"]) {
>     if (self.mapView != nil) {
>       // Get the snapshot of the mapView
>       UIGraphicsImageRenderer *renderer = [[UIGraphicsImageRenderer alloc] initWithSize:self.mapView.bounds.size];
>       UIImage *image = [renderer imageWithActions:^(UIGraphicsImageRendererContext *context) {
>           [self.mapView drawViewHierarchyInRect:self.mapView.bounds afterScreenUpdates:YES];
>       }];
>       // Convert the UIImage to FlutterStandardTypedData
>       NSData *imageData = UIImagePNGRepresentation(image);
>       FlutterStandardTypedData *typedData = [FlutterStandardTypedData typedDataWithBytes:imageData];
>       // Pass the typedData to Flutter
>       result(typedData);
>     } else {
>       result([FlutterError errorWithCode:@"GoogleMap uninitialized"
>                                  message:@"takeSnapshot called prior to map initialization"
>                                  details:nil]);
>     }
>   }
> ```

Hello, @GavrielRosendorn74 

Sorry about this dummy question, but could you explain how do I implement you solution locally, at least until the moment your PR is released?

10x in advance for any help

**Comment by GavrielRosendorn74** [comment]
@Bonissauro You can go check the PR and make the changes needed locally on the package then build and you should be fixed ;) 

Here's the link :

https://github.com/flutter/packages/pull/5823/files

**Comment by iamsharad98** [comment]
@GavrielRosendorn74 Hey are you working on a fix in that PR, actually I am waiting for your PR to merged

**Comment by GavrielRosendorn74** [comment]
Hi @iamsharad98! Yes, I have already worked on a fix. It has passed the first code review. I am just waiting for the Flutter team to confirm the merge. 👍

**Comment by droidpl** [comment]
@GavrielRosendorn74 do you know when are we seeing this landing in a publiv version?

**Comment by danagbemava-nc** [comment]
Hi @droidpl, a release has been made to `google_maps_flutter_ios`, see https://pub.dev/packages/google_maps_flutter_ios/changelog. 

Can you run `flutter pub upgrade` to get the new version of `google_maps_flutter_ios` and check if you still experience this issue?

**Comment by jmagman** [comment]
Thanks for noticing @danagbemava-nc, and this should have been closed with https://github.com/flutter/packages/pull/5823.
