### ISSUE TITLE
Flutter tooling should take heed of archivesBaseName

### ISSUE THREAD

**Issue by mravn-google** [flutter/flutter#13977]
That property can be set by custom Gradle configuration, and will result in a "Gradle failed to produce an Android package" error.

See https://github.com/flutter/flutter/issues/11866#issuecomment-351951650

**Comment by dereklakin** [comment]
@Hixie This was added to a milestone (which looks like it's now deleted) over a year ago. Any plans to address it or is there an alternative to generating custom APK names for Flutter?

**Comment by Hixie** [comment]
cc @zra

**Comment by littleGnAl** [comment]
Any updates on this?

**Comment by bingyingu** [comment]
Here's a temporary fix to get your platform. i'm use v1.9.1+hotfix.6
1、modify $flutterRoot/packages/flutter_tools/gradle/flutter.gradle
     find "getBasePlatform(Project project)" method，and return your platform.
2、android/app/build.gradle add ndk.abiFilters your platform

like this:
    defaultConfig {
        ......
        ndk {
            abiFilters "armeabi-v7a"
        }
     }

    /**
     * Returns the platform that is used to extract the `libflutter.so` and the .class files.
     *
     * Note: This is only needed to add the .class files.
     * Unfortunately, the engine artifacts include the .class and libflutter.so files.
     */
    private static String getBasePlatform(Project project) {
        //if (PLATFORM_ARM64 in getTargetPlatforms(project)) {
        //    return PLATFORM_ARM64;
        //}
        return PLATFORM_ARM32;
    }

**Comment by cirediew** [comment]
Has this been implemented to stable yet? If so, it doesn't seem to be working for me. This is my code in `app/build.gradle`
```
setProperty("archivesBaseName", "$applicationId-$versionName+$versionCode"+ "-" + new Date().format('yyyy_MM_dd'))
```
