### ISSUE TITLE
[firebase_database v0.3.1]: MissingPluginException(No implementation found for method Query#observe on channel plugins.flutter.io/firebase_database)

### ISSUE THREAD

**Issue by Gogetter** [flutter/flutter#13971]
## Steps to Reproduce

```
dependencies:
  firebase_analytics: ^0.2.0
  firebase_auth: ^0.4.0
  google_sign_in: ^2.0.0
  firebase_database: ^0.3.1
  firebase_messaging: ^0.1.0
  firebase_core: ^0.0.2
  flutter_facebook_connect: ^0.0.3
```

Running below code 
```java
@override
  void initState() {
    super.initState();

    final FirebaseDatabase database = new FirebaseDatabase(app: app);

    _categoryRef = database.reference().child(Strings.categoryTablename);

    Future<DataSnapshot> categorySnap = database.reference().child(Strings.categoryTablename).once(); //exception thrown here
    categorySnap.then((DataSnapshot snapshot) {
        debugPrint('Connected to app database and read ${snapshot.value}');
      }
    });
  }
```

produces below error logs

## Logs

```
E/flutter ( 3705): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 3705): MissingPluginException(No implementation found for method Query#observe on channel plugins.flutter.io/firebase_database)
E/flutter ( 3705): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:153:7)
E/flutter ( 3705): <asynchronous suspension>
E/flutter ( 3705): #1      Query._observe.<anonymous closure> (package:firebase_database/src/query.dart:50:38)
E/flutter ( 3705): #2      _runGuarded (dart:async/stream_controller.dart:803)
E/flutter ( 3705): #3      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:217)
E/flutter ( 3705): #4      _ControllerStream._createSubscription (dart:async/stream_controller.dart:816)
E/flutter ( 3705): #5      _StreamImpl.listen (dart:async/stream_impl.dart:466)
E/flutter ( 3705): #6      _NavigatorState.initState (/data/user/0/com.category/cache/categoryUDBOKZ/category/lib/routes/drawer/navigator_view.dart:59:50)
E/flutter ( 3705): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3655:14)
E/flutter ( 3705): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3519:5)
E/flutter ( 3705): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2857:14)
E/flutter ( 3705): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2660:12)
E/flutter ( 3705): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3556:16)
E/flutter ( 3705): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3445:5)
E/flutter ( 3705): #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3524:5)
E/flutter ( 3705): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3519:5)
E/flutter ( 3705): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2857:14)
E/flutter ( 3705): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2660:12)
E/flutter ( 3705): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3556:16)
E/flutter ( 3705): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3445:5)
E/flutter ( 3705): #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3524:5)
E/flutter ( 3705): #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3519:5)
E/flutter ( 3705): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2857:14)
E/flutter ( 3705): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2660:12)
E/flutter ( 3705): #23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4532:14)
E/flutter ( 3705): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2857:14)
E/flutter ( 3705): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2660:12)
E/flutter ( 3705): #26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4532:14)
E/flutter ( 3705): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2857:14)
E/flutter ( 3705): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2660:12)
E/flutter ( 3705): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3556:16)
E/flutter ( 3705): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3445:5)
E/flutter ( 3705): #31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3524:5)
E/flutter ( 3705): #32     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3662:22)
E/flutter ( 3705): #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3519:5)
E/flutter ( 3705): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2857:14)
E/flutter ( 3705): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2660:12)
E/flutter ( 3705): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3556:16)
E/flutter ( 3705): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3445:5)
E/flutter ( 3705): #38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3524:5)
E/flutter ( 3705): #39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3519:5)
E/flutter ( 3705): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2857:14)
E/flutter ( 3705): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2660:12)
E/flutter ( 3705): #42     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4532:14)
E/flutter ( 3705): #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2857:14)
E/flutter ( 3705): #44     Element.updateChild (
```

## `flutter analyze`
```
hint • The value of the field '_user' isn't used at lib/routes/drawer/sbs_navigator_view.dart:34:22 • unused_field
  hint • The value of the field '_databaseError' isn't used at lib/routes/drawer/navigator_view.dart:36:17 • unused_field
  hint • The value of the field '_lastLifeCycleState' isn't used at lib/routes/sbs_onboarding_page_view.dart:23:21 • unused_field
  hint • The method '_signInWithEmailPassword' isn't used at lib/routes/sign_in.dart:115:24 • unused_element
  hint • Method doesn't override an inherited method at lib/routes/sign_in.dart:149:8 • override_on_non_overriding_method
  hint • The value of the field '_lastLifeCycleState' isn't used at lib/routes/sign_in_with_email.dart:54:21 • unused_field
  hint • Unused import at lib/utils/database_utils.dart:1:8 • unused_import
```

## Flutter Doctor
```
[✓] Flutter (on Mac OS X 10.13.2 17C88, locale en-GB, channel alpha)
    • Flutter at /Users/etimbuk/sdks/flutter
    • Framework revision 8f65fec5f5 (4 weeks ago), 2017-12-12 09:50:14 -0800
    • Engine revision edaecdc8b8
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.d8ae797298c3a6cf8dc9f4558707bd2672224d3e

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/etimbuk/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.6)
    • Flutter plugin version 18.3
    • Dart plugin version 172.4343.25

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)
```

Please I will appreciate your ind assistance. thanks

**Comment by Hixie** [comment]
cc @collinjackson @kroikie

**Comment by okaybroda** [comment]
Try reinstalling all the packages that worked for me.

```
flutter clean
flutter packages get
```

If that doesn't work, delete build folder and try installing packages again.

**Comment by Gogetter** [comment]
Thanks @okaybroda. That sorted it.

**Comment by Gogetter** [comment]
Closing as sorted out by @okaybroda suggestion.
```
flutter clean
flutter packages get
```

**Comment by PhamTruongHung** [comment]
> Try reinstalling all the packages that worked for me.
> 
> ```
> flutter clean
> flutter packages get
> ```
> 
> If that doesn't work, delete build folder and try installing packages again.

Tks, That worked for me.

**Comment by duengeonmasterr** [comment]
thanks

**Comment by HassanDabary** [comment]
do not use Flutter Hot run
use normal Run  instead

**Comment by kroikie** [comment]
@Gogetter

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/914. Any further collaboration will be done there.

**Comment by Avi-Patel** [comment]
I am facing same issue, but none of above all solutions works for me. Please provide some guaranteed solution.

**Comment by Nikhilsharma1999** [comment]
E/flutter (24496): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method Query#addSnapshotListener on channel plugins.flutter.io/cloud_firestore)
E/flutter (24496): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (24496): <asynchronous suspension>
E/flutter (24496): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (24496): #2      Query.snapshots.<anonymous closure> (package:cloud_firestore/src/query.dart:61:37)
E/flutter (24496): #3      _runGuarded (dart:async/stream_controller.dart:820:24)
E/flutter (24496): #4      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:215:7)
E/flutter (24496): #5      _ControllerStream._createSubscription (dart:async/stream_controller.dart:833:19)
E/flutter (24496): #6      _StreamImpl.listen (dart:async/stream_impl.dart:475:9)
E/flutter (24496): #7      _StreamBuilderBaseState._subscribe (package:flutter/src/widgets/async.dart:137:37)
E/flutter (24496): #8      _StreamBuilderBaseState.initState (package:flutter/src/widgets/async.dart:111:5)
E/flutter (24496): #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4640:58)
E/flutter (24496): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
E/flutter (24496): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter (24496): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter (24496): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)

**Comment by Nikhilsharma1999** [comment]
I am also getting the same error

**Comment by Nikhilsharma1999** [comment]
Do I need to update my Android Studio IDE?

**Comment by ChunHuaLu** [comment]
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method Query#observe on channel plugins.flutter.io/firebase_database)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
#2      Query._observe.<anonymous closure> (package:firebase_database/src/query.dart:50:38)
#3      _runGuarded (dart:async/stream_controller.dart:820:24)
#4      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:215:7)
#5      _ControllerStream._createSubscription (dart:async/stream_controller.dart:833:19)
#6      _StreamImpl.listen (dart:async/stream_impl.dart:475:9)
#7      Stream.first (dart:async/stream.dart:1254:25)
#8      Query.once (package:firebase_database/src/query.dart:84:55)
#9      _IoTState.initState (package:flutter_iot_green/main.dart:35:12)
#10     StatefulElement.<…>

flutter clean & flutter packages get still can't solve the problem

**Comment by hkmr** [comment]
> [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method Query#observe on channel plugins.flutter.io/firebase_database)
> #0 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
> 
> #1 MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
> #2 Query._observe. (package:firebase_database/src/query.dart:50:38)
> #3 _runGuarded (dart:async/stream_controller.dart:820:24)
> #4 _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:215:7)
> #5 _ControllerStream._createSubscription (dart:async/stream_controller.dart:833:19)
> #6 _StreamImpl.listen (dart:async/stream_impl.dart:475:9)
> #7 Stream.first (dart:async/stream.dart:1254:25)
> #8 Query.once (package:firebase_database/src/query.dart:84:55)
> #9 _IoTState.initState (package:flutter_iot_green/main.dart:35:12)
> #10 StatefulElement.<…>
> 
> flutter clean & flutter packages get still can't solve the problem

Hey Did you find any solution for that issue. ?

**Comment by Avi-Patel** [comment]
> > [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method Query#observe on channel plugins.flutter.io/firebase_database)
> > #0 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
> > #1 MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
> > #2 Query._observe. (package:firebase_database/src/query.dart:50:38)
> > #3 _runGuarded (dart:async/stream_controller.dart:820:24)
> > #4 _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:215:7)
> > #5 _ControllerStream._createSubscription (dart:async/stream_controller.dart:833:19)
> > #6 _StreamImpl.listen (dart:async/stream_impl.dart:475:9)
> > #7 Stream.first (dart:async/stream.dart:1254:25)
> > #8 Query.once (package:firebase_database/src/query.dart:84:55)
> > #9 _IoTState.initState (package:flutter_iot_green/main.dart:35:12)
> > #10 StatefulElement.<…>
> > flutter clean & flutter packages get still can't solve the problem
> 
> Hey Did you find any solution for that issue. ?

I did not solve but got to know that we need to mock this in order to use firebase calls in testing script

**Comment by ChunHuaLu** [comment]
Hello @hkmr @Avi-Patel   I didn't solve it on realtime firebase, I choose to use firestore instead.
 I successfully connect to firestore, maybe realtime firebase works the same way, don't follow the last two steps given by official firebase instruction, skip the last two steps. ( don't need to implement code to AppDelegate.swift )
Does anyone know why we skip the last two steps? Thanks.

**Comment by Nikhilsharma1999** [comment]
Hey @ChunHuaLu how did you connect to firestore?

**Comment by rechor** [comment]
Had a similar issue ("MissingPluginException...#putFile") - stopping and starting the app again fixed the issue.

**Comment by FlorianBergmann** [comment]
Having the same issue with firestore as @Nikhilsharma1999 

I have a project that I build a while ago and picked up again. After upgrading all dependencies I am now stuck with this issue. Clean & get does not fix it for me either.

**Comment by NDJ-1701** [comment]
same issue for me, none of the fixes above do anything to resolve the issue on my end. Developing a flutter web app.

`Error: MissingPluginException(No implementation found for method Query#observe on channel plugins.flutter.io/firebase_database)
    at Object.throw_ [as throw] (http://localhost:5005/dart_sdk.js:4463:11)
    at MethodChannel._invokeMethod (http://localhost:5005/packages/flutter/src/services/platform_channel.dart.lib.js:409:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:5005/dart_sdk.js:37175:33
    at _RootZone.runUnary (http://localhost:5005/dart_sdk.js:37029:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:5005/dart_sdk.js:32116:29)
    at handleValueCallback (http://localhost:5005/dart_sdk.js:32663:49)
    at Function._propagateToListeners (http://localhost:5005/dart_sdk.js:32701:17)
    at _Future.new.[_completeWithValue] (http://localhost:5005/dart_sdk.js:32544:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:5005/dart_sdk.js:32566:35)
    at Object._microtaskLoop (http://localhost:5005/dart_sdk.js:37290:13)
    at _startMicrotaskLoop (http://localhost:5005/dart_sdk.js:37296:13)`

**Comment by jagdish590** [comment]
I am also facing same issue if I added the code to update the data
 dbFirestore
        .collection('farmers')
        .document('nuu86Os9V24Rk3dKfwoy')
        .updateData(newData);

Can someone help me to resolve this issue I already tried flutter clean
flutter packages get

**Comment by datovarc** [comment]
Hi, I am also facing the same issue, with Flutter web.
`Error: MissingPluginException(No implementation found for method Query#observe on channel plugins.flutter.io/firebase_database)
    at Object.throw_ [as throw] (http://localhost:12036/dart_sdk.js:5331:11)
    at MethodChannel._invokeMethod (http://localhost:12036/packages/flutter/src/services/system_channels.dart.lib.js:954:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:12036/dart_sdk.js:39029:33
    at _RootZone.runUnary (http://localhost:12036/dart_sdk.js:38886:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:12036/dart_sdk.js:33872:29)
    at handleValueCallback (http://localhost:12036/dart_sdk.js:34432:49)
    at Function._propagateToListeners (http://localhost:12036/dart_sdk.js:34470:17)
    at _Future.new.[_completeWithValue] (http://localhost:12036/dart_sdk.js:34312:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:12036/dart_sdk.js:34335:35)
    at Object._microtaskLoop (http://localhost:12036/dart_sdk.js:39173:13)
    at _startMicrotaskLoop (http://localhost:12036/dart_sdk.js:39179:13)
    at http://localhost:12036/dart_sdk.js:34686:9
`

I have tried already flutter clean + flutter packages get, but still same issue.

**Comment by equitharn** [comment]
bump!

**Comment by cloudbreakstudios** [comment]
For me I had to update the database rules so that read and write are true.  This will need to be adjusted for release though as setting them to this value makes them public, I believe!

**Comment by equitharn** [comment]
> For me I had to update the database rules so that read and write are true. This will need to be adjusted for release though as setting them to this value makes them public, I believe!

This issue is not related to database rules. I believe what you are facing is not what this thread is about.

**Comment by QuentinSc** [comment]
Same issue with flutter web (2.0.1). No solution ?

**Comment by gmaxferr** [comment]
This still happens, i'm getting:

`No implementation found for method DatabaseReference#set on channel plugins.flutter.io/firebase_database`

> flutter 2.0.3

firebase_core: ^1.0.2
firebase_auth: ^1.0.1
firebase_database: ^6.1.1

**Comment by NikolinNgjela** [comment]
Having the same issue on flutter Web 

```
Error: MissingPluginException(No implementation found for method Query#observe on channel plugins.flutter.io/firebase_database)
    at Object.throw_ [as throw] (http://localhost:51747/dart_sdk.js:5333:11)
    at MethodChannel._invokeMethod (http://localhost:51747/packages/flutter/src/services/system_channels.dart.lib.js:954:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:51747/dart_sdk.js:39031:33
    at _RootZone.runUnary (http://localhost:51747/dart_sdk.js:38888:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:51747/dart_sdk.js:33874:29)
    at handleValueCallback (http://localhost:51747/dart_sdk.js:34434:49)
    at Function._propagateToListeners (http://localhost:51747/dart_sdk.js:34472:17)
    at _Future.new.[_completeWithValue] (http://localhost:51747/dart_sdk.js:34314:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:51747/dart_sdk.js:34337:35)
    at Object._microtaskLoop (http://localhost:51747/dart_sdk.js:39175:13)
    at _startMicrotaskLoop (http://localhost:51747/dart_sdk.js:39181:13)
    at http://localhost:51747/dart_sdk.js:34688:9

```

**Comment by marceloams** [comment]
The same issue here working on mobile app but not on web.

Packages:

 - firebase_database: ^6.1.2
 - firebase_core: ^1.1.0

Error:

```
Error: MissingPluginException(No implementation found for method Query#observe on channel plugins.flutter.io/firebase_database)
    at Object.throw_ [as throw] (http://localhost:56727/dart_sdk.js:5355:11)
    at MethodChannel._invokeMethod (http://localhost:56727/packages/flutter/src/services/system_channels.dart.lib.js:962:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:56727/dart_sdk.js:39215:33
    at _RootZone.runUnary (http://localhost:56727/dart_sdk.js:39072:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:56727/dart_sdk.js:34058:29)
    at handleValueCallback (http://localhost:56727/dart_sdk.js:34618:49)
    at Function._propagateToListeners (http://localhost:56727/dart_sdk.js:34656:17)
    at _Future.new.[_completeWithValue] (http://localhost:56727/dart_sdk.js:34498:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:56727/dart_sdk.js:34521:35)
    at Object._microtaskLoop (http://localhost:56727/dart_sdk.js:39359:13)
    at _startMicrotaskLoop (http://localhost:56727/dart_sdk.js:39365:13)
    at http://localhost:56727/dart_sdk.js:34872:9
```

**Comment by watoo** [comment]
Getting the same issue. Working fine on Andriod, but throws an error on the web.

**Packages:**
firebase_core: ^1.0.3
firebase_database: ^6.1.2

**Error:**
```
Error: MissingPluginException(No implementation found for method DatabaseReference#set on channel plugins.flutter.io/firebase_database)
    at Object.throw_ [as throw] (http://127.0.0.1:8080/dart_sdk.js:5355:11)
    at MethodChannel._invokeMethod (http://127.0.0.1:8080/packages/flutter/src/services/system_channels.dart.lib.js:962:21)
    at _invokeMethod.next (<anonymous>)
    at http://127.0.0.1:8080/dart_sdk.js:39215:33
    at _RootZone.runUnary (http://127.0.0.1:8080/dart_sdk.js:39072:58)
    at _FutureListener.thenAwait.handleValue (http://127.0.0.1:8080/dart_sdk.js:34058:29)
    at handleValueCallback (http://127.0.0.1:8080/dart_sdk.js:34618:49)
    at Function._propagateToListeners (http://127.0.0.1:8080/dart_sdk.js:34656:17)
    at _Future.new.[_completeWithValue] (http://127.0.0.1:8080/dart_sdk.js:34498:23)
    at async._AsyncCallbackEntry.new.callback (http://127.0.0.1:8080/dart_sdk.js:34521:35)
    at Object._microtaskLoop (http://127.0.0.1:8080/dart_sdk.js:39359:13)
    at _startMicrotaskLoop (http://127.0.0.1:8080/dart_sdk.js:39365:13)
    at http://127.0.0.1:8080/dart_sdk.js:34872:9
```

**Comment by kanishk-watt** [comment]
Can anyone provide a solution to this? clean and get not working, moving to stable didn't work.

**Comment by sumanthratna** [comment]
For me, I think the issue was that I upgraded Gradle. If you upgrade Gradle to a version different than the version you created your project with, make sure to update the `distributionUrl` key in `android/app/gradle/wrapper/gradle-wrapper.properties`. You can find the latest distribution URL here: https://docs.gradle.org/current/userguide/gradle_wrapper.html#:~:text=properties-,distributionurl%3Dhttps%5C%3A%2F%2Fservices.gradle.org%2Fdistributions%2Fgradle. 

(may not work for everyone, does not apply to everyone)

**Comment by nathanRamaNoodles** [comment]
For anyone with the web issue, the Realtime Database is on the roadmap for web: https://github.com/FirebaseExtended/flutterfire#firebase_database
![image](https://user-images.githubusercontent.com/32442782/121390699-3ffc6800-c913-11eb-8855-bb0bc6efed6f.png)

**Comment by fuadj** [comment]
> For anyone with the web issue, the Realtime Database is on the roadmap for web: https://github.com/FirebaseExtended/flutterfire#firebase_database
> ![image](https://user-images.githubusercontent.com/32442782/121390699-3ffc6800-c913-11eb-8855-bb0bc6efed6f.png)

They should've written better logs instead of leading us to a rabbit hole for hours. Fuck. Thank you, man you're a life saver.
