### ISSUE TITLE
[CP] Catch error for missing directory in `FontConfigManager`

### ISSUE THREAD

**Issue by eliasyishak** [flutter/flutter#139742]
### Issue Link

https://github.com/flutter/flutter/issues/138434

### Commit Hash

04afff3

### Target

stable

### PR Link

https://github.com/flutter/flutter/pull/139743

### Changelog Description

We are allowing the deletion of a directory to not crash the tool if the directory doesn't exist.

### Impacted Users

All flutter users

### Impact Description

Flutter will crash if it attempts to delete a directory that doesn't exist or any other `FileSystemException`

### Workaround

N/A

### Risk

medium

### Test Coverage

yes

### Validation Steps

The test case added confirms the fix by silently exiting when the deletion error comes up

**Comment by itsjustkevin** [comment]
@eliasyishak could you update the `PR Link` section with the link to the cherry-pick PR?

@christopherfujino for review.

**Comment by eliasyishak** [comment]
@itsjustkevin fixed the link now

**Comment by christopherfujino** [comment]
LGTM, this is our top crasher for 3.16

**Comment by CaseyHillers** [comment]
Released in 3.16.4
