### ISSUE TITLE
Error installing google_sign_in

### ISSUE THREAD

**Issue by vskr** [flutter/flutter#13973]
## Logs

Run your application with `flutter run` and attach all the log output.

```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                0.6s
Resolving dependencies...                                 
* Error running Gradle:
Exit code 1 from: /Users/saivadlamani/trainthebots/android/gradlew app:properties:
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /Users/saivadlamani/Library/Android/sdk/ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.


BUILD FAILED

Total time: 0.792 secs


FAILURE: Build failed with an exception.
```
* Where:
```
Script '/Users/saivadlamani/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 167
```

* What went wrong:
```
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Could not resolve all dependencies for configuration ':app:_debugApk'.
      > A problem occurred configuring project ':google_sign_in'.
         > Could not find method debugProvided() for arguments [file collection] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

I modified build.gradle to include jitpack.io as one of the maven urls

```
allprojects {
    repositories {
        jcenter()
        maven {
            url "https://maven.google.com"
        }
        maven {
            url "https://jitpack.io"
        }
    }
}
```

Strange thing is I see this error and it fails the build even after *removing* google_sign_in dependency from pubspec.yaml. It is very strange because I removed caches packages and I ran flutter run and I still see this error.

**Comment by mit-mit** [comment]
cc @mravn-google

**Comment by mravn-google** [comment]
@vskr The reason removing the `google_sign_in` dependency seems to have no effect is that Flutter tooling is evaluating the Gradle setup prior to rewriting the `.flutter-plugins` file. That file currently mentions the plugin; the Gradle evaluation fails; and then we never get to rewrite it. This bug has been fixed in https://github.com/flutter/flutter/pull/13827 which is not yet part of the Flutter alpha branch. You can just delete the `.flutter-plugins` file. Then Gradle evaluation will no longer include `google_sign_in`.

The fact that `debugProvided` is not defined seems to imply that the Android Studio Gradle plugin has not been correctly applied. I've seen a similar error with a project where one of the `build.gradle` files had been deleted by accident and recreated by Android Studio during a Gradle 3.3->4.1 upgrade.

If possible, could you share the following files:

* `android/settings.gradle`
* `android/build.gradle`
* `android/app/build.gradle`

**Comment by vskr** [comment]
Sure here are the files you mentioned

android/settings.gradle
include ':app'

def flutterProjectRoot = rootProject.projectDir.parentFile.toPath()

def plugins = new Properties()
def pluginsFile = new File(flutterProjectRoot.toFile(), '.flutter-plugins')
if (pluginsFile.exists()) {
    pluginsFile.withInputStream { stream -> plugins.load(stream) }
}

plugins.each { name, path ->
    def pluginDirectory = flutterProjectRoot.resolve(path).resolve('android').toFile()
    include ":$name"
    project(":$name").projectDir = pluginDirectory
}


android/build.gradle
buildscript {
    repositories {
        jcenter()
        maven {
            url "https://maven.google.com"
        }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
    }
}

allprojects {
    repositories {
        jcenter()
        maven {
            url "https://maven.google.com"
        }
        maven {
            url "https://jitpack.io"
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

android/app/build.gradle
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withInputStream { stream ->
        localProperties.load(stream)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 25
    buildToolsVersion '25.0.3'

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.yourcompany.trainthebots"
        minSdkVersion 16
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    androidTestCompile 'com.android.support:support-annotations:25.4.0'
    androidTestCompile 'com.android.support.test:runner:0.5'
    androidTestCompile 'com.android.support.test:rules:0.5'
}

**Comment by vskr** [comment]
Seeing same error as before, when I include google_sign_in in pubspec.yaml

Here is the error:

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/saivadlamani/.pub-cache/hosted/pub.dartlang.org/google_sign_in-2.0.0/android/build.gradle' line: 6

* What went wrong:
A problem occurred evaluating project ':google_sign_in'.
> Could not find method google() for arguments [] on repository container.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Finished with error: Gradle build failed: 

How do I make sure gradle plugin is correctly applied?

**Comment by mravn-google** [comment]
The error seems different now from what was originally reported.

You'd get the `google()` error by depending on a Gradle 4.x based plugin from a Gradle 3.x based Flutter project.

You should either downgrade your dependency on `google_sigin_in` to version 1.0.3, or upgrade your Flutter project to Gradle 4.1 as described [here](https://github.com/flutter/flutter/wiki/Updating-Flutter-projects-to-Gradle-4.1-and-Android-Studio-Gradle-plugin-3.0.1).

**Comment by vskr** [comment]
Using 1.0.3 in pubspec.yaml didn't work

Here is the error message I see when I try get version 1.0.3

Running "flutter packages get" in trainthebots3...
Package google_sign_in has no versions that match 1.0.3 derived from:
- trainthebots3 depends on version 1.0.3
---- Log transcript ----
FINE: Pub 1.25.0-dev.11.0
MSG : Resolving dependencies...
SLVR: Solving dependencies:
    | - cupertino_icons ^0.1.0 from hosted (cupertino_icons) (locked to 0.1.1)
    | - google_sign_in 1.0.3 from hosted (google_sign_in) (locked to 2.0.1)
    | - flutter any from sdk (flutter) (locked to 0.0.40)
SLVR: * start at root
SLVR: | cupertino_icons 0.1.1 from hosted is locked
SLVR: | * select cupertino_icons 0.1.1 from hosted
SLVR: | | flutter 0.0.40 from sdk is locked
SLVR: | | * select flutter 0.0.40 from sdk
SLVR: | | | collection 1.14.3 from hosted is locked
SLVR: | | | * select collection 1.14.3 from hosted
SLVR: | | | | flutter_test 0.0.18 from sdk is locked
SLVR: | | | | * select flutter_test 0.0.18 from sdk
SLVR: | | | | | * select pub itself
SLVR: | | | | | | args 0.13.7 from hosted is locked
SLVR: | | | | | | * select args 0.13.7 from hosted
SLVR: | | | | | | | async 1.13.3 from hosted is locked
SLVR: | | | | | | | * select async 1.13.3 from hosted
SLVR: | | | | | | | | barback 0.15.2+13 from hosted is locked
SLVR: | | | | | | | | * select barback 0.15.2+13 from hosted
SLVR: | | | | | | | | | boolean_selector 1.0.2 from hosted is locked
SLVR: | | | | | | | | | * select boolean_selector 1.0.2 from hosted
SLVR: | | | | | | | | | | charcode 1.1.1 from hosted is locked
SLVR: | | | | | | | | | | * select charcode 1.1.1 from hosted
SLVR: | | | | | | | | | | | convert 2.0.1 from hosted is locked
SLVR: | | | | | | | | | | | * select convert 2.0.1 from hosted
SLVR: | | | | | | | | | | | | crypto 2.0.2+1 from hosted is locked
SLVR: | | | | | | | | | | | | * select crypto 2.0.2+1 from hosted
SLVR: | | | | | | | | | | | | | glob 1.1.5 from hosted is locked
SLVR: | | | | | | | | | | | | | * select glob 1.1.5 from hosted
SLVR: | | | | | | | | | | | | | | google_sign_in 2.0.1 from hosted is locked but does not match 1.0.3
IO  : Get versions from https://pub.dartlang.org/api/packages/google_sign_in.
IO  : HTTP GET https://pub.dartlang.org/api/packages/google_sign_in
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: get
    | X-Pub-Session-ID: 536E0676-A889-498F-8352-1012DFC91E5B
    | X-Pub-Environment: flutter_cli:verify:run
    | X-Pub-Reason: direct
    | user-agent: Dart pub 1.25.0-dev.11.0
IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/google_sign_in
    | took 0:00:00.286314
    | transfer-encoding: chunked
    | date: Sat, 20 Jan 2018 19:17:27 GMT
    | content-encoding: gzip
    | vary: Accept-Encoding
    | via: 1.1 google
    | content-type: application/json
    | x-frame-options: SAMEORIGIN
    | x-xss-protection: 1; mode=block
    | x-content-type-options: nosniff
    | server: dart:io with Shelf
SLVR: | | | | | | | | | | | | | | version 2.0.1 of google_sign_in doesn't match 1.0.3:
    | | | | | | | | | | | | | | |   trainthebots3 0.0.0 (root) -> google_sign_in 1.0.3 from hosted (google_sign_in)
SLVR: | | | | | | | | | | | | | | version 2.0.0 of google_sign_in doesn't match 1.0.3:
    | | | | | | | | | | | | | | |   trainthebots3 0.0.0 (root) -> google_sign_in 1.0.3 from hosted (google_sign_in)
SLVR: | | | | | | | | | | | | | | version 1.0.1 of google_sign_in doesn't match 1.0.3:
    | | | | | | | | | | | | | | |   trainthebots3 0.0.0 (root) -> google_sign_in 1.0.3 from hosted (google_sign_in)
SLVR: | | | | | | | | | | | | | | version 0.3.1 of google_sign_in doesn't match 1.0.3:
    | | | | | | | | | | | | | | |   trainthebots3 0.0.0 (root) -> google_sign_in 1.0.3 from hosted (google_sign_in)
SLVR: | | | | | | | | | | | | | | version 0.2.1 of google_sign_in doesn't match 1.0.3:
    | | | | | | | | | | | | | | |   trainthebots3 0.0.0 (root) -> google_sign_in 1.0.3 from hosted (google_sign_in)
SLVR: | | | | | | | | | | | | | | version 0.2.0 of google_sign_in doesn't match 1.0.3:
    | | | | | | | | | | | | | | |   trainthebots3 0.0.0 (root) -> google_sign_in 1.0.3 from hosted (google_sign_in)
SLVR: | | | | | | | | | | | | | | version 0.0.6 of google_sign_in doesn't match 1.0.3:
    | | | | | | | | | | | | | | |   trainthebots3 0.0.0 (root) -> google_sign_in 1.0.3 from hosted (google_sign_in)
SLVR: | | | | | | | | | | | | | | version 0.0.5 of google_sign_in doesn't match 1.0.3:
    | | | | | | | | | | | | | | |   trainthebots3 0.0.0 (root) -> google_sign_in 1.0.3 from hosted (google_sign_in)
SLVR: | | | | | | | | | | | | | | version 0.0.4 of google_sign_in doesn't match 1.0.3:
    | | | | | | | | | | | | | | |   trainthebots3 0.0.0 (root) -> google_sign_in 1.0.3 from hosted (google_sign_in)
SLVR: | | | | | | | | | | | | | | version 0.0.3 of google_sign_in doesn't match 1.0.3:
    | | | | | | | | | | | | | | |   trainthebots3 0.0.0 (root) -> google_sign_in 1.0.3 from hosted (google_sign_in)
SLVR: | | | | | | | | | | | | | | version 0.0.2 of google_sign_in doesn't match 1.0.3:
    | | | | | | | | | | | | | | |   trainthebots3 0.0.0 (root) -> google_sign_in 1.0.3 from hosted (google_sign_in)
SLVR: | | | | | | | | | | | | | | version 0.0.1 of google_sign_in doesn't match 1.0.3:
    | | | | | | | | | | | | | | |   trainthebots3 0.0.0 (root) -> google_sign_in 1.0.3 from hosted (google_sign_in)
SLVR: BacktrackingSolver took 0:00:00.446510 seconds.
    | - Tried 1 solutions
    | - Requested 1 version lists
    | - Looked up 0 cached version lists
    | 
FINE: Resolving dependencies finished (0.4s).
ERR : Package google_sign_in has no versions that match 1.0.3 derived from:
    | - trainthebots3 depends on version 1.0.3
FINE: Exception type: NoVersionException
FINE: package:pub/src/entrypoint.dart 195                                           Entrypoint.acquireDependencies
    | package:pub/src/command/get.dart 38                                           GetCommand.run
    | package:args/command_runner.dart 194                                          CommandRunner.runCommand
    | package:pub/src/command_runner.dart 168                                       PubCommandRunner.runCommand.<fn>
    | dart:async                                                                    new Future.sync
    | package:pub/src/utils.dart 102                                                captureErrors.<fn>
    | package:stack_trace                                                           Chain.capture
    | package:pub/src/utils.dart 117                                                captureErrors
    | package:pub/src/command_runner.dart 168                                       PubCommandRunner.runCommand
    | package:pub/src/command_runner.dart 117                                       PubCommandRunner.run
    | /b/build/slave/dart-sdk-mac-dev/build/sdk/third_party/pkg/pub/bin/pub.dart 8  main
    | ===== asynchronous gap ===========================
    | dart:async                                                                    _Completer.completeError
    | package:pub/src/entrypoint.dart 243                                           Entrypoint.acquireDependencies
    | ===== asynchronous gap ===========================
    | dart:async                                                                    _asyncThenWrapperHelper
    | package:pub/src/entrypoint.dart 192                                           Entrypoint.acquireDependencies
    | package:pub/src/command/get.dart 38                                           GetCommand.run
    | package:args/command_runner.dart 194                                          CommandRunner.runCommand
    | ===== asynchronous gap ===========================
    | dart:async                                                                    new Future.microtask
    | package:args/command_runner.dart 142                                          CommandRunner.runCommand
    | package:pub/src/command_runner.dart 168                                       PubCommandRunner.runCommand.<fn>
    | dart:async                                                                    new Future.sync
    | package:pub/src/utils.dart 102                                                captureErrors.<fn>
    | package:stack_trace                                                           Chain.capture
    | package:pub/src/utils.dart 117                                                captureErrors
    | package:pub/src/command_runner.dart 168                                       PubCommandRunner.runCommand
---- End log transcript ----
pub get failed (1)

**Comment by mravn-google** [comment]
@vskr I can reproduce the error above. It appears that neither version 1.0.2 nor version 1.0.3 were ever published even though they are both mentioned in the change log. I'll see if I can rectify that.

You can use version 1.0.1 in the mean time.

**Comment by mravn-google** [comment]
@vskr I have published both the missing versions.

**Comment by vskr** [comment]
Thanks!! It looks like 1.0.3 works now. But the issue of MissingPluginException still remains. But I will close this thread, since we have a discussion for missingpluginexception going on in other thread.
