### ISSUE TITLE
Double Underline During Typing in Japanese Language in TextField in flutter web

### ISSUE THREAD

**Issue by ankit20202** [flutter/flutter#139799]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Install Grammarly for spell check and Open the Flutter web application on the Google Chrome browser on a macOS device (MacBook).
2. Navigate to a screen containing a text input field (using either Fleather package or standard Flutter TextField).
3. Activate the Japanese language input method.
4. Start typing in Japanese characters.

### Expected results

The input should be processed without displaying double underlines during typing, providing a seamless user experience.

![6R1gL](https://github.com/flutter/flutter/assets/138212592/ac8e9fe3-9041-45ec-b42b-8a15ac071523)

### Actual results

During the input of Japanese characters, double underlines appear, creating an undesired visual effect. This behaviour is consistent whether using the Fleather package or the default Flutter TextField.

![nhkwT](https://github.com/flutter/flutter/assets/138212592/fd0b81db-2090-4818-ab32-1c14800c6418)

### Code sample

<details><summary>Code sample</summary>

```dart
TextField(
  maxLines: 5,
 )
    
or
//flether package
FleatherField(
  focusNode: focusNode,
  controller: fleatherController,
  editorKey: globalKey,
),    
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/138212592/ac5aa463-cb3f-48d6-b251-c7e7dd08e63b

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
dreamworld@DREAMWORLDs-iMac-Pro-4 harry % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.3, on macOS 12.6 21G115 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] Connected device (3 available)
[✓] Network resources


```

</details>

**Comment by ankit20202** [comment]
> Hi @ankit20202, you are using an older version of flutter.
> 
> Kindly upgrade to the latest version of flutter to see if you still experience this issue. If you do, please provide the updated output of `flutter doctor -v`
> 
> Thank you

dreamworld@DREAMWORLDs-iMac-Pro-4 harry % flutter doctor -v
[✓] Flutter (Channel stable, 3.16.3, on macOS 12.6 21G115 darwin-x64, locale en-IN)
    • Flutter version 3.16.3 on channel stable at /Users/dreamworld/Documents/flutter_sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0366e0a3f (6 days ago), 2023-12-05 19:46:39 -0800
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/dreamworld/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Connected device (3 available)
    • bad Man (mobile)  • 0d5bjj5496gftrsfb84f09b71acb7183f21af1c • ios            • iOS 16.1.2 20B110
    • macOS (desktop)  • macos                                                                  • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)        • chrome                                   • web-javascript • Google Chrome 119.0.6045.199

[✓] Network resources
    • All expected network resources are available.

• No issues found!

i will try latest version of flutter but still same issue

**Comment by danagbemava-nc** [comment]
Hi @ankit20202, kindly share a link to the grammarly extension. 

Does this bug happen without the grammarly extension in your app?

**Comment by ankit20202** [comment]
Hi @danagbemava-nc ,  i use Grammarly for Mac
[extention](https://app.grammarly.com/apps)

This issue not happen without Grammarly

**Comment by danagbemava-nc** [comment]
Hi @ankit20202, does this happen in other non-flutter web apps? 

I'm guessing grammarly may be injecting their own code which is causing the double underlines
