### ISSUE TITLE
why language button Camera in IOS and Android show English when i set default language device is Japanese

### ISSUE THREAD

**Issue by ha8419988** [flutter/flutter#139719]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

help

### Expected results

help me pls

### Actual results

langue in camera not showing Japanese

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```
![Image from iOS](https://github.com/flutter/flutter/assets/70094460/20e86865-13b3-4de7-8968-50e037ea282a)
![Image from iOS](https://github.com/flutter/flutter/assets/70094460/efea3056-6ff8-49d3-8f2f-b3126f5a1580)

</details>

**Comment by danagbemava-nc** [comment]
You will need to handle this yourself. The picker that comes is a native view as such the plugin doesn't have any control over it but instead the native view picks it from the localisation settings in your app.  See https://flutter.dev/docs/development/accessibility-and-localization/internationalization#localizing-for-ios-updating-the-ios-app-bundle for how you can do this for your app. See also https://github.com/flutter/flutter/issues/63719#issuecomment-757053169

Closing from here as this needs to be done for your app yourself.
