### ISSUE TITLE
New Flutter projects using Gradle 4.1?

### ISSUE THREAD

**Issue by arlucio** [flutter/flutter#13976]
I searched everywhere and just can't understand if the new projects created in flutter (New Flutter Project using Android Studio) should already be using to Gradle 4.1, cause when I create a new project, it is still created using the old version.
 
From this post [https://github.com/flutter/flutter/wiki/Updating-Flutter-projects-to-Gradle-4.1-and-Android-Studio-Gradle-plugin-3.0.1] seems like it, right now, should already be created using the new version, got this conclusion by: "After #13492, Flutter tooling creates projects based on Gradle 4.1 and the Android Studio Gradle plugin version 3.0.1." 

This confuses me even more, I updated everything and still creating projects in the old Gradle version.

**Comment by mravn-google** [comment]
Sorry about the confusion. The Flutter alpha branch has not yet been rolled past #13492 and so still uses Gradle 3.3. Rolling alpha is currently blocked on some regressions:

https://github.com/flutter/flutter/issues/13731
https://github.com/flutter/flutter/issues/13742

The Flutter master branch uses Gradle 4.1.

I suggest you either:
* Stay on alpha, using Gradle 3.3. Make sure you only depend on plugins (or plugin versions) that also use Gradle 3.3.
* Temporarily switch to master, create project, then go back to alpha:
   ```text
   flutter channel master
   flutter create myproject
   flutter channel alpha
   ```
   Then your new project will use Gradle 4.1 and you can use upgraded plugins. You'll get some deprecation warnings from Gradle as you build which will go away once alpha rolls past #13492.
* Switch to master and work from there. Beware, this is bleeding edge though.

**Comment by mit-mit** [comment]
Closing issue, let us know if there is anything else we can do to help @arlucio
