### ISSUE TITLE
It is unclear if the Flavors feature is meant to be supported for macOS

### ISSUE THREAD

**Issue by andrewkolos** [flutter/flutter#139774]
## Context

The Flavors feature allows flutter users to have multiple native build configurations that the user can choose between by using the `--flavor` option in `flutter run` and `flutter build`. See [Create flavors of a Flutter app](https://docs.flutter.dev/deployment/flavors) to learn more about the feature.

## Problem

The feature works (to my knowledge) for Android, iOS, and macOS. However, macOS support is not documented and is not under test[^1]. This was brought to attention during review of [#139045](https://github.com/flutter/flutter/pull/139045#discussion_r1419271332), which will explicitly disable use of `--flavor` in `flutter run` for platforms that don't support it. 

The question then is, is macOS meant to be supported by the flavors feature? At the time of its introduction, it was a decently popular request (see https://github.com/flutter/flutter/issues/64088), which makes me question whether I should make it explicitly unsupported.

[^1]: It was initially under test, but it doesn't look like the test ever passed to begin with? See https://github.com/flutter/flutter/pull/125581

**Comment by andrewkolos** [comment]
Since the Xcode tooling underlying macOS and iOS is similar (if not identical), flavor support for macOS might have a low maintenance burden. I will set aside some time to investigate getting this back under test. If I'm able to do that, I would not mind officially documenting it as well.

**Comment by andrewkolos** [comment]
Since this functionality is [back under test](https://github.com/flutter/flutter/pull/140647) and https://github.com/flutter/website/issues/9988 is tracking the need for documentation of flavors support for macOS, I will be closing this issue as completed.

**Comment by cbracken** [comment]
Thanks for fixing. 

As you discovered, this was intended to work but the person who was working on it left Google last year and the work was not completely finished (documentation in particular, but also the test flakiness).
