### ISSUE TITLE
Socks5 Proxy

### ISSUE THREAD

**Issue by xAffan** [flutter/flutter#139729]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Unable to use a socks5 proxy with DNS resolution, only managed to route through requests without DNS resolution.

### Proposal

Add proper proxy (socks5) support to the core HTTP package

**Comment by danagbemava-nc** [comment]
The http package lives in a separate repo. As such this should be reported there. 

Closing from here. 

Thank you
