### ISSUE TITLE
ColorFiltered extends beyond Positioned widgets in Stack

### ISSUE THREAD

**Issue by TNorbury** [flutter/flutter#139777]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a `Stack` with `Positioned` widgets
2. Add a `ColorFiltered` somewhere in the widget tree beneath a `Positioned` widget
3. Run the app

Other important notes:
* This issue only appeared after upgrading to Flutter 3.13. It still appears on Flutter 3.16.
* When Impeller is enabled the issue goes away (but we've decided internally that Impeller isn't ready for our Android app at the moment)
* Reproducible on both Android and iOS (with impeller disabled) 

### Expected results

The color filtering should be applied to and contained within the positioned widget. In the provided code example, it should just cover each "box"

### Actual results

The filtering extends beyond the "box", and even covers/obscures all the `Positioned` widgets that're below the one with the filtering in the `Stack`.

### Code sample

<details><summary>Code sample</summary>

[Dartpad](https://dartpad.dev/?id=1e8306cc86382b1b45188abfdacea4ac)
</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>
Screenshots from production app. The "widget" with the dropdown coming out of it is the one that has the filter applied to it

![Screenshot_20231207-153434](https://github.com/flutter/flutter/assets/16006381/563c847c-3875-4707-9e20-7f917c853aae)

![Screenshot_20231207-153436](https://github.com/flutter/flutter/assets/16006381/353ff99d-472e-4848-8fcc-b6fc60853681)

Here is an additional screenshot from the repo example:
<img width="753" alt="image" src="https://github.com/flutter/flutter/assets/16006381/82a350e4-677d-4a36-a358-7efef265a1e7">

An example of what it should look like:
![simulator_screenshot_25520DC2-7B0D-4398-A92A-5DFA22E51966](https://github.com/flutter/flutter/assets/16006381/7d66d5e1-c609-4b74-abd5-ffb9f51aa60b)

</details>

### Logs

<details><summary>Logs</summary>
Not including logs as I didn't see anything out of the ordinary even with verbose enabled.

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.1.1 23B81 darwin-arm64, locale en-US)
    • Flutter version 3.13.9 on channel stable at /Users/tyler/fvm/versions/3.13.9
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (6 weeks ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/tyler/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (4 available)
    • Pixel 6a (mobile)       • 27061JEGR06958            • android-arm64  • Android 14 (API 34)
    • Tyler’s iPhone (mobile) • 00008030-000C75E90A09802E • ios            • iOS 17.1.2 21B101
    • macOS (desktop)         • macos                     • darwin-arm64   • macOS 14.1.1 23B81 darwin-arm64
    • Chrome (web)            • chrome                    • web-javascript • Google Chrome 120.0.6099.71

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the detailed report @TNorbury 
I ran the code sample using latest stable (3.16) and observed below, but am not sure what's the expected result is. Can you elaborate based on the example provided ?

<img width="539" alt="Screenshot 2023-12-08 at 2 12 44 PM" src="https://github.com/flutter/flutter/assets/67046386/210d32d9-7ede-4a3a-9d67-339964f48168">

**Comment by TNorbury** [comment]
Yeah, so the expected result is that "Box 4" would have a blue-grey color filtered applied to it. In your screenshot it appears to be working (though I do see a thin vertical band right next to Box 4, on the left side, which I don't believe should be there.)

Running the example on my physical android device (with Flutter 3.16.1), I get this result, which I would describe as expected:
![Screenshot_20231208-082416](https://github.com/flutter/flutter/assets/16006381/fe0b22d9-7a3c-4181-a2bb-dd79902a7f16)
Which is interesting because if the example is run on dartpad, I get the bugged behavior... Running the code in a local web build also results in bugged behavior. Running a MacOS results in the expected behavior...
I also tried running our production app on 3.16.1 and I still get the bugged behavior there

But in short I would describe the behavior as: ColorFiltered should only be applied within the 250x250 area (or whatever the size) described by its parent Positioned widget. However what happens is it fills the entire stack (and possibly beyond) and obscures any widgets which are below (i.e. come before in the Stack's children) the Positioned which has the ColorFiltered has a child

**Comment by TNorbury** [comment]
Also, including a screenshot of box 4 without the color filter, to help illustrate the change the filter does:
<img width="270" alt="image" src="https://github.com/flutter/flutter/assets/16006381/5f235bdd-6836-43f8-a97b-f3d84493bc84">

**Comment by darshankawar** [comment]
Thanks for the update. Can you take a look at [this](https://github.com/flutter/flutter/issues/98809) issue and check if it resembles your case or not ?

**Comment by TNorbury** [comment]
Yeah, that looks exactly like my issue. In fact if I change the code example to use a `Column` or `Row`, I get the same bugged behavior.

I'll try the workaround mentioned [here](https://github.com/flutter/flutter/issues/98809#issuecomment-1049730520) and get back to you.

**Comment by TNorbury** [comment]
Ok, I've tried the workaround on both my sample and production app, and the issue appears to be solved! So thank you for pointing me to that!

My question now is, is this behavior actually a bug? Or is using a `ClipRect` actually what is intended? My suspicion is the former, as this issue only showed up as of v3.13.x and the this code has been in our app since early versions of Flutter 2.

Thank you!

**Comment by darshankawar** [comment]
Good to know the linked issue helped you to resolve your case. I'll go ahead and close this issue.



> is this behavior actually a bug? Or is using a `ClipRect` actually what is intended?

You may share your findings in the original issue so that it'll be better for tracking.
