### ISSUE TITLE
Not getting any events after exceeding maximum retry of Face ID in iOS

### ISSUE THREAD

**Issue by SreehariCodewave** [flutter/flutter#139789]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run the app on ios
2. execute await localAuth.authenticate
3. Make authentication failure until reaches maximum retry.
4. post maximum retries, the biometric popup doesn't open nor there is any error message or crash. 

### Expected results

it should throw warning or event to identify the maximum limit breach. 

### Actual results

After exceeding maximum retry limit, **_await localAuth.authenticate_** is not triggering any events

### Code sample

<details><summary>Code sample</summary>

```dart
 bool checkBioStatus = await localAuth.canCheckBiometrics;
      if (checkBioStatus) {
      
        didAuthenticate = await localAuth.authenticate(
          localizedReason: "Login",
          authMessages: [
            AndroidAuthMessages(
              signInTitle: "Title",
              cancelButton: "Use Pin",
              biometricHint: "",
              goToSettingsButton: "Settings",
              goToSettingsDescription: "Please setup biometric authentication in the device to login using fingerprint.",
            ),
          ],
          options: const AuthenticationOptions(
            useErrorDialogs: true,
            stickyAuth: false,
            sensitiveTransaction: true,
            biometricOnly: true,
          ),
        );
        if (didAuthenticate) {
          if (mounted) {
          ///Actions here
          }
        }
      }
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.7, on macOS 14.0 23A344 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.83.1)
[✓] Connected device (3 available)
    ! Error: Browsing on the local area network for iPhone 13. Ensure the device is unlocked and attached with a cable or associated with the
      same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!

**Comment by huycozy** [comment]
Hi @SreehariCodewave 
When exceeding the maximum retries, do you see this warning message: "Biometric authentication is disabled. Please lock and unlock your screen to enable it."?

My device does not support Face ID but fingerprint. It continues working after locking and unlocking device's screen.

**Comment by SreehariCodewave** [comment]
@huycozy , I'm getting a message as Face ID attempts exceeded. 

I'm attaching the screen record with this comment

https://github.com/flutter/flutter/assets/144121857/99608982-fdc7-4c71-b56f-cef05d2bd9b7

**Comment by huycozy** [comment]
I checked this on emulator and also asked my colleague @dam-ease to check this on her physical device (iPhone 13, iOS 17.1.1) as well. We both can't trigger the error `Face ID attempts exceeded`. 

I wonder if there are any specific settings on the device. If there are, can you please share?

Please also confirm this issue with [plugin example](https://github.com/flutter/packages/tree/main/packages/local_auth/local_auth/example) to see if the issue persists or not. Thank you!
