### ISSUE TITLE
Android 12+ Splash Screen didn't show windowSplashScreenBrandingImage and windowSplashScreenAnimatedIcon when first-time opening

### ISSUE THREAD

**Issue by huongrealest** [flutter/flutter#139714]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create native splash
2. Build apk
3. install on Android 12+ Device

### Expected results

show windowSplashScreenAnimatedIcon and windowSplashScreenBrandingImage when first-time opening

### Actual results

didn't show windowSplashScreenBrandingImage and windowSplashScreenAnimatedIcon when first-time opening

### Code sample

<details><summary>Code sample</summary>

```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <!-- Theme applied to the Android Window while the process is starting when the OS's Dark Mode setting is off -->
    <style name="LaunchTheme" parent="@android:style/Theme.Light.NoTitleBar">
        <item name="android:forceDarkAllowed">false</item>
        <item name="android:windowFullscreen">false</item>
        <item name="android:windowDrawsSystemBarBackgrounds">false</item>
        <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>
        <item name="android:windowSplashScreenBackground">#093F47</item>
        <item name="android:windowSplashScreenBrandingImage">@drawable/android12branding</item>
        <item name="android:windowSplashScreenAnimatedIcon">@drawable/android12splash</item>
    </style>
    <!-- Theme applied to the Android Window as soon as the process has started.
         This theme determines the color of the Android Window while your
         Flutter UI initializes, as well as behind your Flutter UI while its
         running.
         
         This Theme is only used starting with V2 of Flutter's Android embedding. -->
    <style name="NormalTheme" parent="@android:style/Theme.Light.NoTitleBar">
        <item name="android:windowBackground">?android:colorBackground</item>
    </style>
</resources>

```

</details>

### Flutter Doctor output

[!] Flutter (Channel stable, 3.16.2, on Microsoft Windows [Version 10.0.19045.3693], locale en-US)
    • Flutter version 3.16.2 on channel stable at C:\Users\Admin\fvm\versions\3.16.2
    ! Warning: `flutter` on your path resolves to C:\Users\Admin\fvm\versions\3.16.0\bin\flutter, which is not inside your current Flutter SDK checkout at C:\Users\Admin\fvm\versions\3.16.2. Consider adding C:\Users\Admin\fvm\versions\3.16.2\bin to the front of your path.
    ! Warning: `dart` on your path resolves to C:\Users\Admin\fvm\versions\3.16.0\bin\dart, which is not inside your current Flutter SDK checkout at C:\Users\Admin\fvm\versions\3.16.2. Consider adding C:\Users\Admin\fvm\versions\3.16.2\bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9e1c857886 (6 days ago), 2023-11-30 11:51:18 -0600
    • Engine revision cf7a9d0800
    • Dart version 3.2.2
    • DevTools version 2.28.3
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.31)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.34114.132
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.84.2)
    • VS Code at C:\Users\Admin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.78.0

[√] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19045.3693]
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 119.0.2151.97

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

**Comment by huycozy** [comment]
Hi @huongrealest 
I checked this with a newly created Flutter project on `Pixel 7, Android 14` but I saw splash screen still show those images at the first time. Please also try again on a new project to see if it works. You can use my below style (I use the existing `ic_launcher` for those images)

```xml
    <style name="LaunchTheme" parent="@android:style/Theme.Light.NoTitleBar">
        <item name="android:forceDarkAllowed">false</item>
        <item name="android:windowFullscreen">false</item>
        <item name="android:windowDrawsSystemBarBackgrounds">false</item>
        <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>
        <item name="android:windowSplashScreenBackground">#093F47</item>
        <item name="android:windowSplashScreenBrandingImage">@mipmap/ic_launcher</item>
        <item name="android:windowSplashScreenAnimatedIcon">@mipmap/ic_launcher</item>
    </style>
```
