### ISSUE TITLE
Scrollbars Blink diagonal

### ISSUE THREAD

**Issue by vccz123** [flutter/flutter#139849]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Execute the Code 

### Expected results

Scrollbars diagonal without blink effect

### Actual results

By running the code the scrollbars vertical and horizontal work fine if only drag to that direction, but if i move diagonal they start blinking together

### Code sample

https://dartpad.dev/?id=3f4abba5b80f36fad86ed64b4c90621e

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

´

**Comment by darshankawar** [comment]
Thanks for the report @vccz123 
I do see the same behavior as reported using code sample provided. I see that you are using custom implementation for `TwoDimensionalGridView`. Instead, can you check using https://pub.dev/packages/two_dimensional_scrollables package and see if using it you get expected behaviour or not ?

**Comment by vccz123** [comment]
I'll take a look at it with the two_dimensional_scrollables. What I ultimately want is that I have a grid view like in the code, which also shows me vertical and horizontal scroll bars, but diagonal panning is also possible. For my project, which is a drawing app, I want to be able to move around the canvas using touch gestures also diagonally, but also display scroll bars that should indicate when I reach the edge of my limited canvas(Drawing Space). The Code in the Dartpad indeed does what i want only the Scrollbars behave strange. I dont know if i can achieve the same result with the two_dimensional_scrollables package. I will try it out.
