### ISSUE TITLE
[http] Flutter Web cannot make simple get requests `XMLHttpRequest error`

### ISSUE THREAD

**Issue by mariopepe** [flutter/flutter#139819]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. use the reproducible code
2. Compile for Flutter web
3. try to access the url mentioned by pressing the "LOL" button: https://download.samplelib.com/mp3/sample-3s.mp3
4. see the error `XMLHttpRequest` (can read entire stack in section "Actual results")

Note 1: resource is accessible from browser by typing the url
Note 2: resource is accessible from Postman by making get request
**Note 3: this code works perfectly on iOS, problem is only on web**

### Expected results

I can access the online resource as much as I can with my browser by typing the url or by making a Postman request

### Actual results

```
Error: ClientException: XMLHttpRequest error., uri=https://download.samplelib.com/mp3/sample-3s.mp3
    dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 941:28  get current
packages/http/src/browser_client.dart 95:22                         <fn>
dart-sdk/lib/async/zone.dart 1661:54                                runUnary
dart-sdk/lib/async/future_impl.dart 162:18                          handleValue
dart-sdk/lib/async/future_impl.dart 846:44                          handleValueCallback
dart-sdk/lib/async/future_impl.dart 875:13                          _propagateToListeners
dart-sdk/lib/async/future_impl.dart 638:7                           [_complete]
dart-sdk/lib/async/stream_pipe.dart 59:43                           <fn>
dart-sdk/lib/async/zone.dart 1655:54                                run
dart-sdk/lib/async/future_impl.dart 205:18                          handleWhenComplete
dart-sdk/lib/async/future_impl.dart 816:38                          handleWhenCompleteCallback
dart-sdk/lib/async/future_impl.dart 872:11                          _propagateToListeners
dart-sdk/lib/async/future_impl.dart 647:5                           [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 721:7                           callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                    _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                     _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7  <fn>


dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 327:10  createErrorWithStack
dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 337:28            _throw
dart-sdk/lib/core/errors.dart 120:5                                           throwWithStackTrace
dart-sdk/lib/async/zone.dart 1386:11                                          callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7            <fn>
```

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('flutter web lol')),
        body: Center(
          child: ElevatedButton(
            onPressed: () async {
              final response = await http.get(
                Uri.parse('https://download.samplelib.com/mp3/sample-3s.mp3'),
              );

              print(response.body);
            },
            child: const Text('LOL'),
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

Successful request on Postman
<img width="773" alt="Screenshot 2023-12-08 at 19 15 38" src="https://github.com/flutter/flutter/assets/14803862/20701c42-994b-4a60-bb62-acf5f53ee190">

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.3, on macOS 14.1.2 23B92 darwin-arm64, locale en-US)
    • Flutter version 3.16.3 on channel stable at /Users/mariopepe/development/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0366e0a3f (3 days ago), 2023-12-05 19:46:39 -0800
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/mariopepe/Library/Android/sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio OLD.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (4 available)
    • iPhone di MP2 (mobile) • 00008110-001E04D02122801E            • ios            • iOS 17.1.2 21B101
    • iPhone 15 Pro (mobile) • BD5A06D8-A887-4346-A3CA-11FB24D4DF0D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 14.1.2 23B92 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 119.0.6045.199

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by navaronbracke** [comment]
Are you getting any errors in the browser's console? `XMLHttpRequest error.` points to a network-level error for the request.

Since you said that this works on iOS and Postman, I _think_ this might be a CORS error on your end.
CORS is a security policy that affects browsers only (which would explain why you see this happen only on web)

**Comment by mariopepe** [comment]
It works as expected with  `flutter run -d chrome --web-browser-flag "--disable-web-security"`

Wouldn't it be possible to make this behavior the default?
Or to add a flag in the material app, or in the main or somewhere else?

Making http requests to an external domain seems like a common scenario in 2023 web-apps.

similar to how we do
```dart
/// Remove the # from the URL
usePathUrlStrategy();
```

We could have something like `allowExternalEHttpRequests()`

**Comment by navaronbracke** [comment]
The CORS policy is something that is done server-side, the server has to return the `Access-Control-Allow-Origin` header,
with the value set to the domain that you are requesting the resource with.
I.e. if your Flutter Web application is hosted at "https://mydomain.com", the server has to include that domain in the value for that header.

That is why you should look for errors in the browser console. If the request is blocked by CORS, you will have errors
that indicate an invalid value for the `Access-Control-Allow-Origin` header.

See the explanation here https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

Disabling CORS is a security risk, as CORS is a protection layer for the browser.

**Comment by mariopepe** [comment]
Sorry I do not understand.

So you are proposing that if I want to display on my flutter web app:
- a simple `.mp3` file hosted on some domain
- an image hosted on Imgur or Flickr
- a map from Mapbox obtained from their API which I pay for etc.

(all things that clearly do not include my domain in the value for that header).

Then I should go knock knock at the doors of these corporations and say _"hey, so Flutter web does not allow me to access your resources unless you allow www.my-little-flutter-app.com domain in your server, can you do it asap? Thanks, cheers."_

Or what are you exactly proposing?

Thank you

**Comment by darshankawar** [comment]
@mariopepe 
Take a look at [this](https://github.com/flutter/flutter/issues/74123) and check if it helps in your case or not related to the error you are getting.
