### ISSUE TITLE
Nesting a hero should assert

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1398]

**Comment by spkersten** [comment]
I can see use cases where nesting Hero's could be useful in combination with nested Navigators. Having a single widget wrapped with two Hero could be useful when transitions in different Navigators should use different Hero animations (flight shuttles). For clarity, I currently don't have this need, but it seems unnecessary to restrict this.

**Comment by esarbanis** [comment]
Right now a nested Hero always asserts, but couldn't we provide a way to opt-out from this behavior? Something like a `strictMode` property which defaults to `true`?

**Comment by Hixie** [comment]
If you have a use case for which the framework is asserting, please file a new bug and we can study it. Thanks!

**Comment by 5hanth** [comment]
could have been "Nesting a Hero with same hero tags should assert" 🤤
