### ISSUE TITLE
Forever issue with material app, router, theme..

### ISSUE THREAD

**Issue by mnts** [flutter/flutter#139860]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Why flutter tream is enforcing to have entire screen changed per route? 

### Proposal

what if I want to have widgets on top of router, like drawers and app bar or at least could I just use one same theme in top level without going through all kinds of errors?

**Comment by moffatman** [comment]
Put the Navigator below your stuff...

**Comment by darshankawar** [comment]
@mnts 
Check above comment / solution and see if it helps.
If not, provide complete code sample that shows actual result you are seeing.
