### ISSUE TITLE
[two_dimension_scrollable] allow to scroll in other dimension without having to wait for the scroll to stop

### ISSUE THREAD

**Issue by ThanhDat-Vo** [flutter/flutter#139842]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Currently, when user scrolls in Axis.horizontal, he has to wait for the scroll to stop completely, before start scroll in Axis.vertical and vice versa.
This cause a delay, which is not a good UX

### Proposal

Please help to allow user to change scroll direction without waiting for the scroll to stop.
This is an example
https://gearheart.io/_next/image/?url=https%3A%2F%2Fapi.gearheart.io%2Fuploads%2Ffast_frozen_scroll_20230303_155855_6824d8f31b.gif&w=3840&q=75

**Comment by Piinks** [comment]
Hi @ThanhDat-Vo this was fixed by https://github.com/flutter/flutter/pull/138442 which should be available in the next stable release.
