### ISSUE TITLE
[google_maps_flutter] API key management is unsafe & this is DANGEROUSLY omitted in docs & is not compliant with GoogleMaps official docs

### ISSUE THREAD

**Issue by mariopepe** [flutter/flutter#139879]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Open [google_maps_flutter](https://pub.dev/packages/google_maps_flutter) on pub.dev
2. check the documentation for Android, iOS and Web
3. In all three platforms the API key to access Google Maps is hardcoded & easily accessible from an unskilled script kid
   - iOS: in `ios/Runner/AppDelegate.swift`
   - Android: in `android/app/src/main/AndroidManifest.xml`
   - Web: in `web/index.html`
4. Then check google maps official documentation at the section "[API security best practices](https://developers.google.com/maps/api-security-best-practices)"

You will see the following text:

> To protect mobile apps, use a secure keystore or secure proxy server:
>
> - Store the API key or signing secret in a secure keystore. This step makes it harder to scrape API keys and other private data directly from the application.
> 
> - Use a secure proxy server. The proxy server provides a solid source for interacting with the appropriate Google Maps Platform API. For more information about using a proxy server, see [Living Vicariously: Using Proxy Servers with the Google Data API Client Libraries](https://developers.google.com/gdata/articles/proxy_setup). 
> Construct your Google Maps Platform requests on the proxy server. Don't allow clients to relay arbitrary API calls via the proxy.
> Post-process the Google Maps Platform responses on your proxy server. Filter out data that the client doesn't need.

I don't see how this plugin is compliant with that.

[Plugin first version is from Nov 28, 2018 (i.e. 5 years ago)]
[Keeping this issue for when my API key will be abused and I will refuse to pay the bill]

### Expected results

Proper implementation would be possible and explained in Docs.

If proper implementation in Flutter is impossible for some reason (we landed on the moon tho) at least it should be properly specified in the docs

### Actual results

Implementation is not proper

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by stuartmorgan** [comment]
> 4. Then check google maps official documentation at the section "[API security best practices](https://developers.google.com/maps/api-security-best-practices)"
> 
> You will see the following text:

You've quoted the contents of the section titled "Protect your API key and signing secret in mobile apps using web services or Static Web APIs".

> I don't see how this plugin is compliant with that.

This plugin doesn't use web services or Static Web APIs in mobile apps, it uses the mobile SDKs.

The README is only intended to describe setup for the plugin. If you are using Google Maps APIs through some other means rather than the plugin, you should certainly follow the documentation for that rather than the plugin's README.
