### ISSUE TITLE
add feature to remove counter text because it took space if i set it to empty string it will take space too 

### ISSUE THREAD

**Issue by abdelrahman-abied** [flutter/flutter#139884]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

![Screenshot 2023-12-10 at 11 16 30 PM](https://github.com/flutter/flutter/assets/31194055/d4c1c311-e3e6-458d-b737-7cab13a699ca)
![Screenshot 2023-12-10 at 11 17 40 PM](https://github.com/flutter/flutter/assets/31194055/9c3d7d1d-f4bb-465c-b6b7-d38c17b0ca73)

### Proposal

how to remove space if i set maxlength of textformfield  but i want to remove space in this case from counter text

**Comment by darshankawar** [comment]
@abdelrahman-abied
I think your question is more suited for support channels like StackOverflow so please ask the same there.
Closing from here, as this is more of a `how to` support question which can have existing solutions on support platforms.
If you disagree, write in comments and I'll reopen it.

**Comment by abdelrahman-abied** [comment]
I disagree with that because I haven't found a solution or trick to do that why I need extra space in my widget if I don't want length counter

**Comment by darshankawar** [comment]
Thanks for feedback @abdelrahman-abied 
Looking into https://api.flutter.dev/flutter/material/InputDecoration/counterText.html, it says:

`If null or an empty string and [counter](https://api.flutter.dev/flutter/material/InputDecoration/counter.html) isn't specified, then nothing will appear in the counter's location.`
So check the https://api.flutter.dev/flutter/material/InputDecoration/counter.html widget and see if it helps in your case or not.

Removing the counterText doesn't seem to be a feasible proposal as it is a part of material design standard.
