### ISSUE TITLE
Detect or document `cocoapods` broken w/ High Sierra update

### ISSUE THREAD

**Issue by pq** [flutter/flutter#13980]
The update to High Sierra leaves `brew`-installed `cocoapods` in a broken state.  

```
[~/src/repos/audio/ios] (master) $ pod setup
/Users/pquitslund/homebrew/bin/pod: /Users/pquitslund/homebrew/Cellar/cocoapods/1.3.1/libexec/bin/pod: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby: bad interpreter: No such file or directory
/Users/pquitslund/homebrew/bin/pod: line 2: /Users/pquitslund/homebrew/Cellar/cocoapods/1.3.1/libexec/bin/pod: Undefined error: 0
```

The correct recourse is:

    brew uninstall cocoapods; brew install cocoapods

FWIW the issue seems to be stale pod symlink and is likely something we could detect and report via `flutter doctor`.  Chatting w/ @cbracken he proposed:

> I bet we could check if the `pod` on the path is a symlink to a versioned ruby dir, and then when doctor discovers that cocoapods is screwed up, instead of reporting something about version 1.0.0 or better, we could provide more precise instructions... like maybe if ruby is also under the homebrew install dir, just report to uninstall and reinstall

Alternatively, we might just document the issue (if we haven't already 😉 ).

**Comment by neiljaywarner** [comment]
Hmmh. I still get this even when i uninstall and reinstall as above, and I'm not on High Sierra but just Sierra :(
@xster

**Comment by iapicca** [comment]
Hi @pq is this issue still meant to be open?

**Comment by ozzy1873** [comment]
This same thing just happened to me when I upgraded to Catalina. Reinstalling cocoapods seems to have fixed it.

**Comment by iapicca** [comment]
HI @pq 
does @ozzy1873 solution works for you?
thank you

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
