### ISSUE TITLE
Android webvbiew location.replace not working as expected

### ISSUE THREAD

**Issue by zhanyuzhang** [flutter/flutter#139894]
### Is there an existing issue for this?

- [X] I have searched the [existing package issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Apackage)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### What package does this bug report belong to?

webview_flutter

### What target platforms are you seeing this bug on?

Android

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
 webview_flutter:
    dependency: "direct main"
    description:
      name: webview_flutter
      sha256: "789d52bd789373cc1e100fb634af2127e86c99cf9abde09499743270c5de8d00"
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "4.2.2"
```

</details>

### Steps to reproduce

I have an Android webview with a page that redirects to another page, using location.replace(url).
Lets say that I have page "A" that redirects to page "B" (using location.replace). When pressing "back" button from page "B", the page returns to page "A", which redirects it to page "B" again. When I debug the history api (history.length), I can clearly see that on page "B" the length has incremented in "1" (only on Android 4.X webview. On iOS / web browser / Android 2.X it remains the same), which is a bug! (location.replace shouldn't change history.lenght!)

### Expected results

Location.replace shouldn't change history.lenght

### Actual results

location.replace change history.lenght

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Videos

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Hi @zhanyuzhang 
This could be similar to https://github.com/flutter/flutter/issues/137737. Please check if it's a similar issue. Otherwise, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well.

Thank you!

**Comment by zhanyuzhang** [comment]
> Hi @zhanyuzhang This could be similar to #137737. Please check if it's a similar issue. Otherwise, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the output of `flutter doctor -v` as well.
> 
> Thank you!

Yeah , it's a similar issue. You can close this issue now.

**Comment by huycozy** [comment]
Thanks for confirming that. Closing this as a duplicate.
