### ISSUE TITLE
[two_dimension_scrollable] add vertical and horizontal scroll bars when scroll in 2 dimensions

### ISSUE THREAD

**Issue by ThanhDat-Vo** [flutter/flutter#139840]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Currently when user scrolls in 2 table view, there are now vertical and horizontal scroll bars to tell the relative position.

### Proposal

Please make it possible to implement vertical and horizontal scroll bars to the table

**Comment by Piinks** [comment]
Hi @ThanhDat-Vo you can apply scrollbars to the TableView multiple ways. The Scrollbar widget can be wrapped around the TableView, or you can use the ScrollBehavior.buildScrollbars to wrap it in scrollbars that way.
