### ISSUE TITLE
Error installing BoringSSL-GRPC

### ISSUE THREAD

**Issue by alasriaj** [flutter/flutter#139855]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

pod install          

### Expected results

Analyzing dependencies
cloud_firestore: Using Firebase SDK version '10.18.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '10.18.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '10.18.0' defined in 'firebase_core'
Downloading dependencies
Installing BoringSSL-GRPC (0.0.24)

[!] Error installing BoringSSL-GRPC
[!] /usr/local/bin/git clone https://github.com/google/boringssl.git /var/folders/cx/0b3w0kh143gg1cwn1h4z0cnc0000gn/T/d20231209-14513-10dmu5e --template=

Cloning into '/var/folders/cx/0b3w0kh143gg1cwn1h4z0cnc0000gn/T/d20231209-14513-10dmu5e'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
error: 5138 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

### Actual results

build pod sucess

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by OlegNovosad** [comment]
Same issue here.

**Comment by alasriaj** [comment]
[✓] Flutter (Channel stable, 3.16.3, on macOS 13.1 22C65 darwin-x64, locale en-US)
    • Flutter version 3.16.3 on channel stable at /Volumes/Project/Sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0366e0a3f (4 days ago), 2023-12-05 19:46:39 -0800
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4
                                                                                                                                                                     [✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Volumes/Project/Sdk/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.1 22C65 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 117.0.5938.149

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by danagbemava-nc** [comment]
This is not a flutter issue. 

Please make sure your internet connectivity is not disrupted while you're running `pod install`. Please also make sure you're using the latest versions of the firebase plugins. 

You may also try https://github.com/grpc/grpc/issues/32489

If the issue still persists, please file an issue on the flutterfire repo so that it can be properly addressed. 

Closing from here as grpc is a dependency of firebase and not related to this repo.

**Comment by benthecodeguru** [comment]
I am facing the same issue. started a few days ago. 
All my projects have been working just fine. 

[!] Error installing BoringSSL-GRPC
[!] /usr/local/bin/git clone https://github.com/google/boringssl.git /var/folders/c_/wgtbyrld1_712cmlcgw0_w080000gr/T/d20231211-24878-zhv447 --template=

Cloning into '/var/folders/c_/wgtbyrld1_712cmlcgw0_w080000gr/T/d20231211-24878-zhv447'...
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly before end of the underlying stream
error: 4372 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

**Comment by umairkhan24** [comment]
> I am facing the same issue. started a few days ago. All my projects have been working just fine.
> 
> [!] Error installing BoringSSL-GRPC [!] /usr/local/bin/git clone https://github.com/google/boringssl.git /var/folders/c_/wgtbyrld1_712cmlcgw0_w080000gr/T/d20231211-24878-zhv447 --template=
> 
> Cloning into '/var/folders/c_/wgtbyrld1_712cmlcgw0_w080000gr/T/d20231211-24878-zhv447'... error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly before end of the underlying stream error: 4372 bytes of body are still expected fetch-pack: unexpected disconnect while reading sideband packet fatal: early EOF fatal: fetch-pack: invalid index-pack output

@benthecodeguru Did you find a solution for this? I suddenly started to face this same issue

**Comment by OlegNovosad** [comment]
For others here.

Ok, so I haven't done anything special so far. I've updated dependencies to the latest, removed `Pods` folder and `Podfile.lock` and suddenly it worked. Probably there was some issue on the boringssl access via network.

**Comment by benthecodeguru** [comment]
@OlegNovosad
what version of Dart are u using in your project?

**Comment by OlegNovosad** [comment]
@benthecodeguru 
Dart 3.2.3, Flutter 3.16.4

**Comment by benthecodeguru** [comment]
Worked for me after running the project in VSCode. I was previously using Android Studio

**Comment by benthecodeguru** [comment]
@umairkhan24 yes I found a solution. what worked for me was I ran the same command in vscode rather than android studio. Also I switched internet for a faster network for the command to run successfuly

**Comment by ganzyhax** [comment]
I have samw problem changed internet did't help, I work on VS

**Comment by ganzyhax** [comment]
[!] Error installing BoringSSL-GRPC
[!] /usr/bin/git clone https://github.com/google/boringssl.git /var/folders/rf/8kbh7fpd4gsgjv36hkf4ygtr0000gn/T/d20231230-83313-2jpu8e --template=

Cloning into '/var/folders/rf/8kbh7fpd4gsgjv36hkf4ygtr0000gn/T/d20231230-83313-2jpu8e'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
error: 4700 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
