### ISSUE TITLE
Unable to remove constraint (flutter pub add)

### ISSUE THREAD

**Issue by superbonaci** [flutter/flutter#139881]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Create a constraint
```
$ flutter pub add dev:hive_generator:^2.0.1
"hive_generator" is already in "dev_dependencies". Will try to update the constraint.
Resolving dependencies...
```

### Expected results

Try to undo it

### Actual results

Does not work:
```
$ flutter pub del dev:hive_generator:^2.0.1
Could not find a subcommand named "del" for "flutter pub".

Did you mean one of these?
  get



Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
```
doesn't either
```
$ flutter pub rem dev:hive_generator:^2.0.1
Could not find a subcommand named "rem" for "flutter pub".

Did you mean one of these?
  get



Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
```

Can somebody explain why this is so difficult to operate?

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
You are using the wrong command to remove packages. 

The right command is `flutter pub remove <package_name_here>`

Closing as this is not a flutter issue. 

Thank you
