### ISSUE TITLE
iOS integration test does not work with the latest version of flutter

### ISSUE THREAD

**Issue by mattbodley** [flutter/flutter#139850]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Use latest version of flutter/dart and run recommended setup for integration testing : 

```flutter drive --driver=test_driver/integration_test.dart --flavor=qa -t lib/main_qa.dart --target=integration_test/boot_test.dart```

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.0, on macOS 14.1.2 23B2091 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.84.2)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!

### Expected results

It should load on IOS and execute tests

### Actual results

The iOS emulator/device loads the app but it just waits and does nothing, in the trace log it says:

```VMServiceFlutterDriver: Flutter Driver extension is taking a long time to become available. Ensure your test app (often "lib/main.dart") imports "package:flutter_driver/driver_extension.dart" and calls enableFlutterDriverExtension() as the first call in main().```

### Code sample

<details><summary>/integration_test/boot_test.dart</summary>

```dart
import 'package:flutter_signin_button/button_view.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:app/constants.dart';

import 'package:app/main_qa.dart' as app;

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  testWidgets("boot up test", (WidgetTester tester) async {
    app.main();
    await tester.pumpAndSettle();

    expect(find.byType(SignInButton), findsOneWidget);
    expect(find.text(kSignInButtonText), findsOneWidget);
  });
}

```

</details>

<details><summary>/test_driver/integration_test.dart</summary>

```dart
import 'package:integration_test/integration_test_driver.dart';

Future<void> main() => integrationDriver();

```

</details>

<details><summary>CLI</summary>

```command line
flutter drive --driver=test_driver/integration_test.dart --flavor=qa -t lib/main_qa.dart --target=integration_test/boot_test.dart

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
VMServiceFlutterDriver: Flutter Driver extension is taking a long time to become available. Ensure your test app (often "lib/main.dart") imports "package:flutter_driver/driver_extension.dart" and calls enableFlutterDriverExtension() as the first call in main().
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.0, on macOS 14.1.2 23B2091 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.84.2)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @mattbodley 
Since you are using `flutter drive`, I think you are hitting https://github.com/flutter/flutter/issues/26968 that you can check and see if it resembles your case or not.
Also, another reference you can check if [this](https://github.com/flutter/flutter/issues/129338#issuecomment-1613907710) works in your case or not.

**Comment by mattbodley** [comment]
Thanks @darshankawar I followed the instructions in #26968 and it worked! The only difference is that in the explanation the  FLUTTER_TARGET was suggested to be test_driver/app.dart but in my case I found this not to work and result in the same problem. What I did was change this to the specific test i.e. integration_test/boot_test.dart and it worked!

I don't this is a super good approach though because when I have more integration test files the FLUTTER_TARGET will each need to be changed in Xcode, so I'm sure this seems to work for some other reason 

Also my run command is a bit more complex: 

```flutter drive --driver=test_driver/integration_test.dart --flavor=integration -t lib/main_integration.dart --target=integration_test/boot_test.dart```

What do you think I need to do to make this work for multiple integration tests? Since in Xcode I had to set this (hardcode it) to that single integration test, meaning I cannot create another test e.g. integration_test/login_test.dart without changing this in Xcode.

![image](https://github.com/flutter/flutter/assets/3054509/f08b08ca-d08f-4777-8c63-dc87b18cbffa)

**Comment by darshankawar** [comment]
Good to know that the linked issue worked in your case @mattbodley 


> What do you think I need to do to make this work for multiple integration tests?

For this, check if https://github.com/flutter/flutter/issues/115751 applies or helps your case further ?
