### ISSUE TITLE
[video_player][android][Impeller][3.16.3] video play , only audio , no image 

### ISSUE THREAD

**Issue by 24** [flutter/flutter#139869]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

down video_player  example 

and add android  Impeller
```
     <meta-data
           android:name="io.flutter.embedding.android.EnableImpeller"
            android:value="true" />
```

and debug or run  

### Expected results

show images

### Actual results

no images

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by 24** [comment]
Because this bug is bound to appear, and this situation will occur whether it is an emulator android or a real machine android.

The code uses the video_player example official example, and then turns on Impeller 

so, the code and logs are not provided.

**Comment by 24** [comment]
audio is ok

no image

![1](https://github.com/flutter/flutter/assets/1859160/d9bff110-7407-4180-ac9e-af85bd28bb7a)

**Comment by jonahwilliams** [comment]
Hi @24 thanks for trying out Impeller on Android. The preview work is not yet complete, and the functionality that video player needs is being tracked in https://github.com/flutter/flutter/issues/139702
