### ISSUE TITLE
[cli] How can I use flutter project as CLI application?

### ISSUE THREAD

**Issue by 13thdeus** [flutter/flutter#139874]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Hi. I have an existing application uses Flutter as framework. I need to use it as a Command Line Interface tool. I've found a way how to quickly hide desktop window on Win/Nix/Mac OS but this is not applicable to Nix servers (in my case I would like to run app on the _Ubuntu server 22.04_) which has no window interfaces at all.

There are few ways how to run code in CLI using dart but it is not works for me for some reasons:
1. I'd like to hide source code from end-user
2. I'd like to avoid requesting install **dart** as an required component
3. My app uses Rust plugin compiles at every build and that code must be hidden too

Is there any ways to run `FlDartProject` without creating any UI elements?

### Proposal

I would like to have a way how to start app w/o running any windows. If it is gonna be separate executable this also wold be great.

**Comment by darshankawar** [comment]
@13thdeus 
Can you take a look at [this](https://melos.invertase.dev/) and check if it helps in your case ?

**Comment by 13thdeus** [comment]
I've checked `melos` but it seems it would not be helpful. I need to find a way how to run flutter/dart code on windowless OS without providing source code. Looks like `melos` couldn't help with it.

**Comment by darshankawar** [comment]
@13thdeus 
Are you looking for this use case to specifically run on windows platform ?

**Comment by 13thdeus** [comment]
@darshankawar I'm looking for way to run an app on Linux at first.

**Comment by darshankawar** [comment]
Can you take a look at https://github.com/flutter/flutter/issues/41737 and see if it helps in your case ?

**Comment by 13thdeus** [comment]
I've found that is enough for me to just use `dart compile exe` command instead of flutter. I still need to update app but that way looks correct for me. Yeah, there is a question how to use rust in this case but it is another question
