### ISSUE TITLE
mac-6 is in Quarantined state due to error.

### ISSUE THREAD

**Issue by kentnguyen99** [flutter/flutter#139844]
### Is there an existing issue for this?

- [X] I have searched the [existing infra issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-infra)

### Type of Request

bug

### Infrastructure Environment

LUCI, Github, Cocoon scheduler, Autosubmit, etc...

### What is happening?

mac-6 is in Quarantined state due to error.
<img width="1576" alt="Screenshot 2023-12-08 at 4 21 21 PM" src="https://github.com/flutter/flutter/assets/120754754/af752a5b-df71-459f-a1fd-2804febebda4">

### Steps to reproduce

Step 1:
Step 2:
..
Step n:

### Expected results

I expect to see X when Y is finished.

**Comment by kentnguyen99** [comment]
@yusuf-goog - Can you take a look of mac-6?  Earlier mac-6 is in Quarantined state due to errors. I ran command "brew remove/install libplist ideviceinstaller libimobiledevice libusbmuxd". Now, it showed a different errors.

Quarantined: Device doctor tool error: b'Unhandled exception:\nidevice_id not found.\n#0 fail (package:device_doctor/src/utils.dart:33)\n#1 getMacBinaryPath (package:device_doctor/src/utils.dart:164)\n<asynchronous suspension>\n#2 IosDeviceDiscovery.deviceListOutput (package:device_doctor/src/ios_device.dart:53)\n<asynchronous suspension>\n#3 IosDeviceDiscovery.discoverDevices (package:device_doctor/src/ios_device.dart:45)\n<asynchronous suspension>\n#4 IosDeviceDiscovery.checkDevices (package:device_doctor/src/ios_device.dart:62)\n<asynchronous suspension>\n#5 main (file:///Volumes/Work/s/w/ir/x/w/cocoon/cipd_packages/device_doctor/bin/main.dart:79)\n<asynchronous suspension>\n'

**Comment by kentnguyen99** [comment]
Hi @godofredoc, Can you take a look of mac-6? It is in Quarantined state due to error "Quarantined: Device doctor tool error: b'Unhandled exception:\nidevice_id not found.\n#0 fail" same error as other Macs about couples months ago. Thanks.

**Comment by godofredoc** [comment]
This is probably related to failures when applying salt states. What is the output of `sudo salt-call state.highstate`?

**Comment by godofredoc** [comment]
Salt states were being applied correctly. The problem was brew manually installed using the flutter user which was causing issues with permissions.

@yusuf-goog @kentnguyen99 we may need to update the labs documentation to remove the parts indicating that brew has to be installed manually as salt states are now taking care of the installation setting the right permissions and using the correct user.

**Comment by godofredoc** [comment]
The machine is now recovered but reassigning this bug to track the documentation update.

**Comment by yusuf-goog** [comment]
> Salt states were being applied correctly. The problem was brew manually installed using the flutter user which was causing issues with permissions.
> 
> @yusuf-goog @kentnguyen99 we may need to update the labs documentation to remove the parts indicating that brew has to be installed manually as salt states are now taking care of the installation setting the right permissions and using the correct user.

You mean remove brew that was manually installed?

**Comment by kentnguyen99** [comment]
@godofredoc, I have looked in Labs documentation that does not have a step to install brew software.

**Comment by kentnguyen99** [comment]
@godofredoc, Is there any else need to be done on this service ticket? Can I close ticket?

**Comment by kentnguyen99** [comment]
I think, the problem has been resolved and fixed by Godofredo. This ticket can be closed.
