### ISSUE TITLE
Version solving failed for `intl: 0.19.0` with `flutter_localizations`

### ISSUE THREAD

**Issue by NeKoFu** [flutter/flutter#139861]
Hi,
Currently, the **flutter_localizations** package depends on **intl ^0.18.1**
Would it be possible to update this dependency to **intl ^0.19.0**

Have a nice day

**Comment by danysz** [comment]
+1

**Comment by huycozy** [comment]
Thanks for the report. This is a known issue at https://github.com/dart-lang/i18n/issues/759 but it seems this should be fixed on Flutter side (a stale issue https://github.com/dart-lang/i18n/issues/458).

**Comment by FaFre** [comment]
It would be really great if this is getting updated, since the usage of intl is pretty widespread and blocks other packages from getting upgraded.

**Comment by loic-sharma** [comment]
Looks like this got closed by accident, reopening

**Comment by loic-sharma** [comment]
This is blocked until [`package:unified_analytics`](https://pub.dev/packages/unified_analytics/versions) version `5.8.6` is released. /cc @eliasyishak

**Comment by FaFre** [comment]
Mhm, doesn't it make more sense to actually reference those package in internal packages from the sdk directly they are shipped with (https://dart.dev/tools/pub/dependencies#sdk). Having internal packages depend on other version they are actually shipped with sounds like that's breaking a lot of stuff, no?

**Comment by eliasyishak** [comment]
Just released `5.8.6` for unified analytics

**Comment by christopherfujino** [comment]
assigning this to @eliasyishak, can you close once intl v0.19.0 has rolled to flutter/flutter?

**Comment by loic-sharma** [comment]
The automated roll failed, I'll close this with a manual roll

**Comment by vuzzer** [comment]
Hi,
`flutter_localizations` depend on `intl 0.18.0`
would be possible to update to intl `0.19.0`.
I have many packages in my project that depend on `intl 0.19.0` ! please 🙏

Have a nice day!

**Comment by loic-sharma** [comment]
@vuzzer Hello, this should be addressed in [the `master` channel](https://docs.flutter.dev/development/tools/sdk/upgrading#switching-flutter-channels). You can try this using:

```
flutter channel master
flutter upgrade
```

The stable channel will be fixed on the next stable release.

**Comment by vuzzer** [comment]
@loic-sharma hello, thanks ! it works
