### ISSUE TITLE
After upgrading to 3.16.2 or 3.16.3 , integration tests have stopped working for android and ios

### ISSUE THREAD

**Issue by Rarsh1992** [flutter/flutter#139978]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Hi
After upgrading to 3.16.2 or 3.16.3 , integration tests have stopped working for android and ios.

Command I am using to run tests: `flutter clean && flutter drive -t "test_driver/bdd.dart"`

Observation:
app launches fine in both ios/android emulator, but then everything halts and just 1 line error message appears.

```
Unhandled exception:
TimeoutException after 0:03:00.000000: Timeout while waiting for observatory debugger uri
```

```
Flutter doctor output:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.3, on macOS 14.1.2 23B92 darwin-x64, locale en-IE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
[✓] VS Code (version 1.84.2)
[✓] Connected device (3 available)
[✓] Network resources
```

I have used `enableFlutterDriverExtension();` too

Nothing is working.

I'll really appreciate if someone could help me get over this issue,Please

Thanks

### Expected results

Test execution should work fine like it was for older flutter versions 

### Actual results

App opens but test execution is failing due to error  
Unhandled exception:
TimeoutException after 0:03:00.000000: Timeout while waiting for observatory debugger uri
no details in error logs makes it tricky to identify the problem area

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter_driver/driver_extension.dart';
import 'package:dummy/main_qa_auto.dart' as app;

void main() {
  // This line enables the extension.
  enableFlutterDriverExtension();
  app.main();
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
flutter: The Dart VM service is listening on http://127.0.0.1:54066/VgKBYgIAQmE=/
flutter: Is remote config verified [true]
Unhandled exception:
TimeoutException after 0:03:00.000000: Timeout while waiting for observatory debugger uri
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.3, on macOS 14.1.2 23B92 darwin-x64, locale en-IE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
[✓] VS Code (version 1.84.2)
[✓] Connected device (3 available)
[✓] Network resources
```

</details>

**Comment by Rarsh1992** [comment]
> Hi @Rarsh1992, do you have flavors enabled in your app?
> 
> For iOS, can you check [#129338 (comment)](https://github.com/flutter/flutter/issues/129338#issuecomment-1613907710) to see if it helps?
Hi @danagbemava-nc ,

I am not using flavours, and as far as I can see ios is building the app from correct spot ie. "lib/main_qa_auto.dart" in my case.

Thanks

**Comment by Rarsh1992** [comment]
@danagbemava-nc ,

I verified that on executing `flutter drive -t "test_driver/bdd.dart"` FLUTTER_TARGET refers to the correct file. 

`FLUTTER_TARGET=/Users/rash/Desktop/test_app/test_app/test_driver/bdd.dart`

heres the content on bdd.dart

```
import 'package:flutter_driver/driver_extension.dart';
import 'package:test_app/main_qa_auto.dart' as app;

void main() {
  // This line enables the extension.
  enableFlutterDriverExtension();
  app.main();
}
```

**Comment by Rarsh1992** [comment]
@danagbemava-nc ,

I verified that on executing `flutter drive -t "test_driver/bdd.dart"` FLUTTER_TARGET refers to the correct file. 

`FLUTTER_TARGET=/Users/rash/Desktop/test_app/test_app/test_driver/bdd.dart`

heres the content on bdd.dart

```
import 'package:flutter_driver/driver_extension.dart';
import 'package:test_app/main_qa_auto.dart' as app;

void main() {
  // This line enables the extension.
  enableFlutterDriverExtension();
  app.main();
}
```

**Comment by danagbemava-nc** [comment]
Hi @Rarsh1992, thanks for the feedback. Can you please provide a complete minimal reproducible code sample so that we can investigate this? Please note that it would be better if this is not your app. Just the smallest amount of code required to reproduce the issue would be fine.

Thank you

**Comment by Rarsh1992** [comment]
@danagbemava-nc 

heres the code.
Let me know if you need anything else:

code for counter app:
lib\main.dart
`
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // TRY THIS: Try running your application with "flutter run". You'll see
        // the application has a purple toolbar. Then, without quitting the app,
        // try changing the seedColor in the colorScheme below to Colors.green
        // and then invoke "hot reload" (save your changes or press the "hot
        // reload" button in a Flutter-supported IDE, or press "r" if you used
        // the command line to start the app).
        //
        // Notice that the counter didn't reset back to zero; the application
        // state is not lost during the reload. To reset the state, use hot
        // restart instead.
        //
        // This works for code too, not just values: Most code changes can be
        // tested with just a hot reload.
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // TRY THIS: Try changing the color here to a specific color (to
        // Colors.amber, perhaps?) and trigger a hot reload to see the AppBar
        // change color while the other colors stay the same.
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          //
          // TRY THIS: Invoke "debug painting" (choose the "Toggle Debug Paint"
          // action in the IDE, or press "p" in the console), to see the
          // wireframe for each widget.
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

`

inside directory `test_driver`

in file `app.dart`:

`
import 'package:test/main.dart' as appp;
import 'package:flutter/widgets.dart';
import 'package:flutter_driver/driver_extension.dart';

void main() {
  // This line enables the extension
  enableFlutterDriverExtension();

  // Call the `main()` function of your app or call `runApp` with any widget you
  // are interested in testing.
  appp.main();
}

`

inside directory `test_driver`

in file `app_test.dart`:

`
import 'dart:async';
import 'package:flutter_gherkin/flutter_gherkin.dart';
import 'package:gherkin/gherkin.dart';
import 'package:glob/glob.dart';
import 'steps/step_definition.dart';

Future<void> main() {
  final config = FlutterTestConfiguration()
    ..build = true
    ..flutterBuildTimeout = const Duration(seconds: 180)
    ..features = [Glob(r"test_driver/features/**.feature")]
    ..reporters = [
      ProgressReporter(),
      TestRunSummaryReporter(),
      JsonReporter(path: './report.json')
    ]
    ..stepDefinitions = [GivenCounterIsSetTo(), TapButtonNTimesStep()]
    ..restartAppBetweenScenarios = true
    ..targetAppPath = "test_driver/app.dart";
  return GherkinRunner().execute(config);
}

`

inside directory `test_driver`

in directory `features` > in file `test.features`:

`
Feature: Counter Button

    As a user
    I want to tap the plus button
    So that I can see the counter increment

    Scenario: Counter increases when the button is pressed
        Given the counter is set to "0"
        When I tap the "Increment" button 10 times
`

inside directory `test_driver`

in directory `steps` > in file `step_definition.dart`:

`
import 'package:flutter_driver/flutter_driver.dart';
import 'package:flutter_gherkin/flutter_gherkin.dart';
import 'package:gherkin/gherkin.dart';

class GivenCounterIsSetTo extends Given1WithWorld<String, FlutterWorld> {
  @override
  RegExp get pattern => RegExp(r"the counter is set to {string}");

  @override
  Future<void> executeStep(String expectedCounter) async {
    final locator = find.text("counter");
    expectMatch(0, 0);
  }
}

class TapButtonNTimesStep extends When2WithWorld<String, int, FlutterWorld> {
  @override
  RegExp get pattern => RegExp(r"I tap the {string} button {int} times");

  @override
  Future<void> executeStep(String buttonKey, int amount) async {
    final locator = find.byTooltip(buttonKey);
    for (var i = 0; i < amount; i += 1) {
      await FlutterDriverUtils.tap(world.driver, locator, timeout: timeout);
    }
  }
}

`

spin up ios/andoid emulator 

then run `flutter clean && flutter drive -t "app.dart"`

**Comment by huycozy** [comment]
@Rarsh1992 Thanks for your update. I see you are using a 3rd package `flutter_gherkin` on the sample code that I'm not familiar with. When running the project, I only see the counter app. Which step should I do next? Please share `steps by steps` to reproduce the issue. Thanks!

Also, I found there was an issue on that package https://github.com/jonsamwell/flutter_gherkin/issues/35. Please check if you can find any information there to investigate this issue further.

Complete sample project: [test.zip](https://github.com/flutter/flutter/files/13681384/test.zip)
