### ISSUE TITLE
[Fatal Error] netty-codec-socks-4.1.52.Final.pom:2:1: Content is not allowed in prolog.

### ISSUE THREAD

**Issue by AhsanAli24117** [flutter/flutter#139906]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Create a new flutter project 
Try to run it using an emulator made by Android studio
Operating System: Windows
Development Environment: VS Code (Project Editing), Android Studio (Emulator)
Flutter version: 3.16.3
Gradle version: (not provided)
Installation: Flutter official repository
Network: Wi-FiStudio

### Expected results

I want it to be properly running so that I can see it on the emulator

### Actual results

it gave me that error
Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
[Fatal Error] netty-codec-socks-4.1.52.Final.pom:2:1: Content is not allowed in prolog.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve io.netty:netty-codec-socks:4.1.52.Final.
     Required by:
         project : > com.android.tools.build:gradle:7.3.0 > io.grpc:grpc-netty:1.39.0 > io.netty:netty-handler-proxy:4.1.52.Final
      > Could not resolve io.netty:netty-codec-socks:4.1.52.Final.
         > Could not parse POM https://repo.maven.apache.org/maven2/io/netty/netty-codec-socks/4.1.52.Final/netty-codec-socks-4.1.52.Final.pom
            > Content is not allowed in prolog.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 29s
Running Gradle task 'assembleDebug'...                             31.3s
Exception: Gradle task assembleDebug failed with exit code 1

firstly I just thought that there should be some error in my code but then I even tried it with a newly created flutter project.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.3, on Microsoft Windows [Version 10.0.22000.2538], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[!] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.32)
    X The current Visual Studio installation is incomplete.
      Please use Visual Studio Installer to complete the installation or reinstall Visual Studio.
[√] Android Studio (version 2023.1)
[√] VS Code (version 1.85.0)
[√] Connected device (4 available)
[√] Network resources

! Doctor found issues in 1 category.

**Comment by darshankawar** [comment]
@AhsanAli24117 
What's the gradle version you are using in the project ?
If you try to run the same project from outside of IDE (ie, from command prompt), do you still get same error ?
