### ISSUE TITLE
Flutter Splash Screen

### ISSUE THREAD

**Issue by YahyaAtta** [flutter/flutter#139927]
Feature Suggestion:

I Have Suggestion Make Flutter Logo Default Splash Screen instead of White Screen in next stable release.

**Comment by darshankawar** [comment]
@YahyaAtta 
I don't think the default splash screen can be overridden. Instead you can customize it as shown in below links:

https://stackoverflow.com/a/73146425
https://kamalbunkar.medium.com/how-to-remove-white-splash-screen-from-flutter-app-1f240bd154c

Closing this, as it isn't feasible to override the default white screen as mentioned in above SO link. If you disagree, write in comments and I'll reopen it.
