### ISSUE TITLE
V/GoogleMapController( 4481): Controller was disposed before GoogleMap was ready.

### ISSUE THREAD

**Issue by Siyaho** [flutter/flutter#139910]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

V/GoogleMapController( 4481): Controller was disposed before GoogleMap was ready after deploying the app to an Android simulator.

### Expected results

Google Map should be shown on Android. On iOS devices, it works fine. **Not working on Android**, though!

### Actual results

Empty canvas - no Google canvas with error:

```
E/FrameEvents( 6856): updateAcquireFence: Did not find frame.
V/GoogleMapController( 6856): Controller was disposed before GoogleMap was ready.
E/PlatformViewsController( 6856): Disposing platform view threw an exception
```

### Code sample

```
                                  Expanded(
                                    child: GestureDetector(
                                      onTap: (){
                                        _openMap();
                                      },
                                      child: Container(
                                          margin: EdgeInsets.only(top: 10),
                                          child: AbsorbPointer(
                                            child: GoogleMapViewPlace(
                                              isFullScreen: false,
                                              zoom: 14,
                                              place: widget.place,
                                            ),
                                            absorbing: true,
                                          )),
                                    ),
                                  )
```

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

[√] Flutter (Channel master, 3.18.0-7.0.pre.59, on Microsoft Windows [Version 10.0.19045.3693], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2023.1)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.82.2)
[√] Connected device (4 available)
[√] Network resources

**Comment by darshankawar** [comment]
> GoogleMapViewPlace

@Siyaho What plugin are you using ? Is it google_maps_flutter ?

**Comment by Siyaho** [comment]
Yes. Turns out, I had two Android folders in my app and I was editing the wrong one (to add the API key). Resolved!
