### ISSUE TITLE
Proposal to improve error message for `Bad state: No element` error by providing missing element details

### ISSUE THREAD

**Issue by LauDijksterhuis** [flutter/flutter#139907]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

When requesting a field that does not exist from a Map, for example FirebaseDocument.data(). The error throws de following: 
```
The following StateError was thrown building
InsuranceInOutPrivateCard-[<'HXuXEZJ6P6Bptn1Ju47a'>](dirty, state:
_InsuranceInOutPrivateCardState#48be0):
Bad state: No element
```

Which is good. 

### Proposal

However, it would be greater if the error message showed which "element" is requested. For example: 
`Bad state: no element at .... ` and then the field that was requested.

**Comment by christopherfujino** [comment]
@LauDijksterhuis thank you for filing this. However, `Maps` are implemented in the Dart SDK itself, so I would suggest filing this feature request at https://github.com/dart-lang/sdk/issues.

**Comment by LauDijksterhuis** [comment]
hi @christopherfujino 
Thank you for your response, I will create a new issue over there.
