### ISSUE TITLE
Next flutter stable release 

### ISSUE THREAD

**Issue by RakiFuyumine** [flutter/flutter#139909]
Hi, I would like to ask about around when is planned next stable release of flutter and what version it would be based on?

**Comment by dam-ease** [comment]
Hi @RakiFuyumine.
You can see https://github.com/flutter/flutter/wiki/Flutter-build-release-channels for details on Flutter releases.
I hope this helps!

Also, you can see https://flutter.dev/community for resources and ask more questions like this
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you
