### ISSUE TITLE
Flutter plugin GoogleMapController unavailable? 

### ISSUE THREAD

**Issue by qwadrox** [flutter/flutter#139973]
### Is there an existing issue for this?

- [X] I have searched the [existing package issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Apackage)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### What package does this bug report belong to?

google_maps_flutter

### What target platforms are you seeing this bug on?

Android

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

[https://0.0g.gg/?b140c03d17dce651#DpQp4WfA11kNg2MNG4HU8bYjgbDbTuPvKtvazfBHCXSz](https://0.0g.gg/?b140c03d17dce651#DpQp4WfA11kNg2MNG4HU8bYjgbDbTuPvKtvazfBHCXSz)

</details>

### Steps to reproduce

Unfortunately I have no idea. 

### Expected results

-

### Actual results

_Side information: Today, we encountered a peculiar bug in our Flutter application where users were unable to navigate beyond the first page. This issue was reproducible on our devices as well. I attached my phone, started to observer  Android system (captured using [Catlog](https://0.0g.gg/?20709dc2a59de7c2#4V8omtDGoMSzHMEVkJXBcNvA3UpR7N9L3QrW9NMqJUhU)). But about a 10 minutes later I could navigate from the first page like nothing happened. Since that time the problem seems to be resolved._ **The ARN-s I posted below related? No idea about that.**

A new ARN popped up in Crashlytics: 
The first one containing a line: `flutter.plugins.googlemaps.GoogleMapController.e(unavailable:8) `
Referencing the flutter plugin. 

```console
main (runnable):tid=1 systid=24024 
       at m.drr.<init>(:com.google.android.gms.policy_maps_core_dynamite@233610105@233610102065.573949206.573949206:97)
       at m.dqo.a(:com.google.android.gms.policy_maps_core_dynamite@233610105@233610102065.573949206.573949206:35)
       at m.fqk.a(:com.google.android.gms.policy_maps_core_dynamite@233610105@233610102065.573949206.573949206:14)
       at m.dqy.f(:com.google.android.gms.policy_maps_core_dynamite@233610105@233610102065.573949206.573949206:3)
       at m.dqy.j(:com.google.android.gms.policy_maps_core_dynamite@233610105@233610102065.573949206.573949206:19)
       at m.dqy.a(:com.google.android.gms.policy_maps_core_dynamite@233610105@233610102065.573949206.573949206:1)
       at m.dqy.h(:com.google.android.gms.policy_maps_core_dynamite@233610105@233610102065.573949206.573949206:8)
       at m.dqy.c(:com.google.android.gms.policy_maps_core_dynamite@233610105@233610102065.573949206.573949206:1)
       at m.dbl.i(:com.google.android.gms.policy_maps_core_dynamite@233610105@233610102065.573949206.573949206:18)
       at m.dbl.e(:com.google.android.gms.policy_maps_core_dynamite@233610105@233610102065.573949206.573949206:1)
       at com.google.maps.api.android.lib6.impl.cm.aE(:com.google.android.gms.policy_maps_core_dynamite@233610105@233610102065.573949206.573949206:76)
       at com.google.maps.api.android.lib6.impl.eh.d(:com.google.android.gms.policy_maps_core_dynamite@233610105@233610102065.573949206.573949206:11)
       at com.google.android.gms.maps.internal.s.bp(:com.google.android.gms.policy_maps_core_dynamite@233610105@233610102065.573949206.573949206:159)
       at m.bbf.onTransact(:com.google.android.gms.policy_maps_core_dynamite@233610105@233610102065.573949206.573949206:21)
       at android.os.Binder.transact(Binder.java:1169)
       at s7.a.u0(unavailable:7)
       at a8.s0.s0(unavailable:8)
       at z7.n.s0(unavailable:10)
       at i7.e.a(unavailable:8)
       at i7.d.a(unavailable:33)
       at z7.o.q(unavailable:46)
       at z7.o.a(unavailable:2)
       at i7.a.o(unavailable:44)
       at i7.a.c(unavailable:5)
       at z7.d.b(unavailable:22)
       at io.flutter.plugins.googlemaps.GoogleMapController.e(unavailable:8)
       at androidx.lifecycle.DefaultLifecycleObserverAdapter.m(unavailable:62)
       at androidx.lifecycle.k$b.a(unavailable:24)
       at androidx.lifecycle.k.a(unavailable:105)
       at io.flutter.plugins.googlemaps.GoogleMapController.U(unavailable:6)
       at io.flutter.plugins.googlemaps.f.a(unavailable:12)
       at io.flutter.plugins.googlemaps.g.a(unavailable:131)
       at io.flutter.plugin.platform.u.M(unavailable:40)
       at io.flutter.plugin.platform.u$a.e(unavailable:15)
       at uf.l$a.c(unavailable:122)
       at uf.l$a.onMethodCall(unavailable:175)
       at vf.j$a.a(unavailable:17)
       at jf.c.l(unavailable:18)
       at jf.c.m(unavailable:40)
       at jf.c.i(unavailable)
       at jf.b.run(unavailable:12)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:211)
       at android.os.Looper.loop(Looper.java:300)
       at android.app.ActivityThread.main(ActivityThread.java:8410)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Videos

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
-
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
ateboros@Mates-MacBook-Pro VoxPay.Flutter % flutter doctor -v 
[✓] Flutter (Channel stable, 3.16.2, on macOS 14.0 23A344 darwin-arm64, locale en-HU)
    • Flutter version 3.16.2 on channel stable at /Users/mateboros/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9e1c857886 (12 days ago), 2023-11-30 11:51:18 -0600
    • Engine revision cf7a9d0800
    • Dart version 3.2.2
    • DevTools version 2.28.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/mateboros/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.14.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 75.1.4
    • Dart plugin version 232.10072.19

[✓] VS Code (version 1.85.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (3 available)
    • M2004J19C (mobile)          • 12a106c00404  • android-arm64 • Android 12 (API 31)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64 • Android 14 (API 34) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64  • macOS 14.0 23A344 darwin-arm64
```

</details>

**Comment by keodoff** [comment]
1) Make sure u have added correct package:
```
dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter:
```
2) Open your project folder in terminal and paste there command : `flutter pub get`

`GoogleMapController ` should be available

**Comment by huycozy** [comment]
@qwadrox Is this issue reproduced locally? If so, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so that we may verify this. 

If it's not reproduced in debug mode, please try running app in release mode.

In case the issue only occurs in production, please provide the list of affected device info and the percentage occurrence of the crash. Thanks!

**Comment by qwadrox** [comment]
> google_maps_flutter

The provided Stacktrace does not directly imply that the GoogleMapController wouldn't be available from the dart code. It's is available, app could be built and released. This problem occurred runtime as an [ARN](https://firebase.google.com/docs/crashlytics/debug-anr-errors).

**Comment by qwadrox** [comment]
> 1. Make sure u had added correct package and inside `dependencies`:
> 
> ```
> dependencies:
>   flutter:
>     sdk: flutter
>   google_maps_flutter:
> ```
> 
> 2. Open your project folder in terminal and paste there command : `flutter pub get`
> 
> `GoogleMapController ` should be available

The provided Stacktrace does not directly imply that the GoogleMapController wouldn't be available from the dart code. It's is available, app could be built and released. This problem occurred runtime as an [ARN](https://firebase.google.com/docs/crashlytics/debug-anr-errors).

**Comment by qwadrox** [comment]
> @qwadrox Is this issue reproduced locally? If so, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so that we may verify this.
> 
> If it's not reproduced in debug mode, please try running app in release mode.
> 
> In case the issue only occurs in production, please provide the list of affected device info and the percentage occurrence of the crash. Thanks!

Only occurs in production.
Based on Crashlytics the devices on which it caused an ARN currently only: Redmi Note 11 Pro 5G
Unfortunately I was not able to reproduce this specific error that is including flutter. 
I could only see similar ones like:
```console
WaitForGcToComplete blocked ClassLinker on Background for 184.233ms
I/SnapshotHandler( 9218): Unable to retrieve flag snapshot for com.google.android.libraries.consentverifier#hu.voxinfo.voxpay.beta, using defaults.
W/MobStoreFlagStore( 9218): Unable to update local snapshot for com.google.android.libraries.consentverifier#hu.voxinfo.voxpay.beta, may result in stale flags.
W/MobStoreFlagStore( 9218): java.util.concurrent.ExecutionException: java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=hu.voxinfo.voxpay.beta, sha256=[d90eef8b8e9aee4adefa3e5c5db721a6114d090ee0ba3e7cf8ada2083feed247], atk=true, ver=231818044.true (go/gsrlt)
W/MobStoreFlagStore( 9218): 	at ajs.s(:com.google.android.gms.dynamite_mapsdynamite@231818044@23.18.18 (190400-0):3)
W/MobStoreFlagStore( 9218): 	at ajs.get(:com.google.android.gms.dynamite_mapsdynamite@231818044@23.18.18 (190400-0):2)
W/MobStoreFlagStore( 9218): 	at alc.g(:com.google.android.gms.dynamite_mapsdynamite@231818044@23.18.18 (190400-0):2)
W/MobStoreFlagStore( 9218): 	at yz.c(:com.google.android.gms.dynamite_mapsdynamite@231818044@23.18.18 (190400-0):1)
W/MobStoreFlagStore( 9218): 	at zb.run(:com.google.android.gms.dynamite_mapsdynamite@231818044@23.18.18 (190400-0):0)
W/MobStoreFlagStore( 9218): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
W/MobStoreFlagStore( 9218): 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
W/MobStoreFlagStore( 9218): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
W/MobStoreFlagStore( 9218): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
W/MobStoreFlagStore( 9218): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
W/MobStoreFlagStore( 9218): 	at java.lang.Thread.run(Thread.java:1012)
W/MobStoreFlagStore( 9218): Caused by: java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=hu.voxinfo.voxpay.beta, sha256=[d90eef8b8e9aee4adefa3e5c5db721a6114d090ee0ba3e7cf8ada2083feed247], atk=true, ver=231818044.true (go/gsrlt)
W/MobStoreFlagStore( 9218): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
W/MobStoreFlagStore( 9218): 	at android.os.Parcel.createException(Parcel.java:3041)
W/MobStoreFlagStore( 9218): 	at android.os.Parcel.readException(Parcel.java:3024)
W/MobStoreFlagStore( 9218): 	at android.os.Parcel.readException(Parcel.java:2966)
W/MobStoreFlagStore( 9218): 	at fe.c(:com.google.android.gms.dynamite_mapsdynamite@231818044@23.18.18 (190400-0):2)
W/MobStoreFlagStore( 9218): 	at rx.a(:com.google.android.gms.dynamite_mapsdynamite@231818044@23.18.18 (190400-0):4)
W/MobStoreFlagStore( 9218): 	at jl.e(:com.google.android.gms.dynamite_mapsdynamite@231818044@23.18.18 (190400-0):2)
W/MobStoreFlagStore( 9218): 	at kj.t(:com.google.android.gms.dynamite_mapsdynamite@231818044@23.18.18 (190400-0):2)
W/MobStoreFlagStore( 9218): 	at kj.u(:com.google.android.gms.dynamite_mapsdynamite@231818044@23.18.18 (190400-0):3)
W/MobStoreFlagStore( 9218): 	at kj.e(:com.google.android.gms.dynamite_mapsdynamite@231818044@23.18.18 (190400-0):2)
W/MobStoreFlagStore( 9218): 	at kn.handleMessage(:com.google.android.gms.dynamite_mapsdynamite@231818044@23.18.18 (190400-0):78)
W/MobStoreFlagStore( 9218): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/MobStoreFlagStore( 9218): 	at android.os.Looper.loopOnce(Looper.java:205)
W/MobStoreFlagStore( 9218): 	at android.os.Looper.loop(Looper.java:294)
W/MobStoreFlagStore( 9218): 	at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by huycozy** [comment]
>Caused by: java.lang.SecurityException: GoogleCertificatesRslt: not allowed

This error appeared on an old issue https://github.com/flutter/flutter/issues/109115. It's known as Google Maps SDK issue rather than Flutter maps plugin issue. The [linked issue](https://issuetracker.google.com/issues/228091313?pli=1) also pointed out: `The logs only recorded by Maps SDK's Legacy renderer and not by the Latest renderer`, so you can try using the latest renderer to see if it can fix the issue.

If it can't fix the issue, as the issue happens on your device, could you try running project in `release` mode to see if you can get all output log (`flutter run --release -v`)?

**Comment by qwadrox** [comment]
> lutter run --release -v

I use the latest renderer and the problem does not seem to appear in release mode. I don't have such records in Crashytics as well, but my [original ARN looks](https://github.com/flutter/flutter/issues/139973#issue-2037395447) very similar. That's why i mentioned only, sorry for being confusing.

**Comment by qwadrox** [comment]
> > Caused by: java.lang.SecurityException: GoogleCertificatesRslt: not allowed
> 
> This error appeared on an old issue #109115. It's known as Google Maps SDK issue rather than Flutter maps plugin issue. The [linked issue](https://issuetracker.google.com/issues/228091313?pli=1) also pointed out: `The logs only recorded by Maps SDK's Legacy renderer and not by the Latest renderer`, so you can try using the latest renderer to see if it can fix the issue.
> 
> If it can't fix the issue, as the issue happens on your device, could you try running project in `release` mode to see if you can get all output log (`flutter run --release -v`)?

I use the latest renderer and the problem does not seem to appear in release mode. I don't have such records in Crashytics as well, but my [original ARN looks](https://github.com/flutter/flutter/issues/139973#issue-2037395447) very similar. That's why i mentioned only, sorry for being confusing.

**Comment by huycozy** [comment]
Alright, I will get back to the original issue. Could you please confirm the original issue can be reproduced in `release` mode? If it is, could you share all output log (`flutter run --release -v`)? (The log may be huge so you can save it as a file and attach it here or using a 3rd party tool like pastebin for eg)

Since the issue was able to reproduce on your device, I would suggest you keep an eye on it if you can replicate it consistently and see if it has any pattern.

**Comment by qwadrox** [comment]
If i can replicate consistently I will get back, but for now I think we can close. I don't see any possibility to solve this having these informations.
