### ISSUE TITLE
Long DropdownButton scroll animation jank (10000 menu items)

### ISSUE THREAD

**Issue by sashkent3** [flutter/flutter#139908]
### Steps to reproduce

1. Create a new Flutter project: `flutter create dropdown_jank`
2. Replace the contents of the `lib/main.dart` with the code sample below
3. Run the app: `flutter run --profile`
4. Press the dropdown button and quickly scroll it down using a scroll bar
5. Observe the jank

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  final List<DropdownMenuItem> items = [
    for (var i = 1; i <= 10000; i++)
      DropdownMenuItem(value: i, child: Text(i.toString()))
  ];

  MyWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return DropdownButton(
      items: items,
      onChanged: (_) {},
    );
  }
}
```

</details>

### Performance profiling on master channel

- [X] The issue still persists on the master channel

### Timeline Traces

<details><summary>Timeline Traces JSON</summary>

[dart_devtools_2023-12-11_16 22 03.322.json](https://github.com/flutter/flutter/files/13637089/dart_devtools_2023-12-11_16.22.03.322.json)

</details>

### Video demonstration

<details>
<summary>Video demonstration</summary>

[[Upload media here]](https://github.com/flutter/flutter/assets/33320473/8927d134-7beb-400d-b388-902b17433be9)

</details>

### What target platforms are you seeing this bug on?

Web, Linux

### OS/Browser name and version | Device information

- OS: Arch Linux x86_64
- Kernel: 6.6.3-arch1-1
- CPU: AMD Ryzen 7 5800HS
- Browser: Chromium Version 119.0.6045.159

### Does the problem occur on emulator/simulator as well as on physical devices?

Unknown

### Is the problem only reproducible with Impeller?

N/A

### Logs

<details><summary>Logs</summary>

```console
>>> flutter --verbose create dropdown_jank
```

[dropdown_jank_create.log](https://github.com/flutter/flutter/files/13637165/dropdown_jank_create.log)

```console
>>> flutter --verbose run -d linux --profile --trace-skia
```

[dropdown_jank_run.log](https://github.com/flutter/flutter/files/13637156/dropdown_jank_run.log)

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.18.0-7.0.pre.57, on Arch Linux 6.6.3-arch1-1, locale en_US.UTF-8)
    • Flutter version 3.18.0-7.0.pre.57 on channel master at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 10a31934f2 (2 days ago), 2023-12-09 07:35:26 -0800
    • Engine revision fb80aafd25
    • Dart version 3.3.0 (build 3.3.0-213.0.dev)
    • DevTools version 2.30.0

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /opt/android-sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /opt/android-sdk
    • ANDROID_SDK_ROOT = /opt/android-sdk
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.21+9)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 16.0.6
    • cmake version 3.27.9
    • ninja version 1.11.1
    • pkg-config version 2.0.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Arch Linux 6.6.3-arch1-1
    • Chrome (web)    • chrome • web-javascript • Chromium 119.0.6045.159 Arch Linux

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by huycozy** [comment]
Hi @sashkent3 
I believe this is an issue with ListView in general. I checked this with a sample code that uses ListView with 10000 items. I can also observe janks and the scrolling animation is laggy as well.

That's a known issue at https://github.com/flutter/flutter/issues/52207. Closing this issue in favor of that one, please follow up on it for updates. Thanks!

**Comment by sashkent3** [comment]
@huycozy Thanks! Upon reading #52207 I found that `itemExtent` or `prototypeItem` can be specified to mitigate the issue (I've verified that the performance is drastically better). In my use case, this is a fine solution, because all menu items should be the same height. However, I don't see the option to specify those attributes for DropdownButton or DropdownMenu. Shouldn't this be implemented?

**Comment by sashkent3** [comment]
I have verified, that passing `prototypeItem` to the underlying ListView fixes my particular example (I feel like Flutter should expose that attribute and `itemExtent` in the DropdownButton itself). I can't quite figure out how to fix `DropdownMenu` in the same way - which is what I want to use in my project.

**Comment by huycozy** [comment]
>However, I don't see the option to specify those attributes for DropdownButton or DropdownMenu.

I think they would be valid feature requests. Please help to open new issues for DropdownButton and DropdownMenu. You can mention this issue as a use case for them. Thanks!
