### ISSUE TITLE
FCM Android Notification tap doesn't open the app

### ISSUE THREAD

**Issue by long1eu** [flutter/flutter#13992]
I'm sending a notification to topic from a Firebase Function to Android, Web, iOS like this:
```
{
	"notification": {
		"title": "title",
		"body": "body",
		"badge": 5,
		"clickAction": "${url}",
		"sound": "default"
	},
	"data": {
		"type": "chat",
		"category": "${url}?destination=${data.destination}",
		"click_action": "FLUTTER_NOTIFICATION_CLICK"
	}
}
```
But on Android when I tap the notification the app doesn't open. I've added the intent filter in the manifest, but still. Any ideas?

**Comment by Hixie** [comment]
cc @collinjackson

**Comment by zoechi** [comment]
What does `AndroidManifest.xml` and `flutter doctor` look like

**Comment by collinjackson** [comment]
Can you confirm if you've set up your AndroidManifest.xml according to the [README](https://pub.dartlang.org/packages/firebase_messaging)?

```
  <intent-filter>
      <action android:name="FLUTTER_NOTIFICATION_CLICK" />
      <category android:name="android.intent.category.DEFAULT" />
  </intent-filter>
```

**Comment by long1eu** [comment]
This is so old that we can close it. :))

**Comment by kroikie** [comment]
@long1eu

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/913. Any further collaboration will be done there.
