### ISSUE TITLE
Failed to run MSBuild command - System Integrity policy has been violated.  Explicit denied file

### ISSUE THREAD

**Issue by coperio** [flutter/flutter#139975]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Step 1:
flutter create my_app
Step 2:
cd my_app
Step 3:
flutter run lib/main.dart

### Actual results

CMake Error at CMakeLists.txt:3 (project):
  Failed to run MSBuild command:

    C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe

  to get the value of VCTargetsPath:

    System Integrity policy has been violated.  Explicit denied file

Building Windows application...                                    423ms
Exception: Unable to generate build files

### Logs

<details>
<summary>Logs</summary>

```console

PS C:\projects\my_app> flutter doctor -v
[✓] Flutter (Channel stable, 3.16.3, on Microsoft Windows [Version 10.0.22631.2428], locale en-US)
    • Flutter version 3.16.3 on channel stable at C:\flutter\sdk
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0366e0a3f (6 days ago), 2023-12-05 19:46:39 -0800
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\android\studio-preview\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34330.188
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2023.1)
    • Android Studio at C:\android\studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[✓] Android Studio (version 2023.2)
    • Android Studio at C:\android\studio-preview
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.2428]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 120.0.6099.71
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 100.0.1185.36

[✓] Network resources
    • All expected network resources are available.

• No issues found!
PS C:\projects\my_app> flutter run lib/main.dart
Launching lib/main.dart on Windows in debug mode...
CMake Error at CMakeLists.txt:3 (project):
  Failed to run MSBuild command:

    C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe

  to get the value of VCTargetsPath:

    System Integrity policy has been violated.  Explicit denied file



Building Windows application...                                    423ms
Exception: Unable to generate build files

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by dam-ease** [comment]
Thanks for filing this @coperio.
I see this seems to be related to Visual Studio, can you try out the solutions in the SO thread to see if it works in your case?
https://stackoverflow.com/questions/44478492/cmake-failed-to-run-msbuild-command-msbuild-exe

**Comment by coperio** [comment]
Thanks for helping me @dam-ease.
The issue was the smart app control, as far as i remember it was on evaluation mode and somehow it turned itself on.
![sac_on](https://github.com/flutter/flutter/assets/153605554/54a243c5-0629-4948-9325-1b012c1d1bcc)
I did a little research on how the smart control works and why its blocking cmake.exe under visual studio installation to start msbuild.exe.
When Smart App Control is turned on and when an app tries to start another app, both apps must be signed with the same certificate otherwise Smart App Control will block that process.

C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe
![cmake exe](https://github.com/flutter/flutter/assets/153605554/2add75f3-76b1-4461-b87c-43fdee11487c)

C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe
![msbuild exe](https://github.com/flutter/flutter/assets/153605554/42434d0d-d885-4df8-b060-9727be5de26e)

![windows_security](https://github.com/flutter/flutter/assets/153605554/98506a62-e0bb-4534-89c1-f007b5dac675)

I solved my problem by turning Smart App Control off.
![sac_off](https://github.com/flutter/flutter/assets/153605554/7a8d37ef-fe5c-4f7c-8a86-ee9d2a7da5aa)
