### ISSUE TITLE
[CP] Fix _availability_version_check for iOS 11 and 12

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#139983]
### Issue Link

https://github.com/flutter/flutter/issues/138711

### Target

stable

### PR Link

https://github.com/flutter/engine/pull/48926

### Changelog Description

Fixes a crash on iOS 11 and 12 (iPhone 5s and iPhone 6)

### Impacted Users

All iOS users targeting iOS 11 and 12

### Impact Description

Apps on these devices crash on app startup.

### Workaround

There is no workaround.

### Risk

low

### Test Coverage

yes

### Validation Steps

Ensure that apps start on these devices.

**Comment by zanderso** [comment]
@chinmaygarde to review.

**Comment by chinmaygarde** [comment]
LGTM. The home screen crash is unrelated and I cannot reproduce.
