### ISSUE TITLE
Windows Interoperability In Dart

### ISSUE THREAD

**Issue by YahyaAtta** [flutter/flutter#139991]
Add C# Language beside C++
I have suggestion Add way
That call Windows APIs Directly from Dart.
generates Dart Bindings for C++/C#
Like JnIgen &FFIGen.

**Comment by brianquinlan** [comment]
Have you looked into [`package:win32`](https://pub.dev/packages/win32)?

**Comment by YahyaAtta** [comment]
> Have you looked into [`package:win32`](https://pub.dev/packages/win32)?

Yes.

**Comment by darshankawar** [comment]
@YahyaAtta 
Your issue is similar to https://github.com/flutter/flutter/issues/64958, so please follow-up in it for further updates.
Closing as duplicate.

**Comment by YahyaAtta** [comment]
> @YahyaAtta 
> Your issue is similar to https://github.com/flutter/flutter/issues/64958, so please follow-up in it for further updates.
> Closing as duplicate.

Thanks you
