### ISSUE TITLE
Safari Web Flutter Engine Goldens differ on macOS 13 from macOS 12

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#139924]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

When running `Linux linux_web_engine` subtests on macOS 13, the Flutter Engine Golden files change: https://flutter-engine-gold.skia.org/search?issue=48807&crs=github&patchsets=8&corpus=flutter-engine.

1. Update to Mac-13 in https://github.com/flutter/engine/blob/bcd74587473014d2cf1fa00928619680875172bb/lib/web_ui/dev/generate_builder_json.dart#L119
2. Run `lib/web_ui/dev/felt test --generate-builder-json`
3. Create a PR

### Actual results

I expect `Linux linux_web_engine` to pass on both macOS 12 and macOS 13.

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by yjbanov** [comment]
The triage included goldens that were (for unknown reasons) left untriaged in post-submit. Now that I triaged those, your triage link only includes true 12 vs 13 changes, and all of them LGTM.

**Comment by yjbanov** [comment]
IOW, feel free to submit the PR with golden updates. Considering this issue as "fixed".

**Comment by vashworth** [comment]
Even after approving golden updates for macOS 13 arm64 and macOS 13 x86, golden update changes continue to show when web tests are switched to run on macOS 12 or 13.
