### ISSUE TITLE
DecorationImage is not showing the image when it's SVG

### ISSUE THREAD

**Issue by RowidaNurElDin** [flutter/flutter#139904]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1- Use Container widget
2- Use DecorationImage inside
3- Provide SVG image using any class (AssetImage(),Svg(),SvgPicture()..etc)

OR

1- Use CircleAvatar widget
2- Use backgroundImage inside
3- Provide SVG image using any class (AssetImage(),Svg(),SvgPicture()..etc)

### Expected results

SVG image is shown normally

### Actual results

SVG image is not shown without any errors

### Code sample

<details><summary>Code sample</summary>

```dart
Container(
          width: double.infinity,
          decoration: const BoxDecoration(
            image: DecorationImage(image: Svg(chatBckImage)),
          //Please use any svg asset other than chatBckImage
              color: Colors.white,
          ),
        ),
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.2, on macOS 14.1.2 23B92 darwin-arm64, locale
    en-GB)
    • Flutter version 3.16.2 on channel stable at
      /Users/rowidanureldin/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9e1c857886 (11 days ago), 2023-11-30 11:51:18 -0600
    • Engine revision cf7a9d0800
    • Dart version 3.2.2
    • DevTools version 2.28.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/rowidanureldin/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[✓] Connected device (2 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64 • Android 14
      (API 34) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64  • macOS 14.1.2
      23B92 darwin-arm64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by dam-ease** [comment]
Hi @RowidaNurElDin.
Can you describe what you are trying to achieve with this?
You can't use assign an `SvgPicture` to a `ImageProvider<Object>` as in the case of the `decoration`.
Please can you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code i.e a single main.dart file that we could run at once which reflects this

> SVG image is not shown without any errors

Thank you!

**Comment by RowidaNurElDin** [comment]
Hello @dam-ease 
I created this project that clarifies the problem 
https://github.com/RowidaNurElDin/decoration_image_bug

**Comment by dam-ease** [comment]
Thanks for your response.
Looking through this, I can reproduce this issue on my end as well.
I tried running the code sample in https://pub.dev/packages/flutter_svg_provider/example as well using the assets in your project instead and the svgs aren't rendering. You can confirm this on your end as well. If this is the case, the flutter_svg_provider is a third-party package and the appropriate place to file this issue will be https://github.com/yang-f/flutter_svg_provider/issues.

Closing this as this might not be an issue with flutter itself, if you disagree, please comment and I'll reopen this.
Thank you!
