### ISSUE TITLE
Hi @RollerFernandez

### ISSUE THREAD

**Issue by slimjoe1987** [flutter/flutter#139944]
Hi @RollerFernandez 
              
              int erms of the below, where is the class MainActivity in AndroiStudio? 

Please use this 
```
class MainActivity: FlutterActivity() {

    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
        GeneratedPluginRegistrant.registerWith(flutterEngine)
    }
}
```

Thank you

_Originally posted by @TahaTesser in https://github.com/flutter/flutter/issues/58347#issuecomment-636881493_

**Comment by danagbemava-nc** [comment]
Please do not file issues with just comments from existing issues without any context. 

Kindly use the appropriate issue template to file issues. 

Closing from here as no context has been provided. 

Thank you
