### ISSUE TITLE
[Flutter Admin] grant github action permissions to create pull requests 

### ISSUE THREAD

**Issue by XilaiZhang** [flutter/flutter#140078]
Currently the [cherry pick github action](https://github.com/flutter/flutter/blob/master/.github/workflows/easy-cp.yml) doesn't have permission to create a pull request ([failed workflow](https://github.com/flutter/flutter/actions/runs/7199162299/job/19610246693))  
```
remote: Permission to flutter/flutter.git denied to github-actions[bot].
  fatal: unable  to access 'https://github.com/flutter/flutter/': The requested URL returned error: 403
```
It is possible that the box of "Allow github actions to create and approve pull requests" isn't ticked in the settings. (flutter/flutter -> 'Settings' tab on the top menu -> 'Actions' tab on the left menu -> 'General')
![Screenshot 2023-12-13 at 10 46 11 AM](https://github.com/flutter/flutter/assets/38773539/b791eff5-c571-4f7e-94ee-108a042d4f85)

Would be great if a Github Admin (maybe sir @godofredoc) could help check if this box is ticked in the settings. Thank you so much!

**Comment by godofredoc** [comment]
Is this required if you are using a PAT with pull request write? Let's move this go/flutter-security-bug

**Comment by godofredoc** [comment]
@XilaiZhang can we close this bug?
