### ISSUE TITLE
[go_router] Should we use imperative methods such as push() and pop() ?

### ISSUE THREAD

**Issue by ShubhamHande99** [flutter/flutter#140049]
I want to use `go_router ` for both the mobile application and the web app, but before starting, 
I have a few questions for which I couldn't find answers in the `go_router `documentation or articles. 

Should we use `Imperative APIs `such as `context.push()`? Is using them against the philosophy of `go_router `or `Navigation 2.0`?

If I have to use only the `context.go()` method, how will we handle the `Imperative ` style navigation stack for the mobile application by only using `context.go()`?

In my case, I have a few top-level routes that will be called from multiple places within the app. I want a back button in the mobile app so I can easily pop and preserve the state of previous screen. Can this be achieved using only `context.go()` or is using `context.push() ` needed in such a case? I don't want to use `child routes`, as it does not make sense for top-level routes.

**Comment by darshankawar** [comment]
@ShubhamHande99 
Check [this](https://github.com/flutter/flutter/issues/114216) and [this](https://github.com/flutter/flutter/issues/100468) and see if it helps to answer your question or not.

**Comment by ShubhamHande99** [comment]
@darshankawar 
I have gone through these issues as they discuss more of `imperative APIs` versus `declarative APIs` usage, but it does not answer my question specifically about whether we should use `imperative APIs` in the `declarative` routing package `go_router`.

**Comment by darshankawar** [comment]
https://github.com/flutter/flutter/issues/114216#issuecomment-1706895322 does mention that both api usage would stay for now. More you can read about it here https://github.com/flutter/flutter/issues/99112#issuecomment-1563213451

**Comment by ShubhamHande99** [comment]
Okay, thanks for the information.
