### ISSUE TITLE
Regression in complex_layout_scroll_perf_bad_ios__timeline_summary build time on 12/6/2023

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#140064]
The performance dashboard showed a regression in the `complex_layout_scroll_perf_bad_ios__timeline_summary` benchmark around 12/6/2023.

Build time metrics like `average_frame_build_time_millis` increased, along with `total_ui_gc_time`.

See https://flutter-flutter-perf.skia.org/e/?keys=X85d9845ae61164943ad8763287b1ec06&selected=commit%3D38291%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253Daverage_frame_build_time_millis%252Ctest%253Dcomplex_layout_scroll_perf_bad_ios__timeline_summary%252C&xbaroffset=38291

The increase does not happen consistently on every run, but there is a clear overall trend.

Tried bisecting, and I noticed a change in this benchmark's behavior starting with https://dart.googlesource.com/sdk/+/85cb56dd205fdc7ca7e8d4eb7c3511075fe1a417

**Comment by alexmarkov** [comment]
Looking at the generated arm64 code, I can only see improvements - less closure and context object allocations, certain switch expressions are optimized out entirely (such as `TooltipState._getDefaultTooltipHeight`).

Maybe smaller number of object allocations caused slower heap growth, which increased total number of GCs and results in higher overall GC time and build time. /cc @rmacnak-google

**Comment by jonahwilliams** [comment]
Given that this was a fairly small regression in a single benchmark and we think the change is good overall, lets close this and move on.

**Comment by jonahwilliams** [comment]
This did result in more overall GC times: 

https://flutter-flutter-perf.skia.org/e/?begin=1704653803&end=1704740203&queries=sub_result%3Dnew_gen_gc_count%26sub_result%3Dold_gen_gc_count%26sub_result%3Dtotal_ui_gc_time%26test%3Dcomplex_layout_scroll_perf_bad_ios__timeline_summary&selected=commit%3D38528%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253Dtotal_ui_gc_time%252Ctest%253Dcomplex_layout_scroll_perf_bad_ios__timeline_summary%252C&xbaroffset=38291
