### ISSUE TITLE
The onchange method of the TextField component in iOS browser receives a different string than the input string

### ISSUE THREAD

**Issue by lyf571321556** [flutter/flutter#140051]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

TextField
      (

      textInputAction: TextInputAction.search,
      onChanged: (value) {
        Toast.show(value);
      },
    )

### Expected results

show correct string

### Actual results

show incorrect string

### Code sample

<details><summary>Code sample</summary>

```dart
TextField
      (

      textInputAction: TextInputAction.search,
      onChanged: (value) {
        Toast.show(value);
      },
    )
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/2295872/5f882fd4-d85d-4c9c-bd9b-385547b79f12

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
╰ flutter doctor -v
[✓] Flutter (Channel stable, 3.13.9, on macOS 13.0 22A380 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.13.9 on channel stable at /Users/ones/Library/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision d211f42860 (7 weeks ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✗] Android toolchain - develop for Android devices
    • Android SDK at /Users/ones/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.9559.10
```

</details>

**Comment by dam-ease** [comment]
Hi @lyf571321556.
Thanks for filing this.
Please can you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code?

**Comment by lyf571321556** [comment]
TextField
(
  textInputAction: TextInputAction.search,
  onChanged: (value) {
 debugPrint('currentValue ${value}');
  },
)

**Comment by dam-ease** [comment]
Hi @lyf571321556.
Thanks for your response. I can't reproduce this on my end, I get the correct and expected output values
```
flutter: currentValue c
flutter: currentValue ce
flutter: currentValue 测
``` 

Can you upgrade to the latest Flutter versions to confirm this on your end, if it does persist, can you share the IDE you are running this on?

**Comment by lyf571321556** [comment]
> Hi @lyf571321556. Thanks for your response. I can't reproduce this on my end, I get the correct and expected output values
> 
> ```
> flutter: currentValue c
> flutter: currentValue ce
> flutter: currentValue 测
> ```
> 
> Can you upgrade to the latest Flutter versions to confirm this on your end, if it does persist, can you share the IDE you are running this on?

This issue was reproduced on Flutter version 3.13.9, and upgrading to the latest version carries significant risks.

**Comment by dam-ease** [comment]
Thanks for your response.
Per our triage process, if an issue no longer occurs on the latest versions, we will consider this fixed and close.
Running this on version `3.13.9`, I can't seem to reproduce as well.
Running on browser, I have this (see video below)

<details><summary>Video</summary>
<p>


https://github.com/flutter/flutter/assets/53122008/a1b91d68-2440-4aa2-9b5b-f662d977af9c


</p>
</details> 

<details><summary>Code Sample Used</summary>
<p>

<details><summary>Code Sample</summary>
<p>

```dart
import 'package:flutter/material.dart';

const Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: darkBlue,
      ),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return TextField(
        textInputAction: TextInputAction.search,
        onChanged: (value) {
          print('currentValue $value');
          _showToast(context, value);
        });
  }

  void _showToast(BuildContext context, String text) {
    final scaffold = ScaffoldMessenger.of(context);
    scaffold.showSnackBar(
      SnackBar(
        content: Text(text),
        action: SnackBarAction(
            label: 'UNDO', onPressed: scaffold.hideCurrentSnackBar),
      ),
    );
  }
}

``` 

</p>
</details> 

</p>
</details> 

Can you check this out as well?
