### ISSUE TITLE
Add blank Required Reason API xcprivacy manifest to plugin template for new plugins

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#140013]
Part of https://github.com/flutter/flutter/issues/131940

Add a blank xcprivacy to the `flutter create --template plugin` template that is correctly hooked up in the template podspec.  This will allow plugin authors to just edit one file instead of needing to fumble around the podspec/Xcode.

From https://github.com/flutter/flutter/issues/131495

> Introduced in Xcode 15, Apple is now flagging specific APIs as needing a “Required Reason” to use. All usages of “Required Reason” APIs MUST be outlined in a Privacy manifest. A Privacy manifest is a document outlining how your app/SDK collects and uses a user’s data.
> 
> This is also time sensitive (https://developer.apple.com/news/?id=z6fu1dcu).
> 
> > Starting in fall 2023, when you upload a new app or app update to App Store Connect that uses an API (including from third-party SDKs) that requires a reason, you’ll receive a notice if you haven’t provided an approved reason in your app’s privacy manifest. And starting in spring 2024, in order to upload your new app or app update to App Store Connect, you’ll be required to include an approved reason in the app’s privacy manifest which accurately reflects how your app uses the API.
> 
> https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api?language=objc https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests?language=objc https://developer.apple.com/videos/play/wwdc2023/10060/

**Comment by stuartmorgan** [comment]
> that is correctly hooked up in the template podspec.

Capturing from Discord: I think we should probably comment out the line in the pod spec, with an explanation, so developers have to affirmatively wire it up. Having the default if someone doesn't know about it be "missing" seems better than saying there's nothing to declare when that might not be accurate.
