### ISSUE TITLE
Flutter Web (PWA) crashes repeatedly without any reason

### ISSUE THREAD

**Issue by semagarcia** [flutter/flutter#140017]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. I've built a Flutter application for web as a PWA. This is built with --release flag and I've also made build with and without --pwa-strategy flag.
2. I've publish the web (static files) to an HTTPS Server
3. I've installed the web as a PWA App on an real iOS device

### Expected results

The application should works always, but sometimes, the app crashes without any error or reason.

### Actual results

The application has an initial splash screen with a button for showing a modal for logging in. The app has some 3rd party flutter packages, like Google Maps or Firebase (auth, cloudstore, analytics, etc., and its corresponding web version in the needed cases).

Once the user writes the credentials, the modal disappears and the home screen should appear after a navigation. The problem occurs here, because sometimes when the home page start to load, the application crashes being reloaded and starting from the beginning -the login- (I cannot reproduce the pattern or find the context/scenario that produces the crash). When the error occurs, the screen only displays a "the https.//.... has generated problems repeatedly".

I've added print statements, Catcher package with Sentry integration for errors... even I've created my custom error callback on `FlutterError.onError` and over `PlatformDispatcher.instance.onError` without success because they are never executed when crashing.

The problem only occurs when I test the PWA on a real iOS device, so, I've debugged it from STP (Safari Technology Preview), but as the application (PWA) reloads, the DevTool opened is closed automatically and I can't see any log, neither HTTP requests nor console traces. I've also tried to check the ServiceWorker from another DevTool instances, but without any useful info.

At home page, I only use Firebase cloudstore for retrieving info from a collection, and I've using a 'StreamBuilder<QuerySnapshot>' widget to gather the info asynchronously. Any other package is involved at this point. at HTML side, I've added the required script imports for Google Maps. The renderer engine is set as auto (default).

The same behavior is not reproducible from browser (not PWA) or even from an Android device (either browser or PWA). I cannot reproduce the crash from an iOS emulator.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

I've execute the following command for building the application; however, this is not the direct problem because the same compilation works on Android devices and from the browser URL direct access for instance.

```console
flutter build web --verbose --release
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.0, on macOS 14.1.2 23B92 darwin-x64, locale es-ES)
    • Flutter version 3.16.0 on channel stable at /Users/sema/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (4 weeks ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/sema/Library/Android/sdk
    • Platform android-34, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554             • android-x86    • Android 8.1.0 (API 27) (emulator)
    • Test iPhone               • test_iphone_id • ios            • iOS 17.1.2
    • macOS (desktop)                    • macos                     • darwin-x64     • macOS 14.1.2 23B92 darwin-x64
    • Chrome (web)                       • chrome                    • web-javascript • Google Chrome 120.0.6099.71

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @semagarcia 
Does the crash occur by creating a new flutter project and then following the steps you mentioned ? ie, to see if the behavior persists without using any plugins ?


> The problem only occurs when I test the PWA on a real iOS device

I see that the iOS version is 17. Is there a way for you to run it on lesser version (< 17) just to confirm if it replicates on those versions as well or just specific to 17 ?

**Comment by semagarcia** [comment]
Thanks for your @darshankawar for your triage

I've tried with another real iOS device (iOS v17.0.3 on iPhone SE) and, until now, I can't reproduce the issue.

The other iOS device (where I repeatedly found the issue) is an iPhone 14 Plus.

If you need further details, please, write me a comment.

Thanks in advance!

**Comment by darshankawar** [comment]
Thanks for the update. If we get any meaningful logs from the device on which it is crashing, would be helpful to properly address the issue. 
See if [this](https://stackoverflow.com/questions/65502006/not-able-to-check-error-logs-while-developing-pwa-in-flutter) helps to get some logs.

**Comment by semagarcia** [comment]
Hi @darshankawar,

I think I have interesting updates after an additional research. I've tried to simplify the problem, and I have the "main > splash > login > home" sequence of screens as always. At home page, I have a query against Firebase (concretely, a cloud firestore collection); that set of results retrieved will populate a list of card. Each card is something like this:

![image](https://github.com/flutter/flutter/assets/10792397/7df7e26f-4811-485b-8c3f-bec95a572795)

I've removed all the UI part (changing all the page to maintain just a text component with the number of the list retrieved in order to ensure the rest of the logic works right):

![image](https://github.com/flutter/flutter/assets/10792397/7d95892d-0382-4838-9274-d40a811a591e)

After that simplification, I'm not be able to reproduce the issue again (or at least, by the moment).

I'm trying to remember that some time ago I've read something about an error with rounded border or an issue like that. 

Do you have some hint or any action that I could follow?

Thanks in advance.

**Comment by darshankawar** [comment]
Thanks for digging and providing updates @semagarcia 
It seems the crash you were seeing could be related to your code implementation and not necessarily a bug in the framework itself, as after segregating the logic and UI, you were unable to replicate the crash. 


> about an error with rounded border or an issue like that.

There may have been lot of issues like it, but in order to pin point which one you are referring to would be tough. But since the crash isn't replicable, maybe it is not an issue at all and you may close this if you think.

**Comment by mengqutaoyuan** [comment]
I have the same problem. I found that when I frequently call flutter's image compression method, or add watermark method, using the image library, on the iPhone 8P iOS14.7 device, the web page crashes without any information. I guess it may be a memory problem. iOS Safari has memory limits, and flutter memory leaks or is not released in time.
