### ISSUE TITLE
`Shortcuts.debugLabel` is ignored in its `FocusNode.debugLabel`

### ISSUE THREAD

**Issue by busslina** [flutter/flutter#140029]
I'm setting `debugLabel` but always prints `Shortcuts`.

This is the source code of `Shortcuts.constructor()`:
```dart
const Shortcuts({
    super.key,
    required Map<ShortcutActivator, Intent> shortcuts,
    required this.child,
    this.debugLabel,
  }) : _shortcuts = shortcuts,
       manager = null;
```
[Here](https://github.com/flutter/flutter/blob/11a9cb7029d77aef521a934645383780a732d67c/packages/flutter/lib/src/widgets/shortcuts.dart#L962)

This is the source code of `Shortcuts.build()`:
```dart
@override
  Widget build(BuildContext context) {
    return Focus(
      debugLabel: '$Shortcuts',
      canRequestFocus: false,
      onKey: _handleOnKey,
      child: widget.child,
    );
  }
```
[Here](https://github.com/flutter/flutter/blob/11a9cb7029d77aef521a934645383780a732d67c/packages/flutter/lib/src/widgets/shortcuts.dart#L1069)

![imagen](https://github.com/flutter/flutter/assets/73592852/33c1d3ff-4822-467d-9e92-0ee9433dff7d)

**Comment by danagbemava-nc** [comment]
Hi @busslina, please provide a complete minimal reproducible code sample along with steps to reproduce so that we can investigate this. Please do not provide screenshots of code/logs as they are not searchable.

Please also provide the output of `flutter doctor -v`

Thank you

**Comment by busslina** [comment]
@danagbemava-nc I just update it with the code and the links to that code. Flutter Doctor is not need because is an identified code issue.

**Comment by danagbemava-nc** [comment]
Hi @busslina,

Please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with steps to reproduce so that we can investigate this issue. 

Thank you

**Comment by busslina** [comment]
@danagbemava-nc 
The problem is just that `A` must be `B`:

### A)
```dart
@override
  Widget build(BuildContext context) {
    return Focus(
      debugLabel: '$Shortcuts',
      canRequestFocus: false,
      onKey: _handleOnKey,
      child: widget.child,
    );
  }
```

### B)
```dart
@override
  Widget build(BuildContext context) {
    return Focus(
      debugLabel: debugLabel == null ? '$Shortcuts' : '$Shortcuts -- $debugLabel',
      canRequestFocus: false,
      onKey: _handleOnKey,
      child: widget.child,
    );
  }
```

**Comment by huycozy** [comment]
@busslina When opening an issue, please try to provide all information indicated in the template so that we can address this issue properly (See bug issue template [here](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml))

More specifically, please provide the information indicated below:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of `flutter doctor -v`
- Reproduction steps
- Which environment did this issue happen in? (Android/iOS/Web/MacOS/Windows/Linux)

**Comment by busslina** [comment]
https://github.com/flutter/flutter/pull/140202
