### ISSUE TITLE
Engine->framework roller blocked due to test failures related to Dart SDK hot reload and debugging

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#140074]
Various tooling-related tests are failing with errors that appear to involve Dart hot reload and debugging.

(example: https://github.com/flutter/flutter/pull/140066)

This appears to have started with this Dart roll: https://github.com/flutter/engine/pull/48961

**Comment by jason-simmons** [comment]
This started with https://dart.googlesource.com/sdk/+/fd2e9b9f1af9e2ced5d263956f82e4ef3b583c8a

**Comment by jason-simmons** [comment]
This can be reproduced by:
* building a `host_debug_unopt` engine at the commit that introduced the Dart SDK change (https://github.com/flutter/engine/commit/a8bf8404fdaa22c24c9d927b3c286dd107a0ecd8)
* run any Flutter app with that engine on Linux
  * `flutter --local-engine host_debug_unopt --local-engine-host host_debug_unopt -d linux run`
* browse to the DevTools URL output by `flutter run`
* in DevTools, go to the debugger tab and set a breakpoint in the app's Dart code

The app process will crash.

Tried capturing a stack trace - the stack frames were all symbolized as `kDartVmSnapshotInstructions`.

**Comment by alexmarkov** [comment]
Crash from the engine with Dart VM in debug mode:

```
../../third_party/dart/runtime/vm/debugger.cc: 1546: error: expected: !function.HasImplicitClosureFunction()
version=3.3.0-222.0.dev (dev) (Tue Dec 12 16:04:53 2023 -0800) on "linux_x64"
pid=776480, thread=776518, isolate_group=main(0x7f74c817e060), isolate=main(0x7f74c8187aa0)
os=linux, arch=x64, comp=no, sim=no
isolate_instructions=7f7576aba6a0, vm_instructions=7f7576aba6a0
fp=7f74db7fc090, sp=7f74db7fbf60, pc=7f7576da138c
  pc 0x00007f7576da138c fp 0x00007f74db7fc090 /.../flutter/dev/integration_tests/flutter_gallery/build/linux/x64/debug/bundle/lib/libflutter_linux_gtk.so+0x4ba138c
-- End of DumpStackTrace
Lost connection to device.
```
