### ISSUE TITLE
[iOS/Crash] - io.flutter.1.ui - EXC_BAD_ACCESS (code=1, address=0x0) while running flutter on native as a module.

### ISSUE THREAD

**Issue by CodeWizard0367** [flutter/flutter#140068]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I have integrated the flutter module into an IOS native application.
It works fine when I don't do anything but once I start interacting with the app and navigate to other page and do explore few other features. the app crashes on release mode and stops at debugger in debug.

The app is using 320 to 500 MB of ram (if this could help anyhow)

### Expected results

The app should not crash.

### Actual results

Xcode debugger stops at flutter engine on below thread:
#0	0x0000000116c64c28 in skia::textlayout::ParagraphImpl::layout(float) ()

The app is using 320 to 500 MB of ram (if this could help anyhow)

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<img width="1552" alt="Screenshot 2023-12-13 at 8 19 36 PM" src="https://github.com/flutter/flutter/assets/153746034/21a835de-35ab-49d9-86ec-c98e1843900d">

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.16.2, on macOS 13.4.1 22F770820d darwin-arm64, locale en-IN)
    • Flutter version 3.16.2 on channel stable at /Users/faisal/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9e1c857886 (13 days ago), 2023-11-30 11:51:18 -0600
    • Engine revision cf7a9d0800
    • Dart version 3.2.2
    • DevTools version 2.28.3

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/faisal/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] VS Code (version 1.83.1)
    • VS Code at /Users/faisal/Desktop/Apps/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] VS Code (version 1.85.0-insider)
    • VS Code at /Users/faisal/Desktop/Apps/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.79.20231130

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.4.1 22F770820d darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.109

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by darshankawar** [comment]
Thanks for the report @CodeWizard0367 
Can you provide complete reproducible code sample that we can use to replicate it our end ? You may also create a demo repo that we can clone.
Also, can you run `flutter run -v` and provide the verbose log that would have error entries that we can take a look at ?

**Comment by CodeWizard0367** [comment]
> Thanks for the report @CodeWizard0367 Can you provide complete reproducible code sample that we can use to replicate it our end ? You may also create a demo repo that we can clone. Also, can you run `flutter run -v` and provide the verbose log that would have error entries that we can take a look at ?

Hi @darshankawar 
It's not possible for me to write a reproducible code also for the `flutter run -v` because I am working with a module it's not possible for me to this as well.

**Comment by darshankawar** [comment]
@CodeWizard0367 
Can you please provide the entire stacktrace in properly formatted text instead of in screenshots ?
