### ISSUE TITLE
Printing 

### ISSUE THREAD

**Issue by gedw99** [flutter/flutter#14001]
I need to print a document from within flutter.

I can see two approaches:
1. Screen capture at a resolution higher than the actual screen and embed it inside a PDF.
2. Generate a PDF totally seperate from the screen.

If anyonce can advice aboout each. I can easily generate a PDF with non flutter code on mobiles in the same way i do on desktop using golang.

Next though is sending the PDF to the printing system on each mobile. 
I could not find any existing code for this and so i want to know if making a Flutter Plugin would be a sensible approach, since its goig to call into Java / swift native API's.

If anyone has thouhts on another approach please advise.

**Comment by zoechi** [comment]
Flutter uses Skia.
Perhaps something like https://groups.google.com/forum/#!topic/skia-discuss/z8HocdF14gI is doable

**Comment by gedw99** [comment]
That solution uses skia and pdfium.
I think a more higher level api accessible from flutter as a dart class is needed.

In order to do this the root flutter widget node needs to be told to render for a paper size also.

Then the output needs to be converted to a PDF and that can be sent to the devices printer spooler.

This is going to become even more important with the flutter for desktop area also

**Comment by gedw99** [comment]
Thanks and I already new that this is possible.

Since flutter is based on skia it would be a good send if the team
integrated the PDF / Xps ( windows ) into flutter proper.

It's a core thing and should be a platform service imho.

What do you think though ?
I know the flutter team have a mountain to climb with other stuff too.
