### ISSUE TITLE
[webview_flutter] Unexpected `adb: device offline` causes integration test failure

### ISSUE THREAD

**Issue by camsim99** [flutter/flutter#140001]
### Is there an existing issue for this?

- [X] I have searched the [existing infra issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-infra)

### Type of Request

bug

### Infrastructure Environment

LUCI

### What is happening?

I'm attempting to have `webview_flutter` integration tests run on AVDs with Android 34, see https://github.com/flutter/packages/pull/5221. Consistently, I see this failure that occurs in [this failed build](https://ci.chromium.org/ui/p/flutter/builders/try/Linux_android%20android_platform_tests_shard_6%20master/3790/overview), for example:
```
01:43 +8 ~1: /b/s/w/ir/x/w/packages/packages/webview_flutter/webview_flutter/example/integration_test/legacy/webview_flutter_test.dart: Video playback policy Auto media playback                      adb: device 'emulator-5554' not found
Installing build/app/outputs/flutter-apk/app-debug.apk...           21ms
Error: ADB exited with exit code 1
adb: device 'emulator-5554' not found

01:43 +8 ~1 -1: loading /b/s/w/ir/x/w/packages/packages/webview_flutter/webview_flutter/example/integration_test/webview_flutter_test.dart [E]                                                         
  TestDeviceException(Unable to start the app on the device.)
  package:flutter_tools/src/test/integration_test_device.dart 63:7  IntegrationTestTestDevice.start
  
  TimeoutException after 0:12:00.000000: Test timed out after 12 minutes.
  package:test_api/src/backend/invoker.dart 338:28  Invoker._handleError.<fn>
  dart:async/zone.dart 1391:47                      _rootRun
  dart:async/zone.dart 1301:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 336:10  Invoker._handleError
  package:test_api/src/backend/invoker.dart 291:9   Invoker.heartbeat.<fn>.<fn>
  dart:async/zone.dart 1399:13                      _rootRun
  dart:async/zone.dart 1301:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 290:38  Invoker.heartbeat.<fn>
  dart:async-patch/timer_patch.dart 18:15           Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 398:19         _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 429:5          _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 184:12      _RawReceivePort._handleMessage
```
which seems to occur because before this, the device goes offline and an uninstall fails, e.g. from that same build:
```
01:05 +8: /b/s/w/ir/x/w/packages/packages/webview_flutter/webview_flutter/example/integration_test/legacy/webview_flutter_test.dart: Video playback policy Auto media playback                         

01:06 +8: /b/s/w/ir/x/w/packages/packages/webview_flutter/webview_flutter/example/integration_test/legacy/webview_flutter_test.dart: Video playback policy Auto media playback                         
01:07 +8: /b/s/w/ir/x/w/packages/packages/webview_flutter/webview_flutter/example/integration_test/legacy/webview_flutter_test.dart: Video playback policy Auto media playback                         adb: device offline

01:07 +8 ~1: /b/s/w/ir/x/w/packages/packages/webview_flutter/webview_flutter/example/integration_test/legacy/webview_flutter_test.dart: Video playback policy Auto media playback                      adb uninstall failed: ProcessException: Process exited abnormally with exit code 1:
adb: device offline
  Command: /b/s/w/ir/cache/android/sdk/platform-tools/adb -s emulator-5554 uninstall io.flutter.plugins.webviewflutterexample
```

I have run this test locally on an emulator running Android 34 and it runs fine, so I'm hoping to get some help investigating this issue.

P.S. I see that there were issues with `webview_flutter` integration tests hanging on legacy (API 22) devices although on a different test and I think running in Firebase (https://github.com/flutter/flutter/issues/136824), so not sure it's related.

### Steps to reproduce

N/A. See `Linux_android android_platform_tests_shard_6 master` builds for https://github.com/flutter/packages/pull/5221.

### Expected results

I expect to see the `webview_flutter/webview_flutter` integration tests proceed normally as they do locally (and seemingly so, on AVDs running Android 33).

**Comment by camsim99** [comment]
cc @bparrishMines not sure if you have seen this issue come up before, would love to know if you have!

**Comment by bparrishMines** [comment]
I haven't seen this before. It looks like it may be due to a legacy test that needs updating

`01:43 +8 ~1: /b/s/w/ir/x/w/packages/packages/webview_flutter/webview_flutter/example/integration_test/legacy/webview_flutter_test.dart: Video playback policy Auto media playback`

I'll see if I can repro locally on 34

**Comment by keyonghan** [comment]
Seems related: https://github.com/flutter/flutter/issues/137947

**Comment by camsim99** [comment]
> I haven't seen this before. It looks like it may be due to a legacy test that needs updating
> 
> `01:43 +8 ~1: /b/s/w/ir/x/w/packages/packages/webview_flutter/webview_flutter/example/integration_test/legacy/webview_flutter_test.dart: Video playback policy Auto media playback`
> 
> I'll see if I can repro locally on 34

Lmk. I couldn't repro it locally, so that's why I filed this issue.

FYI that I'll need to address this issue before having `webview_flutter` compile against Android 34, so it's blocking in that way. However, I'm going on vacation soon and won't be able to work on this until I'm back.
