### ISSUE TITLE
Alignment doesn't work for Wrap widget

### ISSUE THREAD

**Issue by weisong0** [flutter/flutter#14006]
When I set alignment to spaceBetween for a Wrap widget:
```dart
new Wrap(
  direction: Axis.horizontal,
  alignment: WrapAlignment.spaceBetween,
  children: <Widget>[
    new Chip(
      avatar: new CircleAvatar(
          backgroundColor: Colors.blue.shade900, child: new Text('AH')),
      label: new Text('A'),
    ),
    new Chip(
      avatar: new CircleAvatar(
          backgroundColor: Colors.blue.shade900, child: new Text('ML')),
      label: new Text('B'),
    ),
    new Chip(
      avatar: new CircleAvatar(
          backgroundColor: Colors.blue.shade900, child: new Text('HM')),
      label: new Text('C'),
    ),
    new Chip(
      avatar: new CircleAvatar(
          backgroundColor: Colors.blue.shade900, child: new Text('JL')),
      label: new Text('D'),
    ),
  ],
)
```

Try to render the widget, the spaces are not distributed equally between the widgets：
![image](https://user-images.githubusercontent.com/1171990/34754310-d7735f1e-f571-11e7-9101-686d0ae3d5c6.png)

**Comment by gspencergoog** [comment]
If you extend the Wrap contents to cover more than one line, then the expansion does happen.  Wrap with "spaceBetween" expands the lines to all be the same size as the longest line, but since this example only has one line, it is the longest line.

**Comment by yangdong125845** [comment]
alignment: WrapAlignment.center not working ，more than one line

**Comment by etrivinos** [comment]
alignment: WrapAlignment.center worked for me!

**Comment by rmargolinross** [comment]
@gspencrgoog 

> If you extend the Wrap contents to cover more than one line, then the expansion does happen. Wrap with "spaceBetween" expands the lines to all be the same size as the longest line, but since this example only has one line, it is the longest line.

I understand that this is the expected behavior, but it feels limiting in its functionality. I think it would be easier if it acted like a Row/Column, filling its container, but then wrapping when needed. That would be the common use case for everyone I believe. Every container expands in flutter except this one which shrinks for some reason.

**Comment by gspencergoog** [comment]
@rmargolinross It's not the only container that doesn't expand: SizedBox, FittedBox, IntrinsicWidth, and several others do not expand, and UnconstrainedBox takes on the natural size of its child.

In any case, you can put the `Wrap` inside of another widget that does expand, and it will take on that size and use it.

For instance, placing the above example inside of a `SizedBox.expand` does what you and @weisong0 expected, I think, like so:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Wrap Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: WrapTest(),
    );
  }
}

class WrapTest extends StatefulWidget {
  @override
  _WrapTestState createState() => _WrapTestState();
}

class _WrapTestState extends State<WrapTest> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SizedBox.expand(
        child: Wrap(
          direction: Axis.horizontal,
          alignment: WrapAlignment.spaceBetween,
          children: <Widget>[
            Chip(
              avatar: CircleAvatar(child: Text('AH')),
              label: Text('A'),
            ),
            Chip(
              avatar: CircleAvatar(child: Text('ML')),
              label: Text('B'),
            ),
            Chip(
              avatar: CircleAvatar(child: Text('HM')),
              label: Text('C'),
            ),
            Chip(
              avatar: CircleAvatar(child: Text('JL')),
              label: Text('D'),
            ),
          ],
        ),
      ),
    );
  }
}
```

<img width="486" alt="Screen Shot 2020-04-20 at 9 01 17 AM" src="https://user-images.githubusercontent.com/8867023/79772889-8644d100-82e5-11ea-89cc-e598a2830881.png">

**Comment by rmargolinross** [comment]
@gspencergoog Oh that works perfectly. Thanks for the information!
