### ISSUE TITLE
[CP] Catch error for missing directory in `FontConfigManager` in `beta`

### ISSUE THREAD

**Issue by eliasyishak** [flutter/flutter#140006]
### Issue Link

https://github.com/flutter/flutter/issues/138434

### Target

beta

### PR Link

https://github.com/flutter/flutter/pull/140005

### Changelog Description

We are allowing the deletion of a directory to not crash the tool if the directory doesn't exist.

### Impacted Users

All flutter users

### Impact Description

Flutter will crash if it attempts to delete a directory that doesn't exist or any other `FileSystemException`

### Workaround

N/A

### Risk

medium

### Test Coverage

yes

### Validation Steps

The test case added confirms the fix by silently exiting when the deletion error comes up

**Comment by eliasyishak** [comment]
fyi @christopherfujino

**Comment by CaseyHillers** [comment]
Closing as obsolete. The next beta release will be 3.19, which includes the original commit.
