### ISSUE TITLE
[CP] Fix broken pipe SocketException writing to stdin of ios-deploy

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#140000]
### Issue Link

https://github.com/flutter/flutter/issues/139709

### Target

stable

### PR Link

https://github.com/flutter/flutter/pull/139999

### Changelog Description

Fixes a crash in the tool when attempting to write to the STDIN pipe of an ios-deploy sub-process throws a "broken pipe" SocketException.

### Impacted Users

Flutter for iOS developers running debug apps on real iPhones

### Impact Description

When attempting to write to the STDIN pipe of an ios-deploy sub-process and the underlying process has already exited (or crashed), the tool will itself crash with a "broken pipe" SocketException.

### Workaround

Presumably at the point we are detaching from the debugger, the user was no longer interacting with their app, so it should not be blocking their workflow--however, it is still an undesirable dev experience to get a cryptic crash with a reference to a Socket.

### Risk

low

### Test Coverage

yes

### Validation Steps

Reproducing this would be challenging, but I ran the test at `packages/flutter_tools/test/general.shard/ios/ios_deploy_test.dart` on my PR and it passed, which verifies an exception thrown from the same place in the stacktrace will be caught and not crash the tool process.

**Comment by CaseyHillers** [comment]
@jmagman can you review this CP request? If it looks good to you, add the "cp: approved" label.

**Comment by jmagman** [comment]
@christopherfujino is this a big enough deal to warrant a cp?  Should we let this bake in master awhile, given the trickiness of the zones?

**Comment by christopherfujino** [comment]
> @christopherfujino is this a big enough deal to warrant a cp? Should we let this bake in master awhile, given the trickiness of the zones?

A fair question. We get a *lot* of reports of this (#3 by affected clients across 3.16 stable releases and 13% of all crash reports)...but also this seems to be more of an annoyance than actually blocking their workflow.

I'm guessing if you use VSCode and the tool crashes that DartCode will re-start the tool? @DanTup can you confirm this?

**Comment by DanTup** [comment]
> I'm guessing if you use VSCode and the tool crashes that DartCode will re-start the tool? @DanTup can you confirm this?

Not sure which invocation of the tool this refers to. If it's a debug session (`flutter debug_adapter` or `flutter run`) it'll terminate the debug session and the user will be told about that (restarting would be odd, because it would put their app back to the start and could take time compiling etc.).

Other tools (like the device daemon, analysis server etc.) we will usually tell the user it terminated and give an option to restart.

**Comment by christopherfujino** [comment]
> > I'm guessing if you use VSCode and the tool crashes that DartCode will re-start the tool? @DanTup can you confirm this?
> 
> Not sure which invocation of the tool this refers to. If it's a debug session (`flutter debug_adapter` or `flutter run`) it'll terminate the debug session and the user will be told about that (restarting would be odd, because it would put their app back to the start and could take time compiling etc.).
> 
> Other tools (like the device daemon, analysis server etc.) we will usually tell the user it terminated and give an option to restart.

ahh, this is part of the `flutter run` workflow.

**Comment by DanTup** [comment]
My guess is the user would see the debug session end in this case then. Although it sounds like this is probably happening when they're already ending the session, so perhaps it's not noticable (eg. if they disconnect their device or close the simulator, it'd end the session anyway).

**Comment by jmagman** [comment]
Given that, I don't think we should CP this given the complexity of the Zone error handling, and that this only happens when the debugger has already detached.  @christopherfujino if you really want it though I can be probably be convinced.

**Comment by christopherfujino** [comment]
> Given that, I don't think we should CP this given the complexity of the Zone error handling, and that this only happens when the debugger has already detached. @christopherfujino if you really want it though I can be probably be convinced.

Nah, this SGTM. I'll bring it up again if they come for me with pitchforks.
