### ISSUE TITLE
Upgrade flutter 2.8.1 to 3.13.9 has error at dart:js_types

### ISSUE THREAD

**Issue by abeetran** [flutter/flutter#140197]
### Steps to reproduce

1. I build flutter for web
2. My flutter at 2.8.1
3. Updated to 3.13.9
4. Have error at toDart.toInt() and copyWith
<img width="1400" alt="Screenshot 2023-12-15 at 13 43 03" src="https://github.com/flutter/flutter/assets/4253394/c70375f4-79ba-4bcd-9c36-de49ad8be8c0">
this is image error

I installed js_interop: ^0.0.1, the bug does not resolve
Pls help me.
thank you so much

### Expected results

pls give me some instruction to result all bugs

### Actual results

Solve the bugs

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by dam-ease** [comment]
Hi @abeetran
Thanks for filing this.
Can you upgrade to the latest version `3.16.4` to see if this issue still persists?
If it does, Can you try `flutter pub cache repair` and run this again to see if it works in your case?

**Comment by abeetran** [comment]
hi @dam-ease 
In this case i have to build app at version at 3.13.9

**Comment by abeetran** [comment]
I upgrade to 3.16.4 and run it's work
thank you so much @dam-ease
