### ISSUE TITLE
Enable `Update branch` GitHub UI for Cocoon repo

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#140167]
It is not uncommon that the working PRs are out of date with the base branch, and it would be handy to enable `Update branch` UI in Cocoon PRs, same as other repositories. 

Now: 
<img width="1058" alt="Screenshot 2023-12-14 at 11 23 03 AM" src="https://github.com/flutter/flutter/assets/54558023/d61e16e9-d789-408b-b1a7-4a8d4318af27">

Expected:
![Screenshot 2023-12-14 at 11 23 10 AM](https://github.com/flutter/flutter/assets/54558023/037ecc72-5a42-4cd9-93f9-e9b36c83e12d)

**Comment by keyonghan** [comment]
Another issue needs an admin access /cc @godofredoc

**Comment by godofredoc** [comment]
Option has been enabled. The relevant configuration in github is:

![image](https://github.com/flutter/flutter/assets/54371434/9184f7b5-c26a-4632-b38a-46aec8ed715b)
