### ISSUE TITLE
[Impeller] come up with a better way to organize AiksTests

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#140106]
The file is getting too large and it's hard to find things.  It won't scale.

Note: renaming golden tests will invalidate their history.

Possible solutions:
 1) Just break up aiks_unittests.cc based on categories (ex aiks_clipping_unittests.cc, aiks_gradient_unittests.cc)
 1) Completely get rid of aiks_unittests and allow any unittests file to be able to do the same thing so we could mix unittests and golden image tests in a file like `conical_gradient_contents_unittests.cc`

**Comment by gaaclarke** [comment]
I tried splitting up aiks_unittests.cc but keeping the tests the same name.  That doesn't work for the way googletest works.  You'll get a linker error like `ld64.lld: error: duplicate symbol: impeller::testing::kYouInstantiatedAiksTestMultipleTimes`

**Comment by matanlurey** [comment]
I like #2 fwiw :)

**Comment by gaaclarke** [comment]
> I like #2 fwiw :)

I agree.  It's a nontrivial amount of work.  I'm writing up a PR that sorts all of them in that file.  It should be better than what we have now and will only help us with future refactors if we want.

**Comment by gaaclarke** [comment]
closing inlieu of the approach in https://github.com/flutter/engine/pull/49050

**Comment by gaaclarke** [comment]
Oops, meant to close the pull request, not the issue.

**Comment by jonahwilliams** [comment]
@gaaclarke assigning to you because I think you are working on this? If not please unassign and drop the priority back down.

**Comment by gaaclarke** [comment]
> @gaaclarke assigning to you because I think you are working on this? If not please unassign and drop the priority back down.

Yea as I get time I peel some tests out to a new file.  I think we have a decent system now.

**Comment by gaaclarke** [comment]
I'm going to consider this closed.  I have devised a system to organize the tests.  I've split some up and added a warning to the end of aiks_unittests.cc.
