### ISSUE TITLE
Generating a List<Widget> will not respect the declared type of the variable.

### ISSUE THREAD

**Issue by azeunkn0wn** [flutter/flutter#140127]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a List<Widget> with List.generate() or items.map():
`List<Widget> generatedWidgets = List.generate(10, (index) => Text(index.toString())).toList();`

2. print the runtime type of the variable: 
`print(generatedWidgets.runtimeType);`

### Expected results

prints `List<Widget>`

### Actual results

prints `List<Text>`

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

const Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: darkBlue,
      ),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
     List<Widget> test =
      List.generate(10, (index) => Text(index.toString())).toList();  
    
    print(test.runtimeType);
    
    return Text(
      test.runtimeType.toString(),
      style: Theme.of(context).textTheme.headlineMedium,
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Microsoft Windows [Version 10.0.19045.3693]
(c) Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>flutter doctor -v
[√] Flutter (Channel stable, 3.16.4, on Microsoft Windows [Version 10.0.19045.3693], locale en-US)
    • Flutter version 3.16.4 on channel stable at P:\DEV\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2e9cb0aa71 (2 days ago), 2023-12-11 14:35:13 -0700
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at P:\DEV\Android\sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: P:\DEV\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Build Tools 2022 17.4.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
    • Visual Studio Build Tools 2022 version 17.4.33213.308
    ! Unable to locate a Windows 10 SDK. If building fails, install the Windows 10 SDK in Visual Studio.

[√] Android Studio (version 2022.3)
    • Android Studio at P:\DEV\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.85.0)
    • VS Code at C:\Users\AzE\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19045.3693]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 120.0.6099.71
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 120.0.2210.61

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by azeunkn0wn** [comment]
my workaround is wrapping the list generator with `List<Widget>.from()`
`List<Widget>.from(List<Widget> generatedWidgets = List.generate(10, (index) => Text(index.toString())).toList());`

**Comment by moffatman** [comment]
Sorry what is the impact here? List<Text> is a subtype of List<Widget>, you still have a List<Widget>?

**Comment by azeunkn0wn** [comment]
> Sorry what is the impact here? List<Text> is a subtype of List<Widget>, you still have a List<Widget>?

I wanted to add another widget in the list that is not a Text.

**Comment by moffatman** [comment]
Ah ok, you can specify the exact type like this:

`List<Widget>.generate(10, ...);`

**Comment by azeunkn0wn** [comment]
> Ah ok, you can specify the exact type like this:
> 
> `List<Widget>.generate(10, ...);`

worked with .generate().
how about for the items.map(...) ?

```   
    ...
    final List<String> items = List<String>.generate(10,(index)=>index.toString());  // Example items
    List<Widget> listOfWidgets = items.map((e)=> Text(e)).toList();
    print(listOfWidgets.runtimeType);
    
    listOfWidgets.add(Container()); // error: expecting a Text widget.
    ...
```

the biggest issue I have with this is that the dart analyzer recognized the variable as List<Widget>, but it is not in runtime.

**Comment by nandanurseptama** [comment]
> > Ah ok, you can specify the exact type like this:
> > `List<Widget>.generate(10, ...);`
> 
> worked with .generate(). how about for the items.map(...) ?
> 
> ```
>     ...
>     final List<String> items = List<String>.generate(10,(index)=>index.toString());  // Example items
>     List<Widget> listOfWidgets = items.map((e)=> Text(e)).toList();
>     print(listOfWidgets.runtimeType);
>     
>     listOfWidgets.add(Container()); // error: expecting a Text widget.
>     ...
> ```
> 
> the biggest issue I have with this is that the dart analyzer recognized the variable as List, but it is actually not in runtime.

You can infer ```map``` function too, like this :

```dart
List<widget> listOfWidgets = items.map<Widget>((e)=> Text(e)).toList();
```

**Comment by moffatman** [comment]
So we do have some workarounds here, but I do agree, it is kind of a bad edge case. It may be a drawback of Dart type system, in Java this may be covered by the wildcard type concept e.g. `List<? extends Widget>`. But here, we should have some resolution, either an analyzer lint which notes this problem, or even compiler change which makes it a `List<Widget>` automatically.

**Comment by mraleph** [comment]
This is working as specified: type inference context does not propagate to the receiver of a method call e.g. here we have `.toList()` call on `List.generate(10, (index) => Text(index.toString()))` - `.toList()` has type inference context `List<Widget>` but this information does not get used when inferring `List.generate(...)` - instead an empty context is used.

There have been various discussions in the Dart language team on how to handle this and there are some proposals - but nothing definitive at this time. 

@eernstg do you know if there are any issues on the language repo that track this behavior of loosing inference context when going through method call to its receiver expression?

**Comment by eernstg** [comment]
> know if there are any issues on the language repo that track this behavior of loosing inference context

I'm not able to find issues specifically about that topic, but there is an ongoing effort in the direction of propagating the appropriate kind of context into receiver positions.

@chloestefantsova (who's the initiator and main driver of this effort), perhaps you could give some hints about where we might go with this?

Until then, @azeunkn0wn, you could make things work better by providing the type information "at the beginning" of the type inference process (feeding forward) rather than "at the end" (where we are solving for actual type arguments in the initializing expression based on a given end result, namely the declared type of the variable):

```dart
var generatedWidgets =
    List<Widget>.generate(10, (index) => Text(index.toString())).toList();
```

You could argue that readability suffers a bit when the type of the variable isn't stated explicitly, but in cases like this where the type is implied by the constructor invocation right after the `=` it may not be a problem. In any case, type arguments that feed forward like this will in general overcome the lack of context type for receivers, and it usually doesn't make the declaration more verbose.

**Comment by chloestefantsova** [comment]
Like @mraleph and @eernstg mentioned, this is behavior as specified in Dart currently. In all invocations of all kind of members the receiver is always inferred in the empty context, which prevents propagation of the surrounding type context information down the AST. It is something that I want to change with an update to the inference mechanism. In short, the type inference will use a new kind of encoding for the type information and will be able the infer more meaningful type arguments to functions like `map`.

So in the following line the type inference with the proposed updates will be able to infer the missing type argument for `map` as `Widget`

```dart
List<Widget> listOfWidgets = items.map((e)=> Text(e)).toList();
```

**Comment by mraleph** [comment]
@eernstg @chloestefantsova does it maybe make sense to file an umbrella issue for Receiver Type Inference on the dart-sdk/language repo so that we could link users to it?

**Comment by eernstg** [comment]
Certainly, here we go: https://github.com/dart-lang/language/issues/3523.

**Comment by chloestefantsova** [comment]
> @eernstg @chloestefantsova does it maybe make sense to file an umbrella issue for Receiver Type Inference on the dart-sdk/language repo so that we could link users to it?

> Certainly, here we go: [dart-lang/language#3523](https://github.com/dart-lang/language/issues/3523).

And here's the `feature` part of it: https://github.com/dart-lang/language/issues/3527.

**Comment by goderbauer** [comment]
I am going to close this issue since it is not specific to Flutter. Looks like the appropriate issues have been opened on the Dart side and discussion can continue there.
