### ISSUE TITLE
Easy access high contrast color (like onColor from a color)

### ISSUE THREAD

**Issue by ArthurREGNARD** [flutter/flutter#140135]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Similar to the ColorScheme feature, allow the generation of a color palette with high contrast from a specified color seed. This would simplify the process of defining specific color attributes, such as backgroundColor and foregroundColor, for elements like buttons, ensuring a visually appealing and accessible design with distinct color contrast.

### Proposal

Define a class like ColorScheme but with less atribute.

**Comment by dkwingsmt** [comment]
cc @QuncCccccc

**Comment by QuncCccccc** [comment]
We can now generate high-contrast `ColorScheme` by providing a `contrastLevel` in `ColorScheme.fromSeed()`:)
