### ISSUE TITLE
canvaskit folder is too big

### ISSUE THREAD

**Issue by bakteribaik** [flutter/flutter#140161]
so I just created a web page and then tried to build it into release mode, I was quite surprised by the size of the build folder up to 19MB. After I searched the contents of the folder, it turned out that the canvaskit folder was 14MB in size. 

![image](https://github.com/flutter/flutter/assets/64103383/3afc8d6b-f6c9-4afb-98e0-b99f22a7cfdc)

I tried running the command
`flutter build web --web-renderer html`

but still the canvaskit folder is in it. I tried deleting the canvaskit folder and refreshing the website and it seems safe, nothing errors or changed, will it have an impact in the future if I delete the folder? because with a web size of up to 19MB it will take more time for the web to load

**Comment by darshankawar** [comment]
@bakteribaik 
I think your issue is similar to https://github.com/flutter/flutter/issues/126738 so please follow-up in it for further updates.
Closing this as a duplicate.
