### ISSUE TITLE
Flutter Module can't run with a plugin imported but Flutter app can do

### ISSUE THREAD

**Issue by WYK15** [flutter/flutter#140128]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. create a flutter module
2. change `dependencies` in pubspec.yaml, add my plugin
3. code some function in main.dart
4. `flutter run` with connected iPhone
5. error comes out: Could not build the precompiled application for the device.
Error (Xcode): Undefined symbol: _OBJC_CLASS_$_CaptchaOption
6. I create a new flutter app
7. add dependencies in  pubspec.yaml like above, copy code in main.dart above, flutter pub get, flutter run, and it runs.

by the way. my plugin is special, it wraps a native .xcframework, don't know if it makes a difference or not

### Expected results

hope module runs successfully with my plugin imported like flutter app

### Actual results

in flutter module, I run `flutter run`,  symbol in my plugin can not be founded.
it seems like my plugin isn't imported to module successfully

### Code sample

this is flutter module on github:
https://github.com/WYK15/MFCaptcha

### Flutter Doctor output

```shell
[✓] Flutter (Channel stable, 3.16.4, on macOS 13.4 22F66 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.16.4 on channel stable at /Users/wangyankun/Documents/Environments/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2e9cb0aa71 (2 days ago), 2023-12-11 14:35:13 -0700
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/wangyankun/Documents/Environments/AndroidEnvironment/android-sdk-macosx
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (3 available)
    • iPhone 8 white (mobile) • ee838f0919a8f547118d1ba72f5f7aa82aa4c5aa • ios            • iOS 14.4.2 18D70
    • macOS (desktop)         • macos                                    • darwin-x64     • macOS 13.4 22F66
      darwin-x64
    • Chrome (web)            • chrome                                   • web-javascript • Google Chrome
      118.0.5993.117
    ! Error: Browsing for iPhone 11 green (CoreDevice)  on the local area network. Ensure that the device is booted,
      unlocked, and discoverable via Bluetooth and WiFi, or attached with a cable. (code -27)

[✓] Network resources
    • All expected network resources are available.
```

**Comment by dam-ease** [comment]
Hi @WYK15.
Thanks for filing this.
I see this issue occurs only with iOS
Can you try deleting the iOS folder and running `flutter create .` to enable iOS in your project again?
Then try running the app, this should work fine afterwards.

**Comment by WYK15** [comment]
@dam-ease 
if I run `flutter create .`,a new ios directory is created, and it runs well.
but I just want to run ios project in the flutter module, there is a .ios directory in the flutter module,
I run `flutter run` or open  Runner.xcworkspace with Xcode, both can't work, report the same error: 
Undefined symbol: OBJC_CLASS$_CaptchaOption.
Can the project in .ios directory run successfully without creating a new flutter project by `flutter create .`

**Comment by dam-ease** [comment]
Thanks for your response

> Can the project in .ios directory run successfully without creating a new flutter project by flutter create .

Not sure I got this, does this work now or you will like to run it through Xcode?

**Comment by WYK15** [comment]
nope, I just want [the flutter module](https://github.com/WYK15/MFCaptcha) I uploaded to run successfully.
I have tried create a new flutter app by `flutter create .` and import my flutter plugin, it runs well.
but created a flutter module and imported the same plugin, error comes. so I uploaded the module project to github above.
Why does the same plugin work in a Flutter app but throw errors in a Flutter module.

**Comment by dam-ease** [comment]
It seems your question might be best suited for support channels like StackOverflow, please ask the same there for solutions if any. Please also see [flutterhelp](https://www.reddit.com/r/flutterhelp/) for resources and ask questions like this.

Closing from here as this is more of a how-to question rather than a bug or feature request. If you disagree, please comment with more information and I'll reopen this.
Thank you!
