### ISSUE TITLE
Convert a ``Navigator.push()`` into a ``showDialog`` based on the screen dimensions

### ISSUE THREAD

**Issue by JGeek00** [flutter/flutter#140152]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

I want to create a fully responsive application, and I want some screens to have two different behaviors based on the screen dimensions.
- On mobile the new screen will be opened with Navigator.push() like a normal screen
- On desktop and tablet the new screen will be opened with ``showDialog``

I want to create this behavior because I have some screens that have enough content to fill a mobile screen, but that doesn't have enough content to fill a tablet or desktop screen.

It would be something similar to what I described on this other issue https://github.com/flutter/flutter/issues/133946

The problem is that this change has to be dynamic based on the screen dimensions, because on desktop you can resize the window, and on mobile or tablet you can rotate the screen.

Now I have this behavior by using ``Dialog`` and ``Dialog.fullscreen``, but the problem is that even if ``Dialog.fullscreen`` looks like a normal screen, it doesn't behave like that because, for example, on iOS it doesn't support the swipe to go back gesture.

### Proposal

Create something like this:

```dart
showResponsiveScreen(
  breakingWidth: 900,
  screenBuilder: (ctx) => Container()       // Widget to display on mobile
  modalBuilder: (ctx) => Container()        // Widget to display on tablet and desktop
)
```

Example:
The user pushes a new route when the device screen is small. This route will be opened using the same ``MaterialPageRoute`` animation. Then, the user rotates the device and now the device screen width excedes the breakingWidth. On that moment, that route should change to a modal. And then if the user closes the route when it's on modal mode, it should close with the modal animation.

**Comment by darshankawar** [comment]
Thanks for the report @JGeek00 
Have you looked at different ways to make the app responsive as mentioned in the [documentation](https://docs.flutter.dev/ui/layout/responsive/adaptive-responsive#creating-a-responsive-flutter-app) and check if using any of the widgets listed in it  can be used to achieve your use case ?

**Comment by JGeek00** [comment]
> You can't really swap out a modal route like that.... instead the route should itself have responsive layout and appearance.

Ok @moffatman 
So is it possible to push a route that looks like a modal? I mean a route with a widget that doesn't fill the whole screen, and has a translucent overlay that let's you see the widget that's behind.

**Comment by moffatman** [comment]
Yes, route doesn't have to be opaque, it can be transparent too. In fact showDialog just pushes a `DialogRoute`

**Comment by JGeek00** [comment]
@moffatman thank you. With this code I managed to achieve what I wanted. 

```dart
    void openScreen() {
      Navigator.of(context).push(
        PageRouteBuilder(
          opaque: false,
          barrierColor: Colors.black54,
          pageBuilder: (context, animation, secondaryAnimation) {
            if (MediaQuery.of(context).size.width > 700) {
              return  Dialog(
                child: ClipRRect(
                  borderRadius: BorderRadius.circular(28),
                  child: const Screen2()
                ),
              );
            }
            else {
              return const Screen2();
            }
          },
        )
      );
    }
```

**Comment by JGeek00** [comment]
I found this code by digging on how ``MaterialPageRoute`` works.
```dart
final PageTransitionsTheme theme = Theme.of(context).pageTransitionsTheme;
return theme.buildTransitions(this, context, anim1, anim2, child);
```
I think it does what I want, create an Android animation for Android devices and an iOS animation for iOS devices, but it asks for a ``Route`` on the first parameter, and I don't know what to do.

That's basically the behavior that I want: on large displays to show a modal, and on small displays a normal Android or iOS animation.


```dart
void openScreen() {
      Navigator.of(context).push(
        PageRouteBuilder(
          opaque: false,
          barrierColor: Colors.black54,
          transitionDuration: const Duration(milliseconds: 150),
          transitionsBuilder: (context, anim1, anim2, child) {
            if (MediaQuery.of(context).size.width > 700) {
              return FadeTransition(
                opacity: CurvedAnimation(
                  parent: anim1,
                  curve: Curves.easeOut,
                ),
                child: child,
              );
            }
            else {
              final PageTransitionsTheme theme = Theme.of(context).pageTransitionsTheme;
              return theme.buildTransitions(// route //, context, anim1, anim2, child);
            }
          },
          pageBuilder: (context, animation, secondaryAnimation) {
            if (MediaQuery.of(context).size.width > 700) {
              return  Dialog(
                child: ClipRRect(
                  borderRadius: BorderRadius.circular(28),
                  child: const Screen2()
                ),
              );
            }
            else {
              return const Screen2();
            }
          },
        )
      );
    }
```

**Comment by moffatman** [comment]
You may have to create a custom `Route` class probably can't just do it inline within `PageRouteBuilder`?

**Comment by JGeek00** [comment]
@moffatman i tried ro do it with ``PageRouteBuilder`` and I managed to display a modal or not depending on the screen size. I also managed to reproduce the dialog animation, but not the Android or iOS animation. I want to display the normal ``MaterialPageRoute`` animation when the screen is small, but I don't know how to do it. I also want to have the swipe to go back gesture that's available on iOS.

**Comment by moffatman** [comment]
I would expect its a lot of work yeah....

**Comment by darshankawar** [comment]
@JGeek00 
Based on above conversation, it seems the use case is achievable using the approach you mentioned without a need to add the requested feature in the framework itself ?

**Comment by JGeek00** [comment]
Yes, but I don't know how to do it. I would appreciate some help or guidance, and then leave the solution here for other developers that could want the same behavior.

**Comment by darshankawar** [comment]
> I would appreciate some help or guidance, and then leave the solution here for other developers that could want the same behavior.

You may raise this in StackOverflow.

**Comment by JGeek00** [comment]
Ok. Here I have opened the question on StackOverflow.

https://stackoverflow.com/questions/77684295/im-creating-a-responsive-materialpageroute-and-i-need-some-support

If someone could help me I would appreciate it.

**Comment by darshankawar** [comment]
> in the [documentation](https://docs.flutter.dev/ui/layout/responsive/adaptive-responsive#creating-a-responsive-flutter-app)

You may want to refer to this and check if using any of the widgets mentioned, can be used to achieve the use case. 

> If someone could help me I would appreciate it.


Since this is more of a support question, I'll close it for now, because your original proposal doesn't seem to be feasible and also based on [this](https://github.com/flutter/flutter/issues/140152#issuecomment-1857996150) comment.

**Comment by JGeek00** [comment]
@darshankawar what I'm trying to achieve doesn't imply swapping routes. I'm trying to replicate a responsive version of the ``MaterialPageRoute`` that uses a different animation based on the screen width. Currently I have the behavior that I wanted, but I found an unexpected problem.

To do that I cloned the ``MaterialPageRoute`` class that comes with the material package, but the behavior is different, even when the code on both classes is exactly the same (with the difference of the class name). As you can see on the attached file, the animation of the route that is pushed is ok, but the animation of the route that's behind it's not ok. Since the code of this ``ResponsiveMaterialPageRoute`` that i'm creating is the same as the code of the current ``MaterialPageRoute``, there shouldn't be any difference on the behavior.


https://github.com/flutter/flutter/assets/47545344/9d971886-ed58-48b6-8c68-9a9cb52bc3bb
