### ISSUE TITLE
There should be guidance to get GAR for a Flutter applications.

### ISSUE THREAD

**Issue by polina-c** [flutter/flutter#140174]
### Use case

-

### Proposal

-

**Comment by darshankawar** [comment]
Hi @polina-c 
Could you please add some description on what you are looking for ?
I looked for GAR and came across https://api.flutter.dev/flutter/vector_math/Vector4/gar.html but not sure if this is what you are referring to.

**Comment by polina-c** [comment]
closing this
there is duplicate in buganizer
sorry for leaving it this way
