### ISSUE TITLE
Proposal to be able to add divided after the last element in Listview.seperated

### ISSUE THREAD

**Issue by faisalansari0367** [flutter/flutter#140146]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

In a design where we need to show divider at the last of the element we have do following:
1. add 1 to the itemcount and then check for last element and add the divider
2. check for the last element and wrap it inside a column and then add the divider in column widget.

### Proposal

It would be way easier to just configure one bool variable to show the divider after the last index or not by adding an extra parameter in the Listview.seperated (for example: showDivider atLast) something like that to control this functionality.

**Comment by dam-ease** [comment]
Hi @faisalansari0367.
Thanks for proposing this.

This is a known proposal, see https://github.com/flutter/flutter/issues/134272 which was closed per this https://github.com/flutter/flutter/pull/138672#discussion_r1401363002.
You can follow up on these in the issue links shared above.

Closing this from here, if you disagree, please comment and I'll reopen this.
Thank you.
