### ISSUE TITLE
Use CurveTween instead of CurvedAnimation in docs and samples

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter#14015]
The current [animation docs](https://flutter.io/tutorials/animation/#curvedanimation) teach users to use CurvedAnimation to specify the easing curve of a Tween-based animation. This API is less usable than `CurveTween` for this use case because it requires the user to declare the animation's controller on a different object after adding the modifying the timing curve of the Tween. 

For example, let's say the user has this tween animation specified initially:
```
animation = new Tween(begin: 0.0, end: 300.0).animate(controller);
```
She now wants to make it a little more interesting by setting a non-linear easing curve. If she is using the CurvedAnimation, she'd do the following:

```
animation = new Tween(begin: 0.0, end: 300.0).animate(curve);
curve = new CurvedAnimation(parent: controller, curve: Curves.easeIn);
```
But with CurveTween, she don't have to change `animate(controller)` and won't need to deal with the parent property of the CurvedAnimation object:

```
animation = new Tween(begin: 0.0, end: 300.0).chain(
    new CurveTween(
        curve: Curves.easeIn,
        )
     ).animate(controller);
```

IMO, we should recommend using CurveTween over CurvedAnimation for this use case in our docs. 

Cc: @Sfshaza @Hixie @HansMuller

**Comment by Sfshaza** [comment]
Excellent feedback!

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2003](https://github.com/flutter/website/issues/2003) via [**ZenHub**](https://www.zenhub.com/)
