### ISSUE TITLE
Unpin test, test_api and test_core in flutter.

### ISSUE THREAD

**Issue by polina-c** [flutter/flutter#140169]
These packages are pinned various test dependencies need to update their mockito constraint to 5.4.4, which accepts test_api v0.7.0.

See discussion: https://discord.com/channels/608014603317936148/1184909649703600248

**Comment by christopherfujino** [comment]
Looks like all the mockito deps in flutter/packages will need to be bumped, published, and the testing pin in flutter/flutter updated:

https://github.com/search?q=repo%3Aflutter%2Fpackages+mockito+pubspec.yaml&type=code

**Comment by christopherfujino** [comment]
and mockito is pinned in flutter/packages because it appears in https://github.com/flutter/packages/blob/main/script/configs/allowed_pinned_deps.yaml#L23

**Comment by huycozy** [comment]
From primary triage POV, I think this is suited to tool team. Please update labels if it's not correct.

**Comment by christopherfujino** [comment]
This is currently blocked by a circular dependency between flutter/flutter and devtools

Unblocking will require:
- [ ] disable the DevTools flutter customer tests
- [ ] roll vm_service forward in flutter/flutter
- [ ] once the DevTools CI picks up this version of Flutter and the build goes red, Derek can land his DevTools PR to bump to vm_service 14 and fix the build
- [ ] re-enable the DevTools flutter customer tests with the hash of Derek's DevTools PR
