### ISSUE TITLE
Add scrollbar to DropdownMenu when list requires scrolling

### ISSUE THREAD

**Issue by tylervanderhoef** [flutter/flutter#140162]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

When using the new `DropdownMenu` widget to convert to material 3 from the `DropdownList`, the documentation states the following:

> Updating to [DropdownMenu](https://api.flutter.dev/flutter/material/DropdownMenu-class.html)
There is a Material 3 version of this component, [DropdownMenu](https://api.flutter.dev/flutter/material/DropdownMenu-class.html) that is preferred for applications that are configured for Material 3 (see [ThemeData.useMaterial3](https://api.flutter.dev/flutter/material/ThemeData/useMaterial3.html)). The [DropdownMenu](https://api.flutter.dev/flutter/material/DropdownMenu-class.html) widget's visuals are a little bit different, see the Material 3 spec at [m3.material.io/components/menus/guidelines](https://m3.material.io/components/menus/guidelines) for more details.

When browsing the Material 3 documentation, you can see that [drop down menus should show a scroll bar](https://m3.material.io/components/menus/guidelines#2da2f810-4baa-4f61-9ba8-578791b84efe) when the list requires scrolling, yet when a list is long and requires scrolling, no scroll bar is visible as I would expect.

I would expect that a scrollbar is visible to indicate to users that there is more content to be seen, rather than the user needing to try it on their own.

In the example below, I generated a list of 50 items, and you can see that there is no scrollbar on the right even when I scroll down the list.

<img width="418" alt="Screenshot 2023-12-14 at 9 11 24 AM" src="https://github.com/flutter/flutter/assets/104478095/0b6a6ca5-50ff-40e1-9f7c-aade98af10a4">

## Flutter Logs
[flutter_doctor.log](https://github.com/flutter/flutter/files/13676267/flutter_doctor.log)

## Minimal code to reproduce
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: true),
      home: DropdownMenuTest(),
    );
  }
}

class DropdownMenuTest extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final entries = Iterable.generate(
      50,
      (i) => DropdownMenuEntry(value: i, label: i.toString()),
    ).toList();

    return Scaffold(
      body: Center(
        child: DropdownMenu(dropdownMenuEntries: entries),
      ),
    );
  }
}
```

### Proposal

It would be great if there was a way to configure the scrolling functionality, or at a minimum, show the scrollbar as dictated by the [Material 3 guides on this subject](https://m3.material.io/components/menus/guidelines#2da2f810-4baa-4f61-9ba8-578791b84efe).

**Comment by nandanurseptama** [comment]
Yes, i think it should be have scroll indicator too when the `entries` are too long and need to be scrolling.

**Comment by huycozy** [comment]
Thanks for the proposal. I see this can be solved by adding a ScrollBar for SingleChildScrollView in MenuAnchor (DropdownMenu uses it internally) at:

https://github.com/flutter/flutter/blob/a899e04bef12fe4b185b244c89975d83fdaf0879/packages/flutter/lib/src/material/menu_anchor.dart#L3457

**Comment by QuncCccccc** [comment]
Thanks for filing this issue! Looks like when this is running on desktops, the scrollbar will show up and we can use `ScrollbarTheme` to configure the scroll bar. But it doesn't work on mobiles. Still investigating.

**Comment by Piinks** [comment]
The ScrollBehavior (or MaterialScrollBehavior) is what would handle this through buildScrollbar.

**Comment by Piinks** [comment]
Probably something similar to what is in the older _DropdownMenuState:

https://github.com/flutter/flutter/blob/4d624cded34a1894990e8ea2acb9cf10ef29abab/packages/flutter/lib/src/material/dropdown.dart#L301-L315

**Comment by QuncCccccc** [comment]
> Probably something similar to what is in the older _DropdownMenuState:
> 

Thanks a lot for the hint! Just added a fix:)!
