### ISSUE TITLE
Linux/GTK embedder is placing C++ std::function instances within GTK objects

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#140183]
Some GTK objects declared in the Linux embedder contain instances of `std::function`

For example, `send_key_event` in `_FlKeyEmbedderResponder`.

The `_FlKeyEmbedderResponder` is initialized using `g_object_new`.  `g_object_new` appears to be zeroing out the entire `_FlKeyEmbedderResponder` struct and is not calling constructors for any C++ object members within the struct.

This will potentially fail on implementations of `std::function` that depend on proper construction.  Specifically, in https://github.com/flutter/engine/pull/49002 we tried to upgrade to a new version of the libcxx ABI and found that usage of the `std::function` members crashes if the constructor has not run.

@cbracken @robert-ancell

**Comment by dkwingsmt** [comment]
I opened a PR to replace this `std::function` with a C function a `user_data`. https://github.com/flutter/engine/pull/49293
