### ISSUE TITLE
After longpress in any Text-field then can't tap the field to show the keyboard

### ISSUE THREAD

**Issue by subins829** [flutter/flutter#140141]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Just longpress the field and dsimiss the keyboard then clicking the field not working

### Expected results

Need to be able to click the field again

### Actual results

Need to be able to click the field again

### Code sample

<details><summary>Code sample</summary>
Expanded(
              child: GestureDetector(
                behavior: HitTestBehavior.opaque,
                onPanDown: (_) {
                  FocusScope.of(context).requestFocus(FocusNode());
                },
                child: SingleChildScrollView(
                  child: MetaForm(
                    renderer: manager.renderer,
                    config: MetaFormConfig(
                      metadata: manager.metaEntity!,
                      metaFields: manager.metaFields,
                      formFieldMode: formFieldMode,
                      activity: activity,
                      showButtons: activity == MetaFormActivity.search ||
                          activity == MetaFormActivity.create,
                      isReadOnly: widget.isReadOnly,
                      secondaryButtonText:
                          activity == MetaFormActivity.create ? 'Cancel' : null,
                    ),
                    onSearch: (field, text) =>
                        manager.search(field, text ?? " "),
                    onReset: widget.onReset != null
                        ? (reset) {
                            widget.onReset!(reset);
                          }
                        : null,
                    onSubmit: () {
                      if (activity == MetaFormActivity.search) {
                        _onSearch(buildContext);
                      } else {
                        _onSubmit(buildContext);
                      }
                    },
                  ),
                ),
              ),
            ),

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/90414446/f9178bec-077e-43b3-ae51-e64d31f09e0e

</details>

### Logs

<details><summary>Logs</summary>

```[✓] Flutter (Channel stable, 3.10.3, on macOS 14.1.2 23B92 darwin-arm64, locale en-CO)
    • Flutter version 3.10.3 on channel stable at /Users/aptmac/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f92f44110e (7 months ago), 2023-06-01 18:17:33 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/aptmac/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.85.0)
    • VS Code at /Users/aptmac/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (4 available)
    • iPad (mobile)                                  • 00008030-000834CE26D8C02E            • ios            • iOS 17.1.2 21B101
    • iPad Pro (12.9-inch) (5th generation) (mobile) • B7DAC607-6578-4590-98C5-7EE03877FCBF • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)                                • macos                                • darwin-arm64   • macOS 14.1.2 23B92
      darwin-arm64
    • Chrome (web)                                   • chrome                               • web-javascript • Google Chrome
      120.0.6099.71

[✓] Network resources
    • All expected network resources are available.
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```[✓] Flutter (Channel stable, 3.10.3, on macOS 14.1.2 23B92 darwin-arm64, locale en-CO)
    • Flutter version 3.10.3 on channel stable at /Users/aptmac/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f92f44110e (7 months ago), 2023-06-01 18:17:33 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/aptmac/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.85.0)
    • VS Code at /Users/aptmac/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (4 available)
    • iPad (mobile)                                  • 00008030-000834CE26D8C02E            • ios            • iOS 17.1.2 21B101
    • iPad Pro (12.9-inch) (5th generation) (mobile) • B7DAC607-6578-4590-98C5-7EE03877FCBF • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)                                • macos                                • darwin-arm64   • macOS 14.1.2 23B92
      darwin-arm64
    • Chrome (web)                                   • chrome                               • web-javascript • Google Chrome
      120.0.6099.71

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by dam-ease** [comment]
Thanks for filing this @subins829.

I see you are on an older version of flutter, can you please upgrade to the latest versions to confirm this issue still persists, if it does, we will need you to provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code i.e a single `main.dart` file we could run on our end?

Thank you!

**Comment by subins829** [comment]
`import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual, overlays: []);
  runApp(
    MyApp(),
  );
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Forms',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Forms'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final TextStyle textstyle =
      const TextStyle(color: Colors.white, fontWeight: FontWeight.bold);
  final InputDecoration decoration = const InputDecoration(
    border: OutlineInputBorder(),
  );
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: GestureDetector(
        behavior: HitTestBehavior.translucent,
        onPanDown: (_) => FocusScope.of(context).requestFocus(FocusNode()),
        child: SingleChildScrollView(
          child: Center(
            child: Padding(
              padding: const EdgeInsets.all(8.0),
              child: Center(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: [
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    MaterialButton(
                      onPressed: () {},
                      color: Colors.red,
                      minWidth: 160,
                      child: Text(
                        'Google',
                        style: textstyle,
                      ),
                    ),
                    MaterialButton(
                      color: Colors.blue,
                      minWidth: 160,
                      onPressed: () {},
                      child: Text(
                        'Facebook',
                        style: textstyle,
                      ),
                    ),
                    MaterialButton(
                      color: Colors.orange,
                      minWidth: 160,
                      onPressed: () {},
                      child: Text(
                        'E-mail',
                        style: textstyle,
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
`

**Comment by subins829** [comment]
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual, overlays: []);
  runApp(
    MyApp(),
  );
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Forms',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Forms'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final TextStyle textstyle =
      const TextStyle(color: Colors.white, fontWeight: FontWeight.bold);
  final InputDecoration decoration = const InputDecoration(
    border: OutlineInputBorder(),
  );
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: GestureDetector(
        behavior: HitTestBehavior.translucent,
        onPanDown: (_) => FocusScope.of(context).requestFocus(FocusNode()),
        child: SingleChildScrollView(
          child: Center(
            child: Padding(
              padding: const EdgeInsets.all(8.0),
              child: Center(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: [
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    MaterialButton(
                      onPressed: () {},
                      color: Colors.red,
                      minWidth: 160,
                      child: Text(
                        'Google',
                        style: textstyle,
                      ),
                    ),
                    MaterialButton(
                      color: Colors.blue,
                      minWidth: 160,
                      onPressed: () {},
                      child: Text(
                        'Facebook',
                        style: textstyle,
                      ),
                    ),
                    MaterialButton(
                      color: Colors.orange,
                      minWidth: 160,
                      onPressed: () {},
                      child: Text(
                        'E-mail',
                        style: textstyle,
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

**Comment by subins829** [comment]
when we long press the field and swipe up , then the keyboard dsimiss and then we cant access the field later on

**Comment by subins829** [comment]
Is there any proper way to dismiss the keyboard with no issues ?
Tried  `keyboardDismissBehavior: ScrollViewKeyboardDismissBehavior.onDrag` but this will not fully close the keyboard

**Comment by Utkarsh4517** [comment]
Hey @subins829  I tried your code, I found no issues as described here

> when we long press the field and swipe up , then the keyboard dsimiss and then we cant access the field later on


Here's the code I tried:
```  
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual, overlays: []);
  runApp(
    const MyApp(),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Forms',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const HomePage(title: 'Flutter Forms'),
    );
  }
}

class HomePage extends StatefulWidget {
  final String title;
  const HomePage({
    super.key,
    required this.title,
  });

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  final TextStyle textstyle =
      const TextStyle(color: Colors.white, fontWeight: FontWeight.bold);
  final InputDecoration decoration = const InputDecoration(
    border: OutlineInputBorder(),
  );
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: GestureDetector(
        behavior: HitTestBehavior.translucent,
        onPanDown: (DragDownDetails details) =>
            FocusScope.of(context).requestFocus(FocusNode()), // provide DragDownDetails here.
        child: SingleChildScrollView(
          child: Center(
            child: Padding(
              padding: const EdgeInsets.all(8.0),
              child: Center(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: [
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    TextFormField(
                      decoration: decoration,
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    MaterialButton(
                      onPressed: () {},
                      color: Colors.red,
                      minWidth: 160,
                      child: Text(
                        'Google',
                        style: textstyle,
                      ),
                    ),
                    MaterialButton(
                      color: Colors.blue,
                      minWidth: 160,
                      onPressed: () {},
                      child: Text(
                        'Facebook',
                        style: textstyle,
                      ),
                    ),
                    MaterialButton(
                      color: Colors.orange,
                      minWidth: 160,
                      onPressed: () {},
                      child: Text(
                        'E-mail',
                        style: textstyle,
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}


  ```

Here's a screen recording 

https://github.com/flutter/flutter/assets/71646773/2cdfa521-8a0a-4451-aecf-3716cb74fdca

**Comment by dam-ease** [comment]
Thanks for your input @Utkarsh4517.
@subins829. I can't reproduce this on my end as well, I see the same behaviour as @Utkarsh4517.
Can you help with more information on how you reproduced this, most especially with the code sample you shared?

**Comment by subins829** [comment]
Hi @dam-ease @Utkarsh4517 

This issue is related to ipad only.

got a hint --> https://github.com/flutter/flutter/issues/101067 --> something like this

**Comment by subins829** [comment]
https://github.com/flutter/flutter/assets/90414446/e97e8b2e-9f98-4f87-bbe9-aa121736bcfb
