### ISSUE TITLE
Misleading Documentation for `isDeviceSupported()` Method of the "local_auth" Flutter plugin 

### ISSUE THREAD

**Issue by vivekjivani** [flutter/flutter#140148]
## **Issue:**
The current documentation for the [`isDeviceSupported()`](https://pub.dev/documentation/local_auth/latest/local_auth/LocalAuthentication/isDeviceSupported.html) method in the "local_auth" Flutter plugin does not accurately represent its main functionality. The documentation states, "Returns true if the device is capable of checking biometrics or is able to fail over to device credentials," which can be misleading.

## **Proposed Action:**
1. Update the documentation to accurately describe the primary functionality of the [`isDeviceSupported()`](https://pub.dev/documentation/local_auth/latest/local_auth/LocalAuthentication/isDeviceSupported.html) method, emphasizing its purpose in checking if a device has a user-configured system lock.

2. Consider renaming the method to better reflect its functionality, perhaps to something like [`isDeviceLockConfigured()`](https://pub.dev/documentation/local_auth/latest/local_auth/LocalAuthentication/isDeviceSupported.html).

This adjustment will enhance the clarity and user-friendliness of the plugin's documentation, preventing potential confusion among developers.

Please feel free to correct me if I misunderstood the intended functionality of the [`isDeviceSupported()`](https://pub.dev/documentation/local_auth/latest/local_auth/LocalAuthentication/isDeviceSupported.html). Your insights are valuable in ensuring accurate and helpful documentation for the "local_auth" Flutter plugin.

Thank you for your attention to this matter.

**Comment by danagbemava-nc** [comment]
Hi @vivekjivani, how is the documentation misleading?

**Comment by vivekjivani** [comment]
hi @danagbemava-nc, Thanks for Responding, I realized it is not misleading but I didn't get it in the first shot, my request is to change the description of the method to a simpler sentence or add a more descriptive description.

Thanks.

**Comment by danagbemava-nc** [comment]
Hi @vivekjivani, what would you propose it be updated to?

**Comment by vivekjivani** [comment]
I already Proposed in Posiabble Actions in the Issue description,

Also, I wanted you to know that the documentation for [flutter_webview](https://pub.dev/packages/webview_flutter) is poor, you guys need someone who can manage the plugin documents well so people like me don't have to struggle for two days just because documentation is missing proper explanation and examples

**Comment by danagbemava-nc** [comment]
Thanks for update. 

> Also, I wanted you to know that the documentation for [flutter_webview](https://pub.dev/packages/webview_flutter) is poor, you guys need someone who can manage the plugin documents well so people like me don't have to struggle for two days just because documentation is missing proper explanation and examples

Kindly file issues that describe how the documentation is not clear so that it can be improved. 

Thank you

**Comment by stuartmorgan** [comment]
> I realized it is not misleading but I didn't get it in the first shot, my request is to change the description of the method to a simpler sentence or add a more descriptive description.

It's still not clear to me what is being requested here; the proposed changes would make it longer, not simpler, and the current description is accurate as far as I'm aware (and it sounds like you agree that's the case).

Absent a specific actionable suggestion, closing.
