### ISSUE TITLE
run  demo the  iOS mobile the keyboard blocks the input box

### ISSUE THREAD

**Issue by steven-gao** [flutter/flutter#140121]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

 1 download the latest demo
2 chang url 'https://flutter.dev'   to   'https://qamp.yeepay.com/boss-app-access/merchantManage/business?update=Y'

### Expected results

The keyboard does not cover the input box

### Actual results

The keyboard covers

Uploading 171_1702522792.mp4…

 the input box

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/4360916/9d23601d-795f-4dda-8af0-bd3244ba7a54

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
`[✓] Flutter (Channel stable, 3.13.1, on macOS 13.5.1 22G90 darwin-x64, locale zh-Hans-CN)
• Flutter version 3.13.1 on channel stable at /Users/gaotaiwen/Desktop/flutter-sdk/flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision https://github.com/flutter/flutter/commit/e1e47221e86272429674bec4f1bd36acc4fc7b77 (4 months ago), 2023-08-22 21:43:18 -0700
• Engine revision b20183e040
• Dart version 3.1.0
• DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
• Android SDK at /Users/gaotaiwen/Library/Android/sdk
• Platform android-34, build-tools 34.0.0
• ANDROID_HOME = /Users/gaotaiwen/Library/Android/sdk
• Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Build 15A507
• CocoaPods version 1.12.1

[✓] Chrome - develop for the web
• Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Community Edition (version 2022.3)
• IntelliJ at /Applications/IntelliJ IDEA CE.app
• Flutter plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.85.0)
• VS Code at /Users/gaotaiwen/Desktop/Visual Studio Code.app/Contents
• Flutter extension version 3.78.0

[✓] Connected device (4 available)
• EVR AL00 (mobile) • LKN5T18B06003488 • android-arm64 • Android 10 (API 29)
• sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64 • Android 12 (API 32) (emulator)
• macOS (desktop) • macos • darwin-x64 • macOS 13.5.1 22G90 darwin-x64
• Chrome (web) • chrome • web-javascript • Google Chrome 120.0.6099.109
! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
The device must be opted into Developer Mode to connect wirelessly. (code -27)
```

</details>

**Comment by dam-ease** [comment]
Hi @steven-gao.
Thanks for filing this.

> download the latest demo

Which demo are you referring to here?

> Uploading 171_1702522792.mp4…

I see you attempted uploading a video here, could you help with it?
Also, kindly fill/include all the information needed in the template including your output of `flutter doctor -v`

**Comment by steven-gao** [comment]
> Hi @steven-gao. Thanks for filing this.
> 
> > download the latest demo
> 
> Which demo are you referring to here?
> 
> > Uploading 171_1702522792.mp4…
> 
> I see you attempted uploading a video here, could you help with it? Also, kindly fill/include all the information needed in the template including your output of `flutter doctor -v`

the demo path is : /packages-main/packages/webview_flutter/webview_flutter/example.
the output of flutter doctor -v 
`[✓] Flutter (Channel stable, 3.13.1, on macOS 13.5.1 22G90 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.13.1 on channel stable at /Users/gaotaiwen/Desktop/flutter-sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e1e47221e8 (4 months ago), 2023-08-22 21:43:18 -0700
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/gaotaiwen/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/gaotaiwen/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Community Edition (version 2022.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.85.0)
    • VS Code at /Users/gaotaiwen/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (4 available)
    • EVR AL00 (mobile)            • LKN5T18B06003488 • android-arm64  • Android 10 (API 29)
    • sdk gphone64 x86 64 (mobile) • emulator-5554    • android-x64    • Android 12 (API 32) (emulator)
    • macOS (desktop)              • macos            • darwin-x64     • macOS 13.5.1 22G90 darwin-x64
    • Chrome (web)                 • chrome           • web-javascript • Google Chrome 120.0.6099.109
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

`
sorry to reply to you so late.

**Comment by steven-gao** [comment]
https://github.com/flutter/flutter/assets/4360916/9d23601d-795f-4dda-8af0-bd3244ba7a54

this is the video,a web page showed by webview_flutter 4.4.2  lib will block the input box

**Comment by dam-ease** [comment]
Thanks for your response.
Following the steps to reproduce, the URL `https://qamp.yeepay.com/boss-app-access/merchantManage/business?update=Y` returns a 404 error.

You may need to use the SingleChildScrollView to make your column scroll but I can't be sure without reproducing this issue.
Also, this seems somewhat similar to https://github.com/flutter/flutter/issues/131697 which has been fixed in the latest versions of Flutter, kindly upgrade to the latest version of Flutter to see if this issue still persists, if it does, please comment with a valid URL to enable us to reproduce on our end.

Code Sample Used: https://github.com/flutter/packages/tree/main/packages/webview_flutter/webview_flutter/example

Thank you!
