### ISSUE TITLE
Triggering .popUntil() in a Dialog pops then waits 1 second before continuing pop

### ISSUE THREAD

**Issue by norbertje** [flutter/flutter#140279]
### Steps to reproduce

1. Run the given code sample.
2. Click on 'To screen 2'.
3. Click on 'Open dialog'
4. Click on 'Popuntil' 

.popUntil is set to popUntil((route) => route.isFirst)

Additional info: 
- I set the transitionDuration to Duration.zero but it has no effect.
- Triggering Navigator.pop twice triggers the same behaviour
- Triggering Navigator.pop then Navigator.push does not reproduce this kind of issue
- Triggering Navigator.push within Dialog, then triggering Navigator.popUntil from the new screen does not recreate the issue (despite having a Dialog in the Navigator between the first and current screen)

### Expected results

Should pop to Screen 1 without stopping by Screen 2 for a second. 

### Actual results

Screen 2 without dialog is displayed for a second, then proceeds to first screen. I spent quite a time but can't figure out the reason of this behaviour.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Screen1(),
    );
  }
}

class Screen1 extends StatelessWidget {
  const Screen1({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Text('Screen 1'),
          FilledButton(
              onPressed: () {
                Navigator.of(context).push(
                  PageRouteBuilder(
                    pageBuilder: (context, animation, secondaryAnimation) =>
                        Screen2(),
                    transitionsBuilder:
                        (context, animation, secondaryAnimation, child) {
                      return child;
                    },
                  ),
                );
              },
              child: Text('To screen 2'))
        ],
      ),
    );
  }
}

class Screen2 extends StatelessWidget {
  const Screen2({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Text(
            'Screen 2',
          ),
          FilledButton(
              onPressed: () {
                showGeneralDialog<void>(
                  context: context,
                  transitionDuration: Duration.zero,
                  pageBuilder: (BuildContext context, anim, anim2) {
                    return AlertDialog(
                      actions: [
                        FilledButton(
                          child: Text('Popuntil'),
                          onPressed: () {
                            Navigator.of(context)
                                .popUntil((route) => route.isFirst);
                          },
                        ),
                      ],
                    );
                  },
                );
              },
              child: Text('Open dialog'))
        ],
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @norbertje
Can you take a look at https://stackoverflow.com/questions/69454634/how-to-pop-2-screen-at-once-in-flutter and check if it helps in your case or not ?

**Comment by norbertje** [comment]
Yes, I tried that too. Changing the method of how to pop the screen (ex.: Navigator.pop() x2, popUntil() .isFirst, or popUntil() route.settings.name ==) does not change the behaviour. The issue still exist.

**Comment by darshankawar** [comment]
Thanks for the update. I think your issue is similar to https://github.com/flutter/flutter/issues/59990, so please follow-up in it for further updates. Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.

**Comment by norbertje** [comment]
I wouldn't say it's the same issue. I couldn't figure out deep enough if the core of the problem is the same. The issue I experience, triggered solely by dialogs, and setting `transationDuration` to `Duration.zero` (aka. should have no animation), still triggers the issue.
