### ISSUE TITLE
`sorted` function from `package:collection/collection.dart` package  does not work correcly in Flutter app. Surprisingly is works ok when used purerly in simple dart code.

### ISSUE THREAD

**Issue by Petr26** [flutter/flutter#140219]
### Steps to reproduce

Iam trying to simply sort an array of currency strings with few inserted in the front, but in Flutter app, it fails to do so.

Here is the link to dartpad where you can see and reproduce the bug: 
https://dartpad.dev/?id=71ed46339c733bf45b26b3a2ac7d2f4d

Suprisingly is works ok when used purerly in dart: 
https://dartpad.dev/?id=386b5b5a6cdee7298a8be3fb955d7af2

It is surprising because both Dartpad examples uses same Dart version. 

### Expected results

The array should be sorted alphabetially with `[EUR, CZK, USD]` inserted in the front of the array.

### Actual results

The array is not sorted. 

### Code sample

Code sample is in [Dartpad](https://dartpad.dev/?id=71ed46339c733bf45b26b3a2ac7d2f4d)

### Screenshots or Video

<img width="1800" alt="image" src="https://github.com/flutter/flutter/assets/11981022/a246ceb8-604e-4091-a398-162ba0bc8f74">

### Flutter Doctor output

Using dartpad as an code sample

**Comment by moffatman** [comment]
It doesn't even work for me in dart mode. It must depend on initial random seed or something. Your sort function has a bug, it should return 0 if both strings are in the set you want to insert at the front. It also should also look at `b` and return 1 if the special values are there too.

**Comment by Petr26** [comment]
To me it works ok:
<img width="1800" alt="image" src="https://github.com/flutter/flutter/assets/11981022/ec5ed09c-9c82-4f64-8519-feeae8517121">

I dont understand the thing with the seed? What do you mean by that?

And by the definition of the `sorted` function it should return -1 right to be on the top, or not? I mean I tried a lot of versions but it just does not work.

**Comment by moffatman** [comment]
No, -1 does not mean go to the top, it just means specifically `a` comes before `b`, here's my function which works:

```dart
final c = xxxxx.sorted((a,b) {
  final aIsSpecial = a == 'EUR' || a == 'USD' || a == 'CZK';
  final bIsSpecial = b == 'EUR' || b == 'USD' || b == 'CZK';
  if (aIsSpecial == bIsSpecial) {
    return a.compareTo(b);
  }
  else if (aIsSpecial) {
    return -1;
  }
  else {
    // bIsSpecial
    return 1;
  }
});
```

**Comment by Petr26** [comment]
Ah I see. I got confused when in dart it was sorted correctly (at least it works to me). 

Thank you for explanation and working example.

**Comment by moffatman** [comment]
Great np, will close it
