### ISSUE TITLE
[Video_player] Webm file is not playing on safari mobile browser

### ISSUE THREAD

**Issue by adar2378** [flutter/flutter#140238]
### Steps to reproduce

Just use the widget with any webm file link. 

Flutter 3.16.2
video_player: 2.8.1
```
final controller _controller = VideoPlayerController.networkUrl(
            Uri.parse("https://dl6.webmfiles.org/big-buck-bunny_trailer.webm"),
          );
VideoPlayer(_controller);
```

### Expected results

It should play webm video

### Actual results
```
Throwing this error
PlatformException(MEDIA_ERR_SRC_NOT_SUPPORTED, No further diagnostic information can be determined or provided., The video has been found to be unsuitable (missing or in a format not supported by your browser)., null)
```

### Code sample

<details open><summary>Code sample</summary>

```dart
final controller _controller = VideoPlayerController.networkUrl(
            Uri.parse("https://dl6.webmfiles.org/big-buck-bunny_trailer.webm"),
          );
VideoPlayer(_controller);
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by stuartmorgan** [comment]
This is not within the control of the plugin; see https://pub.dev/packages/video_player_web#supported-formats

WebM support in `<video>` for Safari on iOS is something you'd need to file a request with Apple for.
