### ISSUE TITLE
Glitch with SingleChildScrollView after closing keyboard

### ISSUE THREAD

**Issue by grobarko** [flutter/flutter#140278]
### Steps to reproduce

1. Execute `flutter run` on the code sample
2. Tap on the TextField, wait for the keyboard to open.
3. Scroll to the bottom of the page with the keyboard open.
4. Tap on the "done" keyboard button to close the keyboard
When the keyboard is closed the page will automatically scroll to the top causing a glitch if trying to scroll later (see the video example)

It's important to note that the "content height" should be less than one full screen, but more than half a screen. 
This means that the content will scroll when the keyboard is open, but it is not big enough for a scroll when the keyboard is closed.

### Expected results

Screen should not be scrollable. The SingleChildScrollView's height should still be the full screen's height after the keyboard is closed.

### Actual results

Screen is scrollable. Same issue as https://github.com/flutter/flutter/issues/121458

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        useMaterial3: true,
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: SafeArea(
          child: SingleChildScrollView(
            child: Column(
              children: [
                const Text('SCROLL BUG EXAMPLE'),
                TextFormField(
                  decoration: const InputDecoration(hintText: 'Input test'),
                ),
                Container(
                  color: Colors.black,
                  height: 600,
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/12982562/ecfc8cd6-729a-4e7b-bac0-11a733c3820c

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @grobarko 
I tried the code sample using latest master running on pixel 6 emulator but wasn't able to replicate the reported behavior.


https://github.com/flutter/flutter/assets/67046386/2f49b3f0-6012-4001-b8ea-05c700047835

Can you provide your flutter version, device and OS details on which the behavior occurs ?

**Comment by sharabiddin** [comment]
@darshankawar Tested on iOS 17.2 (iPhone 15 Pro Max). I wasn't able to replicate the reported behavior either.

**Comment by PollyGlot** [comment]
I've got this same problem using the code from this issue : https://github.com/flutter/flutter/issues/141376

It happends if I update code using the Hot Reload mode while the keyboard is open. 

<details open><summary>Doctor output</summary>

```console
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.6, on macOS 13.6.3 22G436 darwin-x64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.85.1)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>
