### ISSUE TITLE
Critical Issue Report: Plugin Integration Challenges on iPhone 14 Pro with iOS 17 SDK

### ISSUE THREAD

**Issue by LumiProj** [flutter/flutter#140275]
### Steps to reproduce

1. Install the app on an iPhone 14 Pro with iOS 17 SDK.
2. Navigate to the meeting initiation process using the https://pub.dev/packages/jitsi_meet_flutter_sdk/versions plugin.
3. Observe the "Unfortunately, something went wrong" error on the first attempt.
4. Attempt to use the "Rejoin" option.
5. Notice that the application becomes unresponsive, requiring a reboot.
6. On the second attempt, the meeting can be successfully initiated.

### Expected results

Jitsi plugin should work smoothly even on first attempt.

### Actual results

Upon initiating a meeting, the app fails to run on the first attempt, presenting an error message stating, "Unfortunately, something went wrong." Subsequently, attempting to use the "Rejoin" option does not address the issue; instead, the application becomes unresponsive, necessitating a reboot. It is only on the second attempt that I am able to successfully commence a meeting.

For your convenience, I have attached a video illustrating the problem on the device. I trust that this visual representation will offer valuable insights for resolving the issue, and I appreciate your prompt attention to this matter.

### Code sample

<details open><summary>Code sample</summary>

```dart
[[Paste your code here]](https://pub.dev/packages/jitsi_meet_flutter_sdk/example)
```

</details>

### Screenshots or Video

<details open>
<summary>I have attached a video illustrating the problem on the iPhone 14 Pro. The video provides a visual representation of the issue and may offer valuable insights for resolving the problem.</summary>

https://github.com/flutter/flutter/assets/59764810/fcf50326-ca00-4cb1-95d7-c3f2362dbec9

 

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>
After a thorough evaluation of various pub.dev plugins for jitsi, I have encountered challenges with each implementation. This raises the possibility of an underlying issue within the Flutter framework. I recommend further investigation and resolution to ensure the seamless integration and performance of plugins within the Flutter ecosystem.

**Comment by jwinarske** [comment]
@LumiProj you need to raise this issue with the plug-in developers
https://github.com/jitsi/jitsi-meet-flutter-sdk/issues

**Comment by LumiProj** [comment]
Upon careful examination, I have conducted an inquiry into the reported issue. It has come to my attention that a notable number of users are currently experiencing similar challenges. This phenomenon extends beyond a specific plugin and encompasses all plugins supporting Jitsi. Feedback from users indicates a consensus that the root cause of these issues may be traced back to Flutter, suggesting a potential overarching concern within the framework. Further investigation and resolution are advised to ensure the robust functionality of Jitsi-supported plugins within the Flutter environment.

**Comment by jwinarske** [comment]
@LumiProj can you provide any technical information that is related to the flutter SDK?

**Comment by stuartmorgan** [comment]
Issues with third-party packages need to be reported to the developers of the packages; closing as this does not describe an issue in Flutter.

> After a thorough evaluation of various pub.dev plugins for jitsi, I have encountered challenges with each implementation. This raises the possibility of an underlying issue within the Flutter framework.

A more likely explanation for an issue that is specific to the functionality of a specific third-party SDK, and which happens in every plugin wrapping a that SDK, is an issue with the SDK. That would need to be investigated as a first step.

> Feedback from users indicates a consensus that the root cause of these issues may be traced back to Flutter

If someone investigates the issue from the plugin side and is able to determine that a Flutter bug is involved, they should certainly file an issue with details of that bug, as that would be actionable for the Flutter team.
