### ISSUE TITLE
TapRegion has no clear way to differentiate between different gestures

### ISSUE THREAD

**Issue by Hannnes1** [flutter/flutter#140271]
### Use case

By default, the on screen keyboard is dismissed by non-mobile touch events, such as a click.
It is quite common to want similar behavior on mobile. That can be done by calling `unfocus` on the text fields `FocusNode` inside the `onTapCallback`. That does however mean that both taps and scrolls are handled the same, since `TapRegion` uses `PointerDownEvent` as a trigger for `onTapOutside`. (Contradictory to what the name might suggest. Compare with `onTap` and `onTapDown` in `GestureDetector`)

Having the ability to differentiate between scroll and tap would give developers the ability to close the text field on a tap, but keep it open when scrolling.

Attached below is a video of the Google Home app on Android, showing the behavior that I'm looking for.

https://github.com/flutter/flutter/assets/47989573/77d26c16-5359-44ae-8002-8e30ff88f8e8

### Proposal

`TapRegion`, should have more parameters to differentiate between different gestures, similar to `GestureDetector`. This would be a breaking change, but `onTapOutside` should behave like `onTap` of `GestureDetector`, and a new parameter with the name `onTapDownOutside` should be added that has the current behaviour. Other gestures should be handled by other parameters.

**Comment by darshankawar** [comment]
Thanks for the report @Hannnes1 


> `onTapOutside` should behave like `onTap` of `GestureDetector`

Are you seeing the current behavior using `onTapOutside` that `down` event is not reported, but only `up` event is ?
If so, are you proposing that both events should be triggered as applicable ?

**Comment by Hannnes1** [comment]
@darshankawar
The current behaviour of `onTapOutside` is that only the `down` event is reported (This is the same behavior as `GestureDetector.onTapDown`).

Compare that to `GestureDetector.onTap`, which is only triggered when a tap wins in the gesture arena.

My proposal is that `TapRegion.onTapOutside` should behave the same way as `GestureDetector.onTap`.

**Comment by Hannnes1** [comment]
> Don't you think we need a `void Function(PointerUpEvent event);` or a `void function( )` to achieve what we want?
> 
> Because when I compared TapRegion with GestureDetector, GestureDetector uses :
> 
> ```
> typedef GestureTapDownCallback = void Function(TapDownDetails details);
> typedef GestureTapUpCallback = void Function(TapUpDetails details);
> typedef GestureTapCallback = void Function();
> ```

Yes, all three of those will probably be required @Utkarsh4517, Especially the last one, to correctly identify a tap.

Additional callbacks, such as `onPanStart`, `onPanUpdate` etc. might be needed as well. But that might be outside the intended scope of `TapRegion`. Someone with more knowledge about this than me should probably weigh in.

**Comment by Hannnes1** [comment]
> Just found out that we can achieve the desired output, If we wrap our entire Scaffold with the GestureDetector widget and pass `FocusScope.of(context).unfocus();` inside `onTap` of `GestureDetector`.

Yes, that kind of works. There are some differences in the behavior of this solution and `TapRegion` though. For example `TapRegion.groupId` that can be used to group `TapRegion`s together.

> So what we can do is to rename the current `TapRegion.onTapOutside` to `TapRegion.onTapDownOutside` and Create a new `TapRegion.onTapOutside` which behaves the same as `GestureDetector.onTap`. also the `onTap` function takes no arguments, so `PointerUpEvent` is not required. my bad :(

Yes, that's what I'm thinking. Like I said, there are some differences between `GestureDetector` and `TapRegion`, but that shouldn't affect when a `PointerDownEvent` turns into a tap.

**Comment by Utkarsh4517** [comment]
Hey @Hannnes1 @darshankawar I have a doubt. Do the new `TapRegion.onTapOutside` will be a `void Function()` or a `void Function(PointerDownEvent event)` ?

**Comment by Hannnes1** [comment]
> Hey @Hannnes1 @darshankawar I have a doubt. Do the new `TapRegion.onTapOutside` will be a `void Function()` or a `void Function(PointerDownEvent event)` ?

My interpretation is that it would have to be `void Function()`, since the `PointerDownEvent` might not have the correct information when the tap wins in the arena. (The pointer might have moved slightly, for example)

**Comment by Hannnes1** [comment]
@Utkarsh4517 Did you make any more progress on this? I had a look at it myself, but it seems to be more complicated than I anticipated. Primarily because I would like to avoid a breaking change.

**Comment by jaybe78** [comment]
That issue is quite annoying and I experience the same when for example I push/pop route clicking on a close icon, and the new screen showing up contains a button in the same region, therefore it triggers the onTap of that button on that new screen...

Basically any buttons within the same region on different routes will get their onTapOutside function called.
