### ISSUE TITLE
Let a user skip the root warning in bin/flutter - podman

### ISSUE THREAD

**Issue by RodrigoDornelles** [flutter/flutter#140330]
There is a check for the file `/.dockerenv` to see if it is running in a container in order to suppress the warning, but in **podman** it is found in `/run/.containerenv`

 * <https://github.com/flutter/flutter/issues/10529>
 * <https://github.com/flutter/flutter/pull/10535>
 
 ### extra

 i put this in my `entrypoint.sh` and works fine!
 
 ```
 if [[ -f /run/.containerenv ]] && ! [[ -f /.dockerenv ]]; then
    ln -s /run/.containerenv /.dockerenv 
fi
```

**Comment by danagbemava-nc** [comment]
The line that checks this can be found in

https://github.com/flutter/flutter/blob/2ed0df8405a2d5c7d369a4ccdaa002475e03b138/bin/internal/shared.sh#L213-L219

Labeling as a proposal

**Comment by christopherfujino** [comment]
What exactly is the proposal? Also, it seems like an easier solution here in your entrypoint.sh would just be `touch /.dockerenv`.

Given this logic lives in bash land, I'm not sure we want to keep extending this logic to check for every possible config file or env variable. Should we instead update the warning to say its ok to run as root if you're on CI?

**Comment by RodrigoDornelles** [comment]
> What exactly is the proposal? Also, it seems like an easier solution here in your entrypoint.sh would just be `touch /.dockerenv`.
> 
> Given this logic lives in bash land, I'm not sure we want to keep extending this logic to check for every possible config file or env variable. Should we instead update the warning to say its ok to run as root if you're on CI?

Using only touch may cause bad behavior, as it is a file created at runtime by the docker engine. My proposal as in PR #140380 is to silence podman and kubernets just as it already exists in docker.

**Comment by christopherfujino** [comment]
> Using only touch may cause bad behavior, as it is a file created at runtime by the docker engine.

Can you explain more what bad behavior touching the file may cause? Are you worried podman will do the wrong thing if it detects a `/.dockerenv` file, or the state of the container environment will be corrupted, or something else?

> My proposal as in PR #140380 is to silence podman and kubernets just as it already exists in docker.

I understand your proposal. In https://github.com/flutter/flutter/issues/140330#issuecomment-1863250880, I describe my reservations that would have to be addressed before I approve a pull request.

**Comment by RodrigoDornelles** [comment]
@christopherfujino 

> > Using only touch may cause bad behavior, as it is a file created at runtime by the docker engine.
> 
> Can you explain more what bad behavior touching the file may cause? Are you worried podman will do the wrong thing if it detects a `/.dockerenv` file, or the state of the container environment will be corrupted, or something else?

the file `/.dockerenv` must be created dynamically by docker engine in runtime that's container's environment vars, another programs mayable require the content of this file.

so putting a `touch /.dockerenv` may not be a solution.

but that's a matter for whoever is building the container image. That's show the `ln -s /run/.containerenv /.dockerenv` is  paleative solution to specifically serve my container image.

> > My proposal as in PR #140380 is to silence podman and kubernets just as it already exists in docker.
> 
> I understand what you're proposing, it's just not clear to me that that is the best change to make. In [#140330 (comment)](https://github.com/flutter/flutter/issues/140330#issuecomment-1863250880), I describe my reservations that would have to be addressed before I approve a pull request.


I also don't think it's a good approach to just increase conditions, it works, but a different approach or defining a single environment variable for this would be better.

**Comment by christopherfujino** [comment]
> the file `/.dockerenv` must be created dynamically by docker engine in runtime that's container's environment vars, another programs mayable require the content of this file.
> 
> so putting a `touch /.dockerenv` may not be a solution.

I'm not sure exactly what you're saying here, but if you're worried that `touch` will affect the behavior of other applications if the file already exists, `touch` will not change the contents of a file that exists, only update it's last modified stamp.

> some like `flutter config --disable-warn-root` songs great!

This would not work as this warning is printed from bash, before we even get to the dart code that controls the `flutter config` subsystem.

**Comment by christopherfujino** [comment]
I'm sorry but I don't think we would implement this, even if someone put out a PR for it, due to the cost of maintaining more bash logic and the fact that this can easily be worked around with `touch /.dockerenv` in a Dockerfile.

**Comment by RodrigoDornelles** [comment]
> I'm sorry but I don't think we would implement this, even if someone put out a PR for it, due to the cost of maintaining more bash logic and the fact that this can easily be worked around with `touch /.dockerenv` in a Dockerfile.

**I have already solved my specific problem**, the point is that using `touch` is a bad practice and paleative , as it will cause a duplication of truth sources. There may be another file with the real content of environments being ignored.

Maybe then instead of `$CI`, `$BOT` and `$CONTINUOUS_INTEGRATION` it could be a flutter-exclusive environment variable `$FLUTTER_IGNORE_ROOT_WARN` or similar, and give greater control to the user than maintaining bash

@christopherfujino @danagbemava-nc
