### ISSUE TITLE
Improve API docs layout template making side columns collapsable

### ISSUE THREAD

**Issue by alefwd** [flutter/flutter#140385]
### Use case

When reading the Flutter API docs, for instance this [page](https://api.flutter.dev/flutter/widgets/PositionedTransition-class.html), the primary content takes the centre of the page, while both the sides are taken by a layout with 2 columns, one with the classes on the left, and one with the properties on the right.
This layout makes so that the code snippet is practically unreadable on most of the screens.
Also, the content on the right column is redundant as it's contained also in the bottom half of the page as well.

### Proposal

The proposal is to make the 2 columns collapsable (at least), so that they can collapse to the sides, leaving the whole space for the centre of the page (primary content)

See pic:
<img width="1509" alt="Screenshot 2023-12-19 at 11 35 58" src="https://github.com/flutter/flutter/assets/120181837/4cad932c-5461-4593-ba35-54d40e422180">

**Comment by Captured-Heart** [comment]
This is ver Valid, I hope to see this accepted for better readability

**Comment by rydmike** [comment]
Or maybe just use a screen with more real-estate? I mean those sidebars hardly take up any space below! 😉 It's all relative! 😄

![Screenshot 2023-12-20 at 03 11 01](https://github.com/flutter/flutter/assets/39990307/fc96594d-6fa1-4e5f-9c13-ccf1f168bd8e)

Kidding aside, I do agree, user controllable collapsible sidebars are alway welcome. I implement them too and recommend them e.g. on Flutter desktop UIs. Would certainly be useful here too when you are on a tiny screen and reading docs. Although I do tend to stick to at least dual 32" 4k screens, both used at native res.

**Comment by amrgetment** [comment]
I think it should be made by Flutter web too :)

**Comment by gregslusarski** [comment]
Or add "open in new tab" button next to "copy code", so code example opens in a new tab, and takes entire screen

**Comment by dickermoshe** [comment]
Scrolling down is also a nuisance.  
If your cursor is anywhere in the red the page wont scroll. 
<img width="641" alt="image" src="https://github.com/flutter/flutter/assets/75931499/f5aca52e-504c-450e-bd5f-00f5adbe715d">

The code examples should be collapsable.

**Comment by goderbauer** [comment]
This is probably a discussion for https://github.com/dart-lang/dartdoc.

**Comment by goderbauer** [comment]
I am going to close this one as per my previous comment.
