### ISSUE TITLE
Slider assertion slider.dart:734:12 value >= 0.0 && value <= 1.0

### ISSUE THREAD

**Issue by Mmisiek** [flutter/flutter#140329]
### Steps to reproduce

I have a code using Slider, and it was working very well until recently when the Slider class started raising assert errors. Based on the code, if divisions are added to Slider, the values can be only in the range 0..1. This is not described in the documentation, nor was it required before. I think it is a bug, as any value can be quantized by divisions. 

I tracked down the fact that the min/max/value inside the Slider class is NULL, which they should not be as they are not nullable. They are also passed to class with actual values.

What possibly could happen? 

<details open>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.13.8, on macOS 13.5 22G74 darwin-arm64, locale en-US)
    • Flutter version 3.13.8 on channel stable at /Users/michal/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6c4930c4ac (9 weeks ago), 2023-10-18 10:57:55 -0500
    • Engine revision 767d8c75e8
    • Dart version 3.1.4
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/michal/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (3 available)
    • iPhone 15 Pro (mobile) • 0D1712F2-4847-41C4-925D-B85441090B69 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.5 22G74 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 120.0.6099.109

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
</details>

### Expected results

I expect slider to work and jump between discrete values.

### Actual results

The exception is thrown value >= 0.0 && value <= 1.0

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @Mmisiek, it appears you are using an older version of the flutter framework. Kindly upgrade to the latest stable version(3.16.4) to see if you still experience this issue. 

If you do, please provide the updated output of `flutter doctor -v` along with a complete runnable reproducible code sample so that we can investigate this issue. 

Please also provide the detailed error message from the framework. 

Thank you
