### ISSUE TITLE
[Windows] The result of subtracting two dates in Windows is different from the result calculated on other platforms。

### ISSUE THREAD

**Issue by desert1210** [flutter/flutter#140312]
### Steps to reproduce

Running code separately on Android, Web, and Windows

### Expected results

Get the same result

### Actual results

android: 3528748800
windows: 3529065600

### Code sample

<details open><summary>Code sample</summary>

```dart
final a = DateTime.now();
final b = DateTime(1912, 2, 18);
days = a.difference(b).inDays;
developer.log('gzdate diff: $days');
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
@desert1210 
Since `DateTime` is a dart core method, this issue probably need to be reported in dedicated repo: https://github.com/dart-lang/sdk/issues
Closing from here.
