### ISSUE TITLE
Material date picker does not work in input entry mode when textScaleFactor is less than 1

### ISSUE THREAD

**Issue by tchavet** [flutter/flutter#140387]
### Steps to reproduce

1. Have a textScaleFactor set to something less than 1, either by having the text scale to the minimum in the phone settings or setting it manually with a MediaQuery around the MaterialApp
2. Call showDatePicker with initialEntryMode set to DatePickerEntryMode.input or manually select it in the upper right corner of the dialog

What happens is that in the file date_picker.dart of material, line 662 there is this line:
`final double textScaleFactor = MediaQuery.textScalerOf(context).clamp(maxScaleFactor: _kMaxTextScaleFactor).textScaleFactor;`
that prevents the textScaleFactor to be too high but it should also have `minScaleFactor: 1` because this value is used to calculate the size of the dialog (line 663) so on line 690 the variable `isFullyPortrait` is false, and the input field is not displayed.

### Expected results

The date picker dialog displays correctly

### Actual results

The date picker dialog opens without the text input field, and when switching to the calendar entry mode it throws an error because it is looking for the text field to get the value, but it does not exist.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    const MediaQuery(
      data: MediaQueryData(
        textScaleFactor: 0.9,
      ),
      child: MaterialApp(
        home: DatePickerApp(),
      ),
    )
  );
}

class DatePickerApp extends StatelessWidget {
  const DatePickerApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            showDatePicker(
              context: context,
              initialDate: DateTime.now(),
              firstDate: DateTime(1900),
              lastDate: DateTime.now(),
              initialEntryMode: DatePickerEntryMode.input,
            );
          },
          child: const Text("Show date picker"),
        )
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![Screenshot_2023-12-19-16-00-46-48_19d946f9c86037d18a7f199b8689043d](https://github.com/flutter/flutter/assets/9250878/c76f97bb-ec80-40a8-a56b-e99b38834159)

</details>

### Logs

<details open><summary>Logs</summary>

```console

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.3, on Ubuntu 22.10 5.19.0-46-generic, locale
    en_US.UTF-8)
    • Flutter version 3.16.3 on channel stable at
      /home/deuse/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0366e0a3f (13 days ago), 2023-12-05 19:46:39 -0800
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/deuse/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /snap/android-studio/140/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2023.1)
    • Android Studio at /snap/android-studio/140
    • Flutter plugin version 77.1.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Connected device (3 available)
    • DN2103 (mobile) • IRGEIBMFVSSG7T49 • android-arm64  • Android 13 (API 33)
    • Linux (desktop) • linux            • linux-x64      • Ubuntu 22.10 5.19.0-46-generic
    • Chrome (web)    • chrome           • web-javascript • Google Chrome 114.0.5735.133

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
Hi @tchavet 
This is fixed in https://github.com/flutter/flutter/pull/139236. If possible, could you please upgrade to the latest` master` channel and test it?
