### ISSUE TITLE
`Mac_android entrypoint_dart_registrant` CI bot getting immediate failures

### ISSUE THREAD

**Issue by eyebrowsoffire** [flutter/flutter#140344]
### Type of Request

bug

### Infrastructure Environment

LUCI

### What is happening?

A string of recent infra failures on the `Mac_android entrypoint_dart_registrant` task:
https://ci.chromium.org/ui/p/flutter/builders/try/Mac_android%20entrypoint_dart_registrant

One such example: 
https://ci.chromium.org/ui/p/flutter/builders/try/Mac_android%20entrypoint_dart_registrant/20782/overview

Apparently there are no bots that meet the specified dimensions. Either some pool configuration has gone wrong or .ci.yaml is misconfigured.

**Comment by keyonghan** [comment]
@kentnguyen99 Could you help check any issues with the phone on mac-17? Rebooting doesn't help and the bot cannot find the device.

**Comment by kentnguyen99** [comment]
I'm in processing to replace the mobile phone device due to battery on old phone is going bad.  It should be fine now.
Can you check again?

**Comment by yusuf-goog** [comment]
A moto G4 device has been moved over from staging to mac-17 to unblock this issue. We will work to move these builds off the moto G4 requirement, as those devices are coming end of life in the lab.
