### ISSUE TITLE
Add the ability to set route settings on the menu opened by PopupMenuButton

### ISSUE THREAD

**Issue by sbatezat** [flutter/flutter#140372]
### Use case

I'm using an analytics tool to see when user go from one page to another, so I need to name the pages.
Currently, the "page" opened by PopupMenuButton cannot be named as routeSettings is not set.

### Proposal

Add routeSettings parameter on PopupMenuButton

**Comment by dam-ease** [comment]
Thanks for filing this @sbatezat.
Not sure I totally got this, what would you intend to pass though the route settings parameter and how are you currently implementing with the `PopupMenuButton`?

**Comment by sbatezat** [comment]
> Thanks for filing this @sbatezat. Not sure I totally got this, what would you intend to pass though the route settings parameter and how are you currently implementing with the `PopupMenuButton`?

The usecase is exactly the same than the showDialog function. 

```
showDialog(
      context: context,
      builder: (BuildContext context) => dialog,
      routeSettings: RouteSettings(name: routeDescription),
 );
```

When you open something (a page, a dialog and here a menu) you may be interested to add route settings (a name, or even more some arguments).

In my case, I've got a NavigatorObserver, and when there is a new route browsed by the user, I'm using the route name (provided by routeSettings name parameter).

I'm doing something like that to track the event on my analytics tool :

```
  @override
  void didPush(Route<dynamic> route, Route<dynamic>? previousRoute) {
    _onPageChanged(route);
  }

  @override
  void didPop(Route<dynamic> route, Route<dynamic>? previousRoute) {
    _onPageChanged(previousRoute);
  }

  @override
  void didReplace({Route<dynamic>? newRoute, Route<dynamic>? oldRoute}) {
    _onPageChanged(newRoute);
  }

  void _onPageChanged(Route<dynamic>? route) {
    final String pageName = route?.settings.name ?? "Unknown";
    logger.i("Navigating to \"$pageName\"");
    
    // Here i'm using my analytics tool (example : Google Analytics) to track pages viewed by my users
    trackViewUseCase.trackView(pageName);
  }
```

Please note this is only MY use case, but it could be useful for others purposes.

**Comment by goderbauer** [comment]
PR https://github.com/flutter/flutter/pull/140373 was written to solve this issue but unfortunately it was not completed so the PR has been closed. If anyone would like to start from that PR and apply the review comments and drive this PR to completion, you are definitely welcome to do so!
