### ISSUE TITLE
Collect metrics on mac builds when running without goma

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#140342]
### Type of Request

infra task

### Infrastructure Environment

goma, builds

### What is happening?

We need to determine the impact on build times for mac engine builders that generate artifacts, when they do not use goma.

The requirement to collect this data has been laid out in an internal document.

Additional details to follow below.

**Comment by godofredoc** [comment]
@yusuf-goog can we update this bug with the results of the validation and close?

**Comment by zanderso** [comment]
Closing as obsolete
