### ISSUE TITLE
Slow Performance on Samsung S4 using GPU : PowerVR SGX544MP3 (Initial Load Apps : 7seconds, Action Button : 2 seconds)

### ISSUE THREAD

**Issue by xnuxer88** [flutter/flutter#14035]
Hi There,

Currently I have the same problem here.

I've already build flutter apk for release, this is from sample new project flutter increment floating button. But it seem to slow. for first load apps, it takes 7 seconds. for processing increment floating button it takes 3 seconds. Just from new sample project, I'm not customize the program yet.

```
Initializing gradle... 1.6s
Resolving dependencies... 4.5s
Running 'gradlew assembleRelease'...
Skipping AOT snapshot build. Fingerprint match.
Built build\app\outputs\apk\app-release.apk (7.9MB).
```
I've installed the same installer on Samsung S7, Samsung J3, HTC One it's work fine
same as native speed.

Samsung S7 edge using GPU : Adreno 530 - G9350, Mali-T880 MP12 - G935FD, G935F, G935W8 -> works fine
HTC One using GPU : Adreno 320 -> works fine
Samsung J3 using GPU : Mali-400, Mali-T720 - USA -> works fine
Xiaomi Redmi Note 4 using GPU : Adreno 506 -> works fine
Samsung S4 using GPU : PowerVR SGX544MP3 -> slow
ASUS Zenfone 5 using GPU : PowerVR SGX544MP2 -> the slowest

Thank You.

**Comment by eseidelGoogle** [comment]
There is another report of S4-specific performance troubles: https://github.com/flutter/flutter/issues/7150

**Comment by Hixie** [comment]
Can you clarify exactly what you are measuring?

See also https://github.com/flutter/flutter/issues/14036

**Comment by jonahwilliams** [comment]
Without more information here we've been unable to make additional progress. Closing the issue as no longer actionable, and significantly out of date.
