### ISSUE TITLE
Missing path (/<some path>/Flutter/Release/<some framework>.xcframework/ios-arm64/dSYMs) from XCFramework '<some framework>.xcframework' as defined by 'DebugSymbolsPath' in its `Info.plist` file: xcodecloud issue

### ISSUE THREAD

**Issue by samarthagarwal** [flutter/flutter#140365]
### Steps to reproduce

I have a Flutter module that I use in my iOS application. As a result of the following build command, I get a number of xcframeworks organized in Debug, Profile and Release folders.

```
flutter build ios-framework
```

I then move this folders to my iOS app and it works and builds fine. The app is also live on the app store and since we have Crashlytics integrated, we get the crash reports and all works fine. Recently, we started to set up XCode Cloud and as soon as we tried to build, we ran into the following issue with all the 20-ish frameworks we have as a result of flutter build command.

```
Missing path (/...../Flutter/Release/fluttertoast.xcframework/ios-arm64/dSYMs) from XCFramework 'fluttertoast.xcframework' as defined by 'DebugSymbolsPath' in its `Info.plist` file
```

The XCode build fails as a result.

As a workaround, I removed the following code from the `info.plist` files of all the frameworks and the build succeeded.

```
<key>DebugSymbolsPath</key>
<string>dSYMs</string>
```
I am afraid that this will have obvious consequences. The path defined could be wrong since the folder structure is slightly different. See the screenshot showing that the dSYMs folder is nested inside ios-arm64 folder

<img width="320" alt="Screenshot 2023-12-19 at 12 12 43 PM" src="https://github.com/flutter/flutter/assets/3234592/cb386b3c-c539-47db-8823-5b3bfb2cbddf">

Fixing or removing the path manually every time is not feasible. 

Is there a way to fix this using the flutter CLI or is this a bug in the CLI itself?

### Expected results

The XCode build should succeed as expected.

### Actual results

The XCode build fails with an error message for all the frameworks. The error message complains about no `dSYMs` folder as defined by frameworks `info.plist` file.

### Code sample

No code sample required.

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img width="320" alt="Screenshot 2023-12-19 at 12 12 43 PM" src="https://github.com/flutter/flutter/assets/3234592/e848e12d-b63d-41ea-be59-9d65867e49bf">

</details>

### Logs

<details open><summary>Logs</summary>

```console
Missing path (/...../Flutter/Release/fluttertoast.xcframework/ios-arm64/dSYMs) from XCFramework 'fluttertoast.xcframework' as defined by 'DebugSymbolsPath' in its `Info.plist` file
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.13.6, on macOS 13.6.2 22G320 darwin-arm64, locale
    en-IN)
    ! Warning: `dart` on your path resolves to
      /opt/homebrew/Cellar/dart/3.1.2/libexec/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/sagarwal1/flutter. Consider adding
      /Users/sagarwal1/flutter/bin to the front of your path.
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.84.2)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 2 categories
```

</details>

**Comment by dam-ease** [comment]
Thanks for filing this @samarthagarwal.
Can you check if the path does really exist?
Also, I see you are on an older version of Flutter, can you upgrade to the latest versions to see if this issue still exists there?
If it does, for this issue to be workable, we will need a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Or a simple repo we could run to reproduce this issue.

**Comment by samarthagarwal** [comment]
The folder `dSYMs` does exist but if the path to the folder in the `info.plist` is relative to itself, then I think it should be something like this.

```
<key>DebugSymbolsPath</key>
<string>ios-arm64/dSYMs</string>
```

I can try again to see if changing the path this way fixes the issue. Is there a way in the flutter CLI to configure this?

**Comment by samarthagarwal** [comment]
I tried changing the value of the `DebugSymbolsPath` key in all `info.plist` files but that did not help. Here is what I tried.
```
<key>DebugSymbolsPath</key>
<string>ios-arm64/dSYMs</string>
```
But this resulted `.../ios-arm64/ios-arm64/dSYMs` in the final path which is obviously wrong.

Therefore, I found that the final path actually as reported in the error logs in correct, but for some reason, the `dSYMs` folder is not accessible when building with XCode Cloud. Now I am not sure how to proceed.

Here is a sample `info.plist` for your reference just in case you want to have a look here. This is for the `App.xcframework` framework.
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>AvailableLibraries</key>
	<array>
		<dict>
			<key>BinaryPath</key>
			<string>App.framework/App</string>
			<key>DebugSymbolsPath</key>
			<string>dSYMs</string>
			<key>LibraryIdentifier</key>
			<string>ios-arm64</string>
			<key>LibraryPath</key>
			<string>App.framework</string>
			<key>SupportedArchitectures</key>
			<array>
				<string>arm64</string>
			</array>
			<key>SupportedPlatform</key>
			<string>ios</string>
		</dict>
		<dict>
			<key>BinaryPath</key>
			<string>App.framework/App</string>
			<key>LibraryIdentifier</key>
			<string>ios-arm64_x86_64-simulator</string>
			<key>LibraryPath</key>
			<string>App.framework</string>
			<key>SupportedArchitectures</key>
			<array>
				<string>arm64</string>
				<string>x86_64</string>
			</array>
			<key>SupportedPlatform</key>
			<string>ios</string>
			<key>SupportedPlatformVariant</key>
			<string>simulator</string>
		</dict>
	</array>
	<key>CFBundlePackageType</key>
	<string>XFWK</string>
	<key>XCFrameworkFormatVersion</key>
	<string>1.0</string>
</dict>
</plist>
```

Let me know if anyone has any thoughts.

**Comment by dam-ease** [comment]
Thanks for your response @samarthagarwal.
I think your question is best suited for support channels like StackOverflow, please ask the same there for solutions if any. Please also see [flutterhelp](https://www.reddit.com/r/flutterhelp/) for resources and ask questions like this.

If you disagree, then we would need more information such as a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Or a simple repo we could run to reproduce this issue.
