### ISSUE TITLE
[CP] Fix `UnobstructedPlatformViewTests testMultiplePlatformViewsWithOverlays` test

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#140397]
### Issue Link

https://github.com/flutter/flutter/issues/138193

### Target

stable

### PR Link

https://github.com/flutter/engine/pull/49247

### Changelog Description

Fix engine test `UnobstructedPlatformViewTests testMultiplePlatformViewsWithOverlays` by skipping unexpected events in MultiPlatformViewBackgroundForegroundScenario.

### Impacted Users

Flutter developers running Flutter Engine tests

### Impact Description

May fail flutter/engine test `Linux mac_unopt` in Flutter CI.

### Workaround

No

### Risk

low

### Test Coverage

yes

### Validation Steps

Rerun `Linux mac_unopt` with the fix.

**Comment by XilaiZhang** [comment]
@stuartmorgan could you help review this cherry-pick request? Thank you!

**Comment by jmagman** [comment]
LGTM!

**Comment by XilaiZhang** [comment]
Thanks everyone!
