### ISSUE TITLE
Missing google_app_id. Firebase Analytics disabled

### ISSUE THREAD

**Issue by mobileapp-remish** [flutter/flutter#140360]
getting Missing google_app_id. Firebase Analytics disabled this error even if i configured everything correctly i have added .json file firebase config file and init in main.dart also add id "com.google.gms...." plugin and class path dependecy and firebase bom and analytics on native android side and also analytics is enabled from firebase still getting 

Missing google_app_id. Firebase Analytics disabled

this kind of error in log.

  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.8
  firebase_analytics: ^10.7.4

plugins {
    id "com.android.application"
    id "kotlin-android"
    id "dev.flutter.flutter-gradle-plugin"
    id "com.google.gms.google-services"
}

dependencies {
    implementation(platform("com.google.firebase:firebase-bom:32.7.0"))
    implementation("com.google.firebase:firebase-analytics")
}

buildscript {
    ext.kotlin_version = '1.8.22'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.4.0'
    }
}

[My Flutter dart sdk version  ](sdk: ">=3.1.3 <4.0.0")

**Comment by danagbemava-nc** [comment]
This is not a flutter issue. 

Kindly file an issue on the flutterfire repository so that it can be properly addressed. 

Closing from here. 

Thank you
