### ISSUE TITLE
An infra error occurred while running Google testing

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#140454]
### Type of Request

bug

### Infrastructure Environment

https://github.com/flutter/flutter/pull/138240/checks?check_run_id=19804865653
https://github.com/flutter/flutter/pull/139962/checks?check_run_id=19816036217

### What is happening?

b/317130312

Google Testing check is failing and blocking PRs.

> An infra error occurred while running Google testing

With no additional details (that I can spot).  The internal bug says it's:
> error: CreateCheckRun(78e7ea87f001527c0bb4b923f70c572173cf93b1) encountered error POST https://api.github.com/repos/flutter/flutter/check-runs: 500 [].

### Steps to reproduce

I'm not sure how to reproduce, it's not every PR or commit.

### Expected results

Google Testing should run and report results.

**Comment by jmagman** [comment]
@XilaiZhang I'll assign this one to you to mirror b/317130312 since you're investigating.  🙂

**Comment by huanghui1998hhh** [comment]
+1

**Comment by XilaiZhang** [comment]
Looked at this yesterday and today but couldn't identify the root cause. will keep looking but if my tech lead @CaseyHillers have some insights that would be appreciated

**Comment by XilaiZhang** [comment]
some things to try (not guaranteed to work) are rebasing your pull request. we are still looking at finding the root cause

**Comment by drewroengoogle** [comment]
Hi @XilaiZhang, any updates that need to be shared here, or is this resolved?

**Comment by XilaiZhang** [comment]
still triaging in b/317130312

**Comment by keyonghan** [comment]
Closing as the linked bug has been fixed.
