### ISSUE TITLE
flutter based wayland compositor like qtwayland

### ISSUE THREAD

**Issue by ehjoon** [flutter/flutter#140487]
### Use case

Using Qt, we can make compositor server on embedded system. Recently I'm considering flutter new app framework to make system UI on embedded device. But, I can't find appropriate solution for compositor server like qtwayland.

Anyone knows some solution for building flutter wayland compositor server ?

I'm checking two options, but it looks performance is not good and I'm not sure wlroot is maintained.

https://github.com/roscale/zenith https://github.com/PlayPulseCom/flutter_wlroots

### Proposal

I'm wondering whether there is any official plan for supporting the wayland server feature like qtwayland.

**Comment by jwinarske** [comment]
What's the licensing on QT?

Looking at the qtwayland repo the are no protocol files short of two, which would indicate they are using standard Wayland protocols.

Wlroots is active, as is Weston.

This embedder supports Wayland and is used in Automotive Grade Linux (AGL) variety of embedded use cases involving Wayland; is actively supported:
https://github.com/toyota-connected/ivi-homescreen
