### ISSUE TITLE
https://github.com/monster555/flutter_shader_demo does not look the same on Skia and Impeller on iOS

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#140418]
See e.g. the fire heart one.

On Skia, the fire heart demo is not rendering anything at all. On Impeller, it's visually noisy in the preview and then flipped upside down on full screen.

![4B6C13C7-ADD9-4C24-8D8D-058C6F8503F8](https://github.com/flutter/flutter/assets/8620741/a6265496-35d0-46fb-a46a-69c3ff15e5b2)
![D4E34EFF-1202-4F66-85AC-AA20D16B5F31](https://github.com/flutter/flutter/assets/8620741/4cb3bedb-69f9-422e-8278-fe515394e036)

With https://github.com/flutter/engine/pull/49253 applied, Skia renders fine and Impeller has the same issues depicted here.

**Comment by jonahwilliams** [comment]
Clarification, this is happening on Metal

**Comment by dnfield** [comment]
This turned out to be caused by https://github.com/flutter/flutter/issues/141236
