### ISSUE TITLE
Integrate with username/password auto-fill

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#14047]
Was reading up on changes for Android P, and it led me to file this...

https://android-developers.googleblog.com/2017/11/getting-your-android-app-ready-for.html
https://code.tutsplus.com/articles/faster-logins-with-password-autofill-in-ios-11--cms-29096

@Hixie do you think this is the domain of the framework or plugins?

**Comment by Hixie** [comment]
The built-in text field should just support this out of the box, though we should also expose the APIs to make it possible to make custom text fields to do this.

**Comment by Hixie** [comment]
cc @HansMuller @cbracken

**Comment by orospakr** [comment]
May be a duplicate of #13015.

**Comment by cbracken** [comment]
Also noted on #13015 but we should ensure we integrate correctly with the password fill functionality on iOS 11 and the upcoming changes for iOS 12.

**Comment by AlexVincent525** [comment]
Any updates with this feature? With so many stable version have been released... 😞

**Comment by audkar** [comment]
So much time passes that auto-fill has got much more capabilities then only username/passwords. Now autofill can fill dates/lists/texts/toggles with authData/email/phone/addresses/paymentInfo/etc

**Comment by oth-libs** [comment]
any updates on this?

**Comment by tvolkert** [comment]
Closing as a duplicate of https://github.com/flutter/flutter/issues/13015.  Anyone who's following or added their thumbs-up to this issue, you'll want to do the same to https://github.com/flutter/flutter/issues/13015.
