### ISSUE TITLE
flutter.dev feature grid is blank on Firefox/Linux.

### ISSUE THREAD

**Issue by omeid** [flutter/flutter#140484]
### Steps to reproduce

1. Visit https://flutter.dev/learn with latest Firefox (120.0.1)
2. See the issue:

### Expected results

![image](https://github.com/flutter/flutter/assets/1453118/7cf2f3e3-d5fe-482c-b937-41b16ebe8006)

### Actual results

![image](https://github.com/flutter/flutter/assets/1453118/b29f3c4e-948b-4815-b4e4-fb2bae012a63)

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by dam-ease** [comment]
Hi @omeid.
Thanks for filing this.
Is this issue peculiar to Linux on this version of Firefox?
Can you try this on this version of Firefox: https://www.mozilla.org/en-US/firefox/121.0/releasenotes/
I loaded this page on macos Firefox (version 121.0) and can't reproduce this issue.

**Comment by omeid** [comment]
Hello @dam-ease,

Why trying to figure out the root cause using a different machine and firefox profile, turns out this issue is related to this Firefox extension:

https://addons.mozilla.org/en-US/firefox/addon/turn-off-the-lights/
