### ISSUE TITLE
Cocoon 500 errors generated due to calls from unsupported repository

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#140485]
### Type of Request

bug

### Infrastructure Environment

Cocoon

### What is happening?

We are triggering the "[High rate of 500 http .status](https://console.cloud.google.com/monitoring/alerting/policies/1436182841400880961?project=flutter-dashboard)" alert due to errors being caused by requests from the `flutter/assets-for-api-docs` repo.

We do not support this repository for luci builds.

Likely we need to filter out unsupported repositories when making these calls.

See [log](https://pantheon.corp.google.com/logs/query;cursorTimestamp=2023-12-20T23:25:43.821Z;endTime=2023-12-20T23:25:55.000Z;query=resource.type%3D%22gae_app%22%20AND%20resource.labels.project_id%3D%22flutter-dashboard%22%0AhttpRequest.status%3D500%0Atimestamp%3D%222023-12-20T23:25:43.821Z%22%0AinsertId%3D%22nlanroeft80z%22;startTime=2023-12-20T21:51:54.000Z?project=flutter-dashboard) for further details.

**Comment by yusuf-goog** [comment]
Need to disable these webhook calls on the github side since they are not relevant for this repo.

**Comment by godofredoc** [comment]
`flutter/assets-for-api-docs` got removed from the flutter-dashboard app.
