### ISSUE TITLE
SchedulerBinding.addTimingsCallback doesn't fire with SKWASM

### ISSUE THREAD

**Issue by kevmoo** [flutter/flutter#140429]
It would be amazing to have this for benchmarking!

```
Flutter 3.18.0-14.0.pre.16 • channel master • git@github.com:flutter/flutter.git
Framework • revision a1e1dc3f6c (8 hours ago) • 2023-12-19 17:03:23 +0100
Engine • revision 1d5a141917
Tools • Dart 3.3.0 (build 3.3.0-241.0.dev) • DevTools 2.31.0-dev.0
```

**Comment by yjbanov** [comment]
Bumped to P1 since it's being actively worked on.

**Comment by eyebrowsoffire** [comment]
We're going to have to revert this. This exposes an issue on the dart side (https://github.com/dart-lang/sdk/issues/54991) which breaks the skwasm benchmarks.

**Comment by kevmoo** [comment]
Reopening - the auto-close logic doesn't take into account the text in a revert PR (see https://github.com/flutter/engine/pull/50895)

**Comment by kevmoo** [comment]
I don't think so...

**Comment by zijiehe-google-com** [comment]
Emmm, why can working in my own repo impact this bug? LOL
