### ISSUE TITLE
 It's possible to run file .html, .css, .js file in Flutter?

### ISSUE THREAD

**Issue by lunvjp** [flutter/flutter#14043]
Like the title, I want to see my app can run it. Does anyone have any ideas?

**Comment by zoechi** [comment]
You can use webview. Flutter itself doesn't provide anything to render HTML or CSS or execute JS
https://github.com/dart-flitter/flutter_webview_plugin

**Comment by Hixie** [comment]
Dupe of https://github.com/flutter/flutter/issues/730
