### ISSUE TITLE
In the case of iOS rolling, the text show afterimage

### ISSUE THREAD

**Issue by DaYang816** [flutter/flutter#140442]
### Steps to reproduce

I used the EasyRefresh plug -in to refresh.
The component is covered with CustomScrollView.
Discovery in Russian environment or English environment.
The text show afterimage in IOS

### Expected results

Under normal circumstances, it should be normal

### Actual results

The text show afterimage in IOS

### Code sample

<details open><summary>Code sample</summary>

```dart
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: BrnAppBar(
          automaticallyImplyLeading: false,
          brightness: Brightness.light,
          title: Text('message'),
          titleAlignment: Alignment.center,
        ),
        body: EasyRefresh(
          clipBehavior: Clip.none,
          controller: controller.refreshController,
          onRefresh: () async {
            await Future.delayed(const Duration(seconds: 2));
            controller.refreshController.finishRefresh();
            controller.refreshController.resetFooter();
          },
          onLoad: () async {
            await Future.delayed(const Duration(seconds: 2));
            controller.refreshController.finishLoad(IndicatorResult.noMore);
          },
          child: CustomScrollView(
            slivers: [
              const HeaderLocator.sliver(),
              SliverList(
                delegate: SliverChildListDelegate([
                 Center(
                    child: SizedBox(
                      height: Get.height / 3 * 2,
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Image.asset(
                            'images/no_message_bg.png',
                            width: 148,
                            height: 78,
                          ),
                          SizedBox(height: 16),
                          Text(
                            'Нет уведомления об устройстве',
                            style: TextStyle(
                              color: Color.fromRGBO(150, 154, 157, 1),
                              fontSize: 14,
                            ),
                          )
                        ],
                      ),
                    ),
                  ),
                ]),
              ),
              const FooterLocator.sliver(),
            ],
          ),
        ),
    );
  }
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

https://github.com/flutter/flutter/assets/43984550/6d6f55d2-9a65-4a52-a099-2061898e93f0

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.12, on macOS 12.7.1 21G920 darwin-x64, locale zh-Hans-CN)
Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.85.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

**Comment by DaYang816** [comment]
I see an issue #108590 but the problem still exists

**Comment by dam-ease** [comment]
Thanks for filing this @DaYang816.
I see you are on an older version of Flutter, can you upgrade to the latest versions of flutter to see if this issue still persists?
Also, `EasyRefresh` is a third-part package, can you try with a `CircularProgressIndicator` or similar widget to see if this issue still occurs with them?

**Comment by DaYang816** [comment]
I have a project using SDK 3.13.9. After transplanting the above code, I found that it can be displayed normally.
But the upgraded version will bring code iteration, it takes a lot of time, please tell me to repair the lowest version number of this bug?

**Comment by dam-ease** [comment]
Thanks for your response. 
Not sure I understand what you mean by this

> please tell me to repair the lowest version number of this bug?

But per triage policy, since it is working on the newer versions of Flutter, I'll be closing this as fixed, if you disagree, please write in the comments and I'll reopen this.
Thank you!
