### ISSUE TITLE
Implement FlutterFire Invites plugin 

### ISSUE THREAD

**Issue by tobytraylor** [flutter/flutter#14044]
Our application has a need for the Invites module from Firebase (https://firebase.google.com/docs/invites/).  It looks to have a dependency on firebase dynamic links which does not appear to be implemented either.  Any chance to get this work prioritized.  Seems like most people using firebase would need the invites since a primary use of a realtime database is collaborative use.  

Thank you so much for the flutter framework.  It's exactly what I've been hoping for.

**Comment by long1eu** [comment]
Hi! I'm managed to implement this. It's not to hard.

**Comment by foosionsapps** [comment]
Hi @long1eu, do you have a repo example of your invites implementation? I tried to use your code in the android side but give me some errors in the MainActivity when I want to run the project.

`None of the following functions can be called with the arguments supplied: 
@NonNull public final fun addOnSuccessListener(@NonNull p0: (Runnable!) -> Unit, @NonNull p1: (PendingDynamicLinkData!) -> Unit): Task<PendingDynamicLinkData!> defined in com.google.android.gms.tasks.Task
@NonNull public final fun addOnSuccessListener(@NonNull p0: Activity, @NonNull p1: (PendingDynamicLinkData!) -> Unit): Task<PendingDynamicLinkData!> defined in com.google.android.gms.tasks.Task
@NonNull public abstract fun addOnSuccessListener(@NonNull p0: Activity, @NonNull p1: OnSuccessListener<in PendingDynamicLinkData!>): Task<PendingDynamicLinkData!> defined in com.google.android.gms.tasks.Task
@NonNull public abstract fun addOnSuccessListener(@NonNull p0: Executor, @NonNull p1: OnSuccessListener<in PendingDynamicLinkData!>): Task<PendingDynamicLinkData!> defined in com.google.android.gms.tasks.Task
e: /Users/david/IdeaProjects/my_splash/android/app/src/main/kotlin/com/yourcompany/mysplash/MainActivity.kt: (30, 14): None of the following functions can be called with the arguments supplied: 
@NonNull public final fun addOnSuccessListener(@NonNull p0: (Runnable!) -> Unit, @NonNull p1: (PendingDynamicLinkData!) -> Unit): Task<PendingDynamicLinkData!> defined in com.google.android.gms.tasks.Task
@NonNull public final fun addOnSuccessListener(@NonNull p0: Activity, @NonNull p1: (PendingDynamicLinkData!) -> Unit): Task<PendingDynamicLinkData!> defined in com.google.android.gms.tasks.Task
@NonNull public abstract fun addOnSuccessListener(@NonNull p0: Activity, @NonNull p1: OnSuccessListener<in PendingDynamicLinkData!>): Task<PendingDynamicLinkData!> defined in com.google.android.gms.tasks.Task
@NonNull public abstract fun addOnSuccessListener(@NonNull p0: Executor, @NonNull p1: OnSuccessListener<in PendingDynamicLinkData!>): Task<PendingDynamicLinkData!> defined in com.google.android.gms.tasks.Task
e: /Users/david/IdeaProjects/my_splash/android/app/src/main/kotlin/com/yourcompany/mysplash/MainActivity.kt: (33, 3): 'onSuccess' overrides nothing
e: /Users/david/IdeaProjects/my_splash/android/app/src/main/kotlin/com/yourcompany/mysplash/MainActivity.kt: (33, 50): Unresolved reference: PendingDynamicLinkData
e: /Users/david/IdeaProjects/my_splash/android/app/src/main/kotlin/com/yourcompany/mysplash/MainActivity.kt: (35, 7): Unresolved reference: Log
e: /Users/david/IdeaProjects/my_splash/android/app/src/main/kotlin/com/yourcompany/mysplash/MainActivity.kt: (35, 43): Unresolved reference: it
e: /Users/david/IdeaProjects/my_splash/android/app/src/main/kotlin/com/yourcompany/mysplash/MainActivity.kt: (37, 9): Unresolved reference: MethodChannel
e: /Users/david/IdeaProjects/my_splash/android/app/src/main/kotlin/com/yourcompany/mysplash/MainActivity.kt: (37, 75): Unresolved reference: it`


Thanks!

**Comment by Mistic92** [comment]
Hi, I created this https://github.com/Mistic92/flutter-firebase-invite
But there is no callback for receive invitation id's because I don't need that. 
However, sending invitation works :)

**Comment by pyetti** [comment]
@Mistic92 Thanks for the Android implementation. It works really well. I've been trying to implement for ios, but I can't figure out how to import InviteDelegate. I don't have any experience with ios. You know how I can do that?

`=== BUILD TARGET firebase_invite OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/peteryetti/development/flutter_plugins/flutter-firebase-invite/ios/Classes/SwiftFirebaseInvitePlugin.swift:4:66: error: use of undeclared type 'InviteDelegate'
    public class SwiftFirebaseInvitePlugin: NSObject, FlutterPlugin, InviteDelegate {...}`

**Comment by kroikie** [comment]
@tobytraylor

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/912. Any further collaboration will be done there.
