### ISSUE TITLE
Shadows on switches disappear inappropriately

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#1404]
This is especially visible on the settings page of the stocks app (if you don't notice it right away, try toggling the switches and notice how it affects the shadows of unrelated switches).

**Comment by abarth** [comment]
I suspect the problem is that we're setting the cull rect for the SkPictures too aggressively.  Probably we should set the screen size as the cull rect.

**Comment by Hixie** [comment]
dupe of https://github.com/flutter/flutter/issues/1576
