### ISSUE TITLE
SystemChrome.setSystemUIChangeCallback not functioning in Gesture-based Navigation Mode on Redmi devices

### ISSUE THREAD

**Issue by AbdeMohlbi** [flutter/flutter#140409]
### Steps to reproduce

**Steps to Reproduce:**

1. **Enable Gesture-based Navigation Mode on Redmi Device:**
    - Go to **Settings** > **Additional Settings** > **Full-screen display**.
    - Choose **Full-screen gestures** as the navigation mode.

2. **Implement `SystemChrome.setSystemUIChangeCallback` Functionality in a Flutter App:**

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await SystemChrome.setEnabledSystemUIMode(SystemUiMode.immersiveSticky);
  await SystemChrome.setSystemUIChangeCallback(
      (systemOverlaysAreVisible) async {
    print(systemOverlaysAreVisible);
  });

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      // Your app configuration here
      home: Scaffold(
        appBar: AppBar(
          title: Text('System UI Change Callback Issue'),
        ),
        body: Center(
          child: Text('System UI Change Callback Issue Demo'),
        ),
      ),
    );
  }
}

``` 

4. **Observe the Behavior of the Callback Function in Gesture-based Navigation Mode:**
   - Run the Flutter app on the Redmi device with gesture-based navigation mode activated.
   - Observe whether the `SystemChrome.setSystemUIChangeCallback` function responds or monitors system UI changes when switching between apps or interacting with system UI elements in gesture-based navigation mode.

### Expected results

The SystemChrome.setSystemUIChangeCallback should effectively monitor changes in system UI when the gesture-based navigation mode is active, just as it does in the navigation bar with buttons mode.

### Actual results

The SystemChrome.setSystemUIChangeCallback function does not respond or monitor system UI changes when the gesture-based navigation mode is enabled on Redmi devices. It works as expected only in the navigation bar with physical buttons mode.

### Code sample

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await SystemChrome.setEnabledSystemUIMode(SystemUiMode.immersiveSticky);
  await SystemChrome.setSystemUIChangeCallback(
      (systemOverlaysAreVisible) async {
    print(systemOverlaysAreVisible);
  });

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      // Your app configuration here
      home: Scaffold(
        appBar: AppBar(
          title: Text('System UI Change Callback Issue'),
        ),
        body: Center(
          child: Text('System UI Change Callback Issue Demo'),
        ),
      ),
    );
  }
}

``` 

### Flutter Doctor output

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.4, on Microsoft Windows [version 10.0.19045.3693], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.3.2)
[√] Android Studio (version 2023.1)
[√] VS Code, 64-bit edition (version 1.76.1)
[√] Connected device (4 available)
[√] Network resources
```

**Comment by dam-ease** [comment]
Hi @AbdeMohlbi.
Thanks for filing this.
I currently don't have a Redmi device to test this. Are you able to check on other Android devices to see if this issue still persists or is specific to Redmi devices?
Also, can you check out https://github.com/flutter/flutter/issues/108855 to see if its somewhat similar/related to the issue you are experiencing?

**Comment by AbdeMohlbi** [comment]
I'll need some time to test it on my older devices. It seems like the issue might be related to the phone's UI system not sending updates for Flutter, or Flutter not properly interpreting the current gestures in navigation mode.
It is intersting tho how no one on the cummunity has discoverd that issue

**Comment by AbdeMohlbi** [comment]
The mentioned issue isn't related to what I have here because the colors of the navigation bar and notification bar don't affect the UI changes that should be detected by Flutter in any mode.

**Comment by AbdeMohlbi** [comment]
> Hi @AbdeMohlbi.
> Thanks for filing this.
> I currently don't have a Redmi device to test this. Are you able to check on other Android devices to see if this issue still persists or is specific to Redmi devices?
> Also, can you check out https://github.com/flutter/flutter/issues/108855 to see if its somewhat similar/related to the issue you are experiencing?
> 

Not the same issue tho

**Comment by dam-ease** [comment]
Thanks for your response.

> I'll need some time to test it on my older devices. It seems like the issue might be related to the phone's UI system not sending updates for Flutter, or Flutter not properly interpreting the current gestures in navigation mode.

Please do help with testing this and share your findings

**Comment by AbdeMohlbi** [comment]
> Thanks for your response.
> 
> > I'll need some time to test it on my older devices. It seems like the issue might be related to the phone's UI system not sending updates for Flutter, or Flutter not properly interpreting the current gestures in navigation mode.
> 
> Please do help with testing this and share your findings

I'm currently using Flutter version 3.16.5 and have observed an intriguing behavior while attempting to swipe the notification bar. Initially, upon the first swipe to view notifications (where the clock typically appears), I noticed a lack of responsiveness. However, upon the second swipe to reveal the complete notification bar, the responsiveness was evident, printing 'true' when detected and 'false' upon disappearance.

This behavior is quite interesting as it appears to detect the notification bar's presence accurately only after the second swipe. I believe this inconsistency might be worth investigating further to ensure a seamless user experience. Any insights or suggestions to address this behavior would be greatly appreciated.

**Comment by dam-ease** [comment]
Thanks for your response.
Are these observations on a Redmi device or the other devices you were to test on?
Also, it would be really helpful if you could share screen records and device information of the test devices.
