### ISSUE TITLE
☂️ Increase minimum support iOS version from 11 to 12

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#140474]
Increase minimum target iOS version from 11.0 to 12.0.  Required to fix a crash that happens when iOS `Networking.framework` APIs are called. https://github.com/flutter/flutter/issues/136060

See details in [flutter.dev/go/match-xcode-deployment-range](https://flutter.dev/go/match-xcode-deployment-range).

- [x] https://github.com/flutter/flutter/pull/140478
- [x] Cherry-pick https://github.com/flutter/flutter/pull/140921
- [x] https://github.com/flutter/buildroot/pull/808
- [x] https://github.com/flutter/engine/pull/49542
- [x] https://github.com/flutter/website/pull/10001
- [x] https://github.com/flutter/engine/pull/49771
- [x] https://github.com/flutter/packages/pull/5902
- [ ] Once in stable, update 1p plugins to constrain to iOS version and Flutter stable version

See https://github.com/flutter/flutter/issues/101959 for when this was done 9 -> 11.

**Comment by parlough** [comment]
Do consider adding a step to add a doc to https://docs.flutter.dev/release/breaking-changes with some details on what's happening, why, etc. as a useful resource for developers to know what's coming (and later, what changed in a release).

This could land whenever, such as when the minimum change lands. The [template](https://github.com/flutter/website/blob/main/src/release/breaking-changes/template.md?plain=1) has some details on what to include in the doc.

If developers need to (or can/should) update any files from the initial template or special handling for these versions, please call that out in the doc. 

Thanks!
