### ISSUE TITLE
Hot Reload hotkey not working

### ISSUE THREAD

**Issue by APTGithubAcct** [flutter/flutter#140522]
### Steps to reproduce

Android Studio Hedgehog | 2023.1.1
Build #AI-231.9392.1.2311.11076708, built on November 9, 2023
Runtime version: 17.0.7+0-b2043.56-10550314 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false

Non-Bundled Plugins:
    Dart (231.9409)
    io.flutter (77.1.2)

I updated Android Studio to the version shown above and this problem started. I don't remember what version it was working in, but 6 months ago it was working fine.

### Expected results

Hitting Ctrl + \ on my keyboard should do a hot reload, but when I do this nothing happens. Hot restart (Ctrl + Shift + \) works just fine though.

### Actual results

...nothing happens!

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by dam-ease** [comment]
Hi @APTGithubAcct 
Thanks for filing this.
I can reproduce this on my end as well with Android Studio Hedgehog | 2023.1.1 Beta 6 but the appropriate repo for this to be filed will be https://github.com/flutter/flutter-intellij/issues.
Kindly file this issue in this repo.
Thank you!
