### ISSUE TITLE
Reverse DNS lookup on LAN ip Android regression

### ISSUE THREAD

**Issue by guyluz11** [flutter/flutter#140506]
### Steps to reproduce

Can reproduce for Android, tested also on Flutter Linux and couldn't reproduce.
I think this is a regression.
Only for local IP (LAN).

1. Create an app and prepare an Android device.
2. Find a local network's IP with a hostname.
3. Add internet permission to Android `<uses-permission android:name="android.permission.INTERNET"/>`
4. Paste the example code and replace `ip_with_host_name` with the IP you found.

### Expected results

Getting the host name of the device.

### Actual results

Getting an error in the console that the devices can't be found.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'dart:io';

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  void initState() {
    super.initState();

    initialize();
  }

  initialize() async {
    print('go');
    print('Ip ${(await InternetAddress('ip_with_host_name').reverse()).host}');
  }

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: SizedBox(),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
E/flutter ( 6212): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Failed reverse host lookup (OS Error: hostname nor servname provided, or not known, errno = 8), address = 192.168.31.81
E/flutter ( 6212): #0      _NativeSocket.reverseLookup.<anonymous closure> (dart:io-patch/socket_patch.dart:538:9)
E/flutter ( 6212): <asynchronous suspension>
E/flutter ( 6212): #1      _MyHomePageState.initialize (package:untitled/main.dart:42:18)
E/flutter ( 6212): <asynchronous suspension>
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Flutter 3.16.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 78666c8dc5 (2 days ago) • 2023-12-19 16:14:14 -0800
Engine • revision 3f3e560236
Tools • Dart 3.2.3 • DevTools 2.28.4

```

</details>

**Comment by danagbemava-nc** [comment]
`InternetAddress` is from the `dart:io` library. Any issues you face using it should be reported on the dart-lang/sdk repo. 

Unfortunately, we cannot transfer issues between flutter and dart so you will have to refile the issue over there. 

Closing from here. If you are redirected here, kindly leave a comment below and I will reopen this. 

Thank you
