### ISSUE TITLE
Show scrollbar on 2d scroll in ListView without Width

### ISSUE THREAD

**Issue by nimr77** [flutter/flutter#140599]
### Use case

this use case is mainly on the web and desktop,
let's say you have a 2D scroll and on the vertical scroll you have a wild row 
what to expect is the scrollbar should be visible on the edge of the  vertical scroll  not at the end of it 
so you don't need to slide horizontally to see the vertical scrollbar:

Here is an example:
Btw I can't just make 2D scroll to listview without giving it a width

```
    return SingleChildScrollView(
      scrollDirection: Axis.horizontal,
      child: SizedBox(
        width: 3000,
        child: ListView(
          children: [
            for (var i = 0; i < 100; i++)
              Padding(
                padding: const EdgeInsets.all(8.0),
                child: Container(
                  height: 100,
                  width: 100,
                  color: [Colors.red, Colors.green, Colors.blue][i % 3],
                  child: Text("data $i"),
                ),
              ),
          ],
        ),
      ),
    );
```

### Proposal

https://github.com/flutter/flutter/assets/36929077/4e25e37a-bff2-40d4-9f41-8d9031746851

The vertical should be visible without the need to scroll horizontally

**Comment by nimr77** [comment]
I think the issue is that we need to give the Listview a width!

**Comment by dam-ease** [comment]
Thanks for filing this @nimr77.
I can see the issue you are referring to testing with the code sample shared. Can you try out https://github.com/flutter/flutter/issues/70380#issuecomment-841544548 to see if it works in your case?

**Comment by nimr77** [comment]
I have tested the code 
for them it's working because we have one big container 
but what about a listview builder, it won't work 

```
import 'package:flutter/material.dart';

main() => runApp(MaterialApp(
      theme: ThemeData(
          scrollbarTheme: ScrollbarThemeData(
        trackVisibility: MaterialStatePropertyAll(true),
      )),
      home: MyApp(),
    ));

class MyApp extends StatefulWidget {
  @override
  MyAppState createState() => MyAppState();
}

class MyAppState extends State<MyApp> {
  ScrollController verticalController = ScrollController();
  ScrollController horizontalController = ScrollController();

  @override
  Widget build(BuildContext context) {
    return Scrollbar(
        controller: horizontalController,
        child: SingleChildScrollView(
            scrollDirection: Axis.horizontal,
            child: Scrollbar(
              controller: verticalController,
              notificationPredicate: (notification) => notification.depth == 1,
              child: SizedBox(
                width: 3000,
                child: ListView(
                  controller: verticalController,
                  children: [
                    for (var i = 0; i < 100; i++)
                      Padding(
                        padding: const EdgeInsets.all(8.0),
                        child: Container(
                          height: 100,
                          width: 100,
                          color: [Colors.red, Colors.green, Colors.blue][i % 3],
                          child: Text("data $i"),
                        ),
                      ),
                  ],
                ),
              ),
            )));
  }
}

```

**Comment by Piinks** [comment]
Hi @nimr77 this is a composition issue. When composing two scrolling widgets together with scrollbars, both of the scrollbars will need to be above both scroll views.
Alternatively, there is a 2D scrolling API you could use instead that would not require setting the width of one of the axes. The API is fairly new, and is intended to resolve these issues from nesting one dimensional scrollables inside of one another.

- https://api.flutter.dev/flutter/widgets/TwoDimensionalScrollView-class.html
- https://www.youtube.com/watch?v=UDZ0LPQq-n8&pp=ygUUMmQgc2Nyb2xsaW5nIGZsdXR0ZXI%3D
- https://www.youtube.com/watch?v=ppEdTo-VGcg&t=1s&pp=ygUUMmQgc2Nyb2xsaW5nIGZsdXR0ZXI%3D
- https://pub.dev/packages/two_dimensional_scrollables
