### ISSUE TITLE
Iterable.toString() calls iterableToShortString

### ISSUE THREAD

**Issue by Justus-M** [flutter/flutter#140564]
### Steps to reproduce

You can see it in the flutter source code, toString() for an iterable calls iterableToShortString

### Expected results

I would expect toString() to give me a full string representation of the iterable.

I just spent hours trying to figure out why my equality check for two strings of iterables was returning true even though the iterables contained different values. It was because toString was omitting a bunch of items in the middle as it was shortened by iterableToShortString.

This does not happen for ex. Lists, so I now had to convert it to a list before using toString and comparing

### Actual results

toString() returns a shortened version of the iterable

### Code sample

I believe this is self explanatory

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Not needed, the issue is clear in the source code.

**Comment by Justus-M** [comment]
It does seem to be in line with the documentation, but is there any reason why this deviates from the toString method from a list?

This inconsistent behavior is confusing, I think you shouldn't have to read the docs for things that are this fundamental/basic.

https://api.flutter.dev/flutter/dart-core/Iterable/toString.html

**Comment by danagbemava-nc** [comment]
Hi @Justus-M, this is from the `dart:core` library, as such you should file an issue on the dart-lang/sdk repo. 

Closing from here as this belongs on the dart repo. 

Thank you
