### ISSUE TITLE
Flutter cant run on android getting stack on Launching lib/main.dart on HUAWEI VNS L31 in debug mode... Initializing gradle... Observatory connection never became ready. Application finished.

### ISSUE THREAD

**Issue by harriscreativity** [flutter/flutter#14057]
here is flutter doctor

Last login: Thu Jan 11 18:23:25 on ttys001
NouvellesAppss-MacBook:~ nouvellesapps$ flutter doctor
[✓] Flutter (on Mac OS X 10.13 17A405, locale en-ZA, channel alpha)
    • Flutter at /Users/nouvellesapps/flutter
    • Framework revision 8f65fec5f5 (4 weeks ago), 2017-12-12 09:50:14 -0800
    • Engine revision edaecdc8b8
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.d8ae797298c3a6cf8dc9f4558707bd2672224d3e

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/nouvellesapps/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/nouvellesapps/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.0.1, Build version 9A1004
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Connected devices
    • HUAWEI VNS L31 • 4TE7N16615005417 • android-arm • Android 7.0 (API 24)

**Comment by mdanics** [comment]
I too am having this, trying to run on an android sim

**Comment by Hixie** [comment]
You have to tell us what the stack trace is if we are to have any hope of fixing it or helping you. :-)

**Comment by Hixie** [comment]
Please file a new bug using the templates at: https://github.com/flutter/flutter/issues/new/choose
Please include as much information as you can, including full verbose logs for when you try to run your application, the source for the application (ideally a reduced test case based on the `flutter create` template that still shows the problem), and anything else you can think of.
