### ISSUE TITLE
Support deferred components on desktop platform(MacOS/Windows/Linux)

### ISSUE THREAD

**Issue by NoelJacob** [flutter/flutter#140591]
### Use case

https://github.com/flutter/flutter/issues/136113#issue-1931237847

This issue was closed previously due to not having a use case like on android. I am developing a file manager that can show files from the cloud. Here there needs to be a plugin system for each cloud provider. Deffered components are a perfect use case for this by preventing every provider code from being sent to all users and also making the app extendable with new providers. 

### Proposal

The required package with deferred component will be downloaded from a displayed url and installed by the user in the same flow as the main app was installed in the platform. Now, the .so can be loaded by the app if available.

**Comment by jonahwilliams** [comment]
You cannot use deferred components to expand the functionality of an application or support a plugin model. They can only be use to defer the downloading of source code that was compiled together. This has applications for mobile where initial download size is a concern, but would not be worth supporting on mobile.

For your use case, you need a code push like solution.

**Comment by NoelJacob** [comment]
But they will be compiled and built together, just not downloaded when user downloads the initial app. Only when the user requires a certain cloud provider will they be downloaded and not otherwise.
