### ISSUE TITLE
High memory usage with infinite loops (not sure if it is a memory leak)

### ISSUE THREAD

**Issue by ryjacky** [flutter/flutter#140560]
### Steps to reproduce

1. Create any empty flutter project
2. add while(true){} at the first line in main(){}, or any other infinite loops like Future.periodic(...)
3. Run the program
4. Check the Windows Task manager

### Expected results

The memory should not rise because of an empty infinite loop.

### Actual results

The memory increased by more than 20MB in some cases, it's more when there's some code in the while(true){}
Same issue happens in:
- Release build generated with `flutter build windows`. 
- Creating an infinite loop in another isolate.

The same issue is not observed in a dart-only project. 

In another code where I use it with the win32 package to create a message loop, the memory consumption doubles (around 100MB more).

### Code sample

<details open><summary>Code sample</summary>
Only one while(true){} added at the very first line of main().

```dart
import 'package:flutter/material.dart';

void main() {
  while(true){}
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(

        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(

          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

You can see in the video that the memory usage (the second column) has kept rising. This is a timelapse video and the original length of the video is around 4 minutes.
https://github.com/flutter/flutter/assets/85780529/6c455588-65e9-49ae-8a61-7f18a0cc6dcf

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.5, on Microsoft Windows [Version 10.0.22621.2861], locale en-US)
    • Flutter version 3.16.5 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (3 days ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\ryjac\AppData\Local\Android\sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.5.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33627.172
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2022.2)
    • Android Studio at C:\Users\ryjac\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\222.4459.24.2221.10121639
    • Flutter plugin version 74.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2023.2.5
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.10248

[✓] VS Code (version 1.84.2)
    • VS Code at C:\Users\ryjac\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.2861]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 120.0.6099.129
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 120.0.2210.77

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @ryjacky, is this issue only on windows or are other platforms affected as well?

**Comment by ryjacky** [comment]
Hi @danagbemava-nc , can't test it with Linux currently, but it happens to both Windows 11 and MacOS 14

**Comment by danagbemava-nc** [comment]
Hi @ryjacky, does this reproduce on the mobile platforms as well?

**Comment by ryjacky** [comment]
Hi @danagbemava-nc , this does reproduce on the mobile platforms, the behavior are basically the same on all platforms

**Comment by danagbemava-nc** [comment]
Hi @ryjacky, one final thing. I've tested on windows and macOS at this point. on MacOS, I do see the memory gradually increase however, the flutter screen never loads, it's just a black screen. Windows on the other hand, never connects to the vm so I don't see the window at all. 

Do you also see a black screen on macOS? 

Also, could you let me know what exactly it is you are trying to achieve? While the code sample does indeed reproduce the issue, it doesn't exactly show what you're trying to do, maybe there's a better way to go about it.

**Comment by ryjacky** [comment]
Hi @danagbemava-nc , you're right, the app doesn't load because runApp isn't called due to the infinite loop, I put the loop there for demonstration purpose, but basically it doesn't matter where the loop is, the issue is still there. 

The thing that I'm trying to achieve is to get the mouse cursor's current **screen** position when the app is at foreground (i.e. on top of all window) and the UI needs to change according to the cursor position, for example, a widget's rotation. To do this, I have a few options: 
1. Have a very big window that span across all monitors and get the cursor's current position in the window.
2. Have a window that is just about the size of its contents and use native APIs to hook on the mouse and get its position.

For 1., it might not work properly on every system and desktop environments (because some have window size limitation), so it is likely not the option.
Now, the only option left is 2., however, doing this in Windows requires the program to first call SetWindowsHookEx and then create a message loop where GetMessage is continuously called so the mouse cursor's screen position can be retrieved. Thus, I have to create a infinite loop.

**Comment by iapicca** [comment]
isn't this behavior "intended"?

-  black screen: `while (true) {}` runs forever and `main` never reaches `runApp`
- "memory leak" is actually expected since `while (true) {}` never ends there isn't much that garbage collector can do

@ryjacky what behavior you expect?

**Comment by ryjacky** [comment]
Hmm...
For this
> black screen: while (true) {} runs forever and main never reaches runApp
Yes you're right.

For this,
> "memory leak" is actually expected since while (true) {} never ends there isn't much that garbage collector can do
I believe it would be "intended" if I create objects in the loop, but if it is an empty loop, it shouldn't create any object and should not result in increasing memory usage.

Thus, I expect the memory usage to remain the same. Which is the behavior in pure dart (no flutter framework), Java, C++, etc. Isn't this the normal situation or am I missing something...?

**Comment by iapicca** [comment]
> Thus, I expect the memory usage to remain the same. Which is the behavior in pure dart (no flutter framework), Java, C++, etc. Isn't this the normal situation or am I missing something...?

if this is true I take it back, 
the behavior should be the same of running a "hello world" pure dart app
as `runApp` is never reached

**Comment by danagbemava-nc** [comment]
> Now, the only option left is 2., however, doing this in Windows requires the program to first call SetWindowsHookEx and then create a message loop where GetMessage is continuously called so the mouse cursor's screen position can be retrieved. Thus, I have to create an infinite loop and here comes the problem where I discovered that the infinite loop results in high memory usage

Hi @ryjacky, is there any reason you can't use the event channel in flutter? This should stream the events to you which you can then handle with either a streambuilder widget or any other way of managing streams in flutter. Unless this is what you are already doing(?)

**Comment by ryjacky** [comment]
Hi @danagbemava-nc , I wasn't using it because I am not able to find a document for that. I know method channel, but not event channel. I would like to try that out if there's a document for that.

**Comment by iapicca** [comment]
@danagbemava-nc
I think that the point @ryjacky made [here](https://github.com/flutter/flutter/issues/140560#issuecomment-1877033250) may be compelling;
if a pure dart application running

```dart
void main() {
while(true) {}
print('hi mom!');
}
```
doesn't cause memory leak, than neither should the [code sample](https://github.com/flutter/flutter/issues/140560#issue-2054687181)

**Comment by danagbemava-nc** [comment]
> Edit: I mean I can't find the document for desktop platforms.

I see. I think you may have to check plugins with windows support to see if they use the EventChannel and then mirror that. You can file a request for documentation (if there isn't already one)

> if a pure dart application running
> doesn't cause memory leak, than neither should the https://github.com/flutter/flutter/issues/140560#issue-2054687181

My guess is, this would be true if dart run and flutter run did the same thing, but afaik, they do not do the same thing. 

I'm not entirely sure we are getting a memory leak. My guess as to what is happening is, the flutter engine has launched (this happens before runApp is called, the app has to be built for the target platform along with launching devtools and other things needed for the app to function) so the engine needs to handle the loop running, but this is a purely uneducated guess. 

Labeling this for further insight from the team. It would be interesting to find out why this is happening from someone with more knowledge on the topic. 

<details>
<summary>flutter doctor -v</summary>

```
[!] Flutter (Channel stable, 3.16.5, on macOS 14.1.2 23B92 darwin-arm64, locale en-GB)
    • Flutter version 3.16.5 on channel stable at /Users/nexus/dev/sdks/flutter
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutters/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutter. Consider adding /Users/nexus/dev/sdks/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutters/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutter. Consider adding /Users/nexus/dev/sdks/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (3 weeks ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc1)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0-rc1
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-15.0.0-Release.Candidate.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.10072.19

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (4 available)
    • Pixel 7 (mobile) • 28291FDH2001SA            • android-arm64  • Android 14 (API 34)
    • Nexus (mobile)   • 00008020-001875E83A38002E • ios            • iOS 17.2.1 21C66
    • macOS (desktop)  • macos                     • darwin-arm64   • macOS 14.1.2 23B92 darwin-arm64
    • Chrome (web)     • chrome                    • web-javascript • Google Chrome 120.0.6099.199
    ! Error: Browsing on the local area network for Dean’s iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
  
```
[✓] Flutter (Channel master, 3.18.0-19.0.pre.103, on macOS 14.1.2 23B92 darwin-arm64, locale en-GB)
    • Flutter version 3.18.0-19.0.pre.103 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 65fae87f2f (2 hours ago), 2024-01-08 00:12:26 -0500
    • Engine revision 702ae19c00
    • Dart version 3.3.0 (build 3.3.0-279.0.dev)
    • DevTools version 2.31.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc1)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0-rc1
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-15.0.0-Release.Candidate.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.10072.19

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (4 available)
    • Pixel 7 (mobile) • 28291FDH2001SA            • android-arm64  • Android 14 (API 34)
    • Nexus (mobile)   • 00008020-001875E83A38002E • ios            • iOS 17.2.1 21C66
    • macOS (desktop)  • macos                     • darwin-arm64   • macOS 14.1.2 23B92 darwin-arm64
    • Chrome (web)     • chrome                    • web-javascript • Google Chrome 120.0.6099.199
    ! Error: Browsing on the local area network for Dean’s iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
</details>

**Comment by ryjacky** [comment]
Hi @danagbemava-nc , thanks for the response. Just to clarify that no matter the infinite loop is before or after the runApp() call, the same behavior can be observed.

**Comment by dnfield** [comment]
Capturing a native heap profile would probably be somewhat instructive here. I don't know how to do that on Windows (maybe @loic-sharma or @yaakovschectman know?). 

On macOS or iOS you can use Instruments. On Android you can use heapprof.

If you can capture what memory is getting allocated during this time we might be able to do something about it.

But .. I don't think this is a use case we should worry about too much. Infinite loops can have weird effects. Maybe what's getting allocated is perfectly fine and we shouldn't care about it because we shouldn't really care about making infinite loops efficient - for example, if somehow the compiler decided your code doesn't make sense because of the infinite loop and did something weird, oh well.

**Comment by jason-simmons** [comment]
Took a quick look at this and noticed that app process memory usage increased during the infinite loop on a debug build launched from flutter_tools.  Within a minute the process' memory usage stabilized at about 15MB more than the initial usage at launch.

I was not able to reproduce this on a release build.  I was also unable to reproduce in a debug build launched from Xcode without flutter_tools.

So that implies that this is due to overhead from services used by development tools.

**Comment by ryjacky** [comment]
Omg, hi @jason-simmons , it seems like you're right, I think I might have not tested an _empty_ infinite loop with a release build and it's more likely something mentioned by @iapicca 
> "memory leak" is actually expected since while (true) {} never ends there isn't much that garbage collector can do

I will be closing this issue. 
Gosh that's embarrassing... Anyway thanks for everyone who have helped.

**Comment by iapicca** [comment]
> Omg, hi @jason-simmons , it seems like you're right, I think I might have not tested an _empty_ infinite loop with a release build and it's more likely something mentioned by @iapicca 
> > "memory leak" is actually expected since while (true) {} never ends there isn't much that garbage collector can do
> 
> I will be closing this issue. 
> Gosh that's embarrassing... Anyway thanks for everyone who have helped.
> 

No reason to be embarrassed
Happy coding
