### ISSUE TITLE
[go_router] How to rebuild a widget when the route changes using go_router 13.0.0?

### ISSUE THREAD

**Issue by petodavid** [flutter/flutter#140539]
### What package does this bug report belong to?

go_router

### What target platforms are you seeing this bug on?

Android, iOS

### Have you already upgraded your packages?

Yes

### Dependency versions

```lock
  go_router:
    dependency: "direct main"
    description:
      name: go_router
      sha256: ca7e4a2249f96773152f1853fa25933ac752495cdd7fdf5dafb9691bd05830fd
      url: "https://pub.dev"
    source: hosted
    version: "13.0.0"```

</details>
```

### Steps to reproduce

```
class HomePageAppBar extends StatelessWidget {
  const HomePageAppBar({super.key});

  @override
  Widget build(BuildContext context) {
    final enableHero = GoRouter.of(context).location == GoRouterState.of(context).namedLocation(HomePage.name);

    return HeroMode(
      enabled: enableHero,
      child: Hero(
        tag: 'test',
        child: Placeholder(),
      ),
    );
  }
}
```

### Expected results

Until now the widget rebuilt every time when the route changed

### Actual results

The widget does not rebuild when the route changes, how can we rebuild the widget using the latest 13.0 go_router when the route changes?

### Code sample
```
class HomePageAppBar extends StatelessWidget {
  const HomePageAppBar({super.key});

  @override
  Widget build(BuildContext context) {
    final enableHero = GoRouter.of(context).location == GoRouterState.of(context).namedLocation(HomePage.name);

    return HeroMode(
      enabled: enableHero,
      child: Hero(
        tag: 'test',
        child: Placeholder(),
      ),
    );
  }
}
```

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.16.5, on macOS 14.2.1 23C71 darwin-arm64, locale en-US)
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.2.3/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/david/Developer/flutter. Consider adding
      /Users/david/Developer/flutter/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.85.1)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by dam-ease** [comment]
Thanks for filing this @petodavid 
It seems your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if any. Please also see [flutterhelp](https://www.reddit.com/r/flutterhelp/) for resources and ask questions like this.

Closing from here as this is more of a how-to question rather than a bug or feature request.
If you are proposing a change, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly.
