### ISSUE TITLE
support  onFocus and onBlur for Input

### ISSUE THREAD

**Issue by laterdayi** [flutter/flutter#140538]
### Use case

TextField(onBlur:(value){...}),

### Proposal

When widgets lose focus, they perform server-side input validation, but Flutter does not have a specific hook for such events.

This is not just for networking or multi-line scenarios. If the mobile application has multiple text fields on the screen, and the user can click directly from one text field to another, there needs to be a way to perform actions when the focus changes. You cannot rely on the user to click the Done button, as this is not the only way for the user to exit a field after making an edit.

For anyone with a Web or React Native background, having an "onBlur" or similar callback will be very convenient and familiar.

The current fouceNode method is so outdated that many people need these hooks, so why not make the input field more convenient?

**Comment by dam-ease** [comment]
Thanks for proposing this @laterdayi.
Have you tried using [AutovalidateMode](https://api.flutter.dev/flutter/widgets/FormField/autovalidateMode.html)?
Do you have any issues with it?
I see there are existing proposals similar to this as well
https://github.com/flutter/flutter/issues/40675
https://github.com/flutter/flutter/issues/45841
Can you comment, upvote and follow up on these proposals to avoid duplicates?

**Comment by laterdayi** [comment]
I have a lot of dynamic input fields, and I expect each input field to execute the network request separately out of focus, but this is currently outdated

**Comment by laterdayi** [comment]
I have seen similar problems, but it has been going on for three years and the problem has not been solved

**Comment by Mairramer** [comment]
@laterdayi I'm not a member of the Flutter team, but I think I'll try to implement this. I think it will solve a problem we have/had in our app. Even though it was resolved in another way.

**Comment by Mairramer** [comment]
@laterdayi In the case of `onblur`, you could use [onTapOutside property](https://api.flutter.dev/flutter/material/TextField/onTapOutside.html) .

**Comment by laterdayi** [comment]
This seems to be unsolvable. What I hope is that the input box will request the network interface when it leaves the focus, rather than clicking to complete the appropriate

**Comment by dam-ease** [comment]
Thanks for your response @laterdayi.
This is similar to the existing issues I shared https://github.com/flutter/flutter/issues/140538#issuecomment-1867600881.
Kindly comment, upvote and follow up on these proposals.
Closing this as a duplicate per the above, if you disagree, please comment and I'll reopen this.
Thank you!
