### ISSUE TITLE
Support build.gradle.kts in addition to build.gradle

### ISSUE THREAD

**Issue by reidbaker** [flutter/flutter#140548]
Flutter tools currently check `build.gradle` file only.
Flutter should support both `build.gradle` and `build.gradle.kts` in flutter tools. 

https://github.com/flutter/flutter/blob/ede594f8816f8c0e5a390f5bbb636b4dcaf55f62/packages/flutter_tools/lib/src/project.dart#L654-L656
Some more places where `build.gradle` is hardcoded:
https://github.com/flutter/flutter/blob/ede594f8816f8c0e5a390f5bbb636b4dcaf55f62/packages/flutter_tools/lib/src/project.dart#L558
https://github.com/flutter/flutter/blob/ede594f8816f8c0e5a390f5bbb636b4dcaf55f62/packages/flutter_tools/lib/src/project.dart#L674

Helpfully pointed out in. 
https://github.com/flutter/flutter/issues/121541#issuecomment-1867794715

**Comment by bartekpacia** [comment]
I like this!

I implemented support for Gradle Kotlin DSL in Flutter tool back in #118067 but it was rejected at the time. 
I understand that [this comment of yours](https://github.com/flutter/flutter/pull/118067#issuecomment-1424476038) does not longer represent your current stance on this topic? Because I'd be happy to try to contribute this feature again:)

**Comment by bartekpacia** [comment]
Assigning myself, will try to work on this in the winter break.

**Comment by bartekpacia** [comment]
Aaaand done :) (though I don't think it'll land in the next stable in mid-February)

**Comment by iapicca** [comment]
@bartekpacia 
will`build.gradle.kts` be the default for new projects?

**Comment by bartekpacia** [comment]
No issues for that exists as of now, but of course I'd love to make that happen. Feel free to create an issue for that!

**Comment by reidbaker** [comment]
@iapicca not yet and right now I am thinking not for at least 1-2 releases. The flutter android team is migrating our internal build tooling to kotlin but we need time to update documentation, build migration tooling etc before we would want it to be the default. Right now I would describe kotlin build file support to be in preview for flutter developers that really want to be using kotlin we are going to try to get out of the way.
