### ISSUE TITLE
Native Assets should use Framework instead of dylib on iOS.

### ISSUE THREAD

**Issue by SKKbySSK** [flutter/flutter#140544]
### Use case

It seems that the App Store does not allow iOS app linked with dylib files.
- https://developer.apple.com/forums/thread/670761
- https://developer.apple.com/forums/thread/733527

 
So, we can't upload the Flutter app contains Native Assets package dependencies for now.

### Proposal

Build Framework or XCFramework instead of dylib when using Native Assets package.
Also, we may need to add [Privacy Manifest files](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files?language=objc) in it.

**Comment by jmagman** [comment]
@dcharkes +1 there shouldn't be loose dylibs in the Frameworks directory, or for macOS. 
I wasn't around when you implemented this in https://github.com/flutter/flutter/pull/130494, but it should be _relatively_ simple to make the dylib into a proper .framework.

macOS is the trickier one since the bundle structure requires symlinking:

https://github.com/flutter/flutter/blob/8e431e106e2b9cf1e2570f4cc13f9344c8699534/packages/flutter_tools/lib/src/build_system/targets/macos.dart#L398-L410
https://github.com/flutter/flutter/blob/8e431e106e2b9cf1e2570f4cc13f9344c8699534/packages/flutter_tools/lib/src/build_system/targets/macos.dart#L450-L477
symlinking trickiness
https://github.com/flutter/flutter/blob/8e431e106e2b9cf1e2570f4cc13f9344c8699534/packages/flutter_tools/lib/src/build_system/targets/macos.dart#L504-L526

You can see the iOS one here:
https://github.com/flutter/flutter/blob/8e431e106e2b9cf1e2570f4cc13f9344c8699534/packages/flutter_tools/lib/src/build_system/targets/ios.dart#L117-L123

You'll need to rename it and set the `install_name` (I see you figured that out, though I think `@rpath/ffiPackageName` would be more correct than from `@executable_path/Frameworks` though I'm willing to be convinced otherwise)
https://github.com/flutter/flutter/blob/8e431e106e2b9cf1e2570f4cc13f9344c8699534/packages/flutter_tools/lib/src/macos/native_assets_host.dart#L85-L87

Not sure how the tooling would handle generating the privacy manifest...  I imagine the same for however it's handled for other packages? https://github.com/flutter/flutter/issues/131940

cc @stuartmorgan @vashworth

**Comment by stuartmorgan** [comment]
> @dcharkes +1 there shouldn't be loose dylibs in the Frameworks directory, or for macOS.
> I wasn't around when you implemented this in #130494, but it should be _relatively_ simple to make the dylib into a proper .framework.

Sorry about that, I wasn't aware of this restriction when reviewing.

> Not sure how the tooling would handle generating the privacy manifest... I imagine the same for however it's handled for other packages? #131940

Well, whatever we do for plugins will almost certainly be using Cocoapods (or eventually SPM) directives. Since this has its own build system, it will need its own way of declaring a manifest.

**Comment by dcharkes** [comment]
I've been playing around with this today.

@jmagman Do we need one framework per dynamic library?

I'm only succeeding in doing the code signing if the name of the dylib is the same as the name of the framework: e.g. `NativeAssets.Framework/NativeAssets`. `NativeAssets.Framework/libmy_package.dylib` does not work: `exit code: 1  /Users/dacoharkes/src/dacoharkes/playground/my_package/example/build/native_assets/ios/NativeAssets.Framework/: bundle format unrecognized, invalid, or unsuitable`.

This seems to be consistent with the documentation for `Info.plist`:

https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-101909

Hardcoded only having a single dylib and packaging it as `NativeAssets.Framework/NativeAssets`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleDevelopmentRegion</key>
  <string>en</string>
  <key>CFBundleExecutable</key>
  <string>NativeAssets</string>
  <key>CFBundleIdentifier</key>
  <string>io.flutter.flutter.native_assets</string>
  <key>CFBundleInfoDictionaryVersion</key>
  <string>6.0</string>
  <key>CFBundleName</key>
  <string>NativeAssets</string>
  <key>CFBundlePackageType</key>
  <string>FMWK</string>
  <key>CFBundleShortVersionString</key>
  <string>1.0</string>
  <key>CFBundleSignature</key>
  <string>????</string>
  <key>CFBundleVersion</key>
  <string>1.0</string>
  <key>MinimumOSVersion</key>
  <string>11.0</string>
</dict>
</plist>
```

The signing seems to be working also if an `Info.plist` is omitted. But I assume we need to include it.

(We currently don't support it yet in native assets, but in the future we'd like to support dynamic libraries depending on other dynamic libraries through the native linker. It seems logical that then we'd have multiple dynamic libraries in a single framework? Especially if one dylib is being depended on by another dylib and both are coming from different Dart packages's `build.dart`.)

**Comment by jmagman** [comment]
> Do we need one framework per dynamic library?

Yup!

> I'm only succeeding in doing the code signing if the name of the dylib is the same as the name of the framework

I believe that's true.  The Flutter engine does this and copies `libFlutter` to `Flutter` and changes the `install_name`.
https://github.com/flutter/engine/blob/bf979d22028360c3ff3c7bd08a0b3869ac79d51b/shell/platform/darwin/ios/BUILD.gn#L318
https://github.com/flutter/engine/blob/bf979d22028360c3ff3c7bd08a0b3869ac79d51b/shell/platform/darwin/ios/BUILD.gn#L337C30-L338


> This seems to be consistent with the documentation for `Info.plist`:

I believe it may only be ["needed" for macOS](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPFrameworks/Concepts/FrameworkAnatomy.html) (but it may work without it)?  
I don't think iOS is as well documented, and I believe it works there without one.  Probably Apple would tell you it's needed in both cases, but I spot it in the tool for macOS only.

**Comment by dcharkes** [comment]
> > Do we need one framework per dynamic library?
> 
> Yup!

Ok!

> macOS is the trickier one since the bundle structure requires symlinking

MacOS seems to work locally without symlinking. Is the symlinking a requirement for publishing in the store?

**Comment by jmagman** [comment]
> MacOS seems to work locally without symlinking. Is the symlinking a requirement for publishing in the store?

Yes you definitely need the symlinking, this was a fun P0 when the symlinks weren't preserved https://github.com/flutter/flutter/issues/77173#issuecomment-790151782

**Comment by dcharkes** [comment]
> > MacOS seems to work locally without symlinking. Is the symlinking a requirement for publishing in the store?
> 
> Yes you definitely need the symlinking, but it would fail before App Store publication, including codesigning. This was a fun P0 when the symlinks weren't preserved [#77173 (comment)](https://github.com/flutter/flutter/issues/77173#issuecomment-790151782)

Okay, I'll take a look at setting up the correct structure with symlinks tomorrow.

https://github.com/flutter/flutter/pull/140907 has fixes excluding symlinks. Happy to add the symlinks stuff to that PR or do it in a follow up PR.

**Comment by jmagman** [comment]
> Happy to add the symlinks stuff to that PR or do it in a follow up PR.

I think you should add it to this PR, maybe I'm just traumatized by other times we had macOS framework symlinking issues, but I'd hate for a follow-up PR to be reverted and then for this to be in a non-symlinked state.

**Comment by dcharkes** [comment]
> > Happy to add the symlinks stuff to that PR or do it in a follow up PR.
> 
> I think you should add it to this PR, maybe I'm just traumatized by other times we had macOS framework symlinking issues, but I'd hate for a follow-up PR to be reverted and then for this to be in a non-symlinked state.

I've added it to the PR. So it's ready for review now.

**Comment by jmagman** [comment]
@dcharkes is there more work to track here? Or should https://github.com/flutter/flutter/pull/140907 have closed this?

**Comment by dcharkes** [comment]
The privacy manifest work is tracked in:

* https://github.com/flutter/flutter/issues/140966

The framework packaging is done indeed.
