### ISSUE TITLE
Cannot customise borders of years section in showDatePicker

### ISSUE THREAD

**Issue by AndreeaCcss** [flutter/flutter#140509]
### Steps to reproduce

The years section in the showDatePicker has a border top and bottom that cannot be customised and doesn't respond to any changes applied in the Theme. I would expect that the dividerColor is also applied to this border, or that any other colours options in the ColorScheme could impact these borders

### Expected results

The years section border top and bottom colour take the same colour as the dividerColor in the first screen
<img width="322" alt="Screenshot 2023-12-21 at 15 10 53" src="https://github.com/flutter/flutter/assets/41521522/3c530ce0-a772-4572-bb6f-3a5ebceb462a">

### Actual results

The years section has a border top and bottom whose colours aren't affected by the custom styles
<img width="322" alt="Screenshot 2023-12-21 at 15 04 41" src="https://github.com/flutter/flutter/assets/41521522/32bba615-f5f3-4f75-9fa5-81c9dc3da968">

### Code sample

<details open>
<summary>Code sample</summary>

```dart
showDatePicker(
                                builder: (BuildContext context, Widget? child) {
                                  return Theme(
                                    data: Theme.of(context).copyWith(
                                      inputDecorationTheme:
                                          InputDecorationTheme(
                                              border: UnderlineInputBorder(
                                        borderSide: BorderSide(
                                          width: 0.5,
                                          color: ColorRes.colorPrimary,
                                        ),
                                      )),
                                      colorScheme: ColorScheme.light(
                                          onPrimary: ColorRes.white,
                                          primary: ColorRes.colorPrimary,
                                          background: ColorRes.white),
                                      datePickerTheme: DatePickerThemeData(
                                        headerBackgroundColor:
                                            ColorRes.colorPrimary,
                                        backgroundColor: ColorRes.white,
                                        headerForegroundColor: ColorRes.white,
                                        surfaceTintColor: ColorRes.white,
                                        dividerColor: ColorRes.colorPrimary,
                                      ),
                                    ),
                                    child: child!,
                                  );
                                })
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.1.1 23B81 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by OPTRONIX-10** [comment]
in color scheme use property outlinevariant to change the color of border

**Comment by AndreeaCcss** [comment]
Awesome, that worked, thank you!

**Comment by danagbemava-nc** [comment]
Closing this since it seems like the issue has been solved. 

Thank you
