### ISSUE TITLE
Who is and why GitHub is on my phone and I get notifications from GitHub 

### ISSUE THREAD

**Issue by Muakd** [flutter/flutter#140669]
Source:     8 samples on Battery, 1 samples on AC
  7  ??? (libsystem_pthread.dylib + 6672) [0x2171c3a10]
    7  ??? (libsystem_pthread.dylib + 9428) [0x2171c44d4]
      7  ??? (QuartzCore + 2929952) [0x1aea75520]
        7  ??? (QuartzCore + 2870772) [0x1aea66df4]
          7  ??? (CoreFoundation + 209372) [0x1ad1d11dc]
            7  ??? (CoreFoundation + 210040) [0x1ad1d1478]
              7  ??? (CoreFoundation + 212512) [0x1ad1d1e20]
                7  ??? (CoreFoundation + 215016) [0x1ad1d27e8]
                  7  ??? (CoreFoundation + 220512) [0x1ad1d3d60]
                    7  ??? (CoreFoundation + 220708) [0x1ad1d3e24]
                      7  ??? (QuartzCore + 193636) [0x1ae7d9464]
                        7  ??? (QuartzCore + 592864) [0x1ae83abe0]
                          2  ??? (QuartzCore + 525620) [0x1ae82a534]
                            2  ??? (QuartzCore + 601468) [0x1ae83cd7c]
                              2  ??? (QuartzCore + 605908) [0x1ae83ded4]
                                1  ??? (Metal + 1361472) [0x1aced3640]
                                  1  ??? (AGXMetalG15 + 3152620) [0x246442aec]
                                    1  ??? (AGXMetalG15 + 3141812) [0x2464400b4]
                                      1  ??? (AGXMetalG15 + 4356588) [0x2465689ec]
                                        1  ??? (AGXMetalG15 + 4275480) [0x246554d18]
                                          1  ??? (AGXMetalG15 + 3625188) [0x2464b60e4]
                                1  ??? (Metal + 310724) [0x1acdd2dc4]
                                  1  ??? (libdispatch.dylib + 80616) [0x1b51a4ae8]
                                    1  ??? (libdispatch.dylib + 17152) [0x1b5195300]
                                      1  ??? (Metal + 30856) [0x1acd8e888]
                                        1  ??? (Metal + 31384) [0x1acd8ea98]
                                          1  ??? (IOGPU + 19312) [0x22380db70]
                                            1  ??? (IOGPU + 19704) [0x22380dcf8]
                                              1  ??? (IOKit + 208484) [0x1b5c22e64]
                                                1  <Kernel mode>
                          2  ??? (QuartzCore + 524448) [0x1ae82a0a0]
                            2  ??? (QuartzCore + 303448) [0x1ae7f4158]
                              2  ??? (QuartzCore + 304420) [0x1ae7f4524]
                                1  ??? (QuartzCore + 809532) [0x1ae86fa3c]
                                  1  ??? (QuartzCore + 27512) [0x1ae7b0b78]
                                    1  ??? (QuartzCore + 16956) [0x1ae7ae23c]
                                      1  ??? (QuartzCore + 17356) [0x1ae7ae3cc]
                                        1  ??? (QuartzCore + 27512) [0x1ae7b0b78]
                                          1  ??? (QuartzCore + 16956) [0x1ae7ae23c]
                                            1  ??? (QuartzCore + 17356) [0x1ae7ae3cc]
                                              1  ??? (QuartzCore + 27512) [0x1ae7b0b78]
                                                1  ??? (QuartzCore + 16956) [0x1ae7ae23c]
                                                  1  ??? (QuartzCore + 17356) [0x1ae7ae3cc]
                                                    1  ??? (QuartzCore + 27512) [0x1ae7b0b78]
                                                      1  ??? (QuartzCore + 16956) [0x1ae7ae23c]
                                                        1  ??? (QuartzCore + 17356) [0x1ae7ae3cc]
                                                          1  ??? (QuartzCore + 27512) [0x1ae7b0b78]
                                                            1  ??? (QuartzCore + 16956) [0x1ae7ae23c]
                                                              1  ??? (QuartzCore + 17356) [0x1ae7ae3cc]
                                                                1  ??? (QuartzCore + 27512) [0x1ae7b0b78]
                                                                  1  ??? (QuartzCore + 16956) [0x1ae7ae23c]
                                                                    1  ??? (QuartzCore + 17356) [0x1ae7ae3cc]
                                                                      1  ??? (QuartzCore + 27512) [0x1ae7b0b78]
                                                                        1  ??? (QuartzCore + 16956) [0x1ae7ae23c]
                                                                          1  ??? (QuartzCore + 17356) [0x1ae7ae3cc]
                                                                            1  ??? (QuartzCore + 27484) [0x1ae7b0b5c]
                                                                              1  ??? (QuartzCore + 250340) [0x1ae7e71e4]
                                                                                1  ??? (QuartzCore + 406820) [0x1ae80d524]
                                                                                  1  ??? (QuartzCore + 6998 
                                                                                  why Im I getting this why is my phone been connected to this platform

**Comment by stuartmorgan** [comment]
Closing as this is unrelated to Flutter.
