### ISSUE TITLE
I want a holdable button with animation

### ISSUE THREAD

**Issue by mohammadgjafari** [flutter/flutter#140605]
### Use case

I want a button or container widget which when I hold it, a loading or animation starts on its border and traverse the whole border.

### Proposal

![holdable](https://github.com/flutter/flutter/assets/120301662/37e45633-0384-4e04-ab4f-1d8cba5eaac5)

**Comment by MahdiGharooni** [comment]
you can use my new Flutter plugin, [holdable_button](https://pub.dev/packages/holdable_button) 

it is exactly what you want, when you hold the button(container) a loading will starts near the border, you can also customize it with change the color, child, margin and time duration. Although it should complete.

![hold](https://github.com/flutter/flutter/assets/39171814/e4af02f4-5476-42d5-88fb-5f843cc058d5)

**Comment by mohammadgjafari** [comment]
> you can use my new Flutter plugin, [holdable_button](https://pub.dev/packages/holdable_button)
> 
> it is exactly what you want, when you hold the button(container) a loading will starts near the border, you can also customize it with change the color, child, margin and time duration. Although it should complete.
> 
> ![hold](https://private-user-images.githubusercontent.com/39171814/292756959-5ab5af7d-35d0-4ce3-bf35-85a8988d7b98.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MDg0NzcsIm5iZiI6MTcwMzUwODE3NywicGF0aCI6Ii8zOTE3MTgxNC8yOTI3NTY5NTktNWFiNWFmN2QtMzVkMC00Y2UzLWJmMzUtODVhODk4OGQ3Yjk4LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDEyNDI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2YTgwM2I3MDVhY2VhYzJiMTQzYzg3NjdmYmJhZjg3N2VhMDcwYzc1OTAxMzQ1ZDRhNWFkMGRmNjQwZWY2MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uJ_aHZyVvgaZRiHjwvISrKxDdDtRFFY2-Wf5SnaB6G0)
