### ISSUE TITLE
Building flutter tool 

### ISSUE THREAD

**Issue by cazewonder** [flutter/flutter#14065]
I'm trying to setup flutter on Ubuntu 16.04 x64
Stuck at "Building flutter tool...." for over 30minutes with nothing.
I downloaded and installed dart with deb package but same thing happens.

**Comment by mit-mit** [comment]
You do not need to download and install dart separately.

As for the "Building flutter..." issue, can you try to run the following command: `flutter -v doctor`?

**Comment by cazewonder** [comment]
Installed successfully. Thank you.
