### ISSUE TITLE
set DraggableScrollableSheet initialChildSize to the widget content

### ISSUE THREAD

**Issue by faisalansari0367** [flutter/flutter#140637]
Issue Description:
I have a widget containing multiple nested elements, and I'm encountering an issue with the bottom sheet's initial size. Presently, the bottom sheet defaults to occupying 50% (0.5) of the screen, but I aim for it to adopt the size of my parent widget as its initial state.

The current behavior causes the bottom sheet to open at a fixed size regardless of the content within my widget. I'm seeking guidance on how to dynamically adjust the initial size of the bottom sheet to match the dimensions of the parent widget.

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp(home: MainApp()));
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        onPressed: () => openDynamicSheet(context),
      ),
      body: const Center(
        child: Text('Hello World!'),
      ),
    );
  }

  void openDynamicSheet(BuildContext context) {
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      builder: (context) {
        return const DynamicSheet();
      },
    );
  }
}

class DynamicSheet extends StatelessWidget {
  const DynamicSheet({super.key});

  @override
  Widget build(BuildContext context) {
    return DraggableScrollableSheet(
      expand: false,
      builder: (context, scrollController) {
        return Container(
          color: Colors.blue[100],
          child: Column(
            children: [
              Container(
                color: Colors.red,
                height: 200,
              ),
              Container(
                color: Colors.green,
                height: 200,
              ),
              Container(
                color: Colors.blue,
                height: 200,
              ),
            ],
          ),
        );
      },
    );
  }
}

```

| Image 1                                      | Image 2                                      |
|----------------------------------------------|----------------------------------------------|
| ![Image 1](https://github.com/flutter/flutter/assets/61263149/c5193963-ce6a-4381-ab0a-9edbfa814015) | ![Image 2](https://github.com/flutter/flutter/assets/61263149/485feafc-0e33-4b4b-bc31-f4a0c1cdf0f2) |

**Comment by moffatman** [comment]
Do you mean dimensions of child? Would like this feature too, right now I use a complex parallel calculation to figure out the expected height and pass it to the draggablescrollablesheet initialSize and minSize. However this only really works for me as the child is relatively simple (a grid).

**Comment by faisalansari0367** [comment]
Yes, my problem is that when I set an initialChildSize for example 0.6 it gives renderflex on some devices and the widgets that are rendering in the bottom sheet are based on the API calls. so would love to have something where we initialise the bottom sheet with the dimensions of the child widget.

I have tried to get the size of child widget using renderBox but it returns the size of the parent element which is 0.6

**Comment by dam-ease** [comment]
Thanks for filing this @faisalansari0367.
Can you check out this third-party package https://pub.dev/packages/flutter_screenutil to see if it could suit your use case?

**Comment by faisalansari0367** [comment]
> Thanks for filing this @faisalansari0367. Can you check out this third-party package https://pub.dev/packages/flutter_screenutil to see if it could suit your use case?

Thanks @dam-ease for your response.
I am already using [flutter_screenutil](https://pub.dev/packages/flutter_screenutil) but still unable to achieve the expected results.

My use case is very simple yet very hard to achieve:
I want the `DraggableScrollableSheet` in Flutter to automatically adjust its initial size based on the height of its child widget, rather than setting the initialChildSize manually or setting it do 0.5 by default.

**Comment by faisalansari0367** [comment]
Dear @goderbauer and @dam-ease,

I would greatly appreciate any suggestions, insights, or workarounds you might have regarding my current challenge. I'm seeking assistance in resolving an issue and would be grateful for your expertise.

**Comment by dam-ease** [comment]
Thanks for your response @faisalansari0367.
A possible solution I'm aware of currently is to use some UI calculations to determine the minHeight and make use of [flutter_screenutil](https://pub.dev/packages/flutter_screenutil) to avoid overflows across devices.

You can see support channels like StackOverflow, and ask the same there for solutions if any. Also, you can see [flutterhelp](https://www.reddit.com/r/flutterhelp/) for resources and ask questions like this.

Closing from here as this is more of a how-to question rather than a bug or feature request.

If you are proposing a change, please use the appropriate new issue template and fill out the requested details so that we can address this issue properly.

If you disagree, please write in the comments and I'll reopen this, thank you!
