### ISSUE TITLE
[image_picker][Android] Wide angle option is missing

### ISSUE THREAD

**Issue by jacky87218** [flutter/flutter#140686]
### Steps to reproduce

1. Import package image_picker: 1.0.5
2. Use a "Redmi Note 11S 5G"
3. run ImagePicker().pickImage(source: ImageSource.camera)
4. Screen showing camera view

### Expected results

The camera view displays the wide-angle option (0.6X) and is usable.

Original camera display：

![Redmi Note-camera](https://github.com/flutter/flutter/assets/136868358/fb22ea26-6b51-411b-9882-179001bc92a9)

### Actual results

The camera view only shows the size (1X) and can be zoomed to (2X) via gestures, but can not zoom to the wide-angle setting (0.6X).

![do-image_picker](https://github.com/flutter/flutter/assets/136868358/7ce5a80f-0b75-4ffa-84e3-7b005885ca9f)

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'dart:async';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

class ImagePickerPage extends StatefulWidget {
  const ImagePickerPage({Key? key});

  @override
  State<ImagePickerPage> createState() => _ImagePickerPageState();
}

class _ImagePickerPageState extends State<ImagePickerPage> {
  late List<XFile> _imageFileList;

  @override
  void deactivate() {
    super.deactivate();
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  void initState() {
    _imageFileList = [];
  }

  void _setImageFileListFromFile(XFile? value) {
    if(value != null) {
      _imageFileList.add(value);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Center(
          child: Wrap(
            spacing: 5,
            runSpacing: 5,
            children: _showImages(),
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          takeImage();
        },
        tooltip: "take picture",
        child: const Icon(Icons.add_a_photo),
      ),
    );
  }

  Future takeImage() async {
    final XFile? image = await ImagePicker().pickImage(
      source: ImageSource.camera,
      // maxWidth: 1920,
      // maxHeight: 1080,
      // imageQuality: 50
    );

    if(image != null) {
      _setImageFileListFromFile(image);
      setState(() {
      });
    }
  }

  _showImages() {
    return _imageFileList?.map((file)  {
      return Stack(
        children: <Widget>[
          Container(
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(5),
              color: Colors.black
            ),
            child:
              ClipRRect(
                borderRadius: BorderRadius.circular(5),
                child: Image.file(File(file.path), width: 240, height: 240, fit: BoxFit.contain,),
              ),
          ),
          Positioned(
            right: 5,
            top: 5,
            child: GestureDetector(
              onTap: () {
                setState(() {
                  _imageFileList.remove(file);
                });
              },
              child: ClipOval(
                child: Container(
                  padding: const EdgeInsets.all(3),
                  decoration: BoxDecoration(color: Colors.black54),
                  child: Icon(
                    Icons.close,
                    size: 18,
                    color: Colors.yellow,
                  ),
                ),
              ),
            ),
          ),
        ],
      );
    }).toList();
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console

[√] Flutter (Channel stable, 3.13.9, on Microsoft Windows [版本 10.0.22000.2538], locale zh-TW)
    • Flutter version 3.13.9 on channel stable at D:\tool\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (9 weeks ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at D:\tool\Android\Sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = D:\tool\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code (version 1.85.1)
    • VS Code at C:\Users\p10375256\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.78.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.22000.2538]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 120.0.6099.130
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 120.0.2210.91

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by danagbemava-nc** [comment]
Hi @jacky87218, the image_picker plugin calls a native view which renders the camera view for you. If it isn't available it is either the native view isn't providing it or some options aren't being passed. Do you get the same issue when you try with a native android example?

**Comment by jacky87218** [comment]
> Hi @jacky87218, the image_picker plugin calls a native view which renders the camera view for you. If it isn't available it is either the native view isn't providing it or some options aren't being passed. Do you get the same issue when you try with a native android example?

I haven't tried native android yet, I will try it with Camera2 soon.

Later, I used Camera Plugin (https://pub.dev/packages/camera) and found that the camera IDs obtained by availableCameras() only had two (one front lens and one back lens) instead of three.

**Comment by danagbemava-nc** [comment]
> Later, I used Camera Plugin ([pub.dev/packages/camera](https://pub.dev/packages/camera)) and found that the camera IDs obtained by availableCameras() only had two (one front lens and one back lens) instead of three.

This may be due to a similar reason as https://github.com/flutter/flutter/issues/134151

> I haven't tried native android yet, I will try it with Camera2 soon.

Please keep us updated

**Comment by jacky87218** [comment]
I tried Camera2 to get the lens information, but it also only has two lens.
As you mentioned, the native view isn't providing it.

I referred to a [stackoverflow](https://stackoverflow.com/questions/75884174/flutter-camera-choose-lens/75884506#75884506) article and directly passed parameters that were not in the list, and successfully obtained the lens information and initialized it.

Android Camera2：
```
CameraManager cameraManager = (CameraManager) activity.getSystemService(Context.CAMERA_SERVICE);
String[] cameraIds = cameraManager.getCameraIdList(); // print ["0", "1"]

CameraCharacteristics characteristics = cameraManager.getCameraCharacteristics("2");
```

Android Intent：
```
Intent intent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);
intent.putExtra("android.intent.extras.CAMERA_FACING", 2);
```

Of course, this method is not very good and needs to be customized for specific models of equipment.
And such initialization will not correct Len Distortion.

In addition, the method of initialization using Intent is not the zoom of x0.6, more like x0.9.
Currently, no common parameters related to optical zoom can be found.

**Comment by danagbemava-nc** [comment]
Hi @jacky87218, as you've noticed, there isn't much the image_picker plugin can do considering there isn't a unified way to access the extra cameras yet. It will lead to a lot of maintenance issues if we have to try to account for various android manufacturers and how they decide to setup their cameras. 

Unfortunately, I will have to close this as there isn't much we can do at this point. Feel free to revisit this when there's a unified way to access the extra cameras across android. 

Thank you
