### ISSUE TITLE
extendBody true makes GridView's height change

### ISSUE THREAD

**Issue by minhaeng** [flutter/flutter#140614]
### Steps to reproduce

1. make GridView.builder Widget
2. set Scaffold's property extendBody true 
3. GridView.builder height changed, it seems nearly one row of its item.

### Expected results

do not change GridView's height

### Actual results

GridView's height not changed

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

main() async {
  runApp(const MyApp());
}


class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  int _selectedIndex = 0;

  void _onItemTapped(int index) {
    setState(() {
      _selectedIndex = index;
    });
  }
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        bottomNavigationBar: BottomNavigationBar(
          items: const <BottomNavigationBarItem>[
            BottomNavigationBarItem(
              icon: Icon(Icons.home),
              label: 'Home',
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.business),
              label: 'Business',
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.school),
              label: 'School',
            ),
          ],
          currentIndex: _selectedIndex,
          selectedItemColor: Colors.amber[800],
          onTap: _onItemTapped,
        ),
        extendBody: true,
        body: SingleChildScrollView(
          child: Column(
            children: [
              Container(
                color: Colors.yellow,
                child: GridView.builder(
                  shrinkWrap: true,
                  itemCount: 30,
                  gridDelegate:
                  const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: 7),
                  itemBuilder: (context, index) {
                    return Text(index.toString());
                  },
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by moffatman** [comment]
Sorry what do you expect `extendBody: true` to do if not increase height of body?

**Comment by minhaeng** [comment]
I know that if i set `extendBody: true`, the scaffold body is increased. But what i expect is only to increase scaffold's body, not gridview's height. I want to use customized bottom navigation bar. But after i set 'extendBody: true', it changes gridview's height. Please refer to following image. One is set true, the other one is not.
![true](https://github.com/flutter/flutter/assets/94161447/5969ab24-b14d-4980-87a1-28ac08e63d1d)
![false](https://github.com/flutter/flutter/assets/94161447/b39357dd-556e-4e4c-ae0f-9aabd64b5d5f)

**Comment by moffatman** [comment]
Oh I see it now, the problem is the use of gridview for layout and not scrolling. You can fix it by setting `padding: EdgeInsets.zero,`  to the `GridView`. Then it will shrink to the proper size. GridView will automatically use ancestor `MediaQuery.padding` if `padding` is null so that scrollable content can be revealed from under the navigation bar.

**Comment by minhaeng** [comment]
@moffatman 
solved it! really thank you!! happy new year!

**Comment by moffatman** [comment]
Cheers np

**Comment by rickynguyenc** [comment]
> Oh I see it now, the problem is the use of gridview for layout and not scrolling. You can fix it by setting `padding: EdgeInsets.zero,` to the `GridView`. Then it will shrink to the proper size. GridView will automatically use ancestor `MediaQuery.padding` if `padding` is null so that scrollable content can be revealed from under the navigation bar.

Thank you so much. It work in GridviewBuilder too.
