### ISSUE TITLE
samsung s22 bug (freeze when opening the app showing the launcher icon)

### ISSUE THREAD

**Issue by muhammedelsepa3y** [flutter/flutter#140641]
### Steps to reproduce

The issue occurs on the Samsung S22 with the release version after deploying it to Google Play. I don't have the same device, but I tested the app with an S23, and it works correctly. When the client (S22) opens the app, the launcher icon freezes at the center of the screen, and the app does not open. However, on iOS and other Android devices, it works correctly.

The client's mobile information: Android version 13, One UI version 5.1.

### Expected results

The app should work correctly, like others.

### Actual results

It freezes on the splash screen and does not open.

### Code sample

<details open><summary>Code sample</summary>

```dart
class SplashScreen extends StatefulWidget {
  const SplashScreen({Key? key}) : super(key: key);

  @override
  State<SplashScreen> createState() => _SplashScreenState();
}

class _SplashScreenState extends State<SplashScreen> {
  late final Future getToken =
      Provider.of<DeskStorage>(context, listen: false).getToken();
  late final Future getAppLang =
      Provider.of<LocalizationsService>(context, listen: false)
          .getAppLanguage();

  late final Future getAllAuthData =
      Provider.of<DeskStorage>(context, listen: false)
          .getAllAuthenticatedData();

  late final Future getApplications =
      Provider.of<DeskStorage>(context, listen: false).getApplications();

  late final Future _udpateFCM =  Provider.of<APIService>(context, listen: false)
      .updateFCMTokenByFCM();


  Future<Widget> futureCall() async {
    final res = await getToken.then((token) async {
      await getAppLang;
      return await FirebaseFirestore.instance.collection('conf').doc('conf').get().then((value) async{
          if(value.data()!['backendVersion'] > backendVersion ){
            return Outdated();
          }else{
            if (token == null) {
              return Walkthrough();
            } else {
              await getAllAuthData;
              await _udpateFCM;
              Provider.of<HomeProvider>(context, listen: false).loadData(context);
              return Tabs();
            }
          }
      });



    });
    return Future.value(res);
  }

  @override
  Widget build(BuildContext context) {
    return EasySplashScreen(
      logo: Image.asset('assets/images/logo.png'),
      logoWidth: 312,
      showLoader: false,
      //navigator: Walkthrough(),
      futureNavigator: futureCall(),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![WhatsApp Image 2023-12-27 at 08 22 01_94e50430](https://github.com/flutter/flutter/assets/109048763/c5d32e52-321c-4ff5-a6b4-f53b17d925cc)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.2, on Microsoft Windows [Version 10.0.22631.2861], locale en-US)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.7.6)
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
[✓] VS Code (version 1.85.0)
[✓] Connected device (3 available)
[✓] Network resources
```

</details>

**Comment by dam-ease** [comment]
Thanks for filing this @muhammedelsepa3y.
This seems similar to https://github.com/flutter/flutter/issues/60576. Can you check this out?
Also, do you have any logs from this freeze in prod (from a monitoring service/platform)?

**Comment by muhammedelsepa3y** [comment]
@dam-ease  The issue is that the freeze occurs on another device installing the app from Google Play and I don't have logs for this device . Additionally, issue #60576 seems to involve the app not opening and showing only a black screen, whereas in my case, the launcher icon freezes in the center.

**Comment by muhammedelsepa3y** [comment]
> Thanks for filing this @muhammedelsepa3y. This seems similar to #60576. Can you check this out? Also, do you have any logs from this freeze in prod (from a monitoring service/platform)?

The issue is that the freeze occurs on another device installing the app from Google Play and I don't have logs for this device . Additionally, issue #60576 seems to involve the app not opening and showing only a black screen, whereas in my case, the launcher icon freezes in the center.

**Comment by dam-ease** [comment]
Thanks for your response.
From your code sample, I see you are making use of https://pub.dev/packages/easy_splash_screen which is a third-party package. This might not necessarily be an issue with flutter itself as I see similar issues in the repo https://github.com/imsujan276/EasySplashScreen/issues/2.
Can you follow up on this issue or file another in the appropriate repo?
