### ISSUE TITLE
Problem with the divider

### ISSUE THREAD

**Issue by RocksteadyDog** [flutter/flutter#140629]
### Steps to reproduce

Does the flutter app affect the behavior of other apps?

1) I open the unity remote app (in the app the status bar and navigation bar are hidden)

2A) If I minimize the unity remote app and open the default flutter app from desktop, minimize and go back to unity, if I look at the divider it is hidden....

2B) If I minimize the unity remote app and open the default flutter app from the app list, minimize and go back to unity, if I look at the divider it doesn't hide!

I recorded a video, watch the behavior of the divider for unity app.

Is it a problem with unity app, flutter app or android os?

### Expected results

unity app the divider should fade out

### Actual results

unity app the divider doesn't fade

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

https://github.com/flutter/flutter/assets/29661837/17001eee-c5da-4130-8a3b-4ef08ad78381

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.2.1 23C71 darwin-arm64, locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.85.1)
[✓] Connected device (2 available)            
[✓] Network resources

• No issues found!
```

</details>

**Comment by Digvijaysinh2204** [comment]
Once you provide a safe area to the scaffold

**Comment by Digvijaysinh2204** [comment]
Once you provide a safe area to the scaffold

**Comment by RocksteadyDog** [comment]
> Once you provide a safe area to the scaffold

Divider problem with another app (which is open at the same time as the flutter app)
Does the flutter app affect the behavior of other apps?

**Comment by gabrielgarciagava** [comment]
Have you tried same thing with other apps instead of the flutter one?

If one app affects another, that would be an OS issue, IMO.

By the way, that line is not called divider, it is called Home Indicator.

**Comment by RocksteadyDog** [comment]
> Have you tried same thing with other apps instead of the flutter one?
> 
> If one app affects another, that would be an OS issue, IMO.
> 
> By the way, that line is not called divider, it is called Home Indicator.

I tested, other applications (not flutter) affect the currently open application.  If I open the application from the desktop everything is ok, if I open it from the list of applications the home indicator does not fade out. This is not a flutter problem

**Comment by gabrielgarciagava** [comment]
Cool. You can close the issue then.
