### ISSUE TITLE
`flutter create` emits confusing language about caches unprompted

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#140628]
Version is `3.16.5` (stable):

```shell
$ flutter --version
Flutter 3.16.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 78666c8dc5 (7 days ago) • 2023-12-19 16:14:14 -0800
Engine • revision 3f3e560236
Tools • Dart 3.2.3 • DevTools 2.28.4
```

## Example

```shell
$ flutter create --empty --platforms macos my_app
Found an existing Pub cache at /Users/matan/.pub-cache.
It can be repaired by running `dart pub cache repair`.
It can be reset by running `dart pub cache clean`.
Found an existing Dart Analysis Server cache at /Users/matan/.dartServer.
It can be reset by deleting /Users/matan/.dartServer.
```

---

I have no idea what I'm supposed to be doing with this information, or why it was presented to me. Are my caches stale? What would lead me to wanting to repair or reset either of these caches?

**Comment by tanjy888** [comment]
删除系统换成，重新安装试一下。

**Comment by tanjy888** [comment]
what?

**Comment by dam-ease** [comment]
Hi @matanlurey.
Running this on my end works fine (logs below). Not sure the cause of yours but this could be IDEs or editors used not preventing editing plugin files and when navigating into plugin code, might accidentally modify the code.
Does repairing or resetting the `cache` solve this for you after running the commands?

<details><summary>Logs</summary>
<p>

```
flutter create --empty --platforms macos my_app
Creating project my_app...
Resolving dependencies in my_app... (2.1s)
Got dependencies in my_app.
Wrote 38 files.

All done!
You can find general documentation for Flutter at: https://docs.flutter.dev/
Detailed API documentation is available at: https://api.flutter.dev/
If you prefer video documentation, consider:
https://www.youtube.com/c/flutterdev

In order to run your empty application, type:

  $ cd my_app
  $ flutter run

Your empty application code is in my_app/lib/main.dart.
``` 

</p>
</details>

**Comment by christopherfujino** [comment]
https://github.com/flutter/flutter/pull/122592 links to an internal doc, although I suspect we'll need @sigurdm to clarify here--specifically, in what cases would the user need to/want to "repair" their pub cache? Ditto for resetting the dart analysis server cache?

**Comment by sigurdm** [comment]
I can try to give the context.

Flutter used to override the `$PUB_CACHE` to be `$FLUTTER_ROOT/.pub_cache` while dart defaults to have it in `~/.pub_cache` (on posix systems)

This override had two main reasons:

* Enable packing a pre-populated cache to enable a newly installed flutter to work offline on first run.
* Ensure that if you delete your Flutter SDK and reinstall you delete everything Flutter-related.

It had a number of downsides:

* General confusion around location of the PUB_CACHE.
* General desire to not have Flutter and Dart SDKs do different things!
* Inability to install Flutter SDK in an immutable location [pub/issues/1798](https://github.com/dart-lang/pub/issues/1798) (this is far from the only blocker)
* Prior to [flutter#105343](https://github.com/flutter/flutter/pull/105343) (not in stable yet) this could cause duplicate caches:
  * [flutter#37481](https://github.com/flutter/flutter/issues/37481), Flutter and Dart SDKs not interacting well.
  * [sdk#44944](https://github.com/dart-lang/sdk/issues/44944#issuecomment-778097559), Issues with dart pub global activate interacting poorly between multiple Dart/Flutter SDKs.
  * Duplication of downloads/storage (albeit this is probably a minor concern).
  * See also: [flutter#53833](https://github.com/flutter/flutter/issues/53833)
* Added complexity with [flutter#105343](https://github.com/flutter/flutter/pull/105343) (not in stable yet) we now have:
  * Path patterns for global cache locations duplicated in both pub and flutter code (a likely source of bugs in the future, if the global cache is moved, as could happen for [XDG base directory compliance](https://github.com/dart-lang/sdk/issues/41560)).
  * File I/O code moving files is fragile (non-atomic), increasing the risk that flutter_tools can break the PUB_CACHE.
  * To be fair, atomic file I/O is near impossible to reliably do on Windows.
  * Changing file writing patterns to extract in-place might alleviate issues on Windows, but we haven't done this in dart pub yet.
  * Having anyone but dart pub modifying files in PUB_CACHE is undesirable.

So it was decided to stop overriding $PUB_CACHE. But to accommodate the previous reasons for overriding we did:

* [prepackage](https://github.com/flutter/flutter/pull/121802) basic packages inside the flutter sdk, and install them on first run
* [show](https://github.com/flutter/flutter/pull/122592) this informational notice, such that users will know how to get rid of everything flutter if they want to.

Looking at it now - I don't know/remember why we only print a message when the pub cache already exists. It seems we should always write a message when we create/prepopulate the cache... @jonasfj do you see why? Is this just a mistake?

> In what cases would the user need to/want to "repair" their pub cache?

I guess if things get into a broken state you might want to repair (though I would suggest just deleting and running `pub get` again.)

> Ditto for resetting the dart analysis server cache?

I think that is mainly if you want to erase all flutter state from your system. We could probably improve the phrasing here.

**Comment by matanlurey** [comment]
The context is interesting, but doesn't seem to answer my question - why is this important to show users on `flutter create` by default? I could imagine (?) this going in `flutter doctor`, or perhaps `flutter create --verbose` (?), but I sort of interpret the current output as "something might be wrong" but without anything actionable to do.

**Comment by sigurdm** [comment]
> why is this important to show users on flutter create by default?

Not sure it is important. But if flutter create is the first command run, then it is the point in time where we create the pub-cache - and therefore (IMO) the most meaningful time to make the user aware of the existence of the folder if we want to.

I'm not married to this notification - the Dart SDK (without Flutter) just creates the pub cache implicitly - and noone has ever complained about that. But this was needed to make it acceptable to move the pub cache out of the flutter folder.

If we want to keep it, we could reformulate it to make it more clear that it is an informational notice, not a warning. I'm also happy to remove the warning entirely if that is OK with the Flutter folks.

@christopherfujino any opinion?

**Comment by jonasfj** [comment]
> I have no idea what I'm supposed to be doing with this information, or why it was presented to me. Are my caches stale? What would lead me to wanting to repair or reset either of these caches?

I think this is supposed to happen the first time you run `flutter` after having updated the SDK.

When Flutter moved from having a `PUB_CACHE` in `$FLUTTER_ROOT/.pub-cache` there was a large concern that:
Users would not be able to reset the state of the development machine by deleting the Flutter installation and installing the Flutter SDK from scratch.

To alleviate this concern a compromise was made:
Upon first run the Flutter SDK will display an informational message highlighting the location of existing caches that are being reused, and inform users how to repair/delete these caches.

I personally, think that `$PUB_CACHE` should be global by default and that Flutter shouldn't mess around with it. I think that we should ensure that `PUB_CACHE` remains compatible across SDK upgrades/downgrades (without breakages, we even recompiled globally activated packages on-demand).
I personally, do not think these messages are necessary.


But I do recognize that:
 * (A) Users might navigate into their `PUB_CACHE` using go-to definition and modify files.
 * (B) The Flutter SDK might have build processes that doesn't treat `PUB_CACHE` as read-only (maybe this has been fixed, it's a while since I played with plugins that use gradle).

And including these messages was what made a global `PUB_CACHE` viable to some stakeholders.
Because it gives you the hint that these caches exists and are reused. So if you installed the Flutter SDK to get a clean environment, you need to know that these caches exist and how to clean them.

**Comment by matanlurey** [comment]
Ran into this again today, side project:

```shell
flutter create rollforit --platforms android,macos --empty --org dev.lurey --description "A DM tool to help manage D&D encounters."
Found an existing Pub cache at /Users/matan/.pub-cache.
It can be repaired by running `dart pub cache repair`.
It can be reset by running `dart pub cache clean`.
Found an existing Dart Analysis Server cache at /Users/matan/.dartServer.
It can be reset by deleting /Users/matan/.dartServer.
```

@jonasfj:

> I personally, do not think these messages are necessary.

Who does? It sounds like me and you agree - is there a mythical third party that loves this message?

My 2c is if @christopherfujino also doesn't feel the need for it, I'll send you all a PR this week.

**Comment by christopherfujino** [comment]
> My 2c is if @christopherfujino also doesn't feel the need for it, I'll send you all a PR this week.

Unship it.

**Comment by jonasfj** [comment]
> Who does? It sounds like me and you agree - is there a mythical third party that loves this message?

@Hixie had strong opinions about deleting the Flutter SDK should clear all state. Which wasn't nice, so we compromised by making this notice message highlighting that old caches are present and they can be cleared or repaired.

We haven't seen many bugs about users with confused PUB_CACHE'es since this, and I don't recall issues with dirty caches either. But there could be things I didn't hear, or maybe this notice message had an impact.

**Comment by Hixie** [comment]
Since this information is most relevant when people are trying to debug an issue, I think it would make sense to report all the places we know about during `flutter doctor`, that way someone who is trying to clear out their state can just delete all the directories listed there.
