### ISSUE TITLE
`MaterialApp` Breaks `Navigator.pages`

### ISSUE THREAD

**Issue by caseycrogers** [flutter/flutter#140674]
### Steps to reproduce

1. Write a Nav 2 `Navigator` with multiple pages
2. Wrap it in `MaterialApp`
3. Add a page to the `Navigator`
4. Use the Android system back button/gesture

### Expected results

The top page pops

### Actual results

The app closes.

 Note: I'm fairly certain I saw a GH issue a long time ago for this and it contained a sloppy workaround using `WillPopScope`. I'm trying to migrate my workaround to use `PopScope` and I can't for the life of me find the original issue.

### Code sample

<details open><summary>Code sample</summary>

```dart
...
return MaterialApp(home: PagesDemo());
...

class PagesDemo extends StatefulWidget {
  const PagesDemo({super.key});

  @override
  State<PagesDemo> createState() => _PagesDemoState();
}

class _PagesDemoState extends State<PagesDemo> {
  bool showRed = false;

  @override
  Widget build(BuildContext context) {
    return Navigator(
      pages: [
        MaterialPage(
          child: Scaffold(
            appBar: AppBar(),
            backgroundColor: Colors.blue,
            floatingActionButton: FloatingActionButton(
              onPressed: () {
                setState(() {
                  showRed = true;
                });
              },
              child: const Icon(Icons.navigate_next),
            ),
          ),
        ),
        if (showRed)
          MaterialPage(
            child: Scaffold(
              appBar: AppBar(),
              backgroundColor: Colors.red,
            ),
          ),
      ],
      onPopPage: (route, result) {
        // This method never gets run on Android system back because `MaterialApp`
        // intercepts it and closes the app.
        if (!route.didPop(result)) {
          // Route handled the pop internally.
          return false;
        }
        if (showRed) {
          setState(() {
            showRed = false;
          });
        }
        return true;
      },
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by caseycrogers** [comment]
Thanks! The workaround in your first link worked.

Does the Flutter team have any interest in fixing this bug? The workaround is quite annoying and fairly hard to find.

**Comment by dam-ease** [comment]
Thanks for your response @caseycrogers.
Per this comment https://github.com/flutter/flutter/issues/140296#issuecomment-1859338208, it seems to be a known issue hence not certain if there are plans to fix this.
Are you open to filing a proposal for a change in this behaviour?
