### ISSUE TITLE
my iphone shutdown when download app

### ISSUE THREAD

**Issue by hhyq520520** [flutter/flutter#140634]
### Steps to reproduce

when I download ios app and install on my phone,my 16.3 iphone shutdown and restart,sometimes happen . other time install normal.
I can't find any logs. anyone could help me?

### Expected results

install normal

### Actual results

install normal

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.16.3, on macOS 13.4 22F66 darwin-x64, locale zh-Hans-CN)
    ! Warning: `dart` on your path resolves to /usr/local/Cellar/dart/2.18.2/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/fargowealth/fvm/versions/3.16.3. Consider adding /Users/fargowealth/fvm/versions/3.16.3/bin to the front of your path.
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2022.2)
[✓] Connected device (2 available)
[✓] Network resources
```
</details>

**Comment by danagbemava-nc** [comment]
Hi @hhyq520520, do you have this same issue with the counter app? 

Can you share a screen recording of the issue? 

Can you also navigate to your analytics data in your iPhone settings to see if you can find any crash/records related to your app?

You can find the analytics data for most apps on your iPhone by going to `Settings > Privacy & Security > Analyics & Improvements > Analytics Data`
