### ISSUE TITLE
flutter clean not working

### ISSUE THREAD

**Issue by deepak-gehlot** [flutter/flutter#14067]
## Steps to Reproduce

```
E:\fluter\flutter_firebase>flutter clean
Deleting 'build\'.
FileSystemException: Deletion failed, path = 'build' (OS Error: The system cannot find the path specified.
, errno = 3)
```

## Logs
```
Deleting 'build\'.
FileSystemException: Deletion failed, path = 'build' (OS Error: The system cannot find the path specified.
, errno = 3)
```
## Flutter Doctor
```
E:\fluter\flutter_firebase>flutter doctor
[√] Flutter (on Microsoft Windows [Version 6.3.9600], locale en-US, channel alpha)
    • Flutter at E:\fluter\flutter
    • Framework revision 8f65fec5f5 (4 weeks ago), 2017-12-12 09:50:14 -0800
    • Engine revision edaecdc8b8
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.d8ae797298c3a6cf8dc9f4558707bd2672224d3e

[√] Android toolchain - develop for Android devices (Android SDK 27.0.2)
    • Android SDK at D:\setup\sdk\sdk
    • Android NDK at D:\setup\sdk\sdk\ndk-bundle
    • Platform android-27, build-tools 27.0.2
    • ANDROID_HOME = D:\setup\sdk\sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[-] Android Studio (version 1.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Connected devices
    • Moto E 4 Plus • ZH33L2FD7H • android-arm • Android 7.1.1 (API 25)
```

**Comment by mit-mit** [comment]
Can't repro on Windows with flutter master:

```
C:\Users\mit>flutter create cleanme
C:\Users\mit>cd cleanme
C:\Users\mit\cleanme>flutter build apk
Initializing gradle...                                2.7s
Resolving dependencies...                            76.3s
Running 'gradlew assembleRelease'...
Skipping AOT snapshot build. Fingerprint match.
Built build\app\outputs\apk\release\app-release.apk (7.5MB).

C:\Users\mit\cleanme>flutter clean
Deleting 'build\'.
```

cc @goderbauer any ideas?

**Comment by goderbauer** [comment]
`clean` works as expected on my Windows system.

@deepak-gehlot Do you see this error every single time you execute `flutter clean` in a flutter project? Or was this just a one-off?

**Comment by deepak-gehlot** [comment]
Yes i see this in every single execution

**Comment by mit-mit** [comment]
Can youshare the full output of `flutter -v clean', please?

**Comment by nodejs-practice** [comment]
Not OP, but I did get the same issue. Here's the output from flutter -v clean

flutter clean
Deleting 'build/'.
FileSystemException: Deletion failed, path = 'build' (OS Error: Directory not empty, errno = 39)
vijay@akrivia:~/apps/proma$ flutter -v clean
[ +604 ms] [/home/vijay/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +19 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] [/home/vijay/flutter/] git rev-parse --abbrev-ref HEAD
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[        ] [/home/vijay/flutter/] git ls-remote --get-url origin
[   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] [/home/vijay/flutter/] git log -n 1 --pretty=format:%H
[   +3 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 12bbaba9ae044d0ea77da4dd5e4db15eed403f09
[        ] [/home/vijay/flutter/] git log -n 1 --pretty=format:%ar
[   +3 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 2 weeks ago
[        ] [/home/vijay/flutter/] git describe --match v*.*.* --first-parent --long --tags
[   +4 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.3.1-0-g12bbaba9a
[ +543 ms] Deleting 'build/'.
[+2297 ms] "flutter clean" took 2,815ms.
FileSystemException: Deletion failed, path = 'build' (OS Error: Directory not empty, errno = 39)

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28)
#1      CleanCommand.runCommand (package:flutter_tools/src/commands/clean.dart:35)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:333)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:270)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1126)
#6      _CustomZone.run (dart:async/zone.dart:1023)
#7      runZoned (dart:async/zone.dart:1501)
#8      AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#9      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:261)
#10     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:309)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#13     _rootRun (dart:async/zone.dart:1126)
#14     _CustomZone.run (dart:async/zone.dart:1023)
#15     runZoned (dart:async/zone.dart:1501)
#16     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:265)
<asynchronous suspension>
#18     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#19     new Future.sync (dart:async/future.dart:224)
#20     CommandRunner.run (package:args/command_runner.dart:109)
#21     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:174)
#22     run.<anonymous closure> (package:flutter_tools/runner.dart:54)
<asynchronous suspension>
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#24     _rootRun (dart:async/zone.dart:1126)
#25     _CustomZone.run (dart:async/zone.dart:1023)
#26     runZoned (dart:async/zone.dart:1501)
#27     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#28     runInContext (package:flutter_tools/src/context_runner.dart:41)
<asynchronous suspension>
#29     run (package:flutter_tools/runner.dart:49)
#30     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#31     main (file:///b/build/slave/Linux_Flutter_Packaging/build/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#32     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
`

**Comment by zoechi** [comment]
@nodejs-practice can you please post the output of `flutter doctor -v`?

**Comment by shinayser** [comment]
I was having this problem right now. The problem was that my build.gradle was changing the target folder for builds.

I had this on my project's build.gradle:
`rootProject.buildDir = '../build'`

Change to this:
`rootProject.buildDir = '/build'`

Now works properly.

**Comment by fritz-playmaker** [comment]
> @nodejs-practice can you please post the output of `flutter doctor -v`?

Facing the same issue right now

this is my output for `flutter doctor -v`

`[√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 10.0.17134.472], locale en-US)
    • Flutter version 1.0.0 at C:\flutter_sdk\flutter
    • Framework revision 5391447fae (6 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\DELL XPS 1215\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code (version 1.30.1)
    • VS Code at C:\Users\DELL XPS 1215\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.21.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.`

**Comment by zoechi** [comment]
@fritz-playmaker 

> Facing the same issue right now

Please post the exact error output.

**Comment by zoechi** [comment]
The error message is different. 
I guess this is caused by an AntiVirus software that keeps a file open.
Try deleting the `build/` directory manually.

**Comment by fritz-playmaker** [comment]
> The error message is different.
> I guess this is caused by an AntiVirus software that keeps a file open.
> Try deleting the `build/` directory manually.

Deleting it manually works, so are you suggesting that Windows Defender is the cause?

**Comment by zoechi** [comment]
Perhaps you can exclude the directory for Windows Defender.
It also might be another application that holds a file open in this directory.

**Comment by fritz-playmaker** [comment]
and how do i exclude the directory for Windows Defender? :)

**Comment by zoechi** [comment]
Sorry, can't provide Windows Defender support.

**Comment by Eberewill** [comment]
> I was having this problem right now. The problem was that my build.gradle was changing the target folder for builds.
> 
> I had this on my project's build.gradle:
> `rootProject.buildDir = '../build'`
> 
> Change to this:
> `rootProject.buildDir = '/build'`
> 
> Now works properly

this solution worked for me

**Comment by sukhcha-in** [comment]
I was running a program that was using files from my project, so flutter was not able to delete the files for cleaning. I terminated that program and it worked. :)

**Comment by cntoss** [comment]
> I was running a program that was using files from my project, so flutter was not able to delete the files for cleaning. I terminated that program and it worked. :)

this also work on me

**Comment by ArnantoRizki** [comment]
move the project to another path that have shorter character. It works for me

**Comment by kvt0012** [comment]
Run it with administrator, it works for me

**Comment by mirxtrem-apps** [comment]
i had the same problem, and fix close file explorer. this happend y windows and macOs.

I had not program using folder exactly but i had the file explorer open just with the project folder hightlighted and that is enough to dont leave erase.
