### ISSUE TITLE
Easier setup for infrequent developers

### ISSUE THREAD

**Issue by NobodyForNothing** [flutter/flutter#140602]
### Use case

Starting with Flutter is currently not very straightforward. The framework and tools are not small enough and the way setting up paths works is not very intuitive. This results in long installation times and some perceived roadblocks that are disheartening.

In many open-source projects users with a little developing knowledge implement features that they want. I have had the experience that multiple potential contributors didn't contribute because they had issues installing Flutter that they just didn't care to dig into.

Another group of developers that are impacted by this are developers coming from other platforms who want to add/modify platform-dependent code (e.g. adaptive icons, supported environments, ...) and are not able to test changes themselves because the build still requires the whole SDK.

### Proposal

I understand that the current installation method provides lots of control over the Dart and Flutter SDK and comes with lots of build and debug tools that are required for professional developers and edge cases.
This leads me to believe a separate "Flutter light" tool that has minimal functionality (build), packed into a single executable would be more appropriate than changing the whole toolchain.

This is a very rough sketch and someone more familiar with the tooling likely has a better idea of what is required for a build and how feasible this is.

**Comment by stuartmorgan** [comment]
Everything in the installation process is required for building, so there is no viable "light" installation for the described use case. Closing as infeasible.
