### ISSUE TITLE
"video_player" does not support 'video/avc' format

### ISSUE THREAD

**Issue by Bonnenuit0** [flutter/flutter#140617]
PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(2, null, null, video/avc, avc1.6E000D, 1240800, null, [202, 360, -1.0], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES, null, null)

Forexample: https://video.591.com.tw/online/target/house/hls/2023-12-14/616865/master.m3u8

**Comment by stuartmorgan** [comment]
Please see https://pub.dev/packages/video_player#supported-formats

Closing as the plugin does not control the supported formats.
