### ISSUE TITLE
Bad state: Cannot clone a disposed image

### ISSUE THREAD

**Issue by escamoteur** [flutter/flutter#140789]
### Steps to reproduce

Unfortunately we don't know yet what triggers this error, we only got a bug report which tools use that the user only sees a black screen when he resumes to the app and has to restart the app in sentry we see only this stack trace:

![grafik](https://github.com/flutter/flutter/assets/16635729/ae7f7766-a736-4dbe-a505-29dce0127fe2)

if there is anything that we could add to our app's code to get more details, please let me know

### Expected results

no exception

### Actual results

Black screen with exception in Senty

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

We build the release with CodeMagic with version `== Use Flutter version 3.13.4 ==`

**Comment by dam-ease** [comment]
Hello @escamoteur.
Are you making use of [cached_network_image](https://pub.dev/packages/cached_network_image ) package in your project?

**Comment by kekland** [comment]
@escamoteur @dam-ease seems to be happening in the `flutter_blurhash` package. The error started occuring when blurhash was added into the app. There's also a similar issue in https://github.com/fluttercommunity/flutter_blurhash/issues/40 and https://github.com/fluttercommunity/flutter_blurhash/issues/46. 

I think this issue can be closed, as it's not related to Flutter itself, but is something that has to do with blurhashes.

**Comment by felipecastrosales** [comment]
@kekland Can you suggest something for us to investigate in the package? I've checked the implementation a few times and haven't seen anything suspicious.

> @escamoteur @dam-ease seems to be happening in the `flutter_blurhash` package. The error started occuring when blurhash was added into the app. There's also a similar issue in [fluttercommunity/flutter_blurhash#40](https://github.com/fluttercommunity/flutter_blurhash/issues/40) and [fluttercommunity/flutter_blurhash#46](https://github.com/fluttercommunity/flutter_blurhash/issues/46).
> 
> I think this issue can be closed, as it's not related to Flutter itself, but is something that has to do with blurhashes.
