### ISSUE TITLE
Passing Data in popUntil metgos same like we pass data in pop.

### ISSUE THREAD

**Issue by amit-flutter** [flutter/flutter#140723]
### Use case

there is one situation where the user navigates to a nested page but **wants to update the main page** or previous pages then we use **pop until** method to navigate to a specific page in the tree. that time, we need to get value from the inner page. so there is no **simple way to pass it directly like in the pop method.**

### Proposal

So i request to make a simple way to pass data in the popUntil method while navigating to a specific page in tree. Reference will be a pop method of navigation.

**Comment by huycozy** [comment]
Hi @amit-flutter 
This is a known issue being tracked at https://github.com/flutter/flutter/issues/30112. Closing this issue as a duplicate, so please follow up on it for further updates.
