### ISSUE TITLE
Add iOS support for Google Maps zoom controls

### ISSUE THREAD

**Issue by carmenchargely** [flutter/flutter#140741]
### Steps to reproduce

When implementing Google Maps, the zoom buttons appear on Android but not iOS. 

See this thread for more detail:
https://github.com/FlutterFlow/flutterflow-issues/issues/900

### Expected results

The expected result is for the Google Maps zoom +/- buttons to appear on both Android and iOS. 

### Actual results

The Google Maps zoom +/- buttons do not appear on iOS. You can double tap to zoom on iOS, but we can't expect users to know how to do that.

### Code sample

In the latest `google_maps_flutter` package

<summary>Code sample</summary>
```
  /// True if the map view should show zoom controls. This includes two buttons
  /// to zoom in and zoom out. The default value is to show zoom controls.
  ///
  /// This is only supported on Android. And this field is silently ignored on iOS.
  final bool zoomControlsEnabled;
```

### Screenshots or Video

<summary>Video demonstration</summary>

Google Maps zoom working on Android:
https://github.com/FlutterFlow/flutterflow-issues/assets/136000563/d7b87e3a-f3a0-475e-be0e-6d418ff2c166

Google Maps zoom buttons not appearing on iOS:
https://github.com/FlutterFlow/flutterflow-issues/assets/136000563/d29f5f54-5422-4eeb-b06c-c71d989a4269

### Logs

For more details: https://github.com/FlutterFlow/flutterflow-issues/issues/900

### Flutter Doctor output

For more details: https://github.com/FlutterFlow/flutterflow-issues/issues/900

**Comment by stuartmorgan** [comment]
There are no such controls on iOS: https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_u_i_settings

Closing as we don't add UI in the plugin, we just wrap the SDK. Clients who want UI that the Google Maps SDK doesn't provide are welcome to implement it themselves in whatever style they prefer.
