### ISSUE TITLE
File.copySync() run in separate isolate somehow causes UI thread to churn

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#140763]
## Steps to reproduce

Run the following app:

```dart
import 'dart:io' as io;
import 'dart:isolate';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(
    const MaterialApp(
      title: 'Issue reproduction',
      home: IssueApp(
        numCopiesToMake: 30,
        fileSize: 1024 * 1024 * 1024, // 1GB
      ),
    ),
  );
}

class IssueApp extends StatefulWidget {
  const IssueApp({
    super.key,
    required this.numCopiesToMake,
    required this.fileSize,
  });

  final int numCopiesToMake;
  final int fileSize;

  @override
  State<IssueApp> createState() => _IssueAppState();
}

class _IssueAppState extends State<IssueApp> {
  static Future<int> _copyLargeFileNTimes(_Message message) async {
    // The isolate name here should show that we're not running in the UI thread.
    print('Copying large file ${message.numCopiesToMake} times in isolate "${Isolate.current.debugName}"');

    final io.Directory tmpDir = io.Directory.systemTemp.createTempSync('dart_issue_');
    try {
      final String separator = io.Platform.isWindows ? r'\' : '/';

      // Create a file to serve as a template
      io.File templateFile = io.File('${tmpDir.path}${separator}template');
      templateFile.writeAsBytesSync(List<int>.generate(message.fileSize, (int i) => i % 0xff));
      print('done creating template file; starting to make copies');

      for (int i = 0; i < message.numCopiesToMake; i++) {
        io.File iter = io.File('${tmpDir.path}${separator}copy_$i');
        templateFile.copySync(iter.path);
      }

      return message.numCopiesToMake;
    } finally {
      tmpDir.deleteSync(recursive: true);
    }
  }

  @override
  void initState() {
    super.initState();
    () async {
      int n = await compute<_Message, int>(_copyLargeFileNTimes, _Message(widget.numCopiesToMake, widget.fileSize));
      print('copied file $n times');
    }();
  }

  @override
  Widget build(BuildContext context) => const Center(child: CircularProgressIndicator());
}

class _Message {
  const _Message(
    this.numCopiesToMake,
    this.fileSize,
  );

  final int numCopiesToMake;
  final int fileSize;
}
```

## Expected behavior

Since the work is done in a worker isolate, you expect the progress indicator to keep spinning at 60fps the entire time.

## Actual behavior

After you see the "done creating template file; starting to make copies" message in the logs, the frame rate of the app drops substantially as you can see in the progress indicator animation.

## Diagnosis

The UI thread is somehow getting involved in the I/O work that's being done in the separate isolate.

## Info

```
$ flutter doctor -v
[✓] Flutter (Channel main, 3.18.0-18.0.pre.46, on macOS 14.1 23B2073 darwin-arm64, locale en-US)
    • Flutter version 3.18.0-18.0.pre.46 on channel main at /Users/tvolkert/project/flutter/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision 7c9c1705e8 (2 days ago), 2023-12-29 07:40:37 -0500
    • Engine revision ea4fb2cb94
    • Dart version 3.3.0 (build 3.3.0-272.0.dev)
    • DevTools version 2.31.0-dev.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/tvolkert/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.85.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0
```

**Comment by jonahwilliams** [comment]
If you use the tracer on https://perfetto.dev/, you can see what Cores are being assigned to what work. My guess is its something similar to https://github.com/flutter/flutter/issues/135443 where your background isolate is getting scheduled on the fast core and kicking the UI or raster thread off to a slow core.

**Comment by jonahwilliams** [comment]
@tvolkert I'm guessing this is running on an Android device? perhaps your big old TV?

**Comment by tvolkert** [comment]
Nope this was on macOS desktop with an M3 max chip and 64GB RAM.

**Comment by jonahwilliams** [comment]
Interesting! In that case I'd probably be interested to see what exactly was happening on the UI thread. We have some instructions for getting flame graphs here: 

https://github.com/flutter/engine/blob/main/impeller/docs/ios_cpu_profile.md

Might potentially be a dart:io issue

**Comment by zanderso** [comment]
I'd suspect a GC issue. Lightweight isolates cooperate on GC. If you have one Isolate make a huge allocation and then block the thread on long running synchronous IO operations, it may be failing to cooperate on GC with the UI isolate, causing weird GC behavior on the UI thread. I'm curious what happens if you change the `copySync()` to an `await copy()`. That will run the copy on a third thread, which should leave the helper Isolate thread available to cooperate with the UI thread on GC, which might remove any pathological behavior.

**Comment by zanderso** [comment]
Took a look at a timeline:

![copySync_notifyIdle_stall](https://github.com/flutter/flutter/assets/6343103/a15b3abb-0114-4a47-bebf-9bab09790c85)

It looks like `Dart_NotifyIdle` is triggering a new gen collection on the UI thread, which is failing to synchronize with the worker isolate while it's blocked on the copy call.

Changing to the async version of the copy call as I suggested above avoids the animation stalls. Unfortunately, it seems like an Isolate in an Isolate group doing blocking I/O might need some extra consideration in the interaction between `Dart_NotifyIdle` and new gen GC synchronization? @rmacnak-google may have ideas here.

**Comment by rmacnak-google** [comment]
This is surprising. A native like `File_Copy` should already be at a safepoint during the actual I/O, and a GC should not need to wait for it.

**Comment by zanderso** [comment]
@rmacnak-google any thoughts on next steps for tacking this down?

**Comment by zanderso** [comment]
Oh, I see it's this? https://github.com/dart-lang/sdk/commit/fa7cadde8038873c07fb3b68f4812393403135b3

**Comment by rmacnak-google** [comment]
The issue was with the I/O operations rather than NotifyIdle.
