### ISSUE TITLE
flutter web deployment problem

### ISSUE THREAD

**Issue by longfit** [flutter/flutter#140786]
### Steps to reproduce

package mainly 
dio
go_router 
fluent_ui

I have created a web page item shown information successfully ,No matter run in debugger mode or 
at deployment at the nginx server.

I have enhanced login Page and make it go_router (redirect)
http://192.168.3.207:8100/api/user/login

flutter run -d web-server --web-port 8088 --web-hostname 8088
or
run in the debugger is working properly

But After deployment  to my Nginx web server  and node express db middle server at same machine
the Flutter Web cannot respond when I press login button

                                                              flutter run                                             nginx
         website page                          working properly                                working properly 
                                
        website page + login             working properly                                   only show login page

        

### Expected results

Successfully login and go to main page

at development flutter run

[Screencast from 2024-01-02 12-18-27.webm](https://github.com/flutter/flutter/assets/4157794/f94670e8-9cd9-44c5-b659-5075f395e142)

### Actual results

Flutter web only shown login page and no reponse when I click the login page at live nginx server web

![Screenshot from 2024-01-02 12-19-46](https://github.com/flutter/flutter/assets/4157794/291ea068-2a0a-44f9-9232-477e6edaa55b)

press button no repsonse

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Screencast from 2024-01-02 12-18-27.webm](https://github.com/flutter/flutter/assets/4157794/96f6a893-628a-4606-8558-dd7e92421505)

</details>

It can flutter web propery at flutter run -d web-server --web-port 8088 --web-hostname 8088

### Logs

<details open><summary>Details</summary>
<p>

```
warning one

  flutter.js:362 Exception while loading service worker: Error: Service Worker API unavailable.

The current context is NOT secure.
Read more: https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts
    at FlutterServiceWorkerLoader.loadServiceWorker (flutter.js:130:11)
    at FlutterLoader.loadEntrypoint (flutter.js:360:33)
    at (index):51:2


warning 2

    developer_patch.dart:88 registerExtension() from dart:developer is only supported in build/run/test environments where the developer event method hooks have been set by package:dwds v11.1.0 or higher.


error 3


Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
  
``` 

</p>
</details> 

### Flutter Doctor output

<details open><summary>Details</summary>
<p>

```console
 flutter doctor -v
[✓] Flutter (Channel stable, 3.16.5, on Ubuntu 23.10 6.5.0-14-generic, locale
    en_US.UTF-8)
    • Flutter version 3.16.5 on channel stable at /home/ykwings/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (13 days ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/ykwings/android-sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /home/ykwings/android-sdk
    • Java binary at: /home/ykwings/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 16.0.6 (15)
    • cmake version 3.27.4
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[✓] Android Studio (version 2023.1)
    • Android Studio at /home/ykwings/android-studio
    • Flutter plugin version 77.1.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.85.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.80.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 23.10 6.5.0-14-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.129

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</p>
</details>

**Comment by dam-ease** [comment]
Thanks for filing this @longfit.
Deploying web using the default counter app through the following steps:

```
- flutter build web
- cd build/web
- python3 -m http.server 8000
- ~/ngrok http 8000
``` 
I can't seem to reproduce the problem on my end. Can you try this out on your end as well?
If it does, we will need you to provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so we can triage this properly.

Thank you
