### ISSUE TITLE
[CP] Fix blurriness issue with single GL context rendering

### ISSUE THREAD

**Issue by harryterkelsen** [flutter/flutter#140715]
### Issue Link

https://github.com/flutter/flutter/issues/122541

### Target

stable

### PR Link

https://github.com/flutter/engine/pull/49418

### Changelog Description

This change fixed a bug with blurry rendering in CanvasKit after resizing, as well as many other bugs. The main issue hitting stable branch users is the blurriness bug.

### Impacted Users

All end-customers

### Impact Description

Blurriness after resizing.

### Workaround

Refresh after resizing.

### Risk

low

### Test Coverage

yes

### Validation Steps

Build a web app with the fix applied and resize the app to be larger and verify that it doesn't become blurry.

**Comment by CaseyHillers** [comment]
@yjbanov can you review this CP request? If it looks good to you, add the "cp: approved" label.

**Comment by yjbanov** [comment]
This is too risky to cherry pick for now due to reports of slowness in Firefox and Safari. @harryterkelsen is working on a fix, but I think it's OK to wait for the next release.

**Comment by yjbanov** [comment]
Chatted with @harryterkelsen offline. Closing this cherry pick for now.
