### ISSUE TITLE
[Stepper] Customizable circle margin

### ISSUE THREAD

**Issue by amramer522** [flutter/flutter#140770]
### Use case

```dart
Widget _buildCircle(int index, bool oldState) {
    return Container(
      margin: const EdgeInsets.symmetric(vertical: 8.0),
      width: _kStepSize,
      height: _kStepSize,
      child: AnimatedContainer(
        curve: Curves.fastOutSlowIn,
        duration: kThemeAnimationDuration,
        decoration: BoxDecoration(
          color: _circleColor(index),
          shape: BoxShape.circle,
        ),
        child: Center(
          child: _buildCircleChild(index, oldState && widget.steps[index].state == StepState.error),
        ),
      ),
    );
  }
```

this is the code for building the circle of the stepper the margin is const. It should be dynamic to change by the developer.

also the size of the circle of the step we need to change it size to match our designs.
const double _kStepSize = 24.0;

### Proposal

we need to pass it form the step or stepper 

also we need to make every step open feature to be not only one step opened

**Comment by MohamedElarabi** [comment]
I have the same problem with this widget in old project and I replaced it with a package.
thank you for opening this issue

**Comment by khaledelsherbiny** [comment]
the same with me

**Comment by a7-monir** [comment]
thanks for opening this issue.

**Comment by sharabiddin** [comment]
@amramer522  Please provide minimum code sample to produce the issue

**Comment by amramer522** [comment]
I provide it in the use case this the code in the stepper widget

**Comment by huycozy** [comment]
Hi everyone,

>also the size of the circle of the step we need to change it size to match our designs.
const double _kStepSize = 24.0;

This is a known issue being tracked at https://github.com/flutter/flutter/issues/103124 so please follow up on it for further updates.

Labeling this issue as a separated proposal for `Customizable circle margin`.
