### ISSUE TITLE
Meta? Flutter examples are too complicated

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#140707]
I'm not sure if this is Meta or not, but I've noticed that Flutter examples in the docs and in official plugins are incredibly verbose and include a lot of code that has nothing to do with the task at hand.

Example 1.  
https://pub.dartlang.org/packages/video_player#-example-tab-

So it's cool that we have a complete implementation, but I would personally benefit much more from "load video," "play video", "pause video," "load new video" examples. (I find this to be in huge contrast to what I have seen from the JS community, where they treat every second of someones time as extremely valuable.)

Contrast to this: https://www.npmjs.com/package/react-native-video-processing#usage

Example 2.  
https://docs.flutter.io/flutter/rendering/CustomPainter-class.html

This appears to have semantics wrapped into a tutorial about CustomPainter. I'm not sure why. It may be best practices, but that would be a side note, not a core part of the tutorial.

Contrast to this: https://www.npmjs.com/package/react-native-canvas

**Comment by atsansone** [comment]
The examples cited are for the API docs and pub.dev. Neither of which are covered in the documentation. Please review and prioritize as appropriate.

**Comment by danagbemava-nc** [comment]
Hi @lukepighetti, is this still relevant today? The docs for video player seems to have changed, and it might be the same for the CustomPainter class, but I'm not sure what it looked like when this issue was filed/
