### ISSUE TITLE
Extract modal bottom action sheet concept from Material to Widgets

### ISSUE THREAD

**Issue by xster** [flutter/flutter#14076]
There are multiple Cupertino concepts of a modal dismissable action sheet at the bottom of the screen too such as 
https://developer.apple.com/ios/human-interface-guidelines/views/action-sheets/ and https://developer.apple.com/ios/human-interface-guidelines/controls/pickers/. The current showModalBottomSheet helper mechanism is in bottom_sheet.dart and has a lot of Material concepts baked in. Extract into common utility.

**Comment by ics042** [comment]
@xster , can we wrapper `CupertinoPageScaffold` in `Scaffold` as a workaround solution until above extract be implemented?
```
@override
  Widget build(BuildContext context) {
    return Scaffold(
      body: CupertinoPageScaffold(
          navigationBar: CupertinoNavigationBar(
            middle: Column(
              children: <Widget>[
                Text("Hello Flutter"),
                Text("yes, it is")
              ],
            ),
            trailing: IconButton(
              icon: Icon(Icons.more_horiz), 
              onPressed: () {
                showModalBottomSheet<Null>(context: context, builder: (BuildContext context) {
                  return new Container(
                      child: new Padding(
                          padding: const EdgeInsets.all(32.0),
                          child: Text("Hello World"),
                      )
                  );
                });
              },),
          ),
          child: Center(child: Text("Hello World"),)),
    );
  }
```

**Comment by xster** [comment]
As a temporary workaround, sure. I don't see any issues.

**Comment by ics042** [comment]
Cheers, thank you very much.

**Comment by xster** [comment]
Discussed offline. We're not going to extract this from Material. Instead, we'll create a showCupertinoBottomSheet as a popup route in #7376
