### ISSUE TITLE
mason make shows error after answering questions

### ISSUE THREAD

**Issue by codemenorg** [flutter/flutter#140729]
### Steps to reproduce

1. mason add -g flutter_news_template
2. mason make flutter_news_template

### Actual results

Mismatched tag, expected: 'snakeCase', was: '{{#snakeCase' (1:95)
.../src/client/{{#snakeCase}}{{project_name}}{{/{{#snakeCase}}_api_client.dart

### Logs

```
mason make flutter_news_template                                                                                                                                            ─╯
? What is the user-facing application name? (Daily Globe) Khulna News
? What is the application bundle identifier? (com.google.news.template) com.codemen.khulnanews
? Who are the code owners? (e.g. @user1 @user2) @golamrabbi3
? What flavors do you want your application to include? [development, production]
✗ Making flutter_news_template (0.9s)
Mismatched tag, expected: 'snakeCase', was: '{{#snakeCase' (1:95)
.../src/client/{{#snakeCase}}{{project_name}}{{/{{#snakeCase}}_api_client.dart

``` 

### Flutter Doctor output

flutter doctor                                                                                                                                                              
```
─╯
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.2.1 23C71 darwin-arm64, locale en-BD)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.85.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!


```

**Comment by ditman** [comment]
The code that seems to be generating that file/path is here: 

* https://github.com/flutter/news_toolkit/blob/698dd8ffde0e9db2914f8cd1b67611a742ef4cd1/tool/generator/main.dart#L336-L352

**Comment by codemenorg** [comment]
> Thanks for filing this @codemenorg. This is similar to #139866. Tried reproducing this and I'm able to reproduce, the workaround here [#139866 (comment)](https://github.com/flutter/flutter/issues/139866#issuecomment-1849101605) worked fine in my case, kindly try this out as well. Not certain but this might be an actual issue with getting started with the flutter_news_template. Labelling this for more insights.
> flutter doctor -v

The following generated the code for me after changing file name from - 

`/Users/{{user}}/.mason-cache/hosted/registry.brickhub.dev/flutter_news_template_1.0.7/__brick__/{{project_name.snakeCase()}}/api/lib/src/client/{{#snakeCase}}{{project_name}}{{`

to 

`/Users/{{user}}/.mason-cache/hosted/registry.brickhub.dev/flutter_news_template_1.0.7/__brick__/{{project_name.snakeCase()}}/api/lib/src/client/{{project_name.snakeCase()}}/{{project_name.snakeCase()}}_api_client.dart`

Not sure it would cause other error or not in the project.

**Comment by jmagman** [comment]
cc @MacarenaSantos  @zoeyfan the app is not generate-able (at least on macOS) following the instructions at https://flutter.github.io/news_toolkit/#generate-the-app.  The code @ditman points out has been present for 2 years, did this ever work on macOS?

See https://github.com/flutter/flutter/issues/139866 for more context.

**Comment by ditman** [comment]
A fix I'd try is to rename the filename that seems to be breaking the build ([this one, I think](https://github.com/flutter/news_toolkit/blob/698dd8ffde0e9db2914f8cd1b67611a742ef4cd1/flutter_news_example/api/lib/src/client/flutter_news_example_api_client.dart)) to something that doesn't contain the name of the app (try to call it `news_api_client.dart` or similar), so it doesn't hit those file renaming shenanigans :)

(That doesn't answer @jmagman's questions though)

**Comment by zoeyfan** [comment]
I remembered that this was working fine on MacOS in the past, so I wonder if there has been some recent changes with Mason. Anyway, @MacarenaSantos would you please also pass this to the team? It is concerning given we have received quite a few issues on this one now.

**Comment by elianortega** [comment]
I wanted to use the news toolkit and got the same error message:
```
✓ Compiled pre_gen.dart (2.4s)
✗ Making flutter_news_template (0.6s)
Mismatched tag, expected: 'snakeCase', was: '{{#snakeCase' (1:95)
.../src/client/{{#snakeCase}}{{project_name}}{{/{{#snakeCase}}_api_client.dart
```

I tried installing older versions of mason without luck, maybe @felangel has an idea of what could be happening here? Specially because that code hasn't changed in a long time.

**Comment by zoeyfan** [comment]
Thanks for the additional information. I have notified the team to look into this, and they will be prioritizing this issue immediately.

**Comment by valentinallavayol** [comment]
Version 1.0.8 of the toolkit is published with the fix for this error! Run `mason add -g flutter_news_template 1.0.8` to download the new version.

**Comment by valentinallavayol** [comment]
Closing the issue since it was resolved.
