### ISSUE TITLE
[video_player]When I loop a local file mp4 video on iOS, the memory increase very fast

### ISSUE THREAD

**Issue by NamHofstadter** [flutter/flutter#140732]
### Steps to reproduce

I loop a local mp4 video on iOS, the memory increased every time when the loop is start till app is crashed.
the cpu usage is also very high

but same code all works fine at Android, low and stable memory and cpu usage!

just loop a video by VideoPlayerController.setLooping(true) and nothing else

please help!

video_player:  2.7.2

### Expected results

same performance on Android and iOS

### Actual results

same code on Android works fine, but on iOS, memory and cpu usage are unacceptable

### Code sample

<details open><summary>Code sample</summary>
File file = File("xxx");

VideoPlayerController controller = VideoPlayerController.file(file);

controller.setLooping(true);

await controller.initialize();

controller.play();

</details>

### Flutter Doctor output

`[!] Flutter (Channel unknown, 3.10.7, on macOS 13.3.1 22E261 darwin-arm64,
    locale zh-Hans-CN)
    ! Flutter version 3.10.7 on channel unknown at
      /Users/namcooper/DevTools/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an
      official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions
      at https://flutter.dev/docs/get-started/install.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at
      https://flutter.dev/docs/get-started/install.
    • Framework revision e285328a69 (4 months ago), 2023-08-17 17:55:17 -0700
    • Engine revision 077a732ef4
    • Dart version 3.0.7
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version
    34.0.0-rc4)
    • Android SDK at /Users/namcooper/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0-rc4
    • ANDROID_HOME = /Users/namcooper/Library/Android/sdk
    • Java binary at:
      /Users/namcooper/Library/Java/JavaVirtualMachines/corretto-11.0.12/Content
      s/Home/bin/java
    • Java version OpenJDK Runtime Environment Corretto-11.0.12.7.2 (build
      11.0.12+7-LTS)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • SM A5260 (mobile) • R5CRA1D7N4F • android-arm64  • Android 13 (API 33)
    • macOS (desktop)   • macos       • darwin-arm64   • macOS 13.3.1 22E261
      darwin-arm64
    • Chrome (web)      • chrome      • web-javascript • Google Chrome
      120.0.6099.129

[✓] Network resources
    • All expected network resources are available.
`

**Comment by darshankawar** [comment]
@NamHofstadter Thanks for the report and Happy new year!
I see that you are on old version of stable. Current is 3.16.5. so I suggest you to first upgrade to latest and rerun your scenario to confirm if the reported behavior persists or not.
If yes, please provide memory trace and the crash log you mentioned in text format so that we can take a look at it and verify further.
