### ISSUE TITLE
iOS crash when running gallery app

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1407]
I built the iOS app with Xcode and loaded it on the device. The gallery app started up, but I then saw this in my Xcode:

![screen shot 2016-01-27 at 10 27 54 am](https://cloud.githubusercontent.com/assets/5479/12623857/da12beae-c4e0-11e5-8ef1-377da79990bd.png)

My, my iPod Touch is pretty borked. I had to unplug it and force restart it :)

Here's my version:

```
Flutter
Repository: git@github.com:flutter/flutter.git
Branch: alpha
Revision: 2d6dd63e377b9d4131fa120fad249461f9602684 (4 days ago)
```

**Comment by eseidelGoogle** [comment]
Not sure why it's trying to grab at 0x1.  Would be interesting to repro with a debug build of Skia. @chinmaygarde

**Comment by chinmaygarde** [comment]
* This was was fixed a few days ago after I was able to reproduce the issue in the game.
* Since we no longer strip symbols, these backtraces should be a bit richer.
