### ISSUE TITLE
Trust user-added CA certificates in Flutter application

### ISSUE THREAD

**Issue by Malnen** [flutter/flutter#140737]
I'm writing flutter app that will retrieve data via https from a local server. We have our own certification authority and have installed the certificate on the server. We also installed the intermediate certificate on the Android device so it can be trusted. When connecting to our server in chrome SSL works fine and the browser trusts our CA. But when I try to connect to it in the app, I get this error:
```
E/flutter (15518): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: HandshakeException: Handshake error in client (OS Error:  
E/flutter (15518):  CERTIFICATE_VERIFY_FAILED: self signed certificate in certificate chain(handshake.cc:393)) 
E/flutter (15518): #0      _SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:99:46) 
E/flutter (15518): #1      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:142:25) 
E/flutter (15518): #2      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:911:54) 
E/flutter (15518): #3      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:1040:19) 
E/flutter (15518): <asynchronous suspension> E/flutter (15518):
```

I've followed [this guide](https://developer.android.com/privacy-and-security/security-config) and configured the Android manifest like this and created a network_security_config.xml file

Android Manifest
```
<application
  android:networkSecurityConfig="@xml/network_security_config"
  ...
```
Network Security Config
```
<network-security-config>
    <base-config>
        <trust-anchors>
            <certificates src="system" />
            <certificates src="user" />
        </trust-anchors>
    </base-config>
</network-security-config>
```

It can be reproduced in a new Flutter project. Has anyone encountered a similar problem? We checked our certificates and they are ok. It also works for Chrome on the same device. I checked the Chrome app manifest and we have the same network security configuration. We also cannot addour certificates inside the application because there may be an unlimited number of other CAs in production that we want to trust. We want to trust all certificates added by the user

**Comment by darshankawar** [comment]
@Malnen 
Can you check [this](https://github.com/flutter/flutter/issues/56607) similar issue and confirm if it resembles your case or not ?
