### ISSUE TITLE
Flutter web | NoSuchMethodError: method not found: 'indexOf' (receiver.indexOf is not a function) 

### ISSUE THREAD

**Issue by skalex4** [flutter/flutter#140788]
### Steps to reproduce

1. compile flutter android code for web. 
2. run it in web. 

### Expected results

internally compiled function stringReplaceAllUncheckedString is breaking while running flutter in web. 

```
    stringReplaceAllUncheckedString(receiver, pattern, replacement) {
      var $length, t1, i;
      if (pattern === "") {
        if (receiver === "")
          return replacement;
        $length = receiver.length;
        t1 = "" + replacement;
        for (i = 0; i < $length; ++i)
          t1 = t1 + receiver[i] + replacement;
        return t1.charCodeAt(0) == 0 ? t1 : t1;
      }
      try{

      if (receiver.indexOf(pattern, 0) < 0)
        return receiver;
      if (receiver.length < 500 || replacement.indexOf("$", 0) >= 0)
        return receiver.split(pattern).join(replacement);
      return receiver.replace(new RegExp(A.quoteStringForRegExp(pattern), "g"), A.escapeReplacement(replacement));
      } catch (e) {
        return receiver;
      }
      
```

### Actual results

compiled code should have fail case scenario to handle the failure. 

### Code sample

<details open><summary>Code sample</summary>

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
error from unoptimized js file:

error => NoSuchMethodError: method not found: 'indexOf' (receiver.indexOf is not a function) 
 TypeError: receiver.indexOf is not a function
    at Object.stringReplaceAllUncheckedString (http://localhost:5500/main.dart.js:9880:20)
    at Object.stringReplaceAllUnchecked (http://localhost:5500/main.dart.js:9849:18)
    at http://localhost:5500/main.dart.js:131703:22
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:5500/main.dart.js:12078:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:5500/main.dart.js:69835:12)
    at _awaitOnObject_closure.call$1 (http://localhost:5500/main.dart.js:69823:32)
    at Object._rootRunUnary (http://localhost:5500/main.dart.js:12545:18)
    at StaticClosure.<anonymous> (http://localhost:5500/main.dart.js:145772:16)
    at _CustomZone.runUnary$2$2 (http://localhost:5500/main.dart.js:71701:39)
    at _Future__propagateToListeners_handleValueCallback.call$0 (http://localhost:5500/main.dart.js:70655:51)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.2, on macOS 14.2.1 23C71 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.85.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by brightknight08** [comment]
is `stringReplaceAllUncheckedString` from Flutter codebase? if not, why not declare the types of the parameters in `stringReplaceAllUncheckedString(receiver, pattern, replacement) {`?

**Comment by dam-ease** [comment]
Hi @skalex4.
Please can you upgrade to a newer version of flutter to see if this issue still persists on your end? If it does, Please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code.
Thank you

**Comment by skalex4** [comment]
Hi @dam-ease,

I've tried with 3.16.3 & older versions also (3.13.2, 3.13.8). 

But facing same issue with all the version. 

This is the from the flutter codebase, I'm attaching the screenshots of the example parameter send.
