### ISSUE TITLE
query parameters is absent in go_router 13.0.0

### ISSUE THREAD

**Issue by anup30** [flutter/flutter#140778]
### Steps to reproduce

state.queryParams is not working in go_router 13.0.0 
it shows following error: The getter 'queryParams' isn't defined for the type 'GoRouterState'
i am new to flutter, i was watching tutorial on go router, that showed state.queryParams worked in version 6.2.0
did i missed something? is there an alternate way  of queryParams ?

### Expected results

state.queryParams is not working in go_router 13.0.0 
it shows following error: The getter 'queryParams' isn't defined for the type 'GoRouterState'
i am new to flutter, i was watching tutorial on go router, that showed state.queryParams worked in version 6.2.0
did i missed something? is there an alternate way  of queryParams ?

### Actual results

as above

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
`queryParams` was renamed to `queryParameters`. See https://docs.google.com/document/d/10Xbpifbs4E-zh6YE5akIO8raJq_m3FIXs6nUGdOspOg/edit

In the future, please check the migration docs section of the go_router readme to keep updated with the latest updates. https://pub.dev/packages/go_router#migration-guides

Closing from here. 

Thank you
