### ISSUE TITLE
Linux Arm: Chinese font and Emojis are not being rendered

### ISSUE THREAD

**Issue by Feichtmeier** [flutter/flutter#140738]
### Steps to reproduce

1) Have an ARM machine
2) install Linux desktop
3) install flutter
4) run minimal code sample app with 鉴 and/or 💙 in a text widget or textfield widget
5) See a lot of empty squares

### Expected results

Both Emojis and Chinese letters should be rendered just like on AMD64 Linux machines!

### Actual results

Both Emojis and Chinese letters are not rendered just like on AMD64 Linux machines and show empty squares instead!

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: Text('鉴 💙!'),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Linux Arm:
<img width="707" alt="Bildschirmfoto 2023-12-29 um 16 12 57" src="https://github.com/flutter/flutter/assets/15329494/825c4895-e328-4dd7-969a-ded9ef933d4e">

Linux AMD64:
![image](https://github.com/flutter/flutter/assets/15329494/c49fcb0b-a880-4824-9b52-37aa099bf717)

Apple ARM:
<img width="533" alt="Bildschirmfoto 2023-12-29 um 16 10 04" src="https://github.com/flutter/flutter/assets/15329494/04f0db84-24f5-49b4-9bbc-f836ada48c24">

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
ub@ub:~/fdfdsfsdf$ flutter doctor -v
[✓] Flutter (Channel stable, 3.16.5, on Ubuntu Noble Numbat (development branch) 6.5.0-9-generic, locale de_DE.UTF-8)
    • Flutter version 3.16.5 on channel stable at /home/ub/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (vor 10 Tagen), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 17.0.5 (1ubuntu1)
    • cmake version 3.27.8
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.84.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.78.0

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-arm64 • Ubuntu Noble Numbat (development branch) 6.5.0-9-generic

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @Feichtmeier 
I think it is similar to https://github.com/flutter/flutter/issues/139293 so please follow-up in it for further updates.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.

**Comment by Feichtmeier** [comment]
Ok indeed that looks very similar
I searched the issues for emoji and Chinese but didn't find it because the title hasn't had it
Thanks for finding the duplicate
