### ISSUE TITLE
[Impeller] HAL needs barriers for both Metal/Vulkan for compute usage.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#140798]
The current design of Impeller's HAL assumes that barriers can either always be inferred/tracked (Vulkan image layout) or can be handled either by Metal hazard tracking and/or command buffer submission order.

However Vulkan command buffers promise much less than we think, and as a result Canvas.drawPoints compute implementation behaves erratically. I suspect this is also true of metal command buffers, and hazard tracking is saving us.

Basic setup:

Cmd Buffer 1: <---- Compute DrawPoints Geometry into Buffer A
Cmd Buffer 1. Submit

Cmd buffer 2: <---- Draw Points With Buffer A
Cmd buffer 2. Submit.

The order of submission here works on Metal but is broken on Vulkan. Actually, if we Cmd Buffer 1 and 2 share the same buffer (so there is not a distinct MTLBuffer for the compute command) then it actually has sync issues too.

This blocks the usage of compute for Vulkan.

**Comment by jonahwilliams** [comment]
Q: can we just infer the barriers like we do for textures?

impeller has state tracking for textures, this is done by tracking the layout state on the texture object itself:  https://github.com/flutter/engine/blob/main/impeller/renderer/backend/vulkan/texture_source_vk.h

We could theoretically do something similar for buffer usage. i.e. track some bit that says read from / written to based on when the cmd is encoded and try to insert barriers and do an emulate state transitions. I can't say whether this wouldn't work, but I'm skeptical as I've found the tracked state of the impeller:Texture to be confusing because the state tracking can't always be accurate. For example, the render pass itself will transition the texture state and we have to emulate this by using the SetLayoutWithoutEncoding sometimes. I could imagine a similar issue where a non-trivial buffer usage, i.e. more than one read/write pair into the same buffer leads to confusing runtime barriers and potentially bugs/deadlocks.

In contrast, if the contents/geometry where the compute command is configured, we can always know the correct barriers needed.

@gaaclarke @bdero

**Comment by bdero** [comment]
We would need barriers for user-driven subresource tracking specifically, but we could get away with automating them in most cases. But I'm rusty here... Does the layout tracking complexity actually apply for non-texture buffers? My understanding is that these layout transitions are necessary because the underlying texture data needs to be stored as a [z-order curve](https://en.wikipedia.org/wiki/Z-order_curve) in order to be read by the hardware. And since Vulkan doesn't synchronize resource access at all by default, we're also on the hook for layout optimization because Vulkan doesn't form knowledge around how the resources are going to be used.

**Comment by jonahwilliams** [comment]
The complexity is that the order in which we record commands must be _exactly_ the order that we expect the commands to be executed in so that the internal texture state kind of matches what we claim the state is, which prevents any multithreaded usage.

**Comment by jonahwilliams** [comment]
For example, with the right barriers in place, I should theoretically be able to push tasks to one or more worker threads and have encoding finished and submitted. But if I do that now, the texture state will get out of sync, because the order that commands are encoded (but not submitted) determines how barriers are placed.

**Comment by bdero** [comment]
We talked about this a bit offline. I'm already convinced that we're going to need some kind of barrier API for subresource tracking for perf reasons, and I'm open to the idea that optional hazard tracking for DeviceBuffers wouldn't be worth the complexity savings in the Entities layer (at the expense of the backend).

I believe there are routes we could take to partially track a timeline at recording time and then flush them together at command submission which would allow for parallel CommandBuffer recording/encoding, but I honestly don't know if this complexity is worth it or not. Jonah thinks it's not worth it, and I trust his judgement and am not trying to block this. 

Also also, just to be totally clear, I 100% (no, 200%) agree that Flutter GPU isn't and should never be considered a blocker for making changes like this to Impeller's HAL. It's a very different API than Impeller's HAL to begin with. If anyone adds barriers to the HAL/remove aspects of the automated hazard tracking, you have my full support in breaking Flutter GPU. I'm fully convinced that Flutter GPU _will_ need barriers for bread-and-butter compute use cases, and if we decide later that it's not necessary for certain resources in certain situations in Flutter GPU, I can automate this behavior in the translation layer.

**Comment by jonahwilliams** [comment]
I think our current state tracking is actually incorrect for textures, even though the state should be much simpler. Consider:

1. Upload texture A
2. Reference texture A in render pass 1.
3. Reference texture A in render pass 2.

Under the current state tracking system, we'll insert a barrier when adding the texture to render pass 1, but not render pass 2 based on encoding order. This is actually incorrect, as there is no guarantee that the state of texture A has been updated until some point in the future, and render pass 1 and 2 can be worked on concurrently.

**Comment by jonahwilliams** [comment]
https://github.com/flutter/engine/pull/49946 adds the minimal API required to restore our ability to use Compute. I'm closing this issue with that, and we can file more specific issues as we run into additional synchronization needs

**Comment by jonahwilliams** [comment]
This is completed!
