### ISSUE TITLE
ClipboardData is null on some Android devices after copying text

### ISSUE THREAD

**Issue by perlatus** [flutter/flutter#14078]
On certain Android devices, after selecting and copying text, such as from a web browser, `Clipboard.getData(...)` returns null ClipboardData.

As far as I can tell, this *only* occurs when copying static text after selecting it. It doesn't happen when you copy text from an EditText field, like an SMS app's message compose field. It also doesn't happen when you programatically copy content, such as with the "Copy link address" and "Copy link text" options in Chrome for Android.

*update: Looking into the engine, it's probably due to the [conditional check for the `text/plain` MIME type](https://github.com/flutter/engine/blob/e7e94c6307bcefdbd4835a6f1a594a70df5dfe9a/shell/platform/android/io/flutter/plugin/platform/PlatformPlugin.java#L231), where different device/manufacturer/browser combos may consider copied browser text as valid `text/plain` while others consider it `text/html`.*

## Devices
One of my dev devices is affected ("Personally confirmed"); the others are from user reports from my e1547 app. I'm hoping to get more data on which devices are affected. I don't think this is limited to a specific Android version or manufacturer.

Affected | Personally confirmed | Manufacturer | Model | Android version
-----------------|---------------|-------------|------------|------------------
Yes | Yes | Motorola | Moto E 1st gen | 4.4.4
Yes | No | Samsung | SM-G800Y | 6.0.1
Maybe | No | LG | G6 | 7.0
No | No | Bravis | A505 JOY Plus | 6.0
No | Yes | Motorola | Moto G5 Plus | 7.0
No | Yes | Samsung | SCH-I535 | 4.4.2
No | Yes | Samsung | SM-S766C | 4.3

## Steps to Reproduce

Run the app on an affected device: https://github.com/perlatus/flutter_clipboard_bug
See the example video: https://perlat.us/vid/flutter_clipboard_bug.mp4

## Logs

```
/data/code/gh/flutter_clipboard_bug> flutter analyze
Analyzing /data/code/gh/flutter_clipboard_bug...
No issues found!
Ran in 5.3s
```

There's also nothing logged or thrown when retrieving the system clipboard in the bug case or the expected case.

## Flutter Doctor

```
/data/code/gh/flutter_clipboard_bug> flutter doctor
[✓] Flutter (on Linux, locale en_US.UTF-8, channel master)
    • Flutter at /data/code/clone/flutter
    • Framework revision 8cf109d20f (11 hours ago), 2018-01-11 23:21:53 -0800
    • Engine revision 05fe72d068
    • Tools Dart version 2.0.0-dev.16.0
    • Engine Dart version 2.0.0-edge.28757928b47b192efcec082c78258102beb03f78

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.3)
    • Android SDK at /home/vczf/opt/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-26, build-tools 26.0.3
    • Java binary at: /home/vczf/opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /home/vczf/opt/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Connected devices
    • XT830C • ZX1B72G4V6 • android-arm • Android 4.4.4 (API 19)
```

**Comment by perlatus** [comment]
I can't test this yet since I'm still setting up a dev environment for flutter/engine, but here's what I think would probably fix it: https://github.com/perlatus/engine/commit/cbcdf0f034320776f958bde3249bb0c15d00a1a4

**Comment by perlatus** [comment]
Actually, it looks like the difference between the clipboard contents being text/html or text/plain is due to the web browser that you copy the text from. Chrome for Android and WebViews are text/html, which causes the clipboard contents to be null. Firefox for Android considers it as text/plain. That's why the affected devices are all over the place.

Coercing html to plain text when we ask for plain text would make paste work as expected within flutter apps.

**Comment by perlatus** [comment]
Closing to clarify in #14093

**Comment by GroovinChip** [comment]
@perlatus I'm experiencing this issue now. Do you have a recommended solution?

**Comment by GroovinChip** [comment]
@TahaTesser can we get this re-triaged?
