### ISSUE TITLE
Hardware back button in nested navigator only pops outside navigator

### ISSUE THREAD

**Issue by rmtmckenzie** [flutter/flutter#14083]
## Steps to Reproduce

Create a nested navigator. The top level navigator handles back just fine, but a WillPopScope within the inner navigator is completely ignored.

This is still the case if a WidgetsBindingObserver is used with the inner navigator.

## Discussion...
I've debugged through and the reason this seems to happen is that WidgetsBinding.handlePopRoute iterates forward through the list of WidgetsBindingObservers. This means observers that are registered later are lower down the list so never get called if the first layer can perform a pop. This causes a problem - if I have a nested structure, I want the lower level to be able to decide whether or not to pop before the decision is passed up the structure. But because the top level decides first, I'm going to have to write all my own wiring to propagate the decision downwards through a lower navigator.

I think that a simple fix would be to simply reverse the iteration through the list of WidgetBindingObservers in WidgetsBinding, but I realize that change could cause problems for existing projects (although theoretically if people are following the basic 'flutter' way of doing things, they would only have the one WidgetBindingObserver from the WidgetsApp making pop decisions so maybe it wouldn't cause too many problems).

I also recognize that through what I've seen in other issues & threads, flutter doesn't really want to support nested navigators. However, I think that as adoption grows you're going to see a lot more people attempting to do it as there is nothing that prohibits it, and some of the documentaiton/code make it seem like it should work (i.e. in navigator has a 'bubble RoutePopDisposition' - on close inspection it says it bubbles to the system navigator but I initially assumed it bubbled from navigator to navigator). I personally am using nested navigators because I have an app with multiple sections, and some of the sections have navigational behaviour that are quite different than others, so it made sense to create different navigators (with extra classes for the specific behaviour). And even just for code cleanliness, it's nice to be able to split up functionality into of pages that are handled individually.

## Logs

N/A

## Flutter Doctor

N/A really - this is with the most recent flutter & dart but is reproducible with older versions as well as the relevant code hasn't changed.

    • Flutter at C:\VirtualDrives\Programs\flutter
    • Framework revision 8cf109d20f (15 hours ago), 2018-01-11 23:21:53 -0800
    • Engine revision 05fe72d068
    • Tools Dart version 2.0.0-dev.16.0
    • Engine Dart version 2.0.0-edge.28757928b47b192efcec082c78258102beb03f78

**Comment by rmtmckenzie** [comment]
See this repo for an example: https://github.com/rmtmckenzie/flutter_nested_navigators

**Comment by rmtmckenzie** [comment]
And FYI - adding .reversed to line 406 in widgets/binding.dart solves this. I won't create a pull request for now as I think some discussion is needed before that is looked at...

**Comment by Hixie** [comment]
It's not really clear which navigator to send the message to. Consider a situation where the top navigator has two child navigators, each of which has two child navigators. All of them have had "pushNamed" called on them twice. You hit "back". Which do you want to go back?

**Comment by rmtmckenzie** [comment]
I'm revisiting this and I've now realized the 'right' way of doing this for my use-case which does work just fine - I needed a 'WillPopScope' in the widget created by the outer route that delegates the decision to its internal navigator, which is probably exactly what you're thinking (i.e. have logic within that to choose which navigator if there are several). I'll update my example to reflect this for if anyone else comes across this. I guess my issue is that I assumed that a 'WillPopScope' would work regardless of its' position in the tree rather than depending on the route/navigator directly above it (despite that being said in not quite so many words in the documentation). If I use WillPopScopes appropriately at both levels, the decision to close or not will stay within the first WidgetsBindingObserver's didPopRoute and 'bubble' down the tree properly. My bad!

So any situation where you're dealing with something in the widget tree, it can be handled completely by WillPopScope, and there is no need for WidgetsBindingObserver.

I would still argue that when using a WidgetsBindingObserver directly, either the most recently 'bound' should be the first to have the decision of whether to pop or not (irrespective of the navigator tree) or each of them should have the decision and then the system would pop if none of them handled it. 

This is a bit of a contrived example, but think about the situation where you have a library (with no UI) that does non-instant transactions with an external server. Let's say we start a transaction, then the user presses back. We want to be informed about this so we can roll back the transaction without relying on a cancel function being called so we use a WidgetsBindingObserver to be notified of the user pressing back, but we are never notified because the Navigation tree starting at WidgetApp handles it (assuming it does actually pop). 

This is already quite long so I won't make any more arguments although I can think of other situations where it would be nice to be able to temporarily take control over the 'pop' process without having to rely on all routes above the current level having been done properly; if you consider this and still disagree I'll leave it alone - after all you're the expert =).    And one more thing - theoretically, if WillPopScope has been used properly there should only be one WidgetsBindingObserver that actually has a handlePopRoute implementation in any current apps so changing the order shouldn't cause any issues.

**Comment by Hixie** [comment]
I'm toying with a way to address this in my Router changes. See BackButtonDispatcher in https://github.com/flutter/flutter/compare/master...Hixie:router

**Comment by Hixie** [comment]
You ask many questions that I don't have answers to yet. I will try to let them guide me in my design, so thanks.

My assumption was that a node would take priority when it gains keyboard focus, or when it is tapped. But maybe your application has a different kind of interaction model?

I'm finding it hard to imagine an usable application with six Navigators at a time, let alone five levels of nested routing; maybe you can share your design?

**Comment by rmtmckenzie** [comment]
Sorry, that was just a contrived example to show my point. You're right - there's probably never any case for that many levels of nested navigator unless you're doing something really weird. Also I didn't get that this is something that would happen automatically when keyboard focus is applied; in that case I can definitely see that what I've suggested is overkill and why you've done it the way you did.

In my application I have three levels of nesting; a full-screen top level which switches between logged in and not, a full-screen mid level which switches between modes and displays the app bar, and a bottom level which switches between screens in the various modes. So I think what you've done would work well for it, so long as I make sure I actually give the screens keyboard focus as I transition to them.

A (still somewhat contrived) example where I'd use nested navigators similarly to how I described in my last post is if I were making a design application that worked with a split screen (or most any other app with part that displays something and uses he other part to display data/settings.. Say the top showed the design (& could interact with it), but it could also be swiped left or right to show wireframe vs full design (different pages), and the bottom part of the screen had various menus for adding & modifying elements. I could maybe see a situation where it made more sense to have two levels of nested navigators for simplicity rather than just having a large number different screens for the various options.

But even with that example, I'm still tying to figure out a situation where what you've done wouldn't work... so long as wherever you tap the focus follows.... So ignore me =)

**Comment by Hixie** [comment]
For what you describe I'd probably just have a single Router, and have its build method (on the parsedRouteHandler) actually build all three levels simultaneously. You could then have it handle pop requests however you like, and you'd only have a single backButtonDispatcher.

**Comment by dankop123** [comment]
Any news on the issue?
I'm also having problems with android back button. I'm using `CupertinoTabBar` for bottom navigation and when I push other widget on one of the tab bar children, back button pops tab bar root view.

**Comment by klisiewicz** [comment]
@rmtmckenzie Could you provide some sample code that illustrates how to apply your solution to the `CupertinoTabBar`? Thanks in advance.

**Comment by rmtmckenzie** [comment]
@klisiewicz That depends on what exactly you want to do with the CupertinoTabBar. Are you trying to have something like:

```
    -------------------
   |                   |
   |     Navigator     |
   |          1        |
   |                   |
   |                   |
   |                   |
   |                   |
   |                   |
    -------------------
   |      Cupertino    |
   |         Tab Bar   |
    -------------------
```
where "Navigator 1" is the top-level navigator that handles navigation between the 'tabs', and each of the 'tabs' would have their own navigator? And I'm assuming that if the user taps the back button, you want whichever 'tab' is active to handle it.

In that case, the UI part is more complicated but the back button scope is exactly the same as [the example](https://github.com/rmtmckenzie/flutter_nested_navigators/blob/master/lib/main.dart) I made. Your 'tab' has to keep track of its navigator's state, have a WillPopScope around its inner navigator, and call the inner navigator state's maybePop() (or one of its other methods) from within the WillPopScope's callback.

**Comment by gagaJay** [comment]
@klisiewicz you can also check this [link](https://medium.com/coding-with-flutter/flutter-case-study-multiple-navigators-with-bottomnavigationbar-90eb6caa6dbf) for a sample code.

**Comment by p30arena** [comment]
maybe you should not use nested navigator

```
WillPopScope(
      onWillPop: () async {
        if (selectedCat == null) {
          return true;
        } else {
          setState(() {
            selectedCat = null;
          });
          return false;
        }
      },
      child:
```

**Comment by Nico04** [comment]
I've got a similar project, and this article helped me a lot :
https://medium.com/coding-with-flutter/flutter-case-study-multiple-navigators-with-bottomnavigationbar-90eb6caa6dbf

The key is to use only one WillPopScope, and use the maybePop() of the nested navigator on the onWillPop callback.

**Comment by user82361386** [comment]
This comment from 23 Nov needs a big tick by it.  It is the answer.
> While the issue hasn't technically been resolved, there's a really easy way to get around it. All you need to do is wherever you have another navigator, make sure you wrap it in a WillPopScope and delegate the decision downwards (for example with a navigator you'd probably pass it a globalkey and call !globalkey.state.maybepop() or something).


I can't paste it in, but a StatefulWidget with a WillPopScope(), a Navigator(), and a Global Key can implement static 'of' and 'popOut' to provide:
``
  SubNavigator.of(context).popOut() 
``
for the pages beneath the SubNavigator.

It works multiply nested.

**Comment by phasedarray** [comment]
WillPopScope may solve this
 issue,but it will bring another problem that WillPopScope prevents back swipe in iOS, which isn't an expected behavior. Anyone has solution to make both work?

**Comment by HansMuller** [comment]
About a month ago I wrote an article about bottom navigation with nested navigators in Flutter: https://medium.com/flutter/getting-to-the-bottom-of-navigation-in-flutter-b3e440b9386

Here's a version of the last example from the article that adds support for the back button: https://gist.github.com/HansMuller/0fdde5aac7a3ce6f5bf6c30978bea850

Here's the same example configured for the iOS platform and its pop-swipe gesture:
https://gist.github.com/HansMuller/06c367725097dd457380f8a6c17734d9

**Comment by Nico04** [comment]
> 
> 
> About a month ago I wrote an article about bottom navigation with nested navigators in Flutter: https://medium.com/flutter/getting-to-the-bottom-of-navigation-in-flutter-b3e440b9386
> 
> Here's a version of the last example from the article that adds support for the back button: https://gist.github.com/HansMuller/0fdde5aac7a3ce6f5bf6c30978bea850
> 
> Here's the same example configured for the iOS platform and its pop-swipe gesture:
> https://gist.github.com/HansMuller/06c367725097dd457380f8a6c17734d9

Thanks for this, if I understood well it's quite similar of the other article I've talked about, but you use canPop() and pop() instead of maybePop().
Can you tell me what's the iOS specific part ? 

From your code I just see an addition of an unreachable 'return true'
`navigator.pop();
        return false;
        return true;`

**Comment by HansMuller** [comment]
Sorry about the typo! The extra `return true` didn't belong there. I've removed it from https://gist.github.com/HansMuller/06c367725097dd457380f8a6c17734d9

The only iOS-specifc code is this; so I could try the IOS version of the app out on Android:
```
void main() {
  runApp(
    MaterialApp(
      home: HomePage(),
      theme: ThemeData.light().copyWith(platform: TargetPlatform.iOS),
    )
  );
}
```

**Comment by esDotDev** [comment]
There's plenty of use cases for when we would not want to use the MaterialApp's navigator, and they don't have to get complex. 

In one recent app, I have an interactive background that I want to be always present. On top of that background, is the content of the app, which I'd like to just wrap in a Navigator, and have it 'just work'. 

Why wouldn't Navigator have an onBack event, so it can decide whether to handle the event or not? What good is a navigator class with push/pop support, if it doesn't provide a clear mechanism for handling the hardware back btn when nested?

**Comment by nguu** [comment]
Sorry my english not good, i improve it.

I am newbie, i think maybe my issue is same this issue, i want nested navigator in my app.
This my code: https://github.com/nguu/flutter-nested-navigator

I have Home Page has the FlatButton, when click button i push new Navigator with SecondPage is first route.
In my SecondPage has two button, first is custom back button, second is the FlatButton to push ThirdPage.
In my ThirdPage just only custom back button.
Custome Back Button on my pages, call `Navigator.of(context).pop()`.

- I want to click custom back button, or android back button in ThirdPage, will return SecondPage.
- When i click custom back button, or android back button in SecondPage, will return HomePage.

I use WillPopScope for nested navigator, and just working on ThirdPage.
If i click custom back button on SecondPage, it return the black screen.

I want when i call `Navigator.of(context).pop()`, Navigator check if i am on nested navigation, and if i am on the nested navigator, just pop the route in nested navigator, and when my screen is first route in the nested navigator, will remove nested navigator and back to parent navigator.

```
MaterialApp
-- Navigator
-- -- ThirdPage
-- -- SecondPage
-- HomePage
```

**Comment by rodruiz** [comment]
Hi, 
you need a **WillPopScope** in the main widget.

```dart
// MAIN WIDGET
Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: () {
        // show confirmation
        return AppManager.instance.showCloseAppConfirmation(context);
      },
      child: Scaffold(
       .....
      ),
    );
```
```dart
class AppManager {
  static AppManager _instance;

  static AppManager get instance {
    if (_instance == null) {
      _instance = AppManager._();
    }
    return _instance;
  }

  // REGISTER ALL NAVIGATORS HERE 
  final GlobalKey<NavigatorState> appNavigatorKey = GlobalKey<NavigatorState>();
  final GlobalKey<NavigatorState> anotherNavigatorKey = GlobalKey<NavigatorState>();

  // Because we are calling this from the main widget we have to check
  // nested navigators status.
  Future<bool> showCloseAppConfirmation(BuildContext context) {
    // Check a Lower Navigator First
    if (this.anotherNavigatorKey.currentState.canPop()) {
      print("Using ANOTHER-Navigator");
      this.anotherNavigatorKey.currentState.pop();
      return Future.value(false);
    }

    // Check here any custom navigator
    // ...

    // Check current context navigator Main App Navigator
    if (this.appNavigatorKey.currentState.canPop()) {
      print("Using Main-Navigator");
      this.appNavigatorKey.currentState.pop();
      return Future.value(false);
    }

    // SHOW CLOSE APP CONFIRMATION DIALOG
    return showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: Text('Confirm'),
        content: Text('Are you sure you want to exit?'),
        actions: <Widget>[
          FlatButton(
            child: Text('No'),
            onPressed: () => Navigator.of(context).pop(false),
          ),
          FlatButton(
            child: Text('Yes'),
            onPressed: () => Navigator.of(context).pop(true),
          ),
        ],
      ),
    );
  }
}
```

Hope that helps.

Thanks

**Comment by chunhtai** [comment]
This will more straight forward when navigator 2.0 is implemented https://github.com/flutter/flutter/issues/45938,
and there is a workaround using WillpopScope. Is there anything else that is not yet addressed in this issue? Otherwise, I would like to close as a duplicate of https://github.com/flutter/flutter/issues/45938

**Comment by rmtmckenzie** [comment]
Sure, that's fine with me.

**Comment by amuchand47** [comment]
@rmtmckenzie  Hi, I have create 3 layout, I am going to 3rd layout from home layout (1st one) through 2nd one. When I press back button then I am directly reaching to 1st layout without going to 2nd one. Please do help me .

**Comment by rmtmckenzie** [comment]
@amuchand47 It sounds like the outer scope is handing the back button request rather than the inner one, which you can avoid using a WillPopScope and passing off the request to the child navigator. There's a code example of that above.

Also, this isn't a Q&A site - you'll have better luck asking on StackOverflow and including a minimal code sample.

**Comment by magicleon94** [comment]
Hi there, I'm having the same issue with the "swipe to back" gesture in iOS. Using Navigator 2.0 and BackButtonDispatcher makes everything flawless with the Android back button in the nested navigator, but the "swipe to back" gesture still pops the outside navigator, making useless all the work. And using WillPopScope as a workaround is not an option because using WillPopScope disables the gesture.

Since the gesture is quite important to iOS users I don't like kicking it out just to have a cleaner architecture, but that means 

I'm stuck with Navigator 1.0 and no nested navigation :(

**Comment by chunhtai** [comment]
back swipe usually linked with page transition animation. Can you talk about how you expect back swipe to work if it is not popping the root navigator but just a small portion of the app?

**Comment by magicleon94** [comment]
Hi @chunhtai,

Yes, sorry if I wasn't clear. Let me try explaining better what I mean it happens and what I'd expect.

Suppose I have an app whose pages are Home, About and MultiPageFeature.

Now, Home and About are single pages pushing About onto Home works as expected:
```
-------------------------------About
Root navigator base stack ---> Home
```

Now, suppose MultiPageFeature is a page with its own navigator, used to manage the pages inside that process; for convenience, we'll call these pages FeatureStep1 and FeatureStep2.

Pushing MultiPageFeature and navigating the feature until the FeatureStep2 will result in this stack situation:

```
----------------------------------------FeatureStep2
Nested navigator base ---------------->FeatureStep1
Nested navigator starts here ------------------
Root navigator base stack -------------> Home
```

Now I'm on FeatureStep2 and that my Nested Navigator has the priority on the BackButtonDispatcher.

If I press the Android hardware back button, since the dispatcher priority is taken by the nested navigator FeatureStep2 will be popped and I'll be in this situation:

```
Nested navigator base ---------------->FeatureStep1
Nested navigator starts here ------------------
Root navigator base stack -------------> Home
```

**BUT** if instead of that I perform a back gesture on iOS the priority gets totally ignored and the whole nested navigator gets popped away from the root navigator, resulting in this:

```
Root navigator base stack -------------> Home
```

I'd expect the iOS gesture to "go back" as the Android hardware button scenario, is that a wrong expectation? If so, why would that be?

**Comment by Truba** [comment]
Hi @chunhtai ,

I'm having the same issues as the @magicleon94.
Are there any news on this one, or could this issue be reopened?

**Comment by magicleon94** [comment]
Hi @Truba ,

I have no news on this specific issue, but I've found a "workaround" for the problem it was blocking me on.

My idea was to manage a nested inner navigator via a state management (BLoC in my case), and I could achieve that using [flow_builder](https://pub.dev/packages/flow_builder).

I don't know how (didn't dig enough, I'll admit) but this package succeeds in resolving this issue. So if you're looking for ways to manage a nested flow I highly suggest this package. If you need other stuff, I can suggest to dig deep in the package implementation, since it manages to have both android hardware back button and iOS swipe to back working like a charm!

**Comment by Truba** [comment]
Hi @magicleon94 ,

Ty fo the info on flow_builder. It works, and solves the issue of nested Navigators as advertised 😄 .

I checked a bit in their code, and it seems that they are using `WillPopScope` and manually popping when needed.
While it works, it does feel like a hack.

**Comment by magicleon94** [comment]
> Hi @magicleon94 ,
> 
> Ty fo the info on flow_builder. It works, and solves the issue of nested Navigators as advertised 😄 .
> 
> I checked a bit in their code, and it seems that they are using `WillPopScope` and manually popping when needed.
> While it works, it does feel like a hack.  😅 

Well it's surely a workaround for the mentioned issue, but at least it does the job 🙈 that said, I'd reopen this issue and give it more importance than before, since seeing you noticing this I assume an increasing number of people is suffering from this

**Comment by MatrixDev** [comment]
Is there any hope for reopening this bug? I've stuck with the same problem and it seams there is no way around without workarounds... :(

**Comment by magicleon94** [comment]
Hi @MatrixDev,

I don't know if there's hope to reopen this but meanwhile I can suggest you the "workaround" I've discussed [here](https://github.com/flutter/flutter/issues/14083#issuecomment-758809587) :)
