### ISSUE TITLE
On Android and iOS, markers and circles are not updated properly when changed

### ISSUE THREAD

**Issue by 781flyingdutchman** [flutter/flutter#140849]
### Steps to reproduce

I create my GoogleMap in a `build` method, as follows:
```
        GoogleMap(
          mapType: MapType.none,
          myLocationEnabled: true,
          myLocationButtonEnabled: true,
          minMaxZoomPreference: isRunningOnIos
              ? const MinMaxZoomPreference(3, 11)
              : const MinMaxZoomPreference(3, 11),
          tiltGesturesEnabled: false,
          zoomGesturesEnabled: true,
          zoomControlsEnabled: true,
          buildingsEnabled: false,
          initialCameraPosition: CameraPosition(
            target: context.read<Gps>().initialPosition,
            zoom: zoomLevel,
          ),
          cameraTargetBounds: CameraTargetBounds(validGpsBounds),
          tileOverlays: tileOverlays,
          markers: planeMarker != null ? {planeMarker!} : const <Marker>{},
          polylines: navigationLines.union(runwayGuideLines),
          polygons: airSigmetPolygons,
          circles: dots,
          onMapCreated: onMapCreated,
          onCameraMove: (cameraPosition) =>
              cameraLatLng = cameraPosition.target,
          onCameraIdle: onCameraIdle,
          onTap: onMapTap,
        ),
```
As the `markers` and `circles` parameters I pass a set of markers or circles, and that set can change between successive calls to the `build` method and therefore to `GoogleMaps`. This has worked perfectly for the last build in June 2023, but when I rebuilt my app recently (targeting Android API 34, running on API34 real device), not all of the 'old' markers/circles are removed when a new set is presented. This is most obviously true for the `markers` parameter, as the Set passed never has more than one item, yet I have several overlapping plane markers showing on the screen - clearly, older markers were not properly removed.

This may be related to how the 'diff' is calculated in `maps_object_updated.dart`, or in how that diff is processed on the native side. 

I have tested this with plugin versions from recent (2.5.0) all the way back to 2.2.2, which I am sure used to work in the previous (July 2023) build.  Did something change in the GoogleMaps Service as part of the Google Services that causes this issue?

Separately but perhaps related, I am sure previously the plane icon (the `markers` above) rotation used to be relative to Map North, not the screen - now it is relative to the screen, which is not helpful for my purpose.  Is that also a change? And is #140837 also related?

### Expected results

When I present a new set of Markers or Circles to the GoogleMap object, they should replace the old ones.

### Actual results

_Some_ of the old markers stay in place and are never removed

### Code sample

See above

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Flutter Doctor output
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.2.1 23C71 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by 781flyingdutchman** [comment]
Noted that this is also happening on iOS devices. Also notable that this is only observed on real devices, not on the simulator in debug mode. I suspect it may be related to rapid successive updates to the `markers` and `circles` sets, where somehow the diff gets lost and 'old' markers/circles are not deleted, even though they are no longer in the set.

**Comment by huycozy** [comment]
This looks similar to https://github.com/flutter/flutter/issues/128042. But when I checked it with sample code at https://github.com/flutter/flutter/issues/128042#issuecomment-1580052724, that issue didn't appear. 

Perhaps your case is different, so please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code so that we may verify this. Thanks!

**Comment by 781flyingdutchman** [comment]
Running the following on an iPad Pro (12.9-inch) running iOS 16.7.2 consistently runs fine in debug mode and _crashes_ in release mode:
```
import 'dart:async';
import 'dart:math';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'MapsTest',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final numMarkers = 20;
  final numCircles = 100;
  final centerPos = const LatLng(46, 2);
  late MarkerId id;
  double work = 0;

  Map<MarkerId, Marker> markers = <MarkerId, Marker>{};
  Map<CircleId, Circle> circles = <CircleId, Circle>{};

  @override
  void initState() {
    super.initState();
    for (var n = 0; n < numMarkers; n++) {
      final marker = newMarker('marker');
      markers[marker.markerId] = marker;
    }
    for (var n = 0; n < numCircles; n++) {
      final circle = newCircle();
      circles[circle.circleId] = circle;
    }
    Timer.periodic(const Duration(milliseconds: 200), (Timer t) {
      setState(() {
        for (var n = 0; n < 10000; n++) {
          work = Random().nextDouble();
        }
      });
    });
    Timer.periodic(const Duration(milliseconds: 150), (Timer t) {
      setState(() {
        scramble();
      });
    });
  }

  Marker newMarker(String prefix) {
    final deltaX = (Random().nextDouble() - 0.5) * 2;
    final deltaY = (Random().nextDouble() - 0.5) * 2;
    final marker = Marker(
        markerId: MarkerId('$prefix-${Random().nextInt(100000000)}'),
        position:
            LatLng(centerPos.latitude + deltaX, centerPos.longitude + deltaY),
        alpha: alpha());
    return marker;
  }

  void moveMarker(Marker marker) {
    final deltaX = (Random().nextDouble() - 0.5) / 20;
    final deltaY = (Random().nextDouble() - 0.5) / 20;
    final newPosition = LatLng(
        marker.position.latitude + deltaX, marker.position.longitude + deltaY);
    final newMarker = Marker(
        markerId: marker.markerId, position: newPosition, alpha: marker.alpha);
    markers[marker.markerId] = newMarker;
  }

  Circle newCircle({String prefix = 'Circle'}) {
    final deltaX = (Random().nextDouble() - 0.5) * 2;
    final deltaY = (Random().nextDouble() - 0.5) * 2;
    final circle = Circle(
        circleId: CircleId('$prefix-${Random().nextInt(100000000)}'),
        center:
            LatLng(centerPos.latitude + deltaX, centerPos.longitude + deltaY),
        radius: alpha() * 10000);
    return circle;
  }

  void moveCircle(Circle circle) {
    final deltaX = (Random().nextDouble() - 0.5) / 20;
    final deltaY = (Random().nextDouble() - 0.5) / 20;
    final newPosition = LatLng(
        circle.center.latitude + deltaX, circle.center.longitude + deltaY);
    final newCircle = Circle(
        circleId: circle.circleId, center: newPosition, radius: circle.radius);
    circles[circle.circleId] = newCircle;
  }

  /// Removes some markers, adds others, changes some
  void scramble() {
    var prob = 0.3;
    // Markers
    // remove some
    markers.removeWhere((key, value) => Random().nextDouble() < prob);
    // add new ones to replace
    var toAdd = numMarkers - markers.length;
    for (var n = 0; n < toAdd; n++) {
      Marker marker = newMarker('marker');
      markers[marker.markerId] = marker;
    }
    // move some
    final markersToMove = markers.values
        .where((marker) => Random().nextDouble() < prob).toList();
    markersToMove.forEach(moveMarker);

    // Circles
    // remove some
    circles.removeWhere((key, value) => Random().nextDouble() < prob);
    // add new ones to replace
    toAdd = numCircles - circles.length;
    for (var n = 0; n < toAdd; n++) {
      final circle = newCircle();
      circles[circle.circleId] = circle;
    }
    // move some
    final circlesToMove = circles.values
        .where((marker) => Random().nextDouble() < prob).toList();
    circlesToMove.forEach(moveCircle);
  }

  double alpha() => Random().nextDouble() * 0.7 + 0.3;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Scaffold(
            appBar: AppBar(title: const Text('MapsTest')),
            body: Center(
              child: Column(
                children: [
                  Text('${markers.length} markers'),
                  Text('${circles.length} circles'),
                  Expanded(
                    child: GoogleMap(
                      compassEnabled: false,
                      rotateGesturesEnabled: false,
                      myLocationEnabled: true,
                      myLocationButtonEnabled: true,
                      zoomControlsEnabled: true,
                      markers: Set<Marker>.of(markers.values),
                      circles: Set<Circle>.of(circles.values),
                      initialCameraPosition: const CameraPosition(
                        target: LatLng(46, 2),
                        zoom: 8.0,
                      ),
                    ),
                  )
                ],
              ),
            )));
  }
}
```

You'll need to add your key etc, but basically it creates a set of markers and circles, then removes, adds and moves about 30% of these at a regular interval.  You can change the interval to increase the load, and I also added another 'work' timer to do additional work to stress test. Interestingly, I didn't have any issue with only markers (up to 200 runs fine).

I also note another anomaly: the circles start as a regular circle, then the circle 'line width' grows (visible on real device only) so they become 'thick' circles. You can see them 'grow', so I suspect the app is redrawing the circle with increasing or decreasing radius, giving the illusion of a thicker circle. This doesn't seem right to me either, as I only set the radius when creating the circle - it doesn't change afterwards. (see attached screenshot from simulator).
<img width="304" alt="Screenshot 2024-01-03 at 12 38 22 PM" src="https://github.com/flutter/flutter/assets/24858911/ad7c5f6e-7f50-4950-93ad-15e790f06135">

**Comment by 781flyingdutchman** [comment]
I 
<img width="307" alt="Screenshot 2024-01-03 at 1 01 49 PM" src="https://github.com/flutter/flutter/assets/24858911/39fdead2-41bd-4b95-aa1c-77ee77477674">
realize the screenshot doesn't show the border thickness issue. This one does.

**Comment by 781flyingdutchman** [comment]
I have rebuilt the app, after upgrading from Gradle 7.2 to Gradle 8.2 and the original problem appears to have resolved itself, magically. I have no idea how, as I have not made any change to the code, just rebuilt it.

**Comment by huycozy** [comment]
>realize the screenshot doesn't show the border thickness issue. This one does.

This may be related to https://github.com/flutter/flutter/issues/38303. But it could be another issue, please file another one for that.

Regarding the original issue, I ran your sample code above in release mode but it didn't crash (checked on `iPhone 7, iOS 15.8` and `Realme 6, Android 11`). The markers and circles have changed as expected. 
I'm using Gradle version `com.android.tools.build:gradle:7.3.1`.

Can you share the crash stack trace when it happens? (please share the output of `flutter run --release -v`)
