### ISSUE TITLE
Migrate tests off of Moto G4

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#140893]
Below is a summary of the current breakdown of devices for each platform and the jobs still running on Moto G4 devices across the platforms:

* Linux (15 Moto G4, 12 A02, 35 Pixel 7 Pro)
  * 2 tests on Moto G4
  * 70 benchmarks on Moto G4
* Mac (10 Moto G4, 1 A02, 4 Pixel 7 Pro)
  * 11 tests on Moto G4
  * 2 benchmarks on Moto G4
* Windows (6 Moto G4, 0 A02, 0 Pixel 7 Pro)
  * 6 tests on Moto G4
  * 1 benchmark on Moto G4

### Linux

We can start moving the benchmarks from Moto G4 to A02 today. Ideally, we'd have 15 A02s to match the 15 Moto G4s with the same breakdown between prod/staging/try.

One test on Linux can be shifted to Pixel 7 today, the other is blocked on:
- [ ] https://github.com/flutter/flutter/issues/140420

### For Mac

The 11 tests should be possible to move to the Pixel 7 Pros today. 1 benchmark must be retained and will require one A02 in prod and one in staging, so we'll need 2 total A02s on Mac.

### For Windows

The 6 tests on Windows can't be moved today without hooking up some Pixel 7 Pros to the Windows machines. The 1 benchmark must be retained but can run on an A02 with one in prod and one in staging.

### Summary

* Linux:
  * Would ideally like 15 total A02s with the same breakdown between prod/staging/try as the Moto G4s. We can remove Moto G4 capacity if there aren't enough hosts.
* Mac:
  * Need 2 total A02s with one in prod and one in staging
  * Will likely need more Pixel 7 Pros to cover the increased load, maybe 5 total?
* Windows:
  * Need 2 total A02s with one in prod and one in staging
  * For Pixel 7 Pros:
    * First, swap out 3 Moto G4s for Pixel 7 Pros. Then we can update the .ci.yaml to move tests from Moto G4s to Pixel 7 Pros. If we need more Pixel 7 Pros at that point we can hook up more. Otherwise we can just disconnect the Moto G4s.

I have 8 more Pixel 7 Pros under my desk, but it looks like we may need to buy a few more A02s?

cc @yusuf-goog

**Comment by yusuf-goog** [comment]
Given that capacities are currently split by the pools (`prod` and `staging`), here are the current device breakdowns per pool. We should evaluate what the right balancing should be between the two as well as mitigate the hard separation if possible:

## Prod pool

### Linux
23 Pixel 7 Pro
7 A02s
13 Moto G4

### Mac
1 Pixel 7 Pro
4 Moto G4

### Win
4 Moto G4

## Staging pool

### Linux
10 Pixel 7 Pro
5 A02s
1 Moto G4

### Mac
2 Pixel 7 Pro
3 Moto G4

### Win
2 Moto G4

**Comment by yusuf-goog** [comment]
Started acquisition of additional A02s devices to reach expected capacity.

**Comment by zanderso** [comment]
Closing as obsolete.
