### ISSUE TITLE
Upgrade release bots in pool luci.dart-internal.flutter to macOS 13

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#140835]
### Type of Request

infra task

### Infrastructure Environment

LUCI / Devicelab

### What is happening?

Before we can run tests exclusively on macOS 13, we need macOS 13 bots in `luci.dart-internal.flutter`.

We should also ensure adding/upgrading bots to macOS 13 should not adversely effect anything currently running in that pool.

**Comment by jmagman** [comment]
Not sure if this should be with infra or release, but starting with release.

I believe this is the pool used for release builds like https://ci.chromium.org/ui/p/dart-internal/builders/flutter/Mac%20Production%20Engine%20Drone/9295/overview

We need simultaneous macOS 12 and macOS 13 bot capacity to let macOS 13 "bake" in master to support both versions in case there's a revert.  Not having macOS 13 bots is preventing us from upgrading Xcode in CI, which is blocking us testing the September 2023 iOS release in CI (building against the SDK, testing on simulators, and testing on physical devices in the lab).  See https://github.com/flutter/flutter/issues/134737 and https://github.com/flutter/flutter/issues/133207.  Testing on the latest version of iOS is a high priority, as that is what most Flutter developers and their users are currently on.

@CaseyHillers could you drive getting the macOS 13 capacity you need in the release pool so dev and stable releases go smoothly?  Or direct me to who should drive this work?  We would like to flip this switch ASAP.  🙂

**Comment by drewroengoogle** [comment]
@yusuf-goog Would this make sense to assign to you?

**Comment by yusuf-goog** [comment]
Change to enable rosetta on dart-internal.flutter is merged in.

**Comment by yusuf-goog** [comment]
b/317257696 is still open for the proposed move. I have requested an ETA for completion.

**Comment by vashworth** [comment]
> The plan is to have some mac-13 and some mac-12 bots in the dart-internal.flutter for the immediate future. @vashworth please let me know if that is fine.

As far as I'm aware of this should be fine. @CaseyHillers may know more

**Comment by vashworth** [comment]
> b/317257696 is still open for the proposed move. I have requested an ETA for completion.

@yusuf-goog Looks like all macOS 13 bots being moved in are arm64, do we plan to upgrade/move x86 ones?

**Comment by yusuf-goog** [comment]
We do plan on upgrading all our macs to 13 eventually.

**Comment by jmagman** [comment]
> We do plan on upgrading all our macs to 13 eventually.

(Good catch @vashworth)
I think she means we would need some x86 Macs to be upgraded in this batch since building iOS still requires non-ARM Macs with `drone_dimensions` `cpu=x86` like:
https://ci.chromium.org/ui/p/dart-internal/builders/flutter/Mac%20Production%20Engine%20Drone/9307/overview

**Comment by vashworth** [comment]
@godofredoc moved some builds to be able to use arm64 (https://github.com/flutter/engine/pull/49540)

However as @jmagman mentioned, there are still some builds that require x86 so be able to migrate the engine to macOS 13, we'll need macOS 13 x86 bots in this pool

**Comment by vashworth** [comment]
I believe this is done now. Bot have been moved.
