### ISSUE TITLE
Consider moving Material and Cupertino to a separate package 

### ISSUE THREAD

**Issue by ricardodalarme** [flutter/flutter#140827]
### Use case

Currently, the Material and Cupertino packages are tightly integrated into the Flutter framework. It would be beneficial to consider moving these design languages into separate packages. This could provide advantages such as:

- **Modularity:** Users who don't require Material or Cupertino design can save space by excluding unnecessary packages.
- **Customization:** Developers who wish to use a custom design language can easily replace or modify the existing packages.
- **Reduced Package Size:** The core Flutter package would have a smaller footprint, making it more lightweight for users with specific design requirements.
- **Faster Updates:** Separating Material and Cupertino into independent packages would enable quicker delivery of updates to these design languages, allowing developers to access new features and improvements more promptly.
- **Platforms Development Independence:** Developers targeting desktop or web platforms might not require Material or Cupertino design paradigms, and separating these packages could streamline desktop development by removing unnecessary dependencies.

### Proposal

Separate Material and Cupertino design languages into their own packages, making them optional dependencies for developers who need them.

**Comment by ricardodalarme** [comment]
My primary use case revolves around empowering developers to craft their unique design systems. While having the Material/Cupertino components readily available is undoubtedly beneficial, in scenarios where a custom design system takes precedence, these components might not align seamlessly.

For developers who want to use their own design language and still use the occasional Material/Cupertino component, they could have a lightweight package in their project, say "native_ui_widgets_package", that exports specific widgts, like a dialog, when needed.

**Comment by darshankawar** [comment]
Thanks for the detailed report @ricardodalarme 
I think the use case seems similar to https://github.com/flutter/flutter/issues/101479, so I suggest you to follow-up in it for further updates.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.
