### ISSUE TITLE
MacOS Xcode Cloud missing .dylib

### ISSUE THREAD

**Issue by Bilonik** [flutter/flutter#140887]
### Steps to reproduce

1.Install a package like realm-dart.
2.Archive with Xcode Cloud for MacOS

### Expected results

On local machine when I Archive and upload to Appstore my package contains all the .dylib

![dylib-MacOS](https://github.com/flutter/flutter/assets/8235588/9793adec-fca9-45f7-b84d-92c2a67df202)

### Actual results

On Xcode Cloud when it archive the artifact is missing those dylib.

![missing_dylib](https://github.com/flutter/flutter/assets/8235588/938efe4f-a7cf-4367-9d28-c7aa339df306)

### Code sample

<details open><summary>Code sample</summary>
this is my ci_post_clone.sh

```bash
#!/bin/sh

# The default execution directory of this script is the ci_scripts directory.
cd $CI_PRIMARY_REPOSITORY_PATH # change working directory to the root of your cloned repo.
# Install Flutter using git.
git clone https://github.com/flutter/flutter.git --depth 1 -b stable $HOME/flutter
export PATH="$PATH:$HOME/flutter/bin"

# Install Flutter artifacts for iOS (--ios), or macOS (--macos) platforms.
flutter precache --macos

# Install Flutter dependencies.
flutter pub get

# Install CocoaPods using Homebrew.
HOMEBREW_NO_AUTO_UPDATE=1 # disable homebrew's automatic updates.
brew install cocoapods

dart run realm_dart install

cd macos && pod install

flutter build macos

exit 0
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.2.1 23C71 darwin-arm64, locale en-US)
    • Flutter version 3.16.5 on channel stable at /opt/homebrew/Caskroom/flutter/2.8.1/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (2 weeks ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @Bilonik 

> Install a package like realm-dart.

Is this package a dynamic or static ? and whether it has SPM as a dependency ?

If yes, could you try with static library and confirm if you still get same behavior as reported ?

You may check [this](https://stackoverflow.com/questions/70388272/xcode-cloud-cant-upload-archive-that-has-embeded-package-dependencies) for reference and see if it helps in your case or not:

**Comment by Bilonik** [comment]
Hi @darshankawar ,

This is a cocoa pod package it doesn't have any SPM as a dependency.

**Comment by darshankawar** [comment]
Thanks for the update. I currently don't have the Xcode cloud setup to verify this, but locally, it seems to work as expected.
Based on the report, keeping this issue open for team's tracking.

**Comment by jmagman** [comment]
Your Xcode Cloud screenshot shows a `realm.framework` bundle that's not present in the archive (don't worry about the other missing dylibs, that's Swift runtime stuff handled by Xcode).  I don't know why there would be a difference, but it sounds like it has nothing to do with Flutter tooling.  Is there actually a problem with your macOS app or does it work as expected?

If you are actually seeing a runtime issue with your Xcode Cloud deployed app, I suggest [filing an issue with Realm](https://github.com/realm/realm-dart/issues) though it may be some behavior from Xcode that's swapping it from a dylib to a framework bundle.
