### ISSUE TITLE
[Impeller] new blur: expand coverage clip to work for rotated entities

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#140890]
Spawned from https://github.com/flutter/engine/pull/49299

We landed that optimization just for translation and scaling transforms to capture backdrop filters.  It wasn't working with rotation.  It's lower priority but would be ideal that the optimization works for that as well, just drawing the uv's for the AABB that contains the rotated entity.

See Brandon's comment here: https://github.com/flutter/engine/pull/49299#discussion_r1433654462

**Comment by jonahwilliams** [comment]
@gaaclarke is this something that you are working on as a follow up?
