### ISSUE TITLE
Analysis failure in DevTools Flutter customer tests from Dart 3.3.0-277.0.dev

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#140881]
The roll here https://github.com/flutter/engine/pull/49478 of Dart 3.3.0-277.0.dev contains the commit https://dart.googlesource.com/sdk.git/+/a7e1e26446a0debcd54984afdf8d0de554469325, which is causing Flutter customer_tests to fail. In particular there are new lints in Flutter DevTools:

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8759921046735080641/+/u/run_test.dart_for_customer_testing_shard_and_subshard_None/test_stdout

(In those logs, search for the new error message added in the above Dart SDK commit.)

I have reverted the Dart SDK roll here https://github.com/flutter/engine/pull/49491, and stopped the Dart -> Engine autoroller.

cc @parlough @pq @srawlins @bwilkerson

**Comment by zanderso** [comment]
Here is a revert of the Dart SDK change https://dart-review.googlesource.com/c/sdk/+/344560

**Comment by srawlins** [comment]
Thanks for tracking this, @zanderso and posting the logs. Revert SGTM, and we can clean up the customer tests, and re-check them with the re-land.

**Comment by parlough** [comment]
Sorry about that. I'll work on getting the customer tests updated.

@srawlins I forgot the exact status. Are we able to add them as a try bot yet?

**Comment by srawlins** [comment]
The `flutter-analyze` bot _should_ be running the customer tests today. Available as a try-bot.

I also created [a little script](https://gist.github.com/srawlins/b66dcecb9a93546891cb5f35a2407afa) to run them all, but it's pretty dopey and assumes all the repos are cloned into specific directory names. The big reason it may be useful is that it just does the analysis part of the customer tests - no running actual tests.

**Comment by zanderso** [comment]
I think I saw some messages from @whesse that some of the monorepo builds might not be running/working currently.

**Comment by zanderso** [comment]
A revert landed in the Dart SDK, and the Dart -> Engine roll is caught up.
