### ISSUE TITLE
Move Windows 7 and 8 to unsupported tier; increase minimum supported Windows version to Windows 10

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#140830]
## Overview
This issue proposes to raise the minimum supported version of Windows from Windows 7 to Windows 10 for Flutter Desktop applications.

RFC: http://flutter.dev/go/flutter-drop-win7-2024

## Steps prior to stable release
* [x] Publish [proposal to raise minimum version](https://docs.google.com/document/d/18gfRT8klo0zEvn6fIpders7ghoWIBKO22cNYS22WLhc/edit?resourcekey=0-SFkxdqfyM6KNNkG4zS6aaA). Collect feedback.
* [x] Send email to [flutter-announce](https://groups.google.com/g/flutter-announce) notifying end-of-support timeline.
* [x] Update Windows templates (e.g. [runner.exe.manifest](https://github.com/flutter/flutter/blob/master/examples/api/windows/runner/runner.exe.manifest)).
* [x] Update [supported-platforms.md](https://github.com/flutter/website/blob/main/src/reference/supported-platforms.md).
* [x] Update release notes with new minimums.

Flutter already requires Windows 10 or later for development and includes a [doctor](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/windows/windows_version_validator.dart) check for this, so no `flutter doctor` changes are required.

## Steps post stable release
* [x] Close all Windows 7 and 8 specific issues in the issue tracker with a comment pointing to this issue and the RFC linked here.

## Optional
* [ ] Eliminate Windows 7 specific workarounds in the engine. (e.g. [dpi_utils.cc](https://github.com/flutter/engine/blob/166ccf6097fa5250d2bef5d78a228c3343c6e0f2/shell/platform/windows/dpi_utils.cc#L67-L85))

## Related
Dart tasks: https://github.com/dart-lang/sdk/issues/54509

**Comment by parlough** [comment]
Please add a step to add a page and entry to https://docs.flutter.dev/release/breaking-changes. 

This can happen before the release, perhaps before the announcement so you can link to it from there.

If there’s anything users need to (or can/should) change in their Windows specific files (that they added or from the template), please make sure that is included.

Thank you!!

**Comment by brianquinlan** [comment]
What's the time frame for collecting feedback?

**Comment by brianquinlan** [comment]
It's been over a month - can we say that the feedback period is over?

**Comment by cbracken** [comment]
We had been waiting on feedback from China customers via Google-internal contacts. We have that feedback now and this was discussed amongst Dart/Flutter team staff. The consensus is that we'll be moving ahead with this work.

Flutter 3.19 / Dart 3.3 expected to launch this month (Feb 2024) will be the last set of stable releases to support Windows 7. Customers who require Windows 7 support will need to pin to these releases.

Following the release, we will no longer accept PRs, and we'll close remaining issues specific to Windows 7 (or extract relevant non Windows 7 parts to new issues).

**Comment by cbracken** [comment]
We have cut the last Windows 7/8 release and I have closed all remaining issues specific to Windows 7.
