### ISSUE TITLE
Run flutter/flutter tests on 3.16 stable release on either macOS 12 or macOS 13

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#140895]
Before we can upgrade remaining bots to macOS 13, we need the stable branch to be able to run on macOS 13.

The flutter/flutter tests have been running on master since Nov 28 and the change is already in 3.18 beta.

Once this is done, all devicelab bots can be upgraded to macOS 13.

**Comment by keyonghan** [comment]
Assigning to @vashworth as you are working on the CPs.
