### ISSUE TITLE
JAVA_HOME is set to an invalid directory: 

### ISSUE THREAD

**Issue by mo7amedaliEbaid** [flutter/flutter#140848]
### Steps to reproduce

- Error.
```
ERROR: JAVA_HOME is set to an invalid directory: /usr/lib/jvm/openjdk-11

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

Exception: Gradle task assembleDebug failed with exit code 1
```
I went to this directory and found 

<p float="left">
  <img src="https://github.com/flutter/flutter/assets/131966482/39e224dc-f640-4e70-bad3-43c6b79eedd8" width="570" />
</p>    

- I have changed the default JAVA_HOME path to 
<p float="left">
  <img src="https://github.com/flutter/flutter/assets/131966482/6fb9a9fd-92ff-4445-99b2-1a1899d30d91" width="570" />
</p>    
<p float="left">
  <img src="https://github.com/flutter/flutter/assets/131966482/720bd66e-8815-4372-9701-4a5ec079722f" width="570" />
</p>    

- after changing the defalut java home path, i still get this error.
```
ERROR: JAVA_HOME is set to an invalid directory: /usr/lib/jvm/openjdk-11

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

Exception: Gradle task assembleDebug failed with exit code 1
```

### Expected results

The Default JAVA-HOME path should change in android studio too, since i have changed it on my computer.
at least that what i think should happen.

### Actual results

I get the same error which contain the previous directory

### Code sample

```
ERROR: JAVA_HOME is set to an invalid directory: /usr/lib/jvm/openjdk-11

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by huycozy** [comment]
Hi @mo7amedaliEbaid 
I wonder if this is a Flutter issue or your environment setup issue. Which Flutter command produced that error? Can you share the output of `flutter doctor -v` and `java --version`?

**Comment by mo7amedaliEbaid** [comment]
- flutter doctor -v

```
[✓] Flutter (Channel stable, 3.10.5, on Ubuntu 20.04.2 LTS
    5.15.6-051506-generic, locale en_US.UTF-8)
    • Flutter version 3.10.5 on channel stable at
      /home/user/flutter/flutter_linux_3.0.5-stable/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (7 months ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/user/Android/Sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: /usr/lib/jvm/openjdk-11/bin/java
    ✗ Cannot execute /usr/lib/jvm/openjdk-11/bin/java to determine the version

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (version 2023.1)
    • Android Studio at /snap/android-studio/140
    • Flutter plugin version 76.3.3
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.2 LTS
      5.15.6-051506-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 98.0.4758.102

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

- java --version

```
openjdk 11.0.21 2023-10-17
OpenJDK Runtime Environment (build 11.0.21+9-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.21+9-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)
```

@huycozy

**Comment by mo7amedaliEbaid** [comment]
- I don't know what caused this issue.
- I was working in a project at night , and every thing was working perfectly fine.
- When I opened the project in the morning i faced this issue.
- Without updating any thing or running any command line.

**Comment by huycozy** [comment]
>✗ Cannot execute /usr/lib/jvm/openjdk-11/bin/java to determine the version

I see this error from your Flutter doctor output. Could you also share the output of `update-java-alternatives --list` and `echo $JAVA_HOME`?

This is my results:

```console
huynq@ubuntu:~$ update-java-alternatives --list
java-1.11.0-openjdk-amd64      1111       /usr/lib/jvm/java-1.11.0-openjdk-amd64
java-1.17.0-openjdk-amd64      1711       /usr/lib/jvm/java-1.17.0-openjdk-amd64
jdk-21-oracle-x64              352321536  /usr/lib/jvm/jdk-21-oracle-x64
huynq@ubuntu:~$ echo $JAVA_HOME
/usr/lib/jvm/java-17-openjdk-amd64
```

You can try setting Java version with `sudo update-alternatives --config java` to see if it helps (see full solution [here](https://stackoverflow.com/a/73159429)). 

Maybe also related: https://github.com/flutter/flutter/issues/108618

**Comment by mo7amedaliEbaid** [comment]
- sudo update-alternatives --config java.
```
There are 2 choices for the alternative java (providing /usr/bin/java).

  Selection    Path                                         Priority   Status
------------------------------------------------------------
  0            /usr/lib/jvm/java-11-openjdk-amd64/bin/java   1111      auto mode
  1            /usr/lib/jvm/java-11-openjdk-amd64/bin/java   1111      manual mode
* 2            /usr/lib/jvm/jdk-16/bin/java                  1         manual mode

Press <enter> to keep the current choice[*], or type selection number: 0
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/java to provide /usr/bin/java (java) in auto mode
```

- update-java-alternatives --list.

```
java-1.11.0-openjdk-amd64      1111       /usr/lib/jvm/java-1.11.0-openjdk-amd64
```
- echo $JAVA_HOME
```
/usr/lib/jvm/openjdk-11
```
- I already followed the steps in the solution you shared [Its Link](https://stackoverflow.com/questions/73159428/error-java-home-is-set-to-an-invalid-directory-please-set-the-java-home-variab/73159429#73159429).

- And I think i have changed the JAVA-HOME default directory in my computer, because I also followed the solutions in [This Questions](https://stackoverflow.com/questions/1117398/java-home-directory-in-linux).
- and Used **(dirname $(dirname $(readlink -f $(which javac))))** and the result is
```
/usr/lib/jvm/java-11-openjdk-amd64
```
- But with echo $JAVA-HOME the result is the old directory.
- I mean In Android Studio the Path doesn't been updated.
- I don't know is it a problem with android studio or flutter set up.

**Comment by darshankawar** [comment]
@mo7amedaliEbaid 
Please see if below links helps in your case or not:

https://github.com/flutter/flutter/issues/124013#issuecomment-1498206506
https://github.com/flutter/flutter/issues/124013#issuecomment-1499450287
https://github.com/flutter/flutter/issues/124013#issuecomment-1500564986

**Comment by mo7amedaliEbaid** [comment]
Thanks @huycozy and @darshankawar 
The Problem is solved by Upgrading the Flutter SDK
```
flutter upgrade
```
