### ISSUE TITLE
Dont recognize a Xiaomi Device 

### ISSUE THREAD

**Issue by Geinersb** [flutter/flutter#140807]
### Steps to reproduce

select device dont show my device

### Actual results

dont recognize Xiaomi Device POCO 5G
[☠] Connected device (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    X Exception: Connected device exceeded maximum allowed duration of 0:04:30.000000
    • 

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

[☠] Connected device (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    X Exception: Connected device exceeded maximum allowed duration of 0:04:30.000000
    • 

</details>

**Comment by darshankawar** [comment]
Looking at the error, it looks similar to https://github.com/flutter/flutter/issues/125488, so please follow-up in it for further updates.
Closing as duplicate.
