### ISSUE TITLE
Android Kotlin 

### ISSUE THREAD

**Issue by YahyaAtta** [flutter/flutter#140811]
I Have Suggestion please Implement Kotlin 2.0 compiler (K2 ) (optional) and Kotlin DSL(optional) when you create project in Android flutter when in stable release

**Comment by darshankawar** [comment]
@YahyaAtta 
I think your issue is similar to https://github.com/flutter/flutter/issues/93238 so please followup in it for further updates.
Closing as duplicate.
Also see https://github.com/flutter/flutter/issues/121541 for reference.
