### ISSUE TITLE
Connect Firebase with flutter on android 2024

### ISSUE THREAD

**Issue by lualbertovargas** [flutter/flutter#140847]
Actualmente no hay información reciente o el por que para nuevos usuarios de diversos errores el común es; 
`https://github.com/flutter/flutter/issues/115477`

Parte de los errores son: `sale 
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\l-----\android\app\build.gradle' line: 28

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not get unknown property 'flutterRoot' for project ':app' of type org.gradle.api.Project.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Exception: Gradle task assembleDebug failed with exit code 1`

**Comment by lualbertovargas** [comment]
Lo que debes hacer para solucionar esto es:
app/build.gradle

Esto que vaya afuera de todo:
`apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'`

y en `dependencies {
    implementation platform("com.google.firebase:firebase-bom:32.7.0")
    implementation "com.google.firebase:firebase-analytics"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
}`


**En Build.gradle exactamente en la versión de Kotlin actualiza a la última versión**
en `buildscript {
    ext.kotlin_version = '1.9.21'
    repositories {
        google()
        mavenCentral()
    }

`


`dependencies {
        classpath 'com.android.tools.build:gradle:7.0.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.4.0'
    }`


**Recuerda instalar firebase_core**
En tu main.dart usa:

**Liberia**
`import 'package:flutter/material.dart';
import 'package:flutter/services.dart';`

**using**
`void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const MyApp());
}`

**Comment by lualbertovargas** [comment]
**Sigue estos pasos y suerte en desarollo con Flutter **

**Comment by darshankawar** [comment]
@lualbertovargas 
When you file an issue, please try to avoid non-English language and try to provide details in English so that it'll be easy to understand.
Looking at the error, I think it is better suited to ask in support channels like StackOverflow, as it looks more like a setup / config issue rather than a bug.
Closing from here.
