### ISSUE TITLE
Offer a way to catch Image Decoding errors

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#14089]
My understanding from @apwilson and @jxson is that Flutter doesn't currently offer a way to catch decoding errors (at least from NetworkImage).

Decoding errors were hit today by @jxson in https://github.com/flutter/flutter/issues/14077 and https://github.com/flutter/flutter/issues/14074 which is why this came up.

Maybe https://github.com/flutter/flutter/issues/5741 is a solution?  Maybe this should just be duped to that?

**Comment by zoechi** [comment]
I think I run into this as well today. The exception inly told that it failed to load the codec

**Comment by jxson** [comment]
I believe there are two areas where errors can occur and should be surfaced, one is network errors (covered by #5741) the other is decoder specific. Perhaps both can use the same listener interface to surface errors down in the network and decoding layers...

**Comment by Hixie** [comment]
Our solution here should probably be similar to our solution for https://github.com/flutter/flutter/issues/15325.

**Comment by Hixie** [comment]
See also https://github.com/flutter/flutter/issues/9676.

**Comment by tonyhelloworld** [comment]
大佬，怎么解决这个错误呢
[ERROR:flutter/lib/ui/painting/codec.cc(89)] Failed decoding image. Data is either invalid, or it is encoded using an unsupported format.

**Comment by tonyhelloworld** [comment]
the last question,The problem has already been solved。chage Image URL Can be

**Comment by jonahwilliams** [comment]
This could potentially be addressed by the changes in https://github.com/flutter/flutter/pull/17614.

**Comment by cbracken** [comment]
@jonahwilliams is this safe to close now?

**Comment by jonahwilliams** [comment]
I believe the last of this was completed with https://github.com/flutter/flutter/pull/25980, closing
