### ISSUE TITLE
TextInputType.emailAddress not working on Android (Xiaomi devices)

### ISSUE THREAD

**Issue by jtdLab** [flutter/flutter#140850]
### Steps to reproduce

Create a `TextField` with `TextInputType.emailAddress`.

### Expected results

Shows keyboard with @.

### Actual results

Standard keyboard without @

**Comment by dam-ease** [comment]
Hello @jtdLab.
Thanks for filing these.
Is this peculiar to only Xiaomi devices, I don't have one and can't reproduce on my Android device.
Can you please provide more information on this as indicated in the template? More specifically, 

- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of flutter doctor -v
- A screen record of the issue on your end 

Thank you!

**Comment by jtdLab** [comment]
The error was due to `enableSuggestions` beeing `false`.
