### ISSUE TITLE
Upgrade iOS devices in staging pool to iOS 17

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#140908]
### Type of Request

infra task

### Infrastructure Environment

Devicelab

### What is happening?

After Upgrade Phase 3 of https://github.com/flutter/flutter/issues/134737, all devicelab bots in the staging pool should be on macOS 13, which makes it safe to upgrade the devices to iOS 17.

After upgrading to iOS 17, we'll want to manually launch an app from Xcode at least once. This is because after upgrading, debug symbols need to be copied and this can be a slow process. This should show in a Xcode dialog on app launch.

**Comment by yusuf-goog** [comment]
@kentnguyen99 please upgrade the following iOS devices that are connected to macOS13 hosts:

flutter-devicelab-mac-5
flutter-devicelab-mac-40
flutter-devicelab-mac-4
flutter-devicelab-mac-39
flutter-devicelab-mac-26
flutter-devicelab-mac-23
flutter-devicelab-mac-11
flutter-devicelab-mac-10

**Comment by kentnguyen99** [comment]
Following machines below have been upgraded and running MacOS version 13.6.1.
flutter-devicelab-mac-5
flutter-devicelab-mac-40
flutter-devicelab-mac-4
flutter-devicelab-mac-39
flutter-devicelab-mac-26
flutter-devicelab-mac-23
flutter-devicelab-mac-11
flutter-devicelab-mac-10

**Comment by kentnguyen99** [comment]
All iPhone devices on this listing have been upgraded to iOS 17.2.1 as requested and done.

**Comment by vashworth** [comment]
@kentnguyen99 did you launch an app via Xcode for each device?

**Comment by vashworth** [comment]
Looks like the devices are not paired with the mac. You'll probably need to launch an app via Xcode and accept any dialogs that show on the device

**Comment by vashworth** [comment]
If you get the dialog on the device twice, you may need to accept it once, disconnect, reconnect, and accept again.

**Comment by vashworth** [comment]
Looks like everything is working correctly now. Thanks @kentnguyen99

**Comment by yusuf-goog** [comment]
@kentnguyen99 please update docs to add steps needed for device upgrade/verfication in future.

**Comment by kentnguyen99** [comment]
Here are steps after upgraded new iOS 17.2.1 on iPhone devices.

1. Open Xcode 15 from /opt/flutter/xcode/15a240d/[XCode.app](http://xcode.app/)
2. In the top bar, open Window > Device and Simulators
3. The window that opens should show the connected device
4. Accept the Trust dialog on the iPhone device
5. Wait for the yellow bar at the top of the Device and Simulators window to go away - It should take a minute or so to Copy cache symbols
