### ISSUE TITLE
Gradle 5.0 deprecation warning.

### ISSUE THREAD

**Issue by asaarnak** [flutter/flutter#14099]
`flutter run --release -v` 
or from android/ folder `gradlew --warning-mode=all`

Plugin warning:
```bash
> Configure project :firebase_analytics 
The CompileOptions.bootClasspath property has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the CompileOptions.bootstrapClasspath property instead.
```
App warning:
```bash
The CompileOptions.bootClasspath property has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the CompileOptions.bootstrapClasspath property instead.
        at build_4ltncrt617auxmr13cdrhda1c$_run_closure3.doCall(/home/allar/A/PROJECTS/be_smart/android/build.gradle:27)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
```

Fix the warning on my app with these settings. Plugin still gives warning.
```gradle
android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
```
https://stackoverflow.com/a/47598033/4677270

**Comment by mit-mit** [comment]
cc @mravn-google do we still have this issue?

**Comment by mravn-google** [comment]
Yes. The deprecated API is being used by the Android Studio Gradle plugin version 3.0.1. Upgrading to version 3.1.2 removes the warning. A standard Android Studio project exhibits the same behavior, so it is not Flutter-specific, except our project templates still refer to version 3.0.1.

Tracking in https://github.com/flutter/flutter/issues/16215
