### ISSUE TITLE
file_selector_android_example/MainActivityTest.java uses or overrides a deprecated API

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#140988]
Failing on an unrelated PR https://github.com/flutter/packages/pull/5804
```
> Task :app:compileDebugAndroidTestJavaWithJavac
 Note: /b/s/w/ir/x/w/packages/packages/file_selector/file_selector_android/example/android/app/src/androidTest/java/dev/flutter/packages/file_selector_android_example/MainActivityTest.java uses or overrides a deprecated API.
 Note: Recompile with -Xlint:deprecation for details.
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8759794309036325969/+/u/Run_package_tests/native_integration_tests/stdout

Code:
https://github.com/flutter/packages/blob/main/packages/file_selector/file_selector_android/example/android/app/src/androidTest/java/dev/flutter/packages/file_selector_android_example/MainActivityTest.java

**Comment by jmagman** [comment]
cc codeowner @gmackall 🙂

**Comment by bparrishMines** [comment]
This should be fixed by https://github.com/flutter/packages/pull/5805

**Comment by gmackall** [comment]
Thanks for the cc, followed up on the linked pr

**Comment by jmagman** [comment]
Thanks, closing then.

**Comment by jmagman** [comment]
Wait @bparrishMines this is a deprecation warning during compilation, why would closing a system dialog fix it?

**Comment by gmackall** [comment]
> Wait @bparrishMines this is a deprecation warning during compilation, why would closing a system dialog fix it?

I don't think the deprecation notice in the linked logs are whats causing the failure here, notably camerax has the same deprecation notice 
```
Note: /b/s/w/ir/x/w/packages/packages/camera/camera_android_camerax/example/android/app/src/androidTest/java/io/flutter/plugins/cameraxexample/MainActivityTest.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```
and also notably the file selector tests have the same failures that the pr by @bparrishMines fixes 
```
dev.flutter.packages.file_selector_android_example.FileSelectorAndroidTest > openImageFile[android_34_google_apis_x64(AVD) - 14] [31mFAILED [0m
	androidx.test.espresso.base.RootViewPicker$RootViewWithoutFocusException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root:
	Root{application-window-token=android.view.ViewRootImpl$W@9b7ea29, window-token=android.view.ViewRootImpl$W@9b7ea29, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={adjust=resize forwardNavigation} ty=BASE_APPLICATION wanim=0x1030001

dev.flutter.packages.file_selector_android_example.FileSelectorAndroidTest > openImageFiles[android_34_google_apis_x64(AVD) - 14] [31mFAILED [0m
	androidx.test.espresso.base.RootViewPicker$RootViewWithoutFocusException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root:
	Root{application-window-token=android.view.ViewRootImpl$W@7337fc, window-token=android.view.ViewRootImpl$W@7337fc, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={adjust=resize forwardNavigation} ty=BASE_APPLICATION wanim=0x1030001
Tests on android_34_google_apis_x64(AVD) - 14 failed: There was 2 failure(s).
```

**Comment by jmagman** [comment]
Oh it's a note not an error.  Sorry for the noise I shouldn't pretend to know how to read Android.  :)

**Comment by gmackall** [comment]
No worries! Happy to help

**Comment by bparrishMines** [comment]
> Wait @bparrishMines this is a deprecation warning during compilation, why would closing a system dialog fix it?

Sorry @jmagman. I should of explained how the PR fixed it. I was referring to the error in the link you provided as @gmackall explained. Thanks!
