### ISSUE TITLE
Codesign `Flutter.xcframework` bundle

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#140934]
Flutter iOS XCFrameworks now need to be codesigned, not just the framework binaries within them.  This will be [enforced by Xcode at some point in Spring 2024](https://developer.apple.com/news/?id=r1henawx).

```
codesign --sign "Apple Developer cert etc" ... path/to/Flutter.xcframework
```

> Now with signatures for SDKs, when you adopt a new version of a third-party SDK in your app, Xcode will validate that it was signed by the same developer, improving the integrity of your software supply chain.

https://developer.apple.com/support/third-party-SDK-requirements/

In Xcode Flutter.xcframework is marked as unsigned:
![Screenshot 2024-01-03 at 4 36 25 PM](https://github.com/flutter/flutter/assets/682784/0c12028c-d5a8-4c64-9a3e-1a40549ff9f4)

Note `xcframework` is a directory (bundle), not a binary.  Also the `extension_safe` XCFramework needs to be signed as well.

### Relevant code
Conductor:
https://github.com/flutter/flutter/blob/1082342f8d6c27f61d8b17071bbcbb769a909538/dev/conductor/core/lib/src/codesign.dart#L192-L211
Engine:
https://github.com/flutter/engine/blob/ab4098c742f85518ae5e9773b8a2c1be181cef32/sky/tools/create_full_ios_framework.py#L212-L217
And then wherever the codesigning actually happens.

### Docs
https://developer.apple.com/documentation/xcode/verifying-the-origin-of-your-xcframeworks
https://developer.apple.com/videos/play/wwdc2023/10060/
https://developer.apple.com/videos/play/wwdc2023/10061/?time=878
![Screenshot 2024-01-03 at 4 35 03 PM](https://github.com/flutter/flutter/assets/682784/bf567f8f-a38f-43ff-a2db-d32c7e5b163c)

cc @XilaiZhang @vashworth @stuartmorgan 
Related to privacy manifest work https://github.com/flutter/flutter/issues/131494

**Comment by godofredoc** [comment]
Conductor codesigning code was deprecated and removed. 

It seems like three streams of work are needed:

- [ ] Update the codesigning cli to codesign full directories
- [ ] Update create_full_ios_framework.py#L212-L217 to include the new directories and/or files in the codesigning metadata
- [ ] Update codesigning tests: https://cs.opensource.google/flutter/flutter/+/master:dev/bots/test.dart;l=1661, https://cs.opensource.google/flutter/flutter/+/master:dev/bots/test.dart;l=1678 and https://cs.opensource.google/flutter/flutter/+/master:dev/bots/test.dart;l=1691

**Comment by godofredoc** [comment]
@XilaiZhang please provide regular updates of your findings using this bug

**Comment by jmagman** [comment]
I believe if you codesign the `xcframework` you will no longer need to codesign the executables in the framework.  So the list of file entities to codesign without entitlements would change from
```
      'artifacts/engine/ios-profile/Flutter.xcframework/ios-arm64/Flutter.framework/Flutter',
      'artifacts/engine/ios-profile/Flutter.xcframework/ios-arm64_x86_64-simulator/Flutter.framework/Flutter',
      'artifacts/engine/ios-profile/extension_safe/Flutter.xcframework/ios-arm64/Flutter.framework/Flutter',
      'artifacts/engine/ios-profile/extension_safe/Flutter.xcframework/ios-arm64_x86_64-simulator/Flutter.framework/Flutter',
      'artifacts/engine/ios-release/Flutter.xcframework/ios-arm64/Flutter.framework/Flutter',
      'artifacts/engine/ios-release/Flutter.xcframework/ios-arm64_x86_64-simulator/Flutter.framework/Flutter',
      'artifacts/engine/ios-release/extension_safe/Flutter.xcframework/ios-arm64/Flutter.framework/Flutter',
      'artifacts/engine/ios-release/extension_safe/Flutter.xcframework/ios-arm64_x86_64-simulator/Flutter.framework/Flutter',
      'artifacts/engine/ios/Flutter.xcframework/ios-arm64/Flutter.framework/Flutter',
      'artifacts/engine/ios/Flutter.xcframework/ios-arm64_x86_64-simulator/Flutter.framework/Flutter',
      'artifacts/engine/ios/extension_safe/Flutter.xcframework/ios-arm64/Flutter.framework/Flutter',
      'artifacts/engine/ios/extension_safe/Flutter.xcframework/ios-arm64_x86_64-simulator/Flutter.framework/Flutter',
```
to just the xcframeworks:
```
      'artifacts/engine/ios-profile/Flutter.xcframework',
      'artifacts/engine/ios-profile/extension_safe/Flutter.xcframework',
      'artifacts/engine/ios-release/Flutter.xcframework',
      'artifacts/engine/ios-release/extension_safe/Flutter.xcframework',
      'artifacts/engine/ios/Flutter.xcframework',
      'artifacts/engine/ios/extension_safe/Flutter.xcframework',
```

**Comment by XilaiZhang** [comment]
Umm I read a post from Eskimo that says both the binaries and the framework might need to be signed in an inside-out order. Will create a PR with more info after lunch

**Comment by XilaiZhang** [comment]
Created https://github.com/flutter/cocoon/pull/3429 and sent for review. (Sorry for the delay, took quite a while to collect and learn all the information on bundles)

**Comment by jmagman** [comment]
> took quite a while to collect and learn all the information on bundles

Thank you for all the research, so thorough!

**Comment by XilaiZhang** [comment]
> Conductor codesigning code was deprecated and removed.
> 
> It seems like three streams of work are needed:
> 
> * [x]  Update the codesigning cli to codesign full directories
> * [ ]  Update create_full_ios_framework.py#L212-L217 to include the new directories and/or files in the codesigning metadata
> * [ ]  Update codesigning tests: https://cs.opensource.google/flutter/flutter/+/master:dev/bots/test.dart;l=1661, https://cs.opensource.google/flutter/flutter/+/master:dev/bots/test.dart;l=1678 and https://cs.opensource.google/flutter/flutter/+/master:dev/bots/test.dart;l=1691

The first step is completed, will pass the baton to Jenn to continue with step 2, thank you!

**Comment by jmagman** [comment]
@XilaiZhang is the `create_full_ios_framework` change still necessary since https://github.com/flutter/cocoon/pull/3429 will visit all the directories in the extracted artifact, including the xcframework?

**Comment by XilaiZhang** [comment]
Ah Good point! looks like we can jump directly to step 3

**Comment by XilaiZhang** [comment]
Follow up from release meeting: @jmagman were you successful in verifying bundles are codesigned in the newest release [3.19.0-0.3.pre](https://docs.flutter.dev/release/archive?tab=macos)?

**Comment by jmagman** [comment]
Looks great!
```
$ codesign -d -vv flutter/bin/cache/artifacts/engine/ios-release/Flutter.xcframework
Executable=flutter/bin/cache/artifacts/engine/ios-release/Flutter.xcframework/Info.plist
Identifier=Flutter
Format=bundle
CodeDirectory v=20200 size=199 flags=0x10000(runtime) hashes=1+3 location=embedded
Signature size=9058
Authority=Developer ID Application: FLUTTER.IO LLC (S8QB4VV633)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=Jan 25, 2024 at 4:07:04 PM
Info.plist entries=3
TeamIdentifier=S8QB4VV633
Sealed Resources version=2 rules=10 files=44
Internal requirements count=1 size=168
```

**Comment by SpajicM** [comment]
Hi, does this mean after spring 2024, apps on old versions of Flutter will not be able to be updated on App store?

**Comment by stuartmorgan** [comment]
> Hi, does this mean after spring 2024, apps on old versions of Flutter will not be able to be updated on App store?

Specific questions about what exactly will be enforced when and where would need to be directed to Apple. But in general, if you are using any SDKs on the list at https://developer.apple.com/support/third-party-SDK-requirements/ (which includes Flutter), the currently available docs suggest that at some point you will need to be using recent versions of all of those SDKs, since compliance requires SDK-level changes.

**Comment by jmagman** [comment]
@XilaiZhang I put https://github.com/flutter/flutter/pull/142666 out for review, is there any other spots you're aware of that need to be updated?

**Comment by XilaiZhang** [comment]
> @XilaiZhang I put #142666 out for review, are there any other spots you're aware of that need to be updated?

Thanks a lot for working on this! Approved and posted some comments
