### ISSUE TITLE
Recipe crashes in engine CI

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#140902]
Seeing some crashes in recipes on engine CI today.

https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Production%20Engine%20Drone/237006/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Production%20Engine%20Drone/236956/overview

**Comment by drewroengoogle** [comment]
I wonder if this is related to a recent CL involving the cache micro manager: https://flutter-review.googlesource.com/c/recipes/+/53221

It looks like it got reverted within the last hour at https://flutter-review.googlesource.com/c/recipes/+/53723, let me know if you see additional failures @zanderso 

CC @ricardoamador

**Comment by ricardoamador** [comment]
It is. I will go ahead and close this. There is some funky handling in the python that isn't quite right yet that I need to iron out.
