### ISSUE TITLE
RBE refactor - build fails to copy MacOSX SDK due to `Too many levels of symbolic links`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#140977]
RBE refactoring is WIP: https://github.com/flutter/engine/pull/49416.

`Linux mac_unopt` fails when copying MacOSX SDK to CAS: https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Engine%20Drone/606402/overview

> '/Volumes/Work/s/w/ir/x/w/recipe_cleanup/out-cas-directorysxzsrkv_/host_debug_unopt_arm64/gen/SDKs/MacOSX13.3.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/Headers/ruby/ruby/ruby/ruby/ruby/ruby/ruby/ruby/ruby/ruby/ruby/ruby/ruby/ruby/ruby/ruby/ruby/ruby/ruby/ruby/ruby/ruby/ruby/ruby/ruby/ruby/ruby/ruby/ruby/ruby/ruby/ruby', "[Errno 62] Too many levels of symbolic links:

**Comment by keyonghan** [comment]
`src/out/host_debug_unopt_arm64/gen/SDKs/MacOSX13.3.sdk` is a symlink pointing to `osx_sdk/xcode_14e300c/XCode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk`.

`Too many levels of symbolic links` happens due to some defult symlinks related to ruby from the xcode CIPD pacakge.

**Comment by keyonghan** [comment]
Have tried a couple of LED runs based on the [drone build](https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Engine%20Drone/606402/overview):

Failed:
[Attempt1](https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/d23c526ef7b98243fa4d966c621f00cd13d9b75b79a61e706415f2c73ca4c198/+/build.proto?server=chromium-swarm.appspot.com): remove symlink, copy target to src/out, copy directly from xcode/sdk (self.m.path['cache'].join('osx_sdk', 'xcode_14e300c', 'XCode.app', 'Contents', 'Developer', 'Platforms', 'MacOSX.platform', 'Developer', 'SDKs', 'MacOSX13.3.sdk') to build_dir.join('gen', 'SDKs', 'MacOSX13.3.sdk') - **Too many levels of symbolic links**
[Attempt2](https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/33468801d175148b6e9cbf8e8d63338368406d29a89c84789f0b100cebc5ffc3/+/build.proto?server=chromium-swarm.appspot.com): remove symlink, copy target to src/out, zip xcode/sdk - **Not all files were readable**
[Attempt3](https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/657af668e1814f6a3f269be595d761f2366de7b9132163b13c439e42dbe8989d/+/build.proto?server=chromium-swarm.appspot.com): remove symlink, copy target to src/out, recreate symlink in src/out pointing to xcode/sdk - **infra error when uploaded to cas**
[Attempt4](https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/77522f36ce6572781055468464a4dd44daab73873ee0463b5316f219ce1be50c/+/build.proto?server=chromium-swarm.appspot.com): copy target to src/out with symlinks=True - **infra error when uploaded to cas**

Succeeded:
[Attempt5](https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/a8e93abd187ce848238ae973be091bfba4c6fc211e6c384d4a5e82c27a741ae0/+/build.proto?server=chromium-swarm.appspot.com): remove symlink, copy target to src/out, upload without MacOS_SDK - **Pass**

**Comment by keyonghan** [comment]
Following up with the above Attempt5. By removing symlink and upload to CAS without MacOS_SDK, it also passes on parent build:
[Linux mac_unopt](https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/249312016e10be106fcbf9145791dcea2c9cd87be01ea6e561f6b4c73762f6da/+/build.proto?server=chromium-swarm.appspot.com)
[Mac mac_ios_engine](https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/fbd8c2508c461c7c3cd09d6e53f28045bb9b5735f75f37e7812b916cac0b3578/+/build.proto?server=chromium-swarm.appspot.com)
[Mac mac_host_engine](https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/78e77af2c4f1951f817b198136ac9467da78639dfbd7be7daa507f38ba26bebc/+/build.proto?server=chromium-swarm.appspot.com)

Since this affects only the digest uploaded to CAS, it would not affect artifacts uploaded to GCS and then should not affect Framework side.

**Comment by keyonghan** [comment]
To make it work, I have to manually remove the symlinks of `MacOS SDK` in three locations:
```
src/out/`build name`/gen/SDKs - host_debug_unopt & host_debug_unopt_arm64
src/out/`build name`/clang_x64/gen/SDKs - ios_debug_sim
src/out/`build name`/clang_arm64/gen/SDKs - ios_debug_sim_arm64_extension_safe
```

@zanderso Are these three locations enough? Is there any way to auto retrieve these three locations, I mean `clang_x64`/`clang_arm64`?

**Comment by zanderso** [comment]
I suspect those locations are enough. As for `clang_x64` and `clang_arm64`, there isn't any way to programmatically retrieve those locations from somewhere that I can think of off the top of my head, but those are the standard names for the output directory for targets that are cross-built during our GN build.

You might also walk the tree looking for paths that end in `.../gen/SDKs/`, and assume that the contents is the symlinks that need to be removed.

**Comment by keyonghan** [comment]
https://flutter-review.googlesource.com/c/recipes/+/53803 is a potential fix. But a better approach to move the MacOS SDK to a different location works. Closing.
