### ISSUE TITLE
PaginatedDataTable footer overflows screen

### ISSUE THREAD

**Issue by wetsanddan** [flutter/flutter#14097]
## Steps to Reproduce

Run the data_table_demo.dart file and the footer overflows the screen by 62 pixels.

https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/material/data_table_demo.dart

## Logs

Run your application with `flutter run` and attach all the log output.

I/flutter (27497): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (27497): The following message was thrown during layout:
I/flutter (27497): A RenderFlex overflowed by 62 pixels on the right.
I/flutter (27497): 
I/flutter (27497): The overflowing RenderFlex has an orientation of Axis.horizontal.
I/flutter (27497): The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and
I/flutter (27497): black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
I/flutter (27497): Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the
I/flutter (27497): RenderFlex to fit within the available space instead of being sized to their natural size.
I/flutter (27497): This is considered an error condition because it indicates that there is content that cannot be
I/flutter (27497): seen. If the content is legitimately bigger than the available space, consider clipping it with a
I/flutter (27497): ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex,
I/flutter (27497): like a ListView.
I/flutter (27497): The specific RenderFlex in question is:
I/flutter (27497):   RenderFlex#19ad8 OVERFLOWING
I/flutter (27497):   creator: Row ← ConstrainedBox ← Container ← IconTheme ← Builder ← DefaultTextStyle ← Column ←
I/flutter (27497):   DefaultTextStyle ← AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#557c6 ink renderer] ←
I/flutter (27497):   NotificationListener<LayoutChangedNotification> ← PhysicalModel ← ⋯
I/flutter (27497):   parentData: <none> (can use size)
I/flutter (27497):   constraints: BoxConstraints(w=312.0, h=56.0)
I/flutter (27497):   size: Size(312.0, 56.0)
I/flutter (27497):   direction: horizontal
I/flutter (27497):   mainAxisAlignment: end
I/flutter (27497):   mainAxisSize: max
I/flutter (27497):   crossAxisAlignment: center
I/flutter (27497):   textDirection: ltr
I/flutter (27497):   verticalDirection: down
I/flutter (27497): ◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
I/flutter (27497): ════════════════════════════════════════════════════════════════════════════════════════════════════
![capture2](https://user-images.githubusercontent.com/3400902/34912304-b8499c0e-f8a3-11e7-9f73-4f4630d7b6a0.PNG)

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor

C:\Users\Niihau\flutter\bin\flutter.bat --no-color doctor
[√] Flutter (on Microsoft Windows [Version 10.0.16299.192], locale en-US, channel alpha)
    • Flutter at C:\Users\Niihau\flutter
    • Framework revision 8f65fec5f5 (5 weeks ago), 2017-12-12 09:50:14 -0800
    • Engine revision edaecdc8b8
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.d8ae797298c3a6cf8dc9f4558707bd2672224d3e

[√] Android toolchain - develop for Android devices (Android SDK 27.0.2)
    • Android SDK at C:\Users\Niihau\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Connected devices
    • Samsung Galaxy S7, 7 1 0, API 25, 1440x2560 • 192.168.41.101:5555 • android-x86 • Android 7.1.1 (API 25)

Process finished with exit code 0f

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by Hixie** [comment]
Can you try switching to the master channel (or wait until next week when we release the next alpha) and let me know if it still happens? I think we fixed this recently.

**Comment by wetsanddan** [comment]
That did solve the issue. Thanks!
