### ISSUE TITLE
MissingPluginException(No implementation found for method init on channel plugins.flutter.io/google_sign_in)

### ISSUE THREAD

**Issue by vskr** [flutter/flutter#14096]
Using Flutter's google sign_in

But seeing the following message when I use this statement to sign in a user

_googleSignIn.signIn();

E/flutter ( 6491): MissingPluginException(No implementation found for method init on channel plugins.flutter.io/google_sign_in)

Any help would be appreciated.

**Comment by vskr** [comment]
Bump. 

Could it be because of the error in plugin (unlikely cos other would have noticed it too)

Or is it a user error on my part on how to use the plugin?

**Comment by mravn-google** [comment]
Duplicate of https://github.com/flutter/flutter/issues/14137

**Comment by pulstar** [comment]
Check if you are using any of these packages and remove them:

```
flutter_facebook_auth
flutter_twitter_login
github_sign_in
```

**Comment by pulstar** [comment]
Check if you are using any of these packages and remove it:

```
flutter_facebook_auth
flutter_twitter_login
github_sign_in
```
