### ISSUE TITLE
Import flutter module packed as AAR into another flutter app

### ISSUE THREAD

**Issue by amelmusic** [flutter/flutter#140931]
Hi all,
we have developed module called 'id_detektron_module' which is doing ID and passport scanning etc. Now when we pack this inside AAR file by using flutter build aar, and we import it in android native app by following https://docs.flutter.dev/add-to-app everything works perfectly.
However, our client is also using Flutter and we can't find a way to give them our AAR for them to import and show the UI. We have tried adding code inside their Flutter app to start id detection UI, but we are struggling.

Things we've tried inside their app:

1. In their MainActivity.kt we have tried setting route name known to our module
```
                val flutterIntent = FlutterActivity

                    .withNewEngine().initialRoute("/onboardingHomeScreen?licenseKey='TEST_KEY'")

                    .build(this.application.applicationContext)
                startActivity(flutterIntent)
```
but this just spins again their own app.

2. We have tried targeting directly our package with custom main method
 ```
               var engineGroup:FlutterEngineGroup = FlutterEngineGroup(this)
                FlutterEngineGroupCache.getInstance().put("my_cached_engine_group_id", engineGroup)

                var intent = FlutterActivity.withNewEngineInGroup("my_cached_engine_group_id")
                .dartEntrypoint("package:id_detektron_module/main_package.dart")
                .initialRoute("/onboardingHomeScreen?licenseKey='TEST_KEY'")
                .backgroundMode(FlutterActivityLaunchConfigs.BackgroundMode.transparent)
                .build(this);

                startActivity(intent)
```
in this case flutter complains that it can't find module. Obviously, it can't since it's packed inside AAR file. But we don't know how to invoke our dart packed in AAR.
This is how we've imported AAR file and it works when calling from android native project
releaseImplementation 'com.codecta.id_detektron_module:flutter_release:1.0' 

Do we need to somehow target MainActivity packed inside com.codecta.id_detektron_module:flutter_release?

Is this scenario supported?

Any help is greatly appreciated!

Thnx

**Comment by danagbemava-nc** [comment]
Hi @amelmusic, this scenario is currrently not supported. There's an existing issue tracking this in https://github.com/flutter/flutter/issues/64542

For now, you may try some of the suggestions in https://stackoverflow.com/questions/63242191/how-to-import-flutter-module-to-a-flutter-project

Closing from here as duplicate. 

Thank you
