### ISSUE TITLE
Error while adding animation to Snackbar (iOS simulator)

### ISSUE THREAD

**Issue by zarub2k** [flutter/flutter#14094]
OS: Mac OS
Device: iOS Simulator

## Steps to Reproduce

When I tried to show snackbar with some animation, I am getting the following error.

## Logs

══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 127 pos 15: 'vsync
!= null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
https://github.com/flutter/flutter/issues/new

When the exception was thrown, this was the stack:

Handler: onTap
Recognizer:
TapGestureRecognizer#c1a30(debugOwner: GestureDetector, state: possible, won arena, finalPosition:
════════════════════════════════════════════════════════════════════════════════════════════════════

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by cbracken** [comment]
Are you setting the required `vsync` property in the `AnimationController` constructor?

**Comment by Hixie** [comment]
What does the analyzer report?

**Comment by Hixie** [comment]
@zarub2k I'm going to close it since we haven't heard back from you. Please let us know if you are still running into this.
