### ISSUE TITLE
During interacting with flutter webview, sometime ui is suck in android 

### ISSUE THREAD

**Issue by Abhi3532** [flutter/flutter#140942]
### Steps to reproduce

1. i am running javascript code in flutter webview
2. based on that i am executing my functions
3. when i do it fast, it goes stuck

### Expected results

ui should not stuck in android and if stuck atleast show some error

### Actual results

ui stuck but but no error in logs

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Hi @Abhi3532 
Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the issue. Also, please provide the output of `flutter doctor -v` and `flutter run -v` as well. Thanks!
