### ISSUE TITLE
CheckBox and RadioButton don’t announce changed state

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#14092]
On Android.

**Comment by btastic** [comment]
I think you have to do it by yourself as far as I can read from this:

https://github.com/flutter/flutter/blob/09a6df7461e25984293226e77d8f87ba3aa8b88e/packages/flutter/lib/src/material/checkbox.dart#L63-L84

**Comment by goderbauer** [comment]
@btastic This bug is about screenreader's (like TalkBack on Android) not announcing when a focused checkbox switches from checked to unchecked. Sorry for the confusion.

**Comment by goderbauer** [comment]
TalkBack can be triggered to announce the change of state by sending a `TYPE_VIEW_CLICKED` event.

**Comment by goderbauer** [comment]
This works fine on iOS.
