### ISSUE TITLE
[process] Request examples please, none seem to show on pub.dev or the github repo

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/flutter#140924]
### Use case

If I'm stumbling upon process and would like to write some shell commands through official process it would be helpful, especially reading the result (ie system exit code  1 or 0 etc), or even how to run adb or xcrun simctl commands

### Proposal

Please add examples to https://pub.dev/packages/process
and explanation about mockability perhaps

**Comment by stuartmorgan** [comment]
Closing as a duplicate of https://github.com/flutter/flutter/issues/136217
