### ISSUE TITLE
Include observatory data server (but not UI) in release builds

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#141]
<a href="https://github.com/Hixie"><img src="https://avatars.githubusercontent.com/u/551196?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Tuesday Aug 25, 2015 at 03:09 GMT_
_Originally opened as https://github.com/flutter/engine/issues/794_

----

...so that, given the server elsewhere, you can observe any Sky app.

**Comment by Hixie** [comment]
See also https://github.com/flutter/flutter/issues/890.

**Comment by abarth** [comment]
Duplicated of #890
