### ISSUE TITLE
[Impeller] new blur's downsample step is unaligned

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#141046]
If you make the new blur just draw the downsample step it can be seen that it jiggles around as the sigma changes.  If you change the `CalculateScale` to only return values match `1/2^x`, the jiggling will still happen even though the scalar is remaining the same.

![align](https://github.com/flutter/flutter/assets/30870216/c283b347-01db-485a-8169-a13ad36760be)

```c++
Scalar GaussianBlurFilterContents::CalculateScale(Scalar sigma) {
  if (sigma <= 4) {
    return 1.0;
  }
  Scalar scalar = 4.0 / sigma;
  Scalar foo = log2f(1.f / scalar);
  Scalar bar = std::round(foo);
  Scalar result = 1.f / powf(2.f, bar);
  return result;
};
```

**Comment by gaaclarke** [comment]
Here is some observations:
1) Fixing the size of padding to some large value makes it not jiggle
1) Introducing a fudge translation for the snapshot transform cannot remove the alignment issues.  It seems to be related to the alignment when calculating the uvs for the downsample pass?

**Comment by gaaclarke** [comment]
I added fudge numbers inside of `CalculateUVs`, if there is a soft edge, adding fudge to that doesn't change the edge.

**Comment by jonahwilliams** [comment]
@gaaclarke is this something you are followin up on?

**Comment by gaaclarke** [comment]
> @gaaclarke is this something you are followin up on?

It's lower priority than mips on vulkan.  I'm not 100% certain if it is required for shipping since we did have some level of shimmer in the old blur.  We'll need to do some testing to decide.

I did dedicate a couple days to this, and it's a pain in the butt.  It will probably be obvious once we fix it though.

**Comment by gaaclarke** [comment]
I'm going to close this out.  Where we ended up, if this still exists, the jumps are hidden behind the blurriness of the blur.
