### ISSUE TITLE
[flutter_adaptive_scaffold] Exposing way to customize NavigationRailDestination

### ISSUE THREAD

**Issue by dikatok** [flutter/flutter#141060]
### Use case

Currently, `AdaptiveScaffold` takes only `List<NavigationDestination>` as `destinations` parameter, which is understandable, to make its type common. But, it results in us not being able to use other parameter exposed by `NavigationRailDestination` such as individual `indicatorColor`, `indicatorShape` and the most important one for me personally, `padding`.

### Proposal

Expose a mapper method parameter to allow us customize individual `NavigationRailDestination`.

```dart
    return AdaptiveScaffold(
      mapNavigationRailDestination: (int index, NavigationDestination dest) {
        return NavigationRailDestination(
          icon: dest.icon,
          label: Text(dest.label),
          padding: newSections.contains(index)
              ? const EdgeInsets.only(top: 12)
              : EdgeInsets.zero,
        );
      },
    );
```

**Comment by dikatok** [comment]
I can work on this if the proposed solution is approved.

**Comment by martijn00** [comment]
@gspencergoog this can be closed.
