### ISSUE TITLE
Add source location tracking to RemoteWidget

### ISSUE THREAD

**Issue by johnmccutchan** [flutter/flutter#141070]
Use case: Visual debugger.

See https://github.com/flutter/flutter/issues/90218#issuecomment-1879579898 for more context.

In a Visual Debugger I would like to be able to highlight the RFW text sections that map to a particular widget being displayed. This is similar to Chrome DevTool's 'Elements' feature. 

Ideally we can map from Widget to text section and from text section to Widget.

**Comment by Hixie** [comment]
Would we want this to work for the binary format also?
What kind of API would you want for this?

**Comment by johnmccutchan** [comment]
Re the binary format: If we went from rfwtext to binary, yes, that would be helpful. I think we would also need to embed the rfwtext in the binary as well.

I'm interesting in building a visual debugger tool for rfw, that is, I can type rfwtext into a box and see live updates and also map between the rfwtext and the widget tree:

![AfgoVJMPVDUXcig](https://github.com/flutter/flutter/assets/224266/f2d902e2-0826-43da-aceb-cf733769a6ef)

I'd also like to map between DynamicContent keys and the widget tree.

My concern is that complicated UIs will be hard to debug when using rfw as an intermediate representation and having a simple visual debugger would help.

**Comment by Hixie** [comment]
I'm having trouble understanding what the API should look like to be useful. Would you be able to provide some sample code that shows how you would write the visual debugger against a fictional ideal package:rfw API that does what you need?

**Comment by johnmccutchan** [comment]
Let me sketch in more detail here:

Let's assume I have something like the following (see my screenshot as well for more context)

The following code would run every time I `_rfwText` is changed (i.e. each keystroke). Essentially giving a live preview of whatever I've typed or pasted into my text box.

```
RemoteWidgetLibrary remoteLib = parseLibraryFile(_rfwText);
_remoteWidgetLibrary = remoteLib;
_runtime.update(mainName, _remoteWidgetLibrary!);
```

My tool is also displaying the `root` widget as follows:

```
RemoteWidget(
                  runtime: _runtime,
                  data: _data,
                  widget: const FullyQualifiedWidgetName(mainName, 'root'),
                  onEvent: (String name, DynamicMap arguments)
```

I would like an API that does something like the following:

```
// Encodes the location of some statement/section inside RFW text.
class SourceLocation {
  // Offset into RFW text.
  int offset;
  // Length from RFW text 
  int length;
}

SourceLocation findSourceLocationForWidget(Widget w);
```

Where `w` is required to be a child of `RemoteWidget`.

My debugger would determine the `Widget` (`w`) under my mouse cursor and then call `findSourceLocationForWidget` so that I can change my text display to, for example, underline/highlight the section of RFWText that created `w`.

I could also build a reverse map, where I look at where in the text box my cursor is and determine the `Widget` it is creating and then add a box around the widget.

**Comment by johnmccutchan** [comment]
I actually have a basic demo here: https://github.com/johnmccutchan/rfwpg

**Comment by Hixie** [comment]
Interesting. Let me think about how that might work.

**Comment by Hixie** [comment]
(note to self: we'd need to use a BuildContext/Element as the key, not a Widget.)

**Comment by johnmccutchan** [comment]
Similarly, I'd like to be able to identify sections of rfw text that are keys to something in DynamicContent and do a mapping between a display of the entire DynamicContent tree and the rfw text.

**Comment by Hixie** [comment]
Please take a look at https://github.com/flutter/packages/pull/5876 and let me know if it is sufficient for your needs. Thanks!
