### ISSUE TITLE
Request to Add ```color``` Property to Buttons Extending ```_ActionButton```

### ISSUE THREAD

**Issue by imp-sike** [flutter/flutter#141061]
### Use case

I would like to bring to your attention a minor inconsistency within the current API that I believe could be enhanced for a more seamless user experience.
While navigating through the codebase, I noticed that the `BackButton` is equipped with a convenient `color` property. However, this attribute seems to be missing in other buttons that extend the `_ActionButton` class  like ```DrawerButton```. 

### Proposal

Since `color` is the most used property in these buttons, this slight variation in the API can pose challenges for developers striving to maintain a cohesive design across different buttons.

**Comment by TahaTesser** [comment]
Hi! Feel free to file a PR for this fix with the test

**Comment by imp-sike** [comment]
I want to try contributing to this.
