### ISSUE TITLE
`RefreshIndicator` needs an audit and an overhaul to make it behave like the native indicator

### ISSUE THREAD

**Issue by lukehutch** [flutter/flutter#141034]
### Steps to reproduce

The Flutter `RefreshIndicator` does not behave like the native refresh indicator on Android (e.g. as seen in the Gmail app).

I am creating this issue as an umbrella issue to cover the different aspects of this. Really `RefreshIndicator` needs a careful audit and overhaul to bring it in line with the behavior of the native refresh indicator on Android (and also iOS, but I know nothing about that).

I gave detail on the context in this comment: https://github.com/flutter/flutter/pull/139535#issuecomment-1874650957

In summary:

The Android native refresh indicator changes color when it is armed, and can be dragged a further distance in armed state, which gives a clear indication that the indicator is armed. It also allows a user to drag back to above the arming point, to disarm the indicator again before releasing.

Flutter doesn't allow that -- there is no indication of armed state (#139018), and there is no ability to drag beyond the arming point. Also, in Flutter, after arming, the indicator can end up disarmed if the user moves up by even one pixel (https://github.com/flutter/flutter/issues/138848). It is very easy to trigger this, because there often is a "bounceback" effect on touchpoint-up, whereby a small upwards scroll is initiated by Flutter, even if the user didn't drag upwards (also described in #138848).

Even the visual appearance of the Flutter indicator doesn't properly match the native indicator.

I fixed the lack of overdrag in #139535. However, this is only a partial fix. More work needs to be done to make the Flutter indicator look and work like the native indicator. Hence this issue.

### Expected results

See above

### Actual results

See above

### Code sample

N/A

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
$ flutter doctor -v
[✓] Flutter (Channel beta, 3.18.0-0.2.pre, on Fedora Linux 39 (Workstation Edition) 6.5.12-300.fc39.x86_64, locale en_US.utf8)
    • Flutter version 3.18.0-0.2.pre on channel beta at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fed06b31d9 (3 weeks ago), 2023-12-13 14:53:33 -0800
    • Engine revision 39c6dc9bdd
    • Dart version 3.3.0 (build 3.3.0-174.3.beta)
    • DevTools version 2.30.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/luke/Android/Sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 17.0.4 (Fedora 17.0.4-1.fc39)
    • cmake version 3.27.7
    • ninja version 1.11.1
    • pkg-config version 1.9.5

[✓] Android Studio (version 2022.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 73.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.85.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.81.20231227

[✓] VS Code (version 1.86.0-insider)
    • VS Code at /usr/share/code-insiders
    • Flutter extension version 3.79.20231130

[✓] Connected device (3 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Linux (desktop)            • linux         • linux-x64      • Fedora Linux 39 (Workstation Edition) 6.5.12-300.fc39.x86_64
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 119.0.6045.159

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment]
Thanks for the detailed report @lukehutch, but I think your issue is very similar to an already open umbrella issue : https://github.com/flutter/flutter/issues/96528, so I'll close this in favor of it. You may share all your findings in it for better tracking.
If you disagree, write in comments and I'll reopen it.
