### ISSUE TITLE
[CP] Migrate command usage values (sent with each command)

### ISSUE THREAD

**Issue by eliasyishak** [flutter/flutter#141028]
### Issue Link

https://github.com/flutter/flutter/issues/141017

### Target

stable

### PR Link

https://github.com/flutter/flutter/pull/141019

### Changelog Description

Key features in GA3 are getting deprecated in March 2024 so we would like to CP updates to stable now for 3.16 to start sending events for each `FlutterCommand` we run. This includes the build command which will send run/build targets. Additionally, with this change, every other flutter command (`doctor`, `create`, etc.) will also send an event so this CP will allow us to get good estimations for MAU

### Impacted Users

All flutter users

### Impact Description

If we don't CP this in, we would have to wait for the stable release in February 2024 to start collecting analytics from users on the stable channel as the changes are currently in the beta channel.

### Workaround

No workaround.

### Risk

medium

### Test Coverage

yes

**Comment by zanderso** [comment]
CP lgtm in principle. I believe @christopherfujino is reviewing the CP PR.
