### ISSUE TITLE
StreamBuilder can't re-subscribe stream when it's built as TabBarView's children

### ISSUE THREAD

**Issue by js94766524** [flutter/flutter#141089]
### Steps to reproduce

1. build some StreamBuilder in TabBarView's children
2. when index of tab is 0 the StreamBuilder in children[0] works fine
3. when user changes tab to 1, the StreamBuilder in children[0] unscribed, and the one in children[1] subscribes it's stream. it looks fine up to now.
4. when user changes tab back to 0, the StreamBuild in children[1] unscribed, **BUT** the one in children[0] doesn't re-subscribe. 

### Expected results

the StreamBuilder in children[0] re-subscribe

### Actual results

the StreamBuilder in children[0] doesn't re-subscribe, and the UI looks no problem except it will not be refreshed when the data in stream changed

### Code sample

<details open><summary>Code sample</summary>

```dart
Widget build(context){
  return TabBarView(
    children: [
      StreamBuilder(),
      StreamBuilder(),
      StreamBuilder(),
    ],
  );
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.5, on Microsoft Windows [版本 10.0.22631.2861], locale zh-CN)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.2)
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.85.1)
[✓] Connected device (3 available)
[✓] Network resources
```

</details>

**Comment by js94766524** [comment]
I wrapped the StreamBuilder in a AutomaticKeepAliveClientMixin to prevent the StreamBuilder to dispose. 

this works, but I don't like it. 

It makes my code ugly :(

**Comment by js94766524** [comment]
> @js94766524 Does it occur using FutureBuilder as well ? Can you check below links and see if they help in your case ?
> 
> #27445 #27242

@darshankawar 

This is not the same as `FutureBuilder`. I need refresh UI when data in stream changed. 

The problem is that the `StreamBuilder` canceled the `StreamSubscription` when it is disappeared from screen because it seems to be disposed by the `TabBarView`, but never create a new `StreamBuilder` or  `StreamSubscription` when it is back to screen.

I guess when the `StreamBuilder` was disposed, the element in element's tree is not removed.

**Comment by darshankawar** [comment]
Thanks for the update @js94766524 
Can you take a look at below issues and check if they resemble or help in your case or not ?

https://github.com/flutter/flutter/issues/125849
https://github.com/flutter/flutter/issues/91814
https://github.com/flutter/flutter/issues/28117
