### ISSUE TITLE
Depreciated Members when customizing `RenderView` class to use `compositeFrame` function.

### ISSUE THREAD

**Issue by sososdk** [flutter/flutter#141009]
Related: https://github.com/flutter/flutter/issues/138892

### Use case

I need to customize `RenderView` and handle some things in `compositeFrame` method:

```dart

class CustomRenderView extends RenderView {
  CustomRenderView({
    ...
    required super.view,
  }) : _view = view;

  final ui.FlutterView _view;

  @override
  void compositeFrame() {
    ...
    try {
      ...
      if (automaticSystemUiAdjustment) {
        _updateSystemChrome();
        _doSomething();
      }
      ...
    } finally {
     ...
    }
  }

  void _updateSystemChrome() {
    // ...
  }

  void _doSomething() {
    // ...
  }
}
```

Before `Flutter 3.16.0`
I use `CustomRenderView` like this:

```dart
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  WidgetsBinding.instance
    ..renderView = CustomRenderView(
      configuration: WidgetsBinding.instance.createViewConfiguration(),
      view: PlatformDispatcher.instance.implicitView!,
    )
    ..renderView.prepareInitialFrame();
  
  ...
}
```

In `Flutter 3.16.0`
I use `CustomRenderView` like this:

```dart
void main() {
  final binding = WidgetsFlutterBinding.ensureInitialized();
  final flutterView = binding.platformDispatcher.implicitView!;
  // ignore: deprecated_member_use
  final pipelineOwner = binding.pipelineOwner;
  final renderView = CustomRenderView(view: flutterView);
  final root = View(
    view: flutterView,
    // ignore: deprecated_member_use
    deprecatedDoNotUseWillBeRemovedWithoutNoticePipelineOwner: pipelineOwner,
    // ignore: deprecated_member_use
    deprecatedDoNotUseWillBeRemovedWithoutNoticeRenderView: renderView,
    child: const MyApp(),
  );
  Timer.run(() => binding.attachRootWidget(root));
  binding.scheduleWarmUpFrame();
  
  ...
}
```

The `PipelineOwner` and `RenderView` parameters of the View class have been deprecated. How should I custom `RenderView` in the future?

### Proposal

The `View` class add `renderViewCreator` for creating custom `RenderView`:

```dart
View({
  super.key,
  required this.view,
  RenderView Function()? renderViewCreator,
  required this.child,
})
```

**Reply https://github.com/flutter/flutter/issues/138892#issuecomment-1832442838:**

I can't use custom `View` class, because `View.of()` is used in many widgets, if I use a custom `View`, `View.of()` will throws an exception.

**Comment by dam-ease** [comment]
Hi @sososdk. 
I see this is the same as the issue that was closed.

> If you want to use your own custom render object you'll also have to implement your own custom widget that manages that render object. Flutter doesn't support replacing RenderObjects of widgets and we don't plan to enable that.

Per this, is your question on how to create your own custom render object?

**Comment by sososdk** [comment]
Hi, @dam-ease 
I'm not trying to use a custom render object.  

I custom `RenderView` to use `RenderView.compositeFrame` function.

In Flutter 3.16.0 I can use it in the code below, but it is deprecated.
```dart
final renderView = CustomRenderView(view: flutterView);
  final root = View(
    view: flutterView,
    // ignore: deprecated_member_use
    deprecatedDoNotUseWillBeRemovedWithoutNoticePipelineOwner: pipelineOwner,
    // ignore: deprecated_member_use
    deprecatedDoNotUseWillBeRemovedWithoutNoticeRenderView: renderView,
    child: const MyApp(),
  );
```

I hope there will be a new method to replace it in a future version.

**Comment by goderbauer** [comment]
> I'm not trying to use a custom render object.

What is CustomRenderView in your example if it isn't a custom (= implemented by you) render object?
