### ISSUE TITLE
flutter test needs to support --preview-dart-2 option

### ISSUE THREAD

**Issue by mraleph** [flutter/flutter#14105]
I can't figure out how to run `flutter test` with common front-end:

```console
$ flutter test --preview-dart-2 --local-engine=host_debug -v
Could not find an option named "preview-dart-2".
```

**Comment by aam** [comment]
Took a quick look, not sure what `preview-dart-2` would do for `flutter test`. Doesn't `flutter test` run all flutter application tests via `pub`?

**Comment by mraleph** [comment]
To be honest, I am completely in the dark on how `flutter test` runs, but we certainly need to figure out a way to run the whole thing with CFE, otherwise we don't have enough coverage to make sure that nothing breaks when we flip the switch. If it's about plumbing options through `pub` first then I can file a bug on the dart-lang/sdk tracker too.

It seems Keerti plumbed things through in the internal setup, so we need to plumb things through in the external setup too somehow.

**Comment by aam** [comment]
Yeah, I'm not sure how `package:test` https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/test/runner.dart#L94 works with CFE. Do you know?

Also perhaps `flutter` itself (https://github.com/flutter/flutter/blob/master/bin/flutter#L140)  should be able to run in 2.0 as well?

**Comment by mraleph** [comment]
I think `package:test` is not yet compatible - requires dart-uri support in CFE. It does use isolates though so I think as long as we pass correct arguments to the outer invocation of test suite it should propagate downwards.

**Comment by mit-mit** [comment]
@aam this is urgent and important -- we need test support to confirm CFE is working. Can you sync with SEA on a plan for the missing pieces to support this?

**Comment by aam** [comment]
I believe once (whole) `flutter` tools(https://github.com/flutter/flutter/blob/master/bin/flutter#L140) runs on CFE, `flutter test` will run on CFE as well. Immediate prerequisites for that are `kernel-service.dart.snapshot`, outline/platform `.dill`s for `dart2` that are not packaged into dart sdk used by `flutter` tools (cached in flutter/bin/cache/dart-sdk).

> UPD. Actually data URI support has landed so package:test should become usable.

Who uses and needs data URI support? From what I can see https://github.com/dart-lang/test/blob/master/lib/src/runner/vm/platform.dart#L79 package:test uses spawnUri to load tests.

**Comment by mraleph** [comment]
@aam I think this code here https://github.com/dart-lang/test/blob/master/lib/src/runner/vm/platform.dart#L55-L72 is actually implemented on top of data URIs. The code at line 79 that you reference is only used when you are testing against `pubServeUrl`, which I don't think is the mode that is used for non-web tests.

**Comment by aam** [comment]
You can run `flutter test --preview-dart-2` as of https://github.com/flutter/flutter/commit/f88c60b38c3a5ef92115d24e3da4175b4890daba.

There is remaining work to run the tests in strong mode too that is pending on another dart roll where issue with support of conflicting interfaces is resolved.

**Comment by mraleph** [comment]
Thanks, @aam! \o/
