### ISSUE TITLE
Error in flutter image

### ISSUE THREAD

**Issue by marycanonce** [flutter/flutter#141073]
![a](https://github.com/flutter/flutter/assets/131778112/2a743da3-da63-4c27-9bc3-b569466839b3)
Can I ask anyone how to solve this?

**Comment by dnlmgwi** [comment]
I think this could be an issue with your [pubspec.yaml](https://dart.dev/tools/pub/pubspec).

Eg. Indentation, or the directory called "yours" hasn't been created inside assets directory.

Does your pubspec.yaml look like this?

```
flutter:
  assets:
    - yours/
```

To match this:

```
Flutter_App
    └─── assets/
        |   ⚬ logo.png
        └─── yours/
                ⚬ e.jpg
```

**Comment by yuchengxie** [comment]
meet the same question

**Comment by darshankawar** [comment]
@marycanonce 
Your question / issue is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here, as this looks more of a config issue rather than a bug.
