### ISSUE TITLE
Tabbar - labelPadding notwork with indicator

### ISSUE THREAD

**Issue by bxTruong** [flutter/flutter#141092]
### Steps to reproduce

When I update flutter version 3.16.5, when Tabbar has indicator and labelPadding, labelPadding does not work.
I tested Flutter on the old version 3.13.2 and it still works normally

```
TabBar(
      indicator: BoxDecoration(color: Colors.amber, borderRadius: BorderRadius.circular(100)),
      controller: TabController(length: 2, vsync: this),
      isScrollable: true,
      dividerColor: Colors.transparent,
      tabAlignment: TabAlignment.start,
      tabs: const [
        Tab(text: 'Member'),
        Tab(text: 'Customer'),
      ],
      labelPadding: const EdgeInsets.symmetric(horizontal: 16),
    )
```

### Expected results

I need to inform about this issue, is it because Flutter removed such mechanism or is it due to a bug in this version of Flutter

### Actual results

When I update flutter version 3.16.5, when Tabbar has indicator and labelPadding, labelPadding does not work.
I tested Flutter on the old version 3.13.2 and it still works normally

### Code sample

<details open><summary>Code sample</summary>

```dart
TabBar(
      indicator: BoxDecoration(color: Colors.amber, borderRadius: BorderRadius.circular(100)),
      controller: TabController(length: 2, vsync: this),
      isScrollable: true,
      dividerColor: Colors.transparent,
      tabAlignment: TabAlignment.start,
      tabs: const [
        Tab(text: 'Member'),
        Tab(text: 'Customer'),
      ],
      labelPadding: const EdgeInsets.symmetric(horizontal: 16),
    )```

</details>

**Comment by huycozy** [comment]
Hi @bxTruong 
Could you please share the demo on Flutter 3.13.2? I checked this on 3.10.6 and 3.13.9 but it outputs the same result to 3.16.5 as below demo:

https://github.com/flutter/flutter/assets/104349824/521aafe7-5f4d-40d5-b7de-f5e363845904

If it's a bug since 3.13.2, I will try doing `bisect` to find the commit causing this.
