### ISSUE TITLE
[local_auth]how to detect the changes of user's bio info

### ISSUE THREAD

**Issue by justsonghua** [flutter/flutter#141099]
i try to do a func that when user change the bio info like face id or fingerprint, then when i call LocalAuthentication().authenticate(),  i can get a flag or token so i can notify my users that the bio info had change, this time need to use passcode to do the verfy. But currently LocalAuthentication().authenticate() only return a bool, i wonder is this only can do by Object-C or Kotlin, thank you

**Comment by stuartmorgan** [comment]
Duplicate of https://github.com/flutter/flutter/issues/88848
