### ISSUE TITLE
No podspec found for `video_player_avfoundation` in `.symlinks/plugins/video_player_avfoundation/ios`

### ISSUE THREAD

**Issue by austinn** [flutter/flutter#141067]
### What package does this bug report belong to?

video_player

### What target platforms are you seeing this bug on?

iOS

### Have you already upgraded your packages?

Yes

### Dependency versions

[pubspec.lock.txt](https://github.com/flutter/flutter/files/13851484/pubspec.lock.txt)

### Steps to reproduce

1. Add `video_player` to `pubspec.yaml`
2. `flutter pub get`
3. `flutter run`

### Expected results

Dependencies install and the app runs

### Actual results

`pod install` produces an error: (see Logs)

### Code sample

<details open><summary>Code sample</summary>
The app won't even run, so any code sample isn't relevant
</details>

### Screenshots or Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
> ios % pod install
Analyzing dependencies
Pre-downloading: `FirebaseFirestore` from `https://github.com/invertase/firestore-ios-sdk-frameworks.git`, tag `10.16.0`
cloud_firestore: Using Firebase SDK version '10.16.0' defined in 'firebase_core'
cloud_functions: Using Firebase SDK version '10.16.0' defined in 'firebase_core'
firebase_analytics: Using Firebase SDK version '10.16.0' defined in 'firebase_core'
firebase_app_check: Using Firebase SDK version '10.16.0' defined in 'firebase_core'
firebase_auth: Using Firebase SDK version '10.16.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '10.16.0' defined in 'firebase_core'
Run script to upload symbols already exists.
firebase_crashlytics: Using Firebase SDK version '10.16.0' defined in 'firebase_core'
firebase_dynamic_links: Using Firebase SDK version '10.16.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '10.16.0' defined in 'firebase_core'
firebase_performance: Using Firebase SDK version '10.16.0' defined in 'firebase_core'
firebase_remote_config: Using Firebase SDK version '10.16.0' defined in 'firebase_core'
firebase_storage: Using Firebase SDK version '10.16.0' defined in 'firebase_core'
[!] No podspec found for `video_player_avfoundation` in `.symlinks/plugins/video_player_avfoundation/ios`
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.2.1 23C71 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[!] Android Studio (version unknown)
    ✗ Unable to determine Android Studio version.
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.85.1)
[✓] Connected device (3 available)
    ! Error: Browsing on the local area network for XXX's iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as
      this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by austinn** [comment]
The error seemed to get introduced in `2.8.0`
`pod install` works when I pin the following versions:

```
  video_player: 2.7.2
  video_player_web: 2.1.1
```

**Comment by stuartmorgan** [comment]
> ### Steps to reproduce
> 1. Add `video_player` to `pubspec.yaml`
> 2. `flutter pub get`
> 3. `flutter run`

Is this actually what you did (in a project that was not previously using `video_player`) to reproduce this? I can imagine how this might happen if you were updating an existing project, but not if you were adding it for the first time.

Do you have an `ios/Podfile.lock` file? If so, does deleting fix the problem?

**Comment by austinn** [comment]
> > ### Steps to reproduce
> > 
> > 1. Add `video_player` to `pubspec.yaml`
> > 2. `flutter pub get`
> > 3. `flutter run`
> 
> Is this actually what you did (in a project that was not previously using `video_player`) to reproduce this? I can imagine how this might happen if you were updating an existing project, but not if you were adding it for the first time.
> 
> Do you have an `ios/Podfile.lock` file? If so, does deleting fix the problem?

It was in an existing project. Sorry, that was misleading. I had upgraded `video_player: 2.7.2` to `2.8.0`. 
I did try removing `video_player` completely (flutter clean, delete Pods and Podfile.lock) and reinstalling it, but same issue.

I will try to add it to a new project and see if the issue persists

**Comment by stuartmorgan** [comment]
It sounds like something is caching the old podspec location. Could you provide your `Podfile.lock`?

**Comment by austinn** [comment]
I think I found the root cause of the issue. (Sorry, not an iOS developer)
Someone in the project added the following in the Podfile a long time ago

```
def flutter_install_plugin_pods(application_path = nil, relative_symlink_dir, platform)
  # defined_in_file is set by CocoaPods and is a Pathname to the Podfile.
  application_path ||= File.dirname(defined_in_file.realpath) if self.respond_to?(:defined_in_file)
  raise 'Could not find application path' unless application_path

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.

  symlink_dir = File.expand_path(relative_symlink_dir, application_path)
  system('rm', '-rf', symlink_dir) # Avoid the complication of dependencies like FileUtils.

  symlink_plugins_dir = File.expand_path('plugins', symlink_dir)
  system('mkdir', '-p', symlink_plugins_dir)

    plugins_file = File.join(application_path, '..', '.flutter-plugins-dependencies')
    plugin_pods = flutter_parse_plugins_file(plugins_file, platform)
    plugin_pods.each do |plugin_hash|
      plugin_name = plugin_hash['name']
      plugin_path = plugin_hash['path']
      if (plugin_name && plugin_path)
        symlink = File.join(symlink_plugins_dir, plugin_name)
        File.symlink(plugin_path, symlink)

        if plugin_name == 'ffmpeg_kit_flutter'
          pod 'ffmpeg_kit_flutter/min-gpl', :path => File.join(relative_symlink_dir, 'plugins', plugin_name, platform)
        else
          pod plugin_name, :path => File.join(relative_symlink_dir, 'plugins', plugin_name, platform)
        end
      end
    end
  end
```

Sorry for the invalid issue

**Comment by stuartmorgan** [comment]
>           pod plugin_name, :path => File.join(relative_symlink_dir, 'plugins', plugin_name, platform)

Yes, this logic is no longer valid; custom pod logic will need updating to handle plugins that use `sharedDarwinSource`.
