### ISSUE TITLE
version solving fails for flutter_tool

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#141032]
From running the flutter tool locally at tip of tree:

```
Resolving dependencies... (1.8s)
Because flutter_tools depends on web_socket_channel 2.4.2 which doesn't match
  any versions, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on web_socket_channel: dart pub add web_socket_channel:^2.4.1
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
```

Looks like web_socket_channel was bumped to 2.4.2 in https://github.com/flutter/flutter/pull/140979, but that version does not exist (anymore?) on pub: https://pub.dev/packages/web_socket_channel

**Comment by goderbauer** [comment]
cc @christopherfujino

**Comment by goderbauer** [comment]
Looks like this is also the reason for the tree redness: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8759717247430832049/+/u/flutter_config_--clear-features/stdout

**Comment by goderbauer** [comment]
https://pub.dev/packages/web_socket_channel/versions says at the very bottom that v2.4.2 was retracted.

**Comment by goderbauer** [comment]
Some context about the retracted version is at https://github.com/dart-lang/web_socket_channel/issues/318#issuecomment-1879089387.

**Comment by goderbauer** [comment]
This also broke the packages tree: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8759714323922531057/+/u/flutter_config_--clear-features/stdout (cc @stuartmorgan)

**Comment by piedcipher** [comment]
faced this while doing `flutter channel master`. 

tried a hack by going to flutter directory and doing `git checkout master && git pull origin master`. when opened the SDK in vscode it auto-downloaded the upgrade.

**Comment by christopherfujino** [comment]
This was resolved in https://github.com/flutter/flutter/pull/141040
