### ISSUE TITLE
On macOS 13.6.3 (22G436), flutter(Flutter 3.16.5 • channel stable) cannot recognize the versions of Android Studio and VScode software.

### ISSUE THREAD

**Issue by PeOS-China** [flutter/flutter#141072]
### Steps to reproduce

1. run flutter doctor -v
2. The information output by the console shows that the versions of Android Studio and VS Code cannot be recognized.
3. The following is the version number information of each software：

-      OS version macOS 13.6.3 (22G436), darwin-x64, locale zh-Hans-CN

-      Flutter version 3.16.5 on channel stable

-      Dart version 3.2.3

-     DevTools version 2.28.4

-     Android Studio :

        Android Studio Jellyfish | 2023.3.1 Canary 3
         Build #AI-233.13135.103.2331.11273936, built on January 4, 2024
         Runtime version: 17.0.9+0-17.0.9b1087.9-11255266 x86_64
         VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
        macOS 13.6.3
        GC: G1 Young Generation, G1 Old Generation
        Memory: 1024M
       Cores: 4
       Non-Bundled Plugins:
               com.intellij.marketplace (233.13135.108)
                Dart (233.13135.65)
                io.flutter (77.0.1)

-       VS Code:

            Version: 1.85.1
            Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
            Date: 2023-12-13T09:48:06.308Z
            Electron: 25.9.7
            ElectronBuildId: 25551756
            Chromium: 114.0.5735.289
             Node.js: 18.15.0
             V8: 11.4.183.29-electron.0
             OS: Darwin x64 22.6.0

### Expected results

On macOS 13.6.3 (22G436), flutter can recognize the versions of Android Studio and VScode software.

### Actual results

On macOS 13.6.3 (22G436), flutter cannot recognize the versions of Android Studio and VScode software.

### Code sample

<details open><summary>Code sample</summary>

```dart
flutter -v
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor -v
[✓] Flutter (Channel stable, 3.16.5, on macOS 13.6.3 22G436 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.16.5 on channel stable at /Users/peos/Downloads/code/flutter/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (3 weeks ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/peos/Library/Android/sdk
    • Platform android-34-ext8, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio Preview.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.9-11255266)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version unknown)
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.9-11255266)

[✓] VS Code (version unknown)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0
    ✗ Unable to determine VS Code version.

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.6.3 22G436 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.199

dart --version
Dart SDK version: 3.2.3 (stable) (Tue Dec 5 17:58:33 2023 +0000) on "macos_x64"

flutter --version
Flutter 3.16.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 78666c8dc5 (3 weeks ago) • 2023-12-19 16:14:14 -0800
Engine • revision 3f3e560236
Tools • Dart 3.2.3 • DevTools 2.28.4


```

</details>

**Comment by darshankawar** [comment]
@PeOS-China 
Can you try on the latest master channel and see if you get same behavior ?
See https://github.com/flutter/flutter/issues/139027 for reference.

**Comment by darshankawar** [comment]
@PeOS-China 
Please try to post the logs in collapsed mode.
Check https://github.com/flutter/flutter/issues/121925 to see if it helps in your case or not.

**Comment by PeOS-China** [comment]
> @PeOS-China Please try to post the logs in collapsed mode. Check #121925 to see if it helps in your case or not.

I uninstalled Android Studio Preview and installed non-Preview. it worked

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
