### ISSUE TITLE
Finished with error: Package(s)  require the native assets feature. This feature has not yet been implemented for `TargetPlatform.android_arm64`

### ISSUE THREAD

**Issue by SheepYang1993** [flutter/flutter#141003]
### Steps to reproduce

My Flutter Version 3.16.5

### Expected results

Expected successful run

### Actual results

Finished with error: Package(s)  require the native assets feature. This feature has not yet been implemented for `TargetPlatform.android_arm64`

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @SheepYang1993, can you provide a minimal reproducible code sample so we can investigate this? Native assets is currently experimental on the master channel so if you're running a project that uses it on stable, that would be why you're getting this issue
