### ISSUE TITLE
Document that text field owners must keep track of their controllers

### ISSUE THREAD

**Issue by Arno-Z** [flutter/flutter#14104]
## Steps to Reproduce

When a Material field is scrolled off screen, and loses focus the field will be reset to it's initialValue. See this [screen movie](https://youtu.be/GQKxOIO-IeY) for a demo:

## Logs
```
Analyzing /Users/arno/AndroidStudioProjects/qlouder_expenses...
No issues found!
Ran in 5.6s
```

## Flutter Doctor
```
[✓] Flutter (on Mac OS X 10.13.2 17C205, locale en-NL, channel alpha)
    • Flutter at /Users/arno/flutter
    • Framework revision 8f65fec5f5 (5 weeks ago), 2017-12-12 09:50:14 -0800
    • Engine revision edaecdc8b8
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.d8ae797298c3a6cf8dc9f4558707bd2672224d3e

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at /Users/arno/Library/Android/sdk
    • Android NDK at /Users/arno/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0.beta.2

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
```

**Comment by fractalemagic** [comment]
The solution here should be to use a `KeepAlive` widget to tell the list view to persist the state of your text field. In addition, by default, `ListView`s will automatically wrap your widgets in an `AutomaticKeepAlive` so all you need to do is use `AutomaticKeepAliveClientMixin` to tell the list view that you want to keep the widget's state alive.

**Comment by Arno-Z** [comment]
But KeepAlive is for use in SliverMultiBoxAdaptorWidgets, such as SliverGrid or SliverList. How to do it with a normal scaffold:

  ```
  return new Scaffold(
      resizeToAvoidBottomPadding: false,
      appBar: new AppBar(
          title: const Text('Expense'),
          actions: <Widget>[
            _isNew == false?new IconButton(
              icon: new Icon(Icons.delete),
              tooltip: 'Delete this expense',
              onPressed: () {_onDeleteTap();},
            ):new Column(),
          ]
      ),
      body: **new KeepAlive**(
          keepAlive: true,
          child: _form,
      ),
```

**Comment by eikebartels** [comment]
I had the same issue. It turns out that the default value `true` for `addAutomaticKeepAlives` for the `ListView` has no effect. After setting it manually (see below) it works fine. A possible bug @fractalemagic ?

```
child: new ListView(children: <Widget>[
                    _buildName(context),
                    _buildAddress(context),
                    _buildContact(context),
                    new Container(
                        padding: const EdgeInsets.all(16.0),
                        child: new RaisedButton(
                            child: const Text("Weiter"),
                            onPressed: _handleSubmitted
                        )
                    )
                  ], addAutomaticKeepAlives: true)
```

**Comment by Hixie** [comment]
In a normal Scaffold everything is always kept alive. Only scroll views (anything with a Viewport, really) will ever randomly throw away an instantiated widget.

**Comment by HansMuller** [comment]
I believe that https://github.com/flutter/flutter/pull/15484 will correct the problem reported here, assuming that the app manages the TextEditingControllers itself. There's an example of going that in #1584's description.

**Comment by zoechi** [comment]
dup of #11500 ?

**Comment by markusaksli-nc** [comment]
This is documented in [TextFormField](https://api.flutter.dev/flutter/material/TextFormField-class.html). Leaving open as it is still not documented in [TextField](https://api.flutter.dev/flutter/material/TextField-class.html).
