### ISSUE TITLE
Can we use a unique name, or project name, when generating iOS project?

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1411]
It looks like `flutter ios --init` always uses the name `Flutter`. This means, if I'm trying to load two different apps onto a phone, they seem to collide with the same name.

Since we have a project name, could we use that by default?

Thanks!

**Comment by sethladd** [comment]
cc @chinmaygarde

**Comment by eseidelGoogle** [comment]
See also https://github.com/flutter/flutter/issues/1340

**Comment by chinmaygarde** [comment]
For a first pass, I am wiring in the application name, an identifier, splash screen and launch icons

**Comment by sethladd** [comment]
Thanks!

Closing as dupe of https://github.com/flutter/flutter/issues/1340
