### ISSUE TITLE
Mistranslation in flutter-codelab-first ja#5

### ISSUE THREAD

**Issue by nori26** [flutter/flutter#141106]
https://codelabs.developers.google.com/codelabs/flutter-codelab-first?hl=ja#5

Original Text:
`favorites に MyAppState という新規のプロパティを追加しました。`
Means:
`You added a new property to favorites called MyAppState.`

Proposed Correction:
`MyAppState に favorites という新規のプロパティを追加しました。`

**Comment by darshankawar** [comment]
> Proposed Correction:
> `MyAppState に favorites という新規のプロパティを追加しました。`

Translation : `Added a new property to MyAppState called favorites.`

/cc @domesticmouse

**Comment by domesticmouse** [comment]
The codelabs are, as far as I am aware, only translated once a year by the I/O team. I have no visibility into the process
