### ISSUE TITLE
Icons.add disappears in Android

### ISSUE THREAD

**Issue by carlosbdw** [flutter/flutter#14111]
## Steps to Reproduce

Create a new flutter project with IntelliJ

run in iOS iPhoneX simulator  ✅
run in Android Samsung S8 simulator ❌

![2018-01-16 11 27 42](https://user-images.githubusercontent.com/21432033/34970672-afa89df2-fab0-11e7-82ae-297d500c4ab7.png)

## Flutter Doctor
Running flutter doctor...
[✓] Flutter (on Mac OS X 10.13.2 17C88, locale zh-Hans-CN, channel master)
    • Flutter at /Users/car/Documents/GitHub/flutter
    • Framework revision 299ddb4320 (7 hours ago), 2018-01-15 12:43:43 -0800
    • Engine revision 05fe72d068
    • Tools Dart version 2.0.0-dev.16.0
    • Engine Dart version 2.0.0-edge.28757928b47b192efcec082c78258102beb03f78

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.2)
    • Android SDK at /Users/car/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.2
    • ANDROID_HOME = /Users/car/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.2.6)
    • Flutter plugin version 20.0.2
    • Dart plugin version 172.4343.25

**Comment by raju-bitter** [comment]
You are on the master branch, I don't see this behavior with the alpha branch. Not sure if you are reporting this bug for the master branch, or if you accidentally checkout out the wrong branch.
https://flutter.io/setup-macos/#clone-the-repo
When testing with the master branch on a device (Galaxy Note 5, Android 7.0), everything is working as expected.

**Comment by Hixie** [comment]
@carlosbdw Do you still see this? There was a brief period where we had this bug, but I think we fixed it.

**Comment by zoechi** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
