### ISSUE TITLE
[in_app_purchase] Promoted app store purchase not working 

### ISSUE THREAD

**Issue by rajhimanshu83** [flutter/flutter#141162]
### Steps to reproduce

    Implemented these methods in main.dart
    
```
    SKPaymentQueueWrapper().setTransactionObserver(IosTransactionObserver());
    await SKPaymentQueueWrapper().startObservingTransactionQueue();
```
    
```
class IosTransactionObserver implements SKTransactionObserverWrapper {

  @override
  void paymentQueueRestoreCompletedTransactionsFinished() {
    print("paymentQueueRestoreCompletedTransactionsFinished");
  }

  @override
  void restoreCompletedTransactionsFailed({required SKError error}) {
    print("restoreCompletedTransactionsFailed");
  }

  @override
  bool shouldAddStorePayment({required SKPaymentWrapper payment, required SKProductWrapper product}) {
    print("shouldAddStorePayment");
    return true;
  }

  @override
  void removedTransactions({required List<SKPaymentTransactionWrapper> transactions}) {
    print("removedTransactions:himanshu");

  }

  @override
  void updatedTransactions({required List<SKPaymentTransactionWrapper> transactions}) async {
    print("iap: received (${transactions.length}) updated transactions");
  }
}
```
    

### Expected results

When we try to test the promoted purchases using itms-services protocol, methods in IosTransactionObserver should be called.

### Actual results

IosTransactionObserver is not working when app is killed. It's working when app is in background.

**Comment by dam-ease** [comment]
Thanks for filing this @rajhimanshu83.
Please can you provide the version of the `in_app_purchase` package you are making use of, the output of your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code or a simple repo that could be used to reproduce this?

**Comment by rajhimanshu83** [comment]
`  in_app_purchase: ^3.1.11
`

**flutter doctor -v**

`[✓] Flutter (Channel stable, 3.7.0, on macOS 14.2.1 23C71 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0 on channel stable at /Users/himanshuraj/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (12 months ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/himanshuraj/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Community Edition (version 2023.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.85.0)
    • VS Code at /Users/himanshuraj/Downloads/Visual Studio Code 2.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (3 available)
    • Himanshu's iPhone (mobile) • 00008101-000961A00144001E • ios            • iOS 17.2.1 21C66
    • macOS (desktop)            • macos                     • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)               • chrome                    • web-javascript • Google Chrome 120.0.6099.199

[✓] HTTP Host Availability
    • All required HTTP hosts are available
`


**Code to reproduce**

```

import 'package:in_app_purchase_storekit/in_app_purchase_storekit.dart';
import 'package:in_app_purchase_storekit/store_kit_wrappers.dart';

main() {
    InAppPurchaseStoreKitPlatform.registerPlatform();
    SKPaymentQueueWrapper().setTransactionObserver(IosTransactionObserver());
    await SKPaymentQueueWrapper().startObservingTransactionQueue();
}

class IosTransactionObserver implements SKTransactionObserverWrapper {

  @override
  void paymentQueueRestoreCompletedTransactionsFinished() {
    print("paymentQueueRestoreCompletedTransactionsFinished");
  }

  @override
  void restoreCompletedTransactionsFailed({required SKError error}) {
    print("restoreCompletedTransactionsFailed");
  }

  @override
  bool shouldAddStorePayment({required SKPaymentWrapper payment, required SKProductWrapper product}) {
    print("shouldAddStorePayment");
    return true;
  }

  @override
  void removedTransactions({required List<SKPaymentTransactionWrapper> transactions}) {
    print("removedTransactions");

  }

  @override
  void updatedTransactions({required List<SKPaymentTransactionWrapper> transactions}) async {
    print("iap: received (${transactions.length}) updated transactions");
  }
}
```

**Using itms-services protocol to initiate payment** [HERE](https://developer.apple.com/documentation/storekit/in-app_purchase/testing_promoted_in-app_purchases)

`itms-services//?action=purchaseIntent&bundleId=com.packageName.app&productIdentifier=product_name
`

**Comment by dam-ease** [comment]
Thanks for your response @rajhimanshu83.
I see you are on an older version of Flutter and the package as well, can you please help confirm this issue also persists on the latest versions?

**Comment by rajhimanshu83** [comment]
Yes, the same issue is there in the latest versions.

**Comment by dam-ease** [comment]
I'm unable to run this with only the code snippet shared. Are there any logs or screen records you could share regarding this?
