### ISSUE TITLE
PageView uses global controller, that is never disposed.

### ISSUE THREAD

**Issue by polina-c** [flutter/flutter#141119]
```dart
// Having this global (mutable) page controller is a bit of a hack. We need it
// to plumb in the factory for _PagePosition, but it will end up accumulating
// a large list of scroll positions. As long as you don't try to actually
// control the scroll positions, everything should be fine.
final PageController _defaultPageController = PageController();
```

This code is very old (7 years): https://github.com/flutter/flutter/pull/7948. Unfortunately the PR that introduced it doesn't include any additional rationale.

**Comment by polina-c** [comment]
I see what is the problem: the controller should be readable in widget.

**Comment by Levi-Lesches** [comment]
Ah I was in the middle of filing an issue for this!

Another approach (if making it nullable is not possible), would be to create a new `PageViewController()` in the constructor (_not_ as a default argument, which would be `const`, but in the initializer list of each constructor), and set a flag in the widget to let it know it should dispose of its controller automatically. Something like: 

```dart
  PageView({
    super.key,
    this.scrollDirection = Axis.horizontal,
    this.reverse = false,
    PageController? controller,
    this.physics,
    this.pageSnapping = true,
    this.onPageChanged,
    List<Widget> children = const <Widget>[],
    this.dragStartBehavior = DragStartBehavior.start,
    this.allowImplicitScrolling = false,
    this.restorationId,
    this.clipBehavior = Clip.hardEdge,
    this.scrollBehavior,
    this.padEnds = true,
  }) : _shouldDisposeController = controller == null,
       controller = controller ?? PageViewController(),
       childrenDelegate = SliverChildListDelegate(children);
```

**Comment by polina-c** [comment]
@Levi-Lesches , thanks for the suggestion!

A widget's life is much shorter than it's state and controller's life. It makes it difficult for the widget to dispose its own controller.

**Comment by polina-c** [comment]
The fix is on the way: https://github.com/flutter/flutter/pull/141138

**Comment by polina-c** [comment]
The fix was reverted: https://github.com/flutter/flutter/pull/141479
