### ISSUE TITLE
mac Phase3 upgrades - flutter devicelab staging pool

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#141124]
### Type of Request

infra task

### Infrastructure Environment

devicelab

### What is happening?

Please upgrade the following machines to macOS 13.6.1 (Upgrade all to macOS 13 except 1 arm64 msm8952 devicelab bot):

[flutter-devicelab-mac-5](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-5)
[flutter-devicelab-mac-18](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-18)
[flutter-devicelab-mac-26](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-26)
[flutter-devicelab-mac-40](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-40)

NOTE: we **NOT** upgrading [flutter-devicelab-mac-37](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-37) as per https://github.com/flutter/flutter/issues/134737

**Comment by vashworth** [comment]
@yusuf-goog This list should also include x86 iOS bots from prod pool

**Comment by yusuf-goog** [comment]
Yes, I'll be opening individual tickets to track.

**Comment by vashworth** [comment]
Also, please ensure the following after each upgrade:

Delete any directories within /opt/flutter/xcode if applicable.

Also verify /opt/flutter/xcode is owned by swarming user.

Run DevToolsSecurity - should get response "Developer mode is already enabled."
If you don't get the message, run sudo /usr/sbin/DevToolsSecurity -enable to enable.

**Comment by kentnguyen99** [comment]
Upgrading MacOS to version 13.6.1 on following machines below have been completed and ready for service.
flutter-devicelab-mac-5
flutter-devicelab-mac-18
flutter-devicelab-mac-26
flutter-devicelab-mac-40

**Comment by kentnguyen99** [comment]
All works have been completed and ticket is closed.
