### ISSUE TITLE
error = 121, address = storage.googleapis.com

### ISSUE THREAD

**Issue by HappyJie135588** [flutter/flutter#14110]
C:\Users\HJ>flutter doctor
Updating flutter tool...
Got socket error trying to find package coverage at https://pub.dartlang.org.
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...

等等待待 0 秒秒，，按按 CTRL+C 退退出出 ...
OS Error: ä¿¡å·ç¯è¶…æ—¶æ—¶é—´å·²åˆ°
, errno = 121, address = storage.googleapis.com, port = 49686
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...

等等待待 0 秒秒，，按按 CTRL+C 退退出出 ...
OS Error: ä¿¡å·ç¯è¶…æ—¶æ—¶é—´å·²åˆ°
, errno = 121, address = storage.googleapis.com, port = 49816
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...

等等待待 0 秒秒，，按按 CTRL+C 退退出出 ...
OS Error: ä¿¡å·ç¯è¶…æ—¶æ—¶é—´å·²åˆ°
, errno = 121, address = storage.googleapis.com, port = 50258
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...

等等待待 0 秒秒，，按按 CTRL+C 退退出出 ...
OS Error: ä¿¡å·ç¯è¶…æ—¶æ—¶é—´å·²åˆ°
, errno = 121, address = storage.googleapis.com, port = 50407
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...

等等待待 0 秒秒，，按按 CTRL+C 退退出出 ...

**Comment by InMatrix** [comment]
It looks like you're in China. Please try these instructions before running `flutter doctor`: https://github.com/flutter/flutter/wiki/Using-Flutter-in-China

Let us know if it works for you.

**Comment by HappyJie135588** [comment]
已解决、谢谢、在windows操作系统上需要手动配置国内镜像环境变量、注意中英文标点符号

**Comment by xster** [comment]
Closing this bug if it's resolved for you. Please re-open if you're still experiencing issues.
