### ISSUE TITLE
The "--no-shrink" FLAG with flutter build apk does't work as the document said.

### ISSUE THREAD

**Issue by yanshouwang** [flutter/flutter#141164]
### Use case

[The official document](https://docs.flutter.dev/deployment/android#shrinking-your-code-with-r8) said that the R8 can be disabled with the `--no-shrink` flag when run `flutter build apk`.

But after I tried this, I found it doesn't work, the only way to disable R8 is modify the build.gradle.

Until I run the `flutter build apk --help --verbose` I just konw that this flag doesn't work any more, and this flag was hide without the `--verbose` flag, this flag confused me for a long time.
<img width="1117" alt="image" src="https://github.com/flutter/flutter/assets/24455689/6d5b2edf-1562-4fa9-ad2f-a400461f6141">

I think it's a nessery to clarify this in the docs.

### Proposal

Please update the part of R8 in the official docs.
Or show this flg without `--verbose` when run `flutter build apk --help`(I event don't konw the --verbose flag can work with the --help command before...)

**Comment by gmackall** [comment]
Thanks for the report! Opened as a website issue here: https://github.com/flutter/website/issues/10032
