### ISSUE TITLE
Can't get screen size in release mode.

### ISSUE THREAD

**Issue by coderJohnZhang** [flutter/flutter#14113]
## Steps to Reproduce

I want to get the size of the screen, here is my code:

`final Size screenSize = window.physicalSize / window.devicePixelRatio;`

When I run app in debug mode , the print of the `screenSize` is `Size(960.0, 540.0)`, but when in release mode, the print of the `screenSize` is `Size(0.0, 0.0)`.

## Logs

`flutter run`

D:\flutter_tv>flutter run
Launching lib/main.dart on Percee TV II in debug mode...
Initializing gradle...                                1.0s
Resolving dependencies...                             2.0s
Running 'gradlew assembleDebug'...                   11.7s
Built build\app\outputs\apk\app-debug.apk (23.8MB).
Installing build\app\outputs\apk\app.apk...           8.2s
I/FlutterActivityDelegate( 8892): onResume setting current activity to this
Syncing files to device Percee TV II...
I/flutter ( 8892): initState() screenSize = Size(960.0, 540.0)

`flutter run --release`

D:\flutter_tv>flutter run --release
Initializing gradle...                                1.0s
Resolving dependencies...                             1.9s
Launching lib/main.dart on Percee TV II in release mode...
Running 'gradlew assembleRelease'...                  2.9s
Built build\app\outputs\apk\app-release.apk (8.6MB).
I/FlutterActivityDelegate( 9183): onResume setting current activity to this
I/flutter ( 9183): initState() screenSize = Size(0.0, 0.0)

## Flutter Doctor

D:\flutter_tv>flutter doctor
[√] Flutter (on Microsoft Windows [Version 10.0.14393], locale zh-CN, channel alpha)
    • Flutter at D:\flutter
    • Framework revision 8f65fec5f5 (5 weeks ago), 2017-12-12 09:50:14 -0800
    • Engine revision edaecdc8b8
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.d8ae797298c3a6cf8dc9f4558707bd2672224d3e

[√] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at D:\sdk
    • Android NDK at D:\sdk\ndk-bundle
    • Platform android-26, build-tools 26.0.2
    • ANDROID_HOME = D:\sdk
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2017.3)
    • Flutter plugin version 20.0.3
    • Dart plugin version 173.3942.31

[√] Connected devices
    • Percee TV II • 192.168.1.100:5555 • android-arm • Android 7.0 (API 24)

**Comment by Hixie** [comment]
In release mode we launch the Dart code faster than we can get the dimensions from the system, so we don't know the size straight away. If you listen to onMetricsChanged, you will be notified when the value changes.

If you're using the Flutter framework, rather than dealing with Window directly, I recommend using MediaQuery, which encapsulates the update mechanism cleanly with the widgets build methods, etc.

**Comment by coderJohnZhang** [comment]
Solve it, thanks!

**Comment by ollydixon** [comment]
> In release mode we launch the Dart code faster than we can get the dimensions from the system, so we don't know the size straight away. If you listen to onMetricsChanged, you will be notified when the value changes.
> 
> If you're using the Flutter framework, rather than dealing with Window directly, I recommend using MediaQuery, which encapsulates the update mechanism cleanly with the widgets build methods, etc.

It would be nice if we had some docs on the property for that. Just spend hours trying to fix this issue wondering why the window.devicePixelRatio wasn't working on release versions of my devices.
