### ISSUE TITLE
flutter_packaging_test failing consistently in presubmit

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#141188]
### Type of Request

bug

### Infrastructure Environment

LUCI

### What is happening?

Many PRs are failing `flutter_packaging_test `

https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20flutter_packaging_test
https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20flutter_packaging_test
https://ci.chromium.org/ui/p/flutter/builders/try/Mac_arm64%20flutter_packaging_test
https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20flutter_packaging_test

Example of error:
```
 Running "git clone -b master https://flutter.googlesource.com/mirrors/flutter" in /Volumes/Work/s/w/ir/x/w/archive.
 Cloning into 'flutter'...
 Running "git reset --hard b3fbdf485e3538c7044b9d22c708e30beb5b6575" in /Volumes/Work/s/w/ir/x/w/archive/flutter.
 fatal: Could not parse object 'b3fbdf485e3538c7044b9d22c708e30beb5b6575'.
 Error: Running "git reset --hard b3fbdf485e3538c7044b9d22c708e30beb5b6575" in /Volumes/Work/s/w/ir/x/w/archive/flutter failed
 ```
 
 Looks like infra owns these tests: 
 https://github.com/flutter/flutter/blob/7bf375b58c9d027b14801b663ddb98716d783746/TESTOWNERS#L331

### Expected results

I expect the tests to pass

**Comment by jmagman** [comment]
Hm, why would it be running packaging on a PR commit?  In this case https://github.com/flutter/flutter/pull/141137/commits/b3fbdf485e3538c7044b9d22c708e30beb5b6575

**Comment by CaseyHillers** [comment]
I sent https://flutter-review.googlesource.com/c/recipes/+/53860 for a revert.

**Comment by CaseyHillers** [comment]
Recipes CL landed. Rerunning the check run will get back to a passing state.
