### ISSUE TITLE
mac Phase3 upgrades - flutter devicelab prod pool

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#141129]
### Type of Request

bug

### Infrastructure Environment

devicelab, mac

### What is happening?

Per https://github.com/flutter/flutter/issues/134737 phase3 tasks (x86 iOS devicelab bots - Keep 2 bots on macOS 12 and upgrade the rest to macOS 13), upgrade the following prod pool devicelab machines to macOS 13.6.1:

flutter-devicelab-mac-27
flutter-devicelab-mac-28
flutter-devicelab-mac-29
flutter-devicelab-mac-30

**Comment by vashworth** [comment]
Also, please ensure the following after each upgrade:

Delete any directories within /opt/flutter/xcode if applicable.

Also verify /opt/flutter/xcode is owned by swarming user.

Run DevToolsSecurity - should get response "Developer mode is already enabled."
If you don't get the message, run sudo /usr/sbin/DevToolsSecurity -enable to enable.

**Comment by kentnguyen99** [comment]
Upgrading MacOS version 13.6.1 on following machines below have been completed and ready for service.
flutter-devicelab-mac-27
flutter-devicelab-mac-28
flutter-devicelab-mac-29
flutter-devicelab-mac-30

**Comment by kentnguyen99** [comment]
All works have been completed and ticket is closed.
