### ISSUE TITLE
[quick_actions] Enable for Android emulators

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#141136]
We had this test running in Android emulators, but in late December it suddenly became *incredibly* flake (like, <25% pass rate, maybe even <10%). This change seemed to be out-of-band, and about the same time as what's described in https://github.com/flutter/flutter/issues/140987 and with similar effect (but in a different integration test), so it may have the same underlying cause. Even if so though, we don't know what that underlying cause actually is (i.e., why we suddenly needed to add code to `file_selector_android` tests to dismiss dialogs, and what those dialogs were).

Unfortunately the failure log doesn't tell us much:
```
> Task :app:connectedDebugAndroidTest
Starting 3 tests on android_34_google_apis_x64(AVD) - 14

io.flutter.plugins.quickactionsexample.QuickActionsTest > appShortcutLaunchActivityAfterStarting[android_34_google_apis_x64(AVD) - 14] [31mFAILED [0m
	java.lang.AssertionError: AppShortcut:action_one does not launch the correct activity
	at org.junit.Assert.fail(Assert.java:89)
Tests on android_34_google_apis_x64(AVD) - 14 failed: There was 1 failure(s).

> Task :app:connectedDebugAndroidTest FAILED
```

I'm opting this package out of emulators again for now to get the tree back to a functional state. (It will continue to run on devices via FTL.)

**Comment by gmackall** [comment]
@stuartmorgan do you know if the flake has been re-produced anywhere except our ci? It sounds like it doesn't reproduce in FTL, but I'm unaware if anyone has reproduced it locally

**Comment by reidbaker** [comment]
`dart run ./script/tool/bin/flutter_plugin_tools.dart native-test --android --no-unit --packages=quick_actions_android` should be the command to test this with a local checkout. 
However that command it failing for me because we are targeting java 8 and the ability to target java 8 is about to be removed (similar to https://stackoverflow.com/questions/64791058/warning-options-source-value-7-is-obsolete-and-will-be-removed-in-a-future-re) and someplace we set -Werror  so the build fails.

**Comment by stuartmorgan** [comment]
> @stuartmorgan do you know if the flake has been re-produced anywhere except our ci? It sounds like it doesn't reproduce in FTL, but I'm unaware if anyone has reproduced it locally

I don't think so, but I don't know that anyone else has tried to repro it yet. There were a few layers of problems that built up in the packages tree over break so we've been slowly digging our way out and only recently got to this one.

**Comment by reidbaker** [comment]
```watch --errexit "/Users/reidbaker/packages/packages/quick_actions/quick_actions_android/example/android/gradlew app:connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.notAnnotation=io.flutter.plugins.DartIntegrationTest --no-configuration-cache --continue --warning-mode=summary -D=org.gradle.java.home=/Applications/Android\ Studio\ with\ Blaze\ Beta.app/Contents/jbr/Contents/Home/"```

Command to repeatedly run the tests over and over on my machine

**Comment by reidbaker** [comment]
I ran this for 3h this morning in a loop with no flakes. There is good evidence that the test flakes but I think something about either the emulator, or the environment is critical for making the flake happen often.
