### ISSUE TITLE
Add Video Cache Support

### ISSUE THREAD

**Issue by Firooz-Smart** [flutter/flutter#141155]
### Use case

I know that better_player supports caching videos, which is built upon the video_player package, but it has been a long time without an update, and it also does not play some types of videos. so we need caching support in the underlying player.

### Proposal

Please add video cache support, as it is required for streaming.

**Comment by danagbemava-nc** [comment]
I believe this is a duplicate of https://github.com/flutter/flutter/issues/28094. 

Kindly subscribe to the original issue for updates. 

Closing from here. 

Thank you
