### ISSUE TITLE
Support for matrix types in FragmentShaders

### ISSUE THREAD

**Issue by anlumo** [flutter/flutter#141286]
### Use case

3D rendering math relies on matrices and multiplying them for coordinate transformations. This is directly supported by GLSL fragment shaders via the mat3, mat4, mat3x4, etc types. [Here is the documentation](https://www.khronos.org/opengl/wiki/Data_Type_(GLSL)#Matrices). Implementing support for this in Flutter would allow more complex transformations in FragmentShader uniforms.

### Proposal

Right now, only `setFloat` and `setImageSampler` are implemented. These do not work for matrix types in GLSL, even though they do actually compile (it's a runtime error). I propose adding a new function that takes a `Float64List` to set a matrix uniform.

**Comment by jonahwilliams** [comment]
Matrix types seem to work fine? Without a specific example that is failing I'm not sure what the problem could be. This shows red as you'd expect and not green.

```glsl
uniform mat4 example_data;

out vec4 frag_color;

void main() {
  if (example_data[0][0] == 1) {
    frag_color = vec4(1.0, 0.0, 0.0, 1.0);
  } else {
    frag_color = vec4(0.0, 1.0, 0.0, 1.0);
  }
}

```

```dart
// Copyright 2014 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'dart:ui' as ui;
import 'package:flutter/widgets.dart';

late final ui.FragmentProgram program;

void main() async {
  program = await ui.FragmentProgram.fromAsset('assets/shader.frag');
  runApp(
    Center(
      child:
        CustomPaint(painter: FooPainter(), size: const Size(400, 400)),
      ),
    );
}

class FooPainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    final ui.FragmentShader shader = program.fragmentShader();
    shader.setFloat(0, 1);
    canvas.drawRect(const Rect.fromLTWH(0, 0, 400, 400), Paint()..shader = shader);
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) {
    return true;
  }
}
```

**Comment by anlumo** [comment]
Hmm weird, I could have sworn that it didn't work when I tried it, but now I can't reproduce the issue.
