### ISSUE TITLE
Receive intents - device share menu 

### ISSUE THREAD

**Issue by gcstr** [flutter/flutter#14127]
This might be considered a duplicate of https://github.com/flutter/flutter/issues/357 but it's not exactly the same issue.

I'd like to expose my application to the global share menu and to receive data from other applications, not only browsers.

The OS's share menu usually allows sharing data between apps like simple strings or even images.
Is it planned for Flutter?

**Comment by mrbm** [comment]
Hey guys, excited about flutter! Following up on @gcstr request, very interested in the receiving intents abilities as well. To further clarify, would like to be in browser app like safari or chrome, and then share the link of a page to my flutter app directly from the browser app. Or another case would be using the youtube app and then sharing a video link from the youtube app for my flutter app to receive it with the confirmation coming from the flutter app giving a message that is was received by the app. Thoughts on accomplishing this? This would allow for the basic functionality found in a social bookmarking app. 

Thanks!

**Comment by mrbm** [comment]
@zoechi #7111 references references data going outbound of your flutter app and suggests https://pub.dartlang.org/packages/share, but I don't think it references data going inbound to the flutter app.

Love anybodies thoughts!

**Comment by msveden** [comment]
I want to do the same thing as the OP and the only thing I find how to do is open the share menu. That is *not* what the OP is asking for. In a browser there is a share action that opens a menu with ways of sharing, can a Flutter app be added to that menu?

**Comment by zoechi** [comment]
@msveden https://flutter.io/flutter-for-android/#how-do-i-handle-incoming-intents-from-external-applications-in-flutter

**Comment by msveden** [comment]
OK I will just build my app in React Native then. Thanks for taking time to answer my questions!

**Comment by d-silveira** [comment]
@gcstr check out https://github.com/d-silveira/flutter-share it does exactly what you need, currently for Android

**Comment by gcstr** [comment]
Thanks a lot @d-silveira!
I'll give it a try today.

**Comment by rlee1990** [comment]
@zoechi is there a link on how to receive incoming extensions on ios?

**Comment by zoechi** [comment]
@rlee1990 I'm not aware of one, but that doesn't necessarily mean there isn't.

**Comment by psrcek** [comment]
I see this issue is pretty old, is there any better option for this in 2019?
