### ISSUE TITLE
TextField Input emoticons display abnormally

### ISSUE THREAD

**Issue by WuChuanRong** [flutter/flutter#141254]
### Steps to reproduce

https://github.com/flutter/flutter/assets/33706740/1f016490-0cf5-4ad2-b229-c58945da174d

1.When Input emoticons display abnormally

### Expected results

Input emoticons display normally

### Actual results

1.When Input emoticons display abnormally

### Code sample

<details open><summary>Code sample</summary>

```dart
TextField(
        controller: textController,
        decoration: InputDecoration(
            isCollapsed: true,
            border: InputBorder.none,
            focusedBorder: InputBorder.none,
            hintText: placeholder,
            hintMaxLines: 3,
            hintStyle: const TextStyle(fontSize: 14, color: AppColors.grey777)
        ),
        maxLines: null,
        style: const TextStyle(fontSize: 14, color: Colors.black, height: 1.5),
      )
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.4, on macOS 13.6 22G120 darwin-arm64 (Rosetta), locale zh-Hans-HK)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Hi @WuChuanRong 
I checked this on a simple TextField (without any properties) on `iPhone 7, iOS 15.8` but can't reproduce this issue. I see the video you are providing is on a production app, can you try checking this on a simple sample code with an empty TextField? 

Also, which device are you checking on? (OS, model)

**Comment by WuChuanRong** [comment]
Hi @huycozy If you just express your expression, the numbers will appear.

**Comment by huycozy** [comment]
Can you please be more specific with more information? Please confirm questions [above](https://github.com/flutter/flutter/issues/141254#issuecomment-1884726656). Thanks!

Here is my demo with my device (it works fine without issue):

<details>
<summary>Demo</summary>


https://github.com/flutter/flutter/assets/104349824/8f115d0a-b5a6-498c-bd46-97352ad66d7b


</details>

**Comment by WuChuanRong** [comment]
Hi @huycozy flutter version 3.13.4, iphone emulator iphone 15 Pro Max - iOS 17.0

**Comment by huycozy** [comment]
I just checked this on the same iOS version device (17.0) but the issue doesn't appear.

<details>
<summary>Demo</summary>

<img width="400" src="https://github.com/flutter/flutter/assets/104349824/aee48d3c-7193-40e9-8d15-2a7fe5ca93b5">
</details>

Does this issue only appear on your project or also on a minimal sample code? Could you try the minimal sample code below on a new Flutter project and confirm?

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
            child: TextField(
          decoration: InputDecoration(
              isCollapsed: true,
              border: InputBorder.none,
              focusedBorder: InputBorder.none,
              hintText: 'placeholder',
              hintMaxLines: 3,
              hintStyle: TextStyle(fontSize: 14)),
          maxLines: null,
          style: TextStyle(fontSize: 14, color: Colors.black, height: 1.5),
        )),
      ),
    );
  }
}

```
</details>
