### ISSUE TITLE
Roll vulkan-deps forward

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#141277]
To fix the g3 build of the engine a roll up to https://github.com/KhronosGroup/SPIRV-Cross/commit/ec87a0365521fd268c20608cd6ba5f41b5040e71 will be helpful.

See b/319373605.

cc @dnfield @jason-simmons @jiahaog

**Comment by jason-simmons** [comment]
See https://github.com/flutter/flutter/issues/138117

**Comment by jonahwilliams** [comment]
This is currently blocked on a project to update minimum API levels on Android.

**Comment by zanderso** [comment]
Waiting on b/319373605.

**Comment by jiahaog** [comment]
Clients internally have been migrated to use `minSdkVersion` of >= 21 and we should be unblocked here.
