### ISSUE TITLE
flutter/engine does not build with Bazel

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#14125]
We may eventually be required to add a Bazel build support in order to build our engine binaries on specific parts of Google's infrastructure.  (Not urgently, but there are factors suggesting to me that we may eventually need to.)

There has been at least some discussion of GN/Bazel conversion tools:
https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/wl1T6XX2gg8

GN, being a meta build system, might just have a Bazel generator these days, I don't know.

FYI @tvolkert @chinmaygarde @cbracken

**Comment by Hixie** [comment]
cc @jamesr @abarth who might know where we should start when investigating this.

**Comment by abarth** [comment]
I don't know anything more than what is in that thread.

**Comment by cbracken** [comment]
The engine builds with Blaze internally. I don't believe we have any intention of supporting external Bazel builds, but if this is still needed please re-open.

**Comment by hochhaus** [comment]
@cbenhagen It is strongly desired at my company! Please reopen.

**Comment by prestonvanloon** [comment]
Please reopen. This is needed.

**Comment by chinmaygarde** [comment]
> The engine now builds with Blaze internally.

Only a subset of targets build internally and none of the apps shipping use artifacts built from those internal Bazel rules. It is certainly not production ready or anywhere close to it. There are also aren't any efforts underway to close the gap in supported targets with the GN rules. The minimal rules present are used for prototyping small engine changes in that environment. Supporting build rules for multiple build systems in parallel is a massive undertaking.

> It is strongly desired at my company

This issue only relates to Flutter Engine builds and not Flutter applications themselves. Can you confirm you need to build a custom engine using Bazel?

**Comment by hochhaus** [comment]
> Can you confirm you need to build a custom engine using Bazel?

Thanks for the clarification. We only require flutter applications. I retract my previous comment.

**Comment by chinmaygarde** [comment]
> We only require flutter applications.

Thanks for clarifying. Can you file a bug for the same? I don't see that issue filed already so it may not be on the teams radar.

**Comment by hochhaus** [comment]
Unfortunately, I think it was already filed and declined in #19680. Specifically https://github.com/flutter/flutter/issues/19680#issuecomment-460797316.

**Comment by cbracken** [comment]
FWIW I'd imagine that if you wanted to just write flutter rules youself it's probably not actually a massive undertaking if you were to build on top of https://github.com/cbracken/rules_dart
