### ISSUE TITLE
[Impeller] Either fix `gl_FragCoord` for runtime effect shaders or print a warning when it's used.

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#141236]
We [document](https://docs.flutter.dev/ui/design/graphics/fragment-shaders#current-position) that you cannot sanely use `gl_FragCoord` in Impeller based fragment shaders, but you can in Skia.

If we really and truly can't fix this, we should print a warning when compiling a runtime effect based shader with this code so that users know to fix it.

**Comment by dnfield** [comment]
One possible way to fix this would be to stop making it magically work for the Skia backend.

**Comment by dnfield** [comment]
The more I think about this, the more convinced I am that we should "break" Skia shaders by no longer magically making gl_FragCoord work the way it does, and instead make them use the `FlutterFragCoord()` method.

**Comment by jonahwilliams** [comment]
We already document the expected behavior. Closing as wont-fix
