### ISSUE TITLE
"code ." in cmd is not found.

### ISSUE THREAD

**Issue by marycanonce** [flutter/flutter#141262]
its when I want to call the directory of flutter name to open vs code and it said:

"'code' is not recognized as an internal or external command,
operable program or batch file."

Can I ask a help?

**Comment by dam-ease** [comment]
Helllo @marycanonce.
Not sure this is an issue with flutter itself. 
From the error message you shared, Can you check out https://stackoverflow.com/questions/46638944/code-is-not-recognized-as-an-internal-or-external-command to see if it works in your case?
If not, kindly provide more information on this please

**Comment by marycanonce** [comment]
Thank you, I'll check it
