### ISSUE TITLE
Platform.environment does not read variable for flutter test.

### ISSUE THREAD

**Issue by polina-c** [flutter/flutter#141299]
On mac `print('LEAK_TRACKING = ${Platform.environment['LEAK_TRACKING']}')` gives this output:

```
polinach-macbookpro3:flutter polinach$ echo $LEAK_TRACKING
true

polinach-macbookpro3:flutter polinach$  flutter test /Users/polinach/_/flutter_dev/packages/flutter/test/widgets/page_view_test.dart
00:01 +0: loading /Users/polinach/_/flutter_dev/packages/flutter/test/widgets/page_view_test.dart                                                                              
LEAK_TRACKING = null
...
```

**Comment by polina-c** [comment]
Flutter 3.19.0-3.0.pre.31 • channel master • git@github.com:flutter/flutter.git
Framework • revision ee4afd7179 (5 hours ago) • 2024-01-10 10:45:31 -0500
Engine • revision b361a60ae2
Tools • Dart 3.4.0 (build 3.4.0-12.0.dev) • DevTools 2.31.0

**Comment by stuartmorgan** [comment]
How was `LEAK_TRACKING` set? The behavior shown here would be normal if you `LEAK_TRACKING=true` instead of `export LEAK_TRACKING=true`, for instance.

**Comment by polina-c** [comment]
True: https://stackoverflow.com/questions/1158091/defining-a-variable-with-or-without-export
Thank you!
