### ISSUE TITLE
Network resources error

### ISSUE THREAD

**Issue by marycanonce** [flutter/flutter#141243]
![a](https://github.com/flutter/flutter/assets/131778112/5751f627-ba8f-4877-a4ee-a8ad239a4aea)

How to solve this?

**Comment by dam-ease** [comment]
Thanks for filing this.
This is similar to https://github.com/flutter/flutter/issues/140319, you can check out https://github.com/flutter/flutter/issues/140319#issuecomment-1871180470 to see if it works in your case?
Both seem to be a duplicate of https://github.com/flutter/flutter/issues/125488, can you check it out as well.

Also, Please refrain from posting pictures if not necessary.
