### ISSUE TITLE
Fatal Exception due to "Reply already submitted" error 

### ISSUE THREAD

**Issue by ashwin-dailype** [flutter/flutter#141263]
### What package does this bug report belong to?

image_picker

### What target platforms are you seeing this bug on?

Android

### Have you already upgraded your packages?

Yes

### Dependency versions

<details open><summary>pubspec.lock</summary>

```lock
...
  image_picker:
    dependency: "direct main"
    description:
      name: image_picker
      sha256: f202f5d730eb8219e35e80c4461fb3a779940ad30ce8fde1586df756e3af25e6
      url: "https://pub.dev"
    source: hosted
    version: "0.8.7+3"
  image_picker_android:
    dependency: transitive
    description:
      name: image_picker_android
      sha256: "1ea6870350f56af8dab716459bd9d5dc76947e29e07a2ba1d0c172eaaf4f269c"
      url: "https://pub.dev"
    source: hosted
    version: "0.8.6+7"
  image_picker_for_web:
    dependency: transitive
    description:
      name: image_picker_for_web
      sha256: "98f50d6b9f294c8ba35e25cc0d13b04bfddd25dbc8d32fa9d566a6572f2c081c"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.12"
  image_picker_ios:
    dependency: transitive
    description:
      name: image_picker_ios
      sha256: a1546ff5861fc15812953d4733b520c3d371cec3d2859a001ff04c46c4d81883
      url: "https://pub.dev"
    source: hosted
    version: "0.8.7+3"
  image_picker_platform_interface:
    dependency: transitive
    description:
      name: image_picker_platform_interface
      sha256: c1134543ae2187e85299996d21c526b2f403854994026d575ae4cf30d7bb2a32
      url: "https://pub.dev"
    source: hosted
    version: "2.9.0"
...
```

</details>

### Steps to reproduce

Use the pickImage function with source set as gallery and pick an image. This issue is more frequent in the release mode of build

### Expected results

Ideally the user should be prompted by the system to pick an image and the image's path should be accessible in the code

### Actual results

As soon as the user selects an image in the android provided image picker, the app crashes and the user is taken back to the launcher.

### Code sample

<details open><summary>Code sample</summary>

```dart

final ImagePicker picker = ImagePicker();
final directory = await getApplicationDocumentsDirectory();
final imagesDirectory = Directory('${directory.path}/images');

if (!imagesDirectory.existsSync()) {
  imagesDirectory.createSync();
}

final imageFile = await picker.pickImage(
        source: ImageSource.gallery,
        imageQuality: 65,
        maxWidth: 900,
      );
      if (imageFile != null) {
        final fileName = basename(imageFile.path);
        await imageFile.saveTo('${imagesDirectory.path}/$fileName');

        setState(() {
          edgeImagePaths[index] = '${imagesDirectory.path}/$fileName';
          // edgeImagePaths is a variable declared in the stateful widget under which the above code is being used
        });

      } else {
        Fluttertoast.showToast(msg: 'No image selected');
      }
```
</details>

### Screenshots or Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:1000075213 flg=0x1 }} to activity {com.dailype.dailype.dev/com.dailype.dailype.MainActivity}: java.lang.IllegalStateException: Reply already submitted
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5462)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5501)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2291)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:210)
       at android.os.Looper.loop(Looper.java:299)
       at android.app.ActivityThread.main(ActivityThread.java:8319)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.2.1 23C71 darwin-arm64, locale en-IN)
    • Flutter version 3.16.5 on channel stable at /Users/ashwin/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision 78666c8dc5 (3 weeks ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
    • Android SDK at /Users/ashwin/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    ✗ Unable to get list of installed Simulator runtimes.
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (3 available)
    • M2007J20CI (mobile) • 192.168.29.173:37111 • android-arm64  • Android 12 (API 31)
    • macOS (desktop)     • macos                • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)        • chrome               • web-javascript • Google Chrome 120.0.6099.199

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment]
Hi @ashwin-dailype 
Which Android device are you checking on? (OS, model) 

Can you please provide the entire output log of `flutter run -v`? 

Also, which image source do you choose from? (Google Photo, Phone Gallery..) 

I also see the package version is not the latest one, you can try upgrading to see if the issue persists or not.

**Comment by ashwin-dailype** [comment]
Hello @huycozy!

I did update the package to `^1.0.7` and face the same issue, but I currently don't have the verbose logs for the same. I'll update the thread once I have it. I did attach a few stack trace text files of three different occurrences of this crash at the end of this comment 

Whenever I faced it, I was using the system gallery and not google photos. It is also worth noting that sometimes this crash doesn't occur on reopening the app after clearing it from recents. But again this behaviour doesn't seem to have a pattern I can recognise, it is very random.

As for the devices this issue is occurring on, please refer to the below Crashlytics snips. 

### Crashlytics stats
<img width="960" alt="image" src="https://github.com/flutter/flutter/assets/130335509/f25fdbdf-926a-4feb-b303-52a629c96f69">
<img width="460" alt="image" src="https://github.com/flutter/flutter/assets/130335509/720e6405-fb4b-456d-881d-973dd96c8ca1">


### Stacktrace files

- [com.dailype.dailype_issue_d48aa058fe4aecea479e19cb925ceb84_crash_session_659E102A006F00010B1BB59BFC73B4E2_DNE_0_v2_stacktrace.txt](https://github.com/flutter/flutter/files/13898557/com.dailype.dailype_issue_d48aa058fe4aecea479e19cb925ceb84_crash_session_659E102A006F00010B1BB59BFC73B4E2_DNE_0_v2_stacktrace.txt)
- [com.dailype.dailype_issue_d48aa058fe4aecea479e19cb925ceb84_crash_session_659E330801B000017F34319063AA0C3A_DNE_0_v2_stacktrace.txt](https://github.com/flutter/flutter/files/13898558/com.dailype.dailype_issue_d48aa058fe4aecea479e19cb925ceb84_crash_session_659E330801B000017F34319063AA0C3A_DNE_0_v2_stacktrace.txt)
- [com.dailype.dailype_issue_d48aa058fe4aecea479e19cb925ceb84_crash_session_659F6A6103AD00017F9B1B64D43FC535_DNE_0_v2_stacktrace.txt](https://github.com/flutter/flutter/files/13898559/com.dailype.dailype_issue_d48aa058fe4aecea479e19cb925ceb84_crash_session_659F6A6103AD00017F9B1B64D43FC535_DNE_0_v2_stacktrace.txt)

**Comment by huycozy** [comment]
Thanks for your update with more information. 

Since you can reproduce it (at least randomly), can you please give it a try with [plugin sample code](https://github.com/flutter/packages/tree/main/packages/image_picker/image_picker/example)? (to make sure this is not caused by your implementation). 

And please also provide the device you are checking on (OS, model). Thanks!

**Comment by Gordon2780** [comment]
In my production environment, I experienced a crash similar to yours, with about 200 users experiencing this error. I used the latest version image_picker: ^1.0.7, and when I reproduced the problem on my device, I didn't find the problem.


It looks like when interact with native code Repeated calls to the callback event response and college at IO. Flutter. Plugins. The imagepicker. Messages $ImagePickerApi $1. Success (: 10) 
at io.flutter.plugins.imagepicker.Messages$ImagePickerApi$1.success(:2)


Fatal Exception: java.lang.IllegalStateException: Reply already submitted
       at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(:35)
       at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler$1.reply(:14)
       at io.flutter.plugins.imagepicker.Messages$ImagePickerApi$1.success(:10)
       at io.flutter.plugins.imagepicker.Messages$ImagePickerApi$1.success(:2)
       at io.flutter.plugins.imagepicker.ImagePickerDelegate.finishWithSuccess(:39)
       at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(:56)
       at io.flutter.plugins.imagepicker.ImagePickerDelegate.lambda$onActivityResult$0()
       at io.flutter.plugins.imagepicker.ImagePickerDelegate.b()
       at io.flutter.plugins.imagepicker.a.run(:6)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)
