### ISSUE TITLE
Flutter upgrade should refuse to run or run properly on a branch that comes from a fork.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#14120]
I recently tried to run flutter upgrade because I was prompted to:
```/usr/local/google/home/gspencer/code/flutter/bin/flutter --no-color packages get
Building flutter tool...
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ WARNING: your installation of Flutter is 45 days old.                      ║
  ║                                                                            ║
  ║ To update to the latest version, run "flutter upgrade".                    ║
  ╚════════════════════════════════════════════════════════════════════════════╝

Running "flutter packages get" in catalog...
(code/flutter:traversal) -- flutter > flutter upgrade
Unable to upgrade Flutter: no upstream repository configured.
(code/flutter:traversal) -- flutter > git remote -v
origin	git@github.com:gspencergoog/flutter.git (fetch)
origin	git@github.com:gspencergoog/flutter.git (push)
upstream	git@github.com:flutter/flutter.git (fetch)
upstream	git@github.com:flutter/flutter.git (push)
```

And because my branch wasn't branched from flutter/flutter.git, but rather from gspencergoog/flutter.git, `flutter upgrade` errored out without telling me anything about what I should do, how I could fix it, or why it failed. This seems like a case specific to people who work on the flutter project, but really anyone who forks flutter for any reason will encounter it eventually.

We should:
1) Not warn about stale installs for forked repos
1) Fail to run `flutter upgrade` in a forked repo branch, or, alternatively
1) Make `flutter upgrade` do something useful in a forked repo branch and not error out.
1) At the very least, change the error message so that it is truthful (I *did* have an upstream repo configured, it just didn't match with the origin).

**Comment by willlarche** [comment]
Just ran into this today. Got:
```
Unable to upgrade Flutter: no origin repository configured. Run 'git remote add
origin https://github.com/flutter/flutter' in /Users/larche/flutter
```
even tho I have that remote. Something more useful would be great.

**Comment by jdeltoft** [comment]
I'm having this same quandary right now.  If I have forked flutter, and have origin set to my repo and upstream set to the official flutter github, how should I run "flutter upgrade"?

**Comment by gspencergoog** [comment]
If you have that setup, you should probably not use `flutter upgrade`, since it won't do what you want. That is in fact the setup that most developers who work on Flutter itself have.

I just do this to update locally:
```
git fetch upstream
git checkout master
git reset --hard upstream master
```

I also follow that with this, in order to update the `master` on my fork with the contents of the unchanged `flutter/master` branch. Do NOT do this step if you actually do work on your fork of `master`, because it will replace your forked `master` and all its history with the current `master` from `flutter/flutter` and its history, which is what I want, but may not be what you want.  If you do your work on your own feature branch (which I would highly recommend), this won't affect that branch, only your fork of `master`.

```
git push --force origin master
```

**Comment by jdeltoft** [comment]
so yea, I had this setup because I wanted to try my hand at submitting a change to flutter itself.  But I've since learned more about my issue and abandoned my PR.  So to "fix" myself I just changed origin back to the official git repo with 

    git remote set-url https://github.com/flutter/flutter.git

And then I checked out master and was fine.

**Comment by gspencergoog** [comment]
Yes, that's the right way to switch back to being able to use `flutter upgrade`. To clean it up, you could also delete upstream with `git remote remove upstream` (but it's harmless to leave it).

**Comment by champ96k** [comment]
> ```
> git remote set-url origin https://github.com/flutter/flutter.git
> ```

Thanks, man, its work for me

**Comment by jonahwilliams** [comment]
We've had a lot of contributors attempt to solve this in the past few months. Generally though, I think that adding restrictions to our upgrade flow is too difficult to do in an adhoc manner, so any changes would need to be discussed/planned in a doc in advance and given the OK here before PRs are opened.
