### ISSUE TITLE
SliverFillRemaining overscrolls when bottom padding is set

### ISSUE THREAD

**Issue by shovelmn12** [flutter/flutter#141256]
### Steps to reproduce

Added sample code run on [dartpad](https://dartpad.dev/)

### Expected results

`SliverFillRemaining` needs to fill remaining screen size without padding, so not to create overscroll.
In the added sample I am getting a red box with padding of 30, only at the top and sides, fills up the screen with overscroll of 30, bottom padding.

Seems like that the only solution is to put the bottom padding inside `SliverFillRemaining`:

```dart
       SliverFillRemaining(
                          hasScrollBody: false,
                          child: Padding(
                            padding: const EdgeInsets.only(
                              bottom: 30,
                            ),
                            child: MyWidget(),
                          ),
                        ),
``` 

Which makes no sense as I dont always know what the padding is...

### Actual results

`SliverFillRemaining` overscroll with the exact size of bottom padding.
In the added sample I would expect to get a red box with padding of 30 fills up the screen.

### Code sample

<details open><summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
        home: Scaffold(
          body: SafeArea(
            child: CustomScrollView(
              slivers: [
                SliverPadding(
                  padding: const EdgeInsets.only(
                    top: 30,
                    left: 30,
                    right: 30,
                    bottom: 30, // comment and check overscroll
                  ),
                  sliver: MediaQuery.removePadding(
                    context: context,
                    removeBottom: true,
                    removeTop: true,
                    removeLeft: true,
                    removeRight: true,
                    child: SliverMainAxisGroup(
                      slivers: [
                        SliverFillRemaining(
                          hasScrollBody: false,
                          child: MyWidget(),
                        ),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      );
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Container(
        color: Colors.red,
        child: Center(
          child: Text(
            'Hello, World!',
            style: Theme.of(context).textTheme.headlineMedium,
          ),
        ),
      );
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Over scroll by 30 (bottom padding)
<img width="720" alt="Screenshot 2024-01-10 at 11 08 54" src="https://github.com/flutter/flutter/assets/39903489/f627ea41-0a11-4a1d-acd7-903c0d52ccaf">

No over scroll
<img width="692" alt="Screenshot 2024-01-10 at 11 09 31" src="https://github.com/flutter/flutter/assets/39903489/ce3036db-467f-4fd2-8da8-dd4465b13aa8">

</details>

### Logs

<details open><summary>Logs</summary>

```console
Running on [dartpad](https://dartpad.dev/)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Running on [dartpad](https://dartpad.dev/)
```

</details>

**Comment by moffatman** [comment]
Do you mean `MediaQueryData.padding`? That means there is something "above" the current context which is obstructing the bottom 30 pixels of the screen. So it's intended to overscroll, so you can reveal which content is hidden below the obstruction. Or am I missing something?

**Comment by shovelmn12** [comment]
I mean by `top`, `left` and `right` I can tell for sure that something is wrong here as the behaviour is not the same.

When setting `top`, `left` or `right`  sliver `SliverFillRemaining` is still filling only the remaining of the screen, but why when setting `bottom` it does not.

Check what happens when you set `top` to like 300, `SliverFillRemaining` is shrinking as it thinks the view port shrank, it will only be `viewport.height - topPadding`.

**Comment by Jjagg** [comment]
@shovelmn12

This is expected behavior. `SliverFillRemaining` fills the remaining space in the viewport and slivers are laid out top to bottom (in a vertical, non-reversed scroll view).

That means if you put padding around it, it will take up `viewport.height - padding.top`  starting at `padding.top`. Any bottom padding will be applied afterwards and cause the sliver content to exceed the viewport extent.

Do you have an actual use case that you cannot solve by putting a `Padding` inside the `SliverFillRemaining` instead?

**Comment by shovelmn12** [comment]
@Jjagg 

Hello, thanks for the explanation. And I think `SliverFillRemaining` is really confusing name and does not really help most of the time, ill try to explain my use case maybe I am using the wrong widgets.

What I am trying to create is a page that displays different widgets, depending on types from the server, and buttons at the bottom of the page, no matter what's widget size (it might need scrolling too).

Simplefied example:

```dart
class MyPage extends StatelessWidget {
  final String type;

  const MyPage({
    super.key,
    required this.type,
  });

  @override
  Widget build(BuildContext context) => Scaffold(
        body: SafeArea(
          child: CustomScrollView(
            slivers: [
              MyHeader(),
              if (type == "a") MyAWidget(),
              if (type == "b") MyBWidget(),
              if (type == "c") MyCWidget(),
              if (type == "d") MyDWidget(),
              MyButtons(),
              SomePadding(),
            ],
          ),
        ),
      );
}
```

Now I don't mind using `SliverFillRemaining` and do something in the lines:

```dart
class MyPage extends StatelessWidget {
  final String type;

  const MyPage({
    super.key,
    required this.type,
  });

  @override
  Widget build(BuildContext context) => Scaffold(
        body: SafeArea(
          child: CustomScrollView(
            slivers: [
              MyHeader(),
              SliverFillRemaining(
                hasScrollBody: false,
                child: Column(
                  children: [
                    if (type == "a") MyAWidget(),
                    if (type == "b") MyBWidget(),
                    if (type == "c") MyCWidget(),
                    if (type == "d") MyDWidget(),
                    MyButtons(),
                    SomePadding(),
                  ],
                ),
              ),
            ],
          ),
        ),
      );
}
```

But as I said I donnow what widget is going to display so do I set `hasScrollBody` to `true` or `false`?
And even if I set it to `true` how do I make sure it wont scroll if not needed?
It also ignores `SafeArea` as you stated it will add it at the bottom of the page...
I'd like to continue using slivers within `MyXWidget` and not like the workaround I wrote which uses `Column`s in all `MyXWidget`.

What I'd like to have is `RealSliverFillRemaining` that would always expaned to fill remaining of space in the screen regardless to where it's positioned. I know it's almost impossible due to the nature of flutter (I might be wrong here) so of course it's must be positioned last.

I'd say it need to follow `BoxConstraints(minHeight: viewPort - verticalPadding)` so it will give it's child at least the size of remaining of the screen or their own size, then it will be easy to get the requested behaviour.

I hope it's understandable enough!

**Comment by moffatman** [comment]
To clarify as I see it

```
HeaderWidget()
[some variable number of widgets]
FooterWidget()
```

And if the variable widgets are short, it should look like this:

```
HeaderWidget()
MyWidget1()
// vertical padding
FooterWidget()
```

But once variable widgets get tall enough, there will be no more padding in the middle, and actually we should inject the MediaQuery padding at the bottom to make it fully scrollable.

May need to write a custom `Sliver`, but it's certainly doable, let me think about it.

**Comment by shovelmn12** [comment]
Yeah but footer must stick to the bottom of the page regardless of the MyWidgetX size between header and footer.

Also MyWidgetX might be long so it would make sense to be able it to be a sliver

Thanks for your help

**Comment by Jjagg** [comment]
I don't know if I fully understood correctly what your goal is with SliverFillRemaining, but you may mean something like this:

```dart
        // You could apply outer padding inside the Scrollview by wrapping all your root slivers below in SliverSafeArea(bottom: false, sliver: SliverMainAxisGroup(slivers: [ ... ])) instead of this SafeArea.
        SafeArea(
          bottom: false
          child: CustomScrollView(
            slivers: [
              MyHeader(),
              if (type == "a") MyAWidget(),
              if (type == "b") MyBWidget(),
              if (type == "c") MyCWidget(),
              if (type == "d") MyDWidget(),
              SliverFillRemaining(
                hasScrollBody: false,
                child: SafeArea(
                  top: false,
                  left: false,
                  right: false,
                  child: Align(
                    alignment: Alignment.bottomCenter,
                    child: Column(
                      mainAxisSixe: MainAxisSize.min,
                      children: [
                        MyButtons(),
                        SomePadding(),
                      ],
                    ),
                  ),
                ),
              ),
            ],
          ),
```

This aligns buttons to the bottom with padding and correctly uses SliverFillRemaining so it won't exceed the viewport if MyXWidgets don't take up too much space.

I wrote this on mobile so it may contain typos. 

Key things:
- you can split up SafeArea/Padding to apply bottom padding inside SliverFillRemaining 
- you should only apply SliverFillRemaining to the element that needs to grow to fill the viewport, most of the time this is only the last sliver in the list; docs have some good examples: https://api.flutter.dev/flutter/widgets/SliverFillRemaining-class.html.

**Comment by moffatman** [comment]
Wait a sec, why can't you just use SafeArea above all the slivers? And just not draw at all under the MediaQuery.padding. Would be the simplest. Or is the thing above the slivers which causes the mediaquery padding transparent/semi-transparent?

**Comment by shovelmn12** [comment]
@Jjagg 

Ok, I just starting testing your idea and it hit me why it wont work.

I just have one widget (video player) which I want it to fill the space exactly all others can be whatever size they want. This one probably creates all the issues, otherwise your solution would work!!

Any ideas on how to solve that?

Thanks for the help BTW :)

**Comment by darshankawar** [comment]
@shovelmn12 If you are looking for a working solution, StackOverflow would be place to look for it. 
If you think there's currently a framework limitation for your case, then we can make the issue actionable here.

**Comment by shovelmn12** [comment]
Yes I think there is an issue with `SliverFillRemaining` as specified above!

**Comment by Jjagg** [comment]
@shovelmn12 I think you're expecting `SliverFillRemaining` to do something it's not designed for. It's intended to be the last sliver in a list. I fills the remaining space in the viewport or defers to its child for sizing if the viewport is already full, i.e. the slivers before it + its child take up more space than the viewport extent.
As is, I don't think this is actionable and i do think there are other ways to achieve the behavior you want, but it's still not 100% clear to me what that behavior is exactly.

> I just have one widget (video player) which I want it to fill the space exactly all others can be whatever size they want. 

If you want a sliver's height to match the viewport height you can use `LayoutBuilder`:

```dart
LayoutBuilder(
  builder: (context, constraints) => CustomScrollView(slivers: [
    VideoPlayer(height: constraints.maxHeight),
  ]),
);
```

**Comment by shovelmn12** [comment]
Yeah but that would fill up the whole screen, I have more widgets around there so we will get scrollable page

**Comment by Jjagg** [comment]
Yes, you would add those in the slivers list:
```dart
LayoutBuilder(
  builder: (context, constraints) => CustomScrollView(slivers: [
    SliverOtherWidget1(),
    SliverToBoxAdapter(child: SizedBox(height: constraints.maxHeight, child: VideoPlayer())),
    SliverOtherWidget2(),
  ]),
);
```
