### ISSUE TITLE
Failure to apply gclient vars from build config

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#141234]
The commit here https://github.com/flutter/engine/commit/555aa9bd3a7ce9d82f54a92cd6cf3ada29fa4f5d added a `gclient_vars` section to the `linux_benchmark` build config here: 

https://github.com/flutter/engine/commit/555aa9bd3a7ce9d82f54a92cd6cf3ada29fa4f5d#diff-8d8ebbe64cd5b9b28cbe0da5037a1a9873fd65158b900925b6b5986497c8fce0R8

And a few other places. While the new gclient var was included in some builds, like here:

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20linux_unopt/4991/overview, which spawned
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Production%20Engine%20Drone/536274/overview.

Note in the logs `logging` for step 1 `setup_build`, the `gclient_vars` section contains `'gclient_variables': {'use_rbe': True}`.

However in the `logging` logs for step 1 `setup_build` in `Linux linux_benchmarks`, there is no such `gclient_variables` section despite the section existing in the build config json:

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20linux_benchmarks/4177/overview

This was only caught in post submit because `Linux linux_benchmarks` doesn't run in presubmit, and the commit had to be reverted.

cc @godofredoc @keyonghan

**Comment by zanderso** [comment]
Maybe it's because the recipe is `engine_v2/builder` and not `engine_v2/engine_v2`?

**Comment by keyonghan** [comment]
Okay. There are two issues here:
1) `gclient_variables` is injected to subbuild as a property when scheduled from an orchestrator (the `linux_unopt` case). It is then populated to gclient sync via [`local-custom_vars`](https://flutter.googlesource.com/recipes/+/refs/heads/main/recipe_modules/repo_util/api.py#99). As for the `standalone` build (the `benchmark case`), no `gclient_variables` property exists. This explains why no corresponding values in the build.
2) The `standalone` build is reading the build config `.json` file from `cache`. (see the [checkout path](https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/engine_v2/builder.py#281), and [how](https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/engine_v2/builder.py#156) we get the `build` config from the checkout path). This makes it non-deterministic, depending on the last built/cached results, and this makes it unreliable whether we are testing the real config.

Proposed fix: checkout the `engine` repo for standalone targets which runs `builder.py` recipes directly, and then inject `gclient_variables` explicitly when running gclient checkout.

**Comment by keyonghan** [comment]
The fix has landed.
