### ISSUE TITLE
Image rotation issue

### ISSUE THREAD

**Issue by Gagandeep1408** [flutter/flutter#141266]
### Steps to reproduce

Click photo using front camera in android/iOS.

### Expected results

Image rotation

### Actual results

Image rotation

### Code sample

Image rotation

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Image rotation

**Comment by danagbemava-nc** [comment]
Hi @Gagandeep1408, what plugin are you using? 

Please provide the version of the plugin you're using. 

Please also provide the output of `flutter doctor -v` and a complete minimal reproducible code sample so that we can investigate this issue. 

PS: In the future, when filing an issue, please provide actionable information so that it can be properly investigated. 

Thank you

**Comment by Gagandeep1408** [comment]
I'm using the latest version.

You can capture an image from an iOS device and it will rotate the image.


Thank you


Gagandeep Singh | Project Manager
a: Nexever Pvt Ltd
e: ***@***.*** | w: www.nexever.com
p: +91-9653810896
<https://www.linkedin.com/in/gagan-deep-5538a4131>
<https://twitter.com/Gagan48782702?t=Ove10cQmMt-KMGX6Xf04XQ&s=09>

**Comment by huycozy** [comment]
@Gagandeep1408, this remains unclear. Please provide all information pointed out [above](https://github.com/flutter/flutter/issues/141266#issuecomment-1884878401).

**Comment by arlakay** [comment]
i have same issue, image captured rotate, using version camera: ^0.10.0+5

**Comment by danagbemava-nc** [comment]
Hi @arlakay, what platform(s) are you experiencing this on? Please provide a complete minimal reproducible code sample so that we can investigate this issue. 

What device(s) are you seeing this on?

It would help if you could provide some screenshots/screenrecordings as well. 

Thank youj

**Comment by arlakay** [comment]
happen on android only
compiled using flutter 3.7.0

**Comment by danagbemava-nc** [comment]
@arlakay, what device are you experiencing this on? 

Can you also share some screenshots?
