### ISSUE TITLE
[file_selector] Result of getDirectoryPath is not usable

### ISSUE THREAD

**Issue by CodeDoctorDE** [flutter/flutter#141250]
### Use case

I want to give users the option to use an external storage for documents.

### Proposal

Add option to allow persistent write permission on picked directory.
See point 3: 3. Read/Write any Arbitrary File into the Shared Location under https://medium.com/@vivekvashistha/how-to-save-a-file-in-shared-storage-location-in-android-13-c1e4fdf3d2cb

**Comment by CodeDoctorDE** [comment]
Hmm,
I look at it and found out it returns a content uri directory.
How can I use it to work with dart?
``dart
var path = ...;
var directory = Directory(path);
await directory.create(recursive: true);
...
````
does not work `PathNotFoundException: Creation failed, path = 'content://com.android.externalstorage.documents/tree/primary%3ADocuments/Documents/' (OS Error: No such file or directory, errno = 2)`.
How can I use this?

**Comment by dam-ease** [comment]
Hello @CodeDoctorDE.
Thanks for filing this. Not sure I fully understand this. I see the link shared in original comment contains how to do this, do you run into the error message shared i.e maybe this could be a bug or are you proposing a different method?

**Comment by CodeDoctorDE** [comment]
The thing is: The path you get with the plugin is not usable in a dart project.
You need to use native methods to interact with the directory.
It would be better if there is a way to get the real path out of it to create files and directories in it.

**Comment by dam-ease** [comment]
Please can you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code i.e. a single `main.dart` file we can run to reproduce this ?
Thank you

**Comment by CodeDoctorDE** [comment]
https://gist.github.com/CodeDoctorDE/c60d13d1706e8cfe03496313a96c820a
This is my demo.
The output of file selector seems to be a content directory that can't be used in dart

**Comment by dam-ease** [comment]
From the [docs](https://pub.dev/packages/file_selector#features-supported-by-platform), 

> † Choosing a directory is no supported on versions of Android before SDK 21 (Lollipop).

Can you confirm our Android SDK version?

**Comment by CodeDoctorDE** [comment]
Yes, I'm on android 13 (sdk 34).
The result is something like `content://com.android.externalstorage.documents/tree/primary%3ADocuments/Documents/` but this can't be used in flutter itself.
One fix could be changing the result to a real path, add a convertContentUriToRealPath method in file_selector or supporting this url in dart core.

**Comment by dam-ease** [comment]
Thanks for your response @CodeDoctorDE.
I ran this as well on an Android device (SDK 34) and can reproduce this result on my end as well.
I see this might be similar/related to https://github.com/flutter/flutter/issues/137616. Can you please check this out?
Also, if not, this is not a proposal for write permission any longer but for the result gotten from `getDirectory()`. Kindly clarify that as well.

**Comment by CodeDoctorDE** [comment]
Hello,
thanks for your response.
I think this issue is related to something else. Both has something to do with the getDirectoryPath function, but in this issue is about the result of it. Maybe both of them needs to be converted from a path to a content uri but I'm not very familiar with this.
I would keep this issue opened for this specific request.
After creating I further investigated this issue and had found that this problem is related to the result of the function instead of a write permission. I renamed this issue to clarify this.

**Comment by ChristianEdwardPadilla** [comment]
The same issues exists for the paths returned by `openFile` and `openFiles` on Android (the path value is a content URI and cannot be directly used in Dart). This behavior is not consistent with `image_picker`'s `pickImage` and `pickMultiImage`, which return absolute paths and can be used directly in Dart (for instance, to render an `Image` widget).

**Comment by camsim99** [comment]
In a draft PR, I was able to get file paths for `getDirectoryPath`, then started taking a look at `openFile`/`openFiles`. What I noticed by working on both is that it is extremely difficult to access file paths in the way that `file_selector` expects because Android prefers access via URIs, namely content URIs. Turns out that this is for a variety of reasons including privacy and performance as well as accessing files from different sorts of content providers.

`image_picker` handles content URIs by copying file contents into a temporary file and then returning the path of the temporary file, which I am wary of doing here because we can never be sure of the size of files/directories selected. Because I don't think that trying to use file paths is a future-proof solution, I'm working on outlining some alternative solutions.

**Comment by camsim99** [comment]
Decided to move forward with fixing `openFile`/`openFiles` by copying content of URIs into a temporary file and returning that path to unblock this issue: https://github.com/flutter/packages/pull/6438

However, as I mentioned before, I think we should re-evaluate this long term. I wrote [this doc](https://docs.google.com/document/d/12pJDtl0yubyc68UqKo2hQ7XJwv86_ixCjNemQ7ENCBQ/edit?usp=sharing) on my thoughts and welcome feedback!

**Comment by CodeDoctorDE** [comment]
Yeah i think copying isn't the big solution here.
I would be able to use the getDirectoryPath to store data like documents here to allow users to choose their favorite path to sync it for example with nextcloud.
If we want cross_file as solution, I don't really see a method to list directories and create files in there.
I think having android uri support is generally good for dart to improve the use for other plugins that rely on the file system like video/audio players

**Comment by CodeDoctorDE** [comment]
Hmm, I tested the implementation now but the getDirectoryPath future didn't complete on android
