### ISSUE TITLE
`AppBar` back button focus/hover circle should not fill up whole height

### ISSUE THREAD

**Issue by parlough** [flutter/flutter#141361]
### Steps to reproduce

1. Set up two screens with an `AppBar` and add a way to navigate to the other one
2. Run the app. (I tried macOS, CanvasKit, and skwasm)
3. Navigate to the second page
4. Hover over the automatic back button in the top app bar
5. Notice its hover circle fills up the whole height rather than have a consistent hover target

### Expected results

The circle from hovering over the back button wouldn't fill up the entire height of the app bar, nor expand when the height increases.

### Actual results

The back button hover circle fills up the entire height of the app bar, both with the default height and at increased heights. See screenshots below for reference.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: const HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Home screen'),
        elevation: 8,
        toolbarHeight: 96,
      ),
      body: Center(
        child: TextButton(
          child: const Text('Go to other screen'),
          onPressed: () {
            Navigator.push(
              context,
              MaterialPageRoute(
                builder: (BuildContext context) => const SecondScreen(),
              ),
            );
          },
        ),
      ),
    );
  }
}

class SecondScreen extends StatelessWidget {
  const SecondScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Other screen'),
        elevation: 8,
        toolbarHeight: 96,
      ),
      body: const Center(
        child: Text(
          'Other screen content',
        ),
      ),
    );
  }
}
```

</details>

### Screenshots

<details open>
<summary>Screenshots</summary>

Fill up whole height (default height):
<img width="106" alt="Example of back button expanding to default appbar height" src="https://github.com/flutter/flutter/assets/18372958/e48538ca-5f09-4232-905e-bacccb05a8c0">

Fill up whole height (expanded height):
<img width="112" alt="Example of back button expanding to full appbar height" src="https://github.com/flutter/flutter/assets/18372958/9423db8a-c62b-4976-9751-73ed3a19762b">

Expected behavior:
<img width="97" alt="Expected shape of hover circle" src="https://github.com/flutter/flutter/assets/18372958/8794ee75-8031-4be2-877c-5cc8363dc075">

</details>

### Flutter version info

<details><summary>Version</summary>

```console
Flutter 3.19.0-3.0.pre.43 • channel main • https://github.com/flutter/flutter
Framework • revision f961fdf2ba (4 hours ago) • 2024-01-10 17:37:07 -0500
Engine • revision a045134c91
Tools • Dart 3.4.0 (build 3.4.0-14.0.dev) • DevTools 2.31.0
```

</details>

**Comment by nikkivirtuoso** [comment]
it is given in app_bar.dart line 231 that in app_bar it will automatically take the back icon button if its not defined in the leading section and i think we can resolve it by fixing the height for icon widget in case of leading as it given in constraints that the leading icon can't have width more than leadingwidth and the height can't exceed toolbarheight, can anyone verify this ? please

**Comment by nikkivirtuoso** [comment]
Sir i have resolved the problem 
<img width="404" alt="Screenshot 2024-01-14 at 4 29 34 PM" src="https://github.com/flutter/flutter/assets/148634283/2343681c-08ff-45d0-ad61-f59f3ddc947e">
see

**Comment by HansMuller** [comment]
The AppBar's leading widget fills the available space (height) because it's easy to align the widget within the space, e.g. with `Center`, but it's not possible enable filling the available space if the AppBar consumes it by default.

**Comment by nikkivirtuoso** [comment]
@HansMuller what about using container or material? I have used them and it was working on the leading

**Comment by HansMuller** [comment]
@nikkivirtuoso - yes wrapping the leading widget with another widget, like Container, that absorbs the additional height is a good solution.

**Comment by nikkivirtuoso** [comment]
I have done this and created a pull request but it is failing some test cases![image](https://github.com/flutter/flutter/assets/148634283/a151a2a1-cc1e-400a-9202-30575e6ad0c8)

**Comment by nikkivirtuoso** [comment]
@HansMuller can you please help me with these errors ?

**Comment by rydmike** [comment]
@parlough I agree with you this is a bug. The default behavior should not be like this. You get the wrong size on the implicit leading back button's state layer in M3 mode, even if you do not change the size of the AppBar, and yes it grows with the size of the `AppBar`.

@HansMuller This is a Material-3 spec bug, the default icon state layer should be 40dp regardless of the size of the `AppBar`.

## AppBar Implicit Back Button State Layer Bug

The state layer of an implicit back button in a `AppBar` gets the wrong size.

### Expected result

Expect that the state layer of the implicit icon back button on the `AppBar` follow the Material 3 specification in Material-3 mode and that it thus is 40dp regardless of AppBar size.


| Default Size | Bigger Size |
| ---- | ---- |
| ![icon_state_expected](https://github.com/flutter/flutter/assets/39990307/8072252d-1cac-48a9-9faa-88e09ee038dc) | ![icon_state_big_expected](https://github.com/flutter/flutter/assets/39990307/a24864b6-f00a-406d-b3f0-5e7b6517f530) |


Material 3 specification : https://m3.material.io/components/top-app-bar/specs

The icon button state layer should be 40dp and the tap target size 48dp.

![Screenshot 2024-07-06 at 21 18 19](https://github.com/flutter/flutter/assets/39990307/35ef0717-9950-4d90-8bc6-b3322cb85d4d)


### Actual result

The state layer of size of the implicit back button gets the wrong size, it expands to fills the `AppBar` height.

| Default Size | Bigger Size |
| ---- | ---- |
| ![icon_state_actual](https://github.com/flutter/flutter/assets/39990307/1ff3f5ec-158d-4c00-ac28-fd4d79dbe57d) | ![icon_state_actual_big](https://github.com/flutter/flutter/assets/39990307/6d5ab07f-8fa1-468d-8e3c-898932929e8e) |


<details><summary>Code sample for the actual result</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(home: HomePage());
  }
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Home screen'),
        elevation: 3,
      ),
      body: Center(
        child: FilledButton(
          child: const Text('Go to other screen'),
          onPressed: () {
            Navigator.push(
              context,
              MaterialPageRoute(
                builder: (BuildContext context) => const SecondScreen(),
              ),
            );
          },
        ),
      ),
    );
  }
}

class SecondScreen extends StatelessWidget {
  const SecondScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        // toolbarHeight: 96,
        title: const Text('Other screen'),
        elevation: 3,
      ),
      body: const Center(
        child: Text(
          'Other screen content',
        ),
      ),
    );
  }
}
```
</details>


## Issue Discussion

The correctly working expected result sample was made by using `BackButtonIcon` as leading icon in an `IconButton`. It gets the correct platform adaptive icon by default too and the state layer is correct, as was shown in the expected result.

```dart
class SecondScreen extends StatelessWidget {
  const SecondScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        // Leading icon used for correct style
        leading: IconButton(
          icon: const BackButtonIcon(),
          onPressed: () async {
            await Navigator.maybePop(context);
          },
        ),
        toolbarHeight: 96,
        title: const Text('Other screen'),
        elevation: 3,
      ),
      body: const Center(
        child: Text(
          'Other screen content',
        ),
      ),
    );
  }
}
```

The above uses the same `BackButtonIcon` widget as the implicit created one does, but doing it this way, via an `IconButton` works correctly. 

If we insert the `BackButton()` widget that extends private `_ActionButton()`, so what the implicit creation uses, we do get the same issue as when using the implicit created button.

The ambient icon theme, which is correct, is not being applied to the `BackButton()` widget, for some reason that I did not dig into yet.


### Flutter Doctor

Verified the issue on latest master, which was master, 3.23.0-14.0.pre.154

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.23.0-14.0.pre.154, on macOS 14.5 23F79 darwin-arm64, locale en-US)
    • Flutter version 3.23.0-14.0.pre.154 on channel master at /Users/rydmike/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0b2a8e589e (13 hours ago), 2024-07-06 03:07:25 -0400
    • Engine revision d1ebc5fde6
    • Dart version 3.5.0 (build 3.5.0-323.0.dev)
    • DevTools version 2.37.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/rydmike/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] IntelliJ IDEA Community Edition (version 2024.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 80.0.2
    • Dart plugin version 241.17890.8

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (5 available)
    • MrPinkPro (mobile)              • 74120d6ef6769c3a2e53d61051da0147d0279996 • ios            •
      iOS 17.5.1 21F90
    • iPhone 15 Pro Max (mobile)      • 056C5315-3EA8-44FE-BC53-441A08A340F9     • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)                 • macos                                    • darwin-arm64   •
      macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                    • darwin         •
      macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                                   • web-javascript •
      Google Chrome 126.0.6478.127

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by TahaTesser** [comment]
Investigated this issue today. This is caused by the underlying  `ButtonStyleButton` Icon Button in Material 3. The Material 2 IconButton doesn't use a  button style button.

It looks like a button style button expands to fill the space. This behavior can be observed with any button based on `ButtonStyleButton`. 

### Code sample

<details>
<summary>expand to view the code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Material(
        child: Column(
          children: <Widget>[
            Expanded(
              child: FilledButton(
                onPressed: () {},
                child: const Text('B'),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

> The AppBar's leading widget fills the available space (height) because it's easy to align the widget within the space, e.g. with Center, but it's not possible enable filling the available space if the AppBar consumes it by default.

Then I looked into `NavigationToolbar` if it also does something similar, indeed the it makes the leading widget fill the whole space as Hans commented above so button `ButtonStyleButton` expands as expected. 

This might be a relic of M2 era when we could get away with leading widget filling the whole vertical space and there was no `ButtonStyleButton` back then to reproduce this bug.

<img width="549" alt="Screenshot 2024-08-28 at 17 37 09" src="https://github.com/user-attachments/assets/a1306c2b-2dec-43ac-b25e-11ec2fcb1abc">


I will look into ways to make `NavigationToolbar` leading compatible with M3 style `IconButton`.
