### ISSUE TITLE
MouseRegion.cursor applies only when mouse is moved

### ISSUE THREAD

**Issue by zhuhaichao518** [flutter/flutter#141334]
### Steps to reproduce

This bug happens at least on flutter windows, It works fine on web. Not sure about MacOs.
1. Build the following example app modified from [sample](https://api.flutter.dev/flutter/services/MouseCursor-class.html):
2. Focus on the application and move mouse to the blue region.
3. Press any key.

### Expected results

Mouse cursor changed from SystemMouseCursors.text to SystemMouseCursors.click(hand) immediately.

### Actual results

Mouse cursor changed from SystemMouseCursors.text to SystemMouseCursors.click(hand) the next time you move the cursor.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(const MouseCursorExampleApp());

class MouseCursorExampleApp extends StatelessWidget {
  const MouseCursorExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('MouseCursor Code Sample')),
        body: const MouseCursorExample(),
      ),
    );
  }
}

class MouseCursorExample extends StatefulWidget {
  const MouseCursorExample({super.key});

  @override
  _MouseCursorExampleState createState() => _MouseCursorExampleState();
}

class _MouseCursorExampleState extends State<MouseCursorExample> {
  MouseCursor _cursor = SystemMouseCursors.text;
  final FocusNode _focusNode = FocusNode();

  void _changeCursor() {
    setState(() {
      _cursor = _cursor == SystemMouseCursors.click ? SystemMouseCursors.text : SystemMouseCursors.click;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Center(
      child: RawKeyboardListener(
        focusNode: _focusNode,
        onKey: (event) {
          if (event is RawKeyDownEvent) {
            _changeCursor();
          }
        },
        child: MouseRegion(
          cursor: _cursor,
          child: Container(
            width: 200,
            height: 100,
            decoration: BoxDecoration(
              color: Colors.blue,
              border: Border.all(color: Colors.yellow),
            ),
            child: Focus(
              autofocus: true,
              child: Text('Press any key to change the cursor'),
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Hi @zhuhaichao518 
I checked this on macOS platform and see it works well. The cursor changed right after entering a key. I'm on the latest stable `3.16.6`. 

But I see there's a similar issue https://github.com/flutter/flutter/issues/76622 on Windows platform. Closing this issue as a duplicate, so please follow up on it for further updates. Thanks!
