### ISSUE TITLE
[CP] Replace deprecated `exists` in podhelper.rb

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#141382]
### Issue Link

https://github.com/flutter/flutter/issues/141167

### Target

beta

### PR Link

https://github.com/flutter/flutter/pull/141381

### Changelog Description

Building macOS projects containing plugins may fail with newer versions of Ruby

### Impacted Users

macOS developers

### Impact Description

Build fails.

### Workaround

Possibly installing an older version of Ruby; nothing straightforward

### Risk

low

### Test Coverage

no

### Validation Steps

- Have Ruby 3.2.0 or later
- Make a macOS project
- `flutter pub add path_provider`
- `flutter build macos`

(The reason I answered "no" above is that we don't have CI with this version of Ruby. We do have test coverage that my change does not regress functionality for users for whom it was not broken, and the fix is extremely straightforward, which is why the risk level is low.)

**Comment by itsjustkevin** [comment]
@jmagman @christopherfujino could you take a look at this cherry-pick?

**Comment by jmagman** [comment]
LGTM

**Comment by christopherfujino** [comment]
LGTM

**Comment by CaseyHillers** [comment]
Released in https://github.com/flutter/flutter/commits/3.19.0-0.2.pre
