### ISSUE TITLE
Xcode cache path not set correctly sometimes in recipes

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#141398]
### Type of Request

bug

### Infrastructure Environment

Recipes

### What is happening?

Devicelab has a different Xcode cache path than chromium bots.

In devicelab, the path is `/opt/flutter/xcode`. In non-devicelab, the path is `self.m.path['cache'].join(_XCODE_CACHE_PATH)`.

In a number of places in https://flutter.googlesource.com/recipes/+/refs/heads/main/recipe_modules/osx_sdk/api.py, we use the `_XCODE_CACHE_PATH` regardless of it's a devicelab bot or not. Search for `_XCODE_CACHE_PATH` and you'll find places it's used. We should fix this.

Probably best solution would be to have the path come from a function like the example below and remove `_XCODE_CACHE_PATH` to prevent confusion.

```python
def _xcode_cache_path(devicelab):
  if devicelab:
      return '/opt/flutter/xcode'
  return self.m.path['cache'].join('osx_sdk')
```

**Comment by vashworth** [comment]
cc @ricardoamador I noticed this because looks like the Cache Micro Manager uses the wrong path for devicelab

**Comment by ricardoamador** [comment]
@vashworth thanks for finding this. Will look into it.

**Comment by ricardoamador** [comment]
Hmm I see, there is some confusion with the assumptions made in the code. You are right that we are using the wrong cache path in the cache micro manager and possibly elsewhere. Code needs some cleanup and clarification in the documentation.

**Comment by ricardoamador** [comment]
Fix for this has landed and has been running without issues across mac tasks.
