### ISSUE TITLE
[url_launcher] Phone formatting

### ISSUE THREAD

**Issue by charcoast** [flutter/flutter#141393]
### What package does this bug report belong to?

url_launcher

### What target platforms are you seeing this bug on?

Android, iOS

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
  url_launcher:
    dependency: "direct main"
    description:
      name: url_launcher
      sha256: d25bb0ca00432a5e1ee40e69c36c85863addf7cc45e433769d61bed3fe81fd96
      url: "https://pub.dev"
    source: hosted
    version: "6.2.3"
```

</details>

### Steps to reproduce

1. Call phone with 10 numbers using url_launcher

### Expected results

![image](https://github.com/flutter/flutter/assets/11007668/420e30f1-225c-478c-8c07-ab6e9c0d5fe4)

### Actual results

![image](https://github.com/flutter/flutter/assets/11007668/44a24dc6-4878-4cbc-927a-f72da8752d22)

### Code sample

<details open><summary>Code sample</summary>

```dart
var phone = "tel:4836311500";
launchUrl(Uri.parse(phone));
```

</details>

### Logs

<details open><summary>Logs</summary>

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.6, on Fedora Linux 39 (Workstation Edition) 6.6.8-200.fc39.x86_64, locale pt_BR.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
    ✗ CMake is required for Linux development.
      It is likely available from your distribution (e.g.: apt install cmake), or can be downloaded from https://cmake.org/download/
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)
[✓] Android Studio (version 2023.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.3)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 category.

```

</details>

**Comment by stuartmorgan** [comment]
The plugin is just sending the URL to the system handler. Issues with how your dialer parses and displays `tel:` URLs would need to be reported to the developers of your dialer.
