### ISSUE TITLE
Camera is not working after a build for web.

### ISSUE THREAD

**Issue by engineer-ece** [flutter/flutter#141368]
### Steps to reproduce

1. flutter build web
2. While running camera in different ip address is not working. for 127.0.0.1 only is working for web.

### Expected results

1. want work for different ip address.

### Actual results

camera is not working showing as unsupported exception

### Code sample

 final cameras = await availableCameras();
        // picture = await Navigator.of(context).push(MaterialPageRoute(
        //     builder: (context) => CameraPage(cameras: cameras)));
        XFile? xFile = await Navigator.of(context).push(MaterialPageRoute(
            builder: (context) => CameraPage(cameras: cameras)));
        picture = File(xFile?.path ?? '');
      } catch (e) {
        print('Failed to capture image: $e');

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

Failed to capture image: CameraException(cameraNotSupported, The camera is not supported on this device.)```

flutter.js:371 Exception while loading service worker: Error: Service Worker API unavailable.
The current context is NOT secure.
Read more: https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts
    at FlutterServiceWorkerLoader.loadServiceWorker (flutter.js:133:11)
    at FlutterLoader.loadEntrypoint (flutter.js:369:33)
    at (index):46:23
(anonymous) @ flutter.js:371
main.dart.js:6760 Uncaught CameraException(cameraNotSupported, The camera is not supported on this device.)
    at Object.b (http://192.168.0.195:5500/main.dart.js:4710:19)
    at http://192.168.0.195:5500/main.dart.js:38494:9
    at a54.a (http://192.168.0.195:5500/main.dart.js:6021:62)
    at a54.$2 (http://192.168.0.195:5500/main.dart.js:33075:14)
    at Object.L (http://192.168.0.195:5500/main.dart.js:6007:10)
    at Nq.fB (http://192.168.0.195:5500/main.dart.js:38503:10)
    at http://192.168.0.195:5500/main.dart.js:8449:38
    at a54.a (http://192.168.0.195:5500/main.dart.js:6021:62)
    at a54.$2 (http://192.168.0.195:5500/main.dart.js:33075:14)
    at Object.L (http://192.168.0.195:5500/main.dart.js:6007:10)

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by dam-ease** [comment]
Thanks for filing this @engineer-ece. I can't seem to reproduce this on my end. 

<img width="500" alt="Screenshot 2024-01-11 at 16 58 12" src="https://github.com/flutter/flutter/assets/53122008/e6fcd5f5-33d6-4657-bf74-f75b822f2bb1">

**Steps followed**

- Build the example app in https://pub.dev/packages/camera/example by running `flutter build web`
- In IDE terminal, change directory `cd build/web`
- Then run `python3 -m http.server 8000`
- Then in a new terminal tab: run `ngrok http 8000`, see information on how to use ngrok here [www.ngrok.com](http://www.ngrok.com/).

Kindly try these out to see if the issue still persists on your end or share the steps you followed to reproduce this issue.

<details><summary>flutter doctor -v</summary>
<p>

```
[!] Flutter (Channel stable, 3.16.6, on macOS 14.2.1 23C71 darwin-arm64, locale
    en-NG)
    • Flutter version 3.16.6 on channel stable at
      /Users/damilolaalimi/sdks/flutter
    ! Warning: `dart` on your path resolves to
      /opt/homebrew/Cellar/dart/3.1.5/libexec/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/damilolaalimi/sdks/flutter.
      Consider adding /Users/damilolaalimi/sdks/flutter/bin to the front of your
      path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 46787ee49c (2 days ago), 2024-01-09 14:36:07 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[!] Android Studio (version unknown)
    • Android Studio at /Users/damilolaalimi/Downloads/Android Studio
      Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] VS Code (version 1.83.1)
    • VS Code at /Users/damilolaalimi/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        •
      android-arm64  • Android 14 (API 34) (emulator)
    • Damilola’s iPhone (mobile)  • 00008110-001964480AE1801E            • ios
      • iOS 17.1.1 21B91
    • iPhone 15 (mobile)          • F17D2919-6D61-4295-8408-1719692FE958 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)             • macos                                •
      darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)                • chrome                               •
      web-javascript • Google Chrome 120.0.6099.216

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
``` 

</p>
</details>

**Comment by engineer-ece** [comment]
it only working for localhost 127.0.0.1. not working for other ip address.

> Thanks for filing this @engineer-ece. I can't seem to reproduce this on my end.
> 
> <img alt="Screenshot 2024-01-11 at 16 58 12" width="500" src="https://private-user-images.githubusercontent.com/53122008/295977228-e6fcd5f5-33d6-4657-bf74-f75b822f2bb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMzU2MjksIm5iZiI6MTcwNTAzNTMyOSwicGF0aCI6Ii81MzEyMjAwOC8yOTU5NzcyMjgtZTZmY2Q1ZjUtMzNkNi00NjU3LWJmNzQtZjc1YjgyMmYyYmIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDA0NTUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhNzNmNWFhZTUzMjE1NDU3M2QxNDc1MWQ1NWZhMjZiNWUyYTRhY2U0ZWI1MmUxMmI5YmE4MDQzYzAzNDA4ODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xdmS7hIsnPfwoN9LMFWcxHBDMXlxF4apj4f_At_uVDw">
> **Steps followed**
> 
> * Build the example app in https://pub.dev/packages/camera/example by running `flutter build web`
> * In IDE terminal, change directory `cd build/web`
> * Then run `python3 -m http.server 8000`
> * Then in a new terminal tab: run `ngrok http 8000`, see information on how to use ngrok here [www.ngrok.com](http://www.ngrok.com/).
> 
> Kindly try these out to see if the issue still persists on your end or share the steps you followed to reproduce this issue.
> 
> flutter doctor  #-v

**Comment by dam-ease** [comment]
Thanks for the logs @engineer-ece.
Can you please share detailed steps taken to reproduce this so we can reproduce it on our end as well?
