### ISSUE TITLE
Update both `ProgressIndicator` for Material 3 redesign

### ISSUE THREAD

**Issue by parlough** [flutter/flutter#141340]
Both the circular and linear progress indicators do not fit in within a Material 3 app by default currently, particularly because of the non-rounded corners.

Luckily the Material 3 spec was updated with an overhauled version of each that is both more visually accessible and consistent with Material 3.

**Specification:** https://m3.material.io/components/progress-indicators/specs
**December 2023 updates:** https://m3.material.io/components/progress-indicators/overview#3235e516-f2e6-47f2-807d-adfe1ce6c0a2

**Comment by huycozy** [comment]
Hi @parlough 
>Both the circular and linear progress indicators do not fit in within a Material 3 app by default currently, particularly because of the non-rounded corners.

There is a known issue https://github.com/flutter/flutter/issues/109137 which proposed `StrokeCap` for CircularProgressIndicator. For LinearProgressIndicator, we can use `borderRadius`. Below is the applied result:

<img width="700" src="https://github.com/flutter/flutter/assets/104349824/50b38472-a4e4-4b72-8d26-5ffa41ed5043">


Despite that, it doesn't look like the specs for indicator and track by default as you mentioned above:

<img width="1024" alt="lqdina2g-1P-progress-indicator-anatomy" src="https://github.com/flutter/flutter/assets/104349824/1618a965-b66d-4db4-84f4-d01d1ae55dca">

**Comment by rydmike** [comment]
As a related issue https://github.com/flutter/flutter/issues/131690, the end styles cannot be themed, they can only be set on widget level. This gap should also be fixed, could be nice to add when the support for this style change is added. 

Every time widgets have props that can only be set on widget level, the usefulness of theming components is diminished.

**Comment by rydmike** [comment]
Awesome 👍 thanks @tahatesser
