### ISSUE TITLE
flutter web took more than 30 mins to build

### ISSUE THREAD

**Issue by anythingleee** [flutter/flutter#141352]
### Steps to reproduce

1. install flutter  3.13.9  on Lubuntu 22.04.3 LTS
2. create a default barebone flutter web project
3. build it with  flutter build web --web-renderer canvaskit -vv

### Actual results

```
with following error and whole process took more than 30 mins:
+961650 ms] Hint: When run on the command-line, the compiled output might require a preamble file located in:
                        <sdk>/lib/_internal/js_runtime/lib/preambles.
                      file:///home/desktoppc/flutter/packages/flutter/lib/src/widgets/widget_inspector.dart:291:11:
                      Hint: Overriding 'noSuchMethod' causes the compiler to generate more code and prevents the compiler from doing
                      some optimizations.
                      Consider removing this 'noSuchMethod' implementation.
                        dynamic noSuchMethod(Invocation invocation) {
```

### Logs

<details open>

```
+961650 ms] Hint: When run on the command-line, the compiled output might require a preamble file located in:
                        <sdk>/lib/_internal/js_runtime/lib/preambles.
                      file:///home/desktoppc/flutter/packages/flutter/lib/src/widgets/widget_inspector.dart:291:11:
                      Hint: Overriding 'noSuchMethod' causes the compiler to generate more code and prevents the compiler from doing
                      some optimizations.
                      Consider removing this 'noSuchMethod' implementation.
                        dynamic noSuchMethod(Invocation invocation) {
```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.9, on Ubuntu 22.04.3 LTS 6.2.0-39-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.84.1)

</details>

**Comment by anythingleee** [comment]
upgraded to 

`Flutter 3.16.7 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ef1af02aea (6 hours ago) • 2024-01-11 15:19:26 -0600
Engine • revision 4a585b7929
Tools • Dart 3.2.4 • DevTools 2.28.5
`

and created a new project without any additional code and the problem still there....
here is the full log executing with : flutter build web --web-renderer canvaskit -vv in lubuntu

`[  +28 ms] executing: uname -m
[   +5 ms] Exit code 0 from: uname -m
[        ] x86_64
[  +67 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +68 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +78 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +90 ms] Skipping pub get: version match.
[ +336 ms] Generating /home/hehe/workspace/testapp2/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +187 ms] generated_plugin_registrant.dart not found. Skipping.
[   +2 ms] Compiling lib/main.dart for the Web...
[  +15 ms] Initializing file store
[  +44 ms] web_entrypoint: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
/home/hehe/flutter/packages/flutter_tools/lib/src/build_system/targets/web.dart}
[   +2 ms] Skipping target: gen_localizations
[   +4 ms] web_static_assets: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
/home/hehe/flutter/bin/internal/engine.version}
[ +754 ms] web_static_assets: Complete
[ +180 ms] web_entrypoint: Complete
[   +2 ms] dart2js: Starting due to {}
[  +16 ms] executing: /home/hehe/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/hehe/flutter/bin/cache/dart-sdk/bin/snapshots/dart2js.dart.snapshot
--platform-binaries=/home/hehe/flutter/bin/cache/flutter_web_sdk/kernel --invoker=flutter_tool -Ddart.vm.product=true
-DFLUTTER_WEB_AUTO_DETECT=false -DFLUTTER_WEB_USE_SKIA=true
-DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/4a585b79294e830fa89c24924d58a27cc8fbf406/
--native-null-assertions --no-source-maps -o
/home/hehe/workspace/testapp2/.dart_tool/flutter_build/a4e8a25ce167cd269b14cc476518eb79/app.dill
--packages=.dart_tool/package_config.json --cfe-only
/home/hehe/workspace/testapp2/.dart_tool/flutter_build/a4e8a25ce167cd269b14cc476518eb79/main.dart
[+23386 ms] Compiled 37,867,962 input bytes (29,675,123 characters source) to 57,913,424 kernel bytes in 22.8 seconds using 637.500 MB
of memory
                     Dart file .dart_tool/flutter_build/a4e8a25ce167cd269b14cc476518eb79/main.dart compiled to dill:
                     .dart_tool/flutter_build/a4e8a25ce167cd269b14cc476518eb79/app.dill.
[   +1 ms] executing: /home/hehe/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/hehe/flutter/bin/cache/dart-sdk/bin/snapshots/dart2js.dart.snapshot
--platform-binaries=/home/hehe/flutter/bin/cache/flutter_web_sdk/kernel --invoker=flutter_tool -Ddart.vm.product=true
-DFLUTTER_WEB_AUTO_DETECT=false -DFLUTTER_WEB_USE_SKIA=true
-DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/4a585b79294e830fa89c24924d58a27cc8fbf406/
--native-null-assertions --no-source-maps -O4 -o
/home/hehe/workspace/testapp2/.dart_tool/flutter_build/a4e8a25ce167cd269b14cc476518eb79/main.dart.js
/home/hehe/workspace/testapp2/.dart_tool/flutter_build/a4e8a25ce167cd269b14cc476518eb79/app.dill
[+993963 ms] Hint: When run on the command-line, the compiled output might require a preamble file located in:
                        <sdk>/lib/_internal/js_runtime/lib/preambles.
                      file:///home/hehe/flutter/packages/flutter/lib/src/widgets/widget_inspector.dart:291:11:
                      Hint: Overriding 'noSuchMethod' causes the compiler to generate more code and prevents the compiler from doing
                      some optimizations.
                      Consider removing this 'noSuchMethod' implementation.
                        dynamic noSuchMethod(Invocation invocation) {
                                ^
[+4720 ms] dart2js: Complete
[+9837 ms] web_release_bundle: Starting due to {}
[+4602 ms] shaderc command: [/home/hehe/flutter/bin/cache/artifacts/engine/linux-x64/impellerc, --sksl, --iplr, --json,
--sl=build/web/assets/shaders/ink_sparkle.frag, --spirv=build/web/assets/shaders/ink_sparkle.frag.spirv,
--input=/home/hehe/flutter/packages/flutter/lib/src/material/shaders/ink_sparkle.frag, --input-type=frag,
--include=/home/hehe/flutter/packages/flutter/lib/src/material/shaders,
--include=/home/hehe/flutter/bin/cache/artifacts/engine/linux-x64/shader_lib]
[+1033 ms] Running command: /home/hehe/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/hehe/flutter/bin/cache/artifacts/engine/linux-x64/const_finder.dart.snapshot --kernel-file
/home/hehe/workspace/testapp2/.dart_tool/flutter_build/a4e8a25ce167cd269b14cc476518eb79/app.dill --class-library-uri
package:flutter/src/widgets/icon_data.dart --class-name IconData --annotation-class-name _StaticIconProvider
--annotation-class-library-uri package:flutter/src/widgets/icon_data.dart
[+5558 ms] Running font-subset: /home/hehe/flutter/bin/cache/artifacts/engine/linux-x64/font-subset
build/web/assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
/home/hehe/.pub-cache/hosted/pub.dev/cupertino_icons-1.0.6/assets/CupertinoIcons.ttf, using codepoints 62629 62419 62415 62318
optional:32
[   +1 ms] Running font-subset: /home/hehe/flutter/bin/cache/artifacts/engine/linux-x64/font-subset
build/web/assets/fonts/MaterialIcons-Regular.otf /home/hehe/flutter/bin/cache/artifacts/material_fonts/MaterialIcons-Regular.otf,
using codepoints 57415 57490 57491 57706 58332 58727 57496 57694 57695 57657 57882 57504 61453 57634 57498 57926 61061 61060 62834
62833 59283 59282 57499 57500 61069 61068 62842 62841 59291 59290 58011 58012 61575 61576 63348 63349 59797 59798 58372 58370 61930
61927 63708 63705 60157 60154 58771 58189 62328 61752 983402 63526 60555 59975 57704 57502 58814 58813 57846 57862 57686 61764 57402
optional:32
[ +776 ms] Font asset "CupertinoIcons.ttf" was tree-shaken, reducing it from 283452 to 1272 bytes (99.6% reduction). Tree-shaking can
be disabled
                    by providing the --no-tree-shake-icons flag when building your app.
[   +2 ms] Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 7652 bytes (99.5% reduction).
Tree-shaking can be
           disabled by providing the --no-tree-shake-icons flag when building your app.
[ +193 ms] web_release_bundle: Complete
[+4382 ms] web_service_worker: Starting due to {}
[+1825 ms] web_service_worker: Complete
[ +330 ms] Persisting file store
[  +65 ms] Done persisting file store
[ +160 ms] Compiling lib/main.dart for the Web... (completed in 1051.8s)
[  +51 ms] "flutter web" took 1,052,707ms.
[ +301 ms] ensureAnalyticsSent: 283ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[   +4 ms] exiting with code 0
`

**Comment by darshankawar** [comment]
Thanks for the update. In your above comment, I don't see the time being taken to build is more than 30 mins, but assuming the issue you are concerned with is below:

```
[+14908 ms] Hint: When run on the command-line, the compiled output might
require a preamble file located in:
                       <sdk>/lib/_internal/js_runtime/lib/preambles.
                     ../../../documents/fluttersdk/flutter/packages/flutter/lib/
                     src/widgets/widget_inspector.dart:291:11:
                     Hint: Overriding 'noSuchMethod' causes the compiler to
                     generate more code and prevents the compiler from doing
                     some optimizations.
                     Consider removing this 'noSuchMethod' implementation.
                       dynamic noSuchMethod(Invocation invocation) {
```

I tried on latest master and stable running on mac and observed same log.  Is this a correct interpretation of the case that you are reporting above log while running the said command and not the time the tool is taking to build ? Because I also didn't observe the build taking more than a minute.

Also, the default renderer for desktop browser is canvaskit itself, so probably you don't need to explicitly specify `--web-renderer canvaskit`.

**Comment by anythingleee** [comment]
There are 2 questions : 
Q1: Since you are having the same issue except that your build completed within mins, what exactly the warning means? what do "Consider removing this 'noSuchMethod' implementation." and "the compiler to generate more code and prevents the compiler from doing some optimizations" mean ? Should I do anything about it?

`[+14908 ms] Hint: When run on the command-line, the compiled output might
require a preamble file located in:
                       <sdk>/lib/_internal/js_runtime/lib/preambles.
                     ../../../documents/fluttersdk/flutter/packages/flutter/lib/
                     src/widgets/widget_inspector.dart:291:11:
                     Hint: Overriding 'noSuchMethod' causes the compiler to
                     generate more code and prevents the compiler from doing
                     some optimizations.
                     Consider removing this 'noSuchMethod' implementation.
                       dynamic noSuchMethod(Invocation invocation) {`



Q2: the following is the first run using this command : flutter build web -vv and it really took more than 30mins to build. What do you think is the cause? Is it my computer?

[ +199 ms] executing: uname -m
[  +15 ms] Exit code 0 from: uname -m
[   +1 ms] x86_64
[ +519 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[ +171 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[+1074 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +36 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[ +222 ms] Skipping pub get: version match.
[+1870 ms] Generating /home/hehe/workspace/testapp2/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +274 ms] generated_plugin_registrant.dart not found. Skipping.
[  +23 ms] Compiling lib/main.dart for the Web...
[  +33 ms] Initializing file store
[ +111 ms] web_entrypoint: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
/home/hehe/flutter/packages/flutter_tools/lib/src/build_system/targets/web.dart}
[   +5 ms] Skipping target: gen_localizations
[   +8 ms] web_static_assets: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
/home/hehe/flutter/bin/internal/engine.version}
[ +983 ms] web_static_assets: Complete
[ +275 ms] web_entrypoint: Complete
[   +3 ms] dart2js: Starting due to {}
[  +25 ms] executing: /home/hehe/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/hehe/flutter/bin/cache/dart-sdk/bin/snapshots/dart2js.dart.snapshot
--platform-binaries=/home/hehe/flutter/bin/cache/flutter_web_sdk/kernel --invoker=flutter_tool -Ddart.vm.product=true
-DFLUTTER_WEB_AUTO_DETECT=true
-DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/4a585b79294e830fa89c24924d58a27cc8fbf406/
--native-null-assertions --no-source-maps -o
/home/hehe/workspace/testapp2/.dart_tool/flutter_build/dccdc2b12675b5c9fafed0797ad8a52d/app.dill
--packages=.dart_tool/package_config.json --cfe-only
/home/hehe/workspace/testapp2/.dart_tool/flutter_build/dccdc2b12675b5c9fafed0797ad8a52d/main.dart
[+977518 ms] executing: /home/hehe/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/hehe/flutter/bin/cache/dart-sdk/bin/snapshots/dart2js.dart.snapshot
--platform-binaries=/home/hehe/flutter/bin/cache/flutter_web_sdk/kernel --invoker=flutter_tool -Ddart.vm.product=true
-DFLUTTER_WEB_AUTO_DETECT=true
-DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/4a585b79294e830fa89c24924d58a27cc8fbf406/
--native-null-assertions --no-source-maps -O4 -o
/home/hehe/workspace/testapp2/.dart_tool/flutter_build/dccdc2b12675b5c9fafed0797ad8a52d/main.dart.js
/home/hehe/workspace/testapp2/.dart_tool/flutter_build/dccdc2b12675b5c9fafed0797ad8a52d/app.dill
[+970817 ms] Hint: When run on the command-line, the compiled output might require a preamble file located in:
                        <sdk>/lib/_internal/js_runtime/lib/preambles.
                      file:///home/hehe/flutter/packages/flutter/lib/src/widgets/widget_inspector.dart:291:11:
                      Hint: Overriding 'noSuchMethod' causes the compiler to generate more code and prevents the compiler from doing
                      some optimizations.
                      Consider removing this 'noSuchMethod' implementation.
                        dynamic noSuchMethod(Invocation invocation) {
                                ^
[ +132 ms] dart2js: Complete
[+4279 ms] web_release_bundle: Starting due to {}
[+2792 ms] shaderc command: [/home/hehe/flutter/bin/cache/artifacts/engine/linux-x64/impellerc, --sksl, --iplr, --json,
--sl=build/web/assets/shaders/ink_sparkle.frag, --spirv=build/web/assets/shaders/ink_sparkle.frag.spirv,
--input=/home/hehe/flutter/packages/flutter/lib/src/material/shaders/ink_sparkle.frag, --input-type=frag,
--include=/home/hehe/flutter/packages/flutter/lib/src/material/shaders,
--include=/home/hehe/flutter/bin/cache/artifacts/engine/linux-x64/shader_lib]
[ +185 ms] Running command: /home/hehe/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/hehe/flutter/bin/cache/artifacts/engine/linux-x64/const_finder.dart.snapshot --kernel-file
/home/hehe/workspace/testapp2/.dart_tool/flutter_build/dccdc2b12675b5c9fafed0797ad8a52d/app.dill --class-library-uri
package:flutter/src/widgets/icon_data.dart --class-name IconData --annotation-class-name _StaticIconProvider
--annotation-class-library-uri package:flutter/src/widgets/icon_data.dart
[+3571 ms] Running font-subset: /home/hehe/flutter/bin/cache/artifacts/engine/linux-x64/font-subset
build/web/assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
/home/hehe/.pub-cache/hosted/pub.dev/cupertino_icons-1.0.6/assets/CupertinoIcons.ttf, using codepoints 62629 62419 62415 62318
optional:32
[   +1 ms] Running font-subset: /home/hehe/flutter/bin/cache/artifacts/engine/linux-x64/font-subset
build/web/assets/fonts/MaterialIcons-Regular.otf /home/hehe/flutter/bin/cache/artifacts/material_fonts/MaterialIcons-Regular.otf,
using codepoints 57415 57490 57491 57706 58332 58727 57496 57694 57695 57657 57882 57504 61453 57634 57498 57926 61061 61060 62834
62833 59283 59282 57499 57500 61069 61068 62842 62841 59291 59290 58011 58012 61575 61576 63348 63349 59797 59798 58372 58370 61930
61927 63708 63705 60157 60154 58771 58189 62328 61752 983402 63526 60555 59975 57704 57502 58814 58813 57846 57862 57686 61764 57402
optional:32
[ +179 ms] Font asset "CupertinoIcons.ttf" was tree-shaken, reducing it from 283452 to 1272 bytes (99.6% reduction). Tree-shaking can
be disabled
                    by providing the --no-tree-shake-icons flag when building your app.
[   +6 ms] Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 7652 bytes (99.5% reduction).
Tree-shaking can be
           disabled by providing the --no-tree-shake-icons flag when building your app.
[  +63 ms] web_release_bundle: Complete
[ +551 ms] web_service_worker: Starting due to {}
[ +703 ms] web_service_worker: Complete
[ +205 ms] Persisting file store
[  +11 ms] Done persisting file store
[  +94 ms] Compiling lib/main.dart for the Web... (completed in 1962.5s)
[   +4 ms] "flutter web" took 1,966,341ms.
[ +255 ms] ensureAnalyticsSent: 251ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0

**Comment by darshankawar** [comment]
Thanks for the update. My colleague tried the scenario on his Linux machine using latest stable version on which the build completed quickly and also didn't get the `Hint` warnings:

[vv.txt](https://github.com/flutter/flutter/files/13935351/vv.txt)


`Channel stable, 3.16.7, on Ubuntu 22.04.3 LTS 6.2.0-39-generic` 



> what do "Consider removing this 'noSuchMethod' implementation." and "the compiler to generate more code and prevents the compiler from doing some optimizations" mean ? Should I do anything about it?

I have seen this warning in an already logged issue but don't think we need to do anything about it. If at all, the fix need to be made in the sdk itself. 



> What do you think is the cause? Is it my computer?

Since it is not replicable and only occuring at your end, can you check if you have stable and fast internet connection ?
