### ISSUE TITLE
dart sdk error

### ISSUE THREAD

**Issue by marycanonce** [flutter/flutter#141357]
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart
dart-sdk/lib/async/zone.dart
dart-sdk/lib/async/future_impl.dart

it errors hen I ADD new image in flutter, but the thing is 1 and a half hour later the image works perfectly, the thing is, when we are coding in flutter and and its involves images it didn't responding well but showing errors like: 

Unable to load asset: "assets/images.jpg".
The asset does not exist or has empty data.

did i do somthing wrong?help

**Comment by dam-ease** [comment]
Hello @marycanonce. 
Can you please provide more information on this for us to triage this properly i.e a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production codes and the content of your `pubspec.yaml` file
