### ISSUE TITLE
"Unable to get list of installed Simulator runtimes" in flutter doctor doesn't give specifics of how to resolve the issue

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#141358]
When I run `flutter doctor` on this more or less stock mac, I get:

```
[!] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    ✗ Unable to get list of installed Simulator runtimes.
    • CocoaPods version 1.14.3
```

...but the message doesn't explain what I'm supposed to do about it.

**Comment by darshankawar** [comment]
Hello @Hixie, I think you are hitting https://github.com/flutter/flutter/issues/139496 that you can check which also talks about improving that error message and indicate what needs to be done.

**Comment by Hixie** [comment]
Agreed.
