### ISSUE TITLE
Move android-specific capabilities into their own package

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1413]
To help developers understand what works where, should we create a package just for android-specific services (and maybe something similar for ios-specific services). ? Importing something like package:flutter_android/flutter_android.dart makes this very obvious, plus also helps with doc organization.

For example, specifically the `activity` field from the services library.

Thanks!

**Comment by abarth** [comment]
Fixed.  We don't have any android-specific capabilities now.
