### ISSUE TITLE
Misleading Documentation

### ISSUE THREAD

**Issue by ElNgatia** [flutter/flutter#141324]
### Steps to reproduce

Follow the documentation to set up flutter on Windows OS.

### Actual results

The documentation suggests Flutter to be intalled in 'C:\dev', which contradicts the conditions provided of where not to install Flutter. This will mislead beginners and give them a hard time setting up Flutter.

**Comment by darshankawar** [comment]
Thanks for the report @ElNgatia 
I can't seem to open the docs.flutter.dev site for some reason, so can't check the documentation you highlighted. 

> which contradicts the conditions provided of where not to install Flutter.

Can you provide the condition ?

**Comment by ElNgatia** [comment]
> When the Select Folder for Flutter SDK dialog displays, choose where you want to install Flutter.

> VS Code places you in your user profile to start. Choose a different location.

> Consider %USERPROFILE% or C:\dev.

 > Warning: 

> Don’t install Flutter to a directory or path that meets one or both of the following conditions:

> The path contains special characters or spaces.
> The path requires elevated privileges.
> As an example, C:\Program Files\ fails both conditions.

![Screenshot from 2024-01-08 14-03-02](https://github.com/flutter/flutter/assets/72346625/4b040f8f-7193-4c6d-85d7-26b6943e4c64)

Here's the preview. I think the example path should be changed to something else like ~Downloads/dev.

**Comment by cedvdb** [comment]
Does `C:\Dev` requires elevated privileges ? If not, it's not contradictory.

**Comment by ElNgatia** [comment]
C:\Dev requires elevated privileges.

**Comment by OmmAshutosh** [comment]
try this then i have followed this process to install flutter
Step 2: Set up Flutter Environment Variables
- Open your terminal (Command Prompt on Windows, Terminal on macOS/Linux).
- Run the command flutter doctor to see if Flutter is properly installed.
- If any components are missing, the flutter doctor command will guide you through installing them.
- Add the Flutter SDK path to your system's environment variables.
  - For Windows:
    - From the Start menu, search and choose "Edit the system environment variables".
    - Click on "Environment Variables" button.
    - Under "System Variables", select "Path" and click on "Edit".
    - Add the full path to the Flutter SDK bin folder to the list of paths.
    - Click "OK" to save the changes.
  - For macOS/Linux:
    - Open a terminal and run the command open ~/.bash_profile (or open ~/.zshrc if you use Zsh).
    - This will open the file in a text editor.
    - Add the following line at the end of the file: export PATH="$PATH:/path/to/flutter/bin"
    - Save and close the file, then run the command source ~/.bash_profile (or source ~/.zshrc) to update the environment variables.

**Comment by ElNgatia** [comment]
Setting up the SDK path as a system variable will work but that's quite different from what is in the documentation as it claims that the SDK path be set up in the User variables and not system. It may be easy to work around it as an experienced developer but a beginner may have difficulties installing it.

![Screenshot from 2024-01-11 14-54-24](https://github.com/flutter/flutter/assets/72346625/28066e24-e981-4337-a9c3-c493d4cbf7b4)

**Comment by darshankawar** [comment]
I think this belongs to website repo since the instructions are coming from website, so any issues related to it need to be reported in dedicated [repo](https://github.com/flutter/website/issues/new?template=1_page_issue.yml&title=[PAGE%20ISSUE]:%20%27Start%20building%20Flutter%20Android%20apps%20on%20Windows%27&page-url=https://docs.flutter.dev/get-started/install/windows/mobile/&page-source=https://github.com/flutter/website/tree/main/src/get-started/install/windows/mobile.md): 

Closing from here.
