### ISSUE TITLE
Encountered issues with flutter doctor.

### ISSUE THREAD

**Issue by naxiemolv** [flutter/flutter#141442]
### Steps to reproduce

When I plug in a potentially non-standard adb device (modified adb), flutter doctor crashes and shows an error.

### Expected results

List of devices attached
20080411	device

### Actual results

crashed

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

```
[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us
      know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Invalid UTF-8 byte (at offset 69)
    • #0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1852:7)
      #1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:304:28)
      #2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:300:5)
      #3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:69:18)
      #4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
      #5      _rootRunUnary (dart:async/zone.dart:1407:47)
      #6      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
      #7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
      #8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
      #9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
      #10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
      #11     _StreamController._add (dart:async/stream_controller.dart:658:7)
      #12     _StreamController.add (dart:async/stream_controller.dart:606:5)
      #13     _Socket._onData (dart:io-patch/socket_patch.dart:2447:41)
      #14     _rootRunUnary (dart:async/zone.dart:1415:13)
      #15     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
      #16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
      #17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
      #18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
      #19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
      #20     _StreamController._add (dart:async/stream_controller.dart:658:7)
      #21     _StreamController.add (dart:async/stream_controller.dart:606:5)
      #22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1936:33)
      #23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1379:14)
      #24     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
      #25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
      #26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
      #27     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```

**Comment by naxiemolv** [comment]
[✓] Flutter (Channel stable, 3.16.7, on macOS 14.2 23C64 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.16.7 on channel stable at /Users/liyuyang/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ef1af02aea (12 小时前), 2024-01-11 15:19:26 -0600
    • Engine revision 4a585b7929
    • Dart version 3.2.4
    • DevTools version 2.28.5
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/liyuyang/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = /Users/liyuyang/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 77.1.3
    • Dart plugin version 232.10286

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us
      know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Invalid UTF-8 byte (at offset 69)
    • #0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1852:7)
      #1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:304:28)
      #2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:300:5)
      #3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:69:18)
      #4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
      #5      _rootRunUnary (dart:async/zone.dart:1407:47)
      #6      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
      #7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
      #8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
      #9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
      #10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
      #11     _StreamController._add (dart:async/stream_controller.dart:658:7)
      #12     _StreamController.add (dart:async/stream_controller.dart:606:5)
      #13     _Socket._onData (dart:io-patch/socket_patch.dart:2447:41)
      #14     _rootRunUnary (dart:async/zone.dart:1415:13)
      #15     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
      #16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
      #17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
      #18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
      #19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
      #20     _StreamController._add (dart:async/stream_controller.dart:658:7)
      #21     _StreamController.add (dart:async/stream_controller.dart:606:5)
      #22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1936:33)
      #23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1379:14)
      #24     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
      #25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
      #26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
      #27     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)


[✓] Network resources
    • All expected network resources are available.

**Comment by dam-ease** [comment]
> When I plug in a potentially non-standard adb device (modified adb), flutter doctor crashes and shows an error.

Can you provide more information on this?
