### ISSUE TITLE
User should be able to add custom services to their Flutter-iOS project

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1414]
This might require some custom build steps that the developer needs to do, to integrate a custom service (such as Firebase) to their iOS engine/binary.

Ideally, this is a one-time step. Once completed, the developer can iterate quickly as normal.

**Comment by eseidelGoogle** [comment]
My understanding from last speaking with @mpcomplete was that he planned to own this with help from @chinmaygarde

**Comment by collinjackson** [comment]
I think this bug may be ready to be closed, please confirm.

**Comment by mpcomplete** [comment]
Still working on it, unless @chinmaygarde has performed a miracle.

**Comment by chinmaygarde** [comment]
I think we are close though. I will pair with @mpcomplete and help if possible today.

**Comment by chinmaygarde** [comment]
This can be closed after flutter/engine#2394 and #1835 and there is a roll
