### ISSUE TITLE
put mac-10 mobile device into airplane mode

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#141459]
### Type of Request

infra task

### Infrastructure Environment

devicelab

### What is happening?

per https://github.com/flutter/flutter/issues/141383#issuecomment-1889566040 , please put the iphone connected to mac-10 into airplane mode.

### Steps to reproduce

Step 1:
Step 2:
..
Step n:

### Expected results

I expect to see X when Y is finished.

**Comment by kentnguyen99** [comment]
Done.
