### ISSUE TITLE
Can you help me to remove ticket information

### ISSUE THREAD

**Issue by followthemoney1** [flutter/flutter#141491]
### Steps to reproduce

Hello, can you please remove ticket or all information inside ticket: https://github.com/flutter/flutter/issues/131867#issue-1835446901
Which I posted earlier, as it contains potentially sensitive information that I did not have approval to post

### Actual results

Hello, can you please remove ticket or all information inside ticket: https://github.com/flutter/flutter/issues/131867#issue-1835446901
Which I posted earlier, as it contains potentially sensitive information that I did not have approval to post

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by followthemoney1** [comment]
@huycozy cc

**Comment by followthemoney1** [comment]
I can't remove any data from it
<img width="1037" alt="image" src="https://github.com/flutter/flutter/assets/8526612/942cee8f-4f03-43a9-be1c-8448629eb9a9">

**Comment by bartekpacia** [comment]
Resolved.
