### ISSUE TITLE
`flutter_news_template` does not build for iOS on template 1.0.8 

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#141462]
```
$ mason add -g flutter_news_template 1.0.8
$ mason make flutter_news_template
...
```
In new project build the app for iOS and see it error:
```
$ flutter build ios -t lib/main/main_production.dart --flavor production
...
    [!] CocoaPods could not find compatible versions for pod "Google-Mobile-Ads-SDK":
      In snapshot (Podfile.lock):
        Google-Mobile-Ads-SDK (= 10.9.0, ~> 10.9.0)

      In Podfile:
        google_mobile_ads (from `.symlinks/plugins/google_mobile_ads/ios`) was resolved to 1.0.0, which depends on
          Google-Mobile-Ads-SDK (~> 10.11.0)
```
The `google_mobile_ads` version was bumped to 4.0 in https://github.com/flutter/news_toolkit/commit/445a7a4729fc6ef2890563da824ad7086012aa16 

That version of `google_mobile_ads` requires `'Google-Mobile-Ads-SDK','~> 10.11.0'`
https://github.com/googleads/googleads-mobile-flutter/blob/1801bea96133f47d6e4f3467a67a262466f09e6a/packages/google_mobile_ads/ios/google_mobile_ads.podspec#L18
```ruby
  s.dependency 'Google-Mobile-Ads-SDK','~> 10.11.0'
```

However the news template `Podfile.lock` is set to `10.9.0`.
https://github.com/flutter/news_toolkit/blob/3e80ca8b8c87c0098b61eb42a746223d9e7a52f4/flutter_news_example/ios/Podfile.lock#L136

1. `Podfile.lock` does not need to be part of the template
2. dependabot should not be bumping this version without a test that builds (and ideally tests?) the iOS app to validate the dependency change does not break the template.

cc @valentinallavayol  @zoeyfan

**Comment by valentinallavayol** [comment]
@jmagman If you delete the `Podfile.lock` and re run `pod install` pods get installed succesfully. I agree that removing the `Podfile.lock` from the ios folder is a good solution to avoid this probolems.

**Comment by valentinallavayol** [comment]
@jmagman Actually, I did some research because I got curious on best practices regarding this, and found the following on the Cocoapods documentation: https://guides.cocoapods.org/using/using-cocoapods.html#should-i-ignore-the-pods-directory-in-source-control

_"Whether or not you check in the Pods directory, the Podfile and Podfile.lock should always be kept under version control."_

Taking that into account, I guess removing it should not be the best way to work this out, rather than always committing the changes made on the Podfile.lock so we don't find ourselves into this scenario anymore.

**Comment by jmagman** [comment]
> Taking that into account, I guess removing it should not be the best way to work this out, rather than always committing the changes made on the Podfile.lock so we don't find ourselves into this scenario anymore.

I think it makes sense for the developer to commit their `Podfile.lock` once it's generated.  But I don't think the newly created app template should pre-generate.  The Flutter tool itself doesn't generate a `Podfile.lock` on `flutter create` for the same reason.  `Podfile.lock` is not in in the generated `.gitignore` in order to encourage developers to check it in.

If you want the news template to generate it then you'll need to add tooling in CI to at a minimum build, if not test, the app on iOS.  However I don't think it buys you anything to keep it around.

**Comment by matiasleyba** [comment]
@jmagman We will mark this as resolved since we have removed the `Podfile.lock` from the template in the new version [1.0.9](https://brickhub.dev/bricks/flutter_news_template#changelog).
