### ISSUE TITLE
[Edit] New impeller sharded tests are failing on monorepo

### ISSUE THREAD

**Issue by whesse** [flutter/flutter#141446]
[EDIT: The PR listed here is not the cause, a new subshard of framework_tests ("impeller") included failing tests, and is in the bringup state. Monorepo doesn't know about the bringup state, and was running all shards. PR with the new subshard is https://github.com/flutter/flutter/pull/141341]

The  GLES impeller tests enabled by https://github.com/flutter/engine/pull/49701 are failing on the monorepo builder running framework tests.

This PR is causing many failures on monorepo, and is causing the framework tests time to go from less than 60 minutes to over 90 minutes, and causing builds to time out.

The first failing build is https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/flutter-linux-framework-tests/1879/overview

The common cause of the failures is:
```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following _Exception was thrown running a test:
Exception: Asset 'shaders/ink_sparkle.frag' does not contain appropriate runtime stage data for
current backend (Vulkan).
Found stages: SkSL

When the exception was thrown, this was the stack:
#0      new FragmentProgram._fromAsset (dart:ui/painting.dart:4446:7)
#1      FragmentProgram.fromAsset.<anonymous closure> (dart:ui/painting.dart:4473:55)
```
Are there additional build targets or artifacts that are needed to run these tests, or should they be disabled on these builders and are accidentally being run?

Are these tests expected to add this much additional runtime to the framework tests?

@bdero @whesse

**Comment by whesse** [comment]
This is currently breaking our monorepo builds, which makes it impossible for us to find SDK changes that will break Flutter engine or framework early, before they are rolled into engine.

**Comment by whesse** [comment]
The likely cause of these failures is that some vulcan impeller artifacts are not being built and uploaded by the monorepo linux-host-debug builder. I need some help knowing what these are, and what targets to build to get them.

I see that the engine CI linux-host-engine config (https://github.com/flutter/engine/blob/main/ci/builders/linux_host_engine.json) has a host_debug_impeller_vulcan builder that monorepo does not have, but that builder does not upload any artifacts. So that builder doesn't seem to be the cause of the problem.

We need to converge the monorepo CI and engine CI configuration files, so both of them build and upload the same artifacts, but hopefully we can find and fix this problem before tackling that big task.

The monorepo linux-host config is at https://dart.googlesource.com/monorepo/+/refs/heads/main/ci/builders/host_linux.json
and lists all the build targets and artifact uploads of the monorepo builders, so the missing impeller artifacts would be something missing from there.

The breaking tests are being run in a checkout of Flutter framework, which fetches the engine artifacts built by the monorepo builders by using a custom FLUTTER_STORAGE_BASE_URL and engine.version.  So the artifacts are missing from that storage location.

Are these part of sky_engine.zip? That is uploaded by an android builder, not the linux_host builder.

The key may be to find which artifact is supposed to contain the missing 
 Asset 'shaders/ink_sparkle.frag'
 for vulcan, and what target is supposed to build this. I have no context to figure this out, so could use some help.

**Comment by whesse** [comment]
The problem was completely different: A new framework tests subshard was added in bringup mode, that included failing tests.

Monorepo will be fixed to run the subshards separately, and skip the new impeller shard while it is failing.
Shard is added in https://github.com/flutter/flutter/pull/141341

The title and description of the issue are changed to reflect this new information.

**Comment by jonahwilliams** [comment]
@whesse I'm assigning this to you based on my understanding that you are fixing it, but if you need help/want me to disable the tests I'm happy to take over.

**Comment by whesse** [comment]
This issue can be closed - the impeller subshard is now not running on monorepo while it is being brought up on Flutter CI.
