### ISSUE TITLE
appbar RTL bug

### ISSUE THREAD

**Issue by sajjadintel** [flutter/flutter#141478]
I'm using `appbar` and I've added an Icon button in the leading.
by make the app RTL this button stays on the left and won't come right.

**Comment by darshankawar** [comment]
@sajjadintel 
You need to use `Directionality` widget for the entire app itself as shown below, with which it works as expected:

```
import 'package:flutter/material.dart';

/// Flutter code sample for [AppBar].

void main() => runApp(const AppBarApp());

class AppBarApp extends StatelessWidget {
  const AppBarApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Directionality(
        textDirection: TextDirection.rtl,
        child: Scaffold(
          body: AppBar(
            leading: IconButton(
              icon: Icon(Icons.ac_unit),
              onPressed: () {
                print('icon tapped');
              },
            ),
          ),
        ),
      ),
    );
  }
}
```

<img width="298" alt="Screenshot 2024-01-15 at 1 26 01 PM" src="https://github.com/flutter/flutter/assets/67046386/18f86831-75db-40cb-8a98-2c0b88c69dca">

Closing as resolved. If you disagree, write in comments and I'll reopen it.
