### ISSUE TITLE
Build dashboard shows task stuck as "In Progress"

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#141404]
### Type of Request

bug

### Infrastructure Environment

Cocoon

### What is happening?

https://ci.chromium.org/ui/p/dart-internal/builders/flutter/Linux%20engine_release_builder/796/overview is marked as success by LUCI, but the build dashboard shows it stuck as "In Progress" for the past hour.

![image](https://github.com/flutter/flutter/assets/2148558/fe38daa5-157f-4619-aae5-a130ea08f7c2)

### Steps to reproduce

N/A

### Expected results

I expect the LUCI result to have been propagated to the build dashboard within a few minutes

**Comment by keyonghan** [comment]
Dup of https://github.com/flutter/flutter/issues/141405
