### ISSUE TITLE
Run packages `check_podspecs` build on Mac arm bot

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#141493]
https://github.com/flutter/packages/pull/5873 updates google_maps_flutter to build against arm simulators.  Update `check_podspecs` to run on `Mac_arm64` bots.
```yaml
  ### iOS+macOS tasks ###
  # TODO(stuartmorgan): Move this to ARM once google_maps_flutter has ARM
  # support. `pod lint` makes a synthetic target that doesn't respect the
  # pod's arch exclusions, so fails to build.
  - name: Mac_x64 check_podspecs
```
https://github.com/flutter/packages/blob/14b94ff834c06dbf9220e0066657806c6c7d552c/.ci.yaml#L1064-L1067

@stuartmorgan not sure if you had an open issue for this.

**Comment by stuartmorgan** [comment]
Not that I am finding; thanks for following up on this!

**Comment by jmagman** [comment]
`google_maps_flutter` still doesn't build against ARM simulators with the default version CocoaPods uses during lint.  Reopening.
https://github.com/flutter/flutter/issues/94491#issuecomment-1895035957
