### ISSUE TITLE
[Impeller] vkDestroyPipeline gets called too early sometimes on Vulkan

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#141490]
Error looks like this:

```
E/flutter (21891): [ERROR:flutter/impeller/base/validation.cc(49)] Break on 'ImpellerValidationBreak' to inspect point of failure: 
E/flutter (21891): --- Vulkan Debug Report  ----------------------------------------
E/flutter (21891): |                Severity: Error
E/flutter (21891): |                    Type: { Validation }
E/flutter (21891): |                 ID Name: VUID-vkDestroyPipeline-pipeline-00765
E/flutter (21891): |               ID Number: 1809638909
E/flutter (21891): |       Queue Breadcrumbs: [NONE]
E/flutter (21891): |  CMD Buffer Breadcrumbs: [NONE]
E/flutter (21891): |         Related Objects: Device [12970367433631101008] [ImpellerDevice]
E/flutter (21891): |                 Trigger: Validation Error: [ VUID-vkDestroyPipeline-pipeline-00765 ] Object 0: handle = 0xb4000075ffe07050, name = ImpellerDevice, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bdce5fd | Cannot call vkDestroyPipeline on VkPipeline 0x1500000000150[Pipeline Runtime Stage] that is currently in use by a command buffer. The Vulkan spec states: All submitted commands that refer to pipeline must have completed execution (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkDestroyPipeline-pipeline-00765)
E/flutter (21891): -----------------------------------------------------------------
```

It doesn't seem to negatively impact rendering. I can trigger it pretty easily with https://github.com/dnfield/flutter_shader_demo - run the app with `--enable-impeller` (and make sure Vulkan gets used), then tap back and forth on the `galaxy` demo.

Adding the pipeline to the resource tracker would probably help this.

**Comment by dnfield** [comment]
This happens because the application is suboptimally reloading the fragment programs from disk when transitioning from page to page.

The current pattern looks like this:

```dart
// Preview
return Button(
  child: ShaderWidget('galaxy.frag', width: 200, height: 200),
  onPressed: () => navigateToFullScreen(),
);

// Full screen
return ShaderWidget('galaxy.frag');
```

The better pattern would be 

```dart
final FragmentShader galaxy = await loadShader('galaxy.frag');

// Preview
return Button(
  child: ShaderWidget(galaxy, width: 200, height: 200),
  onPressed: () => navigateToFullScreen(),
);

// Full screen
return ShaderWidget(galaxy);
```

What's happening is the cache gets cleared during navigation and the validation error trips.

**Comment by jonahwilliams** [comment]
We've worked around this so I'm dropping the priority for now.

**Comment by chinmaygarde** [comment]
I am not sure how else to fix this other than to hold a strong reference to each pipeline in `impeller::TrackedObjectsVK`. We, presumably, don't want to do that because that will increase refcount churn on the shared pointers. Since we have already worked around this (effectively making in caller responsibility to keep these alive long enough), should we close this as completed?

**Comment by jonahwilliams** [comment]
I think I would consider this completed. Closing
