### ISSUE TITLE
Engine doesn't build on Rodete

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#14140]
With an in-place-upgraded Goobuntu-to-Rodete machine, I was unable to get an android engine to compile because the compilation environment is either missing some standard C++ headers, or because  the compile line is missing an appropriate include path.  I get numerous errors like this one:

```
FAILED: clang_x86/obj/third_party/dart/runtime/bin/gen_snapshot_dart_io/namespace_android.o 
/usr/local/google/home/gspencer/code/goma/gomacc ../../buildtools/linux-x64/clang/bin/clang++ -MMD -MF clang_x86/obj/third_party/dart/runtime/bin/gen_snapshot_dart_io/namespace_android.o.d -DDART_IO_SECURE_SOCKET_DISABLED -DUSE_OPENSSL=1 -DTOOLCHAIN_VERSION=4e89c701396412a50a901115ab4a2a09145f3777 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DTARGET_ARCH_ARM -DNDEBUG -DTARGET_OS_ANDROID -DDART_PRECOMPILER -DPRODUCT -I../../third_party/dart/runtime -I../../third_party -I../.. -Iclang_x86/gen -I../../third_party/zlib -fno-strict-aliasing -fstack-protector --param=ssp-buffer-size=4 -m32 -momit-leaf-frame-pointer -mstack-alignment=16 -mstackrealign -fPIC -pipe -pthread -fcolor-diagnostics -Wall -Wextra -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wthread-safety -O2 -fno-ident -fdata-sections -ffunction-sections -g0 -Werror -Wall -Wextra -Wno-unused-parameter -Wnon-virtual-dtor -Wvla -Wno-conversion-null -Woverloaded-virtual -g3 -ggdb3 -fno-rtti -fno-exceptions -O3 -fvisibility-inlines-hidden -std=c++11 -fno-rtti -fno-exceptions -c ../../third_party/dart/runtime/bin/namespace_android.cc -o clang_x86/obj/third_party/dart/runtime/bin/gen_snapshot_dart_io/namespace_android.o
In file included from ../../third_party/dart/runtime/bin/namespace_android.cc:5:
In file included from ../../third_party/dart/runtime/platform/globals.h:79:
../../third_party/dart/runtime/platform/math.h:12:10: fatal error: 'cmath' file not found
#include <cmath>
         ^~~~~~~
1 error generated.
```

Another header that is not found is "`<limits>`".

Fixing the android and regular build deps scripts to understand Rodete (as [I mentioned](https://github.com/flutter/flutter/issues/13460#issuecomment-358162660) in #13460 ), still doesn't fix the problem.  The `host_debug_unopt` target builds correctly.

I suspect that this is a mismatch in the libcc for Rodete.

**Comment by rmacnak-google** [comment]
This can be resolved by locally installing the ia32 headers. `g++-multilib` includes these headers but there is probably a smaller, more-specific package.

Longer term, the engine's GN configuration should probably have the C++ compiler use the downloaded sysroots, so everyone is building from the same sources. Compare https://dart-review.googlesource.com/c/sdk/+/25160/4/build/config/sysroot.gni

@jason-simmons

**Comment by gspencergoog** [comment]
Yes, this does indeed fix the build.  For now, I'm going to update the `install-build-deps-android.sh` script to install this.  (I'm not familiar enough with the engine to know how to update the GN configuration, and I want to unblock people working on Rodete, including me).

**Comment by gspencergoog** [comment]
Seems that we were actually already supposed to be installing `g++-multilib`, but we just were using a flawed check for 64-bit architecture that didn't work on Rodete.  I've submitted a PR.

**Comment by tvolkert** [comment]
For posterity, I couldn't build the engine just now on a clean Rodete installation; to fix it, I had to do the following:

```
$ sudo apt-get install pkg-config
$ sudo apt-get install libfreetype6-dev
$ sudo apt-get install glx-alternative-mesa mesa-common-dev
```
