### ISSUE TITLE
Cross links for performance debugging

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#14144]
FAQ should link to debugging.md and testing.md
testing.md should link to debugging.md

**Comment by Hixie** [comment]
cc @Sfshaza

**Comment by Sfshaza** [comment]
I hesitate to do that just now, as I will be moving files around. But I will keep this open for when I've done that.

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2002](https://github.com/flutter/website/issues/2002) via [**ZenHub**](https://www.zenhub.com/)
