### ISSUE TITLE
No error when accessing missing key from dynamic content

### ISSUE THREAD

**Issue by johnmccutchan** [flutter/flutter#141475]
See screenshot. Would have expected an error when accessing "data.listInvalidName".

**Comment by johnmccutchan** [comment]
<img width="1432" alt="Screenshot_2024-01-12_at_11 44 48_AM" src="https://github.com/flutter/flutter/assets/224266/c6d8d599-8724-4bb2-9641-3275f94f294a">

**Comment by Hixie** [comment]
This would be a breaking change, which we are committed to never doing for RFW.

**Comment by Hixie** [comment]
Closing per last comment, but let me know if there's another option.
