### ISSUE TITLE
Right to Left Decimal Numbers Changing Directions

### ISSUE THREAD

**Issue by Plosconos** [flutter/flutter#141502]
### Steps to reproduce

Hello Flutter Team,

My name is Gerson and I am building a project in FlutterFlow.

I found a bug and after contacting them in GitHub their technical team found out the issue and the bug is in Flutter and not in FlutterFlow.... and they told me to contact your team.

GitHub opened ticket:

https://github.com/FlutterFlow/flutterflow-issues/issues/2148#issuecomment-1889575276

GitHub FlutterFlow Answer:

![GitHub Response](https://github.com/flutter/flutter/assets/155753902/9eff9435-9577-4dcb-b297-6d8d2f34dd05)

About the bug:

1) My app is in 2 languages (English and Hebrew).

2) In Hebrew words are written from right to left... only words... NOT numbers

3) I have in the app a textfield to type a decimal number (price)

The issue in the system is: When changing the language from english to hebrew also the decimal numbers are changing position (did not supposed to).

**Example: when I write 50.25 in english and I change to hebrew is showing 25.50 and this is wrong!

Also if I direct typre in Hebrew is also changing direction in decimal numbers... if I type 50.25 already in hebrew is showing 25.50**

I am attaching a quick video showing the issue.

[New.Compressed.zipped.Folder.zip](https://github.com/flutter/flutter/files/13927310/New.Compressed.zipped.Folder.zip)

I have spoken with FlutterFlow technical team and them told me it is a bug in Flutter and they told me to contact your team in order to solve it.

Hope you guys can help me solve the issue.

Thank you very very much and I wish you a lot of success!!!

Best regards,

Gerson

### Expected results

Numbers ( intergers, decimals, percentage, etc...) did not suppouse to change direction in right to left languages.

In ALL right to left languages only words change direction...NOT numbers.

My expection is when using right to left languages the numbers DO NOT change direction.

### Actual results

Hello Flutter Team,

My name is Gerson and I am building a project in FlutterFlow.

I found a bug and after contacting them in GitHub their technical team found out the issue and the bug is in Flutter and not in FlutterFlow.... and they told me to contact your team.

![GitHub Response](https://github.com/flutter/flutter/assets/155753902/9eff9435-9577-4dcb-b297-6d8d2f34dd05)

About the bug:

1) My app is in 2 languages (English and Hebrew).

2) In Hebrew words are written from right to left... only words... NOT numbers

3) I have in the app a textfield to type a decimal number (price)

The issue in the system is: When changing the language from english to hebrew also the decimal numbers are changing position (did not supposed to).

**Example: when I write 50.25 in english and I change to hebrew is showing 25.50 and this is wrong!

Also if I direct typre in Hebrew is also changing direction in decimal numbers... if I type 50.25 already in hebrew is showing 25.50**

I am attaching a quick video showing the issue.

[New.Compressed.zipped.Folder.zip](https://github.com/flutter/flutter/files/13927310/New.Compressed.zipped.Folder.zip)

I have spoken with FlutterFlow technical team and them told me it is a bug in Flutter and they told me to contact your team in order to solve it.

Hope you guys can help me solve the issue.

Thank you very very much and I wish you a lot of success!!!

Best regards,

Gerson

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
Thanks for the report @Plosconos 
In order to properly address the issue, we would need a complete minimal reproducible code sample + replication steps that we can directly run that shows the reported behavior. Also please provide your `flutter doctor -v`.
