### ISSUE TITLE
Breaking Change in latest master: ViewConfiguration constructor named parameter 'size' isn't defined

### ISSUE THREAD

**Issue by ilber** [flutter/flutter#141562]
### Steps to reproduce

I have a code that creates a RenderView like this:
```dart
final renderView = RenderView(
      view: lastView,
      child: RenderPositionedBox(alignment: Alignment.center, child: repaintBoundary),
      configuration: ViewConfiguration(
        size: logicalSize,
        devicePixelRatio: lastView.devicePixelRatio,
      ),
    );
```

Testing the code with the latest master branch it doesn't build.  The breaking change has been caused by this commit:  https://github.com/flutter/flutter/commit/4534a24c09c5919182fc080fe80d48db25c0b56a

### Expected results

The code builds without issues.

### Actual results

The code doesn't build because the constructor I am using doesn't exist anymore. This will make it impossible for us to support older versions of flutter.

### Code sample

<details open><summary>Code sample</summary>

```dart
final repaintBoundary = RenderRepaintBoundary();

    var lastView = WidgetsBinding.instance.platformDispatcher.views.last;

    var logicalSize = lastView.physicalSize / lastView.devicePixelRatio;

    final renderView = RenderView(
      view: lastView,
      child: RenderPositionedBox(alignment: Alignment.center, child: repaintBoundary),
      configuration: ViewConfiguration(
        size: logicalSize,
        devicePixelRatio: lastView.devicePixelRatio,
      ),
    );

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.19.0-5.0.pre.45, on macOS 14.2.1 23C71 darwin-arm64, locale en-CH)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    ! CocoaPods 1.12.1 out of date (1.13.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] Android Studio (version 2020.3)
[✓] Android Studio (version 2023.1)
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.85.1)
[✓] Connected device (2 available)
[✓] Network resources
```

</details>

**Comment by goderbauer** [comment]
Hallo! I am sorry to hear that the change is causing issues. Our breaking change policy is listed here: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes. According to that policy, the change in question did not qualify as a breaking change.

If you want to avoid that changes in Flutter break your project I'd like to encourage you to add your tests to our customer tests repository: https://github.com/flutter/tests

The migration path for your code is relatively straight-forward, though:

```dart
final renderView = RenderView(
      view: lastView,
      child: RenderPositionedBox(alignment: Alignment.center, child: repaintBoundary),
      configuration: ViewConfiguration(
        physicalConstraints: BoxConstraints.tight(logicalSize) * lastView.devicePixelRatio,
        logicalConstraints: BoxConstraints.tight(logicalSize),
        devicePixelRatio: lastView.devicePixelRatio,
      ),
    );
```

**Comment by ilber** [comment]
hey @goderbauer migrating the code is not an issue. The problem is support multiple versions of flutter and because of this breaking change we have to drop support to older versions. 

I can add a test on specific parts of the Flutter API we use but it will be hard to add tests for everything. I think the flutter team should revisit the concept of a breaking change. The api you touched is a public API.
