### ISSUE TITLE
[Proposal] Allow Flutter to override global variables for `dart` and `.pub-cache` path 

### ISSUE THREAD

**Issue by iapicca** [flutter/flutter#141527]
### Use case

In some cases the developer may need a complete installation of `dart`, 
separated from the one shipped together with `flutter`.

Unfortunately in said case `flutter doctor` will complain about dart path
```console
! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.2.4/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/francesco/flutter. Consider adding /Users/francesco/flutter/bin to the front of your path.
```

### Proposal

allow flutter to configure path for dart (and `.pub-cache` presumably) overriding the global variables

NOTE: if this feature already exist feel free to close this issue and,
up to the goodness of your heart, provide an answer [here](https://stackoverflow.com/questions/77815124/how-to-specify-flutter-specific-dart-path)

eg
```bash
flutter config --dart_path <your_home>/flutter/bin # delault
flutter config --pub_cache <your_home>/flutter/.pub-cache # instead of <your_home>/.pub-cache

```

**Comment by christopherfujino** [comment]
@iapicca it sounds to me like the action item here is to offer better documentation to users on *why* a doctor validator failed, and whether or not it is safe for the user to ignore it.

It seems to me like validating that a file exists at a path the user specified is providing minimal value to the user. WDYT?

**Comment by iapicca** [comment]
@christopherfujino 
if I can answer you with a question
(not a speculative one, I honestly don't know how it works)

given the conditions below

```console
dart --version
Dart SDK version: 3.2.5 (stable) (Tue Jan 16 15:02:13 2024 +0000) on "macos_arm64"
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.16.7, on macOS 14.2.1 23C71 darwin-arm64, locale en-US)
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.2.5/libexec/bin/dart, which is not inside your current Flutter SDK checkout at
      /Users/francesco/flutter. Consider adding /Users/francesco/flutter/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.85.1)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

```bash
### DART
export PATH="$HOME/flutter/bin:$PATH"
export PATH="$HOME/.pub-cache/bin:$PATH"
export PATH="/opt/homebrew/opt/dart/bin:$PATH"
```

and assuming that 
- running `dart compile exe bin/myapp.dart` I will use Dart version *3.2.5*
- running `flutter run` I will use  Dart version *3.2.4* (from flutter/bin)
- both dart versions share a single `.pub-cache`

(finally the question)
### will the shared `.pub-cache` cause issues?

if the answer is no the issue can be closed

**Comment by christopherfujino** [comment]
@iapicca that's a good question, and I see where you're coming from now.

I believe the answer to your question "will the shared.pub-cache cause issues" is no, they will not. This is roughly equivalent to me having used the same pub-cache for five years, even though i've been tracking (very nearly) the latest dart-sdk the whole time.

I'm going to close this issue, but if you are not convinced this is a non-issue, feel free to re-open with more context. Thanks!

**Comment by iapicca** [comment]
@christopherfujino 
if you say there is no problem for 2 different version of dart using the same .pub-cache
than there is indeed no reason for this issue to be addressed

thank you for your time
