### ISSUE TITLE
Support for Kinyarwanda (rw) Language locale

### ISSUE THREAD

**Issue by RegisSaffi** [flutter/flutter#141505]
### Use case

I'm requesting the addition of support for the Kinyarwanda language locale (rw) in Flutter. Kinyarwanda is widely spoken, and including this locale would enhance the accessibility of Flutter applications for users who prefer or require Kinyarwanda language support.

## Details
- **Language Code:** rw
- **Language Name:** Kinyarwanda

## Why it Matters
- **Inclusivity:** Supporting Kinyarwanda will make Flutter applications more inclusive.
- **Global Reach:** Kinyarwanda has a significant speaker population, expanding the reach of Flutter applications.

### Proposal

Include Kinyarwanda translations for common UI elements and error messages.

### Documentation
Provide guidance in the documentation on integrating Kinyarwanda language localization.

## Additional Information
- Flutter Version: N/A
- Dart Version: N/A

I believe this feature aligns with Flutter's commitment to diversity and inclusivity. Thank you for considering this request.

**Comment by goderbauer** [comment]
Unfortunately the Google translation service that Flutter depends on doesn't support Kinyarwanda. We appreciate the contribution but unfortunately I'm going to have to close this since we don't have the infrastructure needed to support the `rw` locale.
