### ISSUE TITLE
 404 - when downloading dSYM file for Flutter.framework

### ISSUE THREAD

**Issue by aliakhtar-hu** [flutter/flutter#141506]
### Steps to reproduce

We are following this [document](https://github.com/flutter/flutter/wiki/Crashes/f393b795c90b81f79c61b59bb0f6ac4a8ba92fc9#symbolicating-stack-traces-for-engine-crashes) to download the dSYM file for Flutter.framework

Since we are using Flutter 3.16.1 the flutter engine hash should be `22b600f240548c1cf6f5d3f9ae65a5c9e51bc443` [reference](https://github.com/flutter/flutter/blob/3.16.1/bin/internal/engine.version) 

So the  dSYM download url would be like this 
`https://storage.cloud.google.com/flutter_infra/flutter/22b600f240548c1cf6f5d3f9ae65a5c9e51bc443/ios-release/Flutter.dSYM.zip`

### Actual results

<img width="1078" alt="Screenshot 2024-01-13 at 4 16 27 PM" src="https://github.com/flutter/flutter/assets/64727840/822798af-1cbe-44ee-8d90-ff4f9f034af0">

```
QTYPFWXD6G:FlutterDesktop a.ali15$ flutter --version
Flutter 3.16.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7f20e5d18c (7 weeks ago) • 2023-11-27 09:47:30 -0800
Engine • revision 22b600f240
Tools • Dart 3.2.1 • DevTools 2.28.3
QTYPFWXD6G:FlutterDesktop a.ali15$ 

```

</details>

**Comment by stuartmorgan** [comment]
> ### Steps to reproduce
> We are following this [document](https://github.com/flutter/flutter/wiki/Crashes/f393b795c90b81f79c61b59bb0f6ac4a8ba92fc9#symbolicating-stack-traces-for-engine-crashes) to download the dSYM file for Flutter.framework

You are using a version of that page that is three years old. For current artifacts, you need to reference [the current version of the page](https://github.com/flutter/flutter/wiki/Crashes/).
