### ISSUE TITLE
[camera] Add `isDisposed` getter to `CameraController`

### ISSUE THREAD

**Issue by Dampfwalze** [flutter/flutter#141513]
### Use case

Check if a `CameraController` is already disposed.

### Proposal

Add `isDisposed` getter to `CameraController`.

**Comment by stuartmorgan** [comment]
> ### Use case
> Check if a `CameraController` is already disposed.

This is a description of what the proposed API would do, rather than a use case. What is the goal that you are trying to accomplish that this API would allow for?

**Comment by Dampfwalze** [comment]
In my use case, I am disposing and rebuilding a `CameraController` based on the apps lifecycle, while trying to reuse the old controller, if it has not been disposed yet. So I have the following conditional logic:

```dart
CameraDescription desc = ...;
CameraController controller = ...;

if(controller.isDisposed) {
  controller = CameraController(desc, ResolutionPreset.max);
} else {
  controller.setDescription(desc)
}
```

**Comment by stuartmorgan** [comment]
Why are you keeping the `disposed` controller in the first place? A disposed controller isn't intended to be used again, so it's not clear to me why you are trying to track this within the controller instead of at the level of your code (e.g., by having a nullable field, and then a helper that returns a non-nullable controller by re-populating the field if necessary).

**Comment by Dampfwalze** [comment]
I keep the controller, because I am using Riverpods `FutureProvider` to build and provide the `CameraController`, which keeps the old value when transitioning to a loading state. I am using this value as my old controller I want to reuse. But when I dispose a controller, there is no way to get rid of this value, so that it is not preserved while in loading state. I want to solve this Problem by checking whether the controller is already disposed or not.

**Comment by navaronbracke** [comment]
That use-case is something you can do without the need for the disposed flag. Would you mind opening a thread in the help section on the Flutter Discord? I'll help you out over there.

**Comment by huycozy** [comment]
>I am using this value as my old controller I want to reuse. But when I dispose a controller, there is no way to get rid of this value, so that it is not preserved while in loading state.

@Dampfwalze It's still a bit unclear why you need to preserve the old controller. I see that you can re-assign a new controller after disposing of old one (with any state). Could you be more specific?
