### ISSUE TITLE
When will Material 2 (`useMaterial3: false`) be deprecated?

### ISSUE THREAD

**Issue by Gobmichet** [flutter/flutter#141555]
Hi,

Material 3 recently became default with flutter 3.16.

However, Id' like to know until when will we be able to use  :
`useMaterial3: false,`

In order to continue to use Material 2 'cause Material 3 just destroys our apps UI and we will have some work to migrate all of them...

Do we have a date ?

Will we be able to force Material 2 in our flutter apps ad vitam eternam ?

Would love it 'cause i really prefer Material 2 ! (0_o)

**Comment by huycozy** [comment]
Per [Migration guide](https://docs.flutter.dev/release/breaking-changes/material-3-default#migration-guide):

>You can still opt out of the Material 3 version of the Material library by specifying useMaterial3: false in your MaterialApp theme.

Doesn't it work on your project? If so, could you be more specific with a specific case (sample code, steps to reproduce)?

When opening an issue, please try to provide all information indicated in the template so that we can address this issue properly (See bug issue template [here](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml)).

**Comment by Gobmichet** [comment]
Yes it does work, but i'd want to know until when ? because i read this :
![Capture](https://github.com/flutter/flutter/assets/3100468/76962500-6e76-4807-a669-09e26192d617)

And my problem is to know until when will it work ?

When won't we be able to force the Material2 design for our apps anymore ?

It is very important for us to know that in order to plan our app(s)'s migration(s) (and customization(s) in order to keep the same UI even though passing from Material 2 to 3...)

Thanks in advance.

**Comment by zambetpentru** [comment]
The question I haven't wanted to ask! Hopefully it is kept for quite a long time as it is quite a change to evaluate across our apps and Material 2 works very nicely today for us - is there a Material 3 theme to mimic the size, colour and spacings of Material 2?

**Comment by huycozy** [comment]
Per [Deprecation policy](https://docs.flutter.dev/release/compatibility-policy#deprecation-policy):

>Deprecated APIs are removed after a migration grace period. This grace period is one calendar year after being released on the stable channel, or after 4 stable releases, whichever is longer.

But I'm not pretty sure when it's applied for `useMaterial3` so I will keep this for other's input.

**Comment by HansMuller** [comment]
Before we deprecate `useMaterial3: false` we'll introduce, likely in a separate package, an M2 compatibility theme that preserves as much of the M2 L&F as possible.  We'd definitely prefer that developers migrate to M3 but understand that some of the small changes in text styles and the color scheme can be troublesome for existing apps. 

CC @QuncCccccc, @TahaTesser, @Piinks

**Comment by Piinks** [comment]
Closing in favor of https://github.com/flutter/flutter/issues/143499 as this is a question rather than an action item.
We're currently working on a backwards compatibility solution for M2, which would be established well before the `useMaterial3` flag is deprecated and removed.
