### ISSUE TITLE
Allow programatic access to the Flutter command-line tools

### ISSUE THREAD

**Issue by amal-stack** [flutter/flutter#141599]
### Use case

The [Flutter command-line tools](https://docs.flutter.dev/reference/flutter-cli) provide commands to create, run and analyze Flutter apps. Having APIs to access these tools from a Dart program would be helpful for writing command-line apps. 

I ended up writing a bash script to generate localization code for multiple ARB files using the `flutter gen-l10n` tool.
For apps with a single ARB file and an `l10n.yaml` file, `flutter run` automatically generates localization code. However, for apps with multiple ARB files, I have to run `flutter gen-l10n` for each file with a different set of arguments. I have currently accomplished this with a shell script:
:
*gen_l10n.sh*
```bash
gen_l10n() {
  arb_dir=$1
  template_arb_file=$2
  output_localization_file=$3
  output_class=$4
  
  flutter gen-l10n --arb-dir $arb_dir --template-arb-file $template_arb_file \
    --output-localization-file $output_localization_file \
    --output-class $output_class \
    --no-nullable-getter --format
}

gen_l10n ./lib/l10n app_en.arb app_localizations.dart AppLocalizations
gen_l10n ./lib/utilities/onboarding/l10n messages_en.arb onboarding_localizations.dart OnboardingLocalizations
gen_l10n ./lib/location/map/l10n messages_en.arb maps_localizations.dart MapsLocalizations
gen_l10n ./lib/shared/l10n messages_en.arb shared_app_localizations.dart SharedAppLocalizations

```
I also have to write a `gen_l10n.bat` file for Windows as is customary. 

However, since Dart supports writing command-line apps (https://dart.dev/tutorials/server/cmdline), it would be much more flexible to write a Dart command-line app instead of multiple scripts. 

Currently, to run the `flutter gen-l10n` tool or other commands from the Flutter CLI, I have to use `Process.run()` from `dart:io` . 

Having a way to access the Flutter tools from a Dart program would help with such use cases and would make writing command-line apps for Flutter easier.  

### Proposal

There does not seem to be a way to access these commands programatically from a Dart program. 

Having a way to access the Flutter tools from a Dart program would help with such use cases and would make writing command-line apps for Flutter easier.

**Comment by darshankawar** [comment]
@amal-stack 
Can you check below issues and see if they resemble your case or not ?

https://github.com/flutter/flutter/issues/107157
https://github.com/flutter/flutter/issues/56681

**Comment by amal-stack** [comment]
@darshankawar These issues do address the one specific problem I am solving. This problem is just one of the use cases when having the Flutter tools available in a Dart program would be beneficial among others.

**Comment by darshankawar** [comment]
Thanks for the feedback.

**Comment by christopherfujino** [comment]
@amal-stack so, we have the `flutter daemon` protocol: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/doc/daemon.md

Although it's rough around the edges (it basically only implements what the IDE extensions require), I don't think we would add ANOTHER API for programmatically interacting with the tool at this time.

That is to say, kick the tires on it, and if there are bugs or deficiencies, I would recommend filing specific issues to improve it.

Good luck!
