### ISSUE TITLE
Null safety bug on web

### ISSUE THREAD

**Issue by DanielusG** [flutter/flutter#141567]
### Steps to reproduce

I tested it on Linux and it didn't create any problems, on Web however the exception is generated

Here are the generic steps on what causes the error:
1. Create an abstract class "AbstractClass" with an abstract ChangeNotifier attribute.
2. Inherit the class and call the new class "Parent" and override the attribute though declaring it `final` and initializing it: `final ChangeNotifier attribute = ChangeNotifier();`
3. Inherit the abstract class again and call it "Child", this time perform the override of the attribute by declaring it as `final` and without initializing it: `final ChangeNotifier attribute;` It will be initialized in the constructor with `required this.attribute`

In a function then initialize the Parent class and initialize the Child class by passing to the parent.attribute constructor:
```dart
final ParentClass parentClass = ParentClass();
final ChildClass childClass =
        ChildClass(abstractNotifier: parentClass.abstractNotifier);
childClass.test();
```

The linter warns that in the Parent class and Child class the override set of the attribute is missing, however as can be seen from the code structure at the Parent class the setter does not server since the attribute is declared at the class level and is `final`, so it can no longer mutate.
Whereas at the Child class the non-server setter since the attribute is set by constructor and being `final` can no longer be set.

So I decide to override in both setter classes with this code:
```dart
@override
set abstractNotifier(ChangeNotifier value) {
  print('abstractNotifier parent changed');
  throw Exception('abstractNotifier is final');
}
```

In the Child constructor you need to add attribute.addListener:
```dart
ChildClass({required this.abstractNotifier}) {
  abstractNotifier.addListener(() {
    print('abstractNotifier changed');
  });
}
```

### Expected results

One would then expect that the setters would never be called but to be safe I put the exception, the attribute would then be initialized in parent, and passed to the child as a reference and there should be no problem

### Actual results

What happens on the Web is probably that since it is of type final, the initializer initializes the variable but it is not actually initialized (the setter is not even invoked since the exception is not thrown by the setter)
As a result, the variable remains null, even though it is not of nullable type (here is what I mean by Bug in the nullsafe)
When the child constructor is then called and the addListener method is invoked, it is obviously invoked on null and thus throws an error:
```
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following JSNoSuchMethodError was thrown while handling a gesture:
TypeError: Cannot read properties of undefined (reading 'addListener')

When the exception was thrown, this was the stack:
packages/bug_final_abstract_class/child.dart 10:13                                new
packages/bug_final_abstract_class/main.dart 38:35                                 [_incrementCounter]
packages/flutter/src/material/ink_well.dart 1183:21                               handleTap
packages/flutter/src/gestures/recognizer.dart 275:24                              invokeCallback
packages/flutter/src/gestures/tap.dart 652:11                                     handleTapUp
packages/flutter/src/gestures/tap.dart 309:5                                      [_checkUp]
packages/flutter/src/gestures/tap.dart 242:7                                      handlePrimaryPointer
packages/flutter/src/gestures/recognizer.dart 630:9                               handleEvent
packages/flutter/src/gestures/pointer_router.dart 98:7                            [_dispatch]
packages/flutter/src/gestures/pointer_router.dart 143:9                           <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/linked_hash_map.dart 21:7           forEach
packages/flutter/src/gestures/pointer_router.dart 141:17                          [_dispatchEventToRoutes]
packages/flutter/src/gestures/pointer_router.dart 127:7                           route
packages/flutter/src/gestures/binding.dart 488:5                                  handleEvent
packages/flutter/src/gestures/binding.dart 468:14                                 dispatchEvent
packages/flutter/src/rendering/binding.dart 439:11                                dispatchEvent
packages/flutter/src/gestures/binding.dart 413:7                                  [_handlePointerEventImmediately]
packages/flutter/src/gestures/binding.dart 376:5                                  handlePointerEvent
packages/flutter/src/gestures/binding.dart 323:7                                  [_flushPointerEventQueue]
packages/flutter/src/gestures/binding.dart 292:9                                  [_handlePointerDataPacket]
lib/_engine/engine/platform_dispatcher.dart 1289:5                                invoke1
lib/_engine/engine/platform_dispatcher.dart 273:5                                 invokeOnPointerDataPacket
lib/_engine/engine/pointer_binding.dart 168:30                                    [_onPointerData]
lib/_engine/engine/pointer_binding.dart 791:20                                    <fn>
lib/_engine/engine/pointer_binding.dart 720:7                                     <fn>
lib/_engine/engine/pointer_binding.dart 317:9                                     loggedHandler
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 574:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 579:39  dcall

Handler: "onTap"
Recognizer:
  TapGestureRecognizer#04625
════════════════════════════════════════════════════════════════════════════════════════════════════
```

I also report that in this code reproduction the StackTrace is correct but in my code for the application I am developing the stack trace was completely broken, pointing to asynchronous code points such as requests to firestore.

### Code sample

I created a [repository](https://github.com/DanielusG/bug_final_abstract_class) that contains the reproduction of the bug, just press the floating action button and the exception is thrown.
Build for Web
<details open><summary>Code sample</summary>

```dart
// main.dart
import 'package:bug_final_abstract_class/child.dart';
import 'package:bug_final_abstract_class/parent.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final ParentClass parentClass = ParentClass();

  void _incrementCounter() {
    final ChildClass childClass =
        ChildClass(abstractNotifier: parentClass.abstractNotifier);
    childClass.test();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: const Center(
        child: Text(
          'Bug showcase',
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

```dart
// class.dart
import 'package:flutter/material.dart';

abstract class AbstractClass {
  abstract ChangeNotifier abstractNotifier;
}
```

```dart
// parent.dart
import 'package:bug_final_abstract_class/class.dart';
import 'package:flutter/material.dart';

class ParentClass extends AbstractClass {
  @override
  final ChangeNotifier abstractNotifier = ChangeNotifier();

  ParentClass();

  @override
  set abstractNotifier(ChangeNotifier value) {
    print('abstractNotifier parent changed');
    throw Exception('abstractNotifier is final');
  }
}
```

``` dart
// child.dart
import 'package:bug_final_abstract_class/class.dart';
import 'package:flutter/material.dart';

class ChildClass extends AbstractClass {
  @override
  final ChangeNotifier abstractNotifier;

  ChildClass({required this.abstractNotifier}) {
    abstractNotifier.addListener(() {
      print('abstractNotifier changed');
    });
  }

  void test() {
    print(abstractNotifier.toString());
  }

  @override
  set abstractNotifier(ChangeNotifier value) {
    print('abstractNotifier child changed');
    throw Exception('abstractNotifier is final');
  }
}
```
</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.5, on Garuda Linux 6.6.10-zen1-1-zen, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2023.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

</details>

## Consideration:
I understand that having declared in the abstract class the non-final attribute, one would expect that inherited classes should also not be final, however, I was careless and did not notice this small inaccuracy, and since there was no linter indication about it I did not understand where the problem came from.

## Solution:
The solution of course was to declare final also in the abstract class and this solved the problem, however it would be very useful if the linter warned of this inconsistency, or at least that the error is consistent across platforms since on Linux it does not generate errors while on the Web it does

**Comment by DanielusG** [comment]
Ops i forgot to translate the issue, I am translating the message and will edit it in a few minutes

**Comment by darshankawar** [comment]
Thanks for the report @DanielusG 
I was able to replicate the reported error running the repo on mac + web, but not on mac + desktop. 


> The solution of course was to declare final also in the abstract class and this solved the problem, however it would be very useful if the linter warned of this inconsistency,

Have you tried using [flutter_lints](https://pub.dev/packages/flutter_lints) or [`dart_](https://github.com/dart-lang/linter) that might help to detect the warning ?
