### ISSUE TITLE
[Android] Listening to App life-cycle events through FlutterPlugin instance

### ISSUE THREAD

**Issue by vaidotasstrazdas** [flutter/flutter#141532]
### Use case

It is more a question than feature request, since I am not aware if Flutter supports that or not. Let's say we want to listen to onResume event. In Flutter's Dart widgets, it is pretty straight-forward. Also, if we have some use-case, we can override onResume in the MainActivity which extends FlutterActivity.

However, what if we are developing Flutter plugin that utilizes native Android functionality, and we would like to listen to the same onResume event from that plugin?

### Proposal

My question is the following. Is it possible to listen to onResume from FlutterPlugin instance? If not, are there any potential workarounds that can be utilized, and does Flutter team have any plans on adding such support in the future? For instance, we can listen already onActivityResult by just marking that our plugin extends PluginRegistry.ActivityResultListener. So maybe we already can listen to onResume through utilization of any of the interface from PluginRegistry? If so, which one it would be? Thanks for help in advance.

**Comment by darshankawar** [comment]
@vaidotasstrazdas 
Can you take a look at [this](https://stackoverflow.com/questions/53883813/how-to-handle-android-lifecycle-in-flutter-android-plugin-package) and see if it helps to answer your question ?
