### ISSUE TITLE
Platform exception while implementing the shared preferences

### ISSUE THREAD

**Issue by abdulrehman192** [flutter/flutter#141523]
### Steps to reproduce

When I try to get the instance of the shared preferences it gives the following exception

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)

### Expected results

It need to be smooth usage of the plugin

### Actual results

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)

### Code sample

<details open><summary>Code sample</summary>

```dart
SharedPreferences shared = await SharedPreferences.getInstance();
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.16.7, on Microsoft Windows [Version 10.0.19045.3930], locale en-PK)
    • Flutter version 3.16.7 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ef1af02aea (3 days ago), 2024-01-11 15:19:26 -0600
    • Engine revision 4a585b7929
    • Dart version 3.2.4
    • DevTools version 2.28.5

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\mrabd\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Java\jdk-11.0.14\bin\java
    • Java version Java(TM) SE Runtime Environment 18.9 (build 11.0.14+8-LTS-263)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.31)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.34114.132
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Community Edition (version 2023.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.2.3
    • Flutter plugin version 77.0.1
    • Dart plugin version 233.13135.65

[√] VS Code (version 1.85.1)
    • VS Code at C:\Users\mrabd\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • AC2003 (mobile)   • adb-42b69244-d0zCdr._adb-tls-connect._tcp • android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows                                   • windows-x64    • Microsoft Windows [Version
      10.0.19045.3930]
    • Chrome (web)      • chrome                                    • web-javascript • Google Chrome 120.0.6099.217
    • Edge (web)        • edge                                      • web-javascript • Microsoft Edge 120.0.2210.121

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by huycozy** [comment]
Hi @abdulrehman192 
Which target platform are you seeing the issue on? Please provide the entire output of `flutter run -v`. 

Please also share which `shared_preferences` plugin version you are using as well (a piece of `pubspec.lock` that includes the package and its dependencies. You can remove private dependencies from the file if they are sensitive). Thanks!

**Comment by abdulrehman192** [comment]
[](url)I am facing this issue on android. also keep in mind I ma using the prefix for example. 

`static String prefName = "com.example.educentic_";
  static String introAvailable = "${prefName}isIntroAvailable";`
shared_preferences  version : 2.2.2

The text is too long so I attached the txt files

[run output.txt](https://github.com/flutter/flutter/files/13950497/run.output.txt)

[publock.txt](https://github.com/flutter/flutter/files/13950499/publock.txt)

**Comment by huycozy** [comment]
I can see your fetched package is up-to-date. I tried reproducing this issue with [plugin example](https://github.com/flutter/packages/tree/main/packages/shared_preferences/shared_preferences/example) (updated it to use the same `prefName` as yours but it didn't appear. Can you also try this example on your end?

**Comment by erfinbadrian** [comment]
Hello @huycozy , im got that issue also. any update with this issue?

**Comment by huycozy** [comment]
@erfinbadrian Could you confirm this with [plugin example](https://github.com/flutter/packages/tree/main/packages/shared_preferences/shared_preferences/example)? I can't reproduce the issue with this example.
