### ISSUE TITLE
no show select dialog on. iphone  browse 

### ISSUE THREAD

**Issue by Candy0830** [flutter/flutter#141580]
### Steps to reproduce

iphone 12,  web browse

````flutter
final XFile? image = await ImagePicker().pickImage(  source: ImageSource.gallery);
````

### Expected results

show image select dialog 

### Actual results

not show

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by dam-ease** [comment]
Hello @Candy0830.
Please can you provide all the information in the template? 
I see this is an issue related to the `image_picker` package, you can try with the example here https://pub.dev/packages/image_picker/example. Does this happen on web on iPhone 12?
Is this peculiar to only iPhone 12?
Kindly help with more information on the issue you are facing to help us triage this better.
