### ISSUE TITLE
My UI started to stutter on scroll in new flutter beta upgrade.

### ISSUE THREAD

**Issue by squirelboy360** [flutter/flutter#141581]
### Steps to reproduce

1. I upgraded to the latest beta version of flutter and continued the debugging of my app like nothing happened.
2. I later discovered this stuttering of scrollable UI components especially those with special animations.

### Expected results

I expected the scrollable items to be smooth as always but was stuttering like never before.

### Actual results

Stuttering scrollable components. 

### Code sample

the problem was not from the code but i am guessing the rendering engine of flutter as a result of flutter upgrade.

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Explaining this in words is quiet difficult but i have recorded a short video to show you just how bad this is. In the video you see the stutter. I witnessed it initially from my iphone in a separate app i am working on but later discovered it was even worse in my production app.

https://github.com/flutter/flutter/assets/130235676/981cd381-1899-416f-87cb-3d84381eaca9

</details>

### Logs

the problem was not from the code but i am guessing the rendering engine of flutter as a result of flutter upgrade.

### Flutter Doctor output

the problem was not from the code but i am guessing the rendering engine of flutter as a result of flutter upgrade.

**Comment by jonahwilliams** [comment]
Hi, please fill out the issue template including your flutter doctor. if you can provide a minimal repro or example app that shows the problem that would be helpful

**Comment by kaushik77050** [comment]
I encountered similar kind of issue, to resolve this I created a new project and then copy pasted my code in the new one and it worked, most of the time its because of incompatible version of flutter packages in pubspec.yaml

**Comment by squirelboy360** [comment]
> Hi, please fill out the issue template including your flutter doctor. if you can provide a minimal repro or example app that shows the problem that would be helpful

I cannot submit a new template because i have found a work-around and was just about to close the comment. But I would still provide you with my flutter doctor: flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 3.19.0-0.1.pre, on macOS 14.1.1 23B81 darwin-x64, locale en-NL)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.85.0)
[✓] Connected device (3 available)
    ! Error: Browsing on the local area network for iPhone (107). Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

! Doctor found issues in 1 category. 
---------------------------------------------------------------------
The comment provided by [kaushik77050](https://github.com/kaushik77050) solved the problem.
