### ISSUE TITLE
Powershell 7.4.1 + Flutter + Windows build CMake Error with plugins

### ISSUE THREAD

**Issue by jtmcdole** [flutter/flutter#141514]
## Problem
On my system (windows 11) - I cannot run or build my app for windows with `flutter run -d windows` or `flutter build windows` while in Powershell.  The error is the following:

```shell
flutter run -d windows
Launching lib\main.dart on Windows in debug mode...
CMake Error at flutter/generated_plugins.cmake:15 (add_subdirectory):
  add_subdirectory given source
  "flutter/ephemeral/.plugin_symlinks/audioplayers_windows/windows" which is
  not an existing directory.
Call Stack (most recent call first):
  CMakeLists.txt:58 (include)
```

The directory does exist; its a shortcut.

 So I thought I'd just run `dir`:

```shell
dir .\windows\flutter\ephemeral\.plugin_symlinks\audioplayers_windows
Get-ChildItem: The path cannot be traversed because it contains an untrusted mount point. : 'D:\src\<app_name>\windows\flutter\ephemeral\.plugin_symlinks\audioplayers_windows'
```

## Work around

Don't use powershell for now and use cmd.  `dir` works, `flutter run -d windows` works. It is a mystery to me.

### Actual results

flutter does not run

### Flutter Doctor output

```
[✓] Flutter (Channel beta, 3.19.0-0.1.pre, on Microsoft Windows [Version 10.0.22631.3007], locale en-US)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.6)
[✓] Android Studio (version 2022.3)
[✓] VS Code, 64-bit edition (version 1.85.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

**Comment by huycozy** [comment]
I checked this on my Windows 10 machine but don't see this issue with PowerShell. I'm not sure if this only occurs on Windows 11 or not (my Windows 11 machine is not available currently). So, I will label this issue for other's input.

**Comment by jtmcdole** [comment]
I'm unable to reproduce this now on my same machine...

**Comment by huycozy** [comment]
I checked this on My Windows 11 machine, on the master channel (3.19.0-5.0.pre.45) but can't reproduce this. `flutter` runs well, and `dir` also outputs the fetched plugin without error.

**Comment by jtmcdole** [comment]
Here's hoping it doesn't come back.
