### ISSUE TITLE
reusePort not supported on android

### ISSUE THREAD

**Issue by TheMattSchiller** [flutter/flutter#141587]
### Steps to reproduce

using essentially the example code this works on ios but on android the following error occurs

`error third_party/dart/runtime/bin/socket_android.cc:147: `reusePort` not supported for Android.`

``` 
 void _startDiscovery() async {
    // Start mDNS client
    await mdns.start();

    // Get the PTR record for the service
    await for (final PtrResourceRecord ptr in mdns
        .lookup<PtrResourceRecord>(ResourceRecordQuery.serverPointer(_serviceType))) {
      await for (final SrvResourceRecord srv in mdns.lookup<SrvResourceRecord>(
          ResourceRecordQuery.service(ptr.domainName))) {
        final String bundleId = ptr.domainName;
        ReadDevice(widget.isar, srv.target);
      }
    }

    // Stop mDNS client when done
    mdns.stop();
  }
  ```
 
  

### Expected results

should discover mdns services

### Actual results

fails

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by TheMattSchiller** [comment]
there was an old thread that claimed to fix this by providing rawDatagramSocketFactory but this results in the same error

```@override
class _ControllerPanelState extends State<ControllerPanel> {
  final String _serviceType = "_wled._tcp.local";
  final mdns = MDnsClient(
    // Create a custom RawDatagramSocketFactory to avoid the reusePort issue on Android
    rawDatagramSocketFactory: (dynamic host, int port,
        {bool reuseAddress = true,
          bool reusePort = false,
          int ttl = 255}) {
      return RawDatagramSocket.bind(host, port,
          reuseAddress: reuseAddress,
          reusePort: reusePort,
          ttl: ttl);
    },
  );
  List<Device> _devices = [];

  void _startDiscovery() async {
    // Start mDNS client
    await mdns.start();

    // Get the PTR record for the service
    await for (final PtrResourceRecord ptr in mdns
        .lookup<PtrResourceRecord>(ResourceRecordQuery.serverPointer(_serviceType))) {
      await for (final SrvResourceRecord srv in mdns.lookup<SrvResourceRecord>(
          ResourceRecordQuery.service(ptr.domainName))) {
        final String bundleId = ptr.domainName;
        ReadDevice(widget.isar, srv.target);
      }
    }

    // Stop mDNS client when done
    mdns.stop();
  }
```

`Dart Socket ERROR: ../../third_party/dart/runtime/bin/socket_android.cc:147: reusePort not supported for Android.`

**Comment by huycozy** [comment]
Hi @TheMattSchiller 
I checked this issue with [package example](https://github.com/flutter/packages/tree/main/packages/multicast_dns/example) on `Realme 6, Android 11` device but it worked without issue. Could you also try this example and confirm?

Which Android device are you using? (OS, model) 

Also, please provide the package version you see this issue and the output of `flutter doctor -v`. Thanks!

**Comment by TheMattSchiller** [comment]
so i tried the example but get the same output

my code 
```
   Future<void> _discoverDevices() async {
    // Parse the command line arguments.

    const String name = '_wled._tcp.local';
    final MDnsClient client = MDnsClient();
    // Start the client with default options.
    await client.start();

    // Get the PTR record for the service.
    await for (final PtrResourceRecord ptr in client
        .lookup<PtrResourceRecord>(ResourceRecordQuery.serverPointer(name))) {
      // Use the domainName from the PTR record to get the SRV record,
      // which will have the port and local hostname.
      // Note that duplicate messages may come through, especially if any
      // other mDNS queries are running elsewhere on the machine.
      await for (final SrvResourceRecord srv in client.lookup<SrvResourceRecord>(
          ResourceRecordQuery.service(ptr.domainName))) {
        // Domain name will be something like "io.flutter.example@some-iphone.local._dartobservatory._tcp.local"
        final String bundleId =
            ptr.domainName; //.substring(0, ptr.domainName.indexOf('@'));
        print('WLED instance found at'
            '${srv.target}:${srv.port} for "$bundleId".');
        ReadDevice(widget.isar, srv.target);
      }
    }
    client.stop();

    print('Done scanning');
  }
 ```

output in debug:
```
D/EGL_emulation( 9401): app_time_stats: avg=57.17ms min=3.11ms max=2296.22ms count=49
E/Dart    ( 9401): Dart Socket ERROR: ../../third_party/dart/runtime/bin/socket_android.cc:147: `reusePort` not supported for Android.
E/Dart    ( 9401): Dart Socket ERROR: ../../third_party/dart/runtime/bin/socket_android.cc:147: `reusePort` not supported for Android.
E/Dart    ( 9401): Dart Socket ERROR: ../../third_party/dart/runtime/bin/socket_android.cc:147: `reusePort` not supported for Android.
E/Dart    ( 9401): Dart Socket ERROR: ../../third_party/dart/runtime/bin/socket_android.cc:147: `reusePort` not supported for Android.
D/EGL_emulation( 9401): app_time_stats: avg=20.51ms min=3.38ms max=507.80ms count=32
I/flutter ( 9401): Done scanning
```

my flutter doctor output:
```
[✓] Flutter (Channel stable, 3.16.7, on macOS 13.5.2 22G91 darwin-arm64, locale en-US)
    • Flutter version 3.16.7 on channel stable at /Users/mattschiller/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ef1af02aea (5 days ago), 2024-01-11 15:19:26 -0600
    • Engine revision 4a585b7929
    • Dart version 3.2.4
    • DevTools version 2.28.5

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/mattschiller/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/mattschiller/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.83.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 14 (API 34) (emulator)
    • iPhone 14 (mobile)          • 4E9CA3E1-F3A0-4E49-93AA-648464856264 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 13.5.2 22G91 darwin-arm64
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 120.0.6099.216

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

im running on an emulated pixel 7 pro API 34 device and a physical samsung galaxy s21 with android version 13

**Comment by TheMattSchiller** [comment]
thank you so much for taking a look at this its a total stumper for me. This works beautifully on iOS

**Comment by TheMattSchiller** [comment]
some potentially interesting discoveries. with this code i can avoid the error but iOS complains. Android never discovers a device

```
  final _mdns = MDnsClient(
    // Create a custom RawDatagramSocketFactory to avoid the reusePort issue on Android
    rawDatagramSocketFactory: (dynamic host, int port,
        {bool reuseAddress = true,
          bool reusePort = false,
          int ttl = 255}) {
      return RawDatagramSocket.bind(host, port,
          reuseAddress: reuseAddress,
          reusePort: false,
          ttl: ttl);
    },
  );

  Future<void> _discoverDevices() async {
    // Parse the command line arguments.

    const String name = '_wled._tcp.local';
    // Start the client with default options.
    await _mdns.start();

    // Get the PTR record for the service.
    await for (final PtrResourceRecord ptr in _mdns
        .lookup<PtrResourceRecord>(ResourceRecordQuery.serverPointer(name))) {
      // Use the domainName from the PTR record to get the SRV record,
      // which will have the port and local hostname.
      // Note that duplicate messages may come through, especially if any
      // other mDNS queries are running elsewhere on the machine.
      await for (final SrvResourceRecord srv in _mdns.lookup<SrvResourceRecord>(
          ResourceRecordQuery.service(ptr.domainName))) {
        // Domain name will be something like "io.flutter.example@some-iphone.local._dartobservatory._tcp.local"
        final String bundleId =
            ptr.domainName; //.substring(0, ptr.domainName.indexOf('@'));
        print('WLED instance found at'
            '${srv.target}:${srv.port} for "$bundleId".');
        ReadDevice(widget.isar, srv.target);
      }
    }
    _mdns.stop();

    print('Done scanning');
  }
  ```
  
  android output:
  ```
  D/EGL_emulation( 9926): app_time_stats: avg=490.70ms min=8.27ms max=973.12ms count=2
I/flutter ( 9926): Done scanning
  ```
  
  iOS output:
  ```
  #0      _NativeSocket.bindDatagram (dart:io-patch/socket_patch.dart:1051:7)
<asynchronous suspension>
#1      _RawDatagramSocket.bind.<anonymous closure> (dart:io-patch/socket_patch.dart:2558:15)
<asynchronous suspension>
#2      MDnsClient.start (package:multicast_dns/multicast_dns.dart:110:40)
<asynchronous suspension>
#3      _ControllerPanelState._discoverDevices (package:alienlights/device/device_widget.dart:44:5)
<asynchronous suspension>
  ```
  
  
  working iOS output with previous code
  ```
  flutter: WLED instance found atorbital1.local:80 for "orbital1._wled._tcp.local".
flutter: WLED instance found atorbital1.local:80 for "orbital1._wled._tcp.local".
flutter: Done scanning
  ```

**Comment by huycozy** [comment]
I wonder if this issue only reproduces on emulator. Could you help to check this on a physical device (if you have one)? (my Android emulator can not boot up currently)

**Comment by HarshKishorani** [comment]
@TheMattSchiller I am facing this same issue

> some potentially interesting discoveries. with this code i can avoid the error but iOS complains. Android never discovers a device
> 
> ```
>   final _mdns = MDnsClient(
>     // Create a custom RawDatagramSocketFactory to avoid the reusePort issue on Android
>     rawDatagramSocketFactory: (dynamic host, int port,
>         {bool reuseAddress = true,
>           bool reusePort = false,
>           int ttl = 255}) {
>       return RawDatagramSocket.bind(host, port,
>           reuseAddress: reuseAddress,
>           reusePort: false,
>           ttl: ttl);
>     },
>   );
> 
>   Future<void> _discoverDevices() async {
>     // Parse the command line arguments.
> 
>     const String name = '_wled._tcp.local';
>     // Start the client with default options.
>     await _mdns.start();
> 
>     // Get the PTR record for the service.
>     await for (final PtrResourceRecord ptr in _mdns
>         .lookup<PtrResourceRecord>(ResourceRecordQuery.serverPointer(name))) {
>       // Use the domainName from the PTR record to get the SRV record,
>       // which will have the port and local hostname.
>       // Note that duplicate messages may come through, especially if any
>       // other mDNS queries are running elsewhere on the machine.
>       await for (final SrvResourceRecord srv in _mdns.lookup<SrvResourceRecord>(
>           ResourceRecordQuery.service(ptr.domainName))) {
>         // Domain name will be something like "io.flutter.example@some-iphone.local._dartobservatory._tcp.local"
>         final String bundleId =
>             ptr.domainName; //.substring(0, ptr.domainName.indexOf('@'));
>         print('WLED instance found at'
>             '${srv.target}:${srv.port} for "$bundleId".');
>         ReadDevice(widget.isar, srv.target);
>       }
>     }
>     _mdns.stop();
> 
>     print('Done scanning');
>   }
> ```
> 
> android output:
> 
> ```
> D/EGL_emulation( 9926): app_time_stats: avg=490.70ms min=8.27ms max=973.12ms count=2
> I/flutter ( 9926): Done scanning
> ```
> 
> iOS output:
> 
> ```
> #0      _NativeSocket.bindDatagram (dart:io-patch/socket_patch.dart:1051:7)
> <asynchronous suspension>
> #1      _RawDatagramSocket.bind.<anonymous closure> (dart:io-patch/socket_patch.dart:2558:15)
> <asynchronous suspension>
> #2      MDnsClient.start (package:multicast_dns/multicast_dns.dart:110:40)
> <asynchronous suspension>
> #3      _ControllerPanelState._discoverDevices (package:alienlights/device/device_widget.dart:44:5)
> <asynchronous suspension>
> ```
> 
> working iOS output with previous code
> 
> ```
> flutter: WLED instance found atorbital1.local:80 for "orbital1._wled._tcp.local".
> flutter: WLED instance found atorbital1.local:80 for "orbital1._wled._tcp.local".
> flutter: Done scanning
> ```
> 
> leaving me with this option however the device discovery still does not work on android
> 
> ```
> @override
> class _ControllerPanelState extends State<ControllerPanel> {
>  List<Device> _devices = [];
>  final _mdns = MDnsClient(
>    // Create a custom RawDatagramSocketFactory to handle reusePort based on the platform
>    rawDatagramSocketFactory: (dynamic host, int port,
>        {bool reuseAddress = true,
>          bool reusePort = false,
>          int ttl = 255}) {
>      if (Platform.isIOS) {
>        reusePort = true; // On iOS, reusePort is set to true
>      } else {
>        reusePort = false; // On Android, reusePort is set to false
>      }
>      return RawDatagramSocket.bind(host, port,
>          reuseAddress: reuseAddress,
>          reusePort: reusePort,
>          ttl: ttl);
>    },
>  );
> 
>  Future<void> _discoverDevices() async {
>    // Parse the command line arguments.
> 
>    const String name = '_wled._tcp.local';
>    // Start the client with default options.
>    await _mdns.start();
> 
>    // Get the PTR record for the service.
>    await for (final PtrResourceRecord ptr in _mdns
>        .lookup<PtrResourceRecord>(ResourceRecordQuery.serverPointer(name))) {
>      // Use the domainName from the PTR record to get the SRV record,
>      // which will have the port and local hostname.
>      // Note that duplicate messages may come through, especially if any
>      // other mDNS queries are running elsewhere on the machine.
>      await for (final SrvResourceRecord srv in _mdns.lookup<SrvResourceRecord>(
>          ResourceRecordQuery.service(ptr.domainName))) {
>        // Domain name will be something like "io.flutter.example@some-iphone.local._dartobservatory._tcp.local"
>        final String bundleId =
>            ptr.domainName; //.substring(0, ptr.domainName.indexOf('@'));
>        print('WLED instance found at'
>            '${srv.target}:${srv.port} for "$bundleId".');
>        ReadDevice(widget.isar, srv.target);
>      }
>    }
>    _mdns.stop();
> 
>    print('Done scanning');
>  }
> ```
> 
> ios ouput:
> 
> ```
> flutter: WLED instance found atorbital1.local:80 for "orbital1._wled._tcp.local".
> flutter: WLED instance found atorbital1.local:80 for "orbital1._wled._tcp.local".
> flutter: Done scanning
> ```
> 
> android output:
> 
> ```
> D/EGL_emulation( 9926): app_time_stats: avg=567.86ms min=16.60ms max=1314.59ms count=3
> I/flutter ( 9926): Done scanning
> ```

Did you get any work around with this??

**Comment by huycozy** [comment]
@TheMattSchiller I tried creating a similar Android emulator (Android 14) but the issue still doesn't appear. Checked on both [multicast_dns example](https://github.com/flutter/packages/tree/main/packages/multicast_dns/example) and your sample code below (I commented out `ReadDevice` as it's undefined):

<details>
<summary>Sample code</summary>

```dart
import 'package:multicast_dns/multicast_dns.dart';

Future<void> main() async {
  await _discoverDevices();
}

Future<void> _discoverDevices() async {
  // Parse the command line arguments.

  const String name = '_wled._tcp.local';
  final MDnsClient client = MDnsClient();
  // Start the client with default options.
  await client.start();

  // Get the PTR record for the service.
  await for (final PtrResourceRecord ptr in client
      .lookup<PtrResourceRecord>(ResourceRecordQuery.serverPointer(name))) {
    // Use the domainName from the PTR record to get the SRV record,
    // which will have the port and local hostname.
    // Note that duplicate messages may come through, especially if any
    // other mDNS queries are running elsewhere on the machine.
    await for (final SrvResourceRecord srv in client.lookup<SrvResourceRecord>(
        ResourceRecordQuery.service(ptr.domainName))) {
      // Domain name will be something like "io.flutter.example@some-iphone.local._dartobservatory._tcp.local"
      final String bundleId =
          ptr.domainName; //.substring(0, ptr.domainName.indexOf('@'));
      print('WLED instance found at'
          '${srv.target}:${srv.port} for "$bundleId".');
      // ReadDevice(widget.isar, srv.target);
    }
  }
  client.stop();

  print('Done scanning');
}
```
</details>
