### ISSUE TITLE
Controller was disposed before GoogleMap was ready.

### ISSUE THREAD

**Issue by Scott-Bebington** [flutter/flutter#141503]
### Steps to reproduce

I start my dart app on my android device, the first time it says that my google maps API key was not found even though it is in my androidManifest.xml. then when i hot restart the app it says the controller was disposed before GoogleMaps was ready

### Expected results

I would expect just a basic map to show on my screen

### Actual results

Just a blank screen with errors in my debug console

### Code sample

GoogleMapController? _googleMapController;
final CameraPosition _initialCameraPosition = CameraPosition(
    target: LatLng(-25.749710830259474, 28.24219572478904),
    zoom: 11.5,
  );

// other code here
GoogleMap(
    myLocationButtonEnabled: false,
    zoomControlsEnabled: false,
    onMapCreated: (controller) => _googleMapController = controller,
    initialCameraPosition: _initialCameraPosition
),

### Logs

D/ConnectivityManager(14041): StackLog: [android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4322)] [android.net.ConnectivityManager.registerDefaultNetworkCallbackForUid(ConnectivityManager.java:4886)] [android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4853)] [android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4827)] [io.grpc.android.AndroidChannelBuilder$AndroidChannel.configureNetworkMonitoring(AndroidChannelBuilder.java:216)] [io.grpc.android.AndroidChannelBuilder$AndroidChannel.<init>(AndroidChannelBuilder.java:197)] [io.grpc.android.AndroidChannelBuilder.build(AndroidChannelBuilder.java:168)] [com.google.firebase.firestore.remote.GrpcCallProvider.initChannel(GrpcCallProvider.java:116)] [com.google.firebase.firestore.remote.GrpcCallProvider.lambda$initChannelTask$6$com-google-firebase-firestore-remote-GrpcCallProvider(GrpcCallProvider.java:242)] [com.google.firebase.firestore.remote.GrpcCallProvider$$ExternalSyntheticLambda1.call(Unknown Source:2)] [com.google.android.gms.tasks.zzz.run(com.google.android.gms:play-services-tasks@@18.0.2:1)] [com.google.firebase.firestore.util.ThrottledForwardingExecutor.lambda$execute$0$com-google-firebase-firestore-util-ThrottledForwardingExecutor(ThrottledForwardingExecutor.java:54)] [com.google.firebase.firestore.util.ThrottledForwardingExecutor$$ExternalSyntheticLambda0.run(Unknown Source:4)] [java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)] [java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)] [java.lang.Thread.run(Thread.java:1012)]
D/TrafficStats(14041): tagSocket(126) with statsTag=0xffffffff, statsUid=-1
I/ViewRootImpl@510d9f[MainActivity](14041): ViewPostIme pointer 0
I/ViewRootImpl@510d9f[MainActivity](14041): ViewPostIme pointer 1
I/PlatformViewsController(14041): Hosting view in view hierarchy for platform view: 0
D/NativeCustomFrequencyManager(14041): [NativeCFMS] BpCustomFrequencyManager::BpCustomFrequencyManager()
D/OpenGLRenderer(14041): eglCreateWindowSurface
E/FrameEvents(14041): updateAcquireFence: Did not find frame.
D/OpenGLRenderer(14041): CFMS:: SetUp Pid : 14041    Tid : 14066
W/Parcel  (14041): Expecting binder but got null!
2
E/FrameEvents(14041): updateAcquireFence: Did not find frame.

### Flutter Doctor output

[√] Flutter (Channel stable, 3.16.5, on Microsoft Windows [Version 10.0.22621.3007], locale en-ZA)
    • Flutter version 3.16.5 on channel stable at C:\Users\scott\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (3 weeks ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\scott\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34330.188
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] VS Code (version 1.85.1)
    • VS Code at C:\Users\scott\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.80.0

[√] Connected device (4 available)
    • SM S908E (mobile) • R5CT30RZPXR • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.22621.3007]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 120.0.6099.217
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 120.0.2210.121

[√] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by huycozy** [comment]
You may hit the same reason at https://github.com/flutter/flutter/issues/139910#issuecomment-1851525883. So, please check it again and confirm if you add API key correctly. You may try [plugin example](https://github.com/flutter/packages/tree/main/packages/google_maps_flutter/google_maps_flutter/example) as well.

**Comment by kaushik77050** [comment]
Can you please provide the ss of the AndroidManifest file (make sure to hide the API key)

**Comment by Scott-Bebington** [comment]
Hi. The problem has been solved. Just started work randomly, might have
been a dependency issue or something

Thanks anyway though

**Comment by huycozy** [comment]
Closing the issue as solved.
