### ISSUE TITLE
Need to upgrade nokogiri for website build

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#14153]
Github is telling us we need to upgrade a dependency used when building our website.

We found a potential security vulnerability in one of your dependencies.
The nokogiri dependency defined in Gemfile.lock has a known critical severity security vulnerability in version range < 1.8.1 and should be updated.

Review vulnerable dependency
Only users who have been granted access to vulnerability alerts for this repository can see this message.
Learn more about vulnerability alerts

**Comment by sethladd** [comment]
cc @mjohnsullivan is this something you want your team to own?

**Comment by zoechi** [comment]
Issue moved to [flutter/website #1844](https://github.com/flutter/website/issues/1844) via [**ZenHub**](https://www.zenhub.com/)
