### ISSUE TITLE
Flutter-Web serious issues with postMessage, mouse/touch events, window, context

### ISSUE THREAD

**Issue by P5music** [flutter/flutter#141538]
### Steps to reproduce

I developed a web-app with Flutter Web in the form of a PWA.

My app uses extensively iFrames inside HTMLElementViews, in different screens in the navigation. It is common in my app to have sequences of screens each with an HTMLElementView (with iFrame inside) that are in the navigation stack.

I had to create numberous workarounds to have the screens working properly.
Now it is clear that the choice of Flutter Web for my app was wrong because of the particular features of my app (that is, the above mentioned sequences of screen navigated, each with an iFrame inside) but I discovered all these problems along the way, so I couldn't stop. It was my first Flutter Web project.

Furthermore I like Flutter so I am proud that the app works, but it is not clear if it has to be rewritten with another platform, because the workarounds I had to resort to, clearly created a spaghetti-code situation, and misterious things in the code that normal programmers cannot understand if not instructed, and it is not considered a good practice to have those workarounds in one's app. 
I'd better use a JS framework or vanilla JS. So now the app works but it is sort of a demo or MVP.
It would be a risk to use it in production.

Steps to reproduce: try to handle mouse events and postMessages with more than one screen with iFrames inside, and when the iFrames are removed/recreated, also try to send postMessages from the app to the iFrames.
Also you can test the window object being null navigating back in certain cases.
Also you can test the context of a widget being lost when navigating back in certain cases.

I have to inform the Flutter team developers that those problems are very serious.

Thanks
Best regards

### Expected results

Expected results are not explicitly written because of the inherent system of Flutter Web.
It is not clear if the issues can be solved and whether the Flutter-Web platform is suitable for such applications.

### Actual results

-the iFrames share the postMessage channel among themselves, and with the flutter app itself; I had to use signatures for each different HTMLElementView;
-mouse events are fired in every HTMLElementView, sort of transparent to each other even when in different navigated screens: I had to use PointerInterceptor for each Widget with HTMLElementView, and even with Dialogs over HTMLElementView;
-even with PointerInterceptors in place, events are fired multiple times; I had to use signatures and a complex mapping of messages, signatures, timestamps, sequences, because events are repeated with different timings but with same timestamps, and they are in sequences that are repeated themselves, so not only events have to be filtered when repeated, but also sequences have to be taken into account to avoid false positives or negatives of same-event repetitions.
-it is because indeed it is not clear what happens to iFrames if they are removed (even when explicitly removed when navigating forward/back), it seems that many iFrames continue their lives and still respond to ghost mouse events from other active iFrames and send/receive postMessages.
-the postMessages are sent and received at the same time because they are sent from the iFrames themselves to themselves,  also a "fromDart" signature was necessary to identify the messages from the app to distinguish them from the messages from the iFrame(s).
-a complex system of referencing what element has to be listening now, had to be created and a global variable set to a ever-changing listening function, to be swapped when navigating forward/back.

-when an INPUT HTML element is present in the HTML document of an iFrame, when clicking inside it, it makes the mouse event leak to the underlying widget, like it was a hole.

-the window object is lost in certain cases when navigating back (it is null, I think another window object is now active, that does not make sense because it is the common window object to the app and the iFrames); I also noticed that with Edge browser on Android the window is lost every time the app tab is put in the background (for example when passing to another open document), but this does not happens with many other browser (for instance: Firefox restarts the page, Chrome mantains the window object, if I am not wrong), so it seems to be a bug in Edge.
-also the context can be sometimes volatile in certain situations, that does not make sense with such a navigation system that uses the setState function to be called from any point of the code.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by darshankawar** [comment]
> Steps to reproduce: try to handle mouse events and postMessages with more than one screen with iFrames inside, and when the iFrames are removed/recreated, also try to send postMessages from the app to the iFrames.
> Also you can test the window object being null navigating back in certain cases.
> Also you can test the context of a widget being lost when navigating back in certain cases.

@P5music Can you provide runnable reproducible code sample that we can directly use that shows the actual behavior ?
Also, please provide `flutter doctor -v` to know on which version you are facing the reported issue.

**Comment by P5music** [comment]
> @P5music Can you provide runnable reproducible code sample that we can directly use that shows the actual behavior ? Also, please provide `flutter doctor -v` to know on which version you are facing the reported issue.
 Hello @darshankawar , thank you for the response.
 As you are asking me for the version I am experiencing the issue, it seems that you deem it a sort of bug.
 Focusing only on the postMessage and mouse events problem, I think that it is inherent to the platform, so the Flutter team has to decide what to do. I used the very last Flutter Web versions and automatically upgraded several times.

Instead, if there is a version of Flutter Web where it does not happen, please tell me, so I can compare the behaviour of my app with the two platforms, before creating a test app to demonstrate the problems.

I think whatever minimal app demonstrates the issues, it is not my app per se. However I await your response first, before embarking in creating extensive reproducible code.
Regards

**Comment by P5music** [comment]
I was not able to reproduce the issues with a test app.
I was only able to reproduce this  issue:
when performing hot restart, postMessage can produce multiple messages, and the number of duplications adds up every time the hot restart is performed.
I think this issue can be meaningful also for the others, if they are not always visible and reproducible.

But after upgrading to the new Flutter sdk, that was today, I cannot reproduce even this issue in the test app.

I checked also my app and I noticed that this issue persists, but maybe other issues are mitigated.

I think that it is not safe to remove all workarounds from my app.
In fact the above mentioned issue persists, hence it is enough for me to mantain all workarounds.
It is possible that in recent upgrades something has changed. But I see that if the above mentioned issue persists in my app but was fixed in the test app, it is possible that the issues are not solved, it is not possible to assess.

Were some of the points addressed in recent upgrades?
Regards

**Comment by darshankawar** [comment]
@P5music 
Without replicable code sample that shows the actual issues you are referring to, it'll be tough to address or answer your questions, so please provide us relevant reproducible code sample and what exactly are the issues you are facing with it (you may provide short video) or meaningful screenshots if that'll help to properly convey the issues.
