### ISSUE TITLE
Observatory is showing errors on main screen

### ISSUE THREAD

**Issue by aam** [flutter/flutter#14158]
<img width="1062" alt="screen shot 2018-01-17 at 9 58 54 pm" src="https://user-images.githubusercontent.com/381137/35083009-a62b7584-fbd1-11e7-9223-98d383e3c0c8.png">

This has regressed in 592f297922270c0c338b0048d37a510c9c16db14 which was last dart/engine roll.
Last working flutter commit is a48185a6adcf402405370057260de4a5887bd185.

cc @rmacnak-google

**Comment by aam** [comment]
c9f6e8695da1225575df478c0ecc2e6b77987ae4 (https://dart-review.googlesource.com/33540) seems to be where this regression was introduced.

**Comment by aam** [comment]
And actually it was reverted in https://dart-review.googlesource.com/c/sdk/+/33800 so hopefully in imminent dart roll this will get resolved too.

**Comment by mraleph** [comment]
@rmacnak-google do we test observatory UI (either unit tests or behavior tests)? or at least do we run analyzer on it?

**Comment by aam** [comment]
I would imagine `tools/test.py -rchrome observatory_ui` that are run as part of dart2js-linux-chromeff-*-dev do test observatory ui.

**Comment by rmacnak-google** [comment]
@mraleph We do have unit tests of the UI elements and the service library, and the analyzer runs on these. The code was correct with the current version of the SDK that runs these tests, but Observatory is built with an older, checked-in SDK.

**Comment by mraleph** [comment]
Thanks for clarifications! I just wonder if we could switch tests to run in the way that catches this breakage earlier, e.g. if we could at least run analyzer from the checked in SDK too?

**Comment by rmacnak-google** [comment]
In the past, we have ignored warnings in Observatory's build because they came from third party packages. I should check whether that's still the case and stop hiding them.

**Comment by aam** [comment]
This was fixed by https://github.com/flutter/flutter/pull/14172 engine(dart) roll.
