### ISSUE TITLE
Production builds of Gallery app drives animations at 60fps on Android

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1415]
Once a developer has built their Flutter app for a production-release of their APK, the app should drive animations at a smooth, jank-free 60fps.

**Comment by sethladd** [comment]
cc @iposva-google

**Comment by eseidelGoogle** [comment]
This seems highly dependent on @iposva-google's work on background compilation and turning that on before the Hackathon.  We do not have any automated testing of our fps, but that seems like a relevant sub-bug to delivering this.

**Comment by eseidelGoogle** [comment]
background compilation helped, but there is definitely still some jank.  We need to trace and understand.

I don't expect us to make sustained progress on this until after https://github.com/flutter/flutter/issues/2177.  Punting until after the Hackathon.

**Comment by Hixie** [comment]
This is not an actionable bug. We have performance work ongoing that will address this in time.
