### ISSUE TITLE
A couple of framework presubmits always failing due to resource exhaustion

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#141609]
For example https://github.com/flutter/flutter/pull/141608

https://ci.chromium.org/ui/p/flutter/builders/try/Mac_ios%20flutter_gallery_ios__compile/3637/overview

This is affecting all framework PRs including engine -> framework rolls.

cc engine gardener @ricardoamador

**Comment by sealesj** [comment]
@kentnguyen99 Could you help with `flutter-devicelab-mac-1` and `flutter-devicelab-mac-12` which are dead? https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=device_os&c=os&c=status&d=asc&f=device_os%3AiOS&f=pool%3Aluci.flutter.try&f=cpu%3Ax86&f=os%3AMac&k=os&s=id

I am able to ssh into them and see that they appear to be up
```
flutter@flutter-devicelab-mac-1 ~ % uptime
 7:53  up 17:59, 3 users, load averages: 1.13 1.38 1.45
```

```
flutter@flutter-devicelab-mac-12 ~ % uptime
 7:54  up  5:10, 3 users, load averages: 1.08 1.41 1.44
```

**Comment by sealesj** [comment]
Seeing more showing as dead also at: https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=os&c=status&d=asc&f=pool%3Aluci.flutter.try&k=pool&s=id&f=status%3Adead

**Comment by yusuf-goog** [comment]
@kentnguyen99 Before you reboot or make changes to the bot, please try to see if there are any indication why those bots have died. (Any dialogs, etc. that might hint to the cause)

**Comment by bartekpacia** [comment]
in case it's helpful, here are two others PRs that are failing presumably because of this:
- https://github.com/flutter/flutter/pull/141541
- https://github.com/flutter/flutter/pull/141537

**Comment by ricardoamador** [comment]
The machines are up but it appears they cannot contact the swarming service.
```
285 2024-01-16 17:24:47.091 I: get_authentication_headers(): 0s
285 2024-01-16 17:24:47.091 I: Fetched auth headers (dict_keys(['X-Luci-Machine-Token'])), they expire in -44387 sec. Next check in 0 sec.
285 2024-01-16 17:24:47.183 D: https://chromium-swarm.appspot.com:443 "POST /swarming/api/v1/bot/handshake HTTP/1.1" 401 None
285 2024-01-16 17:24:47.184 W: Got a reply with HTTP status code 401 for https://chromium-swarm.appspot.com/swarming/api/v1/bot/handshake on attempt 0: 401 Client Error: Unauthorized for url: https://chromium-swarm.appspot.com/swarming/api/v1/bot/handshake
285 2024-01-16 17:24:47.184 E: Request to https://chromium-swarm.appspot.com/swarming/api/v1/bot/handshake failed with HTTP status code 401: 401 Client Error: Unauthorized for url: https://chromium-swarm.appspot.com/swarming/api/v1/bot/handshake
285 2024-01-16 17:24:47.184 E: Failed to contact for handshake, retrying in 300 sec...
285 2024-01-16 17:29:47.316 I: Calling /swarming/api/v1/bot/handshake
285 2024-01-16 17:29:47.316 D: GOOGAPPUID = sha1(2024-01-16-flutter-devicelab-mac-12:/opt/s) % 1000 = 564
285 2024-01-16 17:29:47.317 I: ts_mon hook_name='get_authentication_headers' pool='cipd_platform:mac-amd64|cores:12|cpu:x86-64-i7-8700B|device:iPhone12,1|display_attached:1|gce:0|gpu:8086:3e9b|hidpi:0|inside_docker:0|mac_model:Macmini8,1|machine_type:n1-standard-8|os:Mac-13.6.1-22G313|os:iOS-16.2|pool:default|python:3.8.10+chromium.17|ssd:1|zone:us-corp-mtv'
```

**Comment by ricardoamador** [comment]
This is the same issue on both devicelab-mac-1 and devicelab-mac-12. @kentnguyen99 let me know if I can help.

**Comment by kentnguyen99** [comment]
Both mac-1 and mac-12 are up running fine, I can login remotely from laptop. 

flutter@flutter-devicelab-mac-1 ~ % uptime
 9:50  up  1:01, 5 users, load averages: 2.41 1.67 1.45

flutter@flutter-devicelab-mac-12 ~ % uptime
 9:51  up  1:51, 3 users, load averages: 1.17 1.38 1.41

**Comment by kentnguyen99** [comment]
@ricardoamador,  Can you test again on mac-1 & mac12 and see both machines are working properly?  I ran command 
 "Salt-call state.apply" and running fine without errors. Thanks.

**Comment by yusuf-goog** [comment]
flutter-devicelab-mac-25 is also showing up as dead. I'm applying salt states now.

**Comment by ricardoamador** [comment]
@kentnguyen99 it looks like it is resolved now. The certs are no longer showing as expired.

**Comment by ricardoamador** [comment]
Bots are back as well. THank you @kentnguyen99 !

**Comment by yusuf-goog** [comment]
mac-25 is back up as well now.

**Comment by vashworth** [comment]
These bots are still dead:

https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-11
https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-14

**Comment by ricardoamador** [comment]
I do not see mac-14 as down but do see mac-11. Taking a look.

**Comment by yusuf-goog** [comment]
I'm opening another issue for that. Its a different issue from these bots : https://github.com/flutter/flutter/issues/141629

**Comment by ricardoamador** [comment]
devicelab-mac-11 is back up with an updated cert.
