### ISSUE TITLE
[Documentation] Missing breadcrumb from SliverFixedExtentList to SliverVariedExtentList

### ISSUE THREAD

**Issue by navaronbracke** [flutter/flutter#141678]
### Use case

Developers wanting to optimize their scrolling lists will probably find `SliverFixedExtentList` quite easily.

However, if their use case turns out to require varied extents, they won't know about `SliverVariedExtentList`
because there is no breadcrumb to https://api.flutter.dev/flutter/widgets/SliverVariedExtentList-class.html from the docs in https://api.flutter.dev/flutter/widgets/SliverFixedExtentList-class.html

The opposite is already the case, though.

> 

### Proposal

Add a breadcrumb in the documentation for `SliverFixedExtentList` towards `SliverVariedExtentList`, similar to how `SliverVariedExtentList` links back to its sibling widget.

Note: We might want to fix https://github.com/flutter/flutter/issues/138912 first, before adding a link?

**Comment by darshankawar** [comment]
Thanks for the report. Maybe it can be added in `See also` section.
