### ISSUE TITLE
[RFW] Add examples that show how can RFW be used multiple flavors of apps.

### ISSUE THREAD

**Issue by tugorez** [flutter/flutter#141669]
Some ideas
- Add an example where RFW is being used in a small portion of the app.
- Add an example where the app is completely driven by the server.
- Add an example where is shown to to leverage cool things like `Theme` or `Colors` or `LayoutBuilder` can be used in RFW.
- Add an example that shows how adaptative/responsive UIs can be built with RFW.
- Add an example that shows how routing can be handled in RFW.

**Comment by Hixie** [comment]
As with https://github.com/flutter/flutter/issues/141668, PRs are very welcome but I don't know that there's much point having an open-ended issue like this on file, since we'll never be done writing examples. (I don't personally intend to write any more examples.)

**Comment by Hixie** [comment]
Closing per last comment.
