### ISSUE TITLE
Version/changelog labels no longer work

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#141642]
### Type of Request

bug

### Infrastructure Environment

Cocoon/LUCI

### What is happening?

The `flutter/packages` repo's `override: no changelog needed` and `override: no version needed` labels are not working at all, even when pushing commits after applying them.

This blocks landing PRs such as the one linked below.

### Steps to reproduce

Step 1: Open https://github.com/flutter/packages/pull/5902
Step 2: See that the labels that override the changelog and version checks are applied
Step 3: See that `repo_checks` is failing `CHANGELOG and version validation` anyway

### Expected results

`repo_checks` should be passing.

I'm assuming this is a regression from https://github.com/flutter/flutter/issues/140232, which was supposed to fix these labels to work even without re-pushing after applying them, but now not even that works. /cc @keyonghan

**Comment by ricardoamador** [comment]
Okay. Taking a look!

**Comment by keyonghan** [comment]
Now the logic is only with `rerun` rather than a new commit, based on https://github.com/flutter/flutter/issues/140232#issuecomment-1883684744. Do you want both?

Namely if a task failed, a rerun is expected to pick up the label after applied. @stuartmorgan Is this what you tried and didn't work? Please hold a bit on this PR: https://github.com/flutter/packages/pull/5902 without pushing a new commit, so that we can do some experiment.

**Comment by ricardoamador** [comment]
@keyonghan I kicked off a rerun and I can see the labels being collected. Thanks for the note. It does look like the labels are not collected on a new build.

![image](https://github.com/flutter/flutter/assets/32242716/cf71783c-b5ae-4722-8209-88e9658ef7dc)

**Comment by ricardoamador** [comment]
Dropping to P2 as this is working as expected based on previous feedback. @stuartmorgan let us know what you would like to do here.

**Comment by stuartmorgan** [comment]
> Now the logic is only with `rerun` rather than a new commit, based on [#140232 (comment)](https://github.com/flutter/flutter/issues/140232#issuecomment-1883684744). Do you want both?

Yes, the expected behavior is that every run gets the label state from the PR when the run starts. I didn't realize that requesting that re-runs get fresher label state could imply breaking non-re-run builds or I would have been clearer.

I'm actually somewhat confused about what the current behavior is then. Is it the case that non-re-run runs completely ignore the labels, and that *only* re-runs read the labels at all? If so, that's definitely very counter-intuitive for how we're using the repo, and breaks many common workflows; e.g., merging to resolve a conflict would *always* re-fail a PR that had been passing on a re-run.

**Comment by stuartmorgan** [comment]
Boosting up to P1 since this will be very confusing for each new person on the team that encounters it until changed, and will waste CI resources by requiring us to run this check twice every time we run it on a PR using these labels, but now that we can manually re-run every time we push a commit we're technically unblocked.

**Comment by ricardoamador** [comment]
We will go ahead and add this to new runs then.
