### ISSUE TITLE
some devicelab hosts are showing dead devices

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#141629]
### Type of Request

infra task

### Infrastructure Environment

devicelab

### What is happening?

Please check on the devices (showing as not connected) connected to 

https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-11
https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-14

and recover as necessary

**Comment by kentnguyen99** [comment]
Both mac-11 and mac-14 are up and running fine, I can login remotely from my end.  Both mac-11 and mac-14 are out of sync with Salt master so I ran command "salt-call state.apply" to re-sync with Salt master again.  Can someone login both machines and test again?  Thanks.

**Comment by ricardoamador** [comment]
@yusuf-goog adding this to the ticket queue for visibility and tracking.

**Comment by yusuf-goog** [comment]
yes, these bots are recovered, closing.
