### ISSUE TITLE
Debug App using VScode issue

### ISSUE THREAD

**Issue by Jadaboawwad** [flutter/flutter#141615]
### Steps to reproduce

- Clean build
- Debug the app using vscode

### Expected results

debug the app with VSCODE without issues

### Actual results

```
#0      _Completer.completeError (dart:async/future_impl.dart:19:31)
#1      ThreadInfo.resolveUrisToPathsBatch.<anonymous closure> (package:dds/src/dap/isolate_manager.dart:1136:58)
#2      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#3      ThreadInfo.resolveUrisToPathsBatch (package:dds/src/dap/isolate_manager.dart:1136:20)
<asynchronous suspension>
#4      ThreadInfo.resolveUrisToPackageLibPathsBatch (package:dds/src/dap/isolate_manager.dart:1089:21)
<asynchronous suspension>
#5      IsolateManager._sendLibraryDebuggables (package:dds/src/dap/isolate_manager.dart:913:5)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:523:21)
<asynchronous suspension>
#7      IsolateManager._configureIsolate (package:dds/src/dap/isolate_manager.dart:451:7)
<asynchronous suspension>
#8      IsolateManager.registerIsolate (package:dds/src/dap/isolate_manager.dart:247:7)
<asynchronous suspension>
#9      DartDebugAdapter._configureExistingIsolates.<anonymous closure> (package:dds/src/dap/adapters/dart.dart:790:11)
<asynchronous suspension>
#10     Future.wait.<anonymous closure> (dart:async/future.dart:523:21)
<asynchronous suspension>
#11     DartDebugAdapter._configureExistingIsolates (package:dds/src/dap/adapters/dart.dart:783:5)
<asynchronous suspension>
#12     DartDebugAdapter._withErrorHandling (package:dds/src/dap/adapters/dart.dart:2596:14)
<asynchronous suspension>
#13     DartDebugAdapter.connectDebugger (package:dds/src/dap/adapters/dart.dart:716:5)
<asynchronous suspension>
#14     FlutterDebugAdapter._connectDebugger (package:flutter_tools/src/debug_adapters/flutter_adapter.dart:381:9)
<asynchronous suspension>
#15     FlutterDebugAdapter._handleDebugPort (package:flutter_tools/src/debug_adapters/flutter_adapter.dart:462:7)
<asynchronous suspension>
```

### Code sample

<details open><summary>Code sample</summary>

```dart

class App extends StatelessWidget {
  final Map<String, dynamic> firebaseData;
  final AppRouter appRouter = AppRouter();

  App({super.key, required this.firebaseData});

  @override
  Widget build(BuildContext context) {
    return MultiBlocProvider(
        providers: [
          BlocProvider<AuthPagesCubit>(
            create: (_) => injector.get<AuthPagesCubit>(),
          ),
          BlocProvider<HomePageCubit>(
            create: (_) => injector.get<HomePageCubit>(),
          ),
          BlocProvider<LandingPageCubit>(
            create: (_) => injector.get<LandingPageCubit>(),
          ),
        ],
        child: Builder(builder: (context) {
          var isDarkMode = MediaQuery.of(context).platformBrightness == Brightness.dark;
          injector.get<AppSharedPreferences>().setDarkThemeEnabled(isDarkMode);

          return MaterialApp.router(
            debugShowCheckedModeBanner: false,
            supportedLocales: const [Locale('en'), Locale('ar')],
            localizationsDelegates: [
              AppLocalizations.delegate(firebaseData),
              GlobalMaterialLocalizations.delegate,
              GlobalWidgetsLocalizations.delegate,
              GlobalCupertinoLocalizations.delegate
            ],
            localeResolutionCallback: (deviceLocale, supportedLocales) {
              for (var locale in supportedLocales) {
                if (deviceLocale != null && deviceLocale.languageCode == locale.languageCode) {
                  return deviceLocale;
                }
              }
              return supportedLocales.first;
            },
            title: 'Shahim',
            theme: isDarkMode ? darkTheme : lightTheme,
            routerConfig: appRouter.config(),
          );
        }));
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console

Launching lib/main_development.dart on Pixel 6 in debug mode...
Building with Flutter multidex support enabled.
✓  Built build/app/outputs/flutter-apk/app-development-debug.apk.
D/FlutterGeolocator(22546): Attaching Geolocator to activity
D/FlutterGeolocator(22546): Creating service.
D/FlutterGeolocator(22546): Binding to location service.
D/FlutterLocationService(22546): Creating service.
D/FlutterLocationService(22546): Binding to location service.
D/FlutterGeolocator(22546): Geolocator foreground service connected
D/FlutterGeolocator(22546): Initializing Geolocator services
D/FlutterGeolocator(22546): Flutter engine connected. Connected engine count 1
21
D/VRI[MainActivity](22546): Cancelling draw. cancelDueToPreDrawListener=true cancelDueToSync=false
Connecting to VM Service at ws://127.0.0.1:34037/-b7y21oR2tM=/ws
200
D/VRI[MainActivity](22546): Cancelling draw. cancelDueToPreDrawListener=true cancelDueToSync=false
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console

## flutter doctor

```
[✓] Flutter (Channel stable, 3.16.7, on Ubuntu 23.10 6.5.0-14-generic, locale en_US.UTF-8)
    • Flutter version 3.16.7 on channel stable at /home/jadaboawwad/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ef1af02aea (5 days ago), 2024-01-11 15:19:26 -0600
    • Engine revision 4a585b7929
    • Dart version 3.2.4
    • DevTools version 2.28.5

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/jadaboawwad/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /home/jadaboawwad/Android/Sdk
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 16.0.6 (15)
    • cmake version 3.27.4
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[✓] Android Studio (version 2022.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /opt/android-studio
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.85.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.81.20231227

[✓] Connected device (3 available)
    • Pixel 6 (mobile) • 23281FDF6000R0 • android-arm64  • Android 14 (API 34)
    • Linux (desktop)  • linux          • linux-x64      • Ubuntu 23.10 6.5.0-14-generic
    • Chrome (web)     • chrome         • web-javascript • Google Chrome 120.0.6099.129

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```

</details>

**Comment by darshankawar** [comment]
@Jadaboawwad 
Looks like it is similar to https://github.com/flutter/flutter/issues/137163 which has been fixed recently (2 weeks ago) but may not be in stable yet. Can you re-run your scenario after switching to latest master and see if you still get same issue or not ?

`flutter channel master`
`flutter upgrade`
