### ISSUE TITLE
Production builds of Gallery app for iOS drives animations at 60fps

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1416]
Once a developer has built a production-ready version of their IPA, the app should drive all animations at a smooth 60fps (jank-free).

**Comment by eseidelGoogle** [comment]
This seems like a very large topic, likely requiring sub-bugs.  I recommend we change this to target our codelab app instead of a nebulous developer app.  My understanding is that the game is consistently 60hz on iOS today.  We don't have any automated numbers for our apps to verify that however.

**Comment by sethladd** [comment]
Also, we can use the gallery to help measure and track this.

**Comment by davenotik** [comment]
Curious, what's the "astounding performance" label mean? It sounds like a good thing. :smile_cat:

**Comment by eseidelGoogle** [comment]
This bug is non-actionable.  I don't know how we would resolve it.  Presumably through automated testing of the Gallery app?  @yjbanov mentioned he's interested in working on our performance story, but it's not clear that will happen before the Hackathon.

I guess I'll just change the title to reflect that it's the Gallery app we're after here, and we can resolve it through manual testing.

**Comment by davenotik** [comment]
What hackathon? :smile:

**Comment by sethladd** [comment]
@davenotik just an internal mini-hackathon to test our tools with some of our friendly internal teams. Looking forward to doing something more public in the future.

**Comment by jimbeveridge** [comment]
Can you point me to documentation for flags we should (or shouldn't) use for performance testing? For example, I believe that some debug options are turned on by default with `flutter start`?

**Comment by sethladd** [comment]
If you want to do performance testing, definitely run with `flutter start --no-checked` to disable checked mode and asserts.

**Comment by sethladd** [comment]
I doubt we're going to make much progress on this between now and the code lab. Suggest we ensure we're comfortable understanding the performance of a production iOS build, so we can document expectations accordingly.

**Comment by eseidelGoogle** [comment]
We can't really make progress on this until https://github.com/flutter/flutter/issues/2177. Punting from hackathon.

**Comment by sethladd** [comment]
We're going to split this up into individual issues.
