### ISSUE TITLE
Error (Xcode): Framework not found camera

### ISSUE THREAD

**Issue by RobQuatela** [flutter/flutter#141681]
### Steps to reproduce

I don't believe this is a bug, but I am having problems with running on iOS simulator. When I attempt to run, terminal says that the "camera" framework cannot be found.

### Actual results

I am unable to compile the code due to this iOS error. I created another flutter app from scratch and was able to successfully run it on this same iOS simulator. I have been looking for a while now as to how these "Framework not found" issues can be resolved, but I have had no luck. So far, the only error I have received on this is "framework not found camera". I have removed pods and reinstalled, upgraded pods to 1.12 as well.

### Logs

<details open>
<summary>Logs</summary>

```

```

</details>
[flutter_verbose.txt](https://github.com/flutter/flutter/files/13962366/flutter_verbose.txt)

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.16.7, on macOS 13.4.1 22F770820d darwin-x64, locale es-US)
    • Flutter version 3.16.7 on channel stable at /Users/robquatela/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ef1af02aea (6 days ago), 2024-01-11 15:19:26 -0600
    • Engine revision 4a585b7929
    • Dart version 3.2.4
    • DevTools version 2.28.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/robquatela/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Users/robquatela/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/robquatela/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.1)
    • IntelliJ at /Users/robquatela/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/223.8214.52/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
    • IntelliJ at /Users/robquatela/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/202.7660.26/IntelliJ IDEA.app
    • Flutter plugin version 50.0
    • Dart plugin version 202.7319.5

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] VS Code (version 1.75.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554                        • android-x64    • Android 14 (API 34) (emulator)
    • iPhone 14 Pro Max (mobile)   • 60124482-033B-42B3-8ED9-477556D826D0 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)              • macos                                • darwin-x64     • macOS 13.4.1 22F770820d darwin-x64
    • Chrome (web)                 • chrome                               • web-javascript • Google Chrome 120.0.6099.216

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by dam-ease** [comment]
Hello @RobQuatela.
Thanks for filing this.

> I created another flutter app from scratch and was able to successfully run it on this same iOS simulator.

Can you try running the existing app on another iOS Simulator or a real device if available, also not sure if the camera package is being used in this case, if so when the package is removed from the existing app, does this error also persist?
Kindly try these out

**Comment by RobQuatela** [comment]
Hey, thank you for your response! 

I just ran these tests. I attempted to run the project on a different simulator, but the same error occurred. Then, I removed the camera package and it's dependencies and attempted to run but also received the same error. For reference, these are the packages that we were using for camera ability that I removed

`camera: ^0.10.5+9
  path_provider: ^2.1.1
  path: ^1.8.3`

**Comment by dam-ease** [comment]
Thanks for your response @RobQuatela.
Can you share the full `flutter run -v` when the camera and related packages are removed?
Also does this reproduce only with this project, can you try this with a newly created flutter project?

**Comment by RobQuatela** [comment]
OK, just ran that and attached the result of the main project having issues. When I create a new project with the exact same dependencies, it is able to run on the same simulator
[flutterrun.txt](https://github.com/flutter/flutter/files/13976015/flutterrun.txt)

**Comment by dam-ease** [comment]
> The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.4.99.

Saw this in the logs shared, can you please set this to see if it helps in this case?

**Comment by RobQuatela** [comment]
Thank you for this. I think we are getting closer! I updated the PodFile with this install script

`post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end`

And now, when I try to run, I receive this error

`Lexical or Preprocessor Issue (Xcode): 'Flutter/Flutter.h' file not found
/Users/robquatela/.pub-cache/hosted/pub.dev/package_info_plus-5.0.1/ios/Classes/FPPPackageInfoPlusPlugin.h:4:8`

I am continuing to lookup now why this may be happening

**Comment by dam-ease** [comment]
You can check out this SO [Thread](https://stackoverflow.com/questions/64973346/error-flutter-flutter-h-file-not-found-when-flutter-run-on-ios) for possible solutions.

**Comment by RobQuatela** [comment]
Thank you again for your help @dam-ease! I believe everything is now working like it should be.
