### ISSUE TITLE
[RFW] Improve the developer ergonomics

### ISSUE THREAD

**Issue by tugorez** [flutter/flutter#141666]
## Problem
Currently RFW allows developers to write

```
widget root = Container(
  color: 0xFFFFEBEE, // red[50],
  child: Icon(
     icon: 0xe2a0, // flutter_dash
     fontFamily: 'MaterialIcon',
  ), 
);
```

which is awesome but feels like a downgrade coming from flutter where one can write
```dart
Container(
  color: Colors.red[50],
  child: Icon(icon: Icons.flutter_dash),
)
```

## Proposals
I have a few ideas 

### Proposal 1: Extend the material library
Extend widgets to support something like
```
Container(
  color: 'red500',
  // or
  color: {
     name: 'red',
     intensity: '500',
  },
  child: Icon(name: 'flutter_dash'),
), 
```
of course the local widgets will have to now infer user intent, if a valid "string" (like "red" or "red500") is passed do the right mapping; otherwise (a number is passed) use it. A similar treatment should be applied to the Icon param.

### Proposal 2: Provide argument encoders that can be passed as data

Similar to the argument decoders API we can create its encoder counterpart

```dart
class ArgumentEncoder {
   // returns red500 or red
   static String color(double number);
  
   // returns { color: 'red', intensity: 500 },
   static DynamicMap color(double number); // returns red500 or red

   static DynamicMap icon(IconData iconData) => <String, Object?> {
      codePoint: iconData.codePoint,
      fontFamily: iconData.fontFamily,
   };
}
```

So that it can be used as follows

```dart
final data = DynamicContent()
  ..update('icons', {
    'flutter_dash': ArgumentEncoder.icon(Icons.flutter_dash),
  })
  ..update('colors', {
    'red': ArgumentEncoder.color(Colors.red),
    'red500': ArgumentEncoder.color(Colors.red[500]),
  });

const rfw = '''
  widget root = Container(
    color: data.colors.red,
    child: Icon(icon: data.icons.flutter_dash),
  );
''';
```
### Proposal 3: Introduce the `colors` and `icons` identifiers.
Similar to args and state we can introduce new identifiers and give developers control over what to put there.
```
Color(
   color: colors.red,
   child: Icon(icon: icons.flutter_dash),
); 
```

and in dart

```dart
final runtime = Runtime..updateColors('colors', <String, double>{
  'red': Colors.red,
  'red500': Colors.red[500],
});
```
### Proposal 4: Allow data definitions and library aliases to avoid duplication and maximize reuse
```
// library theme.rfwtxt
define colors = {
  'red': 0xFFFFEBEE,
};

// library main.rfwtxt
import theme as theme;

widget Foo = Container(color: theme.colors);
```

**Comment by Hixie** [comment]
`data.colors.red.500` should work today using data references, I think, without needing anything in package:rfw.

That said if the goal is easier authoring, maybe the right solution is just to create a new format (there's been some discussion in #hackers-rfw of a dart-like format) that can then be compiled to the binary form, which is never sent to the client. The client shouldn't have to know about things like `Colors`, that kind of authoring detail should not have performance implications on the client IMHO.

**Comment by tugorez** [comment]
Sorry I should have stated my proposal more clearly. Color and IconData just where examples and each subheader in the issue refers to a different proposal to tackle the same problem. What I get from your comment is that you prefer options that don't have meaningful changes on the language nor the runtime. In that case would you be ok with adding a `ArgumentEncoder` helper?

**Comment by Hixie** [comment]
What I was trying to convey is I don't think this needs a change to package:rfw at all. If someone wants to use `data.colors.red.500` they can already do that in their client by adding a root key to their DynamicContent objects called "colors" that contains the various colors and shades they want to support. Personally I would recommend doing that entirely on the server and sending an integer to the client rather than an enum-like value. The only time I think it'd be better to send an enum-like value is to identify a color from a scheme, e.g. to say "use the app's background color" or "use the branding highlight color" or whatever, and that can already be done using `data`.
