### ISSUE TITLE
url_launcher not resuming my app from Firefox

### ISSUE THREAD

**Issue by markbeij** [flutter/flutter#141601]
### Steps to reproduce

1. Configure Firefox as the default browser
2. From my Flutter app open a browser to a login page
3. Login. The page will redirect to my app
4. My app should resume, but it never does

Configure Chrome as the default browser and all goes well

### Expected results

My app resumes

```console
[log] appstate = inactive
[log] appstate = hidden
[log] appstate = paused
[log] appstate = hidden
[log] appstate = inactive
[log] appstate = resumed
```

### Actual results

My app restarts
```console
[log] appstate = inactive
[log] appstate = hidden
[log] appstate = paused
```

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'dart:developer';

import 'package:app_links/app_links.dart';
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> with WidgetsBindingObserver {
  final appLinks = AppLinks();

  int _counter = 0;
  String? _incomingUrl;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  void _incrementCounter() async {
    final url = Uri.parse('https://tijdelijkdingetje.z6.web.core.windows.net/');

    await launchUrl(
      url,
      mode: LaunchMode.inAppBrowserView,
    );

    final result = await appLinks.uriLinkStream.first;

    setState(() {
      _incomingUrl = result.toString();
      _counter++;
    });
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    log('appstate = ${state.name}');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text('You have pushed the button this many times:'),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
            if (_incomingUrl != null) Text('Coming from: $_incomingUrl'),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.link),
      ),
    );
  }
}
```

AndroidManifest.xml
```xml
<intent-filter android:autoVerify="true">
    <action android:name="android.intent.action.VIEW"/>
    <category android:name="android.intent.category.DEFAULT"/>
    <category android:name="android.intent.category.BROWSABLE"/>
    <data android:host="foo" android:scheme="sample" />
</intent-filter>
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Chrome (expected behavior)
![chrome](https://github.com/flutter/flutter/assets/20302465/1f57235a-592c-4da2-afda-2e846987dd51)

Firefox
![firefox](https://github.com/flutter/flutter/assets/20302465/f921fbda-b0a4-4f52-8456-5b93af3cd699)
</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.16.3, on Microsoft Windows [Version 10.0.22621.2861], locale nl-NL)
    • Flutter version 3.16.3 on channel stable at C:\DEV\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0366e0a3f (6 weeks ago), 2023-12-05 19:46:39 -0800
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\mark\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.30)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.34031.81
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.85.1)
    • VS Code at C:\Users\mark\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.78.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5556 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.2861]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 120.0.6099.131
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 120.0.2210.133

[√] Network resources
    • All expected network resources are available.

• No issues found!```

</details>

**Comment by stuartmorgan** [comment]
All `url_launcher` does here is request launching the relevant intent, which is working here as evidenced by the browser view opening. If once opened, the Firefox-provided view does not behave the way you would expect, you would need to report that to the Firefox developers, as `url_launcher` is no longer involved.

**Comment by markbeij** [comment]
I doubt if it's correct to state that there is nothing to do with the Intent. I'm not an expert in Android development, but as far as I can tell, the plugin flutter_appauth works with the same intent.
I'd appreciate to reopen this issue and check this out al bit further.
Thank you.

**Comment by stuartmorgan** [comment]
> I'm not an expert in Android development, but as far as I can tell, the plugin flutter_appauth works with the same intent.

Given that there are no references to `CustomTabsIntent` anywhere in that package's repository, I'm not sure how you came to the conclusion that it is using the same intent.

> I'd appreciate to reopen this issue and check this out al bit further.

I explained above why the difference in behavior you described cannot be within the scope of `url_launcher`. There is nothing further for us to check here based on what you have described.

If you have specific technical details about an issue in `url_launcher`'s Android implementation, please provide it; simply asserting that you believe that we are wrong about how our own plugin works is not constructive.

**Comment by markbeij** [comment]
Thanks for your swift replies @stuartmorgan, I really appreciate it!

It's used via AppAuth-Android, see: https://github.com/openid/AppAuth-Android/tree/master @stuartmorgan

**Comment by markbeij** [comment]
Found this [issue](https://github.com/flutter/flutter/issues/56690#issuecomment-627739647), with the workaround from @noelmansour, which 
In UrlLauncher.java, I added `customTabsIntent.intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);` in `openCustomTab(..)`. Works like a charm! @stuartmorgan, can you reopen the issue?

**Comment by stuartmorgan** [comment]
> I added `customTabsIntent.intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);` in `openCustomTab(..)`

According to the docs for that flag:

>> This flag is generally used by activities that want to present a "launcher" style behavior: they give the user a list of separate things that can be done, which otherwise run completely independently of the activity launching them.

This does not sound like how `url_launcher` should behave, so unless I'm misunderstanding the behavior this is describing it seems very unlikely that we would want to change this.

Re-opening for the `team-android` to evaluate whether this is something we would want to expose as an option.

**Comment by reidbaker** [comment]
Android team looked at this and we do not think we want to expose that option at this time.
