### ISSUE TITLE
Rebalance VM bots between try v.s. prod and Linux v.s. Windows

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#141693]
For recent cycle (01/01/2024-01/14/2024), 95th% queue time for Linux v.s. Windows and try v.s. prod is:
Linux in try: 4.75 mins
Windows in try: 2.17 mins
Linux in prod: 0.23 mins
Windows in prod: 0.17 mins

We should evaluate/balance the bot capacity to reduce the try queue time.

**Comment by keyonghan** [comment]
@yusuf-goog Do you think we can move like 10 linux bots from prod to try & move 10 windows bots from prod to try? We need to monitor the queue time and may also consider moving some windows capacity to Linux.

**Comment by yusuf-goog** [comment]
Note: after speaking to @keyonghan we are moving 5 win bots and 10 linux: https://chrome-internal-review.googlesource.com/c/infradata/config/+/6882359
