### ISSUE TITLE
Error: Type 'DecoderCallback' not found.     DecoderCallback decode, // ignore: deprecated_member_use

### ISSUE THREAD

**Issue by githubliuqi** [flutter/flutter#141603]
### Steps to reproduce

![image](https://github.com/flutter/flutter/assets/8850754/d9a50092-8068-4573-9ec8-7089bf36a642)

../../../.pub-cache/hosted/pub.dev/photo_manager-2.8.1/lib/src/internal/image_provider.dart:71:5: Error: Type 'DecoderCallback' not found.
    DecoderCallback decode, // ignore: deprecated_member_use
    ^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/photo_manager-2.8.1/lib/src/internal/image_provider.dart:96:5: Error: Type 'DecoderCallback' not found.
    DecoderCallback decode, // ignore: deprecated_member_use
    ^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/photo_manager-2.8.1/lib/src/internal/image_provider.dart:71:5: Error: 'DecoderCallback' isn't a type.
    DecoderCallback decode, // ignore: deprecated_member_use
    ^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/photo_manager-2.8.1/lib/src/internal/image_provider.dart:96:5: Error: 'DecoderCallback' isn't a type.
    DecoderCallback decode, // ignore: deprecated_member_use
    ^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

### Expected results

build success!

### Actual results

../../../.pub-cache/hosted/pub.dev/photo_manager-2.8.1/lib/src/internal/image_provider.dart:96:5: Error: 'DecoderCallback' isn't a type.
    DecoderCallback decode, // ignore: deprecated_member_use

### Code sample

![image](https://github.com/flutter/flutter/assets/8850754/1d9ada83-970f-4dfb-a290-2fd4c0306931)

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by githubliuqi** [comment]
flutter 3.16.7

**Comment by bartekpacia** [comment]
This looks like a problem with the `photo_manager` plugin, which is a 3rd party dependency not maintained by the Flutter Team.

Looks like you're facing this issue: https://github.com/fluttercandies/flutter_photo_manager/issues/1021
