### ISSUE TITLE
[RFW] Refactor the tokenizer and parser

### ISSUE THREAD

**Issue by tugorez** [flutter/flutter#141665]
Ideally I'd like a change like https://github.com/flutter/flutter/issues/141658 to be broken in multiple commits:

1. To add support for it in the tokenizer.
2. To add support for it in the AST.
3. To add support for it in the parser.
4. To add support for it in the runtime.

Ideally `1)` and `2)` can be worked in parallel and then `3)` and `4)` in sequence. Each step should be implemented/tested without any dependencies in the following one. With the current implementation I have to build support for `1)`, `2)` and `3)` in the same commit. 

My proposal would be to be break the existing `dart` subpackage into `tokenizer`, `ast` and `parser`  and have those tested independently.

**Comment by tugorez** [comment]
The following changes (part of `1`) can't be tested in isolation https://github.com/flutter/packages/pull/5907

**Comment by Hixie** [comment]
So far changes for this kind of thing have been very small and are easily done in one PR, can you elaborate on the problem this is trying to solve?

**Comment by tugorez** [comment]
Great question! A simple example would be https://github.com/flutter/packages/pull/5907/files#diff-18889bf13c05c8ab54d3e7ea03591c387ba66ea3dc181b2e02b5b9f539b27695. I can't test that change in isolation. Granted, not a big deal but imagine a more complex RFW feature that requires changing the tokenizer/parser. Ideally you'd like to test these changes at each layer they change.

**Comment by Hixie** [comment]
The tokens are an implementation detail, I wouldn't recommend testing things at that layer. It just makes refactoring harder later (because you can't rely on any of the tests that rely on the implementation details of what you're refactoring). Currently for parsing tests we just test that the parser plus stringification round-trips as expected, or that it generates the appropriate tree structure, or similar, and then have end-to-end tests that verify that it all works as expected.

**Comment by tugorez** [comment]
> It just makes refactoring harder later (because you can't rely on any of the tests that rely on the implementation details of what you're refactoring). 

Are there well known issues that you're aware of? It seems like teams behind popular languages like go[1] and dart[2] test each layer of their compiler individually, in addition to testing everything end to end, which makes sense IMO:  Imagine having a complex feature that requires dozens of new tokens. The PR for that would be massive. BTW I'm not saying we should publish each individual component as a package, we can keep everything inside rfw/lib/src/dart but still have each layer tested. It (almost) never hurts having more tests IMHO.  

I can also understand if you don't want to overengineer features atm; but the alternative would be to wait until a complex feature is needed to refactor things. 

[1]: https://github.com/golang/go/blob/8e658eee9c7a67a8a79a8308695920ac9917566c/src/text/template/parse/lex_test.go#L58
[2]: https://github.com/dart-lang/pana/blob/master/test/tokenizer_test.dart
[3]: https://github.com/dart-lang/html/blob/06bc148600b1d1a70f2256bdf788c213f1f60f55/test/tokenizer_test.dart

**Comment by Hixie** [comment]
Tests are a critical tool to prevent regressions. However, they are not free: they require maintenance, they take time in CI, and they can slow down development (e.g. tests that test internals are going to require more work when changing those internals; flaky tests are also a huge source of development cost).

RFW is currently a very small project (it has one unpaid volunteer working on it a few hours a month). In contrast, Go and Dart are fully funded large projects with dozens of engineers. Correspondingly, their cost and risk budgets will be different than ours on RFW.

Now, if there's specific areas where testing the tokenizer directly would bring value we can't get in a cheaper way then we should of course do it. However, we should do that when there's a real benefit to doing it, not just on principle.

Regarding the original proposal, the rfwtxt tokenizer, rfwtxt parser, and the AST already are split. The AST is in `model.dart`, the tokenizer is the first ~2000 lines of `text.dart` (`_tokenize` and a few support classes), and the parser is the rest of `text.dart`.
