### ISSUE TITLE
[Impeller] Implement mipmap generation for backdrop filters for opengles

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#141732]
This makes blurs look nicer.  It was disabled out of caution to get the feature landed for Metal only after vulkan didn't work.  It might work for opengles though.

See TODO in `impeller/entity/entity_pass.cc`

**Comment by jonahwilliams** [comment]
@gaaclarke was there a problem observed in OpenGL?

**Comment by gaaclarke** [comment]
With out tests in CI we can verify it doesn't crash at least.  It would be nice to get visual confirmation that it looks good too with some manual testing.

**Comment by jonahwilliams** [comment]
Since we're not using mipmaps for backdrop filters anymore, I'm going to close this issue.
