### ISSUE TITLE
GPUTracerVK is expensive, and is doing work unconditionally

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#141788]
Shows up as taking significant time for creating/destroying query pools in profiles, and much of its usage seems unguarded by `IMPELLER_DEBUG`.

We may want to turn this off for everything but devicelab, however due to its own overhead I'm not sure how useful it is for the devicelab at this point. @jonahwilliams wdyt?

**Comment by dnfield** [comment]
<img width="1703" alt="image" src="https://github.com/flutter/flutter/assets/8620741/19ca24bf-b378-4c12-a988-49ff9c72cbe4">

**Comment by jonahwilliams** [comment]
IMPELLER_DEBUG switches enabled to false, which in theory should mostly no-op in release builds. But we should 1) reduce the overhead for our own benchmarks and 2) make this function op-in for now.
