### ISSUE TITLE
[Impeller] Consider caching or at least trying to reuse VkFramebuffer and RenderPass objects

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#141750]
Per https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#renderpass-compatibility, we can reuse the framebuffer as long as the render passes are compatible (and the width/height haven't changed presumably).

I suspect for many frames, the previous frame's framebuffer is reusable.

We could also try to come up with a caching mechanism if this isn't sufficient.

Motivation is an internal trace of an app on a Pixel 5 device, which shows significant time spent in vkCreateFramebuffer:

<img width="622" alt="image" src="https://github.com/flutter/flutter/assets/8620741/9f98f35f-0220-4755-b89f-8bbdb85f2f06">

**Comment by jonahwilliams** [comment]
There are a lot of caveats with framebuffer caching, @gaaclarke worked on this a bit last year. Essentially everything, down to the image views / images needs to be the same. They may not be safe to use until fences have been signaled. The management seems quite difficult.

Though rather than some sort of uniform caching system, we might consider caching the framebuffer for the onscreen render pass. As that should be a lot more static - and since we know the swapchain images invalidation cycle, it could be an easier first attempt/

**Comment by dnfield** [comment]
My first thought was for the onscreen render pass - I'm not sure how much sense it'll make to cache offscreen passes that could be very different very frequently. 

I think it should be a somewhat simple experiment to cache an onscreen pass FBO and see if it helps much.

**Comment by jonahwilliams** [comment]
Also worth noting that I believe the pixel 5 is an adreno whereas the 7s we have are arm, so the driver might have different performance characteristics

**Comment by dnfield** [comment]
Rough idea:

- Make SwapchainImageVK store some kind of `vk::Framebuffer` and `vk::FramebufferCreateInfo`.
- When we create an RT for the swapchain image, put the framebuffer and info on it.
- When we go to create the FBO for the rt, check if the FBO it has is compatible. If so, use it, if not, create new.
- When we go to present the swapchain image, store the FBO and create info back on the swapchain image.

I'm not quite sure if this will work or how to do it cleanly yet (putting vulkan specific stuff on `RenderTarget` seems not quite right to me).

**Comment by jonahwilliams** [comment]
You might consider storing them on the TextureSource used by the swapchain images, which we have to access in the render_pass constructor. Then we don't leak vulkan specific objects.

**Comment by dnfield** [comment]
A similar trace on a Mali GPU (pixel 7 pro) shows VkFramebuffer creation as taking _very_ little time.

**Comment by jonahwilliams** [comment]
Here is a fun one:

More than half of CPU time is render pass creation. I have some ideas on how to fix this everywhere, though I think I've provied it can work for onscreen with: https://github.com/flutter/engine/pull/50142

<img width="1728" alt="Screenshot 2024-01-29 at 5 34 07 PM" src="https://github.com/flutter/flutter/assets/8975114/6c82dd3f-5766-4ab7-a863-c2d4c91f0900">

**Comment by jonahwilliams** [comment]
This still needs to be done for onscreens.

**Comment by Jasguerrero** [comment]
Sorry about the closing idk why github decided to close it after I did a rebase on my personal fork!?

**Comment by jonahwilliams** [comment]
No worries, GitHub is weird
