### ISSUE TITLE
Android setup links from the tool are broken

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter#141772]
Links output by the tool (e.g. by `flutter doctor`) ending in "#android-setup", such as https://flutter.dev/docs/get-started/install/windows#android-setup are broken because of changes in the Flutter installation documentation structure.

cc @parlough

**Comment by parlough** [comment]
Thanks for reporting this! I'll work on something to keep these old links working for now and then likely create some sturdier redirects that the tool can use.
