### ISSUE TITLE
Adding a generic SnapScrollPhysics to the framework

### ISSUE THREAD

**Issue by cjunmokim** [flutter/flutter#14175]
Hello,

I have a list of scrollable items that I want to be able to scroll and have the items snap into place afterwards.
Here is a video I found that demonstrates the snapping behavior I want after scrolls.
https://youtu.be/cUGyvYjGkKA?t=13

I know Flutter provides PageScrollPhysics that implements this snapping behavior for scrolling between pages, but there is not one for a list of scrollable items.

Do you think it would be worthwhile to support this from the framework?

**Comment by xster** [comment]
We're making one that might be more or less what you would like.

You could probably just use the non-iOS skinned underlaying components of it once it's in. 

You can also just use the physics part of it by itself.

**Comment by xster** [comment]
Consider using https://docs.flutter.io/flutter/widgets/FixedExtentScrollPhysics-class.html
