### ISSUE TITLE
Keyboard error

### ISSUE THREAD

**Issue by codebryanc** [flutter/flutter#141714]
### Steps to reproduce

I have one TextField whit this method implemented onChanged and when use the input the issue appears 

### Expected results

_AssertionError ('package:flutter/src/services/hardware_keyboard.dart': Failed assertion: line 471 pos 16: '_pressedKeys.containsKey(event.physicalKey)': A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#f1a79(physicalKey: PhysicalKeyboardKey#80fe7(usbHidUsage: "0x00070006", debugName: "Key C"), logicalKey: LogicalKeyboardKey#18653(keyId: "0x00000063", keyLabel: "C", debugName: "Key C"), character: null, timeStamp: 6:54:33.412902))

### Actual results

**_AssertionError ('package:flutter/src/services/hardware_keyboard.dart': Failed assertion: line 471 pos 16: '_pressedKeys.containsKey(event.physicalKey)': A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#f1a79(physicalKey: PhysicalKeyboardKey#80fe7(usbHidUsage: "0x00070006", debugName: "Key C"), logicalKey: LogicalKeyboardKey#18653(keyId: "0x00000063", keyLabel: "C", debugName: "Key C"), character: null, timeStamp: 6:54:33.412902))**

### Code sample

decoration: InputDecoration(
                    hintText: LocalizationService().getResource('workportal-widget-search') + "...",
                    filled: true,
                    fillColor: Colors.white,
                    contentPadding: const EdgeInsets.symmetric(vertical: 8.0, horizontal: 8.0),                  
                    border: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(10),
                      borderSide: BorderSide.none,
                    ),
                    suffixIcon: Visibility(
                      visible: isSearchEmpty == false,
                      child: GestureDetector(
                        onTap: () {
                          // Clear search in Bloc
                          context.read<SearchBloc>().add(const DoSerachInformation(inputValue: ""));
                          
                          // UX clear info
                          _textSearchController.clear();
                        },
                        child: const Icon(Icons.cancel, color: AppTheme.silverColor, size: 20.0),
                      )
                    ),
                  ),
                  onChanged: (value) {
                      // save info in Bloc
                      context.read<SearchBloc>().add(DoSerachInformation(inputValue: value));
                  },
                  inputFormatters: [
                    FilteringTextInputFormatter.allow(
                      EnvironmentConfig.regexBySearchActivities
                    ),
                  ],
                ),
              ),

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment]
Hi @codebryanc 
When opening an issue, please try to provide all information indicated in the template so that we can address this issue properly (See bug issue template [here](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml))

More specifically, please provide the following information:
- A [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
- The output of `flutter doctor -v`
- Reproduction steps in detail (which keys did you press?) 
- Which environment did this issue happen in? (Android/iOS/Web/MacOS/Windows/Linux)
