### ISSUE TITLE
Dart roll blocked on building gen_snapshot for windows targeting android

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#141786]
Starting in https://github.com/flutter/engine/pull/49866

Guessing it's due to https://dart.googlesource.com/sdk.git/+/5230995e3a9905315dc5b97bd77f9a606e4f06a5

cc @alexmarkov

**Comment by alexmarkov** [comment]
Possible fix: https://dart-review.googlesource.com/c/sdk/+/347065.

@zanderso Is there any way to test it using Flutter CI before landing it in Dart SDK?

**Comment by zanderso** [comment]
I think we'd have to ask @whesse if the failing configuration is one that's supported by the monorepo builders.

**Comment by alexmarkov** [comment]
Fix landed in Dart SDK.
