### ISSUE TITLE
> **It seems this issues didn't happen anymore with:** This is also happening in latest version camera: ^0.10.5+9

### ISSUE THREAD

**Issue by KartikChauhan01** [flutter/flutter#141769]
> **It seems this issues didn't happen anymore with:**
> 
> Inspired by example and not the README https://raw.githubusercontent.com/flutter/plugins/master/packages/camera/example/lib/main.dart.
> 
> Code to fix issue.
> 
> ```
>   @override
>   void didChangeAppLifecycleState(AppLifecycleState state) {
>     // App state changed before we got the chance to initialize.
>     if (controller == null || !controller.value.isInitialized) {
>       return;
>     }
>     if (state == AppLifecycleState.inactive) {
>       controller?.dispose();
>     } else if (state == AppLifecycleState.resumed) {
>       if (controller != null) {
>         onNewCameraSelected(controller.description);
>       }
>     }
>   }
> ```

The link is broken, 

the method should be implement on the widget that calls the camera plugin

_Originally posted by @eliaweiss in https://github.com/flutter/flutter/issues/39109#issuecomment-784003875_

**Comment by darshankawar** [comment]
@KartikChauhan01 
Please don't use comments from other issues to file a new issue because it doesn't give clear details as what exactly the issue you are reporting.
Please use new issue template and fill out requested details so that we can address it properly.
Closing for now.
