### ISSUE TITLE
[flutter release] failed to install Xocde error on 3.19.1 beta branch

### ISSUE THREAD

**Issue by XilaiZhang** [flutter/flutter#141724]
Feel free to dedupe this against an infra issue if already exist.

context: https://chat.google.com/room/AAAAc_4rqiI/z-rjx6xh4cE

engine post submit builds are failing on beta branch due to failure to install Xcode. [sample failure](https://ci.chromium.org/ui/p/dart-internal/builders/flutter/Mac%20Production%20Engine%20Drone/9565/overview)

**Comment by XilaiZhang** [comment]
affected by the cache state of the bot, a cherry pick might be needed

**Comment by godofredoc** [comment]
The xcode installation is from the 12 when the dart-internal service account didn't have access to the xcode packages. That issue has been fixed since then.
