### ISSUE TITLE
Upgrade devicelab flutter-devicelab-mac-5 to macOS 14.x

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#141736]
### Type of Request

infra task

### Infrastructure Environment

devicelab

### What is happening?

@kentnguyen99 please upgrade flutter-devicelab-mac-5 to macOS 14.x

### Steps to reproduce

Step 1:
Step 2:
..
Step n:

### Expected results

I expect to see X when Y is finished.

**Comment by kentnguyen99** [comment]
Upgrading MacOS 14.x on mac-5 has been completed and machine is ready for use.
