### ISSUE TITLE
Drone task not using the Mac cpu dimension

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#141717]
### Type of Request

bug

### Infrastructure Environment

LUCI

### What is happening?

```yml
  - name: Mac mac_host_engine
...
    properties:
...
      cpu: arm64
```
`mac_host_engine` passes in `cpu: arm64`
https://github.com/flutter/engine/blob/c16710721f7c18121a70650bcebc4a96a03353ae/.ci.yaml#L376

However this drone task shows the property, but ran on an x86 Mac and :
https://ci.chromium.org/p/flutter/builders/try/Mac%20mac_host_engine/24484
https://ci.chromium.org/p/flutter/builders/try/Mac%20Engine%20Drone/638932

Bot: https://chromium-swarm.appspot.com/bot?id=build874-m9

### Expected results

I expect the drones to use properties passed in, or to have some way to express the drone properties.

**Comment by keyonghan** [comment]
This is expected as the drone dimension is defined from builder.json: https://github.com/flutter/engine/blob/c16710721f7c18121a70650bcebc4a96a03353ae/ci/builders/mac_host_engine.json#L19

BTW: @godofredoc is working to remove top level dimensions.
