### ISSUE TITLE
[pigeon] Improve Swift generator output style

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#141799]
Running `swift-format` over the Pigeon-generated output turned up a bunch of places where our generator output doesn't match formatted output. While we don't need it to be perfectly formatted, we do generally want to match expected style in the initial generation. And in a number of cases, the output is distinctly non-idiomatic, like parens in `if` statements.

Some things to fix based on initial skim (but when doing this we should iterate a bit with the autoformatter and try to fix anything that's relatively straightforward):
- `if` statements should not use `()`s.
- `case`s should not be indented relative to the `switch`
- Conditional imports should be indented
- Multi-line arrays should use trailing commas
- Named params should have a space after `:`, which is missing in some places

**Comment by jmagman** [comment]
These are good suggestions to make the generated code more idiomatic.  However, should the pigeon generated files have `// swift-format-ignore-file` at the top so swift-format doesn't run on generated files?  That would be better for developers with different versions of swift-format locally or in CI than we have running in our CI.

**Comment by stuartmorgan** [comment]
> However, should the pigeon generated files also have [`// swift-format-ignore-file`](https://github.com/apple/swift-format/blob/main/Documentation/IgnoringSource.md#ignore-a-file) at the top so swift-format doesn't run on generated files? That would be better for developers with different versions of swift-format locally or in CI than we have [running in our CI](https://github.com/flutter/flutter/issues/41129).

Well, if someone has a different version of swift-format than we do they will have an issue with our non-generated code too.

We could opt generated code out of code formatting in general in our CI, but if it's the kind of generation where we check in the results I would rather have it formatted than not since it means we're potentially reading it. E.g., we often use the generated files in the Pigeon tests as important parts of reviewing generator changes, since it's much easier to reason about the diffs to the actual output in many cases, and having those be formatted makes that easier.

**Comment by stuartmorgan** [comment]
(And developers who want that in their own generated code should be able to just put that line in a copyright header, and get it automatically.)
