### ISSUE TITLE
Generate a production-ready IPA from a single command

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1417]
A developer has tested and optimized their app. They are ready for to release it for production. They use a single command (such as `flutter build ipa`). This generates a .ipa file ready to be uploaded to the store.

**Comment by sethladd** [comment]
For the hackathon, it will be sufficient to use Xcode for this. While it would be great to get a CLI for this (thus, making it something we can tool easily), it's not absolutely required for the hackathon.

**Comment by chinmaygarde** [comment]
The current instructions are at https://docs.google.com/a/google.com/document/d/1ii94IoGA-34t9lrqCBDeT5jKKZlPSwAVI14O5IvSvAs/edit?usp=sharing

**Comment by sethladd** [comment]
Thanks for writing this up! This doc doesn't seem publicly accessible.

**Comment by eseidelGoogle** [comment]
It looks like this is possible from teh command line:
http://stackoverflow.com/questions/2664885/xcode-build-and-archive-from-command-line

As soon as we have a `flutter ipa` command we can run it on the bots for every build.  We'll probably want to sign them with a bot-specific key, not sure.

**Comment by abarth** [comment]
`flutter build ios --release` exists and works now.

**Comment by eseidelGoogle** [comment]
I suspect build ios --release actually produces an app (uncompressed, installed on phone) not an ipa (compressed, plus store artwork, sent to store).  So yes, I think we should close this, but we'll need to open separate issues about how-to-publish-a-flutter app on iOS.

**Comment by neelu004** [comment]
Hi, I am using Mac and in cmd I am running flutter build ios this command which will generates my Runner.app in build folder. I want to know how to run this Runner.app in real iOS device.
Please suggest some solution.
Thanks!
