### ISSUE TITLE
Technical debt incurred in cross-repo changes too high

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#141734]
In 2022 this PR - https://github.com/flutter/flutter/pull/101101 - made a seemingly simple change: add a couple of extra debug properties to some layer classes. The PR included a test, yay!

Turns out the web implementation had a bug, stringifying `TileMode` as `TileMode.repeated` instead of just `repeated` like mobile does. Since the implementation is in the engine repo the author couldn't fix it in the PR, and instead added an `isBrowser` check and tested different outputs.

Fast-forward to January 2024. I'm fixing the web bug on the engine - https://github.com/flutter/engine/pull/49786. I didn't know we had a test in the framework testing this. I wrote the engine test, got the PR reviewed, and was mentally preparing to submit. Alas, the framework test failed because it expects a wrong behavior on the web. I guess my PR isn't landing today.

I'm now sending a PR to prepare the framework test - https://github.com/flutter/flutter/pull/141731. Alas, I missed another test that also needs to be prepared for the engine change. Send a PR for that too - https://github.com/flutter/flutter/pull/141700. Once these land, I can submit (hopefully) the engine PR.

Later, when the dust settles, I must remember to send framework PRs to remove the `kIsWeb`.

## Expected behavior

For such a small change, the original PR from 2022 (https://github.com/flutter/flutter/pull/101101), should've been able to just fix everything in one go and one code review.

## Actual behavior

Our setup put a barrier in front of the original contributor, pushing them to incur technical debt (probably not realizing it, since the simple `isBrowser` check doesn't feel too tech debty). The debt persisted until 2024. Now to fix it, I have to send 5 PRs, and request 5 separate code reviews. That seems like an unreasonable amount of effort for simple changes like this.

I feel like we can improve the situation considerably.

**Comment by yjbanov** [comment]
Ah, a new day, a fresh start! What next problem should I tackle today? Oh wait, I'm still fixing `toString`. I need to check if my engine PR rolled into the framework, so I can send a PR that finally fixes the tests for good. I guess this will be my morning, until meetings start.

**Comment by keyonghan** [comment]
Infra plans to support cross repository validation, and this is a good example why we need a cross-repo validation logic.

**Comment by matanlurey** [comment]
Another motivating example: https://github.com/flutter/flutter/issues/141973.

**Comment by yjbanov** [comment]
I'm not sure what "cross repository validation" includes. Here's the list of CUJs that need to be satisfied:

* A contributor easily _proposes_ an engine change and a framework fix for review.
* A contributor easily _reviews_ an engine change and a framework fix for review.
* A contributor easily _submits_ an engine change and a framework fix atomically as a single change.
* A contributor easily _finds_ the breaking change submitted to both the engine and the framework atomically.
* A contributor easily _reverts_ the breaking change submitted to both the engine and the framework atomically.

The "easily" here could mean some combination of "productively", "quickly", "simply". It should not feel like an inefficient, complicated, or lengthy process. It should not waste people's time.

Here I do not want to be prescriptive about _how_ to achieve the "easy". I'm sure multiple approaches are possible. However, to set the bar, I'd expect it to be on par with how we currently send a pull request to flutter/flutter alone. The existing process checks all the boxes. The existing process for making changes across more than one repo, or any one upstream repo (e.g. Dart, Engine, Skia), does not.

**Comment by dnfield** [comment]
The framework should never have depended on the broken implementation.

The framework should also in general avoid depending on the output of `toString` on objects that don't exist in the framework. For example, we used to have a problem where the tests for `ParagraphStyle.toString` were in the framework, and adding anything in the engine would break the framework/require a manual roll. But those tests really belonged in the engine.

If everything was in one repo, it would not have stopped a contributor from special casing web instead of fixing it at the source either - although it might have made your change take less time.

**Comment by yjbanov** [comment]
There's a difference between what "should" happen and what actually happens in practice. If we correct our setup, the path of least resistance will lie along the _right_ path. If someone "should" remember to do the right thing, then we already have failed (and we did fail, as this example demonstrates; there are many more like this).

**Comment by yjbanov** [comment]
Another example from my personal experience just this week. The following batch of PRs should have been just 1 PR:

- https://github.com/flutter/flutter/pull/149274
- https://github.com/flutter/engine/pull/53094
- Engine roll blocked, investigated by @chingjun 
- https://github.com/flutter/flutter/pull/149353
- TBD: the temporary code needs to be rolled back

**Comment by yjbanov** [comment]
Another occurrence: a [benchmark regressed](https://github.com/flutter/flutter/issues/151263) on an engine roll. The roll pulled [multiple engine commits](https://github.com/flutter/flutter/commit/ab4d422213491df7f41acbf0ffff51a608b7991b). All of them are upstream rolls themselves. It's hard to tell which change exactly caused the regression.

**Comment by yjbanov** [comment]
Another occurrence: an engine PR [got reverted](https://github.com/flutter/engine/pull/53679). The change could've been caught by a "Google Testing" shard. However, "Google Testing" doesn't support the engine repo, only the framework repo.

**Comment by yjbanov** [comment]
Another example:

- https://github.com/flutter/engine/pull/53622
- [Reverted](https://github.com/flutter/engine/pull/53629) because framework-side goldens failed and we don't run framework golden tests on engine changes
- Reland: https://github.com/flutter/engine/pull/53642
- [Reverted again](https://github.com/flutter/engine/pull/53705) because G3 tests failed and "Google Testing" is not implemented in the engine

As of this writing, the change hasn't landed yet (it's been 7 days since the first attempt to land).

**Comment by gnprice** [comment]
It sounds like in all three of the examples mentioned today, the key is that there were downstream checks that were affected by the engine changes but those checks don't currently run on engine PRs:
* benchmarks
* "Google Testing"
* framework goldens

If those checks did run on engine PRs, then I think the experience would have been exactly on par with making a change in the framework repo.

For the original example, and the one from May 30 above, running downstream checks on engine PRs would have significantly mitigated things — there'd still be more than one PR, but there'd be fewer of them. And the frustration from having a PR land but then have to be reverted for downstream reasons would be much less frequent (though not eliminated, as even flutter/flutter PRs experience the same thing when Google-internal postsubmit tests fail).

So probably a good actionable thing to try to do here, which would greatly improve the situation, would be to make those downstream checks run on engine PRs. In fact that's really probably three (or more?) separate actionable things to do, one for each check — each of which would improve things independent of the others.

**Comment by yjbanov** [comment]
I agree that adding downstream checks would improve things slightly. However, a few things make me uneasy about that path:

1. The engine and the framework continue being desynchronized from each other. We'd be running tests against some [engine revision, framework revision] tuple that doesn't ship to users. The engine syncs to whatever is currently available framework is, then run tests on them. This also applies to "Google Testing" as it needs both an engine and a framework to run tests against. The source of truth for the engine-framework revision remain solely in the framework.
2. It requires _more_ infrastructure, and with it _more_ complexity, to make this all happen. For example, to make framework goldens work, Skia Golden needs to be taught to work with more than one repo.

I'm afraid the slight team velocity gain from adding cross-repo downstream testing will be undone by the time spent on maintaining the infra that will support it.

**Comment by gnprice** [comment]
Adding those downstream checks would completely resolve the majority of your examples, as well as causing fewer PR cycles (and 100% fewer blocked engine rolls) in the others. Is that really only a slight improvement?

> We'd be running tests against some [engine revision, framework revision] tuple that doesn't ship to users. The engine syncs to whatever is currently available framework is, then run tests on them.

This part doesn't strike me as a problem. It's effectively the same thing that happens every time checks get run on a PR in any repo that's busy enough for other PRs to land while the given PR is open. It does make the check results less than perfectly informative about what would happen on merging, but they're still quite informative and useful.

Even if we were to hypothetically put the framework and engine into a single Git repo (which I gather is your preferred solution), it wouldn't fundamentally change this. The same framework PRs that landed while the given engine PR was open would still land while it was open, and a conflict between them would still turn the tree red.

> 2. It requires _more_ infrastructure, and with it _more_ complexity, to make this all happen. For example, to make framework goldens work, Skia Golden needs to be taught to work with more than one repo.

This I don't have any context on, though. If running more downstream checks would really require a lot more infrastructure that adds a lot more complexity, it may not be worth it.

**Comment by yjbanov** [comment]
> Adding those downstream checks would completely resolve the majority of your examples, as well as causing fewer PR cycles (and 100% fewer blocked engine rolls) in the others. Is that really only a slight improvement?

We might be using different criteria for what a complete resolution looks like. You seem to be saying that blocking a breaking engine change solves the issue completely. However, blocking an engine change without giving the contributor a clean path for addressing it right then effectively blocks them from finishing their task. Yes, the breakage will not break the roller or downstream tests, but the blockage still has cost. After finding out about the breakage, the contributor needs to make changes in the framework to prepare for the engine change (a typical path is to temporarily disable some tests, i.e. add more technical debt and cost). A better approach is to let the engine PR author to fix whatever needs fixing in the framework right in the same PR, and get everything reviewed once. And if things still don't work out, it's only one commit to bisect, and one commit to revert (see https://github.com/flutter/flutter/issues/141734#issuecomment-1920005589 for more CUJs).

> It's effectively the same thing that happens every time checks get run on a PR

I'm not sure that the effect of desync in the codebase is binary. It's not just whether you have it or not, but also how much of it there is. We sync the engine with the framework only at roll time. All testing that's done in the engine, both presubmit and post-submit is desynchronized (e.g. [this framework + engine test shard](https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20Web%20Framework%20tests/41196/overview) always runs on some random engine + framework revision combo). The more hops and delays your code experiences in desync state, the more cost it incurs.

> hypothetically put the framework and engine into a single Git repo (which I gather is your preferred solution), it wouldn't fundamentally change this

So far, single repo indeed seems like the simplest solution. After all, a repo is nothing more than a directory + versioning of that directory. We want the framework and the engine to be two separate entities => put them in separate directories 👍  But we want to _version_ them _together_ => what's the point of putting them in separate repos then? 🤔

However, if we don't want to solve the problem completely, we could solve just the desynchronization problem by rolling every engine commit into the framework as soon as it lands on `main`. All other problems would remain though, and due to lack of downstream testing we'd introduce a new problem: the framework tree will be closed more often.

> If running more downstream checks would really require a lot more infrastructure that adds a lot more complexity, it may not be worth it.

Unfortunately, most of the Github infra is repo-centric. You can only send a PR to one repo. Skia Perf and Skia Gold are built for instance-(one-to-one)-repo. Everything we built on top of these follow that model: LUCI, Cocoon, etc. Just to run framework golden tests (which we don't do today!) we'd need to teach Skia Gold to manage commits/PRs from both flutter/flutter and flutter/engine. We could spend our time on that, but I'd rather the team focus on fixing user issues than spend time building fancy bespoke infrastructures to satisfy the multi-repo requirement that serves no interesting purpose, and whose cost will never go away no matter how much infra we build for it.

**Comment by gnprice** [comment]
The split between the framework repo and engine repo is not only part of the experience of developing Flutter — it's also part of Flutter's user experience, that is the experience of people developing apps using Flutter.

That's because the way we distribute Flutter is as the flutter/flutter Git repo, including the scripts within it that download prebuilt engine artifacts. (Even when you download a release tarball, it just unpacks to a Git worktree, complete with `.git/` directory.)

I hear you that combining the two into a single repo would improve the experience of doing development on the engine. The thing that a proposal to combine them will need to reckon with is that the current setup makes a pretty great developer experience for Flutter's users. Speaking from experience, the fact that Flutter is distributed as a Git repo really shines in particular when experimenting with framework changes in the context of one's app. In addition to being good for our users, that's good for the project, because it's crucial to the funnel for Flutter users turning into Flutter contributors.

If you'd like to combine the framework and engine into one repo, I think a design doc would be a good medium for discussing that. One of the groups of questions that such a design doc should answer would be to spell out concretely how the distribution of Flutter to users would look: would it still be a clone of the repo? How would prebuilt engine artifacts interact with the engine sources in that tree? What would be the space and bandwidth costs of including all those engine sources that most Flutter users never need?

To be clear, I'm not saying there can't be good answers to those questions — just that they need to be figured out and discussed. There are purposes the current setup serves, and there are trade-offs.

**Comment by gnprice** [comment]
(And FWIW I've been known elsewhere as an advocate of monorepo setups, and of merging different version-control repos into a single repo. So I definitely sympathize with the argument that the Flutter engine and framework, because they're ultimately deployed as a unit, should be versioned together in one repo. But there are steps on the way to there that can't be glossed over, particularly given the flutter/flutter repo's role in distributing Flutter to its users.)

**Comment by yjbanov** [comment]
Re https://github.com/flutter/flutter/issues/141734#issuecomment-2221306231

I'm 100% on board. This issue is certainly not a proposal. A proposal would have to be a lot more in-depth, and must ensure the developer experience remains great, same as hacking just on the framework alone.

Re https://github.com/flutter/flutter/issues/141734#issuecomment-2221316605

The long answer is more complicated, but Flutter should not do the "monorepo" thing as in "put literally all code in the same repo". For example, flutter/packages and flutter/cocoon should be in separate repos because they are versioned separately. The only code we have that's versioned atomically is flutter/flutter, flutter/engine, and to a lesser extent dart-lang/sdk. These are the only viable candidates for merging into one. True "monorepo" requires unified versioning of _all_ code that goes into it (see [update_packages.dart](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/update_packages.dart) and [DEPS](https://github.com/flutter/engine/blob/main/DEPS); yes, flutter/flutter and flutter/engine are each a monorepo; also see https://research.google/pubs/why-google-stores-billions-of-lines-of-code-in-a-single-repository/). Without it you'll be in a lot of pain with a monorepo.

**Comment by gnprice** [comment]
Yeah, agreed — flutter/packages has a very different relationship to flutter/flutter than flutter/engine does, and doesn't belong in the same version-control repo in any case. Key to the argument is the fact that the Flutter engine and framework are deployed as a unit.

**Comment by matanlurey** [comment]
I am marking this closed!
