### ISSUE TITLE
How to support paste image in text field?

### ISSUE THREAD

**Issue by lucasjinreal** [flutter/flutter#141753]
Looked around seems no other options to do so, cause flutter Pasteboard didn't supports image well.

Is there any way to support paste image directly in textfiled or, get the image copied and send in email app?

**Comment by dam-ease** [comment]
Hello @lucasjinreal 
This feature isn't supported in TextField yet, a different issue https://github.com/flutter/flutter/issues/23603 and https://github.com/flutter/flutter/issues/92506 are tracking this functionality. Closing this as a duplicate, but feel free to re-open if your use-case does not fall under those issues.

**Comment by lucasjinreal** [comment]
@dam-ease I keep track in another issue.

But this is really needed in desktop, thanks
