### ISSUE TITLE
No Pixel 7 Pro attached to x64 macs in the try pool

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#141745]
A failing framework PR is https://github.com/flutter/flutter/pull/141744

**Comment by ricardoamador** [comment]
@zanderso are we referring to intel as being the CPU or GPU or both?

**Comment by zanderso** [comment]
CPU. I'll retitle the issue to be more clear.

**Comment by zanderso** [comment]
@yusuf-goog may know more about what's intended to be hooked up where. It may be the case that there shouldn't be a Pixel 7 Pro on an x86 mac in the try pool, and this issue should be closed. But he should chime in first.

**Comment by ricardoamador** [comment]
Gotcha. Appreciate the clarification.

**Comment by yusuf-goog** [comment]
There are very few physical testbeds in the try pool:

<google-sheets-html-origin><style type="text/css"></style>
flutter-devicelab-linux-5 | x86-64-i5-7300U | Moto G (4)
-- | -- | --
flutter-devicelab-linux-26 | x86-64-i5-7300U | Pixel 7 Pro
flutter-devicelab-linux-53 | x86-64-avx2 | Pixel 7 Pro
flutter-devicelab-mac-1 | x86-64-i7-8700B | iPhone12,1
flutter-devicelab-mac-12 | x86-64-i7-8700B | iPhone12,1
flutter-devicelab-mac-14 | x86-64-i7-8700B | iPhone12,1
flutter-devicelab-mac-17 | x86-64-i7-8700B | Moto G (4)
flutter-devicelab-mac-19 | x86-64-i7-8700B | Pixel 7 Pro
flutter-devicelab-mac-38 | arm64-64-Apple_M1 | iPhone12,1
flutter-devicelab-mac-45 | arm64-64-Apple_M1 | iPhone12,1
flutter-devicelab-mac-46 | arm64-64-Apple_M1 | iPhone12,1

[flutter-devicelab-linux-5](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-linux-5)	x86-64-i5-7300U	Moto G (4)
[flutter-devicelab-linux-26](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-linux-26)	x86-64-i5-7300U	Pixel 7 Pro
[flutter-devicelab-linux-53](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-linux-53)	x86-64-avx2	Pixel 7 Pro
[flutter-devicelab-mac-1](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-1)	x86-64-i7-8700B	iPhone12,1
[flutter-devicelab-mac-12](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-12)	x86-64-i7-8700B	iPhone12,1
[flutter-devicelab-mac-14](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-14)	x86-64-i7-8700B	iPhone12,1
[flutter-devicelab-mac-17](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-17)	x86-64-i7-8700B	Moto G (4)
[flutter-devicelab-mac-19](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-19)	x86-64-i7-8700B	Pixel 7 Pro
[flutter-devicelab-mac-38](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-38)	arm64-64-Apple_M1	iPhone12,1
[flutter-devicelab-mac-45](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-45)	arm64-64-Apple_M1	iPhone12,1
[flutter-devicelab-mac-46](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-46)	arm64-64-Apple_M1	iPhone12,1

These setups were meant to run some exploratory builds, which were non-blocking. If we want to support builds that block, we should determine the right quantity and configuration of testbeds to have.

**Comment by keyonghan** [comment]
The test has been marked as `bringup: true` and this is unblocked. If we want to enforce test in try pool in the future, we need to have at least 3 testbeds. We need to have seperate bug to track these requests. Closing here.
