### ISSUE TITLE
Upgrade intl package in local_auth_ios

### ISSUE THREAD

**Issue by TheFabbiusCorp** [flutter/flutter#141779]
### Use case

In my project, some packages depend on `intl: ^0.19.0`. Although `local_auth` doesn't depend on `intl`, `local_auth_ios` does. Since there are no breaking changes moving from `intl: ^0.17.0` (minimum version in local_auth_ios) to `intl: ^0.19.0`, is it possible to extend the version to be `intl: ">=0.17.0 <=0.19.0"` or `intl: ^0.17.0`?

### Proposal

Increase the version of intl in `local_auth_ios` from `intl: ">=0.17.0 <0.19.0"` to `intl: ">=0.17.0 <=0.19.0"` or `intl: ^0.17.0`?

**Comment by huycozy** [comment]
Besides `local_auth_ios`, `intl` package also exists in `local_auth_android` as well:

 https://github.com/flutter/packages/blob/76a6fd20f0914689fee483ce89c6a2f6c1952ce8/packages/local_auth/local_auth_android/pubspec.yaml#L24

**Comment by stuartmorgan** [comment]
> is it possible to extend the version to be `intl: ">=0.17.0 <=0.19.0"`

This is definitely something we do when there's no change that affects us; we'd be happy to take a PR to adjust the range to this.
