### ISSUE TITLE
Process Failed to escape the string when powershell command was executed

### ISSUE THREAD

**Issue by laterdayi** [flutter/flutter#141763]
### Steps to reproduce

```
      ProcessResult process = Process.runSync(
        'powershell.exe',
        [
          'Start-Process',
          '-Verb',
          'RunAs',
          '-FilePath',
          'powershell.exe',
          '-ArgumentList',
          "'New-Item -Path C:\\Desktop\\test.ps1 -ItemType File -Value \"123\" '"
        ],
      );
```

### Expected results

```
New-Item -PathC:\\Desktop\\test.ps1 -ItemType File -Value '"123"'
```

Expect to get a command like this, a string 123 in the file

### Actual results

But when escaped by dart, it's always the number 123

### Code sample

```
      ProcessResult process = Process.runSync(
        'powershell.exe',
        [
          'Start-Process',
          '-Verb',
          'RunAs',
          '-FilePath',
          'powershell.exe',
          '-ArgumentList',
          "'New-Item -Path C:\\Desktop\\test.ps1 -ItemType File -Value \"123\" '"
        ],
      );
```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment]
`Process` is from the `dart:io` library of the dart sdk. Any issues you encounter using it should be reported on the dart sdk repo. https://github.com/dart-lang/sdk/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc++

Kindly refile your issue on the dart-sdk repo. 

Closing from here. 

Thank you
