### ISSUE TITLE
How do I know the version number of dart included in flutter sdk among the historical release versions of flutter?

### ISSUE THREAD

**Issue by 295060456** [flutter/flutter#141794]
> 因为我现在在学习dart，目前拿到的demo是dart2，但是我安装的flutter是最新的，那么此时他包含的dart版本是3

Because I am learning dart now, the demo I got so far is dart2, but the flutter I installed is the latest, so the dart version it contains at this time is 3

**Comment by parlough** [comment]
The [Flutter SDK archive](https://docs.flutter.dev/release/archive) has this information for all Flutter releases from the past few years.

You can also run `flutter --version` to determine the version of Dart bundled with your current version of Flutter.

Do note that if the code/demo you received is using Dart 2.12 through 2.19, most code should still work in Dart 3 or later, or do so with very few changes. Any versions before Dart 2.10 or earlier did not support [null safety](https://dart.dev/null-safety).

**Comment by danagbemava-nc** [comment]
Closing this because this has been answered in https://github.com/flutter/flutter/issues/141794#issuecomment-1899523301. 

@295060456, in the future, please ask these types of questions on stackoverflow instead of the flutter repo.

Thank you
