### ISSUE TITLE
Soft hyphens do not insert the hyphen after the break

### ISSUE THREAD

**Issue by navaronbracke** [flutter/flutter#141867]
### Steps to reproduce

1. flutter create text_sample --platforms=web,android,macos
2. replace main.dart with the code sample
3. run the app on web, Android and MacOS (so we can compare some results)
4. Observe the results
5. Now compare these results against a JSFiddle (which uses the `&shy;` character in plain HTML) See the code sample.

### Expected results

The word is broken on the correct place, and the hyphen `-` is placed in the word, before the word break.

When selecting the entire string in the JSFiddle, the text selection does not include  the line break and the hyphen,
which is probably important to mention.

```
Foo­-
barbazqux
```

See the JSFiddle sample screenshot.

This is according to the definition of the [Soft Hyphen](https://en.wikipedia.org/wiki/Soft_hyphen) unicode character.

### Actual results

The line break is in the right place, but no hyphen is inserted.
If I remove the `\u00ad`, the text breaks in a different spot, hence why I think only the hyphen is missing.

This is the case for CanvasKit/HTML and also for MacOS/Android.

### Code sample

<details open><summary>Code sample</summary>

```
// JS Fiddle sample to compare against

// HTML
<div>
  <span>Foo&shy;barbazqux</span>
</div>

// CSS
div {
  max-width: 80px;
}
```

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;

  const MyHomePage({
    super.key,
    required this.title,
  }) : super();

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
        child: SizedBox(
          width: 80,
          child: Text('Foo\u00adbarbazqux'),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Web - JSFiddle (expected results with `\u00ad`)
![Screenshot 2024-01-19 at 15 54 20](https://github.com/flutter/flutter/assets/23480364/da408cc6-3da7-429e-8e53-1936032a2402)

Web - HTML / CanvasKit
![Screenshot 2024-01-19 at 16 00 01](https://github.com/flutter/flutter/assets/23480364/fa825538-1a14-4cd8-8723-9346461f2dae)

MacOS
![Screenshot 2024-01-19 at 16 15 59](https://github.com/flutter/flutter/assets/23480364/20608ac7-aa7a-49d5-9d3b-262c76e93162)

</details>

### Logs

<details open><summary>Logs</summary>

```console
N/A
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.1.2 23B92 darwin-x64, locale
    en-BE)
    • Flutter version 3.16.5 on channel stable at
      /Users/navaronbracke/Documents/flutter
    • Upstream repository git@github.com:navaronbracke/flutter.git
    • FLUTTER_GIT_URL = git@github.com:navaronbracke/flutter.git
    • Framework revision 78666c8dc5 (4 weeks ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/navaronbracke/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/navaronbracke/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.1.2 23B92 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.234

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment]
Thanks for filing a detailed issue, @navaronbracke. But this is a known issue being tracked at https://github.com/flutter/flutter/issues/18443. Closing this issue as a duplicate, so please follow up on it for further updates. 

You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!
