### ISSUE TITLE
Update `Slider` for Material 3 redesign

### ISSUE THREAD

**Issue by parlough** [flutter/flutter#141842]
M3 sliders have an [updated look](https://m3.material.io/components/sliders/overview)

![image](https://github.com/flutter/flutter/assets/6655696/f4314e3d-06ab-4787-b5c5-87aa743c666f)
![image](https://github.com/flutter/flutter/assets/6655696/11a56b4a-d2ed-48d5-ab82-166cf5148917)

Since this occurred after the primary Material 3 transition, this could potentially be an option that starts as defaulting to `false`, switches to `true`, and then is eventually removed. Or a new widget as they are significantly different.

**Specification:** https://m3.material.io/components/sliders/specs
**December 2023 updates:** https://m3.material.io/components/sliders/overview#79de9466-a59c-4236-9099-735e67a38e53

**Comment by TahaTesser** [comment]
cc: @HansMuller @Piinks 
This seems like a good opportunity to resolve all the legacy issues mentioned in  https://github.com/flutter/flutter/issues/125329 and create a separate new Slider widget with the redesign. 

I'll be more than happy to take this when we decide to work on this.

**Comment by parlough** [comment]
As always, you're our hero @TahaTesser! I think this change will be a bit controversial over the original slider due to its size, so decent configuration options are probably worthwhile. However, the new style defaults fit in a lot better with other new styles like the switches and it has a lot of accessibility wins, so I'm excited for this. Thanks 💙

**Comment by HansMuller** [comment]
Creating a new component vs evolving the existing one is a tricky question; there are many pros and cons to consider. Either way, it's a big project. We'll need to think carefully about how (and when) to proceed.

**Comment by Piinks** [comment]
In general, introducing new widgets instead of updating old ones is the most disruptive and breaking change for developers.

**Comment by parlough** [comment]
I have no particular preference, whatever is the standard for the framework and less disruptive works for me :)

**Comment by TheLastFlame** [comment]
> In general, introducing new widgets instead of updating old ones is the most disruptive and breaking change for developers.

Isn't it the other way around? After the old widget is updated, all projects using it will need to update the code to restore the desired results.

In the case of creating a new widget, nothing will break for anyone, they will only have the opportunity to use the new widget if they want.

**Comment by benthillerkus** [comment]
> Isn't it the other way around? After the old widget is updated, all projects using it will need to update the code to restore the desired results.

There isn't a way for the framework to differentiate between the users who want Material Design and those who use `material.dart`, because they need input components, but are actually shipping their own design system hacked on top of that.

For developers who want "native" Material Design like on Android, updating the existing slider would be better. The rest would prefer introducing a new widget, so that they don't need to update their hacks that make the Material widget match their design teams' Figma.

At the core of this is the unresolved "ship material as a seperate package" issue, which would make it much easier to stay on older versions of the package, while at the same time keeping the Flutter version fresh -- and the blankcanvas / shadcn projects that aim to provide actually neutral components that are ment to be customized.

**Comment by guidezpl** [comment]
We'll need to update at least:
- thumb shape
- slider track shape
- indicator shape

I already created the thumb and slider track shapes for an internal prototype, which can serve whoever wants to implement this as a starting point. LMK and I'll send you code.

<img width="709" alt="image" src="https://github.com/flutter/flutter/assets/6655696/bb0067fa-b37f-4cbb-80ee-9397e89c3933">

**Comment by TahaTesser** [comment]
@guidezpl 
Please feel free to send. I can continue the work.

**Comment by TahaTesser** [comment]
@guidezpl 
Just sent me the code, I can take a look, add tests, docs, example and update Slider in a non-breaking way. Thanks!

**Comment by TahaTesser** [comment]
I made a bunch of bug fixes and improvements to the thumb and track code provided by @guidezpl 

Today I created the new value indicator shape to go with this update. 

This is almost done, more tweaks and tests are needed, will file this next week. 
When this land, these shapes will be optional. I'll include an example to explain how to get the new look.

![Screenshot 2024-04-26 at 16 52 55](https://github.com/flutter/flutter/assets/48603081/831f1743-aa93-4620-8b06-71ef01904298)

**Comment by ferraridamiano** [comment]
Thank you @TahaTesser for implemented this cool redesign. In this new material redesign hase been added also the "centered configuration"
![image](https://github.com/flutter/flutter/assets/34270884/a6107c8e-3ce0-450d-9143-51c3fa74b89e)

Will your PR also add this feature or will it be added later? Thank you!

**Comment by TahaTesser** [comment]
@ferraridamiano 
Thanks for sharing this! My current priority is to add new shapes in `Slider` and `RangeSlider` then i could come for new capabilities as part of a separate issue.

**Comment by TahaTesser** [comment]
Making progress with a doc.

**Comment by parlough** [comment]
Calling out that the doc that @TahaTesser wrote can be found at https://flutter.dev/go/updating-material-3-sliders :)

**Comment by TahaTesser** [comment]
@parlough thanks for sharing! Excited to land this soon! (back to it tomorrow after a vacation)

**Comment by tmaihoff** [comment]
Also looking forward to it and excited to see that the issue is still being worked on! I'm happy to review the PR once it's out
