### ISSUE TITLE
Typewriting Experience in Markdown Widget

### ISSUE THREAD

**Issue by decisionslab2** [flutter/flutter#141860]
### Use case

The typewriting effect, where text appears gradually as if being typed in real-time, can add a touch of interactivity and capture users' attention more effectively. I envision a simple yet customizable option within the Markdown widget that allows users to enable or disable the typewriting effect, along with parameters to control the typing speed and delay between paragraphs.

I believe this feature would not only make the Markdown widget more versatile but also open up new possibilities for creative and engaging user interfaces. I understand that you have your hands full with maintaining and improving the package, but I genuinely believe that this addition could benefit the Flutter community as a whole.

### Proposal

If you find merit in this suggestion and decide to consider it for future releases, I would be more than willing to assist in any way possible, whether it be through testing, providing feedback, or even contributing code if that aligns with your development process.

**Comment by stuartmorgan** [comment]
`flutter_markdown` implements the markdown specs as described in the README; what's described here is not related to markdown itself. Closing as out of scope.
