### ISSUE TITLE
[Impeller] SVGs are not properly rendered on iOS simulators

### ISSUE THREAD

**Issue by IsabelaPSouza** [flutter/flutter#141893]
### Steps to reproduce

Create a new project with new flutter version (3.16.8)
Import flutter_svg on new version (2.0.9)
Add a new svg image 
Run app with impeller, the bug should occurs
Run app without impeller (--no-enable-impeller), the bug should disappear

I found this other [issue](https://github.com/flutter/flutter/issues/138598) but it's not solving the problem

| Expected results | Actual results |
| -- | -- |
| <img src="https://github.com/flutter/flutter/assets/90933885/3a0e5f08-7d31-4531-bee6-16b41219073d" width="250" height="500"> | <img src="https://github.com/flutter/flutter/assets/90933885/75f0c7c6-942e-44b3-8d1e-ae0b3bf1cc48" width="250" height="500"> |

### Code sample

Link to repository: https://github.com/IsabelaPSouza/flutter_svg_bug/tree/main

### Flutter Doctor output

<img width="804" alt="Captura de Tela 2024-01-19 às 17 08 32" src="https://github.com/flutter/flutter/assets/90933885/81bc0579-2f36-4df0-841c-398094051b64">

**Comment by danagbemava-nc** [comment]
Hi @IsabelaPSouza, are you only seeing this on simulators or do you experience this on physical devices as well? 

Can you share the other issue you found? The current link you have shared points to this issue.

**Comment by IsabelaPSouza** [comment]
Sorry, the other issue is https://github.com/flutter/flutter/issues/138598

**Comment by jason-simmons** [comment]
This example is using the "multiply" advanced blend mode.  It's running into a known issue where Impeller's `EntityPass` is not correctly providing the destination color for advanced blends if framebuffer fetch is not supported.

https://github.com/flutter/engine/pull/48646 was an attempt to fix this but had to be reverted.  I'm planning to revisit this soon.

**Comment by chinmaygarde** [comment]
This should work now because we always have a render pass. But need to verify.

**Comment by jonahwilliams** [comment]
Confirmed that this works correctly.

I believe this actuall only happens on iOS simulators, so I don't think we'll consider a cherry pick.
