### ISSUE TITLE
[Impeller] UV coordinate mapping system might need to include entity transform as well as effect transform.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#141890]
@matanlurey and I were investigating a case where SurfaceTexutres appeared to not work on the Impeller GLES backend. Upon investigation we found that they were working, but were only displaying a single pixel.

Consider the following code that is used to draw the external textures:

```c++
    // The incoming texture is vertically flipped, so we flip it
    // back. OpenGL's coordinate system has Positive Y equivalent to up, while
    // Skia's coordinate system has Negative Y equvalent to up.
    context.canvas->Translate(bounds.x(), bounds.y() + bounds.height());
    context.canvas->Scale(bounds.width(), -bounds.height());

    if (!transform.isIdentity()) {
      DlImageColorSource source(dlimage, DlTileMode::kRepeat,
                                DlTileMode::kRepeat, sampling, &transform_);

      DlPaint paintWithShader;
      if (context.paint) {
        paintWithShader = *context.paint;
      }
      paintWithShader.setColorSource(&source);
      context.canvas->DrawRect(SkRect::MakeWH(1, 1), paintWithShader);
```

Notice that we draw a 1x1 rectangle and place the scaling transform on the canvas (the entity transform). Separately, the transform applied to the DlImageColorSource (the effect transform) includes a further transformation (maybe the flip?).

When we compute the texture coordinates in impeller, we only apply the effect transform to the rect:

```
  auto uv_transform =
      texture_coverage.GetNormalizingTransform() * effect_transform;
  std::vector<Point> data(8);
  auto points = source_rect.GetPoints();
  for (auto i = 0u, j = 0u; i < 8; i += 2, j++) {
    data[i] = points[j];
    data[i + 1] = uv_transform * points[j];
  }
```

The entity transform is only used as the mvp transform for the vertex_shader coordinates and is not involved in the UV computation.

**Comment by matanlurey** [comment]
I've created a small `AiksTest` (will upload PR momentarily) that emulates this problem:

```cc
// Regression test for https://github.com/flutter/flutter/issues/141890.
TEST_P(AiksTest, 1x1RectWithALargeScaleShouldIncludeEntityTransform) {
  // When handling external textures provided by Android/GLES (for example),
  // the incoming texture is vertically flopped, and we apply a transform (both
  // a translate/scale, and then draw a 1x1 rect) to flip it back.
  //
  // As of #141890, the computed entity transform was not being applied to the
  // UV coordinates, which resulted in the texture being drawn as a scaled up
  // single pixel. This test emulates that scenario.
  Canvas canvas;
  Paint paint;
  auto texture = CreateTextureForFixture("table_mountain_nx.png");

  canvas.Scale({100, 100, 1});

  paint.color_source = ColorSource::MakeImage(
      /*texture=*/texture,
      /*x_tile_mode=*/Entity::TileMode::kRepeat,
      /*y_tile_mode=*/Entity::TileMode::kRepeat,
      /*sampler_descriptor=*/{},
      /*effect_transform=*/Matrix::MakeTranslation({100.0, 100.0}));

  canvas.DrawRect(Rect::MakeLTRB(0, 0, 1, 1), paint);
  ASSERT_TRUE(OpenPlaygroundHere(canvas.EndRecordingAsPicture()));
}
```

## Before

![image](https://github.com/flutter/flutter/assets/168174/0e86e5df-b63c-4e34-97c7-936fb497e20e)

## After

![image](https://github.com/flutter/flutter/assets/168174/bc963142-0611-4c66-a026-24614ad054ad)

(This code is not correct, it just demonstrates that missing the entity transform causes the image to be rendered as a single big pixel)

```diff
diff --git a/impeller/entity/geometry/geometry.cc b/impeller/entity/geometry/geometry.cc
index c29ceb13c31..465c809aafe 100644
--- a/impeller/entity/geometry/geometry.cc
+++ b/impeller/entity/geometry/geometry.cc
@@ -119,8 +119,8 @@ GeometryResult ComputeUVGeometryForRect(Rect source_rect,
                                         RenderPass& pass) {
   auto& host_buffer = renderer.GetTransientsBuffer();
 
-  auto uv_transform =
-      texture_coverage.GetNormalizingTransform() * effect_transform;
+  auto uv_transform = texture_coverage.GetNormalizingTransform() *
+                      effect_transform * entity.GetTransform();
   std::vector<Point> data(8);
   auto points = source_rect.GetPoints();
   for (auto i = 0u, j = 0u; i < 8; i += 2, j++) {
```

**Comment by matanlurey** [comment]
I printed out what the transform looks like:

Coordinate  | Original | UV
------------ | -------- | ---
0 (T-Left)    | (0, 0)     | (0, 0)
1 (T-Right)  | (1, 0)      | (0.00390625, 0)
2 (B-Left)   | (0, 1)      | (0, 0.00390625)
3 (B-Right) | (1, 1)      | (0.00390625, 0.00390625)

**Comment by matanlurey** [comment]
Interestingly enough if I don't apply a `uv_transform` at all:

```diff
diff --git a/impeller/entity/geometry/geometry.cc b/impeller/entity/geometry/geometry.cc
index f9908d3b7ed..25b753b4e5d 100644
--- a/impeller/entity/geometry/geometry.cc
+++ b/impeller/entity/geometry/geometry.cc
@@ -122,8 +122,7 @@ GeometryResult ComputeUVGeometryForRect(Rect source_rect,
   // Calculate UV-specific transform based on texture coverage and effect.
   // For example, if the texture is 100x100 and the effect transform is
   // scaling by 2, then the UV transform should be scaling by 0.5.
-  auto uv_transform =
-      texture_coverage.GetNormalizingTransform() * effect_transform;
+  auto uv_transform = 1;
 
   // Allocate space for vertex and UV data (4 vertices)
   // 0: position
```

... this particular test case WAI:

![Screenshot 2024-01-19 at 4 37 56 PM](https://github.com/flutter/flutter/assets/168174/57a9ca13-a7d7-4920-8956-331d0c519762)

**Comment by matanlurey** [comment]
Another scenario, using the transform's basis only (`w` components without translation):

```diff
diff --git a/impeller/entity/geometry/geometry.cc b/impeller/entity/geometry/geometry.cc
index f9908d3b7ed..5017f040b26 100644
--- a/impeller/entity/geometry/geometry.cc
+++ b/impeller/entity/geometry/geometry.cc
@@ -122,8 +122,8 @@ GeometryResult ComputeUVGeometryForRect(Rect source_rect,
   // Calculate UV-specific transform based on texture coverage and effect.
   // For example, if the texture is 100x100 and the effect transform is
   // scaling by 2, then the UV transform should be scaling by 0.5.
-  auto uv_transform =
-      texture_coverage.GetNormalizingTransform() * effect_transform;
+  auto uv_transform = texture_coverage.GetNormalizingTransform() *
+                      effect_transform * entity.GetTransform().Basis();
 
   // Allocate space for vertex and UV data (4 vertices)
   // 0: position
```

![Screenshot 2024-01-19 at 4 39 53 PM](https://github.com/flutter/flutter/assets/168174/55ba5b95-bb91-4349-8d05-ad48ea3d10df)

**Comment by bdero** [comment]
I wrote a Skia fiddle that's equivalent to the `1x1RectWithALargeScaleShouldIncludeEntityTransform` reproduction, but Skia appears to be behaving the same way: https://fiddle.skia.org/c/d1aef616b657435880ef370157177d01

![image](https://github.com/flutter/flutter/assets/919017/ea38fdd1-d713-42b3-b47d-8e6047958928)

Monkey image is the one being sampled: 
![image](https://github.com/flutter/flutter/assets/919017/02dda6cf-deec-4740-bd5d-454cdfc1edf8)

That doesn't necessarily mean there's not a bug on the Impeller side, but I think this particular repro isn't revealing one. I'll play around with the transforms to see if I can find any differences.

**Comment by bdero** [comment]
I extracted the mandrill image from Skia fiddle and the effect transform seems to have identical behavior between Impeller and Skia. PR with a golden that captures some cases here: https://github.com/flutter/engine/pull/49930

I suspect the bug is in `SurfaceTextureExternalTexture::Paint` rather than Impeller.

**Comment by bdero** [comment]
This turned out to be bugs in the Android embedder. (See https://github.com/flutter/flutter/issues/141636#issuecomment-1904930742)
