### ISSUE TITLE
[tool_crash] HttpException

### ISSUE THREAD

**Issue by as-android-developer** [flutter/flutter#141889]
## Command
```
flutter run --machine --start-paused -d R58N209G34L --devtools-server-address http://127.0.0.1:9100/ --target D:\FlutterProjects\go_plan-master\lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
HttpException
```

```
```
[✓] Flutter (Channel stable, 3.16.5, on Microsoft Windows [Version 10.0.22621.3007], locale en-US)
    • Flutter version 3.16.5 on channel stable at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (4 weeks ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at D:\Android\Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = D:\Android\Sdk
    • Java binary at: D:\GiraffeAndroidStudio\android-studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.4.33205.214
    • Windows 10 SDK version 10.0.19041.0
    ✗ Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[✓] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[✓] Android Studio (version 2023.1)
    • Android Studio at D:\GiraffeAndroidStudio\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[✓] VS Code (version 1.85.2)
    • VS Code at C:\Users\Abdul Satar\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.80.0

[✓] Connected device (4 available)
    • SM A715F (mobile) • R58N209G34L • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.22621.3007]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 120.0.6099.217
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 120.0.2210.144

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 84a1e904f44f9b0e9c4510138010edcc653163f8
### Plugins
audio_manager-0.8.2
cloud_firestore-4.14.0
cloud_firestore_web-3.9.0
file_picker-5.5.0
file_selector_linux-0.9.2+1
file_selector_macos-0.9.3+3
file_selector_windows-0.9.3+1
firebase_auth-4.16.0
firebase_auth_web-5.8.13
firebase_core-2.24.2
firebase_core_web-2.10.0
firebase_messaging-14.7.10
firebase_messaging_web-3.5.18
firebase_storage-11.6.0
firebase_storage_web-3.6.17
flutter_facebook_auth-6.0.4
flutter_facebook_auth_web-5.0.0
flutter_login_facebook-1.9.0
flutter_plugin_android_lifecycle-2.0.17
flutter_share-2.0.0
fluttertoast-8.2.4
google_sign_in-5.4.4
google_sign_in_android-6.1.21
google_sign_in_ios-5.7.3
google_sign_in_web-0.10.2+1
image_cropper-1.5.1
image_picker-0.8.9
image_picker_android-0.8.9+3
image_picker_for_web-2.2.0
image_picker_ios-0.8.9+1
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
open_filex-4.3.4
path_provider-2.1.2
path_provider_android-2.2.2
path_provider_foundation-2.3.2
path_provider_linux-2.2.1
path_provider_windows-2.2.1
shared_preferences-2.2.2
shared_preferences_android-2.2.1
shared_preferences_foundation-2.3.5
shared_preferences_linux-2.3.2
shared_preferences_web-2.2.2
shared_preferences_windows-2.3.2
sqflite-2.3.0
url_launcher-6.2.3
url_launcher_android-6.2.2
url_launcher_ios-6.2.4
url_launcher_linux-3.1.1
url_launcher_macos-3.1.0
url_launcher_web-2.2.3
url_launcher_windows-3.1.1

**Comment by darshankawar** [comment]
@as-android-developer 
Do you get any more logs after this exception is triggered ? If so, can you provide the same here ?
Also, is this exception occuring consistently everytime you run the said command ?
