### ISSUE TITLE
analysis server behavior change in a ~degenerate case

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#141873]
Starting with the Dart roll here https://github.com/flutter/engine/pull/49880, the behavior of the analysis server is different when supplied with the following file:
```dart
import 'package:flutter/material.dart
```

Previously, the analysis server would come back with the errors:
```
  error • error.dart:1:8 • Expected to find ';'. • expected_token
  error • error.dart:1:37 • Unterminated string literal. •
          unterminated_string_literal
warning • error.dart:1:8 • Unused import: 'package:flutter/material.dart'. Try
          removing the import directive. • unused_import

3 issues found.
```

However, after the roll linked above, it reports no errors, and returns success. See https://github.com/flutter/flutter/pull/141870.

**Comment by jason-simmons** [comment]
That Dart roll includes this commit:
`AnalysisDriver. Produce results for all files of a library. #2` - https://dart.googlesource.com/sdk/+/637ec97e42c0bab350d6b4ed86813fadd63c62ea

There was a similar issue involving this test's interaction with the analyzer when a previous version of that commit landed:
https://dart.googlesource.com/sdk/+/89bd370e95c0695250a4f0111be3134b9936eadd

The original version of the commit was reverted to unblock the roll:
https://dart.googlesource.com/sdk/+/0b26a96696ccb504e3ed90dabfff04eb17342705

But it looks like the new version is still seeing issues.

@scheglov @bwilkerson

**Comment by scheglov** [comment]
I'm looking into the analysis server, and `AnalysisDriver` changes.

**Comment by scheglov** [comment]
Some old hacks can have consequences far in the future.
https://dart-review.googlesource.com/c/sdk/+/347421
