### ISSUE TITLE
pigeon README snippet out-of-date

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#141839]
README snippet validator on [my PR](https://github.com/flutter/packages/pull/5934) which didn't touch the README:

```
 Changed packages: pigeon
 [0:00] Running for packages/pigeon...
   Checked 11 snippet(s) in example/README.md.
   The following files have out of date excerpts:
     /b/s/w/ir/x/w/packages/packages/pigeon/example/README.md
   If you edited code in a .md file directly, you should instead edit the files that contain the sources of the excerpts.
   If you did edit those source files, run the repository tooling's "update-excerpts" command on this package, and update your PR with the resulting changes.
   For more information, see https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#readme-code
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8758501385039591137/+/u/Run_package_tests/README_snippet_validation/stdout

1. Fix the README snippet
2. Figure out why this failed out-of-band

cc @stuartmorgan

**Comment by tarrinneal** [comment]
I commented on the code that is changed and needs updated in the README.

Pigeon is weird as it has two README's with snippets. The relevant changes are in the README in the example app.

**Comment by jmagman** [comment]
Oh I see, thank you!
