### ISSUE TITLE
Circular shaped buttons (e.g. FAB) are invisible on Fuchsia

### ISSUE THREAD

**Issue by yyoon** [flutter/flutter#14186]
Currently, the engine version is pinned at flutter/engine@05fe72d068e19c7886e8d27f9b004201d5ad1300 in fuchsia tree, and all the circular buttons like FAB, and any buttons made with `MaterialType.circular` material is invisible.

I also tried rolling both the engine and flutter platform together, and now those circular buttons are visible but shaped as squares.

These commits look somewhat related, but not entirely sure:
flutter/engine@05fe72d068e19c7886e8d27f9b004201d5ad1300
flutter/engine@e1e97b913055efe3289ddfda56ca4a71132ef8d4

cc: @amirh

**Comment by amirh** [comment]
Likely caused by my recent shape changes.
I'm on PTO today, will look at that Monday morning.

**Comment by amirh** [comment]
Just to make sure - what framework version are you using?
There was a breaking change in the engine, and you need to be using framework that's later than https://github.com/flutter/flutter/commit/8cf109d20f5b97cf9389490aa0d6f558616c5203

**Comment by yyoon** [comment]
My framework version is at a6e5de21765431c1e4b0f9f708e5c13562496782, which includes 8cf109d.
