### ISSUE TITLE
Transfer packages/platform to dart team ownership

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#141808]
@mit-mit mentioned this package would be a better fit for the dart team to own. Current plan:

1. [x] Make Dart folks admin on https://github.com/google/platform.dart
1. [x] Transfer https://github.com/google/platform.dart to the `dart-lang` org
1. [x] Sync latest changes from https://github.com/flutter/packages/tree/main/packages/platform to https://github.com/dart-lang/platform.dart: 
https://github.com/dart-lang/platform/pull/46
1. [x] Update repo and issue links in the package to the new source location: 
https://github.com/dart-lang/platform/pull/46
1. [x] Publish updated package: 
https://github.com/dart-lang/platform/pull/47
1. [x] Update publisher in pub.dev to `dart.dev`
1. [x] Remove source from https://github.com/flutter/packages:
https://github.com/flutter/packages/pull/6898
1. [x] Remove `platform` from [the issue template](https://github.com/flutter/flutter/blob/39472d9b6193191b8d11728bbcaf5c287bbb08bb/.github/ISSUE_TEMPLATE/9_first_party_packages.yml?plain=1#L59):
https://github.com/flutter/flutter/pull/149995

cc @stuartmorgan

**Comment by mit-mit** [comment]
Yes; @lrhn is a potential owner.

**Comment by stuartmorgan** [comment]
@lrhn What are the next steps for moving this?

**Comment by lrhn** [comment]
Just said to @mit-mit today that we should figure that out. 

I have a version of the package API that I'd want to continue with, it might need some tweaking around my Wasm experiments.(Is Wasm a platform?)

**Comment by mit-mit** [comment]
Added a tasklist above for how we're planning on doing this, PTAL

**Comment by devoncarew** [comment]
Hi - who's driving this / following up on updating the code in dart-lang/platform.dart?

> I have a version of the package API that I'd want to continue with, it might need some tweaking around my Wasm experiments.(Is Wasm a platform?)

Are we committing to support the current package or still experimenting? Should this be in `dart.dev` or `labs.dart.dev`?

**Comment by mit-mit** [comment]
> Are we committing to support the current package or still experimenting? 

Yes. We concretely plan on a new major version of `package:platform` with full `dart fix` support to migrate.

> Should this be in dart.dev or labs.dart.dev?
It's core, and should be `dart.dev`

**Comment by mit-mit** [comment]
This is now complete!
