### ISSUE TITLE
Could you just put flutter doctor source in somewhere that Chinese could reach?

### ISSUE THREAD

**Issue by rffanlab** [flutter/flutter#14199]
Could you please just put flutter doctor source in somewhere that Chinese could reach?
In storage.google.apis.com I could not reach it .please just put it in github ,so that I can flutter doctor

**Comment by InMatrix** [comment]
Thanks for checking out Flutter. Please check out these instructions for users in China: https://github.com/flutter/flutter/wiki/Using-Flutter-in-China

Let us know if this doesn't work for you.

**Comment by rffanlab** [comment]
Thank you.More ,is this site updated with official?

**Comment by InMatrix** [comment]
Yes, the mirror site is sync'ed with the official repos.  I'm closing this bug for now. Feel free to reopen if it doesn't work for you.

**Comment by rffanlab** [comment]
Another Question comes up.When using "flutter upgrade",It could not download dart 2.
![couldnotdownloaddartupgrade](https://user-images.githubusercontent.com/5079896/37008112-9a97fd2c-211b-11e8-95f4-540cc9026d20.png)

**Comment by rffanlab** [comment]
Because Download action links to storage.googleapis.com but Chinese GFW block access from China,So could you please solve this?
