### ISSUE TITLE
[in_app_purchase] get available offer codes

### ISSUE THREAD

**Issue by ManuelFEMartinho** [flutter/flutter#141963]
### Use case

I want to know within my app if a subscription has offer codes to be redeemed

### Proposal

It's possible to access offer codes in the queryProductDetails api method?

Or is there another way to do this?

Thank you in advance

**Comment by darshankawar** [comment]
@ManuelFEMartinho 
Are you referring to https://github.com/flutter/flutter/issues/110909 ?

**Comment by ManuelFEMartinho** [comment]
hi @darshankawar thanks for the reply

No, I can get the list of a product discounts using the AppStoreProductDetails' skProduct object.

My question is about the subscription offer codes, is it possible to get the list of that like we get the list of product discounts?

Thank you

**Comment by darshankawar** [comment]
@ManuelFEMartinho 
Check [this](https://github.com/flutter/flutter/issues/108170) if it helps in your case or not.
Seems it is only available for iOS 14 and above per readMe [section](https://pub.dev/packages/in_app_purchase#presenting-a-code-redemption-sheet-ios-14).
