### ISSUE TITLE
[Web] - Broken TextField in Semantics mode when given an `InputDecorator` with `errorText` on mobile browsers

### ISSUE THREAD

**Issue by htoor3** [flutter/flutter#141975]
### Steps to reproduce

1. Run a web app in semantics mode and render a `TextField` with an `InputDecorator` that has `errorText`
2. Attempt to click into `TextField`

### Expected results

1. Mobile keyboard pops up, allows us to type. 

### Actual results

1. Mobile keyboard doesn't pop up. 

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() {
  runApp(const App());

  SemanticsBinding.instance.ensureSemantics();
}

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: TextDecorationExample(),
    );
  }
}

class TextDecorationExample extends StatelessWidget {
  const TextDecorationExample({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Column(
        children: [
          TextField(
            decoration: InputDecoration(
              errorText: 'error',
            ),
          ),
        ],
      ),
    );
  }
}
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.19.0-6.0.pre, on macOS 14.2.1 23C71
    darwin-arm64, locale en-US)
```

</details>

**Comment by desmond206x** [comment]
This isn't only a mobile Browser problem.
All my examples from #129324 are for normal Web Chrome without mobile view enabled.

**Comment by htoor3** [comment]
> This isn't only a mobile Browser problem. All my examples from #129324 are for normal Web Chrome without mobile view enabled.

I'm unable to reproduce the issue on Desktop chrome.  The issue that I'm seeing occurs on mobile only - can you send a screen recording of the issues you're seeing on Desktop chrome?

**Comment by msutharworkspace** [comment]
Yes @htoor3 same issue i am facing on native browser when i enable accessibility with below code and run on native browser.

**RendererBinding.instance.ensureSemantics();**

**Comment by msutharworkspace** [comment]
@desmond206x  did you find any solution for this issue?

**Comment by desmond206x** [comment]
I didn't found a solution. We disabled the semantics for all of our products...

My first tests were Flutter_Quill related. I used the flutter master branch.
![quill_semantics](https://github.com/flutter/flutter/assets/833191/803466a9-682f-411e-ad67-47281f61c367)

No input possible in both editors, even after focus change. 

<details>
  <summary>Code Example 1</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_quill/flutter_quill.dart';

void main() {
  runApp(const MyApp());

  SemanticsBinding.instance.ensureSemantics();
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: MyHomePage(),
      ),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  QuillController quillController1 = QuillController.basic();
  ScrollController scrollController1 = ScrollController();

  QuillController quillController2 = QuillController.basic();
  ScrollController scrollController2 = ScrollController();

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        QuillEditor(
          configurations: QuillEditorConfigurations(
            controller: quillController1,
            placeholder: 'editor 1',
            padding: const EdgeInsets.all(8),
            scrollable: false,
            autoFocus: false,
            readOnly: false,
            expands: false,
          ),
          focusNode: FocusNode(),
          scrollController: scrollController1,
        ),
        QuillEditor(
          configurations: QuillEditorConfigurations(
            controller: quillController2,
            placeholder: 'editor 2',
            padding: const EdgeInsets.all(8),
            scrollable: false,
            autoFocus: false,
            readOnly: false,
            expands: false,
          ),
          focusNode: FocusNode(),
          scrollController: scrollController2,
        ),
      ],
    );
  }
}

``` 
</details>

![quill_semantics2](https://github.com/flutter/flutter/assets/833191/773a9d6c-f038-4f9d-acc9-802d9d4652ec)

First input not possible. Only after the first focus change the input is enabled and everything works as expected.

<details>
  <summary>Code Example 2</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_quill/flutter_quill.dart';

void main() {
  runApp(const MyApp());

  SemanticsBinding.instance.ensureSemantics();
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: MyHomePage(),
      ),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  QuillController quillController1 = QuillController.basic();
  ScrollController scrollController1 = ScrollController();

  QuillController quillController2 = QuillController.basic();
  ScrollController scrollController2 = ScrollController();

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        MergeSemantics(
          child: Semantics(
            textField: true,
            focusable: true,
            multiline: true,
            obscured: false,
            child: QuillEditor(
              configurations: QuillEditorConfigurations(
                controller: quillController1,
                placeholder: 'editor 1',
                padding: const EdgeInsets.all(8),
                scrollable: false,
                autoFocus: false,
                readOnly: false,
                expands: false,
              ),
              focusNode: FocusNode(),
              scrollController: scrollController1,
            ),
          ),
        ),
        MergeSemantics(
          child: Semantics(
            textField: true,
            focusable: true,
            multiline: true,
            obscured: false,
            child: QuillEditor(
              configurations: QuillEditorConfigurations(
                controller: quillController2,
                placeholder: 'editor 2',
                padding: const EdgeInsets.all(8),
                scrollable: false,
                autoFocus: false,
                readOnly: false,
                expands: false,
              ),
              focusNode: FocusNode(),
              scrollController: scrollController2,
            ),
          ),
        ),
      ],
    );
  }
}

``` 
</details>

<details>
  <summary>Flutter doctor</summary>
  
C:\flutter\master>bin\flutter doctor -v
[!] Flutter (Channel master, 3.20.0-1.0.pre.21, on Microsoft Windows [Version 10.0.22631.3007], locale de-DE)
    • Flutter version 3.20.0-1.0.pre.21 on channel master at C:\flutter\master
    ! The flutter binary is not on your path. Consider adding C:\flutter\master\bin to your path.
    ! The dart binary is not on your path. Consider adding C:\flutter\master\bin to your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0b5cd5073a (4 hours ago), 2024-02-05 06:16:23 +0100
    • Engine revision f34c658b96
    • Dart version 3.4.0 (build 3.4.0-99.0.dev)
    • DevTools version 2.31.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\user\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.8.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
    • Visual Studio Professional 2022 version 17.8.34322.80
    • Windows 10 SDK version 10.0.19041.0
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
      development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code, 64-bit edition (version 1.86.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.82.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3007]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 121.0.6167.86
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 121.0.2277.98

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
  
</details>

flutter_quill: 9.2.11

I will now try to strip down the examples to pure flutter without quill.

**Comment by desmond206x** [comment]
Okay, that was easy. My code example from here https://github.com/flutter/flutter/issues/129324#issuecomment-1805573390 is still valid and the input doesn't work on first focus.

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

![flutter_semantics](https://github.com/flutter/flutter/assets/833191/5977e1a5-5dbe-47ec-a82e-c07db2f4618c)


void main() {
  runApp(const App());

  SemanticsBinding.instance.ensureSemantics();
}

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: TextDecorationExample(),
    );
  }
}

class TextDecorationExample extends StatelessWidget {
  const TextDecorationExample({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Column(
        mainAxisSize: MainAxisSize.max,
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          TextField(
            decoration: InputDecoration(
              errorText: 'error',
              hintText: 'hint',
              suffixIcon: Icon(Icons.abc),
            ),
            autofocus: true,
          ),
        ],
      ),
    );
  }
}
```

**Comment by msutharworkspace** [comment]
@desmond206x Thank you for reply Also i can't disable semantics on iPad browser because iPad device type is returning  "macOS"

**Comment by msutharworkspace** [comment]
Hi @htoor3 Any update on this issue?

**Comment by dam-ease** [comment]
I'm unable to reproduce this on the latest `master` and `stable` channels.

| Web (Desktop) | Web (Mobile) |
|--------|--------|
| <video src="https://github.com/flutter/flutter/assets/53122008/ec16903a-d957-4156-9140-61b145f7933b" | <img src="https://github.com/flutter/flutter/assets/53122008/e237a291-266a-467a-8934-33069e60400b"> | 

@desmond206x @msutharworkspace Can you please check this out on the latest versions to confirm this no longer reproduces?

<details><summary>stable, master flutter doctor -v</summary>
<p>

```
[!] Flutter (Channel stable, 3.19.0, on macOS 14.2.1 23C71 darwin-arm64, locale
    en-NG)
    • Flutter version 3.19.0 on channel stable at
      /Users/damilolaalimi/sdks/flutter
    ! Warning: `dart` on your path resolves to
      /opt/homebrew/Cellar/dart/3.1.5/libexec/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/damilolaalimi/sdks/flutter.
      Consider adding /Users/damilolaalimi/sdks/flutter/bin to the front of your
      path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bae5e49bc2 (2 days ago), 2024-02-13 17:46:18 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[!] Android Studio (version unknown)
    • Android Studio at /Users/damilolaalimi/Downloads/Android Studio
      Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.86.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] VS Code (version 1.83.1)
    • VS Code at /Users/damilolaalimi/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        •
      android-arm64  • Android 14 (API 34) (emulator)
    • Damilola’s iPhone (mobile)  • 00008110-001964480AE1801E            • ios
      • iOS 17.1.1 21B91
    • iPhone 15 (mobile)          • DBCC5388-DA57-470E-8F0E-477EA0AA3C3A • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)             • macos                                •
      darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)                • chrome                               •
      web-javascript • Google Chrome 121.0.6167.184

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
``` 
```
[!] Flutter (Channel master, 3.20.0-7.0.pre.83, on macOS 14.2.1 23C71 darwin-arm64, locale en-NG)
    • Flutter version 3.20.0-7.0.pre.83 on channel master at /Users/damilolaalimi/fvm/versions/master
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.1.5/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/damilolaalimi/fvm/versions/master. Consider adding /Users/damilolaalimi/fvm/versions/master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6ee7e24bfe (3 hours ago), 2024-02-16 00:51:06 -0500
    • Engine revision dd530f1556
    • Dart version 3.4.0 (build 3.4.0-148.0.dev)
    • DevTools version 2.33.0-dev.6
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[!] Android Studio (version unknown)
    • Android Studio at /Users/damilolaalimi/Downloads/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.86.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] VS Code (version 1.83.1)
    • VS Code at /Users/damilolaalimi/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (6 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554                        • android-arm64  • Android 14 (API 34) (emulator)
    • Damilola’s iPhone (mobile)      • 00008110-001964480AE1801E            • ios            • iOS 17.1.1 21B91
    • iPhone 15 (mobile)              • DBCC5388-DA57-470E-8F0E-477EA0AA3C3A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 121.0.6167.184

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
``` 

</p>
</details>

**Comment by desmond206x** [comment]
Still reproduceable for me with the latest master branch version. Same behaviour as before.

<details>
  <summary>Flutter doctor master</summary>

[!] Flutter (Channel master, 3.20.0-7.0.pre.85, on Microsoft Windows [Version 10.0.22631.3085], locale de-DE)
    • Flutter version 3.20.0-7.0.pre.85 on channel master at C:\flutter\master
    ! The flutter binary is not on your path. Consider adding C:\flutter\master\bin to your path.
    ! The dart binary is not on your path. Consider adding C:\flutter\master\bin to your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a603a17875 (5 hours ago), 2024-02-16 09:43:50 +0200
    • Engine revision dd530f1556
    • Dart version 3.4.0 (build 3.4.0-148.0.dev)
    • DevTools version 2.33.0-dev.6
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\user\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.8.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
    • Visual Studio Professional 2022 version 17.8.34322.80
    • Windows 10 SDK version 10.0.19041.0
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code, 64-bit edition (version 1.86.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.82.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3085]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 121.0.6167.185
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 121.0.2277.112

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

</details>

**Comment by dam-ease** [comment]
Thanks for your response @desmond206x.
Running this again, I see it works on the first run, on reloading the page, it doesn't work until refocusing on the text field. 
<details><summary>Screen record</summary>
<p>


https://github.com/flutter/flutter/assets/53122008/b0fe3ab3-cfc7-478f-a112-ced7485de976



</p>
</details> 
On iOS devices, the keyboard doesn't pop up either on the first run even when TextField is focused or on refocus.
<details><summary>Screen record</summary>
<p>


https://github.com/flutter/flutter/assets/53122008/4788b200-d1ed-472b-8c7b-2f788427212b


</p>
</details> 
On Android devices, the keyboard pops up on refocus and on reloading the web page but on the first run when TextField is focused, the keyboard isn't active.
<details><summary>Screen Record</summary>
<p>

Uploading Screen Recording 2024-02-19 at 07.59.24.mov…


</p>
</details> 

<details><summary>flutter doctor -v</summary>
<p>

```
[!] Flutter (Channel master, 3.20.0-10.0.pre.43, on macOS 14.2.1 23C71 darwin-arm64, locale en-NG)
    • Flutter version 3.20.0-10.0.pre.43 on channel master at /Users/damilolaalimi/fvm/versions/master
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.1.5/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/damilolaalimi/fvm/versions/master. Consider adding /Users/damilolaalimi/fvm/versions/master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 74e054f04a (38 minutes ago), 2024-02-19 01:23:24 -0500
    • Engine revision 07c73b0c84
    • Dart version 3.4.0 (build 3.4.0-154.0.dev)
    • DevTools version 2.33.0-dev.6
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[!] Android Studio (version unknown)
    • Android Studio at /Users/damilolaalimi/Downloads/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.86.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] VS Code (version 1.83.1)
    • VS Code at /Users/damilolaalimi/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554             • android-arm64  • Android 14 (API 34) (emulator)
    • Damilola’s iPhone (mobile)      • 00008110-001964480AE1801E • ios            • iOS 17.1.1 21B91
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 121.0.6167.184

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
``` 

</p>
</details>

**Comment by desmond206x** [comment]
@dam-ease Any progress on this?
Can we change the title? It is not true, that this only happens on mobile browsers. Happens on all web browsers.

Still reproduceible with the current master branch.

**Comment by msutharworkspace** [comment]
This issue is due to error helper text when error helper shows after that keyboard will not work.

**Comment by msutharworkspace** [comment]
This issue is still reproducible in 3.19.6 flutter sdk.

**Comment by fryeap** [comment]
This issue is also causing the semantics reader to skip over the TextField when talkback/voiceover is enabled.

**Comment by jay-athelas** [comment]
Does this work for android chrome as well ? I am having issues inputting text @mdebbar 

`Flexible(
                    flex: 2,
                    child: FormBuilderTextField(
                      key: const ValueKey('email_input'),
                      name: 'email',
                      decoration: const InputDecoration(
                        label: Text('Email'),
                        contentPadding: EdgeInsets.fromLTRB(15, 15, 15, 15),
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.all(Radius.circular(5)),
                        ),
                      ),
                    ),
                  ),`
