### ISSUE TITLE
"flutter upgrade" command "Unable to upgrade Flutter: no upstream repository configured."

### ISSUE THREAD

**Issue by TheOpenDevProject** [flutter/flutter#14193]
## Steps to Reproduce
Run command `flutter upgrade` on Windows 10

## Outcome

`Unable to upgrade Flutter: no upstream repository configured.`

## Code involved

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/upgrade.dart 9e42e4b88f5a4297615927a6cabfa6f4d56a122b

## Notes
It seems that flutter is swallowing up the real error here as based on the output of `git remote -v` we get 
```
origin  https://github.com/flutter/flutter.git (fetch)
origin  https://github.com/flutter/flutter.git (push)
```

and all other signs point to an upstream repository being set.

## Tracking
Will track my attempted fixes against this ticket

**Comment by Hixie** [comment]
This might be my fault, I was poking at this code earlier this week.

**Comment by TheOpenDevProject** [comment]
@Hixie so based on 0ff9023edf7e61bc5bfca915a28fcf5a36e05402 we get

```
Exit code 128 from: git rev-parse @{u}:
@u

fatal: ambiguous argument '@u': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Comment by Hixie** [comment]
Which git are you using? Any chance it's the minigit we ship with the flutter package?

cc @goderbauer @gspencergoog

**Comment by Hixie** [comment]
Oh, if you have your own local checkout that's know to not work (though I forget why exactly).

**Comment by Hixie** [comment]
(and we should definitely make the error message clearer, if we don't outright fix it)

**Comment by TheOpenDevProject** [comment]
@Hixie working on a fix right now.

**Comment by TheOpenDevProject** [comment]
Information strongly suggests a Windows pathing issue.

**Comment by TheOpenDevProject** [comment]
e47894f9db9cbcaa4a7d5f2ddfc0473d8f98db7f This is clearly not a fix but does negate the issue as we now get 
```
Updating flutter tool...
Upgrading Flutter from D:\flutter\flutter...
Already up-to-date.
```

How ever we also run into a similar issue when it goes to upgrade the engine
```
Upgrading engine...

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
```

**Comment by TheOpenDevProject** [comment]
@Hixie @cbracken This seems to be a permission issue. Will investigate where the best place to try and elevate permissions is.

**Comment by cbracken** [comment]
Thanks for looking into this! 

If you're unable to modify the permissions, then next best would be to read the permissions, identify that we're about to have an issue, and exit immediately with an actionable error message.

Which permissions were the problem?

**Comment by TheOpenDevProject** [comment]
I think to go this deep into the issue I would need to attach a debugger and step through the code until it throws an exception.

**Comment by Hixie** [comment]
Removing TODAY label, since we concluded above that this wasn't a regression.

**Comment by TheOpenDevProject** [comment]
Is this still happening?

**Comment by jonasbark** [comment]
Yes, it does. Switching from dev to master, then running `flutter upgrade` and I got "no upstream  repository configured".
I fixed it by deleting the local master branch, then running `flutter channel master` again.

**Comment by Hixie** [comment]
@jonasbark Can you give precise steps for reproducing this?

**Comment by jonasbark** [comment]
- I was on commit `be09a200e` on dev 
- `flutter channel master`
- `flutter upgrade`
- `Unable to upgrade Flutter: no upstream repository configured.`
The console history doesn't go that far anymore so that's all the information I have.

This happens quite regularly when I'm switching channels. What output can I provide when this happens next?

**Comment by Hixie** [comment]
Can you print the output of `git remote -v`?

**Comment by jonasbark** [comment]
I did that and got the same as @TheOpenDevProject in his initial post:
```
origin  https://github.com/flutter/flutter.git (fetch)
origin  https://github.com/flutter/flutter.git (push)
```

**Comment by Hixie** [comment]
I'm not able to repro this. I followed the following steps, on Linux:

```
mkdir temp
cd temp
curl https://storage.googleapis.com/flutter_infra/releases/beta/linux/flutter_linux_v0.3.2-beta.tar.xz | tar xJ
cd flutter
git reset --hard be09a200e # to switch to the commit mentioned above
bin/flutter channel master
bin/flutter upgrade
```

...and there are no errors. :-/

**Comment by jonasbark** [comment]
I'll debug this next time it happens.

**Comment by gspencergoog** [comment]
@goderbauer, could you try this on your Windows machine and see if you see a problem?

**Comment by JoeCodeswell** [comment]
I jut got this messge on windows 10 while trying to upgrade 
  from flutter_0.2.8- beta
  to 0.3.2-beta
Here's my command

    C:\1d\iOSGroupTextPj\groupTextApp>flutter upgrade
    Unable to upgrade Flutter: no upstream repository configured.

**Comment by goderbauer** [comment]
This works fine on my Windows box.
*  I downloaded an old beta SDK from https://flutter.io/sdk-archive/#windows. 
* I unzipped it and double-clicked on flutter_console.bat
* I typed `flutter upgrade` and everything works as expected.

**Comment by mit-mit** [comment]
I'm pretty sure this is a historical issue which will not be triggered by anyone starting with 0.3.z or later. If anyone hits this again, please let us know and we will reopen.

**Comment by JoeCodeswell** [comment]
Hi folks,
For Flutter 0.3.2 command upgrade not working on windows 10 as of 5/30/2018. See below:
   >
    >datetime

    >echo off
    180530_10.30.10_Wed

    >python -c "import platform as p; print(p.platform());print(p.processor())"
    Windows-10-10.0.17134-SP0
    Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
    
    >flutter --version
    Flutter 0.3.2 • channel @u • unknown source
    Framework • revision 44b7e7d3f4 (6 weeks ago) • 2018-04-20 01:02:44 -0700
    Engine • revision 09d05a3891
    Tools • Dart 2.0.0-dev.48.0.flutter-fe606f890b

    >flutter upgrade
    Unable to upgrade Flutter: no upstream repository configured.
    
    >
Please reopen.
Thanks.
Love and peace,
Joe

**Comment by Hixie** [comment]
Please file a new bug and provide as much information as possible — how you installed flutter, what git says your remotes are etc

**Comment by JoeCodeswell** [comment]
Hi Hixie,

I have been doing some research in response to your request to file a new issue. I am suspecting my problem is that i have MANY Git executables installed on my Windows 10 machine, (cygwin, TortoiseGit,, Program Files\Git). 

My question to you is where do you folks expect to find Git? I'll put that one early in my Path environment variable and see if that works. The cygwin Git is the one picked up by the command line now.

Thanks.
Love and peace,
Joe

**Comment by goderbauer** [comment]
Flutter uses the first git executable that it can find in your path.

**Comment by JoeCodeswell** [comment]
OK here's something important i didn't know:
[(Flutter) Get Started: Install on Windows](https://flutter.io/setup-windows/) says:

> Flutter depends on these tools being available in your environment.
>    - PowerShell 5.0 or newer.
>    - Git for Windows 
My fix was to 

1.  download and install [Git for windows] (https://gitforwindows.org/index.html)
2. move its executable "C:\Program Files\Git\cmd" to top of Path (ie before cygwin Git etc.)

Working great now.
I'll use powershell as my cli for flutter/dart as well.

Thanks to all.
Love and peace,
Joe

**Comment by Hixie** [comment]
Interesting. Do you know which version/variant was first in your path before?

**Comment by viveky259259** [comment]
You can restore peace and justice by doing something like:

cd MY_FLUTTER_PATH
git checkout master

Or if that fails:

git checkout -b master upstream/master

**Comment by xanhf** [comment]
I Use git to pull the latest code directly from the master branch，solve this problem，Hopefully that helps

**Comment by dazza5000** [comment]
I fixed this by using `flutter channel stable`

**Comment by supardyke** [comment]
this worked for me right now **flutter channel stable** thanks @dazza5000

**Comment by psyanite** [comment]
Hmm  🤔

This used to work for me but it stopped working after I had to re-install Flutter because I couldn't use the dev channel or something

```
Luna@PANCAKES /c/Apps/flutter ((v1.5.3))
$ git remote -v
origin  https://github.com/flutter/flutter (fetch)
origin  https://github.com/flutter/flutter (push)

Luna@PANCAKES /c/Apps/flutter ((v1.5.3))
$ flutter upgrade
Unable to upgrade Flutter: no origin repository configured. Run 'git remote add origin https://github.com/flutter/flutter' in C:\Apps\flutter
```

I tried CMD, Git Bash, and IntelliJ Terminal. Not sure how to fix anyone help?

**Comment by samane78** [comment]
Seeing this same issue.

**Comment by samane78** [comment]
Saw the same issue. I checked the output of 
$ flutter channel
Flutter channels:
  beta
  dev
  master
  stable

None of the channels was selected, so I chose a channel. For e.g.,
$ flutter channel master

Then "flutter upgrade" runs fine.

**Comment by crimsonsuv** [comment]
> Saw the same issue. I checked the output of
> $ flutter channel
> Flutter channels:
> beta
> dev
> master
> stable
> 
> None of the channels was selected, so I chose a channel. For e.g.,
> $ flutter channel master
> 
> Then "flutter upgrade" runs fine.

This is the actual solution that worked

**Comment by wanjm** [comment]
I run this command again to fix this. it used to be ok 
git branch --set-upstream-to=origin/stable stable

**Comment by Blasanka** [comment]
Please note that `flutter channel stable` is equivalent to `git checkout stable` if you try in flutter framework located directory.

**Comment by ollydixon** [comment]
Fixed with ``flutter channel stable && git pull && flutter upgrade``

Please stop updating Flutter like this, it was working perfectly a few months ago, with the new update many packages don't work now (legacy ones like flutter_is_emulator for example). It's costing me thousands of dollars (development teams) each time you introduce all these bugs. 

We are considering leaving Flutter, we really want to avoid the joke that was React-native breaking changes.

**Comment by alienriquebm** [comment]
> I fixed this by running`flutter channel stable` in terminal.

This worked for me, thanks!!!
