### ISSUE TITLE
Engine unit test failing due to seeing directory that shouldn't exist.

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#141907]
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Production%20Engine%20Drone/550083/overview

The test `flutter/tools/clang_tidy/test/header_filter_regex_test.dart` ensures that engine repo subdirectories are covered by a regular expression. The test is failing because a directory that doesn't exist in the repo is being found in a directory listing, and that extra directory isn't covered by the regular expression.

Guessing this is due to another test not cleaning up after itself, but if that's not the case it could also be an infra caching issue? Initially routing to `team-engine`.

**Comment by zanderso** [comment]
Suspecting https://github.com/flutter/engine/pull/49847

**Comment by zanderso** [comment]
Revert of that change landed here https://github.com/flutter/engine/pull/49908

**Comment by zijiehe-google-com** [comment]
Ooops, thank you.

**Comment by zijiehe-google-com** [comment]
I noticed I made a typo which made a symbolic link in `../out/fuchsia_debug_x64` which should be `out/fuchsia_debug_x64`. I am trying if it fixes the issue.

**Comment by zijiehe-google-com** [comment]
(Removed the last comment since it wasn't accurate.)

We need https://crrev.com/c/5226021, or some hacky way to setup a temporary folder as the pwd. In chromium, the tests are always starting from a temporary folder. I'd go ahead with the former solution now.

**Comment by jonahwilliams** [comment]
The patch was reverted and this should be fixed.
