### ISSUE TITLE
[shared_preferences] [Flutter Web] MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences) 

### ISSUE THREAD

**Issue by Abu-Abdullah** [flutter/flutter#141970]
### Steps to reproduce

Run the sample code in web site

### Expected results

you can increase the counter and display the last number after refresh

### Actual results

throws this error:
```MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences) ```

### Code sample

same code in
https://pub.dev/packages/shared_preferences/example

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/flutter/flutter/assets/2059463/aa5093d9-93ba-47c1-a88f-734db00c555a)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel beta, 3.19.0-0.1.pre, on Microsoft Windows [Version 10.0.22631.3007], locale en-US)
    • Flutter version 3.19.0-0.1.pre on channel beta at E:\Support\flutter
    ! The flutter binary is not on your path. Consider adding E:\Support\flutter\bin to your path.
    ! The dart binary is not on your path. Consider adding E:\Support\flutter\bin to your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1a9a60d044 (12 days ago), 2024-01-10 13:38:09 -0800
    • Engine revision bbebee1465
    • Dart version 3.3.0 (build 3.3.0-279.0.dev)
    • DevTools version 2.31.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\ias12\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34511.84
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.3)
    • Android Studio at C:\Users\ias12\AppData\Local\Programs\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11255266)

[√] IntelliJ IDEA Community Edition (version 2024.1)
    • IntelliJ at C:\Users\ias12\AppData\Local\Programs\IntelliJ IDEA Community Edition
    • Flutter plugin version 77.0.1
    • Dart plugin version 241.8102.112

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3007]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 120.0.2210.144

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

</details>

while it works with web/edge locally in debug mode, it is not with real web hosting. as per the documentation, web is supported by shared_preferences, yet im not able to make it works

**Comment by huycozy** [comment]
Hi @Abu-Abdullah 
I tried building [plugin example](https://github.com/flutter/packages/tree/main/packages/shared_preferences/shared_preferences/example) and deploying it to Firebase hosting but can't see the issue. 

<details>
<summary>Demo</summary>

![Screenshot 2024-01-23 at 14 47 42](https://github.com/flutter/flutter/assets/104349824/b4b76d7d-93d6-4499-930f-d2d0b991f0de)
</details>


Since you deployed it to a site, could you share it here?

Also, I'm on the latest beta channel `Channel beta, 3.19.0-0.2.pre`. You may try upgrading to the latest and retry to see if it persists or not.

**Comment by Abu-Abdullah** [comment]
thanks for the quick response, 

i tried the new binary 3.19.0-0.2.pre and for some reason it works, then i returned back to the old one to see if it is really a bug, and it works as well. It seems there was a hidden issue in my setup and just using a fresh flutter binaries solved the issue.

really not sure of what is happening especially i tried some workarounds/codes found in this repository, in case i face it again and manage to reproduce it every time, i will report it again,

for now it works and thanks for your support

**Comment by Abu-Abdullah** [comment]
ok, it seems i managed to reproduce it again. the issue is happening when i build using this option ```--no-tree-shake-icons```
```
flutter build web --no-tree-shake-icons --web-renderer canvaskit --release
```

can you try please from your end as well. i need to use this option to display the Material icons.

**Comment by huycozy** [comment]
I just built again with that parameter but the deployed web still works well without issue. Please try this on a minimal sample code (a new project with `shared_preferences` simple implementation as in the plugin example) to see if the issue still occurs.

**Comment by Abu-Abdullah** [comment]
thank you for your hint and sorry for any confusion. indeed ```flutter clean``` solved the issue with me.
