### ISSUE TITLE
I cant run app on ios 17 physical device from android studio it switch to xcode and then android studio prompt "Error launching application on iPhone."

### ISSUE THREAD

**Issue by umairali4433** [flutter/flutter#141908]
### Steps to reproduce

Have a functioning Flutter project that builds on iOS 16.4
Update to MacOS Sonoma, iOS 17, and the Xcode 15
Run flutter doctor -v and see that everything checks out
Run flutter run --debug -v and see that it doesn't work

### Expected results

I just want to run my app using android studio. For debug, Hot restart and hot reload

### Actual results

I had a project that was working fine, with iOS 16, but I recently updated to the iOS 17. The project runs fine from Xcode using Product > Run, but it's a pain to have to rebuild every time. Note that the logs show that I am using the beta tool, but I get the same output on the stable tool. I want to debug my app using android studio

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>
<img width="1023" alt="Screenshot 2024-01-20 at 3 30 07 AM" src="https://github.com/flutter/flutter/assets/30576997/f8a3c6b0-a236-4c5e-a156-dcf87d494012">

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.2.1 23C71 darwin-arm64, locale
    en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.85.1)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by umairali4433** [comment]
[Untitled document.docx](https://github.com/flutter/flutter/files/14011828/Untitled.document.docx)

**Comment by darshankawar** [comment]
From the file you shared above, I see below two errors:

```
Error: No pubspec.yaml file found.
           This command should be run from the root of your Flutter project.

```

Which means you probably didn't run the command `flutter run` from root of your project. Make sure the path from which you run the command has `pubspec.yaml` file.


```
Error: Browsing on the local area network for iPhone. Ensure the
device is unlocked and attached with a cable or associated with the same local
area network as this Mac.
           The device must be opted into Developer Mode to connect wirelessly.
```

This indicates your device was probably locked when you tried running the app. Make sure the device remains unlocked.

**Comment by umairali4433** [comment]
@darshankawar the phone is attached and unlocked it was working very fine when I was on iOS 16 after I updated to iOS 17 the app is running but only from the Xcode side not from the android studio side. you can see this as well https://github.com/flutter/flutter/issues/133465 still no progress from the flutter side to resolve this issue.

**Comment by huycozy** [comment]
@umairali4433 Do you still have the [same error above](https://github.com/flutter/flutter/issues/141908#issuecomment-1905340098) after your device is connected?

Also, do you see this issue if running app from non-AndroidStudio editors (like Terminal or VSCode)?

**Comment by umairali4433** [comment]
the i issue i am having right now is if i run app with android studio it will not run but from xcode yes it does

**Comment by huycozy** [comment]
Can you try this from Terminal or VSCode as well? 

And please also try with a new Flutter project instead of your old project on your Android Studio. If it still occurs, can you let us know what the Flutter plugin version on Android Studio is?

**Comment by umairali4433** [comment]
i tried with vs code and with new project still not working

**Comment by darshankawar** [comment]
Maybe this is a genuine issue, as also raised on SO [here](https://stackoverflow.com/questions/77238124/flutter-wont-run-on-physical-ios-device-since-ios-17-unless-im-using-xcode).
@umairali4433  In order to track this issue separately, we would like to see what error are you getting when you run `flutter run` using AS or VSCode. Make sure your device is attached and unlocked and try to run the command `flutter run -v` and provide the verbose logs here. The one you provided earlier doesn't seem to properly replicate the error you are reporting, ie, we couldn't find `Error launching application on iphone.` 


> i tried with vs code and with new project still not working

Can you provide the verbose logs for this ?

**Comment by darshankawar** [comment]
> you can see this as well #133465

Maybe it is similar as the root-cause mentioned in it. But we need to confirm if you are getting any other errors in the log while running on AS or Vscode.
