### ISSUE TITLE
video_player plugin playing video problem

### ISSUE THREAD

**Issue by abbadabbatech** [flutter/flutter#14198]
## Steps to Reproduce

I modified the image_picker to pick and video and return NSURL string and play the video.  However if I base64 encode the file, then store in a DB and then decode and save the video to the application Document Directory it will not initialize and play on iOS, not even testing on Android yet.  Wondering what I am missing or doing wrong or is it a bug?

**Comment by abbadabbatech** [comment]
So I have further tested that the file is creating and if I take it off the device it plays, so I know the file is valid.  For some reason it does not initialize, as well if I take off the check to initialize, I get it to work sometimes, but not even 50%.  I have not been able to catch an error, if I run it on Android its even worse and it throws a media player error, but I am sure its related to how the path to the file is created for iOS.  I have tried the whenComplete and onError, but does not seem to make a difference or provide insight.

**Comment by mravn-google** [comment]
@abbadabbatech https://github.com/flutter/plugins/pull/565 seems to have implemented this `image_picker`+`video_player` feature. Can you supply a video file that provokes the error?

**Comment by abbadabbatech** [comment]
This was not related to the image_picker itself but with the video player plugin, I actually converted to using the launcher instead.  I aso wrote my own picker for image and video, but will test the new one as well.

**Comment by mravn-google** [comment]
@abbadabbatech Right. Would you be able to supply a valid video file that `video_player` cannot handle?

**Comment by zoechi** [comment]
@abbadabbatech have you tried comparing the bytes of the original video and the result of decoding from base64 after loading from the database?

**Comment by abbadabbatech** [comment]
Yep and everything matches, the same video plays fine when using video
launcher plugin.

**Comment by abbadabbatech** [comment]
Also its every video they take using the app, but all play with the video launcher

**Comment by zoeyfan** [comment]
Unfortunately there isn't enough information on this bug to reproduce the issue. Closing for now. 

If you are still experiencing this issue, you're welcome to reopen it. Please tell us exactly how to reproduce the problem you're running into. Attach a small sample that demonstrates the issue, or include the specific tool commands that reproduce the problem along with the results of running `flutter doctor -v`. 

Thank you for using Flutter!
