### ISSUE TITLE
error: package io.flutter.plugins.urllauncher does not exist

### ISSUE THREAD

**Issue by pharshdev** [flutter/flutter#141947]
### Steps to reproduce

1. Add url_launcher: ^6.2.3 to pubspec.yaml
2. Do the plugin configuration for android and ios
3. Run the example code on plugin page

### Actual results

`[flutter_project_name]/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:29: error: package io.flutter.plugins.urllauncher does not exist
      flutterEngine.getPlugins().add(new io.flutter.plugins.urllauncher.UrlLauncherPlugin());`

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 3.19.0-0.1.pre, on macOS 14.2.1 23C71 darwin-arm64
    (Rosetta), locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.84.2)
[✓] Connected device (3 available)            
[✓] Network resources

• No issues found!

```

</details>

**Comment by huycozy** [comment]
I think this has the same cause as https://github.com/flutter/flutter/issues/141947 that is filed recently. Closing this in favor of that one. Please follow up on it for updates. Thanks!
