### ISSUE TITLE
TextField's cursor overlaps label

### ISSUE THREAD

**Issue by hawkkiller** [flutter/flutter#141989]
### Use case

I use the default text theme given by Material 3. Every text style has height as specified [here](https://github.com/flutter/flutter/blob/fed06b31d938f7620ea7417295b8d8d19cf7cf1d/packages/flutter/lib/src/material/typography.dart#L754):

EditableText is the base for all text fields and it uses the cursor size obtained from TextPainter (see [here](https://github.com/flutter/flutter/blob/fed06b31d938f7620ea7417295b8d8d19cf7cf1d/packages/flutter/lib/src/rendering/editable.dart#L1859)).

The problem is that TextPainter favors line height and therefore cursor size becomes larger.

If a label is also provided for a text field, the cursor overlaps the label.

The basic behavior of the text field:
<img width="427" alt="image" src="https://github.com/flutter/flutter/assets/62852417/e56679b6-3fe5-4fec-9a45-9ff2bf81fe37">

TextField that uses font size as cursor size:
<img width="385" alt="image" src="https://github.com/flutter/flutter/assets/62852417/44799586-1b43-4d01-a350-888f5a00c35a">

### Proposal 1

Override cursor size to text style's font size.

In most projects, we create wrappers so to customize Material components and this issue can easily be addressed as well, without any changes to SDK (but feels like a problem, though).

### Proposal 2

TextField with a label can be bigger so that it favors the line height and the cursor doesn't overlap the label.

**Comment by dam-ease** [comment]
Thanks for filing this @hawkkiller. 
I see there is an already open issue describing your use case https://github.com/flutter/flutter/issues/141354.
Can you check this out?
If not, kindly help with more information on how it differs from yours.
Thank you!

**Comment by hawkkiller** [comment]
@dam-ease thanks, it describes the issue I'm having. Closing.
