### ISSUE TITLE
InputDecorator should fill within its border

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#14197]
Currently, when `InputDecoration.filled` is true it just fills the container rectangle. It should fill `InputDecoration.border.getOuterPath(...)`

Currently the `_borderWeight` getter in `_InputDecoratorState` depends on `InputBorder.none`. It should not, see https://github.com/flutter/flutter/pull/14177#discussion_r162768459

**Comment by Hixie** [comment]
@HansMuller did this get fixed at some point?

**Comment by HansMuller** [comment]
Both issues mentioned in the description have been fixed.
