### ISSUE TITLE
Error on Testing when uploading to Google Play

### ISSUE THREAD

**Issue by aniealss** [flutter/flutter#141949]
### Steps to reproduce

When uploading the version to Google Play, it is generated by testing on Google Play

### Expected results

No error reported

### Actual results

NoSuchMethodError reported on Crashlytics

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
io.flutter.embedding.android.FlutterView.sendUserSettingsToFlutter (FlutterView.java:1478)
io.flutter.embedding.android.FlutterView.attachToFlutterEngine (FlutterView.java:1208)
io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onCreateView (FlutterActivityAndFragmentDelegate.java:395)
io.flutter.embedding.android.FlutterActivity.createFlutterView (FlutterActivity.java:767)
io.flutter.embedding.android.FlutterActivity.onCreate (FlutterActivity.java:641)
com.app.doucall.MainActivity.onCreate (MainActivity.kt:21)
android.app.Activity.performCreate (Activity.java:8595)
android.app.Activity.performCreate (Activity.java:8573)
android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1456)
androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate (MonitoringInstrumentation.java:2)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3764)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3922)
android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:103)
android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:139)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:96)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2443)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loopOnce (Looper.java:205)
android.os.Looper.loop (Looper.java:294)
android.app.ActivityThread.main (ActivityThread.java:8177)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:552)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:971)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.8, on macOS 14.1.1 23B81 darwin-arm64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.85.1)
```

</details>

**Comment by aniealss** [comment]
device:
Google
Redfin 64-bit Only ----> android 14
Pixel 6 ----> android 12

**Comment by poqueque** [comment]
Same issue here. It would be good to understand this error that appears only in the Pre-launch report (couldn't reproduce it on a real device) to know if it's safe to release this version to production or not.

**Comment by dam-ease** [comment]
Thanks for the report!
Does this occur only on the devices mentioned here https://github.com/flutter/flutter/issues/141949#issuecomment-1903108051?

**Comment by poqueque** [comment]
In my case these were the devices:

Sdk_goog3_x86_64 -> Android 12
Sdk_goog3_gpc_x86_64 -> Android 12
Pixel 6 -> Android 12
Pixel 7 -> Android 13

**Comment by dam-ease** [comment]
Thanks for your response @poqueque. 
Can you also help with the full crash logs on your end or do you have logs as-is in the original comment?

**Comment by ntaworking** [comment]
@dam-ease 
I facing the same issue (?).
![image](https://github.com/flutter/flutter/assets/102949116/bdecf985-e882-480d-95b5-81534c17a635)
```
Fatal Exception: java.lang.NoSuchMethodError
No interface method anyMatch(Lj$/util/function/Predicate;)Z in class Lj$/util/stream/Stream; or its super classes (declaration of 'j$.util.stream.Stream' appears in /data/app/~~QWOl5NyzFvPElmgEcGPFIw==/androidx.test.tools.crawler-96tXJf54IpbK2rapxOsRqA==/base.apk!classes2.dex)
```
```
io.flutter.embedding.android.j.B (Unknown Source:48)
io.flutter.embedding.android.j.n (Unknown Source:263)
io.flutter.embedding.android.d.s (Unknown Source:130)
io.flutter.embedding.android.c.D (Unknown Source:20)
io.flutter.embedding.android.c.onCreate (Unknown Source:31)
android.app.Activity.performCreate (Activity.java:8074)
android.app.Activity.performCreate (Activity.java:8054)
android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1341)
androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate (MonitoringInstrumentation.java:2)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3688)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3864)
android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:103)
android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2253)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loopOnce (Looper.java:201)
android.os.Looper.loop (Looper.java:288)
android.app.ActivityThread.main (ActivityThread.java:7870)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:548)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1003)
```

**Comment by poqueque** [comment]
This is the crash log from Crashlytics:

FlutterView.sendUserSettingsToFlutter

Fatal Exception: java.lang.NoSuchMethodError: No interface method anyMatch(Lj$/util/function/Predicate;)Z in class Lj$/util/stream/Stream; or its super classes (declaration of 'j$.util.stream.Stream' appears in /data/app/~~m4JzJObuLZurte8rgth1PQ==/androidx.test.tools.crawler-c_J-fGuizeZ5VyCc36y-zA==/base.apk!classes2.dex)
       at io.flutter.embedding.android.FlutterView.sendUserSettingsToFlutter(FlutterView.java:1478)
       at io.flutter.embedding.android.FlutterView.attachToFlutterEngine(FlutterView.java:1208)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onCreateView(FlutterActivityAndFragmentDelegate.java:395)
       at io.flutter.embedding.android.FlutterActivity.createFlutterView(FlutterActivity.java:767)
       at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:641)
       at android.app.Activity.performCreate(Activity.java:8050)
       at android.app.Activity.performCreate(Activity.java:8030)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
       at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:2)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7839)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by camsim99** [comment]
The error is coming from: https://github.com/flutter/engine/blob/b2167a93c1a0470f5d45553fc332e2914d03b29f/shell/platform/android/io/flutter/embedding/android/FlutterView.java#L1478. Will either need to remove the use of streams or document its usage.

**Comment by camsim99** [comment]
Looks like the Stream API was added in Java 8, so if some testing is happening with an older version, that could be behind this, but it's odd that the error wouldn't be occurring, then, with the `Stream` class as a whole versus the `anyMatch` method.

**Comment by matanlurey** [comment]
Ok so here is my running theory, and I'd love OP (@aniealss) to weigh in:

1. Android Studio [supports Java 8](https://developer.android.com/studio/write/java8-support-table)
2 ... but [only](https://developer.android.com/studio/write/java8-support#library-desugaring) if using Android Gradle Plugin 4.0.0 or higher

My understanding is this could happen if they used `flutter create` a long time ago? @gmackall wrote:

> That does actually seem possible, they build with an old AGP version and so they don't get the desugaring, and then presumably that causes issues in lower API levels when Google play tests the build

@aniealss Could you share what version of Gradle/AGP you're using, and if this scenario seems related?

I'm really hesitant to effectively "ban" Java 8 in our Android embedder (and plugins) just because of an older version of Gradle.

**Comment by ericbomgardner** [comment]
I'm not OP, but in case it's helpful:

I'm seeing the same `No interface method anyMatch...` issue in Crashlytics after uploading a build that upgraded Flutter from 3.7.6 to 3.16.9 and releasing it to a Google Play internal track. I have `classpath 'com.android.tools.build:gradle:7.3.0'` in my build.gradle. However, CircleCI, which I think doesn't use Android Studio(?), uploads my builds. I think I may be on an old-ish machine image [1], though; here's the output of `flutter doctor` from the CircleCI machine:

<details>

<summary>`flutter doctor` output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.9, on Ubuntu 20.04.1 LTS 5.4.0-1021-gcp, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)
[!] Android Studio (not installed)
[✓] Connected device (1 available)
[✓] Network resources

! Doctor found issues in 3 categories.
```
</details>

I'm also curious about the answer to @poqueque's question (https://github.com/flutter/flutter/issues/141949#issuecomment-1903808660) -- do we think this crash will only happen from the pre-launch report, or may it happen in production? I'm also wondering whether it's safe to release the build with the updated Flutter version to prod.

Thanks!

[1] The orb I'm using [circleci/android@1.0.3](https://circleci.com/developer/orbs/orb/circleci/android?version=1.0.3), is [configured](https://github.com/CircleCI-Public/android-orb/blob/28a8275a5aa19475c875ffcd77cca15b589d20a0/src/executors/android-machine.yml#L14) to use their `android:202102-01` image

**Comment by camsim99** [comment]
> I'm seeing the same No interface method anyMatch... issue in Crashlytics after uploading a build that upgraded Flutter from 3.7.6 to 3.16.9 and releasing it to a Google Play internal track. I have classpath 'com.android.tools.build:gradle:7.3.0' in my build.gradle. However, CircleCI, which I think doesn't use Android Studio(?), uploads my builds. I think I may be on an old-ish machine image [1], though; here's the output of flutter doctor from the CircleCI machine

Could it be that your old-ish machine uses a Java version lower than 8? Looks like the newer orbs have a default to Java 8, but that isn't noted in the documentation until [circleci/android@2.1.0](https://circleci.com/developer/orbs/orb/circleci/android?version=2.1.0).

> I'm also curious about the answer to @poqueque's question (https://github.com/flutter/flutter/issues/141949#issuecomment-1903808660) -- do we think this crash will only happen from the pre-launch report, or may it happen in production? I'm also wondering whether it's safe to release the build with the updated Flutter version to prod.

Maybe @gmackall can weigh in here? If this is happening because old version of AGP/Java are being used, would this impact the app in prod? My gut says no, but I'm not clear as to why.

**Comment by matanlurey** [comment]
I contacted some folks on Google Play Console internally to see if I can get an "expert" opinion or answer.

I'm still eagerly awaiting reports from our customers though!

**Comment by ericbomgardner** [comment]
> Could it be that your old-ish machine uses a Java version lower than 8? Looks like the newer orbs have a default to Java 8, but that isn't noted in the documentation until [circleci/android@2.1.0](https://circleci.com/developer/orbs/orb/circleci/android?version=2.1.0).

Hm, I think it's Java 11; here's the output I get from `java --version` on the CircleCI machine:
```
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
```

And a full `flutter doctor -v`, which has some Java-related info, too:

<details>

<summary>`flutter doctor` output</summary>

```
[✓] Flutter (Channel stable, 3.16.9, on Ubuntu 20.04.1 LTS 5.4.0-1021-gcp, locale en_US.UTF-8)
    • Flutter version 3.16.9 on channel stable at /home/circleci/usr/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (11 days ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /opt/android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /opt/android/sdk
    • ANDROID_SDK_ROOT = /opt/android/sdk
    • Java binary at: /usr/lib/jvm/java-11-openjdk-amd64/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
    • cmake version 3.16.3
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
    • pkg-config version 0.29.1
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Ubuntu 20.04.1 LTS 5.4.0-1021-gcp

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

</details>

**Comment by matanlurey** [comment]
@ericbomgardner: Could you verify your gradle and specifically, Android Gradle Plugin (AGP) version?

**Comment by ericbomgardner** [comment]
I just remembered I created the build not on CircleCI, sorry! 😓

So sharing my relevant (local) setup:
- `7.3.0` AGP
- `7.5.0` Gradle

<img width="1012" alt="Screenshot 2024-02-05 at 1 21 54 PM" src="https://github.com/flutter/flutter/assets/1123786/127669a5-542f-4214-83cb-0cbce182786a">

**Comment by matanlurey** [comment]
@ericbomgardner:

> So sharing my relevant (local) setup:

... and this is the same setup that causes the Play Console report? I'm just trying to understand what's going on here :P

**Comment by gmackall** [comment]
It looks like this desugaring may not be enabled by default:

>To enable support for these language APIs on any version of the Android platform:
>
>1. [Update the Android Gradle plugin](https://developer.android.com/studio/releases/gradle-plugin#updating-plugin) to 4.0.0 (or higher).
>2. Include the following in your app module’s build.gradle or build.gradle.kts file:
[Kotlin](https://developer.android.com/studio/write/java8-support#kotlin-build.gradle.kts)

https://developer.android.com/studio/write/java8-support#library-desugaring

Notably it looks like you need to add `isCoreLibraryDesugaringEnabled = true` to the `compileOptions` block in the `android` block of your app-level build.gradle

**Comment by ericbomgardner** [comment]
> ... and this is the same setup that causes the Play Console report? I'm just trying to understand what's going on here :P

Ah yeah sorry 😅 , here's the full timeline of what has happened specifically for me:
- I uploaded a build created with my local setup (AGP `7.3.0`, Gradle `7.5.0`) to Google Play
  - This build was our first build created with flutter `3.16.9`
- I released the build to an Internal track
- I **didn't** see any issues in my Play Console pre-launch report
- But I **did** see two instances of the `sendUserSettingsToFlutter`: `No interface method anyMatch...` crash in Crashlytics for that version
  - One for `Sdk_goog3_gpc_x86_64`, one for `Redfin 64-bit Only`
  - I figured these crashes were produced during the production of the pre-launch report, since the build was only released to an internal track and those devices were not ones we've tested the build on

Happy to break my experience out of this issue if this issue is specifically for errors shown in the Play Console pre-launch report!

**Comment by gmackall** [comment]
> > Notably it looks like you need to add ...
> 
> Ooh thanks!
> 
> I had `coreLibraryDesugaringEnabled true` but only ...

Note that you specifically need `isCoreLibraryDesugaringEnabled = true`. It looks like `coreLibraryDesugaringEnabled` is the property that was used AGP 4.0, and it was changed to `isCoreLibraryDesugaringEnabled` in AGP 4.1+

**Comment by ericbomgardner** [comment]
I was able to update to version `1.2.2` of `desugar_jdk_libs` (`1.2.3` gave me an error when building [1]), but unfortunately I still got an instance of the same crash on Crashlytics [2] from the pre-launch report run 😢 

Is there a particular release of `desugar_jdk_libs` (https://github.com/google/desugar_jdk_libs/blob/master/CHANGELOG.md) that looks like it would be likeliest to fix this Stream issue?

[1] 

<details>

<summary>Relevant output of `flutter build appbundle`</summary>

```
...
Warning: Specification conversion: The following prefixes do not match any type: [Ljava/time/DesugarDuration, Ljava/time/DesugarLocalTime]
Error: Missing class jdk.internal.misc.Unsafe (referenced from: jdk.internal.misc.Unsafe j$.util.concurrent.ConcurrentHashMap$TreeBin.U and 15 other contexts)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:l8DexDesugarLibRelease'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.L8DexWorkAction
   > Compilation failed to complete

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 16s
Running Gradle task 'bundleRelease'...                             77.0s
Gradle task bundleRelease failed with exit code 1
```

</details>

[2] 

<details>

<summary>Crashlytics screenshot</summary>

<img width="1043" alt="Screenshot 2024-02-05 at 5 37 10 PM" src="https://github.com/flutter/flutter/assets/1123786/28c309d6-ae51-4d7e-b524-7e4456ce0555">


</details>

**Comment by absar** [comment]
Having the same issue with this setup:
AGP 7.4.2
Gradle 7.6
Flutter 3.16.9

Devices:
Android 13 Model: Pixel 7
Android 12 Model: Pixel 6
Android 13 Model: Redfin 64-bit Only
Android 12  Model: Sdk_goog3_gpc_x86_64

Gradle:
```groovy
compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 33
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
    }

dependencies {
    implementation 'androidx.window:window:1.1.0'
    implementation 'androidx.window:window-java:1.1.0'
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.2.2'
}
```

<details>
  <summary>Logs</summary>

```java
Fatal Exception: java.lang.NoSuchMethodError: No interface method anyMatch(Lj$/util/function/Predicate;)Z in class Lj$/util/stream/Stream; or its super classes (declaration of 'j$.util.stream.Stream' appears in /data/app/~~ClomHZ1wF9Ht1xRX8XfRGg==/androidx.test.tools.crawler-X9AdSy8GIeVs08Wk30TI3g==/base.apk!classes2.dex)
       at io.flutter.embedding.android.FlutterView.sendUserSettingsToFlutter(FlutterView.java:51)
       at io.flutter.embedding.android.FlutterView.attachToFlutterEngine(FlutterView.java:263)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onCreateView(FlutterActivityAndFragmentDelegate.java:130)
       at io.flutter.embedding.android.FlutterFragment.onCreateView(FlutterFragment.java:11)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:24)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:208)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:124)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:347)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:81)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:21)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:38)
       at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:11)
       at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:4)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:20)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1543)
       at androidx.test.runner.MonitoringInstrumentation.callActivityOnStart(MonitoringInstrumentation.java:2)
       at android.app.Activity.performStart(Activity.java:8367)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3669)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:224)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:204)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2306)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7918)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)  

```

</details>

**Comment by absar** [comment]
@matanlurey did you get any response from the Google Play Console team
@ericbomgardner did you find any workaround

**Comment by ericbomgardner** [comment]
> @ericbomgardner did you find any workaround

No, I haven't found one

**Comment by camsim99** [comment]
From the response, it seems likely related to how the app was built, like with an older version of Gradle/AGP, but that seems to contradict the reports above. @matanlurey @gmackall did either of you have another interpretation?

**Comment by matanlurey** [comment]
I concur.

I don't think there is anything for us to change on our end, modulo potentially some sort of linting/minimum requirements.

Is it possible, for example:

> Google Ads SDK and no Google UMP SDK

... causes an older AGP to be used

/cc @reidbaker

**Comment by reidbaker** [comment]
I do not think it is possible for dependencies to cause an older AGP version to be used. Since that is a build dependency on the main project.

**Comment by reidbaker** [comment]
@ericbomgardner Is there any way you can get us a reproduction so that we can continue to investigate?

**Comment by absar** [comment]
A few updates:

1. Crash happens very early during the first 3 seconds but somehow the test continues for the full length of 5+ minutes
2. If you see the screen shots, test crashed at `10:47:42 PM` central European time but the test device video starts with time `1:48:33PM` (probably US LA time), does it mean play console/firebase is restarting the test if it fails, since there is almost a minute difference
3. It does not crash on every device and looks like the crash is random, 3 days ago it crashed on `Pixel 7 Android 13`, but it did not crash on the same device today in prelaunch, however it crashed on other devices `Android12 Pixel 6`, `Android 14 Redfin 64-bit Only`
4. If we download the google signed generic APK and run it on an Android 13 emulator it runs without any issues

**From cashlytics:**
![image](https://github.com/flutter/flutter/assets/1186833/e312d44a-aca4-46d8-a964-3266cc5ae953)

**From pre-launch report video:**
![image](https://github.com/flutter/flutter/assets/1186833/ddb84881-385f-4652-b0b6-7ba750b4643b)

**Comment by ericbomgardner** [comment]
> @ericbomgardner Is there any way you can get us a reproduction so that we can continue to investigate?

I think I should have time to try later this week

**Comment by absar** [comment]
Performed below steps to resolve the issue. No issues received during pre-launch. Tested on Android 5, 9, 13 devices, will do a partial production release to see the impact.
Although not sure why was it failing previously even though R8 was putting these in the intermediary output:
```gradle
-keep class j$.util.function.Function
-keep class j$.util.function.Predicate$-CC {
    j$.util.function.Predicate $default$and(j$.util.function.Predicate, j$.util.function.Predicate);
    j$.util.function.Predicate $default$negate(j$.util.function.Predicate);
    j$.util.function.Predicate $default$or(j$.util.function.Predicate, j$.util.function.Predicate);
}
-keep class j$.util.function.Predicate { *; }
-keep class j$.util.stream.Stream {
    boolean anyMatch(j$.util.function.Predicate);
}
```

Hope these steps will help others, though these might not be useful for everyone since both java source and target compatibility is changed:
1. Moved from imperative Gradle to declarative Plugin DSL https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply
2. Upgraded gradle wrapper from gradle-7.6-all to gradle-7.6.4-bin
3. Upgraded sourceCompatibility and targetCompatibility from  JavaVersion.VERSION_1_8 to JavaVersion.VERSION_11
4. Upgraded kotlin jvmTarget from 1.8 to 11
5. Upgraded coreLibraryDesugaring from com.android.tools:desugar_jdk_libs:1.2.2 to com.android.tools:desugar_jdk_libs:2.0.2

Changelog:
![image](https://github.com/flutter/flutter/assets/1186833/0be0d210-2a93-4fea-91ac-cbc265423e05)

![image](https://github.com/flutter/flutter/assets/1186833/3c55dd48-9997-4576-b1c1-dd6d7015ddaf)

![image](https://github.com/flutter/flutter/assets/1186833/e0ebacfc-d174-45fb-b539-408a0e6aafb4)

![image](https://github.com/flutter/flutter/assets/1186833/d0d5a3f6-a23b-4330-9d69-cd9f78f142aa)

**Comment by ericbomgardner** [comment]
I followed the same steps as @absar, and the crashes no longer occur during the pre-launch report generation.

Thanks for posting such detailed steps @absar!

**Comment by PeperMarkreel** [comment]
We had a similar problem. 
The the R8 settings and updating the desugaring lib from absar fixed it. 

This was our stack trace, posted below for future search engine results, 

`Exception java.lang.NoSuchMethodError: No interface method anyMatch(Lj$/util/function/Predicate;)Z in class Lj$/util/stream/Stream; or its super classes (declaration of 'j$.util.stream.Stream' appears in /data/app/~~M8Hw-tgOj_LmO26Ac2Eh5A==/androidx.test.tools.crawler-tdb1_TiyexQeUG34GWRFyw==/base.apk!classes2.dex)
  at io.flutter.embedding.android.FlutterView.sendUserSettingsToFlutter (FlutterView.java:45)
  at io.flutter.embedding.android.FlutterView.attachToFlutterEngine (FlutterView.java:355)
  at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onCreateView (FlutterActivityAndFragmentDelegate.java:355)
  at io.flutter.embedding.android.FlutterActivity.createFlutterView (FlutterActivity.java:84)
  at io.flutter.embedding.android.FlutterActivity.onCreate (FlutterActivity.java:84)
  at android.app.Activity.performCreate (Activity.java:8050)
  at android.app.Activity.performCreate (Activity.java:8030)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1329)
  at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate (MonitoringInstrumentation.java:2)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3608)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3792)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:103)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2210)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:201)
  at android.os.Looper.loop (Looper.java:288)
  at android.app.ActivityThread.main (ActivityThread.java:7839)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:548)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1003)`

**Comment by ZaneCode6574** [comment]
`Exception java.lang.NoSuchMethodError: No interface method anyMatch(Lj$/util/function/Predicate;)Z in class Lj$/util/stream/Stream; or its super classes (declaration of 'j$.util.stream.Stream' appears in /data/app/~~uJWhfr7-2r72uPtUWoKUhw==/androidx.test.tools.crawler-sTD99_belea-YdmMlmJj4A==/base.apk!classes2.dex)
  at io.flutter.embedding.android.FlutterView.sendUserSettingsToFlutter (FlutterView.java:1478)
  at io.flutter.embedding.android.FlutterView.attachToFlutterEngine (FlutterView.java:1208)
  at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onCreateView (FlutterActivityAndFragmentDelegate.java:395)
  at io.flutter.embedding.android.FlutterActivity.createFlutterView (FlutterActivity.java:767)
  at io.flutter.embedding.android.FlutterActivity.onCreate (FlutterActivity.java:641)
  at android.app.Activity.performCreate (Activity.java:8050)
  at android.app.Activity.performCreate (Activity.java:8030)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1329)
  at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate (MonitoringInstrumentation.java:2)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3608)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3792)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:103)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2210)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:201)
  at android.os.Looper.loop (Looper.java:288)
  at android.app.ActivityThread.main (ActivityThread.java:7839)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:548)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1003)`
  
  I have to downgrade Flutter I think.
