### ISSUE TITLE
Images do not render after activity stop/restart with latest Skia

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#14194]
With the current tip of tree engine:
  * Run Gallery
  * Tap the Android task switcher to suspend the app, then tap it again to resume

The background image on the Gallery menu will be blank.

This was introduced in https://github.com/google/skia/commit/966db9e4ee1e5485fce21a5953b426ad8bf95a9d

The FlutterView's GL surface will be destroyed and recreated during the activity stop/start cycle.  With this change, it looks like the cross-context SkImages are no longer usable with the new surface.

@brianosman @egdaniel

**Comment by brianosman** [comment]
The original reason for that was that Vulkan can't wait on the same
semaphore more than once. Seems like we could split the difference and keep
the logic that only waits once on the semaphore, but still allows importing
to other contexts subsequently?

**Comment by tvolkert** [comment]
@brianosman any update on this?  It's blocking our release into Google, and transitively, a release to our dev channel.

**Comment by egdaniel** [comment]
I believe the fix for this was rolled into flutter on Monday. Are you still seeing it as broken? Brian can correct me I'm wrong about the roll.

**Comment by brianosman** [comment]
Yes, sorry - I forgot to update this bug. https://github.com/flutter/engine/pull/4579 should have fixed this issue .
