### ISSUE TITLE
How to map PurchaseStatus enum for payment state value coming from verifyreceipt response to to manually call completePurchase method?

### ISSUE THREAD

**Issue by fldvlpr** [flutter/flutter#141931]
### Steps to reproduce

Hello There,

I'm checking an [in app purchase](https://pub.dev/packages/in_app_purchase) package scenario for one use case.

Initially i make a buyNonConsumable method to purchase a subscription.

After that I make an api call from my server to verifyreceipt which is giving me "payment_state":1 and "acknowledgement_state": 0, 

After then i check for a property like (purchaseDetails.pendingCompletePurchase) which is giving me true and then I'm making a call for completePurchase method. But somehow at that moment my app closed.

So to manage it next time manually I'm having all the data I need in purchaseDetails object in my server, except PurchaseStatus enum.

So can anyone tell me from where can I map it that? Cause even the PurchaseStatus Class of the package is not providing any proper details how to map it or which states are this

So please add the states required or mapped for PurchaseStatus enum in docs.

### Expected results

We need to map have the doc for states required or mapped for PurchaseStatus enum.

### Actual results

We dont have states required to map for PurchaseStatus enum.

### Code sample

```
PurchaseDetails purchaseDetails = PurchaseDetails(
              productID: (activePlanResponse.value.activeResponseItem?.plan
                  ?.productId ?? '').toString(),
              purchaseID
                  : (activePlanResponse.value.activeResponseItem?.plan
                  ?.orderId ?? '').toString(),
              status
                  : getPurchaseStatusById(id: state.toInt()),
              transactionDate
                  : (activePlanResponse.value.activeResponseItem?.plan
                  ?.transactionDate ?? '').toString(),
              verificationData: PurchaseVerificationData(
                  source: activePlanResponse.value.activeResponseItem?.plan
                      ?.source ?? '',
                  localVerificationData: activePlanResponse.value
                      .activeResponseItem?.plan?.localVerificationData ?? '',
                  serverVerificationData
                      : activePlanResponse.value.activeResponseItem?.plan
                      ?.serverVerificationData ?? ''));
          await purchaseDetails.completePurchase(purchaseDetails);
```

Above values I'm fetching from my server and mapping but don't know how to map this PurchaseStatus value. 

I'm getting an error like following when try to map status manually,
updatePurchaseProducts error :'package:in_app_purchase_android/src/in_app_purchase_android_platform.dart': Failed assertion: line 176 pos 7: 'purchase is GooglePlayPurchaseDetails': On Android, the `purchase` should always be of type `GooglePlayPurchaseDetails`.

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4 22F66 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.85.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

**Comment by darshankawar** [comment]
@fldvlpr 
Based on the error you are getting, check if https://github.com/flutter/flutter/issues/82645#issuecomment-841853349 helps in your case or not.
