### ISSUE TITLE
Sample AppLifecycleListener app doesn't work

### ISSUE THREAD

**Issue by sisyfus** [flutter/flutter#141944]
### Steps to reproduce

I tried the "abort app exit" sample app: https://api.flutter.dev/flutter/widgets/AppLifecycleListener-class.html#widgets.AppLifecycleListener.2  (the **second** sample app on that page)
I have tried two phones (Pixel 6/14 & Kogan Agora 9/8.1), and the embedded web app on that same page
As a matter of courtesy, please note that I have also reported this problem as a reply in this issue: https://github.com/flutter/flutter/issues/134255

### Expected results

-  the app should NOT exit when the Back button is tapped, if the radio button is in the "Do Not Allow Exit" state.
-  when the Quit button is tapped, the app should try to exit 

### Actual results

- when the Back button is tapped, the app exits, regardless of the state of the radio button
- when the  Quit button is tapped, nothing ever happens

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.5, on Microsoft Windows [Version 10.0.22631.3007], locale en-AU)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.33)
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.85.1)
[✓] Connected device (4 available)
[✓] Network resources
```

</details>

**Comment by huycozy** [comment]
Hi @sisyfus 
Thanks for the report! 

This is mentioned on an issue being tracked at https://github.com/flutter/flutter/issues/141185 which is a framework issue, please also see https://github.com/flutter/flutter/issues/141185#issuecomment-1896158055. 

Closing this issue as a duplicate, so please follow up on it for further updates.
