### ISSUE TITLE
flutter-devicelab-mac-17 needs to be recovered

### ISSUE THREAD

**Issue by yusuf-goog** [flutter/flutter#142013]
### Type of Request

infra task

### Infrastructure Environment

devicelab

### What is happening?

[flutter-devicelab-mac-17](https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-17) is dead, please recover.

### Steps to reproduce

Step 1:
Step 2:
..
Step n:

### Expected results

I expect to see X when Y is finished.

**Comment by kentnguyen99** [comment]
mac-17 is up and running fine, I can login remotely from my desk.  mac-17 is out of sync with Salt master, ran command "salt state.apply" to re-sync again with Salt master.

flutter-devicelab-mac-17:~ flutter$ uptime
16:25  up 20:38, 3 users, load averages: 1.40 1.62 1.66
