### ISSUE TITLE
Native in Native, how call C code ? ¯\_(ツ)_/¯

### ISSUE THREAD

**Issue by fedor-elizarov** [flutter/flutter#14201]
I want to use a library written in C in my project, can I call functions from there?

for example how call this in flutter/dart 
```
char * hello()
{
    return "hello";
};
```
if i compile this for arm lib.so/lib.a ?

**Comment by felagund18** [comment]
I think it would be Dart <-> Platform channels <-> JNI call

https://flutter.io/platform-channels/
https://developer.android.com/studio/projects/add-native-code.html

**Comment by 1l0** [comment]
https://github.com/flutter/flutter/issues/7053

**Comment by fedor-elizarov** [comment]
th all (◕‿◕) o( ❛ᴗ❛ )o
