### ISSUE TITLE
Sharing code between dartdev and flutter_tools

### ISSUE THREAD

**Issue by dcharkes** [flutter/flutter#142041]
Currently, it is quite hard to share implementation between dartdev and flutter_tools.

* Dartdev outside g3 uses path dependencies via a DEPS file. Meaning that changes in multiple packages can be made in an atomic way.
* Dartdev inside g3 uses the same dependencies in g3, the packages in DEPS are rolled into g3 with the Dart roll.
* flutter_tools outside g3 uses published dependencies. This means that two helper packages in a mono_repo cannot be updated atomically. (For example `native_asset_cli` is imported by `native_assets_builder` but they are in the same mono repo, meaning one always need to commit dependency, publish, commit dependee, publish.)
* flutter_tools inside g3 uses the same packages as are rolled by the Dart SDK. Meaning that no breaking changes can be rolled in the Dart roll rolling these packages if the API is also used in flutter_tools.

> This means that two helper packages in a mono_repo cannot be updated atomically.

We could solve this, if we would depend packages in mono repos by git dependencies and use dependency overrides or use path dependencies inside the mono repo after https://github.com/dart-lang/native/issues/949 is addressed.

@stuartmorgan @christopherfujino So far I only see published dependencies in flutter_tools `pubspec.yaml`. Is git dependencies on mono repos something the Flutter team would consider?

> flutter_tools inside g3 uses the same packages as are rolled by the Dart SDK. Meaning that no breaking changes can be rolled in the Dart roll rolling these packages if the API is also used in flutter_tools.

This could possibly be solved by either (a) having two copies of the packages in google3 @iinozemtsev, or (b) not building flutter_tools at all in g3, or (c) rolling Dart as part of the Flutter roll instead of separately [probably not feasible].

_Maybe I'm holding it wrong, and code between dartdev and flutter_tools should be shared in a different way._ I'm open to suggestions.

Relevant issue for native_assets_builder and native_assets_cli:

* https://github.com/dart-lang/native/issues/949

**Comment by dcharkes** [comment]
@jonasfj and @mkustermann Pointed out that path-dependencies in flutter_tools is no go, because that would mean every Flutter developer would start downloading things from Github instead of pub every time they update Flutter. (It would be okay to have path dependencies if flutter tools would be compiled to a kernel snapshot and that snapshot would be downloaded instead of downloading all the sources.)

**Comment by dcharkes** [comment]
Also, having a published dependency in flutter_tools, and a git-pinned dependency in dartdev means we can potentially have different behavior in `flutter ...` and `dart ...` with the Dart that is shipped in the flutter SDK.

**Comment by christopherfujino** [comment]
> @jonasfj and @mkustermann pointed out that path-dependencies in flutter_tools is no go, because that would mean every Flutter developer would start downloading things from Github instead of pub every time they update Flutter. (It would be okay to have path dependencies if flutter tools would be compiled to a kernel snapshot and that snapshot would be downloaded instead of downloading all the sources.)

my understanding is we're also relying on semver of vm_service and pub to enforce that `flutter_tools` knows how to talk to the dart vm we have in the cache--is that right @bkonyi 

I'm working on finishing up a public doc that will discuss further.

**Comment by bkonyi** [comment]
> my understanding is we're also relying on semver of vm_service and pub to enforce that `flutter_tools` knows how to talk to the dart vm we have in the cache--is that right @bkonyi

Yes, having `vm_service` pinned is important to guarantee that there won't be any incompatibilities between the package's interface and the actual VM service protocol supported by the shipped Dart SDK.

**Comment by dcharkes** [comment]
I think we're in a good state now.

* Any changes to dart-lang/native packages are rolled into the Dart SDK, which is then rolled into g3. Flutter tools no longer depends on these packages in g3 anymore. So this doesn't break flutter_tools in g3.
* Flutter tools is updated in a PR on this repo, and not on Dart rolls. So we don't have to do any manual Dart rolls.

The only downside is:

> Also, having a published dependency in flutter_tools, and a git-pinned dependency in dartdev and then Dart rolling into flutter, means we can potentially have different behavior in `flutter ...` and `dart ...` with the Dart that is shipped in the flutter SDK.

So we should be mindful close to branch cuts that we don't roll changes into Dart and not Flutter or vice versa.
