### ISSUE TITLE
Decimal calculation error in Dart

### ISSUE THREAD

**Issue by salahturkmen** [flutter/flutter#142032]
### Steps to reproduce

While using the print() function to print the result of multiplication operations between two decimal numbers, I noticed that the result is inaccurate. For example, when multiplying the number 149700 by 0.07, the expected result is 10479, but the result obtained is 10479.000000000002. Similarly, when multiplying the number 156 by 12.960, the expected result is 2021.76, but the result obtained is 2021.7600000000002.

I believe that this error is caused by the way Dart represents decimal numbers. Decimal numbers in Dart are stored as binary numbers with unlimited precision, but they are displayed as decimal numbers with limited precision. This means that a small error may occur when displaying the result
void main() {
  print('nummm:${149700 * 0.07}');
  print('nummm:${156 * 12.960}');
}
I recommend fixing this error permanently. This will help ensure the accuracy of calculations for applications that require high accuracy.

### Expected results

nummm:10479
nummm:2021.76

### Actual results

nummm:10479.000000000002
nummm:2021.7600000000002

 

 

 

 

### Flutter Doctor output

C:\src\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 3.16.8, on Microsoft Windows [Version 10.0.19045.3930], locale en-US)
    • Flutter version 3.16.8 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 67457e669f (6 days ago), 2024-01-16 16:22:29 -0800
    • Engine revision 6e2ea58a5c
    • Dart version 3.2.5
    • DevTools version 2.28.5

[√] Windows Version (Installed version of Windows is version 10 or higher)

• No issues found!
Process finished with exit code 0

**Comment by danagbemava-nc** [comment]
This should be reported on the [dart-lang/sdk](https://github.com/dart-lang/sdk/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) repo for consideration from the team. 

Closing from here.
