### ISSUE TITLE
Update DropdownButtonFormField to m3

### ISSUE THREAD

**Issue by Yukinosuke-Takada** [flutter/flutter#142048]
### Use case

The [Material 3 menus](https://m3.material.io/components/menus/overview#b39b2819-a579-4de1-bca2-8d7dbd3b332c) show a new feature:

![image](https://github.com/flutter/flutter/assets/42461864/663b89e1-2063-4e03-a43c-e907328ac2fd)

And in #115005 `DropdownMenu` is updated to m3.

I was using `DropdownButtonFormField` and seems that the form is m3 but the dropdown menu is not.

https://github.com/flutter/flutter/assets/42461864/adfb11b5-022e-4e46-aa5b-8c7583804d83

```dart
enum Currency {
  jpy,
  usd,
  unknown,
}

...

DropdownButtonFormField<Currency>(
  decoration: const InputDecoration(
    border: OutlineInputBorder(),
    hintText: 'Select a currency',
    labelText: 'Currency',
  ),
  value: formData.value.currency,
  onChanged: (value) {
    ...
  },
  items: Currency.values.map((e) {
    return DropdownMenuItem<Currency>(
      value: e,
      child: Text(e.toString().split('.').last),
    );
  }).toList(),
),
```

### Proposal

Update the dropdown menu of `DropdownButtonFormField` to m3

**Comment by Yukinosuke-Takada** [comment]
For my case, I was able to rewrite the `DropdownButtonFormField` section with `DropdownMenu`.

<img width="351" alt="Screenshot 2024-01-24 at 0 30 21" src="https://github.com/flutter/flutter/assets/42461864/2e716ade-696d-4ad8-b830-10c0908a2cad">

```dart
DropdownMenu(
  onSelected: (value) {
    ...
  },
  initialSelection: formData.value.currency,
  label: const Text('Currency'),
  expandedInsets: EdgeInsets.zero,  // <- may require flutter 3.16 or higher. Issue: #129753
  dropdownMenuEntries: Currency.values.map((e) {
    return DropdownMenuEntry(
      label: e.toString().split('.').last,
      value: e,
    );
  }).toList(),
),
```

**Comment by dam-ease** [comment]
Thanks for filing this @Yukinosuke-Takada.
I think this is similar/related to https://github.com/flutter/flutter/issues/141941.
Can you check this out please?

**Comment by Yukinosuke-Takada** [comment]
Oh sorry. Yes, it is the same feature request!
