### ISSUE TITLE
NFC Support 

### ISSUE THREAD

**Issue by asoseil** [flutter/flutter#14209]
Is there a plan to offer APIs to connect and read tags NFC?

**Comment by dpassola** [comment]
This function was interesting and, also, write NFC.

**Comment by xikitidistant** [comment]
I'll be waiting for NFC functionality with candlesticks, or a declaration of intention to develop it! Also write and read with NFC Apis. Thanks!

**Comment by Hixie** [comment]
It should be relatively straight-forward to implement this as a plugin.
The Flutter team doesn't plan on providing such a plugin in the near term, but we would be happy to advise anyone who does. See: https://flutter.io/developing-packages/ and https://flutter.io/platform-channels/
You can also see https://github.com/flutter/plugins for some plugins we have created so far, if you want to use one as a starting point.

**Comment by munukutla** [comment]
Would be happy to take this up. Hope nobody else is working on it?

**Comment by munukutla** [comment]
@Hixie, assign it to me. I'm already working on it.

**Comment by munukutla** [comment]
[nfc | Flutter Package](https://pub.dartlang.org/packages/nfc)

Work in progress. Reads text data from NFC tags. Supported on Android 6.0

**Comment by NathanaelA** [comment]
@munukutla -

   Awesome; thanks for working on this -- I am going to need NFC in an app I'm going to be working on...


@Hixie - Any good advice on how to deal with this Sync API (besides flutter/engine#4358) for Chaitanya?   
https://developer.android.com/reference/android/nfc/NfcAdapter.CreateNdefMessageCallback.html
(I don't actually need this API call myself at this time, but others might....)

**Comment by guyulmaz** [comment]
Isodep read write iso 14443 type a cards, for example mifare desfire cards, would be great with NFC plugin

**Comment by ConProgramming** [comment]
@munukutla Any progress on that plugin being able to write NFC?

**Comment by GiulioIzzo** [comment]
Any progress with the plugin? The phrase "This is a work in progress. It might be unstable. DO NOT USE IN PRODUCTION"  discourages a lot from using it.

**Comment by munukutla** [comment]
@ConProgramming @GiulioIzzo give it a try now. Fixed some issues.

**Comment by GiulioIzzo** [comment]
It gives me this error:
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (23, 10): Expecting ')
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (21, 47): Type mismatch: inferred type is () -> Unit but Boolean was expected
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (29, 9): Unresolved reference: nfcAdapter
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (30, 17): Unresolved reference: nfcAdapter
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (32, 17): 'return' is not allowed here
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (35, 26): Unresolved reference: intent
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (39, 38): Unresolved reference: Intent
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (41, 13): Unresolved reference: NfcAdapter
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (44, 17): Unresolved reference: MIME_TEXT_PLAIN
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (46, 53): Unresolved reference: Tag
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (46, 58): Unresolved reference: NfcAdapter
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (47, 34): Unresolved reference: execute
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (50, 17): Unresolved reference: Log
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (52, 20): Unresolved reference: NfcAdapter
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (55, 49): Unresolved reference: Tag
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (55, 54): Unresolved reference: NfcAdapter
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (57, 32): Unresolved reference: Ndef
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (61, 38): Unresolved reference: execute
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (68, 43): Unresolved reference: Activity
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (68, 62): Unresolved reference: NfcAdapter
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (69, 22): Unresolved reference: Intent
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (70, 24): Unresolved reference: Intent
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (72, 29): Unresolved reference: PendingIntent
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (74, 36): Unresolved reference: IntentFilter
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (78, 22): Unresolved reference: IntentFilter
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (79, 31): Unresolved reference: NfcAdapter
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (80, 33): Unresolved reference: Intent
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (82, 37): Unresolved reference: MIME_TEXT_PLAIN
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (83, 21): Unresolved reference: MalformedMimeTypeException
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (90, 42): Unresolved reference: Activity
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (90, 61): Unresolved reference: NfcAdapter
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (94, 42): Unresolved reference: AsyncTask
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (94, 52): Unresolved reference: Tag
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (96, 9): 'doInBackground' overrides nothing
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (96, 37): Forbidden vararg parameter type: [ERROR : Tag]
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (96, 52): Unresolved reference: Tag
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (99, 24): Unresolved reference: Ndef
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (102, 36): Unresolved reference: cachedNdefMessage
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (106, 39): Unresolved reference: NdefRecord
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (106, 68): Unresolved reference: Arrays
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (106, 99): Unresolved reference: NdefRecord
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (109, 33): Unresolved reference: UnsupportedEncodingException
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (110, 25): Unresolved reference: Log
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (119, 17): Unresolved reference: UnsupportedEncodingException
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (119, 17): An annotation parameter must be a compile-time constant
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (120, 38): Unresolved reference: NdefRecord
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (143, 99): Unresolved reference: Charset
e: C:\Users\gii\Desktop\dev\flutter\.pub-cache\hosted\pub.dartlang.org\nfc-0.0.4\android\src\main\kotlin\io\flutter\plugins\nfc\NfcPlugin.kt: (146, 9): 'onPostExecute' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':nfc:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by GiulioIzzo** [comment]
It gives me this error:
FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':nfc:compileDebugKotlin'.
Compilation error. See log for more details

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org

BUILD FAILED in 2s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by truongsinh** [comment]
see also https://github.com/matteocrippa/flutter-nfc-reader

**Comment by matteocrippa** [comment]
If you want can look into it and make a pr for that porting the plugin

**Comment by matteocrippa** [comment]
I was thinking, @Hixie is a worth place to put that under `/packages/flutter/lib/src/services`?

Or you prefer somewhere else? I was trying porting my plugin back to java/objc and move there: https://github.com/matteocrippa/flutter/tree/feature/nfc

And later add under /engine/shell the native implementation, but not idea if is a good move, also because it will add by default also the lib for corenfc to any app

**Comment by fengerzh** [comment]
@c16a For NFC, the best user experience is to use it when phone in lock screen mode, thus we need NFC event for App, will the package support NFC event?

**Comment by MatyasK** [comment]
> see also https://github.com/matteocrippa/flutter-nfc-reader by @matteocrippa

I'm trying to use this in my application, but the built-in tags app keeps overwrite it when a tag is read it opens the tags app. 
Any suggestion @matteocrippa ?

**Comment by stuartmorgan** [comment]
Closing, as this isn't within the scope of things we would build a Flutter-team-owned plugin for; community plugins would be the solution here, as noted above.
