### ISSUE TITLE
tool tests failing from pub failures

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#142161]
For example:

https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20tool_integration_tests_4_4/14596

January 22, 14:41 PT

```
01:13 +7 -1: test/integration.shard/break_on_framework_exceptions_test.dart: breaks when EditableText.onChanged throws [E]                                                                             
  Exception: flutter pub get failed: Note: matcher is pinned to version 0.12.16+1 by flutter_test from the flutter SDK.
  See https://dart.dev/go/sdk-version-pinning for details.
  
  
  Because every version of flutter_test from sdk depends on matcher any which doesn't exist (could not find package matcher at https://pub.dev/), flutter_test from sdk is forbidden.
  So, because test depends on flutter_test from sdk, version solving failed.
```

~https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20tool_integration_tests_4_4/14452
January 12, 13:20 PT~  Update, per [this comment](https://github.com/flutter/flutter/issues/142161#issuecomment-1909704657) this was a pub backend outage

```
06:54 +36 -1: test/integration.shard/deferred_components_test.dart: simple build appbundle android-arm64 target succeeds [E]                                                                           
  Exception: flutter pub get failed: 502 Bad Gateway trying to find package vector_math at https://pub.dev/.
  
  Resolving dependencies...
  
  test/integration.shard/test_utils.dart 65:5                getPackages
  ===== asynchronous gap ===========================
  test/integration.shard/test_data/project.dart 66:5         Project.setUpIn
  ===== asynchronous gap ===========================
  test/integration.shard/deferred_components_test.dart 32:5  main.<fn>
```

At first I thought this might have been a temporary outage, but given they were 10 days apart, now I'm not so sure. @jonasfj & @sigurdm do you know of any outages or any other possible reasons for this?

Alternatively, it might have just been two unrelated bad network requests and I'm looking too closely :)

**Comment by sigurdm** [comment]
The first one (Jan 12th) is almost definitely a short outage we had:
![image](https://github.com/flutter/flutter/assets/8613953/8ae683ef-5bac-4453-b595-d99e98cad1e4)

The second one I'm not sure can be ascribed to an outage...

**Comment by jonasfj** [comment]
```
matcher is pinned to version 0.12.16+1 by flutter_test from the flutter SDK.
  See https://dart.dev/go/sdk-version-pinning for details.
  
  
  Because every version of flutter_test from sdk depends on matcher any which doesn't exist (could not find package matcher at https://pub.dev/), flutter_test from sdk is forbidden.
  So, because test depends on flutter_test from sdk, version solving failed.
```

This seems more like a version conflict, but the "could not find package matcher at https://pub.dev/" suggests that pub.dev returned 404 for "matcher". Which it definitely shouldn't do -- or we have a bug in `pub` client interpreting an error as package not found.

**Comment by christopherfujino** [comment]
> This seems more like a version conflict, but the "could not find package matcher at https://pub.dev/" suggests that pub.dev returned 404 for "matcher".

Yeah, my uninformed guess was that the pub client got a 404 querying matcher and concluded it doesn't exist.

**Comment by christopherfujino** [comment]
Ok, so I think the first one we don't need to track, pub server did experience an outage that was quickly resolved.

@jonasfj Shall I file a bug on pub for the other one, that the client should have reported a better error?

**Comment by a-siva** [comment]
@christopherfujino yes I think we should file a bug for the other issue and close this one.
