### ISSUE TITLE
VSBuild (Windows) tasks seem to be extra flaky recently, and might impact tree green-ness disproportionately 

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#142197]
### Type of Request

bug

### Infrastructure Environment

_I'm not sure what environment, sorry._

### What is happening?

https://ci.chromium.org/ui/p/flutter/builders/prod/Windows_arm64%20run_debug_test_windows/1321/overview

In this case VSBuild hung for over an hour.

### Steps to reproduce

_I'm not sure, sorry_.

### Expected results

The build should not turn red, causing gardeners to have to scramble, just to turn green due to no intervention (i.e. either just waiting for automatic re-runs to turn the tree green, or manually clicking buttons to re-run to turn the tree green). We need to have a CI system that only (or nearly only) turns red when human intervention is required.

**Comment by christopherfujino** [comment]
@matanlurey is it true that VSBuild is extra flaky recently? I have never seen this particular error.

**Comment by matanlurey** [comment]
At least a few times this week I saw windows builds failing, I'll admit I didn't check the logs for details - so perhaps this issue should be retitled as "windows builders" or such

**Comment by vashworth** [comment]
Saw a couple times recently that made the tree red:
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20build_tests_6_7/905/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20build_tests_5_7/896/overview

**Comment by loic-sharma** [comment]
Unassigning myself as VS installation flakes are currently below the 2% threshold. The infra team is working on improving diagnostics so that we can investigate this issue.

**Comment by godofredoc** [comment]
Change to add timeouts and logging of the vs_build installation: https://flutter-review.googlesource.com/c/recipes/+/55163

**Comment by godofredoc** [comment]
With the recipes change vs_build installation failures will be easier to triage. I'll land one more optimization and move to P3 for monitoring.

**Comment by godofredoc** [comment]
Logic to install vs_build only if it is not already installed: https://flutter-review.googlesource.com/c/recipes/+/55407

Closing this bug as completed. The optimizations will remove the remaining timeout failures during the installation process.
