### ISSUE TITLE
error : package io.flutter.plugins.sharedpreferences does not exist , after upgrade flutter

### ISSUE THREAD

**Issue by Alaa-Edeen** [flutter/flutter#142142]
### Steps to reproduce

1.run flutter upgrade 
2.stop package shared preferences 

### Expected results

this error show agter run flutter pub upgrade 

### Actual results

s

### Code sample

D:\windows\flutter_project\salfa_game\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:34: error: package io.flutter.plugins.sharedpreferences does not exist
      flutterEngine.getPlugins().add(new io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin());
                                                                             ^
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
Error: Gradle task assembleDebug failed with exit code 1

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by Alaa-Edeen** [comment]
can you help me ?

**Comment by huycozy** [comment]
Hi @Alaa-Edeen, which Flutter version are you working on? Could you share the output of `flutter doctor -v`? 

If you see this issue on Flutter beta channel, there is a known issue at https://github.com/flutter/flutter/issues/141940.
