### ISSUE TITLE
Google Sign In 

### ISSUE THREAD

**Issue by kakelay** [flutter/flutter#142106]
### Use case

I use this package google_sign_in: 6.1.4.
login with  IOS work as normal but for android didn't work . i stuck with this  issues . 

Run and debug on VScode and Response : 

error : PlatformException (PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null))

message : "com.google.android.gms.common.api.ApiException: 10: "

### Proposal

google_sign_in: 6.1.4.

**Comment by dam-ease** [comment]
Hello @kakelay 
I see there are similar issues, Please follow-up in:

https://github.com/flutter/flutter/issues/75224
https://github.com/flutter/flutter/issues/33393

Closing this as a duplicate.
