### ISSUE TITLE
Build Flutter on WebOS (LG Smart TV)

### ISSUE THREAD

**Issue by pachecotatih** [flutter/flutter#142135]
### Use case

Can I build an app in flutter using WebOS? by LG Smart TV?

### Proposal

The idea is create an app from smart tv LG. I wanna support to flutter  LG Smart TV

**Comment by darshankawar** [comment]
@pachecotatih 
Check if [this](https://forum.webostv.developer.lge.com/t/can-we-expect-webos-support-flutter-sometime-soon/995) helps to answer your question / case or not.

Also check below links for your reference:

https://stackoverflow.com/questions/76916358/flutter-web-app-incredibly-slow-on-brand-new-lg-tv-webos-6-0-signage

**Comment by pachecotatih** [comment]
Thanks!!! But my issue is execute as an app to LG TV and when I execute the code in Simulator, returns flutter.js not found in console

**Comment by darshankawar** [comment]
You might want to check https://developer.samsung.com/smarttv/develop/native/flutter.html which seems to be for Samsung smart TV. 
If you are looking to support specifically LG, then the request might belong to LG TV developers and may need to reach out to them.

**Comment by pachecotatih** [comment]
> You might want to check https://developer.samsung.com/smarttv/develop/native/flutter.html which seems to be for Samsung smart TV. If you are looking to support specifically LG, then the request might belong to LG TV developers and may need to reach out to them.

It's specificly from LG TV.

**Comment by darshankawar** [comment]
> It's specifically from LG TV.

This seems specific to particular brand of TV which is niche use case for which I don't think there will be a support feature by Flutter. 
Just like Flutter Tizen which is specific to Samsung and developed by them itself, your proposal for LG tv support most probably need to come from LG tv development team. So I think you need to raise this proposal in LG TV's community here https://forum.webostv.developer.lge.com/

Closing from here, as the request to support LG smart tv specifically doesn't seem to be feasible from Flutter sdk side. If you disagree, write in comments and I'll reopen it.
