### ISSUE TITLE
Document adding CocoaPods dependency when developing plugins

### ISSUE THREAD

**Issue by xster** [flutter/flutter#14214]
https://flutter.io/developing-packages/

Describe what to do when adding a CocoaPod dependency to the plugin's CocoaPod itself

**Comment by Sfshaza** [comment]
@xster, is this documented anywhere?

**Comment by xster** [comment]
I'm closing this bug. I suspect newer documentations were added since I opened this issue. https://flutter.io/developing-packages/#dependencies was the info I was looking for.
