### ISSUE TITLE
Flutterfire plugins should not use dynamic dependency versions on Android

### ISSUE THREAD

**Issue by rock3r** [flutter/flutter#14210]
## Steps to Reproduce

Try building an app with `cloud_firebase` `^0.2.6`, you may observe on some systems an error when building such as:

```
Multiple dex files define Lcom/google/android/gms/internal/zzbf
```

This happened to me when working on https://github.com/dart-lang/conference_app/pull/43, for example. After clearing all Gradle and Android Gradle Plugin build caches, the issue disappeared, but it may well happen to anyone who updates a dependency and then tries to build immediately.

This is due to the various levels of caching that happen in Gradle, where a failed resolution may cause the build system to pick a cached version of a dependency, which may not be compatible with the other(s). This leads to unreproducible builds and the risks of having some users for which things don't work. Diagnosing these issues, due to their transient and random nature, is very complicated.

For all these reasons, using dynamic dependencies versions is a [strongly discouraged practice](http://blog.danlew.net/2015/09/09/dont-use-dynamic-versions-for-your-dependencies/) on Android.

The issue can be solved by simply specifying a single, hardcoded version for the dependencies in the plugins' `build.gradle` files:

```groovy
dependencies {
    api 'com.google.firebase:firebase-firestore:11.8.0'
    api 'com.google.firebase:firebase-core:11.8.0'
}
```

## Flutter Doctor

```
$ flutter doctor
[✓] Flutter (on Mac OS X 10.13.2 17C205, locale en-GB, channel master)
    • Flutter version 0.0.21-pre.287 at /Users/rock3r/src/flutter
    • Framework revision 159db5ca44 (2 days ago), 2018-01-20 14:43:23 -0800
    • Engine revision e45eb692b1
    • Tools Dart version 2.0.0-dev.16.0
    • Engine Dart version 2.0.0-edge.93d8c9fe2a2c22dc95ec85866af108cfab71ad06

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.2)
    • Android SDK at /Users/rock3r/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.2
    • ANDROID_HOME = /Users/rock3r/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.1 Preview.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.3.3)
    • Flutter plugin version 21.0.3
    • Dart plugin version 173.4301.22

[✓] Connected devices
    • Pixel XL • HT73V0201200 • android-arm • Android 8.1.0 (API 27)
```

**Comment by rock3r** [comment]
CC @filiph @collinjackson

**Comment by kroikie** [comment]
@rock3r

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/908. Any further collaboration will be done there.
