### ISSUE TITLE
Fluter hot reload

### ISSUE THREAD

**Issue by isgetzz** [flutter/flutter#142107]
### Steps to reproduce

Android 13  can't be hot loaded, but lower versions can

### Expected results

can hot reload

### Actual results

android 13 button cannot be clicked

### Code sample

<details open><summary>Code sample</summary>

![image](https://github.com/flutter/flutter/assets/24540369/b9a09d1e-f0b1-47b7-993e-aa1efd553fb6)
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
  • Flutter version 3.16.6 on channel stable at C:\Users\merit\AppData\Local\Android\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 46787ee49c (2 weeks ago), 2024-01-09 14:36:07 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
</details>

**Comment by danagbemava-nc** [comment]
Hi @isgetzz, what button are you referring to? 

Do you have this issue if you run your app using the cli instead of your IDE/text editor?
