### ISSUE TITLE
[Impeller] Proposal: Create a per-frame Canvas arena

### ISSUE THREAD

**Issue by bdero** [flutter/flutter#142191]
This is an idea for a short-term solution to drastically reduce heap allocation eliminate refcounting overhead for Aiks and Entity layer resources. This would mean removing all `shared_ptr` usage for all `Contents`, `Geometry`, `ColorSources`, etc.

* `impeller::Picture` goes away, `impeller::Canvas` becomes the "renderable" primitive.
* `Canvas::DrawPicture` consumes a whole `Canvas` along with its arena instead of a `Picture`.
* At the end of `Canvas::Render(AiksContext&)` or `Canvas::RenderToTexture`, arena is cleared and `Canvas` state reset.
* `Canvas` tracks the `Paint`, no methods take a `Paint&` anymore.
* `impeller::ColorSource` is no longer part of the public API, instead we have `Paint::SetLinearGradient(...)`, etc.
* _All_ `std::make_shared`/`std::make_unique` is removed in Aiks. Instead use `arena_ptr<T> Arena::Make<T>(...)`. `arena_ptr<T>::operator*` is zero cost in prod. In debug, it holds a generation int + a reference to the `Arena` itself and asserts that the generations match. If they don't, then there's a lifetime/state reset bug.

**Comment by gaaclarke** [comment]
I attempted this in the past and gave up since in order to get the most benefit the things allocated in the arena should be trivially destructible so we can just trash the block of memory; refactoring everything to be trivially destructible was a heavy lift: https://github.com/flutter/engine/compare/main...gaaclarke:engine:arena

We could potentially store the destructor with the data and call the destructors and still have some of the benefit though.

**Comment by chinmaygarde** [comment]
Is this still a viable proposal? Seems like a pretty invasive update to the API for gains I am not able to understand.

**Comment by bdero** [comment]
The CPU performance situation has vastly improved since this was written, and we have longer term efforts that should eventually take care of the same performance problems this proposal aims to solve, so I don't think we should spend time on this. Closing.

More details:

Impeller does lots of heap allocations and shared_ptr destructions, and the overhead for this was found to be significant. Using a per-frame arena is an idea to eliminate most of it.

At this point, a bunch of work has been done towards combining Entities/Aiks/DL Dispatcher, which is expected to eventually remove the bulk of this overhead by getting us to a state where we're passing around plain old pointers to DisplayList primitives most of the time.
