### ISSUE TITLE
Suggestion to update StreamBuilder documentation for best practices on Stream initialization - as already updated with FutureBuilder.

### ISSUE THREAD

**Issue by mendelg** [flutter/flutter#142189]
### Use case

According to the documentation [on FutureBuilder](https://api.flutter.dev/flutter/widgets/FutureBuilder-class.html) the `Future` should be obtained during `initState` or the like):

> The [future](https://api.flutter.dev/flutter/widgets/FutureBuilder/future.html) must have been obtained earlier, e.g. during [State.initState](https://api.flutter.dev/flutter/widgets/State/initState.html), [State.didUpdateWidget](https://api.flutter.dev/flutter/widgets/State/didUpdateWidget.html), or [State.didChangeDependencies](https://api.flutter.dev/flutter/widgets/State/didChangeDependencies.html). It must not be created during the [State.build](https://api.flutter.dev/flutter/widgets/State/build.html) or [StatelessWidget.build](https://api.flutter.dev/flutter/widgets/StatelessWidget/build.html) method call when constructing the [FutureBuilder](https://api.flutter.dev/flutter/widgets/FutureBuilder-class.html). If the [future](https://api.flutter.dev/flutter/widgets/FutureBuilder/future.html) is created at the same time as the [FutureBuilder](https://api.flutter.dev/flutter/widgets/FutureBuilder-class.html), then every time the [FutureBuilder](https://api.flutter.dev/flutter/widgets/FutureBuilder-class.html)'s parent is rebuilt, the asynchronous task will be restarted.

The reason for is that otherwise, it would be refetched on every rebuild [as explained in my StackOverflow Q&A](https://stackoverflow.com/q/77760360/12349734)

### Proposal

Just as the `FutureBuilder` documentation advises initializing the future in `initState` or an equivalent lifecycle method, I believe it would be highly beneficial for the `StreamBuilder` documentation to include similar guidance. This would help prevent common pitfalls, such as streams being recreated on every build, leading to unnecessary rebuilds and potential performance issues.

I propose adding a section or note to the `StreamBuilder` documentation emphasizing the importance of initializing the stream in a stable manner, similar to the advice given for `FutureBuilder`. This could include a brief explanation and a code snippet demonstrating the recommended practice.

Such an update would greatly assist developers in understanding and implementing StreamBuilder more effectively, ensuring more robust and efficient Flutter applications.

Related:
-  #112676

**Comment by goderbauer** [comment]
Sounds good. PRs are welcome!
