### ISSUE TITLE
Update wiki to have new instructions for how to handle reverts for Gardener Rotation

### ISSUE THREAD

**Issue by eliasyishak** [flutter/flutter#142180]
The current wiki has instructions for the Gardener rotation to revert a PR by manually opening a new one via the Github UI. We need to update the instructions to tell the gardener on duty to use the label `revert` on the PR that has _already_ been merged and let the bots handle the revert.

**Comment by eliasyishak** [comment]
@jonahwilliams I created an issue to make sure I get the wiki fixed.

To confirm, is the only thing we have to do now just adding the `revert` label to the PR that caused the tree to go red?

**Comment by cbracken** [comment]
If you add the label within 24 hours of the patch landing, and it's cleanly revertible then yes. Otherwise the previous manual process applies.

**Comment by eliasyishak** [comment]
Ah, 🤦‍♂️ I totally skipped over that part in the wiki. This issue isn't necessary anymore. @cbracken thank you for clearing that up
