### ISSUE TITLE
[CP] Cherrypick DWDS version 23.0.0+1 into Flutter beta 

### ISSUE THREAD

**Issue by elliette** [flutter/flutter#142169]
### Issue Link

https://github.com/dart-lang/webdev/issues/2316, https://github.com/dart-lang/webdev/issues/2309

### Target

beta

### PR Link

https://github.com/flutter/flutter/pull/142168

### Changelog Description

Updates DWDS (dependency of flutter_tools) to a hotfix release version. This hotfix release version is identical to the current DWDS version in Flutter beta, except it includes the following fixes:

- Filter out internal type properties from the new DDC type system. - [#2348](https://github.com/dart-lang/webdev/pull/2348)
- Fix errors on displaying getters when debugging in VS Code. - [#2343](https://github.com/dart-lang/webdev/pull/2343)

See https://pub.dev/packages/dwds/versions/23.0.0+1/changelog

### Impacted Users

Flutter developers using a debugger to inspect variables

### Impact Description

- [#2348](https://github.com/dart-lang/webdev/pull/2348): Fixes issue where developers would see type parameters during variable inspection 
- [#2343](https://github.com/dart-lang/webdev/pull/2343): Fixes issue when a user is debugging in VS Code where they would see an error for `hashcode` and `runtimeType` properties 

### Workaround

No

### Risk

low

### Test Coverage

yes

**Comment by christopherfujino** [comment]
This LGTM
