### ISSUE TITLE
Microtask semantics have been broken

### ISSUE THREAD

**Issue by 0xZOne** [flutter/flutter#142194]
After #flutter/engine/pull/25789, it cannot be guaranteed that microtasks are processed before an event is processed.

Per https://dart.cn/articles/archive/event-loop:
>The microtask queue is necessary because event-handling code sometimes needs to complete a task later, but before returning control to the event loop. For example, when an observable object changes, it groups several mutation changes together and reports them asychronously. The microtask queue allows the observable object to report these mutation changes before the DOM can show the inconsistent state.

Some discussions on Discord:
https://discord.com/channels/608014603317936148/608022273152122881/1199628106890215505 

See also: https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/

**Comment by mraleph** [comment]
cc @chinmaygarde 
cc @a-siva @lrhn @mkustermann @rmacnak-google - this does seem like a serious violation of microtask semantics

**Comment by lrhn** [comment]
> this does seem like a serious violation of microtask semantics

Maybe! But probably not really.

It very much depends on what "Pause dart microtasks while UI thread is processing frame workloads" _means_.
What happens while paused. If nothing at all, it's just a big lag spike, which is not invalid.

This does not appear to affect the web. If it had, it would almost certainly be broken.

On native, I don't believe we have the same hard link between top level events and microtasks, where the top level event doesn't end until microtasks are done, and things can happen when an event ends (like database transactions committing).

That means that breaking the microtask queue into two parts, and doing something in the middle, is effectively just doing "something" _as_ a microtask. That is perfectly valid, as long as "something" doesn't run top level events.

So as long as whatever the UI thread does, or the current thread does while microtasks are paused (if not nothing) is not running things defined as top-level events, the pause is really just another microtask.

This may feel like a violation of microtask ordering, if something gets to run in the middle of the queue without scheduling itself, but we don't actually _promise_ that much about microtask ordering (IIRC). Multiple tasks scheduled using `scheduleMicrotask` during the same microtask, will be executed in the order they were scheduled, and before any top level event. That's the only strong guarantee.
They will _most likely_ be executed after all previously scheduled microtasks.
And futures _may_ schedule microtasks to report their results, but they don't always.
(We have internal functions that schedule events at the front of the root microtask queue, which shouldn't be detectable, but we can and do cheat with the queue ordering when we can get away with it. And anyone can implement their own microtask queue using zones, which can break even those few promises.)

**Comment by mraleph** [comment]
@lrhn that was my initial reaction as well, but my concern here is that we stop microtask queue but not the event loop. So maybe top-level events can still be delivered and processed, which would certainly violate the expected ordering. 

If top level events _are_ paused as well - then I agree that pausing microtask queue processing is more or less the same as introducing "priorities" where some microtasks are processed ahead of other microtasks. Which might be fine because particular order of unrelated microtasks can't be relied upon anyway.

**Comment by mkustermann** [comment]
@0xZOne Is the issue you filed rooted into an actual misbehavior of an application? If so, do you have a reproduction?

**Comment by lrhn** [comment]
> this does seem like a serious violation of microtask semantics

Maybe! But probably not really.

It very much depends on what "Pause dart microtasks while UI thread is processing frame workloads" _means_.
What happens while paused. If nothing at all, it's just a big lag spike, which is not invalid.

This does not appear to affect the web. If it had, it would almost certainly be broken.

On native, I don't believe we have the same hard link between top level events and microtasks, where the top level event doesn't end until microtasks are done, and things can happen when an event ends (like database transactions committing).

That means that breaking the microtask queue into two parts, and doing something in the middle, is effectively just doing "something" _as_ a microtask. That is perfectly valid, as long as "something" doesn't run top level events.

So as long as whatever the UI thread does, or the current thread does while microtasks are paused (if not nothing) is not running things defined as top-level events, the pause is really just another microtask.

This may feel like a violation of microtask ordering, if something gets to run in the middle of the queue without scheduling itself, but we don't actually _promise_ that much about microtask ordering (IIRC). Multiple tasks scheduled using `scheduleMicrotask` during the same microtask, will be executed in the order they were scheduled, and before any top level event. That's the only strong guarantee.
They will _most likely_ be executed after all previously scheduled microtasks.
And futures _may_ schedule microtasks to report their results, but they don't always.
(We have internal functions that schedule events at the front of the root microtask queue, which shouldn't be detectable, but we can and do cheat with the queue ordering when we can get away with it. And anyone can implement their own microtask queue using zones, which can break even those few promises.)

**Comment by dnfield** [comment]
Is there a failing test case that we could look at?

**Comment by zanderso** [comment]
Is there a user-facing issue here that can be demonstrated by a concrete test or real use case?

**Comment by 0xZOne** [comment]
@mkustermann @lrhn Thank you guys for the detailed analysis.

This indeed does not break the semantics of microtasks.

As long as the events in the secondary queue have not been processed, there is no logical sequence between the tasks in the microtask queue and them. Therefore, the microtask queue can be safely drained without the concern of disrupting semantics.

**Comment by 0xZOne** [comment]
Maybe we should rename `PauseDartMicroTasks` to avoid confusion.

**Comment by 0xZOne** [comment]
> @0xZOne Is the issue you filed rooted into an actual misbehavior of an application? If so, do you have a reproduction?

No, the semantics of microtasks does not seem very clear from the code, so it has been brought up for discussion.

**Comment by dnfield** [comment]
I've filed https://github.com/dart-lang/sdk/issues/54749 as something that I _think_ would help  identify what user-facing (or developer-facing) problems can come up here. In a sufficiently large flutter app it's nearly impossible to figure out where all the microtasks are coming from if you end up getting a lot of them. If you're getting too many, it probably doesn't matter a ton whether they're getting scheduled before or after frame workload - what you really want is to figure out if there any you could remove (e.g. from a widget or package or plugin that's over scheduling microtasks).

**Comment by mkustermann** [comment]
> Maybe we should rename PauseDartMicroTasks to avoid confusion.

Yes. Sent https://github.com/flutter/engine/pull/50138 to rename those methods.
