### ISSUE TITLE
Build is missing RBE logs when timeout

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#142249]
Earlier issue was reported missing logs when timeout happens:
https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Engine%20Drone/631801/overview

http://go/flutter-cl/54100 was landed to attempt to address the issue, but seems it's still missing though some "progress":
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Production%20Engine%20Drone/248801/overview

**Comment by keyonghan** [comment]
My guess is the build level timeout caused the logs missing. We can try exiting earlier within the build step, collect logs in `finally` and then re-throw the exception.

**Comment by keyonghan** [comment]
@zanderso is `30 mins` a reasonable number to measure a build step timeout? With rbe/goma, the build step takes <10mins. I am thinking to define a build step timeout property from `.json` file, with which recipes can exit early to catch the logs, instead of waiting for the whole build to timeout (60 mins).

This should also help fail the build earlier if hanging.

**Comment by zanderso** [comment]
If a build takes longer than 30 minutes is there any way to collect the logs without failing the build?

**Comment by keyonghan** [comment]
https://flutter-review.googlesource.com/c/recipes/+/54521 to collect logs without exiting the build.

**Comment by keyonghan** [comment]
This has been validated to work. Closing.
