### ISSUE TITLE
[GoRouter] Navigate to a StatefulShellBranch from outside the StatefulShellRoute while preserving its navigation stack

### ISSUE THREAD

**Issue by jackmaring** [flutter/flutter#142226]
### Use case

I'm running into an issue using GoRouter where I'm trying to navigate the bottom navbar tabs programmatically if coming from a page that is outside the stateful shell route.

For example if you observe this route hierarchy:

<img width="239" alt="Screenshot 2024-01-25 at 10 19 58 AM" src="https://github.com/flutter/flutter/assets/19756358/18e8673b-75e8-4c1e-bd02-2075bee6b0db">

The navigation flow is you go from B Tab -> About Page -> A Tab, but when you pop from the About Page it shows the B Tab and when you use context.go(A Tab), the A Tab resets its current navigation stack.

### Proposal

I would want to be able to programmatically go to a specific StatefulShellBranch if the route is outside the StatefulShellRoute while also preserving the bottom navbar's current navigation stack. So I would want to be able to follow the path B Tab -> About Page -> A Tab, while also preserving the A Tab's current navigation stack.

**Comment by dam-ease** [comment]
Thanks for proposing this @jackmaring.
Can you check out this SO answer to see if it works in your case
https://stackoverflow.com/a/76712337?

**Comment by jackmaring** [comment]
@dam-ease this article refers to when you are navigation from a StatefulShellBranch to outside the StatefulShellRoute which can be seen in the first part of the navigation flow (Tab B -> About Page). My question is referring to the other way around, going from a route outside the StatefulShellRoute to a StatefulShellBranch, so from Tab B -> About Page -> Tab A. This can be achieved by using context.go(Tab A), but this removes Tab A's current navigation stack.

**Comment by chunhtai** [comment]
When you said navigate from Tab B-> About Page, did you mean push or go?

Can you provide an runnable example so that it would be easier to debug?
