### ISSUE TITLE
Consume scrolling behavior that occurs in sub-widgets.

### ISSUE THREAD

**Issue by MTtankkeo** [flutter/flutter#142289]
### Use case

In Flutter, nested scrolling is handled by delegating activity between scrollable. However, this logic might not work flexibly in certain situations.

There's a problem where the parent widget can't consume the scroll action occurring in the child widget.
When using the RefreshIndicator in Android, an unnatural behavior occurs.
This problem seems to be caused by the parent widget not being able to absorb the scroll action occurring in the child widget.

I wish a feature like `modifier.nestedScroll of android jetpack compose` was provided to allow developers to flexibly handle such behavior.

I tried to solve this problem at the package level, but failed. 😭

## Use currently `RefreshIndicator`:
https://github.com/flutter/flutter/assets/122026021/b00bbe9e-a9cf-40b0-ab99-66366509341d

### Proposal

Would it be possible to provide a feature that propagates the scroll offset to the parent widget before it's reflected, to determine whether it should be consumed or not?

**Comment by Piinks** [comment]
Hi @MTtankkeo can you clarify the issue with some sample code? The RefreshIndicator is not a scrollable widget, so I am not familiar with how this related to nested scrolling.
https://github.com/flutter/flutter/issues/50946 may also be the same issue, would you mind taking a look? Thank you!

**Comment by MTtankkeo** [comment]
The RefreshIndicator is just an example for this issue.

RefreshIndicator is not related to nested scrolling in flutter, but performs its own behavior based on the behavior of the child scroll widget.
But the problem is, it's only consuming, and the child scroll widget performs its own behavior in an implicitly individualistic way, regardless of what RefreshIndicator does.

Flutter does not support the behavior of multiple parent widgets consume single child scroll behavior.

I don't believe that nested scroll behavior is only able by scrollable widgets.

## Difference
https://github.com/flutter/flutter/assets/122026021/9f1075a0-e3d0-419a-b9df-26bc6fdfc096
https://github.com/flutter/flutter/assets/122026021/1667e3df-8564-4c08-8c1e-05b533efaf67

**Comment by MTtankkeo** [comment]
I want a feature similar to this.
```
NestedScrollConnection(
      onPreScroll: (available) {
        // Consume all scrolling offset that occurred,
        // Therefore, the child scrollable widget continues to old offset. (newOffset - consumed)
        return available;
      },
      onPostScroll: (available) {
        // Available is always 0 because it's all consumed.
        //
        // When the scroll offset is calibrated by the clamping operation,
        // the remaining offset is available.
        return available;
      },
      child: ListView.builder(
        itemCount: 100,
        itemBuilder: (context, index) {
          return TouchRipple(
            child: Text("Hello World $index", style: const TextStyle(color: Colors.white)),
          );
        },
      ),
    );
```

**Comment by Piinks** [comment]
This is already possible using ScrollNotification: https://api.flutter.dev/flutter/widgets/ScrollNotification-class.html

**Comment by MTtankkeo** [comment]
I understand that Notification widget only listens.

**Comment by Piinks** [comment]
I am not sure I understand the expectation @MTtankkeo. Can you explain further what you would like to be able to do?
