### ISSUE TITLE
[go_router] Redirect to force user login allows navigate back to homepage

### ISSUE THREAD

**Issue by ddodi1** [flutter/flutter#142210]
### What package does this bug report belong to?

go_router

### What target platforms are you seeing this bug on?

Android, Web

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.0.1
```

</details>

### Steps to reproduce

At app opening, I want to force the user to log-in, using redirect if a login state variable is false.

### Expected results

I expect the app closes on clicking back button.

### Actual results

Clicking on the back button, the user is able to navigate to the home page.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:go_router/go_router.dart';
import 'package:flutter/material.dart';

final router = GoRouter(
    routes: [
      GoRoute(
        path: '/',
        builder: (context, state) {
          return const HomePage();
        },
        routes: [
          GoRoute(
              path: 'login-page',
              builder: (context, state) {
                return const LoginPage();
              }
          ),
        ]
      ),
    ],
    redirect: ((context, state) {
      if (true) { // instead of true, a login state variable
        return '/login-page';
      }
      // return null;
    }),
);

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerConfig: router,
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Home page'),
      ),
      body: const Center(
        child: Text('Home page')
      ),
    );
  }
}

class LoginPage extends StatelessWidget {
  const LoginPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Login page'),
      ),
      body: const Center(
          child: Text('Login page')
      ),
    );
  }
}
```

</details>

### Screenshots or Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

![Screenshot 2024-01-25 071147](https://github.com/flutter/flutter/assets/157674335/5e4ece5a-c94b-47fa-80dc-367c49895001)

</details>

### Logs

<details open><summary>Logs</summary>

```console

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.8, on Microsoft Windows [Versione 10.0.22631.3007], locale it-IT)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.3)
[√] Android Studio (version 2022.3)
[√] Connected device (3 available)
[√] Network resources

• No issues found!

```

</details>

**Comment by dam-ease** [comment]
Hello @ddodi1.
This occurs across platforms and seems to be caused by your logic inside redirect callback. 
Can you double-check your implementation there and refer to sample code here https://github.com/flutter/packages/blob/main/packages/go_router/example/lib/redirection.dart to see if it works in your case?

**Comment by ddodi1** [comment]
Hello, referring to the sample code, I found that the two GoRoutes must be at the same level. 'login-page' can't be nested in '/'. Thanks.
