### ISSUE TITLE
HTTP(S) 1.1 GET/PUT/POST/DELETE is implemented

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#1422]
This might just be a matter of testing our conformance.
- [ ] GET
- [ ] PUT
- [ ] POST
- [ ] DELETE
- [ ] SSL
- [ ] Custom headers
- [ ] Custom mimetype
- [ ] HTTP 1.1
- [ ] One supported high-level package or library (currently: http)
- [ ] Rationalization with dart:io's Http classes
- [ ] Supported low-level library (?)
- [ ] Android
- [ ] iOS
- [ ] gzip encoding
- [ ] proxy support
- [ ] Docs
- [ ] Custom user agent

Another way to look at this:
- [ ] Provide a supported low-level Socket interface from the engine
- [ ] Provide a supported high-level package for awesome HTTP

**Comment by sethladd** [comment]
Related: https://github.com/flutter/flutter/issues/1366

**Comment by Hixie** [comment]
See also https://github.com/flutter/flutter/issues/1051

**Comment by eseidelGoogle** [comment]
This bug is just about testing (which is important!), but I don't think we're going to get to unittesting all this before the Hackathon.  https://pub.dartlang.org/packages/http has tests which we may be able to reuse.

**Comment by abarth** [comment]
Fixed.  We now outsource this to package:http.
