### ISSUE TITLE
Error connecting android sdk

### ISSUE THREAD

**Issue by nchakrawarty** [flutter/flutter#14225]
I have updated android studio but still when i run flutter i get error like 

C:\Users\SON\calculator>flutter doctor
[√] Flutter (on Microsoft Windows [Version 10.0.10240], locale en-IN, channel alpha)
    • Flutter at C:\Users\SON\flutter
    • Framework revision 8f65fec5f5 (6 weeks ago), 2017-12-12 09:50:14 -0800
    • Engine revision edaecdc8b8
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.d8ae797298c3a6cf8dc9f4558707bd2672224d3e

[-] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at C:\Users\SON\AppData\Local\Android\sdk
    • Android NDK at C:\Users\SON\AppData\Local\Android\sdk\ndk-bundle
    • Platform android-26, build-tools 26.0.2
    X Android SDK file not found: C:\Users\SON\AppData\Local\Android\sdk\build-tools\26.0.2\aapt.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.io/setup/#android-setup for detailed instructions.

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[-] Connected devices
    • None

**Comment by xqwzts** [comment]
I just ran into this too, for some reason my `Android/Sdk/build-tools/26.0.2` folder got corrupted.

Deleting and reinstalling it worked for me:
- delete: `Android/Sdk/build-tools/26.0.2`
- Open AndroidStudio
- Tools > Android > SDK Manager
- SDK Tools
- Check `Show Package Details`
- Find `26.0.2` under Android SDK Build-Tools
- Select
- Apply

**Comment by Hixie** [comment]
Reinstalling is what the message suggests, so I'm going to close this. Not clear that there's anything more we can do... If you have any ideas, don't hesitate to file a new bug.

**Comment by OneBlog** [comment]
Help Me Please ..
wandi@wandi:~/flutter$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.11.11, on Linux, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices
    ✗ No valid Android SDK platforms found in /usr/lib/android-sdk/platforms. Directory
      was empty.
[✓] Android Studio (version 3.2)
[!] VS Code (version 1.28.2)
[!] Connected device
    ! No devices available

**Comment by zoechi** [comment]
Have you tried above suggestions?

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .
