### ISSUE TITLE
Flutter requires the Rosetta translation environment on ARM Macs

### ISSUE THREAD

**Issue by astronaute77** [flutter/flutter#142296]
### Steps to reproduce

Hi,

I get the following error when running `flutter doctor` on 3.16.8:

```
╰─ flutter doctor                                                                                                    ─╯
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.16.8, on macOS 14.2.1 23C71 darwin-arm64, locale en-AE)
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information.
      Flutter requires the Rosetta translation environment on ARM Macs. Try running:
        sudo softwareupdate --install-rosetta --agree-to-license
```

The ticket referenced is closed and I’m unable to find an open ticket to track.

### Actual results

Flutter reports an error related to missing Rosetta

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

╰─ flutter doctor                                                                                                    ─╯
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.16.8, on macOS 14.2.1 23C71 darwin-arm64, locale en-AE)
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information.
      Flutter requires the Rosetta translation environment on ARM Macs. Try running:
        sudo softwareupdate --install-rosetta --agree-to-license

</details>

**Comment by darshankawar** [comment]
@astronaute77 


> ```
> Flutter requires the Rosetta translation environment on ARM Macs. Try running:
>         sudo softwareupdate --install-rosetta --agree-to-license
> ```

Can you run the said command and check if it helps to resolve the error ?

**Comment by astronaute77** [comment]
@darshankawar I would like to use Flutter without Rosetta and my question is about tracking the progress towards removing this requirement from Apple Silicon. Again, flutter doctor references an issue that is closed. 
Where the progress can be tracked now?

**Comment by darshankawar** [comment]
@astronaute77 
Check if [this](https://github.com/flutter/flutter/wiki/Developing-with-Flutter-on-Apple-Silicon) document helps in your case or not.

**Comment by astronaute77** [comment]
@darshankawar this document invites users to install Rosetta. 
My question is whether or not, flutter will one day NOT require Rosetta. I have difficulties finding a ticket where this feature is tracked.

**Comment by darshankawar** [comment]
> My question is whether or not, flutter will one day NOT require Rosetta. I have difficulties finding a ticket where this feature is tracked.

See if [this](https://github.com/flutter/flutter/issues/103386) is what you are looking for ?

**Comment by astronaute77** [comment]
This is exactly it, thank you (it might be useful to update the flutter doctor message and target this ticket instead)

**Comment by darshankawar** [comment]
Thanks for the update. I'll close this issue since you've found the correct issue to follow-up.


> it might be useful to update the flutter doctor message and target this ticket instead)

I'll ask this to the team if this need to be updated.
