### ISSUE TITLE
ListWheelViewport should set needsCompositing

### ISSUE THREAD

**Issue by xster** [flutter/flutter#14224]
In the example https://github.com/xster/flutter-test/blob/master/t71_text_transform_rendering_2/lib/main.dart

TransformLayers without text works. canvas.transform works. But TransformLayers with text no longer works.

**Comment by jason-simmons** [comment]
This was introduced when we stopped applying a cull rectangle to the PaintingContext's canvas:
    https://github.com/flutter/flutter/commit/0434ae22ec69c6b91d2cfa00ac715a68942446de

The transform will render correctly if you revert to constructing `new Canvas(_recorder, estimatedBounds)` in PaintingContext._startRecording

**Comment by xster** [comment]
Thanks for the hint. I'm not super sure what what the instructive is from the RenderObject's perspective. The PaintingContext is already created.

**Comment by Hixie** [comment]
That's weird. Bug in skia?

**Comment by xster** [comment]
Tried on tip of skia and messed around a bit but couldn't figure it out. 

https://bugs.chromium.org/p/skia/issues/detail?id=7537

**Comment by xster** [comment]
This issue is no longer reproducible on head. Closing.

**Comment by xster** [comment]
The issue reappeared on skia head.

**Comment by xster** [comment]
Seems to have broken between engine e61bb9ac3a3fd789754e2e54220bcfc27076a857 and 3e877d371a359097d7af28aa6e85026fa2318baa

**Comment by jason-simmons** [comment]
This bug was reintroduced by https://github.com/flutter/engine/commit/c9da0000e2faa1acd0d466cd9ab3f662bd8d9f8f

That commit replaces an SkCanvas::save()/restore() with an equivalent translate/untranslate in order to work around another Skia bug (see https://bugs.chromium.org/p/skia/issues/detail?id=7739)

**Comment by jslavitz** [comment]
@xster Looks like this works now! 
![screenshot_20181025-141650](https://user-images.githubusercontent.com/7806031/47530999-1fb23480-d861-11e8-828b-64f10bb79236.png)

**Comment by xster** [comment]
Cool. Must have been fixed upstream. We should change https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/list_wheel_viewport.dart#L896 to `needsCompositing` then close this issue.

**Comment by LongCatIsLooong** [comment]
The issue should be fixed on master, despite having a visual glitch: #41654. Closing
