### ISSUE TITLE
FlexibleSpaceBar title overflows on top of AppBar actions

### ISSUE THREAD

**Issue by gnawf** [flutter/flutter#14227]
This is a regression, it worked fine in the past. However, I don't remember the last good commit. It broke with one of the commits made in the past few weeks.

<img src="https://user-images.githubusercontent.com/9077461/35275137-97949010-00a3-11e8-8ec2-980e119b65ea.png" height=410/>

## Steps to Reproduce

Run the sample code, the bug should be visible immediately.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(new Sample());
}

class Sample extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: new Scaffold(
        body: new CustomScrollView(
          slivers: <Widget>[
            new SliverAppBar(
              actions: <Widget>[
                new IconButton(
                  icon: new Icon(Icons.cancel),
                  onPressed: null,
                ),
                new IconButton(
                  icon: new Icon(Icons.cancel),
                  onPressed: null,
                ),
              ],
              flexibleSpace: const FlexibleSpaceBar(
                title: const Text(
                    "asdfkljsdfkljsdfkalskdfjalksdjflksjdflkasjdflkasjdfkljasdlfkj"),
                centerTitle: false,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

## Logs

Running flutter run and flutter analyze did not output anything.

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.13.2 17C88, locale en-NZ, channel master)
    • Flutter version 0.0.21-pre.294 at /Users/gnawf/flutter
    • Framework revision 8059aea365 (10 hours ago), 2018-01-22 18:12:39 -0800
    • Engine revision 171d032f86
    • Tools Dart version 2.0.0-dev.16.0
    • Engine Dart version 2.0.0-edge.93d8c9fe2a2c22dc95ec85866af108cfab71ad06

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.3)
    • Android SDK at /usr/local/opt/android-sdk/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-26, build-tools 26.0.3
    • ANDROID_HOME = /usr/local/opt/android-sdk/
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_144-b01)

[-] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    ✗ Your Mac needs to enabled for developer mode before using Xcode for the first time.
      Run 'sudo DevToolsSecurity -enable' to enable developer mode.
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    • CocoaPods version 1.3.1

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2017.3.3)
    • Flutter plugin version 21.0.3
    • Dart plugin version 173.4301.22

[✓] Connected devices
    • iPhone 8 • 533B1ADF-56E5-4A63-9319-1F704E8845E0 • ios • iOS 11.2 (simulator)
```

**Comment by tolbard** [comment]
I have a similar problem the title doesn't wrap correctly and hide AppBar Actions when small or start and finish out of the screen when expanded.

![screen shot 2018-11-28 at 7 51 44 pm](https://user-images.githubusercontent.com/1523058/49143724-5e974680-f347-11e8-85b0-2fac21bf7203.png)
![screen shot 2018-11-28 at 7 50 36 pm](https://user-images.githubusercontent.com/1523058/49143726-5e974680-f347-11e8-909e-35fc1425aedb.png)
![screen shot 2018-11-28 at 7 50 21 pm](https://user-images.githubusercontent.com/1523058/49143729-5f2fdd00-f347-11e8-9549-53d090ea0a4b.png)

**Comment by ljfantin** [comment]
any news about this ?

**Comment by odhs** [comment]
Try this: on the widget Text use:

Text("Your Title", maxLines:1, overflow:TextOverflow.fade )

**Comment by dulkith** [comment]
Any fix?

**Comment by Dancovich** [comment]
Issue still happening in Flutter 1.5.4-hotfix.2

When I build a layout like this, the ellipsis appear when the title is collapsed but it seems the FlexibleSpaceBar is just scaling the text when it expands, which in turn doesn't update the Text widget size in order for it to update the ellipsis.

```dart
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: CustomScrollView(
        scrollDirection: Axis.vertical,
        slivers: <Widget>[
          SliverAppBar(
            expandedHeight: 260.0,
            primary: true,
            pinned: true,
            flexibleSpace: FlexibleSpaceBar(
              centerTitle: false,
              title: Text(
                "Sample of Very Long Text that Overflows the Title",
                maxLines: 1,
                style: TextStyle(shadows: <Shadow>[
                  Shadow(offset: Offset(2, 2), blurRadius: 3),
                ]),
                overflow: TextOverflow.ellipsis,
              ),
              collapseMode: CollapseMode.parallax,
            ),
          ),
          SliverList(
            delegate: SliverChildListDelegate(
              <Widget>[
                SizedBox(
                  height: 1500,
                )
              ]
            ),
          )
        ],
      ),
    );
  }
```
![Screenshot_1559592054](https://user-images.githubusercontent.com/1204296/58830751-6c44c600-8621-11e9-9f9b-490003a5dcc1.png)

![Screenshot_1559592056](https://user-images.githubusercontent.com/1204296/58830755-7070e380-8621-11e9-9827-50b0a7e90559.png)

**Comment by mdmad7** [comment]
Same issue as Dancovich. Any fix?

**Comment by Dancovich** [comment]
> Same issue as Dancovich. Any fix?

I've created a workaround but I need to test for other device sizes. Basically I use a controller and add a listener to monitor the scrolling. When the scrolling pass a certain threshold I change a flag that will place  a `ConstrainedBox` around the title to compensate for the scaling, which in turn will place the ellipsis at the correct place.

Right now both the threshold and the width of the `ConstrainedBox` are hardcoded. I'll do some testing and figure out a way to use `MediaQuery` to get values that will work for all devices.

```dart
bool _isScrollLimitReached = false;
ScrollController _scrollController;

// On initState
_scrollController = ScrollController();
_scrollController.addListener((){
  final newState = _scrollController.offset <=
    (_scrollController.position.minScrollExtent + 120.0);

  if (newState != _isScrollLimitReached) {
    setState(() {
      _isScrollLimitReached = newState;
    });
  } 
});

// ... on the scaffold body
return CustomScrollView(
  controller: _scrollController,
  scrollDirection: Axis.vertical,
  slivers: <Widget>[
    SliverAppBar(
      expandedHeight: 260.0,
      primary: true,
      pinned: true,
      actions: <Widget>[
        IconButton(
          icon: Icon(Icons.edit),
          tooltip: Localization.of(context).getString(Strings.edit_game),
          onPressed: _onGameEdit,
        )
      ],
      flexibleSpace: FlexibleSpaceBar(
        // This is what adjusts the ellipsis based on the size of the text
        title: _isScrollLimitReached
          ? ConstrainedBox(
            constraints: BoxConstraints(maxWidth: 200),
            child: Text(
              _currentGame.name,
              maxLines: 1,
              style: TextStyle(shadows: <Shadow>[
                Shadow(offset: Offset(2, 2), blurRadius: 3),
              ]),
              overflow: TextOverflow.ellipsis,
            ),
          )
          : Text(
            _currentGame.name,
            maxLines: 1,
            overflow: TextOverflow.fade,
          ),
        background: Stack(
          fit: StackFit.expand,
          children: <Widget>[
            FutureImage(
              relativePath: _currentGame.cover,
              fit: BoxFit.cover,
              alignment: Alignment.center,
              imageSemanticsLabel:
              Localization.of(context).getString(Strings.edit_game),
            ),
            Container(
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  begin: Alignment.topCenter,
                  end: Alignment.bottomCenter,
                  colors: [
                    AppColors.colorPrimary[800],
                    AppColors.colorPrimary[800],
                    Color(0x00000000),
                    Color(0x00000000),
                  ],
                  stops: [0.0, 0.05, 0.5, 1.0],
                ),
              ),
            ),
          ],
        ),
        collapseMode: CollapseMode.parallax,
      ),
    ),
    // other slivers
  ],
);
```

**Comment by dimsuz** [comment]
I dug into a `FlexibleSpaceBar` sources and at least now I understand what happens. Turns out that in an expanded state `title` is scaled up to be `1.5` of its size, so naturally it will overflow offscreen. As user scrolls up, `title` is scaled down towards its source size of `1.0`. At this size it will sit in the top toolbar.

Maybe this information will help someone to base their workarounds on until this is fixed.

I wondered why my hack of wrapping title in `ConstraintedBox` with `maxWidth: MediaQuery.of(context).size.width` didn't work. Now I know: I must divide this  `maxWidth` by `1.5`.

**Comment by rolurq** [comment]
Is there any update about this? I need the title in the FlexibleSpaceBar to have its width limited to the space between the leading widget and the actions

**Comment by pkitatta** [comment]
Hi. Any chance we have a fix on this?

**Comment by luminkhant** [comment]
Hi, does anybody solve current problem ?

**Comment by da-revo** [comment]
This needs to be fixed
...by someone smart

**Comment by cronos88** [comment]
Same issue with flutter version: 1.9.1+hotfix 6

**Comment by tiagofischer** [comment]
The problem is that he `FlexibleSpaceBar` widget just scales everything (up to 1.5).
I found a workaround, please check here: https://stackoverflow.com/questions/53251903/title-not-displaying-correctly-on-flexiblespacebar/60231860#60231860
This code can be use as an insight, so the "same changes" can be done inside the `FlexibleSpaceBar` widget.

**Comment by erperejildo** [comment]
still facing the issue. Any update?

**Comment by perclasson** [comment]
The fact that the `FlexibleSpaceBar` overflow `AppBar.actions` is by design. From the [SliverAppBar.flexibleSpace documentation](https://api.flutter.dev/flutter/material/SliverAppBar/flexibleSpace.html):
> This widget is stacked behind the toolbar and the tab bar. It's height will be the same as the app bar's overall height.

See the first two solutions below for that issue. To solve the issue of the expanded SilverAppBar not cropping the title in its expanded state, see the third solution below.

## Solution 1: Use the title directly inside of SliverAppBar
To make sure that the title does not overflow the buttons, you can use the title inside of SliverAppBar directly, [see dartpad](https://dartpad.dev/5a42e322f4ecfc7638d9ba279191f70c).

```dart
SliverAppBar(
  title: Text(
    "asdfkljsdfkljsdfkalskdfjalksdjflksjdflkasjdflkasjdfkljasdlfkj",
    overflow: TextOverflow.ellipsis,
  ),
  ...,
)
```

## Solution 2: Set padding on the FlexibleSpaceBar
If you need to use the FlexibleSpaceBar, you can also set the title padding to avoid the title to overflow, [see dartpad](https://dartpad.dev/a5a43e7c2b8f0b4fb5a9e062934f9c0e).
```dart
flexibleSpace: const FlexibleSpaceBar(
  title: const Text(
    "asdfkljsdfkljsdfkalskdfjalksdjflksjdflkasjdflkasjdfkljasdlfkj",
    maxLines: 1,
    overflow: TextOverflow.ellipsis,
  ),
  centerTitle: false,
  titlePadding: const EdgeInsetsDirectional.only(start: 72, bottom: 16, end: 102),
),

```

## Solution 3: Create custom title that takes the transform effect into consideration
If you have a SliverAppBar with expanded height or that stretches when it overflows, the title will be [transformed](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/flexible_space_bar.dart#L381) to increase in size. This can mean that the title overflows:
<img src="https://user-images.githubusercontent.com/1770678/75149384-1c071a00-5702-11ea-9bca-d931a9eecdc2.png" width="200">

To solve this you can create your own custom title to set the constraints correctly. This solution makes use of of the `FlexibleSpaceBarSettings` that is used for the resizing. See [dartpad for full code](https://dartpad.dartlang.org/d4c5b0189de31e0eb685f4ae83c34bb5):
```dart
class _Title extends StatelessWidget {
  const _Title({
    Key key,
    this.text,
  }) : super(key: key);

  final String text;

  @override
  Widget build(BuildContext context) {
    final settings = context.dependOnInheritedWidgetOfExactType<FlexibleSpaceBarSettings>();
    final deltaExtent = settings.maxExtent - settings.minExtent;
    final t = (1.0 - (settings.currentExtent - settings.minExtent) / deltaExtent).clamp(0.0, 1.0) as double;
    final scaleValue = Tween<double>(begin: 1.5, end: 1.0).transform(t);
    return LayoutBuilder(
      builder: (context, constraints) {
        return Container(
          width: constraints.maxWidth / scaleValue,
          child: Text(
            text,
            maxLines: 1,
            overflow: TextOverflow.ellipsis,
          ),
        );
      }
    );
  }
}
```
It will then be cropped correctly:
<img src="https://user-images.githubusercontent.com/1770678/75149401-245f5500-5702-11ea-8cc3-eceed0b81381.png" width="200">
