### ISSUE TITLE
Flutter unable to relocate to other path without errors

### ISSUE THREAD

**Issue by Syf-Almjd** [flutter/flutter#142229]
### Steps to reproduce

1. make a folder with multiple dart files
2. change path of folder 
3. error comes 

### Expected results

In normal setting and with just one .dart file path change it works but for dictionary change it doesnt

### Actual results

Should relocate easily and change import files path 

</details>

**Comment by dam-ease** [comment]
Thanks for filing this @Syf-Almjd.
From your steps this seems to be with changes in path in the import, are you unable to change the import file names?

> Should relocate easily and change import files path

This seems to be more of a proposal than a bug, can you help with more information on the use-case or how you are proposing this should be changed?
