### ISSUE TITLE
Add the parameters of the output video format in image_picker pickVideo.

### ISSUE THREAD

**Issue by LoveBabyForeve** [flutter/flutter#142291]
### Use case

Add the parameters of the output video format in image_picker pickVideo.

### Proposal

```
final XFile? video = await _picker.pickVideo(
      source: ImageSource.camera,
      preferredCameraDevice: CameraDevice.rear,
      maxDuration: const Duration(seconds: 60),
      **_type: Type.mp4_** 
    );
```

**Comment by dam-ease** [comment]
Thanks for proposing this @LoveBabyForeve
This is similar to https://github.com/flutter/flutter/issues/85623.
Kindly upvote, comment and follow up on that issue for updates.
I'll be closing this in favor of the already existing issue, if you disagree, please comment and I'll reopen this.
Thank you!

**Comment by LoveBabyForeve** [comment]
非常感谢你的回复，但是我的问题和他的不太一样，我的需求是在打开相机后，进行拍照或者拍视频后，可配置**输出**文件的格式，比如图片的jpg、png等，视频的mp4、avi等。

**Comment by LoveBabyForeve** [comment]
更准确点说，是希望在pickImage和pickVideo函数中添加一个参数来决定输出文件的格式。
如代码中被**包括的部分： 
```
  Future<XFile?> pickImage({
    required ImageSource source,
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    CameraDevice preferredCameraDevice = CameraDevice.rear,
    bool requestFullMetadata = true,
   **OutPutImageType type: OutPutType.jpg**
  })



Future<XFile?> pickVideo({
    required ImageSource source,
    CameraDevice preferredCameraDevice = CameraDevice.rear,
    Duration? maxDuration,
    **OutPutVideoType type: OutPutType.MP4**
  })
```
添加一个OutPutImageType / OutPutVideoType type的参数

**Comment by stuartmorgan** [comment]
This would need evaluation as to whether it's even possible; the underlying platform APIs may or may not expose this level of control. (E.g., on Android this would presumably require an intent flag if it's even possible, and even then would probably only be honored by some pickers.)

**Comment by LoveBabyForeve** [comment]
首先，我们可以先做到统一的输出格式，如：图片为jpg，视频为mp4。

目前在使用pickVideo的时候，android输出的格式为mp4，ios则是mov，这给大家带来非常的不便。

**Comment by LoveBabyForeve** [comment]
MP4格式的适用性更加的广泛。

**Comment by stuartmorgan** [comment]
The system-provided image picker controls that `image_picker` provides access to do not provide APIs to control details of camera behavior. Applications that need to specifically configure image capture behavior would need to use `camera` or a similar plugin that interacts directly with camera APIs, and build their own UI, instead of using a the system-provided picker UI.

**Comment by LoveBabyForeve** [comment]
能否告知一下，为什么这个需求被拒绝了？
