### ISSUE TITLE
[tool_crash] HttpException

### ISSUE THREAD

**Issue by ignasiusrajagukguk** [flutter/flutter#142217]
## Command
```
flutter run --machine --start-paused -d emulator-5554 --devtools-server-address http://127.0.0.1:9101/ --target /home/programmer/toddoo_event_production/lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
HttpException
```

```
```
[✓] Flutter (Channel stable, 3.13.7, on Ubuntu 22.04.3 LTS 6.5.0-14-generic, locale en_US.UTF-8)
    • Flutter version 3.13.7 on channel stable at /home/programmer/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2f708eb839 (4 months ago), 2023-10-09 09:58:08 -0500
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/programmer/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /opt/android-studio-2022.2.1/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2022.2)
    • Android Studio at /opt/android-studio-2022.2.1/android-studio
    • Flutter plugin version 75.1.1
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[!] Android Studio (version unknown)
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version unknown)
    • VS Code at /snap/code/current
    • Flutter extension version 3.80.0
    ✗ Unable to determine VS Code version.

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Ubuntu 22.04.3 LTS 6.5.0-14-generic
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 116.0.5845.96

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 2f708eb8396e362e280fac22cf171c2cb467343c
### Plugins
biometric_fingerprint-0.0.7
biometric_signature-2.0.0
camera-0.10.5+5
camera_android-0.10.8+12
camera_avfoundation-0.9.13+6
camera_web-0.3.2+3
device_info_plus-9.1.1
file_selector_linux-0.9.2+1
file_selector_macos-0.9.3+3
file_selector_windows-0.9.3+1
flutter_local_notifications-16.3.2
flutter_plugin_android_lifecycle-2.0.16
flutter_vibrate-1.3.0
google_mlkit_commons-0.6.1
google_mlkit_text_recognition-0.11.0
image_cropper-4.0.1
image_cropper_for_web-2.0.0
image_picker-0.8.9
image_picker_android-0.8.8+1
image_picker_for_web-2.2.0
image_picker_ios-0.8.8+2
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
path_provider-2.1.1
path_provider_android-2.2.1
path_provider_foundation-2.3.1
path_provider_linux-2.2.1
path_provider_windows-2.2.1
pdfx-2.4.0
qr_code_scanner-1.0.1
shared_preferences-2.2.2
shared_preferences_android-2.2.1
shared_preferences_foundation-2.3.4
shared_preferences_linux-2.3.2
shared_preferences_web-2.2.1
shared_preferences_windows-2.3.2
url_launcher-6.2.2
url_launcher_android-6.2.0
url_launcher_ios-6.2.1
url_launcher_linux-3.1.1
url_launcher_macos-3.1.0
url_launcher_web-2.2.0
url_launcher_windows-3.1.1
video_player-2.7.2
video_player_android-2.4.10
video_player_avfoundation-2.5.0
video_player_web-2.1.1
video_thumbnail-0.5.3

**Comment by dam-ease** [comment]
Hello @ignasiusrajagukguk.
I see similar issues to this currently open
https://github.com/flutter/flutter/issues/141889
https://github.com/flutter/flutter/issues/142217
https://github.com/flutter/flutter/issues/79748
Can you provide more information on any of these issues if you have any.
Closing this as a duplicate.
