### ISSUE TITLE
Would like an example of how to write/run a performance test for a Flutter app

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#14237]
We have our own performance tests (which are public), but we don't really have a good example for developers to use themselves for testing the performance of their app.

One example would be to show an example of replicating the Flutter Gallery missed frames benchmark with a simpler sample app.

Another example could be showing how to benchmark some piece of business logic just like @mraleph showed in his Talk at DartConf.

This bug may be too general to track here, but wanted to write this down for our medium-term docs/examples planning.  FYI @mjohnsullivan

**Comment by zoechi** [comment]
Is this covered by 
https://flutter.io/docs/testing/ui-performance
https://flutter.io/docs/cookbook/testing/integration/profiling
?

**Comment by zoechi** [comment]
Issue moved to [flutter/website #2065](https://github.com/flutter/website/issues/2065) via [**ZenHub**](https://www.zenhub.com/)
