### ISSUE TITLE
flutter web app appears Colors.grey.shade100

### ISSUE THREAD

**Issue by ademirtug** [flutter/flutter#142390]
### Steps to reproduce

1. Create a new project using VsCode name it fbug1
2. Copy paste the following code. 
3. now build your project using "flutter build web --base-href /fbug1/  --release"
4. browse fbug1/build/web
5. right click and select "open with VsCode"
6. Click source control and then publish to github
7. name your project fbug1 and commit files as a public project.
8. Browse your project in github
9. Click settings -> pages
10. Under branch section select main and then click save
11. Browse your github pages and you will see an entire screen painted with Colors.grey.shade100
12. Go back to your source code remove Padding encircling "Sometext2"
13. Re-upload your changes, now you see can see a non-empty page.

### Expected results

Pair of text, as I can see in my development machine(Edge Browser).

### Actual results

Blank screen with Colors.grey.shade100

### Code sample

<details open><summary>Buggy Code
</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Bug',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: MyHomePage(title: 'Bug Test'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.grey.shade900,
      body: SingleChildScrollView(
        child: Column(
          children: [getContainer1()],
        ),
      ),
    );
  }

  Widget getContainer1() {
    return Column(children: [
      SizedBox(
        height: 50,
      ),
      Wrap(
        children: [
          Padding(
            padding: EdgeInsets.only(left: 20, bottom: 50, right: 30),
            child: ClipRRect(
              borderRadius: BorderRadius.circular(15),
              child: Text(
                    "Sometext1",
                    style: Theme.of(context).textTheme.bodyMedium?.copyWith(color: Colors.blue),
                  ),
            ),
          ),
          Column(
            children: [
              Padding(
                padding: EdgeInsets.only(left: 20, bottom: 20),
                child: Expanded(
                  child: Text(
                    "Sometext2",
                    style: Theme.of(context).textTheme.bodyMedium?.copyWith(color: Colors.blue),
                  ),
                ),
              ),
            ],
          ),
        ],
      )
    ]);
  }
}

```

</details>

[Expected Result](https://ademirtug.github.io/fbug1/)
[Actual Result](https://ademirtug.github.io/fbug2/)

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.16.0, on Microsoft Windows [Version 10.0.22621.3007], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.3)
[√] Android Studio (version 2023.1)
[√] Android Studio (version 2023.1)
[√] VS Code (version 1.85.2)
[√] Connected device (2 available)
[√] Network resources
```

</details>

**Comment by arnold-parge** [comment]
Can you please upload a screenshot of the expected result and the actual result?

**Comment by ademirtug** [comment]
> Can you please upload a screenshot of the expected result and the actual result?

Added two github project links named Expected and Actual Result.

**Comment by danagbemava-nc** [comment]
@ademirtug, this is an issue with your code. `Expanded` can only be used as a child of a `Column`, `Row` or other similar `Flex` widgets. 

The reason you may not see this issue when you use `Expanded` as a child of a `Padding` is debug mode is because of https://github.com/flutter/flutter/issues/108186. 

Closing from here as this is an issue with the code sample provided and there's already an existing issue asking for improvement in this behaviour. 

Thank you
