### ISSUE TITLE
Android native page embeds FlutterView, how to dynamically associate Channel names?

### ISSUE THREAD

**Issue by LanSeLianMa** [flutter/flutter#142304]
I have previously made a Flutter page embedded with Android native View. To avoid message conflicts, a unique ID is spliced when the channel is established. This unique ID is automatically generated by the AndroidView control provided by Flutter. The Android native side will provide it after inheriting PlatformViewFactory. The callback obtains the unique ID passed by Flutter and completes the dynamic association of MethodChannels at both ends.

Flutter Code

```
AndroidView(                    
	onPlatformViewCreated: (viewId) {
               initChannel(viewId)
               ... ...       
	},
)

initChannel(int viewId) {
        channel = MethodChannel('flutter.mix.android/compute/$viewId')
}
```

Android Code

```
class TestPlatformFactory(private val messenger: BinaryMessenger) : PlatformViewFactory(StandardMessageCodec.INSTANCE) {    

    override fun create(context: Context, viewId: Int, args: Any?): PlatformView {

        channel = MethodChannel(messenger, "flutter.mix.android/compute/$viewId")
	... ... 
    }

}
```

Currently, I am doing the opposite operation, embedding FlutterView in the Android native page, but I don’t know how to complete the dynamic association of the Channels at both ends. Is there any relevant guidance document?

**Comment by darshankawar** [comment]
@LanSeLianMa 
Can you take a look at https://docs.flutter.dev/add-to-app#add-to-android-applications and check if it helps ?

**Comment by LanSeLianMa** [comment]
After reading these documents, I still haven't found any relevant solutions, but thank you very much for your help. I decided not to think about this problem for the time being.
