### ISSUE TITLE
Responsive dialog layout

### ISSUE THREAD

**Issue by mbfakourii** [flutter/flutter#142310]
### Use case

According to the [Responsive layout](https://m3.material.io/components/dialogs/guidelines#9d723c7a-03d1-4e7c-95af-a20ed4b66533). I suggest adding responsive layout dialog to [`Dialog.fullscreen`](https://api.flutter.dev/flutter/material/Dialog/Dialog.fullscreen.html) and [`Dialog`](https://api.flutter.dev/flutter/material/Dialog/Dialog.html).

### Proposal

For example, if the screen is the size of a phone, `Dialog.fullscreen` should be used, otherwise, `Dialog` should be used on large screens.

<img width="1865" alt="kunfkmu6-Full to max - 3P (3)" src="https://github.com/flutter/flutter/assets/20955005/ce1ef210-1406-409f-bff7-b848e68a8cd6">

**Comment by huycozy** [comment]
Hi @mbfakourii 
Does this proposal specify for `showDialog()`? I think this should be described in detail as https://github.com/flutter/flutter/issues/133946. 

This also seems to be related to https://github.com/flutter/flutter/issues/142343.

**Comment by mbfakourii** [comment]
My proposalis somewhat similar to #133946, but it is not related to `Dialog.fullscreen`.

**Comment by huycozy** [comment]
IMO, I'm more inclined to https://github.com/flutter/flutter/issues/142343 as it's like a foundation for this. #133946 proposes for model only, not dialog. So I would suggest you follow https://github.com/flutter/flutter/issues/142343 for updates. If you think this should be a separate issue for dialog, please be more specific (similar to how #133946 was described). Thanks!
